### ISSUE TITLE
Can't connect with Postman using a authentication

### ISSUE THREAD

**Issue by profjefferson** [strapi/strapi#1000]
When i do a request with postman this error occur:

{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Unauthorized"
}

when i choose basic auth, and pass a user and password created in the GUI Admin Panel, this error occur:

{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Invalid token."
}

i dont know how to create a token, i dont see any option in the GUI Admin to create this token, what could be?

**Comment by lauriejim** [comment]
Hello @profjefferson can you check the documentation https://strapi.io/documentation/guides/authentication.html

**Comment by profjefferson** [comment]
I readed the documentation before, but now i can get the token with postman, was a mistake with params, thank you!

**Comment by jezperp** [comment]
Had this same problem, fixed by setting Body to x-www-form-urlencoded and using the params "identifier" and "password"
