### ISSUE TITLE
Strapi analytics harvests user email and name

### ISSUE THREAD

**Issue by buddudevelopers** [strapi/strapi#10001]
### Describe the bug

Strapi analytics seems to harvest user email and user names. This is sensitive personally identifiable information that could be misused if in the wrong hands. Unfortunately its [not declared in the data collected ](https://strapi.io/documentation/developer-docs/latest/getting-started/usage-information.html#collected-data)

### Steps to reproduce the behavior

1. Go to '$STRAPI_ROOT/node_modules/strapi-admin/src/containers/AuthPage/index.js'
```
      if (
        (authType === 'register' && modifiedData.userInfo.news === true) ||
        (authType === 'register-admin' && modifiedData.news === true)
      ) {
        axios({
          method: 'POST',
          url: 'https://analytics.strapi.io/register',
          data: {
            email: user.email,
            username: user.firstname,
          },
        });
      }
```

### Expected behavior

Not to collect sensitive information in strapi analytics

### System

- Node.js version: node v10.19.0 
- NPM version:
- Strapi version: 3.5.4 (node v10.19.0)
- Database: mariadb
- Operating system: Ubuntu-20.04 under wsl

**Comment by soupette** [comment]
Hello @buddudevelopers, we are only "harvesting" these informations if the user consents to.
As you can see in the code example you have provided, the `modifiedData.userInfo.news === true` condition makes sure that the user granted us the authorisation to send him an email.

**Comment by derrickmehaffy** [comment]
> Hello @buddudevelopers, we are only "harvesting" these informations if the user consents to.
> As you can see in the code example you have provided, the `modifiedData.userInfo.news === true` condition makes sure that the user granted us the authorisation to send him an email.

Specifically this information is only sent if you check the box on the main admin register page: 

![image](https://user-images.githubusercontent.com/8593673/114228152-d966c800-992a-11eb-8334-5ae0fbad4831.png)

While the endpoint is stating our our analytics server, that server is used as a relay and this information isn't sent to our actual analytics platform and is instead sent to marketing for things like our weekly newsletter.

![image](https://user-images.githubusercontent.com/8593673/114228371-2fd40680-992b-11eb-9fca-0e7ee74a0941.png)

(Search for emails from hi@strapi.io and hit unsubscribe if you don't want these or want to have your data deleted there is an option to manage your preferences on those emails).

![image](https://user-images.githubusercontent.com/8593673/114228464-4c703e80-992b-11eb-92a7-5a6c633b02bd.png)

**Comment by akhilmhdh** [comment]
Just adding it here:

[About reasons and how to opt out from data collection](https://strapi.io/documentation/developer-docs/latest/getting-started/usage-information.html)

**Comment by derrickmehaffy** [comment]
We are still doing this here: https://github.com/strapi/strapi/blob/9afe470cbf2a37c9ea90a5fd904395ef9bd2cd57/packages/core/admin/admin/src/pages/UseCasePage/index.js#L81-L93

Need to consult the team as this data isn't listed on the docs page: https://docs.strapi.io/developer-docs/latest/getting-started/usage-information.html

**Comment by yanniskadiri** [comment]
Documentation has been updated through [this PR](https://github.com/strapi/documentation/pull/1085), I'm closing this issue.
