### ISSUE TITLE
Authorization Bearer is set and API is public - strapi graphql returns null

### ISSUE THREAD

**Issue by alexchudnovsky** [strapi/strapi#10012]
If an api end point is made public and the graphql query sets an Authorization header the result returned is always null.

I am not 100% sure if this is a bug or it was intended this way, but I had spent hours on working out what the issue was, so I thought I would put it out here.

### Steps to reproduce the behavior

Create any end point in Strapi and make the endpoint public 

Then use Axios and add headers: { Authorization: Bearer xxxx }

The api will return null

### Expected behavior

As the API is public - it should work correctly without returning null, or at least display an error message saying, that the API is public, do not use an Authorization token.

### System

- Node.js version: client v12.14.1 /  strapi v14.15.2)
- NPM version: 6.14.11
- Strapi version:  3.4.0
- Database: 0.5.8-MariaDB-1:10.5.8+maria~focal - mariadb.org binary distribution
- Operating system: Docker - strapi/strapi

**Comment by alexchudnovsky** [comment]
I should just make a note, the Authorization token, needs to be a valid session token - for this to occur

**Comment by akhilmhdh** [comment]
@aleksandryackovlev  Were u using draft system in collection builder. If yes, you need to make it publish in content manager to make it available. 

I just tested it and its working fine for me.

**Comment by alexchudnovsky** [comment]
The draft system is disabled... if that is the case not sure why it's happening here..

**Comment by derrickmehaffy** [comment]
If a JWT (authorization header) is sent then the request is no longer public and it's automatically an authorized request (assuming the token is valid and the user has permissions to view).

You are correct that it should return an error.

**Comment by alexchudnovsky** [comment]
Thank you for the confirmation :)

**Comment by derrickmehaffy** [comment]
Marking as closed as this is intended
