### ISSUE TITLE
Server wasn't able to start properly. Error: Duplicated collection name.

### ISSUE THREAD

**Issue by GinRyan** [strapi/strapi#10019]
### Describe the bug

I created two collections named "categories" and "category" successfully, but errors occurred after restarting server.

```
[2021-04-12T12:51:47.758Z] debug ⛔️ Server wasn't able to start properly.
[2021-04-12T12:51:47.760Z] error Error: Duplicated collection name: `categories`.
The same collection name can't be used for two different models.
First found in API `categories`, model `categories`.
Second found in API `category`, model `category`.
    at C:\Users\Xelloss\Documents\strapi\kickstart-project\node_modules\strapi-database\lib\validation\check-duplicated-table-names.js:55:13
    at Array.forEach (<anonymous>)
    at checkDuplicatedTableNames (C:\Users\Xelloss\Documents\strapi\kickstart-project\node_modules\strapi-database\lib\validation\check-duplicated-table-names.js:47:18)
    at validateModelSchemas (C:\Users\Xelloss\Documents\strapi\kickstart-project\node_modules\strapi-database\lib\validation\index.js:7:3)
    at DatabaseManager.initialize (C:\Users\Xelloss\Documents\strapi\kickstart-project\node_modules\strapi-database\lib\database-manager.js:34:5)
    at Strapi.load (C:\Users\Xelloss\Documents\strapi\kickstart-project\node_modules\strapi\lib\Strapi.js:339:19)
    at async Strapi.start (C:\Users\Xelloss\Documents\strapi\kickstart-project\node_modules\strapi\lib\Strapi.js:191:9)
```

### Steps to reproduce the behavior
0. Create new strapi project using command `strapi new kickstart-project` and setup user;
1. Create new collection type named 'categories' in Content Type Builder and save;
2. Create new collection type named 'category' in Content Type Builder and save;
3. Restart server.
4. Error occurred and error tips printed(error message shows above).

### Reproduce probability

> 100%

### Expected behavior

The same collection name can't be used for two different models.But currently  I can create both  `categories`  and `category` collection name and save.

If `categories`  and `category` are regarded as the same model, there should be a break tip after step 2, and remind me to prevent.

Otherwise,  don't regard `categories`  and `category`  as the same model and don't check duplicated table on starting stage. Once collections `categories`  and `category` are both in database, server can't be started and there's no rescue method to save my work. 

### System

- Node.js version: 14.15.4
- NPM version: 6.14.10
- Strapi version: 
    "knex": "0.21.18",
    "sqlite3": "5.0.0",
    "strapi": "3.5.4",
    "strapi-admin": "3.5.4",
    "strapi-connector-bookshelf": "3.5.4",
    "strapi-plugin-content-manager": "3.5.4",
    "strapi-plugin-content-type-builder": "3.5.4",
    "strapi-plugin-documentation": "3.5.4",
    "strapi-plugin-email": "3.5.4",
    "strapi-plugin-graphql": "3.5.4",
    "strapi-plugin-upload": "3.5.4",
    "strapi-plugin-users-permissions": "3.5.4",
    "strapi-utils": "3.5.4"

- Database: sqlite
- Operating system: Windows 10 20H2 19042.870

**Comment by derrickmehaffy** [comment]
@strapi/maintainers maybe we should be passing the model through a pluralize.singular and check that for duplicates until we can remove pluralize entirely.

**Comment by TheSeally** [comment]
Hello. Can I take this issue?
As for the implementation, I want to add one more check before creating the collection, which will cast the name to a singular number and check in already created collections

**Comment by derrickmehaffy** [comment]
I'd say that @strapi/maintainers probably need to see if this is something we are already going to do in the v4.

**Comment by merc74** [comment]
This bug extends to Single Type, if you try to create a Single Type of the same name as a collection the server will not restart. I guess this is a beginner issue, more advanced users will not fall into those issues.

[2021-05-18T09:50:32.155Z] debug ⛔️  Server wasn't able to start properly.
[2021-05-18T09:50:32.157Z] error Error: Duplicated collection name: `XXXX`.
The same collection name can't be used for two different models.

Those errors should be shown to the user on the interface. The user should be presented with the option to continue or cancel his action. Because once you made the mistake, then you need to manually delete the models that were created, the server will not restart until you fix it.

**Comment by derrickmehaffy** [comment]
should be fixed in v4 as both the content-type builder and the generator won't let you create duplicate content-types. You would have to do this manually and we can't prevent that.
