### ISSUE TITLE
Extremely Large download file size for "url/admin/auth/login"

### ISSUE THREAD

**Issue by Utkarsh-Kumar384** [strapi/strapi#10029]
## Bug report

Strapi takes almost forever to load the /admin route.

### Describe the bug

I am not entirely sure if it's a bug or if there is some issue with my code as I am deploying a strapi project for the first time. However, once I deployed my project to heroku and tried to load the "/admin" or the "/admin/auth/login"  route the page takes almost 1-2min to load the page.

### Steps to reproduce the behavior

Currently, I haven't tried to reproduce the issue in a fresh strapi project due to deadlines approaching very near. However, If anyone tried to reproduce the issue can update the issue and it would be greatly appreciated. I too will try to reproduce the issue once I'm done with the whole project.

### Expected behavior

Expected to load the webpage under 10 -15 seconds.

### Screenshots

![image](https://user-images.githubusercontent.com/65641566/114504737-24e1e480-9c51-11eb-90ba-2277b70b5201.png)

### System

- Node.js version: 12.18.3
- NPM version: 6.14.8
- Strapi version: 3.5.4
- Database: Mongodb
- Operating system: Windows 10 

### Possible Fix

Maybe trying to implement code splitting in webpack might just fix the issue? Haven't checked the source code as of now. It's just an idea that struck my head.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7439
