### ISSUE TITLE
ctx.state.user not populated with GraphQL via middleware

### ISSUE THREAD

**Issue by tention** [strapi/strapi#10027]
### Describe the bug

I am trying to setup a middleware for audit logging and found out that ctx.state.user is not returned for GraphQL request, only works when using REST.

### Steps to reproduce the behavior

1. Create a new middleware "/audit/index.js" with the following codes and enable in config
2. Call any REST API using normal authenticated user, you will see the user information being returned.
3. Try again using GraphQL using normal authenticated user, you will receive undefined.

### Expected behavior

GraphQL should return the user information, similar to REST

### Code snippets

```
module.exports = (strapi) => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        await next();

        if (ctx.state) {
          console.log(ctx.state.user);
        }
      })
    },
  }
}
```

Following are the output from console.log(ctx.state) if it helps.
```
{
  session: <ref *1> Session {
    _sessCtx: ContextSession {
      ctx: [Object],
      app: [Object],
      opts: [Object],
      store: undefined,
      session: [Circular *1]
    },
    _ctx: {
      request: [Object],
      response: [Object],
      app: [Object],
      originalUrl: '/graphql',
      req: '<original node req>',
      res: '<original node res>',
      socket: '<original node socket>'
    },
    isNew: true
  },
  _passport: {
    instance: Authenticator {
      _key: 'passport',
      _strategies: [Object],
      _serializers: [],
      _deserializers: [],
      _infoTransformers: [],
      _framework: [Object],
      _userProperty: 'user',
      _sm: [SessionManager],
      Authenticator: [Function: Authenticator],
      Passport: [Function: Authenticator],
      Strategy: [Function],
      strategies: [Object],
      KoaPassport: [class KoaPassport extends Authenticator]
    }
  }
}
```

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.6
- Database: Postgres
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Related to: https://github.com/strapi/strapi/issues/9159

**Comment by kasonde** [comment]
Resolvers currently do not call users-permissions policy. A work-around for this would be to get the user from the token that's attached to each request you make i.e

```
module.exports = (strapi) => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        await next();
        if (
          ctx.request &&
          ctx.request.header &&
          ctx.request.header.authorization
        ) {
          try {
            const { id } = await strapi.plugins[
              "users-permissions"
            ].services.jwt.getToken(ctx);
            if (id === undefined) {
              return ctx.forbidden(
                "Invalid token: Token did not contain required fields"
              );
            }
            // fetch authenticated user
            ctx.state.user = await strapi.plugins[
              "users-permissions"
            ].services.user.fetchAuthenticatedUser(id);
          } catch (err) {}
          console.log(ctx.state.user);
          console.log(ctx.request);
        }
      });
    },
  };
};
```

**Comment by robbyemmert** [comment]
This would be an easy add to core.

**Comment by derrickmehaffy** [comment]
Works fine in v4 (though you need to build the custom graphQL middlewares: 
![image](https://user-images.githubusercontent.com/8593673/179313075-3d2de7be-ff01-4e79-bdcd-f8503f7062c0.png)

Likewise you have the GraphQL context: 
![image](https://user-images.githubusercontent.com/8593673/179313223-84e09591-3690-498a-ba40-08f29d2e62ca.png)

And access to the koaContext as well:
![image](https://user-images.githubusercontent.com/8593673/179313291-c0a388bf-b6e1-470f-80e5-0964aed269ad.png)

Marking this issue as closed as it works fine in GraphQL
