### ISSUE TITLE
permission denied, open '.strapi-updater.json'

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#10032]
## Bug report

After updating to Strapi version 3.3.0, I can't get it to run on my server.
If I do `npm run develop`, I get this error:
```bash
error Error: EACCES: permission denied, open '.strapi-updater.json'
```
If I do `npm run start`, I get this error:
```bash
error Error: EACCES: permission denied, open '.strapi-updater.json.4145631741'
```
`.strapi-updater.json` does exist, `.strapi-updater.json.4145631741` does NOT exist. 
The files permission is `-rw-------`, so I have tried to change it to `rw-r--r--` (`chmod 644`), but it still doesn't work. 

### Steps to reproduce the behavior

1. Update from version x --> 3.3.0 (where .strapi-updater.json is introduced) 
2. Run your project

**This behaviour is on my remote server, it does still work on my local machine.**

### Expected behavior

Run the same way as on my local machine

### System
- Node.js version: v12.22.1
- NPM version: 6.14.12
- Strapi version: 3.3.0
- Database: Postgres
- Operating system: Ubuntu 20.04.2

**Comment by derrickmehaffy** [comment]
How are you running Strapi (under what user) and who owns the the project directory?

**Comment by baermathias** [comment]
@derrickmehaffy user and group was were both root, I changed both to the username `sudo chown -v username:username /path/to/project`, no it works. Closing this issues, thanks!
