### ISSUE TITLE
Throwing CORS error for downloading attachments on MediaLibrary from AWS S3 bucket

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#10044]
## Bug report
CORS error for downloading attachments on MediaLibrary from AWS S3 bucket though required CORS configuration is added to S3 bucket.

### Describe the bug

We migrated our Strapi app to AWS, we are not able to download attachments from Media Library, from AWS S3 bucket. 
It's throwing CORS error.

### Error:
Access to XMLHttpRequest at '<S3_bucket>.<S3_region>.amazonaws.com/<file_name>.jpeg' from origin '<our_domain>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Steps to reproduce the behavior

1. Run Strapi app connecting to AWS S3 Bucket and Mongo DB.
2. Open Media Library and upload attachments/images
3. Open any attachment and try to Download it
3. Throws CORS error 

### Expected behavior

Attachments from Media Library, S3 bucket can be Downloaded.

### Help needed:

**Note:** We have added required CORS configuration on our S3 Bucket. 

### System

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo
- Operating system: MAC

**Comment by derrickmehaffy** [comment]
Confirmed on v3.5.4 with the following CORS error (default CORS config): 

> Reason: CORS header 'Access-Control-Allow-Origin' missing

To reproduce:

1. Create a strapi application
2. configure AWS-S3 provider
3. Start application
4. Upload one image to media library
5. Try to download image from media library
6. See error in browser debug menu

![image](https://user-images.githubusercontent.com/8593673/114908154-aad86980-9dd0-11eb-9c29-95996cff9860.png)

![image](https://user-images.githubusercontent.com/8593673/114908354-dfe4bc00-9dd0-11eb-909b-9c967225b291.png)

**Comment by vinod77** [comment]
@derrickmehaffy You are Awesome..

Thank you for updating detailed notes for reproducing the issue. Yes, we see the same CORS error.
Could you please expedite this issue or provide us any workaround to fix it because it's blocking our AWS Kube release. And we want downloading attachments to work on the Media Library.

Thanks!
Vinod

**Comment by derrickmehaffy** [comment]
@vinod77 we can't expedite issues but I will directly mention this to our engineering team.

**Comment by alexandrebodin** [comment]
Hi, In S3 you should be configuring the Cors rules. In your bucket go to Permissions > Cors > edit

Here is a simple example to allow the cors with the localhost:1337 url:

```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "http://localhost:1337"
        ],
        "ExposeHeaders": []
    }
]
```

Here is the reference to the aws cors configuration https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html

**Comment by vinod77** [comment]
Hi @alexandrebodin Thank you for the response.

I already configured CORS configuration on my AWS S3 bucket as you mentioned above, but i am still getting CORS error and not able to Download any attachments from Media Library.

Have you tried reproducing this issue after Configuring with above CORS rules?
CC: @derrickmehaffy

**Comment by derrickmehaffy** [comment]
@vinod77 can you share your configured rules (exclude any private information) as we will need to document the proper configuration once we find the root cause.

**Comment by alexandrebodin** [comment]
I haven't been able to reproduce sadly. Right now with this simple rule I'm all good. FYI I have been testing with a public bucket. If you can share the permission conf of your bucket (no name or anything) so I can set it up the same way that would help a lot

**Comment by vinod77** [comment]
Hi @alexandrebodin 

I am able to reproduce this issue on latest Strapi v3.5.4 as well. Actually this issue is happening intermittently.

I installed Strapi `v3.5.4` app and i made only 2 changes:

1. Installed this Plugin:  https://www.npmjs.com/package/strapi-provider-upload-aws-s3
2. Added `config/plugins.js` file with code as mentioned on this plugin with my own S3_Bucket credentials:  `accessKeyId`, `secretAccessKey`, `region` & `Bucket`

**When it works:**
1. Run the local Strapi app connecting to your S3 bucket
2. Upload any images on to Media Library
3. Open any image, wait for some time
4. Now Download it- It works

**When it breaks**
1. Restart the local server. 
2. Now try to Download any of the same images uploaded earlier - It breaks..

**Note:** Here when you upload a new image now & Download it - It works

**S3 CORS configuration i have:**
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "http://localhost:1337",
            "http://localhost:1337/admin"
        ],
        "ExposeHeaders": []
    }
]
```

You can try reproducing it with above steps..
You can try to connect to my own S3 bucket and verify, (I can share you my own S3 bucket credentials separately)

Thanks!

CC: @derrickmehaffy, @alexandrebodin

**Comment by derrickmehaffy** [comment]
@alexandrebodin working with @vinod77 in a PM on Slack I was able to reproduce it even with a proper CORs config in AWS-S3. There is something to do with browser cache, if you open up the chrome dev tools network tab and hit disable cache it works fine, but if you uncheck the disable cache and refresh the page and try to download it will fail every time due to a cors error.

I'm guessing this is something to do with the frontend admin panel @soupette

**Comment by vinod77** [comment]
**+1** for @derrickmehaffy 

Thank you @derrickmehaffy for taking the time to work with me on this issue and to reproduce it. You are very helpful.

Hi @alexandrebodin, @soupette Could you please address this issue ASAP? It's actually blocking our AWS migration/release.

Thank you for the Support!

**Comment by alexandrebodin** [comment]
Hi, You need to add the exposeHeader like follows :) 

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "http://localhost:1337"
        ],
        "ExposeHeaders": [
            "Access-Control-Allow-Origin"
        ]
    }
]
```

**Comment by vinod77** [comment]
Hi @alexandrebodin I tried/tested by adding `"Access-Control-Allow-Origin"` in `"ExposeHeaders"` but it still throwing the same **CORS** error.

Below is my new CORS configuration:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE"
        ],
        "AllowedOrigins": [
            "http://localhost:1337",
            "http://localhost:1337/admin"
        ],
        "ExposeHeaders": [
            "Access-Control-Allow-Origin"
        ]
    }
]
```
As @derrickmehaffy mentioned, It's working with only 1 workaround: by enabling `Disable Cache` in the Network Tab.

CC: @derrickmehaffy , @alexandrebodin , @soupette

**Comment by alexandrebodin** [comment]
I have left cache enabled while testing this solution actually. Can you share the exact error you are receiveing right now please ?

**Comment by vinod77** [comment]
Hi @alexandrebodin I am running core Strapi `v3.5.4` app, connecting to my own AWS S3 bucket (having above CORS configs), I can also share my S3 bucket credentials separately to you (Derrick has it).

Please see below attached screenshots for the CORS error:

<img width="1782" alt="Strapi-Media_Library-CORS-error1" src="https://user-images.githubusercontent.com/23507845/115752787-1043d180-a360-11eb-9427-cdde8908174c.png">

<img width="1782" alt="Strapi-Media_Library-CORS-error2" src="https://user-images.githubusercontent.com/23507845/115752806-15088580-a360-11eb-956f-e4eec9dd4ff4.png">

<img width="1782" alt="Strapi-Media_Library-CORS-error3" src="https://user-images.githubusercontent.com/23507845/115752824-1a65d000-a360-11eb-85df-07ca099889c1.png">

Thank you team for your time/efforts/support on this issue.

CC: @derrickmehaffy , @alexandrebodin , @soupette

**Comment by d2kx** [comment]
Just wanted to say that we have been suffering from the same issue.

S3 is configured properly, we have been using the service for years within other projects.

We also noticed that it works when Chrome/Edge is set to "disable cache" in the browser devtools' network tab. My guess is some misconfiguration in the HTTP client (axios? fetch?) in the admin frontend.

**Comment by alexandrebodin** [comment]
> Just wanted to say that we have been suffering from the same issue.
> 
> S3 is configured properly, we have been using the service for years within other projects.
> 
> We also noticed that it works when Chrome/Edge is set to "disable cache" in the browser devtools' network tab. My guess is some misconfiguration in the HTTP client (axios? fetch?) in the admin frontend that prevents the pre-flight request (HTTP OPTIONS) from happening.

Possible yes We will have a look. @soupette can you check the credentials option we have set on the download request ?

**Comment by ALICIALVO** [comment]
I was encountering with the same CORS issue : "Access to fetch at 'https://bucket-chat-name.s3.region-1.amazonaws.com/010110101001-011010110101-contactus%30(2).jpg' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." This error was when i was trying to download the image from S3 the upload worked great. I tried a bunch of solutions and trying Apigateway, user, policy changes but nothing help it to work.

After long search i've found the solution in one old question someone asked about this error. It turned out that the 'access-control-allow-origin' header was nowhere to be found in the response. it happend all because of the browser caching the requests. so the solution is that you need to add the 'mode: cors' and 'cache: no-cache' options to the fetch request.

With that solution the 'origin' header got included in the request, and voilà – the CORS error was gone.
example 1:
`const response = await fetch(url, { mode: 'cors', cache: 'no-cache' });
`
example 2:
`export const downloadMedia = async (e, originalImage) => {
    e.preventDefault();

    try {
        const response = await fetch(originalImage, {
            method: 'GET',
            mode: 'cors',           // Ensures CORS is handled
            cache: 'no-cache',      // Prevents caching issues
            headers: {
                'Content-Type': 'application/octet-stream'
            }
        });

        if (!response.ok) {
            throw new Error('Failed to fetch the file');
        }

        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.style.display = "none";
        a.href = url;

        const nameSplit = originalImage.split("/");
        const duplicateName = decodeURIComponent(nameSplit.pop());

        a.download = duplicateName;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
    } catch (error) {
        console.log('Error while downloading the image', error.message);
    }
};
`
also this was my cors configuration in s3 bucket:
`[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "PUT",
            "POST",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "http://localhost:5173",
            "*"
        ],
        "ExposeHeaders": [
            "ETag",
            "Content-Length",
            "Content-Type"
        ],
        "MaxAgeSeconds": 3000
    }
] `
and bucket policy: 
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::bucket-name/*"
        }
    ]
}`
but you can use what you think is better for your usecase(:
