### ISSUE TITLE
Allow for more vertical room listing the content types in the Admin Panel

### ISSUE THREAD

**Issue by jorisw** [strapi/strapi#10040]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Allow for more vertical space for the Content Types listing in the Admin Panel

### Why is it needed?

We have many Content Types. The left pane hides most of them because of the fixed height on the Content Types listing. I don't see any reason for this fixed height, as there is plenty of room in the left pane. Because of the fixed height matching a certain amount of Content Types in height, the fact that there are more available to scroll through, also isn't clear (at least on Mac, where scroll bars are not visible by default until you scroll). When hiding overflow, it's better to leave the bottom visible row, only partially visible.

### Suggested solution(s)

- Remove the fixed height on the Content Types listing in the left pane
- Remove the overflow-Y setting
- If you choose to keep the fixed height, make it a fixed height that ends halfway the of bottom item (assuming single line names)

![image](https://user-images.githubusercontent.com/30017/114703109-2da3ea80-9d25-11eb-8a38-ebd33fe2a8c1.png)

**Comment by derrickmehaffy** [comment]
Fixed in v4 as we moved this into a child menu instead
