### ISSUE TITLE
Primary domain redirects to Strapi Nginx Sub-domain

### ISSUE THREAD

**Issue by tejanhu** [strapi/strapi#10054]
Hi

Whenever myself and @ebrimaconta visit the primary domain hosting Apache server (www.findmyrizq.com); it redirects to the sub-domain (cms.findmyrizq.com) that hosts Strapi on Nginx; even though they are located on two separate domains.

This seems to work fine on Google Chrome, but on other browsers, it doesn't work on Explorer nor Safari nor Firefox on all electronic devices.

Is there any advice on this issue, as we have tried numerous ways to resolve this issue?

We have also cleared the cookies and sessions and this hasn't resolved the issue either.

Thanks in advance!

![Screenshot 2021-04-15 at 23 48 02](https://user-images.githubusercontent.com/10237400/114947416-06443f00-9e45-11eb-9bc1-7b5e63cf1310.png)
![Screenshot 2021-04-15 at 23 46 41](https://user-images.githubusercontent.com/10237400/114947358-eb71ca80-9e44-11eb-9c7e-ac1baa359192.png)
![Screenshot 2021-04-15 at 23 46 21](https://user-images.githubusercontent.com/10237400/114947367-ee6cbb00-9e44-11eb-9d2a-9a50fc41cea5.png)
![Screenshot 2021-04-15 at 23 46 41](https://user-images.githubusercontent.com/10237400/114947430-0f351080-9e45-11eb-993d-5c04d7bbb4f1.png)
![Screenshot 2021-04-15 at 23 48 43](https://user-images.githubusercontent.com/10237400/114947473-1fe58680-9e45-11eb-888c-8c1ee6cd38e0.png)
![Screenshot 2021-04-15 at 23 48 59](https://user-images.githubusercontent.com/10237400/114947494-296eee80-9e45-11eb-8b75-c6b6be6c7fea.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
