### ISSUE TITLE
Getting errors installing Strapi

### ISSUE THREAD

**Issue by ChrisB007** [strapi/strapi#10051]
Hell guys, I am trying to install Strapi for my backend, but getting this error:
`error strapi-generate-new@3.5.4: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "15.9.0"
error Found incompatible module.
`

**Comment by roelbeerens** [comment]
Afaik, Strapi doesn't support uneven releases from Node. You would have to set your Node version to 14, 12 or 10 in order to start the application.

**Comment by derrickmehaffy** [comment]
Exactly @roelbeerens we don't support odd versions: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#recommended-requirements

**Comment by tonny008** [comment]
node 16 is released

**Comment by MattieBelt** [comment]
@tonny008 node 16 LTS will only start at the end of 2021.
So strapi will probably look into supporting it later this year 👍🏼 

https://nodejs.org/en/about/releases/
![image](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)
