### ISSUE TITLE
I am unable to access API routes/endpoints. 

### ISSUE THREAD

**Issue by praveenbethapudi** [strapi/strapi#1005]
Strapi is deployed in production mode.. everything looks fine.. no errors in the mongodb database either..
![image](https://user-images.githubusercontent.com/11560534/39136753-8ff123d2-4739-11e8-966f-e2016c19fbb2.png)

Guest role is active with one user and permissions for the collection are set properly..
![image](https://user-images.githubusercontent.com/11560534/39137143-83555b7e-473a-11e8-8902-aa712670d054.png)

it says unauthorised.. wont let me access any of the api endpoints.. I am able to login using postman.. but it wont allow me to access endpoints.. same issue..
![image](https://user-images.githubusercontent.com/11560534/39137562-8c0e2678-473b-11e8-9029-8c0fd715c926.png)
...
![image](https://user-images.githubusercontent.com/11560534/39137259-d017ed0a-473a-11e8-803a-42c9d1188bad.png)

tried everything.. but it just wont call the controller when the route is engaged..

what am I missing??
is there a way to access routes without authentication?
if so have I created the Guest role correctly?

I am running Mongodb 3.6, strapi 3.0.0-alpha.11.3 on node v9.11.1

**Comment by lauriejim** [comment]
Can you log in this file if role and permission is well detected for what you want https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js
