### ISSUE TITLE
Facebook provider error in production but working using localhost

### ISSUE THREAD

**Issue by joeldacuma** [strapi/strapi#10064]
### Describe the bug

Facebook provider is working when my URL in server.js is http://localhost:1339 but when I deployed it in heroku using my production URL it generates error when I tried to request https://mywebsite-api.com/connect/facebook:

![image](https://user-images.githubusercontent.com/20335287/115135165-c9e13080-a048-11eb-9621-0047e7487424.png)

![image](https://user-images.githubusercontent.com/20335287/115135449-188fca00-a04b-11eb-8913-fb080ee6a683.png)

### Steps to reproduce the behavior
1. Added my domain to facebook developer
2. GET request https://mywebsite-api.com/connect/facebook

### Expected behavior

Should return facebook auth json

### Code snippets

server.js:
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1339),
  url: 'http://mywebsite-api.com',
  cron: {
    enabled: true
  },

### System

- Node.js version: 15.14.0
- NPM version: 7.10.0
- Strapi version: 3.1.6
- Database: Postgres
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
> change facebook callback url from localhost to heroku

Exactly @joeldacuma you need to include the heroku domain in Facebook's approved callback URLs.

See: https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#facebook-configuration

Specifically:

> Valid OAuth Redirect URIs
