### ISSUE TITLE
fresh admin `npm start` throwing syntax error

### ISSUE THREAD

**Issue by kitsunekyo** [strapi/strapi#1006]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: mongodb
- **Operating system**: windows 10 x64

**What is the current behavior?**

running npm start after installing `./admin` throws an error

```
$ npm start

> strapi-admin@3.0.0-alpha.12.0.1 start D:\Users\aspieslechner\Documents\Projects\gvc\repo\strapi\admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'D:\Users\aspieslechner\Documents\Projects\gvc\repo\strapi\admin\node_modules\strapi-helper-plugin\node_modules\.bin\cross-env'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.0.1 start: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aspieslechner\AppData\Roaming\npm-cache\_logs\2018-04-23T17_29_33_403Z-debug.log
```

**Steps to reproduce the problem**

followed the tutorial

`strapi new strapi` -> success

- plugin settings-manager has been successfully installed
- plugin content-manager has been successfully installed
- plugin users-permissions has been successfully installed
- plugin email has been successfully installed
- plugin upload has been successfully installed
- plugin analytics has been successfully installed
- info linking strapi dependency to the project
- info your new application is ready at PATH

`cd strapi` and `npm install` -> success (added 1644 packages in 200.836s)

`npm start`

**What is the expected behavior?**

admin being built for development and served at `http://localhost:4000/admin`

**Suggested solutions**

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by soupette** [comment]
Hi @kitsunekyo you need to have the development environment setup in order to fully customize the admin panel.

In order to do so, you need to :
- clone the monorepo : `git clone git@github.com:strapi/strapi.git`.
- run `cd strapi && npm run setup`.
- create a new Strapi project : `strapi new my-app --dev`.
- launch the strapi server : `cd my-app && strapi start`.
- add the `strapi-helper-plugin` dependency to the `analytics` plugin `cd my-app/plugins/analytics && npm link strapi-helper-plugin`.
- launch front end dev server : `cd my-app && npm start`.

After that you should be good to go!

**Comment by kitsunekyo** [comment]
thanks @soupette 

thats my bad. i overlooked the [https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md](https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md) link as it was not my intent to Contribute, but just to adapt the admin section for my usecase.

**Comment by soupette** [comment]
I understand. We have guides in our **[documentation](https://strapi.io/documentation/advanced/customize-admin.html)** to customize the *'basics'* things in the admin... However, if you want to make deeper changes you have to use the development mode *[CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md)*.

🏗 ***PRs** are welcome ! 🏗

**Comment by kitsunekyo** [comment]
if i have something that might be of use for others, of course ;) thanks again
