### ISSUE TITLE
Webpack server side

### ISSUE THREAD

**Issue by alex-eri** [strapi/strapi#10065]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Webpack server side to reduce deploy time and disk space

### Why is it needed?

I want to deploy it on clients local machine, but node_modules is too big for little app. Also it helps deploy app to hosting and CI. Less downtime.

### Suggested solution(s)

Some docs, webpack configurations is needed. Also workarounds to fix generated errors.

### Related issue(s)/PR(s)

Now it fails to start with:

```
[eri@eri-macro kiosk]$ node strapi.bundle.js 
undefined:14
"production" = "production" || false;
^^^^^^^^^^^^

SyntaxError: Invalid left-hand side in assignment
    at Object../node_modules/strapi/lib/core/app-configuration/index.js (/mnt/data/Projects/2021/cms/nuxt/kiosk/strapi.bundle.js:11756:1)
    at __webpack_require__ (/mnt/data/Projects/2021/cms/nuxt/kiosk/strapi.bundle.js:21:30)
...
```

Then i resolve it there is anothers errors. Now with json loading.

**Comment by derrickmehaffy** [comment]
There is currently no means to "build" the backend with koa (what is used) to create a minified version. 

Marking as closed as right now it's just not possible and we don't plan to find alternatives to this.
