### ISSUE TITLE
Community translations with Crowdin

### ISSUE THREAD

**Issue by jsamr** [strapi/strapi#1007]
*ENABLE COMMUNITY TRANSLATIONS WITH [CROWDIN](https://crowdin.com/)*  

[Crowdin](https://crowdin.com/) allows easy translations from the community, [free for OS projects after submitting a request](https://crowdin.com/page/open-source-project-setup-request). I've contributed recently to few projects for french translations and I found it very user friendly and efficient. Would be glad to contribute to this one when you have crowdin setup.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
I will take a look. Thank you for the link.

**Comment by scipe** [comment]
+1

**Comment by derrickmehaffy** [comment]
+1

**Comment by Aurelsicoko** [comment]
It looks awesome! I don't think there is a major issue with the translation in Strapi at this time. However, we should keep in mind that we have to switch on a more conventional way to manage them in the future.

**Comment by jsamr** [comment]
@Aurelsicoko I don't unfortunately :-)

Je n'avais pas réalisé que c'était un projet français ! Un beau projet, bravo à l'équipe.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko https://www.oneskyapp.com/

**Comment by Aurelsicoko** [comment]
@derrickmehaffy OneSkyApp seems to be a service to translate the content with their own translators. This is not what we are looking for 🙈

**Comment by lauriejim** [comment]
@jsamr Can you give project you contribute with crowdin please.

**Comment by jsamr** [comment]
@lauriejim [Tab session manager](https://crowdin.com/project/tab-session-manager)

**Comment by lauriejim** [comment]
Thank you @jsamr  !

**Comment by Aurelsicoko** [comment]
I'm closing it because we created our own automatic system to handle translations with GitHub issues. It works pretty well right now. After discussions with the core team, we don't feel necessary to switch to Crowdin or others similar solutions. We'll reopen this issue if needed. Thanks for the proposal 👍
