### ISSUE TITLE
Normalize created_at and updated_at fields

### ISSUE THREAD

**Issue by luixal** [strapi/strapi#10082]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

**DISCLAIMER**: this FR can be related to the [Database Layer (v4)](https://portal.productboard.com/strapi/1-roadmap/c/73-database-layer-v4) already planned in  ProductBoard.

Usually, I start working on a new Strapi project working with the bookshelf storage connectors, it makes things simpler for starting up. When the project evolves and starts needing custom database queries is when I choose the database I'm using (usually it's already chosen but sometimes you can change your mind in early stages).

When moving from bookshelf to mongodb all the standard queries to the API using `created_at` or `updated_at` filters have to be replaced by `createdAt` or `updatedAt`.

It would make sense the those fields are normalize and have the same name accross databases. Or maybe at the API level, but you will face the same problem if you're using them in your custom queries in Strapi.

### Why is it needed?

It's a pain moving from one database to anohter.

### Suggested solution(s)

Take it into consideration in the [Database Layer (v4)](https://portal.productboard.com/strapi/1-roadmap/c/73-database-layer-v4) already planned in  ProductBoard.

### Related issue(s)/PR(s)

None that I found.

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed as we will be dropping all support for MongoDB in the future with Strapi v4 which would make this feature request as redundant since all SQL databases use the underscore.

https://github.com/strapi/strapi/issues/10186
