### ISSUE TITLE
Sharp package Heroku deployment issue

### ISSUE THREAD

**Issue by edmoura** [strapi/strapi#10093]
Can anyone help me with this, I am trying to deploy my Strapi app on Heroku and I am getting this error. Yesterday it was fine.

remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: heroku/nodejs
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        USE_YARN_CACHE=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=staging
remote:        NODE_MODULES_CACHE=false
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  >=10.0.0
remote:        engines.npm (package.json):   >=6.0.0
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version >=10.0.0...
remote:        Downloading and installing node 16.0.0...
remote:        Bootstrapping npm >=6.0.0 (replacing 7.10.0)...
remote:        npm >=6.0.0 installed
remote:        Resolving yarn version 1.22.x...
remote:        Downloading and installing yarn (1.22.10)
remote:        Installed yarn 1.22.10
remote:
remote: -----> Restoring cache
remote:        Caching has been disabled because NODE_MODULES_CACHE=false
remote:
remote: -----> Installing dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.22.10
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        warning url-loader@1.1.2: Invalid bin field for "url-loader".
remote: dependency and failed compatibility check. Excluding it from installation.
remote:        info fsevents@1.2.13: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > request-promise@4.2.6" has unmet peer dependency "request@^2.34".
remote:        warning "request-promise > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
remote:        warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
remote:        warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
remote:        warning "strapi-admin > @buffetjs/core > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
remote:        warning " > strapi-connector-bookshelf@3.0.0-beta.20" has incorrect peer dependency "knex@^0.20.0".
remote:        warning "strapi-plugin-users-permissions > grant-koa@4.7.0" has unmet peer dependency "koa@>=0.x.x".
remote:        warning " > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.3.0".
remote:        warning " > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
remote:        [4/4] Building fresh packages...
remote:        error /tmp/build_6e548dcc/node_modules/sharp: Command failed.
remote:        Exit code: 1
remote:        Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
remote:        Arguments:
remote:        Directory: /tmp/build_6e548dcc/node_modules/sharp
remote:        Output:
remote:        info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.0/libvips-8.9.0-linux-x64.tar.gz
remote:        (node:3190) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
remote:        (Use `node --trace-deprecation ...` to show where the warning was created)
remote:        make: Entering directory '/tmp/build_6e548dcc/node_modules/sharp/build'
remote:          TOUCH Release/obj.target/libvips-cpp.stamp
remote:          CXX(target) Release/obj.target/sharp/src/common.o
remote:        <command-line>: warning: "_GLIBCXX_USE_CXX11_ABI" redefined
remote:        <command-line>: note: this is the location of the previous definition
remote:        In file included from /app/.cache/node-gyp/16.0.0/include/node/v8.h:30,
remote:                         from /app/.cache/node-gyp/16.0.0/include/node/node.h:63,
remote:                         from ../src/common.cc:22:
remote:        /app/.cache/node-gyp/16.0.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
remote:        /app/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
remote:          452 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
remote:              |                                      ^~~~~~~~~~~
remote:              |                                      remove_cv
remote:        /app/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
remote:          452 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
remote:              |                                      ^~~~~~~~~~~
remote:              |                                      remove_cv
remote:        /app/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:50: error: template argument 2 is invalid
remote:          452 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
remote:              |                                                  ^
remote:        /app/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:63: error: ‘::Perform’ has not been declared
remote:          452 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
remote:              |                                                               ^~~~~~~
remote:        make: *** [sharp.target.mk:139: Release/obj.target/sharp/src/common.o] Error 1
remote:        make: Leaving directory '/tmp/build_6e548dcc/node_modules/sharp/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_6e548dcc/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
remote:        gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
remote:        gyp ERR! System Linux 4.4.0-1088-aws
remote:        gyp ERR! command "/tmp/build_6e548dcc/.heroku/node/bin/node" "/tmp/build_6e548dcc/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_6e548dcc/node_modules/sharp
remote:        gyp ERR! node -v v16.0.0
remote:        gyp ERR! node-gyp -v v7.1.2
remote:        gyp ERR! not ok
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

my package.json 

"devDependencies": {
    "babel-eslint": "^10.0.0",
    "eslint": "^6.3.0",
    "eslint-config-airbnb": "^18.0.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-react": "^7.14.0"
  },
  "dependencies": {
    "axios": "^0.19.1",
    "firebase-admin": "^9.4.2",
    "google-play-billing-validator": "^2.1.1",
    "googleapis": "^52.1.0",
    "heroku": "^7.41.1",
    "knex": "^0.21.1",
    "lodash": "^4.17.5",
    "moment": "^2.27.0",
    "objection": "^2.1.3",
    "pg": "^8.2.0",
    "request-promise": "^4.2.5",
    "simple-encryptor": "^3.0.0",
    "sqlite3": "^4.1.0",
    "strapi": "3.0.0-beta.20",
    "strapi-admin": "3.0.0-beta.20",
    "strapi-connector-bookshelf": "3.0.0-beta.20",
    "strapi-plugin-content-manager": "3.0.0-beta.20",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20",
    "strapi-plugin-documentation": "3.0.0-beta.20",
    "strapi-plugin-email": "3.0.0-beta.20",
    "strapi-plugin-upload": "3.0.0-beta.20",
    "strapi-plugin-users-permissions": "3.0.0-beta.20",
    "strapi-provider-email-sendgrid": "^3.2.5",
    "strapi-provider-upload-cloudinary": "^3.0.0-beta.20",
    "strapi-utils": "^3.0.0-beta.20",
    "stripe": "^8.17.0",
    "uuid": "^3.4.0"
  },

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by saintego** [comment]
@edmoura I have same issue. Did you solved it somehow?

**Comment by AllAboutSunday** [comment]
@saintego Hello Man, yes I did.

on the package.json I added this lines:

 "engines": {
    "node": "14.x",
    "npm": "6.x"
  },
  
It worked for me on Heroku.
