### ISSUE TITLE
Route change does not change source files

### ISSUE THREAD

**Issue by JadenSWang** [strapi/strapi#10094]
### Describe the bug
When adding a relative path url: '/api' to server.js, if I curl localhost:1337/api/admin, I get a positive response, but the website is attempting to source from '/admin/runtime~main.a4097d31.js' which won't work since it should be at '/api/admin/runtime~main.a4097d31.js'

### Steps to reproduce the behavior
add a relative path to a clean installation of strapi

### Expected behavior
all sources should automatically reset to /newpath/filepath

###Code Snippets
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: '/api',
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '199d876ef2df3d574630a90ca704e09c'),
    },
  },
});
;

### System: Docker
version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

**Comment by derrickmehaffy** [comment]
> Public url of the server. Required for many different features (ex: reset password, third login providers etc.). Also enables proxy support such as Apache or Nginx, example: https://mywebsite.com/api. The url can be relative, if so, it is used with http://${host}:${port} as the base url. An absolute url is however recommended.

https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#server

You need to use a proxy layer such as Nginx, HAProxy, Caddy, ect as we aren't modifying the koa-router only changing a handful of internal variables that generate "public" urls and for it to be used with the admin you can't use relative URLs, we strongly recommend absolute URLs.

We have various sample configs for the proxy applications here: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#optional-software-guides

**Comment by JadenSWang** [comment]
I already have the revrse-proxy set up, I've abstracted my question out because I can already access the server at cms.domainname.com/admin, I just want it at cms.domainname.com/path/admin

**Comment by JadenSWang** [comment]
as for the absolute path recommendation, can I set the absolute path as http://localhost/path?
