### ISSUE TITLE
Strapi still doesn't properly route certain paths to the new prefix

### ISSUE THREAD

**Issue by JadenSWang** [strapi/strapi#10095]
Describe the bug
My original request was rudely closed without fully understanding the extent of my issue. I already have a reverse-proxy set up, I already have access to the /api/restaurants -> returns data

my issue is when attempting to access the admin panel at https://cms.domain.com/api/admin and I open up the console, there is an error: failed to get  https://cms.domain.com/admin/init whereas it should be looking for https://cms.domain.com/api/admin/init

I had however updated my path to be an absolute instead of relative as recommended.

I have copied over what I had  before

When adding a relative path url: '/api' to server.js, if I curl localhost:1337/api/admin, I get a positive response, but the website is attempting to source from '/admin/runtimemain.a4097d31.js' which won't work since it should be at '/api/admin/runtimemain.a4097d31.js'

Steps to reproduce the behavior
add a relative path to a clean installation of strapi

Expected behavior
all sources should automatically reset to /newpath/filepath

###Code Snippets
module.exports = ({ env }) => ({
     host: env('HOST', '0.0.0.0'),
     port: env.int('PORT', 1337),
     url: 'http://cms.domain.com/api',
     admin: {
          auth: {
               secret: env('ADMIN_JWT_SECRET', '199d876ef2df3d574630a90ca704e09c'),
          },
     },
});
;

System: Docker
version: '3'
services:
strapi:
image: strapi/strapi
volumes:
- ./app:/srv/app
ports:
- '1337:1337'

**Comment by derrickmehaffy** [comment]
> my issue is when attempting to access the admin panel at https://cms.domain.com/api/admin and I open up the console, there is an error: failed to get https://cms.domain.com/admin/init whereas it should be looking for https://cms.domain.com/api/admin/init

Dupliate: https://github.com/strapi/strapi/issues/8616

> My original request was rudely closed without fully understanding the extent of my issue. I already have a reverse-proxy set up, I already have access to the /api/restaurants -> returns data

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

Nothing rude was intended but your issue already exists and per our contribution guide:

> You have already searched for related issues, and found none open (if you found a related closed issue, please link to it from your post).

**Comment by JadenSWang** [comment]
Thank you for making it more clear that the problem is a duplicate, thats much more helpful than simply closing an issue and repeating things I already know.

**Comment by derrickmehaffy** [comment]
Your previous issue didn't have enough context to make a determination, there was no information that you were already using a proxy.

**Comment by derrickmehaffy** [comment]
future context of related issue: https://github.com/strapi/strapi/issues/10094

**Comment by JadenSWang** [comment]
so even when updating to an absolute path, there is no solution to the problem in #8681?

**Comment by derrickmehaffy** [comment]
> so even when updating to an absolute path, there is no solution to the problem in #8681?

Not currently
