### ISSUE TITLE
Impossible to understand if password input is filled or not

### ISSUE THREAD

**Issue by iksent** [strapi/strapi#10104]
### Steps to reproduce the behavior

1. Create new `Password` field for any model:

![Снимок экрана 2021-04-22 в 18 12 01](https://user-images.githubusercontent.com/32956521/115722370-5cab0380-a398-11eb-8bb0-0bd5499aebb0.png)

2. Go to item and fill that field:

![Снимок экрана 2021-04-22 в 18 12 45](https://user-images.githubusercontent.com/32956521/115722414-692f5c00-a398-11eb-829e-2dd7b7945922.png)

3. Save Item

4. Field content will be empty (immediately after saving, as well as after refreshing the page):

![Снимок экрана 2021-04-22 в 18 12 56](https://user-images.githubusercontent.com/32956521/115722469-76e4e180-a398-11eb-8281-2cafc5044f84.png)

5. So it's impossible to understand if password input is filled or not.

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 3.6.0
- Database: MySQL 5.6 and MariaDB
- Operating system: MacOS ARM

**Comment by soupette** [comment]
@iksent thank you for reporting the issue.

The password input is not returned from the API, and even though if it was you will see a hash instead of the real value. 

I agree with you we might need to display another state, but in the meantime you can add a description to your password fields so your users can know that it is an intended behaviour.

**Comment by maevalienard** [comment]
Thanks for reporting this!

I'd suggest to add a placeholder like "******" when a password is entered. It'll display a value and not feel like it's empty/missing/bugging. I'd also propose to not show the eye icon from this field, if we can't use it :)

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/impossible-to-know-if-password-is-filled-or-not
