### ISSUE TITLE
how to use the absolute url in image from rich text in gridsome

### ISSUE THREAD

**Issue by Tiramisupxl** [strapi/strapi#10103]
1. I had uploaded a image in strapi and use the image in rich text
2. I develop my site with gridsome, and render the rich text, but the image url in it is relative ,the image is not found
![image](https://user-images.githubusercontent.com/13674347/115711731-7a7f6500-a3a6-11eb-8e8d-85e6b7aa0f21.png)
how can I fixed it

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
