### ISSUE TITLE
Nested relation item won't populate in a 'Many-Many-Through' construction, only shows ID

### ISSUE THREAD

**Issue by SvenWesterlaken** [strapi/strapi#10117]
### Describe the bug

Somehow the linked object only shows as an ID after using a custom populate override (see last code snippet) when I try to query with `/timeslots`. I do include a date filter in the query params, but I don't think that is applicable for the bug.

Just to quickly explain the relationships: _A timeslot has many registrations, which holds a user & a boolean whether it is confirmed or not. Therefore a User also has many registrations which would make it a 'Many-Many-Through'-relationship for users & timeslots._

I've tried different ways of defining the populate array, like: `['registrations', 'registrations.user']`, `['registrations', 'registrations.registration.user']`, `['registrations', 'registration.user']`, `['registrations', 'registrations.user.username']`. Unfortunately, none of them seemed to work. I do know it is the right service as my code errored on the frontend whenever I remove the `'registrations'` in the populate array.

The data on the frontend for one of the queried timeslots now is:

```json5
{
   "_id":"608264bb0a3b614dcc1fbc2d",
   "draft":false,
   "max":3,
   "start":"2021-04-20T23:00:00.000Z",
   "end":"2021-04-21T00:00:00.000Z",
   "createdAt":"2021-04-23T06:10:03.277Z",
   "updatedAt":"2021-04-23T06:10:03.277Z",
   "__v":0,
   "registrations":[
      {
         "confirmed":false,
         "_id":"60826c2626d1092090f46a98",
         "createdAt":"2021-04-23T06:41:42.903Z",
         "updatedAt":"2021-04-23T07:27:06.818Z",
         "__v":0,
         "timeslot":"608264bb0a3b614dcc1fbc2d",
         "user":"605a4a377c37614d3844083d", // <-- expect this to be an object
         "id":"60826c2626d1092090f46a98"
      }
   ],
   "id":"608264bb0a3b614dcc1fbc2d"
}
```

### Steps to reproduce the behavior

1. Make a similar construction or copy the below class configurations
2. Try and query with the find service while updating the populate array

### Expected behavior

I would expect the user field to be populated with the user object instead of the ID of the user.

### Code snippets

**Registration class:**
```json
{
  "kind": "collectionType",
  "collectionName": "registrations",
  "info": {
    "name": "registration",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "user": {
      "plugin": "users-permissions",
      "model": "user",
      "via": "registrations"
    },
    "timeslot": {
      "model": "timeslot",
      "via": "registrations"
    },
    "confirmed": {
      "type": "boolean",
      "default": false
    }
  }
}
```

**Timeslot class:**
```json
{
  "kind": "collectionType",
  "collectionName": "timeslots",
  "info": {
    "name": "Timeslot",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "draft": {
      "type": "boolean"
    },
    "start": {
      "type": "datetime"
    },
    "end": {
      "type": "datetime"
    },
    "max": {
      "type": "integer"
    },
    "registrations": {
      "via": "timeslot",
      "collection": "registration"
    }
  }
}
```

**Current service for find (for timeslot)**:
```js
module.exports = {
  find(params, populate) {
    return strapi.query('timeslot').find(params, ['registrations', 'registrations.user']);
  },
};
```

### System

- Node.js version: 14.15.0
- NPM version: 6.4.8
- Strapi version: 3.5.3
- Database: MongoDB
- Operating system: Windows (MongoDB in docker container)

**Comment by OkayX6** [comment]
I have the same issue with Strapi 3.6.1
Interestingly it only happens with the user, which might have permissions tied to it?

**Comment by derrickmehaffy** [comment]
shouldn't be a problem on v4 with the new population logic, marking as closed
