### ISSUE TITLE
Can't access localization

### ISSUE THREAD

**Issue by saniokazzz** [strapi/strapi#10115]
After updating Strapi from version 3.5.4 to 3.6.0 and installing strapi-plugin-i18n, I have enabled Localization in Admin UI, added another locale, but can't see any "Internationalization" box while editing content

**Comment by saniokazzz** [comment]
It's not mentioned in documentation , or I'm missing, that internationalization should be turned on for every single content type also.

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/user-docs/latest/content-types-builder/creating-new-content-type.html#creating-a-new-content-type

**Comment by Yermolitskiy** [comment]
Localization has to be turned on on every collection/content type, also have to use yarn.develop while changing global settings.
