### ISSUE TITLE
Can not test the connection of database when create new project

### ISSUE THREAD

**Issue by laputaclover** [strapi/strapi#1011]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**:  3.0.0-alpha.12.0.1
- **Database**: MongoDB
- **Operating system**: CentOS Linux release 7.4.1708 (Core)

**What is the current behavior?**
When I followed the quick start to create a new project, it stopped at "Testiong database connection..."
I have waited for a few minutes, it didn't show any other message, even no "connection error".
I have tested the connection of MongoDB, it can be connected successfully.
I also check the log of MongoDB, there wasn't any connection from strapi.
(when I change the DB to another product-mysql server, it also stop at this step.)
The full status are as below:

[root@manager sfcms]# strapi new my-project
[2018-04-24T03:28:08.340Z] info Creating your application... It might take a few seconds.
[2018-04-24T03:28:08.418Z] info Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: strapi
 Host: 127.0.0.1
 Port: 27017
 Username: 
 Password: 
 Authentication database: 
 Enable SSL connection: false
[2018-04-24T03:28:19.007Z] info Testing database connection...

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

---

*FEATURE REQUEST TEMPLATE*  

**What is the expected behavior?**

---

- [ ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @laputaclover ! 

Can you confirm you have a `tmp` folder with `strapi-mongoose` as node modules.

**Comment by laputaclover** [comment]
Thanks for you reply : )
In the  `tmp` folder there is only an empty  `etc`  folder, and I have checked the globe modules, no `strapi-mongoose` found. 

I tryed install `strapi-mongoose` module not only in the project also as globe.
`+ strapi-mongoose@3.0.0-alpha.4.3`
When create new project,  nothing changed. The only message is "Testing database connection..."

**Comment by lauriejim** [comment]
You have to install `strapi-mongoose@alpha` all modules are publish with alpha and the version has to be `3.0.0-alpha.12.0.1`

Can you try to not use `-` in your app name (maybe can come from here)

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by CovertCode** [comment]
I'm having a similar issue Error: Cannot find module '/tmp/strapi0e9f63607b0c/node_modules/strapi-hook-mongoose/lib/utils/connectivity.js'
I tired few fixes but none of them worked.

**Comment by lauriejim** [comment]
Can you give us more logs

**Comment by CovertCode** [comment]
> Can you give us more logs

I fixed this issue in my PC and tried some additional paths to create this issue and found just 1 solution for this.
Issue is not with STRAPI. It's with nodejs installation process. If user has installed node.js from snapcraft, ubuntu software center, or flathub then it creates some issue with node.js environment variables or with modules path. I install node.js from above 3 sources and STRAPI gave me errors while creating a new project.
So, I install node.js from terminal using **apt install nodejs**. I don't know what's difference in installing it from various sources. But I think installing from **apt** is the only solution and I don't think there's any harm in doing this way.

**Comment by loicnestler** [comment]
I have the same issue, even though I installed nodejs via apt.
```⏳ Testing database connection...
It might take a minute, please have a coffee ☕️
{ Error: Cannot find module '/tmp/strapi3697668ba6bc/node_modules/strapi-hook-mongoose/lib/utils/connectivity.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Promise.all.then (/usr/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:374:11)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) code: 'MODULE_NOT_FOUND' }
Error: An error occurred. The error exit was triggered on a switchback that is being handled with a callbackfunction in userland. And since no truthy argument was provided, switchback created this anonymous error.
    at Function.error (/usr/lib/node_modules/strapi/node_modules/switchback/lib/normalize.js:40:23)
    at Promise.all.then (/usr/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:379:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)```
