### ISSUE TITLE
qemu: uncaught target signal 4 (Illegal instruction) - core dumped

### ISSUE THREAD

**Issue by xarvel** [strapi/strapi#10118]
```
# strapi start
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Illegal instruction 
```

Verison: 3.6.0 (on 3.5.3 worked well)

**Comment by pkolt** [comment]
I have exactly the same error on version 3.6

When executed in the console:
```sh
strapi start
```

**Comment by xarvel** [comment]
The solution is to build a docker container for ARM platform.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
