### ISSUE TITLE
publicationState still appears in GraphQL queries input despite disabled

### ISSUE THREAD

**Issue by M1CK431** [strapi/strapi#10128]
### Describe the bug

Creating a collection with draft system disabled don't remove the `publicationState` in GraphQL queries input (find one/all).

### Steps to reproduce the behavior

1. Create a collection with draft system disabled
2. Check the GraphQL queries schema: `publicationState` still appears as input for get one/all queries

### Expected behavior

`publicationState` shoud be removed in get one/all GraphQL queries input

### Screenshots

Creating the `contact`  collection with draft system disabled:
![image](https://user-images.githubusercontent.com/31622263/115972822-07feb880-a551-11eb-8e3f-61d0bf4ef249.png)

Checking the generated GraphQL get one/all queries (`publicationState` is still there as input):
![image](https://user-images.githubusercontent.com/31622263/115972876-5ca23380-a551-11eb-9784-c2b88d1c64d6.png)
![image](https://user-images.githubusercontent.com/31622263/115972897-80fe1000-a551-11eb-9bbc-eff688d96275.png)

### System

- Node.js version: v14.16.0
- NPM version: v6.14.11
- Strapi version: v3.6.0
- Database: MariaDB v10.5.9
- Operating system: ArchLinux

**Comment by kasonde** [comment]
Hi @M1CK431 In the GraphQL API (and rest API if you check), this field will accessible but not effective when the draft/publish system has been turned off. Since this is a core feature, Strapi will generate the API schema (both GraphQL and REST) during model generation, and as a result publication state is an included filter field. This won't hinder your usage though since the filter/input field is ignored when the plugin is off.

**Comment by M1CK431** [comment]
Hi @kasonde and thanks for you quick reply! :kissing_heart: 

I'm perfectly align with the low severity because, as you explain, the field is ignored (and thanks a lot to reassure me about that :heart: )

My report is only about the interface (both GraphQL/REST). I mean, if for example, as a backend developer, I provide such endpoint with ineffective parameter to a frontend developer, it will be confusing for him.

If, for some reasons, it's simpler to keep the related code (core feature), I guess that Strapi should at least don't expose that useless field thought API.

Again, I totally agree that such "cosmetic" change should be handled far behind any feature or even "real" bug fix.

I'm using Strapi for the first time and it's a real pleasure, many thanks for your hard work! :man_cartwheeling:

**Comment by kasonde** [comment]
It's a global parameter that applies to the current model and any nested models (relations) and that's why it gets injected into the schema. It would be more complex to remove it from the schema for appearances.
