### ISSUE TITLE
Cannot access content-type localization feature after upgrading to 3.6.0

### ISSUE THREAD

**Issue by alicandirik** [strapi/strapi#10127]
### Describe the bug

I cannot access content-type localization feature after upgrading existing project to version 3.6.0 (I also confirmed version from UI settings) but I can access it if I create new project with version 3.6.0

### Steps to reproduce the behavior

1. Changed packages' versions to 3.6.0
2. Remove `node_modules` and `yarn.lock` file
3. Run `yarn install`
4. Run `yarn build --clean`
5. Run `yarn develop`
6. Edit existing singe type which has entry from UI
7. There is no option for `Enable localization for this Content Type`

### Expected behavior

`Enable localization for this Content Type` option should be accessible

### System

- Node.js version: 14.16.1
- YARN version: 1.22.10
- Strapi version: 3.6.0 
- Database: mySQL
- Operating system: Windows

**Comment by d2kx** [comment]
Did you... install it?

https://strapi.io/documentation/developer-docs/latest/development/plugins/i18n.html#installation

**Comment by alicandirik** [comment]
Thank you. Look like I missed it 😆

**Comment by igghera** [comment]
I had the same situation and ended up here looking for a solution. Perhaps a migration guide is needed, even if it's only for this particular thing?
