### ISSUE TITLE
Controllers can't return falsy values for GraphQL queries and mutations

### ISSUE THREAD

**Issue by gfpacheco** [strapi/strapi#10125]
## Bug report

As I'm writing a custom controller action I cannot return falsy values because `resolvers-builder.js` returns undefined instead.

### Describe the bug

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/resolvers-builder.js#L51 and https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/resolvers-builder.js#L117 ignore valid falsy values (`false`, `''`, `0`) assigned to `ctx.body` and return `values` instead.

### Steps to reproduce the behavior

1. Create a custom action in any controller and set the response to `0`
2. Create a route so you can call it
3. Write the GraphQL schema and resolver
4. Call REST endpoint and get expected result
5. Call GraphQL query and see error

### Expected behavior

GraphQL query should return the same result as REST entpoint.

### Code snippets

`my-controller.js`:
```
module.exports = {
  action: async (ctx, next) => {
    ctx.body = 0;
  },
};
```

`routes.json`
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/my-controller/action",
      "handler": "my-controller.action",
      "config": {
        "policies": []
      }
    }
  ]
}
```

`schema.graphql.js`
```
module.exports = {
  query: `
    action: Int!
  `,
  resolver: {
    Query: {
      action: {
        description: 'Return zero',
        resolver: 'application::my-controller.my-controller.action',
      },
    },
  },
};
```

### System

- Node.js version: v14.15.0
- NPM version: 7.6.0
- Yarn version: v1.22.10
- Strapi version: 3.5.4
- Database: sqlite
- Operating system: MacOS

### Additional context

This can be easily solved by checking `ctx.body === undefined` and I can make the PR if you feel like this is ok.

**Comment by kasonde** [comment]
Hi @gfpacheco the Strapi GraphQL plugin uses [apollo-server-koa](https://www.apollographql.com/docs/apollo-server/v1/servers/koa/) under the hood which requires that resolver responses are "returned" from a resolver as opposed to fetched from the request context. You can see this in action in our [Customize the GraphQL Schema](https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#customize-the-graphql-schema) example where restaurant records are returned in this manner for the custom GraphQL query:
```
restaurantsByCategories: {
  description: 'Return the restaurants open by the category',
  resolverOf: 'application::restaurant.restaurant.findByCategories', // Will apply the same policy on the custom resolver as the controller's action `findByCategories`.
  resolver: async (obj, options, ctx) => {
    // ctx is the context of the Koa request.
    await strapi.controllers.restaurants.findByCategories(ctx);

    return ctx.body.restaurants || `There is no restaurant.`;
  },
},
```
The response that is returned is taken from `ctx.body`.

**Comment by gfpacheco** [comment]
@kasonde I'm not sure if you read my issue properly or you don't know how Strapi works.

When you're creating a GraphQL query, instead of writing the resolver function in the schema file, you can just tell Strapi which controller action to call, in my case `application::my-controller.my-controller.action`.

And when you do that, Strapi creates a wrapper function that serves as your resolver function, that reads the value returned from the controller from `ctx.body` and returns it to `apollo-server-koa`.

The problem is that this wrapper function ignores falsy values and returns undefined [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/resolvers-builder.js#L117) and [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/resolvers-builder.js#L51).

**Comment by kasonde** [comment]
Hi @gfpacheco you're right. I've gone ahead and reopened the issue as well. Thanks again for your clarification.
