### ISSUE TITLE
Impossible to access admin panel after update to 3.6.0

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#10126]
### Describe the bug

After updating to 3.6.0 from 3.5.4 I can't access the admin panel and receive errors from React:
![image](https://user-images.githubusercontent.com/20924122/115938404-2f974780-a4a3-11eb-8027-837f860c767f.png)

### Steps to reproduce the behavior

1. Install 3.5.4
2. Update to 3.6.0

### Expected behavior

Expected everything to work :)

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.6.0 EE
- Database: Postgres
- Operating system: Ubuntu

**Comment by eriskhan** [comment]
Closing the issue as it was related to my extension of LeftMenuFooter component

**Comment by TasosBak** [comment]
@eriskhan Can you give more info on how you resolved the issue? I too have extended the LeftMenuFooter component and I am wondering if we faced the same issue.

**Comment by eriskhan** [comment]
Hey there @TasosBak! I've just deleted the LeftMenuFooter in extensions. You can also start strapi using `yarn develop --watch-admin` and React will show you an error

**Comment by TasosBak** [comment]
Thank you very much @eriskhan!
