### ISSUE TITLE
Installation with node > 14.x.x

### ISSUE THREAD

**Issue by kevingrondin** [strapi/strapi#10134]
When i going to install strapi, this message appear

strapi-generate-new@3.6.0: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "15.11.0"

**Comment by derrickmehaffy** [comment]
See: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#general-guidelines

Specifically:

> Node LTS (v12 or V14) Note that odd-number releases of Node will never be supported (e.g. v13, v15).

**Comment by dkebler** [comment]
well 16 has been out for awhile now (rust never sleeps) and that's what I am running so any reason strapi can't update the engine version at this point?  I can for now run strapi from docker for now.    But can't run it direct (at least I never intend to install previous even versions of node) until this is done.
