### ISSUE TITLE
localizations return an error when using GraphQL and mongodb

### ISSUE THREAD

**Issue by malnakli** [strapi/strapi#10130]
### Describe the bug

When using localizations on GraphQL I get the following error

```
"Cast to ObjectId failed for value \"[object Object]\" at path \"_id\" for model \"test\""
```

```
"extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stringValue": "\"[object Object]\"",
          "kind": "ObjectId",
          "value": "[object Object]",
          "path": "_id",
          "reason": {},
          "stacktrace": [
            "CastError: Cast to ObjectId failed for value \"[object Object]\" at path \"_id\" for model \"test\"",
            "    at model.Query.exec (/.../strapi/node_modules/mongoose/lib/query.js:4371:21)",
            "    at model.Query.Query.then (/.../strapi/node_modules/mongoose/lib/query.js:4463:15)",
            "    at Object.find (/.../strapi/node_modules/strapi-connector-mongoose/lib/queries.js:444:8)",
            "    at fn (/.../strapi/node_modules/strapi-database/lib/queries/helpers.js:31:54)",
            "    at Object.find (/.../strapi/node_modules/strapi-database/lib/queries/helpers.js:15:24)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
```

Only on mongoDB as a database.   
I have test on sqlite database and it works as expected

### Steps to reproduce the behavior

1. Create new strapi project with mongoDB as databae
2. Create a new collection type and enable localization
3. Add new data with two locales
4. Query the collection by calling ```{tests {localizations {
      id
      name
      locale
    }}```

### System

- Node.js version: v14.15.1
- YARN version: 1.22.5
- Strapi version: 3.6.0
- Database: mongoDB
- Operating system: MAC 11.2.3

**Comment by Igal-Kleiner** [comment]
I also ran into that issue, also with GraphQL and MongoDB.

**Comment by petersg83** [comment]
Thank you, I was able to reproduce it ! I'm working on it :)

**Comment by Igal-Kleiner** [comment]
Any ETA on that fix, please?

**Comment by petersg83** [comment]
Probably released today 🙃

**Comment by Igal-Kleiner** [comment]
@petersg83 Thank you very much! Installed the new version, works great!
