### ISSUE TITLE
Newly created strapi site (quickstart) doesnt work.

### ISSUE THREAD

**Issue by Knaackee** [strapi/strapi#10138]
### Bug

Newly created strapi site (quickstart) doesnt work.

### Steps to reproduce the behavior

1. Installing using `yarn create strapi-app my-project --quickstart`
2. Opened "http://localhost:1337/admin" in the Browser
3. Only a white page appears.
4. Chrome DevTools shows the following error

```
main.b3ba95f5.chunk.js:158195 Uncaught TypeError: _reactQuery.QueryClient is not a constructor
    at Object.<anonymous> (main.b3ba95f5.chunk.js:158195)
    at __webpack_require__ (runtime~main.0f454c4e.js:85)
    at Object.<anonymous> (main.b3ba95f5.chunk.js:82715)
    at __webpack_require__ (runtime~main.0f454c4e.js:85)
    at checkDeferredModules (runtime~main.0f454c4e.js:46)
    at Array.webpackJsonpCallback [as push] (runtime~main.0f454c4e.js:33)
    at main.b3ba95f5.chunk.js:1
```

### Expected behavior

A working site which allows me to create the admin user.

### System

- Node.js version: v12.16.0
- NPM version: 6.13.4
- YARN Version: 1.18.0
- Strapi version: 3.6.0
- Database: sqlite3 (default on quickstart)
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/116305252-5cc05000-a758-11eb-9f9e-00ec4e34154e.png)

Unable to reproduce, please provide additional reproduction information and we can reopen the issue.
