### ISSUE TITLE
Editing User fields throws an error in MySQL

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1013]
**Informations**

- **Node.js version**: 9.0.0
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.12
- **Database**: MySQL
- **Operating system**: Windows 10

**What is the current behavior?**

Editing a User always returns a "An error occured during record update". I always get this error, no matter which User i edit, even the newly created ones. 
![image](https://user-images.githubusercontent.com/17174150/39170750-ef803578-479c-11e8-918d-5c8c22fa9c4e.png)
editing other content-types works as it should. only the fields of User throws errors. In the console i get the following error:

[2018-04-24T08:29:27.828Z] error Cannot read property 'split' of undefined
[2018-04-24T08:29:27.829Z] debug POST /auth/forgot-password (3924 ms)

UPDATE:  Forgot-password api call also crashes when trying to update the user with its' resetPasswordToken.

**Steps to reproduce the problem**

1) Select User in Users screen
2) edit username field
3) save

**What is the expected behavior?**

Saving should update the username or other fields of the User

**Suggested solutions**

The problem occurs in the update method of User. The error originates from there, as my forgot-password method crashes at this line of code (at plugins/users-permissions/controllers/Auth.js)

`await strapi.query('user', 'users-permissions').update(user);`

this line of code will ultimately go to the edit function (at plugins/users-permissions/services/User.js)

![image](https://user-images.githubusercontent.com/17174150/39176395-03076714-47ad-11e8-8286-4af2893ee851.png)

I'm guessing there is currently no support for MySQL? This seems a big problem. 

- [ x] I'm sure that this issue hasn't already been referenced

**Comment by scipe** [comment]
Whats console said right this time?

**Comment by piere129** [comment]
@scipe I updated my issue

**Comment by soupette** [comment]
I think your issue is related with your SQL database. I have tried to reproduce your issue using mongoDB it was working fine

**Comment by piere129** [comment]
@soupette I think there is not support for MySQL?

**Comment by derrickmehaffy** [comment]
@piere129 There is minimal support for MySQL AFAIK and it is being worked on in another branch/milestone

MySQL Dev branch: https://github.com/strapi/strapi/tree/sql-xp
MySQL Milestone Tracking: https://github.com/strapi/strapi/milestone/13

**Comment by piere129** [comment]
@derrickmehaffy this is useful, but it doesn't diminish the fact that MySQL is unusable for any decent project at this moment. It seems like this should be hotfixed...

**Comment by derrickmehaffy** [comment]
@piere129 Development is on going, I'm sure if you wished to help with it, the Strapi team would love some pull requests :)

There is no simple hotfix as the differences between MySQL and Mongo are night and day. I'm sure its being worked on as fast as they can.

**Comment by piere129** [comment]
@derrickmehaffy I'll try creating a brand new database and see if it fixes it. The problem might be in my database (I hope)

**Comment by piere129** [comment]
Nope it still doesn't work. @lauriejim can you elaborate on how this isn't reproducable for you? :)

**Comment by lauriejim** [comment]
Fail label attribution*

**Comment by derrickmehaffy** [comment]
@piere129 I'm also looking for more in depth mysql support I'll see if I can reproduce this as well. My guess is it has something to do with the creation of tables in the database.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy We're currently working on a way to automate the table creation, update, etc. It should be released soon. Strapi is almost unusable with SQL database... you've to create the table manually which is not very convenient for a project like us when the added value is to reduce the time of development.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko Yeah I've been following the sql-xp branch looking like solid progress is being made.

**Comment by piere129** [comment]
@derrickmehaffy  creation of tables isn't the problem I think. My second screenshot has a comment saying the implementation is for mongoDB, not for mysql. So my guess is that's where it goes wrong. @Aurelsicoko automatic table creation would be amazing, but it's do-able without it, as long as everything else works :p

**Comment by piere129** [comment]
This issue is closed but it seems like it hasn't been merged with master branch yet.. Any idea when this will happen? As of today, installing with npm install@alpha -g and creating a new strapi application still throws errors when editing fields of a created User.

**Comment by derrickmehaffy** [comment]
@piere129 thats because the pull request for this isn't pushed to live yet, it can take a bit for them to finish multiple patches and deploy a new build to npm

My guess is these fixes will come in 12.1 or 12.2.

You can check milestone progress towards the next build here: https://github.com/strapi/strapi/milestones

**Comment by derrickmehaffy** [comment]
Based on the progress and commits for 12.1, I would expect to see it within a few days to a weeks time.

**Comment by piere129** [comment]
@derrickmehaffy  thank you for the quick response! This issue hasn't been added to a milestone yet, which is why I wanted to check whether or not progress was being made. Hopefully it gets added soon 😄
