### ISSUE TITLE
After upgrading from 3.5.3 to 3.6, attempts to admin changes to roles throw Error

### ISSUE THREAD

**Issue by klausbert** [strapi/strapi#10135]
### Describe the bug

As a Super Admin, after a new Collection-Type is created, when trying to add permissions to Editor / Author role (or change existing permissions, or just pushing the Save button without changing anything) the following error is shown and nothing is saved:

> Permissions have to be defined all together for a
> subject field or not at all

### Steps to reproduce the behavior

1. [Upgrade existing installation](https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html) from 3.5.3 to 3.6.0
   1. Upgrade dependencies in package.json
   2. Rebuild admin panel with `npm run build -- --clean`
   3. (I don't hve any extensions in use)
2. Start Strapi with `strapi develop` or `npm run develop`
3. Login as Super Admin
   * Optionally, create a new Content-Type
4. Go to Settings, Administration Panel Roles
5. Click on Editor role
6. Checkbox all permissions for new Content-Type and press Save
   * Also, try to change an existing permission, or even click on Save without changing anything at all

### Expected behavior

The given permissions should be accepted.

### System

- Node.js version: v14.16.0
- NPM version: 6.4.11
- Strapi version: 3.6.0 (upgraded from 3.5.3)
- Database: MySQL 8.0.23
- Operating system: Ubuntu 20.04

### Additional context

Running on a Linode server

**Comment by derrickmehaffy** [comment]
Can you test out the new v3.6.1 we released today?

**Comment by klausbert** [comment]
Thanks @derrickmehaffy solved in 3.6.1!
Cheers

**Comment by mkrou** [comment]
I have the same problem on 3.6.6

**Comment by madaxen86** [comment]
If anyone still runs into this issue.
As the complete permission config has been changed you need to decide for each permission that is displayed as a dash if you want it to be granted or not. Go through all the tabs and check or uncheck accordingly an you should not get an error anymore.

**Comment by sandoche** [comment]
I have the same issue with 3.6.8 (note that I had to follow this 
https://github.com/strapi/strapi/issues/10423 and go from 3.1.4 to 3.5.4 and then from 3.5.4 to 3.6.8.

**Comment by sandoche** [comment]
> If anyone still runs into this issue. As the complete permission config has been changed you need to decide for each permission that is displayed as a dash if you want it to be granted or not. Go through all the tabs and check or uncheck accordingly an you should not get an error anymore.

This actually works

**Comment by davidparys** [comment]
> If anyone still runs into this issue. As the complete permission config has been changed you need to decide for each permission that is displayed as a dash if you want it to be granted or not. Go through all the tabs and check or uncheck accordingly an you should not get an error anymore.


FYI that's what he means by dash. Works great 👍 
<img width="920" alt="Screenshot 2021-11-25 at 16 39 46" src="https://user-images.githubusercontent.com/56082497/143469827-177df083-12ca-4c2f-9a2c-7df9e7d1f404.png">
