### ISSUE TITLE
Invalid or unexpected token after adding sendgrid 

### ISSUE THREAD

**Issue by mejdi-hafiene** [strapi/strapi#10143]
### Describe the bug

i had a full functional project with no problems, i decided to add sendgrid to send emails, i followed the documentations and added the sendgrid package, after the new package is installed, i can't start the server no more and i got this message instead:
`Error while running command develop: Could not load function /Users/mejdihafiene/development/projects/ascentia/aascentia-server/pet-app/config/functions/.DS_Store: Invalid or unexpected token`

### Steps to reproduce the behavior

1- the strapi server is working
2- i opened the terminal on the project root
3- i typed the following command: `npm install strapi-provider-email-sendgrid`
4- i discovered that the server is not on anymore so i typed on the terminal : `npm run develop` which produced the following error `Error while running command develop: Could not load function /Users/mejdihafiene/development/projects/ascentia/aascentia-server/pet-app/config/functions/.DS_Store: Invalid or unexpected token`

### Expected behavior

the server just starts as usual

### Screenshots

<img width="1792" alt="Screen Shot 2021-04-26 at 1 05 16 PM" src="https://user-images.githubusercontent.com/82941026/116079909-523a8380-a690-11eb-8cd3-764b9fb520aa.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16.0.0
- NPM version: 7.10.0
- Strapi version: 3.5.3
- Database: atlas mongodb
- Operating system: macOs

**Comment by kasonde** [comment]
> Node.js version: v16.0.0
Hi @mejdi-hafiene it seems you're using an unsupported version of Node. Please consider downgrading your Node version and trying again. 
> Node LTS (v12 or V14) Note that odd-number releases of Node will never be supported (e.g. v13, v15).
Refer to this deployment guide on our documentation [Here](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#general-guidelines)
