### ISSUE TITLE
Add Cartesian product

### ISSUE THREAD

**Issue by melishev** [strapi/strapi#10140]
### Why is it needed?

 This will help you create more sophisticated e-commerce applications on Strapi.

### Suggested solution(s)

Adding a plugin or a separate field to the content-types builder to create a product with the further possibility of adding its variations.
For example: Nike sneakers are red and green, also have US 7 and 8 sizes.
To solve this problem, I propose to implement https://en.wikipedia.org/wiki/Cartesian_product

**Comment by derrickmehaffy** [comment]
Most like is a better case for custom fields: https://feedback.strapi.io/developer-experience/p/custom-fields

I will close this in favor of that entry instead
