### ISSUE TITLE
The CMS defaults to my local language (Dutch) instead of English

### ISSUE THREAD

**Issue by marcelhageman** [strapi/strapi#10142]
### Describe the bug

The CMS defaults to my local language (Dutch) instead of English. I do NOT ever want to see the UI in my local language, I work and think in English and the Dutch language annoys me to no end.

### Steps to reproduce the behavior

1. npx install Strapi (it's also not `npx installeer strapi alsjeblieft` 
2. It opens itself in the browser (which is in English) 
3. Which is a browser on my US English Mac OS (niet de Nederlandse variant)
4. It's in !@#$@#!@ Dutch for some arcane reason
5. And there is not a "switch to English, the default language for everything you do in daily life" button anywhere in sight

### Expected behavior

If you feel you must default to someone's local language, at least base it on the language of the system OR the language of the browser OR give the user a choice before assuming anything.

### Screenshots

![image](https://user-images.githubusercontent.com/3671221/116075917-d5110d80-a693-11eb-86b2-97b8f572622e.png)

Look at this monstrosity.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 16.0.0
- NPM version: 7.10.0
- Strapi version: 3.6.0
- Database: I don't know I just set it up fresh for the first time
- Operating system: Mac OS Big Sur 11.2.2

**Comment by soupette** [comment]
The language selection of the admin panel can be changed. To do so,
1. Click on your profile in the upper right dropdown.
2. In the language section choose english
3. Save

**Comment by soupette** [comment]
@marcelhageman I am closing the issue feel free to reopen it.
