### ISSUE TITLE
Cannot make the related fields common to all locales in v3.6.0 | i18n

### ISSUE THREAD

**Issue by haldarmahesh** [strapi/strapi#10158]
## Bug report
Please help

### Describe the bug

I am able to mark fields common to all locales, but the fields which are related to other tables with any of the valid relationship they cannot be changed to `common to all locales`.

### Steps to reproduce the behavior

1. Create two collections
2. mark a field related to another collection
3. Add i18n to the collection
4. In the advanced setting try to toggle disable i18n for the related field 

### Expected behavior

We should be able to disable i18n and mark the related fields common to all locales. 

### Screenshots
**Admin portal:**
![image](https://user-images.githubusercontent.com/7925734/116208851-f25ede00-a75e-11eb-8350-e9b2b72cbcb2.png)
**Content types builder**
![image](https://user-images.githubusercontent.com/7925734/116208915-00acfa00-a75f-11eb-93b9-62f38c713b46.png)
**Advanced settings**
![image](https://user-images.githubusercontent.com/7925734/116208938-060a4480-a75f-11eb-9b87-f5f251f7588d.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14
- NPM version:
- Strapi version: 3.6.0
- Database: mysql
- Operating system: mac

### Additional context
I tried to update the model with the following but didn't work
```json
"component_template": {
      
      "model": "component-templates",
      "via": "page_components",
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    },

**Comment by derrickmehaffy** [comment]
CC @sam-pires / @maevalienard / @JabStrapi

**Comment by krotovic** [comment]
Is there any progress on this?
