### ISSUE TITLE
strapi-provider-email-nodemailer SMTP custom headers not being sent 

### ISSUE THREAD

**Issue by JuanGrauGGG** [strapi/strapi#10160]
### Describe the bug

**strapi-provider-email-nodemailer** package is ignoring nodemailer mail/config attributes like headers.
Therefore it is not possible to send custom SMTP headers as documented here.
https://github.com/nodemailer/nodemailer/blob/master/examples/custom-headers.js#L19

This happens because the email attributes are whitelisted but the 'headers' attribute is missing in that whitelist there https://github.com/strapi/strapi/blob/master/packages/strapi-provider-email-nodemailer/lib/index.js#L19

Fixed whitelist 
```javascript
  const emailFields = [
  'from',
  'replyTo',
  'to',
  'cc',
  'bcc',
  'subject',
  'text',
  'html',
  'attachments',
  'headers'         // <-- missing attribute name
];
```

### Steps to reproduce the behavior

1. Configure strapi to use strapi-provider-email-nodemailer
2. Send an email with custom headers like 'X-SOME-CUSTOM-HEADER': 'SOME VALUE'
3. Check the received email source does't have the header above

### Expected behavior

Received email source should have custom headers in message

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Strapi version: 3.5.4

**Comment by kuakman** [comment]
I'm running into the same issue as [this](https://github.com/nodemailer/nodemailer/issues/1363).
And the current implementation in the nodemailer provider has a lodash -> pick call to only accept the email options described in the description above.

This strapi plugin is literally blocking the ability to pass custom headers to some email providers that offer control over their email behavior. I'd reopen this and add the headers support.

OR ultimately, enable the ability to pass "defaults" from the strapi plugin.js file as the second argument to the ```createTransport``` call in [here](https://github.com/strapi/strapi/blob/develop/packages/providers/email-nodemailer/src/index.ts#L40) so then later, the nodemailer can do its job with those defaults in [here](https://github.com/nodemailer/nodemailer/blob/master/lib/mailer/mail-message.js#L24-L35).

However you want it to make it work.
