### ISSUE TITLE
upload an image , return "Not Found"

### ISSUE THREAD

**Issue by sara0alyahya** [strapi/strapi#10163]
### Describe the bug

We have work with strapi and facing an issue when setup Strapi and with the database.
The main problem is we are losing the data when uploading an image in the production. It’s not saved in the media library.
When uploading an image locally, it’s saved in /public/uploads file and can easily use it and call it on React app, but when uploading the image on  production, it’s not saving and can’t call it because its return “Not Found.”
We are hosting Strapi on Heroku.

### Steps to reproduce the behavior

1.add image content type.
2.add contents and upload an image from device.
3.uploading success.
4.after 24 hours or less the image can't call and return "not found" by inspect the image link.

### Expected behavior

upload an image, and appears correctly when call it all the time.

### Screenshots

<img width="1180" alt="strapi" src="https://user-images.githubusercontent.com/45763914/116306545-dcc4d500-a7ad-11eb-8866-9be49ba0f237.png">

### Code snippets

If applicable, add code samples to help explain your problem.
<img width="455" alt="Screen Shot 2021-04-27 at 11 34 41 PM" src="https://user-images.githubusercontent.com/45763914/116309341-501c1600-a7b1-11eb-89a4-1a0943a937e2.png">
<img width="494" alt="Screen Shot 2021-04-27 at 11 35 08 PM" src="https://user-images.githubusercontent.com/45763914/116309348-527e7000-a7b1-11eb-871a-6024dd0557d8.png">

### System

- Node.js version: v14.13.1
- NPM version: 6.14.8
- Strapi version: 3.5.3
- Database: sqlite, postgres
- Operating system: macOS

**Comment by kasonde** [comment]
@sara0alyahya I think this will provide more insight into your issue. [Heroku Runtime Principles](https://devcenter.heroku.com/articles/runtime-principles#statelessness).

**Comment by keyurm-wmt** [comment]
same issue when i redeployed in the server then file gone its show not found. I use my own server to upload not Heroku then also after redeployed file not showing. using docker i deployed
