### ISSUE TITLE
Not able to set slug with internationalization feature - Not unique

### ISSUE THREAD

**Issue by saravanakumargn** [strapi/strapi#10169]
### Describe the bug

Not able to set slug using slugify with internationalization feature. 

### Expected behavior

Expecting slug should be unique. But with internationalization unique value is not acceptable.

### Screenshots

My Strapi Category field setting

![Screenshot 2021-04-28 at 2 13 41 PM](https://user-images.githubusercontent.com/1115851/116374530-fb69b100-a82b-11eb-9c1f-700fbac416d0.png)

### Code snippets

```
// Category model
"use strict";
const slugify = require("slugify");

module.exports = {
  lifecycles: {
    beforeCreate: async (data) => {
      if (data.label) {
        data.slug = slugify(data.label, { lower: true, strict: true });
      }
    },
    beforeUpdate: async (params, data) => {
      const entity = await strapi.services.category.findOne({ _id: params._id });
      if (entity.slug) {
        data.slug = entity.slug;
      }
    },
  },
};
```

### System

- Node.js version: v14.16.1
- Strapi version: 3.6.0

**Comment by derrickmehaffy** [comment]
@sam-pires what do you want me to label this as?

**Comment by B1Z1** [comment]
Is there any changes, because I cannot find entity by slug with internalization

**Comment by B1Z1** [comment]
Ok, I found solution

strapi.query('post').findOne({locale, slug})

That enough if you want to search by slug with internalizations

**Comment by Stun3R** [comment]
Hi @saravanakumargn,

You can now create slug with the UID field. It allow you to choose which field it's attached to and will generate a slug.

https://strapi.io/documentation/user-docs/latest/content-types-builder/configuring-fields-content-type.html#uid

**Comment by likelovewant** [comment]
> ug})

Can your  share your full code for the custom post controller in strapi  , I AM still finding a solution
