### ISSUE TITLE
Bug with the minimum value on Integer Number field

### ISSUE THREAD

**Issue by FV-Valraiso** [strapi/strapi#10179]
Hello Strapi Team

### Describe the bug

In a collection type, when we use a field type Number with format Integer, if you specify a minimum value it has to be > 0

### Steps to reproduce the behavior

1. Add a field type "Number"
2. Select format Integer
3. Click on "Advanced Settings"
4. Check "Minimum value"
5. Put 0 or a negative number
6. See the error message

### Screenshots

![Capture d’écran 2021-04-29 à 08 40 05](https://user-images.githubusercontent.com/1353509/116511863-61efdd00-a8c7-11eb-8780-177edf7df3c5.jpg)

### Expected behavior

A positive or negative integer should be selected
At least 0 should be considered as positive

### System

- Node.js version: 12.18.1 & 14.16.0
- NPM version: 6.14.5
- Strapi version: 3.6.0
- Database: Mysql 
- Operating system: OSX & Ubuntu

Thanks for help
Francis

**Comment by derrickmehaffy** [comment]
I can confirm this on v3.6.1; there is no reason why minimum value needs to be positive so long as minimum is lower than maximum (if maximum exists).

For example:

Latitude and Longitude have constraints (on earth) of being latitude is -90 to +90 and longitude is -180 to +180.

@FV-Valraiso The workaround for this is to just set a positive number to start, then go in and manually edit the model schema and set it to whatever you want.

**Comment by FV-Valraiso** [comment]
I'll fix it modifying my schema files and check after 3.6.1 upgrade that it's fixed in the UI.
Thanks for quick reply

**Comment by FV-Valraiso** [comment]
It's not fixed in v3.6.1, is it Postponed ?

**Comment by derrickmehaffy** [comment]
@FV-Valraiso No one has created a PR to resolve the issue, if you are up for it please do feel free to submit a PR.

**Comment by FV-Valraiso** [comment]
Great it's working well on 3.6.2.
Thanks :-)
