### ISSUE TITLE
[Website] Filters issue

### ISSUE THREAD

**Issue by Squadz** [strapi/strapi#10170]
## Bug report
Issue when filtering the Starter : https://strapi.io/starters

### Describe the bug
When using multiple filters, the Starter aren't filtered as expected.

### Steps to reproduce the behavior
1. Use cases "Blog" : It will show all Starter related to "Blog". (4 Results)
2. Integrations "Next.js : It will show all Starter that use Next.Js (3 Results)
3.  When selecting both filters : "Blog" and "Next.js" it will show all starter related to blog OR all starter that use next.js. (6 Results).

### Expected behavior
I believe it should only return 1 result, a starter related to blog AND that use next.js. ( https://strapi.io/starters/strapi-starter-next-js-blog )

### Screenshot
http://image.noelshack.com/fichiers/2021/17/3/1619606533-bug.png

### Code snippets

Not applicable

### System

- Strapi Website

### Additional context

Nop

**Comment by francescostella** [comment]
@vcoisne @yvesdo If you need, I can help to look into this issue. I just need pointed to the file of the `https://strapi.io/starters` page.

**Comment by derrickmehaffy** [comment]
> @vcoisne @yvesdo If you need, I can help to look into this issue. I just need pointed to the file of the `https://strapi.io/starters` page.

Currently our website code isn't public, that's something we are looking to open this quarter but no ETA yet. Thank you though!

**Comment by derrickmehaffy** [comment]
Was fixed a while ago, forgot to close issue
