### ISSUE TITLE
Custom Field in Plugin produces i18n missing translation error. 

### ISSUE THREAD

**Issue by u382514** [strapi/strapi#10187]
### Describe the bug

I've created a simple plugin with a custom field called Subdomain. I've added this to the model directly from the backend since there doesn't seem to be a way to do that from the frontend. Getting back into Strapi and going to the collection under content-type builder will throw an error from I18n: 

React Intl Error MISSING_TRANSLATION] Missing message: "content-type-builder.attribute.subdomain" for locale: "en" 

I've tried adding the entry in the en.json file under translations however the issue still occurs. 

### Steps to reproduce the behavior

Create a custom field in a plugin and register the field. Add it to a collection model. Go to strapi admin and click on the collection under content-type builder. Watch the sparks fly in the console. 

### Expected behavior

I expect it to not do that. At the very least I'd expect that the entry in the en.json file should handle it, but preferably I'd like it to not error at all. 

### Screenshots

![image](https://user-images.githubusercontent.com/2907522/116624142-03e5e880-a90d-11eb-971d-bcf452139955.png)

![image](https://user-images.githubusercontent.com/2907522/116624201-224be400-a90d-11eb-9988-b3acab4e9f3b.png)

**Comment by soupette** [comment]
Custom fields are not supported (yet) in the content type builder. We have just made a fix so no error is displayed in the console for such case.
