### ISSUE TITLE
Removing unique constraint from strapi doesn't remove it from Postgres

### ISSUE THREAD

**Issue by cipriancaba** [strapi/strapi#10184]
### Describe the bug

When using the new i18n, I have found the need to remove the unique constraint from the `slug` property of an `article`. While using the content builder to remove it, it appears as working but the database index doesn't get dropped automatically. I need to go in the DB and remove it manually, which is not ideal

### Steps to reproduce the behavior

1. Create a new collection type with a unique slug UUID
2. Change the UUID to a simple text with disabled localization
3. Try to add a new locale of the collection type
4. It will fail with unique contstraint

### Expected behavior

Allow saving new localized content

### System

- Node.js version: v14
- NPM version:
- Strapi version: 3.6.0
- Database: Posgtres
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1114
