### ISSUE TITLE
After updating Strapi 3.6.0, errors are thrown when trying to edit any content types

### ISSUE THREAD

**Issue by hbel** [strapi/strapi#10180]
### Describe the bug

I updated my docker-based Strapi from 3.5.4 to 3.6.0 (I updated the docker container and I also updated the project in the app volume) and even got I18N working. I then stumbled upon the following error:

Whenever I try to edit any content type in the content-type-editor, Strapi throws an non-descript error. Looking at Strapis response, I see that the error is  

```
{"error":{
"contentType.attributes.published_at":
["Attribute keys cannot be one of __component, __contentType, _id, id, created_by, updated_by, published_at, length, attributes, relations, changed, _posts, _pres, collection, emit, errors, get, init, isModified, isNew, listeners, modelName, on, once, populated, prototype, remove, removeListener, save, schema, toObject, validate, format, createdAt, updatedAt"],
"contentType.attributes.created_by":["Attribute keys cannot be one of __component, __contentType, _id, id, created_by, updated_by, published_at, length, attributes, relations, changed, _posts, _pres, collection, emit, errors, get, init, isModified, isNew, listeners, modelName, on, once, populated, prototype, remove, removeListener, save, schema, toObject, validate, format, createdAt, updatedAt"],
"contentType.attributes.updated_by":["Attribute keys cannot be one of __component, __contentType, _id, id, created_by, updated_by, published_at, length, attributes, relations, changed, _posts, _pres, collection, emit, errors, get, init, isModified, isNew, listeners, modelName, on, once, populated, prototype, remove, removeListener, save, schema, toObject, validate, format, createdAt, updatedAt"]
}}
```

so this seems to be connected to the new internal fields Strapi is now adding to every content type. Is there a migration step that should be performed (sadly there is no migration doc for 3.6 yet) to fix this?

### Steps to reproduce the behavior

1. Create a new content type and save it
2. Edit the content type again
3. Try to save the content type -> Error occurs

### Expected behavior

I should be able to save a content-type after changes

### Screenshots

![image](https://user-images.githubusercontent.com/7416029/116517458-4a1c5700-a8cf-11eb-9b19-cdd1401e0c24.png)

### System

Strapi 3.6.0 (docker container) with MongoDB

**Comment by derrickmehaffy** [comment]
Can you please provide your model file for test. The two relations that are listed there (created_by and updated_by) should not be shown there.

**Comment by hbel** [comment]
Just updated to 3.6.1 and the problem is gone. Closing this issue.

**Comment by jordankittle** [comment]
I am having this problem with 3.6.2.   I create a brand new content type, then when I try to edit it and click save, it throws an error: `[2021-07-23T01:41:29.987Z] debug PUT /content-type-builder/content-types/application::blogs.blogs (48 ms) 400`

**Comment by Iliyass** [comment]
`strapi 3.6.6`

and the same issue!

**Comment by derrickmehaffy** [comment]
Can either of you provide a bit more context on how we can reproduce this issue?

**Comment by jordankittle** [comment]
A bit more context is a little vague. Can you tell me what information you need so I know what to give?

**Comment by Iliyass** [comment]
@derrickmehaffy @jordankittle 

Here is a process you can follow to reproduce it.

1. Create a Content-Type with one field
2. Save the the Content-Type 
2.1 The trick here, is that your content type should have the `created_by`, `updated_by` Relations with User (from: admin)
2.2 After the Content-type been Saved
3. Edit the Content-Type and add new field
4. Hit save and you will be shown `An error accured` with errors in console
```
{"error":{
"contentType.attributes.published_at":
["Attribute keys cannot be one of __component, __contentType, _id, id, created_by, updated_by, published_at, length, attributes, relations, changed, _posts, _pres, collection, emit, errors, get, init, isModified, isNew, listeners, modelName, on, once, populated, prototype, remove, removeListener, save, schema, toObject, validate, format, createdAt, updatedAt"],
"contentType.attributes.created_by":["Attribute keys cannot be one of __component, __contentType, _id, id, created_by, updated_by, published_at, length, attributes, relations, changed, _posts, _pres, collection, emit, errors, get, init, isModified, isNew, listeners, modelName, on, once, populated, prototype, remove, removeListener, save, schema, toObject, validate, format, createdAt, updatedAt"],
"contentType.attributes.updated_by":["Attribute keys cannot be one of __component, __contentType, _id, id, created_by, updated_by, published_at, length, attributes, relations, changed, _posts, _pres, collection, emit, errors, get, init, isModified, isNew, listeners, modelName, on, once, populated, prototype, remove, removeListener, save, schema, toObject, validate, format, createdAt, updatedAt"]
}}
```

My current hack:
Is to dump the database and update the {model}.settings.json with the correct properties.

It looks like it has something to do with Updating the Model Schemas. (btw I'm using Postgres)

Thanks.

**Comment by derrickmehaffy** [comment]
@Iliyass I've done exactly the steps you laid out and I can reproduce it at all, however those relations that you mentioned are system fields you shouldn't add those manually as there is a configuration key you can flip to show those in the REST response.

https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#model-options

> populateCreatorFields: Configure whether the API response should include created_by and updated_by fields or not. Accepts a boolean. The default value is false.
