### ISSUE TITLE
Creating a field called locale when localisation is enabled automatically deletes it

### ISSUE THREAD

**Issue by Louvki** [strapi/strapi#10181]
## Bug report
Tried to create a field called "locale". It was an enumeration. The field got removed when I saved. From what I understand this is due to the name being used by strapi when localization is enabled. There should be some sort of warning instead of removing it quietly. 

### Steps to reproduce the behavior
1. Go to Content Type builder
2. Click on 'Create new collection type'
3. Click on  'Advanced Settings' and check the box for 'Enable localization for this Content-Type'
4. Add a field called 'locale'
5. Click 'Save' and wait for the restart
6. See the field locale dissapear without any warning

### Expected behavior

Error/Warning when in the process of naming the field.

**Comment by kasonde** [comment]
Leaving this here to add to the context, the `<content-type>.settings.json` will have the `locale` property inside attributes despite it not showing up in the admin, i.e:
```
 "locale": {
    "pluginOptions": {
      "i18n": {
        "localized": true
      }
    },
    "type": "string"
  }
```

**Comment by derrickmehaffy** [comment]
We do have a means to block certain field names, although the error message text is cutoff. the locale field needs to be added to this list

![image](https://user-images.githubusercontent.com/8593673/116585266-0de7f700-a8cd-11eb-845b-e760825c1946.png)

**Comment by derrickmehaffy** [comment]
Closing this as a duplicate to: https://github.com/strapi/strapi/issues/1198
