### ISSUE TITLE
i18n plugin's non-administrator user permission is not work

### ISSUE THREAD

**Issue by SimDaeSoo** [strapi/strapi#10199]
### Describe the bug
user role permissions for i18n API is not work.
because i18n routes config default policies have "admin::isAuthenticatedAdmin". 
![image](https://user-images.githubusercontent.com/22269524/116755305-34c93900-aa45-11eb-9d5b-b36682c3c9f7.png). 
  
So, non-administrator users cannot access the locale API.
In order for users to access it, you need to create a new config.
![image](https://user-images.githubusercontent.com/22269524/116755582-98536680-aa45-11eb-8b28-dfa532fb2cee.png)
![image](https://user-images.githubusercontent.com/22269524/116756053-6abaed00-aa46-11eb-87b6-32ec7d0ee064.png)

### Steps to reproduce the behavior

1. Go to Settings - Roles & Permissions
![image](https://user-images.githubusercontent.com/22269524/116754428-af915480-aa43-11eb-9ab5-c5e462a478bd.png)

2. And Change i18n locales GET API Permission for `Public`
![image](https://user-images.githubusercontent.com/22269524/116754541-dea7c600-aa43-11eb-9496-5fda93c048e7.png)

3. But locales GET API still forbidden
![image](https://user-images.githubusercontent.com/22269524/116754304-7822a800-aa43-11eb-8e81-21b107282dea.png)

### Expected behavior
If you change the role permission, the permission should change.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.16.1
- Yarn version: v1.22.10
- Strapi version: v3.6.1
- Database: MySQL 8.0.23
- Operating system: Mac OS Big Sur - 11.3(20E232)

**Comment by derrickmehaffy** [comment]
I can confirm this issue on v3.6.1 due to the following policy applied to all i18n routes:

https://github.com/strapi/strapi/blob/a7de8156b1ccc010f028403360949a9180aeae8d/packages/strapi-admin/config/policies/isAuthenticatedAdmin.js#L1-L9

This requires an admin JWT (as it is looking for `ctx.state.isAuthenticatedAdmin` which only comes from logging in and getting an admin JWT)
