### ISSUE TITLE
Strapi Content Type Builder is not displaying connections drop down

### ISSUE THREAD

**Issue by harinniy** [strapi/strapi#10196]
We are using two database connections. Mongo(default) and Sql(additional - attached database.json for reference). We have content types that connect to one of the two.

After migration to beta, the content type builder in admin does not show connections option while creating new content types.

We have hundreds of content types with mysql connection while mongo is the default connection. Kindly help understand if multiple database connections are supported now. 

Hitting the rest/graphql query for rds based content types give 500 error.

error ReferenceError: ModelNameInSingular is not defined
at Object.fetchAll.

Would really appreciate any help from the community regarding this. 

### Steps to reproduce the behavior

Upgrade from alpha to beta

### Expected behavior

1) Content Types Builder in Admin should enable us to choose connections and create content type in any connection.
2) For content types already created using mysql(secondary connection), controller endpoints are throwing 500 error. They used to work before and I have followed steps in migration properly.

### Screenshots

**Before:**

![image](https://user-images.githubusercontent.com/9319459/116718062-3704a680-a9f7-11eb-90d8-032e52dc0549.png)

**After upgrade to beta:** - Shows connection dropdown from which I could select the connection I need.

![image](https://user-images.githubusercontent.com/9319459/116718113-44219580-a9f7-11eb-997c-3d1db5e5bfab.png)

### Code snippets

database.json

`{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "127.0.0.1",
        "port": 2701,
        "database": "xyz",
        "username": "root",
        "password": "123",
        "uri": "mongodb://root:123@127.0.0.1:2701/xyz"
      },
      "options": {
        "authenticationDatabase": "xyz",
        "ssl": false
      }
    },
    "rds": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "db.x.com",
        "port": 3306,
        "database": "xsep",
        "username": "abc",
        "password": "dsfiewjew"
      }
    }
  }
}`

### System

Strapi Version: 3.0.0.beta.20
Operating System: ubuntu 18.04
Database: mongo/mysql
Node Version: v14.15.1
NPM Version: 6.14.11

**Comment by derrickmehaffy** [comment]
> 3.0.0.beta.20

We don't support this version and haven't in over a year and we removed this option quite some time ago (I think in the beta => stable).

@alexandrebodin can you confirm if we are going to remove the multi-DB stuff in v4?

**Comment by derrickmehaffy** [comment]
(For now going to mark this as closed as it's unlikely we will add this option back in, but can wait for a response about v4)
