### ISSUE TITLE
Admin Went Blank After Rebuild

### ISSUE THREAD

**Issue by 5no0p** [strapi/strapi#10200]
After rebuilding my strapi with yarn build 

![image](https://user-images.githubusercontent.com/20361105/116756573-9faa4e00-aa0c-11eb-86b4-ae5abe7bcf5e.png)

I get a blank page for my Admin page 

![image](https://user-images.githubusercontent.com/20361105/116756715-de400880-aa0c-11eb-8339-114b90a08af6.png)

And the only error I found was this

![image](https://user-images.githubusercontent.com/20361105/116756812-0f203d80-aa0d-11eb-89e0-91845a08688d.png)

![image](https://user-images.githubusercontent.com/20361105/116756826-147d8800-aa0d-11eb-8517-d6353ccb288e.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
