### ISSUE TITLE
Operator does not exist: jsonb ~~ unknown - Custom Query PostgreSQL

### ISSUE THREAD

**Issue by Seache** [strapi/strapi#10206]
### Describe the bug

When comparing JSON fields in custom database queries such as `qb.andWhere('location', 'like', '%' + location + '%')`
I get the following error:

`Error: select * from "data" where ("country_code" = $1) and ("languages" like $2) limit $3 - Operator does not exist: jsonb ~~ unknown`

Error code: 42883

I also tried with raw SQL, but same problem:
`qb.andWhereRaw("languages like '%english%'")`

Example JSON data:
```
[
  "english",
  "german"
]
```

### Steps to reproduce the behavior

1. Use PostgreSQL Database
2. Create model with a JSON field
3. Create custom database query with where method comparing a JSON field (like or in)
4. Execute query
5. See error

### Expected behavior

Get query result. Same query works with SQLite.

### System

- Node.js version: v14.15.1
- NPM version: 6.14.9
- Strapi version: 3.6.1
- Database: PostgreSQL Version 12
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Not an issue with Strapi as you are bypassing our code-base and directly using either [Bookshelf](https://bookshelfjs.org/) or [Knex](http://knexjs.org/). Marking as closed

**Comment by dodobardo** [comment]
Hello @derrickmehaffy I currently have this issue even without using Bookshelf or Knex, but using REST APIs from Postman.
