### ISSUE TITLE
Disable i18n for a Field in a Component in a Type

### ISSUE THREAD

**Issue by juliensl** [strapi/strapi#10211]
Hi everybody ! 

### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Have the possibility to disable i18n for a Field in a Component in a Type

### Why is it needed?

Today, we have got the possibility to disable i18n for a Field in a Type, which is pretty useful for pictures and URLs.
We can also disable i18n for a Component in a Type.
But, in my Components, I have texts (which should be international) and pictures (which are mutual between locals).

This is a example screen : 
![image](https://user-images.githubusercontent.com/43228020/116809478-80abd900-ab3e-11eb-9031-0907146df104.png)

Here, I can disable i18n for TopPage_Image, but I can't for Image in TopPage.

### Suggested solution(s)

Have the possibility to disable i18n for a Field in a Component in a Type

Thank you very much ! :) 

Ps : I am not sure to understand why I should post the feature request in both Product Board and Github, I tried to be more explicit in the Github, I hope it is the good way, sorry if I made mistakes.

**Comment by NicolasTsc** [comment]
any news on this? would be really useful.
