### ISSUE TITLE
Bug when having the same attributes in connected entities

### ISSUE THREAD

**Issue by kamalbennani** [strapi/strapi#1022]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**:
v9.6.0
- **npm version**:
v6.0.0
- **Strapi version**:
v3.0.0-alpha.12.0.1
- **Database**:
MongoDB
- **Operating system**:
Linux
**What is the current behavior?**
When I created multiple Content Entities for instance:
```
Course: {
  name: String,
  batches: [Batch],
  subjects: [Subjects]
}

Batch: {
  name: String,
  course: Course,
  subjects: [Subjects]
}

Subject: {
  name: String,
  course: Course,
  batches: [Batch]
}
```
It doesn't let me to for attach a Batch to a Course for instance of a Subject to a Course, I'm getting this error:
![image](https://user-images.githubusercontent.com/14129459/39214125-b740bcb0-4813-11e8-8189-81b908c69304.png)
Here is my cURL:
```
curl 'http://localhost:1337/content-manager/explorer/batch/5adf98d334bff26081a21b2e?source=content-manager' -X PUT -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YWRmOTZjZTYwYjU5YjVhYWIxMTA2ZGIiLCJpZCI6IjVhZGY5NmNlNjBiNTliNWFhYjExMDZkYiIsImlhdCI6MTUyNDYwMjU3NCwiZXhwIjoxNTI3MTk0NTc0fQ.VEqOARGuJCAaaPjtjS0mj82_YjH-geEyt-yj6H61Dvg' -H 'Origin: http://localhost:1337' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Forwarded-Host: strapi' -H 'Accept-Language: en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryQOAOn4K3qTyQjQLI' -H 'Accept: */*' -H 'Referer: http://localhost:1337/admin/plugins/content-manager/batch/5adf98d334bff26081a21b2e?redirectUrl=/plugins/content-manager/batch?page=1&limit=10&sort=_id&source=content-manager' -H 'Connection: keep-alive' --data-binary $'------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="name"\r\n\r\nSemestre 1 - CPD\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="code"\r\n\r\ncpd-s1\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="updatedAt"\r\n\r\n2018-04-24T20:51:31.664Z\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="__v"\r\n\r\n0\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="_id"\r\n\r\n5adf98d334bff26081a21b2e\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="course"\r\n\r\n5adf98a434bff26081a21b2d\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="id"\r\n\r\n5adf98d334bff26081a21b2e\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="createdAt"\r\n\r\n2018-04-24T20:51:31.320Z\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI\r\nContent-Disposition: form-data; name="affectedSubjects"\r\n\r\n[]\r\n------WebKitFormBoundaryQOAOn4K3qTyQjQLI--\r\n' --compressed
```
**Steps to reproduce the problem**
Create the entities and try to attach an entity to another

**What is the expected behavior?**
To be able to attach/add any entity to any other entity

**Suggested solutions**
I think that's related to how the relation between entities is determined

Here is the link to my test repo:
https://github.com/kamalbennani/strapi-test

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @kamalbennani. It's the relation between batch and course.

```js
// in Batch.settings.js model
"course": {
    "via": "batches"
  },
```

This format doesn't exit. Did you write it manually or using admin content type builder ?

Remove `course` in Batch model and `batches` in Course model and start again.

**Comment by kamalbennani** [comment]
@lauriejim via the admin :(

**Comment by lauriejim** [comment]
And what happened if you manually delete and try to recreate relation ?
What is the type of relation you want create ?

**Comment by kamalbennani** [comment]
<Course> OneToMany <Batch>
<Course> OneToMany <Subject>
<Batch> ManyToMany <Subject>

**Comment by kamalbennani** [comment]
I deleted them and when I recreate the relation I get this error
![image](https://user-images.githubusercontent.com/14129459/39272161-6d55104c-48db-11e8-9586-234d5423ba2a.png)
