### ISSUE TITLE
RBAC - Cannot hide media assets in Upload plugin using RBAC conditionals

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#10221]
### Describe the bug

Default and custom conditionals does not hide assets uploaded (using `is-creator` and/or `has same role as creator`). 

### Steps to reproduce the behavior

1. Create two admin users using the `author` role
2. Upload a media asset on author1
3. Login as author2 and view media library
4. See asset from author1

### Expected behavior

Authors (or any role that has limited media library access) should only be able to see their own assets.

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/116934593-06e91d80-ac1a-11eb-9c0c-c079c338f04e.png)

### Code snippets

N/A

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: v3.6.1
- Database: SQLite
- Operating system: Linux Mint 20.1 (Ubuntu 20.04.1)

### Additional context

Internal TID199

**Comment by mikkey** [comment]
Faced the same issue. Hope the fix is coming soon. :)

**Comment by derrickmehaffy** [comment]
@mikkey we are working on this one yes
