### ISSUE TITLE
Strapi Admin Went Blank After Rebuild

### ISSUE THREAD

**Issue by 5no0p** [strapi/strapi#10228]
I rebuild starapi after following this [tutorial](https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi) 

after that, I get my strapi blank and get this error

![image](https://user-images.githubusercontent.com/20361105/116998486-98ba5e80-acde-11eb-8e15-01bef8a6afde.png)

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
