### ISSUE TITLE
Dynamic zone component's private attributes are leaked by the REST API

### ISSUE THREAD

**Issue by JuanGrauGGG** [strapi/strapi#10236]
### Describe the bug

Component's (Dynamic zone) private attributes are leaked by the REST API.

### Steps to reproduce the behavior

1. create a component with a private attribute.
2. create a collection with a dynamic zone attribute and ad the component above 
3. Fill up some data
4. Query the collection API to verify that the private attribute is leaked

### Expected behavior

When retrieving pages through the rest API:
The secret component's private attribute "password"  should not appear in the response
Either way by using. **"private": true** or/and 
"options": {
    "privateAttributes": ["secret"]
  }

### Screenshots

N/A

### Code snippets

Collection with dynamic zone and secret component:

```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "page",
    "description": "Page model"
  },
  "options": {
  },
  "attributes": {
    "name": {
      "type": "string",
      "unique": true,
      "private": false
    },
    "blocks": {
      "type": "dynamiczone",
      "components": [
        "secret"
      ]
    }
  }
}


```
Secret Component 

```json
{
  "collectionName": "components_secret",
  "info": {
    "name": "Secret",
    "icon": "envelope",
    "description": "Component with private attribute"
  },
  "options": {
    "privateAttributes": ["secret"]
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": false
    },
    "password": {
      "type": "string",
      "required": true,
      "unique": false,
      "private": true
    }
  }
}
```

### System

- Node.js version: v12.18.3
- NPM version 6.14.6
- Strapi version: 3.5.4
- Database: MongoDB
- Operating system: MacOS 

### Additional context

https://github.com/strapi/strapi/issues/9804#issuecomment-828267602

**Comment by derrickmehaffy** [comment]
Marking as duplicate to https://github.com/strapi/strapi/issues/9804

(I'ved edited 9804 to state it's not just with GraphQL, @JuanGrauGGG can you mirror your context over to that issue also?)

**Comment by JuanGrauGGG** [comment]
Hi @derrickmehaffy 
According to @ralphsomeday this is a different issue from #9804 which is already closed.
That's why I opened this new one.

Please refer to https://github.com/strapi/strapi/issues/9804#issuecomment-828291463

**Comment by krabbi** [comment]
Same for graphql on 4.1.7

**Comment by derrickmehaffy** [comment]
@krabbi I forgot to close this when I set as duplicate. Can you open a new issue please as this issue is more so targeted to v3. I'd like to get an updated bug report template for the issue on v4.

Thanks!
