### ISSUE TITLE
Incorrect graphql aggregate count result for i18n enabled content type 

### ISSUE THREAD

**Issue by dankostov** [strapi/strapi#10241]
### Describe the bug
count result is not calculated correctly for Internationalized (localized) content type with many locale entries.

### Expected behavior

There should be distinguishment between the logical entry and its localized versions. 
The count should be calculated based on the logical entries and not the localized versions.

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
