### ISSUE TITLE
Duplicated username in auth/registratrion returns email error

### ISSUE THREAD

**Issue by Lafa02** [strapi/strapi#10240]
![image](https://user-images.githubusercontent.com/30123016/117126657-5c990380-ad9b-11eb-9d77-e1afe2b66600.png)
Even if it's a duplicate of the username it gives the email error, I've fixed it by inverting the shortif order in "node_modules\strapi-plugin-users-permissions\controllers\Auth.js" from this
![image](https://user-images.githubusercontent.com/30123016/117126738-7f2b1c80-ad9b-11eb-9eca-bec91eccdacd.png)
to this
![image](https://user-images.githubusercontent.com/30123016/117126801-91a55600-ad9b-11eb-96ed-983649f77767.png)
but since I work from different work stations I need it to be updated in the node modules

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
