### ISSUE TITLE
Graphql can't filter by local on sigle request 

### ISSUE THREAD

**Issue by violabg** [strapi/strapi#10257]
Graphql can't filter by local on sigle request 

### Steps to reproduce the behavior

Create a content type with localisation enabled, for example page
go to graphql doc  
only query pages is filtrable by locale
```graphql
pages(
     sort: String
     limit: Int
     start: Int
     where: JSON
     publicationState: PublicationState
l     ocale: String
): [Page]
```
query page is not filtrable by locale

```graphql
page(
     id: ID!
     publicationState: PublicationState
): Page
```

### Expected behavior

to be able to filter sigle query by locale as per documentation
https://strapi.io/documentation/developer-docs/latest/development/plugins/i18n.html#usage-with-the-graphql-plugin

### System

- Node.js version: v14
- Strapi version: 3.6.1

**Comment by derrickmehaffy** [comment]
We don't support filtering on `findOne` requests and `findOne` !== single-type.

FindOne requests by default only accept IDs and not filters. This is not a bug but is intended.
