### ISSUE TITLE
Regular expression to restrict html tags in any text field doesn't work on Strapi

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#10258]
## Bug report
Regular expression to restrict/block html tags in any text field doesn't work on Strapi

### Describe the bug
For Security purpose and to block XSS attacks. We want to restrict/block html tags on each text field. I tried few RegEx patterns but nothing is working.

Gone through below docs:
https://stackoverflow.com/questions/11229831/regular-expression-to-remove-html-tags-from-a-string/11230103
https://stackoverflow.com/questions/3790681/regular-expression-to-remove-html-tags
https://stackoverflow.com/questions/11229831/regular-expression-to-remove-html-tags-from-a-string/11230103

It's not working well with any RegEx patterns expect this one: `^(\s|\w|\d|/|[|/|\|^|$|*|+|?|.|(|)|[|]|{|}|,|'|"|!|@|#|%|&|)*?$`
**But i am looking for a better RegExp pattern.**

### Steps to reproduce the behavior

1. Go to: Content-type-builder
2. Click on Any collection
3. Open any text field, go to Advanced Settings, add your RegExp on RegExp pattern field to restrict/block html tags 
4. Now go to that collection and on that text field, try to test RegExp pattern with html tags.

### Expected behavior

Need a short RegExp pattern to restrict/block html tags. Html tags should be blocked with the RegExp pattern.

### System

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo
- Operating system: MAC

**Comment by vinod77** [comment]
HI. Found the correct RegExp pattern. We could use this one: `^[^<>]*?$`. It's working as expected.
This issue can be closed now. 
Thanks!

**Comment by derrickmehaffy** [comment]
Closing, thanks @vinod77
