### ISSUE TITLE
Unable to do basic npx install for Strapi with MongoDB connection (on MacOS)

### ISSUE THREAD

**Issue by mlxpress** [strapi/strapi#10268]
## Bug report

I run the _npx create-strapi-app my-project_ command and follow the custom setup steps, but the Strapi installation fails and the terminal shows the error message:

> ⛔️ Connection test failed: Command failed: npm install --prefix /var/folders/j9/2tnvqkkx22l7fk3xndjshp680000gn/T/strapid2157a5eebc0 strapi-connector-mongoose@3.6.1 npm ERR! Cannot read property 'spec' of undefined
> 
> npm ERR! A complete log of this run can be found in: npm ERR!
> /Users/admin/.npm/_logs/2021-05-09T18_01_51_464Z-debug.log

### Describe the bug

I am trying (unsuccessfully so far) to do a basic Strapi + Mongo installation, following the guides:

- https://developer.mongodb.com/how-to/strapi-headless-cms-with-atlas)
- https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations/databases/mongodb.html

I tried installing Strapi with MongoDB Atlas (didn't work), and separately tried installing it to connect with a different localhost Mongo database I set up (running in the background, and was able to connect with Robo3T on my Mac without issue), but in both cases it didn't work and the error message exactly was the same (see above).

Not sure if I am missing something basic here (pretty sure I followed the steps properly and pasted in the correct info from Mongo Atlas, i.e. host/username/password etc, during the setup)... I searched online for answers, without much success.  Some people have suggested it may be an issue of changing the npm config registry (i.e. _npm config set registry https://registry.npmjs.org/_), but that didn't fix anything for me.  Beyond that, I'm at a loss what the problem is.

### Steps to reproduce the behavior
For creating a new Strapi project with Mongo Atlas (preferred connection)

1. Open new terminal in VSCode
2. Run command: _npx create-strapi-app my-project_
3. _Choose your default database client_ mongo
4. _Database name:_ my-project
5. _Host:_ xxxxx.mongodb.net (pasted from my Mongo Atlas cluster)
6. _+srv connection:_ true
7. _Port (It will be ignored if you enable +srv):_ 27017
8. _Username:_ xxxxx (pasted in from Mongo Atlas user, with "all resources" permissions)
9. _Password:_ xxxxx (pasted in from Mongo Atlas user)
10. _Authentication database (Maybe "admin" or blank):_ (blank)
11. _Enable SSL connection:_ true

After following these steps, the terminal shows the error message above, followed by:

> Retrying...
> ? Choose your default database client (Use arrow keys)
> ❯ sqlite 
>   postgres 
>   mysql 
>   mongo 

No installation takes place and the Strapi project folder is not created on my Mac.

### Expected behavior

The installation is successful, and the created Strapi app is connected to Mongo Atlas

### System

- Node.js version: 14.15.2
- NPM version: 7.12.0
- Strapi version: (unsure, as Strapi does not install)
- Database: Mongo Atlas
- Operating system: MacOS Catalina (10.15.7)

**Comment by RileySeaburg** [comment]
I'm getting the same issue on a Postgres installation.

Tried multiple times with multiple versions of node to be sure.

**Comment by derrickmehaffy** [comment]
For now I would recommend running `npx create-strapi-app@latest yourProject --quickstart --no-run` which will generate it as SQLite and once it's generated:

- Swap out the `strapi-connector-bookshelf` for `strapi-connector-mongoose` 
- Remove the knex and sqlite packages
- Reinstall node_modules
- Modify the `./config/database.js` to the example in: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database

It may also be easier to use the URI method: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations/databases/mongodb.html#_5-update-and-replace-your-existing-database-js-config-file-for-the-appropriate-environment-development-production

---

**Please do keep in mind that we will be dropping support for MongoDB in the Strapi v4 version** see: https://github.com/strapi/strapi/issues/10186

**Comment by mlxpress** [comment]
I'll give your suggestions a try - thank you for the heads up!

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
