### ISSUE TITLE
Why pull request that fix prototype pollution was closed?

### ISSUE THREAD

**Issue by gustawdaniel** [strapi/strapi#10261]
This pull request

https://github.com/strapi/strapi/pull/10058

This vulnerability

https://www.npmjs.com/advisories/1649

**Comment by derrickmehaffy** [comment]
Hello, because the tests were failing on update meaning we would need to make changes to the code to update properly and we are already planning to drop MongoDB support: 

https://github.com/strapi/strapi/issues/10186

Setting as closed since there is no issue template.
