### ISSUE TITLE
strapi-plugin-upload permissions are broken when upgrading from 3.5.5 to 3.6.0

### ISSUE THREAD

**Issue by moretti** [strapi/strapi#10275]
### Describe the bug

A few weeks ago, before v3.6.1 was released, I tried to upgrade Strapi from version 3.5.5 to version 3.6.0 and I noticed it broke the user permissions for uploading new files.

Editors cannot longer see the file list on `/admin/plugins/upload`:

<img width="764" alt="Screenshot 2021-05-10 at 11 49 05" src="https://user-images.githubusercontent.com/1186409/117641463-7749ee80-b186-11eb-8336-7e725741cada.png">

<img width="805" alt="Screenshot 2021-05-10 at 11 49 31" src="https://user-images.githubusercontent.com/1186409/117641503-829d1a00-b186-11eb-8e92-92465a0e13a7.png">

Note that super admins can still read and edit the media library, so my temporary workaround was to made the user with the editor role a super admin.

I tried to fix the permissions using another a super-admin account, by clicking on `admin/settings/roles/${editorRoleId}` and editing the following section:

<img width="845" alt="Screenshot 2021-05-10 at 11 42 16" src="https://user-images.githubusercontent.com/1186409/117641709-c4c65b80-b186-11eb-8e2d-4c5c857a9aae.png">

but as you can see it's read-only, even if the current user is super admin.

I tried to rollback to version 3.5.x, but the permissions are still broken, so I suspect it's a problem in the database...is there any manual fix that I can apply to MongoDB in order to fix this problem?

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 3.5.5
- Database: MongoDB
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/10096

**Comment by moretti** [comment]
> Tested upgrade from 3.5.4 to 3.6.1 on MongoDB 4.0.24 (Docker). Fix works

My cluster is running MongoDB 4.4.5.

<img width="296" alt="Screenshot 2021-05-11 at 10 33 36" src="https://user-images.githubusercontent.com/1186409/117785776-306efe00-b245-11eb-9a24-d7bae0e7f39b.png">
