### ISSUE TITLE
Fail update relation when field "value" is present

### ISSUE THREAD

**Issue by XcrossD** [strapi/strapi#1027]
**Informations**
- **Node.js version**:
9.8.0
- **npm version**:
5.6.0
- **Strapi version**:
alpha.12
- **Database**:
mongodb 3.4.14
- **Operating system**:
windows 10

**What is the current behavior?**
Relations cannot be updated successfully when content type linked to contains the field "value"

**Steps to reproduce the problem**
1. Create a content type A containing a field "value"
2. Create content type B containing a relation field
3. Add relation C that links to A in B.
4. Update relation C

(using the same data structure in #886)

**What is the expected behavior?**
Relation is updated successfully.

**Suggested solutions**
One of the following:

1. Make it clear in the documents that value is a reserved field for strapi to work normally.
2. At `packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js`
`line 72: const cleanedData = cleanData(record[current], 'value', 'id');`
swap the order of `value` and 'id` for cleanData to prioritize using id.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @XcrossD can you confirm it's the same as this issue https://github.com/strapi/strapi/issues/791 but with `value`

**Comment by XcrossD** [comment]
@lauriejim I confirm that this is not a duplicate. Only the field "value" will prevent relation from updating. Although the end behavior seems like the same the error message is different.
`{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Cannot read property 'toString' of undefined"}]}]}`

**Comment by lauriejim** [comment]
Hello @XcrossD can you please update your Strapi version, try with new project and tell me if the issue persist.

**Comment by XcrossD** [comment]
@lauriejim Just tested with alpha.12.1.3, the error message becomes ` Cast to ObjectId failed for value "1.11111111111" at path "test"`
Data structure:
![capture](https://user-images.githubusercontent.com/6669029/40033874-e54f1862-582c-11e8-9431-2a4c585c782f.PNG)
![capture2](https://user-images.githubusercontent.com/6669029/40033881-e8906f62-582c-11e8-8c46-cb18348e8c27.PNG)

**Comment by lauriejim** [comment]
@XcrossD Did you test with a fresh new application ?

**Comment by XcrossD** [comment]
@lauriejim `strapi new myProj` with alpha.12.1.3, used the same database hosted on mLab.

**Comment by lauriejim** [comment]
@XcrossD Need to know on a fresh app and fresh database. Cause the issue can persist caused by migration or just a bug in Strapi.

**Comment by XcrossD** [comment]
@lauriejim I just updated to 12.2 and created a fresh database. It now says `value` is a reserved keyword, so I can't finish my test, but I guess that is one way to fix it? I only observed specifically this kind of interaction when there is `value` present. For now maybe it is okay but I'm not sure in the long run whether this kind of behavior will appear again with other keywords.

**Comment by lauriejim** [comment]
If it happen we will have to make it as reserved word.
