### ISSUE TITLE
Starting the app with PM2 on Windows logs error at NPM.CMD with Unexpected Token

### ISSUE THREAD

**Issue by sranjan-m** [strapi/strapi#10271]
I am trying to run the StrApi admin template on a Windows machine under pm2. I could start the ecosystem.config.js using `pm2 start ecosystem.config.js` but the admin site doesn't load on a browser. Checking the `pm2 logs` shows error at **C:\PROGRAM FILES\NODEJS\NPM.CMD** with **SyntaxError: Unexpected token ':'**.

![image](https://user-images.githubusercontent.com/18301541/117615863-f68bf200-b187-11eb-89f1-df15f51ed180.png)

My package.json is something like this.

```
{
  "name": "online-booking-str-api",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "production": "cross-env NODE_ENV=production npm run build",
    "start-production": "cross-env NODE_ENV=production npm start"
  },
  "devDependencies": {},
  "dependencies": {
    "cross-env": "^7.0.3",
    "strapi": "3.5.4",
    "strapi-admin": "3.5.4",
    "strapi-connector-mongoose": "3.5.4",
    "strapi-plugin-content-manager": "3.5.4",
    "strapi-plugin-content-type-builder": "3.5.4",
    "strapi-plugin-email": "3.5.4",
    "strapi-plugin-upload": "3.5.4",
    "strapi-plugin-users-permissions": "3.5.4",
    "strapi-utils": "3.5.4"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "<the alphanumeric uuid>"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}
```
And ecosystem.config.js is as following
```
module.exports = {
  apps: [
    {
      name: 'online-booking-str-api',
      script: 'npm',
      args: 'start-production', //'start'
      env: {
        NODE_ENV: 'production',
      },
      exp_backoff_restart_delay: 100,
    },
  ],
};
```
### System
- Node.js version: 14.16.1
- NPM version: 6.14.4
- Strapi version: 3.5.4
- Database: MongoDB
- Operating system: Windows 10

I am sorry if I'm missing anything in the configuration or installation. Any workaround or solution for this will be really helpful.
Thanks.

**Comment by sranjan-m** [comment]
Hi. Thanks for letting me know. I have already included the things you might need to help me out in this and updated my question. Kindly take a look and please let me know if I am missing any steps or configuration to make it work under pm2.
Thank you.

**Comment by sranjan-m** [comment]
Able to solve the above error shown in pm2 logs by following this [solution](https://github.com/Unitech/pm2/issues/2808#issuecomment-367352136).
But now I'm facing this new [issue](https://github.com/Unitech/pm2/issues/2808#issuecomment-839559064)

Not sure if the problem is with StrApi or pm2 or in any of my configuration. 
Thanks.

**Comment by davistran86** [comment]
Hi, I got the same issue when using with pm2 on Windows

**Comment by derrickmehaffy** [comment]
This is unlikely to be a strapi issue, marking as closed. For further discussion on this please use our forums or Discord
