### ISSUE TITLE
Deploy on subfolder

### ISSUE THREAD

**Issue by federicocappellotto97** [strapi/strapi#10282]
I would like to deploy strapi in a subfolder, https://meitei.it/api, but it says **not found**
If i go to https://meitei.it/api/admin i can see the right page title, but i got some error in console that say some files are not found. And in fact the paths of those files are wrong. 

I tried to deploy strapi on a subdomain, and everything went right, but i need to deploy it on a subdomain
Main website: meitei.it
Strapi: meitei.it/api

This is my config file:
./config/env/production/server.js
```
module.exports = ({ env }) => ({
    host: env('HOST', '0.0.0.0'),
    port: env.int('PORT', 1337),
    url: '/api',
    admin: {
        auth: {
            secret: env('ADMIN_JWT_SECRET', 'cde685fba4fba00d0c4dfae60ddc230d'),
        },
    },
});
```

### System

- Node.js version: 14.16.1
- NPM version:
- Strapi version: latest
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
You need a proxy, see: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#optional-software-guides
