### ISSUE TITLE
Error when creating a new Collection Type

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#10296]
When creating a new Collection Type, I get this error message. It happens just in production (Heroku - PostgreSQL), but not on local (SQLite)

After deploying, the app, starts and the admin works as expected. But when going to the new Collection (in this case, a collection called "Langs"), it gives this error in console:

`error error: select count(*) as "count" from "langs" - relation "langs" does not exist`

The collection had just two plain text fields (no relations with other collections).

The same happens when creating the same collection with different names.

- Node.js version: node v12.22.1
- NPM version: 6.14.12
- Strapi version: 3.5.3
- Database: PostgreSQL
- Operating system: Heroku

**Comment by Jesus82** [comment]
Solved by setting 
```
connections: {
        default: {
          options: {
            useNullAsDefault: true,
          },
        }
      }
```
As suggested here https://github.com/strapi/strapi/issues/7346#issuecomment-670169627

**Comment by Salaahuddiin** [comment]
Thanks for the solution, it worked.

I was struggling this morning with the same thing, it just appeared, I don't know how...
