### ISSUE TITLE
Default values not working when item is created via strapi.query

### ISSUE THREAD

**Issue by luixal** [strapi/strapi#10295]
### Describe the bug

Having an entity-type with a boolean field having its default value set to `false`, it works fine when creating new entities using HTTP requests, but if you create an entity using `strapi.query('myEntityType').create({ ... })`, that boolean field is set to null.

### Steps to reproduce the behavior

1. Create a new entity type, i.e: `book`.
2. Add a boolean field and set its default value to `false`, i.e.: `read`
3. Create a new entity for that type through an HTTP request without passing the `read` field (using Postman or Axios, for example).
4. Check the record, that the `read` field has been set to `false`.
5. Now, create a new book using code without passing the `read` field. i.e.: `strapi.query('book').create({ title: 'Title1' })`
6. Check it and you'll see the `read` field is set to `null` instead of `false`.

### Expected behavior

The `read` field should be `false` in any case a new book is created, not mattering the way you use to create it.

### System

- Node.js version: 14.4.0
- NPM version: 6.14.9
- Strapi version:  3.5.3
- Database: PostgreSQL
- Operating system: Debfian

**Comment by luixal** [comment]
There are more differences, for example the `created_by` and `updated_by` fields are also not filled if you create the entity programatically (although I'm doing it inside a lifecycle hook, which has needed data in the context).

**Comment by luixal** [comment]
Seeing the `status: pending reproduction` label, I've made it for you. Please, find the repo here:

https://github.com/luixal/strapi-issue-10295

Basically it has a collection colled `books` with fields:

* `Title`: type text
* `Description`: type text
* `Read`: boolean, default value is `false`

When I create a new book by calling the _auto-handled_ POST method like this:

```shell
curl --location --request POST 'http://localhost:1337/books/custom' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Title 1",
    "description": "My first book"
}'
```

it creates the book, managing proper deafults (`read` is set to false):

```json
{
    "id": 1,
    "title": "Title 1",
    "description": "My first book",
    "read": false
}
```

Then, I declared a custom endpoint for creating books, which code is this:

```js
myCustomEndpoint: async(ctx) => {
        const result = await strapi.query('books').create({ title: ctx.request.body.title, description: ctx.request.body.description });
        return result;
    }
```

and configured it in the routes file like this:

```js
...
{
  "method": "POST",
  "path": "/books/custom",
  "handler": "books.myCustomEndpoint",
  "config": {
    "policies": []
    }
},
...
```

Give it proper permissions in the strapi admin panel and try it:

```shell
curl --location --request POST 'http://localhost:1337/books/custom' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Title 2",
    "description": "My second book"
}'
```

in this case, the `read` field is set to `null`:

```json
{
    "id": 2,
    "title": "Title 2",
    "description": "My second book",
    "read": null,
    "created_at": "2021-05-12T09:38:38.054Z",
    "updated_at": "2021-05-12T09:38:38.054Z"
}
```

**Extra Info**
I'm not sure (and I'm not reproducing it for keeping this issue focused), but I think the same thing happens to `created_by` and `updated_by` _auto-populated_ field when user is authenticated.

**Comment by kasonde** [comment]
Hi @luixal thanks for the extra info. 
I can confirm that the issue also exists with sqlite3 from my investigations.

**Comment by luixal** [comment]
Yes, I haven't tried with mongo (since it's going to be discontinued...) but I guess it is directly related to logic handling.
