### ISSUE TITLE
Dynamic zone fetch not showing nested dynamic zone fields of relationship

### ISSUE THREAD

**Issue by davidmgrana** [strapi/strapi#10300]
This is the current response:

```
{
  "id": 1,
  "name": "Aerial",
  "slug": "aerial",
  "published_at": "2021-05-07T22:33:18.772Z",
  "created_at": "2021-05-07T22:33:07.566Z",
  "updated_at": "2021-05-11T20:47:25.610Z",
  "sections": [
    {
      "__component": "sections.rotating-text",
      "id": 1,
      "text": "last chance"
    },
    {
      "__component": "sections.product-grid",
      "id": 1,
      "product_grid_layout": {
        "id": 1,
        "name": "crazy layout",
        "published_at": "2021-05-11T20:47:12.864Z",
        "created_at": "2021-05-11T20:47:01.470Z",
        "updated_at": "2021-05-11T20:47:12.885Z"
      }
    }
  ]
}
```

product_grid_layout  is a relationship of the sections.product-grid component and it also has a dynamic zone with components which are not being fetched for some reason, as you can see it's only pulling id, name and the timestamps.

this is what a findone call to that same product grid layout looks like:

```
{
  "id": 1,
  "name": "crazy layout",
  "published_at": "2021-05-11T20:47:12.864Z",
  "created_at": "2021-05-11T20:47:01.470Z",
  "updated_at": "2021-05-11T20:47:12.885Z",
  "grid": [
    {
      "__component": "sections.article",
      "id": 2,
      "title": "my article",
      "order": 3
    }
  ]
}
```

as you can see it does grab the grid dynamic zone this one but i want to avoid doing more than 1 fetch request, Strapi should be doing it automatically right?

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
