### ISSUE TITLE
It is possible to login unconfirmed authenticated users.

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#10308]
## Bug report

It is possible to login on Strapi using a unconfirmed unauthenticated user.

### Describe the bug

When we login using the API(GraphQL), we can get logged in on session even if we are not confirmed yet when we should not get access to the platform if we are not confirmed.

### Steps to reproduce the behavior

1. Register a user from the API(GraphQL), it will be confirmed by default but updated to be unconfirmed.
2. Check the user was create on the admin panel.
3. Do login from the API(GraphQL).
4. See error: it is logged in, the `jwt` comes even when the user is not confirmed yet.

### Expected behavior
It should not be able to login on Strapi while the user is not confirmed.

### Screenshots
![image](https://user-images.githubusercontent.com/5034215/118013207-8bdee000-b35a-11eb-99f6-7f1784ac6b76.png)

### Code snippets

`package.json`:
```json
"dependencies": {
    "knex": "0.21.18",
    "sqlite3": "5.0.0",
    "strapi": "3.6.2",
    "strapi-admin": "3.6.2",
    "strapi-connector-bookshelf": "3.6.2",
    "strapi-plugin-content-manager": "3.6.2",
    "strapi-plugin-content-type-builder": "3.6.2",
    "strapi-plugin-email": "3.6.2",
    "strapi-plugin-graphql": "3.6.2",
    "strapi-plugin-i18n": "3.6.2",
    "strapi-plugin-upload": "3.6.2",
    "strapi-plugin-users-permissions": "3.6.2",
    "strapi-provider-email-amazon-ses": "^3.6.2",
    "strapi-provider-upload-aws-s3": "^3.6.2",
    "strapi-utils": "3.6.2"
  },
```

### System

- Node.js version: `v14.16.1`
- NPM version: `6.14.12`
- Strapi version: `3.6.2`
- Database: `SQLite`
- Operating system: `Deepin 20.2 x86_64`

### Additional context
Our authentication workflow is the next:

1. A user does registration through in the application through the API(GraphQL).
2. This user must be unconfirmed till the admin confirm it.
3. The admin confirm it.
4. The user can then login on the plartfom.

To enable this behaviour avoiding to send confirmation emails, we just opted by not enable the _confirm email_ workflow but update the newly create user after its registration (_afterCreate lifecycle_).

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by SalahAdDin** [comment]
People, I opened the [question.](https://forum.strapi.io/t/it-is-possible-to-login-unconfirmed-authenticated-users/4926)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/it-is-possible-to-login-unconfirmed-authenticated-users/4926/4

**Comment by SalahAdDin** [comment]
> This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:
> 
> https://forum.strapi.io/t/it-is-possible-to-login-unconfirmed-authenticated-users/4926/4

Yeah, I opened that question and it seems to be a rightfull issue.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/it-is-possible-to-login-unconfirmed-authenticated-users/4926/6

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/it-is-possible-to-login-unconfirmed-authenticated-users/4926/8
