### ISSUE TITLE
Collection Types missing from Content-Types Builder after upgrade

### ISSUE THREAD

**Issue by Pythe1337N** [strapi/strapi#10303]
### Describe the bug

When upgrading from 3.4.6 to 3.6.2 all Collection Types is missing in the Content-Types Builder. Everything works as expected, but the Collection Type does not show and cannot be edited.

**Edit: Upgraded first to 3.5.4 and it still works. But going to 3.6.0 triggers this bug.**

### Steps to reproduce the behavior

1. Create new Collection Type in version 3.4.6
2. Upgrade to version 3.6.2
3. Collection Type list in Content-Types Builder is now empty.
4. Revert to  3.4.6 and the list is populated again.

### Expected behavior

The list should be populated after upgrade.

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: 3.4.6 / 3.6.2
- Database: MongoDB
- Operating system: Ubuntu 18.04.5

**Comment by derrickmehaffy** [comment]
Can't reproduce, what I did:

- Created a project on 3.4.6
- Created an article content-type with 2 fields (title/body)
- Added Data to articles model
- Shut down server
- Wiped `node_modules`, `yarn.lock`, `build`, and `.cache`
- Modified package.json with new versions
- Reinstalled node_modules
- Rebuilt the Admin
- Started server
- Saw no issue

v3.4.6:
![image](https://user-images.githubusercontent.com/8593673/118044200-37703c00-b32b-11eb-9f91-e4d20d7f591d.png)

v3.6.2:
![image](https://user-images.githubusercontent.com/8593673/118044220-3c34f000-b32b-11eb-9607-5d09d8617eb0.png)

**Comment by Pythe1337N** [comment]
Thanks for verifying that it works. Completely wiping `node_modules`, `build` and `.cache` and doing a fresh install resolved the issue.
