### ISSUE TITLE
Strapi's roles on Mongo Atlas, Full cluster access?

### ISSUE THREAD

**Issue by btbensoft** [strapi/strapi#10316]
### Describe

I'm using strapi with **mongoDb Atlas**.
On my Atlas'cluster i have sereral database, To secure my strapi database, I want to give it access only to **its** database

If I restrict the roles (full role) to the strapi database, it doesn't work
![image](https://user-images.githubusercontent.com/36570423/118225616-bd07ff00-b485-11eb-9db6-4dd13a4c4c71.png)
![image](https://user-images.githubusercontent.com/36570423/118225236-07d54700-b485-11eb-9a7d-1b013f9b8711.png)

But If i give full roles to my cluster (all database) is working 

![image](https://user-images.githubusercontent.com/36570423/118225284-20ddf800-b485-11eb-9984-4923de0ac85c.png)
![image](https://user-images.githubusercontent.com/36570423/118225899-343d9300-b486-11eb-8bfc-c79a42bf3b3a.png)

Why do you need full access to my cluster?
Can you tell me which **roles I need**?

Thanks you for your help

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
