### ISSUE TITLE
Documentation plugin filter operators are useless

### ISSUE THREAD

**Issue by andraspalfi** [strapi/strapi#10317]
### Describe the bug

Documentation plugin generates swagger doc where the _operators_ are added as _parameters_, but _fields_ are missing.
A valid filtering query on a field looks like `http://localhost:1337/<content-type>?<field_name>_gt=<value>`
However according to doc plugin it tries to query like `http://localhost:1337/<content-type>?_gt=<value>` so __gt_ added as field which expects a value but actually it is just an operator can be used on a field. 
It is impossible to pass the field itself and use filters on fields.
Would be great to provide examples how to use field-filters as well.

### Steps to reproduce the behavior

Generate swagger doc with Documentation plugin. Try it on swagger UI.

### Expected behavior

Doc plugin should generate parameters for each field, and each field should have an operator extension. 
Instead of '_gt' generate '<fieldname>_gt' and for all the operators which usable for fields.

### System

- Strapi version: 3.6.0

**Comment by foresightyj** [comment]
yeah, it is completely useless right now.  so for the time being, I am removing all filter operators as per https://github.com/strapi/strapi/issues/7219.

**Comment by derrickmehaffy** [comment]
fixed in v4, marking as closed
