### ISSUE TITLE
Installation not working on ARM64

### ISSUE THREAD

**Issue by bahamut657** [strapi/strapi#10313]
## Bug report
Installing STRAPI inside docker container based on NodeJS ARM64 image (12 or 14 no difference) results in error building SHARP (particulary, it returns error during VIPS build). No problem at all following the same procedure for x86_64.

### Describe the bug
It is not possible to use STRAPI in ARM64/ARMv8 

### Steps to reproduce the behavior
Create a Dockerfile containing these lines and try to build
```
FROM node:14-buster
WORKDIR /strapi
ENV NODE_ENV production
RUN apt update && apt-get -y install libvips-dev
RUN apt-get -y install glib2.0-dev expat gobject-introspection libgtk2.0-doc 
RUN yarn config set network-timeout 600000 && yarn create strapi-app /strapi --quickstart
EXPOSE 1337
CMD [ "yarn", "start" ]
```

It ends up printing this:

```
Directory: /strapi/node_modules/sharp
Output:
sharp: Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.10.6
sharp: Attempting to build from source via node-gyp but this may fail due to the above error
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.16.1 | linux | arm64
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v14.16.1/node-v14.16.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.16.1/node-v14.16.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.16.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.16.1/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/strapi/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.16.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.16.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/strapi/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/strapi/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:24:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:137: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/strapi/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.21-sunxi64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /strapi/node_modules/sharp
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
```

### Expected behavior
I'm expecting STRAPI works on ARMv8/ARM64

### System

- Node.js version: 12 or 14 (from DockerHub)
- Strapi version: Current release (May 2021)
- Database: N/A 
- Operating system: Armbian 10 (ARM64)

### Additional context
Installed manually glib2.0-dev expat gobject-introspection and libgtk2.0 as suggested in SHARP documentation with no luck.

**Comment by derrickmehaffy** [comment]
> /usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory

You are missing standard build tools and armbian is not a supported environment (can be quite tricky with docker). In this case, the only thing I can recommend is to build the admin panel outside of the docker container, maybe inside a CI/CD or use a docker image that comes with your standard Debian build tools (`build-essential`).

Sharp (libvips) comes in two ways, either:

1) they have a pre-built binary ready to download for your environment 
2) the entire libvips package is compiled from source for your environment 

There have been numerous issues with libvips on ARM (especially with Apples M1 CPU) that are outside our control.

For now I'm marking this issue as closed, but please feel free to continue the discussion.

**Comment by bahamut657** [comment]
My docker image got already installed build-essential (it is based on node:12-buster or node:14-buster)
I verified the libvips-dev installed and it result to be version 8.7.4.
Can I bypass the issue installing manually the libvips 8.10.6 (beta)? This is written inside the SHARP's package.json.
I'm not running on Apples M1 but on RPI4...Any chance to run STRAPI there?

**Comment by bahamut657** [comment]
Just for share and helps other stucked in that problem.
I've completed the STRAPI installation using arm64 (Armbian 10) inside docker container.
Here my Dockerfile (It seems libvips in Armbian is old, and it is required to compile  manually libvips 8.10.6 [beta] from github) 

```
FROM node:14-buster
WORKDIR /strapi
ENV NODE_ENV production
RUN apt update && apt-get -y install libvips-dev
RUN apt-get -y install glib2.0-dev expat gobject-introspection libgtk2.0-doc 
RUN wget https://github.com/libvips/libvips/releases/download/v8.10.6-beta/vips-8.10.6.tar.gz
RUN tar xf vips-8.10.6.tar.gz
RUN cd vips-8.10.6 && ./configure && make && make install && rm -rf vips-8.10.6
RUN yarn config set network-timeout 600000 && yarn create strapi-app /strapi --quickstart
EXPOSE 1337
CMD [ "yarn", "start" ]
```

**Comment by PandelisZ** [comment]
I'd like to re-open this discussion if there's any desire to backport an update to the strapi-plugin-upload@3 package I'm more than happy to send in a PR. I don't see a v3 branch however that I can easily make a PR into.

the latest version of the sharp package works on arm macs and I am now using it in a v3 install of strapi.

> Please can everyone using Apple M1 devices upgrade to sharp v0.28.0
https://github.com/lovell/sharp/issues/2460

**Comment by derrickmehaffy** [comment]
> I'd like to re-open this discussion if there's any desire to backport an update to the strapi-plugin-upload@3 package I'm more than happy to send in a PR. I don't see a v3 branch however that I can easily make a PR into.
> 
> the latest version of the sharp package works on arm macs and I am now using it in a v3 install of strapi.
> 
> > Please can everyone using Apple M1 devices upgrade to sharp v0.28.0
> > [lovell/sharp#2460](https://github.com/lovell/sharp/issues/2460)

At this time we are not backporting into v3, only fixing critical issues or security problems.

**Comment by derrickmehaffy** [comment]
(though please do feel free to submit PRs to the v4)
