### ISSUE TITLE
'Fill in from another locale' only shows the initial default locale

### ISSUE THREAD

**Issue by Naxos84** [strapi/strapi#10328]
### Describe the bug

When creating localized content and want to fill a new locale entry from another locale I expect to have all setup locales as selection. Currently I only have english.

### Steps to reproduce the behavior

Create a new project.

Add a collection type.
Setup multiple languages in settings. (i.e. english, german, french)

Create an entry for the created collection type. (en)
Save.
Create another entry for a different language. (de)
Save.
Select a third language. (fr)
Click "Fill in from another locale".

It only shows english locale.

### Expected behavior

It shows english AND german locale.

First I assumed it is only showing the default language so I changed the default language to (de).
Clicked "Fill in from another locale".
Still it only shows english as selection option.

### System

- Node.js version: 12.16.0
- NPM version: 6.13.4
- Strapi version: 3.6.2
- Database: SqLite
- Operating system: Windows

**Comment by sam-pires** [comment]
Hello @Naxos84 
Thanks for sharing that issue, it should display English AND German indeed.

Could you share some further information, please?
- When you say "Create another entry for a different language. (de)" you do it from the Edit view right, by switching language?

**Comment by Naxos84** [comment]
Hi @sam-pires Sorry for possible being a bit short on the description.

What am I doing in full detail:

Create a collection type "My-Content"
Add a field of type string "my_field"
Save.
Go to settings and add locales (de, fr).

Create an entry for "My-Content"
![grafik](https://user-images.githubusercontent.com/17813025/118500255-ef388b80-b727-11eb-8027-d2a269d9b812.png)
fill the field with some value.
Save.
Inside "Create entry of 'My-Content'" switch the locale  to "de".
![grafik](https://user-images.githubusercontent.com/17813025/118500469-18f1b280-b728-11eb-8718-7657c7a335e5.png)
Fill in some value.
Save.
Now switch fro Frensh (fr).
Select "Fill in from another locale".
Open the drop down menu.
![grafik](https://user-images.githubusercontent.com/17813025/118500648-4179ac80-b728-11eb-9ba2-331a05e2b3c9.png)

There I expect to see english AND german.

**Comment by derrickmehaffy** [comment]
I can confirm this issue on v3.6.2, sample repo with included sqlite DB.

Login is:
```
test@test.com
Test1234!
```

[test10328.zip](https://github.com/strapi/strapi/files/6496849/test10328.zip)

**Comment by derrickmehaffy** [comment]
@Naxos84 I've confirmed the fix in https://github.com/strapi/strapi/pull/10339 but if you need it right away and can't wait for v3.6.3 the fix is easy enough to add with extensions.
