### ISSUE TITLE
Calling ctx.forbidden() in controller not handled correctly by graphql

### ISSUE THREAD

**Issue by sargreal** [strapi/strapi#10324]
### Describe the bug

Calling the methods `ctx.forbidden()` or `ctx.unauthorized()` in a customized controller does not return forbidden or unauthorized error in graphql

### Steps to reproduce the behavior

1. Customize a controller, for example the delete and call the method `ctx.forbidden()` in some circumstance
```js
module.exports = {
  async delete(ctx) {
    const { id } = ctx.params;

    const [restaurant] = await strapi.services.restaurant.find({
      id,
      "owner.id": ctx.state?.user?.id,
    });
    let entity;
    if (restaurant) {
      entity = await strapi.services.restaurant.delete({ id });
    } else {
      ctx.forbidden("You are not allowed to delete this entry");
    }
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
}
```
2. Execute a graphql query with that circumstance
```graphql
mutation($input:deleteRestaurantInput){
  deleteRestaurant(input: {where: {id: "1"}}) {
    restaurant {
      id
    }
  }
}
```
3. Graphql returns internal server error if non-nullable field is requested as response, otherwise no error is shown

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Restaurant.id.",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "deleteRestaurant",
        "restaurant",
        "id"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Restaurant.id.",
            "    at completeValue (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:559:13)",
            "    at resolveField (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:590:12)",
            "    at resolveField (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:472:19)",
            "    at executeFields (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:292:18)",
            "    at collectAndExecuteSubfields (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:590:12)",
            "    at /home/felix/Documents/fekide/it/fekide/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:469:16"
          ]
        }
      }
    }
  ],
  "data": {
    "deleteRestaurant": {
      "restaurant": null
    }
  }
}
```

### Expected behavior

The graphql error should be a forbidden error and optimally contain the message passed to ctx.forbidden

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.17.0 
- NPM version: 6.14.13
- Strapi version: 3.6.1 
- Database: postgres
- Operating system: Manjaro Linux

### Additional context

I think using policies would handle this better, however i did not try that yet. They are also not as simple since one cannot really test if the current user is the owner without getting the data first, which is probably not what should be done in a policy.

This problem should also happen in the guide for [creating the isOwner policy](https://strapi.io/documentation/developer-docs/latest/guides/is-owner.html#limit-the-update)

**Comment by tention** [comment]
Faced the same problem, used the following as workaround.

```
throw strapi.errors.unauthorized('Unauthorized');
```

**Comment by dannylo-gaivota** [comment]
Hello  @sargreal 

try this.... 


on controller
`async delete(ctx) {
        const { id } = ctx.params;

        const [restaurant] = await strapi.services.restaurant.find({
            owner: ctx.state.user.id, // here
        });
        let entity;
        if (restaurant) {
            entity = await strapi.services.restaurant.delete({ id });
        } else {
            ctx.forbidden("You are not allowed to delete this entry");
        }
        return sanitizeEntity(entity, { model: strapi.models.restaurant });
    },`

mutation
`mutation{
   deleteRestaurant(input: {where: {id: "60a509df962006003000f324"}}) { // <= pass an correct id format
    restaurant {
      id
    }
  }

}`

**Comment by sargreal** [comment]
@dannylo-gaivota Thanks for the help, however the id formatting is not the problem. I have already tried several other queries and it is always the same error.

**Comment by dannylo-gaivota** [comment]
> @dannylo-gaivota Thanks for the help, however the id formatting is not the problem. I have already tried several other queries and it is always the same error.

Try that query

` const [restaurant] = await strapi.services.restaurant.find({
            owner: ctx.state.user.id, // <=
        });`

**Comment by sargreal** [comment]
@dannylo-gaivota Thanks again, but this is still not the problem. I actually want to verify if the exact restaurant belongs to the owner. 

But I could actually now verify that this problem is also the same for `policies`. When adding a `ratelimit` to some query and hitting it, the response is not something like an error with "Sorry you have hit the ratelimit. Try again later", but exactly the same error (just in another form now that it is a different query):
```graphql
query {
  restaurants {
    id
  }
}
```

```json
{
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field \"Query.restaurants\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "jobOffers"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Expected Iterable, but did not find one for field \"Query.restaurants\".",
          "stacktrace": [
            "GraphQLError: Expected Iterable, but did not find one for field \"Query.restaurants\".",
            "    at completeListValue (/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:641:11)",
            "    at completeValue (/api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:572:12)",
            "    at /api/node_modules/strapi-plugin-graphql/node_modules/graphql/execution/execute.js:469:16",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": {
    "restaurants": null
  }
}
```

**Comment by Mortalife** [comment]
> @dannylo-gaivota Thanks again, but this is still not the problem. I actually want to verify if the exact restaurant belongs to the owner.
> 
> But I could actually now verify that this problem is also the same for `policies`. When adding a `ratelimit` to some query and hitting it, the response is not something like an error with "Sorry you have hit the ratelimit. Try again later", but exactly the same error (just in another form now that it is a different query):
> 

I spent the a couple days tried to figure this one out, I turned off ratelimit and it went away. The more I use graphql within strapi the more I realise its integration is lacking.

**Comment by derrickmehaffy** [comment]
> > @dannylo-gaivota Thanks again, but this is still not the problem. I actually want to verify if the exact restaurant belongs to the owner.
> > But I could actually now verify that this problem is also the same for `policies`. When adding a `ratelimit` to some query and hitting it, the response is not something like an error with "Sorry you have hit the ratelimit. Try again later", but exactly the same error (just in another form now that it is a different query):
> 
> I spent the a couple days tried to figure the "Expected Iterable, but did not find one for field" error out, I turned off ratelimit and it went away. The more I use graphql within strapi the more I realise its integration is lacking.

We are almost completely rewriting and merging GraphQL into the core of Strapi in the v4 :)

**Comment by jkkang-kosac** [comment]
Do you have plan to fix this bug in v3?

I know that your team does not keep supporting MongoDB in v4 so I need this fix for v3.
Custom APIs are okay because ctx.throw(403, ...) can be used instead of ctx.forbidden(...)
but strapi-plugin-users-permissions package uses this pattern a lot.
So when I call user-permission related function in graphql, I cannot get correct error reason and it's a bit annoying.

You may already know the reason but I'll let you know what I found in your sources. 
You use boom middleware to convert Error to http compatible response but in graphql resolvers-builder only object which passed lodash isError() is throwed so this response object is processed as normal document and failed in the end.
So I think more information is necessary in graphql resolvers-builder to know it's an Error.

**Comment by jkkang-kosac** [comment]
@derrickmehaffy 

> We are almost completely rewriting and merging GraphQL into the core of Strapi in the v4 :)

Do you have plan to fix this bug in v3?

I know that your team does not keep supporting MongoDB in v4 so I need this fix for v3.
Custom APIs are okay because ctx.throw(403, ...) can be used instead of ctx.forbidden(...)
but strapi-plugin-users-permissions package uses this pattern a lot.
So when I call user-permission related function in graphql, I cannot get correct error reason and it's a bit annoying.

You may already know the reason but I'll let you know what I found in your sources.
You use boom middleware to convert Error to http compatible response but in graphql resolvers-builder only object which passed lodash isError() is throwed so this response object is processed as normal document and failed in the end.
So I think more information is necessary in graphql resolvers-builder to know it's an Error.

**Comment by derrickmehaffy** [comment]
We have an entirely different and stable method of throwing errors in v4, marking this as closed as it shouldn't be an issue anymore
