### ISSUE TITLE
Theme Color Change

### ISSUE THREAD

**Issue by LuisValgoi** [strapi/strapi#10323]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Super User can have the ability to change the accent (primary) color of the `strapi-admin`.

### Why is it needed?

In order to deliver the CMS for customers, its always a good idea to customize and to deliver a unique platform.

### Suggested solution(s)

We could have a option of `Appearence` under the `Settings` menus and a color picker. When the user choose this, the `color` & `background-color` in divs, buttons, labels, input and all other components, will change accordingly.

PS.: I think it would be good to have a refactor in the `strapi-admin` components (the `Buffet.js` library), to use a color variables. Something like this: (`--primary-color: #${USER_SELECTED_ACCENT_COLOR}`).

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Duplicate: https://portal.productboard.com/strapi/1-roadmap/c/11-administration-user-interface
