### ISSUE TITLE
Extraction depth

### ISSUE THREAD

**Issue by Dronozavr** [strapi/strapi#1032]
Hello. I have created Content Type `Mentor`, it has a field  `avatar` which is equal to media field type.
Also I have a Content type `Course` which can include a lot of `Mentors` . My issue is that when I extract all `Courses` all data inside nested `mentors`  field are there except the `avatar` which is equal to `null`. When I extract `mentors` in separated request everything is fine. It looks like one more nesting from related content type. Can you help me please how can I extract data related to avatar?

**Comment by lauriejim** [comment]
Please follow the issue template. I will re-open this issue when it's will done.
