### ISSUE TITLE
Add more locales

### ISSUE THREAD

**Issue by tuube** [strapi/strapi#10329]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Could Sámi locales be added to the available locales in i18n plugin? 

Especially Northern Sámi and Inari Sámi:
https://iso639-3.sil.org/code/smn
https://iso639-3.sil.org/code/sme

### Why is it needed?

Current locales are missing some locales that I need.

### Suggested solution(s)

Add Sámi locales to selectable locales for content.

**Comment by JWesorick** [comment]
Is there a reason not all locales are included? (Or just a free form value.)

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by aeadedoyin** [comment]
@JWesorick Could the plugin allow for extension where I add missing locales manually?

For me: I want to add the missing English ISOs, there are several of them here that would be nice to have: https://www.localeplanet.com/icu/

Use case: Where content is different for a locale but it's still in English.

**Comment by JWesorick** [comment]
@aeadedoyin I don't understand Strapi enough to know why the current implementation was chosen. But if you look at my PR where I added all the requested locales I knew about you could add the ones you need easy enough. #13875

**Comment by JWesorick** [comment]
To any maintainer this issue can be closed as the Sámi locales were added in #13875

**Comment by derrickmehaffy** [comment]
Thank you @JWesorick
