### ISSUE TITLE
Get 400 error while creating collection type with name 'news'

### ISSUE THREAD

**Issue by isimaka** [strapi/strapi#10327]
### Describe the bug

Get 400 error while creating collection type with name 'news'.

### Steps to reproduce the behavior

1. [According to official Quick Start guide](https://strapi.io/documentation/developer-docs/latest/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project): `npx create-strapi-app my-project --quickstart`
2. Log into http://localhost:1337/admin, create collection type, fill `Display name` with `news`, hit `Continue`
3. Select collection type `Text`, fill `Name` with `title`, hit `Finish`, hit `Save`
4. See error in browser: 'An error occurred'. See error in terminal: `debug POST /content-type-builder/content-types (51 ms) 400`
5. I tried use `ews` `navy` `new` `newss` as `Display name`, all work fine.

### Expected behavior

`news` is not a sensitive word or illegal string, it is expected to be accepted.

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- Strapi version: v3.6.2
- Database: SQLite
- Operating system: macOS Big Sur 11.2.3

I know I'd better use some other words for substitution as `Display name`, but maybe this is a bug would relates to other critical bugs.
Thanks in advance!

**Comment by kasonde** [comment]
Hi @isimaka , so taking a look at the console log of the error tells us this: `"Content Type name 'news' cannot be pluralized. 
Suggestion: add Item after the name (e.g News -> NewsItem)."`. This does however require a discussion because 'News' is uncountable. It has no plural. cc @sam-pires @maevalienard

**Comment by isimaka** [comment]
WOW, thanks for your timely help and effort, @kasonde and Strapi team!

It is very reasonable that 'type' should be singular.

Though it would take some time to fix this tiny bug due to regular procedure, I am much more confident on Strapi due to your thunder blazing fast and kindly help!

Feel free to close this issue anytime! :grin: :love_you_gesture:

**Comment by kasonde** [comment]
Sure thing. I'll close it as there is an ongoing conversion here #1198 that has information on how you can work around this issue if it arises again.
