### ISSUE TITLE
POST : Passing raw json as text gives validation error.

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#10325]
### Screenshots
![image](https://user-images.githubusercontent.com/71498747/118370818-19bf0300-b5c7-11eb-9599-9d27c519bb8c.png)

![image](https://user-images.githubusercontent.com/71498747/118370826-28a5b580-b5c7-11eb-9010-36b6bf32bac5.png)

### System

- Node.js version: v14
- NPM version: 6.x
- Strapi version: 3.6.2
- Database: Sqlite
- Operating system: CentOs

**Comment by derrickmehaffy** [comment]
The Text option in postman doesn't have the proper `content-type` headers, you must use `application/json` which is set when you select the JSON option in Postman.

Marking as closed as this is not a bug and we have never supported the `text` option in postman.

**Comment by ssoftwares** [comment]
Thank you for your time sir @derrickmehaffy
