### ISSUE TITLE
Content-Type builder, error when creating or deleting Content-Type

### ISSUE THREAD

**Issue by adamkpurdy** [strapi/strapi#10335]
### Describe the bug
I recently successfully set up Strapi on Google Cloud Run with Postgres in Cloud SQL when I was running Strapi v3.5.3 back in March. At the time I was able to create and delete content types without issue. Then this morning I logged into the instance and deleting or creating content type is failing with a 503 error when the `_health` function is ran in the delete or save process. Adding records to the collection is still successful. I've tried updating to 3.6.2 and back to 3.5.3, but the error still persists. Also currious is this is the same issue as [#10310](https://github.com/strapi/strapi/issues/10310). Any help or suggestions would be helpful. Thanks in advance.

### Steps to reproduce the behavior

1. Install any version of Strapi between 3.5.3 & 3.6.2
2. Run build script locally
3. Do a gcr build
4. Deploy to cloud run
5. Log into admin
6. Create new content type

### Expected behavior

The content-type should save properly and be reflected in the left hand menu in the admin dashboard

### Screenshots
**Browser error:**
![image](https://user-images.githubusercontent.com/1054644/118544974-02495c80-b724-11eb-8fef-d3a786e3ed89.png)

**GCloud Logs:**
![image](https://user-images.githubusercontent.com/1054644/118545228-52c0ba00-b724-11eb-8893-77af333c6217.png)

### System

- Node.js version: v14.6.0 locally, v12 in the docker image
- NPM version: yarn v1.22.10 locally v7.12.1 on GCP
- Strapi version: 3.6.2
- Database: Postgres Cloud SQL
- Operating system: GCP

**Comment by derrickmehaffy** [comment]
We do not support running Strapi in a development mode in cloud environments, it's designed to be ran on local machines and the Content-Type builder is specifically disabled in other environments (staging/production).

See this FAQ: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

Closed as this isn't a development environment we support.
