### ISSUE TITLE
One level deep array not populated

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#10346]
### Describe the bug

Data of one level deep nested array was not populated. Does not work with, nor without population array.

### Steps to reproduce the behavior

1. Create collections `body` and `accessory`
2. Create one to many relation body -> accessoriesPDF
3. Query as below.

### Expected behavior

AccessoriesPDF data gets populated.

### Code snippets

query
```js
 const body = await strapi
        .query("body")
        .findOne({ fullName: offer.body.fullName }, ['accessoriesPDF']);
```

output (shortened)
```bash
strapi_1    | {
strapi_1    |   id: 2,
strapi_1    |   itemNumber: 458001,
strapi_1    |   locale: 'en',
strapi_1    |   published_at: null,
strapi_1    |   created_by: 1,
strapi_1    |   updated_by: 1,
strapi_1    |   created_at: 2021-05-17T11:07:58.377Z,
strapi_1    |   updated_at: 2021-05-17T11:07:58.400Z,
strapi_1    |   accessoriesPDF: []
strapi_1    | }

```

### System

- Node.js version: v14.15.3
- NPM version: 6.14.11
- Strapi version: 3.6.2
- Database: postgres 13.3
- Operating system: fedora 33

### Additional context

The gql query returns proper data.
```gql
{bodies {accessoriesPDF {id}}}
```

Body does use draft system and is published.

**Comment by derrickmehaffy** [comment]
Can't reproduce on v3.6.2:

![image](https://user-images.githubusercontent.com/8593673/118882889-7feaa500-b8a9-11eb-9cf4-dbe587b0aab7.png)


Controller code:

```js
"use strict";

const { sanitizeEntity } = require("strapi-utils");

module.exports = {
  /**
   * Retrieve records.
   *
   * @return {Array}
   */

  async test(ctx) {
    let entity = await strapi
      .query("body")
      .findOne({ id: 1 }, ["accessories_pdfs"]);

    console.log(entity);

    return sanitizeEntity(entity, { model: strapi.models.body });
  },
};
```

**Comment by derrickmehaffy** [comment]
Going to mark this one as closed for now but please do feel free to provide more reproduction steps if you have them and we can reopen them.
