### ISSUE TITLE
MongoDB error when requested  has backslash

### ISSUE THREAD

**Issue by lyubchenko** [strapi/strapi#10348]
### Describe the bug
When there is a backslash in the request, the api returns 500  and in console  shows error
 "error MongoError: Regular expression is invalid: \ at end of pattern"

### Steps to reproduce the behavior
1. Create a new entity type, i.e: posts
2. Add field name to model post
3. Open http://localhost:1337/posts?name_contains=test\

### System

- Node.js version:  v14.15.4
- NPM version: 7.12.1
- Strapi version: 3.4.5
- Database: MongoDB server version: 4.4.3
- Operating system:  macOS 11.1

**Comment by derrickmehaffy** [comment]
Confirmed on v3.6.2 however it's unlikely we will fix this since we are depreciating support for MongoDB.

https://github.com/strapi/strapi/issues/10186
