### ISSUE TITLE
Strapi uses 4 different naming methods/conventions (inconsistent naming)

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#10349]
### Describe the bug

Strapi uses 4 different naming methods/conventions. Could we use just one or two? It would simplify alot.

### Steps to reproduce the behavior

This is my actual name: **serviceArea**

Strapi converts it to:
- ServiceArea
- service_area
- service-area

Also internal field names use different cases: `created_at` vs `confirmationToken`

### Expected behavior

Set up best practices for collections types and fields and/or only use the naming I provide for everything, so that it is consistent

### Screenshots

Actual name:
![Screenshot from 2021-05-19 18-26-17](https://user-images.githubusercontent.com/45003352/118849773-598c3000-b8d0-11eb-9087-4a3f88eb002a.png)

What Strapi does:
![Screenshot from 2021-05-19 18-28-38](https://user-images.githubusercontent.com/45003352/118849887-788ac200-b8d0-11eb-8e8a-4ca3905453c2.png)
![Screenshot from 2021-05-19 18-27-10](https://user-images.githubusercontent.com/45003352/118849890-79235880-b8d0-11eb-8820-c1f49889d183.png)
![Screenshot from 2021-05-19 18-26-52](https://user-images.githubusercontent.com/45003352/118849891-79bbef00-b8d0-11eb-80b8-2b08361f1402.png)

**Comment by derrickmehaffy** [comment]
Thank you for starting the discussion on this but we would rather have these types of discussions on our forum and keep GitHub for bugs and feature requests.

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
