### ISSUE TITLE
Plugin with same name as collection blocks api permissions for collection

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#10357]
### Describe the bug

I created a plugin by cli command. Then I created a collection with the same name as the plugin. I set the find permissions for public for this collection. When calling the api endpoint, I got a 403 error. After deleting the plugin folder, calling the api enpoint worked.

### Steps to reproduce the behavior

1. Setup a plugin by cli `strapi generate:plugin my-name`
2. Create a collection in the admin panel with the same name (my-name)
3. Set find, findOne Permission for public for this collection
4. Call the api endpoint => Status 403
5. Deleting or renaming the plugin folder solves the issue

### Expected behavior

Access to api endpoint 

### System

- Node.js version:  v14.15.1
- NPM version:
- Strapi version: 3.6.2
- Database: sqlite
- Operating system: Windows 10

**Comment by kasonde** [comment]
Hi @pointout, I've tried to follow your steps and can't seem to reproduce the issue. Maybe if you can, provide more context with this issue by sharing a screenshot of your permissions page in the admin for both the collection type and the plugin for myself and anybody who maybe be able to reproduce the issue.

**Comment by pointout** [comment]
The problem is, that plugin and collection have the same api endpoint, if they have the same name. Maybe this is a wanted behaviour. I just startet with plugins and stopped again, because I did the intended now with a global function.

Same name collection and plugin:
![strapi-forbidden2](https://user-images.githubusercontent.com/8960545/119368640-8d41ce00-bcb3-11eb-82d2-67f4c67e4bfc.jpg)
![strapi-permissions-coll](https://user-images.githubusercontent.com/8960545/119368766-b5313180-bcb3-11eb-9919-1765cf3fff91.jpg)
![strapi-forbidden](https://user-images.githubusercontent.com/8960545/119368662-9468dc00-bcb3-11eb-8f2a-11c606fe6987.jpg)
![strapi-permission-plugin](https://user-images.githubusercontent.com/8960545/119369023-fd505400-bcb3-11eb-9d2a-2468efd1151f.jpg)
![strapi-plugin-index](https://user-images.githubusercontent.com/8960545/119369030-004b4480-bcb4-11eb-90f7-6d0d4bcd6071.jpg)

Different name for collection and plugin folder:
![strapi-200](https://user-images.githubusercontent.com/8960545/119369117-1953f580-bcb4-11eb-8f7b-f3d2d4327888.jpg)
![strapi-200-2](https://user-images.githubusercontent.com/8960545/119369125-1ce77c80-bcb4-11eb-85fc-56ea88882858.jpg)

**Comment by derrickmehaffy** [comment]
I tried this with a very simple `test` plugin and a `test` model:

![image](https://user-images.githubusercontent.com/8593673/119564626-d8182000-bd5d-11eb-8758-0ac79e7911f5.png)

Also including the repo with it's database, login info is:

```
test@test.com
Test1234!
```

[test10357.zip](https://github.com/strapi/strapi/files/6542228/test10357.zip)

Worked perfectly (note that the prefix is already injected on the routes for plugins). I'm going to mark this as closed as we don't have enough information to reproduce, please provide more information.

**Comment by pointout** [comment]
1. I did a fresh test-instalation
2. Generated a plugin with cli `strapi generate:plugin my-tests` (note the plural)
3. Called the build command
4. Logged in into admin and made a new collection named 'my-test'
5. Set permission for 'find', 'findall' for puplic
6. Made an entry into the colection
7. called localhost:1337/my-tests in browser => forbidden
8. Set permission 'index' for plugin 'my-tests'
9. called localhost:1337/my-tests in browser => "ok"

If the plugin has the plural name of a collection, the route to get collection is not working.

**Comment by derrickmehaffy** [comment]
Extremely rare case but I can reproduce with those steps, thank you.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198
