### ISSUE TITLE
Admin table rows should offer links instead of using onClick to open editor

### ISSUE THREAD

**Issue by jorisw** [strapi/strapi#10356]
### Describe the bug

When opening an item in the Admin Panel for editing, one cannot open it a new tab because it doesn't properly tag the item as a link. Looks like some onClick navigation is used both for the table cells as well as for the edit, duplicate, trash icons.

This makes it cumbersome to edit multiple items.

### Steps to reproduce the behavior

1. Go to the Admin Panel
2. Open an content item's content listing
3. Hold cmd on Mac or ctrl on Windows and click the item title
4. Notice it doesn't open in a new browser tab

### Expected behavior

I expect a cmd-click on Mac or ctrl-click on Windows to open items in a new browser tab.

### System

- Node.js version: v14.15.0
- Yarn version: 1.22.5
- Strapi version: 3.6.2
- Database: MySQL
- Operating system: macOS 11.3
- Browser: Safari 14 (or any WebKit or Mozilla based browser)

### Additional context

Use hrefs or navigation-specific routines to offer navigation rather than custom onClick routines to make the browser open the items in a new tab if the user so prefers.

**Comment by derrickmehaffy** [comment]
Confirmed with @Aurelsicoko on v4.1.5

**Comment by gu-stav** [comment]
Thanks for opening this issue. We discussed it today and believe it would be a valuable addition in terms of UX and A11y. We need to discuss it with the design system team first though.
