### ISSUE TITLE
Webpack TerserPlugin config freeze on hosting with dynamic CPU count

### ISSUE THREAD

**Issue by affinage-digital** [strapi/strapi#10367]
### Describe the bug
I have hosting with dynamic CPU. My project have two folder frontend (nuxt) and backend (strapi).
Nuxt corrected when i disable parallel parameter in TerserPlugin.
![image](https://user-images.githubusercontent.com/207461/119273083-ef49f700-bc11-11eb-8b0f-b421e4599f6d.png)
But strapi dont have convenient access to webpack config.
`npm run build` working only when i disable full TerserPlugin (see screenshot) in node_modules/strapi-admin/webpack.config.js
Just disable parallel params dont help me.

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/207461/119272914-181dbc80-bc11-11eb-8bd9-d4388461f6a6.png)

### Expected behavior

Disable TerserPlugin without change source code (webpack.config.js) in node_modules
Because the reason for freezing the TerserPlugin is not known.

### Screenshots

![image](https://user-images.githubusercontent.com/207461/119273159-3a640a00-bc12-11eb-85fb-457a60eae507.png)

Disable TerserPlugin success build
![image](https://user-images.githubusercontent.com/207461/119273289-d55ce400-bc12-11eb-9e34-7142dc612dbb.png)

### System

- Node.js version: v12.18.1
- NPM version: 6.14.5
- Strapi version: 3.6.1
- Database: mySQL
- Operating system: Linux l25 3.14.51-1gb-csm-d-refsem-cow #5 SMP Wed Jan 25 01:08:22 MSK 2017 x86_64

**Comment by derrickmehaffy** [comment]
@affinage-digital 

> But strapi dont have convenient access to webpack config.

Does the below documentation not work for you?
https://strapi.io/documentation/developer-docs/latest/development/admin-customization.html#custom-webpack-config

**Comment by affinage-digital** [comment]
I could not find this section in the documentation.
Yes, you are right. This solution working.
![image](https://user-images.githubusercontent.com/207461/119514332-98613080-bd7d-11eb-9142-94b2f0cea451.png)
Issue closed.
