### ISSUE TITLE
Pluralize singular doesn't work

### ISSUE THREAD

**Issue by smorrin28** [strapi/strapi#10363]
## Bug report

The pluralize singular exception doesn't work

### Describe the bug

Some words in other languages are pluralized differently in other languages than in English. After trying to add a pluralize rule to pluralize to cover the pluralizations as described in #8915, more specifically a singular rule (e.g. `pluralize.addSingularRule('test')`) to prevent the pluralization of singular words, a collection type with that name cannot be created.

 
### Steps to reproduce the behavior

1. Install pluralize
2. Go to config/functions/bootstrap.js
3. Add a singular rule for a certain word
   ```
   const pluralize = require('pluralize')

   module.exports = () => {
   // ...
   pluralize.addSingularRule('test')
   // ...
   }
   ```
4. Start strapi in development mode
5. Try to create a collection type with `test` as the name
6. The content type build will refuse to create the content type as it "cannot be pluralized"

### Expected behavior

The content type will get created 

### System

- Node.js version: v14.16.1
- NPM version: 7.12
- Strapi version: 3.6.2
- Database: SQLite
- Operating system: MacOS Big Sur

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198
