### ISSUE TITLE
force-redirecting when access list-view page without rawQuery

### ISSUE THREAD

**Issue by ashnamuh** [strapi/strapi#10360]
### Describe the bug
I've found force-redirection error.

### Steps to reproduce the behavior

1. Create a strapi project with `npx create-strapi-app my-project --quickstart`
2. Make an `article` collection type 
3. Access the `article` collection list page by its url without `rawQuery` like the follwing video.
4. Sometimes it force me to redirect into main(`/`) page. And some other times it works well.

### Expected behavior
Always redirecting into list-view page when access the page by the url without `rawQuery`

### Videos

https://user-images.githubusercontent.com/14067417/119115476-2aa5c380-ba62-11eb-8caa-63afd02ba8aa.mov

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.21.0
- NPM version: 6.14.11
- Strapi version: 3.6.2
- Database: default
- Operating system: Mac OS 10.15.7

### Additional context
I wonder, is this a intended behavior? Or users must access the page by clicking collection button on the sidebar? 

If it is a bug, i think the bug is caused by asynchronous codes logic. `redirectUrl` should be a `null` state at [this code](https://github.com/strapi/strapi/blob/4ab210eec65d7f1a4f6334cdef4c797b4e6b9531/packages/strapi-plugin-content-manager/admin/src/hooks/useFindRedirectionLink/utils/getRedirectionLink.js#L26-L42). And the `null` value should be handled at [this code](https://github.com/strapi/strapi/blob/4ab210eec65d7f1a4f6334cdef4c797b4e6b9531/packages/strapi-plugin-content-manager/admin/src/containers/ListViewLayoutManager/index.js#L34-L36)

Could i make a PR if i think correctly?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/10356
