### ISSUE TITLE
Find nearby locations

### ISSUE THREAD

**Issue by valentin-harrang** [strapi/strapi#10374]
## Feature request

Hi everyone,

I am using Strapi and MySQL for my React Native project and I need to query to get all events within X kilometers of my current location.

Although MongoDB could solve my problem because it has a near query natively (https://docs.mongodb.com/manual/reference/operator/query/nearSphere/), I still opted for MySQL because MongoDB support will be dropped in Strapi V4 so I won't be able to update it afterwards . And I also use GraphQL but no luck on Strapi's GraphQL it's not possible to filter by location ..

Is it possible to add this functionality to GraphQL? (example: https://dgraph.io/docs/graphql/schema/search#near)

In the meantime, can you tell me how I can solve this problem please?

Thank you in advance

**Comment by aksdevac** [comment]
You can try using native query using `ST_Distance_Sphere` function.

you can check this links:
https://stackoverflow.com/questions/62823829/get-closest-points-of-a-point-from-a-db
https://mydbops.wordpress.com/2020/05/03/geospatial-data-handling-made-easy-with-mysql-8-0/

& Also we might still see some MongoDB support in 2022 as per this comment:
https://forum.strapi.io/t/dropping-mongodb-support/4549/85

**Comment by derrickmehaffy** [comment]
We don't currently plan on adding a feature like this as it's more so related to Geo fields which is something more related to https://feedback.strapi.io/developer-experience/p/custom-fields

Marking as closed as this is possible something could be added via that feature.
