### ISSUE TITLE
One Click Deployment on Google Firebase

### ISSUE THREAD

**Issue by davidjeba** [strapi/strapi#10379]
### Please describe your feature request

- [ ] **One Click Deployment for DigitalOcean, Platfrom.sh, Render are available**
- [ ] **Please include One Click Deployment to Google Firebase as strapi is more towards mobile first GCP will be very important**

### Summary

Make it easier for mobile app developers to use Strapi as Backend on google firebase

### Why is it needed?

For Enterprise application, devs use Azure, For simple to complex website AWS
but the Primary backend of the mobile app is google firebase. It would be great if you can add Strapi to be deployed easily on google firebase

**Comment by derrickmehaffy** [comment]
The only place where something **like** Strapi could run in firebase is in cloud functions, this has been tried and tested many times on various platforms with zero success (AWS Lambda, Vercel, Google Cloud Functions).

Strapi has to be ran as a service, and if you are using cloud functions, that means every. single. request. has a cold boot time, and in many larger projects that can be 3 seconds to 30 seconds just to boot up the Strapi app and it doesn't fit the style of deployment that Strapi is currently using or what our plans are for the future.

Strapi on it's own is a headless CMS and is designed to be ran as a service (typically an always-on service) not as a serverless function. It also cannot be ran on static hosting like many of the frontend frameworks.

I'm going to mark this feature request as closed as it's more or less impossible to deploy Strapi on firebase without major architectural modifications to the entire project that we do not plan to do. Thank you for the request though.

**Comment by davidjeba** [comment]
I was expecting to run Strapi on a VM/Instance with backend/database as firestore
not wanting to deploy strapi as a serverless application

**Comment by derrickmehaffy** [comment]
> I was expecting to run Strapi on a VM/Instance with backend/database as firestore
> not wanting to deploy strapi as a serverless application

We are not planning to expand the supported database in the near future (in fact we are trying to cut down on non-SQL databases). See: https://github.com/strapi/strapi/issues/10186
