### ISSUE TITLE
Hooks are not triggered

### ISSUE THREAD

**Issue by ElGecko76** [strapi/strapi#10376]
When I create a new record in collection from Strapi content manager, the hooks are not triggered.

I added this code in my `controller` but the `console.log` are not displayed:

```
const index = 'event'

module.exports = {
  lifecycles: {
    async afterCreate(result, data) {
      console.log(data);
      strapi.services.algolia.saveObject(result, index);
    },
    async afterUpdate(result, params, data) {
      console.log(data);
      strapi.services.algolia.saveObject(result, index);
    },
    async afterDelete(result, params) {
      console.log(data);
      strapi.services.algolia.deleteObject(result.id, index);
    },
  },
};
```

### System

- Node.js version: 12.20.1
- NPM version: 7.12.0
- Strapi version: 3.6.2
- Database: MySQL
- Operating system: Ubuntu

**Comment by kasonde** [comment]
Hi @ElGecko76, I think you put that code in the wrong location. Take a look at the [customization docs](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#models) under `models`. You need to add that code in `../api/content-type-name/models/ContentTypeName.js`. If this doesn't work, I can definitely look further into reopening this.
