### ISSUE TITLE
Error with the request /upload/files/:id in MySQL

### ISSUE THREAD

**Issue by omar1989omb** [strapi/strapi#1037]
**Informations**
- **Node.js**:  9.11.1
- **npm**: 5.8.0
- **Strapi**: 3.0.0-alpha.12.0.1
- **Database**: MySQL
- **Operating system**: Ubuntu 17.10

**What is the current behavior?**

Using the request /upload /files/:id with the GET or DELETE methods, the console displays the error:

`[2018-04-25T17:46:54.220Z] error select `upload_file`.* from `upload_file` where `upload_file`.`_id` = '_2' limit 1 - ER_BAD_FIELD_ERROR: Unknown column 'upload_file._id' in'where clause'
`

**Steps to reproduce the problem**

Using the request /upload /files/:id  with MySQL and the GET or DELETE methods.

http://localhost:1337/upload/files/2 (GET or DELETE)
It shows error 500 and in the console the previous message.

**Suggested solutions**

In the file "/plugins/upload/config/functions/bootstrap.js" the column is called id, not _id:

```
CREATE TABLE ${quote}${Model.tableName || Model.collectionName}${quote} (
    id ${Model.client === 'pg' ? 'SERIAL' : 'INT AUTO_INCREMENT'} NOT NULL PRIMARY KEY,
    name text,
    hash text,
    ext text,
    mime text,
    size text,
    url text,
    provider text,
    updated_at ${Model.client === 'pg' ? 'timestamp with time zone' : 'timestamp'},
    created_at ${Model.client === 'pg' ? 'timestamp with time zone' : 'timestamp'}
  );
```

I have modified the file "/plugins/upload/services/Upload.js":

Lines (92-94)
```
 fetch: (params) => {
    return strapi.query('file', 'upload').findOne(_.pick(params, ['_id', 'id']));
  },

```
by:
```
  fetch: (params) => {
    return strapi.query('file', 'upload').findOne(_.pick(params, 'id'));
  },

```
Now it works fine with MySQL

**Comment by lauriejim** [comment]
Hello @omar1989omb You are in a good way to fix it and submit a PR.

Actually your update will broke mongoose applications. You have to investigate in `bookshelf queries` I think instead of `services`

**Comment by lauriejim** [comment]
I think it's the same issue of #1135 !
