### ISSUE TITLE
can we import file outside extension inside extension folder?

### ISSUE THREAD

**Issue by hpachy** [strapi/strapi#10386]
Hello fellas,

I would like to some functions inside utils folder at the root of strapi’s repo, from extension folder but currently I got the following error :
Error: Module not found: Error: Can't resolve '../../utils/buildFullUrl' in '/Users/***/strapi/.cache/plugins/strapi-plugin-content-manager/admin/src/components/TinyMSE'

It's look like we can't call function out of the extension folder... And I do not want to duplicate my functions inside my utils (root of the strapi folder) in each root folder...

So I wonder if we can do something custom the absolute path or something else :/ the problem maybe come from my utils folder position (strapi/utils)...

Thx for your help regards

**Comment by kasonde** [comment]
Hi @hpachy thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.
