### ISSUE TITLE
AWS Upload Provider config location in admin

### ISSUE THREAD

**Issue by JoshR604** [strapi/strapi#1038]
I am confused with the file upload documentation and perhaps you can point me in the right direction? 

I have now installed the aws provider by running the npm command, but I am unable to locate the configuration file(s) as shown in the documentation where it says visit:
“/admin/plugins/upload/configurations/development” — this path does not exist in my project? 

I tried looking at the Upload bootstrap to find out where the config would come from but am unable to locate still.

**Comment by JoshR604** [comment]
Ah I found it now!

For people who can't find it in the future the configuration can be found under the Plugins tab on the side bar.

Plugins >Files Upload -- *hit the gear icon* and the installed provider should be in the drop down list. 👍

**Comment by lauriejim** [comment]
That is strange, I test the path `/admin/plugins/upload/configurations/development` and it works.

**Comment by yummyelin** [comment]
It's strange, I met the same issue.

In my project, `/admin` and `/plugins` are parallel directories. There is no `/admin/plugins`, and there is no `/plugins/upload/configurations`.

![screen shot 2018-06-27 at 5 20 39 pm](https://user-images.githubusercontent.com/3782817/42006434-a1ce6fa6-7a2e-11e8-8bd4-00b5bff0ee02.png)
![screen shot 2018-06-27 at 5 20 29 pm](https://user-images.githubusercontent.com/3782817/42006438-a7ddcc84-7a2e-11e8-98a8-4c1a85fa73ad.png)

**Comment by lauriejim** [comment]
@yummyelin the path is an url, not folder path.
