### ISSUE TITLE
Replacing an image in Media Library does not change the image URL

### ISSUE THREAD

**Issue by felixhagspiel** [strapi/strapi#10382]
### Describe the bug

If I replace an image in the Media Library, the URL of the image stays the same, which results in caching problems, especially when used together with the [image component of nextjs](https://nextjs.org/docs/api-reference/next/image).

### Steps to reproduce the behavior

1. Go to Media Library
2. Click on any existing image / file (Example image URL: "/uploads/myoldimage.jpg")
3. Click "Replace Media" and upload a new file
4. Click "Finish"
5. Image URL is still "/uploads/myoldimage.jpg"

### Expected behavior
URL should be "/uploads/mynewimage.jpg"

### System

- Node.js version: 12.10
- NPM version: 6.10.3
- Strapi version: 3.6.2
- Database: Postgres
- Operating system: Mac / Ubuntu

**Comment by felixhagspiel** [comment]
I have solved this now by overwriting [this line](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L224) to:

```
    _.assign(fileData, {
      hash: generateFileName(file.name),
      ext: path.extname(file.name),
    });
```

**Comment by derrickmehaffy** [comment]
@felixdenoix you mind submitting a PR to fix it for everyone?

**Comment by felixhagspiel** [comment]
@derrickmehaffy I am not quite sure if this is a bug, it seems to be intended (see comment `// keep a constant hash` here https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L224)

**Comment by nwazuo** [comment]
@derrickmehaffy Can you confirm that the line @felixhagspiel overwrote is a proper fix to this issue? 
I see that a related issue is closed as resolved but people are still experiencing this problem. 

I'm thinking to use `patch-package` to apply @felixhagspiel 's fix. Hopefully it doesn't break anything else?
