### ISSUE TITLE
Component with relationship field that contains media: Error: upload_file is not defined on the model.

### ISSUE THREAD

**Issue by denimamab** [strapi/strapi#10380]
### Describe the bug

I've created a new component **MyComponent** with a relation to a collection called **MyCollection** that contains media.
I have another collection that contains a DynamicZone with can use **MyComponent**. When trying to add a new row with the component **MyComponent** I have this error : 
` Error: upload_file is not defined on the model.`

### Steps to reproduce the behavior

1. Create collection type **MyCollection** with field media: Type single Media
2. Create a component **MyComponent** with relation called data wich is a relation to **MyCollection**
3. Create a collection type **MySecondCollectionType** with dynamicZone that can use **MyComponent** as a component 
4. try to add a new row on **MySecondCollectionType** with **MyComponent** in its dynamiczone
5. see the error

### Expected behavior

create a new row

**Comment by kasonde** [comment]
Hi @denimamab I'm currently unable to reproduce this issue. Could you share your preproduction steps in more detail? (Use-case scenarios if possible are also a plus). Also please share more information about your environment. You can refer to [the issue template](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md) for more information about that.

**Comment by denimamab** [comment]
I've found the issue. It was due to the plugin and admin permission customizations on my project.
