### ISSUE TITLE
Can not select locale, no language selectbox

### ISSUE THREAD

**Issue by martijnmichel** [strapi/strapi#10404]
### Describe the bug

Installing Strapi in a docker (latest) with postgres db works fine, adding locales works fine in admin panel. But there is no locale selectbox in any of the created content types. Although everywhere on internet I see examples there should be one.

### Steps to reproduce the behavior

1. Install through docker
2. create locales
3. create content type in builder
4. create an content item
5. try to select locale

### Expected behavior

Expecting to see a locale selectbox

### Screenshots

![image (8)](https://user-images.githubusercontent.com/38880192/120059813-1eb69480-c054-11eb-86de-ba408a9687c0.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12
- NPM version:
- Strapi version: 3.6.2
- Database: postgres
- Operating system: ubuntu 18.04

**Comment by soupette** [comment]
It seems that i18n is not activated on your content type. Can you go to the content type builder, click on your test collection type then in the advanced settings of your collection type activate i18n.

After activating i18n you'll be able to see the local picker.

**Comment by martijnmichel** [comment]
ive installed Directus..

**Comment by soupette** [comment]
> ive installed Directus..

No problem, I am closing this issue then!
