### ISSUE TITLE
Invalid Input Data Please Verify Unique Constraints 

### ISSUE THREAD

**Issue by FredWahlqvistDrop** [strapi/strapi#10403]
### Describe the bug

Did a database migration from a AWS snapshot to my current database. both db are the same version. only difference is name. 
For the migration is used AWS database migration task. 

All data have been migrated, i can see all previous entries and i can also update them, for example changing e a title on a article. 
However when i try to create any new entry I get "Invalid Input Data Please Verify Unique Constraints " 

### Steps to reproduce the behavior

1. Migrate on postgres serverless aurora to another postgres serverless aurora 
2. Change any data 
3. Create new data and this error will occur

### Expected behavior

I should be able to create new entries in the database via strapi. 

### System

- Node.js version: strapi/base:14-alpine (v14.15.3)
- Strapi version: v3.5.4
- Database: Postgres aurora (serverless)

**Comment by derrickmehaffy** [comment]
> Postgres aurora (serverless)

We do not support Aurora since it's not native PostgreSQL. Please test and confirm on an actual PostgreSQL database.

**Comment by jtlindsey** [comment]
@derrickmehaffy @FredWahlqvistDrop I'm having the same problem on postgresql local installation PostgreSQL `13.3`, Strapi Version `3.6.2`

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy @FredWahlqvistDrop I'm having the same problem on postgresql local installation PostgreSQL `13.3`, Strapi Version `3.6.2`

Can you please open a new bug report and fill out the template.

That error message is very generic and you'll want to look at the server log messages for more details.
