### ISSUE TITLE
Dealing with post requests with wrong "Content-Type"

### ISSUE THREAD

**Issue by tudislei** [strapi/strapi#10400]
Sorry that I can't find a better place to post this.

The problem is : when there is a **post** request with **Content-Type: application/json**
but the body is actually a **text** like  `%7B%22logNo%22%3A%2233333333%2`

the response will then automatically be 
`{"statusCode":400,"error":"Bad Request","message":"invalid JSON, only supports object and array"}`  
and the code in the controller will be skipped.

Is there a way to read the body or make the code in the "post" controller work again in this case ? Thank you very very much.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
