### ISSUE TITLE
Setup error about sharp

### ISSUE THREAD

**Issue by atzzta1991** [strapi/strapi#10402]
## Bug report
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/trieu.nhtvn/dj-events/dj-events-backend2/node_modules/sharp
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

### Describe the bug
This happens when I set up new strapi project with cli. I tried docker and it worked fine for a day, then still such error happened, which prevents me from starting my project.

### Steps to reproduce the behavior

1. npx create-strapi-app my-project --quickstart
2. Waiting
3. Then boom!

### Expected behavior

The setup needs to be more simple, easy, and errors free.

### Code snippets
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/trieu.nhtvn/dj-events/dj-events-backend2/node_modules/sharp
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

### System

- Node.js version: v14.17.0
- NPM version: 7.15.0
- Strapi version: 3.6.2
- Database: Sqlite maybe. I choose quickstart setup
- Operating system: MacOS Big Sur 11.2.3

**Comment by derrickmehaffy** [comment]
Do you have the standard build tools installed? (xcode) and are you on an ARM based mac?

**Comment by joeldacuma** [comment]
@derrickmehaffy  I encountered this issue in my M1 Macbook. is there a way to fix this? My other repo is working except strapi base framework.

**Comment by derrickmehaffy** [comment]
The issues with sharp + M1 macs should have already been fixed.

But based on other users having issues, best guess is your brew is not using Rosetta (the compatibility layer for x86 CPUs)

https://stackoverflow.com/questions/66427623/error-installing-native-node-js-add-on-with-node-gyp-on-apple-m1-big-sur

**Comment by derrickmehaffy** [comment]
I don't have an M1 Mac to test with @pwizla / @markkaylor / @mfrachet can you guys assist here?

**Comment by joeldacuma** [comment]
> The issues with sharp + M1 macs should have already been fixed.
> 
> But based on other users having issues, best guess is your brew is not using Rosetta (the compatibility layer for x86 CPUs)
> 
> https://stackoverflow.com/questions/66427623/error-installing-native-node-js-add-on-with-node-gyp-on-apple-m1-big-sur

I already have installed rosetta 2 in my M1 Mac. Other npm packages and frameworks I installed were working fine. Only strapi having an issue because of that sharp module error.

**Comment by derrickmehaffy** [comment]
> > The issues with sharp + M1 macs should have already been fixed.
> > But based on other users having issues, best guess is your brew is not using Rosetta (the compatibility layer for x86 CPUs)
> > https://stackoverflow.com/questions/66427623/error-installing-native-node-js-add-on-with-node-gyp-on-apple-m1-big-sur
> 
> I already have installed rosetta 2 in my M1 Mac. Other npm packages and frameworks I installed were working fine. Only strapi having an issue because of that sharp module error.
> 
> Update: I tried it now and it is now working fine :)

Glad to hear, going to set this one as closed.
