### ISSUE TITLE
Allow Searching on Upload select modal

### ISSUE THREAD

**Issue by Mortalife** [strapi/strapi#10417]
## Feature request

Allow searching within the upload select modal, currently only limited filtering and sorting is enabled.

### Please describe your feature request

- [Done] **I have created my request on the Product Board before I submitted this issue**
- [Done] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Client is having difficulty finding the images they want for a piece of content among the thousands of images uploaded. They need to be able to search similar to what is implemented within media page header.

### Why is it needed?

The client is struggling to find the images they want.
The client used 7gb of data on a single day scrolling through images. 

### Suggested solution(s)

Add a search box as per the media page header (feels like a quick win)
Allow uploads to be tagged (better overall addition)

### Related issue(s)/PR(s)

None

**Comment by soupette** [comment]
This feature has been added in the v4.

**Comment by derrickmehaffy** [comment]
Marking as closed since it's added in the v4
