### ISSUE TITLE
i18n: Delete all localizations of the selected entry

### ISSUE THREAD

**Issue by BitPatty** [strapi/strapi#10411]
### Please describe your feature request

When deleting a localized entry on 3.6.2 there's a pop up saying it will delete "This will delete the active locale **versions**" (plural): 
![image](https://user-images.githubusercontent.com/11077852/120181379-43a23780-c20d-11eb-9cb3-ffd324b2f4bf.png)

Unsure whether this is should be a bug report or a feature request, since the message in the popup is ambiguous. It's unclear whether it tries to tell me that it's going to delete "the currently selected locale" or "all locales which are active in the plugin". In any case, it's doing the former and only deletes the currently selected locale in the overview. From what I've seen there doesn't appear to be an option to delete all localizations at once.

### Why is it needed?

Oftentimes one doesn't want to keep locales of deleted entries. This would greatly improve the UX allowing one to delete everything with 3 clicks in total instead of 3 clicks per locale.

### Suggested solution(s)

A checkbox, secondary button or similar which user could check to delete all locales of the selected entry.

Also, it'd be great if the warning were less ambiguous.

### Related issue(s)/PR(s)

\-

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/i18n-delete-all-localizations-of-the-selected-entry

Thanks!
