### ISSUE TITLE
Date picker not displayed correctly when editing a content type

### ISSUE THREAD

**Issue by moklick** [strapi/strapi#1041]
*BUG TEMPLATE*

**Informations**
- **Node.js version**: v9.11.1
- **npm version**: v5.6.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: MongoDB
- **Operating system**: macOs High Sierra

**What is the current behavior?**

The date picker is not displayed correctly. The icon is outside the input field, the date picker is open and you can't close it.

![screen shot 2018-04-26 at 10 39 37](https://user-images.githubusercontent.com/2857535/39295483-d692bcea-493e-11e8-9b81-8dfddecf5c54.png)

**Steps to reproduce the problem**

1. Add field `Date` to a content type
2. Edit the date of that content type

**What is the expected behavior?**

Date picker icon is inside the input field and opens when you click on it.

**Suggested solutions**

Insert missing date picker css.

**Comment by kadaan** [comment]
Just to confirm, did this fix also resolve the same issue on the "New Entry" pages?
