### ISSUE TITLE
Unable to insert image into Froala Editor. "No link in upload response" 

### ISSUE THREAD

**Issue by develijahlee** [strapi/strapi#10427]
### Describe the bug

Cannot insert image into Froala Editor

### Steps to reproduce the behavior

1. Go to 'Collection Types'
2. Click on 'Archives'
3. Scroll down to 'Froala Editor'
4. Click on **Insert Image**
5. Click **Drop Image**
6. Choose an image to insert
7. See error "No link in upload response"
8. Click "Ok"
9. Image is deleted

### Expected behavior

Image should be inserted into Froala Editor.

### Screenshots

![Screen Shot 2021-06-02 at 5 29 27 PM](https://user-images.githubusercontent.com/54133475/120567596-28be0600-c44d-11eb-9049-bc63f8a41eb3.png)
![Screen Shot 2021-06-02 at 5 28 41 PM](https://user-images.githubusercontent.com/54133475/120567589-25c31580-c44d-11eb-9a5f-a51c177e5780.png)
![Screen Shot 2021-06-03 at 9 24 46 AM](https://user-images.githubusercontent.com/54133475/120567826-923e1480-c44d-11eb-8ff0-833600123ee3.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.16.1
- NPM version: 7.5.2
- Strapi version: 3.5.4
- Operating system: Mac OS
- react-froala-wysiwyg version: 3.2.3

**Comment by derrickmehaffy** [comment]
Hi @develijahlee the editor you are using is not one we maintain ourselves so it's best if you ask those type of questions on our community forum as our GitHub issues are only for the code contained within this repo.

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
