### ISSUE TITLE
Cannot create entry of same name in i18n

### ISSUE THREAD

**Issue by maggie0002** [strapi/strapi#10425]
I have a database entry in English called 'Audio'. For the content-type of the field I have the option enabled that prevents more than one item be created with the same name. 

When I use the i18n feature, I am trying to input the Spanish translation for 'Audio'. It happens to also be 'Audio'. When I try to enter it, Strapi seems to be seeing it as a duplicate entry and preventing the input:

<img width="330" alt="Screenshot 2021-06-02 at 16 40 43" src="https://user-images.githubusercontent.com/64841595/120565221-712fe200-c3c1-11eb-906c-d4de4aa377fe.png">

A work around is to not enter anything in this field, and it defaults to the English word which is the same. However, it then becomes difficult to keep track of which strings have been translated and which are intentionally left blank to avoid this duplication error. 

The same issue occurs between other languages though, for example if I make English 'Audio1', Spanish 'Audio' and French 'Audio', it reports an error that I cannot add the entry. In this circumstance, I cannot leave it blank as it would default to English which is the incorrect string. 

Ideal behaviour would be the i18n fields being an exception to the unique string constraints except within its own language.

v3.6.2

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
