### ISSUE TITLE
Cannot retrieve media types for nested sets.

### ISSUE THREAD

**Issue by Dronozavr** [strapi/strapi#1042]
**Informations**
- **Node.js version**:
9.11.1 
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.11.3
- **Database**:
mongoDB (mongoLab)
- **Operating system**:
Kubutntu

**What is the current behavior?**
Cannot retrieve media types for nested sets.
**Steps to reproduce the problem**
I have created CT "Course", which has relation with CT "Mentors".  Every "Mentor" in "Mentors" has media field 'Avatar', as you may guess it is an image. When I am retrieving mentors from `localhost:1337/mentors`, I get that image for every Mentor and everything is OK. But when I am retrieving   Courses from `localhost:1337/courses` I got courses with nested info about mentors, but the 'avatar' field is equal to `null`.
**What is the expected behavior?**
I would like to retrieve courses with 'Mentors' avatar media field included. 
**Suggested solutions**
It seems like it is the second level of nesting, because the 'strapi' upload mechanism bounds media type to entity like nested set.

- [ V ] I'm sure that this issue hasn't already been referenced

**Comment by XcrossD** [comment]
This is duplicate with #877. I'm trying to get it to work, but I need some guidance from the maintainers.
