### ISSUE TITLE
Unable to create relation between two content types in Postgres DB

### ISSUE THREAD

**Issue by slibin** [strapi/strapi#10422]
I am getting the below error while trying to create Product-Subgroups has and belongs to many Product-Categories relation. This was working find in SQLLite DB but throwing below error in Postgres and strapi gets disconnect after getting the below error. Strapi accept this relation and try to restart but the server gets crashed.You will be able to restart after deleting Product-Subgroups folder from API folder.

Below is the console error - 

[2021-06-02T09:05:35.374Z] debug :no_entry: Server wasn’t able to start properly.
[2021-06-02T09:05:35.410Z] error error: create table “product_categories_product_subgroups__product_subgroups_product_categories” (“id” serial primary key, “product-subgroup_id” integer null, “product-category_id” integer null) - relation “product_categories_product_subgroups__product_subgroups_product” already exists
at Parser.parseErrorMessage (F:\ws\urbanblake\strapi\urbanblake\node_modules\pg-protocol\dist\parser.js:287:98)
at Parser.handlePacket (F:\ws\urbanblake\strapi\urbanblake\node_modules\pg-protocol\dist\parser.js:126:29)
at Parser.parse (F:\ws\urbanblake\strapi\urbanblake\node_modules\pg-protocol\dist\parser.js:39:38)
at Socket. (F:\ws\urbanblake\strapi\urbanblake\node_modules\pg-protocol\dist\index.js:11:42)
at Socket.emit (events.js:315:20)
at addChunk (_stream_readable.js:309:12)
at readableAddChunk (_stream_readable.js:284:9)
at Socket.Readable.push (_stream_readable.js:223:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! urbanblake@0.1.0 dev: strapi develop
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the urbanblake@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\libin\AppData\Roaming\npm-cache_logs\2021-06-02T09_05_35_672Z-debug.log

------------Debug log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli ‘C:\Program Files\nodejs\node.exe’,
1 verbose cli ‘C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js’,
1 verbose cli ‘run’,
1 verbose cli ‘dev’
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.0
4 verbose run-script [ ‘predev’, ‘dev’, ‘postdev’ ]
5 info lifecycle urbanblake@0.1.0~predev: urbanblake@0.1.0
6 info lifecycle urbanblake@0.1.0~dev: urbanblake@0.1.0
7 verbose lifecycle urbanblake@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle urbanblake@0.1.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\ws\urbanblake\strapi\urbanblake\node_modules.bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel® Management Engine Components\DAL;C:\Program Files\Intel\Intel® Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel® Management Engine Components\IPT;C:\Program Files\Intel\Intel® Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\php;C:\Apache24;C:\Apache24\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs;C:\Users\libin\AppData\Local\Android\Sdk;C:\Program Files\Amazon\AWSCLIV2;C:\Program Files\Amazon\AWSCLIV2;C:\Users\libin\AppData\Local\Programs\Python\Python39\python.exe;C:\Users\libin\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\libin\AppData\Local\Programs\Python\Python39;C:\Users\libin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\libin\AppData\Roaming\npm;C:\Users\libin\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\Amazon\AWSCLIV2;C:\Users\libin\AppData\Local\Programs\Python\Python39\python.exe;;C:\Users\libin\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle urbanblake@0.1.0~dev: CWD: F:\ws\urbanblake\strapi\urbanblake
10 silly lifecycle urbanblake@0.1.0~dev: Args: [ ‘/d /s /c’, ‘strapi develop’ ]
11 silly lifecycle urbanblake@0.1.0~dev: Returned: code: 1 signal: null
12 info lifecycle urbanblake@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: urbanblake@0.1.0 dev: strapi develop
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:315:20)
13 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:315:20)
13 verbose stack at maybeClose (internal/child_process.js:1048:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid urbanblake@0.1.0
15 verbose cwd F:\ws\urbanblake\strapi\urbanblake
16 verbose Windows_NT 10.0.19042
17 verbose argv “C:\Program Files\nodejs\node.exe” “C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js” “run” “dev”
18 verbose node v14.15.0
19 verbose npm v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error urbanblake@0.1.0 dev: strapi develop
22 error Exit status 1
23 error Failed at the urbanblake@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by emahuni** [comment]
This usually happens when I do model changes or deploy to a new server running Postgres. This is more of a migration issue.

- I normally delete all tables in DB and just run yarn develop. That gets Strapi to recreate the tables when I run it again.
-  If you want data in the tables, dump the SQL data first (I normally just use Navicat to backup and restore just the tables data only, no other schema thingies, just the data) then delete tables and run Strapi, then restore your data through raw SQL insert commands from the SQL dump. 
- If, for one final reason you can't run the SQL commands because you changed some columns present in the SQL dump but not in your models anymore, then you will have to edit the dump file and rename the columns through some find replace operation or remove any dropped columns that way too. Then run the SQL (I created a knex SQL seeder that does this). 
 
The point is, Strapi creates new tables each time the DB doesn't have any, using the current version's logic, which solves your problem.

**Comment by slibin** [comment]
I recreated all tables manually while moving data from SQLLite to PostgresDB.I was able to create all tables manually. While trying to create a relation between two tables strapi stopped working all of a sudden and i had to delete respective API folder to restart Strapi. Strapi did not throw any warnings or error while creating the relation. Shouldn't strapi give warning when something goes wrong?

**Comment by slibin** [comment]
There are many issues in Strapi while creating relations between content types using Postgress...Please do proper testing.....

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
