### ISSUE TITLE
Cannot access to the admin panel after deploy on heroku

### ISSUE THREAD

**Issue by nguy2616** [strapi/strapi#10429]
## Bug report
Cannot register or using the admin panel
### Describe the bug
All things work on Postman , but I cannot use the admin panel

### Steps to reproduce the behavior

1. Go to 'natwaytest.herokuapp.com/admin'
2.  Fill in information
3. Click on Button
4. See error (Nothing happen)

### Expected behavior

Successfully register/login and redirect to the admin panel page

### Screenshots

![admin](https://user-images.githubusercontent.com/50698564/120579431-b26fd280-c451-11eb-91cf-9c37ade47e93.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.16.0
- Database: postgres

**Comment by derrickmehaffy** [comment]
Hi @nguy2616 Can you please ask this question on our community forum, this GitHub is really for the code itself and not really deployment help. You can also ask on our Community Discord.

Forum: https://forum.strapi.io
Discord: https://discord.strapi.io
