### ISSUE TITLE
setting not provided for search path in (database connection).

### ISSUE THREAD

**Issue by jaydeep11** [strapi/strapi#10436]
I want to have separate schema for strapi . For example, let's say `cms` . When I build app the tables are by default created in `public` schema even if I specify `cms` as default schema in database connection setting. 

I tried creating a separate database user and connection setting , but got following error .
<img width="704" alt="Screenshot 2021-06-04 at 11 02 18 AM" src="https://user-images.githubusercontent.com/44337780/120750661-5cb82a80-c524-11eb-8fd3-a09fb09aa07c.png">
 
Example Database connection: 
```
connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: "postgres",
        ssl: false,
        host: "localhost",
        port: 5432,
        database: "<database_name>_cms",
        username: "xyz",
        password: "xyz",
        schema: "cms",
      },
      options: {
        useNullAsDefault: true,
        debug: false,
        pool: {
          min: 0,
          max: 2,
        },
      },
    },
  }
```

If setting search path option is provided in database connection setting , then problem can be solved.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
