### ISSUE TITLE
Support indexed columns on PostgresDB

### ISSUE THREAD

**Issue by st3penta** [strapi/strapi#10437]
## Feature request

Add the possibility to tag a field of a data model as indexed, such that Postgres creates an index on that column in the corresponding table 

### Summary

When working with a heavily populated Postgres DB, strapi suffers of performance bottlenecks on some types of query (such as sorted ones). 
In order to overcome this, it is useful to use indexes on critical columns in tables, but at the moment strapi doesn't support that for Postgres.
It seems that something similar is only supported by MongoDB: https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#validations

**Comment by st3penta** [comment]
As a side note, i tried creating such indexes manually and they seem to work well, but i'd like to know if there are any downsides in doing this  without strapi knowing. (I also asked the same question here: https://forum.strapi.io/t/manual-addition-of-index-to-db-column-postgresql/5121)

**Comment by pierreburgy** [comment]
Hi @st3penta, would the solution suggested in #9913 solve your issue?

**Comment by st3penta** [comment]
It will, thank you very much!

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/9913
