### ISSUE TITLE
upload plugin to stop generating the thumbnail image

### ISSUE THREAD

**Issue by gondar00** [strapi/strapi#10431]
I am able to stop generating responsive small,medium,large from the settings of media upload plugin, 

But I am unable to find a option to stop generating formats object completely as services like imgix provide this on the fly. 

Is there a configuration way available that I am missing?

**Comment by kasonde** [comment]
Hi, @gondar00 thanks for the question. Could you ask this on the [Community Forum](https://forum.strapi.io)/[Discord](https://discord.com/invite/WFrDyNzNDU) or provide a link to the already asked question so we can move the discussion there? I'll close this issue for now as it's perfect for either of those two community channels. Additionally looks like a duplicate of #10418

**Comment by Mortalife** [comment]
It's not a duplication of #10418. 10418 is related to thumbnail not being used for thumbnails, not that it exists or that it should be possible to have it disabled.

**Comment by ngotrongphuc** [comment]
I found a way to disable thumbnail generation in Strapi v5. Simply add this file at ./src/extensions/upload/strapi-server.ts - it overrides the generateThumbnail method of the Upload plugin. Now thumbnails in the media library will use the original image URL as a fallback.
```ts
export default (plugin) => {
  // Override upload plugin to disable thumbnail generation
  plugin.services['image-manipulation'].generateThumbnail = () => {}
  return plugin
}
```
