### ISSUE TITLE
Plugin Users-permissions: During register, bad error when Username already taken.

### ISSUE THREAD

**Issue by Denis2222** [strapi/strapi#10446]
### Describe the bug

Strapi return bad error during **user register** with already taken **username**

### Steps to reproduce the behavior

1. Install fresh strapi instance 
`yarn create strapi-app debugRegister --quickstart`

2. Register one user
```
{
    'username': 'strapiuser1',
    'password': 'somepassword',
    'email': 'user@strapi.com'
  }
```
3. Register another user with same username and another email

```
{
    'username': 'strapiuser1',
    'password': 'somepassword',
    'email': 'anotheruser@strapi.com'
  }
```
4. Return error with message "Email already taken"

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                }
            ]
        }
    ]
}
```

### Expected behavior

Valid error message:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.username.taken",
                    "message": "Username already taken"
                }
            ]
        }
    ]
}
```

### Code snippets

[I think it is related to Auth.register function](https://github.com/strapi/strapi/blob/0ab3503e3c68c0e794878324a866ce9e6cfe5d47/packages/strapi-plugin-users-permissions/controllers/Auth.js#L514)

```
try {
  const user = await strapi.query('user', 'users-permissions').create(params);
  ...
 } catch (err) {      
  const adminError = _.includes(err.message, 'username')  ? 
  { id: 'Auth.form.error.username.taken',   message: 'Username already taken',  }  :
  { id: 'Auth.form.error.email.taken', message: 'Email already taken' };
  ctx.badRequest(null, formatError(adminError));    
} 
```
err never contain username and err.message only contain : "Duplicate entry"

Warning is whow in console with good info:
```
warn Duplicate entry Error: insert into `users-permissions_user` (fields...) values (values...) - ER_DUP_ENTRY: Duplicate entry 'strapiuser1' for key 'users-permissions_user_username_unique'
```
But not in catch(err) section

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version:  3.6.2 ( Same with 3.6.3 )
- Database:  mysql ( Same with sqlite )
- Operating system: Windows 10

**Comment by Kvizas** [comment]
Had experienced that too. Change in Auth.register is needed.

For myself, I've done quickfix (not the most optimized one) & inserted in line 486
```
    const usernameCheck = await strapi.query('user', 'users-permissions').findOne({
      username: params.username,
    });
    
    if (usernameCheck) {
      return ctx.badRequest(
        null,
        formatError({
          id: 'Auth.form.error.username.taken',
          message: 'Username is already taken.',
        })
      );
    }````

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/9948
