### ISSUE TITLE
In Strapi Admin number field can't type number in

### ISSUE THREAD

**Issue by thormengkheang** [strapi/strapi#10442]
### Describe the bug

In Strapi Admin when I tried to edit a number field of a collection, I can't type the number in. Can only use the input UI to increase & decrease.

### Steps to reproduce the behavior

1. Create a new Product collection
2. Add new number field Qty
3. Save collection
4. Go to Product collection & Add new Product
5. Type the number in the Qty field

### Expected behavior

Expect to be able to type the number because if use input UI to increase or decrease, it is very difficult to increase or decrease a large amount of number.

### Screenshots

![eiyeyh0vB4](https://user-images.githubusercontent.com/8617506/120886467-4c817780-c618-11eb-84dc-f01551f7c98b.gif)

### System

- Node.js version: v12.20.0
- NPM version: 6.14.8
- Strapi version: 3.1.6 Community Edition
- Database: Postgres
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.1.6 Community Edition

Please test on the latest version v3.6.3

I will reopen once we have confirmation the issue exists on the latest release.

**Comment by thormengkheang** [comment]
I can type the number in version 3.6.3 thanks
