### ISSUE TITLE
Unable to extend strapi-plugin-content-manager on latest version 3.6.3

### ISSUE THREAD

**Issue by joeldacuma** [strapi/strapi#10447]
### Description

Previously I am using version 3.1.6 and able extended update function in content-manager to add certain login for my app in admin-panel. 

Migrating to 3.6.3 it is now generating an error.
Cannot find module 'strapi-plugin-content-manager/controllers/ContentManager'

### Steps to reproduce the behavior

1. update strapi package.json to 3.6.3:
    "strapi": "3.6.3",
    "strapi-admin": "3.6.3",
    "strapi-connector-bookshelf": "3.6.3",
    "strapi-plugin-content-manager": "^3.6.3",
    "strapi-plugin-content-type-builder": "3.6.3",
    "strapi-plugin-email": "3.6.3",
    "strapi-plugin-upload": "3.6.3",
    "strapi-plugin-users-permissions": "3.6.3",
    "strapi-provider-email-sendgrid": "3.6.3",
    "strapi-provider-upload-google-cloud-storage": "3.6.3",
    "strapi-utils": "3.6.3",

2. npm install
3.  add updated function in <root>/extensions/content-manager/controllers/ContentManager.js
4. npm run develop
5. Error occurred:
Error: Cannot find module 'strapi-plugin-content-manager/controllers/ContentManager'
- D:\projects\src\github\journey-api\extensions\content-manager\controllers\ContentManager.js
- D:\projects\src\github\journey-api\node_modules\strapi\lib\load\load-files.js
- D:\projects\src\github\journey-api\node_modules\strapi\lib\core\load-apis.js
- D:\projects\src\github\journey-api\node_modules\strapi\lib\core\load-modules.js
- D:\projects\src\github\journey-api\node_modules\strapi\lib\Strapi.js
- D:\projects\src\github\journey-api\node_modules\strapi\lib\index.js
- D:\projects\src\github\journey-api\node_modules\strapi\lib\commands\develop.js
- D:\projects\src\github\journey-api\node_modules\strapi\bin\strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\projects\src\github\journey-api\extensions\content-manager\controllers\ContentManager.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)

### Expected behavior

App should run without hiccup as it is working for version 3.1.6

### System
- Node.js version: 14.17.0
- NPM version: 6.14.13
- Strapi version: 3.6.3
- Database: Postgres 8.3.2
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
> add updated function in /extensions/content-manager/controllers/ContentManager.js
> npm run develop

You are missing a step here, you need to rebuild the admin using something like `yarn build --clean` or `npm run build -- --clean` between these two.

The develop command will only build the admin if the `build` folder exists and if the .cache exists it will reuse it. The `--clean` flag here ensures that the .cache is bypassed and regenerated.

**Comment by derrickmehaffy** [comment]
As we have had no new information from the user I'm marking as closed.
