### ISSUE TITLE
Polish characters in text fields throw unique constraints errors.

### ISSUE THREAD

**Issue by elm039** [strapi/strapi#10440]
### Describe the bug

Using polish characters, such as "ś" and "ć" in rich text field throws an error when trying to save an entry. Not all special characters throw this error, as "ó" does not.

This throws an error:

> Invalid input data. Please verify unique constraints

There aren't any constraints set on the field.

I'm not using internalization support for this type, but I do have the pl-PL internalization support added in the settings.

### Steps to reproduce the behavior

1. Setup a single type with a rich text field
2. Place the following in the text field:
`
Ó Ł Ś Ć Ź Ń Ą
`
3. Save

### Expected behavior

The entry is saved and the typical success message appears.

### System

- Node.js version: v12.18.0
- NPM version: 6.14.4
- Strapi version: v3.6.2
- Database: MySQL
- Operating system: Windows 10 Pro 64bit

### Additional context

This never happened to me before on previous versions of Strapi. May have something to do with the internalization update?

**Comment by fatbattk** [comment]
My guess is very limited unicode support. 😩  This also happens if you copy paste an emoji to a rich-text field.
Despite what the admin UI error shows (`Invalid input data. Please verify unique constraints`), here is the real error,
> ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE2\x9D\xA4' for column...

**Comment by derrickmehaffy** [comment]
> Database: MySQL

What is your database table type set to? 

```
USE db_name;
SELECT @@character_set_database, @@collation_database;
```

You can also check the servers default:

```
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
FROM INFORMATION_SCHEMA.SCHEMATA;
```

**Comment by fatbattk** [comment]
Aha, of course! 👍🏻 Tested and in my case, this was the reason.
Emoji works after I change the db collation to `utf8mb4_0900_ai_ci` from `latin1_swedish_ci`. I think it'll be valuable to hint at ensuring utf8 charset [here](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database) perhaps? Thank you.

**Comment by elm039** [comment]
Yep, that worked for me as well, thanks!
I've had to update the collation of the db, the table AND individual columns though, for some reason that was hard set to latin instead of using default db collation.

Clearly not an issue with Strapi itself, though like @fatbattk mentioned, it could be valuable to mention this in the docs?

**Comment by derrickmehaffy** [comment]
> Yep, that worked for me as well, thanks!
> I've had to update the collation of the db, the table AND individual columns though, for some reason that was hard set to latin instead of using default db collation.
> 
> Clearly not an issue with Strapi itself, though like @fatbattk mentioned, it could be valuable to mention this in the docs?

This depends on the "source" of your database install, I think native packages in popular linux repos ship with a default my.cnf file that sets that default. Installing MySQL/MariaDB from sources usually defaults to utf8. 

It would also depend on the provider, I don't remember off the top of my head what services like AWS, Azure, GCloud set their defaults to but usually this is one of the first things I will check when using a database with any application (reviewing the default variables).

There is a really long list of defaults, if we dive into one like charset then we may need to dive into others and that would be... a lot lol.

https://mariadb.com/kb/en/server-system-variables/

But for example in MariaDB: 

```
character_set_server
Description: Default character set used by the server. See character_set_database for character sets used by the default database. Defaults may be different on some systems, see for example Differences in MariaDB in Debian.
Commandline: --character-set-server
Scope: Global, Session
Dynamic: Yes
Data Type: string
Default Value: latin1
```

https://mariadb.com/kb/en/differences-in-mariadb-in-debian-and-ubuntu/
