### ISSUE TITLE
Replace Media does not change photo preview outside of details modal

### ISSUE THREAD

**Issue by nicholasconfer** [strapi/strapi#10453]
### Describe the bug

After using the "Replace Media" option in the media library or by editing a image file in the collection itself, the preview of the image does not change even though the file has been updated.

### Steps to reproduce the behavior

1. Go to Media Library
2. Click on a previously uploaded image
3. Click the "Replace Media" button and select a new image
4. Click "Finish"
4. The error now is shown.  While the image has been changed on the server, the preview in media library after the modal closes remains the original image.  
5. You can confirm the replacement did work by refreshing the page, but will not see the change before this is done.

### Expected behavior

After replacing media, the preview image should be updated to reduce user confusion.

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- Strapi version: 3.6.2
- Database: postgres
- Operating system: Windows 10

### Additional context

This is similar to issue #10382 , except the concern in this issue was the final file name, verse the concern here is the final preview shown to the user.  I think even with the same image name, without updating the preview, the user will be confused and believe there replacement didn't work.

**Comment by yanniskadiri** [comment]
Thank you for opening this issue, I will close it for now as it has been solved in V4 :)

**Comment by LishaValiyaparambil** [comment]
Hi Team,
I am facing the same issue in strapi v4.10.5. Any comments.

**Comment by 4benefit** [comment]
same issue on v4.10.5. replacing media, don't upload the new file, don't change preview and url.
when is the fix coming out?

**Comment by 4benefit** [comment]
> Thank you for opening this issue, I will close it for now as it has been solved in V4 :)
no, this issue is still in v4.10.5 see my comment

**Comment by kalwas123** [comment]
> Thank you for opening this issue, I will close it for now as it has been solved in V4 :)

Problem still exists in v4.11.3

**Comment by derrickmehaffy** [comment]
Upgrade to the latest version.

**Comment by Adaphath** [comment]
Hey there,
I am currently on Strapi 4.15.5 and we are experiencing the same problem. The URL and the preview are still the same.

**Comment by nmalyarsky** [comment]
Still an issue in v4.26.1.
