### ISSUE TITLE
strapi webhook as a Systemd service not working

### ISSUE THREAD

**Issue by erik-valtechsd** [strapi/strapi#10450]
Hi - I am following this official Strapi + AWS tutorial and I am stuck on the last step of adding a webhook service.  I enable and start the service `sudo systemctl enable webhook.service` and
`sudo systemctl start webhook` but when I check the status `sudo systemctl status webhook` I get the following error:

```
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: webhook.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: webhook.service: Failed with result 'exit-code'.
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: webhook.service: Service hold-off time over, scheduling restart.
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: webhook.service: Scheduled restart job, restart counter is at 5.
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: Stopped Github webhook.
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: webhook.service: Start request repeated too quickly.
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: webhook.service: Failed with result 'exit-code'.
Jun 06 23:43:42 ip-10-0-0-23 systemd[1]: Failed to start Github webhook.
```

Any idea how to debug / fix this?  Any help is appreciated. thx

**Comment by ChristianHeimke** [comment]
could you provide more information? like syslog after trying to start etc. this would help to find the error... currently it's hard to say what's broken or not working (did you delete the comments as requested in the documentation?)

**Comment by kasonde** [comment]
Hi @erik-valtechsd thanks for the question. It seems you're asking a question as opposed to reporting a bug or submitting a feature request which is perfect for our [Community Forum](https://forum.strapi.io). Consider joining and submitting your question there for myself and other community members to offer assistance while you debug this issue.
