### ISSUE TITLE
Not able to create a collection type named Versions or Version

### ISSUE THREAD

**Issue by shabeebcoder** [strapi/strapi#10456]
When i create a collection type named Version or Versions application is crashing with following error 
 
![image](https://user-images.githubusercontent.com/39030086/121317176-18110280-c91b-11eb-9244-f5084c402b8f.png)

**Comment by kasonde** [comment]
Hello, 
In order to understand more about your issue, Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
