### ISSUE TITLE
SLUG is not generated automatically by internationalisation plugin

### ISSUE THREAD

**Issue by sarsonj** [strapi/strapi#10462]
### Describe the bug
We are using content API to create localised content. We have slug defined as UID type linked to Title of our content type. However, when creating new translation through API the slug field remains empty and I have to go to admin and click on "refresh" on slug.

### Steps to reproduce the behaviour

1. Let's have content type, that has Title (string) and slug (UID linked to Title)
2. Create new entry of that content type in admin interface
3. Create localisation through content API `POST http://localhost:1337/article/8/localizations`
4. Show localisations in admin - no slug is generated

### Expected behaviour

I would expect, that slug will be generated automatically

### System

- Strapi version: 3.6.3 (latest)
- Database: mysql

**Comment by derrickmehaffy** [comment]
> POST http://localhost:1337/article/8/localizations

We don't generally "support" creating content like this as there are end-user endpoints to create entries based on locale. In this case the Admin panel itself handles the UID creation hence why you see that happening.

The actual content-manager plugin's admin interface handles the UID creation by asking the backend if a UID is taken and will "make a suggestion" and populate the UID field before sending the POST request.

**Comment by wintercounter** [comment]
Tbh, this feels incredibly wrong. I'm coming across several differences while using admin, using REST, using GraphQL, and using the Backend API. Would be nice to see Strapi having a more streamlined, and more consistent approaches in v4.

Not to mention that much stuff is simply not documented, for advanced questions the forum is just a junkyard. I constantly find myself digging the source code after hours of googling.
