### ISSUE TITLE
Cannot save UTF-8 emotes in JSON fields, becomes ????

### ISSUE THREAD

**Issue by wintercounter** [strapi/strapi#10468]
### Steps to reproduce the behavior

1. Create a JSON field.
2. Try to save the provided sample.
3. Observe

### Expected behavior

Can save UTF-8 character without any problem.

### Code snippets

Input:
```json
{
  "test": "🦇"
}
```

Becomes:
```json
{
  "test": "????"
}
```

### System

- Node.js version: 12
- NPM version: 6.14
- Strapi version: 3.6.3
- Database: MySQL (MariaDB)
- Operating system: Debian 10

### Additional context

- Table encoding: `utf8mb4_general_ci`
- Database encoding: `utf8mb4_general_ci`

**Comment by derrickmehaffy** [comment]
Tested on MariaDB LTS using utf8mb4 encoding results in a database error response from the Strapi application:

> [2021-06-15T14:31:15.554Z] error Error: insert into `tests` (`created_at`, `json`, `published_at`, `rich_text`, `string`, `updated_at`) values ('2021-06-15 07:31:15.548', '{\"isBook\":true,\"emoji\":\"📘\"}', NULL, 'Book  📘', 'Book  📘', '2021-06-15 07:31:15.548') - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x93\x98"}' for column `strapi`.`tests`.`json` at row 1
>     at Query.Sequence._packetToError (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>     at Query.ErrorPacket (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
>     at Protocol._parsePacket (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/Protocol.js:291:23)
>     at Parser._parsePacket (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/Parser.js:433:10)
>     at Parser.write (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/Parser.js:43:10)
>     at Protocol.write (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (/mnt/storage/Development/test10468/node_modules/mysql/lib/Connection.js:88:28)
>     at Socket.<anonymous> (/mnt/storage/Development/test10468/node_modules/mysql/lib/Connection.js:526:10)
>     at Socket.emit (events.js:314:20)
>     at addChunk (_stream_readable.js:303:12)
>     at readableAddChunk (_stream_readable.js:279:9)
>     at Socket.Readable.push (_stream_readable.js:218:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
>     at Protocol._enqueue (/mnt/storage/Development/test10468/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>     at Connection.query (/mnt/storage/Development/test10468/node_modules/mysql/lib/Connection.js:198:25)
>     at /mnt/storage/Development/test10468/node_modules/knex/lib/dialects/mysql/index.js:134:18
>     at new Promise (<anonymous>)
>     at Client_MySQL._query (/mnt/storage/Development/test10468/node_modules/knex/lib/dialects/mysql/index.js:128:12)
>     at Client_MySQL.query (/mnt/storage/Development/test10468/node_modules/knex/lib/client.js:168:17)
>     at /mnt/storage/Development/test10468/node_modules/knex/lib/transaction.js:325:24
>     at new Promise (<anonymous>)
>     at Client_MySQL.trxClient.query (/mnt/storage/Development/test10468/node_modules/knex/lib/transaction.js:320:12)
>     at Runner.query (/mnt/storage/Development/test10468/node_modules/knex/lib/runner.js:151:36)
>     at /mnt/storage/Development/test10468/node_modules/knex/lib/runner.js:40:23
>     at /mnt/storage/Development/test10468/node_modules/knex/lib/runner.js:277:24
> From previous event:
>     at Child.<anonymous> (/mnt/storage/Development/test10468/node_modules/bookshelf/lib/model.js:1160:42)
> From previous event:
>     at Child.<anonymous> (/mnt/storage/Development/test10468/node_modules/bookshelf/lib/model.js:1159:14)
>     at processImmediate (internal/timers.js:458:21)
> From previous event:
>     at Child.<anonymous> (/mnt/storage/Development/test10468/node_modules/bookshelf/lib/model.js:1060:10)
> From previous event:
>     at runCreate (/mnt/storage/Development/test10468/node_modules/strapi-connector-bookshelf/lib/queries.js:113:45)
>     at /mnt/storage/Development/test10468/node_modules/strapi-connector-bookshelf/lib/queries.js:53:34
>     at /mnt/storage/Development/test10468/node_modules/knex/lib/transaction.js:183:22
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by fatbattk** [comment]
From fixing emojis 💯 on #10440 I know you have to modify Strapi's db config charset too.
Not just the DB (MySQL for me) charset, but the library's connection/query charset.

- _/config/database.js_
```
// added line to connections.default.settings
charset: env('DATABASE_CHARSET', 'utf8mb4')
```

If this worked for this issue too, the fix should be modifying the default charset to `utf8mb4` vs`utf8` only.
https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/knex.js#L29

Or at least set that in the appropriate [database-templates](https://github.com/strapi/strapi/tree/master/packages/strapi-generate-new/lib/resources/templates/database-templates) with notes.

**Comment by wintercounter** [comment]
Adding that line helped me! Should be the default.

**Comment by derrickmehaffy** [comment]
fixed in v4: 
![image](https://user-images.githubusercontent.com/8593673/178841871-e49f1985-e0ed-4638-aa77-97d17e7500b6.png)
