### ISSUE TITLE
Cannot submit an auto-generated but required field on non-draft collection

### ISSUE THREAD

**Issue by arthurwhite** [strapi/strapi#10467]
## Bug report

I wanted to make an auto-generated slug for a collection type that doesn't use a draft/publish system.
I followed the doc on [how to create a slug system](https://strapi.io/documentation/developer-docs/latest/guides/slug.html) but also enforced a *required* constrain on the `slug` field.
And as it's auto-generated, I naturally disabled this field in the admin UI.

Now, I cannot submit an entry, because the `slug` is validated before being populated by the model.

That doesn't happen on collection that still use a draft/publish system.

### Steps to reproduce the behavior

1. Take a collection and **set its *Draft/publish system* to *OFF***.
2. Add a text field in this collection, but **with a required constrain**!
3. In the View configuration, set *Editable field* to *OFF* for this field.
4. Add code to model to auto-generate this field on `beforeCreate` life cycle.
5. Try to create a new entry for this collection: the field doesn't validate.

### Expected behavior

Maybe model's `beforeCreate` and `beforeUpdate` functions should be called before validation?

### Screenshots

<img width="880" alt="autogen-required" src="https://user-images.githubusercontent.com/9503891/121682306-39f5bb00-cabc-11eb-94b6-727e17c7420a.png">

### Code snippets

Code used to auto-generate the field:

```js
const slugify = require("@sindresorhus/slugify")

module.exports = {
  lifecycles: {
    async beforeCreate(data) {
      if (data.name) {
        data.slug = slugify(data.name)
      }
    },
    async beforeUpdate(params, data) {
      if (data.name) {
        data.slug = slugify(data.name)
      }
    },
  },
}
```

### System

- Node.js version: 14.17.0
- NPM version: 6.0.0
- Strapi version: 3.6.3

**Comment by soupette** [comment]
@arthurwhite I understand your use case but the admin panel is not aware that you have some custom code in your lifecycle to auto generate an input. Since the admin panel is using the api it will need some informations in order to by pass the required constraints. 

I am thinking that since this field is required and since you are generating in the backend maybe you could remove the required constraints as this fields will always be created.

**Comment by arthurwhite** [comment]
Yes, that's what I've done: I disabled the required constraint.
If you won't handle this in the admin UI, I'll understand as well since it's not really a bug.

Merci quand même !
