### ISSUE TITLE
Relationship fields shows "details" link even if user doesn't have read access

### ISSUE THREAD

**Issue by VeronQ** [strapi/strapi#10474]
### Describe the bug

A relationship field shows a "details" link next to its dropdown in the Edit view whereas the current user doesn't have read access to this given collection type.

### Steps to reproduce the behavior

1. Add a relationship  field **(a)** to a collection type **(b)**
2. Prevent any role to access this collection type by unticking the Read box
3. Create a new post **(b)** and choose any post **(a)** as relation from the dropdown
4. Post shows "details" link next to the dropdown whereas the user is not supposed to have access to

**Sidenote:** while indeed after clicking on "details", the user can't see the content from this page as it it blank, it shows an infinitte loader.

### Expected behavior

Details link should be hidden if the current user does not have access to this collection type view

### Screenshots

![](https://nsa40.casimages.com/img/2021/06/13/210613051646767645.png)

### System

- Node.js version: 14.0.0
- NPM version: 6.14.4
- Strapi version: 3.6.3 (EE)
- Operating system: macOS 10.15.7

**Comment by derrickmehaffy** [comment]
I know this issue is a duplicate, but for the life of me I can't find the older issue :thinking: 

---

@VeronQ we are aware of this in the v3 and it's something we actually plan to address in the v4 with relational permissions.

**Comment by derrickmehaffy** [comment]
Duplicate of: https://github.com/strapi/strapi/issues/9140
