### ISSUE TITLE
Webhook data does not contain __component attribute

### ISSUE THREAD

**Issue by WWAZ** [strapi/strapi#10472]
## Bug report
__component attribute is missing in webhook data. 

### Describe the bug
When requesting a collection type's data by api, which contains a dynamic zone named 'content', components contain the __component attribute – great, like expected. After updating the collection type and checking the data send by webhook, the __component attribute is missing.

### Steps to reproduce the behavior
1. Create a collection type containing a dynamic zone, containing a component.
2. Enter some data and save.
3. Request the collection type by api – __component attribute should be present.
4. Update the collection and check the data send by webhook – __component attribute should be missing.

### Expected behavior
__component attribute should always be present.

By the way it would be great when nested components would contain the __component attribute as well. This would enable more use cases.

#### Api call
<img width="440" alt="strapi-component-bug-api" src="https://user-images.githubusercontent.com/25566288/121717829-ebf3ae00-cae1-11eb-996b-fb78207d48c0.png">

#### Webhook data
<img width="463" alt="strapi-component-bug-webhook" src="https://user-images.githubusercontent.com/25566288/121717837-ec8c4480-cae1-11eb-9377-833b2c05d691.png">

### System
- Node.js version: 14.17.0
- NPM version: 6.14.13
- Strapi version: 3.6.3
- Database: Mysql
- Operating system: Mac OS 10.15.6

**Comment by WWAZ** [comment]
Hi Richard,

thanks for reviewing this issue. However, I think that this is more of a bug than a possible enhancement. This issue touches data consistency.

When we talk about performant applications, API requests have to be cached. In this setting, webhooks are an important component of cache management - they inform us about any changes to models. If the webhook data could be trusted, the data supplied could simply be written to the cache. In practice, however, we now have to query the data from the API again with each webhook request. Unfortunately, this is not an optimal solution.

Best regards
Alex

**Comment by z0lo13** [comment]
I think it is related to #12999
