### ISSUE TITLE
Relational model data issue 

### ISSUE THREAD

**Issue by pakwai122** [strapi/strapi#10481]
I got a collection of articles that has multiple categories, and the relationship between them is N to N. I tried to send a PUT request in JSON format 
`{
        "categories" :[{"id" :10}, {"id" : 11 }]
  }` to the article and update its category ids, for example, https://localhost/article/3. If I send an empty record or the same id records. It won't take the empty record or duplicate id records, which is fine, but the admin panel will show the number of items inconsistently 
<img width="102" alt="Screenshot 2021-06-15 at 8 50 34 AM" src="https://user-images.githubusercontent.com/8893263/121978148-2d25df80-cdba-11eb-9ad8-0a7f80c46a47.png"> If I click to see the details, the category field will show the actual number of items.

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
