### ISSUE TITLE
The i18n plugin offers no way to access localizations via services, models, or other programmatic interfaces

### ISSUE THREAD

**Issue by Drarok** [strapi/strapi#10497]
### Describe the bug

[The documentation](https://strapi.io/documentation/developer-docs/latest/development/plugins/i18n.html#usage-with-strapi-content-api) only shows ways to access localized content via the REST API and the GraphQL plugin.

In order to import data from external sources, I was writing a script using [queries](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#queries) and got stuck once I needed to update/create localized data.

### Steps to reproduce the behavior

1. Attempt to access localized content via query
2. Get stuck

### Expected behavior

There should be programatic access to the localized content.

### System

- Node.js version: all
- NPM version: all
- Strapi version: 3.6.*
- Database: all
- Operating system: all

**Comment by derrickmehaffy** [comment]
Should be resolved in the v4, marking as closed
