### ISSUE TITLE
Can anyone explain why the data integrity with strapi is so poor?

### ISSUE THREAD

**Issue by rinse0ut** [strapi/strapi#10491]
How can I update an entity and other foreign keys get set to null?

I'm well into my project and am experiencing some worrying issues.

Is there some kind of weird orm cascade going on?

I can't even set not null in the db for fields. :(

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
