### ISSUE TITLE
Quick starter project incorrectly named database collections

### ISSUE THREAD

**Issue by jkerys-halo** [strapi/strapi#10490]
Installing `npx create-strapi-starter my-project next-corporate` creates a new project with incorrectly named database tables for components, not following table naming convention. Seen that about half of components were moved between categories, without updating table names. For example, in `elements` category, `testimonial.json` has `"collectionName": "components_slices_testimonials",`, which obviously points that component was moved from `slices` category.
Guess the same issue may exist for more starter projects.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
