### ISSUE TITLE
 relational field counting issue

### ISSUE THREAD

**Issue by pakwai122** [strapi/strapi#10508]
### Describe the bug

I got a collection of articles that have id, title, and content, another collection of categories that have a name, and related to articles. A many-to-many relationship. I tried to send a PUT request to update the existing article record with a category id, for example, update articles with id =1, and category = "" / id doesn't exist.
HTTP://localhost:1337/articles/1
id doesn't exsit
{
    "categories":[{"id":10}]
}
or id is empty
{
    "categories":[{"id":""}]
}

the admin panel will show the wrong number 

### Steps to reproduce the behavior

1. Open postman
2. send put request to the API URL for specific article id, for example, HTTP://localhost:1337/articles/1
3. add JSON format body {
    "categories":[{"id":""}]
}
4. back to Strapi admin panel, and check the category field record.

### Expected behavior

Even update(PUT) an empty id or category id doesn't exist, the admin panel counting should be the same as the JSON response, The JSON response works fine, but admin panel doesn't.

### Screenshots
Send PUT request to the existing record with empty category id, it will return code 200 for success.
<img width="1408" alt="Screenshot 2021-06-18 at 2 02 16 PM" src="https://user-images.githubusercontent.com/8893263/122514035-d597a600-d03d-11eb-9336-0fd7bff30215.png">

For the admin panel will show the wrong counting number
<img width="2010" alt="Screenshot 2021-06-18 at 2 11 55 PM" src="https://user-images.githubusercontent.com/8893263/122514924-4095ac80-d03f-11eb-9a1c-662d0befa577.png">

### System

- Node.js version: v14.6.1
- NPM version:6.x
- Strapi version: 3.6.3
- Database: MySQL
- Operating system: ubuntu

**Comment by derrickmehaffy** [comment]
Confirmed on v3.6.5

Not only is the relational field structure wrong (you don't use an array of objects) but the category ID 10 doesn't exist.

**Comment by pakwai122** [comment]
> Confirmed on v3.6.5
> 
> 
> 
> Not only is the relational field structure wrong (you don't use an array of objects) but the category ID 10 doesn't exist.

What does it mean?

**Comment by pakwai122** [comment]
> Confirmed on v3.6.5
> 
> 
> 
> Not only is the relational field structure wrong (you don't use an array of objects) but the category ID 10 doesn't exist.

How can I fix it?

**Comment by derrickmehaffy** [comment]
> What does it mean?
> How can I fix it?

It means I can confirm the bug exists, we don't have a fix yet.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7631
