### ISSUE TITLE
Option to filter by Draft/Published entries

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#10502]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I want to request an option to filter by Draft/Published entries.

### Why is it needed?

We have users with no publish access, with the intention of first reviewing the content they have created. Being able to filter the entries by Drafts would be very convenient.

### Suggested solution(s)

Offer a filter by Draft/Published entries.

**Comment by abdonrd** [comment]
Also I think it should also be able to be filtered by the author of the entries.

**Comment by derrickmehaffy** [comment]
Already possible in the v4 (for draft & publish, @abdonrd can you open a new feature request on https://feedback.strapi.io for relational stuff in the admin)
