### ISSUE TITLE
Show creation information in the detail view

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#10501]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Right now we have the last updated info like:

<img width="314" alt="Screenshot 2021-06-17 at 11 54 05" src="https://user-images.githubusercontent.com/1007051/122376307-52565180-cf64-11eb-8c70-4a0e5a061563.png">

I think it would be great to show the creation information as well. Maybe something like this would be enough?

<img width="311" alt="Screenshot 2021-06-17 at 11 56 25" src="https://user-images.githubusercontent.com/1007051/122376389-6732e500-cf64-11eb-826e-de6b94b949e4.png">

### Why is it needed?

To find out who created the entry.

**Comment by derrickmehaffy** [comment]
I agree this would be very nice to have

**Comment by derrickmehaffy** [comment]
cc @maevalienard / @sam-pires / @JabStrapi

**Comment by abdonrd** [comment]
This can also help a little bit to understand why the Forbidden notification here: https://github.com/strapi/strapi/issues/10514

**Comment by abdonrd** [comment]
@sam-pires any news here? Thanks!
