### ISSUE TITLE
Create wrong sql with publish_at

### ISSUE THREAD

**Issue by playerthong** [strapi/strapi#10500]
Hi Strapi , I found one critical bug

This is my query I want to run

select distinct `orders`.*, `orders`.`created_at` as `_strapi_tmp_orders_created_at` from `orders` 
left join `bluebolt`.`company_profiles` as `company_profiles_1` on `company_profiles_1`.`id` = `orders`.`partner_worker_company` 
left join `bluebolt`.`company_profiles` as `company_profiles_2` on `company_profiles_2`.`id` = `orders`.`partner_customer_company` 
where (((`company_profiles_1`.`id` = 7)) or 
((`company_profiles_2`.`id` = 7)))  order by `_strapi_tmp_orders_created_at` desc limit 10

However I run with strapi query and I see the log of query is 
select distinct orders.*, orders.created_at as _strapi_tmp_orders_created_at from orders left join bluebolt.company_profiles as company_profiles_1 on company_profiles_1.id = orders.partner_worker_company left join bluebolt.company_profiles as company_profiles_2 on company_profiles_2.id = orders.partner_customer_company where ((((((company_profiles_1.id = 7)) or ((company_profiles_2.id = 7)))))) and (company_profiles_1.published_at is not null) and (company_profiles_2.published_at is not null) and (orders.published_at is not null) order by _strapi_tmp_orders_created_at desc limit 10

Strapi auto add published_at into query and cause wrong query . How could I remove published_at ?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
