### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by alvarofranz** [strapi/strapi#10519]
I am following the official guide with node 14, and I am unable to install strapi:

Error log in the console shows:

```
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-strapi-app@3.6.3" with binaries:
      - create-strapi-app
"C:\Users\Harry" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
error Command failed.
Exit code: 1
Command: C:\Users\Harry Potter\AppData\Local\Yarn\bin\create-strapi-app
Arguments: merfrefefr
Directory: C:\Users\Harry Potter\Desktop\k
Output:
```

**Comment by alvarofranz** [comment]
Apparently a yarn bug, that happens when the Windows username contains a space.

https://github.com/yarnpkg/yarn/issues/6630

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
