### ISSUE TITLE
Invalid docs link in Settings > Webhooks

### ISSUE THREAD

**Issue by devzom** [strapi/strapi#10515]
### Steps to reproduce the behavior

1. Go to admin panel
2. Click on Settings in sidebar, and then pick Webooks
3. Click on link 'See the documentation'
4. You'll be redirected to invalid link [Webhooks invalid documentation link](https://strapi.io/documentation/developer-docs/latest/concepts/webhooks.html)

**Comment by kasonde** [comment]
Closing this issue here. Please resubmit the issue and follow the issue template by providing information relevant to the issue, i.e system information in this case.

Additionally, this issue was fixed in v3.6.3 of Strapi.  #10309
