### ISSUE TITLE
Move :_id validation to routes.json?

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#1051]
**What is the expected behavior?**

More of a refactor than a feature.  Right now strapi generates parameter validation code in the actions like this:

    if (!ctx.params._id.match(/^[0-9a-fA-F]{24}$/)) {
      return ctx.notFound();
    }

Would it make more sense for this kind of validation to live in `routes.json`?:

      "method": "GET",
      "path": "/blah/:_id([0-9a-fA-F]{24})",

---

- [X] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Actually this code is for mongoose controller template and not for bookshelf template.

If we move it in routes.json file. It will be applied on both, mongoose and bookshelf and it's not what we want.

**Comment by nurikabe** [comment]
Ah, right :bulb:
