### ISSUE TITLE
Don't override the favicon

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#10511]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

When you update the `favicon.ico` file in the project root, we expect to have our favicon. But after appearing for a moment, then it disappears.

We find this hardcoded data:

<img width="700" alt="Screenshot 2021-06-18 at 11 50 24" src="https://user-images.githubusercontent.com/1007051/122543041-a4ae7580-d02b-11eb-8a1c-3b8fb2a37ffa.png">

### Why is it needed?

To really allow customize the favicon.

### Suggested solution(s)

Don't override it.

**Comment by derrickmehaffy** [comment]
I believe this should be fixed in the v4, if not please open a bug report
