### ISSUE TITLE
Admin path does not work for non-root proxy host 

### ISSUE THREAD

**Issue by Danial-Zafar** [strapi/strapi#10517]
This is an issue is related to #4513. I face the same while using Nginx for redirecting strapi in my sub-dir. I showing two different versions of the Nginx configuration that were not working and the other was not.
Following was not working
``

# Upstream server for Node Api

upstream server {
	server 127.0.0.1:8081;
}

upstream strapi_server {
	server 127.0.0.1:1337;
}

server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	return 301 https://$host;

	server_name _;
}

server {
	listen 443 ssl;

	# SSL certificate and Key
        ........

	location / {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://server;
        	proxy_connect_timeout       900;
        	proxy_send_timeout          18000;
        	proxy_read_timeout          900;
        	send_timeout                18000;
        	proxy_pass_request_headers on;
	}

	location /cms {
		proxy_pass http://strapi_server;
        	proxy_connect_timeout       900;
        	proxy_send_timeout          18000;
        	proxy_read_timeout          900;
        	send_timeout                18000;
        	proxy_pass_request_headers on;
	}
}
``
Working configuration
``
# Upstream server for Node Api

upstream server {
	server 127.0.0.1:8081;
}

upstream strapi_server {
	server 127.0.0.1:1337;
}

server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	return 301 https://$host;

	server_name _;
}

server {
	listen 443 ssl;

	# SSL certificate and Key
        ........

	location / {
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_pass http://server;
        	proxy_connect_timeout       900;
        	proxy_send_timeout          18000;
        	proxy_read_timeout          900;
        	send_timeout                18000;
        	proxy_pass_request_headers on;
	}

	location /cms /{  #you nee to add this forward slash here and in the proxy_pass well in order to ma /admin work as well
		proxy_pass http://strapi_server/;
        	proxy_connect_timeout       900;
        	proxy_send_timeout          18000;
        	proxy_read_timeout          900;
        	send_timeout                18000;
        	proxy_pass_request_headers on;
	}
}
``
``

I am not reporting an issue here I am just sharing how I resolve this problem. I face this issue and fount no solution.

**Comment by kasonde** [comment]
Hi @Danial-Zafar thanks for the information. Please consider posting this on the [Community Forum](https://forum.strapi.io) as it not an issue.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/8616
