### ISSUE TITLE
Cannot upload files bigger than 2gb

### ISSUE THREAD

**Issue by Batleram** [strapi/strapi#10526]
### Describe the bug

While setting up strapi to allow files bigger than 200mb, i have encountered a barrier at approximately 2gb file sizes.

### Steps to reproduce the behavior

1. Navigate to the Strapi Media Library
2. Upload a file larger than 2gb

### Expected behavior

The file to upload successfully

### Resulting behavior

code 413 with error message:
```
{
   "statusCode":413,
   "error":"Request Entity Too Large",
   "message":"FileTooBig",
   "data":{
      "errors":[
         {
            "id":"Upload.status.sizeLimit",
            "message":"<filename> file is bigger than the limit size!",
            "values":{
               "file":"<filename>"
            }
         }
      ]
   }
}
```

### Code snippets
extensions/upload/config/settings.json
```
{
   "provider": "local",
   "providerOptions":{
      "sizeLimit": 4294967296
   }
}
```
config/middleware.js
```
module.exports = {
    settings: {
      parser: {
        enabled: true, 
        multipart: true,
        formidable: {
          maxFileSize: 4294967296, 
        }, 
      },
    }, 
  };                          
```

### System

- Strapi:3.6.3 docker container
- Database: MariaDB:10.5 docker container
- Operating system: Debian 10 buster

**Comment by kasonde** [comment]
Hi @Batleram do you have any sort of reverse proxy serving your strapi app like Nginx? Also is this running locally?

**Comment by Batleram** [comment]
Yes i do have nginx setup, but in this case I was going directly to the running port and not passing through any proxy

**Comment by Batleram** [comment]
@kasonde it has almost been a week, any update?

**Comment by kasonde** [comment]
Hi @Batleram, I'm still investigating more with this issue and trying to gather information about why this could be caused. I'm unfortunately unable to replicate the issue with the environment you specified. 

Replies on community help threads happen on a "best effort basis" we cannot always respond to every issue. If you require SLA-based help (time-sensitive) we have enterprise plans that include those options starting from our Silver (limited) to our Gold (has SLAs).

If immediate help is what you need, I would suggest reviewing our Enterprising pricing: https://strapi.io/pricing-self-hosted
