### ISSUE TITLE
[2021-06-22 23:01:09] Error while running command build: Could not load js config file /workspace/config/env/production/database.js: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by jvink** [strapi/strapi#10527]
[2021-06-22 23:01:09] Error while running command build: Could not load js config file /workspace/config/env/production/database.js: Cannot read property 'charAt' of undefined

I think it's about this line of code: `const config = parse(process.env.DATABASE_URL);`

_Originally posted by @jvink in https://github.com/strapi/documentation/issues/302#issuecomment-866394481_

**Comment by jvink** [comment]
Env variable is correctly added:

<img width="893" alt="Screenshot 2021-06-23 at 01 08 53" src="https://user-images.githubusercontent.com/27773080/123010795-95c71a80-d3bf-11eb-86c0-42c36e99e17e.png">

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

**Comment by trangchongcheng** [comment]
This i my config, but i still get this error...how can fix it?

![Screen Shot 2021-09-02 at 23 04 26](https://user-images.githubusercontent.com/9212168/131878519-af5618e1-d737-4529-8735-f73bbf7ecd05.png)
![Screen Shot 2021-09-02 at 23 05 09](https://user-images.githubusercontent.com/9212168/131878527-e32dbcb9-17e3-4432-8abe-3b770c126efa.png)

**Comment by AtticusCMBM** [comment]
I'm having the same issue
