### ISSUE TITLE
Wrong welcome page template rendering in Strapi v3.6.3

### ISSUE THREAD

**Issue by dappiu** [strapi/strapi#10533]
Today I opened Strapi UI, but forgot to write `/admin` in the path and I noticed this strange behaviour. The home page is interspersed with template strings. Here's a picture:
![Strapi_welcome_page](https://user-images.githubusercontent.com/2302314/123083258-2f261900-d420-11eb-96fd-d213def941ae.png)

I can't say when this happened for sure because I don't always open Strapi UI on the `/` path, but I usually navigate always to `/admin`, but I remember having seen the page without issues a couple of weeks ago. This morning all my environments (all with version 3.6.3) presents this issue.

Everything else continues to work as expected, so this is not critical (but one should navigate to /admin for himself, as the buttons' links are corrupted.

The login page continues to work as intended, and I can also see my custom logo, which is missing on the welcome page.

### System
- yarn.lock [yarn.lock.zip](https://github.com/strapi/strapi/files/6701198/yarn.lock.zip)
- Node.js version: 14.17.0
- NPM version: 6.14.13
- Strapi version: 3.6.3
- Database: PostgreSQL 12.5
- Operating system: `Linux 5.8.0-1035-aws #37~20.04.1-Ubuntu SMP x86_64 GNU/Linux`

**Comment by kasonde** [comment]
Hi @dappiu, did this issue occur after an upgrade or was this quite literally you navigating to the domain that your strapi app lives on to view the app?

**Comment by Yondo202** [comment]
test

**Comment by dappiu** [comment]
I tracked down this issue and is not on Strapi itself but on a (really nice) Strapi plugin that I updated yesterday: [strapi-plugin-email-designer](https://github.com/alexzaganelli/strapi-plugin-email-designer/releases)

I don't really know yet which the problem really is, but looking at the last release changelog, I see they changed default lodash templating tags, so it's easy to suspect that this may be the problem.

I'm gonna report the issue to the plugin's developers so I'm closing this.

**Comment by alexzaganelli** [comment]
Thank you @dappiu for your contribution. Now it should be fixed on [🔖 1.1.3](https://github.com/alexzaganelli/strapi-plugin-email-designer/releases/tag/1.1.3)
