### ISSUE TITLE
edit option for draft content is disabled

### ISSUE THREAD

**Issue by chandra655** [strapi/strapi#10539]
### Expected behaviour 

Draft content still should be editable

### System

- Node.js version: v12.18.1
- NPM version: v6.14.10
- Strapi version: 3.6.2
- Database: mysql
- Operating system: OSX/linux

**Comment by kasonde** [comment]
Hello, 
Please resubmit your issue while respecting the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md). If instead, you meant to ask a question, I recommend posting it on the [Community Forum](https://forum.strapi.io).
