### ISSUE TITLE
Add a `name` property in attribute entry (model)

### ISSUE THREAD

**Issue by jsamr** [strapi/strapi#1053]
**What is the expected behavior?**

Allow separation between model attributes names and domain names. I.E, I'd like content editors to read "user-friendly" names when they generate content. Perhaps this could go along with content internationalization. 

Sample `*.settings.json`

``` json
{
  "connection": "default",
  "collectionName": "accompaniment",
  "info": {
    "name": "accompagnement",
    "description": ""
  },
  "attributes": {
    "titleText": {
      "multiple": false,
      "type": "string",
      "required": true,
      "name": "Titre de l'accompagnement"
    }
  }
}

```

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
I think it's in the same way as this issue https://github.com/strapi/strapi/issues/661#issuecomment-368846919 can you confirm that @jsamr

**Comment by jsamr** [comment]
@lauriejim Almost, but ideally it would also be integrated with UI localization, so I have attribute names updated when I switch to another locale.

**Comment by jsamr** [comment]
@lauriejim I close this issue and I'll put my suggestion in the aforementioned ticket.
