### ISSUE TITLE
Data vanishing for repeatable component & dynamic zone component even after saving for Collection Types 

### ISSUE THREAD

**Issue by shashika-v** [strapi/strapi#10549]
Data keeps vanishing even after saving for dynamic zone & repeatable component fields

### Describe the bug

I have created a collection type having dynamic zone & repeatable component as fields. Everything looks fine with respect to fields. But when I try to add actual data to the collection types, the data for the dynamic zone & repeatable component fields vanish as soon as I save the data. 

### Steps to reproduce the behavior

1. Add a dynamic zone while creating any collection type
2. Add an existing component that has repeatable component within it.
3. Save the collection type.
4. Now, go to the Collection type & add new data for the same.
5. After you add the data to the dynamic zone, save the changes.
6. We get a toast saying Saved, but the data just vanishes for the dynamic zone.

This isn't happening for all collection types, but only for few.

### Expected behavior

Data should remain as it is after save.

### Screenshots

Before save
<img width="881" alt="Screenshot 2021-06-26 at 7 39 19 PM" src="https://user-images.githubusercontent.com/55730354/123515787-79282c80-d6b6-11eb-9469-26149561321f.png">

After save, the options just vanish.
<img width="874" alt="Screenshot 2021-06-26 at 7 39 58 PM" src="https://user-images.githubusercontent.com/55730354/123515797-8a713900-d6b6-11eb-8d1c-1990a0731b69.png">

### System

- Node.js version: v14.4.0
- NPM version: 6.14.4
- Strapi version:  Community Edition 3.5.4 
- Database: MySQL v8.0.23
- Operating system: MacOS 11.2.1

**Comment by derrickmehaffy** [comment]
> Strapi version: Community Edition 3.5.4

Can you please test on the latest version: v3.6.5

**Comment by derrickmehaffy** [comment]
this is one very old issue with no updated info. closing
