### ISSUE TITLE
[CLI] Wrong E-commerce template url

### ISSUE THREAD

**Issue by htdangkhoa** [strapi/strapi#10546]
### Describe the bug

Hi there!

As the title, when I use the `create-strapi-app` to create my project using the E-commerce template, the CLI throw the error `Could not find the information for strapi/strapi-template-e-commerce. Make sure it is publicly accessible on github.`

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/15341301/123375088-65939d80-d5b2-11eb-9b47-e9b907c04974.png)

### Expected behavior

I try to fetch your [template data](https://api.github.com/repos/strapi/community-content/contents/templates/templates.yml) and decode it, I see the name's repo is incorrect (`strapi/strapi-template-e-commerce`, it should be [`strapi/strapi-template-ecommerce`](https://github.com/strapi/strapi-template-ecommerce)).

Please update the template data at [this](https://github.com/strapi/strapi/blob/master/packages/create-strapi-app/utils/prompt-user.js#L103).

### System

- Node.js version: 14.17.0
- NPM version: 6.14.13
- YARN version: 1.22.10
- Strapi version: 3.6.5
- Database: n/a
- Operating system: MacOS Big Sur

Please correct me if I'm wrong, thanks.

**Comment by markkaylor** [comment]
Hello @htdangkhoa, thanks for reporting the issue.  I see the problem and will open a PR to fix it today.  In the meantime you should still be able to create your project with one of the following commands:
```
yarn create strapi-app --template https://github.com/strapi/strapi-template-ecommerce
```
or 
```
yarn create strapi-app --template ecommerce
```

Let me know if you have anything other problems

**Comment by markkaylor** [comment]
@htdangkhoa you should be all set now to create an E-commerce project using the CLI prompts.
