### ISSUE TITLE
Organize entities into folders

### ISSUE THREAD

**Issue by AbrahemAlhofe** [strapi/strapi#10545]
### Please describe your feature request

- [ ×] **I have created my request on the Product Board before I submitted this issue**
- [ ×] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Add ability to organize entities / instances and i18n to this folders

### Why is it needed?

that will facilitate a lot of things like making a navigation menu with a high level of deep content (ex. /docs/intro/installation )

### Suggested solution(s)

Click on "add" button and choose create folder or create component then i can add folder with its slug, name and description

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
I'm not entirely sure what you mean by folders here, can you give some more examples?

**Comment by AbrahemAlhofe** [comment]
Imagine it like a file system but instead of files the components instances ( entities ) will be

**Comment by derrickmehaffy** [comment]
Are you referring to the left menu and the same content as this issue?

https://github.com/strapi/strapi/issues/900

**Comment by AbrahemAlhofe** [comment]
Yah, but to be for this folders a real effect, like getting entity by path ( ex. /folder/entity )
So each folder will have own name and slug
I will be a good replace for category, since i can get structure of folder to represent as a navigation menu

**Comment by AbrahemAlhofe** [comment]
Or we can add possibility to get nested entity by slug

**Comment by derrickmehaffy** [comment]
Marking as closed as this isn't likely something we will do

**Comment by robclancy** [comment]
I was very surprised when I realized this wasn't a thing. Especially since it is already done for components. Coming from directus this might be a show stopper.
