### ISSUE TITLE
Add Scottish Gaelic to the i18n plugin

### ISSUE THREAD

**Issue by conorjohn** [strapi/strapi#10558]
My update

Hello 👋

I'm adding Celtic (Irish, Manx, Cornish, Welsh etc) languages to this app I am making with Strapi as the CMS, genuinely love it. I noticed Scottish Gaelic was missing, do you think we could add that to the i18n plugin? If it's something I can help with that'd be great. And is there a way I can contribute if I notice any more missing? Because I noticed Navajo is missing too but I don't have a use for it at the moment.
![image](https://user-images.githubusercontent.com/7226984/123651042-0f796100-d823-11eb-9618-3d66641bf30c.png)

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thanks for your time

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by conorjohn** [comment]
> Hello,
> 
> I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Hey, yeah I've a question on [the forum](https://forum.strapi.io/t/requesting-more-languages-for-internationalization/5587) already but there's been no interaction on that yet, so I thought I'd try github, I was directed here on my [previous ticket](https://github.com/strapi/community-content/issues/416), what's the best way I can get it addressed? 

Thanks very much!

**Comment by derrickmehaffy** [comment]
Ah alright, I didn't read through this completely since it didn't use one of our issue templates. This is a feature request.

**Comment by conorjohn** [comment]
Oh I see, sorry, I had use *a template*, just clearly the wrong type, that's my bad, thanks for reopening this!
And if there's anything else I can do to help just give me a shout 😄

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/add-scottish-gaelic-to-the-i18n-plugin
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
