### ISSUE TITLE
Separation between api, table and UI names

### ISSUE THREAD

**Issue by jsamr** [strapi/strapi#1055]
**What is the expected behavior?**

In models, I'd like to have a clear separation between:

- database collection/table names
- api route names (often the same)
- UI localized names

With the same rationale as in #1053, UI names or domain names are consumed by content creators, which might not master the language database collection names were written in.

---

- [x] I'm sure that this issue hasn't already been referenced

**Comment by derrickmehaffy** [comment]
@jsamr just wanted to copy this into here as well, I feel this ticket is very much related to my open ticket: https://github.com/strapi/strapi/issues/661

Which the strapi team have stated is do-able and likely will be done after more initial code stabilization is done.

**Comment by lauriejim** [comment]
Yes it's the same topic. I think the best wait it to discus on #661, define specs on it.
When it's done @Aurelsicoko write a resume of it and then we lock the conversation.
