### ISSUE TITLE
Nested component shows "No permission to see this field"

### ISSUE THREAD

**Issue by shahidcodes** [strapi/strapi#10550]
### Describe the bug

I have a content type "transaction", it has an "invoice" single component and the "invoice" single component has "lineItems" repeatable component. 
The lineItems component is newly added. I have checked the lineItems checkbox in permission and role for that role
![image](https://user-images.githubusercontent.com/17620737/123535755-4c6c2780-d73f-11eb-896d-e33607434e77.png)

But the users with the role is seeing "No permissions to see this field"
![image](https://user-images.githubusercontent.com/17620737/123535774-77567b80-d73f-11eb-95bc-242db8456442.png)

### Steps to reproduce the behaviour

1. Go to 'Content-Type'

1. Create a content type with the transaction and add a invoice single component
2. Create a user with non-super admin role  (editor/author) and give access to transaction and all invoice field
3. Edit `Transaction` Content-Type and add new `lineItem` repeatable component in `invoice` single component
4. Edit the non-super admin rol which access was granted to the above user, and grant lineItems access. (it should look like first screenshot)
5. Go to transaction content manager, and add a transaction
6. It will show no permission to Lineitems field.

### Expected behavior

It should be allowed if the access if granted to the role

- Node.js version: v14.17.0 
- NPM version:7.14.0
- Strapi version:  3.6.2
- Database: MongoDB
- Operating system: Ubuntu 20.10

### Additional Info
Super admin can access the field

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.6.2

Can you please try updating your application to the latest version: v3.6.5 (don't forget to delete your package-lock.json or yarn.lock and rebuild your admin panel)

**Comment by derrickmehaffy** [comment]
No response from user, marking as closed.

**Comment by SANDEEP-226** [comment]
I am using the latest version v4.1.8, But I am not able to edit the nested components. Ex:- if I have a collection type in which I have a component as General Setting which has 4 fields the either all 4 of them can be selected or none of them will be selected 

![image](https://user-images.githubusercontent.com/64078817/166888787-c5781c6f-ccb3-4050-836f-df8c5b0ba799.png)

like this, I can I have control over this.
