### ISSUE TITLE
POST to auth/local should return desired parameters

### ISSUE THREAD

**Issue by fmubaidien** [strapi/strapi#10567]
## Bug report

When a 400 bad request is sent o auth/local the desired parameters are not returned, instead an incorrect JSON returns

### Steps to reproduce the behavior
To reproduce simply POST a bad request (Empty) to auth/local

### Expected behavior

I expected the return to be the desired keys e.g:
{
"uesrname"
"password"
}

### Screenshots
![image](https://user-images.githubusercontent.com/32209468/124099085-d54bd180-da65-11eb-9f5a-2cce7ce35e29.png)
![image](https://user-images.githubusercontent.com/32209468/124099116-dda40c80-da65-11eb-9190-ef5eebb85cb7.png)

### System

- Node.js version: v12.20.1
- Strapi version: 3.6.3
- Database: Mongodb
- Operating system: Fedora

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7746
