### ISSUE TITLE
`request` from `strapi-helper-plugin` tries to parse JSON for `204 No content` response

### ISSUE THREAD

**Issue by viters** [strapi/strapi#10562]
### Describe the bug

`request` from `strapi-helper-plugin` tries to parse JSON for `204 No content` response

### Steps to reproduce the behavior

1. Use `import { request } from 'strapi-helper-plugin';`
2. Call API that returns 204 response with `request`
3. See error that JSON cannot be parsed

### Expected behavior

Response should not be parsed for 204 status

### Additional context

https://github.com/strapi/strapi/blob/master/packages/strapi-helper-plugin/lib/src/utils/request.js

**Comment by daniel-julius-sam** [comment]
Can you give an example for the `request` that gives a `204 error` so that I can do some work on this issue?

**Comment by derrickmehaffy** [comment]
Shouldn't apply in the v4
