### ISSUE TITLE
Changing Media Library image file name doesn't change the file name in the image link.

### ISSUE THREAD

**Issue by allanesquina** [strapi/strapi#10564]
Hi guys, I hope you're doing well.

I'm no sure if it is a bug or a misunderstanding.
After uploading an image to the media library and changing the file name of that image, the link remains the same. 
If I download that image I get the correct name, but when I try to open the image link I get the old name.

Is this the expected behavior?

I'm using Strapi Docker
 
![image](https://user-images.githubusercontent.com/3584636/124037006-3e373900-d9d5-11eb-90e6-9c38f375902a.png)

Thank you.

**Comment by derrickmehaffy** [comment]
Hi @allanesquina yes right now this is intended behavior as the providers do not have functions to handle renaming.

Right now all of our providers can only handle:

- Upload
- Delete

For example in the local provider: https://github.com/strapi/strapi/blob/23bd0226a594058f5b0b25c82aa03f90b691df9b/packages/strapi-provider-upload-local/lib/index.js#L27-L64

**Comment by allanesquina** [comment]
Hi @derrickmehaffy, thank you for the explanation, so it was my misunderstanding.

Loved project BTW.

**Comment by derrickmehaffy** [comment]
We will keep the issue around as a feature request/enhancement request since it's a question that comes up here and there. :)

**Comment by jamielaw-jellyfish** [comment]
After trying out Strapi, this was the first major limitation I encountered in the app. What made it feel like a bug was that it was possible to change the file name in the UI. I guess I would have expected that field to be read-only.

Would it be at all possible to fake a rename by doing a `delete` followed by an `upload`, or does that cause problems under the hood?

**Comment by derrickmehaffy** [comment]
> After trying out Strapi, this was the first major limitation I encountered in the app. What made it feel like a bug was that it was possible to change the file name in the UI. I guess I would have expected that field to be read-only.
> 
> Would it be at all possible to fake a rename by doing a `delete` followed by an `upload`, or does that cause problems under the hood?

That would be fairly destructive I think under the hood. The potential for data loss as a risk would be much higher. (think if a disk was out of space and other services were trying to write to disk, you read the file into memory, delete it, and try placing it again would fail. This isn't a perfect example and has workarounds but this is just one example.)

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/changing-media-library-image-file-name-doesnt-change-the-file-name-in-the-image
