### ISSUE TITLE
Content-Types builder: Can't make components private

### ISSUE THREAD

**Issue by NGuldager** [strapi/strapi#10563]
### Describe the bug

When adding a component as a field to a collection you can't make it private.

### Steps to reproduce the behavior

1. Have a component defined in the Content-Types builder
2. Go to any collection in the Content-Types builder
2. Click on "Add another field"
3. Select "Component"
4. Select "Use existing component"
5. Select any component
6. Go to "Advanced Settings" tab
7. "Private field" is nowhere to be found

### Expected behavior

I expect to be able to set "Private field" on a component in the collection, just as I can with any relations or regular fields

### Screenshots

![image](https://user-images.githubusercontent.com/2247698/123953936-18476f80-d9a8-11eb-87ab-12c46549fe8e.png)

### System

- Node.js version: v12.22.1
- NPM version: v6.14.12
- Strapi version: v3.6.3
- Database: SQLite
- Operating system: macOS Version 11.1

### Additional context

The field is correctly hidden in both GraphQL endpoints and REST when setting `"private": true,` in the code. But any update to the collection in the Content-Types builder will clear the code change.

**Comment by soupette** [comment]
That's an option we can add.

@alexandrebodin WDYT?

**Comment by alexandrebodin** [comment]
I think we can add it yes
