### ISSUE TITLE
Translations in Arabic and French being altered

### ISSUE THREAD

**Issue by walidbillel** [strapi/strapi#10570]
### Translations in strapi being altered after database backup

after a database backup restoration all our multi-lingual content looks altered both in Arabic and French

### Steps to reproduce the behavior

After making a database backup, all the content that has been translated got messed up

### Expected behavior

Expecting to see the database I loaded in strapi

### Screenshots

![Screenshot 2021-07-01 104150](https://user-images.githubusercontent.com/35076190/124148856-10e29d80-da5e-11eb-96e8-7478798ac2d7.png)

### Code snippets

NA

### System

- Node.js version: v14.16.1
- NPM version: 6.14.4
- Strapi version: 3.6.2
- Database: Postgress Azure
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
> Database: Postgress Azure

I would suggest checking the encoding used on the database as it most likely is not something like utf8-mb4 and could likely be something like latin1

**Comment by derrickmehaffy** [comment]
No additional information from user, marking as closed.

**Comment by walidbillel** [comment]
This was not a utf issue. We had to retranslate the Arabic and French versions.

**Comment by omarkhairy21** [comment]
Hello @walidbillel  in your screenshot the data coming from the database and you just rendering it in the data table, I want to help you so I am wondering how can i repredouce the issue ?!
