### ISSUE TITLE
User Password Authentication with bcrypt.compare ALWAYS RETURNS TRUE

### ISSUE THREAD

**Issue by sbastias** [strapi/strapi#10579]
Users-Permissions plugin is using bcrypt.compare - which returns a PROMISE, not a BOOL.

An existing identifier with ANY password sent to the Auth.js authentication callback returns TRUE.

services/User.js:

![image](https://user-images.githubusercontent.com/1007243/124363633-6e1b5200-dc0a-11eb-9849-6b33861824e3.png)

Should be:
```
async validatePassword(password, hash) {
    return await bcrypt.compare(password, hash);
}
```

OR

```
validatePassword(password, hash) {
    return bcrypt.compareSync(password, hash);
}
```

**Comment by mattf96s** [comment]
You probably had extended the user-permissions plugins. Then, a newer strapi version changed the `validatePassword` function to an asynchronous function. When you upgraded strapi versions you probably didn't notice (happened to me).

**Comment by sbastias** [comment]
Oh. That's embarrassing. Sorry!
