### ISSUE TITLE
IPFS file upload

### ISSUE THREAD

**Issue by ateeqrehmani** [strapi/strapi#10586]
May i get any help regarding file upload on IPFS with strapi?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by alexbakers** [comment]
> May i get any help regarding file upload on IPFS with strapi?

Hello, @ateeqrehmani.

This is what you are looking for 👍 

https://github.com/alexbakers/strapi-provider-upload-ipfs-storage
