### ISSUE TITLE
Content-Manager cannot display the collection type when it contains a polymorphic relation

### ISSUE THREAD

**Issue by zahmedFDL** [strapi/strapi#10581]
Describe the bug
I was trying to create a model with polymorphic relation.
I have read docs - https://strapi.io/documentation/3.0.0-alpha/concepts/models.html#relations

When a model contains a polymorphic relation *, the content manager cannot display the model into the Admin UI.

Steps to reproduce the behavior

Go to Content-Type Builder
Define new model with any kind of fields, for example, Favourite
Go to created files and edit JSON schema file( favourite.settings.json)
In section, attributes add a polymorphic field
{ "kind": "collectionType", "collectionName": "navigations_items", "info": { "name": "Navigations items", "description": "" }, "options": { "increments": true, "timestamps": true, "draftAndPublish": false }, "pluginOptions": { "i18n": { "localized": true }, "content-manager": { "visible": true }, "content-type-builder": { "visible": true } }, "attributes": { "title": { "pluginOptions": { "i18n": { "localized": true } }, "type": "string", "required": true, "configurable": false }, "type": { "type": "enumeration", "enum": [ "INTERNAL", "EXTERNAL" ], "default": "INTERNAL", "configurable": false }, "path": { "type": "text", "targetField": "title", "configurable": false }, "externalPath": { "type": "text", "configurable": false }, "uiRouterKey": { "type": "string", "configurable": false }, "menuAttached": { "type": "boolean", "default": false, "configurable": false }, "order": { "type": "integer", "default": 0, "configurable": false }, "parent": { "model": "navigations-items", "columnName": "parent", "configurable": false, "default": null }, "master": { "columnName": "master", "model": "navigation", "configurable": false }, "entities": { "collection": "*", "filter": "field" } } }

Click on it inside the collection types.
Then you will get this error into the chrome javascript console:
2main.9d4912ad.chunk.js:1 TypeError: Cannot read property 'pluginOptions' of undefined at main.9d4912ad.chunk.js:1 at Array.reduce (<anonymous>) at d (main.9d4912ad.chunk.js:1) at b (main.9d4912ad.chunk.js:1) at main.9d4912ad.chunk.js:1 at c (main.9d4912ad.chunk.js:1) at Generator._invoke (main.9d4912ad.chunk.js:1) at Generator.next (main.9d4912ad.chunk.js:1) at n (main.9d4912ad.chunk.js:1) at l (main.9d4912ad.chunk.js:1)

Expected behavior
Display the model into the content manager

System

Node.js version: 12.22.2
NPM version: 6.13.13
Strapi version: 3.6.5
Database: Mysql
Operating system: macOS Big Sur

Additional context
Thanks for your help
![Screenshot 2021-07-05 at 09 34 24](https://user-images.githubusercontent.com/77128991/124435340-2f55db00-dd75-11eb-818b-9d48a250956e.png)
![Screenshot 2021-07-05 at 09 41 52](https://user-images.githubusercontent.com/77128991/124435409-3f6dba80-dd75-11eb-80fc-36b728e7fb55.png)

**Comment by derrickmehaffy** [comment]
Thank you for the report, it's a limitation we have been aware of for some time and you are correct they are not supported in the v3 and will have better support in the v4.

**Comment by soupette** [comment]
@derrickmehaffy they are not supported in the admin yes but the admin should not crash when creating a polymorphic relation with i18n enabled.

I'll try to make a PR soon so the admin does not crash.

**Comment by fchristl** [comment]
I have written a PR in #10628 that lets list and edit views work properly again, even if a model has a polymorphic relation. Hope it helps. In the mean time, you could copy `strapi-plugin-content-manager/admin/src/hooks/useFetchContentTypeLayout/utils/formatLayouts.js` as an extensions, which is what I did for our project that was impacted.

**Comment by fchristl** [comment]
Can anyone from the Strapi team comment on whether or not the PR would be considered for merging? I understand that v4 is probably taking up a lot of your capacity, just would be cool to get a hint.

**Comment by derrickmehaffy** [comment]
> Can anyone from the Strapi team comment on whether or not the PR would be considered for merging? I understand that v4 is probably taking up a lot of your capacity, just would be cool to get a hint.

I can't speak to the PR but from what I understand we should be applying at least some support for polymorphic fields into the admin with v4. I've added it to my list to ask during our internal weekly v4 sync and Q&A meetings. So if you don't hear back from me by next thursday, poke me again.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Do you have any updates on this or shall we just wait for v4 at this point?

Nothing will happen in v3 for sure, I'm not entirely sure on the support for polymorphic relations in v4 yet either. I'll bring up the question in our v4 sync tomorrow (internal meeting)

**Comment by fchristl** [comment]
I've resorted to writing my own alternative, a component that let's me choose a collection in one select field and then an entry in a second one. It's not optimal but works. If you're interested, I can see if I can share the actual code.

**Comment by davidparys** [comment]
> I've resorted to writing my own alternative that works pretty much as you describe it @davidparys, a component that let's me choose a collection in one select field and then an entry in a second one. It's not optimal but works. If you're interested, I can see if I can share the actual code. 


My use case is pretty simple : A CTA component, that would have as an href the information of a certain page, bummer part is that I would like to be able to choose from multiple collection types. The CMS prismic.io (where I'm moving my website from) has this approach and I've found that quite useful, when you link the page, the information you get is a few fields (i.e the slug field and the page locale) that would allow  to build the routing. 

@fchristl l would be definitely interested in seeing how you've managed to implement that 😊👍

**Comment by davidparys** [comment]
> > Thanks for that, that could work, but then on your front end, you have to query collection 1 to 3 and see which one is available right?
> 
> That's right. I have to send every relation through a function to extract the actual target.

@fchristl Based on your idea and what you have sent me, I managed to create a dirty plugin that would handle these relationships for me. I first define the collection I want to fetch (manually - in the attributes ideally -), then it fetches the data of that item or the collection type

https://user-images.githubusercontent.com/56082497/137500795-cc56bc57-8e62-41a1-ba02-bc432b3ba59d.mov

**Comment by fchristl** [comment]
@davidparys would you have a repo for me to check it out? This sounds like a great solution that might be super useful for our project(s). I'd be happy to work with you on getting this into a published lib.

**Comment by davidparys** [comment]
> @davidparys would you have a repo for me to check it out? This sounds like a great solution that might be super useful for our project(s). I'd be happy to work with you on getting this into a published lib.

@fchristl hey sure, you can find it [here](https://github.com/davidparys/strapi-relation-picker). It's a bit messy so far and very locked to a few settings. 

In order for it to work: types need to have the following item names: `title` and `slug`, and obviously you need to have public "read" rights for the types otherwise you will get 400's (my discord David P.#2260)

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/manage-polymorphic-relations-in-the-admin
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
