### ISSUE TITLE
 Strapi Graphql prioritizes generated resolver over custom resolver

### ISSUE THREAD

**Issue by sofyan-ahmad** [strapi/strapi#10588]
### Describe the bug

At the moment Strapi Graphql will prioritize Shadow CRUD resolver over custom resolver. 
It should've been the other way around;

### Steps to reproduce the behavior

1. Create a custom resolver as described here https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#customize-the-graphql-schema
2. Graphql will still hit generated Crud resolver

### Expected behavior

It should've been the other way around; Custom resolver should override the generated resolver

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- Strapi version: 3.6.1
- Database: postgres
- Operating system: mac/unix

**Comment by kasonde** [comment]
Hi @sofyan-ahmad, I have attempted to reproduce what you have described in this issue and I can't seem to. I've attached a repository here that shows the strapi project I created to reproduce this issue. What I did is create a "Person" content type and then customize the "people" shadow crud generated query to return nothing and it worked as expected. Could you share more context about what you did to reach this issue and how you concluded that there's in fact a problem with the order of execution within the plugin?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/8735
