### ISSUE TITLE
relation dropdown behind input field

### ISSUE THREAD

**Issue by omrirz** [strapi/strapi#10583]
### Describe the bug

Dropdown is behind input field.

### Steps to reproduce the behavior

1. Create a relation inside a component inside a content type.
2. Click the relation to open its dropdown.
3. If there is an input field behind that dropdown its z-index it will actually be in front of the dropdown.

### Expected behavior

The dropdown should be in front of the input behind it.

https://user-images.githubusercontent.com/13974474/124507723-1716a800-ddd7-11eb-8be7-2c2930e5c841.mov

### Screenshots

There is a video attached showing the issue.

### Code snippets

N/A

### System

- Node.js version: v14
- NPM version: yarn 1.22.10
- Strapi version: 3.6.5
- Database: mongodb
- Operating system: macOS

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
fixed in v4
