### ISSUE TITLE
Admin panel UI crashed after installing GraphQL 

### ISSUE THREAD

**Issue by aliskhanoff** [strapi/strapi#10596]
- Node.js version: 14.16.1
- NPM version: 6.14.12
- Yarn version: 1.22.5
- Strapi version: 3.2.5
- Database: sqlite or mongo
- Operating system: Windows 10 
- strapi-plugin-graphql version: 3.2.5

package.json
{
  "name": "backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
     "strapi": "3.6.5",
    "strapi-admin": "3.6.5",
    "strapi-utils": "3.6.5",
    "strapi-plugin-content-type-builder": "3.6.5",
    "strapi-plugin-content-manager": "3.6.5",
    "strapi-plugin-users-permissions": "3.6.5",
    "strapi-plugin-email": "3.6.5",
    "strapi-plugin-upload": "3.6.5",
    "strapi-plugin-i18n": "3.6.5",
    "strapi-connector-bookshelf": "3.6.5",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "08e608e2-4395-4c27-a752-f35ed512a468"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

Hello 🙋‍♂️ Strapi developers! Maybe somebody already has posted about this problem, but i can't find any information.

After installing GraphQL module an admin panel is showing with artefacts. I have faced the same problem before...

> I updated my Strapi version from 3.2.5 -> 3.6.5. Nothing changed.

![Screenshot Users page](https://user-images.githubusercontent.com/41637477/125333329-68301a00-e34a-11eb-8e27-5d204757ae88.png)
![Screenshot Content Type builder](https://user-images.githubusercontent.com/41637477/125334384-9bbf7400-e34b-11eb-8bb5-9437be5d8628.png)

**Comment by aliskhanoff** [comment]
Screenshot
![problem screenshot](https://user-images.githubusercontent.com/41637477/125193127-2f5d4b80-e24b-11eb-842a-25886ed34857.png)

**Comment by LucaNerlich** [comment]
please remove .cache and build folder, run the build again and restart strapi. Should work afterwards.

**Comment by kasonde** [comment]
Hi @LucaNerlich please follow the issue template when you submit new issues. The information requested will save some time during debugging as we have a good amount of information to understand your issue. 

I notice that you have Strapi version 3.2.5 installed. Please share a screenshot/copy and paste your package.json. It may have happened that you're installing an updated version of the plugin for an outdated version of Strapi (currently v3.6.5). Your screenshot may help to confirm/rule this out as a possibility.

**Comment by aliskhanoff** [comment]
Hi @LucaNerlich 

I am using `yarn build --clean`
This command is doing the same thing

**Comment by kasonde** [comment]
@aliskhanoff I edited my previous message with some recommendations and a request to share your package.json file

**Comment by kasonde** [comment]
> Hi @aliskhanoff please follow the issue template when you submit new issues. The information requested will save some time during debugging as we have a good amount of information to understand your issue.
> 
> I notice that you have Strapi version 3.2.5 installed. Please share a screenshot/copy and paste your package.json. It may have happened that you're installing an updated version of the plugin for an outdated version of Strapi (currently v3.6.5). Your screenshot may help to confirm/rule this out as a possibility.

**Comment by aliskhanoff** [comment]
I edited my essue text, so the package.json file is all from quickstart template

**Comment by aliskhanoff** [comment]
I updated my strapi from 3.2.5 -> 3.6.5. Nothing changed.

**Comment by aliskhanoff** [comment]
I solved the problem. If you faced the same problem, instead of using yarn package manager, you have to use npm, but is broke my yarn workspaces configuration.

Thanks you @kasonde for replys!

Thanks Strapi ❤ developers

**Comment by kasonde** [comment]
Hi thanks for letting me know. So we actually do not support yarn workspaces yet in Strapi so it is recommended to either downgrade to v1 or use npm like you suggest.
