### ISSUE TITLE
Unique Fields Should Not Be Localized

### ISSUE THREAD

**Issue by cawoodm** [strapi/strapi#10599]
We are unable to create a unique field which is the same in all languages.
Firstly, the UID type does not let you switch off internationalization
Secondly, when we make a text/string field we cannot set it to be unique if we disable internationalization.
This makes it impossible to reference a content type externally because there is no way to uniquely identify it.
It seems Strapi doesn't understand that a UID (Unique Id) should be unique.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
