### ISSUE TITLE
Allow a twitter user to login even if they only have their phone number user-permissions

### ISSUE THREAD

**Issue by tttp** [strapi/strapi#10604]
## Bug report
the oauth user permission assumes that twitter will always returns an email. 
However, it is possible to create an account on twitter by only providing a phone number and users expect to be able to login on strapi front-end.

### Describe the bug

As part of the registration process using twitter, strapi calls twitter api account/verify_credentials.
in case of a "mobile" twitter user, this api returns an empty email (because twitter doesn't have any email for that account, just a phone number)

https://github.com/strapi/strapi/blob/df832fafd1705266d65bae22d8dd3a0fe37964cf/packages/strapi-plugin-users-permissions/services/Providers.js#L310

### Expected behavior

Being able to log-in for every twitter user.
I would expect to create a "unique but placeholder" email (as the rest of the strapi user expects the email to exist), like "screename@twitter.localhost" and let the user login.

Admins will be able to decide if they want to grant further access to the user based on the twitter profile only, without needing the email

### Code snippets

the workaround I found was (on /strapi-plugin-users-permissions/services/Providers.js L 310)

             email: body.email || body.screen_name +"@twitter.localhost",

### Additional context

It might be interesting to be able to use more information and store them to the user account, either generic ones like the profile picture as fetched in the social media, or (in case of twitter), if the account is verified or the number of followers

I can submit a PR if you want

**Comment by derrickmehaffy** [comment]
@strapi/maintainers / @JabStrapi would it better to keep this as a user customization or try to implement something natively?

@tttp it's unlikely we would add specific fields for specific providers (like twitter followers or profile pictures).

**Comment by derrickmehaffy** [comment]
This is likely something we won't implement, if you would like to post this on our Feedback / Feature request page here, please feel free.
