### ISSUE TITLE
Schema hasn't been registered for model "AdminUser"

### ISSUE THREAD

**Issue by cipiasentini** [strapi/strapi#10607]
## Bug report

error MissingSchemaError: Schema hasn't been registered for model "AdminUser".

### Describe the bug

I have two strapi api that are sharing a common database connection. Two content types models are identical in both apis, but one uses this connection I am mentioning. When creating a new entry using the admin panel for that content type (no matter which api is used) I get this error `error MissingSchemaError: Schema hasn't been registered for model "AdminUser".` 
I've already seen other issues that this is because of 'created_by' and 'updated_by' fields and that the 'solution' was to hide them using `"privateAttributes": ["created_by", "updated_by"]` on the models options (and/or `"populateCreatorFields": true` as well) but did not work at all for me (tried including it on both apis models separately and together).

Note that if I create the entries via api or I remove from the database those two columns, the error disappears (I can do the latter cause I'm using mongodb).

### Steps to reproduce the behavior

1. Have two strapi apis set up
2. On one create a content type and on the other replicate that content type but add a connection to the first api
3. Add an entry using the admin panel for the content type
4. Get the error displayed (every time you perform a find/findOne or open it via admin panel) on the api that's using the content type with the connection (the main one doesn't show this issue)

### System

- Node.js version: v12.20.1
- NPM version: 6.14.10
- Strapi version: v3.6.3
- Database: mongodb
- Operating system: linux

### Additional context

The only different thing is that the main api was started using strapi v3.6.3 and the other one (the one that has the connection to the other's database on the content type) was upgraded from v3.0.0 beta20+ to v3.6.3 (all steps on migration guides were applied)

**Comment by derrickmehaffy** [comment]
> Strapi version: v3.6.3

Can you please test with v3.6.5 also have you done any extensions to the plugins, admin panel, or any community packages?

**Comment by cipiasentini** [comment]
I tried updating to the latest version (v3.6.5) the secondary api (the one that has the connection to the other and its reporting the issue) but same thing happened. Should I be updating both? Was some work done on this matter on these two new versions? (I am on v3.6.3)
I have added to the usser-permissions extension a new field (a relation to another content type, but is not related at all with the one I'm querying for). No community packages, and no modifications to the admin panel.

**Comment by derrickmehaffy** [comment]
The environment you are trying to construct here (as I assume the two projects aren't the same model structure) isn't directly one we support, ideally those two applications should each have their own database and it's quite possible they are conflicting with each other (especially since with each version we have some automatic migration scripts that can be run).

**Comment by cipiasentini** [comment]
The two content types are identical (same fields created). What would be the purpose of connection then if I can't get the data from another database?

**Comment by derrickmehaffy** [comment]
> The two content types are identical (same fields created in content type creator from dashboard). What would be the purpose of connection then if I can't get the data from another database?

We are actually removing multi-database support in the v4, it's a legacy feature that we don't really have solid support for.

**Comment by cipiasentini** [comment]
> > The two content types are identical (same fields created in content type creator from dashboard). What would be the purpose of connection then if I can't get the data from another database?
> 
> We are actually removing multi-database support in the v4, it's a legacy feature that we don't really have solid support for.

wow that's really unfortunate...

**Comment by derrickmehaffy** [comment]
It was a legacy feature that was never properly implemented and the ORM we use doesn't have many of the required functions we need to properly support multi-database (mainly relations between databaes).

I'm going to set this as closed since it's not something we will fix.
