### ISSUE TITLE
reinstall strapi and now don't let me  make request : Auth.form.error.email.provide

### ISSUE THREAD

**Issue by F-Y-M** [strapi/strapi#10616]
hi everybody, when i unstall strapi using the nuxt.js e-commerce template, have a problem making a custom controller trying the example that "alex the entreprenerd" (https://www.youtube.com/watch?v=g2KwizpxxeE) make. when make a request the server doesn't send me what i want and in the console shows 
**warn The value of field: 'id', in your where filter, is undefined.**
so i decide to reinstall all strapi (cause i seek for 2 weeks) here, in stacks / overflow / overrun, etc, reddit, facebook, and more... and nothig so i decide to reinstall strapi. ( i'm using postman ofr check the api) and now when i try to "login" from postman to strapi. send me the 
**Auth.form.error.email.provide** i thought that could be a wrong email or password, but not.
the permissions is fine all is public. the strapi service is runing normally

i'm using 

strapi version : v3.6.5
node version : 12.16.2
npm versioin : 7.20.0
OS : linux ubuntu
host : aws (pay cause strapi need more memory)
database: MYSQL (the db was empty before strapi install)

thanks for ur help and for strapi

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
