### ISSUE TITLE
GraphQL query error: "TypeError: Cannot read property 'primaryKey' of undefined"

### ISSUE THREAD

**Issue by normanzb** [strapi/strapi#1061]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: mongodb
- **Operating system**: macos 10.13.1

**What is the current behavior?**
Error thrown after sending graphql query to custom content type that has a manyToMany relation to user type.

**Steps to reproduce the problem**
1. Create a "custom" content-type with manyToMany relation to user type.
2. Create a new user.
3. Add newly created user to be associated with content-type created in step 1.
4. Send a graph ql to query custom content-type with "users" as its subfields. 

**What is the expected behavior?**
User list returned without error

**Suggested solutions**
looks like below line need to return `strapi.plugins[association.plugin].models[params.model]` as last resort:

https://github.com/strapi/strapi/blob/f91be5ce63837504cbe25aac798301e9b33f743e/packages/strapi-plugin-graphql/services/GraphQL.js#L553

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @normanzb can you update your issue and follow the issue template please. We will not work on your issue until it's done.
Thank you.

**Comment by normanzb** [comment]
updated

**Comment by lauriejim** [comment]
@normanzb Can you try with the last version of Strapi please.

**Comment by normanzb** [comment]
tested with 3.0.0-alpha.12.1.3, issue still exist

**Comment by Aurelsicoko** [comment]
@normanzb Thank you for the details, it will help us to fix it 👍

**Comment by jamesscholeyweb** [comment]
I am also experiencing this issue with nested queries:

```
{
  posts {
    Title
    Content
    Author {
      username
    }
  }
}
```

Correctly returns

```
{
  "data": {
    "posts": [
      {
        "Title": "This is a post",
        "Content": "This is some awesome post content!",
        "Author": {
          "username": "James Scholey"
        }
      },
      {
        "Title": "This is another post",
        "Content": "Content here!",
        "Author": {
          "username": "James Scholey"
        }
      }
    ]
  }
}
```

However if I nest a query for all posts of an author null is returned on the posts

```
{
  posts {
    Title
    Content
    Author {
      username
      posts {
        Title
        Content
      }
    }
  }
}
```

Returns 

```
{
  "data": {
    "posts": [
      {
        "Title": "This is a post",
        "Content": "This is some awesome post content!",
        "Author": {
          "username": "James Scholey",
          "posts": null
        }
      },
      {
        "Title": "This is another post",
        "Content": "Content here!",
        "Author": {
          "username": "James Scholey",
          "posts": null
        }
      }
    ]
  },
  "errors": [
    {
      "message": "Cannot read property 'primaryKey' of undefined",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "posts",
        0,
        "Author",
        "posts"
      ]
    },
    {
      "message": "Cannot read property 'primaryKey' of undefined",
      "locations": [
        {
          "line": 7,
          "column": 7
        }
      ],
      "path": [
        "posts",
        1,
        "Author",
        "posts"
      ]
    }
  ]
}
```

**Comment by Aurelsicoko** [comment]
@kamalbennani Thank you for trying to fix the issue, I really appreciate 👍 

You can open a PR with your fix and we'll take a look. It seems nice!
