### ISSUE TITLE
Unable to create project in arm64 machines due to Sharp installation error

### ISSUE THREAD

**Issue by ganeshkbhat** [strapi/strapi#10618]
## Bug report
Sharp installation error in ARM64 Debian 10

`npm ERR! sharp@0.28.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`

### Describe the bug
Errors out using:

```
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
sharp: Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.10.6
../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [sharp.target.mk:137: Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/admin/project/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.19.0-17-arm64
gyp ERR! command "/home/admin/project/nodejs/bin/node" "/home/admin/project/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/admin/project/workspace/sample/dev/node_modules/sharp
gyp ERR! node -v v14.17.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.28.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.28.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Steps to reproduce the behavior
Run `npx create-strapi-app dev next-ecommerce` in Debian 10 Arm64 machine

OR 
`docker-compose up -d` for `mongodb` or `mysql` docker-compose

[https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html#creating-a-strapi-project](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html#creating-a-strapi-project)

### Expected behavior
Install cleanly and install sharp in either npx or docker in Arm64 debian

A clear and concise description of what you expected to happen:

`Install cleanly and install sharp in either npx or docker in Arm64 debian`

### Screenshots
![IMG20210719095736](https://user-images.githubusercontent.com/3424344/126103040-9bb51761-68ce-4ae5-aa80-fb603031f5a7.jpg)
![IMG20210719095724](https://user-images.githubusercontent.com/3424344/126103049-d4c8c90c-1b4b-4830-9a5c-36dde6e805f1.jpg)

### Code snippets
NA

### System

- Node.js version:  V14.17.2 latest
- NPM version: V6.14.13
- Strapi version: 3.6.5
- Database: Mysql 8 /MongoDB 
- Operating system: Linux Debian 10 ARM64 Machine

### Additional context

NA

**Comment by derrickmehaffy** [comment]
Not a Strapi issue, see the error message:

> sharp: Installation error: Use with glibc 2.28 requires manual installation of libvips >= 8.10.6 ../src/common.cc:24:10: fatal error: vips/vips8: No such file or directory

Please see https://github.com/libvips/libvips
