### ISSUE TITLE
Delete config in routes inside a plugin breaks users-permissions role in admin panel

### ISSUE THREAD

**Issue by quentindlf** [strapi/strapi#10613]
### Describe the bug

Hello everyone.
Delete **config** inside **routes.json** inside a **plugin** breaks the access to the roles inside users-permissions. Seems the issue doesn't happen if the collection is in /api. 
Thank you.

`      "config": {
        "policies": []
      }`

### Steps to reproduce the behavior

1. Generate a plugin `strapi generate:plugin customPlugin`
2. Inside the plugin > routes.json, remove : `"config": {
        "policies": []
      }`
3. Access a role inside users-permissions. [/admin/settings/users-permissions/roles/1](/admin/settings/users-permissions/roles/1)
4. Error `Error: [React Intl] An `id` must be provided to format a message.` . The get on /routes provides a 400 Bad Request - {`Id : Not found`}

### Expected behavior

Access should be ok to the roles inside users-permissions admin panel.
Especially in the doc saying : [https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#routing](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#routing)

> TIP
You can exclude the entire config object if you do not want the route to be checked by the Users & Permissions plugin.
#

### System

Using Docker
- Node.js version: v12.20.1
- NPM version: 6
- Strapi version: 3.6.5
- Database: Postgres

**Comment by ErikMayrhofer** [comment]
Thanks for having filed this bug already, that soothes my annoyed mind. I just spent over an hour chasing it :(

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
