### ISSUE TITLE
Incorrect error if you try to create a user with already existing username

### ISSUE THREAD

**Issue by HristiyanEvolution** [strapi/strapi#10612]
### Describe the bug

If you try to create a user with existing username, but unique email the following error will display:
```
"messages": [
                {
                    "id": "Auth.form.error.email.taken",
                    "message": "Email already taken"
                }
```

### Steps to reproduce the behavior

1. Send a POST request to Postman (http://localhost:1337/auth/local/register) that contains unique email, but existing username
2. The response will say Email already taken

### Expected behavior

The response should say Username already taken

### Screenshots

Request & response: https://prnt.sc/1bsqcxe
Console error: https://prnt.sc/1bsqi9s
Users: https://prnt.sc/1bsqp11

### System

- Node.js version: v12.16.3
- Strapi version: v3.6.5
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9948
