### ISSUE TITLE
404 Error when deploying on firebase hosting

### ISSUE THREAD

**Issue by F-Y-E-F** [strapi/strapi#10617]
Hi!, I use firebase hosting to my react app with strapi. When i type myurl.com/admin 404 error page not found appers.

I did 
`npm run build`
then
`firebase deploy`

There's my server.js config file

`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'here's my secret'),
    },
  },
});
`

.env 
`NODE_ENV=production npm start`

Can you help me with that bug?

**Comment by derrickmehaffy** [comment]
We do not support firebase hosting as a platform for deploying.

For community questions, please use our forum: https://forum.strapi.io
