### ISSUE TITLE
"Add New Content Type" modal dialog displayed bottom aligned

### ISSUE THREAD

**Issue by kadaan** [strapi/strapi#1062]
### Configuration
| Node Version  | NPM Version |     Strapi Version    | Database |           OS                     | Resolution | Browser | 
| ------------- | -------------- | ------------------ | --------- | --------------------- | ----------- | -----| 
| v9.11.1            | 5.6.0                | 3.0.0-alpha.12.0.1  | Mongo     | Os X 10.13.3 (17D47) | 2880 x 1800 | Chrome  65.0.3325.181 |

### Current behavior
The "Add New Content Type" modal dialog is displayed at the bottom of the window and causes the content pane to expand, displaying the scroll bar.

### Steps to reproduce the problem
With a full screen browser, open the "Add New Content Type" modal dialog.  Notice that the dialog is bottom aligned and the page is now scrollable.

### Expected behavior
The "Add New Content Type" modal dialog should be vertically and horizontally centered on the page.

---

- [X] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @kadaan, can you provide a screenshot please.

**Comment by kadaan** [comment]
Crud.  Totally took the screenshot and forgot to attach it.  Here you go:

<img width="1440" alt="screen shot 2018-04-29 at 11 08 50 am" src="https://user-images.githubusercontent.com/1904898/39419270-ee53a5c4-4c13-11e8-97db-d6186859839b.png">

**Comment by lauriejim** [comment]
@kadaan thank you for this issue. We will not work on this issue cause it’s not a priority for us and we miss time to did it (I'm sure you can understand we work on more important things for you).
Feel free to submit a PR. Will appreciate your contribution on Strapi!
Check the contributing guide to start: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by kadaan** [comment]
@lauriejim No worries.  Am I correct in assuming that the issue will remain open until fixed?

**Comment by lauriejim** [comment]
Yes. we need the community help to fix this kind of issues.

**Comment by kadaan** [comment]
@lauriejim Seems like it was just addition of a huge margin-top to the bootstrap-overrides.scss that was causing the issue.  Any idea why that existed?
