### ISSUE TITLE
Project version missmatch after migrating to 3.6.5

### ISSUE THREAD

**Issue by TimoVFX** [strapi/strapi#10639]
### Describe the bug

After migrating from 3.5.3 to 3.6.5 following error appears in the console

```
It seems that the built version 3.6.5 is different than your project's one (3.5.3)
Please delete your `.cache` and `build` folders and restart your app
```

even after deleting `.cache` and `build` folder and rebuilding the app

As seen in the Screenshot i still get shown the old version in the settings. But in the sidebar on the lower left i get the new version displayed.

### Steps to reproduce the behavior

In an existing Project follow the [Update Strapi Guide](https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html) 

### Expected behavior

Version should be updated after rebuild

### Screenshots

![strapi-version-missmatch](https://user-images.githubusercontent.com/27963436/126633594-a03a8122-7d94-4e88-a003-ba6ad2fa0643.JPG)

### Code Snippets
package.json:
```
{
  "name": "app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "0.21.18",
    "mysql": "2.18.1",
    "strapi": "3.6.5",
    "strapi-admin": "3.6.5",
    "strapi-connector-bookshelf": "3.6.5",
    "strapi-plugin-content-manager": "3.6.5",
    "strapi-plugin-content-type-builder": "3.6.5",
    "strapi-plugin-email": "3.6.5",
    "strapi-plugin-upload": "3.6.5",
    "strapi-plugin-users-permissions": "3.6.5",
    "strapi-provider-upload-aws-s3": "^3.6.3",
    "strapi-utils": "3.6.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "sudo"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}
```

### System

- Node.js version: v12.18.3
- NPM version: 6.14.6 
- Yarn version: 1.22.10
- Strapi version: 3.5.3/3.6.5
- Database: MySQL
- Operating system: WSL

### Additional context

I tried the usual Stuff:
- deleting node_modules
- rebuilding with --clean
- whole update process once with yarn and npm

Any help on this would be much appreciated.

**Comment by derrickmehaffy** [comment]
Please try deleting your package-lock.json and/or yarn.lock in addition to the node_modules as it appears you have some very agressive caching or your node/yarn is configured to strictly follow the lock files.
