### ISSUE TITLE
Populate deleted components and repeatable components

### ISSUE THREAD

**Issue by MotaZor94** [strapi/strapi#10633]
## Hello everyone,

# 1.
I have a  **LANDING PAGE** model.

![Screen Shot 2021-07-21 at 15 10 46](https://user-images.githubusercontent.com/45624002/126494053-1b63cf54-5d1c-4ce6-9c36-947c8ff91b5d.png)

# 2.
As you can see this model has _relation_ with **PROGRAMMES**.

This **PROGRAMME** _relation_ has few components and repeatable components inside of it which work out of the box.

The problem arose when I realized that the nested relations inside of programmes don't show up, so I followed @derrickmehaffy solution from [here](https://github.com/strapi/strapi/issues/9078)

As you can see below on the image, this fixed the deeply nested relations.
![Screen Shot 2021-07-21 at 15 16 24](https://user-images.githubusercontent.com/45624002/126494857-4e22e1c0-7e66-4833-8bca-2b7f9c59acf6.png)

This was the code that I used to fix this:

``` async findOne(ctx) {
    let populate = [
      "programmes",
      "programmes.locations",
      "programmes.certification",
      "programmes.study_modes",
      "programmes.degree_level",
      "programmes.verticals",
    ];
    let entity = await strapi.services["landing-page"].findOne(
      ctx.query,
      populate
    );
    let data = sanitizeEntity(entity, { model: strapi.models["landing-page"] });
    return data;
  },
```

## PERFECT! 

# 3.

## BUT THERE IS A CATCH
Now, where the issue happened? When I used the populate method all of the components and repeatable components that were there before - inside of the relation with the programme, simply disappeared from the object.

As you can see below are the components that vanished after **populate**.

![Screen Shot 2021-07-21 at 15 10 46](https://user-images.githubusercontent.com/45624002/126495989-38091c18-2792-4468-b169-5676a993c61c.png)

# 4.
I have tried to do something like this:

``` async findOne(ctx) {
    let populate = [
      "programmes",
      "programmes.locations",
      "programmes.certification",
      "programmes.study_modes",
      "programmes.degree_level",
      "programmes.verticals",
      "programmes.pSpecialisations",
      "programmes.ctaButton",
      "programmes.overviewSection",
    ];
    let entity = await strapi.services["landing-page"].findOne(
      ctx.query,
      populate
    );
    let data = sanitizeEntity(entity, { model: strapi.models["landing-page"] });
    return data;
  },
```

But it didn't work, since as from what I understood in @derrickmehaffy comment is that populate is only working for relational fields.

Does anyone have an idea how to fix this?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
