### ISSUE TITLE
v1.6.4 why not enable graphql post by default?

### ISSUE THREAD

**Issue by normanzb** [strapi/strapi#1063]
**What is the expected behavior?**

on 1.6.4, post to /graphql doesn't work, because of below line: 
https://github.com/strapi/strapi/blob/1.6.4/lib/configuration/hooks/router/index.js#L111
Looks like `get` should be replaced with `all` instead?

Also it seems apollo by default using POST for sending request no matter it is read only or not, fixing graphql to `get` is kind make it difficult to integrate with popular client sides, any special reason?

- [x ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @normanzb, we stop to support `1.6.4` version and now we fully work on v3.
Mutation on in a specific branch of the module https://github.com/strapi/waterline-graphql/tree/improve/mutations
