### ISSUE TITLE
Getting issue can not read property of object of undefined

### ISSUE THREAD

**Issue by sanjeetCoder** [strapi/strapi#10647]
Hi,

While calling Strapi API in our frontend react application, I am getting error can not read property of object of undefined when I use map function to iterate over nested object.

When I try to access image url or any property like, hash, ext, it gives error 

Our code is something like :
===============================================
  {bannerData.map((data, index) => {
          console.log("Image URL ", data.image[0].formats.large.url)
            return (
===============================================
Our Strapi JSON is 

"homeBanner": [
        {
            "id": 1,
            "title": "home_banner_ dummies_1",
            "description": "banner_dummy_description_ banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_banner_dummy_description_",
            "image": [
                {
                    "id": 7,
                    "name": "abc.jpg",
                    "alternativeText": "",
                    "caption": "",
                    "width": 1200,
                    "height": 801,
                    "formats": {
                        "large": {
                            "ext": ".jpg",
                            "url": "",
                            "hash": "",
                            "mime": "image/jpeg",
                            "name": ".jpg",
                            "path": null,
                            "size": 95.71,
                            "width": 1000,
                            "height": 668
                        **},**

"

Getting Console error 
==================================================================
homeBanner.js:62 Uncaught (in promise) TypeError: Cannot read property 'url' of undefined
    at eval (homeBanner.js:62)
    at Array.map (<anonymous>)
    at HomeBanner (homeBanner.js:61)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23959)

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
