### ISSUE TITLE
Date input does not respect `required` validation rule

### ISSUE THREAD

**Issue by piersroberts** [strapi/strapi#10643]
## Bug report

Setting a component `date` input to `required` does not get picked up by validation when saving a record in the Strapi admin UI

### Steps to reproduce the behaviour

1. Create a date input and set required to true
2. Create or edit a record that includes a `required` date filed
3. Leave the date field empty
4. Hit save
5. Record saves successfully

### Expected behaviour

We would expect validation to fail and for a toast notification to indicate a failure and for the date field to be highlighted
We would not expect the record to save successfully.

### Code snippets

```
{
  "collectionName": "components_resident_care_assessments",
  "info": {
    "name": "assessment",
    "icon": "asterisk",
    "description": ""
  },
  "options": {},
  "attributes": {
    "status": {
      "type": "enumeration",
      "enum": [
        "RED",
        "AMBER",
        "GREEN"
      ],
      "required": true
    },
    "notes": {
      "type": "text"
    },
    "assessment_date": {
      "type": "date",
      "required": true
    }
  }
}
```

### System

- Node.js version: v14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.5
- Database: MySQL
- Operating system: Alpine Linux

**Comment by derrickmehaffy** [comment]
Unable to reproduce on v3.6.5: 
![image](https://user-images.githubusercontent.com/8593673/126713372-da84a27a-ae1a-413b-8f88-33a36fd5d4d2.png)

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
