### ISSUE TITLE
Lost relate data from image after update document

### ISSUE THREAD

**Issue by lags** [strapi/strapi#1064]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 6.0.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: MongoDB v3.6.4
- **Operating system**: Ubuntu 16.04.4 LTS 64bit

**What is the current behavior?**
I have create a new api called: 'shops' and I put media content type with allow multiple file, any information field string (ex. name, description, etc...) and relation with users "Shops has and belongs to many Users". If I create a new shop with full information and image, all is ok. (check into database field related of uploaded file and also is populate with correct data). If I would like edit for change some data, after save, the relate information of image file is lost.

**Steps to reproduce the problem**
Create a new api called shop with almost media content with allow multiple file and some data.
Try to create a new shop. Save it. Reopen change some data. Save it.

**What is the expected behavior?**
After edit the shop, the related data inside file still here

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/issues/1048
