### ISSUE TITLE
Cannot edit a content type through conten-types builder. I receive 'An error occurred.'

### ISSUE THREAD

**Issue by jordankittle** [strapi/strapi#10645]
### Describe the bug

When I try to edit a content field through the content-types builder, it just says "An error occurred when I click save. 

### Steps to reproduce the behavior

1. Go to 'Content-types builder'
2. Click on 'Content type'
3. Click the field you are trying to edit
4. Edit the data and click finish
5. Click save

### Expected behavior

The content type is updated with the new edits.

### Code snippets

`PUT http://localhost:1337/content-type-builder/content-types/application::chronicles.chronicles 400 (Bad Request)`

### System

- Node.js version: 4.16.1 -->
- NPM version: 6.14.12
- Strapi version: 3.6.2
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.6.2

Can you please try on the latest release (v3.6.5) but I'm unable to reproduce the issue with the information provided.

**Comment by jordankittle** [comment]
Thank you derrick. I just upgraded to 3.6.5 and the error persists. Is there any information I can get you that would help solve the problem?  This seems to be a very core function that isn't working.

**Comment by jordankittle** [comment]
I have tested it on a brand new Strapi project that I am working on as well and I get the same error. 
1.) I create an enumeration content-type with two options:  Stage and Production. I click finish and save. 
I try to change Stage and Production to stage and production.   Change capitals to lowercase. Then I click finish and save and I get the error.

**Comment by jordankittle** [comment]
I have found out a little bit more about the problem.  With enumeration fields:
`Stage
Production
Test`
I can change the 2nd or 3rd field, but I cannot change the first.   If I change test to Changed it works. If I change production to Changed it works. If I change stage to Changed it does not work.

**Comment by jordankittle** [comment]
I have learned more about the problem. Please set advanced settings to required and set the default value. The error occurs when trying to edit the default value.

**Comment by jordankittle** [comment]
Were you abele to reproduce when selecting required and trying to edit the default value?

**Comment by derrickmehaffy** [comment]
I was on vacation last week @jordankittle but I'll try to reproduce it this week

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
