### ISSUE TITLE
strapi don't working exacly when use ckeditor

### ISSUE THREAD

**Issue by nvthuong1996** [strapi/strapi#10650]
### Describe the bug

For some reason i have to use ckeditor instead default editor of strapi.

I follow tutorial at: https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi.

Normal ckeditor working exacly. But if entity has relation, example: category (1 - n) Post. When i save 1 record Post and refresh page => old content don't show in ckeditor ( ckeditor don't show content in database - binding data error ).

If i remove Category out Post view, CKeditor will working.

**Comment by Mites88** [comment]
https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5

This library works great and it's a simple `npm install`. No need to integrate manually if you don't have to.

**Comment by nvthuong1996** [comment]
Thank you
