### ISSUE TITLE
DRAFT/PUBLISH: unexpected side effect in content type when deleting picture from media lib

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#10653]
### Describe the bug

Backend users can delete images from media library page even if it's attached to an entry on which it's mandatory.

### Steps to reproduce the behavior

1. Create a content type with a picture field, required
![image](https://user-images.githubusercontent.com/21955112/127000696-3ca2ae16-5237-4ce7-bcb7-cee1da45ee0a.png)

2. Add a new entity of this content type, with a picture
3. Save it
4. Publish it
![image](https://user-images.githubusercontent.com/21955112/127000895-191f5f17-7a78-4605-a378-30ae78f6e7e7.png)

5. Go to media lib page
6. Find the picture previously uploaded and delete it from there
7. Go back to you entities and open the one created in step 2
8. The entity has no picture and is published, which should theorically not be possible in a standard workflow.
![image](https://user-images.githubusercontent.com/21955112/127000976-9dc4d19a-6865-4da3-ae94-8bae55267a8f.png)

### Expected behavior

A published entity with a mandatory picture should not stay published when you delete picture from media library.

### Screenshots

N/A

### Code snippets

See repro repository: https://github.com/8byr0/strapi-repro-image-sideeffect
(simple strapi app with an Entity content type that only has a picture field. )

### System

- Node.js version: 12.22.1
- NPM version: 6.14.12
- Strapi version: 3.6.5
- Database: sqlite
- Operating system: OSX Catalina

### Additional context

I only took the use case of a content type with draft/publish enabled but the problem is the same for a content type without it, this case is not handled and leads to a broken situation where the API lies: it says the picture is mandatory (i.e. always present) but there's a case where it's not. 
Should the media lib plugin prevent deletion of pictures link to an entity where it's required?

**Comment by daniel-julius-sam** [comment]
Shouldn't the expected behaviour be that the picture is prevented from being deleted?

**Comment by derrickmehaffy** [comment]
I think this is fixed in v4 but if not it we should create a different feature request for cascade delete options for foreign keys.
