### ISSUE TITLE
Confirmation email without code, just link URL

### ISSUE THREAD

**Issue by ar7ar** [strapi/strapi#10668]
Hi!

1- How do I get the user registration confirmation email to send a 6-number code and not a big link?

2- How do I get this confirmation number sent to the new user’s email, to be valid only for 10 minutes?

Thanks

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
