### ISSUE TITLE
Code editor overlap select box

### ISSUE THREAD

**Issue by hckhanh** [strapi/strapi#10666]
I see the UI bug on the CMS

![image](https://user-images.githubusercontent.com/6380436/127588405-60bbad9b-12f8-4190-9368-dfdc9e81ffd9.png)

As you can see, the Code editor is overlap the Select box

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
