### ISSUE TITLE
Can't save new content type

### ISSUE THREAD

**Issue by jezperp** [strapi/strapi#1066]
First of all I'm sorry if this issue already exists, I have searched for it but can't find it.

**Issue:**
I've set up my environment using your Getting Started Guide. I can get started as in logging in to the Admin panel, but it seems I can't create a new Content Type. I just get an error (see image).
I've also set up my table in my database with id and name as columns. The error type is 500 with the route being _http://localhost:1337/content-type-builder/models/_.

**Image:**
![screen shot 2018-04-30 at 10 42 49](https://user-images.githubusercontent.com/1816856/39420303-33cdd5d4-4c64-11e8-9127-d04573cff9a8.png)

**Informations**
- **Node.js version**: v10.0.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: MySQL
- **Operating system**: macOS High Sierra (10.13.3)

**What is the current behavior?**
Getting error 500.

**What is the expected behavior?**
Be able to create new Content Type.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by notedit** [comment]
yes,  same  error

**Comment by jezperp** [comment]
Apparently you get this error if you've already generated an API with CLI, so to fix this I deleted my generated API from the API-folder and clicked save.
