### ISSUE TITLE
Components duplicated when inserted in Dynamic Zone via rest API or strapi.query()

### ISSUE THREAD

**Issue by ermat77** [strapi/strapi#10665]
### Describe the bug

Components in dynamic zone randomly duplicated when creating 22 of them via REST API or strapi.query()

### Steps to reproduce the behavior

1. Create a collection with a dynamic zone that contains 40 different components
2. Use the REST API to create a tuple that contains 22 of the 40 possible components 
3. See error as some of the unique 22 components are randomly duplicated 

### Expected behavior

I expect to see a tuple with the exact same number of components that I send via REST API

#### Collection
![collection_components](https://user-images.githubusercontent.com/34575489/128141214-8ad09f55-8c28-4cfd-8298-9c3a7c7b7187.PNG)

#### Data sent
![log_data_sent](https://user-images.githubusercontent.com/34575489/128141220-8db10931-16d3-4916-aea6-3f50bcada8eb.PNG)

#### Data sent -> Composant structure
![log_sent_composant_structure](https://user-images.githubusercontent.com/34575489/128141221-6f184eb2-dcf7-45c2-8edb-c94978403ea2.PNG)

#### API Response
![log_api_response](https://user-images.githubusercontent.com/34575489/128141217-486ba634-c14e-45f6-b6e1-9de4c768f667.PNG)

### Code snippets

Overrode my create controller : 

```
const data = ctx.request.body
console.log(data.composants.length) ---------> "22"
const result = await strapi.query('modele-de-materiel').create(data)
console.log(result.composants.length) ----------> "27" /* The attempt before was 31 and after 33... it is really random */
```

### System

- Node.js version: 14.17.0
- NPM version: 6.14.13
- Strapi version: 3.6.3
- Database: MySQL 8.0.22
- Operating system: Windows

### Additional context

I have a collection (let's say computer) which has a dynamic zone with more or less 40 possible components inside.
I want to create some computers in the collection and the one I tried to create has 22 components. 
I used the REST API with POST method to create the computer.

The computer is created but some of the components are **randomly duplicated**. I tried several times with the same computer data in a row and it creates the computer with 23 to ~35 components randomly.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by ermat77** [comment]
Updated.

**Comment by ermat77** [comment]
I found the origin of the bug :

I forgot to add one component in the dynamic zone of the collection.

But still the behaviour is strange. When you try to add (via REST API or strapi.query('modele').create()) a component that doesn't belong to a dynamic zone it conducts to a random  duplicating of some of the others added components.

**Comment by derrickmehaffy** [comment]
Should already be fixed in v4

**Comment by joshuaellis** [comment]
@Marc-Roig i think we can remove this from JIRA.
