### ISSUE TITLE
How to use changestream feature of mongodb in strapi

### ISSUE THREAD

**Issue by artemis15** [strapi/strapi#10669]
How to use changestream feature of mongodb in strapi

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
