### ISSUE TITLE
ER_DUP_FIELDNAME in field name case change

### ISSUE THREAD

**Issue by msoler75** [strapi/strapi#10675]
1. I create content type
2. I add some fields. All is fine.
3. If i change any field name to lower case or upper case, server stop running with "duplicated field" error.

error Error: ER_DUP_FIELDNAME: Duplicate column name 'titulo'

4. Trying to start "npm run develop" throws same error.
5. To fix, I just open database manually (in my case, mysql) and change the field name in table.

I think that case sensitive errors in field names should be tolered or warned or auto fixed in strapi. But not halting the server running.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
