### ISSUE TITLE
Strapi Save Emoji as ???? (Question marks) in MySql Database

### ISSUE THREAD

**Issue by iKunalmathur** [strapi/strapi#10676]
### Describe the bug

Strapi Save Emoji as ???? (Question marks) in MySql Database

### Steps to reproduce the behavior

1. Download 'https://github.com/strapi/strapi-starter-next-blog'
2. Connect with database in my case which is MySql
3. Create a new article add a description containing Emoji(🙄).
4. See error: Strapi Save Emoji As ???? in database.

### Screenshots

[Bug Image](https://strapi-discourse-prod.s3.dualstack.us-west-2.amazonaws.com/uploads/original/2X/e/ef870e7d16423803d60508639d9a7dad0668a154.png)
![strapi issue](https://user-images.githubusercontent.com/48683374/127856311-5abb7132-f743-4178-90a6-10a988ec9387.png)

### System

- Strapi Version: 3.6.5
- Operating System: Windows 10
- Database: MySQL
- Node Version: 14.17.0
- NPM Version: 6.14.13
- Yarn Version: none

### Additional context

it works fine with the default database (SQLite)

**Comment by derrickmehaffy** [comment]
Can you please confirm what char encoding your MySQL database is set to?

As MySQL defaults to latin1 / latin1_swedish_ci instead of utf8mb4.

**Comment by iKunalmathur** [comment]
@derrickmehaffy  Hi Thanks for the response but I've changed encoding to utf8mb4_unicode_ci in phpMyAdmin but still, it doesn't work.
![image](https://user-images.githubusercontent.com/48683374/128174103-d75fb6ab-e113-4042-b796-7429d2ef8873.png)

**Comment by derrickmehaffy** [comment]
Make sure the database and the table are set to utf8mb4 and keep in mind that by changing that doesn't change the currently stored data, only new data will have that encoding.

**Comment by machengda89** [comment]
Still don`t work!!

**Comment by iKunalmathur** [comment]
hey @machengda89  which database you are using??

**Comment by pierredarrieutort** [comment]
Hello, try to follow https://github.com/strapi/strapi/issues/10468#issuecomment-868968692.

1 - change wanted columns to `utf8mb4_unicode_ci` :
![image](https://user-images.githubusercontent.com/25182438/140282857-b222565f-d87f-444e-8d00-b7446eda5c1d.png)

2 - In `/config/database.js` go to `connections.default.settings` and add `charset: 'utf8mb4'`

**Comment by themtaysw** [comment]
> Hey, try to follow [#10468 (comment)](https://github.com/strapi/strapi/issues/10468#issuecomment-868968692).
> 
> 1 - change wanted columns to `utf8mb4_unicode_ci` : ![image](https://user-images.githubusercontent.com/25182438/140282857-b222565f-d87f-444e-8d00-b7446eda5c1d.png)
> 
> 2 - In `/config/database.js` go to `connections.default.settings` and add `charset: 'utf8mb4'`
> 
> _It works for me_

works in a certain way for me... it tends to save some emojis normally, tho some of them are still as ????. any possible solution?

**Comment by danieltorres1109** [comment]
I add two lines on config/database:
```
charset: 'utf8mb4',
collation: 'utf8mb4_unicode_ci'
```

My code looks as:
`mysql: {
      connection: {
        connectionString: env('DATABASE_URL'),
        host: env('DATABASE_HOST', 'localhost'),
        port: env.int('DATABASE_PORT', 3306),
        database: env('DATABASE_NAME', 'strapi'),
        user: env('DATABASE_USERNAME', 'strapi'),
        charset: 'utf8mb4',
        collation: 'utf8mb4_unicode_ci',
        password: env('DATABASE_PASSWORD', 'strapi'),
        ssl: env.bool('DATABASE_SSL', false) && {
          key: env('DATABASE_SSL_KEY', undefined),
          cert: env('DATABASE_SSL_CERT', undefined),
          ca: env('DATABASE_SSL_CA', undefined),
          capath: env('DATABASE_SSL_CAPATH', undefined),
          cipher: env('DATABASE_SSL_CIPHER', undefined),
          rejectUnauthorized: env.bool(
            'DATABASE_SSL_REJECT_UNAUTHORIZED',
            true
          ),
        },
      },
      pool: { min: env.int('DATABASE_POOL_MIN', 2), max: env.int('DATABASE_POOL_MAX', 10) },
    },`

**Comment by red-made** [comment]
I've done the following:

1- added, as mentioned before, in config/database:
```
charset: 'utf8mb4',
collation: 'utf8mb4_unicode_ci'
```

2- Edited the column:
```
ALTER TABLE
    table_name
    CHANGE column_name column_name
    LONGTEXT
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
```

3- Edited the table:
```
ALTER TABLE
    table_name
    CONVERT TO CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
```

It's working like a charm
