### ISSUE TITLE
Timestamp fields don't display translated using current UI locale

### ISSUE THREAD

**Issue by natanaelsimoes** [strapi/strapi#10672]
### Describe the bug

On listings, when using another UI language rather than English, if created_at/updated_at is set to be shown it displays date/time in English only without applying the current locale.

### Steps to reproduce the behavior

0. Change UI to any language different from English
1. Go to any listing
2. Click on cog icon
3. Configure view
4. Add `created_at` field
5. Save and go back to listing

### Expected behavior

Expected to show the date translated accordingly to UI locale

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.5
- Database: MySQL
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9513
