### ISSUE TITLE
Setting a Search ID query always gives me first element in GraphQL

### ISSUE THREAD

**Issue by diogoviveiros** [strapi/strapi#10684]
Hello, I am trying to run the following query on GraphQL:

```
query GetArticle($id: ID!){
    article(id: $id , publicationState:LIVE){
        id,
        published_at,
        description
    }
}
```
Where my query format in the schema is as follows:

```
type Query {
  article(id: ID!, publicationState: PublicationState): Article
```

However, any time I run this query, I always only get the Article where id is 1? I’ve tried to set the query with a hard variable too, as you can see below.

![image](https://user-images.githubusercontent.com/11295855/128054779-c59e49ce-596f-48cc-9155-3828907e6900.png)

I’ve also tried not running it in Playground. In Apollo GraphQL on Android, the query I set up with any ID always returns the elements of the article where id is 1, nothing else.

What might be causing this? Thank you!

I am just using the default blog template, so it should be fairly easy to reproduce?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by diogoviveiros** [comment]
I'd argue that it is a bug since this graphql query is error free and it appears to be a backend issue, but I will write in the forum instead then. Thank you

**Comment by derrickmehaffy** [comment]
If you believe it is a bug then please use our required bug report template. Any issue that doesn't follow the template will get closed regardless.

See: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

**Comment by mxkdemo** [comment]
@diogoviveiros did you issue a bug report for this? I'm having the same issue.
