### ISSUE TITLE
After redeployed images give Not Found 404 error 

### ISSUE THREAD

**Issue by keyurm-wmt** [strapi/strapi#10685]
### Describe the bug
I upload strapi project on the server. upload images using the Media Library and it's showing images. but after redeployed these images give me not found 404. this problem occurred after being redeployed on the server. using docker i make a build 

### Steps to reproduce the behavior

1.add image content type.
2.add content and upload an image from the device.
3.uploading success.
4. after redeployed images not showing 

### Expected behavior

Images should remain in the media library.

### Screenshots
![image](https://user-images.githubusercontent.com/84059905/128138512-8d109ceb-3723-4c4e-ad14-f0da86277551.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14 alpine
- Yan version: 1.19.1
- Strapi version: 3.6.5
- Database: MySQL
- Operating system: linux

**Comment by derrickmehaffy** [comment]
Where is your application deployed and are you using an upload provider or just the default?

If you are using the default then the images are on the filesystem so if you are using docker (which I assume based on your Node version) then you need a persistent disk for the container. Most likely you don't have one and when you redeployed the images were wiped since the in memory disk was deleted.

**Comment by georgiod9** [comment]
> Where is your application deployed and are you using an upload provider or just the default?
> 
> If you are using the default then the images are on the filesystem so if you are using docker (which I assume based on your Node version) then you need a persistent disk for the container. Most likely you don't have one and when you redeployed the images were wiped since the in memory disk was deleted.

so how do we fix this?

**Comment by derrickmehaffy** [comment]
If you didn't set a persistent disk, those images are gone. It depends on where you are hosting. This likely isn't a bug and is an environmental issue.
