### ISSUE TITLE
error Error: Cannot use GraphQLObjectType "Query" from another module or realm.

### ISSUE THREAD

**Issue by joohimks** [strapi/strapi#10682]
### Describe the bug

When I tried to install the GraphQL plugin, it downloaded but then the server will be dropped and gives the following error.

### Error
error Error: Cannot use GraphQLObjectType "Query" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.

### Steps to reproduce the behavior

1. Go to 'Marketplace'
2. Click on 'Download GraphQL plugin'
3. The issue will appear

### Expected behavior

That GraphQL plugin will be installed and the server will be up and running smoothly just like how I did with another project yesterday.

**Comment by derrickmehaffy** [comment]
@joohimks can you please add the system information to your bug report:

```
### System

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12 / v14) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

**Comment by derrickmehaffy** [comment]
Will reopen this after the required information is added, just reply back once you've added the information, thanks!

**Comment by joohimks** [comment]
It was the node version, thank you for closing this.
