### ISSUE TITLE
Hash is placed and stored in password field when editing a user in the admin

### ISSUE THREAD

**Issue by lschans** [strapi/strapi#1069]
Node: v8.9.4
npm: 5.6.0
Strapi: 3.0.0-alpha.12.0.1
Database : mongodb v3.4.4
OS: macOS 10.13.4

Behavior:
When I edit a user in the admin, the password field gets filled with the hash of the password. You can verify this inspecting the generated source using the element inspector. When you save the user, the password gets replaced with the hash instead of the password. Next time the user tries to log in, the password fails.

I understand that this is the result of a dynamic model editor and in all cases, except the User model, this behavior would be fine. But if editing and adding users should be done by less technical people, this should work a bit more user-friendly.

Reproduce:
Edit a user with the admin and press save.

Expected behavior:
Just for the User model editor, an exception should be in place to skip this field when it's not changed or such.

Suggested solutions:
Create an exception for the User model, or create a plugin to create/update/delete, users. 

[X] I'm sure that this issue hasn't already been referenced

**Comment by daru23** [comment]
I am having the same issue. Could somebody please take a look to solve it.

**Comment by lschans** [comment]
Update: 
It seems to only happen when you have touched the password field before saving.
In MongoDB the password field goes to 'null' also when I use a password starting with '$2a$10$' this happens.

So if my password is '$2a$10$Awes0mePa5s' it's setting it to 'null' in the database.

**Comment by lauriejim** [comment]
Hello, can you try with new project on the last version of Strapi and tell me if it still happening

**Comment by lschans** [comment]
No in the latest version this is solved. Can close this ticket.

**Comment by pbjer** [comment]
@lauriejim I am experiencing this issue in latest version just installed today
