### ISSUE TITLE
Custom components not working on the latest version 

### ISSUE THREAD

**Issue by rullymartanto** [strapi/strapi#10698]
I try follow this tutorial using latest version 3.6.5

https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms/

and in the content-types editor I got this
![image](https://user-images.githubusercontent.com/5577057/128469445-a927c9ed-94a9-44b8-aca5-33528bca37b9.png)

When I used version 3.2.5 
![image](https://user-images.githubusercontent.com/5577057/128470124-3b57a9e2-8cee-40da-bdef-d79dd2ab842f.png)

and I can used this when input the data
![image](https://user-images.githubusercontent.com/5577057/128469746-1d7554e8-e817-4753-981b-9b8833b9d085.png)

and in the version 3.6.5 it won't work
![image](https://user-images.githubusercontent.com/5577057/128469979-de2673d3-cd62-4003-aaa2-11dd4c211d90.png)

Thanks

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
