### ISSUE TITLE
Unique localized fields are impossible with different UTF-8 characters

### ISSUE THREAD

**Issue by wintercounter** [strapi/strapi#10694]
### Describe the bug

`Dráma` and `Drama` are considered to be the same by uniqueness check, making it impossible to translate such.

### Steps to reproduce the behavior

1. Create a collection with localization
2. Add unique text field
3. Add English version: Drama
4. Try to add Hungarian (or another language) version: Dráma
5. See error.

### Expected behavior

Able to save contents that are actually different.

- Strapi version: 3.6.6
- Database: MariaDB

**Comment by derrickmehaffy** [comment]
UID generation appears to have a pretty strict Regex format that the restricts the field and also is used during automatic generation. Unsure if this classifies as a bug as I'm assuming there was a reason why we used that specific regex but the engineering team may need to weigh in for the reason.

**Comment by petersg83** [comment]
@derrickmehaffy How did you know it is an `uid` type? I don't see `uid` mentionned

**Comment by derrickmehaffy** [comment]
Your right, it was an assumption but the issue should only happen in UIDs I believe and not standard unique values.

**Comment by wintercounter** [comment]
No, it's happening with a unique text field.

![image](https://user-images.githubusercontent.com/963776/151030657-6c127351-7896-4055-8c80-f7819c2620d9.png)

**Comment by derrickmehaffy** [comment]
> No, it's happening with a unique text field.
> 
> ![image](https://user-images.githubusercontent.com/963776/151030657-6c127351-7896-4055-8c80-f7819c2620d9.png)
> 

Thanks for the clarification

**Comment by petersg83** [comment]
Thanks @wintercounter.
It seems to be fixed in V4. So I guess we can close this issue as only security issues are done on V3 anymore 😬

**Comment by derrickmehaffy** [comment]
Marking as closed as fixed in v4
