### ISSUE TITLE
Strapi crashes after graphql installation

### ISSUE THREAD

**Issue by mvoloskov** [strapi/strapi#10702]
### Describe the bug

After `npm run strapi install graphql` I can't launch the server because it fails with the following error:
```
[2021-08-06T12:41:56.504Z] debug ⛔️ Server wasn't able to start properly.
[2021-08-06T12:41:56.504Z] error Error: Cannot use GraphQLObjectType "Query" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

Here's the possible reason:

```
$ find node_modules -name graphql

node_modules/graphql (14.7.0)
node_modules/strapi-plugin-graphql/node_modules/graphql (15.5.0)
node_modules/strapi-plugin-graphql/hooks/graphql
```

Versions are somehow mismatched. Quick fix with `resolutions` field didn't work.

### Steps to reproduce the behavior

1. Install Strapi
2. Go to the installation folder and run `npm run strapi install graphql`. Alternatively, install graphql from the admin panel
3. Try to launch the server with `npm run develop`

### System

- Node.js version: 16.1.0, also reproduced on 12.13.0
- NPM version: 7.11.2
- Strapi version: 3.6.6
- Database: postgresql
- Operating system: macOS 11.5.1

**Comment by alexandrebodin** [comment]
Hi, 

I haven't be able to reproduce the error. Can you share how you created your strapi application to try to reproduce with the exact same steps ?

**Comment by mvoloskov** [comment]
I'm on it. I'll let you know of the results

**Comment by mvoloskov** [comment]
I tried to reproduce it with node 16, and it obviously crashed saying that node 16 is not yer supported. After that, I chose node 14 in my node version manager, and it went flawlessly. Then I deleted package-lock.json in my original repository, reinstalled the deps with node 14, installed graphql, and it all launched just fine.

The original repo was initialized with node 12, I guess that's the reason why there were different versions of graphql.

**Comment by mvoloskov** [comment]
@alexandrebodin FYI, strapi did this when installing the plugin:
```
"strapi-plugin-content-type-builder": "3.6.6",
"strapi-plugin-email": "3.6.6",
"strapi-plugin-graphql": "^3.6.6",
"strapi-plugin-i18n": "3.6.6",
"strapi-plugin-upload": "3.6.6",
```

Note the `^` symbol in the `strapi-plugin-graphql`'s version. I think that's an error because afaik the version number should be exact and should match the strapi version. At the very least, this behavior is inconsistent, as other plugins are installed with the exact versions during initialization.

**Comment by alexandrebodin** [comment]
As you are running npm yourself for the strapi-plugin-graphql, npm uses your configuration :)

you would need to add use --save-exact (which I would recommend or set this in your npmrc config). We could add this as a suggestion in the doc though @pwizla :)

**Comment by bharadwajduggaraju** [comment]
I'm having the same issue on windows with my strapi project but don't want to deal with nvm. Is there any other solutions to the mismatching graphql installations.

**Comment by derrickmehaffy** [comment]
> I'm having the same issue on windows with my strapi project but don't want to deal with nvm. Is there any other solutions to the mismatching graphql installations.

Create a `.npmrc` file at the root of your strapi project folder and add `save-exact=true` to it. You can't use nvm on windows anyway or you can set the key at your global .npmrc config if you want to always use exact

**Comment by bharadwajduggaraju** [comment]
Once I do that, do I have to delete my package-lock.json and node_modules and reinstall them to get graphql working or should I just be able to install graphql then. Thanks a lot btw.

**Comment by mvoloskov** [comment]
@bharadwajduggaraju I suggest you use `n` by tj. Nvm is a laggy piece of garbage, n is quick and snappy [https://github.com/tj/n](https://github.com/tj/n)

**Comment by bharadwajduggaraju** [comment]
Hmm seems interesting let me check that out. Now I added my .npmrc file and I'm going to retry  my installation. If that doesn't work I'll use n.

**Comment by bharadwajduggaraju** [comment]
Hmm I tried to fix the issue by adding a .npmrc with save-exact=true and tried to install the graphql plugin but it failed again. I'm going to just use the rest-api for now and will switch when this issue gets fixed in the future. Unless anyone else has a solution that might work.

**Comment by mvoloskov** [comment]
@bharadwajduggaraju I really recommend you to install node 14 via some kind of version manager. Many tools nowadays may require switching a version. After that, you should be able to just install strapi and graphql plugin easily, just as I did.

**Comment by bharadwajduggaraju** [comment]
Okay let me attempt that using n I guess and Ill see if it works. Thanks again for the help.
