### ISSUE TITLE
Strapi Admin: custom settings menu cause `GENERAL` left menu section disappear

### ISSUE THREAD

**Issue by stafyniaksacha** [strapi/strapi#10707]
### Describe the bug

When defining custom settings menu in a plugin without permissions, the `GENERAL` section disappear from left menu:

### Steps to reproduce the behavior

1. Clone the repo https://github.com/digisquad-io/strapi-tests
2. Go to http://127.0.0.1:1337/admin/settings/application-infos
3. See that we have the `SUPER COOL SETTING` section but the `GENERAL` section disappeared from left menu

### Expected behavior

The `GENERAL` section should be displayed
> Related documentation: https://strapi.io/documentation/developer-docs/latest/development/local-plugins-customization.html#plugin-s-front-end-settings-api

### Screenshots

| before | after |
| --- |  --- |
| ![before](https://user-images.githubusercontent.com/3911343/128598637-a4e20189-0142-450d-b8f9-343e630dd5e0.png) | ![after](https://user-images.githubusercontent.com/3911343/128598643-b329679b-aa9c-41bf-ae7e-0150c23f3327.png) |

### Code snippets

```js
// file: plugins/my-custom-plugin/admin/src/index.js
// import React from 'react';
import App from './containers/App';
import Settings from './containers/Settings';
import pluginId from './pluginId';

export default (strapi) => {
  const menuSection = {
    id: pluginId,
    title: {
      id: `${pluginId}.foo`,
      defaultMessage: 'Super cool setting',
    },
    links: [
      // this is causing the issue:
      {
         title: 'Setting page 1',
         name: 'setting1',
         to: `${strapi.settingsBaseURL}/setting1`,
      },
    ],
  };

  const plugin = {
    id: pluginId,
    icon: 'plug',
    name: 'My custom plugin',
    description: 'Homeland to do awesome things',
    preventComponentRendering: false,
    isReady: true,
    isRequired: true,
    initializer: () => null,
    mainComponent: App,
    trads: {},
    injectedComponents: [],
    blockerComponent: null,
    blockerComponentProps: {},
    settings: {
      mainComponent: Settings,
      menuSection,
    },
  };

  return strapi.registerPlugin(plugin);
};
```

### System

- Node.js version: v14.17.3
- NPM version: 7.20.0 (yarn 1.22.5)
- Strapi version: 3.6.6
- Database: sqlite
- Operating system: win/wsl 2

**Comment by derrickmehaffy** [comment]
@alexandrebodin / @soupette I think this is kinda intended functionality for now as we didn't add a simple why to inject plugin settings into the v3 right (iirc we are solving this in the v4)

**Comment by blueorbitz** [comment]
I would appreciate it if all these hidden rules were documented somewhere clear. I literally, spend the whole day trying to search and hack this to work use to lack of documentation.
I still kinda doubt that because the [e-mail plugin](https://beta.quod.ai/github/strapi/strapi/answers/details?open_file=packages%2Fstrapi-plugin-email%2Fadmin%2Fsrc%2Findex.js&state=%7B%22packages%2Fstrapi-plugin-email%2Fadmin%2Fsrc%2Findex.js%22%3A%7B%22range%22%3A%7B%22lineFrom%22%3A0%2C%22lineTo%22%3Anull%7D%2C%22activeQuestionId%22%3Anull%7D%7D )was able to display the intended output.

![image](https://user-images.githubusercontent.com/2269444/156192520-a9bed509-83c9-4ea1-9fdb-17efdf16823e.png)

**Comment by blueorbitz** [comment]
I am using the user account that was created during the first launch. Is that considered as super admin?
I don't think it is a permission issue, as the default setting (marketplace and plugin) disappeared too, right?

**Comment by soupette** [comment]
Well in the v3 these links disappear if you don't have the permissions to access them, similarly for the settings you need to have the right to see at least one link before accessing them.

**Comment by soupette** [comment]
@blueorbitz we are lacking documentation on this part but you can checkout the example of the [email plugin](https://github.com/strapi/strapi/blob/db6a77697779dcd3434e295f5689faa15080c775/packages/strapi-plugin-email/config/functions/bootstrap.js#L23-L33) here's how you can register permissions in the backend and then in the front-end the naming convention of the permission should follow this [convention](https://github.com/strapi/strapi/blob/db6a77697779dcd3434e295f5689faa15080c775/packages/strapi-plugin-email/admin/src/permissions.js#L1-L7)

**Comment by blueorbitz** [comment]
Hi @soupette, this was a great help. I have managed to solve this (ignoring the provider part is a good enough use case for me).

Anyway, I would love to help back the community. How can I help with updating the docs?

**Comment by soupette** [comment]
> Hi @soupette, this was a great help. I have managed to solve this (ignoring the provider part is a good enough use case for me).
> 
> Anyway, I would love to help back the community. How can I help with updating the docs?

This would be the [repository](https://github.com/strapi/documentation) your are looking for.

**Comment by derrickmehaffy** [comment]
I believe this should not be an issue in v4 as we have native APIs for this now so going to set as closed.
