### ISSUE TITLE
Admin hard-coded colours

### ISSUE THREAD

**Issue by stafyniaksacha** [strapi/strapi#10708]
### Describe the bug

Colour customization is not working as expected when overriding the `packages/strapi-admin/admin/src/themes/colors.js` file because of hardcoded values  

#### Hard-coded `strapi-helper-plugin` colours

> https://github.com/strapi/strapi/blob/1c424ad9bafd767ed8abfffa17ee8f1ebb44d21d/packages/strapi-plugin-content-manager/admin/src/components/DraggedField/Wrapper.js#L66

#### Hard-coded `strapi-helper-plugin` colours

> https://github.com/strapi/strapi/blob/1c424ad9bafd767ed8abfffa17ee8f1ebb44d21d/packages/strapi-helper-plugin/lib/src/components/EmptyState/Wrapper.js#L26

#### Hard-coded `buffet` colours

> https://github.com/strapi/buffet/blob/8147ee06d315fa83929e0f3861e8baac9f12c130/packages/buffetjs-styles/src/components/DatePicker/index.js#L171

#### Non-standard colours

> https://github.com/strapi/strapi/blob/1c424ad9bafd767ed8abfffa17ee8f1ebb44d21d/packages/strapi-helper-plugin/lib/src/components/LoadingIndicatorPage/Loader.js#L23

> https://github.com/strapi/strapi/blob/1c424ad9bafd767ed8abfffa17ee8f1ebb44d21d/packages/strapi-admin/admin/src/containers/AuthPage/components/Register/Span.js#L5

> https://github.com/strapi/strapi/blob/1c424ad9bafd767ed8abfffa17ee8f1ebb44d21d/packages/strapi-admin/admin/src/containers/AuthPage/components/Register/index.js#L144

### Expected behaviour

Components should use only colours available from the theme, like `${(props) => props.theme.main.colors.blue}`

**Comment by derrickmehaffy** [comment]
We are planning to handle this in our v4 which will have a configurable style-sheet and eventually adding in the option for themes (v4 will ship with a default light theme, after the initial release we will build in theme support and ship a dark mode theme, TBD if there will other theme options)

**Comment by derrickmehaffy** [comment]
cc: @JabStrapi

**Comment by soupette** [comment]
With the new v4 you'll be able to customise the theme of the admin panel. Here is the [doc](https://github.com/lingui/js-lingui)

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
