### ISSUE TITLE
Strapi Admin: Count characters in  TEXTBOX when writing a New Entry

### ISSUE THREAD

**Issue by ablaas** [strapi/strapi#10706]
### Please describe your feature request

When creating a new entry, textboxes (short/long text) could show how many characters have been written. 
This is perfect to accurately write `meta-description` and `meta-titles`

An extra feature is showing a different color if you are in the range of allowed number of characters (min/max) as defined for the field.

[ ] **I have created my request on the Product Board before I submitted this issue** <<< ¯\_(ツ)_/¯ NOT SURE WHAT THIS MEANS 
[ x ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

This improves UX when writing content, as you can see how long is your text.
Also gives instant feedback if the text is too short or too long

### Why is it needed?

I'm always frustrated when writing content optimized for SEO, as I need to do it in an external app and paste it, so I can be sure I'm within the limits.

### Suggested solution(s)

While you write, the text box shows how many characters are written, and changes colors (eg from red to gray) when we are between the boundaries of minimum and maximum length.

![image](https://user-images.githubusercontent.com/5245751/128591601-1172508e-ad0c-4b64-a3be-bd41acebbff7.png)

**Comment by scr2em** [comment]
this is still a very specific case ... 
we urgently need the ability to create custom fields which will enable us to
1- Override the current fields to enhance them (like you kindly suggested) 
2- adding new custom fields (npm would flourish with this kind)

because you can do this "feature" by simply editing the core strapi module 
`\node_modules\strapi-plugin-content-manager\admin\src\components
` adding a simple line like this in your desired component 
`{<div>{value.length}</div>}
but to change the core module you will have to fork Strapi and maintain your fork for future updates (manually)
`

**Comment by ablaas** [comment]
Thanks @scr2em ... I'm sure custom fields is a great add-on. 
Anyway... if this is so simple, I suppose it would be so easy for the Strapi team to add it, giving users a much better UX: big value with minimum effort!

**Comment by LucaNerlich** [comment]
I disagree. It clutters the ui and is not inherently and improvement for all users. 
I personally dont really see the benefit of this, apart from specific design limitations for authors.

**Comment by derrickmehaffy** [comment]
cc: @JabStrapi / @maevalienard / @mfrachet to get your thoughts, it would be a pretty simple add-on maybe configurable?

**Comment by ablaas** [comment]
Hi all,

We managed to implement it (fairly simple). Thanks @scr2em for the tip.
I disagree with @LucaNerlich about cluttering, and of course it has benefits. I suppose you don't write SEO optimized content.

1. When writing meta-titles or meta-description, it is very useful to know how many characters you are writing down, so you can be creative and meet SEO-optimized rules.2. 
2. UX: when a field has min/max values, you can see if you are between the range without needing to lose focus or try to save your content. 

You can see how it looks:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/5245751/128818870-9f6b151e-9e72-433a-b2d2-292cf3de88f4.png">

<img width="505" alt="image" src="https://user-images.githubusercontent.com/5245751/128818939-468cfd85-8b96-4b78-a134-6e9c0b79945c.png">

**Comment by ablaas** [comment]
Next step is to implement a color code, so:

if the text field has limits (min/max), the text should change from **red** to **gray** when crossing boundaries.
So it would start 
- If min boundary: red IF x < min ELSE gray
- if min < x < max: gray
- if x > max: red again

**Comment by ablaas** [comment]
@LucaNerlich of course you can declutter the UI with a little refinement, but not sure if the effort is worth:

- Only activate the character counting when the textbox receives the focus
- When losing focus, the counter can dissapear if the validation is ok (max/min)
- If outside boundaries, then the counter in red would stay until corrected.

**Comment by mimartinez** [comment]
Hello everyone,
We have managed to modify the plugin with this code in `/extensions/content-manager/admin/src/components/Inputs/index.js`

```return (
    <div>
      <InputsIndex
        {...metadatas}
        autoComplete="new-password"
        autoFocus={autoFocus}
        disabled={shouldDisableField}
        error={errorMessage}
        inputDescription={description}
        labelIcon={labelIconformatted}
        description={description}
        contentTypeUID={currentContentTypeLayout.uid}
        customInputs={{
          json: InputJSONWithErrors,
          wysiwyg: WysiwygWithErrors,
          uid: InputUID,
          ...otherFields,
        }}
        multiple={fieldSchema.multiple || false}
        attribute={fieldSchema}
        name={keys}
        onBlur={onBlur}
        onChange={onChange}
        options={options}
        step={step}
        type={inputType}
        validations={validations}
        value={inputValue}
        withDefaultValue={false}
      />
      {(inputType === "text" || inputType === "textarea") && (
        <label
          style={{
            position: "absolute",
            top: "0",
            right: "0",
            marginRight: "15px",
            zIndex: "100",
            fontFamily: "Lato",
            fontSize: "12px",
            color: "rgb(158, 167, 184)",
          }}
        >
          {`${inputValue ? inputValue.length : 0} ${formatMessage({
            id: `${pluginId}.form.Input.characters.count`,
          })}`}
        </label>
      )}
    </div>
  );
```

Of course, this code is for all inputs of type `text` and `textarea`, its thing would be to put it in a configuration as it says @derrickmehaffy

**Comment by maevalienard** [comment]
Hi! I find this idea interesting. Thanks for the suggestion 😄  To be perfectly honest, I'm not sure if now is the right time to implement that (v4, etc.) but we'll definitely keep it under consideration for further iterations!

**Comment by rgesulfo** [comment]
Hi @ablaas,
I'm a Product Designer at Strapi, currently working on plugins :)
Your suggested solution seems very relevant for the use cases you mention.
Are you planning to make this feature a plugin? Or does it have to be part of the core?
If you are considering the plugin road, the expansion team (@emilieringwald) is here to help :)
Thanks for all your great work.

**Comment by tablufc88** [comment]
Came across this today whilst trying to implement the exact same thing with v4. Struggled overriding with extensions & ended up using [patch-package](https://github.com/ds300/patch-package) to get it working.

We have a few similar use cases, it would be good to know if this is the best way of overriding things like this.

Here is what I ended up with:

```diff
diff --git a/node_modules/@strapi/admin/admin/src/content-manager/components/Inputs/index.js b/node_modules/@strapi/admin/admin/src/content-manager/components/Inputs/index.js
index 4ffc0f3..9fae114 100644
--- a/node_modules/@strapi/admin/admin/src/content-manager/components/Inputs/index.js
+++ b/node_modules/@strapi/admin/admin/src/content-manager/components/Inputs/index.js
@@ -12,6 +12,7 @@ import Wysiwyg from '../Wysiwyg';
 import InputJSON from '../InputJSON';
 import InputUID from '../InputUID';
 import SelectWrapper from '../SelectWrapper';
+import { useTheme } from "styled-components"
 
 import {
   connect,
@@ -36,6 +37,7 @@ function Inputs({
   queryInfos,
   value,
 }) {
+
   const { fields } = useLibrary();
   const { formatMessage } = useIntl();
   const { contentType: currentContentTypeLayout } = useContentTypeLayout();
@@ -219,7 +221,18 @@ function Inputs({
     );
   }
 
+  const inputLength = inputValue?.length || 0
+  const titleMin = 30
+  const titleMax = 60
+  const descriptionMin = 50
+  const descriptionMax = 160
+  const isSeo = keys.includes("seo")
+  const isTitle = keys === "seo.titleTag"
+  const isDescription = keys === "seo.metaDescription"
+  const theme = useTheme()
+
   return (
+    <div style={{ position: "relative" }}>
     <GenericInput
       attribute={fieldSchema}
       autoComplete="new-password"
@@ -248,6 +261,26 @@ function Inputs({
       value={inputValue}
       withDefaultValue={false}
     />
+    {isSeo && (inputType === "text" || inputType === "textarea") && (
+        <label
+          style={{
+            position: "absolute",
+            top: "0",
+            right: "0",
+            fontSize: "12px",
+            color: isTitle ? ( 
+              (inputLength >= titleMin && inputLength <= titleMax) ? theme.colors.success500 : theme.colors.danger500 )
+
+              : isDescription ? ( 
+              (inputLength >= descriptionMin && inputLength <= descriptionMax) ? theme.colors.success500 : theme.colors.danger500 ) 
+
+              : theme.colors.neutral500
+          }}
+        >
+          {`${inputLength} characters`}
+        </label>
+      )}
+    </div>
   );
 }
```

**Comment by Webbist-dev** [comment]
This looks super useful

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/count-characters-in-textbox-when-writing-a-new-entry
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
