### ISSUE TITLE
Unable to update single type if one of its fields is named "where"

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#10710]
### Describe the bug
If you have a single type and one of its fields is named `where`, you cannot update the content (HTTP 400). It seems that the content is not escaped nor sanitized and is being interpreted in SQL queries. Could lead to SQL injections, no?

### Steps to reproduce the behavior

1. Create a single type with a component field named "where"
2. Go to your single type edit page and fill it with dummy content
3. Save (it may work there)
4. Make an edit and save again
5. A notification is toggled "Invalid input data. Please verify unique constraints"
6. An error is triggered in console (the one below is my actual one)
```
Undefined binding(s) detected when compiling SELECT. Undefined column(s): [about_pages_components.about_page_id] query: select distinct `about_pages_components`.* from `about_pages_components` where `field` = ? and `component_type` 
in (?, ?, ?, ?, ?, ?, ?) and `about_pages_components`.`about_page_id` = ? order by `order` asc
```

### Expected behavior
You should be able to name your fields as you want without triggering errors on save. OR at least trigger an error with a more speaking message: I spent 1 hour figuring out what was wrong.

### Screenshots

N/A

### Code snippets
Single type definition 
```jsonc
// api/about-page/about-page.settings.json
{
  "kind": "singleType",
  "collectionName": "about_pages",
  "info": {
    "name": "aboutPage",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "intro": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "richtext"
    },
    "what": {
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "sections.content-block"
    },
  
    "where": {
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "sections.content-block"
    }
  }
}
```
Component used  below
```jsonc
// components/sections/content-block.json
{
  "collectionName": "components_sections_content_blocks",
  "info": {
    "name": "contentBlock",
    "icon": "archive"
  },
  "options": {},
  "attributes": {
    "title": {
      "unique": false,
      "type": "string"
    },
    "content": {
      "unique": false,
      "type": "richtext"
    },
    "picture": {
      "unique": false,
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "files",
        "images",
        "videos"
      ],
      "plugin": "upload",
      "required": false,
      "pluginOptions": {}
    }
  }
}
```
### System

- Node.js version: 12.22.1
- NPM version: 6.14.12
- YARN version: 1.22.10
- Strapi version: 3.6.6
- Database: tested with both `postgres` and `mysql`
- Operating system: OSX

### Additional context

It may be the same issue with content types (not tested). I guess mongo may not be concerned by this issue.
You may ask yourself "WHY THE HELL DO YOU WANT TO NAME A FIELD WHERE?!". Well: my single type is about page for a next website that presents a project: what, where, when, why, how, how much. 
Temp workaround is to change the field name but this issue should be investigated further.

**Comment by Saad-ISAA** [comment]
or you can just prefix it with an _ like _where _why _when

**Comment by Saad-ISAA** [comment]
i think if there's this restriction of not using these names then strapi should return an error indicating that these names cannot be used when creating that field, instead of the developer investigating what could have gone wrong. this is fixed for created_at created_by fields though

**Comment by derrickmehaffy** [comment]
Question is, do we consider this issue a duplicate of https://github.com/strapi/strapi/issues/1198 (the tracking issue for words that aren't handled for various reasons)

**Comment by derrickmehaffy** [comment]
I'm gonna set this as a duplicate for now, but @8byr0 let me know what you think.

**Comment by 8byr0** [comment]
@derrickmehaffy Well I do not consider this being fully in the other issue's scope. It's related to it because a word used as model attribute leads to API unhandled error complicated to troubleshoot. 

But It's not just about a word making your app malfunctioning: here if you use the "where" keyword then its content is interpreted as a part of SQL request which is IMHO a real security concern but I may be wrong? 

On the other hand I agree with @Saad-ISAA : if you know a word is causing troubles it should at least be rejected properly with an understandable error or be listed in documentation with other words.

**Comment by derrickmehaffy** [comment]
> On the other hand I agree with @Saad-ISAA : if you know a word is causing troubles it should at least be rejected properly with an understandable error or be listed in documentation with other words.

That's specifically what that other tracking issue is for, to eventually develop something to either return a sane error back to the user before it causes problems (just as a bad word list) or handling cases with words that can't have a plural option (like news).

There is no security impact here that I'm aware of but we have had cases of this in the past hence why I created that Tracking issue.
