### ISSUE TITLE
How can we add  dynamic select country, state and city in admin

### ISSUE THREAD

**Issue by tufail** [strapi/strapi#10715]
Hello 👋  

How can we use dynamic data in Strapi admin.
I am using all SQL data from here https://github.com/hiiamrohit/Countries-States-Cities-database

So the logic I like to implement is :
Once the country is selected should show only states from state table which has the same country id and if state is selected should show only cities from the same state.
 
![image](https://user-images.githubusercontent.com/377556/128811141-b7a1d495-ab39-433d-a49c-4bda1e0ede08.png)

Please help me

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8708
