### ISSUE TITLE
v3.6.6 reporting itself as v3.6.5?

### ISSUE THREAD

**Issue by lukearmstrong** [strapi/strapi#10712]
### Describe the bug

I've just updated from v3.6.5 to v3.6.6... but the admin panel still says there is an update available.

### Screenshots

![image](https://user-images.githubusercontent.com/306764/128724842-e712bdd3-363d-4d12-8cab-bf65cf4aac43.png)
![image](https://user-images.githubusercontent.com/306764/128724652-e85f3ad9-a41b-42be-aa26-85a4b98e440b.png)
![image](https://user-images.githubusercontent.com/306764/128724702-49e264ec-0a25-4df6-9f91-117ca4fd40b1.png)
![image](https://user-images.githubusercontent.com/306764/128724733-c41cf823-3e0d-44fa-a3a0-16113d68deec.png)

### System

- Node.js version: v12.20.1
- NPM version: 6.14.10
- Strapi version: 3.6.6
- Database: PostgreSQL
- Operating system: Using the official strapi docker container [strapi/strapi:3.6](https://hub.docker.com/r/strapi/strapi)

**Comment by Saad-ISAA** [comment]
Was answered in discord chat
https://discord.com/channels/811989166782021633/827317901509525594/874305259894374440

can be closed

**Comment by lukearmstrong** [comment]
It turns out I needed to run this command to get the version number to be updated.

```
npm run build -- --clean
```
