### ISSUE TITLE
Adding cloudinary provider give 502 bad gateaway

### ISSUE THREAD

**Issue by chotardlucien** [strapi/strapi#10718]
Hello,

I have installed strapi on a DigitalOcean droplet, secured with SSL through a subdomain. (I was getting an error on my frontend because of HTTP, that's why I secured it with SSL dubdomain)
I also have installed WYSIWYG editor.  Since I have images in rich text fields, the url served by the API is the server IP (HTTP), whereas it should be the domain (HTTPS).

That's why I'm trying to install cloudinary (I didn't find a way to change only the media url from the server IP to my subdomain).
When i add the content of config/plugins.js, it break the backend and I am getting 502 bad gateaway.

`module.exports = ({ env }) => ({
  upload: {
    provider: 'cloudinary',
    providerOptions: {
      cloud_name: env('CLOUDINARY_NAME'),
      api_key: env('CLOUDINARY_KEY'),
      api_secret: env('CLOUDINARY_SECRET'),
    },
    actionOptions: {
      upload: {},
      delete: {},
    },
  },
});`

environment variables are properly set

Please could you help ?
Best regards

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
