### ISSUE TITLE
multi-tenant (multi-site) subdomain and domain

### ISSUE THREAD

**Issue by 3LaHoonK** [strapi/strapi#10722]
Hello strapi

Thank you for your efforts and I wish you continued success

Feature Request
multi-tenant subdomain and domain

Example
strapi multi-store

store1.strapi.com or store1.com or both 
store2.strapi.com or store2.com or both 

Each store is separate from the other

But the same features, services and features
Just disable features, features, and services

Everyone has their own payment gateway

Every store can make an apps for mobile

I wish you success, waiting for a response, thank you

**Comment by derrickmehaffy** [comment]
Duplicate: https://portal.productboard.com/strapi/1-roadmap/c/36-multi-tenancy
