### ISSUE TITLE
New Field having default value is not generating default values to existing records

### ISSUE THREAD

**Issue by prernagp** [strapi/strapi#10724]
### Describe the bug

I altered a table and added a new property to the table. Set its default value, so that the already existing records do not have null values for the same field. But, when I started Strapi, all the existing records have null values for the field.

### Steps to reproduce the behavior

1. Add a new field
2. Set default value
3. After saving, you will see that field is added to the table
4. But the default values are not added.

### Expected behavior

Default values for the already existing records should not be null.

### System

- Node.js version: v14.17.0
- NPM version: 7.16.0
- Strapi version: 3.1.4
- Database: postgresql
- Operating system: Ubuntu 20.04.2 LTS

**Comment by derrickmehaffy** [comment]
This will be made possible in the v4 if using the model settings to set the database default to the Strapi application default.

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed

**Comment by korokd** [comment]
> This will be made possible in the v4 if using the model settings to set the database default to the Strapi application default.

Just ran into the issue describe in this issue. I am using v4, and don't think I've changed any configuration on this, but I digress.

What setting is it that I need to enable to use the application default in the database? Can you link me to the docs? @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> > This will be made possible in the v4 if using the model settings to set the database default to the Strapi application default.
> 
> Just ran into the issue described in this issue. I am using v4, and don't think I've changed any configuration on this, but I digress.
> 
> What setting is it that I need to enable to use the application default in the database? Only doc I could find on that is [the column.defaultTo](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-attributes), but I need a `boolean` not a `string`.
> 
> @derrickmehaffy 

Those column options are experimental and are just abstractions from Knex so they may not cover every use-cases. Usually in most databases, booleans are tinyInt which allow for basically a 0 or 1. I would check your database to confirm and try setting it that instead.

**Comment by korokd** [comment]
> > > This will be made possible in the v4 if using the model settings to set the database default to the Strapi application default.
> > 
> > 
> > Just ran into the issue described in this issue. I am using v4, and don't think I've changed any configuration on this, but I digress.
> > What setting is it that I need to enable to use the application default in the database? Only doc I could find on that is [the column.defaultTo](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-attributes), but I need a `boolean` not a `string`.
> > @derrickmehaffy
> 
> Those column options are experimental and are just abstractions from Knex so they may not cover every use-cases. Usually in most databases, booleans are tinyInt which allow for basically a 0 or 1. I would check your database to confirm and try setting it that instead.

Yeah, I don't really wanna have to use/try that as it is experimental (and I'm not that knowledgeable in databases tbh). I would be more interested in this thing you mentioned when this issue was first opened:

> This will be made possible in the v4 if using the model settings to set the database default to the Strapi application default.

How do I check/change this model setting you spoke of? I couldn't find anything about it on the [model docs](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html).

**Comment by derrickmehaffy** [comment]
That's what I was talking about, it's experimental: https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#database-validations-and-settings

![image](https://user-images.githubusercontent.com/8593673/185220205-b5fb85d4-09dc-4202-a47b-ce1dccb78de3.png)

**Comment by korokd** [comment]
Oh, gotcha. Well, will see if that works then. Thanks for the help @derrickmehaffy !

**Comment by nmtri-dev** [comment]
@korokd are you able to make it work. To me, the existing records in database is not updated with the default value.

**Comment by Husky931** [comment]
still waiting for this. Default values are not being applied.

**Comment by r0emek** [comment]
Worked for me, 
but you need to set both `defaultTo` and `notNullable`. 
Only this configuration tells db to cerate column and fill existing records with default value.
 
    "attName": {
      ...,
      "column": {
        "defaultTo": "defaultValue",
        "notNullable": true
      }
    }
strapi v4.12.0
