### ISSUE TITLE
Issue installing GraphQL plugin in strapi

### ISSUE THREAD

**Issue by gaurav552** [strapi/strapi#10721]
This is simply a bug report, the issue has been resolved. Keep reading for solution. it took me quite awhile to resolve the issue and no `` resolution: {<package>:<version>} `` did not work

_Version - 3.6.6 (node v14.17.4)_

**Steps to reproduce**

1. Create a new project, I tried using custom MySQL database and Strapi templates
2. go to admin panel, and go to market place
3. download GraphQL

it will take some time to download and once the download is complete the server wont be able to restart and throws the following error on the console

```
[2021-08-11T00:56:51.895Z] debug POST /admin/plugins/install (31877 ms) 200
[2021-08-11T00:56:51.896Z] info The server is restarting

[2021-08-11T00:56:53.579Z] debug ⛔️ Server wasn't able to start properly.
[2021-08-11T00:56:53.580Z] error Error: Cannot use GraphQLObjectType "Query" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (E:\cms\strapping\node_modules\strapi-plugin-graphql\node_modules\graphql\jsutils\instanceOf.js:29:13)
    at isObjectType (E:\cms\strapping\node_modules\strapi-plugin-graphql\node_modules\graphql\type\definition.js:122:34)
    at printType (E:\cms\strapping\node_modules\strapi-plugin-graphql\node_modules\graphql\utilities\printSchema.js:130:36)
    at E:\cms\strapping\node_modules\strapi-plugin-graphql\node_modules\graphql\utilities\printSchema.js:59:12
    at Array.map (<anonymous>)
    at printFilteredSchema (E:\cms\strapping\node_modules\strapi-plugin-graphql\node_modules\graphql\utilities\printSchema.js:58:13)
    at Object.printSchema (E:\cms\strapping\node_modules\strapi-plugin-graphql\node_modules\graphql\utilities\printSchema.js:40:10)
    at writeGenerateSchema (E:\cms\strapping\node_modules\strapi-plugin-graphql\services\schema-generator.js:138:31)
    at Object.generateSchema (E:\cms\strapping\node_modules\strapi-plugin-graphql\services\schema-generator.js:109:5)
    at Object.initialize (E:\cms\strapping\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:76:74)
    at E:\cms\strapping\node_modules\strapi\lib\hooks\index.js:37:28 
```

**The problem**
it seems like the installed plugin is using newer version of graphQL when i run `` npm list graphql ``
i get the following it is a pretty big tree and everywhere else it seems to be using graphql 14.7.0, but the last node is using 15.5.0

```
  │ │ ├── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │   └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-depth-limit@1.1.0
  ├─┬ graphql-iso-date@3.6.1
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-tools@4.0.8
  │ ├─┬ apollo-link@1.2.14
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ ├─┬ apollo-utilities@1.3.4
  │ │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-type-json@0.3.2
  │ └── graphql@14.7.0 deduped
  ├─┬ graphql-type-long@0.1.1
  │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  ├─┬ graphql-upload@11.0.0
  │ └── graphql@14.7.0 deduped invalid: "^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0" from node_modules/graphql-type-long
  └── graphql@15.5.0
```
I did this about 15 times over the weekend, and tried out different solutions, and nothing seems to work,
**Because it breaks as soon as I install the graphql this definitely is not a fault on my end**

### Solution

1. just install the graphql plugin
2. run `` npm list graphql ``
3. This is optional but you can check your current graphql version with `` npm info graphql version`` and see if it matches the list. for me the installed version was 15.5.1 but the list showed 15.5.0.
4. run `` npm install graphql@<version>`` for the latest version from the list

This issue wasted my so much time so, something has to be done. Please fix it.

**Comment by derrickmehaffy** [comment]
Ran tests on 5 different machines:

- Local System: Linux Mint 20.2 => Can't reproduce with Node 14/12 + npm/yarn
- Local System: Windows 10 => Can't reproduce with Node 14 + npm/yarn
- Local System: MacOS Catalina => Can't reproduce with Node 14/12 + npm/yarn
- Local Virtual Machine: RedHat 8 => Can't reproduce with Node 14 + npm
- Remote Virtual Machine (DigitalOcean): Ubuntu 20.04.2 => Can't reproduce with Node 14/12 + npm/yarn

Simply using a `npm i strapi-plugin-graphql --save` or `yarn add strapi-plugin-graphql` yielded no errors. I didn't attempt to override the actual `graphql` version and used what was shipped with the plugin.

Likewise using the `yarn strapi install graphql` worked fine as well.

**Comment by gaurav552** [comment]
> Ran tests on 5 different machines:
> 
> * Local System: Linux Mint 20.2 => Can't reproduce with Node 14/12 + npm/yarn
> * Local System: Windows 10 => Can't reproduce with Node 14 + npm/yarn
> * Local System: MacOS Catalina => Can't reproduce with Node 14/12 + npm/yarn
> * Local Virtual Machine: RedHat 8 => Can't reproduce with Node 14 + npm
> * Remote Virtual Machine (DigitalOcean): Ubuntu 20.04.2 => Can't reproduce with Node 14/12 + npm/yarn
> 
> Simply using a `npm i strapi-plugin-graphql --save` or `yarn add strapi-plugin-graphql` yielded no errors. I didn't attempt to override the actual `graphql` version and used what was shipped with the plugin.
> 
> Likewise using the `yarn strapi install graphql` worked fine as well.


This is really interesting, after reading you reply I ran the test 2 more times, and it's still the same, i have to change the version of the graphql installed for the app to run.

Now i just bought this computer that i am working on, and i did ran strapi without any issues on my old machine, so i ran the test again on the old device and i did not have the issue there.

So definitely something is going on with my computer, i did reinstall npm, create-strapi-app and even installed git bash to simulate my old device and none of those helped.

I will be firing up a vm and do some more tests. I will close the issue for the time being.
