### ISSUE TITLE
If i add a custom controller it throw an error, it works fine in new project

### ISSUE THREAD

**Issue by Hamza-Liaqat1** [strapi/strapi#10728]
I am applying is Owner policy, where I have added custom controller methods, sometime it breaks especially when I add it in a running project,
Here is the custom controller
`"use strict";

const { parseMultipartData, sanitizeEntity } = require("strapi-utils");

/**
 * Read the documentation (https://strapi.io/documentation/v3.x/concepts/controllers.html#core-controllers)
 * to customize this controller
 */

module.exports = {
  /**
   * Create a new restaurant
   *
   * @param {*} ctx The Strapi Context
   */
  async create(ctx) {
    let entity;

    if (ctx.is("multipart")) {
      const { data, files } = parseMultipartData(ctx);
      data.user = ctx.state.user.id;
      entity = await strapi.services.restaurant.create(data, { files });
    } else {
      ctx.request.body.user = ctx.state.user.id;
      entity = await strapi.services.restaurant.create(ctx.request.body);
    }
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },

  /**
   * Update a restaurant
   *
   * @param {*} ctx the request context
   */

  async update(ctx) {
    const { id } = ctx.params;

    let entity;

    // Find the restaurant matching the ID and the user
    const [restaurant] = await strapi.services.restaurant.find({
      id: ctx.params.id,
      "user.id": ctx.state.user.id,
    });

    if (!restaurant) {
      return ctx.unauthorized(`You can't update this entry`);
    }

    // Update the restaurant
    if (ctx.is("multipart")) {
      const { data, files } = parseMultipartData(ctx);
      entity = await strapi.services.restaurant.update({ id }, data, {
        files,
      });
    } else {
      entity = await strapi.services.restaurant.update(
        { id },
        ctx.request.body
      );
    }

    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },

  /**
   * List all the categories beloinging to the requesting user
   *
   * @param {*} ctx the request context
   */

    async find(ctx) {
      let entities;

      if (ctx.query._q) {
        entities = await strapi.services.restaurant.search({
          ...ctx.query,
          "user.id": ctx.state.user.id,
        });
      } else {
        entities = await strapi.services.restaurant.find({
          ...ctx.query,
          "user.id": ctx.state.user.id,
        });
      }

      return entities.map((entity) =>
        sanitizeEntity(entity, { model: strapi.models.restaurant })
      );
    },

  /**
   * Get the restaurant with a specific ID
   *
   * @param {*} ctx the request context
   */
  async findOne(ctx) {
    const { id } = ctx.params;

    const entity = await strapi.services.restaurant.findOne({
      id,
      "user.id": ctx.state.user.id,
    });

    if (!entity) {
      return ctx.unauthorized(`You can't view this entry`);
    }

    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },

  /**
   * Count of the categories of the requesting user
   *
   * @param {*} ctx the request context
   */

  count(ctx) {
    if (ctx.query._q) {
      return strapi.services.restaurant.countSearch({
        ...ctx.query,
        "user.id": ctx.state.user.id,
      });
    }
    return strapi.services.restaurant.count({
      ...ctx.query,
      "user.id": ctx.state.user.id,
    });
  },

  /**
   * Delete a record
   *
   * @param {*} ctx the request context
   */
  async delete(ctx) {
    const [restaurant] = await strapi.services.restaurant.find({
      id: ctx.params.id,
      "user.id": ctx.state.user.id,
    });

    if (!restaurant) {
      return ctx.unauthorized(`You can't delete this entry`);
    }

    let entity = await strapi.services.restaurant.delete({ id: ctx.params.id });
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
};
`
Here is the Api response, while getting /restaurants find method

{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Your filters contain a field 'user.id' that doesn't appear on your model definition nor its relations"
}

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
