### ISSUE TITLE
Logging in as admin not working in Chrome, but working in FF

### ISSUE THREAD

**Issue by richleach** [strapi/strapi#10735]
### Describe the bug

(When I installed strapi I had to add a super user, I'm calling him 'sa' for purposes of this report.)
When I log into strapi localhost:1337/admin (as sa) on Chrome (Version 92.0.4515.107 (Official Build) (x86_64)) I get logged in but I don't see the General section of the left side menu (Marketplace, Plugins and Settings are not visible). I have to open and log into Firefox (as sa) in order to see the General menu items. (The Collection Types and the Plugins are visible as expected.) 

### Steps to reproduce the behavior

1. Go to 'http://localhost:1337/admin and login with the credentials of your sa using Chrome in the details I described above.'
2. Notice the left hand menu in darkblue, there should be a "General" section, which is not present in Chrome, only in Firefox.
3. There is no error reported, but the menu items do not fully display in Chrome, I have to open and login using Firefox.

### Expected behavior

I expect to observe the same experience when logging in as the same user in any browser. It would appear that my sa user is a different user in different browsers, at least in Chrome.

### Screenshots

![image](https://user-images.githubusercontent.com/1168807/129422969-25faf052-5cdb-469d-b682-420b339949a0.png)
The screen in the foreground is Chrome, the background is Firefox.

### Code snippets

Not applicable

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.3
- Database: sqllite
- Operating system: Mac OS 10.14.6

### Additional context

I discovered this issue as I was going through a React training course on Udemy, and I needed to login through my Next.js application but I am only getting "Please provide your username or your e-mail." returned from strapi. In an attempt to debug this issue I encountered this admin UI bug.

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.6.3

Can you try upgrading to the latest version? (v3.6.6) and do make sure to rebuild your admin panel

**Comment by derrickmehaffy** [comment]
User hasn't provided any additional context, marking as closed.
