### ISSUE TITLE
error CastError: Cast to ObjectId failed for value ":id" at path "_id" for model `<collection-type-name>`

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#10738]
### Describe the bug

I tried to add a new record/data in Strapi v3.6.6 with MongoDB Atlas. 

Let's say the collection-type name is `my-collection-type`.
However, when I click `Add New myCollectionType` button : 

![image](https://user-images.githubusercontent.com/43397636/129489164-a23fcd8a-1e19-456e-b7ee-38a2d8cb4e56.png)

suddenly I got this error in log : 

`error CastError: Cast to ObjectId failed for value ":id" at path "_id" for model "my-collection-type"`

![image](https://user-images.githubusercontent.com/43397636/129489083-04c9b29f-ec30-411f-801e-c6d298948340.png)

### Steps to reproduce the behavior

1. Login to existing Strapi app using MongoDB
2. Go to the collection-type that you created. In this case, it is `myCollectionTypes`.
3. Click on the 'Add New myCollectionTypes' button
4. See error. The Strapi client (UI) is loading, while the log says `error CastError: Cast to ObjectId failed for value ":id" at path "_id" for model "my-collection-type"`

### Expected behavior

Able to create a new record/data in a collection-type. 

### Screenshots

Added above.

### Code snippets

Just basic database configuration in `config.js` : 
```js
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        host: env('DATABASE_HOST', '127.0.0.1'),
        srv: env.bool('DATABASE_SRV', false),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'strapi-example-mongodb'),
        username: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
      },
      options: {
        authenticationDatabase: env('AUTHENTICATION_DATABASE', null),
        ssl: env.bool('DATABASE_SSL', false),
      },
    },
  },
});
```

`package.json` (already v3.6.6) : 

```json
{
  "name": "strapi-mongodb-sample-app",
  "private": true,
  "version": "0.1.0",
  "description": "Strapi sample app",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.6.6",
    "strapi-admin": "3.6.6",
    "strapi-connector-mongoose": "3.6.6",
    "strapi-plugin-content-manager": "3.6.6",
    "strapi-plugin-content-type-builder": "3.6.6",
    "strapi-plugin-documentation": "3.6.6",
    "strapi-plugin-email": "3.6.6",
    "strapi-plugin-graphql": "3.6.6",
    "strapi-plugin-upload": "3.6.6",
    "strapi-plugin-users-permissions": "3.6.6",
    "strapi-provider-email-amazon-ses": "3.6.6",
    "strapi-provider-upload-aws-s3": "3.6.6",
    "strapi-utils": "3.6.6"
  },
  "strapi": {},
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

### System

- Node.js version: 14.17.5
- Yarn version: 1.22.10
- Strapi version: 3.6.6
- Database: MongoDB Atlas
- Operating system: WIndows 10

In my opinion, this never happened before. This might be a critical bug if it is recognized as a bug and is reproducible as CRUD is one of the most important feature in manipulating data and in Strapi, in my opinion.

Any help is much appreciated !

**Comment by kevinadhiguna** [comment]
I tried to downgrade Strapi v3.6.6 (currently the latest version) one by one until Strapi v3.6.0.
Finally Strapi v3.5.4 worked. Downgrading version seems to be the temporary solution for now.

**Comment by kevinadhiguna** [comment]
I just created a brand new Strapi app in which I use MongoDB to store database and I can confirm the bug still happens.

**Comment by kevinadhiguna** [comment]
I think this is caused by : #8490

**Comment by derrickmehaffy** [comment]
I've just tested every version from v3.5.4 to v3.6.8 and cannot reproduce it.

This sounds like you made a major jump at some point and your model's config/routes.json still has a reference to `:_id` which we stopped using a long time ago.

**Comment by kevinadhiguna** [comment]
> I've just tested every version from v3.5.4 to v3.6.8 and cannot reproduce it.
> 
> This sounds like you made a major jump at some point and your model's config/routes.json still has a reference to `:_id` which we stopped using a long time ago.

It is. I just created a new Strapi app using MongoDB. Then I created a new collection-type in which I can not add a record.

Here is what happened :

![strapi-mongo-bug](https://user-images.githubusercontent.com/43397636/132127045-dcdb81dd-fd1f-46b7-85ad-ec1108ff94d3.gif)

**Comment by kevinadhiguna** [comment]
> I've just tested every version from v3.5.4 to v3.6.8 and cannot reproduce it.
> 
> This sounds like you made a major jump at some point and your model's config/routes.json still has a reference to `:_id` which we stopped using a long time ago.

May I know your system information such as OS and Node version ?

**Comment by derrickmehaffy** [comment]
> > I've just tested every version from v3.5.4 to v3.6.8 and cannot reproduce it.
> > This sounds like you made a major jump at some point and your model's config/routes.json still has a reference to `:_id` which we stopped using a long time ago.
> 
> May I know your system information such as OS and Node version ?

![Selection_1114](https://user-images.githubusercontent.com/8593673/132281120-27e9977b-958c-4452-832f-e63b4977d020.png)

**Comment by kevinadhiguna** [comment]
Thanks @derrickmehaffy . I ran Strapi with MongoDB using docker-compose and it worked well.

The log said that Strapi version was v3.6.8 and NodeJS version was v14.16.0.

**Comment by derrickmehaffy** [comment]
@kevinadhiguna I'd advise against starting a new project with MongoDB because we plan to drop support for it in the v4: https://github.com/strapi/strapi/issues/10186

But if you can't reproduce the issue again I'll set this as closed.

**Comment by kevinadhiguna** [comment]
Alright I really appreciate your time and help @derrickmehaffy. Also, I am truly sorry for suspecting your PR @MattieBelt 🙏

**Comment by MattieBelt** [comment]
Haha no worries @kevinadhiguna! 😉

**Comment by sadeqush** [comment]
Had the same error. Was able to reproduce and eventually solve.
The issue I was having:

routes.json

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/exams",
      "handler": "exam.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/exams/:id",
      "handler": "exam.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/exams/getOnlyActive",
      "handler": "exam.getOnlyActive",
      "config": {
        "policies": []
      }
    } .....
```


In this case, the string `getOnlyActive` would be parsed as a URL parameter as `:id ` and sent to the findOne handler. `exam.findOne({id : getOnlyActive})` would give a cast error. 

I think strapi parses the routes.json to some sort of switch/case which could cause an error like this. The solution is to simply move the findOne handler's route lower in the array. It solved the issue for me.
