### ISSUE TITLE
Cannot upload image in users table through api

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#10730]
### I have added an image field in strapi as to get profile pic of users while registration but the users registration not update API supports image as per my observation.

- When I try registration API and use form data to pass data and files.apiFieldName as we do with other content types if we have to pass multipart data, the registration API doesn't work, it always says "Please provide your password" even when i am passing the password. (Screenshot Attached) . 
- Note: Registartion works perfectly fine and does not give such error if we don't use form data and simply pass raw JSON. 
- When I try to use update user API with form data  , the API return 200 Okay result but the image still does not get updated and still is null.  (Screenshot Attached)

### Steps to reproduce the behavior

1. Create an image fields in Users (from users-permission) content-type.
2. Use the registration API {{baseUrl}}/auth/local/register or update user API {{baseurl}}/users/{{userid}}
3. Use form data and add text data json object with key "data" and add an key with name "files.image" and select type file in postman and select and image
4. Hit the api

### Expected behavior

It should add and update the image successfully just like it does with other content types

### Screenshots

![image](https://user-images.githubusercontent.com/71498747/129321883-05c5cdea-d6a4-48d9-bb66-76f09057c842.png)

![image](https://user-images.githubusercontent.com/71498747/129321238-9207cc26-7a2c-4237-8b3d-7e77a44e222f.png)

### System

- Node.js version: v14
- NPM version: v6.x.x
- Strapi version: 3.6.6
- Database: sqlite
- Operating system: Linux (CentOs)

**Comment by derrickmehaffy** [comment]
Set as a feature request as the current functionality is intended (we strip out all other relational data during registration to prevent security risks such as setting role information and we can't take into account custom relations in that logic)

**Comment by ssoftwares** [comment]
@derrickmehaffy Sir, can you suggest me alternative method or how to customize the register method in Auth.js to accept images. 

![image](https://user-images.githubusercontent.com/71498747/129433870-dbfce812-c838-4e75-84ab-b56c57acf96d.png)

Thanks & Regards
Surya Pratap

**Comment by ssoftwares** [comment]
Any update on this?

**Comment by derrickmehaffy** [comment]
@ssoftwares it's unlikely we will work on this any time soon. I marked it as a feature request but there is no ETA on when (or if) we would add this.

**Comment by MattieBelt** [comment]
Hey @ssoftwares,

Are you looking for a way to upload an image directly on registration or can the upload also be done later on in the progress (e.g. updating the user profile)?

If updating the user later on in the progress works for you, then I would recommend using a _Profile_ collection type with a relation to _User_. You then can add all the custom user fields (`address`, `name`, etc.) as well as the `image` field to _Profile_. After the initial (basic) registration, you then can update/add the profile to the user with the default endpoints which do support mulitpart requests. And on top of the create/update routes you can add a [isOwner](https://strapi.io/documentation/developer-docs/latest/guides/is-owner.html) policy that allows user to only update there own profile.

This makes the initial registration process very short.

I hope this work for you.

**Comment by derrickmehaffy** [comment]
Possible via customization, we likely won't add this to users-permissions but could be explored once we work on the replacement plugin.
