### ISSUE TITLE
Wrong error of username exist via api

### ISSUE THREAD

**Issue by nezzard** [strapi/strapi#10741]
When i'm trying to register via api, i'm get error 'Auth.form.error.email.taken', but it's not.

.includes(err.message, 'username') don't contains any username errors, because 
await strapi.query('user', 'users-permissions').create(params) throw warning
`warn Duplicate entry MongoError: E11000 duplicate key error collection: domosedka-b.users-permissions_user index: username_1 dup key: { username: "test" }`

https://github.com/strapi/strapi/blob/7a80bdaa8e4e4b194853b338a30495c8a1050f1e/packages/strapi-plugin-users-permissions/controllers/Auth.js#L515

### System

- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.6.6
- Database: Mongo
- Operating system: Win10

**Comment by kasonde** [comment]
Hi @nezzard can you confirm that this issue happens after a fresh install and fresh database? I was unable to replicate this issue.

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
