### ISSUE TITLE
Web Proxy problem when running "npx create-strapi-app"

### ISSUE THREAD

**Issue by jacquesh82** [strapi/strapi#10740]
### Describe the bug

Behind a corporate proxy, when I use these commands :

- yarn create strapi-app appname
- npx create-strapi-app appname

after choosing option 
```
npx : 143 installé(s) en 8.233s
? Choose your installation type **Custom (manual settings)**
? Would you like to use a template? (Templates are Strapi configurations designed for a specific use case) **No**
```

I get an error :
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
FetchError: request to https://api.github.com/repos/strapi/community-content/contents/templates/templates.yml failed, reason: connect ETIMEDOUT 140.82.121.6:443
    at ClientRequest.<anonymous> (/home/olaf/.npm/_npx/4153281/lib/node_modules/create-strapi-app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I try to set all this proxy config
```
export http_proxy=http://proxym-inter.compay.fr:8080
export https_proxy=http://proxym-inter.compay.fr:8080
export GLOBAL_AGENT_HTTP_PROXY=http://proxym-inter.compay.fr:8080
export HTTP_PROXY=http://proxym-inter.compay.fr:8080
export HTTPS_PROXY=http://proxym-inter.compay.fr:8080
npm config set proxy http://proxym-inter.compay.fr:8080
npm config set https-proxy http://proxym-inter.compay.fr:8080
yarn config set proxy http://proxym-inter.compay.fr:8080
yarn config set https-proxy http://proxym-inter.compay.fr:8080
git config --global http.proxy http://proxym-inter.compay.fr:8080
git config --global https.proxy http://proxym-inter.compay.fr:8080
```

### Steps to reproduce the behavior
Be behind a corporate proxy

1. just type "npx create-strapi-app appname"
2. See error

### System

- Node.js version: v14.16.0
- NPM version:6.14.11
- Strapi version: latest stable 
- Database: mongodb
- Operating system: Linux RHEL8

**Comment by derrickmehaffy** [comment]
Your proxy appears to block requests to GitHub based on:

> reason: connect ETIMEDOUT 140.82.121.6:443

![image](https://user-images.githubusercontent.com/8593673/129590691-ccdbf888-d680-494e-826e-a69960e292a9.png)

There is not much we can do in this case, I would recommend you speak to your internal IT team to allow GitHub access.

**Comment by derrickmehaffy** [comment]
> Hi everybody,
> 
> I am sorry but I have exactly same issue and everything is ok for my proxy with github.
> In fact, as I can read here : https://www.scrapingbee.com/blog/proxy-node-fetch/, node-fetch library does not seem to easy handle proxy.
> So I suppose, it is still an issue than can be fix anymore.
> Am I wrong ? 
> Indeed, thanks for excellent job for strapi 👍 
> 
> Regards

This only applies if you need to configure a proxy at the application level. If your corp VPN or something at the system/network level is handling that proxy then this should not be the cause.

**Comment by derrickmehaffy** [comment]
> > This only applies if you need to configure a proxy at the application level. If your corp VPN or something at the system/network level is handling that proxy then this should not be the cause.
> 
> I am sorry, i don't really understand what you mean by "application level", in my mind "npx create-strapi-app" command is clearly at application level. So, I suppose that this command should handle proxy like other librairies does, using npm config proxy or https-proxy variables.
> 
> No ?

Meaning you configured a proxy within npm: https://docs.npmjs.com/cli/v7/using-npm/config#https-proxy

If your corp proxy is happening at the network level (you are connected to a VPN or all your internet traffic is routed through a system that proxies the requests and blacklists certain domains, ect) then there isn't much we can do to help.

**Comment by zekidkiller** [comment]
Hi,

Sorry for the delay, I thought I give my answer.
Well, yes, I have configured npm proxy with link you provided.
And it does not work.

Is it suppose to work ?

Thanks
