### ISSUE TITLE
After adding date, cannot add relation

### ISSUE THREAD

**Issue by kadaan** [strapi/strapi#1075]
### Configuration
| Node Version  | NPM Version |     Strapi Version    | Database |           OS                     | Resolution | Browser | 
| ------------- | -------------- | ------------------ | --------- | --------------------- | ----------- | -----| 
| v9.11.1            | 5.6.0                | 3.0.0-alpha.12.0.1  | Mongo     | Os X 10.13.3 (17D47) | 2880 x 1800 | Chrome  65.0.3325.181 |

### Current behavior
After adding a date field to a new content type, adding a relation causes an error.

### Steps to reproduce the problem
Create a new content type in the Content Type Builder.  Add a date to the new content type.  Add a relation to the new content type.  Notice the error.

### Expected behavior
Adding a relation after adding a date should work.

![relation_add](https://user-images.githubusercontent.com/1904898/39465281-55ce8822-4cd7-11e8-81f8-708958b6a1ad.gif)

---

- [X] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
I think this PR https://github.com/strapi/strapi/pull/1068 will fix this issue.
