### ISSUE TITLE
Cannot find module 'estraverse' 

### ISSUE THREAD

**Issue by blogwy** [strapi/strapi#10762]
yarn strapi install documentation

yarn run v1.22.10
$ strapi install documentation
✔ Installing dependencies
Command failed: npm run build
Error: Cannot find module 'estraverse'
Require stack:
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\eslint-scope\lib\scope.js
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\eslint-scope\lib\scope-manager.js 
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\eslint-scope\lib\index.js
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\webpack\lib\optimize\ConcatenatedModule.js
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\webpack\lib\optimize\ModuleConcatenationPlugin.js
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\webpack\lib\WebpackOptionsApply.js- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\webpack\lib\webpack.js
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\strapi-admin\index.js
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\strapi\lib\commands\build.js      
- C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\strapi\bin\strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\eslint-scope\lib\scope.js:29:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\wangyu\Desktop\code\my-strapi-project\node_modules\eslint-scope\lib\scope-manager.js:28:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\eslint-scope\\lib\\scope.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\eslint-scope\\lib\\scope-manager.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\eslint-scope\\lib\\index.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\webpack\\lib\\optimize\\ConcatenatedModule.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\webpack\\lib\\optimize\\ModuleConcatenationPlugin.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\webpack\\lib\\WebpackOptionsApply.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\webpack\\lib\\webpack.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\strapi-admin\\index.js',    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\strapi\\lib\\commands\\build.js',
    'C:\\Users\\wangyu\\Desktop\\code\\my-strapi-project\\node_modules\\strapi\\bin\\strapi.js' 
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-strapi-project@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-strapi-project@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wangyu\AppData\Roaming\npm-cache\_logs\2021-08-19T15_21_14_155Z-debug.log 

> my-strapi-project@0.1.0 build C:\Users\wangyu\Desktop\code\my-strapi-project
> strapi build

Building your admin UI with development configuration ...

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

my info:
strapi: v3.6.7(Community)
node: v14.16.1
yarn: v1.22.10
system: win10 21H1

**Comment by derrickmehaffy** [comment]
Unable to reproduce, this is most likely a user environment issues. Best to move discussion over to the forum: https://forum.strapi.io

**Comment by blogwy** [comment]
> Unable to reproduce, this is most likely a user environment issues. Best to move discussion over to the forum: https://forum.strapi.io

I use npm it's ok
