### ISSUE TITLE
Text overflow on Content Type Builder list page

### ISSUE THREAD

**Issue by kadaan** [strapi/strapi#1076]
### Configuration
| Node Version  | NPM Version |     Strapi Version    | Database |           OS                     | Resolution | Browser | 
| ------------- | -------------- | ------------------ | --------- | --------------------- | ----------- | -----| 
| v9.11.1            | 5.6.0                | 3.0.0-alpha.12.0.1  | Mongo     | Os X 10.13.3 (17D47) | 2880 x 1800 | Chrome  65.0.3325.181 |

### Current behavior
The Content Type Builder list page overflows incorrectly when the page is narrow.

### Steps to reproduce the problem
With a full screen browser, navigate to the Content Type Builder list page, open Chrome dev tools, dock Chrome dev tools to the right, expand Chrome dev tools size.

### Expected behavior
The list page should overflow correctly.

<img width="1440" alt="screen shot 2018-05-01 at 12 28 25 am" src="https://user-images.githubusercontent.com/1904898/39465199-e55191ac-4cd6-11e8-984e-67c0f57521d5.png">

---

- [X] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @kadaan The same answer as your previous issue https://github.com/strapi/strapi/issues/1062#issuecomment-385624371

**Comment by kadaan** [comment]
The issue here seems to be that the height of the `li` tags which make up the list rows is fixed at 5.7rem.  One possible solution is to change this from height to min-height.  One thing that still should be fixed is specifying a min width for the table.

![min_height](https://user-images.githubusercontent.com/1904898/39562715-18d6fa9e-4e62-11e8-9cf0-012724e588c3.gif)

**Comment by lauriejim** [comment]
@soupette It's the best guy to answer you.
