### ISSUE TITLE
Encountered status 403 Forbidden while testing

### ISSUE THREAD

**Issue by lee1409** [strapi/strapi#10774]
### Describe the bug

I was trying to learn how to test the endpoint using graphql. I tried to send the request and got received with status 403. Even though I tried to get the jwt token. I realized that I did not set the permission for the public role and caused the issue. Does anyone know how to update the permission for the specific role without going through UI? 

### Steps to reproduce the behavior

Requirement: strapi-plugin-graphql

1. Follow the [guideline](https://strapi.io/documentation/developer-docs/latest/guides/unit-testing.html#install-test-tools) to setup strapi instance
2. Create a model
3. Try to query using supertest. Ex:
```
const request = require('supertest');

describe('Restaurant', () => {
  let jwt = null;
  let userData = {...};
  let mockData = {..};
  let resp = {...};

  beforeAll(async () => {
    jwt = await request(strapi.server) // app server is an instance of Class: http.Server
      .post('/graphql')
      .send(userData)
      .expect(200) // Expect response http code 200
      .then(res => res.body.data.register.jwt);
  });

  it('succeeded if create a resp', async () => {
    await request(strapi.server) // app server is an instance of Class: http.Server
      .post('/graphql')
      .set('Authorization', `Bearer ${jwt}`)
      .send(mockData)
      .expect(200) // Expect response http code 200
      .then(data => {
        expect(data.text).toBe(JSON.stringify(resp)); // expect the response text
      });
  });
});
```
```
    + {"errors":[{"message":"Forbidden","locations":[{"line":2,"column":7}],"path":["createFood"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Forbidden"},"headers":{}},"message":"Forbidden"}}}],"data":{"createFood":null}}
```

### Expected behavior

```
{"data":{...}}}}
```
### System

- Node.js version: v14.17.4
- NPM version: 6.14.14
- Strapi version: 3.6.6
- Database: sqlite
- Operating system: Ubuntu 20.04 (WSL)

**Comment by kasonde** [comment]
Hi, @lee1409  thanks for the question. I'm closing this here since it's not an issue but a question that is perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.
