### ISSUE TITLE
Numerical Field does not properly show value Zero

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1077]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: v5.6.0
- **Strapi version**: 12.0.1
- **Database**: MongoDB v3.6.4
- **Operating system**: Ubuntu Server 16.04 LTS

**What is the current behavior?**
When using numerical field (Int, Dec, or Float) if a value of `0` is entered the content manager will show a `-` instead of the value. Also while editing a record if you place any value in the text field then delete it, the value will default to `0`

**Steps to reproduce the problem**
Add a numerical field to any endpoint, place a `0` in the field, then return to the content manager.
Note that if the column is displayed in the content manager it will show `-` instead of `0`. Does not affect the API as it will return the proper value.

Second issue, attempt to modify the record and delete the value of the numerical field, which after clicking away it will auto-default back to `0` again. While not breaking, in some cases you may not want a default value of `0` and instead want a default value of `null`

**What is the expected behavior?**
Content Management should display the exact value and not assume that `0` is equal to `null`
Numerical fields should not assume that a default numerical value is `0` and should default to `null`

**Suggested solutions**
Unsure as I'm not sure how the content management plugin determines default values. Recommend adding the option to set a default value on a numerical field to null.

- [x] I'm sure that this issue hasn't already been referenced

- Possible related issues/fixes:
https://github.com/strapi/strapi/issues/670
https://github.com/strapi/strapi/commit/f5571af1c17fc27fb3bda3a208826920a9a7d02c

Issue is likely a "Quality of Life" fix and not a breaking bug

**Comment by lauriejim** [comment]
Hello @derrickmehaffy , thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate it! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md
