### ISSUE TITLE
strapi upload plugin configuration not loaded

### ISSUE THREAD

**Issue by yoanne2x** [strapi/strapi#10777]
### Describe the bug

After configuring GCP bucket provider for media upload, Strapi configuration still uses "local" provider.

### Steps to reproduce the behavior

1. create new strapi app
2. add gcp provider https://www.npmjs.com/package/strapi-provider-upload-google-cloud-storage
3. add plugin.js under ./config/plugin.js with configuration:

`
module.exports = {
  upload: {
    provider: 'google-cloud-storage',
    providerOptions: {
      bucketName: '<BUCKET NAME>',
      publicFiles: false,
      uniform: false,
      serviceAccount: '<GCP SA KEY>'
    }
  }
}
`

4. upload image, image is still using local /upload folder
5. export strapi config, no provider seem to be configured 

### Expected behavior

should use GCP provider to upload media

### System

- Node.js version: 14.17.4
- YARN version: 1.22.11
- Strapi version: 3.6.6
- Database: postgres
- Operating system: mac

**Comment by MattieBelt** [comment]
Hey @yoanne2x,

You probably missed an char, it needs to be `plugins.js` with a plural '**s**'.
![image](https://user-images.githubusercontent.com/31662805/130424090-720bc960-df5e-415c-92f4-31756b31c9a0.png)

**Comment by yoanne2x** [comment]
argh!!!!.... thanks for that!
