### ISSUE TITLE
Blocked user can still login by using the forgot password feature 

### ISSUE THREAD

**Issue by hanguyenmgt** [strapi/strapi#10776]
### Describe the bug

Blocked user can still login by using the forgot password feature 
### Steps to reproduce the behavior

1. Open the forgot password page
2. Submit with an email of a blocked account
3. Click on the reset password link from the reset password email
4. Enter a valid password and confirm password
5. Submit and check

### Expected behavior

Blocked user shouldn't be able to send forgot password request

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.3
- NPM version: 6.14.11
- Strapi version: v3.6.6
- Database: postgre
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
Confirmed on v3.6.7
