### ISSUE TITLE
Cannot access nested component data inside a relationship stored inside a dynamic zone of a component. 

### ISSUE THREAD

**Issue by aqilusman45** [strapi/strapi#10778]
I've come across a strange issue when making relations, and was looking for some guidance.
I have a collection type in which I've stored a dynamic zone. The dynamic zone has a component that holds a relationship to another component. The other component holds a nested component, while primitive data fields such as text, rich text etc are available. The problem I'm facing is that when I query the component, I'm able to get all the data except the nested component inside that relation. 
Below are some images for reference

This is the main blog page model I've created, it has a dynamic zone with a component that has a relation field.
![blog_page_model](https://user-images.githubusercontent.com/46997126/130428890-c1284162-0556-4fd8-a2b0-754c95bea702.PNG)

This is an instance of the blog page type, where I have connected the relation with relevant post/section
![blog_page_instance](https://user-images.githubusercontent.com/46997126/130429065-09be76f6-65c9-4807-ab9a-7e82bb65a5b0.PNG)

This is the FAQ content model type, within this I have another repeatable component called `questionList`.
![FAQ_Model](https://user-images.githubusercontent.com/46997126/130429299-e4cb858a-b80f-4579-8e5d-96f3f3ba53a3.PNG)

This is the instance of the FAQ content model
![FAQ_Page](https://user-images.githubusercontent.com/46997126/130429378-a878912a-0baf-4589-ad10-7609a944a9a8.png)

When I query the blog pages, I only the primitive data types inside the faq data, I can't seem to acccess the list elements
![gql_query](https://user-images.githubusercontent.com/46997126/130429398-608c6581-c223-46cd-8702-3cc59e480557.png)

I need to be able to access the list elements inside the faq data. Any ideas or suggestions?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7454
