### ISSUE TITLE
Search in collection with "&" character

### ISSUE THREAD

**Issue by tamerkalieh** [strapi/strapi#10780]
### Describe the bug

After creating a collection on Strapi, a search within this collection is not possible, when the search string contains the "&" character.

### Steps to reproduce the behavior

1. Go to any collection.
2. Create an item where the name includes a "&" character.
3. Click on the search and try to search for that item.

![Bildschirmfoto 2021-08-23 um 13 29 45](https://user-images.githubusercontent.com/17314534/130440167-f2f6509e-df01-4802-b6b5-f2c8e29b6f3d.png)

https://domain.com/content-manager/collection-types/application::shops.shops?page=1&pageSize=10&_sort=name:ASC&_q=cars&whatever=

I was searching for "cars&whatever". And it looks like strapi is taking apart the search string and taking the substring after the "&" as another query parameter

![Bildschirmfoto 2021-08-23 um 13 30 16](https://user-images.githubusercontent.com/17314534/130440224-7da7ef35-69a0-4447-b6ae-f9a81bc13268.png)

### Expected behavior

The item with name === cars&whatever is found by the search

### System

- Node.js version: 14.16.1
- Yarn version: 1.22.4
- Strapi/Strapi-Admin version: 3.6.5
- Database: Sqlite

is there any way how I can fix that issue?

**Comment by kasonde** [comment]
For extra information, the query string seems to add more params the more it makes requests (after the debounce timer has elapsed and the search query is made). 

![Screenshot 2021-08-23 at 3 03 33 PM](https://user-images.githubusercontent.com/13610895/130452171-8fdaada5-6261-454e-8c1a-9d026a7a947c.png)

**Comment by yanniskadiri** [comment]
For whoever will tackle this issue, it should be tested for all the searches and filters in the CM, Upload plugin and Settings.
