### ISSUE TITLE
"Entries per page" doesn't change the pageSize

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#10796]
### Describe the bug

Changing the setting `Entries per page` inside any collection type doesn't change the pageSize and so doesn't affect the list view.

### Steps to reproduce the behavior

1. Create Strapi project
2. Create collection type
3. enter more than 10 entries
4. Change the `Entries per page` setting
5. Check your list view

### Expected behavior

Change the pageSize and list view

### Screenshots

`Entries per page` are set to 20:
![Screenshot from 2021-08-25 10-06-16](https://user-images.githubusercontent.com/45003352/130753670-d83f8e2a-ea99-45e6-a42d-268aaa81965d.png)

Still only 10 of 15 entries are shown per page:
![Screenshot from 2021-08-25 10-06-35](https://user-images.githubusercontent.com/45003352/130755536-19aa3ae8-61a0-44c6-9329-cc824c70825d.png)

And then another 5 on the next page:
![Screenshot from 2021-08-25 10-06-47](https://user-images.githubusercontent.com/45003352/130755479-abe0e753-ca28-4d23-9b2b-a540fd2528b6.png)

### System

- Node.js version: 14.15.4
- NPM version: 6.14.10
- Strapi version: 3.6.8
- Database: SQLite
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
No response to the issue, so I'm going to go ahead and close this for now.
