### ISSUE TITLE
Customise Specific Collection type layout

### ISSUE THREAD

**Issue by SujayPrabhu96** [strapi/strapi#10798]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Customise the specific collection type layout.

### Why is it needed?

I want to navigate to a local plugin from a collection type. To achieve this, I need to modify layout by making changes to `strapi-plugin-content-manager` and modifications apply to layout of all the collection types.

### Suggested solution(s)

Add link/button to the collection type page to navigate to the plugin

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by soupette** [comment]
In your injected component you can apply the following logic in order to display it in a specific collection type:


```
import { useRoutMatch } from 'react-router-dom';

const MyCompo = () => {
  const { params: {  uid } = useRouteMatch(`/content-manager/:kind/:uid/:id`);
  console.log({ uid });
  
  if (uid !=== 'application::article:article') {
    return null;
  }


  return 'My-compo';
};
```

**Comment by derrickmehaffy** [comment]
This should be solved in v4 with our injection zones
