### ISSUE TITLE
Language fallback when language not yet maintained

### ISSUE THREAD

**Issue by mnuernberger** [strapi/strapi#10806]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Currently, when requesting a locale from Strapi not yet maintained, an empty response is being returned. It would be great if one could configure a fallback language.

### Why is it needed?

It is needed in order to dynamically pull data from CMS and not having issues when a certain language is not available.

### Suggested solution(s)

Possibility to configure a fallback language for requests on non-existent locals.

**Comment by stephent** [comment]
It would also be useful to have the ability to return content for a fallback language even when the specified locale IS available. E.g. I have help articles for locale ```en``` and have a sub-set of them localized for ```en-US```. I would like to be able to pull all articles for ```_locale=en_US``` but also specify ```_fallbackLocale=en``` (or similar). If an article exists for ```en-US``` return that, if not, return the ```en``` version.

At present I don't see any easy alternative to doing multiple API calls and de-duping the results to implement this type of behaviour.

**Comment by 4n4n4s** [comment]
I agree having the default language/a configurable language as fallback would is a must. 
Just tested v4 beta and it looks like that the option does not exist yet unfortunately.

Let's hope we can add this soon that would make strapi a lot better.

Also worth mentioning for v4 beta the locales are accessed using "locale" and not "_locale".
Example: http://localhost:1337/api/some-collections?locale=en

**Comment by sandoche** [comment]
It seems that it has been or will be implemented according to this post:
https://strapi.io/blog/monthly-update-november-2020

```
We are entering the latest phase before starting the development in mid-November. The feature will include a large scope of functionalities such as:
...
- Default fallback (always returns the default local entry value).
```

**Comment by TechQuery** [comment]
Why don't Strapi API support [`Accept-Language` header][1] directly?

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/language-fallback-when-language-not-yet-maintained
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
