### ISSUE TITLE
A hardcoded BCrypt cost factor of 10 is insecure by default

### ISSUE THREAD

**Issue by meagar** [strapi/strapi#10802]
### Describe the bug

A BCrypt cost factor of 10 is too low, and has been too low for nearly a decade. On modern hardware this makes hashed passwords susceptible to bruteforce attack.

This value has been hardcoded into your software for at least 4 years, meaning you've chosen a too-low cost factor for your users for every hashed password you've generated. Having chosen too low a value, it's hard to actually fix this as the original passwords are lost and only the hashes remain.

Additionally, hardcoding this is incorrect. The whole point of BCrypt is that you tune the cost factor over time, increasing it to maintain a relatively constant time for generating/checking hashes. Hardcoding this prevents users from tuning this value.

Ideally one would pick a cost factor that is as high as can be tolerated, something on the order of 100ms to 250ms per hash operation. You would increase the cost factor over time to maintain roughly that same amount of time consumption on each hash operation. The current cost factor on modest hardware consumes something like 0.05ms per hash, far far too low.

A fix to use a new, adjustable cost factor should also include codepaths to migrate to the new cost factor on login for existing users, replacing the cost-10 hashes with the higher cost factor hashes.

https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi-admin/services/auth.js#L12

Lots has been written about this (specifically that `10` is too low) going back many years:

- https://labs.clio.com/bcrypt-cost-factor-4ca0a9b03966
- https://security.stackexchange.com/questions/17207/recommended-of-rounds-for-bcrypt
- https://wildlyinaccurate.com/bcrypt-choosing-a-work-factor/

**Comment by derrickmehaffy** [comment]
We fall roughly right in the middle in terms of speed and security and since this really relates to brute force attacks, of which we have default rate-limits I don't see how increasing the work factor will provide too much of a benefit over the drawbacks.

Gonna close this for now but if others want to chime in on the discussion please feel free.

**Comment by meagar** [comment]
@derrickmehaffy Everything you said is wrong. If that's actually your belief, why are you using bcrypt, and not SHA512?

**Comment by derrickmehaffy** [comment]
I will ignore the personal attacks against myself here as I can tell you are clearly passionate about security (I myself am as well).

While I don't think it's a good idea to force all users up to a new factor level, allowing user configuration of the option I think is fair. Are you open to submitting a PR @meagar?

**Comment by jerodfritz** [comment]
I vote for increasing the work factor to at least 11.   Integration with modern fintech platforms will require this.  For example, https://www.dwolla.com/p/customer-integration-guide/#section-08a
