### ISSUE TITLE
Graphql Boolean argument is being converted to a string

### ISSUE THREAD

**Issue by mrmadhat** [strapi/strapi#10801]
### Describe the bug

I have a custom graphql query that accepts a boolean as an argument. When I try to work with the value in my controller it is being converted to a string.

### Steps to reproduce the behavior

1. Create a content type
2. Add the code below
3. Open http://localhost:1337/graphql and call with a boolean argument
4. See output showing string from console.log

### Screenshots

Graphql playground correctly only accepts boolean values

![image](https://user-images.githubusercontent.com/19492281/130806793-1ef4d92b-8870-490e-afbf-d0d3a5c9891d.png)

Despite this it shows as string when passing `true` or `false`

![image](https://user-images.githubusercontent.com/19492281/130807376-4877ccd0-d5fe-4a53-aff5-0604177ae221.png)

### Code snippets

schema.graphql.js

```
module.exports = {
  definition: `
    type Duration {
      start: String!
      end: String!
    }

    type GetAvailabilityForDate {
      access: Duration
      unavailable: [Duration]
    }

    input GetAvailabilityForDateData {
      spaceId: ID
      date: String!
      findClosestAvailable: Boolean
      findClosestDaysInFutureLimit: Int
    }

    input GetAvailabilityForDateInput {
      data: GetAvailabilityForDateData
    }
  `,
  query: `
  getAvailabilityForDate(input: GetAvailabilityForDateInput!): GetAvailabilityForDate!
  `,
  resolver: {
    Query: {
      getAvailabilityForDate: {
        description: "Returns availability of space",
        resolverOf: "application::spaces.spaces.getAvailabilityForDate",
        resolver: "application::spaces.spaces.getAvailabilityForDate",
      },
    },
  },
};

```

spaces/controllers/spaces.js

```
module.exports = {
  async getAvailabilityForDate(ctx) {
    const data = ctx.query?._input ? ctx.query._input.data : ctx.query;

    let {
      spaceId,
      date,
      findClosestAvailable,
      findClosestDaysInFutureLimit = 7,
    } = data;

    console.log(typeof findClosestAvailable) // string
  }
}
```

### System

- Node.js version: 14.16.0
- Yarn version: 1.22.10 
- Strapi version: 3.6.3
- Database: Postgres
- Operating system: Macos Big Sur

**Comment by kasonde** [comment]
Closed as this has been fixed in v4
