### ISSUE TITLE
[I18N] improve simplified Japanese translation

### ISSUE THREAD

**Issue by matsubaraDaisuke** [strapi/strapi#10811]
### Improve simplified Chinese translation.
Includes translation for strapi-admin and the translations for the following plugins：

- strapi/packages/strapi-plugin-email/admin/src/translations/ja.json

### How to test it?

None

**Comment by kasonde** [comment]
Hi 👋
We now have released the v4. As of now, the v3 is in maintenance mode for 6 months. We will only be fixing critical and security issues on v3 from now on.
I will go ahead and close this Issue. Thank you for contributing to Strapi 🔥
