### ISSUE TITLE
Failed to define custom graphql scalar

### ISSUE THREAD

**Issue by pzhyy** [strapi/strapi#10818]
### Describe the bug

I want to hide my database serial id (all tables), and hope to achieve this by overwriting the scalar ID of graphql. 
So far, I haven't succeeded, can anyone tell me how to do it?

### Steps to reproduce the behavior

1. Create `./extensions/graphql/config/schema.graphql.js` file
2. Fill in the following content
  ```js
  const graphql = require('graphql')
  const Hashids = require('hashids')

  const hashids = new Hashids('salt-xxx', 8)

  console.log('--- Code is executed ---')

  const idScalar = new graphql.GraphQLScalarType({
    name: 'ID',
    description: 'ID custom scalar type',
    serialize(value) {
      return hashids.encode(value) // Convert database id to hash id
    },
    parseValue(value) {
      return hashids.decode(value)[0] // Convert hash id to database id
    },
    parseLiteral(ast) {
      if (ast.kind === graphql.Kind.STRING) {
        return hashids.decode(ast.value)[0] // Convert hard-coded AST string to database id
      }
      return null
    },
  })

  module.exports = {
    definition: `
      scalar ID
    `,
    resolver: {
      ID: idScalar,
    },
  }
  ```
3. Startup project and the console output is as follows
  ```bash
  > strapi develop

  --- Code is executed ---
  --- Code is executed ---
  [2021-08-28T02:49:58.280Z] debug ⛔️ Server wasn't able to start properly.
  [2021-08-28T02:49:58.282Z] error TypeError: Cannot read property 'startsWith' of undefined
      at getActionDetails (/Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/utils.js:154:16)
      at getPolicies (/Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/resolvers-builder.js:179:7)
      at buildQuery (/Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/resolvers-builder.js:94:38)
      at /Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/schema-generator.js:188:44
      at Array.reduce (<anonymous>)
      at /Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/schema-generator.js:171:41
      at Array.reduce (<anonymous>)
      at buildResolvers (/Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/schema-generator.js:165:33)
      at Object.generateSchema (/Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/services/schema-generator.js:49:49)
      at Object.initialize (/Users/xxx/Documents/projects/yyy/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:76:74)
      at /Users/xxx/Documents/projects/yyy/node_modules/strapi/lib/hooks/index.js:37:28
  ```

### Expected behavior

Expect this feature to be available.

The official document mentioned [here](https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#customize-the-graphql-schema):

> If you want to define a new scalar, input or enum types, this section is for you. 

But there is no corresponding example.

### Code snippets

According to the error stack, I found some problems, which may be caused by it.

1. The instance of GraphQLScalarType is breaked

Source code is [here](https://github.com/strapi/strapi/blob/v3.6.8/packages/strapi-plugin-graphql/services/utils.js#L47)

```js
const diffResolvers = (object, base) => {
  let newObj = {};

  Object.keys(object).forEach(type => {
    Object.keys(object[type]).forEach(resolver => {
      if (type === 'Query' || type === 'Mutation') {
        if (!_.has(base, [type, resolver])) {
          _.set(newObj, [type, resolver], _.get(object, [type, resolver]));
        }
      } else {
        _.set(newObj, [type, resolver], _.get(object, [type, resolver]));
      }
    });
  });

  return newObj;
}
```

2. This condition failed

Source code is [here](https://github.com/strapi/strapi/blob/v3.6.8/packages/strapi-plugin-graphql/services/schema-generator.js#L145)

```js
if (graphql.isScalarType(resolvers[type])) {
  return acc;
}
```

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- Strapi version: 3.6.8
- Database: mysql
- Operating system: macos

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by u382514** [comment]
I believe this should be reopened as it's eluding to lack of documentation with a valid example of creating a scalar in Strapi even though it's mentioned in said documentation. 

You do have a documentation tag that I see is used. Can you please reopen with the idea of "Updating your documentation with a valid example of creating custom scalars"?

**Comment by derrickmehaffy** [comment]
> You do have a documentation tag that I see is used. Can you please reopen with the idea of "Updating your documentation with a valid example of creating custom scalars"?

That's a relic from when docs where in this repo, see: https://github.com/strapi/documentation
