### ISSUE TITLE
Routing from plugin

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#1082]
**What is the expected behavior?**

I'm working on a documentation plugin.  Ideally I want the base route to show the documentation depending on user permissions.  In other words, I would like the docs to live here:

http://example.com/

rather than here:

http://example.com/admin/plugins/plugin-name/

I may be able to implement this as a configurable feature and submit a PR, but need some hints about the routing.

How does the router get bootstrapped?

---

- [X] I'm sure that this issue hasn't already been referenced

**Comment by soupette** [comment]
Well, in order to change the routing you have to create a new `Route` in the `AdminPage` container and modify the `LeftMenuLink` component so it doesn't redirect to `plugins/:pluginID`.

**Comment by lauriejim** [comment]
@nurikabe Can you please give us an update about this issue?

**Comment by nurikabe** [comment]
@lauriejim I think we can close this.  I can see now that I can define any public route from basically any `routes.json` definition file.

I'm blocked by https://github.com/strapi/strapi/issues/1128.  If I can figure that out then I can create arbitrary routes outside of admin that allow access depending on admin authentication state.
