### ISSUE TITLE
Querying element by ID in GraphQL always returns the first element. 

### ISSUE THREAD

**Issue by diogoviveiros** [strapi/strapi#10820]
### Describe the bug

When running the following query in GraphQL: 
```
query GetArticle($id: ID!){
    article(id: $id , publicationState:LIVE){
        id,
        published_at,
        description
    }

}
```

Where the schema is: 
`type Query {
  article(id: ID!, publicationState: PublicationState): Article`

Always gives me the first element where id is 1, no matter the id parameter that I try to feed it. You can see that in the image below, where I ask for the article where id is 2, but it only gives me the first one. The output is exactly the same no matter what ID I provide it, whether it be 3, 4, 5, etc. 

![image](https://user-images.githubusercontent.com/11295855/131223615-31218265-2a1e-4824-bba9-686f9b9c9bab.png)

### Steps to reproduce the behavior

1. Use the default blog template
2. Go into GraphQL playground
3. Use the GetArticle query with any parameter besides id:1
### Screenshots

![image](https://user-images.githubusercontent.com/11295855/131223615-31218265-2a1e-4824-bba9-686f9b9c9bab.png)

### Code snippets
```
query GetArticle($id: ID!){
    article(id: $id , publicationState:LIVE){
        id,
        published_at,
        description
    }

}
```

`type Query {
  article(id: ID!, publicationState: PublicationState): Article`

### System

- Node.js version: 12.21.0
- NPM version: 7.15.0
- Strapi version: 3.6.5
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Can't reproduce on v3.6.8: https://www.loom.com/share/b73df06d2bd04413ae01ee3ec04439c4

**Comment by diogoviveiros** [comment]
What should I do then? Any theories on what may be happening?

**Comment by derrickmehaffy** [comment]
> What should I do then? Any theories on what may be happening?

You must have done some kind of modification that is causing the issues. You can try to update to the latest Strapi version but without enough information to reproduce the issue there isn't much I can offer here.

**Comment by diogoviveiros** [comment]
I have no modifications, I am just using the base template

**Comment by derrickmehaffy** [comment]
> I have no modifications, I am just using the base template

I would suggest updating to the latest version.

**Comment by magruder85** [comment]
@diogoviveiros 
Are you using the starter blog template? I encountered this bug by reproducing like so:

System: NodeJS 14.17.6, Mac OS X  11.5.2, Strapi 3.6.8
1. Start a gatsby template: "npx create-strapi-starter my-project gatsby-blog"
2. Go to graphQL playground
3. Execute GetArticle query from comment 1.

I notice in the console log the following on every query:

warn The value of field: 'slug', in your where filter, is undefined.

It's probably got something to do with the issue, I imagine. I do not get this error when I run strapi as a quickstart and create my own content type, similar to what @diogoviveiros  did. I think this is bugged within the starter blog template only, but I would not know where to send this issue.

**Comment by derrickmehaffy** [comment]
@magruder85 can you link to the template you used to reproduce the issue?

**Comment by magruder85** [comment]
@derrickmehaffy 

I followed the instructions on this guide:
https://strapi.io/starters/strapi-starter-gatsby-blog
npx create-strapi-starter my-project gatsby-blog

When strapi started, I ran the query against the GraphQL URL at http://localhost:1337/graphql.

**Comment by diogoviveiros** [comment]
Hello, I can confirm that I am using the start blog template. Should I just start from scratch and this issue will be avoided all together?

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
