### ISSUE TITLE
Setting for remove empty fields

### ISSUE THREAD

**Issue by SamanFekri** [strapi/strapi#10847]
## Feature request
Do not return empty fields
### Please describe your feature request

- [] **I have created my request on the Product Board before I submitted this issue**
- [] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I need a setting when I put an empty string the field doesn't show in the response.

### Why is it needed?

Because Empty sometimes has a different meaning than the empty string

### Suggested solution(s)

put a setting in content-type builder if the field is empty remove the field from response

**Comment by derrickmehaffy** [comment]
Not something we will implement, marking as closed
