### ISSUE TITLE
Strapi 3.6.8 running under pm2 restarting under user load

### ISSUE THREAD

**Issue by mikenowakme** [strapi/strapi#10856]
When my users navigate around the admin interface to view or update content, our instance of Strapi periodically just restarts. On the user side, they see a spinning load animation indefinitely. In the logs, I see no error, just a restart.

We are running on a virtual RedHat 7 server with the MySQL database on a separate server.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
