### ISSUE TITLE
Couldn't configure the view in Users (from user-permission)

### ISSUE THREAD

**Issue by KogayIrina** [strapi/strapi#10855]
### Couldn't configure the view in Users (from user-permission)

I couldn't configure the view in Users collection here: content-manager/collectionType/plugins::users-permissions.user/configurations/edit. I got the error {“statusCode”:400,“error”:“Bad Request”,“message”:{“name”:“validationError”,“errors”:[“settings.defaultSortBy must be one of the following values: id, email, confirmed, blocked, role, username, createdAt, updatedAt”]},“data”:{“name”:“validationError”,“errors”:[“settings.defaultSortBy must be one of the following values: id, email, confirmed, blocked, role, username, createdAt, updatedAt”]}}.
I tried to fix it and then I found the guy with a similar problem: https://forum.strapi.io/t/cant-save-admin-configuration-for-users-permissions-plugin/4558
When I removed my DB, I tried to configure the view again and it worked. So, why this plugin works so weird?

### Steps to reproduce the behavior

1. Go to Content-Types Builder-> 'Users(from user-permission)' (you must have several users created)
2. Click on 'Configure the view'
3. Rename Label
4. See error in the console

### Expected behavior
error {“statusCode”:400,“error”:“Bad Request”,“message”:{“name”:“validationError”,“errors”:[“settings.defaultSortBy must be one of the following values: id, email, confirmed, blocked, role, username, createdAt, updatedAt”]},“data”:{“name”:“validationError”,“errors”:[“settings.defaultSortBy must be one of the following values: id, email, confirmed, blocked, role, username, createdAt, updatedAt”]}}

### System

- Node.js version: v14.17.0
- NPM version: 7.20.3
- Strapi version: 3.6.8
- Database: MongoDB 3.6.11
- Operating system: kubuntu

### Additional context
I removed /extensions/users-permissions/documentation/1.0.0/users-permissions-Role.json and extensions/users-permissions/documentation/1.0.0/users-permissions-User.json for commit, but these files were recreated after the new launch of strapi

**Comment by derrickmehaffy** [comment]
Unable to reproduce on v3.6.8

https://www.loom.com/share/f33fb20fc1d644c9afa3cde76388904a

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
