### ISSUE TITLE
chnage image file extension

### ISSUE THREAD

**Issue by sinafath** [strapi/strapi#10854]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

average WebP file size is 25%-34% smaller compared to JPEG file size.
i need a way to save JPEG files as WebP in media library

### Why is it needed?

for better performance

### Suggested solution(s)

N/A

### Related issue(s)/PR(s)

N/A

**Comment by derrickmehaffy** [comment]
Media conversion is probably something that should happen before Strapi or through a more robust provider system, not something we will likely work on in the near future
