### ISSUE TITLE
OAuth Apps & Personal access tokens

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1086]
**What is the expected behavior?**

As we are creating APIs... It is very likely that many of us want to offer these APIs to the public. It would be great to have a plugin that allows registered users to create OAuth Apps & Personal access tokens.

Example with GitHub:
* OAuth Apps: https://github.com/settings/developers
* Personal access tokens: https://github.com/settings/tokens

---

- ✅ I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @abdonrd, it's a commun usage of APIs you are right.

Anyone feel free to develop this plugin. Not a priority for us now.
Start here: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by hbakhtiyor** [comment]
would be nice to see in strapi

**Comment by juji** [comment]
+1

in addition, access token can have roles assigned to it. So role-based rules will apply.

**Comment by deevolutionism** [comment]
why is something like this not a priority? Seems to me like a core feature of any headless CMS

**Comment by derrickmehaffy** [comment]
@deevolutionism Strapi has a small team and a lot to work on. I'm sure they would love to see a PR for it.

**Comment by lauriejim** [comment]
As said @derrickmehaffy , we are a really small team. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by deevolutionism** [comment]
Sure, I'd be happy to help out with this. I'm not 100% sure where this feature would be implemented, though. Would this fit in as part of the users + permissions plugin? Or would this be a core feature of strapi? Or its own standalone plugin?

**Comment by Aurelsicoko** [comment]
@deevolutionism IMHO, it should be part of the Users & Permissions plugin. All the authentication part is handled by the plugin itself. We have to keep the core as simple as possible. It could happen that some users are using Strapi without any authentication system (without the Users & Permissions plugin) so it's enough to justify that the `API Key` logic should be inside the plugin.

**Comment by deevolutionism** [comment]
@Aurelsicoko OK - well i propose perhaps adding a 5th tab to the roles & permissions admin panel, perhaps labeled "Developer Access" or something along those lines. In that panel there could be sections for generating different access tokens: a section for generating Personal Access Token, and a section for generating tokens for OAuth Apps. Does this seem like the right direction?

**Comment by Aurelsicoko** [comment]
Sounds good to me! It could also be in the `Advanced Settings` section but let's go with a new tab :)

**Comment by Aurelsicoko** [comment]
I've created a new card on our public portal (see https://portal.productboard.com/strapi/c/40-personal-access-token). Can you give me more insights to make sure I'll have enough information to understand the use cases?

Since we're considering to implement this feature, I'm closing this issue. We are moving all the features requests on Product Board.

**Comment by abdonrd** [comment]
@Aurelsicoko I think GitHub is the best example: https://github.com/strapi/strapi/issues/1086#issue-319568700
