### ISSUE TITLE
Federated GraphQL broken out of the box

### ISSUE THREAD

**Issue by dwelch2344** [strapi/strapi#10862]
## Bug report

Federated GQL is a pretty hard win out of the box. In theory it works, but even with just the `QuickStart` project we run into:
* Failures due to `upload` and `user-permissions` not playing nice if you disable `Shadow CRUD`
* Inability to mark custom types with `@keys(fields: ... )` - either the decorator is missing or declared twice (if you define it yourself) 
* Breakage from `Types.addPolymorphicUnionType(...)` for custom types, again due to lack of decorators

### Steps to reproduce the behavior

1. Create a new project: `npx create-strapi-app my-project --quickstart`
2. Add GraphQL: `npx strapi install graphql`
3. Enable GQL Federation and disable Shadow CRUD in `config/plugins.js`
```
module.exports = {
  graphql: {
    shadowCRUD: false,
    apolloServer: {
      tracing: false,
    },
    federation: true
  }
}
```
4. Try to start: `npm run develop`

### Expected behavior

Server turns on with federation magic!

### Proposed solution

In short: rework how schemas are generated, and provide a mechanism to filter what schemas are combined.

I took a stab at reworking how/when Federation is taken into consideration when generating schemas, and got most of the way to a solution with the decorators not existing issue. But the plugins were another scenario (and I bet this only cascades with more graphql-aware plugins in a project. 

I took a few attempts at using hooks / overrides to make the `upload` and `users-permissions` plugins play nicer, but there's not really a way to do so (partially because even changing the config in an earlier hook doesn't matter, since `strapi-plugin-graphql` loads the files again directly from the FS in it's `beforeInitialize` hook). So I've opened a PR with a very simple `skippedSchemas` property that allows you to filter our schemas from either `apis`, `plugins`, or `extensions`.

It might be nicer to allow the plugins themselves to be Shadow CRUD aware, but at the end of the day having the filter is a nice escape hatch for any scenario. 

### Code snippets

I'm opening a PR

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- Strapi version: 3.6.8
- Database: Postgres 13
- Operating system: Mac OS X 

### Additional context

Opening a PR for this - will update description with it here.

**Comment by derrickmehaffy** [comment]
@dwelch2344 thanks for opening this, keep in mind that we are currently under a [community pr change freeze](https://github.com/strapi/strapi/issues/10695) and we are completely rewriting the GraphQL plugin in v4 so I'm not if it's worth it to focus on a PR for the v3 and we should look at this again once v4 is out.

**Comment by dwelch2344** [comment]
Thanks for heads up @derrickmehaffy - new to community so hadn't seen that. 

Would be interested in collaborating on the GraphQL side as I have a lot of federated experience and an active use case. What's the best way to get looped in? I don't see anything specific on Discord, but just realized there might also be a slack...

**Comment by derrickmehaffy** [comment]
> Thanks for heads up @derrickmehaffy - new to community so hadn't seen that.
> 
> Would be interested in collaborating on the GraphQL side as I have a lot of federated experience and an active use case. What's the best way to get looped in? I don't see anything specific on Discord, but just realized there might also be a slack...

The only Slack that exists now is Strapi's internal company slack. The community one was shutdown in favor of Discord.
Regarding GraphQL, this is the refactoring PR for v4: https://github.com/strapi/strapi/pull/10799

I haven't seen any discussions about federation, but in my previous experience it's a very niche usage of the feature hence why it may not be quite up to par with what you expect. (Very few are actually using it, I only know of one customer who is. Not sure in the community)

**Comment by aloulouamine** [comment]
Hello Guys,
After stable release, is there any plan to enable GQL Federation ?

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/add-graphql-federation-v4
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
