### ISSUE TITLE
Getting 200 from malicious get for .env

### ISSUE THREAD

**Issue by cipiasentini** [strapi/strapi#10879]
### Describe the bug

I've just witnessed on the debug console of strapi how some malicious request got through and got the .env respose 200
`[2021-09-03T12:59:33.493Z] debug GET .env (2 ms) 200` this was the only one which response code was 200, there were a lot of trials for getting other paths of .env file.

I would first like to know how can a GET request for .env was made? If I try to make it myself (ie. localhost/.env) on the debug console I get a `[2021-09-03T12:59:33.493Z] debug GET /.env (2 ms) 404` response. And if possible a way to patch it.

### System

- Node.js version: v12.20.1
- NPM version: 6.14.10
- Strapi version: v3.6.3
- Database: mongodb
- Operating system: linux

**Comment by derrickmehaffy** [comment]
@cipiasentini thank you for this, we are investigating right now to see if this is even possible.

**Comment by derrickmehaffy** [comment]
Can you provide more logs of the requests that were made?

**Comment by kasonde** [comment]
Hi @cipiasentini could you also provide deployment information (if possible) for that said Strapi application? Information like what operating system, what reverse proxy was used if any and other information related to the deployment that can be shared.

**Comment by derrickmehaffy** [comment]
@cipiasentini can you please include a copy of your package-lock.json or yarn.lock

**Comment by derrickmehaffy** [comment]
There should be no way to make that request, we are unable to reproduce it without more information.

**Comment by cipiasentini** [comment]
There are no more logs to provide. The only logs related to the issue is were `[2021-09-03T12:59:33.493Z] debug GET .env (2 ms) 200`. Regarding the infrastructure, I'm using docker-compose to run strapi with the sample `docker-compose.yml` file that's on the official documentation. I'm  serving it using `strapi develop` command. The package-lock.json is the following one [https://gist.github.com/cipiasentini/19fc332fbbb36e9b76605202a65dbb80](gist)

**Comment by derrickmehaffy** [comment]
Any upstream network logs from Nginx? Any other failed attempt logs.

Seriously anything and everything you have could help.

We really want to make sure we aren't missing something. This could be critical.

**Comment by cipiasentini** [comment]
I'd be glad to provide any further information, please let me know where can I get those nginx logs? or any other logs required where do I get them from.

Any other failed attempt logs. -> there were as mentioned a lot of other failed attempts (mainly because they were non existent paths like /public/.env) but the successful 200 response for .env path (which I cannot reproduce either because if I do a GET to `url/.env` I get a `debug GET /.env (2 ms) 404` which is to be expected.

**Comment by derrickmehaffy** [comment]
It depends if you are using Nginx or not. Where is your docker container deployed (AWS? GCP? Some other Cloud host?)

I need to get some rough idea of what your infrastructure looks like.

Regarding the `GET .env` vs `GET /.env` the latter of which is normal and it's why this is so strange because a `GET .env` literally shouldn't be possible. Is your Strapi project code somewhere like GitHub (public or private repo) that we can look at?

**Comment by cipiasentini** [comment]
It's on AWS and as mentioned I'm running it using `strapi develop` could it be because of that? Unfortunately I can't share the source code

**Comment by derrickmehaffy** [comment]
I mean, we don't advise that you use develop mode in a deployed environment (production like environment). 

Have you done any modifications to core packages, any extensions, 3rd party plugins, ect?

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
