### ISSUE TITLE
Change password api for users by passing current password and email

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#10874]
### User who want to change their password has no option other then doing forgot password which has a long procedure with a lot of hassle. User knows the current password but want to change password. As of now I have gone through strapi documentation and blogs haven't found a basic thing like this.

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Why is it needed?
To change user password from current password. 

### Suggested solution(s)
Make an API that takes email, current password and new password params and resets password successfully.

**Comment by ssoftwares** [comment]
Oh my god, I just tried users update API to check if anything sensitive such as passwords can be updated with a universal PUT request API. It worked but the worst thing is I can change any user password even if I am a different user, I just need to be logged in and I can change any user's password by using my token. Strapi is so bad at things such as owners policy, we don't want hassle to customize code for such basic things.

**Comment by Flowko** [comment]
any news about this ?

**Comment by derrickmehaffy** [comment]
> any news about this ?

already implemented in v4, we will work on a retroactive patch for v3 in Jan

**Comment by Flowko** [comment]
@derrickmehaffy already implemented in v4 ? sorry because i tried to search for it, but found no documentation about it,
can u share with me more details about this please?

**Comment by derrickmehaffy** [comment]
Ah sorry I thought this is for the admin panel.

No we haven't added a method for the end-user, I do have an example of an updateMe route for v4 on my GitHub: https://github.com/derrickmehaffy/strapi-example-v4-customUpdateMe

**Comment by Flowko** [comment]
its what ive ended up doing, i was hoping for something that will take (current password, new password, confirm new password) that gets sent to an already made api similar to reset-password, kind of more secure for the user. but anyways thanks.
