### ISSUE TITLE
GraphQL - Issue when sending GraphQL variables  with accents (diacritics)

### ISSUE THREAD

**Issue by ablaas** [strapi/strapi#10885]
---
name: 🐛 Bug Report
about: Create a report to help us improve Strapi.
---

### Describe the bug

When trying to performa a GQL query with variables, and one variable has a string with accents, the API throws the following ERROR instead of the result.
The same query, when removing the accented letter will throw back the correct result.

Error:
```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Unexpected end of JSON input"
}
```

### Steps to reproduce the behavior

1. Create the following query in Postman

```gql
query getTopArticlesInnovation($categorylist:[String]){
  articles(sort: "published_at:desc", where: {category: {label_in: $categorylist }}){
    title
    slug
    category {
        label
        slug
    }
  }
}
```

2. Add the following GraphQL Variable:

```json
{
    "categorylist": ["Observatorio Tecnológico"]
}
```

3. Error shows:

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Unexpected end of JSON input"
}
```

4. If you change the variable content to:

```json
{
    "categorylist": ["Sostenibilidad"]
}
```

The correct results appear:
![image](https://user-images.githubusercontent.com/5245751/132121910-9956d364-738d-4dae-a236-792ba10c9a6a.png)

### Expected behavior

The query should show the correct results.

### Screenshots

Working query:
![image](https://user-images.githubusercontent.com/5245751/132121910-9956d364-738d-4dae-a236-792ba10c9a6a.png)

Broken query:
![image](https://user-images.githubusercontent.com/5245751/132121938-1048e1c5-a372-4ff5-8d05-0dbb2827ed89.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.4.0
- NPM version: 7.11.1
- Strapi version: 3.6.6
- Database: Postgre
- Operating system: Mac

### Additional context

The same occurs when sending the string in the query itself:

![image](https://user-images.githubusercontent.com/5245751/132122040-17de50bc-b459-4865-99db-d1bc08b25d19.png)

**Comment by reliut-g** [comment]
Hi @ablaas. 

The problem persists?

I tried to replicate the problem, but it did not reproduce the error.

![Screenshot from 2021-09-05 12-41-49](https://user-images.githubusercontent.com/63687573/132123905-9a8a48cb-ebde-46c7-8d24-c74a3699aaf8.png)

**Comment by ablaas** [comment]
Hi @reliut-g 

So I'v tried again and it works... 😞

Not sure why (this is the worst part). We did a lot of testing before pushing the issue.
So now it works. 

Thanks for your support. I'll close the issue and apologies, this must have to do with a strange behavior we've experienced in our IBM cloud environment with non-related systems.

**Comment by kasonde** [comment]
@ablaas thanks for the information
