### ISSUE TITLE
Add support for sslmode for PostgreSQL

### ISSUE THREAD

**Issue by Cubxity** [strapi/strapi#10894]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Add support for setting sslmode with PostgreSQL.

### Why is it needed?

My PostgreSQL cluster is configured to require SSL/TLS connections. However, Strapi doesn't accept self-signed certificates. I would need to set "sslmode" to "required".

### Suggested solution(s)

Add support for environment variable `DATABASE_SSLMODE` in the PostgreSQL config template and `dbsslmode` from CLI.

### Related issue(s)/PR(s)

None

**Comment by derrickmehaffy** [comment]
```
ssl: {
          rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
        },
```

See: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database

**Comment by Cubxity** [comment]
> ```
> ssl: {
>           rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
>         },
> ```
> 
> See: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database

Is there a good way to do this via the Docker image or from CLI?

**Comment by derrickmehaffy** [comment]
> > ```
> > ssl: {
> >           rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
> >         },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > See: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#database
> 
> Is there a good way to do this via the Docker image or from CLI?

Not directly from the generation CLI, you can create a project with PG and use the CLI arguments and include the `--no-run` one so it won't try to start Strapi after generation is done. Once the project is generated then you can modify the database.js

For Docker, I'd suggest you generate a project outside of docker first (we always recommend you build your own docker config for production) and have your container built based on that project.

Docker at this time is not a priority for us, it will be in the future but right now we are more focused on running Strapi natively not in a container.
