### ISSUE TITLE
Strapi don't work with Yarn 2 Workspaces

### ISSUE THREAD

**Issue by aamibhoot** [strapi/strapi#10904]
### Strapi 3.6.8 doesn't work with Yarn 2 🧶 Workspaces

When trying to run any strapi scripts this error occurs. 
`Error: strapi-admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

And during strapi installation, it shows, `Error while installing dependencies: ... `. I ran `yarn install` from the root but still won't work at all.

### Steps to reproduce the behavior

1. Create Strapi app
2. Run any script of strapi
3. See the error 🚨

### System

- Node.js version: 
- NPM version: v12.17.0
- Strapi version: 3.6.8
- Database: MongoDB
- Operating system: Windos

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9109

**Comment by derrickmehaffy** [comment]
> Is it a duplicate? I'm still experiencing this issue on `strapi@4.0.7`

This issue is quite old. I'd suggest searching to make sure there isn't a newer one or open a new issue with updated information.

**Comment by 1nVitr0** [comment]
> This issue is quite old. I'd suggest searching to make sure there isn't a newer one or open a new issue with updated information.

Sorry, should've probably mentioned that here. I did create an updated issue: #12505
