### ISSUE TITLE
Update Strapi logo in README to support GitHub Dark Mode

### ISSUE THREAD

**Issue by trivikr** [strapi/strapi#10917]
How it currently looks like:

<details>
<summary>Light mode</summary>

![light-mode](https://user-images.githubusercontent.com/16024985/132607885-9d6444f6-da22-43ee-aa1e-1f7afd4c53c2.png)

</details>

<details>
<summary>Dark mode</summary>

![dark-mode](https://user-images.githubusercontent.com/16024985/132607899-e2502e63-ac7e-46d3-b7fd-2c42ee8eac8b.png)

</details>

The logo is not clear in dark mode.

**Comment by derrickmehaffy** [comment]
Thanks for the issue but sorry we don't have assets that will work on both and no way to know the users theme and swap logos.

Going to set this as closed as there is nothing we can do about it right now

**Comment by trivikr** [comment]
> Thanks for the issue but sorry we don't have assets that will work on both.

Should there be an issue to create such an asset?
If yes, where should this issue exist?

**Comment by derrickmehaffy** [comment]
> > Thanks for the issue but sorry we don't have assets that will work on both.
> 
> Should there be an issue to create such an asset?
> If yes, where should this issue exist?

For now we don't see a priority to swap an asset like this. Unless GitHub add the ability to show a different asset based on the mode of the interface we will leave it as is.

**Comment by ajitzero** [comment]
Hi @derrickmehaffy 

GitHub has added support for this now: [Documentation Link](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)

**Comment by derrickmehaffy** [comment]
Awesome, if someone wants to create a new PR using this please feel free.

All of our logos can be found here: https://strapi.notion.site/Media-kit-b10218b27360454a8e6c3e91ca84d44a

**Comment by ajitzero** [comment]
Hi @derrickmehaffy I went ahead and made a PR for this: #12024

I have signed the CLA as a first-time contributor, so please let me know if there is anything else to consider here.
