### ISSUE TITLE
Strapi server restarts unexpectedly 

### ISSUE THREAD

**Issue by mikenowakme** [strapi/strapi#10915]
### Describe the bug

The Strapi server restarts unexpectedly while running under PM2. In development mode, it behaves as expected.

### Steps to reproduce the behavior

While navigating the Strapi admin interface and entering content, users will experience a sudden lack of response. The front end displays a spinning loading animation and a refresh of the browser will restore the site. On the backend, we see in the PM2 log that Strapi is spontaneously restarting.

### Expected behavior

We don’t expect a lack of response.

### Code snippets

Here is what we see the Strapi-out.log from pm2. It appears to just spontaneously restart with no error message.

[2021-09-08T19:24:20.220Z] debug OPTIONS /content-manager/collection-types/application::sms-content.sms-content?page=1&pageSize=10&_sort=name:ASC (1 ms) 204
[2021-09-08T19:24:20.576Z] debug GET /content-manager/collection-types/application::sms-content.sms-content?page=1&pageSize=10&_sort=name:ASC (335 ms) 200
[2021-09-08T19:24:24.739Z] debug OPTIONS /content-manager/collection-types/application::sms-content.sms-content?page=2&pageSize=10&_sort=name:ASC (0 ms) 204
[2021-09-08T19:24:24.915Z] debug GET /content-manager/collection-types/application::sms-content.sms-content?page=2&pageSize=10&_sort=name:ASC (156 ms) 200

> tailoring-cms@0.1.0 start /usr/local/miserver/civ/development/strapi-tailoring/tailoring-cms
> strapi start

 Project information

^[[90m┌────────────────────^[[39m^[[90m┬──────────────────────────────────────────────────┐^[[39m
^[[90m│^[[39m Time               ^[[90m│^[[39m Wed Sep 08 2021 15:24:38 GMT-0400 (Eastern Dayl… ^[[90m│^[[39m
^[[90m│^[[39m Launched in        ^[[90m│^[[39m 9321 ms                                          ^[[90m│^[[39m
^[[90m│^[[39m Environment        ^[[90m│^[[39m production                                       ^[[90m│^[[39m
^[[90m│^[[39m Process PID        ^[[90m│^[[39m 1162267                                          ^[[90m│^[[39m
^[[90m│^[[39m Version            ^[[90m│^[[39m 3.6.8 (node v14.17.6)                            ^[[90m│^[[39m
^[[90m│^[[39m Edition            ^[[90m│^[[39m Community                                        ^[[90m│^[[39m
^[[90m└────────────────────^[[39m^[[90m┴──────────────────────────────────────────────────┘^[[39m

 Actions available

Welcome back!
To manage your project 🚀, go to the administration panel at:
https://cms.g2ymi.org/admin

To access the server ⚡️, go to:
https://cms.g2ymi.org

> tailoring-cms@0.1.0 start /usr/local/miserver/civ/development/strapi-tailoring/tailoring-cms
> strapi start

### System

- Node.js version: 14.17.6
- NPM version: 6.14.15
- Strapi version: Strapi 3.6.8 (Community edition)
- Database: MySQL 8 (on a remote server)
- Operating system: RedHat Enterprise 7.2

### Additional context

We are running under PM2 v 5.1.1.

**Comment by derrickmehaffy** [comment]
Can you provide the error logs from pm2?

(Pm2 dumps two different log files, a usual -out and a -error. These should be in `~/.pm2/logs`)

**Comment by mikenowakme** [comment]
I am seeing things like this:
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-08T21_52_16_928Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tailoring-cms@0.1.0 start: `strapi start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tailoring-cms@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-08T21_52_25_672Z-debug.log


The log file contents:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle tailoring-cms@0.1.0~prestart: tailoring-cms@0.1.0
6 info lifecycle tailoring-cms@0.1.0~start: tailoring-cms@0.1.0
7 verbose lifecycle tailoring-cms@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle tailoring-cms@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/miserver/civ/development/strapi-tailoring/tailoring-cms/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin
9 verbose lifecycle tailoring-cms@0.1.0~start: CWD: /usr/local/miserver/civ/development/strapi-tailoring/tailoring-cms
10 silly lifecycle tailoring-cms@0.1.0~start: Args: [ '-c', 'strapi start' ]
11 silly lifecycle tailoring-cms@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle tailoring-cms@0.1.0~start: Failed to exec start script
13 verbose stack Error: tailoring-cms@0.1.0 start: `strapi start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid tailoring-cms@0.1.0
15 verbose cwd /usr/local/miserver/civ/development/strapi-tailoring/tailoring-cms
16 verbose Linux 4.18.0-305.12.1.el8_4.x86_64
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error tailoring-cms@0.1.0 start: `strapi start`
22 error Exit status 1
23 error Failed at the tailoring-cms@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mikenowakme** [comment]
It was quite flakey with 4 instances in “cluster” mode under pm2. I set it back to 1 instance in “fork” mode for now.

**Comment by mikenowakme** [comment]
I am using the instructions here to set up PM2:
https://strapi.io/documentation/developer-docs/latest/guides/process-manager.html

If there are more detailed best practices, please let me know. Since Strapi behaves better not under pm2, I suspect a pm2 or pm2 configuration issue.

**Comment by mikenowakme** [comment]
Is there any other information I can provide?

**Comment by derrickmehaffy** [comment]
This looks like some bad cached packages in your node_modules. I'd start by deleting the following:

- `package-lock.json`
- `yarn.lock`
- `node_modules` (yes the entire folder)

Then reinstall the modules with either `npm i` or `yarn` and rebuild/restart the pm2 process.

I'd also suggest double checking your package.json to make sure none of the Strapi packages have a `^` before them. Outside of that I'm not even sure how the app is starting, it should be throwing this on boot, not while it's running.

**Comment by kasonde** [comment]
Closing this conversation as it's been stale for 4 months.

**Comment by mikenowakme** [comment]
I actually figured it out. SElinux was restarting pm2 because of the default location of the pid file.
