### ISSUE TITLE
Strapi remounts component when toggling accordion

### ISSUE THREAD

**Issue by TylerOlthuizen** [strapi/strapi#10912]
https://user-images.githubusercontent.com/10456029/132557029-d9f5d0ab-7395-41ec-9fb8-5e9d4cd80016.mov

Strapi remounts component when toggling accordion.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
