### ISSUE TITLE
Folder /uploads with absolute path

### ISSUE THREAD

**Issue by kicaal** [strapi/strapi#10931]
There is a problem that if you are developing the local, with a local database, the media files are saved in the / uploads folder, the problem comes when it consumes from an api, that the url of an image for example comes the relative url ' /uploads/myimage.png 'instead of' http: // localhost: 1337 / uploads / myimage.png ', this produces problems when it is deployed to production that the consumption of images comes from an s3 for example, which returns the absolute url , then, from the front you are forced to "insert" the url of the api when you are in local and when you are in production not

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
