### ISSUE TITLE
Admin - Clicking video controls inside modal dismisses the modal

### ISSUE THREAD

**Issue by k-funk** [strapi/strapi#10940]
### Steps to reproduce the behavior

https://user-images.githubusercontent.com/1933021/132961500-399a570d-48a4-4090-b6a0-9a539923aa7f.mp4

### Expected behavior

Modal shouldn't close

### System

- Node.js version: v14.17.6
- Operating system: MacOS 11.5.2
```
    "strapi": "3.6.8",
    "strapi-admin": "3.6.8",
    "strapi-utils": "3.6.8",
    "strapi-plugin-content-type-builder": "3.6.8",
    "strapi-plugin-content-manager": "3.6.8",
    "strapi-plugin-users-permissions": "3.6.8",
    "strapi-plugin-email": "3.6.8",
    "strapi-plugin-upload": "3.6.8",
    "strapi-plugin-i18n": "3.6.8",
    "strapi-connector-bookshelf": "3.6.8",
```

### Additional context

Fresh install.

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
