### ISSUE TITLE
image is missing when I edit the content again in admin.

### ISSUE THREAD

**Issue by enoy** [strapi/strapi#1094]
**Informations**
- **Node.js version**:
v9.11.1
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0 alpha 12.0.1
- **Database**:
mongo
- **Operating system**:
Mac 10.13.4 (17E199)

**What is the current behavior?**
update image & edit it again, the image is missing in media field.

**Steps to reproduce the problem**
1. Use Content Type Builder to add a contenttype named product. 
2. Add some fields for product, one of them is a new Media field. 
3. Add data for product, upload a image for the media field and submit the form. 
4. Edit the product data and submit.
5. View the data again, the uploaded image is missing.
**What is the expected behavior?**
update image & edit it again, the uploaded image should be there

**Suggested solutions**

---

- [Y] I'm sure that this issue hasn't already been referenced

**Comment by underbayan** [comment]
It also happened to me, This issue is not an accidental phenomenon

**Comment by lauriejim** [comment]
Hello @enoy and @underbayan ! We just release new version of Strapi, can you try to update your version of Strapi and test it again please.

**Comment by enoy** [comment]
I use 12.0.1, how to update my project to the latest version? @lauriejim

**Comment by derrickmehaffy** [comment]
@enoy the easiest way is to generate a new project and copy over your `api` folder.

**Comment by indiecore-fm** [comment]
This is happening to me on alpha 12.2. I'm on windows if that might make any difference. I have a successful upload to amazon though.

**Comment by johanalkstal** [comment]
I know this one is closed but I am giving Strapi a try and I am experiencing exactly this issue.

I have created my first content type, it has a Media field.
When I create a new one of that type and fill in all the fields, I can upload an image and see it in the UI before I save (all uploaded images are also in media files).
I save.
I call the API to get the content but the media property on the returned content is null.
I navigate back to my newly created item and the Media Field is empty. All other fields retain their data.

Node.js version:
v8.10.0
npm version:
5.6.0
Strapi version:
3.0.0-alpha.12.6
Database:
mongo
Operating system:
Mac 10.13.5
