### ISSUE TITLE
Which folders require read & write permission for media upload?

### ISSUE THREAD

**Issue by anupjk-5** [strapi/strapi#10946]
### Describe the bug

I have created a custom s3 provider for media upload. The uploads work perfectly in development. But in production, the upload
fails with 502 bad request. It shows a file size is too large error in the logs (tried with 98kb image also). We have a read only file-system with docker in production. For uploads to work, which folders require read and write permissions in a system?

### Expected behavior

Upload should work in both development and production.

### System

- Docker
- AWS ECS

**Comment by kasonde** [comment]
Hi, thanks for the question. I'm closing this here however since it's not an issue but a question that is great for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.
