### ISSUE TITLE
user/me api returns only _id for admin and both _id and id for authenticated users

### ISSUE THREAD

**Issue by kperveen** [strapi/strapi#1095]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**:  3.0.0-alpha.12
- **Strapi version**: 3.0.0-alpha.12
- **Database**: monogdb
- **Operating system**: Ubuntu 14.04

**What is the current behavior?**
 When `/user/me` is called for an admin user, the response data does not contain the `id` attribute. However, when the same api is called for an authenticated user, the api returns both `id` and `_id`. I double checked it using the api `/content-manager/explorer/user` to get users and the response data contains both the attributes, `id` and `_id` for all the users.

**Steps to reproduce the problem**
Call `user/me` for admin and then call `user/me` for an authenticated user, the response data will have different attributes.

**What is the expected behavior?**
`user/me` should return the same attributes for all the users.

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Every data created with the content manager have `id` key. If you create data from another way, the `id` key will not exist.

**Comment by kperveen** [comment]
hey @lauriejim 
Yeah, it creates an `id` for admin data (when registered via the admin panel) but it's not returning that `id` when `/user/me` is called for admin

**Comment by Aurelsicoko** [comment]
It think it's related to the work started in https://github.com/strapi/strapi/pull/913
