### ISSUE TITLE
CSRF mismatch with login request

### ISSUE THREAD

**Issue by latata** [strapi/strapi#1096]
I'm testing production environment in strapi (v3) with csrf enabled and I realised I can't login because I'm getting CSRF token mismatch. This is because I don't send any csrf token from frontend. Is there a way to get this token from api or something like this? Should /auth/local request require csrf token as it can be executed by non authenticated users?

**Comment by lauriejim** [comment]
Hello @latata can you follow the issue template please. Will reopen this issue when you did it.
