### ISSUE TITLE
Error 404 of all medias after heroku upload

### ISSUE THREAD

**Issue by filippodicostanzo** [strapi/strapi#10974]
### Describe the bug

I develop on heroku my app. 

After correctly uploading my images on the STRAPI platform if I make changes to the code and reload everything on heroku I lose the link to the images and I'm forced to manually reload.

How to resolve this issue?

### System

- Node.js version: v14.17.6
- Strapi version: v3.6.8
- Database: PostgreSQL 
- Operating system: Win10

**Comment by MattieBelt** [comment]
Hey @filippodicostanzo,

Take a look at this FaQ: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-paas

TLDR: Heroku is a ephemeral system, so you need to use a provider for your [file uploads](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#file-uploads).

**Comment by kasonde** [comment]
Thanks @MattieBelt , I'll go ahead and close this as well.

**Comment by filippodicostanzo** [comment]
I solved using amazon aws 3 as provider.
Thanks for your help :)
