### ISSUE TITLE
lifecycles  beforeUpdate cant change data

### ISSUE THREAD

**Issue by liguangsong** [strapi/strapi#10986]
strapi version: 3.6.8
lifecycles  beforeUpdate cant change data,  i need before update to auto change one field value when chage other field value in the Admin Panel, but beforeCreate can change field value

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
