### ISSUE TITLE
Trying to login - error TypeError: Cannot read property 'fields' of null

### ISSUE THREAD

**Issue by allangalera** [strapi/strapi#10983]
### Describe the bug

After a while I start getting error while trying to login. The problem is that I don't know what triggers that. I don't remember at which version it started but for sure since 3.4.4.

We have two instances. One for homologation and one for production. The production one doesn't have DDL access to the database.

This happens on homologation instance. And if I restart the instance it start's working again.

### Expected behavior

To login.

### Screenshots

![image](https://user-images.githubusercontent.com/12666793/133458844-b1c6c8a1-f203-4b9c-8d32-b4b06ae61bf1.png)
![image](https://user-images.githubusercontent.com/12666793/133459660-cd6da902-a3fb-48c1-9166-9f43bd9696bd.png)

### System

- Node.js version: v12
- NPM version: 6
- Strapi version: 3.6.5
- Database: postgres 12.5
- Operating system: node:12-alpine3.12

If I forgot something just tell me and I add here 😄

**Comment by kasonde** [comment]
Hi, could you share steps to reproduce this issue? As much information you could provide could prove very helpful.

**Comment by derrickmehaffy** [comment]
No new information provided, marking as closed
