### ISSUE TITLE
Upload images to S3 not working with the default settings

### ISSUE THREAD

**Issue by Mhm0ud** [strapi/strapi#10992]
### Describe the bug

I'm trying to use aws-s3 provider to upload images to S3 bucket, but the images not uploading to S3, instead of that it's uploading to the local server and it doesn't throw any error

### Steps to reproduce the behavior

1. install s3-provider with `yarn add strapi-provider-upload-aws-s3`
2. Edit config/plugins.js and add the following lines
```
module.exports = ({ env }) => ({
    upload: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        params: {
          Bucket: env('AWS_BUCKET_NAME'),
        },
      },
    },
  });
```
3. execute the commands: `yarn` then `yarn build` then `yarn start`
4. Go to admin and try to upload an image via Media Library
5. After the image is uploaded, inspect the image you will see the URL not an S3 URL, you will see local URL and the S3 bucket empty

### Expected behavior

The image will upload to the S3 bucket, and the URL of the image is a S3 URL.

### Screenshots

![image](https://user-images.githubusercontent.com/16934190/133592899-a7e47bec-3e05-4a17-9851-95cac1cd028d.png)

### System

- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Database: Postgres
- Operating system: Windows 10 

### Additional context

I solved the problem with these steps:
edit file config/plugin.js:

```
module.exports = ({ env }) => ({
upload: {
  provider: 'aws-s3'
  },
});
```
create a file extensions/upload/config/settings.js:

```
module.exports = {
provider: 'aws-s3',
providerOptions: {
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_ACCESS_SECRET,
  region: process.env.AWS_REGION,
  params: {
    Bucket: process.env.AWS_BUCKET_NAME,
  },
},
};
```

**Comment by stafyniaksacha** [comment]
You do not need to create a file in `extensions` folder,

Just:
```js
// config/plugin.js
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3'
  },
  providerOptions: {
    accessKeyId: env('AWS_ACCESS_KEY_ID'),
    secretAccessKey: env('AWS_ACCESS_SECRET'),
    region: env('AWS_REGION'),
    params: {
      Bucket: env('AWS_BUCKET_NAME'),
    },
  },
});
```

**Comment by MattieBelt** [comment]
Hey @Mhm0ud,

Just a small comment, are you sure you configured the right file? As you both said `config/plugins.js` and `config/plugin.js`.👆

The right file is with a plural 's', so `config/plugins.js` should work.

**Comment by paulpopus** [comment]
@MattieBelt I think the confusion around this came from a mix of S3's interface whereby it tells you the bucket is publicly accessible but that not being the case without an auth token and that Strapi needs the bucket to be publicly accessible without any tokens despite having access to the keys to make authenticated requests in the admin UI.

That issue relating to Strapi is already opened here: https://github.com/strapi/strapi/issues/8623

For anyone else, your bucket might need this policy added if you come across this issue despite AWS saying "public read access":

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AddPerm",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::BUCKET_NAME/*"
        }
    ]
}
```

**Comment by Mhm0ud** [comment]
> You do not need to create a file in `extensions` folder,
> 
> Just:
> 
> ```js
> // config/plugins.js
> module.exports = ({ env }) => ({
>   upload: {
>     provider: 'aws-s3',
>     providerOptions: {
>       accessKeyId: env('AWS_ACCESS_KEY_ID'),
>       secretAccessKey: env('AWS_ACCESS_SECRET'),
>       region: env('AWS_REGION'),
>       params: {
>         Bucket: env('AWS_BUCKET_NAME'),
>       },
>     },
>   },
> });
> ```

Yes, I did that before, but it didn't work, and that is why I used the second solution.

**Comment by Mhm0ud** [comment]
> Hey @Mhm0ud,
> 
> Just a small comment, are you sure you configured the right file? As you both said `config/plugins.js` and `config/plugin.js`.👆
> 
> The right file is with a plural 's', so `config/plugins.js` should work.

Yes, I'm sure I did that, and it didn't work.

**Comment by atlmtw** [comment]
I'm having the same issues right now with the live version of strapi 4.0.0

**Comment by derrickmehaffy** [comment]
v3 related, works fine in v4 (and in v3) closing
