### ISSUE TITLE
Server can't start "error: remaining connection slots are reserved for non-replication superuser connections"

### ISSUE THREAD

**Issue by gkkirilov** [strapi/strapi#10999]
Other people and their experience on the issue [https://forum.strapi.io/t/error-remaining-connection-slots-are-reserved-for-non-replication-superuser-connections-sorry-too-many-clients-already/8019/7](https://forum.strapi.io/t/error-remaining-connection-slots-are-reserved-for-non-replication-superuser-connections-sorry-too-many-clients-already/8019/7)

## Bug report

Deploying new version crashes as there are no more connections to be open when running SQL on low tier gcp app engine instance which limits to 25 connections. 

### Describe the bug
Opening the url crashes the instance 

### Steps to reproduce the behavior
1. Follow the GCP App Engine deploy guide
2. Deploy several versions of the same app engine service
3. Open multiple windows to the admin url
4. Server crashes

### Expected behavior
Server to not crash

### Screenshots

![image](https://user-images.githubusercontent.com/8720012/133737301-019e11d4-b0f4-46ea-b3d6-fd58a320f5d5.png)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/error-remaining-connection-slots-are-reserved-for-non-replication-superuser-connections-sorry-too-many-clients-already/8019/8

**Comment by kasonde** [comment]
Hi, thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.
