### ISSUE TITLE
Unable to edit Content Types in Admin Panel that begin with a number (ref: Prior Issue)

### ISSUE THREAD

**Issue by stickchartkeith** [strapi/strapi#10998]
The issue below was closed out, and appears to be related more to attributes but this is occurring for me when Content Types are named starting with a number, error thrown:

```[2021-09-16T17:24:03.488Z] debug PUT /content-type-builder/content-types/application::01-section-features.01-section-features (1176 ms) 400```

I do all of the configuration work on my local Mac, but can replicate this on our production server by running in development mode.  

If my content types do not start with a number, I am able to edit them in the Admin panel successfully.  The workaround is to modify the JSON file directly, so not the end of the world, but this should really get fixed once and for all.  

I would also say that just preventing content types from starting with a number is not a solution, we use a numbering scheme to associate content-types to pages and structure within the site, so it would be preferred to continue allowing Content types to be created with leading numbers.

System

Node.js version: 14.7.1
NPM version: 6.14.13
Yarn version: 1.22.11
Strapi version: 3.6.8
Database: PostgreSQL 12.7
Operating system: Dev: OS X 11.6 / Prod: Ubuntu 20.04.3 / LTS

_Originally posted by @lauriejim in https://github.com/strapi/strapi/issues/5095#issuecomment-641197580_

The issue has been fixed in the stable version of Strapi.
You can no longer create an attributer starting with a number.

**Comment by derrickmehaffy** [comment]
won't fix as we now implement regex checking when you generate content-types via the CLI so you can't create them starting with a number
