### ISSUE TITLE
Extremely slow API response when multiple locales enabled

### ISSUE THREAD

**Issue by cempesket** [strapi/strapi#11006]
## Bug report

Our project has currently 25 locales enabled, but only 2 published pages.

When the pages were being setup in a single locale, the problem was not there. It appeared once more locales were enabled and the translations setup and published.

"Save" and "Publish" became extremely slow.

### API call

PUT /content-manager/collection-types/:contentType/:id

When there are 25 localizations for a specific page, this took 15 seconds to get a response.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
