### ISSUE TITLE
Strapi Start not compiling with existing MySQL database

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1101]
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: MySQL
- **Operating system**: Windows

**What is the current behavior?**

Starting the application with strapi start after installation returns the following error:
`[2018-05-03T12:12:28.984Z] debug Server wasn't able to start properly.
(hook:bookshelf) takes too long to load`

 The database i'm using was made using the creation script of v3.0.0-alpha.12 provided by the command prompt.

Strangely, npm installing strapi locally in the root directory of the project allows the application to compile, but once a server restart is done, for example after creating a new content-type, I get the same error as before I installed strapi locally in the root directory of the project. 

**Steps to reproduce the problem**
1) npm install strapi@alpha -g
2) strapi new my-app
3) enter database credentials (mysql) 
4) cd my-app 
5) strapi start 

-----------------------
(the following steps allow the app to run once, step 8 breaks the app again)

6) npm install strapi@alpha
7) strapi start
8) add a new content-type and save, causing the server to restart

**What is the expected behavior?**

npm installing strapi and using strapi start should make the app compile and not crash

**Suggested solutions**

probably a bug because of the new strapi version released today, no clue about the solutions atm.

- [ x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Hello @piere129 can you update `/config/hook.json` key `timeout` and tell me if it works.

**Comment by piere129** [comment]
@lauriejim what should i update it to?

**Comment by piere129** [comment]
I found the issue: the new strapi update 12.1 auto-generates tables in your database, i was not aware of this because I had existing tables already. These probably caused the error!

**Comment by piere129** [comment]
That did the trick! Apparantly the app automatically stops compiling when the loading time exceeds the timeout number, making this number higher fixed my problem!

**Comment by lauriejim** [comment]
There is no issue here, it's normal. If the load time exceed the timeout, we haven't database connection (in this case) so we have to stop the app cause it will be not usable.

**Comment by tcdona** [comment]
i have the same problem too, thx

**Comment by hzburki** [comment]
I had the same issue. MySQL version `8.0.11` hosted on AWS RDS. Along with what @lauriejim said about increasing the timeout in `config/hook.json`. I had to add a `"pool"` object to `"options"` in database config files. Refer [#2790](https://github.com/strapi/strapi/issues/2790#issuecomment-475123374) for solution
