### ISSUE TITLE
Editor role can only see two locales

### ISSUE THREAD

**Issue by NicolasTsc** [strapi/strapi#11027]
### Describe the bug
So far we have two locales for our content types and added two more. 
As a super admin you can see them when adding content and when opening the dropdown in the content overview.
But for the editor role the locale is not visible. The other two existing locales are visible for the editor role.
I am not 100% sure if its reproducible on a fresh install.
### Steps to reproduce the behavior
1. Add multiple locales
2. Try to add content
3. See if all locales are visible

### Expected behavior
Editor role should see all locales and edit them.

### Screenshots

Dropdown for super admin:
![image](https://user-images.githubusercontent.com/19031453/134170488-9941905a-7f10-4894-8d0c-fc408e7b39d9.png)
Dropdown for editor:
![image](https://user-images.githubusercontent.com/19031453/134170511-95e7d425-6b67-4379-a4cb-29bc1c1fb3cb.png)

### System

- Node.js version: 14.17.1
- NPM version: 6.14.13
- Strapi version: 3.65
- Database: postgresql
- Operating system: debian 9 / win 10

**Comment by NicolasTsc** [comment]
So for anyone else stumbling across this problem in the future. 
When looking in the database I noticed that in the strapi_permission table the field properties had some entries, where the JSON field locales didn`t include all locales. 
The solution was creating a dump, adding all locales and reimporting the dump.

The question remains why some database permissions aren`t getting updated when creating a locale from the UI but that seems more like a Strapi issue.

**Comment by kasonde** [comment]
I can confirm this happens for SQLite and MySQL as well following my testing.

**Comment by JabStrapi** [comment]
Did you try to select the extra locales in the permissions of the Editor role view ?(locales are checked by default for Super Admin role, not for others).

**Comment by kasonde** [comment]
Confirmed @JabStrapi 's recommendation is correct. If you go to the role permissions and select each local for the role you're talking about, you'll be able to choose those locales when editing the content-type. Here's a snippet of what that looks like
![image](https://user-images.githubusercontent.com/13610895/141744845-45523842-effd-4ad4-a0fa-863de20e1380.png)
