### ISSUE TITLE
Consider updating mongoose to 5.13.7 OR 6.x to fix security issue

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#11044]
### Describe the bug

Update mongoose to >5.12.2 version to fix.
https://snyk.io/vuln/SNYK-JS-MONGOOSE-1086688

### System

- Node.js version: 14
- NPM version: NA
- Strapi version: 3.6.x 
- Database: Mongo
- Operating system: Mac

### Additional context

It should be updated to `5.13.7` , but updating to v6 will introduce some Breaking changes, but not sure if it affects strapi v3 directly.

**Comment by Eventyret** [comment]
Added a fix for this to bump the version :)

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
