### ISSUE TITLE
s

### ISSUE THREAD

**Issue by BedzOne** [strapi/strapi#1104]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**:
- **npm version**:
- **Strapi version**:
- **Database**:
- **Operating system**:

**What is the current behavior?**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

---

*FEATURE REQUEST TEMPLATE*  

**What is the expected behavior?**

---

- [ ] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
Please update your issue if you have something to report.
