### ISSUE TITLE
Bookshelf Error - Unhandled promise

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1105]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: 10.2.14-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
After starting a new strapi project using mysql (mariadb) bookshelf throws a nice big error:

**Edit to remove wall of log text**

 Logfile: https://pastebin.com/FuAuR96n

**Steps to reproduce the problem**
Create a new strapi project, select mysql (in my case using MariaDB) and start the project

**What is the expected behavior?**
Not sure what is causing the error, but it shouldn't be there :D

**Suggested solutions**
N/A

- [x] I'm sure that this issue hasn't already been referenced

**Comment by derrickmehaffy** [comment]
Looks like after shutting down the server and restarting it causes this error: 

`dmehaffy@capi1:~/api/CAPIv2-Strapi$ strapi start
[2018-05-03T15:58:13.223Z] debug Server wasn't able to start properly.
(hook:bookshelf) takes too long to load
`

**Comment by xkawi** [comment]
having the same error too when creating new project using postgres as database:

```cli
node:224) UnhandledPromiseRejectionWarning: Error: A model cannot be destroyed without a "where" clause or an idAttribute.
    at Sync.<anonymous> (/usr/src/api/strapi-app/node_modules/bookshelf/lib/sync.js:219:13)
From previous event:
    at Child.<anonymous> (/usr/src/api/strapi-app/node_modules/bookshelf/lib/model.js:1236:19)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Child.<anonymous> (/usr/src/api/strapi-app/node_modules/bookshelf/lib/model.js:1235:8)
From previous event:
    at Function.removePermission (/usr/src/api/strapi-app/plugins/users-permissions/config/queries/bookshelf.js:138:8)
    at Promise.all.Promise.all.toRemove.map.action (/usr/src/api/strapi-app/plugins/users-permissions/services/UsersPermissions.js:279:92)
    at Array.map (<anonymous>)
    at Object.updatePermissions (/usr/src/api/strapi-app/plugins/users-permissions/services/UsersPermissions.js:279:30)
```

It's this line of code: `Promise.all(toRemove.map(action => strapi.query('permission', 'users-permissions').removePermission(action)))` at [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L279)

I am not familiar with user-permission plugin source code nor its table schema. So not sure if it's a bug or we can safely ignore it.

**Comment by derrickmehaffy** [comment]
In my case I did the initial setup the server started with those errors, however past that I cannot restart it after shutting it down.

**Comment by derrickmehaffy** [comment]
@lauriejim any thoughts on troubleshooting and/or what other information do you need?

**Comment by derrickmehaffy** [comment]
@piere129 ahhh good catch ill test and report back

**Comment by derrickmehaffy** [comment]
Can confirm that increasing the variable in hook.json from `3000` to `6000` allowed the server to start.

**Comment by derrickmehaffy** [comment]
Update to the above comment, I've had to progressively increase that limit the more that is added. Right now I'm sitting at 20000 (~20 seconds) so something isn't quite working right :P

**Comment by derrickmehaffy** [comment]
@lauriejim not sure if this is helpful or not, but I've noticed on multiple restarts strapi seems to be taking about an additional 900 to 1100ms to load which has forced me to increase this limit to around 40000 (~40 seconds) even if I'm not adding additional models or data :/

**Comment by lauriejim** [comment]
@derrickmehaffy 40s to start an app it's not normal, we have to update the MySQL database table/column creation process.

How many models and attributes you have ?

**Comment by derrickmehaffy** [comment]
Sorry @lauriejim I just saw this reply. 

I have about 20 models, most of which will have less than 10 attributes but one of them has about 34. This isn't counting the ones installed by strapi (both models and attributes)

This isn't quite up to date but: https://github.com/canonn-science/CAPIv2-Strapi is my test repo. I still have more to add 😛

**Comment by KevinSupertramp** [comment]
Hi, I'm having the same problem with a fresh install + 1 new model. I change the hook.js timeout to 40s and the problem is still here. I connect to a remote MySQL database.

I don't have any log either just:

`[2018-07-26T14:39:49.592Z] debug ⛔️ Server wasn't able to start properly.
[2018-07-26T14:39:49.607Z] error (hook:bookshelf) takes too long to load`

Any ideas?
Thanks a lot!

**Comment by vaskort** [comment]
@KevinSupertramp I also got this error.
Try to increase the `timeout` property inside `config/hook.json`.
Though sometimes I'm still getting incosistent behaviour when trying to dockerise Strapi but if you're not using Docker, it might help.

**Comment by derrickmehaffy** [comment]
If your using bookshelf this shouldn't be an issue anymore. Bookshelf has been modified to help resolve this.

**Comment by williamkunz** [comment]
I am getting this issue *every* time I create a new content-type/model using a local postgres. 
- The local connection to the DB is good. Output printed after successful connection. 
- My `hook.json` timeout is at `30000` just to make sure
- `strapi -v` outputs `3.0.0-alpha.14.3`

(I am fairly new to strapi)

**Comment by maturanomx** [comment]
Welcome @williamkunz !

So... you are able to create and run a  new project, right?. Then, you create a new content-type from the GUI and when restart the application is when you see the error?. I'm correct?

First, try to add the `debug` flag to your database configuration:

`config/environments/development/database.json`
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {},
      "options": {
        "debug": true
      }
    }
  }
}
```

Then, can you share us your complete log please? and your configuration file also could help.

I think would be better open a new issue. To be honest, I don't read all the previous conversation :)

**Comment by christopher4lis** [comment]
Still getting this error when using MySQL instead of Mongo: `(node:32784) UnhandledPromiseRejectionWarning: Error: read ECONNRESET`

**Information:**

- Node.js version: `v10.13.0`
- npm version: `6.4.1`
- Strapi version: `3.0.0-alpha.14.5`
- Database: `5.6.35-MySQL`
- Operating system: `macOS Mojave 10.14`


Ending errors include:

`[2018-11-18T21:30:25.110Z] debug ⛔️ Server wasn't able to start properly.`
`[2018-11-18T21:30:25.111Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load`

Upping the timeout time in hooks didn't fix anything on my end.

**Comment by derrickmehaffy** [comment]
@christopher4lis did you create your project with mongo then switch to mysql?

**Comment by christopher4lis** [comment]
Hi @derrickmehaffy. No, original projects with the above error were all created with MySQL. I did try Mongo after however, and things worked as expected. Seems to just be an issue with the MySQL version.

**Comment by christopher4lis** [comment]
Got it, going to assume it's a missing permission or database issue since everything with Strapi was scaffolded using the `strapi new` command. I'll troubleshoot things further and come back with a solution, appreciate your help so far.

**Comment by waterlooblue** [comment]
I'm having the same issues as @christopher4lis. I can use mySQL when I build strapi locally. Increasing the timeout doesn't help either. What should the database settings look like?

**Comment by Aurelsicoko** [comment]
@waterlooblue You should try to use Mongo 👍

**Comment by derrickmehaffy** [comment]
> @waterlooblue You should try to use Mongo

*shakes finger* @Aurelsicoko

**Comment by puneetverma05** [comment]
@derrickmehaffy  Can you have a look into this ? #2790

**Comment by FikriRNurhidayat** [comment]
It happened after I generate:api with --tpl bookshelf

**Comment by Aurelsicoko** [comment]
@FikriRNurhidayat I'm not sure the generators are up-to-date via the CLI. You should try to create the API (content type) through the UI (content type builder).

**Comment by Evochrome** [comment]
Although this is not really a solution... 
Make sure that a connection with your mySQL database (mariaDB) is possible at all. In my case, my WAMP decided to shutdown the database server, whereafter the Bookshelf error occured. Hope this helps anyone (Took me way to long to figure out 😬)

**Comment by jasenmichael** [comment]
> Can confirm that increasing the variable in hook.json from `3000` to `6000` allowed the server to start.

the above worked for me connecting to remote database, running strapi locally, while my kids are using most of my bandwidth.

**Comment by MatheusRV** [comment]
I get this error when install strapi using Yarn.

**Comment by MaffooBristol** [comment]
I was trying to rebuild something from months ago which I clearly built using Node 10 or so, and then tried to run it with Node 14. Got this issue, downgraded to Node 10 and it's fine.

Could probably be sorted by reinstalling the node modules- for me this wasn't possible due to my actual issue being a package deleted from npm. But it might be of use to people scouring the issue queues.
