### ISSUE TITLE
Client side routing

### ISSUE THREAD

**Issue by andrejko** [strapi/strapi#1106]
Does anyone know the way to make Strapi serve index.html for all requests?
Initial problem is that some React routes like /location/2 are handled by backend, instead of serving index.html and, by that, handling them on front.

**Comment by storm1er** [comment]
It depends on your server configuration, see https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing for exemple. 

Note that you can also fix this through apache or ngynx depending on your server configuration.

**Comment by Kinark** [comment]
Did someone find a solution to this issue? I'm trying to find a way without using nginx.

**Comment by tscans** [comment]
I'm have the same issue on this one.

**Comment by Kinark** [comment]
For the ones having this issue, I recommend you to separate your api and your website in two different domains. So you can manage your website as a static one and your api as a api-only.

**Comment by tscans** [comment]
In this case can I push both apps to the same heroku app?

**Comment by Kinark** [comment]
@tscans I believe you have to run two apps, that's a downside of my method :/
But you can always host your static files on gh-pages or netlify.

**Comment by tscans** [comment]
True, this is probably the most viable now though. Thanks for the suggestion.
