### ISSUE TITLE
Upload file is being saved but no entry in the database. Error returned as 502.

### ISSUE THREAD

**Issue by gregmarzio** [strapi/strapi#11072]
## Bug report
When uploading a file, I am receiving a 502 error. The logs show "upstream prematurely closed connection while reading response header from upstream".

### Describe the bug
The file is being saved in the upload directory but no record is being saved in the database. The install is a standard install of Strapi without any modification.

### Steps to reproduce the behavior

1. Go to Media Library.
2. Upload a PNG, JPG, etc.
3. 502 Error is returned.
4. Nginx logs shows: "upstream prematurely closed connection while reading response header from upstream".
5. Strapi logs show nothing but the file exists in the upload directory but no record is in the database.

### Expected behavior
File appears in the Media Library.

### Screenshots
None.

### Code snippets
None.

### System

- Node.js version: v14 LTS
- NPM version: Yarn v1.22.5
- Strapi version: v3.6.8
- Database: MariaDB v10.6.4
- Operating system: Ubuntu v20.,04 LTS

### Additional context
None

**Comment by sk1122** [comment]
Can you share your nginx conf file? If I am not wrong nginx file is configured by user.

**Comment by gregmarzio** [comment]
Hi @sk1122 

Thank you so much for your response.

Please find the Nginx configuration below. Strapi is set to use port 1338 and this is working correctly.

nginx.conf:
```
user www-data www-data;  ## Default: nobody
worker_processes auto;  ## Default: 1
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;
worker_rlimit_nofile 8192;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 4096;  ## Default: 1024
}

http {
    server_tokens off;

    include /etc/nginx/mime.types;
    include /etc/nginx/fastcgi.conf;
    include /etc/nginx/sites-enabled/*;

    default_type application/octet-stream;
    log_format main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    sendfile on;
    tcp_nopush on;
    server_names_hash_bucket_size 128;

    client_max_body_size 64M;

    # Proxy
    fastcgi_buffers 8 64k;
    fastcgi_buffer_size 128k;
    proxy_connect_timeout 75s;
    fastcgi_send_timeout 300s;
    fastcgi_read_timeout 300s;
    proxy_read_timeout 300s;
    proxy_max_temp_file_size 4096m;
}
```

site.conf:
```
server {
    listen                  80;
    listen                  [::]:80;
    server_name             abcd.tbkwatch.com;
    return 301              https://abcd.tbkwatch.com$request_uri;
}

server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             abcd.tbkwatch.com;

    error_log               /var/log/nginx/abcd.tbkwatch.com-error.log;
    access_log              /var/log/nginx/abcd.tbkwatch.com-access.log combined;

    include                 /web/nginx/website-general.conf;

    location / {
        proxy_pass http://127.0.0.1:1338;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }

    ssl_certificate /etc/letsencrypt/live/abcd.tbkwatch.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/abcd.tbkwatch.com/privkey.pem; # managed by Certbot
}
```

website-general.conf:
```
charset utf-8;

# SSL
ssl_session_cache shared:le_nginx_SSL:1m;
ssl_session_tickets off;
ssl_session_timeout 1d;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;
ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384";
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

# OCSP Stapling
ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
resolver_timeout 2s;

# Headers
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
add_header Referrer-Policy "no-referrer-when-downgrade" always;

# Security
fastcgi_hide_header X-Powered-By;
proxy_cookie_path / "/; HTTPOnly; Secure";

location = /favicon.ico {
    allow         all;
    access_log    off;
    log_not_found off;
}

location = /robots.txt  {
    allow         all;
    access_log    off;
    log_not_found off;
}

location = /sitemap.xml  {
    allow         all;
    access_log    off;
    log_not_found off;
}

location = /xmlrpc.php {
    deny all;
}

location = /web.config {
    deny all;
}

location ~ /\.ht {
    deny all;
}

location ~ /\.git {
    deny all;
}

location ~ /\.(?!well-known).* {
    deny all;
}

location ~ ^/\.user\.ini {
    deny all;
}
```

**Comment by sk1122** [comment]
`upstream` means the server in this case strapi. I think that the problem is with strapi endpoint for uploading files. Connection was closed by upstream means strapi. It also mentions that `while reading response headers`, so there must be problem with response headers. Can you check the headers?

**Comment by gregmarzio** [comment]
Hi @sk1122 

I have checked the headers but it seems to be fine.

We are using the same Nginx configuration on other servers without any issues.

**Comment by sk1122** [comment]
Your nginx file is fine. Problem is with upstream.

Upstream means the web server.

Upstream is closing the connection and thats why nginx is sending 502 error.

Try checking the header you are sending when uploading the file because the problem is with server, so you might be sending wrong type of file or maybe your filetype is different than that sent in headers.

**Comment by derrickmehaffy** [comment]
This appears to be an environment issue and not something to do with Strapi, please use our forum for this.

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by hsnassaad** [comment]
I have the same problem

**Comment by gregmarzio** [comment]
This issue is due to the Strapi instance restarting after an upload.

If you are using Strapi via Node.js, ensure you are not running "strapi develop" command.

If you are using Strapi via PM2, ensure you are not running PM2 watch as true, or "strapi develop" command in your configuration file.

**Comment by hsnassaad** [comment]
Thanks man for replaying, i am using Strapi via PM2 on a ubuntu machine with an nginx proxy.
this is how the `ecosystem.config.js` file looks like:

```
module.exports = {
  apps: [
    {
      name: 'strapi', // Your project name
      cwd: '/home/ubuntu/strapi', // Path to your project
      script: 'npm', // For this example we're using npm, could also be yarn
      args: 'start', // Script to start the Strapi server, `start` by default
      env: {
        NODE_ENV: 'production',
        DATABASE_HOST: 'XXXXXXXXXXXX', // database Endpoint under 'Connectivity & Security' tab
        DATABASE_PORT: 'XXXX',
        DATABASE_NAME: 'XXXXXX', // DB name under 'Configuration' tab
        DATABASE_USERNAME: 'XXXXX', // default username
        DATABASE_PASSWORD: 'XXXXXXXX',
        AWS_ACCESS_KEY_ID: 'XXXXXXXX',
        AWS_ACCESS_SECRET: 'XXXXXXXXX', // Find it in Amazon S3 Dashboard
        AWS_REGION: 'XXXXX',
        AWS_BUCKET_NAME: 'XXXXXXXXX',
      },
    },
  ],
};
```


The problem only occurs when we run the Strapi project with PM2, but if we use `npm run develop` the media are uploaded successfully, otherwise an `504 Gateway Time-out` is happening.
