### ISSUE TITLE
Content Type Builder not working on AWS

### ISSUE THREAD

**Issue by JasonAtallah** [strapi/strapi#1109]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: MongoDb
- **Operating system**: Linux Ubuntu

**What is the current behavior?**
Cannot create new content types
**Steps to reproduce the problem**
Deploy app to AWS, try to create a Content Type
**What is the expected behavior?**
To create a Content Type

Everything works fine on my local machine but when deployed on AWS Strapi won't let me create any content types, I'm getting this error: 
POST http://ec2-XX-XXX-XXX-X.us-west-2.compute.amazonaws.com:1337/content-type-builder/models/ 500 (Internal Server Error)

Mongo and Strapi are on two separate instances, if that makes a difference. Any help would be much appreciated.

- [ x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment]
I supposed you are using `npm start` to start your project on ec2 instance.
Please check old issues https://github.com/strapi/strapi/issues/1008
