### ISSUE TITLE
Upload gets timeout, specially for larger files

### ISSUE THREAD

**Issue by adityaumeshacharya** [strapi/strapi#11107]
I am facing timeout issue on Strapi when I try to upload large videos or anything that takes longer than a minute to upload. PFA the log image, here I tried to upload a 500mb video and got this error.

![cms_error1](https://user-images.githubusercontent.com/35888089/135081686-aadf2848-4285-4aea-b89a-454fa755353e.PNG)

**Comment by MattieBelt** [comment]
Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
