### ISSUE TITLE
New registered field does not show registered value in collection grid view

### ISSUE THREAD

**Issue by antoci-alin** [strapi/strapi#11105]
### Describe the bug

I created a new field through plugin feature, nothing fancy, just a dropdown. Everything looks nice, I get the field when creating the collection entry, the api is exposing the field with the value registered. The issue comes in when I wanted to show the registered value in the gridview. The displaying value is "-" (basically, a default value) but it's not the value that the collection was registered with. As I said, the value comes on the api as it should. 

See screenshots section.

### Steps to reproduce the behavior

1. Create a new plugin
2. Register the field.
3. Create a new collection and add the field through **{collection-name}.settings.json** model.
4. Configure the collection view and add the field to be displayed
5. Refresh the collection view page

### Expected behavior

I expect to see the registered value in the view table.

### Screenshots

<img width="780" alt="Screenshot 2021-09-28 at 12 52 15" src="https://user-images.githubusercontent.com/47194599/135065366-aa26a750-b747-4e1e-8407-c73aa57c7150.png">
<img width="313" alt="Screenshot 2021-09-28 at 12 55 15" src="https://user-images.githubusercontent.com/47194599/135065695-d6f2fc8f-7cb8-4580-8701-af518f41ed9c.png">

### System

- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Database: default
- Operating system: MacOS 11.6

**Comment by antoci-alin** [comment]
> Can you share the {collection-name}.settings.json model?

Sure! Here:

`{
  "kind": "collectionType",
  "collectionName": "carousel_items",
  "info": {
    "name": "carousel-items"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true,
    "privateAttributes": [
      "created_by",
      "created_at",
      "published_at",
      "updated_at",
      "carousel"
    ]
  },
  "pluginOptions": {},
  "attributes": {
    "ref": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "title": {
      "type": "string"
    },
    "body": {
      "type": "richtext"
    },
    "hint": {
      "type": "string"
    },
    "image_url": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "distance": {
      "type": "biginteger"
    },
    "carousel": {
      "via": "items",
      "model": "carousel"
    },
    "tenantlist": {
      "type": "tenantList",
      "columnType": "biginteger"
    }
  }
}`

**Comment by sunnysonx** [comment]
When you are trying to edit the entity, is the value also missing? Or its missing just from the table list?

**Comment by antoci-alin** [comment]
> When you are trying to edit the entity, is the value also missing? Or its missing just from the table list?

If I try to edit the entity, the value is there.  It’s  only missing from  the table list. Better said, it’s replaced with the “-“ sign, as you can see in my screenshots.
