### ISSUE TITLE
Need Array Fields about general data types.

### ISSUE THREAD

**Issue by Aurelyn10** [strapi/strapi#1111]
How can I create multiple items (array) in the number or string fields in Content Type Builder plugin?
I want same key name/different value pairs, like as array or list.
I want to put multiple datas in one field like as current media field ( It has  the option of “Allow multiple files”.)
Thank you.

**Comment by enoy** [comment]
I also often need to create multiple items (array or list) in the number/string/text/media fields in Content Type Builder plugin. Is there a way to do this?
