### ISSUE TITLE
[users-permissions plugin] Update role's permission through GraphQL API

### ISSUE THREAD

**Issue by lakatostamas** [strapi/strapi#11126]
First of all, sorry for not opening this on your `productboard` but I am not sure whether I am approaching the problem from the wrong direction or it's a valid request.

### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue** (nope, but please read my comment above)
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

I am building a React application in front of the Strapi API and I am using GraphQL plugin and Apollo client on the frontend. I am trying to implement a feature where the users can modify the existing roles within my client application. Unfortunately, the `users-permissions` plugin's GraphQL interface only accepts `ID`s in the `updateRole` payload.
![image](https://user-images.githubusercontent.com/17593456/135233069-8a137365-67d6-4464-8f51-c15b13fde977.png)
 
The problem is that, that I can only send the existing permission IDs here without any modification. There is no way to create new permissions through the GraphQL api or modify existing ones, thus there is no way to update the role's permission. However, if I would use the REST API instead of GraphQL, I would be able to modify the users permissions because I could send new roles in the payload: https://github.com/strapi/strapi/blob/d91569c3b6061e51116db367fc25fc6a2881ee04/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L382

### Summary

It would be great if we could have a way to modify existing permission via the GraphQL API.

### Why is it needed?

Currently, there is no way to update the role's permission programmatically via the GraphQL API. Alternatively, the developers can use the REST`/roles/:role` PUT endpoint for updating the permission and GraphQL for everything else, which can be inconvenient and can lead to state desync between Apollo client and the React component.

### Suggested solution(s)

A new GraphQL mutation:
```
 mutation UpdatePermission($input: updatePermissionInput!) {
  updatePermission(input: $input) {
   permission {
    id
    ...
   }
  }
 }
 ```

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
Should already be possible in v4 now
