### ISSUE TITLE
How can I add search bar and CSV file download button on the content manager page?

### ISSUE THREAD

**Issue by Aurelyn10** [strapi/strapi#1112]
Keystone.js has the feature.
http://demo.keystonejs.com/keystone/galleries  
(Sign in with the username _demo@keystonejs.com_ and the password **_demo_**)
I attached the screenshot.
![screenshot](https://user-images.githubusercontent.com/35254636/39603401-d02a946e-4f5a-11e8-992a-e42b2ab9a413.png)

Thank you.

**Comment by soupette** [comment]
You can either modify the `content-manager` plugin or create a new plugin for that.

If you feel like developing one we can provide you with our thoughts on how it should be working and what the design will look like.
