### ISSUE TITLE
Can't install strapi v4 beta - Cannot find module 'strapi-utils'

### ISSUE THREAD

**Issue by neo7-studio-web** [strapi/strapi#11136]
Node v14.16.1
Windows 10

Fresh install : 
`npx create-strapi-app@beta beta --quickstart`

At step of building admin ui, errors : 
`ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'C:\Users\karel\Node\strapi-v4-beta\beta\.cache\admin\src'`

`Field 'browser' doesn't contain a valid alias configuration resolve as module`

Redoing strapi build
`Error: Cannot find module 'strapi-utils'`

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
