### ISSUE TITLE
Localization Plugin Breaks

### ISSUE THREAD

**Issue by Saad-ISAA** [strapi/strapi#11140]
## Bug report
Admin panel crashes with a white screen and a console error on Internationalization page.
### Describe the bug
When we select a locale, and click advanced, then click Basic again will reproduce the error.
Screenshots are attached

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/admin/settings/internationalization`
2. Click on 'Add Locale'
3. Select a Language from 'Locales' dropdown
4. Click 'Advanced Settings'
5. Click 'Base Settings' back
6. Screen turn white 

### Expected behavior

Base settings should be displayed with the selected locale

### Screenshots
![image](https://user-images.githubusercontent.com/63791098/135326876-f12d58f9-c153-4b94-920b-d11e8537668d.png)

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
confirmed on 4.0.0-beta.0

**Comment by derrickmehaffy** [comment]
fixed in beta.2
