### ISSUE TITLE
Admin Panel Freeze on Email Test

### ISSUE THREAD

**Issue by Saad-ISAA** [strapi/strapi#11142]
## Bug report
When we try to test the email testing option in settings, the UI freezes without any information.

### Describe the bug
In v3, if the we test the email, it the loader will keep spinning but the admin panel works, however in v4-beta, the UI freezes.
The email provider is not cofigured, and this is tested in localhost.

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/admin/settings/email`
2. Type a valid email address in ' Send a Test Email '
3. Click 'Test Email'
4. UI Freezes

### Expected behavior
Either an error message should have been displayed after timeout,
or the UI should not freeze

### Screenshots
![image](https://user-images.githubusercontent.com/63791098/135329916-bc924db9-3e0a-44b1-aa37-bcb17e15c0e5.png)

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating system: Ubuntu 20.04

### Additional context

The email provider is not configured so the email will not be sent in the first place, however the error should be displayed without freezing the UI. Expected error is ' Timeout'

**Comment by MattieBelt** [comment]
@Saad-ISAA can't reproduce the UI freeze: https://www.loom.com/share/c06ca938da074122bdf32c5ba32953a8
Can you share some logs?

**Comment by Saad-ISAA** [comment]
@MattieBelt here is a screen record of the issue with terminal logs
[https://www.loom.com/share/47a92d586e414a908435a7cfc7fa41de](url)

nothing is logged even after a long time

**Comment by derrickmehaffy** [comment]
Can't reproduce in beta.4 Will close if no one else can provide additional information
