### ISSUE TITLE
FindOne content-api always returns 403 regardless of permission settings

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11141]
### Describe the bug

All find one routes will return a 403 error regardless of the settings set in users-permissions

All other routes appear to function normally including update with the ID

### Steps to reproduce the behavior

1. Create a collection-type
2. Add some data
3. Set permissions in U&P to allow find and findOne
4. Attempt to go to `/api/CTNAME/1`
5. See error

### Expected behavior

Properly validates permissions

### Screenshots

N/A

### Code snippets

N/A

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating system: Linux Mint 20.2

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Confirmed earlier with @Mcastres (original reporter)

**Comment by alexandrebodin** [comment]
Fixed by https://github.com/strapi/strapi/pull/11133

**Comment by Jbmanllr** [comment]
Hello, ok but, when will release the fixed version? So people can actually test the beta.

**Comment by alexandrebodin** [comment]
This has been released in beta.1

**Comment by Jbmanllr** [comment]
> This has been released in beta.1

Hi, ok thanks, how do i keep track of new beta releases and update it? For example, where does the beta.1 has been released?
npm outdated state that the latest release is 4.0.0-next.0

**Comment by alexandrebodin** [comment]
you can do `npm info @strapi/strapi dist-tags` to see the last version for each tag :)

**Comment by Jbmanllr** [comment]
> npm info @strapi/strapi dist-tags

Thanks !

**Comment by Jbmanllr** [comment]
> you can do `npm info @strapi/strapi dist-tags` to see the last version for each tag :)

Also, i don't want to create a thread for this, but is it normal that so many plugins are missing from beta? Is it possible to test with file upload plugin?

**Comment by derrickmehaffy** [comment]
> > you can do `npm info @strapi/strapi dist-tags` to see the last version for each tag :)
> 
> Also, i don't want to create a thread for this, but is it normal that so many plugins are missing from beta? Is it possible to test with file upload plugin?

Yes this is normal, their backend parts exist and are functional but the frontend teams have not finished migrating views.

As a sub point it's best to do this type of discussion on our community discord as we have a dedicated channel for these questions. 

https://discord.strapi.io

**Comment by Jbmanllr** [comment]
> > > you can do `npm info @strapi/strapi dist-tags` to see the last version for each tag :)
> > 
> > 
> > Also, i don't want to create a thread for this, but is it normal that so many plugins are missing from beta? Is it possible to test with file upload plugin?
> 
> Yes this is normal, their backend parts exist and are functional but the frontend teams have not finished migrating views.
> 
> As a sub point it's best to do this type of discussion on our community discord as we have a dedicated channel for these questions.
> 
> https://discord.strapi.io

Ok, anyway to install file upload?

**Comment by Jbmanllr** [comment]
> > > you can do `npm info @strapi/strapi dist-tags` to see the last version for each tag :)
> > 
> > 
> > Also, i don't want to create a thread for this, but is it normal that so many plugins are missing from beta? Is it possible to test with file upload plugin?
> 
> Yes this is normal, their backend parts exist and are functional but the frontend teams have not finished migrating views.
> 
> As a sub point it's best to do this type of discussion on our community discord as we have a dedicated channel for these questions.
> 
> https://discord.strapi.io

Nobody is answering there, so i try again here, maybe the answer is very simple yet i can't find any clue about how to make file upload and media manager to work with v4 beta? Which packages do i need to install?

**Comment by derrickmehaffy** [comment]
I'm locking this as I already responded to you on Discord. Please do not spam trying to get an answer, we will respond on Discord when we have time.
