### ISSUE TITLE
[v4] Make re-orderable UI elements available for relations again

### ISSUE THREAD

**Issue by flipswitchingmonkey** [strapi/strapi#11147]
### Describe the feature request

This could arguably also be a feature request, but it feels more like a regression...

In v3 Relation fields would use a re-orderable UI element. Even though re-ordering was not supported out of the box, it could be implemented like e.g. so: https://forum.strapi.io/t/save-relation-items-order-issue-2166/332/43

### Expected behavior

I would like to at have at least an option to show the re-orderable UI element for Relation fields as in v3.

### Screenshots

The UI element in v3:
![image](https://user-images.githubusercontent.com/6930367/135345606-802b7c26-6b79-44b3-9a0b-3d019ffdef3b.png)

In v4 beta:
![image](https://user-images.githubusercontent.com/6930367/135345714-aea1dbda-202b-4a60-965d-a8754c79929b.png)

**Comment by derrickmehaffy** [comment]
Edit'ed OP to make it a feature request

**Comment by abdonrd** [comment]
I'm also very interested in this.

We need to display the results in that order (we cannot rely on any content-type field to be able to sort).

**Comment by abdonrd** [comment]
I share our situation in case it could be of help.

We have events, which take place on a date. In each event, a number of matches are held.
The matches have been previously announced, so they are already registered.
So we have an event like:

> - name: 'My event'
> - date: 19/12/2021
> - matches:
>   - match#1
>     - participants: profile#1, profile#2
>   - match#2
>     - participants: profile#3, profile#4
>   - match#3
>     - participants: profile#5, profile#6

But the order of the matches is drawn on the day of the event.
We need to reorder the matches to be able to show them in the order in which they are made.
So we have the event like:

> - name: 'My event'
> - date: 19/12/2021
> - matches:
>   - match#3
>     - participants: profile#5, profile#6
>   - match#1
>     - participants: profile#1, profile#2
>   - match#2
>     - participants: profile#3, profile#4

**Comment by CoenWarmer** [comment]
This for us is the only thing holding us back from adopting Strapi.

**Comment by flipswitchingmonkey** [comment]
We moved to Directus for this because this was non-negotiable.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/2166
