### ISSUE TITLE
[V4] (UI) The "Add/Edit" modal is too big

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11148]
### Describe the bug

This may be still under development and is not actually intended, but if that's not the case - the new popup modal is crazy big, at first it made me think that I'm zoomed in a bunch.
The new design looks fantastic, but this really adds a big stink - IMHO.

### Steps to reproduce the behavior

1. Go to Content Type builder
2. Add a content type or a edit a field

### Expected behavior

IMHO, the modal should be significantly smaller to provide a better, more pleasant UX.

### Screenshots

<img width="1792" alt="Screen Shot 2021-09-30 at 12 35 15 AM" src="https://user-images.githubusercontent.com/11737572/135351914-499d689d-b130-4938-b880-c188ebc2800b.png">

## PS. 
Also the buttons smell fishy and the overall modal layout is broken, so I'll assume that this is simply still work in progress and is not needed to be reported.

If that's the case, pardon the interruption. :) 

<img width="1488" alt="Screen Shot 2021-09-30 at 12 41 18 AM" src="https://user-images.githubusercontent.com/11737572/135352580-21680518-d018-4cc9-af70-6fc244d87ad6.png">

**Comment by LucaNerlich** [comment]
UI is still in alpha and activly being worked on. These "issues" are all known and will be handeled.

**Comment by MattieBelt** [comment]
Confirmed on strapi `4.0.0-beta.0`

**Comment by derrickmehaffy** [comment]
Will be fixed once we get to migrating the "view" for the CTB. The current as of beta.2 is temporary as we needed the CTB to be semi-functional for testing. The frontend team is still working on fully migrating multiple views from Buffet to the new design system.

**Comment by sam-pires** [comment]
Hey

Related to this issue, I have a missing font in the new CTB modal > Settings tab

<img width="1440" alt="Capture d’écran 2021-10-05 à 21 07 17" src="https://user-images.githubusercontent.com/25405887/136087413-1e53bdee-5458-4b15-ab45-2cceba9d6c04.png">

And Congrats team! Niiiiiiiice work 🤩  love it

**Comment by derrickmehaffy** [comment]
oooooo @sam-pires ! Hiyo o/

Yeah the frontend team hasn't finished migrating the CTB view yet so it's still a hybrid of v3/v4 during the beta. They are working on migrating that view here very shortly.

**Comment by derrickmehaffy** [comment]
Fixed in beta.6 or beta.7 can't remember which, issue is fixed though

**Comment by ScottAgirs** [comment]
> Fixed in beta.6 or beta.7 can't remember which, issue is fixed though

`beta.7` had this addressed
