### ISSUE TITLE
v4 does not show the correct version

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11150]
### Describe the bug

Opening the Strapi Application Info Page does not display the correct installed version.

`http://localhost:8000/admin/settings/application-infos`

### Steps to reproduce the behavior

1. Create new Strapi Setup via `npx create-strapi-app@beta beta --quickstart`
2. Open `http://localhost:8000/admin/settings/application-infos`
3. Observe that the displayed version is still 3.6.8

### Expected behavior

Application Infos Page correctly displays the installed version - `4.0.0-beta.0` in this case.

### Screenshots

![image](https://user-images.githubusercontent.com/5942270/135414174-848ea9c5-444b-4101-b505-209f45366831.png)

### System

- Node.js version: v14 LTS
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating system: MacOS

**Comment by mbistuer** [comment]
Hello  @MattieBelt  , @kasonde  
I have looked and pointed to this API https://api.github.com/repos/strapi/strapi/releases/latest
property: tag_name

it would have to change the resource or add to the list of releases

**Comment by oscarsandberg** [comment]
@mbistuer Agree! 

At the moment the version is displayed as you say as the latestReleaseTag. I think it should be derived from the package.json instead as this shows the current used version and not the latest released version. What do you think?

**Comment by LucaNerlich** [comment]
This is super easy

```javascript
import packageJson from '../../package'

function AppVersion() {
    const appVersion = `${packageJson.version}`
}
```

**Comment by oscarsandberg** [comment]
Yes, my suggestion would be to add a value to the AppInfosContext, currentStrapiVersion: strapiVersion. But the version is "wrong" there as well.

**Comment by JabStrapi** [comment]
Fixed in beta.8. Thanks for your report.
