### ISSUE TITLE
v4 content manager table does not show / filter by created/updated timestamp

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11151]
### Describe the bug

In the v4 content manage one cannot add created_at and/or updated_at to the table of added entries. This was possible in v3 (however, the used timeformat was too large (e.g Wednesday, September, xxxx was to wide to be readable).

### Steps to reproduce the behavior

1. Create new Strapi Setup via `npx create-strapi-app@beta beta --quickstart`
2. Create any new Content Model with any fields
3. Create new instance of this model
4. Click the 'add new filter' Button top right of the content table
5. Observe that created_at and updated_at are not available.

### Expected behavior

As a user, I am able to add created_at and updated_at as filterable columns in the content manager. This works in v3.

### Screenshots

![image](https://user-images.githubusercontent.com/5942270/135414680-57f2bfcd-c408-4b41-ac10-1ccae2fa933a.png)

### System

- Node.js version: v14 LTS
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating system: MacOS

**Comment by oscarsandberg** [comment]
Is there a reason that they have been removed? Otherwise I can take a look at it :)

**Comment by LucaNerlich** [comment]
Since kasone (employee) labeled this as a bug, I assume it just has not been ported.

**Comment by derrickmehaffy** [comment]
Yes it's a bug

**Comment by derrickmehaffy** [comment]
Confirmed on beta.11

**Comment by alexandrebodin** [comment]
This is now available in beta.13
