### ISSUE TITLE
Strapi states you need to create database manually

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1115]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: 10.2.14-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
When creating a new content type the adminUI still states to create the table manually: 

![image](https://user-images.githubusercontent.com/8593673/39623958-46a34fe6-4f4c-11e8-869e-1054c6853405.png)

**Steps to reproduce the problem**
Setup a new strapi instance with mysql, create a new content type

**What is the expected behavior?**
Message should not show, as it is no longer required.

**Suggested solutions**
Remove message

- [x] I'm sure that this issue hasn't already been referenced

**Comment by Aurelsicoko** [comment]
We should update the message but we also need to consider this issue https://github.com/strapi/strapi/issues/1114#issuecomment-387016732

**Comment by derrickmehaffy** [comment]
I agree instead of removing the message it should be updated to state how Strapi currently handles the database.

**Comment by derrickmehaffy** [comment]
Also I'm not entirely sure where this message is to update, but I wouldn't mind doing it, I haven't had much success in modifying the AdminUI and rebuilding it. @Aurelsicoko any suggestions you might have and I can try and update this and submit a PR.

**Comment by derrickmehaffy** [comment]
Ah might have found it, can you confirm if I change it in this file:

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-type-builder/admin/src/translations/en.json

`
"noTableWarning.description": "Don't forget to create the table `{modelName}` in your database",
`

That it will change it without rebuilding the admin? I'm not sure if the admin is built on initial install of the package or before that. If its built on initial install then modifying this file should update correctly.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy Yes, it seems the good one. Don't forget to update the key in the others languages if you can.

Check out [the contributing guide](https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md#setup-development-environment) to setup the development environment. You will be able to make updates in the administration of your project and see the changes in real-time without refreshing the page.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I am really only good in english :/ I could attempt a very rough and likely terrible translation using google translate but as we all know that isn't quite the same :P

**Comment by Aurelsicoko** [comment]
Ahahaha why not? No, seriously don't try if you're not sure... we will be able to make the French translation on our side.

**Comment by derrickmehaffy** [comment]
I need to get a little more familiar with setting up the dev env as previous attemps haven't worked out so well :P
