### ISSUE TITLE
Core store's set functions has no default values

### ISSUE THREAD

**Issue by aPisC** [strapi/strapi#11159]
### Describe the bug

The core store can not read back the stored value, if the type is not set when creating the store object (default value of type should be `'core'`).

### Steps to reproduce the behavior

The following code snippet can reproduce the bug

```
const store = strapi.store({
  // type should be 'core' by default 
  // environment is the current environment
  name: 'custom_store',
});

await store.set({key: "v1", value: "something"}); 

const v1 = await store.get({key: "v1"}); // returns null
```

### Expected behavior

In the exaple above, the value of v1 should be `"something"`, but the store.get returns `null`. 

### System

- Node.js version: 14.10
- NPM version: 6.4.17
- Strapi version: 3.6.5
- Database: SQLite
- Operating system: Arch 5.8.7.arch1-1

### Additional context

The problem is that the set function has no default value for the type, and saves the value with `undefined_custom_store_v1` identifier. The get function has default value for type, and tries to read by `core_custom:store_v1` , which won't exist in the database.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by aPisC** [comment]
Updated the original comment based on the guidelines.
