### ISSUE TITLE
[FR] [v3/v4] Content Manager uses a too verbose timeformat to display created_at fields

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11152]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

The v3 Content Manager Table uses a verbose timeformat to display created_at and updated_at fields. Even on a regular fullhd screen, as soon as one adds a couple of other displayed fields, the dates are not readable anymore.

![image](https://user-images.githubusercontent.com/5942270/135415336-6244efa9-63a7-48dc-a7f8-c27cf44f8af4.png)

Clarification: the Field 'Erstellt am' is just the ootb 'created_at' field, but renamed visually.

### Suggested solution(s)

Either choose an abbreviated version e.g Wed, Sep, 21-09-30 etc, or let the user choose the displayed format via settings possibly? Id like to display the date as 2021-09-30. This should fit even in small columns.

### System

- Node.js version: v14 LTS
- Strapi version: 3.6.8
- Database: PostgreSQL
- Operating system: Windows 11

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12216
