### ISSUE TITLE
[v4][GraphQL] Unable to add enumerations to collections/components named with more than one word

### ISSUE THREAD

**Issue by Nirlah** [strapi/strapi#11153]
### Describe the bug

Can’t start the server with GraphQL plugin installed with Collection/Components named with more than one word and contains an enumeration.
The server won’t start and show the error: `GraphQLError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "ENUM_FOO-BAR_DEMOENUM" does not.`.

- Both when installing GraphQL for a project with existing problematic types and when creating the first problematic type after installing GraphQL.
- Both for collection/components named `fooBar` and `Foo Bar`.
- Deleting the type allows the server to start.

_I think it’s because the generated enumeration type that contains the parent type has `-` instead of `_` in the section of the parent type._

### Steps to reproduce the behavior

1. Install the GraphQL plugin in an empty v4 beta installation.
2. Add a new type, name it `fooBar` or `Foo Bar`.
3. Add to it an enumeration field.
4. The server won’t be able to start and show an error.

### Screenshots
<img width="852" alt="Screen Shot 2021-09-30 at 11 49 55" src="https://user-images.githubusercontent.com/1909713/135420044-7c812238-a6aa-422e-8722-f39a46edacf6.png">

### System

- Node.js version: 14.18.0
- NPM version: 6.14.15
- Strapi version: v4-beta.0
- Database: Sqlit
- Operating system: Mac

**Comment by Convly** [comment]
Hello, thanks for reporting the issue, It should be fixed in the upcoming beta release :slightly_smiling_face:
