### ISSUE TITLE
Error when customise admin dashboard

### ISSUE THREAD

**Issue by Aurelyn10** [strapi/strapi#1116]
*BUG TEMPLATE* 

**Informations**
- **Node.js version:   9.10.1**:
- **npm version:     5.6.0**:
- **Strapi version:  3.0.0-alpha.12.1.2**:
- **Database: Mongodb 3.4 ( mLab) **:
- **Operating system:  macOS 10.13.4**:

**What is the current behavior?**
I want to know how I customise the admin dash board.
For example, I want to change the left top logo icon.
https://strapi.io/documentation/advanced/customize-admin.html
I tried to follow this, but terminal command ” ln, npm start, build” not working for me, so could not create new build.
Following is the log on the terminal.
And I attached screenshot.
```
Error: Cannot find module '/Volumes/Data/backend/admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.1.2 prebuild: `APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.1.2 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2018-05-04T05_07_09_129Z-debug.log
```
---

*FEATURE REQUEST TEMPLATE*  

**What is the expected behavior?**
I want to compile dashboard with customizing such as changing logo, removing "General" tab from the left side bar.
---

- [ ] I'm sure that this issue hasn't already been referenced

![screenshot at may 04 17-32-53](https://user-images.githubusercontent.com/35254636/39633726-70ef1f44-4fc1-11e8-94c6-55f1fc007dd5.png)

**Comment by lauriejim** [comment]
Hello @Aurelyn10 can you fix your issue message template (it's little bit unreadable)

**Comment by soupette** [comment]
Hi @Aurelyn10 

We need to update the documentation but in order to rebuild the admin you need to run
**`npm run setup`** at the root of your project

**Comment by Aurelyn10** [comment]
Ok I attached the terminal log screenshot and updated.

**Comment by Aurelyn10** [comment]
Whenever changing something, is it taking time with installing package?
There is no auto compilation feature like as webpack?

**Comment by soupette** [comment]
You need to start your app in dev mode to have the autoreload.
Please refer to the [documentation](https://strapi.io/documentation/plugin-development/quick-start.html#plugin-development-setup)

**Comment by Aurelyn10** [comment]
I followed and did like this:
1. Development Environment Setup
   To setup the development environment please follow the instructions below:
      1)  Fork the repository to your own GitHub account.
      2) Clone it to your computer git clone git@github.com:strapi/strapi.git.
      3) Run npm run setup at the root of the directory.
2. Plugin development Setup
   Create a development project
       1) Go to a folder on your computer cd /path/to/my/folder.
       2) Create a new project strapi new myDevelopmentProject --dev.
3. I do not create my own plugin, just want to customize current admin dashboard, so did NOT follow next instruction this:
" To generate a new plugin run the following commands: ... "
Instead of that, I did following from the document https://strapi.io/documentation/advanced/customize-admin.html#deployment
     Development mode
         #1 — Install its own dependencies
         Run npm install from the ./admin folder.
         #2 — Launch the development server
        Run npm start from the ./admin folder. That's all.
        #3 — Go to the browser
       You should be able to see the admin at http://localhost:4000/admin.
But It shows this error on the browser and terminal:
 `ERROR in Entry module not found: Error: Can't resolve '/Volumes/Data/backend/plugins/analytics/node_modules/strapi-helper-plugin/lib/src/app.js' in '/Volumes/Data/_Backend/strapi/packages/strapi-admin'
`
What is wrong ?

**Comment by Aurelyn10** [comment]
In my test project folder, run command : cd plugins/analytics && npm link strapi-helper-plugin.
so the error was disappeared, but admin page is blank in web browser, where is your admin page?

**Comment by soupette** [comment]
@Aurelyn10 do you have your `strapi server` running? 
> `cd my-app && strapi start`

***Did you follow these instructions?***
``` 

// Create a folder and install Strapi
$ mkdir repositories && cd repositories && git clone git@github.com:strapi/strapi.git (or your fork)
$ cd strapi && npm run setup

// Create a dev app
$ cd .. && strapi new my-app --dev
// When you're app is created
$ cd my-app && rm -rf plugins/analytics
$ strapi start

// In another terminal window
$ cd my-app/admin && npm start 

// When you're done with your modifications
$ cd my-app && npm run setup ---plugins

// You can rebuild the plugins by running 
$ cd repositories/strapi && npm run setup:build
```
If you followed this instructions it should be working localhost:4000/admin and register your first user.

**Comment by Aurelyn10** [comment]
It works now, Thank you for your help.

I will wait for more detailed documentation.
