### ISSUE TITLE
Strapi V4 - How to install Graphql

### ISSUE THREAD

**Issue by Jbmanllr** [strapi/strapi#11166]
Hello, there is no plugin interface on V4. What version of graphql plugin am i supposed to install?

**Comment by LucaNerlich** [comment]
It will be available, once the marketplace has been integrated.

**Comment by Jbmanllr** [comment]
> It will be available, once the marketplace has been integrated.
> 
> If you need it now, try to install the plugin via packagejson "manually".

Yes, but i believe the graphql plugin v4 has been reworked? Where is the new beta package, or do i have to install the regular one with "npm run strapi install graphql" as stated here: https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#usage

**Comment by LucaNerlich** [comment]
just try `"strapi-plugin-graphql": "^3.6.8",` with the new beta0 version. No idea, if it has been ported already, though.

**Comment by Jbmanllr** [comment]
yarn strapi install graphql did the job, thanks

**Comment by alexandrebodin** [comment]
the package is @strapi/plugin-graphql :)
