### ISSUE TITLE
How to login admin user via programmatically (/admin/auth/login)?

### ISSUE THREAD

**Issue by krishnafr123** [strapi/strapi#11178]
### System

- Node.js version: v12.14.1
- NPM version: 6.13.4
- Database: MYSQL
- Operating system: MAC

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
