### ISSUE TITLE
Heroku Application Error after deploying

### ISSUE THREAD

**Issue by Gamalliel19** [strapi/strapi#11170]
### this is the code inside ./env/production/database.js
![Screen Shot 2021-10-02 at 17 19 22](https://user-images.githubusercontent.com/56964467/135712222-92d40622-db6a-4a03-a108-d95ac551388d.png)

### package.json
![Screen Shot 2021-10-02 at 17 18 31](https://user-images.githubusercontent.com/56964467/135712197-021c053e-823c-4fb9-aea3-c2ef9b250b4e.png)

### Heroku Logs --tail
![Screen Shot 2021-10-02 at 17 21 33](https://user-images.githubusercontent.com/56964467/135712279-65dc9b02-f9a3-4ad9-90b1-0c19418ef197.png)

![Screen Shot 2021-10-02 at 17 21 01](https://user-images.githubusercontent.com/56964467/135712261-784ba1c0-96f9-4a12-a286-34f02eff61d5.png)

![Screen Shot 2021-10-02 at 17 20 27](https://user-images.githubusercontent.com/56964467/135712252-5ec9a5cf-ea1f-42ac-81d7-15a6b156ff4a.png)

**Comment by nicogulo** [comment]
I have some issues like this and doesn't solve

**Comment by ChristianHeimke** [comment]
Just guessing, but it seems to be that you are not passing the extracted values from the connection string correctly to the postgres connector.

This is a working example of one strapi project hosted on heroku:

```
# file: config/env/production/database.js

const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: config.host,
        port: config.port,
        database: config.database,
        username: config.user,
        password: config.password,
        ssl: {
          rejectUnauthorized: false,
        },
      },
      options: {
        ssl: true,
      },
    },
  },
});

```

This is also described here: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html

Also, please check the the ENV var of the connection string injected correctly.

**Comment by derrickmehaffy** [comment]
Please keep in mind that environmental issues, unless they can be traced back to a specific code issue, should be posted on our forum and not GitHub.

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
