### ISSUE TITLE
[v4] How to create a new project using Yarn ?

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#11172]
### Describe the bug

I can't create a new project using Yarn. Only npx worked.

### Steps to reproduce the behavior

1. Open terminal.
2. Type `yarn create strapi-app@beta <project-name> --quickstart`
3. See error

### Expected behavior

I can get a v4 Strapi app using Yarn.

### Screenshots

may I install it using Yarn ? I tried it but failed : 

![image](https://user-images.githubusercontent.com/43397636/135738327-b56a81a1-98b0-4f1f-8b67-7c17539ce7d0.png)

Meanwhile NPM did the job : 

![image](https://user-images.githubusercontent.com/43397636/135738322-bcc054c2-ddf8-40d6-aa04-bc345ca71ea9.png)

### System

- Node.js version: 14.17.5
- NPM version: 6.14.14
- Yarn version : 1.22.11
- Strapi version: trying to create a Strapi v4 beta project
- Database: SQLite
- Operating system: Ubuntu 20.04

Any help is appreciated.

**Comment by derrickmehaffy** [comment]
At the moment, it's not possible to specify the version using yarn. 

See: https://github.com/yarnpkg/yarn/issues/6587

Closing as this isn't something we can "fix" per-say and when v4 goes stable the issue won't be a problem just like the current v3 implementation isn't an issue.
