### ISSUE TITLE
[v4] How to fetch data in a collection-type ?

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#11173]
### Describe the bug

Hi, I did the exactly same way to fetch data from a collection-type as I did in previous Strapi versions such as 3.6.8, but I could not do it in Strapi v4 beta version (4.0.0-beta-1).

I installed Strapi v4 beta (`npx create-strapi-app@beta beta --quickstart`) and tried to fetch data from a collection-type in Strapi v4 beta. Somehow I can not fetch it through `http://localhost:1337/<collection-type name>`.

### Steps to reproduce the behavior

1. I created a collection-type named baseball. Then I set public roles permission to allow `find` and `findOne`.

![image](https://user-images.githubusercontent.com/43397636/135738472-c270c5a6-ce4a-4724-9d9b-6bdcffc7987d.png)

2. I already added data and they are published.

![image](https://user-images.githubusercontent.com/43397636/135738479-68b3630d-a193-4b63-b0e7-e8222a81ecf9.png)

3. However, I can not get them via http://localhost:1337/baseballs.

![image](https://user-images.githubusercontent.com/43397636/135738488-bc0ea0b3-7bc8-4630-b294-22b2bb8b562f.png)

`http://localhost:1337/baseball/1` did not work too.

### Expected behavior

`http://localhost:1337/<plural collection-type name>` will show me the data.
For instance, `http://localhost:1337/baseballs` gets me the whole data in the collection-type named `baseball`.

### Screenshots

Added above.
### Code snippets

I did not modify the code at all.

### System

- Node.js version: 14.17.5
- NPM version: 6.14.14
- Strapi version: 4.0.0.-beta-1
- Database: SQLite
- Operating system: Ubuntu 20.04

Any help is appreciated.

**Comment by Convly** [comment]
Hi, starting with V4, the auto-generated REST endpoints are accessible via the `/api` router. Try using `http://localhost:1337/api/baseballs` and let me know if it fixed your issue :slightly_smiling_face:

**Comment by Convly** [comment]
Also, by selecting an action in the U&P plugin you can see the bound API route. It should show you the `/api` prefix.
![image](https://user-images.githubusercontent.com/25851739/135821202-0ee8469f-e767-4d92-83b5-a6a90b15c0fc.png)

**Comment by kevinadhiguna** [comment]
Thanks @Convly  ! 

`http://localhost:1337/api/baseballs` gave me exactly what I wanted.
