### ISSUE TITLE
[v4]: Layout switches between content-manager and content-types builder

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#11189]
## Bug report

The spacing on the left navigation changes when switching between the content-manager and the content-types builder.

![recording](https://user-images.githubusercontent.com/2244375/136020130-366a4c6e-8291-45cb-a069-107628c1243c.gif)

### Steps to reproduce the behavior

1. Open v4 Admin
2. Click on 'Content-Types Builder'

### Expected behavior

The sidebar navigation stays consistent.

### System

- Strapi: 4.0.0-beta.2
- Operating system: Ubuntu / Firefox 94

**Comment by derrickmehaffy** [comment]
fixed in beta.6 I believe (could be beta.7) Either way, issue no longer exists :)
