### ISSUE TITLE
[v4] Content Manager Design Feedback

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#11191]
### Selected fields label

The label "4 currently selected" doesn't make too much sense, if you don't know the fields displays fields. I'd propose: "4 fields shown".

![Screenshot from 2021-10-05 14-31-14](https://user-images.githubusercontent.com/2244375/136023626-06486447-8f72-451c-a76c-7a74601af9e2.png)

### Edit icon button -> link

Each content manager item has a dedicated edit page. For our editors it would be super helpful if you could right-click the edit icon "open in a new tab", because it makes it much easier to bulk edit items. Also it's the proper HTML element.

### Filter field not persisted

It makes it almost impossible to filter the items. The field collapses after each keystroke.

![recording(2)](https://user-images.githubusercontent.com/2244375/136024232-20bf6777-8345-4c02-9c02-b539e5514ad5.gif)

### Delete action

I'd place the delete icon next to filters, so it doesn't has to push the table down.

![Screenshot from 2021-10-05 14-41-32](https://user-images.githubusercontent.com/2244375/136024410-03b4bfda-febf-4182-83ce-f7655e3d1d77.png)

### Updated at

When creating/ editing an item, as soon as a field is updated, the updated at timestamp changes even if you haven't saved the item yet. This is confusing, because it suggests auto-save which is not happening.

![Screenshot from 2021-10-05 14-42-46](https://user-images.githubusercontent.com/2244375/136024607-bd9e4116-1936-4283-99c6-28089bee3cac.png)

### Spacing left/ right

For my taste, the spacing on the left and right is bit too much and makes the form look very dense. 

![Screenshot from 2021-10-05 14-44-12](https://user-images.githubusercontent.com/2244375/136024845-435e0c79-70ce-4610-83a2-da1fbf4f3d25.png)

### Add filter looks off

In comparison with the "Add new entry" button on the top right, the button looks a bit off (font too big

![Screenshot from 2021-10-05 14-45-58](https://user-images.githubusercontent.com/2244375/136025124-af555750-144b-4e10-9473-bead2c45f36a.png)

### System

- Strapi version: 4.0.0-beta.2
- Operating system: Ubuntu / Firefox 94

**Comment by kasonde** [comment]
Hi @gu-stav , thanks for the feedback. Currently we'd love to keep the Github issue list only for issues but we have a dedicated place for feedback regarding the v4 release. [Here's a link](https://forum.strapi.io/t/strapi-v4-beta-is-live/11623) to the forum post for it. Please share this on that thread.
