### ISSUE TITLE
[v4]: Edge displays the toggle password icon twice

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#11190]
## Bug report

Screenshot

![Screenshot from 2021-10-05 14-24-19](https://user-images.githubusercontent.com/2244375/136022059-e88e991b-d8e4-49f4-9619-8175c19c4a27.png)

### Describe the bug

The reveal/ hide password icon is duplicated on password fields.

### System

- Strapi: 4.0.0-beta.2
- Operating system: Ubuntu / Edge 96.0.1028.0

**Comment by lmpham1** [comment]
It seems that Edge automatically adds its own password visibility control button for every `password` input field. According to [this documentation](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal), the following CSS code can be added to any pages with password input to disable Edge's default password visibility control:
```
::-ms-reveal {
    display: none;
}
```

I'd love to work on this issue, but I'm still unsure where to put the CSS code in this project. If anyone can point me in the right direction, I can give it a try and test this method.

**Comment by derrickmehaffy** [comment]
fixed in one of the betas, not sure which but is fine as of beta.11
