### ISSUE TITLE
reset password page for mobile

### ISSUE THREAD

**Issue by mejdi14** [strapi/strapi#11196]
## Feature request
reset password page for mobile
### Summary

When the user forget his password, the mobile app will ask for his email, using the forget-password api the user will receive a new email with a link to the reset-password page, well this will work fine for a web app but for a mobile app there is no way to get the code which the user received, is there a way to user Strapi default reset-password page instead of creating my own reset password page

### Why is it needed?

it's a waste of time to create a web page just for one feature for a mobile app

**Comment by Pablo-Aldana** [comment]
This can be solve by fixing the regular expression on the Reset password url and using deep-link more info on the issue raised here: https://github.com/strapi/strapi/issues/12629

**Comment by derrickmehaffy** [comment]
Not currently something we plan to work on
