### ISSUE TITLE
mongo_client error after adding field in existing Content Builder Type

### ISSUE THREAD

**Issue by srishti-56** [strapi/strapi#1120]
**Information**

Node.js version: v9.9.0
npm version: 5.6.0
Strapi version: 3.0.0-alpha.12.1.2
Database: v3.6.4-MongoDB
Operating system: Ubuntu 14.04 LTS

**What is the current behavior?**
I added an integer column to a Content Builder Type, called "Likes".
After clicking on Save, the server crashes and the following error is logged in the terminal:

```
".." /lib/mongo_client.js:804
          throw err;

TypeError: Cannot read property 'toLowerCase' of undefined
at Object.convertType ( ".." /node_modules/strapi-mongoose/lib/utils/index.js:12:28)
```

**What is the expected behavior?**
After saving the content builder type, the server is expected to restart and the page should reload with the change.

**Suggested solutions**
Check format of fields in Strapi server code before executing query on MongoDB

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by kamalbennani** [comment]
Please check your [Model].settings.json you are probably missing a model|collection key in the definition.

**Comment by srishti-56** [comment]
Thanks for the quick reply!
I haven't seen a collection key in any of the files, is there a way to insert it manually?
The Blogpost.settings.json file looks like this (the other [Model].settings.json file has a similar format with no new keys so I've only added this one for reference)

```
{
  "connection": "default",
  "collectionName": "blogpost",
  "info": {
    "name": "blogpost",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "Title": {
      "type": "string",
      "required": true
    },
    "Content": {
      "type": "text"
    },
    "PublishDate": {
      "type": "date"
    },
    "Author": {
      "via": "UserId",
      "plugin": "users-permissions"
    },
    "PostId": {
      "collection": "mediauploads",
      "via": "relatedToPost",
      "dominant": true
    },
    "Likes": {
      "type": "integer"
    }
  }
}
```

**Comment by lauriejim** [comment]
@srishti-56 Can you give me a log of variables used on the line 12 please.

**Comment by kamalbennani** [comment]
He has a missing model|collection in the Auhor attribute, isn't?
