### ISSUE TITLE
[v4]  Canceling a new CT in progress is not taken into account

### ISSUE THREAD

**Issue by sam-pires** [strapi/strapi#11203]
### Describe the bug
When trying to quit the CTB after I starte creating a new CT, I have a notification that requires me to save before leaving. When I click save it works, but if I click cancel instead and try to leave I get the notification again.

### Steps to reproduce the behavior

1. Go to the CTB
2. Click on Add a new CT
3. Add some fields
4. Close the fields modal and try to quit the page
5. See the notification
6. Click cancel
7. Try to quit the page
8. See the notification again

### Expected behavior
I don't know exactly what should happen after I click cancel (stay there with no more fields or be brought back to another page) 🤔  but I believe I should not have the notification when trying to quit the page at least

### Screenshots

<img width="1096" alt="Capture d’écran 2021-10-05 à 21 21 45" src="https://user-images.githubusercontent.com/25405887/136092360-f64aa196-76ee-48ba-9c20-4d1b12129602.png">

 ➡️ **[Loom](https://www.loom.com/share/12b5d7425f714895b14f2e5844a69a3a)** to see the bug

### System

Node.js version: 12.8.1
NPM version: 6.10.3
Strapi version: v4 beta2
Database: The quickstart one
Operating system: MacOS 10.14

**Comment by derrickmehaffy** [comment]
Fixed in one of the beta releases (don't remember which)
