### ISSUE TITLE
Error with Content-Type-Builder components in Docker image.

### ISSUE THREAD

**Issue by JoaquinC77** [strapi/strapi#11207]
I am creating a Strapi project, it is a blog, which works perfectly. But when creating the Docker image and running the project from Docker, it crashes when displaying the content of a collection which includes dynamic components, which seemed strange to me, since content types that have fixed fields work perfectly.
but as I said, the types of content that do have dynamic components. Those are broken, since it does not rescue any component from the database, nor does it allow me to show the information of that collection that has dynamic content in the dashboard

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
