### ISSUE TITLE
strapi.io website not working

### ISSUE THREAD

**Issue by rowild** [strapi/strapi#11200]
When I open the strapi.io website, I see only erroneous graphics, no texts. Only the very top bar and the footer have readable links. 

This is why I issue a bug report, because I cannot find - or see - a contact email. 
Sorry for misusing github issues for that and not sticking to the contributing guidelines!

This happens to on a Mac Catalina on every browser (Chrome, Firefox, Brave, Safari)

I included some screenshots. Hopefully you can fix that soon - thank you!
![Bildschirmfoto 2021-10-05 um 20 54 04](https://user-images.githubusercontent.com/213803/136085629-aa6218b1-290c-456b-af4c-3da8de02b64f.png)
![Bildschirmfoto 2021-10-05 um 20 54 10](https://user-images.githubusercontent.com/213803/136085633-e591fd59-d04b-43c2-be3d-1f1e0cb3b0cb.png)
![Bildschirmfoto 2021-10-05 um 20 54 17](https://user-images.githubusercontent.com/213803/136085641-ab4e26a7-96d5-4266-953c-c32b125951ec.png)

**Comment by derrickmehaffy** [comment]
I'm setting as closed but we can continue to discuss (closing as this does violate our requirements for opening GitHub issues on this repo.

It appears to load fine for me, can you give any screenshots of your browser console and network tabs?

![image](https://user-images.githubusercontent.com/8593673/136086284-0aa4c183-f0d5-481a-ad9e-2f4df5fe9401.png)

**Comment by rowild** [comment]
@derrickmehaffy Thank you for the fast feedback. Here are 2 screenshots from the console:

The first has errors that are due to adblocker and ublock.
The second shows the the same with adblocker deactivated.

![Bildschirmfoto 2021-10-05 um 21 13 43](https://user-images.githubusercontent.com/213803/136088176-89689a10-5959-433d-bcb0-e55a29378f9e.png)

![Bildschirmfoto 2021-10-05 um 21 13 11](https://user-images.githubusercontent.com/213803/136088169-97e04731-bf7b-492a-99c6-69b477477926.png)

**Comment by derrickmehaffy** [comment]
what the network tab? Can you check disable cache and force a refresh?

**Comment by rowild** [comment]
Here it is:

![Bildschirmfoto 2021-10-05 um 21 19 13](https://user-images.githubusercontent.com/213803/136088773-614f0332-b16c-4b54-bd60-d9bcd9e18fca.png)

**Comment by rowild** [comment]
@derrickmehaffy  If it is alright with you, I suggest to wait for 8 to 12 hours. It might quite well be a problem with my internet provider (DNS not flashed yet ...?)

**Comment by derrickmehaffy** [comment]
That's what it's looking like, you can try to adjust your DNS provider on your system to either Google's (8.8.8.8) or Cloudflare's (1.1.1.1)

You may need to restart your computer or flush your DNS cache, likewise you might need to flush your browsers cache too. Your ISP seems to have a pretty aggressive cache sitting on it and their DNS might be responsible for that.
