### ISSUE TITLE
username and email changes to logged in admin when editing a user record

### ISSUE THREAD

**Issue by jnetRepo** [strapi/strapi#11226]
Hello 👋 

### Describe the bug

The issue I noticed in the latest version (3.6.8) and the previous one is that when I login as an admin to the Strapi admin panel and attempt to edit a record from the Users Collection, the username and email (sometimes also first and last name too) get changed to the currently logged in admin. 

### Steps to reproduce the behavior

1. Login to Strapi admin panel
2. Go to (Users) collection
3. Before you click on any user you have on your screen, notice the username and email of the user you will click on. 
4. Once you click, you will get the edit page with some fields changed to the currently logged in admin such as username and email got changed in the screen. If you click save the record will be updated with the wrong email/username. 

### Expected behavior

What should happen is when you open the user edit page, nothing changes on the screen unless typed by the user. 

### Screenshots
This is the user edit screen: 
![image](https://user-images.githubusercontent.com/72245297/136667438-7f92cd01-a04a-4521-bb91-03b6d2af4a44.png)

### System

- Node.js version: 12.20.2
- NPM version: 6.14.11
- Strapi version: 3.6.8
- Database: AWS-RDS
- Operating system: Ubuntu

**Comment by jnetRepo** [comment]
I've tried using "incognito mode" but same issue occurs. Here's a vid (I hope quality is ok). Notice the quick change that happens between the seconds 09 and 10 of the video where the value will change after the user page opens. 

https://drive.google.com/file/d/102wp_HtKfTt8ictw1epBovg5eHus8_lD/view?usp=sharing

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!
