### ISSUE TITLE
admin panel outline

### ISSUE THREAD

**Issue by yunus-acar** [strapi/strapi#11225]
when the tab key is pressed in the strapi admin panel, the outline is visible on the buttons and links. it would be great if you make it outline:none :D

### Summary

when the tab key is pressed in the strapi admin panel, the outline is visible on the buttons and links. 
### Why is it needed?

because it distorts the image

### Suggested solution(s)

`*{outline:none}`

**Comment by LucaNerlich** [comment]
Please use the bug template :)
