### ISSUE TITLE
Dublicate subcategory slug cannot be for a seperate main Category 

### ISSUE THREAD

**Issue by glancer000** [strapi/strapi#11237]
Hey,

So I'm not 100% sure if this is a platform limitation or a bug. 

Strapi is giving me an error when trying to create a duplicate subcategory but for a new main Category.

For example, the subcategory is "basics" and there are 2 main categories that require that subsection.
www.site.com/marketing/basics
www.site.com/sales/basics

As you can see, I am getting an error when associated it with the second category.

![screenshot-oncore-backend herokuapp com-2021 10 09-14_31_50](https://user-images.githubusercontent.com/36751922/136805885-7dd96837-8ab9-4f17-8e7c-8ef3b00b6a9f.png)

We have Strapi connected to Heroku using a PostgreSQL database 

### Expected behavior

I would have thought that selecting the different main category would have indicated to Strapi that it is creating a new subcategory for a different main category and shouldn't create an conflicts.

**Comment by derrickmehaffy** [comment]
Enhancement that somewhat relates https://github.com/strapi/strapi/issues/8708

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8708
