### ISSUE TITLE
"Something went wrong.": Impossible to delete medias from media library

### ISSUE THREAD

**Issue by benitodotcool** [strapi/strapi#11243]
### Describe the bug

Hello, I'm relatively new to Strapi and I have a problem since this morning which I really don't understand.
I'm currently working on a really simple project with a basic collection type with different type entries and a media field which accept multiple medias. 

I managed to install everything correctly, I followed the official documentation to connect my application to my S3 bucket (which works fine), and I also put in production on heroku also following the official documentation.

When I decided to start adding content to my application everything was working fine, I had however decided to add my images in a second time (since I had put an obligation on the media field, I uploaded a generic image on all my entries).

It seems (I'm not exactly sure) that since then, my media library started not working properly.
The only thing that still works with my media library is uploading, I can upload both locally and on S3 without any problem (I see my bucket filling up in real time).
However, when I decide to delete, add a caption or edit any of my images I get error messages that seem to indicate that they do not exist. I specify that I have these errors both locally and on production.

### Steps to reproduce the behavior

I've done my best to explain in the section above.

### Expected behavior

I think the expected behavior is that my media library should work properly.

### Code snippets

(These manipulations are performed on an image that has just been uploaded.)

When I tried to delete an image (from UI Admin):
> Something went wrong.
Détails
Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')
    at http://localhost:1337/admin/main.4f6113b0.chunk.js:1:9290370
    at Array.find (<anonymous>)
    at http://localhost:1337/admin/main.4f6113b0.chunk.js:1:9290340
    at Array.some (<anonymous>)
    at d (http://localhost:1337/admin/main.4f6113b0.chunk.js:1:9290313)
    at Ka (http://localhost:1337/admin/main.4f6113b0.chunk.js:1:4237642)
    at Ri (http://localhost:1337/admin/main.4f6113b0.chunk.js:1:4246546)
    at gl (http://localhost:1337/admin/main.4f6113b0.chunk.js:1:4285284)
    at cs (http://localhost:1337/admin/main.4f6113b0.chunk.js:1:4276581)
    at ls (http://localhost:1337/admin/main.4f6113b0.chunk.js:1:4276506)
<img width="911" alt="Capture d’écran 2021-10-12 à 01 10 53" src="https://user-images.githubusercontent.com/82047125/136866118-46348019-7c23-4260-9ccb-7dad9c0385c1.png">

When I tried to delete an image (from console):
`[2021-10-11T22:59:49.011Z] debug DELETE /upload/files/undefined (20 ms) 404`

When I refresh my media library page:
![Capture d’écran 2021-10-12 à 01 12 29](https://user-images.githubusercontent.com/82047125/136866062-a830a9d4-fa30-4ed1-a287-ab45a2d90302.png)

### System

- Node.js version: >=10.16.0 <=14.x.x
- NPM version: ^6.0.0
- Strapi version: 3.6.8
- Database: DEV=PostgreSQL | PROD=SQLite
- Operating system: macOS Big Sur (version 11.2.3)

### Additional context

Again, everything was working fine, but at some point I started getting these errors.
I've spent the afternoon searching the internet without finding a solution to my problem. I copied and pasted the error messages, searched this GitHub for issues that could be similar still without finding any solutions.

Is there a way to "reset" the settings/content of the media library? I end up with a lot of images that I deleted from my S3 interface (screen below)
<img width="1200" alt="Capture d’écran 2021-10-12 à 01 08 58" src="https://user-images.githubusercontent.com/82047125/136865949-06127123-2d45-46af-84d7-cd5011182db6.png">

Thank you in advance for your help 🙏🏻
benitodotcool

**Comment by alexauvray** [comment]
Same error happens when trying to set an image on an entry from the media library :

```
Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')
    at http://localhost:1337/admin/main.6f6a6a53.chunk.js:309237:2743
    at Array.find (<anonymous>)
    at http://localhost:1337/admin/main.6f6a6a53.chunk.js:309237:2708
    at e.i.produce (http://localhost:1337/admin/main.6f6a6a53.chunk.js:195008:13639)
    at reducer (http://localhost:1337/admin/main.6f6a6a53.chunk.js:309237:22)
    at Object.wh [as useReducer] (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143658:249)
    at push.exports.useReducer (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143494:173)
    at InputModalStepperProvider (http://localhost:1337/admin/main.6f6a6a53.chunk.js:309214:3929)
    at oh (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143654:146)
    at di (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143676:309)
```

**Comment by benitodotcool** [comment]
> Same error happens when trying to set an image on an entry from the media library :
> 
> ```
> Cannot read properties of undefined (reading 'toString')
> TypeError: Cannot read properties of undefined (reading 'toString')
>     at http://localhost:1337/admin/main.6f6a6a53.chunk.js:309237:2743
>     at Array.find (<anonymous>)
>     at http://localhost:1337/admin/main.6f6a6a53.chunk.js:309237:2708
>     at e.i.produce (http://localhost:1337/admin/main.6f6a6a53.chunk.js:195008:13639)
>     at reducer (http://localhost:1337/admin/main.6f6a6a53.chunk.js:309237:22)
>     at Object.wh [as useReducer] (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143658:249)
>     at push.exports.useReducer (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143494:173)
>     at InputModalStepperProvider (http://localhost:1337/admin/main.6f6a6a53.chunk.js:309214:3929)
>     at oh (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143654:146)
>     at di (http://localhost:1337/admin/main.6f6a6a53.chunk.js:143676:309)
> ```

Yes I noticed that too, if you manage to solve the problem please keep me informed :)
Best,
benitodotcool
