### ISSUE TITLE
Mongodb unique index is being dropped magically

### ISSUE THREAD

**Issue by cipiasentini** [strapi/strapi#11246]
### Describe the bug

My model has a fileld which is specified as unique field. And thus an unique index constraint is created on mongo schema. But from times to times this index is dropped. I'm running strapi using development mode only. And neither turning it off/on or updating the code (live rebuild of app) makes the index dissapear. What makes it go away is letting all run a couple of days and even without changing anything to the code (nor restaring the app)

### Steps to reproduce the behavior

1. Create a content type which has a field with unique restriction
2. Just wait

### Expected behavior

The index shouldn't go away.

### System

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.3.0
- Database: mongodb
- Operating system: Ubuntu 20.04 LTS

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
