### ISSUE TITLE
String Field maxLength Not Passed To Knex

### ISSUE THREAD

**Issue by poita66** [strapi/strapi#11253]
### Describe the bug

Creating a string field always results in a 255 char size column being created, even if the field's maxLength is specified.
This is because the `maxLength` attribute isn't being passed to the Knex `table.string()` function during migration.
I have the change ready to address it, and will be making a PR shortly.

### Steps to reproduce the behavior

1. Create string field with length 300
2. Check DB schema and see column of length 255 has been created

### Expected behavior

The size of the created column should match the specified field size

### System

- Strapi version: 3.6.5
- Database: Postgres
- Operating system: strapi/base Container Image

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
