### ISSUE TITLE
Allow selecting Single Types in Relation Field

### ISSUE THREAD

**Issue by FlxAlbroscheit** [strapi/strapi#11279]
## Feature request 

* [x] **I have created my request on the Product Board before I submitted this issue**
* [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

The "Relation Field" currently allows referencing entities like Users, Role, Permissions or Collection Types. However, it does not allow referencing Single Types, for reasons that are unknown to me :( I suggest adding Single Types as a relation in the Relation Field select-box, as they basically work like Collection Types under the hood. This feature would make the way Strapi works more consistent, decrease redundancies (see below) and enable further use-cases.

### Why is it needed?

For instance, assume I want to build a menu (e.g. as a Collection Type called "Menus"). Each menu has an array of links, each link has the fields/attributes "Label" and "URI/Slug". The very same fields, or similar fields, are also available on all of my Single Types as part of a common component "SEO". I now want to link my menu-link with a given Single Type, so that the Label & Slug can then be resolved from that Single Type (e.g. PortfolioPage.slugUidField). As a result, when the label or slug changes on PortfolioPage, it would also instantly change on my menu-link as the menu-link only contains a reference to the Single Type, no actual content. As it seems, this scenario is not possible currently. Instead, I would have to hard-code the Label and Slug in a simple input-field on my menu-link and hope that this data will not change on the Single Type that I implicitly link to.

### Suggested solution(s)

Add the option "Single Type" to the select-box of a Relation Field X, whereby X can have one or multiple Single Types. On API/GraphQL requests, the referenced Single Type can become fully resolved in order to use its fields.

**Comment by benitodotcool** [comment]
Great idea!

**Comment by dino-zhao** [comment]
需要

**Comment by MarcosGin** [comment]
same here!

**Comment by derrickmehaffy** [comment]
Not currently something we will work on, this would better be handled via dedicated menu builder plugins: https://market.strapi.io/plugins/strapi-plugin-menus

**Comment by sanneh2** [comment]
Bump. I don't understand why this wasn't implemented in version 1.0.0 already.
