### ISSUE TITLE
Strapi Admin Panel taking too much time to load. 

### ISSUE THREAD

**Issue by hammad786** [strapi/strapi#1127]
**Informations**
- **Node.js version**: latest
- **npm version**: latest
- **Strapi version**: Alpha
- **Database**: Mongo
- **Operating system**: Ubuntu

**What is the current behavior?**

I've done a fresh installation and it worked. Admin Panel taking too much time to load/render the body. 

Console Error: It looks like the language "zh-Hans" is not supported by "react-intl" module.

**Steps to reproduce the problem**

At Page load/reload

**What is the expected behavior?**

Should respond fast

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@hammad786 I really wouldn't recommend openly putting that on here, and not much can be done from only the admin panel.

Also with the current bug of strapi showing password hashes this is a huge security issue for you.
I would remove that comment ASAP.

side note, I have no issues rendering the admin panel on chrome.

**Comment by hammad786** [comment]
Thanks for the response :) 

No worries about credentials since it is a testing droplet. 

I just checked the settings tab where I had to enable GZip compression and it started to respond fast as expected. GZip compression is disabled by default due to development mode.

**Comment by negati-ve** [comment]
Is Gzip compression disabled by default on production  mode too? 

I'm having the same issue running on production mode on latest stable release 
The admin login screen takes literally a minute or more to load. (I'm on decent internet connection with atleast 10Mbps downlink and the servers are also pretty fast)

**Comment by anmol5varma** [comment]
@hammad786 Can you help me in enabling the gzip compression?
currently, i have a middleware.js file which looks like

```
module.exports = {
  load: {
    before: ['responseTime', 'boom', 'logger', 'cors', 'responses', 'gzip'],
    after: ['parser', 'router'],
  },
  settings: {
    gzip: {
      enabled: true,
      options: {
        br: false
      }
    }
  }
};

```
