### ISSUE TITLE
ctx.session inside policies is always an empty object?

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#1128]
**Informations**
- **Node.js version**:

9.11.1

- **npm version**:

5.6.0

- **Strapi version**:

3.0.0-alpha.12.1.2

- **Database**:

MongoDB

- **Operating system**:

Windows 10

**What is the current behavior?**

`ctx.session` inside of policies is currently an empty `{}` object

**What is the expected behavior?**

https://strapi.io/documentation/guides/policies.html indicates that we should be able to access the session inside policies.

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @nurikabe what is your use case ?
Did you allow `sessions` in your request config ?
Maybe you also want tu use `ctx.state` as here https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js#L12

**Comment by nurikabe** [comment]
Ah, perhaps I'm not allowing sessions.  Is there a special config for this that I'm missing?

I basically just want to check `if (ctx.session.isAuthenticated === true)` inside a policy applied to a specific route.

**Comment by lauriejim** [comment]
As you ca see in my previous link, we store the user data in `ctx.state.user`. So you can use `if (ctx.state.user)` to check if your user is authenticated.

**Comment by nurikabe** [comment]
Okay, thanks.  Would you like me to update the policies documentation?

**Comment by lauriejim** [comment]
Ho yes please. Update for `How to create a policy?` and for `Scoped Policies`.
Thank you.

**Comment by lauriejim** [comment]
@nurikabe Did you send the Authorization header ?

**Comment by nurikabe** [comment]
@lauriejim No, though I'm hoping to allow authentication from a browser without the need for a token.  In other words:  If the user has logged in to admin, I want them to be able to access any Strapi route that has my custom global policy.

How does admin authorization work?  From the code it seems to be checking against `'utils/auth'`

https://github.com/strapi/sample-strapi-app/blob/master/admin/admin/src/containers/HomePage/index.js#L26

but... I can't seem to figure out where `'utils/auth'` lives?

Should I expect to find it in here?:

https://github.com/strapi/sample-strapi-app/tree/master/admin/admin/src/utils

Sorry for the dumb questions.  I'm new to React.  Once I suss out how the admin module auth works I can leave you alone. :grin:
