### ISSUE TITLE
Dynamically fill a relation field inside a component

### ISSUE THREAD

**Issue by VictorienTardif** [strapi/strapi#11281]
### Please describe your feature request

**What I have:** 

- A collection type "Articles"
- A collection type "Category of article"
- A single type "a page"
- A single type "another page"
- A component "Articles section"

**What I'd like to be able to do:**

I'd like to populate my "Articles section" component with the last 3 articles of a selected category. I'd like to be able to put the component on the first page and just select a category of articles, put it also on the second page with a different category of articles, but do not pick the articles myself.

Is there a way to do that? I haven't found a way to customize what a component or field returns, like you could with a collection.

### Summary

Dynamically/automatically fill relation fields values.

### Why is it needed?

To avoid multiple api calls on frontend to fill the sections and therefore for the authors to not be dependent on the developers.

### Suggested solution(s)

- Add a controller for components?
- On option on the relation field?

### Related issue(s)/PR(s)

_

**Comment by derrickmehaffy** [comment]
Not currently something we will work on but we are planning to allow placing relations in the main view so this should be a bit better UI/UX than components
