### ISSUE TITLE
Browser New Window Title has always "Strai - ", Where Can I remove text ?   

### ISSUE THREAD

**Issue by Aurelyn10** [strapi/strapi#1129]
**What is the expected behavior?**

I want to remove the text "strapi" on browser new tab, when open new routing. where is the setting?

---

- [ ] I'm sure that this issue hasn't already been referenced.

**Comment by Aurelyn10** [comment]
I found.
admin/admin/src/containers/Homepage
return (
      <div>
        <Helmet
          title={`Strapi- ${pluginName}`}
        />
        {containers}
      </div>

Change here.

**Comment by frostini** [comment]
I tried that and it didn't work @samuelboadas. It is being pulled from the index.html  on initial load and then the title is dynamically being re-injected by Helmet. 

You can "eject" the src/components/PageTitle; however, that will only fix the Helmet part and it still always show the 'Stapi Admin' title on initial load.

Another thing I tried is ejecting the index.html but that didn't seem to work.

Can we re-open this issue until somebody can suggest a fix please? We'd like to be able to remove the "Strapi Admin" title on initial page load please.

**Comment by PCostelus** [comment]
I have same problem. Any suggestion?

**Comment by soupette** [comment]
Hello! you might want to take a look at this [component](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/components/PageTitle/index.js)
