### ISSUE TITLE
[v4] Enterprise license error

### ISSUE THREAD

**Issue by macklinhrw** [strapi/strapi#11290]
### Describe the bug

I get an error when launching Strapi with an enterprise license on a fresh install.

### Steps to reproduce the behavior

1. Do a fresh install of Strapi beta using `npx create-strapi-app@beta backend --quickstart`
2. Stop Strapi once it auto runs, then add an enterprise license to license.txt. (Or set STRAPI_LICENSE in env, I tested both.)
3. Run `yarn build --clean` and wait for the admin panel to build.
4. Run `yarn develop` and you should get the error.

### Expected behavior

Strapi should run normally after running `yarn develop` and I should be able to add custom roles.

### Screenshots

![image](https://user-images.githubusercontent.com/19892721/137795322-0dc96123-4b05-42b2-86ab-60b1d7abbf1a.png)

### Code snippets

N/A

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15 (also tested in 8.1.0)
- Strapi version: v4.0.0-beta.3
- Database: sqlite
- Operating system: Ubuntu v20.04, Windows 10

### Additional context

The error can be gotten rid of by removing the license key, but Strapi will launch in community edition.

**Comment by derrickmehaffy** [comment]
Tested using a Bronze license instead of Gold and was able to reproduce issue.

**Comment by sh13n** [comment]
Please, submit your license key here so we can reproduce the issue.

**Comment by sh13n** [comment]
Please, submit your license key here so I can reproduce the issue.
