### ISSUE TITLE
feat(users-permissions): Add crossid provider

### ISSUE THREAD

**Issue by asaf** [strapi/strapi#11305]
### Summary

Add [crossid.io](https://crossid.io) as an Auth Provider.

### Suggested solution(s)

A PR is required that adds the provider and upgrade [simon/grant](https://github.com/simov/grant) to 5.4.18

**Comment by derrickmehaffy** [comment]
Since the WIP PR was closed, will also close this feature request as we won't work on it ourselves (anyone can submit a new PR)
