### ISSUE TITLE
Swagger plugin issue on GCP - Documentation

### ISSUE THREAD

**Issue by juancho11gm** [strapi/strapi#11308]
### Describe the bug

When accessing the `/documentation` page from the Strapi admin panel on a GCP App Engine (Standard) instance, I am seeing the below errors in GCP logs and Page not found with a 404 error.

`error Error: EROFS: read-only file system, open '/workspace/extensions/documentation/public/index.html'`

The documentation plugin was installed in my LOCAL development environment and docs compiled before deploying to GCP App Engine. Locally it works fine.

### Steps to reproduce the behavior

1. launch your Strapi project
2. active the Swagger documentation plugin
3. request the documentation locally (it will work)
4. upload the Strapi project to Google App Engine (gcloud command or whatever)
5. visit the documentation ( https://YourGoogleProject.appspot.com/documentation/v1.0.0 )

### System

- Node.js version: v14.17.6
- NPM version: 8.1.2
- Strapi version: v3.6.8
- Database: MongoDB

### Additional context

Other users are facing the same problem: https://issueexplorer.com/issue/strapi/documentation/377

**Comment by iiibnuadam** [comment]
i still have this issue, anyone can help to fix this? what should i do?

**Comment by PaulRichez** [comment]
@iiibnuadam https://github.com/strapi/strapi/issues/16035#issuecomment-2189867393
