### ISSUE TITLE
Admin resets field value in database without update permissions

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#11304]
## Bug report

When a content-type, with a non-localized field, is saved by an editor, who only has read access on the field, the value is reset. The issue is quite hard to illustrate, so I did my best to describe it in the steps. I haven't figured out yet, if it would work with the "create" permissions being set.

I can provide an example repository, however this might not make anything easier for you, since the permissions + users are stored in the DB.

### Steps to reproduce the behavior

1. Enable a license
2. Add at least one more locale
3. Create a new content type. Enable localization. Add 1 localized and 1 non-localized field.
4. Remove "create" and "update" permissions for an editor from the non-localized field.

![Screenshot from 2021-10-20 11-19-17](https://user-images.githubusercontent.com/2244375/138065727-f45d1895-b713-4147-8c99-003701181d0a.png)

3. Login is the editor
4. Translate the previously created item into another language and save the new item.
5. One both items (the default language + the translated one) the non-localized field is empty.

As an admin you can now set the value again, but as soon as an editor saves the translated version of the item, the value is gone again.

### Expected behavior

The non-localized field keeps its value.

### System

- Node.js version: 14.17.
- NPM version: 
- Strapi version: 3.6.8
- Database: sqlite (but happens on mysql in production too)
- Operating system: Ubuntu

**Comment by gu-stav** [comment]
@derrickmehaffy Any success yet?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Any success yet?

Haven't had time to test but it's on my list for this week

**Comment by gu-stav** [comment]
https://user-images.githubusercontent.com/2244375/143220943-7847ccc3-1529-43f9-9f0a-b9a3a41bd060.mp4

@derrickmehaffy I know you are busy with v4 but nevertheless this issue currently becomes quite an issue in our setup. In order to make it clearer I've created a screencast, where you can see the problem. I hope that helps ...

**Comment by gu-stav** [comment]
@derrickmehaffy I know you are busy with v4 but nevertheless this issue currently becomes quite an issue in our setup. In order to make it clearer I've created a screencast, where you can see the problem. I hope that helps ...

https://user-images.githubusercontent.com/2244375/143221889-111697e2-1ca6-4673-9120-db37a4befc66.mp4

**Comment by danielbeardsley** [comment]
We (at ifixit.com) just ran into this and lost a bunch of data when a translator with limited permissions correctly edited localizable fields. The non-localized fields were erased when they submitted their translations. They didn't notice because having less permissions means not being able to *see* those fields. Thus they carried on with their work, clearing many fields across many records.

This feels like a pretty big bug: Translating some fields leads to deleting the content in fields the translator *explicitly* doesn't have permission to modify.
