### ISSUE TITLE
Gatsby Strapi Tutorial: Error when creating content with relationship

### ISSUE THREAD

**Issue by bzhr** [strapi/strapi#1130]
**Informations**
- **Node.js v9.11.1**:
- **npm v5.6.0**:
- **Strapi 3.0.0-alpha.12.1.2**:
- **MongoDB 3.6.4**:
- **Operating system**:

**What is the current behavior?**
I am following the [tutorial](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/) for using Strapi with Gatsby and after creating the first content type - article - I can't add an article with an author relation.  I always get this error:
```
[2018-05-06T10:55:11.231Z] error Cast to ObjectId failed for value "[ { _id: '5aeedea8ec354f181944cd73',
    username: 'bozho',
    password: 'password',
    email: 'my_email@gmail.com',
    provider: 'local',
    role: '5aeede8dec354f181944cca1',
    __v: 0,
    articles: null,
    id: '5aeedea8ec354f181944cd73' } ]" at path "author"
```
Tried also with different versions of node, mongo etc. 
I noticed that I can add an author by going to Users, and for a selected user to add article and save. But, then when I go to the article (with the relation) page the front end brakes and there are [multiple errors in the console](https://ibb.co/hd7i67)

However, it seems that when I do a graphql query for an article with an author like this:
```
export const query = graphql`  
  query ArticleTemplate($id: String!) {
    strapiArticle(id: {eq: $id}) {
      title
      content
      author {
        id
        username
      }
    }
  }
`
```
I get the expected results, which that the relationship is created by going to a User page and associating an article with the User. 

**Steps to reproduce the problem**
Follow the Gatsby-Strapi tutorial. 

**What is the expected behavior?**
The expected error is to be able to add content type with relational field.

**Suggested solutions**
I don't have a solution, I careful wen through all the steps many times and the error always happens. 

---

I browsed all open and closed issues and I didn't find this exact error referenced or solved. 

- [x ] I'm sure that this feature hasn't already been referenced.

**Comment by liming** [comment]
I have the same error. The error is something like this:

```
Cast to ObjectId failed for value "[ { _id: '5aefa39d590dfb178f3bd5dc',
    username: 'match',
    password: '$2a$10$hOY4GSzeUBu9TwfhmVVe.O6pdEFCxS8VnMgDOBss/ZCkTdSwSwxHq',
    email: 'liming.dl@gmail.com',
    provider: 'local',
    role: '5aefa34e590dfb178f3bd50a',
    __v: 0,
    articles: null,
    id: '5aefa39d590dfb178f3bd5dc' } ]" at path "author"
```

**Comment by liming** [comment]
I figured this out. It's because the author field in article is a multiple selection instead of single selection. To make it as single selection, we need add a dominant flag in the Article.settings.json: 

```json
 "author": {
      "model": "user",
      "via": "articles",
      "dominant": true,
      "plugin": "users-permissions"
    }
```

Then edit article field doing nothing but it can display "save" button. Save the configuration to restart & reindex the api. Edit an article. It would display author in article as single selection.

**Comment by bzhr** [comment]
@liming - Thanks for finding the solution, I will try it out right away. It seems that this needs to be created automatically. Is there more info in the docs on configurations of models?

**Comment by liming** [comment]
@bzhr , I believe it's a bug. What I proposed is just a workaround.

**Comment by bzhr** [comment]
@liming yes, I agree, the solution to the issue is to integrate this in the program so that workaround isn't needed.

**Comment by lauriejim** [comment]
@bzhr Can you update your global Strapi version `npm i strapi@alpha -g` and try again with a new project. We just patch it. Need to know if it works on your side.

**Comment by bzhr** [comment]
@lauriejim do I need to only update the strapi version, anything else to change in the project?

**Comment by lauriejim** [comment]
1.Install new version of strapi
2. Create new app
3. Replace your plugin/content-manager/admin with the new one

Or just try with a new project

**Comment by bzhr** [comment]
How do I do number 3:
> 3. Replace your plugin/content-manager/admin with the new one

**Comment by bzhr** [comment]
Yes, it does work!

**Comment by lauriejim** [comment]
Perfect thank you !

**Comment by liming** [comment]
Hi @lauriejim ,

I just curious about the design of plugins. The plugins are the features of strapi, and these features need to be updated constantly. On the other hand, the user changes are also saved into plugins. For example User.settings.json in users-permission/models. I can see the plugins need to be changed by both strapi and users. That's a design flaw, which will result in:

* It makes strapi project difficult to be upgraded.
* The user changes are difficult to preserve. 

Do you have any future plan to change this design?

**Comment by lauriejim** [comment]
Yes we know it's difficult, there is an issue about this point https://github.com/strapi/strapi/issues/1018. We have an hard work to do on it.

**Comment by erikvullings** [comment]
@lauriejim Is this issue really solved? In v3.0.0-alpha.12.2, when I created a new content type, collection, and add a relation (a collection belongs to many articles - as a side note, I would prefer to read 'a collection has many articles'), I receive the following error:
```console
[2018-05-17T21:18:35.242Z] error Something went wrong in the model `Collection` with the attribute `articles`
[2018-05-17T21:18:35.251Z] error The attribute `collection` is missing in the model Article
```
When checking the collection.settings.json, it looks ok:
```json
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "collection",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "articles": {
      "collection": "article",
      "via": "collection",
      "dominant": true
    }
  }
}
```
but the article content model is missing the collection property, as suggested by the error message. But why doesn't it create it?
```json
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "article",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "content": {
      "type": "text"
    },
    "title": {
      "type": "string"
    },
    "author": {
      "model": "user",
      "via": "articles",
      "plugin": "users-permissions"
    }
  }
}
```

**Comment by kamalbennani** [comment]
^ I think that's related to the name of your model "collection" which might be conflicting with the strapi's logic. Try to rename you model name and retry again

**Comment by erikvullings** [comment]
**@kamalbennani** Indeed, you are right. It is related to the name 'collection'. Are you aware of any other names we should avoid (and could we mention them in the documentation somewhere)!
