### ISSUE TITLE
Auto upgrade to latest version

### ISSUE THREAD

**Issue by underbayan** [strapi/strapi#1131]
Strapi is excellent and very impressive. But when I want to upgrade it,The process is struggling. If there be possible a cli command like `strapi update` to make all plugins and packages upgrade.

**Comment by derrickmehaffy** [comment]
@underbayan please search before creating new issues, this is exactly like https://github.com/strapi/strapi/issues/1018

If you will note in the issue template (which was deleted here) there is a checkbox stating you are sure this hasn't been referenced before.

Not trying to be rude or mean, just trying to help out the strapi team by cutting down on duplicate issues.

**Comment by lauriejim** [comment]
Thank you @derrickmehaffy for your message.
