### ISSUE TITLE
[v4] Returning false on policies return 500 error

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11313]
### Describe the bug

When returning a policy as `false` REST/GraphQL throw a 500 Internal Server error instead of a 401/403/400 (or any other user defined error).

I'm not aware of how to return a sane user error at the policy level

### Steps to reproduce the behavior

1. Create a policy on a content type
2. Call endpoint
3. See error

### Expected behavior

By default we should return a default error code + message (400?) and/or allow users to return a custom statusCode + Message

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/138171277-8fa57a74-8c9d-4088-a1c3-e5a1b9eeddbc.png)

### Code snippets

```js
    {
      method: "GET",
      path: "/blogposts",
      handler: "blogpost.find",
      config: {
        auth: false,
        policies: [
          (ctx, { strapi }) => {
            return false;
          },
        ],
        middlewares: [],
      },
    },
```

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: v4.0.0-beta.4
- Database: SQLite
- Operating system: Linux Mint 20.2

### Additional context

I believe this will be eventually handled by the error handling, but was just playing and saw it now

**Comment by derrickmehaffy** [comment]
Fixed in beta.11 (could have been before that but it works now)

![image](https://user-images.githubusercontent.com/8593673/140852258-cd841bc1-b0a4-436a-aaff-23d40b6e449c.png)

**Comment by chall3ng3r** [comment]
Hi, any way to customize the error instead of the default:
```
{
    "data": null,
    "error": {
        "status": 403,
        "name": "ForbiddenError",
        "message": "Policies failed.",
        "details": {}
    }
}
```
For my current case, I want to return 401, and details containing child objects. How I can do that?

I am upgrading my app from v3, where I simply set the ctx's status and body with custom JSON object with details. I like the new standard error object and would like to customize details about the error.

**Comment by petersg83** [comment]
Hi :) You can follow the example there https://github.com/strapi/strapi/blob/master/examples/getstarted/config/middlewares.js with the `responseHandlers`

**Comment by chall3ng3r** [comment]
@petersg83 thank you for the pointer, I looked it up and docs for implementing custom middleware. Is there a simpler way to return an error with custom details? Like I can do in controller, `ctx.unauthorized()` or `ctx.badRequest()`.

If I have to implement middleware, how I can pass the error details from policy to middleware? 

Alternatively I'm thinking of removing the policy, and handle authorization in controller and return custom error or successful response.

**Comment by saintego** [comment]
any update on custom error messages from policy?

**Comment by derrickmehaffy** [comment]
Just realized I forgot to document it.

@saintego https://github.com/strapi/strapi/pull/12080
