### ISSUE TITLE
NoSQL Embedded Database Support For Quick Start & Testing (Easy To Migrate WithOut Install MongoDB).

### ISSUE THREAD

**Issue by criticalsoft** [strapi/strapi#11328]
There Is SQLite, But I Want NoSQL Database.

**Comment by criticalsoft** [comment]
OK, Bye StrAPI !

**Comment by criticalsoft** [comment]
Ridiculous.

**Comment by derrickmehaffy** [comment]
> #10186 What A Stupid Decision Made By User Base. You Should Drop SQL & SQLite.
> If You Drop Support Of NoSQL Database There Will Be No Reason To Use StrAPI Anymore.
> And Thank You For Told Me This. OK, Bye StrAPI !

Hope you have a wonderful day, sorry to see you leave.
