### ISSUE TITLE
"(hook:mongoose) takes too long to load” on hosting server.

### ISSUE THREAD

**Issue by Aurelyn10** [strapi/strapi#1133]
**Informations**
- **Node.js version  9.10.1**:
- **npm version  5.6.0**:
- **Strapi version 3.0.0-alpha.12.1.2**:
- **Database mLab (mongo client 3.4)**:
- **Operating system , Hosting server : Linux version 2.6.32-896.16.1.lve1.4.53.el6.x86_64 (Red Hat 4.4.7-18)**:

**What is the current behavior?**
I linked mLab to my strapi sample project,
 I can run it on Linux hosting server without installing mongo client?
 I am sure I can run it without installing mongo on hosting server, but it always show this message : “(hook:mongoose) takes too long to load”.
in local host, sometimes I found this message only when bad internet connection.
But hosting server's connection will be great without doubt. It is A2 hosting, it works for other site.
Currently mLab is in Sandbox, and It works on localhost, so mLab credit is correct.

**Steps to reproduce the problem**
After clone the source to hosting server, installed node, but did not install mongo.
with ssh, in myproject folder, I run "npm start --production"
**What is the expected behavior?**

Work normally like as localhost.

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by piere129** [comment]
Take a look at #1105 , the error seems similar to the bookshelf error described there
