### ISSUE TITLE
use any token generated with the correct secret authenticates with the first admin user found if no id is set

### ISSUE THREAD

**Issue by VictorienTardif** [strapi/strapi#11332]
### Describe the bug

If you generate a token with the right secret but without any id, you just get a warning  
`warn The value of field: 'id', in your where filter, is undefined.`   
from ` const admin = await strapi.query('user', 'admin').findOne({ id: payload.id }, ['roles']);`   [(here)](https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi-admin/middlewares/auth/index.js#L20)
and you are authenticated as the admin user with id `1`.
 

### Steps to reproduce the behavior

1. Generate a token without setting any id using the right secret
2. Make a request with that token as authorization header
3. Voilà, you are authenticated as the admin user with id `1`. 

### Expected behavior

The absence of id should throw an error.

**Comment by alexandrebodin** [comment]
This has been fixed in v4. I'll close the issue :)
