### ISSUE TITLE
User throws _id error when calling update user api call in MySQL

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1135]
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: MySQL
- **Operating system**: Windows

**What is the current behavior?**

Updating a User with the api call '/user/:id' throws the following error in MySQL: 
`{"statusCode":400,"error":"Bad Request","message":"select `users-permissions_user`.* from `users-permissions_user` where `users-permissions_user`.`_id` = '2' limit 1 - ER_BAD_FIELD_ERROR: Unknown column 'users-permissions_user._id' in 'where clause'"}` . Updating User in the Admin UI does work however. I also noticed using the api call from frontend does not allow you to update the username alone: it throws an error that the Email is already taken, which makes sense because it doesn't need to be edited. 

**Steps to reproduce the problem**

1) Create a new User. This one has id = 2 in my example
2) do an API call from seperate frontend calling '/user/2'
3) error gets thrown

**What is the expected behavior?**

User should be updated

**Suggested solutions**

I'm posting an issue because I'm not sure how to do a pull request. I fixed the problem by navigating to ./plugins/services/User and editing the fetch method:

`return strapi.query('user', 'users-permissions').findOne(_.pick(params, [ 'id', '_id']));`
became
`return strapi.query('user', 'users-permissions').findOne(_.pick(params, [ 'id']));`

After this it worked as intended :) I know this is a fix on MySQL but I'm not sure about how this fix would work on Mongo databases, but it should at least point to the right direction for fixing this issue!

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@piere129 I think there is a pull request to prevent id duplication (the `id` and `_id`) so this may fix itself as the id duplication fixes happen.

**Comment by lauriejim** [comment]
Hello @piere129 your suggestion will break mongoose application. We have to know why you have _id with SQL database. It's strange.

**Comment by derrickmehaffy** [comment]
@lauriejim I'm not sure what you mean? SQL only has one ID column `id` so I think passing the `_id` in the query is what is causing the issue (not sure why mongo has a `_id` and an `id` column  ¯\_(ツ)_/¯ )

**Comment by lauriejim** [comment]
@piere129 if your proposition work for Mongoose and Bookshelf generated applications feel free to submit a PR.
 
Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by piere129** [comment]
I just got the same error as #1037 but with a mongoose database when calling GET /user/:id , looking into what could be the issue

**Comment by piere129** [comment]
@omar1989omb

**Comment by lauriejim** [comment]
@piere129 Did you try with a new fresh app from `alpha.12.2` version ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
