### ISSUE TITLE
Strapi keeps crashing due to pool connection on Postgres (AWS RDS) error

### ISSUE THREAD

**Issue by murilobd** [strapi/strapi#11354]
## Bug report
Strapi keeps crashing with the follow error messages:
```
error bootstrap function in plugin "content-manager" failed
error error: remaining connection slots are reserved for non-replication superuser connections
```

Strapi is running in an EC2 instance t3.micro on AWS and has the following pool configuration:
```
options: {
        useNullAsDefault: true,
        debug: true,
        pool: {
          min: 2,
          max: 50,
          idleTimeoutMillis: 60000,
          createTimeoutMillis: 60000,
          acquireTimeoutMillis: 60000,
        },
      }
```

The maximum allowed connections on database is 83, but I set it to 50 because only few people (~10) will use Strapi as the website is built using a static generator.

### Expected behavior
Strapi would work smoothly when only a few users are using it (when I say few, I'm saying ~10 people)!

### System

- Node.js version: 12
- NPM version: 
- Strapi version: 3.6.3
- Database: Postgres 11 (RDS AWS)
- Operating system: Linux

### Additional context

I'm considering this as a bug because Strapi keeps crashing even when there's only a single person using it. Would that be because of the pooling configuration? Something wrong with the integration between knexjs and strapi?

**Comment by derrickmehaffy** [comment]
> I was wondering, what if I play with the idleTimeoutMillis and acquireTimeoutMillis from pool configuration? Set idle to 0 (theoretically it would kill the connection as soon as it was done) and increase the acquireTimeoutMillis (until it raises an error, it would wait longer trying to get a connection)? Does it makes sense? Is it logical?

That makes sense to me, these settings come directly from Knex.js so I'm not quite sure how they are applied.
