### ISSUE TITLE
[v4] Content-Type Builder broken in beta.5

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11363]
### Describe the bug

New Beta release appears to break the content-type builder when creating/modifying a content Type:

### Steps to reproduce the behavior

1. Try to create a new content type
2. Add a title and a body field (string, richtext respectively)
3. Save and get a non-descriptive error
4. Look at network logs
5. See error (literally just error, no context)

### Expected behavior

At minimum, provide a useful error. Even better if the CTB works :wink: 

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/138939388-52e93a0b-6c0b-4b37-83c6-89598c0e218e.png)
![image](https://user-images.githubusercontent.com/8593673/138939417-4ae8c997-3566-4309-afcb-5c5863b81345.png)
![image](https://user-images.githubusercontent.com/8593673/138939443-0f354e1a-7769-4ae2-bb6f-0037ecfcdb3d.png)

### Code snippets

Request Paylod:

```json
{
  "components": [],
  "contentType": {
    "draftAndPublish": false,
    "pluginOptions": {},
    "singularName": "blog-post",
    "pluralName": "blog-posts",
    "displayName": "Blog Post",
    "kind": "collectionType",
    "attributes": {
      "title": { "type": "string", "required": true, "unique": true },
      "body": { "type": "richtext", "required": true }
    }
  }
}
```

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.5
- Database: SQLite
- Operating system: Linux Mint 20.2

### Additional context

N/A

**Comment by spathon** [comment]
I get similar error in both beta 10 and 12.
Now and then I get errors like this when just creating a component
```
message: "component field has unspecified keys: allowedTypes, type, multiple, name"
name: "ValidationError"
```
I can reload and do it all over and it works. Have spent some time try to replicate but it only happens now and then
