### ISSUE TITLE
[v4] Create unique validation isn't enforced from REST, CTM, or GQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11366]
### Describe the bug

When you have defined a field as unique (in this case `title`) and you send a POST request to the REST API (or any other interface), it doesn't enforce the unique and will simply allow you to keep creating the same title.

### Steps to reproduce the behavior

1. Create a model with a unique field
2. Either create an entry in the CTM or via REST
3. Attempt to create a duplicate of the same unique field
4. Don't see any validation error

### Expected behavior

If a field is marked as unique, you shouldn't be able to create duplicate values.

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/138968870-4eebdbfa-5cab-4a5b-ae86-6c593054009b.png)
![image](https://user-images.githubusercontent.com/8593673/138968912-09b0c660-d0d1-44bc-938e-31742c08104e.png)
![image](https://user-images.githubusercontent.com/8593673/138968937-be61d9ed-3d4c-488e-8d6f-28bf0522c0aa.png)
![image](https://user-images.githubusercontent.com/8593673/138968965-ca4cdc6d-4408-4918-9ca3-66d391f90da8.png)
![image](https://user-images.githubusercontent.com/8593673/138969004-16cb4d0f-83ad-4f8f-bf0c-0cf5b1cd10f3.png)

### Code snippets

Model Structure

```json
{
  "kind": "collectionType",
  "collectionName": "blogpost",
  "info": {
    "singularName": "blogpost",
    "pluralName": "blogposts",
    "displayName": "blogpost",
    "name": "blogpost",
    "description": ""
  },
  "options": {
    "draftAndPublish": true,
    "comment": ""
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "unique": true,
      "default": "test",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "body": {
      "type": "richtext",
      "required": true,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    }
  }
}
```

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.5
- Database: SQLite
- Operating system: Linux Mint 20.2 

### Additional context

Apparently the unique index isn't being created in the database

**Comment by derrickmehaffy** [comment]
Confirmed on beta.11 regardless if draft & publish or i18n is enabled

**Comment by JabStrapi** [comment]
Should be fixed in the next version.

**Comment by derrickmehaffy** [comment]
Fixed in beta.22
