### ISSUE TITLE
[v4] DB configuration no longer seems to respect 'schema' option for Postgres

### ISSUE THREAD

**Issue by dangerdespain** [strapi/strapi#11367]
### Describe the bug

"schema" no longer seems to be a valid database option for Postgres in `config/database.js`. Even when `schema` is defined, the new tables are created in `public`. 🤞🏼 My application had planned on using this... If this option is still supported, am I configuring this correctly? I have also tried `search_path: ['strapi']` and `searchPath: ['strapi']` in an effort to configure knex.

### Steps to reproduce the behavior

From a fresh project from `npx create-strapi-app@beta`, update `config/database.js` to a configuration that includes a schema option:

```javascript
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', 'localhost'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'postgres'),
      user: env('DATABASE_USERNAME', 'postgres'),
      password: env('DATABASE_PASSWORD', ''),
      schema: env('DATABASE_SCHEMA', 'strapi'),
      ssl: env.bool('DATABASE_SSL', false),
    },
  },
});



``` 

### Expected behavior

Tables that are automatically created by Strapi should be created in the defined Postgres schema (default "public", configured as "strapi" in the reproduction)

### System

- Node.js version: 12.20.0
- NPM version: 6.14.8
- Strapi version: v4.0.0-beta.6
- Database: Postgres 13.1
- Operating system: MacOS Big Sur

**Comment by derrickmehaffy** [comment]
Confirmed on beta.7

**Comment by derrickmehaffy** [comment]
confirmed on beta.11, I attempted a few different fixes but it's above what I understand about the new database logic @alexandrebodin sorry :/

**Comment by alexandrebodin** [comment]
This is now supported in beta.13
