### ISSUE TITLE
[V4] Minimum rule for field number is broken

### ISSUE THREAD

**Issue by Stun3R** [strapi/strapi#11383]
### Describe the bug

It seems than an old bug just came back with `beta.6`.
When you try to apply `0` in `minimum value` rule on `number` field it throws an error thinking it's a NaN instead of type `number`

### Steps to reproduce the behavior

1. Go to `Content Type builder`
2. Click on the content type where you want to apply the `minimum value` rule
3. Select the field, go to advanced settings and set the `minimum value` rule to 0

### Expected behavior

Accept `0` as a minimum value

### Screenshots

![image](https://user-images.githubusercontent.com/34125897/139113837-c2dd27e4-e52f-4c35-85f9-792f6b33095a.png)

### System

- Node.js version: v14.18.1
- Strapi version: 4.0.0-beta.6
- Operating system: MacOS Big Sur

**Comment by derrickmehaffy** [comment]
Confirmed on beta.11, plus some other weird UI logic going on with 0:

https://www.loom.com/share/494bb08528f845929f81515881fcf0a9

**Comment by derrickmehaffy** [comment]
Closing as fixed in above PR
