### ISSUE TITLE
[v3.x] Enable node v16 engines compatibility

### ISSUE THREAD

**Issue by EricKwan2014** [strapi/strapi#11386]
### Summary

[v3.x] Enable node v16 engines compatibility

### Why is it needed?

https://nodejs.org/en/about/releases

node v16 is now Active LTS

### Suggested solution(s)

revise the engines compatibility @ package.json
```
"engines": {
  "node": ">=10.16.0 <=16.x.x",
  "npm": ">=6.0.0 <=8.x.x"
},
```

**Comment by derrickmehaffy** [comment]
We won't be back porting Node v16 support to v3 as it would require far too many changes to function properly.

Thank you for the request though.

**Comment by Igloczek** [comment]
@derrickmehaffy please update the docs, that you are supporting only 12.x and 14.x branches.

https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/cli.html#preparing-the-installation

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy please update the docs, it should say straight, that you are supporting only 12.x and 14.x.
> 
> https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/cli.html#preparing-the-installation
> 
> BTW. The range from `package.json` does not match the minimum version from docs.

Yes the package.json I believe also includes node 10 but it won't matter here in a few weeks once v4 goes live as it drops support for node 10 anyway.

**Comment by Igloczek** [comment]
I believe the 3.x will be still around for some time, and the 3.x docs will be available separately, or at least this is what I'd expect to happen.

**Comment by derrickmehaffy** [comment]
> I believe the 3.x will be still around for some time, and the 3.x docs will be available separately, or at least this is what I'd expect to happen.

Yes for 6 months after v4 release as a time for people to migrate, and yes the docs will be on https://docs-v3.strapi.io (it's not live yet). But we won't be backporting any features or node 16 support to v3. And those 6 months will only be updating v3 for high/critical security issues.

**Comment by aksdevac** [comment]
Hi @Igloczek we have released custom version under `@akemona-org/` with latest LTS Node (18.x) & Mongoose 6.x support here, its made for internal use but should work for everyone.

You can check it here: https://github.com/Akemona/strapi

Hi @derrickmehaffy, we have removed  EE edition dir & related code from this as it was not under MIT license.
