### ISSUE TITLE
Current SSO implementation too restrictive

### ISSUE THREAD

**Issue by dmitrif** [strapi/strapi#11409]
### Please describe your feature request

- [ ] Allow overriding passport strategy outside of EE Gold plan.
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Currently the SSO implementation is entirely gated behind the SSO gold plan. This makes sense for enterprise customers that do not wish to spend extra effort implementing it.

For those of us with shallower pockets, one would hope that it'd be possible to write your own plugin / implementation. 

Currently due to the fact that it's impossible to override the admin backend (without forking), there is no feasible way to enable alternative auth strategies as passport is initialized with a localStrategy only.

For this reason, I ask that the Passport strategies are configurable outside of the EE Gold plan.

### Why is it needed?

I'm frustrated that the extensibility of the auth system is only reserved for EE Gold plan.

### Suggested solution(s)

I ask that the Passport strategies are configurable outside of the EE Gold plan.

### Related issue(s)/PR(s)

N/A

**Comment by derrickmehaffy** [comment]
Hi @dmitrif thanks for opening this, I've notified some of the core team directly on this.

**Comment by dmitrif** [comment]
Thanks @derrickmehaffy !

For posterity, these are the things I've tried:
- Override using `admin/src` overlays
    - Although one can overlay the frontend portions of strapi easily, the backend is not easily overwritable (minus forking).
    - Main problem is that on non-enterprise plan builds, the passport service (backend) is initialized with only a local auth strategy.
- Override passport strategies through plugin interface. This seems to happen too late in the lifecycle and has no effect.
- Override using server hooks on app level
    - They get loaded too early in the lifecycle, and end up getting overridden (see https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi/lib/core/load-hooks.js#L16) 
- Override using server hooks on plugin level
    - Logically checks out and seems to be a viable perspective. Haven't been able to get this to work yet, though.
- Don’t override the default auth middleware / passport strategy, and instead add an additional middleware / hook / passport instance on top.
    - This should work, but seems inefficient.

**Comment by JoeriSmits** [comment]
+1

**Comment by dmitrif** [comment]
Hi there, just wanted to see if the core team has had a chance to review this? Thanks.

**Comment by derrickmehaffy** [comment]
> Hi there, just wanted to see if the core team has had a chance to review this? Thanks.

We have lightly discussed it internally but at this time we can't unlock SSO to lower tiers or the community version at this time.
There is still some discussion happening internally hence why we haven't closed this, as soon as I know more I will share.

**Comment by krichard-gg** [comment]
Checking to see if there is further update since @derrickmehaffy comment on December 28th?

**Comment by derrickmehaffy** [comment]
No, no further updates at this time.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/current-sso-implementation-too-restrictive
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
