### ISSUE TITLE
Create random post id not auto increment

### ISSUE THREAD

**Issue by vivekmpuh** [strapi/strapi#11416]
Hello,

I'am using strapi with MySQL as database, what I noticed is the post id / entry id are auto incremented, How can I make them random generated id's

current working: 
```
posts: [{
    id: 1,
    title: 'some post title'
},{
    id: 2,
    title: 'another post title'
}]
```

what I need is:
```
posts: [{
    id: 4532243434,
    title: 'some post title'
},{
    id: 23523434,
    title: 'another post title'
}]
```

How can I achieve this, please any help is appreciated !!!
Thanks

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
