### ISSUE TITLE
can't create a new project with @beta

### ISSUE THREAD

**Issue by potros** [strapi/strapi#11414]
### Describe the bug

i use
 npx create-strapi-app@beta beta --quickstart
to create a new strapi project but it fails with these error : 

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/provider-upload-local@4.0.0-beta.7
npm WARN Found: peer @strapi/plugin-upload@"^4.0.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @strapi/plugin-upload@"^4.0.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @strapi/plugin-upload@^4.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Steps to reproduce the behavior

1. Run npx create-strapi-app@beta beta --quickstart

### Expected behavior

the projects run correctly

### System

- Node.js version: 16.6.2
- NPM version: 7.20.3
- Strapi version: Beta
- Database: sqlite
- Operating system: windows

**Comment by derrickmehaffy** [comment]
> Node.js version: 16.6.2
> NPM version: 7.20.3

Node 16 support is coming, patience 😛 

For now you need to use Node 14 and NPM 6
