### ISSUE TITLE
api endpoint's pagination params converted wrongly

### ISSUE THREAD

**Issue by zhuang17** [strapi/strapi#1142]
**Informations**
- **Node.js version**:
v9.11.1
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.1.2
- **Database**:
MongoDB
3.6.3
- **Operating system**:
MacOS 10.12

**What is the current behavior?**
The pagination params parsed error.

**Steps to reproduce the problem**
1. Create a `article` ContentType in Admin UI,
2. add some records for article collection,
3. try access api endpoint with pagination params (limit, skip),
http://localhost:1337/article?limit=10&skip=0&sort=createdAt
4. the api return empty array. []

**What is the expected behavior?**
the api should return records by pagination.

**Suggested solutions**

following is the generated API services.fetchAll method on my side
```
  fetchAll: (params) => {
    const convertedParams = strapi.utils.models.convertParams('article', params);

    return Article
      .find()
      .where(convertedParams.where)
      .sort(convertedParams.sort)
      .skip(convertedParams.start)
      .limit(convertedParams.limit)
      .populate(_.keys(_.groupBy(_.reject(strapi.models.article.associations, {autoPopulate: false}), 'alias')).join(' '));
  },
```

when i access the api http://localhost:1337/article?limit=10&skip=0&sort=createdAt 

The result always return [] array,
I log the params and convertedParams values

```
params: { limit: '10', skip: '0', sort: 'createdAt' }
convertedParams: { where: { limit: '10', skip: '0', sort: 'createdAt' },
  sort: '',
  start: 0,
  limit: 100 }
```
looks like the `params { start, limit }` i passed from URL is not parsed as `pagination` param, but parsed as where condition ?

So is there any configuration where i can set the pagination param field, so the strapi.utils.models.convertParams can work well ?

or i should directly change the fetchAll method here ?

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @zhuang17 You are using wring params. Please follow the documentation https://strapi.io/documentation/guides/filters.html.

You have to user `_limit` and `_sort`.

**Comment by zhuang17** [comment]
@lauriejim Thanks,  it works.
