### ISSUE TITLE
Strapi Startup Alters Tables unexpectedly (constraints, 

### ISSUE THREAD

**Issue by linkeal** [strapi/strapi#11421]
### Describe the bug

We have a three environment setup (dev, uat, prod) and build the Strapi Container once for all environments. Our Strapi configuration including the api, config, components, extension folders are copied into our container. The .cache, build and npm_modules is excluded in our container and then build up on build/start time.

Database migrations (adding new columns, tables etc.) and inserting/removing important values like e.g. entries into users-permissions_permission are handled externally via dbmate.

We would like to give Strapi a limited user in production which can only execute Select, Insert, Update, Delete statements and no alter table statements anymore, since all migrations should be handled via our external database migration tool.

However we run into an issue that Strapi tries to drop constraints that do not even exist:

E.g. 
```
2021-11-01 11:41:28.953 CET [78] ERROR:  constraint "enum_eingabewertes_published_at_unique" of relation "enum_eingabewertes" does not exist
2021-11-01 11:41:28.953 CET [78] STATEMENT:  alter table "enum_eingabewertes" drop constraint "enum_eingabewertes_published_at_unique"

(It is trying to drop 477 constraints actually!)
```

I do not understand why Strapi tries to drop constraints that do not exist. Has anyone an hint to what this can be related?
This leads to the problem that we cannot give Strapi a limited rw database user user since it won't start when it cannot try to execute those alter statements even though they are unnecessary.

We have also set the `autoMigration` to false.

This error only occurs on the first startup of an container. Afterwards Strapi caches somewhere that it tried to drop the constraints and won't try again. (Is that in the build folder encoded somehow?)

### Steps to reproduce the behavior

Was not yet able to create a minimal example of this.

### Expected behavior

When autoMigration is turned off, any alter statements of Strapi should not be executed. Would be good if Strapi would throw an info/debug message regarding this to inform the user but not execute it. If it cannot start without it should simply fail.

### System
- Node.js version: v14.16.1
- Strapi version: 3.5.3
- Database: Postgres 13.3
- Operating system: Alpine (Docker)

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.5.8

Are you actually on 3.5.8 or was that a typo for 3.6.8? On either version I can't reproduce this.

**Comment by linkeal** [comment]
> Are you actually on 3.5.8 or was that a typo for 3.6.8? On either version I can't reproduce this.

Indeed a typo. Tested on an upgraded and 3.6.8 and was normally running on 3.5.3. Will try to provide a reproduceable example. Any hints what is included in the autoMigration and what is not?

**Comment by linkeal** [comment]
Someone with the same error messages some time ago: https://stackoverflow.com/questions/60004499/problem-with-making-fields-required-in-strapi

**Comment by derrickmehaffy** [comment]
> > Are you actually on 3.5.8 or was that a typo for 3.6.8? On either version I can't reproduce this.
> 
> Indeed a typo. Tested on an upgraded and 3.6.8 and was normally running on 3.5.3. Will try to provide a reproduceable example. Any hints what is included in the autoMigration and what is not?

Pretty much any create or update SQL statement. I'd recommend turning on `debug: true` in your database.js file as that will dump the raw SQL statements.



> Someone with the same error messages some time ago: https://stackoverflow.com/questions/60004499/problem-with-making-fields-required-in-strapi

That message is quite old :thinking:

**Comment by derrickmehaffy** [comment]
Given how old this issue is, I'll set it as closed for now but if someone can reproduce on Strapi v4 please feel free to open a new issue and link back to this one. Thanks!

**Comment by ScyDev** [comment]
I have the same problem on 4.1.8.

```
sixpack-shop-strapi-server       | Starting the development server...
sixpack-shop-strapi-server       | 
sixpack-shop-strapi-server       | Admin development at http://0.0.0.0:8080/admin/
sixpack-shop-strapi-server       | <i> [webpack-dev-server] Project is running at:
sixpack-shop-strapi-server       | <i> [webpack-dev-server] Loopback: http://localhost:8080/
sixpack-shop-strapi-server       | <i> [webpack-dev-server] On Your Network (IPv4): http://172.18.0.4:8080/
sixpack-shop-strapi-server       | <i> [webpack-dev-server] Content not from webpack is served from '/srv/app/public' directory
sixpack-shop-strapi-server       | <i> [webpack-dev-server] 404s will fallback to '/admin/'
sixpack-shop-strapi-server       | [2022-05-26 11:51:47.466] debug: ⛔️ Server wasn't able to start properly.
sixpack-shop-strapi-server       | [2022-05-26 11:51:47.467] error: alter table "products" drop constraint "idx_products__old_artikel_id__old_pid" - constraint "idx_products__old_artikel_id__old_pid" of relation "products" does not exist
sixpack-shop-strapi-server       | error: alter table "products" drop constraint "idx_products__old_artikel_id__old_pid" - constraint "idx_products__old_artikel_id__old_pid" of relation "products" does not exist
sixpack-shop-strapi-server       |     at Parser.parseErrorMessage (/srv/app/node_modules/pg-protocol/dist/parser.js:287:98)
sixpack-shop-strapi-server       |     at Parser.handlePacket (/srv/app/node_modules/pg-protocol/dist/parser.js:126:29)
sixpack-shop-strapi-server       |     at Parser.parse (/srv/app/node_modules/pg-protocol/dist/parser.js:39:38)
sixpack-shop-strapi-server       |     at Socket.<anonymous> (/srv/app/node_modules/pg-protocol/dist/index.js:11:42)
sixpack-shop-strapi-server       |     at Socket.emit (events.js:376:20)
sixpack-shop-strapi-server       |     at Socket.emit (domain.js:470:12)
sixpack-shop-strapi-server       |     at addChunk (internal/streams/readable.js:309:12)
sixpack-shop-strapi-server       |     at readableAddChunk (internal/streams/readable.js:284:9)
sixpack-shop-strapi-server       |     at Socket.Readable.push (internal/streams/readable.js:223:10)
sixpack-shop-strapi-server       |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
sixpack-shop-strapi-server exited with code 1
```

**Comment by seth146** [comment]
Same problem on 4.1.10. - why is Strapi altering the tables on startup? I'm using Supabase Postgres as the DB for Strapi as well as for the rest of my app, and it is very beneficial to be able to link my Strapi content to the backend entities which only live in Supabase.

`[2022-05-26 17:44:12.146] debug: ⛔️ Server wasn't able to start properly.
[2022-05-26 17:44:12.147] error: alter table "groups" drop constraint "groups_pathway_id_fkey" - must be owner of table groups
error: alter table "groups" drop constraint "groups_pathway_id_fkey" - must be owner of table groups
    at Parser.parseErrorMessage (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/pavol/Documents/ksebe/group-app/ally-app-cms/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
