### ISSUE TITLE
CRUD permissions resetting when updating collection type

### ISSUE THREAD

**Issue by NicolasTsc** [strapi/strapi#11420]
### Describe the bug

Hello,
we currently have a permissions issue in our deployed Strapi environments.
For one content type the CRUD permissions for "/admin/settings/roles/2" get resetted for the editor role whenever we change something for the specific content type.
Therefore after we deployed the changes our editors can`t edit the content unless we change the permissions manually in the dashboard.
We have the problem only for one content type.

### Steps to reproduce the behavior
Hard to reproduce as this error only occurs 

### Expected behavior

The permissions not getting resetted.

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
