### ISSUE TITLE
Upload HEIC files as images

### ISSUE THREAD

**Issue by lechinoix** [strapi/strapi#11422]
### Describe the bug

When uploading a HEIC image (apple's format) on my strapi the media plugin does not seem to handle it like an image. I am using Cloudinary provider setup as documented in the documentation.

### Steps to reproduce the behavior

1. Install strapi with media plugin
2. Upload a HEIC file
3. It will not appear like an image but more like a document

### Expected behavior

I would expect the plugin to convert HEIC format to something like JPEG before uploading it as an image.

Is it possible to create a hook before upload to do this ?

### Screenshots

![image](https://user-images.githubusercontent.com/10167015/139681353-e731713f-f665-4c52-852d-3ff7a3a53ff5.png)

### System

Package.json

```
    "strapi": "3.6.8",
    "strapi-admin": "3.6.8",
    "strapi-connector-bookshelf": "3.6.8",
    "strapi-plugin-content-manager": "3.6.8",
    "strapi-plugin-content-type-builder": "3.6.8",
    "strapi-plugin-email": "3.6.8",
    "strapi-plugin-i18n": "3.6.8",
    "strapi-plugin-upload": "3.6.8",
    "strapi-plugin-users-permissions": "3.6.8",
    "strapi-provider-upload-cloudinary": "^3.6.8",
    "strapi-utils": "3.6.8"
```

System :

```
node: v12.20.0
npm: 6.14.8
MacOS: Catalina 10.15.7
```

**Comment by kasonde** [comment]
Hi, the Strapi media library treats files as files.[ HEIC is a proprietary image format for Apple devices](https://backlightblog.com/iphone-heic-to-jpg) that is not commonly adopted by all platforms (web browsers such as Chrome, etc) as an image format. Essentially it's a file. If you need to convert it to JPEG, you need to convert it post or pre-upload to Cloudinary. I'm closing this issue here as it's not an issue but a question on how to customize the upload process. For your Cloudinary upload provider, for example, your solution is in the [plugin documentation](https://www.npmjs.com/package/strapi-provider-upload-cloudinary).

**Comment by lechinoix** [comment]
Hello, thanks for the answer, I totally agree with this, but actually it is a real pain that I have : all the photo taken from my iPhone are at this format and I do not take advantage of all the feature of the upload plugin (thumbnails etc...). I was hoping for 2 options :

- A beforeUpload hook where I could convert my file to jpeg
- A option to do so directly in the plugin (like I just began to try on [a fork here](https://github.com/lechinoix/strapi/commit/92dbd5deb6ad747254f819f3448a1028e9a04d74))

Maybe we can repost this issue as a feature request ?

**Comment by derrickmehaffy** [comment]
> Hello, thanks for the answer, I totally agree with this, but actually it is a real pain that I have : all the photo taken from my iPhone are at this format and I do not take advantage of all the feature of the upload plugin (thumbnails etc...). I was hoping for 2 options :
> 
> * A beforeUpload hook where I could convert my file to jpeg so the plugin handle it as jpeg
> * A option to do so directly in the plugin (like I just began to try on [a fork here](https://github.com/lechinoix/strapi/commit/92dbd5deb6ad747254f819f3448a1028e9a04d74))
> 
> Maybe we can repost this issue as a feature request ?

Sure if you want to repost as a feature request that's fine.
