### ISSUE TITLE
[v4] API Tokens are not part of the authentication strategies for content-api

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11425]
### Describe the bug

Trying to use a read or full access API token doesn't work and returns a 401 error. Debugging the core strapi authentication method shows that API tokens are not injected into the `strategiesToUse` (see screenshot)

### Steps to reproduce the behavior

1. Create a read or full access API Token
2. Try to call any content-api endpoint
3. See error

### Expected behavior

API Tokens should function on the content-api routes
- Read Token: any find or findOne route
- Full Access Token: any method

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/139745139-c40ea5c8-c60b-4efb-a195-4346bddf10d6.png)

### Code snippets

N/A

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.7
- Database: SQLite
- Operating system: Linux Mint 20.2

### Additional context

Tested using Postman and curl

**Comment by alexandrebodin** [comment]
The feature is not enable until all the frontend is ready

**Comment by Aprilswind** [comment]
Issue still persisting
