### ISSUE TITLE
ctx.state.user is not populated if the route isn't configured with at least an empty policy array

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#11427]
### Describe the bug

In Strapi v3.6.8, ctx.state.user is not populated if you do not define
```json
"config": {
    "policies": []
  }
```
on the route object. Even though in this case, I have no use for policies on this route. This makes it impossible to see the currently logged-in user that is trying to access that route.

### Steps to reproduce the behavior

1. Create a controller (any content type)
2. Define a route for that controller but omit the above JSON property
3. Try to access `ctx.state.user` in the controller. This will return `undefined`
4. Include the above properties in the route definition and the query will return the desired result.

### Expected behavior

To my understanding, not specifying a policy config shouldn't omit a route from populating the currently logged in user. `ctx.state.user` must be populated always.

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 3.6.8
- Database: MySQL
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
Intended as this doesn't allow the uesrs-permissions plugin to inject it's policy. It is an undocumented way to disable auth on a route. We decided not to document this in v3 as it wasn't recommend and in the v4 it has been replaced with a boolean option in the routes to disable auth (eg. `auth: false` to disable it).

It's documented in v4 I believe so going to close this as it's intended.
