### ISSUE TITLE
Preprocess HEIC files before upload-plugin

### ISSUE THREAD

**Issue by lechinoix** [strapi/strapi#11426]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
 - Could use a link here, I wandered 5min on the Projects tab of github before understanding it was [here](https://portal.productboard.com/strapi)
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I would like to be able to apply a format conversion to my images before running those through the upload plugin.

### Why is it needed?

All the photos taken from iPhone are at the HEIC format, which is handled by the upload plugin as files and not images. This means that I do not have a preview in my gallery and I do not have the wanted image formats (thumbnails etc...)

### Suggested solution(s)

As suggested in [this issue](https://github.com/strapi/strapi/issues/11422), I could apply the tranfomation on cloudinary side but I would not have the strapi model correctly filled with formats.

2 suggestions :

- Give an option on the upload plugin to convert some formats to JPEG. This should remain an option or be safe checked because `sharp` needs `libheic` and `libvips` to process HEIC formats. I tried something like this in [a fork](https://github.com/lechinoix/strapi/commit/92dbd5deb6ad747254f819f3448a1028e9a04d74)
- Give a new synchronous hook on Media upload `beforeUpload` to give the opportunity of preprocessing the file before sending it to the plugin

I prefer the second one as it gives more flexibility to the developer and is simpler to implement and maintain on strapi side (no checks on needed dependencies for example)

### Related issue(s)/PR(s)

Related to [this issue](https://github.com/strapi/strapi/issues/11422) wrongly posted as a bug report.

**Comment by lechinoix** [comment]
Happy to contribute on this one if either solution seems interesting to you :)

**Comment by derrickmehaffy** [comment]
@lechinoix can you go through our RFC process and submit an RFC on how you would handle this? https://github.com/strapi/rfcs

**Comment by petersg83** [comment]
Hi @lechinoix,

If you make a special installation of sharp liked discribed here: https://github.com/lovell/sharp/issues/1105#issuecomment-516010573 Does sharp recognize correctly your image?

**Comment by martpet** [comment]
Hello lechinoix,

If you set "accept" to "images/jpeg":

`<input type="file" accept="images/jpeg" />`

then Safari will automatically convert HEIC to JPEG when you select a HEIC image.

**Comment by derrickmehaffy** [comment]
Marking as closed as it's not likely something we will work ourselves
