### ISSUE TITLE
server stopped after add relation

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1143]
**Informations**
- **Node.js version**: 
- **npm version**: 10.0.0
- **Strapi version**: 5.6.0
- **Database**: mongodb 3.6
- **Operating system**: Linux

**What is the current behavior?**
server stopped after add relation.

**Steps to reproduce the problem**
I create new content type called **company** like below:
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "company",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "maxLength": 30,
      "type": "string",
      "required": true
    },
    "description": {
      "type": "string"
    }
  }
}
```

I want to link company to users content type so I add a n:1 (company has many users) relation field in **Users** and when I click save I see this error in my terminal and my strapi server has stopped:
```
[2018-05-08T09:53:23.498Z] error Something went wrong in the model `User` with the attribute `company`
[2018-05-08T09:53:23.500Z] error Cannot read property 'models' of undefined
```

**What is the expected behavior?**

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
I have come across this issue before as well. Especially when adding relations to existing models.

**Comment by cece95** [comment]
i think that this issue is the same as #1139
