### ISSUE TITLE
more instances on the same domain

### ISSUE THREAD

**Issue by GALLLASMILAN** [strapi/strapi#11440]
### Describe the bug

If you have two or more instances on the same domain, you are able to be logged in only in 1 instance at the same time. 
The problem is when the user is logged in via third party authentication. The jwtToken is saved in Cookies and then it is moved from cookies to the localStorage.

The Strapi does not work with **path** or **domain** attribute when sending the jwtToken via ctx to the client:

```
const redirectWithAuth = ctx => {
  //  ....................
  const cookiesOptions = { httpOnly: false, secure: isProduction, overwrite: true };
  // ................
  ctx.cookies.set('jwtToken', jwt, cookiesOptions);
  // ............
};
```
and when I rewrite a cookies path via Nginx, it does not help me, because the localStorage is shared for all instances. 

### Steps to reproduce the behaviour

1. start the first instance via yarn start and server it via Nginx with location /instance-a
2. start the second instance via yarn start and server it via Nginx with location /instance-b
3. login to the first instance via digital identity
4. login to the second instance via digital identity => you will be logged from the first instance after page reload

### Expected behaviour
I will be able to set a default cookies path via configuration (some env property) and I will be able to set **TOKEN_KEY** and  **USER_INFO** in the https://github.com/strapi/strapi/blob/master/packages/strapi-helper-plugin/lib/src/utils/auth.js as well. 
The second part with auth.js is more important.

### System

- Node.js version: **v14.18.1**
- NPM version: **8.0.0**
- Strapi version: **3.6.5**
- Database: **postgres:11**
- Operating system: **Debian GNU/Linux 10 (buster)**

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/more-instances-on-the-same-domain

Thanks!
