### ISSUE TITLE
strapi-plugin-sentry is disabled because no Sentry DSN was provided

### ISSUE THREAD

**Issue by thunderwin** [strapi/strapi#11447]
### Describe the bug

strapi-plugin-sentry is disabled because no Sentry DSN was provided

### Steps to reproduce the behavior

1 yarn add strapi-plugin-sentry

2 
```
  sentry: {
    // https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-sentry
    dsn: env("SENTRY_DSN"),
    sendMetadata: true,
  },
```

not working 

shows 
**strapi-plugin-sentry is disabled because no Sentry DSN was provided**
why??

I do provide SENTRY_DSN, even I hard code it. still won't work

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
