### ISSUE TITLE
Error when adding relation to Admin User in v4beta

### ISSUE THREAD

**Issue by Strapi-User** [strapi/strapi#11456]
### Describe the bug

(Strapi v4 beta)
Error thrown (400 Bad Request) when attempting to save a collection type containing a relation to Admin User (admin::user) in Content-Type Builder. The error indicates that only "oneToOne" and "oneToMany" relations are allowed, despite the request already using such a relation.

Changing the relation to point to a User from users-permissions works, so it only appears to affect admin users.

### Steps to reproduce the behavior

1. Go to Content-Type Builder in Strapi Admin UI
2. Create a new Collection Type
3. Add a relation to "User (from: admin)"
4. Leave the default One-to-One relationship (or change to One-to-Many), then click "Finish"
5. Click the "Save" button for the Content-type 
4. Observe that an error message is shown and the definition for the new collection is not saved. The following error message is returned in the response: `{"error":{"contentType.attributes.admin_user.relation":["must be one of the following values: oneToOne, oneToMany"]}}`

### Expected behavior

The new collection type should be saved with a relation pointing to admin users, without throwing any errors.

### Screenshots
Screenshot showing the request to save a collection type definition with a relation to an admin user:
![v4beta_add_admin_user_relation](https://user-images.githubusercontent.com/93653909/140071119-43c16560-ac62-40ae-8ef6-146d5efc0d5e.png)

Screenshot showing the error response:
![v4beta_add_admin_user_relation_error](https://user-images.githubusercontent.com/93653909/140071137-7a479d37-513f-4711-9b4b-eaf273e72c2e.png)

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.0-beta.7
- Database: SQLite
- Operating system: Ubuntu 18.04 LTS

**Comment by derrickmehaffy** [comment]
Confirmed on beta.9

Payload coming from CTB to Backend:

```json
{
  "components": [],
  "contentType": {
    "displayName": "Blog Posts",
    "singularName": "blogpost",
    "pluralName": "blogposts",
    "description": "",
    "draftAndPublish": true,
    "pluginOptions": { "i18n": { "localized": true } },
    "kind": "collectionType",
    "collectionName": "blogpost",
    "attributes": {
      "title": {
        "type": "string",
        "required": true,
        "unique": true,
        "default": "test",
        "pluginOptions": { "i18n": { "localized": true } }
      },
      "body": {
        "type": "richtext",
        "required": true,
        "pluginOptions": { "i18n": { "localized": true } }
      },
      "date": {
        "pluginOptions": { "i18n": { "localized": true } },
        "type": "date"
      },
      "time": {
        "pluginOptions": { "i18n": { "localized": true } },
        "type": "time"
      },
      "datetime": {
        "pluginOptions": { "i18n": { "localized": true } },
        "type": "datetime"
      },
      "singleAdmin": {
        "relation": "oneToOne",
        "target": "admin::user",
        "type": "relation"
      },
      "multiAdmins": {
        "relation": "oneToMany",
        "target": "admin::user",
        "type": "relation"
      }
    }
  }
}
```

Error Response:

```json
{
  "error": {
    "contentType.attributes.singleAdmin.relation": [
      "must be one of the following values: oneToOne, oneToMany"
    ],
    "contentType.attributes.multiAdmins.relation": [
      "must be one of the following values: oneToOne, oneToMany"
    ]
  }
}
```

---

Relation types accepted are correct in the CTB:
![image](https://user-images.githubusercontent.com/8593673/140174755-94f95823-96b7-41da-ad17-55b8d94bc13c.png)

It appears the backend validation is set incorrect as the proper relations should be `oneWay` and `manyWay` (assuming we are still using those names internally)

**Comment by derrickmehaffy** [comment]
confirmed on beta.11

**Comment by JabStrapi** [comment]
Should be fixed in beta.18
