### ISSUE TITLE
Await inside lifecycle-event causes unexpected behaviour

### ISSUE THREAD

**Issue by EternalBlack** [strapi/strapi#11452]
### Describe the bug

_This might not be applicable to lifecycle hooks in general but certainly is when overriding the upload plugins model (`extensions/upload/models/File.js`)._

When using an `await`call inside a lifecycle hook the code does get executed BUT altering `data` after the `await` doesn't change anything in the DB.

### Steps to reproduce the behavior

1. Override lifecycle hook of upload plugin
2. Add `beforeCreate`
3. Alter data after an `await` call
4. Don't see any changes made to data after the `await` in the DB

### Expected behavior

See changes made after the `await`call propagating into the DB.

### Code snippets

_File.js_
```js
"use strict";

module.exports = {
  lifecycles: {
    async beforeCreate(data) {
      console.log("#############################################");
      data.caption = "my value" // This gets set and is in the DB and API
      let value = await myFunc("my Arg");
      console.log(value); // this gets printed
      data.caption = value; // this is not present in the DB even though `$value` does have a value
      console.log(data.caption); // this gets printed as well
      console.log(data); // even this has the correct value in it

      async function myFunc(myParam) {
        const a = await npm_package_func();
        const b = myParam+a;
        return b;
      }

      console.log("END BEFORE CREATE"); // does get executed in order as well
    },

    afterCreate(result) {
      console.log("AFTER CREATE HERE");  // does get executed in order as well
    },
  },
};
```

Removing the `await` stores "_[Object Promise]_" as String inside the DB.

### System

- Node.js version: v14.16.0
- NPM version: 6.14.11 (but using yarn 1.22.5)
- Strapi version: 3.6.8
- Database: mariadb (latest)
- Operating system: Host MacOS 11.6 (20G165) but using original Docker of Strapi to run Strapi using Docker-Compose

### Additional context

Also running Redis for caching

**Comment by EternalBlack** [comment]
I just recreated the the hole system from a clean slate and this time couldn't reproduce the error.
Will investigate further though as it dawns me that this might be some sort of incompatibility of plugins.

I'll keep you posted if I find anything, otherwise I'll close the issue as this might be something on my end and not actually related to Strapi.

**Comment by EternalBlack** [comment]
As expected this was a plugin incompatibility issue (which I could have noticed beforehand if I had properly read the readme of that plugin🤦🏼‍♂️)...
So this is not Strapis fault at all. Sorry for the confusion.

Plugin that caused the issue (it overrides the `beforeCreate`:
https://github.com/darron1217/strapi-plugin-video-thumbnail

**Comment by derrickmehaffy** [comment]
> So this is not Strapis fault at all. Sorry for the confusion.

It happens :laughing: 

When we get to the marketplace things will get a bit easier because we can validate plugins for a specific Strapi version
