### ISSUE TITLE
Media object consists of data which is not needed. In most cases - URL is only required.

### ISSUE THREAD

**Issue by 239yash** [strapi/strapi#11454]
`   "CoverImage": {
      "id": 1,
      "name": "",
      "alternativeText": "",
      "caption": "",
      "width": 1366,
      "height": 768,
      "formats": {
        "thumbnail": {
          "name": "",
          "hash": "",
          "ext": ".png",
          "mime": "image/png",
          "width": 245,
          "height": 138,
          "size": 28.7,
          "path": null,
          "url": ""
        },
        "large": {
          "name": "",
          "hash": "",
          "ext": ".png",
          "mime": "image/png",
          "width": 1000,
          "height": 562,
          "size": 245.9,
          "path": null,
          "url": ""
        },
        "medium": {
          "name": "",
          "hash": "",
          "ext": ".png",
          "mime": "image/png",
          "width": 750,
          "height": 422,
          "size": 160.31,
          "path": null,
          "url": ""
        },
        "small": {
          "name": "",
          "hash": "",
          "ext": ".png",
          "mime": "image/png",
          "width": 500,
          "height": 281,
          "size": 85.53,
          "path": null,
          "url": ""
        }
      },
      "hash": "",
      "ext": ".png",
      "mime": "",
      "size": 165.36,
      "url": ",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": null,
      "created_at": "",
      "updated_at": ""
    }`

As we can see that media response comes as an object with a whole lot of data which is not required. This data increases the response time, response size too. Can we have some way to only provide the URL of that media in the response?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by adriaanvanrossum** [comment]
Related for future searchers: https://forum.strapi.io/t/reduce-attributes-in-media-column/23855
