### ISSUE TITLE
[V4] Context-aware `register()` function 🖊️ 

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11463]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

_Pre-Scriptum_: I know V4 are almost there, but not yet fully documented, so maybe it's already planned, if so please pardon the interruption ")

--- 

It would great for the new `register()` function to automatically detect its context (Collection Type it relates to).

### Why is it needed?

This would make it more modular and easier to organize files, moreover it would to prevent the `src/index.js` from ballooning up as the app grows.

### Suggested solution(s)

Perhaps it could be done in a way where for a given Collection Type, say, a `Post` we could handle the `register()` for that Collection Type in a file `src/api/post/index.js` instead of `src/index.js`.

Thanks in advance and happy Thursday!

**Comment by derrickmehaffy** [comment]
We have already implemented this in v4, so going to mark it as closed for now but if it's not clear let me know.
