### ISSUE TITLE
Unable to use watch mode after stopping server previously in watch mode

### ISSUE THREAD

**Issue by malgamves** [strapi/strapi#11472]
### Describe the bug

Stopping the the Strapi server in watch mode (`yarn develop --watch-admin`) with `Ctrl + C` (Windows 10) doesn't end the node process but stops the server. When I restart the server in watch mode again after, it will not be in watch mode even if i use the `--watch-admin` because previous node process is still running (I'm guessing) because of this I can't see changes to admin as I make them when developing a plugin.

### Steps to reproduce the behavior

1. Create Strapi app with `npx ctreate-strapi-app@beta <project> --quickstart`
2. Stop server with `Ctrl + C`
3. Restart server in watch mode with `yarn develop --watch-admin` 
4. Make edits, see them reflect in Admin immediately
5. Stop server with `Ctrl + C`
6. See error shown below
7. Restart server in watch mode with `yarn develop --watch-admin` 
8. Observe behavior described above

### Expected behavior

The server should stop and not show and error. I should also be able to be it watch mode when I restart the server with `yarn develop --watch-admin`

### Screenshots

Here is a screenshot of the error when I stop watch mode

![image](https://user-images.githubusercontent.com/25641936/140384467-961f508e-9490-473d-9145-3cb04e3d0cb5.png)

### Code snippets

This is the text error when I stop watch mode
```
(node:820) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'destroy' of undefined
    at Strapi.runLifecyclesFunctions (C:\Users\malga\Desktop\Code\v4-plugin-demo\node_modules\@strapi\strapi\lib\Strapi.js:464:43)
    at async Strapi.destroy (C:\Users\malga\Desktop\Code\v4-plugin-demo\node_modules\@strapi\strapi\lib\Strapi.js:175:5)
    at async process.terminateStrapi (C:\Users\malga\Desktop\Code\v4-plugin-demo\node_modules\@strapi\strapi\lib\utils\signals.js:12:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### System

- Node.js version: 14.15.0
- NPM version: 7.24.1
- Strapi version: 4.0.0-beta.9
- Database: sqlite
- Operating system: Windows 10

### Additional context

I had to go to my task manager and stop all node processes, after which running `yarn develop --watch-admin` works as expected.

**Comment by derrickmehaffy** [comment]
Just noticed in beta.11 that using `ctrl + c` to kill the server yields this:

```
^C(node:2454189) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'destroy' of undefined
    at Strapi.runLifecyclesFunctions (/mnt/storage/Development/testBeta11/node_modules/@strapi/strapi/lib/Strapi.js:466:43)
    at async Strapi.destroy (/mnt/storage/Development/testBeta11/node_modules/@strapi/strapi/lib/Strapi.js:175:5)
    at async process.terminateStrapi (/mnt/storage/Development/testBeta11/node_modules/@strapi/strapi/lib/utils/signals.js:12:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2454189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2454189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So same thing happens in Linux using the `yarn develop --watch-admin`

**Comment by derrickmehaffy** [comment]
Fixed in beta.14
