### ISSUE TITLE
[FR] [v3/v4] Display Filename for documents in media field.

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11474]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

The Strapi Media Field (v3 and v4) does not display any relevant information regarding the 'uploaded/chosen' file.
As demonstrated in the following screenshot, the user does not know, what file he/she actually chose/uploaded.
It almost looks like no file has been selected.

#### Not Working (Documents etc)

V3
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/5942270/140480364-e4e6d897-aa47-4c3c-87c4-854e77fd8f6f.png">

V4
![image](https://user-images.githubusercontent.com/5942270/140481136-9d86356e-7f8a-42e6-b8ca-5e9d57b9d519.png)

#### Working (Images etc)

Image/Video/Gifs work fine. They display a preview. 
![image](https://user-images.githubusercontent.com/5942270/140481021-96dbaea3-04c4-48e1-a562-6724e12093ed.png)

### Why is it needed?

As an author who regularly uploads documents for their users to download, it gets really confusing, since the UI does not provide any feedback on the actual uploaded/chosen file. I have to constantly click on 'edit' to see the filename.

### Suggested solution(s)

I suggest to display its filename.extension. The media field has enough whitespace to add some text.
If the filename is too long, truncate it and display filename[...].pdf for example.

**Comment by derrickmehaffy** [comment]
Already exists, checked in v4.1.5
