### ISSUE TITLE
[V4] A way of getting full data is missing

### ISSUE THREAD

**Issue by Stun3R** [strapi/strapi#11473]
### Describe the bug

Unable to get full data from content-type with limit.

### Expected behavior

In **v3** we were able to retrieve every data from a content type by passing a limit equal to `-1`.
For static site generation or when you can't have an API running all the time, it is great to be able to retrieve all data and just bypass the pagination

### Code snippets

Tried to get all data by bypassing the limit thanks
```js
pagination[start]=0&pagination[limit]=-1
```

### System

- Node.js version: v14.18.1
- Strapi version: 4.0.0-beta.6
- Database: PG
- Operating system: MacOS BigSur

**Comment by derrickmehaffy** [comment]
Confirmed on beta.10, there is no method to fetch all entries since we are converting the Strapi `pagination[limit]` to SQL limit. We need to check if the limit is < 0 and omit the limit from the SQL query

**Comment by derrickmehaffy** [comment]
(confirmed on beta.11)
