### ISSUE TITLE
[v4] Sending malformed POST payload in REST yeilds a 500 error

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11489]
### Describe the bug

if you send an improper POST body payload it will throw a 500 error

### Steps to reproduce the behavior

1. Create a collection type with Draft & Published enabled
2. Set permissions and/or create a user and auth
3. Send a POST request with keys inside an object (without a data object)

### Expected behavior

Should return a 400 Bad Request error, not a 500

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/140578466-d46440a6-9251-4943-a9bb-3c301aa5bec9.png)
![image](https://user-images.githubusercontent.com/8593673/140578529-6c56f1eb-dd66-4e13-8182-f949f450743f.png)
![image](https://user-images.githubusercontent.com/8593673/140578550-2124f0c4-7c11-4b24-9bfc-2bc450515436.png)

### Code snippets

Bad Payload:
```json
{
    "string": "test",
    "stringRequired": "test"
}
```

Good Payload:
```json
{
    "data": {
        "string": "test",
        "stringRequired": "test"
    }
}
```

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.11
- Database: SQLite
- Operating system:  Linux Mint 20.2

### Additional context

N/A

**Comment by DanieleAurilio** [comment]
Hi @derrickmehaffy ,
i think this is another bug related to `"data": {}` when object is empty.
When it is empty should generate an error 400?

If it is a bug, i have prepared a pull request that fixes the bug you described in this issue and the one reported by me.


![image](https://user-images.githubusercontent.com/52456860/141337402-ae73bf88-4093-4059-9214-12ef4999914a.png)


### System

- Node.js version: v14.17.1
- NPM version: v6.14.13
- Strapi version: 4.0.0-beta.11
- Database: MySQL
- Operating system: MacOS Big Sur

**Comment by derrickmehaffy** [comment]
Fixed in beta.13
