### ISSUE TITLE
Issue after upgrading to version 3.6.8

### ISSUE THREAD

**Issue by debolina1** [strapi/strapi#11488]
### Steps to reproduce the behavior

1. 
2. Go to ADMINISTRATION PANEL  
3. 
4. Go to Roles
5. 
6. Pick Editor

### Expected behavior
What to see the Editor screen but seeing error in the console. Page does not load

### Screenshots
main.7cf8a416.chunk.js:1 TypeError: Cannot read properties of null (reading 'indexOf')
    at main.7cf8a416.chunk.js:1
    at Array.reduce (<anonymous>)
    at e (main.7cf8a416.chunk.js:1)
    at main.7cf8a416.chunk.js:1
    at Array.reduce (<anonymous>)
    at d (main.7cf8a416.chunk.js:1)
    at main.7cf8a416.chunk.js:1
    at Array.reduce (<anonymous>)
    at main.7cf8a416.chunk.js:1
    at Array.reduce (<anonymous>)

### Code snippets

If applicable, add code samples to help explain your problem.

### System
STRAPI VERSION

v3.6.8

CURRENT PLAN

Community Edition

NODE VERSION

v14.15.1

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by JuanLGC** [comment]
Hi! @debolina1 did you manage to solve this issue? I'm having the exact same problem and can't find any answers
