### ISSUE TITLE
Default sort order for content types

### ISSUE THREAD

**Issue by krestaino** [strapi/strapi#1149]
**What is the expected behavior?**

I think a useful feature would be the ability to set the default sort order for a content type under the Content Manager. For example, lets say I have a field called `order` for my content type `project`. When I open up the `projects` content type in the admin, by default it would sort by this field which is an integer, rather than the current behavior where it sorts by ID. Ideally this could work with dates, alpha sorting, and numbers.

At first, I thought [`mainField`](https://strapi.io/documentation/guides/models.html#model-information) was exactly this, but it doesn't seem like it, and I wasn't able to figure out what `mainField` does.

I believe this functionality would be very useful for content managers of the admin.

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by Aurelsicoko** [comment]
@krestaino I'm super happy to see this kind of issue raising up! We've already been giving some thoughts to this problem. Here a screenshot of an unexisting part of the Content-Manager settings. We're iterating on the product, and it's in our plan to offer what you ask for!

![content manager - settings view - single](https://user-images.githubusercontent.com/4144726/39805837-415133fc-5378-11e8-8b8d-a109a3778b48.png)

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I know it has been suggested before, but one tiny addition to that (and I'm not sure if this would be easy or difficult to implement) but going along with what is editable, possibly something similar to change what is shown on the content manager? Though moving them around would be nice too, simply hiding a few would be a good start in the right direction.

**Comment by krestaino** [comment]
@Aurelsicoko That looks fantastic! Can't wait to play around with it.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy Great suggestion! I'm keeping it in mind, we could definitely add another option in the screenshot to hide fields or select the ones to show 👍

**Comment by Aurelsicoko** [comment]
FYI, I'm updating the design a little bit to add new settings on the latest view I shared with the community. I would put an update in few days...

**Comment by BroTrue** [comment]
@Aurelsicoko Is it already available?

**Comment by derrickmehaffy** [comment]
@BroTrue no I don't believe this feature is done yet. It is being developed in the following branch I believe: https://github.com/strapi/strapi/tree/settings-ctm

**Comment by Aurelsicoko** [comment]
Here the final design, we already started working on it 💪 

![content manager - settings view - single](https://user-images.githubusercontent.com/4144726/42336569-6318383a-8084-11e8-9573-fc48dc6bc67d.png)

**Comment by soupette** [comment]
#1529

**Comment by lauriejim** [comment]
It's merged on `master` branch

**Comment by krestaino** [comment]
@lauriejim Fantastic. I just played around with it, it's very nice.

Any idea when we'll see a new release with it?

**Comment by Aurelsicoko** [comment]
@krestaino If everything works as expected on our side, it should be released in ~2/3 weeks

**Comment by srishti-vs** [comment]
Can I reorder the Content Types (i.e instead of alphabetic sorting, I want it to be custom sort)?

**Comment by iamvermajayant** [comment]
Hi, How can i use this feature in my strapi project can anyone please explain
