### ISSUE TITLE
[BUG] [v3/v4] Publish / Unpublish does not change 'last edited by'.

### ISSUE THREAD

**Issue by LucaNerlich** [strapi/strapi#11498]
## Bug report

Assuming User A edited a documents content 30mins ago, the sidepanel will say 

Last Update: 30min ago
By: User A

If user B now either publishes or unpublishes it, the "last update" time changes, but the "by" does not.

I just got a huge scare, since our prod instance said "last updated by luca, 30mins ago". And I was 100% sure, that I did not do it. However, a colleague unpublished the content and therefore the time changed to 30mins ago. The "by" was from my actual text change, 3 days ago.

I hope this makes sense.
Same issue in v3 and v4.
Please see attached gif for an example.

### Steps to reproduce the behavior

1. User A edits a document
2. User B unpublishes it
3. By still says "user A".

### Expected behavior

Last update and by correctly update the user and time for content AND draft/publish actions.

### Screenshots

Please observe, that the logged in user does not get set as the 'by' user, when publishing / unpublishing.

### V3

![strapieditdraft](https://user-images.githubusercontent.com/5942270/140729660-be9ae4fc-1ec5-432c-97ef-fe347710e38e.gif)

### V4

![strapieditdraft2](https://user-images.githubusercontent.com/5942270/140730971-5cfaa72b-4437-46ad-931f-430c5ff60238.gif)

### System

- Node.js version: 14 LTS
- NPM version: 6
- Strapi version: 3.6.8 Enterprise
- Database: postgresql
- Operating system: All

**Comment by derrickmehaffy** [comment]
Confirmed on beta.11 and 3.6.8, using publish/unpublish doesn't change the updatedBy

**Comment by jakobsjoqvist** [comment]
@derrickmehaffy I can take a look on this if it's open for contributions?

**Comment by derrickmehaffy** [comment]
Fixed in beta.14, will not be backported to v3
