### ISSUE TITLE
strapi-admin dependency @casl/ability@4.1.6 was not updated

### ISSUE THREAD

**Issue by kakinada9** [strapi/strapi#11494]
### Describe the bug

Hi I am using Strapi 3.6.8 with nodejs - v14.18.1 and npm- 8.1.3. When I run npm i or npm update I am getting the warning 
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.18.1', npm: '8.1.3' }
npm WARN EBADENGINE }

after inspection I understood that strapi-admin has the dependency '@casl/ability@4.1.6' which supports npm version ^6.0.0. Is there a possibility to update that dependency to it's latest version.

### Steps to reproduce
npm i

### System

- Node.js version: v14.18.1
- NPM version: 8.1.3
- Strapi version: 3.6.8
- Database: mongodb 4*
- Operating system: ubuntu 20

I know it's not a bug bug but I don't know where to inform this issue..

**Comment by derrickmehaffy** [comment]
Can't confirm using yarn, appears to only happen with npm. This could be updated though: https://www.npmjs.com/package/@casl/ability

Finding a changelog though isn't fun as the repo for this is a mono-repo and their releases are per package (of which there is a lot).

**Comment by derrickmehaffy** [comment]
Gonna set this as a duplicate to: https://github.com/strapi/strapi/issues/11453
