### ISSUE TITLE
V4beta11, dynamic zone not in rest api request result

### ISSUE THREAD

**Issue by tsv38** [strapi/strapi#11493]
### Describe the bug

V4beta11, dynamic zone not in rest api request result

### Steps to reproduce the behavior

1. Content type with dynamic zone : test
  {
    "kind": "collectionType",
    "collectionName": "tests",
    "info": {
      "singularName": "test",
      "pluralName": "tests",
      "displayName": "test",
      "description": ""
    },
    "options": {
      "draftAndPublish": true
    },
    "pluginOptions": {},
    "attributes": {
      "first_name": {
        "type": "string"
      },
      "dynZone": {
        "type": "dynamiczone",
        "components": [
          "page.content"
        ]
      }
    }
  }

2. Fill content with component in dynamic zone and save
![image](https://user-images.githubusercontent.com/11597547/140648806-377fe2c8-8cef-4de7-8c4a-e06cadf5db6e.png)

3. call http://localhost:1337/api/tests
4. See error : no dyn zone
{"data":[{"id":1,"attributes":{"first_name":"Michel","createdAt":"2021-11-07T09:53:50.691Z","updatedAt":"2021-11-07T12:16:09.874Z","publishedAt":"2021-11-07T09:54:55.805Z"}}],"meta":{"pagination":{"page":1,"pageSize":25,"pageCount":1,"total":1}}}

### Expected behavior

Get dyn zone in api call result

### System

- Node.js version: node v14.18.1
- NPM version: 6.14.15
- Strapi version:  4.0.0-beta.11
- Database: sqlite
- Operating system: WSL

**Comment by derrickmehaffy** [comment]
This is intended as we don't populate anything by default. See the population docs (these will be improved with time)

Although this says relation population, it's the same for dyn-zones and components: https://docs-next.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population
