### ISSUE TITLE
[v4] beta 10 relation dropdown in components hidden

### ISSUE THREAD

**Issue by bline** [strapi/strapi#11490]
### Describe the bug

When adding a repeatable component that has a relation, the dropdown for the relation in the UI is cut off. A z-index issue?

### Steps to reproduce the behavior

1. Install beta10 or previous betas
2. Create a component with a relation to content that has more than one selection
3. Add the component to a single or multi content type
4. go to the content provider interface to select the relation

### Expected behavior

The dropdown menu should not be hidden by the accordion

### Screenshots

![strapi-relation-dropdown-broken](https://user-images.githubusercontent.com/296871/140578834-a3d41651-3a8f-4cc0-b877-3bcd5909a4bc.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: beta.10
- Database: mysql
- Operating system: ubuntu-20.04.3 LTS

**Comment by derrickmehaffy** [comment]
confrimed on beta.11
