### ISSUE TITLE
[BUG] [V4] - Administrator password reset does not send email

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#11506]
### Describe the bug

Once you have created your initial administrator, try resetting the password by entering the email you used while creating the administrator (in my case this was a gmail address) and you'll receive following error:

```
[2021-11-08 16:21:38.513] error: SMTP code:550 msg:550-5.7.26 Unauthenticated email from strapi.io is not accepted due to domain's
550-5.7.26 DMARC policy. Please contact the administrator of strapi.io domain
550-5.7.26 if this was a legitimate mail. Please visit
550-5.7.26  https://support.google.com/mail/answer/2451690 to learn about the
550 5.7.26 DMARC initiative. c3si32164521wmb.151 - gsmtp

Error: SMTP code:550 msg:550-5.7.26 Unauthenticated email from strapi.io is not accepted due to domain's
550-5.7.26 DMARC policy. Please contact the administrator of strapi.io domain
550-5.7.26 if this was a legitimate mail. Please visit
550-5.7.26  https://support.google.com/mail/answer/2451690 to learn about the
550 5.7.26 DMARC initiative. c3si32164521wmb.151 - gsmtp

    at response (/Users/fabio_nettis/github/bucan-labs/beta/node_modules/sendmail/sendmail.js:217:24)
    at onLine (/Users/fabio_nettis/github/bucan-labs/beta/node_modules/sendmail/sendmail.js:234:11)
    at Socket.<anonymous> (/Users/fabio_nettis/github/bucan-labs/beta/node_modules/sendmail/sendmail.js:141:11)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

### Steps to reproduce the behavior

1.  Create Administrator with a gmail address
2. Click on "Forgot your password?"
3. Enter your email & click "Send email"

### Expected behavior

Obviously the mail should be sent and not produce given SMTP error. Also no error is shown when this happens, so the user isn't informed about the failure and simply does not receive an email.

### Screenshots

N/A

### Code snippets

N/A

### System

- Node.js version: 16.9.0
- NPM version: 7.21.1
- Strapi version: beta
- Database: sqlite
- Operating system: MacOS

**Comment by LucaNerlich** [comment]
You need to set a sender/from adress in the email settings in strapi. The domain needs to match your strapi domain.

**Comment by fabio-nettis** [comment]
> You need to set a sender/from adress in the email settings in strapi. The domain needs to match your strapi domain. 
> 
> This is not a bug. 
> 
> Also, which mail provider did you configure?

@LucaNerlich No configuration was made at all. Just the out of the Box configuration. Altough this might not be a bug then;

I think it would be important to **handle this scenario differently** in the front end, as well as the console since it does not give enough information to the developer or front end user.

**Comment by LucaNerlich** [comment]
Im not aware if strapi is even able to send proper mails ootb. Which "free" provider would it use?

Although the "test email" button does something. 

However, for prod, you would always want/need to configure one of the built in mail providers, such as mailgun or sendgrid.

**Comment by derrickmehaffy** [comment]
> Unauthenticated email from strapi.io is not accepted

You still have the `@strapi.io` email set in the templates, this needs to be changed. Under settings look at the email templates section, there are 2 that need to have their emails changed.

Marking as closed as this isn't a bug but a configuration problem. (If you need more help see our Discord: https://discord.strapi.io or our Forum: https://forum.strapi.io)

**Comment by derrickmehaffy** [comment]
Also welcome back @fabio-nettis been a while :)

**Comment by fabio-nettis** [comment]
> Also welcome back @fabio-nettis been a while :)

@derrickmehaffy Indeed it has. Good to be back. I'm most certainly going to build our latest product on top of V4; so I'm pretty hyped up about the update.
