### ISSUE TITLE
Can we override Strapi admin default login with custom Oauth2 provider?

### ISSUE THREAD

**Issue by PradeepMurani** [strapi/strapi#11511]
Hi Folks,

I want to override Strapi admin default login with a custom Oauth2 provider.
Is it possible with Strapi?
Your suggestion would be welcome !!

Below is strapi system information:
    - Strapi Version: 3.6.5
    - Operating System: Ubuntu 20
    - Database: Postgres
    - Node Version: node 14
    - NPM Version: 6.14

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
