### ISSUE TITLE
In type orders I make a request for all orders and in each order there should be an array and there is a count object

### ISSUE THREAD

**Issue by MRXOneX** [strapi/strapi#11547]
I have the Orders type, and the history_records type, I made in order relation has many history_record. Now, when requesting all orders from content-manager/collection-types/application::order.order, I get orders in response in which there is a history_records property, but there is an object with count, and not an array of history_record itself
![image](https://user-images.githubusercontent.com/74454444/141293089-404b4ce6-f836-4735-afe4-ef9dd105319b.png)
![image](https://user-images.githubusercontent.com/74454444/141293249-5773f88a-ddca-44c1-80fc-af81345bcffc.png)
![image](https://user-images.githubusercontent.com/74454444/141293335-484eca8c-658b-4556-a815-b36bab5b8d8c.png)

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
