### ISSUE TITLE
API content manager configuration can be accessed by non-admin

### ISSUE THREAD

**Issue by diakbar** [strapi/strapi#11548]
### Describe the bug

API content-manager is accessible by non admin.
List API:
- /content-manager/content-types/application::APP_ID/configuration

### Steps to reproduce the behavior

1. Login with Editor Role
2. Grab JWT token of Editor Role
3. Hit HTTP GET API content manager with JWT Token using Postman
4. API content manager is readable from non-admin user / editor

### Expected behavior

Shouldn't API content management not be accessible by user with editor role?

### Screenshots
**Request using Token Admin**
![image](https://user-images.githubusercontent.com/1845987/141298447-167dc6b4-5ce1-4140-8ae9-d5daa9396c0d.png)
Token Admin: *.s7E3OWIRp8z4mxRJ89X6_iX54a8W-7KgWuPSaddfly8

**Request using Token Editor**
Token Editor: *9OsoXWKz59LAe4wftPJK6oy_enKh4Y4M0w9IZ_MM-zs
![image](https://user-images.githubusercontent.com/1845987/141298334-6fc1464d-834b-4bea-bfdc-98c9c5a5be86.png)

### Code snippets

No code, this is plugin from strapi

### System

- Node.js version: v14.15.5
- NPM version: 6.14.11
- Strapi version: 3.6.8 Enterprise Edition
- Database: Mongo DB
- Operating system: RHEL 7.5

### Additional context

We are doing pentest on Strapi Platform for our next CMS Platform.

**Comment by derrickmehaffy** [comment]
No sure where I am seeing the problem here? It is the "config" to show how to render the list and edit views of the content manager. Any admin role that ends up with access to a content type needs those endpoints to know how to render.

If the issue is that a role has access to a content-types CTM config but not the content-type itself, I'm missing how there is a problem here?

**Comment by diakbar** [comment]
@derrickmehaffy yes for admin it needs, but for editor role, on UI part, menu CTM config is not appeared. Somehow using editor token we can access CTM config by sending API request via Postman. We already test also update config is not possible using postman + editor token.

Issue/Problem is non-admin role, editor role, can get response CTM API that is on his UI page does not appeared, which mark as OWASP Broken Access Control.
CTM API is /content-manager/content-types/application::APP_ID/configuration. 
Is this by default a normal behavior? Can we restrict this CTM API cannot be accessed/read by on non-super-admin ?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy yes for admin it needs, but for editor role, on UI part, menu CTM config is not appeared. Somehow using editor token we can access CTM config by sending API request via Postman. We already test also update config is not possible using postman + editor token.
> 
> Issue/Problem is non-admin role, editor role, can get response CTM API that is on his UI page does not appeared, which mark as OWASP Broken Access Control. CTM API is /content-manager/content-types/application::APP_ID/configuration. Is this by default a normal behavior? Can we restrict this CTM API cannot be accessed/read by on non-super-admin ?

Simply reading the config is not a problem, no you can't restrict this as it's needed to render the view. There is nothing private in that config, so long as you can't write to it (without permissions of course). It's just a UI layout config.

I'm marking as closed as there is nothing about this that is "Broken Access Control"

**Comment by diakbar** [comment]
Yes, sorry my bad, after read again, both user marked as Admin user that can access dashboard, so this is not a Broken Access Control as I mention before.
