### ISSUE TITLE
Mongodb sorting and pagination error 

### ISSUE THREAD

**Issue by ChiKaLiO** [strapi/strapi#11540]
## Bug report
So, the error started occurring after migrating +26000 docs to our database, sorting or skipping 50+ record crashes the server with timeout error for ex:
`/articles?category.i18name=News&_locale=en&_sort=Date:DESC`
or 
`/articles?category.i18name=News&_locale=en&_start=50`
 or both together same error
`http://localhost:3001/articles?category.i18name=News&_locale=en&_start=0&_limit=5&_sort=Date:DESC`

although everything is smooth in the admin area !!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
