### ISSUE TITLE
Doc request: Adding properties to a relationship

### ISSUE THREAD

**Issue by Joshfindit** [strapi/strapi#1156]
**Informations**
- **Node.js version**:  `v9.9.0`
- **npm version**:  `5.6.0`
- **Strapi version**:  `3.0.0-alpha.11.3`
- **Database**: `mongo`
- **Operating system**: `Linux 488281af74ed 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 Linux` (via the Docker image)

**What is the current behavior?**
Cannot find documentation for storing information *about* a relationship

**Steps to reproduce the problem**
1. Create a Content Type
2. Add a Relation to the content type
3. Be unsure how to add properties

**What is the expected behavior?**
A straightforward way in the UI or in the documentation for how to add properties

**Suggested solutions**
Add information to the documentation about relations

Example:
- `employee` has many `job_title`s
- For each `employee`'s `job_title`, there is a `begin_date` and `end_date`

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Thank you @raulriera for the help.

**Comment by jorisw** [comment]
This issue was wrongfully closed - the OP requested how to add properties to the _relationship_. See OP's example. In the example, the relationship employee - job title relationship exists only for some time, which is described using _relationship properties_ `begin_date`_ and `end_date`.

**Comment by derrickmehaffy** [comment]
@jorisw you add them to one of the models that is part of the relationship. We treat relationships as you would joins in a relational databases so there is no method to add additional data, it's just a link between records.

**Comment by jorisw** [comment]
I understand. So the answer to the question is that what OP wants to do isn't possible at this time. Because adding a `start_time` the the `job_title` wouldn't describe what OP is trying to model.

**Comment by antoineguiral** [comment]
@jorisw I guess we can add a model `employee_job_title` with the data then manage relationship from employee_job_title to employee and job_title? For sure it could be a configuration when many to many relationship is set.
