### ISSUE TITLE
Testing Env Config is not used in Jest Unit Tests as described in the documentation

### ISSUE THREAD

**Issue by JonasJW** [strapi/strapi#11566]
### Describe the bug

The test environment config is not used in Jest tests. When I add `console.log(this.config.get('database.connections'));` inside the load function of Strapi, I can see that it uses the the default database config while the NODE_ENV is `test`.

### Steps to reproduce the behavior

1. create a new strapi project (With other database then Sqlite to see difference to test config)
2. follow [unit test docs](https://strapi.io/documentation/developer-docs/latest/guides/unit-testing.html#testing-basic-endpoint-controller) to setup test config and unit tests
3. start unit test and check used config

### Expected behavior

Should use database config provided in `./config/env/test/database.json` 

### Code snippets

My Config:

`./config/database.js`

    module.exports = ({ env }) => ({
      defaultConnection: 'default',
      connections: {
        default: {
          connector: 'bookshelf',
          settings: {
            client: 'postgres',
            host: env('DATABASE_HOST', 'postgres'),
            port: env.int('DATABASE_PORT', 5432),
            database: env('DATABASE_NAME', 'strapi_dev'),
            username: env('DATABASE_USERNAME', 'strapi'),
            password: env('DATABASE_PASSWORD', 'strapi'),
            ssl: env.bool('DATABASE_SSL', false),
          },
          options: {
            autoMigration: env.bool('AUTO_MIGRATION', false)
          }
        },
      },
    });

`./config/env/test/database.json`

    {
        "defaultConnection": "default",
        "connections": {
            "default": {
                "connector": "bookshelf",
                "settings": {
                    "client": "sqlite",
                    "filename": ".tmp/test.db"
                },
                "options": {
                    "useNullAsDefault": true,
                    "pool": {
                        "min": 0,
                        "max": 1
                    }
                }
            }
        }
    }

### System

- Node.js version: v14.15.0
- NPM version: 6.14.8
- Strapi version: "3.6.8"
- Database: see config above
- Operating system: MacOS Big Sur 11.4

**Comment by kasonde** [comment]
Unable to reproduce this after following the guide as was in the tutorial. Please share more information about what has happened that caused you to conclude that this is as an issue. What is/isn't happening for you? Secondly, please filling in the Operating System section of your issue.

**Comment by JonasJW** [comment]
> Unable to reproduce this after following the guide as was in the tutorial. Please share more information about what has happened that caused you to conclude that this is as an issue. What is/isn't happening for you? Secondly, please filling in the Operating System section of your issue.

Are you sure? I just tried again with a completely new project and the behavior is the same. 

Did you change the `./config/database.js` config? If not, please try with my config above.  It's important, that  `./config/database.js` and `./config/env/test/database.json` are different configs so one can see, that the `./config/database.js` config is actually used when running `npm test`

**Comment by derrickmehaffy** [comment]
> > Unable to reproduce this after following the guide as was in the tutorial. Please share more information about what has happened that caused you to conclude that this is as an issue. What is/isn't happening for you? Secondly, please filling in the Operating System section of your issue.
> 
> @kasonde Are you sure? I just tried again with a completely new project and the behavior is the same.
> 
> Did you change the `./config/database.js` config? If not, please try with my config above. It's important, that `./config/database.js` and `./config/env/test/database.json` are different configs so one can see that the `./config/database.js` config is actually used when running `npm test` instead of `./config/env/test/database.json`

Your path is wrong (or you gave the file the wrong extension) it should be `./config/env/test/database.js` not `.json`

I also wasn't able to reproduce this and am going to set it as closed unless additional information is provided that can reproduce the issue.

**Comment by JonasJW** [comment]
@derrickmehaffy @kasonde I have created [this repo](https://github.com/JonasJW/strapi-unit-test-min) for a reproducible project of the issue. We could reproduce the error on different devices so we would appreciate it if you could take another look at it. Notice the `config/database.js` config, we highlighted what configs are working. As mentioned, we expect `config/database.js` to have no influence on the tests as it should be defined in `config/env/test/database.json`.

> Your path is wrong (or you gave the file the wrong extension) it should be ./config/env/test/database.js not .json

The issue happens with both json an js files and the docs also use .json config files, so this doesn't seem to be the issue

**Comment by derrickmehaffy** [comment]
When using environments, the `./config/env/*/database.js` is **merged** with `./config/data ase.js`. So the core file will always come into play but you can use the env config to overwrite keys when it's merged at runtime.
