### ISSUE TITLE
I can override function bootstrap of the module strap-amin?

### ISSUE THREAD

**Issue by AnechaS** [strapi/strapi#11561]
### System

- Node.js version: v14.17.1
- NPM version: 6.14.13
- Strapi version: 3.6.8
- Database: mysql
- Operating system:

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
