### ISSUE TITLE
[V4] No data returning from dynamiczone & relation type fields

### ISSUE THREAD

**Issue by digitaledge-git** [strapi/strapi#11560]
### Describe the bug

The REST Api is not returning any data for fields with type dynamiczone or relation.

### Steps to reproduce the behavior

1. save data that includes dynamiczone and relation fields
2. call the rest api and review the returned data

### Expected behavior

All (non-hidden) fields should be returned from the api

### Code snippets

My article schema with relation and dynamiczone fields:

`{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Articles",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "article_content": {
      "type": "dynamiczone",
      "components": [
        "image.image",
        "rich-text.rich-text",
        "gallery.gallery"
      ],
      "required": false
    },
    "article_category": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::article-category.article-category",
      "inversedBy": "articles"
    },
    "slug": {
      "type": "string"
    }
  }
}
`

The related category schema:

`{
  "kind": "collectionType",
  "collectionName": "article_categories",
  "info": {
    "singularName": "article-category",
    "pluralName": "article-categories",
    "displayName": "Article_Categories",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "slug": {
      "type": "string",
      "required": true,
      "unique": true,
      "maxLength": 80
    },
    "articles": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::article.article",
      "mappedBy": "article_category"
    }
  }
}
`

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 4.0.0-beta.12
- Database: PostgreSql
- Operating system: macOS Big Sur 11.5.2

**Comment by derrickmehaffy** [comment]
This is intended: https://docs-next.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population

We don't populate anything by default.
