### ISSUE TITLE
[v4] Pluralize the word asset in the Media Library after selecting more than 1 asset

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#11568]
### Describe the bug

The button to begin the upload in the Media library doesn't pluralize the word asset like the asset counter above the assets themselves. 
![image](https://user-images.githubusercontent.com/13610895/141797373-59e22867-5201-412f-a312-5ef31536dfd0.png)

### Steps to reproduce the behavior

1. Go to Media Library
2. Select two assets

### Expected behavior

The button should say assets instead. 
![image](https://user-images.githubusercontent.com/13610895/141797539-c3193584-8054-47aa-bf5f-7ab5f9a6996b.png)

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 4-beta.12
- Database: SQLite
- Operating system: Linux Mint

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/11570

**Comment by yanniskadiri** [comment]
Thanks for highlighting this, it has been solved now :)
