### ISSUE TITLE
hotreload does not work if path to strapi project contains "admin"

### ISSUE THREAD

**Issue by bschelling** [strapi/strapi#11586]
### Describe the bug
hot reload does not work if the pwd to strapi contains admin

### Steps to reproduce the behavior
start strapi from .eg
/users/admin/strapiproject/

run  'npm run develop'
change a file in the project e.g /users/admin/strapiproject/api/test/test.js

### Expected behavior

strapi should reload on file change

### Additional context
Problem is in ignored files in 
/node_modules/strapi/lib/commands/develop.js - if a path contains "admin" it is ignored

```
 const watcher = chokidar.watch(dir, {
    ignoreInitial: true,
    usePolling: polling,
    ignored: [
      /(^|[/\\])\../, // dot files
      /tmp/,
      '**/admin',
      '**/admin/**',
```

**Comment by kasonde** [comment]
Confirmed on both Strapi v3 and v4. Editing the file you referenced from `**/admin/**` to `admin/**` and `admin/` seems to work. I've opened a PR as it's a simple fix and I'll await approval by our team.

**Comment by derrickmehaffy** [comment]
Can't reproduce on Linux but there is a PR submitted to fix
