### ISSUE TITLE
Changing relation cause server error

### ISSUE THREAD

**Issue by Sakkhor909** [strapi/strapi#11595]
### Describe the bug

I have two collections: products and categories. I have edited the products collection and added a relation with categories field as "products has and belongs to one Category". But when I change this relation with "products has one Category", the server goes down without a warning.

 ### Screenshots

![error1](https://user-images.githubusercontent.com/72855902/142000589-8e4d9d6b-392f-483b-97ed-a6f6bb50f6ef.png)

### System

- Node.js version:  v14.0.0
- NPM version: 6.14.4
- Strapi version: 3.6.8
- Database: mysql
- Operating system: linux (ubuntu)

**Comment by derrickmehaffy** [comment]
Please provide more reproductive steps, information provided is not enough to reproduce the issue.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
