### ISSUE TITLE
Logo not changed properly

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1159]
**Informations**
- **Node.js version**: v10.1.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: LINUX

**What is the current behavior?**
Top-Left Logo not change after update.

**Steps to reproduce the problem**
I change file in below path:
`admin/admin/src/assets/images`
based on this docs: https://strapi.io/documentation/advanced/customize-admin.html#logo

**What is the expected behavior?**
I also try to stop/start my server and test with another browser but still it's show previous Strapi logo rather than my new logo.

**Suggested solutions**
**I suggest to add this as an option in site configuration page**, then we can update admin panel logo from with site panel. :wink: 

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@mnlbox did you rebuild the adminUI as stated directly below that? 
![image](https://user-images.githubusercontent.com/8593673/39857169-39462b9e-53e7-11e8-9776-d44b8eb26b9c.png)

**Comment by mnlbox** [comment]
No I didn't. I run that now and got below error on my terminal:
```
> strapi-admin@3.0.0-alpha.12.1.3 prebuild /home/username/Desktop/myApps/appname/admin
> APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '/home/username/Desktop/myApps/appname/admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.1.3 prebuild: `APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.1.3 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2018-05-10T08_16_02_680Z-debug.log

```

**Comment by derrickmehaffy** [comment]
Please see the related bug request: https://github.com/strapi/strapi/issues/1116

These files cannot be changed directly in the admin, the reason for the documentation you referenced is you are modifying the source of the adminUI, once modifications are done you need to rebuild it which places the rebuilt adminUI in the `build` folder which strapi uses on the default :1337 port.

**Comment by derrickmehaffy** [comment]
@lauriejim this is a duplicate issue the one noted above.

**Comment by derrickmehaffy** [comment]
@mnlbox note that with any future strapi updates that make modifications to the adminUI, strapi will replace this build folder so you will need to remodify during each update right now in order to have these changes persist during version changes.

**Comment by derrickmehaffy** [comment]
Other related issues: 
https://github.com/strapi/strapi/issues/1113
https://github.com/strapi/strapi/issues/1036

**Comment by mnlbox** [comment]
So based on #1116 I need `npm run setup`?
@derrickmehaffy so I think it's better to change this issue from bug report to feature request :wink: 
I think it's better to have a graphical UI form for this kind on general customization.
for example anyone need change dashboard logo and now it's a little complicate.

**Comment by derrickmehaffy** [comment]
The problem is how the application is written. The way it is setup is to allow people to build their own plugins and modify the user interface in order to rebuild it and redeploy. This is extremely common in nodejs applications like strapi. Your welcome to submit the feature request, but if this is something you feel should be done, I recommend you try and modify it yourself and submit a Pull request :smile:

**Comment by jtan4nih** [comment]
You need to change the logo for the user's permission plugin at ./plugins/users-permissions/admin/src/assets/images/logo_strapi.png. And rebuild. Good luck!
