### ISSUE TITLE
Sensitive configuration files are versioned

### ISSUE THREAD

**Issue by abelsoares** [strapi/strapi#116]
Strapi has environment configurations at `config/environments/env_name/` which are versioned.  
The problem with versioning this configurations is that anyone contributing to a strapi app can change a configuration file and push it to the repo, which can lead other teammates having their app broken and/or having sensitive data versioned. Also, having config files like `database.json` always showing in git as modified is annoying, specially if there's no reason one want to commit this file. 

An easy solution is to one add, e.g. `database.json` to `.gitignore` and provide a `database.json.dist` template versioned, but i think this should be handled by strapi generator.

I see no more config files other than `database` that are an issue right now, but if so, i suggest merging this kind of `don't want to version this` config files to be merged in a single file template.

Maybe there's other solutions to this kind of issue, WDYT?

**Comment by pierreburgy** [comment]
Good idea @abelsoares.

Here are some other options: 
 - adding a `local.json` file in the `/config` folder (this file would be added to the default .gitignore)
 - using templated JSON in order to use environment variables (eg. `{"port": "{{= process.env.PORT }}"}`)

@everyone: feel free to give ideas and suggestions.

**Comment by Aurelsicoko** [comment]
@abelsoares & @pierreburgy: What seems the best solution for you? We could ignore the `database.json` by adding it into the `.gitignore` file at this time. What do you think about that?
