### ISSUE TITLE
[V4] Enum that starts with an `Integer` not accepted

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11608]
### Describe the bug

Adding an enum field value that starts with an integer doesn't match regex pattern. I bet ya I'm not the only one and this is not the only use-case for when starting an enum with a number (or having a number as a value for that matter) would be useful.

### Steps to reproduce the behavior

1. Create a new `Enum` field and add a value that start with a digit.
2. See error

### Screenshots
<img width="249" alt="Screen Shot 2021-11-17 at 4 17 23 PM" src="https://user-images.githubusercontent.com/11737572/142217318-d4ece89d-c4bb-4b34-8d81-e687d7efe44d.png">

### System

- Strapi version:  v4-beta.13

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7904
