### ISSUE TITLE
Erorr creating component in beta.13

### ISSUE THREAD

**Issue by malgamves** [strapi/strapi#11604]
### Describe the bug

I got an error in admin when i tried to create a component named '2' with enum and text fields

I changed component name and renamed it 'three' same error.

I had previously created a component called '1' successfully

Side note i noticed when you create a component, the icon you pick disappears from the list of available ones to pick from when you want to create another one. When creating the component in the screenshot failed and i restarted the server the icon i picked disappeared even though the component wasn't successfully created.

### Steps to reproduce the behavior

1. Go to 'Admin panel'
2. Click on 'Create Component'
3. Name component and add fields to components, save.
3. Add second component to same component group.

### Expected behavior

I shouldn't get an error when I create a new component to the component group

### Screenshots

![image (24)](https://user-images.githubusercontent.com/25641936/142185453-00054057-9b6b-4058-a7ea-6f7a0a456e8d.png)

### Error Stack

```
Object { err: Response }

err: Response { type: "basic", url: "http://localhost:1337/content-type-builder/components", redirected: false, … }

body: ReadableStream { locked: true }

locked: true

<prototype>: ReadableStream.prototype { cancel: cancel(), getReader: getReader(), tee: tee(), … }

bodyUsed: true

headers: Headers {  }

<prototype>: HeadersPrototype { append: append(), delete: delete(), get: get(), … }

ok: false

payload: Object { error: {…} }

error: Object { name: "ValidationError", message: "component field has unspecified keys: allowedTypes, type, multiple, name", details: {…} }

details: Object { errors: (1) […] }

message: "component field has unspecified keys: allowedTypes, type, multiple, name"

name: "ValidationError"

<prototype>: Object { … }

<prototype>: Object { … }

redirected: false

status: 400

statusText: "Bad Request"

type: "basic"

url: "http://localhost:1337/content-type-builder/components"

<prototype>: ResponsePrototype { clone: clone(), arrayBuffer: arrayBuffer(), blob: blob(), … }

<prototype>: Object { … }

__defineGetter__: function __defineGetter__()

__defineSetter__: function __defineSetter__()

__lookupGetter__: function __lookupGetter__()

__lookupSetter__: function __lookupSetter__()

__proto__: 

constructor: function Object()

hasOwnProperty: function hasOwnProperty()

isPrototypeOf: function isPrototypeOf()

propertyIsEnumerable: function propertyIsEnumerable()

toLocaleString: function toLocaleString()

toString: function toString()

valueOf: function valueOf()

<get __proto__()>: function __proto__()

<set __proto__()>: function __proto__()

length: 1

name: "set __proto__"

<prototype>: function ()
```

### System

- Node.js version: 14.15.0
- NPM version: 7.24.1
- Strapi version: 4.0.0-beta.13
- Database: sqlite
- Operating system: Windows 10

### Additional context

Nothing else

**Comment by soupette** [comment]
> Side note i noticed when you create a component, the icon you pick disappears from the list of available ones to pick from when you want to create another one.

It is an intended behaviour the icon should be unique (only when creating a component in the admin panel).
