### ISSUE TITLE
New Plugin development throw Errors at start

### ISSUE THREAD

**Issue by raza2022** [strapi/strapi#1161]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: mongodb 3.0.6
- **Operating system**: windows 10

**What is the current behavior?**

I am getting this error of cross-env within node_modules deeply

![image](https://user-images.githubusercontent.com/5462788/39863788-13447d5e-5461-11e8-9206-903d6bfb11cd.png)

**Steps to reproduce the problem**

Just follow the plugin development instructions for example
srapi new pakistan --dev
```
$ cd pakistan && strapi generate:plugin my-plugin
$ cd pakistan/plugins/my-plugin && npm link strapi-helper-plugin
$ cd pakistan/plugins/analytics && npm link strapi-helper-plugin
$ cd pakistan/admin && npm start 
```

**What is the expected behavior?**

should working as mentioned within plugin development instructions

**Suggested solutions**

I know if deeply depending within node_modules within strapi-helpers-plugin so my suggestion to keep top level dependencies (which used in scripts for `npm run npm build` etc.) within package.json of root project  

---
I know a very slimier issue already posted. but I believe it's just related to right command running within wrong folder mine is totally different 

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by raza2022** [comment]
@derrickmehaffy yes I know that usual for fast paced development project :+1: 
just one more thing I reproduced the same for linux machine and result exactly same might it help to diagnose the real problem :1st_place_medal:

**Comment by lauriejim** [comment]
I think the plugin generator is not up to date.

If you want to create you own plugin. I think actually to copy and paste `strapi-plugin-email` and custom it. It's the more simple of our plugins.

**Comment by raza2022** [comment]
@lauriejim 

![image](https://user-images.githubusercontent.com/5462788/39919566-733949ac-552d-11e8-972b-9966fee3de18.png)

that the actual case :) actually I want to update content-type-builder plugin to support `json` types as you can see above. when I event failed to event make build for it then I go with new plugin development to just clone content-type-builder with my customization to support `json` type.
let me know if you have any idea of easy to to achieve it many thanks for

**Comment by derrickmehaffy** [comment]
@raza2022 it looks like your trying to dev on windows correct? The strapi team have stated before there are known issues, if you absolutely have no other option, please see the end of this issue: https://github.com/strapi/strapi/issues/680

You will need to setup the WSL on windows (I recommend the Ubuntu one) and develop through bash.

Alternatively you could setup a linux virtual machine in something like virtual box or hyper-v

**Comment by raza2022** [comment]
ok after switching to Linux I made working that comment will help a lot :+1: 
https://github.com/strapi/strapi/issues/680#issuecomment-381018295

**Comment by derrickmehaffy** [comment]
@raza2022 glad to know it helped 👍 I know the strapi team are working hard and will likely focus on fixing the development on windows in the future. 😄

**Comment by thanhdevapp** [comment]
Please fix on windows

**Comment by derrickmehaffy** [comment]
@thanhdevapp The Strapi team is working on it, but it probably won't happen in the near future. I think their goal was by the end of summer. For now you will need to use WSL or Linux VM
