### ISSUE TITLE
Duplicate username returns email already taken error

### ISSUE THREAD

**Issue by blheson** [strapi/strapi#11615]
### **Description**
When users submit a username that has already been registered, the error returned is "Email already taken" even if the email has never been registered. 
### **Steps to reproduce the behavior**
1. Send a post request to http://localhost:1337/auth/local/register with the below payload
{"username":"testUsername","email":"test1@gmail.com","password":"password"}. 

2. After getting a successful response, send another post request to  http://localhost:1337/auth/local/register with a different payload but retain the previous username. For example, {"username":"testUsername","email":"test2@gmail.com","password":"newpassword"}.
3. You will get "Email already taken" error.

### **Expected behavior**
The error message should be "Username already taken" or something related. 

### **Screenshot**
First submission with testUsername was successful
![image](https://user-images.githubusercontent.com/48820972/142272120-cdd7c804-44ce-417d-bd5a-ea0455b4880f.png)

Second submission with testUsername gave the error 
![image](https://user-images.githubusercontent.com/48820972/142272317-7a937005-30ba-4d77-9085-840a998bd972.png)

### **System**
Node.js version: 16.6.2
NPM version: 7.20.3
Strapi version: 3.6.8
Database: MongoDB
Operating system: Windows

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by blheson** [comment]
> Hello, please follow the issue template.
> 
> A proper issue submission lets us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue.
> 
> Thank you.

I just did. Thank you.

**Comment by kasonde** [comment]
@blheson thanks for that. Confirmed on v3

**Comment by derrickmehaffy** [comment]
Won't fix, v3 is maintenance only now for security issues: https://github.com/strapi/strapi/issues/11726

Can't reproduce in v4
