### ISSUE TITLE
v4 issue where oneToMany relationship is not populated

### ISSUE THREAD

**Issue by Kinbaum** [strapi/strapi#11610]
### Describe the bug

I have a collection `configurations` that contains a `features` component. This component is comprised of a `oneToMany` relationship with a collection called `tags`. 

When I access `/api/configurations?populate=features.tags` I am able to see my data without any issues.
Here is the expected output:

```json
{
    "data": [
        {
            "id": 1,
            "attributes": {
                "createdAt": "2021-11-17T14:36:41.936Z",
                "updatedAt": "2021-11-17T14:54:03.720Z",
                "publishedAt": "2021-11-17T14:37:37.094Z",
                "locale": "en",
                "features": {
                    "id": 1,
                    "tags": {
                        "data": [
                            {
                                "id": 1,
                                "attributes": {
                                    "label": "My Tag",
                                    "value": "my-tag",
                                    "createdAt": "2021-11-17T14:35:47.657Z",
                                    "updatedAt": "2021-11-17T14:35:47.657Z",
                                    "publishedAt": "2021-11-17T14:35:47.657Z"
                                }
                            }
                        ]
                    }
                }
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 1
        }
    }
}
```

### The problem

I need to be able to reference this information within another collection `other-collection`. So I decided to implement my own `find` function within the `other-collection`'s controller. Here is a snippet of the controller:

```js
module.exports = {
    async find(ctx, next) {
        const { data } = await strapi.controller('api::configuration.configuration').find({
            query: {
                populate: 'features.tags'
            }
        });

        console.log(data)
    }
}
```

When I visit `/api/other-collection`, this find function is called. When I log the data I get back from the `configuration` controller, I am unable to see the `features.tags`, even though I explicitly added it to populate parameter. 
Here is the output I am getting:

```json
[
    {
        "id": 1,
        "attributes": {
            "createdAt": "2021-11-17T14:36:41.936Z",
            "updatedAt": "2021-11-17T14:54:03.720Z",
            "publishedAt": "2021-11-17T14:37:37.094Z",
            "locale": "en",
            "features": {
                "id": 1
            }
        }
    }
]
```

### Expected behavior

I would expect the if I am calling `strapi.controller` and pass in the desired API, that the information I get back would function identically to an OOTB controller, provided that all parameters passed are identical.

### System

- Node.js version: 16.5.0
- NPM version: 7.20.3
- Strapi version: 4.0.0-beta.13
- Database: Tested in MySQL and SQLite3
- Operating system: MacOS

**Comment by Kinbaum** [comment]
Update: I was able to make this work by swapping out `strapi.controller` with `strapi.entityService.findMany`

**Comment by derrickmehaffy** [comment]
This is intended, we don't populate any relations, components, or dynamic zones by default in the v4. We now have population options during the request:

https://docs-next.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population

**Comment by Kinbaum** [comment]
Hey @derrickmehaffy yes I understand that. If you look at my code snippet, when using the controller, I do pass the `populate` option. The data that is returned ignores the `features.tags` population. 

I was only able to get this working with the `entityService`

**Comment by derrickmehaffy** [comment]
It doesn't support the dot syntax that v3 did in various other ways. You have to build an object structure and stringify that using qs.

(If you aren't sure what I mean I can give an example)

**Comment by Kinbaum** [comment]
I think it would be helpful to have an example of both the controller option, and the entityService option (which seems to support the dot syntax)

**Comment by Kinbaum** [comment]
@derrickmehaffy Could you provide those examples please, thanks.

**Comment by derrickmehaffy** [comment]
Try this: `populate[features][tags]=true`

This is the qs I used to generate it:

```js
const qs = require('qs');

const query = qs.stringify({
  populate: {
    features: {
      tags: true
    }
  }
},
{ 
  encodeValuesOnly: true 
})

console.log(query)
```

**Comment by Kinbaum** [comment]
Can you provide the example in this context:

```js
const entries = await strapi.controller('api::config.config').find({
    // what is the proper syntax here?
});
```

The entity service works if i use this:

```js
const entries = await strapi.entityService.findMany('api::config.config', {
    populate: [ 'clientInfo', 'features.tags', 'products' ],
});
```

**Comment by derrickmehaffy** [comment]
just pass the same object I have in the query to both. populate is a Strapi term but also converted to knex

**Comment by Kinbaum** [comment]
I've tried that and it's not populating. This is the response I get:

```json
{
    "data": [
        {
            "id": 1,
            "attributes": {
                "createdAt": "2021-11-17T14:36:41.936Z",
                "updatedAt": "2021-11-18T14:38:13.726Z",
                "publishedAt": "2021-11-17T14:37:37.094Z",
                "locale": "en"
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 1
        }
    }
}
```

**Comment by derrickmehaffy** [comment]
Can you give me your schema.json files for models/compos or can you push your test code into a git repo.

**Comment by Kinbaum** [comment]
I'll create a reproduction repo and send it

**Comment by Kinbaum** [comment]
Here are the schemas. After these are created, just create a random collection so that you can create a custom controller. In that controller you can try the code above and see that it does not work.

<details>
    <summary>features component</summary>

```json
{
  "collectionName": "components_config_features",
  "info": {
    "displayName": "Features",
    "icon": "cogs",
    "description": ""
  },
  "options": {},
  "attributes": {
    "tags": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::tag.tag"
    }
  }
}
```
</details>

<details>
    <summary>tags collection</summary>

```json
{
    "kind": "collectionType",
    "collectionName": "tags",
    "info": {
        "singularName": "tag",
        "pluralName": "tags",
        "displayName": "Tag"
    },
    "options": {
        "draftAndPublish": true
    },
    "pluginOptions": {},
    "attributes": {
        "label": {
            "type": "string",
            "required": true
        },
        "value": {
            "type": "string",
            "required": true
        }
    }
}
```
</details>

<details>
    <summary>config collection</summary>

```json
{
    "kind": "collectionType",
    "collectionName": "configs",
    "info": {
        "singularName": "config",
        "pluralName": "configs",
        "displayName": "Config",
        "description": ""
    },
    "options": {
        "draftAndPublish": true
    },
    "pluginOptions": {
        "i18n": {
            "localized": true
        }
    },
    "attributes": {
        "name": {
            "type": "string",
            "private": true,
            "required": true
        },
        "features": {
            "type": "component",
            "repeatable": false,
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "component": "config.features"
        }
    }
}
```
</details>

**Comment by derrickmehaffy** [comment]
I tested using the block I gave you above and it works fine. The way you are defining controllers isn't how it should be done in the future (especially since beta.14 since we completely changed how controllers, services, and routes work)

See: https://documentation-git-dev-v4-controllers-updates-strapijs.vercel.app/developer-docs/latest/development/backend-customization/controllers.html

You also shouldn't be calling controllers from other controllers
