### ISSUE TITLE
Auth provider always disabled on Windows

### ISSUE THREAD

**Issue by marcostephan** [strapi/strapi#1162]
**Informations**
- **Node.js version**: 9.7.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: Windows x64

**What is the current behavior?**
Provider authentication returns always 'provider is disabled'

**Steps to reproduce the problem**

- install strapi
- fill in provider settings (Tried google and Facebook)
- enter localhost:1337/connect/[Provider]/

**What is the expected behavior?**
Strapi should redirect the user to the provider's authentication page

**Suggested solutions**
Change line 145 of [plugins/user-permissions/controllers/Auth.js] from 
`const provider = ctx.request.url.split('/')[2];`
to
`const provider = ctx.request.url.split('\\')[2];`

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @marcostephan , thank you for reporting this issue. 
Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md and submit a PR with your issue if it's fix the bug.
