### ISSUE TITLE
Admin panel never loads

### ISSUE THREAD

**Issue by JDoGlass** [strapi/strapi#11634]
### Describe the bug

Admin panel infinitely loading after a change in config/env/development/server.js

### Steps to reproduce the behavior

1. Remove config/server.js, and replace with config/env/development/server.js
2. Modify the latter file to contain the following:
`module.exports = ({ env }) => ({`
`  host: env('HOST', '127.0.0.1'),`
`  port: env.int('PORT', 1337),`
`  url: 'http://localhost:1337/api',`
`  admin: {`
`    url: 'http://localhost:1337/panel-de-administrador',`
`  },`
`});`
3. Run `npm install`, `npm run build` and `npm start` at the project's root directory.
4. Visit http://localhost:1337/panel-de-administrador on a web browser in the local pc.
5. Wait infinitely for the admin panel login screen to load.

### Expected behavior
The admin panel login screen loads.

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Database: MongoDB 
- Operating system: Ubuntu 20.04.3 LTS

### Additional context

When visiting http://localhost:1337/api the result is a "Not found" message

In [an older issue](https://github.com/strapi/strapi/issues/2259), a similar problem was solved using the command `npm run setup`, but it seems this is no longer available in newer versions of Strapi.

As a side note, the following is the output after running the app and visiting both uris:
`[2021-11-18T16:30:46.040Z] debug GET /panel-de-administrador (18 ms) 200`
`[2021-11-18T16:30:46.120Z] debug GET /panel-de-administrador/runtime~main.b24032c8.js (13 ms) 200`
`[2021-11-18T16:30:46.121Z] debug GET /panel-de-administrador/main.e5bc311f.chunk.js (3 ms) 200`
`[2021-11-18T16:30:47.229Z] debug GET /api/admin/init (3 ms) 404`
`[2021-11-18T16:36:29.360Z] debug GET /api (3 ms) 404`
`[2021-11-18T16:36:29.455Z] debug GET /favicon.ico (1 ms) 200`

**Comment by derrickmehaffy** [comment]
You need to have a proxy layer like Nginx, HAProxy, Caddy, or anything similar to this to properly use sub-directory routing.

See: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment.html#optional-software-guides
