### ISSUE TITLE
[v4]Content Security Policy issue of plugin-upload in strapi-4.0.0-beta.13

### ISSUE THREAD

**Issue by boeto** [strapi/strapi#11637]
### Describe the bug

[v4]**Content Security Policy issue** of plugin-upload in strapi-4.0.0-beta.13

### Steps to reproduce the behavior

1. Install and change the upload provider to aws-s3

2. Upload an image and get the issue

### Expected behavior

Should be able to see the picture. The same setting runs correctly in v3.

### Screenshots

![screenshot](https://raw.githubusercontent.com/boeto/image/main/uploads/20211119144511-40f80f.jpg)

### Code snippets

```js
// ./config/plugins.js

module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          Bucket: env("AWS_BUCKET"),
        },
      },
    },
  },
});
```

### System

- Node.js version: v14.17.6
- YARN version: 1.22.17
- Strapi version: 4.0.0-beta.13
- Database: PostgreSQL 13
- Operating system: macOS 10.15

### Additional context

null

**Comment by grzegorzbialy** [comment]
@boeto The internal middleware config change is not documented but I found out you can change default CSP settings middleware in _config/middlewares.js_ like this:

```javascript
module.exports = ({ env }) => [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'script-src': ["'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'],
          'img-src': ["'self'", 'data:', 'cdn.jsdelivr.net', 'strapi.io', `${env('AWS_REGION')}.console.aws.amazon.com`],
        },
      }
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
];
```

**Comment by derrickmehaffy** [comment]
Provider examples will have an example config to show how to properly modify this. Closing as it's not a bug

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-broken-image-even-when-the-images-link-works-cloudinary/14143/4

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-override-csp/14157/2

**Comment by kevinvugts** [comment]
> ```js
> {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         directives: {
>           'script-src': ["'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'],
>           'img-src': ["'self'", 'data:', 'cdn.jsdelivr.net', 'strapi.io', `${env('AWS_BUCKET')}.s3.${env('AWS_REGION')}.amazonaws.com`],
>         },
>       }
>     },
>   },
> ```

Why is this still undocumented?...
Got us busy for hours until we found this github thread.

**Comment by ludovicraymond** [comment]
Doesn't work for me for video assets.

It's ok for image type.

```
'script-src': ["'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'],
 'img-src': ["'self'", 'blob:', 'data:', 'cdn.jsdelivr.net', 'strapi.io', `${env('AWS_BUCKET')}.s3.amazonaws.com`],
 'media-src': ["'self'", 'blob:', 'data:', 'cdn.jsdelivr.net', 'strapi.io', `${env('AWS_BUCKET')}.s3.amazonaws.com`],
```

any idea ?

**Comment by nsavinda** [comment]
![image](https://user-images.githubusercontent.com/84757521/155697588-5a3b8a26-f54c-442e-91f5-946d65ccdedd.png)
https://dev.to/kevinadhiguna/what-is-cors-how-to-configure-cors-in-strapi-461b

**Comment by lunaeidolon** [comment]
> @boeto The internal middleware config change is not documented but I found out you can change default CSP settings middleware in _config/middlewares.js_ like this:
> 
> ```js
> module.exports = ({ env }) => [
>   'strapi::errors',
>   {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         directives: {
>           'script-src': ["'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'],
>           'img-src': ["'self'", 'data:', 'cdn.jsdelivr.net', 'strapi.io', `${env('AWS_BUCKET')}.s3.${env('AWS_REGION')}.amazonaws.com`],
>         },
>       }
>     },
>   },
>   'strapi::cors',
>   'strapi::poweredBy',
>   'strapi::logger',
>   'strapi::query',
>   'strapi::body',
>   'strapi::favicon',
>   'strapi::public',
> ];
> ```

Please help! I followed the instruction but it's not work for me, after restart strapi develop server, the html  do not have csp meta tag

**Comment by didiamuri** [comment]
Here is the configuration that worked for me, I spent 12 hours without finding a solution.

By removing the AWS_REGION, everything worked like a charm.

`"@strapi/strapi": "4.1.0",`

`module.exports = ({ env }) => [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
          'media-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
`

**Comment by didiamuri** [comment]
Here is the configuration that worked for me, I spent 12 hours without finding a solution.

By removing the AWS_REGION, everything worked like a charm.

`"@strapi/strapi": "4.1.0"`

```
module.exports = ({ env }) => [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
          'media-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

**Comment by AvinashUtekar** [comment]
![image](https://user-images.githubusercontent.com/87367466/163465669-ee76b920-9460-4824-b929-c1b6a1e4b360.png)
![image](https://user-images.githubusercontent.com/87367466/163465695-242280ce-d260-4e53-994b-c3f76396c00f.png)

getting issue on image downloading

**Comment by derrickmehaffy** [comment]
> Here is the configuration that worked for me, I spent 12 hours without finding a solution.
> 
> By removing the AWS_REGION, everything worked like a charm.
> 
> `"@strapi/strapi": "4.1.0"`
> 
> ```
> module.exports = ({ env }) => [
>   'strapi::errors',
>   {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         useDefaults: true,
>         directives: {
>           'connect-src': ["'self'", 'https:'],
>           'img-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
>           'media-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
>           upgradeInsecureRequests: null,
>         },
>       },
>     },
>   },
>   'strapi::cors',
>   'strapi::poweredBy',
>   'strapi::logger',
>   'strapi::query',
>   'strapi::body',
>   'strapi::session',
>   'strapi::favicon',
>   'strapi::public',
> ];
> ```

This only applies to us-east1 as all other AWS region S3 buckets NEED the region

**Comment by siemen-subbaiah** [comment]
I have the same error, but the provider which I'm using is cloudinary!

**Comment by siemen-subbaiah** [comment]
For people wondering how to do the same with cloudinary : 

```
module.exports = [
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com'],
          'media-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];

```

**Comment by kwiat1990** [comment]
> For people wondering how to do the same with cloudinary :
> 
> ```
> module.exports = [
>   {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         useDefaults: true,
>         directives: {
>           'connect-src': ["'self'", 'https:'],
>           'img-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com'],
>           'media-src': ["'self'", 'data:', 'blob:', 'res.cloudinary.com'],
>           upgradeInsecureRequests: null,
>         },
>       },
>     },
>   },
> ];
> ```

And how to get other images inside Admin Panel to work? Right now only images from Clouidnary will be loaded, any other don't.

**Comment by carloshs94** [comment]
cant get it to work with scaleway. anyone did it??

`{
  name: "strapi::security",
      config: {
        contentSecurityPolicy: {
          useDefaults: true,
          directives: {
            "connect-src": ["'self'", "https:"],
            'img-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.${env('AWS_REGION')}.${env('S3DOMAIN')}`],
            'media-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.${env('AWS_REGION')}.${env('S3DOMAIN')}`],
            upgradeInsecureRequests: null,
          },
        },
      },
  }`

**Comment by Wwwolfgang** [comment]
I'm trying to make a upload on a Strapi project with a provider (default config, I guess). But al get it response is 
`Refused to connect to 'http://my-url/upload/' because it violates the following Content Security Policy directive: "connect-src 'self' https:".`

With a Status Code 301

But the request url was https://my-url/upload 
The request go through a nginx but why does it respond on http instead of https?
Everything else works in the admin panel, only the uploads dont.

**Comment by tranvuluan** [comment]
> > Here is the configuration that worked for me, I spent 12 hours without finding a solution.
> > By removing the AWS_REGION, everything worked like a charm.
> > `"@strapi/strapi": "4.1.0"`
> > ```
> > module.exports = ({ env }) => [
> >   'strapi::errors',
> >   {
> >     name: 'strapi::security',
> >     config: {
> >       contentSecurityPolicy: {
> >         useDefaults: true,
> >         directives: {
> >           'connect-src': ["'self'", 'https:'],
> >           'img-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
> >           'media-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
> >           upgradeInsecureRequests: null,
> >         },
> >       },
> >     },
> >   },
> >   'strapi::cors',
> >   'strapi::poweredBy',
> >   'strapi::logger',
> >   'strapi::query',
> >   'strapi::body',
> >   'strapi::session',
> >   'strapi::favicon',
> >   'strapi::public',
> > ];
> > ```
> 
> This only applies to us-east1 as all other AWS region S3 buckets NEED the region

Wow thank you, I spent full day but can't fix, so lucky when I see your answer

**Comment by amityweb** [comment]
@carloshs94 

> EDIT: FIXED, i had strapi::security duplicated at the end of the file, so it was being overwritten by the default one.

Ah man you saved me hours. 'strapi::security', was already in the middlewares file when I added the 'strapi::security' code above it so it got cancelled out, and I never noticed.

**Comment by timnolte** [comment]
One thing that should be made very clear by people looking here is that CORS errors and Content Security Policy are NOT the same thing. Those are different headers entirely. It is possibly that a Content Security Policy directive may introduce a CORS error by way of something being blocked, however, if you don't have any errors about specific items that were blocked because of specific Content Security Policies directives then that most likely means it's not a CSP(Content Security Policy) issue.

**Comment by WebShapedBiz** [comment]
I'm having exact same issue with Cloudflare R2 provider (https://www.npmjs.com/package/strapi-provider-upload-cloudflare-r2), with this error message:
`Refused to load the image ... because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://dl.airtable.com".`

Funny enough, when I remove `https://dl.airtable.com` from my `middleware.js` the error message stays the same.

**Comment by deivijt** [comment]
in this guide https://strapi.io/blog/how-to-set-up-amazon-s3-upload-provider-plugin-for-our-strapi-appoficial they keeps  the REGION which is what causes the problem. :/

**Comment by mazwithwala** [comment]
In my case I had a sub directory on STORAGE_URL "/uploads" for both middleware.ts and plugins.ts so I just had to remove that on .env and everything was fine

**Comment by kepes** [comment]
Based on [Strapi docs](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables) I put `midlewares.js` into `config/env/production` folder. This way dev and prod environment separated.

This is my working `midlewares.js` content. I put `AWS_REGION` into the URL
```
module.exports = ({ env }) => [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            `https://${env("AWS_BUCKET_NAME")}.s3.${env("AWS_REGION")}.amazonaws.com`,
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            `https://${env("AWS_BUCKET_NAME")}.s3.${env("AWS_REGION")}.amazonaws.com`,
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

In S3 bucket config I had to make my bucket public. I think the [Strapi - Amazon AWS - Create the bucket](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html#_2-create-the-bucket) doc is wrong because the bucket must be public, contrary to what the documentation says. 

Based on [S3 User guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/HostingWebsiteOnS3Setup.html) I added a `Bucket policy` to my bucket
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::Bucket-Name/*"
            ]
        }
    ]
}
```

After configuration, you should check the images directly in a browser with the S3 Object URL. If everything went well, you can see the picture uploaded by Strapi. If the configuration failed and an error message is displayed, the Bucket is probably still not public.

**Important!**
According to the AWS user guide, creating an S3 bucket is dangerous and should only be done if you are hosting a static website. In my opinion the uploaded images are part of a static website and in this situation it is acceptable, but I am not an AWS expert. Please consider not using the public S3 bucket if you are not comfortable with it!

**Screenshots of my S3 Bucket config**

<img width="883" alt="bucket-01" src="https://user-images.githubusercontent.com/531009/215116064-2ceec1cb-2902-475f-a6a5-809e5a058535.png">
<img width="883" alt="bucket-02" src="https://user-images.githubusercontent.com/531009/215116072-256ca1cd-1360-422e-86b6-e7362a07ef8c.png">
<img width="883" alt="bucket-03" src="https://user-images.githubusercontent.com/531009/215116076-f73844a3-4c4d-4951-b4aa-c518af9b0dc1.png">

Another beautiful day has passed to find this bug :)

**Comment by nikita-fuchs** [comment]
@carloshs94 
> EDIT: FIXED, i had strapi::security duplicated at the end of the file, so it was being overwritten by the default one.

Damn, that was my mistake, too, you saved me !

**Comment by niks7392** [comment]
Is there any same fix for the plugin "strapi-uploader-provider-do" because i am getting the same error

**Comment by galda-mez** [comment]
If anyone has issues with the images of Strapi's Marketplace, add **"market-assets.strapi.io"** to the **img-src** and **media-src** directives, like this:

```ts
export default [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'", 
            "data:", 
            "blob:", 
            `https://${process.env.AWS_BUCKET}.s3.amazonaws.com`, 
            "dl.airtable.com", 
            "market-assets.strapi.io"
          ],
            "media-src": [
            "'self'", 
            "data:", 
            "blob:", 
            `https://${process.env.AWS_BUCKET}.s3.amazonaws.com`, 
            "dl.airtable.com", 
            "market-assets.strapi.io"
        ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];
```

**Comment by andersonstudioa** [comment]
I fixed changing the file `config/middlewares.ts` with `CDN_URL`

![image](https://github.com/strapi/strapi/assets/15079984/8ffc670c-ff44-4827-a1a6-94cea85c0b48)

**Comment by brun0xff** [comment]
> If anyone has issues with the images of Strapi's Marketplace, add **"market-assets.strapi.io"** to the **img-src** and **media-src** directives, like this:
> 
> ```ts
> export default [
>   'strapi::errors',
>   'strapi::security',
>   'strapi::cors',
>   'strapi::poweredBy',
>   'strapi::logger',
>   'strapi::query',
>   'strapi::body',
>   'strapi::session',
>   'strapi::favicon',
>   'strapi::public',
>   {
>     name: "strapi::security",
>     config: {
>       contentSecurityPolicy: {
>         useDefaults: true,
>         directives: {
>           "connect-src": ["'self'", "https:"],
>           "img-src": [
>             "'self'", 
>             "data:", 
>             "blob:", 
>             `https://${process.env.AWS_BUCKET}.s3.amazonaws.com`, 
>             "dl.airtable.com", 
>             "market-assets.strapi.io"
>           ],
>             "media-src": [
>             "'self'", 
>             "data:", 
>             "blob:", 
>             `https://${process.env.AWS_BUCKET}.s3.amazonaws.com`, 
>             "dl.airtable.com", 
>             "market-assets.strapi.io"
>         ],
>           upgradeInsecureRequests: null,
>         },
>       },
>     },
>   },
> ];
> ```

For god's sake thank you, you're awesome!

**Comment by LeNguyenMinhTuan** [comment]
> I'm trying to make a upload on a Strapi project with a provider (default config, I guess). But al get it response is `Refused to connect to 'http://my-url/upload/' because it violates the following Content Security Policy directive: "connect-src 'self' https:".`
> 
> With a Status Code 301
> 
> But the request url was https://my-url/upload The request go through a nginx but why does it respond on http instead of https? Everything else works in the admin panel, only the uploads dont.

I'm stuck here too. Did you solve it ?

**Comment by jsphkhan** [comment]
> ```ts
> market-assets.strapi.io
> ```

This is the solution to follow if anybody is using a CDN in front of S3 bucket. I was using a Cloudfront instance on top of AWS S3.

**Comment by jsphkhan** [comment]
> I fixed changing the file `config/middlewares.ts` with `CDN_URL`
> 
> ![image](https://private-user-images.githubusercontent.com/15079984/260039441-8ffc670c-ff44-4827-a1a6-94cea85c0b48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzEwMjYsIm5iZiI6MTcwNzEzMDcyNiwicGF0aCI6Ii8xNTA3OTk4NC8yNjAwMzk0NDEtOGZmYzY3MGMtZmY0NC00ODI3LWExYTYtOTRjZWE4NWMwYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEwNTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NjY3ODAzOTEyODExMGRjYzg4MDM0MjQxMTM4MjRmNTI2NzY1MzhkNDRlMmU5ODgxMDNhZmE5NjEzNmQwZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TELnVfUW4a3QH0mOVxVRMYB4Yb9SHgsTYwEwvLOlEcI)

This is the solution to follow if anybody is using a CDN in front of S3 bucket. I was using a Cloudfront instance on top of AWS S3.

**Comment by Kamarhinanton** [comment]
Does enyone know, why after transferring data to prod, url is broken in reach text block? In media galery picture is ok.
<img width="1427" alt="image" src="https://github.com/strapi/strapi/assets/77457199/63437788-9da5-49b7-846f-8c4e57f2e366">

**Comment by nikita-fuchs** [comment]
> Does enyone know, why after transferring data to prod, url is broken in reach text block? In media galery picture is ok. <img alt="image" width="1427" src="https://private-user-images.githubusercontent.com/77457199/345797384-63437788-9da5-49b7-846f-8c4e57f2e366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTIzMTksIm5iZiI6MTcyMDA5MjAxOSwicGF0aCI6Ii83NzQ1NzE5OS8zNDU3OTczODQtNjM0Mzc3ODgtOWRhNS00OWI3LTg0NmYtOGM0ZTU3ZjJlMzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDExMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNjViZTU5NDg2OGZlM2VjYmQwMzU1OGM5MmQzOWNlMjhiMWVmNWVjOGE2MzFjNjJlZmE3ODJkYWUyODc2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8pI9jRrtt-8AjBJGDH2xZrTUVfiMXdEXA90wN_U1PQ">

Because your fileURL is pointing to `localhost`, which is not a thing of course when you deploy things somewhere else.

**Comment by Kamarhinanton** [comment]
How I can change this behivor?

**Comment by H3lltronik** [comment]
I haven't been able to fix it and don't know what to do.
My console logs this error:

`Refused to load the image 'https://s3.us-east-1.amazonaws.com/my-bucket-stuff/thumbnail_1700242274671_05530326c8.jpeg?updatedAt=2024-07-09T05%3A26%3A13.053Z' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://s3.us-east-1.amazonaws.com/my-bucket-stuff".`

This is my config/middlewares.js

```
module.exports = ({ env }) => [
  "strapi::errors",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            `https://s3.${env("AWS_REGION")}.amazonaws.com/${env(
              "AWS_BUCKET_NAME"
            )}`,
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            `https://s3.${env("AWS_REGION")}.amazonaws.com/${env(
              "AWS_BUCKET_NAME"
            )}`,
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];

```

I tried adding a wildcard like '/*' in the S3 URL but it doesn't work the only thing that has shown to work is to directly place the entire URL in the "img-src" array but that's obviously wrong.

Please, somebody help me, I've stuck here for days.

I'm running strapi 4.25.2

**Comment by JAV-Ruent** [comment]
I encounter same error, is there anyone so solve the issue?

**Comment by JAV-Ruent** [comment]
@H3lltronik  have you ever fix this issue?

**Comment by DannyST89** [comment]
Thanks ,it works for me.
