### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by justoverclockl** [strapi/strapi#11638]
Hello, i'm trying to install strapi locally to make some tests, but i get this error during the install:

```
Error while installing dependencies:
error my-project@0.1.0: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.13.0"
error Found incompatible module.
```

isn't compatible with latest nodejs version?

**Comment by badertabechecc** [comment]
#10149

**Comment by derrickmehaffy** [comment]
Strapi v3 does not support node 16 and won't, Strapi v4 will be the first to support node 16.

You will need to downgrade to Node v14.
