### ISSUE TITLE
[V4] [RFC] GraphQL Developer Experience improvements 🥇 

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11649]
### Prelude

The below is an opinion. It is based on my experience, may not be complete and I may have missed something, that said I would love for this opinion to be considered, and to hear other people share their thoughts/suggestions.

### Summary

After a few of weeks of working with V4 and GraphQL, I've made a decision to scratch those weeks of work and move away from V4 for ' time being.

Below are the biggest pain points that made me do it.

### Why is it needed?

After trying to switch to V4 using GraphQL, sadly I've discovered that DX could be muuch better.

GraphQL is not going anywhere and Strapi providing a solid and good DX for GraphQL would surely pave way for a whole ecosystem of new potential users and honour the existing GQL lovers.

### Current pain points(s)

1. Defining routes is a pain, especially if compared to what it was like in **V3**
2. Managing User Permissions is much harder and convoluted (somewhat related to the first pain point)
3.  While extending `Mutation` the way it currently is needed to is not per se Strapi related problem, it would be amazing if Strapi would handle this by simply creating a new resolver (I believe this is somewhat how it worked in **V3**)
4. The response format is not great for those working with say Apollo Client 3 (or other clients with cache normalization), where the _GQL Client_ relies on a unique identifier inside it _GQL type_ to track the given object. So having the `ID` inside the `attributes` would be beneficial. Furthermore the nested `data {}` inside the response it somewhat verbose and not sure if it's great DX, not only for the sake of the proportionally increasing nullity checks with each nested relation, but also since it - _again_ - increases the complexity for using the _GQL Client_ with **cache normalization** (this could be solved with something like [`custom merge functions`](https://www.apollographql.com/docs/react/caching/cache-field-behavior/#the-merge-function), but that surely would not be a good DX. **_Perhaps_** this could be solved by moving the `metadata` inside the actual response, say instead of 
```graphql
query {
  posts {
    data {
      id
      attributes {
        title
        ...
      }
    }
    meta {
      pagination {
        ...
      }
    }
  }
}
```
it could be this:
```graphql
query {
  posts {
    id
    title
    meta {
      pagination
      ...
    }
  }
}
```

The approach as in V3 where it was possible to map the same controllers to GraphQL and REST was great, perhaps there is a way to provide same DX with the new engine improvements.

### More context

Please don't hate me Strapi folks, you know I love you. But I feel like we're at the point where it's either speak now or forever hold your peace, so. 😄 

IMHO, regardless of the fact that (as far as I know) the percentage of current Strapi users for GraphQL is low, it is still a very important piece of the puzzle for a modern headless CMS tool. Furthermore, I believe the number has been historically so low because the DX was not great - now unfortunately it seems it has potentially gotten further from great.

**Comment by mattf96s** [comment]
Fully agree with the return pattern comments. I'm not seeing the benefit of the overly nested layers + losing Apollo's normalized cache is a massive downside. For a lot of people, this might end up being a choice between using Strapi and using graphql.

**Comment by krstivojevicv** [comment]
New response format is a huge downside

**Comment by Sepifanovskiy** [comment]
I`v ended up writing transformer for the response. Unfortunately if I apply it in apollo link it messes up caching so we ended with calling transformer function after each query :(

Data and attributes wrappers are totally unnecessary and only cause problems

**Comment by alexandrebodin** [comment]
Hello everyone, thank you for these valuable comments.

We created a RFC a few months back to share the context and why we needed those changes and to get ideas/comments on the GraphQL schema here https://github.com/strapi/rfcs/pull/29. 

I'll close this issue to keep the issues focused on bugs and will mention it in the RFC to keep everything in a single location.
Please do add more context to your comments there so we can come back to it and see what we can do to improve the pain points.

**Comment by ScottAgirs** [comment]
Hi @alexandrebodin thank you for your input.

I will do my best to carve out some time.

While we're here, I wanted to also share my thoughts on this flow - since not everybody will intuitively look for Strapi RFC repo and granted that it's been only less than 2 days and there are already supporters of this notion, seeing this as a legitimate issue - _humbly_, I think leaving this as accessible to Strapi'nauts as possible would be beneficial not only to users but also to Strapi team.

Furthermore, I think one of the reasons why this major change slipped by unnoticed from my radar was because I also often forget about the RFC repo and/or don't find it very convenient to navigate.

Thanks again for taking the time to read this and godspeed with V4 stable launch! 🙌🏼

**Comment by alexandrebodin** [comment]
Thanks for this remark.

I agree with you that the RFC are not visible enough and we should try to improve this. I'm not going to delete it or anything so if someone finds it they can go to the RFC  👍  

And I'll see you there :)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/faulty-generated-graphql-schema/13163/2

**Comment by boazdejong** [comment]
> This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:
> 
> https://forum.strapi.io/t/faulty-generated-graphql-schema/13163/2

That's me, not much extra details. Sorry I didn't know this issue existed. I thought I was doing something wrong in getting the 'data' and 'attributes' in the response, as it is mentioned nowhere in the documentation. This just makes it unusable.

**Comment by mattf96s** [comment]
I'm just using Nexus directly to define the queries.  Also allows you to use graphql-shield + field level authorizations—because the permissions issue with relational data also makes it almost unusable unless you make every single query public.

```
const {extendType, queryField} = require('nexus')
const { prop } = require('lodash/fp')
const { ruleType } = require('nexus-shield')

# Add back id field to the Contact type
const contactWithId = extendType({
  type: 'Contact',
  definition: (t) => {
    t.id('id', { resolve: prop('id') })
  }
})

const getContactDetails = queryField('getContactDetails', {
  type: 'Contact',
  # only allow authenticated users
  shield: ruleType({
    resolve: (root, args, ctx, info) => {
      if (ctx.state.auth.credentials) return true
      return false
    }
  }),
  async resolve() {
    return strapi.entityService.findMany('api::contact.contact', {
      select: '*'
    })
  }
})
`

**Comment by boazdejong** [comment]
I don't get why this is closed. GraphQL is all about better DX and this just makes it so bad.. This needs to be fixed.

**Comment by SteaceP** [comment]
To get a thumbnail:
`data.usersPermissionsUser.data.attributes.picture.data.attributes.formats.thumbnail.url`
Yeah

**Comment by hieuxinhe94** [comment]
Any update on this issue? plz

**Comment by boazdejong** [comment]
I don't think GraphQL has a high priority for them any time soon.. The changes to the schema were made deliberately in V4 it seems.

**Comment by derrickmehaffy** [comment]
We will open a discussion thread about it soon but we won't revert it back to the v3 style as that would be a breaking change and we are trying to follow semver

**Comment by abdonrd** [comment]
> We will open a discussion thread about it soon but we won't revert it back to the v3 style as that would be a breaking change and we are trying to follow semver

As it is a plugin, there should be no problem in making a new major version, right?

So many levels makes it complicated.

**Comment by derrickmehaffy** [comment]
> > We will open a discussion thread about it soon but we won't revert it back to the v3 style as that would be a breaking change and we are trying to follow semver
> 
> As it is a plugin, there should be no problem in making a new major version, right?
> 
> So many levels makes it complicated.

If we change GraphQL then we also need to change REST as the whole point is to unify their response structure meaning it's still a breaking change and we don't update our packages independently like some other frameworks.

**Comment by boazdejong** [comment]
It almost doesn't even make sense to support GraphQL if you have to query like this. Especially not on a 'developer first' platform. The amount of nesting you have to filter through in the response data is ridiculous.

I mean look at this example from my project. GraphQL is all about querying only what you need..

```gql
query {
  wijken {
    data {
      attributes {
        naam
        straten {
          data {
            attributes {
              naam
              klanten {
                data {
                  attributes {
                    wasbeurten {
                      data {
                        attributes {
                          betaald
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

This could and should just be:
```gql
query {
  wijken {
    naam
    straten {
      naam
      klanten {
        wasbeurten {
          betaald
        }
      }
    }
  }
}
```

**Comment by timohofmeijer** [comment]
> I`ve ended up writing transformer for the response.
Would you mind sharing a gist of the transformer @Sepifanovskiy? I intend to do the same and this would likely same me some time.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/discussion-regarding-the-complex-response-structure-for-rest-graphql-developer-experience/13400/1

**Comment by derrickmehaffy** [comment]
Hi everyone, I'm going to lock this issue, please continue the discussion on the above mentioned forum thread ^^^
