### ISSUE TITLE
[v4 beta.14] installation error

### ISSUE THREAD

**Issue by amjadniazi48** [strapi/strapi#11647]
### Describe the bug

Hi strapi team, getting this error while installing v14 on ubuntu 20.04, node verion=14.18.1, npm version 8.1.4

This problem occured with the latest version of npm 8.1.4 while with 6.14.15 its working fine
### Expected behavior

Building your admin UI with development configuration ...

Webpack █████████████████████████ building (10%) 0/1 entries 107/117 dependencies 7/85 modules 73 active 
 node_modules/@strapi/admin/node_modules/react/index.js

`ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes' in '/home/amjad/projects/beta14/.cache/admin/src'
    at /home/amjad/projects/beta14/node_modules/webpack/lib/Compilation.js:1765:28
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/home/amjad/projects/beta14/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/home/amjad/projects/beta14/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /home/amjad/projects/beta14/node_modules/neo-async/async.js:6883:13
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/home/amjad/projects/beta14/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /home/amjad/projects/beta14/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/amjad/projects/beta14/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/amjad/projects/beta14/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/themes' in '/home/amjad/projects/beta14/.cache/admin/src'
  Parsed request is a module
  using description file: /home/amjad/projects/beta14/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/amjad/projects/beta14/.cache/admin/src/node_modules doesn't exist or is not a directory
      /home/amjad/projects/beta14/.cache/admin/node_modules doesn't exist or is not a directory
      /home/amjad/projects/beta14/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /home/amjad/projects/beta14/node_modules
        /home/amjad/projects/beta14/node_modules/@strapi/design-system doesn't exist
      /home/amjad/projects/node_modules doesn't exist or is not a directory
      /home/amjad/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/themes' in '/home/amjad/projects/beta14/.cache/admin/src'
    at /home/amjad/projects/beta14/node_modules/webpack/lib/Compilation.js:1765:28
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/home/amjad/projects/beta14/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/home/amjad/projects/beta14/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /home/amjad/projects/beta14/node_modules/neo-async/async.js:6883:13
    at /home/amjad/projects/beta14/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/home/amjad/projects/beta14/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /home/amjad/projects/beta14/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /home/amjad/projects/beta14/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/home/amjad/projects/beta14/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/themes' in '/home/amjad/projects/beta14/.cache/admin/src'
  Parsed request is a module
  using description file: /home/amjad/projects/beta14/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/amjad/projects/beta14/.cache/admin/src/node_modules doesn't exist or is not a directory
      /home/amjad/projects/beta14/.cache/admin/node_modules doesn't exist or is not a directory
      /home/amjad/projects/beta14/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /home/amjad/projects/beta14/node_modules
        /home/amjad/projects/beta14/node_modules/@strapi/design-system doesn't exist
      /home/amjad/projects/node_modules doesn't exist or is not a directory
      /home/amjad/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory`

### System

- Node.js version: 14.18.1
- NPM version: 8.1.4
- Strapi version: v4.beta14
- Database: postgres
- Operating system: ubuntu 20.04 LTS

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11640
