### ISSUE TITLE
Private attributes are seen in GraphQL (but not seen in API) response

### ISSUE THREAD

**Issue by z-ax** [strapi/strapi#1164]
**Informations**
- **Node.js version**: 9.10.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: MondoDB 3.6.4
- **Operating system**: MacOS

**What is the current behavior?**
Private attributes can be queried with GraphQL (which is bad). But not seen with regular GET request to API (which is expected).

**Steps to reproduce the problem**
Create a model, add attributes, mark some of them private.

**What is the expected behavior?**
Do not let them to be queried.

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by Aurelsicoko** [comment]
It should be fixed in the next release!
