### ISSUE TITLE
[v4] 404 on /auth/local

### ISSUE THREAD

**Issue by moge11** [strapi/strapi#11643]
Hello,

I'm running a Strapi Instance on a remote Server and everytime I try a authentication request I get a 404 error code back.
But I'm able to GET Data through the API.
![image](https://user-images.githubusercontent.com/46135790/142655073-8712b036-6a9e-4f54-9630-f7e2e7d6877e.png)

Node.js Version v16.12.0
NPM Version v8.1.0
Strapi Version v4.0.0-beta.12

**Comment by boazpoolman** [comment]
I think this endpoint has moved to `/api/auth/local`

**Comment by derrickmehaffy** [comment]
Yes that's correct @boazpoolman this is intended as we have a default prefix of /api now on all content API endpoints.

**Comment by shumiyao** [comment]
Where can we find a list of endpoints for version 4?

**Comment by derrickmehaffy** [comment]
> Where can we find a list of endpoints for version 4?

`yarn strapi routes:list`
