### ISSUE TITLE
After creating a super admin user, I'm always redirected to the register page when trying to login to the admin panel

### ISSUE THREAD

**Issue by SeedyROM** [strapi/strapi#11648]
## Bug report

See the title

### Describe the bug

See the title

### Steps to reproduce the behavior

1. Create a strapi application with `yarn create strapi-app <project_name>` using bookshelf / postgres
2. Register an admin user
3. Try and open the admin panel from another window
4. Always redirects to register admin, even if one exists
5. Attempting to create a new admin sends a 400 error saying the admin already exists and no error appears in the UI

### Expected behavior

You can login more than once from one window to use the admin panel.

### System

- Node.js version:  v.14.7.4
- Yarn version: 1.22.4
- Strapi version: 3.1.4 
- Database: Postgres
- Operating system: Arch Linux (Manjaro 21.1.6 Pahvo)

**Comment by derrickmehaffy** [comment]
> Strapi version: 3.1.4

Please test on the latest version (v3.6.8)
