### ISSUE TITLE
[v4] ML When selecting a media, the whole card should be clickable

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#11655]
## Bug report

When I'm trying to select a media item from the media library to insert into a field, I have to click the checkbox in the top-left corner. It would be nice if I could click the whole card in order to select an item. Ideally the whole card also has an interaction-state (hover/ focus).

### System

- Strapi version: 4.0.0-beta.14
- Operating system: Firefox 96.0a1 (2021-11-19) / Ubuntu

**Comment by derrickmehaffy** [comment]
Can you please provide a little more details or screenshots. The limited data here doesn't really make it easy to confirm reproduction. You can either update the issue or file a new one but please provide a little more than 3 sentences.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
