### ISSUE TITLE
Images on published resources disappear occasionally

### ISSUE THREAD

**Issue by m-murasovs** [strapi/strapi#11657]
### Describe the bug

Occasionally, images in our published resources disappear. This morning, I found that one of our pages was down because of this. The image was still in our library and the last update to the Strapi resource had been made a month ago, so it wasn't an issue on our end, but rather in Strapi itself.

This happened a couple of times in the past as well.

### Steps to reproduce the behavior

That's the problem - it's not really possible to reproduce the bug at will. This is more of a report that this issue exists for you to be aware of.

### Expected behavior

Images shouldn't disappear from a resource randomly.

### Screenshots

<img width="696" alt="Screenshot 2021-11-23 at 09 29 36" src="https://user-images.githubusercontent.com/38246758/142998079-7ac9c99b-fd60-4183-8ab9-cf091d311577.png">

### System

- Node.js version: 
- NPM version: 
- Strapi version: 3.6.8
- Database: 
- Operating system:

**Comment by kasonde** [comment]
@m-murasovs please fill out the rest of the issue templates, "System" section. This is the only way we're able to know what environment the application was running on when this issue occurred. Additionally, please share details of your current deployment. This is not an issue with Strapi itself as Strapi will never randomly delete any of your information, we need more information to get to the bottom of what could be causing the issue in question.

**Comment by kasonde** [comment]
Closing due to lack of information.
