### ISSUE TITLE
[v4] CM View Configuration misaligned

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#11654]
## Bug report

Fields in the view configuration of the content manager are misaligned.

![Screenshot from 2021-11-22 18-36-40](https://user-images.githubusercontent.com/2244375/142909034-15c00088-3226-43f3-a54f-353a704bcb26.png)

### System

- Strapi version: 4.0.0-beta.14
- Operating system: Firefox 96.0a1 (2021-11-19) / Ubuntu

**Comment by derrickmehaffy** [comment]
Can't reproduce in Chrome or Edge (Linux Beta), can reproduce in Firefox.

**Comment by yanniskadiri** [comment]
This has been fixed, thanks @gu-stav - see you soon :)
