### ISSUE TITLE
The Strapi version in the admin does not fit

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1166]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The Strapi version in the admin does not fit.

<img width="253" alt="screen shot 2018-05-11 at 11 26 32" src="https://user-images.githubusercontent.com/1007051/39917682-9f97927a-550e-11e8-83a0-01252b9c9337.png">

**Steps to reproduce the problem**

Go to the admin.

**What is the expected behavior?**

The Strapi version in the admin fits.

**Suggested solutions**

Multiline?
Move to another place?
Move the language selector to another place?

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@soupette I think this falls in your realm.
