### ISSUE TITLE
[v4] Requesting Media without success

### ISSUE THREAD

**Issue by moge11** [strapi/strapi#11671]
### Describe the bug

I created a collection with two Text fields and two media fields. When I try to query them via the API ( api/database_names/1)
I just get the two text fields and the creation and updated date but no sign of the media elements.

### Steps to reproduce the behavior

1. Create new Collection type with a media component
2. Add a entry to the new collection
3. Query via REST
4. Don't get any media component

### Expected behavior

Get properties of Media components

### Screenshots

![image](https://user-images.githubusercontent.com/46135790/143276188-2de18085-3ca4-48ed-aea7-fb8b533b54bf.png)
![image](https://user-images.githubusercontent.com/46135790/143276244-c6cd4da2-b934-4f0c-9a3e-627cb4f5f91d.png)

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: v4.0.0-beta.14
- Database: SQLite
- Operating system: Ubuntu 

Thanks in advance!

**Comment by alexandrebodin** [comment]
Hi, medias need to be populated in v4 to avoid overloading data you may not want :) 

You can do `?populate=media`
