### ISSUE TITLE
The images in the Roles and permissions icons are wrong

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1167]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The icons in the Roles and permissions plugin are wrong:

<img width="1078" alt="screen shot 2018-05-11 at 11 26 50" src="https://user-images.githubusercontent.com/1007051/39917856-175c93fa-550f-11e8-87b1-91e60a75d780.png">

<img width="1072" alt="screen shot 2018-05-11 at 11 27 03" src="https://user-images.githubusercontent.com/1007051/39917865-1b5d4918-550f-11e8-900c-12362e4cd8f9.png">

**Steps to reproduce the problem**

Go to the Roles and permissions plugin.

**What is the expected behavior?**

See the right icons.

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
@abdonrd are in in live or dev mode ?

**Comment by abdonrd** [comment]
@lauriejim with `strapi start` after a fresh installation.

**Comment by abdonrd** [comment]
@lauriejim and same thing in the staging deployed version.

**Comment by abdonrd** [comment]
Seems fixed with the last `v3.0.0-alpha.12.2`! 🎉

**Comment by lauriejim** [comment]
Thank you @abdonrd for the update.
