### ISSUE TITLE
Improve the Content Types display names

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1168]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

<img width="1440" alt="strapi-names" src="https://user-images.githubusercontent.com/1007051/39929498-7e2387dc-5538-11e8-965a-fc95d4dd671c.png">

* In the first left sidebard you see `Conferenceeditions`.
* In the second left sidebard you see `Conference Edition`.
* In the relationship you see `Conferenceedition`.

**Steps to reproduce the problem**

Create a model with some camelCase. For example: `conferenceEdition`.

**What is the expected behavior?**

Show names consistently. Probably like `Conference Edition`. Better if we can customize it.

**Suggested solutions**

Add a `displayName` in the `Model.seetings.json`?

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by abdonrd** [comment]
Also when I select the `Conferences` content type:

![conferences](https://user-images.githubusercontent.com/1007051/39934142-36559956-5545-11e8-95a7-31f3bf8e0ec2.jpg)

But when I select the `Conferenceeditions` content type the both content types are selected:

![conference-editions](https://user-images.githubusercontent.com/1007051/39934168-4c3ff036-5545-11e8-8102-85cc404db711.jpg)

**Comment by derrickmehaffy** [comment]
@abdonrd yes the custom left panel names is something the strapi team will be working on. I think they have a few more stability things planned in the near future but I would expect this type of feature rolling out within the next few weeks to months.

Also something odd is going on with your interface there 😛

**Comment by lauriejim** [comment]
I close this issue. It's have been linked to #661 .

**Comment by vitaliyKorzhenko** [comment]
how I can change name in left menu?  How I can use label in admin/config layout.js

**Comment by derrickmehaffy** [comment]
@vitaliyKorzhenko not currently possible.
