### ISSUE TITLE
[V4] [4.0.0-beta.16] Component field type breaks the strapi admin UI 

### ISSUE THREAD

**Issue by firzx77** [strapi/strapi#11682]
### Describe the bug

Component field type breaks the strapi admin UI

### Steps to reproduce the behavior

1. Create 1 collection type, called `measures`
2. Create 1 collection type, called `widget_bars`
3. Create 1 component, and add **relation as a field** that refers from `measures` content type.

### Expected behavior

Component field type should not breaks the strapi admin UI

### Screenshots

<img width="1680" alt="Screen Shot 2021-11-25 at 21 54 49" src="https://user-images.githubusercontent.com/2428512/143465555-3ae3be58-d79e-42e6-939d-06c1c1f52e26.png">
<img width="1680" alt="Screen Shot 2021-11-25 at 21 56 11" src="https://user-images.githubusercontent.com/2428512/143465568-80b7b254-f10c-46cf-acaa-3c5f9fe710ca.png">

### System

- Node.js version: v14.18.1
- NPM version: v6.14.15
- Strapi version: v4.0.0-beta.16
- Database: sqlite3 v5.0.2
- Operating system: macOS Monterey 12.0.1

**Comment by alexandrebodin** [comment]
Fixed in beta.17 ;)
