### ISSUE TITLE
v4 controllers:list is missing from strapi cli on beta 17

### ISSUE THREAD

**Issue by Cpaczek** [strapi/strapi#11697]
### Describe the bug

There should be a way to list all the controllers.

Referenced in the new docs here:
https://docs-next.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#extending-core-controllers

### Steps to reproduce the behavior

`npx create-strapi-app@4.0.0-beta.17 strapibeta17`
`yarn strapi controllers:list`

### Screenshots

![image](https://user-images.githubusercontent.com/25715982/143627423-cada4fcb-7093-467d-bcfb-5314126ef43b.png)

### System

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: Beta 17
- Database: SQLite
- Operating system: Windows 10

**Comment by Cpaczek** [comment]
Still missing on 4.0.0

**Comment by kasonde** [comment]
Confirmed, reached out to our team about it.

**Comment by derrickmehaffy** [comment]
Fixed in https://github.com/strapi/strapi/pull/11716

will be released in next version
