### ISSUE TITLE
Strapi v4: 500 Internal Error thrown by REST API when requesting non-existent field

### ISSUE THREAD

**Issue by log4shell** [strapi/strapi#11696]
### Describe the bug

The REST API throws a 500 Internal Error when requesting a non-existent field on a entity. 

### Steps to reproduce the behavior

1. Invoke GET on a collection and supply a valid field name, e.g., GET /api/tests/?fields=Title
2. Observe that the response lists all entries and includes the specified field (e.g., Title)
3. Invoke GET on a collection and supply an invalid field name, e.g., GET /api/tests/?fields=non-existent
4. Observe that a 500 Internal Error is thrown.

### Expected behavior

The API should ignore invalid field names when returning the response and provide the same data as if the invalid field name had not been provided.

Alternatively, the API should return an error indicating that the request is invalid. However, this approach (like the current 500 Internal Error) can be abused to enumerate private fields on collections, e.g., an attacker can determine if a collection type contains a private field with a specific name (valid response but without the field if it exists, otherwise error thrown). It is therefore recommended to ignore invalid field names instead.

### Console output
Note that the second request (step 3 above) throws an error:

[2021-11-26 18:02:40.490] http: GET /api/tests/?fields=Title (6 ms) 200
[2021-11-26 18:02:49.343] error: select `t0`.`id`, `t0`.`non-existent` from `tests` as `t0` limit 25 - SQLITE_ERROR: no such column: t0.non-existent
Error: select `t0`.`id`, `t0`.`non-existent` from `tests` as `t0` limit 25 - SQLITE_ERROR: no such column: t0.non-existent

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: v4.0.0
- Database: SQLite
- Operating system: Ubuntu 18.04 LTS

**Comment by Marc-Roig** [comment]
closing in favor of https://github.com/strapi/strapi/issues/11696
