### ISSUE TITLE
 Connection test failed: Cannot find module 'mquery'

### ISSUE THREAD

**Issue by AhmadSalihu** [strapi/strapi#11701]
I am trying to install strapi with mongodb, but I keep on getting this error every time I am installing the strapi package " Connection test failed: Cannot find module 'mquery'" Please Any one with an Idea on how I can fixed this issue ? 
this is the console am getting..
`? Choose your installation type Custom (manual settings)
? Would you like to use a template? (Templates are Strapi configurations designed for a specific use case) No
? Choose your default database client
? Choose your default database client mongo
? Database name: inextdatabase
? Database name: inextdatabase
? Host: cluster0.y4fn3.mongodb.net
? Host: cluster0.y4fn3.mongodb.net
? +srv connection: (false)
? +srv connection: false
? Port (It will be ignored if you enable +srv): (27017)
? Port (It will be ignored if you enable +srv): 27017
? Username: ideanext2021
? Username: ideanext2021
? Password: ************
? Password: ************
? Authentication database (Maybe "admin" or blank): admin
? Authentication database (Maybe "admin" or blank): admin
? Enable SSL connection: (y/N) n
? Enable SSL connection: No

⛔️ Connection test failed: Cannot find module 'mquery'
Require stack:
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\promise_provider.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\helpers\promiseOrCallback.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\utils.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\statemachine.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\internal.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\document.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\lib\index.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\mongoose\index.js
- C:\Users\AHMADT~1\AppData\Local\Temp\strapi368bf3894b93\node_modules\strapi-connector-mongoose\lib\utils\connectivity.js
- C:\Users\AhmadTech\AppData\Roaming\npm-cache\_npx\1684\node_modules\create-strapi-app\node_modules\strapi-generate-new\lib\create-customized-project.js
- C:\Users\AhmadTech\AppData\Roaming\npm-cache\_npx\1684\node_modules\create-strapi-app\node_modules\strapi-generate-new\lib\generate-new.js
- C:\Users\AhmadTech\AppData\Roaming\npm-cache\_npx\1684\node_modules\create-strapi-app\node_modules\strapi-generate-new\lib\index.js
- C:\Users\AhmadTech\AppData\Roaming\npm-cache\_npx\1684\node_modules\create-strapi-app\create-strapi-app.js
- C:\Users\AhmadTech\AppData\Roaming\npm-cache\_npx\1684\node_modules\create-strapi-app\index.js

Retrying...
? Choose your default database client (Use arrow keys)
> sqlite
  postgres
  mysql
  mongo`

**Comment by AhmadSalihu** [comment]
Please I need your help and all the help alI can get..

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
