### ISSUE TITLE
API Paths and Permission Role names won't update after renaming collections

### ISSUE THREAD

**Issue by thegoodcode** [strapi/strapi#11702]
### Describe the bug

When you rename a collection type in Content-Type Builder, for example from Post to Article, the api path associated with the collection does not get updated; In our case, /posts returns the list of articles instead of /articles which only returns 404.
Furthermore, the same issue exist in Roles tab of USERS & PERMISSIONS PLUGIN section in Settings page where either in Authenticated or Public Permissions, the name of the collection type in Application accordion remains to be the previous value, in our example Post.

### Steps to reproduce the behavior

1. Create a collection type in Content-Type Builder ( for example named Post )
2. Rename the collection ( for example to Article )
3. Check the api path for the newly renamed collection in localhost ( http://localhost:1337/articles  )
4. Check Authenticated/Public Permissions of Application accordion in Settings page => Roles => USERS & PERMISSIONS PLUGIN

### Expected behavior

The api path associated with collection types alongside their permission role names should update accordingly after renaming a collection.

### System

- Node.js version: v14.18.0
- NPM version: v6.14.15
- Strapi version: v3.6.8
- Database: sqlite
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
v3 is now in security maintenance only so no additional bugs will be fixed since v4 is live. Marking as closed.
