### ISSUE TITLE
On Create/Update ContentType over Builder i get an error message. 

### ISSUE THREAD

**Issue by SupaMario123** [strapi/strapi#11706]
Hello Strapi Team!

I saw your project, and it looks great so i wanted to take a dive into it. 
I created a local strapi project from default docker compose file with a postgres database:

https://github.com/strapi/strapi-docker/blob/master/examples/postgresql/docker-compose.yml

I had even trouble with that, but i got it to work after running 
softwareupdate --install-rosetta
since i work on an apple m1 silicon valley mac. 

I really like the UI of the project, and i would love to use it in future projects, but it has to run without any problems for that. What could be the reason for these errors on create/update ContentType over Builder?

**Errors as an Image:**
<img width="578" alt="Bildschirmfoto 2021-11-29 um 12 26 26" src="https://user-images.githubusercontent.com/33687577/143860514-0f2dbc0f-6612-4b36-9a2e-9412a0639e2a.png">

**Errors from console:**
main.2ced9abe.chunk.js:78 GET http://localhost:1337/admin/users/me/permissions net::ERR_EMPTY_RESPONSE
request @ main.2ced9abe.chunk.js:78
....
main.2ced9abe.chunk.js:78 GET http://localhost:1337/content-type-builder/components net::ERR_EMPTY_RESPONSE
...
push.exports.unstable_runWithPriority @ main.2ced9abe.chunk.js:124781
.....
main.2ced9abe.chunk.js:171538 {err: TypeError: Failed to fetch
 ....
main.2ced9abe.chunk.js:78 GET http://localhost:1337/content-type-builder/content-types net::ERR_EMPTY_RESPONSE
.....
main.2ced9abe.chunk.js:78 GET http://localhost:1337/content-type-builder/reserved-names net::ERR_EMPTY_RESPONSE

Versions:
STRAPI VERSION v3.6.8
NODE VERSION v14.16.0

I would appreciate any help. Thank you!

**Comment by SupaMario123** [comment]
The weird thing is, after refreshing the browser, the changes are saved but i get these errors. And sometimes the entire admin area crashes for a few seconds. Does anyone has any idea?

**Comment by derrickmehaffy** [comment]
It appears your backend crashed and wasn't giving any response. Either way this isn't really a Strapi bug but appears to be an environment issue.

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by SupaMario123** [comment]
@derrickmehaffy  thank you for your answer. I mean i took the official docker compose template to run the project, and the main idea of docker is to avoid environment issues. So i don't understand why this should be one?
