### ISSUE TITLE
v4 Create a new collection type not work

### ISSUE THREAD

**Issue by Cyansilver** [strapi/strapi#11714]
### Create a new collection type not work

Create a new collection type button not responding

### Steps to reproduce the behavior

1. Create a new project strapi (v4.0.0) via yarn
2. Go to content builder plugin
3. Click on Create a new collection type

### Expected behavior

- Can see the form to create new collection type

### System

- Node.js version: v12.22.7
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: sqlite3 5.0.2 
- Operating system:  Ubuntu 18

**Comment by Cpaczek** [comment]
Maybe try updating your node to 14. I was not able to reproduce this issue. Is there an error in console? are you a super-admin?

**Comment by derrickmehaffy** [comment]
Make sure you are using `yarn develop` or `npm run develop` and not `start`

Works fine on Node 12, 14, and 16

![image](https://user-images.githubusercontent.com/8593673/144076790-259dc323-8476-4752-a9eb-e74718138fa9.png)

**Comment by Cyansilver** [comment]
Hi, I updated to node 14 but still the same, no console error:

```test-cms % yarn develop
yarn run v1.22.17
warning ../package.json: No license field
$ strapi develop

 Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Wed Dec 01 2021 09:54:10 GMT+0900 (Japan Standa… │
│ Launched in        │ 912 ms                                           │
│ Environment        │ development                                      │
│ Process PID        │ 266                                              │
│ Version            │ 4.0.0 (node v14.18.0)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available                                                            

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

[2021-12-01 09:57:02.572] http: GET /content-manager/components (37 ms) 200
[2021-12-01 09:57:02.589] http: GET /content-manager/content-types (38 ms) 200
[2021-12-01 09:57:04.865] http: GET /content-type-builder/components (22 ms) 200
[2021-12-01 09:57:04.878] http: GET /content-type-builder/content-types (33 ms) 200
[2021-12-01 09:57:04.890] http: GET /content-type-builder/reserved-names (42 ms) 200
```

And I noticed my edition is community and yours is enterprise, not really sure it is the issue?

**Comment by derrickmehaffy** [comment]
> Hi, I updated to node 14 but still the same, no console error, I'm a super-admin:
> 
> ```
> yarn run v1.22.17
> warning ../package.json: No license field
> $ strapi develop
> 
>  Project information                                                          
> 
> ┌────────────────────┬──────────────────────────────────────────────────┐
> │ Time               │ Wed Dec 01 2021 09:54:10 GMT+0900 (Japan Standa… │
> │ Launched in        │ 912 ms                                           │
> │ Environment        │ development                                      │
> │ Process PID        │ 266                                              │
> │ Version            │ 4.0.0 (node v14.18.0)                            │
> │ Edition            │ Community                                        │
> └────────────────────┴──────────────────────────────────────────────────┘
> 
>  Actions available                                                            
> 
> Welcome back!
> To manage your project 🚀, go to the administration panel at:
> http://localhost:1337/admin
> 
> To access the server ⚡️, go to:
> http://localhost:1337
> 
> [2021-12-01 09:57:02.572] http: GET /content-manager/components (37 ms) 200
> [2021-12-01 09:57:02.589] http: GET /content-manager/content-types (38 ms) 200
> [2021-12-01 09:57:04.865] http: GET /content-type-builder/components (22 ms) 200
> [2021-12-01 09:57:04.878] http: GET /content-type-builder/content-types (33 ms) 200
> [2021-12-01 09:57:04.890] http: GET /content-type-builder/reserved-names (42 ms) 200
> ```
> 
> And I noticed my edition is community and yours is enterprise, not really sure it is the issue?

Should have nothing to do with license level no. But I need more information, can you pull some info from your F12 menu in your browser, specifically from the network tab. Look through some of the requests when you click on the CTB and provide some screenshots?
