### ISSUE TITLE
Cannot update to strapi 4

### ISSUE THREAD

**Issue by sarunluitel** [strapi/strapi#11725]
## Bug report
changed strapi version on my project to 4.0.0 eg: `"strapi": "4.0.0",`

### Describe the bug
Running npm install after this change gives: `npm ERR! notarget No matching version found for strapi@4.0.0.`

- Node.js version: v16.13.0
- NPM version:
- Operating system: WSL 2 (ubuntu on windows 10)

**Comment by derrickmehaffy** [comment]
At the moment there are no migration guides from v3-Stable to v4-Stable. These will be coming soon!

https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html#v4-stable-guides

**Comment by paddotk** [comment]
@derrickmehaffy What about the instructions here? https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html
It mentions 4.0.0 and 4.0.1 explicitly.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy What about the instructions here? https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html
> It mentions 4.0.0 and 4.0.1 explicitly.
> 
> Also, do you perhaps have an estimate of when the migration guide will be updated for v4?

I wrote that just to make it clear how you update minor versions, 4.0.1 doesn't even exist yet.

Best estimate I can give right now is probably sometime in January
