### ISSUE TITLE
v4 infite loops when calling current function with strapi api

### ISSUE THREAD

**Issue by bidoubiwa** [strapi/strapi#11733]
### Describe the bug

⚠️ Maybe not a bug?

The global `strapi` API in plugins gives the possibility to access any code I have exported through the `strapi-server.js`. Which means that if I call the function in which I'm, it creates an infinite loop

### Steps to reproduce the behavior

1. Create a controller as follows
```js
function getCollections(ctx) {
  console.log('Another loop wiii')
  console.log(
    strapi
      .plugin('meilisearch')
      .controller('meilisearchController')
      .getCollections()
  )
}

module.exports = {
  getCollections,
}
```
2. Export it in `index.js` in the same directory
```js
'use strict'

const meilisearchController = require('./meilisearch')

module.exports = {
  meilisearchController,
}
```
3. export it in `strapi-server.js`

```js
const controllers = require('./server/controllers')

module.exports = {
  controllers,
}
```
4. `yarn develop`

### Expected behavior

I guess no infinite loop

### Screenshots

<img width="745" alt="Screenshot 2021-11-30 at 20 41 12" src="https://user-images.githubusercontent.com/33010418/144117014-2d951944-9ade-41fc-a0a4-61319a145233.png">

### Code snippets

See above

### System

- Node.js version: v14
- NPM version: 6.14
- Strapi version: 4.0.0-beta.17
- Database: sqlite
- Operating system: macos

**Comment by derrickmehaffy** [comment]
@soupette / @alexandrebodin not sure if this classifies as a bug

**Comment by alexandrebodin** [comment]
Hi, no it doesn't qualify as a bug. You can create infinite loops with any function that call itself. That's not something we can prevent. on our side. I'm going to close this as it's just a javascript feature
