### ISSUE TITLE
Blank screen after quickstart installation

### ISSUE THREAD

**Issue by Felpat0** [strapi/strapi#11730]
### Describe the bug
After the quickstart installation, the page http://localhost:1337/admin is automatically opened, but it's completely empty. The console prints the error:

> Uncaught ReferenceError: regeneratorRuntime is not defined
>     at main.82edf255.js:8576
>     at Object.423 (main.82edf255.js:8576)
>     at e (main.82edf255.js:8576)
>     at Object.1261 (main.82edf255.js:8576)
>     at e (main.82edf255.js:8576)
>     at Object.9321 (main.82edf255.js:8576)
>     at e (main.82edf255.js:8576)
>     at main.82edf255.js:8576
>     at main.82edf255.js:8576
>     at Object.94344 (main.82edf255.js:8576)

### Steps to reproduce the behavior

Run `npx create-strapi-app@latest my-project --quickstart`

I also tried running `npm run build` then `npm run develop`, same issue.
### Expected behavior

I should see the admin panel

### System

- Node.js version: v12.22.1 (I also tried Node 14 and 16)
- NPM version: 7.21.1
- Strapi version: v4
- Database: sqlite3 5.0.0
- Operating system: MacOs Big Sur

Thanks!

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-mysql-admin-panel-not-work/12954/3

**Comment by KlaiZed** [comment]
I work on Windows, getting rid of the parent folder with a capital letter in the path to the strapi application helped me.  It turns out that this error occurs if any parent folder has a capital letter in its name.  It looks like babel at such moments simply cannot correctly build a project.

**Comment by Felpat0** [comment]
> 

Unfortunately this doesn't work on MacOS :/

**Comment by Felpat0** [comment]
> I work on Windows, getting rid of the parent folder with a capital letter in the path to the strapi application helped me. It turns out that this error occurs if any parent folder has a capital letter in its name. It looks like babel at such moments simply cannot correctly build a project.

Unfortunately this doesn't work on MacOS :/

**Comment by Pierre-Mike** [comment]
I have the same issue on Big Sur and I just upgrade to Monterey  
I have still this issue 
I tried Yarn, Npx. 

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at main.827b5d76.js:9454
    at Object.423 (main.827b5d76.js:9454)
    at e (main.827b5d76.js:9454)
    at Object.1261 (main.827b5d76.js:9454)
    at e (main.827b5d76.js:9454)
    at Object.9321 (main.827b5d76.js:9454)
    at e (main.827b5d76.js:9454)
    at main.827b5d76.js:9454
    at main.827b5d76.js:9454
    at Object.94344 (main.827b5d76.js:9454)
```

- node = v14.15.4
- yarn = 1.22.17
- strapi = 4.0.0
- npm = 8.1.4
- OSX = BigSur And Monterey
- pwd = /Users/pierre-mike/Developer/github/pierre-mike/strapi-test/my-project

**Comment by Pierre-Mike** [comment]
SO 

> > I work on Windows, getting rid of the parent folder with a capital letter in the path to the strapi application helped me. It turns out that this error occurs if any parent folder has a capital letter in its name. It looks like babel at such moments simply cannot correctly build a project.
> 
> Unfortunately this doesn't work on MacOS :/

It does 

I installed this in `/tmp/test-strapi`

and it works

**Comment by Pierre-Mike** [comment]
[I think is lonk](https://github.com/strapi/strapi/issues/11730

this is related

**Comment by derrickmehaffy** [comment]
I'm gonna close this one in favor of https://github.com/strapi/strapi/issues/11835 (even though this is older) simply because the other issue has a bit more information.
