### ISSUE TITLE
Can't update user role by api

### ISSUE THREAD

**Issue by makkahwi** [strapi/strapi#11735]
All I'm trying to do is submit user role through the applicant & api calls

Strapi route to update user is "/users/:id", yet when I send a new role id it doesn't update it

**Comment by kasonde** [comment]
Confirmed in v4
Hello @makkahwi , please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by derrickmehaffy** [comment]
This is intended for security, modification would require modifying the service.
