### ISSUE TITLE
Decimal fields being created as DECIMAL(10,0) in MYSQL 5.7 (0 precision)

### ISSUE THREAD

**Issue by peder1001** [strapi/strapi#1173]
**Informations**
- **Node.js version**: 8.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0
- **Database**: MySQL 5.7
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
When creating a decimal field, the field ends up with Datatype DECIMAL(10,0) in MYSQL.

**Steps to reproduce the problem**
In content type builder, add a new field of type decimal and save.

**What is the expected behavior?**
I expect at least 2 decimal places precision. DECIMAL(10,2).
I tried to set this manually in MYSQL after I created the the field. This worked fine.

But as soon as I edit an item using content manager (for example I change price 10.02 to 10.03, which is a decimal field), and save, then this set the database back to DECIMAL(10,0).

**Suggested solutions**
Allow users in advanced settings to specify the precision, or have a smart default.
Is this a bug? Or as intended?

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by peder1001** [comment]
Will try the following and see if it helps.

@ node_modules\strapi-bookshelf\lib\index.js

from:

 case 'float':
                          case 'decimal':
                            type = attribute.type;
                            break;

to:

                          case 'float':
                            type = attribute.type;
                          break;
                          case 'decimal':
                            type = 'decimal(10,2)';

**Comment by peder1001** [comment]
^^ this fixed my problem, but unsure of correct solution for others. Something to consider in your generic fix.

**Comment by derrickmehaffy** [comment]
@peder1001 you can use the float type which will use the `double` field type. It will give you the precision your looking for.

**Comment by peder1001** [comment]
Maybe float is better for my case anyway. Thanks for the suggestion. But is this as intended that decimals should be added as 10,0 for mysql?
