### ISSUE TITLE
i submit media (images) in admin panel its submit successfullt in content handler its show very well in our content but when we hit api route to get data images data not show in response kindly guide me

### ISSUE THREAD

**Issue by sadiq5566** [strapi/strapi#11746]
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
