### ISSUE TITLE
Runtime fails "randomly"

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#11741]
### Describe the bug

The runtime fails from time to time for no obvious reason (sorry for that).
It seemed like it failed when attempting to log in first, when the database isn't up "yet". However I switched to a permanent running server, so this can't be  the case. This night it failed at 1 am. I am pretty sure nobody was using it at that time.

Does only occure on production (sorry again).

error:
```bash
select "t0".*, "t0"."id" from "admin_users" as "t0" where ("t0"."id" = $1) limit $2 - Connection terminated unexpectedly
```

### Steps to reproduce the behavior

1. Let the server run over night

### Expected behavior

No runtime errors.

### System

- Node.js version: v14.15.3
- NPM version: 7.17.0
- Strapi version: 4.0.0-beta.22
- Database: postgres 14
- Operating system:  fedora

package.json
```json
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {
    "pg-connection-string": "^2.5.0"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "4.0.0-beta.22",
    "@strapi/plugin-i18n": "4.0.0-beta.22",
    "@strapi/plugin-users-permissions": "4.0.0-beta.22",
    "@strapi/strapi": "4.0.0-beta.22",
    "pg": "^8.7.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "d6e21050-b511-4fc7-b221-b0d22952984e"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by kasonde** [comment]
Hello @tw1t611, by the looks of things, signs point to the connection between your database and your application. Is there any configuration you know of that limit connection time to the database?

**Comment by tw1t611** [comment]
As far as I know, there are no time limits. Other limits also shouldn't caused the issue.

I am using postgres 14 within a docker container with default configuration.
Both the strapi and database server are running on permanent instances on render (hoster).

Specs of the database server:
RAM 1 GB
CPU 1
Storage 16 GB

The metrics show, that the servers are not running at cap.
The setup is not running on production and there was nobody working in strapi at the time of the error.

database.js
```js
...
     connection: {
        client: "postgres",
        connection: {
          host,
          port,
          database,
          user,
          password,
          ssl: false,
        },
      }
...
```

The error displays some more info, if that helps:
```bash
Dec 1 02:05:14 PM  [2021-12-01 13:05:14.064] error: select "t0".*, "t0"."id" from "admin_users" as "t0" where ("t0"."id" = $1) limit $2 - Connection terminated unexpectedly
Dec 1 02:05:14 PM  Error: select "t0".*, "t0"."id" from "admin_users" as "t0" where ("t0"."id" = $1) limit $2 - Connection terminated unexpectedly    at Connection.<anonymous> (/opt/render/project/src/strapi/node_modules/pg/lib/client.js:132:73)    at Object.onceWrapper (events.js:482:28)    at Connection.emit (events.js:376:20)    at Connection.emit (domain.js:470:12)    at Socket.<anonymous> (/opt/render/project/src/strapi/node_modules/pg/lib/connection.js:57:12)    at Socket.emit (events.js:376:20)    at Socket.emit (domain.js:470:12)    at TCP.<anonymous> (net.js:673:12)
```

**Comment by kasonde** [comment]
Could you possibly take a look at running the application in an environment that meets the minimum recommended system requirements for Strapi. 1GB of RAM and a Single CPU might not leave the system much room to support itself and the two applications currently running on it. Here's a [link](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html#general-guidelines)

**Comment by tw1t611** [comment]
I posted the database server. Strapi is running in a different container.

These are the specs, which strapi runs on:
RAM 3 GB
CPU 1.5

The requirements should be fulfilled. However, I will upgrade to a bigger server and tell you, if the problem remains.

**Comment by tw1t611** [comment]
Good news. I didn't get the runtime error on
RAM 4 GB
CPU 2

That might be a thing that you can optimize in future, but the issue itself was solved. :)
Thank for your help.

**Comment by tw1t611** [comment]
Hey, the error came up again with the release version.

**Comment by derrickmehaffy** [comment]
I'm resetting this back to closed, this clearly isn't a code bug but an environmental issue.

Check your free resources and see if you need to upgrade server specs.
