### ISSUE TITLE
[v4] components are not visible in REST API

### ISSUE THREAD

**Issue by z33n00n** [strapi/strapi#11744]
### Describe the bug

We created a bunch of content-types and also created components like we did before in 3.6.8. In the admin UI everything looks smooth, but in the API the component data is not in.

### Steps to reproduce the behavior

1. Go to  Admin UI and create simple types and components
2. Create some sample data
3. Go to the REST API and try to access the data. Direct fields are in, components not.

### Expected behavior

I expect, that the components are in the response

### Screenshots

![image](https://user-images.githubusercontent.com/4699203/144222210-e06733fc-db70-4159-973b-acf86d1bb878.png)
![image](https://user-images.githubusercontent.com/4699203/144222652-408673fc-b0a8-4f7d-8e79-afc2bc21b942.png)
![image](https://user-images.githubusercontent.com/4699203/144222727-0ef169c6-8e0a-4925-afb1-5b04d9e19ee5.png)

### Code snippets

Its the default configuration and I there are no private fields

### System

- Node.js version: 12.22.7
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: mariadb
- Operating system: ubuntu

### Additional context

it worked well in 3.6.8

Thank you all for doing a great job!

**Comment by be90728** [comment]
try to add 'populate=*' in your query params.
e.g `/api/overviews/?fields=*&populate=*`

**Comment by kasonde** [comment]
@z33n00n as @be90728 mentioned, you have to explicitly populate them in your api request. Find more information at the link in the comment above.

**Comment by krazylearner** [comment]
I got the same issue. Why you have removed the old functionality? I spend 1 hour trying to figure out whats wrong. A component should be sent in response by default.

**Comment by derrickmehaffy** [comment]
> I got the same issue. Why you have removed the old functionality? I spend 1 hour trying to figure out whats wrong. A component should be sent in response by default.

Short answer is performance, v4 includes multiple breaking changes
