### ISSUE TITLE
UploadFile is null, using GraphQL

### ISSUE THREAD

**Issue by OwenCalvin** [strapi/strapi#1174]
**Informations**
- **Node.js version**:  
8.11.1
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.1.3
- **Database**:
MongoDB
- **Operating system**:
Windows 10

**What is the current behavior?**
FileUpload is null when we query a object with two or more levels
But when we query the first level of the UploadImage we can get his attributes
[https://ibb.co/m7uJYy](url)
[https://ibb.co/dME2ty](url)
(Cannot upload images directly on the issue...)

**Steps to reproduce the problem**
Querying some objects that has some objects and the ImageFile will be null

**What is the expected behavior?**
ImageUpload should have a some properties

**Suggested solutions**
Don't know how to fix it

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by dsheyp** [comment]
same here....


**Steps to reproduce the problem**

this query returns an empty image field:
http://localhost:1337/graphql?query={slides{title%20index%20bgimages{title%20image{url}}}}

this query returns a correctly populated image field:
http://localhost:1337/graphql?query={bgimages{title%20image{url}}}

**Comment by kamalbennani** [comment]
Any updates on this issue ?

**Comment by tewedaj** [comment]
is it working now? i think i got the same problem, i added 
```
query{
  orders(limit: 10,where:{test_contains:"yes"}){
    test
		product{
   			productImage{
         url
        }

    }
  }
}
```

and i got something like `"product":null`
