### ISSUE TITLE
Strapi v4.0 Sendgrid Plugin not showing up in email settings

### ISSUE THREAD

**Issue by alexgrant999** [strapi/strapi#11757]
I install Strapi v4.0 with mySql.

Then install this package:
https://www.npmjs.com/package/@strapi/provider-email-sendgrid

then add the plugins.js file in the config folder with this code:
`module.exports = ({ env }) => ({
 email: {
provider: 'sendgrid',
    providerOptions: {
      apiKey: env('SENDGRID_API_KEY'),
    },
    settings: {
      defaultFrom: 'alex@xxx',
      defaultReplyTo: 'alex@xxx',
    },
  },
});
`

However, when I restart and go back to the email settings, I am not able to choose sendgrid, only sendmail..  I have tried with the old plugin as well!

**Comment by enflam3** [comment]
Yes, Iam also having this issue and would like to know if there is any workaround...

**Comment by iicdii** [comment]
I cannot reproduce it. Did you install package by `yarn add @strapi/provider-email-sendgrid`?

<img width="699" alt="" src="https://user-images.githubusercontent.com/4951716/144480535-e9723bf6-9768-4568-b526-d1b0cff3a030.png">

**Comment by alexgrant999** [comment]
@iicdii, yes I tried is using both of these in turn, neither allowed me to choose sendgrid from the settings.



strapi-provider-email-sendgrid
@strapi/provider-email-sendgrid

Still not able to change the email Provider! I am using a m1 macbook pro.


<img width="1112" alt="Screen Shot 2021-12-03 at 7 18 47 am" src="https://user-images.githubusercontent.com/4098580/144496794-6af3b0cf-014d-473c-a499-e302691d5db1.png">

**Comment by enflam3** [comment]
Yes I am also having same unchangeable provider:
![image](https://user-images.githubusercontent.com/47244576/144503329-07713c69-b8df-4617-b396-4f6c796694fa.png)
by following this guide in the [link](https://docs.strapi.io/developer-docs/latest/plugins/email.html#configure-the-plugin)
![image](https://user-images.githubusercontent.com/47244576/144504032-2de58c3b-04d8-46aa-81d2-0ac3e5796161.png)

Windows 10
Node v16.13.1

rebuilding and restarting dev not helping =/

**Comment by derrickmehaffy** [comment]
We mention this in our Discord Here: https://discord.com/channels/811989166782021633/811989167357689918/915661746981724260

But I'll copy the message here:

If you are having Issues with Upload Providers on v4, please see this WIP Documentation: https://documentation-git-fixes-providers-strapijs.vercel.app/developer-docs/latest/plugins/upload.html#upload
Likewise see this PR for updated Upload provider configs: https://github.com/strapi/strapi/pull/11750

**Comment by alexgrant999** [comment]
@derrickmehaffy This is not Upload Provider, it is sendgrid provider., please see message thread. 
Actually spent hours trying to get it to work.  To be honest, don't think you should be elevating v4 to production until all the bugs are worked out, I probably will be going to v3 until you have worked it out, or use another product.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy This is not Upload Provider, it is sendgrid provider., please see message thread. Actually spent hours trying to get it to work. To be honest, don't think you should be elevating v4 to production until all the bugs are worked out, I probably will be going to v3 until you have worked it out, or use another product.

Sorry I mis-spoke but that documentation link and PR also include email providers. Your settings need to be wrapped in a `config: {}` object

**Comment by derrickmehaffy** [comment]
> To be honest, don't think you should be elevating v4 to production until all the bugs are worked out

We specifically are not recommending it for our Enterprise users, those in the community are familiar enough with bleeding edge releases and we fully expected that we missed some bugs. It happens in open source.

**Comment by alexgrant999** [comment]
@derrickmehaffy @enflam3 @iicdii 
Yes, adding the config key fixed it, the documentation that I used to install 
https://www.npmjs.com/package/@strapi/provider-email-sendgrid
has the incorrect plugins.js code, I suggest you amend this asap so that others do not spend hours trying to get it to work..




module.exports = ({ env }) => ({
  // ...
  email: {
    provider: 'sendgrid',
    providerOptions: {
      apiKey: env('SENDGRID_API_KEY'),
    },
    settings: {
      defaultFrom: 'myemail@protonmail.com',
      defaultReplyTo: 'myemail@protonmail.com',
    },
  },
  // ...
});

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy @enflam3 @iicdii Yes, adding the config key fixed it, the documentation that I used to install https://www.npmjs.com/package/@strapi/provider-email-sendgrid has the incorrect plugins.js code, I suggest you amend this asap so that others do not spend hours trying to get it to work..
> 
> module.exports = ({ env }) => ({ // ... email: { provider: 'sendgrid', providerOptions: { apiKey: env('SENDGRID_API_KEY'), }, settings: { defaultFrom: '[myemail@protonmail.com](mailto:myemail@protonmail.com)', defaultReplyTo: '[myemail@protonmail.com](mailto:myemail@protonmail.com)', }, }, // ... });

I'm aware, that's what that PR I linked fixes :wink: 

see: packages/providers/email-sendgrid/README.md in that PR, the updated readmes will go live when we release v4.0.1 We can't just update them without releasing a new version and there are a lot of other fixes we need to do for v4.0.1

**Comment by enflam3** [comment]
Wrapping code with config: { } worked!
Thanks!
