### ISSUE TITLE
What is the correct configuration to connect psotgres on v4

### ISSUE THREAD

**Issue by RezaRahmati** [strapi/strapi#11759]
Hi there

on v3.6 I have had this configuration to connect to postgres on gcloud, and it's working with no issue , (pay attention to host instead of socketPath, with socket path getting `Error: connect ECONNREFUSED 127.0.0.1:5432`) , anyway this is working perefctly

```
module.exports = ({ env }) => {
        return {
            defaultConnection: 'default',
            connections: {
                default: {
                    connector: 'bookshelf',
                    settings: {
                        client: 'postgres',
                        host: `/cloudsql/${env('INSTANCE_CONNECTION_NAME')}`,
                        database: env('DATABASE_NAME'),
                        username: env('DATABASE_USERNAME'),
                        password: env('DATABASE_PASSWORD'),
                    },
                    options: {},
                },
            },
        }
 }

```

I created a new project using v4, and I noticed the default database.js file is changed, so I changed my config to this
```
module.exports = ({ env }) => {

        return {
            connection: {
                client: 'postgres',
                connection: {
                    host: `/cloudsql/${env('INSTANCE_CONNECTION_NAME')}`,
                    database: env('DATABASE_NAME'),
                    username: env('DATABASE_USERNAME'),
                    password: env('DATABASE_PASSWORD'),
                }
            },
        }
```
using this I get this error : `Error: connect ENOENT /cloudsql/strapi-22:us-central1:strapi-db/.s.PGSQL.5432`

I changed it to socketPath instead of host and I get another error

then I changed it to IP and port as below
```
module.exports = ({ env }) => {
        return {
            connection: {
                client: 'postgres',
                connection: {
                    host: 'my db ip here',
                    port: 5432,
                    database: env('DATABASE_NAME'),
                    username: env('DATABASE_USERNAME'),
                    password: env('DATABASE_PASSWORD'),
                }
            },
        }
```
Now I get this error: `KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

The documentation [here ](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html#configure-the-database) also is old, seems it's for v3 

Any help much appreciated

**Comment by IHIutch** [comment]
I believe `username` was changed to `user` in v4. At least, that's whats working for me.

Try
```
module.exports = ({ env }) => {
        return {
            connection: {
                client: 'postgres',
                connection: {
                    host: 'my db ip here',
                    port: 5432,
                    database: env('DATABASE_NAME'),
                    user: env('DATABASE_USERNAME'),
                    password: env('DATABASE_PASSWORD'),
                }
            },
        }
        
```

**Comment by IHIutch** [comment]
The docs might need to be updated: `user` is shown in the sample config [here](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-examples).

But `username` is mentioned further up in [connection parameters](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-structure)

**Comment by derrickmehaffy** [comment]
> The docs might need to be updated: `user` is shown in the sample config [here](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-examples).
> 
> But `username` is mentioned further up in [connection parameters](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-structure)

Can you open an issue on the documentation repo please: https://github.com/strapi/documentation

Correct structure is:

```js
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', '127.0.0.1'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'strapi'),
      user: env('DATABASE_USERNAME', 'strapi'),
      password: env('DATABASE_PASSWORD', 'strapi'),
      schema: env('DATABASE_SCHEMA', 'public'), // Not required
      ssl: {
        rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
      },
    },
    debug: false,
  },
});
```

**Comment by RezaRahmati** [comment]
update I tried and changed `username` to `user`

```
            connection: {
                client: 'postgres',
                connection: {
                    host: `/cloudsql/${env('INSTANCE_CONNECTION_NAME')}`,
                    database: env('DATABASE_NAME'),
                    user: env('DATABASE_USERNAME'),
                    password: env('DATABASE_PASSWORD'),
                }
            },
```
I get this error `Error: connect ENOENT /cloudsql/strapi-project:us-central1:strapi-db/.s.PGSQL.5432
    at PipeConnectWrap.afterConnect [as oncomplete]`
    
```
            connection: {
                client: 'postgres',
                connection: {
                    host: 'myip',
                    port: 5432,
                    database: env('DATABASE_NAME'),
                    user: env('DATABASE_USERNAME'),
                    password: env('DATABASE_PASSWORD'),
                }
            },
```
I get this error `KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

**Comment by derrickmehaffy** [comment]
You probably need to adjust the pool settings, the documentation had references for that but I'd recommend checking the Knex.js /Tarn.js documentation (Tarn is specifically for handling those pool settings).

**Comment by RezaRahmati** [comment]
Finally I found what is wrong.

My final config is like this
```
            connection: {
                client: 'postgres',
                connection: {
                    host: `/cloudsql/${env('INSTANCE_CONNECTION_NAME')}`,
                    database: env('DATABASE_NAME'),
                    user: env('DATABASE_USERNAME'),
                    password: env('DATABASE_PASSWORD'),
                }
            },
```

The error I was getting `KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?` was related to setting the cloud sql connection in google cloud run configuration. Seems if we don't set it cloud run doesn't have access to cloud sql
