### ISSUE TITLE
V4 Method Not Allowed when hitting /auth/local

### ISSUE THREAD

**Issue by WojtekHerisz** [strapi/strapi#11756]
### Describe the bug

After a fresh installation I cannot hit /auth/local because of getting error 405: Method Not Allowed

### Steps to reproduce the behavior

1. Make fresh installation of Strapi with quickstart
2. Add 1 test user
3. Try to make POST request to /auth/local according to https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#login

### Expected behavior

Get authentication data or get rejected due to wrong username/password

### Screenshots

![2021-12-01 21_11_55-Postman](https://user-images.githubusercontent.com/23483015/144306914-4cc2bc26-650b-4601-a1e9-e41067eb3106.png)

![2021-12-01 21_11_44-Postman](https://user-images.githubusercontent.com/23483015/144306989-8bb56d6f-66f2-4e2a-a17f-f9e9a1918f3b.png)

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: v4.0.0
- Database: sqlite
- Operating system: Windows

**Comment by fabriciomelosilva** [comment]
I have exactly the same problem

**Comment by fabriciomelosilva** [comment]
discovered the problem, the route is wrong.
just access it this way:

http://localhost:1337/api/auth/local/

**Comment by WojtekHerisz** [comment]
> discovered the problem, the route is wrong. just access it this way:
> 
> http://localhost:1337/api/auth/local/

Will it stay like this in next updates of V4? If yes, I think it it should be fixed in docs.

**Comment by derrickmehaffy** [comment]
Yes all content APIs are prefixed by `/api` this is configurable in the `./config/api.js` but it's no longer possible to mount on `/`.

Documentation issues should be reported on https://github.com/strapi/documentation

Marking as closed as there is no code issue.
