### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by OwenCalvin** [strapi/strapi#1175]
**Informations**
- **Node.js version**:
8.11.1
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.1.3
- **Database**:
MongoDB
- **Operating system**:
Windows

**What is the current behavior?**
The returned error message isn't clear

**Steps to reproduce the problem**
Post an object that is already exist and the field that we insert duplicate data is "unique"
We get (returned response):
```
...
data: {
     message: 'An internal server error occurred',
     statusCode: 500,
     error: 'Internal Server Error'
 }
```

Strapi console:
```
E11000 duplicate key error collection: readsan.saner index: username_1 dup key: { : "owen" }
[2018-05-12T19:51:27.984Z] debug POST /saner
```

**What is the expected behavior?**
To return a better message to know if the data is duplicated or if the server occurred a real error 

**Suggested solutions**
Change the returned error messages

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@OwenCalvin Node 9 or above is required to use strapi Alpha 12

**Comment by lauriejim** [comment]
Hello @, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll be glad to count you as one of our contributors!

Probably just have to catch this error and send the correct error code.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by lauriejim** [comment]
This issue is completely related to this one https://github.com/strapi/strapi/issues/1189.

**Comment by derrickmehaffy** [comment]
@lauriejim I think we need to reopen this issue, while the direct error message here is about unique type. I think the 500 error needs to include more information as to what the error is.

**Comment by leafnetjake** [comment]
I agree with @derrickmehaffy 

An interim solution I've used is to send a get request prior to each post/put for each field. This is rather taxing and could be addressed better.

```
data: {…}
​​error: "Internal Server Error"
​​message: "An internal server error occurred"
​​statusCode: 500
```
​strapi console
```
message: 'Path `name` is required.',
name: 'ValidatorError',
properties: [Object],
kind: 'required',
path: 'name',
value: '',
reason: undefined,
'$isValidatorError': true
```

**Comment by lauriejim** [comment]
Please can you open a new clean issue, with detail need please.

**Comment by rishisahu20** [comment]
### You can handle your error status and error code by this==>

`  create: async (ctx) => {
     let values = ctx.request.body;
      const relations = _.pick(values, Business.associations.map(ast => ast.aas));
      const data = _.omit(values, Business.associations.map(ast => ast.alias));
      try{
      const entry = await Business.create(data);
      return Business.updateRelations({ _id: entry.id, values: relations });
      }
      catch(error){
        let values=Object.values(error.errors)
        console.log('Error Field===========>',values[0].message)
        return ctx.response.badData([data], values[0].message)
      }
  }`

HTTP 4xx Errors
ctx.response.badRequest([message], [data])
ctx.response.unauthorized([message], [scheme], [attributes])
ctx.response.paymentRequired([message], [data])
ctx.response.forbidden([message], [data])
ctx.response.notFound([message], [data])
ctx.response.methodNotAllowed([message], [data], [allow])
ctx.response.notAcceptable([message], [data])
ctx.response.proxyAuthRequired([message], [data])
ctx.response.clientTimeout([message], [data])
ctx.response.conflict([message], [data])
ctx.response.resourceGone([message], [data])
ctx.response.lengthRequired([message], [data])
ctx.response.preconditionFailed([message], [data])
ctx.response.entityTooLarge([message], [data])
ctx.response.uriTooLong([message], [data])
ctx.response.unsupportedMediaType([message], [data])
ctx.response.rangeNotSatisfiable([message], [data])
ctx.response.expectationFailed([message], [data])
ctx.response.teapot([message], [data])
ctx.response.badData([message], [data])
ctx.response.locked([message], [data])
ctx.response.preconditionRequired([message], [data])
ctx.response.tooManyRequests([message], [data])
ctx.response.illegal([message], [data])
HTTP 5xx Errors
ctx.response.badImplementation([message], [data]) - (alias: internal)
ctx.response.notImplemented([message], [data])
ctx.response.badGateway([message], [data])
ctx.response.serverUnavailable([message], [data])
ctx.response.gatewayTimeout([message], [data])
#
