### ISSUE TITLE
Extending find core controller: Query parameters are ignored

### ISSUE THREAD

**Issue by Fensterbank** [strapi/strapi#11753]
I followed the [documentation](https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#adding-a-new-controller) on how to extend a core controller by following method 2 on that documentation.

**Our usecase is nothing special:** The `find` controller of a specific entity should only return items, which are referenced (with the `user`-relation) to the current authenticated user.

This does not work anymore in Strapi v4.
I also can use any fantasy parameter I like and strapi won't throw an error, it just returns all data in the database, which could result in a real security issue, if developers used the wrong parameter by mistake.

### Expected behavior

- Setting `ctx.query` should query for specific data like the example in the documentation
- Setting invalid filters should result in a bad request

### Code snippets

```javascript
module.exports = createCoreController('api::publication.publication', ({ strapi }) => ({
  // only own publications can be retrieved
  async find(ctx) {
    ctx.query = { ...ctx.query, 'user.id': ctx.state.user.id, 'notExistingParameter': 'Foo' }

    // Calling the default core action
    const { data, meta } = await super.find(ctx);

    return { data, meta };
  },
}));
```

**Schema:**
```json
{
  "kind": "collectionType",
  "collectionName": "publications",
  "info": {
    "singularName": "publication",
    "pluralName": "publications",
    "displayName": "Publication",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "description": {
      "type": "string"
    },
    "user": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.user",
      "inversedBy": "publications"
    },
    "editions": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::edition.edition",
      "mappedBy": "publication"
    }
  }
}
```

### System

- Node.js version: v14
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: MariaDB
- Operating system: Linux

**Comment by Fensterbank** [comment]
Documentation is really confusing, but this seems to be the right approach to achive this:

```javascript
  async find(ctx) {
    ctx.query = {
      ...ctx.query,
      filters: { ...ctx.query.filters, 'user': ctx.state.user.id }
    }

    // Calling the default core action
    const { data, meta } = await super.find(ctx);

    return { data, meta };
  },
  ```

Closing it.

**Comment by derrickmehaffy** [comment]
> Documentation is really confusing, but this seems to be the right approach to achive this:
> 
> ```js
>   async find(ctx) {
>     ctx.query = {
>       ...ctx.query,
>       filters: { ...ctx.query.filters, 'user': ctx.state.user.id }
>     }
> 
>     // Calling the default core action
>     const { data, meta } = await super.find(ctx);
> 
>     return { data, meta };
>   },
> ```
> 
> Closing it.

Can you specify what's confusing so we can iterate on it and make it more clear? 

Thank you!
