### ISSUE TITLE
API not returning component data

### ISSUE THREAD

**Issue by Solero007** [strapi/strapi#11763]
## Bug report
The api doesn't return component data. Tried SQLite and Postgres

### Describe the bug
When creating a single/ or repeatable component and attach to a content-type the data doesn't get returned in the API (rest)
The schema is correct in the API file.

### Steps to reproduce the behavior

1. Create a new content type, add one field. Then create a component and attach to the new type. 
2. Add data to collection
3. Allow public access to the type 
4. Goto the rest api, view data

### Expected behavior
I'd expect to see the component data, inside the object

### Screenshots
![image](https://user-images.githubusercontent.com/26302508/144405386-596f8f4d-760d-44d7-a428-06588b0737ac.png)
![image](https://user-images.githubusercontent.com/26302508/144405430-5e846024-1ccc-464e-9df4-d39609beb08d.png)

### System

- Node.js version: 14.15.1
- NPM version: 6.14.8
- Strapi version: v4
- Database: postgress/ sqlite
- Operating system: window 10

**Comment by Convly** [comment]
Hi, you need to add `?populate=address` to your URL to return `address` data. (component aren't populated by default)

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population
