### ISSUE TITLE
How to customize queries in strappy? for example how to retrieve custom fields in strapi controller? 

### ISSUE THREAD

**Issue by anuvempally** [strapi/strapi#11761]
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by kvadratpm** [comment]
Hi! You can read about it in the [documentation](https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#implementation).

**Comment by lmartins** [comment]
@anuvempally please try edit your ticket description to describe the actual problem you are running into. As @kvadratpm said you can find most information on the docs, but if you found an actual issue the best chance for your to get meaningful help here is by posting a meaningful question too.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
