### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by joohimks** [strapi/strapi#11764]
### The problem

On two mac devices, with Intel processors. After fresh custom installation with postgres db; I get the following error:
`Building your admin UI with development configuration ...

✔ Webpack
  Compiled successfully in 20.13s

[2021-12-02 16:40:43.109] debug: ⛔️ Server wasn't able to start properly.
[2021-12-02 16:40:43.110] error: connect ECONNREFUSED 127.0.0.1:5432
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

### Steps to reproduce the behavior

1. npx create-strapi-app@latest my-project
2. Custom Install
3. postgres
4. npm run develop
5. See error

### Expected behavior

The application to run smoothly!

### System

- Node.js version: 
- NPM version: 6.14.15
- Strapi version: 
- Database: postgres
- Operating system: OSX

**Comment by iicdii** [comment]
This error generally occurs when Strapi cannot access to your DB. Did you put correct database information in `config/database.js`?

**Comment by derrickmehaffy** [comment]
Indeed @iicdii is correct, this isn't a Strapi issue but your database is refusing the connection. Either due to wrong auth or some other database setting. 

Marking as closed as it's not a code problem with Strapi

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by joohimks** [comment]
> This error generally occurs when Strapi cannot access to your DB. Did you put the correct database information in `config/database.js`?

They're correct. Shouldn't strapi do that with fresh installation?

**Comment by derrickmehaffy** [comment]
> > This error generally occurs when Strapi cannot access to your DB. Did you put the correct database information in `config/database.js`?
> 
> They're correct. Shouldn't strapi do that with fresh installation?

Strapi won't create the database, user, password, and set user permissions on a database. It never has, and most frameworks won't.

You need to create the database, user, and assign permissions on the database for the user.

**Comment by joohimks** [comment]
> > > This error generally occurs when Strapi cannot access to your DB. Did you put the correct database information in `config/database.js`?
> 
> > 
> 
> > They're correct. Shouldn't strapi do that with fresh installation?
> 
> 
> 
> Strapi won't create the database, user, password, and set user permissions on a database. It never has, and most frameworks won't.
> 
> 
> 
> You need to create the database, user, and assign permissions on the database for the user.

My bad. I've used Strapi with docker and it pulls the needful. Problem solved. Thank you
