### ISSUE TITLE
[v4] Error when deploying to Google App Engine

### ISSUE THREAD

**Issue by sccmlkf** [strapi/strapi#11762]
### Describe the bug

I am deploying a new Strapi v4 application to Google App Engine, but I am getting a create directory error.

The error is caused by Google App Engine not uploading an empty folder to the server.

My current solution is to create an empty file in `/database/migrations`.

### Steps to reproduce the behavior

1. `gcloud app deploy app.yaml --project myapi-123456`

### Expected behavior

Deploy success and the application can start in Google App Engine

### Screenshots

![image](https://user-images.githubusercontent.com/82794606/144369161-8ae83113-296f-4e26-9faa-f85c7c58e0b0.png)

### System

- Node.js version: v14
- Strapi version: v4
- Database: PostgreSQL

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by sccmlkf** [comment]
## Bug report

### Describe the bug

I am deploying a new Strapi v4 application to Google App Engine, but I am getting a create directory error.

The error is caused by Google App Engine not uploading an empty folder to the server.

My current solution is to create an empty file in `/database/migrations`.

### Steps to reproduce the behavior

1. `gcloud app deploy app.yaml --project myapi-123456`

### Expected behavior

Deploy success and the application can start in Google App Engine

### Screenshots

![image](https://user-images.githubusercontent.com/82794606/144369161-8ae83113-296f-4e26-9faa-f85c7c58e0b0.png)

### System

- Node.js version: v14
- Strapi version: v4
- Database: PostgreSQL

**Comment by reev-create** [comment]
It seems like Google App Engine does not allow strapi to create folders. 

This issue can be resolved by simply creating a something.txt file inside database/migrations folder to avoid this .
