### ISSUE TITLE
admin UX data confusion issues ? 

### ISSUE THREAD

**Issue by steveinatorx** [strapi/strapi#1176]
**Informations**
- **Node.js version**: 10.0.0
- **npm version**: 6.0.1
- **Strapi version**: Version: 3.0.0-alpha.12.1.3 (node v10.0.0)
- **Database**:  mongo 3.6.4
- **Operating system**: mac osx

**What is the current behavior?**
using the admin content type builder to create a new content type works. But when viewing the content type which is currently empty of objects the UX fills the view with IDs from the User object. 

Refreshing the page on the new content type also causes an error popup. 

Adding a new object also produces an error:  
![screenshot 2018-05-12 16 19 49](https://user-images.githubusercontent.com/4932399/39962339-cefec20c-5600-11e8-9fa8-bea686af28ba.png)

**Steps to reproduce the problem**
create new content type, view content type, create new object of content type

**What is the expected behavior?**

this shouldnt produce an error

**Suggested solutions**

do previous alpha releases have a more stable admin UX ? 

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
@steveinatorx Can you give me your `Advertiver.settings.json` file please.

**Comment by lauriejim** [comment]
I'm not able to reproduce your issue. And I'm not sure to understand your issue very well.

**Comment by steveinatorx** [comment]
Advertiser.settings.json
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "advertiser",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "Name": {
      "type": "string"
    }
  }
}
```

**Comment by steveinatorx** [comment]
so i just did two additional fresh installs and i am seeing the same behavior as above.  I CAN however properly create content types with other names rather than 'Advertisers' which is making me think there is some internal naming clash going on.

**Comment by lauriejim** [comment]
I thin we can link to this issue https://github.com/strapi/strapi/issues/791

**Comment by lauriejim** [comment]
I really can't reproduce your issue.
@steveinatorx can you give me exact steps, click by click what are you doing to have this issue.

**Comment by steveinatorx** [comment]
its the oddest thing - everything in the admin UX works fine - including creating content types and new objects - until i create a new content type called 'advertiser' with the String Field 'Name'. When i try to click the Advertisers menu item - this console error comes up:

![screenshot 2018-05-15 12 47 48](https://user-images.githubusercontent.com/4932399/40080139-f2f42bc6-583e-11e8-911b-387bb586ba61.png)


![screenshot 2018-05-15 12 57 26](https://user-images.githubusercontent.com/4932399/40080397-a625cb96-583f-11e8-8119-1b038d3ba05e.png)

my guess is that this behavior might indeed be related to [#791](https://github.com/strapi/strapi/issues/791) 
For now im just not using the 'advertiser' name for new content type as a workaround

. 
let me know if i can provide you with any more information.

**Comment by derrickmehaffy** [comment]
@lauriejim give me a moment and I'll spin up a fresh one off the current master and the current release build to check

**Comment by derrickmehaffy** [comment]
@lauriejim I think I know the cause here, this may have something to do with a client side ad-blocker. As I have one installed in chrome (ublock origin) and I am getting some odd responses as well and its triggering my ad-blocker:

![image](https://user-images.githubusercontent.com/8593673/40111352-685d032e-58b7-11e8-8c0c-e9a11eff7af1.png)

**Comment by derrickmehaffy** [comment]
@steveinatorx What browser are you using and do you have any adblocking extensions enabled?

**Comment by derrickmehaffy** [comment]
Disabling adblocking allows me to use the adminUI normally: 

![image](https://user-images.githubusercontent.com/8593673/40111491-d5f4d2fe-58b7-11e8-859b-e455577f6570.png)

![image](https://user-images.githubusercontent.com/8593673/40111508-df7f4764-58b7-11e8-91b3-27cd147bacc5.png)

Which makes sense as most adblocking extensions do have some function to trigger and look for `ads`, `advertiser`, ect.

**Comment by abdonrd** [comment]
@lauriejim it works well for me, I can't reproduce the issue.

(I don't use adds bloquer)

**Comment by lauriejim** [comment]
@abdonrd and @derrickmehaffy thank you guys for your feedback!
