### ISSUE TITLE
strapi 4 not show media field in api request

### ISSUE THREAD

**Issue by raheshit** [strapi/strapi#11767]
### Describe the bug
i create  new collection with two field (title , img) and insert one record , but when i request the api for all records just show me 👍 
`{
    "data": [
        {
            "id": 1,
            "attributes": {
                "title": "sdf",
                "createdAt": "2021-12-02T14:08:48.039Z",
                "updatedAt": "2021-12-02T14:10:17.131Z",
                "publishedAt": "2021-12-02T14:10:17.129Z"
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 1
        }
    }
}`

img media field not show in api . please help me!

### System

- Node.js version:  Node LTS version (v14, v16)
- NPM version:
- Strapi version: v4
- Database:sqlite
- Operating system:windows 10

### Additional context

none

**Comment by alexandrebodin** [comment]
Hi there, You need to add `populate=mediaAttributeName or populate=*` in your query params now.

**Comment by raheshit** [comment]
> Hi there, You need to add `populate=mediaAttributeName or populate=*` in your query params now.
thanks a lot. It works
