### ISSUE TITLE
Downloading an image is downloading thumbnail instead of original image

### ISSUE THREAD

**Issue by ihmpavel** [strapi/strapi#11768]
Hi,

URL of the Preview image is `Thumbnail`. That is very handy for smaller file previews, but when I want to download an image in preview I am still downloading the preview image instead of the original image.

https://github.com/strapi/strapi/blob/11f3519710b77042fc58b787acd46288930b510e/packages/core/upload/admin/src/components/EditAssetDialog/PreviewBox/index.js#L160

The line in the code is getting `thumbnail` image, which we use for preview and also for downloading.

**Comment by iicdii** [comment]
Confirmed. I just made PR for it.
