### ISSUE TITLE
Remove foreign key constraints from generated DB schema to allow using PlanetScale DB with Strapi

### ISSUE THREAD

**Issue by benderillo** [strapi/strapi#11775]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

[PlanetScale](https://planetscale.com/) is this new amazing database-as-a-service offering from creators of [Vitess](https://vitess.io/) .

Unfortunately, Strapi users cannot use this service because it does not allow foreign key constraints in the DB schema but Strapi creates the FOREIGN KEY constraints when generates the schema.

They explain why foreign keys are not supported in this article: https://docs.planetscale.com/tutorials/operating-without-foreign-keys

Strapi creates foreign key constraints when creates the db schema from the models, specifically, when creating components but there could be other cases too.

This feature request is to update the code that generates the DB schema to remove the foreign key constraints from it.

### Why is it needed?
To allow Strapi users to use PlanetScale and leverage solid, battle-tested, horizontally scaled MySQL clusters conveniently offered as a managed service.

### Suggested solution(s)

Update schema generating code in Stripe to not to produce foreign key constraints.

### Related issue(s)/PR(s)

None.

**Comment by derrickmehaffy** [comment]
I'm sorry but that database is not supported by us, we have had thousands of users asking for foreign key constraints for years and won't be removing them.

Thank you for the request but it's not one we can fill.

**Comment by danielehrhardt** [comment]
> I'm sorry but that database is not supported by us, we have had thousands of users asking for foreign key constraints for years and won't be removing them.
> 
> Thank you for the request but it's not one we can fill.

More and More Horizontal Scaling Services for MySQL Databases are popping up. 
I wouldn't just close this issue lightly. There are other possibilities like a flag or a config whether foreign key should be used. So please open the issue again. MySQL scaling is an important topic.

**Comment by derrickmehaffy** [comment]
> > I'm sorry but that database is not supported by us, we have had thousands of users asking for foreign key constraints for years and won't be removing them.
> > 
> > Thank you for the request but it's not one we can fill.
> 
> More and More Horizontal Scaling Services for MySQL Databases are popping up. 
> I wouldn't just close this issue lightly. There are other possibilities like a flag or a config whether foreign key should be used. So please open the issue again. MySQL scaling is an important topic.

We have to make choices that best fit the vast majority of our users, foreign key constraints ensure proper data integrity and prevent orphaned entries. We do not plan to support disabling foreign keys, I would advise looking at alternative options.
