### ISSUE TITLE
Global config getter does not return per-environment config.

### ISSUE THREAD

**Issue by MattieBelt** [strapi/strapi#11774]
### Describe the bug

The config getter does not return config that is configured in `/env/{environment}/*.js` as per these [environment configurations docs](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#environment-configurations).

This for example will result in not being able to load an different upload provider as the upload plugin is using `strapi.config.get('plugin.upload', {})`:
https://github.com/strapi/strapi/blob/11f3519710b77042fc58b787acd46288930b510e/packages/core/upload/server/bootstrap.js#L9

### Steps to reproduce the behavior

1. `yarn create strapi-app --quickstart`
2. Create `./config/env/development/plugins.js` with
  ```js
  module.exports = {
    upload: {
      enabled: true,
      config: {
        provider: 'local',
        providerOptions: {
          sizeLimit: 2000000,
        },
      },
    },
  };
  ```
3. Start interactive CLI `yarn strapi console`
4. Try and see differences between `strapi.config.plugins` and `strapi.config.get('plugin.upload', {})`

### Expected behavior

Config getter should respect the per-environment configurations

### Screenshots

![image](https://user-images.githubusercontent.com/31662805/144525082-5ed03763-1262-45dd-8e74-56fdc67c70d4.png)

### System

- Node.js version: `14.16.1`
- NPM version: `7.19.1`
- Yarn version: `1.22.10`
- Strapi version: `4.0.0`
- Database: SQLite (Quickstart)
- Operating system: Ubuntu 20.04

**Comment by iicdii** [comment]
I looked at the plugin code and I couldn't find the one that reads the settings in the `/env/{environment}/*.js` path. I guess it's  under development.
