### ISSUE TITLE
aws-s3 not work in strapi 4

### ISSUE THREAD

**Issue by raheshit** [strapi/strapi#11776]
### Describe the bug

I'm trying to use aws-s3 provider to upload media to S3 bucket, but the images not uploading to S3, instead of that it's uploading to the local server 

### Steps to reproduce the behavior

1.install s3-provider with yarn add strapi-provider-upload-aws-s3
2. edit config/plugins.js and add the following lines
`module.exports = ({ env }) => ({
    upload: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        params: {
          Bucket: env('AWS_BUCKET_NAME'),
        },
      },
    },
  });
`
3.then run build and start project but after the image is uploaded , aws-s3 is empty and image uploaded to local server.
how to change Default provider ?

**Comment by iicdii** [comment]
try `yarn add @strapi/provider-upload-aws-s3` not `yarn add strapi-provider-upload-aws-s3`

**Comment by raheshit** [comment]
> try `yarn add @strapi/provider-upload-aws-s3` instead `yarn add strapi-provider-upload-aws-s3`

i use this yarn add @strapi/provider-upload-aws-s3 but not work.

**Comment by joel611** [comment]
the plugin config structure has changed.

```js
upload: {
    // my-plugin is going to be the internal name used for this plugin
    enabled: true,
    config: {
      // user plugin config goes here
      provider: 'aws-s3',
      providerOptions: ...
    },
  },
```

**Comment by raheshit** [comment]
> the plugin config structure has changed.
> 
> ```js
> upload: {
>     // my-plugin is going to be the internal name used for this plugin
>     enabled: true,
>     config: {
>       // user plugin config goes here
>       provider: 'aws-s3',
>       providerOptions: ...
>     },
>   },
> ```

yes its work . tank a lot

`module.exports = ({ env }) => ({
    upload: {
      enabled: true,
      config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: 'us-east-1',
        endpoint: env('AWS_REGION'),
        s3ForcePathStyle: true,
        params: {
          Bucket: env('AWS_BUCKET_NAME'),
        },
      },
      },
    },
  });
   `
