### ISSUE TITLE
Add full text search option to the API

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1177]
**What is the expected behavior?**

For example, how to add a search option to the `User` content type by `username` & `email`?

Example: `GET /user?search=abdon` (I'm not sure if it's the correct syntax)

And should return to users like:
* `username`: `Abdón`
* `username`: `abdon`
* `username`: `abdonrd`
* `email`: `abdon@domain.com`
* `email`: `name@abdonrd.com`

---

- ✅ I'm sure that this issue hasn't already been referenced.

**Comment by lauriejim** [comment]
@abdonrd You are talking admin search in admin UI and/or with API route ?

> We will work on it soon @Aurelsicoko is making design actually for admin.

Actually we are using filters in generated API. We have `_contains` options. And `_search` is something like `username_contain=abdon` of `email_contain= abdon`.
And that is apply to all attributes of the model you want.

So if you want implement it on your side you will have to transform `params` of this function https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/User.js#L77.
If you use `_search`, you will receive `params._search`. And then you have to map on  `strapi.plugins['users-permissions'].models.user.attributes` to have something like  `params.username_contain=abdon` of `params.email_contain= abdon`.


⚠️ But in any case we will work on it in our side.

**Comment by abdonrd** [comment]
@lauriejim I'm talking about the API, but having it in the admin would not hurt.

**Comment by abdonrd** [comment]
Another good example:

I have a `Document` model with:
* `title`
* `summary`

The user wants to find a document. The search option must also search both fields at the same time.

**Comment by abdonrd** [comment]
I just tried with:

`GET /user?username_contains=abdon&email_contains=abdon`

But it seems to need to match both `contains` conditions.
There are any option right now to allow return with only one match?

**Comment by lauriejim** [comment]
Yes sure, probably have to update `.where` params to handle `or` in this case.

We start to work on filters here https://github.com/strapi/strapi/issues/1204. And will work on search after that.

**Comment by abdonrd** [comment]
@lauriejim ok, thanks Jim!

**Comment by lauriejim** [comment]
In progress on this branch https://github.com/strapi/strapi/tree/ctm-search

**Comment by Aurelsicoko** [comment]
Here a sneak peek of the search bar. I hope you'll like it!

![screen shot 2018-06-11 at 14 27 40](https://user-images.githubusercontent.com/4144726/41231572-bd2b4c2c-6d83-11e8-9c0c-8108b1535b6d.png)

**Comment by abdonrd** [comment]
@lauriejim @Aurelsicoko looks nice! It can be used from the API (not admin UI) too, right? 😁

**Comment by derrickmehaffy** [comment]
@Aurelsicoko beautiful. :heart:

**Comment by lauriejim** [comment]
@abdonrd Nop. It will come in an other PR.
Here for the content manager plugin https://github.com/strapi/strapi/pull/1363

**Comment by derrickmehaffy** [comment]
@abdonrd can you update the issue title to something like `Add search option to the API` since the content-manager search option is already live. :heart:

**Comment by brocgailit** [comment]
This can be accomplished in the API by adding an `or` into the query pipeline.  (This example uses `_q` instead of `_search`)

**Build the `or` Filter** with all string types
```javascript
let search = [{}]; // or() does not allow empty
if (params._q) {
  search = Object.keys(Article.schema.paths)
    .filter( key => Article.schema.paths[key]["instance"] === 'String')
    .map( key => ({[key]: new RegExp(params._q, 'i')}));
  delete params._q;
}
```

**Add to pipeline**
```javascript
return Article
  .find()
  .or(search) // <-- Insert search
  .where(filters.where)
  .sort(filters.sort)
  .skip(filters.start)
  .limit(filters.limit)
  .populate(populate);
```

**Comment by pvk2410** [comment]
Hey There,

Just need some info on this thread.

Are there are samples available to demonstrate the usage of this API for the search? Im specifically looking to invoke these API from postman.

**Comment by lauriejim** [comment]
Hello! By using `localhost:1337/articles?_q=blablabla`

**Comment by pvk2410** [comment]
@lauriejim Thanks , yes this works perfectly!.

Is there a way to extend this search functionality  to search for a specific word / phrase from the content of the assets uploaded in media library?
For example : I have uploaded a word document with content " This is for test". I would like to search for this assets from media library via an API , by giving a part of the file content as the search string.

I tried with  - http://localhost:1337/uploads?_q=Test , but i get a "Not found" response..

Is this possible at all?

**Comment by lauriejim** [comment]
Everything is here in the docs - https://strapi.io/documentation/v3.x/content-api/parameters.html
I'm not sure we have filters for uploads, it doesn't work / exist.

**Comment by 7alip** [comment]
Does Strapi support diacritic sensitive filtering?

For example, my article title is **_"Hâk"_**

```graphql
{
  article(where: { title_contains: "ak" }) {
    title
  }
}
```

It doesn't match with this query

**Comment by lauriejim** [comment]
Strapi doesn't support that. It's only text sensitive.

**Comment by yanotoma** [comment]
> Does Strapi support diacritic sensitive filtering?
> 
> For example, my article title is **_"Hâk"_**
> 
> ```graphql
> {
>   article(where: { title_contains: "ak" }) {
>     title
>   }
> }
> ```
> 
> It doesn't match with this query

Maybe it is too late but you could use search function instead of find
https://strapi.io/documentation/developer-docs/latest/concepts/queries.html#api-reference

in the controller create or override a function and use something like this

```
entities = await strapi.services.article.search({_q: 'ak', _limit:100});
```

the downside is that it will search in all the fields, but it will escape the special characters

**Comment by dellumdeus** [comment]
Why is the `_q` parameter never referenced in the V4 documentation? Also, is there a way to to query like this also in the populated fields of a content type?

**Comment by stephanbogner** [comment]
@dellumdeus 
 I also couldn't find it in the docs but this worked for me:
 `http://localhost:1337/api/projects?_q=design`
 (I checked the browser's network tools in the admin view to see if the parameter is still `_q`)
 
 I think the recommendations for on-site search [on the blog](https://strapi.io/blog/how-to-optimize-strapi-with-on-site-search) are quite overkill for many use cases, so I am glad I found this thread.
