### ISSUE TITLE
how change field label in backend admin strapi 4 or customize style and language

### ISSUE THREAD

**Issue by raheshit** [strapi/strapi#11778]
### Describe the bug

how change field label in backend admin strapi 4 or customize style and language or content builder  field label ?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
