### ISSUE TITLE
UUID crashing the server (ER_DUP_KEYNAME)

### ISSUE THREAD

**Issue by mattf96s** [strapi/strapi#11786]
### Describe the bug

UUID field is crashing the server when making changes to unrelated collections.

```[2021-12-03 18:19:40.472] error: alter table `organisation_onboardings` add unique `organisation_onboardings_designator_unique`(`designator`) - ER_DUP_KEYNAME: Duplicate key name 'organisation_onboardings_designator_unique'
Error: ER_DUP_KEYNAME: Duplicate key name 'organisation_onboardings_designator_unique'
    at Query.Sequence._packetToError ```

### Steps to reproduce the behavior

1. Create a collection with a `uuid` field (not connected to another field)
2. Go to an unrelated collection and add a new field.
3. See error about duplicated key name

### Expected behavior

No error

### System

- Node.js version: v14.18.1 
- NPM version: 6.14.15
- Strapi version: 4.0.0 
- Database: mysql 5.7.23
- Operating system: macOS Big Sur 11.5.2

**Comment by derrickmehaffy** [comment]
UUID is not a valid field type (unless you mean UID but UUID !== UID).

Marking as closed until further information is provided

**Comment by gvocale** [comment]
Running in the same issue as well.

I am removing a relationship from two models (Product and User), but while running the automatic migration in production I get this error:
```
[2022-04-19 13:42:46.708] error: alter table `articles` add unique `articles_slug_unique`(`slug`) - ER_DUP_KEYNAME: Duplicate key name 'articles_slug_unique'
Apr 19 09:42:46 AM  Error: ER_DUP_KEYNAME: Duplicate key name 'articles_slug_unique'
```
The error happens only on production, not on local.
Any idea why?

System
```
Node.js version: v16
Strapi version: 4.1.8
Database: mariadb:10.7.3
```

**Comment by gvocale** [comment]
The same error doesn't happen on localhost where I have no data.

In most of my collections, like `Article`, or `Browse` or `Shop`, I have a field UID `slug`. The field is unique within each collection, but the same slug is used in different collections. For example I have a `Browse` entity with slug `all` and a Shop entity with slug `all`.

I have checked all slugs in Article (I only have 20 entries), and there are no duplicates.

Could it be that when running migrations in production, Strapi is using the slug as unique id and runs into conflicts when two different collections have that same id?

```
MariaDB [mariadb]> show create table articles\G;
*************************** 1. row ***************************
Table: articles
Create Table: CREATE TABLE `articles` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`title` varchar(255) DEFAULT NULL,
`slug` varchar(255) DEFAULT NULL,
`wp_database_id` int(11) DEFAULT NULL,
`content` longtext DEFAULT NULL,
`excerpt` longtext DEFAULT NULL,
`url_web_view` varchar(255) DEFAULT NULL,
`created_at` datetime(6) DEFAULT NULL,
`updated_at` datetime(6) DEFAULT NULL,
`published_at` datetime(6) DEFAULT NULL,
`created_by_id` int(10) unsigned DEFAULT NULL,
`updated_by_id` int(10) unsigned DEFAULT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `articles_slug_unique` (`slug`),
KEY `articles_created_by_id_fk` (`created_by_id`),
KEY `articles_updated_by_id_fk` (`updated_by_id`),
CONSTRAINT `articles_created_by_id_fk` FOREIGN KEY (`created_by_id`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL,
CONSTRAINT `articles_updated_by_id_fk` FOREIGN KEY (`updated_by_id`) REFERENCES `admin_users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4
1 row in set (0.000 sec)
```

As you can see the `slug` is used in the database as UNIQUE KEY.

Is there a way to force Strapi to not use the slug as unique key, but rather a different id?

To add to it, changing all slugs in all collections from `uid` to `string`, **not unique**, did indeed fix the problem with running the migration in production.
