### ISSUE TITLE
[v4] It's impossible to use a custom upload provider

### ISSUE THREAD

**Issue by andreaSimonePorceddu** [strapi/strapi#11782]
### Describe the bug

By configuring a custom upload provider in `config/plugins.js` as described in the documentation [docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider), Strapi is not using the configured provider but instead, it is still using the default one (@strapi/provider-upload-local)

### Steps to reproduce the behaviour

> Note: ENV Variables and the S3 bucket are correctly set

- Install @strapi/provider-upload-aws-s3
- Create the file `config/plugins.js` as explained [here](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider):
```javascript
module.exports = ({ env }) => ({
   upload: {
       provider: 'aws-s3',
       providerOptions: {
       accessKeyId: env('AWS_ACCESS_KEY_ID'),
       secretAccessKey: env('AWS_ACCESS_SECRET'),
       region: env('AWS_REGION'),
       params: {
          Bucket: env('AWS_BUCKET'),
          },
      }
   }
})
```
- run `npm run build && npm run start`  or  `npm run develop`
- Open the admin panel and navigate into the **media libraries** section
- Upload a file

By checking your bucket you will not see any new file, instead, you can see the new file inside the public folder.

I also place a `console.log` inside `node_modules/@strapi/provider-upload-local` upload function
and  inside `node_modules/@strapi/provider-upload-aws-s3` upload function and in fact only `@strapi/provider-upload-local` is executed. 

### Expected behaviour 

It should use the new provider configuration.

### System

- Node.js Version: v14.17.5
- NPM version: 6.14.14
- Strapi version: v4
- Operating system: Mac OS Catalina 10.15.7

### Which alternatives I tried

- Using the old library `strapi-provider-upload-aws-s3` instead of the `@strapi/provider-upload-aws-s3` (not working)
- Create a json configuration inside `src/extensions/upload/config/settings.json` (not working)
- Create a js configuration inside `src/extensions/upload/config/settings.js` (not working)
- Using npm local paths to rename the new library `@strapi/provider-upload-aws-s3` to `strapi-provider-upload-aws-s3` as suggested in the documentation for the scoped packages [docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider) (not working)
- Create a local provider (not working) [docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#create-a-local-provider)

### Workaround 

⚠️ NO NEED TO DO THIS, SCROLL DOWN TO COMMENTS TO SEE THE SOLUTION

I managed to get the aws-s3 provider work in this way:

- Create a local provider in `./providers/my-upload-provider/`
- I copied the `./node_modules/@strapi/provider-upload-aws-s3` into my provider folder
- Since the configuration file written inside  `./configuration /plugins.js` seems not to be provided to our custom provider, we edit the `./providers/my-upload-provider/lib/index.js` by adding the right config:

```javascript
module.exports = {
  init(config) {
   // I add my configuration here
    const configInternal = {
      accessKeyId: process.env.AWS_KEY_ID, 
      secretAccessKey: process.env.AWS_SECRET_KEY,
      region: process.env.AWS_REGION,
      params: {
        Bucket: process.env.AWS_BUCKET_NAME,
      },
    }

    const S3 = new AWS.S3({
      apiVersion: '2006-03-01',
      ...config,
      // And than I passed the configuration to AWS.S3
      ...configInternal,
    });
    ...
}
```
- I force npm to override the `@strapi/provider-upload-local` with my custom provider by using npm local paths:

`package.json`
```json
{
...
    "dependencies": {
        ...
        "@strapi/provider-upload-local": "file:providers/my-upload-provider",
    } 
}
```
- Run `yarn install && yarn develop`

It works for me

Note: I had other issues after this fix, related to CORS. It can be fixed by following this: https://github.com/strapi/strapi/issues/11637

### UPDATE

It seems a docs mistake. Scroll down to the comments to read the solution.

**Comment by konstantinmuenster** [comment]
I had similar issues with the S3 upload provider. It seems like the package documentation is not up to date (at least not on `docs.strapi.io`). You can check the updated documentation here: https://github.com/strapi/strapi/tree/master/packages/providers/upload-aws-s3

If you use `@strapi/provider-upload-aws-s3` instead of the old library, the configuration in `plugins.js` changes slightly as there is a new config level in the object:
```js
module.exports = ({ env }) => ({
  // ...
  upload: {
    config: {             // <-- this one 
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        params: {
          Bucket: env('AWS_BUCKET'),
        },
      },
    },
  },
  // ...
});
```

**Comment by andreaSimonePorceddu** [comment]
@konstantinmuenster 
> I had similar issues with the S3 upload provider. It seems like the package documentation is not up to date (at least not on `docs.strapi.io`). You can check the updated documentation here: https://github.com/strapi/strapi/tree/master/packages/providers/upload-aws-s3

It seems they updated the GitHub readme two hours ago

thanks, I will try with this configuration

**Comment by derrickmehaffy** [comment]
Closing this as the provider config was just wrong, nom readmes will be updated once we release the next version, docs pr is already in progress.

**Comment by ivanix1** [comment]
as of today, still seems to be issue. cannot get this plugin to work on strapi v4.
even after setting the config/plugins.js as mentioned above.

**Comment by uejosh** [comment]
> as of today, still seems to be issue. cannot get this plugin to work on strapi v4. even after setting the config/plugins.js as mentioned above. i can confirm that strapi is still looking for images in the local uploads folder instead on the s3 bucket. no logs or errors shown either.

I am also experiencing this issue. Strapi uploads and tries to retrieve images from http://my-domain/uploads instead of the url of the the upload provider (google cloud storage in my case) configured in the config/plugins.js file. no logs, no errors as well.

**Comment by j4sun** [comment]
I am also having the same issue whilst following this exact documentation: https://github.com/strapi/strapi/tree/main/packages/providers/upload-aws-s3

Any updates on this?

My dependencies:
  "dependencies": {
    "@strapi/plugin-graphql": "^4.10.1",
    "@strapi/plugin-i18n": "4.10.1",
    "@strapi/plugin-users-permissions": "4.10.1",
    "@strapi/provider-upload-aws-s3": "^4.10.7",
    "@strapi/strapi": "4.10.2",
    "better-sqlite3": "8.0.1",
    "pg": "^8.11.0",
    "stripe": "^12.4.0"
  },
