### ISSUE TITLE
NOTICE: Population of Relations, Media, Component, and Dynamic Zone fields

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11787]
## Please see this discussion forum thread to talk about this further: https://forum.strapi.io/t/discussion-regarding-default-population-of-rest/13395

Hello everyone,

Since we have launched the Strapi v4 we have seen an increase in the number of issues regarding automatic population of the following:

- Relations
- Media Fields
- Components
- Dynamic Zones

None of these are populated by default in the v4, **this is intended functionality** largely for performance reasons. We have a temporary documentation page on this here (yes it says relations, but applies to all of the above listed):

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population

And we are currently working on a massive refactoring to this documentation in the following PR:

https://github.com/strapi/documentation/pull/541

---

Please refrain from opening additional issues on the population topic, I will leave this notice unlocked so if you wish to discuss it, you may do so here.

**Comment by eikaramba** [comment]
assuming a posts<->user relationship, how should we then secure the users endpoint if populating and allowing /find permission is required on users? see https://github.com/strapi/strapi/issues/11740#issuecomment-984611247

correct me if i am wrong but for me currently in v4 you either have no relationships to the current user or you have to complete open access to every user, which would be big security issue. hopefuly for me and others this is just a big misunderstanding of how strapi v4 is supposed to work.

**Comment by NadhirBenLazhar** [comment]
1. Start new Strapi v4 project.
2. Add avatar as `media content type` field in `user` model.
3. Activate USERS & PERMISSIONS > ROLES > PUBLIC: ALL Permissions Activated
4. This request works fine (without avatar in response) as expected:
```
GET http://localhost:1337/api/users
```
5. Try to populate `avatar` does not work with `users`. I tried with these requests:
```
GET http://localhost:1337/api/users?populate=avatar
GET http://localhost:1337/api/users?populate=true
GET http://localhost:1337/api/users?populate=*
GET http://localhost:1337/api/users?fields=*
```
6. In another project; The `user` has many relations. no one works with `populate`.
```
GET http://localhost:1337/api/users?populate=posts
```
7. The Terminal error:
```
[2021-12-04 21:42:41.037] error: select `t0`.* from `up_users` as `t0` where (`t0`.`populate` = 'avatar') - ER_BAD_FIELD_ERROR: Unknown column 't0.populate' in 'where clause'
Error: ER_BAD_FIELD_ERROR: Unknown column 't0.populate' in 'where clause'
```
8. The response error:
```
{
    "data": null,
    "error": {
        "status": 500,
        "name": "InternalServerError",
        "message": "Internal Server Error"
    }
}
```
9. I tested this using two (2) strapi projects with:
- PostgreSQL-NO-SSL
- MySQL-YES-SSL

10. Other models work fine with `populate`. as expected. like this one:
```
GET http://localhost:1337/api/categories?populate=posts
```

Thank you.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-api-response-does-not-show-relationships/13095/2

**Comment by rmrantunes** [comment]
Is there any way to start a new Strapi v3.x.x project right now?

**Comment by ovlb** [comment]
Crossposting from the forum w/ more details:

For me, this mechanism isn’t working at all. I spun up a new Strapi instance yesterday (v4.0.0, using Postgres without SSL).

Given the following schema:

```json
{
  "kind": "collectionType",
  "collectionName": "posts",
  "info": {
    "singularName": "post",
    "pluralName": "posts",
    "displayName": "Posts",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string",
      "required": true
    },
    "Slug": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "Content": {
      "type": "richtext",
      "required": true
    },
    "authors": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "plugin::users-permissions.user"
    },
    "users": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "plugin::users-permissions.user",
      "inversedBy": "posts"
    },
    "categories": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::category.category",
      "inversedBy": "posts"
    }
  }
}
```


Categories are basically the same as in the restaurant example from the docs.

```json
{
  "kind": "collectionType",
  "collectionName": "categories",
  "info": {
    "singularName": "category",
    "pluralName": "categories",
    "displayName": "Category"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string"
    },
    "posts": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::post.post",
      "inversedBy": "categories"
    }
  }
}
```

No matter how I use the `populate` parameter, the relations are never showing up in the response. The status code is always `200`. 

```
GET http://localhost:1337/api/posts?populate=*
GET http://localhost:1337/api/posts?populate%5Bcategories%5D=*
…
```

I can break the server by e.g. doing 

```
GET http://localhost:1337/api/posts?populate%5Bcategories%5D=Title
```

which throws 

```
[2021-12-05 14:39:03.151] error: Invalid nested populate. Expected '*' or an object
```

But I guess this is intended.

In the lifecycle hooks, the populate relations are showing up, however, and in the UI too. 

As I am new to Strapi I might miss something? Any hints would be appreciated.

**Comment by NadhirBenLazhar** [comment]
@rmrantunes 

You can list all `create-strapi-app` versions:
`npm view create-strapi-app versions --json`

To create Strapi v3 project:
`npx create-strapi-app@3.6.8 my-project`

Don't forget to downgrade your `node` version.
`nvm install lts/fermium`
or
`nvm install v14.18.2`

then 
```
nvm use v14.18.2
nvm alias default v14.18.2
```

good luck.

**Comment by jdavidferreira** [comment]
I tried following the instructions that are mentioned in temporary documentation page to retrieve all their first-level relations (`?populate=*`) but it is not working. It also doesn't work if I specify the name of the relationship (`?populate=topics`).

node.js v14.18.1
strapi v4
mysql v5.7

**Comment by MichaelTao** [comment]
> Crossposting from the forum w/ more details:
> 
> For me, this mechanism isn’t working at all. I spun up a new Strapi instance yesterday (v4.0.0, using Postgres without SSL).
> 
> Given the following schema:
> 
> ```json
> {
>   "kind": "collectionType",
>   "collectionName": "posts",
>   "info": {
>     "singularName": "post",
>     "pluralName": "posts",
>     "displayName": "Posts",
>     "description": ""
>   },
>   "options": {
>     "draftAndPublish": true
>   },
>   "pluginOptions": {},
>   "attributes": {
>     "Title": {
>       "type": "string",
>       "required": true
>     },
>     "Slug": {
>       "type": "string",
>       "required": true,
>       "unique": true
>     },
>     "Content": {
>       "type": "richtext",
>       "required": true
>     },
>     "authors": {
>       "type": "relation",
>       "relation": "oneToMany",
>       "target": "plugin::users-permissions.user"
>     },
>     "users": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "plugin::users-permissions.user",
>       "inversedBy": "posts"
>     },
>     "categories": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "api::category.category",
>       "inversedBy": "posts"
>     }
>   }
> }
> ```
> 
> Categories are basically the same as in the restaurant example from the docs.
> 
> ```json
> {
>   "kind": "collectionType",
>   "collectionName": "categories",
>   "info": {
>     "singularName": "category",
>     "pluralName": "categories",
>     "displayName": "Category"
>   },
>   "options": {
>     "draftAndPublish": false
>   },
>   "pluginOptions": {},
>   "attributes": {
>     "Title": {
>       "type": "string"
>     },
>     "posts": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "api::post.post",
>       "inversedBy": "categories"
>     }
>   }
> }
> ```
> 
> No matter how I use the `populate` parameter, the relations are never showing up in the response. The status code is always `200`.
> 
> ```
> GET http://localhost:1337/api/posts?populate=*
> GET http://localhost:1337/api/posts?populate%5Bcategories%5D=*
> …
> ```
> 
> I can break the server by e.g. doing
> 
> ```
> GET http://localhost:1337/api/posts?populate%5Bcategories%5D=Title
> ```
> 
> which throws
> 
> ```
> [2021-12-05 14:39:03.151] error: Invalid nested populate. Expected '*' or an object
> ```
> 
> But I guess this is intended.
> 
> In the lifecycle hooks, the populate relations are showing up, however, and in the UI too.
> 
> As I am new to Strapi I might miss something? Any hints would be appreciated.

I ran into this issue. What happened in my case was, I was using the new API token and I only had read-only. If you give it full access it should work.

The alternative solution is to give public role access to the content type (find)

**Comment by ovlb** [comment]
> I ran into this issue. What happened in my case was, I was using the new API token and I only had read-only. If you give it full access it should work.

Ahh yeah. Thank you! 

However, that feels quite unintuitive. I’m using the API token for a static site generator and it should not need full access to build the site, as I’m never manipulating data. Updating the public permissions also does not feel too great.

**Comment by valerie-makes** [comment]
> I ran into this issue. What happened in my case was, I was using the new API token and I only had read-only. If you give it full access it should work.
>
> The alternative solution is to give public role access to the content type (find)

I had this issue too - creating a full access API token worked, but adjusting the public roles did not.

> However, that feels quite unintuitive. I’m using the API token for a static site generator and it should not need full access to build the site, as I’m never manipulating data. Updating the public permissions also does not feel too great.

I agree with this - it seems strange that read permission is not enough.

**Comment by PaulRichez** [comment]
That can help you : https://forum.strapi.io/t/strapi-v4-api-response-does-not-show-relationships/13095

**Comment by FitFingers** [comment]
Is there a way to solve this by editing the services etc in Strapi? V3 was exactly the behaviour I needed and V4 has taken that away somewhat.

**My use case:**
I have a Page component with a dynamic zone and relational field. I need to populate the dynamic zone's content. My structure is this:
```
- content type (page)
   - dynamic zone (content)
      - component (slider)
         - text field (caption)
         - media (thumbnail image)
   - relational field (navigation item)
      - text field (slug)
```

I am using the following URL to query and populate:
``` https://mydomain.com/api/pages?filters[navigation][slug][$eq]=/&populate[content][populate]=* ```

But this only populates some of the content: the media file, for instance, isn't fetched, and the relational field is not returned at all.

It would be great (and perhaps I'm missing something) if there was a way to set this in the Strapi code itself, rather than using URL parameters.

**Comment by PaulRichez** [comment]
I think you can't populate dynamic zone, but i'm not sure :'(

**Comment by tomnovotny7** [comment]
We are using this solution for now https://github.com/strapi/strapi/issues/11836#issuecomment-989131330

**Comment by MurmeltierS** [comment]
Why for heavens sake is there no "populate all" option. I'm completely lost with dynamic zone population here.

**Comment by brucewyne** [comment]
Is there a way to configure this? It seems really silly for my frontend to have to be aware to ask for things like images.

**Comment by derrickmehaffy** [comment]
> Is there a way to configure this? It seems really silly for my frontend to have to be aware to ask for things like images.

You can create a route middleware to set the default population if none if defined:

```js
// path: ./src/api/blog-post/routes/blog-post.js

'use strict';

/**
 * blog-post router.
 */

const { createCoreRouter } = require('@strapi/strapi').factories;

module.exports = createCoreRouter('api::blog-post.blog-post', {
  config: {
    find: {
      middlewares: [
        (ctx, next) => {
          if (!ctx.query.populate) {
            ctx.query.populate = '*'
            // or set to whatever qs populate structure you want
          }

          return next()
        }
      ]
    }
  }
});
```

**Comment by masterdimar** [comment]
Admin UI is populating the relation of the relation in a many to many relation.

In my case this is causing very low response times

**Comment by derrickmehaffy** [comment]
I'm going to lock this issue as all additional comments should go to this discussion instead: https://forum.strapi.io/t/discussion-regarding-default-population-of-rest/13395

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/discussion-regarding-default-population-of-rest/13395/4

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/discussion-regarding-default-population-of-rest/13395/7
