### ISSUE TITLE
`Get` request doesn't return media type

### ISSUE THREAD

**Issue by nblthree** [strapi/strapi#11785]
### Describe the bug

 `Get` request doesn't return media type

### Steps to reproduce the behaviour

This the schema

```
{
  "kind": "collectionType",
  "collectionName": "excursions",
  "info": {
    "singularName": "excursion",
    "pluralName": "excursions",
    "displayName": "excursion",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "image": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ]
    },
    "body": {
      "type": "richtext",
      "required": true
    },
    "title": {
      "type": "string",
      "required": true
    },
    "slug": {
      "type": "uid",
      "targetField": "title",
      "required": true
    }
  }
}
```
This is what I get

`{"data":{"id":1,"attributes":{"body":"Lorem ipsum......","createdAt":"2021-12-03T10:36:47.949Z","updatedAt":"2021-12-03T10:40:41.934Z","publishedAt":"2021-12-03T10:40:41.925Z","title":"Tour in the desert","slug":"tour-in-the-desert"}},"meta":{}}`

As you can see there are no `image` attributes.

### Expected behavior

I should get `image` in the attributes

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version:  v4.0.0
- Database: sql
- Operating system: windows 10

**Comment by amarijanovic** [comment]
I have the same issue using REST. I am using S3 as Upload Provider and turned on localization for the image field

**Comment by am283721** [comment]
Experiencing the same behavior. Been trying for the last day and a half to figure out why media attributes weren't being returned from the API. Tried with various collection configurations and upload providers and with/without GraphQL.

**Comment by derrickmehaffy** [comment]
See: https://github.com/strapi/strapi/issues/11787
