### ISSUE TITLE
Text field RegExp validation

### ISSUE THREAD

**Issue by mattf96s** [strapi/strapi#11781]
### Describe the bug

Cannot remove a *non-required* text field's value if the field has RegExp validation. However, you can leave the field empty when creating the entry without failing the validation.

### Steps to reproduce the behavior

1. Go to content-type builder and create a text field that is not required but has some form of RegExp validation
 > use this as an example`^\d+$`
2. Go to content-manager and create a new entry with that field correctly filled in (as a number)
3. Edit that same entry and remove that field's value (back to blank).
![image](https://user-images.githubusercontent.com/68327846/144599693-f39d0055-8934-4d38-814f-8e6f66c4bc37.png)

### Expected behavior

I can remove a non-required field's value even if the field has RegExp validation.

### Screenshots

![image](https://user-images.githubusercontent.com/68327846/144600108-955f1322-c72c-4803-b3b3-dbce11c5d2e2.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.18.1 
- NPM version: 6.14.15
- Strapi version: 4.0.0 
- Database: MySQL 5.7.23
- Operating system: macOS Big Sur 11.5.2

**Comment by jakobsjoqvist** [comment]
I have been able to reproduce this problem and I will work on a solution tomorrow.

**Comment by derrickmehaffy** [comment]
fixed in https://github.com/strapi/strapi/pull/11808
