### ISSUE TITLE
Update documentation on NPM for packages for v3 to be used only with Strapi v3 and not v4

### ISSUE THREAD

**Issue by ihmpavel** [strapi/strapi#11799]
There is some confusion from some developers which do not know about differences in Strapi v3 and v4. 

Often caused using old packages on NPM, which are only for v3. For example `strapi-provider-upload-aws-s3` instead of `@strapi/provider-upload-aws-s3`. Eg https://github.com/strapi/strapi/issues/11798

It will help a few developers to have a notice in the documentation on NPM for v3 on the top of the readme. Something like `This package is intended to use only with Strapi 3.x, for v4, use scoped package @strapi/xyz` 

Also the title for `https://www.npmjs.com/package/@strapi/provider-upload-aws-s3` is `strapi-provider-upload-aws-s3` instead of `@strapi/provider-upload-aws-s3`

**Comment by lack-of-gravitas** [comment]
There's general confusion across the board for plugins and installable and supported packages. Not sure how v4 can be called a stable release when all of us rely on at least 1 mission critical 3p plugin for features and functions.

In my case, I now have a 6mo ticker to ensure my clients get off v3 and hope/pray the plugins they're used to get ported over to v4 in time. Sever lack of (or multiple) documentation to extend or bwckport via hooks and APIs makes rolling your own custom extensions super hard.

(Super sad face)

**Comment by ihmpavel** [comment]
Yeah, I totally agree with you. I hopped in about two weeks ago. I started using beta version. It was really pain, because I did not want to start rewriting everything month later, after official release... Official release (almost nothing changed from beta versions) should have been delayed about a week to create migrating guides and update official documentation. I ended up patching original plugins via `patch-package` to make them working with v4 (to achieve same results as in v3, because described customization in documentation do not work...) 

But realizing that all official packages needs to be in `@strapi` scope took me some time (documentation was not ready). And now it is still for some configuration options outdated or unusable. Searching everything on Google navigates you (at least with original packages) to `strapi-` and nowhere is a sign, that you should not use the package or it will not work... 

For newbies - in my opinion - should (for now) official packages `strapi-` on npm tell at least supported Strapi versions (same for scoped ones).

**Comment by derrickmehaffy** [comment]
> Also the title for https://www.npmjs.com/package/@strapi/provider-upload-aws-s3 is strapi-provider-upload-aws-s3 instead of @strapi/provider-upload-aws-s3

This is already fixed in the code and will be changed once we release v4.0.1

**Comment by derrickmehaffy** [comment]
all v3 packages have been marked as deprecated on npm, marking as closed
