### ISSUE TITLE
strapi-provider-upload-cloudinary not working in v4 of strapi

### ISSUE THREAD

**Issue by abhijeetbapuni** [strapi/strapi#11798]
### Package strapi-provider-upload-cloudinary not working in v4 of strapi

After install and setup strapi-provider-upload-cloudinary package, images are not uploading to cloudinary and uploading to local only.

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 4.0
- Database: mysql
- Operating system: mac m1

**Comment by ihmpavel** [comment]
Hi, are you using plugins with `@strapi/` prefix?

You should be using [@strapi/provider-upload-cloudinary](https://www.npmjs.com/package/@strapi/provider-upload-cloudinary).

Be aware, that the `config` in `plugins.js` was changed

**Comment by abhijeetbapuni** [comment]
Thank you very much

**Comment by dalton-hill** [comment]
For anyone wanting the updated `plugins.js` format (`upload.config.*` vs `upload.*`)
```
module.exports = ({env}) => ({
  upload: {
    config: {
      provider: 'cloudinary',
      providerOptions: {
        cloud_name: env('CLOUDINARY_NAME'),
        api_key: env('CLOUDINARY_KEY'),
        api_secret: env('CLOUDINARY_SECRET'),
      },
      actionOptions: {
        upload: {},
        delete: {},
      },
    },
  },
});
```

**Comment by harryvu** [comment]
Hi all, I am new to Strapi and struggling to integrate it with cloudinary. I followed this [article ](https://strapi.io/blog/add-cloudinary-support-to-your-strapi-application) and read many others and spent more than a day on it, but no matter what I did, it always upload images to the public/uploads folder! Am I missing something? Please help.

Below are some important files:

./config/plugins.js
module.exports = ({ env }) => ({
  upload: {
    enabled: true,
    config: {
      provider: "cloudinary",
      providerOptions: {
        cloud_name: env("CLOUDINARY_NAME"),
        api_key: env("CLOUDINARY_KEY"),
        api_secret: env("CLOUDINARY_SECRET"),
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
});

./config/middlewares.js
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", "res.cloudinary.com"],
          "media-src": ["'self'", "data:", "blob:", "res.cloudinary.com"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  //...
];

package.json
"devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.11.5",
    "@strapi/plugin-users-permissions": "4.11.5",
    "@strapi/provider-upload-cloudinary": "4.11.5",
    "@strapi/strapi": "4.11.5",
    "pg": "8.8.0"
  },
