### ISSUE TITLE
[v4] Support Database Transactions with Knex, please

### ISSUE THREAD

**Issue by willnode** [strapi/strapi#11792]
### Please describe your feature request

- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Please support database transactions in v4. v3 actually supports database transactions since it is used with Bookshelf.js. v4 uses a custom database engine and I can't see how I can insert knex.js transactions in custom code.

### Why is it needed?

Please read my draft article on how to use database transactions in v3, it also tells the real reason why  database transactions is a must:

https://github.com/strapi/community-content/issues/539

### Suggested solution(s)

We can add a parameter `transaction` in the query engine.

https://github.com/strapi/strapi/blob/6ee0ba1953ad2e4e59ea5d941f3126ef04d7783a/packages/core/database/lib/query/query-builder.js#L7

### Related issue(s)/PR(s)

If there's nobody has time to implement this, will you (the Strapi team) accept PRs to this feature? This feature is so critical to me.

**Comment by Flowko** [comment]
hi @willnode, any news about this from the Strapi team ?

**Comment by willnode** [comment]
Not heard anything yet.

**Comment by copocaneta** [comment]
Thanks for the feature request and also for the article @willnode 

This feature is a must when working with multiple instances of Strapi querying the same database. It's unfortunate that this is not possible on v4. Strapi Team, is there a status for this?

**Comment by derrickmehaffy** [comment]
> If there's nobody has time to implement this, will you (the Strapi team) accept PRs to this feature? This feature is so critical to me.

I would absolutely say we are open to a PR on this

**Comment by willnode** [comment]
Finally an answer 👀 will try on weekend.

**Comment by derrickmehaffy** [comment]
> Finally an answer eyes will try on weekend.

Sorry it's been pretty crazy with v4 :see_no_evil: lots going on

**Comment by benderillo** [comment]
Anyone stumbling upon this issue please consider to go to this PR and show your support :) https://github.com/strapi/strapi/pull/12715 

Missing transactions is a show stopper for me and I'm pretty sure for many others. 

There is not way to do a safe payment support without transactions. Not even that, there is no safe way to ensure uniqueness for a relationship attribute in v4 without transaction either.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/support-database-transactions-with-knex
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
