### ISSUE TITLE
Debug mode for database

### ISSUE THREAD

**Issue by raulriera** [strapi/strapi#1179]
**What is the expected behavior?**
It would be beneficial to see all the queries happening in the background when running strapi in development mode.

I have hacked it into place by modifying these files

`/config/environments/development/database.json`
```json
// after options, inside defaults
"variables": {
    "debug": false
}
```

`/node_modules/strapi-mongoose/lib/index.js`
 
```javascript
// at the top with the rest of the options
const { debug } = _.defaults(connection.variables, strapi.config.hook.settings.mongoose);
variables.debug = debug === true || debug === 'true';

// after the connection

for (let key in variables) {
      instance.set(key, variables[key])
}
```

There is no UI for this, could create a PR if this is the desired approach

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by raulriera** [comment]
Maybe it should do the same for the routes? 🤔

**Comment by Aurelsicoko** [comment]
@raulriera You can already add the `debug` property in the `database.json` configurations file.

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "127.0.0.1",
        "port": 27017,
        "database": "",
        "username": "",
        "password": ""
      },
      "options": {
        "debug": true
      }
    }
  }
}
```

It's working pretty well with Bookshelf. I'm not sure it's supported by our hook `strapi-mongoose` though.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I wasn't even aware of this on bookshelf. Might have saved me a few headaches doing some troubleshooting 😛 

I don't see any detailed information for the debug function in the strapi docs (Minus a single reference in the example config):
https://strapi.io/documentation/configurations/configurations.html#database
https://strapi.io/documentation/configurations/configurations.html#dynamic-configurations

**Comment by raulriera** [comment]
> You can already add the debug property in the database.json configurations file.

Oh, I didn't think of putting it in there because everything in `options` was tied as `connectionOptions` which I thought it was for the initial connect only. I'll test it out and change my PR then

**Comment by raulriera** [comment]
This is stil an issue unless this is merged 🙂 https://github.com/strapi/strapi/pull/1181
