### ISSUE TITLE
"Create new component" toggle visible in production

### ISSUE THREAD

**Issue by Webbist-dev** [strapi/strapi#11790]
### Describe the bug

When running strapi with `NODE_ENV=production` in content-type builder tab the create new component button is still visible while not being functional. This should be removed from the render.

### Steps to reproduce the behavior

1. Run strapi in production
2. Visit content type builder
3. "Create new component" visible

### Expected behavior

The "Create new component" button should not be visible (same behavior "create collection/single")

### Screenshots

![image](https://user-images.githubusercontent.com/6637751/144672749-91496b70-fbd1-473c-9ced-ae82468b0f7b.png)

### System

- Node.js version: v16
- NPM version: N/A
- Strapi version: v4
- Database: N/A
- Operating system: Linux/Windows (OS agnostic issue)

### Additional context

![image](https://user-images.githubusercontent.com/6637751/144672863-a51c0efc-dc21-4da0-97aa-de2ce717fde0.png)

**Comment by derrickmehaffy** [comment]
Confirmed on v4: 
![image](https://user-images.githubusercontent.com/8593673/144673260-6a6270c8-c6a6-4ae0-a55c-674312891251.png)

**Comment by Webbist-dev** [comment]
This has been merged in now, so can be closed

**Comment by derrickmehaffy** [comment]
closing as fixed in #11791 will be in next release
