### ISSUE TITLE
Create user without password causes 400 error

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#11796]
### Describe the bug

Create user without password causes 400 error

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Go to 'User'
3. Click 'Add new Entry'
4. Enter `Username`, `Email` and save
5. `Warning Alert: Bad Request`

### Expected behavior

Either message for password label `This value is required.` should be displayed or `Warning Alert: The form contains some errors` should be displayed.

**Comment by derrickmehaffy** [comment]
You are missing the system block, I can't tell if this is v3 or v4. Please fill out the BR template completely.

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
