### ISSUE TITLE
v4 database host using localhost when a custom server specified 

### ISSUE THREAD

**Issue by nazmulfahim** [strapi/strapi#11805]
I tried to use postgress from an external cloud with strapi but it isn't taking my host configuration. To better understand 

This is my database config

```
module.exports = ({ env }) => ({
  connection: {
    client: "postgres",
    connection: {
      host: "direct host url",
      // host: env("DATABASE_HOST"),
      port: env.int("DATABASE_PORT"),
      database: env("DATABASE_NAME"),
      user: env("DATABASE_USERNAME"),
      password: env("DATABASE_PASSWORD"),
      // schema: env("DATABASE_SCHEMA", "public"), // Not required
      ssl: env("DATABASE_SSL", false),
      // ssl: {
      //   rejectUnauthorized: env.bool("DATABASE_SSL_SELF", false), // For self-signed certificates
      // },
    },
    debug: false,
  },
});

```

but it is giving me an error 

**no pg_hba.conf entry for host "my ip", user "right username", database "right database", SSL off**      

so I assume it is using default localhost which is trying to look for the database on my ip but it isn't there because it is on a external cloud.

Ideally this config should connect. I tried to provide the hostname directly instead of 

`env("DATABASE_HOST")
`
I didn't do any other database related configuration after installing this project.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by nazmulfahim** [comment]
@derrickmehaffy  have created a new issue kindly please solve it asap.

[Issue here](https://github.com/strapi/strapi/issues/11818)
