### ISSUE TITLE
Support for testing

### ISSUE THREAD

**Issue by raulriera** [strapi/strapi#1180]
**What is the expected behavior?**
There doesn't seem to be any tests in the library or in many of nested sub modules. It would be nice to have some sort of testing architecture in place, once in. I would love to fill in some tests. Still finding my way with nodejs, wish I could help out more

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by lauriejim** [comment]
Hi @raulriera, we are actually working on framework tests.

**Comment by lauriejim** [comment]
First round of framework test here https://github.com/strapi/strapi/pull/1311
