### ISSUE TITLE
Can't query users from user-permissions from backend

### ISSUE THREAD

**Issue by Solero007** [strapi/strapi#11803]
## Bug report
Can't query users from user-permissions from the backend

### Describe the bug
Saying it's not found when trying to query it. 
I;ve tried both query and entityService

### Screenshots
![image](https://user-images.githubusercontent.com/26302508/144732179-b1f052f9-3716-49be-888d-3b9f1e73a8bf.png)
![image](https://user-images.githubusercontent.com/26302508/144732181-ee49ec42-3f7a-420b-978c-2d9a4f82c53f.png)

**Comment by iicdii** [comment]
It's `plugin::users-permissions.user`, not `api::user.users-permissions`

**Comment by derrickmehaffy** [comment]
> It's `plugin::users-permissions.user`, not `api::user.users-permissions`

Exactly this, closing
