### ISSUE TITLE
strapi CLI is not working for version 4.0

### ISSUE THREAD

**Issue by zorox-1** [strapi/strapi#11801]
## Bug report

strapi CLI is not working for version 4.

whenever i try to execute `strapi generate:plugin test` , i get the following error: 

You need to run strapi generate in a Strapi project. Make sure you are in the right directory

the folder is the CORRECT folder, im running this from the root folder of the strapi project

the same error is happening for any other strapi command

### Steps to reproduce the behavior

1. run `strapi generate:plugin test` in strapi project root folder 

### Expected behavior

generate a plugin 

### System

- Node.js version: v14.17.3
- NPM version: 8.1.0
- Strapi version: 4.0
- Database: sqlite
- Operating system: mac

**Comment by iicdii** [comment]
`strapi generate:plugin` is v3 CLI command.
run interactive CLI `strapi generate` instead - [Documentation](https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html#strapi-generate)

**Comment by gianlucariccobono** [comment]
`strapi generate` throws "error: unknown command 'generate'. See 'strapi --help'". 

`strapi -v` prints `3.4.3`, the project is running on Strapi v4.0.0.

**Comment by zorox-1** [comment]
when i try to run `strapi generate` , i get eerror: `error: unknown command 'generate'. See 'strapi --help'.`
so i checked `strapi -v` it gives me 3.6.8. 
i search how to update it to version 4.0. but i did not find any info anywhere.
i tried multiple way to update the cli, but none works:
`npm install strapi@alpha -g`
`npm install strapi-g`
`npm install strapi@next -g`
`npm install strapi@latest -g`

none of the above was working, and my strapi cli version was still on 3.6.8 .. 
so how to update the strapi to support version 4.0 ?

**Comment by iicdii** [comment]
If you are using strapi v3 you cannot use v4 CLI obviously.
Migration guide is coming, use v3 CLI until then.

**Comment by zorox-1** [comment]
how to uninstall strapi v3 and install v4 ?

**Comment by zorox-1** [comment]
i found a way around ... i run `yarn strapi generate` and it works.
but it will be cool if we can install strapi cli v4 globally

**Comment by derrickmehaffy** [comment]
> i tried multiple way to update the cli, but none works:
> npm install strapi@alpha -g
> npm install strapi -g
> npm install strapi@next -g
> npm install strapi@latest -g

Don't install Strapi globally, we haven't supported nor recommended this since like 2017. Use `yarn strapi ...` or `npm run strapi ....`

Closing

**Comment by rowild** [comment]
I have to tune in: I am a bit confused that this got closed, because using `strapi generate` in v4 actually DOES cause the error mentioned above. If strapi is supposed to be used with `yarn` prefixed, then this should really go into the docu, where this use is not mentioned anywhere:
https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html
@derrickmehaffy

**Comment by derrickmehaffy** [comment]
> I have to tune in: I am a bit confused that this got closed, because using `strapi generate` in v4 actually DOES cause the error mentioned above. If strapi is supposed to be used with `yarn` prefixed, then this should really go into the docu, where this use is not mentioned anywhere: https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html @derrickmehaffy Would you mind to give this another moment, please?

This is somewhat implied as we support both yarn and npm so if we had to put every single command with tabs for yarn and npm it would be a huge pain.

This is common in Node frameworks so we aren't the only ones doing it when it comes to CLIs but there are also other alternatives such as npx that we won't cover but could just as easily be used.

**Comment by rowild** [comment]
@derrickmehaffy I appreciate your response! However, I really don't see anything wrong with mentioning it in the CLI docu at least. 
Especially since the CLI docu uses wrong code examples: why does it read `strapi new <name>`, when it obviously should read `npm run strapi new <name>`? Given an abridged version without previously mentioning that `npm` or `yarn` has to be used, is eventually a wrong example, wouldn't you agree?

I do understand that you would like to see your assumption – "This is common in Node frameworks" - as common ground. But too often such assumptions have been proven wrong, one simple reason being that not everybody works with the same tech stack all the time. And good documentation should take that into account and instead support with help to use the new tech stack quickly.
This is one good example, where the addition of a simple sentence could increase the quality of the documentation very much. It would help people save time and it would reduce or even eliminate additional – seemingly superfluous –  questions (that take away your time, right?)

**Comment by derrickmehaffy** [comment]
> 

But the bulk of us in the team use yarn, should we use yarn or npm? And if we pick one, how many people are going to ask if yarn is required?

There is just far too much confusion around picking one. In the areas were it counts we specify the tabbed input of npm + yarn

such as installing a plugin:
- https://docs.strapi.io/developer-docs/latest/plugins/graphql.html#usage
- https://docs.strapi.io/developer-docs/latest/plugins/i18n.html#installation
- https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#installation

In fact you don't even have to use yarn or npm here you could actually do the same by using npx or pnpm or various others.

Logically speaking you could still install strapi globally and use it exactly as it's written and in theory there should be no problem but it's not one we recommend nor support.

**Comment by rowild** [comment]
@derrickmehaffy Sorry, I forgot to link to my suggestion here:
https://github.com/strapi/documentation/pull/669#issuecomment-1020295792

IMO there is no need to provide one solution. It should just be mentioned that a package executer solution must be used. It is more about "kicking the brain" should I find myself in the situation where I do not know what I am missing out or doing wrong. That way the mind reacts with "A right: I need to prefix the command." sth similar.

It is _specifically_ the fact that `npm` / `yarn` examples are provided in the documentation links you mention above, but NONE are given on the strapi CLI docu site. I wonder why? After all, that's the center of the CLI docu, isn't it? 
Any other documentation page c/should link to the CLI page with a sentence like "Read up on the proper usage of the <link>strapi CLI</link>." (I would keep the npm and yarn examples, though.)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Sorry, I forgot to link to my suggestion here: [strapi/documentation#669 (comment)](https://github.com/strapi/documentation/pull/669#issuecomment-1020295792)
> 
> IMO there is no need to provide one solution. It should just be mentioned that a package executer solution must be used. It is more about "kicking the brain" should I find myself in the situation where I do not know what I am missing out or doing wrong. That way the mind reacts with "A right: I need to prefix the command." sth similar.
> 
> It is _specifically_ the fact that `npm` / `yarn` examples are provided in the documentation links you mention above, but NONE are given on the strapi CLI docu site. I wonder why? After all, that's the center of the CLI docu, isn't it? Any other documentation page c/should link to the CLI page with a sentence like "Read up on the proper usage of the strapi CLI." (I would keep the npm and yarn examples, though.)

Just saw the suggestion, this makes more sense now. Sorry I wasn't reading your message completely but I get what your going for now.
