### ISSUE TITLE
It says Email already taken, but it's actually not taken when you register user.

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#11806]
### Describe the bug

When you failed to register user, the output error message is wrong.
It says `Email already taken` even though it's not taken. (You can even see user is created despite of the error.)
I debugged this, the actual error occurs during sending email confirmation.

### Steps to reproduce the behavior

1. Settings > Advanced Settings > **Enable email confirmation ON**
2. Input any Redirection url
3. Request GraphQL mutation `register`

### Expected behavior

1. It has to be like `There was a problem while sending the confirmation email`.
2. User account should not be created (I guess)

### Screenshots

<img width="1056" alt="" src="https://user-images.githubusercontent.com/4951716/144740424-22bb2e9e-bd4d-429f-9216-5160f3b82de0.png">

Below is output from my `console.error`
```shell
[sendConfirmationEmail] Error: SMTP code:550 msg:550-5.7.26 Unauthenticated email from strapi.io is not accepted due to domain's
550-5.7.26 DMARC policy. Please contact the administrator of strapi.io domain
550-5.7.26 if this was a legitimate mail. Please visit
550-5.7.26  https://support.google.com/mail/answer/2451690 to learn about the
550 5.7.26 DMARC initiative. bm22si10592340qkb.100 - gsmtp
```

### Code snippets

https://github.com/strapi/strapi/blob/c58e169a6bf3433fd59cfbac9eadc613dafcca67/packages/plugins/users-permissions/server/controllers/auth.js#L339-L370

When you look at the code, if confirmation email sending fails, it throws an error by inner catch, but outer catch throws an error `Email already taken` which is wrong.

### System

- Node.js version: v14.17.1
- NPM version: 6.14.13
- Strapi version: v4.0.0
- Database: SQLite
- Operating system: MacOS

**Comment by Ola-Jumoke** [comment]
I am having the same issue but if I turn off "One account per email address", the registration works. I have tried with multiple unique email addresses and the issue remains the same.

**Comment by MaheshCasiraghi** [comment]
Yes, confirmed this is a bug in V4.

**Comment by dalton-hill** [comment]
I believe this existed in v3 as well (#9788)

**Comment by xencodes** [comment]
any update on this?

**Comment by lucasR23** [comment]
I am facing the same issue with the versions:

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: v3.6.8
- Database: PostgreSQL
- Operating system: Linux Ubuntu

When `Enable email confirmation` is ON I always get the `email already taken error` once it is OFF it works
