### ISSUE TITLE
404 error when trying to login with auth providers

### ISSUE THREAD

**Issue by Flosrn** [strapi/strapi#11807]
### Describe the bug

I have a front-end Next.js app and when I trying to login to strapi backend with next-auth and auth Providers like Google or Github, strapi always returns a 404 error. 

### Steps to reproduce the behavior

1. Create a Next.js App and configure login with Providers like Google or Github with next-auth
2. Click on the login provider button
3. See the 404 error

![CleanShot 2021-12-05 at 11 17 29@2x](https://user-images.githubusercontent.com/12709355/144742458-f74070e6-932e-4d27-b19f-920d4a21b91d.png)
![CleanShot 2021-12-05 at 11 19 07@2x](https://user-images.githubusercontent.com/12709355/144742493-669f53cf-6294-4772-997c-e2e7926709bb.png)

### Screenshots

I followed the docs here: https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers

<img width="548" alt="CleanShot 2021-12-05 at 11 24 09@2x" src="https://user-images.githubusercontent.com/12709355/144742695-822d9c23-15d5-4a11-8fc3-b4ab198aae70.png">

I well configured the providers on strapi side
![CleanShot 2021-12-05 at 11 20 06@2x](https://user-images.githubusercontent.com/12709355/144742564-e0ad3916-ed07-462b-b126-998ab64b1c36.png)
 
 ### Code snippets
 
This is my code in my font-end app
```ts
callbacks: {
    session: async ({ session, user }) => {
      session.jwt = user.jwt;
      session.id = user.id;

      return Promise.resolve(session);
    },
    jwt: async ({ token, user, account }) => {
      const isSignIn = !!user;

      if (isSignIn) {
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/auth/${account?.provider}/callback?access_token=${account?.access_token}`
        );
        const data = await response.json();

        token.jwt = data.jwt;
        token.id = data.user.id;
      }

      return Promise.resolve(token);
    },
  },
```
I enabled the next-auth debug mode and all is ok, the providers work as expected, only the strapi response return 404 error and I don't understand why...

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: v4.0.0
- Database: postgres 8.6.0
- Operating system: mac 12.0.1

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11337
