### ISSUE TITLE
Create user without password causes 400 error

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#11816]
### Describe the bug

Create user without password causes 400 error

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Go to 'User'
3. Click 'Add new Entry'
4. Enter `Username`, `Email` and save
5. `Warning Alert: Bad Request`

### Expected behavior

Either message for password label `This value is required.` should be displayed or `Warning Alert: The form contains some errors` should be displayed.

### System

- Node.js version: v14.17.1
- NPM version: 6.14.13
- Strapi version: v4.0.0
- Database: SQLite
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
Should be fixed as of v4.1.12 (not sure which version fixed it:
![image](https://user-images.githubusercontent.com/8593673/171478526-c15fb0e3-7563-4497-b88b-370053c810bc.png)
