### ISSUE TITLE
Postgress failling to connect with external server in v4

### ISSUE THREAD

**Issue by nazmulfahim** [strapi/strapi#11818]
## Bug report
I am using v4 4.0.0 and trying to use postgress for database. I configure the config/database.js file as follows to connect with a postgress host on a cloud using the pg package.

```
module.exports = ({ env }) => ({
  connection: {
    client: "postgres",
    connection: {
      host: "direct host url",
      // host: env("DATABASE_HOST"),
      port: env.int("DATABASE_PORT"),
      database: env("DATABASE_NAME"),
      user: env("DATABASE_USERNAME"),
      password: env("DATABASE_PASSWORD"),
      // schema: env("DATABASE_SCHEMA", "public"), // Not required
      ssl: env("DATABASE_SSL", false),
      // ssl: {
      //   rejectUnauthorized: env.bool("DATABASE_SSL_SELF", false), // For self-signed certificates
      // },
    },
    debug: false,
  },
});

```

### Describe the bug
It is giving me an error no pg_hba.conf entry for host "my ip", user "right username", database "right database", SSL off. 

I changed the error slightly to hide my credentials but basically this error is showing the right username and database name but not the host. If I use env(DATABASE_HOST) env variable  or direct host url string the error remain same. Which leads me believe the the problem is when configuring database strapi using a default host regardless of env file. for other credentials they are using correct environment variables. 

### Steps to reproduce the behavior

1. create a new project
2. create a postgress cloud host
3. copy paste this configuration
4.  and start the server 

### Expected behavior
 This configuration is directly copied from the doc so It should naturally connect with my postgress host and start strapi development 

### System
- v14.17.1
- 6.14.13
- 4.0.0
- 13.5
- Windows 10 pro

**Comment by Brocy** [comment]
I got a similar issue, running the Postgres on docker, with **DATABASE_USERNAME** and  **DATABASE_PASSWORD**  set to _strapi_, but is complaining about my macbook user

`error: password authentication failed for user "brocycenteio"
    at Parser.parseErrorMessage (/{hidden-my-path}/cms-v4-test/node_modules/pg-protocol/dist/parser.js:287:98)`

Any ideas way??

**Comment by whispers16** [comment]
@Brocy in my case happened the same because I had `username` instead of `user` in `config/database.js`

**Comment by nazmulfahim** [comment]
Found the fix. it has to do with ssl certificates.

```
ssl: {
         rejectUnauthorized: env.bool("DATABASE_SSL_SELF", false), // For self-signed certificates
      },
```

basically this code is mandatory for self signed certificates.  Surprisingly I used this code at the beginning and it didn't work. but now it is working perfectly.

**Comment by Brocy** [comment]
> user

Ya thank you very much

**Comment by nazmulfahim** [comment]
@Brocy  did you fixed? my problem was solved but suddenly I got this issue
