### ISSUE TITLE
Components field not present in Rest API if populate is set.

### ISSUE THREAD

**Issue by tompap** [strapi/strapi#11814]
### Describe the bug

It's not possible using populate in find or findOne functions of a controller to get "components" field.
The components field can only be returned if no populate array is given OR if a related field in the "component field" is given in the populate array

### Steps to reproduce the behavior

1. You need 2 Models and a Component
2. Model A contains Many Model B
3. Model B containes a component Field
4. const entity = await strapi.services.modelA.findOne({ id: ctx.params.id }, [
      "model_b",
      "model_b.component"
    ]);
5. model_b.component is missing in the JSON
6. model_b.component is present if no populate param is given.

### Expected behavior

model_b.component should be in the JSON

### Code snippets

Issue seems to be in the strapi-connector-bookshelf/lib/populate.js
In formatPopulateOptions

there is a check if attribute is a component => with a continue without "adding it" in the extend.

If you add just before the continue

 _.extend(acc, {
          [newKey]: extendWithPopulateQueries(
            [obj[newKey], acc[newKey]],
            queryOptionsToQueryMap(queryOptions, { model: tmpModel })
          ),
        });
        
        continue;

It seems to work correctly

### System

- Node.js version: 14
- NPM version:
- Strapi version: 3.6.8
- Database: sqlite or mysql
- Operating system: Linux and Windows

### Additional context

Seems to be the same projet describe here 
https://forum.strapi.io/t/how-to-populate-component-that-comes-from-a-deep-nested-relation/3018

Note previously I was using Strapi 3.0.5 without any issue.

**Comment by derrickmehaffy** [comment]
See: https://github.com/strapi/strapi/issues/11787

Closing

**Comment by tompap** [comment]
Hello, this is not similar, my issue is about V3 not V4.

**Comment by derrickmehaffy** [comment]
> Hello, this is not similar, my issue is about V3 not V4.

see: https://github.com/strapi/strapi/issues/11726
