### ISSUE TITLE
The User name is not required when creating new user from /api/auth/local/register

### ISSUE THREAD

**Issue by Louai99k** [strapi/strapi#11810]
## Bug report

The User name is not required when creating new user from /api/auth/local/register

### Describe the bug

So When we are registering new users and if we don't pass username it will still work and if we add username it's not unique at all so I can register hundred user without changing the username

### Steps to reproduce the behavior

1. Try to register new user from the endpoint: '/api/auth/local/register' without specifying username
2. Try to  register new user from the endpoint: '/api/auth/local/register' with existing username

### Expected behavior

We shouldn't be able to register without username and this username should be unique

### System

- Node.js version: v16
- NPM version: v6
- Strapi version: v4
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by bibekgupta3333** [comment]
Can I do this Issue @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> Can I do this Issue @derrickmehaffy

We haven't determined if this is intended yet or not, the squad it's assigned to would need to validate that first.

**Comment by alexandrebodin** [comment]
This has been fixed [v4.1.10](https://github.com/strapi/strapi/releases/tag/v4.1.10) going to close :)
