### ISSUE TITLE
Cloudinary not working with fresh installation

### ISSUE THREAD

**Issue by don41382** [strapi/strapi#11820]
Hi Everyone,

I tried to use Strapi together with Cloudinary. I followed the instructions on:

https://strapi.io/blog/how-to-build-a-photo-gallery-with-strapi-nextjs-and-cloudinary

* created new app with yarn
* created new collection
* added strapi-provider-upload-cloudinary
* created config/plugins.js
* added .env file

Everyhting seems to work, but when I try to upload a picture to my new collection, it will be placed inside of the local folder and not on Cloudinary.

How can I see that the plugin is actually active?

### System

- Node.js version: 12.8.4
- NPM version: 6.14.6
- Strapi version: v4.0.0
- Database: -
- Operating system: Mac M1 - Monterey 12.0.1

**Comment by kmal-kenneth** [comment]
I have the same problem since yesterday when I started testing strapi v4.
I am creating a simple project in strapi v4. The project currently works on strapi v3.
The project does not customize any part of strapi, but uses postgresql and cloudinary.

I follow the documentation [Upload Developer-docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration)

I installed the package [@strapi/provider-upload-cloudinary](https://www.npmjs.com/package/@strapi/provider-upload-cloudinary)

Use suggested configuration with config/plugins.js and .env files.

To my surprise the supplier is completely ignored, in development and production.

config/plugins.js

```js

module.exports = ({ env }) => ({
  upload: {
    provider: "cloudinary",
    providerOptions: {
      cloud_name: env("CLOUDINARY_NAME"),
      api_key: env("CLOUDINARY_KEY"),
      api_secret: env("CLOUDINARY_SECRET"),
    },
  },
});
```

package.json

```json

{
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-graphql": "4.0.0",
    "@strapi/plugin-i18n": "4.0.0",
    "@strapi/plugin-users-permissions": "4.0.0",
    "@strapi/provider-upload-cloudinary": "4.0.0",
    "@strapi/strapi": "4.0.0",
    "pg": "^8.7.1",
    "pg-connection-string": "^2.5.0",
    "sqlite3": "5.0.2"
  }
}
```

However, file upload still works locally.

**Comment by kmal-kenneth** [comment]
Must be used

```js
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "cloudinary",
      providerOptions: {
        cloud_name: env("CLOUDINARY_NAME"),
        api_key: env("CLOUDINARY_KEY"),
        api_secret: env("CLOUDINARY_SECRET"),
      },
    },
  },
});
```
It is slightly different from what the readme.md file in the package says.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-not-detecting-cloudinary-upload-provider/13029/5

**Comment by derrickmehaffy** [comment]
Was fixed in: https://github.com/strapi/strapi/pull/11750

The new README's will go out when we release v4.0.1

Closing as this is already fixed. @kmal-kenneth see the cloudinary readme as it has a sample config for the security middleware to enable previews

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-provider-upload-cloudinary-not-transferring-media/4076/29

**Comment by ebitsdev** [comment]
Thanks a lot @kmal-kenneth, your provided config solved the issue for me.

**Comment by mnnlthmpsn** [comment]
> ```js
> module.exports = ({ env }) => ({
>   upload: {
>     config: {
>       provider: "cloudinary",
>       providerOptions: {
>         cloud_name: env("CLOUDINARY_NAME"),
>         api_key: env("CLOUDINARY_KEY"),
>         api_secret: env("CLOUDINARY_SECRET"),
>       },
>     },
>   },
> });
> ```

This doesn't work for me

**Comment by DennisM83** [comment]
Did you find a solution?
`module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "cloudinary",
      providerOptions: {
        cloud_name: env("CLOUDINARY_NAME"),
        api_key: env("CLOUDINARY_KEY"),
        api_secret: env("CLOUDINARY_SECRET"),
      },
    },
  },
});`

This code only just allows Strapi to crash. I can't seem to find a solution.

**Comment by ebitsdev** [comment]
I am successfully running Strapi with the new cloudinary plugin @strapi/provider-upload-cloudinary. Please note that there are 2 versions of the plugin. The version of the plugin that I installed is for Strapi v4 and the other one is for Strapi v3.
My current project contains: strapi v4.0.2 and @strapi/provider-upload-cloudinary.
And following is the content of the plugins.js file located at: myproject/config/plugins.js

```
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "cloudinary",
      providerOptions: {
        cloud_name: env("CLOUDINARY_NAME"),
        api_key: env("CLOUDINARY_KEY"),
        api_secret: env("CLOUDINARY_SECRET"),
      },
      actionOptions: {
        upload: {},
        delete: {},
      },
    },
  },
});
```
Let me know if you are able to get it working.
The complete is at: https://github.com/ebitsdev/strapi-v4-cloudinary

**Comment by mnnlthmpsn** [comment]
> I am successfully running Strapi with the new cloudinary plugin @strapi/provider-upload-cloudinary. Please note that there are 2 versions of the plugin. The version of the plugin that I installed is for Strapi v4 and the other one is for Strapi v3. My current project contains: strapi v4.0.2 and @strapi/provider-upload-cloudinary. And following is the content of the plugins.js file located at: myproject/config/plugins.js
> 
> ```
> module.exports = ({ env }) => ({
>   upload: {
>     config: {
>       provider: "cloudinary",
>       providerOptions: {
>         cloud_name: env("CLOUDINARY_NAME"),
>         api_key: env("CLOUDINARY_KEY"),
>         api_secret: env("CLOUDINARY_SECRET"),
>       },
>       actionOptions: {
>         upload: {},
>         delete: {},
>       },
>     },
>   },
> });
> ```
> 
> Let me know if you are able to get it working. The complete is at: https://github.com/ebitsdev/strapi-v4-cloudinary

It works with strapi v4.. my project was in v3.6.8 so I had to update

**Comment by DennisM83** [comment]
I actually rolled Strapi back to 3.6.8 version. I was able to upload the images to cloudinary using the new version but it wasn't showing up in my api.

**Comment by ebitsdev** [comment]
For the images to be included in the call, you need to call the api with ?populate=*: like: `http://localhost:3000/api/articles?populate=*`. I had the same issue and got it fixed using above. I got the inspiration from here https://forum.strapi.io/t/image-url-not-showing-on-api-call-strapi-v4/12956 and the strapi documentation https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html.

You can try and let me know if it works for you.

Thanks,

**Comment by DeploymentService** [comment]
> ulate=*

how can I download the cloudinary version specified for Strapi version 4, or what is the version of cloudinary specified for strapi version 4 please, I am having the same problem that I have followed the installation document and nothing is happening

**Comment by Hanuman2001** [comment]
Thanks man u saved the day

**Comment by viceodev** [comment]
> I am successfully running Strapi with the new cloudinary plugin @strapi/provider-upload-cloudinary. Please note that there are 2 versions of the plugin. The version of the plugin that I installed is for Strapi v4 and the other one is for Strapi v3. My current project contains: strapi v4.0.2 and @strapi/provider-upload-cloudinary. And following is the content of the plugins.js file located at: myproject/config/plugins.js
> 
> ```
> module.exports = ({ env }) => ({
>   upload: {
>     config: {
>       provider: "cloudinary",
>       providerOptions: {
>         cloud_name: env("CLOUDINARY_NAME"),
>         api_key: env("CLOUDINARY_KEY"),
>         api_secret: env("CLOUDINARY_SECRET"),
>       },
>       actionOptions: {
>         upload: {},
>         delete: {},
>       },
>     },
>   },
> });
> ```
> 
> Let me know if you are able to get it working. The complete is at: https://github.com/ebitsdev/strapi-v4-cloudinary

This did the job for me.
