### ISSUE TITLE
Consider using Loopback Next for back-end framework

### ISSUE THREAD

**Issue by hbakhtiyor** [strapi/strapi#1182]
**What is the expected behavior?**
Would be nice to see [Loopback Next](https://loopback.io/doc/en/lb4/Crafting-LoopBack-4.html) (different from old loopback 3.x version) vision and extend on top of the framework

https://github.com/strongloop/loopback-next/

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@hbakhtiyor due to the development progress on loopback next, I don't forsee this coming in the near-future. It might be possible further on but since loopback 4x is still in a dev preview state, it might be a while. 😛
