### ISSUE TITLE
Is't not possible to install with NPM 8.1.0 and Node 16.13

### ISSUE THREAD

**Issue by biapar** [strapi/strapi#11829]
Hi,

I tried to install the v4. It's not possible to install with:
➜  ~ npm -v
8.1.0
➜  ~ node -v
v16.13.0
➜  ~ 

Have you tested with latest LTS node and npm?
Thanks.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11729
