### ISSUE TITLE
Blank admin panel after running `npx create-strapi-app my-project --quickstart`

### ISSUE THREAD

**Issue by benitodotcool** [strapi/strapi#11835]
### Describe the bug

Hello, I am relatively new to the Strapi community and I want to start a new personal project using the latest version (v4.0.0). I just finished a professional project in v3.6.8 and everything went well.

The problem occurs when I run the command `npx create-strapi-app my-project -quickstart` (same problem with `yarn create strapi-app my-project`), my default browser opens a window `http://localhost:1337/admin` but I have absolutely nothing on the page.

I have tried:
- `rm -rf nodes_modules`
- `npm install`
- `npm run build`
- `npm run develop`

Unfortunately nothing changes. (I did the same steps with yarn too)

### Steps to reproduce the behavior

1. Run `npx create-strapi-app my-project --quickstart`
2.  Or run `npx create-strapi-app@latest my-project --quickstart` (accorded to `[Team/Mod] Derrick` on Discord)

### Expected behavior

Just have the missing admin panel 😢

### Screenshot

<img width="1552" alt="Strapi_blank_admin_panel" src="https://user-images.githubusercontent.com/82047125/145017770-99e64cb6-f0a6-49e4-919c-97aa4fdbacf0.png">

### Code snippets

Here is my package.json:
```
{
  "name": "strapi-backend-benitodotcool",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "4.0.0",
    "@strapi/plugin-users-permissions": "4.0.0",
    "@strapi/plugin-i18n": "4.0.0",
    "sqlite3": "5.0.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "9a0fff07-f4c9-45b7-92e1-80c71c9937f7"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```
Shouldn't I have more dependencies on Strapi?
In my Strapi v3.6.8 project my dependencies object looked like this:
```
  "dependencies": {
    "knex": "0.21.18",
    "pg": "^8.7.1",
    "pg-connection-string": "^2.5.0",
    "slugify": "^1.6.1",
    "sqlite3": "5.0.0",
    "strapi": "3.6.8",
    "strapi-admin": "3.6.8",
    "strapi-connector-bookshelf": "3.6.8",
    "strapi-plugin-content-manager": "3.6.8",
    "strapi-plugin-content-type-builder": "3.6.8",
    "strapi-plugin-email": "3.6.8",
    "strapi-plugin-i18n": "3.6.8",
    "strapi-plugin-upload": "3.6.8",
    "strapi-plugin-users-permissions": "3.6.8",
    "strapi-provider-upload-aws-s3": "^3.6.8",
    "strapi-utils": "3.6.8"
  },
```

### System

- Node.js version: `v14.17.5`
- NPM version: `6.14.14`
- Strapi version: `4.0.0`
- Operating system: `macOS Big Sur`

### Additional context

Before v4.0.0 was announced, I had planned to make a GitHub repository with a basic Strapi application (v3.6.8) containing a `config/plugins.js` file containing
```
module.exports = ({ env }) => ({
  upload: {
    provider: "aws-s3",
    providerOptions: {
      accessKeyId: env("AWS_ACCESS_KEY_ID"),
      secretAccessKey: env("AWS_ACCESS_SECRET"),
      region: env("AWS_REGION"),
      params: {
        Bucket: env("AWS_BUCKET_NAME"),
      },
    },
  },
});
```
to make it easier for me to use Strapi for each new project.
Here is the link of this [repository](https://github.com/benitodotcool/Strapi-Boilerplate)

However, when I try to clone this repository and run `npm install` then `npm run develop`, I have this problem in my console:
![Capture d’écran 2021-12-07 à 12 23 37](https://user-images.githubusercontent.com/82047125/145020720-faebaf02-ebe0-465b-ac45-0cc90edd602b.png)

I can fix this problem thanks to this post on [Stackoverflow](https://stackoverflow.com/questions/67132569/attempting-to-run-strapi-gives-module-parse-error).
> 1. Better solution.
> Check if your Strapi project is nested within another project that uses babel/webpack. I had some old files in my directory with all my projects. When I removed them, it works.
> 
> 2. Workaround solution (With every packages update, it will be back to an earlier version)
> in your strapi folder, go to → `node_modules/strapi-admin/webpack.config.js`
> locate the line → `require.resolve('@babel/preset-env’)`
> replace it with `[require.resolve('@babel/preset-env'),{ targets: 'defaults' }],`
> run the command `npm run dev`

Could this problem be correlated with the fact that the admin panel does not load in version v4.0.0?

### Thanks in advance for any help.

Benitodotcool

**Comment by Pierre-Mike** [comment]
[Blank admin panel after running](https://github.com/strapi/strapi/issues/11730)

this is related

**Comment by soupette** [comment]
@benitodotcool do you still experience this issue?

**Comment by derrickmehaffy** [comment]
Gonna close this for now, @benitodotcool if you still get the issue then reply back and we can reopen.

**Comment by Pierre-Mike** [comment]
It's working for me thanks !!!

**Comment by dotjohann** [comment]
Hi,

I've been experiencing the same issues but following the guides above it still not working :(

What details should I share for someone the be able to help me.

Thanks in advance.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
