### ISSUE TITLE
Can't install strapi-cli globally with yarn

### ISSUE THREAD

**Issue by hbakhtiyor** [strapi/strapi#1183]
**Informations**
- **Node.js version**: v10.1.0
- **yarn version**: 1.6.0
- **Strapi version**: latest of alpha version
- **Database**:
- **Operating system**: Ubuntu 18.04
 

**What is the current behavior?**
Can't install strapi-cli globally with yarn

**Steps to reproduce the problem**
just run the following command
`yarn global add strapi@alpha`

**What is the expected behavior?**

**Suggested solutions**

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by kamalbennani** [comment]
Up till now, strapi is only compatible with npm.

**Comment by lukeajtodd** [comment]
What errors do you happen to get?

I've just installed using `yarn global add strapi@alpha` on Node (v10.1.0). I am on Mac so that could have something to do with this?

**Comment by hbakhtiyor** [comment]
didn't get any errors, just the executable file doesn't exists
