### ISSUE TITLE
V4 Media Library does not visualize assets uploaded to Backblaze B2 through the Upload-S3-Plugin

### ISSUE THREAD

**Issue by MaheshCasiraghi** [strapi/strapi#11837]
Media Library in V4 Admin Interface generates CORS errors when uploading assets to Backblaze B2 S3 API, through the @strapi/provider-upload-aws-s3 plugin.

<img width="307" alt="Screen Shot 2021-12-07 at 12 58 26 PM" src="https://user-images.githubusercontent.com/645276/145025845-883eac83-0db9-419f-b047-212ed8fa3595.png">

![Screen Shot 2021-12-07 at 12 58 50 PM](https://user-images.githubusercontent.com/645276/145025899-b9378bbf-0276-41f2-91b1-bcc3ca9c7590.jpg)

**Comment by ihmpavel** [comment]
Hi, check [new documentation](https://github.com/strapi/strapi/blob/master/packages/providers/upload-aws-s3/README.md#security-middleware-configuration). 

Everything is about `CSP`...

**Comment by WardenCommander** [comment]
@MaheshCasiraghi can you share how did you setup @strapi/provider-upload-aws-s3 plugin to be used with Backblaze B2 bucket? when i try to use it i get error: "Inaccessible host: `s3.us-west-004.amazonaws.com'. This service may not be available in the `us-west-004' region."
