### ISSUE TITLE
Embedded videos not in Rich Text field

### ISSUE THREAD

**Issue by lack-of-gravitas** [strapi/strapi#11838]
Embedded videos not supported in an updated CMS? Previews for embedded videos (youtube / vimeo etc.) supported in the v4 out of the box markdown editor?

Do I have to create a custom plugin for such a basic function in what is an update 

I have tried what I expect standard markdown syntax to be and html embed

Method 1
`[![Everything Is AWESOME](http://i.imgur.com/Ot5DWAW.png)](https://youtu.be/StTqXEQ2l-Y?t=35s "Everything Is AWESOME")`

Method 2
<video controls="controls" width="100%">
<source src="(https://youtu.be/StTqXEQ2l-Y" type="video/mp4"></source>
</video> 
Image

![image](https://user-images.githubusercontent.com/10094964/145028169-ceb62888-bbd4-4d3d-804c-b13fb57e3de2.png)

### Expected behavior

A functional and feature-rich out of the box rich text field / component. The strapi headline literally says manage content easily  -- this doesn't seem very easy. Not being able to do this basic function means we cant expose this to any business users of the CMS without significant investment into a custom plugin.

Refer to **literally** any other modern CMS -- Contentful, Sanity, Ghost etc.

**Comment by ihmpavel** [comment]
Hi, as far as I know, this is only basic, nice looking Markdown editor... 

You should check (and wait for) https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/issues/33 for more advanced WYSIWYG editor.

**Comment by derrickmehaffy** [comment]
I believe at this time we don't plan to add too many features to this editor as eventually we want to swap the default editor out with a better one.

(Though @JabStrapi can reopen this if he thinks otherwise.)

Also I second @ihmpavel wait for the community ckeditor package to be updated.
