### ISSUE TITLE
Single Type Media duplication / mirroring

### ISSUE THREAD

**Issue by GradeSchool** [strapi/strapi#11831]
### Describe the bug
Version 4 Strapi- single type media automatically duplicates itself to all single types...
In v4 of Strapi- I have 4 single type entries - all are supposed to have different media (images), but they cannot be different, they are all the same image, no matter what changes I make to any entry. If I change 1 image (by editing), the other 3 are automatically updated to be the same image.  Is this expected behavior?

### Expected behavior

Each media entry should be discreet.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
