### ISSUE TITLE
Strapi query engine does not work as described in the docs.

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#11839]
### Describe the bug

I tried using the new query engine as described in the docs:
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/single-operations.html#findone

At least findOne() did not work.
descriped (not working):
```js
      offer.pdfContent = await strapi.db
        .query("api::pdf-content.pdf-content")
        .findOne({ where: { name: data.body.fullName }})
``

However I tried it "the old way" and this gave me all text fields (no relations, or components):
```js
      offer.pdfContent = await strapi.db
        .query("api::pdf-content.pdf-content")
        .findOne({ name: data.body.fullName })
```

Sadly I was not able to populate the components I need.

### Steps to reproduce the behavior

1. Query content using findOne()
2. See response

### Expected behavior

1. Works as descriped in docs
2. Please show which fields are required and which are optional in docs
3. values in components are returned
4. populate works

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.0
- Database: postgres 14
- Operating system: fedora 35

**Comment by tw1t611** [comment]
Somehow works now. I can't reproduce the error. Sorry for the noies.

**Comment by philohelp** [comment]
Hi @tw1t611 
Sorry I'm a newbie in Strapi, can I ask you where you put this part of code and where you import strapi from ? I need to migrate an existing project with some tables containing hundreds of entries and I'd like to perform bulk upsert operations. Thanks in advance.

**Comment by tw1t611** [comment]
@philohelp strapi will provide a way to migrate data in Q3 this year, so your probably better off waiting for that.

The new query engine works like this (with nested population). It mustn't be imported within the controller.
```js
    const body = await strapi.db.query("api::body.body").findOne({
      where: { fullName: data.body.fullName },
      populate: {
        model: {
          populate: {
            topSpeed: true,
            power: true,
          },
        },
        previewImage: true,
        pdfContent: {
          populate: {
            accessories: {
              populate: {
                accessory: true,
              },
            },
          },
        },
      },
    });
```

I needed to migrate manually, which wasn't easy because you also need a way to uniquely identify collections and figure out how to set relations to them. If you really want to do it, I'd suggest to

1. Distinguish between languages for every migration script
2. Write a migration script for each collection type and migrate data only
3. Migrate only relations per collection type
4. Upload files manually
5. Migrate file relations

**Comment by philohelp** [comment]
Thanks for the tips. I'm experimenting this with four different databases, no real schema and a dead line in a few weeks - terrible experience. The query engine can only be used inside a controller, right ?

**Comment by tw1t611** [comment]
yes, otherwise you'd need to use the rest api.

**Comment by philohelp** [comment]
Ok, and rest api doesn't do bulk insert. I'll try the query api.
