### ISSUE TITLE
Cannot populate fields, components, dynamic zones together in GET api

### ISSUE THREAD

**Issue by milinpaul** [strapi/strapi#11836]
### Describe the bug

[v4]
I'm trying to setup strapi for our marketing website. I need to create a blog page with `title`, `featureimage`(Media) and `contents` (dynamic zones). 
I need to fetch the all the fields including title, `featureimage` and dynamic zone `contents`. 
But I tried all the possibilities for populating mention in [this doc](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population) but everything is in vain.  

Am I missing something ?? 

### Expected behavior

The GET api should returns as follows: 

```json
"data": [
    {
      "id": 1,
      "attributes": {
        "title": "Test Article",
          // Media input
          "featuredimage": {
            "id": 1,
            "alt": "",
            "media": {
              "data": [
                {
                  "id": 1,
                  "attributes": {
                    "name": "17520.jpg",
                    "formats": {
                      // ...
                    },
                    // ...
                  }
                }
              ]
            },
          // Dynamic Zone
           "content": [
            {
              "id": 1,
              "__component": "blogpost.image"
            },
           {
             "id": 16,
             "__component": "blogpost.richtext",
             "value": "this is something fishy"
            }
          ]
      }
  ],
  "meta": {
    // ...
}
```

### System

- Node.js version: v12
- NPM version:
- Strapi version: v4
- Database: Postgres (Docker)
- Operating system: OS X

**Comment by zeroseed** [comment]
I also face the same issue 
my dynamic zone only showing __component object name , the content of it are hidden

while on v3 without any ?populate query string I can populate all the fields including dynamic zone
v4 is quite new and still need improvement in my opinion

**Comment by milinpaul** [comment]
@zeroseed Seems to be. If you need only to populate dynamic zone you can use `GET /api/endpoint?populate[fieldName][populate]=*`
For me, I need to list the media fields, components and dynamic zone together which I cannot figure out from `populate` params.

**Comment by STih07** [comment]
+1

**Comment by smoothdvd** [comment]
GET /api/endpoint?populate=*

**Comment by tomnovotny7** [comment]
We are using this function for now:
```
const getFullPopulateObject = (modelUid, maxDepth = 20) => {
  if (maxDepth <= 1) {
    return true;
  }
  if (modelUid === "admin::user") {
    return undefined;
  }

  const populate = {};
  const model = strapi.getModel(modelUid);
  for (const [key, value] of Object.entries(
    getModelPopulationAttributes(model)
  )) {
    if (value) {
      if (value.type === "component") {
        populate[key] = getFullPopulateObject(value.component, maxDepth - 1);
      } else if (value.type === "dynamiczone") {
        const dynamicPopulate = value.components.reduce((prev, cur) => {
          const curPopulate = getFullPopulateObject(cur, maxDepth - 1);
          return curPopulate === true ? prev : merge(prev, curPopulate);
        }, {});
        populate[key] = isEmpty(dynamicPopulate) ? true : dynamicPopulate;
      } else if (value.type === "relation") {
        const relationPopulate = getFullPopulateObject(
          value.target,
          maxDepth - 1
        );
        if (relationPopulate) {
          populate[key] = relationPopulate;
        }
      } else if (value.type === "media") {
        populate[key] = true;
      }
    }
  }
  return isEmpty(populate) ? true : { populate };
};
```

Used for example like this:
```
const modelUid = "api::page.page";

module.exports = createCoreController(modelUid, ({ strapi }) => ({
  async find(ctx) {
    const { query } = ctx;

    const { results, meta } = await strapi.service(modelUid).find({
      ...getFullPopulateObject(modelUid),
      ...query,
    });

    const sanitizedEntities = await this.sanitizeOutput(results, ctx);

    return {
      data: sanitizedEntities,
      meta,
    };
  },
}));
```

**Comment by derrickmehaffy** [comment]
Let's keep the population topic in https://github.com/strapi/strapi/issues/11787

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/discussion-regarding-default-population-of-rest/13395/7

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/components-fields-not-showing-on-api-response/14103/2

**Comment by LarssonHenrik** [comment]
This might help: https://www.npmjs.com/package/strapi-plugin-populate-deep

**Comment by digitalextremist** [comment]
Many thanks to @LarssonHenrik. That did the trick. Now to limit the fields returned 😅

**Comment by brianwachira** [comment]
Many thanks to @LarssonHenrik , it works even in 2023

**Comment by anis072** [comment]
> Many thanks to @LarssonHenrik. That did the trick. Now to limit the fields returned 😅
this code can limit the fields returned 
`const getFullPopulateObject = (modelUid, maxDepth = 20, parentModelUid = null) => {
  if (maxDepth <= 1) {
    return true;
  }
  if (modelUid === "admin::user") {
    return undefined;
  }

  const populate = {};
  const model = strapi.getModel(modelUid);
  for (const [key, value] of Object.entries(
    getModelPopulationAttributes(model)
  )) {
    if (value) {
      if (value.type === "relation" && value.target === parentModelUid) {
        continue; 
      }
      if (value.type === "component") {
        populate[key] = getFullPopulateObject(value.component, maxDepth - 1);
      } else if (value.type === "dynamiczone") {
        const dynamicPopulate = value.components.reduce((prev, cur) => {
          const curPopulate = getFullPopulateObject(cur, maxDepth - 1);
          return curPopulate === true ? prev : merge(prev, curPopulate);
        }, {});
        populate[key] = isEmpty(dynamicPopulate) ? true : dynamicPopulate;
      } else if (value.type === "relation") {
        const relationPopulate = getFullPopulateObject(
          value.target,
          maxDepth - 1,
          modelUid // Pass the current model as parent
        );
        if (relationPopulate) {
          populate[key] = relationPopulate;
        }
      
        
      } else if (value.type === "media") {
        populate[key] = true;
      }
    }
  }
  return isEmpty(populate) ? true : { populate };
};`

**Comment by killthekitten** [comment]
The solutions above assume a rather simple structure of the dynamic zone which won't work in all cases. If you find that only some dynamic zone fields are loaded correctly, you might need to change the dynamic zone code to this:

```
} else if (value.type === "dynamiczone") {
        const blocks = value.components
          .map((component) => ({
            [component]: getFullPopulateObject(component, maxDepth - 1, ignore),
          }))
          .reduce((result, block) => ({ ...block, ...result }), {});
        populate[key] = { on: blocks };
      }
```

Related issue in `strapi-plugin-populate-deep`: https://github.com/Barelydead/strapi-plugin-populate-deep/issues/51
