### ISSUE TITLE
Documentation plugin settings don't work

### ISSUE THREAD

**Issue by Coppola-Aleandro** [strapi/strapi#11840]
### Describe the bug

The settings of documentation plugin not work

### Steps to reproduce the behavior
The installation is new Hands-On: 
https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html

<img width="325" alt="Schermata 2021-12-07 alle 16 24 24" src="https://user-images.githubusercontent.com/5457653/145057152-00d9f6d2-5671-4888-80b5-9564a7489d1f.png">

I use this settings.json (I try to change version in "2.0.0" or change Title)
```
{
  "openapi": "3.0.0",
  "info": {
    "version": "2.0.0",
    "title": "DOCUMENTATION Demo",
    "description": "",
    "termsOfService": "YOUR_TERMS_OF_SERVICE_URL",
    "contact": {
      "name": "TEAM",
      "email": "contact-email@something.io",
      "url": "mywebsite.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "x-strapi-config": {
    "path": "/documentation",
    "showGeneratedFiles": true,
    "pluginsForWhichToGenerateDoc": ["email", "upload", "users-permissions"]
  },
  "servers": [
    {
      "url": "http://localhost:1337",
      "description": "Development server"
    },
    {
      "url": "YOUR_STAGING_SERVER",
      "description": "Staging server"
    },
    {
      "url": "YOUR_PRODUCTION_SERVER",
      "description": "Production server"
    }
  ],
  "externalDocs": {
    "description": "Find out more",
    "url": "https://strapi.io/documentation/"
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {},
  "tags": [],
  "components": {}
}
```

### Expected behavior

I should see new documentation -> documentation / 2.0.0

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16.11.1
- Yarn version: v1.22.17
- Strapi version: v4
- Database: Postgres
- Operating system: MacOS

### Additional context
<img width="520" alt="Schermata 2021-12-07 alle 16 26 29" src="https://user-images.githubusercontent.com/5457653/145057506-fc57a60f-1a86-41bc-b3dd-590adeb83f2a.png">

**Comment by mikaisosipila** [comment]
I just tested this out and it seems to work just fine at least on my setup:

![Code_9iLEknz4in](https://user-images.githubusercontent.com/92733164/145215809-01104c72-3d1b-41dc-82de-a75b0fca88db.png)

**Comment by Coppola-Aleandro** [comment]
> I just tested this out and it seems to work just fine at least on my setup:
> 
> ![Code_9iLEknz4in](https://user-images.githubusercontent.com/92733164/145215809-01104c72-3d1b-41dc-82de-a75b0fca88db.png)

You use config/settings.json?

**Comment by zhostasa** [comment]
Hello, I seem to have the same issue, trying out settings in both /src folder as seems correct and root project folder, as documentation suggests - https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings .

**Comment by shinework** [comment]
Same issue here :)

**Comment by luccadumas** [comment]
Same issue here :(

**Comment by witek1902** [comment]
Guys, 
any progress? ;)

**Comment by Coppola-Aleandro** [comment]
> Guys, 
> 
> any progress? ;)

No! 😔

**Comment by roelbeerens** [comment]
I've created a PR to fix this, hopefully this will be merged soon.
