### ISSUE TITLE
v4 Creating relations with/populating users causes 500

### ISSUE THREAD

**Issue by Cpaczek** [strapi/strapi#11847]
### Describe the bug

Found while trying to reproduce: https://forum.strapi.io/t/strapi-v4-no-relation-fields-in-user-collection-types/13226

When trying to populate relations on the User collection from the user-permission plugins returns a 500 with this error in console.

```
[2021-12-08 03:56:53.273] error: select `t0`.* from `up_users` as `t0` where (`t0`.`populate` = '*') - SQLITE_ERROR: no such column: t0.populate
Error: select `t0`.* from `up_users` as `t0` where (`t0`.`populate` = '*') - SQLITE_ERROR: no such column: t0.populate
```

### Steps to reproduce the behavior

1. `npx create-strapi-app user-populate-test`
2. Quickstart
3. Create new collection such as `Article` and give it any relationship (I used many to many)
4. Give permission to find `Article` and `Users` to the public role
5. Add dummy user and article and give relation to eachother
6. GET `http://localhost:1337/api/users?populate=*`

However, this does work if you were to populate the other way around `http://localhost:1337/api/articles?populate=*`

### Expected behavior

Populates relation data

### Code snippets

Article Schema:
```
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Article"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string"
    },
    "users_permissions_users": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "plugin::users-permissions.user",
      "inversedBy": "articles"
    }
  }
}

```

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: SQLite
- Operating system: Windows 10

**Comment by fristyr** [comment]
I have almost the same issue 
https://forum.strapi.io/t/strapi-v4-no-relation-fields-in-user-collection-types/13226
Just instead of Articles described above,
I created User-Roles, my custom collection types, can be anything actually, let's say reviews relation to Users

**Comment by MaheshCasiraghi** [comment]
Confirmed, this also happens with Postgres 14 / Node 16.

**Comment by derrickmehaffy** [comment]
Duplicate #11789
