### ISSUE TITLE
Plugin styles are getting overridden in strapi v4

### ISSUE THREAD

**Issue by rajatdangat07** [strapi/strapi#11849]
### Describe the bug

The styles of [strapi-plugin-ckeditor5](https://www.npmjs.com/package/@colton75/strapi-plugin-ckeditor5) are getting overridden by some other styles.

### Steps to reproduce the behavior

1. Create a new strapi project.
2. Install the [strapi-plugin-ckeditor5](https://www.npmjs.com/package/@colton75/strapi-plugin-ckeditor5) plugin and rebuild the project.
3. Create a collection and in that collection create a field of type rich text.
4. Create an entry in that collection.
5. Type something in that field and try to apply bold or italic to that text.
6. The styles does not get applied because they are getting overridden by some other styles.
7. Inspect the text you have written and check the styles applied to that text to confirm this.

### Expected behavior

Plugin styles should not be overriden.

### System

- Node.js version: 14.18.1
- NPM version: 8.1.4
- Strapi version: 4.0.0

**Comment by derrickmehaffy** [comment]
related https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5/issues/33

**Comment by ihmpavel** [comment]
Hi,

we are using our own version of `ckeditor` with `v4` for more than two weeks.

We needed to tweak the styles as follows

```
.ck-editor__main {
  /* Fix line height */
  .ck-editor__editable {
    line-height: initial;
  }
  /* Revert font styling */
  div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
    font: revert;
  }
  /* Revert list styling */
  ul, ol {
    list-style: initial;
    margin-left: 16px;
  }
}
```

**Comment by colton75** [comment]
This issue has been fixed in [strapi-plugin-ckeditor5](https://www.npmjs.com/package/@colton75/strapi-plugin-ckeditor5). So I think this issue should be closed now.

**Comment by derrickmehaffy** [comment]
Looks like based on these two commits:

https://github.com/colton75/strapi-plugin-ckeditor5/commit/d619785b47995ec3810d00200e44045fa761d31e
https://github.com/colton75/strapi-plugin-ckeditor5/commit/ae956adcc540907387bde2632330f760cfd404d8

Closing :)
