### ISSUE TITLE
Media objects is not displayed

### ISSUE THREAD

**Issue by celsoft** [strapi/strapi#11843]
### Describe the bug

Media objects is not displayed. Local storage.

### Screenshots

![1](https://user-images.githubusercontent.com/5567863/145176005-9bd44551-6b2b-4b72-80ad-4e4594ea1c7d.png)
![2](https://user-images.githubusercontent.com/5567863/145176010-134f3960-d7ea-4ba7-a667-b2bf65b479d7.png)
![3](https://user-images.githubusercontent.com/5567863/145177592-06db5431-a91b-46f2-abda-127c3b2ab4b1.png)

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: v4.0.0
- Database: mysql
- Operating system: windows 11

### Additional context

Filled and empty are not displayed.

**Comment by tuanictu97** [comment]
me too =((

**Comment by tuanictu97** [comment]
Same issues here: https://github.com/strapi/strapi/issues/11767
You need to add populate=mediaAttributeName or populate=* in your query params now.
thanks a lot. It works

**Comment by celsoft** [comment]
> Same issues here: #11767 You need to add populate=mediaAttributeName or populate=* in your query params now. thanks a lot. It works

Thank you.
