### ISSUE TITLE
Api response doesnt send image url

### ISSUE THREAD

**Issue by gobiTugu** [strapi/strapi#11842]
Strapi v4 /api response doesnt send image url how to get url from api response any suggestion or fix?

![New Project](https://user-images.githubusercontent.com/95322515/145119890-e152575b-3899-4658-851b-261ee6f55cea.png)

Response

`{"data":[{"id":1,"attributes":{"date":"2021-02-25","description":"ТУЗ-ийн ээлжит хурал","createdAt":"2021-12-07T00:38:36.318Z","updatedAt":"2021-12-07T00:38:38.253Z","publishedAt":"2021-12-07T00:38:38.248Z"}},{"id":2,"attributes":{"date":"2021-02-19","description":"Ногдол ашгийн шийдвэр","createdAt":"2021-12-07T00:38:59.480Z","updatedAt":"2021-12-07T00:39:01.536Z","publishedAt":"2021-12-07T00:39:01.533Z"}},{"id":3,"attributes":{"date":"2021-03-09","description":"2020 оны Жилийн үйл ажиллагааны тайлан","createdAt":"2021-12-07T00:39:37.031Z","updatedAt":"2021-12-07T00:39:39.046Z","publishedAt":"2021-12-07T00:39:39.043Z"}},{"id":5,"attributes":{"date":"2021-04-26","description":"ТУЗ-ийн ээлжит хурал","createdAt":"2021-12-07T00:53:44.402Z","updatedAt":"2021-12-07T00:53:46.321Z","publishedAt":"2021-12-07T00:53:46.317Z"}},{"id":6,"attributes":{"date":"2021-04-28","description":"Аудитлагдсан санхүүгийн тайлан","createdAt":"2021-12-07T00:54:06.021Z","updatedAt":"2021-12-07T00:54:13.227Z","publishedAt":"2021-12-07T00:54:13.224Z"}},{"id":4,"attributes":{"date":"2021-04-23","description":"Хувьцаа эзэмшигчдийн ээлжит хурал","createdAt":"2021-12-07T00:53:22.859Z","updatedAt":"2021-12-07T00:54:17.648Z","publishedAt":"2021-12-07T00:54:17.644Z"}},{"id":7,"attributes":{"date":"2021-06-04","description":"ТУЗ-ийн ээлжит хурал","createdAt":"2021-12-07T00:54:47.943Z","updatedAt":"2021-12-07T00:54:49.620Z","publishedAt":"2021-12-07T00:54:49.593Z"}},{"id":8,"attributes":{"date":"2021-07-24","description":"2021 оны Хагас жилийн санхүүгийн тайлан","createdAt":"2021-12-07T00:55:21.153Z","updatedAt":"2021-12-07T00:55:23.143Z","publishedAt":"2021-12-07T00:55:23.140Z"}},{"id":9,"attributes":{"date":"2021-08-02","description":"ТУЗ-ийн ээлжит хурал","createdAt":"2021-12-07T00:55:49.204Z","updatedAt":"2021-12-07T00:55:50.726Z","publishedAt":"2021-12-07T00:55:50.722Z"}},{"id":10,"attributes":{"date":"2021-08-10","description":"Хагас жилийн үйл ажиллагааны тайлан","createdAt":"2021-12-07T00:56:10.513Z","updatedAt":"2021-12-07T00:56:13.128Z","publishedAt":"2021-12-07T00:56:13.124Z"}},{"id":11,"attributes":{"date":"2021-08-26","description":"МХБ - Хагас жилийн тайлан, танилцуулга","createdAt":"2021-12-07T00:56:28.007Z","updatedAt":"2021-12-07T00:56:29.527Z","publishedAt":"2021-12-07T00:56:29.521Z"}},{"id":12,"attributes":{"date":"2021-10-05","description":"ТУЗ-ийн ээлжит хурал","createdAt":"2021-12-07T00:56:46.091Z","updatedAt":"2021-12-07T00:56:47.928Z","publishedAt":"2021-12-07T00:56:47.924Z"}},{"id":13,"attributes":{"date":"2021-12-27","description":"ТУЗ-ийн ээлжит хурал","createdAt":"2021-12-07T00:57:01.029Z","updatedAt":"2021-12-07T00:57:02.542Z","publishedAt":"2021-12-07T00:57:02.538Z"}},{"id":14,"attributes":{"date":"2022-01-24","description":"2021 оны Жилийн санхүүгийн тайлан","createdAt":"2021-12-07T00:57:32.813Z","updatedAt":"2021-12-07T00:57:34.738Z","publishedAt":"2021-12-07T00:57:34.735Z"}}],"meta":{"pagination":{"page":1,"pageSize":25,"pageCount":1,"total":14}}}`

**Comment by derrickmehaffy** [comment]
See: https://github.com/strapi/strapi/issues/11787

This is intended
