### ISSUE TITLE
Extending the User-Permissions Plugin with a beforeCreate lifecycle event does not work.

### ISSUE THREAD

**Issue by MaheshCasiraghi** [strapi/strapi#11859]
I have been trying to trigger a beforeCreate lifecycle event for the User content-type of the User-Permissions Plugin, by adding the lifecycles.js or models/User.js files. Also, tried different other methods. Nothing seems to work, and it seems to be a bug/problem presented by many users in Discord. Is it a bug? Is there a way to implement this, which is not covered by documentation yet?

**Comment by MaheshCasiraghi** [comment]
It might be the same bug of #11828

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11828
