### ISSUE TITLE
Install with npx provides yarn commands instead of npm

### ISSUE THREAD

**Issue by spyesx** [strapi/strapi#11858]
### Describe the bug

I installed strapi v4 with [the command given in the documentation](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/cli.html#creating-a-strapi-project) for NPM.

```bash
npx create-strapi-app@latest my-project
```

Therefore, I expect to use NPM as a package manager. However, the installation asks me to use Yarn instead. I don't have Yarn and I asked for NPM in purpose :) Warning, `npm run develop` still works :)  It's just that, the message, should mention `npm` instead.

```
  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.
  ```

I still tried a `npm run develop`

### Steps to reproduce the behavior

From a Node 16 Docker container:

```bash
node@8a6996feb076:/var/www/app$ npx create-strapi-app@latest my-strapi-app
? Choose your installation type Custom (manual settings)
? Choose your default database client mysql
? Database name: strapi
? Host: mariadb
? Port: 3306
? Username: strapi
? Password: ************************
? Enable SSL connection: No

Creating a project with custom database options.
Creating a new Strapi application at /var/www/app/my-strapi-app.
Creating files.
Dependencies installed successfully.

Your application was created at /var/www/app/my-strapi-app.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /var/www/app/my-strapi-app
  yarn develop

node@8a6996feb076:/var/www/app$ 
```

### Expected behavior

Maybe something like the following?

```
Available commands in your project:

  npm run develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  npm run start
  Start Strapi without watch mode.

  npm run build
  Build Strapi admin panel.

  npm run strapi
  Display all available commands.

You can start by doing:

  cd /var/www/app/my-strapi-app
  npm run develop
  ```
### System

- Node.js version: v16.4.2  
  ```bash
  $ node -v
  v16.4.2
  ```
- NPM version: 7.18.1 
  ```bash
  $ npm -v
  7.18.1
  ```

- Strapi version: v4  
  ```bash
  $ cat package.json | grep @strapi/strapi
    "@strapi/strapi": "4.0.0",
  ```
- Database: mariadb but it isn't involved
- Operating system: Official Docker image for Node 16 based on Debian Buster

```
node@8a6996feb076:/$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by derrickmehaffy** [comment]
We check if `yarnpkg` responds and if it does then we use yarn. Attempting to reproduce on a clean system with no yarn at all:

![image](https://user-images.githubusercontent.com/8593673/145517184-6ddc1780-3d3d-4ac0-861f-65d591e93b3d.png)

Closing until more reproduction information can be provided.

**Comment by spyesx** [comment]
Hi ! Thank you for your answer. I can read this screenshot, indeed. However it looks like you did not type the same command to reproduce the result. Reproduction information are provided.

Yours is: `npx create-strapi-app@latest testnode --quickstart --no-run`.

Mine is: `npx create-strapi-app@latest my-strapi-app`. No `quickstart` and no `no-run`.

Also, you are on Ubuntu 20.04 while my post mention Docker Node 16 (which is based on Debian 10).

![Screenshot 2021-12-10 at 07 42 24](https://user-images.githubusercontent.com/372514/145529399-19b62c54-ac47-4e06-9c24-29056796b15a.png)

I don't know what to add. You have my screen and all commands :)

**Comment by spyesx** [comment]
Oh ! Yes, I know what to add :)

```bash
root@2b4b0a2ca7bb:/var/www/app# yarn -v
1.22.5
```

Here, Yarn is included in the image `node:16`. This is why the test is `true`.

However, I still typed `npx`. Is there a way to display the right Strapi commands? This is like typing `apt-get install` being prompted 

> If you want to search for more packages type `yum search`.

**Comment by derrickmehaffy** [comment]
> Oh ! Yes, I know what to add :)
> 
> ```shell
> root@2b4b0a2ca7bb:/var/www/app# yarn -v
> 1.22.5
> ```
> 
> Here, Yarn is included in the image `node:16`. This is why the test is `true`.
> 
> However, I still typed `npx`. Is there a way to display the right Strapi commands? This is like typing `apt-get install` to be prompted
> 
> > If you want to search for more packages type `yum search`.

No, simple answer is remove yarn. It's implied that if yarn exists you intend to use it.
