### ISSUE TITLE
Documentation plugin bug

### ISSUE THREAD

**Issue by mstys** [strapi/strapi#11856]
Hi, found following issue.
When I create a new collection type with **required_field** property for one or many fields 
only fields with `required: true` option is shown in POST .

```json
{
  "kind": "collectionType",
  "collectionName": "conf_register_form2s",
  "info": {
    "singularName": "conf-register-form-2",
    "pluralName": "conf-register-form2s",
    "displayName": "confRegisterForm2",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "conference": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::conference.conference"
    },
    "workshops": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::workshop.workshop"
    },
    "email": {
      "type": "email",
      "required": true,
      "unique": true
    },
    "payment": {
      "type": "boolean",
      "default": false,
      "required": true
    },
   "name": {
      "type": "string"
    }
  }
}
```

Swagger:
```json
{
  "data": {
    "email": "user@example.com",
    "payment": true
  }
}
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by pcrossnz** [comment]
Second this issue
