### ISSUE TITLE
Unable to save User Permissions Advanced settings to turn off email sign-ups

### ISSUE THREAD

**Issue by amaurer** [strapi/strapi#11854]
### Describe the bug

When saving the settings in Admin for user-permissions -> Advanced and turning off Email sign-ups, there is a validation error preventing the save, even though, the field is not editable or applicable. 

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/561465/145244650-8f370ac2-c389-4e1c-9056-d3f6eda47c3f.png)

### Expected behavior

Be able to save the settings if `Enable sign-ups` is turned off. 

### System

- Strapi version: 4
- Database: MySQL

**Comment by Cpaczek** [comment]
Duplicate: #11715 <-work around in here

**Comment by derrickmehaffy** [comment]
Duplicate https://github.com/strapi/strapi/issues/11715
