### ISSUE TITLE
Collection type with dynamic zone - does not save media fields in the dynamic zone component

### ISSUE THREAD

**Issue by sup-at-nessa** [strapi/strapi#11857]
### Describe the bug

I created a reusable component, which had media selected with single media - image type in advanced settings.
I added this component to the collection type as a dynamic zone. But when I try to actually upload image into the dynamic zone from the content manager, the PUT method  response doesn't really show the media response added.

I tried creating a media type field directly on the collection type, this media field works. Its just the media field inside a dynamic zone I guess.

### Screenshots

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/89987208/145386561-c64c4bf4-0513-4cc3-981a-40a24edcd2c1.png">

### System

- Node.js version:  v14.15.4
- NPM version: 6.14.10
- Strapi version:  v4.0.0
- Database: local sqlite
- Operating system: macOS

**Comment by martincapek** [comment]
Do you have any other component with item -> image in that dynamic zone?

**Comment by derrickmehaffy** [comment]
Attempted to reproduce using local and aws-s3 and both work fine. Need more information from the user, marking as closed until more information is provided.
