### ISSUE TITLE
Relations with 1-N to same content-type becomes 1-1 relation

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1186]
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: MongoDB
- **Operating system**: Windows 10

**What is the current behavior?**

Adding a relation from a content-type to itself does not work for 1-N relations. After creation of the content-type, the server restarts and clicking on the content-type shows that the relation is indeed 1-N. But when creating a new object of that content-type, the content-type becomes a 1-1 relation for no apparant reason. N-N relations also work like they should. 

**Steps to reproduce the problem**

1) create a new content-type with a name and a 1-N relation with itself
2) navigate to the view of all content-types and add a new object of the content-type with a name, and save it
3) add a second object of that content-type in similar fashion
4) add a third object of that content-type and attempt to add the other 2 objects of that content-type to the object. The dropdown list now only allows to choose 1 of the 2 other objects, not both. 
5) returning to the content-type settings, the content-type magically became a 1-1 relation

**What is the expected behavior?**

1-N relations should get saved and not change to 1-1 when creating a new object

**Suggested solutions**

n.a.

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
I have noticed this as well when looping a relation back on itself.

**Comment by lauriejim** [comment]
@piere129 Can you confirm, it's still happen with new Strapi version (`3.0.0-alpha.12.2`)?

**Comment by lauriejim** [comment]
Okay I have some news about this issue. The content type builder not write the good lines in the model.
In one case it write `collection` in both side and the relation became `manyToMany` or `model` and the relation became `oneToOne`.
I think it come from the equalizer we use to apply the relation update in the other model. in our case the other model is the model himself.

Start investigation to fix it.

**Comment by lauriejim** [comment]
It's a frontend issue. The relation information sended is the same for both attributes.
In my case `oneToMany`

![relation-himself](https://user-images.githubusercontent.com/5716596/40921876-fa14aee4-6810-11e8-9c31-7bd6770783e2.png)
