### ISSUE TITLE
/users-permissions/permissions endpoint response issue

### ISSUE THREAD

**Issue by makkahwi** [strapi/strapi#11876]
/users-permissions/permissions endpoint response issue

When I call a getAll for the specified end point, it returns all application controls' permissions as false, although the user making the api call has some granted permissions from strapi role permission settings.

In other words, what I'm trying to do is to call the permissions from the endpoint above to know what's allowed n not allowed for a user withing the application. But all I get is incorrect response with all permissions to be false.

### Steps to reproduce the behavior

1. In strapi admin panel, got to Settings > USERS & PERMISSIONS PLUGIN  > roles
2. Pick any role and adjust the application permissions & allow that role to reach endpoint above..
3. In the fronted application, send an api request to the endpoint with jwttoken in header.

### Expected behavior

Get the permissions of the user which send the api call. Instead I get a response with incorrect data (all permissions in response appear to be false).

### Screenshots

I allow user to get access to find endpoint of "Attendance collection"
![image](https://user-images.githubusercontent.com/72427410/145705048-fdc764b3-4cc2-4f11-8ddd-c93c1f178b47.png)

I allow the same user to get permissions endpoint
![image](https://user-images.githubusercontent.com/72427410/145705062-9717aa84-85a1-467b-b8a4-aa450c00f737.png)

when I call the api to getall permissions, I get this wrong data
![image](https://user-images.githubusercontent.com/72427410/145705066-d85817b5-bfa5-497b-b9ab-181b1962ace3.png)

You can see here in the database that this is data i'm trying to get
![image](https://user-images.githubusercontent.com/72427410/145705494-9575c4ee-c6d9-438d-8a5f-2c97a061c717.png)

please note that the api response isn't true even for public or default authenticated roles 

### Code snippets

![image](https://user-images.githubusercontent.com/72427410/145705144-5d5f9629-e874-4163-abe9-4874e6dc9d93.png)
I did try to include in the params of the getall {role: 3} / {user-permissions_role: 3}, but still got the same result

![image](https://user-images.githubusercontent.com/72427410/145705153-60594a9b-52c7-4db8-8a5c-e5ef1ee3bcbf.png)

with jwtoken included in api call header of course

### System

- Node.js version: v14.16.1
- NPM version: 6.14.12
- YARN version: 1.22.10
- Strapi version: v3.6.8
- Database: postgresql 
- Operating system:

**Comment by derrickmehaffy** [comment]
We are no longer fixing v3 issues unless they are considered critical or security related.

see: https://github.com/strapi/strapi/issues/11726
