### ISSUE TITLE
[v4] 

### ISSUE THREAD

**Issue by dostuffthatmatters** [strapi/strapi#11879]
### Describe the bug

When using an email provider other than the ones from `@strapi/provider-email-...` the provider name is used as the package name. For example, when using `strapi-provider-email-postmark` and I set the provider to "postmark" then strapi will look for an npm package named `postmark` and not `strapi-provider-email-postmark`. In this case `strapi-provider-email-postmark` depends on the package `postmark` (which therefore exists) therefore the resulting error is very confusing.

With a `plugins.js` looking like this:
```js
module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'postmark',
      providerOptions: {
        // ...
      },
      settings: {
         // ...
      },
    },
  }
});
```
... the server responds with an error message `provider.init` is not a function. If we change the config to the following:
```js
module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'strapi-provider-email-postmark',
      providerOptions: {
        // ...
      },
      settings: {
         // ...
      },
    },
  }
});
```
... it does work (after modifying that provider package to work with Strapi v4, see: https://github.com/ijsto/strapi-provider-email-postmark/pull/9).

Here is the code where this "provider-name to package-name"-translation happens: 
https://github.com/strapi/strapi/blob/f80b89fe69a95c597aa9a879d39a1ac1a9ba6a4f/packages/core/email/server/bootstrap.js#L5-L27

The question now is: Is it intentional that one has to set the provider name to "strapi-provider-email-postmark", or is this an unwanted thing?

### Steps to reproduce the behavior

The described scenario occurs in `f80b89f`. I am using version `3.5.1` from "strapi-provider-email-postmark" and modified it to work with Strapi v4.

### Expected behavior

I would expect the provider name to be "postmark" instead of "strapi-provider-email-postmark"

### System

- Node.js version: v16
- NPM version:
- Strapi version: v4
- Database: MySQL
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
This is intended in the v4, you should use the full name of the package now. We did this in order to ensure users could use scoped packages (either their own or forks of ours)

**Comment by dostuffthatmatters** [comment]
@derrickmehaffy Ok, thank you!

**Comment by nohehf** [comment]
Could you please update the docs for this, had to found this issue to make it work.

**Comment by derrickmehaffy** [comment]
> Could you please update the docs for this, had to found this issue to make it work.

which doc are you referring to

**Comment by nohehf** [comment]
> > Could you please update the docs for this, had to found this issue to make it work.
> 
> 
> 
> which doc are you referring to

None in particular but it will be cool to have a little warning callout in the plugins sections to explain the changes of the config file structure, it would allow to use a lot of the community maintained plugins that are now broken because of this
Thank you 🙂

**Comment by dostuffthatmatters** [comment]
Something similar to this: https://github.com/ijsto/strapi-provider-email-postmark#example
