### ISSUE TITLE
[v4]Documentation API plugin not completed

### ISSUE THREAD

**Issue by qhoirulanwar** [strapi/strapi#11875]
### Describe the bug

1. the documentation API not complete, just email and Upload - file
2. The settings of documentation plugin not work

### Steps to reproduce the behavior

1. The installation  yarn strapi install documentation
2. Go to (http://localhost:1337/documentation/)

### Expected behavior

I should see the completed documentation like strapi v3

### Screenshots

![image](https://user-images.githubusercontent.com/22901097/145700481-862fe617-3659-46a5-a0fa-0d1186f9e56e.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: v4
- Database: postgresql
- Operating system: windows

### Additional context

![image](https://user-images.githubusercontent.com/22901097/145700572-c099a2fc-ba0d-409f-9c1d-26c8b7f41313.png)

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11840
