### ISSUE TITLE
[V4] Please add mongodb i have many projects on it

### ISSUE THREAD

**Issue by mihirpipermitwala** [strapi/strapi#11877]
## Feature request

I created many projects which use NoSQL (MongoDB)
but now I can't update the version to v4 please support for small developers which use NoSQL(MongoDB)

**Comment by derrickmehaffy** [comment]
Sorry but it's not gonna happen, you can read these links:

https://github.com/strapi/strapi/issues/10186
https://forum.strapi.io/t/mongodb-compatibility-delayed-on-v4/4549
https://strapi.io/blog/mongo-db-support-in-strapi-past-present-and-future

The v4 has completed removed all reference to the MongoDB connector (the code doesn't exist anymore) and we no longer have a connector based system.

MongoDB (the company/team) were supposed to work on their own connector and we would help them integrate it into Strapi v4 but as of right now we have not heard from them at all and we (Strapi the company) **will not bring back MongoDB or any noSQL database for the foreseeable future**.

NoSQL is not the direct we want to move in nor do we think it would be a good fit for the features we have planned for Strapi, we are not the only Headless/Decoupled CMS in the market doing this, Relational Databases are extremely common in the CMS world for very good reasons.

Sorry but it's not gonna happen.
