### ISSUE TITLE
Can't use a new enumeration value

### ISSUE THREAD

**Issue by fcolomas** [strapi/strapi#11872]
### Describe the bug

When you add a new value to an Enumeration and try to use it on a content, new or trying to modifiy an existing one on the admin console, it doesn't allow you, you get on the server a "error: Not null constraint violation." and on the admin console a bad request.

### Steps to reproduce the behavior

1. Go to any existing content type that has an enumeration with more than one item
2. Add an enumeration item, any place 
3. Save the content type
4. In the content manager try to add a new content with the recently added item for the enumeration
5. Save the content
6. The error appears

### Expected behavior

The new item for the enumeration is saved on the new or modified content.

### Screenshots

![image](https://user-images.githubusercontent.com/23507676/145638256-1a588a56-83bd-419f-9552-27b9a25084cb.png)

### Code snippets

N/A

### System

- Node.js version: 14.18.2
- NPM version: 6.14.15
- Strapi version: 4
- Database: Default installation
- Operating system: Ubuntu 20

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
fixed by: https://github.com/strapi/strapi/pull/11864

**Comment by goodpixels** [comment]
I am having the same issue running 4.0.0. When will this be available in a stable release?

**Comment by Webbist-dev** [comment]
You can patch this yourself for now using a patch from patch-package and postinstall-postinstall until 4.0.1 is released

**Comment by goodpixels** [comment]
Thank you for a super quick response!
