### ISSUE TITLE
[v4]relation to admin users making app crash

### ISSUE THREAD

**Issue by GautierDele** [strapi/strapi#11878]
### Describe the bug

A relation to authors (admin users) is making detail crash:
![image](https://user-images.githubusercontent.com/12382966/145721201-097e92fa-75e0-4e08-98c9-bb7eb9890fb3.png)

### Steps to reproduce the behavior

Create the relation and access the detail of a resource
Creating isn't giving problem but editing is making it crash

MIGHT BE RELATED TO USERS PERMISSION ?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
