### ISSUE TITLE
Data not populating ( saved data from dynamic zone / component )  in page strapi API 

### ISSUE THREAD

**Issue by geogeorgejoseph** [strapi/strapi#11874]
Created using **npx create-strapi-app@latest my-project** 

Created a SINGLE TYPE and named it is "Home" 

Added one dynamic zone , 
![Content-Type-Builder](https://user-images.githubusercontent.com/25584016/145677359-a93f5295-1e94-4ba1-936e-7cacf8c9b437.png)

After that created page with that SINGLE TYPE ( Home ) and published it

![Content-Manager](https://user-images.githubusercontent.com/25584016/145677416-414f10b8-c36e-4ebe-82c0-66500a806d5f.png)

For public user added permission to access the API, **But dynamic zone / component data not seen in the API**

![-api-home](https://user-images.githubusercontent.com/25584016/145677498-77f8cb14-6bd1-44a7-ada1-da09aa209fce.png)

**Please give me a solution to bring dynamic zone / component data to the API**

**Comment by tomnovotny7** [comment]
For this simple case it is enough to use populate="*" see [here](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population).

For more complicated stuff you can use our solution here: https://github.com/strapi/strapi/issues/11787#issuecomment-989137950 or follow that issue if any update occures.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11787
