### ISSUE TITLE
[v4] The unique option doesn't work when you empty a field

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#11882]
### Describe the bug

The unique option doesn't work when you empty a field.

### Steps to reproduce the behavior

1. Create an `Profile` content type with a `unique` field, like `instagramUsername`:

    ```json
    "attributes": {
      "name": {
        "type": "string",
        "required": true,
        "unique": true
      },
      "instagramUsername": {
        "type": "string",
        "unique": true
      }
    }
    ```

2. Create new Profile entry with just `name`.
    (I see that now `instagramUsername` it's `null`)

3. Edit the entry, and set `instagramUsername` to `abdonrd`.
    (I see that now `instagramUsername` it's `"abdonrd"`)

4. Edit the entry, and empty the `instagramUsername`.
    **(I see that now the value it's an empty string `""` and not `null`)**
    Maybe it should be `null`?

5. Create another Profile entry with `name` and `instagramUsername`.

6. Edit the entry, and empty the `instagramUsername`.
    ⚠️ `ValidationError. This attribute must be unique`

    <img width="784" alt="Screenshot 2021-12-13 at 13 23 45" src="https://user-images.githubusercontent.com/1007051/145811750-a7134986-c4eb-4e3d-9504-864be4c120d5.png">

    I imagine that the conflict is generated to avoid repeating an empty string.

### Expected behavior

I hope I can save the value without problem.

If I deleted/emptied a field (`instagramUsername`), I hope it doesn't generate a unique conflict.

### System

- Node.js version: v16
- NPM version: v8
- Strapi version: v4
- Database: SQLite
- Operating system: macOS

**Comment by chadwithuhc** [comment]
I've run into issues with the Unique checking across all items in the table (whether they are deleted, or exist on another entry). This confused me at first, but I think it hasn't been built to support having a previously entered value, as long as it is not currently in the list. 

I'd suggest only failing a Unique check if it exists on the entry it belongs to and not the whole table in general. Do you think that is possible?

**Comment by derrickmehaffy** [comment]
@abdonrd / @chadwithuhc can you test with v4.0.2

**Comment by abdonrd** [comment]
> @abdonrd / @chadwithuhc can you test with v4.0.2

Yes, same error with `v4.0.2`.

**Comment by abdonrd** [comment]
Same error with `v4.0.3` and `v4.0.4`.
