### ISSUE TITLE
Failed to run v4 with previous database which has UUID as primary key

### ISSUE THREAD

**Issue by oleksandr990** [strapi/strapi#11881]
Hi, there. I used strapi v3 in the past with id as UUID for postgres database.
A few days ago, I managed to update the project to strapi v4.
But I noticed that running it tries to drop column "id", because it is UUID.
If I try to run it with empty database, it creates "id" with type "bigInt".
But I really need to run it with "id" with type "uuid", because I have lots of data in the database.
How can I overcome this issue?
```
alter table "books" alter column "id" drop not null - column "id" is in a primary key
error: alter table "books" alter column "id" drop not null - column "id" is in a primary key
    at Parser.parseErrorMessage (/home/cosmos/WORKS/Don/talkinarabic-strapi/node_modules/pg-protocol/dist/parser.js:287:98)
```

**Comment by i-bsd** [comment]
Exact same problem here. Please advise.

**Comment by derrickmehaffy** [comment]
UUIDs are not currently supported, this is something we will consider in the future but no ETA.

Duplicate: https://github.com/strapi/strapi/issues/1762
