### ISSUE TITLE
Windows 10 - Sharp Module Installation Issue

### ISSUE THREAD

**Issue by dirq** [strapi/strapi#11887]
### Describe the bug

Creating a new Strapi v4 project errors in Windows 10.

```bash
> strapi-v-4-test@0.1.0 build
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

√ Webpack
  Compiled successfully in 25.88s

Running your Strapi application.

> strapi-v-4-test@0.1.0 develop
> strapi develop


Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\D:\Projects\_Tests\strapi\strapi-v4-test\node_modules\sharp\build\Release\sharp-win32-x64.node

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
Done in 182.13s.
```

### Steps to reproduce the behavior

Run `yarn create strapi-app strapi-v4-test --quickstart` 

### Expected behavior

It should build a project and run it.

### System

- Node.js version: v14.18.1
- NPM version: 8.3.0
- Strapi version: latest
- Database: sqllite (from quickstart)
- Operating system: Windows 10

### Additional context

I thought I heard that Sharp was going to be removed.

**Comment by dirq** [comment]
Note.  `npm install --platform=win32 --arch=x64 sharp` did fix it for me.  But it would have been a better experience to have it just work out of the box.  ;)

**Comment by derrickmehaffy** [comment]
Tested on Windows using Node 16 with NPM 8 and SQLite and couldn't reproduce.

Need more information to reliably reproduce the issue, also I suggest not using NPM 8 with Node 14.

**Comment by oscarnevarezleal** [comment]
Hi, this just happened to me as well.

I switched between workstations and this is a new environment, I'm guessing it has something to do with node-gyp &/|| MsBuildTools. I can't make it work.

**Comment by mosin92** [comment]
Hi, I'm, also facing same error. please let me know, what i should need to do. 
<img width="683" alt="StrapiError" src="https://user-images.githubusercontent.com/55811423/158337117-6f106699-cd33-44a3-99c4-d9238c983348.png">

**Comment by derrickmehaffy** [comment]
@mosin92 need more information, most likely though you are missing some dev depends like python or other build tools.

On windows when you install node, it asks you if you want to install the build tools. You do need those.

**Comment by quangcl** [comment]
@derrickmehaffy I also have the same problem as above, i using NPM version: 6.14.4, Node version: 14.0.0. please let me know, what i should need to do.
