### ISSUE TITLE
Cannot change endpoint of Graphql

### ISSUE THREAD

**Issue by apaniuk** [strapi/strapi#11889]
Cannot change endpoint of Graphql in ./config/plugins.js

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
