### ISSUE TITLE
[v4] sort by graphql duplicating rows

### ISSUE THREAD

**Issue by GautierDele** [strapi/strapi#11880]
### Describe the bug

In V3, i could sort by nested relations in graphql by using this:
![image](https://user-images.githubusercontent.com/12382966/145727621-fc79c043-ae32-49fa-959f-95c2588f12da.png)

But for now, it's duplicating rows and creating lines depending on the relation like a join would do in SQL (using mysql driver) ...

### Expected behavior

Not having duplicated rows

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
