### ISSUE TITLE
[v4] relation to admin users making app crash

### ISSUE THREAD

**Issue by GautierDele** [strapi/strapi#11891]
### Describe the bug

When you make a relation to admin users the detail of the resource crashed

### Steps to reproduce the behavior

Create a relation to admin users:
![image](https://user-images.githubusercontent.com/12382966/145874331-0d89304a-a113-46f9-9f19-d9e447cc0d08.png)

Go to the detail of one row of this resource and you'll have a blank page
![image](https://user-images.githubusercontent.com/12382966/145874482-23c1501e-bd53-4cd6-8d8b-2a19a29fb8c8.png)

### Expected behavior

We should be able to access detail and like admin users to the resource.

### System

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: MySQL
- Operating system: Windows 11

**Comment by GautierDele** [comment]
Hello @iicdii,

Thanks for your fix

I just realised it was also bugged when linking with one to one
![image](https://user-images.githubusercontent.com/12382966/147413862-121aef0f-204c-47db-8d75-130b1d7af104.png)
![image](https://user-images.githubusercontent.com/12382966/147413872-8f3c2b9e-572f-4f62-84b3-4d7aa385bf0c.png)

As you can see the selection field is empty

I'm wondering if your fix is fixing this or I should open another issue ?

Thanks

**Comment by iicdii** [comment]
It's different issue so it'd be better to create new one :)

**Comment by iicdii** [comment]
Yeah the bug you found was on the same logic. Thank you for reporting :)
You can select user by clicking X and click select again **as temporary workaround** until the PR is merged.

https://user-images.githubusercontent.com/4951716/147415168-d9c1b651-30fa-452c-903d-2e0d3a4d8904.mov

**Comment by GautierDele** [comment]
Yeah thanks, that's what i'm using :)
