### ISSUE TITLE
[v4] Sentry plugin throws error after error is thrown

### ISSUE THREAD

**Issue by martincapek** [strapi/strapi#11899]
Hi! 👋 
      
After I tried install sentry plugin and init in code after I throw error 

```
[2021-12-14 10:22:22.731] error: sentry.sendError is not a function
TypeError: sentry.sendError is not a function
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@strapi/plugin-sentry/server/middlewares/sentry.js b/node_modules/@strapi/plugin-sentry/server/middlewares/sentry.js
index 7c6c8c5..5fb6a8e 100644
--- a/node_modules/@strapi/plugin-sentry/server/middlewares/sentry.js
+++ b/node_modules/@strapi/plugin-sentry/server/middlewares/sentry.js
@@ -18,7 +18,7 @@ module.exports = ({ strapi }) => {
     try {
       await next();
     } catch (error) {
-      sentry.sendError(error, (scope, sentryInstance) => {
+      sentryService.sendError(error, (scope, sentryInstance) => {
         scope.addEventProcessor(event => {
           // Parse Koa context to add error metadata
           return sentryInstance.Handlers.parseRequest(event, ctx.request, {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by martincapek** [comment]
Hi, I will use template next time, sorry for that. Also this issues is already reported again and also have PR. 

https://github.com/strapi/strapi/pull/12067
