### ISSUE TITLE
Lack of autocompletion in controllers, services etc.

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#11894]
### Describe the bug

I've noticed that the strapi instance that is passed to controllers, services etc has no autocompletion but the global instance does.

### Steps to reproduce the behavior

1. Create a Service, Controller etc.
2. Test global instance autocomplete
3. Test passed instance autocomplete
4. See lack of automcompletion

### Expected behavior

Since there seem not to be any downsides to using the global instance rather than the passed instance I think this should be added to optimize the DX.

**Comment by derrickmehaffy** [comment]
I'll forgive the rest of the issue template as I asked @fabio-nettis to create this issue after a convo on Discord.

(PS @fabio-nettis next time, I know it's a chore, can you completely fill out the template. :pray: ty)

**Comment by derrickmehaffy** [comment]
To clarify, when extending core controllers and services, the default `strapi` param passed into the function doesn't have auto-complete (it simply doesn't work). If you remove that variable and instead just use `strapi` from the global API auto-complete works perfectly.

If a PM or engineer doesn't understand what was said, poke me on Slack and I'll show you.

**Comment by fabio-nettis** [comment]
> I'll forgive the rest of the issue template as I asked @fabio-nettis to create this issue after a convo on Discord.
> 
> (PS @fabio-nettis next time, I know it's a chore, can you completely fill out the template. :pray: ty)
> 

Sorry for that! My mistake.

**Comment by alexandrebodin** [comment]
Hi, You can't get autocompletion without the global. This is normal behavior unless you explictly load the typing into typescript code or via jsdoc. I'm going to close this as we have come a long way with typescript support & such.
