### ISSUE TITLE
On custom installation, mongodb not available as a db option

### ISSUE THREAD

**Issue by tomfox747** [strapi/strapi#11896]
### Describe the bug
When initialising create-strapi-app, and selecting the custom installation option, no option for mongo is displayed.

### Steps to reproduce the behavior

1. Run "npx create-strapi-app@laters strapi-mongo-test"
2. select custom installation
3. no option to select mongo db

### Expected behavior
When running "npx create-strapi-app@latest strapi-mongo-test". I expect to select custom installation and have the option to use mongo.

- Node.js version: 16.13.1
- NPM version: 8.3.0
- Strapi version: 4.0.0
- Database: mongo
- Operating system: windows 10 x64

**Comment by kasonde** [comment]
Hi @tomfox747 currently v4 does not support MongoDB. You can read more on [this issue](https://github.com/strapi/strapi/issues/10186) and the forum post linked to it.
