### ISSUE TITLE
[GraphQL] query multiple where with collection_null filtering returns wrong result

### ISSUE THREAD

**Issue by JiboStore** [strapi/strapi#11895]
### Describe the bug
When we have Collection type with multiple relations and try to retrieve query with multiple conditions and one of the condition being a relation_null, the result is wrong

### Steps to reproduce the behavior

In the strapi admin web-ui do the following:
1. Create 2 Collection types: Cart and Order
2. In the "Content-Types Builder", specify that "Cart has and belongs to one Order"
3. In the "Content-Types Builder", also specify that "Cart has one User" (User is from User-Permissions plugin) or you can create 3 Collection types and link that third collection type as "owner" to Cart
3. Create 1 Order object and multiple Cart objects, all of the Cart objects should have "owner" set to one User
4. Some of the Cart objects need to be linked to the 1 Order object, leave the rest unlinked
5. Go to your graphql endpoint and query the carts with the following query

```
query {
  carts(where: {
    owner:{id: "6173b921ffbd9a12d17a3a1b<put-your-userid-here>"}
    order_null: false,
  }) {
    id
    order {
      id
    }
    owner {
      id
    }
    updatedAt
  }
}
```

### Expected behavior
results should return all the Cart objects with order: null

### Code snippets

If applicable, add code samples to help explain your problem.
<img width="1673" alt="Screenshot 2021-12-14 at 10 26 46 AM" src="https://user-images.githubusercontent.com/1830158/145923264-a4210294-c152-4aab-b172-c5ef753355dd.png">

### System

- Node.js version: v12.20.0
- NPM version: 6.14.8
- Strapi version: 3.6.8
- Database: mongodb
- Operating system: macosx

### Additional context

Whenever there is a collection_null condition, the result returned will be wrong, if you specify order_null: true in the above case, it will return [] carts

**Comment by derrickmehaffy** [comment]
We don't support v3 anymore unless it's critical or a security issue. See: https://github.com/strapi/strapi/issues/11726
