### ISSUE TITLE
[v4] Media image field did not show up in the API response

### ISSUE THREAD

**Issue by Unviray** [strapi/strapi#11897]
## Bug report

Media image field did not show up in the API response even `private field` is not checked

```json
{
  "data": {
    "id": 1,
    "attributes": {
      "title": "My first entry",
      "head": "The description of entry",
      "body": "The body text of the entry",
      "createdAt": "2021-12-13T14:40:01.307Z",
      "updatedAt": "2021-12-13T14:40:01.307Z",
      "publishedAt": "2021-12-13T14:40:01.305Z"
    }
  },
  "meta": {}
}
```

### Steps to reproduce the behavior

1. Create strapi project and collection type with image field
2. Fill some data with image
3. Fetch api endpoint

### Expected behavior

```json
{
  "data": {
    "id": 1,
    "attributes": {
      "title": "My first entry",
      "head": "The description of entry",
      "body": "The body text of the entry",
      "images": {
        "data": [
          {
            "id": 1,
            "attributes": {
              "name": "earth.jpg",
              "url": "uploads/earth.jpg"
            }
          }
        ]
      },
      "createdAt": "2021-12-13T14:40:01.307Z",
      "updatedAt": "2021-12-13T14:40:01.307Z",
      "publishedAt": "2021-12-13T14:40:01.305Z"
    }
  },
  "meta": {}
}
```

### System

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.0.0
- Database: sqlite
- Operating system: Ubuntu 20.04.3 LTS x86_64

**Comment by Unviray** [comment]
I tried with params `?fields=images` but there is 500 error
```json
{
  "data": null,
  "error": {
    "status": 500,
    "name": "InternalServerError",
    "message": "Internal Server Error"
  }
}
```
```
[2021-12-14 10:17:56.053] error: select `t0`.`id`, `t0`.`images` from `actualites` as `t0` where (`t0`.`id` = '2') limit 1 - SQLITE_ERROR: no such column: t0.images
Error: select `t0`.`id`, `t0`.`images` from `actualites` as `t0` where (`t0`.`id` = '2') limit 1 - SQLITE_ERROR: no such column: t0.images
```

**Comment by salihozdemir** [comment]
try with `?populate=images` params.

**Comment by kasonde** [comment]
Hi @Unviray, by default relations are not populated by default. [Here's](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population) a guide on how to populate the relations you desire.

**Comment by GrigoriyMo** [comment]
> Hi @Unviray, by default relations are not populated by default. [Here's](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population) a guide on how to populate the relations you desire.

Thank you!

**Comment by RyzenRanger** [comment]
To populate one-level deep for all relations, use the * wildcard in combination with the populate parameter:
Ex: `http://localhost:1337/api/technologies?populate=%2A`
After added this param in request I get correctly object with images and do not forget change roles for Public user or you should use Admin token
