### ISSUE TITLE
[v4] Unable to Configure CORS Settings

### ISSUE THREAD

**Issue by salihozdemir** [strapi/strapi#11900]
### Describe the bug

I'm getting a CORS error when I send a post request to upload an image. After that, I realize that I need to change the CORS settings, but when I go to `middleware.js` I see that it is different from v3. I couldn't figure out CORS settings and couldn't find any solution. How can I add Headers to my CORS options? Does the Strapi provide that?

### Expected behavior

Ability to pass options to strapi::cors package

```ts
module.exports = [
  "strapi::errors",
  "strapi::security",
  {
    resolve: "strapi::cors",
    config: {
      headers: [
        "Content-Type",
        "Authorization",
        "X-Frame-Options",
        "X-Requested-With",
      ],
    },
  },
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::favicon",
  "strapi::public",
];

```

### System

- Node.js version: v14
- NPM version: 6.14.13
- Strapi version: v4
- Database: postgresql
- Operating system: macos

**Comment by martincapek** [comment]
Hi, file in v4 is `middlewares.js` not `middleware.js`. Try to rename it and it should work.

**Comment by h00x** [comment]
Try using `name` instead of `resolve`.

Like this:
```
{
    name: "strapi::cors",
    config: {
      headers: [
        "Content-Type",
        "Authorization",
        "X-Frame-Options",
        "X-Requested-With",
      ],
    },
  },
```

**Comment by salihozdemir** [comment]
> Hi, file in v4 is `middlewares.js` not `middleware.js`. Try to rename it and it should work.

oops, It's name is `middlewares.js` already, I wrong write it

**Comment by salihozdemir** [comment]
> Try using `name` instead of `resolve`.
> 
> Like this:
> 
> ```
> {
>     name: "strapi::cors",
>     config: {
>       headers: [
>         "Content-Type",
>         "Authorization",
>         "X-Frame-Options",
>         "X-Requested-With",
>       ],
>     },
>   },
> ```

Great, I tried, but I got the error "Could not load middleware" and as a result my application stopped.

**Comment by h00x** [comment]
Can you share the full content of your middlewares.js file? It works when I use it on my Strapi installation so there might be an other error. And is there any other information about the error?

**Comment by salihozdemir** [comment]
My `middlewares.js` file and error like this:

![image](https://user-images.githubusercontent.com/41580619/146145541-098b63b7-1626-4ff8-94a8-199b9167c834.png)

I think `resolve` is waiting for a file path. It doesn't work because I give it the strapi plugin `strapi::cors`. I am wondering how you got it working?

**Comment by h00x** [comment]
And what do you see when you use `name` instead of `resolve`? Please share the code and error again.

**Comment by salihozdemir** [comment]
@h00x thanks, it works actually you said before but i misunderstood.

**Comment by anestesya** [comment]
My configuration file /config/middlewares.js

module.exports = [
  'strapi::errors',
  'strapi::security',
  {
    name: "strapi::cors",
    config: {
      enabled: true,
      origin: [
        'http://localhost:3000','http://localhost:8000', 'http://vg.local', 'http://localhost:1337',
        'http://apivg.tadtarget.com', 'https://apivg.tadtarget.com'
      ],
      maxAge: 31536000,
      credentials: true,
      methods: [
        "GET",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "OPTIONS",
        "HEAD"
      ],
      headers: [
        "Content-Type",
        "Authorization",
        "X-Frame-Options",
        "Origin",
        "Access-Control-Allow-Headers",
        "Access-Control-Allow-Origin"
      ]
    },
  },
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
];
