### ISSUE TITLE
Ability to add custom resolvers

### ISSUE THREAD

**Issue by oriooctopus** [strapi/strapi#11904]
Let's say a have an entity called `Sublesson`, with a field called `description`.

I would like to add a custom resolver on the `sublesson` called `formattedDescription` which basically gets `description` and formats it. This is just one example, but in general the ability to extend the graphql schema with custom resolvers is something I view as an essential feature.

Is this currently possible? If not, I would like to request that it be added. Thank you!

**Comment by oriooctopus** [comment]
I found a way to do this! 

```
module.exports = {
  definition: `
    extend type Sublesson {
      test: String!
    }
  `,
  resolver: {
    Sublesson: {
      test: {
        description: "this is a test",
        resolver: () => "some returned value",
        resolverOf: "application::sublesson.sublesson.find",
      },
    },
    Mutation: {},
  },
  type: {},
};
```

**Comment by oriooctopus** [comment]
Come to think of it, I think it could be useful to update the docs with this info. I looked all around to try and find info on how to do this and couldn't. I eventually had to dive into the node module itself to figure it out, so I assume other people might have trouble as well. I could put up a PR if you agree.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
