### ISSUE TITLE
[v4] Admin UI populates the relation of a relation

### ISSUE THREAD

**Issue by masterdimar** [strapi/strapi#11903]
### Describe the bug

In a many to many relation, the Admin UI is retrieving the relation of a relation, causing long response times

### Steps to reproduce the behavior

1. Create the collection type A with the field text TestA
2. Create the collection type B with the field text TestB
3. Create a many to many relation between A and B
4. Create 2 entries en collection type A
5. Create 2 entries en collection type B
6. Open first entry of collection type A and relate it to first and second entry of collection B
7. Open second entry of collection type A and relate it to first and second entry of collection B
8. Open first entry of collection type A and check the response

### Expected behavior

Only the direct relation should be retrieved

### Screenshots

![image](https://user-images.githubusercontent.com/3002210/145996574-22fbfb6b-bfe9-4a92-b9a4-f9952ca3ae85.png)

### System

- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: v4.0.0
- Database: sqlite
- Operating system: Windows Server 2012

**Comment by derrickmehaffy** [comment]
should be fixed in v4.0.2
