### ISSUE TITLE
[v4] Default public directory can't be overwritten

### ISSUE THREAD

**Issue by h00x** [strapi/strapi#11907]
## Bug report
I'm unable to change the directory of the public path.

### Describe the bug

According to [this](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/middlewares.html#public) documentation you're able to overwrite the default path of the public directory. Changing it in `config/middlewares.js` to:
```
{
  name: 'strapi::public',
  config: {
    path: env('PUBLIC_DIRECTORY', '/data/public'),
  },
},
```

does nothing to the public path.

### Steps to reproduce the behavior

1. Change the public path in `config/middlewares.js` by changing `strapi::public` to an object with a config and a path property
2. Restart the server
3. Upload something
4. Can't find the uploaded file in the `test` directory but you are able to find it in `public/uploads`

### Expected behavior

I expect the public directory and the content that I upload to be set to the `path` value I specify in `config/middlewares.js`.

### Code snippets
Example of the change to `strapi::public` in `config/middlewares.js`.
```
{
  name: 'strapi::public',
  config: {
    path: './test',
  },
},
```

### System

- Node.js version: 14.18.2
- NPM version: 6.14.15
- Strapi version: 4.0
- Database: SQLite
- Operating system: Debian GNU/Linux 10 (buster)

### Additional context

Trying to get Strapi v4 working on Render.com. Changing the public path is the only thing holding me back using Strapi v4 on an ephemeral environment.

**Comment by TasosBak** [comment]
Hey @h00x did you have any luck with this?

**Comment by h00x** [comment]
Nope not yet, thinking about moving the images to something like Cloudinary while waiting for this to get fixed.

**Comment by TasosBak** [comment]
I did this: 

1. Add a middleware.js file in your config folder if you do not have one
2. Your middleware.js file should be like this `module.exports = ({ env }) => ({
    settings: {
      public: {
        defaultIndex: !!process.env.SHOW_ADMIN_PANEL,
        path: '../test'
      },
    }
  })`
3. Rebuild

**Comment by h00x** [comment]
Thanks for your answer @TasosBak. Are you sure this is for Strapi v4? Because this does nothing in v4. I checked the docs for v3 and it seems like the answer you gave is for v3.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/trying-to-get-strapi-v4-to-work-on-render-com/13201/3

**Comment by leoliuasia** [comment]
I looked the source code for this configuration, founded that this path is hard coded. Something like 'strapi.dirs.public'. You can change this to your path, or change the code to get your own config from middlewares.js. Or change "public: join(root, 'public')" to your path from file 'get-dirs.js'. Or wait the developer fix this problem which change hard coded path to get user configed path. For now configuration only maxAge and defaultIndex enabled.

**Comment by balmacefa** [comment]
Please update the doc. There is no reference on how to override the internals middleware...
add {name, config} to the docs

**Comment by derrickmehaffy** [comment]
> Please update the doc. There is no reference on how to override the internals middleware... add {name, config} to the docs

You shouldn't need to overwrite the core middleware for this, it's a bug that we need to fix.

In the meantime you could use patch-package to fix it if you know where the problem is

**Comment by derrickmehaffy** [comment]
Problem code is here:  https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/utils/get-dirs.js#L14
