### ISSUE TITLE
[v4] Media Gallery doesn't display images from S3

### ISSUE THREAD

**Issue by Igal-Kleiner** [strapi/strapi#11906]
### Describe the bug

When using @strapi/provider-upload-aws-s3 to upload images to AWS S3, after configuring everything as per documentation. the images are being uploaded to S3 bucket, but are not being displayed in the Media Gallery.

### Steps to reproduce the behavior

1. Create a brand new Strapi project with npm (I selected custom installation, with postgre as DB).
2. Install the AWS S3 provider `npm i @strapi/provider-upload-aws-s3 -S`
3. Just in case, I ran `npm run build` to rebuild the project
4. Run `npm run develop` to start your project
5. Create your admin account.
6. Configure your S3 provider according to [documentation](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider)
7. Once the server is restarted go to Media Gallery and try to upload an image.

### Expected behavior

Image is uploaded to S3 and displayed in the Media Gallery, just as it worked in latest 3.x.x versions.

### Actual behavior

The images are being uploaded to S3 bucket, an entry is created in the gallery, but the image itself is not displayed (i.e. not loaded).
Upon inspecting Network requests in browsers' dev. tools I see the following errors:

**Firefox**:
> Content Security Policy: The page’s settings blocked the loading of a resource at {my img URL}.

**Chrome**
> Refused to load the image '{my img URL}' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

When loading the image URL in a browser it is being loaded and displayed.

### System

- Node.js version: 14.15.0
- NPM version: 6.14.8
- Strapi version: 4.0.0
- Database: PostgreSQL
- Operating system: Win 10

**Comment by martincapek** [comment]
You have to set cors policy in `middlewares.js`

```JS
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "your-s3-url",
          ],
          "media-src": ["'self'", "data:", "blob:"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::favicon",
  "strapi::public",
];

```

**Comment by martincapek** [comment]
Sorry wrong mention...

**Comment by Igal-Kleiner** [comment]
> You have to set cors policy in `middlewares.js`

I see... I actually tried to do something similar, but instead of `name` I used `resolve` and I wasn't really sure about the rest. I think the documentation isn't very clear about that. Thanks!
I replaced `your-s3-url` with `*.amazonaws.com`. Then everything worked. Thank you!

**Comment by esnakker** [comment]
@martincapek Thank you, this also works for Cloudinary.

**Comment by Igal-Kleiner** [comment]
@esnakker Hmmm, interesting. unlike S3 I wasn't even able to upload an image to Cloudinary. Perhaps should try again with that solution by @martincapek

**Comment by esnakker** [comment]
@Igal-Kleiner Had the same problem. I think since version 4 the configuration in plugin.js has changed a bit:

Version 3:
```
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: 'cloudinary',
    providerOptions: {
```

Now you have to wrap it in a config object:

```
module.exports = ({ env }) => ({
    upload: {
      config: {
        provider: "cloudinary",
        providerOptions: {
```

**Comment by bishoymelek** [comment]
Thanks @martincapek worked for digitalOcean as well

**Comment by Sathyanarayanan-Dhanuskodi** [comment]
I am using Strapi v4. I am using S3 which is secured so there won't be public access. I use a signed URL to access the S3. But the media library cannot be modified to display the preview with signed URL and the media library cannot be modified so that when we copy the link will be signed.

Is there any way to modify the URL in media library.

**Comment by ndrslmpk** [comment]
any updates?
