### ISSUE TITLE
Admin sometimes crash when filling from another locale

### ISSUE THREAD

**Issue by Mcastres** [strapi/strapi#11908]
### Describe the bug

Admin sometimes crashes when filling from another locale.

### Steps to reproduce the behavior

You can reproduce this behaviour using FoodAdvisor
1. `git clone https://github.com/strapi/foodadvisor.git`
2. `git checkout remove-plugins`
3.  `cd api && yarn && yarn seed && yarn develop`
4. Find a restaurant without an fr-FR locale and try to create one using `Fill from another locale`
5. Reproduce to other restaurants if the error didn't happen on the previous one.

### Expected behavior

Data should be filled with en locale.

### Screenshots

![Capture d’écran 2021-12-14 à 17 15 32](https://user-images.githubusercontent.com/17828745/146042842-3bab7666-40ba-4fc2-8b26-e2e6d2bbbc6c.png)

### System

- Node.js version: v12.8.4
- NPM version: 6.14.6
- Strapi version: v4.0.0
- Database: SQLite3
- Operating system: Mac OS

### Additional context

I also figured out the fact that UID fields are not regenerated when filling from another locale. This causes a Bad request when trying to save the content unless you regenerate them

![Capture d’écran 2021-12-14 à 17 56 26](https://user-images.githubusercontent.com/17828745/146043626-a47ea15e-97a0-4aa2-92e4-f7f8b0f8ac11.png)
.

**Comment by derrickmehaffy** [comment]
I'll take a look at this after lunch maxime to see if I can reproduce it

**Comment by tomnovotny7** [comment]
I created a new project a few days back and the same happened to me.
