### ISSUE TITLE
(v4) Cannot save type builder in number 

### ISSUE THREAD

**Issue by abraham-yusuf** [strapi/strapi#11902]
![Screenshot (1076)](https://user-images.githubusercontent.com/76843145/145987842-1e190711-7101-4f6a-81ea-22f0ef2a08fe.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
