### ISSUE TITLE
playgroundAlways:true  doesn't work

### ISSUE THREAD

**Issue by delmendo** [strapi/strapi#11905]
## Bug report

The documentation https://docs.strapi.io/developer-docs/latest/plugins/graphql.html#configurations recommends setting playgroundAlways to true if you want to turn on playground in production.

### Describe the bug

The configuration doesn't turn on playground in production.

### Steps to reproduce the behavior
configure the /config/plugins.js to make playgroundAlways true
start the server
go to http://localhost:1337/graphql 

### Expected behavior

It should turn on playground even in production or the documentation should be updated for 4.0 to warn that it isn't possible to do that.

### System

- Node.js version:v16.10.0
- NPM version: 8.1.2
- Strapi version: 4.0.0
- Database: Postgresql
- Operating system: Linux

### Additional context

The code that controls turning on the playground system doesn't honor the configuration as described in the documentation.

https://github.com/strapi/strapi/blob/3fca25601b556f78e2049883d56176faa3df894b/packages/plugins/graphql/server/bootstrap.js#L59

It explicitly tests for env instead of checking for a config.

**Comment by kasonde** [comment]
@Convly Is this something that has changed in v4? I can confirm that infact the config option has no effect

**Comment by Convly** [comment]
That is indeed something that has been lost during the V4 development. I've made a PR to fix this in #11999
