### ISSUE TITLE
Strapi 4 Not Showing the Nested Relation of A Content Type 

### ISSUE THREAD

**Issue by anildalar** [strapi/strapi#11918]
**Strapi 4 Not Showing the Nested Relation of A Content-Type**

**Comment by niwasmala** [comment]
Do you mean in Rest API? Seems like same with #11913

**Comment by anildalar** [comment]
> Do you mean in Rest API? Seems like same with #11913 #11787

Thanks It Helped me

**Comment by derrickmehaffy** [comment]
Duplicate, closing
