### ISSUE TITLE
Unable to add manyToMany relation due to too long name Err

### ISSUE THREAD

**Issue by fsalem** [strapi/strapi#11916]
**Using mysql DB and strapi v3.6.8**

When creating two collection types with, for example, the following name
1. Social Media Details
2. Social media Logs

Then if you need to add ManyToMany relation in one of those tables, a SQL error will crash the system because the name of the joint table is too long (more than 64 characters)

The joint table format would be:
**TABLE-NAME_COL-NAME_TARGET-TABLE-NAME_COL-NAME**

The table name in our example would be something like:

**social_media_details_social_media_details_social_media_logs_social_media_logs**

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
