### ISSUE TITLE
Send Email After creating a new page

### ISSUE THREAD

**Issue by geogeorgejoseph** [strapi/strapi#11911]
I am beginner in this Strapi technology

**How to  Send a Email After creating a new page. I am using latest version of strapi.**

**Comment by niwasmala** [comment]
Strapi user here. 

My suggestion is to use [webhook](https://docs.strapi.io/developer-docs/latest/development/backend-customization/webhooks.html#user-content-type-webhooks) in strapi to send to your custom apps to send email, or connecting to zapier like in [this blog](https://chriswray.dev/posts/how-to-cross-publish-posts-from-strapi-with-zapier).

Other way if you want to code, you might want to [use lifecycle hooks](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#lifecycle-hooks) after create for specific content types and [send email programmatically like here](https://docs.strapi.io/developer-docs/latest/plugins/email.html#programmatic-usage).

**Comment by geogeorgejoseph** [comment]
I am using latest version of strapi (v4.0.0)

In Email settings ---> fields seems to be disabled

How to enable this

![Settings-Email-settings](https://user-images.githubusercontent.com/25584016/146761388-2204a6e1-6497-4fb8-8fa1-a35f75a90ae5.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
