### ISSUE TITLE
Media (picture url) does not appear in the api response

### ISSUE THREAD

**Issue by alkosa** [strapi/strapi#11913]
Hi,

I have tried to change version from V3 to V4. But I have a problem with the picture URL in the V4 API response JSON. The pic URL does not appear.

The collection type in the V4:

![kép](https://user-images.githubusercontent.com/39232757/146148686-a773dde6-b4ee-4460-9f7b-62dcd359a16b.png)

And the pictures in the strapi's content manager :

![kép](https://user-images.githubusercontent.com/39232757/146148901-50a65f6d-7d66-41e0-ae87-89e249f38abf.png)

I have tried to get ((GET http://localhost:1337/api/tests) the picture url and i have get this: 

![kép](https://user-images.githubusercontent.com/39232757/146149214-4a79dd6a-8ddf-4526-85d0-f5142db51ed7.png)

![kép](https://user-images.githubusercontent.com/39232757/146149299-40739881-89ea-4214-9ffd-32ad21c4c246.png)

I do not see my pic URL... :)

My question is where is the picture URL? In the strapi V3 everything worked well at the first time: 

For example:

![kép](https://user-images.githubusercontent.com/39232757/146151828-e5c26dcf-4c7b-41b4-b032-9fb87589cbb9.png)

![kép](https://user-images.githubusercontent.com/39232757/146151269-119c9ff9-b63b-4476-b8a1-22127df8793f.png)

What is the problem with the V4 media (picture) handling?

Thanks a lot ...
### System
* nodejs: v12.19.0
* npm: 6.14.8
* starpi: 4.0.0
* dtabase: mysql  Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL) (Dockerized)
* OS: Ubuntu 18.04.3 LTS

**Comment by pavel-nikitin** [comment]
Hi ! I have the same problem with v.4.00 . Fields for media files and relations are't in response.

**Comment by niwasmala** [comment]
Strapi user here.
Seems like strapi v4 doesn't automatically populate media files and relations. You can read the documentation [here](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population). You have to try access GET http://localhost:1337/api/tests?populate=* to see all media and relations

**Comment by alkosa** [comment]
It is working! :) 

Thank for your help. 

Have a nice day.
