### ISSUE TITLE
"Unique" index on content-type fields appears there even though it's creation failed on the back (due to duplicates in data) 

### ISSUE THREAD

**Issue by salouri** [strapi/strapi#11910]
### Describe the bug

When you want to add a unique index on a field with dirty data already (duplicates in my case) it doesn't create the index due to the conflict with current data. However, it still shows the attribute "unique": true in the model file.

### Steps to reproduce the behavior

1. Go to Strapi Admin Portal (e.g. http://localhost:1337/admin on local machine)
2. Click on Content-Types Builder, from the left side bar.
3. From "COLLECTION TYPES" menu select any content-type (e.g. User) and then click on a field to edit it (e.g. email) (Strapi must have been started in develop mode)
4. from the popup window, click on ADVANCED SETTINGS, then check "unique field" checkbox (make sure you select a field that doesn't have this one checked on, and the field has already two records with the same data).
5. looking at the strapi console from terminal you can see the index was not created ...and this is the right behavior so far.
6. Go back to the Admin Portal and refresh the page on the content type from earlier (e.g. User) and the unique checkbox is still there!

### Expected behavior

If index is not created for whatever is the reason, the model should not reflect as if it was created successfully.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.18.2
- NPM version: v6.14.15
- Strapi version: 3.6.8
- Database: postgress
- Operating system: Ubuntu 20

**Comment by derrickmehaffy** [comment]
We currently aren't accepting bug reports for v3 unless they are critical or security related, see: https://github.com/strapi/strapi/issues/11726
