### ISSUE TITLE
Cannot query files through query engine

### ISSUE THREAD

**Issue by ari-motors-team** [strapi/strapi#11922]
### Describe the bug

Cannot query files through query engine.
I tried `upload.upload`, `upload.file`, `upload.files`.
Please add this to the docs.

Here is the code:
```js
const bodyImageData = await strapi.db.query("api::upload.file").findOne({
    where: { id: offer.body.previewImage.id },
})
```

Thats the error:
```bash
strapi_1    | Error: Model api::upload.file not found
```

### Steps to reproduce the behavior

1. Query a file by id
2. See error

### Expected behavior

File data should be returned.

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.0
- Database: postgres 14
- Operating system: fedora 15

**Comment by DanieleAurilio** [comment]
Hi @ari-motors-team ,
i can't reproduce this behavior. 
i am trying to retrive some data from _**api::test-image**_
![image](https://user-images.githubusercontent.com/52456860/146200310-ed79bcaa-3f1b-40fe-81a5-b6583ed4d0d2.png)

this is my code:

   
      const uid = "api::test-image.test-image";
      const tryData = await strapi.db.query(uid).findOne({
        where: { id: 1 },
      });

      console.log(tryData);


and this is my output:

![image](https://user-images.githubusercontent.com/52456860/146200534-b32577c1-8b7f-475d-b6cf-744b13437610.png)


Seems to work correctly.

**Comment by ari-motors-team** [comment]
@DanieleAurilio 
I want to retrieve the actual image from the official upload plugin. Its not a collection I created.
![image](https://user-images.githubusercontent.com/95754840/146206728-eec6e2b4-c95a-4631-a5bb-8ba827ea33ef.png)

**Comment by DanieleAurilio** [comment]
Hi @ari-motors-team ,

      const uid="plugin::upload.file";
      console.log(uid);
      const tryData = await strapi.query(uid).findOne({
        where: { id: 1 },
      });
      console.log(tryData);

With this method i can retrive actual image from the official upload plugin.

**Comment by ari-motors-team** [comment]
@DanieleAurilio Ty, that worked. :)
