### ISSUE TITLE
created by  user data

### ISSUE THREAD

**Issue by sherrywilly** [strapi/strapi#11929]
how do i get the created_by data along with webhooks if any one know please share your knowlege 
![Screenshot 2021-12-16 175536](https://user-images.githubusercontent.com/40135571/146371731-177c057f-48cc-4474-9a88-9182c707247b.jpg)

**Comment by kasonde** [comment]
Hi @sherrywilly  thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.

**Comment by royalpinto** [comment]
https://forum.strapi.io/t/user-createdby-and-updatedby-fields-are-missing-in-the-webhook/15119

**Comment by JustMitah** [comment]
I checked the link in the forum but no answer.... any help please I'm facing the same issue as I want the x-strapi-event payload to contain basic user information.
