### ISSUE TITLE
GraphQL unusable after changing its endpoint

### ISSUE THREAD

**Issue by ricafolio** [strapi/strapi#11928]
### Describe the bug

GraphQL unusable after changing its endpoint

### Steps to reproduce the behavior

1. Change the GraphQL endpoint configuration at `./config/plugins.js` using the code snippets below
2. Access the new endpoint on browser: [http://localhost:1337/graphy](http://localhost:1337/graphy)
3. Playground is stuck at _Loading GraphQL Playground_

### Expected behavior

Should be able to use GraphQL normally at new endpoint

### Screenshots

Playground
![Playground](https://i.imgur.com/C5soCS5.png)

Browser console errors
![Browser console errors](https://i.imgur.com/Eg9XSo6.png)

Browser network tab errors
![Browser network tab errors](https://i.imgur.com/FFpzxKc.png)

### Code snippets

My plugin configuration
```
module.exports = {
  graphql: {
    config: {
      endpoint: '/graphy',
      shadowCRUD: true,
      playgroundAlways: true,
      depthLimit: 7,
      amountLimit: 100
    }
  }
}
```

### System

- Node.js version: v14.18.1
- NPM version: v6.14.15
- Strapi version: v4.0.0
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by jackyang1984** [comment]
as cap security block cdn.jsdelivr.net, should change config/middlewares.js

module.exports = [
    "strapi::errors",
    {
        name: "strapi::security",
        config: {
            contentSecurityPolicy: false
        }
    },
    "strapi::cors",
    "strapi::poweredBy",
    "strapi::logger",
    "strapi::query",
    "strapi::body",
    "strapi::favicon",
    "strapi::public",
];

**Comment by derrickmehaffy** [comment]
Not a bug, the default configuration omits `/graphql` from the CSP config, if you change the default URL you also need to configure or disable CSP.
