### ISSUE TITLE
Missing real 404 page, placeholder is displayed instead.

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#11921]
### Describe the bug

When you try access a non existent page inside the admin panel, you are greeted with an empty screen stating: "TODO NOT FOUND". I guess this was maybe forgotten about.

### Steps to reproduce the behavior

1. Go to the admin panel
2. Enter a non existent url like a misspelled plugin name
3. See the placeholder content

### Expected behavior

There should be a clear, easy to understand error message stating the page was not found, maybe even with an action to take you back home or search for a page.

### Screenshots

![Screen Shot 2021-12-15 at 14 02 56](https://user-images.githubusercontent.com/36916632/146191384-17d40205-06ce-4fca-a665-57df6eaa6ef6.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16.9.0
- NPM version: 7.21.1
- Strapi version: 4.0.0
- Database: SQLite
- Operating system: MacOS, Monterey, 12.0.0

### Additional context

N/A

**Comment by kasonde** [comment]
Confirmed: caused by https://github.com/strapi/strapi/blob/04299a1bdfbcc34866954a402ba1fedd35c3c3bd/packages/core/admin/admin/src/pages/NotFoundPage/index.js

**Comment by kasonde** [comment]
It's in the backlog, refer to #111923 so you should get this sorted out soon.

**Comment by derrickmehaffy** [comment]
Fixed, checked on v4.1.5
