### ISSUE TITLE
_or is not working for each other fields (deep filtering)

### ISSUE THREAD

**Issue by tinycoding5** [strapi/strapi#11925]
Here is my model attributes field
###
```
 "attributes": {
    "user": {
      "via": "assets",
      "plugin": "users-permissions",
      "model": "user"
    },
    "pages": {
      "collection": "page",
      "via": "assets",
      "dominant": true
    },
   "folder": {
      "via": "assets",
      "model": "folders"
    },
  }
```

###

my query is following;
###
```
  const query = qs.stringify({
    _or: [
      [{ 'user.id': userId }, { folder_null: true },],
      [{ 'pages.id': pageId }, { folder_null: true },]
    ]
  })
```

###

response is showing as AND 

How can I fix this issue?

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
