### ISSUE TITLE
Update to 3.0.0 version

### ISSUE THREAD

**Issue by Zingrane** [strapi/strapi#11931]
Hello,

We have issues, can you help us?

https://prnt.sc/238aoq2

https://prnt.sc/238xsne

https://prnt.sc/238aoq2

https://prnt.sc/238xsne

https://prnt.sc/239kq29

**Comment by alanxp** [comment]
Cant see your pictures, also terrible app, change your screen sharing app

**Comment by Zingrane** [comment]
Click on links,to see screenshots

**Comment by derrickmehaffy** [comment]
We don't support migration topics here, see our forum.
