### ISSUE TITLE
[Strapi 4] Drag and Drop to order repeatable component doesn't work on Firefox

### ISSUE THREAD

**Issue by DrMint** [strapi/strapi#11930]
# Drag and Drop to order repeatable component doesn't work on Firefox

### Describe the bug

When using the repeatable component field, users are able to drag and drop entries in order to reorder them. This feature works on Chromium-based browsers (at least tested on Microsoft Edge), but doesn't seem to be functional for Firefox users.

### Steps to reproduce the behavior

1. Log into Strapi using Firefox
2. Create a collection and add a repeatable component field
3. Create an entry in the collection
4. Create multiple entries in the repeatable component field
5. Click and drag the entry in the repeatable component field using the icon on the far right of the entry
6. The entry doesn't move, only the "drag" tooltip appears when hovering over this icon.

### Expected behavior

Firefox user should also be able to reorder the entries using drag and drop.

### Screenshots

![image](https://user-images.githubusercontent.com/29893320/146383472-a954a405-bde6-4da9-abc6-b04b477a03d5.png)

### System

- Node.js version: 12.22.5
- NPM version: 7.5.2
- Strapi version: 14.0.0
- Database: SQLite
- Operating system: Debian 11 (Server), Windows 10 (Client)

**Comment by santicros** [comment]
Can confirm it's also not working for me with Firefox 95 on a Macbook Pro :(
