### ISSUE TITLE
Strapi v4 @strapi/provider-email-amazon-ses not working

### ISSUE THREAD

**Issue by f1sle** [strapi/strapi#11932]
Trying to send a test mail from a strapi admin panel to check if a mail server is configured correctly, but got an error:
**error: Couldn't send test email: can not connect to any SMTP server.**

```
"dependencies": {
    "@strapi/plugin-graphql": "4.0.0",
    "@strapi/plugin-i18n": "4.0.0",
    "@strapi/plugin-users-permissions": "4.0.0",
    "@strapi/provider-email-amazon-ses": "^4.0.0",
    "@strapi/strapi": "4.0.0",
    "pg": "8.6.0",
    "strapi-plugin-email": "^3.6.8"
  },
```
  
  tried also with **@strapi/plugin-email: 4.0.0**
  doesn't work either.
  
  
  **config/plugins.js**
  
```
  module.exports = ({ env }) => ({
  // ...
  email: {
    provider: "amazon-ses",
    providerOptions: {
      key: env("AWS_SES_KEY"),
      secret: env("AWS_SES_SECRET"),
      amazon: "https://email-smtp.us-east-2.amazonaws.com",
    },
    settings: {
      defaultFrom: "no-reply@xxxx.com",
      defaultReplyTo: "info@xxxx.com",
    },
  },
  // ...
});
```

**Comment by f1sle** [comment]
I also changed **Shipper email** and **Response email** in email templates, but no success.

**Comment by F-Y-M** [comment]
i have the same problem using nodemailer:

strapi verison : 4.0.0
node version: 14.17.6
npm version: 8.2.0


`module.exports = ({ env }) => ({
    email: {
      provider: 'nodemailer',
      providerOptions: {
        host: process.env.MAILER_SERVER,
        port: process.env.MAILER_PORT,
        auth: {
          user: process.env.MAILER_USER,
          pass: process.env.MAILER_PASSWORD,
        },
        secure: true
        // ... any custom nodemailer options
      },
      settings: {
        defaultFrom: 'myemail@gmail.com',
        defaultReplyTo: 'myemail@gmail.com',
        testAddress: 'myemail@gmail.com',
      },
    },`

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
