### ISSUE TITLE
[v4] Cannot delete an image from the media-library

### ISSUE THREAD

**Issue by emillo** [strapi/strapi#11939]
### Describe the bug

Uploaded Image cannot be deleted from admin panel, request failed with status code 500

### Steps to reproduce the behavior

1. curl https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png -o lenna.png
2. curl -X 'POST'   'http://localhost:1337/api/upload' -F 'files=@lenna.png'
3. go to strapi admin-> media-library
4. select lenna.png
5. click on button "Delete"
6. click on "Confirm" on the popup

### Expected behavior

The uploaded image is deleted from the media-library

### Screenshots

![Schermata da 2021-12-17 12-52-20](https://user-images.githubusercontent.com/45916590/146541026-4004760a-6fd5-436a-a781-cd2d81cd4337.png)

### Code snippets

This is what the log says for the 500 error:

```
TypeError: Cannot read properties of null (reading 'id')
    at findEntityAndCheckPermissions (/srv/app/node_modules/@strapi/plugin-upload/server/controllers/admin-api.js:197:86)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.destroy (/srv/app/node_modules/@strapi/plugin-upload/server/controllers/admin-api.js:68:26)
    at async returnBodyMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/srv/app/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/body.js:24:7
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/srv/app/node_modules/@koa/cors/index.js:95:16)
    at async /srv/app/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/srv/app/node_modules/koa-session/index.js:41:7)
    at async /srv/app/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
If applicable, add code samples to help explain your problem.
```
### System

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version:v4
- Database: postgres
- Operating system: debian

**Comment by saadms27** [comment]
I have the same bug in my project. I can't delete an image, the response code is 500 and the same error message above.

**Comment by hubroski** [comment]
Same error here.

Putting an try/catch around line 197-203 in @strapi/plugin-upload/server/controllers/admin-api.js seems to catch the error. 

The file can now be deleted without problems.

**Comment by brookbdt** [comment]
I've been facing the same issue. I added the fix to @strapi/plugin-upload/server/controllers/admin-api.js, but that fix isn't being deployed to heroku. My issue is that some images are being deleted, while others aren't. Link to the image doesn't exist as it has been deleted. The thumbnail, however; exists in the dashboard with just the title of the image, without the actual image.
