### ISSUE TITLE
Not Showing Media(Images)  With Deep Nested Relation On Content-Type

### ISSUE THREAD

**Issue by rohitmali123** [strapi/strapi#11935]
Not Showing Media  With Deep Nested Relation ****

**Comment by Devisione** [comment]
i also faced this problem, solved with:

`fetchAPI(`/articles/${id}`, {
      'populate[Content][populate]': '*',
      'populate[preview]': '*',
      'populate[articles_type]': '*',
      fields: '*'
    })`

**Comment by Devisione** [comment]
my solution does NOT cover ALL.

If there is a Dynamic Zone and there is a component inside it, this solution does not work and the component will NOT have an image.

I'm also looking for a solution

**Comment by rohitmali123** [comment]
Yes But It Is Not Working And I'm also  facing  this Issues so looking for a solution

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11787
