### ISSUE TITLE
Migration strapi grpahql from v3 to v4 

### ISSUE THREAD

**Issue by tushar-cefalo** [strapi/strapi#11949]
``In V3, I have used "**where** " to find the data in grpahql, but in v4 I have been using the filter to find the data based on the "**template**" fields. It show an error message` "Field \"template\" is not defined by type \"PageFiltersInput\".",`

Would you please instruct me to fix the issue?

![image](https://user-images.githubusercontent.com/77876914/146735579-4f7fb7a9-a9f8-4686-b413-26a14f15738f.png)

**Node.js version**: 14.17
**NPM version:** 6.9.0
**Strapi version:** 4
**Database:** MySql
**Operating system**: Ubuntu 20

**src/api/address/content-types/page/schema.json**

> {
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "singularName": "page",
    "pluralName": "pages",
    "displayName": "Page",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "pageName": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    },
    "bodySection": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "dynamiczone",
      "components": [
        "shared.title",
        "shared.header",
        "shared.sub-header",
        "shared.image",
        "shared.paragraph",
        "shared.paragraphs",
        "shared.quote",
        "shared.gallery",
        "shared.table",
        "contact.contact-us",
        "shared.employees",
        "shared.image-compare",
        "shared.appointment"
      ]
    },
    "parentPage": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::page.page",
      "inversedBy": "childPages"
    },
    "childPages": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::page.page",
      "mappedBy": "parentPage"
    },
    "slug": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "uid",
      "targetField": "pageName"
    },
    "template": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "enumeration",
      "enum": [
        "Default",
        "Left_Side_Bar",
        "Behandlinger",
        "Health_Info_Type",
        "Aktuelt"
      ],
      "default": "Default"
    },
    "bannerImage": {
      "type": "component",
      "repeatable": false,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "shared.banner-image"
    },
    "breadCrumb": {
      "type": "component",
      "repeatable": true,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "component": "shared.bread-crumb"
    },
    "shortDescription": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "richtext"
    }
  }
}

**Comment by iicdii** [comment]
Can you share your `src/api/address/content-types/page/schema.json`?
And please write down the information about your system.

---

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by tushar-cefalo** [comment]
@iicdii Thank you for your response. I have updated the information. Would you please suggests me?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
