### ISSUE TITLE
GraphQL Component mutation on UserPermissionsUser throws 'Cannot convert object to primitive value'

### ISSUE THREAD

**Issue by mruknowme** [strapi/strapi#11946]
### Describe the bug

In GraphQL, mutating a component created on UserPermissionsUser content type throws `Cannot convert object to primitive value`

### Steps to reproduce the behavior

1. Create a component on User (http://localhost:1337/admin/plugins/content-type-builder/content-types/plugin::users-permissions.user)
E.g. in my case component:
- address
-- address
-- lat
-- lng

2. Try mutating the address component
```graphql
mutation RegisterAddAddress {
	updateUsersPermissionsUser(
		id: "5"
		data: { address: { address: "test2 test2 test2", lat: 20, lng: 130 } }
	) {
		data {
			id
			attributes {
				address {
					id
					address
					lat
					lng
				}
				updatedAt
				createdAt
			}
		}
	}
}
```

This throws the following error:
```json
{
	"errors": [
		{
			"message": "Cannot convert object to primitive value",
			"locations": [
				{
					"line": 51,
					"column": 2
				}
			],
			"path": [
				"updateUsersPermissionsUser"
			],
			"extensions": {
				"code": "INTERNAL_SERVER_ERROR",
				"exception": {
					"stacktrace": [
						"TypeError: Cannot convert object to primitive value",
						"    at /path/to/project/retracted/node_modules/@strapi/database/lib/entity-manager.js:25:74",
						"    at Array.map (<anonymous>)",
						"    at toAssocs (/path/to/project/retracted/node_modules/@strapi/database/lib/entity-manager.js:17:6)",
						"    at Object.updateRelations (/path/to/project/retracted/node_modules/@strapi/database/lib/entity-manager.js:665:28)",
						"    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
						"    at async Object.update (/path/to/project/retracted/node_modules/@strapi/database/lib/entity-manager.js:251:7)",
						"    at async Object.update (/path/to/project/retracted/node_modules/@strapi/plugin-users-permissions/server/controllers/user.js:126:18)",
						"    at async resolve (/path/to/project/retracted/node_modules/@strapi/plugin-users-permissions/server/graphql/mutations/crud/user/update-user.js:36:7)"
					]
				}
			}
		}
	],
	"data": null
}
```

### Notes

'Flattening' the structure e.g. adding `address`, `lat` and `lng` fields directly to User instead of under component works. But this is not an ideal 'workaround`. I as need to reuse the component for other content types and components complexity will grow.

This seems to happen only for User content type, works as expected for others.

MySQL table `up_users_components` is empty (but I am guessing it shouldn't be!?). 

### System

- Node.js version: 16.3.0
- NPM version: 8.1.0 (using `yarn` 1.22.17)
- Strapi version: 4.0.0
- Database: MySQL 8.0.26
- Operating system: macOS

**Comment by iicdii** [comment]
It looks the same kind of issue as #11832. I already made PR #11871

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11832
