### ISSUE TITLE
Can't remove i18n plugin

### ISSUE THREAD

**Issue by M1CK431** [strapi/strapi#11942]
### Describe the bug

Removing i18n plugin using `yarn remove @strapi/plugin-i18n` leads to error: "Warning Alert: An error occurred".
In browser dev tools I can see a `404` error while fetching http://localhost:1337/i18n/locales

### Steps to reproduce the behavior

1. `yarn remove @strapi/plugin-i18n`
2. `yarn develop`
3. open http://localhost:1337/admin/
4. See error "Warning Alert: An error occurred"

### Expected behavior

By definition, a plugin can be removed but it seems I can't remove the i18n plugin.

### Screenshots

![image](https://user-images.githubusercontent.com/31622263/146618105-2ec9cf19-3856-4404-950a-4d59fe94b8c8.png)

### Code snippets

N/A

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: v4.0.0
- Database: MariaDB v10.6.5
- Operating system: ArchLinux

**Comment by abdonrd** [comment]
I think you need to rebuild the project to fix it.

**Comment by M1CK431** [comment]
Thanks a lot @abdonrd you point me to the right direction. The correct command to remove i18n plugin is `yarn strapi uninstall i18n` (which effectively rebuild the admin panel). Now it works perfectly! Thanks again, sorry for the noise.
