### ISSUE TITLE
[v4] Required text field doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#11943]
### Describe the bug

Required text field allow an empty string (`""`).

#### Option 1

1. Create a content-type with just a required text field.
2. Click to create a new entry.
3. Write something in the text field and remove it.
4. Save the entry.
5. In the required text field, it send an empty string (`""`) and it works. ⚠️ 

#### Option 2

1. Create a content-type with a required text field and one more field.
2. Click to create a new entry.
3. Write something in the other field.
4. Save the entry.
5. In the required text field, it send a `null` and it works. ⚠️ 

### Expected behavior

Do not allow to record an empty text when the field is required.

### Screenshots

<img width="1014" alt="Screenshot 2021-12-18 at 19 34 38" src="https://user-images.githubusercontent.com/1007051/146652312-7eee007f-e471-41b4-8c64-124ff334bc9a.png">

A saved entry with the required text empty.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4
- Database: SQLite
- Operating system: macOS

**Comment by soupette** [comment]
When creating a draft entry the required validation is not applied similarly to the v3.

If you try to publish your draft the required validation will be applied.

**Comment by abdonrd** [comment]
Hummm And how can we force validation when we create/update an entry?

**Comment by n-sikka** [comment]
@soupette I also have a similar question and the documentation doesn't provide much help relating to this. 
I understand that the validators execute when publishing the page, but what if we want to execute them even in drafts? 

My use case is of a staging environment. We have Strapi as headless cms and Gatsby pulling the data using GraphQL and rendering the page. So all the unpublished pages need to be shown on staging environments and only published ones on production. But, if these required fields aren't validated, our Gatsby app is prone to errors as we expect some fields to always be in the response body. 


How can we execute required validation when creating a draft entry?

**Comment by derrickmehaffy** [comment]
I believe for now this is just simply considered as won't fix as we believe it to be a feature to not enforce full validation in the draft state especially with the upcoming draft and publish v2 features as well as content versioning.

I'll set this to closed but if you would really like to see this feature please create a feature request on https://feedback.strapi.io so others can upvote it.
