### ISSUE TITLE
String data gets converted into number format

### ISSUE THREAD

**Issue by XcrossD** [strapi/strapi#1194]
**Informations**
- **Node.js version**:
9.8.0
- **npm version**:
5.6.0
- **Strapi version**:
alpha.12.1.3
- **Database**:
mongodb
- **Operating system**:
windows 10

**What is the current behavior?**
If a large number is typed in string field, it is converted to a string with scientific notation.
E.g. 1111111111111111111111111 becomes 1.1111111111111111e+24

**Steps to reproduce the problem**
Type large number in string field, save.

**What is the expected behavior?**
It should retain its original format.

**Suggested solutions**
Possibly related to #995.
Even if a integer parsing library is introduced, it shouldn't affect string field. What is stored in string field should always be what you type, no matter whether it is a number, text....etc. Unless data cleaning is needed, for example, preventing XSS attack.

---

- [X] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@xcrossd if you manually update the database does mongo do this automatically?

**Comment by XcrossD** [comment]
@derrickmehaffy Manually changing the field values in mongo is okay. It retains what I inputted.

**Comment by lauriejim** [comment]
Hello @XcrossD It's completely related to the same issue as #995. Let discuss about this point on #995.
