### ISSUE TITLE
[v4] A non-editable field should not show autocomplete options

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#11940]
### Describe the bug

A non-editable field should not show autocomplete options.

### Steps to reproduce the behavior

1. Configue a view with a non-editable field.
2. Click on the field and see the autocomplete options.

### Expected behavior

Non autocomplete options.

### Screenshots

<img width="389" alt="Screenshot 2021-12-17 at 19 15 25" src="https://user-images.githubusercontent.com/1007051/146589895-66c9a6b2-3384-4482-8ef6-a67fa248374f.png">

```
"slug": {
  "type": "string",
  "required": true,
  "unique": true
}
```

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4
- Database: SQLite
- Operating system: macOS

**Comment by soupette** [comment]
I agree, when a field is disabled the autocompletion should be too.

I think this is an issue that concerns the design system and therefore we should open a new issue in the [dedicated repository](https://github.com/strapi/design-system).

I am closing this issue.

**Comment by yanniskadiri** [comment]
This has been fixed :)
Here it is: https://github.com/strapi/design-system/pull/473
