### ISSUE TITLE
[v4]Drop image to upload dialog in edit view not working

### ISSUE THREAD

**Issue by joel611** [strapi/strapi#11947]
### Describe the bug
Drop file to upload dialog is not working at entity edit view and no any console error
But drop to media library is working.

### Expected behavior
File is upload just like media library

### Screenshots
![image](https://user-images.githubusercontent.com/5180124/146714811-3dc50da9-fe9b-4572-bd83-fd7c1a7cd966.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14
- Strapi version: v4
- Database: mariadb

**Comment by derrickmehaffy** [comment]
Works fine on Chrome and Firefox on Linux Mint 20.2.

User didn't provide enough information to reproduce, closing until more information is provided.

**Comment by LouisLec** [comment]
I think I have the same problem. What I found: when an entity has a repeatable component that itself has a media field inside, none of the file drag'n'drop zones are working in the edit page.

Here is a simple repro. I have two entities. The first one, `test_entity` allows me to upload files with DnD in the edit page, but not `test_2_entity`

`test_entity`
```json
{
  "kind": "singleType",
  "collectionName": "test_entities",
  "info": {
    "singularName": "test-entity",
    "pluralName": "test-entities",
    "displayName": "Test Entity"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "image": {
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "type": "media",
      "multiple": false
    }
  }
}
```

`test_2_entity`
```json
{
  "kind": "singleType",
  "collectionName": "test_2_entities",
  "info": {
    "singularName": "test-2-entity",
    "pluralName": "test-2-entities",
    "displayName": "Test 2 entity",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ]
    },
    "test": {
      "displayName": "test-component",
      "type": "component",
      "repeatable": true,
      "component": "test.test-component"
    }
  }
}
```
and the `test-component`:
```json
{
  "collectionName": "components_test_test_components",
  "info": {
    "displayName": "test-component",
    "icon": "archway"
  },
  "options": {},
  "attributes": {
    "componentName": {
      "type": "string"
    },
    "componentImage": {
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "type": "media",
      "multiple": false
    }
  }
}
```

This is my first issue, do I have to open a new ticket ?

Thanks in advance !
