### ISSUE TITLE
I canceled strapi installation while in progress because it will be installed in an irrelevant file. When I tried to install it again, its giving me this error:  $ npx create-strapi-app@latest dj-events-backend 'create-strapi-app' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Tosinkoa** [strapi/strapi#11948]
$ npx create-strapi-app@latest dj-events-backend
'create-strapi-app' is not recognized as an internal or external command,
operable program or batch file.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
