### ISSUE TITLE
Problems with users permissions plugin

### ISSUE THREAD

**Issue by aggieSzulcDornach** [strapi/strapi#11952]
Hi, we've stared using v4 and there seems to be a problem with users permissions plugin.
We've created custom controller which is about to update user object.

In `3.6.8` everything worked just fine but now we're facing a problem with querying an user.

`strapi.plugins['users-permissions'].services.user` works fine but
`strapi.query('user', 'users-permissions')` gives `error: Model user not found`

Also there is a problem with fetching user relations (eg role). Despite `ctx.state.user` returns full user (with relations), in response from eg `/users/me` there is no way to get relations of an user.

Any help will be appreciated!

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: 4.0.0

**Comment by iicdii** [comment]
In v4 you should query users like below
```js
strapi.db.query('plugin::users-permissions.user').findOne({ where: params, populate: true });
```

> Also there is a problem with fetching user relations (eg role). Despite ctx.state.user returns full user (with relations), in response from eg /users/me there is no way to get relations of an user.

You should check out #11787
