### ISSUE TITLE
Cannot get single type in the selected locale

### ISSUE THREAD

**Issue by Dromediansk** [strapi/strapi#11953]
### Describe the bug

When multiple locales are set in Strapi, fetching a single type in the selected locale is not working properly. It always returns a response in the default locale. 
Moreover, it's not clear whether the provided steps in the [i18n setup](https://docs.strapi.io/developer-docs/latest/plugins/i18n.html) are also valid for single types.

### Steps to reproduce the behavior

1. Go to the admin panel and add a new locale (e.g. German) via Settings - Internationalization. Save the changes.
2. Create a simple single type in Content-Type Builder, e.g. for the about section let's call it "About". In Advanced settings, enable the localization by checking the option "Enable localization for this Content-Type".
3. Create a long text field element within "About" single type and name it e.g. "summary". Save the changes.
4. In Content Manager, fill the "summary" field with some text and click on save + publish for both locales.
5. Update the permissions to read the content type. Go to Settings - under section Roles and permissions plugin, click on Roles - Public - About - check the box "find" and save the changes.
6. Re-run the application and try to get the German locale with `http://localhost:1337/api/about?_locale=de` via Postman or Thunder Client.
7. It will get a response in default locale, instead of German (see the 1st screenshot).

### Expected behavior

It should return a response in the selected locale.

### Screenshots

<img width="1184" alt="Screenshot 2021-12-20 at 14 23 16" src="https://user-images.githubusercontent.com/34217538/146774115-3139ba33-499f-4991-beec-86252806adf8.png">

<img width="1212" alt="Screenshot 2021-12-20 at 14 56 17" src="https://user-images.githubusercontent.com/34217538/146778251-5160d305-7f7b-4d59-a4b8-2b08e39a265b.png">

### System

- Node.js version: `v14.18.1`
- NPM version: `v6.14.15`
- Strapi version: `v4.0.0`
- Database: `sqlite3: v5.0.2`
- Operating system: `macOS Monterey v12.1`

### Additional context

I noticed that when trying to get all available locales for that single type with `http://localhost:1337/api/about?_locale=all` it will receive only the content with the default locale (see 2nd screenshot).

Any help would be appreciated!

**Comment by dougsmith1000** [comment]
Seconded. I just noticed this behavior this morning. Locales aren't listed in the meta object in the default locale's response.

**Comment by Convly** [comment]
Hi, could you try with `locale=de` instead of `_locale=de`?

If I remember correctly we made the switch from `_locale` to `locale` in V4 so maybe it's just the documentation not reflecting this change (in which case we will need to open a pr to fix that) :thinking:

@dougsmith1000 the list of available locales for an entry should be available by populating the `localizations` relation of a localized entry.

**Comment by Dromediansk** [comment]
Thx @Convly for the suggestion, I can confirm that with param `locale` it's working!

<img width="1183" alt="Screenshot 2021-12-21 at 09 51 52" src="https://user-images.githubusercontent.com/34217538/146900474-6c51a3d2-6c28-4c51-8a7b-1407a26037a5.png">

**Comment by Convly** [comment]
Glad it worked, closing this 🙂
