### ISSUE TITLE
Ignore test directories in api folders

### ISSUE THREAD

**Issue by t-wilkinson** [strapi/strapi#11959]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi@3.6.8` for the project I'm working on.

I like to have my tests local to its respective api folder if it doesn't require the global strapi instance. However strapi runs all files in the api directory, including tests. This patch makes strapi ignore any test directories in api folders. However if someone relies on test directories being run by strapi then it could cause some major problems.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi/lib/core/load-apis.js b/node_modules/strapi/lib/core/load-apis.js
index 0f7f985..22222a0 100644
--- a/node_modules/strapi/lib/core/load-apis.js
+++ b/node_modules/strapi/lib/core/load-apis.js
@@ -15,7 +15,7 @@ module.exports = async ({ dir }) => {
     );
   }
 
-  const apis = await loadFiles(apiDir, '*/!(config)/**/*.*(js|json)');
+  const apis = await loadFiles(apiDir, '*/!(config)/**/*.*(js|json)', {globArgs: {ignore: ['**/__tests__/**/*.[jt]s?(x)', '**/tests/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[tj]s?(x)']}});
   const apiConfigs = await loadConfig(apiDir, '*/config/**/*.*(js|json)');
 
   return _.merge(apis, apiConfigs);

```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by domantasjurkus** [comment]
Agree that this would be nice, unfortunate that no follow-up issue was opened.
