### ISSUE TITLE
[v4] Services in User-Permissions Plugin cannot be extended

### ISSUE THREAD

**Issue by sebastian-ludwig** [strapi/strapi#11963]
### Describe the bug

I want to extend `ctx.state.user` with some additional data, so I need to overwrite the `fetchAuthenticatedUser`-service. Unfortunately this is not working, because the Plugin-Services are registered as a function, so this does not work in the `strapi-server.js` as it is stated in the docs:

```
plugin.services.user.fetchAuthenticatedUser = (id) => {
   // return new value
};
```

### Expected behavior

My Code from above should overwrite the Plugin-Implementation.

### System

- Node.js version: v14.18.0
- NPM version:6.14.15
- Strapi version: 4.0.0
- Database: postgreSQL
- Operating system: MacOS

### Solution

It works if we could replace the Service-Functions
```
module.exports = ({ strapi }) => ({ ... })
```
by Objects:
```
module.exports = { ... }
```
like the way it is defined in the controller.

**Comment by kevinvugts** [comment]
@derrickmehaffy @sebastian-ludwig what would be a possible temporary fix for this as it looks like this is a strapi core issue?

**Comment by jesusprubio** [comment]
Same here for files:
- extensions/users-permissions/server/services/providers.js
- extensions/plugin-users-permissions/server/bootstrap/index.js

As workaround I'm using `patch-package` changing the lines inside `node_modules/@strapi/...`
- https://www.npmjs.com/package/patch-package

**Comment by jesusprubio** [comment]
Same for files:
- extensions/users-permissions/server/services/providers.js
- extensions/users-permissions/server/bootstrap/index.js

It works properly if we change directly the Strapi files inside the "node_modules" folder. So we are using `patch-package` as workaround for now.
- https://www.npmjs.com/package/patch-package

**Comment by Zygis0321** [comment]
It is still possible to overwrite plugin services with this workaround 
```
const oldUserServices = plugin.services.user;
plugin.services.user = ({strapi}) => {
    return {
      ...oldUserServices({strapi}),
      fetchAuthenticatedUser: (id) => {
        // return new value
      }
    }
  }
```

**Comment by njacob1001** [comment]
@Zygis0321  where did you put that code? 

maybe in `src/extensions/user-permissions/...` ?

**Comment by njacob1001** [comment]
Check this: check: https://github.com/strapi/strapi/issues/11957#issuecomment-1001102421

it works for me

```
module.exports = (plugin) => {
  const sanitizeOutput = (user) => {
    const {
      password,
      resetPasswordToken,
      confirmationToken,
      ...sanitizedUser
    } = user; // be careful, you need to omit other private attributes yourself
    return sanitizedUser;
  };

  plugin.controllers.user.me = async (ctx) => {
    if (!ctx.state.user) {
      return ctx.unauthorized();
    }
    const user = await strapi.entityService.findOne(
      "plugin::users-permissions.user",
      ctx.state.user.id,
      { populate: ["role"] }
    );

    ctx.body = sanitizeOutput(user);
  };

  plugin.controllers.user.find = async (ctx) => {
    const users = await strapi.entityService.findMany(
      "plugin::users-permissions.user",
      { ...ctx.params, populate: ["role"] }
    );

    ctx.body = users.map((user) => sanitizeOutput(user));
  };

  return plugin;
};

```

**Comment by hkmoon** [comment]
Thanks a lot for all the workarounds!
With this PR #11990 with the below codes in ```extensions/users-permissons/strapi-server.js```, it works well.

```js

const utils = require('@strapi/utils');
const { getService } = require("@strapi/plugin-users-permissions/server/utils");

const { sanitize } = utils;

const sanitizeOutput = (user, ctx) => {
  const schema = strapi.getModel('plugin::users-permissions.user');
  const { auth } = ctx.state;

  return sanitize.contentAPI.output(user, schema, { auth });
};

module.exports = (plugin) => {

  plugin.controllers.user.findOne = async (ctx) => {
    const { id } = ctx.params;

    let data = await getService('user').fetch({ id }, ['role']);

    if (data) {
      data = await sanitizeOutput(data, ctx);
    }

    ctx.body = data;
  };

  return plugin;
};

```

**Comment by semics-tech** [comment]
The issue I have with this is that it overrides the default behaviour of the controllers, is there a way you can just extend without overriding?

I've found a hacky way to do this building off @hkmoon's answer which will store the original controllers, override them but call the original before carrying on with the ctx object mutation.

`
module.exports = (plugin) => {

    const controllers = {
        auth: plugin.controllers.auth,
        user: plugin.controllers.user
    }

    plugin.controllers.user.me = async (ctx) => {
        await controllers.auth.me(ctx)
        console.log("🚀 ~ file: strapi-server.js ~ line 12 ~ plugin.controllers.user.me= ~ ctx", ctx)
    }

    plugin.controllers.auth.callback = async (ctx) => {
        await controllers.auth.callback(ctx)
        console.log("🚀 ~ file: strapi-server.js ~ line 16 ~ plugin.controllers.auth.callback= ~ ctx", ctx)

    }

    return plugin;
};
`

**Comment by derrickmehaffy** [comment]
Marking this one as closed as it is now possible in v4 (has been for a while but we are just cleaning up some issues)
