### ISSUE TITLE
I am not able to get any media field in my api response

### ISSUE THREAD

**Issue by sanjay-20896** [strapi/strapi#11965]
The hero module and videoPopUp has media but not able to get in api response

{
    "data": {
        "id": 1,
        "attributes": {
            "name": "flooco",
            "createdAt": "2021-12-21T06:14:54.471Z",
            "updatedAt": "2021-12-21T08:52:18.420Z",
            "publishedAt": "2021-12-21T06:31:35.001Z",
            "heroModule": {
                "id": 1,
                "shortHeading": "EXPLORE OUR PRODUCTS",
                "heading": "# Are you ready\n# to be the\n## **Change?**\n\n\n\n",
                "bigDesc": "CONNECT"
            },
            "videoPopUp": {
                "id": 1,
                "heading": "diqdxqkibgqki"
            }
        }
    },
    "meta": {}
}

**Comment by roelbeerens** [comment]
In V4 media has to be populated. So if you are using a component with media in it, you need to add a nested populated setting as the populate only works for root level populations. 

The request would probably looks something like `URL?populate=videoPopup,videoPopup.media`

**Comment by sanjay-20896** [comment]
Thank you , This worked to a great extent.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/11787
