### ISSUE TITLE
[v4] Email-Plugin ignores Env-Settings

### ISSUE THREAD

**Issue by sebastian-ludwig** [strapi/strapi#11974]
### Describe the bug

Custom E-Mail Settings for "development" are ignored

### Steps to reproduce the behavior

1. Install and configure `@strapi/provider-email-nodemailer`
2. Create a file `config/env/development/plugins.js` with custom email-settings
3. Send a test email from the Admin-Settings in "Development"-Mode
4. Custom Settings are not used

### Expected behavior

E-Mail-Plugin Settings should be overwritten

### System

- Node.js version: v14.18.0
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: PostgreSQL
- Operating system: MacOS

### Solution
`node_modules/@strapi/plugin-email/server/bootstrap.js` needs to be modified, to receive correct Configuration:

```
// Old
const emailConfig = strapi.config.get('plugin.email');
// New 
const emailConfig = strapi.config.get('plugins.email.config');
```

**Comment by iicdii** [comment]
Would you try with Strapi v4.0.1? There was a fix of configuration per env #11802

**Comment by sebastian-ludwig** [comment]
@iicdii Thank you, works now 👍

**Comment by MaximilianRadons** [comment]
I know this is closed, but is this still an issue?

When using `config/env/development/plugins.js` ,
in `node_modules/@strapi/plugin-email/server/bootstrap.js` i also had to change:

```
// Old
const emailConfig = strapi.config.get('plugin.email');
// New 
const emailConfig = strapi.config.get('plugins.email');
```

When i use config/plugins.js i couldn´t get it to work at all, the configuration is ignored.

I am using @strapi/strapi v4.1.3 and also @strapi/provider-email-nodemailer v4.1.3
