### ISSUE TITLE
[v4] E-Mail Confirmation in User-Permissions Plugin does not work for GraphQL

### ISSUE THREAD

**Issue by sebastian-ludwig** [strapi/strapi#11978]
### Describe the bug

The E-Mail Confirmation after Registration does not work with GraphQL-Mutation
```
mutation EmaiConfirmation($confirmation: String!) {
    emailConfirmation(confirmation: $confirmation) {
      jwt
      user {
        id
        email
      }
    }
  }
```

### Steps to reproduce the behavior

1. Register new User (with enabled email confirmation in the settings)
2. Call GraphQL Mutation from above with the valid Confirmation-Code
3. Receive "token.invalid" 

### Expected behavior

Confirmation should be accepted with a valid Code.

### System

- Node.js version: v14.18.0
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: PostgreSQL
- Operating system: MacOS

### Solution

We need to make sure, that the Controller can read the values from the Request-Query, instead they are placed in the Request-Body:
```
// node_modules/@strapi/plugin-users-permissions/server/graphql/mutations/auth/email-confirmation.js

// Old:
koaContext.request.body = toPlainObject(args);
// New:
koaContext.request.query = toPlainObject(args);
```

**Comment by anthonytison** [comment]
Any update on this bug fix ?
