### ISSUE TITLE
Google auth not working

### ISSUE THREAD

**Issue by techwebdev** [strapi/strapi#11971]
When after choosing an account from google in google signup it redirects to the frontend URL. from the frontend when I call the `api/connect/google/redirect?access_token=XXX` then it shows me the 401 error unauthorized error. I attached the URL which I call from the frontend. I attached a screenshot.
After selecting a Gmail account, it's not created the user in dB. that's the reason it returns a 401 

![image](https://user-images.githubusercontent.com/63657518/146685924-b60bf123-6171-425e-8edb-16e17c35df35.png)
 

## System
** Node.js : 14.1.7.1 **
** strapi : 4.0.0 **

**Comment by manjunathkg** [comment]
Thanks for reporting the issue. 

I am getting the same issue when trying google auth with a nextjs + strapi v4 setup. Auth flow goes to goole and when the user grants the permission, it is going to nextjs api path which calls the strapi app back with the correct access_token. The path called is /api/auth/google/callback?access_token={token} on strapi. Strapi  always returns a 401 response. 

Strapi is a brand new strapi V4 installation with only an admin user.  Any idea how to trouble shoot? I couldn't figure out which code is getting executed for the auth flow.  I tried to add strapi.log.info to the Auth.js file under lib, but that doesn't seem to get executed. Lost on this for the past few  hours.  Appreciate if you can share any solution you get.

Do I need to add the user to the database from admin console to make  it work?

Regards

**Comment by techwebdev** [comment]
The problem is they can't create the user after successfully getting access_token from google 
 i also facing same problem and we will need to wait or if urget then need to do a custom jwt token generate and do this

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/11337

**Comment by popeating** [comment]
Same workflow as you all, a login button that link to: 
http://localhost:1337/api/connect/google
the user grant access and is sent back to a nextjs api route:
http://localhost:3000/api/auth/google/callback?id_token=[......]
the api routes try to get:
http://localhost:1337/api/connect/google/callback?access_token=${req.query.access_token}

but fails with 400 error, i also tried to pass id_token but with no luck
it look the google callback (and many things on Strapi in general) are not documented

anyone knows how i can i authenticate with social (besides adding next-auth)? it's quiete vital for us
thank you

**Comment by naive17** [comment]
Me too!
I stumbled upon this problem and there's no clear way to handle this error in strapi 4

**Comment by JeisonPC** [comment]
Hello, no one has yet been able to authenticate?

**Comment by muhsin097** [comment]
http://localhost:1337/api/auth/google/callback

add 'api' in the url

**Comment by XuanTr** [comment]
I just get once success when i call [http://localhost:1337/api/connect/google/callback?access_token=${req.query.access_token}](http://localhost:1337/api/connect/google/callback?access_token=$%7Breq.query.access_token%7D). 
Anyone have a solution for the issue. I just guess the reason come from google site. Maybe need to revoking the old access_token first.

[Google oauth2 and 400 bad request: Bug on Google side?](https://stackoverflow.com/questions/30212728/google-oauth2-and-400-bad-request-bug-on-google-side)
