### ISSUE TITLE
Unable to see localizations list in API response

### ISSUE THREAD

**Issue by dougsmith1000** [strapi/strapi#11976]
### Describe the bug

In v3, each content type entry would include a list of localizations when one was published. 
![image](https://user-images.githubusercontent.com/1891234/146996227-cd537745-9927-4cd7-8975-ab81e9c22aac.png)

However in v4, I'm unable to retrieve that list using the default findOne behavior in the API. 

### Steps to reproduce the behavior

1. In v4, create a content-type
2. Enable localization for it
3. Populate both the default language and the localized version of the content. 
4. Make a request to the api for the specific content type. This is my response, with two localized languages published:
![image](https://user-images.githubusercontent.com/1891234/146997540-0d915edd-6ce7-488c-bd9b-f3b168cfc589.png)

### Expected behavior

I'd like to receive a list of localizations in the response, as it was in v3, that I can use to query localized content.

### System

- Node.js version: 14.15.4
- NPM version: 7.6.0
- Strapi version: 4.0.0
- Database: MySQL
- Operating system: MacOS Monterrey

Thank you for your help!

**Comment by soupette** [comment]
Hello @dougsmith1000 👋 

With the new v4 you can list the localizations by appending `?populate=localizations` to the URL.

You can find the documentation [here](https://docs.strapi.io/developer-docs/latest/plugins/i18n.html#getting-localized-entries-with-the-locale-parameter).

So for your use case it will be `http://localhost:1337/api/posts/3?populate=localizations` 


I am closing this issue, feel free to reopen it

**Comment by Axxoul** [comment]
In Strapi 4 the webhook payload sent to our server has an empty localizations[] array, although we have the entry in 3 different locales. Wondering if this is connected?
