### ISSUE TITLE
[v4] Creating model from local plugin returns error when starting the server

### ISSUE THREAD

**Issue by nazrinnoorzan** [strapi/strapi#11988]
### Describe the bug

Tried to create model from local plugin, but got error when starting the server.

### Steps to reproduce the behavior

1. Follow this tutorial [https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/server.html#content-types](https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/server.html#content-types)
2. Run `npm run strapi build`
3. Run `npm run strapi develop`
4. See error `error: Cannot set property 'plugin' of undefined`

### Expected behavior

Running `npm run strapi develop` should start the server and show the newly created content type.

### Additional context

Based on the example, on file path `./content-types/content-type-a.js` , should add `schema` as the main object key. That will solve the issue.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by zettabyte918** [comment]
same error

**Comment by zettabyte918** [comment]
![image](https://user-images.githubusercontent.com/18426424/147151844-98a7902d-afe0-4663-b9c6-0a3b0e2eb108.png)
same error i tried to fix it the entire day but i can't

**Comment by zettabyte918** [comment]
i just figure out it after debugging strapi codebase for while so ... u need to respect this structure 

_line 62 there is a .schema in the plugin that the main problem for you_
![image](https://user-images.githubusercontent.com/18426424/147159534-3332ae7c-1d24-442a-9099-4a2570729ed4.png)


### 1) This is your model or content-type it should be named ```schema.js``` inside a folder named ```singularName``` of your model (in my case its ```expert```) 
``` path:  ./server/content-types/expert/schema.js ```

```js
module.exports = {
  info: {
    tableName: "up_experts",
    singularName: "expert", // kebab-case mandatory
    pluralName: "experts", // kebab-case mandatory
    displayName: "Les Experts",
    description: "A regular les experts type",
    kind: "collectionType",
  },
  options: {
    draftAndPublish: true,
  },
  pluginOptions: {
    "content-manager": {
      visible: true,
    },
    "content-type-builder": {
      visible: true,
    },
  },
  attributes: {
    name: {
      type: "string",
      min: 1,
      max: 50,
      configurable: true,
    },
  },
};
```
### 2) then create ```index.js``` in the same folder i repeat it should be exported as  ``` schema``` nothing else 

``` path:  ./server/content-types/expert/index.js ```
```js
"use strict";

const schema = require("./schema");

module.exports = {
  schema,
};

```

### 3) now we are inside ```content-types``` folder add a file named ```index.js``` and it should be exported as singularName of your model in my case ```expert```

``` path:  ./server/content-types/index.js ```
```js
const expert = require("./expert");

module.exports = {
  expert,
};
```

### 4) now go back to and remove curly boi in front of your contentTypes object it should be like this

``` path:  ./server/index.js ```
```js
"use strict";

const register = require("./register");
const bootstrap = require("./bootstrap");
const destroy = require("./destroy");
const config = require("./config");
const controllers = require("./controllers");
const contentTypes = require("./content-types");
const routes = require("./routes");
const services = require("./services");

module.exports = () => {
  return {
    register,
    bootstrap,
    destroy,
    config,
    controllers,
    routes,
    services,
    contentTypes,
    policies: {},
    middlewares: {},
  };
};

```

**Comment by nazrinnoorzan** [comment]
Yup. Or one other way to fix it is just to add `schema` object key inside `./server/content-types/expert/schema.js`

```
module.exports = {
  schema: {
    info: {
      tableName: "up_experts",
      singularName: "expert", // kebab-case mandatory
      pluralName: "experts", // kebab-case mandatory
      displayName: "Les Experts",
      description: "A regular les experts type",
      kind: "collectionType",
    },
    options: {
      draftAndPublish: true,
    },
    pluginOptions: {
      "content-manager": {
        visible: true,
      },
      "content-type-builder": {
        visible: true,
      },
    },
    attributes: {
      name: {
        type: "string",
        min: 1,
        max: 50,
        configurable: true,
      },
    },
  },
};
```

They should update the docs here [https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/server.html#content-types](https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/server.html#content-types) or fix the structure on the node_modules level.
