### ISSUE TITLE
Life Cycle hooks for User-permissions not working

### ISSUE THREAD

**Issue by mnnlthmpsn** [strapi/strapi#11984]
### Describe the bug

Lifecycle hooks for users-permissions not running whenever a user is created or deleted

### Steps to reproduce the behavior

1. Create ./extensions/users-permissions/content-types/users/lifecycles.js if it doesn't alread exist
2. Create afterCreate method as specified in documentation 
https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#lifecycle-hooks
4. console.log(event.result) to check if it runs
5. Nothing is logged when user is created

### Expected behavior

User to be logged in my console after created

### System

- Node.js version: 14.17.5
- NPM version: 6.14.14
- Strapi version: 4
- Database: Postgresql
- Operating system: windows 10

**Comment by kasonde** [comment]
@mnnlthmpsn please specify how you're actually trying to create a user. Is it through the admin or through the Content API?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11828

**Comment by avlosev** [comment]
I have a similar question. Do I understand correctly that when processing related collections, database mechanisms are used, and in fact there are no calls to strapi methods for the dependent collection? As a result lifecycle hooks don't work.
