### ISSUE TITLE
GraphQL Enumerations are not generated any more

### ISSUE THREAD

**Issue by sebastian-ludwig** [strapi/strapi#11993]
## Bug report

This Bug arrived with the latest 4.0.1 version:
The graphql-Schema does not handle ENUMs any more but creates just a String. 
This is not good, because when generating TypeScript Interface based on the Schema, type-information is getting lost.

Before:
```
enum ENUM_APPLICATION_STATUS {
  wait
  yes
  no
}

type Application {
  id: ID!
  status: ENUM_APPLICATION_STATUS!
}
```

Now:
```
type Application {
  id: ID!
  status: String!
}
```

### Expected behavior

ENUMs should still be used in the GraphQL-Schema

### System

- Node.js version: v14.18.0
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Database: PostgreSQL
- Operating system: MacOS

### Additional context

I think, this is related to the changes in #11754

**Comment by iicdii** [comment]
I'm working on it.
I also found it generate a string type instead of enum when it builds an input type.
