### ISSUE TITLE
No media information in REST API request

### ISSUE THREAD

**Issue by bmxmiko** [strapi/strapi#12003]
### Describe the bug

No media information in REST API call.

### Steps to reproduce the behavior

Create a any content with image and do a call `/api/arts/1`. There is no media related things.

### Expected behavior

I would like to have all information in response.

### Screenshots

![Zrzut ekranu (2)](https://user-images.githubusercontent.com/22587256/147160647-049b124e-521b-4cd9-b1c0-c4f715b336f9.png)

Request: `http://localhost:1337/api/artykulies/1`

Response:
```
{"data":{"id":1,"attributes":{"title":"gdfgdfg","body":"dfgdfgdfg","additional":null,"createdAt":"2021-12-22T18:53:51.275Z","updatedAt":"2021-12-22T18:53:53.937Z","publishedAt":"2021-12-22T18:53:53.908Z"}},"meta":{}}
```

### System

- Node.js version: v16
- NPM version: 8.1.2
- Strapi version: 4.0.2
- Database: MySQL 8.0
- Operating system: ubuntu 20.04

**Comment by MarcosGin** [comment]
You need to use the populate query, more info here
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#field-selection

**Comment by bmxmiko** [comment]
@MarcosGin Omg, works! Thanks so much!
