### ISSUE TITLE
Data not getting passed to lifecycle hook when custom create controller is created

### ISSUE THREAD

**Issue by umangag07** [strapi/strapi#12008]
### Describe the bug

When defining create controller for some API data is not getting passed to the lifecycle hook like(beforeCreate(), afterCreate()) when logic should be executed at the both place, strange thing is that for another API it is working perfectly fine data object is having the data in the hook even after defining the custom controller for the api.

### Steps to reproduce the behavior

Strangely can't figure out how to reproduce.

### Expected behavior

Lifecycle hook will get the empty object after defining the create controller otherwise data object will have data inside it.

### System

- Node.js version: v12.22.6
- NPM version:6.14.15
- Strapi version: 3.6.6
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by patrikalbertsson** [comment]
@umangag07 how did you solve this?
