### ISSUE TITLE
Injectable components not pulled in by ExtendComponent

### ISSUE THREAD

**Issue by akearney2** [strapi/strapi#1200]
**Informations**
- **Node.js version**: 9.8.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: mongo 3.6.3
- **Operating system**: MacOS 10.12.6

**What is the current behavior?**
Injected components are not fetched by ExtendComponent. 

**Steps to reproduce the problem**
1. create a plugin with an injectedComponent
2. follow the documentation to add an ExtendedComponent to another plugin (I'm adding one to content-manager)
3. component is not pulled in even though `plugin.toJS.injectedComponents() returns an array

**What is the expected behavior?**
Components load when injectedComponents returns an array

**Suggested solutions**
I was able to get around this issue but updating ExtendComponent with the code below. But since I'm just jumping into strapi i figured i'd love an issue in case i'm not doing something right :-) 

```javascript
const injectedComponents = plugin.toJS().injectedComponents();
      if (!isEmpty(injectedComponents)) {
        const injectedComponents = injectedComponents.filter((compo) => 
```
Also happy to PR this if it seems like the right update.

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by soupette** [comment]
Hi @akearney2!

To be honest I developed the "concept" of this feature and I never had the possibility to use yet!

It was thought to enable the search feature in the `content-manager` and maybe a global search in the admin.

If you got it working, can you submit a PR with your modifications so we can benefit from it?

**Comment by soupette** [comment]
I'm closing this issue since this feature is going to be removed. Also, it is still usable by doing the following.


#### Path: `my-plugin/plugins/my-plugin/admin/src/injectedComponents.js`:

```
import MyComponent from './injectedComponent/MyComponent';
export default [
  {
    plugin: '<pluginName>.<component|container>',
    area: 'top.links',
    component: MyComponent,
    key: 'someUniqueKeyNeededForReact', // https://reactjs.org/docs/lists-and-keys.html
    props: {} // Maybe some props that you want to pass to your component
  },
];
```

Then to use it:

#### Path: `my-app/plugins/<plugin>/admin/src/containers/<container>/index.js` 

```
class MyContainer extends React.Component {
  retrieveTopLinks = () => {
    const { plugins } = this.context.toJS ? this.context.plugins.toJS() : this.context.plugins;
    const componentsToInject = Object.keys(plugins).reduce((acc, current) => {
         const currentPlugin = plugins[current];
         // Retrieve all the components to inject in each plugin
         const injectedComponents = get(currentPlugin, 'injectedComponents', []);
         // Filter them according to your current plugin and container
         const compos = injectedComponents.filter(compo => (
            compo.plugin === `${pluginId}.MyContainer` && 
            compo.area === 'top.links'
         ).map(compo => {
            const Component = compo.component;
      
           return <Compo {...this} key={compo.key} />;
        });

        return [...acc, ...compos];
    }, []);

   return componentsToInject;
  }

   render() {
      return (
       <div> 
         {this.retrieveTopLinks()}    
       </div>
     );
   }
}
```
A working example can be found here (for the retrieving part):

https://github.com/strapi/strapi/blob/b0c12a3912c84fbd9d42e4f8ba55bac465a936ba/packages/strapi-plugin-content-manager/admin/src/containers/EditPage/index.js#L488-L519

And the injectedComponent file can be found there
https://github.com/strapi/strapi/blob/b0c12a3912c84fbd9d42e4f8ba55bac465a936ba/packages/strapi-plugin-content-type-builder/admin/src/injectedComponents.js#L1-L16

BTW @virginieky is the one that fixed the bug and made it work, a logic that will be very similar to that one will be implemented in the beta.

**Comment by gustawdaniel** [comment]
Now it is realized by `injectedComponents` property in plugin registration

```
export default strapi => {
  const pluginDescription = pluginPkg.strapi.description || pluginPkg.description;
  const icon = pluginPkg.strapi.icon;
  const name = pluginPkg.strapi.name;
  const plugin = {
    blockerComponent: null,
    blockerComponentProps: {},
    description: pluginDescription,
    icon,
    id: pluginId,
    initializer: Initializer,
    injectedComponents: [
      {
        plugin: 'content-manager.editView',
        area: 'right.links',
        component: Link,
        key: 'content-type-builder.link',
        props: {
          message: {
            id: 'content-manager.containers.Edit.Link.Fields',
          },
          icon: 'fa-cog',
        },
      },
```

**Comment by tzs007** [comment]
Hi @soupette,

Can I ask where can I find the area config? I suppose, it is some config json, but I cant figured out where it is.

I would like to inject a button into the bottom of the LeftMenu container admin from my independent plugin. Unfortunately, I realized that the admin folder of a plugin doesn't update the .cache folder like admin folder itself.

Thank you!
Bests.

**Comment by soupette** [comment]
@tzs007 unfortunately it's not documented yet, there's one area in the content manager, on the right side of the edit view. You can inject a link here:

<img width="305" alt="Screenshot 2020-11-30 at 09 08 50" src="https://user-images.githubusercontent.com/13311463/100583935-b167b800-32eb-11eb-92c3-abdf1fdeb2db.png">

**Comment by tzs007** [comment]
@soupette thank you! can you predict when will be done in full?
