### ISSUE TITLE
populate not working on users

### ISSUE THREAD

**Issue by evilrat** [strapi/strapi#12001]
## Bug report
Populate doesn't work on users
### Describe the bug

/api/users/1?populate=* & /api/auth/local?populate=*
Both of this doesnt populate role or any other relation.....Using current version of strap 4.0.2

### System

- Node.js version: 14.18.2
- NPM version: 8.3.0
- Strapi version: 4.0.2
- Database: Postgresql
- Operating system: Centos 8

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/11957

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11957
