### ISSUE TITLE
AWS S3: Uploaded Files not showing Error: Provisional headers are shown

### ISSUE THREAD

**Issue by snushah** [strapi/strapi#12019]
Just added a Plugin for AWS S3 Media upload.
After uploading any type of pictures, its uploaded on AWS but appeared as broken on strapi placeholder
Chrome Developer Tools shows **"Provisional headers are shown"**
Not sure what to do?

I am using v:4.0.0

**Comment by alande-amorim** [comment]
@snushah it's happening to me as well. How did you solve this?
Using Strapi v4.0.2

**Comment by snushah** [comment]
Hi, I sorted after following changes to my middlewares.js file as below

module.exports = ({ env }) => [

  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'img-src': ["'self'", 'data:', `${env('AWS_BUCKET_NAME')}.s3.amazonaws.com`],
        },
      }
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
];

**Comment by alande-amorim** [comment]
Thanks @snushah

**Comment by mrcnk** [comment]
In my case I also had to add AWS region to bucket address like:
```js
// config/middlewares.js
module.exports = ({ env }) => [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: {
          "img-src": [
            "'self'",
            "data:",
            `${env("AWS_BUCKET")}.s3.${env("AWS_REGION")}.amazonaws.com`,
          ],
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```
