### ISSUE TITLE
run npx to create starter is failed

### ISSUE THREAD

**Issue by israeldahan** [strapi/strapi#12011]
### Describe the bug
I'm try to install strapi starter and it's failed

### Steps to reproduce the behavior

1. run ```npx create-strapi-starter my-blog gatsby-blog```
2. i choose the Quickstart installation type
3. i got this error 
   `
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (/home/israel/.npm/_npx/256/lib/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:19:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getStarterInfo (/home/israel/.npm/_npx/256/lib/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
    at async buildStarter (/home/israel/.npm/_npx/256/lib/node_modules/create-strapi-starter/utils/build-starter.js:133:7)
   `

### Screenshots

![image](https://user-images.githubusercontent.com/263566/147327994-f9c4f856-75c6-43d1-9864-a46cbc429910.png)

### System

- Node.js version: V14.18.1
- NPM version: 6.14.15
- Strapi version: latest
- Database: 
- Operating system: WSL (Windows Subsystem Linux)

**Comment by israeldahan** [comment]
i think whi is happen.
it's becouse the starter doesn't exist in npm. 
this line ``` const { stdout } = await execa.command(`yarn info ${packageName} --json`);```
return stderr.

**Comment by go-fish-wxy** [comment]
Hi, same issue at my end.
Do you have any update for fixing this issue?

**Comment by israeldahan** [comment]
Yes. You need to run it with strapy version 3

**Comment by huy-lv** [comment]
really bad answer, I dont think we should move to strapi v3

**Comment by huy-lv** [comment]
I got it, this template no longer maintain so we cannot use strapi v4 
![image](https://user-images.githubusercontent.com/7688070/177020844-3dffdc29-48c4-4146-98d0-11ab44d662e4.png)
