### ISSUE TITLE
[v4] logout does not work at admin panel

### ISSUE THREAD

**Issue by matsubaraDaisuke** [strapi/strapi#12015]
## Bug report

[v4] logout does not work at admin panel

### Steps to reproduce the behavior

1. npx create-strapi-app@v4.0.2 new-project
2. create user
3. click logout 

### Expected behavior

propery, exit user

### Screenshots

<img width="648" alt="image" src="https://user-images.githubusercontent.com/25544286/147351644-79d890b6-3543-42cd-aee7-d8e17d6bddab.png">

**Comment by nextrapi** [comment]
I was not able to reproduce this issue. It works fine for me? Can you provide a repo?  Is there any error in the console or network tab of inspect element?

Thanks!

**Comment by ippoippo** [comment]
I was able to replicate. It depends on which browser I was using.

**Comment by ippoippo** [comment]
I was able to replicate. It depends on the browser.

Hardware: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
OS: MacOS Monteray 12.1 (Build 21C52)

- Chrome Version 96.0.4664.110 (Official Build) (x86_64) : ✅ No problem with logout
- Safari Version 15.2 (17612.3.6.1.6) : ❌ Unable to logout. No errors shown on Javascript console.

**Comment by smoothdvd** [comment]
@ippoippo Profile is not work also.

Safari: Version 15.2 (17612.3.6.1.6)
OS: MacOS Monteray 12.1 (Build 21C52)
Hardware: MacBook Air M1 (2020)

**Comment by rlvk-vk** [comment]
I can confirm that it is not working with Safari. It includes both the Profile and Logout links.
If I go to /admin/me it get to the correct place, but the link is not working.

And as stated above: Everything is working fine in Chrome and no errors are in the debugger nor the browser console

**Comment by saifmattias** [comment]
Should have a prio this one :/
