### ISSUE TITLE
Impossible to show admin page after local install

### ISSUE THREAD

**Issue by justoverclockl** [strapi/strapi#12010]
Here the screencast of the error

![X74GQMHLC3](https://user-images.githubusercontent.com/79002016/147297900-684425de-2817-4ea6-a75c-d90a3d84e19d.gif)

Console error: 

```Refused to connect to 'http://localhost:1337/admin/project-type' because it violates the following Content Security Policy directive: "connect-src 'self' https:".```

```
Error: Network Error
    at e.exports (main.dfa22c7a.js:2)
    at XMLHttpRequest.y.onerror (main.dfa22c7a.js:2)
(anonimo) @ main.dfa22c7a.js:2

```

Server.js

```
module.exports = ({ env }) => ({
  host: env('HOST', '127.0.0.1'),
  port: env.int('PORT', 8000),
});

```

database js:

```
const path = require('path');

module.exports = ({ env }) => ({
  connection: {
    client: 'sqlite',
    connection: {
      filename: path.join(__dirname, '..', env('DATABASE_FILENAME', '.tmp/data.db')),
    },
    useNullAsDefault: true,
  },
});

```

**Comment by konstantin83** [comment]
+1
The same story on both sqlite and postgresql

**Comment by m7rlin** [comment]
It happens after changing the default port from 1337 to eg. 1338.

**Comment by konstantin83** [comment]
> It happens after changing the default port from 1337 to eg. 1338.

I'm using default port 1337
<img width="331" alt="✅ 2021-12-27 11-26-33" src="https://user-images.githubusercontent.com/13274062/147451862-6468931e-076c-4d11-95f2-b95385c20d00.png">

**Comment by misterproton** [comment]
Brand new install of 4.0.2, same problem.  Default port 1337.  Using a remote server but did not receive this error on 4.0.

Cannot access the panel to setup the first admin.

**Comment by FancyShare** [comment]
Hi everybody, I've found the reason.
After local install:
npx create-strapi-app YourProjectName
You should build Admin UI first:
npm run build
Then you can run develop:
npm run develop
and see admin page:
http://localhost:1337/admin

No matter sqlite or postgres db.
No matter which port number you choose.
No matter 4.0.0, 4.0.1 or even latest 4.0.2 version.

**Comment by konstantin83** [comment]
> Hi everybody, I've found the reason.

God bless you!

**Comment by justoverclockl** [comment]
This definitely works!

**Comment by derrickmehaffy** [comment]
Going to set this as closed but yes since we now ship the admin pre-built on first load it expects port 1337

**Comment by akshykmr** [comment]
Wow, I was searching for solution so long finally it works, thanks

**Comment by blondbong** [comment]
Wow, you saved my day, now it's working. Tabk you!
