### ISSUE TITLE
[v4] Hidden relational fields are still retrieved from DB

### ISSUE THREAD

**Issue by niekh1234** [strapi/strapi#12017]
IIRC in `V3` I used to *"hide"* relational fields with more than a couple hundred or around a thousand entries to prevent performance issues or crashes. This seemed to have done the job well, as I never experienced lag.

Now in `V4`, I create a collection type with a relational field and have added around 700 entries in that field. It does not matter whether I hide the field using "configure the view" or not, it still tries to retrieve the entries. This is bad, because it causes a JavaScript heap error in V8.

**Check this out:**

![Screenshot from 2021-12-24 21-32-26](https://user-images.githubusercontent.com/34717999/147371661-2a2a50dd-5f7d-40ad-95db-4f0b8a3b8f0f.png)

As you can see I have the collection type `"Category"` which has many `"Balkens" (beams)`.

If we check `"configure the view"` we have this, `"Balkens"` is not present:

![Screenshot from 2021-12-24 21-33-35](https://user-images.githubusercontent.com/34717999/147371680-b865499c-f62e-46cf-bf6f-00e1ac8f2b53.png)

Now I head to browse my `Category` collection, here is the first one:

![Screenshot from 2021-12-24 21-36-08](https://user-images.githubusercontent.com/34717999/147371886-38f74128-15e9-435a-a803-ccd2a5adb9b7.png)

If I were to click on this it shows a white screen and strapi crashes.
If I were to click on an entry with ~50 "balkens" strapi does not crash.

After a while I get:
![Screenshot from 2021-12-24 21-38-24](https://user-images.githubusercontent.com/34717999/147371728-cd921945-8790-438d-9e72-ea24d4168d10.png)

### Expected behavior

It should not retrieve hidden data from the DB. Let alone retrieve everything at once.
From what I remember, having had issues with performance on a large amount of data in v3, the solution was to simply hide the field. But that does not seem to do the job.

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.2
- Database: postgres
- Operating system: Ubuntu 20.04

**Comment by appanchor** [comment]
Hello. I can't speak to the issue of data retrieval for hidden fields, but as for latency in Content Manager with a large number of relationship records, please refer to [this issue comment](https://github.com/strapi/strapi/issues/12004#issuecomment-1015568985).

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/12004
