### ISSUE TITLE
Provider-based Login Bad Request error with SQLITE_CONSTRAINT

### ISSUE THREAD

**Issue by lack-of-gravitas** [strapi/strapi#12022]
### Describe the bug

Provider based login does not work and responds with a Bad Request SQLITE_CONSTRAINT error when testing sign up / sign in API.

### Steps to reproduce the behavior

1. Setup Oauth Credentials in Google Cloud
2. Activate Google provider in Strapi CMS and supply details
3. Visit API (straight localhost or <ngrok routed address>/connect/google) -- YES I HAVE UPDATED SERVER.JS WITH URL CONFIG

### Expected behavior

A JSON response with a  confirmation that user was created.

### Screenshots
![image](https://user-images.githubusercontent.com/10094964/147403347-fe0c8809-13d6-494a-b70f-2d506c8c913a.png)

![image](https://user-images.githubusercontent.com/10094964/147403284-ef39bba3-2b10-4b9e-b344-42dd3451b339.png)

![image](https://user-images.githubusercontent.com/10094964/147403368-cf84cf5a-6f56-44f3-a784-0e682fcf1209.png)

### Context
- have read and attempted fixes described here without success: https://github.com/strapi/strapi/issues/3757
- have read the developer documentation which is incomplete garbage and makes no reference to having to modify the config of an out of the box plugin

**Comment by derrickmehaffy** [comment]
We no longer support v3 unless it's a critical security issue and this issue for now can't be reproduced in v4 as providers are broken via: https://github.com/strapi/strapi/issues/11337

For now I'll mark this as closed and once providers are fixed we can revisit the issue.
