### ISSUE TITLE
Make type of id configurable

### ISSUE THREAD

**Issue by kuongknight** [strapi/strapi#1202]
**What is the expected behavior?**
I used uuid for id from strapi v2 (postgresql) and I try to update to strapi v3
I can't start application because strapi automatic cast related field to integer
I think we should add configurable for id type

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by dj-hedgehog** [comment]
Cuong and I are working together using Postgres type UUID for all IDs.

We added the `uuid-ossp` extension to our Postgres DB Docker image via `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`

**Comment by Aurelsicoko** [comment]
@dj-hedgehog @kuongknight You should try to look at http://bookshelfjs.org/#Model-instance-idAttribute and make a PR to update the `strapi-bookshelf` package to support this case.

**Comment by derrickmehaffy** [comment]
Just as a foot note from my closed issue linked, this should be configurable on each model separately not globally. And example of performance on MySQL using an `Integer` ID vs a `UUID` ID field:

http://kccoder.com/mysql/uuid-vs-int-insert-performance/

**Comment by kuongknight** [comment]
I mean about migrate (create, update table code), current strapi always fixed type for idAtrributes
`switch (relation.nature) {
   case 'oneToOne':
   case 'manyToOne':
   case 'oneWay':
    type = definition.client === 'pg' ? 'integer' : 'int';
    break;
   default:
      return null;
  }`

**Comment by derrickmehaffy** [comment]
@kuongknight I had opened another issue related to your use of the uuid field.

But yes you are right that Strapi hard codes the types. (Like decimal accuracy)
