### ISSUE TITLE
Add Support MongoDB

### ISSUE THREAD

**Issue by xAgustin93** [strapi/strapi#12029]
Is there a date when MongoDB will be supported as in Strapi version 3?

**Comment by GautierDele** [comment]
Please have a look at #10186 
This won't happen but you can produce your own plugin.

**Comment by derrickmehaffy** [comment]
Exactly as @GautierDele stated, we (Strapi) won't ever add it back. The MongoDB team specifically ws supposed to work on it but AFAIK they haven't.
