### ISSUE TITLE
[v4] Modified ID type changes back at the start of the project

### ISSUE THREAD

**Issue by bulby97** [strapi/strapi#12028]
### Describe the bug

In strapi v3, for technical reasons (meaningful ids), I changed the id type of my tables to bigint using the bootstrap files and some alter table commands.
In strapi v4, after any strapi modification (content-type, controller, service...), it seems like it tries to force the integer back for the relations table, because I have this message when I restart my project:

```
alter table "public"."fragment_version_id_links" alter column "fragment_id" type integer using ("fragment_id"::integer) - integer out of range
error: alter table "public"."fragment_version_id_links" alter column "fragment_id" type integer using ("fragment_id"::integer) - integer out of range
```

### Steps to reproduce the behavior

Create a content-type with relations
Change the content-type id type to bigint
Restart the server
Edit some content-type
See error

### Expected behavior

The type of id fields must not change.

**Comment by smoothdvd** [comment]
Similar issue here, Strapi V4 always create/alter relations with column type integer, ignore the foreign key's original type.

I have a metric content-type with id type is varchar(32)
```
...
"attributes": {
    "id": {
      "type": "string",
      "required": true,
      "unique": true,
      "columnType": {
        "type": "specificType",
        "notNullable": true,
        "args":[
          "varchar(32)",
          {"primary": true}
        ]
      }
    },
    ...
}
...
```

and in activity-rating content-type, I try to add metric relation like:
```
"metric": {
  "type": "relation",
  "relation": "oneToOne",
  "useJoinTable": false,
  "target": "api::metric.metric"
}
```

But Strapi always  try to create metric_id with type integer. I think correct way is create metric_id with original type ( id (varchar(32)), in rating table).

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1762
