### ISSUE TITLE
Strapi throws ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by nilsmich** [strapi/strapi#12035]
Hi

### Describe the bug

Strapi throws an error when executing 
```
strapi develop
```
> "error: alter table collection_name add unique collection_name_test_unique(test) - ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes". 

This prohibits running Strapi. 

### Steps to reproduce the behavior

1. Fresh installation of Strapi using the manual installation template
2. In Content-Type Builder add a field of type UID
3. Execute  
 ```
strapi develop
```
4. Program crashes with the above error

### System

- Node.js version: 14.17.0
- NPM version:7.19.0
- Strapi version: 4.0.2
- Database: msql/mariaDB
- Operating system: windows

### Additional Information

The issue seems to appear whenever I try to add a field of the type uid in the Content-Type Builder. It does not appear when using string types only.

Thank you for looking into this.

**Comment by derrickmehaffy** [comment]
Please provide a sample application for testing.

**Comment by nilsmich** [comment]
As mentioned above. It is a fresh installation. I can not push it to production as it crashes when starting the server. 

I have a workaround for myself. I just thought it would be interesting for other users as it seems to be a problem not just for me.

**Comment by derrickmehaffy** [comment]
you didn't give the same of the field, which is what I was asking for.

**Comment by nilsmich** [comment]
This was the solution: https://github.com/strapi/strapi/issues/10248#issuecomment-1079031960

**Comment by superlogicdev** [comment]
"error: alter table collection_name add unique collection_name_test_unique(test) - ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes".
The solution to this problem is given below:

SET GLOBAL default_storage_engine = 'InnoDB';

**Comment by Ahmadnurahsan** [comment]
@superlogicdev  it still show ER_TOO_LONG_KEY while build/develop

{
  "name": "strapi-kupingplug",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "deploy": "strapi deploy"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "4.25.1",
    "@strapi/plugin-users-permissions": "4.25.1",
    "@strapi/plugin-i18n": "4.25.1",
    "@strapi/plugin-cloud": "4.25.1",
    "mysql": "2.18.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "ec907084-92c2-440e-a881-38c3fe11814d"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}


![image](https://github.com/strapi/strapi/assets/72061385/111efbc2-dfdf-4df3-bbbc-ec83d75ca11c)
![image](https://github.com/strapi/strapi/assets/72061385/9046e07a-ac0a-44dc-8f0c-12dad6ba7993)
