### ISSUE TITLE
[Admin]: Using "&" in search query causes ""Your filters contain a field 'xxx' that doesn't appear on your model definition nor its relations"

### ISSUE THREAD

**Issue by brooth** [strapi/strapi#12031]
### Describe the bug

Using "&" (other special symbols?) in the built-in search component leads to 400 error with "Your filters contain a field 'xxx' that doesn't appear on your model definition nor its relations" message

### Steps to reproduce the behavior

1. Go to 'Admin'
2. Pick a collection
3. Enter a search query with '&' somewhere in the middle

### Expected behavior

The search component must encode the query

### Screenshots

<img width="987" alt="Screenshot 2021-12-27 at 18 33 32" src="https://user-images.githubusercontent.com/9823254/147486640-da17a67e-5d1d-41ec-bfa2-713c35b74ccb.png">

<img width="1140" alt="Screenshot 2021-12-27 at 18 34 04" src="https://user-images.githubusercontent.com/9823254/147486648-ffe0d288-9e81-4881-a14e-d534f3499b38.png">

### System

- Node.js version: v12
- NPM version: v6.14.13
- Strapi version: v3.6.8
- Database: MongoDB
- Operating system: Docker Alpine

**Comment by derrickmehaffy** [comment]
We aren't fixing v3 bugs unless they are critical or security related: https://github.com/strapi/strapi/issues/11726
