### ISSUE TITLE
Strapi wont load on intialization error: bind EACCES 0.0.0.0:1337

### ISSUE THREAD

**Issue by vanshreddy** [strapi/strapi#12032]
### Describe the bug

I installed Strapi and it ran the command yarn develop which led to the error: bind EACCES 0.0.0.0:1337 . I googled around and changed the `config/server.js' to 'module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 8082),
  }); '. 

Now Strapi goes to the web browser but says "Warning: An error occured while requesting the API"

**Comment by derrickmehaffy** [comment]
This isn't a Strapi issue, either you have something else running on port 1337 or you don't have permission to bind to ports.

I'd recommend you post on our forum as this isn't a bug in the code.

**Comment by shmox75** [comment]
Same issue here on Windows 11, my port seems free, I tried to run as admin without success.

**Comment by gonwms** [comment]
@shmox75 
It worked! Thanks.
*important to run the terminal as administrator.

**Comment by huaruoji** [comment]
> Same issue here on Windows 11, my port seems free, I tried to run as admin without success. PS: found the solution on windows in the forum with these commands: net stop winnat net start winnat

That's helpful!
