### ISSUE TITLE
Boolean values in API response are not true/false

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1203]
**Informations**
- **Node.js version**: 10.1.0
- **npm version**: 6.0.1
- **Strapi version**: Monorepo 76bb31970f63a86e6976b5406b35d3239d8877b6 (Current Master as of 2018/5/15)
- **Database**: MariaDB v10.2.14
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

When using MySQL, and storing a boolean value, the `tinyint` column type is used thus storing false as `0` and true as `1`. However the api response (get, post, and put) use these values. These `tinyint` values should be used as `true` and `false`.

**Steps to reproduce the problem**

using MySQL, create a boolean field and store some data for testing, Use get, post, and put to try and manipulate the data. Get will return the `0` and `1` values, post/put will not accept `true` or `false` and require the use of the numerical values.

**What is the expected behavior?**

Strapi should translate the boolean `tinyint` to correctly display and accept `false` as `0` and `true` as `1`

**Suggested solutions**

Unsure how bookshelf is handling these values, likely needs a more indepth look and some type of alias to convert back and forth.

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
Can confirm issue exists on Strapi Alpha.12.2

**Comment by lauriejim** [comment]
Hello @derrickmehaffy , thank you for reporting this issue. We are currently on another feature and bug fix. Feel free investigate and to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
I don't have the slightest idea here, It has to do with bookshelf as mongoDB based will properly return the values `true` and `false`
