### ISSUE TITLE
[v4.0.2] Swagger documentation override settings.json not applying

### ISSUE THREAD

**Issue by umair-me** [strapi/strapi#12046]
## Bug report
Created a new project and according to docs https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings added a settings.json file at `src\extensions\documentation\config\settings.json`

### Describe the bug
When running strapi the changes do not show up on swagger documentation

### Code snippets
Used the default json from the above strapi documentation page

**Comment by cbleek** [comment]
same problem here. Does not work in 4.0.0 either.

I've also added the configuration as described in https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/plugins.html to config/plugins.js. Without success:-(

**Comment by cbleek** [comment]
We will update the documentation if someone gives us a tip on how to overwrite the e.g. documantation.info.

**Comment by kayac-chang** [comment]
Hello, I implemented this with this [PR](https://github.com/strapi/strapi/pull/12070)

**Comment by cbleek** [comment]
for me, this works.

**Comment by emilieringwald** [comment]
Thanks for your ticket @umair-me, our team will have a look at this in the coming weeks!
