### ISSUE TITLE
Admin Panel Customization Needed 

### ISSUE THREAD

**Issue by 3akram** [strapi/strapi#12045]
### Please describe your feature request

- [ ] **I want to change the index page on the admin panel localhost:1337/admin/**
- [ ] **I want to change the background color on the Login Page -not the Auth Card - but the surrounding white container**

### Summary

I want to override the admin panel index page /admin/ the one that includes the documentation links to meet the business UI. Also, i need to customize the background color for the LoginPage - not the auth card - but all the surrounding area the default color is F6F6F6 and i want to change it to my primary color/ add some assets and all that stuff. But unfortunately can’t override it.

### Why is it needed?

To be able to add a dark theme to the strapi admin and override the index page will allow me to meet the business UI.

### Screenshots

![Screen Shot 2021-12-29 at 5 04 40 PM](https://user-images.githubusercontent.com/43928342/147675890-e3805eb2-178a-4fac-8f27-65b6caf25e9a.png)

![Screen Shot 2021-12-29 at 5 03 59 PM](https://user-images.githubusercontent.com/43928342/147675875-c8db5cf2-a31f-458c-848d-06b36a08cb91.png)

**Comment by soupette** [comment]
Hello @3akram !

Regarding your issue : 

> I want to override the admin panel index page /admin/ the one that includes the documentation links to meet the business UI.

To do so with the v4 you'll need to fork the @strapi/admin package make your modifications and use your fork in your app instead.

> Also, i need to customize the background color for the LoginPage - not the auth card - but all the surrounding area the default color is F6F6F6

We have made a PR that fixes this issue. However if you need further customisation you should make them in your forked package instead.

**Comment by 3akram** [comment]
Thank you @soupette for your help. I'd recommend to mention in the documentation the use case and the steps to fork and customize the Admin v4 there is many members who i guess doesn't know that too. Thanks again for your help and all your efforts.

**Comment by soupette** [comment]
> I'd recommend to mention in the documentation the use case and the steps to fork and customize the Admin v4 there is many members who i guess doesn't know that too. 

cc/ @pwizla @derrickmehaffy

**Comment by derrickmehaffy** [comment]
Probably better to use patch-package I think, wdyt @soupette or is a full fork really needed?

**Comment by ddegooijer** [comment]
> Thank you @soupette for your help. I'd recommend to mention in the documentation the use case and the steps to fork and customize the Admin v4 there is many members who i guess doesn't know that too. Thanks again for your help and all your efforts.

Any news on this? Could use some help.

**Comment by GuillaumeBordeau** [comment]
Any news ? I am also having issue with customization, I just need to change some simple style rules like resize on textarea, but can't find a way to do it.

**Comment by 3akram** [comment]
@GuillaumeBordeau @ddegooijer 

Like @derrickmehaffy suggested 
I used `patch-package` to customize the `@strapi/admin` instead of forking the repo. All you need to do is to install `patch-package` and customize the `@strapi/admin` in your `node_modules` then patch the modification you did. Note that the `patch-package` is a vital band-aid. you will need to be aware of any updates that might reflects your changes you did in the package in case of changing the package version otherwise it will work just fine.

https://www.npmjs.com/package/patch-package

**Comment by blackinitial** [comment]
@iafilin thanks a lot, its work perfectly

**Comment by Sakura-pgh** [comment]
> 

@iafilin Thanks for the solution, is this under v4?
