### ISSUE TITLE
[v4] Not able to register user with repeatable component

### ISSUE THREAD

**Issue by JohannesOster** [strapi/strapi#12052]
The users-permissions plugin uses the Query Engine to create a new user in the auth controller.
https://github.com/strapi/strapi/blob/eb7aaf9c7d36279e9b025f65a184f0c5ced73b51/packages/plugins/users-permissions/server/controllers/auth.js#L344

Therefore repeatable components are not handled.
Example code:
```
const resp = axios
      .post(`/auth/local/register`, {
        ...credentials,
        numbers: [{number: '+34 12345678', type: 'home', number: '+65 1234566', type: 'work'}]
      })
```
The request would return 200. The user is registered, however, "numbers" is still empty.

Replacing the line (under node_modules) with the entity service:

```
const user = await strapi.entityService.create('plugin::users-permissions.user', { data: params });
```
... resolved this issue for me.

Is the use of the query engine intended?
If so is there another workaround to make repeatable components work?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
