### ISSUE TITLE
Sentry plugin not working with strapi 4

### ISSUE THREAD

**Issue by derweili** [strapi/strapi#12064]
### Describe the bug
I try to use Sentry.io with Strapi 4. I found this blog post https://strapi.io/blog/introducing-sentry-plugin
When trying to install the plugin with `yarn add strapi-plugin-sentry` I received an error that my node 16 environment is incompable to the plugin.

So I searched for a newer version of the plugin and found out there is a separate npm package called `@strapi/plugin-sentry` which references to a newer version of the same plugin (version 4.0.2 currently) while the `strapi-plugin-sentry` package is still at version 3.6.8.

Both packages reference to different versions of this plugin https://github.com/strapi/strapi/tree/master/packages/plugins/sentry

So I installed the newer plugin with `yarn add @strapi/plugin-sentry`

I then followed [the documentation](https://github.com/strapi/strapi/tree/master/packages/plugins/sentry) and added a `config/plugins.js` file with following content:

```
module.exports = ({ env }) => ({
  sentry: {
    dsn: env('SENTRY_DSN'),
    sendMetadata: true,
  },
});
```

And added this to my `.env` file
```
SENTRY_DSN=https://XXXXXXXXXXXXX@oXXXXXX.ingest.sentry.io/XXXXXXX
```

When running `yarn start` or `yarn run build` I get following message in my console:
`@strapi/plugin-sentry is disabled because no Sentry DSN was provided`

So the plugins looks like its not running.

To make sure my env file is not setup wrong, I added the url directly to the `plugins.js` instead of using `env()`

But I get the same error.

Is there something else to do? Is the documentation up to date or does version 4 of the sentry plugin require different settings?

I found out, the plugin tries to load the plugin config in this file: https://github.com/strapi/strapi/blob/6b2e0dc72db42f8aceb98da87865d9300c298375/packages/plugins/sentry/server/services/sentry/index.js#L22

So I tried debuging and found out the plugin does not receive the data from the `config/plugins.js`. Instead it loads its default settings: `{ dsn: null, sendMetadata: true, init: {} }`

### Steps to reproduce the behavior

1. Use Strapi 4
2. Install the sentry plugin using `yarn add @strapi/plugin-sentry`
3. Create the `config/plugins.js` as described above or in [the documentation](https://github.com/strapi/strapi/tree/master/packages/plugins/sentry)
4. Start strapi
5. See the message in the console

### Expected behavior

I whould expect the sentry plugin to load my dsn config and initialize sentry

### Code snippets

`config/plugins.js`:

```
module.exports = ({ env }) => ({
  sentry: {
    dsn: env('SENTRY_DSN'),
    sendMetadata: true,
  },
});
```

### System

- Node.js version: v16.13.1
- Yarn version: 1.22.17
- Strapi version: 4.0.0
- Database: sqlite
- Operating system: MacOS

**Comment by derweili** [comment]
I found out the sentry plugin documentation is out of date. The `config/plugins.js` looks different in strapi 4.
So I added this config:

```
module.exports = {
  // ...
  sentry: {
    enabled: true,
    config: {
      dsn: 'https://XXXXXXXXXXXXX@oXXXXXX.ingest.sentry.io/XXXXXXX',
      sendMetadata: true,
    }
  },
}
```

Now the config is loaded properly. So far so good.

But when I now try to enforce an error to make sure the sentry integration works properly I get an error.

I added `throw new Error('Manual test Error');`  to an api service to test if the sentry intragration works.
When this code runs, I get this error in the console:

```
[2022-01-01 15:45:54.468] error: sentry.sendError is not a function
TypeError: sentry.sendError is not a function
    at /Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@strapi/plugin-sentry/server/middlewares/sentry.js:22:14
    at async /Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@strapi/strapi/lib/middlewares/body.js:24:7
    at async /Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@koa/cors/index.js:56:32)
    at async /Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async /Users/derweili/Code/my-strapi-project/my-strapi-project-server/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
```

This references to this file: 
https://github.com/strapi/strapi/blob/6b2e0dc72db42f8aceb98da87865d9300c298375/packages/plugins/sentry/server/middlewares/sentry.js#L21-L38

The `sentry.sendError` function is not found


I suspect it tries to call this function: 
https://github.com/strapi/strapi/blob/6b2e0dc72db42f8aceb98da87865d9300c298375/packages/plugins/sentry/server/services/sentry/index.js#L65

**Comment by derweili** [comment]
I think I found the reason for the `error: sentry.sendError is not a function`.

The plugin tries to call the `sendError` function on the wrong object:
https://github.com/strapi/strapi/blob/6b2e0dc72db42f8aceb98da87865d9300c298375/packages/plugins/sentry/server/middlewares/sentry.js#L8-L22

The code loads the sentry plugin service (line 8). Based on this service it loads the Sentry SDK by using the `getInstance` (line 10) and stores the this instance in the `sentry` variable.

On this sentry variable, it calls the `sendError()` function (line 21)
Here is the error: this `sendError()` function is not part of the Sentry SDK so it does not exist here.
Instead this function is defined in the plugin service itself. So the correct code should be:

```js
// ...

  strapi.server.use(async (ctx, next) => {
    try {
      await next();
    } catch (error) {
      console.log('sentry send error', sentry)
      sentryService.sendError(error, (scope, sentryInstance) => {
// ...
```

The correct usage of the `sendError()` function is described in the plugins readme: https://github.com/strapi/strapi/tree/master/packages/plugins/sentry#global-sentry-service

```js
strapi
    .plugin('sentry')
    .service('sentry')
    .sendError(error);
```

**Comment by emilieringwald** [comment]
Thanks @derweili, that's indeed something we plan to work on in the coming weeks. We'll keep you posted!

**Comment by joseAbarcaSaavedra** [comment]
same problem here!

**Comment by gdSuhail** [comment]
> same problem here!

I am also getting `@strapi/plugin-sentry is disabled because no Sentry DSN was provided` in` Strapi v4.1.12`. I tried giving the DSN directly in the plugin.js but the issue is still  there.

My plugin.js
```
module.exports = ({ env }) => ({
  sentry: {
    enabled: true,
    config: {
      dsn: `MYSENTRYDSN`,
      sendMetadata: true,
    },
  },
});
```

package.json

```
{
  "name": "medicine-strapi-api2",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "docker-develop": "docker-compose up --build --force-recreate",
    "docker-down": "docker-compose down",
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.12",
    "@strapi/plugin-sentry": "^4.1.12",
    "@strapi/plugin-users-permissions": "4.1.12",
    "@strapi/strapi": "4.1.12",
    "pg": "^8.7.3",
    "strapi-plugin-import-export-entries": "^1.2.0",
    "strapi-plugin-transformer": "^2.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "cf33c79f-e2e6-470d-8d4f-b800374e1d86"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**Comment by gdSuhail** [comment]
> > same problem here!
> 
> I am also getting `@strapi/plugin-sentry is disabled because no Sentry DSN was provided` in` Strapi v4.1.12`. I tried giving the DSN directly in the plugin.js but the issue is still there.
> 
> My plugin.js
> 
> ```
> module.exports = ({ env }) => ({
>   sentry: {
>     enabled: true,
>     config: {
>       dsn: `MYSENTRYDSN`,
>       sendMetadata: true,
>     },
>   },
> });
> ```
> 
> package.json
> 
> ```
> {
>   "name": "medicine-strapi-api2",
>   "private": true,
>   "version": "0.1.0",
>   "description": "A Strapi application",
>   "scripts": {
>     "docker-develop": "docker-compose up --build --force-recreate",
>     "docker-down": "docker-compose down",
>     "develop": "strapi develop",
>     "start": "strapi start",
>     "build": "strapi build",
>     "strapi": "strapi"
>   },
>   "dependencies": {
>     "@strapi/plugin-i18n": "4.1.12",
>     "@strapi/plugin-sentry": "^4.1.12",
>     "@strapi/plugin-users-permissions": "4.1.12",
>     "@strapi/strapi": "4.1.12",
>     "pg": "^8.7.3",
>     "strapi-plugin-import-export-entries": "^1.2.0",
>     "strapi-plugin-transformer": "^2.0.1"
>   },
>   "author": {
>     "name": "A Strapi developer"
>   },
>   "strapi": {
>     "uuid": "cf33c79f-e2e6-470d-8d4f-b800374e1d86"
>   },
>   "engines": {
>     "node": ">=12.x.x <=16.x.x",
>     "npm": ">=6.0.0"
>   },
>   "license": "MIT"
> }
> ```

I was using `plugin.js` but it should be `plugins.js`. I renamed the file and now it is working fine.
