### ISSUE TITLE
Sentry Plugin Readme should be updated for Strapi 4

### ISSUE THREAD

**Issue by derweili** [strapi/strapi#12065]
### Describe the bug

As described in  #12064 the sentry plugin configuration instructions are outdated and should be updated for strapi 4.

### Steps to reproduce the behavior

1. Check ticket #12064 and follow the instructions there.

### Expected behavior

The Instructions should work for Strapi 4

### Code snippets

`config/plugins.js`:
```
module.exports = ({ env }) => ({
  // ...
  sentry: {
    enabled: true,
    config: {
      dsn: env('SENTRY_DSN', null),
      sendMetadata: true,
    }
  },
  // ...
})
```
### System

- Node.js version: v16.13.1
- NPM version: 1.22.17
- Strapi version: 4.0.0
- Database: sqlite
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12064
