### ISSUE TITLE
Strapi v4 - Rest API set publicationState

### ISSUE THREAD

**Issue by reijerteunis** [strapi/strapi#12069]
For my project I am using the rest API to import CSV files into my Strapi v4 admin. This as I need to import more than 300k records.
By default I want to publicationState to be preview, though I don't find a way to achieve this with the API.

Can anyone help me out?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
