### ISSUE TITLE
Strapi V4 sometime drops custom database table

### ISSUE THREAD

**Issue by lazidoca** [strapi/strapi#12068]
### Describe the bug

When adding custom table to database, for example Knex migration table for adding indexes..., the tables are dropped when making some changes in Strapi Content-Type Builder which triggers the database schema changes.

### Steps to reproduce the behavior

1. Add new custom table to database
2. Add new column to an existing content type in Content-Type Builder
3. Click Save to take the effect
4. The table added in step 1 is dropped

### Expected behavior

Any custom table that is not managed by Strapi should not be dropped

### System

- Node.js version: v16
- NPM version:
- Strapi version: v4.0.2
- Database: Postgresql
- Operating system: WSL2

### Additional context

I noticed this bug sometime happens, sometime not

**Comment by derrickmehaffy** [comment]
This is intended based on #1114 

If Strapi doesn't know what the table/column is attached to then it's purged.

**Comment by arunnethues** [comment]
@derrickmehaffy  

I am facing the same issue on v4. 
I am working on custom api and running sql query on custom tables.

could you please elaborate?

what is correct solution for it?
how to handle custom tables?
do I need to create [Models](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html) for each table (personally I don't want to do this)?

**Comment by asergey87** [comment]
I am facing this bug on Strapi 4.5.4 too
Futhermore, when I'm trying to add custom indexes to my strapi content-type tables, these indexes will be deleted after a next re-strart a project ( I tried to do this in two ways: migrations (I know, this is experimental feature, but I tried) and bootstrap method, results the same)
Any idea how to avoid this behaviour?
Thank you!

**Comment by derrickmehaffy** [comment]
Hi @asergey87 can you please open a feature request for this on https://feedback.strapi.io

We had some early design ideas for adding custom indexes to the schema file but I don't believe we have implemented them yet. It would be good to see how many others also need this feature.

Thanks!

**Comment by beetleHun** [comment]
Hi,

I faced the same issue, and if anyone's still wondering, I used a workaround like this:

1. Use manual knex migration files to create the custom tables in the a separate schema (other than the one used by strapi to store the content related tables)

`exports.up = function (knex) {
  return knex.schema.withSchema('<CUSTOM_SCHEMA>')
    .createTable('<CUSTOM_TABLE>', (table) => {
      ...
    });
};`

We have to use manual migrations due to project specific reasons anyway.

2. Setup knexfile to use the separate schema. This way, the _knex_migrations_ table will be in the custom schema as well.

`module.exports = {
  ...
  migrations: {
    directory: './migrations',
    tableName: 'knex_migrations',
    schemaName: '<CUSTOM_SCHEMA>'
  },
};`

3. Create the schema in the database (of course in the same one of which the strapi is connected to)
4. Run the migrations

After any content type modifiation, the tables created in the custom schema will remain.

**Comment by derrickmehaffy** [comment]
We do have native migrations support if you want to construct your own: https://docs.strapi.io/developer-docs/latest/developer-resources/database-migrations.html#understanding-database-migration-files

**Comment by derrickmehaffy** [comment]
> It seems this makes it impossible to create a custom table in the same schema, as it is immediately purged.
> 
> e.g. a migration file like this
> 
> ```js
> "use strict";
> 
> async function up(knex) {
>   await knex.schema
>     .createTable("custom", (table) => {
>       table.increments("id").primary();
>     });
> }
> 
> module.exports = { up };
> ```
> 
> will result in a successful call to create the table on startup, which debug mode shows is immediately dumped afterwards.
> 
> If that's correct, you should probably update the custom migration docs to mention this limitation, as it seems people will need to store data in a separate schema for many use cases.

Indeed, could you do me a favor and open an issue on our documentation repo for this? https://github.com/strapi/documentation

Thank you!

**Comment by chuve** [comment]
What is the reason to purged tables?
In case of renaming the `collectionName` the table is dropped as well. Which is seems a risky in terms of loose the data if you run server on locale pointing to the production database...

**Comment by derrickmehaffy** [comment]
> What is the reason to purged tables?
> In case of renaming the `collectionName` the table is dropped as well. Which is seems a risky in terms of loose the data if you run server on locale pointing to the production database...

There is no way for Strapi to know if you deleted/created or renamed something when manually changing the collectionName. We do plan to, this year, update the CTB to give it the context required to handle renames properly but manual file editing will not be possible.

The reason we clean up the database is detailed here: #1114

**Comment by sujayroro** [comment]
We use Strapi as an Admin panel for our project. Apart from admin related tables rest of schemas are from NestJs entities. For such use case the latest feature #1114 will be bad.

**Comment by michaelbutler** [comment]
This is really sad. Lesson learned for me I guess, but I was playing around with Strapi and connected it to my production postgres database. Other products support a "shared" database by putting prefixes on the table. Strapi cleared my DB with no warning and I had to restore a backup from 3 days ago 😢

**Comment by derrickmehaffy** [comment]
> This is really sad. Lesson learned for me I guess, but I was playing around with Strapi and connected it to my production postgres database. Other products support a "shared" database by putting prefixes on the table. Strapi cleared my DB with no warning and I had to restore a backup from 3 days ago 😢 

We do have a warning for this in the documentation: https://docs.strapi.io/dev-docs/configurations/database

Right at the top of the page.

**Comment by michaelbutler** [comment]
@derrickmehaffy yes you're totally right, I saw that afterwards while browsing through the docs. Interestingly how I ended up here was through the Docker steps, which I understand you don't officially support. However I'll open a Pull Request to add that important warning to any of the Docker pages because I think it could happen to someone else who is looking for a quick start via docker.   Thanks.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy yes you're totally right, I saw that afterwards while browsing through the docs. Interestingly how I ended up here was through the Docker steps, which I understand you don't officially support. However I'll open a Pull Request to add that important warning to any of the Docker pages because I think it could happen to someone else who is looking for a quick start via docker. Thanks.

For sure, please feel free. Obviously we want to make it clear to users what will happen
