### ISSUE TITLE
[Request] replace `mysql` package with `mysql2` to avoid authentication protocol error

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#12062]
### Describe the bug

I created a brand new Strapi v4 app but then got an error saying : 
```bash
error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

This happened after running `yarn develop`.

### Steps to reproduce the behavior

1. Create Strapi app with `yarn create strapi-app my-app`
2. Open the app (`my-app`) in a text editor like VScode.
3. Run `yarn develop`.

### Expected behavior

According to this [thread](https://stackoverflow.com/a/56509065) : 

>MySQL 8 has supports pluggable authentication methods. By default, one of them named caching_sha2_password is used rather than our good old mysql_native_password.

In addition, rather than doing something like : 
- `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'` and then `flush privileges`
it is recommended to replace "mysql.js" with "mysql2.js" package.

I see that Strapi v4.0.2 uses `mysql` package : 

![image](https://user-images.githubusercontent.com/43397636/147839305-97eea8c9-7995-4b5c-82b5-06f6a6dbb6a5.png)

Probably it would be nice if Strapi can utilize `mysql2` package instead of `mysql` package.

<br />

### Screenshots

![image](https://user-images.githubusercontent.com/43397636/147839116-55dbd856-8918-45b9-9755-c3f744de7061.png)

### System

- Node.js version: v16.13.1
- NPM version: v8.1.2
- Strapi version: v4.0.2
- Database: MySQL v8.0.27
- Operating system: Ubuntu 20.04

**Comment by pranay101** [comment]
Hi, I am new to open source and I would like to work on this issue. Please guide me further on what needs to be done.

**Comment by derrickmehaffy** [comment]
This isn't us, it needs to happen on Knex.js also https://github.com/knex/knex/issues/717#issuecomment-974827621

Until they figure that out, not much we can do.

**Comment by VictorienTardif** [comment]
> This isn't us, it needs to happen on Knex.js also [knex/knex#717 (comment)](https://github.com/knex/knex/issues/717#issuecomment-974827621)
> 
> Until they figure that out, not much we can do.

Hi, it looks like knex does support mysql2 https://github.com/knex/knex/blob/89bd0a034fc22413a1f8328bb09193d0a1b5d113/lib/dialects/mysql2/index.js

**Comment by domfie** [comment]
Quickfix: Add `case 'mysql2':` underneath `case 'mysql':` in the @strapi/database/lib/dialects/index.js. If I got time I will open a pull request ☺️

**Comment by derrickmehaffy** [comment]
> Quickfix: Add `case 'mysql2':` underneath `case 'mysql':` in the @strapi/database/lib/dialects/index.js. If I got time I will open a pull request relaxed

It's not quite that easy but I plan on opening a PR shortly, first though we needed to get Knex upgraded to v1. If all goes well this will be merged and released on Wednesday and mysql2 2 weeks after that:
https://github.com/strapi/strapi/pull/12918

**Comment by bornschlegell81** [comment]
I have the same problem.
@derrickmehaffy  was created the PR? What can I do to fix the problem?
Thank you very much

**Comment by derrickmehaffy** [comment]
> I have the same problem.
> @derrickmehaffy  was created the PR? What can I do to fix the problem?
> Thank you very much

I haven't had the time currently but it shouldn't be too difficult to add.

In the short term you can use the legacy password method for MySQL 8

**Comment by Keetta** [comment]
up

**Comment by bornschlegell81** [comment]
up

**Comment by jpcmf** [comment]
up

**Comment by derrickmehaffy** [comment]
Locking this as the `up` comments are not useful. This is something we will work on once we have some free time, else if anyone wants to submit a PR please feel free, but we do need to keep backwards compatibility with `mysql` and not just replace it with `mysql2`

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/add-support-for-mysql2-mysql-v8-auth-system
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
