### ISSUE TITLE
Access controls on data

### ISSUE THREAD

**Issue by osharpe** [strapi/strapi#1207]
Hi, first of all I would like to commend on this product, I am really enjoying exploring the features, it really makes your life easy when developing API.

This is more of a question than feature request and somewhat related to the following issue, however it doesn't really answer my question. https://github.com/strapi/strapi/issues/803

If I have 3 collections - Company, Site, Sensor. I only want to return information which is related to the logged in user.

I don't want to pass this as a argument in the URL http://localhost:1337/company?username=companyuser as its for a multi-tenant application and the API public. I need controls on the API to prevent a customer accessing another customers data.

Like `/user/me` I am looking to create something similar for custom models, which will only return data related to the logged in user.

Can you advise the best way I would implement this in Strapi?

Thanks

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by raulriera** [comment]
I believe this is something that needs to be handle in your models and controllers. I have the same need where I want people to only access information on their account. I'm trying something similar here, where everything is scoped under `practice` account. https://stackoverflow.com/questions/50297399/strapi-graphql-overwrites/50353764#50353764

The implementation of `findMine` looks something like this

```javascript
  /**
   * Retrieve a practice record for the authenticated user.
   *
   * @return {Object}
   */

  findMine: async (ctx) => {
    ctx.params._id = ctx.state.user.practice._id
    return strapi.services.practice.fetch(ctx.params);
  },
```

And then inside your /practice/services.yml you can scope the search either using `.where(conditions)`, `.find(conditions)`, etc

**Comment by lauriejim** [comment]
Please check this issue https://github.com/strapi/strapi/issues/624

@raulriera thank you for your time on this issue.
