### ISSUE TITLE
The classification and entity dependencies API does not show the full relationship

### ISSUE THREAD

**Issue by studyLiyuhong165** [strapi/strapi#12077]
I have a beverage category and a menu
Why the menu data of my drinks category is not displayed correctly. For example, the picture of the menu is not displayed
I've already used population=*
![strapi_drinks](https://user-images.githubusercontent.com/96882850/147911046-40e4e957-ac71-4f87-b2dd-aec4f76b4886.png)
![strapi_menus](https://user-images.githubusercontent.com/96882850/147911049-f1db3593-58be-4ed4-92c2-1a388c5a7799.png)

I tested both apis separately
Menu API display complete
![strapi_drinks_api](https://user-images.githubusercontent.com/96882850/147911126-4cc9fcd2-84bc-4dcb-a383-89c5fe3f09c9.png)
![strapi_menus_api](https://user-images.githubusercontent.com/96882850/147911132-ac54e37f-cdab-400a-b4a7-4ee2408197c3.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
