### ISSUE TITLE
[v4] Relation don't show in api response

### ISSUE THREAD

**Issue by VEXstar** [strapi/strapi#12076]
I'm trying to create an entity that will depend on another one, for example I created a test entity that references to user :
![image](https://user-images.githubusercontent.com/46082448/147891418-54764df9-f19c-4d67-9c34-ca71523a1f1c.png)

Added an entry to the entity:
![image](https://user-images.githubusercontent.com/46082448/147891438-fdcfc3b2-f093-4da1-80ff-e6f6dd100b09.png)

However, the api displays only a text field:
![image](https://user-images.githubusercontent.com/46082448/147891490-2bfceef2-70e5-440d-a7d1-1b757133dfc0.png)

I assumed that I was doing something wrong, but after studying the documentation, I came to the conclusion that it looks like this field should also be displayed.

### System

- Node.js version: v16
- Strapi version: v4.0.0
- Database: postgresql (also does not work with litesql)
- Operating system: Debian 10

**Comment by Webbist-dev** [comment]
You need to make use of populate. 
Check the docs here. 
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population
