### ISSUE TITLE
An empty email is accepted by API even when field is required

### ISSUE THREAD

**Issue by drazik** [strapi/strapi#12081]
### Describe the bug

I have the following collection type:

```json
{
  "kind": "collectionType",
  "collectionName": "newsletter_subscribers",
  "info": {
    "singularName": "newsletter-subscriber",
    "pluralName": "newsletter-subscribers",
    "displayName": "Newsletter subscriber"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "email": {
      "type": "email",
      "required": true,
      "unique": false
    }
  }
}
```

The `email` field is of type `email` and is required. When I send a POST request to `/api/newsletter-subscribers` with the following data:

```json
{
  "data": {
    "email": ""
  }
}
```

The item is created, I receive a `200` response and I see it in the admin panel, even if:

* it shouldn't pass the `required` rule
* it is not an email

### Steps to reproduce the behavior

1. Create a collection type with a required email field
2. Send a post request with an empty string for the field
3. Get a 200 OK response instead of 400 Bad Request

### Expected behavior

The API should return a `400 Bad Request` error, either because the field value is empty, or because an empty string is not an email.

### System

- Node.js version: 16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.2
- Database: SQLite
- Operating system: Ubuntu v21.10

**Comment by abdonrd** [comment]
Seems related to https://github.com/strapi/strapi/issues/11882

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11882
