### ISSUE TITLE
[v4] Don't show relationships as uppercase

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12087]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Right now the relationships appear as uppercase.

<img width="288" alt="Screenshot 2022-01-03 at 20 41 00" src="https://user-images.githubusercontent.com/1007051/147973687-ed41cdce-79b5-4828-a0c6-e458ef00797a.png">

<img width="430" alt="Screenshot 2022-01-03 at 20 41 12" src="https://user-images.githubusercontent.com/1007051/147973693-f318bad3-4148-40f7-811b-ea966dbaf9dd.png">

### Why is it needed?

To respect the original case.

### Suggested solution(s)

Just remove the uppercase.

**Comment by soupette** [comment]
Hello @abdonrd 👋 

With our new design system all links have the same UI, see our [documentation](https://design-system-git-develop-strapijs.vercel.app/?path=/story/design-system-components-link--base) therefore, all links in the admin panel are uppercased.

cc/ @maevalienard @rgesulfo

**Comment by abdonrd** [comment]
Thanks for the reference, @soupette!

I would like to propose to keep the original case, since it can add clarity/meaning.

**Comment by maevalienard** [comment]
Since a change on this component will have an impact on the whole admin panel, we'll take your feedback into consideration for now and make sure we address the change if multiple people agree with you (if that's fine for you) 😄

**Comment by abdonrd** [comment]
Understood thanks!

Meanwhile, could you explain a way to remove the uppercase for this specific case? Thanks!

**Comment by derrickmehaffy** [comment]
> Since a change on this component will have an impact on the whole admin panel, we'll take your feedback into consideration for now and make sure we address the change if multiple people agree with you (if that's fine for you) smile

I'm one of those that agree, I don't really see a reason why we should be forcing a case here? There isn't a logic reason so it must be more design related.

**Comment by torchsmith** [comment]
I agree as well. I understand it from a design perspective, but functionally showing the case differences can make things easier to understand when done purposefully.

**Comment by gu-stav** [comment]
I believe this issue is fixed with the latest release of Strapi (`4.5.0`). Relations have been refactored: https://strapi.io/blog/announcing-strapi-v4.5
