### ISSUE TITLE
Strapi v4 trying to create a .env file with some vars and platform.sh has a forceful read only file system (ROFS)

### ISSUE THREAD

**Issue by hacktivist123** [strapi/strapi#12088]
### Describe the bug

The problem is on boot, Strapi is trying to create a .env file with some vars and platform.sh has a forceful read-only file system (ROFS). So Strapi throws an error because it can't create the .env and it does not check if it already has the values before it tries to create it

### Steps to reproduce the behaviour

1. Create a new strapi v4 application with a Postgres DB
2. Deploy on [Platform.sh](https://platform.sh) in Production
3. After deployment run `platform app logs`
4. See the error in terminal

### Expected behaviour

The strapi application is expected to start successfully.

### Screenshots

![screenshot](https://res.cloudinary.com/hacktivist/image/upload/v1641239649/stuff_wkps7z.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12
- NPM version: v6
- Strapi version:  v4
- Database: Postgres
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
@alexandrebodin / @petersg83 this is the issue I was referring to about us trying to write to .env on every boot even if the file exists and the key exists. It breaks various providers like Platform.sh and Google Apps

**Comment by alexandrebodin** [comment]
The code is only supposed to create the vars if they don't already exist or are set in the config. Here the code it refers too:

```
if (!strapi.config.get('plugin.users-permissions.jwtSecret')) {
    const jwtSecret = uuid();
    strapi.config.set('plugin.users-permissions.jwtSecret', jwtSecret);

    if (!process.env.JWT_SECRET) {
      strapi.fs.appendFile('.env', `JWT_SECRET=${jwtSecret}\n`);
    }
  }
```

@hacktivist123 you said the code doesn't check the value but reading it it seems the value doesn't exist. Can you share how you defined it?

In the case we can write the file I think we should throw an error then @petersg83

**Comment by derrickmehaffy** [comment]
> The code is only supposed to create the vars if they don't already exist or are set in the config. Here the code it refers too:
> 
> ```
> if (!strapi.config.get('plugin.users-permissions.jwtSecret')) {
>     const jwtSecret = uuid();
>     strapi.config.set('plugin.users-permissions.jwtSecret', jwtSecret);
> 
>     if (!process.env.JWT_SECRET) {
>       strapi.fs.appendFile('.env', `JWT_SECRET=${jwtSecret}\n`);
>     }
>   }
> ```
> 
> @hacktivist123 you said the code doesn't check the value but reading it it seems the value doesn't exist. Can you share how you defined it?
> 
> In the case we can write the file I think we should throw an error then @petersg83

Honestly @alexandrebodin I'm of the opinion we really shouldn't be directly writing to a .env as was another case from another user were on their system they had strapi writing to their .env file with hundreds of `JWT_SECRET=randomstuff`.

It's honestly not a best practice to do this automatically, .env files could have a CLI command to generate them but as you don't commit a .env into source control and most PaaS systems won't use it we really should just stick to our .js config files.

It should be user choice if they want to use or generate a .env or handle CLI env vars.

**Comment by derrickmehaffy** [comment]
Meaning in the case of users-permissions we just need to generate the plugins.js file instead of .env

**Comment by jamesv-menklab** [comment]
Running into the same issue on GCS.  Is there any work around at this point?

**Comment by jamesv-menklab** [comment]
Still seeing the same error:

Error: EROFS: read-only file system, open '/workspace/.env'
    at Object.openSync (fs.js:497:3)
    at Object.writeFileSync (fs.js:1528:35)
    at Object.appendFileSync (fs.js:1567:6)
    at Object.appendFile (/workspace/node_modules/@strapi/strapi/lib/services/fs.js:53:18)
    at Object.module.exports [as bootstrap] (/workspace/node_modules/@strapi/plugin-users-permissions/server/bootstrap/index.js:34:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

The entire process with Strapi 4 and GCS has been a bit rocky.  More than happy to test and help out in whatever ways I can!

**Comment by derrickmehaffy** [comment]
Suggestion (taking from convo on discord):

- We should only generate the .env (and a **complete** .env.example) during `--quickstart` deployments
- We should have a CLI command to generate the .env
- We should define the plugins.js with the JWT_SECRET for U&P by default if U&P is installed by default and use the env() syntax
- API_TOKEN_SALT should be put in whatever config file it's supposed to be in (admin.js or server.js) just like the ADMIN_JWT_SECRET is
- Never generate `.env` on boot


Any automatic management (CUD) of a `.env` is anti-pattern and dangerous

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/12255

**Comment by petersg83** [comment]
Thanks for the propositions @derrickmehaffy I've made a PR #12287 that matches almost all you said
