### ISSUE TITLE
Connection cancels on production (randomly)

### ISSUE THREAD

**Issue by ari-motors-team** [strapi/strapi#12086]
### Describe the bug

The deployment of strapi v4 cancels due to a connection error. Here is what I figured out so far:

This behavior applies to Heroku, Digitalocean and Render. Therefore I guess, it's not hosting related.
The behavior did never occure on localhost production builds.

Frontend is running on nextjs and hostet on vercel.
The build process of 1000 pages throws errors randomly (1 to 3 at a time) and always on different sites.

Strapi is hosted on digitalocean at the moment.

As db postgres 13 is used, hosted on digitalocean. (4gb ram, 2 cores)
Here comes the odd behavior. Running strapi on a 10$ instanze. (1gb ram, 1 shared core) does **not** run into any errors.
Deploying strapi on a 50$ instanze (4gb ram, 2 shared cores) make the error occure.

I had the same problem on "bigger" instanzes with different hosting providers.
I assume, that the db server somehow cancels on to many request at a short amount of time.

error
```bash
Error occurred prerendering page "/cs/kontakt/virtualni-showroom". Read more: https://nextjs.org/docs/messages/prerender-error
<span>TypeError: Cannot read property 'data' of undefined</span>
```

Please note, that the error always occures on different pages, but is alway ` Cannot read property 'data' of undefined`, which indicates that the data of the page was not loaded.

### Steps to reproduce the behavior

1. Setup strapi on a pricy server instanze
2. Add 10000+ data entries and fetch them concurrently like vercel ci does.
3. See error

### Expected behavior

Does not cancel request

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.2 (occures at least since beta.10)
- Database: postgres 13
- Operating system: fedora

**Comment by ari-motors-team** [comment]
It just worked once. The issue persists on every setup.

**Comment by derrickmehaffy** [comment]
related to #11860, we need more reproduction steps.

**Comment by ari-motors-team** [comment]
I did send you a friend request on discord. You can have access to the github repo for reproduction.

**Comment by ari-motors-team** [comment]
I got more info on the issue for you. First of all. It does not seem to be any performance/timeout issue at all.
The db disconnects "somehow" on its own.
The problem might be related to the pg schema.

When exporting pg with a custom format
```bash
pg_dump -d pgstring?sslmode=require -Fc > backup.sql
```

and importing it again
```bash
pg_restore -d 'pgstring?sslmode=require' --jobs 4 backup.sql
```

the data gets imported with errors regarding to relations
https://pastebin.pl/view/407aed0d

The data except relations still gets imported, but are not shown in the strapi ui.
You can check that by creating a new entry. It will not start with id 1.
Collections without relations work fine. (Even with i18n plugin)

Importing data with the `--clean` arg (recreate db) made the collections appear, but I think that somehow causes the issue.
```bash
pg_restore -d 'pgstring?sslmode=require' --clean --jobs 4 backup.sql
```

The last try was im-/exporting as text format
```bash
pg_dump -d pgstring?sslmode=require --no-owner --no-acl > dump.sql
psql -d 'ppgstring?sslmode=require' < dump.sq
```
Permissions were not imported (settings > roles > public)

After logging in the first time it felt like strapi was doing some magic. For now the deployment worked.
It seems to break down more often, when people are working in strapi.

I will come back to this, when I used the current version for a while.

**Comment by ari-motors-team** [comment]
Ok, I think I got this working.
Changing the pool config to a minimum made it work.
The build time hasn't been effected by this at all. Even the connections on the db pool on digitalocean stayed the same.
Guess something isn't working as expected there.
For me the workaround fits for now and I think that should be sufficient to investigate the issue.
Still its a rather important issue to solve, even with the workaround.

database.js
```
const { parse } = require("pg-connection-string");

module.exports = ({ env }) => {
  if (process.env.NODE_ENV === "development") {
    return {
      connection: {
        client: "postgres",
        connection: {
          host: "postgres",
          port: 5432,
          database: "strapi",
          user: "strapi",
          password: "strapi",
          ssl: false,
        },
      },
    };
  } else {
    const { host, port, database, user, password } = parse(
      process.env.DATABASE_URL
    );

    return {
      connection: {
        client: "postgres",
        connection: {
          host,
          port,
          database,
          user,
          password,
          ssl: {
            rejectUnauthorized: env.bool("DATABASE_SSL_SELF", false), // For self-signed certificates
          },
        },
        pool: {
          min: 0,
          max: 2,
          acquireTimeoutMillis: 60000,
          createTimeoutMillis: 60000,
          destroyTimeoutMillis: 20000,
          idleTimeoutMillis: 60000,
          reapIntervalMillis: 1000,
          createRetryIntervalMillis: 1000,
        },
      },
      settings: { forceMigration: false },
    };
  }
};
```

**Comment by derrickmehaffy** [comment]
Not likely an issue with the code but environmental. Setting as closed

**Comment by ari-motors-team** [comment]
I doubt it, but well. Guess some other guys will come across this later...

**Comment by TheBit** [comment]
Our setup is also affected and has the same issue:
## System
- Node: 16.13.2
- Yarn: 1.22.15
- Strapi: 4.1.5
- Database: Postgres 13.4 on AWS RDS
- Operating system: FROM node:16.13.2-alpine
- Next.js: 12.0.4

Our CI/CD pipeline stops occasionally due to Strapi being unable to respond to some of those `getStaticProps` => `Apollo Client` => `Strapi GraphQL plugin` calls for hundreds of pages...

**Comment by derrickmehaffy** [comment]
We need more information to reproduce it, as we need to be accurately be able to reproduce the issue to classify it as a bug. Changing tuning configs for Knex is not a bug as that largely depends on the deployment environment. We can't set sane defaults that will work for everyone in every use-case.

It's clear to me based on previous comments that the issue is largely environmental as changing tuning config options appears to solve the issue for most. This isn't the only issue referencing those tuning options and they don't come from us, it's from Knex (specifically tarn.js the pool manager). We have some very light documentation on it but it's best to review their docs as it's likely more complete than ours.
