### ISSUE TITLE
v4.0.2 Unable to query Fields on Content-Types with Gatsby

### ISSUE THREAD

**Issue by ChrisLau90** [strapi/strapi#12093]
### Describe the bug
Gatsby is unable to query fields within Content-Types. The top level content-type can be seen, but non of the fields within it are accessible.

I have gone back to use v3.6.2 as this issue is not present there.

### Steps to reproduce the behavior

I have a brand new Strapi project (`v4.0.2`) with one Single-Type (`homepage`) and one field (`title`). I have enables the `findOne` permission on the `homepage` type for the `public` role.

I run the following query from the graphQL inspector with Gatsby:
```
query MyQuery {
  strapiHomepage {
    title
  }
}
```

and I get the following error:
```
{
  "errors": [
    {
      "message": "Cannot query field \"title\" on type \"StrapiHomepage\".",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "extensions": {
        "stack": [
          "GraphQLError: Cannot query field \"title\" on type \"StrapiHomepage\".",
          "    at Object.Field (C:\\Repos\\drops-bishnaw-frontend\\node_modules\\graphql\\validation\\rules\\FieldsOnCorrectTypeRule.js:48:31)",
          "    at Object.enter (C:\\Repos\\drops-bishnaw-frontend\\node_modules\\graphql\\language\\visitor.js:323:29)",
          "    at Object.enter (C:\\Repos\\drops-bishnaw-frontend\\node_modules\\graphql\\utilities\\TypeInfo.js:370:25)",
          "    at visit (C:\\Repos\\drops-bishnaw-frontend\\node_modules\\graphql\\language\\visitor.js:243:26)",
          "    at validate (C:\\Repos\\drops-bishnaw-frontend\\node_modules\\graphql\\validation\\validate.js:69:24)",
          "    at graphqlMiddleware (C:\\Repos\\drops-bishnaw-frontend\\node_modules\\express-graphql\\index.js:98:38)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
        ]
      }
    }
  ]
}
```

### Expected behavior

`homepage` content-type with `title` field can be queried, and data can be retrieved.

### Screenshots

Strapi Dashboard showing Content-Type with data present:
![image](https://user-images.githubusercontent.com/1782800/148050544-e323e676-2182-4085-9d46-cf72acd0ca89.png)

Gatsby GraphQL inspector showing content-type with no title field available and error showing
![image](https://user-images.githubusercontent.com/1782800/148050383-fca36ab6-6755-4f2d-a723-65611f6789c9.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16.13.1
- NPM version: v7.24.0
- Strapi version: v4.0.2
- Database: SQLite
- Operating system: Windows 10

### Additional context

I'm able to see all the fields and query the data using Strapi v3.6.2

**Comment by derrickmehaffy** [comment]
GraphQL structure has changed since v3: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/graphql-api.html#graphql-api

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
