### ISSUE TITLE
Bulk delete for non-default locale collection type entries doesn't delete entries

### ISSUE THREAD

**Issue by drazik** [strapi/strapi#12092]
### Describe the bug

When deleting multiple entries in non-default locale for a localizable collection type, the entries are not deleted.

### Steps to reproduce the behavior

1. Go to a localizable collection type list
2. Select a locale that is not the default locale
3. Select multiple entries
4. Click on the delete button to delete selected entries
5. Entries are still there

### Expected behavior

Selected entries should be deleted

### Screenshots

![Peek 2022-01-04 11-05](https://user-images.githubusercontent.com/1606068/148042836-88ba942e-4d5f-4c0f-97da-548f00be5550.gif)

### System

- Node.js version: 16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.2
- Database: SQLite
- Operating system: Ubuntu v21.10

### Additional context

Deleting entries one by one works.

**Comment by derrickmehaffy** [comment]
Uhhhhh, can you make sure this doesn't delete the primary locale? :cold_sweat: I hope not (spinning something up to validate now)

**Comment by derrickmehaffy** [comment]
(It doesn't) and confirmed

**Comment by ejgonzalez17** [comment]
Hi, is the issue still open? If so, I would like to contribute by doing so.

**Comment by ejgonzalez17** [comment]
I have made a PR of the topic, I will be attentive to your comments and corrections, have a nice day =)

**Comment by timbrandin** [comment]
Workaround solution is to temporary change the default locale in Strapi and then change it back
