### ISSUE TITLE
[v4] Filter by component data it's not working

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12098]
### Describe the bug

When I try to filter by component data it doesn't work.

### Steps to reproduce the behavior

1. Create a few entries with component. In this example I have a `result` component with `winners` and `replicas`:

<img width="1174" alt="Screenshot 2022-01-04 at 18 31 31" src="https://user-images.githubusercontent.com/1007051/148099759-21663486-1c77-4845-8abd-da969508d5ca.png">

2. It works if I search by a relationship:

<img width="1737" alt="Screenshot_2021-12-29_at_19 33 57" src="https://user-images.githubusercontent.com/1007051/148099498-56646988-8dc0-4171-885f-c43aa789c91c.png">

3. But it doesn't work if I try to filter by the component:

<img width="1737" alt="Screenshot_2021-12-29_at_19 34 02" src="https://user-images.githubusercontent.com/1007051/148099538-af71e2ab-d62d-41e5-9f3f-7948daeffc59.png">

The error is:

>Field \"result\" is not defined by type \"BattleFiltersInput\".

### Expected behavior

Can filter by component.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4.0.2
- Database: SQLite
- Operating system: macOS

**Comment by mariod3w** [comment]
Hello @abdonrd  

how did you solve it?

Is it possible to filter by component somehow?

Thanks.

**Comment by abdonrd** [comment]
No, no news :/

**Comment by derrickmehaffy** [comment]
Tested on v4.1.8 and works fine all the way down to various levels.

Tested compo => compo => relation

![image](https://user-images.githubusercontent.com/8593673/163871870-8ee688e4-d258-4446-8cfc-756de3b2990b.png)

**Comment by nachaos** [comment]
I have the same issue.
As @abdonrd mentioned on the provided example this happens when trying to filter using graphql and not the REST API.
@derrickmehaffy can you please test this again using a graphql query instead?

Thanks!

**Comment by nachaos** [comment]
@derrickmehaffy can this issue be re-opened?

thanks in advance 🙂

**Comment by derrickmehaffy** [comment]
won't reopen this one but instead will stick with https://github.com/strapi/strapi/issues/13248
