### ISSUE TITLE
[v4] Lack of indentation on components list in Content-Type Builder.

### ISSUE THREAD

**Issue by kamiloox** [strapi/strapi#12094]
### Please describe your feature request

Having an indentation on components list in Content-Type Builder. 

### Summary

Add a little padding or margin to nested elements. This will make them more readable in the category list. I don't really see the difference between dots and arrows.

### Why is it needed?

I don't like this because I always struggle and feel like all of my nested elements are roots.

### Suggested solution(s)
The image shows this idea better. On the left is current behavior and on the right is desired one.
![indentation-feature-request-strapi](https://user-images.githubusercontent.com/45523480/148062673-3dc4a925-f657-48a1-8a0a-9d14d4b2abd7.jpg)

**Comment by gu-stav** [comment]
This issue was fixed with the release of [4.3.3](https://github.com/strapi/strapi/releases/tag/v4.3.3).
