### ISSUE TITLE
GraphQL Query Filters Not Filtering

### ISSUE THREAD

**Issue by clovus** [strapi/strapi#12096]
### Describe the bug

GraphQL plugin is installed on my Strapi environment via NPM, including the playground (https://api-dev.metus-cms.com/graphql). Simple queries are working correctly, however, **filters** are **not** working. 

See attached example where I query only outdoor units where `heating:true`. The API simply returns all records, ignoring the filter. I've tried filtering based other fields and none affect the returned data.

### Steps to reproduce the behavior

1. Go to 'https://api-dev.metus-cms.com/graphql'
2. Use any filter (where, sort, limit, etc.), in this case `where: {heating:true}`
3. Returned data ignores filter(s) and simply returns all records

### Expected behavior

Returned data should be filtered based on specified filters in such a way that I no longer feel like I'm taking crazy pills.

### Screenshots

<img width="1390" alt="Screen Shot 2022-01-04 at 10 10 28 AM" src="https://user-images.githubusercontent.com/7705425/148082276-66f27ca1-9c03-4a8e-bff1-23e87ece2d9b.png">

### Code snippets

`query {
  outdoorUnits(where: {heating:true}) {
    id
    heating
  }
}`

### System

- Node.js version: 16.13.1
- NPM version: 8.1.2
- Strapi version: 3.6.8
- Database: PostgreSQL
- Operating system: macOS - Big Sur 11.6

### Additional context

Querying data from outside the Playground (via React frontend fetch request) has the same results; data is returned with no filtering applied.

**Comment by Webbist-dev** [comment]
Check the docs https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/filter.html#logical-operators
Example of a working filter.

`query Parks($slug: String!) {
  parks(filters: { slug: { eq: $slug } }) {
   
  }
}`

**Comment by Convly** [comment]
Hi,

@Webbist-dev filters are introduced in V4, whereas OP is running a V3.6.8 instance. So I don't think it'll work either.

I'll try to reproduce this issue tomorrow.

**Comment by Convly** [comment]
I tried to reproduce in a brand new application and couldn't. However, I'm able to reproduce on the website you've provided. Do you have custom controllers or special middleware/policies defined & applied on your `outdoorUnits` endpoints?

**Comment by clovus** [comment]
> I tried to reproduce in a brand new application and couldn't. However, I'm able to reproduce on the website you've provided. Do you have custom controllers or special middleware/policies defined & applied on your `outdoorUnits` endpoints?

The only customization I'm aware of is a controller on `outdoorUnits` which appends image URLs to include the full address, not just the local path. I'm primarily a frontend dev (disclaimer), so I have a DevOps team helping with Strapi backend. I've reached out to them as well regarding the issue, so if you think the custom controller could be the cause, I can post the code as soon as I hear back from them.

**Comment by derrickmehaffy** [comment]
I also attempted to reproduce and could not, we will need to see the code you have modified but it's unlikely to be a bug directly with Strapi but the result of modification.

**Comment by clovus** [comment]
My backend team confirmed this issue was due to a custom backend controller they set up, which they were able to fix. Issue is resolved so I'm closing this out.
