### ISSUE TITLE
Not able to see the image url in the strapi api in strapi 4

### ISSUE THREAD

**Issue by deepakgudi-pixel** [strapi/strapi#12104]
Not able to see the image url in the strapi api in strapi 4 how do I fix it?? and also I'm getting two api end points when I added the users

**Comment by 4li-ra** [comment]
@deepakgudi-pixel 
In strapi 4 to get relations, use the populate field in the call. Example to get all relations is : GET /api/books?populate=*
Based on the documentation: 
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population

**Comment by safwendr** [comment]
I think they use the image like a seperate table. So you need to use populate in order to view it and you can retrieve the image as an object.
Example:
`localhost:1337/api/users?populate=*`

**Comment by derrickmehaffy** [comment]
See the above comments, read the population documentation.

Closing due to lack of template
