### ISSUE TITLE
Unable to add Authentication to SWAGGER

### ISSUE THREAD

**Issue by 3akram** [strapi/strapi#12102]
### Describe the bug

Hello, i installed the documentation plugin and added a 'refresh-token' endpoint but i can't see the Authentication in the documentation the email and the file-upload is there but the Authentication is not showing at all - the default endpoints or the extra endpoint that i added. 

### Steps to reproduce the behavior

1. Create a new strapi project
2. Add a custom endpoint by adding the code below to /src/extensions/users-permissions/
3. Added that code to the above file to add /refresh-token endpoint. 
4. The endpoint is working and showing on the admin but there is no Authentication tab in the SWAGGER.

### Expected behavior

To see the Authentication tab in SWAGGER and /refresh-token endpoint should be included. 

### Code snippets

my-project/src/extensions/users-permissions/strapi-server.js

```
const utils = require("@strapi/utils");
const { ValidationError } = utils.errors;
const { getService } = require("./utils");
module.exports = plugin => {
  /* Register a new method to auth controller */
  plugin.controllers.auth.refreshToken = async ctx => {
    const { token } = ctx.request.body || {};
    if (!token) {
      throw new ValidationError("Token not exits.");
    }
    let payload;
    try {
      payload = await getService("jwt").verify(token);
    } catch (e) {
      throw new ValidationError(e.message.toString());
    }
    // Generate a new token
    ctx.body = { jwt: await getService("jwt").issue({ id: payload.id }) };
  };

  /* Add a new routes */
  plugin.routes["content-api"].routes.push({
    method: "POST",
    path: "/auth/refresh-token",
    handler: "auth.refreshToken",
    config: {
      prefix: "",
    },
  });
  return plugin;
};
```
my-project/src/extensions/users-permissions/utils/index.js

```
"use strict";

const getService = name => {
  return strapi.plugin("users-permissions").service(name);
};

module.exports = {
  getService,
};

```

### System

- Node.js version: v14.18
- NPM version: v6.14
- Strapi version: v4
- Database: PostgreSQL
- Operating system: macos monterey

### Additional Context

I tried to remove the custom endpoint but the Authentication is still not showing in SWAGGER.

**Comment by emilieringwald** [comment]
Thanks @3akram , the documentation plugin indeed needs a bit of work and we'll have a look at this in the coming weeks. We'll keep you posted!

**Comment by 3akram** [comment]
Thank you @emilieringwald

**Comment by RomanLubushkin** [comment]
Hey guys, is there any news regarding this one?

**Comment by 3akram** [comment]
@RomanLubushkin - I think not yet!

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/unable-to-add-authentication-to-swagger

Thanks!
