### ISSUE TITLE
Error: ER_TOO_LONG_IDENT | Too long column names hit character restriction in database

### ISSUE THREAD

**Issue by keegankb93** [strapi/strapi#12101]
### Describe the bug

Longer names within components and collections can lead to an error saving to the database due column/table name character restriction limits.

### Steps to reproduce the behavior

1. Create any two collections or combination of a collection + component.
2. Give one or both medium to long names. The two I used:

Collection name: test_articles
Component category: test_category
Component name: my_articles_longer_name

3. Add a relation field in the component that is one to many to the collection you just created.
4. Save
5. See error in strapi console/terminal

```
[2022-01-04 16:03:17.855] error: alter table `components_test_category_my_longer_names_test_article_links` add index
`components_test_category_my_longer_names_test_article_links_inv_fk`(`test_article_id`) - 
ER_TOO_LONG_IDENT: Identifier name 'components_test_category_my_longer_names_test_article_links_inv_fk' is too long
Error: ER_TOO_LONG_IDENT: Identifier name 'components_test_category_my_longer_names_test_article_links_inv_fk' is too long
```

### Expected behavior

Expect to have the ability to either customize the column names or have longer than short collection/component names without going over the database restriction.

### System

- Node.js version: 16.7.0
- NPM version: 7.20.3
- Strapi version: 4.0.2
- Database: MYSQL 5.7
- Operating system: MacOS Big Sur

### Additional information

Current workaround:

Manually editing the collectionName in the respective JSON file will rename in the database.

![image](https://user-images.githubusercontent.com/80284046/148132911-66b63540-7413-4aef-b95b-97982e0fbd0e.png)

**Comment by derrickmehaffy** [comment]
Confirmed

Content-type builder locks out the advanced tab for components so you can't set the collection name (we should be handling this issue automatically thought)

Only applies to components and dynamic zones, if you manually edit the collection name it works fine.

**Comment by derrickmehaffy** [comment]
Closing in favor of tracking issue: https://github.com/strapi/strapi/issues/13117
