### ISSUE TITLE
SOLVED! Unable to start strapi

### ISSUE THREAD

**Issue by OceanTechnic** [strapi/strapi#12108]
### Bug report
Unable to start strapi

### Describe the bug
`npm start develop` /  `strapi develop` will return `You need to run strapi develop in a Strapi project. Make sure you are in the right directory`

### Steps to reproduce the behavior

1. Create strapi project
2. After installation exit the Terminal
3. CD to the directory where you have installed it
4. Try running it 
5. And you will get `You need to run strapi develop in a Strapi project. Make sure you are in the right directory`

### Expected behavior
Strapi will not get started

### Screenshots
![image](https://user-images.githubusercontent.com/63557993/148200415-2a05c484-066b-4630-ab69-74e6fe8c226f.png)

### System

- Node.js version: V16.13.0
- NPM version: 8.1.0
- Strapi version: V4
- Database: SqlLite
- Operating system: Windows11

**Comment by OliwerSmedjevik** [comment]
Try to install all the npm modules with `npm install` inside the strapi project folder.
