### ISSUE TITLE
Strapi breaking after renaming 'content type' or 'attribute'

### ISSUE THREAD

**Issue by decimoseptimo** [strapi/strapi#1210]
**Informations**
- **Node.js version**:v8.11.2
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:mongodb 3.4.15
- **Operating system**:ubuntu server 16.04

**What is the current behavior?**

I was following the [tutorial ](https://www.gatsbyjs.org/blog/2018-1-18-strapi-and-gatsby/) with a few differences. 
- Instead of creating a content-type `article` I called it `post`
- Instead of creating an article attribute `title` I called it `Title`
- The article title was created as `unique & required`

Given the differences my gatsby app was not compiling throwing `TypeError: Cannot read property 'allStrapiArticle' of undefined`.

**Steps to reproduce the problem**
I renamed 'post' to `article` and the server broke, It couldn't restart, but I don't remember the error. I just deleted `api/article/` and recreated it from the GUI.

Then I renamed article `Title` to `title` and the server broke, It cannot restart, throwing

```
[2018-05-17T02:22:16.781Z] info The server is restarting

[2018-05-17T02:22:16.784Z] debug PUT /content-type-builder/models/article (42 ms)

/home/ubuntu/strapi-test/node_modules/mongoose/lib/utils.js:429
        throw err;
        ^
MongoError: E11000 duplicate key error collection: strapi-test.article index: title_1 dup key: { : null }
    at /home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/pool.js:598:61
    at authenticateStragglers (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/pool.js:516:16)
    at Connection.messageHandler (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/pool.js:552:5)
    at emitMessageHandler (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
^C
ubuntu@ubuntu-xenial:~/strapi-test$ strapi start

/home/ubuntu/strapi-test/node_modules/mongoose/lib/utils.js:429
        throw err;
        ^
MongoError: E11000 duplicate key error collection: strapi-test.article index: title_1 dup key: { : null }
    at /home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/pool.js:598:61
    at authenticateStragglers (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/pool.js:516:16)
    at Connection.messageHandler (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/pool.js:552:5)
    at emitMessageHandler (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/home/ubuntu/strapi-test/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**What is the expected behavior?**
Strapi to rename things properly w/o the server breaking in the process.

**Suggested solutions**
Remove the models from `/api` and recreate from GUI.

---

- [x ] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
At the moment, Strapi does not delete database tables (or whatever they are called in mongo) and will not rename columns within a table. This has been discussed with the strapi team here: https://github.com/strapi/strapi/issues/1114 (This also includes discussion about mongo as well as mysql)

You will need to drop the table before you start, the error your getting is your trying to recreate an existing index hence the error. But just as a heads up, For now the model names should be lowercase or camel case when you create them. I've noticed odd errors when you attempt to use proper case.

**Comment by decimoseptimo** [comment]
As I said
> Instead of creating an article attribute `title` I called it `Title`
>The article title was created as `unique` & `required`

It seems that when I renamed the attribute in the GUI, strapi didn't remove the conflicting index before trying to rename.

I fixed it with:
```
db.article.dropIndex({Title: 1})
db.article.update({}, {$rename:{"Title":"title"}}, false, true);```

**Comment by decimoseptimo** [comment]
@lauriejim Hi, could you confirm this as a bug?

**Comment by lauriejim** [comment]
It looks a bug yes. Will not have any time to work on this issue. Feel free to investigate on why this issue happen and submit a PR to fix it. Will appreciate your contribution on Strapi!

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by lauriejim** [comment]
It's the same issue as https://github.com/strapi/strapi/issues/1210

**Comment by MartinMuzatko** [comment]
erm. @lauriejim you pointed to the same issue as a duplicate?

**Comment by PeterKey** [comment]
@lauriejim I noticed this bug just now on alpha 14.5. This issue is no duplicate and should be reopened.

**Comment by derrickmehaffy** [comment]
@PeterKey this is a duplicate of: https://github.com/strapi/strapi/issues/1114

It is not currently a "bug" it was intended the way it is, and leaving room for future improvement, see the linked issue from above.

**Comment by PeterKey** [comment]
@derrickmehaffy But why is there even a possibility on the admin page to rename content-types if it just breaks any further functionality?

**Comment by baranelitez** [comment]
this still is an issue and needs to be addressed. At least remove the renaming function if it's going to break the app?

**Comment by JessicaThi** [comment]
> @decimoseptimo It looks a bug yes. Will not have any time to work on this issue. Feel free to investigate on why this issue happen and submit a PR to fix it. Will appreciate your contribution on Strapi!
> 
> Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

The link is broken

**Comment by lauriejim** [comment]
Here is the file - https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
