### ISSUE TITLE
More InjectionZones in the Admin UI

### ISSUE THREAD

**Issue by torchsmith** [strapi/strapi#12100]
## Feature request

More InjectionZones in the Admin UI

### Summary

Would you guys accept a PR that adds more InjectionZones or overrides throughout the admin UI giving plugins more customization with the admin UI?

### Why is it needed?

Would be especially nice to modify or even just add to the following:
- The sidebar more besides just adding menu items.
- The dashboard

### Suggested solution(s)

Add some InjectionZones to a few different areas on the sidebar, and on the dashboard.

Possibly add some new config options to enable changing some wordings like "Strapi Dashboard - Workplace" to "Clients Brand".

**Comment by derrickmehaffy** [comment]
@torchsmith for feature PRs we require users go through our [RFC](https://github.com/strapi/rfcs) process first before we accept feature processes just to make sure things fit our guidelines before we want people to throw a ton of effort at something that gets rejected.

**Comment by torchsmith** [comment]
Thanks @derrickmehaffy , will go ahead through that route as soon as I can!

**Comment by torchsmith** [comment]
Just submitted a PR to the rfcs repo :)

https://github.com/strapi/rfcs/pull/37

**Comment by derrickmehaffy** [comment]
Related RFC: https://github.com/strapi/rfcs/pull/44

**Comment by am2222** [comment]
I think in the main admin page we can also add injection sections. Like what wordpress has. That first page is not very useful right now

**Comment by torchsmith** [comment]
@derrickmehaffy @WalkingPizza the rfcs I created:
https://github.com/strapi/rfcs/pull/37
was already approved to add injection zones.

Here is a quote from strapi team:

> You can start doing some new PRs, please also know that we are working on some features already to bring more customizable capabilities within the admin panel (like logo customization, primary color etc.) - there could be plausible conflicts.

Perhaps @WalkingPizza you could start working on a PR based on my rfcs? I think there is a lot of overlap.

**Comment by torchsmith** [comment]
Sweet! That would be greatly appreciated by many.

**Comment by andresfiloso** [comment]
Using [patch-package](https://www.npmjs.com/package/patch-package) you can create a custom injection zone on available content-manager sections (editView, listView)

`    <InjectionZone area="contentManager.editView.customZone" />`

add it to InjectionZones

```typescript
//  node_modules/@strapi/admin/admin/src/injectionZones.js
  ...
  contentManager: {
     editView: { informations: [], 'right-links': [], customZone: [] },
     listView: { actions: [], deleteModalAdditionalInfos: [] },
  },
  ...
```

And inject your components the same way you use InjectionZones

```typescript
  bootstrap(app) {
    app.injectContentManagerComponent('editView', 'customZone', { name: 'my-compo', Component: CustomComponent  })
  }
```

**Comment by torchsmith** [comment]
I love how this hasn't gone anywhere in over a year and the only way to get around this is to patch the file. Shame.

**Comment by justinyjsong** [comment]
Is it possible to add an injection zone next to delete button for listview?

**Comment by justinyjsong** [comment]
> Using [patch-package](https://www.npmjs.com/package/patch-package) you can create a custom injection zone on available content-manager sections (editView, listView)
> 
> ` <InjectionZone area="contentManager.editView.customZone" />`
> 
> add it to InjectionZones
> 
> ```ts
> //  node_modules/@strapi/admin/admin/src/injectionZones.js
>   ...
>   contentManager: {
>      editView: { informations: [], 'right-links': [], customZone: [] },
>      listView: { actions: [], deleteModalAdditionalInfos: [] },
>   },
>   ...
> ```
> 
> And inject your components the same way you use InjectionZones
> 
> ```ts
>   bootstrap(app) {
>     app.injectContentManagerComponent('editView', 'customZone', { name: 'my-compo', Component: CustomComponent  })
>   }
> ```

This work is not simple if the change you want to make involves @strapi/helper-plugin which is webpack js....

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/developer-experience/p/more-injectionzones-in-the-admin-ui
