### ISSUE TITLE
GraphQL mutations fail to populate relation fields

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12114]
### Describe the bug

GraphQL mutations fail to populate relation fields.

### Steps to reproduce the behavior

1. Create a collection type _x_ that has a relation with another element
1.1 In my case, the type is related to another collection type and to a user from the user-permissions plugin
2. Create a new element of type _x_ through a GraphQL mutation and try to populate one of the related fields by passing the relevant ID
3. Notice how the mutation succeeds but the relations are not populated. 

### Expected behavior

Relations should be populate-able through GraphQL mutations.

### System

- Node.js version: 14
- NPM version: 6.14.15
- Strapi version: 4.0.2
- Database: PostgreSQL
- Operating system: Alpine

**Comment by WalkingPizza** [comment]
Seems to be working on 4.0.3, closing this.

**Comment by WalkingPizza** [comment]
Although I can now populate relations with custom content types, I am still not able to set a relation with a `user-permissions` user through GraphQL.
How do I approach this?

**Comment by M1CK431** [comment]
related to #11957 ?

**Comment by derrickmehaffy** [comment]
Yes @M1CK431 duplicate (thank you!)
