### ISSUE TITLE
cannot install strapi-provider-upload-cloudinary@3.6.8 (latest) with node.js V16

### ISSUE THREAD

**Issue by safwendr** [strapi/strapi#12122]
I can't install  strapi-provider-upload-cloudinary@3.6.8 which is the latest for now to a strapi v4 project, it produce an error: 
`strapi-provider-upload-cloudinary@3.6.8: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.13.0"`
it works on older Node.js versions V14 but downgrading Node.js version cause issues to install pg and pg-connection-string with yarn, because installing it with npm can cause error as you mention in strapi blog [here](https://strapi.io/blog/deploying-a-strapi-api-on-heroku):  
![image](https://user-images.githubusercontent.com/44815799/148398651-98062784-dca5-4572-aa7a-796a7b4af676.png)

**Comment by kasonde** [comment]
Hello @safwendr the plugin you're trying to install is only supported by v3.6.8. If you would like to use the v4 version, install it by specifying the new `@strapi` scope v4 uses for its package names. [Here's the documentation.](https://github.com/strapi/strapi/tree/master/packages/providers/upload-cloudinary)
