### ISSUE TITLE
admin/project-type endpoint does not pick up hostname while using "strapi start"

### ISSUE THREAD

**Issue by rahuljaisinghani** [strapi/strapi#12125]
## Bug report and description
When I  start strapi server with the command **"strapi start"** and access the admin dashboard with https://<domain>/admin/auth/login, endpoints admin/project-type and admin/init are resolved using localhost:1337 instead of my domain
<img width="1352" alt="Screenshot 2022-01-06 at 8 27 02 PM" src="https://user-images.githubusercontent.com/25593096/148413530-65fa9c09-405e-4825-9f22-26cbcb96e881.png">
<img width="1440" alt="Screenshot 2022-01-06 at 9 39 13 PM" src="https://user-images.githubusercontent.com/25593096/148413783-f2b1fa2c-5833-4d7f-9dcf-b886963a0107.png">

This works file when I start strapi server using **"strapi build"** i.e above endpoints get resolved through my domain

<img width="1356" alt="Screenshot 2022-01-06 at 8 34 26 PM" src="https://user-images.githubusercontent.com/25593096/148424780-6ec29222-ac63-4524-b4e4-65bdf3119055.png">

I have set up strapi using docker. version is 4.0.2 (node v14.16.0).
Environment 
 

### System

- Node.js version: v14.16.0
- NPM version: 6.14.11
- Strapi version: 4.0.2
- Database: postgres
- Operating system:  [official strapi/base image](https://hub.docker.com/r/strapi/base)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by toddpratt** [comment]
I'm seeing this issue too. Even though I have the URL set in config/server.js, just two calls try to access 

GET | http://localhost:1337/admin/project-type

I suspect there is a hard-coded localhost somewhere.

**Comment by derrickmehaffy** [comment]
> I'm seeing this issue too. Even though I have the URL set in config/server.js, just two calls try to access
> 
> GET | http://localhost:1337/admin/project-type
> 
> I suspect there is a hard-coded localhost somewhere.

did you rebuild the admin panel?

**Comment by ederfmatos** [comment]
> I'm seeing this issue too. Even though I have the URL set in config/server.js, just two calls try to access
> 
> GET | http://localhost:1337/admin/project-type
> 
> I suspect there is a hard-coded localhost somewhere.

Searching i found one reference in packages "@strapi/admin/webpack.config.js" and "@strapi/admin/scripts/build.js"

**Comment by toddpratt** [comment]
I hadn't done a rebuild.  Unfortunately, my build was OOM killed.  I'm on a 1GB RAM machine but that's a different issue.  I know there's probably nothing that can be done about it.  I'll have to build it locally and deploy it to my VPS I guess.

**Comment by nextlevelshit** [comment]
Built your project and have a look into `.cache/admin/src/core/utils/axiosInstance.js`:

```javascript
instance.interceptors.request.use(
  async config => {
    config.headers = {
      Authorization: `Bearer ${auth.getToken()}`,
      Accept: 'application/json',
      'Content-Type': 'application/json',
    };

    return config;
  },
  error => {
    Promise.reject(error);
  }
);
```

Pass `STRAPI_ADMIN_BACKEND_URL` as environment variable while building, starting or whatever:

```bash
$ STRAPI_ADMIN_BACKEND_URL=https://my-domain strapi build
```
