### ISSUE TITLE
Default role not working on user create

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1212]
**Informations**
- **Node.js version**:v10.1.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:Mongo
- **Operating system**:Linux

**What is the current behavior?**
Default role not working.

**Steps to reproduce the problem**
* create new role.
* Set that as a default role.
* Create new user and not set role for that.
* Default role not set for that after save.

**What is the expected behavior?**
We need default role set for role field when user not set.

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @mnlbox !

I'm not able to reproduce your issue. Can you please retry your steps with a fresh new app and database with Strapi `3.0.0-alpha.12.2` version.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by mnlbox** [comment]
@lauriejim I checked and it's still not working on 12.3.
For reproduce I can refer you again to **Steps to reproduce the problem** section in above post. :thinking:

**Comment by lauriejim** [comment]
Can you try with the last version of Strapi (alpha.12.3) and with fresh new app and new database.

**Comment by lauriejim** [comment]
Okay, actually the default role is only apply on the register function.
We have to set it on create function too.
