### ISSUE TITLE
Allow component nesting in admin UI

### ISSUE THREAD

**Issue by tilman** [strapi/strapi#12126]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Allow component nesting in admin UI. Currently it is limited to two nestings.

### Why is it needed?

Many Frontend Developers follow the Atomic Design Principle of Isolating/Grouping Components into the following hierarchie:
`Atoms < Molecules < Organisms < Templates < Pages`. Therefore many Design Systems already using this Idea and it would be great to create the Components in Strapi the same way. 

### Suggested solution(s)

As far as I noticed this is already fully supported by Strapi. The only reason I found in some forums was that it has been disabled in the UI because of performance reasons. It would be great to have a config Option which would allow the nesting of components. I have commented out the filter of nested components in the SelectComponent of the content-type-builder admin UI and it seems to work pretty well. See the following diff for my temporary solution:

```diff
diff --git a/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js b/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js
index 0c692d8..5d96d05 100644
--- a/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js
+++ b/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js
@@ -47,11 +47,11 @@ const SelectComponent = ({
     return [...acc, ...compos];
   }, []);
 
-  if (isAddingAComponentToAnotherComponent) {
-    options = options.filter(option => {
-      return !componentsThatHaveOtherComponentInTheirAttributes.includes(option.uid);
-    });
-  }
+  // if (isAddingAComponentToAnotherComponent) {
+  //   options = options.filter(option => {
+  //     return !componentsThatHaveOtherComponentInTheirAttributes.includes(option.uid);
+  //   });
+  // }
 
   if (isTargetAComponent) {
     options = options.filter(option => {
```

**Comment by tilman** [comment]
For everyone who wants to get rid of the check in the admin UI you can use the following patch. This solution also works in you CI thanks to patch-package.

1.) yarn add -D patch-package postinstall-postinstall
2.) add this to your package.json
```json
{
    ...
    "scripts":{
        ...
        "postinstall": "patch-package"
        ...
    }
    ...
}
```
3.) create a folder called `patches` at the same level as your package.json
4.) create a file called `@strapi+plugin-content-type-builder+4.0.2.patch` in the `patches` folder with the following content:
```diff
diff --git a/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js b/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js
index 0c692d8..5d96d05 100644
--- a/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js
+++ b/node_modules/@strapi/plugin-content-type-builder/admin/src/components/SelectComponent/index.js
@@ -47,11 +47,11 @@ const SelectComponent = ({
     return [...acc, ...compos];
   }, []);
 
-  if (isAddingAComponentToAnotherComponent) {
-    options = options.filter(option => {
-      return !componentsThatHaveOtherComponentInTheirAttributes.includes(option.uid);
-    });
-  }
+  // if (isAddingAComponentToAnotherComponent) {
+  //   options = options.filter(option => {
+  //     return !componentsThatHaveOtherComponentInTheirAttributes.includes(option.uid);
+  //   });
+  // }
 
   if (isTargetAComponent) {
     options = options.filter(option => {

```
5.) Execture `yarn install` or `npm install`. If you see `Applying patches...` then the setup was successfull.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11319

**Comment by isaozler** [comment]
@tilman this issue was a showstopper... thanks for the patch 👍
