### ISSUE TITLE
CORS error strapi v4. How to override the origin variable?

### ISSUE THREAD

**Issue by Dennise89** [strapi/strapi#12139]
## Bug report
Access to XMLHttpRequest at 'http://localhost:1337/api/categories' from origin 'http://localhost:8080' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

### Describe the bug

I have a fresh installation of strapi and a fresh installation of vue.js. I created a content-type `categories` and set it to public so I can access it.
Now when I try to access the API with my vue app, I get the above error message.

Where and how can I change the origin to `http://localhost`?

### Steps to reproduce the behavior
See above

### Expected behavior

Get the response from the API.

### System

- Node.js version: v14.15.1
- NPM version: 7.0.15
- Strapi version: 4
- Database: sqlite (--quickstart param)
- Operating system: iOS

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Chanondler** [comment]
@Dennise89 have you solved this issue?

**Comment by Dennise89** [comment]
> @Dennise89 have you solved this issue?

@Chanondler Yes I have. Take a look at [this](https://stackoverflow.com/questions/70639958/strapi-v4-throwing-cors-exception)
