### ISSUE TITLE
JavaScript heap out of memory compiling the admin panel

### ISSUE THREAD

**Issue by Noxdor** [strapi/strapi#12137]
### Describe the bug

After a new installation of a strapi app with `npx create-strapi-app@latest <name>` and setting up the connection to a running postgres db, I try to compile the admin panel and it fails. I am running strapi behind an nginx proxy, it seems to work fine because when the app is running, I get a response from `/api`.

Though, running `npm run build` to compile the admin panel, the build process stops every time at exactly 92%. The Webpack step is `asset processing`. After a moment it crashes with the following error messages:

```
<--- Last few GCs --->

[3316:0x64ff000]   108620 ms: Mark-sweep 474.6 (497.2) -> 470.8 (497.5) MB, 1275.2 / 0.0 ms  (average mu = 0.164, current mu = 0.062) allocation failure scavenge might not succeed
[3316:0x64ff000]   109948 ms: Mark-sweep 474.8 (497.5) -> 471.0 (497.7) MB, 1267.5 / 0.1 ms  (average mu = 0.109, current mu = 0.046) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0xb00d90 node::Abort() [node]
2: 0xa1823b node::FatalError(char const*, char const*) [node]
3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
5: 0xea6105  [node]
6: 0xea6be6  [node]
7: 0xeb4b1e  [node]
8: 0xeb5560 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
9: 0xeb84de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe7990a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11f2f06 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15e7819  [node]
Aborted
```

Researching, I found that this might be caused by node running out of memory. So I run `npm run build --max_old_space_size=12000` which seems to increase the available heap size. Unfortunately it keeps crashing at the same point.

I tried a complete new install, same issue.

I am happy to provide any further information!

### Steps to reproduce the behavior

1. Create a new project by running `npx create-strapi-app@latest cms` (in my case I run this on a Debian 10 system in `/var/www/`
2. Enter the directory and set up a few things in `config` following strapi`s guides about setting up nginx with ssl and a domain.
3. Run `npm run build` in the root directory and see it fail at 92%

### Expected behavior

Strapi admin panel compiles successfully.

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.3
- Database: postgres
- Operating system: Debian 10

### Additional context

I am running this on a Debian 10 System in the Cloud via Linode. SSL and Nginx are configured correctly, I can reach the server just fine. Any it can't cause the compilation to crash, even if it wasn't.

**Comment by soupette** [comment]
Can you try building the admin with the `--no-optimization` flag? It will remove the compression step of the build so it uses less memory.

**Comment by kingdun3284** [comment]
Same here, used to be able to build on cloud few days ago. I didn't change any of my environment and tried to build with the same commit that was success before and faced this issue.

**Comment by kingdun3284** [comment]
Should be related to this issue: https://github.com/aws/aws-cdk/issues/18322 , the dependency of color.js had some problem

**Comment by Noxdor** [comment]
@soupette Thank you for your suggestion! Unfortunately running `npm run build --no-optimization` is not fixing the problem. It still gets stuck at 92%.

**Comment by Noxdor** [comment]
@kingdun3284 Shit I read the article linked, can't believe someone would willingly introduce such a bug. Thinking to be a partisan for the free software movement instead hurting it. Hope the Strapi guys will freeze their used version of colors soon to the last usable state.

**Comment by derrickmehaffy** [comment]
How much memory do you have?

**Comment by derrickmehaffy** [comment]
> @kingdun3284 Shit I read the article linked, can't believe someone would willingly introduce such a bug. Thinking to be a partisan for the free software movement instead hurting it. Hope the Strapi guys will freeze their used version of colors soon to the last usable state.

We already have in v4.0.4

**Comment by Noxdor** [comment]
Running this in the cloud, I am having 1GB RAM available.

I just ran it on version v4.0.4, unfortunately that didn't solve the issue.

**Comment by Noxdor** [comment]
Well, it seem I was a little to optimistic compiling this on my little cloud vm! I just ran it on my local machine with 16GB RAM and it compiled just fine. I will close this issue now and hope no one ever finds it 😜

**Comment by hmanov** [comment]
Use yarn build --no-optimization, it works on 1gb ram

**Comment by brianwachira** [comment]
> Use yarn build --no-optimization, it works on 1gb ram

Also worked for me

**Comment by duxcodes** [comment]
> Use yarn build --no-optimization, it works on 1gb ram

This worked for but not with "npm". I had to install yarn and then run `yarn build --no-optimization`.

**Comment by ayalor** [comment]
> Use yarn build --no-optimization, it works on 1gb ram

worked for me, ty a lot

**Comment by jbebe** [comment]
> This worked for but not with "npm"

Because npm uses '--' to pass parameters. So it's going to be `npm run build -- --no-optimization`

**Comment by scottydev** [comment]
> > This worked for but not with "npm"
> 
> Because npm uses '--' to pass parameters to the script. So it's going to be `npm run build -- --no-optimization`

That did it! Forgot about that, thanks for the post.

With Strapi v4.4.3 on Ubuntu v22, 1gb ram + 1gb swap file didn't do it, that's with both the NPM and Yarn installs. It took 2gb ram + 1gb swap to finally get it to build reliably without optimizations.

DatePicker.js seems to be the culprit in my case. Looking forward to that Strapi update which should make this less of an issue in the future.

**Comment by Null78** [comment]
Just stop using webpack for god's sake

**Comment by derrickmehaffy** [comment]
> Just stop using webpack for god's sake

Already in our plan for Strapi v5, we will be switching to Vite instead

**Comment by mortrap** [comment]
Thanks for your answers, guys

**Comment by harshil919** [comment]
hey guys i am getting error on running yarn build --no-optimization and npm run build -- --no-optimization.
```

> blogs@0.1.0 build
> strapi build --no-optimization
error: unknown option '--no-optimization'
``` 

 what do I need to change in thepackage.json? 
my package.json file looks like this:
```
{
  "name": "blogs",
  "version": "0.1.0",
  "private": true,
  "description": "A Strapi application",
  "scripts": {
    "build": "strapi build",
    "deploy": "strapi deploy",
    "develop": "strapi develop",
    "start": "strapi start",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-cloud": "5.8.0",
    "@strapi/plugin-users-permissions": "5.8.0",
    "@strapi/strapi": "5.8.0",
    "better-sqlite3": "11.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  },
  "engines": {
    "node": ">=18.0.0 <=22.x.x",
    "npm": ">=6.0.0"
  },
  "strapi": {
    "uuid": "some numbers here"
  }
}
```

**Comment by lfilipe09** [comment]
> npm run build -- --no-optimization

Seems to be deprecated! https://docs.strapi.io/dev-docs/cli
As I could read you need to use `run build -- --minify`

**Comment by hielsnoppe** [comment]
Unfortunately, I can confirm that also version `5.9.0` fails to build on a machine with 1.5 GB memory.

**Comment by stevewlrls** [comment]
To anyone else who hits this problem, the solution for me was to increase the NodeJS heap size. I my Dockerfile, I added the following just before the 'npm run build':
ENV NODE_OPTIONS=--max_old_space_size=4096

For other build environments just find a way to export NODE_OPTIONS as above.

I don't know why my Strapi Admin UI would build happily in a MacOS terminal but fail in Docker. Perhaps the docker images were built with a constrained heap size.

**Comment by harshil919** [comment]
I made changes to my package.json file itself, modified the build script because --no-optimization flag is deprecated and didn't knew about --minify and it worked!!! though took a long long time(solid 1006608 ms or 16 mins) to build the admin panel.

![Image](https://github.com/user-attachments/assets/c8395b88-2314-40a1-ae00-2e740db7caa4)

**Comment by derrickmehaffy** [comment]
> Unfortunately, I can confirm that also version `5.9.0` fails to `npm run build -- --minify` on a machine with 1.5 GB memory.

Our documentation clearly says 2gb minimum, 4gb recommend

**Comment by stevewlrls** [comment]
> Our documentation clearly says 2gb minimum, 4gb recommend

My build was failing on a Docker VM that had up to 12Gb RAM. And my exploration showed that the relevant limit was the NodeJS heap size - hence the fix above. The default heap size on the Docker images I was using was set at 2Gb. Perhaps you could clarify the guidance to explain that a *heap size* of 4Gb (not virtual RAM size) is recommended.

:)

**Comment by derrickmehaffy** [comment]
> > Our documentation clearly says 2gb minimum, 4gb recommend
> 
> My build was failing on a Docker VM that had up to 12Gb RAM. And my exploration showed that the relevant limit was the NodeJS heap size - hence the fix above. The default heap size on the Docker images I was using was set at 2Gb. Perhaps you could clarify the guidance to explain that a *heap size* of 4Gb (not virtual RAM size) is recommended.
> 
> :)

I wasn't responding to you but the user who mentioned they were using 1.5gb of RAM.

Node's default is slightly under 4gb heap, if whatever base container you are using changes that default that's beyond us to document. (Unless the available memory on the system is below that)

(That default was changed in Node 14)

We expect environments to use the Node defaults unless otherwise documented.

**Comment by tshmieldev** [comment]
Just happened to me
Node 20
Strapi 5
Ubuntu
2GB ram (idle ussage 200mb)
4GB Swap

Can't even build

I can't believe this is not intentional to make you buy the strapi cloud, how is this still a problem?

**Comment by muesli-dev** [comment]
the issue still exists in 2025.

**Comment by deketh** [comment]
Well the minimum 2gb system requirement is not a system requirement it is a requirement just for strapi process it takes 2gb of ram just to build the admin panel, i have a 4gb server and obviously it is not exclusive for strapi also the database etc.

Even though the minimum system requirements are documented build performance for the Admin Panel should be reviewed, I would prefer a slower build (do we really need to load 2gb of data to the ram at the same time to build admin panel?) that at least finishes rather than the process hanging infinitely or worse the server!

**Comment by kevinvugts** [comment]
I can confirm that this issue started to appear for us in the last month. Not sure where it comes from or what has changed internally. For those who have this issue it might be worth to (as a work around) increase your maximum heap size by setting 

`NODE_OPTIONS="--max-old-space-size=6144"` (or any other amount of MB/GB)

**Comment by pezexd** [comment]
Any news about this issue? I can't build my admin panel trough my digital ocean droplet, I used NODE_OPTIONS='--max-old-space-size=8192' and not success, I get Killed status.

**Comment by tshmieldev** [comment]
@pezexd make sure the limit does not surpass your RAM + swap space. Try to build with a smaller limit

**Comment by pezexd** [comment]
Solved for me, I needed move to an droplet from 8gb ram for build be successful, so the problem is about the RAM, at the same way, I get an time of 3min~ to get full build. (also I'm still using the flag `NODE_OPTIONS='--max-old-space-size=8192'`)

**Comment by luissimosa199** [comment]
I'm having the same issue but I'm using Strapi Cloud, I'm assuming that it's due to the Free Tier, but I have not found any reference to RAM in the Tier Descriptions, can someone confirm if upgrading to a paid Tier increases the available memory?

**Comment by sofianegargouri** [comment]
Getting the same issue as well, while upgrading from 5.33.3 to 5.33.4.
I have the issue on GitHub Actions and an on MacBook M3 Pro with 18 GB of memory in a devcontainer.

```
vscode ➜ /workspaces/strapi (dependabot/bun/strapi/minor-and-patch-ff8852181e) $ bun strapi build
[WARN] Declared version of react (19.2.4) is not compatible with the version required by Strapi (^18.0.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of react (19.2.4) is not compatible with the version required by Strapi (^18.0.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of react-dom (19.2.4) is not compatible with the version required by Strapi (^18.0.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of react-dom (19.2.4) is not compatible with the version required by Strapi (^18.0.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of react-router-dom (7.13.0) is not compatible with the version required by Strapi (^6.0.0).
You may experience issues, we recommend you change this.
[WARN] Declared version of react-router-dom (7.13.0) is not compatible with the version required by Strapi (^6.0.0).
You may experience issues, we recommend you change this.
✔ Compiling TS (1418ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
    - STRAPI_AI_URL
    - STRAPI_ANALYTICS_URL
✔ Building build context (96ms)
⠋ Building admin panel
⠙ Building admin panelBrowserslist: browsers data (caniuse-lite) is 6 months old. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

<--- Last few GCs --->

[5305:0x186d6870]    25062 ms: Mark-Compact 1981.0 (2087.7) -> 1970.4 (2093.0) MB, 465.77 / 0.00 ms  (average mu = 0.616, current mu = 0.053) allocation failure; scavenge might not succeed
[5305:0x186d6870]    25772 ms: Mark-Compact 1986.5 (2095.4) -> 1974.5 (2096.7) MB, 669.34 / 0.00 ms  (average mu = 0.388, current mu = 0.057) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb71e90 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0xeaabdc v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0xeaadac v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x10b2adc  [node]
 5: 0x10c8fb4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 6: 0x10a1d1c v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 7: 0x10a2ae0 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0x1081b00 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
 9: 0x1072db8 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
10: 0x1072f5c v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
11: 0x135c22c v8::internal::Handle<v8::internal::NumberDictionary> v8::internal::HashTable<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::New<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType, v8::internal::MinimumCapacity) [node]
12: 0x135c494 v8::internal::Handle<v8::internal::NumberDictionary> v8::internal::HashTable<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::EnsureCapacity<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NumberDictionary>, int, v8::internal::AllocationType) [node]
13: 0x135d140 v8::internal::Handle<v8::internal::NumberDictionary> v8::internal::Dictionary<v8::internal::NumberDictionary, v8::internal::NumberDictionaryShape>::Add<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::NumberDictionary>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, v8::internal::InternalIndex*) [node]
14: 0x122d138  [node]
15: 0x12c7a20 v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [node]
16: 0x1346798 v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin, v8::internal::EnforceDefineSemantics) [node]
17: 0x149d2b0 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [node]
18: 0x149ec44 v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [node]
19: 0x1894a84  [node]
```

**Comment by deketh** [comment]
this issue should be reopened, compilling the admin panel should not consume 2GB of RAM.

**Comment by deketh** [comment]
> Solved for me, I needed move to an droplet from 8gb ram for build be successful, so the problem is about the RAM, at the same way, I get an time of 3min~ to get full build. (also I'm still using the flag `NODE_OPTIONS='--max-old-space-size=8192'`)

It's ok but I would not say that is a viable solution for everyone the whole thing on Strapi is for it being minimal, even for Strapi Cloud @luissimosa199 encounters the issue...

**Comment by arpan-lol** [comment]
I plotted the memory usage during a build, polling system memory every 0.2 seconds

<img width="1169" height="624" alt="Image" src="https://github.com/user-attachments/assets/2ac0e676-4632-4971-87d4-c04532aa4dff" />

still facing the same issue described here. memory usage steadily ramps throughout the build process, eventually consuming nearly all available RAM and heavily relying on swap

i understand the documented minimum system requirements, but I think Admin Panel build performance should still be reviewed. would 100% prefer a slower build that eventually completes over one that aggressively consumes memory to the point where the process hangs indefinitely

as suggested by some people above, i ran it with NODE_OPTIONS="--max-old-space-size=2048" set to 2 gigs. the build did eventually complete. but again, it feels less economical to always have atleast that amount of ram free whenever i wanna run a build. and i may have to wind a couple apps down for that.

Environment:

* Strapi v5.46.1
* Node v20.20.2
* VM specs: 2 GB RAM + 2 GB swap

thanks!

**Comment by edapm** [comment]
Had this issue after upgrading to v5.5.1, with Node v24.19.0, built fine on Mac but failed on the production server.
