### ISSUE TITLE
Strapi is setting a varchar limit of 255 in text fields.

### ISSUE THREAD

**Issue by ZeldOcarina** [strapi/strapi#12130]
## Bug report
Strapi is setting a varchar limit of 255 in text fields.

### Describe the bug
I am getting a random 500 error, so I don't think this was an expected behaviour. I am on Strapi 4.0.3 and using postgresql as a database.

### Steps to reproduce the behavior

1. Add a component
2. Try to include a short text field in the component
3. Go to the content manager section and try to add more than 255 characters in the text field.
4. See error:

update "components_testimonials_home_testimonials" set "id" = $1, "name" = $2, "quote" = $3, "summary" = $4, "cta" = $5, "cta_link" = $6 where ("id" = $7) - value too long for type character varying(255)
error: update "components_testimonials_home_testimonials" set "id" = $1, "name" = $2, "quote" = $3, "summary" = $4, "cta" = $5, "cta_link" = $6 where ("id" = $7) - value too long for type character varying(255)
    at Parser.parseErrorMessage (/home/Mattia/apps/strapi-viva/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/Mattia/apps/strapi-viva/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/Mattia/apps/strapi-viva/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/Mattia/apps/strapi-viva/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

### Expected behavior
If there's no limit set by the user there shouldn't be a set limit to the field or the limit should be much higher.

### Screenshots
![image](https://user-images.githubusercontent.com/42982095/148563586-60042835-0bfb-4cd8-9cd8-fb60012428a6.png)

### System

- Node.js version: 14.16.0
- NPM version: 8:3.0
- Strapi version: 4.0.3
- Database: postgresql
- Operating system: ubuntu 20.04 (This strapi instance is deployed)

**Comment by derrickmehaffy** [comment]
@alexandrebodin this is one of those where it's a question of should we just document the unstable column API on the schema?

**Comment by ZeldOcarina** [comment]
@derrickmehaffy if I could suggest, I would add a more clear error message to the user (as right now it's a general 500) and add the character limit in the short text description. I would do that myself with a PR but I'm really unsure on what to touch in such a big app.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy if I could suggest, I would add a more clear error message to the user (as right now it's a general 500) and add the character limit in the short text description. I would do that myself with a PR but I'm really unsure on what to touch in such a big app.

Keep in mind we have a short text vs longtext field and they use different types. The point of short text string is to be sort. When you select long text it uses the `text` option in most databases.

But yes the error should be more clear.

**Comment by calvinl** [comment]
Just came across this issue trying to extend the users and permissions plugin. I added an extra column to support refresh tokens. I think we should be able to set a string column's character limit, but it appears not to support that at the moment if I'm not mistaken.

**Comment by derrickmehaffy** [comment]
> Just came across this issue trying to extend the users and permissions plugin. I added an extra column to support refresh tokens. I think we should be able to set a string column's character limit, but it appears not to support that at the moment if I'm not mistaken. 

I believe I have found a workaround using some of our unstable and undocumented features in v4 (won't help on v3 I'm afraid).

But the possibility to modify the column type and arguments is possible. See this documentation PR: https://github.com/strapi/documentation/pull/786

**Comment by derrickmehaffy** [comment]
They are now directly in the documentation: https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#database-validations-and-settings

**Comment by derrickmehaffy** [comment]
I believe we have for now handled this issue pretty clearly which is using `string` vs `long text` as fields which use the `varChar(255)` vs `text` fields. Likewise there is a documented way to adjust the length if your DB supports longer than 255 for varChar

**Comment by reorx** [comment]
I think the limitation or the length of 255 is fine, the real problem is, both the frontend and API do not validate the user's input, making it shown the "Internal Server Error" warning eventually. This is quite confusing because users do not understand such notice. Generally, it's an uncovered case about user interaction.

**Comment by receter** [comment]
I had the issue that I used a Text field for a Url as it is recommended for urls:
![image](https://github.com/strapi/strapi/assets/2504695/9dee628f-7955-4dc9-9270-e4a1253ecf23)

There are URLs longer than 255 characters, it would be helpful to communicate this limitation at this point in the interface.

**Comment by jpettigrew-parkinsons-uk** [comment]
I'm seeing what seems to be the same issue when trying to add alt text to an image in the media library. The symptom is 500 errors when saving the updated media. 

At the very least, we should get an informative error message!
