### ISSUE TITLE
Duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#12138]
### Describe the bug
If documents are created specifying an ID. Future documents created without an ID get a 500 error with Duplicate key value violates unique constraint.

When 
### Steps to reproduce the behavior

1. In bootstrap create documents setting a specific id
2. Create a new document using API wihout a specific id
3. Get 500 error for Duplicate key value violates unique constraint

### Expected behavior

New id is unique and created successfully

### System

- Node.js version: v14
- NPM version:
- Strapi version: v4
- Database: Postgres
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
This isn't an issue with Strapi, if you are using Knex.js directly there is nothing we can do about this. You have to set the index start using Knex.

Not a strapi bug, but user environment and customization issue.
