### ISSUE TITLE
Unable to set jwt token expiration

### ISSUE THREAD

**Issue by realfrancisyan** [strapi/strapi#12144]
## Bug report
I am not able to set specific token expiration by following the guidelines described in [here](https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#jwt-configuration).

### Describe the bug
Creating a `security.json` config file simply doesn't take effect. I tried to change the expiration to '1d' and restarted the server but it didn't work. When I logged in to the backend again and got the token pasted at `jwt.io`, it said the expiration date was still one month later.

### Steps to reproduce the behavior

1. Create a `security.json` file under `extensions/users-permissions/config`
2. Set the expiration to '1d' in `expiresIn` field
3. Save and restart the server
4. Relogin with restful API
5. Copy the token and paste it at `jwt.io`
6. Check the `exp` field in `payload`

### Expected behavior

Expiration is set to a specific duration.

### Screenshots

<img width="1127" alt="WechatIMG163" src="https://user-images.githubusercontent.com/2163522/148715381-f8f019b7-ff9f-431a-bc97-88f12c2cf4fc.png">

### Code snippets

`extensions/users-permissions/config/security.json`

```json
{
  "jwt": {
    "expiresIn": "1d"
  }
}
```

### System

- Node.js version: v16.13.0
- NPM version: v8.1.0
- Strapi version: v4.0.3
- Database: sqlite
- Operating system: macOS v12.1

**Comment by derrickmehaffy** [comment]
@realfrancisyan see the linked PR which has updated instructions. I'm gonna set this issue as closed for now since it's documentation related and that PR should be merged soon.

**Comment by thecodemaker12** [comment]
You just have to make:

{
  "jwt": {
    "expiresIn": "30d"
  }
}

**Comment by vatsalboideas** [comment]
<img width="860" alt="Screenshot 2025-01-10 at 5 34 10 PM" src="https://github.com/user-attachments/assets/7ad112d3-c085-4024-83ac-22a6391595f3" />
 guys you need to add the expiry in the admin.js file under config as mentions in the image, this is working
