### ISSUE TITLE
Allow more than 2 levels depth

### ISSUE THREAD

**Issue by noam-zweig** [strapi/strapi#12140]
Hi,

I'm using lifecycle hooks (i.e. `afterUpdate`).
In the lifecycle hooks of `afterXXX` it also returns a result.
This result is populated from the DB, using the `getDeepPopulate` defined here - https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/content-manager/server/services/entity-manager.js#L43

In [L48](https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/content-manager/server/services/entity-manager.js#L48) you hard coded limited the depth to 2.

I have some use-cases that requires more than 2 levels for the validation and processing of the result.
Is it possible to allow controlling the depth? Or maybe increase this to 4?

Thanks,

**Comment by derrickmehaffy** [comment]
Next time please following the feature request template

**Comment by Kinbaum** [comment]
Duplicate #11319

**Comment by derrickmehaffy** [comment]
Closing as duplicate (thanks @Kinbaum I should have caught that)
