### ISSUE TITLE
Strapi affected by colors.js protest

### ISSUE THREAD

**Issue by EzraEn1** [strapi/strapi#12146]
### Describe the bug
~The final step of create-strapi-app does not finish due to an infinite zalgo stream of text intersected with the word "testing"~
The final step of create-strapi-app is running `yarn start` in your project directory. This is when the zalgo stream starts.

### Steps to reproduce the behavior

~1. Run `npx create-strapi-app`
2. Enter your project name.
3. Wait for dependencies to be installed.
4. See error.~

1. Run `yarn start` in your Strapi project.
2. See error.

### Expected behavior

My new ~starter~ Strapi project would be functional. (not exclusive to new projects)

### Screenshots

![image](https://user-images.githubusercontent.com/7076802/148730890-88060561-a5f2-4a23-bfa3-1302d2064f92.png)

### Code snippets

If applicable, add code samples to help explain your problem.
N/A

### System

- Node.js version: 16.10.0
- NPM version: 8.3.0
- Strapi version: ~N/A~ 4.0.3
- Database: N/A
- Operating system: Windows

### Additional context

N/A

**Comment by anildalar** [comment]
I am also getting this error today

**Comment by anildalar** [comment]
it is a serious bug.
When you run 
npm run develop this error shows

**Comment by EzraEn1** [comment]
Unfortunately this is not actually a bug per se, but an attack on the part of the colors.js maintainer. Please see [this news article](https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected) if you'd like more information about the situation. Unfortunately, all we can do right now is issue spot-patches where we can. Reverting back to the "non-liberty" version should fix things.

**Comment by EzraEn1** [comment]
We are most likely suffering from the attack via another package, so someone needs to sort out the dependency tree.

**Comment by EzraEn1** [comment]
Same report as #12142. Closing.
