### ISSUE TITLE
strapi is not able to install

### ISSUE THREAD

**Issue by AnjaliMahawar** [strapi/strapi#12148]
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by EzraEn1** [comment]
Please ensure that the issue template is filled out properly. Please also check that your issue is not a duplicate of #12142.

**Comment by EzraEn1** [comment]
Please close this issue @AnjaliMahawar.
Duplicate of #12142

**Comment by kasonde** [comment]
Duplicate of #12142
