### ISSUE TITLE
Terminal keep showing weird code after running yarn develop

### ISSUE THREAD

**Issue by kingDevGit** [strapi/strapi#12154]
### Describe the bug
The terminal keep showing weird code after running yarn develop

### Steps to reproduce the behavior

1. Install with cli ```yarn create strapi-app my-project```
2. yarn develop
3. See error

### Expected behavior

I expect Strapi ran smoothly

### Screenshots

<img width="742" alt="image" src="https://user-images.githubusercontent.com/3328498/148745263-b471b185-f715-41a3-959e-a5190e549953.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.16.1
- Yarn version: 1.22.10
- Strapi version: 4.0.3
- Database: 3.32.3 
- Operating system: macOSX  Big Sur 11.2.3

**Comment by RolfVeinoeSorensen** [comment]
I have the same problem.

**Comment by PaperjetStudios** [comment]
Yeah I'm getting the same thing here too. No matter what database (sqlite or postgres) or if I use yarn or npm.

**Comment by MartinEmilEshack** [comment]
same here

**Comment by sultanfendonus** [comment]
Same issues I am facing.

**Comment by mickuki321** [comment]
https://github.com/nomiclabs/hardhat/issues/2235

**Comment by moritzruth** [comment]
Workaround: `npm install colors@1.4.1`

**Comment by hoffmannjan-ziegler** [comment]
We've added 
```
  "resolutions": {
    "**/colors": "1.4.0"
  }
```
as said in [hardhat issue](nomiclabs/hardhat#2235) and everything works :)

**Comment by arpadgabor** [comment]
Confirmed. Adding `colors@1.4.1` and `resolutions` from the comment above in `package.json` fixed the issue.

**Comment by kingDevGit** [comment]
Thanks mate! I almost thought that Trinity was in my screen and telling me to follow the rabbit
