### ISSUE TITLE
GraphQL custom resolver fetches data beyond what the resolver returns

### ISSUE THREAD

**Issue by AlexPoirier1** [strapi/strapi#12159]
### Describe the bug

I followed the [Build a custom resolver guide](https://strapi.io/blog/building-custom-resolvers-with-strapi) and am trying to provide data for my custom resolver. Even though I only return mock data, when I test the query, the mock data appears to be merged with other data that I did not fetch. 
Why is the graphQL plugin automagically fetching data and how do I stop it from doing that?

### Steps to reproduce the behavior

1. Define a custom resolver for a graphQL query
2. Mock the return data with empty collections
3. Query (http://localhost:1337/graphql) those collection fields that are in your return type.
4. See that there is more data than what your custom resolver returns in the results.

### Expected behavior

I would expect my custom resolver to not fetch any more data than what I manually fetch.

### Screenshots

Here we can see that somehow, the plugin fetched the entirety of the navigations collection.

![image](https://user-images.githubusercontent.com/7539455/148782010-24415edf-9a24-44c8-89e6-8a206cbbd5f9.png)

### Code snippets

Here is the custom resolver's code:
```
resolver: {
        Query: {
            getNavigationByAlias: async (_, params) => {
                return [{
                    id: 'an_id',
                    createdAt: 'today',
                    updatedAt: 'today',
                    label: 'A Label',
                    alias: 'alias',
                    description: 'testttt',
                    navigation: {},
                    order: 2,
                    icon: 1,
                    pack_external_id: 'test',
                    sections: [],
                    navigations: [],
                    articles: [],
                }]
            }
 ```

### System

- Node.js version: 12.21.0
- NPM version: 7.13.0
- Strapi version: 3.6.8
- Database: mongoDB 4.2.10
- Operating system: MacOS BigSur 11.5.2

### Additional context

I have tried providing the `resolverOf` string like the guide indicate but I get the same results.
Strapi console logs this when executing the query: `The value of field: 'navigation', in your where filter, is undefined.`

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.6.8`

We aren't fixing v3 issues, unable to reproduce on v4

**Comment by AlexPoirier1** [comment]
That's a bummer.. Since you guys dropped mongoDB support for v4, I can't upgrade :( 

Thanks for the answer.

**Comment by derrickmehaffy** [comment]
We will be working on a migration guide for MongoDB users to transition them to a supported SQL database over the next few months.
