### ISSUE TITLE
Mask support for string field

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1215]
**What is the expected behavior?**
I think a mask box support can be useful for string fields. It can be as a optional setting in advanced setting of string field:
![strapi4](https://user-images.githubusercontent.com/25859075/40157453-5b6ffc04-59b4-11e8-8d44-38f75f254957.png)

For example we can set **Mobile** mask for mobile string field and then render mask text box on insert and edit form. For another example it can be used for **Web Url** mask,...
We can also support general and most popular mask by default like:
* Mobile Number
* Phone Number
* Email Address (We now have this as a separate filed type that I don't know why? Why not a simple string field? :thinking: )
* Web URL
* Zip Code
* Or any other custom mask.

Thanks.

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by soupette** [comment]
The email field is already implemented, about the other mask such feature can be developed by following the dynamic used for the WYSIWYG field.

**Comment by mnlbox** [comment]
@soupette  Any news or roadmap for this?

**Comment by soupette** [comment]
@mnlbox it's currently not on our ROADMAP, but you can still submit a PR for this feature request.

**Comment by Aurelsicoko** [comment]
IMO, this is another way to talk about validations. We're considering to implementing them (see https://portal.productboard.com/strapi/c/14-validations). I'm closing the issue but feel free to give me insights on Product Board or comment on this issue.

**Comment by hermesalvesbr** [comment]
Has this functionality been implemented? Where do I find the mask inside the strapi?
