### ISSUE TITLE
The admin stop working after update to `v4.0.4`

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12163]
### Describe the bug

I have a project with the `v4.0.3`. And after update to `v4.0.4`, it has stopped working:

<img width="1594" alt="Screenshot 2022-01-10 at 18 40 14" src="https://user-images.githubusercontent.com/1007051/148813795-f22c25f5-8e6c-4b6a-8034-0d508806c5d1.png">

In the terminal:

>GET /i18n/locales (23 ms) 404

Mention that I _**don't have**_ the i18n plugin.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4.0.4
- Database: SQLite
- Operating system: macOS

**Comment by petersg83** [comment]
Did you re-build the admin? If not, can you try please?

**Comment by abdonrd** [comment]
@petersg83 yeah, I already rebuilt it!

**Comment by soupette** [comment]
What does your `my-app/.cache/admin/src/plugins.js` file look like?

**Comment by abdonrd** [comment]
```
import contentTypeBuilder from '../../../node_modules/@strapi/plugin-content-type-builder/strapi-admin.js';
import email from '../../../node_modules/@strapi/plugin-email/strapi-admin.js';
import upload from '../../../node_modules/@strapi/plugin-upload/strapi-admin.js';
import usersPermissions from '../../../node_modules/@strapi/plugin-users-permissions/strapi-admin.js';


const plugins = {
  'content-type-builder': contentTypeBuilder,
  'email': email,
  'upload': upload,
  'users-permissions': usersPermissions,
};

export default plugins;
```

**Comment by abdonrd** [comment]
Let me try to manually delete the cache folder...

**Comment by soupette** [comment]
> Let me try to manually delete the cache folder...

And the build one...

**Comment by abdonrd** [comment]
Now with the `.cache` & `build` folders deleted...

I run `npm run develop`:

<img width="598" alt="Screenshot 2022-01-10 at 19 00 50" src="https://user-images.githubusercontent.com/1007051/148815689-79af2ad7-bd6d-42c0-993b-233b72438be7.png">

But! Now I NO have `cache` & `build` folders..!

**Comment by soupette** [comment]
> But! Now I NO have cache & build folders..!

Yes it is using the one from the @strapi/admin which has i18n included, can you try to rebuild with the fast command `strapi build --no-optimization` ?

**Comment by abdonrd** [comment]
And after `npm run build` now I have `.cache` and `build` folders again!

And run `npm run develop` and now it works 😮

**Comment by soupette** [comment]
Ok that a good news!

**Comment by abdonrd** [comment]
Yeah, now it's working... 😵‍💫

**Comment by soupette** [comment]
[This line](https://github.com/strapi/strapi/blob/d81919ac2272948b3f5d3b25a4cf8cc7b6994460/packages/core/admin/index.js#L333-L337) is problematic though in your case without i18n it should have triggered a build if the build folder was not there instead of serving the @strapi/admin one.

**Comment by petersg83** [comment]
Yes the difference should be done in both ways then

**Comment by tboulogne** [comment]
hello, 

Same here, some part of admin stop working. Revert to 4.0.2....

**Comment by soupette** [comment]
@tboulogne can you explain which part?

What issue are running into, can you open a new issue with detailed steps on how to reproduce?

**Comment by tboulogne** [comment]
@soupette the content type builder with a blank page.

I will try to open a new issue ASAP.
