### ISSUE TITLE
Enable/Disable (Block) field for Users

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1216]
**What is the expected behavior?**
I think an **enable** field for users can be very useful. Specially for **Admin - Permissions** in https://strapi.io/vote

Then I can enable or disable (block) specific user if we want. (by default all users enabled)

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello ! Feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

It's really not hard issue to do. But have to understand how existing login work. But not really hard I think.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
