### ISSUE TITLE
User from User Permission 403 to use CONTENT-MANAGER endpoint

### ISSUE THREAD

**Issue by J2A2B** [strapi/strapi#12166]
## Bug report

In the Admin Panel, End User from User Permission with right permission on endpoint, can't use it.

### Describe the bug

When I give permission to an End User from User Permission (Authenticated Role) to use an endpoint of the CONTENT-MANAGER, the user can't use it.
There is a 403 Forbidden response on the endpoint.

### Steps to reproduce the behavior

1. Go to 'Settings -> User & Permission Plugin -> Roles & Permission'
2. Open the  'CONTENT-MANAGER section'
3. Click to 'Create' method to allow the permissions and save
4. Test the endpoint with the good user and Token and see the 403 error

### Expected behavior

It Should allow the user to use the Endpoint to create a content in the Admin Panel.
Otherwise, the Admin Panel should not allow changing these permissions. 

### Screenshots

<img width="1439" alt="Capture d’écran 2022-01-10 à 17 37 07" src="https://user-images.githubusercontent.com/15554576/148835694-d0cd9f0e-2bf0-492e-958e-ec4ce25c3b46.png">

### System

- Node.js version: 
- NPM version: v12.16.1
- Strapi version: v3.6.8
- Database: MongoDB
- Operating system:

**Comment by derrickmehaffy** [comment]
We no longer support v3 unless it's a critical issue or security related: Strapi version: v3.6.8
