### ISSUE TITLE
[v4] Add policy to endpoint via the admin panel

### ISSUE THREAD

**Issue by 3akram** [strapi/strapi#12165]
### Please describe your feature request

- [ ] **Attach a policy to an endpoint to create/edit content for the current logged in user**

### Summary

Hello, i'm trying to add the currentUser logic to the API. Say i'm a regular user - authenticated via the API -. when i create a content it created successfully but not belong to the current user. Say i have articles have a relation many to one with the user. what i need to do is to create an article -without adding the currentUser id to the request payload - and this article created and belong to the user automatically without adding extra code in the core controller. i tried to add a policy and attach it via the admin panel - we used the same approach in strapi 3 - but i can't add the same behaviour in strapi 4. Is there a way to achieve it 

### Why is it needed?

To be able to allow the admins to create content for the users also to allow the users to create content for themselves directly through the API.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by 3akram** [comment]
Hi, 

thanks for your responding

the policy feature was in strapi v3 but not in strapi v4 so the feature request is to add it to v4 or mention in the documentation another way to achieve the same functionality

**Comment by derrickmehaffy** [comment]
> Hi,
> 
> thanks for your responding
> 
> the policy feature was in strapi v3 but not in strapi v4 so the feature request is to add it to v4 or mention in the documentation another way to achieve the same functionality

We removed it as it was not recommended and that logic has been completely deleted, as those policies had to be created on the file system it made no sense to assign them while in production. We won't re-add this as it would break our policy on a "single source of truth"

For policies that source of truth is the routes file, just like with route middlewares.

**Comment by 3akram** [comment]
Okay got it now thank you
