### ISSUE TITLE
[v4] Admin production api call

### ISSUE THREAD

**Issue by wwiechorek** [strapi/strapi#12167]
I deploy a strapi v4 in production using Docker.
Admin server try to get api localhost:1337 but I access painel by another URL.

I try change host and port, but admin frontend dont change a host call.

If i try change de port, same error occured. I think admin FE fixed call localhost:1337.

The problem not occurs in version 4.0.0, but occurs in versions 4.0.3 and 4.0.4.

Error: An error ocurred while request the API.

<img width="676" alt="Captura de Tela 2022-01-10 às 17 42 03" src="https://user-images.githubusercontent.com/5429129/148836484-c8b25c4d-fd97-41a5-864e-854fc46c618d.png">
 
<img width="805" alt="Captura de Tela 2022-01-10 às 09 27 50" src="https://user-images.githubusercontent.com/5429129/148836563-7cd9cf43-2202-4a89-9771-eda16bf3df70.png">

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
