### ISSUE TITLE
Re-order content type fields from admin dashboard with drag n drop

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1217]
**What is the expected behavior?**
I think it can be very good UI/UX experience if user can re-order content type fields from admin dashboard with drag n drop. I know that it can be done from json file but with graphical support it can be more simpler. :wink: 

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by soupette** [comment]
@mnlbox this feature will be developed some time later and will be a plugin. If you feel like developing it we can provide you with our thoughts on how it should work.

**Comment by mnlbox** [comment]
@soupette I don't find any plugin for this. Can you guide me more?

**Comment by derrickmehaffy** [comment]
@mnlbox there is no plugin currently it's a planned future feature.

**Comment by soupette** [comment]
@mnlbox I meant that such plugin is meant to be developed later unless you feel like contributing by developing it yourself

**Comment by UniBen** [comment]
I’m interested in developing a plugin for ordering. Please could you let me know what you are thinking of @soupette?

**Comment by derrickmehaffy** [comment]
@soupette any update for @UniBen if he is interested. :stuck_out_tongue:

**Comment by soupette** [comment]
@UniBen that would be great!
Currently there is a [`layout.js`](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/config/layout.js) in the admin that can be used to hide some elements from the left menu.

Maybe your plugin can extends this functionality a bit like the `content-type-builder` does?

**Comment by Fmstrat** [comment]
@mnlbox How do you order with JSON?

**Comment by eltel** [comment]
Did anything come of this?? Desperately needed

**Comment by derrickmehaffy** [comment]
@eltel No, currently there is no feature that allows for this.

**Comment by 4levels** [comment]
Too bad this didn't make it in, needing this as well.  Will try to create a plugin..

**Comment by tarikmiljkovic** [comment]
Need also

**Comment by domantasjurkus** [comment]
You can change the order by going to `api/<content_type>/models/<content_type>.settings.json` and reorder the `attributes` key.

**Comment by lack-of-gravitas** [comment]
@domantasjurkus doesn't work or the updates are intermittent with no way to debug. Sometimes re-ordering in those files re-orders on the CMS frontend and at other times it does not.

**Comment by 0speedy** [comment]
So, 4 years later, is there any existing solution, please? The request is closed so it looks like the original plans to integrate this feature were dropped :(

**Comment by derrickmehaffy** [comment]
See this feedback thread (it's still open but not decided if we will do it or not): https://feedback.strapi.io/customization/p/ordering-content-type-entries-in-the-list-view
