### ISSUE TITLE
at=error code=H10 desc="App crashed" method=GET path="/" host=anaya-photos.herokuapp.com request_id=2ea507db-ea29-4279-a7fe-5e675ec37966 fwd="42.105.49.103" dyno= connect= service= status=503 bytes= protocol=https

### ISSUE THREAD

**Issue by ps6067966** [strapi/strapi#12176]
Please help with error

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
