### ISSUE TITLE
[v4] Cannot query usersPermissionsRoles with GraphQL, REST works

### ISSUE THREAD

**Issue by boristian** [strapi/strapi#12181]
### Describe the bug

Querying `usersPermissionsRoles` with GraphQL returns `FORBIDDEN` error, while REST-query works fine.
I have another project with v3 where it is also working with GraphQL, of course with a corresponding query.

Query:

```gql
query Roles {
  usersPermissionsRoles {
    data {
      attributes {
        name
        type
      }
      id
    }
  }
}
```

Response:

```json
{
  "errors": [
    {
      "message": "Forbidden access",
      "extensions": {
        "error": {
          "name": "ForbiddenError",
          "message": "Forbidden access",
          "details": {}
        },
       "code": "FORBIDDEN"
      }
    }
  ],
  "data": {
    "usersPermissionsRoles": null
  }
}
```

HTTP-GET `/api/users-permissions/roles` with the same Authorization-Header works fine.

### Steps to reproduce the behavior

1. Go to `Settings` > `Roles` > `Authenticated`
2. Set the permissions `getRole` and `getRoles` `Users-permissions` 
3. Save
4. Post this GraphQL query with Authorization-Header:
```gql
query Roles {
  usersPermissionsRoles {
    data {
      attributes {
        name
        type
      }
      id
    }
  }
}
```

### Expected behavior

I would expect that strapi would return a `UsersPermissionsRoleEntityResponseCollection`.

### System

- Node.js version: v14.18.2
- Strapi version: v4.0.4
- Database: SQLite
- Operating system: Docker container with alpine-Linux

### Additional context

But maybe i am just doing something wrong. Thank you in advance!

**Comment by M1CK431** [comment]
This issue could probably be solved by #11990

**Comment by JannikWempe** [comment]
The same thing is happening for i18n locales: REST works and GraphQL is forbidden.

**Comment by 0xjoohi** [comment]
I am facing this issue currently and my usage is to query the role per user to grant access to certain things in the UI. 

Another temporary fix I have made is added a boolean at the content  type of the users whether that user is part of a certain group; then query accordingly.

This is definitely a temporary solution but the "Forbidden" problem should be fixed imo.

**Comment by LaurenzSommerlad** [comment]
I currently have the same issue. Would be great if this issue is fixed :) Thx

**Comment by macrozone** [comment]
this happens for me on all contents,
when i use the playground i get "Forbidden access"

just tried strapi for the first time

**Comment by M1CK431** [comment]
> this happens for me on all contents, when i use the playground i get "Forbidden access"
> 
> just tried strapi for the first time

Looks like something else: have you allowed public access in role permissions?

**Comment by macrozone** [comment]
> > this happens for me on all contents, when i use the playground i get "Forbidden access"
> > just tried strapi for the first time
> 
> Looks like something else: have you allowed public access in role permissions?

just found that, thx! solved the problem.

**Comment by robbyemmert** [comment]
I fixed this by updating Strapi and all plugins to ^4.2.3.

In the old version, the permission being configured is plugin::users-permissions.role.getRoles, but the permission being checked for the usersPermissionsRoles resolver is plugin::users-permissions.role.find.

Upon updating, I have a getRoles and a find option under "Roles". I'm not sure why Strapi needs both, but you need to make sure both are enabled for your role.

**Comment by robbyemmert** [comment]
However, the property `role` is still null when querying the Me type that results from the `login` mutation.

**Comment by robbyemmert** [comment]
Was finally able to get a role to return by adding middleware to the role property, checking if it returned a blank value, then doing something like:

```
if (info.fieldName === "role" && !value) {
  const userWithRole = await strapi.db
    .query("plugin::users-permissions.user")
    .findOne({
      where: {
        id: parent.id,
      },
      populate: {
        role: true,
      },
    });
  console.log("Result", parent, args, value);
  return userWithRole?.role;
}
```

**Comment by alexandrebodin** [comment]
Closing as this is fixed :)
