### ISSUE TITLE
components on single types not showing in api

### ISSUE THREAD

**Issue by SrJuggernaut** [strapi/strapi#12185]
### Describe the bug

Components added to Single Types are not reflected in the api

### Steps to reproduce the behavior

1. Create a single type
2. Add a component to that single type
3. Create an api token
4. Make an api Call to that single type

### Expected behavior

Reuse a component (Like seo) 

### Screenshots
![imagen](https://user-images.githubusercontent.com/23366813/149189576-0f3fbe9d-5549-429e-8085-22a46a35f842.png)
![imagen](https://user-images.githubusercontent.com/23366813/149189455-bfeee249-248e-44cd-a6ff-93b4a11cf670.png)

### System

- Node.js version: v14.18.2 
- NPM version: 6.14.15
- Strapi version: 4.0.4 
- Database: Postgres
- Operating system: Ubuntu wsl over windows

**Comment by DanielChuDC** [comment]
Hi @SrJuggernaut , I assume that you are using Rest API and faced the same issue before.

 Luckily, I found out the[ official documentation about `populate`](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#field-selection), it solved the issue. Perhaps it may helps you.

For GraphQL, just query the name of the relation/ single type will show.

**Comment by alecgerona** [comment]
Any idea why this is so? I've been trying to work around https://github.com/strapi/strapi-examples/issues/166 and I spent hours wondering why the other fields aren't being shown on a simple api call.

**Comment by DanielChuDC** [comment]
The reason stated on the strapi  documentation is about performance and speed. Since the single type and component or dynamic zone can be iterated, it may be costly to transfer over network.

You may read more on the link I pasted above. @alecgerona

**Comment by derrickmehaffy** [comment]
This topic has been discussed widely, next time please search for topics about population we have many many examples in our documentation about population.

**Comment by AdrianoLupossa** [comment]
I just spent the same amount of time, trying to understand this, that's a huge change from other versions and at least you guys should include this in release notes.

**Comment by brianwachira** [comment]
> I just spent the same amount of time, trying to understand this, that's a huge change from other versions and at least you guys should include this in release notes.

Agreed!
