### ISSUE TITLE
Separate "User Password Reset" form or "Unchange Password" field

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1218]
**What is the expected behavior?**
In practice we want change user field not user password generally. But always when I want to update an user field update user form show error and force me to enter password. So I always forced to update my users password when I want to update another fields. Because of this in real world I prefer to update my users fields from database that it's not good UI/UX experience.
I think it's better to move user password change to a separate form for example called **User Reset Password** or add a unchange feature to password in user update page. For example show some strar (*) and password can't change except I enter new password.
Let's talk about it here. :wink: 

---

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by lauriejim** [comment]
Actually we not send `password` value if you not update the user password. @soupette can confirm that I think.
So I don't understand why you have an issue on it.

**Comment by mnlbox** [comment]
:thinking: But I need insert password now. So maybe it's a bug yes?
Anyway I think a **Reset Password** form can be useful. :thinking:

**Comment by soupette** [comment]
Hi!
> Actually we do not send the `password` value if you are not updating it

If you do not modify the password field it won't be updated.

> But I need insert password now. So maybe it's a bug yes?

Can you provide some step to reproduce it because I just tried and it's working fine on my side

> Anyway I think a Reset Password form can be useful.

You can hide the password field from the form by modifying the following file :

**Path -**: `my-app/plugins/users-permissions/config/layout.js`

```js
module.exports = {
  user: {
    actions: {
      create: 'User.create', // Use the User plugin's controller.
      update: 'User.update',
      destroy: 'User.destroy'
    },
    attributes: {
      username: {
        className: 'col-md-6'
      },
      email: {
        className: 'col-md-6'
      },
      provider: {
        className: 'd-none'
      },
      resetPasswordToken: {
        className: 'd-none'
      },
      role: {
        className: 'd-none'
      },
      password: {
        className: 'd-none'
      }
    }
  }
};
```
Then you can create a specific container in the `content-manager` plugin to have a specific form.
