### ISSUE TITLE
Network error to admin API

### ISSUE THREAD

**Issue by rahulrkr08** [strapi/strapi#12190]
## Bug report

I deployed the Strapi app into Kubernetes and deployed the build folder to the S3 bucket, when accessing the S3 bucket, I am getting the Network error (screenshot attached below).

### Steps to reproduce the behavior

1. Build Strapi in production mode
2. Push application into Kubernetes
3. Push build folder into S3 bucket and configure it as wesite host
4. and access S3 bucket URL.

### Expected behavior

When accessing S3 bucket, it should load admin panel.

### Screenshots

![Screenshot 2022-01-13 at 2 17 57 PM](https://user-images.githubusercontent.com/2932484/149296852-d4f6afa9-82df-4e76-b556-033ca4c09413.png)

### Code snippets

```js
// ./config/admin.js
module.exports = ({ env }) => ({
  url: '/',
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  serveAdminPanel: false
});

// ./config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'http://xxx.com,
});

```

### System

- Node.js version: v16 
- NPM version: 8
- Strapi version: 4.0.2 
- Database: Postgress
- Operating system: Linux

**Comment by kibblerz** [comment]
I believe you atleast need a path in the admin url.

**Comment by derrickmehaffy** [comment]
@kibblerz is correct

Your admin path `url: '/',` should be the public url to your admin just as the server path `url: 'http://xxx.com,` is the public url to your strapi backend.

A new build will be needed.

I'm gonna set this as closed as it's not really a bug but a configuration problem so it's best to move this convo to our forum or discord
