### ISSUE TITLE
[v4] Override a controller to set the context user as author doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12199]
### Steps to reproduce the behavior

1. Update a controller like this:
```javascript
module.exports = createCoreController('api::answer.answer', () => ({
  async create(ctx) {
    // Set the current user as the author of the answer
    ctx.request.body.data.author = ctx.state.user.id;

    const response = await super.create(ctx);

    return response;
  }
}));
```

2. Save an REST entry from a user (sending the auth token)
3. The author is not saved

### Expected behavior

The author was saved.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4.0.4
- Database: SQLite
- Operating system: macOS

### Additional context

I see that this line (`sanitizeInput`) removes the author:

https://github.com/strapi/strapi/blob/ce09d38972ff48db3fbfd0ab80b58f3b5bf91a0c/packages/core/strapi/lib/core-api/controller/collection-type.js#L59

From:

https://github.com/strapi/strapi/blob/ce09d38972ff48db3fbfd0ab80b58f3b5bf91a0c/packages/core/strapi/lib/core-api/controller/index.js#L27-L30

And from:

https://github.com/strapi/strapi/blob/ce09d38972ff48db3fbfd0ab80b58f3b5bf91a0c/packages/core/utils/lib/sanitize/index.js#L14-L32

**Comment by abdonrd** [comment]
Seems like it works if I enable this permissions in the `Authenticated` role:

- User-Permissions > User > find

But obviously I can't activate this; it would give access so that users can get the information of other users.

**Comment by abdonrd** [comment]
Probably @Convly can help here :)

**Comment by abdonrd** [comment]
Related with:
- https://github.com/strapi/strapi/issues/12238

**Comment by derrickmehaffy** [comment]
related to: https://github.com/strapi/strapi/issues/11957

**Comment by alexandrebodin** [comment]
This was fixed a while back :)
