### ISSUE TITLE
[v4] Changes of required field in Content-Type Builder doesn't show in Content Manager

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#12198]
### Describe the bug

Changes of required field in Content-Type Builder doesn't show in Content Manager. 

### Steps to reproduce the behavior

1. Create collection type, for example, Category
2. Create text field "Subtitle" - not required.
3. Save the collection.
4. Create some entries of Category.
5. Come back to collection type and change field "subtitle" from "not required" to "required".
6. Open the page of creating new entry of Category
7. Observe the bug: the field of subtitle is not required

### Expected behavior

Changing the option from "not required" to "required" is saved.

It's repeatable problem with any content type in admin.

### Screenshots

Content-Type Builder: field is required

<img width="1084" alt="2022-01-14 14-36-32" src="https://user-images.githubusercontent.com/1038168/149510201-88fda49c-68f1-4565-88be-eec241c893fb.png">

Content Manager: field is not required - the bug

<img width="1028" alt="2022-01-14 14-37-14" src="https://user-images.githubusercontent.com/1038168/149510231-c9a6e79c-61a1-4f33-8330-00105c2f8e9c.png">

### System

- Node.js version: 14.17.5
- NPM version: 6
- Strapi version: 4.0.4
- Database: SQLite
- Operating system: MacOS

**Comment by abdonrd** [comment]
Right! Mention to @rockmandash here: https://github.com/strapi/strapi/pull/12111#issuecomment-1007615343

**Comment by ronronscelestes** [comment]
Hi @teinett and @abdonrd! Thank you for spotting those required field UI issues, it's currently on the way to being fixed - some of them had to be fixed in the DS beforehand 😊
