### ISSUE TITLE
[v4] Filters in `findOne` controller doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12208]
### Describe the bug

Filters in `findOne` controller doesn't work.

### Steps to reproduce the behavior

1. Create a controller like this:
```javascript
async findOne(ctx) {
  // Filter by the current user as the author
  ctx.query = {
    ...ctx.query,
    filters: {
      author: {
        id: ctx.state.user.id
      }
    },
  };

  const response = await super.findOne(ctx);

  return response;
},
```

2. Run the REST `GET /content-type/:id`
3. It shows the entry, even if the user is not the author

### Expected behavior

The custom filter working

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4.0.4
- Database: SQLite
- Operating system: macOS

### Additional context

Debugging a bit...

After this:

https://github.com/strapi/strapi/blob/31259dbf4ad7099cab3c4927af9a28db9dc5fb3e/packages/core/strapi/lib/core-api/service/collection-type.js#L54-L56

I see that this line removes the custom params:

https://github.com/strapi/strapi/blob/31259dbf4ad7099cab3c4927af9a28db9dc5fb3e/packages/core/strapi/lib/services/entity-service/index.js#L144

**Comment by kasonde** [comment]
Hi, thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.

You filter must look like [this](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/filter.html#eq) in Strapi v4. Hope this helps!
```
ctx.query = {
    ...ctx.query,
    filters: {
      author: {
        id: {
          $eq: ctx.state.user.id
        }
      }
    },
  };

**Comment by abdonrd** [comment]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@strapi/strapi@4.0.4` for the project I'm working on.

I just tried to fix #12208.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@strapi/strapi/lib/services/entity-service/index.js b/node_modules/@strapi/strapi/lib/services/entity-service/index.js
index 20a40c7..1815d56 100644
--- a/node_modules/@strapi/strapi/lib/services/entity-service/index.js
+++ b/node_modules/@strapi/strapi/lib/services/entity-service/index.js
@@ -141,9 +141,9 @@ const createDefaultImplementation = ({ strapi, db, eventHub, entityValidator })
   async findOne(uid, entityId, opts) {
     const wrappedParams = await this.wrapParams(opts, { uid, action: 'findOne' });
 
-    const query = transformParamsToQuery(uid, pickSelectionParams(wrappedParams));
+    const query = transformParamsToQuery(uid, wrappedParams);
 
-    return db.query(uid).findOne({ ...query, where: { id: entityId } });
+    return db.query(uid).findOne({ ...query, where: { ...query.where, id: entityId } });
   },
 
   async count(uid, opts) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Webbist-dev** [comment]
I agree this should be a thing. I'd like to filter on more than the id (if routing via slug in my frontend)

**Comment by abdonrd** [comment]
I just create a PR: https://github.com/strapi/strapi/pull/12223

**Comment by abdonrd** [comment]
@kasonde could you reopen the issue? Thanks!

**Comment by kasonde** [comment]
@abdonrd thanks for the extra information.

**Comment by polp6880** [comment]
@abdonrd @kasonde what would be a good workaround for this in the current released version? I have an _/api/trips_ endpoint and I want to allow _/api/trips/:id_ only if the authenticated user matches the trip user. My idea was to use filters as suggested above as I'm not aware of an alternative option.

**Comment by derrickmehaffy** [comment]
> @abdonrd @kasonde what would be a good workaround for this in the current released version? I have an _/api/trips_ endpoint and I want to allow _/api/trips/:id_ only if the authenticated user matches the trip user. My idea was to use filters as suggested above as I'm not aware of an alternative option.

route middleware would be the best method and use the `find` in the middleware instead of findOne, then you can deal with parsing the array instead of the object. (you can do it at the controller level too, but middleware option is cleaner)

**Comment by polp6880** [comment]
Thanks @derrickmehaffy

**Comment by derrickmehaffy** [comment]
Last time I discussed this with our engineering team it wouldn't make sense to have filters on findOne since the findOne method we have requires you to specify the ID of the entry you need to find making the filters pointless. For now we recommend using findMany

**Comment by Kazdan1994** [comment]
Hey everyone, try this

```
async findOne(ctx){
    const user = ctx.state.user;
    const { id } = ctx.params;

    const entity = await strapi.query(UID).findOne({
      where: {
        id,
        users: user.id
      }
    });
    const sanitizedEntity = await this.sanitizeOutput(entity, ctx);

    return this.transformResponse(sanitizedEntity);
  }
```

**Comment by alexisottonkpler** [comment]
> Last time I discussed this with our engineering team it wouldn't make sense to have filters on findOne since the findOne method we have requires you to specify the ID of the entry you need to find making the filters pointless. For now we recommend using findMany

Filters are needed for policies that filter the access right to a content threw a findOne query

**Comment by vibonacci** [comment]
This is often desired when you search 1 by id, but also want to see if related field matches a value. In many frameworks, findOne support additional filters.
