### ISSUE TITLE
Email validation wrong URL v4

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#12202]
### Describe the bug

The url sent in the email validation is missing /api

### Steps to reproduce the behavior

1. Set url in config. i.e www.website.com
2. Build and register new user
3. Get validation email with link to www.website.com/auth/email-confirmation?confirmation=fbd5b9279c3efc92a5a615b8ddffcfdafb7f8cf5
4. See error 404.

### Expected behavior

Email validation link should route to the api endpoint.
i.e.  www.website.com/api/auth/email-confirmation?confirmation=fbd5b9279c3efc92a5a615b8ddffcfdafb7f8cf5 instead of www.website.com/auth/email-confirmation?confirmation=fbd5b9279c3efc92a5a615b8ddffcfdafb7f8cf5
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14
- NPM version: v6
- Strapi version: v4
- Operating system: Node-14:slim

### Additional context

I tried adding /api to the end of the url parameter, but then the admin panel breaks.

**Comment by petersg83** [comment]
Hello :) Thanks, it's been fix in https://github.com/strapi/strapi/pull/12162
