### ISSUE TITLE
Enable image rotation by default

### ISSUE THREAD

**Issue by ovlb** [strapi/strapi#12204]
### Describe the bug

Images uploaded straight from the camera are displayed rotated.

There is a setting in the media library to rotate images, but it is turned off by default. I’d argue that correctly rotated images should be the default.

### Steps to reproduce the behavior

1. Take a picture with your phone camera
2. Upload image to Strapi
3. See rotated image

### Expected behavior

Image rotation is calculated correctly by default.

### Screenshots

<img width="849" alt="Screenshot of the Strapi media editor. An uploaded image is shown upside down." src="https://user-images.githubusercontent.com/7645967/149638251-333319f4-5603-4b90-9bd8-d481772da092.png">

### System

- Node.js version: v14.8.3
- NPM version: 6.14.5
- Strapi version: v4.0.4
- Database: Postgres
- Operating system: mac/Ubuntu

**Comment by WalkingPizza** [comment]
I see your point, but I don't think auto-rotation should be enabled by default.

Checking for the _Orientation_ tag and rotating images adds overhead to the server, and it might not be necessary for the typical Strapi user, and considering how easy it is to enable the option, I'd say it makes much more sense to keep it disabled by default.

**Comment by derrickmehaffy** [comment]
Pretty sure we already do this? https://github.com/strapi/strapi/issues/5996 based on the EXIF data. Anything beyond that I agree it shouldn't be default. Logic implementations to determine what is up or down is not a good idea.

I'll set this as a discussion and assign it to our content squad to see what they think but my opinion would be no.

**Comment by yanniskadiri** [comment]
Thanks for highlighting this, we'll discuss it in the content squad and I'll get back to you.

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/enable-image-rotation-by-default

Thanks!
