### ISSUE TITLE
Template Installation Fail

### ISSUE THREAD

**Issue by definite2** [strapi/strapi#12211]
### Describe the bug

I cannot use strapi templates. When I run the template commands as following the [templates docs](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/templates.html#using-a-template), at first it creates the project folder succesfully; but in a second it gives *Template Installation failed...* error, then immediately it deletes the project folder that has been created.

### Steps to reproduce the behavior

I tried four different command to create strapi project using template :

-  `npx create-strapi-app@latest my-project --template next-example --quickstart` 
- `npx create-strapi-app@latest my-project --template https://github.com/strapi/strapi-template-next-example.git`
- `npx create-strapi-app my-project --template https://github.com/strapi/strapi-template-next-example.git`
- `npx create-strapi-app my-project --template next-example`

In the end it gives the following error:
Error: ⛔️ Template installation failed: Command failed: C:\WINDOWS\system32\cmd.exe /q /s /c "npm view next-example name version --silent"

### Screenshots
![image](https://user-images.githubusercontent.com/48595100/149666530-8f351b56-f430-4b7a-a2fe-587ed39e1dc0.png)

### System

- **Node.js** version: 14.18.1
- **NPM** version: 6.14.15
- **Operating system**: Windows 10

### Additional context
With the same system given above, I can successfully run `npx create-strapi-app@latest my-project --quickstart` .
I tried with other templates (i.e. ecommerce) as well but the same error occured.
Similar bug report #8786

**Comment by kasonde** [comment]
Hi @definite2 please open an issue for these in the repositories of the respective templates. You have mentioned that vanilla strapi cli installs are working fine.

**Comment by AbdalrhmnRoston** [comment]
Please tell me if you managed to solve the problem because I have the same problem, thank you

**Comment by rawestmoreland** [comment]
I am getting the same error when trying to use a template generated by the strapi CLI.

My command: 

`npx create-strapi-app blog001 --template https://github.com/rawestmoreland/strapi-template-blog`

And the output:

```
Error: ⛔️ Template installation failed: Command failed: npm view https://github.com/rawestmoreland/strapi-template-blog name version --silent

    at createProject (/Users/richard/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createQuickStartProject (/Users/richard/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-quickstart-project.js:23:3)
```

**Comment by elihuvillaraus** [comment]
Same issue here... hope someone finds a solution

**Comment by koctalha** [comment]
Same also. Is there any specific reason to have this error?
I am able to deploy with default strapi blog template, but not the custom one.
