### ISSUE TITLE
API Tokens 403 after redeploying Strapi service

### ISSUE THREAD

**Issue by MichaelLegg** [strapi/strapi#12212]
### Describe the bug

If you create one of the new v4 API Tokens and do a request to the Content API with any access level, it works up until you redeploy your Strapi instance and then it 403s.

The tokens remain in the UI - presumably as they're stored in the database. There's no expiration settings or anything, so they presumably aren't expiring.

### Steps to reproduce the behavior

1. Go to {strapi-serice}/admin/settings/api-tokens
2. Generate a new token (any access level)
3. Do a request to the content API and receive a successful response
4. Redeploy Strapi service
5. Do the same request with the same token, receive a 403

### Expected behaviour

Tokens work between deploys.

### Screenshots

N/A

### Code snippets

Response:

```
{
	"data": null,
	"error": {
		"status": 401,
		"name": "UnauthorizedError",
		"message": "Missing or invalid credentials",
		"details": {}
	}
}
```

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 4.0.4
- Database: Postgres
- Operating system: Windows 10

**Comment by kasonde** [comment]
@MichaelLegg please elaborate more on the steps to reproduce the issue. How are you redeploying you application? What is the deployment workflow you're following? Also what is the setup on the local machine versus the machine you're redeploying to?

**Comment by MichaelLegg** [comment]
Hey @kasonde, apologies - the issue was a bit scant on detail.

I've just been doing a bit more testing. If I run Strapi locally in either production or development mode(pointing at a Heroku Postgres DB) - then create a token and do a request, I get a 200 back. If I then restart the server, I still get a 200. No issues there, it would seem.

However, when I do the same process, but I do the above steps with the Strapi backend on my deployment environment on Heroku (pointing at the same database), the token seems to be invalid after I have redeployed/restarted the service.

I can still see the token in the UI, there's nothing to suggest it's invalid for any reason, but all requests using the token return a 403.

I also notice that if I create a token on my deployed Strapi instance, and use it to try to query the content-API on a strapi instance that's running locally, I receive a 403. They are both looking at the same database (postgres deployed on Heroku). I should have thought that should work?

I could be fundamentally misunderstanding how the API tokens work here in v4. But my assumption was that they were stored in your database, and therefore two deploys, or one local and one deployed version, should both work using the same token - and, in the same vein re-deploying the Strapi instance to a deployment service shouldn't stop them from working?

A quick loom of the local vs deployed tokens case (as it's a bit hard to do one of the re-deployment of the Heroku instance causing invalidation):
https://www.loom.com/share/33ac3ffee9ee4371aff07627d7fbe9d2

**Comment by MichaelLegg** [comment]
I've since found the tokens will become invalid seemingly at random intervals just running locally, in addition to the reproduction steps above that occur when running across multiple deployment environments.

**Comment by derrickmehaffy** [comment]
setting this a duplicate to: https://github.com/strapi/strapi/issues/12255
