### ISSUE TITLE
Strapi v3 filters not working

### ISSUE THREAD

**Issue by leon-wbr** [strapi/strapi#12224]
### Describe the bug

When trying to use filters in a REST API request, it interprets them as a field on the model and gives a 400 Bad Request error.

### Steps to reproduce the behavior

1. Create any model
2. Request a list of models with any filters
3. See error

### Expected behavior

Use the filter as described [in the documentation](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering).

### System

- Node.js version: v12.18.3
- NPM version: 6.14.7
- Strapi version: v3
- Database: SQLite
- Operating system: Windows

**Comment by lack-of-gravitas** [comment]
Made the same mistake -- I was looking at v4 documentation which references filter functionality. If you go to v3 docs, there's no filters.

**Comment by derrickmehaffy** [comment]
docs.strapi.io is for v4
docs-v3.strapi.io is for v3

the `filters` key doesn't exist for v3 as the filtering system is different, closing

**Comment by gustawdaniel** [comment]
change 

```
?[filters][$contains]=pod
```

to

```
?title_contains=pod
```

docs filters v3 https://docs-v3.strapi.io/developer-docs/latest/developer-resources/content-api/content-api.html#filters
docs filters v4 https://docs.strapi.io/dev-docs/api/rest/filters-locale-publication
