### ISSUE TITLE
[v4] npm install does not work with npm 8.3.0

### ISSUE THREAD

**Issue by cschuller** [strapi/strapi#12232]
### 🌵 Describe the bug

Running `npm install` does not install the `@casl/ability` dependency of  Strapi when using `npm` 8.x

The missing dependency will break all (?) user permission features.

For example:
- Open media library page in admin UI will display a white page.
- Open any permission related settings in the admin UI will display a white page.
- Authenticated API endpoints do not work.

On white pages a console error is shown in the log.

```
TypeError: Cannot read properties of undefined (reading 'allPermissions')
```

### 🚩 Steps to reproduce the behavior

1. `npx create-strapi-app@latest my-project`
2. `cd my-project`
3. `rm yarn.lock`
4. `rm -rf node_modules`
5. `npm install`
6. `npm run build`
7. `npm run start`

Step **5** `npm install` will print this warning:

```
npm WARN EBADENGINE Unsupported engine {                         
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.3.0' }
npm WARN EBADENGINE }
```
### 🧪 Analysis

- The `@strapi/admin` has a dependency to '@casl/ability@4.1.6'
- '@casl/ability@4.1.6' requires a specific `npm` version `'^6.0.0'`

### ⭐Expected behavior

- `npm install` installs all required dependencies
- Strapi is using a dependency that matches the system requirements

### 💡 Options/Ideas to fix the issue

- Update `@casl/ability` from version `4.1.6` to `5.4.3`
- Replace `@casl/ability` dependency
- Pull-request to `@casl/ability` to update the engine property in `package.json`

### 🍋 Work-arounds

- Use an older `npm` version that does not check the required engine of a dependency
- Use `yarn` (because it does not check the required engine)
- Manually install `@casl/ability` (bad idea)

A `package-lock.json` file and a `npm ci` will not work.

### System

- Node.js version: v16.13.2
- NPM version: 8.3.0
- Strapi version: v4.0.4
- Database: sqlite
- Operating system: Windows 10 & Ubuntu 20.04

### Links

- https://github.com/strapi/strapi/blob/master/packages/core/admin/package.json
- https://www.npmjs.com/package/@casl/ability

### Related issues
- https://github.com/strapi/strapi/issues/11494
- https://github.com/strapi/strapi/issues/11453

**Comment by derrickmehaffy** [comment]
Seems related to https://github.com/strapi/strapi/issues/11729

**Comment by derrickmehaffy** [comment]
Latest version of @casl/ability is 5.4.3: https://www.npmjs.com/package/@casl/ability

We probably need to upgrade as I can confirm they pin npm v6: https://github.com/stalniy/casl/blob/2c295738b145cffe938ba56084ae217abb4703e0/packages/casl-ability/package.json#L42-L44

**Comment by derrickmehaffy** [comment]
@cschuller are you good to make a PR to fix this? (Thank you very much for your detailed digging, well done, probably the best issue I've seen in years :laughing: )

**Comment by cschuller** [comment]
@derrickmehaffy I just started using Strapi, so not a lot of experience here. 
Anyway I can give it a try and prepare a pull-request. Maybe I need some support for the final integration test.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I just started using Strapi, so not a lot of experience here. 
> Anyway I can give it a try and prepare a pull-request. Maybe I need some support for the final integration test.

Ah no problem, I would suggest just updating the package. I believe you know the location to update so it should be a pretty simple change but I understand if you aren't sure how to test that change.

Else if you aren't confident no big deal, I just like to promote community members into contribution if they are willing 😁

**Comment by cschuller** [comment]
@derrickmehaffy I will create a pull-request tomorrow.
Need to check the breaking changes of `@casl/ability` between `4.1.6` and `5.4.3` and if this relevant for Strapi code.

**Comment by ovlb** [comment]
Das CASL handle API key validation? We have a weird issue in our instance where an API gets invalidated after seemingly random amounts of time. We were suspecting a rate limit or so at first, but the keys were constantly throwing 401 errors when trying to access the API. Might be a different issue though.

**Comment by derrickmehaffy** [comment]
> Does CASL handle API key validation? We have a weird issue in our instance where an API gets invalidated after seemingly random amounts of time. We were suspecting a rate limit or so at first, but the keys were constantly throwing 401 errors when trying to access the API. Might be a different issue though.

Not sure what it does TBH as I didn't dig that deep but are you on Node 16 / NPM 8?

**Comment by ovlb** [comment]
> Not sure what it does TBH as I didn't dig that deep but are you on Node 16 / NPM 8?

Yes, we were. I’ve just downgraded the deployed version to 14/6 and will monitor if this issue comes up again.

**Comment by linbudu599** [comment]
@cschuller Thanks!

**Comment by denik1981** [comment]
All tests (unit and e2e) need to pass for any submitted PR.

**Comment by cschuller** [comment]
@denik1981 
Maybe you can help out with this pull-request:
https://github.com/strapi/strapi/pull/12254

See pull-request documentation what is missing

**Comment by denik1981** [comment]
Yes, I'm working on it. My unit tests have passed well with the modifications I made but not the e2e ones. 
I will post it here once I have a suitable RFC PR.

As you said, there are some breaking changes that need to be addressed. As a side note, a future PR could be made to explore and refactor strapi "sanitize" code because I believe one of the BREAKING CHANGES of CASL is solving what sanitize() was trying to achieve for the lack of a particular @casl feature. Need to explore further on this but, IMHO, a first attempt is to upload a PR that will make users able to use npm 8 and keep the app stable without running into this kind of issue. 

I'm also thinking if it would be necessary to add a step job in the current GH workflow to test for an npm install. 
It's all **yarn** currently.

**Comment by cschuller** [comment]
@denik1981 I am not sure if adding a commit to add a specific test and remove it with a second one is helpful. In the end it is be like a manual test.  

I think adding an extra test for CI/workflow testing the install is a waste of computation time, yes this bug was somehow tricky to find for me, but I have never seen this kind of problem before.

Another idea: we could add a permanent GitHub action that tests `npm install`, but needs to be manually started, like a proof for this fix and for future "strange" issues like does not work on OS X, nodejs Y, npm Z, ... 

🎉 Thanks for working on this. 

My free time is currently very limited (👶), but I hope I can contribute in the future.

**Comment by denik1981** [comment]
Yes, I was referring to a GH action.
I agree it will add too much workload to the CI process that's why I suggest the alternative to submit the workflow run within a special commit within the PR aimed for the only task of running this tailored workflow. And a later one to reset the GH workflow as it was before. Somehow you have to test for this. I don't think testing locally is enough.

**Comment by denik1981** [comment]
I have just submitted a PR for this #12265

**Comment by denik1981** [comment]
@derrickmehaffy Can you check why the PR workflow is stopped in the security check? 
Might be because I updated a major semver (@casl/ability)? It has been paused in that step for a long time.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Can you check why the PR workflow is stopped in the security check? Might be because I updated a major semver (@casl/ability)? It has been paused in that step for a long time.

It just takes a while, it passed before I triggered of merge of master into your branch. All good :)
