### ISSUE TITLE
Missing Docker images for v4 and up

### ISSUE THREAD

**Issue by mway-niels** [strapi/strapi#12231]
We want to deploy Strapi as a CMS for our Gatsby website. We're running v3.6.8 at the moment and saw that v4.0.4 has been released in the meantime.

Unfortunately we weren't able to find the updated image on [Docker Hub](https://hub.docker.com/r/strapi/strapi), the latest version there is 3.6.8.

**Comment by RobinSJames** [comment]
@mway-niels you may find [strapi/base](https://hub.docker.com/r/strapi/strapi#strapi-base) to be more useful to you then.
It'll allow you to build your own image.

**Comment by derrickmehaffy** [comment]
We will release the v4 docker images in time, this is the repo to post the request on.

**Comment by beaussan** [comment]
@derrickmehaffy Any idea on the timeline (like weeks, months) ? I want to start a new project on v4 but I don't know if I should hold until the official docker image exists

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Any idea on the timeline (like weeks, months) ? I want to start a new project on v4 but I don't know if I should hold until the official docker image exists

AFAIK it's been pushed until Q2 as it's a very low priority for us right now. You don't need our images to use docker (we recommend you build your own for production anyway).

Here is a community blog post about how to build your own images: https://blog.dehlin.dev/docker-with-strapi-v4

**Comment by mariushosting** [comment]
I get over 1000 emails in the last 3 months, and people tell me they want version 4.x from strapi on docker hub, I think this should be high priority imho ;-)
