### ISSUE TITLE
[v4] Strapi endpoint doesn't seem to show components in the response

### ISSUE THREAD

**Issue by alexeysarakuz** [strapi/strapi#12235]
Hey, just created a Strapi project 4.0.4 
Created a quite simple single type with the following fields:
<img width="1440" alt="Снимок экрана 2022-01-18 в 18 23 30" src="https://user-images.githubusercontent.com/26776049/149976992-8a45c619-3e6e-4356-9b23-433f6288e5cb.png">
& updated permissions (added find checkmark in the corresponding single type)
And these fields doesn't seem to be available somehow
<img width="1119" alt="Снимок экрана 2022-01-18 в 18 30 00" src="https://user-images.githubusercontent.com/26776049/149978076-49f27600-8e66-491e-bf38-c63bdefb6e4d.png">

(everything is published)

I restarted the app, built it, reinstalled node modules, and ran it on multiple PC
I checked Strapi starters but there is the same issue there, am I doing something wrong?

**Comment by WalkingPizza** [comment]
You need to configure the `populate` parameter. More info [here](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population).

**Comment by alexeysarakuz** [comment]
> You need to configure the `populate` parameter. More info [here](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population).

Man! Thank you so much

**Comment by derrickmehaffy** [comment]
closing as there is multiple duplicates of this issue.

**Comment by alexeysarakuz** [comment]
> closing as there is multiple duplicates of this issue.

any references, please?
