### ISSUE TITLE
iln8 plugin bug, enable to duplicate

### ISSUE THREAD

**Issue by Antoine-arranz** [strapi/strapi#12247]
Hello, here is my bug report with the internationalization plugin
## Bug report

I have a Article collection with a list of articles all available in fr,en & pt. When I click on the dupplicate icon to dupplicate an article (on the right of the line where the are all listed), The article is dupplicate on the 3 locales. Everything is OK but if you make some changes and you save, the other locale will be emptied 

### Steps to reproduce the behavior

1. Create an article in different locale
2. Click on the dupplicate icon
3. Modify the new article and save it
4. The other locale on the new article will be erased

### Expected behavior

On the dupplicate article, the other locale should not be erased
### Screenshots

![image](https://user-images.githubusercontent.com/64416150/150176047-bc96431a-be15-4b83-bbc4-d3534b773d9b.png)
![image](https://user-images.githubusercontent.com/64416150/150175654-0fb2abfa-0360-4438-bd4b-537810cb80bb.png)
![image](https://user-images.githubusercontent.com/64416150/150175689-8d975c5b-fc8e-493c-a190-091c5f4a9896.png)

### System

- Node.js version: <14.15.0>
- Strapi version: <v3>

### Additional context

Everything is working well if you modify a locale that is not your default locale first

**Comment by derrickmehaffy** [comment]
```
Node.js version: <14.15.0>
Strapi version:
```

Please fill out the entire requirements of the template, I have no idea what Strapi version or any other information on your environment.

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
