### ISSUE TITLE
Unique and localisation - checks in all languages

### ISSUE THREAD

**Issue by HannesOberreiter** [strapi/strapi#12248]
### Describe the bug

Unique fields are checked in all languages and therefore you cannot same value in different languages. To be honest, I don't know if that is expected.

### Steps to reproduce the behavior

1. Create a Content-Type with a text-field with attributes "**Enable Unique**" and "**Enable localization for this field**" enabled.
2. Create a "New Entry" for this Content-Type and write for example the text value "**Tourist**" for English
3. Now create for example the "German" localisation which would be the same: "**Tourist**"
4. You get an error that the value is not "Unique"

### Expected behavior

The "unique" check should only apply to one language.

### System

- Docker: strapi/base:latest (tag 14)
- Strapi version: 4.0.4

### Additional context

Somewhat similar issue: https://github.com/strapi/strapi/issues/10694

Cheers
Hannes

**Comment by yanniskadiri** [comment]
This is an issue related to this one too: #10107
It's not the same use case but it's the same cause. It's a feature request we will address in the future. Thanks for sharing your use case :)

**Comment by jhoward1994** [comment]
This issue has been fixed in v5 from 5.0.0-beta.13 onwards via https://github.com/strapi/strapi/pull/20427
