### ISSUE TITLE
Bookshelf issue with timestamps, cannot send post requests

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1224]
**Informations**
- **Node.js version**: 9
- **npm version**: 5
- **Strapi version**: 12.2
- **Database**: MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

Error when posting and using MariaDB with timestamps:

``` 
code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \' \'2018-05-08 09:19:40.037\')\' at line 1',
  sqlState: '42000',
  index: 0,
  sql: 'insert into `systems` (`created_at`, `fields`, `files`, `updated_at`) values (\'2018-05-08 09:19:40.037\', `systemName` = \'Test\', , \'2018-05-08 09:19:40.037\')' }
```

**Steps to reproduce the problem**

Attempting to send any post request to a model that is attached to MySQL

**What is the expected behavior?**

Strapi should not send milliseconds to a mysql database:

`2018-05-08 09:19:40.037`

**Suggested solutions**

Change has happened since v12.1.3 that is causing this error.

**Related to**

https://github.com/strapi/strapi/issues/870
https://github.com/strapi/strapi/issues/1119

---

- [X] I'm sure that this feature hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
@lauriejim Posts requests are completely broken on v12.2 due to timestamps FYI

**Comment by derrickmehaffy** [comment]
AdminUI additions are not affected, only post requests

**Comment by lauriejim** [comment]
Hey @derrickmehaffy thank you for this reporting. It happen on File upload and other generated API ?

**Comment by derrickmehaffy** [comment]
This is just on a standard model, file uploads have had some issues the past few releases as well.
Mainly with SQL syntax

**Comment by derrickmehaffy** [comment]
Odd @lauriejim so I did some additional testing with a brand new test machine:

Node v10
NPM v5
Strapi v12.2
OS Ubuntu 18.04 LTS
DB MariaDB 10.2

Everything worked fine, which I find strange. The only difference here is the OS version (16.04 vs 18.04) and the Node Version (10 v 9)

What I tested: Created a new VM for each Database Type (3 in total) MongoDB, Postgres, MariaDB. installed Strapi v12.2 globally, and created a new project. Started the project and created a test model, and inputed some test data via the adminUI, edited the data, and deleted it.

Then I did the same using postman, authenticated and got token, `POST` data, `PUT` edited data, and `DELETE` the data. All worked fine on all 3 databases.

I did however notice that with MariaDB when first starting on the fresh project strapi fails to start with `bookshelf took too long to load`, I also had the same error after creating the test model and it auto-restarts. So there is certainly a load issue when using mysql. I increased the hook limit to `40000` and didn't hit any issues after that.

**Comment by derrickmehaffy** [comment]
I will do some additional testing on the VM I had issues with and create another ubuntu 16.04 VM to test on. There might have been a bug while updating strapi globally or node 9.

**Comment by derrickmehaffy** [comment]
Versions for issue VM: 
![image](https://user-images.githubusercontent.com/8593673/40248351-89af66f6-5a84-11e8-8905-1f096ad3ca82.png)

Versions for working VM:
![image](https://user-images.githubusercontent.com/8593673/40248381-98009d06-5a84-11e8-8197-3b1ec2b02132.png)

**Comment by derrickmehaffy** [comment]
@lauriejim tested on old VM and can't reproduce error. For now you can mark this as closed and I'll continue testing to see if I can get it to appear.
