### ISSUE TITLE
afterUpdate lifecycle hook on Type not called

### ISSUE THREAD

**Issue by AugustZellmer** [strapi/strapi#12253]
### Describe the bug

The `afterUpdate` lifecycle hook on a Type is not being called, afaict.

### Steps to reproduce the behavior

1. Create a new Type `Foo`. 
2. In the `api/foo/models/foo.js` file, add the following code:
```
'use strict';

module.exports = {
  async afterUpdate(event) {
    strapi.log.error('here');
    console.log('there');
  }
}
```
3. Start the server.
4. Update a Foo.

### Expected behavior

Either "here" or "there" (preferably both) is logged to the console.

### Actual behavior

"PUT /content-manager/single-types/application::foo.foo (251 ms) 200" is logged to the console, but that's all.

### System

- Node.js version: 14.18.3
- Yarn version: 1.22.17
- Strapi version: 3.6.2 (I know version 3 isn't supported anymore, but I can't figure out how to migrate to version 4.)
- Database: MySQL or Postgres
- Operating system: Linux

**Comment by AugustZellmer** [comment]
possibly related to https://github.com/strapi/strapi/issues/11828?

**Comment by derrickmehaffy** [comment]
@AugustZellmer not quite, this issue is for v3

We don't support v3 anymore but the structure of your file is wrong. The lifecycles need to be incased in a lifecycles object in v3:  https://docs-v3.strapi.io/developer-docs/latest/development/backend-customization.html#lifecycle-hooks

**Comment by AugustZellmer** [comment]
I should've paid more attention to the docs. Thanks!
