### ISSUE TITLE
roles relational data is not updating to database

### ISSUE THREAD

**Issue by gegeburlogz** [strapi/strapi#1226]
**Informations**
- **Node.js version**:v10.1.0
- **npm version**:5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**:MongoDB
- **Operating system**:Windows 10

**What is the current behavior?**
does not updating roles and provider in database with an error 
![image](https://user-images.githubusercontent.com/19794022/40226874-810b9e12-5abf-11e8-8a60-d4036dc3bdf0.png)
![image](https://user-images.githubusercontent.com/19794022/40227358-e02de14c-5ac0-11e8-88dc-e8bb4b0dafe7.png)

**Steps to reproduce the problem**
Add New user then save or edit an existing user then save

**What is the expected behavior?**
 We need see user role in Users page

**Suggested solutions**

**Comment by lauriejim** [comment]
Please follow the migration guide https://github.com/strapi/strapi/wiki/migration-guide-alpha.12.1-to-alpha.12.2

`this.updateRelation` is on `alpha.12.2` and not in `alpha.12.1.3`.
