### ISSUE TITLE
Creating and connecting Strapi to existing postgres database deleted all existing tables

### ISSUE THREAD

**Issue by myedugate3tech** [strapi/strapi#12261]
### Describe the bug

I was trying to connect Strapi v4 to the existing Postgres database hosted on AWS. After building and running the admin panel, it deleted all the existing tables.

### Steps to reproduce the behaviour

Create a new Strapi application with PostgreSQL and connect to an existing database that already has some tables. Then build and run the application

### Expected behaviour

Strapi should create/override only new tables and do not delete any existing ones during the initial setup.
I have tried this on Strapi v3 and MongoDB which never deleted any existing collections.

### System

- Node.js version: v16.13.0
- NPM version: v8.1.4
- Strapi version: v4
- Database: postgresql
- Operating system: Windows 11

**Comment by derrickmehaffy** [comment]
This is intended as a solution to #1114 

We do have a setting `forceMigration: false` that will disable all actions related to database schema management here: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#settings-configuration-object

---

DX Squad / Growth Squad maybe we could implement a check of the database to see if it's empty before we create and if stuff exists asks the user if they are okay with data being deleted?

Likewise maybe we could add another setting to not delete tables or columns (or we add an option to ignore certain tables/columns from the check)

**Comment by smoothdvd** [comment]
Can we separate migration and model?

**Comment by Interfaxis** [comment]
hello @derrickmehaffy  👋🏻 
it means that I need to use the forceMigration setting if I want to purge the database tables and columns that I don't use? (probably because of attributes name updates, etc), I see this is something new in v4 but I don't understand what should I use. :-) thank you in advance

**Comment by John0x** [comment]
Does this usecase work yet?
I would really like to use strapi instead of Directus, but this keeps me from adopting it.

**Comment by affinage-digital** [comment]
forceMigration: false - not working
i got `relation "strapi_core_store_settings" already exists`  every time
i dont understand what happened

**Comment by John0x** [comment]
Has this been released?
Can't really find any documentation
@vincentbpro

**Comment by derrickmehaffy** [comment]
> Has this been released? Can't really find any documentation @vincentbpro

Not that I'm aware of, I'll let Vincent expand in case I missed the PR

**Comment by Max3939** [comment]
forceMigration: false - This does not work inPostgreSQL! 
Strapi deletes the tables anyway. Can you please tell me how to turn it off? Why is this even needed?
Perhaps I did not write something correctly, but unfortunately there is no example in the documentation.

My Code:

module.exports = ({ env }) => ({
 // forceMigration: false,
  connection: {
    client: "postgres",
    connection: {
      host: env("DATABASE_HOST", "192.168.1.100"),
      port: env.int("DATABASE_PORT", 5432),
      database: env("DATABASE_NAME", "blablabla"),
      user: env("DATABASE_USERNAME", "blablabla"),
      password: env("DATABASE_PASSWORD", "pass"),
      schema: env("DATABASE_SCHEMA", "public"), // Not required
      ssl: env("DATABASE_SSL", false),

      // {
      //   rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
      // },
    },
    forceMigration: false,
    debug: false,
    
    
  },
});

**Comment by hobe** [comment]
@Max3939 `forceMigration`  needs to be a subproperty of `settings` (see docs: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-structure):

```
         connection: {
            client: env("DATABASE_CLIENT", "postgres"),

            connection: {
                host: env("DATABASE_HOST", "127.0.0.1"),
                port: env.int("DATABASE_PORT", 5432),
                database: env("DATABASE_NAME", "strapi"),
                user: env("DATABASE_USERNAME", "strapi"),
                password: env("DATABASE_PASSWORD", "strapi"),
            },
            debug: false
        },
        settings: {
            forceMigration: env("FORCE_MIGRATION", false),
        }
```
