### ISSUE TITLE
Swagger UI Documentation Plugin: No "Retrieve your jwt token" button implemented

### ISSUE THREAD

**Issue by jpizzle34** [strapi/strapi#12260]
### Describe the bug

There is no "Retrieve your jwt token" functionality in the Admin UI of the Swagger UI Documentation Plugin as described in the docs:
https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#administration-panel

Strapi v3 has this feature, however it doesn't seem to be implemented in Admin UI of Strapi v4 (yet).

### Steps to reproduce the behavior

1. ```yarn create strapi-app my-new-app```
2. ```yarn strapi install documentation```
3. Go to ```Plugins > Documentation``` or ```Settings > Documentation``` in the Admin UI.

### Expected behavior

To be able to conveniently generate a JWT token from the Admin UI for the purpose of testing with the Swagger UI Documentation Plugin.

### Screenshots

-

### Code snippets

-

### System

- Node.js version: v16.13.0
- NPM version: 8.1.2
- yarn version: 3.1.1
- Strapi version: v4
- Database: SQLite
- Operating system: Ubuntu 21.10

### Additional context

-

**Comment by derrickmehaffy** [comment]
Can confirm this used to exist in v3, doesn't in v4. Set as a feature request not a bug (I have no idea why it was removed)

**Comment by emilieringwald** [comment]
We will have a look into this and let you know if it's on purpose or not, and therefore if / when we'll add it back for v4.
