### ISSUE TITLE
Forgot password mail  template not changed

### ISSUE THREAD

**Issue by techwebdev** [strapi/strapi#12263]
### Describe the bug
when I change from code mail templates it's not changed it gives the same output as put in the admin panel
![image](https://user-images.githubusercontent.com/63657518/150518545-efbea2f7-fad8-4a75-b439-e522ed649273.png)

### Steps to reproduce the behavior
add forgot-password template in config/email-templates/forgot-password.js

### Expected behavior
when the change mail from code it should display updates 

### System

- Node.js version: 14.17.1
- NPM version: 6.14.13
- Strapi version: 4.0.5
- Database: postgresql
- Operating system: macos

**Comment by iicdii** [comment]
Why and what did you change in `forgot-password.js`?
[The doc](https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#templating-emails) says you can update template in admin panel.

**Comment by techwebdev** [comment]
in strapi 3 there options because if I will change the server any time I need to copy-paste from the admin or if some time anything happened I need to make a template again so

**Comment by derrickmehaffy** [comment]
see This doc, you have to require that file and set it in your admin.js

https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#forgotten-password-email

Not a but

**Comment by techwebdev** [comment]
already added this in `config/admin.js`. please have a look. 
![image](https://user-images.githubusercontent.com/63657518/150679046-22e48193-1f7f-4709-b8ec-efc8888d670c.png)

![image](https://user-images.githubusercontent.com/63657518/150679110-6a869167-21fc-4a13-a53f-a3fdea6325fd.png)

**Comment by derrickmehaffy** [comment]
> already added this in `config/admin.js`. please have a look. ![image](https://user-images.githubusercontent.com/63657518/150679046-22e48193-1f7f-4709-b8ec-efc8888d670c.png)
> 
> ![image](https://user-images.githubusercontent.com/63657518/150679110-6a869167-21fc-4a13-a53f-a3fdea6325fd.png)
> 
> @derrickmehaffy can you check anything i did wrong

That does look correct, what does the email look like that it sends?

**Comment by techwebdev** [comment]
it's same display which we add from strapi admin panel @derrickmehaffy

**Comment by C4rlit0** [comment]
Hey !
Same problem here ! 
Please update the docs or fix this bug, we can't update the email template from with steps explained here :
https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#forgotten-password-email

Thanks for your help !

**Comment by derrickmehaffy** [comment]
> Hey ! Same problem here ! Please update the docs or fix this bug, we can't update the email template from with steps explained here : https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#forgotten-password-email
> 
> Thanks for your help !

can you open an issue on the documentation repo: https://github.com/strapi/documentation

Thanks!

**Comment by EugeneVigonny** [comment]
Are there any updates on this issue? It looks like this error still exists

**Comment by lucaslacerdacl** [comment]
This question should be open.
