### ISSUE TITLE
Starting brand new Strapi attempts Mongo as database 

### ISSUE THREAD

**Issue by hilyin** [strapi/strapi#12270]
### Starting brand new Strapi attempts Mongo as database instead of SQLite

When attempting to start a brand new Strapi install using docker-compose as shown here https://strapi.io/blog/how-to-self-host-your-headless-cms-using-docker-compose it attempts to use a non-existant mongo database instead of SQLite.

### Steps to reproduce the behavior

Create docker-compose.yml with the contents:
```
version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
```

Run `docker-compose up`

Observe infinite loop of database connection tries to a nonexistent mongo database.

```
⇒  docker-compose up
Starting strapi-tester_strapi_1 ... done
Attaching to strapi-tester_strapi_1
strapi_1  | 🚀 Starting to create your Strapi application.
strapi_1  |
strapi_1  | Database determined by CLI args: mongo
strapi_1  |
strapi_1  | ⏳ Testing database connection...
strapi_1  | It might take a minute, please have a coffee ☕️
strapi_1  | (node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
strapi_1  | ⚠️  Database connection has failed! Make sure your database is running.
strapi_1  |
strapi_1  | ⏳ Testing database connection...
strapi_1  | It might take a minute, please have a coffee ☕️
strapi_1  | ⚠️  Database connection has failed! Make sure your database is running.
strapi_1  |
strapi_1  | ⏳ Testing database connection...
strapi_1  | It might take a minute, please have a coffee ☕️
strapi_1  | ⚠️  Database connection has failed! Make sure your database is running.
strapi_1  |
strapi_1  | ⏳ Testing database connection...
strapi_1  | It might take a minute, please have a coffee ☕️
strapi_1  | ⚠️  Database connection has failed! Make sure your database is running.
strapi_1  |
strapi_1  | ⏳ Testing database connection...
strapi_1  | It might take a minute, please have a coffee ☕️
strapi_1  | ⚠️  Database connection has failed! Make sure your database is running.
```

### Expected behavior

Expecting Strapi to create a fresh SQLite database and connect to it and continue startup process.

### System

- Node.js version: Current one used in Strapi's dockerfile.
- NPM version: Current one used in Strapi's dockerfile.
- Strapi version: Latest Dockerfile used from `strapi/strapi`
- Database: n/a
- Operating system: MacOS 11.6, Docker version 20.10.8

**Comment by derrickmehaffy** [comment]
We don't currently offer a v4 docker container, it's coming soon but this isn't related to the Strapi code-base specifically

cc @Mcastres @yvesdo
