### ISSUE TITLE
Changing JWT Configuration Expiry in security.json has no effect

### ISSUE THREAD

**Issue by jpizzle34** [strapi/strapi#12272]
### Describe the bug

Changing the default JWT expiry via ```extensions/users-permissions/config/security.json``` as described in the [docs](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue) has no effect on the expiry of any JWT's generated by Strapi.

### Steps to reproduce the behavior

1. ```yarn create strapi-app my-strapi-app```
2. ```yarn develop```
3. Create ```extensions/users-permissions/config/security.json``` containing the following:
```
{
  "jwt": {
    "expiresIn": "1d"
  }
}
```
4. Restart strapi server.
5. Create a new user in Strapi admin UI or via API.
6. Login as the new user via the API:
```
HTTP POST  /api/auth/local
Body:
{
    "identifier": "user@example.com",
    "password": "53cr3t"
}
```
7. Extract and decode JWT from API response and extract `exp` timestamp.

Expiry is 30 days (Strapi default) from when JWT was issued.

### Expected behavior

JWT expiry timestamp minus JWT issue timestamp should be equal to the `expiresIn` time interval defined in ```.../security.json```

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Yarn version: 3.1.1
- Strapi version: v4.0.5
- Database: SQLite
- Operating system: Ubuntu 21.10

**Comment by Elduwani** [comment]
I've had this same issue since upgrading to v4. Expiry is always 30days regardless of what's in security.json

**Comment by DevToong** [comment]
Create src/extensions/users-permissions/strapi-server.js
in strapi-server.js input
`"use strict";
const config = require("./server/config");
module.exports = (plugin) => {
  plugin.config = config;
  return plugin;
};
`
And  
Create src/extensions/users-permissions/server/config.js
in config.js input
`"use strict";

module.exports = {
  jwt: {
    expiresIn: "4d",
  },
};
`
Sorry, I'm not good at English.

**Comment by TumTumMai** [comment]
Create src/extensions/users-permissions/strapi-server.js
in strapi-server.js input

"use strict";
const config = require("./server/config");
module.exports = (plugin) => {
plugin.config = config;
return plugin;
};

And
Create src/extensions/users-permissions/server/config.js
in config.js input

"use strict";
module.exports = {
jwt: {
expiresIn: "4d",
},
};

Sorry, I'm not good at English.

**Comment by derrickmehaffy** [comment]
We don't use .json files anymore, and @TumTumMai is correct

**Comment by Elduwani** [comment]
On inspection the config object in the plugin has other relevant attributes, and all that needs to be changed here is the jwt key. What worked in strapi-server.js is

module.exports = (plugin) => {
  plugin.config.jwt = config.jwt
  return plugin
}

**Comment by georgeraveen** [comment]
I was able to solve this by following this [article  ](https://medium.com/@arnaud512/change-jwt-expiration-in-strapi-3-x-a39713979c20)

**Comment by ANGdesarrollo** [comment]
How can i put for less than a day?
