### ISSUE TITLE
When I select PostgresQL, I get "Connection test failed: connection ECONNREFUSED 127.0.0.1:5432".

### ISSUE THREAD

**Issue by jtaxiexpress** [strapi/strapi#12273]
### Describe the bug

When I select PostgresQL, I get "Connection test failed: connection ECONNREFUSED 127.0.0.1:5432".

### Steps to reproduce the behavior
"npx create-strapi-app@3.6.8 New Gatsby".
Run this, proceed as follows.
>Manual

Do you want to use a template? (A template is a strapy configuration designed for a specific use case.)
>Y

>Blog

Select the default database client.
>postgres

>Host: 127.0.0.1
>Port: 5432
>username: postgres
>Password: ********
> Enable SSL connection. (y/N) y

### System

- Node.js version: 14.18.1
- NPM version:6.14.15
- Strapi version: 3.6.8
- Database:postgres
- Operating system: mac bigsurer arm

### Additional context
I sent a ping to 127.0.0.1.
I got a reply.

I'm using gatsby.
I prefer to use v3.6.8 if possible, because strapi v4.x.x messes up the graphQL values.

**Comment by derrickmehaffy** [comment]
The database is refusing the connection, not a bug that we can fix without knowing why it refused the connection. Most likely using a self-signed certificate when the user selected yes on SSL. Normally locally installed PG servers don't have SSL enabled.
