### ISSUE TITLE
Find in Natural Language

### ISSUE THREAD

**Issue by denerFernandes** [strapi/strapi#1227]
**Informations**
- **Node.js version**: 8.6
- **npm version**: 5.7.1
- **Strapi version**: 3.12
- **Database**: MongoDB
- **Operating system**:Ubuntu 17.04

**What is the current behavior?**
I have an collection in portuguese, how to find in Natural Language? 

How to search for cafe(coffee), feijao (beans) and results for café, feijão?

**Steps to reproduce the problem**

GET ?alimento_contains=cafe

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
@denerFernandes Can you precise your issue please. I don't really understand it.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
