### ISSUE TITLE
[v4.0.5] event.state does not get passed from beforeXxx to afterXxx as documentation suggests

### ISSUE THREAD

**Issue by sturatcliffe** [strapi/strapi#12271]
### Describe the bug

When defining content type lifecycle hooks, the documentation [here](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#declarative-and-programmatic-usage) suggests we should be able to share state between ```beforeXxx``` and ```afterXxx``` lifecycle hooks by setting and reading an object on the ```event.state``` property.

However, in practice this property is not passed to the ```afterXxx``` hook successfully, and is always ```undefined``` when checking it. 

### Steps to reproduce the behavior

1. Generate a new Strapi project with ```npx create-strapi-app@latest my-project --quickstart```
2. Once your project is up and running - create any test content collection type
3. Create an instance of the collection type you created at step 2, and hit save
4. In the ```src/index.js``` file, modify the ```bootstrap``` function to register a lifecycle hook:

```
bootstrap({ strapi }) {
    strapi.db.lifecycles.subscribe({
      models: [NAME_OF_YOUR_MODEL],

      beforeUpdate(event) {
        event.state = "doStuffAfterWards";
        console.log("BEFORE UPDATE: ", event.state);
      },

      afterUpdate(event) {
        console.log("AFTER UPDATE: ", event.state);
      },
    });
  }
```

5. After the server restarts from saving the ```src/index.js``` file, make an update to the instance of your model that you created in step 3, and hit save
6. Check the server console

### Expected behavior

Server console should output the following:

```
BEFORE UPDATE:  doStuffAfterWards
AFTER UPDATE:  doStuffAfterWards
```

### Actual behaviour

```event.state``` is always ```undefined```, so the server console outputs the following:

```
BEFORE UPDATE:  doStuffAfterWards
AFTER UPDATE:  undefined
```

### System

- Node.js version: v16.13.1
- NPM version: v8.1.2
- Yarn version: v1.3.2
- Strapi version: v4.0.5
- Database: N/A but Postgres
- Operating system: Windows 10 pro

### Additional context

Apologies if this should be a documentation update request, but I'm not sure if the documentation is wrong, or whether there is genuinely a bug with the event object.

Thanks in advance, and any tips on a workaround would be much appreciated!

**Comment by royalpinto** [comment]
Would be really helpful to have the user object in these events to know who did the action.

**Comment by kamal-choudhary** [comment]
I am also facing the same issue.

**Comment by derrickmehaffy** [comment]
There is a PR that adds this, in the short term you could use patch-package to apply that PR until we have time to review and merge

**Comment by ExploHash** [comment]
Same issue here

**Comment by kamal-choudhary** [comment]
Hi @ExploHash, the method suggested by @derrickmehaffy worked for me. Though, this is a temporary solution.

**Comment by dzcpy** [comment]
Same issue here. Hope it can be fixed soon

**Comment by wileyknight** [comment]
I created an object just above the module.export and used that to pass information around between update actions for the time being.

**Comment by derrickmehaffy** [comment]
Going to lock this, see my previous comment if you want support for State before we add it ourselves you can go look at the PR
