### ISSUE TITLE
The updated_at field doesn't update when a relation is created.

### ISSUE THREAD

**Issue by alonba** [strapi/strapi#12274]
# The updated_at field doesn't update when a relation is created.
I'll explain further -
I have a table of artworks that has a many-to-many relation with another table - buyers.
When a buyer buys an artwork, I need to connect the buyer's entry with the artwork's entry by updating the "buyers" field of the artwork.
Now, a connection is made - I have the buyer listed in the artwork's buyers list, and the artwork listed in the buyer's artworks list.
What's the problem? 
The field "updated_at" of the buyer wasn't updated. (Of course, the "updated_at" field of the artwork did change, as it should).

Now - the problem even gets worse. When updating the relation from the GUI, it updates the "updated_at" field only of one side of the relation, But when I update it using the API, none of the sides get "updated_at" gets updated.

## Steps to reproduce the behavior
1. Create a many-to-many relation between any two tables (I guess the problem would occur also with other types of relations).
2. Make a connection between an entry in the first table and the second (choose a buyer for your artwork)
3. Go to the second table entry (the specific buyer you chose on step 2) and see that the "updated_at" field didn't change. 

## Expected behavior
I'd expect the "updated_at" field to be updated on this scenarios.

### System
- Node.js version: 14.17.5
- NPM version: 7.21.0
- Strapi version: 3.6.8
- Database: sqlite
- Operating system: windows 10 64bit

**Comment by derrickmehaffy** [comment]
v3 related, we aren't fixing bugs on v3 that aren't critical or security related.

And the action is intended as that field is database related and some relations don't touch that table in v3 so technically speaking the table wasn't updated.

**Comment by alonba** [comment]
Is it different on V4?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by derrickmehaffy** [comment]
It's not different on v4 because those fields are controlled by the database, not Strapi. If the table is updated then the value in the database is updated: https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html

It has nothing to do with Strapi and we intentionally don't pass those values onto the database since we use the `ON UPDATE CURRENT_TIMESTAMP` option for the updatedAt field.
