### ISSUE TITLE
Normalize REST API response for "plugin::users-permissions.user"

### ISSUE THREAD

**Issue by soupette** [strapi/strapi#12280]
### Describe the bug

The REST API response for the "plugin::users-permissions.user" should be the same as any other model when using the content api.

### Steps to reproduce the behavior

1. Call the `http://localhost:1337/api/users` endpont
2. See the response

```json
[
    {
        "id": 1,
        "username": "bob",
        "email": "bob@strapi.io",
        "provider": "local",
        "confirmed": true,
        "blocked": false,
        "createdAt": "2022-01-24T07:58:39.177Z",
        "updatedAt": "2022-01-24T07:58:39.177Z"
    }
]
```

### Expected behavior

The response should follow the new v4 format:

```json
{
   "data": [
    {
        "id": 1,
        "attributes": {  
            "username": "bob",
            "email": "bob@strapi.io",
            "provider": "local",
            "confirmed": true,
            "blocked": false,
            "createdAt": "2022-01-24T07:58:39.177Z",
            "updatedAt": "2022-01-24T07:58:39.177Z"
        }
    }
  ]
}
}
```

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: v4.0.4
- Database: sqlite

**Comment by derrickmehaffy** [comment]
@alexandrebodin would "fixing this" be considered a breaking change? :thinking:

**Comment by soupette** [comment]
Yes I think so but it also makes it very complicated to use the API response when doing dynamic fetching, for instance in the `gatsby-source-strapi` v2 plugin we have to handle this content type differently than the others.

The API response also differs for the `/api/upload/files` and the `/api/i18n/locales` endpoints which makes them unsuable in Gatsby for instance.

**Comment by derrickmehaffy** [comment]
> Yes I think so but it also makes it very complicated to use the API response when doing dynamic fetching, for instance in the `gatsby-source-strapi` v2 plugin we have to handle this content type differently than the others.
> 
> The API response also differs for the `/api/upload/files` and the `/api/i18n/locales` endpoints which makes them unsuable in Gatsby for instance.

Even if it is a breaking change @soupette I really think we need to also, just wanted to ask as me and a few community users were discussing it in Discord yesterday.

**Comment by derrickmehaffy** [comment]
Last update I've had internally is we don't plan to address this in v4 as it would be a breaking change so it will have to wait til v5 or for when we replace U&P plugin with a replacement.

Going to lock this thread as we can't do anything about it right now.

**Comment by alexandrebodin** [comment]
Considering the plans to rework/replace this plugin in the mid term we will not be working on this in v5. Closing as it will be replaced
