### ISSUE TITLE
No option to deactivate Users & Permissions plugin, even though it is said in docs

### ISSUE THREAD

**Issue by kskrlinnorth2** [strapi/strapi#12286]
From docs https://docs.strapi.io/user-docs/latest/plugins/strapi-plugins.html#default-plugins "The Users & Permissions plugin is installed by default on all v4 Strapi applications, but can be deactivated.".

### Steps to reproduce the behavior

There is no such option in admin panel under plugins or any other settings page. There aren't also any clear true/false values in database to deactivate this plugin via database. I am not finding anything about it in files too.

### Expected behavior

To be able to deactivate or remove this plugin.

### Screenshots

As you can see, there are no action buttons to deactivate plugin:
![image](https://user-images.githubusercontent.com/61736280/150814407-9f9efd67-f1ff-44c3-a362-561e1df6eca5.png)

### System

- Node.js version: v16
- NPM version: v8
- Strapi version: v4
- Database: mysql
- Operating system: w11

**Comment by marianhlavac** [comment]
Disabling plugins is described in documentation here:

https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/plugins.html#graphql-configuration

**Comment by derrickmehaffy** [comment]
Or you just uninstall it `yarn remove @strapi/plugin-users-permissions` / `npm uninstall @strapi/plugin-users-permissions`

Not a bug

**Comment by kskrlinnorth2** [comment]
There is no plugins.js file

![image](https://user-images.githubusercontent.com/61736280/150940228-24075b42-34a9-4cd1-93ee-36bd20dd893f.png)

**Comment by derrickmehaffy** [comment]
> There is no plugins.js file
> 
> ![image](https://user-images.githubusercontent.com/61736280/150940228-24075b42-34a9-4cd1-93ee-36bd20dd893f.png)

you create it if it doesn't exist

**Comment by cpmuc** [comment]
Like this
 
`module.exports = ({ env }) => ({
  // enable a plugin that doesn't require any configuration
  'users-permissions': false,
});
`

But this still shows the login screen and registration options, is there a way to disable this as well?

**Comment by derrickmehaffy** [comment]
> Like this
> 
> ```
> module.exports = ({ env }) => ({
>   'users-permissions': false,
> });
> ```
> 
> But this still shows the login screen and registration options, is there a way to disable this as well?

That isn't the users-permissions plugin, it's the authentication for the admin then no you can't disable that.

**Comment by kskrlinnorth2** [comment]
I just removed it from package.json in the end.

**Comment by Zedonboy** [comment]
I am getting Missing credential error from all my APIs.

How do i make it public?

**Comment by biki** [comment]
> I am getting Missing credential error from all my APIs.
> 
> How do i make it public?

Same here. Removing the plugin from package.json still requires an API_TOKEN with proper rights set, even on GET routes. 
Any way to deactivate this fully?
