### ISSUE TITLE
GraphQL Playground does not work without `users-permission` plugin

### ISSUE THREAD

**Issue by marianhlavac** [strapi/strapi#12289]
After uninstalling the `users-permission` plugin the GraphQL playground breaks down and is not accessible.

* Visiting http://localhost:1337/graphql/ gives 401 response saying:

```
{"data":null,"error":{"status":401,"name":"UnauthorizedError","message":"Missing or invalid credentials","details":{}}}
```

* Using API key in headers and visiting the same URL ends up in 400 response saying:

```
GET query missing.
```

### Steps to reproduce the behavior

1. Install strapi using `create-strapi-app`
2. Install `graphql` plugin
3. Uninstall `users-permissions`
4. Access `http://localhost:1337/graphql`

### System

- Node.js version: v14.17.6
- Strapi version: 4.0.5
- Operating system: macOS

**Comment by qhoirulanwar** [comment]
i have same issue

before condision
i setup new strapi project & i restore table contain form my previus project  up_roles up_users up_users_role_link table

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.8

**Comment by JulianAtTheFrontend** [comment]
Still not working as of v4.3.4

**Comment by Bassel17** [comment]
> Still not working as of v4.3.4

what are you exactly facing ?

**Comment by JulianAtTheFrontend** [comment]
The server still responds "UnauthorizedError" "Missing or invalid credentials".
When I reactivate user-permissions plugin it works perfectly.

**Comment by Bassel17** [comment]
so you are not seeing the graphql playground ?

**Comment by JulianAtTheFrontend** [comment]
I can "see" the playground, but it doesn't connect to the server. (so no docs & schema visible)

**Comment by Bassel17** [comment]
@JulianAtTheFrontend oh yes that's the normal behavior, by default nothing is public, unless you use the users & permissions plugin and you specify them as public. so when you remove the users & permissions plugin you will need to use the Api Tokens, generate a token and use it to make your requests

**Comment by JulianAtTheFrontend** [comment]
Ah ok! Makes absolutely sense!

**Comment by bsdayo** [comment]
@Bassel17 Currently at 5.0.3, I can still reproduce this problem.

## Steps

- `pnpm create strapi`
- `cd my-strapi-project`
- `pnpm remove @strapi/plugin-users-permissions`
- `pnpm add @strapi/plugin-graphql`
- `pnpm run develop`
- Go to the admin panel and create an account
- Visit `http://localhost:1337/graphql`
- **Cannot** see the GraphQL playground page, receives this error:
    ```json
    {
        "data": null,
        "error": {
            "status": 401,
            "name": "UnauthorizedError",
            "message": "Missing or invalid credentials",
            "details": {}
        }
    }
    ```
    ![image](https://github.com/user-attachments/assets/fcf791d9-cf48-4e3a-81b0-4810efebb8dd)

**Comment by maxep** [comment]
Hey :wave: 

I'm also not able to access the playground in Strapi 5 (without user-permission). @alexandrebodin - as you mentioned a [complete rework](https://github.com/strapi/strapi/issues/14441#issuecomment-2026265218) of gql in v5 - is this a regression? or are we missing something?

**Comment by alexandrebodin** [comment]
@maxep It's not something I'm aware of. Can you open a new issue for v5 specificaly so it can be triage and reported to the team in charge please 🙏
