### ISSUE TITLE
Condition provider does not work as expected when the returned query contains a nested query (relation) 

### ISSUE THREAD

**Issue by adziok** [strapi/strapi#12295]
### Describe the bug
*Enterpise edition required to reproduce my case*
Condition provider does not work as expected when the returned query contains a nested query (relation).
In article list I recive list with good length (filtering work) but records are empty.

![image](https://user-images.githubusercontent.com/37898993/151002798-96dfc71b-52f1-4950-8372-cec6c6191e94.png)

I have tried several ways, but whenever the query contains a nested query I get the same result.

### Steps to reproduce the behavior

1. Go to 'backend/src/bootstrap.js'
2. Register `Condition provider` in module exports method.
```
  strapi.admin.services.permission.conditionProvider.register({
    displayName: 'Author filter',
    name: 'list-only-author-articles',
    plugin: 'admin',
    async handler(user) {
      return {
        author: {
          id: '__provide_author_id__',
        }
      };
    },
  });
```
3. Go to settings and add new condition to role
![image](https://user-images.githubusercontent.com/37898993/151004270-3ab097ca-8d84-4aec-a948-77ad7ee0ac76.png)

4. Log in to account with given role
5. Try to list articles (at least one should fulfill query returned in point 1)

### Expected behavior

List of articles

### System

- Node.js version: v16
- NPM version:8 .1.2
- Strapi version: v4.0.5
- Database: SQLite3
- Operating system: MacOs

**Comment by PierrePerrin** [comment]
Hi @adziok,

Actually, I'm facing the same issue right now. Have you managed to fix it? If so, how?

Thanks.

**Comment by manuelliebchen** [comment]
Hey did anyone fix it?
