### ISSUE TITLE
Add uuid as a primary key in any collection

### ISSUE THREAD

**Issue by JakubLog** [strapi/strapi#12292]
### Please describe your feature request

- **Just like in a title**
- **I use postgres and my collections in DB are with default id (auto-increment)**
- **I just want to change auto-increment option to UUID.**

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1762

**Comment by i4j5** [comment]
How to replace primary keys with UUID?
