### ISSUE TITLE
overriding default documentation does not work

### ISSUE THREAD

**Issue by salar-amr** [strapi/strapi#12296]
hello , I have a problem with strapi 4.0.4, and documentation 4.0.4^ , I replaced the default config of documentation plugin through these steps:
1- create strapi-server.js file in extensions/documentation 
2- change config property of plugin with my own custom config

I added users-permission plugin and it worked but changing the title, description ... does not work ,
most important creating override documentation for apis also does not work.

**Comment by george-rb2** [comment]
I got the same issue..
The setting are totally useless.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by salar-amr** [comment]
> > This is a templated message
> 
> Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> A proper issue submission let's us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue with the template and we can reopen this report.
> 
> Thank you.

I changed my comment to describe my issue better , and sorry for my weak english

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12046

**Comment by salar-amr** [comment]
> Duplicate: #12046

my issue is mostly about overrides folder for customizing suggested documents for apis which is not working, about the overriding config I found an easier way : 
.../plugin-documentation/server/services/documentation.js  line: 136

const settings = _.cloneDeep(defaultConfig);
should be replaced by this:
const settings = _.cloneDeep(config);
 
however about overriding api documentation i still did not come up with any solution

**Comment by Zedonboy** [comment]
@salar-amr did you solve your issue?

**Comment by filson14-mq** [comment]
@derrickmehaffy 
> Duplicate: https://github.com/strapi/strapi/issues/12046

This is definitely not a duplicate as linked issue is about swagger settings, not overriding API endpoits' response etc. That case seems still not solved while it is crucial, I guess. If we are not able to sync the documentation with all middlewares, plugins and customizations used in the API, it is a bit useless (with all due respect)

**Comment by dabrowskif** [comment]
@salar-amr Hello, did you solve your issue? Im struggling with this aswell.

**Comment by tirthshah574** [comment]
This is still not solved. I'm facing the same issue

**Comment by dassiorleando** [comment]
I second @tirthshah574, I still can't override my APIs using the documentation plugin.

**Comment by dassiorleando** [comment]
@tirthshah574 are you sure you used the `registerOverride` function provided by the **Documentation** plugin to perform overrides?

I tried and it worked, it's documented [here](https://docs.strapi.io/dev-docs/plugins/documentation).

**Comment by tirthshah574** [comment]
Yes, it's functioning correctly, but if you place the "doc" under the overrides folder, it doesn't work. To address this, I need to write custom code that fetches all files from the overrides folder, creates an object, and then passes it to the `registerOverride` function. This is necessary because we've made numerous customizations to the default Strapi APIs, so we have to override each API individually since by default it only creates documentation for every content type.

**Comment by markkaylor** [comment]
@tirthshah574 it sounds like you are migrating from v3 to v4? 
> but if you place the "doc" under the overrides folder, it doesn't work

This is by design. The doc plugin no longer reads from the filesystems based on a file structure convention as it did in v3.

> I need to write custom code that fetches all files from the overrides folder

That is one option, but I believe you could also just import them and then register them. Something like:

```js
// my-strapi-app/src/index.js or plugin register

import overrideA from '../api/someApi/override.json'
import overrideB from '../api/someApi/override.json'

...

register({ strapi }) {
	strapi.plugin('documentation').service('override').registerOverride({ ...overrideA, ...overrideB })
}

// or depending on the needs of each override register them individually

register({ strapi }) {
	const overrideService = strapi.plugin('documentation').service('override')
	overrideService.registerOverride(overrideA)
	overrideService.registerOverride(overrideB)
}
```

Hope that helps, feel free to open a new issue if something is not working as described in the documentation.
