### ISSUE TITLE
Can't create relation field with same collection type

### ISSUE THREAD

**Issue by teresas** [strapi/strapi#12299]
### Describe the bug

I have a collection type "News Items" and want to add a many-to-many relation field to other News Items. This way I can have a "Related News Items" list later. When I try to create the relation field, I get an error under the field name that says "This name exists in the target". If I change the name of one of the fields, I wind up with 2 related news items fields instead of 1.

### Steps to reproduce the behavior

1. Go to /admin/plugins/content-type-builder
2. Click "Create new collection type"
3. Type "News Item" in Display name input and click "Continue"
4. On "Select a field for you collection type" modal, click "Text"
5. On "Add new Text field" modal, type "title" in Name input and click "Finish"
6. Click "Save" and wait for server to restart
7. Click "Add another field to this collection type"
8. On "Select a field for you collection type" modal, click "Relation"
9. On "Add new Relation field" modal, select "News Item" from the select dropdown on the right
10. Click the many-to-many button option in the middle
11. Click "Finish"
12. See error
13. Change "Field name" on left to "other_news_items"
14. Click "Finish"
15. See that **two** relation fields have been added "other_news_items" and "news_items"

### Expected behavior

I would expect to be able to have a piece of content relate to other content of the same collection type without duplicate fields. In this case, the relation field names would be the same on both ends. When creating/editing an entry of type News Item, there should be a single relation field that should list all the content of the News Item type except for the entry currently being edited.

### Screenshots
 
![Screen Shot 2022-01-25 at 10 04 42 AM](https://user-images.githubusercontent.com/1242178/151029173-1f6a5524-2c1d-4ea1-87c1-a1b9e85c42f3.png)
![Screen Shot 2022-01-25 at 10 06 11 AM](https://user-images.githubusercontent.com/1242178/151029189-583e2c58-ff2a-43ba-90da-3bd27191e8fa.png)

### System

- Node.js version: v14.18.1
- NPM version: 7.6.0
- Strapi version: v3.6.6
- Database: Postgress
- Operating system: macOS Big Sur 11.6.2

### Additional context

My end goal is to have a list of "Related News Items" on an individual News Item's page.

**Comment by derrickmehaffy** [comment]
Please test in v4 as we don't support the v3 anymore unless it's for critical or security related issues.
