### ISSUE TITLE
Option for enable/disable created/update_by_id in schema.json

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#12302]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Option for enable/disable created/update_by_id in content-type's schema.json

### Why is it needed?

Some tables don't need these fields, such like admin_permissions table.

### Suggested solution(s)

Add some options like "createByUser/updatedByUser" in "options".

**Comment by derrickmehaffy** [comment]
Engineering decided to enforce this on all tables as there is no reason to not include it at this point, it's much easier to just set this as enabled and not worry about needing it later for something.
