### ISSUE TITLE
Make the BoundRoute section sticky in the Roles editor

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12300]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Stick the BoundRoute component to its position when scrolling down in the Roles editor.

### Why is it needed?

When many permissions are present, you have to scroll up to check the route that's bound to the specific permission you are editing. If the BoundRoute component were sticky, users would always have the path on-screen.

### Screenshots

Before
![image](https://user-images.githubusercontent.com/34224657/151067758-e64fcb9c-9648-4fa4-b0a8-c9da398b0ee9.png)

After
![image](https://user-images.githubusercontent.com/34224657/151067694-98a30f72-dc60-482f-9d69-1fb15a4c5bf2.png)

**Comment by derrickmehaffy** [comment]
Heck yes, pleaseeeeeeee

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/make-the-boundroute-section-sticky-in-the-roles-editor

Thanks!
