### ISSUE TITLE
V4. Add count to graphql

### ISSUE THREAD

**Issue by celsoft** [strapi/strapi#12315]
V4. 
Hello 👋 Add count to graphql.

**Comment by WalkingPizza** [comment]
You can already count items in a collection with something like this:
```gql
{
  restaurants {
    meta {
      pagination {
        total
      }
    }
  }
}
```

**Comment by celsoft** [comment]
Ok. How to count relations?

**Comment by kasonde** [comment]
Hi thanks for the question. I'm closing this here however since it's not an issue but a question that is perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.

**Comment by celsoft** [comment]
> Hi thanks for the question. I'm closing this here however since it's not an issue but a question that is perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.

https://forum.strapi.io/t/v4-please-show-code-example-how-to-return-count-function-in-gql/14951

I'll be waiting for your response. Thank you.
