### ISSUE TITLE
`strapi generate` accepts invalid names

### ISSUE THREAD

**Issue by Paratron** [strapi/strapi#12311]
When using `strapi generate` you are able to provide names for plugins (maybe also other elements) which are refused by Strapi as being invalid.

If the name is not `formatted-like-this`, Strapi won't boot since it says the name of a plugin should be in kebab-case. The generate script accepts any name format happily, tough.

### Expected behavior

The generate script should pass the provided name to the validator.

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by Paratron** [comment]
Sorry, what?

This is not a bug report but a friendly reminder that something has been forgotten - namely to check if the provided plugin names are valid after all.

99% of the bug template is unnecessary because the information is not needed.

I understand the benefits of bug templates but this is a little bureaucratic, dont you think?

**Comment by Paratron** [comment]
Thanks for the comment! You are doing a good job as issue manager 👍

I will try to update the text when I have some free time.
