### ISSUE TITLE
Multiple users can sign up with the same username

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12319]
### Describe the bug

Multiple users can sign up with the same username through `api/auth/local/register`.

### Steps to reproduce the behavior

1. Create a user through a POST request to `api/auth/local/register` with username `foo`.
2. Repeat step 1 ensuring the email you use in the POST data is different.
3. Notice how two users are created and both have `foo` as their username.

### Expected behavior

Requests should fail when there is already a user with username `foo`.

### Screenshots

![image](https://user-images.githubusercontent.com/34224657/151212740-3ad4c3ed-3d34-4f21-8cbb-2764aa3150bb.png)

### Code snippets

Example POST requests to `api/auth/local/register`

```json
{
    "username": "Test",
    "email": "test@me.com",
    "password": "test"
}
```

```json
{
    "username": "Test",
    "email": "test2@me.com",
    "password": "test"
}
```

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Yarn version: 1.22.15
- Strapi version: 4.0.5
- Database: PostgreSQL
- Operating system: Alpine

### Additional context

Probably related to my other issue, #12301.

**Comment by Emeka-Ugbanu-hub** [comment]
I would love to help with this

**Comment by yanniskadiri** [comment]
Thanks for highlighting this - @Emeka-Ugbanu-hub @WalkingPizza let us know if you work on this, we'll also explore it in the coming weeks!

**Comment by WalkingPizza** [comment]
> Thanks for highlighting this - @Emeka-Ugbanu-hub @WalkingPizza let us know if you work on this, we'll also explore it in the coming weeks!

I have actually already attached a PR that should fix this. Let me know what you think once you get a chance to look at it.

Thanks!

**Comment by yanniskadiri** [comment]
Indeed thanks! We'll have a look :)

**Comment by Krito1997** [comment]
Has this issue been fixed yet?

**Comment by Krito1997** [comment]
I would love to work on this issue

**Comment by alexandrebodin** [comment]
Hey Actually this was fixed I think. The username has to be unique now so you can't create multiple times the same username. You can still mix username & email but I'm going to do some updates to handle it better though. @WalkingPizza can you test this again and close if you have the same conclusions ?
