### ISSUE TITLE
Not able to fetch relation/images using gatsby-source-plugin

### ISSUE THREAD

**Issue by mayankraipure11** [strapi/strapi#12316]
Relation -->. 
## Bug report
Not able to fetch relations/images even when I pass populate as query string in **gatsby-source-strapi** plugin.
### Describe the bug
 {
      resolve: `gatsby-source-strapi`,
      options: {
        apiURL: `http://localhost:1337/api`,
        collectionTypes: [{
          name: `contact`,
          api: { qs: { _populate:`*` } }
        }],
      },
    },
Using graphQL I am not able to fetch images/relations 
### Expected behavior

When I use http://localhost:1337/api/ipos?populate=* directly in browser it gives me relations of 1 level but do not get images.
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.17.3
- NPM version: 6.14.13
- Strapi version: 4.0.4
- Database: postgres
- Operating system: Mac
- Gatsby version: ^4.4.0"
-  gatsby-source-strapi: ^1.0.2",

**Comment by kasonde** [comment]
This plugin does not support v4 yet. There is a notice on the plugin [repository page.](https://github.com/strapi/gatsby-source-strapi)
