### ISSUE TITLE
Transaction in strapi

### ISSUE THREAD

**Issue by lfcc1** [strapi/strapi#12326]
Hello,
I'm new on strapi and I'm investigating if I should start using it or not. 
Until now, I could replicate most of the functionality I need, however, I was not able to create a MySQL transaction.
I have searched in the documentation and forums but I was not able to find an example of how to create a transaction so I can commit multiple queries and rollback if something has gone wrong.
Is there any solution for this?

Thank you.

**Comment by kasonde** [comment]
Hi thanks for the question. I'm closing this here however since it's not an issue but a question that is perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.
