### ISSUE TITLE
Periodic 401 error on same request

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#12325]
### Describe the bug
If I submit the same request several times to strapi, about 1 in 5 times I get a 401 unauthorized error. However then the same request works.

### Steps to reproduce the behavior

1. Get JWT
2. Do a Get request to an authenticated endpoint
3. Repeat same request several times
4. Will get sporadic 401 errors

### Expected behavior

Consistently get the same result

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14
- NPM version:
- Strapi version: v4
- Database: postgres
- Operating system: UNIX

**Comment by kasonde** [comment]
Hi @pcriadoperez, please share your **exact** Node, NPM and Strapi version. Additionally more details about how your application is deployed. Is it deployed on the cloud to a certain service? or locally?

**Comment by pcriadoperez** [comment]
Hi, It is deployed as a docker container in Google Cloud Run. I realized the issue is that I didn't have set the JWT_SECRET, so any new container was returning a 401 error. The issue is now fixed. Thanks for the quick response!
