### ISSUE TITLE
Changing port in `config/server.js` breaks admin

### ISSUE THREAD

**Issue by dodiameer** [strapi/strapi#12327]
### Describe the bug

Changing the port from 1337 to something else breaks the admin panel because some request like `/admin/project-type` are still being made to `localhost:1337`

### Steps to reproduce the behavior

1. Create new project using `yarn create strapi-app project --quickstart`
2. Edit port in `config/server.js` to anything other than 1337 (e.g. 3001)
3. Run `yarn develop`
4. Go to admin page

### Expected behavior

See the admin panel normally, and start setting up my admin user

### Screenshots

Admin panel

![image](https://user-images.githubusercontent.com/61318540/151380099-d65e9605-955b-48d5-9bf3-2db53fa01272.png)

Failing request

![image](https://user-images.githubusercontent.com/61318540/151380364-e428502d-28cf-4483-9d50-aff9081cb190.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Yarn version: 1.22.17
- PNPM version: 6.26.1
- Strapi version: 4.0.5
- Database: SQLite
- Operating system: Windows 11

### Additional context

I tested on new projects created with NPM, PNPM, and Yarn. I ran into this issue in version 4.0.0 too but I gave up and didn't submit an issue back then.

**Comment by dodiameer** [comment]
I just did, I set it to `http://localhost:3001` but I still have the same issue

**Comment by dodiameer** [comment]
Okay, I managed to get it to work by running `pnpm build` and then `pnpm develop` and was able to create a user, but now going to:

- Content type builder
- Media Library
- Their settings page
- Any of the User permissions plugin setting pages

presents me with a white page and and error in the console: `TypeError: Cannot read properties of undefined (reading 'allPermissions')`

**Comment by dodiameer** [comment]
This looks like it's a common issue and it's not related to changing the port, so I'm closing this issue.

**Comment by chenjiangui** [comment]
same problem
