### ISSUE TITLE
Passwords are not validated upon user creation

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12320]
### Describe the bug

When signing up through the REST API, users can set their password to whatever they like, without any checks on how long the password is and what characters it contains. On the other hand, creating a user in the content manager is not possible unless the specified password is at least 6 characters long.

### Steps to reproduce the behavior

1. Create a user through a POST request to `api/auth/local/register` with password `a`.
2. Notice how the request is successful and the user is created.
3. Try creating another user through the Content Manager with password `a`.
4. Notice how the system won't create the user until you specify a password that is at least 6 characters long.

### Expected behavior

Requests to `/api/auth/local/register` should require a password that is at least 6 characters long.
Or, in general, the fields specified in the request should undergo the same checks they undergo when the action is performed in the content manager.

### Screenshots

![image](https://user-images.githubusercontent.com/34224657/151214617-4eba60c6-16c4-4bed-8693-4b8b9ae9cc81.png)

### Code snippets

Example POST requests to `api/auth/local/register`

```json
{
    "username": "Test",
    "email": "test@me.com",
    "password": "a"
}
```

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Yarn version: 1.22.15
- Strapi version: 4.0.5
- Database: PostgreSQL
- Operating system: Alpine

**Comment by WalkingPizza** [comment]
Just stumbled upon #10705, which seems to describe the issue in a more general way, and has already been reviewed by the team, so I am closing this.

**Comment by kasonde** [comment]
@WalkingPizza thanks!
