### ISSUE TITLE
App getting crashed when hitting the api's for different collection types - digital ocean app platform

### ISSUE THREAD

**Issue by lowkeyAngry** [strapi/strapi#12333]
The app is hosted on the Digital Ocean App Platform with Postgres as DB.

I added this code in **src/helpers/populate.js** to populate all the data using the REST API.

```
const { isEmpty, merge } = require("lodash/fp");

const getModelPopulationAttributes = (model) => {
  if (model.uid === "plugin::upload.file") {
    const { related, ...attributes } = model.attributes;
    return attributes;
  }

  return model.attributes;
};

const getFullPopulateObject = (modelUid, maxDepth = 20) => {
  if (maxDepth <= 1) {
    return true;
  }
  
  if (modelUid === "admin::user") {
    return undefined;
  }

  const populate = {};
  const model = strapi.getModel(modelUid);
  for (const [key, value] of Object.entries(
    getModelPopulationAttributes(model)
  )) {
    if (value) {
      if (value.type === "component") {
        populate[key] = getFullPopulateObject(value.component, maxDepth - 1);
      } else if (value.type === "dynamiczone") {
        const dynamicPopulate = value.components.reduce((prev, cur) => {
          const curPopulate = getFullPopulateObject(cur, maxDepth - 1);
          return curPopulate === true ? prev : merge(prev, curPopulate);
        }, {});
        populate[key] = isEmpty(dynamicPopulate) ? true : dynamicPopulate;
      } else if (value.type === "relation") {
        
        const relationPopulate = getFullPopulateObject(
          value.target,
          maxDepth - 1
        );

        if (relationPopulate) {
          populate[key] = relationPopulate;
        }
      } else if (value.type === "media") {
        populate[key] = true;
      }
    }
  }
  return isEmpty(populate) ? true : { populate };
};

module.exports = getFullPopulateObject;
```

The API endpoints that do not have the controller override with this function are working fine in the app platform and are giving the response, but that is not the case with other endpoints where I have used this function for deep populate, and is giving me this error, see the below screenshot:

![image](https://user-images.githubusercontent.com/72743092/151487341-a9d03ca5-5145-415d-ab75-92605389e4eb.png)

There are no errors in the run time logs in the DO app. Also, everything is working fine locally. Have no idea why this is happening. Any help is appreciated, Thanks!!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
