### ISSUE TITLE
Content type name disappears in add relation window on Firefox

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1233]
**Informations**
- **Node.js version**:v10.1.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:Mongo
- **Operating system**:Linux

**What is the current behavior?**
Content type name disappears in add relation window

**Steps to reproduce the problem**
See this:
![strapi 1](https://user-images.githubusercontent.com/25859075/40264314-9600892e-5b35-11e8-97ff-1907cc7cca49.gif)

**What is the expected behavior?**
We need to know both side content type name for create a relation.

**Suggested solutions**
---

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hi @mnlbox can you tell me if it still happen with `3.0.0-alpha.12.2` version (with fresh project)

**Comment by lauriejim** [comment]
@mnlbox Can you give me the browser you use please.

**Comment by lauriejim** [comment]
@mnlbox any update please.

**Comment by soupette** [comment]
@lauriejim I ran into the issue last week. I'm taking care of fixing it

**Comment by mnlbox** [comment]
Thanks @soupette .
So I think you can move this to 12.4 milestone.

**Comment by lauriejim** [comment]
Still can not reproduce it with last version of Strapi. Need precise steps to reproduce.

**Comment by mnlbox** [comment]
It's always like this man. I just do normal step to create a relation. :thinking: 
I'm using Firefox. Is it matter?

**Comment by derrickmehaffy** [comment]
@mnlbox if you try this on Chrome does the same issue still happen? Can you provide your Firefox version number?

**Comment by mnlbox** [comment]
@derrickmehaffy I'm using Firefox version 60.0.2. I can check new version and tell result here.

**Comment by lauriejim** [comment]
Does it work for you with Google Chrome ?

**Comment by mnlbox** [comment]
@lauriejim yes it's working well on chromium but not dosplay correct in Firefox.

**Comment by derrickmehaffy** [comment]
@mnlbox can you test with Strapi 14.1.1 want to make sure this issue is still happening
