### ISSUE TITLE
Naming a component as plural of other component throws error

### ISSUE THREAD

**Issue by 13milliseconds** [strapi/strapi#12330]
### Describe the bug

After creating a Photo component that consist of an image and a text box for single images I create a Photos component to repeat the Photo and add settings such as columns. I can create this new component but when using it in the Content Manager I am not allowed to save. 

Console reads `table components_media_photos has no column named columns`.
Changing the collectionName from components_media_photos to components_media_gallery fixes this.

### Steps to reproduce the behavior

1. Create component "name"
2. Create different component "names"
3. Try to use it in the content manager

### Expected behavior

Obviously setting the new name as a plural of another component was bad practice in the first place but Strapi should not allow you to do this. Adding an alert such as `Name already in use` would fix this. 

### System

- Node.js version: 16.13.2
- Strapi version: 4.0.2   
- Operating system: OSX Monterey

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1198

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198
