### ISSUE TITLE
strapi-plugin-upload: breakpoints doesn't work

### ISSUE THREAD

**Issue by Jimmylet** [strapi/strapi#12338]
### Describe the bug

The pull request https://github.com/strapi/strapi/pull/9002 add the ability to add breakpoints from config/plugin.js.
Doc: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration

### Steps to reproduce the behavior

1. create config/plugin.js
2. Add the code in the example of the documentation  (https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration)
3. Restart the server
4. Upload a file

### Expected behavior

I created several specific thumbnails. None added in public/uploads.

### Code snippets

My plugin.js
```
module.exports = ({ env }) => ({
  upload: {
    config: {
      breakpoints: {
        xlarge: 1920,
        large: 1000,
        medium: 750,
        small: 500,
        xsmall: 64
      },
    },
  },
});
```
### System

- Node.js version: v14.15.5
- NPM version: 6.14.11
- Strapi version: 4.0.5
- Database: mysql
- Operating system: Mac OS

**Comment by Webbist-dev** [comment]
I've seen no issue with breakpoints. The images generated will be whatever size you upload down depending on initial size. Afaik they do not scale up. This will only work on images uploaded after you've added the configuration.

**Comment by Jimmylet** [comment]
@Webbist-dev , I started with a fresh install. It does not work. I'm uploading 4k images and I don't have new thumbnails in my public/uploads file.

While researching, I discovered that I was not the only one. A person on the strepi forum recently asked the question of why it wasn't working but got no answers.

https://forum.strapi.io/t/how-to-resize-uploaded-images-to-custom-sizes/4064/8

I have followed the documentation and nothing is happening.

**Comment by Webbist-dev** [comment]
Im using a provider for uploads in 4.0.5 and have all generated images output to my image buckets. Perhaps it's a local uploads issue.

Thanks,
Alex
________________________________

**Comment by Jimmylet** [comment]
@Webbist-dev , strange.
I just overwritten the configuration of the image-manipulation.js file (in node_modules) and it works… 

```
const DEFAULT_BREAKPOINTS = {
  large: 1000,
  medium: 750,
  small: 500,
  xsmall: 64 <---- NEW
};
```

I conclude that it is the link with the new plugin.js file that does not work...
But why ? It should just work.

**Comment by Jimmylet** [comment]
@Webbist-dev , I just tried on another computer (under Mac Os too), and it still doesn't work. I tried with Node 14 and Node 16.

**Comment by ptzol** [comment]
You just simply misspelled the filename:  config/plugin**s**.js

**Comment by RemyMachado** [comment]
@Jimmylet 
I have the same problem. Why did you close the issue? Did you find a solution

**Comment by everythinginjs** [comment]
the same problem here
the below piece of code does not work I still get 1000 converted  even though I uploaded 1921 image

```
 upload: {
    config: {
      breakpoints: {
        xlarge: 1920,
        large: 1000,
        medium: 750,
        small: 500,
      },
    },
  },
```

**Comment by MindDesign** [comment]
Strapi wont create images for breakpoints larger than the original image. So make sure all images are larger than, or as large as, the biggest breakpoint.
