### ISSUE TITLE
Server returns an Internal Server Error when trying to send an email confirmation email to a user that doesn't exist

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12344]
### Describe the bug

When sending a POST request `auth/send-email-confirmation` containing an email that doesn't exist in the body, the server throws an Internal Server Error. 

### Steps to reproduce the behavior

1. Send a POST request to `api/auth/send-email-confirmation`, passing an email that is not linked to an existing user.
2. Notice how the server throws an Internal Server Error instead of handling the exception.

### Expected behavior

The server should return an Application Error just like it does when the email is not valid, the user is already confirmed or it is blocked.

### Code snippets

```bash
curl --location --request POST 'http://localhost:1337/api/auth/send-email-confirmation' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "idontexist@strapi.io"
}'
```

### System

- Node.js version: 16
- NPM version: 8.1.2
- Yarn version: 1.22.15
- Strapi version: 4.0.6
- Database: PostgreSQL
- Operating system: Alpine

### Additional context

Error happens in `/packages/plugins/users-permissions/server/controllers/auth.js` because the controller attempts to verify whether the user is confirmed before checking that the user actually exists. I have submitted a PR that prevents this.

Also, I know this is probably not super high prio, but I noticed that while the other controllers return readable error messages, this specific one returns what looks like error codes.

**Comment by derrickmehaffy** [comment]
Not sure we should say that the user doesn't exist as that may leak some information but I agree it shouldn't be a 500 error.

Confirmed on v4.0.7

**Comment by alexandrebodin** [comment]
Fixed since then ;)
