### ISSUE TITLE
Can't access direct Admin routes when developing the Admin with --watch-admin on v4.0.6

### ISSUE THREAD

**Issue by esiao** [strapi/strapi#12343]
### Describe the bug

When developing the admin pannel on Strapi v4.0.6 using `strapi develop --watch-admin` the admin pannel routes are not available directly. You need to go to `/admin/` first and then visit the sub-routes.

### Steps to reproduce the behavior

1. Run `yarn develop --watch-admin`
2. Go to admin `http://localhost:8080/admin/`
3. Click on Content Manager
4. You are redirected to `http://localhost:8080/admin/content-manager/collectionType/api::appointment.appointment?page=1&pageSize=10&sort=id:ASC`
5. Reload your page for an error. `Cannot GET /admin/content-manager/collectionType/api::appointment.appointment`
6. Try to access the page directly, you get the same error.

### Expected behavior

The page should show up without having to go through the `/admin/` route every time.

When developing a plugin the admin interface reloads which forces you to go back to the `/admin/` first and then access your screen again.
It does appear there's another issue, I can't access Strapi with http://localhost:8000 but can with http://localhost:8080.
I upgraded this morning, it was working with v4.0.5 but I had to log into the Admin each time.

### Screenshots

<img width="1792" alt="Screen Shot 2022-01-28 at 11 54 14 AM" src="https://user-images.githubusercontent.com/1942801/151612657-985b59c5-5fce-4ea4-846c-8acf3f327b9f.png">

### System

- Node.js version: v14.17.5 through nvm
- NPM version: 6.14.14
- Strapi version: v4.0.6
- Database: PostgreSQL
- Operating system: Mac OS 12.1

**Comment by Prooksius** [comment]
Yes, the same

**Comment by creazy231** [comment]
Same problem, just want to update my plugin for the community - without success :(

**Comment by derrickmehaffy** [comment]
wasn't able to reproduce on v4.6.1
