### ISSUE TITLE
GraphQL Mutation Request to create new user fails with strange message

### ISSUE THREAD

**Issue by manjunathkg** [strapi/strapi#12347]
### Describe the bug
When trying to test graphql mutation requests in V4, get a strange exception that the type of input variable is the same as the type of expected variable. If so, it is not clear why this is an exception. There is no syntax error in the graphql mutation query.

### Steps to reproduce the behavior

1) Give create/update/delete permissions to authenticated role and launch graphql at http://localhost:1337/graphql. Get Bearer token for a user with authenticated role so that graphql commands are authorized.
2) Try to create a new user with mutation request below
 mutation createNewUser($input: UsersPermissionsUserInput) {
  createUsersPermissionsUser(data: $input){
    data {
      id
      attributes {
        username
        email
      }
    }
  }
}
3) Set the input data structure as below in query variables
{
  "input": {
    "username": "g3h3",
    "email": "g3@h3.com",
    "password": "12345"
  }
}
4) Run the mutation query. It errors out with a strange error.  Note that the input type is the same as the expected type and it errors out with

"Variable \"$input\" of type \"UsersPermissionsUserInput\" used in position expecting type \"UsersPermissionsUserInput!\".",

### Expected behavior

Should have created a User of type "UsersPermissionsUser"

### Screenshots

![Screen Shot 2022-01-29 at 2 51 43 PM](https://user-images.githubusercontent.com/1911858/151655574-52810757-a99b-493e-a28a-febb22f9eb9b.png)

### Code snippets

-NA-

### System

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: V4.0.0
- Database: postgres
- Operating system: Mac

**Comment by Convly** [comment]
Hi, as it is stated in your error message, your input variable type mismatch the one expected by the schema

> "Variable "$input" of type "UsersPermissionsUserInput" used in position expecting type "UsersPermissionsUserInput!".",

Try adding a "`!`" at the end of the `UsersPermissionsUserInput` type (on the first line in your mutation)

Let me know if it fixed your issue :slightly_smiling_face:

**Comment by kasonde** [comment]
Closing per @Convly 's comment.
