### ISSUE TITLE
Strapi crashes after upgrading to 4.0.6

### ISSUE THREAD

**Issue by Igal-Kleiner** [strapi/strapi#12357]
### Describe the bug

I upgraded Strapi to 4.0.6 and found out that when I want to edit some of the collection types entries (not all of them, but some), Strapi crashes and I’m getting the following errors in the console:
![4 0 6](https://user-images.githubusercontent.com/1457782/151761086-2617d834-d3f2-46b8-b312-9fded528cab3.PNG)
I did follow the [migration guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.0.x-to4.0.6.html).

I tried to delete .cache and build folders, rebuilt Strapi - same result.
I downgraded back to 4.0.5, rebuilt - everything works just fine.Upgraded again to 4.0.6 - crash.
I think that it crashes on entries that have a multimedia field in them, or a multimedia file in rich text editor, though I’m still not entirely sure of that.

### Steps to reproduce the behavior

1. While using 4.0.5, create some collection types with multimedia fields, image, single. 
2. Create some entries and upload images (in my case I use S3 as provider)
3. Upgrade to version 4.0.6, rebuild, run Strapi.
4. In the admin panel try to edit one of the entries with multimedia fields.

### Expected behavior

Have to be able to edit entries as usual, the app should not crash.

### System

- Node.js version: v14.15.0
- NPM version: v6.14.8
- Strapi version: 4.0.6
- Database: Amazon RDS PostgreSQL
- Operating system: Win10

### Additional context

As I stated above, I'm not entirely sure that the problem is with entries that have multimedia fields. If needed, I'm OK with having a Zoom talk and share my screen to demonstrate the issue.

**Comment by rowild** [comment]
I just upgrade to 4.0.6, too, while re-working the "Deliveroo Clone" tutorial, which has multimedia and rich-text fields. Everything works fine (on localhost with SQLite, Note 14.18.3, npm 8.3, yarn 1.22.17, MacOS Catalina): Also could change text in richt-text fields on a remote Heroku/PostGres Installation (but couldn't text images, since AWS S3 is not working yet).

**Comment by Igal-Kleiner** [comment]
@rowild 
Yeah, as I said, I'm not entirely sure the issue is with entries containing multimedia fields. I am able to edit some collection types, but it crashes on the others. Just checked again, and it seems multimedia fields is what these collection types have in common, as the app crashes on these collection types only.

**Comment by rowild** [comment]
@Igal-Kleiner Yes, I understood. Just wanted to test your scenarios and provide some feedback. – When talking about multi media fields, do you use images only or are there any other types involved, too (video, audio)? Do you have the same problem on localhost?

**Comment by Igal-Kleiner** [comment]
@rowild For now I used only images. Videos are planned in the future, but I'm still far away from that.
I tried to remove the S3 plugin and upload an image directly, but the app still crashed. I tried to access Media Library, and also wasn't able, got the following errors:
![media-library](https://user-images.githubusercontent.com/1457782/151785656-b3dd5564-4338-4836-b94a-37ec866be28d.PNG)
Also unable to access Roles or Providers in 'USERS & PERMISSIONS PLUGIN' in the Settings page, also getting this `TypeError: Cannot read properties of undefined (reading 'allPermissions')` error message.

**Comment by rowild** [comment]
@Igal-Kleiner you wrote you deleted .cache and build - have you also tried to delete node_modules? Also, do you have the same troubles on localhost?

**Comment by Igal-Kleiner** [comment]
@rowild 
Upon your suggestion I tried to delete node_modules as well (along with the other 2 directories). Alas, same result.
And I am running on localhost only, the project is still under development, no production yet.
Next step I can try - have a completely new installment of Strapi and then try to move all the collection types to it.

**Comment by rowild** [comment]
I thought it's remote, since the code is minified - sorry! 
Hard to find out the real problem, when everything is minified, though...
I wonder if going back to 4.0.5, creating a new admin, deleting the old one, and going back to 4.0.6 would do some magic? Probably not...

**Comment by rowild** [comment]
@Igal-Kleiner How about updating node? You use 14.15, but there is 14.18.3 available...

**Comment by Igal-Kleiner** [comment]
@rowild 
Well, upgrading node to 14.18.3 didn't help, still the same error. I did try to create a new project though. It looks like I am able to access media library, and all the uploaded images are there. I migrated the collection types, I can see them all in the admin panel. The problem is once I did that - Strapi deleted all the data from the DB, except the test users I created. I guess they simply rebuilt all the tables, without considering possible data existence. Now I'll have to create new entries, which will take me a while...

**Comment by kasonde** [comment]
Hi @Igal-Kleiner please share a snippet of your package.json file (removing any secret info of course)

**Comment by Igal-Kleiner** [comment]
@kasonde Here you go:
```lang-js
{
  "name": "backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "4.0.6",
    "@strapi/plugin-i18n": "4.0.6",
    "@strapi/plugin-users-permissions": "4.0.6",
    "@strapi/provider-upload-aws-s3": "^4.0.6",
    "@strapi/strapi": "4.0.6",
    "pg": "8.6.0",
    "slugify": "^1.6.5",
    "socket.io": "^4.4.1",
    "strapi-plugin-ckeditor5": "^2.0.0-rc.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "my-uuid-is-here"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

Meanwhile I must thank Amazon for their automated backup: restored a snapshot and the installation of Strapi is working. Still wonder what went wrong with the upgrade though...

**Comment by derrickmehaffy** [comment]
Please try these steps one more time:

- Delete `node_modules`
- Delete `.cache`
- Delete `build`
- Delete `package-lock.json` or `yarn.lock`
- Reinstall node modules
- Rebuild admin

And see if that works, my assumption is your lock files are caching stuff it shouldn't. There was also some admin improvements that likely could have broken ckeditor5 plugin, we don't test with 3rd party packages.

I couldn't reproduce this on a clean 4.0.5 => 4.0.6 upgrade but I didn't test with ckeditor

**Comment by jch-code** [comment]
> Please try these steps one more time:
> 
> * Delete `node_modules`
> * Delete `.cache`
> * Delete `build`
> * Delete `package-lock.json` or `yarn.lock`
> * Reinstall node modules
> * Rebuild admin
> 
> And see if that works, my assumption is your lock files are caching stuff it shouldn't. There was also some admin improvements that likely could have broken ckeditor5 plugin, we don't test with 3rd party packages.
> 
> I couldn't reproduce this on a clean 4.0.5 => 4.0.6 upgrade but I didn't test with ckeditor

These steps resolved a similar issue for me. Thanks!

I was getting the same `TypeError: Cannot read properties of undefined (reading 'allPermissions')` when accessing 'Content-Type Builder' and 'Roles' or 'Providers' under the 'USERS & PERMISSIONS PLUGIN'

Only tested locally at the moment as I have not upgraded on any deployed environments yet.

**Comment by derrickmehaffy** [comment]
> > Please try these steps one more time:
> > 
> > * Delete `node_modules`
> > * Delete `.cache`
> > * Delete `build`
> > * Delete `package-lock.json` or `yarn.lock`
> > * Reinstall node modules
> > * Rebuild admin
> > 
> > And see if that works, my assumption is your lock files are caching stuff it shouldn't. There was also some admin improvements that likely could have broken ckeditor5 plugin, we don't test with 3rd party packages.
> > I couldn't reproduce this on a clean 4.0.5 => 4.0.6 upgrade but I didn't test with ckeditor
> 
> These steps resolved a similar issue for me. Thanks!
> 
> I was getting the same `TypeError: Cannot read properties of undefined (reading 'allPermissions')` when accessing 'Content-Type Builder' and 'Roles' or 'Providers' under the 'USERS & PERMISSIONS PLUGIN'
> 
> Only tested locally at the moment as I have not upgraded on any deployed environments yet.

It's usually the lock files, everyone forgets to delete them and don't realize that a `yarn install` or `npm install` don't always automatically update them.

**Comment by derrickmehaffy** [comment]
I'm going to set this as closed unless someone else can confirm that doing the steps I mentioned in https://github.com/strapi/strapi/issues/12357#issuecomment-1027275782 don't work

**Comment by Igal-Kleiner** [comment]
> Please try these steps one more time:
> 
>     * Delete `node_modules`
> 
>     * Delete `.cache`
> 
>     * Delete `build`
> 
>     * Delete `package-lock.json` or `yarn.lock`
> 
>     * Reinstall node modules
> 
>     * Rebuild admin
> 
> 
> And see if that works, my assumption is your lock files are caching stuff it shouldn't. There was also some admin improvements that likely could have broken ckeditor5 plugin, we don't test with 3rd party packages.
> 
> I couldn't reproduce this on a clean 4.0.5 => 4.0.6 upgrade but I didn't test with ckeditor

Yup, can confirm that deleting the `package-lock.json` file and following the other steps did solve the issue, as previously I did try deleting only the above mentioned folders, not this file. Thank you very much!

**Comment by leidig54** [comment]
I'm getting this error on a fresh install as soon as I add the [strapi-provider-upload-google-cloud-storage](https://github.com/Lith/strapi-provider-upload-google-cloud-storage) plugin. I'm unable to load the admin panel past the login screen. 


```
main.5e9bbe39.js:2 TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.5e9bbe39.js:2:945847)
    at f (main.5e9bbe39.js:2:1187178)
    at s (main.5e9bbe39.js:2:1171361)
    at si (main.5e9bbe39.js:2:1936873)
    at Xu (main.5e9bbe39.js:2:1989170)
    at ks (main.5e9bbe39.js:2:1976411)
    at Ps (main.5e9bbe39.js:2:1976339)
    at Ss (main.5e9bbe39.js:2:1976202)
    at xs (main.5e9bbe39.js:2:1973168)
    at main.5e9bbe39.js:2:1922665
fu @ main.5e9bbe39.js:2
main.5e9bbe39.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.5e9bbe39.js:2:945847)
    at f (main.5e9bbe39.js:2:1187178)
    at s (main.5e9bbe39.js:2:1171361)
    at si (main.5e9bbe39.js:2:1936873)
    at Xu (main.5e9bbe39.js:2:1989170)
    at ks (main.5e9bbe39.js:2:1976411)
    at Ps (main.5e9bbe39.js:2:1976339)
    at Ss (main.5e9bbe39.js:2:1976202)
    at xs (main.5e9bbe39.js:2:1973168)
    at main.5e9bbe39.js:2:1922665
```

```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build -- --clean",
    "gcp-build": "strapi build -- --clean",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.0.7",
    "@strapi/plugin-users-permissions": "4.0.7",
    "@strapi/strapi": "4.0.7",
    "pg": "^8.7.3",
    "sqlite3": "5.0.2",
    "strapi-provider-upload-google-cloud-storage": "^4.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "52c1ee49-e23f-484c-9b21-f44096180cab"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by shin0602** [comment]
> I'm getting this error on a fresh install as soon as I add the [strapi-provider-upload-google-cloud-storage](https://github.com/Lith/strapi-provider-upload-google-cloud-storage) plugin. I'm unable to load the admin panel past the login screen.
> 

I was getting some error.
`.gcloudignore` add `yarn.lock` and rebuild fixed it.
