### ISSUE TITLE
GraphQL ApolloError misleading error message

### ISSUE THREAD

**Issue by HaruMiyaGi** [strapi/strapi#12350]
Sometimes, when doing my graphql queries I received `Class constructor ApolloError cannot be invoked without 'new'` error. However I found that error to be misleading, because on googling it I get solutions that don't do anything.

The fix is updating `packages/plugins/graphql/server/format-graphql-error.js` files line `47` from `return ApolloError('Internal Server Error', 'INTERNAL_SERVER_ERROR');` to `return new ApolloError('Internal Server Error', 'INTERNAL_SERVER_ERROR');`

**Comment by gvocale** [comment]
Running into the same issue
