### ISSUE TITLE
new user auth0 duplicate username error

### ISSUE THREAD

**Issue by logicminds** [strapi/strapi#12355]
### Describe the bug
If two new users sign up with emails jon@microsoft.com, and jon@google.com there is a unique username constraint where the 2nd account is never created.  The second account is never created because the username of jon
is taken already by the first user.   This occurs because the default auth0 signup only asks for email, password.

Furthermore there is no integration to verify if a username already exists as part of the auth0/user-permissions-users plugin.

### Steps to reproduce the behavior
1.  Setup auth0 for app
2. Register new user with auth0 provider `jon@example.com`
3. Register 2nd new user with auth0 provider ` jon@example2.com`
4. Check strapi logs for db errors

### Expected behavior

A second user would be created will different username

### Screenshots
<img width="389" alt="Screen Shot 2022-01-30 at 4 10 04 PM" src="https://user-images.githubusercontent.com/563900/151723736-8f646437-ec1b-4a0d-9d53-47c0b66f5f04.png">

### Code snippets

https://github.com/strapi/strapi/blob/v3.6.7/packages/strapi-plugin-users-permissions/services/Providers.js#L523

The issue is due to there is no username provided in the call that is unique to create the account. Everything falls back
to the nickname  Two usernames with the same name cannot
exist as a result.

```
  const username = body.username || body.nickname || body.name || body.email.split('@')[0];
              
```
Example payload from auth0
```json
{
    "created_at": "2022-01-30T23:03:22.872Z",
    "email": "jon@example.com",
    "email_verified": true,
    "identities": [
        {
            "connection": "Username-Password-Authentication",
            "provider": "auth0",
            "user_id": "61f719cbe422",
            "isSocial": false
        }
    ],
    "name": "jon@examle.com",
    "nickname": "jon",
    "updated_at": "2022-01-30T23:15:09.216Z",
    "user_id": "auth0|61f71922",
    "last_ip": "71.36.126.140",
    "last_login": "2022-01-30T23:15:09.216Z",
    "logins_count": 2,
    "blocked_for": [],
    "guardian_authenticators": []
}

```

### System
Node 14
Strapi 3.6.8
Auth0 provider
### Additional context

The issue is due to there is no username, nickname or name provided in the call to create the account. Everything falls back
to the nickname which is not unique `jon`.  Two usernames with the same name cannot
exist as a result.

It appears as if username is no longer available in the auth response payload.  Thus nickname is then used.

  `body.username || body.nickname || body.name`

I suppose a fix is to re-order to `body.username || body.name || body.nickname` ? 

I don't really know how to populate username, nickname on auth0 side during the signup process.  It is possible my signup
process needs to be more robust by checking for usernames, and such before even making the initial call to strapi /connect/auth0 route.

**Comment by smakinson** [comment]
I just realized this as well during a local register. I'm looking at using email for both username & email & added a fullName field that gets set during registration in some extending code for `plugin.controllers.auth.register`.
