### ISSUE TITLE
Pagination total value unexpected behaviour

### ISSUE THREAD

**Issue by giorgiPapava** [strapi/strapi#12367]
### Describe the bug

total value on meta pagination object has weird behavior when using filter. I have 4 entry in collection. When accessing total property without filters it returns 4 as expected but when I'm trying to use filter with field that is type of array and has multiple elements inside it's getting duplicate count and returns as 4+. 

### Steps to reproduce the behavior

1. Create collection with at least one relational field of type array
2. Fetch collection using filters and mention that type of array relational field 

### Expected behavior

It should return real total count and not duplicate it when using filter.

### Screenshots

![image](https://user-images.githubusercontent.com/66740160/151961094-388de7a7-4388-4209-8e05-f71226b244a0.png)
![image](https://user-images.githubusercontent.com/66740160/151961207-48a005f1-60de-460a-8750-fec70d9400d5.png)

### System

- Node.js version: 14.17.6
- NPM version: 6.14.15
- Strapi version: 4.0.6
- Database: tested on sqlite and postgres
- Operating system: Windows 11

**Comment by dunkman32** [comment]
Same problem here. @giorgiPapava

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7631
