### ISSUE TITLE
Collection slow response from admin page only

### ISSUE THREAD

**Issue by margani** [strapi/strapi#12366]
### Describe the bug

Admin page for listing the data for one of my collection types is taking 34-37 seconds to load, whilst when calling the API, it takes less than a second.

### Steps to reproduce the behavior

I don't know if it's about the collection type, or about the admin site. But I know I don't have any customisation after running the steps in [Quick start page](https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project). 

I don't know if it helps but I have used the following dockerfile to host it in a docker container:
```dockerfile
FROM node:16
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./app/package.json ./
COPY ./app/yarn.lock ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN yarn config set network-timeout 600000 -g
RUN yarn install
WORKDIR /opt/app
COPY ./app/ .
RUN yarn build
EXPOSE 1337
CMD ["yarn", "develop"]
```

I defined a collection type (ATH-Item) with 6 small text fields, 3 large text fields, 3 small JSON fields, 1 field with a Name Value component field and 10 small other fields.
I started inserting about 2000 records into it.
I observe that the page for listing this entity in Admin is taking about 30 seconds (34s-37s) to load. It's projecting only Id, UpdatedAt and State fields, whilst requesting it via API istaking less than a second.

Admin Page:
Request:  GET | https://<domain>/content-manager/collection-types/api::ath-item.ath-item?page=1&pageSize=10&sort=id:ASC
Response: 
```json
{
  "result": [10 records],
  "pagination": { "page": 1, "pageSize": 10, "pageCount": 178, "total": 1775 }
}
```
Time: 36 seconds

API:
Request: https://<domain>/api/ath-items
Response: 
```json
{
  "data": [25 records],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 25,
      "pageCount": 71,
      "total": 1775
    }
  }
}
```
Time: 139 milliseconds

My middlewares.js file content:
```js
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

### Expected behavior

Same admin response speed as the API.

### Screenshots

Admin screenshot:
![ath-item-admin](https://user-images.githubusercontent.com/46093/151942683-a1635b17-3fd6-4e3c-842a-9b89d5060541.gif)

API screenshot:
![ath-item-api](https://user-images.githubusercontent.com/46093/151942707-7c40bbc2-2606-498a-8d45-c0dab14ace88.gif)

### Code snippets

N/A

### System

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: 4.0.6
- Database: SQLite
- Operating system: Ubuntu docker container with node:16 docker image.

### Additional context
Now that the number of records is growing, getting response from Admin page is taking longer.

**Comment by derrickmehaffy** [comment]
likely duplicate: https://github.com/strapi/strapi/issues/12004
