### ISSUE TITLE
Creating a relation causes alpha12.2 to crash

### ISSUE THREAD

**Issue by indiecore-fm** [strapi/strapi#1237]
**Informations**
- **Node.js version**: 10.0.0
- **npm version**: 6.0.1
- **Strapi version**:alpha12.2
- **Database**: mongo3.6
- **Operating system**:windows 10 x64

**What is the current behavior?**

When I create any kind of relation I receive this error:

> [2018-05-20T01:06:11.056Z] error Something went wrong in the model `Videos` with the attribute `subSeries`
> [2018-05-20T01:06:11.058Z] error Cannot read property 'attributes' of undefined

**Steps to reproduce the problem**

Create a relation to anything.

**Suggested solutions**
If I delete the added relation from the json, strapi will start again.

**Comment by indiecore-fm** [comment]
Trying this on a fresh project with only creating a title string for each endpoint allowed me to create to the relation this time. But going back to the original project, it will not let me.

**Comment by lauriejim** [comment]
Please follow the migration guide for your original project https://github.com/strapi/strapi/wiki/migration-guide-alpha.12.1-to-alpha.12.2

**Comment by indiecore-fm** [comment]
@lauriejim Well that's not helpful because this was generated on a fresh install of 12.2 Please look again. Its not the same issue as before its talking about the attributes.

It seems when you try to add to many things to an endpoint at once then save issues like this crop up. After it happened to this project, adding any relation to any endpoint resulted in this error.

**Comment by lauriejim** [comment]
@indiecore-fm  Can you please provide me exact steps you did to have this issue.

**Comment by indiecore-fm** [comment]
@lauriejim What I did was add a "has many" relation. That's all I did and it created the above error. Then after I manually deleted the addition made, Strapi would start back up. 

I also had this issue if I tried adding too many content types at one time.

Whats strange is that this issue has not come up on my other fresh 12.2 build.
