### ISSUE TITLE
Cannot create new collection types with v4.0.6

### ISSUE THREAD

**Issue by dzcpy** [strapi/strapi#12376]
### Describe the bug

After freshly installed Strapi 4.0.6, under development enviroment, everytime I click `Create new collection type`, `Create single Type` or `Create new component`, nothing would happen., there's no error messages in the console (both frontend and backend) too.

### Steps to reproduce the behavior

1. Install Strapi 4.0.6 from `create-strapi-app`, using custom (instead of quickstart) and set database to `PostgreSQL`
2. Run `yarn develop`, and create the first admin user.
3. Go to 'http://localhost:1337/admin/plugins/content-type-builder/content-types/plugin::users-permissions.user'
4. Click on 'Create new collection type'
5. See error

### Expected behavior

It should allow user to add new collection type.

### Screenshots

https://user-images.githubusercontent.com/203980/152087427-d2322ef3-f52f-434d-8d4c-30aba92ed418.mp4

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v16.19.3 (tried v14 too) -->
- NPM version:
- Strapi version: 4.0.6
- Database: PostgreSQL
- Operating system: Tried both WIndows and Debian Linux, none of them work

**Comment by dzcpy** [comment]
It turned out to be something related to my browser. But it's still quite weird.

**Comment by zsctest** [comment]
Hi,I have the same problem.Could you tell me how you resolve it finally.
node.js version:v16.13.0
Strapi version: 4.1.2
Database: SQLite

**Comment by dzcpy** [comment]
@zsctest Hi, I used another browser, I'm not sure why but it works in Chorme but not another Chromium based browser

**Comment by zsctest** [comment]
Actually,I use Chrome too.Anyway thank you.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月20日(星期天) 凌晨1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [strapi/strapi] Cannot create new collection types with v4.0.6 (Issue #12376)





 
@zsctest Hi, I used another browser, I'm not sure why but it works in Chorme but not another Chromium based browser
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
