### ISSUE TITLE
Bug when deploy to digital ocean 

### ISSUE THREAD

**Issue by MohamedSonata** [strapi/strapi#12373]
I'm using latest version of strapi and when deployed it to digital ocean it's going well but the problem is after every deployment is deleting old data and media files... Im just created new collections and some fields and push it gut hub repository to deployment... How can i stop this problem

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
