### ISSUE TITLE
Install an earlier version

### ISSUE THREAD

**Issue by omaraga12** [strapi/strapi#12374]
Hello. I am used to work with Strapi 3.6.8, but now I only can install 4.0.2 version.

Is there a way to install an specific version?
Thank you

**Comment by derrickmehaffy** [comment]
I will answer the question once, but in the future please ask questions either on our forum or discord.

`npx create-strapi-app@3.6.8 your-project`

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
