### ISSUE TITLE
Allow On/Off values to be customizable in the Admin

### ISSUE THREAD

**Issue by kibblerz** [strapi/strapi#12372]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

The Boolean labels in the Admin should be configurable. This doesn't necessarily impact usability, but it seems to be a bit awkward from an End User standpoint. Booleans are typically displayed as either true/false or Yes/No in my experience. Ideally this should be customizable. On/Off doesn't always fit the use case of the attribute, and may lead to confusion among less technical users.

I haven't submitted to the product board since this is a relatively minor issue, and I'm uncertain this qualifies as a "bug". Though being able to customize simple things like this in a CMS is necessary.

### Why is it needed?

While On/Off is synonymous with Yes/No or True/False, it typically isn't used for boolean attributes in a CMS. This would be better if it were configurable, but it doesn't seem to be. For example, if you have a boolean attribute on an item called isFeatured, Yes/No sounds much more intuitive than On/Off.

While functionality isn't impacted by this, and it may be a bit nitpicky, being able to customize these attributes can easily make the admin feel more fluid.

### Suggested solution(s)

Add an attribute to the model attributes in schema.json to allow overriding the labels with an array of overrides like this:

labels: ["Yes", "No"]

**Comment by yanniskadiri** [comment]
Hey @kibblerz thanks for highlighting this, we will address this issue in the coming weeks.

**Comment by kibblerz** [comment]
@gu-stav yup that looks like it'll do it! Looking forward to the release, thanks!

**Comment by alexlau811** [comment]
Seems those PRs do not allow customisable of the boolean but only changed the ON/OFF to TRUE/FALSE?

**Comment by gu-stav** [comment]
@alexlau811 Yes, that is true. You can use the translation system to overwrite these strings globally, in case you need that.
