### ISSUE TITLE
Completely hide fields that a user role doesn't have permissions to view, instead of showing "No permissions to see this field".

### ISSUE THREAD

**Issue by ksaitor** [strapi/strapi#12379]
### Completely hide fields that a user role doesn't have permissions to view, instead of showing "No permissions to see this field".

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Why is it needed?

I'm using Strapi UI internally, within a team, and i'd like to make sure that certain user roles are not aware that certain fields exist on a model. Important for organisational security. And not distracting as well.

Fields should be completely hidden, instead of displayed with "No permissions to see this field"
![image](https://user-images.githubusercontent.com/936436/152130843-40bcdc20-c648-41a1-9de1-8d5a5ab8e404.png)

### Suggested solution(s)

Completely remove "No permissions to see this field" and filed label.

**Comment by yanniskadiri** [comment]
I agree this is something we could hide - or at least it could be an option.
Now we have to spend some time thinking about how we could rearrange the layout for the end-user that cannot see some fields.

**Comment by ksaitor** [comment]
@yanniskadiri just glanced at Strapi's DOM structure. Just removing the `col` div should suffice. Not sure how exactly the UI  generator works, and what edge cases need to be considered, but doesn't seem like a rocket science to just hide the field, instead of dimming it out.

![image](https://user-images.githubusercontent.com/936436/153109262-d3204175-0b53-436f-a366-da54e97ba64c.png)

**Comment by derrickmehaffy** [comment]
> @yanniskadiri just glanced at Strapi's DOM structure. Just removing the `col` div should suffice. Not sure how exactly the UI generator works, and what edge cases need to be considered, but doesn't seem like a rocket science to just hide the field, instead of dimming it out.
> 
> ![image](https://user-images.githubusercontent.com/936436/153109262-d3204175-0b53-436f-a366-da54e97ba64c.png)

We have an alternative view system that allows the user to customize how it's seen. For example you can allow users to view fields but not edit them or allow them edit but not create.

Bit more complex than just deleting the col as some users may still want to show the field is there and others want it removed

https://docs.strapi.io/user-docs/latest/content-manager/configuring-view-of-content-type.html

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/completely-hide-fields-that-a-user-role-doesnt-have-permissions-to-view-instead

Thanks!
