### ISSUE TITLE
getting incomplete data in PUT response / put doesn't update repeatable component with relation

### ISSUE THREAD

**Issue by fxck** [strapi/strapi#12388]
request payload

![image](https://user-images.githubusercontent.com/1303561/152192724-8a82c8f1-ce29-42bd-9559-7483416862de.png)

response

![image](https://user-images.githubusercontent.com/1303561/152192782-655408fb-e52c-4d85-aa80-f90cb70bde0f.png)

it work 8/10 times, it's pretty random, when it goes wrong it goes wrong in either of two ways, request ends with success, but:

1. assignees get updated but I get `[]` in the response (assignees get updated properly, but they are empty in the response)
2. assignees get removed completely (deletes existing, doesn't add the ones I sent as part of the PUT, returns empty array in the response - obviously)

here's the type 
![image](https://user-images.githubusercontent.com/1303561/152192978-7d35059c-4eb2-4449-b364-181c63ee0758.png)

using strapi v4.0.7, node v14.15.4, mysql

**Comment by fxck** [comment]
The problem seems to be relations  in general, not just repeatable components, I just got the same incomplete answer while updating status.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
