### ISSUE TITLE
Impossible to create an admin user: warning an error occurred while requesting the API

### ISSUE THREAD

**Issue by Duddy67** [strapi/strapi#12386]
Hi,
I've been struggling for hours trying to install Strapi on my Ubuntu server. 

### System

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version: 4
- Database: LiteSql
- Operating system: Ubuntu 20.04

> npx create-strapi-app@latest my-project --quickinstall  

All the installation process goes seamlessly but when I go to http://mydomain:1337/admin in order to create a first user I get this warning:  

> Warning: an error occurred while requesting the API.

I know this problem has been encountered several times but none of the suggested solutions have helped me so far.
I also found this error in the Chrome console but I'm not not sure it's related to the my issue: 

> main.815f1087.js:2 Refused to connect to 'http://localhost:1337/admin/project-type' because it violates the following Content Security Policy directive: "connect-src 'self' https:".

Any idea ?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by andrew-hossack** [comment]
Any updates on this @Duddy67?
