### ISSUE TITLE
Media Library and Content-Type Builder not loading in production | cannot read properties of undifined (`reading Allpermissions`)

### ISSUE THREAD

**Issue by TekinaTawar** [strapi/strapi#12393]
### Describe the bug
In my Heroku Production environment, Once logged into the admin panel, navigating to the Media Library or Content-Type Builder or clicking on ‘upload media’ is taking me to a blank page.

### Steps to reproduce the behavior

1.  Deploying on heroku.
2. Loggin in Admin Panl
3. Going to Either Content Type Builder or Media Library or trying to add a Media
4. Blank Screen

### Expected behavior

For a second the loading circle roates and then screen goes blank, and there is error in console as provided in screenshots section.

### Screenshots
![image](https://user-images.githubusercontent.com/54059966/152282446-95ac49e4-d520-4c84-aeb2-de9e9f8b9858.png)

### System

- Node.js version: V16.X.X
- NPM version: V8.X.X
- Strapi version: V4.0.6
- Database: PosgreSQL
- Deployed On: Heroku Free tier.

### Additional context
I am sure this is not a isolated case because I found someone else also facing same issue: [Click Here](https://forum.strapi.io/t/media-library-and-content-type-builder-not-loading-in-production/13639)

**Comment by witek1902** [comment]
Related issue: https://github.com/strapi/strapi/issues/12384

**Comment by witek1902** [comment]
System
Node.js version: V16.13.2
NPM version: V8.4.0
Strapi version: V4.0.7
Database: PostgreSQL
Deployed On: Kubernetes

**Comment by sunnychaganty** [comment]
Issue on local development:

Node.js version: V16.13.2
NPM version: V8.3.0
Strapi version: V4.0.7
Database: SQLite

**Comment by carellano** [comment]
downgrade to version 4.0.4 and not problem

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12384

See these two comments:
https://github.com/strapi/strapi/issues/12384#issuecomment-1030384163
https://github.com/strapi/strapi/issues/12384#issuecomment-1030386159

**Comment by SteveScott** [comment]
I was not able to resolve this issue. Steps I took.
-- Remove package-lock.json and yarn.lock
-- remove yarn.lock
-- remove node-modules
-- run ```yarn install```
-- run ```yarn develop```
-- clear browser cache
-- navigate to plugins.

Result:
-- blank screen with above-mentioned error in console.

**Comment by MichaelLegg** [comment]
> I was not able to resolve this issue. Steps I took. -- Remove package-lock.json and yarn.lock -- remove yarn.lock -- remove node-modules -- run `yarn install` -- run `yarn develop` -- clear browser cache -- navigate to plugins.
> 
> Result: -- blank screen with above-mentioned error in console.


All of those steps are good, but you also need to update your Strapi packages if you haven't already (then delete your node-modules/package-lock).
 
If you take a look at the guide @derrickmehaffy linked in #12384:
https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#upgrade-your-dependencies

The Strapi version upgrade steps involve doing the steps you mentioned but also updating all the different Strapi packages.
I think @strapi/plugin-users-permissions is the one specifically that has the fix for this issue, but it can't hurt to upgrade everything if you haven't already.

I'm currently running:
    "@strapi/plugin-i18n": "4.0.7",
    "@strapi/plugin-users-permissions": "4.0.7",
    "@strapi/provider-upload-cloudinary": "^4.0.7",
    "@strapi/strapi": "^4.0.7",


and I'm not seeing that issue anymore.

**Comment by SteveScott** [comment]
The other step that I left out that I needed to do was rebuild the admin portal with ```yarn build```

**Comment by MhdSadd** [comment]
> I was not able to resolve this issue. Steps I took. -- Remove package-lock.json and yarn.lock -- remove yarn.lock -- remove node-modules -- run `yarn install` -- run `yarn develop` -- clear browser cache -- navigate to plugins.
> 
> Result: -- blank screen with above-mentioned error in console.

Was facing this error with Media Library, kept showing blank page even though server wasn't crashing. doing all of these and that of @MichaelLegg fixed it, though I downgraded to versions 4.9.1
