### ISSUE TITLE
randomly getting "Cannot destructure property 'id' of 'object null' as it is null"

### ISSUE THREAD

**Issue by fxck** [strapi/strapi#12395]
Strapi 4.0.7, node v14.15.4, after trying to add a new entity with repeatable components I'm getting this error, which points to this place

![image](https://user-images.githubusercontent.com/1303561/152302633-e1fd0fed-1cb0-48bb-bff2-1d8d4e708c8f.png)

> [2022-02-03 07:49:36.061] error: Cannot destructure property 'id' of 'object null' as it is null.
TypeError: Cannot destructure property 'id' of 'object null' as it is null.
at /var/www/node_modules/@strapi/strapi/lib/services/entity-service/components.js:50:58
at Array.map (<anonymous>)

it works 9 out of 10 times

same collection type as in https://github.com/strapi/strapi/issues/12388

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
