### ISSUE TITLE
Graphisql

### ISSUE THREAD

**Issue by johntom** [strapi/strapi#1239]
I installed plugin on version 3.0.0-apha.12 but get graphiql not found when I try to open http://localhost:1337/graphiql

**Comment by raulriera** [comment]
It was removed in favor of playground. Use /playground instead after localhost :)

**Comment by derrickmehaffy** [comment]
@johntom The strapi team haven't updated their docs page, I'll poke them on the slack to let them know, but graphiql was removed in favor of playground which is far more powerful.

**Comment by johntom** [comment]
Thanks !

**Comment by lauriejim** [comment]
It's have been updated.
