### ISSUE TITLE
Date field value subtracts 1 to 2 days each time an entry is saved

### ISSUE THREAD

**Issue by chrisabrams** [strapi/strapi#12392]
### Describe the bug

Saving an entry will subtract any date field values by 1 to 2 days each time the record is saved.

### Steps to reproduce the behavior

1. Create a Collection Type
2. Add a date field, with a type of "date"
3. Go to the content manager and create a new entry for your content type
4. Choose a date
5. Hit save and watch the date decrease 1-2 days

### Expected behavior

When I pick a date, I expect that date to be the date which I chose.

### Screenshots

![Screen Shot 2022-02-02 at 9 54 13 PM](https://user-images.githubusercontent.com/527740/152278709-e4f91191-abe8-4074-bccd-dab14c9280cd.png)

Just so it's clear, this is a date field.

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.0.7
- Database: SQLite
- Operating system: macOS Monterey

### Additional context

Can't recall seeing this type of behavior in any kind of CMS before.

**Comment by dorrin-sot** [comment]
Hi! I would like to fix this issue but I'm having trouble reproducing it. Does the decrease happen immediately or does it take a while? If it is happening right away, am I doing something wrong?

https://user-images.githubusercontent.com/59933477/152344515-70b803bc-1a45-45fb-acb9-26a60aa214fe.mov

**Comment by chrisabrams** [comment]
@dorrin-sot thanks for reaching out.

Here is what is happening for us (as we are trying to evaluate Strapi). You'll see both dates subtract two days below:

https://user-images.githubusercontent.com/527740/152440292-cc4198f3-0519-452c-8b7b-1a505c278677.mov

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11509
