### ISSUE TITLE
Default redirect url setting in User-Permission's provider has a extra slash

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#12403]
### Describe the bug

Default redirect url setting in User-Permission's provider has a extra slash

### Steps to reproduce the behavior

1. Go to 'Settings'
2. Click on 'Providers'
3. Click on edit icon of any provider, for example: Github
4. See error, "//api/auth/github/callback"

### Expected behavior

Default(Placeholder) url should be "/api/auth/github/callback"

### Screenshots

<img width="832" alt="Screen Shot 2022-02-04 at 9 43 16 PM" src="https://user-images.githubusercontent.com/22420/152540036-58d78102-48c3-4c4e-a7e3-dc88408f09ec.png">

<img width="646" alt="Screen Shot 2022-02-05 at 11 06 11 AM" src="https://user-images.githubusercontent.com/22420/152626635-c3691db4-d1a7-49a8-9ca5-b2d4371a04fa.png">

### System

- Node.js version: v14
- NPM version: 6.14.15
- Strapi version: 4.0.7
- Database: PostgreSQL 13
- Operating system: macOS 12.2

**Comment by derrickmehaffy** [comment]
No system block information so I have no idea what version of Strapi you are running but we fixed auth providers in v4.0.6


---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by smoothdvd** [comment]
@derrickmehaffy I updated the system information
