### ISSUE TITLE
Add a support for Aggregations  with bookshelf

### ISSUE THREAD

**Issue by kamalbennani** [strapi/strapi#1240]
**What is the expected behavior?**
Can Strapi support aggregation, I'd love to do something like that:
```javascript
query PostData {
  viewer {
    user {
      articles(where:{ createdAt: { gt: "2016", lt: "2017" }}) {
        aggregations {
          count
          sum {
            recommends
            reads
          }
          avg {
            recommends
            reads
          }
        }
      }
    }
  }
}
```
Like the did here: https://docs.scaphold.io/tutorials/aggregations-in-graphql/

- [x] I'm sure that this issue hasn't already been referenced.

**Comment by derrickmehaffy** [comment]
Related PR Merged: https://github.com/strapi/strapi/pull/1407

**Does not support bookshelf, should be added before issue closed**

**Comment by Aurelsicoko** [comment]
@lauriejim Can we close it?

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I think that someone should take a look at bookshelf to support this feature on the other databases before this gets closed.

**Comment by lauriejim** [comment]
@derrickmehaffy is true. Still open since Bookshelf is not developed.

**Comment by ScottAgirs** [comment]
I would like to chime in with a gentle ➕, this is a much-needed feature for me as well

**Comment by lauriejim** [comment]
This has been released - fixed in the beta.20
