### ISSUE TITLE
Belongs to many relationship  filters getting undefined attribute level error

### ISSUE THREAD

**Issue by techwebdev** [strapi/strapi#12406]
### Describe the bug
- when try to make a filter on belongs to many fields inner condition like i want to check customer with attached all bookings in if booking id greater than today's date

### Steps to reproduce the behavior

1. Create  a  any table and give other tables with `belongs to many` relationships 
2. call this API and try to put the booking date greater than filter 
3. in the console you will get the undefined level error 

### Expected behavior
- it should return then greater than date data of customer 

### Screenshots

![image](https://user-images.githubusercontent.com/63657518/152604503-69f7d5c2-13b5-4066-89b9-da43f5e58e4b.png)

### Code snippets

![](https://cdn.discordapp.com/attachments/841755530007805983/939267386513686588/unknown.png)
![image](https://user-images.githubusercontent.com/63657518/152604604-4901217b-6b8d-42bc-b75c-6905f1c8f3b8.png)

### System

- Node.js version: v14.17.1
- NPM version: 6.14.13
- Strapi version: 4.0.7
- Database: PostgreSQL 
- Operating system: macos

**Comment by kibblerz** [comment]
Facing same issue. Any workarounds?
