### ISSUE TITLE
Incorrect handling of error messages for auth provider callback

### ISSUE THREAD

**Issue by degoev** [strapi/strapi#12407]
Some error cases in this [function](https://github.com/strapi/strapi/blob/6343ce509ce166ad855c918bbccb0d50c842eb98/packages/plugins/users-permissions/server/services/providers.js#L545) call `reject` with 3 arguments, but [controller `callback` ](https://github.com/strapi/strapi/blob/6343ce509ce166ad855c918bbccb0d50c842eb98/packages/plugins/users-permissions/server/controllers/auth.js#L107) expects two arguments, and reads `message` fields of the array actually. So this error cases  are not handled properly and the controller only returns `"An application error occured"`

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by degoev** [comment]
Update this with template
