### ISSUE TITLE
plugin development - cannot GET plugin after server refresh

### ISSUE THREAD

**Issue by killermonk** [strapi/strapi#12409]
### Describe the bug

When I make a change to a plugin's source files and the server/page refreshes, I get a 404 error instead of being taken back to the rebuilt version of my plugin.

### Steps to reproduce the behavior

1. Create a new plugin
2. Launch dev mode using `strapi develop --watch-admin`
3. Navigate to plugin from home page ( http://localhost:8080/admin/ )
4. Change a file inside the plugin directory and save
5. Server restarts and browser refreshes
6. 404 - "Cannot GET /admin/plugins/my-dev-plugin"

### Expected behavior

When strapi reloads and refreshes the page, it should load my plugin.
Right now I have to navigate back to the home page and back into the plugin.

### System

- Node.js version: v12.22.3
- NPM version: 7.20.1
- Strapi version: 4.0.7
- Database: Sqlite
- Operating system: Mac OS 11.6.3

**Comment by mohimali** [comment]
This is happening to me as well, in my case it keeps logging me out. And I have to log back in.
