### ISSUE TITLE
Content and Content Types Wiped After Strapi Container build

### ISSUE THREAD

**Issue by henry232323** [strapi/strapi#12412]
### Describe the bug

I am running a vanilla strapi instance in a docker instance connected to an AWS RDS PostgreSQL database.

```
FROM node:14-buster-slim AS deps
WORKDIR /strapi-app
ENV NODE_ENV production
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install --production
COPY . .
RUN yarn build
EXPOSE 80:80
CMD ["yarn", "develop"]
```

Each time I rebuild and deploy the app, the entries for content and content types (including their tables) get removed. My login information and internationalization settings remain however.

### Steps to reproduce the behavior

1. Build and deploy container
2. Create content type and add some examples to it
3. Save the data
4. Verify the content types in the database
5. Shut down the container and service
6. Rebuild and redeploy the container
7. Verify the content types are no longer in the database

### Expected behavior

The database should persist between builds.

### System

- Node.js version: 14.19.0
- Yarn version: 1.22.17
- Strapi version: 4.0.7
- Database: PostgreSQL 13.4
- Operating system: Debian (Buster-slim)

### Additional context

This appears to have been reproduced by at least one other person in the Discord. Rebuilding the container also clears the filesystem, and only contains the output of a freshly created strapi instance.

**Comment by derrickmehaffy** [comment]
Docker should not be used for development without having a persistent filesystem, content-types are saved on the filesystem not the database.

Irregardless this isn't a bug specifically, I would advise taking a look at [this blog post](https://blog.dehlin.dev/docker-with-strapi-v4) for docker related info but functionally Strapi is not entirely stateless while in development mode as it was never intended to be, see this FAQ entry: https://docs.strapi.io/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
