### ISSUE TITLE
Can't Run Strapi on port 1337 getting error 426 "This page isn't working"

### ISSUE THREAD

**Issue by TechXTT** [strapi/strapi#12414]
I just installed strapi v4.
I'm running node 16.13.2
With npm 8.4.1
Windows 11

This is the command I used to install it:
`npx create-strapi-app@latest testing-strapi --quickstart`

After the installation it gave me :
![image](https://user-images.githubusercontent.com/71842793/152647837-5b6cc921-7f3e-431c-b868-19b9d4a612a5.png)

And when it auto opened on my Chrome browser(Tried on Edge too) 
It gave me this:
![image](https://user-images.githubusercontent.com/71842793/152647887-3ecce1aa-534b-43ea-9ae5-5fa1d575efbf.png)

I tried different version of node , updated npm.
Later I tried changing all the refrences of port 1337 to another port and it did load but it said that it had a problem with the api and it was trying to connect to api on port 1337 not 3001 as I set it then.
Console of /admin(with changed port)
![image](https://user-images.githubusercontent.com/71842793/152648023-7803adf8-9dc3-4bea-bc84-464d7ed6f7eb.png)
/admin page with changed port:
![image](https://user-images.githubusercontent.com/71842793/152648063-e67ca623-c3db-4ff7-8a98-86ad0c48358c.png)

Update:

Tried it on WSL same problem I presume the problem is with the port,

**Comment by TechXTT** [comment]
I'm sorry found the problem apparently Razer Chroma's server is running on port 1337 so after I killed the process it started working.

**Comment by TechXTT** [comment]
For anyone with a similar problem quick guide on how I found it:
open cmd with administrator
run `netstat -aon`
you will get a list with all ports in use and the ProcessID that is using it
find the port and look up the last number that is the PID 
open Task Manager go to Details page sort by PID and find the specific PID

**Comment by TechXTT** [comment]
Nope it worked for like 10 seconds it opened the admin panel for registration entered the info tried to submit gave an error and it stopped working again.

**Comment by rrfaria** [comment]
I found an issue on changing port to solve this ... 
I had same issue so I changed port to 1338 on .env and then run yarn develop again 
It opens but with errors
It still looking for 1337 
and the only place I found this port is on line 3
```
config\server.js 
```
![image](https://user-images.githubusercontent.com/11916455/156940270-37d55aa6-fbdd-4fff-b398-30eb9b4f6a7c.png)

**Comment by TechXTT** [comment]
> I found an issue on changing port to solve this ... I had same issue so I changed port to 1338 on .env and then run yarn develop again It opens but with errors It still looking for 1337
> 
> to avoid it I built again and run yarn develop then it worked ![image](https://user-images.githubusercontent.com/11916455/156940270-37d55aa6-fbdd-4fff-b398-30eb9b4f6a7c.png)

To change port of strapi you need to do it the following way:
change your .env file located in the root project directory adding this line:
`PORT=1338`
Then save the file, and run this command in order to refresh up all the things:
`npm run build`
now you can start your server by running:
`npm run develop`

**Comment by blaw6331** [comment]
**NOTE TO PEOPLE WITH RAZOR PRODUCTS**
razor has a process called RzSDKServer that is causing this issue 
`Get-Process -Id (Get-NetTCPConnection -LocalPort 1337).OwningProcess` 
then
`taskkill /F /PID IDFROMABOVECOMMAND`

or change the strapi port like people have done in above comments

This strapi localhost:1337/admin is not showing a HTTP error code 426 Upgrade Required that makes the page not load

**Comment by agdgdag** [comment]
> netstat -aon

Thank You! This started happening after I bought my Razer mouse and installed Razer Synapse software. They did release an update which will fix this port conflict, so just update your Synapse and Srapi will run just fine

**Comment by buden3000** [comment]
not sure what was using port 1337 on my machine as there was nothing in the list when i checked but changing the port has just got this running for me so would suggest this is a fix for some other unknown issue too possibly

**Comment by LukeBennettUK** [comment]
> I found an issue on changing port to solve this ... I had same issue so I changed port to 1338 on .env and then run yarn develop again It opens but with errors It still looking for 1337
> 
> to avoid it I built again and run yarn develop then it worked ![image](https://user-images.githubusercontent.com/11916455/156940270-37d55aa6-fbdd-4fff-b398-30eb9b4f6a7c.png)

Thank you so much for your answer, I changed the localhost port, ran `yarn strapi build` then `yarn strapi start` and it worked! No need to kill processes through task manager.

**Comment by kolpaja** [comment]
> For anyone with a similar problem quick guide on how I found it: open cmd with administrator run `netstat -aon` you will get a list with all ports in use and the ProcessID that is using it find the port and look up the last number that is the PID open Task Manager go to Details page sort by PID and find the specific PID

you are amazing, thank you

**Comment by nkechr1s** [comment]
> I'm sorry found the problem apparently Razer Chroma's server is running on port 1337 so after I killed the process it started working.

Lol same here.

**Comment by Lauro235** [comment]
What worked for me is...

`ctrl shift f` => type 1337
replace all with 1338

**Comment by lsotoj** [comment]
Go over the proccesse's that is runnin over the same port, in my case was Razer keyboard that was running on the same port, I just finished the procces ID and it worked.  :)

**Comment by CostinSariu** [comment]
> For anyone with a similar problem quick guide on how I found it: open cmd with administrator run `netstat -aon` you will get a list with all ports in use and the ProcessID that is using it find the port and look up the last number that is the PID open Task Manager go to Details page sort by PID and find the specific PID

Hey as a newbie dev who barely knows what he's doing with a deadline, I've been trying to solve this for 6 hours and wanted to thank you sosososo much for coming back to post your solution.

**Comment by jonupton** [comment]
Absolute legend. I've been sat here trying to diagnose why windows cannot access a WSL port.

**Comment by af0nx** [comment]
Thanks so much

**Comment by af0nx** [comment]
Thanks for the help.
