### ISSUE TITLE
AllPermissions cannot read error, causing plugins to fail.

### ISSUE THREAD

**Issue by SteveScott** [strapi/strapi#12411]
### Describe the bug

I am having trouble loading two modules: the media library module and content-type builder module. The page does not load, I get a blank page. I also get a blank page when I access the plugin settings. I get the following error in the console:

```
main.0cf6ee77.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'allPermissions')
    at g (main.0cf6ee77.js:2:1184892)
    at li (main.0cf6ee77.js:2:2516981)
    at $u (main.0cf6ee77.js:2:2569278)
    at kl (main.0cf6ee77.js:2:2556519)
    at Sl (main.0cf6ee77.js:2:2556447)
    at Pl (main.0cf6ee77.js:2:2556310)
    at Ol (main.0cf6ee77.js:2:2553276)
    at main.0cf6ee77.js:2:2502773
    at t.unstable_runWithPriority (main.0cf6ee77.js:2:2710634)
    at Ga (main.0cf6ee77.js:2:2502550)
```
```
main.0cf6ee77.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'allPermissions')
    at t.default (main.0cf6ee77.js:2:1710186)
    at t.useMediaLibraryPermissions (main.0cf6ee77.js:2:1628293)
    at t.MediaLibrary (upload.3abe648f.chunk.js:1:15557)
    at li (main.0cf6ee77.js:2:2516981)
    at $u (main.0cf6ee77.js:2:2569278)
    at kl (main.0cf6ee77.js:2:2556519)
    at Sl (main.0cf6ee77.js:2:2556447)
    at Pl (main.0cf6ee77.js:2:2556310)
    at Ol (main.0cf6ee77.js:2:2553276)
    at main.0cf6ee77.js:2:2502773
```
Something about reading the permissions.
 These errors appeared after installing pm2 although I am not entirely sure. It looks like Strapi also updated from 4.0.0 to 4.0.7 the day the error occurred.

I am running the azure-strapi integration. It was working well until this happened.

### Steps to reproduce the behavior
Got to a plugin in the admin console. Content-Type Builder and Media Library give the same error.

### Expected behavior

The pages should load without error.

### System

- Node.js version: 12.22.7
- NPM version: 6.14.15
- Strapi version: 4.0.7
- Database: PostgreSQL 13.4
- Operating system: Ubuntu 20.04.3 LTS

### Additional context

I ran ```rm -rf node_modules && yarn cache clean && yarn``` but no luck.

**Comment by SteveScott** [comment]
I see this is mentioned elsewhere. #12393

**Comment by lem38** [comment]
Same problem for me with version 4.0.7.
Downgrade 4.0.6, work fine.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12384

See these two comments:
https://github.com/strapi/strapi/issues/12384#issuecomment-1030384163
https://github.com/strapi/strapi/issues/12384#issuecomment-1030386159

**Comment by thiago-anjos** [comment]
Same problem here with version 4.2.0

![image](https://user-images.githubusercontent.com/4588828/175344950-3cf9bc4b-e4aa-4ff2-b2ed-4d59ab062665.png)

**Comment by chrift** [comment]
> Same problem here with version 4.2.0
> 
> ![image](https://user-images.githubusercontent.com/4588828/175344950-3cf9bc4b-e4aa-4ff2-b2ed-4d59ab062665.png)
> 
> I've done the downgrade to verson 4.1.9 and it works!

Interestingly, I got this error when upgrading to 4.1.9 or 4.2.0 from 4.1.8 and have had to revert to 4.1.8

**Comment by haysclark** [comment]
This issue also shows up when upgrading from `@strapi/strapi@4.2.0-beta.1` too the following:
- `@strapi/strapi@4.2.0-beta.3`
- `@strapi/strapi@4.2.0-beta.4`

**Comment by haysclark** [comment]
> This issue also shows up when upgrading from `@strapi/strapi@4.2.0-beta.1` too the following:
> 
> * `@strapi/strapi@4.2.0-beta.3`
> * `@strapi/strapi@4.2.0-beta.4`

Ahh... resolved. Looks like the TSConfig files in `@strapi/typescript-utils/` were moved around. All local Typescript configs that extend the base configs need to be modified to something like this:

```json
  "extends": "@strapi/typescript-utils/tsconfigs/server",
```

or

```json
  "extends": "@strapi/typescript-utils/tsconfigs/admin",
```

**Comment by haysclark** [comment]
In the end, I needed to delete my `package-json.lock` file and re-run `npm install --force`.
