### ISSUE TITLE
Editor role does not have permissions to see Content-Manager and permissions cannot be updated

### ISSUE THREAD

**Issue by Dromediansk** [strapi/strapi#12417]
## Bug report

User with Editor role cannot see any data in Content Manager. Furthermore, Super admin role cannot edit permissions for Editor role (400 error).

### Describe the bug

_First of all I should mention that I've installed the Internationalization plugin to have content in 2 locales (en and sk). I'm not sure if this has something to do with it._

When Editor role visits Content Manager, there is no content and  the following message appears:

`"You don't have the permissions to access that content"`

I thought, that the permissions of the role must be adjusted to see the content. 
So when logging in as Super Admin role, I wanted to update role permissions via "Settings" -> "Roles". However, when updating any Collection-Type or Single-Type, I get 400 error with the message: 

`"Permissions have to be defined all together for a subject field or not at all"`

### Steps to reproduce the behavior

1. As a Super Admin, create a new locale (in my case it's Slovak(sk) and English(en)). The default locale is sk.
2. Create some data to have something in Content Manager.
3. Log in as a user with Editor role and go to Content Manager and a permission error should appear.
4. If you want to adjust permissions, log in as a user with Super Admin role.
5. Go to "Setting" -> "Roles" -> edit role within Editor
6. tick all checkboxes in any Single-Type or Collection-Type
7. 400 error should appear

### Expected behavior

As Editor role, I should see content in Content Manager and edit the data for all locales.

### Screenshots

<img width="1680" alt="Screenshot 2022-02-05 at 18 53 11" src="https://user-images.githubusercontent.com/34217538/152653369-fa7030fb-77a9-458b-9495-12c41467d665.png">

<img width="1423" alt="Screenshot 2022-02-05 at 19 05 08" src="https://user-images.githubusercontent.com/34217538/152653909-7c7a4645-bd3e-4d2f-87af-0b5249db8411.png">

<img width="987" alt="Screenshot 2022-02-05 at 18 55 26" src="https://user-images.githubusercontent.com/34217538/152653599-0fcc9c63-86e9-4690-8739-976795e93e97.png">

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: v4.0.7
- Database: SQL Lite
- Operating system: MacOS Monterey 12.1

### Additional context

I'm using Community Edition, but this feature should be included, right? 
Also, I already tried to delete `package.lock.json`, `node_modules`, `.cache` and `.build`. It didn't help.

**Comment by derrickmehaffy** [comment]
Can you please open up the SQLite database in a DB editor and take a few screenshots (or just dump) the following tables of data:

- `admin_permissions`
- `admin_permissions_role_links`
- `admin_roles`

In the intern if you purge the admin_permissions table and restart your app it should rebuild the permissions

**Comment by Dromediansk** [comment]
Thank you for the response, it helped a lot!

The solution was truncating table `admin_permissions` and restarting the application.

**Comment by tungdmctv** [comment]
In my case I have to truncate 2 tables  admin_permissions  and admin_permissions_role_links
restart node and everything woks fine.
