### ISSUE TITLE
Unable to change admin ui locale to 'ro'

### ISSUE THREAD

**Issue by Odisseuss** [strapi/strapi#12422]
### Unable to change the admin ui locale to 'ro'

After reading the documentation about customizing the admin ui in the [strapi docs](https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#configuration-options) I tried adding the 'ro' locale in the config object. This however does not result in the ro locale being available in the admin ui.

Additional Info:  I did add my own 'ro' translation for a project i did with strapi v3.6.8. There i managed to get it working by following the docs. After seeing that this does not work as i imagined with strapi v4, i thought that maybe the docs were unclear and the 'ro' locale is not supported. So i thought about adding it manually. However it's not mentioned in the docs how i could add a locale that is not supported. 

### Expected behavior

After adding the 'ro' locale in the admin ui, i expected it to be available in the dropdown on the login page.

### Code snippets

`/src/admin/app.js`
```
export default {
  config: {
    locales: [
        'en',
        'ro',
    ],
  },
  bootstrap(app) {
    console.log(app);
  },
};
```

### System

- Node.js version: v16 LTS
- NPM version: 8.1.2
- Strapi version:  v4.0.7
- Database: SQLITE
- Operating system: Windows 11

**Comment by teabyii** [comment]
If you are in development, you can try to remove .cache & build folder, and restart the strapi.

**Comment by an-2018** [comment]
Found a similar problem, i had to add a ro.json file with the translations for romanian into the ```api\nextdoor_api\node_modules\@strapi\admin\admin\src\translations\``` folder, not sure if this is the flow to add or update languages in Strapi

**Comment by b3nab** [comment]
Agreed with @an-2018, I'm using yarn berry v3 with workspaces enabled (don't know if it can matter).
So what's the purpose to have this feature without having the possibility to extend the translations?
