### ISSUE TITLE
Graphql schema isn't generated

### ISSUE THREAD

**Issue by uragecz** [strapi/strapi#12420]
### Describe the bug

V3 version was generating /exports/graphql/schema.graphql that we were using to generate types on FE. In new v4 this schema isn't generated. I tried to create plugins.js and set there shadowCRUD to true (it should be by default), but still it doesn't help.. Is this some "new feature" and should we generate / approach this schema differently or it's a bug ?

### Expected behavior

V4 version should also generate simply graphql.schema. This schema is neccesary for most of FE

### System

- Node.js version: v14
- NPM version: 8.4.1
- Strapi version: v4.0.6
- Operating system: macOS 12.1

**Comment by Convly** [comment]
Hey, thanks for submitting your first issue on the Strapi repository!

Could you update your message following our [issue template](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md) please? It helps us to review & track the bugs and feature requests faster.

Concerning your issue, I confirm that we're aware we're not generating this file anymore. The good news is that it shouldn't be hard to add the option to generate it again. I'll look into it this week.

Have a nice day!

**Comment by Convly** [comment]
Hey @uragecz, the ability to generate the GraphQL schema in a file has been merged (see related PR) and should be available in the next Strapi release (4.0.8) in ~2 days.
If the issue persists, please feel free to reopen the issue.

Have a nice day!

**Comment by artcoded-net** [comment]
Hi all, I'm still having a hard time fetching the graphQL schema from my frontend (NextJs).
Am I missing something?

I am using graphql-codegen with the following configuration:
``` yaml
overwrite: true
schema: "http://localhost:1337/graphql"
documents: "apollo/**/*.graphql"
generates:
  types/generated-types.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```
And this is the config/plugins.js part for the graphQL plugin:
``` javascript
module.exports = ({ env }) => ({
  // other plugins' configuration
  graphql: {
    enabled: true,
    config: {
        generateArtifacts: true,
        artifacts: {
          schema: join(__dirname, '..', 'schema.graphql'),
          typegen: join(__dirname, '..', 'types.d.ts'),
        },
        endpoint: '/graphql',
        shadowCRUD: true,
        playgroundAlways: true,
        depthLimit: 7,
        amountLimit: 100,
        apolloServer: {
            tracing: false,
            introspection: true
        }
    }
},
//
}
```
Thanks!

**Comment by uragecz** [comment]
@artcoded-net it's working for me in 4.0.8 ... my plugins.js looks - 


```
'use strict';

const { join } = require('path');

module.exports = ({ env }) => ({
    graphql: {
        enabled: true,
        config: {
            generateArtifacts: true,
            artifacts: {
                schema: join(__dirname, '..', 'public/generate/schema.graphql'),
                typegen: join(__dirname, '..', 'types.d.ts'),
            },    
        }
    },
})
```
