### ISSUE TITLE
Entities added before graphQL plugin installment are not shown in Permissions tab.

### ISSUE THREAD

**Issue by Oleg-Bogatyrev** [strapi/strapi#12430]
### Steps to reproduce:

1. Install strapi 4.0.7
<img width="699" alt="Screenshot 2022-02-08 at 10 22 22" src="https://user-images.githubusercontent.com/98803857/152937687-6ffc65d9-a10e-4ae7-9c76-6fd54ca6d588.png">

2. Fill in collections types

3. Install GraphQL plugin

4. Fill in more collections types

7. Navigate to Settings -> Roles -> Public -> Permissions section

8. **Note** : there are collection types displayed only added after plugin installation.
   **Expected behavior**: all collection types should be displayed despite addition time.

**Environment**: Strapi 4.0.7, Postgresql DB, Node 14.17.5, macOS Big Sur

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
