### ISSUE TITLE
Binding frontend users in Strapi

### ISSUE THREAD

**Issue by madonzy** [strapi/strapi#1243]
Hi guys ;)

I'm trying to understand how to build user entity for frontend. Imagine:
1) I have frontend app (VueJS) - **App 1**
2) I have backend app (Strapi) - **App 2**

When frontend (App 1) guest want to register, I want App 1 send a request (ask to register new customer) to App 2, if everything is ok App 2 creates a user. Important that App 1 user should be created (not App 2 user, newly created custom will not have the ability to login to the backend (App 2)).

How can I implement that? How later will the customer storage its session? Or I need to use separate framework for App 1 to use that kind of data?

**Comment by derrickmehaffy** [comment]
@madonzy I would recommend looking at the guides: https://strapi.io/documentation/tutorials/

Specifically the one geared at Gatsby. You would need to tie into the REST API interface to build GET/POST/PUT/DELETE requests to build bridges between the data storage in `App 2` and your front end user interface in `App 1`

**Comment by indiecore-fm** [comment]
Hey buddy, if you need help I am building a boilerplate to quickly hook up a strapi backend to a nuxt frontend. I can help you get started.

**Comment by derrickmehaffy** [comment]
@indiecore-fm I wouldn't mind seeing these as well, please feel free to drop links to your repos in here 😄

**Comment by indiecore-fm** [comment]
@derrickmehaffy Of course. Here you go! I still have a lot to do, but working when I can on it. (wifes about to pop)

Currently there is no frontend admin panel/theme etc, but Auth and registration works. All you have to do is clone this and just make sure your strapi API is up and running. Its already set to: localhost:1337

I plan to add a lot to this to really make it a great starting point for anyone to use!

 https://github.com/indiecore-fm/strapi-nuxt-boilerplate
