### ISSUE TITLE
DatePicker failed to validate on "no required" datetime column: foo must be a `date` type, but the final value was: `Invalid Date` (cast from the value `""`)

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#12431]
### Describe the bug

When I modified a record, reset a nullable datetime field, then save, Strapi report:
```
foo must be a `date` type, but the final value was: `Invalid Date` (cast from the value `""`)
```

### Steps to reproduce the behavior

1. Add a datetime field named 'foo', set "Required field" off
2. Insert a new record with a valid date in 'foo' field
3. Edit the record
4. Reset the 'foo' field
5. Save
6. Error reported, foo must be a `date` type, but the final value was: `Invalid Date` (cast from the value `""`).

### Expected behavior

Skip validate field which is not requirement when it's value is empty

### Screenshots

https://user-images.githubusercontent.com/22420/152959899-75da0075-efb9-48ce-9a44-360f733829a7.mov

### Code snippets

https://github.com/strapi/strapi/blob/6b627b436d72094c9f1242472688c7d6b3ef596d/packages/core/helper-plugin/lib/src/components/GenericInput/index.js#L150

onClear() should set target value null

### System

- Node.js version: v14
- NPM version: 6.14.15
- Strapi version: 4.0.7
- Database: PostgreSQL 13
- Operating system: macOS 12.2

**Comment by derrickmehaffy** [comment]
fixed in https://github.com/strapi/strapi/pull/12445 closing, will be in next release
