### ISSUE TITLE
Hard-coded Swagger UI layout

### ISSUE THREAD

**Issue by stafyniaksacha** [strapi/strapi#12434]
### Describe the bug

It seems that we can not change the Swagger UI layout in the documentation plugin

### Steps to reproduce the behavior

1. https://github.com/strapi/strapi/blob/master/packages/plugins/documentation/server/controllers/documentation.js#L61-L64

### Expected behavior

We should be able to create our own layout in the extension directory, such as the settings.json file (https://github.com/strapi/strapi/pull/12070)

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/developer-experience/p/allow-for-customization-of-the-swagger-ui-layout
