### ISSUE TITLE
Cannot set date older than 1972?

### ISSUE THREAD

**Issue by willnode** [strapi/strapi#12441]
### Describe the bug

In the date picker, I can't select older than 1972. I also can't type the date directly. I need it to enter birth date data there.

### Steps to reproduce the behavior

1. Create an entity with a date component
2. Try to set the date as `1960-01-01`

### Expected behavior

I should be able to select a date older than 1972.

### Screenshots

![image](https://user-images.githubusercontent.com/20214420/153111832-8046003f-55cd-4e93-a84d-8af57b30ecac.png)

### Code snippets

Not relevant

### System

- Node.js version: 14.17.5
- NPM version: 6.14.14
- Strapi version: 4.0.5
- Database: MySQL
- Operating system: Rocky Linux 8.5

### Additional context

I can't see where `1972` is hardcoded on Strapi code, can you guide me on where to fix it for the quick patch? (I've been `patch-package`-ing Strapi a lot of times for my client project)

**Comment by iicdii** [comment]
You need to look at [@strapi/design-system](https://github.com/strapi/design-system)

https://github.com/strapi/design-system/blob/da180377d5f72c4830af8b4a757c988047f63c55/packages/strapi-design-system/src/DatePicker/utils/getYears.js#L4-L10

**Comment by willnode** [comment]
Thanks for pinpointing the code @iicdii. Though I need to have a little find+replace because in `node_modules` I only find the "compiled" js code there, but it's doable and works.

My case is done, but doesn't this means Strapi should consider extending the year range of the default date picker? Birthdate is common and a lot of people are older than 50 years.

**Comment by iicdii** [comment]
I agree with you. the current range `current year - 50` ~ `current year` seems so restricted now 🤔 
Other design systems have props like `minDate`, `maxDate` and it's enough to cover possible cases.

**Comment by digimarktech** [comment]
I'm new to using Strapi. How do I make use of this new change? Do I need to create a custom component? I've already installed the design-system package

**Comment by willnode** [comment]
@digimarktech you need [patch-package](https://www.npmjs.com/package/patch-packages) and edit files directly in node_modules. it's in `@strapi/design-system`.

**Comment by gu-stav** [comment]
Hello! We are going to release version 4.1.4 tomorrow, which will include a fix for this issue. You will be able to select dates between 200 years in the past till 15 years in the future for now. Would this cover all your use cases, @willnode, @digimarktech?

**Comment by willnode** [comment]
Yes indeed, thanks @gu-stav!

**Comment by digimarktech** [comment]
Yes, it will @gu-stav! Thank you so much!
