### ISSUE TITLE
GraphQL and filter

### ISSUE THREAD

**Issue by johntom** [strapi/strapi#1244]
Using playground but can't get a simple filter to work.
This works
...
{
  articles {
  title ,content,contentHtml }
}
This fails
{
    articles (
            title: "Reynold 2" 
    ) {
          _id
  title
    content
    contentHtml 
    }
}
...
...
error
{
  "error": "Response not successful: Received status code 400"
}
...

**Comment by derrickmehaffy** [comment]
@johntom can you edit this with the proper bug report template? Also when pasting code, please use the code block.

**Comment by johannpinson** [comment]
Hello @johntom 

Please have a look to this docs: https://strapi.io/documentation/3.x.x/guides/graphql.html#query-api

The "filter" logic works with the `where` param where you can put a JSON with the wanted rules.

**Comment by johntom** [comment]
Hi,
I tried many variatins...
Thanks,
John
**Informations**
- **Node.js version**:nvm use 8.9.4
- **npm version**:1.1.3
- **Strapi version**:3.0.0-alph.12
- **Database**:mongodb
- **Operating system**:win10


**What is the current behavior?**
`
```
query {
  articles( title:"Reynold 2") {
        _id
  title
    content
    contentHtml 
  }
}`
```
```
{
  "error": "Response not successful: Received status code 400"
}
```

**Steps to reproduce the problem**



**What is the expected behavior?**



**Suggested solutions**





- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by johannpinson** [comment]
Can you test this:

```graphql
query {
  articles(where: {
    title: "Reynold 2"
  }) {
    _id
    title
    content
    contentHtml
  }
}
```

**Comment by johntom** [comment]
Yes that worked, I read a bunnc of articles and never saw that "where" was required.
```
{
  "data": {
    "articles": [
      {
        "_id": "5ac2370666367202f0a2deaf",
        "title": "Reynold 2",
        "content": "test short",
        "contentHtml": null
      }
    ]
  }
}
```

**Comment by BjoernRave** [comment]
did you manage to write an `AND` filter?

**Comment by lauriejim** [comment]
There is no planning for that for now.
You have to code it yourself by using the ORM functions.
`strapi.query('modelName').model`
