### ISSUE TITLE
Strapi cannot restart after creating a new collection type

### ISSUE THREAD

**Issue by Keith-Hon** [strapi/strapi#12453]
### Describe the bug
Strapi cannot restart after creating a new collection type

### Steps to reproduce the behavior

1. Go to 'Content-type Builder'
2. Click on 'Create new collection type'
3. Input Display name "Language"
4. Click "Continue"
5. Click "Text"
6. Input "name" under "Name" field
7. Click "Finish"
8. Click "Save"

### Expected behavior
Strapi restarts without error

### Code snippets

[2022-02-10 13:56:36.157] debug: ⛔️ Server wasn't able to start properly.
[2022-02-10 13:56:36.158] error: alter table `languages` add constraint `languages_created_by_id_fk` foreign key (`created_by_id`) references `admin_users` (`id`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'created_by_id' and referenced column 'id' in foreign key constraint 'languages_created_by_id_fk' are incompatible.        
Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'created_by_id' and referenced column 'id' in foreign key constraint 'languages_created_by_id_fk' are incompatible.

### System

- Node.js version: 
- NPM version: 14.18.3
- Strapi version: 4.0.7
- Database: MySQL 8
- Operating system: Windows 10

### Additional context
I migrated the database from sqlite into MySQL and imported the dump.sql

**Comment by Keith-Hon** [comment]
related to https://github.com/strapi/strapi/issues/11723

**Comment by derrickmehaffy** [comment]
semi-duplicate to https://github.com/strapi/strapi/issues/11723

Marking as closed as it's close enough.

**Comment by aaroncrawford** [comment]
For anyone that runs into this now..

We ran into this as well right after migrating from Sqlite to Mysql like the OP.  Had to go dump our MySQL db out again, then changeout all of the IDs across all tables to be `int unsigned` to get Strapi back up.  Unsure if it will produce any long-term side effects, but I think it'll be fine.  Just to verify what strapi does when it sets up a new MySQL DB, I saw that all of the ID's are int unsigned as well.

e.g. in the mysql dump
``CREATE TABLE `admin_permissions` (`id` int NOT NULL AUTO_INCREMENT,....``
to
``CREATE TABLE `admin_permissions` (`id` int unsigned NOT NULL AUTO_INCREMENT,....``

**Comment by iMagesh** [comment]
Thanks, @aaroncrawford for sharing that. It helped us. 

We have migrated from SQLite to MySQL now for Strapi. After migrating the data strapi was not running because of a incompatibility in the schema. It worked once I changed all the primary keys to `int unsigned`.
