### ISSUE TITLE
Strapi admin cannot load ressources with relative server url

### ISSUE THREAD

**Issue by MrSquaare** [strapi/strapi#12457]
### Describe the bug

Strapi admin cannot load ressources with relative server url

### Steps to reproduce the behavior

1. Add relative url to `config/server.js`
Example:
```js
module.exports = () => ({
  url: "/relative",
});

```
2. Launch Strapi server (strapi dev/start)
3. Open Strapi admin url
4. See errors in console

### Expected behavior

Loading ressources from url

### System

- Node.js version: v16.13.1
- NPM version: 8.3.2
- Strapi version: 4.0.7
- Database: sqlite
- Operating system: Ubuntu 21.10

**Comment by derrickmehaffy** [comment]
This largely depends on how Strapi is deployed but we strongly recommend absolute URLs, this isn't really a bug but more of a proxy configuration issue.

**Comment by MrSquaare** [comment]
I think it should be removed that Strapi supports relative URLs.

Moreover, I just did some more tests, and I see the same problem: 
- No URL in `config/server.js`, `/dashboard` URL in `config/admin.js`
- `http://localhost:1337/route` URL in `config/server.js`, No URL in `config/admin.js`
- `http://localhost:1337/route` URL in `config/server.js`, `/dashboard` URL in `config/admin.js`
- `http://localhost:1337/route` URL in `config/server.js`, `http://localhost:1337/route/dashboard` URL in `config/admin.js` (it's probably normal)

I will continue testing with `host` and `port` in `config/admin.js`
