### ISSUE TITLE
No graphql query generated for types with circular structure

### ISSUE THREAD

**Issue by chronark** [strapi/strapi#12469]
### Describe the bug

We are using a collection type `Category` that has multiple relations to itself and want to use graphql to access it.
```json
{
  "kind": "collectionType",
  "collectionName": "categories",
  "info": {
    "singularName": "category",
    "pluralName": "categories",
    "displayName": "Category",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "parent": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::category.category",
      "inversedBy": "children"
    },
    "children": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::category.category",
      "mappedBy": "parent"
    }
  }
}

```

### Steps to reproduce the behavior

1. Create new collection type:
2. Add a oneToMany relation to itself
3. Add a manyToOne relation to itself

### Expected behavior

I expect a graphql query field `Query.categories` to be generated.

### System

- Node.js version: `v4.18.3`
- NPM version: `v6.14.15`
- Strapi version: 
```
"@strapi/plugin-graphql": "4.0.6",
"@strapi/strapi": "4.0.6",
```
- Database: sqlite
- Operating system: mac os

**Comment by derrickmehaffy** [comment]
Appears to work fine for me

![image](https://user-images.githubusercontent.com/8593673/153507947-78a0181e-f386-40ae-bb07-a890105295f2.png)

marking as closed until more information is provided

**Comment by chronark** [comment]
Yeah you are right. It's somehow working today but wasn't generating the schema properly yesterday.
Thanks for checking though
