### ISSUE TITLE
REST PUT statement doesn't conform with Documentation 

### ISSUE THREAD

**Issue by opgbaudouin** [strapi/strapi#1246]
**Informations**
- **Node.js version**:9.5.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:mongodb 3.6
- **Operating system**: windows 10 x64

**What is the current behavior?**
Performing a simple PUT request with AXIOS on server sides does not return the updated object but a status object instead.
This is contrary to the documentation 
my result for doing a simple PUT is:
```
data: { n: 1, nModified: 0, ok: 1 }
```
**Steps to reproduce the problem**
Create an new type with a few vars
Create a new instance of that type.
use Axios on serverside (but i presume for all) with PUT to modify a call - result (in .data is not the object)

```
//quick helper function.
axios.defaults.baseURL = API_BASE_URL;
axios.defaults.headers.common['Authorization'] = "Bearer " + WEBTOKEN;
...
async function put(url, data, extraHeaders = {}) {
    const {data: result, error} = await axios.put(url, data, {headers: extraHeaders});
    return result
}

async function updateLicense(license) {
    const res = await put('license/'+license.id, license);
    console.log(res); //this should be the license as PER DOCUMENTATION
    return res;
}
```

**What is the expected behavior?**
Either the documentation of the PUT statement is out of date or the behaviour has changed. Or perhaps there is an setting inside the PUT REST comment to choose the more low bandwidth (as it is now) or the complete setting.

Documentation url:
https://strapi.io/documentation/getting-started/quick-start.html#update-data-put

see also:
https://stackoverflow.com/questions/797834/should-a-restful-put-operation-return-something

Perhaps a simple '200' would be OK. 

**Suggested solutions**
Decide on the way it is used - this is a KEY feature of an API creating tool. 

---

- [x ] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment]
Hello @opgbaudouin, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature and bug fix. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

The response you get is actually the mongoose response. You can check how to change it to have the updated object.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by opgbaudouin** [comment]
Due to your request to update to 3.0.0-alpha.12.2 i can now confirm that it does now indeed return the OBJECT as per the documentation.

This makes sense based on the updates required when migrating as edit went from:
```
 /* edit: async (params, values) => {
    // Note: The current method will return the full response of Mongo.
    // To get the updated object, you have to execute the `findOne()` method
    // or use the `findOneOrUpdate()` method with `{ new:true }` option.
    await strapi.hook.mongoose.manageRelations('item', _.merge(_.clone(params), { values }));
    return Item.update(params, values, { multi: true });
  },*/
```
to
```
    edit: async (params, values) => {
        // Extract values related to relational data.
        const relations = _.pick(values, Item.associations.map(a => a.alias));
        const data = _.omit(values, Item.associations.map(a => a.alias));
        
        // Update entry with no-relational data.
        const entry = await Item.update(params, data, { multi: true });
        
        // Update relational data and return the entry.
        return Item.updateRelations(Object.assign(params, { values: relations }));
    },
```

I would therefor suggest you can close this - as 'solved' (or at least compliant with docs).

Also a little more digging on my part should have spotted the previous comment about it returning the mongoose part...

**Comment by lauriejim** [comment]
@Aurelsicoko update this part for the `3.0.0-alpha.12.2` so it's good now.
