### ISSUE TITLE
Deeply Nested Components Not Saving Data. Worked in v3, broken in v4

### ISSUE THREAD

**Issue by jirbjirbjirb** [strapi/strapi#12466]
In Strapi V3, we are able to nest components deeper than is possible through the UI. We understand that the inability to add components at a deep level through UI is an expected behavior in v3, but is possible through directly editing the JSON, as stated below. 

https://github.com/strapi/strapi/issues/4890#issuecomment-570598553)

However, when we attempt the same thing in v4, all data entered in our nested component is wiped on save. This is not the case in v3, and is currently blocking our project from moving to Strapi V4

### Steps to reproduce the behavior

1. clone and boot v4
2. create new collection (our example is pages)
3. create dynamic zone inside pages, with a component of its own (modular blocks)
4. inside modular blocks, create repeatable component (ours is called blocks)
5. inside of blocks add non-repeateable component (ours is design)
6. add component inside design (our is margin), component should have some data, we have some text fields in this example.

### Expected behavior

When enter values in our fields in "margin" and save, values should be saved. This works in v3, however in v4 saving wipes our data.

Here is a video demonstrating current behavior in v4:https://www.loom.com/share/2ef25875151b47f485fc5282002e0fbe

at this point, our pages collection looks like this:

![Screen Shot 2022-02-10 at 10 16 35 AM](https://user-images.githubusercontent.com/50177082/153437614-660403fa-41a2-4a08-a4c9-fe93bb1f2acc.png)

relevant JSON looks like this:
![Screen Shot 2022-02-10 at 10 17 43 AM](https://user-images.githubusercontent.com/50177082/153437847-23fe071c-bd62-4501-b7c7-80ba8e10d5d1.png)

### System

- Node.js version: 14
- NPM version: 6.14.15
- Strapi version: v4
- Operating system: osx 12.1

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11319
