### ISSUE TITLE
ECONNRESET and ECONNABORT errors when serving mp4 from public folder

### ISSUE THREAD

**Issue by Sektin** [strapi/strapi#12461]
### ECONNRESET and ECONNABORT error messages in strapi console

When I spam click F5 in the browser, I get ECONNRESET and ECONNABORT error messages in the strapi console.

### Steps to reproduce the behavior

1. Create a new strapi project version 3.6.8 or 4/latest
2. Start strapi server
3. Log in
4. Go to Media Library
5. upload a mp4 file
6. create a simple html file containing a <video src="localhost:1337/uploads/upload_someHash.mp4 controls /> in the body
7. open the html
8. video should load an work normally
9. you should see a 206 get request in the browser network tab and in strapi console
10. start spam clicking F5
11. you should encounter above mentioned errors after a while in the strapi console

### Expected behavior

To not see these errors in the strapi console, because the connection reset or abortion should get handled somewhere.

### Screenshots

![2022-02-09 14_57_44-test html - strapi_test - Visual Studio Code](https://user-images.githubusercontent.com/52243145/153394770-0ead05c1-a032-4231-bfd2-c26143d52eb7.png)

### Code snippets

I can catch the error in node-modules/koa/lib/context.js in the onerror(err) function:

```
onerror(err) {
    // don't do anything if there is no error.
    // this allows you to pass `this.onerror`
    // to node-style callbacks.
    if (null == err) return;

    // When dealing with cross-globals a normal `instanceof` check doesn't work properly.
    // See https://github.com/koajs/koa/issues/1466
    // We can probably remove it once jest fixes https://github.com/facebook/jest/issues/2549.
    const isNativeError =
      Object.prototype.toString.call(err) === '[object Error]' ||
      err instanceof Error;
    if (!isNativeError) err = new Error(util.format('non-error thrown: %j', err));

    let headerSent = false;
    if (this.headerSent || !this.writable) {
      headerSent = err.headerSent = true;
    }

   console.log(err);

    // delegate
    this.app.emit('error', err, this);
...
```

I can see the koa-range package beeing involved creating the 206 partial-content response.
In node-modules/koa-range/index.js line 70:

```
...
console.log(ctx.response.header);
ctx.set('Content-Range', rangeContentGenerator(start, end, len));
ctx.status = 206;
...
```

I can catch the error and override it with my own console log in node-modules/strapi/lib/Strapi.js. But I don't like having to override node-module.

```
class Strapi {
  constructor(opts = {}) {
    this.reload = this.reload();

    // Expose `koa`.
    this.app = new Koa();

    this.router = new Router();

    this.initServer();

    // Logger.
    this.log = logger;

this.app.on("error", (error) => {
    if (error.code === "ECONNABORTED" || error.code === "ECONNRESET") {
      this.log.debug("video stream was aborted by client", { error });
    } else {
      this.log.error("Koa app-level error", { error });
    }
  });
...
```

I can also see the error in ./config/bootstrap.js. But this does not override the logger, I then get 2 messages in the console:

```
module.exports = async () => {
  console.log("bootstrap.js");
  strapi.app.on("error", (error) => {
    if (error.code === "ECONNABORTED" || error.code === "ECONNRESET") {
      strapi.log.debug("video stream was aborted by client", { error });
    } else {
      strapi.log.error("Koa app-level error", { error });
    }
  });
...
```

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.8 or 4/latest
- Database: MySQL
- Operating system: Windows 10

### Additional context

A simple koa setup serves the mp4 with request 200 - no problems there
I have yet to build a simple koa setup using koa-range and serve the files with 206. Would be interesting to see what happens.
Opend a thread in the forums: https://forum.strapi.io/t/econnreset-and-econnaborted-triggered-by-mp4-after-reloading-browser/15473

My question is: Is it ok to just ignore these error messages? Nothing breaks or crashes, the videos play just fine. And if yes where would be the best place to catch them?

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.0.7 but I also don't even remotely understand what would cause this under normal usage conditions?

**Comment by Sektin** [comment]
You need to spam ctrl + F5 in Chrome to reproduce it frequently. In Edge and Firefox it takes some time to get even one error message.

**Comment by derrickmehaffy** [comment]
> You need to spam ctrl + F5 in Chrome to reproduce it frequently. In Edge and Firefox it takes some time to get even one error message.

I understand that @Sektin but what is the use-case where you spam ctrl +f5 and why is it something we should handle lol? I could throw 500 requests per second and DDoS an application too but I guess I'm missing the point here?

**Comment by derrickmehaffy** [comment]
This is effectively just a DDoS, gonna mark as closed

**Comment by Pablo-Aldana** [comment]
I'm having the similar issue with v4, I have an html that requires an image from public folder to create an Open graph card.
It works like charm on browser, Facebook, Twitter....but it does return 206 on WhatsApp for iPhone, I have test it on WhatsApp Android and macOS and  it returns 200 however for iOS it returns 206 

I have created a test example here: https://vive.scintillam.com/download/strapitest.html

The specific line that returns the error is this one:
`<meta property="og:image" content="https://vive.scintillam.com/uploads/New_Project_8_4e84cb230c.jpg"/>`

at NGINX level I'm getting 
`XXX - - [09/Jun/2022:12:58:03 +0000] "GET /uploads/New_Project_8_4e84cb230c.jpg HTTP/2.0" 206 89955 "-" "WhatsApp/2.22.10.76 I"`

at strapi level:
`[2022-06-09 14:57:58.538] http: GET /uploads/New_Project_8_4e84cb230c.jpg (18 ms) 206`

The only difference I can find when I query from WhatsApp Web the browser it is different and so is the response

```
XXX - - [09/Jun/2022:13:01:18 +0000] "GET /download/test.html HTTP/1.1" 200 1008 "-" "WhatsApp/2.2216.8 N"
XXX - - [09/Jun/2022:13:01:19 +0000] "GET /uploads/New_Project_8_4e84cb230c.jpg HTTP/1.1" 200 89955 "-" "-"
```

It is certainly weird, I guess on iPhone the header sent is different but not sure why Strapi responds with 206 instead 200 for the same file.

Any ideas would be more than welcome
