### ISSUE TITLE
Cannot update users with the API 

### ISSUE THREAD

**Issue by moadw** [strapi/strapi#12478]
### Describe the bug
An individual user cannot be updated with the API. The PUT  endpoint for users is not updating the user although we are using a full permissions token. The API is not returning error but 200 ok without updating the user record. 

### Steps to reproduce the behavior
You must have users with custom fields on the content manager. 

1. Go to settings > API tokens and create a full access token
2. Make a quest to The endpoint: 
`PUT /api/users/{id}` changing the user data. 
3. Try to change a text value. Example: 

```
{
    "data" : {
        "zipCode" : "33134"
    }
}
```
4. After sending the data request it returns a 200 ok response but the user object will still contain null fields. 

```
{...
"zipCode" : null
}
```
5. Same thing will occur if you authenticate with a user that also has role permissions for updating users. 

### Screenshots
<img width="572" alt="Screen Shot 2022-02-10 at 9 50 37 PM" src="https://user-images.githubusercontent.com/4247590/153530576-9625ac12-e01b-4cba-b133-1931816688b2.png">

### System
Node.js version: v16
NPM version: 8.1.2
Strapi version: v4.0.7
Database: postgres
Operating system: Ubuntu

**Comment by Aregver** [comment]
Are you getting an error message from the request?

**Comment by moadw** [comment]
@kasonde format updated. 
@Aregver there is no error message form the request, shows 200 OK. 
<img width="1212" alt="Screen Shot 2022-02-11 at 8 47 45 AM" src="https://user-images.githubusercontent.com/4247590/153602751-a7e5b92e-712b-41a3-8e0b-3e16bc58c7d9.png">

**Comment by moadw** [comment]
> Hello, please follow the issue template.
> 
> A proper issue submission lets us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue.
> 
> Thank you.

I have updated the issue to the correct format. @kasonde Let me know if this will be taken in account some day. Strapi V4 requires fixes on the user-permissions API endpoints.

**Comment by kasonde** [comment]
@moadw it's definitely gonna be taken into account :) We're having an influx of U&P related issues and this is one of them. Thanks for updating the format. I'll be able to verify this a tad bit later today.

**Comment by sebrojas14** [comment]
This is important! Any workaround?

Check out this also, users permissions generate an api endpoints that doesn't works https://github.com/strapi/strapi/issues/12555

**Comment by sebrojas14** [comment]
Solved: just remove `data` json key from body, send data to change only

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12280

**Comment by SandovalJr** [comment]
Hi, Just remove "data " json key from body, send the data you want to change.
![e0d29209-dce6-44b3-b5ab-59ac5845081d](https://user-images.githubusercontent.com/55955387/176955051-8519f6d1-b00a-4816-9955-08fdbd0c9137.jpg)

**Comment by gvr37leo** [comment]
I just walked into this issue
happened because the documentation says you should add the data key
https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#update-an-entry

{
  "data": {
    "title": "Hello",
    "relation": 2,
    "relations": [2, 4],
  }
}

**Comment by TheHuns** [comment]
Having a very similar issue. Not with a user type but a custom schema. I tried the suggestion above removing the `data` object part of the json but get this
```
 "status": 400,
        "name": "ValidationError",
        "message": "Missing \"data\" payload in the request body",
```
With that in I get a 200 response back but no change to the data. Anyone else found a different solution?

**Comment by anuj-scanova** [comment]
I'm getting **400** response after removing `data` from the payload.

<img width="704" alt="Screenshot 2024-02-02 at 14 31 08" src="https://github.com/strapi/strapi/assets/105233146/fefe04a2-1da6-4ec3-8b57-51e6ff70d36b">

**Comment by KarelDiaz** [comment]
@moadw, did you solve the problem?
