### ISSUE TITLE
Native SSL / HTTPS integration for server

### ISSUE THREAD

**Issue by Erim32** [strapi/strapi#12477]
### Please describe your feature request

- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

SSL / HTTPS  Native integration
Since 2021, all browsers requires HTTS support in production, 
Currently, Strapi server only support HTTP protocol,  It's possible to support HTTPS using some hacks with nginx, it's not a standalone solution.
That should be nice to have a sub folder in config/ to copy SSL certificates and be able to enable HTTPS support in config/server.js file.

### Why is it needed?
When we want to deploy any website using strapi in production we are facing to two issues;
- With a domain name, we can't easily use strapi web server because https support is not to specify certificates, Browser depreciates these kinds of websites.
- If we use strapi only as an API server (npm run start), it's not possible to call the API from a website using HTTPS protocol because we will call an insecure request.

### Suggested solution(s)
Integrate optional SSL certificates for web server : 

- Add a facultative SSL option in config/server.js 
- If this configuration is set to true then
- Check if config/ fiolder contains an ssl/ folder
- Create an alternative version to strapi/lib/services/server/http-server.js to support HTTPS using certificates in config/ssl/ folder.
- If ssl option is enable and certificate are present start https server, else start http server.**

Example of options to support HTTPS with koa server.
https://stackoverflow.com/questions/44689542/add-ssl-to-node-js-koa-server

Files to update:
/packages/core/strapi/lib/services/server/http-server.js

**Comment by derrickmehaffy** [comment]
While it's possible, it's not recommended, as to update the certificates you have to restart the server which is not good in production. Using standard proxy applications to offload SSL is a common standard in even large enterprise environments. You should not be running node applications on your edge.

Likewise to run a node application on the standard port 443 on linux means you need to run the node application as root **which is extremely bad and absolutely not recommended**

We won't add native https for this exact reason, you should be using a common proxy application or service to offload your SSL management.

Every major cloud has options for this or you can use something like Cloudflare. For actual proxy applications you have Nginx, Apache, Traefik, HAProxy, Caddy, and many many others.
