### ISSUE TITLE
Change width of fields on Edit page

### ISSUE THREAD

**Issue by vitaliy-bdk** [strapi/strapi#12475]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Quick summary what's this feature request about.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
fixed by : https://github.com/strapi/strapi/pull/12398

**Comment by derrickmehaffy** [comment]
@vitaliy-bdk next time can you please fill out the template with actual content? Next time we will just close your issue.
