### ISSUE TITLE
Miss-spelling port for "strapi develop --watch-admin" command.

### ISSUE THREAD

**Issue by Arsh1a** [strapi/strapi#12496]
## Bug report

There is a small port miss-spelling when running `strapi develop --watch-admin`.

### Describe the bug

There is a small port miss-spelling when running `strapi develop --watch-admin`. Instead of saying that the admin panel runs on port 8080, it says it's running on port 8000.

### Steps to reproduce the behavior

1. Run `yarn develop --watch-admin` command
2. Check the console. It says `Admin development at http://localhost:8000/admin/` 

### Expected behavior

It is expected to write  `Admin development at http://localhost:8080/admin/`.

### Screenshots

![Capture](https://user-images.githubusercontent.com/42667460/153716586-35970901-0521-46ac-963a-a9521f2728bc.PNG)

### System

- Node.js version: v14.18.2
- NPM version: v6.14.15
- Strapi version: v4
- Operating system: Windows 10

**Comment by Arsh1a** [comment]
I've fixed the issue in the following pull request: #12497

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12343
