### ISSUE TITLE
Formatted date is more better for list tables

### ISSUE THREAD

**Issue by Developer-Nijat** [strapi/strapi#12502]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I think formatted date is more better for list tables. Current format is not comfortable. Look at below example screenshot

### Why is it needed?

Shorter fields will allow us to see more information

### Suggested solution(s)

I suggest use moment format. Example DD.MM.YYY HH:mm

![strapi-date-format(1)](https://user-images.githubusercontent.com/51002164/153744198-db103764-fc73-407b-9885-b9844b0761a5.png)

**Comment by ippoippo** [comment]
My preference would be for it to be configurable.
For example, I would like YYYY/MM/DD HH24:MI.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12216
