### ISSUE TITLE
Yarn PnP warns about undeclared dependencies in @strapi/admin

### ISSUE THREAD

**Issue by 1nVitr0** [strapi/strapi#12505]
### Describe the bug

When running `develop` using yarn in PnP mode, it immediately exits with an error or throws multiple warnings in `loose` mode. The warnings are:

```
(node:37369) [MODULE_NOT_FOUND] Error: node-fetch tried to access encoding (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: @strapi/admin tried to access whatwg-fetch, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:37369) [MODULE_NOT_FOUND] Error: @strapi/admin tried to access react-is, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Additionally it throws the following error, which does not seem to have any visible consequences (I'm guessing it is supposed to open the browser?):

```
Error: spawn ENOTDIR
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at open (/home/aram/yarn-pnp/.yarn/cache/open-npm-8.2.1-f135ffeb36-fcde005918.zip/node_modules/open/index.js:205:34)
    at async Strapi.openAdmin (/home/aram/yarn-pnp/.yarn/unplugged/@strapi-strapi-npm-4.0.7-629da0ab63/node_modules/@strapi/strapi/lib/Strapi.js:208:7)
```

### Steps to reproduce the behavior

1. Create a new strapi-app using `yarn create strapi-app`
2. Create a .yarnrc.yml file wih `pnpMode: loose`
3. Run `yarn install`
4. Run `yarn develop`

### Expected behavior

All dependencies should be listed as dependencies and not throw warnings or errors .

### System

- Node.js version: v16.13.0
- NPM version: `yarn` v3.1.1
- Strapi version: 4.0.7
- Operating system: Ubuntu 21.10

**Comment by 1nVitr0** [comment]
On a larger project I also get

```
(node:6284) [MODULE_NOT_FOUND] Error: @strapi/strapi tried to access @strapi/plugin-i18n, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:6284) [MODULE_NOT_FOUND] Error: @strapi/strapi tried to access @strapi/plugin-users-permissions, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:6284) [MODULE_NOT_FOUND] Error: @strapi/strapi tried to access sqlite3, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by MrChrisRodriguez** [comment]
FYI the lack of explicitly defined dependencies is [causing issues for new users](https://github.com/strapi/strapi/issues/13158#issuecomment-1111825777) (now that React 18 launched). Explicitly defining dependencies would also protect against issues like that in the future.

**Comment by kibblerz** [comment]
https://github.com/strapi/strapi/pull/13513#issuecomment-1151460208

I opened this pull request. With these changes, I have successfully gotten yarn to use PnP without allowing fallback or pnpMode: loose. 

I haven't been able to test it yet with npm install or nodeLinker, so there may need to be some adjustments. 

If testing this out, make sure to add the dependencies from the root of the Strapi repository to your Strapi app. There's quite a few of them due to the way the admin serves from the Strapi application

**Comment by Imshubh69** [comment]
it's been 1 month and still this issue isn't resolved

**Comment by derrickmehaffy** [comment]
Should be address by: https://github.com/strapi/strapi/pull/13769
