### ISSUE TITLE
How can I get role user to be displayed at login ?

### ISSUE THREAD

**Issue by DevToong** [strapi/strapi#12509]
### Describe the bug

How can I get role user to be displayed at login in strapi V4 like in strapi V3?

### Steps to reproduce the behavior

http://localhost:1337/api/auth/local

### Expected behavior
in V3

![V3strapi](https://user-images.githubusercontent.com/86232812/153802770-ec739ed7-40b8-4632-ab74-c4b96ce08f28.jpg)

in V4
![strapi4](https://user-images.githubusercontent.com/86232812/153802900-2e193167-b7e3-4c85-a7c8-405b0c736d3d.jpg)

### System

- Node.js version: v14.18.2
- NPM version:
- Strapi version: v4.0.6
- Database:
- Operating system:Mac M1

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11957
