### ISSUE TITLE
Unable to locate and change the route where the docs are located

### ISSUE THREAD

**Issue by jared-leddy** [strapi/strapi#12507]
### Describe the bug

The route for publishing your docs is not identified. There are also no mentions of how to set a custom route or subdomain. Where are these docs published (when you install and use this plugin) and how can you change it? 

### Steps to reproduce the behavior

Review: 
https://market.strapi.io/plugins/@strapi-plugin-documentation

### Expected behavior

Was expecting to easily find and locate the answer.

**Comment by derrickmehaffy** [comment]
https://docs.strapi.io/developer-docs/latest/plugins/documentation.html
