### ISSUE TITLE
Error in deleteMany query

### ISSUE THREAD

**Issue by mahmoudmy** [strapi/strapi#12501]
### Describe the bug

`deleteMany` has a problem with params

### Expected behavior

I'm trying to use `deleteMany ` for bulk delete operation, but it fails.

### Code snippets

This is my model:
```json
{
  "kind": "collectionType",
  "collectionName": "refrences",
  "info": {
    "singularName": "refrence",
    "pluralName": "refrences",
    "displayName": "refrence",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "status": {
      "type": "enumeration",
      "enum": [
        "unseen",
        "approved",
        "rejected",
        "noAnswer"
      ],
      "default": "unseen",
      "required": false
    },
    "comment": {
      "type": "richtext",
      "required": false
    },
    "expert": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::users-permissions.user"
    },
    "suggestion": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::suggestion.suggestion",
      "inversedBy": "refrences"
    }
  }
}
```

when I try to use `deleteMany` :
```js
strapi.db.query('api::refrence.refrence').deleteMany({
    where: {
          suggestion: 3,
          status: 'unseen'
    },
});
```
this error occures:
```
Error: delete from `refrences` where (`t2`.`id` = 3 and `status` = 'unseen') - SQLITE_ERROR: no such column: t2.id
```
### System

- Node.js version: 14
- NPM version: 8
- Strapi version: 4.0.6
- Database: Sqlite
- Operating system: Windows 10

**Comment by salar-amr** [comment]
there are many bugs around deleteMany method, I also have same issue exactly same error "unknown column t2.id"
also when using deleteMany related data (child table or link table) won't be deleted (however when using single delete operation it is CASCADE on delete by default)
as a temporary hack you can use "Promise.all" api
