### ISSUE TITLE
Populate Body Names

### ISSUE THREAD

**Issue by aukgit** [strapi/strapi#12510]
### Please describe your feature request

- [ ] Currently in strapi v4, it requires to use populate specific model names to get the json response, please add a method or button to generate all these populate model names.

### Summary

Currently in strapi v4, it requires to use populate specific model names to get the json response, please add a method or button to generate all these populate model names.

### Why is it needed?

Too much work to figure out which dynamic zones are used and figuring out it's names

### Suggested solution(s)

Kindly add a button to give the query names for populate

**Comment by derrickmehaffy** [comment]
We won't add a button or something but we are planning to add more glob options like `*.*` and `**` in addition to the current `*` population
