### ISSUE TITLE
Clone or Copy Content, Component, Model

### ISSUE THREAD

**Issue by aukgit** [strapi/strapi#12518]
### Please describe your feature request

- [ ] There should be a button to clone component (Clone component with a new name)
- [ ] There should be a button to clone content records and data.
- [ ] There should be a button to clone Model with new name

### Summary

Cloning feature on component, content, model.

### Why is it needed?

Sometimes it is very tiresome to recreate the same component with a slight change, it would be better if there is cloning feature. Also same goes for content, the same content creation with slight change could be done using the cloning feature.

### Suggested solution(s)

Add clone button with component, model, types, contents

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/9429

**Comment by rohitashwabgp** [comment]
Please any update on this feature ?

**Comment by derrickmehaffy** [comment]
Please see the link to the other issue
