### ISSUE TITLE
Unable to filter based on media/upload values

### ISSUE THREAD

**Issue by kibblerz** [strapi/strapi#12524]
### Describe the bug

When attempting to query the API and filtering by uploads/media, the API responds with an Internal Server Error.

### Steps to reproduce the behavior

1. Choose a Content-Type/Endpoint that implements the upload/media plugin.
2. Navigate to the API endpoint and add populate parameters for the media field and then filter attempt to filter by images with a null $url. Like this: /api/endpoint?populate[image][filters][id][$notNull]=true&filters[image][url][$notNull]=true
3. You should receive an Internal Server Error. Knex will report "Unknown column 't0.url' in 'where clause'"
4. If you attempt to filter by id in the filter clause like : filters[image][id][$notNull]=true, it will use the id from the content type being queried and not the upload ID.

### Expected behavior

Filtering by Media/Uploads should render the correct results. They seem to be rather simple joins so it shouldn't be difficult to join them when being queried so that filter options can be used.

### Code snippets

This is the query Knex is executing when trying to filter by uploads. When filtering by a relational content type, the query typically includes a join with the relevent type. Currently it seems that Strapi is combining the data after query.

'select `t0`.*, `t0`.`id` from `endpoint` as `t0` where (`t0`.`url` is not null and `t0`.`published_at` is not null) limit ?'

### System

- Node.js version: v16
- NPM version: 8.1.2
- Strapi version: v4
- Database: Aurora DB
- Operating system: Mac OSx (local development)/Alpine Linux (Deployed on)

**Comment by derrickmehaffy** [comment]
We don't support filtering on polymorphic models like upload or dynamic zones at this time and don't have any plans to.

**Comment by an-nadaa** [comment]
@derrickmehaffy any explanation/justification for that? and any work around for people who want to filter by dynamic zone and still have paginations in place? How should we approach this?

**Comment by gimyboya** [comment]
@derrickmehaffy any explanation/justification for that? and any work around for people who want to filter by dynamic zone and still have paginations in place? How should we approach this?

**Comment by derrickmehaffy** [comment]
It's too complex and would have horrible performance, if you need that lavel of complexity your better off writing your own database queries using knex (`strapi.db....`)

I'm going to lock this issue as it's something I've already confirmed with our CTO as something we won't entertain.
