### ISSUE TITLE
User-Permissions-Plugin doesn't provide policies, Admin Policies don't seem to work either

### ISSUE THREAD

**Issue by maximilianschmidt** [strapi/strapi#12521]
### Describe the bug

In the [Docs](https://docs.strapi.io/developer-docs/latest/development/backend-customization/policies.html#plugin-policies) it is mentioned that the Plugin 'User & Permissions' provide a couple of policies out of the box to be used to secure API routes. However, this is not the case as can be seen when typing `yarn strapi policies:list` (please see screenshot attached, note that policies no 3 and 4 are custom policies to test things out). Also there is no policies-folder under `node_modules/@strapi/plugin-users-permissions/server`. As a workaround, i am trying to secure routes by doing the following: 

```
{
    method: "GET",
    path: "/exampleroute",
    handler: "example.handler",
    config: {
      policies: ["admin::isAuthenticatedAdmin"],
    }
}
```

This does not work either as the response is always `401` with the following error message: 

```
{
    "data": null,
    "error": {
        "status": 401,
        "name": "UnauthorizedError",
        "message": "Missing or invalid credentials",
        "details": {}
    }
}
```

The JWT-Token used in the Authorization Header is `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ0ODM0NjUyLCJleHAiOjE2NDc0MjY2NTJ9.YHbNyXeEtbSvP9Zhg8RY6isc89jcHul9AshdZmzU4Ss`, the user from the JWT (User ID 1) is a Super Admin. 

Am i missing something important here or is this a bug?

### Steps to reproduce the behavior

1. Type `yarn/npm strapi policies:list`
2. Policies mentioned in the docs are not present

OR 

1. Create custom route
2. Try to secure with `admin::isAuthenticatedAdmin` policy
3. Make call to created custom route with Authorization Header present
4. See 401-error although being a super admin

### Expected behavior

Users-Permissions-Plugin should provide the mentioned Policies. The `admin::isAuthenticatedAdmin` should work as intended, e.g. letting JWT from Admin Users make a request to a protected route

### Screenshots

<img width="399" alt="image" src="https://user-images.githubusercontent.com/4113660/153853644-23aed269-59be-4293-887b-f55bd73e04dd.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.16.1
- NPM version: 7.14.0
- Strapi version: 4.0.7
- Database: Default
- Operating system: Mac OS 12.0.1

### Context

Additionally, when setting `auth: false` in the config of the route, the context has no `ctx.state.user`. When messing directly with `@strapi/strapi/lib/services/auth/index.js` the context also has no `ctx.state.user`.

**Comment by kerwanp** [comment]
I am having the same issue, did you find a solution?

**Comment by maximilianschmidt** [comment]
im in mobile so only a brief response: turns out you need to add the user you want to authenticate with to the Permissions-Plugin in the Content Area of the backend, the Plugin creates a content type "user". i was trying to authenticate with the user I use to log in to the backend itself. turns out the auth policies don't seem to work with those users. 

i circumvented by using an API key. 

please let me know if I should elaborate once I'm on a PC again

**Comment by maximilianschmidt** [comment]
oh, and you need to authenticate the user from the permission-plugin via the API /login call and use the token from the response, I guess. haven't tested that though

**Comment by martin-landhi** [comment]
Hey @maximilianschmidt 

I am having the same issue and i did not undertood your answer.

I am creating a plugin with a custom route that i only want to be acceded by a user with the role "authenticated" that comes by default.

I am trying to use the jwt token in the bearer token of the call that i made on my custom route but i get 401 unauthorized.

how can i make that call and also get the user data on the controller? the plugin did not come with the policies that the docs say here:

![Selection_777](https://github.com/strapi/strapi/assets/101138298/b794a8e3-949d-49db-932e-67ce6c0c314e)

**Comment by martin-landhi** [comment]
Ok, the issue was that the api have to be in "content-api" and be /api. Without that the auth and ctx.stata.user did not work.....

the documentation have to be clear with this.

**Comment by devDalys** [comment]
> Хорошо, проблема заключалась в том, что API должен находиться в «content-api» и быть /api. Без этого auth и ctx.stata.user не работали.....
> 
> документация должна быть ясна с этим.

Can you please show me how it should turn out ? It's still not working for me.

**Comment by mrusmanali** [comment]
@devDalys 

This is how your routes file should look like

```
module.exports = {
  'admin': {
    type: 'admin',
    routes: []
  },
  'content-api': {
    type: 'content-api',
    routes: []
  }
};
```

**Comment by vripoche** [comment]
I don't understand why this issue is closed, if you call API with `request()` in Strapi UI custom component, you have an Admin token in `Bearer` but still a `401`.
Policy `admin::isAuthenticatedAdmin` should be available for that purpose, no ?

**Comment by hacktisch** [comment]
> @devDalys
> 
> This is how your routes file should look like
> 
> ```
> module.exports = {
>   'admin': {
>     type: 'admin',
>     routes: [
>        // admin only routes (works only from strapi admin)
>     ]
>   },
>   'content-api': {
>     type: 'content-api',
>     routes: [
>        // routes exposed to public 
>     ]
>   }
> };
> ```

I don't know why two people downvoted your comment, this finally made it work for me (Strapi v4.24.5) and this wasn't documented anywhere with Strapi. Thanks! 

So to clarify, this:
* Moves the route from /[routepath] to /api/[routepath]
* Adds a section for your plugin to the roles' permissions settings (at /admin/settings/users-permissions/roles)
* Makes the user available in your plugin via ctx.state.user
