### ISSUE TITLE
strapi@alpha installs in wrong directory

### ISSUE THREAD

**Issue by template01** [strapi/strapi#1252]
Hi,

When i run the installer ```npm install strapi@alpha -g``` strapi installs it self into ```/usr/lib/node_modules/strapi``` instead of ```/usr/local/lib/node_modules/strapi``` where the stable version is installed. 
Any ideas on how to fix this?
If I manually copy the package into the right directory works properly.

Cheers
Lasse

**Comment by lauriejim** [comment]
Hello @template01 , do you have the same issue with an other node modules ?

**Comment by template01** [comment]
Hey. This must be an issue of npm. As you suggested other globally installed packages are also stored in ```/usr/bin/ ``` and not ```/usr/local/bin/```. I'll try to solve this issue in some other way.
Thanks for responding!
