### ISSUE TITLE
Admin UI with plugin build time increased significantly

### ISSUE THREAD

**Issue by kovapatrik** [strapi/strapi#12527]
### Describe the bug

When upgrading from 4.0.2 to any greater version, it takes 700 seconds or more to build the Admin UI, at 4.0.2 it was about 80sec. I'm using a Wysiywg plugin. I have followed the [official Strapi guide](https://docs.strapi.io/developer-docs/latest/guides/registering-a-field-in-admin.html#setting-up-the-plugin) to write that. If I simply disable the plugin, then the build time get normalized again.

### Steps to reproduce the behavior

1. Create Strapi project with version > 4.0.2
2. Follow the official guide to add an Wysiwyg plugin to the Admin UI
3. yarn build or npm run build
4. Experience the build time

### Expected behavior

I don't see any compatibility issues or any task to do, when updating versions (aside from the middlewares.js change, but it didn't solve my problem) so I would expect to work everything like at version 4.0.2.

### System

- Node.js version: v14.17.4
- NPM version: 6.14.14
- Yarn version: 1.22.11
- Strapi version: >= 4.0.3 (I'm guessing at this point, but I tried 4.0.3, 4.0.5, 4.0.7)
- Database: postgres or local
- Operating system: Windows 10

**Comment by salar-amr** [comment]
I faced the same issue after adding custom Wysiwyg plugin, I really don't know why this steps fix the issue but  worked for me
1- remove ck-editor (or any other library u r usign for text editor) from package.json file of your custom plugin
2- install your text editor package in the main package.json file (top level)
3- (optional) try "ckeditor4-react" library

**Comment by kovapatrik** [comment]
Thanks for the help, but sadly it doesn't solve the problem on my side.

**Comment by derrickmehaffy** [comment]
I believe as of v4.1.18 (might have been slightly earlier) we massively increased the performance of the admin build. I'll set this issue as closed/fixed but if you still notice speed problems feel free to respond back and we will reopen.
