### ISSUE TITLE
Knex connection timeout issue on Strapi start

### ISSUE THREAD

**Issue by eugeneingram** [strapi/strapi#12535]
I've been experiencing a similar issue to that described here: https://github.com/strapi/strapi/issues/11860

This is occurring when attempting to deploy to a Digital Ocean environment.  I've tried all sorts of settings for the connection pool settings on the Postgresql database and in database.js to no avail.  The `strapi start` process eventually fails with the knex connection timeout error.

Is there a minimum amount of DB RAM and size of connection pool Strapi needs to be able to start and run migrations for updated/created models?  I'm just wondering if a Strapi instance with many collections and components is not suited to a 1GB database instance?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
