### ISSUE TITLE
Can't access user's role from usersPermissionUser query

### ISSUE THREAD

**Issue by forntoh** [strapi/strapi#12533]
### Describe the bug

When I fetch user information for `query usersPermisionUser` in graphql, the `role` object is not populated. The server says "Forbidden access", I have given all rights to role in the settings.

### Steps to reproduce the behaviour

1. Add a user.
2. log in as that user and grab his token.
3. Write the query for `usersPermissionUser` in graphql playground while including the role in the return data fields.
4. Add the token to the header.
5. Add the user's id as a parameter.
6. Launch the query.
7. Observe that the `role` field will be null

### Expected behavior

You should be able to fetch the role of a user if you have permission to (Authenticated).

### Screenshots

![image](https://user-images.githubusercontent.com/27886627/154047717-11342990-8606-4eb4-8156-f630a340ab80.png)
![image](https://user-images.githubusercontent.com/27886627/154047845-7d7d28ca-93db-49c0-a3ab-3eeb7be34acb.png)

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.0.7
- Database:
- Operating system: Windows 11

**Comment by derrickmehaffy** [comment]
duplicate https://github.com/strapi/strapi/issues/11957

**Comment by forntoh** [comment]
I tried all the proposals in #11957 but `role` is still not populated. It throws an error and tells me `Forbidden access`. The role field is `null`
