### ISSUE TITLE
Cleaning date input causing error

### ISSUE THREAD

**Issue by martincapek** [strapi/strapi#12546]
### Describe the bug
When clicking on X to clean date input it cause error.

### Steps to reproduce the behavior

1. Add date to date input
2. Click on X
3. Click on save 

<img width="369" alt="Screenshot 2022-02-16 at 10 49 58" src="https://user-images.githubusercontent.com/12203768/154239049-2cdc04dd-9a6b-4972-aa45-7f4aae73652e.png">
<img width="396" alt="Screenshot 2022-02-16 at 10 51 20" src="https://user-images.githubusercontent.com/12203768/154239307-0466e884-b9bc-43ef-ba45-175e96159dc8.png">

<img width="418" alt="Screenshot 2022-02-16 at 10 49 00" src="https://user-images.githubusercontent.com/12203768/154238881-3828be76-892c-4e16-8c7e-0bdd73215c98.png">

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: v4.0.2
- Database: PostgreSQL
- Operating system: macOS

**Comment by gu-stav** [comment]
This issue will be fixed by `4.0.8` and this PR: https://github.com/strapi/strapi/pull/12445

**Comment by martincapek** [comment]
@gu-stav thanks :)
