### ISSUE TITLE
More options for "Entry title"

### ISSUE THREAD

**Issue by oriooctopus** [strapi/strapi#12549]
**I would be happy to take this feature on myself with a bit of guidance**

## Feature request

 I have a collection with a rich text field called “text”. Because it is rich text, I can’t use it as the entry title when I configure the view. This is very inconvenient because I’m either faced with not having a label, or having to duplicate the data with a normal text field called “InternalLabel”

### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

My request would be to either 
1. Add core support for rich text fields and long text fields as entry titles. For rich text fields the unparsed string could be shown, and perhaps for long text fields new lines could be removed or shown as \n
2. Add a way for us to extend it ourselves via plugins or other customization

### Why is it needed?

Entry title is a crucial feature for easier management because it saves you time from having to click into something. This is especially helpful when there are maybe 50 things, and none of them have a useful entry title, and you have to click into each one to find what you want.

Adding a "Short text" label just for this purpose is doable of course, but to me an unclean solution.

### Suggested solution(s)

Mentioned above in the summary

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/more-options-for-entry-title

Thanks!
