### ISSUE TITLE
svg icon is not showing in api response

### ISSUE THREAD

**Issue by ranshine** [strapi/strapi#12548]
I am newbie to strapi, i created a single type page with components and different fields. In json api response i am able to see everything except svg icon info. I added svg images to my assets and added svg images in content manager specific screen. Is there anything i need to do.
other images types i am able to see
http://localhost:1337/api/home-screen?populate=*

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
