### ISSUE TITLE
ApplicationError is not a constructor

### ISSUE THREAD

**Issue by merijnponzo** [strapi/strapi#12547]
I changed a component name from 'Dienstenslider' to 'Dienstslider', I also renamed the .json scheme of the component from
**.src/components/flexblocks/dienstenslider.json** to **.src/components/flexblocks/dienstslider.json**

Within the json file i changed **"collectionName": "components_flexblocks_dienstensliders"** to **"collectionName": "components_flexblocks_dienstsliders"**

I cleared the .cache and build folder
Then i got the error:
```
[2022-02-16 12:23:04.318] error: ApplicationError is not a constructor
TypeError: ApplicationError is not a constructor
    at /pf_backend/node_modules/@strapi/plugin-graphql/server/services/builders/dynamic-zones.js:17:15
```

Nodejs v14.18.3
Npm 6.14.15
Strapi 4.07 (error also with 4.05)
Postgres
Mac Os Catalina

Going further i tried to manually delete all 'Dienstenslider' from the database

Within @strapi/plugin-graphql/server/services/builders/dynamic-zones.js:17:15

```
  const componentsTypeNames = components.map(componentUID => {
      const component = strapi.components[componentUID];
      console.log(component)
      if (!component) {
        throw new ApplicationError(
          `Trying to create a dynamic zone type with an unknown component: "${componentUID}"`
        );
      }
```
I am not sure if ApplicationError is not a constructor should happen in the first place.
But the componentUID is still looking for 
flexblocks**.diensten**slider

So const component = strapi.components[componentUID]; results into **undefined**

A quick fix for me could be to find flexblocks.dienstenslider from where it's loaded

any tips are welcome

**Comment by merijnponzo** [comment]
It appears, after a fresh install of strapi, and copying my flexibele blocks and api to the .src folder that there still was a 'dienstenslider' in one of my api's, after renaming this to 'dienstslider' it works again

```
 "blocks": {
      "type": "dynamiczone",
      "components": [
        "flexblocks.dienstenslider"
      ]
    }
```

However, this error doesn't ring any bell and has more to do with a bug within dynamic-zones.js then renaming dynamic zones ;-)
```
TypeError: ApplicationError is not a constructor
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
