### ISSUE TITLE
How to create a custom end point to generate random two items

### ISSUE THREAD

**Issue by AhmedSarhan** [strapi/strapi#12554]
Hello I'm not sure why I don't get any replies on the forum but I need help so I would appreciate it very much if I can get any help here

I would like to create a custom end point for example (/random-posts) that returns every time it’s called two random posts from my posts collection.

how can I do that? I would like to point out that I’m using GraphQl so if I can just do some work around in the Query that would work too.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by AhmedSarhan** [comment]
@derrickmehaffy  I already asked a question here and didn't get any help and I know it is not mandatory but I would really appreciate the help as I have some what of a  tight deadline 
https://forum.strapi.io/t/how-to-create-a-custom-end-point-to-generate-random-two-items/15603/1

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I already asked a question here and didn't get any help and I know it is not mandatory but I would really appreciate the help as I have some what of a tight deadline https://forum.strapi.io/t/how-to-create-a-custom-end-point-to-generate-random-two-items/15603/1

I'm sorry you haven't gotten an answer yet, someone may not have the answer you are looking for but the GitHub issues are not the place for questions only bug reports which is why I closed this.

I don't have an answer for you as doing any kind of random action is not a simple process

**Comment by AhmedSarhan** [comment]
@derrickmehaffy I totally understand so I basically did something that might not be the best to do in that process but it wasn't also that complicated 
I went and made a custom endpoint and inaide of it I used the database query strapi offera to fetch with findmany 
Made the limit two 
Used the $or condition in where 
And the not so smooth part was I passed two ids in the or each one is a Math generated number the first between 0,250 and the second ia between 251 and 500 and that did it for now
But I can't get a graphql query for my custom end point not sure why
My new endpoint goes as /api/random/posts
