### ISSUE TITLE
Add support for multiple content types to component relational fields

### ISSUE THREAD

**Issue by alee8648** [strapi/strapi#12552]
---
name: Add support for multiple content types to component relational fields
about: Allow content editors to select from multiple different content types at a time in a relational field
---

### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Add an option to component relational fields that allows content editors to choose from multiple different content types at a time, e.g. Posts, Pages, Projects. Currently, the field can only allow for one or more from the same content type.

### Why is it needed?

Our use case is a spotlight component that links to content from all over the site, not just a specific subtype of content. Other use cases might limit the field to just 2 or 3 content types that can be linked to from a slider or grid.

### Suggested solution(s)

When adding a relational field to the component in the content type builder there should be 2 additional options:
- X has one Content Type A or Content Type B (or Content Type C ...)
- X has many Content Type A or Content Type B (or Content Type C ...)

![image](https://user-images.githubusercontent.com/11977269/154284666-78e3d18b-cd3e-444c-81d6-d9839984e242.png)

In the content builder, this should be reflected in the dropdown for the field, which will now include a variety of different content types. It should include a marker to indicate what content type each item belongs to.

### Related issue(s)/PR(s)

--

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/5798
