### ISSUE TITLE
Media Library Crop feature : small cropped result

### ISSUE THREAD

**Issue by gianniprata** [strapi/strapi#12568]
### Describe the bug
In Media Library, when I want crop an image, the cropped image resolution is very small and unusable.

### Steps to reproduce the behavior

1. Go to Media Library
2. Choose an image and Click on Edit button
3. Click on crop button
4. Select an area
5. See the very small image size 

### Expected behavior
As describe here https://strapi.io/features/media-library,
the resolution of the cropped image remains dependent on the resolution of the original image

### Screenshots
![image](https://user-images.githubusercontent.com/3144797/154470576-ae6103ed-3ba0-4fc2-8f68-601267d4f6c9.png)
here we see in the black frame, the ridiculous size of the cropped image (65X81px)

 expected behavior :
![image](https://user-images.githubusercontent.com/3144797/154470664-85c76dfd-68ca-4d94-8caf-c6ff179f94cd.png)

### System

- Node.js version: 14
- NPM version: >=6
- Strapi version: V4.0.7
- Database: SqlLite (local) Postgres
- Operating system:

**Comment by jobe451** [comment]
+1 same issue here

**Comment by yanniskadiri** [comment]
Thanks @gianniprata we'll explore the issue during the next weeks and let you know if we can find a quick fix or if it requires a bit more work.

**Comment by gu-stav** [comment]
@gianniprata I just merged a PR, which will fix this issue. It will be included in the next release. If you encounter any problems, please let me know 🌻

**Comment by gu-stav** [comment]
@gianniprata Can to try to delete your `.cache` and `build` folder a run a new clean build?
