### ISSUE TITLE
Hard coded url domain and port number

### ISSUE THREAD

**Issue by J-F-Liu** [strapi/strapi#12564]
### Describe the bug

Running Strapi inside docker container with port mapping 1337->1338, but the following request blocks page loading.
When use port mapping 1337->1337, the admin page cannot be opened on another machine.

```
http://localhost:1337/admin/project-type
```
### Expected behavior

All request urls use the same port number.

### Screenshots

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1472963/154428074-3b6f6f45-a73a-454d-a952-ef646363919f.png">

![2e384eccfc12bf4403f630fb89f9d37](https://user-images.githubusercontent.com/1472963/154429165-7db73e24-e46b-4188-9ab0-471c8bc5bf93.png)

### System

- Node.js version:  v14
- NPM version:
- Strapi version: 4.0.8
- Database: SQLite
- Operating system: Alpine

**Comment by tiennm-galaxt** [comment]
thanks for the issue i had the same problem on production build

**Comment by dzcpy** [comment]
Same problem

**Comment by fgbreel** [comment]
I have this issue as well and seems there is no way to set the admin url during runtime, which is not much devops friendly.

**Comment by derrickmehaffy** [comment]
This is intended, you need to configure the url in `./config/server.js` and rebuild the admin via `yarn build` or `npm run build`.

There is also an option to have your admin at a different location than the backend so you can set that location in `./config/admin.js`

Marking as closed as the current is intended.
