### ISSUE TITLE
Icon can not be used while using short-text type

### ISSUE THREAD

**Issue by mrklika** [strapi/strapi#12566]
### Describe the bug

Hi, It is not possible to insert an icon to a short-text type field, it results in internal server error.  It was possible in the previous version 3.4.

### Steps to reproduce the behavior

1. Create new collection-type with short-text field "name"
2. Create new item within the collection type and insert name as "Hello there dev 🤝"
3. Save
4. Internal server error appears

### Expected behavior

Could be possible to insert any text to short-text type.

### Screenshots

![image](https://user-images.githubusercontent.com/14203910/154451240-c14445c2-737e-4383-943d-be4690082338.png)
![image](https://user-images.githubusercontent.com/14203910/154451369-028e0102-fa8c-4ece-ba9e-062dde520071.png)
![image](https://user-images.githubusercontent.com/14203910/154451545-e58173af-2a97-4204-a22d-087a399cd8e8.png)

### System

- Node.js version: v16.9.1
- Strapi version: 4.0.7
- Database: MariaDB

**Comment by godzzo** [comment]
It is probably a DB [character encoding](https://stackoverflow.com/questions/31698871/er-truncated-wrong-value-for-field-on-saving-some-strings-to-mysql) error. Icon = Emoji character. Should use `utf8mb4`.

`ALTER DATABASE <database-name> CHARACTER SET utf8mb4`

**Comment by derrickmehaffy** [comment]
> It is probably a DB [character encoding](https://stackoverflow.com/questions/31698871/er-truncated-wrong-value-for-field-on-saving-some-strings-to-mysql) error. Icon = Emoji character. Should use `utf8mb4`.
> 
> `ALTER DATABASE <database-name> CHARACTER SET utf8mb4`

It is absolutely a char encoding problem, not a Strapi problem so going to close the issue but feel free to discuss

**Comment by UnKnoWn-Consortium** [comment]
@derrickmehaffy Sorry for bringing up an old closed "issue". But I have encountered this even though my MariaDB database setup has the correct charset and collation. 

I then figured if this has anything to do with the `mysql` connector. I checked the [connection options](https://github.com/mysqljs/mysql#connection-options) and bingo there is a `charset` field that defaults to `UTF8_GENERAL_CI`. 

Do you think it is sensible to have this set to `utf8mb4` at the template configuration for the mysql connector?
