### ISSUE TITLE
Fields resizing is not saved 

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#12574]
### Describe the bug

It's about the release of <https://github.com/strapi/strapi/pull/12398>.
Restarting the server will cause the configuration to be lost.
Only the "50%" option will be saved.

### System

- Node.js version: v16.13.2
- NPM version: 8.4.0
- Strapi version: 4.0.8
- Database: mysql
- Operating system: debian11 (container)

**Comment by smoothdvd** [comment]
I meet this issue too. Some times it will reset to 50% and the field's position also be put in the last one in the configure view.

**Comment by gu-stav** [comment]
Thank for you reporting this issue. We can reproduce it and will work on it as soon as possible.
