### ISSUE TITLE
[v4] REST API - Populate with filtering broken after update from 4.0.7 to 4.0.8

### ISSUE THREAD

**Issue by signly-projects** [strapi/strapi#12578]
### Description

I was working on a query that consisted of using populate with filtering using Strapi's REST API. Very similar to what you guys have in your docs. e.g.

`GET http://localhost:1337/api/book?populate[pages][filters][pageNumber][$eq]=100`

All was working fine until I decided to update to the new version 4.0.8 (from v4.0.7). 

### Expected behavior

The expected behaviour is to get back all the books containing the populated page entry that has a property pageNumber equal to 100. Instead, I get the following error:

```
[2022-02-17 19:16:38.305] error: Cannot read properties of undefined (reading 'attributes')
TypeError: Cannot read properties of undefined (reading 'attributes')
```

If I rollback to Strapi v4.0.7 all works fine - I get the expected result.

This is either a bug OR the documentation hasn't been updated.

### System

- Node.js version: 16.13.2
- NPM version: 8.3.0
- Strapi version: 4.0.8
- Database: PostgreSQL 14.1
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.0 all relationship filtering is broken

![image](https://user-images.githubusercontent.com/8593673/154579124-a282b45a-aa77-4f99-bde6-0d42f3c3d728.png)

**Comment by derrickmehaffy** [comment]
Confirmed on v4.0.8 also

![image](https://user-images.githubusercontent.com/8593673/154579695-aa28179c-1561-4a5a-b2d3-491852dd9bbd.png)

**Comment by derrickmehaffy** [comment]
Normal filtering on relations is fine, but filtering during population is not

Test project with database, see the readme for QS reproduction
[test12578.zip](https://github.com/strapi/strapi/files/8092624/test12578.zip)

**Comment by Convly** [comment]
Hey, sorry you faced this issue, I've made a fix in the PR mentioned above. Hope it'll fix your problem.
