### ISSUE TITLE
Cannot click 'pencil' icon in Content Manager

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#1257]
**Informations**
- **Node.js version**:
9.0.0
- **npm version**:
6.0.1
- **Strapi version**:
3.0.0-alpha.12.2
- **Database**:
MongoDB v3.6.5
- **Operating system**:
Mac OS X Sierra
**What is the current behavior?**
Nothing happens when I click the icon ( I can however click anywhere else on the line )

**Steps to reproduce the problem**
Click the pencil icon.

**What is the expected behavior?**
To edit the entry (just as when clicking anywhere on the line).

**Suggested solutions**
Well, erhm ... how about making it work as expected!?

**Comment by blaasvaer** [comment]
Well, as described in the issue – I know that.

But how about making a great UX, and just fix the link on the icon? It seems bloody weird that I can ANYTHING BUT THE ICON!

When basic stuff like this isn't working, you're telling me that all sorts of bugs will crawl through the cracks ... there seems to be A LOT of basic stuff that isn't working (skim the issues, please).

**Comment by blaasvaer** [comment]
Firefox Quantum: 59.0.2 (64-bit)

**Comment by mnlbox** [comment]
I also use Strapi with Firefox and I think it's need more fix in UI / UX in Firefox. :wink:

**Comment by derrickmehaffy** [comment]
@blaasvaer I'm sure the Strapi team would appreciate people like you to create pull requests to help fix issues. They are a small team of guys and may not have enough time to fix these issues at our beck and call. :smile: 

They are after all only human, I myself have made a few small but needed PRs to help the team and do testing to help them cut down on fix time. With this being an open source project, the development is not completely up to the owners of the repo but everyone who uses it.

I will say comments like this:

> Well, as described in the issue – I know that.
> 
> But how about making a great UX, and just fix the link on the icon? It seems bloody weird that I can click ANYTHING BUT THE ICON!
> 
> When basic stuff like this isn't working, you're telling me that all sorts of bugs will crawl through the cracks ... there seems to be A LOT of basic stuff that isn't working (skim the issues, please).

Can be quite demoralizing to the team, they are working as hard as they can.

**Comment by soupette** [comment]
@blaasvaer anyway thanks for reporting this bug.

Here's the [fix](https://github.com/strapi/strapi/blob/content-manager-filters/packages/strapi-plugin-content-manager/admin/src/components/TableRow/index.js) if you want to have it working before the next release (it's in the IcoContainer component, if forgot to add the `onClick` handler).

**Comment by johannpinson** [comment]
Hey @soupette,

I watched this issue yesterday but don't have the time to push my commit before you.
To avoid repetitive function calls, I change a little the behavior of the component.

You can see the change in the commit linked to this issue.
Do you think the pull request is still welcome?

**Comment by soupette** [comment]
@johannpinson sure your PR is more than welcomed, in fact it's better that the one I made!
