### ISSUE TITLE
Use UUID instead of email as unique identifier

### ISSUE THREAD

**Issue by JeremieLeblanc** [strapi/strapi#12575]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Don't require email for users. Use a different unique identifier field.

### Why is it needed?

When using providers, the email is most likely unique, but not an identifier as the user can always change the email associated with the account.
In my case, I am only allowing users to login using the Discord provider. Discord provides a unique id that should be used as the identifier instead of email. Even more so because email is not even included in the default "Identify" scope and must be requested on top of it. On Discord, the username and email can be changed quite easily and totally breaks the user saved in the Strapi database. If instead of relying on the email address, we used the unique Id, this would not affect it.
On top of this, my app is built for web3 and in this space asking the user for an email address is not standard as most people value their anonymity online.

### Suggested solution(s)

Instead of relying on the email address as the unique identifier we could used a UUID. This fixes the issue of changing email addresses, both within a local account and from providers. Most if not all providers should have a unique id that is not attached to the email address in the first place, so why not use it. It also makes the user process less opiniated and customizable.

**Comment by derrickmehaffy** [comment]
This issue was discussed with our product team and currently we don't feel this is something we would want to implement. Thank you for opening the issue and please feel free to open a feature request on our feedback database: https://feedback.strapi.io

Thank you! :pray:

**Comment by abaksha-sc** [comment]
This would solved also issue when social account doesn't have email. For example Twitch allows to create account with only phone number and we have an issue that such users cannot register:

https://github.com/strapi/strapi/blob/0e2e3dbbe6ba49ae9392cfbefa17aeabff24e504/packages/plugins/users-permissions/server/services/providers.js#L60
