### ISSUE TITLE
Populate Media and Dynamiczones from Components

### ISSUE THREAD

**Issue by noxsii** [strapi/strapi#12583]
Hey guys,
i cant get Media or Dynamiczones from Components in the API. What is wrong?

### System

- Node.js version: v14.18.3
- NPM version: v6.14.16
- Strapi version: v4.0.5
- Database: mysql
- Operating system: linux

**Comment by ephb** [comment]
Hey, 
are you using the populate parameter and not getting the desired results?

Please describe your issue in more detail:

1. Which api are you using
2. What does your query look like
3. What does your response look like

**Comment by noxsii** [comment]
Hi :)
Sure. i use the populate Paramters.

<img width="1154" alt="Bildschirmfoto 2022-02-17 um 12 15 44" src="https://user-images.githubusercontent.com/53399498/154912955-6a803ff5-5433-475a-b4b3-a2e54b08fd44.png">

and the response looks like:

`{
                    "id": 2,
                    "__component": "content.button-group"
                }`

**Comment by derrickmehaffy** [comment]
Please see: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#component-dynamic-zones

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
