### ISSUE TITLE
npx create-strapi-app fails to install sharp@0.30.1 module

### ISSUE THREAD

**Issue by andcmill** [strapi/strapi#12580]
### Describe the bug

I am getting failed install on sharp module.  See additional context section for more details.

### Steps to reproduce the behavior

1. Open terminal
2. cd into project folder
3. run this-->   npx create-strapi-app backend --quickstart

### Expected behavior

I expect the install to complete

### Screenshots

Here is the console text (error begins at `npm ERR! code ELIFECYCLE`):

npx: installed 104 in 67.302s
Creating a quickstart project.
Creating a new Strapi application at C:\Users\acm\Desktop\farfalla\VSCode\stickers\backend.
Creating files.
Error while installing dependencies:
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated 
and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstan
ces, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2
ZEqIau
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a No
de.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated sequelize@5.22.5: Please update to v6 or higher! A migration guide can be found here: https://sequelize.org/v6/
manual/upgrade-to-v6.html
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instea
d.
npm WARN deprecated @types/bson@4.2.0: This is a stub types definition. bson provides its own type definitions, so you do not need 
this installed.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade as
ap.
sharp: Installation error: getaddrinfo ENOTFOUND github.com
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current
: {"os":"win32","arch":"x64"})
npm WARN @strapi/helper-plugin@4.1.0 requires a peer of qs@6.10.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-virtualized@9.22.3 requires a peer of react@^15.3.0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN react-virtualized@9.22.3 requires a peer of react-dom@^15.3.0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.30.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)`

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.30.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\acm\AppData\Roaming\npm-cache\_logs\2022-02-17T23_14_50_068Z-debug.log
```

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd C:\Users\acm6an\Desktop\farfalla\VSCode\stickers\backend && npm install

### Code snippets

N/A

### System

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.0
- Database: "sqlite3": "5.0.2"
- Operating system: Windows 10 Enterprise, OS Build 19042.1526, Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   2.11 GHz, 64-bit operating system, x64-based processor,

### Additional context

I've read some good reviews about it and I decided/excited to give it a try only I can't seem to get past the error below.

**Comment by derrickmehaffy** [comment]
This is not an issue with Strapi itself as you are most likely missing dependencies for your system. Please check the Sharp or libvips documentation for failed builds

**Comment by CN91** [comment]
Since there are so many issues in this repo with the 'sharp' dependency of this project. Is there any way we could use strapi without sharp? I'm currently also in a bit of a rabbithole while trying to deploy Strapi to a nodejs_buildpack on a cloud foundry environment. Most of it is due to sharp and it's dependency to libvips, but since I want to use Strapi I was wondering if there could be a way / version for strapi without the Sharp dependency.

**Comment by derrickmehaffy** [comment]
> Since there are so many issues in this repo with the 'sharp' dependency of this project. Is there any way we could use strapi without sharp? I'm currently also in a bit of a rabbithole while trying to deploy Strapi to a nodejs_buildpack on a cloud foundry environment. Most of it is due to sharp and it's dependency to libvips, but since I want to use Strapi I was wondering if there could be a way / version for strapi without the Sharp dependency.

It is not possible no as sharp handles pulling file information, transformation, cropping, rotating, clearing exif data, etc. Basically all the core functions of the media library.
