### ISSUE TITLE
3.6.9 not marked as latest on NPM

### ISSUE THREAD

**Issue by jorrit** [strapi/strapi#12585]
### Describe the bug

Version 3.6.9 is nog tagged with the `latest` tag at https://www.npmjs.com/package/strapi. This means that NPM is not offering this version as update for 3.6.8.

**Comment by derrickmehaffy** [comment]
Thanks for the report, I've notified the team but closing as it's not really a bug.

**Comment by D0wn10ad** [comment]
Hi, may I know the status on this? It's been 2 months since this is reported but 3.6.9 is still not tagged with the `latest` tag

There are some bug fixes we would want to apply into our instances.

Thanks!

**Comment by derrickmehaffy** [comment]
> Hi, may I know the status on this? It's been 2 months since this is reported but 3.6.9 is still not tagged with the `latest` tag
> 
> There are some bug fixes we would want to apply into our instances.
> 
> Thanks!

We cannot set it as latest now as some packages don't use the new `@strapi/` scope thus all v3 package versions "latest" will be frozen at v3.6.8

You can still update your packages to v3.6.9 but we won't be fixing this as our focus is on the v4, once we get to the EOL date for v3 we will mark all of the outdated packages as deprecated
