### ISSUE TITLE
An error occurred while fetching the permissions

### ISSUE THREAD

**Issue by kwzm** [strapi/strapi#1258]
**Informations**
- **Node.js version**: 10.1.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongoDB
- **Operating system**: win7 x64

**What is the current behavior?**
When I clicked on  Role & Permissions link, the view alerted message "An error occurred while fetching the premissions". I had created some content types, but I found nothing in the permissions.
 
![default](https://user-images.githubusercontent.com/16114101/40416966-3c1bc8fe-5eb1-11e8-838b-38b67c9254e7.PNG)

**Steps to reproduce the problem**

Click on  Role & Permissions link

**What is the expected behavior?**

Show the permissions

**Suggested solutions**

None

**Comment by enozr** [comment]
Sometimes  I can see this error:

[2018-05-24T16:04:39.908Z] debug GET /users-permissions/routes (23 ms)
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }
[2018-05-24T16:05:45.486Z] debug GET /users-permissions/roles/5b06d64ff66e2a43b15f6e79?lang=en-US (289742 ms)
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }


[2018-05-24T16:07:32.962Z] debug GET /users-permissions/permissions?lang=en-US (193833 ms)
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }


[2018-05-24T16:01:51.559Z] debug GET /users-permissions/roles (22 ms)
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }
[2018-05-24T16:03:19.548Z] debug GET /users-permissions/roles/5b06e052ed74674e0cfc684c?lang=en-US (289045 ms)
{ Error: read ETIMEDOUT
    at _errnoException (util.js:1003:13)
    at TLSWrap.onread (net.js:620:25) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read' }

**Comment by GalEldarDev** [comment]
I managed to recreate the above issue, through a sequance of events / actions in the admin dashboard.

1. Click on **_Roles and Premissions Tab_**
2. Add a **_New Role_**
3. Name it **_Guest_**
4. Add only the _Admin_ to the **_Guest_**  array
5. Click **_Save_**

**Comment by soupette** [comment]
I managed to reproduce the issue as well. What happens is that when you create the new role `Guest` and add the admin user to it he is not allowed to access the admin panel anymore.
So in order to fix you have to set his role back to `Administrator`.

**Comment by lauriejim** [comment]
@kwzm and @enozr I'm not able to reproduce your issue. Are you trying to play with two applications with the same database ? 

@GalEldarDev your steps match with an other issue. We have to block admin user role update.

**Comment by GalEldarDev** [comment]
Thanks for the update @lauriejim .
I will do my best to push a PR with a fix in the next few days.

**Comment by lauriejim** [comment]
Hello @GalEldarDev have you an update about this issue ?

**Comment by nom4da** [comment]
I'm having issues with this too. I cannot set permissions to newly created roles. It won't load any of the permissions checkboxes.

Thanks for all your efforts!

**Comment by lauriejim** [comment]
Can you guys try with last version of Strapi. Fresh new app and new fresh database.

**Comment by nom4da** [comment]
I just did.

It works for newly created content types, but for those migrated from previous versions (copying folders inside /api) won't work. It won't display permissions checkboxes for those. 

Anything more we need to do for a successful model migration besides copying contents on /api ?

**Comment by lauriejim** [comment]
It depend of the source version.

Migration guide here: https://github.com/strapi/strapi/wiki

**Comment by nom4da** [comment]
Hello
I run again into this problem but I found the why and a possible solution. 

I created a custom service for emails as suggested in this link
https://strapi.io/documentation/guides/services.html

I created them under /api/email/services. But there are no controllers, since is not an actual content type. So when I go to create a new Role, and it tries to create the the actions checkboxes, it throws an error coming from:

users-permissions/services/UsersPermissions.js -> - line 119 - in getActions
strapi.api[email].controllers is undefined in this case, so it throws an error.

I fixed it by adding an IF statement

if (strapi.api[key].controllers)
        acc.controllers[key] = generateActions(strapi.api[key].controllers[key]);

Just wanted to let you know.

Thanks again for Strapi!

**Comment by lauriejim** [comment]
Hello @nom4da , can you create new issue please to report your case.

**Comment by LuisHCK** [comment]
I have the same problem strapi v **3.0.0-alpha.17**
![strapi roles permissions](https://user-images.githubusercontent.com/5175137/50268820-d52cde80-03f1-11e9-9870-19b2d928d8e9.png)

**Comment by derrickmehaffy** [comment]
@LuisHCK same, please create a new issue.

**Comment by derrickmehaffy** [comment]
@LuisHCK the issue in this thread is not related to the one that is happening now. this issue was due to a connection to the Strapi marketplace which no longer exists. Thus it is not a duplicate, as that failure is not possible anymore.
