### ISSUE TITLE
[v4] Media Library shows broken images instead of the good one

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#12595]
### Describe the bug

Media containers show broken images.

I use aws-s3 upload provider with Yandex Cloud variables. 
The provider uploads original image and the thumbnail image to the cloud.
The Strapi has the correct link, but it doesn't show the image.

### Steps to reproduce the behavior

1. Go to Media Library.
2. Observer list of uploaded images.
3. Each container of the image has broken image.

### Expected behavior

I see the thumb images of the original uploaded image.

### Screenshots

The Media Library:
<img width="1393" alt="2022-02-19 06-14-56" src="https://user-images.githubusercontent.com/1038168/154784017-75866bad-e938-482d-b25c-084760467a46.png">

The content manager:
![2022-02-19 06-15-45](https://user-images.githubusercontent.com/1038168/154784033-4460c962-d5e1-474b-9484-9726b05fcb46.jpg)

The source code:
<img width="1397" alt="2022-02-19 06-15-46" src="https://user-images.githubusercontent.com/1038168/154784230-fe3fa848-9e62-4798-b2e0-43718e159018.png">

The source code from the screenshot:
`<img src="https://strapi-static.storage.yandexcloud.net/thumbnail_character_profile_example_a5ae653959.png?width=1892&amp;height=1064" alt="character-profile-example.png" aria-hidden="true" class="sc-hAWBJg cBWdaK">`

src of the image: https://strapi-static.storage.yandexcloud.net/thumbnail_character_profile_example_a5ae653959.png?width=1892&height=1064 - it opens correctly in the new tab. 

### Code snippets

The file ./config/middlewares.js

```
module.exports = [
  'strapi::errors',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'storage.yandexcloud.net/strapi-static'],
          'media-src': ["'self'", 'data:', 'blob:', 'storage.yandexcloud.net/strapi-static'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];
```

### System

- Node.js version: 14.18.3
- NPM version: 6.14.15
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: MacOS

**Comment by WalkingPizza** [comment]
It's probably a content security policy error due to the security middleware not being configured correctly.
Replace `storage.yandexcloud.net/strapi-static` with `https://strapi-static.storage.yandexcloud.net` in your configuration and previews should start working again.

**Comment by teinett** [comment]
Thanks, @WalkingPizza! It works now! 

The correct code of `./config/middlewares.js` is the following:

```
const BUCKET = process.env.YANDEX_CLOUD_BUCKET;
const BUCKET_URL = `https://${BUCKET}.storage.yandexcloud.net`;

module.exports = [
  'strapi::errors',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::favicon',
  'strapi::public',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', BUCKET_URL],
          'media-src': ["'self'", 'data:', 'blob:', BUCKET_URL],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];

```

**Comment by didiamuri** [comment]
Here is the configuration that worked for me, I spent 12 hours without finding a solution.

By removing the AWS_REGION, everything worked like a charm.

`"@strapi/strapi": "4.1.0"`

```
module.exports = ({ env }) => [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
          'media-src': ["'self'", 'data:', 'blob:', `https://${env('AWS_BUCKET')}.s3.amazonaws.com`],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

**Comment by insivika** [comment]
Thank you @didiamuri !!!

**Comment by AlyoshaS** [comment]
Thank you, @didiamuri!

**Comment by aslaker** [comment]
++ On this solution @didiamuri You are a lifesaver.

**Comment by zofo27** [comment]
Hi, i have the same problem but on video thumbnail 
![image](https://github.com/strapi/strapi/assets/5077124/489d29eb-eadd-4a8e-8a3f-e84c8529a963)

Any have a solution for this???

This is my middleware.js

module.exports = [
  'strapi::errors',
  /* Replace 'strapi::security', with this snippet */
  /* Beginning of snippet */
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "script-src": ["'self'", "*.tinymce.com", "*.tiny.cloud", "https:"],
          "connect-src": ["'self'", 'https:', "*.tinymce.com", "*.tiny.cloud", "blob:", "*.strapi.io"],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            "strapi.io",
            'market-assets.strapi.io',
            'https://${env('AWS_BUCKET')}.s3.amazonaws.com',
            "s3.amazonaws.com",
            "cdn.jsdelivr.net",
          ],
          'img-src': [
            "'self'",
            'data:',
            "*.tinymce.com",
            "*.tiny.cloud",
            'blob:',
            'dl.airtable.com',
            "strapi.io",
            "s3.amazonaws.com",
            'https://${env('AWS_BUCKET')}.s3.amazonaws.com',
            "cdn.jsdelivr.net",
          ],
          "style-src": [
            "'self'",
            "'unsafe-inline'",
            "*.tinymce.com",
            "*.tiny.cloud",
          ],
          "font-src": ["'self'", "*.tinymce.com", "*.tiny.cloud"],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            'dl.airtable.com',
            'https://${env('AWS_BUCKET')}.s3.amazonaws.com',
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  /* End of snippet */
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  'plugin::strapi-plugin-moesif.moesif',
];

**Comment by ksparsh2011** [comment]
Does anyone know why my images are not getting saved in either public folder or my aws bucket that in configured, plugins.ts and config file are in place, also does anyone has any idea how we can add upload.ts extension in v4
