### ISSUE TITLE
Upload should take URL pointing to media

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#12590]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Upload endpoint should be able to handle URLs pointing to a media resource both on `Upload files related to an entry` and `Upload file during entry creation`

### Why is it needed?

Typically API responses contains URLs to media such that they can be served from a CDN (just like Strapi itself). If I want to insert these entries programatically I first have to retrieve the image myself instead of passing the URL along.

**Comment by kasonde** [comment]
I fear theres a possiblity that this feature request would essentially deviate from the fact that media entities are represented in the database as records and their relative path stored in the database. We use IDs as the source of truth because they typically never change

**Comment by petersg83** [comment]
Hi @sjoukedv,
The url feature you see in the admin panel works only on the front-end part of Strapi, not in the back-end part.
We used to do it in the back-end but there were some security issues that I don't remember that made us remove it. It was removed in this PR https://github.com/strapi/strapi/pull/8442.
So I think it is unlikely that we would propose this feature again.

**Comment by derrickmehaffy** [comment]
Not something we will do, marking as closed
