### ISSUE TITLE
[v4] Media Library shows height x width of the media, instead of width x height

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#12594]
### Describe the bug

The Media Library shows width and height of the media on the wrong places.

### Steps to reproduce the behavior

1. Go to 'Media Library
2. Observe your uploaded media
3. The container for each media has dimension, for example, 1064x1892. I understand this as vertical image. 
4. See error: it's height on the first place, not the width. The actual image is horizontal: 1892x1064.

### Expected behavior

The correct dimension is 1892x1064, i.e. width x height.

### Screenshots

The media library:
<img width="1375" alt="2022-02-19 06-01-27" src="https://user-images.githubusercontent.com/1038168/154783776-e8980faf-8b23-4f1f-81c8-a597b2590382.png">

The actual media:

![2022-02-19 06-08-56](https://user-images.githubusercontent.com/1038168/154783816-77b5f9da-230a-437d-8b0d-3980d6bf7307.jpg)

### System

- Node.js version: 14.18.3
- NPM version: 6.14.15
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: MacOS

**Comment by yanniskadiri** [comment]
Thanks for highlighting this @teinett, we'll fix it in the next weeks :)
