### ISSUE TITLE
Renaming component field of a collection does not migrate data over

### ISSUE THREAD

**Issue by oriooctopus** [strapi/strapi#12597]
## Bug report

I have a collection `sublesson` with a component field called `challenges`. If I rename that field from `challenges` to `steps` for example, none of the data is migrated over and I would theoretically have to redo it all.

### Steps to reproduce the behavior

1. Create a collection 
2. Create a component
3. Attach the component to the collection via a field
4. Populate the data
5. Rename the component field

### Expected behavior

The data should migrate over

### Screenshots

<img width="1082" alt="Screen Shot 2022-02-19 at 11 34 21 AM" src="https://user-images.githubusercontent.com/20331238/154805316-46f91ff1-8ce8-49ee-8238-19c20dd986ba.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.8.1
- Strapi version: 4.0.7
- Database: PostgreSQL
- Operating system: MacOS

**Comment by kasonde** [comment]
Thanks for reporting, marking this as a feature request

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12626
