### ISSUE TITLE
How to login in another browser?

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#1259]
**What is the expected behavior?**
When I create the first admin user in Firefox, and then (for debugging reasons switch to Chrome, I have to again register. I would expect to be able to actually login, since I've already created an admin user.

Is this by design, or am I missing some point here?

**Comment by derrickmehaffy** [comment]
Duplicate of:
https://github.com/strapi/strapi/issues/1254
and
https://github.com/strapi/strapi/issues/1235
