### ISSUE TITLE
Configurated routes doesn't populates

### ISSUE THREAD

**Issue by degoev** [strapi/strapi#12592]
---
name: 🐛 Bug Report
about: Errors when populating configurated routes
---

### Describe the bug

Bug in getting auth state from koa ctx [at this line](https://github.com/strapi/strapi/blob/393909c381b51016b83b6c9e45c94a33c63c323b/packages/core/strapi/lib/core-api/controller/index.js#L11)

### Steps to reproduce the behavior

1. Create 2 collection types **A** and **B** with oneToMany relation
2. Add `auth: false` in config for `find` route in **B** collection type
3. Try to find **A** entries by `GET` request with populating **B** entries
4. See error: **B** entries aren't populated

### Expected behavior

Relations fields should be populated while its public visibility defined by route's config

### Code snippets

Auth context is now getting by 
`const getAuthFromKoaContext = getOr({}, 'state.auth');`
but should getting by 
`const getAuthFromKoaContext = get('state.auth');`

I created [PR](https://github.com/strapi/strapi/compare/master...degoev:patch-1) with these fixes
### System

- Strapi version: 4.0.7
- Database: Postgres
- Operating system: MacOS m1

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12226

**Comment by mohammed7aafar** [comment]
solution is on #12226 

[see this for solution](https://github.com/strapi/strapi/issues/12226#issuecomment-1146577670)
