### ISSUE TITLE
redirection issue

### ISSUE THREAD

**Issue by suvankarsarkar** [strapi/strapi#12604]
$ strapi version
4.1.0

npm 8.3.1

node 16.14.0

unable to create initial admin

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by suvankarsarkar** [comment]
strapi version 4.1.0
npm 8.3.1
node 16.14.0
unable to create initial admin
as it " Refused to connect to 'http://localhost:1337/admin/init' "
it was a known similar issue https://github.com/strapi/strapi/issues/393
was fixed at https://github.com/strapi/strapi/pull/431/commits/ff25575cfdf0bfcf6342e50fdf3f1290cca400dc @ 2018 jan
