### ISSUE TITLE
[Heroku] S3 upload timeout and workaround

### ISSUE THREAD

**Issue by Tragio** [strapi/strapi#12601]
## Bug report

Using Heroku and S3 provider plugin enables users to upload files. When these files are large, or the user is on a slow internet connection, the upload can take longer than 30 seconds. It can result in hitting the H12 request timeout in Heroku.

We should enable a direct upload to S3 so we can avoid Heroku timeout. This will enable broader free use of Strapi.

The main advantage of direct uploading is that the load on the application’s dynos would be considerably reduced. Using app-side processes for receiving files and transferring to S3 can needlessly tie up your dynos and will mean that they will not be able to respond to simultaneous web requests as efficiently.

https://devcenter.heroku.com/articles/s3-upload-node#direct-uploading

### Steps to reproduce the behavior

1. Create a free dyno on Heroku and set up S3 provider plugin.
2. Upload a big file

CC: @alexandrebodin (since you worked on this provider plugin)

**Comment by Louai99k** [comment]
I'm facing the same problem right now and I'm totally agreeing on enabling the S3 direct uploading. Actually the problem with the upload service [here](https://github.com/strapi/strapi/blob/main/packages/core/upload/server/services/upload.js#L158) because the temp directory and the whole `fs-extra` things is taking a lot of ram I guess. So if there a config to stop all of the temp directory process I think we can avoid this problem.

**Comment by majjikishore007** [comment]
Hi, @Louai99k  is this issue resolved? if not I would like to work on this.

**Comment by Louai99k** [comment]
Hi, @majjikishore007 Me and Strapi team working on resolving this. Thanks

**Comment by Tragio** [comment]
@Louai99k is there any news on this or any workaround? I'm finishing a project and also using Strapi Cloud, but until this is fixed, the project is pretty much useless. Every time I upload a file that is more than 100Mb it returns an error and also using Strapi Cloud. 😞

**Comment by Louai99k** [comment]
Yes I have made a work around and it did work for heroku I'll share my work here today so we can close this issue today I hope.

**Comment by Louai99k** [comment]
First of all let me explain what is happening so you'll know why I made the solution like this:

Strapi server makes an optimization to the media and especially to the images when you make the upload and it's using a very heavy-to-process workflow (even if you turn all the optimization settings from the settings page) that make the images perfect as a result but at the same time it's make it hard for the ram of the server.

My solution was to make a custom controller that still creates the `file` entry to make the asset appears in the Media Library but at the same time the uploading flow will be controlled by me so I can control how the file is going to processed and what jobs Strapi will do (so it's not just for the memory problem but it's for customizing all the workflow of the uploading) and I'll explain it down as step-by-step form _(this will be a little bit long but I hope it will explain so much about the solution)_:

1. I made a folder called **upload** inside the extension file so I can extend the upload plugin to add some controllers and services to it.
2. I created a controller named `uploadAttachments` and it looked like this _(the code not explained with comments it's just a workflow that is totally up to you)_:

```js
"use strict";

// This is a custom service that I've created and I'll show it's source code below.
const uploadService = require("../services/upload");

const folderNameTypeMap = {
  product: { singular: "Product", plural: "Products" },
  user: { singular: "User", plural: "Users" },
  blog: { singular: "Blog", plural: "Blogs" },
};

module.exports = {
  async uploadAttachments(ctx) {
    const {
      request: {
        files: { files },
        body: { data },
        params: { id: targetID, type }, // Those are used just for the foldering system
      },
    } = ctx;

    // I'm getting this to use it as a parent for the folder
    // of the media if it's not created yet.
    const parentFolder = await uploadService.getFolder(
      folderNameTypeMap[type].plural
    );

    // This folder will be found by the name and if it's not created yet
    // the service will automatically create one and assign it as a child
    // of the parentFolder.
    const folder = await uploadService.getFolder(
      `${folderNameTypeMap[type].singular}_${targetID}`,
      parentFolder.id
    );

    // Those are options for aws exclusively that will put the new media
    // inside specific folder in the S3 bucket.
    const formattedType = type.endsWith("y") ? type.replace(/y$/, "ie") : type;
    const path = `${formattedType}s/${type}_${targetID}`;

    // The files coming from the request
    const filesArray = Array.isArray(files) ? files : [files];

    // here you can put some data as info for the file (or files) such as name, alt, caption etc.
    let info = data;
    if (typeof data === "string") {
      info = JSON.parse(data);
    }
    info = Array.isArray(info) ? info : [info];

    const filesInfoArray = filesArray.map((_, i) => {
      const infoData = info[i];
      if (infoData) {
        return {
          ...infoData,
          folder,
          path,
        };
      }
      return { folder, path };
    });

    const filesWithURLs = await uploadService.doUpload(
      filesArray,
      filesInfoArray
    );
    return filesWithURLs.map((el) => ({ url: el.url, id: el.id }));
  },
};
```

3. I created a service named `upload` and it looked like this:

```js
"use strict";

const fs = require("fs");
const crypto = require("crypto");
const { extension } = require("mime-types");

const randomSuffix = () => crypto.randomBytes(5).toString("hex");

const nameToSlug = (name) => name.replace(/\s/g, "-");

const generateFileName = (name) => {
  const baseName = nameToSlug(name);
  return `${baseName}_${randomSuffix()}`;
};

module.exports = {
  // This function will create the file type that Strapi is using inside the Media Library.
  createFileData(file, info) {
    const filename = info.name || file.name.replace(/\.\w+$/g, "");
    const config = strapi.config.get("plugin.upload");
    const fileData = {
      name: filename,
      alternativeText: info.alt || info.alternativeText || "",
      caption: info.caption || "",
      ext: `.${extension(file.type)}`,
      hash: generateFileName(filename),
      mime: file.type,
      size: file.size / 1024, // file size needs to be kilobytes
      provider: config.provider,
      user: info.user,
      folderPath: info.folder.path,
      folder: info.folder.id,
      related_entity: info.related_entity,
      path: info.path,
    };
    fileData.getStream = () => fs.createReadStream(file.path);
    return fileData;
  },

  // This is the function that make the actuall upload to aws S3.
  async doUpload(files, filesInfo) {
    const result = await Promise.all(
      files.map(
        (file, i) =>
          new Promise(async (resolve) => {
            const info = filesInfo[i];

            const fileData = this.createFileData(file, info);

            let entry;

            try {
              // Here I'm using the upload provider of strapi to upload
              // directly to S3 without doing any extra processes.
              await strapi
                .plugin("upload")
                .service("provider")
                .upload(fileData);

              // After making the uploading, The provider service will write on the fileData
              // object and will set the url inside of it.
              fileData.previewUrl = fileData.url;

              // And here I'm creating the file so it'll appear inside the media library
              // at the specific folder that I've provided.
              entry = await strapi.entityService.create("plugin::upload.file", {
                data: fileData,
              });

              resolve(entry);
            } catch (err) {
              if (fileData.url) {
                // If any error is happened I'm telling Starpi to delete my file
                // from aws.
                await strapi.plugin("upload").provider.delete(fileData);
              }

              throw err;
            }
          })
      )
    );
    return result;
  },

  // This function will either get me the file with the given name or
  // it'll create it if it's not existing and will set it inside the parent folder I'm providing.
  async getFolder(name, parent = null) {
    const folder = await strapi.db
      .query("plugin::upload.folder")
      .findOne({ where: { name } });

    if (folder) return folder;

    const folderService = awaitstrapi.plugin("upload").service("folder");

    return await folderService.create({ name, parent });
  },
};
```

## Notes:

- The controller and service names is up to you.
- All of the code and explanation made assuming that you have a decent amount of knowledge of Strapi's workflow and you are using version 4.3 and above.
- If you noticed I made A folder system for the REST API (which Strapi don't support at this moment) so this workflow is not just making the files uploaded to Amazon without any run of memory issues, but it's also making you control all the process of creating the file and adding some special functionality to the workflow.
- Sorry for the bad English 😁.

@kasonde this is the solution I told you about earlier.

**Comment by Tragio** [comment]
@Louai99k thank you for your amazing explanation 🙏 

So I created `src/extensions/upload/uploadAttachments.js` and  `src/extensions/services/upload.js` but seems that it is not activated. I even put `console.log` in every function to make sure, but nothing is being called. Is anything missing? 

Perhaps you have some instructions at `./src/index.js`? 🤔

**Comment by Louai99k** [comment]
Check out [this page](https://docs.strapi.io/developer-docs/latest/development/plugins-extension.html#extending-a-plugin-s-content-types). Actually yes you're missing the folder structure for extending a plugin in strapi. You should do something like this:
```bash
/extensions
  /upload
    strapi-server.js # this file is the file that actually strapi is reading
    /controllers
      uploadAttachments.js
    /services
      upload-service.js
```
And don't forget to import those files into `strapi-server.js` so they'll activate it. there is so much details I highly recommend you read the docs very carefully.

**Comment by Tragio** [comment]
@Louai99k thank you once again. I don't use Strapi since I created this issue 😅 I moved on to the frontend to avoid stale the project. Would be possible for you to also share the `strapi-server.js`? 🙂

**Comment by Louai99k** [comment]
Sure.

strapi-server.js:

```js
"use strict";

const server = require("./server");

module.exports = (plugin) => {
  plugin.controllers["content-api"] = {
    ...plugin.controllers["content-api"],
    ...server.controllers.contentApiController,
  };
  plugin.routes["content-api"].routes.push(...server.routes.uploadRoutes);
  const uploadService = plugin.services.upload({ strapi });
  plugin.services.upload = () => ({
    ...uploadService,
    ...server.services.uploadService,
  });
  return plugin;
};
```

The `server/index.js`:

```js
"use strict";

const contentApiController = require("../server/controllers/content-api");
const uploadService = require("../server/services/upload");

module.exports = {
  controllers: {
    contentApiController,
  },
  services: {
    uploadService,
  },
};

```

be aware about the naming.

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/s3-upload-timeout-and-workaround

Thanks!

**Comment by Tragio** [comment]
@Louai99k I never could make it work on my side. I also don't understand why the Strapi team doesn't pay attention to this issue as it is not only related to Heroku but all other providers I tested... Perhaps, you could do a minimal repo just with that so I can see what I did wrong and maybe we can pin your repo to everyone that encounters this issue?

**Comment by Louai99k** [comment]
@Tragio Sure! I'll schedule a reminder to create a repo for this when I'm available.
