### ISSUE TITLE
Not able to singIn into strapi admin sign in page 

### ISSUE THREAD

**Issue by goku1stmain** [strapi/strapi#12608]
Not able to singIn into strapi admin sign in page 
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/94339977/154944056-5aac2d0c-d288-4e48-9fbd-f343bb1741b7.png">

**Comment by noxsii** [comment]
Check your Node and npm Version :)

**Comment by goku1stmain** [comment]
it was working fine till today morning. it is an URL that is hosted. so normally I don't need to run my project to open the strapi admin panel . And I am getting contents from strapi using rest API

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
