### ISSUE TITLE
Unused  Object.assign( in ratelimit.js

### ISSUE THREAD

**Issue by danielehrhardt** [strapi/strapi#12605]
Why is here a Object assign?

https://github.com/strapi/strapi/blob/393909c381b51016b83b6c9e45c94a33c63c323b/packages/plugins/users-permissions/server/middlewares/rateLimit.js#L18

**Comment by kasonde** [comment]
Hi @danielehrhardt  thanks for the question. I'm closing this here however since it's not an issue but a question that is perfect for our [Community Forum](https://forum.strapi.io).
