### ISSUE TITLE
[GraphQL] - Can't access user role from login

### ISSUE THREAD

**Issue by anthonytison** [strapi/strapi#12603]
### Describe the bug

When i'm logging in with GraphQL, the user object doesn't send me back the user role. Instead i have a null response. But if tried to get information directly from a query Me i get the type

### Steps to reproduce the behavior

Mutation
```javascript
mutation {
 login(input: { identifier: "...", password: "..." }) {
   jwt
   user {
    username
    email
    role {
     type
    }
   }
  }
}
```

Response
```json
{
  "data": {
    "login": {
      "jwt": "MY JW TOKEN",
      "user": {
        "username": "MY USERNAME",
        "role": {
          "type": null
         }
      }
    }
  }
}
```

### Expected behavior

I should retrieve the response below

```json
{
  "data": {
    "login": {
      "jwt": "MY JW TOKEN",
      "user": {
        "username": "MY USERNAME",
        "role": {
          "type": "MY ROLE"
         }
      }
    }
  }
}
```

### System

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 4.1.0
- Database: Postgres

**Comment by kasonde** [comment]
Hi @anthonytison we have two issues that actually share the underlying problems going on here. I'll link them here, close this one as it'll technically just be a duplicate: #12379 (If you run a query to show all usersPermissionsUsers and try to fetch their role as well, it throws that error which isn't necessary) and also, you currently can't populate roles at all because of a bug in the users-permissions plugin. Read more here: #12181 and [here](https://github.com/strapi/strapi/issues/12303#issuecomment-1031696262)

**Comment by anthonytison** [comment]
Hi @kasonde, 
thank you for response. I'm gonna check the links you shared right away.

**Comment by viac92** [comment]
Hi, I see you fix the bug about users-permissions plugin but I can't get the role with the login mutation yet.

There are any updates?

**Comment by BorisKamp** [comment]
Any updates? Same problem here: `role` is `null` on login

**Comment by mrwisu** [comment]
Here is a workaround based on [this answer in other issue](https://github.com/strapi/strapi/issues/12181#issuecomment-1190523520).

```typescript
  extensionService.use(() => ({
    resolversConfig: {
      "UsersPermissionsMe.role": {
        middlewares: [
          async (resolve, user, ...rest) => {
            const value = await resolve(user, ...rest);
            if (!value) {
              const userWithRole = await strapi.entityService.findOne(
                "plugin::users-permissions.user",
                user.id,
                {
                  populate: {
                    role: true,
                  },
                }
              );

              return userWithRole?.role;
            }
            return value;
          },
        ],
      },
    },
  }));
```

**Comment by BorisKamp** [comment]
> Here is a workaround based on [this answer in other issue](https://github.com/strapi/strapi/issues/12181#issuecomment-1190523520).
> 
> ```ts
>   extensionService.use(() => ({
>     resolversConfig: {
>       "UsersPermissionsMe.role": {
>         middlewares: [
>           async (resolve, user, ...rest) => {
>             const value = await resolve(user, ...rest);
>             if (!value) {
>               const userWithRole = await strapi.entityService.findOne(
>                 "plugin::users-permissions.user",
>                 user.id,
>                 {
>                   populate: {
>                     role: true,
>                   },
>                 }
>               );
> 
>               return userWithRole?.role;
>             }
>             return value;
>           },
>         ],
>       },
>     },
>   }));
> ```

Works great, thanks!

I think this should be fixed in Strapi tho instead of us having to do it like this.
