### ISSUE TITLE
Cannot set property 'publishedAt' of undefined

### ISSUE THREAD

**Issue by aodbee** [strapi/strapi#12615]
This error

Count couldn't be created. Try again! TypeError: Cannot set property 'publishedAt' of undefined

My code

 const nowDate = new Date()
        const zoneLog = await   strapi.service('api::zone-log.zone-log').create({
            type, 
            count, 
            zone,
            publishedAt:   nowDate.toLocaleString('th-TH', { timeZone: 'UTC' })
        });

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by lgemc** [comment]
That can also happen when instead of `createCoreController` `createCoreService` is wrongly placed

**Comment by molaei2000** [comment]
thank @vhnizdiukh 
another issue is how could add file?
`let entity;

      const {user} = ctx.state;
      let {data} = ctx.request.body
      const files =ctx.request.files
      console.log(files)
      data = JSON.parse(data)
      data.author = user;
      entity = await strapi.service("api::post.post").create({
        data: {
          ...data,
          image:files['files.image']
        }
      });
    const sanitizedEntity = await this.sanitizeOutput(entity, ctx);
    return this.transformResponse(sanitizedEntity); `
it is not work when I add file.

**Comment by molaei2000** [comment]
I find it
`let entity;
      const {user} = ctx.state;
      let {data} = ctx.request.body
      const files =ctx.request.files
      console.log(files)
      data = JSON.parse(data)
      data.author = user;
      entity = await strapi.service("api::post.post").create({
        data: {
          ...data,
        },
        files:{
          image: files['files.image']
        }
      });
    const sanitizedEntity = await this.sanitizeOutput(entity, ctx);
    return this.transformResponse(sanitizedEntity);
  }`
