### ISSUE TITLE
Strapi not honoring URL settings and returning localhost:1337 instead

### ISSUE THREAD

**Issue by fgbreel** [strapi/strapi#12624]
### Describe the bug
Hi, I hope you are doing well,

Strapi is returning wrong URL for `/admin/init`, even settings the `url` attribute to both `server` and `admin` to be a full URL location.

Should be "http://app.foo.bar/admin/init".
Currently returning "http://localhost:1337/admin/init`.

### Steps to reproduce the behavior

1. Install strapi 4.0.7
2. Add `url: "http://app.foo.bar/admin"` in  `config/admin.js`
3. Add `url: "http://app.foo.bar"` in `config/server.js`
3. Access `http://app.foo.bar/admin`

### Expected behavior

No requests with `http://localhost:1337` in the URL.

### Screenshots

![Screenshot from 2022-02-22 13-50-07](https://user-images.githubusercontent.com/893920/155135751-877adaa6-2b00-48c7-9b03-624e6c2a6704.png)

### Code snippets

```js
// config/admin.js
module.exports = ({ env }) => ({
  url: "http://app.foo.bar/admin",    // I added this line
  auth: {
    secret: env('ADMIN_JWT_SECRET', 'aaaaaaaaaaaaaaaaaaaaaaaaaa'),
  },
});
```

```js
// config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: "http://app.foo.bar",    // I added this line
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

### System

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.0.7
- Database: SQLite
- Operating system: Debian

**Comment by fgbreel** [comment]
I'm setting the `url` in `config/admin.js`  as https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/admin-panel.html#available-options

And setting the `url` in `config/server.js` as per https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/server.html#configurations

My `/etc/hosts` contains:

```
127.0.0.1 app.foo.bar
```

Then I start the server with `NODE_ENV=production strapi start`.

Looks like everything is ok, except for `/admin/init` and `/project-type` which for some reason has `http://localhost:1337` instead of the URL that I defined.

I found that there are several issues (open and closed ones) about mismatch URL, I think is something related.

1. https://github.com/strapi/strapi/issues/12564
2. https://github.com/strapi/strapi/issues/8616
2. https://github.com/strapi/strapi/issues/12457
3. https://github.com/strapi/strapi/issues/9027


I don't think it should be that hard to get the URLs working and I think I did everything correctly.

**Comment by fgbreel** [comment]
Would be great to have **[this](https://github.com/strapi/strapi/issues/10867)** specific super odd runtime-depends-on-build (and vice-versa) documented somewhere.

**Comment by derrickmehaffy** [comment]
I've edited your post as the information provided is incorrect, you should never set the `HOST` var to a domain, all you need to do is rebuild the admin. Yes the url keys are statically compiled into the admin panel as the admin panel is built in react and doesn't have to be served by the Strapi backend. It can be built and served somewhere else entirely which is why we have the option to disable serving it.

Strapi's admin panel is not built using next and it isn't served as SSR, it's CSR so an absolute URL to the backend is **required** and for ease of development we statically build that absolute URL into the admin panel.

**Comment by fgbreel** [comment]
You are right, and it makes sense.

I think I got a `0.0.0.0` at some point in a `.js` file and set that to a domain to see what gives.

Thanks for adding 🙏🏼

**Comment by derrickmehaffy** [comment]
No problem :)

**Comment by ssshammi** [comment]
Hi i am having a similar issue not sure where to add these. STRAPI_ADMIN_BACKEND_URL=http://app.foo.bar HOST=app.foo.bar NODE_ENV=production yarn build because this STRAPI_ADMIN_BACKEND_URL is for strapi version 3?

**Comment by derrickmehaffy** [comment]
> 

Strapi v4 moved the admin url to the `./config/admin.js` file instead, you'll need to set the environmental variable name.

Btw you should never set HOST to a domain, it should either be 0.0.0.0 or an actual IP address on the machine you deploy it on.

**Comment by AakashPat** [comment]
Still not working!
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/10728448/206261306-581904b7-8dbb-4648-926d-7e864ec3ce39.png">

![image](https://user-images.githubusercontent.com/10728448/206261210-f926ba26-a42a-4ca7-b1ad-06db6941eb1e.png)

**Comment by derrickmehaffy** [comment]
> Still not working!
> <img width="1102" alt="image" src="https://user-images.githubusercontent.com/10728448/206261306-581904b7-8dbb-4648-926d-7e864ec3ce39.png">
> 
> ![image](https://user-images.githubusercontent.com/10728448/206261210-f926ba26-a42a-4ca7-b1ad-06db6941eb1e.png)
> 

Can you share your admin.js and server.js file?

**Comment by AakashPat** [comment]
ADMIN.js

`module.exports = ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
});
`

server.js

`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('PUBLIC_URL', 'http://api.f4.mydomain.in'),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
`

> > Still not working!
> > <img alt="image" width="1102" src="https://user-images.githubusercontent.com/10728448/206261306-581904b7-8dbb-4648-926d-7e864ec3ce39.png">
> > ![image](https://user-images.githubusercontent.com/10728448/206261210-f926ba26-a42a-4ca7-b1ad-06db6941eb1e.png)
> 
> Can you share your admin.js and server.js file?

ADMIN.js

`module.exports = ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
});
`

server.js

`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('PUBLIC_URL', 'http://api.f4.mydomain.in'),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
`

**Comment by derrickmehaffy** [comment]
And you don't happen to have a `./config/env/production/server.js` do you?

**Comment by derrickmehaffy** [comment]
Or a `PUBLIC_URL` set in your .env file?

**Comment by daniel-fodor** [comment]
Is there any solution about the problem?

**Comment by fgbreel** [comment]
Check my previous https://github.com/strapi/strapi/issues/12624#issuecomment-1047993271 

For me, passing the FQDN in the HOST variable **only** when `npm build`-ing (together with STRAPI_ADMIN_BACKEND_URL) worked.
