### ISSUE TITLE
Repeater: not displaying all data in the API

### ISSUE THREAD

**Issue by emilianovelasco** [strapi/strapi#12628]
### Describe the bug

It is not possible to obtain the data of a "Repeater > Media" via the REST API, input or basic data appears. However, when we go to edit an item that has a "Repeater > Media", in Strapi ADMIN the relationship does appear perfectly (it seems that the ADMIN uses a different API)

### Steps to reproduce the behavior

1. Go to 'Content-Type Builder'
2. Add new 'collection of multiple items'
3. Add 'Component' (repeatable) and repeat items using fields "title => Text" and "thumb => Media"
4. Add new 'collection item' with some repeatables items data
5. Check the API 'api/collection/1?populate=*' 
6. Only the basic data of the collection will appear, and only the 'title' of each repeatable item will appear
7. If we edit the collection item again, we can see the repeatable component full of data, with the inputs and the media, correctly visible and related

### Expected behavior

The API should show all the data of a collection.

### System

- Node.js version: v14
- Strapi version: v4.1.0
- Database: MySQL

**Comment by Dragurimu** [comment]
I am having the same problem.

**Comment by derrickmehaffy** [comment]
This is intended, you need to dive into custom population as the `*` wildcard only goes one level deep (into the components).

We have documentation on populating deeper into dynamic zones/components: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#component-dynamic-zones
