### ISSUE TITLE
Use suggested relationship names by default

### ISSUE THREAD

**Issue by jaguilar87** [strapi/strapi#1262]
**What is the expected behavior?**
When you add a new relation and do not specify a relation name, use the placeholder instead of firing an error.

**Current behavior**
It shows a red error saying `This value input is required.`.

**Comment by jaguilar87** [comment]
![screen shot 2018-05-23 at 16 22 31](https://user-images.githubusercontent.com/14294477/40430750-20142dc8-5ea6-11e8-9181-a2507deb413a.png)

**Comment by Aurelsicoko** [comment]
You're not the first one to report it, we should definitely use the placeholder as value, it will save time for everyone 👍
