### ISSUE TITLE
Filters aren't being taken into account in the pagination count for GraphQL

### ISSUE THREAD

**Issue by HaruMiyaGi** [strapi/strapi#12637]
### Describe the bug

When executing a GraphQL filtered query the pagination count is wrong.

### Steps to reproduce the behavior

1. Install Strapi with graphql
2. Create 'Product' collection (with text field: `name`)
3. Create 'Category' collection (with text field: `name`)
4. In 'Products' collection create another field of type: Relation and link 'Products' and 'Categories' together ('Product has and belongs to many Categories')
5. Go to Content Manager and create 3 categories with names: 'Category 1', 'Category 2', 'Category 3', save & publish each one
6. In Content Manger create 1 Product with name 'test' and assign those 3 categories, save & publish
7. In Strapi Dashboard go to Setting -> Roles -> Public and under permisions for 'Product' select all & Save
8. Now goto GraphQL Playground (localhost:1337/graphql) and perform `Code snippets` query
9. See that the pagination total is 3 instead of 1

### Expected behavior

Paginations total to be 1.

### Code snippets

```
query {
  products(
    filters: {
      categories: { name: { in: ["Category 1", "Category 2", "Category 3"] } }
    }
  ) {
    data {
      id
    }
    meta {
      pagination {
        total
      }
    }
  }
}
```

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: 4.1.0
- Database: MySQL
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/7631
