### ISSUE TITLE
Auth.js catch all error displays incorrect message

### ISSUE THREAD

**Issue by raulriera** [strapi/strapi#1263]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongoDB
- **Operating system**: macOS

**What is the current behavior?**
When creating additional required fields in the user model inside the permissions plugin, any attempt at creating a new user by using the Auth.js will fail with the hardcoded message `'Auth.form.error.email.taken'` as seen by line 283

https://github.com/strapi/strapi/blob/eeaba813e0c9120ffd7481d973ded2d86f7c1d13/packages/strapi-plugin-users-permissions/controllers/Auth.js#L275-L285

**Steps to reproduce the problem**
- Create a required field in the user model
- Logout and try to create a new user

**What is the expected behavior?**
It should display the correct "something is.required message", I don't think the form should include the fields, it should just make it impossible to register a user at this point. But it should correctly display what is wrong

**Suggested solutions**
Remove this line `const adminError = _.includes(err.message, 'username') ? 'Auth.form.error.username.taken' : 'Auth.form.error.email.taken';` and change the way the models are displaying their errors information. 

Instead of using `"UsersPermissionsUser validation failed: lastname: Path `lastname` is required., firstname: Path `firstname` is required."`, pass back translations keys like above, but with dynamic properties?

**Comment by mnlbox** [comment]
@raulriera I think you find reason of my issue here: #1254
