### ISSUE TITLE
GraphQL shadow mutation throws an error "Invalid date"

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#12630]
### Describe the bug
GraphQL throws an error "Invalid date" even though the exact date value is entered.
<img width="964" alt="error" src="https://user-images.githubusercontent.com/4951716/155273580-b4c85d5e-e580-4070-9b42-fb6a49187240.png">

### Steps to reproduce the behavior

I tested with `strapi/examples/getstarted` example.

1. Go to http://localhost:1337/graphql
2. Execute mutation
```gql
mutation CreateCategory($data: CategoryInput!) {
  createCategory(data: $data) {
    data {
      attributes {
        date
        datetime
      }
    }
  }
}

{
  "data": {
    "date": "2022-01-01"
  }
}
```

### Expected behavior

Mutation should create an entry

### System

- Node.js version: 14.17.1
- NPM version: 8.4.1
- Strapi version: 4.1.0
- Database: SQLite, mySQL
- Operating system: MacOS M1 silicon

### Additional context

If the field is `DateTime` format, entering ISO String (ex: `'2022-02-23T07:01:06.869Z'`) creates an entry without validation error. Only `Date` format has a validation issue.

**Comment by iicdii** [comment]
I think the `graphql-iso-date` library parse date to ISO string.

https://github.com/strapi/strapi/blob/fd2238d06c832c7adaaf41b0b1b98bf91b40c217/packages/plugins/graphql/server/services/internals/scalars/index.js

There is opened issue in github - https://github.com/excitement-engineer/graphql-iso-date/issues/106

**Comment by robinvandenb** [comment]
Facing the same issue. If the date is formatted correctly I only get a "invalid date" error without the full stack trace

**Comment by petersg83** [comment]
Thank you for the issue and the digging @iicdii. I read your PR. I'm wondering if the good way to go wouldn't be to find a way to not cast the Date value into `new Date` there https://github.com/strapi/strapi/blob/fd2238d06c832c7adaaf41b0b1b98bf91b40c217/packages/plugins/graphql/server/services/internals/scalars/index.js. @Convly do you have any idea?
