### ISSUE TITLE
fineOne via REST API is returning unpublished data

### ISSUE THREAD

**Issue by ippoippo** [strapi/strapi#12639]
### Describe the bug

The findMany REST API endpoint works as expected. Only Published content is returned.
The findOne REST API endpoint, when provided with the ID of an unpublished item is incorrectly returning that content.

### Steps to reproduce the behavior

- I have an entity called `article-tutorial`.
- I have published and unpublished items. For example, `article-tutorial` with ID=5 is unpublished, and `article-tutorial` with ID=6 is published.

**Call the findMany endpoint.**

`GET {{host}}/api/article-tutorials`

Returns Published items only. Item with id=5 is not in list of results.

**Call the findOne endpoint.**

`GET {{host}}/api/article-tutorials/5`

I get

```
{
    "data": {
        "id": 5,
        "attributes": {
            "createdAt": "2022-02-23T22:33:15.796Z",
            "updatedAt": "2022-02-23T22:33:15.796Z",
            "publishedAt": null,
            "title": "SMXDSN252 - Never Published",
            "description": "SMXDSN252 - Never Published",
            "sort_order": "251",
            "article_text": null,
            "duration": null,
        }
    },
    "meta": {}
}
```

### Expected behavior

The default behaviour for this API should be to never return unpublished content, just by guessing IDs.

### Screenshots

N/A 

### Code snippets

See above.

### System

- Node.js version: v14.18.2
- NPM version: 6.14.15
- Strapi version: 4.0.8 (release notes for 4.0.10 don't indicate there is any fix for this)
- Database: Tested on both MySQL (Integration and Prod environments) and SQLite locally.
- Operating system: Local is MacOS 12.2.1

### Additional context

N/A

**Comment by ippoippo** [comment]
@iicdii Regarding #12645 
I'm not sure that providing a parameter on what is potentially a public API is the right approach.
I'm OK with having the EntityService or QueryEngine having a parameter that overrides a default of not returning Draft Data (or vice versa).

But, the REST API is "public". There should not be a parameter that you can supply as a query from the calling side.
Instead, I would expect there to be config you set in code somewhere. Maybe in `config/api.js` ? In there, the default is `"includeDraftPublicationState" = false`. 
If you then set `"includeDraftPublicationState" = true`, it returns Draft items in the REST API response. The client then, has the opportunity to opt out with a request parameter (`suppressDraftPublicationState`).

What do you think.

What I'm getting at, the default is to hide. The server side can open up. The client can suppress.

**Comment by iicdii** [comment]
Yes, the draft data can be exposed by sending request like `/api/categories/1?publicationState=preview`.
Adding config `includeDraftPublicationState` makes sense to me. But we need Strapi teams' opinion.
I just thought they don't consider that it's critical issue that draft data could be exposed. Because

- Currently, the draft data is already exposed by just accessing (`/api/categories/1`).
- They already added params for `publicationState` in `findOne` internally, but it was just ignored when sanitizing params.

So I decide the direction of work according to the future opinion of the Strapi team.

**Comment by derrickmehaffy** [comment]
The current action is intended, draft and publish is not a security feature it's an organizational one. 

the publication state filter is only used on the findMany, if you directly access an entity it should show the data regardless of publication state. If you need to lockout access to draft entries in findOne then you'll need to write custom policies to do that.

Marking as closed as we won't "fix" this as it's intended.

**Comment by jafaruddeen** [comment]
@ippoippo, I was also getting the same thing as you've mentioned, so I do some code to return null if an item is unpublished

`async findOne(ctx) {
    const { id } = ctx.params;

    const entity = await strapi.entityService.findOne(
      "api::article.article",
      id,
      {
        fields: ["id", "publishedAt", "slug", "title", "subTitle", "duration"],
        populate: {
          category: {
            fields: ["title", "description"],
          },
          data: {
            populate: "*",
          },
        },
      }
    );

    if (entity.publishedAt === null) {
      return null;
    } else {
      return entity;
    }
  }`

And it's returning this 
`{
"data": null,
"error": {
"status": 404,
"name": "NotFoundError",
"message": "Not Found",
"details": {}
}
}`

**Comment by jafaruddeen** [comment]
@ippoippo, I was also getting the same thing as you've mentioned, so I do some code to return null if an item is unpublished
`async findOne(ctx) {
    const { id } = ctx.params;

    const entity = await strapi.entityService.findOne(
      "api::article.article",
      id,
      {
        fields: ["id", "publishedAt", "slug", "title", "subTitle", "duration"],
        populate: {
          category: {
            fields: ["title", "description"],
          },
          data: {
            populate: "*",
          },
        },
      }
    );

    if (entity.publishedAt === null) {
      return null;
    } else {
      return entity;
    }
  }`

And it's returning
`{
"data": null,
"error": {
"status": 404,
"name": "NotFoundError",
"message": "Not Found",
"details": {}
}
}`

**Comment by NitrusAphalion** [comment]
Logically it seems like this should work as per the OP point, weird design decision.

**Comment by BumbuKhan** [comment]
I had the same issue. As @jafaruddeen mentioned, we can check whether `publishedAt` field is `null` or not.

Here is the slightly updated query I used:

```
// Fetching all published & approved reviews for the course
const { reviews } = await strapi.entityService.findOne('api::course.course', courseId, {
  populate: {
    reviews: {
      filters: {
        $and: [
          {
            approved: {
              $eq: true
            },
          },
          {
            publishedAt: {
              $notNull: true,
            }
          },
        ],
      }
    },
  },
});
```
