### ISSUE TITLE
Query `locale=all` not work with Single Type

### ISSUE THREAD

**Issue by leduchung** [strapi/strapi#12638]
### Describe the bug

The query param `locale=all` does not work with Single Type content.
Tested with API https://docs.strapi.io/developer-docs/latest/plugins/i18n.html#getting-localized-entries-with-the-locale-parameter

### Steps to reproduce the behavior

1. Set up multiple languages for a single type (e.g. a simple text) and add some content
2. Run the query: `http://localhost:1337/api/{singleTypeName}?locale=all` (replace the singleTypeName with proper one)
3. The return JSON contains only default language

### Expected behavior

The return JSON includes all languages

### System

- Node.js version: v16.13.1 
- Strapi version: v4.1.0

**Comment by leduchung** [comment]
hi, thanks for the fix. Do you have any timeline for this PR to be merged?

**Comment by daton89** [comment]
I have the same problem with strapi 3.6.8
query the locale all returns only the document with default locale, also when I try to query the other locales only the document with default locale returns. 

![image](https://user-images.githubusercontent.com/6856342/157910114-7788821f-b491-4cc7-a179-a5f98434df11.png)
![image](https://user-images.githubusercontent.com/6856342/157910160-401d9ee7-0740-4e75-b440-7f4496829515.png)
![image](https://user-images.githubusercontent.com/6856342/157910188-d2940d99-b128-485a-800c-d4c23bf0736d.png)

**Comment by RafidMuhymin** [comment]
We are facing the same issue. Is there any way to extend Strapi to enable this?

**Comment by raphaeldas** [comment]
For everyone interessted: I solved this problem by adjust the controller of the desired single-type:

``` javascript
// Original Controller:
// module.exports = createCoreController('api::demo-type.demo-type');

module.exports = createCoreController('api::demo-type.demo-type', ({ strapi }) => ({
	async find(ctx) {
		if (ctx.query.locale === 'all') {
			const localesArray = await strapi.plugins.i18n.services.locales.find()
			const locales = localesArray.map(locale => locale.code);
			console.log(locales);
			let data = [];

			for (let locale of locales) {
				ctx.query.locale = locale;
				const response = await super.find(ctx);
				data.push(response.data);
			};

			const meta = {};
			return { data, meta };
		}

		return await super.find(ctx);
	}
}));
```

This code checks if the query parameter `locale=all` exists, then queries a list of all available languages from the i18n service. With these languages the find query gets made and collected in an array. this array then finally gets return.
