### ISSUE TITLE
Redirect URL in provider edit panel should be prefixed with '/api'

### ISSUE THREAD

**Issue by kwang1198** [strapi/strapi#12640]
### Describe the bug

The redirect URL in provider edit panel should be prefixed with `/api`

### Steps to reproduce the behavior

1. Go to 'Strapi admin'
2. Click on 'Settings'
3. Click on 'Whatever provider that has redirect URL'

### Expected behavior

The redirect URL prefixed with `/api`

### Screenshots

<img width="828" alt="image" src="https://user-images.githubusercontent.com/71486219/155453313-005b5517-7c42-4827-958a-76791eafaabd.png">

### System

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version: v4
- Database: sqlite
- Operating system: macOS Monterey

**Comment by smoothdvd** [comment]
Upgrade to latest the Strapi 4.1.0, set url: '/' in ./config/server.js. Then clear the provider info in the value of ''plugin_users-permissions_grant' of table 'strapi_core_store_settings'.

**Comment by kwang1198** [comment]
The version I use is already 4.1.0. While I print the value in the table, I get the following output and there is no `redirectUri`.
```
{
    "enabled":false,
    "icon":"discord",
    "key":"",
    "secret":"",
    "callback":"api/auth/discord/callback",
    "scope":["identify","email"]
}
```
I think the value showed in the panel comes from this line of code:
`packages/plugins/users-permissions/admin/src/components/FormModal/Input/index.js`
```
const inputValue =
    name === 'noName' ? `${strapi.backendURL}/connect/${providerToEditName}/callback` : value;
```
Is there any way to get prefix like `strapi.api.prefix`?

**Comment by smoothdvd** [comment]
@kwang1198 You need delete json object of discord provider in database, Strapi will re-generate correct value for you after rerun strapi develop.

**Comment by kwang1198** [comment]
The value above is already re-generated.

**Comment by smoothdvd** [comment]
@kwang1198 You want redirect url?
<img width="829" alt="Screen Shot 2022-02-24 at 4 40 53 PM" src="https://user-images.githubusercontent.com/22420/155489367-b9e13375-56cb-4fde-8d55-f646726a704f.png">

https://github.com/strapi/strapi/blob/fb9cbc1a2389dd0ff44ea77d1d523ae2c78d33c8/packages/plugins/users-permissions/server/services/providers.js#L592

**Comment by smoothdvd** [comment]
@kwang1198 Looks the placeholder text is not same as the redirect url actually.

**Comment by kwang1198** [comment]
> @kwang1198 You want redirect url? <img alt="Screen Shot 2022-02-24 at 4 40 53 PM" width="829" src="https://user-images.githubusercontent.com/22420/155489367-b9e13375-56cb-4fde-8d55-f646726a704f.png">
> 
> https://github.com/strapi/strapi/blob/fb9cbc1a2389dd0ff44ea77d1d523ae2c78d33c8/packages/plugins/users-permissions/server/services/providers.js#L592

Yeah, the redirect url should be `/api/connect/discord/callback`

**Comment by smoothdvd** [comment]
@kwang1198 @petersg83

https://github.com/strapi/strapi/blob/da9b064536156aa564a43b6ddbe006981084e834/packages/plugins/users-permissions/admin/src/pages/Providers/utils/forms.js#L111

Don't know why this input should be named "noName", I think this name value is "redirectUri".

**Comment by kwang1198** [comment]
@smoothdvd I agree. I think `intlLabel` and `name` should be consistent. Either both start with `hint` or `redirectUri`.
