### ISSUE TITLE
findOne service not support "filters"

### ISSUE THREAD

**Issue by southpush** [strapi/strapi#12641]
## Bug report
Filters is not work in the below code.
```
strapi.service("api::project.project").findOne(ctx.params.id, {
     filters: {
         "name": {
            "$eq": "111"
         }
     }
})
```

Is it a bug or just not support ?

### Describe the bug

In ths source code in file "core-api/service/collection-typs.js", the function findOne accepts the params parameter. In the index.d.ts show that it receives the filters field. But filters not work.

### Code snippets

```
strapi.service("api::project.project").findOne(ctx.params.id, {
     filters: {
         "name": {
            "$eq": "111"
         }
     }
})
```

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by kasonde** [comment]
In the absence of the information you've omitted from this issue, I'm not able to reproduce this issue you're facing. Please update your issue.

**Comment by NicoHof** [comment]
In the docs there is this "caution" block just below the code example which states that filters only work on "find" and not on "findOne" https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#find-multiple-restaurants-with-ids-3-6-8

But its not explained why or how to change it. Maybe the docs can be extended there?

**Comment by derrickmehaffy** [comment]
> In the docs there is this "caution" block just below the code example which states that filters only work on "find" and not on "findOne" https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#find-multiple-restaurants-with-ids-3-6-8
> 
> But its not explained why or how to change it. Maybe the docs can be extended there?

https://github.com/strapi/strapi/issues/12208
