### ISSUE TITLE
Redirect to users list page after update user info

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1264]
**Informations**
- **Node.js version**: 10.1.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: Mongo
- **Operating system**: Linux

**What is the current behavior?**
When we update iser info and click **Save** button I think it's better to go to users page. See current behavior in below gif:
![strapi 10](https://user-images.githubusercontent.com/25859075/40464888-2222c8f8-5f33-11e8-8554-6eb20865f5fa.gif)

**Steps to reproduce the problem**
* Click on users content type
* Click on a user
* Update user info
* Click **Save** button
* You are still in user update page :disappointed: 

**What is the expected behavior?**
Redirect to users list page after update.

**Suggested solutions**
--

**Comment by soupette** [comment]
@mnlbox do you have a password manager?

**Comment by mnlbox** [comment]
@soupette Yes, I just use Firefox default password manager.

**Comment by soupette** [comment]
I believe that this is the issue, I facing it when I use 1password

**Comment by mnlbox** [comment]
I don't know. Are you have same issue on Firefox?

**Comment by johannpinson** [comment]
Hey @mnlbox 

I just test it on FF 60.0.1 and MacOS 10.13.4 and I can't reproduce the issue, the password manager of FF don't stop the redirect to the user list page.

What is your version ?

**Comment by derrickmehaffy** [comment]
Chrome Version 66.0.3359.181 (Official Build) (64-bit) & Windows 10/Linux Mint 18.3/Kubuntu 18.04

Able to reproduce the issue, but hitting the back button twice brings me to the login screen and I'm able to login in just fine from there.

**Comment by mnlbox** [comment]
@johannpinson I'm also using Firefox 60.0.1 on Linux and my Strapi version also 12.2

**Comment by lauriejim** [comment]
@mnlbox can you disable the password manager of your browser and test again please.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.

**Comment by mnlbox** [comment]
@lauriejim What type of information you want?

**Comment by mnlbox** [comment]
@lauriejim @soupette
