### ISSUE TITLE
How to reach to custom controllers api

### ISSUE THREAD

**Issue by muzammil-majeed-viabletree** [strapi/strapi#12646]
Hello,

Issue is that there is no way to update the user password after login, so I created my own controller and trying to call it from my app but everytime it is giving an error of **405 (Method not allowed)**. 

Api call:
`http://localhost:1337/api/account/updatePassword`

Screenshot of backend code is attached. Just help me how to reach the endpoint.

![Screenshot from 2022-02-24 13-53-05](https://user-images.githubusercontent.com/96433525/155490983-49d282a8-f93e-4166-9221-9a2fc04a5ee9.png)

**Comment by muzammil-majeed-viabletree** [comment]
?????

**Comment by 4strodev** [comment]
I have the same problem, did you solve it?

**Comment by muzammil-majeed-viabletree** [comment]
<img width="406" alt="Screenshot 2023-06-22 at 4 34 20 PM" src="https://github.com/strapi/strapi/assets/96433525/12af40b2-a7d5-491f-b570-88177ca451cd">

I was using the wrong folder structure. This one is the correct.

**Comment by 4strodev** [comment]
In my case, it was that I was pointing to the wrong route. I think... At some point, it started to work 😅
