### ISSUE TITLE
ne, nin, ncontains filters don't work for relations at all

### ISSUE THREAD

**Issue by ashmore11** [strapi/strapi#12658]
# Bug report
### Describe the bug
When executing a query with a deep filter on a relation using eq, in or contains, the filter works as expected and only returns items that match the criteria provided in the filter. But when using the opposite filter (ne, nin, ncontains), the data is returning items that should be omitted.

### Steps to reproduce the behavior
Execute a deep filter using `ne`, `nin` or `ncontains` on any relation

### Screenshots
<img width="1728" alt="Screenshot 2022-02-25 at 07 10 44" src="https://user-images.githubusercontent.com/1529910/155670869-757aa5d3-f316-4123-9acb-6570290a449a.png">

### Code snippets
GraphQL:
```
searchUsers(where: { followers: { fullname_ne: "Scott Ashmore" } })
```
Vanilla:
```
const users = await strapi.query("user", "users-permissions").find({
  _where: {
    followers: { fullname_ne: "Scott Ashmore" },
  }
});
```

### System
Node.js version: v12
NPM version: 6.14
Strapi version: 3.5.4
Database: MariaDB
Operating system: Mac

**Comment by derrickmehaffy** [comment]
We aren't supporting Strapi v3 for non critical or security related bugs at this time. Our v3 to v4 migration guide should be out shortly.)

**Comment by nikolasimic3** [comment]
This problem exist also on v4. I'm on latest v4.5.6 and I have the same problem, works well for `$eq`, but doesn't for `$ne`.

**Comment by julesrenaud** [comment]
@derrickmehaffy from what I understand, this also applies for v4. I'm unable to filter out entities based on an excluding factor in a relation (ex.: filtering out articles that have a category with the name "Recipes"). It seems it doesn't work at all.

**Comment by PenguinOfWar** [comment]
Can confirm this is still broken in v4. Encountering the same issue.

**Comment by damianryann** [comment]
@derrickmehaffy I can also confirm to having this issue on v4, kinda not good as it's a core filtering feature :/

**Comment by derrickmehaffy** [comment]
Given how old this issue is, please open a new bug report for v4 with all the required information.
