### ISSUE TITLE
has-and-belongs-to-many create two relational tables in MySQL

### ISSUE THREAD

**Issue by pbvahlst** [strapi/strapi#12652]
### Describe the bug

When creating "has-and-belongs-to-many" relation e.g. between a "person" and an "address" two relational tables
are created in the database: "addresses_persons_links" and "persons_addresses_links".
Shouldn't there only be one relational table and then the models "inversedBy" should be used to point to the other side?

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 4.1 
- Database: MySQL 8.1
- Operating system:

**Comment by smoothdvd** [comment]
@pbvahlst Add "useJoinTable": false to your field attribute definition in schema.json.

**Comment by pbvahlst** [comment]
Ok, thanks. Will the table be used for future features or can it safely be excluded? Right now it is not populated, so it just feels like clutter having two tables represeenting the same.

**Comment by pbvahlst** [comment]
Looking at https://github.com/strapi/strapi/blob/master/packages/core/database/lib/metadata/relations.js createManyToMany it seems that only the owning side should have a joinTable?

**Comment by pbvahlst** [comment]
I think I see the problem. When creating many-to-many with the content-type-builder the generated schemas both have `inversedBy` instead of one of them having `mappedBy`.

**Comment by pbvahlst** [comment]
Can this be confirmed as a bug?

**Comment by derrickmehaffy** [comment]
(More info will come once we start working on content-versioning :) )
