### ISSUE TITLE
Users API does not have meta information

### ISSUE THREAD

**Issue by ssshammi** [strapi/strapi#12661]
The issues is the rest API USERS endpoint does not have a data key attribute or any meta information so the data provider is throwing errors. 

### Describe the bug

all other content endpoint have meta information and data key by default. But it seems that the User endpoint is normalized. 

### Steps to reproduce the behavior
call
http://localhost:1337/api/users/?populate=*
the response is a normalized array. no data or attribute keys no meta information.
`[
{
}
]
`
call a custom endpoint
http://localhost:1337/api/courses/?populate=*

The response is a json data with meta information and data key 
```
{
data: [
{
id: 1,
attributes: {

}
}
],
meta: {
pagination: {
page: 1,
pageSize: 25,
pageCount: 1,
total: 6
}
}
}
```
...

### Expected behavior

There should be a consistency in the response of all endpoint either everything should be normalized or all endpoint return a similar data structure

**Comment by sjoukedv** [comment]
I have a similar issue: for me the `/api/users/me` is not populating the `role` and/or a custom `collection`. 

Seems to be related to #11957 which has had a fix already.

Tried overwriting the `fetchAuthenticatedUser(id){...}` and also inside `src/index.js`:

```
 register ({ strapi }) {
    strapi.service('plugin::users-permissions.user').fetchAuthenticatedUser = (id) => {
      return strapi
        .query('plugin::users-permissions.user')
        .findOne({ where: { id }, populate: ['role', 'subscriptions'] })
    }
   ```

Related forum post: https://forum.strapi.io/t/get-currrent-logged-user-with-custom-data-added-to-the-user-collection-type/1024/22

**Comment by yegor-innovationfeel** [comment]
You can simply override in extensions/users-permissions/strapi-server.js

`
const utils = require("@strapi/utils");
const { sanitize } = utils;
const {
  transformResponse,
} = require("@strapi/strapi/lib/core-api/controller/transform");

////////

plugin.controllers.user.find = async (ctx) => {
    const sanitizeOutput = async (user, ctx) => {
      const schema = strapi.getModel("plugin::users-permissions.user");
      const { auth } = ctx.state;

      return sanitize.contentAPI.output(user, schema, { auth });
    };

    const sanitizeQuery = async (query, ctx) => {
      const schema = strapi.getModel("plugin::users-permissions.user");
      const { auth } = ctx.state;

      return sanitize.contentAPI.query(query, schema, { auth });
    };

    const sanitizedQuery = await sanitizeQuery(ctx.query, ctx);

    const { results, pagination } = await strapi.entityService.findPage(
      "plugin::users-permissions.user",
      sanitizedQuery
    );

    const sanitizedResults = await Promise.all(
      results.map((user) => sanitizeOutput(user, ctx))
    );

    return transformResponse(sanitizedResults, { pagination }, ctx);
  };
`

And in response will be standard - {data: [], meta: {}}
