### ISSUE TITLE
`publicationState` is ignored in nested `populate` queries

### ISSUE THREAD

**Issue by cortopy** [strapi/strapi#12665]
### Describe the bug

`publicationState` is getting ignored in nested `populate` queries.

Given the following query:

```js
featuredCategories: {        
  populate: {
    category: {
      fields: ['id']
    }
  }
}
```

the field `featuredCategories[n].category` (a repeatable component) gets populated with the field `id` only if the category is published. This feels like the expected behaviour

However, the following doesn't work:

```js
featuredProductCategories: {        
  populate: {
    category: {
      publicationState: 'preview',
      fields: ['id']
    }
  }
}
```

Whereas `fields`  is used internally for the query, `publicationState` is just ignored

### Steps to reproduce the behavior

1. Create content type with draft system
2. Create a component with a relation field to component(1)
3. Add a content type with a repeatable component of (2) 
5. Try to deeply populate the component field while referenced content-type (1) is in draft. It doesn't work
6. Publish content-type of (1)
7. Now the populate query works

### Expected behavior

`publicationState` should work with populate just like `fields` does

### System

- Node.js version: v16
- NPM version: 6.14
- Strapi version: 4.1
- Database: postgres
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
Publication state is a top level filter only that propagates down all levels. Changing this to be a feature request instead

**Comment by markkorput** [comment]
This is still a problem

**Comment by damigrowth** [comment]
Its not propagating

> > Publication state is a top level filter only that propagates down all levels. Changing this to be a feature request instead
> 
> _Does_ it work like that? Because it's not propagating down for me, even though the top level component (and all intermediate components) do have drafts enabled (when specifying `publicationState=preview` I do get data from draft top-level components but not from child components)

It doesn't propagate for child components for me too..

**Comment by vovapankiw** [comment]
I have the same behavior, I'm using  "@strapi/strapi": "4.15.5",

**Comment by LuizPelegrini** [comment]
in Strapi ^4.21.1, nested relations are ignored when using `publicationState=preview`, it's not propagating, so my query ends up with empty relations when those are draft

**Comment by LucaNerlich** [comment]
did you ever find a solution for this?

I am on 5.9.0 and when using documents().findMany and populating a relation that has draft and publish enabled, I cannot get the published versions of those relation documents...
