### ISSUE TITLE
Authorization token doesn't get the same data like Unauthorized

### ISSUE THREAD

**Issue by OmarMtya** [strapi/strapi#12677]
### Describe the bug

This happens when I create a relation between any entity and users-permissions.
When I use the authorization bearer doesn't work the population in URL. Here's an example of what I recieve when I use the token:

![image](https://user-images.githubusercontent.com/39967608/155895400-a960ab74-c2fb-4a8d-9e98-5526a74d9edb.png)

Everything looks perfect, but what I need is a **user** attribute, which I only see it when I don't use any token.

![image](https://user-images.githubusercontent.com/39967608/155895429-3e85e446-5526-43b1-bdfe-5c47cbf79186.png)

### Steps to reproduce the behavior

1. Create a new entity
2. Add a new attribute to that entity, I called that user and User has many posts
3. Save and give permissions to Unauthorized and Authorized users to the **find** function
4. Get the data with Authorization Bearer and without it

### Expected behavior

Get the same data between an Authorized and Unauthorized user. Exactly the user attribute.

### Screenshots

![image](https://user-images.githubusercontent.com/39967608/155895540-e1e56da1-ba14-4a11-90ec-82e0d742b160.png)

![image](https://user-images.githubusercontent.com/39967608/155895400-a960ab74-c2fb-4a8d-9e98-5526a74d9edb.png)

![image](https://user-images.githubusercontent.com/39967608/155895429-3e85e446-5526-43b1-bdfe-5c47cbf79186.png)

### System

- Node.js version:  16.13.2 
- NPM version: 8.4.1
- Strapi version: 4.1.1 
- Database: sqlite
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11957
