### ISSUE TITLE
Error sending sending notification to Slack channel

### ISSUE THREAD

**Issue by Ann0426** [strapi/strapi#12679]
### Describe the bug

Created a webhook to automate sending notifications to a slack channel via slack incoming webhook but failed.

### Steps to reproduce the behavior

1. Log in as admin user in strapi dashboard
2. Go to `settings` -> `webhooks`
3. Click on `+ Create new webhook`
4. Create webhook name
5. Copy and paste the webhook url from slack incoming webhook.
6. Scroll down to Events. Click Entry and Media.
7. Click on `Save` and `trigger`
8. Error message shows `Error 400: missing_text_or_fallback_or_attachments`

### Expected behavior

There should be a notification in slack channel. 

### Screenshots
<img width="1253" alt="Screen Shot 2022-02-27 at 6 34 26 PM" src="https://user-images.githubusercontent.com/70348464/155905007-403e95c9-ea7d-463a-a912-842a20748edd.png">

### System

- Slack version : `Slack-4.23.0-macOS.dmg`
- Strapi version: v4 
- Operating system: MacOS

**Comment by kasonde** [comment]
Hi thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io) or our [Community Discord](https://discord.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.

**Comment by joeykay9** [comment]
@Ann0426 did you post in the community forum? Can you share link if so.

@kasonde I have the same issue with Error 400: no_text as the error message on `Trigger`. Seems there's something not right.

**Comment by Abhishek-cmd13** [comment]
I am getting the same error!
