### ISSUE TITLE
TypeError: undefined is not an object (evaluating 't[n].leftMenuSections.forEach')

### ISSUE THREAD

**Issue by agursoy** [strapi/strapi#12684]
Hi all, I was using strapi 3.0.4 since one year. I know it is pretty old version but it was old project. Last week I made small change. Everything is working great in my local machine. But in production it gives that errors. Is there anyone to see this kind of error in his project? 

<img width="1280" alt="Screen Shot 2022-02-28 at 12 42 58" src="https://user-images.githubusercontent.com/1447418/155961122-5c2dc2e6-1208-4a0f-a215-1236b0f5912f.png">

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
