### ISSUE TITLE
Cannot upload file via graphql

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#12680]
### Describe the bug

I get the following error when uploading a PDF file.
> Input buffer contains unsupported image format

### Code snippets

```javascript
import fs from 'fs-extra'
import { GraphQLClient, gql } from 'graphql-request'

const apiToken = '......'
const endpoint = '......'

const fixedFileName = 'force-override-filename'
const filePath = '/path/to/file'
const stream = fs.createReadStream(filePath)

const gqlClient = new GraphQLClient({endpoint})
gqlClient.setHeader('Authorization', `Bearer ${apiToken}`)

const {
  upload: { data: upload },
} = await gqlClient.request(
  gql`
    mutation ($file: Upload!, $name: String!) {
      upload(file: $file, info: { name: $name }) {
        data {
          id
          attributes {
            url
          }
        }
      }
    }
  `,
  {
    file: stream,
    name: fixedFileName,
  },
)
stream.close()
```

### System

- Node.js version: 16.13.2
- NPM version: 8.4.0
- Strapi version: 4.1.1
- Database: mysql8
- Operating system: debian11

### Additional context

In the <https://github.com/strapi/strapi/pull/12099> release, `isSupportedImage()` was added to `image-manipulation.js`, but graphql does not use it.

**Comment by ippoippo** [comment]
Related to #12673 🤔

**Comment by rktyt** [comment]
Code snippets added.

**Comment by petersg83** [comment]
Thank you @rktyt, you spotted correctly the missing use of `isSupportedImage`!
I created a PR to fix this bug
