### ISSUE TITLE
Content-types ‘User’  should be readable and editable in admin panel with default validations/regexps

### ISSUE THREAD

**Issue by hugetiny** [strapi/strapi#12689]
### Describe the bug

lots of bugs in register.
there are three fields (username,email,password) in the register payload.
there are no validation/regexp for username/password.

### Steps to reproduce the behavior

1. goto 'http://localhost:1337/graphql'
2. mutation register 
3.   if the password endswith special character/password starts with special character/username endswith special character......
4.  the server returns
```
{
  "errors": [
    {
      "message": "An error occurred during account creation",
      "extensions": {
        "error": {
          "name": "ApplicationError",
          "message": "An error occurred during account creation",
          "details": {}
        },
        "code": "STRAPI_APPLICATION_ERROR"
      }
    }
  ],
  "data": null
}
```

### Expected behavior

Content-types ‘User’ should be readable and editable in admin panel with default validations/regexps

### Screenshots

![image](https://user-images.githubusercontent.com/19659202/155995056-e3124eed-e647-4550-8567-c0e6adf59ff2.png)

### System

- Node.js version:  v16
- NPM version: v6
- Strapi version: v4
- Database: Postgres
- Operating system: Windows 10

**Comment by kasonde** [comment]
Please edit your title to be more explicit. You have mentioned lots of bugs but only outlined 1 clearly. Please outline the rest to help our product team better understand your experience.

**Comment by marcoautiero** [comment]
> ## Bug report
> ### Describe the bug
> lots of bugs in register. there are three fields (username,email,password) in the register payload. there are no validation/regexp for username/password.
> 
> ### Steps to reproduce the behavior
> 1. goto 'http://localhost:1337/graphql'
> 2. mutation register
> 3. if the password endswith special character/password starts with special character/username endswith special character......
> 4. the server returns
> 
> ```
> {
>   "errors": [
>     {
>       "message": "An error occurred during account creation",
>       "extensions": {
>         "error": {
>           "name": "ApplicationError",
>           "message": "An error occurred during account creation",
>           "details": {}
>         },
>         "code": "STRAPI_APPLICATION_ERROR"
>       }
>     }
>   ],
>   "data": null
> }
> ```
> 
> ### Expected behavior
> Content-types ‘User’ should be readable and editable in admin panel with default validations/regexps
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/19659202/155995056-e3124eed-e647-4550-8567-c0e6adf59ff2.png)
> 
> ### System
> * Node.js version:  v16
> * NPM version: v6
> * Strapi version: v4
> * Database: Postgres
> * Operating system: Windows 10

I don't meet any issue using special characters, I'm able to create a user even specifying `!!!!!!` as username and/or password. 
I think you used a username or password with less than 6 characters. Maybe we could refine the error message, but I don't see critical issue here.

**Comment by soupette** [comment]
@hugetiny I am closing this issue because we need more information. Feel free to reopen a new one with more details.

**Comment by hugetiny** [comment]
> @hugetiny I am closing this issue because we need more information. Feel free to reopen a new one with more details.

？？？
