### ISSUE TITLE
Run Strapi without the admin panel through CLI

### ISSUE THREAD

**Issue by mithenks** [strapi/strapi#12696]
### Summary

Add a way to run Strapi server without the admin panel through the CLI.

### Why is it needed?

Right now, through CLI commands, it's possibile to:
 * run both Strapi server and admin panel, with `develop` command
 * run both Strapi server and admin panel, with this last in watch mode, with `develop --watch-admin` command
 * run only the Strapi admin panel in watch mode, with `watch-admin` command

Especially in this last case Strapi server should already be running.

The only way I found in the documentation to run only the Strapi server is by settings `serveAdminPanel: false` option in `config/admin.js`. 
I hope we could add an option to the Strapi CLI to easily disable admin panel, without the need to modify a configuration file. 

### Suggested solution(s)

Add a `--no-admin-panel` option to `develop` CLI command that will run only Strapi server, without the admin panel.

**Comment by mithenks** [comment]
See https://github.com/strapi/strapi/pull/12697 for a possible implementation

**Comment by derrickmehaffy** [comment]
@mithenks technically this is already possible by setting the `serveAdminPanel: env.bool('SERVE_ADMIN', true)` which would allow you to do something like `SERVE_ADMIN=false yarn start`

Would that work for you, I'm just not sure we really need to add flags for every little thing when it's better to handle via environment variables.

**Comment by mithenks** [comment]
@derrickmehaffy thanks for your response, I haven't tested your suggestion but it seems good to me!

M.
