### ISSUE TITLE
Filtering datetime (e.g gte) with graphql not working

### ISSUE THREAD

**Issue by bedorn** [strapi/strapi#12699]
### Describe the bug

Filtering datetime field with graphql not working. I tried to use number (getTime()), but feedback is that string is expected.

### Expected behavior

Filtered result by datetime range queried.

### Code snippets

{
   anyContenttype(
    pagination: { limit: -1 }
        filters: {
          	detectedAt: { gte: "2022-02-28T23:00:00.000Z" }
        }
    ) {
        data {
          id
        }
    }
}

### System

- Node.js version: v12.20.1
- NPM version: 6.14.10
- Strapi version: v4.1.0
- Database: postgres
- Operating system: ubuntu 20.04

**Comment by cortopy** [comment]
I just experienced the same trying to filter by `updatedAt`

**Comment by jumptrnr** [comment]
> I just experienced the same trying to filter by `updatedAt`

Did you have any luck with a a work around?

**Comment by cortopy** [comment]
I just upgraded to 4.1.5 and seems to be working!

**Comment by kasonde** [comment]
Fixed with this PR #12725
