### ISSUE TITLE
Sentry integration is not working with Strapi 4

### ISSUE THREAD

**Issue by shyamlohar** [strapi/strapi#12702]
### Describe the bug
Strapi is not reporting any errors to the sentry. tried triggering errors by sending invalid graphql request and Rest API call in both cases it's not reporting errors to sentry.

### Steps to reproduce the behavior

1. Enable graphql plugin
2. Install latest sentry plugin (one compatible with sentry 4)
3. Configure sentry plugin in config/plugin.js as shown in step below 

```javascript
// path: ./config/plugins.js

module.exports = {
  //
  graphql: {
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: true,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
  sentry: {
    enabled: true,
    config: {
      dsn: "https://xxxxxxxxxxxxxxxxxxx@xxxxxxx.ingest.sentry.io/xxxxxxx",
      sendMetadata: true,
    },
  },
};

```
5. Create A collection
6. Add Data
7. Call graphql API / Rest API with invalid parameters 
8. It will return error response 
9. Error wont be logged in sentry

### Expected behavior

The error should be reported to the sentry and should be visible in the sentry dashboard.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:  v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.0.3
- Database: postgres / sqlite
- Operating system: mac / linux

**Comment by kasonde** [comment]
Please share your package.json just so we can have a look at what version of the sentry plugin you have installed. (Also please consider updating your strapi version and it's dependencies to the latest version)

**Comment by shyamlohar** [comment]
Hey this is what my package.json looks like sorry for delayed reply 

```{
  "name": "strapi-production",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "^4.0.3",
    "@strapi/plugin-i18n": "4.0.3",
    "@strapi/plugin-sentry": "^4.1.1",
    "@strapi/plugin-users-permissions": "4.0.3",
    "@strapi/strapi": "4.0.3",
    "pg": "^8.7.1",
    "sqlite3": "5.0.2",
    "strapi-middleware-cache": "^2.1.7"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "d131dec1-ef29-4211-987e-003549bb28cc"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by derrickmehaffy** [comment]
> Hey this is what my package.json looks like sorry for delayed reply
> 
> ```
>   "name": "strapi-production",
>   "private": true,
>   "version": "0.1.0",
>   "description": "A Strapi application",
>   "scripts": {
>     "develop": "strapi develop",
>     "start": "strapi start",
>     "build": "strapi build",
>     "strapi": "strapi"
>   },
>   "dependencies": {
>     "@strapi/plugin-graphql": "^4.0.3",
>     "@strapi/plugin-i18n": "4.0.3",
>     "@strapi/plugin-sentry": "^4.1.1",
>     "@strapi/plugin-users-permissions": "4.0.3",
>     "@strapi/strapi": "4.0.3",
>     "pg": "^8.7.1",
>     "sqlite3": "5.0.2",
>     "strapi-middleware-cache": "^2.1.7"
>   },
>   "author": {
>     "name": "A Strapi developer"
>   },
>   "strapi": {
>     "uuid": "d131dec1-ef29-4211-987e-003549bb28cc"
>   },
>   "engines": {
>     "node": ">=12.x.x <=16.x.x",
>     "npm": ">=6.0.0"
>   },
>   "license": "MIT"
> }
> ```

You have a bunch of miss-matched strapi packages and I know for a fact that `strapi-middleware-cache` doesn't work on the v4 as there is a new replacement package for it.

**Comment by shyamlohar** [comment]
@derrickmehaffy We are not using `strapi-middleware-cache` will be removing that from dependencies. did you mean I should have same versions for `@strapi/plugin-graphql` ,`@strapi/plugin-i18n` ,`@strapi/plugin-sentry` and `@strapi/strapi`

**Comment by derrickmehaffy** [comment]
Yes all packages prefixed with `@strapi/` should have the same version.

**Comment by derrickmehaffy** [comment]
@strapi/developer-experience / @strapi/expansion I'm not sure the root cause on this and it could be either package so I've set it to both of your projects for now.

**Comment by SujayPrabhu96** [comment]
Folks, does it have to do anything with https://github.com/getsentry/sentry-javascript/issues/4956

Strapi v4 by default adds sentry 6.3.0 to yarn lock file which has some bugs. Can we update sentry version to 6.3.2 as mentioned https://github.com/getsentry/sentry-javascript/issues/4956#issuecomment-1103679589
