### ISSUE TITLE
I can't filters in populate information of Holidays [V4]

### ISSUE THREAD

**Issue by DevToong** [strapi/strapi#12709]
### Screenshots

![ถามฟฟฟ](https://user-images.githubusercontent.com/86232812/156323065-c5bc8518-eccb-4a21-ae4c-14790af2ab5f.jpg)

### System

- Node.js version: 16
- Strapi version: v4
- Database: mysql
- Operating system: mac M1

### Additional context

Thank you very much for your help.

**Comment by kasonde** [comment]
Fixed in this [comment](https://github.com/strapi/strapi/issues/12578#issuecomment-1043597470). Please respect the issue template next time. And add explicit values for system specifications. i.e Node 16.x.x and Strapi v4.x.x, etc... This would help us track the issue down easier.
