### ISSUE TITLE
Upload REST on V4.1.1 always returns 401 

### ISSUE THREAD

**Issue by rcdk** [strapi/strapi#12705]
### Describe the bug

All endpoints going to the upload plugin returns 401 even http://localhost:1337/upload/files - 
The return is always:

{
    "data": null,
    "error": {
        "status": 401,
        "name": "UnauthorizedError",
        "message": "Missing or invalid credentials",
        "details": {}
    }
}

### Steps to reproduce the behavior

1. Download and install fresh Strapi V 4.1.1
2. Open admin and upload a file
3. Open Setting and grant public access to all endpoints, or just the "find" if you´ll only try: http://localhost:1337/upload/files
4. Open Browser and go to ex. http://localhost:1337/upload/files
5. You should now get a 401 return
6. This also goes for all other endpoint regarding the Upload plugin :-(
7. Post returns the same issue when trying to upload through the REST API

### Expected behavior

I would expect the endpoint to be accessible :-)

### Screenshots

![image](https://user-images.githubusercontent.com/3657898/156242131-b56910f6-0edf-4d74-8274-d5604185fc36.png)
![image](https://user-images.githubusercontent.com/3657898/156242201-de7ac1ba-df03-4631-9dde-64cfbfb367e9.png)
![image](https://user-images.githubusercontent.com/3657898/156242530-e8c71ed9-db30-4b80-9cbd-4b52b1fec2f2.png)

### System

- Node.js version: 14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.1
- Database: Have tried both Sqlite and MariaDB
- Operating system: Windows 10 - build 19044.1526

### Additional context

Please help or call me an idiot if i missed something :-) - Thanks so much, and thanks for a great product !!

**Comment by rcdk** [comment]
So ill just call my self an idiot :-) - I did not prefix the endpoint with api/ - Basically because i looked at:

![image](https://user-images.githubusercontent.com/3657898/156318399-2bda9e1c-cd39-49ee-9002-fdaad82cd875.png)

Instead of:

![image](https://user-images.githubusercontent.com/3657898/156318462-bd3cbdbd-530f-4a9e-91c6-47f21ad5122f.png)

Thanks a lot again for a great product :-)

**Comment by PHTremor** [comment]
Hie @rcdk 
I am having the same issues but with graphQl. since I can't use the link "api/uploads" what could be the problem and its solution?

my mutation
![image](https://user-images.githubusercontent.com/83657331/202965953-771ef0f2-40eb-4aec-b511-6c0b5628c9c3.png)

my variables
![image](https://user-images.githubusercontent.com/83657331/202966028-0dcdacb0-069b-4b08-950b-139374df0d03.png)

*Note: I'm using Cloudinary as the image provider
