### ISSUE TITLE
Login loop when adding a relation OneToOne related to USER

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1270]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**:5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb 3.6.4
- **Operating system**: macOS

**What is the current behavior?**
Adding a relation in a content type, make it oneToOne related to a new field in content type USER. It redirects to login and continue as a login loop.
For example, here are two content types, one is USER created by default, one is PROFILE created by me.
![screen shot 2018-05-24 at 2 42 10 pm](https://user-images.githubusercontent.com/3782817/40515247-ee493b6a-5f60-11e8-8df3-4f0b2dc861cb.png)
![screen shot 2018-05-24 at 2 44 23 pm](https://user-images.githubusercontent.com/3782817/40515265-f91698da-5f60-11e8-92be-fbba2a36d068.png)
I add a new relation UID to related to UID in USER, (UID is not created in USER). After saving, it goes to login loop.
![screen shot 2018-05-24 at 2 42 59 pm](https://user-images.githubusercontent.com/3782817/40515288-112dd3a2-5f61-11e8-87b5-76628566d059.png)

**Steps to reproduce the problem**
1. Create a content type A.
2. Add a few fields
3. Add a relation, oneToOne related to a new field in USER

**What is the expected behavior?**
Expect no loop.

**Suggested solutions**

**Comment by yummyelin** [comment]
Related to issue https://github.com/strapi/strapi/issues/849

**Comment by soupette** [comment]
@yummyelin I tried to reproduce your issue but I wasn't able to...

**Comment by lauriejim** [comment]
Look working well ! Try with clean install of Strapi, a fresh new project and fresh new database.
