### ISSUE TITLE
PublicationState not working for populated fields

### ISSUE THREAD

**Issue by vcque** [strapi/strapi#12719]
### Describe the bug

Publication state has no effect on results population when call the REST api.

### Steps to reproduce the behavior

1. Create a new strapi application `npx create-strapi-app@4.0.7 strapi-test --quickstart`
2. Create a `Parent` content type
3. Create a `Child` content type
4. Add a relation field : 1 parent <-> n children
5. Create a parent in published status
6. Create 2 children, one in draft status, the other in published status
7. Get the parent with populated field `http://localhost:1337/api/parents/1?populate=*`

### Expected behavior

The parent should only list one child : the published one. Here there is both.

### Screenshots

![image](https://user-images.githubusercontent.com/2727161/156389134-dba17961-3b72-4476-adfc-2292589db32d.png)
![image](https://user-images.githubusercontent.com/2727161/156389271-518bd2c6-ef39-4f4a-bca5-bffb7aced879.png)
![image](https://user-images.githubusercontent.com/2727161/156389484-3aa21c4e-c8a2-49f2-927b-1aa150ca073c.png)

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: tested in 4.0.7 and 4.1.1
- Database: Either postgresql or default (what is in quickstart)
- Operating system: Ubuntu 20.04.3 LTS

**Comment by Cefalu129** [comment]
This does not appear to be a duplicate of #12665. These are opposite problems. 

- #12665 says that a nested `populate` rightly does not return the drafted content, but setting `publicationState` to 'preview' is ignored by the nested `populate`.
- This says that a nested `populate` still returns the drafted content.

**Comment by LucaNerlich** [comment]
did you ever find a solution for this?

I am on 5.9.0 and when using documents().findMany and populating a relation that has draft and publish enabled, I cannot get the published versions of those relation documents...
