### ISSUE TITLE
Update Strapi version notice in the admin add up as many times as the page reloads

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#12728]
### Describe the bug

In the Strapi admin, if you're using a version less that latest, the notice that tells you that there's a newer version of Strapi available will spawn a new notice message instead of keeping the exact same one.

### Steps to reproduce the behavior

1. Create a strapi project with version <= latest
2. Ignore the message showing you that there's a new Strapi version
3. Make the admin restart itself by doing something like editing a content type
4. See the new message below (or above) the old message 

### Expected behavior

The old message should be aware of itself and not respawn

### Screenshots

![image](https://user-images.githubusercontent.com/13610895/156517833-1916810c-c25d-4499-9479-be0609d53e63.png)

### System

- Node.js version: 14.17.6
- NPM version: 6
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: MacOS BigSur
- Browser: Chrome

**Comment by ronronscelestes** [comment]
Thanks for creating the issue @kasonde 
Indeed the release notification is used in Admin which reloads when submitting a CT 🤔
We will see what we can do to fix that 🙏

**Comment by ronronscelestes** [comment]
Fixed with this PR https://github.com/strapi/strapi/pull/12813
(forgot to add `fixes` prefix to automatically close this issue 🙈)
Will close this PR, thank you @kasonde
