### ISSUE TITLE
Ambiguous notification counter on settings menu item in the left nav bar

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#12729]
### Describe the bug

The notification counter in the settings menu item object isn't as descriptive as it suggests. I know that the point of interest here is the "Upgrade your admin panel" link under the "Strapi version" section of the application details but at first glance, it's not easy to tell that IT is in fact the notification. The reason for this is the "See all pricing plans" link right next to it, appears exactly the same yet it's not a notification. 

### Steps to reproduce the behavior

1. Create Strapi project with version < latest
2. See settings menu item indicator
3. Click on menu item
4. See application detail

### Expected behavior

A more defined "notification" or call to action could be visible here.

### Screenshots

![image](https://user-images.githubusercontent.com/13610895/156519003-9b9a7d65-76f1-40ad-92be-feb076d24ce2.png)

### System

- Node.js version:14.17.6
- NPM version: 6
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: MacOS
- Browser: Chrome

**Comment by ronronscelestes** [comment]
Nice catch @kasonde - id's link of the application info page changed and it broke the notification UI that should appear - thank you!

**Comment by ronronscelestes** [comment]
hi @kasonde @derrickmehaffy 
I linked this issue with this PR fix https://github.com/strapi/strapi/pull/12777 that has been merged now, did I miss a step? I thought it would automatically close this issue 🕵️‍♀️

**Comment by derrickmehaffy** [comment]
> hi @kasonde @derrickmehaffy 
> I linked this issue with this PR fix https://github.com/strapi/strapi/pull/12777 that has been merged now, did I miss a step? I thought it would automatically close this issue 🕵️‍♀️

Not sure why it didn't tbh but thanks, I'll go ahead and mark as closed

**Comment by derrickmehaffy** [comment]
> > hi @kasonde @derrickmehaffy
> > I linked this issue with this PR fix #12777 that has been merged now, did I miss a step? I thought it would automatically close this issue female_detective
> 
> Not sure why it didn't tbh but thanks, I'll go ahead and mark as closed

@ronronscelestes Ah I know why

![image](https://user-images.githubusercontent.com/8593673/158273710-a2bfb15c-7af8-4edb-9a97-8e54b0a91e9d.png)

You need to put `fixes #whateverID` if you just put the link or the `#id` it won't do anything

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy ohh noted I'll be careful to add fixes in front of the idea next time, thank you!

No problem! :+1:

**Comment by suprMax** [comment]
I am still seeing this, was this already shipped?

**Comment by derrickmehaffy** [comment]
> I am still seeing this, was this already shipped? <img alt="Screen Shot 2022-03-28 at 8 29 33 PM" width="1187" src="https://user-images.githubusercontent.com/789031/160463258-8b0bfe58-0ea6-4bd7-b6b2-01ada7321d91.png"> Not even sure what the notification is about, running v4.1.5

Is that a new project or an updated one?

**Comment by ronronscelestes** [comment]
Hi @suprMax!
Subnav's notification should look like this: 

<img width="1104" alt="Screenshot 2022-03-28 at 22 32 42" src="https://user-images.githubusercontent.com/71838159/160482859-c678eb25-0a0f-4a8a-8984-37a9cc5e88e0.png">

The fix was shipped in this [release](https://github.com/strapi/strapi/releases/tag/v4.1.5) 🤔

**Comment by derrickmehaffy** [comment]
I'm guessing you need to rebuild your admin or make sure you delete your yarn.lock or package-lock.json to ensure the pre-built admin we ship with packages get's updated also.

**Comment by suprMax** [comment]
I upgraded from v4.1.3 to v4.1.5 and had that issue. Now I've upgraded to v4.1.7 and reinstalled/rebuilt everything. The issue seems to be gone now.
