### ISSUE TITLE
Save Database Connection / Module into database, not file.

### ISSUE THREAD

**Issue by imiskolee** [strapi/strapi#12726]
hi:

When we build a large dynamic system, the module creator and developer are not the same, current just supported save connection/module as a file, it's meaning developer as module creator.

I am thinking about how can we save module metadata to the metadata database, it keeps the source code static.

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

**Comment by imiskolee** [comment]
@kasonde pls review.
