### ISSUE TITLE
Decimal fields are stored as string in DB

### ISSUE THREAD

**Issue by soupette** [strapi/strapi#1273]
**Informations**
- **Node.js version**: v9.10
- **npm version**: v6.0.1
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: Postgres
- **Operating system**: Mac OS

**What is the current behavior?**
Decimal data is stored as string in the database.

**Steps to reproduce the problem**
- Create a content type with a decimal field
- Go to the `content-manager` and create an entry
- The admin send the data as with the correct format (number)

**What is the expected behavior?**
The data should be stored as numeric type.

I believe this issue as already been referenced but since it's working for integer and float and not decimal I'm opening a new issue.

**Comment by derrickmehaffy** [comment]
Odd, this was something I submitted a PR for @soupette

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/pull/1151

**Comment by soupette** [comment]
@derrickmehaffy I know but while working on the filters for the `content-manager` I noticed that it doesn't work only for numerical fields.

**Comment by derrickmehaffy** [comment]
@soupette Thats strange, can you check the database to confirm its being stored as a string? 

Based on this: https://www.postgresql.org/docs/9.5/static/datatype-numeric.html

`decimal` should be a valid data type, the same applies to MySQL and I can 100% confirm that is how its being set (though some have stated its default accuracy should be changed, that is something we should look at from both the cli and adminUI later on)

**Comment by derrickmehaffy** [comment]
@soupette I believe something like this should fix it: https://github.com/derrickmehaffy/strapi/commit/57cb35bb1053712b76d605fef4f05455482edb7e

**Comment by derrickmehaffy** [comment]
If you want I submit a pull request, but I'm about to head off for the holiday weekend here in the US in about ~30 minutes.

**Comment by kamalbennani** [comment]
I don't know how the fix in the PR will fix something, because after all, doing definition.client === 'pg' ? attribute.type : 'decimal' is the same as just using 'decimal', perhaps there is something that I missed :thinking:

**Comment by lauriejim** [comment]
Data is well stored, if you did an export of your table we got the correct format. Looks coming from node-pg.
