### ISSUE TITLE
Unable to login via google provider if email prefix exists as username.

### ISSUE THREAD

**Issue by bulby97** [strapi/strapi#12736]
### Describe the bug

As of now it's not possible to login via the google provider if the email prefix (before @) exists as username in the db.

### Steps to reproduce the behavior

1. Create a user with "smo" as username in strapi
2. Login via google with smo@gmail.com
3. See error 400, an error has occured

### Expected behavior

Strapi should be able to create the user, maybe with a random string as suffix.

### Screenshots

<img width="563" alt="image" src="https://user-images.githubusercontent.com/3509412/156477766-dce7accf-d442-4451-a725-913c4a9796e3.png">

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
