### ISSUE TITLE
More detailed release notes

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#12733]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

I would like to see more detailed release notes, or more frequently updated documentation, or more careful testing.

### Why is it needed?

I'm not sure which version they changed, but the latest version (v4.1.2) no longer includes relationship data in the webhook data.
Also, I could not find any release notes on this.

**Comment by derrickmehaffy** [comment]
All of our release notes are based on pull requests, if you believe something is a bug please open a bug report.

Release notes are here under each version, all GA release notes are generated automatically: https://github.com/strapi/strapi/releases
