### ISSUE TITLE
Can't use new values set on an already existing enum

### ISSUE THREAD

**Issue by crotru** [strapi/strapi#12735]
### Describe the bug

New values on existing enums can't be set in a collection type

### Steps to reproduce the behavior

1. Create a new enum component with two values : 
    <img width="500" alt="Capture d’écran 2022-03-02 à 10 20 52" src="https://user-images.githubusercontent.com/22882255/156334268-015b70c1-4fe6-4776-9ab2-0a458b62fea7.png">

2. Use it in a collection type : Works well when setting one of those two values (foo / bar): 
    <img width="500" alt="Capture d’écran 2022-03-02 à 10 27 56" src="https://user-images.githubusercontent.com/22882255/156334586-4f42fda3-72d5-4a63-9f2f-14fc2767bc6b.png">

3. Add a third value to the enum component (baz). 

4. That new value appears in the component list, but we get a "bad request" when saving the entry : 
    <img width="500" alt="Capture d’écran 2022-03-02 à 10 29 46" src="https://user-images.githubusercontent.com/22882255/156335385-379ce7dd-5d23-4e11-9213-8dfaf41802f1.png">

### Expected behavior

To be able to set and use new values for an existing enum

### System

- Node.js version: 14.18.1
- Strapi version: v4.1.1

### Additional context

- console returns `error: Not null constraint violation.` on save attempt

**Comment by crotru** [comment]
Actually same as #11872 that is stated as fixed by: https://github.com/strapi/strapi/pull/11864, but still having this in 4.1

**Comment by kasonde** [comment]
Can't reproduce this in v4.2.0

**Comment by derrickmehaffy** [comment]
Can't reproduce in v4.1.11, gonna set as closed for now.
