### ISSUE TITLE
Single Types do not seem to need plural API slugs

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#12732]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Single types do not seem to need plural API slugs to be defined for them. 

### Why is it needed?

It seems like an extra option when creating a single type that isn't used in the application.

### Suggested solution(s)

Probably removing that field for the create/edit single type form

### Screenshot
![image](https://user-images.githubusercontent.com/13610895/156520208-9b07c18c-bbaf-4dd1-b385-294fa600c757.png)

**Comment by vincentbpro** [comment]
We have discussed it with @alexandrebodin and pluralized slugs are used internally (as table name etc..), also they are necessary to avoid breaking changes when editing a single-type into a collection-type.

**Comment by alexandrebodin** [comment]
Closing :)

**Comment by krestaino** [comment]
Just to confirm, the pluralized slugs are only used internally? So if I wanted to create a single type called "settings" for my app, and I use "settingss" for the pluralized slug, I won't regret this and I'll never need to use the "settingss" slug? If that's the case, I don't care about using "settingss", but it does feel wrong.

**Comment by alexandrebodin** [comment]
As long as the singular and plural are different there won't be technical issues but we would definitely not recommend doing this from a naming standpoint
