### ISSUE TITLE
Entity service API - operator not applied

### ISSUE THREAD

**Issue by GautierDele** [strapi/strapi#12742]
### Describe the bug

From 4.0.8, it seems like the entity service API is not working correctly, applying a simple $lte operator according to the documentation is giving an empty where query to the db.
![image](https://user-images.githubusercontent.com/12382966/156579476-668c2b7c-7ad4-4186-a1ec-8278abd445c1.png)

The query logged:
![image](https://user-images.githubusercontent.com/12382966/156579504-6d881e94-5cfe-44c9-9181-44ed8d1aaaca.png)

The convert-query-param.js is called but it result in the object above.

The params given to the function:
![image](https://user-images.githubusercontent.com/12382966/156579943-65540af8-c02e-4836-883c-34ca8ca3a708.png)
![image](https://user-images.githubusercontent.com/12382966/156579992-1f32113a-81e4-4feb-8dfa-21b9ae87e490.png)

Has something changed ? Is the doc outdated ? https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/filter.html#lte

I'm continuing investigating for now

relates https://github.com/ComfortablyCoding/strapi-plugin-publisher/issues/15

### System

- Node.js version: 16
- NPM version: 8.6.0
- Strapi version: 4.1.2
- Database: MySQL
- Operating system: Windows 11

**Comment by GautierDele** [comment]
Ok so basically the bug is due to the fact that i'm trying to filter with a Datetime object, this is how to fix the query:
![image](https://user-images.githubusercontent.com/12382966/156585175-7169a712-f50b-4c2f-a303-a5f2d991b0b2.png)

This clearly is a bug

Might need some test on this to avoid regression in the future

**Comment by kasonde** [comment]
Fixed with #12725 :)
