### ISSUE TITLE
Make component icons optional

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#12741]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

In the Create a component section of the admin panel

<img width="789" alt="スクリーンショット 2022-03-03 22 24 44" src="https://user-images.githubusercontent.com/26789317/156574618-309fea62-5662-47a6-838c-d3cde2c16baf.png">

### Why is it needed?

- No matching icon exists.
- I don't think it's being used even though it's set up. 
 
stapi v4.1.2

**Comment by dzcpy** [comment]
+1, or allow it to use the same icon, and provide a search feature for the icon

**Comment by Slowl** [comment]
+1, this is super annoying to have to waste ~5mins looking for an icon (the search input is often useless)

It's even more annoying when you can't reuse an icon.
It would be better to just use a placeholder if no icon is selected

**Comment by bakkerjoeri** [comment]
Yeah hard agree. I also find myself sinking unnecessary amounts of time into finding an icon that might fit the bill, and it rarely does. Ideally icons would be optional and as an extra it would be great if you could reuse the same icon, especially since not all components share an immediate context.

**Comment by innesian** [comment]
It takes more time to pick out an icon than to make the field. You also can't seem to re-select icons or search icons. Even if there were labels underneath I could use the browser search to find one. If it's required for the UI somewhere just set a default and let it be optional.

**Comment by laugepetersen** [comment]
+1 Icon's either doesn't fit the component and can't be reused for similar components. We absolutely need this to be optional!

**Comment by carlos-duran** [comment]
+1 because I started using random icons for my components :(

**Comment by gu-stav** [comment]
Hello everyone. We decided to make the icon optional and will allow reusing the same icon.

I'll start working on this as soon as I have some capacity. 💫
