### ISSUE TITLE
Replace default `_id` by `id` with Mongoose

### ISSUE THREAD

**Issue by johannpinson** [strapi/strapi#1274]
When the schema is generated, the primaryKey used is `_id`.
But following the OpenCRUD and other GraphQL convention, the flag "_" should not be used for variable like `title` or `content`

I already try to change it inside the plugin and it seems to work with MongoDB because there are the two fields `_id` and `id` inside an document (but I don't try with MySQL).
But even after change the content of a document, the change looks good.

What do you think about it @Aurelsicoko ?

This is my snippet to test it (I already remove the value `_id` inside initialState):
```js
      if (_.get(model, 'options.timestamps') === true) {
        Object.assign(initialState, {
          id: 'String',
          createdAt: 'String',
          updatedAt: 'String'
        });

        Object.assign(acc.resolver[globalId], {
          createdAt: (obj, options, context) => { // eslint-disable-line no-unused-vars
            return obj.createdAt || obj.created_at;
          },
          updatedAt: (obj, options, context) => { // eslint-disable-line no-unused-vars
            return obj.updatedAt || obj.updated_at;
          },
          id: (obj, options, context) => { // eslint-disable-line no-unused-vars
            return obj._id || obj.id;
          }
        });
      }
```

**Comment by lauriejim** [comment]
I will transform this issue in more globally issue.

We have to replace and handle `id` for GraphQL and REST API and with `mongoose` and `bookshelf`

**Comment by johannpinson** [comment]
Ok but it's seems you will have some issue with mongoose.
The docs indicate some constraints about remove it:

> The _id field is the only exception because MongoDB includes it by default`

http://mongoosejs.com/docs/api.html#query_Query-select

**Comment by Aurelsicoko** [comment]
@johannpinson I made a proposal here https://github.com/strapi/strapi/pull/913. We can't remove the `_id` field but we can use the `id` instead. Mongoose supports both attributes to select an entity.

**Comment by johannpinson** [comment]
@Aurelsicoko In fact, keep the `_id` isn't a problem for me, it's just about the GraphQL logic and so remove the `_` to get just `id`.
But since mongoose consider `_id` as an ObjectId, it's why I suggest to add a custom resolver as for the timestamps fields (I don't remember if MySQL/Postre used both or only `id`).

**Comment by Aurelsicoko** [comment]
I was speaking about that because the issue is more global and not specific to GraphQL. I agree with your proposal, you should do it like that 👍

**Comment by johannpinson** [comment]
I will wait the issue #1356 to be merged before updating this resolver

**Comment by brunofigalveskk** [comment]
I'm getting some problems with these two field `id` and `_id`. When I create some content and don't use the content manager plugin to create them and I have 2 collections with a relationship strapi crashes for me when I try to edit one of these contents.

**Comment by acarrera94** [comment]
Is there a workaround for this in the meantime? I would much rather work with "id" than "_id" in the front end.

**Comment by PGzxc** [comment]
what can i do if i want to register user by strapi API not by content manager ; and   table users-permissions_user in mongodb has id field

**Comment by lauriejim** [comment]
Hello @PGzxc ! There is no issue on your message.
You just have to follow this documentation https://strapi.io/documentation/3.x.x/guides/authentication.html#registration

**Comment by derrickmehaffy** [comment]
+1 to completely getting rid of `_id` :stuck_out_tongue:
