### ISSUE TITLE
Register Now button not working in the Write for the Community section of Strapi website

### ISSUE THREAD

**Issue by oliverisMisiunas** [strapi/strapi#12750]
### Describe the bug

The Register Now button in the [Write for the Community](https://strapi.io/write-for-the-community) section of your official website (strapi.io) seems to not be functioning correctly. When it's clicked, the page just refreshes and adds "%23contact" to the URL, which doesn't have any visible effect.

### Expected behavior

I believe it would be more convenient if when the button is clicked, the page would automatically scroll down to the registration form which is at the bottom of the page.

### Additional notes

I apologize if this is the wrong repository for this issue. I couldn't find the repo for your official website.

**Comment by derrickmehaffy** [comment]
Thanks @oliverisMisiunas I've reported it to the team. I'm gonna go ahead and set this issue as closed and copy it over to our internal repo for the website.

We do plan to open source our website repo but until then we don't have a good place to report website issues.
