### ISSUE TITLE
critical issue is updating repeatable components

### ISSUE THREAD

**Issue by hsnbsst** [strapi/strapi#12753]
## Bug report

I want to share with you this problem that happened to me, I couldn't find a way in any way, can anyone help me?

When I want to update the data in a repeatable component, it deletes all the data in it and only updates the data I entered, leaving it id. is there any solution to this? I looked all over the document and couldn't find anything. what i want is just to update that data.

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/components-dynamic-zones.html#update

I'm doing the process in this link, but I don't want it to delete the data

### Code snippets

`await deleteOldComponents(uid, componentUID, entityToUpdate, attributeName, componentValue);`

### System

- Node.js version: v14
- NPM version:
- Strapi version: v4.1.1
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
