### ISSUE TITLE
Theme extension UI/Navigation bug in v4

### ISSUE THREAD

**Issue by cwsyth** [strapi/strapi#12755]
## Bug report
**Custom colors:**
Tried around a lot with admin panel custimization and in the documentations it says you can work with the theme key. So I created a custom app.js in my admin configuration:

_app.js:_
```
export default {
    config: {
        theme: {
            colors: {
                //color example https://github.com/boazpoolman/strapi-code-themes/blob/master/themes/github-dark-mode.js
                //or using darkTheme colors directly https://github.com/strapi/design-system/blob/main/packages/strapi-design-                 system/src/themes/darkTheme/dark-colors.js
            }},},};
```

Image of result: 
![example](https://user-images.githubusercontent.com/46164156/156788458-2f128afb-df64-4565-ac15-6020a2097132.PNG)
The problem I have right not with this method is: Everything color related works except the input fields, so the loginscreen input fields or the ones where you crete new collections and so on.

**Using Strapi Design System:**
Then I started to play around with strapi design system pakage which I got with npm from github page (version 1.0.0). Tried to change the theme this time with the strapi official one. Code now looks like this:

_app.js:_
```
import { darkTheme } from "@strapi/design-system/themes";

export default {
    config: {
        theme: darkTheme
    },
};
```
Image of result: 
![asdasdsa](https://user-images.githubusercontent.com/46164156/156788580-786832f2-8c8c-47d4-9ac0-5ff39daba44c.PNG)
Good part is it's fixed but with this method I encounter the bug that the Sidebar-Navigation buttons stop working (for example I want to got to the settings page), analyzing with dev tools, the link is there but clicking it doesnt work. Not really getting any error codes or hints that help me with the cause. 

**The weird part:**
Also tried to install the design system outside the main @*strapi folder, for example @strapi2 which leads to the first problem again: Inputs fields not applying the colors but with working navigation buttons. Also tried using the design system pakage from the admin module which doesn't work at all for me.

**Edit:**
Having the strapi design system makes manually applying colors work too. So installing it fixed the input fields missing the colors but leads to breaking the navigation links without even using a theme.

### System

- Node.js version: v16.14.0
- NPM version: 8.5.1
- Strapi version: 4.1.2
- Database: Postgres
- Operating system: Windows

**Comment by derrickmehaffy** [comment]
We will be releasing the dark theme here soon along with the required DS version bump with it. There is some issues in DS v1 that make it a breaking change and we can't release it yet so there will be a new v1.1 released without the breaking changes and handle them more gracefully.

cc @iparidhi / @HichamELBSI / @maevalienard not sure if how to help this user, if there is anything you can provide in the meantime.

**Comment by ronronscelestes** [comment]
hi @cwsyth 😀
as @derrickmehaffy said the DS v.1.0.0 holds some breaking changes, it's not recommended to use it yet!
to continue playing with the custom theme you can use `lightTheme` / `darkTheme` from v.0.0.1-alpha.78, input fields won't have background issues + no breaking changes on `Link` / `NavLink`

```
    "@strapi/design-system": "0.0.1-alpha.78",
    "@strapi/icons": "0.0.1-alpha.78",
```
hoping it will help 🚀

**Comment by cwsyth** [comment]
@ronronscelestes thanks for the reply. Tried out the version you have mentioned and it works flawlessly.

**Comment by derrickmehaffy** [comment]
Should be fixed I believe since we updated the DS quite a bit, marking as closed for now but if someone still has issues respond back and we can reopen.
