### ISSUE TITLE
Bug on UI production build. (reading 'startSection') 

### ISSUE THREAD

**Issue by tiennm-galaxt** [strapi/strapi#12752]
Hello.
I am getting error with strapi version 4.1.1
Node version: 16
This error occurs when I build docker production.
Please see the picture below for details.

When I upgrade to 4.1.2 this error does not occur. This happened before on 4.1.0.

I think this happens when not using the latest version stapi.

<img width="881" alt="Screen Shot 2022-03-04 at 16 19 09" src="https://user-images.githubusercontent.com/99155355/156735514-d2f3d13c-017e-4e36-8087-ce285e231130.png">

**Comment by AlMuz** [comment]
Hello.
Also updated strapi and strapi permission packages versions to the 4.1.2 and I'm getting the same error.
Also I'm getting TypeError: Cannot read properties of undefined (reading 'allPermissions').

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
