### ISSUE TITLE
strapi take too long time to start on first time (v3)

### ISSUE THREAD

**Issue by wikoci** [strapi/strapi#12765]
Strapi take too long time to start on first time .

it will take 5 or 10 min to start .
someone can explain this

**Comment by mpuz** [comment]
I does not start at all - i have tried installing using npx and it just stuck after login. Also tried docker version - same thing - Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
