### ISSUE TITLE
Response error object not accessible

### ISSUE THREAD

**Issue by kalexei** [strapi/strapi#12767]
### Describe the bug

When sending a bad request you can't utilise the "error" object from strapi response since an error is thrown right at the request time, making it hard to show users what kind of error it is.

### Steps to reproduce the behavior

1. Make a request like:
```js
const {data, error} = await axios.post(`${url}/api/auth/local`, {
  identifier: email,
  password
});
```
2. If successful, you can access data object, otherwise throws an error
```js
try {
  //....
  const {data, error} = await axios.post(`${url}/api/auth/local`, {
    identifier: email,
    password
  });
  if(error) throw error;
  //....
} catch (err) {
  console.log(err.message);
  // Error: Request failed with status code 400
}
```

### Expected behavior

Should not throw an error from the request and instead return an error object, that way it is possible to utilise it properly.

### System

- Node.js version: v16.14.0
- NPM version: 8.3.1 (yarn v1.22.17 for strapi)
- Strapi version: v4.1.2
- Database: postgresql
- Operating system: macos

### Additional context

Maybe I'm not doing it right but I cant access the error object because an error is thrown from the request immediately.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12280
