### ISSUE TITLE
Disabled localization for component doesn't work

### ISSUE THREAD

**Issue by TobiHaas** [strapi/strapi#12775]
### Describe the bug

When you create a component with a relation to another element it's not possible to reuse the same relation for all languages.
I wanted to create an ordered relation between two content-types.

Content type A contains multiple steps of content type B. I used repeating components because I wanted to order the relations and wanted to be able to reorder them.

So A1 contains B1, B3, B2, B6, B18.
And A2 contains B1, B18, B3
and so on...

I wanted to maintain these relations for all languages at once. But when you add the Bs to the As it seems like it creates new instances of the Bs every single time. Because when you create a relation in this component in language DE and save it and then you switch to EN it seems like there is the relation but when you click on 'Details' in the component relation you end up in a 'EN' instance of B but with DE texts.

### Steps to reproduce the behavior

1. Create two content types A and B. With two languages
3. Create some entries in both content types and languages.
4. Create a component that includes a relation to B with disabled localization
5. Go to A and use the component in one language and link to one object of B
6. Switch language and check the linked component. It shows the active language but uses content from the inactive language.

### Expected behavior

If you disable localization within a component with a relation you would expect that it always uses the active language. Just like a regular relation.
It would be also cool to be able to order relations anyway.

### System

- Strapi version: v4.1.1

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12538
