### ISSUE TITLE
 Plugin name is not in kebab (an-example-of-kebab-case)

### ISSUE THREAD

**Issue by raghav-zwt** [strapi/strapi#12778]
I have followed these steps https://strapi.io/blog/how-to-build-a-strapi-custom-plugin than after `run yarn develop --watch-admin`

![image](https://user-images.githubusercontent.com/99175516/157213997-c8728d39-0d31-4d0e-9c07-ba666a38899c.png)

**Comment by raghav-zwt** [comment]
Package Version

```
"@strapi/design-system": "^1.0.0",
"@strapi/icons": "^1.0.0",
"@strapi/plugin-i18n": "4.1.2",
"@strapi/plugin-users-permissions": "4.1.2",
"@strapi/strapi": "4.1.2",
"mysql": "2.18.1",
"strapi-plugin-menus": "^0.2.2",
"styled-components": "^5.3.3"
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
