### ISSUE TITLE
Strapi ORM Documentation

### ISSUE THREAD

**Issue by mig4ng** [strapi/strapi#1277]
*BUG TEMPLATE* 

**Informations**
- **Node.js version**: v10.1.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MongoDB
- **Operating system**: Linux

**Is there any documentation regarding the strapi orm?**
I am trying to add custom services to my models, I want to update my content type when I use the GET route, I simply want to increave an attribute value by one and I searched the whole documentation and such thing does not exist or I am unable to find it.
Is documentation for this planned or already somewhere I am not finding?

**Comment by mnlbox** [comment]
@mig4ng Please up vote to **Documentation** in https://strapi.io/vote :wink:

**Comment by nurikabe** [comment]
Are you running into a problem where returning data from the MongooseJS ORM doesn't allow you to modify the object?  If so, transform the returned Mongoose document to a JavaScript object.

**Comment by lauriejim** [comment]
@mig4ng Please follow the mongoose ORM documentation.
