### ISSUE TITLE
admin: enable to wrap the admin app in additional providers

### ISSUE THREAD

**Issue by macrozone** [strapi/strapi#12785]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Develors should be able to wrap the admin app in additional providers.

#### Background

I want to create a strapi plugin that provides ReactPage as content editor in strapi. (i am maintainer of ReactPage).

https://react-page.github.io/,

ReactPage is a "rich-layout" editor, its is more than wysiwyg; developers can add any react components to it, so that your webmasters can add videos, product sliders, etc. to your content, with multi-column layouts and drag and drop.

It can be used both for displaying content (read only) and editing content. (It uses code splitting to only load minimal bundles when only used in read-only).

I now want to used it in a "two-tier" setup, with strapi as cms and a nextjs frontend.

This requires code sharing between frontend and strapi, where you share the configuration for `ReactPage` (mainly the cell-plugins that contain the various components that can be added). This is easily solvable and can lead to really great cms experiences.

#### problem

Creating a custom strapi plugin with a reactPage editor was easy and works so far, its basically a custom field (atm. for the json type)

Problem: a developer that uses my plugin should be able to configure the plugin. This usually involves the cell types (CellPlugins) that can be added to the content. These "CellPlugin"s are defined as objects, where you have a Renderer which is a react-component. So my plugin would not directly define cell plugins, that would be up to the developer that integrates my plugin into their strapi admin app.

I noticed that its not documented how to pass config to custom fields (see https://github.com/strapi/documentation/issues/783).

I noticed however, that you can indeed pass arbitrary config to `attributes` inside schema.json in content-types, these attributes in turn are available in the plugins component.

**However there is a catch**:  you can only pass primitives there, as it is a json. But in my case, i want to pass components and other complex objects to the custom field.

#### Possible solution:

If developers or plugins could wrap the admin app with React providers, you could solve this problem like this: 

- the developer would wrap the admin app with a special wrapper (a react context provider) where the full config for my plugin is defined 
-  in practice you would have multiple configs, e.g. a blogpost might have different components than a landing page
- you could use the schema.json attributes to select which config to use (if multiples are available)

#### Benefits

providing a way to wrap the whole admin app in a custom provider also enables other use cases and is really simple to implement.

### Suggested solution(s)

somewhre in config/admin.js you should be able to declare a Component that wraps the admin app. Alternativly we could also hook right before the app is mounted into the dom tree.

### Alternatives

Initially i raised this documentation issue: https://github.com/strapi/documentation/issues/783 where i was looking for a more direct way into passing config to custom field components. 

But i think the combination with a provider/wrapper with custom attributes in the schema.json is the better way and cleaner way to do it.

### Related issue(s)/PR(s)

I think implementing this wrapper api should be easy enough, i hope i can do a pr for that.

**Comment by derrickmehaffy** [comment]
Hello! Custom fields is actually a feature that we will be working on in Q2.

I'm going to close this issue in favor of https://feedback.strapi.io/developer-experience/p/custom-fields

cc @strapi/product for whichever PM is overseeing custom fields :)
