### ISSUE TITLE
REST API - Field Type Media Returns NULL , maybe better to return empty object?

### ISSUE THREAD

**Issue by da-kicks-87** [strapi/strapi#12782]
### Please describe your feature request

To have the REST API, field type Media return empty object and not NULL

### Why is it needed?

When working with the REST API and destructuring the objects from the Media Field type an error is thrown and crashes the app from Next.js if the value is NULL.  Media Field type is set to NULL on default if no data is added by end-user in CMS. This is not the case in many of the other field types. They are either empty strings or empty arrays.

For example say if I have an Article content type and I want the Featured Image field (Media type) to be optional and have the page render regardless if user choose an Featured Image or not. In order to achieve this I would have to add a conditional check before I destructure the object from the API. I feel its an unnecessary extra step that would be simpler if the Media Field type was an empty object and not a NULL by default.
Anyone else think this should be changed? Is there a reason on why it Media Field type is set to NULL on default?

### Suggested solution(s)

I suggest the Media Field type should be an empty object by default.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by da-kicks-87** [comment]
@derrickmehaffy Updated to the template.
