### ISSUE TITLE
customize folders to watch for `--watch-admin`

### ISSUE THREAD

**Issue by macrozone** [strapi/strapi#12784]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Let devlopers configure which folders to watch additionaly. 

### Why is it needed?

Use case: sharing code between a frontend app and a backend app.

In this case, you will have a setup with some shared package, that can be achieved by using yarn workspaces or similar.

I could manage to get this to work, but `develop --watch-admin` won't restart on changes to the shared code.

### Suggested solution(s)

there is already an option `watchIgnoreFiles`, but i am looking for the opposit: to whitelist certain directories to watch.

So maybe `additionalWatchFiles` ?

**Comment by macrozone** [comment]
> @macrozone would this be an option for the front-end or the back-end?

for the admin ui

**Comment by derrickmehaffy** [comment]
This issue was discussed with our product team and currently we don't feel this is something we would want to implement. Thank you for opening the issue and please feel free to open a feature request on our feedback database: https://feedback.strapi.io

Thank you! :pray:
