### ISSUE TITLE
Entry Title multiple custom to display

### ISSUE THREAD

**Issue by AndreaCeccatoUlulab** [strapi/strapi#12795]
![image](https://user-images.githubusercontent.com/92713509/157467557-46f77d28-fbcd-42fd-8dc5-8a1900f306f9.png)
![image](https://user-images.githubusercontent.com/92713509/157468762-7d6eb649-9bb3-4c8c-be3c-b1266676216f.png)

Give the possibility in the "/ configurations / edit" routes to modify the display view with more fields in a personalized way, and not just one

**Comment by AndreaCeccatoUlulab** [comment]
![image](https://user-images.githubusercontent.com/92713509/157482758-32615cf6-bcb8-4040-9d85-26a6eb6435b8.png)
Also give the possibility to modify the display even with fields of the "relationship" type with the desired property

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
