### ISSUE TITLE
Feature Request - Support Soft Delete

### ISSUE THREAD

**Issue by imiskolee** [strapi/strapi#12790]
# Feature request
Please describe your feature request
[] I have created my request on the Product Board before I submitted this issue
[] I have looked at all the other requests on the Product Board before I submitted this issue

# Summary
Support soft delete.

# Why is it needed?
the user story already created on: https://github.com/knex/knex/issues/5052, looks like the knex can not support it, because of it's just a cross-database SQL Builder, but an ORM.

I am thinking about how can we support soft delete on API & admin? 

# Suggested solution(s)
1. create a flag when creating connection, called `Enabled Soft Delete`
2. when the flag is enabled, route all delete record(s) operators to update.

if the design is confirmed, I can start the PR.

# Related issue(s)/PR(s)

**Comment by derrickmehaffy** [comment]
> if the design is confirmed, I can start the PR.

We would need to have an RFC first: https://github.com/strapi/rfcs

**Comment by derrickmehaffy** [comment]
This isn't something we will work on ourselves so going to mark as closed
