### ISSUE TITLE
createIfNotExists record in components

### ISSUE THREAD

**Issue by AndreaCeccatoUlulab** [strapi/strapi#12794]
"A component can be updated while updating an entry with the Entity Service API. If a component id is specified, the component is updated, otherwise the old one is deleted and a new one is created:"

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/components-dynamic-zones.html#update

Create only if the component record does not exist, without overwriting the record with a new id but the same values.

a similarity function a **createIfNotExists()** or  sync() 

**A)**
`strapi.entityService.createIfNotExists('api::article.article', 1, {
  data: {
    myComponentRepeatable: [
     {
      limit: 10,
      value: 100
     },
     {
      limit: 20,
      value: 119
     },
   ]

  },
});`

**B)**
NEW records
`  {  
      id: 1,
      limit: 10,
      value: 100
     },
     {
      id: 2,
      limit: 20,
      value: 119
     }`
     
 **C)**
by repeating the same action of point A, the result is the same as point B, without generating new records with new ids (3 and 4)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
