### ISSUE TITLE
Cloudinary upload provider plugin not getting actionOptions config

### ISSUE THREAD

**Issue by neilpoulin** [strapi/strapi#12809]
#### Overview of problem
Using a fresh installation of Strapi, I noticed the cloudinary upload provider is not receiving the `actionOptions` configuration as expected from the `upload` config in `./config/plugins.js`. The `actionOptions` should be able to configure the behavior of how files are uploaded (or deleted) on cloudinary by enabling parameters to be sent to the cloudinary API call. The latest documentation describes how to use the `actionOptions` to pass configuration to the `upload` and `delete` functions. However, when adding a configuration (such as `folder: 'development'`) the options are no passed to cloudinary and my files are stored in the root directory in cloudinary. 

The documentation for the cloudinary provider can be found [here](https://github.com/strapi/strapi/tree/master/packages/providers/upload-cloudinary). 

I was able to configure these options in older versions of strapi (`3.6.5`). 

Note: I am aware that the plugins configuration object now needs to be nested under a `config` key in the plugins file. 

#### Root cause(s)

Debugging through the Strapi source code, it looks like a couple things are happening that cause the expeced configuration not to make it into the cloudinary plugin as expected. 

1. The `upload` and `delete` functions are patched/overloaded in the `@strapi/plugin-upload/server/bootstrap.js` file, which attempts to pass in the `actionOptions` configuration to the provider (if it exists). The code snippet looks like this: 

```js
  // @strapi/plugin-upload/server/bootstrap.js
  
  // ... omitted code that sets up the provider
  
 const providerInstance = provider.init(providerOptions);

  return Object.assign(Object.create(baseProvider), {
    ...providerInstance,
    upload(file, options = actionOptions.upload) {
      return providerInstance.upload(file, options);
    },
    delete(file, options = actionOptions.delete) {
      return providerInstance.delete(file, options);
    },
  });
  ```

When debugging the server bootup, i can see that indeed `actionOptions` has the expected value that I had configured in `config/plugins.js`. 

2. As noted in the [Upload docs](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#create-providers), the method `uploadStream` is used preferentially over `upload` on the provider instance. 
> For performance reasons, the upload plugin will only use the uploadStream function if it exists, otherwise it will fallback on the upload function.

Notice, however, that the `uploadStream` method does not get overloaded with `actionOptions` like `upload` and `delete` methods do. 

3. The `cloudinary-provider` implements the `uploadStream` method, which calls the same internal function as the `upload` method. However, since the `uploadStream` method was not overloaded, the custom configuration is not passed to the provider instance, and as a result my files are not uploaded into the configured folder. 

#### Proposed solution(s)

I as able to create my own custom provider to reproduce and ultimately fix this issue. As I see it, there are (at least) 2 ways to address the issue. 

1. **Fix the issue for the cloudinary-provider specifically.** 
To do this, the `uploadStream` method simply needs to be removed from the provider. By doing so, Strapi will fall back to using the default `upload` method, which gets properly initialized with the custom actionOptions in the `bootstrap.js` script. 

2. **Fix the issue for _all_ upload providers**
This would require editing the `bootstrap.js` file to overload the `uploadStream` method in an identical way to the `upload` and `delete` methods. 

### Steps to reproduce the behavior

1. install `@strapi/provider-upload-cloudinary` (v4.1.3 at time of writing)
2. Add a `plugins.js` file with the following contents: 
```js
// ./config/plugins.js
module.exports = ({env}) => ({
  upload: {
    config: {
      provider: 'cloudinary-custom',
      providerOptions: {
        cloud_name: env('CLOUDINARY_NAME'),
        api_key: env('CLOUDINARY_KEY'),
        api_secret: env('CLOUDINARY_SECRET'),
        folder: env('CLOUDINARY_FOLDER', 'development'),
      },
      actionOptions: {
        uploadStream: {folder: env('CLOUDINARY_FOLDER', 'development')},
        upload: {folder: env('CLOUDINARY_FOLDER', 'development')},
        delete: {},
      },
    },
  },
})

```
4. Ensure you have all of environment variables set in your `.env` file to enable uploading to cloudinary
5. Upload a file via the Media Library in the Strapi Admin UI. 
6. Go to Cloudinary, notice that the file you uploaded is not in the folder you configured via env variables (or `development` fallback). 

### Expected behavior

I would expect the above configuration to save my files to the `development` directory in cloudinary.  

### Screenshots

not applicable 

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: `14.19.0`
- NPM version: `6.14.16`
- Strapi version:  `4.1.3`
- Database: postgres 12
- Operating system: MacOS

**Comment by gvocale** [comment]
Waiting on this fix 🙏

**Comment by rozenteno** [comment]
Hello, I'm having the same problem as the issue describes. Is there any solution or workaround for this? 
Thank you ☺️
