### ISSUE TITLE
[v4] Overriding social auth providers mapping to user

### ISSUE THREAD

**Issue by SergeShkurko** [strapi/strapi#12805]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

For strapi v4

Simple way for overriding `@strapi/plugin-users-permissions/server/services/providers.js` purest request to user model transformation

### Why is it needed?

When the `User` model is expanded, I want to get more data from the provider to automatically fill it
It is desirable to provide an independent opportunity to map data

### Suggested solution(s)

Hm, maybe add special api in plugin with plugin extension, like this:
`file: src/extensions/users-permissions/strapi-server.js`
```js
module.exports = (plugin) => {
    plugin.services.providers.customResponseMappers = {
      'google': (body) => ({...}),
      'facebook': (body) => ({...}),
    }
     // or 
    // plugin.services.providers.customResponseMapper = (provider, body) {
    //   ...
    // }
 }
```

add new api call on mapping, example:
```diff
      case 'google': {
        const google = purest({ provider: 'google', config: purestConfig });

        google
          .query('oauth')
          .get('tokeninfo')
          .qs({ access_token })
          .request((err, res, body) => {
            if (err) {
              callback(err);
            } else {
+             if (this.customResponseMappers != null && 'google' in this.customResponseMappers) {
+               callback(null, this.customResponseMappers['google'](body));
+             } else {
                 callback(null, {
                   username: body.email.split('@')[0],
                   email: body.email,
                  });
+             }
           }
          });
        break;
      }
```

### Related issue(s)/PR(s)

[Let us know if this is related to any issue/pull request.](https://github.com/strapi/strapi/issues/6014)

**Comment by SergeShkurko** [comment]
Solution from docs outdated and not works with strapi v4  
https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#user-object-in-strapi-context

**Comment by SergeShkurko** [comment]
Related #8942

**Comment by SergeShkurko** [comment]
Related #12193

**Comment by mattia85** [comment]
@derrickmehaffy any updates about this feature request? 
Thank you.

**Comment by derrickmehaffy** [comment]
Currently it's on indefinite hold as we have yet to determine if we want to continue updating the current U&P plugin or build an entirely new one.

**Comment by dz85** [comment]
It's September now. But what's the official advice from Strapi to add a new custom provider for users-permissions using the extensions forming? we are looking forward to it. T T And it seems that the src/extensions/xxx/strapi-server.js doesn't work for strapi 4.3.8(the latest version).

**Comment by Dan6erbond** [comment]
Bump. I'm trying to extend the U&P plugin with a "simple" provider, but it's turning out to be a lot less simple than hoped. I can't even figure out how/where to register a new provider, let alone make sure it shows up in the UI, etc. and it's a must-have feature because my OAuth provider isn't one of the defaults.

**Comment by diacu** [comment]
I managed to rewrite the service like that:
- create a file `src/extensions/users-permissions/strapi-server.ts` with the following content:
```ts
import _ from "lodash";
import { getService } from "@strapi/plugin-users-permissions/server/utils";

export default plugin => {
  const providersService = plugin.services["providers"];
  // I suppose we could also reference providers-registry, in order to add new providers.

  plugin.services["providers"] = ({ strapi }) => {
    /**
     * Duplicate of original method.
     * Could not find a better way, this method is not exported in the original service
     */
    const getProfile = async (provider, query) => {
      // [...]
    };

    // The original service is exporting connect and buildRedirectUri (I reuse it).
    const { buildRedirectUri } = providersService({ strapi });

    // Rewrite the connect with some other rules
    // Example: I wanted to handle the advancedSettings.unique_email case
    // and merge the accounts in case same email address is used with different
    // social auth providers.
    const connect = async (provider, query) => {
      // [...]

      return existingOrNewCreatedUser;
    };

    return { connect, buildRedirectUri };
  };

  return plugin;
};

```

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/overriding-social-auth-providers-mapping-to-user

Thanks!

**Comment by lmoy28** [comment]
> I managed to rewrite the service like that:
> 
> * create a file `src/extensions/users-permissions/strapi-server.ts` with the following content:
> 
> ```ts
> import _ from "lodash";
> import { getService } from "@strapi/plugin-users-permissions/server/utils";
> 
> export default plugin => {
>   const providersService = plugin.services["providers"];
>   // I suppose we could also reference providers-registry, in order to add new providers.
> 
>   plugin.services["providers"] = ({ strapi }) => {
>     /**
>      * Duplicate of original method.
>      * Could not find a better way, this method is not exported in the original service
>      */
>     const getProfile = async (provider, query) => {
>       // [...]
>     };
> 
>     // The original service is exporting connect and buildRedirectUri (I reuse it).
>     const { buildRedirectUri } = providersService({ strapi });
> 
>     // Rewrite the connect with some other rules
>     // Example: I wanted to handle the advancedSettings.unique_email case
>     // and merge the accounts in case same email address is used with different
>     // social auth providers.
>     const connect = async (provider, query) => {
>       // [...]
> 
>       return existingOrNewCreatedUser;
>     };
> 
>     return { connect, buildRedirectUri };
>   };
> 
>   return plugin;
> };
> ```

Hey ! 

I'm new to strapi so sorry if i'm not getting something abvious.

I'm using js (not ts as your file is), I just copy pasted the functions from my node_modules into your code and added a console.log() in the start of each functions but I got nothing logged when using Google Auth... Could you someone point me in the right direction ? 

Thanks a lot
