### ISSUE TITLE
Why strapi trying to connect to https://analytics.strapi.io/track ?

### ISSUE THREAD

**Issue by kevrat** [strapi/strapi#1280]
Get it when start my first project on strapi

```
(node:28331) UnhandledPromiseRejectionWarning: FetchError: request to https://analytics.strapi.io/track failed, reason: connect ETIMEDOUT 54.148.198.248:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/strapi/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
(node:28331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It is tracking my project info? Where can i find note about what kind info its track and how can i disable it?

**Comment by Aurelsicoko** [comment]
@kevrat Thank you for raising this issue! A similar issue (https://github.com/strapi/strapi/issues/479) has been opened a few months ago.

We are using this to improve the product and know more about the usage of Strapi. To be 100% transparent about this process, here the list of the data we're collecting and why:

- uuid _(unique ID of the app)_
- model names and attributes names _(Is Strapi used to build content or product or service API?)_
- environment (dev, staging, prod)
- node_modules names _(Are developers integrating Strapi with Stripe? It means that we should develop a plugin to simplify the process with Stripe. Are developers using Strapi with strapi-bookshelf or strapi-mongoose? It helps us to prioritize the issues.)_
- os
- build configurations _(how many people are deploying the admin on another server?)_

This is not personal data, it has nothing to do with GDRP btw. You can disable the tracker by removing the `uuid` property in the `package.json` of your project.

-----

We are going to add a section in the documentation to be transparent with everyone. We're not collecting sensitive data (databases, env variables, custom config) and everything is encrypted. You should be aware that many other open-source projects such as Node.js or npm are tracking you as well. This is necessary to understand how the product is used, we don't have bad intentions behind this 👍

**Comment by kevrat** [comment]
All is clear, thanks for the explanation

**Comment by Antoine-lb** [comment]
Even after reading a lot of the documentation, and more than 4 months of heavy use of Strapi, I just learned this now.

No matter if is anonymised and in good faith, I was a very bad surprise and I blame you for it. 

Do a better job comunicating such activity. Everyone running a Strapi back-end in production should now it.

Now I look like a total idiot in behalf of my company for selling the use of Strapi without knowing you where pushing data to your servers even in production.

**Comment by derrickmehaffy** [comment]
@Antoine-lb I'm not sure how we could make it more clear, the `Telemetry` entry on the documentation is 6th item down on the table of contents, it's shown to you the first time you open up the documentation.

The information provided to us only shows us where we should focus our development, and what features are most important to everyone. It also helps us highlight issues to fix bugs before they become a major problem. We are not selling this data, nor does it ever leave our hands, it's only purpose is to help make the project better.

You are welcome to read through the documentation for it here: https://strapi.io/documentation/v3.x/getting-started/usage-information.html#commitment-to-our-users-data-collection

**Comment by mbaev** [comment]
For those who's finding the issue relevant after years, here's the solution:
https://docs.strapi.io/dev-docs/cli#strapi-telemetrydisable

**Comment by klaudiaaaj** [comment]
Hi, try run in the command line
 ` npm run strapi telemetry:disable    `
