### ISSUE TITLE
CORS issue with ApolloServer middleware

### ISSUE THREAD

**Issue by surgeharb** [strapi/strapi#12816]
Hello 👋 
I opened this [PR](https://github.com/strapi/strapi/pull/12815) which has all the details. Can anyone please check if it is valid?

### Issue
`header in the response must not be the wildcard '*' when the request's credentials mode is 'include` when calling the `/graphql` endpoint with `credentials=include` config which enforces cors.

Apollo Client (example: React)
```js
const apolloLink = createHttpLink({
  uri: 'http://localhost:1337/graphql',
  credentials: 'include', // in order to send cookies and force cors
});

const apolloClient = new ApolloClient({
  link: apolloLink,
  cache: new InMemoryCache({
    addTypename: false,
  }),
});
```

Strapi Plugins Configuration
```js
// ./server/config/plugins.js
module.exports = {
  graphql: {
    config: {
      endpoint: '/graphql',
      apolloServer: {
        cors: {
          credentials: true,
          headers: ['Content-Type', 'Accept', 'Authorization'],
          origin: 'http://localhost:3000',
        },
      },
    },
  },
};
```

When enforcing `cors` with `/graphql` endpoint, if it is not passed down this middleware. `cors` will be set to `origin=*`.
```js
// apollo-server-koa/src/ApolloServer.ts - line 100
if (cors === true || cors === undefined) {
  // Unlike the express `cors` package, `fastify-cors`, or Hapi, Koa's cors
  // handling defaults to reflecting the incoming origin instead of '*'.
  // Let's make it match.
  middlewares.push(
    middlewareFromPath(path, corsMiddleware({ origin: '*' })),
  );
} else if (cors !== false) {
  middlewares.push(middlewareFromPath(path, corsMiddleware(cors)));
}
```

**Comment by surgeharb** [comment]
Added the fix in a separate PR: https://github.com/strapi/strapi/pull/12815
Please let's check if this is a valid issue, but it solved my problem with CORS + ApolloServer.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by darius-v** [comment]
Hello,

@surgeharb 

```
apolloServer: {
        tracing: false,
        introspection: true,
        // The plugin would otherwise mount its own @koa/cors with origin '*' on /graphql,
        // bypassing the allowlist in config/middlewares.ts (strapi::cors). Let the global one handle it.
        cors: false,
      },
```
we did not find the docs about this cors parameter, is it ok to add it this way?
