### ISSUE TITLE
Error requesting API after changing port number on new installation of 4.1.3

### ISSUE THREAD

**Issue by wileyknight** [strapi/strapi#12826]
### Describe the bug

Changing the port to anything other than 1337 causes the API to error.

### Steps to reproduce the behavior

1. Create new project with npx create-strapi-app@latest my-project
2. Setup project normally and run develop.  Enter credentials and stop the server.
3. Change the port in .env and server.js to any valid port other than 1337
4. Run develop and open the admin panel. See error.

### Expected behavior

Strapi running normally on preferred port number.

### System

- Node.js version: 16.14.0
- NPM version: 7.20.5
- Strapi version: 4.1.3
- Database: Postgres
- Operating system: Ubuntu 20.04.4

**Comment by stefanbinder** [comment]
I just can confirm the bug.
Maybe console errors are helping to solve the bug:
```
Refused to connect to 'http://localhost:1337/admin/project-type' because it violates the following Content Security Policy directive: "connect-src 'self' https:".
```
or
```
Refused to connect to 'http://localhost:1337/admin/init' because it violates the following Content Security Policy directive: "connect-src 'self' https:".
```

**Comment by flowck** [comment]
I'm facing the same error on a brand new installation.

Version: 4.1.5

**Comment by mukkoo** [comment]
Same issue for me

**Comment by derrickmehaffy** [comment]
When you change the port you need to build the admin panel, we ship Strapi now with a prebuilt admin panel but that expects ports 1337.

This is intended for now as we can't use dynamic ports in the admin build.

**Comment by slootjes** [comment]
For someone else ending up here and not knowing what to do after changing the port and having a broken admin, run this command: `npm run build` and then start your development server again by running: `npm start develop`.
