### ISSUE TITLE
I can't open admin log in page.It auto redirect to register.

### ISSUE THREAD

**Issue by sb4yd3e** [strapi/strapi#1282]
**Informations**
- **Node.js version**: 8.11.1
- **npm version**: 6.1
- **Strapi version**:v3.0.0-alpha.12.2
- **Database**:Mongo DB
- **Operating system**:OSX

When in log out from admin panel it auto redirect to register new admin.
And can't open http://localhost:1337/admin/plugins/users-permissions/auth/login

**Comment by lauriejim** [comment]
Please check opened issue. One already exist about this point.

**Comment by derrickmehaffy** [comment]
Related issue: https://github.com/strapi/strapi/issues/1254
