### ISSUE TITLE
Audio Files cannot be selected in Media Library

### ISSUE THREAD

**Issue by danielehrhardt** [strapi/strapi#12822]
### Describe the bug

Audio Files cannot be selected in Media Selector. 

### Steps to reproduce the behavior

1. Open Media Selector for File Field
2. Try to select a Audio File
3. The Checkbox is missing

### Expected behavior

There should be a checkbox to select the Audio File

### Screenshots

![image](https://user-images.githubusercontent.com/19570043/158018320-2aa4bb8e-6acc-4263-ac65-d9839bb47fae.png)

### Code snippets

-
### System

- Node.js version: 
- NPM version:
- Strapi version: v4.1.3
- Database: mySQL
- Operating system: Ubuntu

### Additional context

-

**Comment by gu-stav** [comment]
Thank you for the bugreport. I've double-checked it but unfortunately can't reproduce it. Can you confirm you enabled audio files on the media field? This can be done in `Content-Type-Builder > Field > Advanced Settings`. Please make sure "Audios" are selected there.

**Comment by danielehrhardt** [comment]
> Thank you for the bugreport. I've double-checked it but unfortunately can't reproduce it. Can you confirm you enabled audio files on the media field? This can be done in `Content-Type-Builder > Field > Advanced Settings`. Please make sure "Audios" are selected there.

![image](https://user-images.githubusercontent.com/19570043/158375885-9a32d50d-e2e5-4e93-bb8d-03836318a984.png)

Audio is not available

**Comment by gu-stav** [comment]
@danielehrhardt Do you mind sharing your dependencies in `package.json` with me?

**Comment by danielehrhardt** [comment]
> @danielehrhardt Do you mind sharing your dependencies in `package.json` with me?

```
{ "name": "i", "private": true, "version": "0.1.0", "description": "A Strapi application", "scripts": { "develop": "strapi develop", "start": "strapi start", "build": "strapi build", "strapi": "strapi" }, "dependencies": { "@sentry/node": "^6.18.2", "@sentry/tracing": "^6.18.2", "@strapi/plugin-documentation": "^4.1.3", "@strapi/plugin-i18n": "4.1.3", "@strapi/plugin-sentry": "^4.1.3", "@strapi/plugin-users-permissions": "4.1.3", "@strapi/strapi": "4.1.3", "dotenv": "^16.0.0", "mysql": "^2.18.1", "sqlite3": "^5.0.2", "strapi-plugin-config-sync": "^1.0.0-beta.8", "strapi-plugin-passwordless": "^4.0.5", "strapi-plugin-sentry": "^3.6.8" }, "author": { "name": "A Strapi developer" }, "strapi": { "uuid": "b62ff054-c713-4dfa-828a-5e5f63b3c0d4" }, "engines": { "node": ">=12.x.x <=16.x.x", "npm": ">=6.0.0" }, "license": "MIT"}
```

**Comment by gu-stav** [comment]
Mh, that looks good to me. Could you try to:

1. Delete `.cache` und `build` directories
2. Run `yarn build`

And see if this fixes your issue?

**Comment by danielehrhardt** [comment]
> Mh, that looks good to me. Could you try to:
> 
> 1. Delete `.cache` und `build` directories
> 2. Run `yarn build`
> 
> And see if this fixes your issue?

Thank you!
This worked.
