### ISSUE TITLE
Uploads not be replaced

### ISSUE THREAD

**Issue by danielehrhardt** [strapi/strapi#12824]
### Describe the bug

When a File is Uploaded to a Field in a Collection the first time the Upload does work. 
But if then a new File will be uploaded to the same Field the old File will stay.

### Steps to reproduce the behavior

Use the Documentation Provided here to upload a File.
https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider
Tested with Audio Files. 
Upload a File and then try to upload a different File. The first File uploaded will stay.

### Expected behavior

The File should be replaced in the Entry with the new File uploaded. 

### Screenshots

-

### Code snippets

[Documentation](https://docs.strapi.io/developer-docs/latest/plugins/upload.html#using-a-provider)

### System

- Node.js version: v16
- NPM version:
- Strapi version: v4.1.3
- Database: mySql
- Operating system: Ubuntu

### Additional context

-

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/13041

See this comment for my suggestion as it applies here too: https://github.com/strapi/strapi/issues/13041#issuecomment-1095496718
