### ISSUE TITLE
SVG width and height missing

### ISSUE THREAD

**Issue by Zharkan** [strapi/strapi#12823]
### SVG width and height missing when uploading

Strapi used to get width and height of uploaded svg, now it doesn't do it anymore.

### Steps to reproduce the behavior

1. Upload an svg
2. Check its dimensions
3. It's empty

### Expected behavior

Strapi should output width and height of svg
### System

- Node.js version: v14.19.0
- NPM version: 8.5.2
- Strapi version: v4.1.3
- Database: Postgre
- Operating system: Ubuntu 18.04

**Comment by quornik** [comment]
Same problem here. SVG upload was working flawlessly on strapi prior to 4.1, at some point and some update it started returning SVG's without dimensions.

**Comment by comalex** [comment]
facing the same issue, SVG height and weight is empty in 4.1.7

**Comment by lexa18** [comment]
facing the same issue, SVG height and weight is empty in 4.1.9.

**Comment by leo-diehl** [comment]
Same issue here

**Comment by troyere** [comment]
Same issue here

**Comment by ngladbach** [comment]
I have now encountered the bug as well in 4.1.6, 4.1.7 and 4.1.12

**Comment by petersg83** [comment]
It should be in the next patch release in 2 weeks :)
