### ISSUE TITLE
entityManager deleteMany fires afterDelete instead of afterDeleteMany 

### ISSUE THREAD

**Issue by pbvahlst** [strapi/strapi#12827]
### Describe the bug

entityManager `deleteMany()` fires `afterDelete` instead of `afterDeleteMany`. This can be verified on line 337 of https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/database/lib/entity-manager.js

### Steps to reproduce the behavior

1.subscribe to `beforeDeleteMany`,  `afterDelete` and `afterDeleteMany`
2. through the entityManager delete many entries
3. See that `beforeDeleteMany` and `afterDelete` AND NOT `afterDeleteMany` is fired

### Expected behavior
`beforeDeleteMany` should result in `afterDeleteMany` on succes and NOT `afterDelete`

### System

- Node.js version: v16
- NPM version: 8
- Strapi version: 4.13
- Database: mysql
- Operating system: windows

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by pbvahlst** [comment]
It should be updated now, sorry if it wasn't clear ebough

**Comment by pbvahlst** [comment]
It should be updated now, sorry if it wasn't clear enough

**Comment by JMartinCollins** [comment]
https://github.com/strapi/strapi/blob/698ae33e0007811ce24b568cc5d873d7a4d2a832/packages/core/database/lib/entity-manager.js#L339

This problem is still present in 4.1.11

**Comment by arpadgabor** [comment]
Apparently this has been fixed.

https://github.com/strapi/strapi/blob/master/packages/core/database/lib/entity-manager.js#L339

**Comment by derrickmehaffy** [comment]
Mmmmm the git blame shows that line was last modified 3 months ago: https://github.com/strapi/strapi/commit/7f0b35ebdbe9ee8f6b33a546ccbd639781c664c5 in v4.1.12.

I cannot reproduce in Strapi v4.2.3 so I'll set it as closed for now.
