### ISSUE TITLE
Deeply nested image components do not work. :bug: 

### ISSUE THREAD

**Issue by dogunbound** [strapi/strapi#12828]
### Describe the bug

Wrapping an image inside of a repeatable component, then inside of a dynamic zone causes problems. Whenever I try publishing then saving it, the image disappears on strapi's frontend. I took a look at the database and found the collection files_related_morphs and saw the relation of the image saved. I think this is a backend problem.

My reason for thinking the problem is a query problem with the backend portion of strapi is that when I query like so:

```
  const query = qs.stringify({
    filters:{
      id: {
        $eq: storyId,
      },
    },
    populate: {
      populate: '*',
      zone: {
        populate: '*',
      },
    },
  });

	useEffect(() => {
		if (loading) {
			axios.get(`${process.env.REACT_APP_strapiURL}/api/stories/?${query}`)
				.then((res) => {
// ... unrelated
```
zone being the dynamic zone, it fetches everything in the component other than the image. The same behavior is present in the strapi frontend.

### Steps to reproduce the behavior

1. Create component with an image inside of this component.
2. Create a component wrapping the step 1s component as a component (repeatable or not).
3. Create a dynamic zone which wraps step 2s component.
4. Try and save an image in step 1s component.
5. Page will refresh and thus disappear. 

### Expected behavior

When saving image, image shows up on the front end side of the back end.

### Screenshots

video on how the bug works: https://www.youtube.com/watch?v=hui7dBTX4i4

### Code snippets

N/A

### System

- Node.js version: v16
- NPM version: v8.3.1
- Strapi version: v4.1.3
- Database: Postgres
- Operating system: Linux

### Additional context

N/A

**Comment by c3s4** [comment]
I have a similar issue but in my case I have a relation to another content type element.
Same result for me: I save and relation disappears!

**Comment by BorysShulyak** [comment]
The same issue. And it is really important blocker (

**Comment by dogunbound** [comment]
> I have a similar issue but in my case I have a relation to another content type element. Same result for me: I save and relation disappears!

Should I relabel this as: some deeply nested components do not work?

**Comment by dogunbound** [comment]
Possible duplicate of: https://github.com/strapi/strapi/issues/5798

**Comment by dogunbound** [comment]
So I did a little more digging and found out that sqlite3 works find with strapi. Now I am 99% confident that the issue lies in how strapi queries the database for information.

**Comment by dogunbound** [comment]
As a side note, me, Daedalus, and derrick tried to fetch this deeply nested data from a working version of a similarly built strapi interface, and was unsuccessful to get the query to run. We tried:
```
const query = qs.stringify({
    filters:{
      id: {
        $eq: storyId,
      },
    },
    populate: ['*', 'zone.*', 'zone.frame3.*','zone.frame3.images.*']  
});
```

```
 populate: {
      populate: '*',
      zone: {
        frame3:{
           images :{
             populate :"*",
           }
        }
      },
    },
  });
```
and
```
  const query = qs.stringify({
    filters:{
      id: {
        $eq: storyId,
      },
    },
    populate: {
      populate: '*',
      zone: {
        populate: '*',
      },
    },
  });
```

None of them got the image to populate in the deeply nested component.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11955
