### ISSUE TITLE
Bootstrap invokes configuration 3 times which causes issues in certain container environments

### ISSUE THREAD

**Issue by jbool24** [strapi/strapi#12836]
### Describe the bug

Using Strapi v4.1.3 but noticed this in earlier versions including v3.
The bootstrap process invokes the configs at least 3 times.

### Steps to reproduce the behavior

1. Prepare a base Strapi project
2. Add a `console.log` statement inside the body of any `config/*.js` file
3. Run strapi dev or strapi build then run the code
4. You will see the log statement print 3 times.

### Expected behavior

Not sure if this is intended behavior for bootstrapping the application however this causes issues in completely containerized environments that connect to an elastic SQL service. The specific use case I have is with Google Cloud Run (strapi instance) and Google Cloud SQL ( managed Postgres ). The Run service is never able to start correctly because the connections do not establish properly due to the triple restart (or triple invocation of database code).

### Screenshots
You can see below my instance is logging an ENV var which will be present at runtime, but shows that `config/database.js` is invoked 3 times.
![Screenshot from 2022-03-14 11-22-50](https://user-images.githubusercontent.com/13041345/158204368-6d9f553d-3d9e-497b-bfa9-d19705bb5fa1.png)

In Cloud Run service the bootstrap completes and connects to the SQL server at least once but hangs because Run monitor cannot establish that the http socket is up and listening. The bootstrapping gets to here and then hangs and stalls after about 4 seconds since Cloud Run monitor is unable to make the healthcheck.
![Screenshot from 2022-03-14 11-32-21](https://user-images.githubusercontent.com/13041345/158206462-1ddba329-5479-45bd-92d0-3ba217514d33.png)

### Code snippets

```javascript
module.exports = ({ env }) => {
  let dbSettings = {};

  console.log('INSTANCE_CONNECTION_NAME: ', env('INSTANCE_CONNECTION_NAME'))

  if (env('NODE_ENV') === 'production' && env('INSTANCE_CONNECTION_NAME')) {
    const dbSocketPath = env('DB_SOCKET_PATH', '/cloudsql')
    const instanceName = env('INSTANCE_CONNECTION_NAME');
    console.log("Config DB Socket Path " + `${dbSocketPath}/${instanceName}`)
    // dbSettings['socketPath'] = `${dbSocketPath}/${instanceName}`
    dbSettings['host'] = `${dbSocketPath}/${instanceName}`
  } else {
    dbSettings['host'] = env('DATABASE_HOST', '127.0.0.1')
    dbSettings['port'] = env.int('DATABASE_PORT', 5432)
  }

  dbSettings['database'] = env('DATABASE_NAME')
  dbSettings['user'] = env('DATABASE_USERNAME')
  dbSettings['password'] = env('DATABASE_PASSWORD')
  // dbSettings['ssl'] = env.bool('DATABASE_SSL', false)

  if (env.bool('DEBUG')) console.log(dbSettings);

  return ({
    connection: {
      debug: env.bool('DEBUG_DB', false),
      client: 'postgres',
      connection: dbSettings,
    },
  });
}
```

### System

- Node.js version: v14.18.2
- NPM version: 8.2.0
- Strapi version: @strapi/strapi@4.1.3
- Database: Postgres v14
- Operating system: Linux

### Additional context

Launching the strapi instance inside a container with Google Cloud Run
Database hosted in Google Cloud SQL

**Comment by jbool24** [comment]
Found the solution to why Cloud Run did not complete the run. I had not forced the HTTP server to bind to `0.0.0.0` of the container so the default was binding to `127.0.0.1` which is unreachable outside the container. 

However still not sure if the three invocations of the config is intended behavior so I am going to leave this issue open for comment by the team.

**Comment by derrickmehaffy** [comment]
Can't reproduce in v4.1.7; bootstrap, register, and config files appear to only be loaded once:
![image](https://user-images.githubusercontent.com/8593673/162819664-d4afa1ef-78e4-49a4-b6ba-509d70e816fc.png)

**Comment by jbool24** [comment]
@derrickmehaffy You have put the `console.log` in the module global scope. Move it inside the exports closure and you will see the function is invoked 3 or more times. look at my example closely. I'm returning a config object not the object directly.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy You have put the `console.log` in the module global scope. Move it inside the exports closure and you will see the function is invoked 3 or more times. look at my example closely. I'm returning a config object not the object directly.
> 
> I have also upgraded to 4.1.7 since posting this and the behavior remains.

Ah yeah I see, I don't believe we can stop this since your basically exporting a function which is called at various levels. Especially for the DB
