### ISSUE TITLE
Can not Install Strapi Alpha on windows

### ISSUE THREAD

**Issue by dertuerke** [strapi/strapi#1283]
Informations

Node.js version: 8.11.2
npm version: 6.1.0
Operating system: Windows 10

Hi,

if i try to install strapi i get this error:
`npm ERR! Unexpected token < in JSON at position 0 while parsing near '<!DOCTYPE HTML PUBLI...'`

**Comment by damtsnkff** [comment]
@dertuerke node version should be >= 9.
https://strapi.io/documentation/getting-started/installation.html

**Comment by dertuerke** [comment]
@damtsnkff i try it with node-lts and with node 10.x. In both i get the same error.

**Comment by dertuerke** [comment]
So i found the error on my System.

My system probably does not like the package `koa-favicon 2.0.1`

**Comment by soupette** [comment]
@lauriejim @Aurelsicoko should we lock the `koa-favicon` version?

**Comment by dertuerke** [comment]
@soupette I withdraw my statement. It does not seem to matter.

**Comment by lauriejim** [comment]
@dertuerke We will be able to help you actually. 
Please use your mac 😄

**Comment by Aurelsicoko** [comment]
@soupette If the `koa-favicon@2.0.1` is the cause of the error, we should lock it to `2.0.0`.

**Comment by dertuerke** [comment]
I found the issue on my system.
The npm proxy was wrong.

After i change from `http://registry.npmjs.org/` to `https://registry.npmjs.org/`, it works 😄 

I do not know why the "HTTP" did not work. But with "HTTPS" it works.
I can imagine that it is the IT structure in our company.

I hope it helps others too.

**Comment by kevincam3** [comment]
So does this mean all developers on Windows can't use Starpi? I tried using the docker image but it doesn't work either. It looks promising but let me know if I need to look for something else if I don't have a mac

**Comment by derrickmehaffy** [comment]
@kevincam3 this is an old issue, Strapi does run (though maybe at a slighly more limited capacity) on windows, but you can easily setup WSL to work with strapi on Windows.

**Comment by kevincam3** [comment]
Got it thanks. Just saw tht WSL 2 is coming soon. I was able to get it working with Docker using MySQL so I'm good for now. Thanks for the quick reply.
