### ISSUE TITLE
Consistency in event parameter in lifecycles hooks

### ISSUE THREAD

**Issue by bidoubiwa** [strapi/strapi#12832]
### Please describe your feature request

I would like consistency in what the `result` field of the `event` parameter present in all `lifecycles` functions (such as `afterCreate`) contains.

### Why is it needed?

When one entry is being deleted, the `result` field contains the entry being deleted: 

`afterDelete` on one entry being deleted:

```js
  // ... other fields
  "params": {
    "where": {
      "id": 43
    }
  },
  "result": {
    "id": 43,
    "title": "my article 9933",
    "description": "my super article content",
    "createdAt": "2022-03-14T10:36:44.306Z",
    "updatedAt": "2022-03-14T10:36:44.306Z"
  }
```

Which makes it possible for me to fetch the `id` field doing `event.result.id` (that I need in order to sync with another database). 

At the other end, when I delete multiple entries, it does not trigger `afterDeleteMany`, it also trigger `afterDelete`. 
The problem is that in this case, the id's of the entries being deleted are very much nested and the `result` field does not contain the entries being deleted but the number of documents: 

`afterDelete` when multiple entries are being deleted:
```js
// .... other fields
 "params": {
    "where": {
      "$and": [
        {
          "id": {
            "$in": [
              44,
              42
            ]
          }
        }
      ]
    }
  },
  "result": {
    "count": 2
  }
```

Which, results in my code looking like this: 

```js
  let entriesId = []
  // Different ways of accessing the id's depending on the number of entries being deleted
  // In case of multiple deletes:
  if (
    params?.where?.$and &&
    params?.where?.$and[0] &&
    params?.where?.$and[0].id?.$in
  )
    entriesId = params?.where?.$and[0].id.$in
  // In case there is only one entry being deleted
  else entriesId = [result.id]
```

This is based on different ways I found to delete documents, I'm not sure I this works in all cases since it seems a bit hacky.

### Suggested solution(s)

I would have expected that `result` contains the entries, or a new field called `results`.

**Comment by Hobbenhopf** [comment]
I think the issue here is that the `strapi.db.query(...).deleteMany(...)` will trigger the `afterDelete` lifecycle instead of the `afterDeleteMany`.
We view this as a bug.

**Comment by derrickmehaffy** [comment]
> I think the issue here is that the `strapi.db.query(...).deleteMany(...)` will trigger the `afterDelete` lifecycle instead of the `afterDeleteMany`. We view this as a bug.

Generally yes but the `deleteMany` didn't exist in v3 and was only added in v4. The content-manager plugin is using old logic from v3 and was never migrated to use the deleteMany thus it's not really a bug and is an enhancement to change over to the new API

**Comment by bidoubiwa** [comment]
In `v3`  the lifecycle was `afterDelete` and returned an array or a simple object depending if it delete multiple entries or not. 

This was my code in v3:
```js
async function afterDelete(result, collection, connector) {
  try {
    let entriesId = []
    // works with both delete methods
    if (Array.isArray(result)) {
      entriesId = result.map(doc => doc.id)
    } else {
      entriesId = [result.id]
    }
    await connector.deleteEntriesFromMeiliSearch({ collection, entriesId })
  } catch (e) {
    console.error(e)
  }
}
```

In v4 it changed its usage to the following: https://github.com/meilisearch/strapi-plugin-meilisearch/blob/aad2a1e4802808e2b6e0a374fb746881ff4ee242/server/services/lifecycle/lifecycle.js#L64

I think that it is not using the old logic but that the logic changed?

**Comment by nitintecg** [comment]
@maccomaccomaccomacco is this fixed in new strapi release ?

**Comment by nitintecg** [comment]
is this issue is fixed in new strapi release ?
