### ISSUE TITLE
Cannot save a content with a relation

### ISSUE THREAD

**Issue by alexandremottet** [strapi/strapi#1284]
**Informations**
- **Node.js version**: 9.7.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: mongo
- **Operating system**: windows

**What is the current behavior?**
When you try to save a content which contain a relation field type you got the following error :
`this.updateRelations is not a function`
The value of the relation is not saved.

**Steps to reproduce the problem**
Follow the blog article : ~~https://blog.strapi.io/building-a-static-website-using-jekyll-and-strapi/~~
https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/
When you try to save the content you will get the error.

**What is the expected behavior?**
The value of the relation is saved with no error.

**Suggested solutions**
I have no clue, but I will be glad to help in the fix.

**Comment by lauriejim** [comment]
@alexandremottet Did you use this [Repo](https://github.com/strapi/strapi-examples/tree/master/jekyll-strapi-tutorial) or you follow the article with a fresh new Strapi app?

**Comment by alexandremottet** [comment]
I linked the wrong article (so sorry), I use this article with a fresh strapi app : https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/

**Comment by alexandremottet** [comment]
My bad, I just run `npm update -g strapi` and it works.

**Comment by weactivist** [comment]
I have the same issue. Built with docker-compose. The versions used are:

"strapi": "^3.0.0-alpha.12.2",
"strapi-mongoose": "3.0.0-alpha.12"

> version: "3"
> services:
>     node:
>         image: strapi/strapi
>         env_file: .env
>         ports:
>             - 1337:1337
>         depends_on:
>             - mongo
>         links:
>             - mongo
>         volumes:
>             - ./strapi-app:/usr/src/api/strapi-app
>             - /usr/src/api/strapi-app/node_modules
>     mongo:
>         image: mongo
>         env_file: .env
>         ports:
>             - 27017:27017
>         volumes:
>             - ./db/:/data/db
>         restart: always

**Comment by tguelcan** [comment]
same problem

**Comment by ashishgkwd** [comment]
I am also facing the same issue when using the docker repo: https://github.com/strapi/strapi-docker
Although, I am using the latest branch i.e. 3.0.0-alpha.12.2

**Comment by ashishgkwd** [comment]
Meanwhile, running `npm install strapi@alpha -g` installs `strapi@3.0.0-alpha.12.3` version and is running fine 👍
