### ISSUE TITLE
Marketplace CORS issue

### ISSUE THREAD

**Issue by SoftCreatR** [strapi/strapi#12858]
After updating to 4.1.5, where the Marketplace has been integrated into Strapi, it doesn't work due to CORS issues:

> Access to XMLHttpRequest at 'https://market-api.strapi.io/plugins' from origin 'https://my-api.tld' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:1337' that is not equal to the supplied origin.

**Comment by gu-stav** [comment]
Thank you for opening an issue so quickly. We are deploying a fix, which will be live soon. No update of Strapi should be needed, as this is on the marketplace side.

**Comment by alexandrebodin** [comment]
Hi @SoftCreatR This issue should be fixed now. Can you retry and close the issue if that's the case?

Thank you fro notifying us!

**Comment by SoftCreatR** [comment]
> Access to XMLHttpRequest at 'https://market-api.strapi.io/plugins' from origin 'https://my-api.tld' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by alexandrebodin** [comment]
Hum that's strange We explicitly set this header 🤔  can you try clearing your cache ?

**Comment by SoftCreatR** [comment]
> can you try clearing your cache ?

It's disabled by default ;)

Your APU clearly does not set that header:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: Cowboy
Cache-Control: max-age=21600
Date: Wed, 16 Mar 2022 11:36:40 GMT
Via: 1.1 vegur, 1.1 cb643617ee4bca09492409ac12401bfc.cloudfront.net (CloudFront)
Content-Encoding: br
Vary: Accept-Encoding
X-Cache: Hit from cloudfront
X-Amz-Cf-Pop: TXL50-P4
X-Amz-Cf-Id: 03t8RsraVaj3mmJRjBLMpj2dXymhzkZSro5Aheuf4tFZ4qdMLuEHxQ==
Age: 287
```

**Comment by alexandrebodin** [comment]
Well it depends who you are asking :D 
We are still investigating :)
![Screenshot 2022-03-16 at 12 44 33](https://user-images.githubusercontent.com/6065744/158582848-d59e3b3c-8921-4595-afe3-9429b33168a6.png)

**Comment by alexandrebodin** [comment]
I think we found the issue with our caching. I'll go ahead and close. Let us know if it comes back!
