### ISSUE TITLE
Custom error message not shown when using singleType in strapi/admin

### ISSUE THREAD

**Issue by Jose4gg** [strapi/strapi#12865]
### Describe the bug

When throwing custom errors on `single-types` form at the strapi admin, it displays the default error message: **Warning: Bad Request**.

### Steps to reproduce the behavior

1. Add this file at `src/extensions/content-manager/strapi-server.js` and start the server:
```
"use strict";
const { ForbiddenError } = require("@strapi/utils").errors;

module.exports = (plugin) => {
    const singleTypeController = plugin.controllers["single-types"];

    singleTypeController.createOrUpdate = function (ctx) {
        throw new ForbiddenError("Custom error");
    };

    return plugin;
};
```
2. If you don't have a single type created, go to **Content-Type Builder** and create a new single type.
3. Go to **Content Manager**
4. Click on any `Single Type` you have
5. Make any change and save it.

### Expected behavior
<img width="443" alt="image" src="https://user-images.githubusercontent.com/17036072/158680418-fc07d8ee-49b9-489d-8447-5a28c0a32078.png">

### Current behavior:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/17036072/158686862-d3b8386a-1dc6-4cab-b7e3-9c82083cb3ed.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.5
- Database: PostgreSQL
- Operating system: MacOSX

### Additional context

The file `/packages/core/admin/admin/src/content-manager/components/SingleTypeFormWrapper/index.js` it has the bug at displayErrors function. The `errorPayload` must be obtained from `err.response.data` instead of `err.response.payload` at line `146`.

**Comment by derrickmehaffy** [comment]
fixed in https://github.com/strapi/strapi/pull/12632
