### ISSUE TITLE
Clean install of Strapi on GCP return Admin page with no content and "Cannot read properties of undefined (reading 'toggleNotification')"

### ISSUE THREAD

**Issue by adamk72** [strapi/strapi#12869]
### Steps to reproduce the behavior

1. On a local machine, install Strapi via the instruction listed here: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html. 
2. Per those instructions follow through with `gcloud app deploy app.yaml --project <gcp_project_name>`.
3. After it completes deployment, visit the website via `gcloud app browse'.
4. Open the administration panel and login (once you've signed up, a normal login page will show).
5. See that the `/admin` link is a blank page and dev tool reports back two similar errors, starting with `Uncaught TypeError: Cannot read properties of undefined (reading 'toggleNotification')`

### Expected behavior

The admin page should be full of content.

### Screenshots
![Screen Shot 2022-03-17 at 00 37 07](https://user-images.githubusercontent.com/62404383/158744071-b29447b5-d2d8-46ef-866e-b2ba95d6ec73.png)

### System

- Node.js version: I have tried this with both 14 and 16
- NPM version: 8
- Strapi version: 4.1.5, 4.1.2, and 3.8.6
- Database: Postgres
- Operating system: GCP

### Additional context

Used `yarn` for package management.

There is a closed issue here https://github.com/strapi/strapi/issues/12013 with recent activity from users, but seems to have not been viewed recently by the Strapi team as far as I can tell, with versions displaying similar symptoms as far back v4.0.2.

Thanks for your time and attention.

**Comment by adamk72** [comment]
Update: I got this to successful run by switching from `yarn` to `npm`. 

`yarn` is our preferred way of doing builds, so I would still consider this a bug.

**Comment by crissCM** [comment]
I had the same problem. I switched to npm and tried with the following config but got another error:
Strapi version: 4.2.0-beta.0
node: 16.13.2
npm: 8.1.2

![image](https://user-images.githubusercontent.com/78145538/158791357-efb70e51-73da-4d20-b8e1-6f2ce6a4b722.png)

**Comment by MaxBQ** [comment]
I had this problem too when I updated the belt to 4.1.5

The solution to this problem for me was to roll back all dependencies to version 4.0.5 and everything was fine.

**Comment by rasmus-rudling** [comment]
Is there a fix for this yet? Have tried everything and still getting the same error. Tried with npm as well, but it didn't work, and I don't really understand what would be the difference from yarn since the error is in production?

**Comment by rideddy84** [comment]
@rasmus-rudling You have to insert `yarn.lock` line into `.gcloudignore` file. Then Google App Engine uses NPM for package download.

**Comment by rideddy84** [comment]
@crissCM Undefined of `isSubmitting` can occur when there is `strapi-helper-plugin` in the dependencies property of the `package.json`. For version 4.x `strapi-helper-plugin` is not required. Just use `@strapi/helper-plugin`.
```
import { request } from '@strapi/helper-plugin';
```

**Comment by rasmus-rudling** [comment]
THANK YOU @rideddy84 adding `yarn.lock` to `.gcloudignore` was the only missing piece!

**Comment by rasmus-rudling** [comment]
I added a PR [here](https://github.com/strapi/documentation/pull/821) that adds your suggestion to the guide!

**Comment by vripoche** [comment]
Hello,

I have this `isSubmitting` of `undefined` error with the last `4.1.7` version (I moved from `4.1.5` one) in setting:
http://localhost:1337/admin/settings/users-permissions/advanced-settings

Only `@strapi/helper-plugin` (not `strapi-helper-plugin`) is used for its `useCMEditViewDataManager` hook to manage preview links in admin panel.

**Comment by derrickmehaffy** [comment]
I'll go ahead and set this issue as closed due to the documentation PR that @rasmus-rudling mentioned being merged. Thanks :)

**Comment by aquadesk** [comment]
I built with `npm` and try to empty `.cache` and `build` and `node_modules` 

after building

I still get the errors.

I checked `package-lock.json` to see if I somehow depend on react18 but there is no react18 installed.



```
react_devtools_backend.js:3973 TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.841c3036.js:2:2286114)
    at d (main.841c3036.js:2:2133832)
    at li (main.841c3036.js:2:1623885)
    at Vu (main.841c3036.js:2:1676182)
    at Cl (main.841c3036.js:2:1663423)
    at Pl (main.841c3036.js:2:1663351)
    at Sl (main.841c3036.js:2:1663214)
    at xl (main.841c3036.js:2:1660180)
    at main.841c3036.js:2:1609677
    at t.unstable_runWithPriority (main.841c3036.js:2:3408535)
overrideMethod @ react_devtools_backend.js:3973
fu @ main.841c3036.js:2
n.payload @ main.841c3036.js:2
va @ main.841c3036.js:2
Qi @ main.841c3036.js:2
Vu @ main.841c3036.js:2
Cl @ main.841c3036.js:2
Pl @ main.841c3036.js:2
Sl @ main.841c3036.js:2
xl @ main.841c3036.js:2
(anonymous) @ main.841c3036.js:2
t.unstable_runWithPriority @ main.841c3036.js:2
Go @ main.841c3036.js:2
Xo @ main.841c3036.js:2
Ko @ main.841c3036.js:2
ql @ main.841c3036.js:2
t.unstable_runWithPriority @ main.841c3036.js:2
Go @ main.841c3036.js:2
Nl @ main.841c3036.js:2
(anonymous) @ main.841c3036.js:2
F @ main.841c3036.js:2
w.port1.onmessage @ main.841c3036.js:2
react_devtools_backend.js:3973 Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (1340.881bca16.chunk.js:2:1497058)
    at $i (main.841c3036.js:2:1636516)
    at Qi (main.841c3036.js:2:1636313)
    at Vu (main.841c3036.js:2:1677255)
    at Cl (main.841c3036.js:2:1663423)
    at Pl (main.841c3036.js:2:1663351)
    at Sl (main.841c3036.js:2:1663214)
    at xl (main.841c3036.js:2:1660180)
    at main.841c3036.js:2:1609677
    at t.unstable_runWithPriority (main.841c3036.js:2:3408535)
overrideMethod @ react_devtools_backend.js:3973
fu @ main.841c3036.js:2
n.callback @ main.841c3036.js:2
ga @ main.841c3036.js:2
bu @ main.841c3036.js:2
Rl @ main.841c3036.js:2
t.unstable_runWithPriority @ main.841c3036.js:2
Go @ main.841c3036.js:2
Dl @ main.841c3036.js:2
xl @ main.841c3036.js:2
(anonymous) @ main.841c3036.js:2
t.unstable_runWithPriority @ main.841c3036.js:2
Go @ main.841c3036.js:2
Xo @ main.841c3036.js:2
Ko @ main.841c3036.js:2
ql @ main.841c3036.js:2
t.unstable_runWithPriority @ main.841c3036.js:2
Go @ main.841c3036.js:2
Nl @ main.841c3036.js:2
(anonymous) @ main.841c3036.js:2
F @ main.841c3036.js:2
w.port1.onmessage @ main.841c3036.js:2
main.841c3036.js:2 Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (1340.881bca16.chunk.js:2:1497058)
    at $i (main.841c3036.js:2:1636516)
    at Qi (main.841c3036.js:2:1636313)
    at Vu (main.841c3036.js:2:1677255)
    at Cl (main.841c3036.js:2:1663423)
    at Pl (main.841c3036.js:2:1663351)
    at Sl (main.841c3036.js:2:1663214)
    at xl (main.841c3036.js:2:1660180)
    at main.841c3036.js:2:1609677
    at t.unstable_runWithPriority (main.841c3036.js:2:3408535)
```

**Comment by evle** [comment]
same error here and my version is **4.1.7**
use yarn and npm both not working, still got the error:
**TypeError: Cannot read properties of undefined (reading 'toggleNotification')**

**Comment by cur1ou5soul** [comment]
also on 4.1.7 I got the same error - switched back and forth on yarn and npm but somehow it never worked.
