### ISSUE TITLE
[V4] On Delete Cascade Database Constraint 

### ISSUE THREAD

**Issue by 3akram** [strapi/strapi#12874]
### Summary

When using a `SQL` Database i see it very necessary to have the option to add the `ON DELETE CASCADE` when creating an entity relation with another entity

### Why is it needed?

Going to solve tonz of orfen data issues in the database. Imagine that i want to delete a user or allow the user to delete his profile on my system and the `User` model has a relation with a lot of resources - also resources has relations between each others - something like `User` has a relation with `Article` and the `Article` has many `Images` Also the `User` has many `Payrolls` which i want to keep so i won't add the on delete cascade on this relation. So, what i might find helpful is at least allow the `ON DELETE CASCADE` on the `One To Many` relations. i know that this feature has a lot of edge cases that needs to be handled but it will solve a lot of performance issues and database leake.

### Suggested solution(s)

Add/Specify that i want to add `ON DELETE CASCADE` - Optional field when creating a one to many relation from resource to another resource.

**Comment by derrickmehaffy** [comment]
duplicate: https://feedback.strapi.io/feature-requests/p/allow-customization-of-foreign-keys-for-options-like-cascade-delete
