### ISSUE TITLE
Can't create a field named ID in a component

### ISSUE THREAD

**Issue by bfiaut** [strapi/strapi#12876]
## Bug report

When creating a component, if I name a field `ID`, it makes the application crash.

In the logs of the application, I have : 

```
[2022-03-17 12:40:33.662] error: create table `components_shared_videos` (`id` integer not null primary key autoincrement, `name` varchar(255) null, `id` varchar(255) null) - SQLITE_ERROR: duplicate column name: id
Error: create table `components_shared_videos` (`id` integer not null primary key autoincrement, `name` varchar(255) null, `id` varchar(255) null) - SQLITE_ERROR: duplicate column name: id
```

### Steps to reproduce the behavior

1. Create a new component
2. Add a text field
3. Name the filed "ID"
4. The app crashes

### Expected behaviour

Prevent the user from creating a field named "ID" in every component / single type / collection.

### System

- Node.js version: v16.14.1
- NPM version: 6.14.15
- Strapi version: 4.1.5
- Database: SQLite

**Comment by RaimonxDev** [comment]
Strapi adds the ID field automatically for each new entity. If you want to use your own ID it seems to me that it cannot be modified (it is what the DUPLICATE error shows in the console) you can use another name with the UID field type.

**Comment by Badestrand** [comment]
I am having the same issue and can't even start my strapi instance anymore, `yarn develop` simply quits with an error immediately:

```
create table `collections` (`id` integer not null primary key autoincrement, `name` varchar(255) null, `besitzer` varchar(255) null, `id` varchar(255) null, `created_at` datetime null, `updated_at` datetime null, `published_at` datetime null, `created_by_id` integer null, `updated_by_id` integer null, constraint `collections_created_by_id_fk` foreign key(`created_by_id`) references `admin_users`(`id`) on delete SET NULL, constraint `collections_updated_by_id_fk` foreign key(`updated_by_id`) references `admin_users`(`id`) on delete SET NULL) - SQLITE_ERROR: duplicate column name: id
```

All I did was add an "id" field to a collection type.

**Comment by bfiaut** [comment]
@Badestrand you must update the JSON file directly in your app sources and remove the ID attribute on the element you've put it on.

**Comment by derrickmehaffy** [comment]
Duplicate to: https://github.com/strapi/strapi/issues/1198

As others have said, ID is a protected name and cannot be reused. We should throw a proper Error here and the Content-Type builder shouldn't allow for this. If you are storing metadata you should use something like videoID or youtubeID.

**Comment by ccoenen** [comment]
To this day, Strapi breaks when you add a field called `ID`. It is ridiculous that there is not even a warning.
