### ISSUE TITLE
Shortcodes like feature 

### ISSUE THREAD

**Issue by davidjeba** [strapi/strapi#12870]
Wordpress has this very slick feature called "shortcodes"
strapi needs something like that to call widget anywhere {inside the domain, outside the domain}
embeddable widgets anywhere...

**Comment by maxpropp** [comment]
This is not a bug, maybe you should move this to the forum?

**Comment by davidjeba** [comment]
unable to move this into feature request

**Comment by derrickmehaffy** [comment]
Please submit all feature requests to our new roadmap website: https://feedback.strapi.io/
