### ISSUE TITLE
CSP violation in marketplace

### ISSUE THREAD

**Issue by atouchsimo** [strapi/strapi#12886]
### Describe the bug

Plugins images are not loading in market place due to CSP violation

### Screenshots

![Drag Racing](https://i.imgur.com/ZzBg7nD.png)

### System

- Node.js version: 14.17.6
- NPM version: 6.14.15
- Strapi version: 4.1.5

**Comment by atouchsimo** [comment]
@markkaylor yeap it was a cache issue, they are loading now 👍🏻

**Comment by ChristherLenander** [comment]
Clearing the Cache folder didn't work for me. I use the strapi-provider-upload-dos for digital ocean.

**Comment by markkaylor** [comment]
@ChristherLenander do you have an error in the console you could share? Did you also clear your browser cache?

**Comment by ChristherLenander** [comment]
![image](https://user-images.githubusercontent.com/49711748/159444805-c8fffd4e-0846-40ed-ace6-f5e88442434d.png)

Yes I cleard both Strapi cache and browser cache.

**Comment by twoabd** [comment]
Add dl.airtable.com to CSP Directive in /config/middlewares.js

```
module.exports = [
  "strapi::errors",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "storage.googleapis.com",
            "dl.airtable.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "storage.googleapis.com",
            "dl.airtable.com",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];
```
