### ISSUE TITLE
Graphql subscription

### ISSUE THREAD

**Issue by evilrat** [strapi/strapi#12880]
Ple add graphql subscription support....it is very much required

**Comment by timbrandin** [comment]
This is already a feature request: https://portal.productboard.com/strapi/1-roadmap/c/45-graphql-subscriptions

**Comment by derrickmehaffy** [comment]
Duplicate: https://feedback.strapi.io/developer-experience/p/graphql-subscriptions

**Comment by alexander-mart** [comment]
> This is already a feature request: https://portal.productboard.com/strapi/1-roadmap/c/45-graphql-subscriptions

404 — Oopsie, portal not found
