### ISSUE TITLE
Media upload type limitation going to a blank page

### ISSUE THREAD

**Issue by maxpropp** [strapi/strapi#12897]
### Describe the bug

When you define a content type to have media of a specific type and upload one of the "not allowed" types, the page goes blank.

I was uploading an image into a media that I set it up so that it only allows files and not images/videos, so it was doing this weird behavior. It does not actually block me from uploading, but it goes blank after uploading (it still uploads successfuly). I think it should somehow send an error and not send the user to a blank page though.

I did not test doing it the other way around though.

### Steps to reproduce the behavior

1. Limit media to only files.
2. Upload an image instead of a file.
3. See it go blank.
4. Check the file, it is uploaded succesfuly

### Expected behavior

Element should not be uploaded. Maybe a warning about the type being uploaded

### System

- Node.js version: 16.3.0
- NPM version: 7.15.1
- Strapi version: 4.1.3
- Database: MySQL
- Operating system: Windows 10

**Comment by DevJuliox** [comment]
Can someone help me with this, it's happening to me as soon as I click on upload image, Thanks

**Comment by maxpropp** [comment]
> Can someone help me with this, it's happening to me as soon as I click on upload image, Thanks

Hey, can you please explain your issue and what you are trying to achieve?

I did not fix my problem, I just don't upload the wrong file type.

**Comment by mehrad-meraji** [comment]
having the same issue here, the files get uploaded and are visible in the database-- also the entries get created but (the images) don't actually appear on the entry. **Also the Media Library breaks the entire dashboard and just shows a blank screen**

```javascript
await Promise.all(initial_categories.map(async (cat) => {
    const { image, banner_image, ...category} = cat;
    const entry = strapi.entityService.create('api::category.category', {
      data: {
        ...category,
      },
    });
    const files = {
      image: {
        path: 'database/assets/categories/' + image,
        name: image,
        alternative_text: image,
        caption: image,
        mime: mime.lookup('database/assets/categories/' + image)
      },
      banner_image: {
        path: 'database/assets/categories/' + banner_image,
        name: banner_image,
        alternative_text: banner_image,
        caption: banner_image,
        mime: mime.lookup('database/assets/categories/' + banner_image)
      }
    };
    return await strapi.entityService.uploadFiles('api::category.category', entry, files);
  }))
```

**Comment by gu-stav** [comment]
@mehrad-meraji Thanks for adding this use case. Could you give https://github.com/strapi/strapi/pull/12881 a try and see if it solves your problem?

**Comment by mehrad-meraji** [comment]
@gu-stav thank you! i updated in the other issue but repeating here for posterity

I used type instead of mime and everything works like a charm!
I assumed that the column name of mime is the same as the property passed to the upload method

Thank you for all your help
