### ISSUE TITLE
[4.2 beta] - Can't overwrite the theme colors

### ISSUE THREAD

**Issue by boazpoolman** [strapi/strapi#12896]
### Describe the bug

When using the `4.2.0-beta.0` with typescript I can't seem to overwrite the theme in the `src/admin/app.js` file.

### Steps to reproduce the behavior

1. `npx create-strapi-app@beta test-app-beta --ts` use quickstart method
2. `cd test-app-beta`
3. `yarn add strapi-code-themes`
4. Create file `src/admin/app.js` or `src/admin/app.ts` doesn't really matter.
5. Fill the file with this contents:

```
import { shadesOfPurple } from 'strapi-code-themes';

export default {
  config: {
    theme: {
      colors: shadesOfPurple,
    },
  },
};
```

### Expected behavior

Expected the theme to be overwritten with the colors from `strapi-code-themes`.

### System

- Node.js version: v14.19.0
- Strapi version: 4.2.0-beta.0
- Database: sqlite
- Operating system: Mac OS (M1)

### Additional context

When I do an non-typescript install of the beta this issue does not happen and the theme can be overwritten.

**Comment by derrickmehaffy** [comment]
should be fixed in https://github.com/strapi/strapi/pull/12912
