### ISSUE TITLE
Unique field option in enumeration field

### ISSUE THREAD

**Issue by Dinesh-m4** [strapi/strapi#12891]
Hello

In strapi documentation there is unique filed option for enumeration field

![Screenshot from 2022-03-21 12-02-28](https://user-images.githubusercontent.com/90827714/159214495-d8e7f249-b2f8-4cfb-b2be-3e87b1b7cc5c.png)

But unable to find it while adding enum field through content type builder 

![Screenshot from 2022-03-21 12-04-52](https://user-images.githubusercontent.com/90827714/159214639-e4a42700-9627-4747-ab1c-71c623b4addb.png)

How to unique filed for enum. 

Thank you ;)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
