### ISSUE TITLE
Plugin development guide doesn't work as expected

### ISSUE THREAD

**Issue by minvedacat** [strapi/strapi#1289]
**Informations**
- **Node.js version**:9.11.1/10.2.1
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.2
- **Database**:mongodb v3.6.5
- **Operating system**: Mac OS X 10.13.4

**What is the current behavior?**
It failed to `npm start` under `admin` folder during [plugin development guide](https://strapi.io/documentation/plugin-development/quick-start.html#plugin-development-setup)
Here is the log:
```
➜ npm start

> strapi-admin@3.0.0-alpha.12.2 prestart /Users/zm/.nvm/versions/node/v9.11.1/lib/node_modules/strapi/node_modules/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/Users/zm/.nvm/versions/node/v9.11.1/lib/node_modules/strapi/node_modules/strapi-admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.2 prestart: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.2 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Steps to reproduce the problem**
1. Follow [plugin development guide](https://strapi.io/documentation/plugin-development/quick-start.html#plugin-development-setup)
2. During `To generate a new plugin` step 4, `npm start` will fail

**What is the expected behavior?**
A admin server should be brought up and available at http://localhost:4000/admin

**Suggested solutions**
After manually install `strapi-helper-plugin`, a `loadAdminConfigurations.js not found` error appeared. The current installed version by default is `strapi-helper-plugin@3.0.0-debugalpha.4.1` which has no `loadAdminConfiguration.js`
With `npm install -g strapi-helper-plugin@3.0.0-alpha.12.2` then run `npm link strapi-helper-plugin` in *[project_folder]/admin* will help `npm start` find the currently script but with following warning:
```
➜ npm start

> strapi-admin@3.0.0-alpha.12.2 prestart /Users/zm/Documents/GitHub/strapi/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

(node:42542) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'routes' of undefined
    at _.forEach (/Users/zm/Documents/GitHub/strapi/packages/strapi-plugin-users-permissions/middlewares/users-permissions/index.js:25:35)
    at /Users/zm/Documents/GitHub/strapi/packages/strapi-plugin-users-permissions/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/zm/Documents/GitHub/strapi/packages/strapi-plugin-users-permissions/node_modules/lodash/lodash.js:3010:24)
    at /Users/zm/Documents/GitHub/strapi/packages/strapi-plugin-users-permissions/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Users/zm/Documents/GitHub/strapi/packages/strapi-plugin-users-permissions/node_modules/lodash/lodash.js:9342:14)
    at Object.initialize (/Users/zm/Documents/GitHub/strapi/packages/strapi-plugin-users-permissions/middlewares/users-permissions/index.js:24:11)
    at /Users/zm/Documents/GitHub/strapi/packages/strapi/lib/middlewares/index.js:30:23
    at Promise (/Users/zm/Documents/GitHub/strapi/packages/strapi/lib/middlewares/index.js:130:43)
    at new Promise (<anonymous>)
    at Promise.all.Object.keys.map.middleware (/Users/zm/Documents/GitHub/strapi/packages/strapi/lib/middlewares/index.js:70:9)
    at Array.map (<anonymous>)
    at Strapi.module.exports (/Users/zm/Documents/GitHub/strapi/packages/strapi/lib/middlewares/index.js:68:34)
(node:42542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:42542) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> strapi-admin@3.0.0-alpha.12.2 start /Users/zm/Documents/GitHub/strapi/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server


Strapi plugin succesfully started in development mode. ✓

-----------------------------------
Access URL: http://localhost:4000/admin
-----------------------------------
Press CTRL-C to stop
```

**Comment by minvedacat** [comment]
@soupette the commands worked for me either.
So that was my mistake. I thought [Develpoment Environment Setup](https://strapi.io/documentation/plugin-development/quick-start.html#development-environment-setup) is not required for plugin development.

**Comment by soupette** [comment]
Ok good news! 
I'm closing the issue

**Comment by BroTrue** [comment]
I try to follow this instuction but got this error

```
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

E:\Work\strapi_dev\strapi\packages\strapi-helper-plugin\node_modules\.bin\cross-env:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.2 prestart: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.2 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by derrickmehaffy** [comment]
Windows support is meh right now, as with many other issues listed here in the git repo. I would suggest either use WSL (Ubuntu) or doing your development in a virtual machine if your on windows

WSL Guide: http://wsl-guide.org/en/latest/

**Comment by BroTrue** [comment]
owww thanks , well I got ubuntu also. I will try it :)

**Comment by derrickmehaffy** [comment]
@BroTrue ^^

Also the Strapi team are aware of the issues when doing development on windows hence their note in the roadmap: https://github.com/strapi/strapi/projects/1

**Comment by BroTrue** [comment]
Well for big projects anyway is needed linux/macos... windows is too...
From the road map I wait for this feature 

"Plugin - Content Internalization
Translate the content of your API in any language, from the admin panel."

Or i will try to do by myself... we will see.
thank you for quick reply!

**Comment by derrickmehaffy** [comment]
Thats what I'm here for, to try and answer the basic questions while the Strapi team focuses on bug fixes and feature updates 😛

**Comment by BroTrue** [comment]
All is working well, i got small question. After all of this, dist "strapi" (that contains files from fork rep) is need or I can delete it ? =)

**Comment by piyushchauhan2011** [comment]
> Hi @minvedacat, I'm unable to reproduce your issue but can you try by running the following?
> 
> ```
> // Clone the repository with your fork
> $ mkdir repositories && git clone STRAPI_FORK
> $ cd strapi && npm run setup
> 
> // Create an app in another folder
> $ mkdir sandbox && cd sandbox
> $ strapi new my-app --dev
> // Remove the analytics plugin
> $ cd my-app && rm -rf plugins/analytics
> // Create a plugin
> $ strapi generate:plugin my-plugin
> // Link the `strapi-helper-plugin`
> $ cd plugins/my-plugin && npm link strapi-helper-plugin && cd ...
> // Start the strapi server
> $ strapi start
> // In another terminal window
> $ cd my-app/admin && npm start
> ```
> I just tried the commands above and it worked for me

I ended up using these commands and it worked for me too. I think, plugin development documentation is missing straight forward steps for doing plugin development, can be documented there too 👍 @soupette
