### ISSUE TITLE
[v4] How can I use database transactions in my customize api? It appears that this feature is not supported in version 4.0

### ISSUE THREAD

**Issue by xhxuhuan** [strapi/strapi#12905]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Quick summary what's this feature request about.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11792
