### ISSUE TITLE
Problem with application errors on external login providers

### ISSUE THREAD

**Issue by sebrojas14** [strapi/strapi#12907]
### Describe the bug

Not clear error when email is already taken by another login provider.

`{status: 400, name: "ApplicationError", message: "An application error occured", details: {}}`

### Steps to reproduce the behavior

Just login with Google with an already locally registered email.

### Expected behavior

Should inform that the email is already taken

### Screenshots

No need.

### Code snippets

No need.

### System

- Node.js version: v16
- Strapi version: 4.1.5

**Comment by sebrojas14** [comment]
This is caused by a problem in user-permissions plugin code.

https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js:76
connect method:
`if (_.isEmpty(user) && !advanced.allow_register) {
            return resolve([
              null,
              [{ messages: [{ id: "Auth.advanced.allow_register" }] }],
              "Register action is actually not available.",
            ]);
          }`

https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/controllers/auth.js:103
callback method:
`// Connect the user with the third-party provider.
      let user;
      let error;
      try {
        [user, error] = await getService('providers').connect(provider, ctx.query);
      } catch ([user, error]) {
        throw new ApplicationError(error.message);
      }

      if (!user) {
        throw new ApplicationError(error.message);
      }`

As you can see, `callback` method is expecting a value in `error.message` that is not provided by `connect`

**Comment by byoungd** [comment]
Any solution for this, I got the same issue with Github provider.

And the error info is blew:
```
 error: {
    status: 400,
    name: 'ApplicationError',
    message: 'An application error occured',
    details: {}
  }

```

**Comment by sebrojas14** [comment]
I had to add a strapi-server.js file in `src/extensions/users-permissions` and override al code.

**Comment by byoungd** [comment]
> Hey @[byoungd](https://github.com/byoungd), I had to add a `strapi-server.js` file in `src/extensions/users-permissions` and override al code.

Cound you provide the file (or code), I'm still struggling with this.

**Comment by byoungd** [comment]
> Hey @[byoungd](https://github.com/byoungd), I had to add a `strapi-server.js` file in `src/extensions/users-permissions` and override al code.

I'm still waiting for your solution.

**Comment by rossanmol** [comment]
Can replicate the problem.

**Comment by sebrojas14** [comment]
[byoungd](https://github.com/byoungd) Maybe tomorrow U can elaborate here.

**Comment by byoungd** [comment]
Thanks man！





------------------ Original ------------------
From: Sebastián Rojas Ricaurte ***@***.***&gt;
Date: Sat,Mar 26,2022 10:39 AM
To: strapi/strapi ***@***.***&gt;
Cc: han ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [strapi/strapi] Problem with application errors on external login providers (Issue #12907)





 
byoungd Maybe tomorrow U can elaborate here.

**Comment by derrickmehaffy** [comment]
Can't reproduce with v4.1.5, need more information.

**Comment by sebrojas14** [comment]
> Can't reproduce with v4.1.5, need more information.

What did you do? I Think is very clear the issue. Please cretae an user with local provider. Then, try to create an user with the same email bit with Google login provider for example. Api will return "An application error occured" instead of a clear error.

**Comment by sebrojas14** [comment]
[byoungd](https://github.com/byoungd), this is the workaround:

`src\extensions\users-permissions\strapi-server.js`:
```
"use strict";

require("dotenv").config();
const _ = require("lodash");
const jwt = require("jsonwebtoken");
const utils = require("@strapi/utils");
const { getService } = require("@strapi/plugin-users-permissions/server/utils");
const {
  validateCallbackBody,
} = require("@strapi/plugin-users-permissions/server/controllers/validation/auth");
const { sanitize } = utils;
const { ApplicationError, ValidationError } = utils.errors;
const sanitizeUser = (user, ctx) => {
  const { auth } = ctx.state;
  const userSchema = strapi.getModel("plugin::users-permissions.user");

  return sanitize.contentAPI.output(user, userSchema, { auth });
};

const emailRegExp =
  /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

module.exports = (plugin) => {
  // lazy load heavy dependencies
  const providerRequest = require("./services/providers-list");
  /**
   * Copy of getProfile method from https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js#L24
   * @param {String}   provider
   * @param {Function} callback
   */
  const getProfile = async (provider, query, callback) => {
    const access_token = query.access_token || query.code || query.oauth_token;

    const providers = await strapi
      .store({ type: "plugin", name: "users-permissions", key: "grant" })
      .get();

    await providerRequest({
      provider,
      query,
      callback,
      access_token,
      providers,
    });
  };

  /**
   * Rewrite of connect method.
   * OVERRIDE: https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js#L44
   * @param {*} provider
   * @param {*} query
   * @returns
   */
  const connect = async (provider, query) => {
    const access_token = query.access_token || query.code || query.oauth_token;

    return new Promise((resolve, reject) => {
      if (!access_token) {
        return reject([null, { message: "No access_token." }]);
      }

      // Get the profile.
      getProfile(provider, query, async (err, profile) => {
        if (err) {
          return reject([null, err]);
        }

        const email = _.toLower(profile.email);

        // We need at least the mail.
        if (!email) {
          return reject([null, { message: "Email was not available." }]);
        }

        try {
          // OVERRIDE: instead of find many with email, we assume that  theres only one account per email and look for the user with the email so we can login with multiple providers
          const users = await strapi.query('plugin::users-permissions.user').findMany({
            where: { email },
          });

          const advanced = await strapi
            .store({
              type: "plugin",
              name: "users-permissions",
              key: "advanced",
            })
            .get();

          const user = _.find(users, { provider });

          if (_.isEmpty(user) && !advanced.allow_register) {
           // OVERRIDE: change error object
            return resolve([
              null,
              // [{ messages: [{ id: "Auth.advanced.allow_register" }] }],
              { message: "Register action is actually not available." },
            ]);
          }

          if (!_.isEmpty(user)) {
            return resolve([user, null]);
          }

           if (
             !_.isEmpty(_.find(users, (user) => user.provider !== provider)) &&
             advanced.unique_email
           ) {
           // OVERRIDE: change error object
             return resolve([
               null,
               { message: "Email is already taken." },
             ]);
          }

          // Retrieve default role.
          const defaultRole = await strapi
            .query("plugin::users-permissions.role")
            .findOne({ where: { type: advanced.default_role } });

          // Create the new user.
          const params = {
            ...profile,
            email, // overwrite with lowercased email
            provider,
            role: defaultRole.id,
            confirmed: true,
          };

          const createdUser = await strapi
            .query("plugin::users-permissions.user")
            .create({ data: params });

          return resolve([createdUser, null]);
        } catch (err) {
          reject([null, err]);
        }
      });
    });
  };

  /**
   * Rewrite of callback method.
   * OVERRIDE: https://github.com/strapi/strapi/blob/master/packages/core/content-manager/server/controllers/collection-types.js
   * IMPORTANT: this should be reviewd and updated in Strapi version bumps.
   * Added lines are marked with comments starting with OVERRIDE
   * @param {*} ctx
   * @returns
   */
  plugin.controllers["auth"].callback = async (ctx) => {
    const provider = ctx.params.provider || "local";
    const params = ctx.request.body;

    const store = await strapi.store({
      type: "plugin",
      name: "users-permissions",
    });

    if (provider === "local") {
      if (!_.get(await store.get({ key: "grant" }), "email.enabled")) {
        throw new ApplicationError("This provider is disabled");
      }

      await validateCallbackBody(params);

      const query = { provider };

      // Check if the provided identifier is an email or not.
      const isEmail = emailRegExp.test(params.identifier);

      // Set the identifier to the appropriate query field.
      if (isEmail) {
        query.email = params.identifier.toLowerCase();
      } else {
        query.username = params.identifier;
      }

      // Check if the user exists.
      const user = await strapi
        .query("plugin::users-permissions.user")
        .findOne({ where: query });

      if (!user) {
        throw new ValidationError("Invalid identifier or password");
      }

      if (
        _.get(await store.get({ key: "advanced" }), "email_confirmation") &&
        user.confirmed !== true
      ) {
        throw new ApplicationError("Your account email is not confirmed");
      }

      if (user.blocked === true) {
        throw new ApplicationError(
          "Your account has been blocked by an administrator"
        );
      }

      // The user never authenticated with the `local` provider.
      if (!user.password) {
        throw new ApplicationError(
          "This user never set a local password, please login with the provider used during account creation"
        );
      }

      const validPassword = await getService("user").validatePassword(
        params.password,
        user.password
      );

      if (!validPassword) {
        throw new ValidationError("Invalid identifier or password");
      } else {
        ctx.send({
          jwt: getService("jwt").issue({
            id: user.id,
          }),
          user: await sanitizeUser(user, ctx),
        });
      }
    } else {
      if (!_.get(await store.get({ key: "grant" }), [provider, "enabled"])) {
        throw new ApplicationError("This provider is disabled");
      }

      // Connect the user with the third-party provider.
      let user;
      let error;
      try {
        [user, error] = await connect(provider, ctx.query);
      } catch ([user, error]) {
        throw new ApplicationError(error.message);
      }

      if (!user) {
        throw new ApplicationError(error.message);
      }

      ctx.send({
        jwt: getService("jwt").issue({ id: user.id }),
        user: await sanitizeUser(user, ctx),
      });
    }
  };

  return plugin;
};
```

`src\extensions\users-permissions\services\providers-list.js`:
(copy the file from https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers-list.js)

**Comment by byoungd** [comment]
> [byoungd](https://github.com/byoungd), this is the workaround:
> 
> `src\extensions\users-permissions\strapi-server.js`:
> 
> ```
> "use strict";
> 
> require("dotenv").config();
> const _ = require("lodash");
> const jwt = require("jsonwebtoken");
> const utils = require("@strapi/utils");
> const { getService } = require("@strapi/plugin-users-permissions/server/utils");
> const {
>   validateCallbackBody,
> } = require("@strapi/plugin-users-permissions/server/controllers/validation/auth");
> const { sanitize } = utils;
> const { ApplicationError, ValidationError } = utils.errors;
> const sanitizeUser = (user, ctx) => {
>   const { auth } = ctx.state;
>   const userSchema = strapi.getModel("plugin::users-permissions.user");
> 
>   return sanitize.contentAPI.output(user, userSchema, { auth });
> };
> 
> const emailRegExp =
>   /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
> 
> module.exports = (plugin) => {
>   // lazy load heavy dependencies
>   const providerRequest = require("./services/providers-list");
>   /**
>    * Copy of getProfile method from https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js#L24
>    * @param {String}   provider
>    * @param {Function} callback
>    */
>   const getProfile = async (provider, query, callback) => {
>     const access_token = query.access_token || query.code || query.oauth_token;
> 
>     const providers = await strapi
>       .store({ type: "plugin", name: "users-permissions", key: "grant" })
>       .get();
> 
>     await providerRequest({
>       provider,
>       query,
>       callback,
>       access_token,
>       providers,
>     });
>   };
> 
>   /**
>    * Rewrite of connect method.
>    * OVERRIDE: https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js#L44
>    * @param {*} provider
>    * @param {*} query
>    * @returns
>    */
>   const connect = async (provider, query) => {
>     const access_token = query.access_token || query.code || query.oauth_token;
> 
>     return new Promise((resolve, reject) => {
>       if (!access_token) {
>         return reject([null, { message: "No access_token." }]);
>       }
> 
>       // Get the profile.
>       getProfile(provider, query, async (err, profile) => {
>         if (err) {
>           return reject([null, err]);
>         }
> 
>         const email = _.toLower(profile.email);
> 
>         // We need at least the mail.
>         if (!email) {
>           return reject([null, { message: "Email was not available." }]);
>         }
> 
>         try {
>           // OVERRIDE: instead of find many with email, we assume that  theres only one account per email and look for the user with the email so we can login with multiple providers
>           const users = await strapi.query('plugin::users-permissions.user').findMany({
>             where: { email },
>           });
> 
>           const advanced = await strapi
>             .store({
>               type: "plugin",
>               name: "users-permissions",
>               key: "advanced",
>             })
>             .get();
> 
>           const user = _.find(users, { provider });
> 
>           if (_.isEmpty(user) && !advanced.allow_register) {
>            // OVERRIDE: change error object
>             return resolve([
>               null,
>               // [{ messages: [{ id: "Auth.advanced.allow_register" }] }],
>               { message: "Register action is actually not available." },
>             ]);
>           }
> 
>           if (!_.isEmpty(user)) {
>             return resolve([user, null]);
>           }
> 
>            if (
>              !_.isEmpty(_.find(users, (user) => user.provider !== provider)) &&
>              advanced.unique_email
>            ) {
>            // OVERRIDE: change error object
>              return resolve([
>                null,
>                { message: "Email is already taken." },
>              ]);
>           }
> 
>           // Retrieve default role.
>           const defaultRole = await strapi
>             .query("plugin::users-permissions.role")
>             .findOne({ where: { type: advanced.default_role } });
> 
>           // Create the new user.
>           const params = {
>             ...profile,
>             email, // overwrite with lowercased email
>             provider,
>             role: defaultRole.id,
>             confirmed: true,
>           };
> 
>           const createdUser = await strapi
>             .query("plugin::users-permissions.user")
>             .create({ data: params });
> 
>           return resolve([createdUser, null]);
>         } catch (err) {
>           reject([null, err]);
>         }
>       });
>     });
>   };
> 
>   /**
>    * Rewrite of callback method.
>    * OVERRIDE: https://github.com/strapi/strapi/blob/master/packages/core/content-manager/server/controllers/collection-types.js
>    * IMPORTANT: this should be reviewd and updated in Strapi version bumps.
>    * Added lines are marked with comments starting with OVERRIDE
>    * @param {*} ctx
>    * @returns
>    */
>   plugin.controllers["auth"].callback = async (ctx) => {
>     const provider = ctx.params.provider || "local";
>     const params = ctx.request.body;
> 
>     const store = await strapi.store({
>       type: "plugin",
>       name: "users-permissions",
>     });
> 
>     if (provider === "local") {
>       if (!_.get(await store.get({ key: "grant" }), "email.enabled")) {
>         throw new ApplicationError("This provider is disabled");
>       }
> 
>       await validateCallbackBody(params);
> 
>       const query = { provider };
> 
>       // Check if the provided identifier is an email or not.
>       const isEmail = emailRegExp.test(params.identifier);
> 
>       // Set the identifier to the appropriate query field.
>       if (isEmail) {
>         query.email = params.identifier.toLowerCase();
>       } else {
>         query.username = params.identifier;
>       }
> 
>       // Check if the user exists.
>       const user = await strapi
>         .query("plugin::users-permissions.user")
>         .findOne({ where: query });
> 
>       if (!user) {
>         throw new ValidationError("Invalid identifier or password");
>       }
> 
>       if (
>         _.get(await store.get({ key: "advanced" }), "email_confirmation") &&
>         user.confirmed !== true
>       ) {
>         throw new ApplicationError("Your account email is not confirmed");
>       }
> 
>       if (user.blocked === true) {
>         throw new ApplicationError(
>           "Your account has been blocked by an administrator"
>         );
>       }
> 
>       // The user never authenticated with the `local` provider.
>       if (!user.password) {
>         throw new ApplicationError(
>           "This user never set a local password, please login with the provider used during account creation"
>         );
>       }
> 
>       const validPassword = await getService("user").validatePassword(
>         params.password,
>         user.password
>       );
> 
>       if (!validPassword) {
>         throw new ValidationError("Invalid identifier or password");
>       } else {
>         ctx.send({
>           jwt: getService("jwt").issue({
>             id: user.id,
>           }),
>           user: await sanitizeUser(user, ctx),
>         });
>       }
>     } else {
>       if (!_.get(await store.get({ key: "grant" }), [provider, "enabled"])) {
>         throw new ApplicationError("This provider is disabled");
>       }
> 
>       // Connect the user with the third-party provider.
>       let user;
>       let error;
>       try {
>         [user, error] = await connect(provider, ctx.query);
>       } catch ([user, error]) {
>         throw new ApplicationError(error.message);
>       }
> 
>       if (!user) {
>         throw new ApplicationError(error.message);
>       }
> 
>       ctx.send({
>         jwt: getService("jwt").issue({ id: user.id }),
>         user: await sanitizeUser(user, ctx),
>       });
>     }
>   };
> 
>   return plugin;
> };
> ```
> 
> `src\extensions\users-permissions\services\providers-list.js`: (copy the file from https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers-list.js)

Yeah, I do have the problem and maybe it’s about node version?

My local env is:

- macOS 12.3
- node 14.18.3

**Comment by ptminh-kmp** [comment]
Hi, I got same error. I setup Strapi Google Authentication following this article: https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers
Front end use sample project https://github.com/strapi/strapi-examples/tree/master/login-react.

Front end console log show:
<img width="803" alt="Screen Shot 2022-03-30 at 18 28 42" src="https://user-images.githubusercontent.com/52888255/160824467-00d0d873-8298-444b-9f41-da5bf7628ae8.png">

Strapi show:
<img width="577" alt="Screen Shot 2022-03-30 at 18 29 39" src="https://user-images.githubusercontent.com/52888255/160824616-3352b9b7-87ba-4620-a7fa-b000446b60cf.png">

**Comment by byoungd** [comment]
Yeah I quite don’t understand why this issue has been closed.





------------------ Original ------------------
From: ptminh-kmp ***@***.***&gt;
Date: Wed,Mar 30,2022 7:30 PM
To: strapi/strapi ***@***.***&gt;
Cc: han ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [strapi/strapi] Problem with application errors on external login providers (Issue #12907)





 
Hi, I got same error. I setup Strapi Google Authentication following this article: https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers
 Front end use sample project https://github.com/strapi/strapi-examples/tree/master/login-react.
 
Front end console log show:
 
 
Strapi show:

**Comment by ptminh-kmp** [comment]
> Yeah I quite don’t understand why this issue has been closed.
> […](#)
> ------------------ Original ------------------ From: ptminh-kmp ***@***.***&gt; Date: Wed,Mar 30,2022 7:30 PM To: strapi/strapi ***@***.***&gt; Cc: han ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [strapi/strapi] Problem with application errors on external login providers (Issue #12907) Hi, I got same error. I setup Strapi Google Authentication following this article: https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers Front end use sample project https://github.com/strapi/strapi-examples/tree/master/login-react. Front end console log show: Strapi show: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;


I try @sebrojas14 solution, it works. Maybe you can try it again. This is strapi project folder after fix
<img width="173" alt="Screen Shot 2022-03-30 at 18 38 16" src="https://user-images.githubusercontent.com/52888255/160826069-60e806be-088b-4855-8ae9-b650c817dd1e.png">

But I still wait for offical solution anyway.

**Comment by byoungd** [comment]
> > Yeah I quite don’t understand why this issue has been closed.
> > […](#)
> > ------------------ Original ------------------ From: ptminh-kmp _**@**_._**> Date: Wed,Mar 30,2022 7:30 PM To: strapi/strapi _**@**_.**_> Cc: han _**@**_._**>, Comment _**@**_.**_> Subject: Re: [strapi/strapi] Problem with application errors on external login providers (Issue #12907) Hi, I got same error. I setup Strapi Google Authentication following this article: https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers Front end use sample project https://github.com/strapi/strapi-examples/tree/master/login-react. Front end console log show: Strapi show: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> I try @sebrojas14 solution, it works. Maybe you can try it again. This is strapi project folder after fix <img alt="Screen Shot 2022-03-30 at 18 38 16" width="173" src="https://user-images.githubusercontent.com/52888255/160826069-60e806be-088b-4855-8ae9-b650c817dd1e.png">
> 
> But I still wait for offical solution anyway.

Thanks man, I will try it.

**Comment by ptminh-kmp** [comment]
> [byoungd](https://github.com/byoungd), this is the workaround:
> 
> `src\extensions\users-permissions\strapi-server.js`:
> 
> ```
> "use strict";
> 
> require("dotenv").config();
> const _ = require("lodash");
> const jwt = require("jsonwebtoken");
> const utils = require("@strapi/utils");
> const { getService } = require("@strapi/plugin-users-permissions/server/utils");
> const {
>   validateCallbackBody,
> } = require("@strapi/plugin-users-permissions/server/controllers/validation/auth");
> const { sanitize } = utils;
> const { ApplicationError, ValidationError } = utils.errors;
> const sanitizeUser = (user, ctx) => {
>   const { auth } = ctx.state;
>   const userSchema = strapi.getModel("plugin::users-permissions.user");
> 
>   return sanitize.contentAPI.output(user, userSchema, { auth });
> };
> 
> const emailRegExp =
>   /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
> 
> module.exports = (plugin) => {
>   // lazy load heavy dependencies
>   const providerRequest = require("./services/providers-list");
>   /**
>    * Copy of getProfile method from https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js#L24
>    * @param {String}   provider
>    * @param {Function} callback
>    */
>   const getProfile = async (provider, query, callback) => {
>     const access_token = query.access_token || query.code || query.oauth_token;
> 
>     const providers = await strapi
>       .store({ type: "plugin", name: "users-permissions", key: "grant" })
>       .get();
> 
>     await providerRequest({
>       provider,
>       query,
>       callback,
>       access_token,
>       providers,
>     });
>   };
> 
>   /**
>    * Rewrite of connect method.
>    * OVERRIDE: https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers.js#L44
>    * @param {*} provider
>    * @param {*} query
>    * @returns
>    */
>   const connect = async (provider, query) => {
>     const access_token = query.access_token || query.code || query.oauth_token;
> 
>     return new Promise((resolve, reject) => {
>       if (!access_token) {
>         return reject([null, { message: "No access_token." }]);
>       }
> 
>       // Get the profile.
>       getProfile(provider, query, async (err, profile) => {
>         if (err) {
>           return reject([null, err]);
>         }
> 
>         const email = _.toLower(profile.email);
> 
>         // We need at least the mail.
>         if (!email) {
>           return reject([null, { message: "Email was not available." }]);
>         }
> 
>         try {
>           // OVERRIDE: instead of find many with email, we assume that  theres only one account per email and look for the user with the email so we can login with multiple providers
>           const users = await strapi.query('plugin::users-permissions.user').findMany({
>             where: { email },
>           });
> 
>           const advanced = await strapi
>             .store({
>               type: "plugin",
>               name: "users-permissions",
>               key: "advanced",
>             })
>             .get();
> 
>           const user = _.find(users, { provider });
> 
>           if (_.isEmpty(user) && !advanced.allow_register) {
>            // OVERRIDE: change error object
>             return resolve([
>               null,
>               // [{ messages: [{ id: "Auth.advanced.allow_register" }] }],
>               { message: "Register action is actually not available." },
>             ]);
>           }
> 
>           if (!_.isEmpty(user)) {
>             return resolve([user, null]);
>           }
> 
>            if (
>              !_.isEmpty(_.find(users, (user) => user.provider !== provider)) &&
>              advanced.unique_email
>            ) {
>            // OVERRIDE: change error object
>              return resolve([
>                null,
>                { message: "Email is already taken." },
>              ]);
>           }
> 
>           // Retrieve default role.
>           const defaultRole = await strapi
>             .query("plugin::users-permissions.role")
>             .findOne({ where: { type: advanced.default_role } });
> 
>           // Create the new user.
>           const params = {
>             ...profile,
>             email, // overwrite with lowercased email
>             provider,
>             role: defaultRole.id,
>             confirmed: true,
>           };
> 
>           const createdUser = await strapi
>             .query("plugin::users-permissions.user")
>             .create({ data: params });
> 
>           return resolve([createdUser, null]);
>         } catch (err) {
>           reject([null, err]);
>         }
>       });
>     });
>   };
> 
>   /**
>    * Rewrite of callback method.
>    * OVERRIDE: https://github.com/strapi/strapi/blob/master/packages/core/content-manager/server/controllers/collection-types.js
>    * IMPORTANT: this should be reviewd and updated in Strapi version bumps.
>    * Added lines are marked with comments starting with OVERRIDE
>    * @param {*} ctx
>    * @returns
>    */
>   plugin.controllers["auth"].callback = async (ctx) => {
>     const provider = ctx.params.provider || "local";
>     const params = ctx.request.body;
> 
>     const store = await strapi.store({
>       type: "plugin",
>       name: "users-permissions",
>     });
> 
>     if (provider === "local") {
>       if (!_.get(await store.get({ key: "grant" }), "email.enabled")) {
>         throw new ApplicationError("This provider is disabled");
>       }
> 
>       await validateCallbackBody(params);
> 
>       const query = { provider };
> 
>       // Check if the provided identifier is an email or not.
>       const isEmail = emailRegExp.test(params.identifier);
> 
>       // Set the identifier to the appropriate query field.
>       if (isEmail) {
>         query.email = params.identifier.toLowerCase();
>       } else {
>         query.username = params.identifier;
>       }
> 
>       // Check if the user exists.
>       const user = await strapi
>         .query("plugin::users-permissions.user")
>         .findOne({ where: query });
> 
>       if (!user) {
>         throw new ValidationError("Invalid identifier or password");
>       }
> 
>       if (
>         _.get(await store.get({ key: "advanced" }), "email_confirmation") &&
>         user.confirmed !== true
>       ) {
>         throw new ApplicationError("Your account email is not confirmed");
>       }
> 
>       if (user.blocked === true) {
>         throw new ApplicationError(
>           "Your account has been blocked by an administrator"
>         );
>       }
> 
>       // The user never authenticated with the `local` provider.
>       if (!user.password) {
>         throw new ApplicationError(
>           "This user never set a local password, please login with the provider used during account creation"
>         );
>       }
> 
>       const validPassword = await getService("user").validatePassword(
>         params.password,
>         user.password
>       );
> 
>       if (!validPassword) {
>         throw new ValidationError("Invalid identifier or password");
>       } else {
>         ctx.send({
>           jwt: getService("jwt").issue({
>             id: user.id,
>           }),
>           user: await sanitizeUser(user, ctx),
>         });
>       }
>     } else {
>       if (!_.get(await store.get({ key: "grant" }), [provider, "enabled"])) {
>         throw new ApplicationError("This provider is disabled");
>       }
> 
>       // Connect the user with the third-party provider.
>       let user;
>       let error;
>       try {
>         [user, error] = await connect(provider, ctx.query);
>       } catch ([user, error]) {
>         throw new ApplicationError(error.message);
>       }
> 
>       if (!user) {
>         throw new ApplicationError(error.message);
>       }
> 
>       ctx.send({
>         jwt: getService("jwt").issue({ id: user.id }),
>         user: await sanitizeUser(user, ctx),
>       });
>     }
>   };
> 
>   return plugin;
> };
> ```
> 
> `src\extensions\users-permissions\services\providers-list.js`: (copy the file from https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers-list.js)

Thank you. It works

**Comment by chouji19** [comment]
Hi, does anyone has the file [providers-list.js](https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers-list.js) the link is not available anymore, please. 

@byoungd 
thanks

**Comment by ptminh-gms** [comment]
> Hi, does anyone has the file [providers-list.js](https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/providers-list.js) the link is not available anymore, please.
> 
> @byoungd thanks
You can get this attached file or create strapi project with version < 4.2.x like `npx create-strapi-app@4.1.12 my-project --quickstart`

[providers-list.txt](https://github.com/strapi/strapi/files/9301827/providers-list.txt)

**Comment by Davidosky007** [comment]
the above solution doesn't work for me any idea on how to fix this issue?
