### ISSUE TITLE
Custom Dynamic Routes other than /:_id

### ISSUE THREAD

**Issue by masterkrieger** [strapi/strapi#1290]
**Informations**
- **Node.js version**: 9.10.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb v3.4.4
- **Operating system**: Mac OS X 10.13.4

**What is the current behavior?**
Added a custom dynamic route "/:slug" to `./api/article/config/routes.json`, where 'article' is my content type name. Response is a 404 error when accessing `localhost:1337/article/example-post` in browser, rather than query article "/:_id".

`{
  "routes": [
    {
      "method": "GET",
      "path": "/article",
      "handler": "Article.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/article/:_id",
      "handler": "Article.findOne",
      "config": {
        "policies": []
      }
    },`
    **`{
      "method": "GET",
      "path": "/article/:slug",
      "handler": "Article.findOne",
      "config": {
        "policies": []
      }
    },
}`**

**Steps to reproduce the problem**
Edited `./api/article/config/routes.json` to add  dynamic route "/:slug" with "findOne" handler.

**What is the expected behavior?**
Querying articles based on anything other than "_id".

**Suggested solutions**
Unknown. Possibly opening up to other query parameters in the `api/article/controllers/Article.js`

**Comment by raulriera** [comment]
My guess is that you need to remove `{ "method": "GET", "path": "/article/:_id", "handler": "Article.findOne", "config": { "policies": [] } }`, otherwise you are just creating the same route again... The router doesn't know `article/something-in-here` is an id or a slug, it will just do a match that it found something else and only something else after /article...

**Comment by raulriera** [comment]
If you removed the id route, then you need to change the findOne code to be `if (!ctx.params.slug.match(/^[0-9a-fA-F]{24}$/)) {` instead :)
