### ISSUE TITLE
Rich Text Editor Doesn't Support Multi Paragraph Edits

### ISSUE THREAD

**Issue by willisplummer** [strapi/strapi#1291]
**Informations**
- **Node.js version: 9.11.1**:
- **npm version: 5.6.0**:
- **Strapi version: 3.0.0-alpha.12.2**:
- **Database: MongoDB**:
- **Operating system**:

**What is the current behavior?**
Highlighting multiple paragraphs of text and clicking bold erases the highlighted text and replaces with the string `**bold text**`.

**Steps to reproduce the problem**
Highlight multiple paragraphs of text and click bold

**What is the expected behavior?**
Should apply bold styling to the entire highlighted region or just be disabled if that's not supported.

**Suggested solutions**
I haven't worked with DraftJS in a little while but I believe that this is a fairly common issue related to how it separates paragraphs into unique content blocks and then applies text styling on a per block basis?

**Comment by lauriejim** [comment]
Hello @willisplummer , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by soupette** [comment]
@willisplummer In fact it's logic itself that needs to be improved.

The bug is that instead of inserting `**` at both ends of the paragraph I set at the line ones.

**Comment by Aurelsicoko** [comment]
I'm closing this issue, please refers to this public card on Product Board (see https://portal.productboard.com/strapi/c/37-wysiwyg-html-editor). Even if the title doesn't express that we'll change the editor, we will certainly take a look at free & open-source alternatives like Froala.
