### ISSUE TITLE
[4.2.0-beta.0] Documentation plugin doesn't work

### ISSUE THREAD

**Issue by AlexDede** [strapi/strapi#12923]
### Describe the bug

When using the 4.2.0-beta.0 with typescript documentation plugin doesn't work. It's return 404 error

### Required System information

- Node.js version: 16.14.0
- Yarn version: 1.22.17
- Strapi version: 4.2.0-beta.0
- Database: MariaDB
- Operating system: Mac OS

### Steps to reproduce the behavior

1. Install documentation plugin
1. Go to the documentation page
2. Click on 'Open' button
4. See error:

```JSON
{
  "data": null,
  "error": {
    "status": 404,
    "name": "NotFoundError",
    "message": "Not Found",
    "details": {
      
    }
  }
}
```

### Expected behavior

Swagger documentation should be opened

### Screenshots

<img width="1692" alt="Screenshot 2022-03-23 at 17 42 17" src="https://user-images.githubusercontent.com/17781943/159738665-a1901ef6-bea2-417b-b701-ce547d04c57a.png">

<img width="591" alt="Screenshot 2022-03-23 at 17 42 47" src="https://user-images.githubusercontent.com/17781943/159738796-22873d4c-5fd3-4501-96c1-53397e1c947e.png">

**Comment by Convly** [comment]
Hi, thanks for opening this issue. I just wanted to reassure you as we're currently investigating this bug so that we can provide a fix for the stable release of the TypeScript feature. Thanks for your patience :raised_hands:

**Comment by soupette** [comment]
I am closing this issue as the fix has already been merged.
