### ISSUE TITLE
Relations don't get created through API

### ISSUE THREAD

**Issue by Nisthar** [strapi/strapi#12925]
### Required System information

- Node.js version:  v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.5.1
- Database: sqlite
- Operating system: windows 10

### Describe the bug

When you are uploading image to any content-type, the relations are not created. I think this is a bug on the sanitize function which strips the relation.

![image](https://user-images.githubusercontent.com/11994157/159909305-dd8de64b-5c0d-49ce-93e5-5c1851624822.png)
![image](https://user-images.githubusercontent.com/11994157/159909483-900bcb3f-81bd-4cce-9304-c4bc07fa56ce.png)

### Steps to reproduce the behavior

1. Create a content type with image field and some relation
2. Send a POST request to the content type along with image and relation
3. The image gets uploaded but the relation didn't get recorded.

### Expected behavior
The relation and image gets stored.

**Comment by Nisthar** [comment]
It works fine if you remove the sanitize function

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12238
