### ISSUE TITLE
[4.2 beta] We can not load or configure plugins with typescript

### ISSUE THREAD

**Issue by stafyniaksacha** [strapi/strapi#12926]
### Describe the bug

Configuring plugins and resolving local plugins do not work.
It seem that [`config/plugins.ts` is not loaded at all](https://github.com/strapi/strapi/blob/v4.2.0-beta.0/packages/core/strapi/lib/core/loaders/plugins/get-user-plugins-config.js#L15). Also [local plugin resolve target](https://github.com/strapi/strapi/blob/v4.2.0-beta.0/packages/core/strapi/lib/core/loaders/plugins/index.js#L35) seem to be forced as javascript.

### Steps to reproduce the behavior

1. create a new typescript project `npx create-strapi-app@4.2.0-beta.0 --typescript my-project`
2. generate a local plugin `yarn strapi generate`
3. create `config/plugins.ts` with
   ```
   export default ({ env }) => ({
     tsplugin: {
       enabled: true,
       resolve: "./src/plugins/tsplugin",
     }
   })
   ```

### Expected behavior

We should be able to configure plugins with typescript.
We should be able to work with local plugins written in typescript.

**Comment by soupette** [comment]
I am closing it as #13108 has been merged

**Comment by uvlek** [comment]
How deal with it?!
