### ISSUE TITLE
[4.2 beta] Default tsconfig file

### ISSUE THREAD

**Issue by stafyniaksacha** [strapi/strapi#12927]
### Describe the bug

Typescript configuration is split in two different files:
- `tsconfig-admin.json`
- `tsconfig-server.json`

IDE and `tsc` needs by default a `tsconfig.json` to work properly without any configuration.

### Expected behavior

We need something like:

- `src/admin/tsconfig.json` <admin config with extends: ../../tsconfig.shared.json> 
- `tsconfig.shared.json`
- `tsconfig.json` <server config with extends: ./tsconfig.shared.json> 

also, when creating plugins with the cli generation tools, a new `src/admin/tsconfig.json` should be generated

**Comment by Convly** [comment]
Hey @stafyniaksacha, thanks for opening this issue!

Indeed providing a single tsconfig.json file for the different parts of the app makes more sense.

Here is what we are proposing & are probably going to implement:

```
# App
/tsconfig.json
/src/admin/tsconfig.json

# Plugins
/src/plugins/**/tsconfig.json
/src/plugins/**/admin/tsconfig.json
```

Also, even if it's more linked to #12926, we would like to give the responsibility to build the plugins files to the plugins themselves. However, it might have some impact on the speed of the performance of the development mode. We'll keep you posted on that.

**Comment by stafyniaksacha** [comment]
Sound perfect @Convly !

**Comment by soupette** [comment]
Yes @Convly it will not be possible at the moment to have a different tsconfig.json for plugins that the one set in the src/admin folder.

**Comment by soupette** [comment]
I am closing this issue as it has been fixed
