### ISSUE TITLE
Saved value of relation field not displayed after save

### ISSUE THREAD

**Issue by thbwd** [strapi/strapi#12930]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1 (using yarn 1.22.17 though)
- Strapi version: 4.1.5
- Database: MySQL 8
- Operating system: macOS 12.2.1

### Describe the bug

The selected value in a relation drop-down is not displayed after save or when I load the entry. The bug disappears when I delete another component.

### Steps to reproduce the behavior

1. Create a new strapi project
2. Add the attached api and components directory.
3. Create a new "Allgemeine Seite" entry and add "Mehrspaltig" to the dynamic zone. Save. 
4. Create a second "Allgemeine Seite" entry:
5. Within the second record, add "Mehrspaltig" to the dynamic zone.
6. Add an item within "Mehrspaltig".
7. Select the first record in the relation drop-down.
8. Save the new record.
9. Observe that the selected value has disappeared.
10. Reload the page and observe that the value is not displayed.
11. Delete the "Slider" (*not* "Slider Eintrag") component from the Content-Type manager.
12. Go back to the second record.
13. Observe that the value is displayed now.

### Expected behavior

The selected value should be displayed as usual regardless of the existence of the Slider component.

### Screenshots

https://user-images.githubusercontent.com/5495918/159982527-e42bcbd8-9af9-42d0-a9d9-74183208bac3.mov

### Code snippets

See attached files.

[api_components.zip](https://github.com/strapi/strapi/files/8344232/api_components.zip)

**Comment by KubaZachacz** [comment]
Yes, yes, yes! 
I've got the same issue when saving relations inside repeatable components :/

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11955
