### ISSUE TITLE
SingleTypes don't show repeatable components

### ISSUE THREAD

**Issue by EGGamer** [strapi/strapi#12931]
## Bug report
When a Single Type just contains a repeatable component, the data of the repeatable component doesn't show on the REST API.

#### Development Enviroment
- Node.js version: 16.13.1
- NPM version: 8.4.0
- Strapi version: 4.1.5
- Database: sqlite
- Operating system: Windows

#### Production Enviroment
- Node.js version: 14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.5
- Database: mysql
- Operating system: CentOS 8

### Describe the bug

I have a Single Type configured as you can see in the image below (code snippet also added below):

![Strapi config](https://i.imgur.com/9m6aNLk.png)

As you can see, the single type just contains a repeatable component (you can find the schema of the component below).

This is the data I have put, and this is what I would expect to get from the REST API:

![Single Type Data](https://i.imgur.com/6zva7lL.png)

But here you have the response I get from the REST API:

```json
{
  "data": {
    "id": 1,
    "attributes": {
      "createdAt": "2022-03-24T18:03:24.216Z",
      "updatedAt": "2022-03-24T18:03:25.956Z",
      "publishedAt": "2022-03-24T18:03:25.951Z"
    }
  },
  "meta": {
    
  }
}
```

What's interesting is that with GraphQL the data is there:
#### Query
```graphql
query {
  homeNumberStat {
    data {
      attributes {
        NumberStats {
          topText
          statNumber
          bottomText
          position
        }
      }
    }
  }
}
```

#### Response
```json
{
  "data": {
    "homeNumberStat": {
      "data": {
        "attributes": {
          "NumberStats": [
            {
              "topText": "test1",
              "statNumber": 2,
              "bottomText": "test2",
              "position": "left"
            },
            {
              "topText": "test3",
              "statNumber": 2,
              "bottomText": "test4",
              "position": "right"
            }
          ]
        }
      }
    }
  }
}
```

So the issue must be with the REST API and not my data or my configuration. **Also note that this happens both on development AND production environments (with different databases in them).**

### Steps to reproduce the behavior

1. Create a Single Type, and put a Repeatable component with some fields.
2. Add data with the Content Manager
3. Go to the API endpoint of the REST API. You will see that there is no data there.

### Expected behavior

The data of the repeatable component should appear on the API response.

#### Single Type schema
```json
{
  "kind": "singleType",
  "collectionName": "home_number_stats",
  "info": {
    "singularName": "home-number-stat",
    "pluralName": "home-number-stats",
    "displayName": "Home-NumberStats"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "NumberStats": {
      "type": "component",
      "repeatable": true,
      "component": "home.number-stat",
      "required": true,
      "max": 2,
      "min": 2
    }
  }
}
```

#### Repeatable component schema
```json
{
  "collectionName": "components_home_number_stats",
  "info": {
    "displayName": "NumberStat",
    "icon": "adjust"
  },
  "options": {},
  "attributes": {
    "topText": {
      "type": "string"
    },
    "statNumber": {
      "type": "integer",
      "required": true,
      "default": 0
    },
    "bottomText": {
      "type": "string"
    },
    "position": {
      "type": "string",
      "required": true
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
intended, you need to populate it: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#population
