### ISSUE TITLE
Support node LTS version

### ISSUE THREAD

**Issue by SupremeTechnopriest** [strapi/strapi#1296]
**Informations**
- **Node.js version**: 8
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.12
- **Database**: mongo
- **Operating system**: osx

**What is the current behavior?**

Strapi requires unstable versions of node.  Strapi should support the Long Term Support versions of nodejs.  Not the versions where bugs will never be fixed.  Until node 10 is LTS, you should support node 8.  

**Steps to reproduce the problem**

Close strapi `cd admin` `npm i` with node 8

**What is the expected behavior?**

Long term supported node should be supported, not experimental versions.

**Suggested solutions**

Make strapi accept node 8 since it is LTS.

**Comment by derrickmehaffy** [comment]
As Strapi is an alpha project at the moment and there is still a large amount of ongoing development and with node 10 going into LTS in October 2018 (about 5 months from now) I would say it would be best to require and develop on node 10 to promote future development.

Node LTS release Schedule: https://github.com/nodejs/Release#release-schedule

**Comment by lauriejim** [comment]
Completely ok ! Strapi will be available with LTS node version when we will move on stable v3 version.

**Comment by cawoodm** [comment]
Is there an overview which NodeJS versions are supported? Googling didn't turn up much...

**Comment by SupremeTechnopriest** [comment]
@cawoodm https://github.com/strapi/strapi/blob/master/package.json#L92-L95

**Comment by SupremeTechnopriest** [comment]
I gave up on Strapi.  I have no faith in their team to follow best practices. They just seem to do whatever they want.  This thread was much longer where I argued why this is a bad idea.  Looks like they since have deleted all my criticism and back and forth with the project lead.  Shameful.  I would consider researching alternatives.

**Comment by cawoodm** [comment]
I just tried Strapi on `14.4` - doesn't run and with the same useless message you get whenever anything doesn't work. It works on `13.2` though.

```
debug ⛔️ Server wasn't able to start properly.
error (hook: bookshelf) is taking too long to load.
```

**Comment by SupremeTechnopriest** [comment]
Maybe that’s on a different branch. You can look at the package.json for other branches and see if that helps.

**Comment by derrickmehaffy** [comment]
@cawoodm Strapi supports only LTS versions, which in this case is v12 (though it will work with v10, the plan is to remove that shortly). It will never be supported to use an "odd" node version such as v13, and v14 doesn't go LTS until October and is not supported yet.
