### ISSUE TITLE
Migrating data fail

### ISSUE THREAD

**Issue by NidMo** [strapi/strapi#12967]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.5
- Database: mysql:5.7
- Operating system: mac 12.2.1

### Describe the bug

I try migrating localdata, execute .sql file success, and then gen data.But  when i run strapi, i can't find my import data.

### Steps to reproduce the behavior

1. mysql database export .sql file
2. migrating data by .sql file
3. run strapi
4. can't find data

### Screenshots

before  migrating
![image](https://user-images.githubusercontent.com/24955673/160290967-5fb55874-25ab-4b0e-8899-c7a1394be15c.png)

after migrating

![image](https://user-images.githubusercontent.com/24955673/160291014-68b447cd-f1ac-4b78-8b89-4ae75c97c8da.png)

![image](https://user-images.githubusercontent.com/24955673/160291022-bc08baef-e853-4088-af04-9170201182bb.png)

after run strapi

![image](https://user-images.githubusercontent.com/24955673/160291070-3e22948a-3b4b-48e6-88ec-6ed7b989ce61.png)

![image](https://user-images.githubusercontent.com/24955673/160291088-6c220726-97cd-45e4-9e8d-e5a739abbad0.png)

i don't know ,after run strapi ,database will init

**Comment by boazpoolman** [comment]
Hi @NidMo 

Your code likely doesn't match up with the data you are migrating.
Maby push and pull your code first, before migrating the data?

**Comment by NidMo** [comment]
> Hi @NidMo
> 
> Your code likely doesn't match up with the data you are migrating. Maby push and pull your code first, before migrating the data?

When migrating, the environment is the same

The same is mysql 5.7
The same is strapi 4.1.5

**Comment by boazpoolman** [comment]
Do you use git for the Strapi project? @NidMo

**Comment by boazpoolman** [comment]
Yeah, because you have files locally that you don't have remotely.
Make sure the files are the same, then this won't be an issue.

**Comment by NidMo** [comment]
> 

not yet.

**Comment by NidMo** [comment]
> Yeah, because you have files locally that you don't have remotely. Make sure the files are the same, then this won't be an issue.

You mean that the strapi project will generate some files locally when creating content. Will strapi initialize the database based on these files?

**Comment by boazpoolman** [comment]
Exactly

**Comment by NidMo** [comment]
> Exactly. EDIT: When you create content types / components

How should I export content and content types / components？

**Comment by boazpoolman** [comment]
It's the code. You need to move your codebase to the server. Which is most easily done with git.

**Comment by NidMo** [comment]
> It's the code. You need to move your codebase to the server. Which is most easily done with git.

So if you only use the database to export data and use the .sql file to import, there will be a problem?

**Comment by boazpoolman** [comment]
Yes, you need to match up code and database. If you do a fresh install and add the database you will encounter the issue you're having.

**Comment by NidMo** [comment]
> Yes, you need to match up code and database. If you do a fresh install and add the database you will encounter the issue you're having.

So is there no good solution now? Can I write a plug-in to export content, content types / components into a JSON file, and then call the API to generate data through this JSON file?

**Comment by NidMo** [comment]
> No you locally:
> 
> ```
> git init
> git add .
> git commit -m "Initial commit"
> git push
> ```
> 
> And remotely:
> 
> ```
> git pull
> ```
> 
> And THEN you import the DB

But sometimes I don't need to export all the data. I may only need to export some content types.

**Comment by boazpoolman** [comment]
But the code doesn't contain the data. It only contains the schema

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
