### ISSUE TITLE
I can't inspect data from component in lifecycle hooks.

### ISSUE THREAD

**Issue by TumTumMai** [strapi/strapi#12963]
### Required System information

- Node.js version: 16.14.2
- NPM version:8.5.2
- Strapi version:4.0.5
- Database:mysql
- Operating system:Mac M1

### Describe the bug

I can't inspect data from component in lifecycle hooks.

### Screenshots

![277295932_5084762678255527_2819443636523053657_n](https://user-images.githubusercontent.com/85682045/160247752-b52fa6b7-357a-4352-810d-b116ec367a2a.jpg)

![277347224_5084758794922582_6265522340169002935_n](https://user-images.githubusercontent.com/85682045/160247757-b6a2fe88-642a-4702-993a-47ea14d5b153.jpg)

![277352915_5084758781589250_2291606547179597394_n](https://user-images.githubusercontent.com/85682045/160247760-786e87be-eabf-4108-a7e0-5649a79cf99c.jpg)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
