### ISSUE TITLE
Override don't work...

### ISSUE THREAD

**Issue by lvothnrv** [strapi/strapi#12968]
Hello friends 👋 , 
I need to override the middleware body to add includeUnparsed I don’t see how to do it… 
Then I would also need to override services for users-permissions it doesn’t does not work… while it works for the controller. 
![code](https://user-images.githubusercontent.com/62966130/160291565-0f61f3cd-8cb1-4f9a-9b44-61d8558789e3.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
