### ISSUE TITLE
graphql + role & permissions broken interaction

### ISSUE THREAD

**Issue by datner** [strapi/strapi#12978]
## Bug report
Hey! I was absolutely shocked not to find a single issue (open or closed) referencing `resolverConfig`. 
Was there a purge? Is it that much of an unpopular feature? I found it to be quite trivial to need to define 1 or 2 not-crud resolvers in even a small application.

### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.1.5
- Database: postgres
- Operating system: win10

### Describe the bug

The bug is quite simple. the `auth` option in `resolveConfig` is either entirely ignored, or the docs are confusing 😅
makes me suspect that none of the other options work either.

### Steps to reproduce the behavior

1. add the `graphql` addon
2. Go to `src/index,js`
3. Add any mutation
4. configure it to have `auth: false`
5. try to run that mutation from the `/graphql` playground

### Expected behavior

Actually disable the auth for public custom resolvers :)

### Screenshots

![image](https://user-images.githubusercontent.com/22598347/160431262-d3672437-0989-4761-9cf7-42c629bb5bfd.png)

### Code snippets

example config
```ts
  register({ strapi }) {
    const extension = {
      typeDefs: `
        type Mutation {
          test(input: String!): String!
        }
      `,
      resolvers: {
        Mutation: {
          test() {
            return "good!";
          },
        },
      },
      resolverConfig: {
        "Mutation.test": {
          auth: false,
        },
      },
    }

    strapi.plugin("graphql").service("extension").use(extension);
  },
```
doesn't work using `nexus` too!
```ts
  register({ strapi }) {
    /**
     * @param {{nexus: import('nexus')}}}
     */
    const extension = ({ nexus }) => ({
      types: [
        nexus.mutationField("test", {
          type: nexus.nonNull("String"),
          args: {
            input: nexus.stringArg()
          },
          resolve() {
            return "good!";
          },
        }),
      ],
      resolverConfig: {
        "Mutation.sendOrders": {
          auth: false,
        },
      },
    });

    strapi.plugin("graphql").service("extension").use(extension);
  },
```

### Additional context

This makes strapi unusable for anything bigger than a trivial crud graphql CRM.
I don't mind trying to solve this myself, but I need direction.

**Comment by Convly** [comment]
Hi, thanks for taking the time to open an issue.

Could you try replacing `resolverConfig` with `resolversConfig` and let me know if it fixes your issue?

**Related documentation**: https://docs.strapi.io/developer-docs/latest/plugins/graphql.html#extending-the-schema

**Comment by datner** [comment]
ugh, I feel so dumb. Thats 2h down the drain 😭 

Man, types would have really been appreciated to avoid making a clown out of myself..

This can be closed 😓
