### ISSUE TITLE
Unable to set role from api during account registration

### ISSUE THREAD

**Issue by evilrat** [strapi/strapi#12976]
## Bug report
During account creation it always takes default role

### Required System information

- Node.js version: v16.13.1
- NPM version:8.1.2
- Strapi version:v4.1.5
- Database:postgres
- Operating system:centos 8

### Describe the bug

During account creation it always takes default role when i call api......unable to pass role other then default

### Steps to reproduce the behavior

https://localhost:1337/api/auth/local/register ---- it demo link as i have hostesd on server and it has domain linked

JSON passed

{
        "username": "teacher65",
        "fullname": "teacher super",
        "email": "teacher65@demo.in",
        "number": "0000000000",
        "password": "demo123",
        "language": 3,
        "doubt": 5,
        "class": 27,
        "board": 7,
        "brand": "",
        "device": "",
        "model": "",
        "versionSdkInt": "",
        "versionRelease": "",
        "product": "",
        "androidId":"",
        "role":4
      }

Also Tried

{
        "username": "teacher65",
        "fullname": "teacher super",
        "email": "teacher65@demo.in",
        "number": "0000000000",
        "password": "demo123",
        "language": 3,
        "doubt": 5,
        "class": 27,
        "board": 7,
        "brand": "",
        "device": "",
        "model": "",
        "versionSdkInt": "",
        "versionRelease": "",
        "product": "",
        "androidId":"",
        "role":{
            "id": 4
        }
      }

Response i Received on postman:-

{
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "An error occurred during account creation",
        "details": {}
    }
}
### Expected behavior

i Want to pass link user to diffrent role then default

### Additional context

User is inserted successfully but shows error and role is default only

**Comment by derrickmehaffy** [comment]
For security reasons this is not something we allow
