### ISSUE TITLE
Role object in permissions.js undefined

### ISSUE THREAD

**Issue by Velua** [strapi/strapi#1297]
**Informations**
- **Node.js version**: 9.4.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: Mongo 3.0.8
- **Operating system**: Ubuntu 16.04.1

**What is the current behavior?**
```
TypeError: Cannot read property '_id' of null
    at module.exports (/home/john/code/derp/plugins/users-permissions/config/policies/permissions.js:37:16)
    at <anonymous>
```

**Steps to reproduce the problem**
Create a fresh strapi instance with `strapi new derp`
`strapi start`
Navigate to http://localhost:1337/admin in the web browser. 

**What is the expected behavior?**
Admin portal to come up and offer me to create an account

**Suggested solutions**

**Comment by Velua** [comment]
Feels somewhat related to #1235 in a way? or #1222

**Comment by lauriejim** [comment]
Yes that's it !
