### ISSUE TITLE
Cannot fetch more that 10 files through the GpraphQL API

### ISSUE THREAD

**Issue by Matb85** [strapi/strapi#12980]
### Required System information

- Node.js version: 14.19.0
- NPM version: 6.14.6
- Strapi version: 4.1.5
- Database: postresql
- Operating system: ubuntu 20.04 LTS

### Describe the bug

Whenever I try to fetch images via the Graphql api, the response never contains more that 10 photos.
scenarios:
- when I fetch photos from an entry that has e.g. 7 photos it returns those 7
- when I fetch photos from an entry that has e.g. 13 photos it returns 10 as if the last 3 did not exist

### Steps to reproduce the behavior

1. Create a model with a media field and allow selecting many files
2. create a new entry in the content manager and select 10 photos from the library
3. update permission & try to fetch data via the GQL api
4. See only 10 photos

### Expected behavior

The api returns correct data - the expected number of photos/media files.

### Screenshots

The api returns only 10 files even though the entry has more
![image](https://user-images.githubusercontent.com/69219238/160451473-131d45bd-24c2-43bb-b99e-c7abbb8546c4.png)

### Code snippets
![image](https://user-images.githubusercontent.com/69219238/160450992-00ce5512-c51a-4169-9f30-39b00ab438df.png)

### Additional context

The rest api works fine - I can fetch all 21 files from the entry.
![image](https://user-images.githubusercontent.com/69219238/160452211-ba259e01-68ea-41b7-9779-f14eb67153f6.png)

Am I missing something? Is this intentional (e.g. because otherwise the response would be too large)? Please let me know

**Comment by LokutS2i** [comment]
Can you just paste your GraphQL request please ?
I think I have the answer

**Comment by LokutS2i** [comment]
Try this https://www.contentful.com/developers/docs/references/graphql/#/introduction/query-complexity-limits and set the limit at -1
I had a problem like this, it's because GraphQL set by default the limit of responses to 10

**Comment by Matb85** [comment]
@LokutS2i you're a life saver, thanks a lot!
