### ISSUE TITLE
Unique option for Enumeration field

### ISSUE THREAD

**Issue by Dinesh-m4** [strapi/strapi#12998]
### Required System information

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.5.1
- Database: Postgres
- Operating system: Ubuntu 20.04 lts

### Describe the bug

Unable to slect unique option for enumeration field

### Steps to reproduce the behavior

1. Go to 'content type builder  -> create a collection type/single type'
2. Click on 'c'
3. Select enemuration field -> advanced settings 
5. There is no unique filed option

### Expected behavior

Expecting Unique field option for enumeration

### Screenshots

![Screenshot from 2022-03-21 12-02-28](https://user-images.githubusercontent.com/90827714/160603377-0dde04db-0b20-4dde-99bc-6db9ad7dad53.png)

![Screenshot from 2022-03-21 12-04-52](https://user-images.githubusercontent.com/90827714/160603427-8426e8e1-f7e2-4597-be81-e530ac4662c7.png)

**Comment by petersg83** [comment]
Hello :)
Thank you, indeed. We will investigate if the code or the documentation should be updated.
Can you describe your use-case please? Why do you want the enum field to be unique?

**Comment by Dinesh-m4** [comment]
Hi,
I'm using a enum field for meta properties so I wish to have Unique property for enum, so that multiple enum values can't be created by Editors.

**Comment by petersg83** [comment]
Can you say a bit more about the general use-case? What are the values inside your enum? Why should they be unique?
Even if it is technically possible to set uniqueness on enum fields it seems unusual to me. The typical usecase would be a set of color "blue", "yellow", "green" that you use multiple times.

**Comment by Dinesh-m4** [comment]
For Example I am having some enums listed in a dropdown,I want enum field to available for selection only once.Currently it is not in that way,because of that user can able to select the same enum field again and again which leads to duplication.

**Comment by petersg83** [comment]
I understand the feature. My question is about a real life example. What values did you put in your enum field?

**Comment by derrickmehaffy** [comment]
> A meta component, one field as enum with values like meta-title, meta-description, og-tags, etc...

You do know that unique applies to the entire content-type correct? So based on that logic you couldn't reuse it in any entity unless this is in a single-type?

**Comment by Dinesh-m4** [comment]
Yes unique applies to entire content type but I'm using that meta component enum field values, will those values be unique for content types.

**Comment by derrickmehaffy** [comment]
> Yes unique applies to entire content type but I'm using that meta component enum field values, will those values be unique for content types.

Component unique will not apply to the parent content-type

**Comment by Dinesh-m4** [comment]
Its not component unique, I've used enum field in a component, I need multiple values of enum field should not be selected multiple times.

**Comment by joshuaellis** [comment]
I've spoken to the backend engineers and because we don't currently have this ability we would consider this an enhancement not a bug. I've moved it to product visibility on their board for them to review :)

**Comment by prince-lwm** [comment]
Hi, Did anyone find a solution for this? Or Is it planned?

**Comment by prince-lwm** [comment]
@Dinesh-m4 Have you find a solution in other way?

**Comment by ndrslmpk** [comment]
Are there any plans to add this? From my perspective this should be here or at least when it comes to `uid` fields be a mandatory feature. I would expect uids to have no duplicated values, when you have a big database you might want to prevent this from happening as it might cause problems, when retrieving slugs (by definition unique) from the database.

**Comment by ahmafi** [comment]
This could be very usefull. My use case is that I'm using an enumeration for the slug of some known pages in a collection, but I don't want multiple contents for one page.
