### ISSUE TITLE
Strapi v4 : Strapi custom plugin data doesn’t display on result page

### ISSUE THREAD

**Issue by LokutS2i** [strapi/strapi#12996]
### System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.5
- Database: MySQL
- Operating system: localhost

### Context

I want to create a custom plugin on Strapi v4 and to do that I need to create a service on the server side that retrieve data to use them on the front end side.

I created my plugin using the tutorial of Strapi so he is completly and fine integrated.

### Description of the Problem

My problem is that I’m able to recover the data on the server side but not to display/send them on the result page that is send when the feature is called so I can’t use them on the front end side of the plugin.

### Code

Here is my code in the file my-plugin/server/services/my-service.js :

```js
getData() {
    try {
      //I create my response variable
      let response = {};
      //I recover my data with strapi that is returned in Promise
      response = strapi
        .query("api::feedback-form.feedback-form", "strapi-plugin-export-csv")
        .findMany();
      //I return the data on the result page
      return response.then((data) => {
        return data;
      });
    } catch (err) {
      console.log("An error occurred while loading the data :");
      console.log(err);
      return null;
    }
  },
```
### Result page that stay in this state also when when a return the data

![image](https://user-images.githubusercontent.com/102290895/160552186-abb0a80b-c447-448f-89dd-ca330f64e24b.png)

**Comment by derrickmehaffy** [comment]
```
response = strapi
        .query("api::feedback-form.feedback-form", "strapi-plugin-export-csv")
        .findMany();
```

You need to make the controller async and put an await before the strapi query

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
