### ISSUE TITLE
Component Data missing from WebHook Payload request

### ISSUE THREAD

**Issue by qunu** [strapi/strapi#12999]
### Required System information

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: v4.1.3 - v4.2.0-beta.0
- Database: MySQL
- Operating system: MacOS

### Describe the bug

Component Data missing from WebHook request.

4.1.2

<img width="443" alt="Screenshot 2022-03-29 at 13 32 30" src="https://user-images.githubusercontent.com/5539045/160602300-27f27e05-9277-4e81-ac30-ffcb20542637.png">

4.1.3

<img width="460" alt="Screenshot 2022-03-29 at 13 34 12" src="https://user-images.githubusercontent.com/5539045/160602390-38becc2b-7358-46ed-9829-91b52bf5973a.png">

### Steps to reproduce the behavior

1. Change package.json replacing the below from 4.1.2 to 4.1.3
dependencies": {
    "@strapi/strapi": "4.1.2",
    "@strapi/plugin-users-permissions": "4.1.2",
    "@strapi/plugin-i18n": "4.1.2",
    "mysql": "2.18.1"
  },
2. Delete node_modules
3. npm install
4. npm run develop
5. Fire off WebHook

### Expected behavior

I expect the related component data to be sent in the WebHook payload as in v4.1.2.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by qunu** [comment]
It's not the nested data that is missing.
It's the component data that is missing from the Relation collection type.
ie.
If you have a collection type 'Test Run' that has a relation with collection type 'test' then when WebHook is sent for 'Test Run' the data does not have the extra data from the 'test' collection type, only the basic data as seen in the screenshots above

Example of setup below :

<img width="844" alt="Screenshot 2022-04-11 at 22 12 37" src="https://user-images.githubusercontent.com/5539045/162824030-53c1d069-2228-457a-95d7-d38d797aa236.png">
<img width="849" alt="Screenshot 2022-04-11 at 22 12 54" src="https://user-images.githubusercontent.com/5539045/162824016-1082c041-1979-44f3-8ef8-0d77ddc32ffc.png">

Hope this clarifies

**Comment by derrickmehaffy** [comment]
@qunu can you please provide a test repo that reproduces the issue? 
Thank you :)

**Comment by JWandscheer** [comment]
Same Issue here.
As an addition: The component content is missing in the webhook f.e. if an entry is created via GraphQL, but when duplicating the entry in Strapi, the Webhook for event.create contains the component data.
Can someone investige this further? Maybe i can try to give a repo that reproduces the issue.
