### ISSUE TITLE
auto refresh server feature

### ISSUE THREAD

**Issue by portokallidis** [strapi/strapi#130]
I am sure that you are already up to this.. 
It would be useful for strapi start to use some kind of a supervisor to restart the server instead of just logging "warn: You still need to restart your server to fully enjoy changes..."

**Comment by pierreburgy** [comment]
Hi @portokallidis,

Currently, a cluster system is implemented in Strapi (http://strapi.io/documentation/configuration#reload) but it only restart the server if it crashes. What tool do you suggest?

**Comment by yanickrochon** [comment]
If I may pitch in, restarting a server on file change should only happen in development mode, and should never happen in production. Likewise, in development mode, there should not need to have a cluster. This auto-refresh should never happen in production.

**Comment by portokallidis** [comment]
Sorry I was referring in development mode.
You can include a tool like nodemon in the package.json and modify the npm start command
And now when i update something in studio it auto restarts the server, supposing you start the app with "npm start" and not with "strapi start" 

Steps
-------
Install nodemon dependency 
` npm install --save-dev nodemon `
Change package.json start command to 
`node_modules/.bin/nodemon --watch config --watch api server.js --harmony `

**Comment by yanickrochon** [comment]
I'd vote that this should be part of strapi, and automatically be handled if in development mode. Many frameworks use config files in the root of the projects to manage commands, environments, etc. (ex: mocha, grunt, gulp, nodemon, etc.), and having a `strapi.json` file with command line arguments and environment settings  In this case, strapi uses a `./config/strapi.config` file.

While the configuration subject is not part of this question, configuring an auto refresh should be done as such. (i.e. being enabled by default, and could be disabled optionally)

**Comment by Aurelsicoko** [comment]
I agree. This feature could be awesome! We will add the auto-reload feature in the v3.0 milestone. Thanks for your suggestion. We appreciate!

**Comment by max-ivaneychyk** [comment]
try it https://github.com/strapi/strapi/issues/1008#issuecomment-489678542
