### ISSUE TITLE
Where is the CDN param for @strapi/provider-upload-aws-s3

### ISSUE THREAD

**Issue by lack-of-gravitas** [strapi/strapi#13007]
Where is the CDN param for @strapi/provider-upload-aws-s3 -- how do I set the Cloudfront distribution so that my s3 bucket isn't hammered?

**Comment by WardenCommander** [comment]
Here is open point:https://github.com/strapi/strapi/pull/11886

and we are still waiting.

**Comment by lack-of-gravitas** [comment]
yeah it's a bit stupid to suggest pointing directly to a bucket -- god help your AWS bills if you have content managers loading and refreshing pages and layouts

**Comment by WardenCommander** [comment]
I agree, this should me core feature. Im using buckblaze s3 bucket (its cheaper then aws) and cloudflare for cdn.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by lack-of-gravitas** [comment]
Forums are stale, discord doesnt work with these queries -- it's OK. We just went to Directus and have never been happier. THings just work.
