### ISSUE TITLE
mainField will lost content type builder model update

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1301]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**:5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb 3.6.4
- **Operating system**: macOS

**What is the current behavior?**
mainField in xxx.settings.json will lost if using admin panel to modify the same model

**Steps to reproduce the problem**

1. manually add 'mainField' in models/Profile.settings.json([documentation](https://strapi.io/documentation/guides/models.html#model-information)), since there is no entry to modify on admin panel.
![screen shot 2018-05-29 at 3 41 12 pm](https://user-images.githubusercontent.com/3782817/40690068-01f66640-635a-11e8-8cba-da0166fe508a.png)

2. modify field 'phoneNumber' in model 'Profile' use admin panel. For example, make 'phoneNumber' unique.
![screen shot 2018-05-30 at 10 29 31 am](https://user-images.githubusercontent.com/3782817/40737054-7b34be40-63f4-11e8-9bb3-3ff0efced8d2.png)

3. Result is: 'phoneNumber' saved, but 'mainField' lost.
![screen shot 2018-05-29 at 3 41 31 pm](https://user-images.githubusercontent.com/3782817/40690070-05d0d322-635a-11e8-854f-2ad7a8acce66.png)

**What is the expected behavior?**
new xxx.settings.json should copy from old xxx.settings.json, and merge new changes.

**Comment by derrickmehaffy** [comment]
Can confirm, just tested as well and `mainfield` is lost when modifying the model via the adminUI
