### ISSUE TITLE
I can't multiple line save enumeration with korean 

### ISSUE THREAD

**Issue by minsuKil** [strapi/strapi#13017]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.6
- Database: sql lite 3
- Operating system: mac

### Describe the bug

When I save multiple line save enumeration with korea. I can't it

### Steps to reproduce the behavior

1. Go to ContentType builder -> collection types -> add enumeration field with Enumeration
2. insert multiline value with Korean language.
3. click to finish button
4. you can see error message "Duplicate values are not allowed"
5. English is fine

### Screenshots

<img width="823" alt="image" src="https://user-images.githubusercontent.com/20369210/160957827-a3a7351e-c03e-4be0-ba5d-ae2ca7e68493.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
@petersg83 based on https://github.com/strapi/strapi/pull/12200 shouldn't this work? I mean I don't think we tested it and I have no idea how we would generate proper names for the values

**Comment by derrickmehaffy** [comment]
> Enum values are casted to values that match the graphql specifications (`/[_A-Za-z][_0-9A-Za-z]*/` source: http://spec.graphql.org/June2018/#sec-Names).
> 
> The code that does the cast is this [one](https://github.com/strapi/strapi/pull/12200/files#diff-57227a2c2810478b95bd9792203da4396890f7b1db552ede00aa5d46c4f65f2cR1). The lib used is this one : https://github.com/sindresorhus/slugify and the lib seems to return empty strings for korean (and probably many other languages).
> 
> We see here the limit of the current enum field. To solve this problem we have to separate the enum value and the display value. This feature is in the backlog but not sure when we would work on it. Ping @yanniskadiri @maevalienard

Yup, I think the only way forward is that split display/actual enum as we can't continue to tweak the logic and still support them properly in GraphQL

**Comment by durashere** [comment]
What do you think will be the best workaround for displaying proper characters on frontend if response is bad? Or maybe not using enum at all?

**Comment by petersg83** [comment]
You can play with https://github.com/sindresorhus/slugify to see if the words you use can be casted in something different than `""`. If no words work, I guess I would suggest to not use enum if displayed characters are mandatory. Maybe using a text area or a relation.

Also, is it mandatory to display in native language in Strapi or in your front-end application?
If it is only in your front-end application, maybe you can use english words in strapi and map then in the front.

**Comment by kdurek** [comment]
Hey, thanks for reply!
I don't plan to use strapi dashboard at all for my users, so I need words in my frontend app.
I ended up using textarea and validating it on front-end, but thanks to your idea I will think about using english words and mapping them.

**Comment by petersg83** [comment]
Ok :) With pleasure, thank you!

**Comment by derrickmehaffy** [comment]
closing in favor of https://feedback.strapi.io/feature-requests/p/custom-labels-for-enum-values
