### ISSUE TITLE
Foreign Key Constraint Too Long on MySQL

### ISSUE THREAD

**Issue by aaroncrawford** [strapi/strapi#13014]
## Bug report

After creating a new component, Strapi crashed and I'm getting the following error:
`error: alter table 'components_pages_product_categories_product_categories_links' add constraint 'components_pages_product_categories_product_categories_links_inv_fk' foreign key ('product_category_id') references 'product_categories' ('id') on delete CASCADE - ER_TOO_LONG_IDENT: Identifier name 'components_pages_product_categories_product_categories_links_inv_fk' is too long`

I believe the foreign key constraint name is too long with nested relationships/joins.

### Required System information

- Node.js version: 14.18.0
- NPM version: 8.0.0
- Strapi version: 4.1.6
- Database: MysQL 8
- Operating system: MacOS

### Describe the bug

Derrick said the following:
`you have a bunch of nested compos and it's failing on the join table`

### Steps to reproduce the behavior

1. Created a new component named "Product Categories".  This component is used in a page builder/dynamic zone.
2. While creating, I assigned created a relation to the Collection Type `Product Categories`.  Inside that collection is a Relation to Products.  I'm guessing this is where the nested information was coming from which resulted in the joins failing due to key length.

### Expected behavior

Strapi does not crash.

### Additional Information
This was discussed with the mod Derrick on Discord in the v4-discussions channel at 1:02 PM (CST) on 3/30/22.  A brief discussion was had there if you want to lookup the history.  Just find the picture of the dog :)

**Comment by derrickmehaffy** [comment]
Closing in favor of tracking issue: https://github.com/strapi/strapi/issues/13117
