### ISSUE TITLE
Upload plugin controller has unimplemented handlers /count

### ISSUE THREAD

**Issue by jorgeRambla** [strapi/strapi#13011]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.1.2 (but realates to latest version 4.1.5 also)
- Database: sqlite 
- Operating system: macOs
 
### Describe the bug

On: GET /api/upload/files/count
```json
{
   "data":null,
   "error":{
      "status":500,
      "name":"InternalServerError",
      "message":"Internal Server Error"
   }
}
```

Beacuse on count controller we are trying to call `getService('upload').count(ctx.query);`

And upload service do not have the `count`method.

### Steps to reproduce the behavior

1. GOTO user-permissions plugin
2. Enable upload count endpoint for public rol
3. GET /api/upload/files/count

### Expected behavior

Endpoint do no response with a 500 error. And return the count of the existing files.

### Code snippets

```javascript
  async count(ctx) {
    ctx.body = await getService('upload').count(ctx.query);
  }
```

```javascript
Object.keys(strapi.plugins.upload.services.upload).join(',');
```
Results in:
```bash
emitEvent,formatFileInfo,enhanceFile,upload,uploadFileAndPersist,updateFileInfo,replace,update,add,findOne,findMany,findPage,remove,uploadToEntity,getSettings,setSettings
```

No count method in service upload

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.7 we have a count service trying to fetch a service that doesn't exist since we got rid of count endpoints by default in v4.

**Comment by derrickmehaffy** [comment]
TODO: remove count controller

**Comment by jorgeRambla** [comment]
I will create a PR to remove the count controller then

**Comment by jorgeRambla** [comment]
Waiting for first pull request workflow approval
