### ISSUE TITLE
make a post request to 

### ISSUE THREAD

**Issue by fono97** [strapi/strapi#13028]
Hi everyone.
I am building an online community with strapi and React.
I am really stuck and seeking for answer .
I created a collection type called blog that has 4 fields 
name, email, id, comments.
comments has value a repeatable component that has 4 fields 
name, id , img, comment.

below is the datastructure
{
  "blogs" : "[
    {
        "name": "gabriel",
        "_id": "1",
        "email": "myemail.com",
        "comments": [
           {
            "name ": "strapi",
             "id" :1,
             "img ": "user1Image",
              "comment":"I love this blog"
            },
             {
            "name ": "node",
             "id" :2,
             "img ": "user2Image",
              "comment":"I want to eat"
            },       
          ],           
        
    },
 ]"
}
  

I could add data into a comments field manually since its value is a repeatable component , however, how can I make request to allow users to post data on the comments fields above.
I looked strapi docs and it seems like component doesn't have an endpoint.
I am really stuck please.
any resources that could guide me throughout the solution will be really appreciate

here was my first approache
axios
.post("http://localhost:1337/blogs/", {
comments: {
name:"gabriel",
id :"3",
"img":"user3image",
comment:"strapi is amazing"
}
})
.then((response) => {
console.log("User profile", response.data);
})
.catch((error) => {
console.log("An error occurred:", error.response);
});
in my second approaches , 
axios
.post("http://localhost:1337/blogs/id", {
comments: {
name:"gabriel",
id :"3",
"img":"user3image",
comment:"strapi is amazing"
}
})
.then((response) => {
console.log("User profile", response.data);
})
.catch((error) => {
console.log("An error occurred:", error.response);
});

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
