### ISSUE TITLE
Data Model Encryption not working , Model class is missing

### ISSUE THREAD

**Issue by sanjeetCoder** [strapi/strapi#13026]
Dear team, 

Data Model Encryption not working , Model class is missing
## Bug report

We are trying to encrypt model data in **Strapi 4.0** but because of latest update, we are unable to encrypt data. Latest strapi does not have any model class. We are unable to configure in Service, Route and Controller class.

### Required System information

- Node.js version: 14.17
- NPM version: 6.14.5
- Strapi version: 4.0
- Database: Default
- Operating system: Window 10

### Describe the bug

We are trying to encrypt model data in **Strapi 4.0** but because of latest update, we are unable to encrypt data. Latest strapi does not have any model class. We are unable to configure in Service, Route and Controller class.

### Steps to reproduce the behavior

Our Code for Strapi 3.0 written under model and it's working perfectly
=============================================
//'use strict';

/**
 * Read the documentation (https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#lifecycle-hooks)
 * to customize this model
 */

//module.exports = {};
/*********************************************/
'use strict';
var CryptoJS = require("crypto-js");
var AES = require("crypto-js/aes");
const cryptokey = process.env.CRYPTO_KEY ? process.env.CRYPTO_KEY : "youngunicornsrunfree";

/**
 * Read the documentation (https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#lifecycle-hooks)
 * to customize this model
 */
//module.exports = {};
module.exports = {
    lifecycles: {
        //Triggered before entry creation.        
        async beforeCreate(data) {
            strapi.log.info("beforeCreate CRYPTO_KEY: " + cryptokey);
            const encrypted = CryptoJS.AES.encrypt(data.postalCode, cryptokey);
            const encryptedCou = CryptoJS.AES.encrypt(data.country, cryptokey);
            strapi.log.info("beforeCreate New Data saved is this: " + encrypted.toString());
            data.postalCode = encrypted.toString();
            data.country = encryptedCou.toString();

        },

        //Triggered before entry update.        
        async beforeUpdate(params, data) {
            strapi.log.info("beforeUpdate CRYPTO_KEY: " + cryptokey);
            strapi.log.info('beforeUpdate params: ', params);
            if (data.published_at || data.published_at === null) {
                let query = await strapi.query('authentication').findOne({ id: params.id });
                strapi.log.info('beforeUpdate dataFetch: ', query.postalCode);
            } else {
                strapi.log.info('beforeUpdate data: ', data.postalCode);
                const decrypted = CryptoJS.AES.decrypt(data.postalCode, cryptokey);
                const value = decrypted.toString(CryptoJS.enc.Utf8);
                strapi.log.info("beforeUpdate Decrypted data.postalcode: " + value);

                const decryptedCunt = CryptoJS.AES.decrypt(data.country, cryptokey);
                const valueCnt = decryptedCunt.toString(CryptoJS.enc.Utf8);
                strapi.log.info("beforeUpdate Decrypted data.country: " + valueCnt);

                if (valueCnt) {
                    // Dont do anything because data is already encrypted
                    strapi.log.info("beforeUpdate no change Data already encrypted: " + data.country);
                } else {
                    // Here encrypt your string again
                    const encrypted = CryptoJS.AES.encrypt(data.country, cryptokey);
                    strapi.log.info("beforeUpdate encrypting Data to: " + encrypted.toString());
                    data.country = encrypted.toString();
                }

                if (value) {
                    // Dont do anything because data is already encrypted
                    strapi.log.info("beforeUpdate no change Data already encrypted: " + data.postalCode);
                } else {
                    // Here encrypt your string again
                    const encrypted = CryptoJS.AES.encrypt(data.postalCode, cryptokey);
                    strapi.log.info("beforeUpdate encrypting Data to: " + encrypted.toString());
                    data.postalCode = encrypted.toString();
                }

            }
        },
        //Triggered after search
        afterFind: async (results, params, populate) => {
            results.forEach(res => {
                const decrypted = CryptoJS.AES.decrypt(res.postalCode, cryptokey);
                const value = decrypted.toString(CryptoJS.enc.Utf8);
                if (value) {
                    // Dont do anything because data is already encrypted
                    strapi.log.info("afterFind decrypted data.postalcode: " + value);
                    res.postalCode = value;
                } else {
                    strapi.log.info("afterFind data.postalcode not encrypted: " + res.postalCode);
                }

                const decryptedCont = CryptoJS.AES.decrypt(res.country, cryptokey);
                const valueCont = decryptedCont.toString(CryptoJS.enc.Utf8);
                if (valueCont) {
                    // Dont do anything because data is already encrypted
                    strapi.log.info("afterFind decrypted data.country: " + valueCont);
                    res.country = valueCont;
                } else {
                    strapi.log.info("afterFind data.country not encrypted: " + res.country);
                }
            })
        },
    },
};

### Expected behavior

We are adding our code, but it's already containing module.exports and in built syntax

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
