### ISSUE TITLE
Strings and Numbers are not allowed as Json Values

### ISSUE THREAD

**Issue by JonasJW** [strapi/strapi#13032]
### Required System information

- Node.js version: 14.15.0
- NPM version: 6.14.8
- Strapi version: 4.1.0
- Database: Postgres
- Operating system: MacOS Monterey 12.1

### Describe the bug

When having a JSON attribute in a CollectionType, string and number values are not allowed. When Entering "test", I get the Error `error: Unexpected token t in JSON at position 0`. 

### Steps to reproduce the behavior

1. Create a CollectionType with a Json attribute
2. Create new Entry
3. enter "test" or 1
4. Click on Save

### Expected behavior

As strings and numbers are considered valid Json, I would expect Strapi to allow these kinds of values as well, especially as boolean values are allowed.

**Comment by esiao** [comment]
Hello Jonas, that would be because a JSON value needs to be valid JSON. You can use https://jsonlint.com/ to try it out.
It should be in the format of `{ "key": "value" }` where the value can be "test" or 1 in your example.

**Comment by JonasJW** [comment]
> Hello Jonas, that would be because a JSON value needs to be valid JSON. You can use https://jsonlint.com/ to try it out. It should be in the format of `{ "key": "value" }` where the value can be "test" or 1 in your example.

@esiao I know that it needs to be a valid Json, what I'm saying is, a single String like "test" is valid Json. You can even try with https://jsonlint.com/. Enter "test" and it will say `Valid JSON`

**Comment by stafyniaksacha** [comment]
According to the RFC, simple value are JSON too: https://datatracker.ietf.org/doc/html/rfc8259#section-13

**Comment by derrickmehaffy** [comment]
> According to the RFC, simple value are JSON too: https://datatracker.ietf.org/doc/html/rfc8259#section-13
> 
> > Here are three small JSON texts containing only values:
> >   "Hello world!"
> >   42
> >   true
> 
> you can do: 
> ```js
> JSON.parse(42)
> > 42
> ``` 
> 
> I think the issue is coming from yup validators that require json fields to be objects

Most likely yes; objects or arrays.

I don't remember exactly (would need to go dig through the code) but I believe we also do some kind of regex check.

**Comment by jmwohl** [comment]
Running into this too. The behavior is unexpected and incorrect — in fact the data gets saved correctly to the postgres jsonb field because it is valid json, but when it gets [pulled out and parsed it errors](https://github.com/strapi/strapi/blob/master/packages/core/database/lib/fields.js#L37). As far as I can tell it's only a problem for simple string values like the original example, numbers work fine. 

A couple potential solutions:

1. If the first and last char are double quotes, escape them before parsing.
2. Put the `JSON.parse(...)` in a try/catch and if it fails just return the value as a string.

**Comment by gu-stav** [comment]
Hi 👋🏼 I can not reproduce this issue using strapi@4.6.1 and I believe this has been fixed. Could you try and upgrade you instances and test this again? In case I am missing something feel free to ping me and I will re-open.
