### ISSUE TITLE
Content-Security-Policy: Cannot set directives properly

### ISSUE THREAD

**Issue by DevTrong** [strapi/strapi#13039]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.1.6

### Describe the bug

The Content-Security-Policy takes some default values, even though the property was overridden.

### Steps to reproduce the behavior

1. Change `strapi::security` in `middlewares.js` to:
```
{
    name: 'strapi::security',
    config: {
        contentSecurityPolicy: {
            directives: {
                'img-src': ["'self'", 'data:'],
            },
        },
    },
}
```
2. Go to network tab and check response headers (or `content-security-policy`)
3. Other values will be added to the `img-src` despite changing it to only use `["'self'", 'data:']`
![Screenshot 2022-04-01 at 13 50 48](https://user-images.githubusercontent.com/3624351/161258074-582f9911-e1dc-4337-9c39-3bd86ccdd2cc.png)

### Expected behavior

Only the defined values should be added to the `content-security-policy` response header.

### More Context:
In the `security.js` file - line 34 (https://github.com/strapi/strapi/blob/master/packages/core/strapi/lib/middlewares/security.js) `defaultsDeep` is being used, to merge the configs.
Arrays will not replaced, instead existing values will be updated and new ones appended. So
`_.defaultsDeep([3], [1, 2]) // results into: [3, 2]`

**Comment by derrickmehaffy** [comment]
closing for now as we won't change anything
