### ISSUE TITLE
Bug Content Manager User

### ISSUE THREAD

**Issue by lvothnrv** [strapi/strapi#13030]
Hello, someone would know why it bugs when you modify the User API by adding fields for example. We can no longer change the display of the view.. it's really annoying.
<img width="651" alt="Capture d’écran 2022-03-31 à 22 52 21" src="https://user-images.githubusercontent.com/62966130/161130624-d1530a87-1f64-4955-a5bb-8e3d3b161729.png">
<img width="1028" alt="Capture d’écran 2022-03-31 à 22 52 38" src="https://user-images.githubusercontent.com/62966130/161130638-79bd315a-4639-44c7-bdbb-13aa1f240960.png">

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
