### ISSUE TITLE
White Labeling Not working | Unable to Configure Home Page

### ISSUE THREAD

**Issue by sanjeetCoder** [strapi/strapi#13035]
## Bug report
White Labeling Not working | Unable to Configure Complete Home Page Layout 
### Required System information

- Node.js version: 14.17
- NPM version: 6.14.5
- Strapi version: 4.0
- Database: Sqlite
- Operating system: Window

### Steps to reproduce the behavior

1. Go to 'admin'

### Expected behavior

We are supposed to remove layout of Content box view like Tutorials, Documentations etc.

### Screenshots

![image](https://user-images.githubusercontent.com/62275756/161248205-ad476b7b-5e57-417c-8a62-0cffc77fc3bd.png)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
