### ISSUE TITLE
Collections with repeatable components take a huge amount of time to load

### ISSUE THREAD

**Issue by dieguezz** [strapi/strapi#13046]
### Required System information

- Node.js version: 16.6.0
- NPM version: 7.19.1
- Strapi version: 4.1.7
- Database: SQL
- Operating system: Arch Linux

### Describe the bug

When loading data from a collection that uses repeatable components, from content-manager or from the REST API, its taking a huge amount of time to load results.

### Steps to reproduce the behavior

1. Create a pair of components
2. Create a collection type that uses both components as repeatable
3. Add some content from the content manager
4. Content data takes a lot of time to load (150000ms)

### Expected behavior

It should not take a lot of time to load

### Screenshots
- Content type
![image](https://user-images.githubusercontent.com/1161455/161408830-4f6c2be4-c014-4a28-a648-927bf7b7e498.png)

- Content manager list
![image](https://user-images.githubusercontent.com/1161455/161408910-6facbe63-6707-42bd-96b5-4a8d87ca4d1d.png)

- Item content
![image](https://user-images.githubusercontent.com/1161455/161408918-17d585f0-a686-4af8-809e-dabd5c19d01c.png)

- Console log from content-manager
![image](https://user-images.githubusercontent.com/1161455/161408840-32cf0789-d9bd-46b3-a54c-96ce65ab1a6a.png)

- Postman request / response
![image](https://user-images.githubusercontent.com/1161455/161408955-88c8af03-bb1f-428c-a129-378d7d35bf02.png)

### Additional context

- I am using i18n but that is not the problem, as it happened before setting it up.
- From postman, if not adding `populate: *` then it takes 5ms. The problem comes when querying components

**Comment by derrickmehaffy** [comment]
Set as confirmed based on the number of reactions to the issue, not validated personally though it falls in line with previous performance issues. Likely needs additional optimization on the admin APIs and what we populate/select on the list vs the edit views.

**Comment by petersg83** [comment]
Hello! Sorry for the delay.
- Do you still experience this issue with the last versions of Strapi?
- Can you tell in the received data if there is some unwanted data? We had a bug where some entities would populate their parents but it should be fixed.

**Comment by derrickmehaffy** [comment]
As there hasn't been an update here in a week I'll go ahead and mark this as closed but if someone else has the issue we can look at reopening this.

Thanks!
