### ISSUE TITLE
beforeUpdate query returns afterUpdate data

### ISSUE THREAD

**Issue by pmacom** [strapi/strapi#13047]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.1.7
- Database: SQLite
- Operating system: Mac OS X

### Describe the bug

`beforeUpdate` queries are the same as `afterUpdate` results.

Components/DZs/Relations might also be updating prior to this `beforeUpdate` function gets called. Therefore any changes seen between `event.state` in the before/after hook lifecycle will be the same.

### Steps to reproduce the behavior

[Bug Example Repo](https://github.com/pmacom/strapi-beforeupdate-bug) 

1. Create a new instance of the `Example` content type and set the name field to 'Some Name'
2. Change the `name` of the content to `New Name`
3. Check the console to see
```
{ before: { id: 1, name: 'New Name', images: [ [Object] ] } }
{ after: { id: 1, name: 'New Name', images: [ [Object] ] } }
```

### Expected behavior

{ before: { id: 1, name: 'Some Name', images: [ [Object] ] } }
{ after: { id: 1, name: 'New Name', images: [ [Object] ] } }

### Code snippets

https://github.com/pmacom/strapi-beforeupdate-bug/blob/master/src/api/example/content-types/example/lifecycles.js
```
const model = 'api::example.example'
const populate = {
    gallery: {
        populate: {
            images: true
        }
    }
}

module.exports = {
    async beforeUpdate(event) {
        const { id } = event.params.where
        const before = await strapi.db.query(model).findOne({ where: { id }, populate })
        console.log({ before: before.gallery})
    },
    async afterUpdate(event) {
        const { result } = event
        console.log({ after: result.gallery })
    },
};
```

**Comment by derrickmehaffy** [comment]
I think there is some confusion as to the data that gets passed in the lifecycles:

- beforeX doesn't pass the old data, it's the new data provided in the update payload (and it only includes the data sent). If you need the previous data you should fetch it from the database
- afterX should be the new state in the database including any unchanged data
- components aren't currently handled in lifecycles as at the database layer they are just content-types and components don't have their own lifecycles yet. 
- We have an open feature request for components getting their own lifecycle but it's pretty low on our priority list

**Comment by derrickmehaffy** [comment]
Marking as closed as this doesn't really look like a bug, just a misunderstanding of the lifecycles
