### ISSUE TITLE
Field of type media is not updated in entity when function update() is called on entity service  

### ISSUE THREAD

**Issue by jmsofarelli** [strapi/strapi#13041]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.1.7
- Database: SQLite
- Operating system: macOS Catalina (v10.15.7)

### Describe the bug

Using an entity service to create an entity (method `create()`) with a field of type `media` works fine.
Example (from a controller): 
```
const { parseMultipartData } = require('@strapi/utils');
const { data, files } = parseMultipartData(ctx);
const entity = await strapi.service('api::publication.publication').create({ data, files });
```
The file is created in the Media Library and is correctly associated to the entity (media field).

Updating the file of an entity using method `update()` does not work:
```
const entity = await strapi.service('api::publication.publication').update(id, { data, files });
```
The file is create in the Media Library but it's NOT updated in the entity (media field)

### Steps to reproduce the behavior

1. Create a new collection type
2. Add new media field (single media)
3. Create a controller / extend a core controller and call the entity service using a code similar to the above
4. Call the controller action to create the entity sending the file (works fine)
5. Call the controller action to update the entity sending a new file
6. The old file is not replaced by the new one in the entity (can be checked in admin UI)

### Expected behavior

The media field should be updated with a reference to a new file

### Code snippets

Code used to create the entity (frontend): => works
```
const method = 'POST';
const url = '/api/publication;
const headers = { 'Content-Type': 'multipart/form-data' };
let data = new FormData();
data.append("data", JSON.stringify({}));
data.append('files.file', file);
await axios({ method, url, data, headers });
```

Code used to update the entity: => file is uploaded but entity not updated
```
const method = 'PUT';
const url = '/api/publication/1; // id =1
const headers = { 'Content-Type': 'multipart/form-data' };
let data = new FormData();
data.append("data", JSON.stringify({}));
data.append('files.file', file);
await axios({ method, url, data, headers });
```

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.7 though as a workaround I would suggest uploading the new media first then simply updating the entity using it's media ID instead of trying to upload the entity straight to the entity instead.
