### ISSUE TITLE
Enabling Count route in V4

### ISSUE THREAD

**Issue by franckadil** [strapi/strapi#13048]
## Bug report

v3 had a /count route that would return the total number of entries.
I can’t seem to find this in v4. I used this to count my articles the front end.

Count is not an enabled route by default anymore.

### Required System information

- Strapi version: V4 latest
- Database: MysQL
- Operating system: Ubuntu 20.04 Lts

### Describe the bug
Count is not an enabled route by default anymore.

### Steps to reproduce the behavior
But when trying to create a custom route and a custom count controller I get a 404 error:
[Steps used 👈 ](https://github.com/nextrapi/Strapi_V4_Content_Type_Count/issues/1)

**Comment by derrickmehaffy** [comment]
We no longer felt a count rout was needed considering we return proper pagination metadata on all requests now.

I'm closing this as it's not a big report but something we intended. If you would like to open a feature request please use our feedback website: https://feedback.strapi.io
