### ISSUE TITLE
Check for and display Validation Errors in the UI

### ISSUE THREAD

**Issue by flomero** [strapi/strapi#13058]
### Required System information

- Node.js version: v14.16.0
- NPM version: v14.11.0
- Strapi version: v4.1.3
- Database: postgres v13.2
- Operating system: linux

### Describe the bug

The UI allows you to create a Content Collection with e.g. the API ID `date`. (It only checks the Display Name for invalid inputs.) Only after creating fields and trying to safe it displays 'Warning: an error has occcured', but without telling the user what the error is and how to fix it.

If you inspect the console you can see it:
`message: "Content Type name cannot be one of boolean, date, date-time, dateTime, time, upload"
name: "ValidationError"`

### Steps to reproduce the behavior

1. Go to 'Content-Type Builder'
2. Click on 'Create new Collection Type'
3. Input `date`  as API ID and something else as the Display Name
4. Try to safe the Collection Type

### Expected behavior

Stop the user from entering invalid API IDs in the first place, by checking all input fields not only 'Display Name'

**Comment by derrickmehaffy** [comment]
I can confirm this on v4.1.8

- content-type builder won't let you do this at all
- manually editing singularName and pluralName in the schema won't work (throws an error on boot
- Using the `yarn strapi generate content-type` allows you to do this just fine and the server will boot (no idea what's different if I were just to manually edit the schema). But adding/removing fields will throw errors.

Our CLI should validate displayName, singular, and plural + we need better error handling on boot when invalid names are detected (for everything)
