### ISSUE TITLE
Content Manager Auto Complete: Case Sensitive Text, Integer Values

### ISSUE THREAD

**Issue by kimstewartca** [strapi/strapi#13056]
Strapi 4.1.7 Content Manager, Collection Type Relationships: 
Auto complete does not work for case sensitive values.  For example, if the value is "United States", typing "united" will not work, must be "nited" or "United" to get the auto complete result to show.

Strapi 4.1.7 Content Manager, Collection Type Relationships: 
Also, typing an integer values will not auto complete if they are too far down the list, you must first scroll all the way down the auto complete dropdown list to reveal the value.  For example typing "2004" will not give the auto complete result, if it starts with 1886 you must scroll all the way down to see the 2004 result first.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by kimstewartca** [comment]
## Bug report

### Required System information

- Node.js version: v14.19.1
- NPM version: 8.5.5
- Strapi version: 4.1.8
- Database: AWS RDS Postgres 14.2
- Operating system: Ubuntu Server 20

### Describe the bug

Strapi 4.1.8 Content Manager, Collection Type Relationships:
Typing an integer values will not auto complete if they are too far down the list, you must first scroll all the way down the auto complete dropdown list to reveal the value. For example typing "2004" will not give the auto complete result, if it starts with 1886 you must scroll all the way down to see the 2004 result first.

### Steps to reproduce the behavior

1. Create a collection type "year" with 100 unique entries, 1925 through 2025.
2. Create a two way relationship within Strapi Content Builder with this collection type and another collection type.
3. Next, create or edit an existing entry, select "Year" dropdown and start typing "2004"

### Expected behavior

It should show "2004" with autocomplete via typing but instead you must manually scroll down to the very bottom of the dropdown list to see this result and to select it.

**Comment by kimstewartca** [comment]
## Bug report

### Required System information

- Node.js version: v14.19.1
- NPM version: 8.5.5
- Strapi version: 4.1.8
- Database: AWS RDS Postgres 14.2
- Operating system: Ubuntu Server 20

### Describe the bug

Strapi 4.1.7 Content Manager, Collection Type Relationships:
Auto complete does not work for case sensitive values. For example, if the value is "United States", typing "united" will not work, must be "nited" or "United" to get the auto complete result to show

### Steps to reproduce the behavior

1. Create a collection type "country" with "United States" as an entry.
2. Create a two way relationship within Strapi Content Builder with this collection type and another collection type.
3. Next, create or edit an existing entry, select "Country" dropdown and start typing "united" (without a capital U).

### Expected behavior

Expecting to see"United States" with autocomplete via typing but it won't show up with a lowercase "u".  You must type "United" with a capital "U" to see the autocomplete result.
