### ISSUE TITLE
Unble to access strapi rest api using Azure Active Directory Token

### ISSUE THREAD

**Issue by teamsdeveloper** [strapi/strapi#13057]
Hi.,
I am using Azure Active Directory Provider (Microsoft) and I followed instructions given in the below url to setup Microsoft Provider.

https://stackoverflow.com/questions/62137923/how-can-i-set-up-sso-with-azure-ad-and-our-back-end-strapi

If I clicked sign in button from front web site, it took me to admin portal and then admin portal took me to active directory sign in page. I signed in successfully, It redirected me to admin portal and admin portal redirected me to front web site with access token.

Then I got that access token from query string, passed that token to strapi rest api for example I have collection type called categories (Authenitcated )

/api/categories and passed authorization header with the token which I got from azure active directory.

But I still get 401 error.

Please help me to fix it

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
