### ISSUE TITLE
Strapi can't load local custom upload provider

### ISSUE THREAD

**Issue by siamekanto19** [strapi/strapi#13052]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.1.7
- Database: sqlite
- Operating system: macOS Monterey 12. 3

### Description

Strapi can't load the custom upload provider created at the `providers` directory in project's root as per instructed in the documentations. Even after following all steps in documentation carefully, the server fails to start and throws the following error:
```
Server wasn't able to start properly
Could not load upload provider "custom" // Or whatever the name of the provider is
```

### Steps to reproduce the behavior

1 . Create a custom local upload provider (without publishing to npm) exactly as it was instructed in Strapi docs.
2. Run `npm install` and `npm run develop` 
3. It should throw the said error above
4. If it doesn't throw the error in first run, stop the server and make some changes to the provider's code and run `npm install` and `npm run develop` again. Now it should throw the error.

### Expected behavior

Custom upload providers loads without any error and works as expected by the codes inside of the provider.

### Screenshots

<img width="1123" alt="Screenshot 2022-04-04 at 2 13 28 PM" src="https://user-images.githubusercontent.com/71663224/161502227-9aff91e3-7a39-4f96-ae40-56cd9ffac865.png">

### Reporudction Repository

Please use this repository for reproduction: https://github.com/siamekanto19/strapi-custom-provider-error-reproduction
@gu-stav

**Comment by petersg83** [comment]
Hi @siamekanto19!
I downloaded your reproduction repository (thank you for that, it is really helpful) and it works on my side, even after modifying the custom provider.
What happens if you delete the folder `/users/siam/Desktop/strapi-plugin-fix/node_modules/@strapi/provider-upload-custom` and run `yarn` again?

**Comment by siamekanto19** [comment]
Hi @petersg83 

Thank you for taking your time to review my issue. I later found out that, strapi can't load the provider if I bring any external js library inside the provider's `upload` and `uploadstream` functions. In my case, I imported the library `sharp` to do some custom image manipulations on my own inside the custom provider. After I imported it, strapi fails to load the plugin. Can you please check that?

I have made the new commit to the reproduction repository where I imported the same external library inside the provider's code. Can you please pull the main branch and check the issue again?

Thanks a lot

**Comment by petersg83** [comment]
Thanks for the commit! I see there is the following error :
![Capture d’écran 2022-04-08 à 18 20 02](https://user-images.githubusercontent.com/11708220/162482299-866e95de-151d-46b8-82df-50ce4834e010.png)
I think you forgot to put `async` line 43 and 64 :)

I will update Strapi so the error is correctly sent to the terminal
