### ISSUE TITLE
Unable to change Stapi Dashboard Grid View like Documentation,Tutorials, Blog etc

### ISSUE THREAD

**Issue by sanjeetCoder** [strapi/strapi#13051]
## Bug report
Unable to change Stapi Dashboard Grid View like Dashboard,Tutorials, Blog etc

### Required System information

- Node.js version: 14.17
- NPM version: 6.14.5
- Strapi version: 4.1.5
- Database: Sqlite
- Operating system: Windows

### Describe the bug
We are trying to remove Stapi Dashboard Grid View like Dashboard,Tutorials, Blog etc but it's not getting removed while other data are easily editable

### Steps to reproduce the behavior 
1. Go to 'src/admin/app.js'
2. Click on 'app.js'

### Expected behavior

We want to remove Stapi Dashboard Grid View like Dashboard,Tutorials, Blog etc 

### Screenshots

![image](https://user-images.githubusercontent.com/62275756/161501008-a9b0cd56-902a-4a11-a649-ad6f8adb8680.png)

### Code snippets

![image](https://user-images.githubusercontent.com/62275756/161500696-f7efd9ae-11db-4a45-9958-1f51ec484d88.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
