### ISSUE TITLE
Always load the short user language code  in UI when reload page.

### ISSUE THREAD

**Issue by zhuang17** [strapi/strapi#1306]
**Informations**
- **Node.js version**:
v9.11.1
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.2
- **Database**:
MongoDB
3.6.3
- **Operating system**:
MacOS 10.12

**What is the current behavior?**
Now I choose `Chinese Simplify Language(ZH-HANS`) in admin UI, and the next time when i reload the page in browser , the UI load the Language (`ZH`) in admin UI

https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/LanguageProvider/reducer.js#L27

```
// Detect user language.
const userLanguage = window.localStorage.getItem(localStorageKey) ||  window.navigator.language ||  window.navigator.userLanguage;

// Split user language in a correct format.
const userLanguageShort = get(split(userLanguage, '-'), '0');

// Check that the language is included in the admin configuration.
const foundLanguage = includes(languages, userLanguageShort) && userLanguageShort;

const initialState = fromJS({
  locale: foundLanguage || first(languages) || 'en',
});
```

looks like the code here will always load the short user language code (eg, zh for zh-hans, zh-hant )

**Steps to reproduce the problem**
1. create a new project, install project and start the server.
2. login in the admin portal, then set my language By Click the Button in `Right Top Corner`, and then switch to `ZH-HANS`.
The language become `ZH-HANS` and the `strapi-admin-language` become zh-hans in LocalStorage. Until now all works on my side.
3.  when next time i login into the admin portal, or just reload the page in browser,
My language become `ZH`. 

**What is the expected behavior?**
In `Step 3`, The admin UI should load the language i set in `step 2`.

**Suggested solutions**

try load the whole language code first, and then load the short language code if the whole language not exist.

**Comment by zhuang17** [comment]
and btw,  the current ZH translation is actually Traditional Chinese script, which should be ZH-HANT if we have multiple Chinese Language sub tag.
i guess we may change current ZH translations to ZH-HANT.

**Comment by lauriejim** [comment]
Hello @zhuang17 , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by zhuang17** [comment]
@lauriejim 

I open a PR [#1354](https://github.com/strapi/strapi/pull/1354) for this, please help review it when you have time.

**Comment by lauriejim** [comment]
Thank you a lot @zhuang17 for this update. I will ask to @soupette to review your code.
