### ISSUE TITLE
Image field from component is not saved in database mysql.

### ISSUE THREAD

**Issue by seriiserii825** [strapi/strapi#13065]
Hi. 

I created a component Skills and added to page About. 

[screen](https://i.imgur.com/FLClZm1.png)

In database after i filled fields in content manager, fields image and logo for type image doesn't exists. 

[screen](https://i.imgur.com/Y2AoMdr.png)

And at the end, i can't get those fields from query. 

[screen](https://i.imgur.com/misJd5V.png)

This is the schema

```
{
  "collectionName": "components_skill_skills",
  "info": {
    "displayName": "skills",
    "icon": "circle-notch",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
      "unique": false
    },
    "percent": {
      "type": "string",
      "required": true,
      "unique": false
    },
    "color": {
      "type": "string",
      "required": true
    },
    "logo": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images",
        "videos",
        "audios",
        "files"
      ]
    },
    "Image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ]
    },
    "number": {
      "type": "integer"
    }
  }
}

```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
