### ISSUE TITLE
No error on typescript compilation fail

### ISSUE THREAD

**Issue by DimitriGilbert** [strapi/strapi#13068]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: 4.2.0-beta.0 
- Database: mysql
- Operating system: ubuntu

### Describe the bug

When using typescript if an error happens on compilation in develop mode no error are output in the terminal just 

```bash
Starting the compilation for TypeScript files in /srv/app
error Command failed with exit code 1.
``` 

You have to run ```strapi build``` to get the error.
To be clear this is not blocking, just very inconvenient.

### Steps to reproduce the behavior

1. create a project using typescript and the 4.2 beta0
2. make a mistake in a ts file (I didn't use kebab case in the config/plugins.ts for a plugin name, that does the trick)
3. See "error" in the terminal

### Expected behavior

see the errors on typescript compilation in the console when in development mode.

**Comment by marcoautiero** [comment]
Hey @DimitriGilbert, the error that you describe is not showing in 4.3.0-beta, if you run your project with `yarn develop` and you make a mistake in a .ts file you'll receive in the terminal a description of the error.

We can consider editing the behavior of the CLI, to avoid interrupting the session if you have some compilation error, but this is a different issue/enhancement. Thank you for opening this issue and indirectly bringing light to us on this eventual enhancement.
