### ISSUE TITLE
Boolean fields are not displayed correctly in content manager overview

### ISSUE THREAD

**Issue by NicoHof** [strapi/strapi#13066]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- **Strapi version: v4.1.7**
- Database: sqlite
- Operating system: macOS M1

### Describe the bug

Boolean fields are not shown correctly in content manager collection type overview like http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user

### Steps to reproduce the behavior

1. fresh strapi instance `npx create-strapi-app@latest test-boolean-fields --quickstart`
2. Create a new user (or any other content of a custom collection type with boolean fields)
3. Configure the view to show the boolean fields http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user/configurations/list
4. visit overview: http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user
5. Boolean fields are not displayed correctly with `true/false` but with `-` regardless of the value

### Expected behavior

It should be shown if the field value is true/false.

### Screenshots
<img width="1165" alt="Bildschirmfoto 2022-04-05 um 23 46 44" src="https://user-images.githubusercontent.com/11634051/161855226-91129640-a5ff-4bb7-9557-842b7e1e1c93.png">

<img width="871" alt="Bildschirmfoto 2022-04-05 um 23 48 16" src="https://user-images.githubusercontent.com/11634051/161855305-892f9649-6e65-418b-b212-2940a2eba09c.png">

**Comment by fdis111** [comment]
Hey @gu-stav, I would like to work on this issue. Please guide me with next steps.

**Comment by gu-stav** [comment]
@fdis111 I think I'll fix this myself today because I know where the bugs come from and it will be quite an easy fix. I'll let you work on the `lang` attribute of the `html` element. Thanks for showing so much dedication :)
