### ISSUE TITLE
Drag&Drop doesn't work on file fields

### ISSUE THREAD

**Issue by vcque** [strapi/strapi#13061]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.7
- Database: Postgres 13
- Operating system: MacOs / Firefox or Chrome

### Describe the bug

Drag&dropping a file on the upload widget opens the file in a new browser window instead of adding it to the content's files.

### Steps to reproduce the behavior

1. Go to a content edit panel with a file fields (singular or multiple)
2. Drag&drop an image from your computer
3. The image is previewed in a new browser window

### Expected behavior

The image should be added to the file field.

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.7

**Comment by spenya** [comment]
Same on 4.1.8

**Comment by kibblerz** [comment]
Can we prioritize this? We have clients that have complained about this issue, either we need to fix the drag and drop or change the text to something else until the drag and drop is fixed. Makes it a bit confusing for end users

**Comment by kibblerz** [comment]
Just tested and noticed that one field which allows all file types works, but the one that only allows images fails

**Comment by mattpr** [comment]
If you click to open the media-library uploader modal, the drag-drop area there works.  it is just the drag-drop area for the media field on the content type that doesn't work.  This media field is type image (not all).

![Screen Shot 2022-05-01 at 16 48 51](https://user-images.githubusercontent.com/1196252/166151338-bf9ee75a-3a96-4b66-ac87-f60e82642c0c.png)

![Screen Shot 2022-05-01 at 16 46 41](https://user-images.githubusercontent.com/1196252/166151343-c7b8f9b8-2b32-44b5-899a-0d126ed72f11.png)

`Version            │ 4.1.9 (node v14.17.3)`
