### ISSUE TITLE
Base64encoded data not getting uploaded using the rest APIs

### ISSUE THREAD

**Issue by ssshammi** [strapi/strapi#13075]
Hi am able to post files using postman 
![image](https://user-images.githubusercontent.com/2300969/162068942-b727c719-5ce5-4ec1-b243-0c4e472b5598.png)
 but not using 64bytes encoded data together with json request object using  post method to a content endpoint.  i am not sure if it was able to write the file to the upload folder because the folder does not have the file.  I am sending the file form [UE4] 
![image](https://user-images.githubusercontent.com/2300969/162076263-9675e410-8078-4ad0-9013-1f623b985d9c.png)
![image](https://user-images.githubusercontent.com/2300969/162076320-4520c5eb-be31-4683-b24a-9b1241c818f8.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by ssshammi** [comment]
Hi this is not an issue. I want to customize the or capture the data sent in the string field as Base64encoded string. together with data object i think because i have content type as JSON. I am not able to send multi-part form-data from the unreal environment. So is it possible to capture the string filed fiels.fieldname  together with data. where do i need to change cause in controllers i only get the json content type and string field flie.audiorespose @derrickmehaffy

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
