### ISSUE TITLE
Dark Mode Selector Not Available

### ISSUE THREAD

**Issue by jared-leddy** [strapi/strapi#13085]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.7
- Database: MySQL 5.5.5-10.3.34-MariaDB
- Operating system: Mac OS Monterey 12.2.1

### Describe the bug

[Strapi dark mode](https://strapi.io/blog/strapi-dark-mode) was released, and I'm trying to update my instance locally. Only, the option to change it isn't available.

### Steps to reproduce the behavior

1. Click on my name (bottom left corner)
2. Click on "Profile"
3. Scroll down to the "Experience" section. 
4. "Interface language" is available, but not "Interface mode". 

### Expected behavior

Expected to see "Interface mode" available. 

### Screenshots

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/57743183/162330472-9f964b86-3385-4b3e-9a53-ef0af7c8992d.png">

**Comment by derrickmehaffy** [comment]
Can you please try the following:

Option A:
- Rebuild your admin panel using either `npm run build` or `yarn build`

Option B:
- Delete any `build`, `.cache`, `package-lock.json`, `yarn.lock`, and `node_modules` file or folders
- Reinstall your node_modules
- (optional) run the build command listed in option a


Most likely you didn't delete the lock file when you upgraded versions and we ship a default build with the admin package and you may be using this cached build.

**Comment by jared-leddy** [comment]
```npm run build``` was the solution. Thank you!
