### ISSUE TITLE
Component with relations displays draft options

### ISSUE THREAD

**Issue by aggieSzulcDornach** [strapi/strapi#13086]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.1.7
- Database: Postgres

I created component which is wrapping relation (has one).
When I'm using it (as repeatable element), it gives me options that are not published yet.
How can I remove draft records from visible options?

Component:
![image](https://user-images.githubusercontent.com/95346609/162379173-bc9ff8e3-6635-4804-8b5b-a0444617d97d.png)

Usage:
![image](https://user-images.githubusercontent.com/95346609/162379077-c408a98e-5ce5-42c0-95ce-9e24d028108d.png)

Displaying:
![Screenshot from 2022-04-12 10-07-05](https://user-images.githubusercontent.com/95346609/162912612-e0d2fd93-9c63-45a9-a00c-74c2d38f9bc1.png)

**Comment by derrickmehaffy** [comment]
I'm not gonna mark this as duplicate but it might be related to:
https://github.com/strapi/strapi/issues/12739
https://github.com/strapi/strapi/issues/12665

**Comment by derrickmehaffy** [comment]
@gu-stav I'm not confident this is a bug, I'm guessing it's a feature request/enhancement but since you added it to the content project I'll let your squad decide.

**Comment by gu-stav** [comment]
@derrickmehaffy Thanks. We will review it as part of the next community issues review. I don't know either on top of my head.

**Comment by gu-stav** [comment]
@derrickmehaffy We looked at the issue briefly, because we are working on relations at the moment but didn't fully understand if this is a bug or a feature request: we settled on feature request, which is asking to allow configuring whether only published or also draft entities are displayed.

If you agree this is a feature-request: could you move it to Canny then please? 🙏🏼

**Comment by derrickmehaffy** [comment]
Created: https://feedback.strapi.io/customization/p/hide-component-with-relations-drafts

Will mark this as closed and lock it
