### ISSUE TITLE
How to uninstall a generated local plugin?

### ISSUE THREAD

**Issue by F0restN** [strapi/strapi#13084]
Hi guys,

I was going to remove a local plugin that was created by `strapi generate:plugin <name>` command.

But every time when I type `strapi uninstall <plugin:name> --delete-files` it shows

![image](https://user-images.githubusercontent.com/36153171/162247797-5b6971f1-a893-4f8a-95d5-b72a24416c94.png)

Strapi: version 3.6.8

How come??

**Comment by MaroueneA** [comment]
Try to stop the Strapi server with CTRL+C and restart it

**Comment by F0restN** [comment]
> 

Thank you, but it doesn't work. Same error message still

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

---

Delete the package from your package.json and if you want to remove the files entirely you can just delete your `node_modules` folder and reinstall them. (also recommended you delete any package-lock.json or yarn.lock file)
