### ISSUE TITLE
Documentation plugin cannot read property 'documentation' of undefined

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#13098]
### Required System information

- Node.js version: 14.19.0
- NPM version: 6.14.6
- Strapi version: 4.1.7
- Database: Postgres
- Operating system: Linux

### Describe the bug

Whenever setting the password at the global settings (settings > Documentation) the server throws the following error:

```
[2022-04-09 10:33:04.366] error: Cannot read property 'documentation' of undefined
TypeError: Cannot read property 'documentation' of undefined
    at module.exports (path-to-strapi/node_modules/@strapi/plugin-documentation/server/middlewares/restrict-access.js:12:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async policiesMiddleware (path-to-strapi/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (path-to-strapi/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (path-to-strapi/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (path-to-strapi/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async path-to-strapi/node_modules/@strapi/strapi/lib/middlewares/body.js:25:7
    at async path-to-strapi/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async cors (path-to-strapi/node_modules/@koa/cors/index.js:56:32)
    at async path-to-strapi/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
```

It looks like the `ctx.session` object is not defined;

```
  if (!ctx.session.documentation || !ctx.session.documentation.logged) {
 .....
 }
```

From https://github.com/strapi/strapi/blob/master/packages/plugins/documentation/server/middlewares/restrict-access.js#L12. We can anyway add a check for `ctx.session` to surpress this error.

### Steps to reproduce the behavior

1. Set a password for the documentation
2. (optionally) regenerate the documentation
3. View the documentation page

### Expected behavior

Visit the documentation page by entering the password.

### Additional context

I am overriding some of the `user-permissions` plugin settings, but this should not make a difference for this endpoint.

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.1.7, can you please provide your `./config/middlewares.js` and did you upgrade from a previous v4 version? We added the session middleware a little while back and it is required now for most plugins.

**Comment by sjoukedv** [comment]
Here is the `middleware.js`

```
module.exports = [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'dl.airtable.com', extra-cdn-domain.com'],
          'media-src': ["'self'", 'data:', 'blob:', extra-cdn-domain.com'],
        },
      }
    },
  },
  'strapi::cors',
  'strapi::logger',
  'strapi::query',
  'strapi::favicon',
  'strapi::public',
  {
    name: 'strapi::body',
    config: {
      enabled: true,
      multipart: true,
      includeUnparsed: true,
    },
  }
];
```

I am only adding some allowed media sources since I am using a CDN and I need the unparsed body to handle Stripe webhooks.

**Comment by derrickmehaffy** [comment]
You are missing the session middleware: https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.0.x-to4.0.6.html
