### ISSUE TITLE
Default value field strips newlines

### ISSUE THREAD

**Issue by StructByLightning** [strapi/strapi#13093]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.0.7
- Database: Sqlite
- Operating system: Ubuntu 20.04

### Describe the bug

The default value option strips newlines, making it impossible to define multiline default values for Rich Text fields.

### Steps to reproduce the behavior

1. Create a Collection Type with a Rich Text field.
2. In the Rich Text field's settings, set the default value to "lineone\nlinetwo"
3. Save the new Collection Type.
4. Go to the Content Manager and create a new object from the Collection Type
5. In the Rich Text field, it'll show "lineonelinetwo", with no newline between the lines.

### Expected behavior
In step 5, I expected to see
```
lineone
linetwo
```

### Screenshots
N/A

### Code snippets
N/A

### Additional context
I'm using the Toast UI Editor plugin, but the bug occurs with Strapi's default markdown editor as well.

**Comment by derrickmehaffy** [comment]
I believe the issue is in our markdown parser

**Comment by knightjdr** [comment]
If you add a newline `\n` to the default value it gets escaped in the json schema file

```
"type": "richtext",
"default": "lineone\\nlinetwo",
"required": true
```

If you edit the json (to replace the double backslash with a single), it will display as expected.
