### ISSUE TITLE
Peer-dependencies inconsistency

### ISSUE THREAD

**Issue by btd1337** [strapi/strapi#13103]
### Required System information

- Node.js version: `16.13.1`
- PNPM version: `7.0.0`
- Strapi version: `v4.2.0-beta.1 `
- Database:
- Operating system: MacOS

### Describe the bug

There is an outdated peer-dependencies configuration that is visible when trying to install via pnpm.

### Steps to reproduce the behavior

```
pnpm install --strict-peer-dependencies
```

This command above will report the peer-dependencies inconsistencies

Trying to solve them:

```
pnpm add --save-peer immer@9.0.6 koa@">=2.0.0" qs@6.10.1 react-is@">= 16.8.0" react-select@">=4.0.2 <5.0.0" redux@"^2.0.0 || ^3.0.0 || ^4.0.0-0" typescript@">=4.2.0 <5.0.0" webpack@"^5.0.0" @babel/core@">=7.0.0 <8.0.0" react-dom@">=16.8.0 <17.0.0 || >=17.0.0 <18.0.0" react@">=16.8.0 <17.0.0 || >=17.0.0 <18.0.0"
```

And if you try:

```
pnpm update
```

```sh
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @strapi/strapi
  └─┬ @strapi/admin
    └─┬ react-virtualized
      ├── ✕ unmet peer react@"^15.3.0 || ^16.0.0-alpha": found 17.0.2 in @strapi/admin
      └── ✕ unmet peer react-dom@"^15.3.0 || ^16.0.0-alpha": found 17.0.2 in @strapi/admin
```

### Expected behavior

No peer-dependencies inconsistency

### Additional context

Test with [pnpm](https://pnpm.io) which is more rigid to detect these inconsistencies.

**Comment by derrickmehaffy** [comment]
should be addressed by: https://github.com/strapi/strapi/pull/13769
