### ISSUE TITLE
forgotPassword mutation returns "Forbidden" error

### ISSUE THREAD

**Issue by dlujan** [strapi/strapi#13100]
### Required System information

- Node.js version: v17.9.0
- NPM version: 8.5.5
- Strapi version: 4.0.7
- Database: Postgres
- Operating system: MacOS

### Describe the bug

I'm using GraphQL. When I fire the 'forgotPassword' mutation with a valid email I get a "Forbidden" error.

### Steps to reproduce the behavior

1. Open Postman and paste in the mutation and supply a valid email in Variables
2. Make sure it's a POST request, click Send
3. See the pasted below error body

### Expected behavior

I expect an email to be sent to the entered email address with a reset password token.

### Screenshots

![Screen Shot 2022-04-09 at 6 06 58 PM](https://user-images.githubusercontent.com/40183621/162594491-0b282ab1-d432-48e1-b16b-3f39b70eee1b.png)

### Code snippets

If applicable, add code samples to help explain your problem.

```
mutation ForgotPassword($email: String!) {
    forgotPassword(email: $email) {
        ok
    }
}
```

```
{
    "errors": [
        {
            "message": "Forbidden",
            "extensions": {
                "error": {
                    "name": "ApplicationError",
                    "message": "Forbidden",
                    "details": {}
                },
                "code": "STRAPI_APPLICATION_ERROR"
            }
        }
    ],
    "data": {
        "forgotPassword": null
    }
}
```

### Additional context

I'm using Sendgrid and have successfully made a test email from the Strapi admin. I don't think that's related to this problem, however. Also, I get the above error response when I make this request on production. When I call this mutation locally I get this an "Unauthorized" error - all boxes are checked for users permissions still:
```
{
    "errors": [
        {
            "message": "Unauthorized",
            "extensions": {
                "error": {
                    "name": "ApplicationError",
                    "message": "Unauthorized",
                    "details": {}
                },
                "code": "STRAPI_APPLICATION_ERROR"
            }
        }
    ],
    "data": {
        "forgotPassword": null
    }
}
```

**Comment by dlujan** [comment]
Thank you for responding. I updated my Strapi version and reinstalled my packages. I'm still getting the same problem.

**Comment by bublinec** [comment]
Same problem here

**Comment by bublinec** [comment]
I forgot to change this sender address. (I'll share this in case there is ever such a moron as myself) 
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/44405894/163124650-83efe0c5-f298-4392-83c8-483136706852.png">

**Comment by dlujan** [comment]
Oh sh*t dude! @bublinec That fixed the problem! Getting an email now to reset password!

Gonna close this now but it would be great to **have a better error message for this issue** that isn't just "Forbidden".

**Comment by AnshIcode** [comment]
Yes, its working , we have to change the shipper address for sending the Forgot/reset Password email , Thanks for the solution @bublinec

**Comment by joseacunacarrera** [comment]
And is there a restriction on the emails you can put in there? I tried with one email and it worked fine, but with other email accounts I'm getting the same "Forbidden" error. I don't know if there's a configuration for that and haven't found anything
