### ISSUE TITLE
Settings lost on custom created API endpoints

### ISSUE THREAD

**Issue by Audit-a-la-Carte** [strapi/strapi#13106]
### Required System information
- Node.js version:
- v14.16.1

- Strapi version:
- 4.1.7

- Database:
- CloudSQL Google (Mysql 8)

- Operating system:
- strapi/base:14-alpine

### Describe the bug
After creating a custom endpoint on Strapi, one has to set the permissions to find or findOne. If one stores the correct settings it works, but something in the background seems to reset this setting (or possibly a deployment). The actual API endpoint of the collection type created by the admin does keep its settings, so it seems to be related to the custom (by code) created API endpoints.

### Steps to reproduce the behavior

1. Pull data in a Vue app, as usual
2. Pull data from regular endpoint, created by collection generated API, it works
3. Pull data from custom endpoint and set permissions, it works
4. A day later (could be shorter, but I noticed it three times now after a day) the settings and access are removed
5. No errors can be found, but after resetting the rights it works right away and an x period later, it fails on me once more.

### Expected behavior

It should be consistent and trustworthy the API endpoint delivers results. Can't use this in a production environment.

### Screenshots

![](https://cdn.discordapp.com/attachments/841755530007805983/963143296920731718/Screenshot_2022-04-11_at_20.26.37.png)

**Comment by derrickmehaffy** [comment]
This sounds like you are on a host that puts it's systems to "sleep" and when they wake they fetch the code again. In systems like these you can't use SQLite. Is your setup configured to use SQLite locally and MySQL in production? If you you may have forgotten to set `NODE_ENV=production` and you are actually using a SQLite 3 database instead.

**Comment by Audit-a-la-Carte** [comment]
Hi @derrickmehaffy, first off thanks for your reply! I am using Cloud run (with dedicated resources assigned) and have experienced the issue with a local DB (vs CloudSQL) engine before. Therefore I checked this prior to submitting this request 👼🏼 

Also, the changes we make to the collection entries are affected and persist (after a restart or some time). I have checked the CloudSQL database and this reflects the database changes I made in the production environment. So this doesn't seem to be the root cause this time? My database config looks like this:

```module.exports = ({ env }) => ({
  connection: {
    client: 'mysql',
    connection: {
      socketPath: `/cloudsql/${env("INSTANCE_CONNECTION_NAME")}`,
      host: env('DATABASE_HOST'),
      port: env.int('DATABASE_PORT', 3306),
      database: env('DATABASE_NAME', '###'),
      user: env('DATABASE_USERNAME', '###'),
      password: env('DATABASE_PASSWORD', '###'),
      ssl: env.bool('DATABASE_SSL', false),
    },
  },
});
```

So I did a restart just now and this didn't affect any of the settings or data. If you have any ideas on how to trace this to the root cause, would be much appreciated. 

PS: I do have NODE_ENV production indeed.

**Comment by Audit-a-la-Carte** [comment]
I haven't had any issues for a few days (upgraded to 4.1.8) not sure why, but the settings do persist now. Let's close this one and come back in case this reoccurs. Appreciate your follow up @derrickmehaffy, thanks!

**Comment by Audit-a-la-Carte** [comment]
I just had the same issue once more, I am not sure what was different. I haven't touched much... 

Once I adjust the settings from the admin panel, I can see the changes reflected on the CloudSQL database. So I am sure this isn't some default NoSQL database within the container. I am afraid there is something being executed at build time, which affects the database. I have tried reviewing migrations, but since this leaves some stored data and more recent information is missing I don’t think this has to do with Migrations? Is there a way I can check what migrations have been applied recently?

**Comment by Audit-a-la-Carte** [comment]
I am also losing data regularly, so this seems to be related to each other (settings or other database values).

**Comment by Audit-a-la-Carte** [comment]
Today the rights were dropped again and I lost my single types on production. I trust this has to do with migrations on a restart of a container, as the database seems persistent but I can't wrap my head around why this happens. If I know how to stop migrations or log the output somewhere I can better trace it.

**Comment by Audit-a-la-Carte** [comment]
I tried a couple of extra things but was not successful. This morning once more part of my database content was gone! What happens here?

So for clarity, it does not lose connectivity to the database as the admin panel just works. It also does not revert to install mode. I just loose data I entered yesterday in an entity I created.

I tried Pool options on the database, but also no luck. What could be causing this? My Cloudrun instance is on dedicated resources, so no preemptible machine.

**Comment by Audit-a-la-Carte** [comment]
Closing this ticket and expecting the Google CloudSQL infrastructure to abstract the database engine in a way, that the data doesn't always persist in combination with Strapi. Moving the setup to Digital Ocean, resolved the issue. Still it does lose connection on the container but does reconnect the database after a few minutes. Acceptable for now...

**Comment by derrickmehaffy** [comment]
> Closing this ticket and expecting the Google CloudSQL infrastructure to abstract the database engine in a way, that the data doesn't always persist in combination with Strapi. Moving the setup to Digital Ocean, resolved the issue. Still it does lose connection on the container but does reconnect the database after a few minutes. Acceptable for now...

If you are using docker on DO try setting your DB pooling min to 0 instead of 1
