### ISSUE TITLE
Strapi crashes after adding strapi-plugin-ckeditor5.

### ISSUE THREAD

**Issue by shahzaibgeekshub** [strapi/strapi#13109]
I tried to remove strapi default markdown editor and trying to add [strapi-plugin-ckeditor5](https://www.npmjs.com/package/strapi-plugin-ckeditor5) but strapi crashes when i open any entry in content manager which includes rich text editor field.

Here is the error.
<img width="1433" alt="Screenshot 2022-04-12 at 6 28 12 PM" src="https://user-images.githubusercontent.com/101640085/162973195-7415b20d-cef0-40cc-9ef2-5ffda5302895.png">

Here is my package.json

```
{
  "name": project-name",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.2",
    "@strapi/plugin-users-permissions": "4.1.2",
    "@strapi/provider-email-sendgrid": "^4.1.2",
    "@strapi/strapi": "4.1.2",
    "axios": "^0.26.1",
    "bcrypt": "^5.0.1",
    "lodash": "^4.17.21",
    "pg": "^8.7.3",
    "pg-connection-string": "^2.5.0",
    "sqlite3": "5.0.2",
    "strapi-plugin-ckeditor5": "^2.1.1-rc.1",
    "strapi-utils": "^3.6.8",
    "underscore": "^1.13.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "my-project's uuid"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```
This is what i have done so far.

1. - Delete node_modules
2. Delete .cache
3. Delete build
4. Delete package-lock.json or yarn.lock
5. Reinstall node modules
6. Rebuild admin

**Comment by derrickmehaffy** [comment]
This is not a Strapi issue, you will need to talk to the author and open an issue on their repo: https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5
