### ISSUE TITLE
Long component names are not reflected in database

### ISSUE THREAD

**Issue by dogunbound** [strapi/strapi#13116]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.7
- Database: PostgreSQL
- Operating system: Linux

### Describe the bug

If the collection's name is long, then the table name gets cut off in postgres.

I have a component named: image_size_caption_and_lightblue_background.
It's collection name in the component json is: components_subcomponents_image_size_caption_and_lightblue_backgrounds

The table name in postgres is: components_subcomponents_image_size_caption_and_lightblue_backg. The table name gets cut off because postgres only allows table names up to 63 characters. 

It seems the problem is an accumulation of both the name of the component (subcomponents) and the component category's name. This could become a real problem if user decides to have many similarly named and long collection names.

### Steps to reproduce the behavior

1. Create new strapi app that uses postgres
2. Create a component with a long name. The example above (image_size_caption_and_lightblue_background) has 43 characters. 
3. Save
4. Open a database viewing tool and view the table names.

### Expected behavior

Prevent user from using a name too long. Strapi should add string length of both the component name, and the category of component it is under.

### Screenshots

![image](https://user-images.githubusercontent.com/64436119/163078215-bfba306f-d4b1-4c82-970c-c0f7e7eb994a.png)

![image](https://user-images.githubusercontent.com/64436119/163078227-1fae80a0-9d86-479e-b862-b30d618d450f.png)

### Code snippets

component json:
```
{
  "collectionName": "components_subcomponents_image_size_caption_and_lightblue_backgrounds",
  "info": {
    "displayName": "image_size_caption_and_lightblue_background",
    "icon": "american-sign-language-interpreting"
  },
  "options": {},
  "attributes": {
    "image": {
      "allowedTypes": [
        "images"
      ],
      "type": "media",
      "multiple": false,
      "required": true
    },
    "size": {
      "type": "enumeration",
      "enum": [
        "XXS",
        "XS",
        "S",
        "M",
        "L",
        "XL",
        "XXL"
      ],
      "default": "S",
      "required": true
    },
    "caption": {
      "type": "richtext"
    },
    "lightblue_background": {
      "type": "boolean",
      "default": false,
      "required": true
    },
    "lightblue_caption_background": {
      "type": "boolean",
      "default": false,
      "required": true
    }
  }
}
```

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
Closing in favor of tracking issue: https://github.com/strapi/strapi/issues/13117
