### ISSUE TITLE
Version 4.1.8 Strapi error in build

### ISSUE THREAD

**Issue by LokutS2i** [strapi/strapi#13126]
### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.1.8
- Database: MySQL
- Operating system: Windows 11

### Describe the bug

I have an error when I build, but the strapi backend can be lunched so I don't know what is this problem🤷🏼‍♂️

### Steps to reproduce the behavior

I just updated strapi from v4.1.7 to v4.1.8

### Screenshots

![image](https://user-images.githubusercontent.com/102290895/163346631-cd9c62e5-9eea-424f-b7d4-bd54fcfb406a.png)
![image](https://user-images.githubusercontent.com/102290895/163346700-520815fa-5c20-4a5d-b7ac-ae3fe7c05bb1.png)

**Comment by NicoHof** [comment]
I can confirm. My deployment failed, too. I think breaking changes are introduced with this PR and are not mentioned in migration guides? https://github.com/strapi/strapi/pull/12287

**Comment by LokutS2i** [comment]
Do you mean this in config/admin.js  :

`module.exports = ({ env }) => ({
  apiToken: {
    salt: "*********************6b4c24",
  },
});
`
???

**Comment by niklasfjeldberg** [comment]
Have the same issue.

**Comment by MaroueneA** [comment]
Hello Community,

When updating Strapi to its latest version 4.1.8 , I encountered the same deployment problem.

**Comment by derrickmehaffy** [comment]
I recently wrote a PR for our heroku guide: https://github.com/strapi/documentation/pull/850

But yes outside of development environment you need to define your secrets now, we will be adding a small migration guide for v4.1.8 to cover this. cc @StrapiShaun / @pwizla

**Comment by derrickmehaffy** [comment]
@LokutS2i Did you get this error in production or a deployed environment or locally?

**Comment by aldovandus** [comment]
Same issue. I added this and it works now:
![image](https://user-images.githubusercontent.com/12563425/163981087-0030dabc-d9a0-4c4d-a689-202dfbe828be.png)
https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code/backend/configuration.html#admin-panel-configuration

**Comment by StrapiShaun** [comment]
Hello all, I am a technical writer at Strapi. There is now a draft migration guide available: [v4.1.8 migration- Add API_TOKEN_SALT #851
](https://github.com/strapi/documentation/pull/851). Comments are always appreciated.

**Comment by Kahtaf** [comment]
Adding this in my `config/admin.js` doesn't seem to be working for me in production (GCP). Works locally. 

```
module.exports = ({ env }) => ({
  auth: {
    secret: '*****',
  },
  apiToken: {
    salt: '*****',
  },
});
```

After deploying to GCP, everything works for about a minute or two, and then I see this in the logs and then content manager stops loading, and my newly added collection type tables get deleted. 

```
 Missing apiToken.salt. Please set apiToken.salt in config/admin.js (ex: you can generate one using Node with `crypto.randomBytes(16).toString('base64')`).
```

**Comment by derrickmehaffy** [comment]
@Kahtaf can you take this to our community platforms as I don't believe this is a bug but a problem in your environment. There is a #deployment channel on our Discord linked below that we can chat with you to figure it out.

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
