### ISSUE TITLE
Version 4.1.8 breaks custom `webpack.config.js` in `src/admin`

### ISSUE THREAD

**Issue by dzcpy** [strapi/strapi#13124]
### Required System information

- Node.js version: 16.x
- NPM version: 8.3.1
- Strapi version: 4.1.8
- Database: postgresql
- Operating system: windows

### Describe the bug

After upgrading to v4.1.8, all webpack config is invalid now.

### Steps to reproduce the behavior

1. Upgrade Strapi to 4.1.8
2. Try to add `/src/admin/webpack.config.js` with the following content:
```js
const { resolve } = require('path');

module.exports = (config, webpack) => {
  const rule = config.module.rules.find(rule => /babel-loader/.test(rule?.use?.loader));
  if (rule && rule.include) {
    rule.include.push(resolve('./node_modules/@strapi/admin/admin/src'));
  }
  return config;
};
```
3. Try to use JSX in plugin admin development, it won't work.

### Expected behavior

`/src/admin/webpack.config.js` should be working

### Screenshots

![image](https://user-images.githubusercontent.com/203980/163305819-ae1e739d-0026-4bff-842c-841b76717d9b.png)

**Comment by derrickmehaffy** [comment]
I believe we removed some babel packages in v4.1.8: https://github.com/strapi/strapi/pull/13089

This isn't really a "bug" per-say since it's customization. I'll poke @soupette to see if he has anything to add but will close this since we won't revert that PR.

**Comment by dzcpy** [comment]
@derrickmehaffy Could you please shed some lights on how to make it work with jsx? It seems that webpack cannot process jsx files anymore. How can I add it back?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Could you please shed some lights on how to make it work with jsx in `node_modules/@strapi/admin/src`? It seems that webpack cannot process jsx files anymore. How can I add it back?

Honestly I have no idea, let me try poking the frontend engineers and see what they think

**Comment by soupette** [comment]
@dzcpy babel-loader is only used to process some specific files otherwise we use esbuild-loader so I guess the customisation you are trying to do is not the correct one. Currently the loader is not used to parsed `.jsx` files so I am going to make a PR to fix the issue.
