### ISSUE TITLE
Admin: getting 403 error page after refresh on slower networks

### ISSUE THREAD

**Issue by matoushavlena** [strapi/strapi#13121]
### Required System information

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.8
- Database: pg
- Operating system: MacOS
- Browser: Chrome 100.0.4896.75 (Official Build) (x86_64)

### Describe the bug

Randomly getting 403 error page (`/admin-panel/content-manager/403`) after refreshing (F5) a page from Content Manager (for example `/admin-panel/content-manager/collectionType/api::blog-category.blog-category/73`). Appears like a race condition issue - it's easier to replicate with network throttling (actually needed when running Strapi locally).

### Steps to reproduce the behavior

1. Log in to Strapi admin
2. Go to Content Manager
3. Click on any Collection Type
4. (in Developer Console set network throttling to Fast 3G or similar) - this step might be needed only for local environment
5. Refresh the page (F5)
6. You get 403 error page `/admin-panel/content-manager/403`

### Expected behavior

The refresh should take you back to the same Content Manager page.

### Screenrecording

https://user-images.githubusercontent.com/9358330/163253776-8a2a6d94-db37-468f-85b6-5f877bc12f93.mov

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.8 but man you **really** have to slow the network down for it to happen. To the point where I'm not sure if you would ever have users with that slow of a connection (I dropped it to like 56k dial-up speeds)

**Comment by matoushavlena** [comment]
@derrickmehaffy This happens on one of our instances running on IBM Public Cloud (Openshift cluster) without any network throttling. You need to hit the refresh like 30 times, but it occasionally happens even on fast network.

**Comment by detodos** [comment]
@matoushavlena  confirmed on v4.1.8. It's happening the same on the EC2 instance ( c5a.xlarge ) (Production mode).

* Have you found any solution?

* How many admin/editor users do you have in your Strapi? I ask you because this issue started to show up when I created some admin/editor users.

**Comment by starrett67** [comment]
This happens to me on content manager pages regardless of page load speed. Running strapin in ecs fargate containers on aws.

**Comment by starrett67** [comment]
Since this was reproducible almost 100% of the time, I spent some time debugging. I realized this was a race condition caused by the permissions provided by RBAC provider would sometimes be an empty array causing the content manager to think the user does not have access to anything. I was able to fix it by patching strapi admin:

@strapi+admin+4.2.2.patch
```
diff --git a/node_modules/@strapi/admin/admin/src/content-manager/pages/App/useModels.js b/node_modules/@strapi/admin/admin/src/content-manager/pages/App/useModels.js
index 30ceea5..818a1e6 100644
--- a/node_modules/@strapi/admin/admin/src/content-manager/pages/App/useModels.js
+++ b/node_modules/@strapi/admin/admin/src/content-manager/pages/App/useModels.js
@@ -86,7 +86,7 @@ const useModels = () => {
       dispatch(resetProps());
     };
     // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [dispatch, toggleNotification]);
+  }, [dispatch, toggleNotification, allPermissions]);
 
   return { ...state, refetchData: fetchDataRef.current };
 };
```

**Comment by gu-stav** [comment]
Hi everyone 👋🏼 I'm sorry the issue got stuck for so long. I've tried to reproduce it today using strapi@v4.6 and was not able to do so with a throttled network, but I don't see the fix @starrett67 suggested being applied either.

Could someone confirm whether the issue is gone or still present? 🤔

**Comment by shweta943** [comment]
@gu-stav This issue is still there in production env. Mine is Strapi v4.6.1

**Comment by gu-stav** [comment]
@shweta943 Could you share a reproduction e.g. using a video recording or reproducible steps?

**Comment by shweta943** [comment]
(This issue is only visible in production)
I got stuck for hours and couldn't find a way to tackle this.

-Log in to Strapi admin

- Go to Content Manager

- Click on any Collection Type or single type

- Reload the page.

- The error is displayed "You don't have the permission to access that content"
