### ISSUE TITLE
One-to-many relation is handled via separate entity-to-entity table (like many-to-many).

### ISSUE THREAD

**Issue by benderillo** [strapi/strapi#13135]
### Required System information
- Strapi version: 4.1.5
- Database: MySQL
- Operating system: MacOS

### Describe the bug

**When creating a one-to-many relationship in the content builder, the resulting DB schema is like it is many-to-many.**

**Example:**
We have two Collection types: Review and Course.
The Course can have many reviews. Review belongs to only one Course.
So in Strapi Content builder we define a relation on the Review type as "`Course` has many `Reviews`".

**Expected behaviour**
The "reviews" table in the database would have a "course" field containing course.id.

**Actual behaviour**
A third table is created that contains mapping of review.id <-> course.id.

In may-to-many relationship modelling, there is no way to store relation information in the same tables that relate to each other without breaking data normalisation rule. Therefore, a third table is usually added to store relationships.

For the one-to-many relationship this is excessive because a table that is on the "one" side of the relationship can store the relationship information easily in a single field.

This, standard approach to one-to-many relationship DB design is more efficient than the "third table" one that Strapi is using in v4. 
With the current design approach, even the simplest of requests (get all reviews for a given course) will require a JOIN.
While with the traditional approach, this is just one table query

Strapi v3 had it right.

**Comment by derrickmehaffy** [comment]
This is intended as we when we implement content-versioning, we will also need to be able to version relations too (think multiple drafts of an entity that share a oneToOne relation with something else.

**Comment by benderillo** [comment]
oh well... this is another one of those changes I am seeing in v4 made for the future "content versioning" but negatively impacting my current use/experience with Strapi.
The example I have provided is simplistic. but I have another one that I just ported from v3. It had only one JOIN initially. Now I had to rewrite it to 4 JOINS (four joins!).

With this cost, the "content versioning" feature better be a really good one and more importantly be really something a lot of customers are waiting for 🥇

**Comment by benderillo** [comment]
@derrickmehaffy I am sorry for not giving up this one just yet. But I have just realised that this schema design also makes it impossible to leverage SQL `Unique` constrains on relations any more.
Given the same example of a Review entity that has a restriction of  one review per user per course. Previously, a single UNIQUE constraint on the table that makes (user, course) UNIQUE would do. 
Now I need a transaction and an extra query to the DB to ensure no user can post two reviews for a single course.

More I dig into it, more unpleasant it smells so I'd like to ask if there is any place I can read on the design of this "content versioning" feature? Was there an alternative design for it that would not require making these schema tradeoffs?
It is just, I don't believe I need the "content versioning" but it impacts me big time, so I would like to understand what it is and how it is designed.

**Comment by derrickmehaffy** [comment]
> 

We don't have the full design done yet and the first iteration of this is just gonna be `draft and publish v2` initially. The problem we had was we needed to make any breaking changes before we developed the feature so a lot of choices were made in Q4 2021 with the expectation we would build the feature later this year or early next year.

But to follow semver we needed to give us some freedom to do things differently without needing to add breaking changes and thus have to push for Strapi v5 before we were ready so a lot was left more open ended than would normally be ideal.

**Comment by derrickmehaffy** [comment]
It's like clearing trees and flatting the ground before you design the house, you kinda have to know how much land you have to determine how best to design the house. We aren't to the point where we are drawing up plans yet.

**Comment by blemoine167** [comment]
So basically do you plan to allow the user to choose a "no content versioning design" or are we stuck with this awkward design forever ? This is a crucial matter for us.

**Comment by derrickmehaffy** [comment]
> So basically do you plan to allow the user to choose a "no content versioning design" or are we stuck with this awkward design forever ? Is it possible to update the schema under the hood (making a simple FK column) without breaking strapi ? This is a crucial matter for us.

To allow for users to disable or enable the content versioning system requires the usage of our schema design, so no you cannot convert to using a simple FK column.

Strapi is not building an API framework, it's being a Headless CMS and thus the use-cases we are targeting rely on bulk usability with minimal deep effort. This requires us to design things differently than one might in their own custom backend as we have to cover a broad range of use-cases not just once niche one.

**Comment by tonilopezmr** [comment]
but please, add an option for the ones who don't want versioning, this is impacting really bad to us as well, we still need to use v3 without be able to move to v4.

Add a simple option where you just turn off this versioning and link tables. If not we would need to migrate out of Strapi and many will do as well.

**Comment by nightwalker89** [comment]
When I try to create a one-to-many relationship where there is only one review per user per product in Strapi v4, it doesn't check for duplicates or provide an option to enforce that. I'm not sure what to call this type of relationship: a user can review a product multiple times, but that's not the behavior I want. Is this still a **ones**-to-many relationship? It feels like a strange pattern to me. We can enforce uniqueness by manually checking for duplicates, but that seems like a bad solution.
