### ISSUE TITLE
[4.2.0] Can't override admin endpoint

### ISSUE THREAD

**Issue by giacomoforlani** [strapi/strapi#13134]
### Required System information

- Node.js version: 14.17.6
- NPM version: 8.5.2
- Strapi version: 4.2.0-beta.0
- Database: sqlite
- Operating system: macOS Monterey 12.0.1

### Steps to reproduce the behavior

1. Create quickstart project with TypeScript `npx create-strapi-app@latest my-project --quickstart`
2. Modify start command on package.json with `"start": "NODE_ENV=production strapi start"`
3. Build the project with `npm run build`
4. Start the project with `npm run start`
5. Register admin user
6. Visit http://0.0.0.0:1337/admin

### Description
The Admin dashboard is broken because is trying to call http://localhost:1337/admin/project-type instead of http://0.0.0.0:1337/admin/project-type

This happens because the Admin build is placed into the `dist/build` path instead of `build`. In this way, can't override the variable `STRAPI_ADMIN_BACKEND_URL`, so the admin build use default `localhost:1337`.

To resolve the issue, I need to move the `dist/build` folder into the project root.

If I use another version of Strapi, like 4.1.8, the `build` folder is placed correctly into the project root.

### Screenshots
<img width="1792" alt="Screenshot 2022-04-15 at 09 36 00" src="https://user-images.githubusercontent.com/55762486/163540260-f679b0dc-bbc7-4509-a7d3-1674531c81ee.png">

**Comment by Vidski** [comment]
Facing the same issue

**Comment by negprof** [comment]
Same problem here.

**Comment by marcoautiero** [comment]
Thank you for opening this issue.

I'm not able to reproduce this issue in the last beta.3

Please, let me know if for you is the same, I'll wait some days for your confirmation before closing the issue :)

**Comment by giacomoforlani** [comment]
Hi @marcoautiero ,
thank you for your reply.

I tried to reproduce again the bug with version beta.3 but now everything works correctly.
