### ISSUE TITLE
Strapi crashes when attempting to upload faulty / unreadable image

### ISSUE THREAD

**Issue by dogunbound** [strapi/strapi#13132]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.7
- Database: PostgreSQL
- Operating system: Linux

### Describe the bug

```
[2022-04-14 08:36:29.592] http: POST /upload (1056 ms) 200
[2022-04-14 08:36:29.594] http: POST /upload (1101 ms) 200
... many uploads later
[2022-04-14 08:36:53.390] http: POST /upload (663 ms) 200
Error: pngload_buffer: libspng read error
vips2png: unable to write to target target

[2022-04-14 08:36:53.913] http: POST /upload (615 ms) 200
[2022-04-14 08:36:53.932] http: POST /upload (640 ms) 200
[2022-04-14 08:36:53.962] http: POST /upload (672 ms) 200
[2022-04-14 08:36:54.031] http: POST /upload (744 ms) 200
Error: pngload_buffer: libspng read error
vips2png: unable to write to target target
```
### Steps to reproduce the behavior

upload an image that is "faulty / unreadable"
Use this image (right click the link and hit save image as): 
![bacchic-dancers-2nd-cent-ac-hatay-archaeology-museum-antakya-hatay-province-turkey-R8243B](https://user-images.githubusercontent.com/64436119/163405278-26d062f5-a695-452d-b88b-01db0d26fa00.png)

### Expected behavior

Try catch to prevent strapi from crashing when this happens. Possibly even a transaction rollback on the database to delete the newly inserted image that is fault. Or do it the other way around and make sure that the image can be read before running a transaction.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

This would just be a nice to have because I upload a HUGE amount of images at once sometimes. Every now and then I have a faulty image that doesn't work. It would be nice if strapi handled this for me.

**Comment by derrickmehaffy** [comment]
Confirmed on v4.1.8 
![image](https://user-images.githubusercontent.com/8593673/163877666-07ca60d2-151e-4a4a-8171-db7a695b6499.png)

**Comment by dogunbound** [comment]
@derrickmehaffy I just realized that this is a security problem too because someone malicious can upload image data through the upload params if their frontend requires the ability to upload images.
![image](https://user-images.githubusercontent.com/64436119/163910295-013d278a-81f8-4fcd-92ed-f8eb24a9b209.png)


This allows bad actors to hard crash a strapi server for those who intend use the upload feature.

**Comment by Krito1997** [comment]
Can you explain what a "faulty/unreadable" picture is?

**Comment by dogunbound** [comment]
@Krito1997 Computers aren't perfect. Sometimes I get a read or write error moving a bunch of images around on my PC. I sometimes produce "faulty/unreadable" images. If you download the image in the original post https://user-images.githubusercontent.com/64436119/163405278-26d062f5-a695-452d-b88b-01db0d26fa00.png That is a faulty/unreadable picture.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I just realized that this is a security problem too because someone malicious can upload image data through the upload params if their frontend requires the ability to upload images. ![image](https://user-images.githubusercontent.com/64436119/163910295-013d278a-81f8-4fcd-92ed-f8eb24a9b209.png)
> 
> This allows bad actors to (possibly anonymously) hard crash a strapi server for those who intend use the upload feature.

Aye yeah I informed the PM about this as well.

**Comment by Marc-Roig** [comment]
This should have been fixed in https://github.com/strapi/strapi/pull/13949.
Closing this issue
