### ISSUE TITLE
Admin Page Blank After Deploy to App Engine

### ISSUE THREAD

**Issue by iyansr** [strapi/strapi#13139]
### Required System information

- Node.js version: 16
- NPM version: >=6
- Strapi version: 4.1.8
- Database: PostgreSQL
- Operating system: App Engine

### Describe the bug

Hi, After deploying to App Engine, admin panel show loading and show white blank page after that.
Already changing default admin URL by following this [Post Setup Documentation](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html#post-setup-configuration), but when I visited /dahsboard , it show json api with 404 error

### Expected behavior

Working Properly

### Screenshots
![image](https://ik.imagekit.io/iyansr/ezgif-5-02fbdc4d07_ua75viVaY.gif?ik-sdk-version=javascript-1.4.3&updatedAt=1650173775025)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by kalves** [comment]
Hi, 

Did you run 
`NODE_ENV=production npm run build`
If so, what's the content of your build folder ?

**Comment by iyansr** [comment]
> Hi,
> 
> Did you run `NODE_ENV=production npm run build` If so, what's the content of your build folder ?

Hi, @kalves i already set to production, hovewer, the /api route seems fine.
Here some content of build folder 

![image](https://user-images.githubusercontent.com/42711013/163709939-a5fa6103-8c48-4ab8-93e0-208d8e493125.png)

**Comment by EGGamer** [comment]
Hi! I have a similar issue. I deploy the CMS to our VPS. In our case, we build everything, we start it, and everything works correctly. Though, after some time, a similar issue to this appears. The dashboard page basically just stays blank. In the console, it gives a Javascript error. I have seen that Cloudflare might be causing this issue in my case. Though, this has just started happening after upgrading to 4.1.8. Previous versions didn't do this.

**Comment by iyansr** [comment]
> Hi! I have a similar issue. I deploy the CMS to our VPS. In our case, we build everything, we start it, and everything works correctly. Though, after some time, a similar issue to this appears. The dashboard page basically just stays blank. In the console, it gives a Javascript error. I have seen that Cloudflare might be causing this issue in my case. Though, this has just started happening after upgrading to 4.1.8. Previous versions didn't do this.

Have you try downgrading? Will it work?

**Comment by iyansr** [comment]
Upate: even after downgrading to 4.1.7, issue still same

**Comment by kalves** [comment]
Apparently, the admin panel runs on `/admin` by default. Did you refer to this part [https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#access-url](url) of the doc ?

**Comment by iyansr** [comment]
> Apparently, the admin panel runs on `/admin` by default. Did you refer to this part []([https://docs.strapi.io/developer-docs/latest/development/admin-customization.html#access-url](url) of the doc ?)

Let me try

**Comment by iyansr** [comment]
Strill Blank, even after setup url, and visit /dashboard

**Comment by kalves** [comment]
Are you with `pm2` ?

**Comment by iyansr** [comment]
no, honestly, never heard before 😅

**Comment by iyansr** [comment]
Additonal info: Page become blank after login. If user not logged it yet, it shows login form normally

**Comment by iyansr** [comment]
Turns out i have simmilar issue with https://github.com/strapi/strapi/issues/12869

**Comment by vitalijalbu** [comment]
> Are you with `pm2` ?

I'm also facing this issue, running with pm2. welcome page is ok, but /admin has 2 js files 404 not found. I use a 3rd domain
