### ISSUE TITLE
Filters and pagination not showing in graphql Schema

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#13137]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.8
- Database: Postgres
- Operating system: Linux

### Describe the bug

In my latest builds the filters and pagination attributes are not included in the schema. The only difference if found is that I've add some custom-routes, but I'm not sure how that would affect it.

### Steps to reproduce the behavior
- Still working on reproducibility

### Expected behavior

Filters and pagination to always be built in graphql schema unless specified otherwise

**Comment by KarimIO** [comment]
I'm having the same issue. I'm not sure if we have to create custom resolvers to use filters? But either way it's very confusing.

**Comment by semdzh** [comment]
I have the same problem with the latest version. In version 4.1.5 everything works fine.

**Comment by pcriadoperez** [comment]
I upgraded again to 4.1.8, ran `npm install` and now its working again. Not sure what caused the issue or how I solved it.

**Comment by semdzh** [comment]
> I upgraded again to 4.1.8, ran `npm install` and now its working again. Not sure what caused the issue or how I solved it.

I did the same, but still facing this problem.

**Comment by or2e** [comment]
same propblem, only sort in args
![image](https://user-images.githubusercontent.com/33551334/163698137-5ffa22dc-6187-4148-8ea8-7ff4dde94469.png)

**Comment by kalves** [comment]
Hi, I'm facing the same issue. Everything is fine in development mode, but in production only "sort". 

Graphql : 1.7.41
Strapi: 4.1.8

**Comment by geodiv** [comment]
In `/home/yoyo/Documents/my-strapi/node_modules/@strapi/plugin-graphql/server/services/content-api/index.js` there is a call to `pruneSchema` from `@graphql-tools/utils` package which leaves only the **sort** argument in the generated content type schemas. It seems that this happens with the latest version **8.6.8** of `@graphql-tools/utils`. If we force the version **8.6.7** the schemas are generated correctly. I added this in the `package.json`

`"resolutions": {
      "@graphql-tools/utils": "8.6.7"
  }`

**Comment by jonrrivera** [comment]
<img width="1440" alt="Screen Shot 2022-04-18 at 11 15 48 AM" src="https://user-images.githubusercontent.com/18686388/163854426-2bd49cc3-7abc-419e-b19a-09914a1d7260.png">


I continue to get `"Unknown argument \"where\"` on all Queries, unless I use sort

whats going on :(

**Comment by aquadesk** [comment]
I get similar error for login. It lost input params..

**Comment by jonrrivera** [comment]
I am now able to filter other parameters using:

`
  "overrides": {
    "@graphql-tools/utils": "8.6.7"
  }
`

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13150

**Comment by aquadesk** [comment]
@jonrrivera it does solve the issue on the graphql side but 4.1.8 has an issue with frontend side

https://github.com/strapi/strapi/issues/13158
https://github.com/strapi/strapi/issues/13164

so on.. issues are coming
