### ISSUE TITLE
strapi develop --watch-admin , Uncaught ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by buddudevelopers** [strapi/strapi#13147]
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: "@strapi/strapi": "4.1.8",
- Database: sqlite
- Operating system: Ubuntu 21.10

### Describe the bug

Running `npm run strapi develop -- --watch-admin` shows a blank webpage with an error in the js console `Uncaught ReferenceError: __webpack_require__ is not defined`

`Uncaught ReferenceError: __webpack_require__ is not defined
    <anonymous> webpack-internal:///./src/BaseCheckbox/index.js:1
    eval http://164.90.207.180:8000/:59
    js http://164.90.207.180:8000/admin/main.bundle.js:8960
    __nested_webpack_require_791__ http://164.90.207.180:8000/admin/main.bundle.js:8720
    node_modules strapi/admin/node_modules/@strapi/design-system/BaseCheckbox.development.js/</<@http://164.90.207.180:8000/admin/main.bundle.js:8784
    node_modules strapi/admin/node_modules/@strapi/design-system/BaseCheckbox.development.js/<@http://164.90.207.180:8000/admin/main.bundle.js:8787
    webpackUniversalModuleDefinition http://164.90.207.180:8000/admin/main.bundle.js:8698
    node_modules strapi/admin/node_modules/@strapi/design-system/BaseCheckbox.development.js@http://164.90.207.180:8000/admin/main.bundle.js:8700
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    fn http://164.90.207.180:8000/admin/runtime~main.bundle.js:323
    node_modules strapi/admin/node_modules/@strapi/design-system/BaseCheckbox.js@http://164.90.207.180:8000/admin/main.bundle.js:9014
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    fn http://164.90.207.180:8000/admin/runtime~main.bundle.js:323
    webpackUniversalModuleDefinition http://164.90.207.180:8000/admin/main.bundle.js:62348
    node_modules strapi/helper-plugin/build/helper-plugin.development.js@http://164.90.207.180:8000/admin/main.bundle.js:62350
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    fn http://164.90.207.180:8000/admin/runtime~main.bundle.js:323
    node_modules strapi/helper-plugin/build/index.js@http://164.90.207.180:8000/admin/main.bundle.js:64119
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    fn http://164.90.207.180:8000/admin/runtime~main.bundle.js:323
    js http://164.90.207.180:8000/admin/main.bundle.js:98920
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    fn http://164.90.207.180:8000/admin/runtime~main.bundle.js:323
    js http://164.90.207.180:8000/admin/main.bundle.js:99076
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    fn http://164.90.207.180:8000/admin/runtime~main.bundle.js:323
    js http://164.90.207.180:8000/admin/main.bundle.js:99096
    __webpack_require__ http://164.90.207.180:8000/admin/runtime~main.bundle.js:28
    __webpack_exec__ http://164.90.207.180:8000/admin/main.bundle.js:170184
    <anonymous> http://164.90.207.180:8000/admin/main.bundle.js:170185
    webpackJsonpCallback http://164.90.207.180:8000/admin/runtime~main.bundle.js:1204
    <anonymous> http://164.90.207.180:8000/admin/main.bundle.js:1`

### Steps to reproduce the behavior

1. install nodejs 16 on ubuntu 21.10
2. install strapi using the command `npx create-strapi-app@latest my-project --quickstart`
3. stop the strapi server 
4. run it with the watch-admin option `npm run strapi develop -- --watch-admin`
5. See error in the browser console

### Expected behavior

I expected strapi to run on localhost:8000 without any errors

### Screenshots

https://i.ibb.co/BzFSKD6/Screenshot-from-2022-04-18-12-51-39.png

### Additional context

I wanted to try out backend development by creating a plugin however the error still happens even on a fresh install of strapi

**Comment by buddudevelopers** [comment]
ignored by @strapi

**Comment by soupette** [comment]
@buddudevelopers did you solve the issue?
