### ISSUE TITLE
Concurrent Session 

### ISSUE THREAD

**Issue by ASIM-SAMI** [strapi/strapi#13148]
### Required System information

- Node.js version: v14.15.0
- NPM version: 8.3.0
- Strapi version: 4.1.7
- Database: sqllite
- Operating system: windows

### Describe the bug

Hi guys, 

when I logged in to the admin panel and open a new tab/browser i still can logged in from other tab or browser at the same time,

I want if there's user using the account from the browser of his phone, no one can logged in until his logged out

you did a great work with strapi thx.

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
