### ISSUE TITLE
Can't update users in the administration panel

### ISSUE THREAD

**Issue by EGGamer** [strapi/strapi#13141]
## Bug report
There's a bug in the User section of the Admin panel, where I can't edit users (change roles for instance).

### Required System information

- Node.js version: 14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.8
- Database: MySQL
- Operating system: CentOS 8

### Describe the bug

I'd like to go to a user, and be able to change their roles in the Administration panel. But there's a bug where I click on a user and I go to their settings page. But, after a couple of seconds, every field changes with the information of **my** user. If I change any field and hit save, it gives an error. Currently, to change any user's information, I need to change it directly in the database, which is not desirable. (I have attached a video below so that you can see what the error is)

### Steps to reproduce the behavior

1. Go to Settings -> Administration panel -> Users
2. Click on any user.
3. On their settings page, initially you will see the selected user's details. But after a couple of seconds, every field will populate with **your** account's details, instead of the selected user's.
4. Try to change any settings like the email, the roles or the names, and when saving, you will be prompted with an error.

### Expected behavior

When I click on a user to change their settings, all the fields should contain their information, not mine. Also, if I change any field like the email or roles, when saving it should change it correctly.

### Screenshots

A video where you can clearly see the bug:
https://user-images.githubusercontent.com/40073654/163712053-518065e0-fc05-44ef-ab11-b32b4f9e8ab6.mp4

**Comment by derrickmehaffy** [comment]
What browser are you using and what method of storing your user information are you using? (native chrome? some extension like 1password? ect)

**Comment by EGGamer** [comment]
@derrickmehaffy After doing some tests I concluded that the issue is caused by LastPass. This didn't happen previously so I thought it was an issue with Strapi. 

I'll close the issue.
