### ISSUE TITLE
Strapi [v4] css color for relation search unreadable on dark mode.

### ISSUE THREAD

**Issue by dogunbound** [strapi/strapi#13149]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.7
- Database: PostgreSQL
- Operating system: Linux

### Describe the bug

When searching for a specific value in a relation, the typed search query is unreadable on dark mode due to the query text also being dark.

### Steps to reproduce the behavior

1. Create a collection.
2. Create a single type with a reference to the above collection.
3. Enable dark mode.
4. Go to the single type and query something in the relational component.

### Expected behavior

Text is supposed to be a legible light color.

### Screenshots

[Youtube video demonstrating the issue](https://youtu.be/Rfls7meDhBs)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Not a big problem, just a little annoying when you typo.

**Comment by derrickmehaffy** [comment]
Confirmed v4.1.8

**Comment by gu-stav** [comment]
Fixed by https://github.com/strapi/strapi/pull/13291
