### ISSUE TITLE
Unable to Remove Tutorials/Code Examples/Documentations/Blogs section and Join the community links from Home Page

### ISSUE THREAD

**Issue by ravichadda** [strapi/strapi#13144]
### Required System information

- Node.js version:14.15.0
- NPM version:6.14.8
- Strapi version:4.1.7
- Database:Sqlite
- Operating system:Windows 10

### Describe the bug

Hi Team,

I am able to change the Logo, Title, Subtitle, But unable to remove the Sections from Home Page as:

1. Tutorials/Code Examples/Documentations/Blogs
2. Join the community links

### Steps to reproduce the behavior

1. Go to 'Admin Dashboard'
3. Click on 'Stay on the default home page '
4. Scroll down to 'Scroll down the Dashboard, the two containers have links not removed from the dashboard as well '
5. See the screenshot

### Expected behavior
I want to remove the default page links and add our custom UI js component according to the product design theme.

### Screenshots

<img width="1792" alt="Screenshot 2022-04-18 at 1 59 07 PM" src="https://user-images.githubusercontent.com/47782607/163782540-27956d78-c32e-4403-af59-f212ab40dbf1.png">

### Code snippets
<img width="1139" alt="Screenshot 2022-04-18 at 2 15 56 PM" src="https://user-images.githubusercontent.com/47782607/163782857-d90aa74e-c113-4ae3-81c5-9073ac1ba40c.png">

If applicable, add code samples to help explain your problem.

### Additional context
I had successfully done this Home Page customization in Strapi@V3. But the same approach not working in Strapi@V4. Please help us to resolve this issue, its impact on our product delivery and development as well. 

**Take this issue on High Priority.**

**Looking forward to the best solution.**

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13049

**Comment by kgrv** [comment]
There seems to be no solution to remove the links from the home page of the dashboard. Also, this doesn't seem to be a duplicate issue of https://github.com/strapi/strapi/issues/13049

**Comment by salihcodes** [comment]
That's such a crazy feature to get rid of. Is this some ploy to get cheap marketing or what?
