### ISSUE TITLE
I am not able to open Strapi in Iframe

### ISSUE THREAD

**Issue by sanjeetCoder** [strapi/strapi#13156]
## Bug report
I am not able to open Strapi in Iframe. I am trying to open Strapi in React Iframe, but it's not opening.

### Required System information

- Node.js version: 14.15
- NPM version: 6.14.8
- Strapi version: 4.1.8
- Database: Sqlite
- Operating system: Windows

### Describe the bug

While trying to open Strapi inside React Iframe, it's showing refuse to connect. How to make it's embedded.

![image](https://user-images.githubusercontent.com/62275756/164025448-7ba3b3a4-f5cf-4e0f-941f-70a87e190841.png)
### Steps to reproduce the behavior

1. Create a react project
2. Install react-iframe i'e npm install react-iframe 
3. Create a component say Iframe.js
4. Use Iframe and under src , give full path of strapi admin
5. Add route path in app.js

### Expected behavior
It should show strapi under Iframe in browser

### Screenshots
![image](https://user-images.githubusercontent.com/62275756/164025541-c35152bf-7198-49cf-88ba-c2690083ec1c.png)

### Code snippets

import React from "react";
import Iframe from "react-iframe";

const IframeApp = () => {
  return (
      <Iframe
        src="http://21.50.540.559:1337/"
        
        width="100%"
        height="1000px"
        id="myId"
        className="myClassname"
        display="initial"
        position="relative"
        
      />
  );
};

export default IframeApp;

**Comment by shinygang** [comment]
How did you solve this problem? @sanjeetCoder
