### ISSUE TITLE
Sorting by nested relation attribute duplicates entries

### ISSUE THREAD

**Issue by VictorienTardif** [strapi/strapi#13153]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.3.0
- Strapi version: 4.1.8
- Database: mysql
- Operating system: MacOS

### Describe the bug

When sorting entries by an attribute of a related entry, the parent entry is duplicated.

### Steps to reproduce the behavior

1. Create a collection type "Articles" and create some entries.
2. Create a collection type "Article categories" with a many-to-many relation to "Articles" and create some entries.
3. Assign at least 2 "Articles" to the same "Article category".
4. Query "Article categories" sorting them by "Articles" creation date (or anything else): `/api/article-categories?sort=articles.createdAt:ASC`

You will see that each "Article category" is returned as many times as the number of items it contains: 

```
{
  "data": [
    {
      "id": 1,
      "attributes": {}
    },
    {
      "id": 1,
      "attributes": {}
    },
    {
      "id": 1,
      "attributes": {}
    },
    {
      "id": 1,
      "attributes": {}
    },
    {
      "id": 2,
      "attributes": {}
    },
    {
      "id": 3,
      "attributes": {}
    },
    {
      "id": 3,
      "attributes": {}
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 25,
      "pageCount": 1,
      "total": 3
    }
  }
}
```

Pagination is ok though.

### Expected behavior

When querying entities, "Article categories" in this case, I expect each one to be unique.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/11892
