### ISSUE TITLE
GraphQL only accepting sorting filter

### ISSUE THREAD

**Issue by jonrrivera** [strapi/strapi#13150]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.5.0 
- Strapi version: 8.5.0 
- Database: postgres
- Operating system: MacOS

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/graphql` and make any Query, you will notice you can only sort, but not filter, where or anything else
<img width="681" alt="Screen Shot 2022-04-18 at 11 10 47 AM" src="https://user-images.githubusercontent.com/18686388/163853852-c31c327e-16c1-4dd0-ac84-52f2567b9af9.png">

4. See error:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Just noticed this myself while testing another bug, confirmed on v4.1.8

**Comment by marcoautiero** [comment]
I can't reproduce this bug, I can apply filters in my graphql queries

**Comment by Martijn-Schoenmaker-Webbio** [comment]
This is definitely still a bug. I'm on 4.1.9 and it still occurs. The only arguments graphQL gives me on a collectiontype is sort. Nothing is.

**Comment by Martijn-Schoenmaker-Webbio** [comment]
Reinstalling graphql in strapi fixed the issue for me! Like mentioned here https://github.com/strapi/strapi/issues/13157#issuecomment-1109046546
