### ISSUE TITLE
Package subpath './v4' is not defined by "exports"

### ISSUE THREAD

**Issue by RolfVeinoeSorensen** [strapi/strapi#13151]
### Required System information

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.1.8
- Database: PostgreSQL
- Operating system: Debian + MacOs + Centos same error on all

### Describe the bug

Upgrading from 4.1.7 to 4.1.8 causes error when trying to run strapi
`Package subpath './v4' is not defined by "exports"`

1. Update all strapi core, i18n and plugins from 4.1.7 to 4.1.8
2. Remove build and node_modules
3. Run yarn install
4. Run strapi build clean
5. Run strapi
6. See error

### Expected behavior

UUID should not throw error

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Can't reproduce, can you please try deleting your `package-lock.json` and/or `yarn.lock` in addition to your node_modules and try to reinstall again.

**Comment by RolfVeinoeSorensen** [comment]
I have an extension for the permission plugin and it was a require that had been changed which caused the issue..
Thank you for replying I will close the issue.
