### ISSUE TITLE
I found that when deleting SVG files, the delete method implemented by the provider will not be triggered

### ISSUE THREAD

**Issue by NidMo** [strapi/strapi#13154]
### Required System information

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.1.5
- Database: mysql：5.7
- Operating system: window10

### Describe the bug

I found that when deleting SVG files, the delete method implemented by the provider will not be triggered

### Steps to reproduce the behavior

1. Create a local provider
2. upload svg file
3. delete svg file
4. See problem， the delete method not triggered

### Expected behavior

 the delete method triggered, delete svg file

### Code snippets

```
module.exports = {
  init(providerOptions) {
    return {
      upload(file) {
        // upload the file in the provider
        // file content is accessible by `file.buffer`
      },
      uploadStream(file) {
        // upload the file in the provider
        // file content is accessible by `file.stream`
      },
      delete(file) {
         console.log('call delete')
        // delete the file in the provider
      },
    };
  },
};
```

**Comment by NidMo** [comment]
when I delete .png file ,the delete function is work.

**Comment by derrickmehaffy** [comment]
Tested the following providers and they all functioned properly:

- https://github.com/strapi/strapi/tree/master/packages/providers/upload-aws-s3
- https://github.com/strapi/strapi/tree/master/packages/providers/upload-cloudinary
- https://github.com/strapi/strapi/tree/master/packages/providers/upload-local

Didn't test rackspace but we are gonna get rid of that one soon anyway and it's practically impossible to test with.

I'm going to set this as closed until we get more updated reproduction steps or information
