### ISSUE TITLE
Cannot load user permissions pages in dashboard -  Error Cannot read properties of undefined (reading 'allPermissions')

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#13164]
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.1.8
- Database: Postgres
- Operating system: Linux

### Describe the bug

When loading user permissions pages in admin panel I get a blank page and the following error in the console:
```
Cannot read properties of undefined (reading 'allPermissions')
    at ne (main.62556eb3.js:8038:9547)
    at Xu (main.62556eb3.js:7523:54812)
    at _c (main.62556eb3.js:7527:9231)
    at Ac (main.62556eb3.js:7527:992)
    at Jc (main.62556eb3.js:7527:920)
    at fs (main.62556eb3.js:7527:771)
    at $s (main.62556eb3.js:7525:11154)
    at main.62556eb3.js:7523:39609
    at h.unstable_runWithPriority (main.62556eb3.js:7548:3946)
    at Hi (main.62556eb3.js:7523:39387)
```
### Steps to reproduce the behavior

1. Go to /admin/settings/users-permissions/advanced-settings
2. Get a blank page and an error in the console.

### Expected behavior
- Page loads correctly.

**Comment by aquadesk** [comment]
This worked for me but not sure it would for you

replace `v4.1.8` to `4.1.7` in package.json

use `npm ci` instead of `npm i` to install dependencies.

Let me know if this works.

**Comment by phastari** [comment]
I had simular issues with /admin/plugins/upload and /admin/plugins/documentation
removing node_modules, .cache, build and package-lock.json then reinstalling (npm install) solved the issues, I did not have to downgrade to 4.1.7

@aquadesk Thank you!

**Comment by pcriadoperez** [comment]
It happens also when trying to upload files. Will try rebuilding.

**Comment by derrickmehaffy** [comment]
Closing as the comment made by @aquadesk is exactly correct.

**Comment by aquadesk** [comment]
I know this solves the problem that OP is posted but if you use 4.1.8 there possibly a problem with graphql plugin.
so watch out.

**Comment by aquadesk** [comment]
> > I know this solves the problem that OP is posted but if you use 4.1.8, there is possibly a problem with graphql plugin. so watch out.
> > @aquadesk do you have a link to this issue somewhere? Will help folks trying to diagnose their own issue if the above suggestion doesn't work.

I don't have one but I see some already filed

https://github.com/strapi/strapi/issues?q=+4.1.8+graphql+

Solutions suggested in the comments of issues didn't work for me so I am sticking with 4.1.7 for now.
