### ISSUE TITLE
filters parameter doen't work via graphql query

### ISSUE THREAD

**Issue by ahmadjoya** [strapi/strapi#13169]
in the recent version of strapi (4.1.8) the filters paramter in graphql query doen't work. it says Unknown argument \"filters\" on field \"Query.article\" but it was ok in the previous version like: 4.1.1

here is my query
```
query{
  article(filters: { slug: { eq: "test" }}) {
    data {
      id
    }
  }
}
```

and here is the response
```
"error": {
    "errors": [
      {
        "message": "Unknown argument \"filters\" on field \"Query.article\".",
        "locations": [
          {
            "line": 2,
            "column": 11
          }
        ]

```

**Comment by Olli1080** [comment]
Same here. It still works in 4.1.7 but in 4.1.8 the Graphql input IDFilterInput is omitted in introspection and filters in general

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
