### ISSUE TITLE
GraphQL Shadow CRUD enum response not supporting UTF8

### ISSUE THREAD

**Issue by durashere** [strapi/strapi#13165]
### Required System information

- Node.js version: v14.19.1
- NPM version: yarn v1.22.18
- Strapi version: v4.1.8
- Database: PostgreSQL
- Operating system: MacOS

### Describe the bug

Strapi dont response with polish / non-english characters when using Shadow CRUD

### Steps to reproduce the behavior

1. Create content with any non-english character for example ł ą ę ż ź
2. Go to GraphQL playground
3. Run any Shadow CRUD query for response
4. See that response is translated to only english characters

### Expected behavior

Response populated with defined characters

### Screenshots

![image](https://user-images.githubusercontent.com/21038648/164445237-6af9110b-8d59-43ed-9179-5d191e0a3c5e.png)
Database entry using db explorer Beekeeper Studio

![image](https://user-images.githubusercontent.com/21038648/164445659-680ebcba-ccb8-4863-aa52-e7cd4fd46616.png)
console.log()

![image](https://user-images.githubusercontent.com/21038648/164448847-28eb05d9-cc99-4fac-ab92-3c5528fabb4e.png)
GraphQL Playground Shadow CRUD

![image](https://user-images.githubusercontent.com/21038648/164448569-91f18121-7683-4375-aeac-b3b0be7586a9.png)
GraphQL Playground Custom resolver

![image](https://user-images.githubusercontent.com/21038648/164446235-d093b028-4988-437f-9a31-b92aad684002.png)
My PostgreSQL encoding is UTF8

### Code snippets

```javascript
nexus.extendType({
  type: "Query",
  definition(t) {
    t.nonNull.list.nonNull.field("uniqueIngredients", {
      type: "String",
      async resolve() {
        const data = await strapi.db.connection.context.raw(
          'SELECT DISTINCT unit FROM "ingredients"'
        );
        const test = await strapi.entityService.findMany(
          "api::ingredient.ingredient"
        );
        console.log(`file: index.js > line 30 > resolve > test`, test);
        return data.rows.map((item) => item.unit);
      },
    });
  },
}),
```
Custom resolver

```graphql
query {
  ingredients {
    data {
      id
      attributes {
        name
        quantity
        unit
      }
    }
  }
}
```
Shadow CRUD query

When used with custom resolver response is great

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13017

see this comment: https://github.com/strapi/strapi/issues/13017#issuecomment-1101536552
