### ISSUE TITLE
POST multipart/form-data on generated API for file upload

### ISSUE THREAD

**Issue by jiradeto** [strapi/strapi#1316]
**Informations**
Node 8.11.1
npm 5.6.0
The latest version of Strapi
Mongo DB 3.6.5

**What is the current behavior?**
I am trying to create the Mongo document and upload its image simultaneously by using POST API with the `multipart/form-data`.

Let's say I want to create new Product with fields `title`, `price`, `image`, here is the example of my request body of FormData
```
let data = new  FormData();
data.append('title', 'itemA'),
data.append('price', 199),
data.append('photo', {
   uri: photo.uri,
   type: 'image/jpeg', // or photo.type
   name: photos.name
 }); 
```

**Response**
```
{
    "_id": "5b15765878094a5c6165eceb",
    "createdAt": "2018-06-04T17:26:48.377Z",
    "updatedAt": "2018-06-04T17:26:48.389Z",
    "__v": 0,
    "image": null,
    "id": "5b15765878094a5c6165eceb"
}
```
Though there is no error, Strapi created empty record 

**Screenshort**

![image](https://user-images.githubusercontent.com/16756648/40932573-fb0227d0-6858-11e8-836d-a86abb004d59.png)

**What is the expected behavior?**

The server should create record and upload image.  

Is there any work around on this ? 
Thank you in advance.

**Comment by lauriejim** [comment]
Hello @jiradeto !

Actually if you follow the upload process: https://strapi.io/documentation/guides/upload.html#examples

**Step 1** is to create your entity.
**Step 2** is to upload your file and link it to your entity.

Generated API doesn't support form-data request. So you can't create entry with file in the same request.

I transform this issue in _feature request_

**Comment by SerQuicky** [comment]
Hello @lauriejim,

I have the same problem, if the API doesn´t support form-data request, what are the options to send the file to the API? Can I just parse the form data to a json and add the refId to it?

**Comment by Nyeedz** [comment]
I'm facing the same problem, upload file image only works on model user from users-permissions plugin
https://github.com/strapi/strapi/issues/1318#issuecomment-394803982

**Comment by indra-uolles** [comment]
I was able to upload images to model other than user, specifically model "item". My code is messy, so here's my postman screenshot:
![screen shot 2018-06-18 at 08 48 45](https://user-images.githubusercontent.com/5262720/41520170-114414e6-72d5-11e8-8cf0-41e0994f1287.png)

**Comment by siffash** [comment]
Same problem here, but the response I get trying to send a post request to /upload is:
{
	"statusCode": 403,
	"error": "Forbidden",
	"message": "Forbidden"
}
Deployed in heroku.

**Comment by lauriejim** [comment]
@siffash you have to set your header if you are authenticated, or if you want this route open, check permissions in [Roles](http://localhost:1337/admin/plugins/users-permissions/roles) then click on **Public** role. And open **Upload** dropdown and check `upload`.

**Comment by OscarGBeta-Gif** [comment]
Hola buenos dias, estoy intentando enviar formulario con datos y imagenes al servidor (strapi) desde mi frontend con angular, pero solo puedo enviar datos, quisiera que me instruyan como subir las imagenes y los datos a strapi. Gracias

**Comment by kunalkamble** [comment]
@lauriejim how I can get it working for `users-permissions_user`?

I have a user avatar field and which is a Single media type

It throws this error on the console 

`[2020-12-21T10:25:44.346Z] error TypeError: Cannot read property 'associations' of undefined`

![image](https://user-images.githubusercontent.com/1706750/102767502-ac77b080-434d-11eb-8303-6ba644bbfd73.png)

**Comment by kunalkamble** [comment]
@laurenskling NVM, I found the solution.
I was missing a **source**, which was optional.

![image](https://user-images.githubusercontent.com/1706750/102810829-698bfc00-4392-11eb-9ad1-6fc3696787af.png)

**Comment by kunalkamble** [comment]
> I was able to upload images to model other than user, specifically model "item". My code is messy, so here's my postman screenshot:
> ![screen shot 2018-06-18 at 08 48 45](https://user-images.githubusercontent.com/5262720/41520170-114414e6-72d5-11e8-8cf0-41e0994f1287.png)

https://github.com/strapi/strapi/issues/1316#issuecomment-748901562
