### ISSUE TITLE
Graphql filters parameter doesn't filter by date string

### ISSUE THREAD

**Issue by KirillTovpinets** [strapi/strapi#13162]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: v4
- Database: postgress
- Operating system: Windows

### Describe the bug

I try to filter my collection by date field but graphql doesn't filter collection by given date filter.

### Steps to reproduce the behavior

1. Go to 'https://api-dev.metus-cms.com/graphql'
2. Use filter parameter to set up date filter, in this case where:
```
query FilterByDate {
 contents(filters: {
  expiringDate: { eq: "2022-02-02" }
 }) {
 data{
  id
}
```
Returned data ignores date filter and simply returns all records (the same for any operator with date such as 'gt', 'lt', 'gte' end so on.

### Expected behavior

Graphql should filter my collection by given date parameter

### Screenshots

![image](https://user-images.githubusercontent.com/14245565/164228473-3845e732-4e2c-4b81-be78-54c2817c9df8.png)

### Code snippets
```
query FilterByDate{
 contents(filters: {
  expiringDate: { eq: "2010-04-20" }
  }){
  data{
    id
    attributes{
      expiringDate
    }
   }
  }
}
```

**Comment by aquadesk** [comment]
This worked for me but not sure it would for you

replace v4.1.8 to 4.1.7 in package.json

and do this.

rm -rf node_modules .cache build package-lock.json && npm ci && npm run develop
what this command does are

remove node_modules .cache build package-lock.json
use npm ci instead of npm i to install dependencies.
and then npm run develop
Let me know if this works.

**Comment by derrickmehaffy** [comment]
I don't think this one is the same error, I believe this a database filtering issue. Trying to reproduce it now

**Comment by KirillTovpinets** [comment]
Sorry guys, I haven't mentioned the whole version of my strapi, which was 4.1.1. But now I've upgraded version to 4.1.9 and the bug was disappeared. All work as expected. Thanks for reply to this issue. Now this issue can be closed. Thanks a lot

**Comment by derrickmehaffy** [comment]
> Sorry guys, I haven't mentioned the whole version of my strapi, which was 4.1.1. But now I've upgraded version to 4.1.9 and the bug was disappeared. All work as expected. Thanks for reply to this issue. Now this issue can be closed. Thanks a lot

Sure no problem, marking as closed!
