### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token (at main.f878bb6e.js:2:26089)

### ISSUE THREAD

**Issue by sultanfendonus** [strapi/strapi#13167]
Admin panel frontend not working after migrating from 4.1.7 to 4.1.8
Blank page showing with this console error in the browser
`Uncaught SyntaxError: Invalid or unexpected token (at main.f878bb6e.js:2:26089)
`
**Required System information**

- Node.js version: v16.14.2
- NPM version: v8.5.0
- Strapi version: 4.1.8
- Database: PG
- Operating system: Ubuntu 20.04

**Steps to reproduce the behavior**

- Upgraded the system from 4.1.7 to 4.1.8
- Build the project
- After serving via pm2 the backend API working fine but unable to access the login page.

**Expected behavior**
- UI should load.

**Additional context**
If I downgrade to v4.1.7 then it is working fine.
<img width="1504" alt="Screenshot 2022-04-21 at 8 14 18 PM" src="https://user-images.githubusercontent.com/49182623/164477505-492fe369-ac84-4820-8ae2-1414a030572a.png">

**Comment by derrickmehaffy** [comment]
Can you please try following the steps in this: https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#upgrading-the-dependencies

Specifically:
![image](https://user-images.githubusercontent.com/8593673/164517347-1edc1efa-08fd-4ef7-a8b8-67e16dfd9e00.png)

Also be sure you took a look at: 
https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.0.x-to-4.1.8.html

**Comment by sultanfendonus** [comment]
> Can you please try following the steps in this: https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#upgrading-the-dependencies
> 
> Specifically: ![image](https://user-images.githubusercontent.com/8593673/164517347-1edc1efa-08fd-4ef7-a8b8-67e16dfd9e00.png)
> 
> Also be sure you took a look at: https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.0.x-to-4.1.8.html

Thanks for the migration guides. Actually, I found the issue. This was happening for the Cloudflare cache. I purged the cache and it is working fine now.

**Comment by kgrosvenor** [comment]
I can reproduce this, ill try some of the above

**Comment by derrickmehaffy** [comment]
> I can reproduce this, ill try some of the above. I'm using cloudflare too but this usually isn't an issue in other node projects, are both file names the same in the output of the file between versions, is this why? @derrickmehaffy 

That could be part of the cause, CloudFlare didn't update it's cache or wasn't aware it needed to bust it's cache.

**Comment by hsnbsst** [comment]
I'm facing the same problem, I tried all of them but it didn't work. With google chrome and edge web browser, white screen occurs, safari also enters smoothly.

**Comment by kentnek** [comment]
@sultanfendonus please reopen this issue as purging cache only works temporarily.

**Comment by sultanfendonus** [comment]
> @sultanfendonus please reopen this issue as purging cache only works temporarily.

Thanks. I reopened it. Hopefully Strapi team will solve this soon.

**Comment by derrickmehaffy** [comment]
We need more information to reproduce this. @kentnek can you please open a new issue, link to this one, and provide more information that helps with reproduction because at this stage I have a feeling it's an environment issue, not an actual bug.

**Comment by edde746** [comment]
Having this same issue... It's trying to do `1.toFixed` which is causing the issue.

**Comment by luismgl** [comment]
I had this same issue, purging the cache on Cloudflare would only solve it temporarily.

Solved it by disabling the minify options on Cloudflare. It's working now!

**Comment by matepaiva** [comment]
Good to know that the problem is around minification. But it's weird the it only happens with this file. It smells like semicolon, hehe. Maybe you have to add semicolons before minification, because _MAYBE_ without this it is merging two different expressions as one. It's only a guess of mine.

**Comment by BrunoGabrielGodoi** [comment]
I was having the exact same problem. To solve, I disabled cache for my admin page by creating a page rule with "cache level: Bypass". Turning minify off didn't help.

**Comment by yorjaggy** [comment]
Awesome the @BrunoGabrielGodoi solution makes the trick in this issue!

**Comment by yorjaggy** [comment]
Awesome, the @BrunoGabrielGodoi solution makes the trick in this issue!
Thanks

**Comment by dummydamn** [comment]
> I was having the exact same problem. To solve, I disabled cache for my admin page by creating a page rule with "cache level: Bypass". Turning minify off didn't help.

Which file should i add this config?

**Comment by sh13n** [comment]
https://github.com/strapi/strapi/issues/13805#issuecomment-1190288374
https://github.com/strapi/strapi/issues/13805#issuecomment-1229230964

**Comment by AnoirsGit** [comment]
@dummydamn did you find where to change?

**Comment by Poudr** [comment]
but if it's a minification issue, why it's not appears all the time you try to load the app ?

**Comment by Poudr** [comment]
but if it's a minification issue, why it's not appears all the time you try to load the app ?

**Comment by BrunoGabrielGodoi** [comment]
> 

@dummydamn, this config is inside Cloudflare on "Page Rules". If you are using some other CDN there will be, probably, somewhere to disable all cache for that address
