### ISSUE TITLE
Image optimalization breaks WebP animations in Media Gallery

### ISSUE THREAD

**Issue by martincapek** [strapi/strapi#13166]
## Bug report

Media Gallery image optimalization breaks animation in WebP images.

### Required System information

- Node.js version: v16
- NPM version:  v8
- Strapi version: 4.1.8
- Database: PG
- Operating system: macOS

### Steps to reproduce the behavior

1. Go to Media Gallery
2. Upload WebP animation (link for image https://drive.google.com/file/d/1cEpWI3tay4ovhGCgtps-az60QevSSgIw/view?usp=sharing)
3. Animation stop working

### Expected behavior

Animation works even after image is optimized.

### Additional context
If I disable `Size optimalization` it works fine.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/10420

**Comment by martincapek** [comment]
Hi Derrick, I don't think so. I saw #10420 and that issue is about add option to create WebP copies of images. My issue is about broken optimalization of WebP images. Or am I wrong? If yes can you please clarify it. Thanks!
