### ISSUE TITLE
Entity Service is populating a relation, even though: { populate: { products: false } }

### ISSUE THREAD

**Issue by ScyDev** [strapi/strapi#13173]
### Required System information

- Node.js version: v14.17.0
- NPM version: 6.14.13
- Strapi version: 4.1.8
- Database: PostgreSQL 13.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
- Operating system: Ubuntu 20.04

### Describe the bug

Entity Service is populating a relation, even though I explicitly tell it not to and the docs state "The Entity Service API does not populate relations, components or dynamic zones by default".

### Steps to reproduce the behavior

1. Create Category content type
2. Create Product content type
3. Create many-to-many relation between them
4. Override core controllers findOne() action
5. Call API, see Category entity with populated "products" relation

### Expected behavior

The Entity Service not populating relations by default, and especially not if I tell it not to.

### Screenshots

Code:
![image](https://user-images.githubusercontent.com/1307146/164729358-b6176a41-9427-4598-859d-963ee88ced68.png)

Server log:
![image](https://user-images.githubusercontent.com/1307146/164729467-ce126de0-4e97-44a3-a815-25af15047ff3.png)

API call response:
![image](https://user-images.githubusercontent.com/1307146/164729629-a62c1ccf-7e59-421b-9e2b-5be4da4eeb3d.png)

### Code snippets

```
module.exports = createCoreController('api::category.category', ({ strapi }) =>  ({

  async findOne(ctx) {
    const { id } = ctx.params;
    const { query } = ctx;

    // don't populate "products" relation: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/populate.html#advanced-populating
    const opts = {
      populate: {
        products: false
      },
    }

    console.log("fetching categories with custom findOne controller, without populating products relation. opts: ")
    console.log(opts)

    // const entity = await strapi.service('api::category.category').findOne(id, query);
    const entity = await strapi.entityService.findOne('api::category.category', id, opts);
    const sanitizedEntity = await this.sanitizeOutput(entity, ctx);

    return this.transformResponse(sanitizedEntity);
  }

}));
```

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by ScyDev** [comment]
@derrickmehaffy How is this not a bug? The docs say that Entity Service does not populate relations by default. Yet it clearly does, in my example.
