### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by hamzehparsi** [strapi/strapi#13176]
npm 6.14.16
node v16.14.2
windows 10

Building your admin UI with development configuration ...
Admin UI built successfully
[2022-04-24 08:06:52.120] debug: ⛔️ Server wasn't able to start properly.
[2022-04-24 08:06:52.121] error: Could not load js config file C:\Users\837256\my-strapi\node_modules\@strapi\plugin-upload\strapi-server.js: 
Something went wrong installing the "sharp" module

The specified module could not be found.
\\?\C:\Users\837256\my-strapi\node_modules\sharp\build\Release\sharp-win32-x64.node

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
Error: Could not load js config file C:\Users\837256\my-strapi\node_modules\@strapi\plugin-upload\strapi-server.js:
Something went wrong installing the "sharp" module

**Comment by ColinSather** [comment]
I had this issue as well on my Windows 10 machine too. I decided to run Strapi on my Debian Linux server instead. Worked like a charm.

**Comment by vitor-mariano** [comment]
Looks like it's a problem with Sharp getting SO dependencies.
https://github.com/lovell/sharp/issues/3086

In the past I had the same problem to install Sharp on Alpine Linux too.
When I'm using Windows for development, I always prefer to use WSL2. It might be an option for you too.

**Comment by derrickmehaffy** [comment]
you are missing the build tools when you installed node. Reinstall node and when you get to the step which asks you to check the box to install build tools, check it.

You might be able to access the script that does this in your start menu, find the node folder and the script should be listed there.
