### ISSUE TITLE
Boolean field value not visible when is not editable

### ISSUE THREAD

**Issue by HonzaVrkota** [strapi/strapi#13171]
### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.1.8
- Database: sqlite
- Operating system: Windows 10

### Describe the bug

Boolean fields value is not visible, when is disable editing in administration. Value is correctly saved in field, but editor cannot see the value. When editing of the field is enable the value is correctly displayed.

### Steps to reproduce the behavior

1. Create boolean field for content-type
2. Go to content type and change the value of the field.
3. Go to configure the view and change state Editable field to false.
4. Go back to edit and the value of the boolean field is not visible.

### Expected behavior

Cannot edit boolean field, but see the value of the field.

### Screenshots

[Video of this bug](https://www.awesomescreenshot.com/video/8536834?key=9bef87e6866c5f0b207f7475cbc65317
)

**Comment by gu-stav** [comment]
I think this issue should be fixed by upgrading to the latest release. Can you confirm this, @HonzaVrkota ?

**Comment by HonzaVrkota** [comment]
Confirm, this issues is fixed. 🎉
