### ISSUE TITLE
Renaming Collection Type Entry With Many Items "Internal Server Error"

### ISSUE THREAD

**Issue by kimstewartca** [strapi/strapi#13179]
### Required System information

Node.js version: v14.19.1
NPM version: 8.5.5
Strapi version: 4.1.8
Database: AWS RDS Postgres 14.2
Operating system: Ubuntu Server 20

### Describe the bug

Renaming a collection type entry with many items attached to it causes an "Internal Server Error", thus removing all of the pre-existing relationships to that collection type entry.

### Steps to reproduce the behavior

1. Create a collection type "vehicleBody" and entry called "4WD".
2. Create a collection type "vehicle" and attach "4WD" via relationship to the "vehicleBody" for 80,000 entries.
3. Within Strapi 4.1.8 admin panel, rename the collection type vehicleBody entry "4WD" to "AWD".  (or any new name)
4. After a few minutes of waiting receive "Internal Server Error", lose all pre-existing relationships to that collection type entry.

### Expected behavior

Expected the renaming of a collection type entry with many items attached to it to take a few minutes but without "Internal Server Error", and without the loss of data relationships.

### Screenshots

https://i.imgur.com/bRdKZYr.png
https://i.imgur.com/QyQEyw4.png
https://i.imgur.com/udvDTfM.png

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12083
