### ISSUE TITLE
Missing mime-type with API upload breaks Web UI

### ISSUE THREAD

**Issue by hughobrien** [strapi/strapi#13174]
### Required System information

- Node.js version: v14.18.2
- NPM version: 6.14.15
- Strapi version: v4.1.8
- Database: Postgres 11
- Operating system: Azure Kubernetes (Ubuntu 18.04 IIRC)

### Describe the bug

When creating an entry with an image via an API call, certain fields, such as `mime-type` are stored as null. When a browser attempts to view such an entry, or to open the media library, the page fails to load.

```
main.a419461b.js:7896 TypeError: Cannot read properties of null (reading 'split')
```

The file must be deleted via the API to recover access to the admin interface.

I believe this is an issue caused by the uploading client not correctly specifying the mime data (as another client behaves correctly) but the system should reject such input rather than accept and enter this invalid state.

### Steps to reproduce the behavior

1. Create an entry with a form-data encoded image, note that this works correctly and the web interface is happy. ([http tool](https://github.com/httpie/httpie) 
```shell
http --verbose --form -A bearer -a "$token" \
       POST "${endpoint}/api/cms-article-archives" \
       "files.image@~/wp/queries/imgs/foo-bar.jpg" \
       data="$(jo Title=hughtest Summary=hughtest type=text)"
```

2. Attempt the equivalent in Python
```python
import requests
import json
from pprint import pprint

token = "snip"
host = "https://snip"
path = "/api/cms-article-archives"


data = {
    "Title": "hughtest",
    "Summary": "hughtest",
    "type": "text",
}

with open("/home/hugh/wp/queries/imgs/foo-bar.jpg", "rb") as f:
    r = requests.post(
        f"{host}{path}",
        headers={"Authorization": f"Bearer {token}"},
        files=[("files.image", f)],
        data={"data": json.dumps(data)},
    )
```

This returns success
```
shell ❯ bpython  ~/strapi.py
{'data': {'attributes': {'Subtitle': None,
                         'Summary': 'asdf',
                         'Title': 'zzz',
                         'UUID': None,
                         'body': None,
                         'createdAt': '2022-04-23T00:58:59.878Z',
                         'duration_seconds': None,
                         'locale': 'en',
                         'publish_to_app': False,
                         'publish_to_website': False,
                         'publishedAt': '2022-04-23T00:58:59.869Z',
                         'role_model': None,
                         'type': 'text',
                         'updatedAt': '2022-04-23T00:58:59.878Z'},
          'id': 16},
 'meta': {}}
```

3. Attempt to view this newly created entry in the content manager, or to open the media manager at all, note the client side error as above.

note this snippet from querying the endpoint again
```shell
http -A bearer -a "$token" \
        GET "${endpoint}/api/upload/files"
```

```
"hash": "todolist_f0cdb72a2e",
    "ext": ".jpg",
    "mime": null,
    "size": 717.77,
    "url": "https://snip/assets/todolist_f0cdb72a2e.jpg",
    "previewUrl": null,
    "provider": "strapi-provider-upload-azure-storage",
    "provider_metadata": null,
    "createdAt": "2022-04-23T00:59:03.277Z",
    "updatedAt": "2022-04-23T00:59:03.277Z"
  }
```

### Expected behavior

Rejection of invalid input or autocorrection of mime-type 

### Additional context

Please note we have an enterprise agreement so happy to take discussion there.

Thank you.

**Comment by hughobrien** [comment]
Confirming that correcting the python code to set the mime-type results in a successful upload AND a non-broken web UI

**Comment by gu-stav** [comment]
@derrickmehaffy FYI:I've already opened a PR to fix the issue: https://github.com/strapi/strapi/pull/12881, because the problem was reported in https://github.com/strapi/strapi/issues/12761 earlier already. It seems that Alex was not happy with the proposed solution and it seemed as if this existed before, but was removed in v4 intentionally.

I'm not sure about the direction here: both ways (API throws an error if the mime-type is missing and to do our best in the backend to guess the mime-type) seem fine to me, but I'm personally leaning towards the latter, because it prevents mistakes on the side of the user.

**Comment by hughobrien** [comment]
For what it's worth, as a user I'd rather get the error and then correct it client-side over accidentally relying on some magic. Especially if that magic leads to something unexpected further down the line.

But -- I'm probably in the minority so I think the auto option (if not provided) is probably the smoothest from a developer experience point of view.
