### ISSUE TITLE
Media relation format (GET) is not correct

### ISSUE THREAD

**Issue by Nyeedz** [strapi/strapi#1318]
**Informations**
- **Node.js version**: 10.3.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongoDB
- **Operating system**: Windows 10 64bits

**What is the current behavior?**
When i upload an file to my model called "/chamados", with the media field caled "pictures", i'm receiving an wrong response from the server.

**Steps to reproduce the problem**
POST to "/chamados" with multipart/form-data, i'm getting this response

![image](https://user-images.githubusercontent.com/17225811/40944784-671cd3fc-682c-11e8-9d22-bd30329e8277.png)

**What is the expected behavior?**
should return this

![image](https://user-images.githubusercontent.com/17225811/40944747-44838b88-682c-11e8-8fc5-f5985f0e9e25.png)

**observations**

When i POST to /users with the same body/headers and the same field works just fine and when i put manually the pictures from the strapi dashboard works fine as well

**Suggested solutions**

**Comment by lauriejim** [comment]
I will link this issue to this one #1316

**Comment by Nyeedz** [comment]
I'm still can't upload an midea file to my model "chamados"

i have an model called Chamados and an filed called photos, and when i try to post an image for this file show me this response

{
	"_id": "5b51f43b48d68028b477aeb1",
	"createdAt": "2018-07-20T14:39:55.947Z",
	"updatedAt": "2018-07-20T14:58:40.251Z",
	"__v": 0,
	"id": "5b51f43b48d68028b477aeb1",
	"photos": []
}

dont upload an image 


my post 
![image](https://user-images.githubusercontent.com/17225811/43009705-c0ee62b8-8c14-11e8-8340-02e7c209a2f5.png)

![image](https://user-images.githubusercontent.com/17225811/43009720-c942618a-8c14-11e8-8595-ebded2005236.png)


ps: I'm alse tried to post with multipart/form-data Header and dont word

**Comment by Aurelsicoko** [comment]
@Nyeedz You need to use the route `/upload` not `/photos`. Then, thanks to the `ref`, `refId` and `field` parameters, it will attach the uploaded file to the resource.

**Comment by lauriejim** [comment]
You will find more information here https://strapi.io/documentation/guides/upload.html
