### ISSUE TITLE
better-sqlite3 fails to install

### ISSUE THREAD

**Issue by Tragio** [strapi/strapi#13184]
### Required System information

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.1.8
- Database: better-sqlite3
- Operating system: MacOS 12.3.1

### Describe the bug

I'm using an M1 Pro with the latest Node 14 version. Better-sqlite3 fails to install. I already tried to install it locally and globally and it always fails, also tried to clear all cache, package-lock, yarn, and npm, and always the same result. I also tried to revert to 7.4.6 and 7.5.0 and it also fails.

### Screenshots

![CleanShot 2022-04-25 at 09 18 44@2x](https://user-images.githubusercontent.com/5109593/165049089-4624ae4a-1634-41f7-bb9f-f7de4a9786e4.png)

![CleanShot 2022-04-25 at 09 15 10@2x](https://user-images.githubusercontent.com/5109593/165048463-49eb02ac-3492-4b3a-9f5f-040764a034af.png)

**Comment by Tragio** [comment]
Fixed by upgrading npm to 8.7.0.

**Comment by derrickmehaffy** [comment]
you need python 2 as well, if you are on a mac latest updates removed python 2

**Comment by Marc-Roig** [comment]
If anyone needs to install python2 in MacOS:

```bash
brew install pyenv
pyenv install 2.7.18
pyenv global 2.7.18
echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
```

[Source](https://stackoverflow.com/a/67274521)

**Comment by derrickmehaffy** [comment]
@PaulBratslavsky this might help you
