### ISSUE TITLE
Adding same component in plural form corrupts table

### ISSUE THREAD

**Issue by kaij** [strapi/strapi#13182]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.1.2
- Strapi version: 4.1.8
- Database: MariaDB 10.7
- Operating system: Debian

### Describe the bug

The two independently created components "content.Teaser" and "content.Teasers" share the same table. This gives column not found errors when saving data and corrupts data (columns are deleted from the database table).

### Steps to reproduce the behavior

1. Create component with display name "Teaser" (in category "content")
2. Create component with display name "Teasers" (in category "content")
3. Check database tables -> there is only one table "components_content_teasers". 

It seems that "Teasers" is using the wrong table name (probably should be e.g. "teaserss"). Deleting the component "teasers" resolves the problem.

### Expected behavior

Either creation of plural form components is disallowed, or plural forms like "Teasers" map to an own table. 

### Additional context

Workaround: the user can rename the component "Teasers" to "Teaser List" (however this does not solve data corruption in case of spelling errors etc.)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198
