### ISSUE TITLE
firebase phone auth not found

### ISSUE THREAD

**Issue by Manishmg3994** [strapi/strapi#13196]
#request
*need firebase phone auth

### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
