### ISSUE TITLE
GraphQL errors doesn't have code to help for i18n

### ISSUE THREAD

**Issue by MoOx** [strapi/strapi#13195]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.7.0
- Strapi version:
  ```
    "dependencies": {
        "@strapi/plugin-graphql": "^4.1.8",
        "@strapi/plugin-i18n": "4.1.8",
        "@strapi/plugin-users-permissions": "4.1.8",
        "@strapi/provider-email-nodemailer": "^4.1.8",
        "@strapi/strapi": "4.1.8",
        "pg": "^8.7.3"
      },
  ```
- Database:  PostgreSQL 14.2 (inside Docker container Debian 14.2-1.pgdg110+1)
- Operating system: macOS 12.3.1 (21E258)

### Describe the bug

Currently calling GraphQL api doesn't provide error code that can be used to translated safely error message.
Relying on English sentence is not safe as it can be changed.

Here is a answer that doesn't show any codes. 

```json
{
    "errors": [
        {
            "message": "2 errors occurred",
            "extensions": {
                "error": {
                    "name": "ValidationError",
                    "message": "2 errors occurred",
                    "details": {
                        "errors": [
                            {
                                "path": [
                                    "email"
                                ],
                                "message": "email is a required field",
                                "name": "ValidationError"
                            },
                            {
                                "path": [
                                    "password"
                                ],
                                "message": "password is a required field",
                                "name": "ValidationError"
                            }
                        ]
                    }
                },
                "code": "BAD_USER_INPUT"
            }
        }
    ],
    "data": null
}
```

It seems Rest API have this codes.

### Steps to reproduce the behavior

1. Make a GraphQL api call that trigger an error

### Expected behavior

Like Rest API, we should have things like

```json
{
  "id": "Auth.form.error.email.taken"
  "message": "Email already taken"
}
```

**Comment by kasonde** [comment]
Hi @MoOx ,
Error codes are not a part of GraphQL or the GraphQL standard. GraphQL is primarily a query language that utilizes the HTTP protocol for data transfer. That is one of the ways it's fundamentally different from REST.

**Comment by MoOx** [comment]
I don’t see why you don’t want to add error code to errors. It’s the only smart way to ensure stable i18n.
The spec explicitly mention an example where error code are returned in `extensions`

> GraphQL services may provide an additional entry to errors with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to add additional information to errors however they see fit, and there are no additional restrictions on its contents.

[Example № 199](https://spec.graphql.org/October2021/#example-8b658)
```json
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [{ "line": 6, "column": 7 }],
      "path": ["hero", "heroFriends", 1, "name"],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```

Since you are able to add the error message, adding the code in the `extensions` could be done as it’s basically your own translation key for REST response.

Am I missing something ?
