### ISSUE TITLE
Bootstrap API related files in strapi generate command doesn't create exports for plugins

### ISSUE THREAD

**Issue by Mcastres** [strapi/strapi#13192]
### Required System information

- Node.js version: 14
- NPM version: 6.14
- Strapi version: 4.1.8
- Database: Sqlite3
- Operating system: MacOs

### Describe the bug

When generating a content-type for a plugin using the `strapi generate` command. Only the schema.json file is created but not the export that is needed to make it work.

```
├── index.js // This file should import the file that is missing
└── task // Created content-type
    ├── // A file should export the scheme below
    └── schema.json
```

### Steps to reproduce the behavior

1. Run `strapi generate` and create a content-type for an existing plugin.
2. Verify that only a `schema.json` file has been generated

### Expected behavior

Export files should be generated.

**Comment by alexandrebodin** [comment]
Closing as we won't be fixing this and be changing the way we do things :)
