### ISSUE TITLE
Admin JWT Unauthorized on Content API Requests 

### ISSUE THREAD

**Issue by ExtravagantBiscuit** [strapi/strapi#13193]
### Required System information

- Node.js version: v14.19.1
- NPM version: v6.14.16
- Strapi version:  4.1.8
- Database: Sqlite
- Operating system: MacOS (M1)

### Describe the bug

Using the jwt of an authenticated admin user, I am unable to make authenticated requests to the Content API.

I have tested with a superadmin and normal admin with table access enabled both on the Admin Roles and Authenticated Role via the Users and Permissions Plugin.

### Steps to reproduce the behavior

1. Create some content in the Content Manager, or use a blog starter as an example https://github.com/strapi/starters-and-templates/tree/main/packages/starters/next-blog
2. Login in to the admin panel
3. Retrieve the authenticated users JWT using the authenticated network requests in your browser devtools
4. Add the token to the Documentation plugin or HTTP client such as Postman
5. Request the content you created in the Content Manager e.g. http://localhost:1337/api/articles
6. Observe 401 UnauthorizedError

### Expected behavior

An authenticated admin should be able to access the Content API

### Screenshots

![image](https://user-images.githubusercontent.com/104498554/165497970-5b25d4bd-85f1-43c1-963a-7b802d0f691d.png)
![image](https://user-images.githubusercontent.com/104498554/165498050-5ee45715-b7e2-4b13-8a46-08885c42e1cd.png)
![image](https://user-images.githubusercontent.com/104498554/165498105-4e764c09-c481-4e3b-95bd-d17b3b875ed0.png)

### Code snippets

Not applicable

**Comment by vitor-mariano** [comment]
I guess you're confusing admin users, who have access to the Strapi admin panel, with regular users, who have access to API resources.

Admin users are intended to access only the admin resources, not the API itself. You can find them through Settings > Administration Panel > Users

<img width="1075" alt="CleanShot 2022-05-01 at 15 18 35@2x" src="https://user-images.githubusercontent.com/2306588/166159103-ee484026-0095-4fbe-8545-7a8248148cc3.png">

What you're looking for are the users from Users & Permissions plugin, where you can find through Content Manager > Collection Types > Users

<img width="1205" alt="CleanShot 2022-05-01 at 15 21 03@2x" src="https://user-images.githubusercontent.com/2306588/166159156-186d7b64-954e-461e-a6bd-07dc9da5393d.png">

To get the user token, you should send a `POST` request to `/api/auth/local` containing `identifier` and `password`.

``` json
{
  "identifier": "testuser",
  "password": "yourpassword"
}
```

Then you should receive a response like this.

``` json
{
  "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9…",
  "user": {
    …
  }
}
```

> ⚠️ In this case, `identifier` is the user `username`. Don't confuse with `email`. If you want the users to login with their emails, you should register them with `username` the same as `email`.

Try to request `/api/articles` with this generated `jwt` and let me know if it works.

**Comment by ExtravagantBiscuit** [comment]
I understand the distinction; however, the use case I'm targeting _is_ admin users.  I'm trying to migrate a plugin from v3 to v4 that's targeted towards admin users who are using the admin panel, part of this functionality requires the plugin UI to be able to update the 'content'.

I've found this is possible by building new plugin endpoints and using the entity service but this is pretty frustrating when all I want is the CRUD functionality you'd get from the content API.

**Comment by derrickmehaffy** [comment]
This is entirely intended, we split the Admin and Content-API's in v4 and we will not allow them to cross mix ourselves anymore.

It was a security issue in v3 that this could happen. Eventually the plugin that will replace U&P will have some method to use the Admin users as a provider but we won't build this into the current U&P.

In v4 you build specific routes for end-users and admins, you should build the routes for the admins within the admin API.

**Comment by kevinvugts** [comment]
> This is entirely intended, we split the Admin and Content-API's in v4 and we will not allow them to cross mix ourselves anymore.
> 
> It was a security issue in v3 that this could happen. Eventually the plugin that will replace U&P will have some method to use the Admin users as a provider but we won't build this into the current U&P.
> 
> In v4 you build specific routes for end-users and admins, you should build the routes for the admins within the admin API.

Hi @derrickmehaffy,

What would you advise if you are logged in as admin in the back-end and want to  trigger a function that creates localizations for a collection-type item in each language that you've had enabled in the strapi back-end? 

As an admin you do not have access to the /api resources. So what will be the best way, apart from making the route public which is a very bad idea, of doing this?

Any idea? :)

**Comment by derrickmehaffy** [comment]
> > This is entirely intended, we split the Admin and Content-API's in v4 and we will not allow them to cross mix ourselves anymore.
> > 
> > It was a security issue in v3 that this could happen. Eventually the plugin that will replace U&P will have some method to use the Admin users as a provider but we won't build this into the current U&P.
> > 
> > In v4 you build specific routes for end-users and admins, you should build the routes for the admins within the admin API.
> 
> Hi @derrickmehaffy,
> 
> What would you advise if you are logged in as admin in the back-end and want to  trigger a function that creates localizations for a collection-type item in each language that you've had enabled in the strapi back-end? 
> 
> As an admin you do not have access to the /api resources. So what will be the best way, apart from making the route public which is a very bad idea, of doing this?
> 
> Any idea? :)

You build an admin route, I would suggest looking at some of the existing community plugins that are already using this method to get some real world examples.
