### ISSUE TITLE
Stand-alone strapi front end

### ISSUE THREAD

**Issue by MattAurich** [strapi/strapi#1320]
I really like the idea of having a decoupled deployment for the frontend and backend strapi, but am having some trouble decoupling the two when developing. Ideally I would like to have them in two separate repos/directories, but it seems like the admin(frontend) portion of the project is tightly coupled with the backend. When running the package.json scripts, it attempts to crawl up the directory structure looking for the containing backend directory. Has anyone successfully decoupled the two? And/or any recommendations?

**Comment by soupette** [comment]
Hi @MattAurich can you be more specific on the setup you did for decoupling the two in development?

**Comment by MattAurich** [comment]
Hey, @soupette . I moved the admin directory into a separate project/directory and removed the files that are the result of a project initialization like /node_modules (since admin has it's own node_modules it is responsible for) and /build, then:

1. ran npm install

2. updated the pathing for the plugins found on the server (that I kept running)

3. ran the build script found in the package.json

4. used http-server to create a simple server for the files

Though there were some snags along the way and the final solution didn't end up working properly.

**Comment by maturano** [comment]
Question: wouldn't be better that the `/admin` page were the default one for strapi?; instead of `public/index.html`

The dashboard as an independent and isolate system, not as  part of something to be implemented.

I also tried isolate the dashboard. I make it render correctly, but the plugin installation doesn't work.

**Comment by MattAurich** [comment]
The backend is easy enough to separate out and work on independently of the front end. I am starting into a CRUD react app that plays well with the strapi-backend, if it comes far enough along I'll turn it into a public repo

**Comment by soupette** [comment]
@MattAurich we made some boilerplates with react if you want to [check them out](https://github.com/strapi/strapi-examples)

**Comment by MattAurich** [comment]
@soupette this is awesome, thanks!
