### ISSUE TITLE
REST API - unable to update image associated with a model

### ISSUE THREAD

**Issue by rajeshg** [strapi/strapi#13204]
I have a model called Product which has an image. 

![image](https://user-images.githubusercontent.com/143390/165772000-caad02b8-fb2a-4883-9f83-7e8fda7d3061.png)

**Here is what works:**
Create a product with image by using a POST request with FormData
`
{
  "data": {
      'department': ''xyz',
     'name': 'xyz'
  },
  "files": {
      "image": <File Object>
   }
}
`

**What doesn't work:**
Updating product with image by using a PUT request with FormData, using similar data as above
All the data except the image gets updated. 

**Additional info:**
- User has all CRUD permissions
- Image field is set to 'required'
- Documentation doesn't specify whether it's possible to update images, but I don't see any reason why it shouldn't be possible.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
