### ISSUE TITLE
500 error on new user registration with existing username

### ISSUE THREAD

**Issue by de-soul** [strapi/strapi#13205]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.6.0
- Strapi version: v4.1.8-v4.1.9
- Database: sqlite
- Operating system: MacOS

### Describe the bug

I get 500 error when i trying to register user with username already exists on strapi. I expect that strapi will return error callback like: "This username is already taken", but got 500 error on server side: 

```
[develop:backend ] [2022-04-28 18:08:40.039] error: This attribute must be unique
[develop:backend ] ValidationError: This attribute must be unique
[develop:backend ]     at handleYupError (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/utils/lib/validators.js:63:9)
[develop:backend ]     at /Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/utils/lib/validators.js:73:5
[develop:backend ]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[develop:backend ]     at async Object.create (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/services/entity-service/index.js:164:23)
[develop:backend ]     at async Object.<anonymous> (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/services/entity-service/index.js:67:20)
[develop:backend ]     at async Object.register (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:339:20)
[develop:backend ]     at async returnBodyMiddleware (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
[develop:backend ]     at async policiesMiddleware (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
[develop:backend ]     at async /Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/middlewares/body.js:25:7
[develop:backend ]     at async /Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
[develop:backend ]     at async /Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
[develop:backend ]     at async cors (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@koa/cors/index.js:95:16)
[develop:backend ]     at async /Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
[develop:backend ]     at async session (/Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/koa-session/index.js:41:7)
[develop:backend ]     at async /Users/desoul/Develop/nuxt-strapi-radio/backend/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
```

My frontend uses https://strapi-v0.nuxtjs.org/ plugin for my Nuxt 2 application. 
Registration performing by:
```
const data = {
  username: this.form.username,
  email: this.form.email,
  password: this.form.password,
}
this.$strapi.register(data)
```

Error response looks like: 
```
{"data":null,"error":{"status":400,"name":"ApplicationError","message":"An error occurred during account creation","details":{}}}
```

So, this problem occurs after using strapi v4.1.8 and v4.1.9 version, on my past project on strapi v4.1.5 i have no problems with that.

**Comment by dcrendon** [comment]
I am having a similar issue but with a password validation error. It used to return the error in the response but now I get a generic `An error occurred during account creation` and the actual error is logged in the server console:
`
[2022-04-28 19:14:18.351] error: password must be at least 6 characters
ValidationError: password must be at least 6 characters
    at handleYupError (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\utils\lib\validators.js:63:9)
    at C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\utils\lib\validators.js:73:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\services\entity-service\index.js:164:23)
    at async Object.<anonymous> (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\services\entity-service\index.js:67:20)
    at async Object.register (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\plugin-users-permissions\server\controllers\auth.js:339:20)
    at async returnBodyMiddleware (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\middlewares\body.js:25:7
    at async C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\middlewares\logger.js:22:5
    at async C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
    at async cors (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@koa\cors\index.js:95:16)
    at async C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\middlewares\errors.js:13:7
    at async session (C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\koa-session\index.js:41:7)
    at async C:\Users\Bebo\Desktop\Code\texas-woodshed\node_modules\@strapi\strapi\lib\services\metrics\middleware.js:29:5
`

**Comment by pcriadoperez** [comment]
Having a similar issue, I was ignoring username in previous version, now it's asking me for it to be unique and can't edit any users

**Comment by kasonde** [comment]
Please provide steps to reproduce this issue you're facing.

**Comment by derrickmehaffy** [comment]
Closing for now as no steps to reproduce

**Comment by mithenks** [comment]
I can confirm this issue in Strapi 4.1.12

@derrickmehaffy should I report the details here or on a new issue?

**Comment by derrickmehaffy** [comment]
> I can confirm this issue in Strapi 4.1.12
> 
> @derrickmehaffy should I report the details here or on a new issue?

New please
