### ISSUE TITLE
Support HTTP_PROXY when sending webhooks

### ISSUE THREAD

**Issue by callumgare** [strapi/strapi#13209]
### Describe the bug

Our hosting setup requires all outbound connections originating from the container to be to be sent though a [web proxy](https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers). Setting `HTTP_PROXY` to specify that a program should send requests though the specified proxy is [a common convention](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/) and one that we use. Unfortunately Strapi doesn't currently honor this. It appears that this node-fetch request is the source of this: https://github.com/strapi/strapi/blob/bba52c3c8f0cbb465cd10a14eac6bae56e9e4bd1/packages/core/strapi/lib/services/webhook-runner.js#L78

node-fetch doesn't automatically support this convention either (though there is a lot of interest in it to do so https://github.com/node-fetch/node-fetch/issues/79). One way to quickly add support though is use the agent option in node-fetch to pass in an agent from [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent) (as suggested here https://github.com/node-fetch/node-fetch/issues/79#issuecomment-711947354).

### Steps to reproduce the behavior
1. Set the enviroment variable HTTP_PROXY to the domain of the proxy you want to use.
1. Load Strapi and go to \<strapi domain\>/admin/settings/webhooks.
2. Create a webhook to anything.
3. Trigger webhook.
4. Notice the proxy provided by HTTP_PROXY is not used.

### Expected behavior

Strapi to notice that `HTTP_PROXY` is set and use the URL which it is set to to proxy any outgoing webhooks.

### Required System information

This applies to the current version of Strapi (see the link in the second below to the exact point in the Strapi source). We're hosting Strapi in a Debian docker container but as described the issue would be applicable in any enviroments that required the support of HTTP_PROXY.

### Screenshots
![Screenshot from 2022-04-28 10-11-26](https://user-images.githubusercontent.com/346340/165893514-d3c9de69-ca88-4d32-943e-040ce8954209.png)

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
