### ISSUE TITLE
Multiple back end pods in Kubernetes

### ISSUE THREAD

**Issue by deanpeterson** [strapi/strapi#13215]
If I run Strapi on Kubernetes. Can I spin up multiple pods for the back end or will that cause conflicts? 

The forums appear to be a bit of a ghost town so hoping to get some insight if this is possible here.

**Comment by vitor-mariano** [comment]
I left a comment in your topic there with my personal experience running multiple instances of Strapi. I hope it should help you.

https://forum.strapi.io/t/multiple-backend-pods-in-kubernetes/18119/2

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
