### ISSUE TITLE
Basic Responsive UI.   please!

### ISSUE THREAD

**Issue by fadhilx** [strapi/strapi#13213]
Dear Strapi team

please make strapi admin UI to be responsive
all you need to do is 
hide this mf sidebar
![image](https://user-images.githubusercontent.com/15516786/165921716-f9f380a3-f02f-4080-860c-137bd83f321d.png)
and then, put a button somewhere to toggle it
and the the result is 
![image](https://user-images.githubusercontent.com/15516786/165922430-9e71e1c1-42f3-483f-b3ae-daa016323333.png)

**Comment by blackinitial** [comment]
yeah, need responsive on mobile

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Comment by dominikjasek** [comment]
I created a patch which makes it at least little bit more usable for users on phone. It looks still ugly, however IMHO better than current strapi non-responsive version.


https://user-images.githubusercontent.com/48070343/199593462-1005f7f4-8ac3-43a2-8a01-76e1a6926bf4.mp4

Feel free to use it: https://gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed

**Comment by kubarazny** [comment]
> I created a patch which makes it at least little bit more usable for users on phone. It looks still ugly, however IMHO better than current strapi non-responsive version.
> 
>  Monosnap.screencast.2022-11-02.21-05-19.mp4 
> 
> Feel free to use it: https://gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed

How to apply this patch?

**Comment by kubarazny** [comment]
+1 we need this:(

**Comment by dominikjasek** [comment]
> > I created a patch which makes it at least little bit more usable for users on phone. It looks still ugly, however IMHO better than current strapi non-responsive version.
> > Monosnap.screencast.2022-11-02.21-05-19.mp4
> > Feel free to use it: [gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed](https://gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed)
> 
> How to apply this patch?

use [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by kubarazny** [comment]
> > > I created a patch which makes it at least little bit more usable for users on phone. It looks still ugly, however IMHO better than current strapi non-responsive version.
> > > Monosnap.screencast.2022-11-02.21-05-19.mp4
> > > Feel free to use it: [gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed](https://gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed)
> > 
> > 
> > How to apply this patch?
> 
> use [patch-package](https://www.npmjs.com/package/patch-package)

it's not working now

![image](https://github.com/strapi/strapi/assets/19205232/14c222dd-4030-4eb6-a313-0e4e974e2539)
