### ISSUE TITLE
Lifecycles are not called when on relations on page load of parent collection

### ISSUE THREAD

**Issue by oriooctopus** [strapi/strapi#13216]
## Bug report

Let's say I have collection A with relation of collection B. If I go to the content page for collection A I expect 4 things to happen:
1. The data for collection A will load
2. The lifecycles for Collection A will run
3. The relevant data for collection B will load (since collection A has a relation field for collection B)
4. The lifecycles for collection B will run

Item number 4 does not happen. I think that it should, and I'll illustrate why with the following problem I'm having:

On collection B there is a field called `internalLabel`. This field is blank. and non-editable by the user. Its value is filled in dynamically during the `afterFind` lifecycles. 

Here's where the problem comes in. The field for the entry title of collection B is `internalLabel`. Because item 4 is not happening, when I load collection A the value of `internalLabel` is blank, meaning that I have no idea what the relation is. Take a look at this video:

https://user-images.githubusercontent.com/20331238/166104592-3a94ad7a-183c-4066-af23-8b32aa41da72.mp4

As you can see, when I click the select component, the lifecycles for collection B do actually run and `internalLabel` is actually populated. However, after I save and the page reloads, the data for collection B loads but the lifecycles for collection B do not. This is what causes the field to go blank after save.

### Required System information

node 14.18.1
npm 6.14.15
strapi 4.1.7
postgres 
macOS

### Additional context

I would argue that if the lifcycles run when we expand the select component, they should also run on page load

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Comment by CleberRossi** [comment]
@oriooctopus Have you fixed this? Or found a way of fixing it? I am running thru the same problem
