### ISSUE TITLE
Webhook does not trigger any event for related entries

### ISSUE THREAD

**Issue by jonadeline** [strapi/strapi#13214]
## Bug report
When updating a relation in an entry, the webhook doesn't trigger any `entry.update` event for the related entry.

### Required System information

- Node.js version: 16.3.1
- NPM version: 8.1.2
- Strapi version:4.1.8
- Database: SQLite
- Operating system: macOS Monterrey

### Steps to reproduce the behavior

1. Create a collection type with a many to many relation with an other collection
2. Enable the webhook events on entry (tick all the checkbox on the entry line) - we can use https://hookbin.com/ for testing purposes. 
3. Create an entry of this new collection type
4. Update this entry adding a relation to the other collection.
5. Check the events triggered by the webhook

### Expected behavior

I expect an event to be triggered not only for the entry I just modified directly in Strapi but also for the related entry.

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
