### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toggleNotification')

### ISSUE THREAD

**Issue by evle** [strapi/strapi#13222]
### Required System information

- Node.js version: 14.16.2
- NPM version: 8.5.0
- Strapi version: 4.1.7
- Database: postgres
- Operating system: Centos / MacOS

### Describe the bug

Document (Swagger) plugin not working

### Steps to reproduce the behavior

1. Install document plugin
2. Click `documents` on Strapi admin
3. Showing a blank page 
4. See error in chrome console, **TypeError: Cannot read properties of undefined (reading 'toggleNotification')**

### Expected behavior

show Swagger document page.

**Comment by derrickmehaffy** [comment]
Delete your node_modules and any of the following if they exist:
- build
- .cache
- yarn.lock
- package-lock.json

Make sure you are only installing the Strapi v4 packages (excludes community packages), meaning all Strapi official v4 packages start with `@strapi/*`. So in your case `@strapi/plugin-documentation`

Reinstall your node_modules, rebuild the admin panel, and try running again.

Respond back if this doesn't work and I will reopen the issue.

**Comment by evle** [comment]
> Delete your node_modules and any of the following if they exist:
> 
> * build
> * .cache
> * yarn.lock
> * package-lock.json
> 
> Make sure you are only installing the Strapi v4 packages (excludes community packages), meaning all Strapi official v4 packages start with `@strapi/*`. So in your case `@strapi/plugin-documentation`
> 
> Reinstall your node_modules, rebuild the admin panel, and try running again.
> 
> Respond back if this doesn't work and I will reopen the issue.

Hi @derrickmehaffy, thanks for help, I got the same error again after build. Before build, I have removed node_modules, .cache, build and *.lock.

My document plugin version:  "@strapi/plugin-documentation": "^4.1.8",

<img width="762" alt="image" src="https://user-images.githubusercontent.com/3981092/166403686-46c695cc-b872-492b-8e74-6535f6b8f788.png">

**Comment by gu-stav** [comment]
@derrickmehaffy I was able to reproduce the issue. It doesn't happen with our development setup, but with a clean Strapi installation as an end-user. I've pinned down the root cause, but I don't understand yet, why it is happening and will need to talk to soupette about it next week.

**Comment by evle** [comment]
hi, @gu-stav & @derrickmehaffy ,  I think this issue caused by dependency versions mismatch. After check yarn.lock, I downgrade from **@strapi/helper-plugin: 4.1.9**  to  **@strapi/helper-plugin: 4.1.7** and it works well now.

**Comment by derrickmehaffy** [comment]
I'll set the issue to the content squad @gu-stav but if this belongs to expansion feel free to move it.

**Comment by renegadevi** [comment]
I experience same error message.. but with 4.1.9. Using docker with nginx. I downgraded from 4.1.9 to 4.1.8 and it worked again.

**Comment by eveningforgery** [comment]
Same issue on 4.1.11, clean install on GCP and postgres

**Comment by am2222** [comment]
The same issue with latest version. I deploy it on a clean machine. Also it only happens in documentation page

**Comment by eliasleyton** [comment]
Same issue here.

**Comment by gu-stav** [comment]
Hello everybody. We moved this issue into one of our next sprints. That means we are going to start working on a fix in approx. 2 weeks.

**Comment by frejandreassen** [comment]
Same issue here. @strapi/helper-plugin version 4.1.11
Trying to downgrade to version 4.1.7 and 4.1.8 but receive other errors (dependancy related?)

**Comment by danielehrhardt** [comment]
same 
![image](https://user-images.githubusercontent.com/19570043/173187817-6e22df2f-02c4-45ea-9d47-baf09131ae7c.png)

**Comment by frejandreassen** [comment]
> Same issue here. @strapi/helper-plugin version 4.1.11 Trying to downgrade to version 4.1.7 and 4.1.8 but receive other errors (dependancy related?)

Resolved: Looked closely at the guide at https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html and made sure to add yarn.lock to the .gcloudignore file. Now it works on Google App Engine.

**Comment by emiller12** [comment]
Hello, I am also getting the same error. It feels like it is broader than the swagger plugin that the OP mentioned, as I am not using that plugin at all.

For me it doesn't seem to matter what versions I use for the `@strapi/*` dependencies (currently on 4.1.12 but have tried downgrading to the various versions mentioned in this thread)... The problem seems to show up after the 2nd `strapi build` after a clean install. Clearing everything (node_modules, lock file, build dir and cache dir) and re-installing fixes it for the first `strapi build` after the clean out... but then it comes back again after a subsequent `strapi build` and then get that same console error in the browser at admin runtime. 

`TypeError: Cannot read properties of undefined (reading 'toggleNotification')`

If I do `strapi develop` after doing a complete clean out as described above, then it works... and subsequent `strapi develop` runs also work... But as soon as I do a single `strapi build` after having previously done a `strapi develop` the error comes back... and then trying to run `strapi develop` again after the build also then shows the same error in the browser when trying to run the admin app.

It's pretty frustrating, was not expecting to run into something like this out of the box.

Hopefully the above info can help you with your investigation @gu-stav & @derrickmehaffy 

If you get a chance, I'm sure everyone on this thread would appreciate an update on how the team are going with finding fix :)

**Comment by baremetals** [comment]
I had this same issue. I deleted the package.lock and send the build to app engine and it worked. put the yarn.lock in .gitignore the .gcloudignore does not work well sometimes.

**Comment by gu-stav** [comment]
Hello everybody, we have decided to prioritize this issue. 🚀 

It is not yet fully clear to me, what happens. You are right: it doesn't have anything to do with your plugin or an actually missing method, but with the way we bundle the whole application.

Could you do me a favor and try to replace the following file:

`node_modules/@strapi/admin/webpack.alias.js`

with

```js
'use strict';

const path = require('path');

const alias = [
  'whatwg-fetch',
  '@fortawesome/fontawesome-svg-core',
  '@fortawesome/free-solid-svg-icons',
  '@strapi/design-system',
  '@strapi/icons',
  'date-fns',
  'formik',
  'history',
  'immer',
  'lodash',
  'moment',
  'qs',
  'react',
  'react-copy-to-clipboard',
  'react-dnd',
  'react-dnd-html5-backend',
  'react-dom',
  'react-error-boundary',
  'react-fast-compare',
  'react-helmet',
  'react-is',
  'react-intl',
  'react-redux',
  'react-router',
  'react-router-dom',
  'react-virtualized',
  'react-select',
  'redux',
  'reselect',
  'styled-components',
  'yup',
];

module.exports = alias.reduce(
  (acc, curr) => {
    acc[`${curr}$`] = require.resolve(curr);

    return acc;
  },
  {
    'react-select/animated': require.resolve('react-select/animated'),
    'react-select/async': require.resolve('react-select/async'),
    'react-select/async-creatable': require.resolve('react-select/async-creatable'),
    'react-select/base': require.resolve('react-select/base'),
    'react-select/creatable': require.resolve('react-select/creatable'),
    '@strapi/helper-plugin': require.resolve('@strapi/helper-plugin'),
    ee_else_ce: path.resolve(__dirname),
  }
);
```

and try to re-run `yarn build` to see if that fixes the issue for you?

**Comment by danielehrhardt** [comment]
> ```js
> 'use strict';
> 
> const path = require('path');
> 
> const alias = [
>   'whatwg-fetch',
>   '@fortawesome/fontawesome-svg-core',
>   '@fortawesome/free-solid-svg-icons',
>   '@strapi/design-system',
>   '@strapi/icons',
>   'date-fns',
>   'formik',
>   'history',
>   'immer',
>   'lodash',
>   'moment',
>   'qs',
>   'react',
>   'react-copy-to-clipboard',
>   'react-dnd',
>   'react-dnd-html5-backend',
>   'react-dom',
>   'react-error-boundary',
>   'react-fast-compare',
>   'react-helmet',
>   'react-is',
>   'react-intl',
>   'react-redux',
>   'react-router',
>   'react-router-dom',
>   'react-virtualized',
>   'react-select',
>   'redux',
>   'reselect',
>   'styled-components',
>   'yup',
> ];
> 
> module.exports = alias.reduce(
>   (acc, curr) => {
>     acc[`${curr}$`] = require.resolve(curr);
> 
>     return acc;
>   },
>   {
>     'react-select/animated': require.resolve('react-select/animated'),
>     'react-select/async': require.resolve('react-select/async'),
>     'react-select/async-creatable': require.resolve('react-select/async-creatable'),
>     'react-select/base': require.resolve('react-select/base'),
>     'react-select/creatable': require.resolve('react-select/creatable'),
>     '@strapi/helper-plugin': require.resolve('@strapi/helper-plugin'),
>     ee_else_ce: path.resolve(__dirname),
>   }
> );
> ```

works for me

**Comment by emiller12** [comment]
Hi @gu-stav 

I just tried replacing the contents of `node_modules/@strapi/admin/webpack.alias.js` as requested and that seems to do the trick 🎉 

I can now run two+ builds in a row and not get the `toggleNotification` error when running the admin ui.

Good that it seems like potentially a simple fix for you guys 😃

**Comment by edoardo-bluframe** [comment]
@emiller12 Simple **now**

I am imagining them running around for **days** trying to figure how to fix it till they found this - really **amazing** - solution?? :rofl:

**Comment by emiller12** [comment]
@gu-stav just an FYI... I have since installed the documentation plugin into my project, and I found that even with the your fix suggested above pasted into my node_modules folder I was getting a different error visiting `http://localhost:3000/admin/plugins/documentation`. This new error was:
```
No QueryClient set, use QueryClientProvider to set one
```

However I found that using the bellow content in that file instead seemed to fix both errors (the toggleNotification one and the one above):

```javascript
'use strict';

const path = require('path');

const alias = [
  'object-assign',
  'whatwg-fetch',
  '@fortawesome/fontawesome-svg-core',
  '@fortawesome/free-solid-svg-icons',
  '@strapi/design-system',
  '@strapi/icons',
  'date-fns',
  'formik',
  'history',
  'hoist-non-react-statics',
  'immer',
  'invariant',
  'lodash',
  'moment',
  'qs',
  'react',
  'react-copy-to-clipboard',
  'react-dnd',
  'react-dnd-html5-backend',
  'react-dom',
  'react-error-boundary',
  'react-fast-compare',
  'react-helmet',
  'react-is',
  'react-intl',
  'react-redux',
  'react-router',
  'react-router-dom',
  'react-virtualized',
  'react-select',
  'redux',
  'reselect',
  'styled-components',
  'yup',
];

module.exports = alias.reduce(
  (acc, curr) => {
    acc[`${curr}$`] = require.resolve(curr);
    return acc;
  },
  {
    'react-select/animated': require.resolve('react-select/animated'),
    'react-select/async': require.resolve('react-select/async'),
    'react-select/async-creatable': require.resolve('react-select/async-creatable'),
    'react-select/base': require.resolve('react-select/base'),
    'react-select/creatable': require.resolve('react-select/creatable'),
    '@strapi/helper-plugin': require.resolve('@strapi/helper-plugin'),
    ee_else_ce: path.resolve(__dirname),
  }
);

```

**Comment by gu-stav** [comment]
@emiller12 Thank you - that is an interesting observation. The only difference I see you having `hoist-non-react-statics` still in the list of aliases. Can you confirm this makes the difference for the error you see?

Unfortunately I'm not able to reproduce it yet ...

**Comment by exmozz** [comment]
@gu-stav hi! I've fixed the issue with toggleNotification using your suggested webpack.alias.js file, but I've got same error "No QueryClient set, use QueryClientProvider to set one".

I've got this error only on "User and Permissions Plugin" Settings pages (Roles, Providers, Email Templates, Advanced Settings).

**Comment by DitoCahyaPratama** [comment]
@emiller12 hi! i've replace webpack.alias.js using your suggested, but I've got same error "No QueryClient set, use QueryClientProvider to set one".

I've got this error only on Media page, "User and Permissions Plugin" Settings pages (Roles, Providers, Email Templates, Advanced Settings).

**Comment by gu-stav** [comment]
@exmozz @DitoCahyaPratama Thanks for the reports - I'll look into that today. So far I haven't found a reproduction for it. You can follow along / test the progress in this PR: https://github.com/strapi/strapi/pull/13606

**Comment by exmozz** [comment]
@gu-stav one more thing that could help: I've got this problem only on one deployment to webhosting throught cPanel, were permissions are limited (no sudo access, for example).
Thank you!

**Comment by DitoCahyaPratama** [comment]
@gu-stav Hi, i found the solution, i add react-query in aliasExactMatch array and error "No QueryClient set, use QueryClientProvider to set one". is not show again

**Comment by gu-stav** [comment]
@DitoCahyaPratama Thanks for the confimation. I figured that out too (you can check the PR: https://github.com/strapi/strapi/pull/13606). I think with that we are on a good path to resolve the whole issue with the next release 🚀

**Comment by gu-stav** [comment]
Hello again everybody. We have released version `4.2.1-alpha.0` which contains the fix done in https://github.com/strapi/strapi/pull/13606 to properly test it in real-world scenarios. It does not contain anything else, so it should be safe to install.

If you could give it a run and report back, if you experience any problems or if this problem seems to be fixed for you, that would be awesome.

**Comment by mtahirgulzar** [comment]
> 

same issue is there is any solution?

**Comment by gu-stav** [comment]
@mtahirgulzar Which version of Strapi are you on?
