### ISSUE TITLE
REST API - unable to update image associated with a model

### ISSUE THREAD

**Issue by rajeshg** [strapi/strapi#13223]
### Required System information

- Node.js version: v16.14.2
- NPM version: v8.7.0
- Strapi version: v4.1.9
- Database: Postgres v13.6 (on heroku)
- Operating system: linux (heroku basic dyno)

### Describe the bug
I am unable to update an image associated with a model. i.e., PUT request on a model doesn't update the image (other properties on the model get updated without issue)

If I have a model called Product which has an image.
![image](https://user-images.githubusercontent.com/143390/166334200-22ee114d-3195-41b0-89d2-f58c4023ed79.png)
**Here is what works:**
Create a product with image by using a POST request with FormData
{ "data": { 'department': ''xyz', 'name': 'xyz' }, "files": { "image": <File Object> } }

**What doesn't work:**
Updating product with image by using a PUT request with FormData, using similar data as above
All the data except the image gets updated.

### Steps to reproduce the behavior

1. Create a model with an image
2. Send POST request to create one object of that model using API (example: product with image gets created with id 1)
3. Send PUT request to update the image (example: update image and price on the model with id 1 above)

### Expected behavior

Image gets updated

### Screenshots
Provided above.

### Code snippets

```javascript
const onSubmit = (data, store, token) => {
    const formData = new FormData()
    let bodyData = {
      name: data.name,
      price: data.price === "" ? null : data.price,
      description: data.description,
      department: data.department,
      catalog: {id: Number(data.catalog)},
      product_category: {id: Number(data.productCategory)},
      store: {id: store.id},
    }
    formData.append("data", JSON.stringify(bodyData))
    if (data.image.length > 0) {
      formData.append("files.image", data.image[0], data.image[0]?.name)
    }
    axios
      .put(getStrapiURL("/api/products/" + product.id), formData, {
        headers: {
          "Content-Type": "multipart/form-data",
          Authorization: `Bearer ${token}`,
        },
      })
      .then(function (response) {
        setSubmitError(null)
        router.push("/admin/products/")
      })
      .catch(function (error) {
        setSubmitError(error.message)
      })
}
```

### Additional context
User has all CRUD permissions
Image field is set to 'required'
Documentation doesn't specify whether it's possible to update images, but I don't see any reason why it shouldn't be possible.

**Comment by rajeshg** [comment]
This is previous reported in #13204

**Comment by derrickmehaffy** [comment]
Thank you for properly filling out the bug report but this isn't really a bug but more of a usage question

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
