### ISSUE TITLE
HTTP/2 is not supported

### ISSUE THREAD

**Issue by sean-rallycry** [strapi/strapi#13224]
### Required System information

- Node.js version:  v14.19.1
- NPM version:  v8.3.1
- Strapi version:  v4.1.8
- Database: Postgres
- Operating system:  Google Cloud Run

### Describe the bug

When deployed with HTTP/2 enabled, the Strapi application does not fall back to HTTP/1.1

### Steps to reproduce the behavior

1. Start the application with `yarn develop` or `yarn start`
2. In terminal, `$ curl -i --http2-prior-knowledge http://localhost:1337`
---> Result:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
```

### Expected behavior

HTTP/2 request should fallback to HTTP/1.1 and return data as normal

### Code snippets

I believe that if the following line is updated to require `http2-wrapper` as a shim, then the issue will be immediately resolved without further impact to the app.
https://github.com/sean-rallycry/strapi-rc/blob/master/packages/core/strapi/lib/services/server/http-server.js#L3

http2-wrapper: https://www.npmjs.com/package/http2-wrapper

### Additional context

Why do I care?  

We've discovered that there is a limitation in Google Cloud Run of 32MB for requests when running HTTP/1.1, which is a major issue when attempting to upload large files to the media plugin.

The solution is to update the deployment to run HTTP/2, which uncaps the maximum request sizes, but this breaks the Strapi deployment due to the issue noted above (traffic does not return at all due to incorrect response).  Adding http2-wrapper should fix the local curl and also the deployed behavior in HTTP2 mode.

Setting the v4 configuration values to increase the max upload size as described in the documentation is insufficient to resolve this issue because the request max size is being limited by the hosting layer on Google.

*my apologies for bug-reporting what is truly an enhancement... the user voice board would have been insufficient for this level of detail.

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Comment by filson14-mq** [comment]
Hi @sean-rallycry @derrickmehaffy 

Nice work with figuring out the solution. Is this feature considered to be done somwhen? I can't see it on the roadmap yet it's not done either ;)
