### ISSUE TITLE
Image-Upload: Dimensions of animated GIF are missing

### ISSUE THREAD

**Issue by AndreasFaust** [strapi/strapi#13230]
### Required System information

- Node.js version: v16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.1.9
- Database: MariaDB
- Operating system: Mac OSX 12.3.1

### Describe the bug

When uploading an animated GIF, its dimensions are missing. 
The dimensions therefore cannot be requested via GraphQL.

### Steps to reproduce the behavior

1. Go to Media Library
2. Upload animated GIF
3. Check "DIMENSIONS": There is nothing to see

### Expected behavior

Width and Height of an image are are shown at DIMENSIONS and can be requested. 

### Screenshots
<img width="812" alt="Bildschirmfoto 2022-05-03 um 19 00 18" src="https://user-images.githubusercontent.com/15075587/166502832-48b77a6a-940e-42e3-b9aa-1e4c194bb05d.png">

**Comment by 99michel99** [comment]
They are missing for .webm files as well

**Comment by lexa18** [comment]
Also missing for .svg. 
Before version 4.0.8 everything worked fine.
