### ISSUE TITLE
refactor: Remove unneeded passing parameter `asset` to `useUpload`

### ISSUE THREAD

**Issue by MichaelEvtushenko** [strapi/strapi#13238]
As the title says, [useUpload](https://github.com/strapi/strapi/blob/master/packages/core/upload/admin/src/hooks/useUpload.js#L37) doesn't accept any argument, so [passing](https://github.com/strapi/strapi/blob/39047e9f8476c435d12f5bf58d664d925a9adb35/packages/core/upload/admin/src/components/AssetCard/UploadingAssetCard.js#L32
) `asset` totally redundant and confusing to me personallly.

**Comment by gu-stav** [comment]
Thank you for opening the issue. I've realized the same in the last couple of days - the argument will be gone with the release of folders in the media library.
