### ISSUE TITLE
Admin Login always redirect to register

### ISSUE THREAD

**Issue by sidharthv96** [strapi/strapi#1324]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.9
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
Even after registering an admin user, if I try to login again or from incognito, it redirects again to the register page.
The flow works fine from my local dev environment. (MacOS) 

**Steps to reproduce the problem**

`strapi new testapp
`
Go to localhost:1337/admin/
It should redirect to registration page.
Create a new account.

Open Incognito
Go to localhost:1337/admin/
It will again open the registration page.
After registering, If we log out, we can sign in to the old account. 

**What is the expected behavior?**

In Incognito, the user should be shown login page.

**Suggested solutions**
Plugin initialising problem at the frontend.
`/users-permissions/init` is returning `{"hasAdmin":true}`
And second user is being registered as a normal user and not Admin user.

[Test](http://app.corrazone.com)

**Comment by jdutchak** [comment]
this link has a fix that worked for me
https://github.com/strapi/strapi/issues/1235

**Comment by lauriejim** [comment]
Fixed here https://github.com/strapi/strapi/pull/1222.
Please follow the issue template message. You don't try to search on closed issue.
