### ISSUE TITLE
[4.2.0-beta.2] `createCoreController` type definition issues

### ISSUE THREAD

**Issue by joshjung** [strapi/strapi#13241]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.5.5
- Strapi version: 4.2.0-beta.2
- Database: postgres
- Operating system: Mac OSX

### Describe the bug

Heads up there is an issue with the `createCoreController` type in 4.2.0-beta.2:

The definition is:

`export function createCoreController(uid: string, cfg?: ControllerConfig = {}): () => Controller;`

However, this does not allow you to pass a function, which is necessary to receive the strapi object. For example, you cannot do the following because TypeScript sees it as a type collision:

```
export default factories.createCoreController('api::content.content', ({strapi}) => ({
  async find(ctx: Context): Promise<Response> {
    const { query } = ctx;

    const { results, pagination } = await strapi.service(uid).find(query);
    const sanitizedResults = await this.sanitizeOutput(results, ctx);

    return this.transformResponse(sanitizedResults, { pagination });
  },
...
```

However, the javascript code for `createCoreController` clearly allows you to accept a function as the `cfg`:

```
let userCtrl = typeof cfg === 'function' ? cfg({ strapi }) : cfg;
```

_Note! The same issue exists with `createCoreService`_

_Note 2! The return type is also incorrect for `createCoreController` and `createCoreService`._

**Comment by marcoautiero** [comment]
Fixed in https://github.com/strapi/strapi/pull/13289
