### ISSUE TITLE
GraphQL `filters` not working with Components

### ISSUE THREAD

**Issue by reimertz** [strapi/strapi#13248]
### Required System information

- Node.js version: v14.19.1
- NPM version: 0.39.1
- Strapi version: 4.1.9
- Database: sqlite and postgres
- Operating system: macOS 12.3.1 (21E258)

### Describe the bug

I am trying to use GraphQL `filters` functionality  over component values. Sadly, components are not included in the generated GraphQL schema. 

### Steps to reproduce the behavior

1. Create a new collection named Test.
2. Create a new component name Test.
3. Add a 'hello' string field to the Test component 

If all went well you should see this schema

```
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "singularName": "test",
    "pluralName": "tests",
    "displayName": "Test"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "test": {
      "displayName": "Test",
      "type": "component",
      "repeatable": false,
      "component": "test.test",
      "required": true
    }
  }
}
```

4. add a new entry to the Test collection and set hello to "yolo".
5. open localhost:1337/graphql and run below query

```
{
  tests (filters: {hello :{ eq: "yolo"}}){
    data {
      attributes {
        test {
          hello
        }
      }
    }
  }
}
```
6. See error

### Expected behavior

To have the test entry returned. 

### Screenshots
<img width="841" alt="test collection" src="https://user-images.githubusercontent.com/625287/167027589-74cdb8aa-5c8b-4b6e-9584-35b8d35eded9.png">

<img width="1320" alt="graphql" src="https://user-images.githubusercontent.com/625287/167027596-eaf4f654-dd42-400c-b455-422256c42b17.png">

**Comment by Convly** [comment]
Fixed in https://github.com/strapi/strapi/pull/13572
