### ISSUE TITLE
I got a react error when click "Add a new language"

### ISSUE THREAD

**Issue by spksoft** [strapi/strapi#1325]
**Informations**
- **Node.js version**: v.8.4.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: Mongodb
- **Operating system**: MacOS

**What is the current behavior?**
I get a blank page when click "Add a new language" inside Plugin -> Settings Manager -> Global Settings -> languages. When I call Chrome dev tools I got a error log below.
```
main.js:16 Error: Minified React error #254; visit http://reactjs.org/docs/error-decoder.html?invariant=254&args[]=value0 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at n (main.js:11)
    at n (main.js:16)
    at gt (main.js:16)
    at c (main.js:16)
    at h (main.js:16)
    at main.js:16
    at u (main.js:16)
    at l (main.js:16)
    at beginWork (main.js:16)
    at a (main.js:16)
wt @ main.js:16
commitErrorLogging @ main.js:16
j @ main.js:16
b @ main.js:16
v @ main.js:16
y @ main.js:16
interactiveUpdates @ main.js:16
qe @ main.js:16
main.js:11 Uncaught Error: Minified React error #254; visit http://reactjs.org/docs/error-decoder.html?invariant=254&args[]=value0 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at n (main.js:11)
    at n (main.js:16)
    at gt (main.js:16)
    at c (main.js:16)
    at h (main.js:16)
    at main.js:16
    at u (main.js:16)
    at l (main.js:16)
    at beginWork (main.js:16)
    at a (main.js:16)
```

**Steps to reproduce the problem**
I just follow a installation and get start documentation and I just explore the admin dashboard and I try to click "Add a new language"

**Comment by soupette** [comment]
hi @spksoft I believe it's related with the `react-select` ref, here's the [concerned issue](https://github.com/JedWatson/react-select/issues/2459)

**Comment by RobinPel** [comment]
I'm having the same error (although it's #188 instead of #254) on a clean install of the latest version v3.0.0-alpha.14.1.1 for clicking "Add a new language", as well as for clicking "Add content type" on the Content Type Builder page. 

`Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. main.js:11`

Any workarounds known?

**Comment by peckhouse** [comment]
**Node.js version**: v10.10.0
**npm version**: 6.4.1
**Strapi version**: 3.0.0-alpha.14
**Database**: Mongodb
**Operating system**: Linux (AWS EC2 Server)

Hello, 
I'm having this issue on distant server.
![screen shot 2018-09-17 at 14 39 22](https://user-images.githubusercontent.com/700371/45607545-11b20c80-ba88-11e8-8f03-e1405415cfc2.png)

I just installed Strapi on the server, and every time I try to interact with User `Role` dropdown or the  
`Add content type` button I got the above error.

I tried to do the same install on my local, and I didn't got any issues.
Is there something I'm doing wrong, or a server configuration I am missing that could trigger this issue?

**Comment by nguyenkhois** [comment]
I have the same problem when I install on AWS EC2 Server
**Strapi version**: 3.0.0-alpha.14
**Database**: Mongodb
**Operating system**: Linux (AWS EC2 Server)
**Docker version** 18.06.1-ce
**Port**: 1337

![strapi](https://user-images.githubusercontent.com/31632421/45646224-fc0e0880-bac2-11e8-9114-121396da5e6f.png)

**Comment by nguyenkhois** [comment]
I have the same problem when I install on AWS EC2 Server
**Strapi version**: 3.0.0-alpha.14
**Database**: Mongodb
**Operating system**: Linux (AWS EC2 Server)
**Docker version** 18.06.1-ce
**Port**: 1337

![strapi](https://user-images.githubusercontent.com/31632421/45646518-dd5c4180-bac3-11e8-9c75-16519fca2be5.png)

**Comment by nguyenkhois** [comment]
**"Solution" for Docker users**:
I have cloned [strapi-docker](https://github.com/strapi/strapi-docker/blob/master/Dockerfile) and changed only one line `RUN npm install -g strapi@3.0.0-alpha.14` to `RUN npm install -g strapi@3.0.0-alpha.14.1.1`. Then I created a new other Dockerfile.

It works fine in my case when I install the modified Strapi Dockerfile on Amazon Linux server (EC2). You can test [the modified Dockerfile](https://hub.docker.com/r/khois/grapis/) on Docker Hub before Strapi release the new official version for Docker.

**My system**:
* Amazon EC2 - Linux
* Docker for Linux (both MongoDB and Strapi are in Docker)
        *  MongoDB version 4 (lastest)
        *  Strapi vesion strapi@3.0.0-alpha.14.1.1 (modified)

**Comment by soupette** [comment]
@byoungd I'm aware of the issue and I'll try to fix when I have the time...

The `add new language` just adds a new locale in `may-app/config/locales` so you can manually create one until I take care of the problem.

**Comment by byoungd** [comment]
@soupette Got it. I will try to create one manually then feed back. Thanks for your response so quickly and I am getting like strapi more and more.

**Comment by byoungd** [comment]
@soupette When I created `zh_hans.json` in `app/config/locales`, Chrome refreshes automatically and one unknown language Appeared. But I can't set it as default language with the alert `An error occured`. Waiting fix this. 
Thanks any way.

**Comment by soupette** [comment]
@byoungd in you can also set it manually
**Path -** `./config/languages.json`

```
{
  "enabled": true,
  "defaultLocale": "zh_Hans",
  "modes": [
    "query",
    "subdomain",
    "cookie",
    "header",
    "url",
    "tld"
  ],
  "cookieName": "locale"
}
```
