### ISSUE TITLE
On Windows, with Chrome and FireFox browsers, icon for Invite new user is broken

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#13259]
### Describe the bug

When SuperAdmin user goes through Settings > Users > Invite new user, after filling all the fields and press [Invite], the icon on the left of URL to copy to give access to new user is broken : 

### Steps to reproduce the behavior

1. Go to Settings > Users > Invite new user
2. After filling all the fields and press [Invite]
3. Pop-up appears with URL to send to new user for registration
4. See error : icon is broken (see screenshot below)

### Expected behavior

Icon should be complete.

### Screenshots

![image](https://user-images.githubusercontent.com/97893822/167156874-6088a213-8a5b-4344-b96f-f73826ed10f5.png)

Jira card : https://strapi-inc.atlassian.net/browse/CONTENT-153

**Comment by derrickmehaffy** [comment]
*sly cough* :pray: just to keep things fair with the community can we also fill out the version information

https://media.giphy.com/media/Pnh0Lou03fv92J4puZ/giphy.gif

**Comment by jhoward1994** [comment]
Hi @derrickmehaffy, everything looks fine from my side, but I am running mac. Do you know anyone on the team who could test this on windows?

**Comment by derrickmehaffy** [comment]
I believe @MarionLemaire uses windows (and is on our QA team), so it's possible she could take a look.

**Comment by joshuaellis** [comment]
> Hi @derrickmehaffy, everything looks fine from my side, but I am on a mac. Do you know anyone on the team who could test this on windows?

I can test this. I'll use the npx command for the latest version.

**Comment by derrickmehaffy** [comment]
Ah shoot yeah totally forgot about that, sorry Josh

**Comment by joshuaellis** [comment]
It was still broken @jhoward1994, but i've opened a quick PR to solve it 👍🏼
