### ISSUE TITLE
Admin web interface does not work if I change default port

### ISSUE THREAD

**Issue by c3s4** [strapi/strapi#13266]
### Required System information

- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.1.9
- Database: Postgres
- Operating system: MacOS but also on Docker from node-alpine

### Describe the bug

If I change the default port, the admin web interface stops to work because calls for `/admin/project-type` on `http://localhost:1337` instead of my chosen port. This happens using docker but also using the getting started script `npx create-strapi-app@latest my-project`.

I'm using the developer mode and if I run `yarn build` before the `strapi develop`, everything working fine, but with v4.0.0 I didn't need to build in dev mode. 

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest my-project`
2. When strapi started stop it
3. Change the `PORT` in `.env` file
4. Run `yarn develop`
5. Access to the web ui
6. The loader spins indefinetly, if you take a look to the browser network console you'll see `http://localhost:1455/admin/project-type` getting a 404 because it uses the default port.

### Expected behavior

The admin UI works as expected.

### Additional context

I tried to use the `4.0.0` version and everything works as expected, without any build.
I don't understand why I need a build in dev mode, I thought webpack could build the UI on runtime in dev mode.

**Comment by shifajaman** [comment]
Hi @c3s4 ,

I was able to reproduce this bug. 
![image](https://user-images.githubusercontent.com/85345302/167434747-478d28b1-c048-4cfa-b866-3df71937c7ec.png)

@c3s4 , can I start to fix it?

**Comment by c3s4** [comment]
Hi @shifajaman, I would appreciate it so much :)

**Comment by Zharkan** [comment]
Have you tried to rebuild the admin ?

**Comment by soupette** [comment]
@c3s4 when you change the PORT you need to rebuild your admin panel by running either `yarn build` or `npm run build`.


After the 4.0.0 we introduced a default build meaning that if you haven't customised your admin panel and that you are using the default plugins instead of generating a new build we use the one from the @strapi/admin package in your node_modules.

I am closing this issue feel free to reopen it.
