### ISSUE TITLE
Strapi und digital Ocean

### ISSUE THREAD

**Issue by Estheryu991** [strapi/strapi#13268]
Darf ich fragen was ist die Unterschied zwischen Digital Ocean und Strappi? 

bei unserer Firma benutzt das

**Comment by thiagobutignon** [comment]
Strapi é um gerenciador de conteúdo e o Digital ocean é onde hospedamos aplicações backend, front end e banco de dados.

**Comment by derrickmehaffy** [comment]
Hello!

To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms. 

Thank you and have a wonderful day!

---

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
