### ISSUE TITLE
Images are not shown in Media Library after upload via REST API

### ISSUE THREAD

**Issue by komape** [strapi/strapi#13286]
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.8.0
- Strapi version: v4.1.9
- Database: SQLite
- Operating system: macOS v12.3.1

### Describe the bug

After uploading images via the REST API they are listed in the Media Library but you cannot see the image itself, only a placeholder. I can download the image and open the image in a new tab without problems. Seems like the upload itself was successful but it's just not displayed it in the Media Library.

### Steps to reproduce the behavior

1. Upload an image via REST API
2. Open Media Libray

### Expected behavior

The images should be shown directly in the Media Library.

### Screenshots

![image](https://user-images.githubusercontent.com/25869589/167860684-3ef55141-157e-4730-9abe-5da73df5b5fa.png)
![image](https://user-images.githubusercontent.com/25869589/167860756-aa4c0341-3fc7-427a-9d38-70d62d7be715.png)

### Code snippets

n/a

### Additional context

n/a

**Comment by Nikoxx99** [comment]
Does they shown when uploading directly from the strapi UI ?

**Comment by petersg83** [comment]
Hello :) Which upload provider do you use ? (local, cloudinary etc.)

**Comment by keshav1123** [comment]
I am also facing the same issue. 
I am using this package @strapi/provider-upload-aws-s3. When I am using default Strapi uploader it's working, but when using a provider it does not show the image thumbnail inside the Media Library

**Comment by keshav1123** [comment]
> @keshav1123 Did you try modifying the security config: https://github.com/strapi/strapi/tree/master/packages/providers/upload-aws-s3#security-middleware-configuration ?

Thanks, It's working as intended now.

**Comment by komape** [comment]
If I upload them via the admin panel they are shown.

The whole Strapi app is local.

**Comment by komape** [comment]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/25869589/167886249-30ae0bdf-a2ad-4b99-9a28-19a1321727f4.png">

**Comment by derrickmehaffy** [comment]
> <img alt="image" width="1248" src="https://user-images.githubusercontent.com/25869589/167886249-30ae0bdf-a2ad-4b99-9a28-19a1321727f4.png">

Looks like there are some errors in the console, can you share those as well? (I assume most are related to the tracking block)

**Comment by komape** [comment]
My media settings:

- responsive friendly upload

`config/plugins.js`
```javascript
upload: {
  config: {
    breakpoints: {
      large: 1000,
      small: 500,
      xsmall: 64,
    },
  },
},
```

- size optimization enabled
- auto orientation disabled

Does that help?

**Comment by komape** [comment]
I think I found out why the images aren't shown in the Media Library. They're alle tagged with 'DOC' and not 'IMAGE'. Seems like Strapi thinks these are ordinary file and not explicitly images. All files are .jpeg files. Do I need to tag them during upload? Can I do change that afterwards via the REST API?

**Comment by komape** [comment]
Another thing I noticed is the usage of uploaded images for image fields in one of my collections. The collection type has a field with a reference to an uploaded file that must be an image.

![image](https://user-images.githubusercontent.com/25869589/169293085-7035e6c4-2ccf-4977-9eec-fff9f7123ea6.png)

If I try to select an image via the admin interface I can't select any of the files because they have the type 'DOC' and not 'IMAGE'. But there hasn't been any problem setting those images via the REST API.

For me it seems like there's a bug in the auto detection of media type in the REST API for uploads. This causes the following problems. Please reopen this issue.

**Comment by komape** [comment]
I double checked and images uploaded via REST API have the MIME type `application/octet-stream` and images uploaded via admin panel have the MIME type `image/jpeg`.

Could this be caused by #12881?

**Comment by petersg83** [comment]
Hi @komape Yes it seems totally related to that. Does it work now for you?
The thing is that the mime type is automatically added by the browser and web technologies like that. So depending on which technology you use, the mime-type may be missing, leading to image being not detected.
The PR https://github.com/strapi/strapi/pull/12881 you shows is an attempt to auto-detect the mime-type when it is not provided, based on the extension of the filename. How are your pictures names?
You can manually set the mime type by putting `Content-Type: image/jpeg` at the upload of your file with form-data

**Comment by komape** [comment]
This workaround solved it. Thanks!

Please add this to your documentation here: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#upload-files.

**Comment by petersg83** [comment]
I'm glad it works!
It's definitely something to add in the doc.
Can you share your piece of code where you use it? So I can quickly make a PR for the doc based on it?

**Comment by komape** [comment]
Sure I can do but I did it with Dart and the `http` and `http_parser` packages. Here's the code to create an entry and upload the files within one request:

```dart
Future<void> updloadEntry(MyEntry entry) async {
  Uri url = Uri.parse('http://myHost/api/entries');
  String json = jsonEncode(entry.toJson());
  MultipartRequest request = MultipartRequest('POST', url)
    ..headers.addAll(getHeaders(contentType: 'multipart/form-data'))
    ..fields['data'] = json;
  for (int i = 0; i < entry.images.length; i++) {
    String fileName = entry.images[i];
    File file = File('my/file/path/$fileName');
    bool fileExists = await file.exists();
    if (!fileExists) {
      print('+++ File $fileName does not exist');
    } else {
      request.files.add(await MultipartFile.fromPath('files.images', file.path,
          filename: fileName, contentType: MediaType.parse('image/jpeg')));
    }
  }
  StreamedResponse response = await request.send();
  if (response.statusCode > 201) {
    print(
        '+++ Failed to create entry ${entry.id} ${response.statusCode} ${response.reasonPhrase}');
  }
}

```

**Comment by petersg83** [comment]
Thank you!
