### ISSUE TITLE
sizeLimit in @strapi/provider-upload-local is in kilobytes, not bytes.

### ISSUE THREAD

**Issue by umcai** [strapi/strapi#13282]
### Required System information

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: v4.1.9
- Database: postgres
- Operating system: WSL(Docker build from strapi/base)

### Describe the bug
`sizeLimit` in @strapi/provider-upload-local is in **kilobytes**, not bytes.

### Steps to reproduce the behavior
Set sizeLimit to 1000, and upload a file of size 900KB.

### Expected behavior
![image](https://user-images.githubusercontent.com/11835233/167587079-ef747fac-e4b4-4126-a60c-2c9ab7bc45bc.png)

### Screenshots
Uploaded successfully
![image](https://user-images.githubusercontent.com/11835233/167587951-8ab43b5b-1427-416a-bffb-b2826846bc94.png)

### Code snippets
![image](https://user-images.githubusercontent.com/11835233/167587802-1a3ebc13-124d-4ee8-89f4-b9f6236e3b2b.png)

### Additional context
Uploaded files in windows environment.

**Comment by umcai** [comment]
My mistake.😅

**Comment by derrickmehaffy** [comment]
Can you try editing your the local upload provider here: https://github.com/strapi/strapi/blob/cf33ce0b63ab7e07e75c46b3f4382cf3a9c0956c/packages/providers/upload-local/lib/index.js#L18-L22 and put a console.log to log out the `file.size` and the `sizeLimit`?

**Comment by umcai** [comment]
@derrickmehaffy this is the output:
![image](https://user-images.githubusercontent.com/11835233/167983231-d96673b5-2f09-41ff-aeeb-ea38a07f37b4.png)

I uploaded a file less than 1KB:
![image](https://user-images.githubusercontent.com/11835233/167983415-ce49aced-da20-4796-92e6-59f8ef788d10.png)

And a file larger than 1MB (Of course, the upload failed this time, but setting the sizeLimit to 6000 can upload successfully):
![image](https://user-images.githubusercontent.com/11835233/167983661-2b737835-47ca-499f-aa17-79fc7c03cef3.png)

The files I uploaded via Chrome, Firefox, Edge and Postman on Windows and Mac are all in `KB`

**Comment by DanieleAurilio** [comment]
Hi @derrickmehaffy @umcai,
i think put `sizeLimit = sizeLimit/1024;` in [strapi/packages/providers/upload-local/lib/index.js](https://github.com/strapi/strapi/blob/cf33ce0b63ab7e07e75c46b3f4382cf3a9c0956c/packages/providers/upload-local/lib/index.js#L17-L18) can solve this behaviour.
Could it be a good solution?

If it will be a good solution i can pickup this issue and will make a pr.

**Comment by derrickmehaffy** [comment]
So there is basically two paths we can take here (and I don't know which way is better):

Either we update the documentation to clearly state it's in KB (not kB or KiB btw) meaning I can transfer this issue to the documentation repo

Or we do as you suggestion @DanieleAurilio and do a quick PR to adjust the actual checked size.

I'll ask the team their thoughts but I'd like to hear both of yours as well.

**Comment by Marc-Roig** [comment]
Hello! We have an open PR that concerns this issue https://github.com/strapi/documentation/pull/1133

The sizeLimit will actually be in bytes (as the docs says), not KB. :) 
We thought it would be weird to ask for KB when normally it is asked with bytes. Also the change was easier to make.
