### ISSUE TITLE
[4.2.0-beta.2] Type definition for WhereParams in query(...).findMany and other query functions is missing attributes

### ISSUE THREAD

**Issue by fingeg** [strapi/strapi#13287]
## Bug report
The `WhereParams` type in [`@strapi/database`](https://github.com/strapi/strapi/blob/master/packages/core/database/lib/index.d.ts) is not complete. It only has support for `$and`, `$or` and `$not`, so most of the functions described in the [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/filtering.html#lt) are missing.

### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.2.0-beta.2
- Database: postgres
- Operating system: Ubuntu-20.04

### Describe the bug

Incomplete type definition as described above.

### Steps to reproduce the behavior

1. Try using the `where` attribute in `strapi.query('UID').findMany({ where: { ... } })`
2. Only the basic and, or and not operations are available

### Expected behavior

The type should have all the attributes as described in the docs

**Comment by marcoautiero** [comment]
Fixed by #13290
