### ISSUE TITLE
API Filters $eq = problem with the results

### ISSUE THREAD

**Issue by loicy** [strapi/strapi#13294]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.10.0
- Strapi version: 4.1.9 (tested on 4.1.10)
- Database: 10.5.8-MariaDB
- Operating system: Windows (dev) & Linux (prod)

### Describe the bug

I've done the research with some of the guys on Discord and we haven't found a solution.

When searching via populate and a filter, the answers that don't match are displayed with a "data: null". Is it possible to delete answers when doing filter queries or is there a bug?

### Steps to reproduce the behavior

1. Making a collection with a relationship (one to one)
2. Create several posts with a different relationship
3. Making a request with a filter on the relationship

### Expected behavior

There should be no response other than the query with the filter

### Screenshots

![Capture d’écran 2022-05-12 020719](https://user-images.githubusercontent.com/36493474/167968312-54a89fdc-4563-4033-a6d9-de000e9fc73c.png)

### Code snippets

Request : {API_URL }/faq-posts?populate[faq_categorie][filters][category][$eq]=account (exemple of request

**Comment by derrickmehaffy** [comment]
You need to also filter on the parent if that's what you are trying to filter, not just/or filtering within the populate.

Going to mark this as closed though as it's not a bug report but a question.

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
