### ISSUE TITLE
Blank pages in admin panel after upgrade to 4.1.10

### ISSUE THREAD

**Issue by Fluxium2006** [strapi/strapi#13299]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.5.0
- Strapi version: 4.1.10
- Database: SQLite
- Operating system: Win 10 Pro 64 Bit

### Describe the bug

After upgrading Strapi from version 4.1.8 to 4.1.10, some pages of the admin panel show a blank page. Upon page refresh, the left sidebars flash and you see a loading spinner and then the page is blank again.

### Steps to reproduce the behavior

1. Have Strapi 4.1.8 installed
2. Use a database migration script [https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.1.8+-to-4.1.10.html](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.1.8+-to-4.1.10.html)
3. Edit your package.json like this:
    `
"@strapi/plugin-i18n": "4.1.10",
    "@strapi/plugin-users-permissions": "4.1.10",
    "@strapi/provider-email-sendgrid": "^4.1.10",
    "@strapi/strapi": "4.1.10",
`
4. Build admin UI
5. Run Strapi
6. Go to "`/admin/settings/users-permissions/roles`" or "`/admin/plugins/content-type-builder`" or "`/admin/settings/media-library`"

### Expected behavior

The page loads normally.

### Additional context

The browser console shows these errors:
`
TypeError: X.default() is undefined` in media library and users-permissions settings

`TypeError: e.useGuidedTour() is undefined` on page "`admin/plugins/content-type-builder`"

**Comment by Fluxium2006** [comment]
I also tried upgrading from 4.1.8 to 4.1.10 without a migration guide (as I noticed that I didn't need it). I just edited my `package.json`, ran `npm install`, `npm run build` and `npm run develop`, but the error still occurs.

**Comment by Fluxium2006** [comment]
I found a solution for this:

1. Have Strapi 4.1.10 installed
2. Delete `.cache` and `build` folders
3. Delete `package-lock.json`
4. Run `yarn install` (install yarn first if you haven't)
5. Run `yarn build` - `npm run build` seems to not do a correct job for some reason
6. Run `yarn develop`

Now, the media library, content types builder and users-permissions settings load again.

**Comment by csharpee** [comment]
> I found a solution for this:
> 
>     1. Have Strapi 4.1.10 installed
> 
>     2. Delete `.cache` and `build` folders
> 
>     3. Delete `package-lock.json`
> 
>     4. Run `yarn install` (install yarn first if you haven't)
> 
>     5. Run `yarn build` - `npm run build` seems to not do a correct job for some reason
> 
>     6. Run `yarn develop`
> 
> 
> Now, the media library, content types builder and users-permissions settings load again.

I reinstalled and it worked again, but after setting up my api, I am now again unable to see my admin page.

**Comment by amrit-citrusleaf** [comment]
Bump. Facing the same issue. Clean build is not working. Roles page in settings is blank.
Getting -`TypeError: ae.default() is undefined`
