### ISSUE TITLE
Strapi white screen with GraphQL plugin (TypeError: Cannot destructure property 'startSection' of '(0 , build.useGuidedTour)(...)' as it is undefined.)

### ISSUE THREAD

**Issue by jack3898** [strapi/strapi#13293]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.4.1
- Strapi version: 4.1.10
- Database: sqlite
- Operating system: Windows 11 Professional

### Describe the bug

Installing the GraphQL plugin (4.1.10) causes multiple areas of the dashboard to display a white screen with the following error in the browser console:

![image](https://user-images.githubusercontent.com/28375223/167938228-1ac27fc3-88e3-4bf9-8d7d-6cb0bd74e7f2.png)

When I remove the GraphQL plugin, delete .cache and build directories, the screen is accessible again.

### Steps to reproduce the behavior

1. Install the latest version of Strapi
2. Run the develop script
3. Create an account and access the content types builder
4. Observe that you **can** access the builder without any problems (no white screen)
5. Stop strapi and delete .cache and build directories
6. Install the GraphQL plugin with `npm install @strapi/plugin-graphql` or `npm run strapi install graphql`
7. Run the develop script
8. Observe the white screen when trying to access content types builder with the above attached screenshot displayed in your console window

### Expected behavior

Access to the content types builder when strapi is opened in development mode with the graphQL plugin installed.

### Additional context

Also does not work with the latest beta version of Strapi.

**Comment by derrickmehaffy** [comment]
Could not reproduce on v4.1.10, most likely environmental based, likely due to cache.

Will reopen if more reproduction information is provided.

**Comment by Nikoxx99** [comment]
Try deleting package-lock.json and node_modules then using yarn instead of npm

`npm install --global yarn`
then
`yarn`
 
now you can do `npm run develop`

Npm is doing some strange things lately

**Comment by derrickmehaffy** [comment]
> Npm is doing some strange things lately

Understatement of the year :100:

**Comment by brandonratz** [comment]
**Reproduced**

- Yarn 3.2.1
- Node 14.17.0
- Strapi 4.1.11

1. `yarn create strapi-app my-project --quickstart`
2. `yarn strapi install graphql`
3. `yarn develop`
4. Browse to http://localhost:1337/admin/plugins/content-type-builder

Console error and WSOD
```
TypeError: Cannot destructure property 'startSection' of '(0 , build.useGuidedTour)(...)' as it is undefined.
```

**Comment by v4dkou** [comment]
I am also seeing a white screen upon installing GraphQL plugin, albeit with a different error
```TypeError: r is undefined```
Appears to be a minified version of the same error (no idea why would it be minified though, as I am building Admin UI in development mode with `strapi develop`)

Environment
* Yarn 3.2.1
* Node 16.15.0
* Strapi 4.1.1

Purging cache or starting the project from scratch does not help.

@derrickmehaffy Would you kindly reopen the issue?

**Comment by MrChrisRodriguez** [comment]
+1 to reopen. I can't speak for OP, but it appears @brandonratz, @v4dkou, and I are all running into this with Yarn PNP.

- Yarn 3.2 (PNP)
- Node 14.19.1
- Strapi 4.1.11

--

@v4dkou, you may want to enable source maps. 
1. Go to `src/admin` and rename the example file in there to `webpack.config.js`
2. Add the source map configuration, then rebuild. For example, I'm using eval-source-map

```
return {
    ...config,
    devtool: 'eval-source-map'
  }
```

You can see the [various source map options here](https://webpack.js.org/configuration/devtool/#development).

**Comment by v4dkou** [comment]
@MrChrisRodriguez Not using PnP, but I am using Yarn Workspaces

--

Thanks for the tip on enabling source maps in Strapi's admin panel!

**Comment by derrickmehaffy** [comment]
For those of you using PNP can you please open a feature request on the feedback website: https://feedback.strapi.io

As far as I know, at this time we don't support PNP, which is a very specific feature of yarn that is not standard

**Comment by aivils** [comment]
I got same error when I used "strapi generate" to generate the plugin. All the built-in plugins disappeared (blank screen) and only my plugin remained working. The error appears after "strapi generate" when the plugin contains only the generated code. Despite this I was able to design my own plugin.
Now using node v14.19.1 (npm v8.10.0)
Strapi v4.1.8
I don't use yarn.

**Comment by aivils** [comment]
I also copied original strapi code untouched to the plugins folder and I got same error noticed above:

Browse to http://localhost:1337/admin/plugins/content-type-builder
```
TypeError: Cannot destructure property 'startSection' of '(0 , build.useGuidedTour)(...)' as it is undefined.
```

My own code config/plugins.js
```
module.exports = {
  'gatsby': {
    enabled: true,
    resolve: './src/plugins/plugin-gatsby-preview'
  },
}
```
where plugin-gatsby-preview folder contains code from the package "@strapi/plugin-gatsby-preview"

**Comment by kacper-witas-tsh** [comment]
Got the same error with clean strapi installation when running via npm workspaces

**Comment by ZeldOcarina** [comment]
UPDATE: removing the build folder, node_modules and package-lock.json, re-running `npm install` and `npm run build` fixed the issue. Now I will try to re-update.

**Comment by kibblerz** [comment]
Interesting find,
When I have my strapi version set to 4.1.11 it's the content type builder that gives a white screen, on 4.1.12 it's the media library.

This is with PnP

**Comment by yomomano** [comment]
Problem still exists with a normal default install on localhost (`npm run develop`). 
Tried node 14, node 16, strapi v4.18 and v2.0.0. No diff. Cleared cache, rebuild admin panel. 
I can access admin panel, all sections normally except `Content-Type Builder` and `Media Library`: these two give white screen and mentioned error in devtools: 

`TypeError: Cannot destructure property 'startSection' of '(0 , t.useGuidedTour)(...)' as it is undefined.`

**Comment by ZeldOcarina** [comment]
> 

Hey @yomomano did you try to remove the node_modules and the package-lock.json as I was suggesting a couple of comments above?

**Comment by yomomano** [comment]
> > 
> 
> Hey @yomomano did you try to remove the node_modules and the package-lock.json as I was suggesting a couple of comments above?

Mia culpa ! That fixed it (node 14, strapi v4.2.0).  Thank you

**Comment by sharkfin009** [comment]
I have the same error:

﻿
main.33888d05.js:8011 TypeError: Cannot destructure property 'startSection' of '(0 , t.useGuidedTour)(...)' as it is undefined.

i am using yarn.

**Comment by sharkfin009** [comment]
I had the same situation. Managed to fix by deleting .cache and the build directory. That worked , while deleting node modules and the lock file did not. Go figure ... (actually there may be someone who will figure! that would be great lol )
