### ISSUE TITLE
motification table database

### ISSUE THREAD

**Issue by JosueTavaress** [strapi/strapi#13304]
- Node.js version: 16.0
- NPM version: 7.10.0
- Strapi version: v4
- Database: postgreSQL
- Operating system: ubuntu

bug: when I delete the schema the data is deleted in the database

how can I change the table name in the database without losing the content?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
