### ISSUE TITLE
Allow for configurable accuracy on Decimal/Float

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1330]
**Note: This is for tracking a future change per @lauriejim if anyone would like to work on this you can submit a PR**

**What is the expected behavior?**

Decimal and Float values right now do not have configurable accuracy, and any attempts to modify it directly in the database will be overwritten whenever strapi restarts (bookshelf, unsure on mongoose).

Per this PR for Decimal: https://github.com/strapi/strapi/pull/1314 I am creating this issue only to spark discussion on the best way to handle defining the accuracy of a field type per model.

This should be done on both the adminUI and within the model config files in my opinion, on a per model/field basis. Some examples of how this is done on both postgres and mysql are below:

https://www.postgresql.org/docs/10/static/datatype-numeric.html
https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html

In both database types the accuracy is usually defined as:
Type(M,D)
```
FLOAT(M,D)
REAL(M,D)
DOUBLE PRECISION(M,D)
```

Where M,D is defined as M - Total digits stored and D - Total digits after the decimal point (subtracted from M). So if you have a `M,D` set as `20,8` then you could have a total of 20 digits with 12 of them before the decimal and 8 after it thus allowing for a number such as: `999,999,999,999.77777777`

Something else that should also be considered is unsigned/signed values, for instance the data type `serial` is an alias for `BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE` Basically where `unsigned` states you cannot have a negative number, but in doing so allows for you to double the maximum digits in the value. This is easy to handle in MySQL and Postgres but I am unsure about mongo.

**Comment by derrickmehaffy** [comment]
Per this recent change, decimal currently can only handle the following `M,D` - `10,2`:
https://github.com/strapi/strapi/blob/adf643854efa94abc5b0246ff403862904ccdd4f/packages/strapi-bookshelf/lib/index.js#L363-L365

**Comment by derrickmehaffy** [comment]
You can also within MySQL just define the M value which for Float is `12` and for Double is `22`

**Comment by Aurelsicoko** [comment]
@derrickmehaffy What should we do with this issue? I understand the need but it doesn't seem a priority for now.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I mean at least on bookshelf you just need to define some default accuracy values and allow for users to overwrite it. This would also require an addition to the adminUI.

I don't think should should be closed, and either should be kept as a Good for new contributors. I personally think this is an important issue as without it you are basically locking users in to use only the defined accuracy that Strapi has coded into bookshelf.

I honestly don't have the skills required to modify bookshelf, the adminUI, and the model.settings.json parser. Hence the reason I stated in the OP `if anyone would like to work on this you can submit a PR`

**Comment by derrickmehaffy** [comment]
@alexandrebodin should we just document the column options for this in v4 or are you planning to make large changes to them

**Comment by chouchua** [comment]
Has anyone addressed this issue in V4? or is this in the pipeline already?

**Comment by derrickmehaffy** [comment]
Already possible now in v4 using the experimental database field modifications: https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#database-validations-and-settings
