### ISSUE TITLE
fix(content-manger): Check `datetime` type on an empty state

### ISSUE THREAD

**Issue by MichaelEvtushenko** [strapi/strapi#13319]
https://github.com/strapi/strapi/blob/2edd2ae00c04b973f9bc2c91a9e83efb4a7b93a9/packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/index.js#L238
As the title says, need to add the following check for `datetime` type as well:
```
if (value === '' && (type === 'date' || type === 'datetime' )) {
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
