### ISSUE TITLE
Users related rest apis do not conform to entity type format

### ISSUE THREAD

**Issue by Keith-Hon** [strapi/strapi#13318]
Describe the bug
1. Users rest api does not conform to entity type format
2. Populated fields from users rest api do not conform to entity type format

Steps to reproduce the behavior
1. Call api/users, the returned data doesn't conform to the format of, but got flatten out

Expected: {
    "data": [
        {
            "id": 1,
            "attributes": { }
        } ]
}

Actual:

[
    {
        "id": 1,
        ...
    }
]

2. Define a collection type called "membership", and assign relation in users, such that each user has a membership.
Call api/users?populate[0]=membership, the populated membership doesnt follow an entity type neither.

System
Node.js version: v12.22.8
NPM version: 6.14.15
Strapi version: v4.1.10
Database: postgres
Operating system: ubuntu 20.04.2 LTS

**Comment by Keith-Hon** [comment]
I am writing an ts sdk which has the following function:

 const { success: boolean, entity?: UsersPermissionsUserEntity} = await strapi.getEntity<UsersPermissionsUserEntity>({
            types: "users",
            populateParams: ["membership"],
            attributes: [{
                key: "email", value: abc@gmail.com
            }]
 });

the sdk then calls a rest api to get the entity from strapi. It works fine except for "users" type, where the response has different format from other collections.

**Comment by Keith-Hon** [comment]
The types are generated using graphql-codegen on strapi graphql endpoint

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12280
