### ISSUE TITLE
API Token not working with, custom plugin

### ISSUE THREAD

**Issue by WardenCommander** [strapi/strapi#13311]
### Required System information

- Node.js version:14
- NPM version:6.8
- Strapi version:4.1.10
- Database:postgres
- Operating system:railway

### Describe the bug
Hello, so im not sure if its a bug or not. Im trying to use API Token(Bearer Token) from Settings to pull data from plugin collection type, if i use Bearer token on native collection type from stapi authorization works as it should be, if use bearer token on collection type from plugin (api/my-plugin/my-collection-type) i cant read data as it returns status:401, UnauthorizedError. But if i try to read data as public without Bearer token i can read data.

### Expected behavior

Bearer token should work on all api routes.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by WardenCommander** [comment]
@derrickmehaffy for me its a bug, as token is not working on api routes from plugins. Or its not documented how to do it?

**Comment by derrickmehaffy** [comment]
I closed this because none of the bug report template was followed and immediately it looked like a question.

Generally I won't even read an issue if I see within the first 5 seconds the template wasnt followed or there is no steps outlining how to reproduce.
