### ISSUE TITLE
Changing api prefix will result public folder and admin site not accessible

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi#1331]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongo
- **Operating system**: Mac

**What is the current behavior?**
Changing api prefix is very problematic. After following instruction, api with prefix is working. However, both **public** folder and **admin** site is no longer accessible.

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
I reopen your previous issue.
