### ISSUE TITLE
CTB: extendFields can only be used once for each field

### ISSUE THREAD

**Issue by sargreal** [strapi/strapi#13322]
### Required System information

- Node.js version: v14.17.0
- NPM version: 8.5.5
- Strapi version: 4.1.11
- Database: sqlite
- Operating system: Manjaro Linux

### Describe the bug

When trying to extend field types in the content type builder with some custom settings, only the first registered one is actually shown in the base/advanced settings of a field.

The problematic code is here: 

https://github.com/strapi/strapi/blob/master/packages/core/content-type-builder/admin/src/utils/formAPI.js#L54-L76

In line 58 the if clause is opened, and the field extensions are only added, if it was previously empty. The if clause should end after line 69.

### Steps to reproduce the behavior

1. Add two new settings to a single field type in the Content-Type-Builder using the `formsAPI` (similar to the way it is done in the i18n plugin in the bootstrap function of the admin interface). This needs to be done in a new plugin. Full example code in the `Code snippets`
2. Start the admin interface
3. Create new content type
4. Add boolean field
5. Switch to advanced settings (Issue should be the same on base settings)
3. See that only one of the settings is available

### Expected behavior

All field extensions should be visible

### Screenshots

What is shown when editing the advanced settings:
![image](https://user-images.githubusercontent.com/19500573/168488278-fc34b6c3-cd33-4aea-add3-63d5ace770df.png)

### Code snippets

Code snippet to add two settings to a boolean field:

```js
export default {
  register(app) {
    /* ... */
  },
  bootstrap(app) {
    const ctbPlugin = app.getPlugin('content-type-builder')
    if (ctbPlugin) {
      const ctbFormsAPI = ctbPlugin.apis.forms

      ctbFormsAPI.extendFields(['boolean'], {
        validator: () => {},
        form: {
          advanced() {
            return [
              {
                name: 'pluginOptions.example.test1',
                type: 'checkbox',
                intlLabel: {
                  id: 'content-type-builder.example.test1.label',
                  defaultMessage: 'Configure Test 1',
                },
              },
            ]
          },
        },
      })

      ctbFormsAPI.extendFields(['boolean'], {
        validator: () => {},
        form: {
          advanced() {
            return [
              {
                name: 'pluginOptions.example.test2',
                type: 'checkbox',
                intlLabel: {
                  id: 'content-type-builder.example.test2.label',
                  defaultMessage: 'Configure Test 2',
                },
              },
            ]
          },
        },
      })
    }
  }
}
```

This is obviously in this case not how it should be done (both settings can be added with one call to `extendFields`), but only serves to illustrate what would happen if two different plugins would add a settings to the same field type.

### Additional context
This problem was discovered in the context of the deepl strapi plugin, when trying to allow the user to configure for each field how the translation should happen (Fekide/strapi-plugin-deepl#13). Once a new setting was added through the forms API, the settings for localization (i18n plugin) would always disappear.

**Comment by derrickmehaffy** [comment]
@sargreal are you open to submitting a pull request?

**Comment by sargreal** [comment]
@derrickmehaffy definitely, just wanted to make sure the issue is seen as valid ^^
