### ISSUE TITLE
Incomplete context in policies and 403 PolicyError not logged

### ISSUE THREAD

**Issue by fdel-car** [strapi/strapi#13327]
### Required System information

- Node.js version: 14.17.2
- NPM version: 6.14.13
- Strapi version: 4.1.9
- Database: PostgreSQL
- Operating system: macOS

### Describe the bug

It seems that when reaching a policy, some middlewares didn't run yet.
For example, `ctx.query` is `undefined` inside the policy code - it's defined in the controller code on the other hand. Or when you block a request with a policy, the request doesn't produce any log in the terminal, which leads to believe that the order of middlewares should be reviewed maybe?

### Steps to reproduce the behavior

1. Create and use any policy.
2. Log `ctx.query` from there, and/or make sure the request will be blocked.
3. Call the endpoint that uses that policy.
4. You'll notice that `ctx.query` is `undefined`, and you won't see a 403 log entry on your terminal if the request is blocked.

### Expected behavior

I expect the context accessible in the policy code to be similar to the context accessible in the controller code for instance.
I expect that blocking a request with a policy to be similar to sending a 403 from a controller, going through the same middlewares.

**Comment by derrickmehaffy** [comment]
Can you please provide some sample code? (If it's not logging, that certainly isn't intended but want to check on the other stuff)

**Comment by derrickmehaffy** [comment]
@fdel-car I see you attached PN but this is normally a DevExp issue. I'll let you all figure out assignment :sweat_smile:

**Comment by petersg83** [comment]
I believe it's still a valid issue

**Comment by derrickmehaffy** [comment]
> reopening as I believe it's still a valid issue

Yeah sorry, one of my automations was set to the wrong label :see_no_evil:

**Comment by Boegie19** [comment]
This are basically 2 issues.
The ctx.query I can't reproduce on latest.
The noting being logged after an error is thrown I can reproduce.
This is because errors bypass all middleware's until the error middleware.
To fix this we would put the logger before the error middleware so that everything gets logged properly.
