### ISSUE TITLE
Error: association is not defined

### ISSUE THREAD

**Issue by JunQiGenYuan** [strapi/strapi#1332]
**Informations**
- **Node.js version**:
- **npm version**:
- **Strapi version**:
- **Database**:
- **Operating system**:

**What is the current behavior?**
When update entity that include file without change the file, cause error "association is not defined".

**Steps to reproduce the problem**
https://github.com/strapi/strapi/blob/e7af7bbeefe8d4c69f8682fa2195d0a75167b157/packages/strapi-bookshelf/lib/relations.js#L24

The variable association is undefined within function of transformToArrayID, which only used by update function below.

**What is the expected behavior?**

**Suggested solutions**
There are two ways to resolve this problem I think:
1. Add association param to function transformToArrayID, then add association as param to call it in function update.
2. Move the transformToArrayID into function update below.

**Comment by lauriejim** [comment]
@juampynr Can you provide steps I have to do to reproduce this issue please.

**Comment by lauriejim** [comment]
Hello @juampynr , please follow the issue template so we can get a better understanding about the origin of your bug. Need steps to reproduce and setup informations.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

**Comment by MechJosh0** [comment]
I have opened a ticket with the correct templating guideline https://github.com/strapi/strapi/issues/1461
