### ISSUE TITLE
[v4] [Admin Panel] Weird bug on Media Library page due to formatDuration function

### ISSUE THREAD

**Issue by kamal-choudhary** [strapi/strapi#13320]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.5
- Database: MySQL
- Operating system: macOS Big Sur

### Describe the bug

After uploading videos through GraphQL mutations, the Media Library page on Strapi Admin Panel gets broken and gives this error `RangeError: Invalid time value -> at formatDuration.js -> at VideoAssetCard.js`. I labeled this bug as weird because I am unable to reproduce it consistently. I follow the same steps and sometimes an error appears and sometimes the page loads fine.

I believe the error is because of the duration label that is supposed to represent the duration/length of the file.

### Steps to reproduce the behavior

1. Create 5-6 video entries using API calls or GraphQL mutations (I am using GraphQL)
2. Go to Strapi Admin Panel
3. Click on "Media Library" 
4. Page won't load and this error will show in the console "RangeError: Invalid time value"
5. If you go to other pages, those pages will load fine
6. Even, if some linked collection type is using the latest media you uploaded will load fine and we can see media there. It loads fine because here video asset card doesn't have that duration label.
7. Delete the last item uploaded through API call and the Media Library page will load again [no matter whatever the last item was]

Note: I am not saying the error will show all the time - sometimes, the page loads fine, and sometimes it gives an error.

### Expected behavior

The Media Library page should load fine.

### Screenshots

![error](https://user-images.githubusercontent.com/24447743/168475713-9a668d9e-7a72-408b-95ce-da664b5e24b4.png)

### Code snippets

Example of a file I am uploading:

File: {
   lastModified: 1652620521344
   lastModifiedDate: Sun May 15 2022 18:15:21 GMT+0500 (Pakistan Standard Time) {}
   name: "ahmed-video.mp4"
   size: 672335
   type: "video/mp4"
   webkitRelativePath: ""
}

### Additional context

1. The videos I am uploading are linked to another collection type i.e. when I upload a new video, it takes place of the previously linked video - though, all videos exist in the Media Library.

2. I can watch the video if it has been linked to some collection type. By going into **Content Manager** and then **Content type** and then opening the entry. (just to explain that video is correctly being uploaded and accepted by Strapi)

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I want to leave this one open for now - 4.1.11 was the time I had introduced a refactoring for that function which has broken something. Since then it has not been touched and I'd like to investigate what is happening.

Sure no problem :)

**Comment by gu-stav** [comment]
@kamal-choudhary Thanks for opening this issue. I had a look today and I believe this issue does not exist any longer, once you upgrade to at least 4.1.6 (current version is 4.2.0). I'll therefore close the issue.

If you still experience an issue, feel free to ping me and I'll re-open.
