### ISSUE TITLE
[users-permissions]: Extending the user model with relations doesn't work in v4/postgres anymore

### ISSUE THREAD

**Issue by fingeg** [strapi/strapi#13334]
## Bug report
In strapi v3 with MongoDB it was not a problem to extend the user model with a new relation. That relation was automatically included into the response of `auth/local` and therefore was easily accessible. 
Now it doesn't show up in the response at all anymore, which is because the SQL based relations need the `populate: true` argument on a `query(...).findOne(...)`, which is not specified in the `auth.js` of the user-permissions plugin.

https://github.com/strapi/strapi/blob/27639fa67ee100f23d805301f9f91e440c7b210e/packages/plugins/users-permissions/server/controllers/auth.js#L59

that line should be:
```ts 
const user = await strapi.query('plugin::users-permissions.user').findOne({ where: query, populate: true });
 ```
I don't know if the `populate: true` has an impact on performance in case no relations exist (the default). In that case it should be configurable at least.

### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.2.0-beta.2 (but should be the same in the current release)
- Database: postgres
- Operating system: Ubuntu-20.04

### Describe the bug

In my application, I extended the user with a list of products it is corresponding to. Every product is a relation to a different collection. Those products should show up on the user object in the response of `auth/local` and possible other responses involving the user object, too.
The specific reason why this worked with MongoDB and v3 as well as a possible fix is described above.

### Steps to reproduce the behavior

1. Add a relation to the user collection
2. Set the permissions of that relation to accessible
3. Make a user authentication with `auth/local`
4. The relation won't show
5. Just locally add the `populate: true` attribute and the output works as expected.

### Expected behavior

The relation should show up within the user object in any kind of users-permissions requests.

**Comment by fingeg** [comment]
I looked into what `populate: true` does in case there are no relations present and when the attribute is set to true the function:
https://github.com/strapi/strapi/blob/27639fa67ee100f23d805301f9f91e440c7b210e/packages/core/database/lib/query/helpers/populate.js#L8
is called, which just iterates through the attributes of the collection model to find relations. If there are no relations it simply returns an empty array, which should have almost no impact on the performance.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13296
