### ISSUE TITLE
[plugin:documentation]: Missing locale parameter in the openapi schema

### ISSUE THREAD

**Issue by martinloretzzz** [strapi/strapi#13338]
### Required System information

- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 4.1.10
- Database: sqlite
- Operating system: windows 11

### Describe the bug

The documentation plugin isn't adding the locale parameter to GET Requests, when i18n is enabled for the endpoint.
I'm using the openapi schema to generate the typescript interfaces and client code with openapi-generator.

### Expected behavior
Each GET request should have something like this in the parameters array of the schema, if i18n is enabled.
```
{
  name: "locale",
  in: "query",
  description: "The locale of the response e.g. en, de-DE",
  deprecated: false,
  required: false,
  schema: {
    type: "string",
  }
}
```

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
