### ISSUE TITLE
Database integration with strapi

### ISSUE THREAD

**Issue by ShreyashSalian15** [strapi/strapi#13341]
Hello there I wanted to integrate MariaDB in strapi but when I execute this command "npx create-strapi-app my-project
" and select custom setting I am not getting an option of selecting MariaDB I am getting only these three options did anyone know how am I supposed to do this?

![image](https://user-images.githubusercontent.com/105337128/168789314-d23a9a94-f626-412e-8918-b7decdef839d.png)

**Comment by ShreyashSalian15** [comment]
I am using this documentation for installation 
https://docs-v3.strapi.io/developer-docs/latest/setup-deployment-guides/installation/cli.html#creating-a-strapi-project

**Comment by derrickmehaffy** [comment]
You just select MySQL, MariaDB is a drop in replacement for MySQL and in v4 we go off of Knex dialects in that menu. Within Knex both MySQL and MariaDB function off the MySQL dialect

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
