### ISSUE TITLE
Error saving view configuration on random collections

### ISSUE THREAD

**Issue by Solero007** [strapi/strapi#13340]
### Required System information

- Node.js version: v16
- NPM version:  8.5.5
- Strapi version: 4.1.11
- Database: Postgres
- Operating system: Windows 11

### Describe the bug

When trying to configure a view, it displays and error on save. 

"main.a8c4bf62.js:8404 TypeError: Cannot read properties of undefined (reading 'settings')
    at content-manager.c5f5fb6a.chunk.js:70:9499
    at Array.reduce (<anonymous>)
    at Cu (content-manager.c5f5fb6a.chunk.js:70:9179)
    at Eu (content-manager.c5f5fb6a.chunk.js:70:7872)
    at content-manager.c5f5fb6a.chunk.js:70:12803
    at Object.onSuccess (content-manager.c5f5fb6a.chunk.js:1108:2759)
    at main.a8c4bf62.js:8404:54181"

I've truncated the database, i've even created a new database. And this issue only happens on certain collections. 
I've also cleared the node_modules, updated strapi - yet the same thing happens. 

This issue doesn't happen on all collections - just a random one each time. But the error stays on that collection - even sometimes after I truncate the database.

### Steps to reproduce the behavior

1. Go to "Configure view" from a collections
2. Make a change to view
3. Save
4. Error appears

### Expected behavior

To save the updated view settings

### Screenshots

![image](https://user-images.githubusercontent.com/26302508/168778804-231014e0-663e-4628-8c12-c511f17a9190.png)

**Comment by derrickmehaffy** [comment]
Unable to reproduce on v4.1.11. Tested on 20 different collections in the same application and could never trigger the error.

Need more information and likely a database dump with a known problem collection + code

**Comment by Thando-James** [comment]
I am getting a similar issue. Locally everything works fine, but after having uploaded my project onto cpanel, some collections do not allow me to add antries. And when I try to set some permissions for roles, it also errors with a 404. Below are the errors.
![Screenshot 2022-05-21 at 15 52 51](https://user-images.githubusercontent.com/20462145/169654816-038563a4-48d6-409e-afe6-0c83755faf44.png)
![Screenshot 2022-05-21 at 15 55 16](https://user-images.githubusercontent.com/20462145/169654886-215890d2-0846-42cc-9ebc-e0425b0258b1.png)

**Comment by derrickmehaffy** [comment]
> I am getting a similar issue. Locally everything works fine, but after having uploaded my project onto cpanel, some collections do not allow me to add antries. And when I try to set some permissions for roles, it also errors with a 404. Below are the errors. I'm on v4.1.11 ![Screenshot 2022-05-21 at 15 52 51](https://user-images.githubusercontent.com/20462145/169654816-038563a4-48d6-409e-afe6-0c83755faf44.png) ![Screenshot 2022-05-21 at 15 55 16](https://user-images.githubusercontent.com/20462145/169654886-215890d2-0846-42cc-9ebc-e0425b0258b1.png)

you issue is unrelated to this bug, yours is mostly a domain configuration issue.

**Comment by Oranuf** [comment]
I am running into this exact issue in my current repository. Started after upgrading from 4.2.0 to 4.2.2 but I don't believe that's the issue directly. Console error:

![image](https://user-images.githubusercontent.com/19432418/176916671-75a478c8-6405-4281-91b5-fe7bc63edd81.png)

**Comment by Solero007** [comment]
I figured it out in the end. 
Delete all your custom table headers in the config for the view (the “configure the view” section), save it – then got back to edit your layout. 

Hope this helps.

**Comment by EugeneKonovalov** [comment]
> I figured it out in the end. Delete all your custom table headers in the config for the view (the “configure the view” section), save it – then got back to edit your layout. Hope this helps. 
Hi @Solero007! Could you please explain more detailed, what is "custom table headers" in this case? It seems I've got same problem =(  Don't know how to recreate it yet, trying to figure it out.
