### ISSUE TITLE
White screen on content-type-builder page because useGuidedTour returns 0 instead of a dictionary

### ISSUE THREAD

**Issue by MrChrisRodriguez** [strapi/strapi#13356]
### Required System information

- Node.js version: various (14.19.1, 16.13.2)
- NPM version: various (8.4.1, 8.7.0)
- Strapi version: various (4.1.10, 4.1.11)
- Database: various (Postgres and sqlite)
- Operating system: various (macOS 12.3.1, Windows 11 Pro, Alpine Linux)

### Describe the bug
When trying to access the content type builder section of the admin interface, a user sees a white screen and the following error is logged in the console:

```TypeError: Cannot destructure property 'startSection' of '(0 , build.useGuidedTour)(...)' as it is undefined.```

Per @v4dkou, when minified, this error may also present itself as:

```TypeError: r is undefined```

### Steps to reproduce the behavior

Per @brandonratz in [this comment](https://github.com/strapi/strapi/issues/13293#issuecomment-1128358863):

- Yarn 3.2.1
- Node 14.17.0
- Strapi 4.1.11
1. yarn create strapi-app my-project --quickstart
2. yarn strapi install graphql
3. yarn develop
4. Browse to http://localhost:1337/admin/plugins/content-type-builder

### Expected behavior

The page to load successfully.

### Additional context

Here are some notable findings when exploring this issue:
- It's happening on clean repo clones and clean installs so it's unlikely to be a caching issue.
- @jack3898 ([comment](https://github.com/strapi/strapi/issues/13293#issue-1233136115)) and @v4dkou say that the issue began for them when they added the GraphQL plugin.
- My team is not using the GraphQL plugin. We do use these other plugins (listed [here](https://github.com/strapi/strapi/issues/13293#issuecomment-1129474899)).
- All of us are using Yarn. It also appears we may all be using Yarn Workspaces.

Here's where behavior diverges a little:
- @v4dkou is using Yarn Workspaces, but not PnP, and is experiencing this issue.
- My team experiences this issue when using PnP. But by changing that workspace application to use the node-modules node-linker instead of PnP, we're able to get it working. 

The issue is traced to [this line](https://sourcegraph.com/github.com/strapi/strapi/-/blob/packages/core/admin/admin/src/pages/SettingsPage/pages/ApiTokens/ListView/index.js?L37) and when stepping through, the useGuidedTour() function returns `0` instead of a dictionary.

Similar code appears elsewhere in the codebase. I **did not** have any issues accessing this settings page:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/772585/169214964-bbbdce9c-1e82-4de3-8834-295e9f56faed.png">

If I were a gambling man, I'd wager that this has something to do with how yarn (or Webpack?) is handling dependencies when they're hoisted (or 'virtualized', as in PnP mode) and is either a deeper bug that needs to be investigated, or could be resolved by having some stricter / more explicit dependencies defined within Strapi.

**Comment by derrickmehaffy** [comment]
As mentioned in https://github.com/strapi/strapi/issues/13293 can you either open a feature request to support yarn PNP and/or Workspaces via our feedback website: https://feedback.strapi.io

Alternatively if you are willing to open a feature PR please feel free.
