### ISSUE TITLE
Need to get you forum working first

### ISSUE THREAD

**Issue by murugappanrm** [strapi/strapi#13355]
I having been trying access the both the forum and discord and pages are loading forever. Please make sure your sites are all working and reliable. I was so excited on knowing what Strapi can do and then all the excitement died the moment i realized Strapi Web Sites are either deadly slow or not working. 

Now I am afraid to use the product. Sort out you sites please.

**Comment by Convly** [comment]
Hey @murugappanrm, thanks for opening this issue.

Both the [discord](https://discord.strapi.io) and the [forum](https://forum.strapi.io) are working fine (_at least for me and for the down detector website_) and we didn't receive any alert concerning a potential outage on our services. (please note that for Discord we're using Discord's servers anyway).

If the error persists on your end, it might come from somewhere else.

Have a good day.
