### ISSUE TITLE
Invite new user: email with camel case error

### ISSUE THREAD

**Issue by marco-villanueva** [strapi/strapi#13360]
### Required System information

- Node.js version: 16.15.0
- NPM version:  8.3.0
- Strapi version: 4.1.8
- Database: PosgreSQL
- Operating system: Window 10

### Describe the bug

When creating a new admin user (invite new user), if the email has any capital letters, it does not submit the form or show errors. In Network (DevTools) it shows a 400 error.

Is there a sanitizer or something that does a toLowerCase to avoid this error?

### Steps to reproduce the behavior

1. Go to Settings / Users
2. Click on "Invite new user"
3. Fill the form with an email like "ExamPle@example.com"
4. Click on "Invite user"
5. You can repeat it with the network open.

### Expected behavior

The form field automatically saves lower cases only.

**Comment by derrickmehaffy** [comment]
Odd it should just be lowercasing it and not validating the input :thinking:

**Comment by WalkingPizza** [comment]
> Odd it should just be lowercasing it and not validating the input 🤔

In standard scenarios, you are indeed lowercasing the email as per [this line](https://github.com/strapi/strapi/blob/2dfb6469947e4837dc73acd9a865842bd02d4c77/packages/core/admin/server/validation/common-validators.js#L20), but the [defaultValidationParams](https://github.com/strapi/strapi/blob/2dfb6469947e4837dc73acd9a865842bd02d4c77/packages/core/utils/lib/validators.js#L66) are enforcing strict checks on the email, which apparently says that `lowercase()` should only check that the string is in fact lowercase without transforming it beforehand according to [Yup's documentation](https://github.com/jquense/yup#stringlowercasemessage-string--function-schema).

**Comment by jaysoni-ash42** [comment]
@derrickmehaffy  do we need to make the change on the frontend on the form or the backend ?

**Comment by derrickmehaffy** [comment]
All emails should be lowercase no matter the location so if you want to do the translation on the frontend that's fine, we also should be doing it on the backend.

Doesn't particularly matter if we force the user to type it that way or if we just convert it for them but we should pick something.
