### ISSUE TITLE
  yarn create strapi-starter my-project next-blog

### ISSUE THREAD

**Issue by Tammeny** [strapi/strapi#13372]
### System information

- Node.js version: v14.16.1
- NPM version: .9.0
- Strapi version: 4.0.3
- Database: mysql 5.6
- Operating system: macOS Monterey 12.3.1

### Describe the bug

I tried to Install strapi, It was not successfully

### Steps to reproduce the behavior

1. run `npx create-strapi-starter strapi-next-blog next-blog`
2. See error
`Error: ⛔️ Template installation failed: Command failed: npm install @strapi/template-blog@1.0.0 --no-save --silent`

### Expected behavior

Install and run successfully

### Screenshots

![image](https://user-images.githubusercontent.com/5690568/169694655-40f65a67-132b-4286-9ce0-45bd2505cd96.png)

**Comment by hasanradi93** [comment]
I got the same error now, are you found the solution?

**Comment by derrickmehaffy** [comment]
Moving this to the starters and template repo

**Comment by derrickmehaffy** [comment]
Appears I can't transfer issues to the repo, can you please open this bug report on https://github.com/strapi/starters-and-templates

Thanks :)
