### ISSUE TITLE
Search does not work in Content-Manager list view

### ISSUE THREAD

**Issue by benderillo** [strapi/strapi#13374]
### Required System information

- Node.js version: v16.14.0
- Yarn version: 1.22.18
- Strapi version: 4.1.11
- Database: MySQL
- Operating system: Mac

### Describe the bug

The search field available in ListViews of the Content Manager plugin does nothing.
![Screen Shot 2022-05-23 at 5 39 54 PM](https://user-images.githubusercontent.com/1569988/169779446-cd294909-be33-4127-ba24-2906facbf254.png)

When I type in a search keyword and hit enter, the list view does not change. It reloads because the url gets updated (the &_q=<search keyword> gets appended to it) but the list view shows the same content.

I have a collection of reviews. Each review has `title` and `comment` fields. The `title` is a short string text type and the `comment` is a long text field.

I type a search keyword that matches at least one of the entries I see in the list.
But searching for it does nothing to the list view.
![Screen Shot 2022-05-23 at 5 50 50 PM](https://user-images.githubusercontent.com/1569988/169781575-0035d3af-89c3-4006-b1be-a2a953b1ffd7.png)

The url is updated like this, though:
```
http://localhost:1338/dashboard/content-manager/collectionType/api::review.review?page=1&pageSize=10&sort=title:ASC&_q=great
```

### Steps to reproduce the behaviour

1. Go to 'Content Manager'
2. Click on a collection type to open the List View
3. Ensure the view is set to be "Searchable"
4. Click the search field and type a search query that is guaranteed to get a match.

### Expected behaviour

When I hit enter on a search field with valid search keyword, the ListView content should be limited to only the items that match the search keyword.

### Additional context

If this is not how the search should work, could you explain how this should work then or point me to the documentation that explains it.

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.1.11, I assume you were pressing enter after you entered your search query (which is required) but appears to work fine: https://www.loom.com/share/e5d3c788e060425c8d335f4f0c42202a

Going to set this as closed until the OP provides additional information, could be possible a community plugin is conflicting with the search? Unlikely but possible I suppose.

**Comment by benderillo** [comment]
Well it does not work for me and I use the same version.
Would appreciate any hints on how to debug it to figure out what's causing it.
Where to look first? 
Clearly, hitting enter creates the right query "_q=nothing" and the query is sent to content-manager api... but either result is not filtered or refresh is not done correctly in ui...

**Comment by benderillo** [comment]
Nevermind. It was me all along. 
I patched `@strapi/database` with support for `mysql2` as a dialect by simply doing a fall-through in the [`database/lib/dialects/index.js`](https://github.com/strapi/strapi/blob/d3b957e5c66d023e313f79d51a56d36767a3fa28/packages/core/database/lib/dialects/index.js#L7) like so:

```diff
-   case 'mysql':
+  case 'mysql':
+  case 'mysql2':
      return require('./mysql');
```

But turned out it was not enough because the code in `@strapi/database/lib/query/helpers/search.js::applySearch` has its own switch on a dialect!
https://github.com/strapi/strapi/blob/d3b957e5c66d023e313f79d51a56d36767a3fa28/packages/core/database/lib/query/helpers/search.js#L44-L52

Frankly, this switch is a code smell and violation of the DRY principle, and should not exist. Each dialect should expose a function that does the preparation of the search columns in its own fashion. So the code in the `search.js` could just blindly call it.
