### ISSUE TITLE
Public Rule api returns 401 on the server when long time no request

### ISSUE THREAD

**Issue by ray0324** [strapi/strapi#13388]
## Bug report

Public Rule api returns 401 on the server when long time no request
reproduce  frequecy:  first 2 requst every day  

then it seems ok

### Required System information

- Node.js version: v16.14.2
- NPM version:8.9.0
- Strapi version: 4.1.11
- Database:mysql
- Operating system: centOS

### Expected behavior

return 200 

### Screenshots

<img width="846" alt="WX20220523-102438@2x" src="https://user-images.githubusercontent.com/5204198/170185535-0da0297e-9d10-4283-9f5e-08f9499f247a.png">
<img width="1253" alt="WX20220525-101532@2x" src="https://user-images.githubusercontent.com/5204198/170185560-297f815d-5ecb-423b-b1bf-56dae3bd0184.png">

**Comment by bang88** [comment]
I have the same issue too. very strange. There are no reproduction steps here just leave the website there and then re-open the browser after a few hours. the first request will get a 401 error and if you refresh the webpage it will return the correct result.

**Comment by midas104** [comment]
We have similar issues. After long delay without requests we have 401

**Comment by midas104** [comment]
I think it's related to this code
```

    const publicPermissions = await strapi.query('plugin::users-permissions.permission').findMany({
      where: {
        role: { type: 'public' },
      },
    });

    if (publicPermissions.length === 0) {
      return { authenticated: false };
    }

    return {
      authenticated: true,
      credentials: null,
    };
  } catch (err) {
    return { authenticated: false };
  }
```

if for some reason server lost connection to DB then it will throw 401

**Comment by kwiat1990** [comment]
I experience currently the very same issue with Strapi `4.1.2` and `4.2.0` as well and Postgres. 

Hitting one of public API routes after a few hours without of idle get me always an 401 error with this message: `missing or invalid credentials`.

I‘ve check this a few times already, also in incognito mode with the same results: the first request returns the error and the following requests do work as expected. 

In Strapi log I can see following connection error for the initial request `Connection Error: Connection ended unexpectedly`.

**Comment by derrickmehaffy** [comment]
> I experience currently the very same issue with Strapi `4.1.2` and `4.2.0` as well and Postgres.
> 
> Hitting one of public API routes after a few hours without of idle get me always an 401 error with this message: `missing or invalid credentials`.
> 
> I‘ve check this a few times already, also in incognito mode with the same results: the first request returns the error and the following requests do work as expected.
> 
> In Strapi log I can see following connection error for the initial request `Connection Error: Connection ended unexpectedly`.
> 
> @derrickmehaffy it‘s definitely an existing problem.
> 
> EDIT: after defining in `database.js` a `pool` object with minimal value set to 0 (followed @midas104 last comment), Strapi seems to be working fine and after a few hours of inactivity on my page the mentioned connection error doesn’t show up.

I'm guessing you are also in a docker or container based env? The issue we identified was not a Strapi one but Docker killing idle connections after a period of time. Some kind of maximum connection timeout.

**Comment by kwiat1990** [comment]
Yes, my Strapi instance runs inside a Docker container as I use Caprover to manage my server. After I’ve added those DB connection settings to `database.js` it doesn’t kill idle connections anymore. I don’t know what performance impact it can have but I guess it doesn’t matter in my case (low traffic).

**Comment by alexandrepaiva-dev** [comment]
I'm having this issue as well (Strapi v4.3.6). I'm going to try that db config proposed by @midas104 - hopefully that will fix it in my case too.

**Comment by derrickmehaffy** [comment]
> Yes, my Strapi instance runs inside a Docker container as I use Caprover to manage my server. After I’ve added those DB connection settings to `database.js` it doesn’t kill idle connections anymore. I don’t know what performance impact it can have but I guess it doesn’t matter in my case (low traffic).

It should be fairly small as you will just see a small latency around the TCP handshake: https://www.geeksforgeeks.org/tcp-3-way-handshake-process/

which should be only a few ms depending on your ping

**Comment by fabus961** [comment]
I solved it when opening the page / development page in a new incognito tab.
