### ISSUE TITLE
Upsert entity doesn't cleanup existing components

### ISSUE THREAD

**Issue by Keith-Hon** [strapi/strapi#13385]
Describe the bug

When I try to upsert entities which has components defined, new components keep adding to the table and leaving the old ones staying in the database. This keep increasing the table size and not ideal.

Steps to reproduce the behavior
Create a content type with a component defined and keep upserting entities.

System
Node.js version: v12.22.8
NPM version: 6.14.15
Strapi version: v4.1.10
Database: postgres
Operating system: ubuntu 20.04.2 LTS

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
