### ISSUE TITLE
Possibility to query / select a custom function !

### ISSUE THREAD

**Issue by itisnajim** [strapi/strapi#13384]
**Required System information**
Node.js version: v14.17.6
NPM version: 6.14.15
Strapi version: 4.1.11
Database: PosgreSQL
Operating system: Ubuntu 18.04 (LTS) x64

**Describe the bug**

Find entries using [Query Engine API](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/single-operations.html#findmany) with selecting a [PostgreSQL](https://www.postgresql.org/) function or a custom created one as a column not supported yet !

*Example:* [earthdistance](https://www.postgresql.org/docs/current/earthdistance.html)
```ts
const latitude = 33.9692189;
const longitude = -6.8572628;
const entries = await strapi.db.query('api::place.place').findMany({
  select: ['*', `earth_distance(ll_to_earth(latitude, longitude), ll_to_earth(${latitude}, ${longitude})) as distance`],
  where: { distance: {$lt: 1000} },
  orderBy: { distance: 'ASC' },
  populate: { category: true },
});
```

**Expected behavior**
Selecting whatever i want, not just the predefined fields/columns in the table.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by derrickmehaffy** [comment]
For feature requests can you please open them on our feature request website: https://feedback.strapi.io


We are now only allowing bug reports on the GitHub issues.

Thanks!
