### ISSUE TITLE
Strapi Jekyll Pagination Conflicting

### ISSUE THREAD

**Issue by csharpee** [strapi/strapi#13382]
My entire Jekyll site depends on a lot of functionality from this plugin. 

I am unable to use this plugin and Strapi because the posts, products, pages, etc.. are loaded from the Strapi API. 

as an example, 

a strapi jekyll GET posts

```
---
layout: default
---

<div class="home">
  <h1 class="page-heading">Restaurants</h1>
  {%- if strapi.collections.restaurants.size > 0 -%}
  <ul>
    {%- for restaurant in strapi.collections.restaurants -%}
    <li>
      {{ restaurant.name }}
    </li>
    {%- endfor -%}
  </ul>
  {%- endif -%}
</div>
```
a paginatev2 jekyll example, 

```
<!--  Featured Product Posts -->
<section class="row">
	{%- assign featured_posts = paginator.posts | slice: 1, 4 -%}
	{%- for post in featured_posts -%}
		{%- include product_featured.html -%}
	{%- endfor -%}
</section>
```

I want to store the data in an api and have jekyll build and pull that data, but to do so means I will have to completely change my setup.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
