### ISSUE TITLE
Content manager doesn't work correctly

### ISSUE THREAD

**Issue by JuliaSamofal** [strapi/strapi#13389]
Hello,
1. When you go to Content manager
2. Click on Section 
3. Section doesn't load
4. You can see the error  
content-manager.13f391a8.chunk.js:70 
TypeError: Cannot read properties of undefined (reading 'reduce')
    at ko (content-manager.13f391a8.chunk.js:70:8775)
    at content-manager.13f391a8.chunk.js:70:8108
    at Array.forEach (<anonymous>)
    at Eu (content-manager.13f391a8.chunk.js:70:8088)
    at content-manager.13f391a8.chunk.js:70:12444
    at Generator.next (<anonymous>)
    at i (content-manager.13f391a8.chunk.js:70:11853)

<img width="1440" alt="Screenshot 2022-05-25 at 10 08 55" src="https://user-images.githubusercontent.com/106232710/170214356-a37720a4-a5cf-40aa-97ff-b88a60ab9b2a.png">

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by hsnbsst** [comment]
I have that same problem

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
