### ISSUE TITLE
Admin panel can't load in heroku deployment

### ISSUE THREAD

**Issue by st4l1nR** [strapi/strapi#13381]
### Required System information

- Node.js version:16.15.0
- NPM version: 8.10.0
- Strapi version: 4.1.0
- Database: postgress
- Operating system: Windows 10

### Describe the bug

Admin panel  can't load in heroku deployment
![image](https://user-images.githubusercontent.com/61132529/169888059-d84dd914-06cc-4a9a-bf70-7fe76b4b70e9.png)
![image](https://user-images.githubusercontent.com/61132529/169888716-526b6a2d-f5b7-4123-a537-319aca0ea192.png)
![image](https://user-images.githubusercontent.com/61132529/169888749-5446de4b-8731-42f4-8ad8-47af427fb654.png)

### Steps to reproduce the behavior
I implement the same configuration as in [heroku setup ](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#heroku-install-requirements) for strapi

**Comment by derrickmehaffy** [comment]
> Strapi version: 4.1.0

Can you please test on the latest version which at the time of writing is 4.1.11

Closing for now as there is no steps to reproduce and following the documentation for Heroku doesn't trigger the error
