### ISSUE TITLE
Strapi Dashboard is not fetching Content Types data from Database

### ISSUE THREAD

**Issue by SarathSantoshDamaraju** [strapi/strapi#1339]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.12.2
- **Database**: Mongodb (3.6.5) both Shell and Server
- **Operating system**: High Sierra (10.13.4)

**What is the current behavior?**

I don't see any user related data after registering on the **newly**  created strapi app. Below is the screen that I see in the `Content Types > Users`.

<img width="1440" alt="screen shot 2018-06-07 at 6 22 30 pm" src="https://user-images.githubusercontent.com/10527102/41100748-ca251bc6-6a7f-11e8-9aad-224b9aa23e76.png">

 So I tried creating a new user and I don't see any roles to assign. 

![dashboard](https://user-images.githubusercontent.com/10527102/41099080-11c2c6f4-6a7b-11e8-818d-7b179772e2f1.png)

I see only one error and this is the trace :-
```
Unable to load "zh-Hans" translation for the plugin analytics. Please make sure "zh-Hans.json" file exists in "pluginPath/admin/src/translations" folder.
a @ main.js:14
(anonymous) @ main.js:14
m @ main.js:1
pa @ main.js:1
./node_modules/strapi-helper-plugin/lib/src/i18n.js @ main.js:14
t @ main.js:1
./node_modules/strapi-helper-plugin/lib/src/app.js @ main.js:14
t @ main.js:1
../strapi-admin/node_modules/strapi-helper-plugin/node_modules/fbjs/lib/emptyFunction.js @ main.js:1
(anonymous) @ main.js:1
```
I could conform that data is stored in the Database but somehow dashboard is unable to fetch it

![db](https://user-images.githubusercontent.com/10527102/41100233-71132a60-6a7e-11e8-9bec-36edecc614eb.png)

Following are the checks I used to see the consistency of the issue:

1. Restart the Server
2. Create and test app every time from different browsers
  2.1 Chrome:  66.0.3359.181 (64-bit)
  2.2 Firefox: 61.0b10 (64-bit)
  2.3 Opera: 52.0
3. Check for the Roles & Permissions and see if Database is running.
4. Delete `node_modules` and install them again.

This is the same case even with **Custom Content Types**. I can see the data in the database but it is not being fetched into the dashboard

<img width="1440" alt="screen shot 2018-06-07 at 5 52 34 pm" src="https://user-images.githubusercontent.com/10527102/41100387-d7f5d0a2-6a7e-11e8-8c7e-2ed2cf35a96f.png">

**I can able to access the data from Public API, but unable to see them in the dashboard**

**Steps to reproduce the problem**
I have just followed the steps mentioned in the [Getting Started](https://strapi.io/getting-started) page

**Comment by SarathSantoshDamaraju** [comment]
Surprisingly, Uninstalling and Reinstalling Strapi, has fixed the above issue, But before that it was very redundant. Anyways keeping it open and you can close it if you feel it is not replicable.

**Comment by mwdwrd** [comment]
Happening to me as well now. Same as above.

**Comment by rodrigoWollies** [comment]
+1

**Comment by sdinesh86** [comment]
I also faced similar issue but just stopping and restarting the server worked for me

**Comment by mnlbox** [comment]
Maybe related: #1271

**Comment by lauriejim** [comment]
So it happen randomly... Can you guys try with the last version of Strapi, fresh new app and fresh new database. Tell me if it still happen please.

**Comment by SarathSantoshDamaraju** [comment]
Yes @lauriejim , I have tried that as well before reinstalling Strapi. Even that was not helpful.

**Comment by sidharthv96** [comment]
When I update an object from content manager, the user relation becomes null. Related?

**Comment by SarathSantoshDamaraju** [comment]
@sidharthv96 , I don't think so. Do you see any errors? or tried restarting the server ?

**Comment by lauriejim** [comment]
@SarathSantoshDamaraju So looks good now ?

**Comment by SarathSantoshDamaraju** [comment]
@lauriejim , Working fine for me.

**Comment by abhimediratta** [comment]
I restarted the system and the data started displaying again, for me.

**Comment by cesarvarela** [comment]
This is happening to me now

**Comment by nom4da** [comment]
It's happening to me as well. It only shows the Content Types first time I login, but if I refresh the browser only Users is shown. 

Seems that on refresh it doesn't make this request:
http://localhost:1337/content-manager/models

**Comment by asherccohen** [comment]
"strapi": "3.0.0-beta.19.3",

![Annotation 2020-05-04 103448](https://user-images.githubusercontent.com/34692625/80948821-26751c80-8df3-11ea-8207-b6f066eb5471.png)
![Annotation 2020-05-01 180336](https://user-images.githubusercontent.com/34692625/80949084-9aafc000-8df3-11ea-9fce-409b2fcee4dc.png)

I'm still having this issue. Only happens on PROD, jwt token is generated but entried from DB cannote be retrieved. Any help towards fixing this?

**Comment by icheered** [comment]
Sorry to necrobumb this, but I'm facing the exact same issue. I have 3 strapi instances, 3 database instances, and 3 node web servers running. 2/3 run fine, but the third has been giving me all kinds of issues. Data not showing in dashboard, first page load being terribly slow, even though the configuration seems to be identical in all 3 cases.

Did anybody figure out a solution or has any updates on this problem?
