### ISSUE TITLE
Bulk operations on internationalized content mess up with locales

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#13393]
### Required System information

- Node.js version: 16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.1.11
- Database: SQLite
- Operating system: MacOS

### Describe the bug

When using the Query Engine's `createMany` function, Strapi does not default the locale of the new entries to the default locale of the instance, which means that newly created entries are created in the database but cannot be seen in the admin panel.

This bug also allows users to use the Query Engine to create entities in locales other than those enabled on the Strapi instance.

### Steps to reproduce the behavior

1. Create a controller that runs a `createMany` query on an internationalizable content type, making sure not to specify a `locale` value.
2. Notice how browsing through that content type in the content manager, the new entries are not present.
3. Check your database and notice how the entires have in fact been created even though they are not visible.
4. Repeat (1) but passing in a value for `locale` that represents a locale you have not yet enabled on your instance, like `es` for Spanish or `it` for Italian.
5. Notice how (2) and (3) are still valid in this scenario as well.

### Expected behavior

The Query Engine should default the `locale` value to the instance's default locale or throw an error and not create the entries.

**Comment by WalkingPizza** [comment]
I'd be happy to work on a PR if we agree on a way to proceed!

**Comment by petersg83** [comment]
Hello :)
I think it's both an issue and not an issue.

- It's not an issue as it is intended that the query engine is not aware of this kind of logic. The query engine is a low-level (dumb) layer, the correct layer to manipulate entities is the entity service (you can check difference between the two [here](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine-api.html#query-engine-api)). For instance, no constraints (unique, minimum etc.) are checked on this layer, it's done on the layer above.
- However it is also an issue as I see this boundary was not respected and that the default locale is set when calling `strapi.db.query().create()`, so it is inconsistent that it is not set also for `strapi.db.query().createMany()`.

I created a PR (#15742) to fix this inconsistency by having `createMany` to set the default locale.
However we cannot prevent a wrong locale there.
