### ISSUE TITLE
API returns data in wrong/flattened format (without attributes field) randomly at times

### ISSUE THREAD

**Issue by jakubprzybylski** [strapi/strapi#13398]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.8
- Database: Postgresql
- Operating system: Windows

### Describe the bug

Small disclaimer: I can't use the appropriate names for my collections, because that would be data sensitive for the project.

I'm building components for two collection types using similar scheme, let's say I have Collection Type `Foo` and `Moo`. Both are complicated, they have some text fields, image fields and nested components.

For both of them, I've prepared components `Foos` and `Moos` that have `title`/`description` and most importantly a repeatable component `items` consisting of `Foo/Moo Item` component which contains some text and a related `Foo`/`Moo` (respectively) (`Foo`/`Moo Item` has one `Foo`/`Moo` (relation)).

Initially, I've prepared the API for `Foos` and it went great. But when I return the data of `Moos` component, the structure is not resembling Strapi V4 data structure (fields of the populated relation are together with "id", instead of being nested inside "attributes") and I don't know why. This obviously breaks my UI logic, as I expect the same response format (data containing id and attributes).

What's more, every data type that needs populating (such as image) is broken in the same way. Image in `Moo` inside `Moos` component has `url`, `name`, `caption` with `id` on the same level in API's response. Image in `Foo` has image parameters inside `attributes` field, which is correct.

### Steps to reproduce the behavior

1. Create some collection types.
2. Create a component that would have a relation containing the collection type like `Foo Item` that has one `Foo` (relation), `Moo Item` that has one `Moo` etc.
3. Create a component of higher order, such as `Moos` and `Foos`. Fill it with typical fields such as title, description but also repeatable field called items that has repeatable component created in Step 1.
4. At times, the response will omit attributes field and return data in a weird flat format, where id is together with other attributes on the same level in response format.

### Expected behavior

Everytime I receive a nested relation field within a component, I expect the same structure (data: { id, attributes }).

### Screenshots

![1](https://user-images.githubusercontent.com/27766718/170513331-85d6d633-fb74-4b21-8f1d-9a3a82087c96.png)
![2](https://user-images.githubusercontent.com/27766718/170513337-8d3e189a-3df9-4d4a-963c-2e9c18381799.png)
![3](https://user-images.githubusercontent.com/27766718/170513338-74d9b247-eb1b-4560-8d4b-5e0fd077a643.png)
![4](https://user-images.githubusercontent.com/27766718/170513339-3ca24497-1e08-4717-8eb7-31e45e425d9a.png)

**Comment by derrickmehaffy** [comment]
Not able to reproduce on v4.1.12

Do you have any community plugins installed? Is this locally or deployed somewhere?

We need some steps to reproduce.

**Comment by jakubprzybylski** [comment]
Hi,

I don't have any community plugins installed and it's locally. I don't really have any suggestions to reproduce it, but two things are specific for this data instance:
- the Moo collection type has a space in name, so it's generated with a '-' in model files and I created the relation model providing the moo name in Moo Item component with snake_case
- the Moo Item component (opposed to Foo Item component) has only the relation field inside.

So maybe it's possible that this bug occurs for relations with a space in name in components that contain solely the relation? My colleague wasn't able to reproduce it as well, but my guess would be that there is something in Strapi code that flattens the response in some unforeseen, omitted cases. Might be worth inspecting, because a generic React component on the front-end side stops working in case of receiving a different structure than the typical one (with data, id and attributes field). :)

**Comment by jakubprzybylski** [comment]
Oh, I have a different suggestion! Could it be because the problematic relation is populated on the fourth level inside nested components? Because I know that there are some limitations with nested components on Strapi v4, so perhaps the API gets lost on populating deeper fields as well.

So I'm retrieving a "Doo" entity and I populate the Moo using: "section.subsection.items.moo". Perhaps if it would be higher in order the bug wouldn't occur?
