### ISSUE TITLE
indexing database auto in schema.json

### ISSUE THREAD

**Issue by haidvams** [strapi/strapi#13409]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

in version 3 strapi has indexing in setting.json  but in version 4 it gone 
i can't indexing on file schema.json like this

 "fields": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::quiz.quiz",
       "index": 1 
    }

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
