### ISSUE TITLE
The npm run lint has a lot of errors

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1340]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.3
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The `npm run lint` 💥

**Steps to reproduce the problem**

<img width="1040" alt="screen shot 2018-06-07 at 14 46 04" src="https://user-images.githubusercontent.com/1007051/41100734-6c66abb6-6a62-11e8-909c-7ec35e380ec9.png">

<img width="1040" alt="screen shot 2018-06-07 at 14 46 43" src="https://user-images.githubusercontent.com/1007051/41100738-6f8d21da-6a62-11e8-98d5-a6942cc110ee.png">

Run `npm install`... And then:

<img width="1040" alt="screen shot 2018-06-07 at 14 50 23" src="https://user-images.githubusercontent.com/1007051/41100742-713a87ca-6a62-11e8-8a9b-17504929f8ec.png">

**What is the expected behavior?**

0 errors.

**Suggested solutions**

**Comment by abdonrd** [comment]
Anyway, I think we can remove the `node_modules` in the scripts as:

```json
"strapi": "strapi",
"lint": "eslint api/**/*.js config/**/*.js plugins/**/*.js",
```

**Comment by soupette** [comment]
the commands have change the lint is only run in the monorepo now.

i'm closing the issue
