### ISSUE TITLE
relationship in single component does not return in reposne

### ISSUE THREAD

**Issue by BisarAhmed** [strapi/strapi#13408]
### Required System information
- Node.js version: 16.15.0
- NPM version: 8.10.8
- Strapi version: 4.0.6
- Database: MySQL
- Operating system: Ubuntu 20.04

### Describe the bug

a relationship field  in component then add to single type like dynamic zone, when fetch the endpoints the relationship field does not return. even with populate=*

![relation](https://user-images.githubusercontent.com/98802178/170873629-ff3ce01b-9c71-4da3-b3c1-1adb75dc7792.png)

the tutorial_category does not return

### Expected behavior
 the relationship field value should be return

**Comment by derrickmehaffy** [comment]
I believe this user is referring to the end-user APIs in which the wildcard is intended to only go one level deep and the relationship specified is 2 levels deep.

The more complex population logic is required for this. Hence the won't fix label and closure of the issue.
