### ISSUE TITLE
[2022-05-30 16:27:06.962] error: Cannot read properties of undefined (reading 'update') TypeError: Cannot read properties of undefined (reading 'update')

### ISSUE THREAD

**Issue by sanju-cmd** [strapi/strapi#13414]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
