### ISSUE TITLE
translations for messages

### ISSUE THREAD

**Issue by redni** [strapi/strapi#1341]
**Informations**
- **Node.js version**: v10.4.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: MongoDB
- **Operating system**: Arch Linux

**What is the current behavior?**
Messages related to the API are not translated by Strapi. Message translation files exist in plug-in directories, but messages are always displayed in English.

**Steps to reproduce the problem**
Launching a Strapi with another language than English.

**What is the expected behavior?**
Using translations from the currently selected language instead of English.

**Suggested solutions**
Currently none. I did not check the code completely, but it seems to me that the admin panel uses the same files as the rest of the system? Unless I'm wrong and the messages need for separate translations?

![zrzut ekranu z 2018-06-07 18-54-28](https://user-images.githubusercontent.com/18102267/41114799-c198a8b4-6a85-11e8-9679-e6b2736e9295.png)
![zrzut ekranu z 2018-06-07 18-54-32](https://user-images.githubusercontent.com/18102267/41114800-c1c87878-6a85-11e8-9df1-a1e528fe4b6b.png)

**Comment by derrickmehaffy** [comment]
@redni I don't believe the API itself has any translations or any soft of localization option. The AdminUI translations are here: https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src/translations

**Comment by lauriejim** [comment]
Hi @redni !
API error message have to be in english. The message to display is translated in admin as @derrickmehaffy said.

**Comment by redni** [comment]
I do not want to re-open the issue but I would like to ask for information on how can I translate the erorr.messages shown in json if they are not downloaded from the translation catalogs?  It is not possible? I would like to make pop-up messages on my native language like json will show, for example, someone typed a wrong password or ID.

**Comment by derrickmehaffy** [comment]
@redni, you could do the translation on your application side. Basically check for x error message, then display y popup. Right now the API will only reply in English.

**Comment by lauriejim** [comment]
Error messages are handle by Boom node module.
You can add a middleware in your application to update messages.
