### ISSUE TITLE
Problem with cropping image

### ISSUE THREAD

**Issue by aggieSzulcDornach** [strapi/strapi#13417]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.1.10
- Database: Postgres

When I'm adding an image to media library, sometimes crop option is not working at all.
It's happening only when I'm trying to crop a picture right after uploading. When the pic is already in the media library everything seems to be fine.
I have no customizations.
I'm not sure what is causing this, it does not matter what type the file is. It just happens randomly.

![image](https://user-images.githubusercontent.com/95346609/171005291-e9e805da-4c6f-482d-b1d5-db80f4dc0adb.png)

Any help will be appreciated!

**Comment by derrickmehaffy** [comment]
Need steps to reproduce and/or ideally some short video showing what happens.

Marking as closed until reproduction steps are provided.

**Comment by aggieSzulcDornach** [comment]
Hi, here a video: [cropping image](https://www.loom.com/share/80082c15d5a2499189dcd4d83ef47930)

**Comment by gu-stav** [comment]
@aggieSzulcDornach Thanks for the video reproduction. Which browser are you using? Could you check the console of the developer tools to see, if there is any error message, which could give us a hint what is happening?

**Comment by derrickmehaffy** [comment]
@gu-stav I just tested and confirmed it on v4.1.12 using Chrome and Firefox (on linux). It only happens while you are uploading, before hitting the "upload x asset". You hit the edit button and try to crop before you upload (thus the file doesn't exist in the provider yet, it's only in the browser cache pending upload.)

**Comment by ray1005yb** [comment]
I encountered a different case.

Once I cropped the original asset, I could not crop it again.  I closed the window and tried again, but could not crop. There was no error log on console.

https://user-images.githubusercontent.com/26866972/173088718-ffa3d1c3-2770-49ed-9ab8-1d4c4931f2fb.mov

Node.js version: 16.15.0
NPM version 8.5.5
Strapi version: 4.1.12
Browser Chrome
Database: Amazon Aurora
Upload plugin: https://github.com/zoomoid/strapi-provider-upload-aws-s3-advanced

**Comment by gu-stav** [comment]
@ray1005yb Thank you. We'll have a look into that aswell, once we start looking into the issue.

**Comment by gu-stav** [comment]
I've created a PR which should both issues mentioned: https://github.com/strapi/strapi/pull/13706

**Comment by Tabish618** [comment]
I am encountering an issue while attempting to crop images in Strapi after integrating the AWS S3 plugin for image storage. The error message displayed is along the lines of "Cannot convert toBlob in canvas."

I have verified that there are no CORS issues in AWS S3, as I have allowed all origins. Despite this, the error persists.

Could you please advise on potential solutions or if there are any configurations I might have missed? Your assistance would be greatly appreciated.

I am using the strapi versions

 "@aws-sdk/client-secrets-manager": "^3.840.0",
    "@strapi/plugin-cloud": "5.19.0",
    "@strapi/plugin-users-permissions": "5.19.0",
    "@strapi/provider-upload-aws-s3": "^5.17.0",
    "@strapi/strapi": "5.19.0",
    "better-sqlite3": "11.3.0",

**Comment by atu-record** [comment]
@Tabish618  i had the same issue with cloudinary - seems to be an Strapi bug outputing the images without crossOrigin. solutions was patching it in `src/admin/app.ts`

```ts 
export default {
    bootstrap() {

        const observer = new MutationObserver((mutations) => {
            mutations.forEach((mutation) => {
                mutation.addedNodes.forEach((node) => {
                    if (node instanceof HTMLImageElement) {
                        patchImage(node);
                    }
                    if (node instanceof HTMLElement) {
                        node.querySelectorAll('img').forEach(patchImage);
                    }
                });
            });
        });

        observer.observe(document.body, {
            childList: true,
            subtree: true,
        });

        function patchImage(img: HTMLImageElement) {
            if (img.src.includes('res.cloudinary.com') && !img.crossOrigin) {
                img.crossOrigin = 'anonymous';
                const src = img.src;
                img.src = '';
                img.src = src;
            }
        }
    },
};
```
