### ISSUE TITLE
UI crashes for certain missing role permissions

### ISSUE THREAD

**Issue by Badestrand** [strapi/strapi#13413]
### Required System information

- Node.js version: v14.19.3
- NPM version: 6.14.17
- Strapi version: 4.1.12
- Database: SQLite
- Operating system: Ubuntu 20.04.

### Describe the bug

The dashboard gives a fully white screen and a console error when I go to a certain collection in my content manager as a non-admin user.

### Steps to reproduce the behavior

Sorry I can't give you a fully reproducible behaviour.

From the console error message and searching the source code I figured out that the bug comes from this line: https://github.com/strapi/strapi/blob/master/packages/core/admin/admin/src/content-manager/components/DynamicTable/CellContent/utils/hasContent.js#L48 where `content` was either null or undefined. 

I don't have any plugins installed or any modified source code, so just a plain intallation.

I already fixed it by granting the role all permissions but I am sure it still shouldn't occur either way. It appeared in a collection that had references to another collection which that user couldn't see with their permissions. After granting the role all permissions the error vanished. 

### Expected behavior

Not crashing the interface.

### Screenshots

-

### Code snippets

-

### Additional context

Feel free to close because it's too unspecific but I thought because I nailed it down to an exact line someone might have an idea what could have caused it.

**Comment by gu-stav** [comment]
@Badestrand Thanks for opening this issue. Could you share with us at least the content-model which creates the problem and the set of permissions you are applying? This would help to fix the issue much quicker ...

**Comment by kibblerz** [comment]
I don't believe this is a permissions issue. Is the error your experiencing showing in the browser console as an allPermissions issue? I was experiencing that, which i believe was a dependency resolution issue. I resolved it with PR #13513 and using Yarn PnP

**Comment by gu-stav** [comment]
@Badestrand I was able to reproduce the issue without `read` permissions on the role and created a PR to fix the issue. Thanks for reporting it.
