### ISSUE TITLE
Nested components/fields are missing in the UI after saving the content

### ISSUE THREAD

**Issue by rpoltorak** [strapi/strapi#13427]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.8
- Database: Postrgres/SQLite (checked on both)
- Operating system: MacOS Big Sur (11.6.1)

### Describe the bug

It looks like there's a bug with UI for the certain nested structures. Here's how my model looks like:

![screen_model](https://user-images.githubusercontent.com/16037518/171177989-91519a1c-7e6e-40ca-8262-e2e1256964ec.png)

What I'm trying to do is to attach an image to the most nested item (in this case represented by "Section Item" component). When I click "Save", everything is ok regarding the request, but unfortunately, the image is missing in the UI. What's important is that the image is missing only in the UI. If you fetch the data using the endpoint or check directly in the database, everything seems to be fine.

That problem seems to occur not only with images, but also with some other components that are deeply nested. The case with the image was the easiest one for me to replicate.

### Steps to reproduce the behavior

1. Go to the "Content Manager"
2. Select "Page" content type
3. Click on the first item from the list
4. Try to add an image to the most nested item represented by "Section Item" component
5. Click "Save"
6. See that the uploaded image is missing after saving the item.
7. See that the image has been submitted and existing in the database by checking the `http://localhost:1337/api/pages/1?populate=items.items.items.image` endpoint

### Expected behavior

The image should be visible after saving the item.

#### Model

![screen_model](https://user-images.githubusercontent.com/16037518/171177989-91519a1c-7e6e-40ca-8262-e2e1256964ec.png)

#### Error replication

https://user-images.githubusercontent.com/16037518/171180484-c7f8940d-4c14-4ecc-bcbf-8105b44cafe8.mov

#### Response from the endpoint

![Screenshot 2022-05-31 at 15 22 36](https://user-images.githubusercontent.com/16037518/171183882-3866ef15-d3be-4ed6-9d2b-a3e12fa69de6.png)

### Code snippets

[Repository with the all components that are necessary to reproduce this bug including the database](https://github.com/rpoltorak/strapi-error)

I've tried to simplify this as much as I could so to make this working please run `npm i`, `npm run develop` and log in with these credentials:

```
login: rklwxqymekpxjusbnu@bvhrk.com
password: Strapi1234
```

### Additional context

This is only my guess but it looks like the UI is re-rendered using the response from PUT request after saving the item. I've  checked that response and it looks like this:

#### Response from `PUT http://localhost:1337/content-manager/collection-types/api::page.page/1`

![Screenshot 2022-05-31 at 15 25 34](https://user-images.githubusercontent.com/16037518/171184197-a58a4d28-fef6-4fb8-be6e-06d6ca9baebc.png)

Maybe it could be helpful, that the most nested item has only image id instead of populating the whole object.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/11955
