### ISSUE TITLE
Custom route + custom action returns 403

### ISSUE THREAD

**Issue by yasinishyn** [strapi/strapi#13433]
## Bug report

Following [custom action creation documentation](https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#adding-a-new-controller) and [custom routes creation documentation](https://docs.strapi.io/developer-docs/latest/development/backend-customization/routes.html#creating-custom-routers) a new endpoit was added. After controller and router were defined, new methods were allowed via the `Settings -> USERS & PERMISSIONS PLUGIN -> Roles -> Public (or Authenticated, or public and Authenticated with different combinations)` (see the screenhsot).

When the method is called, I receive 403 every time.

### Required System information
- Node.js version: v16.0.0
- NPM version: 7.10.0
- Strapi version: 4.1.11
- Database: SQLite
- Operating system: MacOS

### Describe the bug

src/api/lastupdated/routes/lastupdated-company.js
```js
'use strict';

console.log('here here here')

module.exports = {
  routes: [
    {
      method: 'GET',
      path: '/lastupdated',
      handler: 'lastupdated.lastupdated',
    },
  ]
}
```

src/api/lastupdated/controllers/lastupdated.js
```
"use strict";

module.exports = {
  async lastupdated(ctx) {
    ctx.body = 'ok';
  },
};
```

### Steps to reproduce the behavior

1. Create a custom router
2. Create a custom controller
3. Allow the action with admin panel
4. Send the request

### Expected behavior

Status `200` with the body added in the controller

### Screenshots

<img width="557" alt="Screenshot 2022-05-31 at 18 34 00" src="https://user-images.githubusercontent.com/2759317/171212610-08b44ca7-2b30-4d73-ae7c-356fd99868e1.png">
<img width="341" alt="Screenshot 2022-05-31 at 18 34 05" src="https://user-images.githubusercontent.com/2759317/171212618-c1062474-2b23-4bb3-9fad-adfccd98b177.png">

### Additional context

Any other API methods work as expected.
If the unexisting endpoint is called I receive a 404.
If a none-existing controller method is given to the router, the build fails.
The problem is with the allow/un-allow methods via the admin panel, or this is what it seems to be.

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.1.12: 

![image](https://user-images.githubusercontent.com/8593673/171291250-07bbb90c-f4ee-4409-8c1f-e0ca4c6d0380.png)
![image](https://user-images.githubusercontent.com/8593673/171291257-23b0eaeb-cb56-4cdd-8e7c-02f1dfcf10ae.png)

**Comment by yasinishyn** [comment]
@derrickmehaffy 
thank you for helping.

I found the problem.

I've tried to do the same and it worked. The main difference is that I was using an "Authenticated" Read-only token. 

If you have a read-only token, you have to add this to your custom route config in order for this to work:

```js
      config: {
        auth: {
          scope: ['find']
        }
      }
```

Another option is to use a `full-access` token, or to make the endpoint fully public like [here](https://github.com/strapi/strapi/issues/13433#issuecomment-1142678278)

**Comment by smoothdvd** [comment]
@yasinishyn But if config with scope: ['find'], authenticated user with jwt token can not access this custom route ( return with 403).
