### ISSUE TITLE
npm install  sharp  Command failed

### ISSUE THREAD

**Issue by licao** [strapi/strapi#13436]
warning "@strapi/strapi > @strapi/admin > @strapi/design-system@1.1.1" has incorrect peer dependency "@strapi/icons@^0.0.1-alpha.73".
warning "@strapi/plugin-users-permissions > react-redux@7.2.3" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
warning "@strapi/strapi > @strapi/admin > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "@strapi/strapi > @strapi/admin > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.12" has unmet peer dependency "formik@^2.2.6".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.12" has unmet peer dependency "immer@9.0.6".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.12" has unmet peer dependency "qs@6.10.1".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.1.12" has unmet peer dependency "react-select@^4.0.2".
warning "@strapi/strapi > @strapi/admin > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning "@strapi/plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
[11/12] ⡀ better-sqlite3
[-/12] ⢀ waiting...
[-/12] ⢀ waiting...
[10/12] ⢀ sharp
error D:\mywork\code\my-project\node_modules\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: D:\mywork\code\my-project\node_modules\sharp
Output:

**Comment by licao** [comment]
npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp"
npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips"
npm install sharp

fixed it

**Comment by denics** [comment]
Hi @derrickmehaffy please re open this issue, especially because solution proposed here 

> npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp" npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips" npm install sharp
> 
> fixed it

does not work anymore as NPM does not allow custom variables :(

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy please re open this issue, especially because solution proposed here 
> 
> > npm config set sharp_binary_host "https://npmmirror.com/mirrors/sharp" npm config set sharp_libvips_binary_host "https://npmmirror.com/mirrors/sharp-libvips" npm install sharp
> > 
> > fixed it
> 
> does not work anymore as NPM does not allow custom variables :(

Best to open a new issue that respects our issue template.

**Comment by xingqiwu55555** [comment]
> NPM does not allow custom variables

I met the same issue, so any update for this?

**Comment by jy1989** [comment]
> > NPM does not allow custom variables
> 
> I met the same issue, so any update for this?

`yarn config set` is ok
