### ISSUE TITLE
failing unit tests

### ISSUE THREAD

**Issue by DanielRuf** [strapi/strapi#1343]
The tests are failing for PRs

https://travis-ci.org/strapi/strapi/builds/389351042#L485

**Comment by lauriejim** [comment]
Hello @DanielRuf !

PR you did cause this issue. All others works fine.
Let discuss of that on your PRs

**Comment by DanielRuf** [comment]
> Hello @DanielRuf !
> 
> PR you did cause this issue. All others works fine.
> Let discuss of that on your PRs

Are you sure? => https://travis-ci.org/strapi/strapi/builds/389718656

**Comment by DanielRuf** [comment]
Also this was not my PR: https://travis-ci.org/strapi/strapi/builds/389351042#L485

**Comment by lauriejim** [comment]
Caused by timeout. All build are OK
