### ISSUE TITLE
Mysql Count only responds with 404

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1344]
**Informations**
- **Node.js version**: v10.4.0
- **npm version**: v6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: MariaDB (MySQL) v10.2.15
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

Using any model count returns a 404 Error

**Steps to reproduce the problem**

Using the above node/npm/strapi/mysql versions, create a model, provide data, and use the /-modelname-/count will return a 404

**What is the expected behavior?**

Count should respond with the proper value

**Suggested solutions**

Unknown as I am not sure what the cause is for the 404 error. All models have the proper count entries in the following files (Used as examples in this case):

config/routes.json
https://github.com/canonn-science/CAPIv2-Strapi/blob/fc749cebddf9b616bc8eb78d58e0144b8a26aa09/api/system/config/routes.json#L19-L26

controllers/System.js
https://github.com/canonn-science/CAPIv2-Strapi/blob/fc749cebddf9b616bc8eb78d58e0144b8a26aa09/api/system/controllers/System.js#L31-L39

services/System.js
https://github.com/canonn-science/CAPIv2-Strapi/blob/fc749cebddf9b616bc8eb78d58e0144b8a26aa09/api/system/services/System.js#L70-L91

This is in all of my models, however all models provide a 404 both with public and with authentication (I have permissions setup properly to provide counts on public)

**Comment by derrickmehaffy** [comment]
Postman: 

![image](https://user-images.githubusercontent.com/8593673/41132965-23ec6a4e-6a92-11e8-93e2-b98cabab6a86.png)


And debug logs:

```
0|capidev  | { method: 'select',
0|capidev  |   options: {},
0|capidev  |   timeout: false,
0|capidev  |   cancelOnTimeout: false,
0|capidev  |   bindings: [ 'public', 1 ],
0|capidev  |   __knexQueryUid: 'a384563a-0aaf-4d16-83ed-3ca6a38baacd',
0|capidev  |   sql:
0|capidev  |    'select `users-permissions_role`.* from `users-permissions_role` where `users-permissions_role`.`type` = ? limit ?' }
0|capidev  | { method: 'select',
0|capidev  |   options: {},
0|capidev  |   timeout: false,
0|capidev  |   cancelOnTimeout: false,
0|capidev  |   bindings: [ 3, 'application', 'system', 'findone', true, 1 ],
0|capidev  |   __knexQueryUid: '0db486ae-f0df-46a5-9568-75b21edbb850',
0|capidev  |   sql:
0|capidev  |    'select `users-permissions_permission`.* from `users-permissions_permission` where `users-permissions_permission`.`role` = ? and `users-permissions_permission`.`type` = ? and `users-permissions_permission`.`controller` = ? and `users-permissions_permission`.`action` = ? and `users-permissions_permission`.`enabled` = ? limit ?' }
0|capidev  | { method: 'select',
0|capidev  |   options: {},
0|capidev  |   timeout: false,
0|capidev  |   cancelOnTimeout: false,
0|capidev  |   bindings: [ 'count', 1 ],
0|capidev  |   __knexQueryUid: '4f4d4069-7ec4-4226-a103-d4d2ec17a297',
0|capidev  |   sql:
0|capidev  |    'select `systems`.* from `systems` where `systems`.`id` = ? limit ?' }
0|capidev  | [2018-06-08T00:34:43.230Z] debug GET /system/count (6 ms)
```

**Comment by derrickmehaffy** [comment]
I am using pm2 instead of the normal strapi start but have modified my package.json to do so.

**Comment by derrickmehaffy** [comment]
I confirmed with a new fresh 12.3 project that it also responds with a 404 error.

@okaris can you provide any help here, I know you created the PR for bookshelf on the count route: https://github.com/strapi/strapi/pull/1307

Along with the services and controllers: https://github.com/strapi/strapi/pull/1293

@lauriejim was testing done on this prior to release? Trying to make sure this isn't an issue with my environment.

**Comment by okaris** [comment]
> I am using pm2 instead of the normal strapi start but have modified my package.json to do so.
This shouldn't yield any problems.

Based on the files you've provided I can't see any reason for it to now work. Mongoose and Bookshelf uses the same routes template so there shouldn't be any errors in that. The `count` function uses almost the same code with `fetchAll` function. Only difference is it does not add `sort` `limit` `skip`. Can you tell me if fetchAll returns what it should as it is?

**Comment by derrickmehaffy** [comment]
@okaris Yes fetch all does what it needs to and works fine. To me it looks like the route isn't being called but it's hard to figure out as there is no error message in the console

**Comment by lauriejim** [comment]
Fix here https://github.com/strapi/strapi/pull/1352

**Comment by derrickmehaffy** [comment]
Nice catch @lauriejim, just curious on why moving them around fixes it?

**Comment by derrickmehaffy** [comment]
Can confirm the fix in https://github.com/strapi/strapi/pull/1352 works as intended, marking this as resolved. It will likely be pushed out in 12.4
