### ISSUE TITLE
Documentation Plugin doesn't generate Proper Type for the Localization prop , and doesn't generate Refs for Components in Dynamic Zones

### ISSUE THREAD

**Issue by meganoob1337** [strapi/strapi#13453]
### Required System information

- Node.js version: 14.17.6
- NPM version: 8.5.3
- Strapi version: 4.1.12
- Database: Postgres
- Operating system: MacOS

### Describe the bug

When Generating a OpenAPI documentation with the Documentation Plugin , Content-Types that Are localized have an Empty array for the "localizations" prop instead of the correct type.

Also it doesn't generate Proper refs for Components in Dynamic Zones, which Bloats the Documentation if there are many Components in Dynamic Zones that are used in multiple Content-Types.
This also Makes it not as UserFriendly to use with CodeGens ( i use Orval) because the Component-types in Dynamic Zones are not Named properly (for example A Slider Component is named AnyOf instead of Slider)

### Steps to reproduce the behavior

1. Go to Content Types , create A localized Content-type, add a Dynamic Zone, Create one or more Components and add them to the Dynamic Zone.
2. Go To Documentation Plugin and Create Documentation
3. Look at the Generated Documentation and see that Localizations prop shows an empty array as type instead of the proper Content-Type. also see that Dynamic Zone Components are not Reffed but just defined inside an AnyOf

### Expected behavior

Components in Dynamic Zones are Reffed.
the localizations prop shows the "parent" content type aswell

### Additional context
i Created A Patch for it and would like to submit it as a PR or have it implemented by someone from Strapi:

<snip> too much of a wall of text

**Comment by derrickmehaffy** [comment]
@meganoob1337 I snipped your patch out, in the future can you zip those and just attach the zip file? I should have mentioned that to you in Discord but wasn't paying attention. If you want to see an example, see this: https://github.com/strapi/strapi/pull/13435#issuecomment-1144114747

**Comment by meganoob1337** [comment]
[patches.zip](https://github.com/strapi/strapi/files/8837460/patches.zip)
Like this?
Added the Patch here
