### ISSUE TITLE
"Create new XXX" buttons and general editing/adding missing

### ISSUE THREAD

**Issue by mortenmoulder** [strapi/strapi#13469]
### Required System information

- Node.js version: 16.11.1
- NPM version: 8.0.0
- Strapi version: 4.1.12
- Database: sqlite3
- Operating system: Windows 11

### Describe the bug

All the "Create new XXXXXX" buttons are missing when cloning the repository from production into a local machine, and changing the database from MySQL to sqlite3.

My user is Super Admin and I am running in development mode with `npm run develop` (after setting NODE_ENV to development).

My .env file is the same on production and my local machine. That's my only clue at this point, because APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET, and JWT_SECRET are identical, but I never cloned the database. My local machine is running with an empty sqlite3 database, from when I set up Strapi locally once (I copied the file from another repository).

### Steps to reproduce the behavior

1. Create with blog template: `npx create-strapi-app my-app-name --template blog`
2. Setup MySQL database connection
3. Call `npm run build`
4. Create another blog template `npx create-strapi-app my-app-name --template blog`
5. Setup sqlite3 database
6. Copy sqlite3 database file from `.tmp/data.db` into the MySQL project
7. Modify database.js with JavaScript from below
8. Set DB_DRIVER variable in `.env` file to `sqlite`
9. Set NODE_ENV to development
10. Run `npm run develop`
11. Login
12. No "Create new" buttons appearing and I can't modify anything

`database.js`

```
const path = require('path');

module.exports = ({ env }) => ({
  connection: env("DB_DRIVER", "mysql") === "mysql" ? {
    client: 'mysql',
    connection: {
      host: env('DATABASE_HOST', 'localhost'),
      port: env.int('DATABASE_PORT', 3306),
      database: env('DATABASE_NAME', 'strapi_db'),
      user: env('DATABASE_USERNAME', 'strapi'),
      password: env('DATABASE_PASSWORD', 'strapi'),
      ssl: env.bool('DATABASE_SSL', false),
    },
  } : {
    client: 'sqlite',
    connection: {
      filename: path.join(__dirname, '..', env('DATABASE_FILENAME', '.tmp/data.db')),
    },
    useNullAsDefault: true,
  },
});

```

### Expected behavior

Expected to be able to edit and modify anything

### Screenshots

![image](https://user-images.githubusercontent.com/1304665/172021229-ccda427c-5c79-448e-839c-32586022d8b5.png)

![image](https://user-images.githubusercontent.com/1304665/172021235-1372aecc-eef4-4002-b279-cd6a64db065c.png)

![image](https://user-images.githubusercontent.com/1304665/172021239-18cf84a4-0c05-40ad-88c6-033ce63cca6a.png)

**Comment by mortenmoulder** [comment]
I've found a reliable way to reproduce these steps. It's really broken and it prevents me from using Strapi. It's related to the issue in #13397

I can reproduce it by creating a blog from the templates, then simply going into the schema editor and removing something from the blocks section, such as media, quote, or slider. I think the problem is, there are already created articles, and those articles contain some of the sections I am trying to remove.

If I remove the build directory and node_modules, then run `npm install` and `npm run develop`, the sections I just removed (media, quote, and slider) are still there and the create buttons are gone.

I then checked with git to see which files were affected, and it was only the article schema file. This means that something in the database was changed and I am now unable to create new stuff. Why? No clue. Where in the database? No clue. But I do know it's very annoying, that I can't even remove sections (that are in use) without having to completely start from scratch with a brand new project. I can reproduce this on 4.1.11 as well.

**Comment by mortenmoulder** [comment]
What I did to reproduce a white screen with the `Cannot read properties of undefined (reading 'startSection')` message :

1. Create new project with `npx create-strapi-app my-app-name --template blog --quickstart`
2. Navigate to http://localhost:1337/admin and create an admin account
3. Go to the Content-Type Builder and find the Article collection type: http://localhost:1337/admin/plugins/content-type-builder/content-types/api::article.article (https://i.imgur.com/9LNSaqh.png)
4. Remove Media, Quote, and Slider from the blocks section and press save: https://i.imgur.com/FNBiFaN.mp4
5. Stop the application by pressing CTRL+C in the terminal
6. Run `npm run build`
7. Run `npm run develop`
8. Go to the Content Manager and open the Article collection type: https://i.imgur.com/3WHyeub.png
9. Click on an article (for example "The internet's Own boy" with ID = 1)
10. Go to the Content-Type Builder, find the Article collection type, and add the Media, Quote, and Slider to the blocks section again
11. Go to the article from step 8-9 and they work again
12. Remove the Media, Quote, and Slider from the article you opened
13. Repeat step 3-4
14. Go to the article again and now it works again, but the other articles (that still have data in those components we just removed) are broken

---

What I did to reproduce no create buttons:

Create an app.js file with the following content:

```
const strapi = require('@strapi/strapi');
strapi().start();
```

Run `node app.js`

If I run `npm run develop` it works just like normally again. I need to run the NodeJS command, because I run Strapi in Plesk.

**Comment by derrickmehaffy** [comment]
> Create an app.js file with the following content:

This is normal as there is no way to start the development mode via a file like this (what you are doing here is basically doing a `yarn start` or `npm run start` which doesn't have autoReload enabled).

We do not support running a development server in a deployed environment as the develop command is designed to only be used locally. Following the steps to reproduce any missing CTB actions while using `npm run develop` work just fine.

I'm gonna mark this issue as closed as I believe the issue revolves around something we don't support, which is running the develop mode via a startup file.

**Comment by derrickmehaffy** [comment]
If I'm wrong, do let me know and I can reopen this.

**Comment by mortenmoulder** [comment]
@derrickmehaffy I was able to recreate this issue, and I now have a solution locally, where running `npm run develop` does not have the buttons. I have also confirmed that it says:

```
The autoReload feature is required to use this plugin. Start your server with `strapi develop`
```

I have verified that everything is running in development mode as well.

Since the project might contain some user logs and emails, how do you want me to distribute the project, so you can just run `npm install` and `npm run develop` to confirm and debug? I have a link to a .zip file with the project (including SQLite DB but no node_modules), so however you want to receive that, let me know.

**Comment by mortenmoulder** [comment]
Aha.. I have no idea how this works, but I have found yet another bug.. and I have no idea why.

So I did a `grep -rnw "my@email.com" .` and I only found my email in .git directory. I therefore assume my user is in the database, so I looked at the admin_users table in the SQLite database. Sure enough, my user was there.

I then changed my email to something else, but it wasn't affected in the database. Huh, weird. I then changed my password, and the same thing happened. I then ran `git status` and saw 0 affected files (my database is not included).

I logged out and logged in with the new email and new password, and those worked fine. However, still no sign of my credentials anywhere. Maybe in the browser cached? Nope, I could still log in via incognito mode.

So I decided to delete my `.cache` and `build` directories, run `npm run build` and finally `npm run develop`. Now I could not log in anymore. However, I could still log in with my old credentials.. and guess what.. the create buttons appeared again. And if I change my email or password, it's affected in the database as well. The autoReload feature message also disappeared.

For the record, I did run `npm run develop` a lot of times before removing the cache and build directories, just to make sure it wasn't NodeJS that did some caching.

So now my project works and I have 0 changed files in git, which would probably also mean, that even if I did send the ZIP to you, you couldn't reproduce it. I have no idea how on earth you would ever be able to reproduce this, but there's definitely a bug somewhere. Maybe start by looking at your "save user" pipeline, to see if the user gets saved somewhere else than the database.

**Comment by mortenmoulder** [comment]
The madness continues.

If I add `url: 'https://my_production_url.com'` to the server.js, it updates the production database.. when running it in development mode... locally. Is this documented anywhere? This entire issue is literally surrounded around me adding the URL to my production API in the server.js file.

I can't find any documentation about this, so I'm guessing I just have to remove it and then it works locally and in production. 

Man... You guys should really, really, REALLY add some very, very specific variable that an user need to set, to be able to modify production data locally. Something like:

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 3000),
  url: 'https://api.website.com',
  i_understand_that_setting_this_to_true_will_allow_localhost_to_modify_production: true
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

Strapi should definitely check if the URL in server.js is different from the development URL, and then throw a big fat red warning on /admin. I spent way too long trying to figure this problem out.

**Comment by mortenmoulder** [comment]
@derrickmehaffy So please tell me this... If you lock down editing collection types in /admin in production, but you don't lock it down in development contacting a production database, what's the point of locking it down in production in the first place?

It seems like a weird hack, that I am allowed to modify the production environment while running it locally in development. I could understand it if I was changing a connection string to the database, and I accidentally selected the production database, but I am simply changing an URL. I even specified the local database in the database.js file.

I'm sure I'm not the only one, who thinks this is weird.

**Comment by mortenmoulder** [comment]
@derrickmehaffy I have not watcher enabled, no. Not unless it's automatically enabled when running `npm run develop`.

What I think is weird is:

1. I build the application in development mode
2. I check on / that I am in development mode
3. My host and port in `server.js` are set to 0.0.0.0 and 3000
4. My database in `database.js` is set to use a local database

But if I add `url: "https://production-website.com"` to `server.js`, none of the details above matter anymore. 

I think it's fundamentally wrong, that all your development settings can be bypassed simply by entering the production URL. Here are some ideas:

- Show a warning on /admin saying that `url` (from `server.js`) differs from `location.href`
- Show a warning on /admin, when `GET /` returns development and `GET {url}` returns production
  - Ultimatively it would be nice, that the user had to accept, that they are running in development but the URL targets a production environment (like a popup that you can hide, which lasts until session expiry or save it on the user)
- Completely disable the possibility of changing production data when running in development, except if you bypass it with a property such as `i_understand_that_setting_this_to_true_will_allow_localhost_to_modify_production` (obviously find a better name)

I hope it makes sense to you. I was so close to disbanding Strapi completely, because I couldn't figure out, why I couldn't modify stuff when running locally in development mode. That's when I found out, my local development instance was targeting my production environment, all because of one simple property in the `server.js` file. Had I seen a popup that told me, I was targeting a production environment, I would've put two and two together.

**Comment by derrickmehaffy** [comment]
The logic to handle this would exist on the backend, not the admin so your suggestions here won't work.

I understand what your trying to do, but your logic depends on the Strapi backend serving the admin and in many cases it doesn't.

Your logic fits an SSR application, not a CSR one. Our admin doesn't use Next it's just bare bones react and it goes where it's told.

My best suggestion here is double checking what URL you set. At the end of the day it's the responsibility of the engineer deploying the application to ensure they set the correct settings.
