### ISSUE TITLE
i18n Installation is not effective

### ISSUE THREAD

**Issue by milerL** [strapi/strapi#13475]
### Required System information

- Node.js version: v16.14.2
- NPM version:8.12.0
- Strapi version:{
    "@strapi/plugin-graphql": "^4.1.12",
    "@strapi/plugin-i18n": "^4.1.12",
    "@strapi/plugin-users-permissions": "4.1.12",
    "@strapi/strapi": "4.1.12",
    "better-sqlite3": "7.4.6",
    "pg": "^8.7.3",
    "strapi-provider-upload-oss": "^0.1.6"
  }
- Database:postgres
- Operating system:

### Describe the bug

https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html
Strapi is installed through documentation, but I18N is installed by default but not effective

Why my page doesn't have Locales？

### Screenshots
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/26897689/172118192-2565af5a-1022-4403-abc3-5a2b3c6f502b.png">
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/26897689/172118270-a0902591-075b-46e1-9bba-45de06e80558.png">
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/26897689/172118432-2d9389a5-fb8d-4165-b225-884f5cb3e15b.png">
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/26897689/172118817-91fd6d91-424a-4a2a-8560-fcb77e2e3331.png">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
