### ISSUE TITLE
Check file extension on loading routing files

### ISSUE THREAD

**Issue by danieldormann** [strapi/strapi#13476]
Hi all,

I noticed strapi doesn't seem to check on file extensions when loading files in src/api/*/routes. Practically speaking:

When editing files with vim, it creates a temporary swap file in the same folder. For instance editing example.js will create .example.js.swp for the time editing. Now while working in the routes directory in development mode will lead to reloading the strapi instance and then crashing, with a random exception, because obviously the format is not expected.

At least for controller files this doesn't seem to be the case, I suspect we could find the same behavior for other api files.

For reproducing, just create any non js format file:

`echo "foo" > src/api/hello-world/routes/whatever.foo`

strapi version is 4.1.8

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
