### ISSUE TITLE
Register with gmail addresses doesn't work / email confirmation

### ISSUE THREAD

**Issue by dsfaccini** [strapi/strapi#13472]
### Required System information

- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: v4.1.12
- Database: sqlite
- Operating system: Windows11

### Describe the bug

When I register using an @gmail address whilst email confirmation is on, the response is 
```
status 400 bad request 
{"data":null,"error":{"status":400,"name":"ApplicationError","message":"Email already taken","details":{}}}
```
The user is registered on the strapi admin though, the problem is the frontend has no way of knowing
The weirdest thing is, looking at the code that preemptively returns the register function -- BEFORE ADDING THE USER -- I can't see why the user is possibly getting registered.

```javascript
// node_modules\@strapi\plugin-users-permissions\server\controllers\auth.js
// line 322

const user = await strapi.query('plugin::users-permissions.user').findOne({
      where: { email: params.email },
    });

if (user && user.provider === params.provider) {
      /*davidcomment*/
      console.log("{ email: params.email }", { email: params.email }, "user", user);
      throw new ApplicationError('Email is already taken');
    }
```
I guess the real quesiton is why the strapi query is finding a user with a different email address

For an @hotmail address it returns status 200 data: new_user 
So @gmail addresses are f***ed I guess?
Also strapi doesn't handle address+strapi@gmail.com. If I then use address+strapi2@gmail.com it registers as a separate user

### Steps to reproduce the behavior

1. run the server with "npm run develop"
2. go to http://localhost:1337/admin/settings/users-permissions/advanced-settings
3. set "Enable email confirmation"  to True
4. make POST request to http://localhost:1337/api/auth/local/register using e.g. 
5. ```json {"name": "david", "password": "davidpw", "email": "david@gmail.com",  "username": "david",}```
6. you can use https://chrome.google.com/webstore/detail/talend-api-tester-free-ed/aejoelaoggembcahagimdiliamlcdmfm or Postman or any REST interface
7. Read the response status and error
8. go to http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user?page=1&pageSize=10&sort=username:ASC and refresh
9. You'll see the user got created in spite of the error message in the response

### Expected behavior

response status 200 with the respective newly-created user data

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

There's also the problem that the "confirmed" field becomes useless if  "Enable email confirmation"  is set to False,, even though it could still be useful

**Comment by kibblerz** [comment]
The OAuth login that comes in the free version of Strapi only works with the users & permissions "Users" table. For OAuth to work with the Admin Users you either need the Gold plan, or to write your own logic tying the user to the admin and Generating a JWT Token.

**Comment by kibblerz** [comment]
`const user = await strapi.db.query('admin::user').findOne({
            where: {
              email: { $eq: profile.email }
            }
          })`
