### ISSUE TITLE
This attribute must be unique ValidationError: This attribute must be unique

### ISSUE THREAD

**Issue by Hirrad** [strapi/strapi#13470]
- Node.js version: 16.14.2
- NPM version: 8.9.0
- Strapi version: 4.1.11
- Operating system: Windows 10

### Describe the bug
Faced such an error during the registration test. When registering, almost when repeating no problems, an error is generated "Email is already taken" as it should be, but when there are repetitions with username, the error "An error occurred during account creation" is already issued + The strapi itself sees a validation error. At first I thought the problem was in the username itself, I created another unique field, but the error is the same and everything repeated.
I get exactly the same error, after even if I correct username i the data goes away on the server, and the exact same error when a non-existent mail is entered (if verification is almost enabled), a constant 400 error and the answer "An error occurred during account creation"

### Expected behavior

the answer should be "Username is already taken" and "Login is already taken" or something similar

### Screenshots
![strapi_error](https://user-images.githubusercontent.com/37995560/172027123-b827be70-83ab-4405-86f9-3c6befde03c7.jpg)
![api](https://user-images.githubusercontent.com/37995560/172027116-b0a434d2-64fe-4efe-aa42-65bd4d81916e.jpg)

**Comment by derrickmehaffy** [comment]
Should be fixed by: https://github.com/strapi/strapi/pull/13435
