### ISSUE TITLE
updateRole in UsersPermissions service is comparing users ObjectID references

### ISSUE THREAD

**Issue by victorlambert** [strapi/strapi#1347]
**Informations**
- **Node.js version**: 9.5.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: MongoDB 3.6.2
- **Operating system**: MacOS 10.13.3

**What is the current behavior?**
Any call of updateRole function of UsersPermissions service breaks the user roles relations, linking them to the authenticated role.

**Steps to reproduce the problem**
- Create a role 
- Affect one user to this new role
- Try to update the new role's permissions using ``strapi.plugins['users-permissions'].services.userspermissions.updateRole`` in a bootstrap function for example.
- After your role's permissions are updated, you'll see that the user will be affected back to the authenticated role.

**What is the expected behavior?**
User's role should not be modified. 

**Suggested solutions**
Change
https://github.com/strapi/strapi/blob/cbca97feb3417b082fe47a3f4830c9381d2e8631/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L392
https://github.com/strapi/strapi/blob/cbca97feb3417b082fe47a3f4830c9381d2e8631/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L399
To
```
_.differenceBy(body.users, role.users, val => role._id ? val._id.toString() : val.id.toString())
```

**Comment by lauriejim** [comment]
Hello @victorlambert .

The `body` object you have to send in the function contain an `users` key that contain users linked to this role.

Can you be sure you don't send an empty array for the `users` key.

**Comment by victorlambert** [comment]
Hey @lauriejim, I am sure that I do not send an empty array for users. But I just found why I had this issue. I was calling `getRole` and then `updateRole` on server side using a boostrap function. In this case, _.differenceBy 'id' is comparing users lists by ObjectID that do not have been parsed as JSON. So comparing users by ObjectID reference always return all users. These same functions (`getRole` and `updateRole`) called from REST through admin will compare 'id' as string (and not ObjectID) and run well as expected.

**Comment by JustBeYou** [comment]
@victorlambert  did you find any workaround to use `getRole` + `updateRole` in `bootstrap.js`?
