### ISSUE TITLE
How to obtain media data through API？

### ISSUE THREAD

**Issue by milerL** [strapi/strapi#13474]
### Required System information

- Node.js version:16.14.2
- NPM version:8.12.0
- Strapi version:4.12.0
- Database:postgres
- Operating system:macos

### Describe the bug
REST API  Unable to get media data!
Why is there no media data?
How do I get media data?

### Expected behavior

Media data can be obtained

### Screenshots

![image](https://user-images.githubusercontent.com/26897689/172113037-c87bf885-df72-4348-a735-ab10982a6be6.png)
![image](https://user-images.githubusercontent.com/26897689/172113076-731ce939-b560-412f-8da1-6cbafc7ea2ff.png)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
