### ISSUE TITLE
cannot query relationship field using graphql

### ISSUE THREAD

**Issue by web-programmer-here** [strapi/strapi#13483]
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: v4.1.12

### Describe the bug

I just tried the starter blog and can't query the relationship fields. 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/81479051/172287848-11e3ee42-9e49-41bd-9535-b15c94ce8701.png">

but there is no option to get the authors when querying for articles

<img width="323" alt="image" src="https://user-images.githubusercontent.com/81479051/172287924-2dc53df2-9708-4f4b-8526-c491017d8bfa.png">

Shouldn't be possible to query the relationship field? I also dont see one for the category

**Comment by bolg55** [comment]
Can you please let us know which blog starter you used and the exact steps to reproduce so we can better assist? Thanks

**Comment by web-programmer-here** [comment]
@bolg55 thanks, I cant remember which one, I was following a tutorial. It was something with the relationship field, after fixing that and restarting the server it works now. Closing the issue.
