### ISSUE TITLE
Enable versioning for this Content-Type is not work

### ISSUE THREAD

**Issue by NidMo** [strapi/strapi#13496]
### Required System information

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.1.12
- Database: mysql 5.7
- Operating system: windows 10

### Describe the bug

Enable versioning for this Content-Type is not work, will throw error: uuid is not a function

![image](https://user-images.githubusercontent.com/24955673/172548512-fd0fc9da-0542-4ea4-9e88-e24c6b0965dc.png)

### Steps to reproduce the behavior

1. Create any content type
2. Enable versioning for this Content-Type
3. save content

### Expected behavior

save success

**Comment by ailchenkoDynamo** [comment]
@NidMo Hello, How did you enable versioning for Content-Type? Thanks

**Comment by ihmpavel** [comment]
Hi, did you use plugin [Content Versioning](https://market.strapi.io/plugins/@notum-cz-strapi-plugin-content-versioning)?

There are known limitations with UID https://github.com/notum-cz/strapi-plugin-content-versioning#know-limitation
 - Not working with UID and unique fields
 - Not have i18n support
 - Not working with relations

**Comment by NidMo** [comment]
> This is an issue with a 3rd party plugin, not Strapi itself. Closing.
> 
> Please contact the versioning plugin author.

thank you
