### ISSUE TITLE
GraphQL issues with camelCase API

### ISSUE THREAD

**Issue by 1ncidental** [strapi/strapi#1349]
**What is the expected behavior?**
When you install the Graphql plug in, if you have any content types with Spaces in their titles, grahql will cause Strapi to crash on restart. From here you must uninstall the graphql plugin before Strapi will start again.
Perhaps if Graphql cannot handle spaces in the field names, we could stop the plugin from being installed?

**Comment by derrickmehaffy** [comment]
@1ncidental strapi itself should not handle spaces at all (most APIs won't), generally APIs will use camelcase instead of spaces due to this reason.

Also in the future can you please use the bug report template and fill in all the required information to report a bug.

**Comment by lauriejim** [comment]
Hello @1ncidental , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
