### ISSUE TITLE
Integer Columns not taking 0 as a value through strapi studio

### ISSUE THREAD

**Issue by nikhilshekhawat** [strapi/strapi#135]
I inspected the strapi studio console when I hit update on an integer field with value 0 it passes "" instead of 0. This is what makes the update fail. It works fine if I run it through postman.

**Comment by pierreburgy** [comment]
Good catch @nikhilshekhawat, we will fix it asap. Thank you for the report.

**Comment by nikhilshekhawat** [comment]
sure @pierreburgy Another thing that does not work is the MIN check. Because of the same reason I suppose. If I set the min as 0, I can set -100 as a value

**Comment by laclance** [comment]
Having the same issue, any news on when this will be fixed?

**Comment by nicolasform** [comment]
Same here. I want to fix it myself but I'm a bit list in the admin console sources. Any tip about where to look?

**Comment by nicolasform** [comment]
Ok I got it. It is about a test to ensure a field value is set, but the test considers 0 as an empty/null value.

Quick fix: in "api/admin/public/dist/frontend.min.js" you can go around the character 26328 (first line) and change
`e[r]=t||""`
for
`e[r]=(t===null?"":t)`
Like that, your admin panel will accept 0 values. As a side effect, this change will also not abort your update if a field is incorrect ; the incorrect field value will simply be ignored and the old value kept. Maybe there is other side effects but I didn't see them until now. I'm sure there is a more intelligent way to fix that but I don't feel comfortable enough with the code to find it.

Good to know for the strapi team: the bug can also be be found at line 2346 in api/admin/public/dist/frontend.js

Hope it helps!

**Comment by Aurelsicoko** [comment]
@nicolasform As you know, we are working on the next version, and we decided to spent to a "maintenance only" mode for the current v1.5.5 to only patch critical issues. Thanks for great work! It will definitely help us for fix this issue on the `Content Type Builder` plugin.

However, I was just thinking about that, you can make a PR on this [repository](https://github.com/strapi/strapi-generate-admin), I will be easy for us to push a new release for you guys. What do you think about that?

**Comment by nicolasform** [comment]
@Aurelsicoko You're welcome. I don't see any "frontend.js" or "frontend.min.js" in the strapi-generate-admin repository. I guess they are generated, but where ?

**Comment by samuel-ye** [comment]
the real culprit is located at frontend's src/strapi/explorer/explorer-edit.controller.js line 175 if need rebuilding admin panel, it should be:
formattedModel[key] = (value===null?'':value);
