### ISSUE TITLE
Slash at the end of the JS files on AWS Amplify

### ISSUE THREAD

**Issue by crocco95** [strapi/strapi#13506]
### Required System information

- Node.js version: 16
- Strapi version: 4.1.11
- Database: PostgreSQL

### Describe the bug

When I deploy the Strapi application on AWS Amplify, the build and the deploy go successfully but when I open it in the browser and try to navigate, the pages are blank. Reading the network or the console tab I notice a redirect: every single file is redirected adding a trailing slash like in the screenshot below in the "Screenshot" section.

Request:
Request URL: https://main.dvvegi0wyzkp0.amplifyapp.com/admin/main.e0e7b7d0.js
Status Code: 301

Response:
location: /admin/main.e0e7b7d0.js/

On my local machine the issue is not present and the application works well.

### Steps to reproduce the behavior
You can see the issue live by navigating this URL: https://main.dvvegi0wyzkp0.amplifyapp.com

### Expected behavior

Just see the content displayed correctly.

### Screenshots

<img width="720" alt="Schermata 2022-06-08 alle 16 12 55" src="https://user-images.githubusercontent.com/6146017/172639088-13245e51-6556-4f2c-a683-3eb132ac28a0.png">

**Comment by derrickmehaffy** [comment]
Not enough reproduction information, appears environmental but no information on the environment/variables used.

Please provide detailed reproductive steps and we can reopen.

**Comment by crocco95** [comment]
You are completely right and I am sorry for the missing informations. 


Env variables (.env file)
```env
JWT_SECRET=hidden
API_TOKEN_SALT=hidden

AWS_ACCESS_KEY_ID=hidden
AWS_ACCESS_SECRET=hidden
AWS_REGION=hidden
AWS_BUCKET=hidden

DATABASE_HOST=hidden
DATABASE_PORT=hidden
DATABASE_NAME=hidden
DATABASE_USERNAME=hidden
DATABASE_PASSWORD=hidden
DATABASE_SSL=hidden

NODE_ENV=production

PORT=80
```

config/server.js
```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', env('PORT'),
  app: {
    keys: env.array('APP_KEYS',[ 'hidden' , 'hidden' ]),
  },
});
```
config/plugins.js
```js
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        params: {
          Bucket: env('AWS_BUCKET'),
        },
      },
    },
  },
});
```

config/middlewares.js
```js
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'hidden'],
          'media-src': ["'self'", 'data:', 'blob:', 'hidden'],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
];
```

config/database.js
```js
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST'),
      port: env.int('DATABASE_PORT'),
      database: env('DATABASE_NAME'),
      user: env('DATABASE_USERNAME'),
      password: env('DATABASE_PASSWORD'),
      ssl: env.bool('DATABASE_SSL'),
    },
  },
});
```

config/api.js
```js
module.exports = {
  rest: {
    defaultLimit: 25,
    maxLimit: 100,
    withCount: true,
  },
};
```

config/admin.js
```js
module.exports = ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET',  env('JWT_SECRET')),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT', env('API_TOKEN_SALT'))
  }
});
```

package-json:
```json
{
  "name": "test-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.5",
    "@strapi/plugin-users-permissions": "4.1.5",
    "@strapi/provider-upload-aws-s3": "^4.1.5",
    "@strapi/strapi": "^4.1.8",
    "pg": "8.6.0",
    "strapi-plugin-sitemap": "^2.0.6"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "fc166fb2-cbb8-4244-8d69-470bd74f817e"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT",
  "devDependencies": {
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0"
  }
}
```

Tell me if I am forgetting something and I will provide you as soon as possible

**Comment by crocco95** [comment]
@derrickmehaffy can you please reopen the issue or there is something else I have to add to my request? I can provide other details if specified

**Comment by derrickmehaffy** [comment]
The only thing I can see missing is you didn't set the URL key in your server.js

But I don't think this is an actual bug, it's most likely a configuration issue so it would be better for you to ask these questions on our community platforms. See the links to those in the templates message below.

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
