### ISSUE TITLE
Webhook payload doesn't include image in relation fields

### ISSUE THREAD

**Issue by kovansky** [strapi/strapi#13509]
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.1.4
- Yarn version (I use yarn): 3.2.0
- Strapi version: v4.1.12
- Database: SQLite
- Operating system: Ubuntu 20.04.3 LTS

### Describe the bug

I have a **Single Type** (named Crew) with an one-to-many relation field with **Collection Type** (named Person) that contains a `name` (string field) and `image` (media, single image field).
The problem is that the image field is not included in webhook payload and I cannot find a way to enable it.

### Steps to reproduce the behavior

1. Create a collection type "person" with `name` (string) field and `image` (media, single, type: image) field;
2. Create a single type "crew" with one-to-many relation field "crew_people" linking to the "person" type;
3. Create a webhook with all events checked (for example targeting the [webhook.site](https://webhook.site))
4. Trigger an update of the "crew" type
5. Check the webhook payload

### Expected behavior

I expect the webhook to contain images in the same way it is contained in the GET requests.

#### Result of GET request ("expected" behavior)

```json
{
  "data": {
    "id": 1,
    "attributes": {
      "createdAt": "2022-05-05T22:32:03.168Z",
      "updatedAt": "2022-06-08T10:12:30.978Z",
      "crew_people": {
        "data": [
          {
            "id": 1,
            "attributes": {
              "name": "Gerle",
              "createdAt": "2022-05-25T12:23:55.751Z",
              "updatedAt": "2022-05-25T12:23:56.710Z",
              "publishedAt": "2022-05-25T12:23:56.706Z",
              "image": {
                "data": {
                  "id": 27,
                  "attributes": {
                    "name": "gerle.jpg",
                    "url": "/uploads/gerle_fa4b3408a3.jpg",
                    "createdAt": "2022-05-25T12:22:54.120Z",
                    "updatedAt": "2022-05-25T12:22:54.120Z"
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}
```
*I cut the image attributes for brevity*

#### Payload of the webhook (actual behavior)

```json
{
  "event": "entry.update",
  "createdAt": "2022-06-08T20:55:21.766Z",
  "model": "crew",
  "entry": {
    "id": 1,
    "createdAt": "2022-05-05T22:32:03.168Z",
    "updatedAt": "2022-06-08T20:55:13.274Z",
    "crew_people": [
      {
        "id": 1,
        "name": "Gerle",
        "createdAt": "2022-05-25T12:23:55.751Z",
        "updatedAt": "2022-05-25T12:23:56.710Z",
        "publishedAt": "2022-05-25T12:23:56.706Z"
      }
    ]
  }
}
```

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/webhook-payload-doesnt-include-image-in-relation-fields

Thanks!
