### ISSUE TITLE
Can't create admin user "An error occurred while requesting the API" on live domain only, it run on local

### ISSUE THREAD

**Issue by bhargav2204** [strapi/strapi#13517]
I start up a development server I get “Warning: An error occurred while requesting the API” in live domain not in local and am left with an infinite loading screen. This issue is occur when I lived this project on my domain. it Run on local. Does anyone know how to fix this in live ?

**Comment by codeblooded47** [comment]
Can you give more details.
what's your config/server.js for live and local.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
