### ISSUE TITLE
attribute must be unique in repeatable component bug

### ISSUE THREAD

**Issue by 2-man** [strapi/strapi#13515]
check post on forum
https://forum.strapi.io/t/post-query-to-add-new-item-in-repeatable-component

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
