### ISSUE TITLE
Error while installing @strapi/plugin-graphql in Strapi 4.2.0-beta.4

### ISSUE THREAD

**Issue by JeffinJ** [strapi/strapi#13512]
## Bug report

ERESOLVE unable to resolve dependency tree error while installing **@strapi/plugin-graphql** in **Strapi 4.2.0-beta.4**

- Strapi version: Strapi 4.2.0-beta.4

npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.0.0" from @strapi/plugin-graphql@4.2.0-beta.4
npm ERR! node_modules/@strapi/plugin-graphql
npm ERR!   @strapi/plugin-graphql@"4.2.0-beta.4" from the root project

Does graphql-plugin supports strapi beta version with typescript? thanks

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
