### ISSUE TITLE
Images are not showing in the media library when connected with the digital ocean spaces

### ISSUE THREAD

**Issue by sarangkkl** [strapi/strapi#13516]
I am using digital ocean spaces for the media files uploading i am using this https://github.com/shorwood/strapi-provider-upload-do uploader to upload files in my digital ocean spaces and it works fine the files uploaded there are public by default 

![image](https://user-images.githubusercontent.com/72507795/172990587-a9296c14-b4a2-4b45-8a6c-d9f82cf86d42.png)
 but when i try to view image in the media library 
![image](https://user-images.githubusercontent.com/72507795/172990662-bf522e02-ed52-46e3-96d1-c29098673dc1.png)

the images does not show also i try to copy the image link by inspect and the provided link was working

**Comment by alegemaate** [comment]
Hey @sarangkkl I faced a similar problem with S3 and was able to resolve using something like this in my middlewares file:

```
module.exports = ({ env }) => [
  ...,
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'script-src': ["'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'],
          'img-src': [
            "'self'",
            'data:',
            'cdn.jsdelivr.net',
            'strapi.io',
            'dl.airtable.com',
            '<bucket>.s3.<region>.amazonaws.com',
          ],
        },
      },
    },
  },
  ...
];
```

In your case, just replace the s3 bucket url, with the one from your digital ocean space.

**Comment by sarangkkl** [comment]
where is s3 bucket url

**Comment by alegemaate** [comment]
This one 
```
<bucket>.s3.<region>.amazonaws.com
```

And then replace it with the one being blocked by your browser (digital ocean url). But only add the domain, not the full urls, or protocol.

You will have to add the above to your middlewares file.

**Comment by officialrj18** [comment]
any update about it? i am facing similar issue

**Comment by sarangkkl** [comment]
yes i have fixed the issue

**Comment by sarangkkl** [comment]
i recommend not using strapi it have serious issue of database vanishing

**Comment by derrickmehaffy** [comment]
Please contact the author of the package as we cannot assist with 3rd party packages here.
