### ISSUE TITLE
Images from public folder are returned with 206 when trying to generate Open Graph card on WhatsApp iOS.

### ISSUE THREAD

**Issue by Pablo-Aldana** [strapi/strapi#13521]
## Bug report

Images from public folder are returned with 206 when trying to generate Open Graph card on WhatsApp iOS. Not affecting other apps.

### Required System information

- Node.js version: 14.15.1
- NPM version: 7.5.3
- Strapi version: 4.1.12
- Database: Postgres 
- Strapi server Operating system: MacOSx and Ubuntu
-  Device issue: iPhone XR, iPhone 12 (probably all whatsapp iOS )

### Describe the bug

On WhatsApp iOS when generating the OpenGraph card public folder returns 206 instead 200. I have created a dummy project with vanilla KOA and it works well, which makes me thinks there is something in between that modify the headers of the calls and requires partial content 206. 

you can test it on https://vive.scintillam.com/download/strapitest.html

The specific line that returns the error is this one:
<meta property="og:image" content="https://mysubdomain.mydomain.com/uploads/New_Project_8_4e84cb230c.jpg"/>

at NGINX level I'm getting
`XXX - - [09/Jun/2022:12:58:03 +0000] "GET /uploads/New_Project_8_4e84cb230c.jpg HTTP/2.0" 206 89955 "-" "WhatsApp/2.22.10.76 I"`

at strapi level:
`[2022-06-09 14:57:58.538] http: GET /uploads/New_Project_8_4e84cb230c.jpg (18 ms) 206`

The only difference I can find when I query from WhatsApp Web the browser it is different and so is the response

```XXX - - [09/Jun/2022:13:01:18 +0000] "GET /download/test.html HTTP/1.1" 200 1008 "-" "WhatsApp/2.2216.8 N"
XXX - - [09/Jun/2022:13:01:19 +0000] "GET /uploads/New_Project_8_4e84cb230c.jpg HTTP/1.1" 200 89955 "-" "-"```

On NGINX error.log there is the following:
```022/06/09 16:31:13 [error] 33922#33922: *247 upstream prematurely closed connection while reading upstream, client: XXX.10.70.XXX server: mysubdomain.mydomain.com, request: "GET /uploads/New_Project_8_4e84cb230c.jpg HTTP/2.0", upstream: "http://127.0.0.1:1340/uploads/New_Project_8_4e84cb230c.jpg", host: "mysubdomain.mydomain.com"
```

I was thinking it was my NGINX configuration, however It is reproducible on your local machine:
Create and endpoint that returns a static HTML (you can use mine) with a meta tag or link tag that points to an image on the public folder (uploaded with Strapi of course). Run your code and grab your local IP i.e 192.168.68.114 go to your iPhone while you are connected to the same network and paste the link to your endpoint on WhatsApp: http://192.168.68.114:1337/api/event/2

it will try to retrieve the OG card with all the information except the image won't load and the server will return a 206.

I couldn't found  any significant differences between the headers between laptop and iPhone when calling the endpoint apart from the user agents:

iPhone header 
```
{
  request: {
    method: 'GET',
    url: '/api/event?uid=175',
    header: {
      'x-forwarded-host': 'mysubdomain.mydomain.com',
      'x-forwarded-server': 'mysubdomain.mydomain.com',
      'x-real-ip': 'XXX.10.XX.197',
      'x-forwarded-for': 'XXX.10.XX.197',
      'x-forwarded-proto': 'https',
      host: 'mysubdomain.mydomain.com',
      connection: 'Upgrade',
      accept: '*/*',
      range: 'bytes=0-99999',
      'user-agent': 'WhatsApp/2.22.10.76 i',
      'accept-language': 'en-GB,en;q=0.9',
      'accept-encoding': 'gzip, deflate, br'
    }
  },
  response: {
    status: 404,
    message: 'Not Found',
    header: [Object: null prototype] {
      'content-security-policy': "connect-src 'self' https:;img-src 'self' data: blob: https://dl.airtable.com;media-src 'self' data: blob:;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
      'x-dns-prefetch-control': 'off',
      'expect-ct': 'max-age=0',
      'x-frame-options': 'SAMEORIGIN',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'x-permitted-cross-domain-policies': 'none',
      'referrer-policy': 'no-referrer',
      vary: 'Origin'
    }
  },
  app: { subdomainOffset: 2, proxy: false, env: 'production' },
  originalUrl: '/api/event?uid=175',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>'
}
```

Laptop header

```
{
  request: {
    method: 'GET',
    url: '/api/event?uid=175',
    header: {
      'x-forwarded-host': 'mysubdomain.mydomain.com',
      'x-forwarded-server': 'mysubdomain.mydomain.com',
      'x-real-ip': 'XXX.10.XX.197',
      'x-forwarded-for': 'XXX.10.XX.197',
      'x-forwarded-proto': 'https',
      host: 'mysubdomain.mydomain.com',
      connection: 'Upgrade',
      range: 'bytes=0-1024000',
      'accept-encoding': 'br, gzip, deflate, none',
      'accept-language': 'en',
      'user-agent': 'WhatsApp/2.2216.8 N'
    }
  },
  response: {
    status: 404,
    message: 'Not Found',
    header: [Object: null prototype] {
      'content-security-policy': "connect-src 'self' https:;img-src 'self' data: blob: https://dl.airtable.com;media-src 'self' data: blob:;default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
      'x-dns-prefetch-control': 'off',
      'expect-ct': 'max-age=0',
      'x-frame-options': 'SAMEORIGIN',
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'x-permitted-cross-domain-policies': 'none',
      'referrer-policy': 'no-referrer',
      vary: 'Origin'
    }
  },
  app: { subdomainOffset: 2, proxy: false, env: 'production' },
  originalUrl: '/api/event?uid=175',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>'
}
```
In case you have doubts you can download the image, but it is a really tiny image of a couple of KB, and not a massive file, and happens exactly the same with all the images queried that way, as mentioned it works like charm on other browsers.

As a curiosity, I have tried with an image stored in a Strapi v3 and it also does not work.

### Steps to reproduce the behavior

1 -  Create a static html on your Strapi with a meta tag og:image or a link href that point to an image on the public folder.
2 - Copy the link and paste it in your WhatsApp (iOS).
3 -  Image is not retrieved and an 206 is returned on strapi console. (if your a using nginx you'll see an upstream closed error.)

You can test it yourself with this test I have created and you'll see how image is generated in any platform i.e WhatsApp android, WhatsApp MacOS or when publishing on Facebook, however it does not on WhatsApp iPhone. https://vive.scintillam.com/download/strapitest.html 
 
### Expected behavior

A 200 should be returned for images and elements on the public folder so that the open graph will work correctly.

Thinking It was a KOA problem I have created a dummy project using Koa-static as Strapi is using to return files from the public folders and it works without problem, to use it follow same steps explained above for your local enviroment

https://github.com/Pablo-Aldana/testKOA

### Screenshots

![image](https://user-images.githubusercontent.com/9969839/173048073-2dbbedd9-31a2-4d39-bd47-f9b5dd4a915e.jpeg)

![image](https://user-images.githubusercontent.com/9969839/173048113-09d1a73d-04b0-4ede-9eae-e06fe0320230.jpeg)

### Code snippets

static html created here that can be reused on local environments to test it.  https://vive.scintillam.com/download/strapitest.html

### Additional context

I'm trying to generate OG cards for my application where it returns the card (article) image, title, description, etc..  It works great on every platform and browser, iOS apps( iMessage, telegram, Facebook, etc.. ) Android (all apps), desktop, Mac, including WhatsApp app on MacOS, but does not work for  WhatsApp iOS, where the images from public folder are returned with 206 instead the normal 200.

### Related issue:
https://github.com/strapi/strapi/issues/12461

**Comment by wenerme** [comment]
The video can not play on safari, is this the same problem ?

safari will issue a byte-range request first

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1777211/176849141-a17a9b76-3e8e-4079-8df6-74ed368e2b32.png">

**Comment by wenerme** [comment]
This one is fixed, but the problem still exists in 4.1.11 https://github.com/strapi/strapi/issues/2246

**Comment by derrickmehaffy** [comment]
> This one is fixed, but the problem still exists in 4.1.11 #2246
> 
> Problem SOLVED by disable https://github.com/alexkainzinger/strapi-middleware-upload-plugin-cache

Can you be more specific, the issue with images not working in whatsapp is related to the package you mentioned?

**Comment by wenerme** [comment]
My problem is related to safari, don't test with whatsapp, not sure it's the same problem.

**Comment by Pablo-Aldana** [comment]
Hi,

I was wondering if there is any news regarding this issue as I have been upgrading all the version until 4.3.2 and the issue still persists. I know it is a rear one, but still a pain for users when trying to share a link via WhatsApp iOS (more than 60% of my users)  I'm more than keen to participate in real time testing if needed

**Comment by derrickmehaffy** [comment]
We have not evaluating the issue currently due to time and priority on other feature development and bug fixes. If those that do have the time to look at it know the issue and would like to submit a PR please feel free.

At the moment the content squad has not reviewed the issue and there is quite the backlog for us: https://github.com/orgs/strapi/projects/11

**Comment by kasonde** [comment]
I'm closing this issue because this isn't a Strapi issue but a Facebook OpenGraph issue and the fact that it sometimes will ask for not only a range of data (image sizes) or only get partial content as the status states. This is from my research, you can read more here: https://stackoverflow.com/a/9807896, of course if I've missed something you can let us know.

**Comment by Pablo-Aldana** [comment]
Hi @kasonde @derrickmehaffy  I'd like to reopen this issue, as after further investigation It does not an Facebook issue itself but how the upload plugin / strapi handles the range header

After further investigations by just curl-ing or doing a postman to an image in the image gallery i.e
http://localhost:1338/uploads/FENLES_CONECTA_ICON_2_34d1483207.png
with a header 

`Range bytes=0-99999`

It will  try to get the image and after around 5s return a 206 and the image won't show up hanging the response.
![image](https://github.com/strapi/strapi/assets/9969839/a0ff278b-b6fb-486a-a330-6ad05c1b3bec)


However if you do the same call to a different endpoint it will work, (i.e: /api/food)

More over if you use the KOA example I shared with you while ago, https://github.com/Pablo-Aldana/testKOA  and performs the same test with the image in my case "http://192.168.68.114:3000/uploads/Screenshot_2022_06_01_20_51_28_mz_T_Lrq_049c151b2d.png"

![image](https://github.com/strapi/strapi/assets/9969839/fd76d17a-81fd-4b34-ae0e-d524ea33c2cf)


it will return successfully the image. 

So the problem lies in how Strapi handles the range header with the plugin and not with Facebook itself
It is true indeed WhatsApp iOS send a range header, while open graph, WhatsApp Android or any other it does not and that's why it works in others but not with iOS but from my understanding the plugin should be able to work with Range

**Comment by derrickmehaffy** [comment]
Given how old this issue is, could you open a new one so we can start from a clean slate?

There is a lot of misc info to dig through in this one.
