### ISSUE TITLE
Saving login credentials causes validation error when changing roles/user info

### ISSUE THREAD

**Issue by jameshhood** [strapi/strapi#13524]
### Required System information

- Node.js version: 14.17.5
- NPM version: 8.5.1
- Strapi version: 4.1.1
- Database:
- Operating system:

### Describe the bug

As a super admin, I cannot simply change other users roles. It forces me to enter in a password and confirm it (changing their password) I should be able to add/remove roles without having to change the users password

### Steps to reproduce the behavior

Preq: Be a super admin and have 1 other user

1. Login as Super Admin
2. Save login credentials to browser.
3. Go to 'settings'
4. Click on 'Users' under Administration Panel
5. Select other user
6. Change User roles
7. Click Save

### Expected behavior

User roles should be simply updated. I should not have to provide a username or password for this user. 

### Additional context

Two problems exist here
1. Username and Password auto populate with my own login info
2. Removing info from 1. causes a 400 in the console

**Comment by jameshhood** [comment]
![image](https://user-images.githubusercontent.com/30268306/173673660-54e01a07-5a72-47de-9030-b48bbf8cd924.png)

Maybe it has something to do with my Username and Password being saved/cached by the browser so it auto populates in these fields but even when I clear them out and try to add a role and hit save I get this error.

![image](https://user-images.githubusercontent.com/30268306/173674004-33085cb2-2a69-4b3e-9385-40c9a52db64d.png)

**Comment by jameshhood** [comment]
Confirmed that when opened in an incognito tab and did not have those values auto populated, it works just fine.

**Comment by jameshhood** [comment]
I have updated my reproduction steps and the title to the bug to better represent the issue at hand.

**Comment by bolg55** [comment]
Thanks - Are you using Chrome? If so, are you saving your creds in the standard chrome password store, or using something like 1Password?

**Comment by jameshhood** [comment]
Yes I am just using Chrome and using it's native password saving. No other plugins.

``` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36```

**Comment by ihmpavel** [comment]
I can confirm, while updating user, after loading the page autofilled password is entered and I am unable to save edited user. Does not matter which user it is. Every time Chrome autofills my username (as email) and a password. (No plugins, native Chrome autofill manager.)

Only in Incognito mode is possible to edit user without editing some other values.

Chrome: _Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36_

On the screen I loaded only this user, but password has been filled automatically.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/42217494/173685173-459f2b97-9e69-44cb-a9aa-925ef7fcc096.png">

Possible fix: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
