### ISSUE TITLE
Thousands of webhooks requests sent on update.

### ISSUE THREAD

**Issue by sqlninja** [strapi/strapi#13525]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.11.0
- Strapi version: 4.1.12
- Database: Sqlite (Local) / Postgres (Production)
- Operating system: Mac (Local) / Ubuntu 20.04 (Production)

### Describe the bug

When subscribed to `update` webhooks, I receive thousands of requests to my API. Not happening with `publish`

### Steps to reproduce the behavior

Don't how to "reproduce" this issue, it's just happening

### Expected behavior

Expecting to only receive one request per "action"

### Screenshots
Note the milliseconds between each record...
![image](https://user-images.githubusercontent.com/2085814/173159706-da21dfd1-2c10-49e3-a263-da973b45838d.png)

### Potential duplicate issues:

- [#9590](https://github.com/strapi/strapi/issues/9590)
- [#9193](https://github.com/strapi/strapi/issues/9193)

**Comment by anildalar** [comment]
its a bug
