### ISSUE TITLE
Strapi development environment does not watch files because of strapi-helper-plugin error

### ISSUE THREAD

**Issue by renettarenula** [strapi/strapi#1353]
**Informations**
- **Node.js version**: v10.4.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: Mongo 3.6.4
- **Operating system**: Mac OS 10.13.4

**What is the current behavior?**
I am expecting for the development environment to watch the changes every time I saved a file. Unfortunately, it doesn't update because of a bunch of warnings that is available on client.js

```
/Users/compname/workspace/my-app/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src/app.js
Module not found: Error: Can't resolve '../../../../config/layout.js' in '/Users/compname/workspace/my-app/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src'
 @ /Users/compname/workspace/my-app/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src/app.js 52:11-50
/Users/compname/workspace/my-app/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src/app.js
Module not found: Error: Can't resolve '../../../../config/layout.js' in '/Users/compname/workspace/my-app/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src'
 @ /Users/compname/workspace/my-app/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src/app.js 52:11-50
/Users/compname/workspace/my-app/plugins/settings-manager/node_modules/strapi-helper-plugin/lib/src/app.js

```

This warning appears for my own generated plugins and the default plugins included by Strapi.

I did follow this instruction step-by-step when I am setting up my development environment: https://github.com/strapi/strapi/issues/1289#issuecomment-392845254

**Steps to reproduce the problem**
`cd admin && npm start`

Go to `localhost:4000/admin` and look @ the dev console. As a result, some plugins like settings manager does not appear under the plugins menu and plugins generated by `strapi generate:plugin my-plugin` does not update when changes are made.

**What is the expected behavior?**
Related modules of strapi-helper-plugin is required correctly.

**Comment by derrickmehaffy** [comment]
May want to modify your versions to state mongo and macos just to clarify.

**Comment by renettarenula** [comment]
After tinkering around for a bit, I notice that I just need to add `layout.js` under the config folder of my plugin. I also have some _'injectedComponents' module not found error_ but that no longer stops the changes from being watched. The generated plugin should be improved by including layout.js under config folder by default to help people save time. Closing this.

**Comment by krsnaa** [comment]
@renettarenula - how did you handle the `Can't resolve '../../../../config/layout.js' in '/Users/compname/workspace/my-app/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src'` error - i.e. in plugins other than your own?

**Comment by soupette** [comment]
Well the dev environment does watch files but the issue is that when you have the server autoreload activated, the strapi server restarts each time you make a modification in one of your front-end file.

I made a commit to fix this problem but the PR is not ready yet.

**Comment by yummyelin** [comment]
@soupette Sorry to bother you. Have you submitted the PR? I met the same issue.
