### ISSUE TITLE
Using the '/email' route from the frontend returns 401 unauthorized  

### ISSUE THREAD

**Issue by akarkaselis** [strapi/strapi#13556]
I am using axios to send an email from my frontend and it doesn't work unless I add "Authorization: 'bearer + token' (I use the one that i found while sending myself a test email in strapi admin panel). 

What i don't understand is that I made sure to set Send Email to allow Public Role. 

here is what I do (that works) in the frontend (Nuxtjs btw): 

> await this.$axios.$post( '/email',
          {
            to: 'email@mail.com'
            from: 'otheremail@mail.com'
            subject: 'Email Subject',
            html: '<strong>Hello world!</strong>',
            attachments:  [data],
          },
          {
            headers: {
              Authorization: 'Bearer +token I got from strapi',
              'Content-Type': 'application/json',
            },
          }
        )

Any day now that token will expire. Is there a way to set one up and have the frontend use it or is there an actual way of using '/email' without autorisation?

I've tried to change the permissions in the admin panel, but I'm starting to think this is a bug.

Thank you

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by akarkaselis** [comment]
The issue has been updated

**Comment by derrickmehaffy** [comment]
> The issue has been updated

Please specify exactly which v4 version
