### ISSUE TITLE
Request to support getting media similarly to the referenced fix

### ISSUE THREAD

**Issue by christhoperbernard** [strapi/strapi#13559]
https://github.com/strapi/strapi/blob/07bc405c06a1357f1dc15a19c969cd8f37a30ec7/packages/core/admin/server/controllers/authenticated-user.js#L7

I think it will be great and more convenient if we could just grab the whole user object here (obviously without the private fields). Any reason why it's not similarly supported as the referenced link?

Reference:
https://github.com/strapi/strapi/pull/11960

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
