### ISSUE TITLE
Image in the model isn't replaced after loading a new image

### ISSUE THREAD

**Issue by tim4ous** [strapi/strapi#13576]
### Required System information

- Node.js version: v15.14.0
- NPM version: v7.7.6
- Strapi version: v4.2.0
- Database: SQLite
- Operating system: macOS 12.3.1

### Describe the bug

I have added one image field (avatar) to the standard user model. I also created a new endpoint to upload the user's avatar. This endpoint works fine if the user doesn’t have an avatar. However, if the user already has an avatar, the new avatar uploaded via my new endpoint doesn't replace the user's old avatar (while the new avatar appears in the media library, that is, the new avatar is not attached to the user).

### Code snippets

I'm using the following code to upload avatars in the my endpoint:
```js
const attachment = await strapi.plugins.upload.services.upload.upload({
    data: {
        refId: user.id,
        ref: 'plugin::users-permissions.user',
        field: 'avatar'
    },
    files: avatar,
});

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by tim4ous** [comment]
@derrickmehaffy hello, thank you for your answer. Do I understand correctly that the case I described is the normal behavior of the upload plugin?

**Comment by derrickmehaffy** [comment]
It largely depends on the complete logic used. I would need to do a bit of testing but since this is custom code and not the intended use of this function is why I had to close this.

Sorry.
