### ISSUE TITLE
Clean install of Strapi on GCP return Admin page with no content and "TypeError: can't access property "toggleNotification", Z.useContext(...) is undefined"

### ISSUE THREAD

**Issue by ibytergj** [strapi/strapi#13585]
### Required System information

- Node.js version: node v16.15.0
- NPM version: npm@8.1.2
- Strapi version: 4.2.0
- Database: postgres 14
- Operating system: GCP

### Describe the bug
Clean install of Strapi on GCP return Admin page with no content

### Steps to reproduce the behavior

```
1.     On a local machine, install Strapi via the instruction listed here: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html.
2.     Per those instructions follow through with gcloud app deploy .
3.     After it completes deployment, visit the website via `gcloud app browse'.
4.     Open the administration panel and login (once you've signed up, a normal login page will show).
5.     See that the /admin link is a blank page and dev tool reports back two similar errors, starting with 
```

TypeError: can't access property "toggleNotification", Z.useContext(...) is undefined main.9abb0ca1.js:8381:69
Uncaught TypeError: can't access property "toggleNotification", Z.useContext(...) is undefined main.9abb0ca1.js:7981:5421

### Expected behavior

The admin page should be full of content.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Similar to https://github.com/strapi/strapi/issues/12869 but not the same exact error msg.

I can provide password for access

**Comment by gu-stav** [comment]
Hello and thank you for opening this issue. I'm currently starting to investigate, what is happening, but is not yet fully clear to me. What I can say: you are right: it doesn't have anything to do with your plugin or a missing method, but with the way we bundle the whole application.

Could you do me a favor and try to replace the following file:

`node_modules/@strapi/admin/webpack.alias.js`

with

```js
'use strict';

const path = require('path');

const alias = [
  'whatwg-fetch',
  '@fortawesome/fontawesome-svg-core',
  '@fortawesome/free-solid-svg-icons',
  '@strapi/design-system',
  '@strapi/icons',
  'date-fns',
  'formik',
  'history',
  'immer',
  'lodash',
  'moment',
  'qs',
  'react',
  'react-copy-to-clipboard',
  'react-dnd',
  'react-dnd-html5-backend',
  'react-dom',
  'react-error-boundary',
  'react-fast-compare',
  'react-helmet',
  'react-is',
  'react-intl',
  'react-redux',
  'react-router',
  'react-router-dom',
  'react-virtualized',
  'react-select',
  'redux',
  'reselect',
  'styled-components',
  'yup',
];

module.exports = alias.reduce(
  (acc, curr) => {
    acc[`${curr}$`] = require.resolve(curr);

    return acc;
  },
  {
    'react-select/animated': require.resolve('react-select/animated'),
    'react-select/async': require.resolve('react-select/async'),
    'react-select/async-creatable': require.resolve('react-select/async-creatable'),
    'react-select/base': require.resolve('react-select/base'),
    'react-select/creatable': require.resolve('react-select/creatable'),
    '@strapi/helper-plugin': require.resolve('@strapi/helper-plugin'),
    ee_else_ce: path.resolve(__dirname),
  }
);
```

and try to re-run `yarn build` to see if that fixes the issue for you?

**Comment by ibytergj** [comment]
Hi I am a new user to strapi and following this doc - https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html and this video https://www.youtube.com/watch?v=4Z79lmOpHGo

i am not sure in this process where I would run the command you asked me to?

**Comment by ibytergj** [comment]
I updated the file as you asked and tried a yarn build from my local console. Did another 'gcloud app deploy'. Did not seem to help.
I decided to remove both the yarn.lock file and the package-lock.json file and redid the 'gcloud app deploy".
I now am able to enter the admin panel successfully.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/13222
