### ISSUE TITLE
@strapi/provider-upload-cloudinary Error when replacing image more than once

### ISSUE THREAD

**Issue by rawestmoreland** [strapi/strapi#13586]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.12.2
- Strapi version: 4.2.0
- Database: postgres:14
- Operating system: Linux (Heroku deploy)

### Describe the bug

When _replacing_ an image **more than once** Cloudinary / Strapi throws a 500 error.

### Steps to reproduce the behavior

1. Upload an asset in the media library
2. Replace that asset once 👍 
3. Try and replace that asset again 👎 
4. See error:

```
2022-06-17T04:54:06.557458+00:00 app[web.1]: [2022-06-17 04:54:06.556] error: Error deleting on cloudinary: Cannot destructure property 'resource_type' of 'file.provider_metadata' as it is undefined.
```

### Expected behavior

Should be able to replace the image as many times as you want.

### Screenshots

![Recording 2022-06-16 at 23 55 29](https://user-images.githubusercontent.com/30242837/174227843-88aba69d-2622-4403-b62e-6ef3301b261c.gif)

### Code snippets

None

### Additional context

None

**Comment by Thomas-T** [comment]
Same here, problem is located to the "formats" column stored in the database.
when an image is replaced, the way it's data are stored changes, and if you attempt a second change, an error will thrown.
(using strapi 4 and GCS provider).

this is the formats objet stored in the database after an update : 
{
	"thumbnail": {
		"ext": ".jpg",
		"hash": "thumbnail_wallpaperflare_com_wallpaper_321f1770df",
		"mime": "image/jpeg",
		"name": "thumbnail_wallpaperflare.com_wallpaper.jpg",
		"path": null,
		"size": 5.4,
		"width": 117,
		"buffer": {
			"data": [255, 216, ...... 255, 217],
			"type": "Buffer"
		},
		"height": 156
	}
}

the buffer is stored (why ?) and the complete URL is missing. but GCS provider (and i think other providers too) require the URL field to be present and crashes.

**Comment by detronexyt** [comment]
Hey, replace work fine only when you update pdf files.

**Comment by Marc-Roig** [comment]
Hello! 
I have been trying to reproduce this is issue without success.  So my guess is.. it is already fixed (not probable), or your strapi app has different configurations than mine.

I have tried with images, pdfs, videos and I get the sam result. Replacing them, multiple times, in cloudinary does not give me any error.

Could you try to update to 4.3.4 just to check?

**Comment by derrickmehaffy** [comment]
Marking as closed for now until new reproduction steps are added
