### ISSUE TITLE
Impossible to upload MULTIPLE FILES to media library in development mode + sqlite

### ISSUE THREAD

**Issue by yomomano** [strapi/strapi#13587]
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: 4.1.8
- Database: sqlite
- Operating system: ubuntu 20

### Describe the bug

In development mode, STRAPI restarts after SQLITE database file is updated. 
This makes it impossible to upload MULTIPLE FILES to media library as after the first upload, STRAPI restarts. 
SINGLE FILE UPLOAD is ok.

This problem only occurs in development mode.

### Steps to reproduce the behavior

1. Start STRAPI in development mode
2. create a media field for multiple files
3. upload multiple files to media library --> error 503 occurs for all files and only first file is visible after a refresh. 

### Expected behavior

Same behavior as in production mode.

### Screenshots

--

### Code snippets

--

### Additional context

Adding database folder with *.sqlite file to ignore list would be a work-around but not tested:

```
module.exports = ({ env }) => ({
 ....
  apiToken: {
    salt: env('API_TOKEN_SALT')
  },
  watchIgnoreFiles: ['**/db/**'],
...
});
```

**Comment by kasonde** [comment]
Can't reproduce even in v4.2.0, care to share a video showing this issue occurring? This could help us understand what you're doing when this issue occurs

**Comment by derrickmehaffy** [comment]
As we haven't been able to reproduce this and there is no new information I'm going to go ahead and set this as closed. If you have new information that might help us reproduce this issue please feel free to share and we can look at reopening this issue.

Thanks!
