### ISSUE TITLE
users-permissions plugin config not avaiable

### ISSUE THREAD

**Issue by JejomStark** [strapi/strapi#13593]
### Required System information

- Node.js version: 14.19.3
- NPM version: 6.14.17
- Strapi version: 4.2.0
- Database: Postgresql
- Operating system: ubuntu

### Describe the bug

I created a users-permissions extensions, but when I deploy this extension, strapi send me an error and ask me to set "jwtSecret". 
Therefore, I add a ./config/plugins.js with jwtSecret but this file this file is not interpreted.
I do tests on add this file in ./config/env/staging/plugins.js but same error.

I see where is the error in node_modules/@strapi/plugin-users-permissions/server/bootstrap/index.js with the function :

strapi.config.get('plugin.users-permissions.jwtSecret') that it's undefined

How can I set correctly this variable, with a config file?

My plugins.js file:
```js
module.exports = ({ env }) => ({
    'users-permissions': {
        enabled: true,
        config: {
            jwtSecret: env('JWT_SECRET'),
            jwt: {
                expiresIn: '7d',
            },
        },
    }
});

```

### Steps to reproduce the behavior

1. create user extensions in ./src/extensions/users-permissions
2. add config/plugins.js
3. run your app with environment diffrent of "development"

### Expected behavior

I would like to configure my JWT environment with ./config/env/staging/plugins.js

**Comment by sjoukedv** [comment]
Did you try without the `enabled` key?

The following works for me:

```
  'users-permissions': {
    config: {
      jwtSecret: env('JWT_SECRET'),
      jwt: {
      expiresIn: '30d',
      },
    },
  },
```

You can always view the entire available config from the source: https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/config.js as the docs are outdated sometimes.

**Comment by kasonde** [comment]
Hi @JejomStark , could you please describe exactly what it is you're trying to achieve? As well as sharing clearer steps to reproduce what you're trying to achieve? With the information shared? I'm unable to reproduce this issue.

**Comment by derrickmehaffy** [comment]
As we haven't been able to reproduce this and there is no new information I'm going to go ahead and set this as closed. If you have new information that might help us reproduce this issue please feel free to share and we can look at reopening this issue.

Thanks!

**Comment by NicolasJaussaud** [comment]
I arrived at the same problem. No matter how much you put in the "config/plugin" file, the "users-permissions" object is not interpreted. As a result, the jwtSecret is missing in production.

Does anyone have a solution?

**Comment by derrickmehaffy** [comment]
> I arrived at the same problem. No matter how much you put in the "config/plugin" file, the "users-permissions" object is not interpreted. As a result, the jwtSecret is missing in production.
> 
> Does anyone have a solution?

It's "plugins" not "plugin" any config file for multiple parts is plural. "admin", "server", "api" are singular because there is only one. "plugins", "middlewares" are plural because it contains the config of multiples.
