### ISSUE TITLE
Custom content type names for the admin

### ISSUE THREAD

**Issue by kamwing** [strapi/strapi#1359]
**What is the expected behavior?**

Please add "Field Name" when Add New Field in Content Type Builder

It's similar "Collection Name" when the name of your Content Type and your table name differ

**Comment by derrickmehaffy** [comment]
@lauriejim likely related to previous discussion: https://github.com/strapi/strapi/issues/661

I believe @Aurelsicoko and I spoke at length about this as a planned change, not sure what you guys had in mind for an ETA since it will change quite a bit of stuff.

**Comment by Aurelsicoko** [comment]
@kamwing @derrickmehaffy IMO, it has nothing to do with the Content-Type Builder. It's a pure UI issue that should be handled by the Content Manager plugin which will allow you to add custom label name for a specific field.

We're going to develop a new section in the Content Manager. Please note this is a work in progress, not the final design.
![screen shot 2018-06-22 at 15 57 13](https://user-images.githubusercontent.com/4144726/41780423-fb5a6f46-7634-11e8-89d2-7f2e186b0b1a.png)

- Add label to an attribute.
- Add description to an attribute to help the marketing people to contribute for example.
- Allow a field to be editable or not (administrator permissions could override this config).
- Custom the layout and the position of the field in the Edit view.

**Comment by lauriejim** [comment]
It's released in last version of Strapi.
There is a content manager section in the left menu to update field name

**Comment by nodegin** [comment]
Why is this closed? How to update the CT name?

**Comment by derrickmehaffy** [comment]
@nodegin because it's related to field names, it's already on the roadmap for the left menu names but it's not currently possible.

**Comment by Aurelsicoko** [comment]
In the latest version of Strapi, you can create a CT with a custom name (spaces are allowed).

**Comment by jcieslar** [comment]
@Aurelsicoko Are you going to add to strapi https://github.com/strapi/strapi/issues/1359#issuecomment-399464357 ? CT name is propagated to api and to database structure but labels would be very helpful for content menagers in the admin interface.
