### ISSUE TITLE
jwt storage and authorization

### ISSUE THREAD

**Issue by dpedron** [strapi/strapi#13599]
### Required System information

- Node.js version: 14.19.3
- Yarn version: 1.22.19
- Strapi version: 4.1.12
- Database: MySql 2.18.1
- Operating system: windows 11 version 21H2

### Describe the bug

I try to upload a file with  fetch but i get a 401 (Unauthorized) for response.
My token is stored in the sessionStorage.

3 other members of my team tried to upload the file.
1 had the same response and token stored in the sessionStorage
The others managed to upload the file, but i don't know why their token  were stored in the localStorage.

```
const uploadFile = async () => {
    const token = `Bearer ${window.sessionStorage.jwtToken.replace(/\"/g, '')}`; //  const token = `Bearer ${window.localStorage.jwtToken.replace(/\"/g, '')}`; // If in localStorage
    const fileInput = document.getElementById('file-upload-input');

    var formData = new FormData();
    formData.append('files', fileInput.files[0]);

    var requestOptions = {
      method: 'POST',
      parseReqBody: false,
      headers: {
        Authorization: token,
      },
      body: formData,
      redirect: 'follow',
    };

    await fetch('http://127.0.0.1:1337/api/entries/upload', requestOptions);
  };
```

Why i have a 401 error as an answer ?
Why the token is stored either in the local or in the session storage ?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by KoTTi97** [comment]
For those wondering why the JWT token is stored in either localStorage or sessionStorage, it depends on whether the user selected the "Remember me" checkbox when logging into Strapi
