### ISSUE TITLE
Setting pagination pageSize to 0 still returns an object.

### ISSUE THREAD

**Issue by dogunbound** [strapi/strapi#13602]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.2.0
- Database: Postgres
- Operating system: Linux

### Describe the bug

Whilst using the REST API for querying, setting pageSize to 0 unexpectedly changes to 1. 

### Steps to reproduce the behavior

1. Create a collection with multiple entries.
2. Create a query with pagination pageSize set to 0.
3. Query it.

Alternatively, click this link:
[?pagination%5Bpage%5D=1&pagination%5BpageSize%5D=0](https://syrios.cs.uh.edu/api/coins?pagination%5Bpage%5D=1&pagination%5BpageSize%5D=0)

### Expected behavior

Documentation that 0 = 1 for pageSize

OR

Actually, return 0 items.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

The ability to query the metadata without querying data would be excellent.

**Comment by bolg55** [comment]
Does setting pageSize to -1 give you the desired result?

**Comment by dogunbound** [comment]
No
