### ISSUE TITLE
BUG: Sometimes unable to filter by field in admin portal

### ISSUE THREAD

**Issue by chrift** [strapi/strapi#13608]
### Required System information

- Node.js version: 16.4.2
- Npm version: 8.5.0
- Yarn version: 1.22.18
- Strapi version: 4.1.8
- Database: Postgres
- Operating system: Linux

### Describe the bug

I am unable to filter by a field in the admin area. There is a "band" field, which is a relation to the “band” collection type that does not appear in the filter dropdown. All other fields (including other relations) are in the filter dropdown, and I can’t see anywhere that configures which fields are filterable. This is the case for all collections that have a relation to band, **as well as some other relations**, i.e. the problem is not specific to relations to "band"s. 

The filter appears locally, but not in our deployed environment. Same codebase, same database.

### Steps to reproduce the behavior
1. Add a relation to a collection type.
2. Attempt to filter by it on the collection list view.

### Expected behavior
Expected to see the "band" field in the filter drop down

## Local
Note the presence of the band field and filter
![image](https://user-images.githubusercontent.com/2837753/174783370-238c0bd2-4277-44f5-9c55-2234abbd528b.png)

## Deployed
Note the absence of the band filter, but the presence of the field. This is the same collection as the above screenshot. 
![image](https://user-images.githubusercontent.com/2837753/174783673-c05bbaf3-64ed-4295-85ff-491964de9fcc.png)

### Code snippets

N/A

**Comment by derrickmehaffy** [comment]
Can you try updating to v4.2.2 as I am unable to reproduce?

**Comment by soupette** [comment]
It might be related to RBAC only allowed fields can be filtered in the dropdown.

**Comment by chrift** [comment]
> It might be related to RBAC only allowed fields can be filtered in the dropdown.

I am a super user, so I think I should have access to everything. 
When you say allowed fields, do you mean because it's a relation, I should have access to the underlying collection? Or is there a separate control for individual fields?

**Comment by derrickmehaffy** [comment]
@chrift I still can't reproduce running the latest, is your code public?

**Comment by soupette** [comment]
@chrift did you disable the filtering in the settings page of the content manager listview?

**Comment by derrickmehaffy** [comment]
As we have no new information I'm going to set this as closed for now.

**Comment by chrift** [comment]
> @chrift I still can't reproduce running the latest, is your code public?

Its not I'm afraid, it's a client's codebase. 

> @chrift did you disable the filtering in the settings page of the content manager listview?

No, and can filter by other fields. 
![image](https://user-images.githubusercontent.com/2837753/184930753-536d526e-0c67-4224-875d-12bb69d3c613.png)

**Comment by derrickmehaffy** [comment]
Can you try to reproduce the client codebase in a fresh project and see if you can reproduce the issue?

**Comment by chrift** [comment]
I have, and I cannot reproduce locally.
