### ISSUE TITLE
Using the (public) '/email' route from the frontend returns 401 unauthorized

### ISSUE THREAD

**Issue by akarkaselis** [strapi/strapi#13616]
### Required System information
- Node.js version:
v16.15.0
- NPM version:
8.5.5
- Strapi version:
v4.1.12
- Database:
Postgresql
- Operating system:
Win 10

I am using axios to send an email from my frontend through strapi and it doesn't work unless I add "Authorization: 'bearer + token' (I use the one that i found while sending myself a test email in strapi admin panel). 

What i don't understand is that I made sure to set Send Email to allow Public Role. 

here is what I do (that works) in the frontend (Nuxtjs btw): 

> await this.$axios.$post( '/email',
          {
            to: 'email@mail.com'
            from: 'otheremail@mail.com'
            subject: 'Email Subject',
            html: '<strong>Hello world!</strong>',
            attachments:  [data],
          },
          {
            headers: {
              Authorization: 'Bearer +token I got from strapi',
              'Content-Type': 'application/json',
            },
          }
        )

Any day now that token will expire. Is there a way to set one up and have the frontend use it or is there an actual way of using '/email' without autorisation?

I've tried to play with the permissions in the admin panel, but I'm starting to think this is a bug.

Thank you

### Steps to reproduce the behavior
1. Use strapi as backend. 
2. Code the above code on your front-end.
3. Make sure you enable the public "send" permission in strapi settings.
4. You will realise you need a valid token to send the email.

### Expected behavior
Email should be able to send without needing authorization.

**Comment by kasonde** [comment]
@akarkaselis can you share the URL you're posting to?

**Comment by kasonde** [comment]
Gotcha, any logs coming back from the admin?

It seems also that your URL is wrong. In Strapi v4, it's http://localhost:1337/api/email

**Comment by akarkaselis** [comment]
Well, trying with /api/email gives me a 401 and I just have no idea what token that one wants. With for the moment /email I can use the token I found while sending myself a test email from strapi. I don't see any logs, sorry.
