### ISSUE TITLE
Register - always return 'This username is already taken'

### ISSUE THREAD

**Issue by leinue** [strapi/strapi#1361]
**Informations**
- node: **v9.11.1**:
- npm: **v5.6.0**:
- strapi: **v3.0.0-alpha.12.3**:
- database: **mongodb**:
- OS: **OSX**:

**What is the current behavior?**

when i post a request to register a new user in strapi, there's always return:

``` javascript
{"statusCode":400,"error":"Bad Request","message":"This username is already taken"}
```
**Steps to reproduce the problem**

POST /auth/local/register HTTP/1.1
Host: localhost:1337
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 323ffcdc-edd1-3101-0a87-855ebd162d46

{"email":"sssswwxxqqqxssss@qq.com","username":"ssssqqqssw","password":"1234567890"}

**What is the expected behavior?**

it should successfully register

**Suggested solutions**

i dont know

**Comment by leinue** [comment]
![image](https://user-images.githubusercontent.com/2469688/41287645-052d089c-6e76-11e8-8221-b2cd740443fa.png)

this user does not exist

**Comment by mnlbox** [comment]
@leinue Maybe Related: #1254

**Comment by derrickmehaffy** [comment]
@mnlbox I think that issue was AdminUI related, posting a new user via the api shouldn't happen as I think it is decoupled from the adminUI

**Comment by leinue** [comment]
@derrickmehaffy posting via the api also has the problem, adminUI just for display the error

**Comment by leinue** [comment]
@derrickmehaffy posting via the api also has the problem, adminUI just for display the error

**Comment by leinue** [comment]
Haven't been solved

**Comment by leinue** [comment]
When i redeploy the project, it worked fine

**Comment by leinue** [comment]
I have to reopen this issue coz I found a login error:

When I post via api to login, there's alway return 

``` shell
Identifier or password invalid.
```

**Comment by leinue** [comment]
![image](https://user-images.githubusercontent.com/2469688/41327411-f477518a-6ef5-11e8-9782-cdba3b2c44fd.png)
![image](https://user-images.githubusercontent.com/2469688/41327418-f9fa247a-6ef5-11e8-902b-f3988cc0d89e.png)

@mnlbox @derrickmehaffy

**Comment by leinue** [comment]
Using username worked fine, but email can not work

**Comment by derrickmehaffy** [comment]
Odd @leinue I can't reproduce this, Posting both with email or username.

**Comment by lauriejim** [comment]
@leinue Can you give me you r user model please.

**Comment by daqst** [comment]
I am encountering this error too.  I'm wondering if it is the same (since it's occurring in the `getProfile` function of Providers.js) The steps to reproduce:

- Set up a new Strapi development installation.
- Log in and create a new (admin) user.
- Enable Google authentication
- Go to `localhost:1337/connect/google`
- Select Google account to login with
- Presented with 'Auth.form.error.email.taken'

The plugins/users-permissions/service/Providers.jsL69 seems to be checking if there is a user where the provider (google) does not match the provider (local).  This is indeed true for the first and only user.  This statement then fails and returns an error.

If you are checking to see if the email is already taken?  Shouldn't the find statement be comparing email as well as provider?

**Comment by leinue** [comment]
``` javascript
{
  "connection": "default",
  "info": {
    "name": "user",
    "description": ""
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    }
  }
}
```

@lauriejim

**Comment by lauriejim** [comment]
Ho okay, you use numbers as password.
Please check this issue : https://github.com/strapi/strapi/issues/932

Please use something else than numbers for your password.
Will not work on now so feel free to investigate on this issue and submit a PR.
