### ISSUE TITLE
npm run build not exiting process

### ISSUE THREAD

**Issue by arsicaleksa** [strapi/strapi#13614]
### Required System information

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.1.12
- Database: PostgreSQL
- Operating system: MacOS

### Describe the bug

When you run `npm build`, the build process is completed but `npm run build` command never exited and this causes problems for automated deployments, next command cannot be executed because `npm run build` command is not exited.

### Steps to reproduce the behavior

1. Open a terminal
2. Navigate to the Strapi app folder
3. Run `npm run build`
4. Build is completed but the `npm run build` command is never exited

### Expected behavior

The build process should be exited when it is completed.

### Screenshots

It is built successfully but the process is still running.
![image](https://user-images.githubusercontent.com/76953102/175052001-9224db66-8ce0-4a4e-80dd-bb3c619df356.png)

### Code snippets

`process.exit();` is not being called.
https://github.com/strapi/strapi/blob/master/packages/core/strapi/lib/commands/build.js#L50

### Additional context

How to build Strapi UI?

**Comment by arsicaleksa** [comment]
@kasonde I've updated the issue.

**Comment by arsicaleksa** [comment]
3. How to build UI in CI/CD process, `npm run build` completely blocks the process?

**Comment by kasonde** [comment]
@arsicaleksa understood. please ask all questions either on our Discord or Forum.

**Comment by razorness** [comment]
This happens with Strapi `v4.5.2` using official GraphQL plugin on Nodejs `v16.18.1` and Ubuntu `20.04.5 LTS` when you setup Apollo Server with Redis Cache:

`config/plugins.ts`:
```ts 
import { KeyvAdapter } from '@apollo/utils.keyvadapter';
import Keyv from 'keyv';
import KeyvRedis from '@keyv/redis';

export default ({ env }) => ({
	graphql : {
		enabled: true,
		cache  : new KeyvAdapter(new Keyv({ store: new KeyvRedis('redis://localhost:6379') })),
	}
});
```

**Comment by arsicaleksa** [comment]
@kasonde, yes the issue still persists.

The process will not exist on the successful build, you can see it here: https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/commands/builders/admin.js#L51
`process.exist()` is still missing.

**Comment by garytube** [comment]
still having this issue!

**Comment by joshuaellis** [comment]
> still having this issue!

Hey @garytube, I've just taken a quick look at this with both `yarn` & `npm` on node `16` & `18` using `strapi@4.6.1` but I couldn't reproduce this – would you be able to give some details of your setup etc. so I can try to reproduce?

**Comment by garytube** [comment]
@joshuaellis sure!

node 18.14.0
npm 9.4.2
yarn 1.22.9

created a new test instance with

`yarn create create-strapi-app@latest test_strapi --quickstart`
 
 changed a few config settings and did a  yarn build - which does not exit


```json
{
  "name": "test-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/strapi": "4.6.1",
    "@strapi/plugin-users-permissions": "4.6.1",
    "@strapi/plugin-i18n": "4.6.1",
    "better-sqlite3": "8.0.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "c6f89b63-c939-429c-979f-a0c006f4fb57"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by joshuaellis** [comment]
Our build command is also ran with `develop` and the process cannot exit during `develop` so we need to differentiate between them.

**Comment by alicanso** [comment]
same here!

**Comment by cwillinx** [comment]
> This happens with current Strapi when you setup Apollo Server with Redis Cache. Hoewer, the build seems to work.
> 
> `config/plugins.ts`:
> 
> ```ts
> import { KeyvAdapter } from '@apollo/utils.keyvadapter';
> import Keyv from 'keyv';
> import KeyvRedis from '@keyv/redis';
> 
> export default ({ env }) => ({
> 	graphql : {
> 		enabled: true,
> 		cache  : new KeyvAdapter(new Keyv({ store: new KeyvRedis('redis://localhost:6379') })),
> 	}
> });
> ```
> 
> Environment:
> 
> * Strapi `v4.5.2` with official GraphQL plugin
> * Typescript `v4.6.2` (from Strapi)
> * Yarn `v1.22.19`
> * Nodejs `v16.18.1`
> * Ubuntu `20.04.5 LTS`
> 
> `tsconfig.json`:
> 
> ```json
> {
>   "extends": "@strapi/typescript-utils/tsconfigs/server",
>   "compilerOptions": {
>     "outDir": "dist",
>     "rootDir": "."
>   },
>   "include": [
>     "./",
>     "./**/*.ts",
>     "./**/*.js",
>     "src/**/*.json"
>   ],
>   "exclude": [
>     "node_modules/",
>     "build/",
>     "dist/",
>     ".cache/",
>     ".tmp/",
>     "src/admin/",
>     "**/*.test.*",
>     "src/plugins/**"
>   ]
> }
> ```
> 
> It would be great to receive an error message.

I have exactly this issue with **Strapi 4.14.5.**
When I comment out this line, the admin build finishes as expected.

**Comment by joshuaellis** [comment]
We've reworked this pipeline so these issues shouldn't be a problem, you're several versions behind - I would look to upgrade to be honest.

**Comment by cwillinx** [comment]
I updated Strapi to the latest version - **Strapi 4.17.1.**

**Unfortunately, the issue still exists.**

The last console output is "Building admin panel (30333ms)", the process never exits.

Please, reopen the issue, @joshuaellis!

**Comment by joshuaellis** [comment]
@cwillinx if you're still facing the issue, please a new issue following the template so we can reinvestigate.

**Comment by rohit-32** [comment]
For people still facing this issue, it happens because Redis connects  as soon as you initialise it, i manages to fix this by making Redis connection lazy,

**Comment by cwillinx** [comment]
Thank you so much, @rohit-32 !

Could you share how to achieve the lazy connection?
