### ISSUE TITLE
cannot install using npx create-strapi-app@latest my-project --quickstart

### ISSUE THREAD

**Issue by AyaanMAG** [strapi/strapi#13627]
when i initailly ran it, i got 

`create-strapi-app@latest
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'create-strapi-app@4.2.0',
npm WARN EBADENGINE   required: { node: '>=14.19.1 <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.9.0', npm: '8.5.5' }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@strapi/generate-new@4.2.0',
npm WARN EBADENGINE   required: { node: '>=14.19.1 <=16.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.9.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Creating a new Strapi application at D:\Strapi CMS\ayaanmag-personal-website.
Creating files.
Error while installing dependencies:
error ayaanmag-personal-website@0.1.0: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "17.9.0"
error Found incompatible module.

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd D:\Strapi CMS\ayaanmag-personal-website && yarn install`

then after switching to the newly created dir and running yarn install I got
`yarn install v1.22.15
info No lockfile found.
[1/5] Validating package.json...
error ayaanmag-personal-website@0.1.0: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "17.9.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command`

yarn has always been up to date and now i updated npx too but the npx version couldn't be more than a month old so its not ancient or something

Im running windows 10

**Comment by raflymln** [comment]
you are using Node v17, strapi only works in node 16.15.1 or lower
