### ISSUE TITLE
[database/dialects/mysql] allow fulltext indexes to be recognized

### ISSUE THREAD

**Issue by lkho** [strapi/strapi#13628]
### Required System information

- Node.js version: 16.15
- NPM version: 8.3.0
- Strapi version: 4.3.0-beta.1
- Database: mysql 8
- Operating system: macOS

### Describe the bug

A custom index other than primary key and unique index will be dropped and recreated every time the schema is being synced.

### Steps to reproduce the behavior

1. define a content type with a custom index
```json
{
  "kind": "collectionType",
  "collectionName": "search_hits",
  "attributes": {
    "word": { "type": "string", "required": true }
  },
  "indexes": [
    { "name": "ft_search", "columns": ["word"], "type": "fulltext" }
  ]
}

```
2. restart strapi
3. modify some parts of the schema, e.g. add a column
```json
{
  "kind": "collectionType",
  "collectionName": "search_hits",
  "attributes": {
    "word": { "type": "string", "required": true },
    "col2": { "type": "string" }
  },
  "indexes": [
    { "name": "ft_search", "columns": ["word"], "type": "fulltext" }
  ]
}

```
4. restart strapi
5. even the index does not change, it gets dropped and recreated with the same parameters again.

### Expected behavior

The index should be considered _unchanged_.

### Additional context

the schema inspector does not recognize full text indexes and return a `null` type for these, thus it is always marked as changed in diff.

https://github.com/strapi/strapi/blob/c7c4518adae2f4e134f4178e4397ffd119de758a/packages/core/database/lib/dialects/mysql/schema-inspector.js#L164

**Comment by alexandrebodin** [comment]
Hi, after revalidating, I can confirm this was fixed last year.
