### ISSUE TITLE
Data With GraphQl is Empty

### ISSUE THREAD

**Issue by kevingrondin** [strapi/strapi#13635]
Node.js version: v16.15.1
NPM version: 8.11.0
Strapi version: 4.2.0
Database: "better-sqlite3": "7.4.6"
Operating system: windows 11

```Shell
npx create-strapi-app@latest backend
cd backend
npm run strapi install graphql
npm run develop
```

Create a collection __Product__ with:
- __title__ : String (required)
- __description__ : String (required)
- __price__ : Number (required)
- __image__ : Media (required)

I create two __Product__ in __Product__ with all required

I add rules find and findOne on __Product__ for __Public__

and on `http://localhost:1337/graphql`

```Graphql
query {
  products {
    data {
      id
      attributes {
        title
      }
    }
    meta {
      pagination {
        page
        pageSize
        total
        pageCount
      }
    }
  }
}
```

And my data is empty

```Graphql
{
  "data": {
    "products": {
      "data": [],
      "meta": {
        "pagination": {
          "page": 1,
          "pageSize": 10,
          "total": 0,
          "pageCount": 0
        }
      }
    }
  }
}
```

**Comment by edvincandon** [comment]
Did you activate the **Draft/Publish** setting on your content-type ? You probably forgot to publish your entities.

**Comment by kevingrondin** [comment]
> @kevingrondin Did you activate the **Draft/Publish** setting on your content-type ? You probably forgot to publish your entities.

Yes **Draft/Publish** is activate by default

**Comment by derrickmehaffy** [comment]
As no new information, marking as closed.
