### ISSUE TITLE
Data Empty

### ISSUE THREAD

**Issue by kevingrondin** [strapi/strapi#13634]
```Shell
npx create-strapi-app@latest backend
npm run strapi install graphql
npm run develop
```

Create a collection __Product__ with:
- __title__ : String (required)
- __description__ : String (required)
- __price__ : Number (required)
- __image__ : Media (required)

I create two __Product__ in __Product__ with all required

I add rules find and findOne on __Product__ for __Public__

and on `http://localhost:1337/graphql`

```Graphql
query {
  products {
    data {
      id
      attributes {
        title
      }
    }
    meta {
      pagination {
        page
        pageSize
        total
        pageCount
      }
    }
  }
}
```

I'v got this 🤯

```Graphql
{
  "data": {
    "products": {
      "data": [],
      "meta": {
        "pagination": {
          "page": 1,
          "pageSize": 10,
          "total": 0,
          "pageCount": 0
        }
      }
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by kevingrondin** [comment]
- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: 4.2.0
- Database: "better-sqlite3": "7.4.6"
- Operating system: windows 11
