### ISSUE TITLE
Upload - (koa-body) formidable filter not applied

### ISSUE THREAD

**Issue by jakubmirejovsky** [strapi/strapi#13645]
Hi, I'm trying to secure a file upload to only accept certain file types (extension and mime check).

Since Strapi uses koa-body and formidable to handle uploads, I followed their respective readmes.

I set up config/middlewares.js as follows:

```
{
    name: "strapi::body",
    config: {
      formLimit: "512mb", // modify form body
      jsonLimit: "512mb", // modify JSON body
      textLimit: "512mb", // modify text body
      formidable: {
        maxFileSize: 512 * 1024 * 1024, // 512MB file limit,

        /* TODO This filter somehow doesn't work */

        filter: function ({name, originalFilename, mimetype}) {
          console.log("FORMIDABLE", name, originalFilename, mimetype);
          // keep only images
          return mimetype && mimetype.includes("image");
        }
      },
    },
  },
```

**the filter function is not passed to formidable options** - no console log and no filtering is happening.

I tried to reverse-engineer the code, but with no success.

**The goal is to restrict POST /upload to only accept certain file types.**

Steps to reproduce:
```
yarn create strapi-app my-project --quickstart
#change middlewares.js to the code above and try to upload a file (like an .exe os .msi)
```

Node 14.19.3

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by jakubmirejovsky** [comment]
---
name: 🐛 Bug Report
about: Middleware config not passed to formidable
---


## Bug report

### Required System information


- Node.js version: 14.19.3
- NPM version: 6.14.17
- Strapi version: 4.2.2
- Database: SQLite
- Operating system: Windows 10

### Describe the bug

strapi::body config ('filter' property) is not passed to formidable (via koa-body)

### Steps to reproduce the behavior

1. yarn create strapi-app my-project --quickstart
2. change middlewares.js to the code in the original comment
3. Go to http://localhost:1337 and create your administrator account
4. Go to http://localhost:1337/admin/plugins/upload
5. Click on Add new assets
6. Pick a dangerous file, like an .exe or .php or .html

### Expected behavior

Uploaded file should go through filter defined in config/middlewares.js.

The console.log() should write to the terminal

### Screenshots

Not applicable

### Code snippets

**config/middlewares.js**

```
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  {
    name: "strapi::body",
    config: {
      formLimit: "512mb", // modify form body
      jsonLimit: "512mb", // modify JSON body
      textLimit: "512mb", // modify text body
      formidable: {
        maxFileSize: 512 * 1024 * 1024, // 512MB file limit,

        /* TODO This filter somehow doesn't work */

        filter: function ({name, originalFilename, mimetype}) {
          console.log("FORMIDABLE", name, originalFilename, mimetype);
          // keep only images
          return mimetype && mimetype.includes("image");
        }
      },
    },
  },
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];

```

If applicable, add code samples to help explain your problem.

### Additional context

This might be related to koa-body and its interface. Still, it is very much a security issue to let users upload dangerous files.
