### ISSUE TITLE
Strapi shcema issue

### ISSUE THREAD

**Issue by Denchooo** [strapi/strapi#13641]
Hi guys,
is it possible someone to help me with a very weird problem. Everyday when i open the Strapi and check let's say for example table Products inside i have field "keywords" etc. but when i come back more than 6th hours this field isn't presented in the Strapi Schema. I am using g-cloud for hosting and postgre SQL 12 and strapi 3.5.3 and node_version 14.19

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by BlagoyS** [comment]
> > This is a templated message
> 
> Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> A proper issue submission let's us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue with the template and we can reopen this report.
> 
> Thank you.

https://github.com/strapi/strapi/issues/13641#issuecomment-1171017965
