### ISSUE TITLE
User Profile Name field not validated

### ISSUE THREAD

**Issue by Gulshanaggarwal** [strapi/strapi#13648]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.1
- Strapi version: v4.2.0
- Database: Sqlite
- Operating system: Windows

### Describe the bug

Name field under the User Profile section is marked as required but it can be easily bypassed using spaces.

### Steps to reproduce the behavior

1. Go to 'http://localhost:1337/admin/me'
2. Click on 'Name Field'
3. Press Space Bar 2-3 times
4. Save

### Expected behavior

When user input their name it should be trimmed to avoid spaces.

### Additional context

It saves exactly in database(eg. empty spaces string) what user enter in the field, there is no validation.

**Comment by richorrichard** [comment]
Hi @derrickmehaffy! I'm still pretty new to the project, but I looked into this issue and it seems like there's a pretty easy fix. I've submitted PR, but there may be a complication. I looked into the form validation for the user profile, and the `yup` schema was updated 2 years ago ([Fix validations for users Commit b7686d0](https://github.com/strapi/strapi/commit/b7686d0)), and my update would revert that change. Maybe @soupette can provide some more insight about whether this would roll back an essential fix, but it looks to me like it passes tests and doesn't impact the saved data.

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy! I'm still pretty new to the project, but I looked into this issue and it seems like there's a pretty easy fix. I've submitted PR, but there may be a complication. I looked into the form validation for the user profile, and the `yup` schema was updated 2 years ago ([Fix validations for users Commit b7686d0](https://github.com/strapi/strapi/commit/b7686d0)), and my update would revert that change. Maybe @soupette can provide some more insight about whether this would roll back an essential fix, but it looks to me like it passes tests and doesn't impact the saved data. 

That's a good catch, soupette doesn't work for us anymore but I know he is still hanging around in the community. I'll test your PR though and see if I notice anything breaking.

Thanks for the quick PR :)

**Comment by gracebir** [comment]
@WalkingPizza  what does `gu` and `sa` for as country code
