### ISSUE TITLE
GraphQL - Apollo Server (DOS, persistent queries)

### ISSUE THREAD

**Issue by ihmpavel** [strapi/strapi#13646]
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: 4.2.0
- Database: Postgres
- Operating system: Docker, `node:lts-alpine`, AWS ECS

`package.json` dependencies
```
...
"dependencies": {
    ...
    "@strapi/plugin-graphql": "^4.2.0",
    "@strapi/plugin-i18n": "^4.2.0",
    "@strapi/plugin-users-permissions": "^4.2.0"
    "@strapi/strapi": "^4.2.0",
    ...
}
```

### Describe the bug

After building fresh new production instance with latest Strapi, an `Apollo Server` warning occurs. 

### Steps to reproduce the behavior

1. Create fresh new Strapi instance
2. Build Strapi (Docker, `node:lts`, Alpine)
3. Start Strapi
4. Wait till server boot
5. See error/warning in the console before Strapi startup

`Persisted queries are enabled and are using an unbounded cache. Your server is vulnerable to denial of service attacks via memory exhaustion. Set `cache: "bounded"` or `persistedQueries: false` in your ApolloServer constructor, or see https://go.apollo.dev/s/cache-backends for other alternatives.`

### Expected behavior

After starting a production server there should not be Apollo GQL warning. (Locally on M1 Macbook there is no error/warning.)

Changed because of Apollo Server 3.9 - https://www.apollographql.com/docs/apollo-server/performance/cache-backends/

**Comment by derrickmehaffy** [comment]
Can not reproduce on v4.2.0 or v4.3.0.beta-1

![image](https://user-images.githubusercontent.com/8593673/176728382-c2016da4-510b-4040-a4dd-6a7c88058cb4.png)


Will close for now but need more information from user on how to reproduce to reopen.

**Comment by b3nab** [comment]
I don't know if can help but, the server should run for a long time to see errors for me. I don't know if there are some problems about the connections to db.

Also, I managed to get the same error, plus some others.

![image](https://user-images.githubusercontent.com/3042431/179054358-c8823031-bf81-4e36-ae6a-e635ac2a32a5.png)

![image](https://user-images.githubusercontent.com/3042431/179054509-7f0526f3-6881-4bd4-bfee-d843aee12fd1.png)

![image](https://user-images.githubusercontent.com/3042431/179054214-384c6d60-c989-4584-aa25-165697e82873.png)

**Comment by b3nab** [comment]
Yes, I'm using the fantastic tutorial on how to run strapi v4 in a docker container.

**Comment by derrickmehaffy** [comment]
You need to modify the DB pooling config and set the min pool size to 0 instead of 1. Docker's network has some stupid logic that if a connection is open for too long it will just kill it which destroys the idle pool connections to the database.

See: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#database-pooling-options

It's a dumb thing that docker does without much explanation

**Comment by b3nab** [comment]
Oh, I was missing that part.

So, just to help some others also, here are the steps to get rid of 
error: select count(*) as "count" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly Error: select count(*) as "count" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly

and also 

error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly Error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly

The steps are:
- edit the cms/config/database.js
- add the following part to `connection`:
```
{
  client: 'postgres',
  connection: {
    // ...
    pool: {
      min: 0
    }
    // ...
  }
}
```

and that's all (?).

**Comment by derrickmehaffy** [comment]
Yup exactly, I just submitted a documentation PR here: https://github.com/strapi/documentation/pull/999

**Comment by derrickmehaffy** [comment]
All good, glad you got it figured out :)

**Comment by b3nab** [comment]
Thanks a lot @derrickmehaffy . Your help has been crucial to get rid of this error, it was driving me crazy. :1st_place_medal: 

Anyway, just to continue talking regarding the issue on the first post. 

> Persisted queries are enabled and are using an unbounded cache. Your server is vulnerable to denial of service attacks via memory exhaustion. Set `cache: "bounded"` or `persistedQueries: false` in your ApolloServer constructor, or see https://go.apollo.dev/s/cache-backends for other alternatives.

I can see it right now with version 4.2.3 (just deployed).

![image](https://user-images.githubusercontent.com/3042431/179278870-72aa84f1-92fe-4947-bc1a-92187057ece8.png)

**Comment by b3nab** [comment]
It should also be treated as a security issue according to what I'm reading from here https://www.apollographql.com/docs/apollo-server/performance/cache-backends/#ensuring-a-bounded-cache

Inside the plugin `graphql` for strapi, the `ApolloServer` should also have `cache: "unbounded"` to ensure this problem won't happen.

So I searched for a quick solution: the plugin also let us overrides some values, we can change the configuration of plugin.
```
  'graphql': {
    enabled: true,
    config: {
      apolloServer: {
        cache: 'bounded'
      }
    }
  }
```

 Right now I'm testing this solution, I'll keep you posted.

**Comment by derrickmehaffy** [comment]
My concern is I can't reproduce this in a fresh project so there is something different from yours than from a fresh install.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/179296123-1e27d15a-c487-4d3d-bef5-64e79bccb078.png)

**Comment by ihmpavel** [comment]
Hi,

I was only able to reproduce it in production environment, not while developing. Not sure why, because the configuration is very similar. The only difference is the image we use while building the Docker image. 

I am not 100 % sure it pop ups in version 4.2.3, but removing `yarn.lock` and making fresh install showed it in production in version 4.2.2 (the initial issue).

I am not using any custom resolvers, everything managing through UI. 

Only custom provider on S3 (just few updates on the official one), deepl plugin and wysiwyg editor, both can be found in the Strapi Market.

Maybe we can reopen this?

I can create PR, adding https://github.com/strapi/strapi/blob/master/packages/plugins/graphql/server/bootstrap.js#L38 the required config, as mentioned by you and by my initial issue where something changed in version 2.9 of ApolloServer https://www.apollographql.com/docs/apollo-server/performance/cache-backends/

**Comment by ihmpavel** [comment]
Hi, successfully replicated in version 4.2.3 in AWS ECS

<img width="400" alt="image" src="https://user-images.githubusercontent.com/42217494/179364875-0e5c6cf8-c84b-4f24-a771-8f875beb592f.png">

**Comment by vanishree165** [comment]
Hello Techie's 👩‍💻 🧑‍💻 ,

So for now i faced the same above issue while in deployment.

And I'm using 

Node.js version: v14.17.5
Database: Postgres
Operating system: Heroku 
Graphql version: 16.2.0

Hereby i attached screenshot for your reference . Kindly reopen/help to sort out this issue 

<img width="1095" alt="Screenshot 2022-09-21 at 3 02 54 PM" src="https://user-images.githubusercontent.com/69952120/191469930-0ce6d170-e42a-475c-a025-a705f73f69eb.png">

**Comment by FahmyChaabane** [comment]
I am facing the same stuff without even having a Database.
I am just using a gql server as middle-man service.
And yes, i am in docker.

**Comment by vanishree165** [comment]
> Hello Techie's 👩‍💻 🧑‍💻 ,
> 
> So for now i faced the same above issue while in deployment.
> 
> And I'm using
> 
> Node.js version: v14.17.5 Database: Postgres Operating system: Heroku Graphql version: 16.2.0
> 
> Hereby i attached screenshot for your reference . Kindly reopen/help to sort out this issue
> 
> <img alt="Screenshot 2022-09-21 at 3 02 54 PM" width="1095" src="https://user-images.githubusercontent.com/69952120/191469930-0ce6d170-e42a-475c-a025-a705f73f69eb.png">

I fixed this issue guys by adding "persistedQueries: false," in my configuration part


`const apollo = new ApolloServer({
    typeDefs: schema,
    persistedQueries: false,
    resolvers,
    context: async (req) => ({ auth: _.get(req.res.locals, 'auth.payload'), db }),
    plugins: [
      ApolloServerPluginLandingPageGraphQLPlayground({
        settings: {
          'request.credentials': 'include',
          'editor.theme': 'dark',
        },
      }),
    ],
  })`
  
  Thanks 😊
