### ISSUE TITLE
Nested components

### ISSUE THREAD

**Issue by EVSHK** [strapi/strapi#13651]
Hello, i tried the **How to test it** exemple and it works on Strapi Admin side by editing the files directly.
But when i try to fetchAPI this page the response is not complete. Got only 1 sub-level.

try fetch 1 : const res = await fetchAPI("/testPage", {populate: "\*"});
try fetch 2 : const res = await fetchAPI("/testPage", {populate: {content: {populate: "\*"}}});

Can you help ? Maybe i missed something on te populate part or ?

![Capture d’écran 2022-06-24 à 16 19 22](https://user-images.githubusercontent.com/44260574/175554985-ee1e8afd-ec8c-4460-87dc-05b1131d8702.png)
![Capture d’écran 2022-06-24 à 16 18 28](https://user-images.githubusercontent.com/44260574/175554822-b259c9b2-a9ff-41e6-9fed-a06742a510b4.png)
![Capture d’écran 2022-06-24 à 16 17 39](https://user-images.githubusercontent.com/44260574/175554694-eae7e526-2640-4beb-9493-2c083eabc523.png)

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
