### ISSUE TITLE
Different values calling /findManyWithCount()/.count() and .findMany().length

### ISSUE THREAD

**Issue by aggieSzulcDornach** [strapi/strapi#13652]
## Bug report

Hi, I'm trying to make pagination. I have complex where query which I'm using in both .findMany() and .count().
The result from .count() is different and incorrect (I have no clue from where the result comes from).

I have internationalization (four languages: fr, de, nl, en)

Problem shows up only for non-default lang.

Description:

I have 127 entries in french.
I'm sending locale and a bunch of other filters to strapi.
I'm calling:
`await strapi.db.query('api::post.post').findMany({
      offset: (pagination.page - 1) * pagination.pageSize,
      limit: pagination.pageSize,
      populate: ctx.query.populate,
      orderBy: [{ publication_date: 'DESC' }, { id: 'DESC' }],
      where: whereData,
    });`
and result's length is 127.

When I'm calling:
`await strapi.db.query('api::post.post').count({
      where: whereData,
    });`
It gives me 352. The same is while calling .findManyWithCount().

Any help will be appreciated!

### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.2.0
- Database: Postgres

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/7631

(The root cause of the duplicate issue is these functions)
