### ISSUE TITLE
listLocales Returning 403 for Authenticated Users

### ISSUE THREAD

**Issue by kevinjmo** [strapi/strapi#13653]
### Required System information

- Node.js version: v16.13.2
- NPM version: v8.12.2
- Strapi version: v4.2.0
- Database: Postgres
- Operating system: macOS

### Describe the bug

When querying for `/api/i18n/locales` as an Authenticated User (with API token set in `headers.Authorization`), it still returns a 403 Forbidden. All other routes that require authentication are returning 200.

I found that when allowing the `listLocales` actions in the Public unauthenticated route (and not setting any `headers.Authorization`), it returns the list of locales properly.

### Steps to reproduce the behavior

Here’s a quick screencast demonstrating the GET requests for a Test collection type and for `listLocales`. You can see that in the admin panel, both are checked (and this is under the Authenticated Role). And when making the request with the API token, getting all the `tests` work while getting the locales return a 403.

![176329474-f7a8f3c8-dbf0-4e06-95d1-7c4e293330ad](https://user-images.githubusercontent.com/9851651/176479095-d9b8b2c3-b29e-4360-a157-0c458a004735.gif)

However, it seems to work when we enable it in the Public role as an unauthenticated user. Here you’ll see that I enabled the find actions for Tests and i18n locales and they both return 200.

![176329748-3191fb4e-eb2a-43f2-b312-64fb47092bee](https://user-images.githubusercontent.com/9851651/176479133-118a3b72-f8dd-4bec-bdc7-4223e5e63328.gif)

### Expected behavior

Querying for `/api/i18n/locales` as an Authenticated User (with API token set in `headers.Authorization`) should return 200.

### Additional context

Initially discussed with @derrickmehaffy in #10951, moved here as a new issue.

**Comment by derrickmehaffy** [comment]
Unable to reproduce: 
![image](https://user-images.githubusercontent.com/8593673/176727217-22aa8adb-ff63-4687-82a5-75b67e99ade1.png)

Both authenticated and public works. Note it's normal that if you provide an authorization header a request is no longer public. Public does not grant everyone access, it only grants non-authenticated users access (meaning no authorization header)

**Comment by kevinjmo** [comment]
Thank you for the update, @derrickmehaffy. Would you mind sharing what headers you’re using?

**Comment by derrickmehaffy** [comment]
> Thank you for the update, @derrickmehaffy. Would you mind sharing what headers you’re using?

Not at home at the moment so can't look at that request again but I didn't add anything specific so most likely just the client and type (application/json)

**Comment by kevinjmo** [comment]
<img width="1060" alt="Screen Shot 2022-06-30 at 11 30 42" src="https://user-images.githubusercontent.com/9851651/176751913-ee58c6d9-0463-4075-bfda-db53211a56af.png">

I believe I have the same setup as you, but I’m still getting the 403 Forbidden errors. What could be the issue here?

**Comment by kevinjmo** [comment]
@andrea-mono you said you were also running into a similar issue?

**Comment by andrea-mono** [comment]
> @andrea-mono you said you were also running into a similar issue?

Yes, but with graphql. I can't retrieve the locales also from the graphql playground.

**Comment by kevinjmo** [comment]
> No modifications to the users-permissions plugin @kevinjmo ?

No modifications other than enabling `listLocales` for the Authenticated role of course.

<img width="1116" alt="Screen Shot 2022-07-06 at 10 31 54" src="https://user-images.githubusercontent.com/9851651/177609505-2942449b-0034-40bb-a5f7-62f7d4601107.png">

**Comment by derrickmehaffy** [comment]
:thinking: there has to be something else that is missing here.

**Comment by derrickmehaffy** [comment]
Wow I'm sorry, I'm an idiot. I was testing with a JWT not an API Token.

- JWT from an authorized user: :heavy_check_mark: 
- Read/Write API token: :heavy_check_mark: 
- Read-Only API token: :x: 

So the issue is the route scopes most likely not allowing read-only.

**Comment by Convly** [comment]
Hi, I think the issue is mainly linked to how the read-only tokens work behind the scene. Currently, they're only checking for scopes ending with `find` or `findOne`, which doesn't fit the `listLocales` scope.

An idea would be to allow customizing the patterns for read-only tokens so that they can fit different application structures and user cases. (just have to think about how to handle REST vs GraphQL vs WS vs .... gracefully)
In the meantime, we're soon going to release a beta for the second iteration of API tokens, which will allow you to declare more granular permissions for your tokens (a bit like what you can do with U&P but for tokens). This should allow you to add the `listLocales` scope on top of the other methods you need.

**Comment by Convly** [comment]
However investigating a bit this issue made me spot the fact we're not exposing the right scope right now for GraphQL > i18nLocales, I'll submit a fix for that

**Comment by gitstart** [comment]
Hi, @Convly @derrickmehaffy could you please take a look at this PR.

**Comment by alexandrebodin** [comment]
Hi, reviewing old issues this as fixed a while back ;)
