### ISSUE TITLE
API Paths and Permission Role names won't update after renaming collections in strapi V4

### ISSUE THREAD

**Issue by pandeyprafull** [strapi/strapi#13656]
### Describe the bug

When you rename a collection type in Content-Type Builder, for example from Post to Article, the api path associated with the collection does not get updated; In our case, /posts returns the list of articles instead of /articles which only returns 404.
Furthermore, the same issue exist in Roles tab of USERS & PERMISSIONS PLUGIN section in Settings page where either in Authenticated or Public Permissions, the name of the collection type in Application accordion remains to be the previous value, in our example Post.
### Steps to reproduce the behavior

1. Create a collection type in Content-Type Builder ( for example named Post )
2. Rename the collection ( for example to Article )
3. Check the api path for the newly renamed collection in localhost ( http://localhost:1337/articles )
4. Check Authenticated/Public Permissions of Application accordion in Settings page => Roles => USERS & PERMISSIONS PLUGIN

### Expected behavior

The api path associated with collection types alongside their permission role names should update accordingly after renaming a collection.

### System 
- Node.js version: v14.18.1
- NPM version: 8.3.0
- Strapi version: 4.0.2
- Database: mysql
- Operating system: Ubuntu

**Comment by pandeyprafull** [comment]
@derrickmehaffy Please check this issue

**Comment by derrickmehaffy** [comment]
This is intended for now as renaming the content type in the type builder is a visual change and doesn't rename all the nested files and folders on the filesystem nor does it modify the routes.

We do not plan to change this in the near future. Can you please post this request on our feature request board here: https://feedback.strapi.io
