### ISSUE TITLE
Amazon isn't working properly

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#1366]
The documentation and site isn't running properly. It's dead or very slow. Why don't you consider switching to GitHub pages for hosting? Everything else is working perfectly on my connection. I'm learning this wonderful tool and documentation seems to be the problem here. So I've considered building it locally. I thought my connection was dead until I saw this error:

504 ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. 
For more information on how to troubleshoot this error, please refer to the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-504-gateway-timeout.html). 
Generated by cloudfront (CloudFront)
Request ID: LC2jGUzfii2k_gVAtRNNiXQLxdxDDmCqBC0e3eypEi52h1rd0R4UcQ==

**Comment by SharkeyO** [comment]
Experienced the same thing today. Site has been off for hours.

**Comment by lauriejim** [comment]
Hello @emahuni , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
