### ISSUE TITLE
Error when saving content-type: "Invalid schema edition"

### ISSUE THREAD

**Issue by vovacmig** [strapi/strapi#13667]
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.13.2
- Strapi version: 4.2.2
- Database: MariaDB 10.5.8
- Operating system: Linux 4.2.8

### Describe the bug

Invalid schema edition

### Steps to reproduce the behavior

1. Go to 'Content-Type Builder'
2. Click on 'Create a single type'
3. Filled in display name 'Page'
4. Add text field 'Title' 
5. Press save
6. See error 'Invalid schema edition'

### Expected behavior

Saving new content-Type

### Screenshots

![image](https://user-images.githubusercontent.com/11471687/176733033-efa23f37-f367-41df-833e-0cef745fdcf3.png)

**Comment by yanniskadiri** [comment]
We were not able to reproduce the bug. Could you provide more information and share your content schema?
Also, it would be great if you could share a screen recording of the bug. Thanks.

**Comment by derrickmehaffy** [comment]
As we have had no update to this and cannot reproduce I'm going to set it as closed for now.

**Comment by ryanjanelli** [comment]
I ran into this same issue. It came down a permissions error with writing/updating a file. 

Errors:
0|app  | [2022-12-08 16:42:15.735] error: Error writing schema files
0|app  | [2022-12-08 16:42:15.736] error: EACCES: permission denied, open 'this is the path of my url, removed for privacy reasons'
0|app  | Error: EACCES: permission denied, open 'this is the path of my url, removed for privacy reasons'

Changing permissions to the directory I was writing to resolved this issue and allowed me to modify content-types with new fields as needed.

**Comment by ulonix** [comment]
Can someone post what should be the proper rights of strapi folders for non-root users?

**Comment by vovacmig** [comment]
> Can someone post what should be the proper rights of strapi folders for non-root users?

In all self-respecting CMSs, these processes have long been automated and warnings about incorrect rights to folders, files, etc. are displayed in the admin panel.

**Comment by pjr94** [comment]
I think this can be triggered by adding a component in a plugin under plugin-name/components/component.json and trying to register it like this in strapi-server.js
```
  const componentToAdd = require('./components/component.json')
  if (!strapi.components) {
    strapi.components = {};
  }
  strapi.components['plugin::notifications-plugin.noticeComponent'] = componentToAdd 
    console.log('Registered components:', strapi.components)
```

**Comment by Blovario** [comment]
**I have the same issue**

I'm encountering an issue while working on a custom Strapi plugin where I register components and use them in my content types.

Here’s an example of the structure I am using:

1. **Content type in the plugin (`content-types/article/index.ts`)**:

```typescript
"use strict";

export default {
  collectionName: 'articles',
  info: {
    singularName: 'article',
    pluralName: 'articles',
    displayName: 'Articles',
  },
  options: {
    draftAndPublish: true,
  },
  attributes: {
    title: {
      type: 'string',
      required: true,
      configurable: false,
    },
    body: {
      type: 'text',
      configurable: false,
    },
    slug: {
      type: 'uid',
      targetField: 'title',
      required: true,
      configurable: false,
    },
    metadata: {
      type: 'component',
      repeatable: false,
      component: 'article.metadata',
      configurable: false,
    },
  },
};
```

2. **Component registration in the plugin (`server/register.ts`)**:

```typescript
import { Schema, Strapi } from '@strapi/strapi';

export default ({ strapi }: { strapi: Strapi }) => {
  const articleMetadata: Schema.Component = {
    collectionName: "components_article_metadata",
    category: "article",
    modelName: "metadata",
    globalId: "ComponentArticleMetadata",
    uid: "article.metadata",
    modelType: "component",
    attributes: {
      author: { type: "string" },
      publishedAt: { type: "datetime" },
      keywords: { type: "string" }
    },
    options: {},
    pluginOptions: {},
    info: {
      displayName: "Metadata",
    },
  };

  // Registering the component
  strapi.components[articleMetadata.uid] = articleMetadata;
};
```

**The issue:**

When I try to create a new content type through the Strapi admin UI, I receive the following error:

```
[2024-10-17 11:56:04.767] error: Error writing schema files
[2024-10-17 11:56:04.767] error: The "path" argument must be of type string. Received undefined
```

This problem only occurs when I include a component (like `article.metadata`) inside a content type within my plugin. If I comment out the component, I am able to create new content types without any issues.

Could this be related to how components are registered within a plugin? Is there a proper way to register components inside plugins that works smoothly with the Content-Type Builder?

Thank you in advance for your help!

**Comment by Bryelmo** [comment]
Hello everyone, 
I'm facing this issue too but only if I use my local strapi with a plugin I'm developing and implemented with Yalc.
My plugin installs its content-types and make them usable through the core content-manager plugin.

If I want to create some other content types I get this error:

`error: Error writing schema files
 error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

So, in detail Strapi creates the content type folder in /src/api path and create all the needed files except the schema.json.

Maybe someone of you has an idea for that.
Thanks in advance.
