### ISSUE TITLE
[Local][Node.js]  ECONNREFUSED ::1:1337 on local development with Axios and Nodejs app

### ISSUE THREAD

**Issue by JulienHe** [strapi/strapi#13680]
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: v4.1.12
- Database: sqlite
- Operating system: Mac OS Monterey 12.1

### Describe the bug

While I'm working on a Google Cloud Functions to manage the publication status of my content, I wanted to make it more automatic. I wrote a function that let me get all the content that have a `publicationState: PREVIEW` with a specific date, in my case today. I work with GraphQL on this project and I tried my queries on Postman to get a grasp of it. 
What I tried to achieve is to update my publications to be updated from PREVIEW to LIVE without any human interaction.  I avoid any plugin to do so as I can't run any cron on my app engine in production.

- When I run the query on Postman, I get the content I need, I have no problem. 
- When I run the `CURL` snipper from postman on my terminal, I have no problem.
- When I run the Node.js code on my production environment, I have no problem
- When I run the Node.js code on my local environment, I get an error. 

### Expected behavior

Be able to query `http://localhost:1337/graphql` on my node.js app locally.

#### Postman
![CleanShot 2022-07-04 at 08 40 50@2x](https://user-images.githubusercontent.com/718868/177157104-dc52b380-1052-4cb7-a845-9e65a3ad4a45.jpg)

#### Curl
```
curl --location --request POST 'http://localhost:1337/graphql' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"query getSnacks($date: Date) {\n    snacks(publicationState: PREVIEW, filters: { publish_at: { eq: $date } }) {\n      data {\n        id\n      }\n    }\n  }","variables":{"date":"2022-07-03"}}'
```

![CleanShot 2022-07-04 at 08 42 43@2x](https://user-images.githubusercontent.com/718868/177157379-e48ca8b3-1998-4cdb-921e-e0f6f53f346d.jpg)

#### Node.js
![CleanShot 2022-07-04 at 08 45 09@2x](https://user-images.githubusercontent.com/718868/177157743-6ff542b4-882d-4c17-9502-6d80267e325d.jpg)

https://jsonhero.io/j/5C1RgIvUu6TS

#### Function
```
'use strict';
const functions = require('@google-cloud/functions-framework');
const axios = require('axios');
require('dotenv').config()

functions.http('updatePublication', (req, res) => {
    const today = new Date();
    const dd = String(today.getDate()).padStart(2, "0");
    const mm = String(today.getMonth() + 1).padStart(2, "0"); //January is 0!
    const yyyy = today.getFullYear();
    
    const getPublication = JSON.stringify({
        query: `query getSnacks($date: Date) {
            snacks(publicationState: PREVIEW, filters: { publish_at: { eq: $date } }) {
                data {
                    id
                }
            }
        }`,
        variables: {"date":`${yyyy}-${mm}-${dd}`}
    });
    const configGetPublication = {
        method: 'post',
        url: `${process.env.GRAPHQL_API_URL}`,
        headers: { 
            'Content-Type': 'application/json'
        },
        data : getPublication
    };
    
    const sendGetRequest = async () => {
        try {
            const resp = await axios(configGetPublication);
            console.log(JSON.stringify(resp.data));
            res.send(JSON.stringify(resp.data));
        } catch (err) {
            console.error(JSON.stringify(err));
            res.send(JSON.stringify(err));
        }
    };
    
    sendGetRequest();
});
```

#### Middleware
```
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:"],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];

```

**Comment by derrickmehaffy** [comment]
This isn't really a Strapi bug the the `localhost` alias in mac isn't set properly. It's pointing to a ipv6 address and not the internal ipv4 address (127.0.0.1) and for some reason apple doesn't set `127.0.0.1` and `::1` to the same. 

Short answer is set your `host` key in the `.env` directly to 127.0.0.1

**Comment by derrickmehaffy** [comment]
I'm going to close this as it really isn't a bug on Strapi side but something that Apple recently introduced but it doesn't impact everyone so it sounds like a piece of software modifying the default hosts file.

**Comment by JulienHe** [comment]
I see. I did find a solution to workaround. I use [ngrok](https://ngrok.com/), then I was able to get/post your local Strapi.

**Comment by vrajpatel01** [comment]
open terminal and run this command
`sudo nano /etc/hosts`

than remove 
::1          localhost 
and save sile and restart your strapi server

**Comment by prodkt** [comment]
> sudo nano /etc/hosts

@vrajpatel01 Thank you sir! Worked perfect.

**Comment by pmccourt** [comment]
The issue I found was that MacOS doesn't seem to like localhost as the env for the location of the Strapi API in the frontend config. Replace localhost with 127.0.0.1 everywhere you can.

**Comment by derrickmehaffy** [comment]
> The issue I found was that MacOS doesn't seem to like localhost as the env for the location of the Strapi API in the frontend config. Replace localhost with 127.0.0.1 everywhere you can.

Good old apple adding useless changes to something that has existed for decades lol.

**Comment by kokorolx** [comment]
> open terminal and run this command `sudo nano /etc/hosts`
> 
> than remove ::1 localhost and save sile and restart your strapi server

Thank you. That saved my life
