### ISSUE TITLE
Creating many to many relationship  in content-type builder can fail based on capitalization.

### ISSUE THREAD

**Issue by omarzion** [strapi/strapi#1370]
First off I must say, I found strapi several days ago and have been loving it!

**Informations**
- **Node.js version**: v8.11.2
- **npm version**: v5.6.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: Mongo
- **Operating system**: linux

**What is the current behavior?**
creating many to many relationship  in content-type builder can fail based on capitalization.

**Steps to reproduce the problem*
in content builder
1. create type Blog Post Category (was autochanged to blogpostcategory)
2. create type Blog Post (was autochanged to blogpost)
Blog Post -> add many to many relation to Blog Post Category

**crash** and can't restart
```
error Something went wrong in the model `Blogpost` with the attribute `categories`
error Cannot read property 'attributes' of undefined
```

looking at the generated api models, I think it is a capitalization issue in the generation.

`Blogpostcategory.info.name !== BlogPost.attributes.category.collection`

and Blogpostcategory wasn't given a matching relation attribute, maybe because it crashed first?

Blogpostcategory.settings.json
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "blogpostcategory",
    "description": "Different categories for blog posts"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    }
  }
}
```
Blogpost
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "blogpost",
    "description": "A blog post"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    /* omitted irrelevant */
    "categories": {
      "collection": "blogPostCategory",
      "via": "posts",
      "dominant": true
    }
    /* omitted irrelevant */
  }
}
```

**Comment by lauriejim** [comment]
Hello @omarzion , I suggest you to use `blogpostcategory` instead of `BlogPostCategory ` for now.
We have a feature request related to your issue here https://github.com/strapi/strapi/issues/661

**Comment by derrickmehaffy** [comment]
Aye yeah @Aurelsicoko I spoke about this, I believe it is planned to change just not sure when @omarzion its an issue that affects other things like the AdminUI ect. The same applies to plural stuff as well.

**Comment by omarzion** [comment]
@lauriejim thanks, I corrected the issue before posting the issue.

Is this currently being worked on?  I've not done a lot of open source work but I would like to help out with strapi.  Maybe I can look into it this evening

Are the plans to move towards camel case, or to move towards lower case with nice formatting for the labels in the admin?

I think #661 #1055  and #1370 could all be handled together

What are your preferences on the matter?

**Comment by lauriejim** [comment]
Hi @omarzion . Actually it's not a priority for us. This feature need a lot of updates and I really think it's not a good first issue. Many core feature of Strapi have to be updated and I prefer to the core team work on.

**Comment by lauriejim** [comment]
It has been fixed. Not present in last version of Strapi

**Comment by omarzion** [comment]
It's sounds like when you changed the name it can no longer find the model project type, make sure your project type model has the same spelling and capitalization as well since you've changed it in project

**Comment by lauriejim** [comment]
@dblinov If you manually update your content type name, you will have to manually update all other models that refers to it.
