### ISSUE TITLE
Titles too long do not render properly in content manager

### ISSUE THREAD

**Issue by vcque** [strapi/strapi#13719]
### Required System information

- Strapi version: 4.2.0

### Describe the bug

When titles are longer than 300px, the title is truncated and cannot be seen in full, in the content manager's collection table and relation widgets.

It is especially detrimental when titles use prefixes in them that are longer than 50 chars. (which is a case we encountered recently here...)

### Steps to reproduce the behavior

1. Create an entity with a title of more than 50 characters
2. Go to the corresponding collection table or a relation linking to this entity
3. Check that the title is truncated

### Expected behavior

There should be a way to see the full text of the truncated field.

I think adding tooltips in each case could be sufficient.

### Screenshots

Table case :
![image](https://user-images.githubusercontent.com/2727161/177820724-f5489651-3c0d-4f0a-a789-d654d989f2b3.png)

Relation case : 
![image](https://user-images.githubusercontent.com/2727161/177820869-7cf7eb9e-75d8-45a6-8809-de7b4efa7057.png)

**Comment by derrickmehaffy** [comment]
This should already be the case, if you hover over the title it will show the full one. Can you confirm or did you have some other idea in mind?

**Comment by vcque** [comment]
Hi Derrick, thank you for responding,

I tried with different browsers (Chrome / Firefox / Safari) with strapi version 4.2.3 and there is no tooltip on hover. Maybe a regression ?
