### ISSUE TITLE
Plugin development Setup stuck in starting the server in the admin folder

### ISSUE THREAD

**Issue by YiteLMG** [strapi/strapi#1371]
**Informations**
- **Node.js version**: 9.8.0
- **npm version**: 5.8.0
- **Strapi version**: v3.0.0-alpha.12.3
- **Database**: Mongo v3.6.3
- **Operating system**: Windows 10 Subsystem for Linux - Ubuntu 16.04 and Ubuntu 16.04

**What is the current behavior?**
Plugin development Setup with v3.0.0-alpha.12.3

Stuck in Start the server in the admin folder 
`cd pathToMyProject/myDevelopmentProject/admin && npm start`

![cap](https://user-images.githubusercontent.com/39724917/41332772-cd3bcb20-6f11-11e8-9a8b-bb494f4cd805.PNG)

**Steps to reproduce the problem**
1. Clone it to your computer `git clone git@github.com:strapi/strapi.git`.
2. Run `npm run` setup at the root of the directory.
3. Create a new project `strapi new myDevelopmentProject --dev`.
4. Remove plugins/analytics `rm -rf myDevelopmentProject/plugins/analytics `
5. Create plugin `cd myDevelopmentProject && strapi generate:plugin my-plugin`
6. Link the strapi-helper-plugin dependency in your project folder `cd pathToMyProject/myDevelopmentProject/plugins/my-plugin && npm link strapi-helper-plugin.`
7. Start the server in the admin folder cd pathToMyProject/myDevelopmentProject/admin && npm start and go to the following url http://localhost:4000/admin.

**What is the expected behavior?**
v3.0.0-alpha.12.2 is fine

**Suggested solutions**

**Comment by soupette** [comment]
@YiteLMG I'm facing the same bug, until I fix it, you can press `cmd + c` one time and it will start your server

**Comment by puntonero** [comment]
Same problem in my ubuntu box, but CTRL + C simply kicks me back to the command prompt
