### ISSUE TITLE
Table head background is white when previewing a rich text field in dark mode

### ISSUE THREAD

**Issue by knightjdr** [strapi/strapi#13736]
### Required System information

- Node.js version: 16.6.2
- NPM version: 7.20.2
- Strapi version: 4.2.2
- Database: SQLlite 3
- Operating system: Linux Mint

### Describe the bug

If you create a table in a rich text field and then click on `Preview mode`, the table head has a white font with a light background when dark theme is enabled, making the text very hard to read.

### Steps to reproduce the behavior

1. Enable dark mode on user profile
2. Create a new content entry that has a rich text field
3. Create a table in markdown
4. Click on `Preview mode`

### Expected behavior

The table head should be dark to match the theme.

### Screenshots

![markdown](https://user-images.githubusercontent.com/6589097/178113059-e5b1c4d9-e340-4bbd-92ee-ac708632a326.png)
![preview](https://user-images.githubusercontent.com/6589097/178113060-8babc32f-33aa-4735-b76d-e40a18a66396.png)

**Comment by derrickmehaffy** [comment]
Confirmed on v4.2.2

![image](https://user-images.githubusercontent.com/8593673/178336346-3b81bfe0-ab9d-4dff-8bb6-d7260e4f107b.png)
