### ISSUE TITLE
Default values for fields are not set and they get published when added to existing content-types.

### ISSUE THREAD

**Issue by WiktorG** [strapi/strapi#13731]
### Required System information

- Node.js version: 16.3.0
- NPM version: 7.15.1
- Strapi version: 4.1.12
- Database: PostgreSQL
- Operating system: Intel Mac OS 12.4 Monterrey 

### Describe the bug

Hi! We're trying to enhance our single-type with new fields. I added necessary fields to our Single Type, marked them as required (in my case boolean and single component) and set default values for both of them (tab advanced in field configuration).

I set _**false**_ for the boolean and I expected the component to already be there without the need to click the button and create it manually since I marked it as required.

Single Type was already published, so they appeared in it's view. 
I triggered build for our frontend application and got error that aforementioned fields are non-nullable. 
We use Strapi's Graphql API.

When I went to the Single Type editor and manually filled required fields - build was successful.
Without filling them I couldn't save changes, but that behavior is expected.

I think if fields have default values they should be there from the beginning 😁

### Steps to reproduce the behavior

1. Create new Single Type
2. Add some fields (not required)
3. Fill the fields and publish the Single Type
4. Edit the Single Type model (add fields that are marked as required with default values - Boolean is the best example)
5. If you go to playground and try to query for the field you created - it should be available in the Schema, but will throw an error

### Expected behavior

Default values are set initially and schema works without errors 

### Screenshots

<img width="816" alt="Zrzut ekranu 2022-07-8 o 13 46 39" src="https://user-images.githubusercontent.com/23586708/177986219-bcb70808-2e90-4aa4-a659-89ee5c2d56a7.png">

<img width="1305" alt="Zrzut ekranu 2022-07-8 o 13 46 12" src="https://user-images.githubusercontent.com/23586708/177986170-dd86a906-98e2-40c0-b684-e876561a58ce.png">

<img width="1444" alt="Zrzut ekranu 2022-07-8 o 13 47 29" src="https://user-images.githubusercontent.com/23586708/177986315-115cf687-84dd-43f0-ba94-b217d435fd77.png">

**Comment by derrickmehaffy** [comment]
I don't believe this is functionally possible right now as it would mean we would also need to set relations as required (which isn't possible): https://feedback.strapi.io/customization/p/specify-relation-column-as-required / https://github.com/strapi/strapi/issues/557

Components are functionally just relations, if you create the component entity then of course the "required" takes effect but just like if you used a oneToOne relation or oneToMany relation setting something required on the related component wouldn't mean that you need to create that entity (since the relation isn't required).

**Comment by derrickmehaffy** [comment]
I'm going to raise the question internally but I have a feeling this is gonna be a feature request and should be moved over to our feedback/feature request database

**Comment by danielbeardsley** [comment]
This just bit us (at ifixit.com) as well. We added a new boolean field with a default of "false" and then all our graphQL queries were coming back effectively empty (though with 200 status codes) and stack trace in an error:
```
"extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field ProductList.testBoolean.",
            "    at completeValue (/Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/graphql/execution/execute.js:559:13)",
            "    at /Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/graphql/execution/execute.js:469:16",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
            "    at async Promise.all (index 7)",
            "    at async Promise.all (index 1)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)",
            "    at async execute (/Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/requestPipeline.js:205:20)",
            "    at async processGraphQLRequest (/Users/federicobadini/Documents/Projects/react-commerce/backend/node_modules/apollo-server-koa/node_modules/apollo-server-core/dist/requestPipeline.js:148:28)"
          ]
        }
      }
```

**Comment by derrickmehaffy** [comment]
> This just bit us (at ifixit.com) as well. We added a new boolean field with a default of "false" and then all our graphQL queries were coming back effectively empty (though with 200 status codes) and stack trace in an error:

Very cool to see ifixit using Strapi (love you guys and gals <3)

Can you confirm which Strapi version you are on?

**Comment by derrickmehaffy** [comment]
Scratch that, I see your source is public: https://github.com/iFixit/react-commerce/blob/main/backend/package.json

Can you try jumping up to 4.4.7 and see if that helps?

**Comment by federicobadini** [comment]
> Can you try jumping up to 4.4.7 and see if that helps?

Just a quick feedback to confirm that v4.4.7 still has the issue

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/customization/p/default-values-for-fields-are-not-set-and-they-get-published-when-added-to-exist

Thanks!

**Comment by danielbeardsley** [comment]
I think the described issue doesn't seem to capture the alarming bug have run into. Adding a new required boolean field (with a default field) resulted in all graphQL queries returning a 200 with a stack trace as a response.
