### ISSUE TITLE
[admin] error after saving edit view layout in content type manager

### ISSUE THREAD

**Issue by lkho** [strapi/strapi#13755]
### Required System information

- Node.js version: 16
- NPM version: 8.3.0
- Strapi version: 4.3.0-beta.1
- Database: mysql
- Operating system: Mac

### Describe the bug

error popup after saving edit view layout in content type manager, if the corresponding content type has a component added to the list view columns.

### Steps to reproduce the behavior

1. create a component type X
2. create a collection type Y
3. add the component X into Y
4. configure the list view of Y, add the component X to the columns list and save.
5. configure the Edit view of Y, make any kind of changes, and save.
6. error popup and the dialog stay there
7. refresh the page, the changes are actually _saved successfully_, and the editor can also load successfully.

### Expected behavior

no error popup

### Screenshots

<details>

![Screenshot 2022-07-13 at 12 29 22 PM](https://user-images.githubusercontent.com/7780243/178651123-b72b9fbf-613c-417c-a63b-431d5115066d.png)

![Screenshot 2022-07-13 at 12 31 10 PM](https://user-images.githubusercontent.com/7780243/178651137-902af2d7-83a0-4e1f-8c24-7301f80fe6f0.png)

</details>

### Code snippets

`formatLayouts(...)` is hard coded with `components: {}`

https://github.com/strapi/strapi/blob/42aba356ad1b0751584d3b375e83baa4a2c18f65/packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/index.js#L70-L78

and inside the routines of `formatLayouts` the components are not found.

https://github.com/strapi/strapi/blob/42aba356ad1b0751584d3b375e83baa4a2c18f65/packages/core/admin/admin/src/content-manager/hooks/useFetchContentTypeLayout/utils/formatLayouts.js#L167-L170

### Additional context

maybe the edit view layout does not need to format the list view components?

**Comment by RomanLubushkin** [comment]
Faced it as well, really annoying one

**Comment by alexmittsel** [comment]
Please fix it. Thx!

**Comment by gu-stav** [comment]
I believe this issue is fixed in the latest `4.2.3` release in https://github.com/strapi/strapi/pull/13676 and therefore I'll close the issue. If you believe this is a mistake and it does not work, please feel to ping me and I'll re-open.
