### ISSUE TITLE
Strapi install does not allow anything other than 14.19-14.20, i.e. no 16.x

### ISSUE THREAD

**Issue by onexdata** [strapi/strapi#13750]
### Describe the bug

When installing Strapi with Node version 16, I get... 

Error while installing dependencies:
error general@0.1.0: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <=14.x.x". Got "16.13.0"

When installing Strapi with Node version 14, I get...

error @strapi/strapi@4.2.2: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=16.x.x". Got "14.17.6"

This means I can only install with 4 very specific releases.

### Steps to reproduce the behavior

Just run the ```npx create-strapi-app@latest my-project``` command on your home page with any node version other than 14.19.1, .2, .3 or 14.20.0

### Expected behavior

Node compatibility described.

**Comment by enBonnet** [comment]
Did you try with `14.19.1`? It should work.

**Comment by derrickmehaffy** [comment]
Your node v14 is too old, we allow anything greater than that v14 release in the error message.

Can't reproduce the issue with v16 at all.
