### ISSUE TITLE
[Bug/ Improvement]: Add a confirmation popup after clicking on dynamic Zone's component

### ISSUE THREAD

**Issue by Charlesdoiron** [strapi/strapi#13756]
Add a deletion confirmation popup after clicking on the trash.
Indeed the trash is very close to the arrows and a costly error quickly arrived.

<img width="902" alt="Capture d’écran 2022-07-13 à 09 31 23" src="https://user-images.githubusercontent.com/4417717/178677117-7549d5d9-a34d-467f-a35f-33d0403c45ea.png">

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Comment by gu-stav** [comment]
@derrickmehaffy I'd like to keep this one open for a couple of days, so that we can discuss it with @maevalienard if you don't mind. I believe this is too small for a feature request and has a valid point. I promise I'll take care to close the issue again, if we don't agree on something in the squad here.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I'd like to keep this one open for a couple of days, so that we can discuss it with @maevalienard if you don't mind. I believe this is too small for a feature request and has a valid point. I promise I'll take care to close the issue again, if we don't agree on something in the squad here.

That's fine, I'll set it as an enhancement then.

**Comment by yanniskadiri** [comment]
Thanks for highlighting this issue.

Adding a deletion confirmation popup means you would have to confirm the deletion in the popup, and then save the entry to take this deletion into account. It might create some misunderstanding for the user, so we won't implement it.

That being said, we'll dedicate some time at some point to bring a solution to this issue. I'll close it for now as this is more of an enhancement.
