### ISSUE TITLE
[Bug Report]using JWT authenticate user not store a field which has relation with users-permission content type.

### ISSUE THREAD

**Issue by Paiman-Rasoli** [strapi/strapi#13753]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.2.3
- Database: Postgres
- Operating system: Windows 10

### Describe the bug
Hi, I have a table that has a relation with users permission content type, when using user's JWT token (which gives when user log in) all data save except user_id but when I create a token with full_access from the Strapi admin panel at that time all data stored in the table,
### Steps to reproduce the behavior
Postman Body and headers:(use JWTwhich retrieved through Strapi login route ).
![image](https://user-images.githubusercontent.com/83835010/178603089-982e9a7d-a796-4dd5-b4be-16408dc13037.png)
![image](https://user-images.githubusercontent.com/83835010/178603152-05148bbf-24ce-49d8-963b-52590ee9b7ba.png);

after sending the request all data stored except **user_id**.
Applicant-info table (user_id which has relation with users permission):

![image](https://user-images.githubusercontent.com/83835010/178602544-4bb56fd8-116b-4ced-89d7-0bab0dfec023.png)

But when I use the token from admin panel with full access at that time user_id store and also return the result in response.

![image](https://user-images.githubusercontent.com/83835010/178603766-9d6e69a4-cf06-4e64-82e0-6dcc995008cd.png)

![image](https://user-images.githubusercontent.com/83835010/178603859-a56ebde5-156c-4006-8d7c-c1a64278d062.png)

### What I expect.
like the previous version, each authenticated user could create data with his own JWT token but now I should just use one static token which is not safe.

Hint: I have also send the request through my Next.js app all data were saved except user_id.

Thanks in advance

**Comment by ziayamin** [comment]
I have the same issue.

**Comment by SayedHassan-Hussaini** [comment]
I faced the same problem, Any solution.

**Comment by Paiman-Rasoli** [comment]
When using graphql mutation it saves the data except for user_id and also in response it gives **Forbidden access** error.
```javascript
const createApplicantInfo = async (payload) => {
  console.log("T ", API, " payload", payload);
  const httpLink = createHttpLink({ uri: API });
  const authLink = setContext((_, { headers }) => {
    return {
      headers: {
        ...headers,
        authorization: `Bearer ${payload?.token}`,
      },
    };
  });

  const client = new ApolloClient({
    cache: new InMemoryCache(),
    defaultOptions: {
      mutate: {
        fetchPolicy: "no-cache",
      },
    },
    link: authLink.concat(httpLink),
    ssrMode: true,
  });
  try {
    const { data } = await client.mutate({
      mutation: gql`
      mutation {
        createApplicantsInfo(
          data: {
            year_graduation: ${Number(payload?.q1)},
            user_id: ${Number(payload?.id)},
            publishedAt: "2022-06-23T03:09:37.807Z"
          }
        ) {
          data {
            id
            attributes {
              year_graduation
              user_id {
                data {
                  id
                }
              }
            }
          }
        }
      }
    `,
    });
    return data;
  } catch (err) {
    const [x] = err.graphQLErrors;
    console.error("GLP😀", x);
    return null;
  }
};
```
The response which I give in console.
```javascript
GLP😀 {
  message: 'Forbidden access',
  extensions: {
    error: {
      name: 'ForbiddenError',
      message: 'Forbidden access',
      details: {}
    },
    code: 'FORBIDDEN'
  }
}
```
But I see one row store in the table which has year_graduation store but user_id not stored.
**Hint:**: in local it is working however my Strapi deployed to Heroku at that time user_id not storing.
![image](https://user-images.githubusercontent.com/83835010/178731256-10b0041e-9ba5-49ab-a0b3-988628b2d095.png)

**Comment by Paiman-Rasoli** [comment]
I have update Strapi version to 4.2.3 and still when I use user JWT (retrived when using **api/auth/loca**l route) one field which has relation with user-permission not store.
Table Notes:

![image](https://user-images.githubusercontent.com/83835010/178796557-436af9a6-2340-4076-9f2d-a597f5ebd857.png)

Authenticated User:

![image](https://user-images.githubusercontent.com/83835010/178796870-21639fe6-b141-4057-8d57-ae6414f1f083.png)

Request Body and Bareare Token which gained through Strapi login route

![image](https://user-images.githubusercontent.com/83835010/178797071-15b9e305-418c-46fe-9bdc-c6aff3e5b87c.png)

![image](https://user-images.githubusercontent.com/83835010/178797121-dc2a94bb-5f6d-43d7-9b44-203db5e72deb.png)

What I expect:
![image](https://user-images.githubusercontent.com/83835010/178797279-a3c12519-f5e0-4ffd-8d54-7e3fd84d80c0.png)

When using GraphQ in response return forbidden but create a row in table without having user_id.

**Comment by derrickmehaffy** [comment]
You need to enable the `find` permission of the related content-type.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12238

**Comment by Paiman-Rasoli** [comment]
> You need to enable the `find` permission of the related content-type.

Thank You for your help. now it is working but if it throws error like method is not support I could easily find the solution again Thank You.

**Comment by derrickmehaffy** [comment]
No problem!
