### ISSUE TITLE
Improve GraphQL handling of content-type attribute names

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#13761]
## Bug report

In https://github.com/strapi/strapi/pull/13717 @petersg83 and I discovered that currently attribute names of content-types are not handled consistently, which coud lead mostly to problems when using GrahpQL.

GraphQL brings some challenges, because all names/ enum values ... must match the following regex: https://spec.graphql.org/June2018/#sec-Names. In the REST API or the internal Content-API we currently don't need and don't enforce these constraints. Therefore attribute names such as "`--1`", "`$`" are valid. As soon as a user would install the GraphQL plugin, the plugin would throw an error, because these names can not be used in the GraphQL schema.

I believe this is not an easy fix and requires some discussion and might therefore be material for strapi@v5, but I wanted to open the issue anyways so that we do not forget about it.

### Frontend

Validation of fieldnames is scuttered and handled in different places. The regex mentioned in the GraphQL spec is defined many times and contains different variations.

Strapi should make sure we are exporting a shared regex from somewhere and validate all names against it, if we define the regex as baseline for attribute names.

### Backend

Currently users could change the names of attributes in the schema files. During bootstrap they are validated, but not checked against the GraphQL spec regex. Therefore a user could name an attribute "`$`" and it would work. As soon as they would install the GraphQL plugin, they will see an error during the bootstrap process.

Strapi should ensure we are exporting and validating the regex from a central place and validate all schema attribute names against if, if we define the regex as baseline.

### Required System information

- Node.js version: not applicable
- NPM version: not applicable
- Strapi version: 4.x
- Database: not applicable
- Operating system: not applicable

### Expected behavior

I expect my attribute names to work with and without GraphQL. In order to achieve this I think we'd have several options:

#### Option 1: Make the GraphQL name regex the baseline

GraphQL has the most strict rules that we would need to apply to names. Therefore the regex could act as baseline. However, this doesn't come without challenges on  the users side: in my opinion it is hard to explain what is actually allowed. For example: an attribute name can not start with a number nor contain non-alphanumerical characters. This might be limiting for users when they want to describe their content-model.

#### Option 2: Use regressed attribute names in GraphQL

Similar to enumeration values, the GraphQL plugin could make sure it accepts all attribute names, but runs some normalization on them, to make them compatible with the GraphQL spec. This does not require any changes on the user/ schema side, but might be brittle, because an attribute such as "--1" or "0815" can not be automatically regressed into a valid value.

#### Option 3: Allow users to define seperate GraphQL attribute names

Similar to handling singular/ plural values, we could offer the ability to users to overwrite the attribute name in GraphQL. This would bring a lot of flexibility (because a schema doesn't need to be changed if it contains invalid attribute names, once the GraphQL plugin was installed), but moves the burden onto the user.

### Screenshots

Not applicable.

#### Related issues

- https://github.com/strapi/strapi/issues/13017
- https://github.com/strapi/strapi/issues/13766

**Comment by derrickmehaffy** [comment]
I agree with @petersg83 here, we originally had this plan but it was cut due to time. It might be good to revisit that and actually implement it. AFAIK @maevalienard already has the design mostly finished.

Realistically enum's actual values should be limited to the same regex that GraphQL uses in my opinion but we could easily add labels on top of these values. (maybe even a way to fetch those labels on the frontend side so users don't have to hardcode them in their frontends?)

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/improve-graphql-handling-of-content-type-attribute-names

Thanks!
