### ISSUE TITLE
Upload failed not displaying custom error message on Media UI

### ISSUE THREAD

**Issue by gowthamik14** [strapi/strapi#13767]
I have implemented plugin (Upload) extension to stop uploading few file types. 
After extension Plugin admin-api controller returns 400 bad request with custom error message that only certain file types are allowed.

I can see in the network tab the api is returning error object with error message

![image](https://user-images.githubusercontent.com/62015937/178775813-7744cad7-e658-44bb-9e9b-465107755441.png)

It is displaying on UI the uncaught axios error message.  

![image](https://user-images.githubusercontent.com/62015937/178776217-1353a5c6-30d3-42f2-899a-a07f11f00283.png)

It would be good to display the error message sent from the backend.

Strapi Version : Latest

**Comment by derrickmehaffy** [comment]
@gowthamik14 I'd be interested in your implementation and seeing if we could possibly add it into the core. Would you be willing to share?
