### ISSUE TITLE
Custom auth provider

### ISSUE THREAD

**Issue by JejomStark** [strapi/strapi#13773]
## Bug report
Bug in strapi on custom auth provider

### Required System information

- Node.js version: 14.19.3
- NPM version:6.14.17
- Strapi version: 4.2.0
- Database: sqlite
- Operating system: ubuntu

### Describe the bug

I created a custom auth provider.
like email, it is really basic : 

`custom: {
    enabled: true,
    icon: 'enveloppe',
 }`

But on the interface, there are yet, the other attributes. (Client ID,Client Secret, The redirect URL...)

I updated the getProviders function, to do the same action as "email"

`users-permissions/controllers/settings.js

......
// line 64
 if (provider !== 'email' && provider !== 'custom') {
.....`

But the problem seem to be in the frontend.

### Steps to reproduce the behavior

1. Create a custom auth provider
2. Go to admin panel, in settings -> providers
3. Click on your provider

### Expected behavior

consider attributes of custom provider, if no redirect url is needed don't show the form element.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by JejomStark** [comment]
Before the last version of strapi my custom provider dridn't have these new attributes, now it does so I think this is a bug.
Like before consider attributes of custom provider, if no redirect url is needed don't show the form element.
