### ISSUE TITLE
Issue starting server after installing GraphQL with oneWay relations in a model

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1377]
**Informations**
- **Node.js version**: v10.4.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: 10.1.29-MariaDB
- **Operating system**: Linux Mint 19 Beta (Ubuntu 18.04)

**What is the current behavior?**

If you have a model with a oneway relation and you install the graphQL plugin, the server will fail to start

**Steps to reproduce the problem**

install the GraphQL plugin and create some models that contain `oneWay` relations, the server will fail to start pointing towards graphql (likely because there is no defined option in graphQL to grab the oneway type)

**What is the expected behavior?**

GraphQL should also handle oneway relations

**Suggested solutions**

Modify and add a case in GraphQL for oneWay relations

**Comment by derrickmehaffy** [comment]
note removing graphql plugin allows the server to start just fine.

**Comment by derrickmehaffy** [comment]
@lauriejim Breaking issue with 12.3 on graphQL if you are using oneWay relations.

**Comment by johannpinson** [comment]
@derrickmehaffy can you test with the new 3.0.0-alpha.12.4, it looks to working well for me

**Comment by lauriejim** [comment]
Same as @johannpinson . It works great with `alpha.12.4`

**Comment by derrickmehaffy** [comment]
Yes @lauriejim no issues with 12.4
