### ISSUE TITLE
Upload config not recognizing new breakpoints

### ISSUE THREAD

**Issue by julianadormon** [strapi/strapi#13798]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 3.6.8
- Database:  n/a
- Operating system: windows 10

### Describe the bug

Modifying the upload config breakpoints does nothing.

### Steps to reproduce the behavior

1. Create new strapi project
2. Create plugins.js in cms/strapi/config
3. Add new breakpoints config settings
4. Wait for restart
5. Navigate to strapi admin and go to Media plugin and upload new image
6. Add image to a strapi "page"
7. View page - console.log image.formats

### Expected behavior

Expect to see a sizes attribute with max-width sizes that correspond to the new breakpoints
But all I see are the defaults

### Screenshots

![image](https://user-images.githubusercontent.com/89358714/179623085-9b92d9ac-2986-4be5-98d0-319f69b94ac1.png)
![image](https://user-images.githubusercontent.com/89358714/179623158-7519c033-3133-4c6e-8934-7bf88f735ecb.png)
![image](https://user-images.githubusercontent.com/89358714/179623208-997fb995-5dad-410b-a9ac-b2b78825ac82.png)
![image](https://user-images.githubusercontent.com/89358714/179623255-f972e0ae-7812-4fc7-a88c-fc18822915f7.png)
![image](https://user-images.githubusercontent.com/89358714/179623317-ed8382c2-aa16-4308-bc1f-06dcf6f79852.png)

The last image shows the output.
A. Notice how there are only 4 items when the config now has 5.
B. My breakpoints show 499px for the small size, yet the out put shows the default of width: 500.

### Code snippets
`module.exports = ({ env }) => ({
    upload: {
      config: {        
        breakpoints: {
          xlarge: 1919,
          large: 999,
          medium: 749,
          small: 499,
          xsmall: 60
        },
        providerOptions: {
            localServer: {
              maxage: 30000000
            },
          },
      },
    },
  });`

If applicable, add code samples to help explain your problem.

**Comment by edgarnet** [comment]
This might be a problem with the `plugins.js` config as a whole. I've been trying to setup the GraphQL plugin with `tracing`, but the playground doesn't update after re-building Strapi.

**Comment by edgarnet** [comment]
The `plugins.js` config is **working** after changing some other options. This required changes to the `middlewares.js` config, inspired by another [comment](https://github.com/strapi/strapi/issues/11637#issuecomment-977244572), to get the playground to load properly. The `tracing` feature once offered by Apollo Server is actually [deprecated](https://github.com/apollographql/apollo-tracing) and requires another solution for telemetry.

**Comment by julianadormon** [comment]
@edgarnet thanks. What were the "other" changes you made to the plugins.js file to get it working?

**Comment by edgarnet** [comment]
@julianadormon I changed the graphql `endpoint` which updated as expected. Did you run `strapi build` before running the server again? There might be a build cache that's favoring the default config.

**Comment by julianadormon** [comment]
@edgarnet Thank you! I will try that. For the time being, I solved my problem by overwriting the default values in the strapi/node_modules/strapi-plugin-upload/services/image-manipulation.js file

**Comment by julianadormon** [comment]
@edgarnet I am running locally so I ran npm run strapi develop after reverting and unfortunately, only the defaults are showing again. Thanks again.

**Comment by julianadormon** [comment]
Seems like on ongoing problem that has not been addressed:
https://forum.strapi.io/t/how-to-resize-uploaded-images-to-custom-sizes/4064/8
and:
https://forum.strapi.io/t/how-do-i-create-thumbnails/956

**Comment by julianadormon** [comment]
and:
https://www.reddit.com/r/Strapi/comments/gipli9/strapipluginupload_breakpoint_sizes/

**Comment by edgarnet** [comment]
>I ran npm run strapi develop after reverting and unfortunately, only the defaults are showing again.

Did you do `npm run strapi build` **before** running develop?

**Comment by julianadormon** [comment]
Thank you @edgarnet. I actually built the project on a test server after the fact and got the same results. I found other people with the same issue and posted links above. It may be that this issue was never resolved. Most arrived at the same "fix" I did which was to modify the file in node_modules (ugg). Thanks again for looking out :)

**Comment by johndoudou** [comment]
I can confirm the only "fix" that is working on my end is to modify node_modules.
I tried to change `config/plugins.js` and run `strapi build`, and this had no effect whatsoever.

**Comment by johndoudou** [comment]
Oh actually, i found the problem : documentation isn't right.
plugins.js code should be : 

```
module.exports = ({env}) => ({
    upload: {
        config: {
            breakpoints: {
                xlarge: 1920,
                large: 1000,
                medium: 750,
                small: 500
            }
        },
    }
})
```

**Comment by gu-stav** [comment]
@johndoudou Glad you found the issue. Would you like to open a PR in [strapi/documentation](https://github.com/strapi/documentation/)?

CC @pwizla

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports for v3 unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You

**Comment by derrickmehaffy** [comment]
(Please feel free to continue the discussion even though this is closed but at this point in time we are not troubleshooting or fixing v3 bugs)
