### ISSUE TITLE
Nodemailer configuration

### ISSUE THREAD

**Issue by iwoogy** [strapi/strapi#13796]
### Required System information

- Node.js version: v14.17.1
- NPM version: 6.14.15
- Strapi version: 4.2.3
- Database: sqlite
- Operating system: OS X 12.4

### Describe the bug

I'm quite new to Strapi. I tried to configure nodemailer to send email via smtp.

### Steps to reproduce the behavior

1. Install nodemailer provider [Doc](https://github.com/strapi/strapi/tree/master/packages/providers/email-nodemailer) 
`npm install @strapi/provider-email-nodemailer --save`

2. Configure the plugin.js for local development

<img width="475" alt="CleanShot 2565-07-18 at 19 15 30@2x" src="https://user-images.githubusercontent.com/479162/179509165-86d4e180-ea1c-4bf5-ae56-701ab08f0eaa.png">

3. Start MailDev via Docker

`docker run -p 1080:1080 -p 1025:1025 maildev/maildev`

<img width="637" alt="CleanShot 2565-07-18 at 19 02 54@2x" src="https://user-images.githubusercontent.com/479162/179509269-6bfb17b5-c123-41f4-a74b-20da654ea683.png">

<img width="1171" alt="CleanShot 2565-07-18 at 19 01 25@2x" src="https://user-images.githubusercontent.com/479162/179509650-e1f943a8-463c-4cf4-8fe2-ed296a2adfe6.png">

4. Test email delivery

![CleanShot 2565-07-18 at 19 00 58@2x](https://user-images.githubusercontent.com/479162/179509342-2fd1bd25-1473-4ce9-8328-dd7646ad9c38.png)

5. Error in the console

<img width="1270" alt="CleanShot 2565-07-18 at 19 07 22@2x" src="https://user-images.githubusercontent.com/479162/179509405-439b00ae-f6db-4252-a86e-9153f1ca0832.png">

```bash
error: Couldn't send test email: can not connect to any SMTP server.
Error: Couldn't send test email: can not connect to any SMTP server.
```

### Expected behavior

Sending a test email successfully.

### Additional context

Github repo for reproduction.
https://github.com/iwoogy/StrapiNodeMailerDev

**Comment by derrickmehaffy** [comment]
Cannot reproduce on an actual in production smtp server, this is likely not a big with Strapi but an environmental issue.

Marking issue as closed, please take any help question to our community sources:

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by iwoogy** [comment]
I actually have the same problem with production smtp server.

I follow the same tutorial and add the credentials from SendInBlue.

I got exactly the same error in development environment.
