### ISSUE TITLE
Strapi admin panel not working in production

### ISSUE THREAD

**Issue by zettabyte918** [strapi/strapi#13805]
### Required System information

- Node.js version: v16.14.0
- NPM version: v8.3.1
- Strapi version: v4.2.3
- Database: better-sqlite3
- Operating system: Ubuntu 20.04.3 LTS

### Describe the bug

i install a fresh strapi application v4.2.3 in my development environment (localhost:1337) the admin panel working fine everything works as it should.
but whene i run it in production environment (**vps Ubuntu 20.04.3 LTS with nginx as reverse proxy** ) the api works but the admin panel not working and there an error in the browser console
```
Uncaught SyntaxError: identifier starts immediately after numeric literal
```

### Steps to reproduce the behavior

1. Go to [https://api.les-experts.tn/admin](url)
2. open console in the browser
3. See error

### Expected behavior

The admin panel should work in the prodcution environment

### Screenshots

![image](https://user-images.githubusercontent.com/18426424/179780169-8d60153d-72b3-4a2e-8818-60bed3d87b0c.png)

### Code snippets
In my production i build strapi and i run it with this to command and pm2
#### **`package.json`**
```json
"build-prod": "NODE_ENV=production strapi build",
"start-prod": "NODE_ENV=production strapi start"
```
#### **`config/env/production/admin.js`**
```js
module.exports = ({ env }) => ({
  auth: {
    secret: env("ADMIN_JWT_SECRET", "xxxxxxxxxxxxxxxxxxxxxxxx"),
  },
  apiToken: {
    salt: env("API_TOKEN_SALT"),
  },
  serveAdminPanel: env.bool("SERVER_ADMIN_PANEL", false),
});
```
#### **`config/env/production/server.js`**
```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('PUBLIC_URL','localhost'),
  app: {
    keys: env.array("APP_KEYS"),
  },
});
```
#### **`.env`**
```env
HOST=0.0.0.0
PORT=1337
SERVER_ADMIN_PANEL=true
PUBLIC_URL=https://api.les-experts.tn
APP_KEYS=xxxxxxxxxxxxxxxxxxxxxxx
API_TOKEN_SALT=xxxxxxxxxxxxxxxx
ADMIN_JWT_SECRET=xxxxxxxxxxxx
JWT_SECRET=xxxxxxxxxxxxxxxxxxx
```
#### **`nginx config file`**
```js
#strapi api
server {
    # Listen HTTP
    listen 80;
    server_name api.les-experts.tn;

    # Proxy Config
    location / {
        proxy_pass http://localhost:1337;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }
}
```

### Additional context

i face this problem only in strapi 4.2.3 but with 4.0.5 the admin panel working as it should be

**Comment by derrickmehaffy** [comment]
> serveAdminPanel: env.bool("SERVER_ADMIN_PANEL", false),

You aren't serving the admin panel and the Nginx config is not setup to serve static files from the build (this is a different method of using Nginx than normal).

Either way this isn't a bug, it's a configuration issue. Please use our community platforms for questions like these.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by zettabyte918** [comment]
if anyone have the same problem actually it was cloudflare issues that purging my admin js file and it somehow edited the code or idk anyway you need to add page rule to bypass cloudlfare purge cache 
1) Go to page rule
2) In the dropdown select "cache level" then select "bypass" 
3) In the url put your admin strapi url in the end of the url add asterisk (*) https://api.example.com/*

**Comment by sh13n** [comment]
> if anyone have the same problem actually it was cloudflare issues that purging my admin js file and it somehow edited the code or idk anyway you need to add page rule to bypass cloudlfare purge cache
> 
> 1. Go to page rule
> 2. In the dropdown select "cache level" then select "bypass"
> 3. In the url put your admin strapi url in the end of the url add asterisk (*) https://api.example.com/*

Instead cache level (step 2), you can try to disable Rocket Loader, it works in my case.
