### ISSUE TITLE
Eslint config is broken

### ISSUE THREAD

**Issue by jonathan-baernthaler** [strapi/strapi#13802]
## Bug report

while working on a plugin project I figured that eslint did not work, because the parser is outdated. After some exploration I found a solution and want to report it here, so that the solution is documented, if someone else runs into the same issue. 

### How to reproduce 

1. create a new strapi app with npx create-strapi-app@latest my-project --quickstart (this will at the time being create a new strapi app with version 4.2.3)

2. generate a new strapi plugin with yarn strapi generate 

3. add eslint and babel-eslint as dev-dependency to the project (babel-eslint is the current parser defined in the eslintrc)

4. add lint scripts to the package.json:  
    "lint": "eslint --ext .js src",
    "lint:fix": "eslint --ext .js src--fix",

- _if you run yarn lint or have the vscode eslint plugin installed you will see the following error 

- Parsing error: Must use import to load ES Module
- require() of ES modules is not supported.

- this is an issue related to babel-eslint it is adviced to switch the parser to @babel/eslint-parser as babel-eslint is deprecated and no longer maintained._ 

5. yarn remove babel-eslint, and then yarn add @babel/eslint-parser

6. in the eslintrc: switch the "parser": "babel-eslint" to "parser": "@babel/eslint-parser"

- _we will now the Parsing error: No Babel config file detected_

8. thus we will add "requireConfigFile": false to the parserOptions in the eslintrc, as adviced

- _now eslint works except that it cannot handle jsx. we get the following error for react components:
- Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript"._

- _to solve this we need to do 2 things:_ 

9. yarn add @babel/preset-react -D

10. in the eslintrc add "babelOptions" : { "presets": [ "@babel/preset-react" ] } to the parserOptions

**now you got a working eslint setup. your final eslintrc and package.json should look like this:**

<img width="649" alt="Screenshot 2022-07-19 at 11 48 21" src="https://user-images.githubusercontent.com/47054977/179721717-dad361c0-d0cd-4e2a-aaaf-ab893dd41494.png">
<img width="641" alt="Screenshot 2022-07-19 at 11 48 44" src="https://user-images.githubusercontent.com/47054977/179721733-759de9af-3dd0-4c41-b6ff-2f675f179351.png">

### Solution

1. yarn add @babel/eslint-parser @babel/preset-react -D 
2. (optional: yarn add eslint -D if not installed globally)
3. exchange babel-eslint for @babel/eslint-parser in the eslintrc
4. add "requireConfigFile": false to "parserOptions" in eslintrc
5. add "babelOptions" : { "presets": [ "@babel/preset-react" ] } to the "parserOptions" in eslintrc
6. (optional: add linting scripts to package.json: "lint": "eslint --ext .js src", "lint:fix": "eslint --ext .js src--fix", )

**Comment by derrickmehaffy** [comment]
That's for the info it's greatly appreciated, as this isn't really a bug report I'll go ahead and set it as closed but anyone looking for info when searching should be able to find this.

**Comment by alissawix** [comment]
@derrickmehaffy I believe this is a bug, since the eslint is broken for a new Strapi project. And it is still reproduced
