### ISSUE TITLE
Browsing assets in Strapi dashboard doesn't have sort by file type.

### ISSUE THREAD

**Issue by Erfan1995** [strapi/strapi#13812]
**Bug description**

In adding and browsing assets in Strapi dashboard, we don't have a sort by file type option. 

### Steps to reproduce the behavior

1. Go to 'Content manager'
2. Select a 'Collection' you created.
3. Click on 'Add media'
4. Click on 'BROWSE' in 'Add new assets'
5. Click on 'Sort by'

### Expected behavior

For better user experience, it should have sort by file type as well. 

### Screenshots

![Screenshot 2022-07-20 115926](https://user-images.githubusercontent.com/20784403/179917565-b712c43b-5883-4e07-ac3d-b9e4d7258793.png)

**Comment by gu-stav** [comment]
@Erfan1995 Thanks for the issue. What kind of sorting would you expect here and what is your use-case?

**Comment by luixal** [comment]
Maybe a filter by file type would make more sense. Maybe a field with some options like "Images, Videos, Documents, ..." or even document type (text/word, spreadsheet, ...) so you can filter out the rest of uploads that doesn't match what you're looking for.

**Comment by gu-stav** [comment]
@derrickmehaffy Could we move that issue to Canny?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Could we move that issue to Canny?

Yup I will :)

**Comment by derrickmehaffy** [comment]
Moved this to https://feedback.strapi.io/customization/p/add-file-type-sort-to-upload-plugin-ui

Marking this issue as closed and locking it
