### ISSUE TITLE
UID doesn't auto fill

### ISSUE THREAD

**Issue by arashkevich25** [strapi/strapi#13811]
Added new uid field (targetField/options tried two) to User. After adding new user by API this field doesnt fill up into db. 

I attempted to add lifecycles to `src/extensions/users-permissions/content-types/user/lifecycles.js` but it doesn't work as well.
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.2.2
- Database: Postgress
- Operating system: MacOS

### Code snippets
`src/extensions/users-permissions/content-types/user/lifecycles.js`

```
'use strict';

const uuid = require('uuid');

module.exports = {
  beforeCreate: async (model) => {
    model.set('unique_name', uuid());
  }
};
```

**Comment by Kazdan1994** [comment]
Hello,

I did that:
`src/index.js`

```
'use strict';

const { v4: uuidv4 } = require('uuid');

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register(/*{ strapi }*/) {},

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap(/*{ strapi }*/) {
    strapi.db.lifecycles.subscribe({
      models: ['plugin::users-permissions.user'],

      async beforeCreate(event) {
        event.params.data.uid = uuidv4().replace('-', '');
      },
    });
  },
};
```

Hope it can help you.

**Comment by SAG33** [comment]
> Привет
> 
> Я сделал это: `src/index.js`
> 
> ```
> 'use strict';
> 
> const { v4: uuidv4 } = require('uuid');
> 
> module.exports = {
>   /**
>    * An asynchronous register function that runs before
>    * your application is initialized.
>    *
>    * This gives you an opportunity to extend code.
>    */
>   register(/*{ strapi }*/) {},
> 
>   /**
>    * An asynchronous bootstrap function that runs before
>    * your application gets started.
>    *
>    * This gives you an opportunity to set up your data model,
>    * run jobs, or perform some special logic.
>    */
>   bootstrap(/*{ strapi }*/) {
>     strapi.db.lifecycles.subscribe({
>       models: ['plugin::users-permissions.user'],
> 
>       async beforeCreate(event) {
>         event.params.data.uid = uuidv4().replace('-', '');
>       },
>     });
>   },
> };
> ```
> 
> Надеюсь, это может помочь вам.

Buddy, tell me pls - how to do the same for any field of the Content-type Builder?
Thank you in advance

**Comment by derrickmehaffy** [comment]
Currently the UID logic does not work with relations but I wasn't really sure what was being asked here. I'll close this one for now but if you still feel this is a bug let us know.
