### ISSUE TITLE
i18n plugin: Wrong language code for Ukraine

### ISSUE THREAD

**Issue by DevHusariaSolutions** [strapi/strapi#13816]
Code ISO 3166 for Ukraine is "ua".
Plugin uses "uk".
It's not just incorrect, but also people may think it's British English...

**Comment by gu-stav** [comment]
@ronronscelestes could you have a look at this one?

**Comment by ronronscelestes** [comment]
Hi @DevHusariaSolutions 😊
We are handling i18n with [IETF BCP 47](https://en.wikipedia.org/wiki/IETF_language_tag) format:

- `uk` is defining the language from [ISO 639 nomenclature](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
- `UA` is defining the region from [ISO 3166-1 alpha-2 nomemclature](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements)

For example UK would mean _United Kingdom_ which is a region and not a language:
British English would then be `en` for _English_ **language** + `GB` for _United Kingdom of Great Britain and Northern Ireland_ **region**.
