### ISSUE TITLE
Upload file during creation with Component not working correctly

### ISSUE THREAD

**Issue by freloe** [strapi/strapi#13828]
### Required System information

- Node.js version: 14.19.3
- YARN version: 1.22.19
- Strapi version: 4.1.12
- Database: sqlite
- Operating system: Ubuntu 20.04.4 LTS

### Describe the bug

Uploading via the multiform/form-data to an Object with a file inside a Component doesn't correctly link/save the file in the Component.
Other file uploads to the root data, not in a Component, work correctly.

### Expected behavior

File should show up in the Component

### Data Model

The Collection Type
```json
{
    "kind": "collectionType",
    "collectionName": "recommendation_information_all",
    "info": {
    "singularName": "recommendation-information",
    "pluralName": "recommendation-information-all",
    "displayName": "Recommendation_Information",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "recommendation": {
      "type": "component",
      "repeatable": false,
      "component": "contacts.professor"
    },
    "student": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::student.student",
      "inversedBy": "recommendation_information"
    }
  }
}
```

The Component
```json
{
  "collectionName": "components_contacts_professors",
  "info": {
    "displayName": "professor",
    "icon": "user-graduate",
    "description": ""
  },
  "options": {},
  "attributes": {
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    },
    "email": {
      "type": "email"
    },
    "recommendation_letter": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "files"
      ]
    },
    "title": {
      "type": "string"
    }
  }
}
```

### Code thats not working
```javascript
save(event) {
    event.preventDefault()
    return new Promise(async (resolve,reject) => {
      let formData = new FormData()
      formData.append("data",JSON.stringify({
          "recommendation":{
            "first_name":this.state.firstName,
            "last_name":this.state.lastName,
            "email":this.state.email,
            "title":this.state.title
          }
      }))
      console.log(this.state.letter)
        formData.append("files.recommendation[0].recommendation_letter",this.state.letter)
      let request = {
        method:"POST",
        body:formData
      }
      let result = await fetch('http://localhost:1337/api/recommendation-information-all',request)
      console.log(result)
      resolve(true)
    })
  }
```

### Additional Context
Probably an unrelated Problem/Bug adding Relations during creation also doesn't seem to work

**Comment by degoev** [comment]
Uploading to component works well if you add populate params for this component to the uploading request.

@freloe Try this:
`let result = await fetch('http://localhost:1337/api/recommendation-information-all?populate[recommendation][populate]=%2A',request)`

This bug occurs when code at [this line](https://github.com/strapi/strapi/blob/06694ec71d345d59def7e1fa94f8fce4a50d6d37/packages/core/strapi/lib/services/utils/upload-files.js#L73) can't resolve component id (because component is not populated)

![photo_2022-07-28 14 49 18](https://user-images.githubusercontent.com/50908619/181498446-593b8be8-b024-4432-983d-42be00289f14.jpeg)
![photo_2022-07-28 14 49 03](https://user-images.githubusercontent.com/50908619/181498448-3c62486a-9f4f-438d-8bf7-1ed08f34850d.jpeg)

**Comment by freloe** [comment]
> Uploading to component works well if you add populate params for this component to the uploading request.
> 
> @freloe Try this: `let result = await fetch('http://localhost:1337/api/recommendation-information-all?populate[recommendation][populate]=%2A',request)`
> 
> This bug occurs when code at [this line](https://github.com/strapi/strapi/blob/06694ec71d345d59def7e1fa94f8fce4a50d6d37/packages/core/strapi/lib/services/utils/upload-files.js#L73) can't resolve component id (because component is not populated)
> 
> ![photo_2022-07-28 14 49 18](https://user-images.githubusercontent.com/50908619/181498446-593b8be8-b024-4432-983d-42be00289f14.jpeg) ![photo_2022-07-28 14 49 03](https://user-images.githubusercontent.com/50908619/181498448-3c62486a-9f4f-438d-8bf7-1ed08f34850d.jpeg)

Thank you very much, that solved the issue!

**Comment by nikkizol** [comment]
Hey guys, is there any work around,  I upload image in repeatable component via admin panel, but it get's somewhere else as I don't see it in that component table.

**Comment by derrickmehaffy** [comment]
> Hey guys, is there any work around,  I upload image in repeatable component via admin panel, but it get's somewhere else as I don't see it in that component table.

This issue should be fixed on the latest release, what version are you running?

**Comment by nikkizol** [comment]
@derrickmehaffy 4.4.3v
