### ISSUE TITLE
I am unable to connect my personal database's table to Strapi, or I am unable to connect Strapi database's table to my personal project

### ISSUE THREAD

**Issue by Chanaka-Sandaruwan** [strapi/strapi#13826]
### Required System information

- Node.js version:>=10.16.0 <=14.x.x
- NPM version:^6.0.0
- Strapi version:3.6.8
- Database: MongoDB
- Operating system: ubuntu 20.04

### Describe the bug

I am unable to connect my personal database's table to the Strapi database's table, or I am unable to connect the Strapi database's table to my personal database's table. 

My personal project will always be connected to a separate database table which I will create manually. The same table used in Strapi must be created in my personal database's table, and whenever Strapi's table is updated, I need to update my personal database's table.

### Expected behavior

The same table used in Strapi must be created in my personal database's table, and whenever Strapi's table is updated, I need to update my personal database's table.

**Comment by BurhanRaja** [comment]
Which database are you using?

In README.md :-

Database agnostic: Strapi works with SQL databases. You can choose the database you prefer: PostgreSQL, MySQL, MariaDB, and SQLite.

**Comment by Chanaka-Sandaruwan** [comment]
I use MongoDB, the problem is how can I update the Strapi database's table as same as my  MongoDB database's table.

**Comment by gu-stav** [comment]
@BurhanRaja said it already: we do not support MongoDB with Strapi@v4. If you encounter a problem using it with Strapi@v3, please refer to Discord and ask the question there.
