### ISSUE TITLE
pt-BR translated words are not being properly displayed

### ISSUE THREAD

**Issue by rogix** [strapi/strapi#13835]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.2.3
- Database: SQLite (quickstart)
- Operating system: Linux Mint 20.2 Cinnamon

### Describe the bug

Some pt-BR translations are not being properly displayed, even the translation existing in the pt-BR.json file. 

### Steps to reproduce the behavior

1. Go to `admin/app.js`
2. Update locales to `locales: ["pt-BR"]`
3. Run `yarn develop` again
4. Change the language to `pt-BR` in the admin panel
5. See the error

### Expected behavior

All the words translated in the pt-BR.json file should be displayed properly.

Here you can check the word "Password" is not being translated.

![image](https://user-images.githubusercontent.com/12768403/180650419-fe5f5b2d-fad6-4458-8bd8-27db6914f29e.png)

However this word is already translated in the pt-BR.json file, as one can see here:

![image](https://user-images.githubusercontent.com/12768403/180650482-df7a7a48-30bc-4376-a6b3-eef4cc7c3542.png)

**Comment by gu-stav** [comment]
Could you try and translate the key `global.password` with "Senha" and see if it fixes your issue?

**Comment by rogix** [comment]
Hi, @gu-stav! I tried and it works.

![image](https://user-images.githubusercontent.com/12768403/180775355-55d41f34-bd39-4f46-a163-047fbcfbd311.png)

I forked it and tried it local and it worked as expected. Not just `password`, but all the other pt-BR translations not displayed properly face a similar problem. Adding `global` fix the issue. It seems some translations files are missing the `global.**`.

I could open a pull request to fix this issue, if it's ok.

**Comment by gu-stav** [comment]
@rogix If you feel like there is an issue, please go ahead and propose a fix :)

**Comment by rogix** [comment]
Thanks, @gu-stav! I'll do it. :)

**Comment by Nike682631** [comment]
Is this issue still available to work on?

**Comment by rogix** [comment]
Hi, @Nike682631 I have just created the PR concernig this issue. Please, feel free to review it and add any comment you think is important and I will check it out. Thanks!

**Comment by danilomasato** [comment]
estou enfrentando o mesmo problema, poderia me ajudar??
