### ISSUE TITLE
[plugin-email] Default sender email UI issue

### ISSUE THREAD

**Issue by veronq** [strapi/strapi#13844]
### Required System information

- Strapi version: **4.2.3**
- Database: **sqlite**
- Operating system: **macOS Monterey**

### Describe the bug

When using an object as the **defaultFrom** setting of the email provider, it renders **[object Object]** in the dashboard UI.

### Steps to reproduce the behavior

1. Install the [sendgrid email provider](https://www.npmjs.com/package/@strapi/provider-email-sendgrid),
2. Create the `config/plugins.js` file,
3. Set the **defaultFrom** setting as an object (name, email),
4. Go to the Settings/Configuration page in the admin dashboard,
5. The **default sender email** field shows **[object Object]**.

### Expected behavior

The `Default sender email` field should display both the sender name and email.

### Screenshots

![Screen Shot 2022-07-26 at 10 11 22 am](https://user-images.githubusercontent.com/29384992/180907557-882b63ab-17f9-46c6-a988-0e87dba358f5.png)

### Code snippets

**config/plugins.js**
```
module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'sendgrid',
      providerOptions: {
        apiKey: env('SENDGRID_API_KEY'),
      },
      settings: {
        defaultFrom: {
          email: 'no-reply@example.com',
          name: 'My Company'
        },
        defaultReplyTo: 'no-reply@example.com',
        testAddress: 'dev@example.com',
      },
    },
  },
});
```

**Comment by derrickmehaffy** [comment]
Currently our providers only support email addresses and not objects, see how it's used here in the provider itself:

https://github.com/strapi/strapi/blob/70f9be00fc72e194658e64ea5360f526260b1352/packages/providers/email-sendgrid/lib/index.js#L16
