### ISSUE TITLE
i18n - Editor role can't use newly added languages

### ISSUE THREAD

**Issue by holyvikt** [strapi/strapi#13850]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version:  4.2.3
- Database: SQLite (5.0.8)
- Operating system: Ubuntu 20.04.3 (WSL Windows 11)

### Describe the bug

When adding a new language in the settings (Internationalization), only a user with the SuperAdmin role can add records in the newly added language to existing entities. Editors only have access to languages set before the entity was created.

### Steps to reproduce the behavior

1. Login as admin
2. Set two languages in Internatialization settings (e.g. en, cs)
3. Create content type  with turned on internationalization
4. Allow Editor to read and update data of newly created content type.
5. Both Admin and Editor should be able to create items in en and cs
6. As Admin, add new language (e.g. fr)
7. Admin now has option to create items in fr.
8. Editor still can create items only in en and cs.

Note: If the current editor's role is changed to Sueper Admin, they will also see fr in the dropdown menu.

### Expected behavior

If a new language is added, all roles that have access to the content type should be able to work with all available languages.

### Screenshots

2 screenshots with admin and editor views after applying the steps above.

Admin view:
![admin-view](https://user-images.githubusercontent.com/49520673/180982761-9f828eca-23d9-4fec-b1f4-d457b3f21576.png)

Editor view:
![editor-view](https://user-images.githubusercontent.com/49520673/180982795-f93060e7-15ba-4360-8f2d-ae0ea38639df.png)

**Comment by kasonde** [comment]
Hi @holyvikt you have to go back to the Admin Role and enable that new locale for the desired user. 

Unfortunately, there's a bug that will stop you from fixing this in the community edition. You have to have a license. I'm working on opening that issue now and will close this and reference it here.

**Comment by VladimirAndrianov96** [comment]
Hey, have you tried restarting the Strapi instance? I noticed it does not refresh a cloud instance after you create a new language using a local instance (cloud and local instances both use same cloud DB), this might help someone, that requires restarting Strapi in cloud manually

**Comment by kasonde** [comment]
> Hi @holyvikt you have to go back to the Admin Role and enable that new locale for the desired user. Can you confirm that this helps?

Closing this as no response. This should be the source unless otherwise. I'll reopen it when we have more information.
