### ISSUE TITLE
@strapi/helper-plugin and EditViewDataManagerProvider

### ISSUE THREAD

**Issue by Tikondra** [strapi/strapi#13853]
- Node.js version: v14.19.3
- NPM version: 6.14.17
- Strapi version: 4.3.0-beta.2
- Database: postgres
- Operating system: macOS

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/52007300/180999049-efa2dda1-79a1-41e9-a3fc-c912db7a8fb0.png">

![image](https://user-images.githubusercontent.com/52007300/181001225-b9d235c4-30e4-4170-b3a9-da37d39a0bdb.png)

![image](https://user-images.githubusercontent.com/52007300/181001379-76150768-275f-4c6f-b054-c44aa4037da5.png)

**Comment by gu-stav** [comment]
Thank you very much for the issue. 🌻 

You have saved me from a bigger bug, which would have gotten released tomorrow otherwise. I believe this issue will be fixed by https://github.com/strapi/strapi/pull/13854.
