### ISSUE TITLE
afterCreateMany does not provide the `id` of the newly created entries

### ISSUE THREAD

**Issue by bidoubiwa** [strapi/strapi#13856]
### Required System information

- Node.js version: node 14/18 (tried on both)
- NPM version: 8.12.0
- Strapi version: 
     - "@strapi/strapi": "^4.2.3",
     - "@strapi/utils": "^4.2.2",
- Database: `sqlight`
- Operating system: Mac m1

### Describe the bug

When creating multiple entries into a content-type that has been subscribed to `afterCreateMany` hook the returned data inside the event element do not contain the generated `id`.
The data lies in `params.data` which understandably by the naming implies what has been provided and not what has been returned. 
Nonetheless the `result` object contains the **count** of the number of entries that have been added and not the added data like in `afterCreate`.

### Steps to reproduce the behavior

1. Create a content type named restaurant with a title field and a description field
2. Subscribe it to `afterCreateMany`
```js
await strapi.db.lifecycles.subscribe({
   models: ["api::restaurant.restaurant"],
    async afterCreateMany(event) {
       console.log(JSON.stringify(event, null, 2))
     },
   }
```
4. Create some entries
```js
  await strapi.db.query('api::restaurant.restaurant').createMany({
    data: [
      {
        title: 'ABCD',
        description: 'ho',
      },
      {
        title: 'EFGH',
      },
    ],
  })
```
6. Result: 
```
"action": "afterCreateMany",
  "model": {
    "singularName": "restaurant",
  }
  // removed non relevant fields
  "params": {
    "data": [
      {
        "title": "ABCD",
        "description": "ho",
        "createdAt": "2022-07-26T14:07:33.836Z",
        "updatedAt": "2022-07-26T14:07:33.836Z"
      },
      {
        "title": "EFGH",
        "createdAt": "2022-07-26T14:07:33.836Z",
        "updatedAt": "2022-07-26T14:07:33.836Z"
      }
    ]
  },
  "result": {
    "count": 2
  }
}
```

### Expected behavior

To be able to work with the newly created entries the `id` is necessary. For example to add it in a separate database (i.e meilisearch or elasticsearch). 
By having to generate our own `id` we would not be bale in the future remove that entry or update it in the second database in the other hooks like `afterDeleteMany` or `afterUpdateMany`.

**Comment by derrickmehaffy** [comment]
Confirmed via @petersg83 on internal Slack that it was originally intended but I agree with @kasonde that it does look like a bug to me.

Either way I'll leave it for @marcoautiero to figure out if it's a bug or enhancement.

![image](https://user-images.githubusercontent.com/8593673/182947096-d52dcef8-ea16-4942-a4d1-bc3a9307b94c.png)

**Comment by WalkingPizza** [comment]
I am trying to make a PR to improve this.
Should I pass an `ids` array in the results along with `count`?

PS: I have found a bug with `createMany`. Apparently, `this.createQueryBuilder(uid).insert(dataToInsert).execute()` does not return all of the affected IDs but just the last one.

**Comment by bidoubiwa** [comment]
> Should I pass an ids array in the results along with count?

That is a good idea, since the user could potentially add a very big amount of documents adding them as whole objects in the result field could be problematic. Whereas returning the `ids` only, provides the possibility to fetch the documents in batches in case there are too many added documents.

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/aftercreatemany-does-not-provide-the-id-of-the-newly-created-entries

Thanks!
