### ISSUE TITLE
Enumeration field doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1386]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.4
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

After create a new enumeration field in the content type builder, the server stop with:

```
"ENUM_CATEGORY_TYPE" not found in document
```

**Steps to reproduce the problem**

Add a new enumeration field in the content type builder.

**What is the expected behavior?**

Working :)

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/1383

**Comment by derrickmehaffy** [comment]
@abdonrd do you have graphql installed?

**Comment by abdonrd** [comment]
Oh! I thought I did not have it, and that it would be a different issue. But it seems that if it is the same.

Thanks @derrickmehaffy!

**Comment by lauriejim** [comment]
A PR is open about this issue https://github.com/strapi/strapi/pull/1384
