### ISSUE TITLE
Handle media library error messages more gracefully with providers

### ISSUE THREAD

**Issue by Sija** [strapi/strapi#13867]
# Edit: Issue is due to a limit in an AWS resource, moved this to be an enhancement of the error message, see: https://github.com/strapi/strapi/issues/13867#issuecomment-1199572603

### Required System information

- Node.js version: v16.16.0
- Strapi version: v4.3.0
- Database: PostreSQL
- Operating system: Linux

### Describe the bug

In case `Error: Request failed with status code 413` is thrown when uploading a file (We're using s3 provider), ML goes completely blank and console shows `TypeError: _e.response.data.error is undefined`.

That seems to be a regression from #13768 caused by [these lines](https://github.com/strapi/strapi/pull/13768/files#diff-8fcff829dd031c69d9109c5c77282ab27d946bd7e885b623fe52b86b49781e0eR104-R105).

### Steps to reproduce the behavior

1. Go to Media Library
2. Upload a file big enough to cause response `413` status code
3. App blows up

### Expected behavior

Error to be shown in the UI.

### Additional context

I'm using S3 upload provider.

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.3.0 either via media library or api upload, I do get the 413 error response but the app remains running. Tested with a 1GB text file

![image](https://user-images.githubusercontent.com/8593673/181282513-8bdff01a-591c-4a4a-826a-accd79e0170e.png)

**Comment by Sija** [comment]
@derrickmehaffy We're getting a `413` response with the payload:

```json
{"message":"Request Entity Too Large"}
```

**Comment by derrickmehaffy** [comment]
Same for AWS S3: 
![image](https://user-images.githubusercontent.com/8593673/181284233-fdc07947-d1b8-40ad-a80a-11070a37be32.png)

@Sija that error is expected unless you have modified the maximum file size configs for both the body middleware and the upload plugin.

**Comment by derrickmehaffy** [comment]
After updating the body middleware and plugin config, while I don't get the error described above I do have a stalled upload: https://www.loom.com/share/c22bb0a09fbe43c98941c5ad743e72a5

**Comment by Sija** [comment]
@derrickmehaffy Could you please provide me with the way how to update the body middleware and plugin config?

**Comment by derrickmehaffy** [comment]
It's in the upload plugin docs here: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#max-file-size

**Comment by Sija** [comment]
@derrickmehaffy Thanks 🙏

**Comment by gu-stav** [comment]
@Sija Are you using a custom controller or provider? The only idea I have how this could have happened, if the API throws different error formats.

**Comment by Sija** [comment]
@gu-stav nope, this happens when adding the file in the Media Library directly. I'm using S3 upload provider, app itself is running on ECS, accessed through ALB and API Gateway

**Comment by gu-stav** [comment]
Thanks for the info. I'll have a look tomorrow and work on a fix asap, if I find a way to reproduce it.

**Comment by gu-stav** [comment]
@Sija could share your s3 config with me please (except the keys of course :)).

**Comment by Sija** [comment]
After bit of digging it seems that the error is produced by the AWS API Gateway (because of its 10mb, unchangeable [limit](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#http-api-quotas)) - and this is something we need to "fix" ourselves.

Another thing though is that the ML shouldn't blow up in case there's unexpected response payload, and just gracefully display generic error message (in this case it could actually take the proper error description from the `message` key of the response payload).

**Comment by derrickmehaffy** [comment]
Indeed, I agree we should handle the error message a bit more gracefully. I'll change this to an enhancement since we know the bug isn't on the Strapi side

**Comment by Sija** [comment]
Nevertheless ML shouldn't blow up, therefore I'd call it a bug.

**Comment by derrickmehaffy** [comment]
> Nevertheless ML shouldn't blow up, therefore I'd call it a bug.

It's not really a bug per say but we should tell the user the why the ML isn't working with a better error message hence why it's an enhancement. A bug is when something isn't working as intended when the pre-reqs are setup correctly, in your case the pre-reqs were not correct. It's just a matter of how we prioritize issues and small things like this that we call enhancements get a lower priority as they are "nice to have" and not "required to be fixed"

**Comment by gu-stav** [comment]
@Marc-Roig and I discussed the issue today and we believe it is realated to: https://github.com/strapi/strapi/issues/13316 We will come up with a fix until the next release on Wednesday. The preferred solution is to catch this class of errors in the backend and send the normalized response back. If it turns out, this becomes a bigger issue, we will make sure the frontend can handle both formats (for the moment).

**Comment by Sija** [comment]
@gu-stav it doesn't seem to be related. As mentioned before, the error response is sent by the AWS API Gateway and the error handling was broken in #13768

**Comment by gu-stav** [comment]
@Sija Thanks! I agree it was broken there. The fix will (hopefully) not be to handle that error in the frontend, but to send back a normalized error format, as we do everywhere. Right now, we are trying to figure out, why this is not handled yet.

**Comment by Sija** [comment]
@gu-stav In this particular case you can't normalize the response, since the error is not being sent be strapi at all, but from the "higher" infrastructure layer - being the AWS API Gateway (which sits in a front of strapi).

**Comment by gu-stav** [comment]
@Sija I see - so you are using the API Gateway as a proxy (sorry I am not familiar with the setup)? That would mean the fact the error message worked was a coincidence?

**Comment by Sija** [comment]
> @Sija I see - so you are using the API Gateway as a proxy (sorry I am not familiar with the setup)? That would mean the fact the error message worked before was a coincidence, because the format matched the one from the Proxy?

@gu-stav That's correct.

> In any case the interface shouldn't go blank I agree, but in this case we'd need to display a generic error message then I think?

I guess so 👍
