### ISSUE TITLE
No visible scroll indicator in relations with more than 4 entries

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#13865]
### Required System information

- Node.js version: 16
- Strapi version: v4.3.0-beta.2
- Operation System: MacOS

### Describe the bug

This is more of a UX bug.

![Bildschirmfoto 2022-07-27 um 15 49 34](https://user-images.githubusercontent.com/45072099/181264697-7b5b8e43-bf31-4250-b3b1-bd18e8fe9d2d.png)

In this screenshot we got multiple relations to pages assigned in the right sidebar.
One of our content editors was confused because he couldn't add `partners` to that list even though it has been working on other pages like this. Turns out that the fifth entry that's selected is `partners` and that one is just not visible because only 4 entries are shown and besides the `(5)` on top, there is no visible indication that this is a scrollable field.

### Steps to reproduce the behavior

1. Create a relation
2. Add more than 4 entries

### Expected behavior

There should be some kind of visible indication that there are more entries (e.g. the 5th entry is partially visible).

**Comment by gu-stav** [comment]
We are currently re-working the design and the way relations are handled. They will be moved into the main layout and new design will take scrollbars into account. You can follow the progress here: https://feedback.strapi.io/customization/p/move-relations-into-the-main-view

I think we won't fix this issue with the current implementation, to be able to move to the new one quickly. I'll therefore close this one.

**Comment by gu-stav** [comment]
@Emmanuel-Melon We hope to release a beta version in about 6 weeks.

**Comment by Emmanuel-Melon** [comment]
> @Emmanuel-Melon We hope to release a beta version in about 6 weeks. You can follow the progress here: https://feedback.strapi.io/customization/p/move-relations-into-the-main-view

Okay I'll check it out!
