### ISSUE TITLE
TypeError: host.onUnRecoverableConfigFileDiagnostic is not a function when creating new strapi app

### ISSUE THREAD

**Issue by jordyvanraalte** [strapi/strapi#13866]
### Required System information

- Node.js version: v16.13.1
- NPM version:  v16.13.1
- Strapi version: 4.3.0
- Database:
- Operating system: Windows 10

### Describe the bug

By creating a strapi project with the command npx create-strapi-app my-project --quickstart and starting it with either npm run develop or yarn develop gives me the following error:

TypeError: host.onUnRecoverableConfigFileDiagnostic is not a function

### Steps to reproduce the behavior

1. Install strapi app through npx or yarn
2. Run develop either through npm or yarn
3. See error

### Expected behavior

Strapi starting up and redirecting in the browser to the start up page

**Comment by Convly** [comment]
Hi, could you share a minimal version of your project (as a zip for example) that would allow me to reproduce your issue?

Normally you shouldn't have any issue related to TypeScript when creating a JavaScript Strapi application.

**Comment by jordyvanraalte** [comment]
Hereby as requested the minimal version of my project. I deleted the node modules.

However, it seems like a Windows privelege issue. I created a new project on my desktop and it seems to work. When I try to create a project through Webstorm IDE, I still have the error. I also tried to run Webstorm through adminstrator, however I still get the same error.

[my-project.zip](https://github.com/strapi/strapi/files/9201372/my-project.zip)

**Comment by dngferreira** [comment]
Migrating from a 4.2.3 to 4.3.0 also got me this error on a Linux( debian 11) server.
Reverting to 4.2.3 fixed it.

**Comment by lukasjapan** [comment]
I have the same issue on a MacBook:

```
$ node --version
v16.15.1
$ yarn --version
1.22.18
$ yarn create strapi-app strapi --quickstart
yarn create v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "blitz > @testing-library/react@11.2.5" has unmet peer dependency "react@*".
warning "blitz > @testing-library/react@11.2.5" has unmet peer dependency "react-dom@*".
...
warning "graphql-cli > graphql-config > @graphql-tools/url-loader > @graphql-tools/delegate > @graphql-tools/batch-execute@7.1.2" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "graphql-cli > graphql-config > @graphql-tools/url-loader > @graphql-tools/delegate > @graphql-tools/schema@7.1.5" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
[4/4] 🔨  Building fresh packages...
success Installed "create-strapi-app@4.3.0" with binaries:
      - create-strapi-app
Creating a quickstart project.
Creating a new Strapi application at /Users/lukasprasuhn/global-development/sentosa-admin/strapi.
Creating files.
Dependencies installed successfully.

Your application was created at /Users/lukasprasuhn/global-development/sentosa-admin/strapi.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/lukasprasuhn/global-development/sentosa-admin/strapi
  yarn develop

Running your Strapi application.

> strapi@0.1.0 develop
> strapi develop

TypeError: host.onUnRecoverableConfigFileDiagnostic is not a function
    at Object.getParsedCommandLineOfConfigFile (/Users/lukasprasuhn/global-development/sentosa-admin/strapi/node_modules/typescript/lib/typescript.js:40048:18)
    at module.exports (/Users/lukasprasuhn/global-development/sentosa-admin/strapi/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)
    at Object.module.exports [as resolveOutDir] (/Users/lukasprasuhn/global-development/sentosa-admin/strapi/node_modules/@strapi/typescript-utils/lib/utils/resolve-outdir.js:15:7)
    at async module.exports (/Users/lukasprasuhn/global-development/sentosa-admin/strapi/node_modules/@strapi/strapi/lib/commands/develop.js:25:18)
error Command failed.
Exit code: 1
Command: /opt/homebrew/bin/create-strapi-app
Arguments: strapi --quickstart
Directory: /Users/lukasprasuhn/global-development/sentosa-admin
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

However, it worked when running the command in a docker container.

```
$ docker run --rm node:16 yarn create strapi-app strapi --quickstart
```

Strangely, I could also get it running by simply not using the `--quickstart` feature.

I hope this helps.

**Comment by lukasjapan** [comment]
I have the same issue on a MacBook:

```
$ node --version
v16.15.1
$ yarn --version
1.22.18
$ yarn create strapi-app strapi --quickstart
yarn create v1.22.18
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "blitz > @testing-library/react@11.2.5" has unmet peer dependency "react@*".
warning "blitz > @testing-library/react@11.2.5" has unmet peer dependency "react-dom@*".
...
warning "graphql-cli > graphql-config > @graphql-tools/url-loader > @graphql-tools/delegate > @graphql-tools/batch-execute@7.1.2" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "graphql-cli > graphql-config > @graphql-tools/url-loader > @graphql-tools/delegate > @graphql-tools/schema@7.1.5" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
[4/4] 🔨  Building fresh packages...
success Installed "create-strapi-app@4.3.0" with binaries:
      - create-strapi-app
Creating a quickstart project.
Creating a new Strapi application at {...}/strapi.
Creating files.
Dependencies installed successfully.

Your application was created at {...}/strapi.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd {...}/strapi
  yarn develop

Running your Strapi application.

> strapi@0.1.0 develop
> strapi develop

TypeError: host.onUnRecoverableConfigFileDiagnostic is not a function
    at Object.getParsedCommandLineOfConfigFile ({...}/strapi/node_modules/typescript/lib/typescript.js:40048:18)
    at module.exports ({...}/strapi/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)
    at Object.module.exports [as resolveOutDir] ({...}/strapi/node_modules/@strapi/typescript-utils/lib/utils/resolve-outdir.js:15:7)
    at async module.exports ({...}/strapi/node_modules/@strapi/strapi/lib/commands/develop.js:25:18)
error Command failed.
Exit code: 1
Command: /opt/homebrew/bin/create-strapi-app
Arguments: strapi --quickstart
Directory: {...}
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

However, it worked when running the command in a docker container.

```
$ docker run --rm node:16 yarn create strapi-app strapi --quickstart
```

Strangely, I could also get it running by simply not using the `--quickstart` feature.

I hope this helps.

**Comment by sauldeleon** [comment]
Hi. I have just migrated my strapi to 4.3.0 and have started facing this issue, using a Macbook pro and latest nodejs version. Going back to previous 4.2.x Version solved the issue!

**Comment by Convly** [comment]
Hey there, I tried to reproduce it again (and on different systems (windows 11/macOS/ubuntu 22) but failed every time.
At this point, I'm wondering if it could be linked to globally installed packages with different versions?

@sauldeleon @dngferreira @jordyvanraalte 
Would you be ok sharing with me your terminal logs (same as what lukasjapan did) so that I can compare them to see if there is some kind of pattern?

**Comment by sauldeleon** [comment]
> 

Hello @Convly and thanks for your response.

In my scenario you could clone my repo and give it a try. I think you dont need any data but I cannot provide ENV variables if needed. Or maybe I can share you via private DM.

Anyway, Here is my terminal log

```
yarn start:api                            
TypeError: host.onUnRecoverableConfigFileDiagnostic is not a function
    at Object.getParsedCommandLineOfConfigFile (/path/whemotion/packages/api/node_modules/typescript/lib/typescript.js:40053:18)
    at module.exports (/path/whemotion/packages/api/node_modules/@strapi/typescript-utils/lib/utils/resolve-config-options.js:9:43)
    at Object.module.exports [as resolveOutDir] (/path/whemotion/packages/api/node_modules/@strapi/typescript-utils/lib/utils/resolve-outdir.js:15:7)
    at async module.exports (/path/whemotion/packages/api/node_modules/@strapi/strapi/lib/commands/start.js:14:18)
```

tested node version
v16.15.0

repository url: https://github.com/yisuses/whemotion
branch: chore/update-dependencies

Steps:

1. clone
2. yarn
3. yarn start:api

in case you need something else, please ping me!

**Comment by Convly** [comment]
Hey @sauldeleon. Thanks a lot for your repository. I'm now able to reproduce the issue & will look into it.

**Comment by Convly** [comment]
Alright from what I saw from your repository, it looks like `ts.findConfigFile` (that we use to detect if we're in a typescript project or not) is detecting false positive because it recursively look in... the parent directories (you've a tsconfig.json at the root of your monorepo).

I'll try to investigate more later & find a solution.

**Comment by sauldeleon** [comment]
hey @Convly great! Maybe is then an issue that only affects to monorepos, right? which is a good point as for most of the projects this would work successfully then.

Let me now if I can help somehow!

**Comment by lukasjapan** [comment]
>  is detecting false positive because it recursively look in... the parent directories

```
$ cd /tmp/
$ yarn create strapi-app strapi --quickstart
```

I can confirm that this works.

**Comment by Convly** [comment]
Hi, I submitted a fix in the linked PR.
It should be publicly available on August 10th. In the meantime, you can apply the fix locally and see if it solves the issue for you.

Thanks again to all of you for raising this issue :slightly_smiling_face:

**Comment by sauldeleon** [comment]
@Convly somebody is a legend here, and it is you!

Thanks a lot!!

![image](https://user-images.githubusercontent.com/2400723/182425206-efab1365-93e6-46a9-afa4-2d9880162e2f.png)

**Comment by rubyjasmin** [comment]
For anyone who is getting the following error on `next dev`:
```
ReferenceError: requestAnimationFrame is not defined
```
Try moving `import "raf/polyfill"` to the top of _app.tsx
