### ISSUE TITLE
Strapi generate doesn't work

### ISSUE THREAD

**Issue by Umoren** [strapi/strapi#13864]
## Bug report
`strapi generate` doesn't work.
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: 3.6.0-beta.5
- Database: sqlite
- Operating system: macOS Monterrey

### Describe the bug

It returns this error `error: unknown command 'generate'. See 'strapi --help'.`
I had to use `yarn strapi generate`
### Steps to reproduce the behavior

1. Create a new strapi project `yarn create strapi-app project-test --quickstart`
2. Run `strapi generate` if you have the global CLI installed or `yarn strapi develop`
3. error:

### Expected behavior

```bash
➜  my-strapi-project-test yarn strapi generate
yarn run v1.22.19
$ strapi generate
? Strapi Generators plugin - Generate a basic plugin
? Plugin name 
```

**Comment by kasonde** [comment]
Hi, this works in the latest v3 release which is v3.6.10. Please consider using the latest version of Strapi and also using the correct v3 cli generation syntax. For example: yarn strapi generate:<controller,plugin,model, etc>.
