### ISSUE TITLE
Preview button present in development  mode but not in production

### ISSUE THREAD

**Issue by boluT-bi** [strapi/strapi#13863]
After installing and setting up this plugin feature in plugin.js, the preview button appears and works fine on a local server

![2022-07-27](https://user-images.githubusercontent.com/72227433/181227977-2ebcfb19-79fe-4e11-a375-d1f9fa20d947.png)

The live server is up to date and shows that the preview button has been installed:
![2022-07-27 (2)](https://user-images.githubusercontent.com/72227433/181228238-b8c49bc5-c661-4205-933f-f703dfa92716.png)

But the preview button doesn't appear in the ui

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Additionally, this is not an issue with Strapi but a question that you have with the plugin in question. For this, please post your question on either of our community forums ([Discord](https://discord.strapi.io) and [Forum](https://forum.strapi.io)). If you do believe this is an issue with the plugin, please engage the plugin creator through their Github issues. 

Thank you.
