### ISSUE TITLE
create record with relations using restful api, successful but relations is null

### ISSUE THREAD

**Issue by lordzpipo** [strapi/strapi#13874]
### Required System information

- Node.js version: v16
- NPM version: 8.3.1
- Strapi version: 4.2.3
- Database: sqlite
- Operating system: macos

### Describe the bug

To experience strapi V4, start with fresh project and create a new collections `mytable` with following schema
```
name: text (short text),
user: relations with users(non admin) table
```

create an user using admin dashboard and got the id (example id: 1), then try to create a record using postman with following data
```
{
  data: {
    "name": "strapi test",
    "user": 1 
  }
}
```

record create successful but without relations.
data response as following:
```
{
    "data": {
        "id": 2,
        "attributes": {
            "name": "test name222",
            "createdAt": "2022-07-28T06:07:55.997Z",
            "updatedAt": "2022-07-28T06:07:55.997Z"
        }
    },
    "meta": {}
}
```

### Steps to reproduce the behavior

1. as above

### Expected behavior

record with relations

### Screenshots

-
### Code snippets

-

### Additional context

come from strapi 3

**Comment by petersg83** [comment]
Hello @lordzpipo 
Have you try to use the  `populate` param ?
The related documentation is here: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#rest-api-population-field-selection

**Comment by lordzpipo** [comment]
hi @petersg83 ,
Thanks for answer my question, please allow me to correction my question

Data is created when using restful apis, but the relations field is empty in database (for this case, `user` is empty in database)

This is example output from sqlite3 
```
id|name|user|
1|strapi test||
```

It should looks like this on sqlite3
```
id|name|user|
1|strapi test|1|
```

**Comment by kasonde** [comment]
Hi @lordzpipo please make sure that permissions are enabled for the intended role on the content-types in question. Without this, the data will not be stored.
