### ISSUE TITLE
extend Admin pages is not working.

### ISSUE THREAD

**Issue by gowthamik14** [strapi/strapi#13876]
### Required System information

- Node.js version: 16.15
- NPM version: 8.5
- Strapi version: Latest
- Database:
- Operating system: Windows
### Steps to reproduce the behavior

I would like to extend Auth page and want to implement some more restrictions on passwords.  I could able to do this v3 by copying the Auth page utils forms in the Admin src folder and implement my own validation schema. I tried the same and it is not working with v4 and there is no documentation available for this.  Could you please let us know how to do in Strapi v4 or update documentation. 
![image](https://user-images.githubusercontent.com/62015937/181455339-10c25114-7a47-4433-bab2-f6daffc7fdcc.png)

This is my folder structure and it seems my password validation in my new util is not getting picked up.

**Comment by kasonde** [comment]
Hi, we currently do not support extending the admin in v4. The only work-around for this would be for you to use patch-package and implement your customizations that way.
