### ISSUE TITLE
The one way relation doesn't work with himself

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1387]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.4
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The one way relation doesn't work:

<img width="757" alt="screen shot 2018-06-14 at 10 41 24" src="https://user-images.githubusercontent.com/1007051/41401237-955a39d6-6fbf-11e8-9f59-c39f31f53468.png">

It requires a value in the disabled input.

**Steps to reproduce the problem**

Try to create a one way relation.

**What is the expected behavior?**

Working :)

**Comment by derrickmehaffy** [comment]
Very likely related to: https://github.com/strapi/strapi/issues/1374

Although in this case its a single oneWay, I believe fix provided in the above link disables the check on the disabled input. @soupette ?

**Comment by lauriejim** [comment]
Is it a duplicate issue ? @abdonrd did you already have an other oneWay relation in your model ?

**Comment by derrickmehaffy** [comment]
@lauriejim I just created a oneway relation in 12.4 so I can't reproduce his issue unless I try and add more than one to the same model.

**Comment by derrickmehaffy** [comment]
likely a duplicate issue.

**Comment by abdonrd** [comment]
In my case, is the second field; and the first was a simple `name` (String).

**Comment by lauriejim** [comment]
@abdonrd If you are trying to make a relation with an other model than the same.
Not `category` -> `category` but `category` -> `user` for example, it works ?

**Comment by abdonrd** [comment]
@lauriejim yes! It works with the `user` model.

**Comment by lauriejim** [comment]
Some news about it, if you are create the relation manually it will work on the content manager.

**Comment by derrickmehaffy** [comment]
@lauriejim I believe this is related the issues that have been reported with oneWay in general. I think there is a bug with the adminUI that may be causing this issue.

**Comment by derrickmehaffy** [comment]
Likely related: https://github.com/strapi/strapi/issues/1477
