### ISSUE TITLE
Documentation plugin generating invalid OpenAPI schema

### ISSUE THREAD

**Issue by nimajneb** [strapi/strapi#13885]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.0
- Database: SQLite
- Operating system: macOS Monterey v12.2

### Describe the bug

I'm trying to auto-generate a TypeScript client for my Strapi API using `openapi-typescript-codegen` and I believe I'm running into an issue where the Strapi documentation plugin is creating an invalid OpenAPI documentation, which is breaking code generation completely.

### Steps to reproduce the behavior

1. `yarn create strapi-app my-project --quickstart`
2. `cd my-project`
3. `yarn strapi install documentation`
4. `yarn develop`
5. Generate documentation

### Expected behavior

1. Generate valid JSON Schema objects in responses
2. Generate valid paths.

### Code snippets

Taken from the generated `full_documentation.json`:

```jsonc
"/users-permissions/roles": {
      "get": {
        ...
      },
      "post": {
        "tags": [
          "Users-Permissions - Users & Roles"
        ],
        "summary": "Create a role",
        "requestBody": {
          "$ref": "#/components/schemas/Users-Permissions-RoleRequest"
        },
        "responses": {
          "200": {
            "description": "Returns ok if the role was create",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ok": {
                      "type": "enum",
                              ^^^^^^
                      "enum": [
                        true
                      ]
                    }
                  }
                }
              }
            }
          },
          "default": {
            ...
          }
        }
      }
    }
```

As I understand from the OpenAPI spec, the `properties` of a response's content is supposed to be a valid JSON Schema object, which does not have an `enum` type. `openapi-typescript-codegen` does not seem to understand this and produces completely invalid code from this.

I am guessing that this should probably be a `boolean` type instead?

The second thing is one path that seems invalid to me:

```jsonc
    "/connect/(.*)": {
              ^^^^
      "get": {
        "tags": [
          "Users-Permissions - Auth"
        ],
        ...
      }
    }
```

I might be wrong about this one, but (.*) does not look valid to me in a path. (At least the code generator gets very confused over this and generates invalid code.)

### Additional context

I was looking to work around this by disabling the plugins that cause the problem via `settings.json` (without success) and found this related issue: https://github.com/strapi/strapi/issues/13808. Any other workaround would be highly appreciated! :)

**Comment by christian-reichart** [comment]
Same issue here. Also noticed an issue with the date-time types:

```
      "Users-Permissions-Role": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "createdAt": {
            "type": "datetime"
          },
          "updatedAt": {
            "type": "datetime"
          }
        }
      },
``` 
I think it should be

```
"createdAt": {
            "type": "string",
            "format": "date-time"
          }
```

**Comment by ndawg** [comment]
Same issue here. This was my workaround, but I'm not sure how valid it is:
```typescript
const fixDocumentation = (json: any) => {
    // Remove all properties that have a type of enum
    jp.apply(json, '$..[?(@.type=="enum")]', (data: any) => {
        return {
            type: "boolean"
        }
    })

    // Remove the `connect` endpoint which results in a malformed function name
    delete json["paths"]["/connect/(.*)"];

    return json
}
```

**Comment by sjoukedv** [comment]
+1

Generating valid (Open)API specification for a backend framework is absolutely a necessary feature in comparison to competitors.

**Comment by cf-ts** [comment]
Hi there, the error lies in the user-permission plugin, the following file is incorrect: /node_modules/@strapi/plugin-users-permissions/documentation/content-api.yaml
But even with these wrong types corrected one error remains in the full_documentation, I think it comes from another source: "Structural error at components.schemas.Error.properties.data.oneOf.1.items should be object Jump to line 67"  
Here the items of "type: array" are described with "items: []", which is wrong, "items" has to be an object, with types and so on... Maybe it would be great to use a validator like this one https://editor.swagger.io/ in development! I have created a PR: https://github.com/strapi/strapi/pull/14863

**Comment by JacobGalati** [comment]
I think I'm running into a related issue. It appears that single content types have the wrong response schema.
If I create a single type named "Example", `full_documentation.json` will include:
```json
"ExampleListResponse": {
  "properties": {
    "data": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ExampleListResponseDataItem"
      }
    },
    "meta": {
      "type": "object",
      "properties": {
        "pagination": {
          "properties": {
            "page": {
              "type": "integer"
            },
            "pageSize": {
              "type": "integer",
              "minimum": 25
            },
            "pageCount": {
              "type": "integer",
              "maximum": 1
            },
            "total": {
              "type": "integer"
            }
          }
        }
      }
    }
  }
},
```
And when viewing the documentation you can see the example 200 response is 
```json
{
  "data": [
    {
      "id": 0,
      "attributes": {
        "createdAt": "2022-11-28T22:18:37.668Z",
        "updatedAt": "2022-11-28T22:18:37.668Z"
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 0,
      "pageSize": 25,
      "pageCount": 1,
      "total": 0
    }
  }
}
```

But the actual response is 
```json
{
  "data": {
    "id": 1,
    "attributes": {
      "createdAt": "2022-11-28T21:12:56.121Z",
      "updatedAt": "2022-11-28T21:57:34.231Z",
    }
  },
  "meta": {}
}
```
in which data is an object and not an array.

Additionally in the `paths` schema `populate` parameter does not allow for multiple fields as shown in [the developer docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#component-dynamic-zones). The example shows that it accepts a string or an array of strings, but the generated schema only accepts a string.

**Comment by joshuajeschek** [comment]
I encountered the same errors:
1. `enum` instead of `boolean`
```diff
- "type": "enum",
+ "type": "boolean",
"enum": [
  true
]
```
2. `type: datetime` instead of `type: string; format: date-time`
```diff
- "type": "datetime"
+ "type": "string",
+ "format": "date-time"
```
This is quite important to me, since I am using [OpenAPITools/openapi-generator](https://github.com/OpenAPITools/openapi-generator) to automatically generate a typescript client for my CMS, and it doesn't work with a faulty spec.
