### ISSUE TITLE
Media modal doesn't show the folder in the "Location"

### ISSUE THREAD

**Issue by Sija** [strapi/strapi#13887]
### Required System information

- Node.js version: v16.16.0
- Strapi version: v4.3.0

### Describe the bug

When opening Media Details modal from the linked `media` field, the _Location_ field shows `Media Library` instead of the folder that the file resides in.

### Steps to reproduce the behavior

1. Move the asset `X` to the folder `Y`
2. In Content Manager go to the model with the `media` field
3. Select the asset `X` to be used in above-mentioned `media` field
4. Save the model
5. Click _edit_ icon on the selected media
6. Observe that the _Location_ field is showing `Media Library` instead of `Y`

### Expected behavior

I'd expect to see the folder `Y` selected in the _Location_ field.

### Screenshots

<img width="399" alt="image" src="https://user-images.githubusercontent.com/988/181527777-7f1fef48-5fce-4ae5-adff-c3aa700f0d97.png">

**Comment by yulafezmesi** [comment]
same here

**Comment by rustyy** [comment]
In addition, it leads to unintended behavior, as clicking "Finish" on the media overlay will move the asset back to media root.

**Comment by ronronscelestes** [comment]
hi, thank you for highlighting this issue - indeed we should show the current location!
we are currently missing folder information for the asset when requesting the value of media fields - we will open a PR to fix this quickly :)
