### ISSUE TITLE
Strapi does not accept updated image size when resizing it manually on upload

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#13883]
### Required System information

Required System information
Node.js version: 16
Strapi version: 4.3.0
Database: Postgress
Operating system: MacOS

### Describe the bug

We are resizing our images to a max width of 4096 before uploading them.
When doing that the image gets resized correctly, but Strapi doesn't update the images width and height even though we pass the correct values to it.

### Steps to reproduce the behavior

1. Upload an image and resize it beforehand
2. Check the image size in the image library. It should be the same as before.
3. Open the image. The real image size should vary from what Strapi shows you.

### Expected behavior

Strapi should accept our image width and height as the new sizing values.

### Screenshots

A screenshot of the image library:
![Bildschirmfoto 2022-07-28 um 12 19 36](https://user-images.githubusercontent.com/45072099/181483430-e6f6e618-bf38-4e88-9fd6-5826a47bf7f7.png)

The original image:
![placeholder_large](https://user-images.githubusercontent.com/45072099/181483470-a2de0039-21e9-460c-9fe3-d28a7a0dd291.png)

The resized image:
![placeholder_large_171145088b171705f5d7c229180af248](https://user-images.githubusercontent.com/45072099/181483484-d4206a3c-ffa1-497f-a4b0-0755b0ad5632.png)

### Code snippets

```ts
const upload = (file, customParams = {}) =>
      new Promise<void>(async (resolve, reject) => {
        // Upload file to S3 bucket
        const path = file.path ? `${file.path}/` : '';

        // We are generating our own hash here
        const hash = hasha.fromFileSync(file.stream.path, { algorithm: 'md5' });
        file.hash = file.name.replace(file.ext, '') + '_' + hash;

        let resizedImageStream: fs.ReadStream;

        if (file.tmpWorkingDirectory && (file.width > MAX_SIZE || file.height > MAX_SIZE)) {
          // Resize the image before uploading
          sharp.cache(false); // Disable cache usage
          const filePath = join(file.tmpWorkingDirectory, file.hash);
          const inputBuffer = await fsAsync.readFile(file.stream.path);
          const info = await sharp(inputBuffer)
            .resize({ width: MAX_SIZE, height: MAX_SIZE, fit: 'inside', withoutEnlargement: true })
            .avif({ lossless: true })
            .heif({ lossless: true })
            .jp2({ lossless: true })
            .jpeg({ quality: 100 })
            .tiff({ quality: 100 })
            .webp({ lossless: true })
            .toFile(filePath);

          // This does not seem to work, Strapi keeps it's original width and height
          file.width = info.width;
          file.height = info.height;
          file.size = 20494 / 1000;
          resizedImageStream = fs.createReadStream(filePath);
        }

        S3.upload(
          // @ts-expect-error (we already set the Bucket property in `config/plugins.ts`)
          {
            Key: `${path}${file.hash}${file.ext}`,
            Body: resizedImageStream ? resizedImageStream : file.stream,
            ACL: 'public-read',
            ContentType: file.mime,
            ...customParams,
          },
          (err, data) => {
            if (err) {
              return reject(err);
            }

            // Set the URL with CDN base url
            file.url = `${process.env.CDN_BASE_URL}/${data.Key}`;

            resolve();
          }
        );
      });
```

**Comment by Marc-Roig** [comment]
I proposed a solution (https://github.com/strapi/strapi/pull/13930) that maintains the correct image size when you resize it using an upload provider like yours.
The size of the image was being overridden with the initial width & height values. 

I have to note that, resizing images in the upload provider, can potentially bring some issues if you are using responsive image formats.

When uploading an image, if you are using the responsive image formats (described here how to configure them  https://docs.strapi.io/developer-docs/latest/plugins/upload.html#configuration) ,  multiple images with different width&heights are generated/uploaded. If you do the resizing in the upload provider,  you will be resizing the responsive format images too.

But, for your use case (setting a max value for the width and height), this should not be a problem.
