### ISSUE TITLE
File hash not updating when replacing a image in the image library

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#13882]
### Required System information

- Node.js version: 16
- Strapi version: 4.3.0
- Database: Postgress
- Operating system: MacOS

### Describe the bug

When replacing an image with an image with different data the `hash` of the image doesn't change.

### Steps to reproduce the behavior

1. Upload an image to the image library
2. Open it and check the hash in the filename
3. Replace that image
4. Check the filename of the new image. It should be the same.

### Expected behavior

The hash of the image should correspond with the image data. Identical images should have the same hash.

### Additional context

We are using a custom upload plugin to upload our files to a S3 bucket (maybe that is related) and habe to generate our own hashes now.

**Comment by WalkingPizza** [comment]
This is tricky!

When using the `local` provider, the image's hash – which is just a random 5-character string and is not related in any way to the image's content, is actually appended to the filename to generate the URL at which the image is retrievable.

If the hash were to change, the URL would too, implying that you are not technically replacing the image, but rather deleting the old one and creating a new entry entirely.

Just out of curiosity, are you using hashes to prevent duplicate files from being uploaded to S3?

**Comment by AdrianFahrbach** [comment]
> Just out of curiosity, are you using hashes to prevent duplicate files from being uploaded to S3?

We are using hashes to "detect" file changes on the client.
Our site is statically generated and images are cached (hard). So in our case only if the hash / the url of the image changes, the client sends a requests.

**Comment by derrickmehaffy** [comment]
This isn't really a bug but more of an enhancement. The current logic is intended.

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/developer-experience/p/change-file-hash-when-replacing-image
