### ISSUE TITLE
Add database reset command to CLI

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1388]
**What is the expected behavior?**
Add database reset command to CLI

In Meteor.js we have a useful command called `meteor reset` in CLI. It's a simple clean database command and very useful in development process (when you break many thing and want to start from a fresh state). I think it also can be useful for Strapi community. For example as `strapi reset` :thinking:

**Comment by derrickmehaffy** [comment]
@mnlbox there is an issue that directly relates to this, the plan is go a little farther than this.

Here: https://github.com/strapi/strapi/issues/1114

See the discussion between me and @Aurelsicoko at the bottom.

**Comment by Aurelsicoko** [comment]
I think we should continue the discussion in the other issue #1114. I'm closing this one, but I keep it in mind. It could be very useful!

**Comment by sebbean** [comment]
this seems great for when you're just gettin goin

i just messed up my db and not sure how best to go about fixing it without starting completely from scratch
