### ISSUE TITLE
Creating collections with existing table names can cause the entire system to crash.

### ISSUE THREAD

**Issue by pbrn46** [strapi/strapi#13893]
### Required System information

- Node.js version: 14.19.3
- NPM version: 7.16.0
- Strapi version: 4.3.0
- Database: Sqlite
- Operating system: Windows 10 64-bit

### Describe the bug

When creating a collection using the admin Content-Type builder, one can erroneously create a collection having the same name as an existing table. This will effectively nuke the existing table and cause unexpected errors and the inability to restart the server.

### Steps to reproduce the behavior

1. Create a collection using the Content-Type Builder called "Admin Role". The system will try to generate a plural table name called `admin_roles`.
2. Restart the server.
3. Errors emitted as the expected internal table structure has been modified.

### Expected behavior

The system should either continue on merrily, distinguishing the user-created table from the built-in ones, or should throw a soft error to the user preventing overwriting of the table.

### Additional context

A possible solution could be to have user tables prefixed instead? Distantly related to #5080

**Comment by kasonde** [comment]
@pbrn46 thanks for the report. i'm not quite sure prefixing tables will work here. I think having a list of protected table names and checking against that could be great. If I'm not mistaken, you can still edit table names in the schema.json generated by strapi and break your app by accident (if you don't know about the important admin tables). 

Which by the way I just found out restarts the application and generates two separate tables.

**Comment by kasonde** [comment]
![image](https://user-images.githubusercontent.com/13610895/184245077-6b7a6175-b322-40e0-9ae6-45ef050c238b.png)
Like this

**Comment by Eventyret** [comment]
@jhoward1994 A variation of this issue has re-occurred here https://github.com/strapi/strapi/issues/16092

**Comment by derrickmehaffy** [comment]
Going to merge this one into https://github.com/strapi/strapi/issues/16222 as they are related and we could solve the issue by preventing certain content-type names or attribute names from being used
