### ISSUE TITLE
Upload component does not display pictures after saving

### ISSUE THREAD

**Issue by boxcc** [strapi/strapi#13894]
### Required System information

- Node.js version: v14.19.3
- NPM version: 6.14.17
- Strapi version: 4.3.0
- Database: sqlite
- Operating system: macOS Monterey 12.4

### Describe the bug

I created a demo using "strapi-starter next-corporate", but found that "content-manager > Page > Home > contentSections > Feature columns group > features > icon" always disappears after saving

![121659063038_ pic](https://user-images.githubusercontent.com/11386943/181675096-7b7c67e8-3f68-4ad9-816c-df91c043aa0a.jpg)

data actually exists

![131659063101_ pic](https://user-images.githubusercontent.com/11386943/181675109-66550e96-c92b-4dac-bc03-2f5691a5e958.jpg)

### Steps to reproduce the behavior

1. Run ```yarn create strapi-starter my-project next-corporate```
2. Go to 'content-manager > Page > Home > contentSections > Feature columns group'
3. Open any "features" field
4. See the error (icon field doesn't show the picture it should)

### Expected behavior

Can display saved data normally

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/11955
