### ISSUE TITLE
App crash after restart when create field named ID in new collection

### ISSUE THREAD

**Issue by alexarcherr** [strapi/strapi#13890]
### Required System information

- Node.js version: v16
- NPM version: 8.11.0
- Strapi version: 4.3.0
- Database: 
- Operating system: MacOS 12.4

### Describe the bug

If try to create field with name 'ID' and type 'UID' while creating new Collection (I know its dumb, but...), then app crash continuously while restarting. 

### Steps to reproduce the behavior

1. Create demo project with command 'npx create-strapi-app@latest my-project' -> Quickstart
2. yarn install
3. npm run develop
4. Create any admin account
5. Create a collection type with any name
6. Select a field for your collection type - choose 'UID'
7. Name set to 'ID'
8. Click 'Save'
9. Get 'The restart is taking longer than expected' on screen and stacktrace in console. Manual restart didn't help, system has been broken.

### Expected behavior

I expected to get an error on my incorrect actions.

### Screenshots
<img width="676" alt="Screen Shot 2022-07-28 at 22 41 02" src="https://user-images.githubusercontent.com/11070395/181623587-303f3e5f-3a22-4350-b7cb-96b753b7f7e0.png">

<img width="870" alt="Screen Shot 2022-07-28 at 22 35 12" src="https://user-images.githubusercontent.com/11070395/181623303-840442c0-10cc-4795-a242-a2dd5ca1c1ee.png">
<img width="692" alt="Screen Shot 2022-07-28 at 22 28 05" src="https://user-images.githubusercontent.com/11070395/181623354-8323196e-5c0d-4fc6-a9da-bb58196237f0.png">

**Comment by derrickmehaffy** [comment]
This should be a blocked name, workaround is to name it something other than ID as we won't allow this name to be reused.

The "fix" here is to prevent someone from adding a new field named ID

**Comment by SAG33** [comment]
I've a similar problem with the Id field. By default in Strapi v.3 (tested by 3.6.8.), in postgresql db Strapi creates primary key is interger-type field but in externaldb primary key is uuid-type field. For connection with external db I cannot setting related tables - the created relationship is simply not saved when creating a new record. 
I haven't found a quality solution to this problem yet.

**Comment by derrickmehaffy** [comment]
We don't support non-integer based primary keys currently.

**Comment by SAG33** [comment]
> У меня аналогичная проблема с полем Id. По умолчанию в Strapi v.3 (протестировано 3.6.8.), в postgresql db Strapi создает первичный ключ в поле типа interger, а в externaldb первичным ключом является поле типа uuid. Для соединения с внешней базой данных я не могу установить связанные таблицы - созданная связь просто не сохраняется при создании новой записи. Все потому, что я не могу получить первичный ключ записи таблицы. Я еще не нашел качественного решения этой проблемы.

So far, I had to create a new "id" column in each table of the external database and set the primary key of the table to it.

**Comment by SAG33** [comment]
First letter capitalize or word UpperCase name of table in v.4.3.2 is a big problem for my project. First connection tables dropping  fuction also very sad.
In v.3.6.8. I was able to connect my external DB without problem (only change primary_key column from uuid-type to interger)

**Comment by derrickmehaffy** [comment]
Currently we do not support using external non-strapi created/managed DBs within Strapi (at least not as the primary DB).

As this is an unsupported use-case I'll go ahead and mark this issue as closed. If you would like to open a feature request please feel free on https://feedback.strapi.io
