### ISSUE TITLE
Cloudinary-provider does not respect sizeLimit in providerOptions

### ISSUE THREAD

**Issue by Jonashr** [strapi/strapi#13895]
### Describe the bug
@/strapistrapi: 4.3
@/strapi/provider-upload-cloudinary: 4.3.0

Because of the 10mb limit on Cloudinary uploads we have been trying to set a max sizeLimit for uploads in the media library. When we upload a file that is more than 10mb, it causes the application to trash.

By setting the following config in /config/middlewares.js file, we are able to get it working in local environment:

```
  {
    name: "strapi::body",
    config: {
      formidable: {
        maxFileSize: 5 * 1024 * 1024, // multipart data, limit the size to 5mb.
      },
    },
  },

```

When we try to upload a file that is more than 5mb we get the following error-message:
The uploaded file exceeds the maximum allowed asset size.

<img width="868" alt="Screenshot 2022-07-29 at 13 34 23" src="https://user-images.githubusercontent.com/8199791/181703000-51d713b6-de17-43f3-8a10-21281f36cf8d.png">

When deployed, this does not work. It still accepts files over 5mb. So back to the documentation, in this section it describes that you can also set the sizeLimt in the **providerOptions** in the plugins.js file.

The plugins.js file looks like this.
```
module.exports = ({ env }) => ({
  upload: {
    config:{
      provider: 'cloudinary',
      providerOptions: {
        cloud_name: env('CLOUDINARY_NAME'),
        api_key: env('CLOUDINARY_KEY'),
        api_secret: env('CLOUDINARY_SECRET'),
        sizeLimit: 5 * 1024 * 1024
      },
      actionOptions: {
        upload: {
          folder: env('CLOUDINARY_FOLDER'),
        },
        delete: {},
      },
    },
  },
  'users-permissions': {
    config: {
      jwtSecret: env('JWT_SECRET')
    }
  }
});
```

So we deploy, and try again. Validation still does not work, the application crashes and we have to restart the app again. Are we missing something or is this a bug ? It seems like other users have experienced similar bug in the past, but with no solution.

### Additional Context
- Backend is hosted on Heroku.

**Comment by WalkingPizza** [comment]
Looking at the Cloudinary upload provider, it looks like the Strapi server does not check for the file's size at all, but instead checks whether it is okay for Cloudinary by expecting a very precise error when it is not.

https://github.com/strapi/strapi/blob/5ef019318cf441c8aa30c9ec873500151c80bec8/packages/providers/upload-cloudinary/lib/index.js#L31-L33

If my assumptions are correct, it looks like `sizeLimit` is ignored when using Cloudinary.

**Comment by derrickmehaffy** [comment]
Normally throwing errors should not crash the application it should just be returning the error to the "user"

Indeed it looks like since the provider had a proper error message and specific limitations we are using their error which is good but we should also take into account the user wanting to set a maximum limit that might be below the providers limit.

**Comment by derrickmehaffy** [comment]
For the PM who reviews this issue there is two parts to it:

- Fixing the bug of the application crashing due to the error being thrown
- An enhancement to add in support to limiting the file size

Either this issue should not be closed unless both of these are covered or the enhancement needs to be in a new issue.

**Comment by WalkingPizza** [comment]
> First of all, thank you for highlighting this issue @Jonashr. It seems, providers other than local, do not have the sizeLimit config implemented.
> 
> I will be working on this during the following days.
> 
> One thing that I can not reproduce is, the strapi:body maxFileSize config not working. You mention, that when deployed, it stops working for you. Could you specify how are you deploying it? I am not able to reproduce it and that config works for me, in development and production environments.

Hey @Marc-Roig,

I submitted a PR to implement the `sizeLimit` parameter in Cloudinary and S3, you can check it out here: #14047.
Let me know what you think of it.

Have a great weekend!
