### ISSUE TITLE
afterFindOne Lifecycle infinite loop

### ISSUE THREAD

**Issue by maeng2418** [strapi/strapi#13897]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.3.0
- Database: sqlite3
- Operating system: Mac OS M1

### Describe the bug

I have wanted to make a view counter. For Example, After Someone tried to request a GET API of post with specific id, the post's view increase +1.
So, I create a file "src/api/post/content-types/post/lifecycles.ts"
and I wrote code like this...
```
module.exports = {
  async afterFindOne({ result }) {
    try {
      await strapi.query("api::post.post").update({
        where: {
          id: result.id,
        },
        data: {
          view: result.view + 1,
        },
      });
    } catch (err) {
      console.log(err);
    }
  },
};
```

After Running, When I trigger a API, the lifecycle method running infinitely...

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
