### ISSUE TITLE
Latest docker image of strapi/strapi point to version 3.6.8

### ISSUE THREAD

**Issue by mariushosting** [strapi/strapi#13891]
Latest docker image of strapi/strapi point to version 3.6.8
https://github.com/strapi/strapi/releases/tag/v3.6.8

this should be version 4.3.0
https://github.com/strapi/strapi/releases/tag/v4.3.0

I'm missing something?

**Comment by derrickmehaffy** [comment]
We are not currently building v4 docker images as we do not recommend our images for production use anyway. We are planning to write detailed documentation this quarter for how to build your own containers which is our recommended best practice.

If you would like to quickly generate dockerfiles for your project please see this community project here:

https://github.com/strapi-community/strapi-tool-dockerize

And please feel free to share feedback on docker related topics on the feedback page here: https://feedback.strapi.io/developer-experience/p/strapi-v4-docker-image


As this is not a bug report for Strapi itself I'm setting this issue as closed and locking it.
