### ISSUE TITLE
Editor and Author roles are denied permissions to access Media Library

### ISSUE THREAD

**Issue by treighmawaka** [strapi/strapi#13892]
### Describe the bug

It is currently not possible for admin panel users with Author or Editor roles to access the Media Library.  I was previously faced with issue  #12417 (those same users being denied permission to access the Content Manager). As suggested in the fix,  I was able to resolve the main content permissions problem by truncating the `admin_permissions` and `admin_permissions_role_links` tables. Now, however, the Media Library is no longer available to those two admin roles.

### Steps to reproduce the behaviour

1. Log in as a user with Author or Editor role and create a new Collection Type containing a media field.  A permission error should appear.

### Expected behavior

An admin user with Author or Editor role should be able to manage media assets using the Media Library.

### Screenshots

<img width="1219" alt="Screen Shot 2022-07-28 at 5 52 09 PM" src="https://user-images.githubusercontent.com/92684310/181648864-ad935555-e677-40c2-ab85-2fcd04058513.png">

### Additional context

When the permissions denied modal is in view for about 10 seconds, the admin panel goes completely white as seen here:
<img width="1439" alt="Screen Shot 2022-07-28 at 5 53 24 PM" src="https://user-images.githubusercontent.com/92684310/181648868-8e44f75e-6889-4852-b40c-68587dad6a4e.png">

Here's a log of errors found in the console:
[admin-panel-1659046748673.log](https://github.com/strapi/strapi/files/9214642/admin-panel-1659046748673.log)

### System information
- Node.js version:  v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.3.0
- Database: PostgreSQL 12
- Operating system: macOS Big Sur

**Comment by treighmawaka** [comment]
@gu-stav as seen in the attached screen cast, I've just tested `4.3.4` locally and on a staging build, but the issue persists.  Can you please give it another look?

https://user-images.githubusercontent.com/92684310/184163352-fb841302-d03d-46ad-8334-a03f87823189.mp4

**Comment by gu-stav** [comment]
@treighmawaka To me it looks like as if the current user doesn't have permissions to access the media library (which is why it is not displayed in the left menu). Can you double-check if your user has "Access" permissions:

<img width="1507" alt="Screenshot 2022-08-12 at 15 23 25" src="https://user-images.githubusercontent.com/2244375/184362775-ab7c0203-9a41-470e-99de-b0fdf0e6d4f7.png">

**Comment by treighmawaka** [comment]
@gu-stav good call! I see no access permissions there. How do I add/update them?
![strapi-permissions](https://user-images.githubusercontent.com/92684310/184368724-ee64ce1d-7996-4168-867e-aa3d990fd14f.jpg)

I get the following modal when I click the `settings` button.
<img width="1440" alt="Screen Shot 2022-08-12 at 9 59 16 AM" src="https://user-images.githubusercontent.com/92684310/184369140-3b37b7e7-70ae-4b90-b78e-089f5d3920aa.png">

**Comment by derrickmehaffy** [comment]
> @gu-stav good call! I see no access permissions there. How do I add/update them?
> ![strapi-permissions](https://user-images.githubusercontent.com/92684310/184368724-ee64ce1d-7996-4168-867e-aa3d990fd14f.jpg)
> 
> I get the following modal when I click the `settings` button.
> <img width="1440" alt="Screen Shot 2022-08-12 at 9 59 16 AM" src="https://user-images.githubusercontent.com/92684310/184369140-3b37b7e7-70ae-4b90-b78e-089f5d3920aa.png">
> 
> 

That looks like your permissions was corrupted because thats a permission we add to the default roles 🤔

**Comment by treighmawaka** [comment]
@gu-stav ah that makes sense. Can you please point me to a quick fix?

**Comment by gu-stav** [comment]
Mh I don't, but maybe @derrickmehaffy has an idea?

**Comment by treighmawaka** [comment]
Sorry I meant to ping @derrickmehaffy. Any thought?

**Comment by derrickmehaffy** [comment]
I mean short answer is they can't because RBAC blocks them so the only way would be directly in the database.

Perso5i don't really see why we block users from controlling access to plugins myself.

**Comment by treighmawaka** [comment]
> I mean short answer is they can't because RBAC blocks them so the only way would be directly in the database.
> 
> Personally I don't really see why we block users from controlling access to plugins myself.

Thanks. At this stage, I don't mind manually touching the database. Kinda desperate if you see what I mean. Do you know which tables I need to modify?

**Comment by derrickmehaffy** [comment]
> > I mean short answer is they can't because RBAC blocks them so the only way would be directly in the database.
> > 
> > Personally I don't really see why we block users from controlling access to plugins myself.
> 
> Thanks. At this stage, I don't mind manually touching the database. Kinda desperate if you see what I mean. Do you know which tables I need to modify?

I don't remember off the top of my head but I believe it should be something like `strapi_permissons`.

I've stepped away from my computer for a few minutes and am on my phone but as soon as I get back I'll double check.

**Comment by derrickmehaffy** [comment]
The two tables that matter here are `admin_permissions` and `admin_permissions_role_links`

The former sets the permission nodes uploadand the latter assigns those permission nodes to the role.

![image](https://user-images.githubusercontent.com/8593673/184409245-fc75a029-25a2-45a1-aa16-9944fdbf2307.png)

![image](https://user-images.githubusercontent.com/8593673/184409462-fc8acd98-e0e3-4e9f-87ee-16728a5997ec.png)

As you can see here all the roles have their own permission nodes (for a reason called conditionals) so you would need to see if these permission nodes exist in your DB (if not create them) and then see if the node to role link exists (it won't or they would have the permission) so you need to create this also.

---

My concern is how this happened.

**Comment by treighmawaka** [comment]
@derrickmehaffy it worked! I truly appreciate your help. I too wonder what caused this all to start with, although I suspect truncating the `admin_permissions` and `admin_permissions_role_links` has something to do with this. See my [initial issue](https://github.com/strapi/strapi/issues/13892#issue-1321568847) report above.

Thanks again!

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy it worked! I truly appreciate your help. I too wonder what caused this all to start with, although I suspect truncating the `admin_permissions` and `admin_permissions_role_links` has something to do with this. See my [initial issue](https://github.com/strapi/strapi/issues/13892#issue-1321568847) report above.
> 
> Thanks again!

Quite welcome!

**Comment by tomasmezdej** [comment]
Hi @derrickmehaffy, i have found this issue, but i have problems with setting things up. Problem is lets say i have lets say 3 users.
1. Super admin
2. First Author - this role should manage only their own content
3. Second Author - this role should manage only their own content
In case of content, there is no problem with this, but when i try to access media library it shows modal that i do not have permission rights. I´ve tried to set things up in database like mentioned above but nothins seems to work. Can you please help me or redirect me somewhere i can read about this ?
Thanks

**Comment by TOZXII** [comment]
> Hi @derrickmehaffy, i have found this issue, but i have problems with setting things up. Problem is lets say i have lets say 3 users.
> 
> 1. Super admin
> 2. First Author - this role should manage only their own content
> 3. Second Author - this role should manage only their own content
> 
> In case of content, there is no problem with this, but when i try to access media library it shows modal that i do not have permission rights. I´ve tried to set things up in database like mentioned above but nothins seems to work. Can you please help me or redirect me somewhere i can read about this ?
> 
> condition ["admin::is-creator"] is not working
> 
> Thanks

I got the same problem did you solve it?

Where I want only the creator of that asset to see his own assets not the other assets of other users

**Comment by tomasmezdej** [comment]
> > Hi @derrickmehaffy, i have found this issue, but i have problems with setting things up. Problem is lets say i have lets say 3 users.
> > 
> > 1. Super admin
> > 2. First Author - this role should manage only their own content
> > 3. Second Author - this role should manage only their own content
> > 
> > In case of content, there is no problem with this, but when i try to access media library it shows modal that i do not have permission rights. I´ve tried to set things up in database like mentioned above but nothins seems to work. Can you please help me or redirect me somewhere i can read about this ?
> > condition ["admin::is-creator"] is not working
> > Thanks
> 
> I got the same problem did you solve it?
> 
> Where I want only the creator of that asset to see his own assets not the other assets of other users

No i did not, i contacted support and they know about this issue but there is no ETA on fix.

**Comment by javadbat** [comment]
> The two tables that matter here are `admin_permissions` and `admin_permissions_role_links`
> 
> The former sets the permission nodes uploadand the latter assigns those permission nodes to the role.
> 
> ![image](https://user-images.githubusercontent.com/8593673/184409245-fc75a029-25a2-45a1-aa16-9944fdbf2307.png)
> 
> ![image](https://user-images.githubusercontent.com/8593673/184409462-fc8acd98-e0e3-4e9f-87ee-16728a5997ec.png)
> 
> As you can see here all the roles have their own permission nodes (for a reason called conditionals) so you would need to see if these permission nodes exist in your DB (if not create them) and then see if the node to role link exists (it won't or they would have the permission) so you need to create this also.
> 
> My concern is how this happened.

thank you its worked
