### ISSUE TITLE
Image Preview Disappears After Upload

### ISSUE THREAD

**Issue by Enijar** [strapi/strapi#13900]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.5.5
- Strapi version: 4.1.10
- Database: MySQL
- Operating system: Ubuntu 20.04

### Describe the bug

Uploaded images are not rendered in the preview (see video demonstration).

https://user-images.githubusercontent.com/5284715/181745267-bb88509e-8215-4d4c-8858-eccc95422de5.mp4

There is also no image data returned from the API (see screenshot).

![Screenshot 2022-07-29 at 11 51 03](https://user-images.githubusercontent.com/5284715/181745758-37773b50-6e22-4362-81e8-bb7273ff410a.png)

### Steps to reproduce the behaviour

1. Create a single type with a nested set of components
2. Give one of the nested components an image field
3. Upload an image
4. Image preview shows
5. Click "Save", and the image preview disappears 
6. Refresh the page, and the image preview is empty

### Expected behaviour

Image previews should show.

**Comment by thedanielenrico** [comment]
Any update on this issue? I'm experiencing the same issue with Strapi 4.1.12 (node v14.17.6).

**Comment by petersg83** [comment]
hi @thedanielenrico 
@bolg55 Did you test it with the latest version of Strapi (4.3.4)? I believe it was fixed already

**Comment by derrickmehaffy** [comment]
Marking as closed as this should be fixed in the current latest versions, if the issue comes up again do let us know and we can reopen.
