### ISSUE TITLE
Error when saving many to many relationship

### ISSUE THREAD

**Issue by jeffwsw** [strapi/strapi#1390]
**Informations**
- **Node.js version**: 10.1.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: MongoDB 3.6.4
- **Operating system**: MacOs

**What is the current behavior?**
I'm trying to save a many to many relationship, basically have one "audition" model and I have to add multiple contacts to it (they can appear in other auditions).

When I try to link the contact(relationship) with the audition I get this error in the strapi console.

```
TypeError: strapi.hook.mongoose.manageRelations is not a function
    at Object.add (/Applications/MAMP/htdocs/actorsguru/agapi/api/relationship/services/Relationship.js:52:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2018-06-14T16:17:49.644Z] debug POST /relationship (108 ms)
```

**Steps to reproduce the problem**
This is the code I used to link the two, using the strapi sdk

```
//save relationship
let saved = await STRAPI.createEntry('relationship', this.state.data);
		
// link saved contact to audition
await saved.linkTo(this.state.audition, 'Auditions');
```

**What is the expected behavior?**

The relationship should be saved and linked to the corresponding audition but right now the relation is not created.

**Suggested solutions**

I tried using direct requests with axios instead of the sdk but the behavior is the same.

**Comment by lauriejim** [comment]
Hello @jeffwsw . I don't understand your issue. Can you give me a repo with your code. I don't know how to reproduce your issue .

**Comment by jeffwsw** [comment]
I found some old code was left in the service file from an older version of strapi after some debugging so the error has disappeared.
