### ISSUE TITLE
Updating Admin panel logo fails

### ISSUE THREAD

**Issue by Sija** [strapi/strapi#13906]
### Required System information

- Node.js version: v16.16.0
- Strapi version: v4.3.0

### Describe the bug

I'm getting an error when trying to update the admin panel logo (Settings -> Global Settings -> Overview -> Customization -> Logo).

> menuLogo must be a `object` type, but the final value was: ...

### Steps to reproduce the behavior

1. Go to the Settings -> Global Settings -> Overview -> Customization -> Logo
2. Click on _Change logo_ icon
3. Click on _Choose another logo_ button
4. Select new image
5. Click _Upload logo_ button
6. Click _Save_ button
7. Observe the error

### Expected behavior

Logo is successfully updated.

### Additional context

I'm using S3 upload provider.
Sentry event: https://sentry.io/share/issue/d6a14c62bd1540a48e259653bd4992d3/

**Comment by RedrumIzBak** [comment]
Same error here using Cloudinary as the upload provider.

**Comment by petersg83** [comment]
Duplicate of https://github.com/strapi/strapi/issues/13762
