### ISSUE TITLE
Media Libary reports incomplete asset url with S3

### ISSUE THREAD

**Issue by Maxdola** [strapi/strapi#13909]
### Required System information

- Node.js version: 16.13.0
- NPM version:  8.10
- Strapi version: 4.2.3
- Database: 8.7.3
- Operating system: Kubernetes

### Describe the bug

When I upload a File that is 8MB in size or larger the URL reported in the Media Libary and in the API is incomplete.

### Steps to reproduce the behavior

1. Upload A File in the Media Libary
2. Get The URL of that file via the API or UI.

### Expected behavior

Report the complete URL

### Code snippets

Correct Url:
`
https://XXXXX.compat.objectstorage.eu-frankfurt-1.oraclecloud.com/BUCKET/NAME_af6ea832f9.pdf
`

Reported URL:
`
/BUCKET/NAME_af6ea832f9.pdf
`

The wrong Url is also saved in the Table `files` Column `url`

**Comment by kasonde** [comment]
Hi 👋
This is intended behavior. Ideally, you want to be able to change the source of your media if you change providers as well. The full URL is only automatically concatenated for you on the front-end admin and not for the backend side.

**Comment by Maxdola** [comment]
> Hi 👋 This is intended behavior. Ideally, you want to be able to change the source of your media if you change providers as well. The full URL is only automatically concatenated for you on the front-end admin and not for the backend side.

Hi,
I have to say that is not correct in my case. For Files below 8MB in size, the Full URL is shown in the frontend and also backend. For files larger than 8MB only the path in the provider is shown.

This is an example response from the Strapi API where you can see the difference.

https://gist.github.com/Maxdola/ff92200bde49d73f98bdf0f2774e99c0

**Comment by Marc-Roig** [comment]
Hi, I am reopening the issue! 
If the behavior is different when changing the file size... this is something that needs to be addressed.

I am not able to reproduce the urls being encoded differently for files bigger than 8MB.

What I see is, that for providers (other than local) the URLs are always complete URLs.  I have tried with images and pdfs bigger than 10MB and 1MB. I  still see the full URL in both cases.

Which endpoint have you used to get this response? https://gist.github.com/Maxdola/ff92200bde49d73f98bdf0f2774e99c0

**Comment by Maxdola** [comment]
> the URLs are always complete URLs

Hi, I was using the Pages Endpoint to fetch all Pages.

Some Files I've tested it with are from https://testfiledownload.com I've tested it with 10,5 and 1 MB and ony the 1MB file reported the full URL.

**Comment by Marc-Roig** [comment]
Still unable to reproduce it with those 10, 5 and 1MB files.

Using aws-s3 provider and strapi 4.3.4

```js
[
    {
        "id": 4,
        "createdAt": "2022-08-16T15:27:50.520Z",
        "updatedAt": "2022-08-16T15:27:50.520Z",
        "publishedAt": null,
        "File": [
            {
                //...
                "size": 1048.58,
                "url": "https://strapi-testing-bucket.s3.us-west-2.amazonaws.com/test1_Mb_5b371e75ae.db",
                "previewUrl": null,
                "provider": "aws-s3",
                //...
            },
            {
                //...
                "size": 10485.76,
                "url": "https://strapi-testing-bucket.s3.us-west-2.amazonaws.com/test10_Mb_8127732a55.db",
                "previewUrl": null,
                "provider": "aws-s3",
                //...
            },
            {
                //...
                "size": 5242.88,
                "url": "https://strapi-testing-bucket.s3.us-west-2.amazonaws.com/5_MB_48a663ffe8.zip",
                "previewUrl": null,
                "provider": "aws-s3",
                //...
            }
        ]
    }
]
```

**Comment by Marc-Roig** [comment]
What is your provider config in `config/plugins.js`?

**Comment by Maxdola** [comment]
> ```js
> 2022-08-16T15:27:50.520Z
> ```

Since its only enabled in Production, this is our `config/env/production/plugin.js`:

```
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("S3_ACCESS_KEY"),
        secretAccessKey: env("S3_ACCESS_SECRET"),
        region: "eu-frankfurt-1",
        params: {
          Bucket: env("S3_BUCKET_NAME"),
        },
        s3ForcePathStyle: true,
        endpoint:
          "https://XXX.compat.objectstorage.eu-frankfurt-1.oraclecloud.com",
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
});
```

**Comment by Marc-Roig** [comment]
Thank you! I will continue working with this tomorrow, maybe it has something to do with s3ForcePathStyle / endpoint arguments. 

This is my config now:
```js
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          Bucket: env("AWS_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
```

**Comment by Marc-Roig** [comment]
Actually, as @WalkingPizza pointed in discord, this might be an issue with the way Oracle's S3 Compatibility API work. And may not be related to strapi.

**Comment by derrickmehaffy** [comment]
Indeed I suspect this issuenis on Oracle, not Strapi.

Oracle does not use native S3 but a compatibility layer on top of their storage buckets.

This will likely lead us down the same path as things like AWS Aurora, AWS DynamoDB, IBM DB2, Google BigQuery, AWS Redshift, and Azure Cosmos.

None of these we support, while Strapi **may work** with cloud proprietary options, they are not officially supported.

---

If this issue cannot be replicated on AWS S3 then it's not likely to be one we can/will fix. This also applies to other alternative S3 sources such as DigitalOcean. 

I will mark this issue as closed for now until someone can provide reproductive steps to confirm the issue on AWS S3. (Likewise btw I could not reproduce and I got to the point of upload a 3.2GB iso file and hit no issue to the Strapi internal testing bucket)
