### ISSUE TITLE
Content Manager forbidden / not allowed Bug

### ISSUE THREAD

**Issue by mvrahden** [strapi/strapi#13913]
### Required System information

- Platform: Docker node:16
- Strapi version: 4.3.0
- Database: Postgres

### Describe the bug

1. Given a content-type without any fields and opening the content manager.
The page will return after some processing back to home and display a message `Information: You are not allowed to see this document`.
2. Add a field to that content-type and access the content manager, it will work as expected...
3. Remove all fields, you'll have the bug again.

Within the Network tab of the Developer Tools you'll find a Http Request (`GET http://localhost:1337/content-manager/single-types/api::homepage.about?`) responding with `403 Forbidden` – in this case "About" was the Content-type without fields and it was associated to the API "homepage".

### Expected behavior

I would expect to be able to access the content manager indepent from the Content-Types state. If it is in an invalid state, give a notice. If it is empty, give a notice.  
But don't redirect and give a notice about access restrictions.

I hope this helps you :)

**Comment by alexandrebodin** [comment]
I can't retrace the history but this is fixed the the lastest versions of Strapi :)
