### ISSUE TITLE
Watch mode breaks admin panel on strapi 4.3

### ISSUE THREAD

**Issue by imokya** [strapi/strapi#13915]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.3.0
- Database: mysql 
- Operating system: windows10

### Describe the bug

I was follow the tutorial 'How To Build Plugins in Strapi v4‘ on youtube
I could not access admin panel when using:
yarn develop --watch-admin

instead I have to rebuild using 'yarn build' to refresh the plugin page

it gives me this error: 
{"data":null,"error":{"status":404,"name":"NotFoundError","message":"Not Found","details":{}}}

**Comment by WalkingPizza** [comment]
The `watch-admin` flag starts the Strapi instance on port `8000` instead of port `1337`.
So, instead of accessing `http://localhost:1337/admin`, you should access `http://localhost:8000/admin`.

**Comment by bis0072** [comment]
it is breaking in production also. nginx, Operating system: ubuntu 20.04. node 16.13.0, Strapi version: 4.3.0, Database: pg

**Comment by imokya** [comment]
@WalkingPizza I didn't notice that. It works thank you.
