### ISSUE TITLE
Same result appears on 2 pages

### ISSUE THREAD

**Issue by hkmute** [strapi/strapi#13916]
### Required System information

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.2.3
- Database: postgres
- Operating system: MacOS

### Describe the bug

When the sorted field has the same value in multiple entries, and the entries appear in different pages, some entries will appear in both page. There are also cases where an entry will be skipped.

### Steps to reproduce the behavior

1. Create a collection with a text field
2. Create a few entries with same value
3. Create a few entries with other values
4. Sort the result according to the text field
5. Ensure entries of the same value are separated in 2 pages

### Expected behavior

Same entry should appear only once in pagination

### Screenshots
id: 7 appearing in 2 pages
<img width="902" alt="image" src="https://user-images.githubusercontent.com/54314549/182027047-0f144ddb-34e0-400c-863d-4cdc3c08861e.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/54314549/182027067-2153ee0d-7c27-416f-94a1-0a1dc6b61138.png">

**Comment by bolg55** [comment]
Given the steps to reproduce, I am not able to reproduce this. Would you be able to make a quick video? That would be helpful. Thanks

**Comment by hkmute** [comment]
There seems to be some extra conditions to trigger this issue other than just have same data across 2 pages, but I can't figure it out exactly.

You can check the end of the videos for the final results.

ID 3 on page 1 and 2
ID 4 disappeared
https://drive.google.com/file/d/1-V2pKjQ4q8EiStpgjp2J7LSOQc3cvUHu/view

ID 10, 11, 12, 13, 14, 15 on page 1 and 2
https://drive.google.com/file/d/1pPhAmwZhthivqrzinVc5_-k7Zg1SiwdT/view

**Comment by derrickmehaffy** [comment]
This is largely going to be up to the default ordering response from the database, all we can do is "ask the database" to order the information and it will respond with the information.

I also cannot reproduce this but I also don't see how we can fix this either if there is a problem :thinking:

**Comment by hkmute** [comment]
I found that this issue could possibly be resolved by add id as an additional sorting params, like &sort=name:ASC&sort=id:ASC.

As I am facing the same issue when calling REST API to get strapi content, I am not sure whether this can be handled within strapi or I will have to add an additional sorting params for all the APIs.

**Comment by derrickmehaffy** [comment]
> I found that this issue could possibly be resolved by add id as an additional sorting params, like &sort=name:ASC&sort=id:ASC.
> 
> As I am facing the same issue when calling REST API to get strapi content, I am not sure whether this can be handled within strapi or I will have to add an additional sorting params for all the APIs.

Adding the additional sort params would be the best method, again we are at the mercy of the database technology behind and how it handles paging. Keep in mind that databases (and strapi itself) are not context aware of previous queries. A request is made, a query happens, and a response is provided. All history of this action is gone when the next cycle happens.
