### ISSUE TITLE
Collection Type relation field in darkmode background and field label has same color

### ISSUE THREAD

**Issue by MohamedSonata** [strapi/strapi#13912]
- Node.js version:16.3

- Strapi version:4.3.0

- Operating system:windows

### Describe the bug

The Problem In Collection types with Relation fields in dark mode the entries seen by white color and background also had white color 
it's need to change for black and background too 

### Screen Shot:
https://user-images.githubusercontent.com/96669613/181920402-472562f5-4e02-46b1-a0d0-1985b2fb9af4.png

**Comment by HarleySalas** [comment]
I also came here to open an issue for this. Really would like to be able to enjoy darkmode :P

**Comment by WalkingPizza** [comment]
What browser are you using?

**Comment by MohamedSonata** [comment]
I'm using Firefox this problem comes after upgrade to 4.3.0 version
