### ISSUE TITLE
custom server hooks not working

### ISSUE THREAD

**Issue by routayush1** [strapi/strapi#13927]
Hi Guys
Hope you guys are doing well

As I have implemented custom hook in my strapi , Its not working ,nothing is showing in terminal ,I can not able to get the problem.
Can you please help

**Comment by Meljesson** [comment]
I suggest you describe more in detail or visit the discord channel for more help at https://discord.com/channels/811989166782021633/841755530007805983

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by routayush1** [comment]
https://forum.strapi.io/t/strapi-hooks-use-cases/2001/7?u=ayush_kumar_rout

Hello all ,

i am unable to run my custom server hook,can someone please help.

i have my config file in ./config/hook.js
```
module.exports = ({ env }) => ({
  settings: {
   redis: {
      enabled: true,
      db: 0,
      host: env("REDIS_HOST"),
      port: env.int("REDIS_PORT"),
    },
  },
});
```
i have my hook in ./hooks/redis/index.js
```
const Redis = require("ioredis");
module.exports = (strapi) => {
  return {
    async initialize() {
      console.log(" hello it works");    
    },
  };
};
```

it use to work in v3 but in v4 it does not work

**Comment by sauldeleon** [comment]
Can we reopen this?

I cant find anything in the documentation about how to implement server hooks in strapi v4 and the way if is being done in v3 docs does not work for me :(

The above comment is my same problem!

**Comment by derrickmehaffy** [comment]
Hooks in Strapi v4 are not the same as in v3, we have no generalized methods to build hooks into the global API but if you need an example see my redis plugin: https://github.com/strapi-community/strapi-plugin-redis

**Comment by sauldeleon** [comment]
that gave me an idea. Thanks a lot for your time!!
