### ISSUE TITLE
Fails to install required npm packages on a MacBook Pro (13-inch, M2, 2022)

### ISSUE THREAD

**Issue by liammcintosh97** [strapi/strapi#13920]
### Required System information

- Node.js version: v16.16.0
- NPM version:  8.13.2
- Strapi version: 3.6.8
- Database: sqlite3 version 5.0.0
- Operating system: MacOS Monterey version 12.4 running on a MacBook Pro (13-inch, M2, 2022)

### Describe the bug

When I try to install the dependancies I run into the below error...
`npm ERR! code 1
npm ERR! path /Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c /var/folders/43/b5hl16wx4y99c91v0z0vy3m80000gn/T/install6593555736.sh
npm ERR! sharp: Using cached /Users/liamalton/.npm/_libvips/libvips-8.10.6-darwin-arm64v8.tar.br
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.16.0 | darwin | arm64
npm ERR! (node:88491) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/liamalton/.node-gyp/16.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/liamalton/.node-gyp/16.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/liamalton/.node-gyp/16.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp/build/./gyp-mac-tool", line 611, in <module>
npm ERR!     sys.exit(main(sys.argv[1:]))
npm ERR!   File "/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp/build/./gyp-mac-tool", line 28, in main
npm ERR!     exit_code = executor.Dispatch(args)
npm ERR!   File "/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp/build/./gyp-mac-tool", line 43, in Dispatch
npm ERR!     return getattr(self, method)(*args[1:])
npm ERR!   File "/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp/build/./gyp-mac-tool", line 246, in ExecFilterLibtool
npm ERR!     if not libtool_re.match(line) and not libtool_re5.match(line):
npm ERR! TypeError: cannot use a string pattern on a bytes-like object
npm ERR! make: *** [Release/nothing.a] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/liamalton/Documents/Vue/Liams-Website/cms/liams-website/node_modules/sharp
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liamalton/.npm/_logs/2022-07-31T22_10_02_690Z-debug-0.log
liamalton@Liams-MacBook-Pro liams-website % node
`

### Steps to reproduce the behavior

1. Run 'npm install' in the terminal 

### Expected behavior

The required packages should be installed 

### Code snippets

Here is my package.json
`{
  "name": "liams-website",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.6.8",
    "strapi-admin": "3.6.8",
    "strapi-utils": "3.6.8",
    "strapi-plugin-content-type-builder": "3.6.8",
    "strapi-plugin-content-manager": "3.6.8",
    "strapi-plugin-users-permissions": "3.6.8",
    "strapi-plugin-email": "3.6.8",
    "strapi-plugin-upload": "3.6.8",
    "strapi-plugin-i18n": "3.6.8",
    "strapi-connector-bookshelf": "3.6.8",
    "knex": "0.21.18",
    "sqlite3": "5.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "2ef969e5-bc0c-4dd1-833c-69e67c89f39b"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}
`

**Comment by derrickmehaffy** [comment]
Hello,

Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports for v3 unless they could be deemed high or critical severity or related to security in nature.

The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

- [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
- [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
- [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
For now I will mark this issue as closed as we do not believe this issue is Critical/High Severity nor related to security.

Thank You
