### ISSUE TITLE
Add option to allow GraphQL playground in Production

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1392]
**Informations**
- **Node.js version**: v10.4.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: 10.2-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

Currently playground works just fine in Development and Staging, however when using `NODE_ENV=production` the server responds with a 404 Error

**Steps to reproduce the problem**

Setup a project, install the graphQL plugin and start strapi with node_env=production

Attempt to visit http://localhost:1337/playground

**What is the expected behavior?**

playground should still function in production mode.

**Comment by lauriejim** [comment]
Hey @derrickmehaffy it's not an issue.
We chose to disable this plugin in production environment. We wont anyone use it when your app is live.

Code here: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/hooks/graphql/index.js#L125

**Comment by derrickmehaffy** [comment]
@lauriejim I think this is something that should be configurable in options. I understand there is possible dangers of damaging large queries but the same could be said of actually hitting the /graphql endpoint with the same thing.

To me playground is similar to something like swagger, Its a graphql tool you can use to understand the structure of the API and frontend builders would use it to figure out how to build the front end. Specifically if those front end builders are doing so remotely. (IE if your API is public and people outside your influence wish to use it).

Personally I think it should be enabled by default and have the option to disable it, but either way is fine.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko what are your thoughts on this?

**Comment by derrickmehaffy** [comment]
If limits need to be placed on graphQL (configurable ones I would hope) this article might be good read: https://dev-blog.apollodata.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b

**Comment by derrickmehaffy** [comment]
Realistically speaking I believe if a user had playground installed elsewhere you could hit the `yourapihere/graphql` and achieve the same result.

**Comment by derrickmehaffy** [comment]
For instance if you install the local desktop version of playground (in my case on linux mint)

Using the packages listed under the release:https://github.com/prismagraphql/graphql-playground/releases/tag/v1.6.0


I can successfully attach my desktop version of playground to my production API:
![image](https://user-images.githubusercontent.com/8593673/41454398-1f9e1978-702e-11e8-9179-583035b6d95b.png)

**Comment by derrickmehaffy** [comment]
The point I'm making @johannpinson is what if your not the one building the apps lol. Such in the case of the api I'm working on isn't just for consumption of our own apps but anyone to use. I don't see the benefit of security to disable it on production when anyone can use the electron app in the same way?

As I've stated on other issues like this, we shouldn't cripple the power users for the sake of simplicity. Mistakes have to be made to learn from them.

Thus I think at least adding the *option* to enable it on production should be a pretty straightforward example of tools power users can use.

If we look at playground like you would something like swagger, given they are very different in how they look and work with different technology. They are basically a test/debug/auto-documentation tool. If swagger were to implemented like with playground, I would expect swagger would also run on production.

The goal I see here is provide the end user/developer with as many options as we can and to not restrict them if we don't have to. Allow the user to make those choice instead of forcing the choice for them. :smiley:

**Comment by derrickmehaffy** [comment]
I wouldn't want to ask every person who plans on consuming my API/GraphQL to install the electron app. :P

**Comment by derrickmehaffy** [comment]
@johannpinson Thank you sir, I had a little fix in my project to enable it. (My frontend devs were bugging me too much lol)

**Comment by dorny-mb** [comment]
you can also add a config for the Strapi graphql plugin if you want to be explicit that playground should only be available in dev/production by doing something like this in ./config/plugins.js

`module.exports = {
  //
  graphql: {
    playgroundAlways: process.env.NODE_ENV === 'development,
  },
};`

**Comment by dorny-mb** [comment]
you can also add a config for the strapi graphql plugin if you want to be explicit that playground should only be available in dev/production by doing something like this in `./config/plugins.js`

```
module.exports = {
  //
  graphql: {
    playgroundAlways: process.env.NODE_ENV === 'development,
  },
};
```

**Comment by derrickmehaffy** [comment]
> > you can also add a config for the strapi graphql plugin if you want to be explicit that playground should only be available in dev/production by doing something like this in `./config/plugins.js`
> > ```
> > module.exports = {
> >   //
> >   graphql: {
> >     playgroundAlways: process.env.NODE_ENV === 'development',
> >   },
> > };
> > ```
> 
> This is a very misleading comment! You need to nest the config options inside the `config` key as explained here in the [docs](https://docs.strapi.io/developer-docs/latest/plugins/graphql.html#configurations) and it should look like:
> 
> ```
> module.exports = {
>   graphql: {
>     config: {
>       playgroundAlways: true,
>     }
>   },
> }
> ```

That comment was from last year and is valid for Strapi v3, you are on v4 so yes the config you showed is correct for v4 but not v3.

**Comment by v-dimitroff** [comment]
> > > you can also add a config for the strapi graphql plugin if you want to be explicit that playground should only be available in dev/production by doing something like this in `./config/plugins.js`
> > > ```
> > > module.exports = {
> > >   //
> > >   graphql: {
> > >     playgroundAlways: process.env.NODE_ENV === 'development',
> > >   },
> > > };
> > > ```
> > 
> > 
> > This is a very misleading comment! You need to nest the config options inside the `config` key as explained here in the [docs](https://docs.strapi.io/developer-docs/latest/plugins/graphql.html#configurations) and it should look like:
> > ```
> > module.exports = {
> >   graphql: {
> >     config: {
> >       playgroundAlways: true,
> >     }
> >   },
> > }
> > ```
> 
> That comment was from last year and is valid for Strapi v3, you are on v4 so yes the config you showed is correct for v4 but not v3.

Thanks for clarifying this one - I've edited the comment to make it clear where the difference comes from. Most probably people searching for this recently are gonna need a solution for v4.
