### ISSUE TITLE
entityService props ?

### ISSUE THREAD

**Issue by hsnbsst** [strapi/strapi#13929]
hello, in the v4.2.3 version of strapi, when you put a dot after entityService, its sub-features appear. eg " findPage, find vs " .
now when I switch to 4.3.0, they don't come after putting a dot

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.3.0
- Database: mysql

**Comment by derrickmehaffy** [comment]
This is because we removed the normal typescript types from JS projects and is something we plan to address later.

Marking this as closed as it's not really a bug report
