### ISSUE TITLE
Can't start strapi on new Typescript-generated project

### ISSUE THREAD

**Issue by bwyx** [strapi/strapi#13933]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.3.2
- Database: Postgres
- Operating system: Linux 5.17.6-arch1-1

### Describe the bug

Can't run newly generated TypeScript version with the following error:

```sh
error TS18003: No inputs were found in the config file '../projects/my-strapi/tsconfig.json'. Specified 'include' paths were 
'["./","src/**/*.json"]' and 'exclude' paths were 
'["node_modules/","build/","dist/",".cache/",".tmp/","src/admin/","**/*.test.ts","src/plugins/**"]'.
```

### Steps to reproduce the behavior

1. generate new project `npx create-strapi-app@latest my-strapi`
2. Choose `Custom (manual settings)` > preferred language `TypeScript`
3. npm run develop/build

### Expected behavior

TypeScript-generated project should be able to run immediatelly

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I was able to build the project by modifying `tsconfig.json`:

```diff
{
  ...
-  "include": ["./", "src/**/*.json"],
+  "include": ["./src", "./config", "src/**/*.json"],
  ...
}
```

**Comment by boazpoolman** [comment]
Same issue for me on 4.3.2

**Comment by Convly** [comment]
Hey, thanks for taking the time to write this issue.

It's quite interesting that this issue impacts some users but not everyone.

@bwyx Your fix will ignore configuration files though, maybe prefer it smth like `./*` (not sure it'll work though).

I'll play a bit with the different solutions & implement new defaults for the tsconfig includes.

**Comment by Antoine-lb** [comment]
My two cents: I works for me on `4.3.2` 

My Setup:
- macOS Big Sur `v11.6`
- Node `v14.19.1`
- yarn `v1.22.17`

I generated the project with the flag (`--typescript`) and not with `Custom (manual settings)`
e.g.:
```bash
npx create-strapi-app@latest --typescript strapi-ts
```

**Comment by bwyx** [comment]
that's weird, using the `--typescript` flag instead like @Antoine-lb didn't have any issue like this

**Comment by bwyx** [comment]
I think it's just a typescript issue, I'll closed it
