### ISSUE TITLE
Infinite loop while updating content in beforeUpdate lifecycle

### ISSUE THREAD

**Issue by gilson-perfomatix** [strapi/strapi#13931]
### Required System information

- Node.js version: v14.15.4
- NPM version: 6.14.16
- Strapi version: 4.2.0
- Database: Postgres v8.6.0
- Operating system: Ubuntu 18.10

### Describe the bug

While updating content in beforeUpdate lifecycle the same lifecycle is triggered again and again which goes infinite. I am using the following code :
`
const entry = await strapi.db.query('api::some-detail.some-detail').update({
  where: { id: 1},
  data: {
    page_url: 'https://google.com',
  },
});
`

### Steps to reproduce the behavior

1. Execute a beforeUpdate lifecycle which has code to update a record
2. And it calls the same beforeUpdate again

### Expected behavior

It should update once and stop.

**Comment by Meljesson** [comment]
If you're updating the same content with the above code you've shown, meaning, the content you want to run an API update on is the same on this code is on, then you're hitting an infinite loop because you are constantly triggering update and re running this same code on a before update lifecycle.  
[Update this content] -> [Run lifecycle to update this content] -> [Update this content] -> ...

What you should do is update another entry instead of the one you're updating or change it to afterUpdate to run once

**Comment by WalkingPizza** [comment]
If you are updating the same entry that is triggering the `beforeUpdate` lifecycle, you can simply override the data passed in the context that's being passed to the lifecycle function instead of calling the `update` method again.

**Comment by derrickmehaffy** [comment]
See above comments, this isn't something we can prevent as lifecycles wrap the database queries and you are doing an update database query in the lifecycle.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by gilson-perfomatix** [comment]
@WalkingPizza Thanks for the comment! Can you link to an example for the proper way or drop a snipper for the same?

**Comment by WalkingPizza** [comment]
> @WalkingPizza Thanks for the comment! Can you link to an example for the proper way or drop a snipper for the same?

```js
// Suppose you have a URL field you want to set to "https://google.com" automatically every time an entry is updated.

module.exports = {
    async beforeUpdate({ params }) {
        params.data.url = "https://google.com";
   }
}
```

For more information about the `params` object refer to [the Strapi Documentation regarding lifecycle events](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#available-lifecycle-events).
