### ISSUE TITLE
REST API filtering doesn't work

### ISSUE THREAD

**Issue by SitkaCharley** [strapi/strapi#13932]
### Required System information

- Node.js version: v14.15.0
- NPM version: 6.14.8
- Strapi version: 4.2.3
- Database: postgre
- Operating system: Ubuntu 16.04.7 LTS

### Describe the bug

I've created a collection **restaurant** of content type **Restaurant** having only one text field - **name**. Then populated this collection with 2 entries. Entries are published and publicly available.

>
| _name_           
+----------------+
| kfc             
+----------------+
| mcdonalds  

### Steps to reproduce the behavior

1. Go to GET 'http://localhost:1337/api/restaurants?name=mcdonalds'
2. See result - 

> {"data":[{"id":1,"attributes":{"name":"kfc","createdAt":"2022-08-01T14:22:23.629Z","updatedAt":"2022-08-01T14:22:27.832Z","publishedAt":"2022-08-01T14:22:27.830Z"}},{"id":2,"attributes":{"name":"mcdonalds","createdAt":"2022-08-01T14:22:38.104Z","updatedAt":"2022-08-01T14:22:38.852Z","publishedAt":"2022-08-01T14:22:38.850Z"}}],"meta":{"pagination":{"page":1,"pageSize":25,"pageCount":1,"total":2}}}

### Expected behavior

Expected only filtered entries being returned. Like so

> {"data":[{"id":1,"attributes":{"name":"kfc","createdAt":"2022-08-01T14:22:23.629Z","updatedAt":"2022-08-01T14:22:27.832Z","publishedAt":"2022-08-01T14:22:27.830Z"}}],"meta":{"pagination":{"page":1,"pageSize":25,"pageCount":1,"total":2}}}

### Screenshots

![image](https://user-images.githubusercontent.com/21178526/182179687-b303b1ce-e60d-4678-b5ab-f49891399843.png)

**Comment by derrickmehaffy** [comment]
You are using the old v3 filtering syntax, not the v4 one, see: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
