### ISSUE TITLE
Still getting broken images in production after modifiying strapi::security

### ISSUE THREAD

**Issue by Stuhl** [strapi/strapi#13936]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.0
- Database: postgresql
- Operating system: Ubuntu 18.04 (NGINX as webserver)

### Describe the bug
Still getting broken images in **production** even after adding this to my `config/middlewares.js` file:

```
{
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", "https:"],
          'img-src': ["'self'", "data:", "blob:", 'dl.airtable.com'],
          'media-src': ["'self'", "data:", "blob:", 'dl.airtable.com'],
          upgradeInsecureRequests: null
        }
      }
    }
  }
```

The error I'm still getting:
<img width="355" alt="Unbenannt" src="https://user-images.githubusercontent.com/22722663/182329076-aa73a4aa-cf6d-45fa-974e-6569accbf15f.PNG">

Here is the weird part: **Occassionaly, like once a day, it works. when I come back around half an hour later, the images are again broken.** 

Maybe there is a caching issue? Like do I need to clear the cache somewhere to make it work properly?

### Expected behavior
The configuration file should handle the problem but it's not working for me. I've tried different setups, removed the `useDefaults: true` statement, changed order of properties etc etc.

Nothing seems to work.

### Additional context
I don't know if this helps but here is part of my package.json config:

```
"devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.2.0",
    "@strapi/plugin-users-permissions": "4.2.0",
    "@strapi/strapi": "^4.3.0",
    "better-sqlite3": "7.4.6",
    "node-fetch": "^2.6.7",
    "pg": "^8.7.3",
    "snoowrap": "^1.23.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "e12d230a-737a-4a4f-ae27-c8f04aa558ba"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
```

**Comment by WalkingPizza** [comment]
Did you rebuild the project after updating the middleware configuration?
Can we see the full `middlewares.js` file?
Feel free to omit any private values.

**Comment by Stuhl** [comment]
Yes I always do the following:

```
git pull
NODE_ENV=production npm run build
npm run start
```

I read somewhere that deleting the build folder and clearing the npm cache helps, but it didn't for me.

Here is my entire `middlewares.js`:

```
module.exports = [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", "https:"],
          'img-src': ["'self'", "data:", "blob:", 'dl.airtable.com'],
          'media-src': ["'self'", "data:", "blob:", 'dl.airtable.com'],
          upgradeInsecureRequests: null
        }
      }
    }
  },
  {
    name: 'strapi::cors',
    config: {
      enabled: true,
      origin: [
        "http://localhost:1337",
        "http://localhost:3000",
        "https://mysite.com",
        "https://www.mysite.com"
     ],
      headers: ["'Access-Control-Allow-Origin'", 'Content-Type', 'Authorization', 'Origin', 'Accept'],
      keepHeaderOnError: true
    }
  },
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

Speaking of which, I also have the cors problem where I can't upload gifs or videos with the media library. The cors property is supposed to solve that but yeah, it doesn't for me. I probably will open a new issue for that to keep this thread clean.

**Comment by WalkingPizza** [comment]
> Yes I always do the following:
> 
> ```
> git pull
> NODE_ENV=production npm run build
> npm run start
> ```
> 
> I read somewhere that deleting the build folder and clearing the npm cache helps, but it didn't for me.
> 
> Here is my entire `middlewares.js`:
> 
> ```
> module.exports = [
>   'strapi::errors',
>   {
>     name: 'strapi::security',
>     config: {
>       contentSecurityPolicy: {
>         useDefaults: true,
>         directives: {
>           'connect-src': ["'self'", "https:"],
>           'img-src': ["'self'", "data:", "blob:", 'dl.airtable.com'],
>           'media-src': ["'self'", "data:", "blob:", 'dl.airtable.com'],
>           upgradeInsecureRequests: null
>         }
>       }
>     }
>   },
>   {
>     name: 'strapi::cors',
>     config: {
>       enabled: true,
>       origin: [
>         "http://localhost:1337",
>         "http://localhost:3000",
>         "https://mysite.com",
>         "https://www.mysite.com"
>      ],
>       headers: ["'Access-Control-Allow-Origin'", 'Content-Type', 'Authorization', 'Origin', 'Accept'],
>       keepHeaderOnError: true
>     }
>   },
>   'strapi::poweredBy',
>   'strapi::logger',
>   'strapi::query',
>   'strapi::body',
>   'strapi::session',
>   'strapi::favicon',
>   'strapi::public',
> ];
> ```
> 
> Speaking of which, I also have the cors problem where I can't upload gifs or videos with the media library. The cors property is supposed to solve that but yeah, it doesn't for me. I probably will open a new issue for that to keep this thread clean.

What upload provider are you using?

The `middlewares.js`file seems to have its default config, so I'm pretty sure something's missing.

For GIFs and videos, most of the time you have to edit the CORS settings of your provider's account (eg. the policies of your S3 bucket).

**Comment by bolg55** [comment]
Just following up here - as @WalkingPizza mentioned, if you could let us know which upload provider you are using, that would be helpful. Thanks!

**Comment by Stuhl** [comment]
Hey, first of all I solved the problem with uploading GIFS and videos. The problem wasn't caused by strapi. It was nginx. the directive `client_max_body_size` is set to 1MB at default. For most gifs and videos you have to increase that, else you get the blank screen error. Unfortunately it wasn't obvious what caused the error, I only found out by searching through the issue threads here.

A notice in the deployment section in the strapi docs would be nice, could avoid headaches for alot of people in the future.


As for the upload provider, I don't use any e.g. it must be `@strapi/provider-upload-local`. The files are being uploaded onto my own server. Maybe the issue is related to my server in some sense? Maybe the firewall is blocking requests or something like that.

Cheers

**Comment by derrickmehaffy** [comment]
Hello @Stuhl 

I added this warning a while back to the upload plugin docs. Can you clarify if you mean somewhere else as well?

I want to make sure others see it 

![Screenshot_20220812-070432_Chrome.jpg](https://user-images.githubusercontent.com/8593673/184370193-2b9bbe9e-1e83-4d98-9383-8eeddbcef9ee.jpg)

Warning is here: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#max-file-size

**Comment by derrickmehaffy** [comment]
Anyway, since it's been confirmed this is fixed by an upstream resource I'll set this as closed.
