### ISSUE TITLE
AdminUI should support logging in via "providers"

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1393]
**What is the expected behavior?**

The adminUI should also allow for users to register with one of the 3rd party providers (facebook, twitter, github, ect) along with local registration.

**Comment by soupette** [comment]
@derrickmehaffy currently the `register-page`is only displayed the first time you open the admin  [see line 108](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/AdminPage/index.js) and the only way to add a custom provider using the admin is to be authenticated.

So, adding a social connect to the `register-page` means that the first user has to enable a provider manually unless we add some `prompting` options to the current CLI to ease the process.

If a  👋 someone  👋  from the community feels like taking care of the CLI part I would be happy to add the social connect to the admin!

**Comment by lauriejim** [comment]
@derrickmehaffy We can already disable local email login / register.

**Comment by derrickmehaffy** [comment]
Ah nice yeah I just noticed that @lauriejim, it doesn't appear there is an actual registration for local except for the initial admin user creation? At least the login page doesn't offer a link for it.

**Comment by lauriejim** [comment]
Yes that's it. Exactly the same as WordPress. Register form for the setup of your app. Then you will have to develope your application that implement a register and login form.

**Comment by derrickmehaffy** [comment]
Assuming that plans to change with the addition of the adminUI permissions or no?

**Comment by derrickmehaffy** [comment]
Marking as closed for now, support for this won't happen for some time

**Comment by ciriousjoker** [comment]
Is this planned at all?

**Comment by derrickmehaffy** [comment]
> Is this planned at all?

It does exist yes but it's only for Strapi enterprise customers. It's known as SSO
