### ISSUE TITLE
Register with API misses 'id' in user object, while register with adminUI has 'id'

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1394]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: mongodb 3.6.4
- **Operating system**: macOS

**What is the current behavior?**

Call http://localhost:1337/auth/local/register API to register a new user, there is no 'id' in user object.
Go to http://localhost:1337/adminpanel/plugins/users-permissions/auth/register to register, there is no 'id'.

Use adminUI to 'add new user' in content manager, there has 'id'.

**Steps to reproduce the problem**

**What is the expected behavior?**
Expect consistency.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @yummyelin . It's related to this issue https://github.com/strapi/strapi/issues/1274
We have an long work to do on this point.
