### ISSUE TITLE
Strapi throws error when deleting image using AWS S3 Provider or local provider.

### ISSUE THREAD

**Issue by idahdam** [strapi/strapi#13948]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.1.2
- Strapi version: 4.3.0
- Database: PostgreSQL 14
- Operating system: Windows 10

### Describe the bug

Strapi throws error 500 when deleting an image, regardless its in media library or a folder inside of media library.

### Steps to reproduce the behavior

1. No setup for image provider or setup AWS S3 Provider accordingly using this link https://www.npmjs.com/package/@strapi/provider-upload-aws-s3
2. Upload Image (from media library, single type, or collection type)
3. Delete image

### Expected behavior

Image is deleted locally/in aws s3 provider, but throws and error.

### Screenshots

Here is the screenshot when the error happened:
![image](https://user-images.githubusercontent.com/40880027/182513860-e1643ec1-eb7d-44b1-a32d-497357ade3c9.png)

And when the page is refreshed:
![image](https://user-images.githubusercontent.com/40880027/182513946-4030a730-9b31-44f3-b40f-496f4127a5ca.png)

This works perfectly if you're trying to delete a folder, but not with image within a folder or just in media library in general.

### Code snippets

The error thrown in console is this:
`TypeError: Cannot read properties of undefined (reading 'length')
    at Object.deleteMany ...`

which is located in `node_modules/@strapi/plugin-upload/server/controllers/admin-folder-file.js`. The problem might lie here:

```
  if (deletedFiles.length + deletedFolders.length > 1) {
    strapi.telemetry.send('didBulkDeleteMediaLibraryElements', {
      rootFolderNumber: deletedFolders.length,
      rootAssetNumber: deletedFiles.length,
      totalFolderNumber,
      totalAssetNumber: totalFileNumber + deletedFiles.length,
    });
  }
```

because when I log the results of the params of if condition when you tried to delete an image, you'll get a value for `deletedFiles` but undefined for `deletedFolder`.

**Comment by petersg83** [comment]
Hello :)
The fixed was released in 4.3.2
