### ISSUE TITLE
Strapi keep looping until timeout when add new COLLECTION TYPES/Filed until user restart the strapi server

### ISSUE THREAD

**Issue by Ahmedsaber9** [strapi/strapi#13947]
Hello Strapi Team
Thanks for your hard work

- Node.js version:v14.19.3
- NPM version:6.14.17
- Strapi version:4.3.2
- Database: Default
- Operating system: ubuntu 18.04

### Describe the bug

it happens when adding any new  
-New COLLECTION TYPES
-New COLLECTION Filed

The admin panel timeout with massage "The restart is taking longer than expected
The server should have restarted, please check your logs in the terminal." the logs also say that server is restarted. and it's start with that loop.

`[2022-08-03 18:46:27.207] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:27.426] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:27.642] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:27.867] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:28.086] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:28.304] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:28.531] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:28.749] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:28.969] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:29.540] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:30.531] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:31.663] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:32.560] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:33.548] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:34.559] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:35.556] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:36.532] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:37.530] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:38.658] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:39.527] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:40.532] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:41.612] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:42.534] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:43.529] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:44.533] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:45.526] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:46.532] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:47.526] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:48.533] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:49.531] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:50.531] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:51.527] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:52.534] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:53.659] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:54.536] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:55.579] http: HEAD /_health (0 ms) 204
[2022-08-03 18:46:56.532] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:57.525] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:58.533] http: HEAD /_health (1 ms) 204
[2022-08-03 18:46:59.535] http: HEAD /_health (1 ms) 204`

after I do it myself and restart the server it keeps the same way until I open the admin page myself, after restarting and re-login I found the Field/COLLECTION  is added normally 

### Steps to reproduce the behavior

1. Create NEW COLLECTION TYPES

### Steps to reproduce the behavior

1. Create NEW COLLECTION Filed

### Expected behavior

The server restart itself without the user interaction affter submitting a new COLLECTION Filed or COLLECTION TYPES

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by Ahmedsaber9** [comment]
Added as requsted

**Comment by derrickmehaffy** [comment]
Please confirm the command you are using to start the server and please provide either more detailed steps to reproduce or a video (loom video is very easy to use and free) showing the steps to reproduce.

**Comment by Ahmedsaber9** [comment]
starting server command: npm run develop
detailed steps to reproduce: nothing special 
loom : https://www.loom.com/share/10fd8aea3bc24c7aa408218cb94fb969

**Comment by Ahmedsaber9** [comment]
loom server looping when adding new COLLECTION TYPES https://www.loom.com/share/dc268d0703184f2c80e531948690423f

**Comment by Ahmedsaber9** [comment]
I noted that there are no views for my videos, just following the issue, in case no one noticed my replies. 
also, the bug is not a blocker for regular usage.

**Comment by derrickmehaffy** [comment]
Is this running development in a deployed location? Like is this being used in production in develop mode?

Also where is this application hosted because working locally I cannot reproduce this at all:

https://www.loom.com/share/ce6734cb07634f64b7d22516449b6c08

**Comment by Ahmedsaber9** [comment]
Hi @derrickmehaffy 
my strapi is hosted at my VPS, it's working at proxmox virtualization.
I'm only running strapi with the command npm run develop, I don't go further to use it as production mode. the develop mood is fine for me. 
Server spec :
`sudo lshw                        
    description: Computer
    product: Standard PC (i440FX + PIIX, 1996)
    vendor: QEMU
    version: pc-i440fx-5.2
    width: 64 bits
    capabilities: smbios-2.8 dmi-2.8 smp vsyscall32
    configuration: boot=normal uuid=DDA1EAA3-9090-844C-8583-2B612B5B2E9B
  *-core
       description: Motherboard
       physical id: 0
     *-firmware
          description: BIOS
          vendor: SeaBIOS
          physical id: 0
          version: rel-1.14.0-0-g155821a1990b-prebuilt.qemu.org
          date: 04/01/2014
          size: 96KiB
     *-cpu:0
          description: CPU
          product: AMD Ryzen 5 3600 6-Core Processor
          vendor: Advanced Micro Devices [AMD]
          physical id: 400
          bus info: cpu@0
          version: pc-i440fx-5.2
          slot: CPU 0
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save umip rdpid arch_capabilities
          configuration: cores=4 enabledcores=4 threads=1
     *-cpu:1
          description: CPU
          product: AMD Ryzen 5 3600 6-Core Processor
          vendor: Advanced Micro Devices [AMD]
          physical id: 401
          bus info: cpu@1
          version: pc-i440fx-5.2
          slot: CPU 1
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat npt nrip_save umip rdpid arch_capabilities
          configuration: cores=4 enabledcores=4 threads=1
     *-memory
          description: System Memory
          physical id: 1000
          size: 8048MiB
          capabilities: ecc
          configuration: errordetection=multi-bit-ecc
        *-bank
             description: DIMM RAM
             vendor: QEMU
             physical id: 0
             slot: DIMM 0
             size: 8048MiB
     *-pci
          description: Host bridge
          product: 440FX - 82441FX PMC [Natoma]
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 02
          width: 32 bits
          clock: 33MHz
        *-isa
             description: ISA bridge
             product: 82371SB PIIX3 ISA [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: isa
             configuration: latency=0
        *-ide
             description: IDE interface
             product: 82371SB PIIX3 IDE [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1.1
             bus info: pci@0000:00:01.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: ide isa_compatibility_mode-only_controller__supports_bus_mastering bus_master
             configuration: driver=ata_piix latency=0
             resources: irq:0 ioport:1f0(size=8) ioport:3f6 ioport:170(size=8) ioport:376 ioport:e0e0(size=16)
        *-usb
             description: USB controller
             product: 82371SB PIIX3 USB [Natoma/Triton II]
             vendor: Intel Corporation
             physical id: 1.2
             bus info: pci@0000:00:01.2
             version: 01
             width: 32 bits
             clock: 33MHz
             capabilities: uhci bus_master
             configuration: driver=uhci_hcd latency=0
             resources: irq:11 ioport:e0c0(size=32)
           *-usbhost
                product: UHCI Host Controller
                vendor: Linux 4.15.0-189-generic uhci_hcd
                physical id: 1
                bus info: usb@1
                logical name: usb1
                version: 4.15
                capabilities: usb-1.10
                configuration: driver=hub slots=2 speed=12Mbit/s
              *-usb
                   description: Human interface device
                   product: QEMU USB Tablet
                   vendor: QEMU
                   physical id: 1
                   bus info: usb@1:1
                   version: 0.00
                   serial: 28754-0000:00:01.2-1
                   capabilities: usb-2.00
                   configuration: driver=usbhid maxpower=100mA speed=12Mbit/s
        *-bridge
             description: Bridge
             product: 82371AB/EB/MB PIIX4 ACPI
             vendor: Intel Corporation
             physical id: 1.3
             bus info: pci@0000:00:01.3
             version: 03
             width: 32 bits
             clock: 33MHz
             capabilities: bridge
             configuration: driver=piix4_smbus latency=0
             resources: irq:9
        *-display
             description: VGA compatible controller
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 02
             width: 32 bits
             clock: 33MHz
             capabilities: vga_controller bus_master rom
             configuration: driver=bochs-drm latency=0
             resources: irq:0 memory:fd000000-fdffffff memory:fea70000-fea70fff memory:c0000-dffff
        *-generic
             description: Unclassified device
             product: Virtio memory balloon
             vendor: Red Hat, Inc.
             physical id: 3
             bus info: pci@0000:00:03.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:e000(size=64) memory:fe400000-fe403fff
           *-virtio0 UNCLAIMED
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@0
                configuration: driver=virtio_balloon
        *-scsi
             description: SCSI storage controller
             product: Virtio SCSI
             vendor: Red Hat, Inc.
             physical id: 5
             bus info: pci@0000:00:05.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: scsi msix bus_master cap_list
             configuration: driver=virtio-pci latency=0
             resources: irq:10 ioport:e040(size=64) memory:fea71000-fea71fff memory:fe404000-fe407fff
           *-virtio1 UNCLAIMED
                description: Virtual I/O device
                physical id: 0
                bus info: virtio@1
                configuration: driver=virtio_scsi
        *-network
             description: Ethernet interface
             product: 82540EM Gigabit Ethernet Controller
             vendor: Intel Corporation
             physical id: 12
             bus info: pci@0000:00:12.0
             logical name: ens18
             version: 03
             serial: d2:c6:ba:95:e3:0c
             size: 1Gbit/s
             capacity: 1Gbit/s
             width: 32 bits
             clock: 33MHz
             capabilities: bus_master rom ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
             configuration: autonegotiation=on broadcast=yes driver=e1000 driverversion=7.3.21-k8-NAPI duplex=full ip=95.216.87.27 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
             resources: irq:11 memory:fea40000-fea5ffff ioport:e080(size=64) memory:fea00000-fea3ffff
        *-pci:0
             description: PCI bridge
             product: QEMU PCI-PCI bridge
             vendor: Red Hat, Inc.
             physical id: 1e
             bus info: pci@0000:00:1e.0
             version: 00
             slot: 0, chassis 1
             width: 64 bits
             clock: 66MHz
             capabilities: pci msi slotid normal_decode cap_list
             resources: memory:fea72000-fea720ff ioport:d000(size=4096) memory:fe800000-fe9fffff ioport:fe200000(size=2097152)
        *-pci:1
             description: PCI bridge
             product: QEMU PCI-PCI bridge
             vendor: Red Hat, Inc.
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 00
             slot: 0, chassis 2
             width: 64 bits
             clock: 66MHz
             capabilities: pci msi slotid normal_decode cap_list
             resources: memory:fea73000-fea730ff ioport:c000(size=4096) memory:fe600000-fe7fffff ioport:fe000000(size=2097152)
     *-scsi:0
          physical id: 1
          logical name: scsi1
          capabilities: emulated
        *-cdrom
             description: DVD reader
             product: QEMU DVD-ROM
             vendor: QEMU
             physical id: 0.0.0
             bus info: scsi@1:0.0.0
             logical name: /dev/cdrom
             logical name: /dev/dvd
             logical name: /dev/sr0
             version: 2.5+
             capabilities: removable audio dvd
             configuration: ansiversion=5 status=ready
           *-medium
                physical id: 0
                logical name: /dev/cdrom
                capabilities: partitioned partitioned:dos
                configuration: signature=610a091e
              *-volume UNCLAIMED
                   description: Hidden HPFS/NTFS partition
                   physical id: 1
                   capacity: 455MiB
                   capabilities: primary bootable hidden
     *-scsi:1
          physical id: 2
          logical name: scsi2
        *-disk
             description: SCSI Disk
             product: QEMU HARDDISK
             vendor: QEMU
             physical id: 0.0.0
             bus info: scsi@2:0.0.0
             logical name: /dev/sda
             version: 2.5+
             size: 80GiB (85GB)
             capabilities: 5400rpm gpt-1.00 partitioned partitioned:gpt
             configuration: ansiversion=5 guid=eedee1b1-196f-4de6-9479-0a33d8ba2df5 logicalsectorsize=512 sectorsize=512
           *-volume:0
                description: BIOS Boot partition
                vendor: EFI
                physical id: 1
                bus info: scsi@2:0.0.0,1
                logical name: /dev/sda1
                serial: b7b69c1b-a616-4bd0-ab98-12dd65dfc5c9
                capacity: 1023KiB
                capabilities: nofs
           *-volume:1
                description: EXT4 volume
                vendor: Linux
                physical id: 2
                bus info: scsi@2:0.0.0,2
                logical name: /dev/sda2
                logical name: /boot
                version: 1.0
                serial: 72b2125a-3b58-4da2-84c9-bad26ff95360
                size: 1GiB
                capabilities: journaled extended_attributes large_files huge_files dir_nlink 64bit extents ext4 ext2 initialized
                configuration: created=2020-12-28 01:32:10 filesystem=ext4 lastmountpoint=/boot modified=2022-08-08 16:06:15 mount.fstype=ext4 mount.options=rw,relatime,data=ordered mounted=2022-08-08 12:19:14 state=mounted
           *-volume:2
                description: EFI partition
                physical id: 3
                bus info: scsi@2:0.0.0,3
                logical name: /dev/sda3
                serial: rZ1re5-ips1-6fgS-P2Mm-Kn6r-onk4-TifKig
                size: 48GiB
                capacity: 77GiB
                capabilities: lvm2`

**Comment by Ahmedsaber9** [comment]
![image](https://user-images.githubusercontent.com/23035531/183723200-80975b50-f3b1-49b7-8d40-4b407f7fca39.png)

**Comment by derrickmehaffy** [comment]
We do not support running the develop mode in a deployed environment. If this issue can't be reproduced locally then it's not something we will fix (largely because we likely can't).

I'm guessing the watcher isn't working on your deployed host so Strapi can't see or know when it needs to restart.

Please provide steps to reproduce this issue locally and not in a remote environment.

**Comment by derrickmehaffy** [comment]
Since there is no new information I'm gonna set this one as closed. If you have more information please feel free to reply and we can look at reopening this.

**Comment by MelleNi** [comment]
I'm getting this locally. Fresh install, following this guide: https://strapi.io/blog/how-to-build-a-blog-with-astro-strapi-and-tailwind-css

Upon saving the first collection, it reboots the server and is then stuck forever outputting this:
```
[2023-02-28 11:31:00.013] http: HEAD /_health (0 ms) 204
```

**Comment by ronycodex** [comment]
Found a solution to this problem i was facing this error because i accidentally named one of my field "number ".

Solved it by :
-> Stop the server
-> Go to: src/api/<collection_name>/content-types/<collection_name>/schema.json
-> found the attribute renamed it
-> start the server by hitting "npm run develop" or "yarn develop"

Hope you guys fix your problem comment with "❤️‍🔥" if i helped ya.

**Comment by AthorusDigital** [comment]
I've had the same problem for weeks. For the moment I have not found a solution... My fields are mainly named "tilte", "content", "index". The index field in indexId does not change anything.

[2023-05-18 18:19:26.111] http: HEAD /_health (6ms) 204
[2023-05-18 18:19:26.224] http: HEAD /_health (1ms) 204
[2023-05-18 18:19:26.333] http: HEAD /_health (1ms) 204
[2023-05-18 18:19:26.441] http: HEAD /_health (1ms) 204
[2023-05-18 18:19:26.549] http: HEAD /_health (1ms) 204
[2023-05-18 18:19:26.678] http: HEAD /_health (1ms) 204
[2023-05-18 18:19:26.782] http: HEAD /_health (1ms) 204
[2023-05-18 18:19:26.891] http: HEAD /_health (0 ms) 204

**Comment by escii** [comment]
same..

**Comment by oghenetefa** [comment]
Why has this issue been Closed? the problem still persists 

**Strapi**: v4
**node**; V20.7.0

**PC Device info**
Processor	Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz   2.60 GHz
Installed RAM	8.00 GB (7.87 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

I would submit a duplicate issue myself but...

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy it seems to be a mistake with :
> 
> ```
> // core/content-type-builder/admin/src/components/DataManagerProvider/DataManagerProvider.ts
>  await serverRestartWatcher(true); 
> ```
>  
>  because function is 
>  
> ```
>  // core/content-type-builder/admin/src/components/DataManagerProvider/utils/serverRestartWatcher.ts
>  export function serverRestartWatcher(response: any, didShutDownServer?: boolean)
> ```
> 
> call has only one arg....

Good catch, I'll reopen this

**Comment by derrickmehaffy** [comment]
For more recent information, I've only seen this happen on Windows recently. Mac + Linux don't experience it afaik

**Comment by derrickmehaffy** [comment]
Will do some testing once I have a moment

**Comment by derrickmehaffy** [comment]
Can you confirm your Strapi version?

**Comment by derrickmehaffy** [comment]
Can anyone reproduce this on a more recent version?

**Comment by Convolva** [comment]
@derrickmehaffy Yup, just did with Strapi v4.11.1 today. 

![image](https://github.com/strapi/strapi/assets/95045175/c6a79b37-34d8-4904-b04c-2852ae112bac)


### Steps to re-produce:
- Create a field and called it "cover_image" for a blogs content-type
- Rename the field to coverImage
- Save the field.
- If the issue doesn't show up at this point, then try deleting the field and then it takes forever for the server to restart with the following statements showing on the console:

![image](https://github.com/strapi/strapi/assets/95045175/53a7daa7-b405-429a-9e15-b588d7808bb1)

**Extra Info:**
I am working with MySQL for DB and NGINX.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Yup, just did with Strapi v4.11.1 today. 
> 
> ![image](https://github.com/strapi/strapi/assets/95045175/c6a79b37-34d8-4904-b04c-2852ae112bac)
> 
> 
> ### Steps to re-produce:
> - Create a field and called it "cover_image" for a blogs content-type
> - Rename the field to coverImage
> - Save the field.
> - If the issue doesn't show up at this point, then try deleting the field and then it takes forever for the server to restart with the following statements showing on the console:
> 
> ![image](https://github.com/strapi/strapi/assets/95045175/53a7daa7-b405-429a-9e15-b588d7808bb1)
> 
> **Extra Info:**
> I am working with MySQL for DB and NGINX on Ubuntu 22 (Linux) so I think this is not a windows specific issue.
> 
> I faced this issue in prod mode.
> 
> 

4.11.x isn't a recent version as the current latest is 4.20.1

**Comment by Convolva** [comment]
Oh yeah my bad, I just noticed that. I have resolved it for now by re-building the strapi admin and starting it and then deleting it, which seems to fix the issue for now in 4.11.1.

As for the latest version, I will be updating it to 4.20.1 soon. Will post here again if I notice this issue again.  @derrickmehaffy

**Comment by noeldrew** [comment]
Happened to me simply following the Strapi quick start guide on the website. Fresh install of everything

**Comment by DomVournias** [comment]
Is it fixed?

**Comment by sutamura** [comment]
This issue happens to me and I found upper case letters cause this issue in my environment.
Win11 23H2 KB5043076/ Strapi v4.25.11 on localhost/  node.js v20.17.0

I assume no space allowed in the name field leads us to use big letters.
I hope this may help you.

**Comment by Inevitabilis** [comment]
+1 here. Win10 pro 10.0.19045, strapi v4.25.11, node,js v20.15.0
From fresh install i've made entity Game with fields Title: string (i've seen people mentioning this field here) and CoverArt: media
Then created RoomConnection entity with no fields, and at this point webapp showed "need to restart to apply changes"
Was a bunch of _health HEAD requests too

the request contents are as follows:

```
HEAD /_health HTTP/1.1
Host: localhost:1337
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Referer: http://localhost:1337/admin/plugins/content-type-builder/content-types/api::game-trick.game-trick
Connection: keep-alive
Cookie: username-localhost-8888=2|1:0|10:1724619913|23:username-localhost-8888|196:eyJ1c2VybmFtZSI6ICI3M2RjYmRkY2E1MmM0ODQ2YWRkZDY1OTk0NWI3ODI3ZCIsICJuYW1lIjogIkFub255bW91cyBFcmlub21lIiwgImRpc3BsYXlfbmFtZSI6ICJBbm9ueW1vdXMgRXJpbm9tZSIsICJpbml0aWFscyI6ICJBRSIsICJjb2xvciI6IG51bGx9|d0aa1379646172d0e492e09177094a7208c68149ad13d15725cf1dd75837848f; _xsrf=2|4b8c5a10|23a2c75f7cf375b6b539b3cfe7a84f62|1724619913
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
```

The response is as follows:

```
HTTP/1.1 204 No Content
Content-Security-Policy: connect-src 'self' https:;img-src 'self' data: blob: https://market-assets.strapi.io;media-src 'self' data: blob:;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Vary: Origin
Access-Control-Allow-Origin: 
Access-Control-Allow-Credentials: true
strapi: You are so French!
X-Powered-By: Strapi <strapi.io>
Date: Tue, 17 Sep 2024 09:45:13 GMT
Connection: keep-alive
```

There doesn't seem to be any change between these requests and responses, unless it is somewhere in cookies down the line, and obviously their time does change
