### ISSUE TITLE
Uninstall plugin 'file upload' causes 'content type builder' buggy

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1395]
**Informations**
- **Node.js version**: 9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: mongodb 3.6.4
- **Operating system**: macOS

**What is the current behavior?**
After uninstall plugin 'file upload', there are a few bugs while adding new field to content type.

**Steps to reproduce the problem**

1. Uninstall plugin 'file upload'.
2. Go to content type 'user', click 'add new field', a window pops out.
There has 'Relation' and 'Enumeration'.
![screen shot 2018-06-14 at 5 20 14 pm](https://user-images.githubusercontent.com/3782817/41444460-0d85b696-6ff8-11e8-811b-3a918cc72fd0.png)
3. close the window and click again.
'Relation' disappeares.
![screen shot 2018-06-14 at 5 21 14 pm](https://user-images.githubusercontent.com/3782817/41444481-29a21306-6ff8-11e8-8fff-7ccf4bfe5e1d.png)
4. close the window and click again.
'Enumeration' disappears.
![screen shot 2018-06-14 at 5 17 14 pm](https://user-images.githubusercontent.com/3782817/41444493-4204010c-6ff8-11e8-8360-7b3e2b3b62bc.png)

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @yummyelin, I try to reproduce and I got `relation` and `enum` type after uninstall `upload` plugin ... Can you try with last version of Strapi please.

**Comment by yummyelin** [comment]
I think I reproduced the issue, using 12.6.

[demo repo](https://github.com/yummyelin/strapi-hellol)

**Comment by lauriejim** [comment]
@yummyelin Can you make your repo public please, I can't access.

**Comment by redni** [comment]
@lauriejim from what I see @yummyelin made a typo in the address of the repository when he added his comment. This address should work: https://github.com/yummyelin/strapi-hello

**Comment by lauriejim** [comment]
Thank you @redni.
@yummyelin can you update your app with last version of Strapi please.

**Comment by yummyelin** [comment]
@lauriejim yes, I am using latest version of Strapi, 3.0.0-alpha.12.6

**Comment by lauriejim** [comment]
Good, I suggest you to not delete this plugin 😆 
We will not work on it soon. Not critical issue.

**Comment by yummyelin** [comment]
ok

**Comment by lauriejim** [comment]
But thank you for this bug report.
