### ISSUE TITLE
The most of the Strapi starters are not installable

### ISSUE THREAD

**Issue by mlc-mlapis** [strapi/strapi#13965]
When using the latest version **create-strapi-starter my-project `<starter>`** (v4.3.2) and selecting a starter from the page https://strapi.io/starters, the installation has been crashing with the error:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getPackageInfo (...\v14.17.0\node_modules\create-strapi-starter\utils\fetch-npm-starter.js:19:27)
```

It seems that only 2 starters (gatsby-blog + next-blog) are working somehow, but there are different problems with dependencies.

NodeJS: 14.17.0
NPM: 6.14.13
OS: Windows 10

**Comment by derrickmehaffy** [comment]
Please open an issue on the starters and templates repo as this repo is for the Strapi code specifically: https://github.com/strapi/starters-and-templates
