### ISSUE TITLE
V4 - collection types dissappear after create new one. 

### ISSUE THREAD

**Issue by jowiBoyz** [strapi/strapi#13963]
Hello there, 

both of my collection types dissappear today after create a new one. But they are still in api folder. 
I have cleaned the browser cache and strapi backend, restart it and open it in other browser.  But nothing helps and they are still missing in the browser strapi admin. I thought first maybe collection type are limited only 5 for free plan ??.  Anyone has the similar problem ?  Please advice . Thank you. Here are my dependencies :

  "dependencies": {
    "@strapi/plugin-i18n": "4.3.0",
    "@strapi/plugin-users-permissions": "4.3.0",
    "@strapi/provider-upload-cloudinary": "^4.3.0",
    "@strapi/strapi": "^4.3.2",
    "better-sqlite3": "7.4.6",
    "pg": "^8.7.3",
    "pg-connection-string": "^2.5.0",
    "slugify": "^1.6.5"
  },

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
