### ISSUE TITLE
Uploaded Media with API not linked to specified filed COLLECTION and uploaded to Media Library - API Uploads only

### ISSUE THREAD

**Issue by Ahmedsaber9** [strapi/strapi#13969]
Hello Strapi Team
Thanks for your hard work

- Node.js version:v14.19.3
- NPM version:6.14.17
- Strapi version:4.3.2
- Database: Default
- Operating system: ubuntu 18.04

### Describe the bug
I have a COLLECTION TYPE that has some media fields

`{
  "kind": "collectionType",
  "collectionName": "user_kycs",
  "info": {
    "singularName": "user-kyc",
    "pluralName": "user-kycs",
    "displayName": "UserKyc",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "firstname": {
      "type": "string",
      "unique": false
    },
    "secondname": {
      "type": "string"
    },
    "thirdname": {
      "type": "string"
    },
    "fourthname": {
      "type": "string"
    },
    "fivevname": {
      "type": "string"
    },
    "sixname": {
      "type": "string"
    },
    "Id_front_pic": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ]
    },
    "selfie_pic_cam": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "videos",
        "audios",
        "files"
      ]
    },
    "livens_test_shoot_pic1": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ]
    },
    "livens_test_shoot_pic2": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ]
    },
    "livens_test_shoot_pic3": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ]
    },
    "livens_test_shoot_video": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "videos",
        "audios",
        "files"
      ]
    },
    "is_id": {
      "type": "boolean",
      "required": true
    },
    "is_passport": {
      "type": "boolean",
      "required": true
    },
    "id_number": {
      "type": "string"
    },
    "expire_date": {
      "type": "string"
    },
    "Issuer_city": {
      "type": "string"
    },
    "birth_city": {
      "type": "string"
    },
    "dob": {
      "type": "text"
    },
    "save_number": {
      "type": "string"
    },
    "save_date": {
      "type": "string"
    },
    "Issuer_save_city": {
      "type": "string"
    },
    "id_version": {
      "type": "string"
    },
    "all_ocr_data_as_as": {
      "type": "text"
    },
    "id_back_pic": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "passport_pic": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "videos",
        "audios",
        "files"
      ]
    },
    "pic_test": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    }
  }
}

`
I'm using the following request to upload the images to the desired field 

![image](https://user-images.githubusercontent.com/23035531/182689019-22a2edf3-082e-46bd-8430-4efe3870c21d.png)

`refId:38
ref:api::user-kyc.user-kyc
//filed:selfie_pic_cam
//field:Id_front_pic
//field:id_back_pic
//filed:passport_pic
//filed:livens_test_shoot_pic1
//filed:livens_test_shoot_pic2
//filed:livens_test_shoot_pic3
//filed:livens_test_shoot_pic3
//filed:livens_test_shoot_video
filed:pic_test`

The Problem is all the media fields got uploaded but to the **API Media folder only,** except for the **id_back_pic** and **Id_front_pic**, it's working fine and got linked to desired.

I don't use any custom code for that task, and I tried to use the same config for the id_back_pic and Id_front_pic to be the same as the rest of the media fields without luck.

I tried to create a new COLLECTION TYPE  with media fields, and the same problem is happing 

### Steps to reproduce the behavior

1. Create a NEW COLLECTION
2. Create a Media COLLECTION field
3. try to upload a pic to a specific media field
It may happen with all fields or one can't verify when or how it's happening 
4- try to upload a pic  **id_back_pic** and **Id_front_pic** it will work "that only available at my server" - if needed to see it I have no problem 
5- try to upload any pic, it will be uploaded too but not assigned to the desired field, **but to Media Library - API Uploads only**
6- the two pics are uploaded with the API with the mentioned postman request. 

![image](https://user-images.githubusercontent.com/23035531/182692750-309c3602-27f5-478f-8d6d-a7bf78637c83.png)

### Expected behavior

The media field should upload and view the image at the desired field, not only to the Media Library - API Uploads.

**Comment by derrickmehaffy** [comment]
Based on the information provided you have typed `filed` not `field` which I believe to be the problem. Please double check you don't have any other typos but I believe this to be user error and not a bug so I'll redirect you to community sources.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Ahmedsaber9** [comment]
Thanks for your response , yes I discovered this alone and I was about to replay to fix that.
many thanks to you.
but I have a recommendation, the key I'm using should be a "Core key" let's say that liked with strapi file upload system, but the system uploads the pic anyhow, and I think the response should have an alert at least, I don't know if that contradicts with strapi architecture but that is my recommendation. waiting to know your opinion.
many thanks.
