### ISSUE TITLE
User relation saved as null from content manager

### ISSUE THREAD

**Issue by sidharthv96** [strapi/strapi#1396]
**Informations**
- **Node.js version**:v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: Mongo v3.6.5
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
I have this relation inside my customer model.

```
"user": {
      "model": "user",
      "via": "customer",
      "plugin": "users-permissions",
      "required": true,
      "unique": true
    },
```

The customer is auto created when a new user is added. This works fine. But when I try to edit any attribute of the customer from the content manager, the relation is saved with null. I can't set the relation again from the content manager again. This happens even if I edit only a boolean field in the customer model

It works fine in my local environment. macOS

**Steps to reproduce the problem**
It was working fine yesterday night. I only restarted the server.

**What is the expected behavior?**
User relation should be saved to the DB

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@sidharthv96 on your issue move the ` on your code bit down one line so it doesn't code block the rest of the issue template :)

**Comment by sidharthv96** [comment]
This issue is very random in nature.
I just tried editing it a few minutes back and the data was saved.
When I tried now, it's null again.

**Comment by lauriejim** [comment]
What is the nature of your relation between `user` and `customer` ?

**Comment by sidharthv96** [comment]
One-One

**Comment by lauriejim** [comment]
Can you try to remove `"required": true` and `"unique": true` from the relation. It's not handle by the framework.

It's work fin on my side...

**Comment by lauriejim** [comment]
Can you try with the last version of Strapi and tell me if it's work well on your side too.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
