### ISSUE TITLE
Can't build admin panel without the /src/admin folder

### ISSUE THREAD

**Issue by fdel-car** [strapi/strapi#13975]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.13.2
- Strapi version: 4.3.2
- Database: PostgreSQL 12.9
- Operating system: WSL2 / Ubuntu 20.04

### Describe the bug

Without the `/src/admin` folder in the project we can't build the admin panel:

```text
Building your admin UI with development configuration...
[Error: ENOENT: no such file or directory, scandir '/path/to/my-strapi-app/src/admin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/path/to/my-strapi-app/src/admin'
}
```

And without the example files inside - so with an empty `/src/admin` - we can see this error message after every build:

```text
Building your admin UI with development configuration...

✖ Webpack
  Compiled with some errors in 8.81s

[
  {
    file: './.cache/admin/src/tsconfig.json',
    message: `\x1B[90mTS18003: \x1B[39mNo inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["../../../src/admin/*","../../../src/**/**/admin/src/*"]' and 'exclude' paths were '["node_modules","**/*.test.js","*.js"]'.`,
    details: undefined,
    stack: `Error: \x1B[90mTS18003: \x1B[39mNo inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["../../../src/admin/*","../../../src/**/**/admin/src/*"]' and 'exclude' paths were '["node_modules","**/*.test.js","*.js"]'.\n` +
      '    at /path/to/my-strapi-app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:42:27\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at /path/to/my-strapi-app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:41:16\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (/path/to/my-strapi-app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:5:58)'
  }
]
Admin UI built successfully
```

### Steps to reproduce the behavior

1. Create a new strapi project using `create-strapi-app`
2. Either completely remove the `/src/admin` folder, or the example files inside
3. Run `yarn build`
4. See one of the error above, depending on what you did in step 2

### Expected behavior

A folder like `/src/admin` shouldn't be required, and I would not expect any error if it ends up being empty, especially given that the default content is example files.

### Additional context

As I'm migrating an app from Strapi v3 to v4 I stumbled upon this because I didn't have the `/src/admin` folder, it is indeed generated when using `create-strapi-app` but I think it could be quite confusing for other users if they end up in the same situation.

**Comment by derrickmehaffy** [comment]
Meaning codemods isnt creating it as part of the migration.

We should determine if it needs to exist and if so then we need to update codemods or remove it's requirement.

CC @yanniskadiri

**Comment by bis0072** [comment]
same problem I'm facing.

**Comment by tms0** [comment]
Note: This is a regression that has been introduced in Strapi v4.3.x, it was working without this folder in the previous versions (was OK until 4.2.3)

**Comment by derrickmehaffy** [comment]
If that's true then it means it's a bug and we shouldn't be requiring this, should be a fairly simple fix if anyone wants to put in a PR

**Comment by Vindeep07** [comment]
@derrickmehaffy I would like to work on this.
But I am not sure about solution for second error where webpack gives no input error, would be helpful if can direct for it.

**Comment by derrickmehaffy** [comment]
I'm more or less waiting on my engineering team to respond on if these files are required or not to determine what needs to be done.

**Comment by gsouf** [comment]
I'm still getting this issue, trying to upgrade from 4.2 to 4.3.9, or even latest that is 4.5.6. Any idea?

**Comment by derrickmehaffy** [comment]
> I'm still getting this issue, trying to upgrade from 4.2 to 4.3.9, or even latest that is 4.5.6. Any idea?

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by gsouf** [comment]
Well, it's really a follow up on this issue. I pulled the version that fixed this exact bug but still getting the bug. I'm happy to open a question tho but I'm not sure it would be of any more help as people involved with this issue are all in this ticket

**Comment by gsouf** [comment]
If anyone wonders, I fixed by adding the default file `src/admin/webpack.config.example.js` found in the default install of strapi.
