### ISSUE TITLE
Non-superusers in admin can bypass user restrictions to trigger webhooks

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#13970]
### Required System information

- Node.js version: v14
- NPM version: v6
- Strapi version: v4.2.3 & v3.6.10
- Database: SQLite 3
- Operating system: Linux Mint 20.3

### Describe the bug

Admin panel users without access to the webhooks settings page are able to trigger webhook tests with no option to control that access (if they have a valid admin panel token then they can trigger them)

### Steps to reproduce the behavior

1. Create a content-type
2. Setup a webhook (I recommend https://webhook.site/ for testing webhooks)
3. Create a new admin user with any other role than superuser and do not enable access to the webhooks feature
4. Use that user to send a POST request to `/admin/webhooks/1/trigger`
5. See that the response is 200 and the webhook was actually triggered

### Expected behavior

If the user does not have access to the webhooks feature, they should not be able to trigger webhooks. 
API Tokens (write) should have access to trigger webhooks but even better if during API tokens v2 we control specific access to trigger

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/182720569-159f3153-74b5-433f-9e4e-88ce2458e893.png)

### Code snippets

N/A

### Additional context

I have created this issue as I believe it's not that critical of a security threat since the user can only trigger the webhook test mode which will provide the following response to the webhook URL:

```json
{
  "event": "trigger-test",
  "createdAt": "2022-08-03T21:51:12.607Z"
}
```

This is trivial to work around at the client side as you simply need to watch for that specific event and ignore it but regardless it's still a potential for a DDoS attack that could impact downstream services or cause undo harm to downstream services if it's not properly protected against

**Comment by WalkingPizza** [comment]
Added the missing policies in #14003.

> API Tokens (write) should have access to trigger webhooks but even better if during API tokens v2 we control specific access to trigger

At the moment it looks like API tokens don't have access to any of the admin routes, probably due to the `admin::isAuthenticatedAdmin` policy.

**Comment by derrickmehaffy** [comment]
> Added the missing policies in #14003.
> 
> > API Tokens (write) should have access to trigger webhooks but even better if during API tokens v2 we control specific access to trigger
> 
> At the moment it looks like API tokens don't have access to any of the admin routes, probably due to the `admin::isAuthenticatedAdmin` policy.

Nice let me test your PR but I believe you are right, we just didn't have the policies. I'll need to check and see if we can fix the issue in v3 also by backporting the fix.
