### ISSUE TITLE
How to get localized entry from a collection

### ISSUE THREAD

**Issue by kzrodrigo** [strapi/strapi#13987]
Hi!

I’m trying to get a single entry from a collection with localization, but I can’t find the right query string. Specifically, I’m trying to get a localized blog entry from a blogs collection.

This works: .../api/blogs?locale-fr-CA[&optional-populate-query], but it brings all the blog entries, in the localized language.

This: .../api/blogs/1?locale=fr-CA[&optional-populate-query] will return the correct entry, but ignore the locale and display only the default locale. All the optional population works, regardless of the order (I’ve trived putting the locale at end, in the beginning, and in the middle, same behaviour).

I could bring all the entries and filter by ID, but it’s not the ideal solution. What I really want is to being just the specific entry in the correct locale.

Is it possible?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
