### ISSUE TITLE
Admin panel can't run when I change prefix in productioin

### ISSUE THREAD

**Issue by kwzm** [strapi/strapi#1398]
**Informations**
- **Node.js version**: 10.1.0
- **npm version**:  5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb
- **Operating system**: win7 x64

**What is the current behavior?**

When I changed prefix to /api in production, and then I opened http://10.2.5.98:1337/api/dashboard, the page didn't show anything. Then I open console and found GET http://10.2.5.98:1337/dashboard/vendor.dll.js 404 (Not Found).

**Steps to reproduce the problem**

As above

**What is the expected behavior?**

Admin panel is ok.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Duplicate issue, see: https://github.com/strapi/strapi/issues/1323

**Comment by derrickmehaffy** [comment]
@kwzm I believe the admin panel should still run at `localhost:1337/admin` or in your case /dashboard

The prefix is for your get requests on models such as `localhost:1337/blog`
