### ISSUE TITLE
Typescript generate plugin is broken

### ISSUE THREAD

**Issue by matepaiva** [strapi/strapi#13998]
### Required System information

- Node.js version: 14.16.1
- NPM version: 6.14.12
- Strapi version: 4.3.2
- Database: mysql
- Operating system: linux
- Plugin Strapi version (devDependency): 4.1.8

### Describe the bug
I generated a plugin using the cli and followed all the steps from the documentation, but at `npm run build` it throws a typescript error:

``` 
▶ npm run build                        

> file-bulk-uploader-by-url@0.0.0 build /server/src/plugins/test
> tsc

server/controllers/my-controller.ts:6:8 - error TS2339: Property 'plugin' does not exist on type 'StrapiInterface'.
6       .plugin('test')
         ~~~~~~
``` 

### Steps to reproduce the behavior
```
new/server/src  main ✗                                                                                                                                            1d23h ⚑ ◒  
▶ npm run strapi generate plugin              

> anteprojectos-pt_server@0.1.0 strapi /server
> strapi "generate" "plugin"

? Plugin name: test
? Choose your preferred language: TypeScript
✔  +! 26 files added
 -> /plugins/test/strapi-admin.js
 -> /plugins/test/strapi-server.js
 -> /plugins/test/tsconfig.json
 -> /plugins/test/server/bootstrap.ts
 -> /plugins/test/server/destroy.ts
 -> /plugins/test/server/index.ts
 -> /plugins/test/server/register.ts
 -> /plugins/test/admin/src/index.tsx
 -> /plugins/test/admin/src/pluginId.ts
 -> /plugins/test/server/config/index.ts
 -> /plugins/test/server/content-types/index.ts
 -> /plugins/test/server/controllers/index.ts
 -> /plugins/test/server/controllers/my-controller.ts
 -> /plugins/test/server/middlewares/index.ts
 -> /plugins/test/server/policies/index.ts
 -> /plugins/test/server/routes/index.ts
 -> /plugins/test/server/services/index.ts
 -> /plugins/test/server/services/my-service.ts
 -> /plugins/test/admin/src/translations/en.json
 -> /plugins/test/admin/src/translations/fr.json
 -> /plugins/test/admin/src/utils/axiosInstance.ts
 -> /plugins/test/admin/src/utils/getTrad.ts
 -> /plugins/test/admin/src/components/Initializer/index.tsx
 -> /plugins/test/admin/src/components/PluginIcon/index.tsx
 -> /plugins/test/admin/src/pages/App/index.tsx
 -> /plugins/test/admin/src/pages/HomePage/index.tsx
✔  ++ /plugins/test/README.md
✔  ++ /plugins/test/package.json
✔  -> 
You can now enable your plugin by adding the following in ./config/plugins.ts
─────────────────────────────────
export default {
  // ...
  'test': {
    enabled: true,
    resolve: './src/plugins/test'
  },
  // ...
}
─────────────────────────────────

▶ cd plugins/test 
▶ npm i
▶ npm run build
> test@0.0.0 build /server/src/plugins/test
> tsc
server/controllers/my-controller.ts:6:8 - error TS2339: Property 'plugin' does not exist on type 'StrapiInterface'.
6       .plugin('test')
         ~~~~~~
Found 1 error in server/controllers/my-controller.ts:6
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.0.0 build: `tsc`
npm ERR! Exit status 1
```

### Expected behavior

The example plugin should just work.

### Additional context
I found it weird that the devDependency in the plugin package.json didn't match the Strapi version:

```
"devDependencies": {
    "typescript": "4.6.3",
    "@strapi/strapi": "4.1.8"
  },
```

So I updated it to match my installed version, which is 4.3.2. But then it started throwing even more errors, such as:
```
server/register.ts:3:39 - error TS2709: Cannot use namespace 'Strapi' as a type.
3 export default ({ strapi }: { strapi: Strapi }) => {
                                        ~~~~~~
```

Also I tried to update the typescript version from 4.6.3 to 4.7.4, but it made no change.

**Comment by garytube** [comment]
I have a similar Problem with Services.
I created a new service on a fresh strapi (ts template) install.

I  used the ts code provided by the docs 

https://docs.strapi.io/developer-docs/latest/development/backend-customization/services.html#adding-a-new-service

`export default factories.createCoreService('api::test.testservice', ({ strapi }) => ({
  // Method 1: Creating an entirely custom service
  async exampleService(...args) {
    let response = { okay: true }

    if (response.okay === false) {
      return { response, error: true }
    }

    return response
  }
}));
`
Typescript yells at me

> (parameter) strapi: Strapi
'strapi' is declared but its value is never read.ts(6133)
Argument of type '({ strapi }: { strapi: Strapi; }) => { exampleService(...args: any[]): Promise<{ okay: boolean; } | { response: { okay: boolean; }; error: boolean; }>; }' is not assignable to parameter of type 'Service | ServiceCallback<Service>'.
  Type '({ strapi }: { strapi: Strapi; }) => { exampleService(...args: any[]): Promise<{ okay: boolean; } | { response: { okay: boolean; }; error: boolean; }>; }' is not assignable to type 'ServiceCallback<Service>'.
    Type '{ exampleService(...args: any[]): Promise<{ okay: boolean; } | { response: { okay: boolean; }; error: boolean; }>; }' is not assignable to type 'Service'.ts(2345)



This makes Typescript happy but I don't want to the replace a core service.
`
  // Method 3: Replacing a core service
  async findOne(entityId, params = {}) {
    return strapi.entityService.findOne('api::test.testservice', entityId, this.getFetchParams(params));
  }`

**Comment by StrapiShaun** [comment]
> ## Bug report
> ### Required System information
> * Node.js version: 14.16.1
> * NPM version: 6.14.12
> * Strapi version: 4.3.2
> * Database: mysql
> * Operating system: linux
> * Plugin Strapi version (devDependency): 4.1.8
> 
> ### Describe the bug
> I generated a plugin using the cli and followed all the steps from the documentation, but at `npm run build` it throws a typescript error:
> 
> ```
> ▶ npm run build                        
> 
> > file-bulk-uploader-by-url@0.0.0 build /server/src/plugins/test
> > tsc
> 
> server/controllers/my-controller.ts:6:8 - error TS2339: Property 'plugin' does not exist on type 'StrapiInterface'.
> 6       .plugin('test')
>          ~~~~~~
> ```
> 
> ### Steps to reproduce the behavior
> ```
> new/server/src  main ✗                                                                                                                                            1d23h ⚑ ◒  
> ▶ npm run strapi generate plugin              
> 
> > anteprojectos-pt_server@0.1.0 strapi /server
> > strapi "generate" "plugin"
> 
> ? Plugin name: test
> ? Choose your preferred language: TypeScript
> ✔  +! 26 files added
>  -> /plugins/test/strapi-admin.js
>  -> /plugins/test/strapi-server.js
>  -> /plugins/test/tsconfig.json
>  -> /plugins/test/server/bootstrap.ts
>  -> /plugins/test/server/destroy.ts
>  -> /plugins/test/server/index.ts
>  -> /plugins/test/server/register.ts
>  -> /plugins/test/admin/src/index.tsx
>  -> /plugins/test/admin/src/pluginId.ts
>  -> /plugins/test/server/config/index.ts
>  -> /plugins/test/server/content-types/index.ts
>  -> /plugins/test/server/controllers/index.ts
>  -> /plugins/test/server/controllers/my-controller.ts
>  -> /plugins/test/server/middlewares/index.ts
>  -> /plugins/test/server/policies/index.ts
>  -> /plugins/test/server/routes/index.ts
>  -> /plugins/test/server/services/index.ts
>  -> /plugins/test/server/services/my-service.ts
>  -> /plugins/test/admin/src/translations/en.json
>  -> /plugins/test/admin/src/translations/fr.json
>  -> /plugins/test/admin/src/utils/axiosInstance.ts
>  -> /plugins/test/admin/src/utils/getTrad.ts
>  -> /plugins/test/admin/src/components/Initializer/index.tsx
>  -> /plugins/test/admin/src/components/PluginIcon/index.tsx
>  -> /plugins/test/admin/src/pages/App/index.tsx
>  -> /plugins/test/admin/src/pages/HomePage/index.tsx
> ✔  ++ /plugins/test/README.md
> ✔  ++ /plugins/test/package.json
> ✔  -> 
> You can now enable your plugin by adding the following in ./config/plugins.ts
> ─────────────────────────────────
> export default {
>   // ...
>   'test': {
>     enabled: true,
>     resolve: './src/plugins/test'
>   },
>   // ...
> }
> ─────────────────────────────────
> 
> ▶ cd plugins/test 
> ▶ npm i
> ▶ npm run build
> > test@0.0.0 build /server/src/plugins/test
> > tsc
> server/controllers/my-controller.ts:6:8 - error TS2339: Property 'plugin' does not exist on type 'StrapiInterface'.
> 6       .plugin('test')
>          ~~~~~~
> Found 1 error in server/controllers/my-controller.ts:6
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! test@0.0.0 build: `tsc`
> npm ERR! Exit status 1
> ```
> 
> ### Expected behavior
> The example plugin should just work.
> 
> ### Additional context
> I found it weird that the devDependency in the plugin package.json didn't match the Strapi version:
> 
> ```
> "devDependencies": {
>     "typescript": "4.6.3",
>     "@strapi/strapi": "4.1.8"
>   },
> ```
> 
> So I updated it to match my installed version, which is 4.3.2. But then it started throwing even more errors, such as:
> 
> ```
> server/register.ts:3:39 - error TS2709: Cannot use namespace 'Strapi' as a type.
> 3 export default ({ strapi }: { strapi: Strapi }) => {
>                                         ~~~~~~
> ```
> 
> Also I tried to update the typescript version from 4.6.3 to 4.7.4, but it made no change.

This seems to be resolved by
1. updating the plugin dev dependency (./src/plugins/{plugin-name}/package.json) of `"@strapi/strapi": "4.1.8" -> "4.3.2"
2. changing the import declaration to `import { Strapi } from "@strapi/strapi"` in the following files: 
`bootstrap.ts`
`register.ts`
`index.ts`
`my-service.ts`
`my-controller.ts`
`destroy.ts`. 

Thanks to @matepaiva for helping to troubleshoot this issue.
