### ISSUE TITLE
Content Manger  Always Save any entry To Published Not To draft While Send The request From Api

### ISSUE THREAD

**Issue by MohamedSonata** [strapi/strapi#14005]
- Node.js version:16
- NPM version:6
- Strapi version:4.3.2
- Operating system:windows

### Describe the bug

while You're trying to add a new entry to and collection type created  From Api Request Strapi system save the entry to (Published) 
Not To (Draft) In First ... I think should there any option to sending it to draft or publish as i choose ... I hope If there's a solution...

NOTE*
This Only happen From Api Request  Not Like Strapi dashboard in first save it to draft then as i want To publish it or no  

### Screenshots

https://user-images.githubusercontent.com/96669613/183316223-e235a3ac-fd17-47c3-84b6-10bd2a5758ca.png

**Comment by derrickmehaffy** [comment]
It's already possible to do so, you just need to include the field `publishedAt` and set it to null when you send the post request.

Marking as closed as this isn't a bug.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by MohamedSonata** [comment]
Thanks Derrick For Help....
 Next Time I will Post strapi Forum

**Comment by derrickmehaffy** [comment]
> Thanks Derrick For Help.... Next Time I will Post strapi Forum

no problem :)
