### ISSUE TITLE
Content type attribute is ignored if attribute name is repeated but capitalised

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#14012]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.5.5
- Strapi version: 4.3.2
- Database: SQLite
- Operating system: MacOS Monterey 12.4

### Describe the bug

When creating (or editing) a content-type, in the content-type builder, and creating two attributes with the same name, but one capitalized. For example, in the getstarted project I modified the name field to Category:

![image](https://user-images.githubusercontent.com/20578351/183396928-f832ea1f-35b8-45d4-9f10-7ff632684c49.png)

When you try to create an entry, the capitalized field get's ignored

### Steps to reproduce the behavior

1. Go to Content-type Builder, and create a content-type with two attributes with the same name, but one capitalized.
2. Follow steps : https://scribehow.com/shared/Workflow__ir8xhVcbQt-a1K0DTNE-sQ

### Expected behavior

When creating an entry, the field with the capitalized name should appear when saving the entry.

### Screenshots

The request that is made when creating the entry
[POST] http://localhost:1337/content-manager/collection-types/api::category.category?plugins[i18n][locale]=en
Payload:
```json
{
    "id": 3,
    "datetime": null,
    "createdAt": "2022-08-08T10:28:32.898Z",
    "updatedAt": "2022-08-08T10:28:32.898Z",
    "publishedAt": null,
    "locale": "en",
    "category": null, // <--- There should be a Category attribute here too 
    "date": null,
    "addresses": [],
    "localizations": []
}
```

**Comment by derrickmehaffy** [comment]
@yanniskadiri / @marcoautiero I don't know who owns this one so I set to both your projects.

Most likely this needs to be looped in with: https://github.com/strapi/strapi/issues/1198 but it's not technically the word itself and more so the capitalization. We need to check that the field word doesn't exist regardless of capitalization (during the check convert all to lowercase)

**Comment by derrickmehaffy** [comment]
Merged into tracking issue: https://github.com/strapi/strapi/issues/16222
