### ISSUE TITLE
Requirement : Need to link a field to google places with latitude and longitude

### ISSUE THREAD

**Issue by gilson-perfomatix** [strapi/strapi#14024]
### Required System information

- Node.js version: v14.15.4
- NPM version: 6.14.16
- Strapi version: 4.2.0
- Database: Postgres : 8.6.0
- Operating system: ubuntu 18.10

Requirement : Need to link a field to google places with latitude and longitude. Any examples? Please drop in reply

**Comment by kasonde** [comment]
Hi @gilson-perfomatix, thanks for the question but I'm closing this is it's a question and not an issue. For this, please post your question either on our [Community Forum](https://forum.strapi.io) or in the general help section of our [Discord](https://discord.strapi.io) server.
