### ISSUE TITLE
Documentation plugin does not work properly

### ISSUE THREAD

**Issue by Ragin-LundF** [strapi/strapi#14020]
### Required System information

- Node.js version: v18.7.0
- NPM version: 8.15.0
- Strapi version: 4.3.2
- Database: Postgres
- Operating system: MacOS

### Describe the bug

I wanted to create an API documentation of my content library so that I can generate the client automatically.

According to the documentation (https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#settings) you can configure some things:

- Version (`$.info.version`) -> works
- Path for the API (`$.x-strapi-config.path`) -> does not work
- Definition der zu generierenden API (`$.x-strapi-config.pluginsForWhichToGenerateDoc`) -> does not work
(more I have not tested)

To test this I created the file `settings.json` under `/src/extensions/documentation/config/`. Since the version is overwritten, I strongly assume that the plugin has taken note of this file, but ignores the `x-strapi-config` section.

The content of the `settings.json`:

```json
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0"
  },
  "x-strapi-config": {
    "showGeneratedFiles": true,
    "path": "/api-docs",
    "pluginsForWhichToGenerateDoc": [
      "mycontenttest"
    ]
  }
}
```

Moreover, the documentation of the plugin at https://docs.strapi.io/developer-docs/latest/plugins/documentation.html#swagger-json-and-openapi-json-files says that it is possible to download the `openapi.json`, or `swagger.json` files.
Concrete:

```
You need to grant the permission to call the controller action to the roles that can have access.
```

However, I have found absolutely no way to assign these rights.

I think the documentation either needs some love here or some stuff is just broken....

### Steps to reproduce the behavior

1. Install `documentation` plugin
3. Add the `settings.json` (replace for example `mycontenttest` with `upload` to have a simple test)
4. Open the documentation (with `/documentation` for `pluginsForWhichToGenerateDoc` and `/api-docs` to see 404)
5. See error
6. Try to download the `/documenation/openapi.json` or `/documenation/swagger.json`

### Expected behavior

The documentation is available under `/api-docs` and shows for example only `upload` API.
I can download (and maybe have some permissions to set under settings) the API definitions.

**Comment by landoephan** [comment]
I'm having the same issue, is there any news here?

**Comment by landoephan** [comment]
Also, the overrides option doesn't work for me, hope that will be fixed, too

**Comment by markkaylor** [comment]
I believe these issues should have been resolved. The documentation for the plugin has been updated https://docs.strapi.io/dev-docs/plugins/documentation. I'll close this but if you find something described in the documentation that is not working properly please submit another issue.
