### ISSUE TITLE
4.3.x Admin build no longer uses config/server.js url

### ISSUE THREAD

**Issue by ajm13** [strapi/strapi#14023]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: postgres
- Operating system: macOS 12.3, and Amazon Linux 2

### Describe the bug

After installing 4.3.2 and building with `NODE_ENV=production npm run build`, the `build` folder is no longer generated in the project root. In addition, the `url` config in `config/server.js` seems to be ignored, as the admin panel requests resources from `localhost:1337` rather than the provided `url`.

### Steps to reproduce the behavior

1. Edit `config/server.js` and add `url` set to anything other than `localhost:1337`
2. Run `NODE_ENV=production npm run build`
3. Run `npm run start`
4. Open browser to `localhost:1337/admin`
5. Inspect network requests
6. See API hits (like `/admin/project-types`) still going to `localhost:1337`

### Expected behavior

The `url` provided in `config/server.js` should be used everywhere in the admin panel.

### Additional context

I have tested and verified that version 4.2.3 does not have this issue, and properly uses the provided `url` when building the admin panel. Additionally, 4.2.3 creates the `build` folder at project root when building.

**Comment by harrycarp** [comment]
Same issue here. Digging around the webpack build for the admin page, I found that http://localhost:1337 is hard-coded into the options.

```javascript
// \@strapi\admin\webpack.config.js

module.exports = ({
  cacheDir,
  dest,
  entry,
  env,
  optimize,
  pluginsPath,
  options = {
    backend: 'http://localhost:1337', // the culprit
    adminPath: '/admin/',
    features: [],
  },
  roots = {
    eeRoot: './ee/admin',
    ceRoot: './admin/src',
  },
  tsConfigFilePath,
}) => {

 // more code here

}
```

I'm still digging to see if there is a workaround, or if this is even the root of the issue. Some feedback from the Strapi Team would be wonderful :)

**Comment by harrycarp** [comment]
Okay so I got it working on my end with the following changes.

1. in `config/admin.js` the url parameter must be the absolute url where you access the admin page

```javascript
// /config/admin.js
module.exports = ({ env }) => ({
  url: 'https://cms.mywebsite.com/admin',
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
});
```

2. The STRAPI_ADMIN_BACKEND_URL must **NOT** include the `/admin` path

```bash
STRAPI_ADMIN_BACKEND_URL=https://cms.mywebsite.com
``` 
**NOT**
```bash
STRAPI_ADMIN_BACKEND_URL=https://cms.mywebsite.com/admin
```

3. Lastly, the url parameter in the `config/server.js` file must be the absolute path of the root of your CMS

```javascript
// config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'https://cms.mywebsite.com.au',
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

---

This is for a single instance setup where the admin panel is on the same server as the server code.

I hope this helps!

**Comment by ajm13** [comment]
Unfortunately that configuration did not seem to work for me, it still attempts to request urls like `localhost:1337/admin/project-type`. Running it locally this is easy to miss, but it is apparent if you change the port for the local server.

For example, the following configuration does **NOT** work:
```js
// /config/admin.js
module.exports = ({ env }) => ({
  url: 'http://localhost:8000/admin',
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
})
```

```js
// /config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 8000),
  url: 'http://localhost:8000',
  app: {
    keys: env.array('APP_KEYS'),
  },
})

```

```env
# .env
STRAPI_ADMIN_BACKEND_URL=http://localhost:8000
```

After building and starting the above with `NODE_ENV=production npm run build` and `npm run start`, the local server is properly hosted on port 8000, but when visiting the admin portal, there is a "Warning: An error occurred while requesting the API" and the console shows a failed request to `localhost:1337/admin/project-type`.

**Comment by ajm13** [comment]
Turns out this was caused by a build issue; webpack was complaining that the `src/admin` folder did not provide any inputs. Adding in an empty `webpack.config.example.js` file fixed the issue (even though that file isn't used).

**Comment by pandeyprafull** [comment]
@ajm13 Can you please elaborate your working strategy step by step...

**Comment by ajm13** [comment]
Yes, the strategy that worked for me was the following:

`config/admin.js` only contains `apiToken` and `auth`

`config/server.js` contains:
```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('URL', 'http://localhost:1337'),
  app: {
    keys: env.array('APP_KEYS'),
  },
})
```

`src/admin/webpack.config.js` (must be created if it doesn't exist):
```js
'use strict'

/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
  return config
}
```

When deploying to production, I have `URL` in the env set to the address of my deployed Strapi instance (e.g. `https://cms.example.com`)

**Comment by aiokr** [comment]
have no use, main.d40f9ca1.js:2225 Refused to connect to 'http://localhost:1337/admin/init' is always

**Comment by twofingerrightclick** [comment]
> Yes, the strategy that worked for me was the following:
> 
> `config/admin.js` only contains `apiToken` and `auth`
> 
> `config/server.js` contains:
> 
> ```js
> module.exports = ({ env }) => ({
>   host: env('HOST', '0.0.0.0'),
>   port: env.int('PORT', 1337),
>   url: env('URL', 'http://localhost:1337'),
>   app: {
>     keys: env.array('APP_KEYS'),
>   },
> })
> ```
> 
> `src/admin/webpack.config.js` (must be created if it doesn't exist):
> 
> ```js
> 'use strict'
> 
> /* eslint-disable no-unused-vars */
> module.exports = (config, webpack) => {
>   return config
> }
> ```
> 
> When deploying to production, I have `URL` in the env set to the address of my deployed Strapi instance (e.g. `https://cms.example.com`)


Thanks for documenting! 
This was a little bit frustrating to have to do - 1337 not available on my machine currently. Took me a good few minutes. For strapi 4.10.6. I only had to add the file. No other URL config required.
