### ISSUE TITLE
Components are not removed from database when removing entity

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#14039]
### Required System information

Node.js version: 16.15.0
NPM version: 8.5.5
Strapi version: 4.3.2
Database: SQLite
Operating system: MacOS Monterey 12.4

### Describe the bug

When deleting an entity from a collection type, that has a Component attribute/field. The component data is not removed from the database.

### Steps to reproduce the behavior

I am using the get started project from the Strapi repository. 

1. I create an entity that has a component (Address Content-type, which has a repeat_req component)
2. Entity and the components are stored in the database. I can see (again, in the get started project), in the table `components_blog_test_comos` the components are stored there.
3. I delete the same entity.
4. The components are still stored in the `components_blog_test_comos` table.

### Expected behavior

When deleting an entity, the components should also be removed from the database.

### Additional context

The problem is in  `packages/core/strapi/lib/services/entity-service/index.js`  in the delete function:

```js
  async delete(uid, entityId, opts) {
    // ...

    await db.query(uid).delete({ where: { id: entityToDelete.id } }); // <=== The entity is deleted before the components. It should be the other way around.
    await deleteComponents(uid, entityToDelete); // <=== This searches for the entity components, but the entity is already deleted.

    // ...
  },

```

**Comment by derrickmehaffy** [comment]
I believe we should be able to solve this by modifying the foreign key constraints to enable cascade delete instead of doing it on the logic side.

**Comment by Marc-Roig** [comment]
@derrickmehaffy makes sense actually. My first guess was to first delete the components before the entity.
But It makes more sense just having a cascade delete, I will discuss it with @petersg83 tomorrow.
