### ISSUE TITLE
Webpack - Not coordinated build command / Unable to serve the build folder due to bad imports. 

### ISSUE THREAD

**Issue by dl3c01n** [strapi/strapi#14049]
## Bug report
Hello,

I found something because i wanted to host the strapi "backend" to AWS S3, and it said "404 not found" for all the javascript files imported inside "index.html" of the build.

### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4
- Database: PostgreSQL
- Operating system: macOS

### Describe the bug
When you want to host the strapi "backend" application, you have to run the command "yarn build".

After this command is executed, you will get a directory called "build" which includes every files compiled.

The bug comes here, when you want to host, or serve this index.html, you will get a white page, why ? Because it imports javascript files from "/admin/file.js" which is not a valid path due to webpack build.

### Steps to reproduce the behavior

1. Run the "yarn build" or "npm run build"
2. Serve your index.html (cloud or local)
3. Navigate to the url
4. See error (white page)

### Expected behavior

The expected behavior is : Strapi Backend works.

However, i found the fix.

I made a question on StackOverFlow, so here is the link, with the fix i found. 

https://stackoverflow.com/questions/73302164/webpack-change-src-path-of-javascript-files-in-index-html?noredirect=1#comment129453799_73302164

**Comment by derrickmehaffy** [comment]
The build for Strapi javascript does not include the backend, only the admin. This is intended and the only exception to this is for typescript projects which are completely built and dumped into a dist.

For the moment we have no plans to change this, Strapi javascript projects need to be ran as a service but you can serve the admin panel from S3 if you wanted.
