### ISSUE TITLE
Property Comment

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#1405]
Put comments on fields so that we can understand the earlier reasoning behind the introduction of the field in the first place. If you look at MySQL, there is a field comment that helps explaining things a bit, more like the description for content type.

**Comment by derrickmehaffy** [comment]
@emahuni can you explain a bit more and provide a few examples?

**Comment by lauriejim** [comment]
Hello @emahuni , please follow the issue template so we can get a better understanding about the origin of your bug or your feature request.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
