### ISSUE TITLE
 Internal Server Error 500 returned when filtering with a field that doesn't exist in the table schema

### ISSUE THREAD

**Issue by yossefEl** [strapi/strapi#14060]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: Mysql
- Operating system: Debian GNU/Linux 10 (buster)

### Describe the bug

I was trying to filter the data with (filters[active][$eq]=true)  but the field active doesn't exist in the table, the expected response in this case is 200 with empty data but I get a 500 Internal Server Error
 
### Steps to reproduce the behavior

1. Try to filter with a field that doesn't exist in the table 

### Expected behavior

I think the expected response, in this case, is status Code 200 with empty data Or a response ignoring the filter.

### Screenshots

<img height="200" alt="Screen Shot 2022-08-10 at 12 47 17" src="https://user-images.githubusercontent.com/39236784/183893677-d25a48d6-8476-49ae-b239-2889960c0387.png" float="right">

Thank you

**Comment by vikasvmads** [comment]
Hi, If the issue is still open , I want to work on this. :)

**Comment by Marc-Roig** [comment]
Hi @vikasvmads  :) It is still open, and there is an ongoing discussion about how to fix this in https://github.com/strapi/strapi/pull/14081.

The current point of the discussion is, that we should return a 500 error, when filtering by a nonexisting field, to not leak the database structure.

**Comment by vikasvmads** [comment]
Thanks, @Marc-Roig. I will wait for your response. :)

**Comment by Aurelsicoko** [comment]
**Issue was linked to Harvestr Discovery:**  [Deployment](https://app.harvestr.io/components/0/list/r8EfG_FjD)
