### ISSUE TITLE
The GraphQL plugin doesn't work.

### ISSUE THREAD

**Issue by LSLobato** [strapi/strapi#14067]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.3
- Database: MySQL/ GraphQL
- Operating system: Linux Ubuntu

### Describe the bug

After installing the GraphQL dependency, Strapi returned the error:
error: merge.extractExtensionsFromSchema is not a function
TypeError: merge.extractExtensionsFromSchema is not a function

### Steps to reproduce the behavior

1. execute 'yarn strapi install graphql' on terminal
2. add this configs on config/plugin.js
  graphql: {
    config: {
      endpoint: '/graphql',
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
3. execute 'yarn develop' on terminal

### Expected behavior

Expected behavior is to run strapi and admin panel

### Screenshots

![image](https://user-images.githubusercontent.com/28567201/183980880-ce3a472c-5998-409e-83ab-e8e249513638.png)

### Resolution

this bug can be resolved by changing the mergeSchema function, removing the merge schemas.
The extractExtensionsFromSchema is not a function and this file do not exists on directory: /node_modules/@graphql-tools/merge

![image](https://user-images.githubusercontent.com/28567201/183983637-bbf5dc0d-7ef2-4ab9-93c7-a4210e2278c3.png)

![image](https://user-images.githubusercontent.com/28567201/183983951-8539d913-7387-4291-af6a-a31f66a17389.png)

**Comment by romulopin** [comment]
Parabéns! funcionou em nossa aplicação perfeitamente. valeu.

**Comment by petersg83** [comment]
Hello :) I recommend to read this issue : https://github.com/strapi/strapi/issues/14048
The fix has been released already :)

I'm closing this issue since it's a duplicate
