### ISSUE TITLE
Json payload

### ISSUE THREAD

**Issue by johntom** [strapi/strapi#1406]
**Informations**
- **Node.js version**:9.5.0
- **npm version**:4.1.2
- **Strapi version**:3.0.0-alpha.12.4
- **Database**:Mongo v2.4.10
- **Operating system**:win10

**What is the current behavior?**
Client Aurelia.io (latest) using fetch
The following works when sending the following
let product = `name=${this.name.value}&rating=${rating.value}` 
addbakery(product) {
        var url =    'http://localhost:1337/'bakery';
        return fetch(url, {
            method: 'post',
            headers: {
                'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
            },
               body: product
        }).then((res) => res.json());
    }

When I try to post valid json (I need to use json to convert older apps) 
  let product = `{name:${this.name.value},rating:${rating.value}}` 
  addbakeryJ(product) {
        var url =    'http://localhost:1337/'bakery';
        return fetch(url, {
            method: 'post',
           // mode: 'cors',
            headers: {
                 'Accept': 'application/json',
                      'Content-Type': 'application/json',
            },
           body: JSON.stringify(product)
        }).then((res) => res.json());
    }
{ Error: invalid JSON, only supports object and array
    at parse (D:\Frameworks\Strapi-Gatsby\api\node_modules\co-body\lib\json.js:60:13)
    at D:\Frameworks\Strapi-Gatsby\api\node_modules\co-body\lib\json.js:45:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) status: 400, body: '"{name:sundae 4,rating:3}"' }
[2018-06-17T17:57:44.779Z] debug POST /bakery (30 ms)

**Steps to reproduce the problem**
Normal strapi cli 

**What is the expected behavior?**
accept both types of data payloads

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Something seems odd, I dont think `{name:sundae 4,rating:3}` is valid json.

Also @johntom can you use code blocks where applicable to make it a little easier to read?

**Comment by derrickmehaffy** [comment]
Just did some testing on MySQL @lauriejim @Aurelsicoko the json data type isn't properly being handled on bookshelf knex either. I'm getting errors on trying to save data to the DB:

```
[2018-06-17T21:53:48.801Z] error insert into `testmodels` (`created_at`, `data`, `test`, `updated_at`) values ('2018-06-17 14:53:48.790', {"a":5,"b":10}, 'test2', '2018-06-17 14:53:48.790') - ER_BAD_FIELD_ERROR: Unknown column 'a' in 'field list'
```
