### ISSUE TITLE
Call to /api/auth/<provider>/callback?access_token=<the access token> returns a 404

### ISSUE THREAD

**Issue by jumptrnr** [strapi/strapi#14069]
### Required System information

- Node.js version: v14.19.3
- NPM version: 6.14.17 (but use yarn 1.22.19)
- Strapi version: 4.3.3
- Database: MariaDB/GraphQL
- Operating system: OSX

### Describe the bug

Using oAuth provider (Google at least) - the call to the strapi server for callback returns a 404 
ie the strapi log file shoes: 

`http: GET /api/auth/google/callback?access_token=<my returned access token> (11 ms) 404`

### Steps to reproduce the behavior

1. Start with working oauth in 4.3.2 (google at least)
2. Update to 4.3.3
3. login from oauth on client (nuxt)
4. Strapi server shows a 404 error
5. Revert to 4.3.2 and the error goes away

Local auth worked fine.

### Expected behavior

As in 4.3.2 - expect successful login

### Screenshots

N/A

### Code snippets

Error showed up in 4.3.3 and goes away if reverting back to 4.3.2

### Additional context

N/A

**Comment by digitaldesigndj** [comment]
This route should return a `500` when it fails. The 404 is a problem. I have seen it affecting both the google and discord providers, however it does not seem to affect the local auth stuff. Rolling back the upgrade restored us.

**Comment by digitaldesigndj** [comment]
Just a guess. But I would start with code that adds the reset password route.

**Comment by alexandrebodin** [comment]
This is now fixed in https://github.com/strapi/strapi/releases/tag/v4.3.4.
