### ISSUE TITLE
Database is reset on every reload after applying TypeScript support to the project

### ISSUE THREAD

**Issue by filson14-mq** [strapi/strapi#14065]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.3.3
- Database: sqlite
- Operating system: macOS

### Describe the bug

After applying TypeScript support to an existing Strapi project (following [this instruction](https://docs.strapi.io/developer-docs/latest/development/typescript.html#add-typescript-support-to-an-existing-strapi-project) ) the database is being reset every time we restart the app (which is done also while adding new content type). That includes user accounts, media library state etc.

### Steps to reproduce the behavior

1. Follow the instruction above to add TS support for your existing project using sqlite locally (add tsconfig files etc)
2. Rebuild project with npm run build
3. Run app with npm run develop
4. Create account and log in
5. Add new content type in Strapi
6. See the problem (app shows registration form as there is no account after restart).

You can also stop running app and run it again to see the problem (no need to create content).

### Expected behavior

Database should be preserved as before using TS.

### Screenshots

![obraz](https://user-images.githubusercontent.com/99251472/183958238-dd783c91-85fd-489d-8c34-d6b5f3b6571c.png)

### Additional context
Just to be clear. The problem is seen on local machine while developing strapi app. No cloud deployment or docker image building is involved (as it is expected behaviour that filesystem-database is reset in that kind of environment).

**Comment by kasonde** [comment]
Hi @filson14-mq I take it that you came from a version before Typescript, updated and then you're facing this issue right?

**Comment by kasonde** [comment]
HI @filson14-mq I've created a PR for a migration guide here: https://github.com/strapi/documentation/pull/1054
Ideally you can fix this by appending an additional: `..` in your database filename string. i.e:

Before: 
```js
filename: path.join(__dirname, '..', env('DATABASE_FILENAME', '.tmp/data.db')),
```

After:
```js
filename: path.join(__dirname, '..', '..', env('DATABASE_FILENAME', '.tmp/data.db')),
```

**Comment by filson14-mq** [comment]
> Hi @filson14-mq I take it that you came from a version before Typescript, updated and then you're facing this issue right?

Yes, that is correct.

> Ideally you can fix this by appending an additional: .. in your database filename string. i.e:

Great, thank you!
