### ISSUE TITLE
GraphQL fetching default locale only

### ISSUE THREAD

**Issue by AvinashUtekar** [strapi/strapi#14064]
### Required System information

- Node.js version: 14.20.0
- NPM version: 6.14.17
- Strapi version: 4.2.0
- Database: postgres
- Operating system: windows10

### Describe the bug

I am trying to fetch data based on locale with graphql, but it fetching data of locale which is set as default localization in ,
`global settings/internationalization/` 

### Steps to reproduce the behavior

- Go to  :  

1. install i18 plugin
2. create new collection type and Enable localization for this Content-Type
3. go to  global settings/internationalization
4. click on add new locale 
5. add new locale (eg: add "pt" locale and **set as default locale**) 
6. got collection type that we created earlier and add some entries for both locales (for 'en' and 'pt')
7. now go to http://localhost:1337/graphql and add bellow query
```
{
  document_name  (filters: { locale: { eq: "en" } }) {
    data {
      id
    }
  }
}
```
8. if run this query it will not show entries which has locale is **en** it will return empty array , because we set '**pt**' as default locale in 5th step.
9. now if we set 'en' as default locale in global settings/internationalization and then if we hit the same query it will show the result.
10. in REST API this locale query working fine , but in graphql its a issue
11. please let me know if its a bug or i missing some steps

### Screenshots

![image](https://user-images.githubusercontent.com/87367466/183950229-72f01890-cb1e-48cb-8aca-83d8fa089a59.png)

**Comment by petersg83** [comment]
Hello @AvinashUtekar :) Have you check this part of the documentation: https://docs.strapi.io/developer-docs/latest/plugins/i18n.html#getting-localized-entries-with-graphql ?

**Comment by AvinashUtekar** [comment]
> Hello @AvinashUtekar :) Have you checked this part of the documentation: https://docs.strapi.io/developer-docs/latest/plugins/i18n.html#getting-localized-entries-with-graphql ?

thank you.
