### ISSUE TITLE
# Media Library not accepted long text Caption

### ISSUE THREAD

**Issue by DucSilva** [strapi/strapi#14071]
I have a trouble when i used Media Libary that it's not accept my image upload with Caption long text . Any body plz help me?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
