### ISSUE TITLE
TS config is not properly detected on Windows

### ISSUE THREAD

**Issue by florianmrz** [strapi/strapi#14079]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.12.1
- Strapi version: 4.3.3
- Database: Postgres
- Operating system: **Windows**

### Describe the bug

TSConfig detection breaks on windows due to windows path style.

### Steps to reproduce the behavior

1. Be on Windows
2. Start a Strapi TS project
3. It won't be able to detect that it's a TS project and fail e.g. when loading the db config

### Expected behavior

The TS config detection should work regardless of OS / path style.

### Code snippets

This bug was introduced with https://github.com/strapi/strapi/pull/13937.
The issue is in `packages\utils\typescript\lib\utils\get-config-path.js`.

```js
const dirAbsolutePath = path.resolve(dir);
// ... should be ...
const dirAbsolutePath = path.resolve(dir).split(path.sep).join(path.posix.sep);
```
This makes sure that paths are using the same separators on all OS.
Since the check below uses `String.startsWith()` this will fail if the path separator is not the same as the one returned from `ts.findConfigFile()`.

https://github.com/strapi/strapi/blob/c0f0ae5049cf65c9b6700204d4a494c661a8ee33/packages/utils/typescript/lib/utils/get-config-path.js#L19-L26

**Comment by saevarb** [comment]
I can confirm that this is an issue for us using 4.3.8 under Windows 10. We patched it ourselves with `patch-package`:

```diff
-  return configFilePath.startsWith(dirAbsolutePath) ? configFilePath : undefined;
+  return configFilePath.startsWith(dirAbsolutePath.replaceAll("\\", "/")) ? configFilePath : undefined;

```

**Comment by MaksZhukov** [comment]
Any updates?

**Comment by South-Paw** [comment]
See #13237, here is a local change you can make [to fix it](https://github.com/strapi/strapi/issues/13237#issuecomment-1258045747)

There is also PR #14088 which fixes this this that was put up a month ago but the Strapi team hasn't merged it for whatever reason.
