### ISSUE TITLE
Media Library Warning an error occurred

### ISSUE THREAD

**Issue by mhayta** [strapi/strapi#14086]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.17.0
- Strapi version: v4.3.4
- Database: MySQL
- Operating system: CentOS Linux release 7.9.2009 (Core)

### Describe the bug

Last few days media library show error and files not listed

### Steps to reproduce the behavior

--When i click media library, 4 times "warning an error occured" popup shown and not listed uploded media. console 404 error :https://domain.com/upload/files?sort=updatedAt:DESC&page=1&pageSize=10&filters[$and][0][folder][id][$null]=true .
-- When i try to upload files from content manager same error and "Woops! Something went wrong. Please, try again." error

node_modules, .cache, build folders and package.json and package-lock.json files deleted several times and reinstall with npm install npm build have no error.

update latest version all packages
"dependencies": {
    "@strapi/design-system": "1.2.1",
    "@strapi/plugin-i18n": "4.3.4",
    "@strapi/plugin-users-permissions": "4.3.4",
    "@strapi/provider-email-sendgrid": "^4.3.4",
    "@strapi/strapi": "4.3.4",
    "mysql": "^2.18.1",
    "slugify": "^1.6.5",
    "sqlite3": "5.0.11",
    "strapi-plugin-ckeditor5": "2.1.1-rc.1",
    "strapi-plugin-menus": "^1.0.0",
    "strapi-plugin-navigation": "^2.2.1",
    "strapi-provider-email-smtp": "^1.0.3"
  },

### Screenshots

https://user-images.githubusercontent.com/13572595/184239003-fc37fd1d-489c-4501-9c29-e35a1bdee0cf.mp4

**Comment by kasonde** [comment]
Hi, could you please share the logs from your backend and also the response message from those failed network requests? Also, did this happen suddenly for you? Or has the media library never worked for you?

**Comment by mhayta** [comment]
media library was work normal since last 6 month. its happened suddenly while upload new files with my teammate. NGINX logs have no error record

**Comment by mhayta** [comment]
> media library was work normal since last 6 month. its happened suddenly while upload new files with my teammate. NGINX logs have no error record

**Comment by mhayta** [comment]
> Hi, could you please share the logs from your backend and also the response message from those failed network requests? Also, did this happen suddenly for you? Or has the media library never worked for you?

media library was work normal since last 6 month. its happened suddenly while upload new files with my teammate. NGINX logs have no error record

**Comment by mhayta** [comment]
i ve found that problem! modsecurity rule 980130, 949110, 942290 sql injection. But i have to disabled rules for domain
