### ISSUE TITLE
Generic error is thrown instead of detailed error when creating new collection

### ISSUE THREAD

**Issue by Los** [strapi/strapi#14094]
### Required System information

- Node.js version: v16
- NPM version: 8.11.0
- Strapi version: 4.3.4
- Database: Postgres
- Operating system: MacOS

### Describe the bug

I've tried to create a new collection type and received an generic error that I had no idea what was going on.

Once I took a look on console, it had a lot of more detail about it. I think the message inside `data.error.details` should be thrown instead of the generic error on alert

### Steps to reproduce the behavior

1. Go to Content Type Builder
2. Create new collection type
3. Create some text fields
4. Create a unique ID field without attached field filled
5. Try to save the collection
6. See the error

### Expected behavior

The error message inside alert should be like the erro message in console

### Screenshots

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/4088193/184420697-d6996a4a-1393-44ce-9675-2b99273ba532.png">

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/4088193/184420746-f63f54bc-f87f-42d5-8f6e-aa32d5e1123f.png">

### Code snippets

No code snippets

### Additional context

No more context needed

**Comment by derrickmehaffy** [comment]
Can you provide some screenshots of the UID field (both the normal settings and advanced settings?)

Selecting a field to attach to should be optional :thinking:

**Comment by Los** [comment]
> Can you provide some screenshots of the UID field (both the normal settings and advanced settings?)
> 
> Selecting a field to attach to should be optional 🤔

Sure! Yeah, thats what I thought as well

<img width="852" alt="image" src="https://user-images.githubusercontent.com/4088193/184421361-fa0e1822-a48f-4b0b-aec6-a981f06f7148.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/4088193/184421380-6a437776-5792-4437-92cf-bdf2e731d187.png">

**Comment by derrickmehaffy** [comment]
That's quite odd, I see nothing wrong here. you didn't by chance try to manually modify the content-type schema.json did you, just used the content-type builder to build this whole model?

**Comment by Los** [comment]
> That's quite odd, I see nothing wrong here. you didn't by chance try to manually modify the content-type schema.json did you, just used the content-type builder to build this whole model?

Yeah, just content-type builder

**Comment by derrickmehaffy** [comment]
Alright let me see on a fresh project if I can reproduce this, normally yes I do agree with you we need to make the error messages show up in the admin more consistent which is something we are already aware of but the UID shouldn't be throwing that error to begin with.

**Comment by Los** [comment]
> Alright let me see on a fresh project if I can reproduce this, normally yes I do agree with you we need to make the error messages show up in the admin more consistent which is something we are already aware of but the UID shouldn't be throwing that error to begin with.

Sure! That's a pretty new project, I started it on 4.3.2 and the only thing that I did so far, was upgrade it to 4.3.4. Thats the first collection that I try to create

I see another issue.

I try to remove the attached field/add and it keeps on forever loading once I save the collection

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/4088193/184422221-4bba01e5-272e-4049-9190-c8493cf8a66c.png">

I can give you access to the environment if you want to take a look on it. I am using Heroku to host it

**Comment by derrickmehaffy** [comment]
Well I can't seem to reproduce and get that error :thinking: 

https://www.loom.com/share/e242f3d456e34bc19e32bfdb32349a03

Something to keep in mind however that the Content-type builder will not/should not work in Heroku as it saves the new schema to the filesystem and heroku wipes the file system when it goes to "sleep" so we do not support running in develop mode while the application is deployed else-where, only locally on your host machine.

**Comment by derrickmehaffy** [comment]
See this FAQ on why: https://docs.strapi.io/developer-docs/latest/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

**Comment by Los** [comment]
Thats good info! I will try to reproduce the issue locally and let you know

**Comment by Los** [comment]
@derrickmehaffy not able to reproduce it locally. Might be an issue with Heroku or their environment as well.

But, should I keep the error message issue opened?

**Comment by derrickmehaffy** [comment]
I think for now we can close this as under normal conditions that error shouldn't come up and usually we handle errors gracefully.

Worst case if someone else runs into something similar we can come back and take a look but this is the first time I've seen this one.

Thank you though :)
