### ISSUE TITLE
TypeError: l.customReplacements is not iterable  in development mode

### ISSUE THREAD

**Issue by sleeporsmile** [strapi/strapi#14098]
### Required System information

- Node.js version: 16.16.0
- YARN version: 3.2.2
- Strapi version: 4.3.3-4.3.4
- Database: sqlite
- Operating system: mac os

### Describe the bug

Problem with content type builder. When switch to Content-Type Builder page from Content Manager  - shows white screen and TypeError in console.
Work good in prev version 4.3.2

### Steps to reproduce the behavior

1. Run in dev mode 
2. Click to Content Manager
3. Click to Content-Type Builder
4. See error in console and white screen

### Screenshots
<img width="906" alt="Снимок экрана 2022-08-14 в 10 59 55" src="https://user-images.githubusercontent.com/43747618/184527909-684d2d78-99ef-44a7-8a9b-5cb554d25b20.png">

**Comment by derrickmehaffy** [comment]
Unable to reproduce, can you please try without Yarn Berry? Also based on that URL, is this running local on your host machine or just in your network? We do not support `development` mode using the `develop` command outside of your host machine.

**Comment by sleeporsmile** [comment]
> Unable to reproduce, can you please try without Yarn Berry? Also based on that URL, is this running local on your host machine or just in your network? We do not support `development` mode using the `develop` command outside of your host machine.

It just renamed localhost, any way in prev versions work good.

**Comment by derrickmehaffy** [comment]
> > Unable to reproduce, can you please try without Yarn Berry? Also based on that URL, is this running local on your host machine or just in your network? We do not support `development` mode using the `develop` command outside of your host machine.
> 
> It just renamed localhost, any way in prev versions work good.

Regardless if it worked or not, I wasn't able to reproduce and we don't currently support yarn berry due to some dependencies issues we have to fix.

Do you have any community plugins installed or could you provide your package.json?

**Comment by sleeporsmile** [comment]
> > > Unable to reproduce, can you please try without Yarn Berry? Also based on that URL, is this running local on your host machine or just in your network? We do not support `development` mode using the `develop` command outside of your host machine.
> > 
> > 
> > It just renamed localhost, any way in prev versions work good.
> 
> Regardless if it worked or not, I wasn't able to reproduce and we don't currently support yarn berry due to some dependencies issues we have to fix.
> 
> Do you have any community plugins installed or could you provide your package.json?

  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@strapi/plugin-i18n": "^4.3.4",
    "@strapi/plugin-seo": "^1.7.4",
    "@strapi/plugin-users-permissions": "4.3.4",
    "@strapi/strapi": "4.3.4",
    "better-sqlite3": "^7.6.2",
    "qs": "^6.11.0",
    "strapi-plugin-config-sync": "^1.0.3",
    "strapi-plugin-import-export-entries": "^1.10.1",
    "strapi-plugin-placeholder": "4.1.5",
    "strapi-plugin-preview-button": "^0.3.5",
    "strapi-plugin-rest-cache": "^4.2.4",
    "strapi-provider-rest-cache-memory": "^4.2.4"
  },

**Comment by derrickmehaffy** [comment]
Can you try removing these four as I'm not familiar with those (the others we test pretty regularly)

- `"@_sh/strapi-plugin-ckeditor": "^1.1.2",`
- `"strapi-plugin-import-export-entries": "^1.10.1",`
- `"strapi-plugin-placeholder": "4.1.5",`
- `"strapi-plugin-preview-button": "^0.3.5",`

**Comment by sleeporsmile** [comment]
> Can you try removing these four as I'm not familiar with those (the others we test pretty regularly)
> 
> * `"@_sh/strapi-plugin-ckeditor": "^1.1.2",`
> * `"strapi-plugin-import-export-entries": "^1.10.1",`
> * `"strapi-plugin-placeholder": "4.1.5",`
> * `"strapi-plugin-preview-button": "^0.3.5",`
> 
> Then rebuild your admin and restart

I removed strapi-plugin-import-export-entries and it has resolved my problem
