### ISSUE TITLE
Probleme with Graphql : roles

### ISSUE THREAD

**Issue by titoff002** [strapi/strapi#14096]
Hello,

I would like to retrieve all the roles of the user, but it does not work.

My code : 

```
mutation{
  login(input: {
    identifier: "XXX",
    password: "XXX"
  }){
    user{
      id
      username
      email

      roles{
        name
        type
        description
      }
    }
    jwt
  }
}
```

This code return errors : 

```
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"roles\" on type \"UsersPermissionsMe\". Did you mean \"role\"?",
        "locations": [
          {
            "line": 9,
            "column": 7
          }
```

How to attach roles ?

Have you an example ?

Thanks.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
