### ISSUE TITLE
Documentation plugin generates flattened schema components

### ISSUE THREAD

**Issue by ndawg** [strapi/strapi#14097]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: Postgres
- Operating system: Linux (Ubuntu via WSL 2)

### Describe the bug

The schema types produced by the documentation seem to be generating improperly due to how many properties are shoved inside a single response. Consider the following collection type:
![Image](https://i.imgur.com/7xnYyzW.png)

There are two relevant schema components generated, `ProductResponse` and `ProductListResponse`. One might assume that `ProductListResponse` utilizes the schema of `ProductResponse` but that isn't the case - it [nests all the properties inside as an array](https://hastebin.com/uzarotefet.json). This is really bad for [generated client models](https://hastebin.com/sisohexuza.typescript). Similarly, `ProductResponse` [doesn't have some common schema](https://hastebin.com/vaxayilomi.json) for folders, images, files, etc.

### Steps to reproduce the behavior

1. Create a simple collection type schema
2. Generate an OpenAPI spec with the documentation plugin
3. Notice the structure of the spec

### Expected behavior

I would expect the plugin to generate a `schema` for each of the types defined in strapi. For example, `Product` should have its own schema that is utilized in a `ProductResponse` and `ProductListResponse`. In addition, common schema types like images, folders, files, etc. should also have their own schema types.

### Additional context

The generated schema is actually [broken right now](https://github.com/strapi/strapi/issues/13885), so this issue will probably need to wait on a fix for that.

Also see: [Components Section](https://swagger.io/docs/specification/components/) on the Swagger docs

**Comment by ruiaraujo012** [comment]
Same here, I would want to use this to generate code for my react application but the types are incorrectly generated.

**Comment by ruiaraujo012** [comment]
Any update on this?
