### ISSUE TITLE
After running yarn build, media uploads stops working

### ISSUE THREAD

**Issue by julianwagle** [strapi/strapi#14101]
### Required System information

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version: 4.3.4 .. also tried with 4.3.3
- Database: MySQL
- Operating system: MacOs

### Describe the bug

After running `yarn build` I am no longer able to upload photos

### Steps to reproduce the behavior

1. `yarn create strapi-app my-project --ts && cd my-project && yarn develop`
2. Go to media library and add all the photos you want, it should work
3. `yarn build && yarn develop`
4. Go back to media library and try to upload anything. It will throw the following error:

[2022-08-15 00:56:25.293] error: invalid JSON, only supports object and array
Error: invalid JSON, only supports object and array
    at parse (/.../my-project/node_modules/co-body/lib/json.js:60:13)
    at /.../my-project/node_modules/co-body/lib/json.js:45:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /.../my-project/node_modules/@strapi/strapi/lib/middlewares/body.js:35:9
    at async /.../my-project/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /.../my-project/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/.../my-project/node_modules/@koa/cors/index.js:95:16)
    at async /.../my-project/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/.../my-project/node_modules/koa-session/index.js:41:7)
    at async /.../my-project/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5

### Expected behavior

Media should be able to be uploaded when using the media uploader

### Additional context

I have tried with both the standard koa uploaded and the cloudinary uploader and i get the same error both times. I have tried adding in the recent updates from [#13992](https://github.com/strapi/strapi/pull/13992) since they were related to cloudinary error reporting but it made no difference in the error message.

**Comment by derrickmehaffy** [comment]
Unable to reproduce given the current steps, have you done any customization or have any community plugins installed?

**Comment by julianwagle** [comment]
> Unable to reproduce given the current steps, have you done any customization or have any community plugins installed?

Hey Derrick, I took note of what you said and went through all my dependencies and found that it was `"axios": "0.27.0",` that was causing the issue. Likely a conflict with koa. Not sure if you guys would rather keep this issue open until the dependency is supported or if you'd rather close the issue and add this to a list of unsupported packages.
