### ISSUE TITLE
Couldn't able to save Hindi Text

### ISSUE THREAD

**Issue by arjun-rage** [strapi/strapi#14107]
Hi Team,

I was trying to save the data for **UI Navigation plugin** which is Hindi text , but it is not saving. No error has been throwed.

**Comment by arjun-rage** [comment]
![ui nav error](https://user-images.githubusercontent.com/111339644/184814676-5d3146bf-e066-4031-b518-535875ab635c.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
