### ISSUE TITLE
.gitignore missing database file

### ISSUE THREAD

**Issue by udf2457** [strapi/strapi#14106]
Please see my pull request #14105.

I don't want to be forced to sign the CLA just to submit a one-line amendment to the .gitignore.

By way of backgound, the credentials got saved there by the Strapi setup tool (Postgres DB option was selected but I guess it will do the same for other databases).

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by udf2457** [comment]
@derrickmehaffy You dismissed my PR out of hand with a misleading comment.

You stated "Our default config file uses environment variables and not static strings.".

This is not true. 

As I pointed out, my database file was created automatically by the Strapi setup tool. I did not populate it myself. As I said, I selected Postgres as the database option.

Therefore it is untrue that your "default" uses environment variables, because your very own tool populated the credentials into that database file !

**Comment by udf2457** [comment]
@derrickmehaffy 

I'm sorry but you are making absolutely zero sense.

Your setup tool appears to be perfectly capable of creating an env file with the following:

```
HOST=
PORT=
APP_KEYS=
API_TOKEN_SALT=
ADMIN_JWT_SECRET=
JWT_SECRET=
```

So why are you so against putting database credentials in the env file that your tool creates ?

**Comment by derrickmehaffy** [comment]
Because those are automatically generated, not user input.

Database credentials will almost always differ between environments, especially since we strongly recommend using specific environment configurations: 

https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#environment-configurations

---

I understand your frustrations but please do be considerate of our Code of Conduct.

**Comment by derrickmehaffy** [comment]
Appreciate your feedback thank you, sorry to see you go and hopefully we see you again.

I'll consider this issue resolved as "agree to disagree"
