### ISSUE TITLE
overlay is closing when text is selected because mouseup is triggered when not hovered over overlay

### ISSUE THREAD

**Issue by jonasfrey** [strapi/strapi#14110]
### Required System information
- Node.js version: v12.22.12
- NPM version: 6.14.16
- Strapi version: 
    "@strapi/strapi": "4.1.12",
    "@strapi/plugin-users-permissions": "4.1.12",
    "@strapi/plugin-i18n": "4.1.12",
- Database:
    "better-sqlite3": "7.4.6"
- Operating system:
Description:    Ubuntu 20.04.4 LTS

### Describe the bug
selecting text on an overlay will close the overlay

### Steps to reproduce the behavior

1. login to strapi http://localhost:1337/admin
2. click "Content-type biulder"
3. click "Create new collection type" 
4. enter a string in "display name"
5. try to select the whole text in "display name", drag mouse from right end of input to the left end of the screen until the mouse is not hovered over the overlay anymore
6. release the mousebutton (which will emit the 'mouseup' javascirpt event)
7. the overlay will close which is annoying

### Expected behavior

the overlay should not close

### Screenshots

![strapi_gif_bug](https://user-images.githubusercontent.com/16288044/184895463-718c0ef6-44bf-4e78-96e3-e4311cb89c34.gif)

**Comment by derrickmehaffy** [comment]
@jonasfrey while I know this issue is valid and I really don't want to close it. Can you please update the issue and follow our issue template.

I know it's a bit redundant but it is required.

 🙏 Thank you

**Comment by jonasfrey** [comment]
@derrickmehaffy i updated the format of the bug report hopefully it is correct now

**Comment by derrickmehaffy** [comment]
Looks perfect, thank you so much!
