### ISSUE TITLE
File upload Issue

### ISSUE THREAD

**Issue by AvinashUtekar** [strapi/strapi#14126]
## Bug report
Uploaded file is not linking with field in repeatable component

### Required System information

- Node.js version: 14.20.0
- NPM version: 6.14.17
- Strapi version: 4.2.0
- Database: postgres
- Operating system: Windows 10

### Describe the bug
when i upload files for repeatable component file is uploaded but its not attaching to the field for which i upload the file.

please let me correct if i am doing wrong way

i am doing this, as shown in screenshot
![image](https://user-images.githubusercontent.com/87367466/185223990-8c095acc-d263-42e9-974f-a4a5f7ad0102.png)

in the data object i am passing that activity array
`{
        "name":"demoEevent",
        "activity":[
            {
                    "name": "Powering the Aviation of the Future",
            }
        ]
}`

### Steps to reproduce the behavior
1. create one collection name "timeline" with field name as text
2. create one component name "activity" add fields in component name "docs" (type: media, select: multiple media) and "name" (type: text)
3. add activity component in timeline collection and set as repeatable component
4. now hit api as shown in screenshot

so here file will upload but it will not attached in docs field in activity

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/issues/14125

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I don't think it's a duplicate. I saw this comment in the code: <img alt="Capture d’écran 2022-08-22 à 14 30 33" width="529" src="https://user-images.githubusercontent.com/11708220/185921575-e0cdd11b-9b72-4e18-b17d-cd0c553700f1.png">

I'll take your word for it, to me it sounds exactly like the problem in the other issue and that other issue isn't just limited to components.

**Comment by petersg83** [comment]
Yes let's try. I created a fix for the other issue, so we can try to reproduce with the usecase here once the fix is merged

**Comment by derrickmehaffy** [comment]
Just some additional confirmation before the fix is merged:



![Image](https://user-images.githubusercontent.com/8593673/187760423-dd1e714a-baeb-4837-899f-36e2e92f465e.png)


![Image](https://user-images.githubusercontent.com/8593673/187760438-6b453a18-7651-412e-adee-7e8cf1d3535b.png)

**Comment by petersg83** [comment]
@derrickmehaffy do you mean you confirm the bug? What fix do you talk about?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy do you mean you confirm the bug? What fix do you talk about?

I was doing this as a test to show reproduction steps on issues, ignore me @petersg83

**Comment by yamalweb** [comment]
> ## Bug report
> Uploaded file is not linking with field in repeatable component
> 
> ### Required System information
> * Node.js version: 14.20.0
> * NPM version: 6.14.17
> * Strapi version: 4.2.0
> * Database: postgres
> * Operating system: Windows 10
> 
> ### Describe the bug
> when i upload files for repeatable component file is uploaded but its not attaching to the field for which i upload the file.
> 
> please let me correct if i am doing wrong way
> 
> i am doing this, as shown in screenshot ![image](https://user-images.githubusercontent.com/87367466/185223990-8c095acc-d263-42e9-974f-a4a5f7ad0102.png)
> 
> in the data object i am passing that activity array `{ "name":"demoEevent", "activity":[ { "name": "Powering the Aviation of the Future", } ] }`
> 
> ### Steps to reproduce the behavior
> 1. create one collection name "timeline" with field name as text
> 2. create one component name "activity" add fields in component name "docs" (type: media, select: multiple media) and "name" (type: text)
> 3. add activity component in timeline collection and set as repeatable component
> 4. now hit api as shown in screenshot
> 
> so here file will upload but it will not attached in docs field in activity

This way worked for me
https://github.com/strapi/strapi/issues/13828#issuecomment-1198038610

**Comment by petersg83** [comment]
Closing as it should be fixed in #14724
