### ISSUE TITLE
The video, once added, is not editable, not selectable, not removable. – @strapi/provider-upload-aws-s3

### ISSUE THREAD

**Issue by kalwas123** [strapi/strapi#14121]
- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.3.4
- Database: sqlite
- Operating system: macos

The video, once added, is not editable, not selectable, not removable. You can't see how long is the video. If you add a movie while completing a field, the movie is added to that field, but to another field it can no longer be added. Images work properly. It seems to me that it does not work after the latest strapi update.

### Steps to reproduce the behavior

Init Strapi -> install "@strapi/provider-upload-aws-s3": "^4.3.4",

### Expected behavior

Wants to add video to media library and then be able to use it

### Screenshots

<img width="369" alt="Zrzut ekranu 2022-08-17 o 17 21 00" src="https://user-images.githubusercontent.com/20096223/185178266-0f431d0f-f466-44d2-a6d5-5e7e12678c72.png">

**Comment by kalwas123** [comment]
I had to add  Cross-origin resource sharing (CORS)

**Comment by JulianGoh5** [comment]
@kalwas123 would you be able to share the source code of what edits you made to fix? Facing the same issue
