### ISSUE TITLE
Upload Plugin does not update the refId

### ISSUE THREAD

**Issue by am2222** [strapi/strapi#14125]
### Required System information

 

- Node.js version: 16
- NPM version: 6.14
- Strapi version: v4.3.2
- Database:PG
- Operating system: Linux/Win

### Describe the bug

When Updating a file using `{{ _.baseURL }}api/upload` to an entity of type `plugin::users-permissions.user` The image gets uploaded and corresponding row in `files_related_morphs` table will be added. However it adds a new row instead of updating the existing row which cause strapi to return the first uploaded file
<img width="761" alt="image" src="https://user-images.githubusercontent.com/4707503/185219972-1cbc1524-8938-403b-b330-6bad5b8d051a.png">

### Steps to reproduce the behavior
1. Add a user object as following setting ```"image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },```
2. upload a file using upload api
3. upload another using the same upload api
4. The user image is not updated with the second image

### Expected behavior

I think we need to update refId row in `files_related_morphs` table instead on creating, or check if it exists update it.
### Additional context
[
I guess this line should change?
](@strapi/plugin-upload/server/services/upload.js#L337-L338

```javascript
    const res = await strapi.query(FILE_MODEL_UID).create({ data: fileValues });

```)

**Comment by derrickmehaffy** [comment]
I have been able to reproduce this but it seems there is something weird with the create and upload linking too. There was a chat in discord about this earlier today.

**Comment by RajatChoudhary999** [comment]
Hey, I'm new to open source can someone help to get Started? Thanks in advance!
