### ISSUE TITLE
HELP ME PLEASE => Pure sql : update SQL don't work

### ISSUE THREAD

**Issue by titoff002** [strapi/strapi#14123]
Hello,

I'm trying create a update SQL : 

```
const data = await strapi.db.connection.context.raw(
        `update up_users set username = ?, email = ?
        where id = ?;` ,  [body.email, body.nom, id]
      );
```
But don't work !

`body.email, body.nom, id `= are ok

For update,  `await strapi.db.connection.context.raw` can be used ?

how to execute an "update" sql query with strapi ?

Thanks to you.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
