### ISSUE TITLE
WYSIWYG : table tag converting to div

### ISSUE THREAD

**Issue by AnkitAneja** [strapi/strapi#1413]
I am facing issue in WYSIWYG , when I add table tag in the WYSIWYG, table tag converting to div. Can anyone please help me out from this issue

**Comment by lauriejim** [comment]
Hello @AnkitAneja , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
