### ISSUE TITLE
Dark mode dropdown has white text on a white background

### ISSUE THREAD

**Issue by chrift** [strapi/strapi#14156]
### Required System information

- Node.js version: 16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.3
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

When in dark mode, the dropdowns are white, and so is the text. 

### Steps to reproduce the behavior

Have a relation on a type

### Expected behavior

Dropdowns are not white

### Screenshots

![image](https://user-images.githubusercontent.com/2837753/185932499-19f7bd7d-3012-41ee-9de1-47c8a41e8856.png)

**Comment by gu-stav** [comment]
@chrift on which version exactly are you on? This should be fixed in the latest release.

**Comment by chrift** [comment]
4.3.0
Ill update to 4.3.4 and update!

**Comment by gu-stav** [comment]
Thank you. I'll close this one in the meantime. Ping me, if you still experience it please :)
