### ISSUE TITLE
z-index of true/false selector is higher than that of a select dropdown 

### ISSUE THREAD

**Issue by chrift** [strapi/strapi#14155]
### Required System information

- Node.js version: 16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.3
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug
I have a dynamic zone. One component has a relation in, exhibited via a dropdown. Another component has a boolean, exhibited with a true/false selector. The z-index of the true/false selector is higher than the dropdown, so it shows in front of the dropdown. 

### Expected behavior
The true/false selector is behind the dropdown

### Screenshots

![image](https://user-images.githubusercontent.com/2837753/185931254-28fa394d-1142-4d58-a05f-bc8a0dec75a7.png)

**Comment by jaysoni-ash42** [comment]
@gu-stav  can i work on this issue?

**Comment by gu-stav** [comment]
@jaysoni-ash42 Sure, I'd be happy if you would like to do it. Let me know if you need help of any kind (I'm available on discord too).

**Comment by jaysoni-ash42** [comment]
@gu-stav  @chrift  i am not facing the same issue on my end you can look at this demo images  running the same strapi version.
<img width="702" alt="Screen Shot 2022-08-23 at 12 21 07" src="https://user-images.githubusercontent.com/68722497/186087852-334d08c9-edeb-48e4-935b-4327285107e6.png">
<img width="702" alt="Screen Shot 2022-08-23 at 12 21 07" src="https://user-images.githubusercontent.com/68722497/186087858-57f61556-79e9-45ef-925c-09789bf05e54.png">

**Comment by jaysoni-ash42** [comment]
@chrift  which browser are you using because i. am using chrome and was not able to recreate the bug.
<img width="702" alt="Screen Shot 2022-08-23 at 12 21 07" src="https://user-images.githubusercontent.com/68722497/186094484-49f72540-c0f1-4a09-adcf-115d996ce974.png">

**Comment by chrift** [comment]
We updated to 4.3.4 from 4.3 in order to fix the issue mentioned [here](https://github.com/strapi/strapi/issues/14156) and it looks like it has also fixed this issue 👍

**Comment by gu-stav** [comment]
@jaysoni-ash42 Thank you for your support 🌻
