### ISSUE TITLE
GraphQL schema does not put ! non-nullable for required Repeatable Component

### ISSUE THREAD

**Issue by jonathan-baernthaler** [strapi/strapi#14152]
### Required System information

- Node.js version: 16.8.0
- NPM version: 7.21.0
- Strapi version: 4.3.3
- Database: sqlite3
- Operating system: MacOS

### Describe the bug

similar to issue https://github.com/strapi/strapi/issues/5538 the graphql schema does not put ! non-nullable for repeatable components. This produces a lot of overhead for typescript projects that rely on a type generator. 

### Steps to reproduce the behavior

**with the following model:**

```
{
  "collectionName": "components_sections_clients",
  "info": {
    "displayName": "Clients",
    "icon": "handshake",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": false
    },
    "clients": {
      "type": "component",
      "repeatable": true,
      "component": "elements.client",
      "required": true
    },
    "identifier": {
      "type": "string"
    }
  }
}
```

**and the following component:**

```
{
  "collectionName": "components_elements_clients",
  "info": {
    "displayName": "Client",
    "icon": "user",
    "description": ""
  },
  "options": {},
  "attributes": {
    "logo": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ]
    },
    "newTab": {
      "type": "boolean",
      "default": true
    },
    "url": {
      "type": "string"
    },
    "displayname": {
      "type": "string"
    }
  }
}
```

**the graphql schema produces** 

`
type ComponentSectionsClients {
...
clients: [ComponentElementsClient]!
...
}
`

**Expected Behavior** 

That the schema Component inside the Array would be non-nullable. This affects graphql-codegen and makes the types be either ComponentElementsClient or Null in Typescript later.

`
type ComponentSectionsClients {
...
clients: [ComponentElementsClient!]!
...
}
`

For a moment I thought that this might be due to the option of filtering repeatable components but [Component!]! allows returning an empty array if no matches are found. So I think this would be a great fix for everyone relying on typescript code generation

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/10030
