### ISSUE TITLE
Typescript lifecycle `Event` type missing `result` property for 11 Action types: eg: `afterCreate`, `afterCreateMany `, etc...

### ISSUE THREAD

**Issue by haysclark** [strapi/strapi#14167]
### Required System information

- Strapi version: 4.3.4

### Describe the bug

The lifecycle `Event` types for the following `Actions` are missing the `result` property in their [Typescript type](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/lifecycles/index.d.ts#L37-L41).

- [afterFindOne](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L120)
- [afterFindMany](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L131)
- [afterCount](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L147)
- [afterUpdate](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L248)
- [afterUpdateMany](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L273)
- [afterCreate](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L178)
- [afterCreateMany](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L206)
- [afterUpdate](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L248)
- [afterUpdateMany](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L273)
- [afterDelete](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L304)
- [afterDeleteMany](https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/database/lib/entity-manager.js#L319)

### Expected behavior

`Event` object types for `afterFindOne`, `afterFindMany`, `afterCount`, `afterUpdate`, `afterUpdateMany`, `afterCreate`, `afterCreateMany`, `afterUpdate`, `afterUpdateMany`, `afterDelete`, `afterDeleteMany`

**Comment by kasonde** [comment]
Just a note, I've noticed the other TS issues you opened. Thanks for the reports. I've tagged those as help-wanted while I wait for input from members of our Eng team.

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
