### ISSUE TITLE
Typescript `Subscriber` typing doesn't allow `models` property.

### ISSUE THREAD

**Issue by haysclark** [strapi/strapi#14165]
### Required System information

- Strapi version: 4.7.4

### Describe the bug

Typescript service typing doesn't allow addition of custom services, when adding a new service such as follows:

```typescript
// src/index.ts
import type { Strapi } from "@strapi/strapi";
import type { Subscriber } from "@strapi/database/lib/lifecycles/subscribers";

const userSubscriber: Subscriber = {
  models: ["plugin::users-permissions.user"],
  async afterCreate(event) {
    console.log(`event ${JSON.stringify(event, undefined, 2)}`);
  }
};

export default {
  bootstrap({ strapi }: { strapi: Strapi }) {
    strapi.db.lifecycles.subscribe(userSubscriber);
  }
};
```

[CodeSandbox example](https://codesandbox.io/s/strapi-typescript-4-3-4-typecheck-error-models-does-not-exist-in-type-subscriber-kock3w?file=/src/index.ts:0-845)

It throws a typing error as follows:
```bash
 error TS2322: Type '{ models: string[]; afterCreate(event: Event): Promise<void>; }' is not assignable to type 'Subscriber'.
 Object literal may only specify known properties, and 'models' does not exist in type 'Subscriber'.
  
13   models: ["plugin::users-permissions.user"],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   Found 1 error in src/index.ts:13
```

### Expected behavior

Should allow `models` property with `string` Array type. e.g.: `models: string[]`

**Comment by MathieuRegis** [comment]
Same issue here (v4.5.0) :
`Argument type {models: string[], beforeCreate({params}: {params: any}): Promise<void>, afterCreate({result, params}: {result: any, params: any}): Promise<void>} is not assignable to parameter type Subscriber`

in `node_modules/@strapi/database/lib/lifecycles/subscribers`, `Subscriber` doesn't have any `models` attributes

**Comment by derrickmehaffy** [comment]
Closing as merging this into the tracking issue #15225
