### ISSUE TITLE
Images that are less than and equal to 150x150 can't get formats url from strapi

### ISSUE THREAD

**Issue by ToeWaiPhyo10** [strapi/strapi#14171]
Required System information

- Node.js version:14.7.3
- NPM version:7.24.0
- Strapi version:4.1.12
- Database:postgres
- Operating system:Window 10

Describe the bug

I uploaded an image from frontend to strapi and that image size is 150x150. When in the strapi CMS i can see the image but can't retrieve the url because i got the formats as null.

Steps to reproduce the behavior

1.upload the 150x150 image.
2.go to the CMS and can see the image
3.setup and get url from frontend
4.can't get any format for that photo

 Expected behavior

1.upload the 150x150 image.
2.go to the CMS and can see the image
3.setup and get url from frontend
4.can get  formats for that photo

This is sample issues photo 
![WhatsApp Image 2022-08-23 at 3 29 45 PM](https://user-images.githubusercontent.com/98570075/186117957-24a440a4-e812-47bd-82c1-eefa5d9a6b6f.jpeg)

The image that i uploaded to strapi
![WhatsApp Image 2022-08-23 at 12 01 30 PM](https://user-images.githubusercontent.com/98570075/186118163-430b9583-1598-46dd-8313-446f71b0d8ef.jpeg)

**Comment by bolg55** [comment]
Can you please fill out the bug report form, including explicit steps to reproduce? I understand what you are describing, but for clarity to future viewers, it is helpful and will help us troubleshoot more effectively. Thanks

**Comment by gracebir** [comment]
> Can you please fill out the bug report form, including explicit steps to reproduce? I understand what you are describing, but for clarity to future viewers, it is helpful and will help us troubleshoot more effectively. Thanks

@ToeWaiPhyo10 please add the steps to reproduce

**Comment by gracebir** [comment]
@bolg55 , what value could we set as minimun size image and minimun width image?

**Comment by WalkingPizza** [comment]
I believe this is intended!

The smallest default breakpoint is `small` with a value of `500px`, but since the image is 150x150, the smallest breakpoint is bigger than the actual image and thus it is not generated.

In this case, you can grab the default URL in the image's attributes rather than grabbing it from the `formats` object.

https://github.com/strapi/strapi/blob/78af3ebe621aec3658fc5a4141038418e7aef67d/packages/core/upload/server/services/image-manipulation.js#L122-L149

**Comment by gracebir** [comment]
@WalkingPizza, I don't think we also to make a look image validation where the max size has been setting

**Comment by kasonde** [comment]
Hi @ToeWaiPhyo10 I remember we had an issue about this and I had a chat with one of our PMs about this. It's intended behavior. I can't explain it better than @WalkingPizza already has.
