### ISSUE TITLE
TypeError: strapi.hook.mongoose.manageRelations is not a function

### ISSUE THREAD

**Issue by johntom** [strapi/strapi#1417]
**Informations**
- **Node.js version**:9.5.0
- **npm version**:4.1.2
- **Strapi version**:3.0.0-alpha.12.4
- **Database**:Mongo v2.4.10
- **Operating system**:win10

**What is the current behavior?**
Posting to articles from a custom form raises
```
services article data Article { _id: 5b283e9553ad82716c4a17ea,
  title: 'GTZ TEST ',
  content: 'This is a test for adding article thru custom form',
  createdAt: 2018-06-18T23:21:57.028Z,
  updatedAt: 2018-06-18T23:21:57.028Z,
  __v: 0,
  contentImage: null,
  id: '5b283e9553ad82716c4a17ea' }
TypeError: strapi.hook.mongoose.manageRelations is not a function
    at Object.add (D:\Frameworks\Strapi-Gatsby\api\api\article\services\Article.js:54:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
[2018-06-18T23:21:57.036Z] debug POST /article (23 ms)
```
**Steps to reproduce the problem**
add a custom form in public folder also added socket.io
article.html 
```

<section>
    <h1>Add new article !</h1>

    <label for="title">
        <span>Title :</span>
        <!-- name of the bakery entity -->
        <input type="text" name="title" id="title" />
    </label>
    <label for="content">
        <span>Content :</span>
        <!-- name of the bakery entity -->
        <input type="text" name="content" id="content" />
    </label>


    <button id="add">Add</button>
    <div id="article"></div>
</section>
<script src="/socket.io/socket.io.js"></script>
<script>
    const socket = io();

    // to get the value name to create an entity
    const name = document.getElementById('title');
    // to get the value rating to create an entity
    const content = document.getElementById('content');
    // to listen to click event and send our request
    const add = document.getElementById('add');
    const article = document.getElementById('article');
    socket.on('article_ready', res => article.innerHTML += `<div>- ${res.title} is ${res.content}/ is a good post</div>`);

    add.addEventListener('click', () => { // listen to click event
        // send a post request with our input value
        fetch('/article', {
            method: 'post',
            headers: { "Content-type": "application/x-www-form-urlencoded; charset=UTF-8" },
            body: `title=${title.value}&content=${content.value}`
        })
            .then((res) => {
                if (res.status !== 200) return;
                res.json().then((data) => console.log(data));
            }
            )
            .catch((err) => console.log('Fetch Error :-S', err));
    });
</script>
```
without socketio using json payload
```
<section>
    <h1>Add new article !</h1>

    <label for="title">
        <span>Title :</span>
        <!-- name of the bakery entity -->
        <input type="text" name="title" id="title" />
    </label>
    <label for="content">
        <span>Content :</span>
        <!-- name of the bakery entity -->
        <input type="text" name="content" id="content" />
    </label>


    <button id="add">Add</button>
    <div id="article"></div>
</section>
<!-- <script src="/socket.io/socket.io.js"></script> -->
<script>
        const add = document.getElementById('add');
        const article = document.getElementById('article');
        add.addEventListener('click', () => { // listen to click event
         
    let product = {};
    product.title = `${title.value}`;
    product.content =  `${content.value}`;
    // send a post request with our input value
    fetch('/article', {
        method: 'post',
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        },
       
        body: JSON.stringify(product)
    })
        .then((res) => {
            if (res.status !== 200) return;
            res.json().then((data) => console.log(data));
        }
        )
        .catch((err) => console.log('Fetch Error :-S', err));



});

</script>
```

**What is the expected behavior?**
posting an artilcle though dashboard succeeds

**Suggested solutions**
commenting out line await and post passes. Just not sure of any potential issues.
  add: async (values) => {
    const data = await Article.create(_.omit(values, _.keys(_.groupBy(strapi.models.article.associations, 'alias'))));
    console.log('services bakery data Article',data)
   
  //  await strapi.hook.mongoose.manageRelations('article', _.merge(_.clone(data), { values }));
    return data;
  },

i found Relations not being saved with POST API request, only with PUT #919...

**Comment by lauriejim** [comment]
Hello @johntom did you check this [Repo](https://github.com/wonknu/strapi_socket) for you socket.io usage ?

**Comment by daru23** [comment]
Did you recently migrate your project? 

I am facing the same problem and I notice that the new models generate different code. I am assuming this is cause of a migration process.

**Comment by derrickmehaffy** [comment]
I've seen something similar to this myself, if you generate a new project, create all your models with just a `test` string field then copy over your `/api/-modelname-/models/-modelname-.settings.json` and of course your `/config/environment` you should be able to migrate up version pretty easily. In your case, copying over your `/public` folder as well.

The strapi team did state they are working on a tool to help make updating easier:

![image](https://user-images.githubusercontent.com/8593673/41596365-f6dc3e94-737e-11e8-8036-3334cc3d03ce.png)

Might be a little while, but some of the updates do modify the .js files in the config/controller/models/services

**Comment by johntom** [comment]
Thanks for all the suggestions, socket.io is not the issue as I have 2 custom forms with and without the causes issue. I will test later and get back.

**Comment by daru23** [comment]
@derrickmehaffy Thanks a lot. Work smoothly for me.

**Comment by lauriejim** [comment]
@johntom What happen if you are trying with a fresh new app ? Your issue still happen ?

**Comment by johntom** [comment]
@lauriejim I will test when I arrive home tonight, at client all day.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.

**Comment by daru23** [comment]
For me, this issue stop when I made npm install inside all the plugins folders.
Maybe that can help you.

**Comment by johntom** [comment]
sorry, went to mongo-world and schedule became crazed. At any rate the problem no longer exists with 3.0.0-apha.,12.6
