### ISSUE TITLE
Admin Content Type Builder should not remove unknown attribute options

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#14183]
### Required System information
- Node.js version: v14.20.0
- NPM version:
- Strapi version: 4.3.4
- Database: Postgres12
- Operating system: MacOS 12.4

### Describe the bug

I normally put custom options in attributes and schema.json files to be used by custom logic in the api, which the actual core code doesn't mind. However, the Admin content-type-builder seems to clear all these up and re-arrange attributes in another order, whenever it is used. As long as it doesn't know it, it removes it whenever I edit anything.

eg:

```json
"attributes": {
    "profile": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::profile.profile",
      "cascade": true
    }
},
"cube": {
   "measures": {
       "name": "profiles_count"
    }
}
```

The above code has logic that is used when I do any cascade operations with the model, and the other is used to generate cubejs schema based on the model schema. To avoid rewriting things and make it more coupled, I put these in schema files (it's easier to understand what cascade is doing when being read from the schema.json file rather than a separate file)

As a result, I avoid using the content-type-builder whenever there is custom code in the schema files.

### Steps to reproduce the behavior

Create a content type and edit the schema file with the example code above and save. Then go to the Admin panel and add another field using the content type builder and save. Now open the schema file again, the custom code will be gone.

### Expected behavior

It should ignore any fields that it doesn't know and leave them as they are, as long as they are valid json. It should not rearrange attributes order, the order has meaning to the developer if they used an editor.

### Code snippets

as above

**Comment by alexandrebodin** [comment]
I can't retrace the history but this is fixed the the lastest versions of Strapi :)
