### ISSUE TITLE
Return null when trying to get current uploaded file

### ISSUE THREAD

**Issue by henrych4** [strapi/strapi#1418]
**Informations**
- **Node.js version**: 9.0.0
- **npm version**: 5.5.1
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MongoDB
- **Operating system**: macOS High Sierra Version 10.13.1

**What is the current behavior?**
I have created a content type with field 'media'. And when I upload a excel file to strapi and get relevant information using the following code:
```
Dailydata.findOne({_id: result.id}).populate('dailydata').then(function(o) {
    console.log('done: ', o);
  }).catch(function(e) {
    console.log('e: ', e);
});
```
The console printed "dailydata: null".

However, when I replace 'result.id' with an id corresponding to an existing record, the code works and prints information about the file.

**Steps to reproduce the problem**
Create a content type called 'Dailydata' with field called 'dailydata'
Add the following code to model/Dailydata.js
```
afterSave: async(model, result) => {
  Dailydata.findOne({_id: result.id}).populate('dailydata').then(function(o) {
    console.log('done: ', o);
  }).catch(function(e) {
    console.log('e: ', e);
  });
},
```

**What is the expected behavior?**
Return information about files successfully.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @henrych4 !
I don't understand what you want to do with the `afterSave` function. 
Are you using the content manager to create your `Dailydata` ?

**Comment by henrych4** [comment]
Thanks for the prompt reply. Yes, I use content manager to create `Dailydata`. 
And I am trying to fill in other content based on `Dailydata` and therefore I add some code in `afterSave` event.

**Comment by lauriejim** [comment]
Actually the upload feature not allow to create your entry and upload in the same time ([issue here](https://github.com/strapi/strapi/issues/1316))
So first we create the entry (without media file) and then we upload your files by joining ([Upload documentation](https://strapi.io/documentation/guides/upload.html)) them to the entry previously created.

It's why you have `null` to your media key. Files are not upload at this point.

I close this issue cause you need is related to the issue I linked previously.

**Comment by henrych4** [comment]
So at which point I can retrieve the file?
