### ISSUE TITLE
Can not start strapi on version 4.3.5

### ISSUE THREAD

**Issue by tailm0796** [strapi/strapi#14197]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.5
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

I can not start strapi after excute:
```
 yarn create strapi-app my-project --quickstart
```

### Steps to reproduce the behavior

1. Run  
```
 yarn create strapi-app my-project --quickstart
```

### Screenshots

![image](https://user-images.githubusercontent.com/45816446/186428812-0c2bdfc9-a587-44f1-9908-62d2342d4121.png)

**Comment by gu-stav** [comment]
`4.3.5` introduced a bug when the GraphQL plugin was not installed, which should be fixed by [`4.3.6`](https://github.com/strapi/strapi/releases/tag/v4.3.6). Please upgrade to this version.
