### ISSUE TITLE
Can't access auth/local in production

### ISSUE THREAD

**Issue by kwzm** [strapi/strapi#1420]
**Informations**
- **Node.js version**: v10.1.0
- **npm version**: v5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb
- **Operating system**: win7 x64

**What is the current behavior?**

I can't access auth/local in production server. I use postman to send the request, url is `http://myIp:1337/api/auth/local`(I use prefix /api), but it return 404

**Steps to reproduce the problem**

Run strapi in production server, and then use postman to send login api.

**What is the expected behavior?**

I can access login api.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@kwzm can you provide the file where you changed the prefix. 

The prefix needs to be `/api` not `api`

Also there are known issues with the prefix and losing access to both the adminUI and the public folder just as an FYI.

**Comment by kwzm** [comment]
@derrickmehaffy  Sorry, it's my fault.

**Comment by anselmobattisti** [comment]
> @derrickmehaffy Sorry, it's my fault.

Here i was trying to access it via GET instead of POST!

**Comment by kevinkowa** [comment]
I'm running strapi on heroku and when I call /auth/local with a post it gives me a 404. 

https://{project_name}.herokuapp.com/auth/local

on dev this works, but on prod it gives me a 404
