### ISSUE TITLE
When using the create service, the result does not return the author property, for example: createdBy

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [strapi/strapi#14204]
## Bug report

- Node.js version: v14
- Strapi version: 4.3.6
- Database: postgres
- Operating system: MAC

When creating a record from the client (with nextjs) the data is inserted in the collection-type but it does not show information about the author, as you will see in the image:

<img width="206" alt="Untitled 2" src="https://user-images.githubusercontent.com/21962584/186493097-c386453a-efd8-4549-aa2c-253f5831f50f.png">

but if I generate the record directly from the strapi UI it works.

My intention is that it shows the *createdBy* information when the insert is done from the client (nextjs).

In fact, I did a test inserting data with postman:

```json
{
"id": 202,
     "identifier": "9821ddd4-81da-490c-a205-7163998f9ddd",
     "createdAt": "2022-08-24T18:08:51.732Z",
     "updatedAt": "2022-08-24T18:08:51.732Z",
     "publishedAt": null,
     "userID": "82",
     "name": null
}
```
And it doesn't show me the *createdBy* field

I appreciate your help!

**Comment by smoothdvd** [comment]
@ChrisMichaelPerezSantiago what post body when you inserted in Postman?

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @smoothdvd ,

It is an authenticated service, I am passing the payload as data and the token.

```ts
  /**
   *
   * @return {Http} POST /create
   **/
  create({ data, token }: { data: object; token: string }) {
    return Http.post(
      `${endpoint}`,
      { data: data },
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );
  },
```

**Comment by ChrisMichaelPerezSantiago** [comment]
@smoothdvd ,


According to the documentation: https://docs.strapi.io/developer-docs/latest/guides/is-owner.html

There is an example where it is indicated that it must be passed (author property):
```ts
ctx.request.body.author = ctx.state.user.id;
```

```ts
"use strict";

const { sanitize } = require("@strapi/utils");

/**
 * user-check-in controller
 */

const { createCoreController } = require("@strapi/strapi").factories;

const sanitizeOutput = (data, ctx) => {
  const schema = strapi.getModel("api::user-check-in.user-check-in");
  const { auth } = ctx.state;
  return sanitize.contentAPI.output(data, schema, { auth });
};

module.exports = createCoreController(
  "api::user-check-in.user-check-in",
  ({ strapi }) => ({
    async create(ctx) {
      ctx.request.body.data.user = ctx.state.user.id;
      ctx.request.body.author = ctx.state.user.id; // HERE: AUTHOR

      const query = strapi.db.query("api::user-check-in.user-check-in");
      const entity = await query.create(ctx.request.body);
      const sanitizedEntity = await sanitizeOutput(entity, ctx);

      return sanitizedEntity;
    },
  })
);
```

**Result**:

It does not return the author information (createdBy)
```json
{
    "id": 324,
    "identifier": "9821ddd4-81da-490c-a205-7163998f9223",
    "createdAt": "2022-08-25T08:39:24.226Z",
    "updatedAt": "2022-08-25T08:39:24.226Z",
    "publishedAt": null,
    "userID": "82",
    "name": null
}
```

**Comment by smoothdvd** [comment]
In restful-api, you can send
```
{
  "data": {
    "created_by_id": 1,
    "updated_by_id": 1
  }
}
```
to add author.

**Comment by ChrisMichaelPerezSantiago** [comment]
@smoothdvd, Could you provide an example (using strapi version 4) of what it would look like?

**Comment by smoothdvd** [comment]
```
ctx.request.body.data.created_by_id = ctx.state.user.id;
ctx.request.body.data. updated_by_id = ctx.state.user.id;
```

**Comment by ChrisMichaelPerezSantiago** [comment]
@smoothdvd,

There is no way to assign the author of the publication to a user created from the content-type User?
<img width="887" alt="Untitled" src="https://user-images.githubusercontent.com/21962584/187018075-05517f07-e1d0-4cb3-9760-e7f470430785.png">



It shows me an error in the relations of the db in assigning the ID to the user, since it only works with `id = 1`, which in theory is me.

**Comment by smoothdvd** [comment]
@ChrisMichaelPerezSantiago because of created_by_id / updated_by_id is associated with admin_users's id.

**Comment by kasonde** [comment]
Hi @ChrisMichaelPerezSantiago that created_by field is associated to Admin Users and not UsersPermissions users. I would go with @smoothdvd's recommendation for having that information related to the U&P plugin stored.
