### ISSUE TITLE
Relation dropdown search is case sensitive but only for items after first 20

### ISSUE THREAD

**Issue by chrift** [strapi/strapi#14202]
### Required System information

- Node.js version: 16.14.2
- Yarn version: 1.22.18
- Strapi version: 4.3.4
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

When selecting a relation via the dropdown, the search is case sensitive **only for items that are not in the first list of 20 that are loaded when the dropdown is opened** leading to misleading results being shown. 

### Steps to reproduce the behavior
1. Have type1 with a relation to type2
2. type2 should have a text field "name"
3. Create 20 records in type2 with name of "Test"
4. Create a 21st record in type with name of "Find Me"
5. On type1 record creation page, in the relation dropdown, search for "find"

### Expected behavior
The "Find Me" record is found

### Screenshots

![image](https://user-images.githubusercontent.com/2837753/186473661-edf5f27a-62d5-480a-b614-0cf2c6be3868.png)
![image](https://user-images.githubusercontent.com/2837753/186473704-39798974-bff9-4c9f-841c-c57952687e3c.png)
![image](https://user-images.githubusercontent.com/2837753/186473748-24f3655b-f939-4882-b1e3-088fff1d2ef6.png)
![image](https://user-images.githubusercontent.com/2837753/186473782-fd5e1fb1-97af-4ce6-a320-c1ffabf1875e.png)

### Additional context

Once the relation has been loaded after the dropdown has been opened, it will show in a case insensitive search.
I.e:
1. Open dropdown
2. Search for "Find" - record will appear
3. Search for "find" - record will appear because was loaded in step 2

![image](https://user-images.githubusercontent.com/2837753/186474664-e6ff2114-bed7-4bb4-8fa3-4ae07893ad0d.png)

**Comment by WalkingPizza** [comment]
I believe it's a duplicate of #13888.
You can find a PR that aims at solving this in that issue.

**Comment by chrift** [comment]
Yes, I would agree it is a duplicate. Marking this as closed.
