### ISSUE TITLE
Components injected into Content Manager Edit View do not render after filling in fields from another locale

### ISSUE THREAD

**Issue by Esipode** [strapi/strapi#14224]
### Required System information

- Node.js version: 14.20
- NPM version: 6.14.17
- Strapi version: 4.1.8
- Database: Postgres
- Operating system: MacOS

### Describe the bug

When creating or editing a collection type, if you have a component injected into the edit view of the content manager and select the 'Fill in from another locale' button, the page will stop rendering the injected component.

### Steps to reproduce the behavior

1) Create a plugin with a component to inject into the content manager's edit view
2) Go to 'Content Manager'
3) Select a collection type with localization enabled
4) Select an entry to edit its fields
5) In the right sidebar, select 'Fill in from another locale' 
6) Select a locale and click 'Yes, fill in'
6) See that the component you created earlier has stopped rendering

### Expected behavior

The injected component should continue to render after filling in the fields from another locale.

### Screenshots

https://user-images.githubusercontent.com/56048122/186761747-ae3697c9-666c-462b-b61c-8c260c2467b7.mov

### Code snippets

Here is the component being injected:

```
import Translate from './components/translate';

const name = pluginPkg.strapi.name;

export default {
  register(app) {
    app.registerPlugin({
      id: pluginId,
      initializer: Initializer,
      isReady: true,
      name,
    })
  },
  
  bootstrap(app) {
    app.injectContentManagerComponent('editView', 'informations', {
      name: 'translate',
      Component: Translate
    })
  }
}
```

And the component itself:

```
import React from 'react';
import { Button } from '@strapi/design-system/Button';

const Translate = () => {
  const data = useCMEditViewDataManager();
  
  return (
    <Button
      size='S'
      fullWidth
      variant='secondary'
      onClick={async (e) => {
        e.preventDefault();
        console.log('test');
      }}
    >
      Translate from English
    </Button>
  )
}

export default Translate;
```

**Comment by derrickmehaffy** [comment]
Can you please test this on the latest version, yours is quite old: `Strapi version: 4.1.8`

Marking as closed for now until the user confirms the issue on at least 4.3.x

**Comment by Esipode** [comment]
Retested on 4.3.6, issue is still present.

**Comment by kasonde** [comment]
We currently have a few issues about "Fill in from another locale" that our product team is aware of. I'll close this as it's related to #14313 just so we can reduce the amount of threads for related issues. Thank you!
