### ISSUE TITLE
Unable to install Strapi 

### ISSUE THREAD

**Issue by VinylVault** [strapi/strapi#14236]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.18.0
- Strapi version: latest v4 (as far as i know)
- Database: PG
- Operating system: win 10

### Describe the bug

unable to complete install either via `npx create-strapi-app@latest my-project` or running a starter as per docs

as detailed below, this appears to be an issue when trying to access the FontAwesome private npm repo.

Access to this repo (even for the free libraries) requires a login, which requires payment to the best of my knowledge.

### Steps to reproduce the behavior

1. Go to 'Terminal in IDE'
2. Navigate to drive / folder where you want to create the Strapi installation
3. Run `npx create-strapi-app@latest [project-name]`
4. See error in additional content

### Expected behavior

a completed installation routine

### Additional context

`npm i --verbose` output

```
npm verb stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/",service="npm.fontawesome.com"
npm verb statusCode 401
npm verb pkgid @fortawesome/fontawesome-free@^5.15.2
... 
npm verb Windows_NT 10.0.19044
npm verb node v16.13.1
npm verb npm  v8.18.0
npm ERR! code E401
npm ERR! Incorrect or missing password.
```

**Comment by derrickmehaffy** [comment]
You have setup the paid font awesome globally on your machine. Double check your npm config: https://fontawesome.com/docs/web/setup/packages

This isn't a bug with Strapi but the users environment, going to set as closed.

**Comment by VinylVault** [comment]
@derrickmehaffy No, I havn't set them up.
