### ISSUE TITLE
Admin settings roles page does not work anymore and throws an error with every safe

### ISSUE THREAD

**Issue by tilman** [strapi/strapi#14249]
### Required System information

- Node.js version: v14.19.3
- NPM version: pnpm 7.9.4
- Strapi version: 4.2.2
- Database: postgres
- Operating system: macOS

### Describe the bug / Steps to reproduce the behavior

I have created a new single type which I want to add to one of my configured roles under`/admin/settings/roles`.
Therefore I aktivated the tick in the top level view left to the single type name. After hitting save an error notifaction shows up with `Warning: An error occured` (not very helpful to be honest). If I check the network manager I can see the following error message from the permissions PUT request:
```json
{"data":null,"error":{"status":400,"name":"ValidationError","message":"Permissions have to be defined all together for a subject field or not at all","details":{"errors":[{"path":["permissions"],"message":"Permissions have to be defined all together for a subject field or not at all","name":"ValidationError"}]}}}
```
But still, I don't really know what to do different. 

### Expected behavior

A working role settings page or a more helpful error message.

### Additional context

This affects our production system and my only workaround is to give my content editor super admin rights to solve this, which is really not appreciated. Would be great If you can help me with another workaround (like changing the DB directly) if this error is not possible to fix.

**Comment by bolg55** [comment]
I just want to clarify that I am taking the steps you've outlined. If so, I wasn't able to reproduce on the latest Strapi v4.3.6, but will roll back and attempt on 4.2.2 if you can verify that these are the correct reproduction steps.

https://user-images.githubusercontent.com/43022248/187695883-21705832-b27e-4877-969e-f1364adf44a6.mov

**Comment by bolg55** [comment]
Ok, that's helpful -> I misread and thought you were using a custom role which is why I used an Ent version. I will try w/ the community edition. Thanks for the clarification

**Comment by bolg55** [comment]
I am unable to reproduce on v4.2.2 community edition. Creating a single type and enabling on both editor/author roles do not produce an error for me.

**Comment by derrickmehaffy** [comment]
Also cannot reproduce. Going to mark this as closed for now until we can get clean reproduction steps.

**Comment by kahrpatrick** [comment]
I have encountered the same issue. This post solved it for me: https://github.com/strapi/strapi/issues/12842#issuecomment-1073462936
