### ISSUE TITLE
__component key those not appear on nested component

### ISSUE THREAD

**Issue by WebMamba** [strapi/strapi#14243]
### Required System information

- Node.js version: v16.17.0
- Yarn version: 1.22.19
- Strapi version: 4.3.6
- Database: mysql
- Operating system: OSX

### Describe the bug

If you request a Single-Type or a Collection-Type containing a component, and this component contains himself a component. With the api you can request to populate and get also this nested component. The parent component contains the __component key. This component can be really useful when doing content generation. But these those not appear when on the child component.

### Steps to reproduce the behavior

1. Create a single type
2. Create the first component
3. Create a first component with a component property using the first component
4. Fill your single type
5. Request your content-type with a 2 level population

### Expected behavior

The key __component should appear for the first level component and the second level component

### Screenshots

<img width="439" alt="Capture d’écran 2022-08-29 à 12 41 39" src="https://user-images.githubusercontent.com/32077734/187183878-3cba025a-b515-48b4-8101-e6be553ba12e.png">

### Additional context

If needed I can help with a PR but I wasn't sure if it's a bug or a feature 😄. So be free to discuss it!
Cheers.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/8453
