### ISSUE TITLE
Error message is not detailed enough when I create a content type

### ISSUE THREAD

**Issue by phollaki** [strapi/strapi#14242]
### Required System information

- Node.js version: v14
- NPM version: 6.14.17
- Strapi version: 4.3.6
- Database: postgres
- Operating system: MAC (M1)

### Describe the bug

When I wanted to create an article content type with Title, Content, Thumbnail and Slug attributes I got a simple general error message. It took me 20-30 minutes to figure out where the error was coming from. I only figured it out because console logged the error object, so I found out my Slug has no Attached Field. It is required and the error message says:
`"contentType.attributes.Slug.targetField must be one of the following values: Title"`. 

Also UID field didn't warn me to set an Attached field, because its required.

### Steps to reproduce the behavior

1. Create a new project with strapi
2. Try to create a new content type and add a UID field without Attached filed
3. Try to find out what the error message means.

### Expected behavior

Clear and Informative error message.

### Screenshots

<img width="820" alt="image" src="https://user-images.githubusercontent.com/60651308/187178086-d81b9b49-7f78-4f4e-b678-7fa7efca4bf0.png">

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/60651308/187177799-1f2bae27-2bf8-40c0-b3d6-4307dac78f3f.png">

### Code snippets

--

### Additional context

--

**Comment by phollaki** [comment]
@gracebir No. Just create a fresh react project with strapi with npx (with latest strapi version). Then create a new content type in strapi Admin UI.

**Comment by alexandrebodin** [comment]
Hi, This issue has been fixed in the lastest versions of Strapi.
