### ISSUE TITLE
Call to /api/auth/github/callback?access_token=<token> returns a 400

### ISSUE THREAD

**Issue by larbish** [strapi/strapi#14257]
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0 (yarn 1.22.18)
- Strapi version: 4.3.6
- Database: pgsql
- Operating system: OSX

### Describe the bug

Using Github oAuth provider - the call to the strapi server for callback returns a 400 

Response for `http://localhost:1337/api/auth/github/callback?access_token=<token>` is :

`{"data":null,"error":{"status":400,"name":"ApplicationError","message":"401 Unauthorized","details":{}}}`

### Steps to reproduce the behavior

1. Try working oauth in 4.3.4
2. Update to 4.3.6 (4.3.5 is broken because of #14198)
3. Try oauth again 
4. Strapi server returns a 400 error
5. Reverting back  to 4.3.4 fix it
 
### Expected behavior

Succefull login

### Additional context

This method is never reached: https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/services/providers-registry.js#L282

**Comment by HmnSDR** [comment]
Can you pls send me only one passord can connect to authe

**Comment by marcelobaez** [comment]
I'm having the same issue! I'm using the microsoft provider, its well configured and enabled. Same as you, I've been able to get the access token in my frontend, and sent it to /api/auth/{provider}/callback?access_token={accesstoken}. Strapi always responds with 403 forbidden
