### ISSUE TITLE
strapi-provider-upload-google-cloud-storage not able to edit video

### ISSUE THREAD

**Issue by jamesaphoenix** [strapi/strapi#14250]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.3.3
- Database: CloudSQL (postgres)
- Operating system: Linux

### Describe the bug

Currently I am saving all of my media in cloud storage with the following cloud provider -  https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage

Version: `"@strapi-community/strapi-provider-upload-google-cloud-storage": "^4.2.3"`

### Steps to reproduce the behavior

I cannot delete, edit or re-select any of the media for a Video. However images work just fine.

### Expected behavior

The media video should have dimensions and should be editable within the admin dashboard.

### Screenshots
![Screenshot 2022-08-29 at 16 25 12](https://user-images.githubusercontent.com/17482746/187241289-eb883cb7-c527-4a3c-9b32-8cc719663b61.png)

**Comment by StrapiShaun** [comment]
I am having the same issue with DigitalOcean (using the AWS s3 provider). Images and audio files can be selected, but the only way to select videos is the 'select all' at the top of the media library.

**Comment by kasonde** [comment]
Hi 👋🏾 
Closing this issue as it's not a Strapi issue but an issue with the provider itself. [Here's the problem](https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage/issues/132) . We're experiencing the same thing with DigitalOcean spaces with our S3 provider.
