### ISSUE TITLE
Use of lifecycle error handling in production.

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [strapi/strapi#14263]
Node.js version: v14
Strapi version: 4.3.6
Database: postgres
Operating system: MAC

I am currently using the library:  For error handling in a lifecycle of a particular content-type.

```js
const { errors } = require("@strapi/utils"); // version: ^3.6.10
```

The problem is the following, using the following code as a reference:

```js
module.exports = {
   beforeCreate: async(ctx) => {
    const identifier = ctx.params.data.identifier;

     if (!identifier) {
       throw new ApplicationError("The identifier was not provided");
     }
    // ....
   },
};
```

When I'm working on localhost (development mode) with NextJS the error is the expected *The identifier was not provided*, but when the client application is in production it always sends the error "Internal Server Error". It is as if it did not overwrite the message.

In Production:
<img width="265" alt="1" src="https://user-images.githubusercontent.com/21962584/187497436-7e167345-09c9-401d-8d22-13d2db247c73.png">

In Development:
<img width="245" alt="2" src="https://user-images.githubusercontent.com/21962584/187497500-fc55a951-8a53-48fb-8c09-98266493e472.png">

My intention is that both in production and in development the errors are the same. I will appreciate your help!

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
