### ISSUE TITLE
Save application logs in .log file

### ISSUE THREAD

**Issue by Thyvo** [strapi/strapi#1427]
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 5.6.0 
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: MongoDB
- **Operating system**: Server 2016

**What is the current behavior?**
Hi,

I would like to write my console output (info to error) to written into a logfile.

I already tried the code below to write the output to a file, unfortunately, nothing gets written to the file.

(File: config/functions/bootstrap.js)
```
'use strict';
var fs = require('fs')

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */

module.exports = cb => {
  console.log('starting in mode: '+ process.env.NODE_ENV)
  if (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'commandline') {
    var access = null, 
        error = null,
        dir = __basedir + 'logs/'
    if (process.env.NODE_ENV === 'commandline') {
      error   = dir + 'error.cmd.log'
      access  = dir + 'access.cmd.log'
    } else {
      error   = dir + 'error.prod.log'
      access  = dir + 'access.prod.log'
    }
    access = fs.createWriteStream(access, { flags: 'a' })
    error = fs.createWriteStream(error, { flags: 'a' })
    proc.stdout.pipe(access)
    proc.stderr.pipe(error)
  }
  console.log('started in mode: '+ process.env.NODE_ENV)
  cb();
};
```
What would be the best way to achieve this?

**Comment by derrickmehaffy** [comment]
I would also be interested in this, I've been using a temp solution when starting strapi to push the console to a file.

`strapi start > ~/strapi.log` 

Obvious this isn't the best solution. Also just a heads up @Thyvo Windows support for strapi is hit or miss at this moment I recommend you use the WSL (Ubuntu) or do development in a linux VM

**Comment by Aurelsicoko** [comment]
We are using Pino (https://github.com/pinojs/pino/) to display the logs in the terminal. There is an option to write the logs inside a file, we could extend our current support. It should not be that hard to make it work!

@derrickmehaffy Are you interested to make a try and open a PR?

**Comment by derrickmehaffy** [comment]
I'll take a look once I get home from work to see if this is something within my skillset. :smile:

**Comment by entwicklerfr** [comment]
Hello @Aurelsicoko,

You are currently using `pino` and `pino-std-serializers`.  
Is it possible to use the core package pino-tee for an easier implementation of this feature ?

**Comment by entwicklerfr** [comment]
Hello @derrickmehaffy ,

I pushed a PR this morning: "Save application logs in .log file" :  #2183

**Comment by lauriejim** [comment]
I will review you RP @entwicklerfr

**Comment by derrickmehaffy** [comment]
awesome @entwicklerfr I look forward to taking a look, pm2 does a pretty decent job but having actual log files will be handy

**Comment by maturanomx** [comment]
Just to make visible my opinion about why I think this should not be a feature of Strapi: https://github.com/strapi/strapi/pull/2183#pullrequestreview-167650420

**Comment by maturanomx** [comment]
> Logs should be routed not by the application, but by the exection environment the application runs in. Node applications typically write logs to `stdout` using the `console` module. Instead of the application specifying where the logs should end up, write to `stdout` using `console` and then let the execution environment (container, server, etc.) pipe the `stdout` stream to the appropriate destination (i.e. Splunk, Graylog, etc.).
**Otherwise:** Application handling log routing === hard to scale, loss of logs, poor separation of concerns

More extensive argumentation: https://github.com/i0natan/nodebestpractices/pull/272/files

Totally support that.

**Comment by Aurelsicoko** [comment]
@maturanomx Me too. It's the exact same situation we had with SSL. We could handle it but it's not part of our job. There are plenty of others solutions that write logs better than us. 

We're offering a Node.js application that allows people to build API quickly with a dashboard to manage the content. We should not handle SSL, logs, views, etc. We can do it but we won't do it because it's not in our scope.

@entwicklerfr I really appreciate the work you've done ( 👍). However, we should limit your work to this mission: Follow best practices to make sure the logs are usable for dedicated logs tools/solutions.

**Comment by entwicklerfr** [comment]
@Aurelsicoko,

I simply took an User Story in the strapi backlog.  
If the Owner of this Product finally decides to not implement this feature it's absolutely not a problem for me.  
I simply stop my current work on this Pull Request.  
At least things are clear.
:ok_hand:

**Comment by Aurelsicoko** [comment]
@entwicklerfr Thank you for your understanding 👍 

Can you give me the link where you saw this task? I'll remove it and maybe remove the whole backlog because it doesn't seem up-to-date.

**Comment by gtamas** [comment]
@Aurelsicoko 
How to tell strapi to log normal JSON to stdout?
I would like to to send log messages to graylog, using pino-gelf. 
However, Strapi currently does not print the JSON, but it prints some fancy formatted message instead.

Or is there a better way to push the logged messages to graylog?

Thanks in advance!

**Comment by derrickmehaffy** [comment]
@gtamas I do exactly that: https://github.com/sethblack/pm2-gelf-pro

my `~/.pm2/module_config.json`

```json
{
    "pm2-gelf-pro": {
        "graylogPort": 12201,
        "graylogHost": "-snip-",
        "gelfAdapterName": "udp",
        "graylogFields": "{\"app\": \"-snip-\"}"
    },
    "module-db-v2": {
        "pm2-gelf-pro": {}
    }
}
```

**Comment by gtamas** [comment]
@derrickmehaffy 
Thanks!
Do you know how to prevent Strapi from logging events below a given log level? I wanna log only warn and above, but Strapi seems to log pretty much everything.

E.g: whenever a request is received, it prints stuff like:

`{"level":20,"msg":"GET /favicon.ico (1 ms)","pid":28206,"hostname":"somehost","v":1}`

I dont't want to log these, only the things I log explicitly via strapi.log or ctx.log() commands.

**Comment by gayathrinukala** [comment]
> I would also be interested in this, I've been using a temp solution when starting strapi to push the console to a file.
> 
> `strapi start > ~/strapi.log`
> 
> Obvious this isn't the best solution. Also just a heads up @Thyvo Windows support for strapi is hit or miss at this moment I recommend you use the WSL (Ubuntu) or do development in a linux VM

**Comment by gayathrinukala** [comment]
> I would also be interested in this, I've been using a temp solution when starting strapi to push the console to a file.
> 
> `strapi start > ~/strapi.log`
> 
> Obvious this isn't the best solution. Also just a heads up @Thyvo Windows support for strapi is hit or miss at this moment I recommend you use the WSL (Ubuntu) or do development in a linux VM
