### ISSUE TITLE
GraphQL schema doesn't reflect usersPermissionsUsers query result

### ISSUE THREAD

**Issue by MoOx** [strapi/strapi#14277]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.7.0
- Strapi version: 4.3.6
- Database: postres 14.2-1.pgdg110+1
- Operating system: macOS 12.5.1

### Describe the bug

I am doing a graphql query like `usersPermissionsUsers`

```graphql
  query User_getByUsername_Query($username: String!) {
    usersPermissionsUsers(filters: {username: {eq: $username}}) {
      data {
        id
        attributes {
          username
          email
        }
      }
    }
  }
```

Schema says this query returns `UsersPermissionsUserEntityResponseCollection`

Which is 

```graphql
type UsersPermissionsUserEntityResponseCollection {
  data: [UsersPermissionsUserEntity!]!
  meta: ResponseCollectionMeta!
}
```

But in my case I don't receive an array of data, but directly a single result:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/157534/187708999-f593e964-3ad6-48d8-8fcf-db0383cac458.png">

### Steps to reproduce the behavior

1. Just call a similar query using EQ filter on `usersPermissionsUsers`

### Expected behavior

The result should reflect graphql schema & return an array with a single entry.

**When using GraphQL client like Relay, generated code from the schema expect the result to match the query schema, thus generate code that won't work during runtime. **

**Comment by MoOx** [comment]
Hummm. I faced something weird. Not sure what I did but it seems I am not able to reproduce this issue.

**Comment by kasonde** [comment]
Hi @MoOx I think the issue was you queried a singular user. I'm referencing the image you shared here: 
![image](https://user-images.githubusercontent.com/13610895/187746184-7f1b6b8f-0372-4110-96cd-c307d943330f.png)
