### ISSUE TITLE
S3 providers are transposing the bucket and endpoint for video uploads

### ISSUE THREAD

**Issue by StrapiShaun** [strapi/strapi#14288]
### Required System information

- Node.js version: 14.19.3
- NPM version: yarn 1.22.18
- Strapi version: 4.3.6
- Database: Postgres/SQlite
- Operating system: Mac OS 12.4

### Describe the bug

When uploading videos to Digital Ocean Spaces the S3 providers return the file address incorrectly. The bucket and endpoint are transposed in the address and `http` is missing (see screenshot). 

### Steps to reproduce the behavior

1. Add an S3 provider to a Strapi project (AWS or community DO for example).
2. Connect to a DO spaces account
3. Add a video to the media library 
4. inspect the uploaded video with the browser dev tools and see the incorrect address.

### Expected behavior

Return the correct address for video storage. 

### Screenshots

First 2 lines are for a functioning image upload. Lines 3-5 are for the video upload. 

<img width="1186" alt="Screen Shot 2022-09-01 at 16 55 54" src="https://user-images.githubusercontent.com/97027841/187956947-cb8dbe79-4ad7-4547-9a49-bcc8c4313a20.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

There is a test Strapi project and Spaces account in the company DO account that illustrates this problem. 
Adding after discussion with @petersg83

**Comment by petersg83** [comment]
@derrickmehaffy Did you reproduce the error? I couldn't find how to do it on my side

**Comment by derrickmehaffy** [comment]
Not me directly no but the issue has come up with @kasonde I believe.

Iirc it may depend on the file size (that might be another issue though)

**Comment by StrapiShaun** [comment]
Good catch @derrickmehaffy. I just tried again and small (<1mb) works, but larger clips still transpose the URL.

**Comment by petersg83** [comment]
I could reproduced. Interesting indeed, in one case the S3 returns an url with https `https://doproviderstestaug.fra1.digitaloceanspaces.com/video_6fc92eb8b5.mov` and on the other one without `fra1.digitaloceanspaces.com/doproviderstestaug/4dbaa904f4b1a03f2725417ca2fa05ba_4213e7bb7c.mov`.
I wonder what is going on. 
Do we have to prepend the http ourselves

**Comment by petersg83** [comment]
I couldn't reproduce using directly S3.

**Comment by petersg83** [comment]
Should we handle that in our side or should we tell DO and wait for them to fix it if it's on their side?<
@derrickmehaffy @StrapiShaun Do you know any way to contact them?

**Comment by derrickmehaffy** [comment]
We have a shared channel with them in our internal slack.

**Comment by StrapiShaun** [comment]
Hi, I just tested this. For me, it is adding the protocol but still not parsing the address correctly (screenshot). The bucket name (`videotest` in this example) is being added after the endpoint (`fra1`... in this example) for larger video files, but it is working correctly for smaller videos or images. My application is using v4.4.7. 
<img width="454" alt="Screen Shot 2022-11-08 at 07 13 01" src="https://user-images.githubusercontent.com/97027841/200488929-e9cc8425-5240-49cb-9425-a3077c37621f.png">

**Comment by nathan-pichon** [comment]
> Hi, I just tested this. For me, it is adding the protocol but still not parsing the address correctly (screenshot). The bucket name (`videotest` in this example) is being added after the endpoint (`fra1`... in this example) for larger video files, but it is working correctly for smaller videos or images. My application is using v4.4.7. <img alt="Screen Shot 2022-11-08 at 07 13 01" width="454" src="https://user-images.githubusercontent.com/97027841/200488929-e9cc8425-5240-49cb-9425-a3077c37621f.png">

This address is correct, no? I can download the file through this url.
I just checked, we cannot play this video in our admin panel, but we can download the file. I might need to dive a bit more on how we display videos in our admin panel.

**Comment by nathan-pichon** [comment]
I just figured out why it doesn't display on admin panel. Thanks to @petersg83 
@StrapiShaun As the domain changes, and that we have no power to change anything, it is Digital Ocean that imposes us the url used to retrieve the file, it is necessary to update the middleware security to add the url `fra1.digitaloceanspaces.com` in the authorized domains.

**Comment by StrapiShaun** [comment]
Thanks @nathan-pichon. All good now. closing this issue.

**Comment by laurenskling** [comment]
> We have a shared channel with them in our internal slack.

@derrickmehaffy did they ever respond? I've written my own S3 uploader to DO and struggling with the difference in response url when files get larger than about 5.2M

**Comment by StrapiShaun** [comment]
@laurenskling checkout the security middleware config in [my test project](https://github.com/StrapiShaun/testDOnovember/blob/main/config/env/production/middlewares.js). In this case, you need to list both '*.fra1.digital...' and 'fra1.digital...' to encompass the way DO returns the URLs.

**Comment by laurenskling** [comment]
The security is not my issue. I now have 2 different URL formats in my database, so sending different formats in my API.
