### ISSUE TITLE
TS QueryEngine populate accepts only array type

### ISSUE THREAD

**Issue by antokhio** [strapi/strapi#14286]
## Bug report
According to example from [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/query-engine/populating.html)

```
strapi.db.query('api::article.article').findMany({
  populate: {
    componentB: true,
    dynamiczoneA: true,
    relation: someLogic || true,
  },
});
```

### Required System information

- Node.js version: 16.4
- Strapi version: 4.3.2
- Template --typescript

### Describe the bug

```
let invitation = await strapi.db
  .query("api::collaborator.collaborator")
  .findOne({
    where: {
      user: user.id,
      project: data.project,
      collaborator: data.collaborator,
    },
    //populate: ["user", "project", "collaborator"],
    populate: {
      user: true,
      project: true,
      collaborator: true,
    }
  });
```
however property "populate" is ```(property) FindParams<AllTypes>.populate?: (string | number | symbol)[]```
resulting: 
```
Type '{ user: true; project: true; collaborator: true; }' is not assignable to type '(string | number | symbol)[]'.
````

So currently: 
``` populate: ["user", "project", "collaborator"]```

works however passing object should work too according to the docs.

**Comment by kasonde** [comment]
Confirmed. Even just saying `populate: true` breaks the project.

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
