### ISSUE TITLE
Warning during installation

### ISSUE THREAD

**Issue by ilosrim** [strapi/strapi#14289]
Hello 👋
Such a warning appears during the installation of "Strapi":
```bash
⠙ Installing dependencies: warning @strapi/strapi > koa-session > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by derrickmehaffy** [comment]
Thank you for the information but you can safely ignore this, likewise next time please follow the issue template

> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
