### ISSUE TITLE
New filter `in`?

### ISSUE THREAD

**Issue by johannpinson** [strapi/strapi#1428]
hey @soupette @Aurelsicoko 

What is this new kind filter with the keyword `in`?
I see you use it for the admin, but what about for using it with the API directly?

https://github.com/strapi/strapi/blob/8832a5baab70655eeb79ccaec79fedd53f0b60e9/packages/strapi-utils/lib/models.js#L472

cf. commit https://github.com/strapi/strapi/commit/8832a5baab70655eeb79ccaec79fedd53f0b60e9#diff-bf3a6e5f9eb97177916c46670dc7046e

**Comment by soupette** [comment]
hi @johannpinson this filter is used for the search especially with mongo

**Comment by johannpinson** [comment]
Ok but i didn't see here it's used.
Is it for filtering about a relation?

**Comment by Aurelsicoko** [comment]
@johannpinson No, it's to simulate the SQL query `LIKE` with Mongo. However, we could use it for another purpose as well like relation filtering 👍

**Comment by johannpinson** [comment]
@Aurelsicoko 
Just to be sure, why it's not used the `contains(s)` filter if it's to make a `LIKE` operation?

**Comment by Aurelsicoko** [comment]
@johannpinson Great question, @soupette worked on it, he will probably give a better answer than me.

**Comment by soupette** [comment]
@johannpinson you're right this filter is not needed anymore I started to use it with Mongo to make a full test search but I went for another solution.

It should be removed

**Comment by johannpinson** [comment]
@soupette Ok, I will let you remove it in next release and close this issue btw 😉
