### ISSUE TITLE
Use Server Environment Variables for Database Configuration

### ISSUE THREAD

**Issue by szelee** [strapi/strapi#143]
**Node.js version**: 4..5.0
**npm version**: 3.10.6
**Strapi version**: 1.5.4
**Operating system**: Windows 10

I would like to use Server Environment Variables for Strapi Database Configuration. The only way to configure the environment variables for the database is using the solution recommended by the following link:

http://stackoverflow.com/questions/36722661/strapi-configure-with-environment-variables

Hope this can be improved with a proper configuration without modifying the server.js file.

**Comment by Aurelsicoko** [comment]
Thanks for opening this issue @szelee. This is definitely something we need to improve on the v3.
IMO, we have only one solution to solve this. We should use the ES6 template syntax to allow dynamic values.

For example, a configuration's file could look like this:
```
"connections": {
    "permanent": {
      "adapter": "mysql",
      "user": "${DB_USER}",
      "password": "${DB_PASSWORD}",
      "database": "${DB_NAME || 'test'}",
      "host": "127.0.0.1",
      "migrate": "alter"
    }
 }
```

This is pretty easy to implement and the JSON syntax is valid.

**Comment by Aurelsicoko** [comment]
Merged on master.

**Comment by trungkhong** [comment]
How to config in mongodb?? Please help me! "sails-mongo" can't install, I tried to download zip module and add to node_modules  but still can not run.

**Comment by Kostanos** [comment]
Trying to use: 
```
"host": "${DB_HOST}"
or
"host": "${DATABASE_HOST}"
```
and get error like:
`error DB_HOST is not defined`

So, the only way is to use: 

```
"host": "${process.env.DATABASE_HOST}",  // Depends on which ENV variable are you using.
```

**Comment by Aurelsicoko** [comment]
@Kostanos You're right, I've updated my previous example.
