### ISSUE TITLE
Json reset when uploading media

### ISSUE THREAD

**Issue by GreatGeorge1** [strapi/strapi#1430]
**Informations**
I am using the latest stable docker image on ubuntu 16.04.
Docker version 18.03.1-ce, build 9ee9f40
Strapi v3.0.0-alpha.12.4

**What is the current behavior?**
When uploading media object, json fields setting undefined.

**Steps to reproduce the problem**
Create type with media object (supporting multiple files or not doesn't matter). 
Create a new object of that type, input some json, save.
Reopen, upload some images, save.
Reopen, json is not defined.

**Comment by lauriejim** [comment]
Can you open this issue on `strapi-docker` repo https://github.com/strapi/strapi-docker
