### ISSUE TITLE
 Abandoned ses provider core library

### ISSUE THREAD

**Issue by danquack** [strapi/strapi#14307]
The node module (node-ses) has been abandoned with the last contribution 2 years ago. The sole maintainer recommends not using this module anymore. 
https://github.com/aheckmann/node-ses/issues/73#issuecomment-847081281

Provider: https://github.com/strapi/strapi/tree/main/packages/providers/email-amazon-ses

I am not sure the process that should be in place for maintaining plugins, but was hoping to start a conversation on what it would take to convert to the aws sdk or similar.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
