### ISSUE TITLE
Typescript `@strapi/typescript-utils`'s `getConfigPath` return false negative due to incorrect directory checking procedure in Windows

### ISSUE THREAD

**Issue by rachasakr** [strapi/strapi#14306]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.6
- Database: Postgres
- Operating system: Windows 10

### Describe the bug

When starting Strapi with a Typescript-enabled project, in the `getConfigPath` function, [`dirAbsolutePath = path.resolve(dir)`](https://github.com/strapi/strapi/blob/main/packages/utils/typescript/lib/utils/get-config-path.js#L19) return _backward_ slash but `typescript`'s [`ts.findConfigFile`](https://github.com/strapi/strapi/blob/main/packages/utils/typescript/lib/utils/get-config-path.js#L20) return _forward_ slash. So when checking directory using `configFilePath.startsWith`, instead of `true`, it return `false` even if `tsconfig.json` is exists in both root and admin folder.

### Steps to reproduce the behavior

1. Create Strapi project with Typescript support and create `tsconfig.json` according to [Strapi documentation](https://docs.strapi.io/developer-docs/latest/development/typescript.html#add-typescript-support-to-an-existing-strapi-project)
2. `yarn`
3. `yarn start`

### Expected behavior

`getConfigPath` should return `true` if `tsconfig.json` is exists.

### Screenshots

![image](https://user-images.githubusercontent.com/27821769/188278262-a87d6f66-eea9-4633-9f3a-e0567485f0a3.png)

```
PS <project folder>\app> yarn strapi start
yarn run v1.22.19
warning ..\..\..\..\package.json: No license field
$ strapi start
getConfigPath <project folder>\app tsconfig.json <project folder>/app/tsconfig.json
<project folder>\app isTSProject false
getConfigPath <project folder>\app tsconfig.json <project folder>/app/tsconfig.json
getConfigPath <project folder>\app tsconfig.json <project folder>/app/tsconfig.json
getConfigPath <project folder>\app\src\admin tsconfig.json <project folder>/app/src/admin/tsconfig.json
[2022-09-03 22:31:53.588] debug: ⛔️ Server wasn't able to start properly.
[2022-09-03 22:31:53.591] error: Unknown dialect undefined
Error: Unknown dialect undefined
    at getDialectClass (<project folder>\app\node_modules\@strapi\database\lib\dialects\index.js:12:13)
    at getDialect (<project folder>\app\node_modules\@strapi\database\lib\dialects\index.js:19:23)
    at new Database (<project folder>\app\node_modules\@strapi\database\lib\index.js:27:20)
    at Function.Database.init (<project folder>\app\node_modules\@strapi\database\lib\index.js:77:35)
    at Strapi.bootstrap (<project folder>\app\node_modules\@strapi\strapi\lib\Strapi.js:392:30)
    at Strapi.load (<project folder>\app\node_modules\@strapi\strapi\lib\Strapi.js:457:16)
    at async Strapi.start (<project folder>\app\node_modules\@strapi\strapi\lib\Strapi.js:198:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Code snippets

Modified from [get-config-path.js](https://github.com/strapi/strapi/blob/main/packages/utils/typescript/lib/utils/get-config-path.js)

```
module.exports = (dir, { filename = DEFAULT_TS_CONFIG_FILENAME, ancestorsLookup = false } = {}) => {
  const dirAbsolutePath = path.resolve(dir);
  const configFilePath = ts.findConfigFile(dirAbsolutePath, ts.sys.fileExists, filename);
  console.log('getConfigPath', dirAbsolutePath, filename, configFilePath);
...
```

### Potential solution

Instead of `String.startsWith`, use [`path.normalize`](https://nodejs.org/api/path.html#pathnormalizepath) first.

**Comment by rachasakr** [comment]
FYI, I've updated [the return line](https://github.com/strapi/strapi/blob/main/packages/utils/typescript/lib/utils/get-config-path.js#L26) to this and it's now working properly:

```
return path.normalize(configFilePath).startsWith(dirAbsolutePath) ? configFilePath : undefined;
```

**Comment by rachasakr** [comment]
Searching further in `typescript`'s repo, it seems they [strictly use forward slash](https://github.com/microsoft/TypeScript/blob/main/src/compiler/path.ts#L503) regardless of OS. So we either give in with TypeScrpt or do the path normalizing mentioned above.

**Comment by rachasakr** [comment]
PS: This issue might duplicate with #14088. But you might consider the solution mentioned above.

**Comment by palbrecht1** [comment]
Thanks a lot!!

**Comment by derrickmehaffy** [comment]
In my attempt to reproduce, got the issue straight away on Windows 10

![image](https://user-images.githubusercontent.com/8593673/190639862-a91a5a92-38c2-4e44-951d-5e9e58012059.png)

![image](https://user-images.githubusercontent.com/8593673/190639712-dafccbcb-a46a-4b52-bde1-2b06cefb5f02.png)

**Comment by derrickmehaffy** [comment]
Also related to internal TID1832 for an EE customer

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/13237

**Comment by kadhumalrubaye** [comment]
> FYI, I've updated [the return line](https://github.com/strapi/strapi/blob/main/packages/utils/typescript/lib/utils/get-config-path.js#L26) to this and it's now working properly:
> 
> ```
> return path.normalize(configFilePath).startsWith(dirAbsolutePath) ? configFilePath : undefined;
> ```

it works  on local, thanks , but what if i deploy the project on a host machine ? the module folder will removed  and new one will be created on the host with the same error ? every time i deploy the code i should edit it manually ?
