### ISSUE TITLE
UID fields can not be created without an attached field

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#14312]
## Bug report

@kasonde [reported internally](https://strapihq.slack.com/archives/CEN0F9WF6/p1662274230026039) that it is impossible to create uid fields, which are not attached to another field.

Shared loom video: https://www.loom.com/share/59e284d5a90b4ffd9cf7943f7e120eff

Backend error thrown:

```json
{
  "error":{
    "name":"ValidationError",
    "message":"contentType.attributes.test.targetField must be one of the following values: name",
    "details":{
      "errors":[
        {
          "path":["contentType","attributes","test","targetField"],
          "message":"contentType.attributes.test.targetField must be one of the following values: name","name":"ValidationError"
        }
      ]
    }
  }
}
```

It looks like as if this is a regression.

### Required System information

- Node.js version: not relevant
- NPM version: not relevant
- Strapi version: 4.3.6
- Database: not relevant
- Operating system: not relevant

### Steps to reproduce the behavior

See attached loom video.

### Expected behavior

It was validated with @yanniskadiri that we do want to support uid fields, which are not attached to another field.

**Comment by jaysoni-ash42** [comment]
@gu-stav  i want to work on this  do we need to remove the none field from the selector and add a validation for the attached field to be required?

**Comment by gu-stav** [comment]
@jaysoni-ash42 That sounds great, thanks! I think the first step would be fixing the validation error (which should not happen). I'm not sure if there will be follow-up tasks or if it will work out of the box. In case you hit any roadblocks, feel free to ping me here or on discord.
