### ISSUE TITLE
Missing Language Code for Te Reo Māori

### ISSUE THREAD

**Issue by chris-turner-datacom** [strapi/strapi#14319]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.3.5
- Database: SQLite
- Operating system: Windows 10

### Describe the bug

Currently, when creating a Locale, Te Reo Māori (mi) is not an option for a language code in the dropdown.

### Steps to reproduce the behavior

1. Go to 'Settings>Internationalization'
2. Click on 'Add new locale'
3. Type 'Māori' or 'mi' in the Locales box
4. No results are shown

### Expected behavior

Te Reo Māori (mi) should be included as an option.

### Additional context

Te Reo Māori is an official language of New Zealand and all government websites must be presented in both English and Te Reo Māori.

**Comment by kasonde** [comment]
Hi please submit a pull request to add your desired language in a future release of Strapi. We're still working on a better workflow for this but for now, this is the only way to get the language added.
