### ISSUE TITLE
Fetch error: Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by kwzm** [strapi/strapi#1431]
**Informations**
- **Node.js version**: v10.1.0
- **npm version**: v5.6.0
- **Strapi version**: 3.0.0-alpha.12.2"
- **Database**: mongoDB
- **Operating system**: win7 x64

**What is the current behavior?**

When I fetched api, it consoled error like that:

`Failed to load http://10.2.5.98:1337/api/product?_start=0&_limit=20: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://10.2.5.98' is therefore not allowed access.`

**Steps to reproduce the problem**

I used [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) to fetched like this:

```js
return fetch(apiUrl, newOptions)
    .then(checkStatus)
    .then(parseJSON)
    .then(data => ({ data }))
    .catch((err) => {
      return Promise.reject(err);
    });
```

I didn't set credentials mode was 'include'.

And the security in production is like this:

```json
{
  "csrf": {
    "enabled": false,
    "key": "_csrf",
    "secret": "_csrfSecret"
  },
  "csp": {
    "enabled": true,
    "policy": [{
        "img-src": "'self' http:"
      },
      "block-all-mixed-content"
    ]
  },
  "p3p": {
    "enabled": true,
    "value": ""
  },
  "hsts": {
    "enabled": true,
    "maxAge": 31536000,
    "includeSubDomains": true
  },
  "xframe": {
    "enabled": true,
    "value": "SAMEORIGIN"
  },
  "xss": {
    "enabled": true,
    "mode": "block"
  },
  "cors": {
    "enabled": true,
    "origin": "*",
    "expose": [
      "WWW-Authenticate",
      "Server-Authorization"
    ],
    "maxAge": 31536000,
    "credentials": true,
    "methods": [
      "GET",
      "POST",
      "PUT",
      "PATCH",
      "DELETE",
      "OPTIONS",
      "HEAD"
    ],
    "headers": [
      "Content-Type",
      "Authorization",
      "X-Frame-Options",
      "Origin"
    ]
  },
  "ip": {
    "enabled": false,
    "whiteList": [],
    "blackList": []
  }
}
```

It's almost the same as development, but the development is well, the prodution is bad.

**What is the expected behavior?**

Fetch is ok.

**Suggested solutions**

No

**Comment by kwzm** [comment]
Then I modify origin to http://10.2.5.98 like this:

![default](https://user-images.githubusercontent.com/16114101/41634955-b3b09aca-7478-11e8-87e0-1a0e5d3f18e2.PNG)


But the response header Access-Controll-Allow-Origin still is *:


![default](https://user-images.githubusercontent.com/16114101/41634864-4c776a32-7478-11e8-9f4b-238a3a320529.PNG)

**Comment by kwzm** [comment]
@derrickmehaffy Hi, how to update strapi, just install strapi@3.0.0-alpha.12.5 is ok ? What about admin, does it need to update ?

**Comment by lauriejim** [comment]
Your issue has been fixed in `3.0.0-alpha.12.3` - https://github.com/strapi/strapi/pull/1298

Check here for migration guide https://github.com/strapi/strapi/wiki

**Comment by derrickmehaffy** [comment]
@kwzm Aye, follow the migration guides going from 12.2 -> 12.3, 12.3 -> 12.4. and 12.4 -> 12.5

**Comment by kwzm** [comment]
@lauriejim @derrickmehaffy  First of all, thanks a lot, you replied so fast.

And I red the migration guide, but I have some questions:

1.

![getting start](https://user-images.githubusercontent.com/16114101/41644747-94580b9e-74a1-11e8-919f-11bac66a8547.PNG)

Why I need to create a new project by strapi? Is it for copy new items to old project?

2.

![update node modules](https://user-images.githubusercontent.com/16114101/41644879-fda36c92-74a1-11e8-924a-af529acdc702.PNG)

Is update node modules in old project?

3.

![udpate admin](https://user-images.githubusercontent.com/16114101/41645009-4ffadff2-74a2-11e8-852d-8e27e40fd757.PNG)

Is that use new admin folder(create in Getting started) to cover old one(in old project)?

4.

![update the plugins](https://user-images.githubusercontent.com/16114101/41645150-b15797a4-74a2-11e8-974b-6c941309709a.PNG)

I don't understand this sentence 'Copy the fields and relations you had in your /plugins/users-permissions/models/User.settings.json file in the new one.' , copy for what? Since next step will use new plugins folder to cover old one, why do we have to copy the `User.settings.json` in the new one?

5.

![default](https://user-images.githubusercontent.com/16114101/41645770-867d5288-74a4-11e8-8e33-cc96bdc736ec.PNG)

Is all my api need to add a new route?
Is the article(read underline) replace to my api name?

Sorry for asking so many questions, I am a beginner.

And please forgive me for my poor English.

**Comment by kwzm** [comment]
@derrickmehaffy Thanks a lot, after reading you reply, I was suddenly enlightened. :)

**Comment by kwzm** [comment]
@derrickmehaffy Thank you for your compliment, you are flattering me. :smile:

**Comment by kwzm** [comment]
@derrickmehaffy Hi, I updated my local project successfully, and then used git to push in gitlab. Now I pulled the latest code from the gitlab in ubunto, then ran `npm install --production` `NODE_ENV=production npm strat` as the [blog](https://blog.strapi.io/how-to-deploy-a-strapi-application/) says, but got a error like this:

![default](https://user-images.githubusercontent.com/16114101/41693838-dc2b1e64-7539-11e8-9cbd-87652de21242.PNG)


Actually, I got some warning after running `npm install --production`, but I was not sure if it has effects.

![default](https://user-images.githubusercontent.com/16114101/41693945-768d4ca2-753a-11e8-8152-2f0d58707e36.PNG)


PS: My node and npm versions in ubunto were the same as local, so I was confused.

**Comment by derrickmehaffy** [comment]
@kwzm Yeah I've had issues with that as well, it seems when you upload to git the package.json doesn't include everything that the Strapi-CLI installs (When you use `strapi new -projectname-` it installs some npm packages as well)

Not sure you need the --production bit though. Also pretty sure npm start doesn't work unless you modify the startup command.

@lauriejim what is the best way to handle these packages not being resolved after upload a project to github? I usually just install them one by one and use the --save option. Is this something we could have added to the package.json?

**Comment by kwzm** [comment]
@derrickmehaffy Hi, it seems that I am not alone in this problem :smile: , and just like you I am also install them one by one.
