### ISSUE TITLE
Cannot add component field to Content Manager Table/List

### ISSUE THREAD

**Issue by thomas-br** [strapi/strapi#14318]
### Required System information

- Node.js version: v14.19.3
- NPM version: 6.14.17
- Strapi version: 4.3.6
- Database: SQLite, MySQL, MariaDB
- Operating system: MacOS / Linux

### Describe the bug

In our Content-Type model we have created & used a component for a typical field to reduce duplication. The component contains a string field and a relation. Example: Model `Book`, contains component `ISBN` with the sub-fields `ISBN-Number` (String) & `ISBN Type` (Relation to a Type Model).

It is not possible to add the ISBN Number to the Content-Manager Table/List or Search for it. If it was direct fields it would be possible to add as a table column. Also relations are possible to be added, which are treated internally very similar to components.

### Steps to reproduce the behavior

1. Go to Content-Editor of a suitable Content-Type
2. Try adding a Component field to the list of instances

### Expected behavior

The field that can be set as "Entry title" for a component when editing the view should be selectable and displayable in the Content Manager List/Table as a column.

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
