### ISSUE TITLE
slug set to null instead of empty String when using postgresql

### ISSUE THREAD

**Issue by ohayak** [strapi/strapi#14310]
### Required System information
- Node.js version: 16
- NPM version: 8.15
- Strapi version: 4.6.3
- Database: postgresql 13 (pg: 8.7.3)
- Operating system: MacOS

### Describe the bug

when creating an entry with an empty slug using strapi UI, the slug value is set to null instead of empty String in the database. this is particularly troublesome for people using dynamic pages with NextJS (the famous [[..slug]].ts).

### Steps to reproduce the behavior

1. create a new entry for an existing collection with empty slug
2. go to Postgres Data page and query the collection table to see the slug set to null

### Expected behavior

I think the expected behaviour is to have empty string. This what the corportate and blog templates (nextjs version) are expecting.
I think that the fact that initial data is inserted via bootstrap is dosn't produce this behaviour.

**Comment by derrickmehaffy** [comment]
Unsure of what logic we expect so assigning to content squad to confirm

**Comment by NeseemGit** [comment]
Any update on this? I am running into the same issue in particular with the Corporate Strapi starter. If a slug is left blank, the value is set to null but the code expects and empty string.

**Comment by derrickmehaffy** [comment]
> Any update on this? I am running into the same issue in particular with the Corporate Strapi starter. If a slug is left blank, the value is set to null but the code expects an empty string. 

Can you open an issue on the starter repo please?
