### ISSUE TITLE
New user password not being saved

### ISSUE THREAD

**Issue by santiagopampillo** [strapi/strapi#1432]
**Informations**
- **Node.js version**: 10.4.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.5
- **Database**: mongodb
- **Operating system**: ubuntu 16.4

**What is the current behavior?**
When creating a new user with a number only password (ex: "123456") the password is not being saved (null).

**Steps to reproduce the problem**
create a new user and assign him with 123456 password

**What is the expected behavior?**
to saved the hash password

**Suggested solutions**
I guess that this is a low priority but it should be added to the backlog.

**Comment by Saifr711** [comment]
I am facing the same issue actually.. anyone who has a solution for this? Really annoying as it is stopping me to complete the last dependency before I wrap up the project...

**Comment by derrickmehaffy** [comment]
@Saifr711 this issue is over a year old, which Strapi version are you on? If it's v3.1.x then please open up a new issue.
