### ISSUE TITLE
Migration to npm scoped package

### ISSUE THREAD

**Issue by johannpinson** [strapi/strapi#1433]
**What is the expected behavior?**

Actually, each npm package is named `strapi-myname`.
The goal will be to have `@strapi/myname`, like Babel or Angular.

Btw, there are also some eventually improvements:
- Change `strapi` package to `cli` (so it will become `@strapi/cli` and the folder will be `strapi-cli`)
- Is the `strapi-utils` may be `@strapi/core` because it's used (almost) everywhere? (or maybe `strapi` which also contains the CLI and some core functions?)
- `strapi-mongoose` and `strapi-bookself` to `@strapi/orm-mongoose` / `@strapi/orm-bookself` (or `@strapi/database-mongoose` for example)
- all `strapi-upload-*` as `@strapi/plugin-upload-*` (because it's depends of the plugin upload)
- same thing for the `email` package

**Comment by derrickmehaffy** [comment]
Documentation for scoped packages: https://docs.npmjs.com/misc/scope

**Comment by derrickmehaffy** [comment]
Btw +1 from me on this, I think following the standard is prob the best route here.

**Comment by Aurelsicoko** [comment]
We should definitely implement this 💯 

It will also impact our release script (https://github.com/strapi/strapi/blob/master/scripts/publish.js)

**Comment by johannpinson** [comment]
@Aurelsicoko 
cf. Babel for example, Lerna can be use directly to simplify the publish script:

https://github.com/babel/babel/blob/9283efaeb7a8c5b505b19332c3407dc44c668777/Makefile#L107-L117

**Comment by johannpinson** [comment]
@Aurelsicoko 
During creating some "test" projects, I see in the root `node_modules` that the `strapi` folder is a symlink for the global package installed.
Since I modify some files to make tests, bug fix or evolution, it applies it to all projects and I need to make a `npm install` at the root folder to change it.

By passing to the scope logic, it will allow to install only the `cli` on global and the `core` in the project folder (and why not the cli inside the project and target it with the `npx` command)

**Comment by Aurelsicoko** [comment]
@johannpinson We have the exact same approach than Sails on this part. When you're creating a new project, we're trying to detect if Strapi is installed globally. If yes, we are creating a symlink to this global version. It avoids to reinstall Strapi and to keep the same version whatever the project you're using. However, I agree it has some downsides as well. I'm not sure we should continue to do that because our ecosystem is more complicated than Sails.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I second this, especially for someone who manages their project on github, I would rather not have to install Strapi globally on every machine I need to deploy it to. Especially for automated deployments.

I've noticed that if I try and deploy my project on a server without strapi installed globally there are a number of missing packages. I could install it, but its just an extra step that could cause issues.

**Comment by lauriejim** [comment]
@derrickmehaffy, Normally if you are in a project and you run `npm i` it's reinstall all application node modules and plugins node module. So it's strange you have an issue by pushing your app in production.

**Comment by derrickmehaffy** [comment]
@lauriejim If you create a new project locally, push it to github, and deploy it on AWS or somewhere else and run `npm i` compare the two node_modules folders. :stuck_out_tongue:

**Comment by lauriejim** [comment]
Yes @derrickmehaffy , it's what said @Aurelsicoko https://github.com/strapi/strapi/issues/1433#issuecomment-403522883

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I think it might be best to add some kind of alternative option instead of symlinking the packages.

Is it possible to only install the `strapi-cli` and force projects to grab all the node_modules from npm instead of symlinking, we are hitting some issues when working with travis-ci and not having it install the `strapi@alpha` :slightly_frowning_face:

**Comment by abdonrd** [comment]
Any plan about this for the `beta`?

**Comment by lauriejim** [comment]
For now it's not planned.
We have to discuss and define what we have to do with this topic.

**Comment by lauriejim** [comment]
This topic not need to still open.
So I close this issue.
