### ISSUE TITLE
Strapi Admin Management on CDN MP4 video hint has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by fuxianwei** [strapi/strapi#14331]
## Bug report

Access to video at 'https://yuncha-new.oss-cn-hangzhou.aliyuncs.com/upload/bg_video_b792fd773b.mp4?updated_at=2022-09-06T08:57:03.294Z' from origin 'http://admin.guohan.bnzhyl.com:1337' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
yuncha-new.oss-cn-hangzhou.aliyuncs.com/upload/bg_video_b792fd773b.mp4?updated_at=2022-09-06T08:57:03.294Z:1          GET https://yuncha-new.oss-cn-hangzhou.aliyuncs.com/upload/bg_video_b792fd773b.mp4?updated_at=2022-09-06T08:57:03.294Z net::ERR_FAILED 206

### Required System information

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: 4.3.6
- Database: sqlite3
- Operating system:  mac os 12.4

### Describe the bug

I used Ali OSS provider to manage my media files, but after StrAPI admin controlled MP4 uploading successfully, console preview MP4 reported CORS error, please help me solve this problem,
I configured STRAPI :: Security and StrAPI :: Cors in the middleware, the uploaded pictures can be loaded normally, but the video can not be loaded in the list
 thank you

### Steps to reproduce the behavior

1. Go to 'Media Library'
2. Click on 'add new assets Upload a video to Ali cloud OSS'
3. Scroll down to 'View the file list after the video is uploaded successfully'
Access to video at 'https://yuncha-new.oss-cn-hangzhou.aliyuncs.com/upload/bg_video_b792fd773b.mp4?updated_at=2022-09-06T08:57:03.294Z' from origin 'http://admin.guohan.bnzhyl.com:1337' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
yuncha-new.oss-cn-hangzhou.aliyuncs.com/upload/bg_video_b792fd773b.mp4?updated_at=2022-09-06T08:57:03.294Z:1          GET https://yuncha-new.oss-cn-hangzhou.aliyuncs.com/upload/bg_video_b792fd773b.mp4?updated_at=2022-09-06T08:57:03.294Z net::ERR_FAILED 206

### Expected behavior

The video list is loaded properly

### Screenshots

<img width="1239" alt="截屏2022-09-07 12 42 57" src="https://user-images.githubusercontent.com/1736689/188790505-02758c27-fede-4d84-ad10-a16ee9332648.png">

### Code snippets

{
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", 'https:', 'http:'],
          'img-src': [
            "'self'",
            'data:',
            'blob:',
            'clips.vorwaerts-gmbh.de',
            'yuncha-new.oss-cn-hangzhou.aliyuncs.com',
          ],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            'clips.vorwaerts-gmbh.de',
            'yuncha-new.oss-cn-hangzhou.aliyuncs.com',
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  {
    name: 'strapi::cors',
    config: {
      origin: "*",
      methods: "*",
      headers: "*",
      keepHeaderOnError: true,
    },
  }

**Comment by smoothdvd** [comment]
You should config cross domain policy in Aliyun OSS.

**Comment by fuxianwei** [comment]
> You should config cross domain policy in Aliyun OSS.

Thank you for your answer. I'll try it

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
