### ISSUE TITLE
Can not import XML file into, Strapi fields (Migrate from WordPress to Strapi)

### ISSUE THREAD

**Issue by Chanaka-Sandaruwan** [strapi/strapi#14338]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.19.1
- Strapi version: 4.3.6
- Database: SQLite
- Operating system: Windows 10

### Describe the bug

My goal is to import posts from my Wordpress site into a custom NextJS site. My first step is to export the XML, convert it into JSON, filter all the content that I require, and then update the data into strapi fields. In a simple example, I create "cd" as my collection type and create a "title" field inside that entity, and I attempt to update all my previous Wordpress titles into that entity, attempting to follow the references provided by this official YouTube channel (https://youtu.be/-NuExe4NfpQ), but that always results in errors. 

### Expected behavior
I am trying to update the title, content, and other data on the Strapi database, but I always receive an error message. It would be helpful if there were a document that I could refer to in order to solve this problem.

![image](https://user-images.githubusercontent.com/104133044/188875177-0eff0d9a-c243-43b3-9651-9e9fa08ccd93.png)
![image](https://user-images.githubusercontent.com/104133044/188877977-a73678b8-637f-42bc-ad78-60d9b3979582.png)

### Code snippets

![image](https://user-images.githubusercontent.com/104133044/188878211-d6feec65-3ba5-425e-810e-c2f15975caac.png)

**Comment by kasonde** [comment]
Hi @Chanaka-Sandaruwan I'm closing this as it's not an issue but a question. Please feel free to reach out to our Community through either our [Discord](https://discord.strapi.io) server or our [Community Forum](https://forum.strapi.io)
