### ISSUE TITLE
"Fill in from another locale" don't copy Number field

### ISSUE THREAD

**Issue by davefv** [strapi/strapi#14336]
### Required System information

- Node.js version: 14.19.1
- NPM version: 8.6.0
- Strapi version:4.3.6
- Database: mysql
- Operating system: Ubuntu 20.04

### Describe the bug

After create a new translation of a collection type I click on "Fill in from another locale" button, but a Nuber field don't fill successfully

### Steps to reproduce the behavior

1. Go to Settings > Internationalization > Add new locales > Catalan
2. Set English as default language
3. Content Type Builder > Create new collection type > Test
4. Advanced settings > Check Enable localization for this Content-Type
5. Create field Text > Name: Name
6. Create field Number > Name: Year, Number format: integer
7. Save
8. Content Manager > Test > Create new entry: Name: Test 1, Year 2022
9. Save
10. On locales dropdown, change to another locale (ex: Catalan)
11. Click on Fill in from another locale
12. On popup select English and click Yes
13. Then Name field is filled but Year field is empty
14. After click inside Year field, the field value is NaN

### Expected behavior

Year field has filled with English value (2022)

### Screenshots

![image](https://user-images.githubusercontent.com/34725063/188861580-e02208ad-e838-4a3d-a141-a927837b7b1e.png)

**Comment by kasonde** [comment]
Hi @davefv I've been able to confirm this and the issue you created about relations here #14337, I'm going to go ahead and close this and set is as related to that. These issues are seemingly related and we can have a discussion around the same in one issue. Thanks again for the report :)
