### ISSUE TITLE
"Fill in from another locale" don't copy Relation field

### ISSUE THREAD

**Issue by davefv** [strapi/strapi#14337]
### Required System information

- Node.js version: 14.19.1
- NPM version: 8.6.0
- Strapi version:4.3.6
- Database: mysql
- Operating system: Ubuntu 20.04

### Describe the bug

After create a new translation of a collection type I click on "Fill in from another locale" button, but a Relation field don't fill successfully

### Steps to reproduce the behavior

1. Go to Settings > Internationalization > Add new locales > Catalan
2. Set English as default language
3. Content Type Builder > Create new collection type > Test
4. Advanced settings > Check Enable localization for this Content-Type
5. Create field Text > Name: Name
7. Save
8. Content Type Builder > Create new collection type > Example
9. Advanced settings > Uncheck Enable localization for this Content-Type
10. Create field Text > Name: Name
11. Content Manager > Example > Create new entry: Name: Example 1
12. Save
13. Content Manager > Test > Create new entry: Name: Test 1, example: Example 1
14. Save
15. On locales dropdown, change to another locale (ex: Catalan)
16. Click on Fill in from another locale
17. On popup select English and click Yes
18. Then Name field is filled but Relation field is empty

### Expected behavior

Relation field has filled with English value (Example 1)

### Screenshots

![image](https://user-images.githubusercontent.com/34725063/188865225-2e2df032-d55f-4137-8115-30f49c76dc1c.png)

**Comment by soupette** [comment]
If I remember correctly this is an intended behavior when copying from another locale, we don't copy relations and password fields.

**Comment by gu-stav** [comment]
I'll close this issue for now as it is intended. It is not possible to share relations across multiple locales at the moment. However: we are going to refactor the data model quite a lot this quarter, which will make that possible. We are aware of the importance of this, but for now, this is not an issue but a feature request which is better suited for https://feedback.strapi.io/

**Comment by adriaanvanrossum** [comment]
Created this video to show what was happening here. Relations are dropped between locale switches:

https://user-images.githubusercontent.com/1079135/206030059-f3e8d80e-cd8d-446a-ad8c-9c165a9cbe57.mp4

But it seems like it's not supported at the moment. Good to know!

**Comment by vibonacci** [comment]
Is this really intended behavior, or is actually supporting it too hard / complex given the chosen data structure for localization early on? 😛

This is a huge limitation, especially for a project that is aimed at content management.

If you have a product with product tags, and let's say 4 languages, you'd have to add the tags for each 4 languages, while the tags for each locale are the same tag base record!

**Comment by KasperiP** [comment]
Curious about the situation with this issue. Has anyone found any workarounds? For our use case, this is a major deal breaker, and we will probably need to consider using something else if it is not fixable.

**Comment by rehantoday** [comment]
It's funny when devs mark bug as feature ;))

What is logical here is that it if translated version of locale is available, then it should automatically fetch it.

**Comment by kristiczk** [comment]
2024, any updates?

**Comment by fmlukaszmatusik** [comment]
Same here, but it seems it works kinda properly in v5...

**Comment by kennethzuniga** [comment]
This was a huge disappointment for us in v4. We had a tags relation field used for thousands of articles, we wanted to translate these tags into multiple languages, to our surprise all relations were lost in the locale versions. Can someone please confirm if this was fixes in v5? Thank you

**Comment by imdj** [comment]
> We had a tags relation field used for thousands of articles, we wanted to translate these tags into multiple languages, to our surprise all relations were lost in the locale versions. 
> Can someone please confirm if this was fixes in v5? Thank you

Nope, it's still broken in v5. It's indeed very frustrating. I'm currently on the latest version v5.9.0. 

The following recent issue might help:
- #21322

**Comment by sylvainGarnot** [comment]
> This was a huge disappointment for us in v4. We had a tags relation field used for thousands of articles, we wanted to translate these tags into multiple languages, to our surprise all relations were lost in the locale versions. Can someone please confirm if this was fixes in v5? Thank you

Sadly still the same in v5.15

**Comment by sq-tupai** [comment]
This is really ugly design, I don't know why this is intended, I facing new issue but related to same thing that is when I add new translation to a record, the relationships is not pre-filled for me, in my opinion, the relationship should be locked while adding new translation, it shouldn't be changed. This bullshit waste me a lot of time, I had looking for another solution to ensure the data structure consistence before output to frondend. It's v5.30.0.

**Comment by lmartincek** [comment]
still no usable fix?

**Comment by Annoiiyed** [comment]
This is, single-handedly, a reason for me not to use Strapi ever again.

**Comment by erkintuere** [comment]
So Strapi supports localization, but only if editors enjoy rebuilding the same relationships for every language.
Every additional locale multiplies manual work so that’s not content management or feature, it’s a design flaw.

Thats why this cms can not be more than blog 101 app.

**Comment by jamalsoueidan** [comment]
Just found out this,,, its easy for me to maintain the relationship, since i Use the api, but for people doing this manually... GOOD LUCK AND ENJOY your life 🗡️

**Comment by Adzouz** [comment]
Hey there, it was tough and long but relations are finally preserved in the Fill from another locale feature and will be part of the next release on Wednesday April 15th 🚀
I know that this one was really requested and we really value your feedback, it's just that it wasn't easy to resolve. I really hope that it will reduce frustration on your side 🙏
