### ISSUE TITLE
EntityId field returns incorrect data in localised versions of the Entity

### ISSUE THREAD

**Issue by ghost** [strapi/strapi#14348]
### Required System information

    Node.js version: 16.17.0
    NPM version: 8.15.0
    Strapi version: 4.3.8
    Database: SQLite
    Operating system: Windows 10

### Describe the bug

In a CollectionType called Test with localization enabled, adding a field called TestId returns the id of the parent Test instead of the TestId in objects contained in the localizations data array.

### Steps to reproduce the behavior

1. Create a CollectionType called Test with localization enabled.
2.  Give it a text field called TestId with localization enabled on the field.
3. Create a sample Test in the default locale entering some text in the TestId field.
4. Create a sample Test in a second Locale entering some text in the TestId field.
5. Using Postman, send a get request to /api/tests?populate=*
6. Observe that in data>attributes>localizations>data>attributes>TestId, observe that the returned value is not what was entered in the field (and is stored in the db), it is instead the id of the Test in the default Locale.

### Expected behavior

The value returned should be as it is in the database.

### Screenshots

![image](https://user-images.githubusercontent.com/102500914/189017467-b4bf87a3-5150-4ff7-afb6-83ff60f5f14c.png)
![image](https://user-images.githubusercontent.com/102500914/189017544-e11004c4-5b04-48d0-86ef-2475454803b0.png)
![image](https://user-images.githubusercontent.com/102500914/189017667-7f4a92c3-c580-4e5f-b0d1-f9e319140869.png)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by alexandrebodin** [comment]
I verified this issue again and it is fixed at least since Strapi v4.11.4. Thanks
