### ISSUE TITLE
Strapi intermittently restarts 

### ISSUE THREAD

**Issue by zalmane** [strapi/strapi#1434]
**Informations**
- **Node.js version**:
9.5.0
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.2
- **Database**:
postgresql
- **Operating system**:
WSL (Ubuntu Linux on windows)

**What is the current behavior?**
Strapi intermittently restarts (in dev mode with autoreload). Shows a message as if a file has changed when no file has changed.
1|str | [2018-06-20T11:12:12.477Z] info File changed: /mnt/c/Users/abcd/projects/api/plugins/settings-manager/admin/build/ddee87a8c4cdbc2a60b5d4ddc3a1549a.svg
1|str | [2018-06-20T11:12:12.478Z] info The server is restarting

**Steps to reproduce the problem**
I suspect this has to do with WSL and the way the hotreload detects changes?

**What is the expected behavior?**
Should not reload unless a file has changed

**Suggested solutions**

**Comment by zalmane** [comment]
Just tried with 12.5. Same issue.

**Comment by derrickmehaffy** [comment]
@zalmane can you upload your project to GitHub and link it (if there is nothing secret or personal in it)

**Comment by lauriejim** [comment]
@zalmane Can you try to update watched file liste [here](https://github.com/strapi/strapi/blob/master/packages/strapi/bin/strapi-start.js#L71) and add `admin` folder.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
