### ISSUE TITLE
Missing collection entries from API Call

### ISSUE THREAD

**Issue by fxmb** [strapi/strapi#14361]
Hi everyone 👋,
we are since recently facing an absurd problem: 

We make a call to a collection and call all elements like so:` /api/providers/?populate=deep`. Basically, we want to fetch ALL entries for `providers`.  This worked perfectly fine, however, since recently Strapi is not returning all entries, sometimes one is missing, sometimes a couple, then some hours later everything works again. The missing entries vary (presumably) randomly... 

I cannot give a better description as the problem is so weird and irreproducible. We have around 40-45 different entries, hence the call should return 40-45 entries. 
Could this be a pagination issue? We are pretty clueless. Thanks for any help! 

(It used to work just fine, no, we didnt make any changes)

I know this is not a super helpful description, but the problem is neither deterministic nor reproducible. 

Stack with NextJS hosted on DO:
    "@strapi/plugin-i18n": "4.3.2",
    "@strapi/plugin-seo": "^1.7.2",
    "@strapi/plugin-users-permissions": "4.3.2",
    "@strapi/strapi": "4.3.2",

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
