### ISSUE TITLE
Strange behavior when have multiple component with unique field inside

### ISSUE THREAD

**Issue by Jan080906** [strapi/strapi#14365]
### Required System information

- Node.js version: v16.17.0
- NPM version: 8.15.0
- Strapi version: 4.3.2
- Database: sqlite
- Operating system: Window

### Describe the bug

I suspect some strange behaviors when have multiple component with unique field inside.

### Steps to reproduce the behavior 1

1. Create repeatable component name **"CompA"** and add unique text field name **"ComAOption"**
2. Create repeatable component name **"CompB"** and add unique text field name **"ComBOption"**
![image](https://user-images.githubusercontent.com/47817662/189299256-43d156c7-b311-43c2-ac15-445c842d72ae.png)
3. Add **"1"** to **"ComAOption"**  and **"1"** to **"ComBOption"**
4. Click on Save 
5. Add **"2"** to **"ComAOption"** and **"2"** to **"ComBOption"**
6. See error **"ComAOption must be unique"** and **"ComBOption must be unique"**
![image](https://user-images.githubusercontent.com/47817662/189302670-d3b1238a-1c3d-48bc-91e3-a89ea42de40a.png)

### Expected behavior
Should be able to save

### Steps to reproduce the behavior 2

1. Continue from step the above step
2. Add new entry then add **"1"** to **"ComAOption"** 
3. See error **"ComAOption must be unique"** 
![image](https://user-images.githubusercontent.com/47817662/189303572-564a737e-7d23-4ea5-8a86-00fcb75311af.png)

### Expected behavior
Should be able to save since the uniqueness should be within its own components and it own entry

**Comment by kasonde** [comment]
Hi, I'm closing this as it's related to #12541
