### ISSUE TITLE
Is there a better way to render dark mode logo?

### ISSUE THREAD

**Issue by tjuandev** [strapi/strapi#14364]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.8.0
- Strapi version: 4.3.6
- Database: Postgres
- Operating system: Ubuntu LTS

### Describe the bug

I'm trying to render a logo based on dark and light mode, when it's dark, the logo is white and so on... I'm currently using Local Storage to do that, but the STRAPI_THEME variable is "null" or non existent sometimes, unless you go to profile and set a theme (by Default is OS Based).

### Steps to reproduce the behavior

1. yarn strapi develop --watch-admin
2. go to localhost:8000/admin
3. Check LocalStorage

### Expected behavior

The STRAPI_THEME cache variable should have a default value (following OS preferences or being "dark" by default) instead of being "null" or sometimes even not appear.

### Code snippets

```js
import menuLogo from "./extensions/menu.svg";
import authLogoWhite from "./extensions/authLogoWhite.svg";
import authLogoBlack from "./extensions/authLogoBlack.svg";

const THEME = localStorage.getItem("STRAPI_THEME");
const isDarkTheme = THEME !== "light";

export default {
  config: {
    auth: {
      logo: isDarkTheme ? authLogoWhite : authLogoBlack,
    },
    menu: {
      logo: menuLogo,
    },
  },
  bootstrap(app) {
    console.log(app);
  },
};
```

**Comment by ronronscelestes** [comment]
hi @tjuandev thank you for taking the time to share this issue and this interesting use case! 🙂
