### ISSUE TITLE
Strapi Graphql plugin

### ISSUE THREAD

**Issue by JejomStark** [strapi/strapi#14378]
### Required System information

- Node.js version:  16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.4
- Database: PostgreSql
- Operating system: Linux

### Describe the bug
I encounter large latencies with the Graphql plugin. To be more precise, I made a simple benchmark with the same processor and the same RAM (1cpu/1g Ram), with the same data.
The result is telling compared to the Rest API (See image below)

![unknown](https://user-images.githubusercontent.com/97748574/189585675-7eef9b65-5ad8-4e93-8527-4785e033ca8d.png)

### Steps to reproduce the behavior

1. Create a dataset of data with 3 levels deep (Level 1 => 30 rows, other levels are just 1=1 joins
2. Request with Grapql and Rest API

### Expected behavior

A better performance with graphql

**Comment by derrickmehaffy** [comment]
Can you add in a bit more information about the model structure?

Also was your database also hosted on the same machine?

**Comment by JejomStark** [comment]
I've a simple structure with 3 levels,

A category->book->author for example. If I want the author data from the category, there are latencies.

Database is a Postgresql on Google Cloud, no lantecy with it

**Comment by derrickmehaffy** [comment]
Were you also running this test in google cloud or locally? Was the testing script used locally or triggered within the google cloud network (there is always latency, just depends on how much).

**Comment by JejomStark** [comment]
this test was performed on the same server, so it is not an underlying infrastructure issue as the Rest API responds correctly for the same dataset

**Comment by derrickmehaffy** [comment]
So the Strapi application and the PG database was on the same virtual machine in Google Cloud (just want to understand the environment this was running in, as that is quite important)
