### ISSUE TITLE
Cannot create new controllers using the createCoreController function

### ISSUE THREAD

**Issue by darkmavis1980** [strapi/strapi#14375]
### Required System information

- Node.js version: 16.17
- NPM version: 8.15.0
- Strapi version: 4.3.8
- Database: MariaDB
- Operating system: Windows 10

### Describe the bug

I'm trying to create a new controller with custom routes to handle some custom endpoints I want to serve via Strapi, and while if I just export a simple object in the controller, it works fine, if I try to use the `createCoreController` function it will just throw an error.
For example, if I want to create my `/hello` endpoint, the following will work:

```javascript
// src/api/hello/controllers/hello.js
module.exports = {
  sayHello: async(ctx) => {
    ctx.body = 'hello';
  }
};

//src/api/hello/routes/hello.js
module.exports = {
  routes: [
    {
     method: 'GET',
     path: '/hello',
     handler: 'hello.sayHello',
    },
  ],
};

```

But in my case I need to access to strapi services, so I was following [this example from the documentation](https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#implementation), and using the `createCoreController` function changing my code to this:

```javascript
// src/api/hello/controllers/hello.js

const { createCoreController } = require('@strapi/strapi').factories;

module.exports = createCoreController('api::hello.hello', ({ strapi }) =>  ({
  sayHello: async(ctx) => {
    ctx.body = 'hello';
  }
}));
```

The code above will throw an error once I start to run the application with `npm run build && npm run develop`:

```bash
[2022-09-10 22:42:37.360] debug: ⛔️ Server wasn't able to start properly.
[2022-09-10 22:42:37.362] error: Error creating endpoint GET /hello: Cannot read properties of undefined (reading 'kind')
TypeError: Error creating endpoint GET /hello: Cannot read properties of undefined (reading 'kind')
    at Object.isSingleType (/home/user/Code/my-project/node_modules/@strapi/strapi/node_modules/@strapi/utils/lib/content-types.js:90:25)
    at createController (/home/user/Code/my-project/node_modules/@strapi/strapi/lib/core-api/controller/index.js:36:20)
    at /home/user/Code/my-project/node_modules/@strapi/strapi/lib/factories.js:11:28
    at Object.get (/home/user/Code/my-project/node_modules/@strapi/strapi/lib/core/registries/controllers.js:37:61)
    at Strapi.controller (/home/user/Code/my-project/node_modules/@strapi/strapi/lib/Strapi.js:136:46)
    at getController (/home/user/Code/my-project/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:101:19)
    at getAction (/home/user/Code/my-project/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:128:22)
    at /home/user/Code/my-project/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:71:22
    at createRoute (/home/user/Code/my-project/node_modules/@strapi/strapi/lib/services/server/routing.js:79:
```

### Steps to reproduce the behavior

1. Create a new API route with controller
2. See error

### Expected behavior

The controller should work and has access to the `strapi` instance.

**Comment by darkmavis1980** [comment]
So after a some tries, I figured out that I had to create a content-types, with no attributes as I don't need to store any data for those endpoints, but essentially I had to add the following file:

```json
// src/api/hello/content-types/hello/schema.json
{
  "kind": "singleType",
  "collectionName": "hello",
  "info": {
    "singularName": "hello",
    "pluralName": "hellos",
    "displayName": "Hello"
  },
  "pluginOptions": {},
  "attributes": {}
}
```

Once this is created, Strapi will start normally, but maybe this should be stated in the documentation, or if it's stated somewhere (I couldn't find any reference about it), it should be made more clear that you need to create the content-types.

**Comment by derrickmehaffy** [comment]
Core controllers only exist for content types, you can still create custom controllers using the alternative syntax.

Anyway, closing as this isn't a bug.

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
