### ISSUE TITLE
How i delete username field in users

### ISSUE THREAD

**Issue by xbeakmanx** [strapi/strapi#14374]
I already modified the schema.json in src/extensions/users-permissions/content-types/user and it doesn't work for me, the field username don't show anymore but when I create a new user in strapi show me a warning: username is a required field

I also tried set username in attributes required: false, unique: false and still don't work

### Required System information

- Node.js version:v16.13.0
- NPM version:8.1.0
- Strapi version:v4.3.8
- Database:postgres
- Operating system:macos

### Describe the bug

Username field in users keep showing as required when I already deleted

### Steps to reproduce the behavior

1. Go to users
2. Click on create new entry
3. Click on the save button

### Screenshots

<img width="953" alt="image" src="https://user-images.githubusercontent.com/60238989/189492883-b78b8742-ea68-44ac-963b-162139ce7cf1.png">

**Comment by xbeakmanx** [comment]
My schema: 

{
  "kind": "collectionType",
  "collectionName": "up_users",
  "info": {
    "name": "user",
    "description": "",
    "singularName": "user",
    "pluralName": "users",
    "displayName": "User"
  },
  "options": {
    "draftAndPublish": false,
    "timestamps": true
  },
  "attributes": {
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmationToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.role",
      "inversedBy": "users",
      "configurable": false
    },
    "profile_view": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "cellphone": {
      "type": "biginteger"
    }
  }
}

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
