### ISSUE TITLE
Cannot create a new user without field "username" after deleted from the schema

### ISSUE THREAD

**Issue by xbeakmanx** [strapi/strapi#14376]
## Bug report

I already modified the schema.json in src/extensions/users-permissions/content-types/user and it doesn't work for me, the field username don't show anymore but when I create a new user in strapi show me a warning: username is a required field

I also tried set username in attributes required: false, unique: false and still don't work

### Required System information

Node.js version:v16.13.0
NPM version:8.1.0
Strapi version:v4.3.8
Database:postgres
Operating system:macos

### Describe the bug

Username field in users keep showing as required when I already deleted

### Screenshots

<img width="953" alt="Captura de Pantalla 2022-09-10 a la(s) 11 33 52 a m" src="https://user-images.githubusercontent.com/60238989/189510876-902f44f7-208c-4d02-8605-0f79e7fd5993.png">

**Comment by xbeakmanx** [comment]
My schema:

{
"kind": "collectionType",
"collectionName": "up_users",
"info": {
"name": "user",
"description": "",
"singularName": "user",
"pluralName": "users",
"displayName": "User"
},
"options": {
"draftAndPublish": false,
"timestamps": true
},
"attributes": {
"email": {
"type": "email",
"minLength": 6,
"configurable": false,
"required": true
},
"provider": {
"type": "string",
"configurable": false
},
"password": {
"type": "password",
"minLength": 6,
"configurable": false,
"private": true
},
"resetPasswordToken": {
"type": "string",
"configurable": false,
"private": true
},
"confirmationToken": {
"type": "string",
"configurable": false,
"private": true
},
"confirmed": {
"type": "boolean",
"default": false,
"configurable": false
},
"blocked": {
"type": "boolean",
"default": false,
"configurable": false
},
"role": {
"type": "relation",
"relation": "manyToOne",
"target": "plugin::users-permissions.role",
"inversedBy": "users",
"configurable": false
},
"profile_view": {
"type": "media",
"multiple": false,
"required": false,
"allowedTypes": [
"images"
]
},
"cellphone": {
"type": "biginteger"
}
}
}

**Comment by 3webbg** [comment]
@xbeakmanx 
username  is common field, it will be easier for you to create users with **username** - **email address**

user: jon@gmail.com
email: jon@gmail.com

**Comment by derrickmehaffy** [comment]
I can confirm with @3webbg here, the U&P is specifically coded and expects the username field to exist. Closing as this isn't a bug but a custom modification.

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
