### ISSUE TITLE
Bulk delete from admin interface isn't working

### ISSUE THREAD

**Issue by ErhanAbi** [strapi/strapi#14384]
### Required System information

- Node.js version: v18
- NPM version: 8.8.0
- Strapi version: 4.3.8
- Database: mysql
- Operating system: macOS

### Describe the bug

I have an entity type that has multiple components associated with. Not all instances of those entity types have the components data filled, ie. we can have some of those components set as null.

For example, we have `estates` (which represent real estate properties). Those `estates` can have either `apartmentDetails` / `houseDetails` / `terrainDetails` as separate components. But it doesn't make sense to have all the components filled and thus each estate can have only one of those components filled based on the estate type.

Component mapping based on estate type
- `apartment` type -> `apartmentDetails`
- `house` type -> `houseDetails`
- `terrain` type -> `terrainDetails`

Now, when I try to bulkDelete from admin one or more estates, I get an internal server error.

After some investigation, I found out that the problem is triggered by the `deleteComponents` method from `strapi/lib/services/entity-service/components.js#deleteComponents`. The error is thrown by the following code

```js
      // Load attribute value if it's not already loaded
      const value =
        entityToDelete[attributeName] ||
        (await strapi.query(uid).load(entityToDelete, attributeName));
```

This happens because the `entityToDelete` variable there is an object that contains only the properties associated with the components of the model. So for an estate with `id=100`, the `entityToDelete` will be an object like 

```
{
  apartmentDetails: null,
  houseDetails: null,
  terrainDetails: {
    id: 38,
    surface: 2180,
    streetOpeningSize: 10,
    classification: 'build_up_area',
    // ...etc
  }
}
```

So when `entityToDelete[attributeName] === null` it tries to load it but the problem is that it doesn't have the id of the original entity that's being deleted. Which in this case would be the `estate(id=100)`. It's just a plain object that contains only the properties of the components associated with the original entity type.

### Steps to reproduce the behavior

Once you have a more complex entity type that has multiple components which can be null,

1. Go to `admin ui / content-manager / entity`
2. Check a few items from the list (One is enough to repro the problem)
3. Click on delete button

### Expected behavior

The expected behavior is to have the selected entities and their associated components deleted. The current behavior is that the entities are deleted, BUT the associated components aren't deleted. Also, the webhook isn't triggered because an error occurs during the deletion of the components.

**Comment by ErhanAbi** [comment]
Hi, any updates on this one?

**Comment by Marc-Roig** [comment]
Hi @ErhanAbi .
That was an amazing issue description. It provided all (and more) necessary information to fix the problem!

I have created a PR that addresses this :) We will try to merge it asap.

Thank you.

**Comment by kgaurav-ts** [comment]
Which version has got this fix?
