### ISSUE TITLE
[feature request] List View Context data getter for plugins

### ISSUE THREAD

**Issue by Prozi** [strapi/strapi#14388]
Hello, I've created a custom strapi plugin

1. and it's working if I insert it into edit view with `app.injectContentManagerComponent('editView', 'right-links', { ... })` and `useCMEditViewDataManager()` for getting the context data

2. but now after moving it to list view with `app.injectContentManagerComponent('listView', 'actions', { ... })`
I can't get the data using `useCMEditViewDataManager()` (obviously returning falsy value since not in EditView now)

_how can I get similar data like readActionAllowedFields, slug, layout from a plugin in listView ???_

**expected behaviour:**
plugin in listView has access to at least some context thanks to similar function to `useCMEditViewDataManager()` for lists
I'm not even requesting full context data as in the edit view. but I'd love to have access to at least
- slug
- layout.kind (to check is it collectionType for my plugin)
- attributes (I was using readActionAllowedFields so this would be good)

thank you

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
