### ISSUE TITLE
Local Strapi can't be started from folder different from project root

### ISSUE THREAD

**Issue by dj-hedgehog** [strapi/strapi#144]
**Node.js version**: 6.4
**npm version**: 3.10.3
**Strapi version**: All
**Operating system**: All

I've got a `test` folder which is setting up the test-environment for integration tests. I'm calling `strapi.start()` from within `test/test.js` but that doesn't work because since `appPath` is always considered to be the current working directory.

Will you accept a PR for this or do you have any idea of how to solve this problem differently?

**Comment by Aurelsicoko** [comment]
Did you try to add an `appPath` key in your configuration's files? Because the default path is `process.cwd()` if no path has been defined [(more details)](https://github.com/strapi/strapi/blob/v2/packages/strapi/lib/configuration/load.js#L68).

**Comment by dj-hedgehog** [comment]
The configuration files are only `.json` so how would I add it?

**Comment by domantasjurkus** [comment]
Wanted to reopen this issue for v3. The suggestion above works for v2, however  the file structure has changed, not sure where to change the `appPath`.
