### ISSUE TITLE
Unable to create first user

### ISSUE THREAD

**Issue by Tryptich** [strapi/strapi#1440]
After the installation of the CMS, i can't create the first user according to tutorial.
i have install all the plugin but i can't apply the tutorial.

strapi version : 3.0.0-alpha.12.4
node version: v8.11.3
Win 10

**Comment by henrych4** [comment]
As mentioned [here](https://strapi.io/getting-started), requirements for strapi are

- node (at least v9.0.0)
- npm (at least v5.0.0)
- mongoDB (at least v3.4)

Perhaps you can try update node version and see whether it works

**Comment by derrickmehaffy** [comment]
@Tryptich Please follow the bug template, issues that don't follow it will be closed.

Also as @henrych4 has said, 
Node >=9
NPM >= 5
MongoDB >= 3.4 OR MySQL >= 5.6
Also I don't recommend Windows as support is hit or miss on it, Either use the WSL (Ubuntu) or a Linux VM.

**Comment by lauriejim** [comment]
Hello @Tryptich , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
