### ISSUE TITLE
Strapi timezone sqlite utc updatedAt field not in local timezone

### ISSUE THREAD

**Issue by ALWISHARIFF** [strapi/strapi#14409]
Dear Strapi Team,
I am using The following specification of softwares.

    Node.js version: v16.17.0
    NPM version: v8.15.0
    Strapi version: 4.3.8
    Database: SQLite
    Operating system: Windows 10
I created my content schema using the content manager i now have a public route to fetch resources from the server.
The createdAt field that is automatically added by strapi is according to **UTC timezone format** I tried changing the `database.js file` in the _**config folder**_ added` timezone:"Africa/Nairobi" `to` connection.connection` object `as per the docs `but if **fails to record time with the current timezone** even after **adding various posts and publishing them**

_Originally posted by @ALWISHARIFF in https://github.com/strapi/strapi/issues/11509#issuecomment-1245564144_

**Comment by derrickmehaffy** [comment]
SQLite requires you to manually set the value if you want to use timezones of which is not currently possible in Strapi.

This instead should have a call out in the documentation that it's not positive set timezones on SQLite3 (it's also generally advised against to change the database timezone as conversions should happen on the client side)

Please open an issue or a pull request on our documentation repo: https://GitHub.com/Strapi/documentation to add this warning.

Closing bug report as won't fix
