### ISSUE TITLE
Strapi Component Media field Maps to Wrong Relations.

### ISSUE THREAD

**Issue by SudeepPatel-0812** [strapi/strapi#14419]
### Required System information

- Node.js version: v14.20.0
- NPM version: v6.14.17
- Strapi version: v4.1.8
- Database: PostgreSQL
- Operating system: Ubuntu 20.04 (Strapi runs in docker)

### Describe the bug

I have a component with details attached to collection. That collection contains media as a field, now if I post only 2 component with/without image it works as expected but if I post more than 2 components following things happen:

-  If I add the image id for the component, it may (sometimes) get replaced with some random image. If I don't upload an image then for any of the component there will be random image mapped.
- If I post more than 3 images & image is attached sometimes it would map random image or sometimes it maps correct image i.e inconsistent mapping/relations are being made here.
- Even if I pass null to the media field it still maps the relation.

### Steps to reproduce the behavior

1. Make a collection & attach a component to it with media field.
2. Goto Postman and post a payload & fill in media field with image id for 2 components & check the Strapi collection (GUI). You will get the same response that you posted.
3. Now do the same as point 2 & post 3-4 components with/without images.
4. See the error.

### Expected behavior

Expected behavior should be to map the component relations correctly.

### Screenshots
![Payload](https://user-images.githubusercontent.com/93346617/190124542-d22df6eb-e3c6-4c72-8378-eda796f7d7d2.png)

I haven't attached the image still one image got uploaded.
![Upload 1 Strapi](https://user-images.githubusercontent.com/93346617/190123936-ffa8108e-421f-4d78-b78b-6989abd155bc.png)

**Also I provided the same image id for component 1 & 4. So for component 1 I have the expected image but for component 4 it's a random image that resides in my media library**

### Code snippets

I haven't made any changes to the core controller.

**Comment by derrickmehaffy** [comment]
Chatted with this user on Discord and tested it live with them both on v4.1.8 and v4.4.3 and could not reproduce the issue. They mentioned the issue seems to have disappeared on their side as well.

![image](https://user-images.githubusercontent.com/8593673/195678189-0417eb56-ef6f-45ca-9872-a25aefd6e8b3.png)

Marking issue as closed unless someone can provide additional steps to reproduce this in a fresh project.
