### ISSUE TITLE
"invalid geometry" error when inserting "geometry" type data to PostgreSQL

### ISSUE THREAD

**Issue by emrahaydemir** [strapi/strapi#14412]
Hello, I am using PostgreSQL as database. Everything works smoothly. I want to take advantage of the "geometry" data type that PostgreSQL provides built-in. 

Coordinate information sent from the front-end should be converted to PostgreSQL geometry data type and saved. But when inserting data I get the following error: (from strapi): 

`error: insert into "public"."deeds" ("geometry", "published_at", "updated_at") values ($1, $2, $3) returning "id" - parse error - invalid geometry`

I spent several hours trying to solve this problem. Then, to understand the root of the problem, I manually added the geometry data from strapi to PostgreSQL. This works flawlessly. I guess Strapi can't add geometry data type.

At first I thought it was due to a plugin. But later I realized that this is a general problem. Here I explained the problem in more detail: [https://github.com/am2222/strapi-plugin-postgis/issues/1#issuecomment-1245911964](https://github.com/am2222/strapi-plugin-postgis/issues/1#issuecomment-1245911964)

**Comment by emrahaydemir** [comment]
I check via PostgreSQL whether the geojson data I sent with Postman is valid. PostgreSQL confirms this.

![image](https://user-images.githubusercontent.com/35865864/190009748-533d367c-ff55-42d2-8b44-7608b5fbcd1d.png)

![image](https://user-images.githubusercontent.com/35865864/190010260-f4efe783-7d4e-47c6-827a-9eb1358ffb21.png)

**Comment by am2222** [comment]
@emrahaydemir can you wrap your query around `ST_MakeValid` ? 
https://postgis.net/docs/ST_MakeValid.html

If this works I will update the plugin too. This is not related to the strapi and it is related to the postgis!

**Comment by emrahaydemir** [comment]
i just trid `ST_MakeValid` but didnt work. 

I wanted to simplify the problem a little more. First, I sent the same GeoJSON data to PostgreSQL as a query. Added this successfully and I can see the polygon. Then I changed the data type of the "geometry" column to "text" to see the data coming from Strapi to PostgreSQL. So Strapi was able to add the content successfully. When I compared the two data, I noticed that the geometry code of the polygon I added manually did not have quotes, but the geometry code sent from Strapi had **double quotes** at the beginning and end. Could this be the problem?

GeoJSON manually add by query to PostgreSQL. **Result**: `0103000020110F0000010000000500000000000000C0CE56C010E18C8FE5BA46400000000080F353C09B4F4F0243EB484000000000404551C095C70D3FF9B9454000000000800F56C0C0094D5EF158404000000000C0CE56C010E18C8FE5BA4640`

GeoJSON added by Strapi to PostgreSQL. **Result**: `"0103000020110F0000010000000500000000000000C0CE56C010E18C8FE5BA46400000000080F353C09B4F4F0243EB484000000000404551C095C70D3FF9B9454000000000800F56C0C0094D5EF158404000000000C0CE56C010E18C8FE5BA4640"`

**Comment by emrahaydemir** [comment]
Also, when I check before sending the geometry data, I don't see double quotes

![image](https://user-images.githubusercontent.com/35865864/190073915-f9b79f90-7780-4b0b-872f-9dbc0056f2ff.png)

**Comment by emrahaydemir** [comment]
Also, when I check before sending the geometry data, I don't see double quotes.

![image](https://user-images.githubusercontent.com/35865864/190074243-beb397d8-1c17-4517-9f43-cf235b1e4eb1.png)

**Comment by emrahaydemir** [comment]
I think I solved the problem. First I create a data of type "string". After Strapi saves it to the schema, I force the data type of the table to be changed to geometry via POSTGRESQL. I don't know how healthy this is. But now it works fine

`alter table deeds alter column geometry type geometry using geometry::geometry`


strapi schema.json `"geometry": {
      "type": "string",
      "required": true
    }`
