### ISSUE TITLE
Error "relation already exists" when I try to run develop on centos7 with PostgreSQL

### ISSUE THREAD

**Issue by giang3010** [strapi/strapi#14416]
### Required System information

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version: 4.2.0
- Database: postgres 14
- Operating system: windows

### Describe the bug

Catch when I try to run my project from local to centos7

### Screenshots

![image](https://user-images.githubusercontent.com/64892248/190089310-2f95e918-a67f-446c-b47a-4038a71a5a5f.png)

**Comment by Chanvannak52** [comment]
ThonChanvannak
