### ISSUE TITLE
boostrap.js not called totally

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1441]
**Informations**
- **Node.js version**: 9.0.0
- **npm version**: 5.5.1
- **Strapi version**: 3.0.0 alpha 12.5
- **Database**: Mongo
- **Operating system**: Linux

**What is the current behavior?**
I want to add some init data to my app and done same step as https://github.com/strapi/strapi-examples/tree/master/cheesecakes#bootstrap-application-data but it's not working at all. I search and find that boostrap.js not called totally.
I try to change my `bootstrap.js` file like below but it seems `bootstrap.js` not called totally:
```
'use strict';

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */

module.exports = cb => {
  console.log("++++++++++++++ bootstrap.js called ++++++++++++++");
  cb();
};
```

**Steps to reproduce the problem**
change `bootstrap.js` like above.

**What is the expected behavior?**
print log message.

**Suggested solutions**
--

**Comment by lauriejim** [comment]
I ran `strapi new myProject` and update `bootstrap.js`file with a log and it works well.

**Comment by mnlbox** [comment]
@lauriejim I re create another app and it's working now. I don't now why :thinking:
