### ISSUE TITLE
Two join tables are created for many-to-many relations instead of one

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#14428]
### Required System information

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version: 4.3.8
- Database: SQLite
- Operating system: macOS

### Describe the bug

Two join tables are created for many-to-many relations instead of one.
It is because the created attributes for the relation both have "inversedBy" instead of one having "inversedBy" and the other "mappedBy".

### Steps to reproduce the behavior

Follow what is done in this video:

https://user-images.githubusercontent.com/11708220/190352181-196c7b4c-d89d-4ae8-8fc6-4961ee7e1d4e.mov

Notice at the end, if I edit the content-type a second time, then the relation is back to what it is supposed to be + the second join table is deleted.

### Expected behavior

Only one join table should exist + the 2 attributes of the many-to-many relations should have, for on "inverseBy", for the other "mappedBy".

**Comment by majjikishore007** [comment]
hi @derrickmehaffy  can i work on this

**Comment by derrickmehaffy** [comment]
> hi @derrickmehaffy can i work on this

We don't assign issues, and you don't need to ask. You can just submit a PR and add something like `fixes #14428` to the PR comment

**Comment by derrickmehaffy** [comment]
> I reported this in #12652 where it was stated to be preparations for versioning?

It is possible that we may use it for versioning, information on this one is a little fluid at the moment. Sorry for the confusion @pbvahlst
