### ISSUE TITLE
Fresh npm installation prints deprecation warnings

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#14420]
### Required System information

- Node.js version: not applicable
- NPM version: not applicable
- Strapi version: 4.3.8
- Database: not applicable
- Operating system: not applicable

### Describe the bug

A user reported on twitter that while installing Strapi, the package manager (npm) prints a few warnings, which might look scary in the eyes of a user:

```
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

I think we should try and reduce that list as much as possible.

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest`
2. Go into the created project
3. Run `npm install`

### Expected behavior

I'll try to break one these warnings one-by-one:

- ✅  `source-map-url`, `urix`, `resolve-url` can be fixed by upgrading `plop`
- ❓  `har-validator` needs to be replaced by something else or inlined
- ❌  `mailcomposer`, `buildmail` the problem comes from the `sendmail` package, which didn't have an update
- ✅ `formidable` could be fixed by upgrading `koa-body`
- ❌ `querystring` nothing we can do for now, because `node-polyfill-webpack-plugin` did not have a new release
- ❌ `uuid` nothing we can do, since it comes from `koa-session` (no new release) and `request` (the latter is not maintained anymore)
- ❓ `request` is required by the users-permissions plugin and would need be refactored

### Additional context

- https://twitter.com/peteralexbizjak/status/1569749067919507457

**Comment by alexandrebodin** [comment]
I'm going to go ahead and close this as we will always have some warnings that we address as we go. Mostly likely those specific ones are not present since then.

**Comment by gu-stav** [comment]
👋🏼 @alexandrebodin 

> I'm going to go ahead and close this as we will always have some warnings that we address as we go. Mostly likely those specific ones are not present anymore.

I agree with what you said - we will always have to face some of these warnings.

Imo this issue highlights a problem with our dependencies (e.g. some dependencies in the area of email are unmaintained and out-of-date), and therefore I think we should either keep this issue open or open more specific ones with the problematic dependencies. Otherwise, I fear that we/ the responsible team do not have enough incentive to start fixing the problem and update/ replace these dependencies, which is not as trivial as merging a dependabot update.

What do you think?

**Comment by alexandrebodin** [comment]
That's a good point. We should explore using dependabot and snyk more in that regard as keep issue open as we can see here just endsup having old issues that nobody looks at anyway :/ Opening specific issues sounds like a better manageable system to me indeed

**Comment by joshuaellis** [comment]
We've optimised dependabot recently with groups, but i found renovate to be really nice to work with – https://github.com/renovatebot/renovate it does a lot of automatic batching and manages workflow dependencies too 👀
