### ISSUE TITLE
Axios error in admin portal when using Brave browser

### ISSUE THREAD

**Issue by jhoward1994** [strapi/strapi#14433]
### Required System information

- Node.js version: v16.17.0
- NPM version: v8.15.0
- Strapi version: v4.3.8
- Database: SQL Lite
- Operating system: MacOS 12.5

### Describe the bug

An Axios error when running Strapi locally in Brave browser

### Steps to reproduce the behavior

1. Run `yarn develop` in `/examples/getstarted`
2. Run `yarn develop` in `/packages/core/admin`
3. Set up admin account
4. Navigate to `http://localhost:4000/admin/`

### Expected behavior

No error as seen in other browsers (chrome, firefox)

### Screenshots

<img width="1501" alt="Screenshot 2022-09-15 at 16 23 03" src="https://user-images.githubusercontent.com/48524071/190444044-f7d4bd24-a266-42c0-91d2-36e0db498b89.png">

### Code snippets

https://github.com/strapi/strapi/blob/92955d19f9e33c72de192d7fbb8ddbefd2f0b408/packages/core/admin/admin/src/pages/App/index.js#L94

`appInfo` is undefined

### Additional context

Seemingly caused by Brave ad & tracking prevention

**Comment by Marc-Roig** [comment]
Had the same behaviour with uOrigin adblock using Chrome.

I don't know if this is something we want, but there are services specialized in preventing analytics requests to be blocked, such as [DataUnlocker](https://dataunlocker.com/).
