### ISSUE TITLE
Typescript plugin generation problem

### ISSUE THREAD

**Issue by kepes** [strapi/strapi#14446]
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.1.2
- Strapi version: 4.3.8
- Database: sqlite
- Operating system: osx 12.5

### Describe the bug

When Typescript Plugin generated with `npm run strapi generate` the generated code contains two error in `src/plugins/plugin-name/admin/src/components/Initializer/index.tsx`

1. `Cannot assign to 'current' because it is a read-only property.ts(2540)`
2. `Cannot invoke an object which is possibly 'null'.ts(2721)`

I found this article about the problem but I can't solve it:
https://claritydev.net/blog/typescript-typing-react-useref-hook/

### Steps to reproduce the behavior

1. generate code with `npm run strapi generate`
2. choose 'Plugin'
3. Type plugin name
4. choose 'TypeScript'
5. Wait for code generation
6. Type 'npm run build'
7. check `src/plugins/plugin-name/admin/src/components/Initializer/index.tsx`

### Expected behavior

Code generated without Typescript error.

### Screenshots

<img width="683" alt="Képernyőfotó 2022-09-19 - 18 05 39" src="https://user-images.githubusercontent.com/531009/191062491-e5faeedf-f9b5-41ae-aaf7-c02b20dcbdd8.png">

### Code snippets

```
const Initializer: React.FC<InitializerProps> = ({ setPlugin }) => {
  const ref = useRef<(id: string) => void | null>(null);
  ref.current = setPlugin;

  useEffect(() => {
    ref.current(pluginId);
  }, []);

  return null;
};
```

**Comment by vitormanfredini** [comment]
Here's a temporary solution that I found:
Replace the code in `src/plugins/plugin-name/admin/src/components/Initializer/index.tsx` for the one in this file:
https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/blob/master/admin/src/components/Initializer/index.tsx

Then `cd src/plugins/plugin-name/` and `yarn && yarn build` to build the plugin

Then `cd` back to the project root and `yarn develop`
