### ISSUE TITLE
Introspection queries in GraphQL Playground fail without users-permissions plugin

### ISSUE THREAD

**Issue by tpimh** [strapi/strapi#14441]
### Required System information

- Node.js version: v16.17.0
- yarn version: v1.22.19
- Strapi version: 4.3.8
- Database: sqlite/postres
- Operating system: Alpine Linux edge

### Describe the bug

This is mostly related to GraphQL Playground and has very little to do with Strapi. When opening GraphQL Playground while not having user-permissions plugin installed, the "IntrospectionQuery" requests would fail with 401. Also, a misleading text "Server cannot be reached" is displayed next to the URL (the correct text in this case would be "Authorization required").

Setting Authorization HTTP Header with a token fixes is (this header is also used for the introspection query). However, it's not working on the Settings tab (click gear icon in the top right corner of Playground). I tried adding `request.globalHeaders` with my Authorization token, but it didn't seem to affect anything.

### Steps to reproduce the behavior

```
yarn create strapi-app . --quickstart --ts --no-run
yarn strapi uninstall -d users-permissions
yarn strapi install graphql
yarn develop
```

1. Open GraphQL Playground: http://localhost:1337/graphql
2. See a misleading "Server cannot be reached" error message
3. Set "Authorization" HTTP header a token generated from Strapi Dashboard
4. The error disappears, GraphQL Playground seems to be healthy (might need to refresh the page if polling is disabled)
5. Open Settings (gear icon in the top right corner), more introspection queries without Authorization header are sent for some reason
6. Close Settings to observe that "Server cannot be reached" error is back (goes away after refreshing the page)

### Expected behavior

Opening GraphQL Playground for the first time must not give a misleading error message.

Opening Settings shouldn't produce any introspection queries.

`request.globalHeaders` should be supported.

### Screenshots

![Screenshot 2022-09-18 at 10-16-00 Playground - http __localhost 1337_graphql](https://user-images.githubusercontent.com/1071872/190890465-cf1084d8-bc20-47ce-94da-44cbe5d84c09.png)
Initially, GraphQL Playground leads you to believe there's a connectivity problem

![Screenshot 2022-09-18 at 10-16-31 Playground - http __localhost 1337_graphql](https://user-images.githubusercontent.com/1071872/190890533-992a4ba5-e979-44f7-aaf8-b1ea13959231.png)
Fixed after adding Authorization Header

![Screen Shot 2022-09-18 at 10 17 11](https://user-images.githubusercontent.com/1071872/190890547-f0e42f46-2d3a-4ea8-9569-591115942003.png)
Seems to be broken again after opening and closing Settings (even though introspection polling is enabled and GraphQL requests succeed)

### Additional context

This issue seems to be closely related to #12289. In my opinion, the easiest way to fix it without modifying the Playground is similar to #13838: allow all introspection queries in development environment regardless authentication status.

**Comment by alexandrebodin** [comment]
Hi, Closing as won't fix. Apollo v4 has completley changed playground management et we will rework this entirely in the upcoming v5
