### ISSUE TITLE
Content type folders prevent the server from starting

### ISSUE THREAD

**Issue by cache-your-dreams** [strapi/strapi#14448]
### Required System information

- Node.js version: v14.19.3
- NPM version: 6.14.17
- Strapi version: 4.3.8
- Database: SQLite
- Operating system: MacOS

### Describe the bug

I am unable to launch the server after I have created a content type and reverted the Untracked files created.

### Steps to reproduce the behavior

1. Launch the server from within the **example/getstarted** folder
2. Create a content type
3. Stop the server
4. Using VS Code (or another editor) revert the 4 untracked files
5. Launch the server, again from within the **example/getstarted** folder
6. In the CLI, I have the error `error: Cannot read property 'singularName' of undefined`
![Screenshot 2022-09-20 at 13 04 10](https://user-images.githubusercontent.com/104358430/191241900-e8704c1f-7e46-4bb0-82dd-68ff036b2d00.png)
8. If I removed the folders that were created during the content type creation, the server launches as expected.

### Expected behavior

Either the error message should stipulate that the folders need to be removed, the folders are removed automatically or the empty folders don't stop the launching of the server.

**Comment by alexandrebodin** [comment]
Closing this as outdated :)
