### ISSUE TITLE
Missing JWT_SECRET when creating Strapi project with Custom option

### ISSUE THREAD

**Issue by minhdao** [strapi/strapi#14440]
I noticed `JWT_SECRET` is missing when creating Strapi project and then select manual settings option. 

I think this is an issue because when deploying to some hosting provider like Digital Ocean, the `JWT_SECRET` is required when building and deploying the app.

Strapi version inside `package.json`:

```
"@strapi/strapi": "4.3.8",
"@strapi/plugin-users-permissions": "4.3.8",
"@strapi/plugin-i18n": "4.3.8",
```

Please refer to the images below for the options selected when running `npx create-strapi-app@latest strapi-one`:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/3313237/190856678-512cd461-45f9-4235-b9bf-101897b63e91.png">

<img width="882" alt="image" src="https://user-images.githubusercontent.com/3313237/190856704-7b42c122-562b-427a-8dfd-b2cf8ad8eb31.png">

The current work around is to create another Strapi project with the `Quickstart` option, and use the generated `APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET, JWT_SECRET`

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
