### ISSUE TITLE
Cropping images from media library potentially leads to uploading much larger images

### ISSUE THREAD

**Issue by Alexnortung** [strapi/strapi#14457]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.3.2
- Database: sqlite
- Operating system: Linux

### Describe the bug

Might be related to #7990. When uploading an image that has been optimized with various tools (such as tinypng or imagify) and then cropping the image, the image will be much larger in file size and might even result in a 413 error if you have set a upload limit on your ingress (nginx, etc.).

### Steps to reproduce the behavior

1. Find an image (https://i.redd.it/tp2z5z6106p91.png) (file size: ~450kb)
2. Go to tinypng.com and upload the image (optimized file size: ~132kb)
3. Start your strapi project with `npm run dev`
4. Go to media library
5. Upload the optimized image
6. Edit the image and choose the crop tool
7. crop it to a size of approximately `669✕493` (Should cut off a little part of the image) and make a duplicate
8. Observe that the file size is larger (in my case ~143KB)

### Expected behavior

I would expect the image to be smaller in file size, not larger.

### Screenshots

None.

### Code snippets

None.

### Additional context

This was an even worse problem in our production environment, where we uploaded a ~1MB image and after cropping it, it was ~4MB. This lead to a 413 error from Nginx, since the file upload limit was 3mb.

Another thing that would be nice would be if the client could handle 413 responses when trying to upload and display an error message that said "tile is too large", instead of "internal server error".

**Comment by derrickmehaffy** [comment]
I can confirm this, I used tinypng to compress the image, uploaded it (and the original), then cropped the compressed one.

I'm not sure if we can fix this as it might be sharp's issue.

---

Compressed + Cropped


![Image](https://user-images.githubusercontent.com/8593673/199271664-b8049681-d43f-4c35-b8fa-d8e0c7bda918.png)


![Image](https://user-images.githubusercontent.com/8593673/199271686-4f9123f0-1748-492f-906d-032e87ac8772.png)


---

Original + Cropped


![Image](https://user-images.githubusercontent.com/8593673/199271895-f419aa4b-b063-421f-8e66-9ebd76874623.png)


![Image](https://user-images.githubusercontent.com/8593673/199271925-66e2165c-05f7-4c5d-b20e-a188c8bc09ed.png)

**Comment by Alexnortung** [comment]
Alright, would you suggest that I open an issue at sharp's repo?

**Comment by derrickmehaffy** [comment]
That would be my suggestion here yeah

**Comment by Marc-Roig** [comment]
@Alexnortung Thank you for asking opening an issue on the sharp repo. We have looked into this and their proposed solution.

Our conclusion:
- Changing the png resize algo to be palette based might help in some cases and not others
- We thought on adding this configuration somewhere in the media library, but this will require work and discussions and we don't think it's worth yet. We provide the cropping functionality to focus an image at a certain position and size, but not to add optimisations.

For now we are archiving this and if we work on something related in the future we will reopen the discussion :)

**Comment by Marc-Roig** [comment]
Also, because we see this as an enhancement (to select quality slider and ways to encode images) you could open a Canny ticket https://strapi.canny.io/

**Comment by zicomontibeller** [comment]
Im having the same problem, I just don't get it, what is the purpose of using strapi image formats if they are resizing to larger images? It is just useless. Im surprised this issue was just ignored
