### ISSUE TITLE
REST API pagination returns an object on page 1 and 2

### ISSUE THREAD

**Issue by komape** [strapi/strapi#14468]
### Required System information

- Node.js version: v14.19.2
- NPM version: 8.17.0
- Strapi version: v4.2.3
- Database: PostgreSQL 14.5
- Operating system: Ubuntu 22.04 (LTS) x64

### Describe the bug

The REST API returns the same object on page 1 and 2. I can't see anything that could cause this. And it's probably not the best if I describe the content types in every detail here, so please let me know if you want to know something specifically.

### Steps to reproduce the behavior

1. Send a REST API request with `?pagination[page]=1&pagination[pageSize]=32` and `?pagination[page]=2&pagination[pageSize]=32`
2. Take a look into returned JSON

### Expected behavior

Each object occurs only on a single page.

**Comment by marcoautiero** [comment]
I tried to reproduce it, but everything works here; the response corresponds to the expected page and page size.

**Comment by derrickmehaffy** [comment]
Please try upgrading to the latest version, as we don't have sufficient information to reproduce the issue I will make this as closed.

If you are able to reproduce this in a fresh project, please let us know and we can reopen this.

**Comment by komape** [comment]
@derrickmehaffy I can't upgrade to the latest version because your data model restrictions break my application. I'll create an issue with details once I have enough time.

**Comment by wude935** [comment]
@komape were you able to resolve the error? I'm running into the same error
