### ISSUE TITLE
Generic Servicetype error

### ISSUE THREAD

**Issue by Punit0405** [strapi/strapi#14461]
Hello Strapi , I have found a bug before 2 months and its not have been resolved by you. Solution to that bug is under the PR no #14208 . Please review that and merge as soon as possible so that we can upgrade.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
