### ISSUE TITLE
Typescript) Database interface does not contain connection

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#14469]
### Required System information

- Node.js version: 16.17.0
- NPM version:8.19.2
- Strapi version: 4.3.9
- Database: mysql8
- Operating system: debian

### Describe the bug

I am using `strapi.db.connection.raw()` to execute raw SQL, but I get a type error.
> Property 'connection' does not exist on type 'Database'.

Note:
I'm currently trying to upgrade from 4.2.3 to 4.3.9.

### Expected behavior

No type errors.

**Comment by South-Paw** [comment]
See #13237 ([local change you can make here to fix it](https://github.com/strapi/strapi/issues/13237#issuecomment-1258045747)) and there is a PR #14088 fixing this that was offered a month ago but Strapi team hasn't merged it for whatever reason.

**Comment by matthewdenison** [comment]
Is there a workaround for this?

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
