### ISSUE TITLE
REST API with filtering option $contains returns objects with different value 

### ISSUE THREAD

**Issue by komape** [strapi/strapi#14467]
### Required System information

- Node.js version: v14.19.2
- NPM version: 8.17.0
- Strapi version: v4.2.3
- Database: PostgreSQL 14.5
- Operating system: Ubuntu 22.04 (LTS) x64

### Describe the bug

The Content-Type `artwork` has a field `materials` which is a repeatable component called `material`. That type has one enumeration field `value`. Two possible values are `pen` and `pencil`.

If a request to the REST API contains the filtering option `$contains` for the `materials` field with the value `pen`, the response not just contains objects with `pen` but also objects with `pencil`. This is wrong in my opinion. It seems to check if the material `value` starts with the given value and not if they are equal.

### Steps to reproduce the behavior

1. Create a Content-Type with a repeatable component consisting of an enumeration field.
2. Create two values for the enum with one of them sharing the first letters with the other (i.e. `pen` and `pencil`).
3. Create two `x` objects with different enumeration values.
4. Send a request to the REST API: `https://<host:port>/api/<pluralApiId>?filters[<repeatableComponentField>][<enumField>][$contains][0]=pen`

### Expected behavior

The response should only contain objects with `pen` and not with `pencil`.

**Comment by derrickmehaffy** [comment]
Marking as closed as @marcoautiero is correct. Using contains with "pen" should and will return "pencil"

If you want exact filtering, you should use the $eq which is for equals

**Comment by komape** [comment]
@derrickmehaffy @marcoautiero Thanks for the hint. The only documentation regarding the keyword for filtering is this page: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering

Is there any documentation with more details regarding the meaning of the keywords?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy @marcoautiero Thanks for the hint. The only documentation regarding the keyword for filtering is this page: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/filtering-locale-publication.html#filtering
> 
> Is there any documentation with more details regarding the meaning of the keywords?

No not really though "contains" is fairly universal here. Given we aren't using the JavaScript method here but converting it to the SQL "like" syntax but functionally it works the same. https://www.w3schools.com/java/ref_string_contains.asp

**Comment by komape** [comment]
@DMehaffy thanks for the explanation. Can you these hints to the documentation. That would already help. 

IMO Strapi is a great solution and we're really happy with it but the documentation for the REST API was a little bit disappointing. I had to figure out many things by trying out and take assumptions. This creates an uncertainty if everything works on our website as intended.

**Comment by derrickmehaffy** [comment]
> @dmehaffy thanks for the explanation. Can you these hints to the documentation. That would already help.
> 
> IMO Strapi is a great solution and we're really happy with it but the documentation for the REST API was a little bit disappointing. I had to figure out many things by trying out and take assumptions. This creates an uncertainty if everything works on our website as intended.

We tried to keep it fairly simple but I would recommend passing along this feedback in https://github.com/strapi/documentation
