### ISSUE TITLE
Lose specific table on database after deployment

### ISSUE THREAD

**Issue by Yu-Qi** [strapi/strapi#14460]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.1.8
- Database: postgresql
- Operating system: Ubuntu

### Describe the bug
We deploy strapi by github action. And the some tables in the database are lost in the some cases.
For example, we have two feature branches A & B which has new table Ta & Tb.
First, after merging A branch to dev branch, the new table Ta would be created on strapi. It's normal now.
And then, after merging B branch to dev branch, the new table Tb would be created on strapi. But the table Ta would disappear.

### Steps to reproduce the behavior

1. Create the two feature branches from the main feature.
2. Check out to A branch to ` yarn develop`. Click on  "Create new collection type" to create Table Ta.
3. Merge A branch to dev. And deploy according to dev branch.
4. Check out to B branch to ` yarn develop`. Click on  "Create new collection type" to create Table Tb.
5. Merge B branch to dev. And deploy according to dev branch.
6. The table Ta would disappear.

**Comment by derrickmehaffy** [comment]
Your schema is being modified and you are basically deleting the collection type from Branch A. I'm going to close this as it isn't a bug but please do feel free to open a thread in the community spaces about this as it sounds like you are having some issues in your source control.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
