### ISSUE TITLE
REST API does not respect locale parameter for localized children

### ISSUE THREAD

**Issue by HitMeWithYourBestShot** [strapi/strapi#14473]
## Bug report
Hello,

I'm not sure if this is a bug or the behaviour as designed, but I could not find anything in the docs about it.

### Required System information

- Node.js version: 18.8.0
- NPM version: 8.18.0
- Strapi version: 4.3.6
- Database: Postgres
- Operating system: Windows 11

### Describe the bug
When using the REST API in combination with the I18 plugin, the locale parameter is not respected for child objects of non-localized parents. Instead the default locale is returned for the children.

### Steps to reproduce the behavior
1. Enable the Internationalization (i18n) plugin and add french as an extra language besides the default.
2. Create a new collection type 'Localized' and enable localization for it. Add a short text localized field named 'label'.
3. Create a new collection type 'NonLocalized' and disable localization for it. Add a 'has one' relation field which references the Localized type.
4. Create a new entry for the Localized type. Fill in both languages.
5. Create a new entry for the NonLocalized type that references the entry created above.
6. Query the REST API with the following url: /api/non-localizeds?populate=%2A&locale=fr
7. The response contains the populated entry of type 'Localized', but it is in the default language (German in my case) instead of French.

```
{
  "data": [
    {
      "id": 1,
      "createdAt": "2022-09-27T09:45:02.708Z",
      "updatedAt": "2022-09-27T09:45:02.708Z",
      "localized": {
        "id": 1,
        "label": "labelDe",
        "createdAt": "2022-09-27T09:42:20.313Z",
        "updatedAt": "2022-09-27T09:47:39.810Z",
        "locale": "de"
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 25,
      "pageCount": 1,
      "total": 1
    }
  }
}
```

### Expected behavior

The response contains the populated localized entry in French.

**Comment by bolg55** [comment]
Hello -> step 5. "Create a new entry for the NonLocalized type that references the entry created above.", are you able to select different options in the relation? When attempting to reproduce I was only able to select the default.
