### ISSUE TITLE
error: insert into "files_related_morphs"

### ISSUE THREAD

**Issue by nvoskuilen** [strapi/strapi#14472]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.17.0
- Strapi version: 4.3.9
- Database: PostgreSQL @ DigitalOcean (managed)
- Operating system: DigitalOcean App Platform

### Describe the bug

We initially deployed strapi v4.3.4 where we did not (yet) encounter the following issue, but after we upgraded to 4.3.8 we noticed:

A "Warning: internal Server Error" after adding an image for a repeatable component and clicking save.

### Steps to reproduce the behavior

1. Create a repeatable component with an image
2. Use the strapi-provider-upload-do plugin to upload some images
3. Via content-manager create some entries with images and hit save
4. A "Warning: internal Server Error" should popup
5. If no error is shown, try changing one of the images and hit save. 

Unfortunately we did not managed to reproduce the exact steps to trigger the error. But when the issue happens, all images will be broken..

### Additional context

Logs
```
[strapi] [2022-09-23 15:10:51] [2022-09-23 15:10:51.495] error: insert into "files_related_morphs" ("field", "file_id", "order", "related_id", "related_type") values ($1, $2, $3, $4, $5) returning "id" - column "id" does not exist
[strapi] [2022-09-23 15:10:51] error: insert into "files_related_morphs" ("field", "file_id", "order", "related_id", "related_type") values ($1, $2, $3, $4, $5) returning "id" - column "id" does not exist
[strapi] [2022-09-23 15:10:51]     at Parser.parseErrorMessage (/opt/node_modules/pg-protocol/dist/parser.js:287:98)
[strapi] [2022-09-23 15:10:51]     at Parser.handlePacket (/opt/node_modules/pg-protocol/dist/parser.js:126:29)
[strapi] [2022-09-23 15:10:51]     at Parser.parse (/opt/node_modules/pg-protocol/dist/parser.js:39:38)
[strapi] [2022-09-23 15:10:51]     at TLSSocket.<anonymous> (/opt/node_modules/pg-protocol/dist/index.js:11:42)
[strapi] [2022-09-23 15:10:51]     at TLSSocket.emit (node:events:513:28)
[strapi] [2022-09-23 15:10:51]     at TLSSocket.emit (node:domain:489:12)
[strapi] [2022-09-23 15:10:51]     at addChunk (node:internal/streams/readable:315:12)
[strapi] [2022-09-23 15:10:51]     at readableAddChunk (node:internal/streams/readable:289:9)
[strapi] [2022-09-23 15:10:51]     at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
[strapi] [2022-09-23 15:10:51]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

We noticed that by redeploying the app it will fix the issue temporary, we are able to save the content.

**Comment by mananzealousweb** [comment]
I got the same issue when updating the page/articles. Did you find the solution to this @nvoskuilen ?

**Comment by derrickmehaffy** [comment]
I can't reproduce this issue using our own S3 provider and DO Spaces (We can't provide support for 3rd party upload providers if the bug's root cause is there). For now I'll mark this as closed until reproduction steps can be detailed.
