### ISSUE TITLE
Rendering issue: Custom fields are causing problems for other components.

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#14489]
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.4.0
- Database: mysql8
- Operating system: debian

### Describe the bug

When custom fields and JSON,RichText fields are used together, the
JSON,RichText fields will go wrong.

JSON and RichText fields do not display values.
Click once to appeared.

and...

Overlapping line numbers are displayed in JSON fields.

### Screenshots

JSON fields:
![screenshot](https://user-images.githubusercontent.com/26789317/192945307-d2e8e6e6-6f06-45c4-a1f1-3ca72f032261.png)

### Additional context

I also tried [ColorPicker 4.4.0](https://www.npmjs.com/package/@strapi/plugin-color-picker) but the same problem occurs.

It does not seem to be related to the Input component of the custom field.
Because it happens even if the Input component is the following.

```jsx
export default () => {
  return <div>test</div>
}
```

**Comment by robsgreen** [comment]
I am also seeing this issue on 4.4.3
I added a custom field based on JSON and now the other regular JSON fields in the admin display this behavior. 

<img width="953" alt="image" src="https://user-images.githubusercontent.com/7075886/196812911-e009e495-9eb8-4cc3-9d20-8e9061836d4b.png">

**Comment by emilieringwald** [comment]
Hello! We just added this to our current sprint, we'll give you an update as soon as possible.
