### ISSUE TITLE
Server wasn't able to start properly

### ISSUE THREAD

**Issue by bawangxx** [strapi/strapi#14488]
`npx create-strapi-app@latest my-project --ts --quickstart`
![1](https://user-images.githubusercontent.com/8935765/192921457-87cb819c-44e6-40f7-a4c8-e6abee9579ec.png)

**Comment by South-Paw** [comment]
See #13237, here is a local change you can make [to fix it](https://github.com/strapi/strapi/issues/13237#issuecomment-1258045747)

There is also PR #14088 which fixes this this that was put up a month ago but the Strapi team hasn't merged it for whatever reason which is really frustrating

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
