### ISSUE TITLE
API can`t accept string no english,how to solve it?

### ISSUE THREAD

**Issue by lstrcat** [strapi/strapi#145]
**Node.js version**:4.4.5
**npm version**:2.15.5
**Strapi version**: 1.5.4
**Operating system**:Win7 x64
![qq 20160920114143](https://cloud.githubusercontent.com/assets/1246297/18656833/38484d08-7f27-11e6-913b-77677e56636f.png)
this is my POST,  notice that the Response, the **name** .

**Comment by lstrcat** [comment]
solved!It is because the chaset of the database

**Comment by Aurelsicoko** [comment]
Which database are you using? Can you try to reset to UTF-8 your database?

**Comment by lstrcat** [comment]
MySql,Yes i reset it to UTF-8 .but after restart StrAPI,it change back to Latin1.so the name became `?????` again.

**Comment by Aurelsicoko** [comment]
What value are you trying to insert? On your screenshot, we can perfectly read the value "default" which is an english string too. Can you show us your model, please?

**Comment by lstrcat** [comment]
`Gift.settings.json`
```
{
  "identity": "gift",
  "connection": "ttmysql",
  "defaultTemplate": "default",
  "displayedAttribute": "",
  "schema": true,
  "attributes": {
  "name": {
    "type": "string"
  },
  "jb": {
    "type": "integer"
  },
  "lang": {
    "type": "string",
    "required": true
  },
  "template": {
    "type": "string",
    "required": true
  },
  "id_ref": {
    "type": "int"
  },
  "createdBy": {
    "model": "user"
  },
  "updatedBy": {
    "model": "user"
  },
  "contributors": {
    "collection": "user",
    "via": "gifts"
  }
},
  "autoCreatedAt": true,
  "autoUpdatedAt": true
}
```

i **Create A Gift** with the name "礼物" that non-english string
![qq 20160920163447](https://cloud.githubusercontent.com/assets/1246297/18663233/37f31d78-7f50-11e6-875c-f76556892bd6.png)

**Comment by Aurelsicoko** [comment]
Is the same exact value in the database? The issue concerns more the Waterline ORM or your database than Strapi, though.
