### ISSUE TITLE
Added new column from mysql workbench connected with aws RDS but not reflecting data update with Strapi

### ISSUE THREAD

**Issue by pankajSudoviz** [strapi/strapi#14506]
I added new column in the mysql database of aws RDS which is connected with strapi APIs (to make manipulation in the data on the DB) but when I ran PUT request to add data in new added column the data is not reflecting in it.

I have appropriate routes in json file for it. 
Any suggestions to fix this?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
