### ISSUE TITLE
IDEA shows ts errors in just generated plugin

### ISSUE THREAD

**Issue by romash1408** [strapi/strapi#14501]
### Required System information

- TypeScript: 4.6.3
- Strapi version: 4.4.0

### Describe the bug

I generated plugin through `yarn strapi generate` and selected TypeScript.
And now Intellijie IDEA shows TypeScript errors in almost every generated file under `/src/plugins/<name>/admin/src/`

### Expected behavior

I think there should be `/src/plugins/<name>/admin/src/tsconfig.json` file generated
```json
{
  "extends": "@strapi/typescript-utils/tsconfigs/admin.json"
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/14085271/193197598-a4603163-6f4f-4197-81de-11ad7480b0f1.png)

**Comment by romash1408** [comment]
@derrickmehaffy what reproduction information should I provide besides issue description?
> I generated plugin through yarn strapi generate and selected TypeScript.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy what reproduction information should I provide besides issue description?
> 
> > I generated plugin through yarn strapi generate and selected TypeScript.

I'm sorry, this got closed in error by the wrong label being used in the github action. Reopening.

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
