### ISSUE TITLE
Sizing of custom fields in "Configure View" is determined by backend type.

### ISSUE THREAD

**Issue by xenobytezero** [strapi/strapi#14509]
### Required System information

- Node.js version: 16.15.0
- Yarn version: 3.2.3
- Strapi version: 4.4.0
- Database: sqlite
- Operating system: Windows 10

### Describe the bug

When attempting to "Configure View" and entity that uses custom fields, I found that the ability to set the width of a field in the view appears to be tied to the underlying type of the field, rather than the capabilities of the front end component.

I had two custom fields that were both of backend type `string` which I could set to be 50% width and sit next to each other, however when I updated the type of one of them to be `json`, the width setting disappeared from that field.

This matches the behaviour when adding a standard text field and a JSON field to a content type, which backs up my assumption above.

### Expected behavior

I would imagine that sizing should follow the more flexible `string` options, since the design of the input component is down to the implementor.

**Comment by emilieringwald** [comment]
Hey @xenobytezero! Thanks for the heads-up, we are going to have a look at this as soon as possible.

**Comment by markkaylor** [comment]
Hello @xenobytezero, this was addressed in https://github.com/strapi/strapi/releases/tag/v4.10.0. I'll close this now but thank you for reporting the issue.
