### ISSUE TITLE
Add nvm config file

### ISSUE THREAD

**Issue by thelovekesh** [strapi/strapi#14520]
As a NodeJS developer, it's common to work with different node versions. NVM is a helpful utility to manage such things.

# TODO
- Add a `.nvmrc` file
- Specify a node version that complies with current development standards.

**Comment by thelovekesh** [comment]
@derrickmehaffy  If it is deemed to be a fit, please assign it to me. I will be happy to raise a PR for this.

**Comment by derrickmehaffy** [comment]
We don't assign issues, also all issues much follow our bug report templates. If you want to submit a PR, just do it.
