### ISSUE TITLE
Fail to update admin path

### ISSUE THREAD

**Issue by AustinBratcher** [strapi/strapi#1452]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 6.0.0
- **Strapi version**: 3.0.0-alpha.12.5
- **Database**: Mongo (hosted on Mlab)
- **Operating system**: macOS 10.13.5

**What is the current behavior?**
In the server config for each environment (i.e. config/environments/**/server.json) there is an option to set the default path for the admin page (by changing the admin.path variable). It is suggested in the [deployment documentation](https://strapi.io/documentation/guides/deployment.html) to change the variable to /dashboard for security reasons. However when doing so, plugins are not loaded. I believe this is due to some kind of routing issue. After setting the admin.path to '/dashboard' trying to navigate to /dashboard/plugins returns a 404 error. Trying to navigate to /admin/plugins (after the admin.path variable has been set to  '/dashboard') works just fine. 

**Steps to reproduce the problem**
For whatever environment you are working in, change the admin.path variable to anything but "admin" in config/environments/<your_environment>/server.json.

**What is the expected behavior?**
When the Strapi Admin page loads, for whatever value is set in admin.path, the plugins should load. 

**Suggested solutions**
This is probably an issue in the main strapi router (not in the react router). I'm not familiar enough with it to give any suggestions off the top of my head.

**Comment by AustinBratcher** [comment]
Upon some further digging in the chrome network tools, it looks like none of the needed resources are loading after the admin.path variable is set. All the requests look at the /admin route. So I'm not sure if this is a front end issue where the route requested should be changed or if this a back end issue where the requested routes are changed when they should not be.

**Comment by derrickmehaffy** [comment]
May have something to do with the routing issues on the API prefix too. If you change it to something like /API you lose access to the /public and /admin

**Comment by derrickmehaffy** [comment]
Possible related issue: https://github.com/strapi/strapi/issues/1323

(Jim don't close this one as duplicate since it's technically a different issue)

**Comment by lauriejim** [comment]
Hello @AustinBratcher . I just tried with a fresh new project and database with Strapi alpha.12.6 and it work well on my side.

Can you try with last version of Strapi please.

**Comment by derrickmehaffy** [comment]
@lauriejim I just tested changing the admin path and it does work fine on 12.6, there is still an issue with the prefix though. I think it should be safe to close this issue.

**Comment by Aurelsicoko** [comment]
@AustinBratcher Can you confirm it works on the latest release? So we can close the issue.

**Comment by AustinBratcher** [comment]
@Aurelsicoko and @lauriejim 

Just updated to 3.0.0-alpha.12.6. In a development environment, changing the admin path works fine. However, as soon as I run my api in my production environment, I get the same problems mentioned before. Is there some other configuration that could be causing the issue?

**Comment by soupette** [comment]
@AustinBratcher did you manage to change the admin path in production?

**Comment by AustinBratcher** [comment]
No, sorry. This project has been put on the back burner for the next couple
of weeks. If I get a chance to try and make the change, I'll be sure to let
you know.

**Comment by lauriejim** [comment]
Looks working on my side. I close this issue.
Will reopen it if it still happen after your test on your project.

**Comment by nickkrein** [comment]
Solved that issue. Now having the same issue as https://github.com/strapi/strapi/issues/2092

**Comment by bringmethecode** [comment]
I am still experimenting this issue... Strapi 3.0.0-alpha.14.4.0

I see there are severals hardcoded urls in the Admin:

`admin/src/containers/AdminPage/saga.js`:

```
    const [{ allowGa }, { strapiVersion }, { currentEnvironment }, { layout }] = yield all([
      call(request, '/admin/gaConfig', { method: 'GET' }),
      call(request, '/admin/strapiVersion', { method: 'GET' }),
      call(request, '/admin/currentEnvironment', { method: 'GET' }),
      call(request, '/admin/layout', { method: 'GET' }),
    ]);
```

`admin/src/containers/ListPluginsPage/saga.js`:

```
export function* pluginsGet() {
  try {
    // Fetch plugins.
    const response = yield [
      call(request, '/admin/plugins', { method: 'GET' }),
      call(request, '/admin/currentEnvironment', { method: 'GET' }),
    ];
...
```
I see you define `remoteURL`, should these files make use of it?

**Comment by soupette** [comment]
@bringmethecode the hardcoded urls are the one used to make the api calls the admin is like a standalone app so it's intended.
Also you should upgrade to 14.5

**Comment by PaulDreef** [comment]
Same issue on my side:

`
﻿
main.js:1 ⚠️ It looks like the language "pt-BR" is not supported by "react-intl" module.
main.js:1 ⚠️ It looks like the language "zh-Hans" is not supported by "react-intl" module.
main.js:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/config/plugins.json 404 (Not Found)
main.js:1 SyntaxError: Unexpected token T in JSON at position 0
    at main.js:1
main.js:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/gaConfig 404 (Not Found)
main.js:1 SyntaxError: Unexpected token T in JSON at position 0
main.js:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/strapiVersion 404 (Not Found)
main.js:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/currentEnvironment 404 (Not Found)
main.js:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/layout 404 (Not Found)
/admin/bd03a2cc277bb…4e679fe9942.woff2:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/bd03a2c….woff2 net::ERR_ABORTED 404 (Not Found)
/admin/27bd77b9162d3…c4217c7c5e2a.woff:1 GET https://temp-vipmd-dev-app.azurewebsites.net/admin/27bd77b….woff net::ERR_ABORTED 404 (Not Found)
﻿
​
`
I ran a "npm run setup", zipdeploy to azure, node10..
The admin/ path is hardcoded ? In the build-dir there is no admin folders (only a config)

What do I miss ?

**Comment by lauriejim** [comment]
Maybe this article can help you https://github.com/strapi/strapi/wiki/Switch-from-dev-app-to-prod

**Comment by easydrops** [comment]
I had the same issue with strapi alpha 14 - updating to alpha 24.1 helped.
