### ISSUE TITLE
Missing Permissions for Uploads Folders

### ISSUE THREAD

**Issue by tit1** [strapi/strapi#14522]
### Required System information

- Node.js version: 16.4.2
- YARN version: 1.22.19
- Strapi version: 4.4.1
- Database: PostgreSQL
- Operating system: Mac

The is no permissions for Uploads/folders or permissions are not inherited from the Uploads permissions. I am working on a Strapi site with all APIs currently being public. When trying to access `uploads/folder` i get an unauthorized error.

1. Go to the Strapi admin panel under 'USERS & PERMISSIONS PLUGIN' select Roles and Public.
2. Expand the the 'Upload' panel and select All.
3. Save
4. Using insomnia send a get request to http://localhost:xxxx/uploads/folders
5. 401 - Unauthorized

### Expected behavior

Id expect a API response containing all the current folders in Uplaods

### Screenshots

![image](https://user-images.githubusercontent.com/8396914/193467955-e5ae04cd-aea7-4edb-8043-b1f4cb7227df.png)
![image](https://user-images.githubusercontent.com/8396914/193467977-6715b26d-66c7-4067-b5dd-2c17053008db.png)

**Comment by tit1** [comment]
Sorry updated my comment. I had the wrong URL `/api/upload/folders` instead of `/upload/folders`

**Comment by CleberRossi** [comment]
@tit1 Is everything right? Can you close the issue, please ?

**Comment by derrickmehaffy** [comment]
Marking as closed on the users behalf.

**Comment by vaibhavcartoq** [comment]
Any solution for this issue?
