### ISSUE TITLE
Data gets deleted randomly most of the times when Strapi server is restarted

### ISSUE THREAD

**Issue by aschick82** [strapi/strapi#14533]
### Data gets deleted randomly most of the times when Strapi server is restarted

I am using Strapi v4.4.1 connected to a Postgres database.

Unfortunately, all of my data gets deleted randomly and this is very annoying.

This happens most of the times when the server is restarted or I run the app in development mode connected to my production database.

I had a lot of drafted data a few days ago and suddenly I noticed that they were disappeared.

This is a serious issue and needs to be fixed.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
