### ISSUE TITLE
Access admin panel through link with token

### ISSUE THREAD

**Issue by guillermodoghel** [strapi/strapi#1454]
Depending the user role, I have an admin panel link in my frontend. But due its in another host, admin user needs to login again. I would love to have a way to access de admin panel via an href, something like http://localhost:1337/admin/?login=asdfasdfasdf.... that allows me to enter directly into the admin panel without need to re-login

**What is the expected behavior?**

Given a route to the admin panel, allow to login using the JWT token as a parameter.  (asuming I got the token from the login request from the API)
IE: http://localhost:1337/admin/?login=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNTMwMDIwMzkxLCJleHAiOjE1MzI2MTIzOTF9.9FDMq7GCSjf4ZGRnHQX-uZsf73YGQmAo_TpRYbI6RbA

Gets me into de admin page without having to login

**Comment by derrickmehaffy** [comment]
@guillermodoghel can you update this with the proper template (it looks like a feature request)

**Comment by guillermodoghel** [comment]
I've resolved this by doing the following aberrant workarround

On my frontend app I created and href that looks like
```
STRPI_PATH + '/admin/?login' +
              encodeURIComponent(JSON.stringify({token:getToken(),user:getUser()}))
```

where getToken() and getUser() are the admin jwt and user object returned in login.

On the strapi side, in ./admin/admin/src/containers/AdminPage.indexjs
in the begnining of   **componentDidMount() {** I added this code

```
    if(this.props.location.search.includes('?login')){
      let loginstuff = JSON.parse(decodeURIComponent(this.props.location.search.slice(6)));
      auth.setToken(loginstuff.token);
      auth.setUserInfo(loginstuff.user);
    }
```

I think there are way a more "correct" ways of doing it. 
The ideal thing would be to only send the jwt token as a parameter, but when I tried to only do auth.setToken, I could access the admin panel, but it worked super weird (the username wasnt loaded, and half of functionalities wont work)

Is there any way, from inside the admin, to get the **user object** with the jwt token as an input parameter?

**user object** -> `{"username":"admin","id":1,"email":"test@sometek.ws","provider":"local","role":{"id":1,"name":"Administrator","description":"These users have all access in the project.","type":"root"}}`

**Comment by lauriejim** [comment]
@guillermodoghel Feel free to submit a PR to share your work with the Strapi community

**Comment by Aurelsicoko** [comment]
I'm closing this issue because we will change our way of handling administrators and users. Currently, there is one collection/table for both. We will create a true administrator system. So this feature won't make sense anymore or the approach will be different.

Feel free to continue the discussion and ping me if needed.

**Comment by deevannaveed** [comment]
> I'm closing this issue because we will change our way of handling administrators and users. Currently, there is one collection/table for both. We will create a true administrator system. So this feature won't make sense anymore or the approach will be different.
> 
> Feel free to continue the discussion and ping me if needed.

I have changed the default WYSIWYG rich text editor to Froala editor, via Froala we can upload images, files and videos so now I have a problem, how can I get the admin token to send with image upload post request? It works when the upload plugin `upload` permission is checked in public roles and permissions but it will not work when its only allowed to authenticated users!

**Comment by soupette** [comment]
@deevannaveed you can use the `auth.getToken()` utility, here's how to use it in the admin panel:

```
import { auth } from 'strapi-helper-plugin`;

const token = auth.getToken();
```

Note: [here's the utility](https://github.com/strapi/strapi/blob/master/packages/strapi-helper-plugin/lib/src/utils/auth.js) if you want to check the informations stored in your local storage.
