### ISSUE TITLE
Strapi failed to compile in admin development mode

### ISSUE THREAD

**Issue by michelmfreitas** [strapi/strapi#14548]
### Required System information

Strapi Version: 4.3.8
Operating System: MacOS Monterey
Database: SQLite
Node Version: 16.17.1
NPM Version: 8.15.0
Yarn Version: 1.22.19

### Describe the bug

I've been using the strapi API for my application and the app works when not run on the admin mode (npx strapi watch-admin). But I need to run with admin mode and the application failed to compile.

I thought that was some error caused by me. However, I create a new clean installation (with quickstart) from strapi and try to run a development admin mode and the error is the same.

```
Failed to compile.
Module parse failed: Unexpected token (402:11)
cache/admin/src/StrapiApp.js
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/esbuild-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
|       fields: { fields }
|     } = this.library;
>     return  {
|       return this.runHookWaterfall(name, initialValue, async, store);
|     }} runHookSeries={this.runHookSeries} themes={this.configurations.themes} settings={this.settings} showTutorials={this.configurations.tutorials} showReleaseNotification={this.configurations.notifications.releases} store={store}><>
```
I've tried to remove node_modules and cache folder and install dependencies and build again but doesn't work.

I think can be an error from webpack compilation with react scripts, according to some issues that I found on StackOverflow, but it's not applicable in strapi case. (The users changed the react-script version on the package.json and it works).

What do I need to do?

**Comment by ayhid** [comment]
I have the same thing with strapi 4.4.3 (node v14.20.1)

**Comment by CleberRossi** [comment]
Hello,  @ayhid  and @michelmfreitas 

I am having trouble to reproduce this error. 

What I tried:

`yarn build && yarn develop `

opened another tab:

`yarn strapi watch--admin`

Everything seemed to work fine, can you gimme more details about this problem?

Things I want to know:

1. Is this error ocurring during the build on browser or on sh console?
2. There error is when running strapi develop or running watch-admin?
3. Are you able to do what you need with strapi develop, but when you add watch-admin, using por 8000 you have this problem?
4. Have you tried in another computer, OS or someone in your project with differrent system reqs?

**Comment by minht11** [comment]
I am experiencing the same error when using npm workspaces. At least as far as I understand it fails to dynamic link node_modules from root
