### ISSUE TITLE
Alpha12.5 won't start within docker container due to "new" command

### ISSUE THREAD

**Issue by philippfrenzel** [strapi/strapi#1455]
api_1            | [2018-06-22T18:27:26.469Z] error `$ strapi new` can only be called in an empty directory.
api_1            | [2018-06-22T18:27:27.141Z] error This command can only be used inside a Strapi project.

`
FROM node:alpine

LABEL maintainer="Luca Perret <perret.luca@gmail.com>" \
      org.label-schema.vendor="Strapi" \
      org.label-schema.name="Strapi Docker image" \
      org.label-schema.description="Strapi containerized" \
      org.label-schema.url="https://strapi.io" \
      org.label-schema.vcs-url="https://github.com/strapi/strapi-docker" \
      org.label-schema.version=latest \
      org.label-schema.schema-version="1.0"

WORKDIR /usr/src/api

RUN npm install -g strapi@3.0.0-alpha.12.5

COPY strapi.sh ./
RUN chmod +x ./strapi.sh

EXPOSE 1337

COPY healthcheck.js ./
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s \
      CMD node /usr/src/api/healthcheck.js

CMD ["./strapi.sh"]
`

**Comment by lauriejim** [comment]
@philippfrenzel This issue is related to Docker, can you please create it in `strapi-docker` repo please.

**Comment by philippfrenzel** [comment]
Hi, so I´ll post it their ;) Thanks for answering
