### ISSUE TITLE
package.json license should be MIT not READ LICENSE IN LICENSE

### ISSUE THREAD

**Issue by unsalted** [strapi/strapi#14550]
### Required System information

- Node.js version:18
- NPM version:8.19
- Strapi version: 4+
- Database: Not relevant
- Operating system: Mac / Linux

### Describe the bug

package.json has License listed as `SEE LICENSE IN LICENSE`.  It should be `MIT`.

Many companies have well developed processes for working with Opensource software, one component of these processes is doing strict checks of licenses using tools like, license-checker. If the package.json is missing a license or the license type is not one that is permitted, the packages are blocked from being used.  Unblocking these packages in some instances requires legal reviews, and allow-listing. This in many cases also only applies to a single version.  

With Strapi's current way of attributing license in the package.json, engineers need to request allow listing for every single Strapi package, despite the fact that the community edition, is actually under MIT license. In short, the decision to put SEE LICENSE IN LICENSE, adds days of delays to projects, hours of headaches, and more or less blocks Strapi from even being tested in some companies.

I do genuinely see this as a bug, because it effectively blocks software development at companies with well run Ops.  And it is do to a poorly formed package.json.

### Steps to reproduce the behavior

1. Go to package.json and read that it is says SEE LICENSE IN LICENSE.

### Expected behavior

License should say `MIT`.

If certain files should be under a different license put a second License file with those files.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by thomasgilmore95** [comment]
I would like to work on this

**Comment by thomasgilmore95** [comment]
@derrickmehaffy Ok, more than happy to work on this after you discuss.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Ok, more than happy to work on this after you discuss.

Most likely we won't let others work on this, this is something the core team needs to address ourselves but thanks for the offer.

**Comment by alexandrebodin** [comment]
Hi @unsalted  

Strapi license is an extension of the MIT license and as such we cannot put MIT in the package.json. This would be at best missleading :)

According to npm's documentation when you use a modified license you should point to the file. https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license.

**Comment by unsalted** [comment]
As far as i'm aware it is MIT when being used as CE, at least that is how it's represented.  It would be a shame that Strapi would make it difficult for customers to use because of packaging EE software with CE.  I just want to emphasize that his has considerable downstream impacts on customers. If a shrug is the best solution, that's fine.

**Comment by derrickmehaffy** [comment]
> As far as i'm aware it is MIT when being used as CE, at least that is how it's represented.  It would be a shame that Strapi would make it difficult for customers to use because of packaging EE software with CE.  I just want to emphasize that his has considerable downstream impacts on customers. If a shrug is the best solution, that's fine.

The code still exists in the user's node modules so that if they decide to purchase a license all they need to do is just drop the license in a file and restart the server (don't even need to rebuild).

It would be more accurate to say that the CE mode only uses MIT code but that the proprietary code still exists on the user's computer.

**Comment by derrickmehaffy** [comment]
Has Alex mentioned though since we're following NPMs documented best practice I'll set this one as resolved.
