### ISSUE TITLE
`getEnabledPlugins`fails silently when package can not be resolved

### ISSUE THREAD

**Issue by manvydasu** [strapi/strapi#14569]
### Required System information

- Node.js version: N/A
- NPM version: N/A
- Strapi version: 4.4.3 (Latest)
- Database: N/a
- Operating system: N/A

### Describe the bug

Logic inside `get-enabled-plugins.js` ignores exceptions (fails silently) and continues execution without any warnings to the user.

https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/core/loaders/plugins/get-enabled-plugins.js#L70

```javascript
  for (const dep of Object.keys(dependencies)) {
    const packagePath = join(dep, 'package.json');
    let packageInfo;
    try {
      packageInfo = require(packagePath);
    } catch {
      continue;
    }

    if (isStrapiPlugin(packageInfo)) {
      validatePluginName(packageInfo.strapi.name);
      installedPlugins[packageInfo.strapi.name] = {
        ...toDetailedDeclaration({ enabled: true, resolve: packagePath }),
        info: {
          ...packageInfo.strapi,
          packageName: packageInfo.name,
        },
      };
    }
  }
``` 

### Steps to reproduce the behaviour

Using custom strapi plugins and `pnpm` with default configuration. (I. can add more details with needed, but the problem is visible from the code itself)

### Expected behaviour

When exception is throw during execution of `getEnabledPlugins, code should not continue executing or at least error should be logged somewhere.
With the current behaviour, code fails silently at mentioned step, but fails later with a different error (due to missing package info), which then has to be manually traced back to this code location.

**Comment by pbvahlst** [comment]
Maybe more finegrained error handling is needed before stopping execution og printing an error. If as an example we have a `package.json` like this
```
{
  "exports": {
    ".index.js": "./index.js"
  }
} 
```
An error would be thrown because `package.json` is not exported. But the current module is not a strapi plugin and don't need to expose its `package.json` but still need to be listed as a dependency to be `required` somewhere else in the code.

**Comment by manvydasu** [comment]
@kasonde 
Hey,
I was using Lerna + pnpm when I jumped on this.
One lerna package was a strapi application, which was using a custom plugin.
And the other one was custom strapi plugin (this plugin was used by the application in the same lerna monorepo).

If I can find some free time, I'll attempt to add reproducible example. 
But in my view, some simple logging in that try/catch block would be sufficient.
