### ISSUE TITLE
V.4.4.3 CKEditor not loading

### ISSUE THREAD

**Issue by galago** [strapi/strapi#14568]
Hello 👋 after upgrading to the newest version my CKEditor plugin is not loading in my Heroku instance. It does load in my local environment though. I just downgraded to V.4.4.1 and it works fine again. My version of Strapi is inherited from TS Beta 1. 

I checked heroku logs and no error was found, it just doesn't load the editor at all, even calls are made to CKEditor plugin:
```

> 2022-10-07T07:24:11.482798+00:00 heroku[router]: at=info method=GET path="/ckeditor/config/plugin" host=urbanist-travel-strapi-v4.herokuapp.com request_id=76b8b943-e7a7-4e26-8b17-83dce8a21582 fwd="212.102.48.217" dyno=web.1 connect=0ms service=21ms status=200 bytes=4893 protocol=https
> 2022-10-07T07:24:11.481343+00:00 app[web.1]: [2022-10-07 07:24:11.481] http: GET 
> /ckeditor/config/plugin (19 ms) 200
> 2022-10-07T07:24:11.795687+00:00 app[web.1]: [2022-10-07 07:24:11.795] http: GET 
> /ckeditor/config/uploadcfg (21 ms) 200
> 2022-10-07T07:24:11.797042+00:00 heroku[router]: at=info method=GET path="/ckeditor/config/uploadcfg" host=urbanist-travel-strapi-v4.herokuapp.com request_id=1aa50dc5-900c-413b-a50f-55ce5e128fad fwd="212.102.48.217" dyno=web.1 connect=0ms service=23ms status=200 bytes=1013 protocol=https

```

heroku 
strapi: 4.4.3
strapi-plugin-ckeditor1.1.2
node 16.17.1
DB: PostGres

**Comment by derrickmehaffy** [comment]
This plugin is not built or maintained by Strapi, please open an issue with the maintainer.
