### ISSUE TITLE
Memory Peak during uploads (independently of the provider used)

### ISSUE THREAD

**Issue by Jose10go** [strapi/strapi#14576]
### Required System information

- Node.js version: Node 16
- Yarn version: yarn 3.2.3
- Strapi version: Strapi 4.4.3
- Operating system: Debian bullseye  

### Describe the bug

When uploading a big video file the memory footprint of the app go up like if the file is buffered into memory. When hosted online sometimes the result is a 502 with the server crashing for running out of memory. This might have useful context https://github.com/strapi/strapi/issues/6432

### Steps to reproduce the behaviour
The error could be reproduced using the API, for simplicity we will describe how to reproduce it using the admin. Also the provider was not relevant, I was able to reproduce this issue with the local provider, the S3 one and the google cloud one.

1. Go to Media library in admin
2. Upload a big video file (I use a 1.5 Gb video) 
3. Watch the memory consumption.( Locally I check this dropping some `console.logs` with the `process.memoryUsage()` API. If Strapi is deployed in the cloud you might have a better tool to validate this.)

### Expected behaviour
The memory consumption shouldn't go up like if the file is being buffered into memory.(There should be no Memory Peak)

### Screenshots

Memory peak during uploads in Google Cloud deployed Strapi around 11:30:

![Screenshot 2022-10-07 at 18 12 15](https://user-images.githubusercontent.com/49805918/194600146-3bb4f567-28e9-4a1a-adca-004c3cf9d5fb.png)

### Additional context

After dropping some console.logs to check memory usage I think I found where the problem is, the image-manipulation service has an isImage function https://github.com/strapi/strapi/blob/main/packages/core/upload/server/services/image-manipulation.js#L209. This function is used in the upload service uploadFileAndPersist function https://github.com/strapi/strapi/blob/main/packages/core/upload/server/services/upload.js#L244 to determine if a file should be upload as an image, or as a generic file.
The isImage function is where the file is being buffered into memory, it is using getMetadata based on Sharp library to extract the file format... I don't have experience using Sharp, they support streams but I am not sure if it should be used  with streams of files that are not images, like videos in my case.... so maybe it shouldn't be used to verify if a file is actually an image.

As a workaround I am overwriting the isImage function of the image-manipulation service on my extension folder with something like:
```
const EXTENSIONS_TO_PROCESS = ['.jpeg', '.png', '.webp', '.tiff', '.svg', '.gif']; 

const isImage = async (file) => {
  const format = file.ext;
  return format && EXTENSIONS_TO_PROCESS.includes(format);
};
```

If the Strapi team feels like this could be a possible solution I am happy to open a PR.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/14417

**Comment by changqing91** [comment]
> 重复：#14417

you closed a important issue
