### ISSUE TITLE
config:restore doesn't restore collection type from JSON dump file

### ISSUE THREAD

**Issue by sts-ryan-holton** [strapi/strapi#14573]
### Required System information

- Node.js version: 14.19.3
- NPM version: 8.19.2
- Strapi version: 4.4.1
- Database: MySQL (5.7)
- Operating system: Mac

### Describe the bug

When running a `config:restore` I'm not seeing a newly added content type in my content type builder -> my collection type -> my field list.

I have a collection type called `Career`, and a field called `salary` that I previously added, ran a `config:dump` and when restoring don't see it restoring the `salary` field.

### Steps to reproduce the behavior

1. Add collection type
2. Add new int field called salary
3. run `npm run strapi config:dump > dump.json`
4. run `npm run strapi config:restore < dump.json`
5. run `npm run build`
6. run `npm run start`

### Expected behavior

I should expect to see my `salary` field restored within my collection type.

### Screenshots

<img width="708" alt="Screenshot 2022-10-07 at 16 42 22" src="https://user-images.githubusercontent.com/25177538/194594016-9c2cb5f8-120b-4e42-8e0a-a2ce1d45ce06.png">
<img width="1086" alt="Screenshot 2022-10-07 at 16 42 13" src="https://user-images.githubusercontent.com/25177538/194594020-e850ad04-1b5d-4143-8fe6-e28df5c36185.png">

**Comment by derrickmehaffy** [comment]
This command only dumps the configuration of a content-type (from the core_store table in the database) which holds the view config, not the schema config which is already located on the filesystem.

**Comment by derrickmehaffy** [comment]
No, that is largely the reason we strongly recommend users are using source control like Git.

Ideally you should be comitting often and small commits to give you that file history.
