### ISSUE TITLE
Define default attributes for JSON input

### ISSUE THREAD

**Issue by nicokant** [strapi/strapi#1457]
**What is the expected behavior?**
I would expect to be able to configure fields inside a JSON field, this would allow  a structured approach, and would allow reusing already implemented fields to better edit a JSON content

**Comment by derrickmehaffy** [comment]
@nicokant can you provide some examples of this? The Json input has been completely redesigned by @Aurelsicoko & @soupette  last week

see: https://github.com/strapi/strapi/pull/1401
and
https://github.com/strapi/strapi/pull/1447

**Comment by jmp1548** [comment]
Found this while googling the same question. Not sure if this is what @nicokant meant, but I was looking for a default starting point for the json input. For example

Let's say you have a component you want to pass props into called header.

Make a json input called Header and then set the default to be something like this:

{
   logo: "",
   headline: "",
   subline: ""
   list: [ ]
}

By allowing for this default behavior, someone can duplicate the same structure every-time in the admin panel and have a starting point to enter values.

**Comment by Aurelsicoko** [comment]
@soupette can you confirm the JSON input isn't taking care of the default value?

**Comment by soupette** [comment]
It does know but only if you set the default value in your `<apiName>.settings.json`

For instance 

```
"attributes": {
  "json": {
    "type": "json",
    "default": { "ok": true }
  }
}
```

Shall we close this issue?

**Comment by nkmnz** [comment]
The suggested workaround to define the default value inside of `<apiName>.settings.json` works fine, but from the adminUI I get a 400 on my PUT request and the following response: 
`{"error":{"contentType.attributes.conclusion":["contentType.attributes.conclusion field cannot have keys not specified in the object shape"]}}`
Any idea?

**Comment by nkmnz** [comment]
I recant - the workaround does not work since every update of the content type via the UI deletes the default values in `<apiName>.settings.json`
