### ISSUE TITLE
Can't edit a json field when its value is false

### ISSUE THREAD

**Issue by wusuopu** [strapi/strapi#14587]
### Required System information
- Node.js version: v16.13.2
- Yarn version: 1.22.15
- Strapi version: 4.2.2
- Database: sqlite 3
- Operating system: Linux

### Describe the bug

it will occur a error when edit a json field which value is `false`.

### Steps to reproduce the behavior

1. Edit a json field, if its value is `true` or other value it will be ok.
![image](https://user-images.githubusercontent.com/1478284/194842654-3b85d06a-ee11-46bf-95bc-671d3ecb023c.png)

2. Change the value to `false` and save it.
![image](https://user-images.githubusercontent.com/1478284/194842834-3a18d65f-f8ae-44d9-80b8-5b20d3596f9a.png)

3. After save it, it will occur a error on this field when edit again.
![image](https://user-images.githubusercontent.com/1478284/194843352-221d8255-ceae-453c-9ba7-200e7c1e7aa0.png)

**Comment by gu-stav** [comment]
@wusuopu Thank you for opening this issue! I believe this might be fixed already by upgrading to the latest version of Strapi. Closing the issue in the meantime - in case it still does not work, feel free to ping me and I will re-open.
