### ISSUE TITLE
createCoreService => GenericService type typescipt issue

### ISSUE THREAD

**Issue by safweb89** [strapi/strapi#14586]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I was trying to create a custom service and i faced a typescript issue whith my service methods return types

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@strapi/strapi/lib/core-api/service/index.d.ts b/node_modules/@strapi/strapi/lib/core-api/service/index.d.ts
index 850660d..9944cac 100644
--- a/node_modules/@strapi/strapi/lib/core-api/service/index.d.ts
+++ b/node_modules/@strapi/strapi/lib/core-api/service/index.d.ts
@@ -21,5 +21,5 @@ export interface CollectionTypeService extends BaseService {
 export type Service = SingleTypeService | CollectionTypeService;
 
 export type GenericService = Partial<Service> & {
-  [method: string | number | symbol]: <T = any>(...args: any) => T;
+  [method: string | number | symbol]: <T = any>(...args: any) => any;
 };
```

**Comment by jeromeheissler** [comment]
Also solved with that solution : https://github.com/strapi/strapi/issues/14035#issuecomment-1246635209

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
