### ISSUE TITLE
Server fails to restart in development after modifying the code

### ISSUE THREAD

**Issue by sinamoradi1375** [strapi/strapi#14581]
### Required System information

- Node.js version: 16.14.0
- Yarn version: 1.22.19
- Strapi version: 4.4.3
- Operating system: Windows 10 x64

### Describe the bug
Hi everyone, I've successfully migrated my Strapi project to typescript recently. I've also configured Winston loggers in `config/logger.ts` (I've added the implementation in the code snippets section)

When I run `yarn develop`, the compilation of Strapi is done successfully and a folder gets created in the `dist` folder called `logs`  with two files named `http.log` and `error.log`. 
I need the logs directory to be deleted as well and the server gets restarted easily.
I've also excluded the `logs` directory in both `tsconfig.json` and `watchIgnoreFiles` property in `config/admin.ts`.

So here's the thing: when I change the server code and wait for the reload, the following error is printed in the terminal: 
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOTEMPTY: directory not empty, rmdir 'D:\Repositories\Gitlab\lumos-cms\backend\dist\logs'
```
So I need to stop Strapi and start it again.
I've also tried running it as an administrator but didn't help.
Any thoughts on this?

### Screenshots
![image](https://user-images.githubusercontent.com/38537095/194751284-d5ab7fd3-7d3c-422b-9332-b46181fa20be.png)
![image](https://user-images.githubusercontent.com/38537095/194751291-8fb104eb-0548-42af-aecb-43b301021747.png)

### Code snippets

```typescript
/*config/logger.ts*/

import { winston, formats } from "@strapi/logger";
import path from "path";

const { prettyPrint, levelFilter } = formats;

export default {
  transports: [
    new winston.transports.Console({
      level: "http",
      silent: process.env.RUN_CONSOLE_LOGGER_IN_SILENT_MODE === "true",
      format: winston.format.combine(
        levelFilter("http"),
        prettyPrint({ timestamps: "YYYY-MM-DD hh:mm:ss.SSS" })
      ),
    }),
    new winston.transports.File({
      filename: path.join(__dirname, "../logs/http.log"),
      level: "http",
      silent: process.env.RUN_HTTP_LOGGER_IN_SILENT_MODE === "true",
      format: winston.format.combine(
        winston.format.uncolorize(),
        winston.format((info) => {
          try {
            // Only log messages containing status code greater than or equal to 400
            if (parseInt(info.message.slice(-3)) < 400) return false;

            return info;
          } catch (error) {
            console.log(error, "error happened while logging");
            return info;
          }
        })(),
        levelFilter("http"),
        prettyPrint({ timestamps: "YYYY-MM-DD hh:mm:ss.SSS" }),
        winston.format.uncolorize()
      ),
    }),
    new winston.transports.File({
      filename: path.join(__dirname, "../logs/error.log"),
      level: "error",
      silent: process.env.RUN_ERROR_LOGGER_IN_SILENT_MODE === "true",
      format: winston.format.combine(
        levelFilter("error"),
        prettyPrint({ timestamps: "YYYY-MM-DD hh:mm:ss.SSS" }),
        winston.format.uncolorize(),
        winston.format.json()
      ),
    }),
  ],
};

```

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
