### ISSUE TITLE
Strapi v4 customize page using patch-package

### ISSUE THREAD

**Issue by nicswebdev** [strapi/strapi#14595]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.4.3
- Database: MySQL
- Operating system: Windows 10

### Describe the bug

I want to change the text inside login page with my custom text. I make some changes on `node_modules/@strapi/admin/src/pages/AuthPage/components/Login/BaseLogin.js`

Before editing that file, I install patch-package dependencies into my project. Inside project package.json file I added `"postinstall": "patch-package"` too.

After make some changes on file, I run this command `yarn patch-package @strapi/admin`

After finished I saw there are patches folder created and inside that folder I can saw the file which have diff code.

But, when I re run the strapi admin frontend, on login page text which I already changed still display original text from strapi.

Is there any mistakes I made on the steps ?

I used strapi version 4.4.3

Thanks before.

### Steps to reproduce the behavior

1. Go to `node_modules/@strapi/admin/src/pages/AuthPage/components/Login/BaseLogin.js` and change the login welcome text
2. Add `"postinstall": "patch-package"` inside package.json file under the scripts
3. Add patch-package dependencies using `yarn add patch-package postinstall-postinstall`
4. Run `yarn patch-package @strapi/admin`

### Expected behavior

The text in login page showing like what I've change.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
