### ISSUE TITLE
The case-ignoring filter does not work if Cyrillic is used

### ISSUE THREAD

**Issue by devcustrom** [strapi/strapi#14597]
## Bug report
The case-ignoring filter does not work if Cyrillic is used.

### Required System information
- Node.js version: v16.13.1
- PNPM version: 7.13.2
- Strapi version: 4.4.3
- Database: SQLite(default)
- Operating system: windows 11

### Describe the bug
We have such data
```json
[
  {
    "id": 1,
    "username": "Иван"
  }
]
```
and we make such a request
/api/users?filters[username][$eqi]=иван
or
/api/users?filters[username][$containsi]=ив

But we won't get the required object in the response

**Comment by WalkingPizza** [comment]
This might be an encoding/collation issue with your DB rather than a Strapi issue.

Both `$containsi` and `$eqi` are converted to SQL queries that use the the `LOWER` function.
If your database has the wrong collation config, the `LOWER` function does not know how to process Cyrillic characters, and therefore does not transform them to lowercase and breaks your filters.

**Comment by devcustrom** [comment]
> This might be an encoding/collation issue with your DB rather than a Strapi issue.
> 
> Both `$containsi` and `$eqi` are converted to SQL queries that use the the `LOWER` function.
> If your database has the wrong collation config, the `LOWER` function does not know how to process Cyrillic characters, and therefore does not transform them to lowercase and breaks your filters.

but I use the standard starpi with sqlite, without any settings

**Comment by derrickmehaffy** [comment]
https://www.sqlitetutorial.net/sqlite-functions/sqlite-lower/

![image](https://user-images.githubusercontent.com/8593673/199265013-8d53dac9-43c4-47ce-a0f2-ada787877340.png)

We create SQLite DBs with the UTF8 encoding and Cyrillic is not ASCII so the lower option won't work here, it's isn't something that we can really fix as it's a limit of SQLite. I would suggest using an actual database and swapping that databases encoding option: https://dev.mysql.com/doc/refman/8.0/en/charset-cyrillic-sets.html (don't forget to change the encoding setting in the knex config also, which is in our database.js file with the `charset` key).

I'm marking this as closed as it's not an issue with us but implementations in upstream libs and projects
