### ISSUE TITLE
Strapi getting error when loading dynamic zones Components

### ISSUE THREAD

**Issue by NguyenSon2310** [strapi/strapi#14594]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.4.3
- Database: Postgresql
- Operating system: Ubuntu 22.04

### Describe the bug

After migrate Strapi from v3 to v4 and migrate database, when I load dynamic zones components I have error like this, anyone seen it before?

### Steps to reproduce the behavior
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33917382/195001514-0f4b0385-58ba-4ac8-8e77-4a2be8c6b84e.gif)

### Detail of bugs
![Screenshot from 2022-10-10 11-58-02](https://user-images.githubusercontent.com/33917382/195001565-f69c6780-4955-464d-b671-c41bcca62a99.png)

After setup babel-plugin-formatjs like the error said
I have error like that when I run **yarn develop --watch-admin**
![Screenshot from 2022-10-12 16-40-10](https://user-images.githubusercontent.com/33917382/195311348-91f5cc24-6cea-4707-9d58-adc220449120.png)
![Screenshot from 2022-10-12 16-40-26](https://user-images.githubusercontent.com/33917382/195311379-2618c9a5-656b-43b7-b7ff-b7bac7431bf7.png)

**Comment by derrickmehaffy** [comment]
Unable to reproduce this, can you provide some more information? Maybe your code base so I can try to reproduce this?

Since we don't have enough information I'll mark this as closed but if you have new information and respond here I can reopen it.
