### ISSUE TITLE
Upload "Files Are Empty"

### ISSUE THREAD

**Issue by mwong-combo** [strapi/strapi#14609]
### Required System information

- Node.js version: 16
- NPM version: 8.19.2
- Strapi version: 4.4.3
- Database: PostgresSQL
- Operating system: MacOS

### Describe the bug

Upload was working regular as usual until recently when I tried uploading an image. 

Axios is returning an error message "Files are empty". So I don't necessarily think this is a provider issue but more so first uploading to Strapi. But just to provide info, I am using s3 as a provider.

### Steps to reproduce the behavior

1. Go to Media Library
2. Upload an image

### Expected behavior

Image should be uploaded successfully

### Screenshots

<img width="1511" alt="Screen Shot 2022-10-12 at 3 13 22 PM" src="https://user-images.githubusercontent.com/109992655/195429935-e05cee5a-2618-447a-b896-0ac532068018.png">

### Additional context

Again it was working perfectly before but all of sudden this occurred! As an added context, I did have a production version of my Strapi instance running as well. Could there have been some weird error that messed with database configurations?

Also I tried resetting everything again locally by setting up a new Strapi instance (same DB) and it worked! But after I tried testing it on the production instance that was still running a previous version of my application, it broke again. And now I can't upload on either environment.

**Comment by mwong-combo** [comment]
Actually I think this could because I npm installed Axios to be the latest version. This may have made Strapi use the parent level Axios version causing things to work incorrectly. I think I should be good now.

**Comment by mikaoelitiana** [comment]
I confirm `axios > 0.27.2` breaks the file upload. I had `axios@1.1.3` installed and reverting to `0.27.2` fixed the issue.

**Comment by s-stude** [comment]
Any ideas if strapi will fix this so any version of axios could be used?
