### ISSUE TITLE
Strapi v4, missing or invalid credentials

### ISSUE THREAD

**Issue by smurfens** [strapi/strapi#14602]
I have my Strapi app deployed to Railway and my React frontend in a AWS S3 bucket. 

Everything is working fine but after a while of not accessing the strapi adminpanel I a will get a 401 missing or invalid credentials from the strapi api in my frontend. 

I can access the api from a postman or just via browser but not the frontend. 

This will all be resovled by just logging in to strapi again... havnt seen anyone else with this problem online.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
