### ISSUE TITLE
Support for MSSQL database

### ISSUE THREAD

**Issue by maturano** [strapi/strapi#1462]
**What is the expected behavior?**
Knex has support for MSSQL. What do you need to have that same support in Strapi?

In a quick test, everything seems to work once the database is created. So, the first impediment would be the initialization of the table scheme.

Currently, we are [creating manually the queries for this](https://github.com/strapi/strapi/blob/5a156adf8b659fb7b8086dbab5ae280fd1d8cb6a/packages/strapi-bookshelf/lib/index.js#L450). Why are not we  using the [`createTable` knex's method](https://knexjs.org/#Schema-createTable) for this? :thinking: 

What other problems will I found when using MSSQL as a database?

**Comment by lauriejim** [comment]
Actually we are focused on MySQL, Postgres and Mongo. Feel free ton investigate on how you can make MSSQL work.

**Comment by maturano** [comment]
I will. I just ask for point me in the right direction; help understanding the current implementation.

My first block is the raw queries on `strapi-bookshelf`. I will try change them using the knex´s API. Is there some reason it is not used now? Is that the correct approach?

**Comment by derrickmehaffy** [comment]
@maturano I spoke with @lauriejim on slack about this, he agreed that they should be moved over to use the knex API but at the moment it isn't a high priority for them. If you are interested in doing so I'm sure they would appreciate it. Based on the knex documentation it shouldn't be too terribly difficult to support MSSQL.

**Comment by maturano** [comment]
Excellent! I will work on it and I´ll send a PR when I have something 👍

**Comment by derrickmehaffy** [comment]
Sounds good!
