### ISSUE TITLE
Can't custom base url

### ISSUE THREAD

**Issue by dotkiro** [strapi/strapi#14622]
### Required System information

- Node.js version: 16.15.1
- NPM version:8.11.0
- Strapi version:4.4.3
- Database:mydql
- Operating system:windows 12

### Steps to reproduce the behavior

1. Go to 'config/server.ts'
2. set 'url:cms'
3. npm run develop
4. open browser
5. See error

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by dotkiro** [comment]
> ## Bug report
> ### Required System information
> * Node.js version: 16.15.1
> * NPM version:8.11.0
> * Strapi version:4.4.3
> * Database:mydql
> * Operating system:windows 12
> 
> ### Describe the bug
> Set the base url, can't open administration panel
> 
> ### Steps to reproduce the behavior
> 1. Go to 'config/server.ts'
> 2. set url: 'cms'
> 3. npm run develop
> 4. open browser
> 5. See error

**Comment by derrickmehaffy** [comment]
`set url: 'cms'` 

As mentioned in our documentation, the server URL should be absolute, not relative.

https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/server.html#available-options

> An absolute url is however recommended.

**Comment by dotkiro** [comment]
> `set url: 'cms'`
> 
> As mentioned in our documentation, the server URL should be absolute, not relative.
> 
> https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/server.html#available-options
> 
> > An absolute url is however recommended.

Still not working

**Comment by derrickmehaffy** [comment]
I need more information to try and reproduce the issue other than "it's not working" please.

**Comment by dotkiro** [comment]
> I need more information to try and reproduce the issue other than "it's not working" please.



```shell
PS D:\Codes> npm create strapi-app@latest strapi-cms
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Ok to proceed? (y) y
? Choose your installation type Custom (manual settings)
? Choose your preferred language
? Choose your preferred language TypeScript
? Choose your default database client (Use arrow keys)
? Choose your default database client sqlite
? Filename: (.tmp/data.db)
? Filename: .tmp/data.db

Creating a project with custom database options.
Creating a new Strapi application at D:\Codes\strapi-cms.
Creating files.
Dependencies installed successfully.

Your application was created at D:\Codes\strapi-cms.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.
  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd D:\Codes\strapi-cms
  yarn develop

PS D:\Codes> cd .\strapi-cms\
PS D:\Codes\strapi-cms> ls


    目录: D:\Codes\strapi-cms


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2022/10/26     10:49                config
d-----        2022/10/26     10:49                database
d-----        2022/10/26     10:51                node_modules
d-----        2022/10/26     10:49                public
d-----        2022/10/26     10:49                src
-a----        2022/10/26     10:49            249 .editorconfig
-a----        2022/10/26     10:49            214 .env
-a----        2022/10/26     10:49            144 .env.example
-a----        2022/10/26     10:49           1162 .gitignore
-a----        2022/10/26     10:49            497 favicon.png
-a----        2022/10/26     10:49            656 package.json
-a----        2022/10/26     10:49           2279 README.md
-a----        2022/10/26     10:49            368 tsconfig.json
-a----        2022/10/26     10:51         476353 yarn.lock
```

then `config\server.ts`
```ts
export default ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  app: {
    keys: env.array("APP_KEYS"),
  },

  // add this
  url: "/cms",
});

```

```sh
PS D:\Codes\strapi-cms> npm run develop
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> strapi-cms@0.1.0 develop
> strapi develop

Starting the compilation for TypeScript files in D:\Codes\strapi-cms
Building your admin UI with development configuration...
Admin UI built successfully

 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Wed Oct 26 2022 11:33:46 GMT+0800 (中国标准时间) │
│ Launched in        │ 826 ms                                           │
│ Environment        │ development                                      │
│ Process PID        │ 7660                                             │
│ Version            │ 4.4.5 (node v16.15.1)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/cms/admin

To access the server ⚡️, go to:
http://localhost:1337/cms
```

go to `http://localhost:1337/cms/admin` and go on 
```sh
[2022-10-26 11:34:04.478] http: GET /cms/admin (15 ms) 200
[2022-10-26 11:34:04.682] http: GET /admin/project-type (5 ms) 200
[2022-10-26 11:34:04.793] http: GET /admin/init (3 ms) 200
[2022-10-26 11:34:04.805] http: GET /admin/telemetry-properties (1 ms) 200
[2022-10-26 11:34:27.352] http: POST /admin/login (100 ms) 200
[2022-10-26 11:34:27.369] http: GET /admin/6925.f5c8b6fc.chunk.js (2 ms) 404
[2022-10-26 11:34:27.375] http: GET /admin/9166.8fcb3019.chunk.js (3 ms) 404
[2022-10-26 11:34:27.376] http: GET /admin/Admin-authenticatedApp.0148e33c.chunk.js (3 ms) 404
```

go to `http://localhost:1337/cms`

```sh
[2022-10-26 11:34:42.829] http: GET /cms (3 ms) 404
```

1. got `404`
2. `/cms` not work; request `/admin/...`

**Comment by derrickmehaffy** [comment]
> url: "/cms",

Can you change this to an absolute URL? Also for sub-path proxying you will need something like Nginx, HAProxy, Caddy, or something else like that. If you just want to use a subdomain that you don't need the proxy (though you would want it for SSL termination)

**Comment by eyelash** [comment]
I just submitted a more detailed report for this bug: #15948.
