### ISSUE TITLE
Email Confirmation: Invalid token on the second request

### ISSUE THREAD

**Issue by zockerwurf** [strapi/strapi#14627]
### Required System information

- Node.js version: >=12.x.x <=16.x.x
- NPM version: >=6.0.0
- Strapi version: 4.3.6
- Database: sqlite
- Operating system: Windows

### Describe the bug

When a user creates a new account, he gets a email with a confirmation-link (with a token inside). If the user clicks this link twice, he gets an error the second time, looking on an json-response (no styled interface). The message is:
`{"data":null,"error":{"status":400,"name":"ValidationError","message":"Invalid token","details":{}}}`

### Steps to reproduce the behavior

1. Register a new user using the users-permissions-plugin
2. Click on the email-confirmation-link in the received email.
3. Click another time on the same link.

### Expected behavior

The first time the user is redirected:
`ctx.redirect(settings.email_confirmation_redirection || '/');`

I wish the user could be redirected too (p.e. to the login-form) if he clicks the confirmation-link the second time.

### Code snippets

/config/sync/core-store.plugin_users-permissions_email.json:
`
    "email_confirmation": {
      "display": "Email.template.email_confirmation",
      "icon": "check-square",
      "options": {
        "from": {
          "name": "XXX",
          "email": "XXX"
        },
        "response_email": "XXX",
        "object": "Account confirmation",
        "message": "<p>Thank you for registering!</p>\n\n<p>You have to confirm your email address. Please click on the link below.</p>\n\n<p><%= URL %>?confirmation=<%= CODE %></p>\n\n<p>Thanks.</p>"
      }
`

**Comment by IJsLauw** [comment]
I would like to redirect the user as well, to a specified url would be great, thanks!

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Lauwisme** [comment]
Leaving this here for future reference:

https://github.com/strapi/strapi/blob/97e6bb4346343dc2ba76e12eb124d43d8ba7b17f/packages/plugins/users-permissions/server/controllers/auth.js#L368

This line is the cause of the problem, setting the token to null is that's why when the user clicks twice, the second time he get's rejected.

**Comment by IJsLauw** [comment]
https://feedback.strapi.io/feature-requests/p/redirect-a-user-after-confirmation-link-failed

**Comment by sebastianspiller** [comment]
I wrote a patch by extending the users-permissions plugin. Now, you can click the link multiple times and the invalid token error will not occur, but you will be redirected to the confirmation page:

`src/extensions/users-permissions/strapi-server.ts`
`
module.exports = (plugin) => {
  // copied from original auth code
  const sanitizeUser = (user, ctx) => {
    const { auth } = ctx.state;
    const userSchema = strapi.getModel("plugin::users-permissions.user");

    return strapi.contentAPI.sanitize.output(user, userSchema, { auth });
  };

  const rawAuth = plugin.controllers.auth({ strapi });
  const auth = ({ strapi }) => {
    return {
      ...rawAuth,
      emailConfirmation: async (ctx, next, returnUser) => {

        // i skipped the yup validation as it is just checking for string required of confirmation
        const confirmationToken =
          typeof ctx.query.confirmation === "string"
            ? ctx.query.confirmation
            : null;

        const userService = strapi.service("plugin::users-permissions.user");
        const jwtService = strapi.service("plugin::users-permissions.jwt");

        const [user] = await userService.fetchAll({
          filters: { confirmationToken },
        });

        if (user && !user.confirmed) {
          await userService.edit(user.id, {
            confirmed: true,
            confirmationToken: null,
          });
        }

        if (returnUser) {
          ctx.send({
            jwt: jwtService.issue({ id: user.id }),
            user: await sanitizeUser(user, ctx),
          });
        } else {
          const settings = (await strapi
            .store({
              type: "plugin",
              name: "users-permissions",
              key: "advanced",
            })
            .get()) as { email_confirmation_redirection?: string };

          ctx.redirect(settings.email_confirmation_redirection || "/");
        }
      },
    };
  };

  plugin.controllers.auth = auth;

  return plugin;
};
`
