### ISSUE TITLE
GraphQL Plugin: sorting isn't typed accurately

### ISSUE THREAD

**Issue by YassinEldeeb** [strapi/strapi#14638]
The getting started template on this repo works great as a reproducible example: https://github.com/strapi/strapi/tree/main/examples/getstarted

### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.3.6
- Database: PostgreSQL
- Operating system: MacOS

### Describe the bug

When sorting there's no type-safety, you just type a string and hope that it's a field. a possible improvement for this would be to generate all of the fields combined with `DESC` and `ASC` as enum variants in the graphql schema

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/graphql`
2. Query a content type and try to sort it
3. It's of type `[String]` so no auto-completion/validation is provided

### Expected behavior

I think this is a much better experience
```graphql
{
    movies(sort: [rating_ASC, date_DESC]) {...}
}
```

### Screenshots

<img width="327" alt="Untitled" src="https://user-images.githubusercontent.com/72823042/196126599-4847d4f2-90e1-4060-a835-52867a602b36.png">

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
