### ISSUE TITLE
Graphql 'Create endpoint' not working properly with user-permission-user relationship

### ISSUE THREAD

**Issue by zirho** [strapi/strapi#14634]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Yarn : 1.22.19
- Strapi version: 4.4.3
- Database: sqlite (default)
- Operating system: mac os

### Describe the bug

I've created a new collection type Map

it has a relationship with user-permissions-user one to one.

graphql endpoint allow me to call mutate like below
```
mutation CreateTest {
  createMap (data: { user: 1 }) {
    data {
      id
      attributes {
        user {
          data {
            id
          }
        } 
      }
    } 
  }
}
```

This does not attach the user to the new object created.

![image](https://user-images.githubusercontent.com/1251296/196005126-de790edb-5cf2-439a-9cb0-6a21806798f2.png)

### Steps to reproduce the behavior

1. run
```
npx create-strapi-app@latest strapi-test --quickstart
cd strapi-test
yarn add @strapi/plugin-graphql
```
2. create a collection type with user-permission-user relationship one to one
2. allow public to update map
3. make graphql query as above
4. check out the new record created without user attached to it.

### Expected behavior

new record created should have user attached to it.

### Screenshots

![image](https://user-images.githubusercontent.com/1251296/196005312-b3f16fff-573f-43b1-b803-7c92b8728325.png)

![image](https://user-images.githubusercontent.com/1251296/196005391-bf7ca219-1162-43a9-8f92-2f39a0f41a12.png)

![image](https://user-images.githubusercontent.com/1251296/196005395-8095f5be-636e-42a0-91f9-f723ef552b61.png)

![image](https://user-images.githubusercontent.com/1251296/196005126-de790edb-5cf2-439a-9cb0-6a21806798f2.png)

![image](https://user-images.githubusercontent.com/1251296/196005418-868a7341-ddd6-4fed-ab23-3ffa16ac5470.png)

### Code snippets

[fresh install strapi showing issue ](https://github.com/zirho/strapi-issue-user-map)

You can clone and start it and query to see the issue.

**Comment by bolg55** [comment]
This is not a bug -> You need to go to Settings > Users & Permissions Plugin Roles > Edit public role and under the U&P section, be sure to enable crud for user:

<img width="486" alt="Screen Shot 2022-11-01 at 12 43 45 PM" src="https://user-images.githubusercontent.com/43022248/199288753-05a67b55-57c2-493c-baea-b2db7de335cd.png">

Doing this, I was able to create a map and have it attach a previously created test user with the id of 1:

<img width="976" alt="Screen Shot 2022-11-01 at 12 44 32 PM" src="https://user-images.githubusercontent.com/43022248/199288909-e96e9e22-fef4-4160-9551-097979478b83.png">

**Comment by zirho** [comment]
Thanks @bolg55 
I appreciate it
