### ISSUE TITLE
Strapi upgrade removes roles and locales

### ISSUE THREAD

**Issue by shoaibmerchant** [strapi/strapi#14632]
### Required System information

- Node.js version: 14.19.3
- NPM version: 6.14.17
- Strapi version: 4.4.3
- Database: MySQL on RDS
- Operating system: Amazon AMI

### Describe the bug

1. We were running Strapi 4.2.0, and also relying on the i18n plugin for managing locale wise content
2. We decided to upgrade to 4.4.3 today for a search issue that has recently been fixed.
3. When we start the server after npm install and build, we could see following issues - 
    3.1. We were using user & permissions plugin and found that all permissions for the Public User were deselected. So all APIs started throwing 403.
    3.2. The locales got deleted other than the default (en), and all content tables with locale column got set to null.
5. **Note - we did not run ``npm run develop`` and rather ran the upgrade directly on CI on a staging environment. Not sure if that makes any difference.**
6. In the logs I also see an entry -
```
 Error: ER_NO_SUCH_TABLE: Table 'test_db.upload_folders' doesn't exist
```

### Steps to reproduce the behavior

1. Create a strapi application with 4.2.0, use user permissions plugin and i18n plugin
2. Migrate to 4.4.3, check if database is migrated successfully.

### Expected behavior

Strapi should have updated to 4.4.3 and all database should have migrated.  Also i suggest that the locales foreign key should not be SET NULL but NO ACTION. Open for comments.

### Screenshots

Attached logs - [web.stdout.log](https://github.com/strapi/strapi/files/9787848/web.stdout.log)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
I tried to reproduce this and was even digging through the log you attached but cannot see where Strapi wiped this information (you had database debugging on) so I don't think this issue was caused by Strapi to be entirely honest.

If you can provide more detailed reproduction steps I can reopen this but for the moment I can't reproduce and I'm not entirely sure how you even got into this state or what migration you ran via CI/CD

**Comment by shoaibmerchant** [comment]
Hey @derrickmehaffy thanks for looking into this, I will try the upgrade a couple of times more on a cloned database and see if it is consistently reproducible.

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy thanks for looking into this, I will try the upgrade a couple of times more on a cloned database and see if it is consistently reproducible.

Please and thank you, if you are able to reproduce it do ping me and I can reopen this
