### ISSUE TITLE
GraphQL Plugin: filtering a field of type enum doesn't trigger any auto-completion for equality

### ISSUE THREAD

**Issue by YassinEldeeb** [strapi/strapi#14639]
The getting started template on this repo works great as a reproducible example: https://github.com/strapi/strapi/tree/main/examples/getstarted

### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.3.6
- Database: PostgreSQL
- Operating system: MacOS

### Describe the bug

When filtering on a field of type Enum, you get all of the matchers as type String instead of the enum type for that field and have auto-completion and validation when writing variants. Instead of using `StringFilterInput` for every field filtering, there should be a customly generated type for each field that's of type enum.

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/graphql`
2. Query a content type and try to filter it by an enum field
3. It's of type `String` so no auto-completion/validation is provided

### Expected behavior

There should be a customly generated type for each field that's of type enum.

### Screenshots

<img width="442" alt="Untitled(1)" src="https://user-images.githubusercontent.com/72823042/196129297-a405c2d1-d95f-4a30-a616-5e5634ea8939.png">

### Code snippets

Instead of `StringFilterInput` for enum filtering:
```graphql
input StringFilterInput {
  and: [String]
  or: [String]
  not: StringFilterInput
  eq: String
  eqi: String
  ne: String
  startsWith: String
  endsWith: String
  contains: String
  notContains: String
  containsi: String
  notContainsi: String
  gt: String
  gte: String
  lt: String
  lte: String
  null: Boolean
  notNull: Boolean
  in: [String]
  notIn: [String]
  between: [String]
}
```

This gives a better gql experience cause now we get auto-completion and validation on the filtering inputs for fields of type enum:
```graphql
input AddressColorEnumFilterInput {
  and: [ColorEnum]
  or: [ColorEnum]
  not: AddressColorEnumFilterInput
  eq: ColorEnum
  eqi: ColorEnum
  ne: ColorEnum
  startsWith: String
  endsWith: String
  contains: String
  notContains: String
  containsi: String
  notContainsi: String
  gt: String
  gte: String
  lt: String
  lte: String
  null: Boolean
  notNull: Boolean
  in: [ColorEnum]
  notIn: [ColorEnum]
  between: [ColorEnum]
}
```

**Comment by derrickmehaffy** [comment]
related to: https://github.com/strapi/strapi/pull/12200 and https://github.com/strapi/strapi/issues/13165

specifically: https://github.com/strapi/strapi/pull/12200#discussion_r786120685
