### ISSUE TITLE
Can't update user permissions for a plugin

### ISSUE THREAD

**Issue by link82** [strapi/strapi#14641]
### Required System information

- Node.js version: 16.13.0
- Yarn version: 1.22.19
- Strapi version: 4.4.3
- Database: postgreSQL
- Operating system: OSX

### Describe the bug

Can't change admin user permissions for installed plugins. I tried both with standard plugins and community plugins but every change is inhibited.

### Steps to reproduce the behavior

1. `npx create-strapi-app@latest test-project`
2. Setup application using javascript / postgres
3. Create your database and start up dev server using `yarn develop`
4. Visit [Strapi admin panel](http://localhost:1337/admin) and create your Super admin user
5. Go to "Settings > (Administration panel) Roles > Editor" and choose edit
6. Move to "Plugins" tab and try to change any permission.

I am facing the same problem also with community plugins.

I tried to look for hints on Strapi documentation with no luck.

### Expected behavior

I expect to able to customize roles user permissions, for installed plugins.

### Screenshots

[https://imgur.com/a/6jL03Jj](url)

**Comment by derrickmehaffy** [comment]
This is limited by the RBAC, we plan to make this free very shortly: https://feedback.strapi.io/feature-requests/p/free-rbac-community-edition

**Comment by link82** [comment]
Ok, thank you.
