### ISSUE TITLE
REST/GraphQL Plugin: can't search by unique constraints when using the singular version of fetching a content-type

### ISSUE THREAD

**Issue by YassinEldeeb** [strapi/strapi#14640]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.3.6
- Database: PostgreSQL
- Operating system: MacOS

### Describe the bug

Can’t search by unique constraints when using the singular version of fetching a content-type. Only the id is allowed. To search by the slug in that case the only option is to use the plural version of `address` aka. `addresses` and index the first item in that array which actually might be the internal solution for this if it was some sort of an internal limitation.

### Steps to reproduce the behavior

1. Go to `http://localhost:1337/graphql`
2. Query a content type, specifically the singular version of it and try to search by a unique field on that content type.
3. You'll see that only the ID is the field that can help you find something.

### Expected behavior

I should be able to search a single row by unique fields on that content-type I'm quering.

### Screenshots

<img width="903" alt="Untitled(2)" src="https://user-images.githubusercontent.com/72823042/196131417-4009f3f3-d7d5-49d4-ab4a-2362f64bfe35.png">

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
