### ISSUE TITLE
macbook instrall error

### ISSUE THREAD

**Issue by 405482116** [strapi/strapi#14644]
when run ```npx create-strapi-app@latest my-project --quickstart```

then will show below error  **/node_modules/sharp: Command failed.**

**Comment by tarnveerSingh** [comment]
can you post with the screenshot of the error as well

**Comment by Theebanraj-Uthayakumar** [comment]
Hi, it seems you don't have build tools like make to build one of the dependencies for image processing :) On mac they can be installed with an xcode util easily. https://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/
Once done retry & let me know if this fixed it for you :)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
