### ISSUE TITLE
Discussion: Why JavaScript with JSDoc type regestries instead of TypeScript for the codebase(esp: GQL plugin)?

### ISSUE THREAD

**Issue by YassinEldeeb** [strapi/strapi#14642]
So I started contributing to fix some of the issues I had with strapi specifically with the graphql plugin and something amazed me which was "JSDoc type registries instead of TypeScript", I wonder about this design decision and what's the reason behind it?

If any of you wanna chat for a bit I'd really appreciate knowing the reason behind this crucial technical decision and thanks in advance! ☕️

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
