### ISSUE TITLE
GraphQL Update and Delete mutations for single type ignores locale param

### ISSUE THREAD

**Issue by alexcho267** [strapi/strapi#14662]
### Required System information

- Node.js version: v16.17.1
- NPM version: v8.15.1
- Strapi version: v4.4.3
- Database: MySQL - production and SQLite - locally
- Operating system: GCP Cloud Run - production and macOSx - locally

### Describe the bug

My setup uses both the GraphQL and i18n plugins. Issue occurs when trying to execute an Update or Delete mutation of a single type using the locale parameter. Instead of updating or deleting the locale specific record it executes the mutation on the default locale.

### Steps to reproduce the behavior

1. Go to Settings->Internationalization
2. Ensure there is a default locale and several other locales added and saved
3. Set up a single content type with a few fields
4. Add content to single content type for default locale and several other locales
5. Go to Playground (URL/graphql)
6. Run an update/delete mutation with a locale parameter added
7. See error that mutation is applied to default instead of the locale specified

### Expected behavior

Expectation is that the localized record specified by the locale parameter is updated or deleted and not the default locale. See code snippet and json blob below.

### Code snippets

```
mutation testData($data: TestDataInput!, $locale: I18NLocaleCode) {
  updateTestData(data: $data, locale: $locale) {
    data {
      attributes {
        locale 
        title
        localizations {
          data {
            attributes {
              title
              locale
            }
          }
        }
      }
    }
  }
```

```
{ "locale": "fr-FR", "data": { "title": "test title"}} 
```

**Comment by kasonde** [comment]
The problem is [here](https://github.dev/strapi/strapi/blob/0aec9b313e84cebcbd4d2cae07cdd3837003f20b/packages/plugins/graphql/server/services/builders/mutations/single-type.js#L57). It's only high sev for now because there is no workaround technically. `locale` is not a valid `findParameter` for findMany or any operation according to the docs.
