### ISSUE TITLE
Cannot find module 'react-select/animated' when using with Turborepo and Chakra UI

### ISSUE THREAD

**Issue by TimLanzi** [strapi/strapi#14661]
## Bug report
I get the following error when I create a Strapi app with Turborepo. It does not happen until after I install Chakra UI in another of my monorepo's applications:

```bash
cms:build: Error: Cannot find module 'react-select/animated'
cms:build: Require stack:
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\webpack.alias.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\webpack.config.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\utils\get-custom-webpack-config.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\utils\index.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\index.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\strapi\lib\commands\builders\admin.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\strapi\lib\commands\builders\index.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\strapi\lib\commands\build.js
cms:build: - D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\strapi\bin\strapi.js
cms:build:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
cms:build:     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
cms:build:     at D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\webpack.alias.js:51:25
cms:build:     at Array.reduce (<anonymous>)
cms:build:     at Object.<anonymous> (D:\Projects\strapi-turbo-bug-test\node_modules\@strapi\admin\webpack.alias.js:50:12)
cms:build:     at Module._compile (node:internal/modules/cjs/loader:1126:14)
cms:build:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
cms:build:     at Module.load (node:internal/modules/cjs/loader:1004:32)
cms:build:     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
cms:build:     at Module.require (node:internal/modules/cjs/loader:1028:19)
```
It doesn't look like react-select is a dependency of @strapi/admin after taking a look at that package.json.

### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0 (but I am using Yarn version: 1.22.19)
- Strapi version: 4.4.3
- Database: SQLite
- Operating system: Windows 10 as well as Pop OS 22.04

### Describe the bug
When using Strapi in Turborepo, an error occurs on build saying Strapi can't find 'react-select/animated'. This occurs when another app in the monorepo is using Chakra UI.

### Steps to reproduce the behavior
1. Create new Turborepo:
```bash
npx create-turbo@latest

# Answers to prompts
? Where would you like to create your turborepo? [anywhere]
? Which package manager do you want to use? yarn
```

2. Create Strapi app in monorepo:
```bash
cd apps
npx create-strapi-app@latest cms

# Answers to prompts
? Choose your installation type Quickstart (recommended)
```

3. Install Chakra UI to separate app in monorepo:
```bash
cd ..
# Package versions copy/pasted from Chakra UI docs: https://chakra-ui.com/getting-started/nextjs-guide
yarn workspace web add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6
```

4. A build will work at this point:
```bash
yarn build
```
However, after another yarn install, the build will fail on the Strapi app:
```bash
yarn install
yarn build --force
```

### Expected behavior
Strapi should build without error.

**Comment by virtenv** [comment]
The same error when I use "@sklinet/strapi-plugin-tinymce":"1.0.4"

Error: Cannot find module 'react-select/animated'
Require stack:
- /opt/node_modules/@strapi/admin/webpack.alias.js
 - /opt/node_modules/@strapi/admin/webpack.config.js
 - /opt/node_modules/@strapi/admin/utils/get-custom-webpack-config.js
 - /opt/node_modules/@strapi/admin/utils/index.js
 - /opt/node_modules/@strapi/admin/index.js
 - /opt/node_modules/@strapi/strapi/lib/commands/builders/admin.js
 - /opt/node_modules/@strapi/strapi/lib/commands/builders/index.js
 - /opt/node_modules/@strapi/strapi/lib/commands/develop.js
 - /opt/node_modules/@strapi/strapi/bin/strapi.js
   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
   at Function.resolve (node:internal/modules/cjs/helpers:109:19)
   at /opt/node_modules/@strapi/admin/webpack.alias.js:51:25
   at Array.reduce (<anonymous>)
   at Object.<anonymous> (/opt/node_modules/@strapi/admin/webpack.alias.js:50:12)
   at Module._compile (node:internal/modules/cjs/loader:1155:14)
   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
   at Module.load (node:internal/modules/cjs/loader:1033:32)
   at Function.Module._load (node:internal/modules/cjs/loader:868:12)
   at Module.require (node:internal/modules/cjs/loader:1057:19)

**Comment by imklau** [comment]
I used Strapi with Next.js template and got the same error too. I don't believe it's related to Chakra UI or Turborepo.
Installing `react-select` as a dependency was a temporary fix for me 😬

**Comment by joshuaellis** [comment]
Can I check you're using yarn 1 or NPM?

**Comment by TimLanzi** [comment]
I'm using Yarn 1
