### ISSUE TITLE
Cannot load SQL file of Strapi data into PostgreSQL from pg_dump

### ISSUE THREAD

**Issue by khaitruong922** [strapi/strapi#14672]
Strapi version: 4.4.0

I tried to export all the data from one PostgreSQL database to another. I use pg_dump to export a SQL script which is used to import data into the other database. Unfortunately, I got this error everywhere when I ran the script.

```
psql:backup.sql:28: ERROR:  role "admin" does not exist
```

Does anyone know how to fix this issue? If not, is there a way to move all Strapi data from a database to another?

**Comment by antokhio** [comment]
Hi, can say that I did that at list few times with pg_dump, psql ‘something’ and it was working like charm, this likely issue with the script, witch commands are u using exactly?

**Comment by khaitruong922** [comment]
@antokhio 

The commands are

```
pg_dump --db_name=$CONN_STRING > backup.sql
psql -U postgres -f backup.sql
```

**Comment by antokhio** [comment]
> @antokhio
> 
> Hi, here are the commands I used.
> 
> ```
> pg_dump --db_name=$CONN_STRING > backup.sql
> psql -U postgres -f backup.sql
> ```

Try:
```
pg_dump -U username -f backup.sql database_name
```

```
psql -d database_name -f backup.sql
```

**Comment by khaitruong922** [comment]
@antokhio 

I have already fixed the issue. I add the -O and -x flags in the pg_dump to not export the object ownership and the import works. Thanks anyway!
