### ISSUE TITLE
In Strapi 4.4.4 CORS strategy doesn't work anymore and throws 500 error

### ISSUE THREAD

**Issue by kwiat1990** [strapi/strapi#14675]
# Setup

- Node.js version: 16.14.2
- NPM version: 8.13.2
- Strapi version: 4.4.4
- Database: postgres
- Operating system: MacOS Monterey 12.6

### Describe the bug

After recently update from `4.4.3` to `4.4.4` responses with the following error while visiting `localhost:1337` or any other related URL:
```json
{
  "data": null,
  "error": {
    "status": 500,
    "name": "InternalServerError",
    "message": "undefined is not a valid origin"
  }
}
```

I have a custom CORS policy in `middleware.js` (see "step to reproduce" for the code), which did worked with previous versions. After update to `4.4.4` it seems to be broken. Using standard CORS config as `'strapi::cors'` fix the issue. 
 
### Steps to reproduce the behavior

1. Update Strapi to 4.4.4
2. Make sure to have custom CORS policy in `middleware.js`, e.g.:
```js
{
      name: "strapi::cors",
      config: {
        enabled: true,
        headers: "*",
        origin: env.array("ALLOWED_ORIGINS_URL"), // for example: http://localhost:3000,http://localhost:1337
      },
    },
```

### Expected behavior

Strapi works normally without any errors. Admin panel can be visited.

**Comment by Convly** [comment]
Hi, thanks for creating this issue.

It might be related to https://github.com/strapi/strapi/pull/14552

I'll take a look asap.

**Comment by Convly** [comment]
I was able to reproduce it.

**Comment by marcowuethrich** [comment]
Workaround (But be careful, nothing for prod environment):
`
{
    name: 'strapi::cors',
    config: {
      enabled: true,
      origin: [
        '*'
      ]
    }
  },
`

**Comment by Convly** [comment]
Missed the message from https://github.com/koajs/cors/pull/87#issuecomment-1272320436 saying it was, in fact, a breaking change. We'll have to fix that for the next release in any case (either by downgrading or fixing the middleware implementation).

@CleberRossi is it something you would be interested in providing a fix for?

**Comment by CleberRossi** [comment]
Hello, I checked and the fixed I had added was moved from koajs/cors 3.x.x and created one other 4.x.x

**Comment by Convly** [comment]
Yep, we're going to upgrade to koa/cors@3.4.3 as it contains the revert/fix and release 4.4.5 with it.
We will then work on upgrading it to 4.x.x by reworking a bit how our middleware works so that it doesn't break existing apps.

**Comment by Convly** [comment]
Fix released in [v4.4.5](https://github.com/strapi/strapi/releases/tag/v4.4.5)

**Comment by CleberRossi** [comment]
@Convly Thank you very much, Sorry for that. Did not realized they would be reverting commit and that would impact previous released made by us.

**Comment by Convly** [comment]
No worry @CleberRossi, it happens, and we should have caught it during the review.
Anyway, it's been fixed and happy to work on a fix for the original issue soon :slightly_smiling_face:

**Comment by kwiat1990** [comment]
Thank you guys for immediate feedback and the fix.
