### ISSUE TITLE
500 error when sorting by a non existing field in a content-type GET request 

### ISSUE THREAD

**Issue by christiancp100** [strapi/strapi#14671]
### Required System information

- Node.js version: v14.20.1
- NPM version: 6.14.17
- Strapi version: 4.4.3
- Database: sqlite
- Operating system: macOS Monterey 12.6 

### Describe the bug

When trying to sort by a field that does not exist in a ContentType through a GET request to the Strapi API, the response is a 500 error instead a 400.

### Steps to reproduce the behavior

1. Launch the getStarted example project in the Strapi repository
2. Create a couple of countries using the Content Manager
3. Create a request to sort them using a non existing field, such as: http://localhost:1337/api/countries?sort=doesntExist
4. See the 500 error.

### Expected behavior
When the request above is made, the error code should be 400, because it's a bad request. It shouldn't be an error in the server.

### Screenshots
<img width="887" alt="Screenshot 2022-10-19 at 12 43 43" src="https://user-images.githubusercontent.com/16720378/196670007-bc6019de-3d61-4d9a-a926-a88019dfe822.png">

The error displayed in the console:
<img width="977" alt="Screenshot 2022-10-19 at 12 41 57" src="https://user-images.githubusercontent.com/16720378/196669615-a4ccc3bd-f23d-4756-9d97-a3bcb1b76982.png">

### Code snippets
This is the cURL that I've used:

**Comment by prasoonmhwr** [comment]
May I work on this

**Comment by derrickmehaffy** [comment]
> May I work on this

@prasoonmhwr please read: https://github.com/strapi/strapi/issues/14577

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/14060
