### ISSUE TITLE
Request to follow Rest API Standard HTTP Methods

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1468]
**What is the expected behavior?**

Following this rough guide: https://restfulapi.net/http-methods/

I purpose that modifications should be done to the default routes, as well as adding the `PATCH` route by default.

Currently the `PUT` route is doing the work that typically in an API the `PATCH` route does in that you are able to patch a specific value without sending the entirety of the response.

In addition to this change I believe that, with validations (doesn't currently exist per the vote page), the `PUT` method should should do a "Update if exists, Create if not". Normally this is optional, but for the sake of building a standard use case API framework I feel it is important.

I have included some additional articles also discussing this topic:

- https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#restful
- https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#define-operations-in-terms-of-http-methods
- http://restful-api-design.readthedocs.io/en/latest/methods.html#patch-vs-put
- http://www.restapitutorial.com/lessons/httpmethods.html
- https://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/
- https://spring.io/understanding/REST

**Comment by derrickmehaffy** [comment]
As an addition to this topic, I believe some extra attention to applying the proper HTTP response codes to errors is also an important one, an example of such codes: https://www.restapitutorial.com/httpstatuscodes.html

There have been quite a few instances where a user error happens but the server responds with a 500 code (Server Error) such as forgetting a required field in a POST request which should normally respond with a 400 code.

**Comment by Aurelsicoko** [comment]
I 💯 agreed with this, it should be easy to implement but it will generate breaking changes on many projects...

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I do agree, but hopefully most will agree to follow normal API standards is fairly important.

That being said Strapi is Alpha so breaking changes should be common practice anyway :nerd_face:

**Comment by derrickmehaffy** [comment]
Marking this issue as closed as there is currently no roadmap plans to move towards a standard. Can be reopened should those plans be added to the roadmap
