### ISSUE TITLE
Custom Plugin Endpoint is missing in permissions

### ISSUE THREAD

**Issue by user3470** [strapi/strapi#14694]
### Required System information

Node LTS version (v18)
Strapi v4.4.3

- Node.js version: V18
- NPM version: 8.19.2
- Strapi version: 4.4.3
- Database: SQQlite
- Operating system: Ubuntu 22.04

### Custom Plugin Routes
After generated Custom plugin and added an Endpoint, when lookinging into the Admin UI under Settings >  USERS & PERMISSIONS PLUGIN  > Permissions Custom Plugin is not available to allow authentication

### Steps to reproduce the behavior

1.Generate Custom Plugin (CLI)
2. In src/plugins/[PluginName]/server/routes/index.js Add another route
3. In Admin UI go to Settings > USERS & PERMISSIONS PLUGIN > [Any Role] > Permissions
4. Custom Plugin is not available

### Expected behavior

A dropdown of Plugin name > Endpoint to check for authenticate under user role

### Additional context

This used to work in Strapi V3

**Comment by karimxload** [comment]
Facing same issue on version 4.4.5. The generated `myController.index` endpoint is not accessible. When I hit the endpoint it returns a 404 not found error. Also, it's not listed when I run `yarn strapi routes:list`. I don't know exactly where this issue was introduced but on strapi version 4.3.9 everything is working fine. When I hit the endpoint on that version, it gives me a unauthorized error as expected.

**Comment by karimxload** [comment]
I had a similar issue. I couldn't access my plugin api routes. The problem for was that I made a simple mistake of not providing the right plugin name in condig/plugins.ts

```typescript
export default {
 // my plugin name was todo
  "my-plugin": { // updating this to my plugin name fixed it.
    enabled: true,
    resolve: "./src/plugins/todo",
  },
};
```

**Comment by derrickmehaffy** [comment]
In v4 we split the admin and content-apis, I have a draft PR that fixes the plugin generation but can you check that you are properly exporting the route as part of the content-api?

See this PR for some information: https://github.com/strapi/strapi/pull/14603
