### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/workspace/favicon.png'

### ISSUE THREAD

**Issue by NicoHof** [strapi/strapi#14693]
### Required System information

- Node.js version: v16.18.0
- Strapi version: v4.4.5
- Database: Postgres
- Operating system: Digital Ocean App Platform

### Describe the bug

Visiting Strapi Backend UI causes a `500 - InternalServerError` because loading `favicon.ico` fails.

### Steps to reproduce the behavior

1. Go to '/'

### Expected behavior

No error loading favicon.ico

### Code snippets

Strapi logs:
```
Error: ENOENT: no such file or directory, open '/workspace/favicon.png'
[2022-10-20 13:13:09]     at Object.openSync (node:fs:590:3)
[2022-10-20 13:13:09]     at Object.readFileSync (node:fs:458:35)
[2022-10-20 13:13:09]     at /workspace/node_modules/koa-favicon/index.js:50:28
[2022-10-20 13:13:09]     at dispatch (/workspace/node_modules/koa-compose/index.js:42:32)
[2022-10-20 13:13:09]     at middleware.handler (/workspace/node_modules/@strapi/strapi/lib/services/server/middleware.js:96:41)
[2022-10-20 13:13:09]     at dispatch (/workspace/node_modules/koa-compose/index.js:42:32)
[2022-10-20 13:13:09]     at /workspace/node_modules/@strapi/strapi/lib/middlewares/body.js:58:15
[2022-10-20 13:13:09]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-20 13:13:09]     at async /workspace/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
[2022-10-20 13:13:09]     at async /workspace/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
```

Browser Console:

**GET** `https://DOMAIN/favicon.ico` **500**

### Additional context

Maybe introduced here? https://github.com/strapi/strapi/pull/14655

**Comment by dubem-design** [comment]
Same issue when I tried to create a custom plugin. The plugin is not visible

**Comment by matthewdenison** [comment]
Same thing has happened to me. The content-type builder crashed in my case. I created a PNG version of the favicon.ico file to get around it for now.

**Comment by derrickmehaffy** [comment]
Can any of you confirm if you are using typescript or regular CommonJS?

**Comment by matthewdenison** [comment]
> Can any of you confirm if you are using typescript or regular CommonJS?

I am using typescript

**Comment by darkmavis1980** [comment]
I have the same issue, and I'm not creating any custom plugins, just using it as a backend for my personal site, issue appeared after I upgraded from `4.4.3` to `4.4.5`

**Comment by derrickmehaffy** [comment]
@darkmavis1980 are you also on typescript?

**Comment by derrickmehaffy** [comment]
Can any/all of you add this file to the root of your Strapi project: 
![favicon](https://user-images.githubusercontent.com/8593673/198366643-7261700d-c8c4-4ebb-83c8-792a330ab4a5.png)

save it as `favicon.png`

**Comment by NicoHof** [comment]
> Can any/all of you add this file to the root of your Strapi project: ![favicon](https://user-images.githubusercontent.com/8593673/198366643-7261700d-c8c4-4ebb-83c8-792a330ab4a5.png)
> 
> save it as `favicon.png`

@derrickmehaffy I added it and for me it solves the issue.

**Comment by derrickmehaffy** [comment]
So we need a migration guide then cc @gu-stav or we need to add an OR check for .ico or .png

**Comment by gu-stav** [comment]
@derrickmehaffy Thanks. I'll have a look if it would be easy to get a fix that makes the change backward-compatible for the next version and add it to the migration guide the 4.4.5.

Apologies, everyone - I didn't expect at all that this could happen. 🤦🏼

**Comment by derrickmehaffy** [comment]
Thanks @gu-stav :)

**Comment by darkmavis1980** [comment]
> @darkmavis1980 are you also on typescript?

Nope

**Comment by derrickmehaffy** [comment]
> > @darkmavis1980 are you also on typescript?
> 
> Nope

We found the issue above with a pending fix
