### ISSUE TITLE
Count route responds 404 *only* when should return 0

### ISSUE THREAD

**Issue by guillermodoghel** [strapi/strapi#1469]
**Informations

- **Node.js version:**Node v10.4.1
- **npm version:** npm 6.1.0
- **Strapi version:** 3.0.0-alpha.12.6
- **Database:** 10.1.32-MariaDB (myqsl 5.6.36 / PHP 5.6.36 from XAMPP for OSX)
- **Operating system:** mac os high sierra 10.13.4

**What is the current behavior?**

When I run a count request with filters, and the expected resoult is greater equal than 1, It responses is the correct number, but when should respond with a 0, I get a 404

**Steps to reproduce the problem**
Create some entity, fill some data, and run a count request with some filters

For example I have my invoice entity
<img width="746" alt="screen shot 2018-06-26 at 11 24 26" src="https://user-images.githubusercontent.com/12142386/41918837-8e551dc2-7933-11e8-9ba5-5cb6b6fcce27.png">

With this data
<img width="946" alt="screen shot 2018-06-26 at 11 24 15" src="https://user-images.githubusercontent.com/12142386/41918878-9f345a36-7933-11e8-97d2-c0647a8c7dd8.png">

The "found something count" works great
<img width="909" alt="screen shot 2018-06-26 at 11 23 50" src="https://user-images.githubusercontent.com/12142386/41918894-a9a38d02-7933-11e8-9157-15799f0f57a5.png">

but the "should return 0" returns a 404
<img width="906" alt="screen shot 2018-06-26 at 11 24 02" src="https://user-images.githubusercontent.com/12142386/41918935-bbf33bd8-7933-11e8-9412-d5d53dc0f0fc.png">

**What is the expected behavior?**
Is this a bug or a feature? When the count ammount is 0, I think it should return a 0, its more accurate than a 404

related with https://github.com/strapi/strapi/issues/1344 maybe?

**Comment by derrickmehaffy** [comment]
@guillermodoghel unlikely related to my issue there. The count service likely doesn't have a catch setup. Much like a GET request returns an empty json array, the count doesn't get a response from the db on data and defaults to a 404 error. 

Your right that it should return a 0. (Technically speaking this should be a 500 error if anything lol, 4xx is a user problem. So regardless it shouldn't be a 404)

I can confirm this bug exists though.

**Comment by lauriejim** [comment]
There is somewhere (haha) in the code where we check if the body is empty or not to set 404 response. We have to omit `0` as body to not send 404 response.
The thing you have to do is to find where the test is made :shipit:

**Comment by bahdcoder** [comment]
@lauriejim are you working on this? I could have a look and raise a PR later today if you haven't started yet. 🤔
