### ISSUE TITLE
Forgot-Password Route Application Error

### ISSUE THREAD

**Issue by mazarady** [strapi/strapi#14704]
### Describe the bug
I’m attempting to make a request to this route: http://localhost:1337/api/auth/forgot-password following the documentation listed [here](https://strapi.gitee.io/documentation/3.0.0-alpha.x/guides/authentication.html#forgotten-password), however, I get a 400 response with the following Application error:

1. "SMTP code:553 msg:553 5.7.2 [TSS09] All messages from 104.34.59.95 will be permanently deferred; Retrying will NOT succeed. See https://postmaster.yahooinc.com/error-codes\r\n". 

I'm not sure if this is a known bug or if I'm setting it up wrong.

**Comment by mazarady** [comment]
![Screen Shot 2022-10-22 at 7 21 36 PM](https://user-images.githubusercontent.com/16010644/197370025-407dc8aa-9c24-4073-813c-b66e3c1809ca.png)

Image of my postman request.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.
