### ISSUE TITLE
Upload "Files Are Empty"

### ISSUE THREAD

**Issue by parliament718** [strapi/strapi#14706]
### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.4.5
- Database: ?
- Operating system: MacOS

I'm trying to set up a new Strapi instance and have added a Product content type with a "productImages"  property (Media type).

However, I'm unable to upload any media. I keep getting "Files are empty" error when calling the /upload route.

<img width="827" alt="Screen Shot 2022-10-23 at 7 40 16 PM" src="https://user-images.githubusercontent.com/3580270/197404444-d1197fd3-26ae-4f49-a7d1-3d189830e3c9.png">

![Screen Shot 2022-10-23 at 7 44 58 PM](https://user-images.githubusercontent.com/3580270/197404671-c2c7cfe4-e94c-4d69-9a75-2a3fd6945ffd.png)
![Screen Shot 2022-10-23 at 7 45 03 PM](https://user-images.githubusercontent.com/3580270/197404674-2c51d42e-0081-4e94-a208-097bcb27e7fc.png)

Someone else reported this exact issue just 11 days ago [here](https://github.com/strapi/strapi/issues/14609) but seemed to have a resolution related to removing Axios.

 I do not have Axios installed separately from Strapi, so I believe this is not the real issue.

I can see that ```files``` param in the payload is indeed empty,  I'm new to Strapi and at a bit of a loss here.

**Comment by luke-z** [comment]
Hey Vazy

I just experienced the same problem and had Axios installed.
The switch to node-fetch didn't solve my problem.

I then proceeded to delete all the temp files/folders

- yarn.lock
- node_modules/
- .cache/
- build/

After reinstalling the modules and rebuilding the admin UI, uploads started to work again.

Could very well be a problem from upgrading to 4.3.4 to 4.4.3 in my case.

**Comment by parliament718** [comment]
Thanks that worked.

**Comment by appanchor** [comment]
This error will occur after strapi build if axios 1.0.0 or higher is installed. No errors with axios 0.27.2 or the default strapi dependency. I wasted a day troubleshooting this. You get what you pay for.

**Comment by s-stude** [comment]
Any ideas if strapi will fix this so any version of axios could be used?
