### ISSUE TITLE
Documentation plugin doesn't generate locale parameter for OpenApi endpoints

### ISSUE THREAD

**Issue by AlberGonAcosta** [strapi/strapi#14712]
### Required System information

- Node.js version: v16.16.0
- NPM version: v8.11.0
- Strapi version: 4.4.3
- Database: Default
- Operating system: MacOS Monterey 12.5

### Describe the bug

When I enable localization in a Content-Type the OpenApi documentation generated doesn't have `locale` as a parameter and that makes impossible to search for other languages apart from the default one.

### Steps to reproduce the behavior

Prerequisites: Have a Content-type with the localization **enabled** and with several translations on it (Let's call it `vocabulary` for the sake of the example)

1. `npm run develop`
2. Go to the OpenApi documentation generated
3. Click on the `/vocabularies` endpoint
4. See that there is no `locale` parameter available
5. Try the endpoint with the default parameters (And with a valid authorization if needed)
6. See that the response is valid and returns the entry for the default language
7. In the `filters` parameter add `{"locale":"XX"}`, where `XX` is some of the other languages you have set up apart from the default language (e.g. `es`) and Execute the call again
8. See that the response is empty
9. In the `filters` parameter change back the locale to the default one and Execute the call again
10. See that the response returns the entry for the default locale

### Expected behavior

When I enable localization in a specific Content-Type I expect to see a `locale` parameter on that specific Content-Type's OpenApi endpoints so it can be turned into a query parameter on the final REST call.

### Screenshots

Content-Type with localization enabled
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/115982469/197514399-2e0568c4-5036-4e1a-b9b5-75ab9f8e31d4.png">

OpenApi endpoint with no `locale` parameter available
<img width="727" alt="image" src="https://user-images.githubusercontent.com/115982469/197514574-851a0658-7233-4534-ba52-bf4f64f99d93.png">

Filter applied for the default locale
<img width="982" alt="image" src="https://user-images.githubusercontent.com/115982469/197514794-226b5010-14e8-45f1-8a2e-c34f5c75f331.png">

Filter applied for other locale apart from the default one
<img width="975" alt="image" src="https://user-images.githubusercontent.com/115982469/197514880-603c7b79-4e07-4453-a073-75b2038e0177.png">

Content-Type has an entry for that locale published
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/115982469/197514989-d343846d-aa88-45f5-b84d-a070fdc915d1.png">

**Comment by emilieringwald** [comment]
Hello! Thank you for the ticket, we just added this to our backlog. We'll have a look as soon as possible.
