### ISSUE TITLE
REST API Single Types do not publish

### ISSUE THREAD

**Issue by reklis** [strapi/strapi#14719]
### Required System information

- Node.js version: 18.10
- NPM version: 8.19.2
- Strapi version: 4.4.5
- Database: postgres
- Operating system: Linux 5.19.16-76051916-generic

### Describe the bug

"Single types" and "Collection types" behave differently via REST API.  

### Steps to reproduce the behavior

Create two types: one collection type, one single type.  Both with a single field, for example foo field type json.

Creating the single type entry works: 

    PUT /api/mysingletype/

    {
      "data": {  "foo":  { "bar": "baz" } }
    }

   response OK

Updating the single type fails:

    PUT /api/mysingletype/

    {
      "data": {  "foo":  { "bar": "baz" } }
    }

    // response
    {
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "singleType.alreadyExists",
        "details": {}
    }
    }

Note: I also tried PUT /api/mysingletype/1 but that had the same result.

Fetch the record that was created, not found

    GET /api/mysingletype
    
    {
    "data": null,
    "error": {
        "status": 404,
        "name": "NotFoundError",
        "message": "Not Found",
        "details": {}
    }
    }

Fetching unpublished works:

    GET /api/mysingletype?publicationState=preview

    {
    "data": {
        "id": 1,
        "attributes": {
            {  "foo":  { "bar": "baz" } },
            "createdAt": "2022-10-25T02:14:10.165Z",
            "updatedAt": "2022-10-25T02:28:22.258Z",
            "publishedAt": null
        }
    },
    "meta": {}
    }

### Expected behavior

Expected: single type to work like collection type.

* Collection type automatically publishes object (publishedAt not null)
* Collection type allows updates of content with PUT

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

    ⎆ npm ls
    cms@0.1.0
    ├── @strapi/plugin-i18n@4.4.5
    ├── @strapi/plugin-users-permissions@4.4.5
    ├── @strapi/strapi@4.4.5
    ├── @strapi/utils@4.4.5
    ├── better-sqlite3@7.4.6
    ├── pg@8.8.0
    ├── strapi-plugin-redis@1.0.0-alpha.2
    ├── strapi-plugin-rest-cache@4.2.4
    └── strapi-provider-rest-cache-redis@4.2.4

    ⎆ cat docker-compose.yaml
    services:
      postgres:
        image: postgres:14
        environment:
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
      redis:
        image: redis:7
        ports:
          - 6379:6379
    volumes:
      pgdata:

**Comment by derrickmehaffy** [comment]
Yeah that is absolutely not supposed to happen, I can confirm this on v4.4.5

![image](https://user-images.githubusercontent.com/8593673/199263921-2a6e99a0-9d11-4df3-8698-c0db008e6111.png)
![image](https://user-images.githubusercontent.com/8593673/199263979-f25de684-045b-4c82-b72f-7d603ca30b4a.png)

**Comment by kasonde** [comment]
@derrickmehaffy and @reklis to get around this for now you need to append `publicationState=false` to your unpublished Single type update request. 

I think this is a flaw in the way we search for single types. Since the ID is never exposed (we expect 1 every time since it's a singleType) a findAll query is ran by the Entity Service. But the ES won't return publicationState=null by default so you have to apply that filter.
