### ISSUE TITLE
Action Button very smaller

### ISSUE THREAD

**Issue by worapolburaphan** [strapi/strapi#1472]
**What is the expected behavior?**
I need to have a edit and remove button instead icon action because it's very smaller, hard for click remove icon

**Comment by derrickmehaffy** [comment]
Might worth also adding a `Delete` button when viewing the record instead of just `Reset` @soupette 

I believe we discussed this previously but I don't remember if there was a technical issue with this.

**Comment by derrickmehaffy** [comment]
@xeastcrast Just clicking on the record will open the edit option. I do agree though the delete one is quite small and hard to click

**Comment by Aurelsicoko** [comment]
Thanks for reporting this! I agree with you, it's too complicated to click on the icons. We should increase the space around the icons and also increase the font-size to make them bigger. 

@derrickmehaffy You're also right, we should add a `Delete` button in the Edit view 👍
