### ISSUE TITLE
make `only` property optional in the RouterConfig 

### ISSUE THREAD

**Issue by StrapiShaun** [strapi/strapi#14720]
### Required System information

- Node.js version: 14
- NPM version: 6
- Strapi version: 4.4.5
- Database: sqlite
- Operating system: macOS

### Describe the bug

The property `only` is mandatory for the middleware route configurations in js and ts and should be optional. 

### Steps to reproduce the behavior

 the RouterConfig type expects it at [packages/core/strapi/lib/types/factories.d.ts](https://github.com/strapi/strapi/blob/8231bb905ada00ec26dada3c574c51bf6ae2c0d2/packages/core/strapi/lib/types/factories.d.ts#L33)

type RouterConfig = {
  prefix?: string;
  only: string[];
  except?: string[];
  config: SingleTypeRouterConfig | CollectionTypeRouterConfig;
};

1. Go to packages/core/strapi/lib/types/factories.d.ts
2. see the config: 

type RouterConfig = {
  prefix?: string;
  only: string[];
  except?: string[];
  config: SingleTypeRouterConfig | CollectionTypeRouterConfig;
};

### Expected behavior

only should be optional

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

See [this issue](https://github.com/strapi/documentation/pull/1226) in the docs repo.

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
