### ISSUE TITLE
DateTime Picker Return Different response other than one exists in the front End Fewer hours

### ISSUE THREAD

**Issue by MohamedSonata** [strapi/strapi#14726]
Hello Guys 

- Node.js version:16
- NPM version:
- Strapi version: 4.4.3
- Database: sqlite
- Operating system: windows

I'm using Strapi Version 4.4.3 I've found a Problem With Date Time Field

thers's a problem while try getting the Response  the strapi server return Datetime field but by Minus 2 hours  of what i saved in the front end .... 
 
 and also the default  field response of each api collection  Field (updatedAt) returned by minus 5 hours 

The problem with date time is coming only in response ..
in front end it's working well as u see  but when do any update and try getting response server return different response as what there in front end 
https://user-images.githubusercontent.com/96669613/198177653-4b675dfe-29ef-4d4c-b35d-7908a5e54d9e.png
https://user-images.githubusercontent.com/96669613/198177663-e065b1d7-504a-4780-a898-71dcf392018e.png

there's new Problem also when send a request Update the DateTime field with new value server automatically increase hours by One hour on what u send in the request

**Comment by gu-stav** [comment]
@MohamedSonata Thank you for opening this issue. Is that regression that appeared after an update for you?

**Comment by MohamedSonata** [comment]
@gu-stav Yes i find this problem after last update of my current version 4.4.3 .

previous versions was return right data as you set it in front End .

**Comment by derrickmehaffy** [comment]
> @gu-stav Yes i find this problem after last update of my current version 4.4.3 .
> 
> previous versions was return right data as you set it in front End .

Can you confirm that your frontend converted to UTC/GMT before it sends the information? Strapi strictly expects that dates and times sent are in UTC/GMT as the server shouldn't handle that conversion.

**Comment by MohamedSonata** [comment]
@derrickmehaffy 

Can you confirm that your front end converted to UTC/GMT before it sends the information? Strapi strictly expects that dates and times sent are in UTC/GMT as the server shouldn't handle that conversion.

i'm talking about Strapi front end Not My custom front end  The Dashboard of any strapi app  as i add the pictures here ..

when editing any entries in Content manger if the entery include dateTime field or no the response returning the time minus 2 hours and also updatedAt response with any request returning with decreased 2 hours 

https://user-images.githubusercontent.com/96669613/198177653-4b675dfe-29ef-4d4c-b35d-7908a5e54d9e.png
https://user-images.githubusercontent.com/96669613/198177663-e065b1d7-504a-4780-a898-71dcf392018e.png


https://user-images.githubusercontent.com/96669613/199132878-c36c4246-839e-452a-b8b8-1babb1491aba.mp4

**Comment by derrickmehaffy** [comment]
Ah this is likely a regression then from v3, I'll do some more testing on this as I think I know how to reproduce.
