### ISSUE TITLE
failed installing email plugin

### ISSUE THREAD

**Issue by CantGetRight82** [strapi/strapi#1473]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: Mongo 3.6.5
- **Operating system**: macOS High Sierra 10.13.4

**What is the current behavior?**
When creating a new project with the cli, I get the following error:

[2018-06-27T07:38:48.888Z] error An error occurred during email plugin installation.
[2018-06-27T07:38:48.889Z] error Command failed: node /usr/local/lib/node_modules/strapi/bin/strapi.js install email 

**Steps to reproduce the problem**
strapi new myproject

**What is the expected behavior?**
No errors :)

**Suggested solutions**
It seems the npm url does exist:
https://www.npmjs.com/package/strapi-plugin-email

But the connected github repo does not:
https://github.com/strapi/strapi-plugin-email

**Comment by derrickmehaffy** [comment]
Just saw this as well, here is the error if you delete the directory and attempt to install it using the strapi-cli:

```
strapi install email
[2018-06-27T07:42:27.939Z] debug Installation in progress...
[2018-06-27T07:42:27.940Z] debug Installing the plugin from npm registry.
[2018-06-27T07:42:29.074Z] error An error occurred during plugin installation. 
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-email
```

**Comment by derrickmehaffy** [comment]
@CantGetRight82 Just a heads up, spoke with @lauriejim on slack he is aware and actively working on this :+1:

**Comment by lauriejim** [comment]
@CantGetRight82 working on it, it will be fixed in few minutes

**Comment by lauriejim** [comment]
Please run `npm i strapi@alpha -g` and create your project.

**Comment by lauriejim** [comment]
@CantGetRight82 and @derrickmehaffy You can confirm

**Comment by derrickmehaffy** [comment]
@lauriejim the email plugin installed however the bookshelf package will not. I'm guessing there is a wider issue with some other strapi packages.

**Comment by derrickmehaffy** [comment]
https://www.npmjs.com/package/strapi-bookshelf

**Comment by CantGetRight82** [comment]
My installation works now, thanks!
