### ISSUE TITLE
Error saving content that contain Unicode characters in text

### ISSUE THREAD

**Issue by andimuka** [strapi/strapi#14738]
### Required System information

- Node.js version: 14.20.0
- NPM version: 6.14.17
- Strapi version: 4.2.3
- Database:  Ver 15.1 Distrib 10.4.26-MariaDB
- Operating system: Ubuntu 20.04.5 LTS

### Describe the bug

Cannot save content if one of text fields which are part of the content type contains special Unicode characters besides text. These characters are invisible to the user so the user is unaware what he is doing wrong.
Generally happens when you copy formatted content from other sources. In our case it was text copied from PowerPoint online.

### Steps to reproduce the behavior

1. Go to the Content Manager in Strapi
2. Create a new entry in a content type which has at least one field of type text
3. In the text field paste a text content containing a hidden Unicode character as well
4. Click on Save button to save the content

### Expected behavior

Content gets saved.

### Actual behavior
I receive an error: Bad request, and I cannot save the content.

### Additional context

The Unicode character that we tried was U200B (zero width space)
You can copy the following sentence to reproduce the issue: There is a hidden character here (&#8203;) here

Error in backend:
`
0|strapi-stage  | [2022-10-05 05:27:06.954] http: GET /content-manager/collection-types/api::use-case.use-case?page=1&pageSize=10&sort=title:ASC&locale=de (40 ms) 200
0|strapi-stage  | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
0|strapi-stage  | Error: ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
0|strapi-stage  |     at Query.Sequence._packetToError (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
0|strapi-stage  |     at Query.ErrorPacket (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
0|strapi-stage  |     at Protocol._parsePacket (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/Protocol.js:291:23)
0|strapi-stage  |     at Parser._parsePacket (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/Parser.js:433:10)
0|strapi-stage  |     at Parser.write (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/Parser.js:43:10)
0|strapi-stage  |     at Protocol.write (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/Protocol.js:38:16)
0|strapi-stage  |     at Socket.<anonymous> (/srv/strapi/strapi-stage/node_modules/mysql/lib/Connection.js:88:28)
0|strapi-stage  |     at Socket.<anonymous> (/srv/strapi/strapi-stage/node_modules/mysql/lib/Connection.js:526:10)
0|strapi-stage  |     at Socket.emit (events.js:400:28)
0|strapi-stage  |     at Socket.emit (domain.js:475:12)
0|strapi-stage  |     --------------------
0|strapi-stage  |     at Protocol._enqueue (/srv/strapi/strapi-stage/node_modules/mysql/lib/protocol/Protocol.js:144:48)
0|strapi-stage  |     at Connection.query (/srv/strapi/strapi-stage/node_modules/mysql/lib/Connection.js:198:25)
0|strapi-stage  |     at /srv/strapi/strapi-stage/node_modules/knex/lib/dialects/mysql/index.js:132:18
0|strapi-stage  |     at new Promise (<anonymous>)
0|strapi-stage  |     at Client_MySQL._query (/srv/strapi/strapi-stage/node_modules/knex/lib/dialects/mysql/index.js:126:12)
0|strapi-stage  |     at executeQuery (/srv/strapi/strapi-stage/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
0|strapi-stage  |     at Client_MySQL.query (/srv/strapi/strapi-stage/node_modules/knex/lib/client.js:146:12)
0|strapi-stage  |     at Runner.query (/srv/strapi/strapi-stage/node_modules/knex/lib/execution/runner.js:130:36)
0|strapi-stage  |     at ensureConnectionCallback (/srv/strapi/strapi-stage/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
0|strapi-stage  |     at Runner.ensureConnection (/srv/strapi/strapi-stage/node_modules/knex/lib/execution/runner.js:307:20)
0|strapi-stage  | [2022-10-05 05:28:01.069] http: GET /admin/content-manager/collectionType/api::use-case.use-case/create?plugins[i18n][locale]=de (2 ms) 200
0|strapi-stage  | [2022-10-05 05:28:01.120] http: GET /admin/runtime~main.b8731227.js (1 ms) 200
`

**Comment by derrickmehaffy** [comment]
I'm unable to reproduce this, I did try using the zero-width space unicode char although my system (Linux Mint) replaces this char with a dot in the content-manager (I tried a few other unicode chars as well) and could not reproduce this issue.

![image](https://user-images.githubusercontent.com/8593673/199113511-c0f13ab8-4114-40b1-b5d9-e7375d6334ec.png)

Can you confirm what encoding your tables has? Some MariaDB / MySQL instances set a default encoding type of `latin1-swedish_ci` or `latin1` which doesn't support unicode chars, you should change to `utf8mb4` if possible (optionally set your server's default to this as well). Node that simply changing the database type isn't enough, you will also have to migrate each table as well.

![image](https://user-images.githubusercontent.com/8593673/199113909-b8dc6cd8-0cac-450e-8804-3da3905f17de.png)

See: https://dbasecenter.com/converting-your-data-from-latin1-to-utf8mb4/

Since I believe this issue to be an encoding one unrelated to Strapi I'll mark this as closed but let me know if you aren't sure or believe this to still be a bug.
