### ISSUE TITLE
failed behind reverse proxy

### ISSUE THREAD

**Issue by leoyox** [strapi/strapi#14735]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.13.2
- Strapi version: 4.4.3
- Database: sqlite3
- Operating system: Linux

### Describe the bug
1. self-hosted on my pc in LAN
2. frp proxy to my VPS
3. access from public network with www.xxxx.com

there are 2 XHR accessing localhost:1337 other than www.xxxx.com

### Screenshots

![image](https://user-images.githubusercontent.com/109495645/198529471-4541f4db-e498-4bed-8784-245164616708.png)

![image](https://user-images.githubusercontent.com/109495645/198530452-44123c4a-ec54-4a3a-a68d-aae311ff97d9.png)

**Comment by derrickmehaffy** [comment]
Ensure you set the server.js URL key and rebuild the admin panel.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
