### ISSUE TITLE
Strapi doesn't start after naming conflict occurs

### ISSUE THREAD

**Issue by paddotk** [strapi/strapi#14739]
## Bug report
Creating a (single) type with an existing name makes the server crash upon saving, and the server won't start anymore.

### Required System information
- Node.js version: 16.14.2
- yarn version: 1.22.11
- Strapi version: 4.4.3
- Database: ?
- Operating system: Windows 10

### Describe the bug
See steps below.

### Steps to reproduce the behavior
1. Add a single type e.g. called `jobs`. This is the singular name; make the plural name something else, e.g. `jobss`
2. Add another single type called `job`. Singular name `job`, plural `jobs`
3. So far everything works, and I can add content types to it.
4. Click 'save'. At this point the server crashes
5. Trying to start the server again, it just gives me the following error and quits:
  ```bash
    [2022-10-28 16:02:51.634] debug: ⛔️ Server wasn't able to start properly.
    [2022-10-28 16:02:51.635] error: The singular name "jobs" should be unique
  ```

I managed to get Strapi working again by deleting the folder in `/src/api/`, although normally I'd prefer not to mess with the generated files there.

* To clarify my choices, we have a job overview page (which is `jobs`) and a page for a specific job (detail page), called `job`.

### Expected behavior
I'd expect to get an error when trying to save (or preferably as soon as I create the type), stating what issue occurs.

### Additional context
This issue might be related: https://github.com/strapi/strapi/issues/13263

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1198

**Comment by paddotk** [comment]
@derrickmehaffy I encounted this a month ago, but #1198 was closed a few months ago. Doesn't this mean the issue isn't actually fixed?

**Comment by paddotk** [comment]
Sorry, I guess I got confused with the fix PR being merged, but that's just a reference.
Best of luck with it then :)
