### ISSUE TITLE
Error when assigning a role to a user

### ISSUE THREAD

**Issue by RealRzhaka** [strapi/strapi#14747]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.4.5
- Database: Postgres 14.5
- Operating system: Windows 11

### Describe the bug

Error when giving or changing roles to any user

### Steps to reproduce the behavior

I try give or remove roles and get **"Warning: An error occurred"**

**Comment by derrickmehaffy** [comment]
Please provide more information to reproduce the issue, as there is no clear reproduction steps or more information on how to reproduce the error, I'm marking this issue as closed.
