### ISSUE TITLE
The default MongoDB connectOptions overrides the URI params options

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#1474]
**Informations**
- **Node.js version**: v9.11.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.12.6
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The default MongoDB `connectOptions` overrides the URI params options.

**Steps to reproduce the problem**

With this database config:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "uri": "${process.env.DATABASE_URI}"
      }
    }
  }
}
```

And this environment variable:

`DATABASE_URI=mongodb://username:password@host:port/database?authSource=admin&ssl=true`

In the `instance.connect` at:

https://github.com/strapi/strapi/blob/4becad13f1e571ceaa9684b9ea36771367a039e1/packages/strapi-mongoose/lib/index.js#L76

The `connectOptions` overrides the `?authSource=admin&ssl=true` from the URI.

**What is the expected behavior?**

Not override the options from the URI.

**Suggested solutions**

Use the params from the URI.

**Comment by abdonrd** [comment]
@lauriejim What do you mean? Like this?

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo"
      },
      "options": {
        "uri": "${process.env.DATABASE_URI}"
      }
    }
  }
}

```

**Comment by lauriejim** [comment]
I think something like that should work

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "uri": "..."
      },
      "options": {
        "authenticationDatabase": "admin",
        "ssl": true
      }
    }
  }
}
```

**Comment by abdonrd** [comment]
@lauriejim I can't do that because I use a service that only offers me a URI with all the information; like this:

`DATABASE_URI=mongodb://username:password@host:port/database?authSource=admin&ssl=true`

**Comment by lauriejim** [comment]
Okay. Maybe we can update your PR.

In the way you did it, if someone use `uri` it's options will not be applied. Or he has to set it in the `uri` url and it's not really user friendly.

So a way to handle both case can be to transform `uri` url params to option key value ?

**Comment by abdonrd** [comment]
Ok, if we assume that `options` is more important than the parameters of the URI.

**Comment by lauriejim** [comment]
If you remove `options` object in your database config, with your `uri` params it's working on your case ?

**Comment by abdonrd** [comment]
No, because it's override SSL as `false`:

https://github.com/strapi/strapi/blob/4becad13f1e571ceaa9684b9ea36771367a039e1/packages/strapi-mongoose/lib/index.js#L72

**Comment by lauriejim** [comment]
We can maybe doing something like that

```js
const { uri, host, port, username, password, database } = _.defaults(connection.settings, strapi.config.hook.settings.mongoose);
const uriOptions = getUriParms(uri); // if there is an uri
const { authenticationDatabase, ssl, debug } = _.defaults(connection.options, uriOptions, strapi.config.hook.settings.mongoose);
```

**Comment by abdonrd** [comment]
Updated and working for me! 😁 Thanks @lauriejim!

**Comment by lauriejim** [comment]
Yeah top ! 👍

**Comment by lauriejim** [comment]
@abdonrd  Can you just make a try without `uri` params in your database file please.
With an local mongo database

**Comment by abdonrd** [comment]
@lauriejim oops! Fixed now!
