### ISSUE TITLE
JSON Data Type is not working in GraphQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1476]
**Informations**
- **Node.js version**: v10.5.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: 10.2.15-MariaDB
- **Operating system**: Linux Mint 19 Beta (Ubuntu 18.04)

**What is the current behavior?**

Using the json data type, GraphQL responds on all entries with `[object Object]`

**Steps to reproduce the problem**

Create a model with the JSON data type, and enter some data. Query the model with GraphQL (Playground)

**What is the expected behavior?**

GraphQL should format the data properly and display it

**Suggested solutions**

Not sure what is causing this, likely the recent fixes to the JSON data in MySQL. Unsure of the best approach for this.

**Comment by derrickmehaffy** [comment]
It seems GraphQL is mapping the JSON data as a string, see the following screenshot from my project:

<img width="792" alt="capture d ecran 2018-06-27 a 15 29 00" src="https://user-images.githubusercontent.com/8593673/41977459-3f613a92-79d4-11e8-8607-187c9fdfa769.png">

**Comment by lauriejim** [comment]
Hello @derrickmehaffy ! thank you for reporting this issue.
Ping @johannpinson have you also this issue ?

**Comment by derrickmehaffy** [comment]
@lauriejim I spoke with @johannpinson yesterday on the slack (before it died :stuck_out_tongue: )

He stated this: 

> ok, the field is considered as a `String`, so what you have a field which had applied `.toString()` method
> > and so, a JSON field with the `.toString()` method is `[Object object]` (because it needs to use `JSON.stringify` instead)

**Comment by Blacknosaur** [comment]
I have this issue too. Without GraphQL it works but you only see [Object object] through the CRM but with GraphQL it doesn't return an object but the string "[Object object]"

**Comment by lauriejim** [comment]
Guys feel free to submit a PR to fix this issue. Will appreciate your contribution on this issue.

**Comment by johannpinson** [comment]
@lauriejim @derrickmehaffy 

I'll try to look it around the end of the week.
If someone else want to fix it, just do it 👍
