### ISSUE TITLE
Extending Strapi Services causes TypeError w/ Strapi (TS) v4.4.5

### ISSUE THREAD

**Issue by benjamin-p-newton** [strapi/strapi#14762]
## Bug report

Upgraded from Strapi v4.3.2 (TS) to v4.4.5 and now all the extended service definitions for collection types are throwing a TypeError.
The TypeError suggests that additional service methods are... "not assignable to parameter of type 'GenericService | ServiceCallback<GenericService>".

### Required System information

- Node.js version: v16.18.0
- NPM version: v8.19.2
- Strapi version: v4.4.5
- Database: sqlite
- Operating system: Windows 11

### Describe the bug

Receive the below TypeError when extending services for a collection type as per TypeScript example provided in documentation here: https://docs.strapi.io/developer-docs/latest/development/backend-customization/services.html#adding-a-new-service

> Argument of type '({ strapi }: { strapi: Strapi; }) => { exampleService<T = any>(...args: any): Promise<{ okay: boolean; } | { response: { okay: boolean; }; error: boolean; }>; find(params: object): Promise<{ ...; }>; findOne(entityId: any, params?: {}): Promise<...>; }' is not assignable to parameter of type 'GenericService | ServiceCallback<GenericService>'.

### Steps to reproduce the behavior

1. Create a new Strapi (TS) project using the CLI: `npx create-strapi-app@latest my-project --quickstart --ts`
2. Run the project locally: `npm run develop`
3. Navigate to http://localhost:1337/admin in your browser, create any collection type and save.
4. Once the project has re-built extend the "my-project/src/api/[collection-type]/services/[collection-type].ts" service file as per the documentation: https://docs.strapi.io/developer-docs/latest/development/backend-customization/services.html#adding-a-new-service
5. Attempt to build or run the solution via the CLI: `npm run build` or `npm run develop`

### Expected behavior

Expected behavior is that I can extend the service for the collection type as per the documentation.

### Screenshots

![2022-11-02 21_37_27-object ts - my-project - Visual Studio Code](https://user-images.githubusercontent.com/100539240/199503853-4b85b451-904e-4682-b70e-9a0065ee76ca.png)

### Code snippets

This is an example of the code that throws the error for an 'Object' collection type.

```
/**
 * object service
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreService('api::object.object', ({ strapi }) =>  ({
    // Method 1: Creating an entirely custom service
    async exampleService(...args) {
      let response = { okay: true }
  
      if (response.okay === false) {
        return { response, error: true }
      }
  
      return response
    },
  
    // Method 2: Wrapping a core service (leaves core logic in place)
    async find(...args) {  
      // Calling the default core controller
      const { results, pagination } = await super.find(...args);
  
      // some custom logic
      results.forEach(result => {
        result.counter = 1;
      });
  
      return { results, pagination };
    },
  
    // Method 3: Replacing a core service
    async findOne(entityId, params = {}) {
      return strapi.entityService.findOne('api::object.object', entityId, this.getFetchParams(params));
    }
  }));

```

### Additional context

N/A.

**Comment by Woods30** [comment]
I have met this issue too, is there any solutions for it?

**Comment by Woods30** [comment]
Great! I have resolved this problem with the solution refer to #14208

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
