### ISSUE TITLE
Twitter Provider Error

### ISSUE THREAD

**Issue by juanvrgr** [strapi/strapi#14769]
# Twitter Provider not working

I've been trying to implement Twitter login via the provider for some days now and I still can't figure out If I'm doing something wrong of if there's a problem with Twitter or the provider.

I followed this guide https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#providers step by step. First I downloaded the Strapi Login Example repo, couldn't make it work. Then followed the steps to make the integration in my project, and I got the same errors as before. I tried a lot of things and got some error variants, I will detail these down below. For the provider, 

- I got the Twitter authorization and login done, got all the data from Twitter but when I pass the access token on the /api/auth/twitter/callback?access_token request I get a 401 Unauthorized.
- Then I tried adding the access_secret too to make it /api/auth/twitter/callback?access_token=123&access_secret=456, and got 403 Forbidden. This is where I got stuck the most, trying a lot of things on the Users-permissions roles for both Public and Authorized, but couldn't make it work in any way.
-  I tried using API global tokens from Strapi as Bearer, but still get 403 Forbidden.
-  I regenerated the Twitter tokens, changed app settings in all the possible ways, but **I only get 403 Forbidden or 401 Unauthorized if access_token and access_secret parameters are wrong, so it seems the codes are working but something is blocking it and can't get the JWT token for the user.**

### I'm not sure if I'm missing something, or if something is broken with the Twitter provider or what, so that's why I'm reporting this as a bug . I'm willing to provide more information or screenshots to help solve this. ###

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by itaysarfaty** [comment]
@marcelobaez Did you resolve the issue? I'm facing the same one currently.
