### ISSUE TITLE
My data were deleted from Postgres after some time.

### ISSUE THREAD

**Issue by zprx** [strapi/strapi#14772]
### Required System information

- Node.js version: v16.13.0
- Strapi version: v4.4.1
- Database: PostgreSQL
- Operating system: Linux

### Describe the bug

Second time in one week data were deleted from PostgreSQL by itself.
I have not done any update, and I today when I was not able to build project, I found out that database empty, and all data dropped. It's second case in one week, what is going on , how I can fix this?

**Comment by storewaladotcom** [comment]
i second that. experiencing the same behavior where data is lost. i'm using postgres too.

**Comment by derrickmehaffy** [comment]
This is simply not possible with Strapi and PostgreSQL, most likely you have deployed your application into an environment with an ephemeral filesystem (EG Heroku) and your default `database.js` file is still probably set to SQLite.

Please provide more information about your environment, where you are deploying, the structure of your config files, etc.

Given the information you have provided now, we simply cannot help you.

**Comment by zprx** [comment]
@derrickmehaffy  I am using PG and all  in docker. I am not using heroku or something else. 
That's my database.js , and I am not agree that you closed ticket without any discussion... 

`const fs = require('fs');
const path = require('path');

export default ({ env }) => {
  return {
    connection: {
      client: 'postgres',
      connection: {
        host: env('DATABASE_HOST', ''),
        port: env.int('DATABASE_PORT', 25060),
        database: env('DATABASE_NAME', ''),
        user: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
        ssl: {
          ca: env('DATABASE_SSL', fs.readFileSync(`${path.resolve('./')}/config/ca.crt`).toString()),
        },
      },
    },
  }
};
`

**Comment by derrickmehaffy** [comment]
@zprx we don't provide environment support on GitHub issues, please open up a Convo in our community spaces. If you are also dockerizing your database, ensure you have a persistent volume to go with it.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by iamtun** [comment]
@zprx Can you fix this? I have the same issue with one collection.
Ex: 
- I have two collections. (Names: Paper-exam, grades)
- I create one record and add relation from paper-exam to grade with relation is one to many
- After creating a many times (1 day) paper exam lost grade data. `updated_at` did not change but the data modified

---
If you can solution, please help me. Thanks !
