### ISSUE TITLE
Problem with the Content-Type Builder in Strapi 4.4.6

### ISSUE THREAD

**Issue by WebShapedBiz** [strapi/strapi#14788]
### Required System information

- Node.js version: 16.13.1
- NPM version: 8.19.2
- Strapi version: 4.4.6
- Database: SQLite (localhost)
- Operating system: elementaryOS 6.1 (Ubuntu 20.04 based)

### Describe the bug

I have had the same Strapi installation for a few months now, starting with v4.2.0. and upgrading it with each new release, the latest being v4.4.5., and I didn't have a single issue.
Today I tried to upgrade to v4.4.6. and initially, everything went smoothly, Admin started correctly and all modules within Admin are working except Content-Type Builder. Clicking on it the screen goes blank (white) and there is no error in the terminal. However, in the console I got this error:

![ksnip_20221104-151216](https://user-images.githubusercontent.com/6765137/199997748-bba1cee5-626a-4e98-833e-1bea13abdea1.png)

These are my `package.json` dependencies:
```
"dependencies": {
    "@strapi/plugin-i18n": "4.4.6",
    "@strapi/plugin-users-permissions": "4.4.6",
    "@strapi/provider-email-mailgun": "4.4.6",
    "@strapi/provider-upload-aws-s3": "4.4.6",
    "@strapi/strapi": "4.4.6",
    "better-sqlite3": "7.4.6",
    "form-data": "^4.0.0",
    "pg": "^8.7.3",
    "strapi-plugin-fuzzy-search": "^1.9.4",
    "strapi-tiptap-editor": "^0.7.14"
  },
```

When I change back all versions from 4.4.6. to 4.4.5. everything is back to normal.

### Steps to reproduce the behavior

1. Install/upgrade Strapi to the latest 4.4.6. version 
2. Login in Admin
3. Go to the "Content-Type Builder" plugin
4. See blank screen and console error

Thank you for your time and effort.

**Comment by derrickmehaffy** [comment]
This should be fixed in 4.4.7 I believe (hotfix we released today)

For now I'll mark this as closed but if the issue still happens let us know and we can reopen.

**Comment by WebShapedBiz** [comment]
Thank you @derrickmehaffy for this update.

**Comment by WebShapedBiz** [comment]
Sorry to report, but I'm having exactly the same behavior with v4.4.7

**Comment by derrickmehaffy** [comment]
> Sorry to report, but I'm having exactly the same behavior with v4.4.7 on my current Strapi installation. I've created a new Strapi installation and everything works fine there :-(
> It seems that I cannot make an update from v4.4.5 to v4.4.6/v4.4.7

Delete your lock files node modules folder and reinstall and then rerun build

**Comment by WebShapedBiz** [comment]
How silly of me... of course that worked, thank you @derrickmehaffy.

**Comment by derrickmehaffy** [comment]
> How silly of me... of course that worked, thank you @derrickmehaffy.

No problem, happens to us all!

**Comment by tadwohlrapp** [comment]
Can confirm the issue persists in 4.4.7:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/2788192/200548866-31bdb782-94ef-4f68-a1b0-6d9d342a7b47.png">

On pretty much every page I navigate to in the admin panel. I see the loading spinner, a flash of the page and then a completely blank page and the errors in the console. Sometimes reloading the page once or twice fixes it, sometimes it doesn't.

```
  "dependencies": {
    "@strapi/icons": "^1.3.0-beta.0",
    "@strapi/plugin-i18n": "4.4.7",
    "@strapi/plugin-users-permissions": "4.4.7",
    "@strapi/provider-upload-cloudinary": "^4.4.7",
    "@strapi/strapi": "4.4.7",
    "better-sqlite3": "7.6.2",
    "pg": "^8.8.0",
    "strapi-plugin-config-sync": "^1.0.4",
    "strapi-plugin-import-export-entries": "^1.18.0"
  },
```

**Comment by tadwohlrapp** [comment]
@WebShapedBiz have you been able to resolve the issue on your end?

**Comment by derrickmehaffy** [comment]
Can you please try removing the import export plugin. I believe some others reported a similar issue and it was related to that. Likewise your icons packages out of sync with the rest.

**Comment by WebShapedBiz** [comment]
Yes @tadwohlrapp, what @derrickmehaffy suggested solved my issue, but as I understand you have a similar but not exactly the same problem.
