### ISSUE TITLE
How can I set difference role each user when them register on difference website

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1478]
**Informations**
- **Node.js version**: 10.4.1
- **npm version**:  6.1.0
- **Strapi version**:3.0.0-alpha.12.5
- **Database**: Mongodb
- **Operating system**: Ubuntu 18.0

**What is the current behavior?**
I don't know how to set difference user role on them register on difference website that use the same api such as "POST /auth/local/register"

**What is the expected behavior?**
I want to set difference role each user when them register on difference website.
Example once I post request:
```
{
      username: 'test',
      password: '123456',
      email: 'test@test.com',
      role: 'Writer' // <<-- Set to my custom role as i set in admin panel
}
```

**Comment by lauriejim** [comment]
Hello @xeastcrast ! Thank you for this proposition.
We will not work on this feature, not priority for us.
Feel free to customize plugin `users-permissions` ([here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L253)) to choose an other role depending of the origin of your request
