### ISSUE TITLE
NetworkError when uploading with Cloudinary

### ISSUE THREAD

**Issue by itsnewtjam** [strapi/strapi#14791]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.4.7
- Database: MySQL
- Operating system: Ubuntu

### Describe the bug

When attempting to upload images using the Cloudinary provider, I receive "An error occurred while uploading the file." in the admin dashboard, and an AxiosError / NetworkError is logged to the console.

I've seen other issues mentioning Axios versions, the updated plugins.js config, and different Node versions, however none of the solutions presented have helped. I also tried creating a new Strapi project and only setting up the Cloudinary provider in case something else I'd set up was causing this error, but no luck there either.

### Steps to reproduce the behavior

1. Install and set up Cloudinary provider
1. Go to 'Media Library'
2. Click on 'Add new assets'
3. Upload an image

### Screenshots

![strapi-screenshot](https://user-images.githubusercontent.com/78121730/200141659-80d6a7cb-a0bc-4a65-b819-5d6c92c7a329.png)

**Comment by nicoXXXXXtitan** [comment]
Hello
How did you solve your problem?
