### ISSUE TITLE
CLI ts:generate-types emits wrong types for MediaAttribute

### ISSUE THREAD

**Issue by minht11** [strapi/strapi#14795]
### Required System information
- Node.js version:
- NPM version:
- Strapi version: 4.4.7
- Database:
- Operating system:

### Describe the bug

A CLI command `strapi ts:generate-types` generates incorrect types for `MediaAttribute`.

### Steps to reproduce the behavior

1. Have a component schema like this:
```json
{
  "collectionName": "components_global_footer_images",
  "info": {
    "displayName": "FooterImages"
  },
  "options": {},
  "attributes": {
    "images": {
      "allowedTypes": [
        "images"
      ],
      "type": "media",
      "multiple": true, // This field is important
      "required": true
    }
  }
}

```
2. Generate typescript types using CLI command `strapi ts:generate-types`
3. Look inside generated schema.d.ts file and notice that types are incorrect, `MediaAttribute` is typed as if it should contain only one image, allowed types are not included also.
```ts
export interface GlobalFooterImages extends ComponentSchema {
  info: {
    displayName: 'FooterImages'
  }
  attributes: {
    images: MediaAttribute & RequiredAttribute
  }
}
```

### Expected behavior
Generated types should be something like this
```ts
export interface GlobalFooterImages extends ComponentSchema {
  info: {
    displayName: 'FooterImages'
  }
  attributes: {
    images: MediaAttribute<'images', true> & RequiredAttribute
  }
}
```

**Comment by minht11** [comment]
Just so as to not spam with new issues Media type is typed as `any` as well which is not ideal as it makes working with eslint while disallowing usage of `any` very hard https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/strapi/lib/types/core/attributes/common.d.ts#L10

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
