### ISSUE TITLE
Strapi Startup Alters Tables After Database Migration

### ISSUE THREAD

**Issue by dolphrundgren** [strapi/strapi#14794]
### Required System information
Node: 18.7.0
Strapi: 4.3.4
NPM: 8.15.0
Database: Postgres
OS: NixOs

### Describe the bug
I have migrated my database from Sqlite to Postgres. When trying to start my Strapi instance, it fails to connect to the new Postgres server. I get the following error:

error: alter table "upload_folders" drop constraint "idx_67259_upload_folders_path_id_index" - constraint "idx_67259_upload_folders_path_id_index" of relation "upload_folders" does not exist
error: alter table "upload_folders" drop constraint "idx_67259_upload_folders_path_id_index" - constraint "idx_67259_upload_folders_path_id_index" of relation "upload_folders" does not exist

[This appears to be a resurrection of Issue 11421](https://github.com/strapi/strapi/issues/11421)

### Steps to reproduce the behavior

1. Create local postgres database.
2. Use pg_loader to dump Sqlite data into postgres db.
3. Use pg_restore to migrate local postgres db to remote db (I'm using DigitalOcean)
4. Update config/database.js according to [developer docs](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-structure).
5. run "npm install pg"
6. run "npm run develop"

### Expected behavior
I should connect to the new db no problem. As a sanity test, I logged into the remote DB and confirmed that the tables from my SqLite instance were properly migrated. 

### Screenshots

[Debug buffer copied to Gist for reference.](https://gist.github.com/dolphrundgren/dfe52f662945a3196941f123b5334dea)

### Additional context

My hope here was to avoid having to manually repopulate my content-types with content after switching to postgres for production. DB migrations are never really fun, but I was slogging through it until this final hitch has brought me to a halt.

**Comment by derrickmehaffy** [comment]
Can you please try purging all entries in the `strapi_database_schema` table?

**Comment by nolliebigspin** [comment]
Hi, @dolphrundgren,
I've run into the same issue you described above. Did you find any solution for this problem? I'm currently running on Strapi 4.7.0 which throws me the same error after "successfully" migrating from sqlite to postgres with pgloader.

**Comment by yongchenglow** [comment]
Hi everyone, I ran into the same issue and managed to fixed it. This is a very weird user experience for first time users. I definitely recommend Strapi to change this. By default, Strapi will remove all [unknown tables](https://docs.strapi.io/dev-docs/database-migrations).....

To fid it, add the following to the file `config/database.js`
```javascript
  ...
  return {
    connection: {
      ...
    },
    settings: {
      runMigrations: true,
      forceMigrations: false,
    },
  };
```

**Comment by fanshaohua-fan** [comment]
The config mentioned by @yongchenglow  not solveing the issue either.

It works only on the first time when you initialize the strapi.
Once you make any change on ContentType, it will get blocked during the server starting with error below.
```
The server is restarting

Error: ER_DUP_KEYNAME: Duplicate key name 'upload_folders_path_id_index'
  code: 'ER_DUP_KEYNAME',
  errno: 1061,
  sqlMessage: "Duplicate key name 'upload_folders_path_id_index'",
  sqlState: '42000',
  index: 0,
  sql: 'alter table `upload_folders` add unique `upload_folders_path_id_index`(`path_id`)'
}

```

While if you change the forceMigrations to true, in order to start up the application.
All your existing tables(unknow for strapi) will be cleaned up...

It's truely annoying.

**Comment by yongchenglow** [comment]
Oh dear! So sorry for this @fanshaohua-fan . I gave up on the product because of this issue, didn't do any further testing after.

**Comment by koborg** [comment]
Guys any update on it? I have exactly the same issue when I try to migrate SQLite to Postgresql.

**Comment by perabjoth** [comment]
The easy workaround for this is to simply go ahead and create the missing indexes and when you run strapi it will just drop them. They don't have to be correct since they're getting deleted anyways.

One gotcha is that the index names are very similar so if you get the "same error" after creating the index, take a closer look as it may be a similarly named index.

Example:
```ALTER TABLE IF EXISTS strapi.upload_folders
    ADD CONSTRAINT idx_41892_upload_folders_path_id_index CHECK (1=1)
    NOT VALID;

COMMENT ON CONSTRAINT idx_41892_upload_folders_path_id_index ON strapi.upload_folders
    IS 'test';
