### ISSUE TITLE
Strapi Can't Create CORE API documentaion in swagger which will trigger in Browser Network tab while click on any collection-type 

### ISSUE THREAD

**Issue by pandeyprafull** [strapi/strapi#14796]
### Required System information

- Node.js version:v14.18.1
- NPM version: 8.3.0
- Strapi version: v4.3.2
- Database: Mysql
- Operating system: Ubuntu 20.04 LTS

### Describe the bug

Strapi Can't Create CORE API documentaion in swagger which will trigger in Browser Network tab while click on any collection-type . Is there Any possible way to create a swagger documention for these also by adding few Plugin properties or something Please do let me know.
### Steps to reproduce the behavior

1. Go to your strapi dashboard and then click on Content-Manager
2. Go to your Browser Network tab.
3. Click on Any Collection-Type.
4. You will get the Strapi Internal Core API's which will internally hit.

### Screenshots
![Screenshot from 2022-11-07 12-04-52](https://user-images.githubusercontent.com/29433163/200241442-265ff230-bd85-4575-9ecf-305841e9fe59.png)

### Additional context

I have applied same documentation structure as mentioned in [https://docs.strapi.io/developer-docs/latest/plugins/documentation.html](url).
But there is no provision listed as per my concern in official doc for the CORE API's .

Please Help urgently required @derrickmehaffy

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
