### ISSUE TITLE
Can use sequelizejs or mongoosejs with strapi ? 

### ISSUE THREAD

**Issue by sbacem** [strapi/strapi#148]

**Comment by Aurelsicoko** [comment]
Hi @sbacem! On the current version (v1.5.4), you can't use another ORM. The default ORM is Waterline. But, on the next version (v3), we will use Mongoose as a default ORM. Moreover, it will be possible to use others ORM. However, the entire Strapi ecosystem (plugins) will be only compatible with Mongoose.

You should take a look at [our blog ](http://blog.strapi.io)to get some fresh news about the v3.
