### ISSUE TITLE
MongoError: not authorized on [dbname] to execute command { listIndexes: "users-permissions_role"

### ISSUE THREAD

**Issue by decimoseptimo** [strapi/strapi#1480]
**Informations**
- **Node.js version**:
v8.11.3
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.6
- **Database**:
MongoDB shell version v3.4.15
- **Operating system**:
ubuntu server 18.04

**What is the current behavior?**
error: `MongoError: not authorized on [dbname] to execute command { listIndexes: "users-permissions_role"`
on: `"role : "userAdminAnyDatabase"`

but works ok on: `"role : "root"`

**Steps to reproduce the problem**
```
strapi new [name]
cd [name] && strapi start
```

I'm fairly new to mongodb, so I'm aware I may be missing something.

**Comment by derrickmehaffy** [comment]
@decimoseptimo this isn't an issue with Strapi. This is due to permissions not being setup correctly on mongo. Please take a look at their docs here: https://docs.mongodb.com/manual/tutorial/manage-users-and-roles/

**Comment by derrickmehaffy** [comment]
You can also use either MySQL/MariaDB or Postgres if you are more familiar with them.

**Comment by decimoseptimo** [comment]
thakns, I'll check it out.
