### ISSUE TITLE
Blog example crashes when changing a collection types to allow i18n

### ISSUE THREAD

**Issue by tatosjb** [strapi/strapi#14804]
### Required System information

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: 4.4.7
- Database: postgres: 10.12 (image name `postgres:10.12-alpine`)
- Operating system: Ubuntu 22.04

### Describe the bug

The blog example crashes when changing collection types to enable localization.

### Steps to reproduce the behavior

* Create a project with this command `yarn create strapi-app api --template blog --quickstart --ts`
* Run the project
* Go to the admin panel and click on edit in any of the collection types(could be any of them, you could do with article)
* Go to advanced tab and check `Enable localization for this Content-Type` then save.

At this point the server will broke when restarting.

### Screenshots
![strapi](https://user-images.githubusercontent.com/7603203/200388575-96d68508-2c2d-424b-8bb0-f80e50fbf8fa.gif)
![image](https://user-images.githubusercontent.com/7603203/200388001-a620be3d-a8c8-41fa-adff-1cd790164915.png)

### Code snippets

```json
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Article",
    "description": "Create your blog content"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "type": "string",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "description": {
      "type": "text",
      "maxLength": 80,
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "slug": {
      "type": "uid",
      "targetField": "title"
    },
    "cover": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "author": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::author.author",
      "inversedBy": "articles"
    },
    "category": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::category.category",
      "inversedBy": "articles"
    },
    "blocks": {
      "type": "dynamiczone",
      "components": [
        "shared.media",
        "shared.quote",
        "shared.rich-text",
        "shared.slider"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    }
  }
}
```

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Moving this to the proper repo

**Comment by derrickmehaffy** [comment]
For some reason can't migrate this issue but can you please create a new issue on https://github.com/strapi/starters-and-templates
