### ISSUE TITLE
API Token with a duration of 30 or 90 days can not be created from admin UI

### ISSUE THREAD

**Issue by eeni** [strapi/strapi#14802]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: 4.4.0
- Database: PG 14
- Operating system: Mac OS Monterey

### Describe the bug

API Token creation with a duration of 30 or 90 days is not possible from the Strapi Admin UI.
I get a 500 Status Code error, and the below error on my Strapi Application Logs 
``error: insert into "strapi_api_tokens" ("access_key", "created_at", "description", "expires_at", "lifespan", "name", "type", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" - value "7776000000" is out of range for type integer``  

Looks like on the "strapi_api_tokens" database table the column "lifespan" has an `integer` datatype which can not hold the milliseconds value"7776000000" which is the conversion of 90 days. 

### Steps to reproduce the behavior

1. Go to 'Strapi Admin'
2. Click on 'Settings -> API Tokens'
4. Create a new token with a Token Duration of 30 or 90 days.

### Expected behavior

You expect that the API Token is going to be created successfully.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by simotae14** [comment]
Hello, @eeni and Hugh Lilly we have investigated the issue and we plan to release a bug fix soon. Thanks
