### ISSUE TITLE
New Collections or Fields are not displayed in Content Manager

### ISSUE THREAD

**Issue by T-Gwynbleidd** [strapi/strapi#14818]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.4.6
- Yarn version: 1.22
- Database: Postgres
- Operating system: Windows 11

### Describe the bug

A new collection has been created and fields added to an existing collection. Everything is fine on my local, the only difference to the deployed site is my local DB which is SQLite.

The site is deployed to Heroku following the Strapi documentation. Once deployed the fields are visible, but after an indeterminate amount of time time, it is as if the site partially forgets them and an Internal Server Error is thrown.

I say partially because if viewed in the Content-Type Builder the fields are there, but when selecting Configure the View (selected from Content-Type Builder) those new fields are missing. Trying to load those Collections/Single Types from the Content Manager returns Internal Server Error.

Any permissions that are set and data entered for the new fields are lost.

### Steps to reproduce the behavior

1. Deploy site, all is well.
2. After an indeterminate amount of time passes.
3. Go to Content Manager
4. Click on the new Collection/Single Type, or existing Collection/Single Type that has new fields
5. Page does not load, instead breaking.
6. See the error in dev console.

### Expected behavior

New fields and collection/single types persist, in both the Content Manager and Content-Type Builder

### Screenshots
Strapi Content Type Builder, showing the new Collection.

![image](https://user-images.githubusercontent.com/1684872/200821989-432927f6-c3a8-4802-b871-bed3e49e101c.png)

After indeterminate time...
Strapi Content Manager, now missing the new Collection Type.

![image](https://user-images.githubusercontent.com/1684872/200821793-986753a0-9ac4-4aa5-86af-5c7991131407.png)

Here's the issue with the new fields, they can be seen in the Content-Type Builder.

![image](https://user-images.githubusercontent.com/1684872/200823117-652c231c-ac78-4c4d-97f3-c4be5010fd42.png)

But, not when configuring the view.

![image](https://user-images.githubusercontent.com/1684872/200823629-8cc4598d-b3d1-47da-b597-92bd0fc6f359.png)

If trying to load the Collection/Single Type in the Content Manager it breaks the web page showing nothing, except in the console.

![image](https://user-images.githubusercontent.com/1684872/200823800-ed8c3aa3-4ce2-42ef-bdd6-d87c5d2234fb.png)

### Additional context

Redeploying fixes the issue, but any previously set permissions or data for those fields is lost.

**Comment by derrickmehaffy** [comment]
This sounds like your Heroku instance isn't actually using the PostgreSQL database but is instead using SQL. What is the contexts of your config folder? Specifically do you have say a `./config/env/production/database.js` and in Heroku do you have `NODE_ENV` set to `production`?
