### ISSUE TITLE
Cannot add or delete admin role, getting "Community Edition - You have reached the limit"

### ISSUE THREAD

**Issue by edlefebvre** [strapi/strapi#14815]
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.18.0
- Strapi version: 4.4.7
- Database: SQLite (dev environment) and MariaDB (staging environment)
- Operating system: fedora 36 (dev env) ubuntu 22.04 (staging environment)

### Describe the bug

On dev environment (local), I have three admin roles. When trying to delete a role, I get the popup message "Community Edition - You have reached the limit" .

When deployed on staging environment (distant server, git repo), I use MariaDB. I have only one admin role (the default one) and I can't add more, I get the popup message "Community Edition - You have reached the limit" .

### Steps to reproduce the behavior

1. Go to Settings
2. Add 3 roles
3. Try to delete one of these roles

### Expected behavior

Should let me delete a role (local env). Should let me add a role when there is only one existing (staging env).

### Additional context

The staging environment is using the same git repo as the local environment, but not the same database engine.

**Comment by derrickmehaffy** [comment]
This is currently intended, we do plan to make the RBAC system free in the CE I believe next quarter. For more information and to share your feedback please see this: https://feedback.strapi.io/feature-requests/p/free-rbac-community-edition
