### ISSUE TITLE
Error when setup the development environment, npm run setup return "Unexpected end of JSON input while parsing near '...e,"directories":{},"d'"

### ISSUE THREAD

**Issue by rizalibnu** [strapi/strapi#1481]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: @3.0.0-alpha.12.6
- **Database**: MongoDB
- **Operating system**: macOS High Sierra v10.13.4

**What is the current behavior?**

When attempting to setup the development environment and I run `npm run setup` at the root of the project directory, it's error.

```
> @3.0.0-alpha.12.6 setup /Users/xxx/node/strapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.12.6 clean:all /Users/xxx/node/strapi
> npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules


> @3.0.0-alpha.12.6 removesymlinkdependencies /Users/xxx/node/strapi
> node ./scripts/removeSymlinkDependencies.js

npm notice created a lockfile as package-lock.json. You should commit this file.
+ strapi-lint@3.0.0-alpha.12.6
added 1 package and updated 1 package in 3.868s
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! Unexpected end of JSON input while parsing near '...e,"directories":{},"d'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-06-28T10_14_38_170Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.12.6 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @3.0.0-alpha.12.6 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-06-28T10_14_38_228Z-debug.log
```

**Steps to reproduce the problem**

1. [Fork the repository](https://github.com/strapi/strapi) to your own GitHub account.
2. Clone it to your computer `git clone https://github.com/strapi/strapi.git`.
3. Run `npm run setup` at the root of the directory.

**What is the expected behavior?**
Working :)

**Suggested solutions**
-

**Comment by rizalibnu** [comment]
Hi @lauriejim i've updated steps to reproduce, i cloned with HTTPS `git clone https://github.com/strapi/strapi.git`
But I think it's same.

**Comment by ichals09** [comment]
@rizalibnu, git clone git@github.com:strapi/strapi.git not work on windows

**Comment by ichals09** [comment]
Informations

Node.js version: 8.9.4
npm version: 6.1.0
Strapi version: 3.0.0-alpha.12.5
Database: MongoDB
Operating system: Windows 10 Home Single Language

I got this error when i run `npm run setup`

`> @3.0.0-alpha.12.6 setup X:\xxx\gitstrapi
> npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean


> @3.0.0-alpha.12.6 clean:all X:\xxx\gitstrapi
> npm run removesymlinkdependencies && rm -rf package-lock.json && rm -rf packages/*/package-lock.json && rm -rf packages/*/node_modules


> @3.0.0-alpha.12.6 removesymlinkdependencies X:\xxx\gitstrapi
> node ./scripts/removeSymlinkDependencies.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ strapi-lint@3.0.0-alpha.12.6
added 69 packages and updated 1 package in 99.798s
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 68 packages in 44.542s
5.1.0
v8.9.4

🕓  The setup process can take few minutes.

📦  Linking strapi-utils...
✅  Success

📦  Linking strapi-lint
✅  Success

📦  Linking strapi-generate...
✅  Success

📦  Linking strapi-generate-api...
✅  Success

📦  Linking strapi-helper-plugin...
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! Unexpected end of input at 1:23998
npm ERR! bc8934","tarball":"https://registry.npmjs.org/caniuse-lite/-/caniuse-
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     X:\Users\XXX\AppData\Roaming\npm-cache\_logs\2018-06-29T08_24_40_514Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.12.6 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @3.0.0-alpha.12.6 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by derrickmehaffy** [comment]
@ichals09 There are known issues when working with Strapi on windows, can you test using the Windows WSL or a linux VM?

**Comment by rizalibnu** [comment]
I solved it `npm cache clean --force`
and then `npm run setup` again
