### ISSUE TITLE
Can't change frontend users: role.connect field must have at least 1 items

### ISSUE THREAD

**Issue by Zielgestalt** [strapi/strapi#14826]
### Required System information

- Node.js version: 16.17.0
- NPM version:  8.15.0
- Strapi version: 4.5.0
- Database: postgrey
- Operating system: mac os

### Describe the bug

If I want to change an existing frontend user (plugin-user-permissions) already connected to a role (e.g. Authenticated) I can't save the changes. I get the warning: role.connect field must have at least 1 items. When I change the role to a different value, everything works fine.

### Steps to reproduce the behavior

1. Create a user with role 'Authenticated' and save the user
2. Change a value of a field (except the role)
3. Click on 'save'
5. See error 'role.connect field must have at least 1 items'

### Expected behavior

Successful save action

**Comment by gstrainovic** [comment]
I had the same problem after switching from 4.4.3 to 4.4.5. Am back to 4.4.3, works again.

**Comment by hsnbsst** [comment]
i had the same problem v4.5.0

**Comment by pcriadoperez** [comment]
Having the same issue

**Comment by Mikeez** [comment]
Relation mapping is not set correctly

**Comment by Zielgestalt** [comment]
Maybe related to this: https://github.com/strapi/strapi/issues/14832

**Comment by alt-sandip-baikare** [comment]
I am facign same issue. Could not able to update the user.

**Comment by dubem-design** [comment]
Same here

**Comment by bskuratov** [comment]
The same on my side

**Comment by iantrudell** [comment]
Also having this issue with 4.5.0

**Comment by Florian-crg** [comment]
To temporary avoid this issue while you set your changes set the field **role** to another value. It will save your data without error. Then you can set back the role where it was.

**Comment by tnntwister** [comment]
Same here. Thanks Florian for the tip, it works.

**Comment by diacu** [comment]
For me it doesn't work. If I try with another role, I get Internal Server Error

**Comment by Zielgestalt** [comment]
For me it works only if I save the other role first and then save again with the original role.

**Comment by diacu** [comment]
> For me it works only if I save the other role first and then save again with the original role.

I tried this and it didn't work. With Authenticated role I get this error. With other roles (custom) I just get "Internal Server Error". I didn't have the time to investigate, I downgraded for the moment.

**Comment by t1tdev** [comment]
having same issues (cant update user , getting a 403 response on new controllers, and the role.connect error when attempting to update a user from strapi)

**Comment by HonzaVrkota** [comment]
same for me. [@Florian-crg](https://github.com/strapi/strapi/issues/14826#issuecomment-1312762273) - this temporary works, but it's annoying...

**Comment by abdhass** [comment]
im having same issue. Will be watching this

**Comment by adamhancock** [comment]
Version 4.5.1 fixes the role.connect error for me.

**Comment by Zielgestalt** [comment]
I can confirm this is fixed in 4.5.1.
