### ISSUE TITLE
 REST API: One-to-many relations in dynamic zone components are not populated

### ISSUE THREAD

**Issue by dm4t2** [strapi/strapi#14829]
### Required System information

- Node.js version: v16
- NPM version: v8
- Strapi version: v4.5.0
- Database: PostgreSQL
- Operating system: Ubuntu 22.04

### Describe the bug

I'm currently migrating from v3 to v4 and got stuck while trying to deeply populate one-to-many relations in dynamic zone components. For example, I have an "article" collection type with a "restrictions" dynamic zone that contains a one-to-many relation to a "country" collection type.

According to the [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#deeply-populate-a-dynamic-zone-with-2-components) the URL `/api/articles?populate[restrictions][populate]=%2A` should deeply populate, but it doesn't work.

I also tried the [Populate deep plugin](https://market.strapi.io/plugins/strapi-plugin-populate-deep) without success.

### Steps to reproduce the behavior

1. Clone the [reproduction repo](https://github.com/dm4t2/strapi-reproduction) with included SQLite db.
2. Start the Strapi server
3. Open http://localhost:1337/api/articles?populate[restrictions][populate]=%2A or http://localhost:1337/api/articles?populate=deep

### Expected behavior

countries relation should be populated.

### Screenshots

![image](https://user-images.githubusercontent.com/11592259/201060840-34798c26-9b73-4830-9d18-7404808f118d.png)

### Additional context

Credentials for Admin UI: admin@strapi.com - Admin1234

**Comment by kellycampbell** [comment]
Make sure you have set the permissions for that second collection type and have also published your collection entries.

**Comment by dm4t2** [comment]
Thanks, the missing permissions caused the issue. In v3, the relations are also populated without setting the permissions for some reason, probably a bug. Might be worth to be mentioned in v3 to v4 migration docs.
