### ISSUE TITLE
Content-Manager: able to choose which fields to show in the list page

### ISSUE THREAD

**Issue by phanhoangloc** [strapi/strapi#1482]
**Informations**

* **Node.js version**: 9.10.1
* **npm version**: 5.6.0
* **Strapi version**: @3.0.0-alpha.12.5
* **Database**: MongoDB
* **Operating system**: macOS High Sierra v10.13.5

First, I'd like to thanks the Strapi team for a nice library. It helps me save tons of time when building a new web admin. Great work!

As far as I know, the list page only shows 4 first fields of a model.

I wonder whether we can dynamically specify which field we'd like to see on the UI. It could be any model attribute that we have created.

Example: 
I've created 10 fields for the model A `F1, F2, F3, F4, F5, F6, F7, F8, F9, F10`

**What is the current behavior?**
It always shows `F1, F2, F3, F4`

**What is the expected behavior?**
I can choose whatever I'd like to show. i.e `F1, F8, F9`

I tried to make some changes to the plugin and technically, I can say it's possible. I'd be happy to submit a PR for it. But first, I'd like to listen to your ideas on the topic.
Do you think it's a common need?

**Comment by derrickmehaffy** [comment]
@phanhoangloc This feature is already in development. You can read more on the Strapi blog: https://blog.strapi.io/roadmap-update-2-stability-tests-experience/

Their expected release date on this is July 23rd however delays always happen.

**Comment by phanhoangloc** [comment]
Cool. Thanks for sharing @derrickmehaffy !
