### ISSUE TITLE
Updating from Strapi 4.4.7 to 4.5.0: error on start up - relation already exists

### ISSUE THREAD

**Issue by adam-t-knight** [strapi/strapi#14833]
### Required System information

- Node.js version: v18.12.0
- NPM version: 8.19.2
- Strapi version: 4.5.0
- Database: Postgres
- Operating system: MacOs

### Describe the bug

When updating my Strapi project from 4.4.7 to 4.5.0, when I start up the project I receive an error that a relation already exists.

### Steps to reproduce the behavior

Update your Strapi project to 4.5.0 and run strapi develop

### Expected behavior

Strapi start normally

### Screenshots

<img width="1455" alt="Screenshot 2022-11-10 at 14 21 43" src="https://user-images.githubusercontent.com/78620471/201105357-5b590a65-dad1-43c1-babe-878cfbc8425f.png">

### Additional context

I removed node_modules, package-lock.json, .cache, build and re-ran npm install. Still got the same error

**Comment by derrickmehaffy** [comment]
Duplicate https://github.com/strapi/strapi/issues/14832
