### ISSUE TITLE
Filtering nested objects returns null in GraphQL

### ISSUE THREAD

**Issue by Blacknosaur** [strapi/strapi#1484]
**Informations**
- Node: v10.5.0
- npm: v6.1.0
- Strapi: v3.0.0-alpha.12.6, tried in v3.0.0-alpha.13.0.1 too
- MongoDB: v3.4.15
- OS: Ubuntu 16.04.4 LTS

**What is the current behavior?**
In a model with one-to-many relationships, if you try to filter the nested object with a "where" statement through GraphQL it always returns null

**Steps to reproduce the problem**

`{
	users{
		_id
		encuestas( where: { valoracion: 5} ) {
			_id
			valoracion
		}
	}
}`

User and encuesta have a one-to-many relationship. The query returns always null but if you delete the filter it works.

Error log:
`
TypeError: Cannot convert object to primitive value
    at parseFloat (<anonymous>)
    at isNumeric (/home/ubuntu/project/api/node_modules/strapi-utils/lib/models.js:15:17)
    at _.forEach (/home/ubuntu/project/api/node_modules/strapi-utils/lib/models.js:462:24)
    at /home/ubuntu/project/api/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/ubuntu/project/api/node_modules/lodash/lodash.js:3010:24)
    at /home/ubuntu/project/api/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/home/ubuntu/project/api/node_modules/lodash/lodash.js:9342:14)
    at Object.convertParams (/home/ubuntu/project/api/node_modules/strapi-utils/lib/models.js:457:7)
    at encuestas (/home/ubuntu/project/api/plugins/graphql/services/GraphQL.js:570:59)
    at resolveFieldValueOrError (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:531:18)
    at resolveField (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:495:16)
    at /home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:364:18
    at Array.reduce (<anonymous>)
    at executeFields (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:361:42)
    at collectAndExecuteSubfields (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:772:10)
    at completeObjectValue (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:762:10)
    at completeValue (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:660:12)
    at completeValueWithLocatedError (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:580:21)
    at completeValueCatchingError (/home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:556:21)
    at /home/ubuntu/project/api/plugins/graphql/node_modules/graphql/execution/execute.js:684:25
    at Array.forEach (<anonymous>)
    at forEach (/home/ubuntu/project/api/plugins/graphql/node_modules/iterall/index.js:83:25)
`

This query works flawlessly in Strapi 3.0.0-alpha.12.5 but fails in 3.0.0-alpha.12.6

**What is the expected behavior?**
It should return an array with the items which meet the condition or an empty array if none does.

**Suggested solutions**
I don't know how to fix it.

**Comment by lauriejim** [comment]
Hello @Blacknosaur . I ping @johannpinson on this issue cause it's related to GraphQL.
Did you try after migrate your project or with a fresh project with last version of Strapi ?

**Comment by Blacknosaur** [comment]
The project was working on 12.3 but we move it to a new server with a fresh install of the last version (12.6). At first I didn't noticed Strapi version had changed, but when I downgraded to 12.3 it worked again. To check which was the problematic version I pushed it to 12.4 and 12.5 without problems but everything failed again when retried 12.6 (not a fresh install this second time)

**Comment by lauriejim** [comment]
If you want migrate your application you have to follow migration guides https://github.com/strapi/strapi/wiki
I thinks it's why you have your issue.

If you create a new project with alpha.12.6 and you make your graphql query I think it will work. Can you confirm that ?

**Comment by Blacknosaur** [comment]
We have just tried with a clean project in alpha.12.6, same result. When I try to filter a nested object it returns null instead of the filtered array, if the filter is out it returns the complete array without any problems

**Comment by johannpinson** [comment]
@Blacknosaur 

Can you give me an example of your db structure?
If you can, feel free to copy/paste your models json file.

**Comment by BroTrue** [comment]
Got the same problem. I already try to create clean db, make such sturcture
products
--title
--logo
contact
--name
--surname

and relation between them many -to-many

when I try it on `http://localhost:1337/playground `query with ` where: {}` its give me  `Cannot convert object to primitive value`

**Comment by Blacknosaur** [comment]
In the example I posted before I queried model "Encuesta" nested into "User". These are User.settings.json and Encuesta.settings.json

`{
  "connection": "default",
  "info": {
    "name": "user",
    "description": ""
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "encuestas": {
      "collection": "encuesta",
      "via": "user"
    },
    "sistematicaentrada": {
      "collection": "sistematicadato",
      "via": "user"
    },
    "gestiondato": {
      "collection": "gestiondato",
      "via": "user"
    },
    "status": {
      "multiple": false,
      "type": "boolean"
    },
    "idsol": {
      "multiple": false,
      "type": "string"
    },
    "picture": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    },
    "store": {
      "collection": "store",
      "via": "users",
      "dominant": true
    },
    "name": {
      "multiple": false,
      "type": "string",
      "required": true
    },
    "surname": {
      "multiple": false,
      "type": "string"
    },
    "idsol2": {
      "multiple": false,
      "type": "string"
    },
    "idsol3": {
      "multiple": false,
      "type": "string"
    },
    "phone2": {
      "multiple": false,
      "type": "string"
    },
    "phone3": {
      "multiple": false,
      "type": "string"
    },
    "phone": {
      "multiple": false,
      "type": "string"
    },
    "retos": {
      "collection": "reto",
      "via": "users"
    },
    "itinerarios": {
      "collection": "itinerario",
      "via": "users"
    },
    "avanceretos_": {
      "collection": "avancereto",
      "via": "user"
    }
  },
  "collectionName": "users-permissions_user"
}`

`{
  "connection": "default",
  "collectionName": "encuesta",
  "info": {
    "name": "encuesta",
    "description": "Encuestas valoraciones a clientes"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "user": {
      "model": "user",
      "via": "encuestas",
      "plugin": "users-permissions"
    },
    "opinion": {
      "multiple": false,
      "type": "text"
    },
    "tipocliente": {
      "multiple": false,
      "type": "string"
    },
    "fecha": {
      "multiple": false,
      "type": "date"
    },
    "valoracion": {
      "multiple": false,
      "type": "decimal"
    },
    "comercial": {
      "multiple": false,
      "type": "decimal"
    }
  }
}`

As you can see, "Encuesta" isn't the only model related to "User". "Sistematicaentrada" and "Gestiondato" are pretty similar to "Encuesta" and have exactly the same problem. I don't post their models for not flooding this.

**Comment by Blacknosaur** [comment]
I have just followed the migration guidelines to update the project to alpha@13.0.1 and it have the same problem than alpha@12.6

**Comment by Tonours** [comment]
Hey @lauriejim :wave: ! 

After doing some tests, it appears that the `isNumeric` function in `lib/models.js` of `strapi-utils` package could return false positive for object.

A workaround for this is to check that the value is not an Object.

```js
const isNumeric = (value) => {
  return !_.isObject(value) && !isNaN(parseFloat(value)) && isFinite(value);
};
````

After this update, you will be able to perform where requests.

Let me know if you want i open a PR for this.

**Comment by lauriejim** [comment]
Hi @Tonours !
If your code fix an issue, of course I will appreciate a pull request ;)

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
Any update about this issue ?

**Comment by Tonours** [comment]
@lauriejim Hey ! I can do a PR at the end of the week
