### ISSUE TITLE
strapi 4.5.0 graphql query relation field pagination setting is invalid

### ISSUE THREAD

**Issue by fuxianwei** [strapi/strapi#14841]
### Required System information

- Node.js version: v16.17.1
- NPM version: 8.15.0
- Strapi version: 4.5.0
- Database: sqlite3 @7.6.2
- Operating system: Mac os

### Describe the bug

strapi 4.5.0 graphql query relation field pagination setting is invalid

### Steps to reproduce the behavior

1. For example, executing graphql queries `query GetFields(
  $locale: I18NLocaleCode!
  $slug: String
  $pagination: PaginationArg
) {
  fields(
    locale: $locale
    filters: { slug: { eq: $slug } }
    sort: ["order:asc", "publishedAt:asc"]
    pagination: $pagination
  ) {
    data {
      id
      attributes {
        __typename
        locale
        name
        slug
        description
        introduce
        publishedAt
        teams(pagination: {pageSize: 4}) {
          data {
            attributes {
              slug
              name
              avatar {
                ...FileParts
              }
            }
          }
        }
      }
    }
  }
}
fragment FileParts on UploadFileEntityResponse {
  data {
    id
    attributes {
      alternativeText
      width
      height
      mime
      url
      formats
    }
  }
}`
2. 'Query the associated field teams in fields, `teams(pagination: {pageSize: 4})` pagination setting is invalid'
3. In fact, there are more than four teams in the query, so the paging setup is invalid
<img width="1680" alt="截屏2022-11-13 17 08 32" src="https://user-images.githubusercontent.com/1736689/201514291-7a8420d5-214b-4891-b84d-3e5e45f685bd.png">

### Expected behavior

According to the teams pagination Settings, four relevant records were queried

**Comment by DanielSusanu** [comment]
I am having the same issue. Passing pageSize:4 and there response contains all entries.

**Comment by dnsdrs** [comment]
I upgraded to version >4.5 and am confronted to the same bug. This is quite annoying 😢

**Comment by Marc-Roig** [comment]
Hello @fuxianwei @dnsdrs we have reproduced your issue and we are looking at it, we will try to provide a solution asap.

**Comment by Marc-Roig** [comment]
After some delay, here is the PR with the fix https://github.com/strapi/strapi/pull/15715 :) 

We will aim to release this in 4.6.1 / 4.6.2

**Comment by Marc-Roig** [comment]
The fix will be released on Feb 15th on 4.6.2 :)

**Comment by reimertz** [comment]
Thanks @Marc-Roig for all the hard work! 

I see that the deadline for 4.6.2 is Feb 22nd. Just want to confirm if this is about to be released (today / tomorrow) or if we're looking at next week. If so, I might patch in these fixes till 4.6.2 are released.
