### ISSUE TITLE
Incomplete type generation for graphql

### ISSUE THREAD

**Issue by Olli1080** [strapi/strapi#14843]
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: e.g. 4.4.7 and 4.5.0
- Database: postgresql
- Operating system: Windows 11

### Describe the bug

.*Entity{, Response, ResponseCollection}, .*RelationResponseCollection
are generated as {} in NexusGenRootTypes
The same are generated semi-correctly in NexusGenFieldTypes but with references to invalid/imcomplete NexusGenRootTyes

May be related to graphql-nexus/nexus#839
E.g.

```
UploadFileEntity: {};
UploadFileEntityResponse: {};
UploadFileEntityResponseCollection: {};
UploadFileRelationResponseCollection: {};
```

### Steps to reproduce the behavior

1. Create a new strapi instance
2. Enable typescript artifacts for graphql-plugin
3. Generate with npx strapi develop

### Expected behavior

The types should contain references to corresponding fields.

### Screenshots

.

### Code snippets

.

### Additional context

.

**Comment by derrickmehaffy** [comment]
Hello, we are marking this issue as closed as it has been combined into a centralized Tracking issue for all Typescript issues.

Please see: #15225 

If you believe this was merged into the tracking issue in error please let us know. For any further debug information please use the tracking issue.

Thanks!
