### ISSUE TITLE
My custom tsvector fields on multiple tables disappeared after upgrading to 4.5.0 

### ISSUE THREAD

**Issue by ntarandek** [strapi/strapi#14847]
### Required System information

- Node.js version: 16.5.0
- Yarn version: 1.22.17
- Strapi version: 4.5.0
- Database: PostgreSQL
- Operating system: macOS 12.6

### Describe the bug

Immediately after upgrading from 4.4.7 to 4.5.0 and resolving issues with duplicate values (mentioned in other issue reports) I noticed that my fully custom TSVector fields were missing. Therefor saving the data was not working with an error like this:

`error: update "products" set "name" = $1, ..., "updated_at" = $46 where ("id" = $47) - record "new" has no field "tsv"`

### Steps to reproduce the behavior

1. Update the Strapi version, rebuild and restart
2. Try to save content for tables with custom fields and related triggers
3. See error

### Expected behavior

My custom fields not to disappear from DB.

### Additional context

SQL script for one custom field and related indexes and triggers that I am using:

`ALTER TABLE products ADD COLUMN tsv tsvector;`

`CREATE INDEX products_search_idx ON products USING GIN (tsv);`

`CREATE OR REPLACE FUNCTION products_search_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  new.tsv = to_tsvector(
    COALESCE(new.name, '') 
    || COALESCE(new.description, '') 
    || COALESCE(new.rich_description, '') 
    || COALESCE(new.text_properties, '')
  );
  RETURN new;
END
$$;`

`CREATE OR REPLACE TRIGGER products_tsv_update
BEFORE INSERT OR UPDATE 
ON products
FOR EACH ROW EXECUTE PROCEDURE products_search_trigger();`

and a simple update command to force new field to be filled:

`UPDATE products SET name = name;`

I have resolved it by re-running the scripts but it might be important to take a look at this issue.

**Comment by ntarandek** [comment]
Tried to update to 4.5.1 - same thing happened.

**Comment by ntarandek** [comment]
Another update - this also happens when I change the model where custom field exists. Since I did not see this happening until now (maybe by chance), seems important to note.

**Comment by derrickmehaffy** [comment]
Hi @ntarandek can you share your custom field code? I've double checked our color picker custom field and didn't see an issue so I'm wondering what is different about your implementation?

**Comment by ntarandek** [comment]
> Hi @ntarandek can you share your custom field code? I've double checked our color picker custom field and didn't see an issue so I'm wondering what is different about your implementation?

I did not need real Strapi custom field with inputs for this since it is only used for search which I perform via raw SQL - so no real "plugin" implementation was done here. Basically my "implementation" boils down to executing custom SQLs (which I provided) to create DB fields, triggers and other stuff and then calling custom SQL to grab what I need for futher Strapi based queries.

I resolved my issue of missing fields on DB changes by adding a bit of DB bootstraping logic which simply recreates the fields on restart (when needed). These fields are automatic anyway so no user inputs are lost and functionality is kept as it should be.

**Comment by nathan-pichon** [comment]
Hey @ntarandek,

Thanks for bringing this issue to our attention. Sorry for the delay.

We can't guarantee that these columns will be retained between upgrades or restarts since Strapi manages the database schema itself. However, there are a couple of things you can try to solve this issue.

First, you might want to define your columns in the `schema.json` file instead. This will ensure that your changes are tracked and managed by Strapi. You can learn more about writing schema.json in our [documentation](https://docs.strapi.io/dev-docs/backend-customization/models#model-attributes).

Alternatively, you could try using Strapi's custom fields feature. This lets you add custom fields to your content types without modifying the underlying database schema. You can check out our [documentation](https://docs.strapi.io/dev-docs/custom-fields) to learn more about custom fields.

**Comment by ntarandek** [comment]
@nathan-pichon Thank you for the reply.

I will check out the custom fields very soon for other purposes, but for the mentioned index fields, my solutions works for now (and since it is live already - I am not too eager to mess around with it now :))

As far as I am concerned, this can be closed.
