### ISSUE TITLE
Complex Filter- Internal Server Error when use [$or],[$and] in filter

### ISSUE THREAD

**Issue by kogutu** [strapi/strapi#14854]
### Required System information

- Node.js version: 16.13.1
- NPM version:  8.3.0
- Strapi version:4.5
- Database:  10.5.17-MariaDB - MariaDB Server
- Operating system: CentOS Linux 8

### Describe the bug
I try use complex filter [$or] and [$and]  in my request api. When use $or or $end I get Internal Server Error. When remove from my request complex filter item [$or],[$and] - server return response without error.

### Steps to reproduce the behavior

1. Execute request
` /api/orders?pagination[start]=0&pagination[limit]=50&populate=*&filters[$or][shipping_address][lastname][$contains][0]=grab&filters[$or][shipping_address][firstname][$contains][0]=grab`

2. I get Internal Server Error
3. On Strapi Console I get more info about error: 
```
error: value.map is not a function
value.map is not a function
    at processWhere (/node_modules/@strapi/database/lib/query/helpers/where.js:127:28)

```

**Comment by derrickmehaffy** [comment]
Can you give me a bit more information about your content model structure?

Is `shipping_address` a relation or a component?
