### ISSUE TITLE
AVIF images getting dimensions null x null

### ISSUE THREAD

**Issue by multipliedtwice** [strapi/strapi#14857]
### Required System information

- Node.js version: 16.18.1
- NPM version: latest
- Strapi version: latest
- Database: pg
- Operating system:

### Describe the bug

When I upload images in AVIF format - dimensions don't appear. JPEG works fine.

### Steps to reproduce the behavior

1. Upload AVIF image
2. Open file details

### Expected behavior

Dimensions shown

### Screenshots

![image](https://user-images.githubusercontent.com/33694447/201716107-11e9f08b-31e0-4511-8af2-1ec7b43a4ddf.png)

**Comment by thousandsofraccoons** [comment]
Also, renaming of AVIF files doesn't work

**Comment by derrickmehaffy** [comment]
Confirmed the dimensions issue (but not the renaming issue) using the following sample file:

https://raw.githubusercontent.com/link-u/avif-sample-images/master/fox.profile0.10bpc.yuv420.avif
