### ISSUE TITLE
Subtle UI bugs for relational fields

### ISSUE THREAD

**Issue by tomardern** [strapi/strapi#14877]
### Required System information

- Node.js version: node v16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.0
- Database: Postgres
- Operating system: Linux/Docker

### Describe the bug
I am not a designer, and this could very be "my taste", but the new relational field UI looks a little unpolished vs the other areas of strapi. 

### Steps to reproduce the behavior

1. Create a content type with a relational field
2. Add some items to that field

### Expected behavior
- Additional padding around the status badge
- Vertical alignment of text isn't centred
- A bullet point is shown next to the status, unlike elsewhere in strapi where it is not shown
- Right hand scroll bar hidden, which makes the area non-obviously scrollable.

### Screenshots

![image](https://user-images.githubusercontent.com/1135454/201966289-2901f12a-0f4e-44c2-85d2-13c645c6972c.png)

### Code snippets

N/a

### Additional context

N/a

As always, keep up the great work!

**Comment by gu-stav** [comment]
@tomardern Could you please add information about which browser/ operating system you are using?

**Comment by z0lo13** [comment]
@gu-stav I am having same issue 

[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)

**Comment by derrickmehaffy** [comment]
If you could also provide your package.json that would be helpful as well to see if many a community package is causing some conflicts

**Comment by gu-stav** [comment]
Hello 👋🏼 It looks like as if you are using on older version of the admin UI - the bullet in front of the status badge should be gone and the padding should look differently.

Could you very if the following steps would solve your problem:

- delete `.cache` and `build` folders
- rebuild the admin UI by running `npm run build` or `yarn build` followed by `npm run start` or `yarn start`

**Comment by tomardern** [comment]
Removing `.cache` and `build` directories worked - looking much better :) 

![image](https://user-images.githubusercontent.com/1135454/203575487-aea054c4-6bf9-4288-9d56-c6636c080352.png)

**Comment by z0lo13** [comment]
@tomardern 
@gu-stav 

For it did not help indeed. Below is my package .json

`"devDependencies": {},
  "dependencies": {
    "@bn-digital/strapi-plugin-field-uuid": "^1.1.7",
    "@notum-cz/strapi-plugin-content-versioning": "^0.4.4",
    "@strapi/plugin-graphql": "^4.5.2",
    "@strapi/plugin-i18n": "4.5.2",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "4.5.2",
    "@strapi/provider-upload-cloudinary": "^4.5.2",
    "@strapi/strapi": "4.5.2",
    "moment": "^2.29.4",
    "mysql": "2.18.1",
    "sharp": "^0.31.2",
    "strapi-plugin-fast-content": "^1.0.0",
    "strapi-plugin-fuzzy-search": "^1.10.2",
    "strapi-plugin-import-export-entries": "^1.18.0",
    "strapi-plugin-menus": "^1.1.0",
    "strapi-plugin-placeholder": "^4.3.6",
    "strapi-plugin-sitemap": "boazpoolman/strapi-plugin-sitemap#beta",
    "strapi-plugin-vercel-deploy": "^1.3.1"
  },`

**Comment by joshuaellis** [comment]
> @tomardern @gu-stav
> 
> For it did not help indeed. Below is my package .json
> 
> ```
> "devDependencies": {},
>   "dependencies": {
>     "@bn-digital/strapi-plugin-field-uuid": "^1.1.7",
>     "@notum-cz/strapi-plugin-content-versioning": "^0.4.4",
>     "@strapi/plugin-graphql": "^4.5.2",
>     "@strapi/plugin-i18n": "4.5.2",
>     "@strapi/plugin-seo": "^1.7.7",
>     "@strapi/plugin-users-permissions": "4.5.2",
>     "@strapi/provider-upload-cloudinary": "^4.5.2",
>     "@strapi/strapi": "4.5.2",
>     "moment": "^2.29.4",
>     "mysql": "2.18.1",
>     "sharp": "^0.31.2",
>     "strapi-plugin-fast-content": "^1.0.0",
>     "strapi-plugin-fuzzy-search": "^1.10.2",
>     "strapi-plugin-import-export-entries": "^1.18.0",
>     "strapi-plugin-menus": "^1.1.0",
>     "strapi-plugin-placeholder": "^4.3.6",
>     "strapi-plugin-sitemap": "boazpoolman/strapi-plugin-sitemap#beta",
>     "strapi-plugin-vercel-deploy": "^1.3.1"
>   },
> ```

can you run `npm ls @strapi/design-system` and share what that logs please?

**Comment by z0lo13** [comment]
@joshuaellis 

```
├─┬ @strapi/strapi@4.5.2
│ └─┬ @strapi/admin@4.5.2
│   └── @strapi/design-system@1.3.1
└─┬ strapi-plugin-vercel-deploy@1.3.1
  └─┬ @strapi/strapi@4.4.5
    └─┬ @strapi/admin@4.4.5
      ├── @strapi/design-system@1.2.5
      └─┬ @strapi/helper-plugin@4.4.5
        └── @strapi/design-system@1.2.5  deduped
```

**Comment by joshuaellis** [comment]
hm 🤔 I'd probably open this as a new issue because _in theory_ your plugin shouldn't interfere with your UI.
