### ISSUE TITLE
Adding hook were we can plug custom function and process

### ISSUE THREAD

**Issue by maru3l** [strapi/strapi#1488]
It's would be nice to have hook were we can plug our function in a process. Like the Wordpress way to make plugin with there's Filters and Actions.

https://codex.wordpress.org/Plugin_API/Filter_Reference

I'm actually working on something where I need to add some code in the `strapi-plugin-content-manager` and it's not optimal. With the hook, I would only have to attach my fonction to the hook and it will run when the hook will be process.

I think the Pub/Sub technique could be a good start.

**Comment by lauriejim** [comment]
Hello @maru3l !
We plan to have this in Strapi (not now, it's an hard work and it take many times). It will be so easy to customize anything !

**Comment by Aurelsicoko** [comment]
The hook system will be added with the rework of the plugins' architecture. Please refers to this card in our public roadmap https://portal.productboard.com/strapi/c/26-new-plugin-architecture.

Since we will implement this feature, I'm closing this issue.
