### ISSUE TITLE
Remove attributes  createdBy, updatedBy,  contributors ?!

### ISSUE THREAD

**Issue by sbacem** [strapi/strapi#149]
When creat new api 
by default i have 3 attributes in models

```
    "createdBy": {
      "model": "user"
    },
    "updatedBy": {
      "model": "user"
    },
    "contributors": {
      "collection": "user",
      "via": "cars"
    }

```
For many case, I don't  need this
how remove it ?

**Comment by pierreburgy** [comment]
@sbacem: you can remove it directly from your `Car.settings.js` file. Also, please remove the following code in `User.settings.json`:
```
"cars": {
  "collection": "cars",
  "via": "contributors"
}
```

**Comment by sbacem** [comment]
Thanks for quick reply.
I think for remove 
```
   "createdBy": {
      "model": "user"
    },
    "updatedBy": {
      "model": "user"
    },
```
It's necessary to set 

```
  "autoCreatedAt": false,
  "autoUpdatedAt": false 
```

For contributors when i remove the following code in User.settings.json

```
"cars": {
  "collection": "cars",
  "via": "contributors"
} 
```
i can't see  my list of Cras from admin panel ( I connected with my admin profile )

**Comment by pierreburgy** [comment]
```
"autoCreatedAt": false,
"autoUpdatedAt": false 
```
are related to the following fields: `createdAt` (not `createdBy`) and `updatedAt` (not `updatedBy`). So, you don't need to remove them, except if you want to remove `createdAt` and `updatedAt` fields.

Did you reload admin panel page?

**Comment by sbacem** [comment]
thanks, you are right ;-)

> createdAt (not createdBy) and updatedAt (not updatedBy)

but i want to remove `createdAt` and` updatedAt` for this i set  : 

```
"autoCreatedAt": false,
"autoUpdatedAt": false 
```
Yes reload admin panel page but I can't see the liste.
After many test, i think the issu it's when set  `"autoCreatedAt": false` or `"autoUpdatedAt": false`.

**Comment by pierreburgy** [comment]
Do you get any error in your web browser console?

**Comment by sbacem** [comment]
when I click  Models->cars
i have 
`Internal Server Error`

Link for my project 
https://strapi-sakli-bacem.c9users.io:8080/admin/#

Login : admin@admin.com
password: admin123

you can see my project code:
https://ide.c9.io/sakli_bacem/strapi

**Comment by sbacem** [comment]
@pierreburgy : i can't see list of cars in admin panel because the sort by default **createdAt**

_/strapi/explorer/car?sort=**createdAt**%20desc&limit=15_

How change it ?

**Comment by pierreburgy** [comment]
Using Node v4:
- Replace `createdAt` with `id` in `yourApp/api/admin/public/src/strapi/explorer/explorer-list.controller.js` (https://github.com/strapi/strapi-generate-admin/blob/ace3ef885234fe36d862fae303f22305958ec8bd/files/api/admin/public/src/strapi/explorer/explorer-list.controller.js#L64).
- Install bower and gulp (`npm install gulp bower -g`).
- In `yourApp/api/admin/public/` folder, run `npm install`, then `gulp dist`.
- Reload the web browser page.

**Comment by sbacem** [comment]
Thanks very much @pierreburgy
