### ISSUE TITLE
Dynamic zone empty after page reload or first load

### ISSUE THREAD

**Issue by Zharkan** [strapi/strapi#14907]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database:  postgres 15
- Operating system: ubuntu 22.04

### Describe the bug

Once the dynamic zone is edited and saved, if I reload the page then the content of the dynamic zone is missing. Sometimes it will come back if I unpublish and publish it again. Dynamic zone's content is still present in graphql or api requests.

### Steps to reproduce the behavior

1. Edit a dynamic zone
2. Reload the page
3. Content is missing

### Expected behavior

Dynamic zone's content should not disappear.

**Comment by Zharkan** [comment]
Upgrading to 4.5.0 makes the dynamic zones empty, can't edit anything without having to unpublish and republish..

**Comment by drazik** [comment]
I have kind of the same issue. On v4.5.3, when I update the content of a field in a dynamic zone, submit, then reload the page, I can see the previous content but not the one I just entered.

In my case, the REST API response also contains the old content. And I don't have draft system enabled so I can't publish / unpublish.

If I update the field with another value, then I see the previous one. I means I need to update the field two times with the same value to be able to see this value.

To be clear:

- There is not value in the field
- I enter value A then save => success
- Reload => the field is empty
- I enter value B then save => success
- Reload => I see value A in the field
- I enter value B then save => success
- Reload => I see value B in the field

**Comment by derrickmehaffy** [comment]
I'm unable to reproduce this on v4.5.4. Can some of you share your content-model structure?

Here is what I was testing with:

![image](https://user-images.githubusercontent.com/8593673/209356270-ff1c54fe-c850-42fb-83be-dcfc48750408.png)

**Comment by Zharkan** [comment]
![ksnip_20221223-160641](https://user-images.githubusercontent.com/53452535/209357242-8f71034d-0fd5-43af-aa2a-ff85176e3bf0.png)
Some of the components include relations, that might cause the issue ?
For example : the button component includes relations to other pages so the client can select pages from any collection and have the button linking to the right page on the frontend, I don't know if it makes sense to you.
![ksnip_20221223-160920](https://user-images.githubusercontent.com/53452535/209357589-5e00f692-9416-44c0-a394-41ca6bc6f66e.png)

**Comment by Zharkan** [comment]
Strapi v 4.5.5 fixed it for me. What about you @drazik ?

**Comment by derrickmehaffy** [comment]
Since we haven't had an update on this and the original reporter validated it as fixed I'll set this as closed.
