### ISSUE TITLE
Resized responsive images larger (in size, KB) than the original

### ISSUE THREAD

**Issue by kilobyte2007** [strapi/strapi#14902]
### Required System information

- Node.js version: 18.11.0
- NPM version: 8.19.2
- Strapi version: 4.5.0
- Database: MySQL
- Operating system: macOS and Ubuntu Server

### Describe the bug

When uploading a PNG image of a large size (1444px in width) with the responsive option enabled in Strapi, a responsive image is generated with a lower visual size (1000px in width), but with a much greater size in KB (509KB vs 199KB on the original) which makes creating the responsive images pointless.

Here is a link to the original: [Original 199KB - 1444px](https://www-new.personizely.net/strapi/uploads/cart_Abandonment_Offers_d24c225b75.png)
Here is a link to the large format: [Large - 509KB - 1000px](https://www-new.personizely.net/strapi/uploads/large_cart_Abandonment_Offers_d24c225b75.png)

### Steps to reproduce the behavior

1. Make sure the responsive images option is enabled
2. Upload the image to the media library
3. Open the image and compare the original image with the responsive ones

I have tried enabling the lossless option as well (even though I don't want it enabled as I want the original to always be perfect) and the result was still the same.

### Expected behavior

I was expecting since the image is smaller visually (px), it shouldn't be larger in size (kb), even when the optimization option is disabled, but I tried enabling it and still got the same result.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/14457
