### ISSUE TITLE
upgrading to 4.5.1 has server error on restart: relation "globals_unique" already exists

### ISSUE THREAD

**Issue by pentcle** [strapi/strapi#14912]
### Required System information

- Node.js version: 14.19.1
- NPM version:
- Strapi version: 4.5.1
- Database: postgresql
- Operating system: macos 12.0.1

### Describe the bug

When i upgrade from 4.4.7 to 4.5.1 i am able to run the backend once, but when i restart the server i get this error message: 
```error: alter table "globals_components" add constraint "globals_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "globals_unique" already exists```

### Steps to reproduce the behavior

1. Upgrade to strapi 4.5.1 in package.json as per upgrade instructions
2. Run `yarn build`, `yarn develop`
3. Server starts fine and i can view the cms at localhost:1337/admin
4. Upon server restart this error is displayed and the server will not start: ```error: alter table "globals_components" add constraint "globals_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "globals_unique" already exists```

### Expected behavior

I expected the server to not have an error 

### Screenshots

globals_components/Indexes with strapi 4.4.7
<img width="268" alt="image" src="https://user-images.githubusercontent.com/80323528/202417541-9f113c23-d9a7-4307-9a05-11f08da18369.png">

globals_components/Indexes after upgrading to strapi 4.5.1 and running `yarn build`
![image](https://user-images.githubusercontent.com/80323528/202418041-a28daea4-8776-4e32-8f91-c8a67256e04c.png)

now i run `yarn develop` for the first time 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/80323528/202418339-6324da61-d50e-4c37-abf3-d444f850125d.png">

and then i change something in strapi that requires a restart
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/80323528/202419107-c801d6ce-67b8-48bb-90bf-1f9dc79e16d0.png">

**Comment by petersg83** [comment]
Have you tried to migrate already but you had an error and just retried now? Or is it the first time you try to migrate to 4.5.x?

**Comment by pentcle** [comment]
i did it yesterday and had the same issue. i took a fresh cut of the pre-upgrade db for testing

**Comment by Marc-Roig** [comment]
I am trying to replicate your setup and I am not getting any error.

I start from a strapi app v4.4.7 using postgres, I migrate to v4.5.1 , everything works ok.
I make a change on the schema so the app has to be restarted, and It is restarting correctly.

For some reason the schema inspector is not detecting it has that index and trying to recreate it. I still have to try it with node v14. I will continue investigating this 🤔

**Comment by pentcle** [comment]
which version of node are you using? i can change version

**Comment by Marc-Roig** [comment]
I am using node v16.15.0

**Comment by Marc-Roig** [comment]
Btw, Do you have something else called globals in your application? Is it possible for you to rename that component ?

**Comment by pentcle** [comment]
i have this: 
![image](https://user-images.githubusercontent.com/80323528/202463836-9ce775a5-fa1e-433b-a054-f453af0ab6af.png)

**Comment by adam-t-knight** [comment]
I might be having a similar issue, originally reported here: https://github.com/strapi/strapi/issues/14833

Node.js version: v18.12.0
NPM version: 8.19.2
Strapi version: 4.5.1
Database: Postgres
Operating system: MacOs

[2022-11-17 16:07:46.045] error: create index "insurance_documents_collection_terms_and_conditions_links_order_inv_fk" on "insurance_documents_collection_terms_and_conditions_links" ("insurance_documents_order") - relation "insurance_documents_collection_terms_and_conditions_links_order" already exists
error: relation "insurance_documents_collection_terms_and_conditions_links_order" already exists

Everything runs fine on 4.4.7 and then I started getting this when updating from Strapi 4.4.7 to 4.5.0. Unfortunately the neither the 4.5.1 update nor the database migration script seem to solve it. Dropping the DB and allowing Strapi to regenerate it doesn't seem to work either.

If I remove the relation from the schema, then Strapi will start, but if I recreate the relation through Content Manager and hit save then Strapi hits this same error when restarting.

Looking through my schema files I can't seem to find any duplicate relations either.

**Comment by pentcle** [comment]
these are the dependencies we have (and had updated to 4.5.1)

    "@strapi/plugin-i18n": "4.4.7",
    "@strapi/plugin-users-permissions": "4.4.7",
    "@strapi/provider-upload-cloudinary": "4.4.7",
    "@strapi/strapi": "4.4.7",

**Comment by adam-t-knight** [comment]
I was able to get past the error I was seeing... by recreating all of my content types and their relations. It seems that when redoing them, some of the relations changed to mappedBy and some changed to inversedBy. I also allowed all of the names for the content types to autofill instead of customising them, just to be safe.

**Comment by Marc-Roig** [comment]
@adam-t-knight @pentcle  That might actually be the problem! That was a good catch. 💡  

I have not tested this and if this is a problem I will provide a proper solution for it 💪 . In the meantime:

This error might appear when a bidirectional relationship, in both sides of the schema.json files, have both inversedBy attribute. **So changing one of the inversedBy to mappedBy should fix it.** 

⚠️ **Make sure to make a back up firs**t, changing one of the sides might remove the joinTable that holds the relationship data, if that happens it means you have to change the other side of the relation.

----
**Some context:**
For bidirectional relationships Strapi uses mappedBy and inversedBy (see [docs](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#model-attributes)). So one side holds the mappedBy attribute and the other inversedBy.

We had a bug that was recently fixed https://github.com/strapi/strapi/pull/15037 , where both sides of the relation had inversedBy. And 4.5.0 was trying to create the unique index twice because of that.

**Comment by Marc-Roig** [comment]
Update, we merged a PR to print on console which relation attributes require changes and with that we conclude this issue should be fixed by that (even if it requires manual intervention)

It is the best solution we found out when exploring the issue. Hope it works for you all.

**Comment by AlbertCardo** [comment]
This issue can be related to https://github.com/strapi/strapi/issues/16055. The error (`alter table "up_users_components" add constraint "up_users_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "up_users_unique" already exists`) is the same, and in our case it also started after upgrading Strapi (from `^4.4.3` to `4.10.4`).

**Comment by AlbertCardo** [comment]
FYI we fixed the issue by setting `settings: { forceMigration: true }` in our [database configuration](https://docs.strapi.io/dev-docs/configurations/database#settings-configuration-object).
