### ISSUE TITLE
YupValidationError thrown silently

### ISSUE THREAD

**Issue by antokhio** [strapi/strapi#14913]
## Bug report

`YupValidationError` thrown silently in `api/contentType/service/`, with entityService api, need to check with query engine: 
consider we have enum field: 
```json
{
  "attributes": {
    "myEnum": {
      "type": "enumration",
      "enum": ['one','two','three']
    }
  }
}
```
now we do: 
```ts
const result = await strapi.entityService.create("api::myapi.myapi", {data: {
  myEnum: 'four'
});
console.log(result) // < not showing anything
```
basically there is no error or anything in console unless you do:
```
try { ... }
catch (e:any) {
   console.log(e.message)
}  
```
now you can see:
```py
YupValidationError: type must be one of the following values: ...
```

this is really frustrating, the validation step should throw, if in controller you get 404 in service you get basically nothing, had to reassemble whole content-type few times before i understand where the error is... 

### Required System information

- Strapi version: 4.5.1
- Database: Postgres 14

**Comment by derrickmehaffy** [comment]
Can you provide the full code for your controller or service as the default factory controller/service handles this perfectly:

![image](https://user-images.githubusercontent.com/8593673/209358006-f27529f5-8b72-456b-8e0b-812c19cce0f0.png)

Did you completely override a core service, extend it, or is this an entirely custom service?

**Comment by antokhio** [comment]
@derrickmehaffy hi, so the problem is that there is no error in console: 
![image](https://user-images.githubusercontent.com/1254168/209979251-d94a237d-72b6-4654-ae45-88421b90e89f.png)

idk if it make sense, but i came across this when i was trying to figure out why some partial part of content was not created
