### ISSUE TITLE
Error 400 on image cropping

### ISSUE THREAD

**Issue by Siddharth00** [strapi/strapi#14928]
### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.5.1
- Database: Postgres
- Operating system: MacOs

### Describe the bug

Bad Request → The Error only appears when cropping an image in a folder. When the image is in the “Assets” part, the cropping works fine. 
Also, if cropping the image and saving it as duplicate, the cropping works fine but the image gets saved in the assets and not in the respective folder.

### Steps to reproduce the behavior

1. Go to Media Library
2. Select any folder
3. Edit/Crop the image
4. See the error

```
{
  "data": null,
  "error": {
    "status": 400,
    "name": "ValidationError",
    "message": "fileInfo.folder must be a `strapiID` type, but the final value was: `{\n  \"id\": \"1\",\n  \"name\": \"\\\"photos\\\"\",\n  \"pathId\": \"1\",\n  \"path\": \"\\\"/1\\\"\",\n  \"createdAt\": \"\\\"2022-10-04T12:45:09.264Z\\\"\",\n  \"updatedAt\": \"\\\"2022-10-04T12:45:09.264Z\\\"\"\n}`.",
    "details": {
      "errors": [
        {
          "path": [
            "fileInfo",
            "folder"
          ],
          "message": "fileInfo.folder must be a `strapiID` type, but the final value was: `{\n  \"id\": \"1\",\n  \"name\": \"\\\"photos\\\"\",\n  \"pathId\": \"1\",\n  \"path\": \"\\\"/1\\\"\",\n  \"createdAt\": \"\\\"2022-10-04T12:45:09.264Z\\\"\",\n  \"updatedAt\": \"\\\"2022-10-04T12:45:09.264Z\\\"\"\n}`.",
          "name": "ValidationError"
        }
      ]
    }
  }
}
```

**Comment by Audit-a-la-Carte** [comment]
+1 for this one
