### ISSUE TITLE
alternativeText, caption gets not automatically set anymore

### ISSUE THREAD

**Issue by dominikzogg** [strapi/strapi#14932]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.1
- Database: postgresql
- Operating system: linux (rockylinux in a docker container)

### Describe the bug

Previously, when uploading files, the alternative text and caption were set automatically. This is not the case anymore since a CMS upgrade.

### Steps to reproduce the behavior

1. Go to the media library
2. Upload an image
3. Check if alternative text and caption are set.

### Expected behavior

The alternative text and caption are set with the filename or filename without ending.

**Comment by gu-stav** [comment]
This is now the intended behavior. The previous behavior caused a11y problems - you can follow the discussion here: https://github.com/strapi/strapi/issues/13295

**Comment by dominikzogg** [comment]
@gu-stav get that, thanks
