### ISSUE TITLE
Add Regexp for attribute value validation

### ISSUE THREAD

**Issue by decimoseptimo** [strapi/strapi#1493]
**What is the expected behavior?**
When adding a new content of type 'number', in content type builder.
min/max 'value' is present as an option but 'length' isn't. I'm aware they could conflict against one another, perhaps allowing one or the other?

Bug or feature? I don't know. I tried to solve it my self [but](https://github.com/strapi/strapi/issues/415#issuecomment-401563765).

**Comment by lauriejim** [comment]
Hello @decimoseptimo , what do you mean with `length` for numbers ?
If you set `10` as max value, the length will be max 2.
If you set `890` as max value, the max length will be 3.
Don't understand your need.

**Comment by decimoseptimo** [comment]
Yes you're right, It would be useful for constrained length codes, like zip codes and phones. And to account for left zeros.

**Comment by lauriejim** [comment]
In this case you have to store it as string. You are not trying to store a number to make math operations.

**Comment by decimoseptimo** [comment]
What about adding regex as a field type in content type builder?

**Comment by lauriejim** [comment]
That can be useful for string validation yap. But it can be apply on string and not on number

**Comment by decimoseptimo** [comment]
You meant regex can be applied on strings but not in numbers?

**Comment by lauriejim** [comment]
Nop, It's just I don't see use case for number.

**Comment by derrickmehaffy** [comment]
Ah @lauriejim I can find a case for a decimal, for instance Latitude/Longitude. In most cases when talking lat/lon the farthest accuracy you get to is one ten-thousdands (0.0001) thus if you wanted to ensure you validate this accuracy you would use regex in most cases. This could be done using string but if you wanted to calculate a distance between two points, you should be storing the data as a number.

I don't think regex should be added as its own type, I think regex should be something you can apply to an already existent field type.

**Comment by decimoseptimo** [comment]
@derrickmehaffy seems fair to me.

I just checked the model [validators](https://strapi.io/documentation/guides/models.html), too few. There's a "Framework - Validations" request in strapi.io/vote. I wonder whether that's aimed to solve it.


A how-to guide to create custom validators would be nice for newbies.

**Comment by lauriejim** [comment]
I think we can update this issue to "Add Regexp as model validator" ?

**Comment by derrickmehaffy** [comment]
@lauriejim Yes this is something that should be added to the validations entry on the vote page. Since regex itself is a validation. :stuck_out_tongue:

**Comment by decimoseptimo** [comment]
@lauriejim I agree

**Comment by Aurelsicoko** [comment]
Please refers to the "Validations" card available on Product Board (https://portal.productboard.com/strapi/c/14-validations). The validations should also support regexp like it was discussed in this issue.

I'm closing this issue because we're moving all the features requests on Product Board.
