### ISSUE TITLE
ER_LOCK_DEADLOCK error when trying to save an entity with multiple nested components

### ISSUE THREAD

**Issue by kilobyte2007** [strapi/strapi#14937]
Hey everyone!
I have an issue with saving an entity that has nested components - an Internal Server Error happens when updating an entity with multiple nested components.
The error is: `ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction`

If I try saving the entity multiple times, sometimes, on the 10th or 20th time it may save, but then the error comes back.

### Steps to reproduce the behavior
Please use this repository for a reproduction: https://github.com/kilobyte2007/strapi-bug-reproduction

1. Start strapi (you have first to specify your database credentials)
2. Go to `Content Manager`
3. Select `Landing Page`
4. Click `Create new entry`
5. Click `Add a component to sections`
6. Select `Pricing Plans`
7. Add 2 plans
8. Specify at least 5 features for every plan
9. Click `Save` - the error usually happens here, but sometimes there is no error at first so go back and add one more feature to any plan and try clicking `Save` again

### Expected behavior
The entity saves without an error.

### Screenshot
![image](https://user-images.githubusercontent.com/1911258/202777935-052843b8-3930-4274-b039-09203af6a627.png)
![image](https://user-images.githubusercontent.com/1911258/202778156-a1b19d4d-efb1-4e39-96ee-c3d0e623c93b.png)

### System information
- Node.js version: v16
- NPM version: v8
- Strapi version: 4.5.1
- Database: MySQL 8.0
- Operating system: Reproduced on both macOS and Linux

**Comment by pwilms** [comment]
On 4.5.2 the same issue is present.

**Comment by dottodot** [comment]
Yes I'm having the same issue, was fine on 4.4

**Comment by thongbn** [comment]
I got problem too when in 4.5.2. Acctually it happend from version 4.4.6. I got error when using navigation plugin with enable i18n. Please fix it :( 

`
UPDATE
navigations_localizations_links as a,
(
SELECT id, ROW_NUMBER() OVER (PARTITION BY navigation_id ORDER BY navigation_order) AS src_order
FROM navigations_localizations_links
WHERE navigation_id = 1
) AS b
SET navigation_order = b.src_order
WHERE b.id = a.id 
`

![image](https://user-images.githubusercontent.com/14286010/203816238-93cce3fa-f79c-4609-9209-519a5c162b38.png)

**Comment by petersg83** [comment]
Thank you for the issue! I could reproduce it.
