### ISSUE TITLE
Save content gives error: error: Undefined attribute level operator disconnect

### ISSUE THREAD

**Issue by taviroquai** [strapi/strapi#14938]
Update by: @derrickmehaffy 

**This is/was an unintended breaking change, we are looking into how to mitigate it**

---

### Required System information

- Node.js version: v16
- NPM version: 8.15
- Strapi version: 4.5.1
- Database: mysql
- Operating system: windows

### Describe the bug

After upgrading to version 4.5.1 it gives error on saving content

### Steps to reproduce the behavior

Please see screencast below

### Expected behavior

Save without errors

### Screenshots

![error_strapi](https://user-images.githubusercontent.com/498409/202795512-cb6f8621-d543-4643-a0b2-200204e4b35e.gif)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

More info:
The PUT request is sending the connect/disconnect params.
![image](https://user-images.githubusercontent.com/498409/202857742-5ea6a627-a895-48ab-a3bb-a536794ce5ce.png)

**Comment by taviroquai** [comment]
Ok after digging enough I found the problem:

I'm using lifecyle hooks to load content relations and to compute some fields.

Now in version 4.5.1 **I can't do this anymore** (example):
```javascript
module.exports = {
  async beforeCreate(event) {
    let { data } = event.params;
    if (data.relation) {
      const related = await strapi.entityService.findOne('api::related.related', data.relation, {
        fields: ['firstname', 'lastname']
      });
     data.computed = `${related.firstname} ${related.lastname}`
    }
  },
}
```

**Comment by pcriadoperez** [comment]
In our case `event.params.populate` is now undefined and was breaking our beforeUpdate lifecycle.
I'm a bit surprised strapi did this change without notifying on the release.

**Comment by chris-turner-datacom** [comment]
I have the same issue - the object that I was expecting to be inside event.params.data from the 4.4 versions is now not present in the 4.5.0. This is a significant breaking change for anyone using lifeCycle hooks. There seems to longer be a way to get the information I need in the lifecycle hooks due to this and so currently, I can't update past 4. Was this an intentional change?

**Comment by letrape** [comment]
I have managed to fix this issue by doing: 

Check the comments in the new code to see the solution 

**Original code  NOT WORKING ANYMORE **
` async beforeUpdate (event) {
        
        let parentId = event.params.data.parent
        if(parentId)
        {
            
            const parent  = await strapi.entityService.findOne('api::category.category', parentId, {
                fields: ['path'],
                populate: { category: true },
              });
            console.log(parent)
            event.params.data.path = `${parent.path} > ${event.params.data.name}`
        }
        else 
        {
            event.params.data.path = event.params.data.name
        }

    }`
    
    **NEW CODE**
    
    ` async beforeUpdate (event) {
        
        /*
  Now the id comes into a connect object, If the object did not change then the connect will be an emtpy array []
         In this case is 1:1 relationship so I can target the first element of the array safely  
       The original parent object (or wathever you named it) has changed to a new {disconnect, connect} notation, you only need 
       to  dig into the object 
*/
        
        let parentId = event.params.data.parent.connect ? event.params.data.parent.connect[0].id   
        if(parentId)
        {
            
            const parent  = await strapi.entityService.findOne('api::category.category', parentId, {
                fields: ['path'],
                populate: { category: true },
              });
            console.log(parent)
            event.params.data.path = `${parent.path} > ${event.params.data.name}`
        }
        else 
        {
            event.params.data.path = event.params.data.name
        }

    }`

**Comment by derrickmehaffy** [comment]
I can confirm this issue, it was due to the new relational reordering feature added in v4.5.x

I'm letting the team know of the breaking change so we can see if there is a way to mitigate it.

**Comment by joshuaellis** [comment]
Hi @fkukus,

This is on our radar and it's planned to be talked with other BE engineers in the internal sync meeting this week. From there we'll be able to address the issue. Thank you for your patience, when we have more information on the issue we'll report back!

**Comment by Marc-Roig** [comment]
@fkukus We are having a discussion about this and how we can address it as josh pointed out.

The current problem:
beforeCreate payload might not stable (at least with relations), and it's something we might not be able to control. 
- If you create the entity through the Admin UI, you might get one.
- If you create the entity through the Content API, you might get another.

The safe bet should be to use the `enityService.findOne` for now (as @letrape pointed out). Could that work for you @fkukus ?

**Comment by fkukus** [comment]
Wow, thank you both for your quick answers!

@Marc-Roig yes, for now, we can deal with an additional `entityService.findOne` with the appropriate populate to retrieve the missing related content.

**Comment by Marc-Roig** [comment]
We have reached on a conclusion about db db lifecycles, which is, there is no workaround on standarizing what gets to the db lifecycles. So in case you need it to be, you should be using the entityService find one for it.

Depending on who does the query (Content Manager, Rest API, GraphQL) you might receive a different payload on the db lifecycles.

We are going to document this behaviour properly in the documentation so other people can avoid this situation.

**Comment by galaxxyz** [comment]
@Marc-Roig Hello, could this data structure change be added to the migration guides? We update to 4.5.x quite late, but unfortunately this change is a unexpected issue for us too..

**Comment by elliotlaws** [comment]
Also found this issue unexpectedly, it's made migrating to V4 more painful and would have been nice to have proper  documentation for something like this. 

Please can the types be updated to reflect these changes?

**Comment by AvinashUtekar** [comment]
its a major change, i have a lot code written in lifecycles hook,
now need to modified it.

**Comment by gamerly-dev** [comment]
@Marc-Roig Anything that breaks existing functionality is a breaking change, regardless of whether it's unavoidable or intended. 

I can't see where this is documented, and if I have to account for an unknown data structure / 3 different possible data structures, it makes using lifecycle hooks quite unappealing. 

Is it worth considering a utility that takes the event.params.data and returns the ID?

**Comment by kgaurav-ts** [comment]
affects me too!
