### ISSUE TITLE
Email provider Mailgun test email not working

### ISSUE THREAD

**Issue by laohanme** [strapi/strapi#14944]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: v4.5.1
- Database: postgresql
- Operating system: Windows 10

### Steps to reproduce the behavior

1. install ```yarn add @strapi/provider-email-mailgun```
2. Setup on ```config/plugins.js``` 
```
  email: {
    config: {
      provider: 'mailgun',
      providerOptions: {
        key: env('MAILGUN_API_KEY'), // Required
        domain: env('MAILGUN_DOMAIN'), // Required
        url: env('MAILGUN_URL', 'https://api.mailgun.net'), //Optional. If domain region is Europe use 'https://api.eu.mailgun.net'
      },
      settings: {
        defaultFrom: 'myemail@protonmail.com',
        defaultReplyTo: 'myemail@protonmail.com',
      },
    },
  },
```
3. Send Test Email 

### Expected behavior

```
error: Couldn't send test email: Not Found.
 at Object.test (C:\....\node_modules\@strapi\plugin-email\server\controllers\email.js:50:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by eruiz-impact** [comment]
Did you provide the MAILGUN_API_KEY and MAILGUN_DOMAIN in your .env file?

**Comment by laohanme** [comment]
> Did you provide the MAILGUN_API_KEY and MAILGUN_DOMAIN in your .env file?

Yes, I have put it all inside .env file
