### ISSUE TITLE
Add Recaptcha in public forms to prevent spam

### ISSUE THREAD

**Issue by ghufr** [strapi/strapi#1494]
**What is the expected behavior?**
Extra layer of security to prevent spam in public facing forms.

I don't really know if there is any kind of security mechanism built in strapi that can limit login attempt or any public facing forms, i think adding recaptcha is nice and simple way to prevent spam...

**Comment by derrickmehaffy** [comment]
@ghufr I don't believe there is on the admin page, as for the API itself I know there isn't. I believe thats coming with the `rate limit` feature listed on the vote page.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy We should definitely add a rate limit on the attempt to log in. I'm keeping this in mind to potentially add it in the roadmap 👍

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I figured as much. You guys have a ton of ideas and not enough time in the day 😛

**Comment by Aurelsicoko** [comment]
The team is growing so we are going to be able to push more features in the roadmap 💪

**Comment by Aurelsicoko** [comment]
The rate limitation has been added. I'm closing the issue.

**Comment by opentechiz** [comment]
I think this issue is related to this
https://github.com/strapi/strapi/issues/3446

Any form submission should be integrated with recapcha to avoid spam

**Comment by lauriejim** [comment]
You can use the rate-limit feature.
There is here a rate limit policy https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js
You can create your own and apply it to the route you want to "protect". 
That is a workaround.

**Comment by Zhuinden** [comment]
Rate limit is not the same as Recaptcha.
