### ISSUE TITLE
Allow node 16 in strapi v3

### ISSUE THREAD

**Issue by cipriancaba** [strapi/strapi#14946]
## Bug report

Due to independent reasons, we are stuck with v3 for now. We can only install strapi with `yarn --ignore-engines` due to node engine requirements in the strapi package json

Please allow for node 16

Current setup
```
 "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
```

Opened pr #14947 for this

**Comment by derrickmehaffy** [comment]
As mentioned in the PR we won't be doing this, marking as closed
