### ISSUE TITLE
You need to run strapi start in a Strapi project

### ISSUE THREAD

**Issue by hastalavistababy** [strapi/strapi#14957]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 3.1.0-alpha.5
- Database: sqlite
- Operating system:  Ubuntu 22.04 x64

### Describe the bug

You need to run strapi start in a Strapi project. Make sure you are in the right directory

### Steps to reproduce the behavior

1. yarn create strapi-app my-project --quickstart --no-run
2. cd /var/www/html/my-project
3. yarn start develop

See proces logs

### Expected behavior

Start the strapi project

**Comment by hastalavistababy** [comment]
> 

I got this error after tried ``` strapi develop ``` and ``` strapi start ```

```You need to run strapi develop in a Strapi project. Make sure you are in the right directory```

**Comment by derrickmehaffy** [comment]
This is because you aren't inside the actual root of the Strapi directory, marking as closed as this isn't a bug

**Comment by needleshaped** [comment]
Unless `yarn install` is ran, Strapi will not recognize it's directory.

**Comment by Jaafar0941499966** [comment]
You need to run strapi develop in a Strapi project. Make sure you are in the right directory

**Comment by j-peace** [comment]
In my case I had to use `npm install` instead of `yarn install`
