### ISSUE TITLE
Media Library give error when we work with 300k images

### ISSUE THREAD

**Issue by claudiograssia** [strapi/strapi#14954]
## Bug report
Uploading Assets decrease performance when we upload assets, you can discover it only if you try to upload more than 100k assets

### System information

- Node.js version: 16.16.0
- NPM version: 8.11 .0
- Strapi version: 4.5.1, (  all version after integrated feature folder )
- Database: Mysql 8
- Operating system: Ubuntu 22.04

### Describe the bug
When we land on page Media Library in admin, we give error. 
After a careful analysis, we discover that the sql that strapi generate is not optimized:
```sql
select distinct `t0`.`updated_at`, `t0`.*, `t0`.`id` from `files` as `t0` left join `files_folder_links` as `t1` on `t0`.`id` = `t1`.`file_id` left join `upload_folders` as `t2` on `t1`.`folder_id` = `t2`.`id` where (((`t2`.`id` is null))) order by `t0`.`updated_at` DESC limit 10
```
This query could be optimized by removing left join

### Steps to reproduce the behavior

1. Go to on admin -> Media Library
2. Try to upload more than 100K media, 0 on folder and much more not in folders
3. Refresh Media Library
4. You see error or a very performance low for loading assets ( depends from performance of the your machine )

### Expected behavior
Assets are loading in without lost performance, whatever are the number of the uploaded assets 

### Additional context
Please remove the join from select, we tried that and the fix will increase drastically the performance.

**Comment by claudiograssia** [comment]
In addition i want share with you that the real problem is the filter:
http://0.0.0.0:1337/upload/files?sort=updatedAt:DESC&page=1&pageSize=10&filters[$and][0][folder][id][$null]=true
If I try to remove the filter the response is very fast.

**Comment by joshuaellis** [comment]
Hey @claudiograssia, out of curiosity, do you have an estimation on how long on average this takes?

**Comment by petersg83** [comment]
Hello :)
I tried locally with SQLite and 200k files. The query [http://0.0.0.0:1337/upload/files?sort=updatedAt:DESC&page=1&pageSize=10&filters[$and][0][folder][id][$null]=true](http://0.0.0.0:1337/upload/files?sort=updatedAt:DESC&page=1&pageSize=10&filters%5B$and%5D%5B0%5D%5Bfolder%5D%5Bid%5D%5B$null%5D=true) was taking between 700 and 1500ms.
The response time is indeed increasing with the number of files.
You propose to remove the left join, but it would then break the query no? Since it is done to get the files that are not in any folder ```WHERE (`t2`.`id` IS NULL)```.
```sql
SELECT DISTINCT
	`t0`.`updated_at`,
	`t0`.*,
	`t0`.`id`
FROM
	`files` AS `t0`
	LEFT JOIN `files_folder_links` AS `t1` ON `t0`.`id` = `t1`.`file_id`
	LEFT JOIN `upload_folders` AS `t2` ON `t1`.`folder_id` = `t2`.`id`
WHERE (`t2`.`id` IS NULL)
ORDER BY
	`t0`.`updated_at` DESC
LIMIT 10;
```

I think the slowness comes from the `order by`. I'm looking into adding a database index on `updated_at`. It reduces the query to ~200ms

**Comment by claudiograssia** [comment]
Hello, thanks for your support @petersg83,
I tried to insert the index to column update_at, actually has resolved my problem.
Before insert index the query take 8s for 300k images, now seems to be very fast.

Many thanks @petersg83.
For me you can close this issue, but I think that is very useful to insert index to update_at on strapi core.

**Comment by petersg83** [comment]
@claudiograssia I'm glad it works! I added the indexes now, it will be in the next release :)
