### ISSUE TITLE
Warning: An error occurred while requesting the API, only in localhost

### ISSUE THREAD

**Issue by hexacris** [strapi/strapi#14956]
## Bug report

Admin server doesn't start on localhost.

### System information

- Node.js version: 16.18.1 (LTS)
- NPM version: 8.19.2
- Strapi version: 4.5.0
- Database: Postgre
- Operating system: Windows 11

### Describe the bug

Admin server doesn't start on localhost but is running normal on production. Infinite loading loop. I can't understand why in develop mode the logs are showing the slug `admin/admin/init` duplicated for example when in production all is ok....

### Steps to reproduce the behavior

1. clone project
2. `npm i` or `yarn`
3. `npm run build` or `yarn build`
4. `npm run develop` or `yarn develop`

### Expected behavior

Run the project in development mode

### Screenshots

![image](https://user-images.githubusercontent.com/35607474/203136246-e4320abc-4a96-4615-a6a1-35fea39f3771.png)

![image](https://user-images.githubusercontent.com/35607474/203133791-58bda386-15e5-4229-8a6a-f7f6d8e1fc1f.png)

![image](https://user-images.githubusercontent.com/35607474/203136106-a2394463-380a-40e6-9f2f-3f62f89bfbaa.png)

**.env** (with the next variables too, APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET, JWT_SECRET)

![image](https://user-images.githubusercontent.com/35607474/203136734-8e95d624-13be-4bd3-b818-fcb20c859d4e.png)

**server.js**

![image](https://user-images.githubusercontent.com/35607474/203136439-d9b7f6f3-37c5-4ac0-9cd2-73e06d0a42e5.png)

**admin.js**

![image](https://user-images.githubusercontent.com/35607474/203136612-48b1a811-14ea-4403-9ed7-f32dfb789005.png)

### Additional context

I tried deleting the `.cache` `build` `node_modules` serveral times, build again but I got the same error.

**Comment by derrickmehaffy** [comment]
Can you please try upgrading to v4.5.4? We have released a few hotfixes I believe that should solve this issue (also please do delete your lock file and node_modules when doing this upgrade)
