### ISSUE TITLE
Error manageRelations is not a function

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1496]
**Informations**
- **Node.js version**: 10.x.x
- **npm version**: 6.x.x
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: mongodb
- **Operating system**: ubuntu18

**What is the current behavior?**
I get this error when i post to api

> I must replace my work folder name with myPath, path and *.js because can't show on public
```
| TypeError: strapi.hook.mongoose.manageRelations is not a function
|     at Object.add (/myPath/api/path/services/*.js:77:32)
|     at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by lauriejim** [comment]
Please update your Strapi application following migration guide in the wiki
