### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by arslion** [strapi/strapi#14979]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.2
- Database: mysql
- Operating system: Ubuntu 

### Describe the bug

Trying to sort the marketplace with Newest but it crashes.

### Steps to reproduce the behavior

1. Go to '/admin/marketplace'
2. Click on 'Sort by Newest'
3. See error

### Expected behavior

Sort plugin list by newest first

### Screenshots

![image](https://user-images.githubusercontent.com/3967627/203609777-c3cb607e-01ed-4502-a62c-e7e23450dc92.png)

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.5.4 so it appears fixed: 
![image](https://user-images.githubusercontent.com/8593673/209725476-149b7def-87fa-4323-b9da-17dc824eac3e.png)

**Comment by arslion** [comment]
yeah it might got fixed now. Haven't updated my version yet.

**Comment by arslion** [comment]
> Can't reproduce on v4.5.4 so it appears fixed: ![image](https://user-images.githubusercontent.com/8593673/209725476-149b7def-87fa-4323-b9da-17dc824eac3e.png)

yeah it might got fixed now. Haven't updated my version yet.
