### ISSUE TITLE
Official React-Admin data provider

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1497]
**What is the expected behavior?**
Please provide official [React-Admin data provider](https://marmelab.com/react-admin/DataProviders.html).
It can be very useful as an alternative.

**Comment by lauriejim** [comment]
Can you give us more details please.

**Comment by mnlbox** [comment]
@lauriejim With React-Admin we can generate CRUD page for end user. With this integration we can connect Strapi to React-Admin and generate end user web application. Then we have REST (GraphQL) and admin dashboard on Strapi and user website on React-Admin.

**Comment by derrickmehaffy** [comment]
@lauriejim its basically a way to quickly tie in Strapi into this frontend CRUD. I've used it in the past with loopback. If you look at some of the other examples (like loopback since it has a similar feature set).

@mnlbox I think this is something that could use the StrapiSDK to build it out pretty easily.

**Comment by mnlbox** [comment]
@derrickmehaffy I don't know. Can you more cleaner guide to how to use StrapiSDK for this?

**Comment by derrickmehaffy** [comment]
@mnlbox there isn't a guide, I'm saying use the strapiSDK to develop a connector. If you look at some of the other examples of connectors it shouldn't take much. The sdk pretty much offers everything up on a silver platter for you :p

**Comment by mnlbox** [comment]
@Let's talk about this in slack. What is your username there?

**Comment by Pritoj** [comment]
@mnlbox My username is `pritojs`.

**Comment by Calcyfer** [comment]
Have any of you made any progress on this?

**Comment by jonasdehovre** [comment]
Also really curious on the progress on this!

**Comment by derrickmehaffy** [comment]
I think @Pritoj is working on it currently

**Comment by Pritoj** [comment]
Hey guys,
So I had hit a few roadblocks on this. I'm currently working on this, but only after work. Will try to get it out ASAP.

**Comment by Pritoj** [comment]
Hey Guys,
Please check this out https://github.com/Pritoj/ra-dp-strapi

Any feedback appreciated

**Comment by Aurelsicoko** [comment]
I'm closing the issue because it has been resolved thanks to the amazing work done by @Pritoj. You can still comment and ping us if needed.

**Comment by jeremyrajan** [comment]
This seems like a better alternative https://github.com/nazirov91/ra-strapi-rest :)
