### ISSUE TITLE
EditFieldForm - relationType is undefined

### ISSUE THREAD

**Issue by LB22** [strapi/strapi#14981]
### System information

- Node.js version: 18.9.0
- NPM version: 8.19.1
- Strapi version: 4.5.0
- Database: Postgres
- Operating system: Windows 10

### The bug

Clicking Escape button while in configure the view -> edit attribute, I'm getting a white screen and a few errors in console.
```
TypeError: attributes[fieldToEdit] is undefined
    at EditFieldForm
```
```
Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
```

Logs are pointing me to content-manager -> EditFieldForm() -> 
 `const relationType = attributes[fieldToEdit].relationType;`

Pretty sure it's this line right here:
https://github.com/strapi/strapi/blob/main/packages/core/admin/admin/src/content-manager/pages/ListSettingsView/components/EditFieldForm.js#L40

### Steps to reproduce the behavior

1. Select a Collection Type under Content Manager. 
2. Click on Configure the view (the little settings cog to the right)
3. Under View, edit (by pressing the pen) any of those attributes.
4. When the edit menu popped up, press the Escape button

### Expected behavior

I expect the edit menu to just go away, as if you clicked cancel.

### Screenshots

This is the edit menu. Once you've got it open, press the Escape button and your screen will likely turn white.
![strapi-error](https://user-images.githubusercontent.com/55314315/203661608-1665172a-29c7-4588-a02f-0e7fe76a930f.PNG)

Mention as you wanted @derrickmehaffy 😃

**Comment by alainkaiser** [comment]
Hi @LB22

I am getting the same error (some sort of):

_Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop_

On my end, the error happens when I click on any select/dropdown in the admin panel.

**Comment by joshuaellis** [comment]
hey @LB22 can you see if this is still an issue in `4.5.2` i've just tried a couple of times and couldn't reproduce it on my end.

**Comment by joshuaellis** [comment]
@LB22 sorry I'm checking in on this sporadically, can you share the schema of the content type you're trying to edit at the time & then which field you try to edit? just so i can be _even more specific_ in my replication.
