### ISSUE TITLE
replace qs with QueryString?

### ISSUE THREAD

**Issue by jimmywarting** [strapi/strapi#14980]
I don't suppose you could be able to replace qs with QueryString?

reduce pkg size... and use built in web spec'ed things

**Comment by joshuaellis** [comment]
Hi @jimmywarting,

If I understand you correctly, I don't think it's that simple. `qs` is used on both the front and backend of the app. We'd have to use `URLSearchParams` on the frontend & we could use that or either `querystring` on the backend. However, you then have the issue that `qs` and `querystring` are not equal in functionality – https://stackblitz.com/edit/node-xa27zd?file=index.js (run `node index.js` in the terminal to see).

If you're interested in giving it a go, then please feel free to see if it's possible.
