### ISSUE TITLE
Email forms

### ISSUE THREAD

**Issue by Devilla** [strapi/strapi#1498]
hey dude, having problem with sending email forms to contact@support within my website. How to send mail on behalf of user when he's not given any permission to acces his mail.

**Comment by lauriejim** [comment]
Hello @Devilla , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

**Comment by Devilla** [comment]
Okay sure.

**Comment by Devilla** [comment]
**Informations**
- **Node.js version : v8.11.3**:
- **npm version : 5.6.0x`**:
- **Strapi version : 3.0.0-alpha.12.6**:
- **Database : MongoDB**:
- **Operating system : Ubuntu 16.04.4 LTS**:


**What is the current behavior?**
 Problem with sending email forms to contact@support within my website .Forms are hitting at strapi but not redirecting to email address.

**Steps to reproduce the problem**strapi
-Email forms : Contact Us, Affiliate Register Page, demopage etc.
Please checkout : https://staging.useinfluence.co,
https://staging.useinfluence.co/contact,
https://staging.useinfluence.co/affiliateregister etc

**What is the expected behavior?**
 Send email forms to contact@support within my website. Forms are hitting at strapi and redirecting to email address to generate tickets(freshdesk).


**Suggested solutions**
Ask user permission for sending mails.
Fake mails with user email.










**What is the expected behavior?**

Send email forms to contact@support within my website. Forms are hitting at strapi and must redirect to email address provide ( like contact@support )  to generate tickets(freshdesk).

**Comment by Devilla** [comment]
Please reopen the issue.

**Comment by lauriejim** [comment]
I don't understand your issue. Need more details. Errors you get or anything else.
With info I have now, I can't do nothing for you.

**Comment by derrickmehaffy** [comment]
@Devilla I also don't understand what the issue is here. Can you provide some context to the problem?

**Comment by Devilla** [comment]
@lauriejim  @derrickmehaffy  please checkout the following snaps : 
1. I create Affiliate Register Request.
2. It's  API getting response from strapi.
3. But now showing any mails in Freshdesk account.

![screenshot from 2018-07-02 19-25-23](https://user-images.githubusercontent.com/15603274/42168873-cb068f02-7e2f-11e8-860c-4d31d2485bad.png)
![screenshot from 2018-07-02 19-25-29](https://user-images.githubusercontent.com/15603274/42168874-cb4e9f04-7e2f-11e8-97a3-2760a9c07050.png)
![screenshot from 2018-07-02 19-26-13](https://user-images.githubusercontent.com/15603274/42168875-cb8cc3ce-7e2f-11e8-8d77-fb281efaeda3.png)
![screenshot from 2018-07-02 19-39-11](https://user-images.githubusercontent.com/15603274/42168876-cbf963d0-7e2f-11e8-8f8d-55626f53ce1a.png)

**Comment by derrickmehaffy** [comment]
@Devilla this doesn't help us, what is the bug with Strapi itself? We dont need to know your frontend or another backend. We need to know what kind of issue this is with Strapi itself.
