### ISSUE TITLE
Migration from 12.5 to 12.6 generating new plugins & admin issue

### ISSUE THREAD

**Issue by fleshgakker** [strapi/strapi#1499]
**Informations**
- **Node.js 10.4.1**:
- **npm version 6.1.0**:
- **Strapi version 12.6**:
- **Mongodb 3.4.15**:
- **Ubuntu 16.04 (win10 & regular)**:

**After removing 12.5 admin & plugins folders cannot generate new with npm install, postinstall**

mioji@mioji:/*/$ npm i

> ***@0.1.0 postinstall /***/
> node node_modules/strapi/lib/utils/post-install.js

🔸  Administration Panel
📦  Installing packages...
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bootstrap@4.1.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-redux-saga@0.4.0 requires a peer of eslint@^3.19.0 but none is installed. You must install peer dependencies yourself.

✅  Success

✅  Success

As result both admin & plugins folders are empty.

**Comment by derrickmehaffy** [comment]
@fleshgakker you need to create a temporary "new" project with `strapi new blah` and ignore the database bit (you can use your current one) after it's generated copy over the admin/plugins folders to your project

**Comment by lauriejim** [comment]
Hello @fleshgakker , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
