### ISSUE TITLE
Strapi Internationalization whitescreen v4.5.2 | ALL my collections ERASED!

### ISSUE THREAD

**Issue by csharpee** [strapi/strapi#14999]
On clicking any button in the admin dashboard that interacts with locales results in a **whitescreen**.

 The web browser debug log is of the following: 

```
TypeError: g is null
Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
```

I tested it on Firefox web browser.

**Comment by csharpee** [comment]
I just **uninstalled** the locale plugin and **reinstalled** it and all my collections vanished! :angry: and the locale still produces a white screen after interacting with any locale link or query.

![image](https://user-images.githubusercontent.com/18726788/203861124-43dc9fbc-f44a-423a-a7dc-7b58cc329691.png)

**Comment by csharpee** [comment]
I have completely recovered through a backup...the weirdest part is the locales are now working and all my collections are restored.

**Comment by csharpee** [comment]
According to Greg from Discord:

"Strapi keeps the db structure in sync with the content types. Everytime Strapi starts, it sanitizes the db. if you delete a content type or a field or a relation (which is what you did by uninstalling the plugin and then starting Strapi), then the associated data gets deleted. This is by design and one big change compared to v3. In v3 everything was being kept, but this caused other issues.

Anyway, I can only recommend to A) have backups and B) have separate db instances for different environments so that you can develop and test on one stage and have production data on another stage.

Regarding the problem with the translation plugin. No idea what went wrong there in the first place. Could be a version issue. Strapi is known for causing problems upon upgrading versions, even minor and patch versions. Usually the trick is to delete the node_modules folder and the lockfile and do a clean install from there, which I'm personally not a fan of. "

**Comment by derrickmehaffy** [comment]
related to #1114
