### ISSUE TITLE
WS polling returns 404

### ISSUE THREAD

**Issue by dj-hedgehog** [strapi/strapi#150]
**Strapi version**: 2

My frontend connects to the Strapi backend using a WebSocket connection. The frontend is polling `?EIO` but the backend returns a 404. What am I doing wrong here?

![localhost 3000 2016-10-04 16-18-45](https://cloud.githubusercontent.com/assets/7140800/19077817/442c066e-8a4e-11e6-894c-166c69b3433a.png)

**Comment by Aurelsicoko** [comment]
Hi @dj-hedgehog! Can you give more details and code snippets of your frontend and backend?

**Comment by dj-hedgehog** [comment]
It was related to not proxying the WS requests properly in the frontend.
