### ISSUE TITLE
(hook:mongoose) wasn't loaded due to missing key 'enabled' in the configuration on NODE_ENV="production"

### ISSUE THREAD

**Issue by brandhaug** [strapi/strapi#1501]
**Informations**
- **Node.js version**: 10.5.0 / 8.9.4
- **npm version**: 6.1.0 / 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: MongoDB 3.6.3
- **Operating system**: Windows 10

**What is the current behavior?**
Error on running `node server.js`:
`[2018-07-02T08:24:36.348Z] warn (hook:mongoose) wasn't loaded due to missing key 'enabled' in the configuration`
`(node:16320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: strapi.models.core_store.forge is not a function`
`(node:16320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
`(node:16320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: strapi.models.core_store.forge is not a function`
`(node:16320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): ReferenceError: config is not defined`
`(node:16320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): ReferenceError: config is not defined`
`[2018-07-02T08:24:40.062Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).`
`[2018-07-02T08:24:40.062Z] warn Perhaps you forgot to call it?`

The problem does not occur when NODE_ENV="development", even with the same database connection.

**Steps to reproduce the problem**
`SET NODE_ENV="production"`
`node server.js`

**What is the expected behavior?**
Server start

**Suggested solutions**
I see someone having a similar problems on https://github.com/strapi/strapi/issues/698, but they assume it's because of OS X, and I'm running Windows. I've tried running `npm install strapi-bookshelf@alpha --save`, but it didn't fix it.

**Comment by derrickmehaffy** [comment]
@brandhaug bookshelf won't help you here. Its for MySQL and Postgres. Most likely your database.json file isn't setup properly in `config/environments/staging` or `config/environments/production` I believe by default those two files use environment variable for connection information. If you copy over the config from your development folder to those and attempt to start it should work, although realistically you should be using env variables for those configs (or all of them)

https://www.twilio.com/blog/2017/08/working-with-environment-variables-in-node-js.html

**Comment by brandhaug** [comment]
Thanks for the tip, I previously used environment variables for hostname, port, database, username and password. The problem was fixed when I removed these, and replaced them by using the environment variable for database uri.
