### ISSUE TITLE
thowing an ApplicationError in a lifecycle hook with a custom message no longer displays the custom message

### ISSUE THREAD

**Issue by ghost** [strapi/strapi#15017]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.4.7
- Database: SQLite
- Operating system: Windows

### Describe the bug

In a BeforeUpdate or BeforeCreate lifecycle hook, if I throw an ApplicationError with a custom message, that message is ignored and instead 'Internal Server Error' is displayed to the user. This is contrary to the behaviour described in the documentation and how this used to work before recent updates: https://docs.strapi.io/developer-docs/latest/developer-resources/error-handling.html#services-and-models-lifecycles

### Expected behavior

The custom error Message should display to the user.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
I just tested this last week during my best practices call on Discord: https://www.youtube.com/watch?v=zjOSx9il98Q and it worked fine on v4.5.4 and I can't reproduce it on 4.5.x

**Comment by DeniskasViskas** [comment]
doesn't work on 4.9.0

**Comment by julesrenaud** [comment]
@derrickmehaffy the error message is no longer shown to the user, only shows up in the console. To test quickly:

1. Create a fresh install of Strapi
2. Create an API Token
3. Try to create another API Token with the same name

**Comment by Boegie19** [comment]
If this issue still exists please give replications steps.

**Comment by jonandernovella** [comment]
@Boegie19 I have replicated this issue with the version 4.10.6 of strapi. The UI shows Internal Server Error after updating an entry in the collection.

The code looks as follows:

```
const { errors } = require("@strapi/utils");

const isRelationSet = (data) => {
  if (data.connect.length === 0) {
    throw new errors.ApplicationError("The xyz field must be set");
  }
};

export default {
  beforeCreate(event) {
    isRelationSet(event.params.data.xyz);
  },

  beforeUpdate(event) {
    isRelationSet(event.params.data.xyz);
  },
};
```

**Comment by julesrenaud** [comment]
> If this issue still exists please give replications steps.
@Boegie19 

I did give replication steps, see my comment above
https://github.com/strapi/strapi/issues/15017#issuecomment-1523690577

**Comment by julesrenaud** [comment]
This issue shouldn't be closed, the functionality is broken on fresh installs... should be fairly easy to figure out

**Comment by Martijn-Schoenmaker-Webbio** [comment]
This is indeed still a problem. When using ` throw new errors.ValidationError("Custom error message") or ` throw new errors.ApplicationError("Custom error message")` the admin always displays "Internal Server Error". This error can also be seen in the network tab. Message is not being sent to the client it seems.

**Comment by derrickmehaffy** [comment]
Tested on a fresh v4.11.5 project with beforeCreate, beforeUpdate, and beforeDelete:

![image](https://github.com/strapi/strapi/assets/8593673/6a082d8a-e91a-413f-bfda-cf8ae47f94a9)
![image](https://github.com/strapi/strapi/assets/8593673/9677242f-682c-4f0f-98f9-b9bfb1f485e4)
![image](https://github.com/strapi/strapi/assets/8593673/2f72d7b2-6560-4fbf-beff-09f9a8a97ccc)

**Comment by Martijn-Schoenmaker-Webbio** [comment]
It has to do with adding lifecycles to a **plugin**. In both the content-types and the bootstrap (`strapi.db.lifecycles.subscribe`), it will not include the message. 

I have tested the lifecycles inside the project itself and that does work indeed.

So there needs to be a fix for messages that come from plugins.

**Comment by Boegie19** [comment]
@Martijn-Schoenmaker-Webbio Are there any strapi plugins with this issue?
if not it would be to the plugin maintainer to fix this issue

**Comment by Martijn-Schoenmaker-Webbio** [comment]
@Boegie19 No, the point I'm making is that if you're implementing this in a plugin (which I'm doing), you will not get the message, it will always say "Internal server error". So the Strapi team needs to make sure the messages from plugins are also shown.

**Comment by Boegie19** [comment]
@Martijn-Schoenmaker-Webbio If it is in the strapi admin core UI maintained by strapi yes.
But if it is in the custom plugin UI no that is the problem of the plugin maintainer

**Comment by Martijn-Schoenmaker-Webbio** [comment]
@Boegie19 Yes, I'm talking about the core UI. I'm subscribing to a lifecycle for a collection type. Upon saving the collection type and throwing an Error, I expect the message to appear in the notification modal.

**Comment by jhoward1994** [comment]
Hi, I'm afraid I cannot reproduce this issue.

I am using the i18n plugin to subscribe to db lifecycle events like this


```
...
const registerModelsHooks = () => {
  const i18nModelUIDs = Object.values(strapi.contentTypes)
    .filter((contentType) => getService('content-types').isLocalizedContentType(contentType))
    .map((contentType) => contentType.uid);

  if (i18nModelUIDs.length > 0) {
    strapi.db.lifecycles.subscribe({
      models: i18nModelUIDs,
      async beforeCreate(event) {
        throw new ApplicationError('I18N error message');
      },
    });
  }
...

```

And I can see this error is surfaced in the UI

<img width="1238" alt="image" src="https://github.com/strapi/strapi/assets/48524071/c118b02e-a86b-4918-a965-1dc7d2f64775">


To me this seems to show that subscribing to these lifecycle events from a plugin works as expected. Could this be down to the implementation of the plugin you are using?

**Comment by Boegie19** [comment]
> I was able to reproduce this issue in v4.9.0.
> 
> **Admin UI & Console:** ![image](https://user-images.githubusercontent.com/104756792/268982023-145f8f01-48f2-4d57-b6d1-7104b02b4b76.png)
> 
> **Lifecycle.js of a controller:** ![image](https://user-images.githubusercontent.com/104756792/268981129-3398cb0d-768f-4f96-9346-a9404779e2b1.png)
> 
> Steps to reproduce:
> 
> 1. Create a lifecycle.js under a controller.
> 2. Add beforeCreate/beforeUpdate hooks
> 3. Add this code block `throw new ApplicationError('Custom error message', {foo: "bar"})` inside the hook method

Mind checking if this issue still exists on the latest version if that is the cease please open an new issue for this where in you tag this issue.

**Comment by ihor-zinchenko** [comment]
Same for me:
Strapi: 4.20.0

Steps:

1. Create lifecycles.ts inside any collection
2. Put some code there
```import { errors } from '@strapi/utils';
const { ApplicationError } = errors;

module.exports = {
  beforeCreate(event) {
    const { data, where, select, populate } = event.params;

    console.log(event.params);

    throw new ApplicationError('Something went wrong 123', {
      errors: [
        {
          path: ["slug"],
          message: "This attribute must be unique",
          name: "ValidationError",
        },
      ],
    });
  },

  beforeUpdate(event) {
    const { result, params } = event;

    // do something to the result;
  },
};
```

2. Got error:
![image](https://github.com/strapi/strapi/assets/38561554/f2b6cb60-48d1-4408-8f34-1fe3bd2d0892)
