### ISSUE TITLE
I don't have default value for text field for single type

### ISSUE THREAD

**Issue by MaksZhukov** [strapi/strapi#15013]
### Required System information

- Node.js version: 16.17.1
- NPM version:  8.11
- Strapi version: 4.5.0
- Database: mysql
- Operating system: windows

### Describe the bug

I don't have default value for text field

### Steps to reproduce the behavior

1. Go to 'content type builder'
2. Click on 'single create type'
3. Click on creatring text field
4. Set the default value for it
5. Go to content manager
6. Open the 'single type'
7. See the field is empty

### Expected behavior

1. Go to 'content type builder'
2. Click on 'single create type'
3. Click on creatring text field
4. Set the default value for it
5. Go to content manager
6. Open the 'single type'
7. See the field is filled by your default value

### Screenshots

![image](https://user-images.githubusercontent.com/23615115/204092376-7c9612a6-8c23-476a-bff0-f6541697b1ea.png)
![image](https://user-images.githubusercontent.com/23615115/204092396-b278b357-89f0-44c3-8900-08b10946e203.png)
![image](https://user-images.githubusercontent.com/23615115/204092409-074f169d-306e-47b8-98d4-3c9e6d3fc1f5.png)

### Code snippets

    "autoSynonyms": {
      "type": "string",
      "default": "авто"
    }

**Comment by derrickmehaffy** [comment]
Can't confirm on v4.5.5:

![image](https://user-images.githubusercontent.com/8593673/210091354-7e8e1c38-5eec-4857-bf33-6250fb7394ba.png)
![image](https://user-images.githubusercontent.com/8593673/210091378-12e0bf83-23e5-45ab-968e-b4a0bd1c5c3b.png)
