### ISSUE TITLE
`forceMigration: false` not working with PostgreSQL databases? 

### ISSUE THREAD

**Issue by pwizla** [strapi/strapi#15027]
## Bug report

Through the Hotjar feedback widget on the documentation website, we received the following report from a user:

### Required System information

- Node.js version: unknown
- NPM version: unknown
- Strapi version: unknown
- Database: PostgreSQL
- Operating system: Windows 10

### Describe the bug

Feedback content (copying/pasting from Hotjar):
> `forceMigration: false ` does not work in PostgreSQL! 
> Strapi deletes the tables anyway. Can you please tell me how to turn it off? Why is this even needed? Perhaps I did not write something correctly, but unfortunately there is no example in the documentation. 

### Steps to reproduce the behavior

/ 
(see code snippet for a bit more context)

### Expected behavior

From what the user is asking, actually having the forced migration disabled.

### Screenshots

/ 

### Code snippets

The user provided this code snippet (I guess this is the content of their `config/database.js` file)

> My Code: 

```
module.exports = ({ env }) => ({ 
	connection: { 
		client: "postgres",
  		connection: {
      		host: env("DATABASE_HOST", "192.168.1.100"),
      		port: env.int("DATABASE_PORT", 5432),
			database: env("DATABASE_NAME", "blablabla"),
			user: env("DATABASE_USERNAME", "blablabla"),
			password: env("DATABASE_PASSWORD", "pass"),
			schema: env("DATABASE_SCHEMA", "public"),
		},
		forceMigration: false,
		debug: false,
	},
}); ”
```

**Comment by derrickmehaffy** [comment]
forceMigration will only stop the creation/update of new tables/columns but not the deletion. The deletion is intended as a fix to #1114 

Marking as closed/not-planned as for the moment we do not believe this a bug and instead should be redirect to https://feedback.strapi.io as a feature request to add in a boolean toggle to disable the "cleanup"
