### ISSUE TITLE
Not able to extend user-permissions controller endpoints (results in 405 error)

### ISSUE THREAD

**Issue by SvenWesterlaken** [strapi/strapi#15024]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.5.1
- Database: MySQL 8.0.30
- Operating system: MacOS

_NOTE: I do use Typescript, so not sure if that has any influence on the fact that the strapi-server should be a `.ts` or `.js` file._

### Describe the bug

When writing different kind of solutions for extending the default users (by the users-permission plugin), it doesn't seem to have any effect as it either gives a 405 error (Method not allowed) or doesn't find the endpoint at all when using different methods (as a test). Also the endpoint doesn't show up in the strapi server plugin settings configuration.

### Steps to reproduce the behavior

1. Install Strapi normally
2. Create a `strapi-server.js` file in the `/src/extensions/user-permissions/` folder with the below code snippet (as this is based on the [documentation](https://docs.strapi.io/developer-docs/latest/development/plugins-extension.html#within-the-extensions-folder))
3. Try and see if the endpoint is in the list of permissions (settings in strapi backend portal)
4. Try to send an authorized API call to the endpoint `/api/users/new`

### Expected behavior

I expect the controller function/endpoint to be called appropriately & show up in the permissions list. And therefore show the given console log `Called from custom function`.

### Screenshots

Logs from the server (when calling the said endpoint):
<img width="458" alt="image" src="https://user-images.githubusercontent.com/16725310/204316034-322afe8d-5612-466d-b9b2-dc88b0e813bb.png">

### Code snippets

```js
// /src/extensions/user-permissions/strapi-server.js

module.exports = (plugin) => {

  // Create the new controller
  plugin.controllers.user.createNew = async (ctx) => {
    // const user = ctx.state.user;

    // console.log(ct);

    // User has to be logged in to update themselves
    // if (!user) {
    //   return ctx.unauthorized();
    // }
      console.log('Called from custom function')
      return;

  };

  // Add the custom route
  plugin.routes['content-api'].routes.unshift({
    method: 'POST',
    path: '/users/new',
    handler: 'user.createNew',
    config: {
        prefix: '',
    }
  });

  return plugin;
};
```

**Comment by dimitrisganotis** [comment]
Try to use a typescript file like this: strapi-server.ts

`export default plugin => {
   ...
   return plugin;
}`

**Comment by SvenWesterlaken** [comment]
Apparently, I got the same when I tried to create new routes on my custom API objects. It might have been a caching thing as after a complete restart of my coding environment it magically worked again and after that, the above code also appeared to work. Thanks for the suggestion. Changing it to typescript still works.
