### ISSUE TITLE
User Roles and Permissions on Production

### ISSUE THREAD

**Issue by bahdcoder** [strapi/strapi#1504]
**Informations**
- **Node.js version**:
v9.10.1
- **npm version**:
5.6.0
- **Strapi version**:
3.0.0-alpha.12.5
- **Database**:
mongodb
- **Operating system**:
macos high sierra v10.13.2

**What is the current behavior?**
This concerns specifically the `Roles and Permissions` plugin.

Currently, when new content is created on development (for example, a new `Article` model), permissions for this do not show up when pushed to the production environment.

<img width="1415" alt="screen shot 2018-07-02 at 10 18 03 am" src="https://user-images.githubusercontent.com/19477966/42157140-d00b68d8-7de4-11e8-93c2-6fcfaab69097.png">

The screenshot above shows the roles and permissions for my application in production, and I just added the `Course` model locally, and pushed to production. But as you can see, on production, the roles and permissions for `Course` do not show up (only thoese for Article, and Tag show up, since they were there from the initial deployment and fresh database connection)

**Steps to reproduce the problem**
- create new strapi app
- create new content with content builder, for example, Article.
- deploy this application to production (with production database)
- visit the roles and permissions page, and select  any of the default roles (for example, `Authenticated`).
- expect to see under the `Application` tab, a list of permissions for `Article`.
- on development, create new content with content builder, for example, Tag.
- deploy the latest changes to production.
- visit the roles and permissions page, and select  any of the default roles (for example, `Authenticated`).
-  expect to see under the `Application` tab, a list of permissions for only `Article`, and not `Tag`.

**What is the expected behavior?**

When new content is created on development, roles and permissions for the content should show up 

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@bahdcoder are you using the same database for all your node env?

**Comment by bahdcoder** [comment]
@derrickmehaffy no. All environments have separate databases.

**Comment by derrickmehaffy** [comment]
@bahdcoder Hmmm if you purge your staging/production database and restart are the permissions shown?

(Permissions are stored in the database)

**Comment by derrickmehaffy** [comment]
@Aurelsicoko wasn't something added that checks existing models and if the permission isn't found or a duplicate is found it is deleted/recreated?

**Comment by bahdcoder** [comment]
@derrickmehaffy yes, if I do this, I see the permissions.

**Comment by derrickmehaffy** [comment]
Yeah so strapi isn't checking the permissions table/collection on boot if it exists

My guess for now @bahdcoder is to export that collection from your development and import/overwrite for staging production (I don't use mongo, so I have no idea on a simple way to do this. With MySQL I can just export CSV and import it to the other database)

**Comment by bahdcoder** [comment]
@derrickmehaffy thanks for your suggestion. 
The main problem with this suggestion is that it's not scalable. 
At the moment, with the current bug, It means no one can actually work on a strapi application after it is deployed, which is not a good thing if you think about it, because software products will keep progressing over time.

I am looking through the source code to see if there is any contribution i can make so this issue goes away.

**Comment by derrickmehaffy** [comment]
@bahdcoder @Aurelsicoko is working on a permissions export/import feature. Right now permissions are stored in the database and only in the database. Regardless of the fact new models aren't being added into the permissions table, even if they were with default values they wouldn't be the same values you may have set in development.

**Comment by bahdcoder** [comment]
@derrickmehaffy @Aurelsicoko 

I was able to find the problem with the current implementation and fix this (I still do not know if this is a bug, or if this requires fixing 😄). 

Please, could someone explain to me why we have the `actions.json` config file in the `user-permissions` plugin? I would love to understand more so I can make meaningful contributions to the project. 🙇

**Comment by lauriejim** [comment]
Hello @bahdcoder !

Can you tell me where is hosted your application. and what is your deployment process ?
Did you restart your production application after deploy it?

**Comment by bahdcoder** [comment]
Hello @lauriejim thanks for reaching out. 
I deployed my application on a Digital Ocean droplet.
After every deployment, I restart my app using PM2.

**Comment by lauriejim** [comment]
Okay and you can see all your content types in the left menu ?

**Comment by bahdcoder** [comment]
@lauriejim yes I can. @lauriejim I would love to submit a PR with a fix, that's if you have all the information you need.

**Comment by derrickmehaffy** [comment]
(I'm not quite sure what that file is for @bahdcoder, I believe @Aurelsicoko would be the best person to answer that.)
