### ISSUE TITLE
RBAC/MediaLibrary: Author can delete other user's folders (including all assets)

### ISSUE THREAD

**Issue by meck93** [strapi/strapi#15059]
## Bug report

A Strapi Admin user with role: 'author' is able to delete other user's folders (including all assets). This can lead to really annoying situations in production where by accident one user deletes the images of another user. 

### Required System information

- Node.js version: v16
- NPM version: v8
- Strapi version: v4.5.3
- Database: Postgres
- Operating system: MacOS

### Describe the bug

See video & reproduction steps

### Steps to reproduce the behavior

1. Open the 'GetStarted' app
2. Add an user with role 'author'
3. As a super admin, create a media folder 
4. As as super admin, upload an image to the folder in the media library
5. As an author, go to the media library, you should be able to see the folder (which is ok, no assets visible). But you shouldn't be able to delete the folder even though it contains assets of other users. The super admin can no longer see the folder as well as the uploaded images. The author was able to delete the super admin's images by deleting the folder.

### Expected behavior

- The user with role 'author' should not be able to delete a folder that contains image's uploaded by another user. 
- The user with role 'author' should only be able to delete his/her own created folders.
- Alternatively, an option could be provided to completely disable the 'media folders' feature. 

### Video Reproduction

https://user-images.githubusercontent.com/22457755/205140629-fde7e0ec-8db1-4615-958c-516351f84d43.mov

**Comment by gu-stav** [comment]
We have decided not to introduce new permissions for the first iteration of folders. Folders inherit permissions from assets - as soon as you remove "delete" permissions from your authors, they won't be able to delete folders anymore.

However: we have seen this feature request several times already, so thank your for opening the issue. Do you mind creating a feature request at https://feedback.strapi.io/ ?

**Comment by meck93** [comment]
Hi @gu-stav 

Thanks for your reply. I created a feature request: https://feedback.strapi.io/feature-requests/p/permission-management-for-media-library-folders

> We have decided not to introduce new permissions for the first iteration of folders. Folders inherit permissions from assets - as soon as you remove "delete" permissions from your authors, they won't be able to delete folders anymore.

One thing, I'd like to clarify. I don't think this is a feature. It's more like a part of the implementation is missing. 
- A user with role 'author' is able to delete any folder, even folders that contain assets owned by other users. 
- The user is unable to see the content of the folder which is correct since the assets have been uploaded by another user.
- BUT the user is able to see the folder which has also been created by another user. This should not be possible in my eyes. The folder shouldn't even be visible to the user. 

Also, removing the 'delete' permission from the authors is not possible (see my attached screenshot). I don't think it really helps as the authors should be able to delete their uploaded assets (with this change, they're only able to upload assets, correct?).

<img width="1195" alt="Screenshot 2022-12-05 at 23 27 28" src="https://user-images.githubusercontent.com/22457755/205756480-da319d39-8b20-4419-bf17-c2b07e0329a4.png">


Since I don't want to complain and am grateful for you work. Is there a way that I could help implement this feature?

**Comment by gu-stav** [comment]
Thank you for the clarification and the feature request :)

> The user is unable to see the content of the folder since the assets have been uploaded by another user. [...] BUT the user is able to see the folder which has been created by another user and the user is able to delete the folder including all its assets for which the user doesn't have any permissions.

How do you hide the assets from one user for others? Did you implement this using an 'is-owner' policy?

**Comment by meck93** [comment]
> How do you hide the assets from one user for others? Did you implement this using an 'is-owner' policy?

I haven't configured or implemented anything yet in regards to the media library. The asset permissions (visibility restricted for the 'author' role) seems to be the default behaviour. 

<img width="1257" alt="Screenshot 2022-12-06 at 07 02 50" src="https://user-images.githubusercontent.com/22457755/205832879-2dbec9d5-2055-471e-8c58-a81b34ba31e8.png">

I can't change or open the dropdown (see screenshot). Would I have to implement the viewing rights via a 'is-owner' policy?  I haven't tried that yet.

Regarding asset permissions. I think it might have been implemented in this PR https://github.com/strapi/strapi/pull/10291 related to this issue https://github.com/strapi/strapi/issues/10221 -> it seems the issue was similar in that case. The permissions were not respected for the assets. An author was able to see a super admin's uploaded images.

**Comment by meck93** [comment]
@gu-stav do you know if the Media Library List View PR https://github.com/strapi/strapi/pull/15085 will fix this issue? A similar/related issue is described in the PR description.

**Comment by meck93** [comment]
@gu-stav have you had a chance to take a look at it yet?

**Comment by meck93** [comment]
@kasonde did you have a chance to have a look at it yet?

**Comment by derrickmehaffy** [comment]
> @kasonde did you have a chance to have a look at it yet?

He is currently on vacation and will be back next week

**Comment by kasonde** [comment]
Hi @meck93 just a note: I'm not on the Engineering team, actually Support Team here at Strapi. I've read through the thread and wanted to know what in particular you'd like me to look at?

**Comment by meck93** [comment]
> Hi @meck93 just a note: I'm not on the Engineering team, actually Support Team here at Strapi. I've read through the thread and wanted to know what in particular you'd like me to look at?

Hi @kasonde 

I guess it is about reproducing the issue on your side. The label added by @derrickmehaffy says 'pending reproduction'. Can you reproduce the case shown in the video? 

See the issue description above. There is probably a missing permission/owner check somewhere. I have not configured/customized anything, this works with every fresh Strapi installation. 

Let me know if you need more information.

**Comment by meck93** [comment]
@kasonde @derrickmehaffy @gu-stav any update on the issue? 

Is there anyway I can help? Shall I dig into the code or is someone already working on this? 

Thanks for the feedback!

**Comment by derrickmehaffy** [comment]
> @kasonde @derrickmehaffy @gu-stav any update on the issue?
> 
> Is there anyway I can help? Shall I dig into the code or is someone already working on this?
> 
> Thanks for the feedback!

For the moment the implementation would be quite complex and I don't believe any of the product or engineer squads have dove into this issue yet (RBAC in the Media Library)

**Comment by meck93** [comment]
@derrickmehaffy could we provide a workaround in the meantime to mitigate the impact of this issue. For example, I was thinking of a toggle (somewhere in the settings) to disable Media Library folders across the application. Alternatively, could we maybe implement a mitigation strategy using an 'is-owner' policy as previously suggested by @gu-stav ?

**Comment by gu-stav** [comment]
@meck93 I agree that any follow-up iteration on permissions should take that into account and implement the same ideas Strapi already has for content-types but for folders. Right now we haven't planned any work on that and we didn't include it in the first iteration because it is a lot of work to get right and we wanted to see first what everyone would do and need.

Internally folders and assets/ files are like any other content-type: I'm wondering if you could implement the policy system already on them on your own. 🤔 @derrickmehaffy do you have an idea?

There is already an open feature request on Canny: https://feedback.strapi.io/feature-requests/p/permission-management-for-media-library-folders

We take this board into account when we decide on what to work on next. Would you mind adding your vote(s) and use-case there?
