### ISSUE TITLE
create-strapi-app not respecting --quickstart argument and prompting for input

### ISSUE THREAD

**Issue by hdeadman** [strapi/strapi#15056]
### Describe the bug

create-strapi-app is prompting for input when a command line option is used that already specifies the installation type. This is a problem when it is used in scripts/CICD/etc. 

```
$ npx -y create-strapi-app getstarted --quickstart --no-run
? Choose your installation type (Use arrow keys)
> Quickstart (recommended)
  Custom (manual settings)
```

- Node.js version: v18.12.1
- NPM version: 9.1.3
- Strapi version: 4.5.3
- Database: N/A
- Operating system: Windows

### Steps to reproduce the behavior
```
$ npx -y create-strapi-app getstarted --quickstart --no-run
? Choose your installation type (Use arrow keys)
> Quickstart (recommended)
  Custom (manual settings)
```

### Expected behavior

No prompt for installation type since --quickstart command line option was used. 

### Additional context
This causes problems when this is used in CICD tests:

https://github.com/apereo/cas/actions/runs/3590240888/jobs/6043699648#step:7:536

**Comment by innerdvations** [comment]
[This PR should fix it](https://github.com/strapi/strapi/pull/15060), I just need to do some more tests to be sure before merging. If you're able to confirm that it fixes your issue, that would be great.

**Comment by hdeadman** [comment]
Thanks, works for me locally. It looks like there are nightly builds published to npm registry so I should be able to use experimental tag starting tomorrow to get a working module? (e.g. `npx -y create-strapi-app@experimental getstarted --quickstart --no-run` (Just so CICD test doesn't fail until next release). 

```
$ node create-strapi-app.js --quickstart myproject --no-run
Creating a quickstart project.
Creating a new Strapi application at C:\Users\xxx\git\strapi\packages\cli\create-strapi-app\myproject.
Creating files.
Dependencies installed successfully.

Your application was created at C:\Users\xxx\git\strapi\packages\cli\create-strapi-app\myproject.
```
