### ISSUE TITLE
Fails to start strapi when creating a plugin using createCoreRouter

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#15050]
## Bug report
```
TypeError: Cannot read properties of undefined (reading 'kind')
    at isSingleType (/home/pablo/github/ciudadela/backend/node_modules/@strapi/utils/lib/content-types.js:90:25)
    at createRoutes (/home/pablo/github/ciudadela/backend/node_modules/@strapi/strapi/lib/core-api/routes/index.js:6:7)
    at get routes [as routes] (/home/pablo/github/ciudadela/backend/node_modules/@strapi/strapi/lib/factories.js:59:31)
```
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.5.2
- Database: postgresql
- Operating system: Ubuntu

### Describe the bug

Strapi fails to start when using the factory controler.

### Steps to reproduce the behavior

1. Build typescript plugin using cli
2. Build content type in plugin and bootrstrap API
3. Add API to routes
4. Strat Strapi

### Expected behavior

Strapi starts correctly and has expected routes 

### Code snippets

code for routes/index.ts
```typescript
import notification from "./notification";

export default {
  notification,
}

```typescript
code for routes/notifications/index.ts
/**
 *  router
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreRouter('plugin::notifications.notification');
```

**Comment by kepes** [comment]
Same issue here. I think when Strapi call `createCoreRouter` the plugin's (and other) content types not initialized yet. In `factories.js` at line 59 `strapi.contentTypes` give me only 5 initialized content-type:
```
'admin::permission'
'admin::user'
'admin::role'
'admin::api-token'
'admin::api-token-permission'
```

The problem can be avoided by not using the `createCoreRouter` command and defining each endpoint individually, such as in [Create custom routes](https://docs.strapi.io/developer-docs/latest/development/backend-customization/routes.html#creating-custom-routers)

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/14438
