### ISSUE TITLE
Strapi-bookshelf Model.create() is not a function.

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1505]
**Informations**
- **Node.js version**: v.9.11.1
- **npm version**: v.5.6.0
- **Strapi version**: 3.0.0-alpha12.6
- **Database**: PG
- **Operating system**: Linux Ubuntu 17.10

**What is the current behavior?**
First time I faced this bug when I tried to migrate to 12.5, now I created 12.6 new project, I faced it again. So, each service have this code: 
```
add: async (values) => {
    // Extract values related to relational data.
    const relations = _.pick(values, Transaction.associations.map(ast => ast.alias));
    const data = _.omit(values, Transaction.associations.map(ast => ast.alias));

    // Create entry with no-relational data.
    const entry = await Transaction.create(data);

    // Create relational data and return the entry.
    return Transaction.updateRelations({ id: entry.id, values: relations });
  },
```
On row `const entry = await Transaction.create(data);` it throws me an error 
```
TypeError: Transaction.create is not a function
    at Object.add (/home/dulgeoion/strapi-projects/alpha12.6-pg/api/transaction/services/Transaction.js:86:33)
    at create (/home/dulgeoion/strapi-projects/alpha12.6-pg/api/transaction/controllers/Transaction.js:90:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```
The same behavior has this row `const entry = await Transaction.update(params, data, { multi: true });` 
Remove service also throws an error.

So if we will console.log all `Model` methods, we won't find there `create` or `update`. We could find `create` just in this case `Model.collection().create(data)`. `Update` don't know where to find.

**Steps to reproduce the problem**
Try to create new project with pg and strapi-bookshelf, and create api.
`

**What is the expected behavior?**
Creating, updating and removing fileds in current model.

**Comment by lauriejim** [comment]
Hello @dulgeoion 
Did you follow migration guide instruction to move from `alpha.12.5` to `alpha.12.6` ?

**Comment by dulgeoion** [comment]
Hello @lauriejim! O created new project on 12.6, so this issue is not related to migration

**Comment by dulgeoion** [comment]
On 12.7 it started working. Strange thing.
