### ISSUE TITLE
lodash defaultsDeep is problematic for cors middleware (and potentially other middlewares, too)

### ISSUE THREAD

**Issue by GregorSondermeier** [strapi/strapi#15055]
### Required System information

- Node.js version: 14.20.1
- NPM version: 6.14.17
- Strapi version: 4.4.7
- Database: MariaDB
- Operating system: Ubuntu

### Describe the bug

The process to customize the `strapi::cors` middleware (actually all middlewares, but that's a topic for another day) is a bit problematic.

We have installed [strapi-plugin-transformer](https://market.strapi.io/plugins/strapi-plugin-transformer) and in there it mentions that we need to whitelist a custom header for CORS. The example code given is:

```
// /config/middlewares.js

module.exports = [
  // ..
  {
    name: 'strapi::cors',
    config: {
      headers: ['Strapi-Transformer-Ignore'],
    },
  },
  // ..
]
```

I'm not filing this issue under the plugin's repo because IMO the underlying issue that I'm about to explain is a Strapi issue:

In [/packages/core/strapi/lib/middlewares/cors.js](https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/middlewares/cors.js#L20) the [defaultsDeep](https://lodash.com/docs/4.17.15#defaultsDeep) function is used to merge the config provided in _/config/middlewares.js_ with the defaultConfig.

That is problematic because whenever I configure my own headers, `defaultsDeep` does not add it to the default list of headers, but instead merges it by index (and not even by value).

Strapi's default headers are:
`['Content-Type', 'Authorization', 'Origin', 'Accept']`

My custom config is:
`['Strapi-Transformer-Ignore'],`

The resulting merged headers are:
`['Strapi-Transformer-Ignore', 'Authorization', 'Origin', 'Accept']`

I don't think that's intended and it took my a while to debug this issue.

My current workaround is to set my custom config to:
`['Content-Type', 'Authorization', 'Origin', 'Accept', 'Strapi-Transformer-Ignore']`
So I essentially add my custom header to the existing headers as of Strapi v4.4.7.
But this is also problematic because whenever Strapi changes its default headers here, I will not know this.

### Expected behavior

I'm not sure tbh. I see a few possible options:

1. In [/packages/core/strapi/lib/middlewares/cors.js](https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/middlewares/cors.js#L20) check for arrays and merge both arrays by value, not by index. But this would essentially make it impossible to remove Strapi's default headers in the custom config and thus could be considered a breaking change. Also I guess there are more instance of this I'm not aware of.
2. Export the default config so that I as a developer can choose to import it or not, consequentally I can choose to extend the default list or provide my own list from scratch.

I personally prefer option 2, but have a feeling this has to be done more often anyway and this instance I found here is just the tip of the iceberg.

**Comment by derrickmehaffy** [comment]
I set this as a bug but also discussion as I don't know what was intended here, need to have engineering team confirm

**Comment by alexandrebodin** [comment]
Doing some spring clean up this was fixed a while back we do not use defaultsDeep anymore so users can overwrite completely. The default config is documented on our docs to help overwrite when necessary
