### ISSUE TITLE
[DynamicZones]: allow default setting of whether components should be collapsed or not

### ISSUE THREAD

**Issue by perostlin** [strapi/strapi#15061]
### Required System information

- Node.js version: 16.15.1
- NPM/YARN version: 8.11.0/1.22.17
- Strapi version: 4.5.3
- Database: PostgreSQL 11
- Operating system: macOS Ventura 13.0

### Describe the bug

When we upgraded to Strapi **v4.5.3**, we noticed that dynamic zones are open (**not collapsed**) by default in the admin panel.

### Expected behavior

We expect the dynamic zones to be closed (**collapsed**) by default.

#### Current
![image](https://user-images.githubusercontent.com/20464832/205254428-53c4a030-ccc2-4147-bba2-c24900c46e41.png)

#### Expected
![image](https://user-images.githubusercontent.com/20464832/205254760-6f758b1b-df40-4252-90f1-5e8a97237549.png)

### Additional context

We have many components with many fields in our dynamic zones and this makes it hard for our content managers to navigate/find the components they really want to change.

## Update 1

Tested this with a new installation of Strapi **4.5.3**, same result unfortunately.

```
npx create-strapi-app@latest my-project --quickstart
```

### Required System information

- Node.js version: 16.15.1/18.12.1
- NPM/YARN version: 8.11.0/1.22.17
- Strapi version: 4.5.3
- Database: better-sqlite3 7.4.6
- Operating system: macOS Ventura 13.0

### Screenshots
![image](https://user-images.githubusercontent.com/20464832/205257464-ad77d391-30e3-4d50-a069-8a3e3ce33cf0.png)

## Update 2

Since we now have the possibility to set **title** for components in dynamic zones, we would really appreciate if they where collapsed by default, or have the possibility to choose.

### Screenshots
![image](https://user-images.githubusercontent.com/20464832/205265448-0ab18a33-2374-4589-9316-d864216b1a4f.png)

**Comment by joshuaellis** [comment]
@maevalienard can you advise on this? It's a small change but good to know what you want the default behaviour to be :)

**Comment by maevalienard** [comment]
Hello @perostlin, thanks for the issue! 

I think I'd rather see the Dynamic zones open by default, for several reasons:
- One fewer click 
- Easier to see the content you actually want to change. In your case perostlin, I'm glad to see that your editors are able to know the component they want to change only based on the title, but I know that for a good majority, seeing the actual content is preferable
- Increase discoverability of the feature

Thank you for the ping and the idea 🌷

**Comment by Alacon** [comment]
I would really like this feature as well.
Or at least an option to change the default behavior.

Seems like there's no need for the accordion if they should be open for convenience.

**Comment by perostlin** [comment]
Hello @maevalienard, thank you for the response!

We do see that this might be the preferred way if the DZ does not contains that many components, in our case we have between 10-20 components, which makes the page not so easy to navigate and a lot of scrolling.

As @Alacon states, we can't really see the need for an accordion either, especially now when we also have the relations in the main view as well, it gets a little bloated.

Perhaps it could be a selection in the content manager if the DZ should collapse or not?

**Comment by joshuaellis** [comment]
I'm going to reshape this issue as a feature request whilst we discuss it :)

**Comment by perostlin** [comment]
Thanks for the fast feedback @joshuaellis and @maevalienard!

**Comment by maevalienard** [comment]
I'll discuss the topic with @yanniskadiri (Product manager of the squad related to this issue) :)

**Comment by youmeokay** [comment]
> Hello @perostlin, thanks for the issue!
> 
> I think I'd rather see the Dynamic zones open by default, for several reasons:
> 
>     * One fewer click
> 
>     * Easier to see the content you actually want to change. In your case perostlin, I'm glad to see that your editors are able to know the component they want to change only based on the title, but I know that for a good majority, seeing the actual content is preferable
> 
>     * Increase discoverability of the feature
> 
> 
> Thank you for the ping and the idea 🌷

Fair enough, still, I would need an option to collapse by default.
Maybe it could be a setting in the editors profile section, where you toggle between dark/light mode.

My feedback from editors and people who manage content is that it can be overwhelming to have all components open by default. Some of them would prefer to search for content by Component-Name. I guess it depends a bit on a subjective workflow, but when you have lots of components (around 20), you have to scroll quite a lot. And for some scrolling is worse than having to have 1 extra click.

**Comment by joshuaellis** [comment]
I'm going to lock this as we've already decided to take this onboard and look into the possibility of adding the option in the settings, we'll update when there's an update to be had.
