### ISSUE TITLE
Flags not been passed to CLI quickstart / ts

### ISSUE THREAD

**Issue by Eventyret** [strapi/strapi#15074]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: SqlLite
- Operating system: MacOs (Tested on Linux as well)

### Describe the bug

When using `npx create-strapi-app@latest my-app --typescript` flags are not passed, passing `--quickstart` will still ask the question if you want custom or quickstart.

This will prevent the user from passing --ts or --quickstart to create a project with quickstart settings and typescript.
### Steps to reproduce the behavior

1. Execute `npx create-strapi-app@latest my-app --typescript --quickstart`

### Expected behavior

Expected cli to start and not ask if we want quickstart or custom.
Also selecting quickstart will make it a `JS` project not TS even though flag was passed

### Screenshots
![image](https://user-images.githubusercontent.com/977232/205599405-b6cd1e1f-5636-4ef1-b64d-bba1681b04dc.png)

![Screenshot 2022-12-05 at 09 07 22](https://user-images.githubusercontent.com/977232/205599217-f7166fc8-fa99-452d-a032-b490ace1292c.png)

**Comment by rit001** [comment]
This is leaving something of an open question regarding the project.....

I'm trying to get my head around the whole eco-system and this issue badly tripped me up in the early days as it resulted in the deployment process not matching notes that are provided in the docs. 

At the same time it is raising another question - I'm looking into what it will take to combine strapi into the CI pipeline we have for our development and deployment cycle, but just what CI testing is done for changes in strapi? The loss of the whole command line interface for deployment would seem to be something that should have been spotted during the integration tests!

**Comment by Eventyret** [comment]
> This is leaving something of an open question regarding the project.....
> 
> I'm trying to get my head around the whole eco-system and this issue badly tripped me up in the early days as it resulted in the deployment process not matching notes that are provided in the docs.
> 
> At the same time it is raising another question - I'm looking into what it will take to combine strapi into the CI pipeline we have for our development and deployment cycle, but just what CI testing is done for changes in strapi? The loss of the whole command line interface for deployment would seem to be something that should have been spotted during the integration tests!

Don't think this is the place to discuss CI testing, as this issue has nothing to do with CI testing. 
You don't need to "install" strapi for the first time to do CI testing.

**Comment by rit001** [comment]
> Don't think this is the place to discuss CI testing, as this issue has nothing to do with CI testing. You don't need to "install" strapi for the first time to do CI testing.

The question was more about the CI process that the strapi code based is passed through when an update is made. Anything I do within my own CI process is building on the strapi CI process.

The background to my use of "install" is to create the tooling needed to create a docker image, so this process does start with the execution of "npx create-strapi-app@latest", so the loss of the CLI processing when combined with only a few days understanding of the strapi environment has been interesting.

**Comment by Eventyret** [comment]
> > Don't think this is the place to discuss CI testing, as this issue has nothing to do with CI testing. You don't need to "install" strapi for the first time to do CI testing.
> 
> The question was more about the CI process that the strapi code based is passed through when an update is made. Anything I do within my own CI process is building on the strapi CI process.
> 
> The background to my use of "install" is to create the tooling needed to create a docker image, so this process does start with the execution of "npx create-strapi-app@latest", so the loss of the CLI processing when combined with only a few days understanding of the strapi environment has been interesting.

Think we are getting a bit off topic here from what the issue was about.

If you want to create docker images, you want to create the image from a project. Not use Docker to create up a new project.
You want an existing project that you can run. Hence why you won't need the CLI / CI for testing.

It's only passing flags that is currently bugged it seems.
So you can simply do `npx create-strapi-app@latest` hit enter on `quickstart` and off to the races you are.
THEN make a docker image of the created project and do your testing.

**Comment by alexandrebodin** [comment]
Hi we have a fix we will relese on wenesday :)

**Comment by Eventyret** [comment]
@alexandrebodin thank you 😊

**Comment by bolg55** [comment]
fixed
