### ISSUE TITLE
CSRF-token not showing

### ISSUE THREAD

**Issue by Pavel-Mishalov** [strapi/strapi#1508]
**Informations**
- **Node.js version 9.3.0**:
- **npm version 5.5.1**:
- **Strapi version 3.0.0-alpha.12.6**:
- **Database (MongoDB v4.0.0)**:
- **Operating system (Ubuntu 18.04 LTS)**:

**What is the current behavior?**

In the file `config / environments / ** / security.json` I set the parameters csrf

```
  "csrf": {
    "enabled": true,
    "key": "_csrf",
    "secret": "_csrfSecret",
    "angular": true,
    "cookie": "csrf"
  }
```

Couldn't receive csrf token for my requests to your api

**Steps to reproduce the problem**

**What is the expected behavior?**
I expect to see a variable csrf in the cookie or in the result HTML, which I will pass in requests to the server

**Suggested solutions**

**Comment by reskwer** [comment]
need hepl
![image](https://user-images.githubusercontent.com/8849299/42539747-bb99612c-84a4-11e8-8f26-c0e1b5566b5b.png)

**Comment by reskwer** [comment]
@lauriejim - please tell me what to do so that I can use the CSRF token

**Comment by lauriejim** [comment]
Please check https://github.com/koajs/koa-lusca
