### ISSUE TITLE
Version 4.1.9 throws an error: "name": "ApplicationError", "message": "Email already taken" via Postman

### ISSUE THREAD

**Issue by PublicTrades** [strapi/strapi#15088]
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: 4.1.9
- Database: Postgres
- Operating system: MacOS

### Describe the bug

I recently setup an instance of Strapi  and Postgres via railway (https://railway.app), and tried making a few request to test the api. Upon making POST request to fetch/ update a user that was originally setup through Strapi admin, I am getting an `Email already taken` 404 error message.

### Steps to reproduce the behavior

1. Configured user `Content-Type` by adding a `user_role` field via Strapi admin (Note that this is not meant to replace the default Strapi  user role).
2. Saved the file, and the entry was successfully saved in the database.
3. Made a `GET Request` to `https://my-railway-url/api/users `  to retrieve `ALL USERS` successfully.
4. I made a Post request to `https://my-railway-url/api/auth/local` to get user info along with the `JWT token`
5. Received a `JWT token` along with user information.
6. Copied the `JWT Token` and made another POST request - with `body set to JSON`, entered info to update the existing user
7. Got an error `Email already taken`

### Expected behavior

User information updated with the new entries.

### Screenshots

https://freeimage.host/i/HCvcw0P

**Comment by derrickmehaffy** [comment]
The issue here is how you formatted the post request: 
![image](https://user-images.githubusercontent.com/8593673/210091571-085e65a1-2334-41a9-9820-61853be31b4b.png)

you shouldn't use `?id=3` but instead your url should be `/api/users/3` you are actually sending a POST request to the create endpoint, not the update one, likewise your method should be PUT, not POST
