### ISSUE TITLE
When create Entry with post method it brings {"statusCode":404,"error":"Not Found","message":"Not Found"}

### ISSUE THREAD

**Issue by JonasJustus** [strapi/strapi#1509]
Node 9.11.1 
npm 5.6.0
3.0.0-alpha.12.6
mongodb 3.4.14
Ubuntu 1604

**What is the current behavior?**
If you create a entry over an public post create call the system creates the entry but shows you afterwards
 {"statusCode":404,"error":"Not Found","message":"Not Found"}

**Steps to reproduce the problem**
on www.florian89.de
click on Neue Karte erstellen
type in something random in the first field and press send

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @JonasJustus , Can you make sure your form is well send to the correct URL.
Try with postman. If it's work with postman, it mean your front-end implementation is wrong.
