### ISSUE TITLE
Invalid service not detected at startup or build

### ISSUE THREAD

**Issue by nickvanballegooijen** [strapi/strapi#15091]
### Required System information

- Node.js version: 16.17.1
- NPM version: 8.15
- Strapi version: 4.5.3
- Database: postgres
- Operating system: windows

### Describe the bug
Strapi does not validate services after creating when starting the app, on build or listing the services.

I created the following service whis has incorrect code, because the service part `api::service-name.service-name` should not be closed with curly brackets. 
When calling the function i received the following error `error: strapi.service(...).serviceFunc is not a function`. My call was right so it was unclear what was causing this error. A validation on the service export would prevent that.

```javascript
`const { createCoreService } = require('@strapi/strapi').factories;

module.exports = createCoreService('api::service-name.service-name'), ({strapi}) => ({`
async serviceFunc(){
}
...
```
Correct code
```javascript
module.exports = createCoreService('api::service-name.service-name', ({strapi}) => ({`
```
### Expected behavior

Strapi valids the services on a build or when starting the application. This was bot not happening. Another possibility is to not list the service with `yarn strapi services:list` so it's clear that the service is invalid.

**Comment by bolg55** [comment]
please use the bug template to provide explicit steps to reproduce. Also, feel free to submit a PR if you believe you have a fix for this issue. Thanks!
