### ISSUE TITLE
Strapi upload or delete media stuck in endless loading

### ISSUE THREAD

**Issue by inc-ali** [strapi/strapi#15100]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.9.2 
- Strapi version: 4.5.0
- Database: PostgreSQL 
- Operating system: alpine (docker)

### Describe the bug

I am using the latest version of strapi. Up until recently I am not able to upload or delete any media (as an admin) when strapi is deployed in the cloud. 

When I upload or try to delete an image, it is stuck in an endless loading state. No errors are displayed in the interface, console or network view. The application log also outputs nothing. 

But running locally everything works as expected. 

I appreciate any hints on resolving or even debugging the issue. 

I have implemented the strapi-provider-upload-sftp-v2. 

### Expected behavior

Upload an image successfully or see a an error message for further debugging.

**Comment by bolg55** [comment]
Does this issue persist if you redeploy using v4.5.4?
