### ISSUE TITLE
The JSON Input traps the users cursor when tabbing through the form

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#15107]
### Required System information

- Node.js version: not applicable
- NPM version: not applicable
- Strapi version: v4.5.3
- Database: not applicable
- Operating system: MacOS

### Describe the bug

When tabbing through the CM Edit Form, the cursor is trapped by the JSON Input, which is an a11y issue:

https://user-images.githubusercontent.com/2244375/206162986-a47884e5-4960-4657-8070-62ca1bc1fa79.mp4

### Steps to reproduce the behavior

1. Create a content-type using a JSON field
2. Tab through the form in the content manager

### Expected behavior

I expect a way to leave the input.

**Comment by BhuvaneshPatil** [comment]
We are using codemirror for JSON input here.
It has overridden the TAB key behavior. We can disable it when we initialize the behavior by adding some options. The discussion can be found here - 

https://github.com/codemirror/codemirror5/issues/5444

Shall I go ahead and make a PR for same ?

Here is the video - 

https://user-images.githubusercontent.com/27822551/206867978-fc641185-b42e-44c6-8d90-645aef5000ba.mp4

**Comment by gu-stav** [comment]
@BhuvaneshPatil Thanks for sharing - that's amazing! We are currently in the process of moving the `JSONInput` into the design-system. @madhurisandbhor will open a PR soon. Can we ping you there once it is open to see if we the issue still exists and how we could solve it? 🙏🏼

**Comment by BhuvaneshPatil** [comment]
Glad I could help @gu-stav. I will definitely like to work on this issue. Do let me know if this issue persists.
