### ISSUE TITLE
Graphql plugin duplication

### ISSUE THREAD

**Issue by leon1995** [strapi/strapi#15102]
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: sqlite
- Operating system: macos

### Describe the bug

Strapi is not able to run with `plugin-graphql` plugin. I followed the [quick-start guide](https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html) and the [graphql documentation](https://docs.strapi.io/developer-docs/latest/plugins/graphql.html) to install the plugin, but the server is not starting anymore.

### Steps to reproduce the behavior

1. Create a new strapi app `npx create-strapi-app@latest strapi-test`
2. `cd strapi-test`
3. install graphql plugin `npm install @strapi/plugin-graphql`
This results in
```
[2022-12-07 08:49:57.531] debug: ⛔️ Server wasn't able to start properly.
[2022-12-07 08:49:57.533] error: Cannot use GraphQLScalarType "Time" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
Error: Cannot use GraphQLScalarType "Time" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

**Comment by NitoBa** [comment]
This happen because there are two different versions of graphql installed inside node_modules.
To solve this problem you need override the graphql version.
Add this in your package.json

```json
"overrides": {
  "@strapi/plugin-graphql": {
  "graphql": "15.8.0"
  }
}
```
Version 15.8.0 is the version before the latest

**Comment by alexissel** [comment]
I am having the same problem with Strapi v4.16.0

**Comment by BorisKamp** [comment]
How is this closed!? It's still happening

**Comment by NikitaPanteleev** [comment]
I solved this issue in the following manner.
1. run `npm list graphql` to see duplicated versions, in my case, all except for one versions are 16.8.1:
<img width="228" alt="Screenshot 2024-01-03 at 21 22 24" src="https://github.com/strapi/strapi/assets/4668362/26486caf-23a7-48b9-96eb-fead8ab06483">
2. so I added the following lines in package.json:
```
"overrides": {
    "graphql": "16.8.1" 
  },
```

**Comment by BorisKamp** [comment]
> I solved this issue the following way.
> 
> 1. run `npm list graphql` to see duplicated versions, in my case, all except for one version are 16.8.1:
> 
> <img alt="Screenshot 2024-01-03 at 21 22 24" width="228" src="https://private-user-images.githubusercontent.com/4668362/294031197-26486caf-23a7-48b9-96eb-fead8ab06483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MzQzNzgsIm5iZiI6MTcwNDYzNDA3OCwicGF0aCI6Ii80NjY4MzYyLzI5NDAzMTE5Ny0yNjQ4NmNhZi0yM2E3LTQ4YjktOTZlYi1mZWFkOGFiMDY0ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMTMyNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTRjN2IxNmE4M2FkYjFmYzJmN2ZhNmY2ZWU1MjhhMWRmOWUyNTg0MTZhZTQ1M2ZhNzBhYWY1YjUwNjliZGJmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5HarT3P9RinYy1cggEsNeG49lPLT1LvbHqWEIFwRlvk">
> 2. add the following lines in package.json:
> 
> ```
> "overrides": {
>     "graphql": "16.8.1" 
>   },
> ```

Thank you! This fixed it. I had the `15.8.0` version on `graphql-upload` as well. Who's 'fault' is this that it's not synced across all with the same `16.8.1` version?
