### ISSUE TITLE
Unable to deploy strapi to DigitalOcean Droplet. Refused to connect to 'http://localhost:1337/admin/project-type'

### ISSUE THREAD

**Issue by AakashPat** [strapi/strapi#15118]
**Bug report**

Strapi is not picking up the PUBLIC_URL and /admin is calling back to a localhost:port URL.

I have a clean install of Strapi which I hope to access through a reverse proxied internet address and the browser is reporting errors trying to access localhost:port. I have defined a public url in server.js according to instructions [here](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/server.html#available-options)

**config/server.js**

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('PUBLIC_URL', 'http://f4.mydomain.in'),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

**.env file**
```
HOST=0.0.0.0
PORT=1337
APP_KEYS=****,*****,***,***
API_TOKEN_SALT=****
ADMIN_JWT_SECRET=****
JWT_SECRET=****
PUBLIC_URL=http://f4.mydomain.in
STRAPI_ADMIN_BACKEND_URL=
```

**NGINX configuration**
```
server {  
    listen 80;
    server_name f4.mydomain.in;
    location / {  
                proxy_pass http://localhost:1337;  
                proxy_http_version 1.1;  
                proxy_set_header Upgrade $http_upgrade;  
                proxy_set_header Connection 'upgrade';  
                proxy_set_header Host $host;  
                proxy_cache_bypass $http_upgrade;  
    }  
}
```

bowser console errors:
![Screenshot 2022-12-08 at 12 06 34 PM](https://user-images.githubusercontent.com/10728448/206375695-7731356c-6196-4f74-90bb-fc9e634a96d4.png)

**Steps to reproduce the behavior**

- install strapi on a server
- configure nginx as above
- access admin for first time
- see console errors in the browser

**Expected behavior**
Strapi should replace "localhost:port" with PUBLIC_URL when calling back to the server

**System**
Node.js version: 16.13
NPM version: 8.1.2
Strapi version: latest
Database: Postgres
Operating system: ubuntu-22.04

**Comment by ecosse3** [comment]
Unfortunately I have exact same issue with AWS and newest Strapi.

**Comment by AakashPat** [comment]
I am using DigitalOcean. My Postgres database is in docker container.
Strapi is a simple installation like suggested from the docs.
I have tried every single combination.

But here is what I have found:
1. The actual backend REST API is working absolutely fine.
`http://f4.mydomain.in/api/teams`
2. I can access the graphql playground at the correct link and am also able to make queries as required. `http://f4.mydomain.in/graphql`
3. I am not able to access **ONLY THE ADMIN DASHBOARD.**

As a hack I have connected to the same Postgres database on my DigitalOcean Droplet from my local strapi project. That way, I can still access the console and update the data on the remote instance.

**Comment by jump24-luke** [comment]
We have the same issue when deploying to Google App Engine, I think it is a bug with Strapi.

I found the solution is to not set the `url` setting in `config/server.js` at all. Remove the line entirely. Like this:

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

The strapi frontend will automatically determine the correct URL from the browser.

**Comment by AakashPat** [comment]
> We have the same issue when deploying to Google App Engine, I think it is a bug with Strapi.
> 
> I found the solution is to not set the `url` setting in `config/server.js` at all. Remove the line entirely. Like this:
> 
> ```
> module.exports = ({ env }) => ({
>   host: env('HOST', '0.0.0.0'),
>   port: env.int('PORT', 1337),
>   app: {
>     keys: env.array('APP_KEYS'),
>   },
> });
> ```
> 
> The strapi frontend will automatically determine the correct URL from the browser.

Thanks for the recommendation. I will try this later tonight and report if that works.

As an alternative, I am resorting to running my strapi api in a docker container. That allows me to route everything just fine. And it also helped simplify my static asset storage configuration.

**Comment by ecosse3** [comment]
> I found the solution is to not set the `url` setting in `config/server.js` at all.

Unfortunately it doesn't work to me neither.

I saw another solution to put `STRAPI_ADMIN_BACKEND_URL=` env here: https://forum.strapi.io/t/deployed-strapi-admin-panel-trying-to-hit-localhost-1337/7598/25 (I use this env for preview custom plugin).

But it doesn't work to me neither.

**Comment by juanbercoff** [comment]
> As an alternative, I am resorting to running my strapi api in a docker container. That allows me to route everything just fine. And it also helped simplify my static asset storage configuration.

I think the issue is with nginx. In my case, I can access myurl.com:1337/admin as expected. But when I proxy the request with nginx to localhost:1337, myurl.com/admin throws 404. Also, it can't access assets/images/logo_login.png

**Comment by derrickmehaffy** [comment]
After you change the URL you need to rebuild the admin

**Comment by rortan134** [comment]
> After you change the URL you need to rebuild the admin

Will this behavior change anytime soon?
It does cause a few unexpected problems and the need to rebuild just for changing a single line.

**Comment by derrickmehaffy** [comment]
> > After you change the URL you need to rebuild the admin
> 
> Will this behavior change anytime soon? It does cause a few unexpected problems and the need to rebuild just for changing a single line.

It's not currently in our plan at the moment no: https://feedback.strapi.io/developer-experience/p/configure-strapi-backend-url-after-build
