### ISSUE TITLE
mongoose error when creating instance of model with only 2 one-to-many relations

### ISSUE THREAD

**Issue by doebi** [strapi/strapi#1511]
**Informations**
**Running latest docker image**
- **Node.js version**: (derived from docker image)
- **npm version**:  (derived from docker image)
- **Strapi version**: 3.0.0-alpha.12.4  (derived from docker image)
- **Database**: mongo
- **Operating system**: docker (Host: ubuntu 18.04)

**What is the current behavior?**

When creating a model i get this error:
```
 TypeError: utils.populate: invalid path. Expected string. Got typeof `undefined`
api_1      |     at populate (/usr/src/api/strapi-app/node_modules/mongoose/lib/utils.js:591:11)
api_1      |     at model.Query.Query.populate (/usr/src/api/strapi-app/node_modules/mongoose/lib/query.js:3295:30)
api_1      |     at params.parseRelationships.Object.keys.reduce (/usr/src/api/strapi-app/node_modules/strapi-mongoose/lib/relations.js:51:20)
api_1      |     at Array.reduce (<anonymous>)
api_1      |     at Function.update [as updateRelations] (/usr/src/api/strapi-app/node_modules/strapi-mongoose/lib/relations.js:28:129)
api_1      |     at <anonymous>
api_1      |     at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Steps to reproduce the problem**
The model has 2 one-to-many relations:

```

{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "model",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "a": {
      "model": "a"
    },
    "b": {
      "model": "b"
    }
  }
}
```

**What is the expected behavior?**
...

The model should be created.

**Suggested solutions**
...

I am not sure yet, whats causing this or if the problem is due to me using it wrong.
I tried to create a model using api first by sending
`{ "a": <id>, "b": <id> }` *I also verified to be sure, i send correct ids.*

Even when creating a model of that content-type in the web-ui admin i get the error mentioned above.

When creating a model through api with `{}` (empty model) it works.

**Comment by lauriejim** [comment]
Can you please open this issue in `strapi-docker` repo please.

**Comment by doebi** [comment]
Why?

If the application is broke, why should the error be in the environment?
Do you open a issue on linux, if your node javascript code fails to run?

Read. Think. Then think again before you answer. Please.

This issue is more related to the mongoose package than your docker deployment.

**Comment by doebi** [comment]
@lauriejim I request to reopen this issue.

**Comment by derrickmehaffy** [comment]
@doebi Because you are using docker on Strapi 12.4 (the latest version in that repo), the current release of Strapi is 12.6. We generally always ask for users to update to the latest release to confirm the issue, however the docker is not currently updated to the latest release.

Thus your issue is with Strapi 12.4 not Strapi 12.6, please open the issue for your environment, in this case docker. Previous release branches are not kept within the mono-repo design.

Also, I find it extremely distasteful to provide rude comments to the Strapi Team (which I am not apart of), that is not a very good way to get support. 

That being said, the strapi team divert all issues, related or not, for docker to the docker repo.

If you would like to create a Strapi 12.6 project not in docker and confirm the issue still exists then I'm sure this could be re-opened.

**Comment by doebi** [comment]
I cannot leave this uncommented. Yes I was being rude, but I was being rude in response. If someone takes the time to report a problem in order to contribute making this project more stable and mature, then closing that issue, without providing any meaningful or helpful content, is just plain rude aswell.

I can understand if you as a maintainer are overwhelmed by the amount of issues opened, but just closing them for no reason is no solution.

The docker not being updated to the latest version, sure deserves an issue in docker-strapi, but that is a completely different issue not related to the core of this one.

For your enlightenment i setup a 12.6 project and verified, that the issue still exists. You may or may not reopen this issue, I really don't care anymore. I guess, that due to our dispute this issue is not high on your priority list.

As a footnote I want to mention. Opensource is based on contributions of various people, where most of them spend their spare time. Still, them being maintainers does not make them better people, or allow them to be rude to users. In another project they might just be users as well. To ensure a healthy environment it requires a respectful social interaction in **both directions**. So keep in mind: What goes around comes around.

**Comment by derrickmehaffy** [comment]
@doebi can you provide re-producible steps to re-create this error outside of a docker container on Strapi 12.6.

Issues are closed as needed, typically if its a duplicate issue, not reproducible, outside the scope of this repo (IE docker environments) or not enough information is provided to re-produce the error for troubleshooting.

I just created a fresh Strapi 12.6 project using node 10, npm 6, and mongo and was able to create multiple models with multiple oneToMany relationships (max I attempted was 10 in one model).

As a footnote to the rest of your comment, I will message you on slack.

**Comment by lauriejim** [comment]
@doebi Thank you to report issue
I just ask you if you can create this issue in `strapi-doker`. It's every time the same message I send.
See https://github.com/strapi/strapi/issues/1455 https://github.com/strapi/strapi/issues/1430 https://github.com/strapi/strapi/issues/1368 It's not a rude message I think, no one of this guys was hurt by my message. Just have to copy and past your issue content in an other repo, in the good place to be handle.

Actually we have thousands issues to read and answer every week. We have some guide lines to keep issues sorted and classified to be able to fix it better and faster as we can. We not close issues just for fun.

To go forward on this issue, please open it on `strapi-docker` repo if you have an issue using docker.
If you have the issue with `alpha.12.6` without docker, please reopen one with full required information.

I lock the conversation. We have to go forward with smile and good mood
