### ISSUE TITLE
Filters by publishedAt in localizations i18n

### ISSUE THREAD

**Issue by spalz** [strapi/strapi#15115]
I use the i18n plugin

And I output records only if they have two translations:

```
&filters[$and][0][localizations][locale][$eq]=ky
&filters[$and][1][localizations][locale][$eq]=cn
```
**Result**
```javascript
{
   title: "...",
   locale: "fr",
   localizations: [
      {
         title: "...",
         locale: "ky"
      },
      {
         title: "...",
         locale: "cn"
      },
   ]
}
```

This works fine, but if one or more translations are in draft status, I just won't get them in the response, and the result will be like this:
```javascript
{
   title: "...",
   locale: "fr",
   localizations: [
      {
         title: "...",
         locale: "ky"
      }
   ]
}
```
Although I expect an empty answer since one translation is missing

Next I add a third filter by publishedAt:
```
&filters[$and][0][localizations][locale][$eq]=ky
&filters[$and][1][localizations][locale][$eq]=cn
&filters[$and][2][localizations][publishedAt][$notNull]=true
```
And it turns out that any filters with “localizations” and “NotNull" do not work

How else can I filter entries in localizations so that the filter takes into account the publication status?
Is this error or is it meant to be?

I would be grateful for any advice))

- Node.js version: v16.17.1
- Yarn version: 1.22.18
- Strapi version: 4.4.5
- Database: PostgreSQL 15.0
- Operating system: mac os

**Comment by Marc-Roig** [comment]
Hello :) This should be possible to make by using the publicationState query param ([see here for more info](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/api-parameters.html#api-parameters))

So for your case:
```
&filters[$and][0][localizations][locale][$eq]=ky
&filters[$and][1][localizations][locale][$eq]=cn
&publicationState=preview
```

With this you should receive all entities without taking into account the publication state
