### ISSUE TITLE
Strapi requires Node.js >=14.19.1 <=18.x.x 

### ISSUE THREAD

**Issue by storyandfortune** [strapi/strapi#15117]
I'm running node: 'v19.1.0' & Strapi won't install. I get the following errors. Will Strapi support future versions of node?

Need to install the following packages:
  create-strapi-app@4.5.3
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'create-strapi-app@4.5.3',
npm WARN EBADENGINE   required: { node: '>=14.19.1 <=18.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@strapi/generate-new@4.5.3',
npm WARN EBADENGINE   required: { node: '>=14.19.1 <=18.x.x', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.1.0', npm: '8.19.3' }
npm WARN EBADENGINE }
? Choose your installation type Quickstart (recommended)
You are running Node.js 19.1.0
Strapi requires Node.js >=14.19.1 <=18.x.x
Please make sure to use the right version of Node.

![Screen Shot 2022-12-07 at 4 21 17 PM](https://user-images.githubusercontent.com/90532776/206326098-a555a3b6-0b2f-477b-91b7-1c29484327da.png)

**Comment by rembrandtreyes** [comment]
From the docs. Strapi is now recommending node v18 🎉
> [Node.js](https://nodejs.org/): only maintenance and LTS versions are supported (v14, v16, and v18). Other versions of Node.js may not be compatible with the latest release of Strapi. Node v18.x is recommended for Strapi v4.3.9 and above, Node v16.x for Strapi v4.0.x to v4.3.8.

Now to answer the question. 
> Will Strapi support future versions of node?

Like @Eventyret said, Strapi is currently supporting the LTS versions of node. So node v19 might not make it, but you can more likely bet on node v20 to be supported.

**Comment by derrickmehaffy** [comment]
> From the docs. Strapi is now recommending node v18 🎉
> > [Node.js](https://nodejs.org/): only maintenance and LTS versions are supported (v14, v16, and v18). Other versions of Node.js may not be compatible with the latest release of Strapi. Node v18.x is recommended for Strapi v4.3.9 and above, Node v16.x for Strapi v4.0.x to v4.3.8.
> 
> Now to answer the question. 
> > Will Strapi support future versions of node?
> 
> Like @Eventyret said, Strapi is currently supporting the LTS versions of node. So node v19 might not make it, but you can more likely bet on node v20 to be supported.

As you said, node 19 will -never- make it because it's a development release (all odd versions are) and we only support LTS (which are even).

Node releases the new LTS versions every October which is when we evaluate and add support.

Marking this as closed and locked as we have the same discussion about this every year.
