### ISSUE TITLE
Update providers not persisted to database issue

### ISSUE THREAD

**Issue by bahdcoder** [strapi/strapi#1512]
**Informations**
- **Node.js version**:
9.10.1
- **npm version**:
5.6.0
- **Strapi version**:
 v3.0.0-alpha.12.6
- **Database**:
mongodb
- **Operating system**:
macosHighSierra

**What is the current behavior?**

Updating the authentication providers does not work. When providers are updated (and enabled, for example github), a successful confirmation message is received, but when trying to use said provider
to authenticate using the `/connect/github` endpoint, an error is received saying `Provider not enabled.`.
**Steps to reproduce the problem**
- Create a new strapi app
- Update and enable one of the providers, for example github
- Visit `http://localhost:1337/connect/github` in the browser.
- An error is received saying `Provider is not enabled.`.

- Restart your server
- Visit the page for updating providers. 
- Notice that Github has been reset to disabled, and all of its credentials have been cleared.

**What is the expected behavior?**

- Updating providers should be persistent and work properly.

**Suggested solutions**

I went through the code base, and I realised that the function used to update the providers is the cause of the problem.

```js

updateProviders: async (ctx) => {
    if (_.isEmpty(ctx.request.body)) {
      return ctx.badRequest(null, [{ messages: [{ id: 'Cannot be empty' }] }]);
    }

    await strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
      key: 'grant'
    }).set({value: ctx.request.body}); // RIGHT HERE, THIS IS THE PROBLEM.

    ctx.send({ ok: true });
  }

```

The data coming from the client side is stored in a `providers` key, like this:

```js
updateProviders: async (ctx) => {
   console.log(ctx.request.body); // { providers: { email: { ... }, github: { ... } ... } }
}

```

Because of this, the data stored is wrapped in a providers key before saving into the database. 

To fix this issue, the data passed into the `strapi.store().set` function should be: 

```js

updateProviders: async (ctx) => {
    if (_.isEmpty(ctx.request.body)) {
      return ctx.badRequest(null, [{ messages: [{ id: 'Cannot be empty' }] }]);
    }

    await strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
      key: 'grant'
    }).set({value: ctx.request.body.providers }); // RIGHT HERE, THIS IS THE FIX.

    ctx.send({ ok: true });
  }

```

I would gladly submit a PR to fix this if this is agreed to be a bug.

**Comment by derrickmehaffy** [comment]
Nice catch, I should be able to test this myself here soon as well. I would say go ahead and create the PR and submit it, further testing can be done and documented on the PR :+1:

**Comment by lauriejim** [comment]
@bahdcoder Thank you for your PR ! Will review it soon as possible ! Appreciate
