### ISSUE TITLE
Documentation plugin deactivate based on ENV variable

### ISSUE THREAD

**Issue by landoephan** [strapi/strapi#15127]
## Bug report

I'm having a k8s pod, which is read only (`readOnlyRootFilesystem` option set to true). Everything works fine until I activated the strapi documentation plugin (`yarn strapi install documentation`), since it tries to write something in the src directory. I'm getting following error:

```
Server wasn't able to start properly.
[2022-12-08 09:50:49.749] [31merror[39m: EROFS: read-only file system, open '/opt/app/src/api/contact-info/documentation/1.0.0/contact-info.json'
Error: EROFS: read-only file system, open '/opt/app/src/api/contact-info/documentation/1.0.0/contact-info.json'
error Command failed with exit code 1.
```

To fix this I want to activate and deactivate the plugin based on an env variable, but I can't find any documentation on how to do this. 

An alternative would be to add `@strapi/plugin-documentation` as devDependency instead of dependency, but then the plugin doesn't work anymore, even in dev mode.

Is there an option to deactivate the documentation plugin based on an env variable?

### Required System information

- Node.js version: 16.16.0
- NPM version: 8.11.0
- Strapi version: 4.5.3
- Database: postgres
- Operating system: linux

### Expected behavior

I can deactivate the documentation plugin in prod environment and activate it for development

**Comment by landoephan** [comment]
I can just configure it in plugins.ts/js:

```
export default ({ env }) => ({
  i18n: true,
  documentation: env('ACTIVATE_DOCUMENTATION_PLUGIN', false),
})
```

**Comment by landoephan** [comment]
this deactivates the plugin, but it stills wants to add the documentation files

**Comment by alexandrebodin** [comment]
Hi, in the process of reviewing old/stale issues 👋 

The config to disable the plugin is 
```js
module.exports = {
  documentation: {
	enabled: false // use env var here
  }
}
