### ISSUE TITLE
[Lifecycle hooks]: Relations no longer populated

### ISSUE THREAD

**Issue by perostlin** [strapi/strapi#15138]
### Required System information

- Node.js version: 16.15.1
- NPM/YARN version: 8.11.0/1.22.17
- Strapi version: 4.5.3
- Database: PostgreSQL 11
- Operating system: macOS Ventura 13.0

### Describe the bug

When we upgraded to Strapi **v4.5.0**, we noticed that relations no longer are populated in the lifecycle event result.

### Expected behavior

We would like to have relations populated in the lifecycle event result, like we did before **4.5.0**.

#### Current
```json
{ 
  "id": 1, 
  "enterprise": 
  { 
    "count": 1 
  } 
}
```

#### Expected
```json
{
  "id": 1,
  "enterprise": {
    "id": 1,
    "name": "Company Name",
    "createdAt": "2022-11-20T16:08:26.555Z",
    "updatedAt": "2022-11-21T12:57:40.255Z",
    "publishedAt": "2022-11-21T12:57:40.254Z"
  }
}
```

### Additional context

We use relation properties in our lifecycle hooks, so it would be nice to get all information needed in the event result, so we don't have to do extra database queries.

**Comment by pavelglac** [comment]
Have a similar problem. Now the lifecycle hooks returns only changed fields but in my case, I need them all. I am composing the URL of the category where the links depend on the URL of the parent category. So if someone changes just the slug of the category I am unable to compose URL bcs I don't get the parent id now.

**Comment by joshuaellis** [comment]
@Marc-Roig is this related to #14882? If so could we close this issue in respect to the former?

**Comment by Marc-Roig** [comment]
@joshuaellis yes it is, closing this issue as we will have the discussion in https://github.com/strapi/strapi/issues/14882.

We are working on a fix and plan to deliver it in the next release if possible :)
