### ISSUE TITLE
DateTime timezone issue on accessing data in through api

### ISSUE THREAD

**Issue by ssshah** [strapi/strapi#15135]
There is an already issue created but its closed without resolved.
i am trying to access the date time field data and filter on that field but its showing different data on different zones which is not correct i want to see same data everywhere regardless of the timezone 
https://github.com/strapi/strapi/issues/8739

**Comment by bolg55** [comment]
Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.
