### ISSUE TITLE
ID can not be fetched via Graphql query

### ISSUE THREAD

**Issue by vOtto** [strapi/strapi#15137]
### Required System information

- Node.js version: v16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: Postgres
- Operating system: Mac

### Describe the bug

ID column can not be fetched via graphql query.

### Steps to reproduce the behavior

Query record via graphql and include ID in query

### Expected behavior

query should return id

**Comment by bolg55** [comment]
please be more explicit with your steps to reproduce and the bug report in general.
