### ISSUE TITLE
Documentation link in GuidedTour is hard to read

### ISSUE THREAD

**Issue by rembrandtreyes** [strapi/strapi#15146]
## Bug report
Hi there 👋 I wanted to raise an issue with the documentation link in Guided Tours. The link is hard to read and as someone with color blindness, I had to get really close to my screen to read what the letters were saying. I also noticed the bullet points which don't seem to mesh with the styles for the modal. I would also expect the bullets to be white (This could be a separate issue).

This seems like an excellent first issue 🤔.

### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: Postgres
- Operating system: macOS

### Steps to reproduce the behavior

I am not sure how to trigger the Guided Tours again but it looks to be coming from this line within the `documentationLink` component https://github.com/strapi/strapi/blob/dd227e2b645901ff35aa8d599ecfe8bae27850ab/packages/core/admin/admin/src/components/GuidedTour/layout.js#L155 

### Expected behavior
Based from other links in Strapi the color we would expect is `rgb(123, 121, 255)`

#### Actual
<img width="693" alt="Screen Shot 2022-12-10 at 7 03 03 PM" src="https://user-images.githubusercontent.com/15057964/206887630-ea10a206-793b-4808-8df9-9c488e9d9b23.png">

#### Expected 
<img width="679" alt="Screen Shot 2022-12-10 at 10 12 39 PM" src="https://user-images.githubusercontent.com/15057964/206887647-aaaec4e9-2931-41d9-ac35-442b9f3c67bd.png">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by ronronscelestes** [comment]
good catch, thank you for highlighting this issue 😊
