### ISSUE TITLE
Drag icon in repeatable component not visible in dark mode

### ISSUE THREAD

**Issue by BhuvaneshPatil** [strapi/strapi#15141]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: Not Relevant
- Operating system: Windows 11

### Describe the bug

In the dark mode, the *Drag* icon is not visible, adding repeatable components.

### Steps to reproduce the behavior

 1.   Create a content-type with a repeatable component
 2.   Add items and observe.
 
### Expected behavior
Icon's color should change according to the mode. For Example - In light mode it has dark color.
That same color is being used here.

### Screenshots

On hover - 

![Drag Icon - On Hover](https://user-images.githubusercontent.com/27822551/206709023-e5084b9e-ec0f-4bbf-b1ea-ea8777647b7f.png)

Without hover - 

![Drag Icon - Without hover ](https://user-images.githubusercontent.com/27822551/206709031-4a92f6d5-11be-41d1-b678-9931b9619b28.png)

**Comment by BhuvaneshPatil** [comment]
I want to work on this issue.

**Comment by derrickmehaffy** [comment]
Confirmed in v4.5.4: 
![image](https://user-images.githubusercontent.com/8593673/209726354-96449753-5f8d-4148-ac6a-a952301c3710.png)

@BhuvaneshPatil please feel free to submit a PR and just add the `fixes #15142` to the PR description :)

**Comment by joshuaellis** [comment]
This will be fixed with `4.6`
