### ISSUE TITLE
Creating content with a component with the content type configuration "Draft/Publish= False" results in a "Woops! Something went wrong. Please, try again." error.

### ISSUE THREAD

**Issue by yuyj109** [strapi/strapi#15150]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.3 Enterprise Edition
- Database: postgresql
- Operating system: mac OS 13.0

### Describe the bug

Trying to upgrade from strapi v4.4.7 to v4.5.3.

Creating content with a component with the content type configuration "Draft/Publish = False" results in a "Woops! Something went wrong. Please, try again." error.

### Screenshots

1. content
<img width="773" alt="001-Classroom-Contents" src="https://user-images.githubusercontent.com/364807/207012361-e5482243-5f16-4bba-a920-feed43cad7c2.png">

2. relation
<img width="829" alt="002-Tutorial-relation" src="https://user-images.githubusercontent.com/364807/207012903-2bd9fa74-2b5f-4872-9817-10e932af986e.png">

3. Configurations
<img width="830" alt="003-Tutorial-Options" src="https://user-images.githubusercontent.com/364807/207012987-5159bd8a-0890-49e0-96b4-418576a9873d.png">

4. results

https://user-images.githubusercontent.com/364807/207013453-c331deca-4568-4ce0-a312-9882ea172da1.mov

`strapi develop --watch-admin` admin debug mode log

<img width="1797" alt="004-with-admin" src="https://user-images.githubusercontent.com/364807/207013941-3ea29038-88af-4df1-8929-d6e87867d654.png">

### Expected behavior

We expect to be able to register the same as in the v4.4.7 version.

**Comment by joshuaellis** [comment]
I've just tried to reproduce this bug & and I can't reproduce it on the latest version `4.6.0`.

This version of Strapi brought a lot of bug fixes to relations in the EditView and I encourage you to update your application. I will close the corresponding PR because it's not relevant anymore :)

If you can still reproduce on `4.6.0`, please open a new issue

**Comment by yuyj109** [comment]
The same error is reproduced, so create a new Issue after summarizing the conditions.

**Comment by derrickmehaffy** [comment]
> The same error is reproduced, so create a new Issue after summarizing the conditions.

I did also test starting at a lower version and upgrading as you did and I also could not reproduce. Do you have any plugins installed?

**Comment by yuyj109** [comment]
> I did also test starting at a lower version and upgrading as you did and I also could not reproduce. Do you have any plugins installed?

Reproduced with content changed from the example application(/examples/getstarted) in the main(e0e2d28f02) branch.
https://github.com/strapi/strapi/compare/e0e2d28f02...yuyj109:strapi:reporduce/required-single-components-woops

**Comment by yuyj109** [comment]
open a new issue: https://github.com/strapi/strapi/issues/15680
