### ISSUE TITLE
Issue when deleting an collection entry with no component defined on strapi v4

### ISSUE THREAD

**Issue by gghiguchi** [strapi/strapi#15156]
### Required System information

- Node.js version: 16.18.1
- NPM version: 6.14.17
- Strapi version: 4.4
- Database: Postgres
- Operating system: MacOS / Linux

### Describe the bug

This bug happens when trying to delete a collection row in list view on strapi admin interface. 

### Steps to reproduce the behavior

1. Create a collection type with at least one field and at least one component with one field
2. Create an entry for that collection type without adding the component
3. In Strapi Admin List View, delete that recently created entry
4. See error "Warning: An error occurred during record deletion." and the page will still display the deleted row, even though it did delete that entry

### Expected behavior

To delete the entry with no warning and refreshing the page so that the deleted entry is not displayed anymore

### Code snippets

The collection type json is 
```
{
  "kind": "collectionType",
  "collectionName": "model",
  "info": {
    "singularName": "model",
    "pluralName": "models",
    "displayName": "model",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "component": {
      "displayName": "new",
      "type": "component",
      "repeatable": false,
      "component": "new.new"
    },
    "title": {
      "type": "string"
    }
  }
}
```

And the component json
```
{
  "collectionName": "components_new_news",
  "info": {
    "displayName": "new",
    "icon": "archive",
    "description": ""
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string"
    }
  }
}
```

**Comment by bolg55** [comment]
Are you able to reproduce this with a new instance of Strapi running the latest version? I am unable to reproduce. Following your instructions, I am able to delete the entry.
