### ISSUE TITLE
Error when accessing a resource for which permission does not exist

### ISSUE THREAD

**Issue by leiyangyou** [strapi/strapi#1516]
**Informations**
- **Node.js version**: 9.4.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongodb
- **Operating system**: Mac OSX

**What is the current behavior?**
when accessing an object through the api for which a permission isn't defined, the following error in printed in console

```
TypeError: Cannot read property 'policy' of null
    at module.exports (/***/plugins/users-permissions/config/policies/permissions.js:51:18)
```

**Steps to reproduce the problem**

create a new strapi project
run
```
strapi start
curl http://localhost:1337/user/
```

**What is the expected behavior?**

no error should be produced

**Suggested solutions**

looks like the culprit is the following line

```
// Execute the policies.
  if (permission.policy) {
    return await strapi.plugins['users-permissions'].config.policies[permission.policy](ctx, next);
  }
```

either an early return, or checking of nullity of permission should be done

**Comment by COcisuts** [comment]
I've got same problem today trying cheesecake strapi official example...
https://github.com/strapi/strapi-examples/tree/master/cheesecakes
Cannot access to admin to continue the tutorial...

**Comment by gillesdm** [comment]
Same issue here. Trying to use Gatsby v2 to fetch articles and users (both which have been made through the Strapi admin panel). Also getting this error upon request.

**Comment by franksn** [comment]
@datboirog94 I don't have this problem using postgresql, yet i do when i use mongodb.

**Comment by AnilNewari** [comment]
Same issue her while accessing users data and other apis data.

**Comment by lauriejim** [comment]
@leiyangyou Did you test your suggested code ?

If it works can you submit a PR to share it with the community please. Will appreciate your contribution on this issue.

**Comment by doublemarked** [comment]
I'm getting this error also. The patch seems like it will sidestep the error, but how can I go about adding a policy for the specified route? In my admin panel, the route is simply missing from the model under "Roles & Permissions". It's not clear how I'm supposed to repair this so that I might apply an appropriate policy for the route.

**Comment by bManrique17** [comment]
yo tambien :(
