### ISSUE TITLE
Creating admin and adding Roles & Permissions while Bootstraping 

### ISSUE THREAD

**Issue by yadnyeshJTC** [strapi/strapi#15163]
#Requirement is to initialize db with prefill data 

### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.4.5
- Database:  better-sqlite3 version 7.4.6
- Operating system: MacOs Venture v13

### Describe the bug

Project is based on Typescript
Bootstrap all data for development purpose so that, whoever new working on the project will not be needed to insert all data in strapi admin panel.
Inserting an new data works fine but only when there is admin user is created. I am not able to create admin and roles from code please help.
Tried [https://github.com/strapi/strapi/issues/3365](https://github.com/strapi/strapi/issues/3365) this but it's not working for me. 

### Code snippets
below is the bootsrap function, currently i am coping .db file which is already filled with define data of admin and roles. Problem with this approach is there is no control over data. Need to fill admin and roles data from code like below i have done with home-page

`async bootstrap() {
    try {
      const isFirst = await isFirstRun();

      if (isFirst && process.env.NODE_ENV === 'development') {
        await fs.copyFileSync('./data/data.db', './.tmp/data.db');
        const data = await getHomePage();
        await strapi.services['api::home-page.home-page'].createOrUpdate({
          data,
        });

        console.log(
          '\x1b[32m%s\x1b[0m',
          `Development data copied successfully \nAdmin:${process.env.ADMIN} \npassword: ${process.env.ADMIN_PASS}`,
        );
      }
    } catch (e) {
      console.log(e);
    }
  },
};`

**Comment by bolg55** [comment]
Please include explicit steps to recreate the issue. Thanks
