### ISSUE TITLE
Plugin v4 : create components for Dynamic zone inside plugin

### ISSUE THREAD

**Issue by Thisisjuke** [strapi/strapi#15173]
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.3
- Database: postgresql
- Operating system: Ubuntu 22.04.1 LTS

### Describe the bug

I want to create components for `Dynamic Zone` inside a plugin. I create them inside the builder, and then I drag and drop them inside my plugin. I tried to alias them, but nothing seems to work.

### Steps to reproduce the behavior

1. Go to `Content type builder`
2. Create a model with a Dynamic zone and then create a component like `blocks/headingsBlock` with a text `name`.
Mine looks like this:
```json
{
  "collectionName": "components_block_headings_blocks",
  "info": {
    "displayName": "HeadingsBlock",
    "icon": "link",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "richtext"
    }
  }
}

```
3. Copy the generated file and do something with it. For example, I put it inside my plugin `content-types` folder and export them.
```tsx
import pageSchema from './page'
import headingsBlockSchema from './block/headings-block'

export default {
  'page': pageSchema, // working fine
  'headingsBlock': headingsBlockSchema, // not working
};
```
4. See error in the console or admin dashboard (details below)

### Expected behavior

- I can create components for Dynamic Zone in my plugin.
- I can find something to help me inside the documentation. 

### Screenshots

After some tweaking, I can display them in a hacky way: as you can see, it's not in the `component` section but in the `TYPES UNIQUES`
![image](https://user-images.githubusercontent.com/23522065/207442652-59907fd8-b6ef-4bd5-9e78-1eaa74f039d1.png)

### Code snippets

This does nothing:
```
  "kind": "component",
```

### Additional errors:
```
Error: The key of the content-type should be the same as its singularName. Found cta-block and undefined. at **validateKeySameToSingularName**
```
But I don't want to add it as a unique type, so I don't need a `singularName`

### Additional context

I investigated on my own and I am not able to figure how to do it.

I logged things in the core like: 
```
const validateKeySameToSingularName = (contentTypes) => {
  for (const ctName of Object.keys(contentTypes)) {
    const contentType = contentTypes[ctName];

    console.log(contentType)

    if (ctName !== contentType.schema.info.singularName) {
      throw new Error(
        `The key of the content-type should be the same as its singularName. Found ${ctName} and ${contentType.schema.info.singularName}.`
      );
    }
  }
};
```
My conclusion are that maybe it's not implemented yet ?

**Comment by derrickmehaffy** [comment]
Duplicate: 

- https://feedback.strapi.io/customization/p/dynamic-zone-in-components
- https://feedback.strapi.io/developer-experience/p/components-inside-of-plugins
