### ISSUE TITLE
Admin Uploads fails with axios >= 1.0.0

### ISSUE THREAD

**Issue by Pablo-Aldana** [strapi/strapi#15186]
## Bug report
If you upgrade to axios version greater than 0.27.2 (versions 1.0.0, 1.1.0 .... 1.2.1 ) file upload via web admin fails. 

### Required System information

- Node.js version: 16.5.1
- NPM version: 8.11.0
- Strapi version: 4.5.4, 4.5.3, 4.5.2
- Database: Postgress
- Operating system: Almalinux 9 and macOS Ventura

### Describe the bug

If you upgrade to axios version greater than 0.27.2 (versions 1.0.0, 1.1.0 .... 1.2.1 ) file upload via web admin fails, giving the following error:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/9969839/207868691-b1a776b9-f7ca-4f93-b0fe-c19684c38132.png">

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/9969839/207868512-8af82582-5077-4ef2-8282-9270297c8a42.png">

however It does not throw anything on the logs

### Steps to reproduce the behavior

1. got to package.json 
2. Upgrade version of axios from 0.27.2 to a newer 
3. run yarn install, yarn build, yarn development
4. Go to Media library and upload a file

### Expected behavior

File should upload without issues with newer versions of Axios.

### Additional context

We should be able to use newer versions of axios to avoid security issues and have bug fixes of this library.

**Comment by re2005** [comment]
Same issue, already couple months ago.
