### ISSUE TITLE
Image not show on content manager

### ISSUE THREAD

**Issue by reskwer** [strapi/strapi#1518]
**Informations**
- **Node.js version**: 9.11
- **npm version**:  5.11
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongo
- **Operating system**: win10 LTSB

**What is the current behavior?**
image not show 
![image](https://user-images.githubusercontent.com/8849299/42291232-21b9914c-7fd3-11e8-88b4-fe8a2e6898f2.png)

**Steps to reuser imageproduce the problem**

add user image

**What is the expected behavior?**

showed image

**Suggested solutions**

**Comment by asos-VasilisKortsimelidis** [comment]
Also, in case its helpful, when you make a `GET` request you can't see the url of the image, its empty.

![screen shot 2018-07-05 at 15 42 59](https://user-images.githubusercontent.com/35957481/42330158-5ff78670-806a-11e8-91dd-9bd6875c3bb5.png)
