### ISSUE TITLE
Install error if SQLite is selected as the database

### ISSUE THREAD

**Issue by jasonjg** [strapi/strapi#15185]
### Required System information

- Node.js version: 18.9.0
- NPM version: 9.2.0
- Strapi version: 4.5.4
- Database: SQLite
- Operating system: WSL2 Ubuntu 20.04

### Describe the bug

This error occurs when installing with SQLite selected as the database.  
It appears to occur during installation of the better-sqlite3 v7.4.6 package.  
It does not occur when installing with MySQL selected as the database.

### Steps to reproduce the behavior

1. Type "npx create-strapi-app@latest my-project"
2. Choose "Quickstart" **OR** Choose "Custom (manual settings)" and SQLite
3. During installation, observe the following error: 
`npm ERR! path /home/user/my-project/node_modules/better-sqlite3`

### Expected behavior

This does not happen when choosing MySQL as the database, so I expected the installation to finish without error.

### Code snippets

```
npm ERR! code 1
npm ERR! path /home/user/my-project/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.4.6 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.9.0 runtime=node arch=x64 libc= platform=linux)
```

### Additional context

I was able to fix this issue by changing the better-sqlite3 version in package.json to the most current version, 8.0.1 .

1. Open "package.json" in the "my-project" directory.
2. Within the `"dependencies"` object, change `"better-sqlite3": "7.4.6"` to `"better-sqlite3": "8.0.1"`
3.  Type `npm install`

**Comment by derrickmehaffy** [comment]
Can you make sure you have the debian package `build-essential` installed? It looks like you were missing some build tools.

**Comment by jasonjg** [comment]
Hi Derrick,

Thanks for your response.  I'm still learning how to use Linux so your comment is very helpful.  I ran `apt list --installed` and `build-essential` did not show up.  I'll install the package and try a fresh install of Strapi.

From what I've read the package might not have been installed because I'm using the WSL version of Ubuntu.  I've updated the OS in my initial post to reflect that.  Thanks again.

**Comment by jasonjg** [comment]
I installed `build-essential` and Strapi installation completed without error.  Thank you!

**Comment by derrickmehaffy** [comment]
> Hi Derrick,
> 
> Thanks for your response. I'm still learning how to use Linux so your comment is very helpful. I ran `apt list --installed` and `build-essential` did not show up. I'll install the package and try a fresh install of Strapi.
> 
> From what I've read the package might not have been installed because I'm using the WSL version of Ubuntu. I've updated the OS in my initial post to reflect that. Thanks again.

Nah it's not just WSL, it's not installed by default as a norm "non-dev" won't need it. Usually it's only needed when you need to compile packages from source which in your case is most likely due to either SQLite not having a prebuilt binary for your system or Sharp (lib-vips) for the same reason.

Glad you got it working!
