### ISSUE TITLE
Getting error - Cannot read properties of undefined (reading 'isEE') when customizing application URL

### ISSUE THREAD

**Issue by bioker** [strapi/strapi#15183]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: SQLite
- Operating system: Ubuntu 22.04

### Describe the bug

When following a quickstart guide with a little change of customizing application URL via `url: /strapi` argument in `config/server.js` I can see the following error in the web console after the application build and start - `Cannot read properties of undefined (reading 'isEE')`.

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest my-project --quickstart`
2. Go to the directory and add `url: /strapi` to `config/server.js`
3. Run `npm run build` and `npm run develop`
4. See the error in the web console once the browser is automatically opened after the application starts

### Expected behavior

I would expect the URL parameter to be customizable without such issues.

### Screenshots

![image](https://user-images.githubusercontent.com/15965645/207732288-15c9b0e7-23e0-492b-8139-6033f97f249e.png)

### Code snippets

my config/server.js:

```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  url: '/strapi',
});
```

**Comment by ivanThePleasant** [comment]
Hey 👋

It looks like you might have followed documentation incorrectly. If you are trying to change the admin url on the same server (eg. change url from `http://localhost:1337/admin` to `http://localhost:1337/strapi`), then you should add the desired url to the `config/admin.js` file, not `config/server.js`. If, on the other hand, you are indeed trying to change url for a different server, then `config/server.js` file should have a full url (https://example.com/).

**Comment by bioker** [comment]
Thanks for the hint @ivanThePleasant :+1: I will try to use a full URL for now.

**Comment by ivanThePleasant** [comment]
No worries @bioker, thank you. Feel free to reopen in case the issue is not resolved 😊👍

**Comment by Rutvij07** [comment]
@ivanThePleasant with UI routing I also want to change my server routing also , how can I do that
