### ISSUE TITLE
Add two different Enumeration Values returns Duplicate Error

### ISSUE THREAD

**Issue by arslion** [strapi/strapi#15180]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: Mysql
- Operating system: Ubuntu

### Steps to reproduce the behavior

1. Go to 'Content-type Builder'
2. Add New Enumeration field in Any content-type
3. Add these two values (UTC+12, UTC-12)
6. Click on 'Finish'
7. See error

### Expected behavior

As they are two different values it should be fine.

### Screenshots

![image](https://user-images.githubusercontent.com/3967627/207697363-a31f96e8-eea3-4afa-b0dd-96506373ef38.png)

**Comment by bolg55** [comment]
I don't think this is a bug, as the error is quite explicit that it only accounts for alphanumeric characters, so both are viewed as UTC 12:00. I will mark this as an enhancement for consideration instead.

**Comment by sudo-allahrakha** [comment]
Issue #16477 
May be a good use case . 


![Image](https://user-images.githubusercontent.com/81164804/234547886-831025b3-c544-4f4b-940c-dcfa306a255c.png)
