### ISSUE TITLE
Width of relation field is not 100% in Content Manager

### ISSUE THREAD

**Issue by radoslavzeman** [strapi/strapi#15191]
### Describe the bug

When I set the width of relation field to 100% in Configure view settings, the actual select field is not 100% wide. Only the list of selected entities is 100% wide. Similarly for 66%. The 50% width seems to work properly.

### Steps to reproduce the behavior

1. Set the width of some relation field to 100% in Configure view.
2. Check the width in Content manager
3. See that the width of actual select field is not 100%. Only the listed entities have the full width. Similar behaviour for 66%.

### Expected behavior

The width of relation fields in Content manager should respect configured view width.

### Screenshots

![image](https://user-images.githubusercontent.com/19418224/208028812-f99a9b1d-be8c-45ba-b5ff-95c3815a6bd7.png)

### Additional context

We use long slugs (urls) as main field for page relations, so it is crititcal for us to see the whole slug in 100% width mode. As there is no hover tooltip with full slug anymore, you can see just shortened slug if the slug is too long.

### Required System information

- Node.js version: v16.15.0
- Yarn version: 1.22.18
- Strapi version: 4.5.1
- Database: Postgres
- Operating system: macOS Monterey

**Comment by ronronscelestes** [comment]
hi @radoslavzeman, thank you for sharing this UI issue.
it was a design decision so far so we would need @maevalienard opinion on it 👀

**Comment by maevalienard** [comment]
I'll wait to see if we have more similar comments before changing this :) 

Thank you for letting us know @radoslavzeman :)

**Comment by radoslavzeman** [comment]
Hi, thanks for the answer 🙂  I did't expect it to be a design decision 😄 I don't see much advantage of it, but surely there is some reason behind it.
Okay, let's see.
