### ISSUE TITLE
[Bug]: REST API UPDATE Error at 4.5.4 version when data with component Component (repeatable) nested 

### ISSUE THREAD

**Issue by Marcosul** [strapi/strapi#15190]
### Required System information

- Node.js version: v14.19.1
- NPM version: 6.14.16
- Strapi version: 4.5.4
- Database: MYSQL
- Operating system: Ubuntu 20.04

### Describe the bug

After updating my project from version 4.5.3 to 4.5.4 the UPDATE (PUT) function of an endpoint where the sent goal contained a repeatable component nested within another repeatable component, I start showing a 500 error as a return.

After returning my project to version 4.5.3 the function worked again.

Below is an object submitted to update a repeatable component called "sections" with another nested repeatable component called "elements" that throws an error in the REST API UPDATE (PUT) endpoint in version 4.5.4:

`{ "data": { "sections": [ { "id": 1, "name": "fff", "elements": [ { "id": 22, "type": "heading1", "content": [ { "text": "Sua joia", "type": "h1", "hover": { "color": [ "gray.900", "white" ] } } ], "name": null } ] }, { "id": 2, "name": "xxx", "elements": [ { "id": 33, "type": "heading2", "content": [ { "text": "Sua joia", "type": "h1", "hover": { "color": [ "gray.900", "white" ] } } ], "name": null } ] } ] }}`

**Comment by petersg83** [comment]
Do you have the logs of the server?

**Comment by Marcosul** [comment]
@petersg83 , I don't have the server log because it just showed error code 500 (Internal server error) and I had to revert to version 4.5.3.

But I put the details of the event in the description to reproduce the scenario and identify the problem.

**Comment by derrickmehaffy** [comment]
I'm unable to reproduce on v4.5.5

Original data request:

![image](https://user-images.githubusercontent.com/8593673/210112982-9591ef75-312b-425c-8b15-38899895cedf.png)

Updated with 2 nested components (one single, one repeat):

![image](https://user-images.githubusercontent.com/8593673/210113012-d35f4c3b-f378-419e-bc88-1971b27c56bd.png)
