### ISSUE TITLE
strapi 3 with Angular 2

### ISSUE THREAD

**Issue by sbacem** [strapi/strapi#152]
There are ideas to integrate angular 2 in strapi.
Example : use angular 2 for administration panel ?

There is a date release Strapi 3 ?

**Comment by pierreburgy** [comment]
@sbacem, the new administration panel will be developed using React and released in the next few weeks. Of course, the APIs created with Strapi will be fully compatible with any angular 2 based front-end applications.

**Comment by sbacem** [comment]
:cool:  so v3 coming very soon, this is very interesting.

There is plugin like[ angular sdk](http://loopback.io/doc/en/lb2/AngularJS-JavaScript-SDK.html) in [loopback ](http://loopback.io/) ?

I will want migrate my app from loopback to strapi, but is better to starting 1.5 or expect v3 ?
It will have a tool to migrate from strapi v1.5 to 3 ?

**Comment by pierreburgy** [comment]
We will probably develop a JavaScript SDK, so it will make sense to create an Angular SDK on top of it.

Until v3 official release, please use Strapi v1.5: v3 is not stable enough to be use for a production ready project.

**Comment by sbacem** [comment]
@pierreburgy  thank you for the answer.

**Comment by crisz** [comment]
What about the Angular SDK?

**Comment by lauriejim** [comment]
It's not plan to create it now. Javascript SDK is available https://github.com/strapi/strapi-sdk-javascript
