### ISSUE TITLE
How would I create my own APP_KEYS, API_TOKEN_SALT, ADMIN_JWT_SECRET and JWT_SECRET?

### ISSUE THREAD

**Issue by csharpee** [strapi/strapi#15206]
https://auth0.com/blog/brute-forcing-hs256-is-possible-the-importance-of-using-strong-keys-to-sign-jwts/

I need to create my own secure keys based on my own algorithm, how would I do this for my Strapi project? I don't want my keys _auto_ created by someone else.

**Comment by Eventyret** [comment]
Don't think this needs to be a github issue either the forums or discord should suffice for answers.

**Comment by petersg83** [comment]
You can set them in the config file, for instance API_TOKEN_SALT is `apiToken.salt` https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/admin-panel.html#available-options

You can check the way it's done in the getStarted example : https://github.com/strapi/strapi/blob/main/examples/getstarted/config/admin.js

**Comment by csharpee** [comment]
@Eventyret I personally think everybody should have the *choice* to choose if they want their keys auto generated or if they want to create their own keys. 

@petersg83 I understand this, I am simply speaking on how to create ones own keys via CLI. 

I wasn't sure if anything would break and haven't tested my own set of keys on a fresh Strapi project.

**Comment by Eventyret** [comment]
Absolutely just generate the key and set it. 😊
All I was saying was it was answered multiple times in discord and the forums. How to set it that is.

**Comment by csharpee** [comment]
The problem is I haven't fiddled with this myself..nor have I found any documentation on how this is accomplished via CLI without a NPM package. 

I see Strapi makes use of Auth0  https://www.npmjs.com/package/jsonwebtoken npm package, but creating these keys aren't difficult to do for ones own spacetime continuum.. 

As an _example_, 

my .env.example displays
```
HOST=0.0.0.0
PORT=1337
APP_KEYS=asdadsfasdfaGQ==,asdfasdfadsfasdfA==,asdfasdfasdfasdf==,asdfasdfasdfsaf==
API_TOKEN_SALT=asdfasdfasdfasdf==
ADMIN_JWT_SECRET=asdfasdfasdfasg==
JWT_SECRET=asdf/asdf/asdfasdf==
```

Each secret needs to be generated and used in place of each VARIABLE. 

Will each variable accept *any* type of key and does it matter how big the key is? Do I need to sign the keys or anything else? Maybe I am thinking to deeply about this, but it is important to me.

If I generate my own keys via CLI with openssl, I am able to do it man different ways.. 

As a simple example, 

`openssl rand -base64 32`

`openssl rand -base64 128`

both sets of keys are entirely different. and from what @Eventyret has said, _any_ **type** of key at _any_ length will work.

**Comment by Eventyret** [comment]
I would not make it to long i think highest I go is 32 with openssl rand base64 but yes it needs to be a strong. App keys needs to be 2-3 comma seperated strings

**Comment by credwards27** [comment]
For anyone still getting here from a search engine:

`openssl rand -base64 <number>`

The create-strapi-app tool uses this for the .env file:

`openssl rand -base64 16`

**Comment by Eventyret** [comment]
> For anyone still getting here from a search engine:
> 
> `openssl rand -base64 <number>`
> 
> The create-strapi-app tool uses this for the `.env` file:
> 
> `openssl rand -base64 16`

Note on this it needs to be a `unix` system so `linux` or `mac` for windows you need gitbash to use the above command from @credwards27

**Comment by zirhoo** [comment]
You can copy paste in your shell 

```

# Generate keys
APP_KEYS=$(openssl rand -base64 16),$(openssl rand -base64 16),$(openssl rand -base64 16)
API_TOKEN_SALT=$(openssl rand -base64 16)
ADMIN_JWT_SECRET=$(openssl rand -base64 16)
TRANSFER_TOKEN_SALT=$(openssl rand -base64 16)

# Print results
echo "APP_KEYS=$APP_KEYS"
echo "API_TOKEN_SALT=$API_TOKEN_SALT"
echo "ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET"
echo "TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT"
```
