### ISSUE TITLE
[Bug] Public Access to Images should be disallowed

### ISSUE THREAD

**Issue by csharpee** [strapi/strapi#15204]
### Required System information

The Strapi version I am using is : **4.5.4**. 
Yarn version: ` v1.22.11`
Node version: `v14.21.1 `

### Describe the bug

I disable access to **uploads** , but still have access to the images on my Strapi CMS.

### Steps to reproduce the behavior

1. Go to Strapi CMS as a public viewer and download a known image.

```
https://cms.example.com/uploads/galactic_andromeda_workstation_393e5d94d4.webp
```
2. Notice a image in the viewer of the browser.

### Expected behavior

I should receive a *401* unauthorized request when accessing a image from Strapi CMS host.

**Comment by csharpee** [comment]
Further research doesn't provide any real solutions. 

I was :thinking: about disabling it via *nginx* but , this may completely disable downloading the images all together. 

The images aren't private, but downloading these images could increase bandwidth and potentially create a DDOS type attack on the CMS server. 

Some research on the subject: 

https://scribe.bus-hit.me/@tomhetto/how-to-protect-uploads-route-with-a-custom-policy-779c455603a8

https://forum.strapi.io/t/private-media-uploads/321

https://stackoverflow.com/questions/65018674/strapi-upload-to-local-private-path

**Comment by bolg55** [comment]
Can you provide more explicit steps to reproduce, as well as if you are trying to get the image from the admin panel or elsewhere.

**Comment by csharpee** [comment]
> Can you provide more explicit steps to reproduce, as well as if you are trying to get the image from the admin panel or elsewhere.

Goto a image you have uploaded to your Strapi project..

https://www.example.com/uploads/a-image-upload.jpg

**Comment by derrickmehaffy** [comment]
Closing in favor of: https://feedback.strapi.io/feature-requests/p/modify-or-allow-for-privatesecured-files
