### ISSUE TITLE
[Bug] The order of repeatable components will be lost after updating an entry in version 4.5.4

### ISSUE THREAD

**Issue by Frully** [strapi/strapi#15205]
### Required System information

- Node.js version: 18.12.1
- Strapi version: 4.5.4
- Database: MySQL 8.0.3.1
- Operating system: macOS 13.0.1

### Describe the bug

The order of repeatable components will be lost after updating an entry in version 4.5.4

**Comment by raph941** [comment]
Hi @Frully.
Thanks for raising this issue. 
It would help to quickly identify the potential issue here if you could add a `Step to reproduce` section, and/or a quick screen recording on how to reproduce this issue. 
Also the expected behavior you would ideally want to happen here.

**Comment by mirkooom** [comment]
it seems the same issue i reported here https://github.com/strapi/strapi/issues/15035

**Comment by derrickmehaffy** [comment]
> it seems the same issue i reported here https://github.com/strapi/strapi/issues/15035

Indeed thanks, closing as duplicate.
