### ISSUE TITLE
Custom error messages from beforeDelete lifecycle hooks are not shown in the content manager UI

### ISSUE THREAD

**Issue by soudis** [strapi/strapi#15215]
### Required System information

- Node.js version: 16
- NPM version:
- Strapi version: 4.5.1
- Database: mariadb
- Operating system: ubuntu 22.04

### Describe the bug

When throwing error messages in the beforeDelete or beforeDeleteMany lifecycle hooks the content manager does not show the error message, but just the generic message: 

>  “Warning An error occurred during record deletion."

This works fine with other hooks like beforeUpdate or beforeCreate, but not for the beforeDelete* hooks.

See also: https://forum.strapi.io/t/throw-error-message-in-lifecycle-hook-doesnt-change-the-error-message-display-in-the-ui/1515/17

### Steps to reproduce the behavior

1. Create lifecycle hook for an entity type

```TypeScript
import { errors } from '@strapi/utils';

export default {
  async beforeDelete(event) {
    throw new errors.ApplicationError("Test Message");
  },
};
```

2. Try to delete entity in content manager.

### Expected behavior

The custom error message "Test Message" is shown to the editor.

**Comment by derrickmehaffy** [comment]
FYI tested this in my recent best practices video and it works fine: https://www.youtube.com/watch?v=zjOSx9il98Q
