### ISSUE TITLE
Reset admin CLI command does accept params

### ISSUE THREAD

**Issue by caseymilne** [strapi/strapi#15227]
## Bug report
CLI command for reset admin password, npm run strapi admin:reset-user-password fails by not accepting any params. Any entry for "email" or "password" as described in the docs results in the error message: Missing required options `email` or `password`.

Tested using both --email=name@example.com as well as -e=name@example.com. Regardless of flag used, error response is always missing options. Tested both --password=newPassword and -p=newPassword. Error message is always missing required options.

### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.4.7
- Database: sqlite
- Operating system: Windows10

### Steps to reproduce the behavior

1. Enter the command into CLI at the Strapi project root: npm run strapi admin:reset-user-password --email=name@example.com --password=newPassword123

### Expected behavior
Expected command to accept params and prompt confirmation of admin password change.

**Comment by bolg55** [comment]
not able to reproduce. Can you try using `yarn strapi admin:...` or `npx strapi admin:...` You might also want to test on a new project using v4.5.x+ to see if the error persists.

**Comment by caseymilne** [comment]
npx strapi admin:reset-user-password worked.
