### ISSUE TITLE
Custom GraphQL Resolvers without auth token throws Forbidden access.

### ISSUE THREAD

**Issue by zamudio1243** [strapi/strapi#15226]
### Required System information
- Node.js version:  v16.17.0
- NPM version: 8.15.0
- Strapi version: 4.5.0
- Database: mariadb:10.3
- Operating system: win11

### Describe the bug
I need to create a custom public GraphQL resolver, but any custom GraphQL resolver that I made needs an access token.
For example: 
```ts
extensionService.use({
      typeDefs: `
        type Query {
            customGetProducts: [ProductEntityResponse!]
        }
	`,
      resolvers: {
        Query: {
         customGetProducts: {
            resolve: async (parent, args, context) => {
              const { toEntityResponse } = strapi.service(
                "plugin::graphql.format"
              ).returnTypes;

              const products = (await strapi.entityService.findMany(
                "api::product.product",
                {
                  filters: {
                    $or: [
                      
                      {
                        id: 6,
                      },
                      {
                        id: 5,
                      },
                    ],
                  },
                }
              )) as Product[];
              return products.map((product) => toEntityResponse(product));
            },
          },
        },
      },
    )

```
Now, if I send a request with Bearer Auth, the custom resolver works
![image](https://user-images.githubusercontent.com/47469444/208779683-a4801025-30e7-476f-a839-53f41ad6b49f.png)

But if I send this request without Bearer Auth, it throws me a Forbidden access
![image](https://user-images.githubusercontent.com/47469444/208779799-190c95ad-7e2c-4bad-a373-12372492ba70.png)

**Comment by bolg55** [comment]
routes are protected by default. In the admin, can you make sure you go to Settings > Users & Permissions: Roles > Public and enable the correct permissions. 

Also, please use the Bug report template to outline steps to reproduce.

**Comment by RamiroEda** [comment]
You need to add the `resolversConfig` field on the `extensionService.use` function as shown [in the documentation](https://strapi.io/blog/extending-and-building-custom-resolvers-with-strapi-v4).

> Let's define configurations to allow us public access when making the request.
> ```ts
> resolversConfig: {
>     "Query.authorsContacts": {
>         auth: false,
>     },
> },
> ```

Hope it helps!

**Comment by zamudio1243** [comment]
Thaks so mucho @RamiroEda. it works !!!!
