### ISSUE TITLE
Custom api routes and controllers return 404 not found

### ISSUE THREAD

**Issue by marceloavf** [strapi/strapi#1522]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 6.0.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: MongoDB
- **Operating system**: Windows 10

**What is the current behavior?**
After creating an API with `Content Type Builder`, I tried to include a new `router` and `controller` in a GET method, but it returns 404 status with not found error.

```json
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

**Steps to reproduce the problem**
- Create a simple API using `Content Type Builder`
- Include a new router, e.g.:

path: `api/arquivo/config/routes.json`
```json
{
      "method": "GET",
      "path": "/arquivo/latest",
      "handler": "Arquivo.latestDigitalOcean",
      "config": {
        "policies": []
      }
    },
```

- Include a new controller function for this router

path: `api/arquivo/controllers/Arquivo.js`
```js
/**
   * Retrieve a arquivo latest record.
   *
   * @return {Object}
   */

  latestDigitalOcean: async (ctx) => {
    ctx.status = 200;
    return ctx.send('Hello World!');
  },
```

- Acess it in `http://localhost:1337/arquivo/latest`

**What is the expected behavior?**
Accept to create custom routes for the API

**Comment by marceloavf** [comment]
Changing the order make it work again, any reason why ?

```diff
{
  "routes": [
    {
      "method": "GET",
      "path": "/arquivo",
      "handler": "Arquivo.find",
      "config": {
        "policies": []
      }
    },
+    {
+      "method": "GET",
+      "path": "/arquivo/latest",
+      "handler": "Arquivo.latestDigitalOcean",
+      "config": {
+        "policies": []
+      }
+    },
    {
      "method": "GET",
      "path": "/arquivo/count",
      "handler": "Arquivo.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/arquivo/:_id",
      "handler": "Arquivo.findOne",
      "config": {
        "policies": []
      }
    },
-    {
-      "method": "GET",
-      "path": "/arquivo/latest",
-      "handler": "Arquivo.latestDigitalOcean",
-      "config": {
-        "policies": []
-      }
-    },
}
```

**Comment by hectorgrecco** [comment]
Você não colocou o colchete pra fechar a array "routes", talvez seja isso.

**Comment by derrickmehaffy** [comment]
@hectorgrecco can you please use english to make sure everyone understand correctly?

**Comment by hectorgrecco** [comment]
@derrickmehaffy Ok! 
I wrote: "You do not have closed. Maybe, it's that"

**Comment by lauriejim** [comment]
if `/arquivo/latest` is after `/arquivo/:_id`, `/arquivo/:_id` will match with you custom route. `_id` will be `latest` and `latest` is not a correct id value.

If you set your custom route before, strapi will match your custom route before `/arquivo/:_id`.

**Comment by sachinshah114** [comment]
I have the same issue. I tried to change the order of the API but not works for me. Can anyone share the proper solution?

**Comment by lauriejim** [comment]
Can you share your `routes.json` file content please.

**Comment by Shuky** [comment]
Was there a solution for this? I have a similar issue, only with the default generated code for collection's controllers.
https://github.com/strapi/strapi/issues/5528

**Comment by lazurey** [comment]
Stuck in the same behaviour problem yesterday, remove & reinstall `node_modules` didn't help, my controller just kept return `404`.

Finally found the issue, it's because my `try/catch` code, it intends to throw an error and then catch & `ctx.throw`, but somehow strapi caught the error before my code, and return `404`.

In short, if nothing above works for you, try to remove all code in the controller and simply return "ok" to see if `404` is gone. If this is the case, then check if there's any error not handled properly in your original code.

**Comment by philval** [comment]
just saying, I had a 404 error doing the "Hello World" example from https://strapi.io/documentation/v3.x/concepts/controllers.html#custom-controllers
then I *restarted the server*, and got a response.

**Comment by derrickmehaffy** [comment]
> just saying, I had a 404 error doing the "Hello World" example from https://strapi.io/documentation/v3.x/concepts/controllers.html#custom-controllers
> then I _restarted the server_, and got a response on the endpoint

This is normal with Node.js as it can't see the changes until the server restarts

**Comment by TheMangoTrain** [comment]
Make sure the controller has a `return`.

Not having a simple return (anything, like "success") was the reason why I was getting 404 on a new route and controller.

**Comment by TheMangoTrain** [comment]
Ultimately, the reason I got the error:
The return in a controller needs to be an object. I lazily made it a string, and that caused the same error as OP.

Inside the controller...
**FAILS:**
`return "hello world"`

**WORKS:**
`return {"message":"hello world"}`

**Comment by ionutpopa** [comment]
It works if you just return something at the end of the controller, for example:
`return "ok"` <- that worked for me

**Comment by felixrolando** [comment]
I had the same issue and i resolved return context send like this:

export default {
  async products(ctx) {
    try {
    
      return ctx.send({
       
        message: "Products related",
      });
    } catch (error) {}
  },
};
