### ISSUE TITLE
Unable to add Component that contains a component

### ISSUE THREAD

**Issue by hoggworks** [strapi/strapi#15238]
Hi!

I'm working on a Strapi project and have come up against either a bug or a limitation of the system: If we create a Component that contains a component within it, we seem to lose the ability to add it to other components. 

For example, if we had a component called CTA, with this structure:
CTA
  - title
  - description

And a second component called CTA Wrapper, we could add that component as a field. 

However, if we were to add a component inside CTA so it was like this:

CTA
  - title
  - description
  - CTAInsideComponent
    - field1

We wouldn't be able to see it as an option to add to CTA Wrapper anymore. Is this a known limitation, or a bug? If it's a known limitation, what might be a workaround for it?

Thanks!

**Comment by toxicity1985** [comment]
Hello,

You can add it manually inside the corresponding json file related to the component type.

**Comment by hoggworks** [comment]
Is that the only workaround? No way to add it in the front end?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bolg55** [comment]
This is by design, as the front end can get unruly with nested components. As @toxicity1985 mentioned, you can add it inside the json file.
