### ISSUE TITLE
Updating Content Type name does not update database, it adds a new field

### ISSUE THREAD

**Issue by leoalves** [strapi/strapi#1523]
**Informations**
- **Node.js version**:
v.10.6.0
- **npm version**:
v6.1.0
- **Strapi version**:
v 3.0.0-alpha.12.6
- **Database**:
Mongo 3.6

- **Operating system**:
Ubuntu 16.04

**What is the current behavior?**
When updating a Content-Type name, Strapi adds a new field into the database instead of renaming it in the database. I tested with a relation and string type.

**Steps to reproduce the problem**
Create a string Content-Type name it names, add a value. Rename the Content-Type to name.  The new name field will be empty.  In the database collection there will be two fields one named names with the value and another one named name that is empty. 

**What is the expected behavior?**
Database field should be renamed, when editing a content-type name.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1114
