### ISSUE TITLE
GTID consistency issue

### ISSUE THREAD

**Issue by skovacic3** [strapi/strapi#15246]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 4.5.4
- Database: MYSQL 5.7
- Operating system: Alpine Linux 3.13

### Describe the bug

After upgrading from v4.1.7 to v4.5.4 saving any change in the content manager throws an internal server error. We also tried v4.5.3, the same issue happens.

Here are the logs:

`[2022-12-22 11:52:40.732] [31merror[39m: DROP TEMPORARY TABLE IF EXISTS tempOrderTableName_1671709960725 - ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION: Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.`

`Error: ER_GTID_UNSAFE_CREATE_SELECT: Statement violates GTID consistency: CREATE TABLE ... SELECT.
    at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)`

It seems to be an issue with GTID consistency.

Turning `@@GLOBAL.GTID_MODE` to OFF fixes this issue. However we don't want to change this because it causes problems on our high availability setup.

Edit: issue seems to be related to the `cleanOrderColumnsForInnoDB` function

https://github.com/strapi/strapi/blob/v4.5.4/packages/core/database/lib/entity-manager/regular-relations.js#L272

### Steps to reproduce the behavior

1. Go to content manager in admin
2. Change a field to something new
3. Click save

### Expected behavior

Saving should work normally.

**Comment by bolg55** [comment]
Would you be able to outline the steps you took to upgrade from 4.1.7 -> 4.5.4?

**Comment by skovacic3** [comment]
I've followed the migration guides on the website on the versions that required it. For other versions I just updated the package.json and ran yarn install and build.

Some notes: 
- none of our files had MIME set to null, so I skipped the database migration script when going 4.1.8 to 4.1.10
- we do not use SQLite, so I skipped all the steps related to SQLite

**Comment by tholden92** [comment]
I have the same issue when going from 4.5.1 to 4.5.5

Reverting back to 4.5.1 resolves the issue.

**Comment by alucav** [comment]
i solved this by switching from MySQL to postGres. Not ideal for everyone but it is a solution.
