### ISSUE TITLE
UID field is always localized

### ISSUE THREAD

**Issue by StructuralRealist** [strapi/strapi#15248]
### Required System information

- Node.js version: 18.9.1
- NPM version: 8.19.1
- Strapi version: 4.5.4
- Database: Postgresql 14
- Operating system: Linux

### Describe the bug

The UID field is always localized. This does not always make sense. A unique ID might need to point to a unique resource where the localization is irrelevant.

For example, you might use the UID field to create a slug for a page. Some websites localize their URLs (e.g. `/about` and `/over`) but another common pattern is to prefix the path and use the same slug (i.e. `/about` and `/nl/about`).

Another issue arises when the localized fields are the same (e.g. `/book-reviews/harry-potter`) where you would get `/book-reviews/harry-potter` and `/book-reviews/harry-potter-1`.

Please consider making the UID field localization setting customizable. 

### Steps to reproduce the behavior

1. Add a new collection content type
2. Enable Localization
3. Add a UID field
4. Try to set the field to the same value for all locales

### Expected behavior

I would expect the UID field to be the same for all locales of a content entry.

**Comment by bolg55** [comment]
Not sure if this is a bug or more of a discussion for improvement?

**Comment by StructuralRealist** [comment]
I would say it's a bug as it is currently impossible to create a unique identifying field for translatable content.

**Comment by rktyt** [comment]
https://github.com/strapi/strapi/issues/12538

This seems to be the current specification, but in general it is a "specification bug".
I think similar discussions have been going on since v3.

I have already given up on this being addressed.

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/uid-field-is-always-localized
