### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_supported_np

### ISSUE THREAD

**Issue by arixwap** [strapi/strapi#15240]
### Required System information

- Node.js version: **16.15.0**
- NPM version: **8.5.5**
- Strapi version: **4.5.4**
- Database: **SQLite**
- Operating system: **Mac Os 10.13.6 (High Sierra)**

### Describe the bug

When run **yarn develop** command, I got this error
```
yarn run v1.22.18
$ strapi develop
dyld: lazy symbol binding failed: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: /Users/imacone/www/kesato-strapi-backend/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _pthread_jit_write_protect_supported_np
  Referenced from: /Users/imacone/www/kesato-strapi-backend/node_modules/sharp/build/Release/../.././vendor/8.13.3/darwin-x64/lib/libvips-cpp.42.dylib
  Expected in: /usr/lib/libSystem.B.dylib

✨  Done in 7.36s.
```
I think its because package **sharp v0.31.2**. Its doesn't support with **MacOs** below **10.15.7**

You can find the same issue from sharp itself here: https://github.com/lovell/sharp/issues/3438

### Steps to reproduce the behavior

1. It's happened when you are old MacOs version user.
2. Make sure Mac Os version is **10.15.7**, or below
3. Install strapi like usually. `yarn && yarn develop`
4. You will find the error later

### Expected behavior

I'm sure its because package **sharp v0.31.2**.

It is possible to downgrade sharp version? Before its was work when I install Strapi v4.5.3

### Screenshots

![Screen Shot 2022-12-22 at 10 48 08](https://user-images.githubusercontent.com/11769214/209044598-993b02ce-0bbf-4853-855e-d6d621f5f69d.png)

**Comment by bolg55** [comment]
Our minimum supported MacOS is 10.15 but we recommend running 11 or newer, as per our docs: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment.html

**Comment by arixwap** [comment]
WKWK
