### ISSUE TITLE
Empty results when using an "equal" filter on a numeric string

### ISSUE THREAD

**Issue by techguydave** [strapi/strapi#1524]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: MongoDB
- **Operating system**: Alpine Linux

**What is the current behavior?**
When running an "equal" filter on a string field whose value is completely numeric, the result is an empty array, regardless of whether it's GraphQL or REST. When using "_contains", however, the relevant item(s) will be return. If the field's value is changed to include a single alphabetical character, the "equal" filter works as expected.

**Steps to reproduce the problem**

1. On a content type (Ex: `article`), create a `String` field (`shortId`)
2. Add a new item for that type, filling in the field with just numbers (`shortId` = `01234`) and save it
3. Visit the REST URL (`http://localhost:1337/article?shortId=01234`)
4. Try a query in GraphQL Playground
```graphql
query GetArticle {
  singleArticle: articles(where: {shortId: "01234"}) {
    shortId
    _id
  }
}
```
5. Repeat steps 3-4 adding `_contains` (`shortId_contains`)

**What is the expected behavior?**
A string field that's populated with only numbers should be returned when using the "equal" filter on a query.

**Suggested solutions**
None

**Comment by lauriejim** [comment]
Hello @synth3tk , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by synth3tk** [comment]
It looks like cd53ef5ddf93ce543721fb688aeb929211d20486 is the offending party. I should have a PR submitted sometime today that will bypass this check if the field type is a string.

**Comment by lauriejim** [comment]
thank you for your PR I will take a look.
