### ISSUE TITLE
strapi export import error: unknown command 'export'

### ISSUE THREAD

**Issue by thenaazimkhan** [strapi/strapi#15251]
I build all content types locally with MySQL database and deployed my strapi admin panel to the ubuntu production server with pm2. everything is working fine but the problem locally build data is not there so I go to the documentation and find the data management system.

[Data Management System](https://docs.strapi.io/developer-docs/latest/developer-resources/data-management.html#export-data-using-the-cli-tool)

in this docs, there are two CLI commands.

1 strapi export
2 strapi import

when I try to do the same as in docs, I am getting the error:
strapi export
error: unknown command 'export'

so my issue is to get all data from the local database to my production database. is there anyway,
I don't want to build all data again on the production server.

strapi version 4.5.1
node version 16.18.0

**Comment by derrickmehaffy** [comment]
Hello, the DEITS feature is only available in our beta (v4.6.0-beta.1), see this forum post: https://forum.strapi.io/t/data-import-export/24443
