### ISSUE TITLE
Required content can be saved empty on version 4.5.4

### ISSUE THREAD

**Issue by douglaschalegre** [strapi/strapi#15256]
### Required System information

- Node.js version: v14.19.1
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: mysql 8
- Operating system: windows 10

### Describe the bug

On version 4.5.4 you can save empty fields even if they are with "required": true on schema.json

### Steps to reproduce the behavior

1. Add the field as "required": true on Collection Type schema.json
2. Go to Content Manager
3. Click on the Collection Type you created the field
4. Create a new entry and leave a required field empty
5. It will save without errors 

### Expected behavior

On strapi version 4.4.7 trying to save a empty field with required true resulted in error and the user could not save

**Comment by nathan-pichon** [comment]
Hello @douglaschalegre 
Thanks for sharing your issue with us.

Did your server restart after changing the schema.json file?

**Comment by bolg55** [comment]
I was able to replicate this - it happens if:

1. You are already in the content manager when updating the schema.json. 

This is because the server does not restart. Navigating away, or refreshing the page will update the content type field to have the `required` flag.

**Comment by derrickmehaffy** [comment]
FYI when Draft & Published is enabled on the content-type this is INTENDED. Going to lower this to low since the actual way to hit this bug is extremely rare. If you want required to always be enforced then you will have to turn off D&P

**Comment by Marc-Roig** [comment]
Changing the schema.json fields does require the website to be refreshed, I would not consider this a bug and not related to D&P.
Closing for now, we can reopen again if the issue is caused by another matter.

**Comment by douglaschalegre** [comment]
Hey guys!

I've started a new project from scratch with only two collections-types, news (with D&P) and authors (no D&P). And did the following:

1. Adding one to many relationship between news and authors (news has many authors).
2. Adding on news schema.json the required: true on authors relation.
3. Stopped the server.
4. Deleted .cache and build folders.
5. Executed npm run develop.

All the steps above resulted on the same unwanted behavior. I can save a news with no authors even it being true on schema.json and the frontend showing a * on the field

I'm using the newest version (v4.5.6) since it was released with a critical security fix. 
Node.js version: v16.19.0
NPM version: 8.19.2
MySQL 8

Screenshots:

![published-without-author](https://user-images.githubusercontent.com/19676959/212994850-8a059cd7-8442-4d17-8674-236160b46113.png)
![schema-news](https://user-images.githubusercontent.com/19676959/212994890-5c104205-c7fd-4408-befc-96f91eeb9caa.png)
![schema-authors](https://user-images.githubusercontent.com/19676959/212994926-9018676a-88fe-4e1c-9e6b-42a72ef6dd30.png)
![field-shows-star](https://user-images.githubusercontent.com/19676959/212995136-36822f7e-6974-4b43-a750-943cd767799d.jpg)

**Comment by douglaschalegre** [comment]
I also found other users experiencing this:
https://feedback.strapi.io/customization/p/specify-relation-column-as-required

**Comment by Marc-Roig** [comment]
Adding a required relation field was something that was working but not supported by Strapi.

Since 4.5.0 we changed the way we work with relations on the Content Manager, and soon we plan to work on making a relation field required. 

For now there is no good solution for this until we develop the feature.
