### ISSUE TITLE
Duplicating users with same emails

### ISSUE THREAD

**Issue by VladislavDolgolenko** [strapi/strapi#15257]
https://github.com/strapi/strapi/blob/05be5849a7e12707af02e4351bc94edca35d89f4/packages/plugins/users-permissions/server/services/providers.js#L81

Resolve:
`if (users.length > 0 && advancedSettings.unique_email) { `

How to check issue:
1. Registration via local provider (email and password).
2. Registration via facebook login or other (account with same email).

As a result, we will get two user accounts with the same email.

**Comment by VladislavDolgolenko** [comment]
I did understand something. A user can only have one provider to singing into their account. Different provider - different user account.

**Comment by bolg55** [comment]
closing as this isn't a bug, as you've mentioned in your follow up

**Comment by VladislavDolgolenko** [comment]
> closing as this isn't a bug, as you've mentioned in your follow up

All in all, the behavior does not match the expectation according to logic. You can create two user accounts with the same email, but no more than two, according to the code:

https://github.com/strapi/strapi/blob/05be5849a7e12707af02e4351bc94edca35d89f4/packages/plugins/users-permissions/server/services/providers.js#L81

How to check issue:
1. Create an account via Facebook
2. Create an account via Google or other provider with same email.
3. Create an account via other provider with same email -> error 'Email is already taken.'

As a result, we will get two user accounts with the same email.

**Comment by dineshkumar-adk** [comment]
Yes we are getting two user accounts, with the same email...then how to restrict user from signin with google, if they already signed up with the same email.
