### ISSUE TITLE
How to specify upload-file field's directory?

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1525]
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongoDB
- **Operating system**: macOS

**What is the current behavior?**
I have two fields which both are upload-file fields, and I am using aws s3 as provider.
I want to upload files to the same bucket but different directory.
How can I do that?

**Comment by lauriejim** [comment]
Hello @yummyelin , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by lauriejim** [comment]
You will have to custom the plugin upload and aws provider config to handle bucket.

**Comment by yummyelin** [comment]
If custom the aws provider config, it gives the same directory path for all upload-file fields.

I have a temporary solution, which is using field name as directory path. 

The contributing guide link is expired, so I leave my modification here:
https://github.com/strapi/strapi/blob/master/packages/strapi-upload-aws-s3/lib/index.js#L74
```
          S3.upload({
            Key: `${file.path}/${file.hash}${file.ext}`, // add ${file.path}/
            Body: new Buffer(file.buffer, 'binary'),
            ACL: 'public-read'
          }
```
https://github.com/strapi/strapi/blob/master/packages/strapi-upload-aws-s3/lib/index.js#L95
```
            Delete: {
              Objects: [{
                Key: `${file.path}/${file.hash}${file.ext}` // add ${file.path}/
              }]
            }
```
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/controllers/Upload.js#L44
```
        Object.assign(file, {
          path: `${ref}/${field}`, // add this line
          related: [{
            refId,
            ref,
            source,
            field
          }]
        });
```

Please review and feel free to modify.

**Comment by lauriejim** [comment]
Can you provide a PR with your update please. It will be easier for me to test.
