### ISSUE TITLE
strapi.server.listRoutes() returns all routes 2 times

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#15267]
## Bug report
strapi.server.listRoutes() returns all routes 2 times
### Required System information

- Node.js version: v18.9.1
- NPM version: 8.19.1
- Strapi version: 4.5.4
- Database: sqlite
- Operating system: Windows 10

### Describe the bug

strapi.server.listRoutes() returns all routes 2 times

### Steps to reproduce the behavior

1. create custom route with a controller that returns `strapi.server.listRoutes()`
2. go to the endpoint you just created
3. search for what ever endpoint you want I recommend `/api/users/me`
4. See error (It exists 2 times)

### Expected behavior

To return all routes 1 time not every route 2 times

**Comment by derrickmehaffy** [comment]
Source of the issue is here: https://github.com/strapi/strapi/blob/44c3c09438fda172a1f94f85958a2085686f1cda/packages/core/strapi/lib/services/server/index.js#L107-L115

**Comment by sobhardwaj** [comment]
> 

will it be fix in next minor version ...??

**Comment by sobhardwaj** [comment]
> Source of the issue is here:
> 
> https://github.com/strapi/strapi/blob/44c3c09438fda172a1f94f85958a2085686f1cda/packages/core/strapi/lib/services/server/index.js#L107-L115

will it be fix in next minor version ...??
