### ISSUE TITLE
Issue when selecting permissions on field level

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#15264]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.5.4
- Database: SQLite
- Operating system: MacOS M1 Pro Ventura 13.0

### Describe the bug

Error when selecting the permissions at the field level.

### Steps to reproduce the behavior

https://www.loom.com/share/3eef1ccd67664765beda9b64e0550ae9

**Comment by Marc-Roig** [comment]
Hello :) this is an issue that only happens in the community edition. In future strapi releases this will be fixed so I am closing this issue for now.


If in the future we have problems with this again we will reopen it.
