### ISSUE TITLE
/i18n/locales 404

### ISSUE THREAD

**Issue by Hakiba** [strapi/strapi#15268]
### Required System information

- Node.js version: v16.17.1
- NPM version: 8.15.0
- Strapi version: 4
- Database: mysql
- Operating system: o2switch

### Describe the bug

I'm trying to deploy a strapi app on o2switch using Nodejs (and Mysql) for a Nextjs app.

### Steps to reproduce the behavior

Each time I connect to my admin panel this error appears

### Screenshots

<img width="1439" alt="Capture d’écran 2022-12-26 à 12 32 37" src="https://user-images.githubusercontent.com/41543008/209544784-371977d3-02a7-491c-9694-eca4f3c31f9e.png">

And just before log in

<img width="1438" alt="Capture d’écran 2022-12-26 à 12 54 02" src="https://user-images.githubusercontent.com/41543008/209546115-29c4aab0-9202-4726-a692-d6143ded914e.png">

### Code snippets
.env :
```
APP_HOST=127.0.0.1
PORT=1338
```

./config/server.js:
```javascript
module.exports = ({ env }) => ({   host: env('APP_HOST', '0.0.0.0'),   port: env.int('PORT', 1337),   app: {     keys: env.array('APP_KEYS'),   }, });
```

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
