### ISSUE TITLE
Publish without validation for boolean field(required) without default value

### ISSUE THREAD

**Issue by foreachone** [strapi/strapi#15270]
### Required System information

- Node.js version: 16.18.0
- NPM version: 8.19.2
- Strapi version: 4.5.4/4.4.7
- Database:
- Operating system: mac os 

### Describe the bug

Require boolean field is not validated in collection type.

### Steps to reproduce the behavior

1. Create single component with required boolean filed
2. Create a collection type reference with this component
3. Publish this collection type without add this component entry
4. Add this component entry in this collection type without select any boolean value
5. Error: this collect type can save without validation
6. I select value and save publish version, then I delete this entry and new an entry without selecting value, validation also not work 

### Expected behavior

Boolean validation can work for required data field

### Screenshots
<img width="1489" alt="Screenshot 2022-12-27 at 11 23 57" src="https://user-images.githubusercontent.com/33291657/209606369-d7db4d48-8d68-411b-bc6f-675c698b0364.png">

**Comment by foreachone** [comment]
Also for strapi version 4.4.7

**Comment by ronronscelestes** [comment]
I was able to reproduce this issue on 4.5.4

https://user-images.githubusercontent.com/71838159/209655575-d7b2d3d3-47f7-4d55-b473-b07da929e97b.mov

**Comment by ronronscelestes** [comment]
good catch @foreachone - thank you for highlighting this issue!
I'll open a PR to fix this :)
