### ISSUE TITLE
401 for admin/telemetry-properties after upgrade to 4.5.4

### ISSUE THREAD

**Issue by arashkevich25** [strapi/strapi#15271]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.5.4
- Database: postgress
- Operating system: MAC OS

### Describe the bug

After upgrading strapi to version 4.5.4 can't run the application due 401 (/admin/telemetry-properties) error 

### Steps to reproduce the behavior

1. change version in package.json from version 4.4.3 to 4.5.4
2. remove node_modules and yarn.lock
3. install packages
4. yarn develop
5. See error

### Expected behavior

Should works properly

### Screenshots

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/15210655/209642933-364c50df-248f-44c6-b5d5-be86a8d38db5.png">

<img width="621" alt="image" src="https://user-images.githubusercontent.com/15210655/209642968-645c0099-e873-423a-8b83-66f7618cab53.png">

### Code snippets

```json
    "@strapi/plugin-graphql": "4.5.4",
    "@strapi/plugin-i18n": "4.5.4",
    "@strapi/plugin-sentry": "4.5.4",
    "@strapi/plugin-users-permissions": "4.5.4",
    "@strapi/provider-email-amazon-ses": "4.5.4",
    "@strapi/provider-upload-aws-s3": "4.5.4",
    "@strapi/strapi": "4.5.4",
```

**Comment by Convly** [comment]
Hey, thanks for reporting this issue.

Did you try removing your `.cache` & `build` directories from your application folder (so that it forces a new admin clean build)?

**Comment by arashkevich25** [comment]
Thanks for the answer, but unfortunately still the same issue.

**Comment by Convly** [comment]
What if you manually run `yarn build` in your project?
If it's still not working, then it might be something deeper :thinking:

**Comment by arashkevich25** [comment]
ok, resolved, i had issue with permissions and removing .cache folder. Thank you for help

**Comment by Convly** [comment]
Glad I was able to help, have a nice day!
