### ISSUE TITLE
Selecting video media does not work in content manager

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#15275]
### Required System information

- Node.js version: v18.9.1
- NPM version: 8.19.1
- Strapi version: 4.5.4
- Database: sqlite
- Operating system: Windows 10

### Describe the bug

upload plugin does not allow you to select video's in the content editor in its place you are send to the edit page

### Steps to reproduce the behavior

1. Create content with media with video enabled
2. Upload video to media in wmv format
3. Go to content manager 
4. create new entry with media field
5. Click on `click to add an asset`
6 Try and click the checkmark to add the media you
7 It does not check and opens edit menu
### Expected behavior

To check the checkmark so that I can select video media

### Screenshots

![Alt Text](https://i.gyazo.com/34cafc7dea65648d7326d2a2b8cc72a7.gif)

### Code snippets

Temp patch with patch-package to solve the issue
```patch
diff --git a/node_modules/@strapi/plugin-upload/admin/src/components/AssetCard/AssetCardBase.js b/node_modules/@strapi/plugin-upload/admin/src/components/AssetCard/AssetCardBase.js
index 1ab68aa..1c89049 100644
--- a/node_modules/@strapi/plugin-upload/admin/src/components/AssetCard/AssetCardBase.js
+++ b/node_modules/@strapi/plugin-upload/admin/src/components/AssetCard/AssetCardBase.js
@@ -79,7 +79,7 @@ export const AssetCardBase = ({
       <CardHeader>
         {onSelect && (
           // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions
-          <div onClick={handlePropagationClick}>
+          <div style={{zIndex: 1}} onClick={handlePropagationClick}>
             <CardCheckbox value={selected} onValueChange={onSelect} />
           </div>
         )}
```

### Additional context

Reported by yasir129 in Discord

**Comment by paddotk** [comment]
#15041 is closed but can still be used for reference. I also put a (late) response there with some additional info:
> I tried both uploading directly in the Media Library as well as in the Content Manager (add asset > 'Add more assets' > select video), and when deleting and re-uploading it doesn't work either.
This happens on different videos (though I think I only tried with .mp4).
