### ISSUE TITLE
Use pnpm to create strap-app but the guide shows yarn mistakenly 

### ISSUE THREAD

**Issue by xJkit** [strapi/strapi#15276]
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: sqlite 
- Operating system:  macOS 12.4 (Apple Silicon M1)

### Describe the bug

I use the following command to bootstrap the strapi app but the cli indicates the yarn command instead.

```sh
pnpm create strapi-app

? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at ~/
Creating files.
Dependencies installed successfully.

Your application was created at ~/

Available commands in your project:

  yarn develop
  Start Strapi in watch mode. (Changes in Strapi project files will trigger a server restart)

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/jaychung/Documents/Workspace/commercial/v2-j-murmur-official/j-murmur-admin
  yarn develop

Running your Strapi application.

> j-murmur-admin@0.1.0 develop
> strapi develop
```

### Steps to reproduce the behavior

Run `pnpm create strapi-app` and the cli gives an indication for yarn. 
Also, the project generates a default `yarn.lock` file for you.

### Expected behavior

Give a guide for `pnpm` instead of `yarn`, and generate a `pnpm-lock.yaml` file rather than `yarn.lock`.

### Code snippets

```
pnpm create strapi-app
```

**Comment by derrickmehaffy** [comment]
Strapi will automatically detect when yarn is installed, usually you can force usage of npm with the npm flag but for the moment we do not support pnpm

The npm flag would be `--use-npm` from: https://docs.strapi.io/developer-docs/latest/developer-resources/cli/CLI.html#strapi-new

To support pnpm please create a feature request on https://feedback.strapi.io
