### ISSUE TITLE
custom fields  broken in v4.5.4

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#15273]
### Required System information

- Node.js version: 18.10.0
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: sqlite
- Operating system: MacOS

### Describe the bug

It worked in 4.5.3 but stopped working in 4.5.4.
I have multiple custom fields registered with one plugin.

### Steps to reproduce the behavior

```
Collection 'A'
  - customField 'A' (type string)
Collectioln 'B'
 - customField 'B' (type richtext)
 - customFiled 'C' (type json)
```

Given the above configuration, if you go back and forth between the entry screen for collection 'A' and the entry screen for collection 'B', you will only see the custom fields in one collection.
Reload your browser and it will be displayed.

### Expected behavior

Same behavior as 4.5.3.

### Screenshots

https://user-images.githubusercontent.com/26789317/209652396-65421f21-9849-4a83-9ea9-65c10f3253ab.mov

**Comment by rktyt** [comment]
Updates

```
Collection 'A'
  - customField 'A' (type string)
  - customField 'B' (type richtext)
Collectioln 'B'
 - customField 'B' (type richtext)
 - customFiled 'C' (type json)
```

In the above case customField 'B' is displayed.

----

https://github.com/strapi/strapi/blob/v4.5.4/packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js#L15

`componentStore.size === 0` is usually valid only at the time of initial loading.
So the following if statement will be false and the new one will not be loaded.
Because `loading` is basically still false.

https://github.com/strapi/strapi/blob/v4.5.4/packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js#L39

```diff
39c39
<     if (componentUids.length && loading) {
---
>     if (componentUids.length) {
```

The above changes will allow it to function properly, but we have not checked other parts of the system, so we do not know if this is the right thing to do.

**Comment by derrickmehaffy** [comment]
Could you provide a sample plugin for us to test with that you reproduced the issue on?

**Comment by rktyt** [comment]
@derrickmehaffy 

Below is a sample plugin to reproduce the problem.

`package.json`:
```json
{
  "name": "test",
  "strapi": {
    "name": "test",
    "displayName": "test plugin",
    "description": "test plugin",
    "kind": "plugin"
  }
}
```

`strapi-admin.js`:
```javascript
"use strict";

const pluginId = "test";
const customFields = [
  { type: "richtext" },
  { type: "string" },
  { type: "json" },
];

module.exports = {
  register(app) {
    customFields.forEach((field, i) => {
      const fieldName = `test${i + 1}`;
      app.customFields.register({
        ...field,
        pluginId,
        name: fieldName,
        intlLabel: {
          id: `${fieldName}.label`,
          defaultMessage: `${fieldName} label`,
        },
        intlDescription: {
          id: `${fieldName}.desc`,
          defaultMessage: `${fieldName} desc`,
        },
        components: {
          Input: async () => ({
            default() {
              const React = require("react");
              return React.createElement("div", null, fieldName);
            },
          }),
        },
      });
    });
  },
};
```

`strapi-server.js`:
```javascript
"use strict";

const plugin = "test";
const customFields = [
  { type: "richtext" },
  { type: "string" },
  { type: "json" },
];

module.exports = {
  register({ strapi }) {
    customFields.forEach((field, i) => {
      const fieldName = `test${i + 1}`;
      strapi.customFields.register({
        ...field,
        plugin,
        name: fieldName,
      });
    });
  },
};
```

Save to `src/plugins/test`.

**Comment by magnus-bb** [comment]
I have (what I think is) the same issue when multiple custom fields are installed (noticed on 4.5.5 and 4.5.6).

I have a custom date picker as well as the CKeditor custom field installed, and only one of them at any time will show 'Not supported'. If I go to the content manager of a collection with a custom field that shows 'Not supported' and refreshes, it will load the field correctly, but then navigating to the content manager of a collection with the other custom field will cause that field to display 'Not supported'.

When looking at React devtools, I see that Strapi seems to only try to use the first custom field component that is loaded (I am not a React developer myself). In the screenshot you can see the React devtools open while having the CKeditor selected, but it incorrectly tries to use our date picker:
![image](https://user-images.githubusercontent.com/51884390/214797377-adf335bd-1e8e-402e-b7bb-f13908dbf652.png)

**Comment by orlando1108** [comment]
Hi, after few hours trying to get my custom field working correctly, i came to this issue and i think that's also my issue.
i use 2 external plugins, multi-select and config-sync.
When i setup everything for my custom plugin generated by the cli, i notice the 2 external plugins stop working and desapear from the UI. 
except if i remove this part of my custom plugin :
![image](https://user-images.githubusercontent.com/22614778/214975202-424a474b-52d4-4188-97d9-ba1af89c3e19.png)
  
  So only this part of the config breaks the app.
  The favicon also desapears !!!

**Comment by GregorSondermeier** [comment]
we're currently on v4.4.7 but need to upgrade soon to at least v4.5.6 because of the security issue. we have multiple custom fields in the project.

**Comment by Torsten85** [comment]
this is my current working (but very ugly) workaround:
 
<details>
  <summary>src/admin/useLazyComponentFixed.js</summary>

  ```js
import { useCustomFields } from '@strapi/helper-plugin'
import { useMemo, useCallback, useEffect, useState } from 'react'

const componentStore = new Map()

export default function useLazyComponents(componentUids = []) {
  const [lazyComponentStore, setLazyComponentStore] = useState(Object.fromEntries(componentStore))
  const newUids = useMemo(() => componentUids.filter(uid => !componentStore.get(uid)), [componentUids])
  const [loading, setLoading] = useState(newUids.length > 0)
  const customFieldsRegistry = useCustomFields()

  useEffect(() => {
    const setStore = store => {
      setLazyComponentStore(store)
      setLoading(false)
    }

    const lazyLoadComponents = async (uids, components) => {
      const modules = await Promise.all(components)

      uids.forEach((uid, index) => {
        componentStore.set(uid, modules[index].default)
      })

      setStore(Object.fromEntries(componentStore))
    }

    const componentPromises = newUids.map(uid => {
      const customField = customFieldsRegistry.get(uid)

      return customField.components.Input()
    })

    if (componentPromises.length > 0) {
      lazyLoadComponents(newUids, componentPromises)
    }
  }, [newUids, customFieldsRegistry])

  const cleanup = useCallback(() => {
    componentStore.clear()
    setLazyComponentStore({})
  }, [])

  return { isLazyLoading: loading, lazyComponentStore, cleanup }
}

  ```
</details>

<details>
  <summary>src/admin/webpack.config.js</summary>

```js
module.exports = (config, webpack) => {
  config.plugins.push(
    new webpack.NormalModuleReplacementPlugin(/useLazyComponents/, require.resolve('./useLazyComponentFixed.js'))
  )
  return config
}
```
</details>

**Comment by joshuaellis** [comment]
> we're currently on v4.4.7 but need to upgrade soon to at least v4.5.6 because of the security issue. we have multiple custom fields in the project. this bug report is worrying.

As you can see, there is a PR in review at the moment to resolve this issue.

**Comment by GregorSondermeier** [comment]
> As you can see, there is a PR in review at the moment to resolve this issue.

Cool, thx
