### ISSUE TITLE
Migration from v4.4.5 to v4.5.1 - Unique Relation Index name too long

### ISSUE THREAD

**Issue by sunnysonx** [strapi/strapi#15285]
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 4.5.1
- Database: MySQL v5.7.33
- Operating system: Windows11 with WSL2 (Ubuntu 20.04)

### Describe the bug

In v4.5.1 there have been introduced unique indexes on relationships. While trying to upgrade strapi from v4.4.5 to v4.5.1 it produces an error related to index name being too long.

```
alter table `components_sections_homepage_platforms_mobile_apps_links` add index `components_sections_homepage_platforms_mobile_apps_links_order_fk`(`mobile_app_order`)
```
The components_sections_homepage_platforms_mobile_apps_links_order_fk name is too long, so it can't create the index.

### Steps to reproduce the behavior

1. Create a relation with a component with a longer name and it add it to a dynamic zone.
2. Upgrade strapi to v4.5.1 (where unique indexes were introduced)
3. Start Strapi and it will fail because the indexes can't be created with such a long name.

### Expected behavior

The indexes to be created properly.

### Screenshots

<img width="445" alt="image" src="https://user-images.githubusercontent.com/14160283/209840322-ea841e3e-64b3-423f-bd96-df20b21a1bcd.png">

### Possible solution
Change the index name pattern in order to generate a smaller name (which does not include the full name of the current table). At least for components, it can exclude the "components" word and also it may exclude the DZ name (in my case, "sections"). So it will generate a name like `homepage_platforms_mobile_apps_links_order_fk`

**Comment by derrickmehaffy** [comment]
Closing to merge in https://github.com/strapi/strapi/issues/13117

The only currently known workaround is to modify your content-type schemas to change their collection names and build a small [DB migration script](https://docs.strapi.io/developer-docs/latest/developer-resources/database-migrations.html) to not lose your data
