### ISSUE TITLE
Strapi Admin can't be iframe'd (with partial solution)

### ISSUE THREAD

**Issue by JonKrone** [strapi/strapi#15297]
## Bug report

Even with proper content security policy (CSP) headers that allow Strapi to be iframed in a different domain, Strapi Admin crashes when iframed because it uses browser storage APIs (`localStorage`, `sessionStorage`) that aren't available within an iframe.

A fix we found for this is to make a simple wrapper around the storage APIs that uses a fallback storage solution such as memory storage when browser storage is not available. This prevents Strapi from crashing when iframed so that it's usable. In the Our Fix section below I've added all the code changes we made to make this work.

Unfortunately, a simple in-memory fallback does not fully replicate the browser storage behavior because, obviously, browser storage persists between refreshes/etc while in-memory data is reset. For our needs, it has worked well enough because localStorage is used sparingly in Strapi Admin to begin with. More comprehensive support from the Strapi team would likely mean bringing some of the data tracked by localStorage to the database.

I consider this a bug and feature request and informational to other users, so I wasn't sure where to put it (forums/discord/issues).

### Required System information

- Node.js version: lts/fermium
- NPM version: yarn 3.3.1
- Strapi version: 4.3.9
- Database: postgres
- Operating system: 

### Describe the bug

When the CSP headers are changed in the "strapi::security" plugin that should allow Strapi to be iframed into an application on another domain, Strapi crashes when loaded.

Strapi Admin crashes because it tries to use `localStorage` and `sessionStorage` APIs which are not available when the document is running in an iframe.

### Steps to reproduce the behavior

To reproduce, you need to add some lenient CSP headers via `strapi::security` plugin configuration (see below). Then simply try to embed the Strapi Admin in an iframe on another domain: `<iframe src="https://your-strapi-url.com/admin" />`

<details>
<summary>Sample middlewares.ts</summary>

```ts
export default [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: {
          "frame-ancestors": [
            "'self'",
            "'http:'",
            "'https:'",
          ],
        },
      },
    },
  },
  ...,
]
```
</details>

### Expected behavior

I would expect Strapi to be loaded in the iframe and function as normal.

### Screenshots

<details>
<summary>A screenshot of Strapi working in an iframe in our internal Platform app.</summary>

![image](https://user-images.githubusercontent.com/2660142/210003565-83a1ba46-7eab-43a8-8abe-382ae39d7fc6.png)
</details>

### Additional context

Currently, browser storage APIs are used for:
1. The user's selected language
2. dark/light mode
3. tracking the user's progress through the GuidedTour of Strapi.

The simplest fix for the Strapi team would be to use a storage helper internally that has a fallback to a in-memory storage when browser storage APIs are not available. There are a lot of localStorage wrapper libraries out there you could get inspiration from and would get you 90% of the way there, I think.

# Our Fix

<details>
<summary>1. Update your `strapi::security` middleware to allow embedding in another domain</summary>
Add something like this `frame-ancestors` CSP configuration to the `strapi::security` plugin for the domains you want to enable iframe embedding on.

```ts
// src/config/middlewares.ts
export default [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: {
          "frame-ancestors": [
            "'self'",
            "https://your-app.com"
          ],
        },
      },
    },
  },
  ...,
]
```
</details>

<details>
<summary>2. Create a global wrapper with the same API as browser storage</summary>
Customize your Admin app via the `src/admin/app.ts` file to import the storageWrapper we'll make below.

```ts
// src/admin/app.ts
import "./extensions/storageWrapper";

export default {
  bootstrap() {
    // console.log("bootstrapped");
  },
};
```

Our team doesn't need any of the features enabled by localStorage and they aren't getting in our users' way, so this simple mock works well enough for us. Note the `storageReplaceMe` stuff, which is a webpack hack described in the next section.

```ts
// src/admin/extensions/storageWrapper.ts
const isLocalStorageAvailable = (() => {
  try {
    // This will throw if `localStorage` is not available
    // See `storageReplaceMe` note in webpack.config.js
    (window as any).storageReplaceMe.getItem("STORAGE_TEST");
    return true;
  } catch (e) {
    return false;
  }
})();

/**
 * An in-memory storage implementation.
 *
 * Based on https://github.com/gr2m/localstorage-memory/blob/master/lib/localstorage-memory.js
 */
const createMemoryStorage = () => {
  let cache = {};

  let length = 0;
  const getItem = (key) => {
    if (key in cache) {
      return cache[key];
    }

    return null;
  };

  const setItem = (key, value) => {
    if (typeof value === "undefined") {
      removeItem(key);
    } else {
      if (!cache.hasOwnProperty(key)) {
        length++;
      }

      cache[key] = "" + value;
    }
  };

  const removeItem = (key) => {
    if (cache.hasOwnProperty(key)) {
      delete cache[key];
      length--;
    }
  };

  const key = (index) => {
    return Object.keys(cache)[index] || null;
  };

  const clear = () => {
    cache = {};
    length = 0;
  };

  return {
    length,
    getItem,
    setItem,
    removeItem,
    key,
    clear,
  };
};

const storage = isLocalStorageAvailable
  ? // See `storageReplaceMe` note in webpack.config.js
    (window as any).storageReplaceMe
  : createMemoryStorage();

(window as any).storageWrapper = storage;

export default storage;
```
</details>

<details>
<summary>3. Use webpack to replace existing uses of browser storage with our storage wrapper</summary>

Add this to your `src/admin/webpack.config.js` file. Sorry for the extensive comments.

```ts
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config

  config.plugins.push(
    /**
     * When the Strapi admin panel is loaded in an iframe, it crashes because
     * iframes are not allowed to access localStorage and sessionStorage. In
     * order to enable the Admin panel to run in an iframe, we need to replace
     * the storage implementation with one with a fallback to a compatible
     * storage, i.e. memory storage. Ideally, this would be done in the Strapi
     * library itself but until then we need to in-place patch the admin panel,
     * by:
     *
     * 1. Create a storage wrapper that uses memory storage if browser storage
     *    is not available.
     * 2. Replace all references to browser storage with the storage wrapper.
     *
     * The storage wrapper is implemented in ./extensions/storageWrapper.ts, and
     * mimics the localStorage and sessionStorage APIs. The storage wrapper is
     * imported by src/admin/app.js, adding a `storageWrapper` global variable.
     *
     * To replace all references to the browser storage APIs with
     * `window.storageWrapper`, we use Webpack's DefinePlugin to change the
     * variables when they're bundled. However, the @strapi/admin package comes
     * with pre-built bundle files which already contain references to the
     * native storage APIs. Those bundles are not re-built by default, so we
     * need to force the admin panel to re-build by patching the @strapi/strapi
     * package (file
     * /node_modules/@strapi/strapi/lib/commands/builders/admin.js) to accept an
     * env variable (STRAPI_ADMIN_FORCE_BUILD=true) that forces the admin panel
     * to re-build, and thus to actually apply these DefinePlugin patches.
     */
    new webpack.DefinePlugin({
      localStorage: "window.storageWrapper",
      sessionStorage: "window.storageWrapper",
      "window.localStorage": "window.storageWrapper",
      "window.sessionStorage": "window.storageWrapper",
    }),
    /**
     * To detect whether our app has access to the native storage APIs, we check
     * if we get an error when trying to use the localStorage API. However,
     * because of the above DefinePlugin, all references to localStorage are
     * replaced with `window.storageWrapper`, so to work around the above
     * DefinePlugin, we make up a variable called `storageReplaceMe` that
     * is turned into `localStorage` after bundling. This is a hack, but it works.
     */
    new webpack.DefinePlugin({
      "window.storageReplaceMe": "window.localStorage",
    })
  );

  return config;
};
```

</details>
<details>
<summary>4. Patch the `@strapi/strapi` library to add an ENV var that forces Strapi to re-build its pre-bundled bundle.</summary>

This is the patch we applied.

```diff
diff --git a/lib/commands/builders/admin.js b/lib/commands/builders/admin.js
index aabd4bdda758998adf784588482231e0a6e9b9c6..8e080d3388e2e5d6b4ae37dc67000e18d401bd13 100644
--- a/lib/commands/builders/admin.js
+++ b/lib/commands/builders/admin.js
@@ -38,7 +38,7 @@ module.exports = async ({ buildDestDir, forceBuild = true, optimization, srcDir
       buildDestDir,
       // front end build env is always production for now
       env: 'production',
-      forceBuild,
+      forceBuild: forceBuild || process.env.STRAPI_ADMIN_FORCE_BUILD === 'true',
       plugins,
       optimize: optimization,
       options: {
```
</details>

Then you can run your app with `STRAPI_ADMIN_FORCE_BUILD=true yarn strapi dev` and you'll be able to embed it!

**Comment by derrickmehaffy** [comment]
> More comprehensive support from the Strapi team would likely mean bringing some of the data tracked by localStorage to the database.

This is not possible, as our admin panel uses React and not a SSR frontend such as Next.js. What is stored in local/session is the auth tokens and other data that is used by the frontend. 

For the moment I would not consider this a bug but instead a feature request (I would recommend posting that on https://feedback.strapi.io) but to be honest I don't think there really is a solution to this issue without a local or session storage.
