### ISSUE TITLE
relartionship witout target in plugin::upload.file

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#15298]
- Node.js version: v18.9.1
- NPM version: 8.19.1
- Strapi version: 4.5.4
- Database: sqlite
- Operating system: Windows 10
### Steps to reproduce the behavior

1. Go to /api/content-type-builder/content-types
2. search for related 
3. see that target is null
### Expected behavior

for target not to be null

### Code snippets
https://github.com/strapi/strapi/blob/main/packages/core/upload/server/content-types/file/schema.js#L85-L89

```json
"related": {
   "type": "relation",
   "relation": "morphToMany",
   "configurable": false,
   "targetAttribute": null,
   "private": false
},
```

**Comment by derrickmehaffy** [comment]
This is intentional as it's a polymorphic relation (several content-types can be related to upload without adding a new field) this is specific logic just for the media field and is not a normal relation.
