### ISSUE TITLE
Can't npm install this plugin

### ISSUE THREAD

**Issue by hades200082** [strapi/strapi#15292]
### Required System information

- Node.js version: 18.12.1
- NPM version: 9.1.3
- Strapi version: 4.5.5
- Database: Postgres
- Operating system: Windows

### Describe the bug

Running `npm install` results in error:

```
69 verbose stack TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
69 verbose stack     at open (node:internal/fs/promises:537:10)
69 verbose stack     at writeFile (node:internal/fs/promises:876:20)
69 verbose stack     at Shrinkwrap.save (D:\Program Files\nvm\v18.12.1\node_modules\npm\node_modules\@npmcli\arborist\lib\shrinkwrap.js:1133:7)
69 verbose stack     at [saveLockFile] (D:\Program Files\nvm\v18.12.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1440:17)
69 verbose stack     at [saveIdealTree] (D:\Program Files\nvm\v18.12.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1394:42)
69 verbose stack     at Arborist.reify (D:\Program Files\nvm\v18.12.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:31)
69 verbose stack     at async Install.exec (D:\Program Files\nvm\v18.12.1\node_modules\npm\lib\commands\install.js:146:5)
69 verbose stack     at async module.exports (D:\Program Files\nvm\v18.12.1\node_modules\npm\lib\cli.js:133:5)
70 verbose cwd D:\Projects\Personal\Strapi
71 verbose Windows_NT 10.0.22621
72 verbose node v18.12.1
73 verbose npm  v9.1.3
74 error code ERR_INVALID_ARG_TYPE
75 error The "path" argument must be of type string or an instance of Buffer or URL. Received null
76 verbose exit 1
```

full log file [2022-12-29T12_50_02_176Z-debug-0.log](https://github.com/strapi/strapi/files/10319535/2022-12-29T12_50_02_176Z-debug-0.log)

### Steps to reproduce the behavior

1. Run the command `npm install @strapi/provider-upload-cloudinary` in the Strapi project folder
2. See the error

### Expected behavior

The cloudinary plugin to be installed.

### Screenshots

N/A

### Code snippets

N/A

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
It seems your package-lock.json is having some issues

> 37 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules

Can you try deleting your node_modules folder and the package-lock.json and try again? To be entirely honest this doesn't look like a Strapi issue but an npm one. (I also could not reproduce this on my windows 10 test machine)

**Comment by derrickmehaffy** [comment]
Closed for now until the user responds with more information

**Comment by ha-akelius** [comment]
I had same issue,

I am using npm, 
my issue because I have an empty folder called yarn-lock it causing this issue, 

I solved it by deleting this folder

**Comment by mattg66** [comment]
I also had this issue, @ha-akelius's answer sorted it for me, by removing the yark-lock folder

**Comment by jrencz** [comment]
I also can confirm that removing the folder solves the problem

I checked node `14.21.2` (npm `6.14.17`), `16.19.0` (npm `8.19.3`) and `18.14.0` (npm `9.3.1`) - **the problem didn't occur on 14**.
May it be that npm tries to check something in that folder and because it's an empty folder it fails?

**Comment by umair-me** [comment]
For me too it was the yarn-lock folder, no idea how it got created, I use npm only...

**Comment by frebarcelos** [comment]
You must have done the same as me and copied the docker-compose example, it has a protected yarn volume, when you upload this docker it creates this folder and then generates the error for installing any other package, just delete the folder and eliminate the line " - /yarn.lock:/opt/yarn.lock" and problem solved

**Comment by MaxLikesCode** [comment]
@ha-akelius Lifesaver! Yes, deleting the yarn.lock folder that magically got created somehow fixed the issue.
