### ISSUE TITLE
Delete Image From Bucket 

### ISSUE THREAD

**Issue by imdevpratik** [strapi/strapi#15290]
### Required System information

- Node.js version:18.01
- NPM version:6.14.17
- Strapi version:4.5.2
- Database:Postgres (14.5)
- Operating system:Ubuntu 22.04.1 LTS

### Describe the bug

Hey I'm using Digital Ocean Space for Uploading media files I'm successfully done this requirement using 'provider-upload-AWS-s3' but i want delete the uploaded media file in Digital Ocean Space (Bucket) by deleting that particular file in Strapi media library

**Comment by derrickmehaffy** [comment]
We currently store file data in the database, you would need to use our delete API to remove this record as once the file is uploaded Strapi does not look at the contents of the storage provider to keep live data on what exists there or not.

Doing this would be a new feature and should be added to our feedback database: https://feedback.strapi.io
