### ISSUE TITLE
Is any way to change buit in models from studio?

### ISSUE THREAD

**Issue by sinegovsky-ivan** [strapi/strapi#153]
Hello!
How i can change database for user model or add fields to user model?

Thank you!

**Comment by pierreburgy** [comment]
@sinegovsky-ivan, this feature has been disabled in the Studio in order to avoid issues. You can edit manually by updating `/api/user/models/User.settings.json` file.

In Strapi v3, we will be able to edit it directly from the open-source admin panel.

**Comment by sinegovsky-ivan** [comment]
thank you!
