### ISSUE TITLE
Cannot read properties of undefined (reading 'runMigrations')

### ISSUE THREAD

**Issue by dogusdeniz** [strapi/strapi#15308]
### Required System information

Required System information
Node.js version: v16.14.2
NPM version: 8.5.0
Strapi version: 4.5.5
Database: 8.0.31, for Win64 (x86_64)
Operating system: Win64

### Describe the bug

The runMigrations setting for Strapi is not defined. ([on this page](https://github.com/strapi/strapi/pull/14593) ,  that is it will be active by default, but there is no definition)

` Cannot read properties of undefined (reading 'runMigrations') `

I upgraded from 4.5.3 to 4.5.5 and added a new migration, but I got the above error from strapi.

### Screenshots

I debugged and the following results are out

![image](https://user-images.githubusercontent.com/32245914/210161283-404a2826-efce-415a-87a8-02a5ee348981.png)

### Additional context

https://github.com/strapi/strapi/blob/e912c0a4d7ff6c0c71290e3f008db6ac05cb9260/packages/core/database/lib/migrations/index.js#L64

### Suggested solution

``` js
      return pending.length > 0 && (db.settings?.runMigrations || true);
```

**Comment by Torsten85** [comment]
I've run into the same problem and after a little investigation, I think the error is as follows:

This
```js
return pending.length > 0 && db.settings.runMigrations;
```

should be this
```js
return pending.length > 0 && db.config.settings.runMigrations;
```

As this was introduced in your PR @gary-alway , could you have a look? Thanks!

**Comment by MaximStone** [comment]
Faced the same problem.

**Comment by derrickmehaffy** [comment]
regardless if it's true or false: 

False: 
![image](https://user-images.githubusercontent.com/8593673/210627053-c7e63e7d-3ae4-44e2-9a95-a68a4d1c41ab.png)

True: 
![image](https://user-images.githubusercontent.com/8593673/210627074-eb6494f9-9245-4e27-8478-f8bfd7db57d6.png)

**Comment by derrickmehaffy** [comment]
> I've run into the same problem and after a little investigation, I think the error is as follows:
> 
> This
> 
> ```js
> return pending.length > 0 && db.settings.runMigrations;
> ```
> 
> should be this
> 
> ```js
> return pending.length > 0 && db.config.settings.runMigrations;
> ```
> 
> As this was introduced in your PR @gary-alway , could you have a look? Thanks!

Hey @Torsten85 do you want to submit a PR?

**Comment by denisukvadim** [comment]
I send PR for fix this issues
https://github.com/strapi/strapi/pull/15374
