### ISSUE TITLE
Creating a new Strapi with lasted version 

### ISSUE THREAD

**Issue by Aldrichclement2kvisiongroup** [strapi/strapi#15306]
## Bug report
➤ YN0000: ┌ Resolution step
➤ YN0032: │ better-sqlite3@npm:7.4.6: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ formidable@npm:1.2.6 is deprecated: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
➤ YN0032: │ sharp@npm:0.31.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ mini-create-react-context@npm:0.4.1 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0032: │ node-addon-api@npm:5.0.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0061: │ mailcomposer@npm:3.12.0 is deprecated: This project is unmaintained
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ buildmail@npm:3.10.0 is deprecated: This project is unmaintained
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0002: │ @strapi/helper-plugin@npm:4.5.5 [7454c] doesn't provide react-is (p75dd1), requested by styled-components
➤ YN0002: │ @strapi/helper-plugin@npm:4.5.5 [c342e] doesn't provide react-is (pde75e), requested by styled-components
➤ YN0002: │ @strapi/plugin-content-type-builder@npm:4.5.5 doesn't provide webpack (p68277), requested by @strapi/helper-plugin
➤ YN0002: │ @strapi/plugin-upload@npm:4.5.5 doesn't provide webpack (p98115), requested by @strapi/helper-plugin
➤ YN0002: │ @strapi/plugin-users-permissions@npm:4.5.5 doesn't provide webpack (p7b20c), requested by @strapi/helper-plugin
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 18s 692ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.6.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ ylru@npm:1.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yup@npm:0.32.11 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yup@npm:0.32.9 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 9s 248ms
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @strapi/strapi@npm:4.5.5 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.27.1 must be built because it never has been before or the last one failed
➤ YN0007: │ sharp@npm:0.31.2 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.15.18 must be built because it never has been before or the last one failed
➤ YN0007: │ msw@npm:0.49.1 [7454c] must be built because it never has been before or the last one failed
➤ YN0007: │ better-sqlite3@npm:7.4.6 must be built because it never has been before or the last one failed
➤ YN0009: │ better-sqlite3@npm:7.4.6 couldn't be built successfully (exit code 1, logs can be found here: C:\Users\2KVISI~1\AppData\Local\Temp\xfs-ecb0d9b4\build.log)
➤ YN0000: └ Completed in 41s 812ms
➤ YN0000: Failed with errors in 1m 11s

### Required System information

- Node.js version: 18.12.0
- NPM version:8.19.2
- Strapi version: lasted
- Database: sqlite
- Operating system: windows

**Comment by derrickmehaffy** [comment]
Can you please confirm what you are using as it would appear this is either yarn v3/berry or pnpm as this response is not normal npm.

**Comment by aldrichclementd** [comment]
Hello, I was able to solve the problem. It was due to the fact that I wanted to use mysql and I forgot to make the connection between my mysql server and strapi. Now everything works fine.

**Comment by duytd-ttlab** [comment]
Hello, I would like to ask about the update plan for 2 dependencies `mailcomposer@npm:3.12.0` and `buildmail@npm:3.10.0`. 
I worry about security because they are not maintained for 6 years.

**Comment by derrickmehaffy** [comment]
> Hello, I would like to ask about the update plan for 2 dependencies `mailcomposer@npm:3.12.0` and `buildmail@npm:3.10.0`. 
> I worry about security because they are not maintained for 6 years.

Please email security@strapi.io.

Marking this specific issue as resolved since the user mentioned it's fixed.
