### ISSUE TITLE
Production server crashes when using fully qualified domain name in HOST env, or leaks the IP address of the production server as HOST

### ISSUE THREAD

**Issue by Jonathan-Dobson** [strapi/strapi#15310]
### System information

- Node.js version: v14.21.2
- NPM version: 6.14.17
- Strapi version: 4.5.5
- Database: official dockerhub container of PostgreSQL 14.6 on x86_64-pc-linux-musl
- Operating system: VPS machine running latest version of Alpine linux and docker

### Describe the bug

The server crashes when using the FQDN for the HOST env var because strapi is telling the http server to listen on an IP address that belongs to cloudflare, probably obtained through dns, instead of listening to the real IP of my strapi machine.

### Steps to reproduce the behavior

1. Setup a VPS server with docker and a strapi container
2. Setup a docker nginx proxy server with SSL to route requests based on domain name
3. Setup a cloudflare.com DNS and SSL and point it to the VPS IP. 
4. Set strapi env.HOST=https://mydomain.com
5. Build and run strapi in production mode
6. server error (see screenshot below)

### Expected behavior

1. Expecting server to start and listen on the actual IP address of the machine strapi is running on without crashing.
2. Expecting the production server IP address to be secure and not be leaked out to the public.

### Screenshots

![image](https://user-images.githubusercontent.com/52715503/210176792-1ee0b7dd-01b2-48cf-89fb-9af08c8535cc.png)

#### This alternate configuration works, but it breaks something else:
The server doesn't crash when starting with env.HOST=0.0.0.0 and everything seems to work on the admin portal except for one thing; The USERS & PERMISSIONS plugin for the GOOGLE provider fails to complete authenticating when it sends the wrong redirect URL.
![image](https://user-images.githubusercontent.com/52715503/210178883-8893daf4-e800-47cb-94e4-940c185b53c3.png)

The `strapi develop` server running on a local machine can successfully complete the google authentication flow and it even adds the user to the strapi users. Just will not happen in production because the server crashes when setting HOST to a FQDN. I can also set the HOST= my real IP, but this still also breaks the users & permissions plugin for google oauth because the redirect URL uses the private local IP running in a docker container virtual network. This is also a poor security practice. We should mitigate this attack vector (exposing actual server IP addresses) by using DNS domain name based URL's along with some mechanism (like cloudflare) that can mask the real IP in DNS with a proxy IP.

### Recommended fix

1. Use a env.HOST for starting the strapi server only. Nothing else.
2. Use a env.DOMAIN to allow app hooks for creating public URL's. (ex: google callback)
3. Stop starting strapi server with IP obtained from DNS. Use nodejs to query the local machine IP instead.

**Comment by derrickmehaffy** [comment]
We strictly bind the host to available IP addresses (interfaces on the system), if the hostname used does not resolve to an interface/IP located on that host it will fail to bind properly. We do not treat this as a virtual bind. To properly set the public URL you should be using the URL key, not host as documented on this page: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/server.html and among all of our reverse proxy guides, for example with nginx: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/optional-software/nginx-proxy.html#strapi-server

This is a core method from node, something that we don't intend to change.
