### ISSUE TITLE
Dev build run failed after upgrade strapi from v4.5.4 to 4.5.5

### ISSUE THREAD

**Issue by necrox87** [strapi/strapi#15312]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.11.0
- Strapi version: 4.5.5
- Database: MySQL
- Operating system: Ubuntu 20.04 LTS (WLS)

### Describe the bug

Build failed after upgrade to v4.5.5

marco@DESKTOP-84OOPNB:~/projects/private/api-backend-test$ npm run build

> api-backend-test@0.1.0 build
> strapi build

Building your admin UI with development configuration...

● Webpack █████████████████████████ building (58%) 1/1 entries 3184/3639 dependencies 621/1504 modules 380 active
 esbuild-loader › node_modules/@strapi/plugin-upload/admin/src/pages/App/MediaLibrary/components/Header.js

ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage'
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/marco/projects/private/api-backend-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/marco/projects/private/api-backend-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@fortawesome/free-solid-svg-icons' in '/home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage'
  Parsed request is a module
  using description file: /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/package.json (relative path: ./admin/src/pages/HomePage)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage/node_modules doesn't exist or is not a directory
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/node_modules doesn't exist or is not a directory
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/node_modules doesn't exist or is not a directory
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/node_modules doesn't exist or is not a directory
      looking for modules in /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules
        single file module
          using description file: /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/package.json (relative path: ./node_modules/@fortawesome/free-solid-svg-icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.tsx doesn't exist
        /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
      /home/marco/projects/private/api-backend-test/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/marco/projects/private/api-backend-test/node_modules
        single file module
          using description file: /home/marco/projects/private/api-backend-test/package.json (relative path: ./node_modules/@fortawesome/free-solid-svg-icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.tsx doesn't exist
        /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
      /home/marco/projects/private/node_modules doesn't exist or is not a directory
      /home/marco/projects/node_modules doesn't exist or is not a directory
      /home/marco/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/package.json (relative path: ./node_modules/@fortawesome/free-solid-svg-icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.tsx doesn't exist
        /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' in '/home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage'
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/marco/projects/private/api-backend-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/marco/projects/private/api-backend-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/marco/projects/private/api-backend-test/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@fortawesome/free-solid-svg-icons' in '/home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage'
  Parsed request is a module
  using description file: /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/package.json (relative path: ./admin/src/pages/HomePage)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/HomePage/node_modules doesn't exist or is not a directory
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/pages/node_modules doesn't exist or is not a directory
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/src/node_modules doesn't exist or is not a directory
      /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/admin/node_modules doesn't exist or is not a directory
      looking for modules in /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules
        single file module
          using description file: /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/package.json (relative path: ./node_modules/@fortawesome/free-solid-svg-icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons.tsx doesn't exist
        /home/marco/projects/private/api-backend-test/node_modules/strapi-plugin-email-designer/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
      /home/marco/projects/private/api-backend-test/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/marco/projects/private/api-backend-test/node_modules
        single file module
          using description file: /home/marco/projects/private/api-backend-test/package.json (relative path: ./node_modules/@fortawesome/free-solid-svg-icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons.tsx doesn't exist
        /home/marco/projects/private/api-backend-test/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
      /home/marco/projects/private/node_modules doesn't exist or is not a directory
      /home/marco/projects/node_modules doesn't exist or is not a directory
      /home/marco/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/package.json (relative path: ./node_modules/@fortawesome/free-solid-svg-icons)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons.tsx doesn't exist
        /home/marco/projects/private/api-backend-test/node_modules/@strapi/admin/node_modules/@fortawesome/free-solid-svg-icons doesn't exist

### Steps to reproduce the behavior

1. Upgrade strapi v4.5.4 to v4.5.5
2. Run command "npm install"
3. Run command "npm run build"

### Additional context

I have fixed this problem installing this packages manually:

npm i --save @fortawesome/fontawesome-svg-core
npm install --save @fortawesome/free-solid-svg-icons
npm install --save @fortawesome/react-fontawesome

**Comment by gu-stav** [comment]
This issue is related to the email-designer plugin and is fixed in `2.1.2` according to https://github.com/alexzaganelli/strapi-plugin-email-designer/issues/114
