### ISSUE TITLE
Relation is not set if the related data is not public

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#15313]
### Required System information

- Node.js version: 14.21.2
- yarn version:  1.22.19
- Strapi version: 4.5.5
- Database: sqlite
- Operating system: macos

### Describe the bug

I'm trying to create entries with a GraphQL mutation (form submissions). I am adding some fields plus a relation (which form it is). The relation did not get filled. After trying a bunch of things, I realized I have to make the `find` endpoint on the related data (the forms collection) for it to get filled.
I would understand if this was a decision: when you are not able to find data, you should not be able to add it somewhere. But wouldn't it make sense to then error on creates that include this relation field? Erroring on something like: you are not allowed to set the form relation. Not only did I not understand why my field did not get filled, it might even result in missing production data if I forget to add the permission and nothing ever errors.

### Steps to reproduce the behavior

1. Install GraphQL (although this probably happens in REST as well)
2. Add a model with a relation (form)
3. create the model via GraphQL, including the relation: `form: 1`
4. See how it is not set on the entry.

### Expected behavior

Either I should be able to set the relation, or I want it to error.

### Additional context

Migrating from v3. Running models from plugins.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/12238
