### ISSUE TITLE
Warnings about unsupported RETURNING clause in Node SQLite3 client

### ISSUE THREAD

**Issue by mjadczuk** [strapi/strapi#15317]
### Required System information

- Node.js version: 16.19.0
- Strapi version: 4.5.3
- Database: SQLite 3.40.
- Operating system: Pop!_OS

### Describe the bug

I'm using a SQLite3 database for tests in Strapi with the `node-sqlite3` client. When running the tests, I'm getting the following warnings:

```
  console.log
    node-sqlite3 does not currently support RETURNING clause
      at Logger._log (node_modules/knex/lib/logger.js:42:13)
```

Initially, I thought that it is caused by an outdated SQLite version, since `RETURNING` support was added in SQLite 3.35. However, I've verified that the Node client version that I'm using (`5.1.4`) includes a newer release of SQLite:

```yml
sqlite3@^5.1.4:
  version "5.1.4"
  resolved "https://registry.yarnpkg.com/sqlite3/-/sqlite3-5.1.4.tgz#35f83d368963168b324ad2f0fffce09f3b8723a7"
  integrity sha512-i0UlWAzPlzX3B5XP2cYuhWQJsTtlMD6obOa1PgeEQ4DHEXUuyJkgv50I3isqZAP5oFc2T8OFvakmDh2W6I+YpA==
  dependencies:
    "@mapbox/node-pre-gyp" "^1.0.0"
    node-addon-api "^4.2.0"
    tar "^6.1.11"
  optionalDependencies:
    node-gyp "8.x"
```

To verify the SQLite version, I've ran the following query:

```javascript
await strapi.db.connection.context.raw("select sqlite_version()")
```

As expected, it yields `{'sqlite_version()': '3.40.0'}`, which [should support](https://www.sqlite.org/lang_returning.html) the `RETURNING` clause.

For the record, my locally installed version of `sqlite3` (`3.38.2`) also supposedly supports `RETURNING`, but I can also confirm it is not the source of the issue: the same warnings are also displayed when the tests are ran via Docker, and the local installation does not seem to be used either way based on the `sqlite_version()` result.

Are these warnings something that I should be worried about, or is it just Knex warning about a possibly unsupported feature?

### Steps to reproduce the behavior

1. Generate a TypeScript Strapi project.
2. Add unit tests supports as per documentation.
3. Configure local SQLite database.
4. Run tests.

### Expected behavior

Using a recent SQLite release should not issue any warnings.

**Comment by derrickmehaffy** [comment]
Issue is users need to move over to better-sqlite3, maybe we can add a warning?

**Comment by alexandrebodin** [comment]
sqlite3 has been replaced since then and the migration has been documented :) closing this as nothing left to fix
