### ISSUE TITLE
Error while installing dependencies:

### ISSUE THREAD

**Issue by hamzehparsi** [strapi/strapi#15316]
hello i am try install strapi latest version but error
description
all required install ( https://github.com/nodejs/node-gyp#on-windows ) 

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.5
- Database: sqlite (quick installation)
- Operating system: windows 11
please help me

**Comment by ivanThePleasant** [comment]
Hey 👋 Just to clarify, are you trying to do a fresh install, or are you updating to a newer version of strapi?

**Comment by hamzehparsi** [comment]
yes i am install fresh or new install strapi
thank you

**Comment by ivanThePleasant** [comment]
@hamzehparsi could you please share the full error log that you are getting? Thanks 😊

**Comment by hamzehparsi** [comment]
Creating a project with custom database options.
Creating a new Strapi application at F:\my-sstrapi.
Creating files.
Error while installing dependencies:

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd F:\my-sstrapi && yarn install

**Comment by ivanThePleasant** [comment]
@hamzehparsi and if you then try to run it, do you get any other errors?

**Comment by hamzehparsi** [comment]
very very thank you
i am going to folder and run npm run i and install node_module and run strapi

**Comment by prasad-takale-eminds** [comment]
Hi I am getting same error for 
`npx @strapi-community/dockerize@latest` command. 

Node.js version: v18.16.1
NPM version: 9.5.1
Strapi version: 4.12.4
Database: sqlite (quick installation)
Operating system: Ubuntu 22.04.3 LTS

For fresh installation
