### ISSUE TITLE
Custom service files not working with typescript

### ISSUE THREAD

**Issue by eucciferri** [strapi/strapi#15327]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.5
- Database: sqlite
- Operating system: macOS Ventura

### Describe the bug
Since several versions ago, it's impossible to use the service files of the collection types in TypeScript.

### Steps to reproduce the behavior

1. Create a new project running the following command: npx create-strapi-app@latest my-project --ts --quickstart
2. Open the project folder in VSCode
3. Create a new Collection Type
4. Open and edit the service file of the new Collection Type
5. Add or overwrite the find method as the Strapi documentation suggests

https://docs.strapi.io/developer-docs/latest/development/backend-customization/services.html#adding-a-new-service

```
import { factories } from "@strapi/strapi";

export default factories.createCoreService(
  "api::product.product",
  ({ strapi }) => ({
    // Method 2: Wrapping a core service (leaves core logic in place)
    async find(...args) {
      // Calling the default core controller
      const { results, pagination } = await super.find(...args);

      // some custom logic
      results.forEach((result) => {
        result.counter = 1;
      });

      return { results, pagination };
    },
  })
);
```

### Expected behavior
The method should not throw an alert message with types issues.

### Screenshots
<img width="588" alt="image" src="https://user-images.githubusercontent.com/38674416/210266172-e3ac51af-9748-4b3d-bdce-a7aabf2bfaa6.png">

### Code snippets
N/A

### Additional context
N/A

**Comment by sobhardwaj** [comment]
it is major issue in typescript I guess,  I didn't check with typescript although

**Comment by Bassel17** [comment]
Hello, thank you for publishing the issue, this should be working in the latest versions, so if you can update your strapi project and update us with your findings. Thank you
