### ISSUE TITLE
You can only work in one branch at a time, and you need to shut the application down to do merges because data is deleted

### ISSUE THREAD

**Issue by ToxicKevinFerm** [strapi/strapi#15337]
### Required System information

- Node.js version: Any
- NPM version: Any
- Strapi version: 4+
- Database: Postgres
- Operating system: Any

### Describe the bug

You are unable to work properly with git-flow in Strapi 4 and above.
This is because the database is synced and automatically updated to match the code.
So when you're changing branches and working with multiple branches, your data keeps getting deleted, this is frustrating.
You cannot change branch or do merges while Strapi is running.

### Steps to reproduce the behavior
0. Start Strapi
1. Checkout a new branch
2. Create a new content type
3. Add some content for that content type 
4. Commit your changes
5. Switch back to the first branch

Strapi will now have deleted all your data from the content type you just created.
This behaviour may be good for production, but it's detrimental to development.
It's not reasonable to take backups and restore on each branch change.
### Expected behavior

Strapi should not drop tables in development environment.

**Comment by nikita-fuchs** [comment]
This sounds like you're using SQLite ? The contents of your SQLite db change along with the branch you're switching.

**Comment by ToxicKevinFerm** [comment]
It's not sqlite @nikita-fuchs

When something in the schema changes, Strapi runs migrations that drops all tables and data not matching the schema.
But the schema changes constantly while working in different git branches.
This feature of strapi then makes it impossible to have consistent data across multiple git branches working on different features.

**Comment by nikita-fuchs** [comment]
Ah, damn, I see. I'm new to strapi. I know this phenomenon from working with an ORM called Prisma. What you can (and should) do is to have different DBs per working branch. The behaviour of strapi makes sense as the DB model needs to correspond strapi's data models, or else things wont' work unless you know very precisely, what you are doing. I don't remember how exactly, but I used some features of git to switch env / config files among branches.

**Comment by derrickmehaffy** [comment]
> Ah, damn, I see. I'm new to strapi. I know this phenomenon from working with an ORM called Prisma. What you can (and should) do is to have different DBs per working branch. The behaviour of strapi makes sense as the DB model needs to correspond strapi's data models, or else things wont' work unless you know very precisely, what you are doing. I don't remember how exactly, but I used some features of git to switch env / config files among branches.

Exactly this, we had the exact reverse problem in Strapi v3: #1114 that we "fixed" by being far more strict with the database tables which is normal for a product like ours. The data in the development shouldn't matter. Once we launch DEITS you'll be able to take an export but those exports will be bound the content-type structure: https://github.com/strapi/strapi/pull/15036
