### ISSUE TITLE
design bug

### ISSUE THREAD

**Issue by CN91** [strapi/strapi#15335]
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.5.5
- Database: postgres
- Operating system: macos

### Describe the bug

It feels really silly but it annoys me. The icon for 'bold' is not shown properly in the button for it in the rich text editor. 

### Steps to reproduce the behavior

1. Create a component with a rich text element
2. Go to the component to create a new element
3. Look at the screen / editor 
4. See wrong sizing / incorrect display of the icon.

### Expected behavior

Proper display of the icon ; the B should be fully visible.

### Screenshots
![Schermafbeelding 2023-01-03 om 12 12 59](https://user-images.githubusercontent.com/7311583/210347023-ed639e19-2b4f-4201-b162-865d18b3d28a.png)

**Comment by joshuaellis** [comment]
This is a DS issue & was fixed by https://github.com/strapi/design-system/pull/821

It will be resolved in the next release of the DS.
