### ISSUE TITLE
createMany dosen't insert realation

### ISSUE THREAD

**Issue by MHZarei** [strapi/strapi#15340]
### Required System information

- Node.js version: v16.16.0
- NPM version: 
- Strapi version: 4.5.5
- Database: Sqlite
- Operating system: ubuntu 22.04

### Describe the bug

If your entity have relation with another entity, and on createMany use id of it to insert, it doesn't insert relation data!
For example this code just insert rate and date and the user information doesn't inserted.
```
await strapi.db.query('api::rate.rate').createMany({
      data: [{ date: 1672788743747, user: 1, rate: 1 },
                 { date: 1672788743747, user: 2, rate: 2 },
                 { date: 1672788743747, user: 3, rate: 5 },
        ],
    }); 
```

### Expected behavior

I expected the relation information (for above example: user) saved in the database;

**Comment by derrickmehaffy** [comment]
These will need to be an array of ids that already exist or you will need to loop through and create them beforehand and grab the IDs. We don't support creating nested data at any level.

**Comment by dzcpy** [comment]
This is actually a bug. It doesn't save any relations (using id), when this entity has already been created and is available with that relation ID.

**Comment by alicanso** [comment]
why is it closed? problem is still exist?

**Comment by qraxiss** [comment]
problem still exist!

**Comment by Carw** [comment]
problem still exist!

**Comment by ItayTur** [comment]
Facing it for a week now

**Comment by Shariar-Hasan** [comment]
still facing the issue, is there any solution for this?
