### ISSUE TITLE
yarn install (workspaces) - not work!

### ISSUE THREAD

**Issue by reskwer** [strapi/strapi#1534]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6
- **Strapi version**: v3.0.0-alpha.12.6
- **Database**: mongo
- **Operating system**: windows 10 LTSB

**What is the current behavior?**
yarn install (workspaces) - not work
![image](https://user-images.githubusercontent.com/8849299/42405311-54b78598-819c-11e8-9afe-9b8386b7f291.png)

it's hard code ?
![image](https://user-images.githubusercontent.com/8849299/42405351-1b794d42-819d-11e8-8d6a-c8962196608e.png)

**Steps to reproduce the problem**
yarn add workspaces
yarn install package

**What is the expected behavior?**

succesfull install packages

**Suggested solutions**

**Comment by reskwer** [comment]
![image](https://user-images.githubusercontent.com/8849299/42414896-a1fc91f2-8248-11e8-8777-afc4ab996a51.png)
add admin folder in secessed install

**Comment by lauriejim** [comment]
Please check this issue https://github.com/strapi/strapi/issues/885
