### ISSUE TITLE
Cant move the cursor with left/right arrow while editing content in a field within a repeatable component

### ISSUE THREAD

**Issue by CosminComsa** [strapi/strapi#15352]
### **Required System information**

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: 4.3.3
- Database: mysql
- Operating system: macOS Monterey 12.6
- Browser: Chrome 108.0.5359.124

### **Describe the bug**
While editing the content of a repeatable component, when i try to move the cursor to edit a character in a word, the cursor is not moving when i press left/right arrow. The field is a normal text field. 

### **Steps to reproduce the behavior**

1. Create a collection, 
2. For the collection create a repeatable component with at least one text field
3. Type a word, like "password" and try to move the cursor to the "s" character only using your keyboard left/right arrows.

### **Expected behavior**
The cursor should move when the left/right arrows are tapped.

**Comment by joshuaellis** [comment]
This was fixed in a more recent version of `strapi`, i'd recommend updating your project and seeing if the problem persists.

**Comment by CosminComsa** [comment]
@joshuaellis Thanks for the fast response, i updated the project and everything works great! I will close this issue.
