### ISSUE TITLE
Changing the default id to another title in relation is not working.

### ISSUE THREAD

**Issue by joshuaolusayo** [strapi/strapi#15375]
### Required System information

- Node.js version: >=14.19.1 <=18.x.x
- NPM version: >=6.0.0
- Strapi version: 4.5.5
- Database:
- Operating system:

### Describe the bug

I am trying to set up a relation between two different collections but I am only left with an option to use the id of the other collection. I prefer to use another field like email, phoneNumber or possibly combine field (like firstName + lastName) but my changes in editTitle field is not affecting the result of what;s been shown. Sometimes, it automatically uses the first field used when creating a collection instead of id (but never consistent and annoying that it can't be changed) I would appreciate if this can be fixed asap or help provided on how to get it fixed.

Strapi version: 4.5.5

### Steps to reproduce the behavior

1. Go to 'Content Manager, Add new entry into your collection.'
2. Click on 'relation field and you will see the issue.'

### Expected behavior

I was expecting the changes made inside entryTitle to be used to fetch the list of relations name

### Screenshots
<img width="384" alt="Screenshot 2023-01-07 at 1 54 19 AM" src="https://user-images.githubusercontent.com/53523015/211124736-f823c667-8f85-4fc3-8543-13b9cd9c873a.png">
<img width="864" alt="Screenshot 2023-01-07 at 1 51 09 AM" src="https://user-images.githubusercontent.com/53523015/211124733-170b0bc4-6ee3-4afe-88ce-676e1c198cce.png">

**Comment by Boegie19** [comment]
Combinations of fields is not possible still chancing the entity title is see: https://docs.strapi.io/user-docs/latest/content-manager/configuring-view-of-content-type.html#configuring-the-list-view

**Comment by joshuaolusayo** [comment]
I did but nobody responded. When I eventually got response, it wasn't helpful. Everyone that contributed said it has to be a bug because it has been previously fixed before.

To cut the long story short, I had a bad experience with it and I had to write the whole logic myself in Node/Express.

**Comment by joshuaolusayo** [comment]
I did but nobody responded. When I eventually got response, it wasn't helpful. Everyone that contributed said it has to be a bug because it has been previously fixed before.

To cut the long story short, I had a bad experience with it and I had to write the whole logic myself in Node/Express.

**Comment by derrickmehaffy** [comment]
> I did but nobody responded. When I eventually got response, it wasn't helpful. Everyone that contributed said it has to be a bug because it has been previously fixed before.
> 
> To cut the long story short, I had a bad experience with it and I had to write the whole logic myself in Node/Express.

It is not a bug in this case no, if anything it's more of a feature request but this is not something we have "fixed" before as at the moment it's limited to certain types of fields.
