### ISSUE TITLE
RBAC header column for permissions is missing padding between title and CRUD checkboxes

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#15371]
### Required System information

- Node.js version: v18
- NPM version: v8
- Strapi version: v4.5.5
- Database: SQLite
- Operating system: Linux Mint 21.1

### Describe the bug

In the RBAC for Collection and Single types the padding between the column header and the CRUD checkboxes is a bit too close

### Steps to reproduce the behavior

1. Go to the admin roles section
2. Click on a role
3. See the missing padding on the header column

### Expected behavior

not sure how much padding should be added, but just a bit more

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/211052657-7d0d0115-3dbc-45fb-a675-5c50cbdc358a.png)

### Code snippets

N/A

### Additional context

N/A

**Comment by gu-stav** [comment]
Interesting. I thought I had fixed that in https://github.com/strapi/design-system/pull/755. Are you sure you are using the latest version of the DS + rebuild the admin?

**Comment by derrickmehaffy** [comment]
> Interesting. I thought I had fixed that in [strapi/design-system#755](https://github.com/strapi/design-system/pull/755). Are you sure you are using the latest version of the DS + rebuild the admin? What browser are you using?

This was in food advisor which I think is a few versions behind, but it's at least 4.5.x: https://github.com/strapi/foodadvisor/blob/bed4a05d6c12bebf2ec11ac6fc2554f91c12f400/api/package.json#L21

**Comment by derrickmehaffy** [comment]
Appears fixed as of v4.5.5, we just need to update food advisor.
