### ISSUE TITLE
NGINX - path - /scs. How to configure strapi to process the incoming request

### ISSUE THREAD

**Issue by manishsg** [strapi/strapi#1539]
**Informations**
- **Node.js version**:
v9.11.1
- **npm version**:
node5.6.0
- **Strapi version**:
3.0.0-alpha.12.3

- **Database**:
- **Operating system**:

**What is the current behavior?**
We have nginx reverse proxy to 2 nodejs servers. 
a. Client app on react
b. strapi api

the strapi location is set to /scs.

How do we configure strapi so that it can process the incoming request.
Admin Path
File Upload path.

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @manishsg . I suggest you to use subdomain for your Strapi app.
You also can check issues here https://github.com/strapi/strapi/issues?q=is%3Aissue+nginx+is%3Aclosed

**Comment by manishsg** [comment]
Hi,

I have setup the following 
# HTTPS - proxy requests on to local Node.js app
server {
        listen 443 ssl http2;
        server_name mysite.com;

        # Pass requests for / to localhost:8080
        location / {
                root /var/www/mysite.com/html;
                proxy_pass http://localhost:8080/;
        }

        # Pass requests for /admin to localhost:8181/admin/
        **location /scs {**
           
                proxy_pass http://localhost:1337/
        }

        location ~ /.well-known {
                allow all;
        }
}

Also updated the request.json in the environment to add route prefix as "scs"
The admin panel is not available in this situation.

**Comment by manishsg** [comment]
proxy_pass http://localhost:1337/ --> point to strapi

**Comment by derrickmehaffy** [comment]
@manishsg You probably need to set some headers for Nginx. I haven't tested something like this, but in my case my nginx config is as such:

```
server {

# Listen HTTPS
    listen 443 ssl;
    server_name api.example.com;

# Custom Error Page
    error_page 500 501 502 503 /Maintenance/maintenance.html;

# Maintenance Location
    location /Maintenance/ {
        root /var/www/example.com;
    }

# Root Location
    root /var/www/example.com/api.example.com/public_html;

# SSL Config
    ssl_certificate /etc/nginx/ssl/acme/api.example.com/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/acme/api.example.com/api.example.com.key;
    ssl_session_timeout  5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS;
    ssl_prefer_server_ciphers   on;

# Proxy Config
    location / {
        proxy_pass http://apiProd;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
```

**Comment by manishsg** [comment]
Thanks derrick. I have similar configuration except the subdomain is set to /scs as I need to use the main domain for the client react app.

# Proxy Config
    location /scs {
        proxy_pass http://apiProd;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

With the above setup /admin is not available for access.

**Comment by derrickmehaffy** [comment]
@manishsg is it possible to instead use a sub-domain like api.example.com instead of /scs.

Maybe something like scs.example.com? (It would make your setup much easier to work with)

**Comment by manishsg** [comment]
Ic. How do we create the subdomain on nginx ?

**Comment by manishsg** [comment]
https://www.digitalocean.com/community/questions/how-to-create-subdomain-with-nginx-server-in-the-same-droplet --> can it be on the same physical host ?

**Comment by derrickmehaffy** [comment]
@manishsg you would use the `servername` 

Here is a rough nginx docs page: http://nginx.org/en/docs/http/server_names.html

But yes they can be on the same physical host. Nginx looks for what URL is being requested.
example.com vs scs.example.com can serve two different proxies.

For instance I have an Nginx proxy in front of about 30 different websites all on the same IP and the same ports 😄

**Comment by derrickmehaffy** [comment]
Give me a few moments and I'll see if I can get a rough config made for you.

**Comment by derrickmehaffy** [comment]
Something like this, (I didn't actually check to make sure it all works, but its close)

Note that you may need to move the Upstream Servers to a different file, for instance I store mine in `/etc/nginx/conf.d/upstream.conf`

```
####################
# Upstream Servers #
####################

upstream example {
	server localhost:8080
}

upstream scs {
	server localhost:1337
}

########################
# HTTP SRV example.com #
########################
server {

# Listen HTTP
    listen 80;
    server_name example.com;

# Else Redirect to HTTPS // API
    location / {
      return 301 https://$host$request_uri;
    }
}

#########################
# HTTPS SRV example.com #
#########################
server {

# Listen HTTPS
    listen 443 ssl;
    server_name example.com;

# Root Location
    root /var/www/html/example.com;

# SSL Config
    ssl_certificate /path/to/your/crt;
    ssl_certificate_key /path/to/your/key;

# Proxy Config
    location / {
        proxy_pass http://example;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}

############################
# HTTP SRV scs.example.com #
############################
server {

# Listen HTTP
    listen 80;
    server_name scs.example.com;

# Else Redirect to HTTPS // API
    location / {
      return 301 https://$host$request_uri;
    }
}

#############################
# HTTPS SRV scs.example.com #
#############################
server {

# Listen HTTPS
    listen 443 ssl;
    server_name scs.example.com;

# Root Location
    root /var/www/html/example.com;

# SSL Config
    ssl_certificate /path/to/your/crt;
    ssl_certificate_key /path/to/your/key;

# Proxy Config
    location / {
        proxy_pass http://scs;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
```

**Comment by derrickmehaffy** [comment]
You also would need to make this subdomain with your domain provider in its DNS settings.

for example with goDaddy: https://www.godaddy.com/help/add-a-subdomain-20047

**Comment by manishsg** [comment]
Awesome. Thank you. I will give it a try and get back with details.

**Comment by manishsg** [comment]
Pleas

**Comment by derrickmehaffy** [comment]
Good to know @manishsg :smiley: glad I could help

**Comment by Naxos84** [comment]
What needs to be done, if subdomain is not an option?

**Comment by derrickmehaffy** [comment]
@Naxos84 Strapi would need to readd the prefix option.
