### ISSUE TITLE
Reset password sends invalid link (localhost)

### ISSUE THREAD

**Issue by paddotk** [strapi/strapi#15392]
### Required System information

- Node.js version: 16.14.2
- NPM version: 8.12.1
- Strapi version: 4.4.3
- Database: Not sure/not relevant
- Operating system: Windows 10

### Describe the bug
When I click 'forgot password' on a test/production server, it sends an e-mail with the following link:
`http://0.0.0.0:8080/admin/auth/reset-password?code=c57fd176971e888cf3e3dbf69e413948fbcf559`
This is of course not the right domain name/IP address.

I do notice that when I replace `http://0.0.0.0:8080` with the correct base url, it works, it opens up the page where you can change your password.

### Steps to reproduce the behavior
1. Go to the login screen
2. Click on 'Forgot your password?'
3. An e-mail is sent. This contains aforementioned link.

### Expected behavior
It should take the base url of wherever you are.

**Comment by bl96** [comment]
Hello,
i think you must set the **url** in the config/server.js file, which serves as a public url.

Like: 
`
//config/server.js file
`
`
module.exports = ({env}) => ({
  host: env('HOST'),
  port: env.int('PORT'),
  url: env('PUBLIC_URL','your public default url')
})
`

and then add to your environment variables PUBLIC_URL with your public url as a value.

Hope it helps.

**Comment by paddotk** [comment]
Hi @bl96, thank you, that works.

I'd say that having to configure this doesn't make a whole lot of sense though, as the domain is already known. Except for when we have a custom page for this, but there's a field in the settings to configure this (which doesn't seem to work though...).

**Comment by Boegie19** [comment]
This is not a bug since you need to specify the URL in config/server.js.
