### ISSUE TITLE
Pagination doesn't work in Graphql queries for repeteable components

### ISSUE THREAD

**Issue by monzonj** [strapi/strapi#15393]
## Bug report
Repeatable components inside a content type cannot be paginated with graphQl, for instance, to retrieve only a subset number of elements.

### Required System information

- Node.js version: v16.17.1
- NPM version:  8.15.0
- Strapi version: 4.5.5
- Database: PostgresSQL
- Operating system: Ubuntu 1.18

### Steps to reproduce the behavior

- Create a component with any number of fields
- Create a content type that includes the above component (repeatable), let's call this field `component`
- Populate the content type with more than one of the repeatable component
- Do a graphql query that paginates the repeatable component to return only one element `component(pagination: {limit:1})`

The query still returns all available repeated components and does not apply pagination

**Comment by Marc-Roig** [comment]
Hello! :) @monzonj I have tried to reproduce this in 4.7.1 and it seems to be fixed by https://github.com/strapi/strapi/pull/15715.

Could you check that actually fixes it for you?

**Comment by monzonj** [comment]
Hello @Marc-Roig 
Yes! i confirm that with version 4.7.1 it works as expected
