### ISSUE TITLE
Media Library - Cannot move existing files from the main folder

### ISSUE THREAD

**Issue by bl96** [strapi/strapi#15401]
### Required System information

- Node.js version: 16.17.1
- Strapi version: 4.5.5 (same issue applies for 4.5.0 - 4.5.5)
- Database: MariaDB 10.3.37
- Operating system: Windows 11

### Describe the bug

Files located in Media Library cannot be moved to created folders. I have created multiple folders, but when i want to move the existing file from main folder (the media library) to one of them then in the selection box there is only Media Library option (see the pictures below). However, when I upload a file inside some created folder, then i can move it between folders and also move it to media library. If i move this file from my folder to the media library then i can not move it back to folder too.

### Expected behavior

Show all folders as options in selection box when moving files from Media Library folder (the main folder).

### Screenshots
1. Folders are created
![Screenshot 2023-01-10 190720](https://user-images.githubusercontent.com/47901930/211630887-6b1896a4-a1c4-402e-bd44-2ccfdf382c3c.png)
2. File from root folder cannot be moved to created folders.
![Screenshot 2023-01-10 190758](https://user-images.githubusercontent.com/47901930/211630901-a15a1a1c-c812-43f0-a85f-8d11986c66dc.png)
3. File from the created folder can be moved to other folders.
![Screenshot 2023-01-10 190848](https://user-images.githubusercontent.com/47901930/211630909-98dffad2-e27e-41f3-b0d7-888086446b9f.png)

**Comment by dogusdeniz** [comment]
if you are on Media Library page , you need to expand the row to move file.

![image](https://user-images.githubusercontent.com/32245914/211933279-4dc3d854-8870-4f17-861e-c626a99c016c.png)

**Comment by bl96** [comment]
Hi @dogusdeniz,

didn´t see that arrow, it works properly. Thanks for help!
