### ISSUE TITLE
Delete a record with an image

### ISSUE THREAD

**Issue by MechJosh0** [strapi/strapi#1540]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.5
- **Database**: MySQL
- **Operating system**: Ubuntu

**What is the current behavior?**
When you try to delete a record which an an image it will fail to delete.
Frontend error: `An error occurred during record deletion.`

Server error:
```
ReferenceError: association is not defined
    at transformToArrayID (C:\Users\[...]\strapi\node_modules\strapi-bookshelf\lib\relations.js:24:3)
    at params.parseRelationships.Object.keys.reduce (C:\Users\[...]\strapi\node_modules\strapi-bookshelf\lib\relations.js:232:34)
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (C:\Users\[...]\strapi\node_modules\strapi-bookshelf\lib\relations.js:74:129)
    at <anonymous>
```

**Steps to reproduce the problem**
1. Create a new content type named Example
2. Add two field types, { title => String, image => Image }
3. Save the new content type
4. Go to the entries for content type Example
5. Add a new entry with a title `Foo 1`, save
6. Delete the record with the title `Foo 1`
7. Add a new entry with a title `Foo 2`, save
8. Delete the record with the title `Foo 2` **- This will cause the error**

**What is the expected behavior?**
Both records 6 and 8 should be deleted.

**Suggested solutions**
Delete the related image(s)/file(s) and the record.

**Comment by lauriejim** [comment]
Hello @MechJosh0 it has been fixed in alpha.12.6. Please migrate your application following migration guides in the wiki.
