### ISSUE TITLE
Strapi logs user out of admin panel when clicking on plugins and marketplace tab 

### ISSUE THREAD

**Issue by heyjaypray** [strapi/strapi#1541]
**Informations**
- **Node.js version**: 10.4.0
- **npm version**: 6.1.0
- **Strapi version**: 12.6
- **Database**: MongoDB
- **Operating system**: Mac OSX

**What is the current behavior?**
Strapi logs user out of the admin panel when selecting the plugins and marketplace tab

**Steps to reproduce the problem**
Click plugins and marketplace tab on Strapi v12.6

**What is the expected behavior?**
To take user to plugins and marketplace page

**Comment by fedecarg** [comment]
I'm having the same issue

* Strapi `v3.0.0-alpha.12.6`
* MongoDB `v2.6.10`
* Node.js `10.1.0`
* Linux, Ubuntu `16.04`

**Comment by lauriejim** [comment]
Hello, it's fixed, can you confirm please.

**Comment by derrickmehaffy** [comment]
@lauriejim Yes its fixed

Thanks for the quick fix
