### ISSUE TITLE
Edit view broken when using lot of fields

### ISSUE THREAD

**Issue by ntarandek** [strapi/strapi#15417]
### Required System information
- Node.js version: 16.5.0
- NPM version: 7.19.1
- Strapi version: 4.5.5 and 4.5.6
- Database: PostgreSQL 14
- Operating system: Mac Montery / Windows 10

### Describe the bug
I have a Product and Order tables that have quite a lot of fields (and they should) and when I try to edit either of them, from version 4.5.5 (works normally in 4.5.4 and I was forced to downgrade since my clients needs to be able to do their work) I keep getting the error (see screenshot). The error count increases regurarly and the tab with Strapi admin is completely frozen - I have to forcefully close it with Chrome Task Manager.

It behaves the same in Chrome, Firefox and Safari (all updated).

I tried to see changes from 4.5.4 to 4.5.5 and I see that CustomField logic was added, but did not find any obvious issue just by checking the changes.

I do not have any custom code that would cause this and only Strapi version change causes/resolves the issue - with full rebuild. 

This two screen only use normal fields (text, numbers, select, date/time) including one or two JSONs - no dynamic zones & no components.

### Expected behavior
That I can use edit screens with larger amount of fields without such issues.

### Screenshots
<img width="818" alt="Screenshot 2023-01-12 at 06 56 52" src="https://user-images.githubusercontent.com/5468733/211990545-c53893b0-5410-4a97-ab05-c67194ac878e.png">

**Comment by eucciferri** [comment]
Same issue here!

**Comment by eucciferri** [comment]
Hi @derrickmehaffy! How's it going? Any news about this issue? I can't update my Strapi projects from 4.5.4 because this problem.

Thanks!!

**Comment by ntarandek** [comment]
I tried about all that came to mind but lack of in-depth knowledge of Strapi internals (and it is a bit of a deep rabit hole :)) blocks me from at least preparing some patch for the issue. I do have one more try on my list (which will be done in a day or two) - simply stripping edits aways from edit view with a problem and try to see which one stops the issue - then going back in the depths of this render loop. Maybe you, @eucciferri, can try something similar. Maybe we get lucky and at least narrow it down and provide more specific into to the Strapi team.
