### ISSUE TITLE
Can't add a new field

### ISSUE THREAD

**Issue by bartgarbiak** [strapi/strapi#1542]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongo 4.0.0
- **Operating system**: macOS 10.13.5

Adding new fields to a new Content Type doesn't work. A blank screen appears, and a React error
`Expected ref to be a function or a string.` shows up in the console.

**Steps to reproduce the problem**
1. Setup Strapi
2. Enter admin
3. Add new Content Type
4. Click on "Add New Field"

**What is the expected behavior?**
A form for adding a new field should show up

**Suggested solutions**
No idea, sadly.

**Comment by lauriejim** [comment]
Hello @bartgarbiak did you have this issue after migrate your app or it's with a fresh new app ?

**Comment by soupette** [comment]
@bartgarbiak I'am unable to reproduce the error can you give me a link to your repo please?

**Comment by bartgarbiak** [comment]
That's what I was afraid of (it's a too obvious error to be overlooked). Unfortunately, I can't share the repo at the moment. Can you hint me what else I can do to at least debug that? Maybe not-minimized react would give a more detailed error (like, which ref is missing).

**Comment by soupette** [comment]
Well I'm aware that we have this error in the `settings-manager` plugin because it uses ref. Can you try to  create a new app and see if this happens again?

For debugging you need to have the dev mode set up, open the modal and see the warning in the console.

**Comment by bartgarbiak** [comment]
Ok, reinstalled entire Strapi globally, and the issue doesn't appear anymore. This can be closed, I believe.
