### ISSUE TITLE
Strapi 4.5.4+ Update Failing on Login

### ISSUE THREAD

**Issue by awtrimpe** [strapi/strapi#15431]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.4 (4.5.5 & 4.5.6)
- Database: SQLite
- Operating system: Ubuntu

### Describe the bug

When upgrading our Typescript project from 4.5.3 in the hope of removing transitive vulnerabilities, the admin panel becomes unavailable on initial load.

The call to /admin/telemetry-properties fails with status code 401.

Signing out or using cleared browsers does not seem to resolve the issue.

### Screenshots

<img width="880" alt="image" src="https://user-images.githubusercontent.com/43074742/212149069-66f5a904-c081-4d3e-a017-19186e809bae.png">

### Additional context
4.5.3
<img width="536" alt="image" src="https://user-images.githubusercontent.com/43074742/212149624-ef89895a-ee48-4a6a-ac50-07a27ea66ac2.png">

4.5.4
<img width="539" alt="image" src="https://user-images.githubusercontent.com/43074742/212149160-ed7a92b9-d8bd-4234-a58f-ef91a37a8ae2.png">

**Comment by globitdev** [comment]
@awtrimpe:  After to update the strap version, you will need to rebuild the admin panel.
`yarn build clean`

[https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#step-1-upgrade-the-dependencies](url)

**Comment by awtrimpe** [comment]
Thank you @globitdev !

I really apologize, I thought running develop on its own would rebuild but I should have followed the docs more closely. This resolved the issue!

Feel free to close this issue.
