### ISSUE TITLE
Can't have multi lines in content type description

### ISSUE THREAD

**Issue by haydos89** [strapi/strapi#1543]
**Informations**
- **Node.js version**: 
9.11.1
- **npm version**:
6.0.1
- **Strapi version**:
3.0.0-alpha.12.6
- **Database**:
MongoDb
- **Operating system**:
Fedora Linux

**What is the current behavior?**
400 Bad Request - request.error.model.read

**Steps to reproduce the problem**
1. Navigate Content Type builder
2. Create new content type - in the description add, 'Hello, World!

' - Note the new line is intentional
3. Add 4 fields - 1 string, 1 description, 1 enumeration, and 1 media
4. Attempt to save and note the error in the title.

5. Close strapi in CLI
6. Run `strapi start`
7. Note a new bug - `SyntaxError: ~/api/MyHappyModel/models/MyHappyModel.settings.json: Unexpected token 
 in JSON at position 152`
8. Open this file and note the JSON generated is invalid - the description field has a new line creating invalid JSON

**What is the expected behavior?**
New content type creates successfully

**Suggested solutions**
Ensure multi-line text fields are stringified/generated correctly

No issues with same title.

**Comment by lauriejim** [comment]
Hello @entwicklerfr ! Yap, setup (and dev experience) is not completely ready for Windows; Sorry for that.

Yap you can! I think it's an issue about parsing the API `description` params.

**Comment by entwicklerfr** [comment]
Hello @lauriejim,

Ok, I saw you are assigned to review on my PR https://github.com/strapi/strapi/pull/2140.

Thx.
