### ISSUE TITLE
[updated] Can't make 'relation' field required

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#15445]
### Required System information
Node.js version: v18.12.1
NPM version: v9.2.0
Strapi version: 4.5.6
Database: postgres
Operating system: OSX

### Describe the bug

It's not possible to make a 'relation' required. As Strapi treats a relation like a data field with a DB relation attached, it should be possible to mark this data field as required, but this can't be done.

### Steps to reproduce the behavior

1. Start creating a 'relation' in some data type
2. Click on _advanced_

### Expected behaviour

I can mark this data field _required_

### Screenshots
No way to make this field required:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/11761828/212333323-212ae93b-7d81-4958-80a1-4662754f5487.png">

**EDIT:** When adding `required` to the data type's schema.json, it works !

```
 "editedByRelation": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::users-permissions.user",
      "required": true
    },
```
and the checker responds:
```
"data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "editedByRelation must be defined.",
        "details": {
            "errors": [
                {
                    "path": [
                        "editedByRelation"
                    ],
                    "message": "editedByRelation must be defined.",
                    "name": "ValidationError"
                }
            ]
        }
    }
```

**Comment by joshuaellis** [comment]
Hey @nikita-fuchs this isn't a bug, it's an enhancement. We've spoke about trying to do this and it is on the content team's radar :)

**Comment by nikita-fuchs** [comment]
hey, thanks !

enhancement? this simply looks like somebody forgot it when doing the frontend work and adding the checkboxes to all data types - the backend already supports it, so I think it was a bug 😜 Anyways, should be done in 10 minutes frontend work, don't let us wait till version 6 with this ;)

Cheers !

**Comment by joshuaellis** [comment]
I think these were automatic changes – so no it hasn't been made yet, this is largely down to the fact that iirc relations are all handled the same way whether they're polymorphic or not and bidirectional relations are difficult to handle with `required`. 

So unfortunately there aren't any updates – sorry for the confusion. But we are still actively discussing this internally.

**Comment by Arunjenson-ss** [comment]
any update on this?

**Comment by netzpixel** [comment]
We really need this feature! It's been requested 6 years ago...

**Comment by AleferReinert** [comment]
I miss this feature too.

**Comment by nikita-fuchs** [comment]
IMHO it is not even a feature request. The feature on strapi is that you can mark fields required. From the product side, there is no reason to not have this for relations. So actually, it's a bug that should be fixed.

**Comment by derrickmehaffy** [comment]
> IMHO it is not even a feature request. The feature on strapi is that you can mark fields required. From the product side, there is no reason to not have this for relations. So actually, it's a bug that should be fixed.

It is considered a feature request as it was never intentionally added.

**Comment by nikita-fuchs** [comment]
If you promise a car to have door handles, it's not a feature request to have one on the passenger's side, too.

**Comment by chrisbraddock** [comment]
> **EDIT:** When adding `required` to the data type's schema.json, it works !

I'm observing that the UI shows that the relationship is required(red asterisk on relation field label), but I am allowed to save/create the record so long as all other validations are satisfied.

**Comment by chrisbraddock** [comment]
Shouldn't the people requesting this be upvoting it? I was only the second upvote. 
![image](https://github.com/strapi/strapi/assets/130854/04550af8-f725-4c83-a0af-5fcbee340b23)

**Comment by girish-soman** [comment]
Any update on this

**Comment by AhmedMuhsingez** [comment]
Adding the `"required": true` in the schema.json doesn't initiate the validation - meaning it's just useless. All i see is a red star over the field now, but it's meaningless since the form doesn't validate and I can still "publish" the article even if the fields are empty..

<img width="858" alt="image" src="https://github.com/user-attachments/assets/bee9d041-6bad-4944-99dc-dd7320a50941">

**Comment by leninjohnsonjames** [comment]
@AhmedMuhsingez ,
Same issues happening for me too, After done schema changes not working. only I got start.

**Comment by leninjohnsonjames** [comment]
Anyone having proper solution

**Comment by eucelso** [comment]
I chose to use Strapi for a project, but I'm bitterly regretting it.

Apart from this point, I agree with @nikita-fuchs.

I opened this PR https://github.com/strapi/strapi/issues/20529#event-13618811247 and so far no response.

Now I'm also experiencing the same problem, I need to add a field that is related to requied and I can't.

**Comment by kimyvgy** [comment]
Hello everyone, there is a small plugin to ensure that relation fields are not left empty. You can install it via NPM or Yarn as follows:

```bash
yarn add strapi-plugin-required-relation-field
```

You just set `required: true` to the relation fields in your `schema.json` file and then... bump.

Here is the GitHub repository: https://github.com/teguru-labs/strapi-plugin-required-relation-field.

**Comment by Risini1998** [comment]
@kimyvgy,
 **strapi-plugin-required-relation-field** This plugin doesn't work with strapi v4. 

Any feature update?

**Comment by Nirbhay007** [comment]
Any update on this issue as still not working. Using strapi v4 even if i add required : "true" it doesn't validate in backend.

**Comment by girish-soman** [comment]
Team, 

This is something that you guys can try to get rid of this bug at least from the project level.

In my project, I faced the issue where Strapi does not enforce required validation on relation fields during create or publish operations, which led to incomplete or invalid data being saved.

To overcome this limitation, I used Strapi lifecycle hooks (beforeCreate, beforeUpdate) to manually validate required relation fields before allowing the operation to proceed.

**Comment by abdulmoiez876** [comment]
Hi @girish-soman , can you share a snippet for lifecycle hooks implementation? I also tried this approach but when I tried updating an entry with or without `category` field (this is the one with relation type for my case), `connect` and `disconnect` nested attributes were inconsistent, so I didn't go with that approach.
`
async beforeUpdate(event) {
    const { data } = event.params;
    console.log({ connect: data.category.connect })
    console.log({ disconnect: data.category.disconnect })
}
`

**Comment by Fritze1602** [comment]
We ran into the same issue with required relations in Strapi v5 (relations not reliably available in lifecycles / connect-disconnect inconsistencies).

What finally worked for us was Document Service middleware, not lifecycle hooks or API middlewares.

This runs before persistence and is independent of REST / GraphQL / Admin UI paths. 

```ts
export default {
  register({ strapi }) {
    strapi.documents.use(async (ctx, next) => {
      if (ctx.uid !== "api::product.product") return next();
      if (ctx.action !== "create" && ctx.action !== "update") return next();

      const rel = ctx.params?.data?.weight_class;
      const connect = Array.isArray(rel?.connect) ? rel.connect : [];
      const disconnect = Array.isArray(rel?.disconnect) ? rel.disconnect : [];

      // required on create
      if (ctx.action === "create" && connect.length === 0) {
        throw new ValidationError("Weight class is required.");
      }

      // prevent removal on update
      if (ctx.action === "update" && disconnect.length > 0 && connect.length === 0) {
        throw new ValidationError("Weight class cannot be removed.");
      }

      return next();
    });
  },
};
```
