### ISSUE TITLE
Entity API returning wrong data for populated fields

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#15444]
### Required System information

Node.js version: v18.12.1
NPM version: v9.2.0
Strapi version: 4.5.6
Database: postgres
Operating system: OSX

### Describe the bug
When using population in the entity service API, it insists on returning the `id` of the related record. It's not possible to get just some specific field only. 

### Steps to reproduce the behaviour

1. Have some roles created for the `users-permissions` users.
2. Try querying for a user record and populating only the `type` of the role, not the full role record.

```
await strapi.entityService.findOne("plugin::users-permissions.user",  ctx.params.id,
    { populate: {
        role: { fields: ["type"]
        }}});
```
The response will be:
```
{
  id: 2,
...
  role: { id: 3, type: 'assistant' }
}
```

whereas it's fully possible to populate **only** the `id`:
```
await strapi.entityService.findOne("plugin::users-permissions.user",  ctx.params.id,
    { populate: {
        role: { fields: ["id"]
        }}});
```

resulting
```
 {
  id: 2,
...
  role: { id: 3 }
},
```

### Expected behavior

I can populate only selected fields just as the documentation suggests: https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/populate.html#advanced-populating

**Comment by Marc-Roig** [comment]
Hello :) Indeed what you mention would be ideal, this change would result in a breaking change as people might expect to always receive an id.

Strapi (as of today) does not consider `id` as another attrribute (it's not defined in the schema) but something that is intrinsic to each entity.

So unfortunately we will not be able to change this behaviour in the mid term :/ I would be glad to continue the conversation if you think what I explained is not actually the case.
