### ISSUE TITLE
Can't register the first administrator user

### ISSUE THREAD

**Issue by Audry300** [strapi/strapi#15456]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.5.6
- Database: SQLite
- Operating system: Windows 10

### Describe the bug

I just created a new project, following the quick start guide. However, I can’t manage the create the first administrator user from the admin registration page. I get a 400 (Bad Request) when I press on the " Let’s start " button. I’ve provided all the information necessary and even a valid email. Has anyone else encountered this?

### Steps to reproduce the behavior

1. Create a new strapi project
2. Go to the administrator registration page
3. Provide all the necessary information to register
4. Click on the "Let's start" button
5. See the error in the console

### Screenshots
![image](https://user-images.githubusercontent.com/71721639/212568957-6197141f-dc15-4741-8d2f-e20e2a6b5a0c.png)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by jolucas245** [comment]
I also have the same error

**Comment by jolucas245** [comment]
@Audry300 Hey man, I created the project using the "sudo" command and then yarn create, and it worked. Try too.

`$ sudo yarn create strapi-app menu_cms --quickstart`

**Comment by Audry300** [comment]
Hey @jolucas245, I appreciate the feedback. Was your OS Windows 10?

**Comment by Audry300** [comment]
So I just used Mozilla Firefox instead of Chrome and I can access the admin dashboard, so this could be a browser related issue.

**Comment by Audry300** [comment]
![image](https://user-images.githubusercontent.com/71721639/213575899-01a858bb-4231-4524-85fa-00d7803d277d.png)

This was the error message, from the network tab, using Chrome

**Comment by vipulverma42** [comment]
To add to above issue I found my first name and last name had 1 extra blank space in end. Once removed no more issue in chrome to register

**Comment by Tinomuchenje** [comment]
@joshuaellis is anyone working on this? I have experienced this and would like to fix the bug.

**Comment by joshuaellis** [comment]
> @joshuaellis is anyone working on this? I have experienced this and would like to fix the bug.

No need to ask, feel free to just give it a go :)
