### ISSUE TITLE
New "empty" (field-less) components can't be saved in the admin GUI

### ISSUE THREAD

**Issue by webhype** [strapi/strapi#15455]
### Required System information

- Node.js version: 16 LTS
- NPM version: Yarn latest
- Strapi version: 4.5.6
- Database: Postgres 14
- Operating system: Mac OS Ventura

### Describe the bug

When creating new components, but NOT adding any fields to them, the "Save" button is not clickable. 

I can make it clickable though by clicking "Edit" on the not-yet-saved component, click "Finish" (still without adding any fields), and now the "Save" button is clickable and the empty component can be saved.

### Steps to reproduce the behavior

1. Go to http://localhost:1337/admin/plugins/content-type-builder/
2. Click on "+ Create new component", type in any display name, select any category and click "Continue"
3. You will notice that the "Save" button on the page is not clickable until I add at least one field. But what if I am not sure yet what fields I want? I can't save my work!
4. The workaround is, click on "Edit", and immediately "Finish", et voila! The Save button is now clickable and I can save my "empty" (field-less) component.

### Expected behavior

The admin GUI should have a clear policy; either field-less components can be saved or not. Either they should be savable always or never (I would prefer always), but the workaround described above is inconsistent.

### Screenshots

Brief Loom video showing the problem: https://www.loom.com/share/1209d744c6cf42e185c2189501f03188

**Comment by raph941** [comment]
Hi @derrickmehaffy,
I'd love to help with this, could you please confirm the desired convention to adopt in resolution for this?

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy, I'd love to help with this, could you please confirm the desired convention to adopt in resolution for this?

TBH I'm not sure, the product and engineer teams will need to comment on the way it should work. As I'm on our support team I only review and reproduce issues.

**Comment by joshuaellis** [comment]
Hi @webhype, @raph941 I've spoken with other engineering members and we've concluded this is currently expected behaviour. Therefore, I would ask you either submit a PR to change it so we can discuss further (although this may be a fruitless effort) or submit a feature request in Canny – https://strapi.canny.io/
