### ISSUE TITLE
Question: Can I upload an asset to local MediaLibarry from controller?

### ISSUE THREAD

**Issue by exotexot** [strapi/strapi#15484]
Hello,

I wrote a custom controller: in my src/api/XYZ/controller/custom.js to handle a certain action.

I was wondering if it is possible to upload an image asset directly from the controller, without making an EXPLICIT api call, since the STRAPI element is exposed in the coreController

module.exports = createCoreController(
  "api::xyz.xyz",
  ({ strapi }) => ({

..

Sadly this is not really well documented in Strapi documentation, but I have seen something like:
strapi.plugins.upload.services.upload

However I don't know which arguments to pass here.

**Comment by nikita-fuchs** [comment]
+1 on this, following along.

**Comment by dogusdeniz** [comment]
Here example code, good luck.



```js
       myendpoint: async (ctx) =>{
        const { object_id } = ctx.request.body;
        const { files } = ctx.request.files;

        await strapi.plugins.upload.services.upload.upload({
          data: {
            refId: object_id,
            ref: 'api::api-name.api-name', // your collection uid
            field: 'images', // your collection image field name
            fileInfo: { folder: 1 }, // if you want assign a folder
          },
          files: files,
        });

       return ctx.send();
     
      }
```


Sorry maybe there is a syntax error
