### ISSUE TITLE
Bad checks throw server Error on taken username and password

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#15497]
Come on guys, I can't be the first one to notice. 🤠

### Required System information
Node.js version: v18.12.1
NPM version: v9.2.0
Strapi version: 4.5.6
Database: postgres
Operating system: OSX

### Describe the bug

When registering a new user and its username and/or email is taken, a fully blown server error is thrown , and no proper response data is sent. Only the console log gives you a hint about what went wrong: `ApplicationError: Username already taken`

### Steps to reproduce the behaviour

1. Register user with email or username that is already taken
2. See 500 Error thrown
3. See no information returned whatsoever through the API.

### Expected behavior

See
1. a correct status code, 2. the usual api input check results like on any other malformed input:
```
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "2 errors occurred",
        "details": {
            "errors": [
                {
                    "path": [
                        "username"
                    ],
                    "message": "This attribute must be unique",
                    "name": "ValidationError"
                },
                {
                    "path": [
                        "email"
                    ],
                    "message": "This attribute must be unique",
                    "name": "ValidationError"
                }
            ]
        }
    }
}
``` 

### Code snippets

Some (maybe legacy?) code in the `users-permissions` plugin is to blame for this: 
https://github.com/strapi/strapi/blob/0a4a76112a781d23a1f19e4ae1343431f81410c2/packages/plugins/users-permissions/server/controllers/auth.js#L308-L325

### Additional context

0. The second function here is never run my tests showed.
1.  who can spot a scoping mistake ? 😉
2.  This code prevents the data being passed to the generic input validation logic (that seems to be based on validity checks the DB gives back to Strapi I suppose, but I'm new now to strapi so I don't know for sure yet)
3. In production, monitoring tools get clogged up with false errors (as these are no real errors). 
4. Generally speaking, throwing errors here is a bad practice, a proper response would be adequate.
5. There is no way for a frontend to know, what the actual issue was.
6. Not putting username and email as part of the overall validation process means that end-users technically can't be told about **all** the issues with their api data in **one** request. Fill out a form and send it ? Oh no, your email is already in use. Change, send again. Oh no, your username is already in use. Change something once more....

**Comment by fahmifitu** [comment]
What a bug. I just noticed it in my system. all error throwing is broken. It completely destroyed my error handling on the client side. Well done strapi team

**Comment by nikita-fuchs** [comment]
Superseded by: https://github.com/strapi/strapi/issues/15648
