### ISSUE TITLE
@strapi/plugin-color-picker Color Picker regex not supporting alpha transparent color value `#FF000000`

### ISSUE THREAD

**Issue by antokhio** [strapi/strapi#15495]
## Bug report
Strapi plugin Color Picker regex not supporting alpha value `#FF000000`

### Required System information

- Node.js version: 16.18.0
- Strapi version: 4.6.0-beta.0

### Describe the bug

The field value looks ok but there is regex validation issue:
![image](https://user-images.githubusercontent.com/1254168/213402205-b74da8cf-9dff-4e95-a0b2-809a8c33a6db.png)

I'm not the regex expert this seems to work:
```
^#([A-Fa-f0-9]{6,8}|[A-Fa-f0-9]{3})$
```

**Comment by derrickmehaffy** [comment]
Your hex color code isn't valid, Hex color codes are 6 chars not 8

**Comment by joshuaellis** [comment]
I'd disagree with that @derrickmehaffy you can add an additional 2 characters for mapping the alpha. But this would be an enhancement to the field we provide, so it probably wants to go on Canny anyway :) CC @markkaylor & @remidej

**Comment by markkaylor** [comment]
The regex provided is just a default value, it can be changed in the Content type builder advanced settings for the field. @antokhio, if you find a regex that works with alpha could you please share it here and I will update the default value being set on the color picker:

https://github.com/strapi/strapi/blob/61f3ef23ed551030e8fc6bf14d591d2b397775d3/packages/plugins/color-picker/admin/src/index.js#L36

**Comment by derrickmehaffy** [comment]
> I'd disagree with that @derrickmehaffy you can add an additional 2 characters for mapping the alpha. But this would be an enhancement to the field we provide, so it probably wants to go on Canny anyway :) CC @markkaylor & @remidej 

TIL, was not aware of that.

**Comment by antokhio** [comment]
> The regex provided is just a default value, it can be changed in the Content type builder advanced settings for the field. @antokhio, if you find a regex that works with alpha could you please share it here and I will update the default value being set on the color picker:
> 
> https://github.com/strapi/strapi/blob/61f3ef23ed551030e8fc6bf14d591d2b397775d3/packages/plugins/color-picker/admin/src/index.js#L36
> 
> or feel free to open a PR :)

Actually it’s in a body of issue:
```
^#([A-Fa-f0-9]{6,8}|[A-Fa-f0-9]{3})$
```

But again, I’m not reflex expert ;)
