### ISSUE TITLE
Blocking a multi-origin request

### ISSUE THREAD

**Issue by sbacem** [strapi/strapi#155]
I set config
```

  "cors": {
    "origin": true,
    "expose": [
      "my-host:8080"
    ],
    "maxAge": 31536000,
    "credentials": true,
    "methods": [
      "GET",
      "POST",
      "PUT",
      "PATCH",
      "DELETE",
      "OPTIONS",
      "HEAD"
    ],
    "headers": [
      "Content-Type",
      "Authorization"
    ]
  },
```
But always same error in navigator Blocking a multi-origin request  😩😩😩

**Comment by Aurelsicoko** [comment]
What's your origin host? Did you set the `Access-Control-Expose-Headers` with the value `my-host:8080` in your request? If not, the request will be rejected.

**Comment by sbacem** [comment]
Of course i make real host `my-host:8080` it's just example in github  :smirk:.
i solved the problem there not from strapi, it's from my environment in cloud 9 :pensive:
Thanks for you @Aurelsicoko
