### ISSUE TITLE
Dynamic Zone i18n does not work correctly when components contain relations 

### ISSUE THREAD

**Issue by JonasGruenwald** [strapi/strapi#15506]
### Required System information

- Node.js version: v18.10.0
- NPM version: 8.19.2
- Strapi version: 4.5.6
- Database: Posgres & SQLite
- Operating system: MacOS

### Steps to reproduce the behavior

1. Create a new project with i18n and two locales
2. Create a collection type with any field, e.g. collection 'People' with text field 'Name'
3. Create a single type with localization enabled which contains a localization enabled dynamic zone which has a component that contains a relation to the collection type e.g. 'Guest List' with component 'Guest' which is a 1:n relation to 'People'
4. Create an entry in the collection, then create an entry for the single type in one locale 
5. Switch to the other locale
The following happens:
- The Dynamic zone components from the original locale are still visible
- Attempting to save in the new locale will cause an internal server error
```
error: insert into `components_test_test2s` (`id`) values (1) returning `id` - UNIQUE constraint failed: components_test_test2s.id
```
- When deleting the component in the new locale, then switching back to the original locale, the screen will go blank with this frontend error:
```
Uncaught TypeError: i is not iterable
```

### Expected behavior

When switching to another locale, the localized dynamic zone should not contain entries from the original locale, and should not cause errors when attempting to edit.

### Additional context

As far as I can tell, this error only occurs when the component contains a relation, I have reproduced it with a brand new Strapi project before creating this issue.

It's possible to work around this by refreshing the page every time when switching locales, but it is very cumbersome, as frontend errors will still occur when switching between locales, also components will be displayed inconsistently after switching sometimes, for example when the DE dynamic zone has 2 entries and you switch to EN which has 1 entry, the zone will display the correct EN entry and then the second DE entry.

**Comment by JonasGruenwald** [comment]
I've just made a repro to reproduce this issue with :

https://github.com/JonasGruenwald/strapi-issue-15506

And here is a video demonstrating the issue, it seems like it's enough if a component with a relation exists to cause an error

https://www.youtube.com/watch?v=tPBBb6vCM7w

**Comment by Przemek625** [comment]
I can confirm that I have a similar project. When debugging it it looks like the backend  returns correct data. But fronted do not refresh fields that contains relations.

**Comment by jonadeline** [comment]
Yes same here. the issue happens with localized relation fields.  

When I switch the locale in the right column to edit my content in another language, it's still displaying the relations in the previous locale.  I have to hard refresh the page or to switch the locales again to display the relation in the right language. 
I believe this is mainly a frontend issue as when i save my content the relations are saved with the right locale even if they are displaying in the wrong one.

I did a small screenscast for better understanding. 

https://www.loom.com/share/6b8460f64c9b4112b98ae01b7cc754b0

**Comment by Moutaz-homsi** [comment]
A similar issue here on a relation field inside a component .

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12538
