### ISSUE TITLE
Email Confirmation Internal Server Error caused by Office 365 Outlook Threat Scanning completing confirmation before redirecting the user

### ISSUE THREAD

**Issue by foxjordan** [strapi/strapi#15519]
### Required System information

- Node.js version: 16.17.0
- Strapi version: 4.5.6
- Database: mysql
- Operating system: Ubuntu 20.04 Running in an Azure VM

### Describe the bug

When the Strapi backend sends the confirmation email to a user, the confirmation link is something like `${backendURL}/api/auth/email-confirmation?confirmation=${confirmationCode}`. When that link is clicked from within a managed email client (Office 365), it is passed through a threat protection filter (pictured)
<img width="630" alt="image" src="https://user-images.githubusercontent.com/6166163/213812352-4b582447-66d0-4506-85dd-9d9db921684d.png">

The email confirmation is completed successfully when this happens before the mail client redirects the user to the confirmation url, so the user exists and is confirmed by the time the user reaches the confirmation page for the first time. 

Instead of redirecting the user to the frontend URL specified in the Strapi settings, it leaves the user on `${backendURL}/api/auth/email-confirmation?confirmation=${confirmationCode}` where it displays an internal server error in JSON format. 

```
{
"data": null,
"error": {
"status": 500,
"name": InternalServerError",
"message": "Internal Server Error"
}
}
```

### Expected behavior

Ideally: The URL should redirect the user to the specified frontend URL if the email address is confirmed.

Acceptable: Stay on the same URL but provide a message stating the user already exists or is already confirmed.

There should at least be a place (and maybe there is and I just can't find it) where we can specify how Strapi handles a user already exists scenario, or a way to redirect users away from our backend URL.

**Comment by dogusdeniz** [comment]
I think you should provide this with a frontend.  strapi gives you confirmation API.  
You can also send a strapi request from the confirmation page in your frontend project and you can direct according to the response.

**Comment by foxjordan** [comment]
> I think you should provide this with a frontend. strapi gives you confirmation API.
> You can also send a strapi request from the confirmation page in your frontend project and you can direct according to the response.

I'm not sure I understand what you mean. I did provide a frontend. It correctly redirects to that frontend most of the time, just not in this specific circumstance.

**Comment by derrickmehaffy** [comment]
The problem is when we validate the user the key for that validation is deleted so when another request is made using that validation key should fail because it doesn't exist. I agree with @dogusdeniz here in that it's not really something we (Strapi) should handle.

**Comment by foxjordan** [comment]
> The problem is when we validate the user the key for that validation is deleted so when another request is made using that validation key should fail because it doesn't exist. I agree with @dogusdeniz here in that it's not really something we (Strapi) should handle.

@derrickmehaffy that totally makes sense, I'm just not sure where it even would be handled. As far as I can tell, there's nowhere for me to customize what happens in this scenario. Strapi provides a setting for redirecting on a successful confirmation. The 500 status is coming from Strapi, so I need to know where that's being generated so I can intercept it and redirect it appropriately.

**Comment by derrickmehaffy** [comment]
It's most likely an uncaught database error because the validation doesn't exist.

In the uses and permissions plugin you'd want to look for the route that handles the validation and then from there you can get the controller name. 

Let me see if I can find it.

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/blob/7cb5e9e8e28d643008f9fdbc9fc44f0a9faeddce/packages/plugins/users-permissions/server/controllers/auth.js#L356

**Comment by foxjordan** [comment]
Amazing. Thank you!

**Comment by raykeating** [comment]
This code resolved the issue for me:

```js

// Path: /src/extensions/users-permissions/strapi-server.js

const { validateEmailConfirmationBody } = require("@strapi/plugin-users-permissions/server/controllers/validation/auth");
const { getService } = require("@strapi/plugin-users-permissions/server/utils");
const utils = require("@strapi/utils")
const { ValidationError } = utils.errors;

module.exports = (plugin) => {

  plugin.controllers.auth.emailConfirmation = async (ctx, next, returnUser) => {
      const { confirmation: confirmationToken } = await validateEmailConfirmationBody(ctx.query);
  
      const userService = getService('user');
      const jwtService = getService('jwt');
  
      const [user] = await userService.fetchAll({ filters: { confirmationToken } });
  
      if (!user) {
        throw new ValidationError('Invalid token');
      }
  
      await userService.edit(user.id, { confirmed: true });
  
      if (returnUser) {
        ctx.send({
          jwt: jwtService.issue({ id: user.id }),
          user: await sanitizeUser(user, ctx),
        });
      } else {
        const settings = await strapi
          .store({ type: 'plugin', name: 'users-permissions', key: 'advanced' })
          .get();
  
        ctx.redirect(settings.email_confirmation_redirection || '/');
      }
  };

  return plugin;
};
```

This overrides the default behavior which is to expire the the confirmation token.  This code has all the same behaviors as the default controller, but it doesn't expire the token.  So any time the email confirmation link is clicked it will redirect the user to your email confirmatino redirection url.
