### ISSUE TITLE
PNPM build fails

### ISSUE THREAD

**Issue by 0x00A1FA** [strapi/strapi#15511]
ModuleNotFoundError: Module not found: Error: Package path ./lib/maps/entities.json is not exported from package [...]/node_modules\entities (see exports field in [...]/node_modules\entities\package.json)

**Comment by aussieboi** [comment]
Using:
- strapi: 4.9.0 
- pnpm: 8.1.0
- node: 18.15.0

I had same issue just added following to `.npmrc` in root of strapi project and it work fine now. Hope it helps. 

```
node-linker=hoisted
shamefully-hoisted=true
dedupe-direct-deps=true
```

**Comment by aussieboi** [comment]
It worked locally, in CI env failed with latest pnpm 8.1.1, tested on few versions but didn't manage to make it work. now removed lockfile and global store to be sure now doesn't work locally.

**Comment by TechQuery** [comment]
> Using:
> 
> * strapi: 4.9.0
> * pnpm: 8.1.0
> * node: 18.15.0
> 
> I had same issue just added following to `.npmrc` in root of strapi project and it work fine now. Hope it helps.
> 
> ```
> node-linker=hoisted
> shamefully-hoist=true
> dedupe-direct-deps=true
> ```

@aussieboi Thanks, it works! So I build a Template Repository with PNPM: https://github.com/idea2app/Strapi-PNPM-Docker-ts
