### ISSUE TITLE
Files find url root points to localhost:1337

### ISSUE THREAD

**Issue by osamajandali** [strapi/strapi#1551]
**Informations**
- **Node.js version**:
v9.11.2
- **npm version**:
v5.6.0
- **Strapi version**:
3.0.0-alpha.12.7.1
- **Database**:
mongodb
- **Operating system**:
Ubuntu 16.04.4 x64

**What is the current behavior?**
url property that return from requesting the files api have **localhost:1337** in the url property

this is the response:
`[
  {
    "_id": "5b448d83e6c26214a4274e13",
    "name": "logo.png",
    "hash": "8f91515da1b44e4d87bfdbb2d97c4a9f",
    "ext": ".png",
    "mime": "image/png",
    "size": "5.71",
    "url": "http://localhost:1337/uploads/8f91515da1b44e4d87bfdbb2d97c4a9f.png",
    "provider": "local",
    "related": [
      {
        "_id": "5b448d83e6c26214a4274e14",
        "ref": {
          "_id": "5b448d83e6c26214a4274e12",
          "createdAt": "2018-07-10T10:42:11.004Z",
          "updatedAt": "2018-07-10T10:42:11.019Z",
          "__v": 0,
          "id": "5b448d83e6c26214a4274e12"
        },
        "kind": "Project",
        "field": "mainImg"
      }
    ],
    "createdAt": "2018-07-10T10:42:11.036Z",
    "updatedAt": "2018-07-10T10:42:11.046Z",
    "__v": 0,
    "id": "5b448d83e6c26214a4274e13"
  }
]
`

**Steps to reproduce the problem**
1- start server
2- request `upload/files'

**What is the expected behavior?**

the url property should be without `localhost:1337`

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
+1 to this especially if your running behind an nginx proxy. That URL will almost always be wrong.

**Comment by lauriejim** [comment]
Hello @osamajandali and @derrickmehaffy . That's a good catch !
We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

You will have to update the plugin `strapi-plugin-upload` and `strapi-upload-local` upload provider.
But be careful because I think it can break the media input in the content manager. You probably have to update the `strapi-plugin-content-manager` too.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by osamajandali** [comment]
I will start working on it 👍

**Comment by lauriejim** [comment]
Thank you @osamajandali !

**Comment by appsolutegeek** [comment]
Hi,

Does anyone know if any work has started or near finishing? I have the same issue of what I think is being explained here.

I have strapi behind nginx on port 80 with its own domain name.

So going to the domain name, strapi works, but adding an image always appends localhost:1337.

I tried updating the HOST and PORT env files but of course, then I can't access it anymore.

**Comment by lauriejim** [comment]
@osamajandali Have you some news about this issue please.

**Comment by osamajandali** [comment]
@lauriejim I am sorry for being late at this as I was super busy last month.. I started working on it back then and I think I am going to finish it this weekend..

**Comment by cpof-tea** [comment]
In generated api `plugins/upload/controllers/Upload.js`
or in `strapi-helper-plugin@alpha` - `controllers/Upload.js`
```
66 |       if (file.url && file.url[0] === '/') {
67 |         file.url = strapi.config.url + file.url;
68 |       }
```
I understand why strapi.config.url is actually here when strapi is representing as remote api, but when it's local this strapi.config.url should be disabled, I think. Or there should be an option to disable it.

**Comment by derrickmehaffy** [comment]
@lauriejim also related to this, even setting the host option it still adds the Strapi port so if you proxy requests via nginx the port will be wrong unless you are proxying 1337 (which you shouldn't be :P )

I think that there needs to be a "Read Only" option for that files url
Server is actually running on `localhost:1337` but the files show the read only `https://domain.com` (Note the no port)

**Comment by derrickmehaffy** [comment]
I've started a fix for this: https://github.com/strapi/strapi/pull/1813

**Comment by derrickmehaffy** [comment]
@osamajandali was this in line with what you were thinking?
