### ISSUE TITLE
Strapi not generating unique slugs for new entries when the same value is submitted from the front-end

### ISSUE THREAD

**Issue by kofitalent** [strapi/strapi#15514]
I am using Strapi V4 as backend and Next Js as front-end to develop a web app where a user can create an account as an author and be able to submit article via the front-end. The content builder for the articles at the back-end has a slug field which is generated from the title field of the article. 

Adding an entry with the same title at the back-end correctly generates the slug and appends a number to titles that are the same. Now the issue is with the submission of entries at the front-end by authors. When an author submits 2 separate entries with the same title, Strapi returns an error because it unable to correctly generate the slug which a a unique and required field.

I had to use a timestamp to temporarily allow authors post articles. How do I solve this issue as I don't want slugs to be generated and posted from the front-end. I beleive it might be a bug with the built-in slug system in Strapi.

**Comment by dogusdeniz** [comment]
I think you must use db.lifecycle

[Strapi Lifecycle Doc](https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#lifecycle-hooks)

```js
// ./src/api/[api-name]/content-types/[api-name]/lifecycles.js
const {errors} = required('@strapi/utils');

module.exports = {
  beforeCreate: async (event) => {
    const { data, where, select, populate } = event.params;
    const count = await strapi.db.query('api::api-name.api-name').Count({
         where : {
             title : data.title
         }
    });

    if(count>0) throw new errors.ApplicationError ('must be unique');
  },
}
```

Sorry, it can be there is some syntax error, I write in phone, I will fix it later.

**Comment by dogusdeniz** [comment]
I think I misunderstood your question, are we talking about the uid generator?

**Comment by kofitalent** [comment]
Yes the uid generator.

**Comment by kofitalent** [comment]
When I add an entry at the Strapi backend, the uid generator is able to
generate my slug field from the title of the entry correctly. However when
I add an entry from the front-end, the uid generator is unable to generate
the slug from the title automatically as it does at the Strapi backend.
