### ISSUE TITLE
strapi not installing with npx create strapi-app my-project --quickstart

### ISSUE THREAD

**Issue by gethushan** [strapi/strapi#15520]
Here is the Problem 
How to resolve it ...
Please give me a solution ....

PS D:\My Projects\Dashboard> npx create-strapi-app@latest my-project --quickstart
Creating a quickstart project.
Creating a new Strapi application at D:\My Projects\Dashboard\my-project.
Creating files.
Error while installing dependencies:
warning @strapi/strapi > koa-session > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning @strapi/strapi > @strapi/admin > react-router > mini-create-react-context@0.4.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained 
warning @strapi/strapi > @strapi/admin > node-polyfill-webpack-plugin > url > querystring@0.2.0: The querystring API is considered Legacy. new 
code should use the URLSearchParams API instead.
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: 
https://github.com/lydell/resolve-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please 
see https://github.com/lydell/urix#deprecated
warning @strapi/plugin-users-permissions > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142     
warning @strapi/plugin-users-permissions > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() 
in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @strapi/plugin-users-permissions > request > har-validator@5.1.5: this library is no longer supported
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.5.6" has unmet peer dependency "webpack@^5.74.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder > @strapi/helper-plugin > react-select > @emotion/react > @emotion/babel-plugin@11.10.5" has unmet peer dependency "@babel/core@^7.0.0".
error D:\My Projects\Dashboard\my-project\node_modules\better-sqlite3: Command failed.
Exit code: 1
Command: prebuild-install || npm run build-release
Arguments:
Directory: D:\My Projects\Dashboard\my-project\node_modules\better-sqlite3
Output:
prebuild-install warn install No prebuilt binaries found (target=18.12.0 runtime=node arch=x64 libc= platform=win32)

> better-sqlite3@7.4.6 build-release
> node-gyp rebuild --release

gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@18.12.0 | win32 | x64
gyp info find Python using Python version 3.10.2 found at "C:\Program Files\Python310\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\R GETHUSHAN\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\My Projects\Dashboard\my-project\node_modules\better-sqlite3
gyp ERR! node -v v18.12.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok

 Keep trying!

gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\
studio.js:369:14)
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\R GETHUSHAN\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\R GETHUSHAN\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gy
p.js" "rebuild" "--release"
gyp ERR! cwd D:\My Projects\Dashboard\my-project\node_modules\better-sqlite3
gyp ERR! node -v v18.12.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok

 Keep trying!

**Comment by RajaSharmaIndia** [comment]
@gethushan
same error

**Comment by sobhardwaj** [comment]
> @gethushan
> same error

try out stable version

**Comment by huamurui** [comment]
>prebuild-install warn install No prebuilt binaries found (target=18.12.0 runtime=node arch=x64 libc= platform=win32)

    better-sqlite3@7.4.6 build-release

I had met the same, I not sure...but I notice they're checking node version,maybe some dependences do not have a adaption to the new version of node.

So, I change my node version from 18 to 16 and the problem just gone.

**Comment by StrapiShaun** [comment]
A related issue in the docs repo: https://github.com/strapi/documentation/issues/1438

**Comment by sobhardwaj** [comment]
I got the same issue, I remove better-sqlite3 from package.json it working fine then.

**Comment by mpstaton** [comment]
This is pretty discouraging.  I don't understand why they don't just say in their documentation how to force install dependencies.  React isn't even listed in the dependencies.

4:16:40 ~/code/colearn/contentGraph master $ yarn develop   
yarn run v1.22.19
warning ../../../package.json: No license field
$ strapi develop
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/dist/cli.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/index.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/commands/index.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/cli.js
- /Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/bin/strapi.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js:15:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/dist/_chunks/index-sNH2VWbC.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/dist/cli.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/admin/index.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/action.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/commands/actions/watch-admin/command.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/commands/index.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/dist/cli.js',
    '/Users/mps/code/colearn/contentGraph/node_modules/@strapi/strapi/bin/strapi.js'
  ]
}

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:17:08 ~/code/colearn/contentGraph master $ yarn install --dev
yarn install v1.22.19
warning ../../../package.json: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.36s.
