### ISSUE TITLE
no validation in api generation cli

### ISSUE THREAD

**Issue by Bokitza** [strapi/strapi#15521]
### Required System information

- Node.js version: 16.0.0
- NPM version:7.10.0
- Strapi version: 4.5.6
- Database: PG
- Operating system: MacOS

### Describe the bug

When doing ```npm run strapi generate``` an API and choosing a camelcase name for your api - it won't validate you - yet the server will fail running.

### Steps to reproduce the behavior

1. try generate a new api with the cli
2. call it thisIsACamelCaseExample
3. go npm run strapi develop

### Expected behavior

validate me to be kebab case (:

### Screenshots

<img width="560" alt="image" src="https://user-images.githubusercontent.com/58147254/213889488-69edb19a-2d4d-4ad0-a57c-efc0b75621c4.png">

**Comment by alexandrebodin** [comment]
Hi, doing some cleanup, I confirm this is fixed in the latest version.
