### ISSUE TITLE
Having a content-type with the name `then` causes Strapi to be unable to start

### ISSUE THREAD

**Issue by JosephCarrington** [strapi/strapi#15557]
## Bug report
Having a content-type with the name `then` causes Strapi to be unable to start

### Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Strapi version: 4.5.6
- Database: sqlite
- Operating system: OSX

### Steps to reproduce the behavior

Using the Content-Type Builder
1. create a new content type with the Display name `Then`
2. Add a text field called `Title`
3. Save the content-type

Strapi will be unable to restart and emits the following error:
```
[2023-01-24 12:07:35.671] debug: ⛔️ Server wasn't able to start properly.
[2023-01-24 12:07:35.673] error: Cannot read properties of undefined (reading 'contentType')
TypeError: Cannot read properties of undefined (reading 'contentType')
    at Object.then (.../node_modules/@strapi/strapi/lib/factories.js:12:27)
```

### Expected behavior

I expected Strapi to restart and use my new content type

### Additional context

Having chatted with the folks on open office hours in Discord, the idea seems to be that `then` is a reserved word either in sqlite  or Strapi itself. We chatted about not allowing a user to enter a reserved word as an api name through the editor.

**Comment by Boegie19** [comment]
I can confirm and replicate the issue with replications staps

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1198
