### ISSUE TITLE
Can not get relation of plugin's content-type from api

### ISSUE THREAD

**Issue by thongbn** [strapi/strapi#15567]
### Required System information
- Node.js version: 16-apline
- NPM version: yarn
- Strapi version: 4.5.6
- Database: maria 10.6
- Operating system:

### Describe the bug

Can not get relation of plugin's content-type from api

### Steps to reproduce the behavior
1. Create Content type in Plugin, and its appeared in Colletion types, full function
![image](https://user-images.githubusercontent.com/14286010/214540172-98595ccc-dca6-4cad-9e0d-eec06bc40034.png)
2. Add Relation in 1 of api content type, Relation appeared in content-type, can save , remove 
![image](https://user-images.githubusercontent.com/14286010/214540326-85dc9a77-b3f5-4704-90d1-bcb38348e138.png)
![image](https://user-images.githubusercontent.com/14286010/214540458-a115026b-6e42-44c1-9c34-f3e6ac36dbaf.png)
3. Call api with populate field but no relation of plugin returned (other relation "api::" work-well
![image](https://user-images.githubusercontent.com/14286010/214540719-4829869f-827d-46f0-a8af-ec0a243e53e9.png)

**Comment by thongbn** [comment]
To make it clear
I have api::tours:tours created by content builder
and plugin::payment-vns.payment-product created in plugin
1 Tour have 1 relation (one-to-one) with payment-product
And i need get payment-product when get Tour via Api

**Comment by petersg83** [comment]
How do you authenticate with the API ? With `API Token` or with `Users&Permission`? Can you check that you correctly gave permission to get the payment product content-type ?
