### ISSUE TITLE
Add MariaDB in github action tests

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#15573]
## Issue description

In the past months we have seen a raising number of issues related to the database layer in strapi.

Examples:
https://github.com/strapi/strapi/issues/15558
https://github.com/strapi/strapi/issues/15246
https://github.com/strapi/strapi/issues/15202
https://github.com/strapi/strapi/issues/15539

Making changes in the db layer proved to be challenging and tedious. Because of the fact Strapi supports many DBs (sqlite, postgres, mysql, mariadb and soon cockroach db) and some of them might behave a little bit different.

We are only testing for Sqlite, Postgres & Mysql (version 8)
And some of the issues could have been prevented by testing using those DBs in the first hand.

This issue aims to open the discussion of if we should add more DBs into the github action matrix such as:
- Maria DB
- DBs using clustering

It would be worth mentioning that right now Github Actions are taking a bit too long to run, and we should fix that before adding those.

ping @derrickmehaffy @Boegie19

**Comment by Boegie19** [comment]
I think we could as a temp workaround until 

> It would be worth mentioning that right now Github Actions are taking a bit too long to run, and we should fix that before adding those.

is fixed we could maby tag a pr with a spesific lable what willl run all the extra tests only for that spesific pr. all prs that touch database need to do that.

**Comment by derrickmehaffy** [comment]
I know something we have discussed in the past too was running some of our own self-hosted GitHub actions runners in our own AWS infra (ideally an isolated account away from our other production applications).

I think some of the time our tests take so long as we have to wait in the queue for the public runners shared by all GitHub users.

**Comment by Boegie19** [comment]
I agree the queue can like take 10 a 15 minutes plus the longest test taking 45 minutes is 1 hour what could have been 45 minutes. still my question would be would that be worth the cost of hosting it on aws?

**Comment by Boegie19** [comment]
Also adding more dbs should only increase the waiting time for waiting for a available GitHub server this would impect waiting time until done but not testing time.

**Comment by petersg83** [comment]
MySQL 5 is already tested actually :)

**Comment by alexandrebodin** [comment]
going to close this now that mysql is being dropped and EOF ;)
