### ISSUE TITLE
Lower case email while registering ( Local Auth )

### ISSUE THREAD

**Issue by anshulk** [strapi/strapi#1557]
**What is the expected behavior?**
Using local auth, I expected email to be changed to lowercase while registering too, which is not happening.

Had a look at Auth.js. Are [these lines](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L259-L264) required. Can they be replaced by lowercasing email instead ?

Also in my case, newly registered users were not able to login via email, only via name. I had to check "getRole" in UserPermissions from the admin dashboard's Roles and Permissions for Authenticated users. 
Is this desired behaviour ?

**Comment by Aurelsicoko** [comment]
Yes, we should lowercase the email because an email isn't case sensitive. Can you make a PR? We would love merge it 👍

**Comment by SK-Commit** [comment]
When a user is created with an uppercase letter like "testMail@test.com", it's not possible to authenticate through "/auth/local" endpoint in alpha 25.2. @lauriejim @Aurelsicoko
