### ISSUE TITLE
TS: QueryFromContentType<"plugin::categorizer.category">.count(params: any) - params should be optional.

### ISSUE THREAD

**Issue by antokhio** [strapi/strapi#15586]
## Bug report
Seems a typo in TS:
```ts
(method) QueryFromContentType<"plugin::categorizer.category">.count(params: any): Promise<number>
```
results: 
```await strapi.db.query("plugin::categorizer.category").count(undefined)```

however: 
```await strapi.db.query("plugin::categorizer.category").count()```

should work

### Required System information

- Strapi version: 4.6.0

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/15225
