### ISSUE TITLE
Cron Enabled By Default

### ISSUE THREAD

**Issue by Cpaczek** [strapi/strapi#15588]
### Required System information

- Node.js version: v16
- Strapi version: v4.6.0
- Database: sqlite
- Operating system: windows

### Describe the bug

Should cron enabled by default?
https://github.com/strapi/strapi/blob/a9e55435c489f3379d88565bf3f729deb29bfb45/packages/core/strapi/lib/Strapi.js#L433-L436
 I think the check should go inside of here should it not?
https://github.com/strapi/strapi/blob/59b83c59534de5ef728059f32be5ebb994242ddc/packages/core/strapi/lib/services/cron.js#L11-L15
Even if cron is disabled explicitly a plugin could still do strapi.cron.add and bypass that. or is this indented behavior for the telemetry cron?

If not I can open a PR to fix it.

**Comment by petersg83** [comment]
It has to be check but I think it is an intended behavior. The logic is that the user can disable its own `cron` tasks but not the others, if a plugin uses `cron`, it's its responsability to provide a config that impact this own `cron` logic.
