### ISSUE TITLE
Default value of an enumeration is set to null using strapi admin ui.

### ISSUE THREAD

**Issue by npjonath** [strapi/strapi#1558]
**Informations**
Node: v10.6.0
npm: 6.1.0
strapi: 3.0.0@alpha-12.7
database: mongo
os: mac os / ubuntu 16.04 LTS

**What is the current behavior?**
When setting the initial value of an enum to a table through strapi admin UI. the default value is saved as null. When I try to set another value it's working.

**Steps to reproduce the problem**
1 - Create new table with an enumeration (STARTED,STOPPED)
2- Create an entry for table (don't change the default value of the enumeration), save it.
3- Query through graphql or REST. It return null.
4- Go back and edit the enumeration value. save it.
5- Query return the correct value.

**What is the expected behavior?**
Save the default value of the enum field.

**Suggested solutions**
No.

**Comment by derrickmehaffy** [comment]
@npjonath you need to set the default value, as with an enum the value could be null

**Comment by npjonath** [comment]
Ho Alright, my bad. It's working now. thanks
