### ISSUE TITLE
Allow GraphQL paging using cursors

### ISSUE THREAD

**Issue by download13** [strapi/strapi#1559]
Pagination using `start` and `limit` work well for small collections, but querying large datasets will eventually require the ability to paginate using cursors.

You can see in the [OpenCRUD specification](https://github.com/opencrud/opencrud/blob/master/spec/2-relational/2-2-queries/2-2-1-toplevel.md#example) they allow using `after` or `before` as cursor parameters that enable efficient traversal of large result sets.

This feature request may be redundant if #1057 gets implemented first, but if you guys were planning on doing incremental feature additions to the GraphQL plugin, this would be a great one to have.

Thanks!

**Comment by lauriejim** [comment]
Hello @download13 . Can you write this message in #1057 issue please.
It's same topic so I close this issue.

**Comment by n8tb1t** [comment]
So, currently there is no an efficient way to fetch data with cursor and build infinite scroll pagination.

**Comment by lauriejim** [comment]
You will have to use the `_limit` & `_start` to deal with pagination.

**Comment by GabrielLiade** [comment]
hey ! How did you do to implement an infinite scroll with only start and limit ? thank you

**Comment by JiboStore** [comment]
@GabrielLiade you can check out this post:
https://strapi.io/blog/pagination-in-strapi-using-graph-ql

But using start and limit (offset based approach in that article), we'll be in trouble if new records are inserted / deleted between our paginated query.

That article shows cursor based solution but I didn't see it in my schema and thus cannot specify the cursor, I wonder if there is any setting to enable it
