### ISSUE TITLE
Blueprints findOne by attribute not worked correctly

### ISSUE THREAD

**Issue by sbacem** [strapi/strapi#156]
I used this 
localhost/category?ref=mod-formation
But not working, i hase all category list

**Comment by Aurelsicoko** [comment]
I need more information to know what happened. Are you sure your app is running on port 80? Moreover, can you show me the controller on which the `/category` route is pointed to?

**Comment by sbacem** [comment]
@Aurelsicoko 
yes my server is running on port 80
it work because if i use
`localhost/category?where={"ref":["mod-formation"]}`
i have a good result but with array 
for this i used 
`localhost/category?ref=mod-formation`
to get one category
but the filtre `ref=mod-formation` not work i have all category
i generates api category by cli, i use default controller

**Comment by Aurelsicoko** [comment]
Can you log `this.params` in your controller and show me the results? The value should be `{ref: 'mod-formation'}`.

Then, can you try to hard code this in your controller? And show me the results too? 
````
Category.find({ref: 'mod-formation'}).exec(function (error, categories) {
   console.log(categories);
});
```

**Comment by sbacem** [comment]
i try it, the results 

```
[ { createdBy: '57f7a3f27d09c6e209ca49fb',
    updatedBy: '57f7a3f27d09c6e209ca49fb',
    createdAt: '2016-10-14T20:51:41.144Z',
    title: 'Module Formation',
    description: 'Cette catégorie pour le module Nos Formations',
    updatedAt: '2016-10-17T19:41:14.551Z',
    alias: 'mod-formation',
    ref: 'mod-formation',
    id: '58014585aca5495104c2f6a6' } ]
```
i try also it `findOne` work fine

**Comment by Aurelsicoko** [comment]
You missed the first log. What's the value of `this.params` when you request the URL `localhost/category?ref=mod-formation`?

**Comment by sbacem** [comment]
Sorry.
I set in find action 
```
  find: function * () {
    console.log("Params : ");
    console.log(this.params);
    this.model = model;
    try {
      let entries = yield strapi.hooks.blueprints.find(this);
      this.body = entries;
    } catch (err) {
      this.body = err;
    }
  },
```
The results
```
Params : 
{}
```

**Comment by Aurelsicoko** [comment]
Thanks! Sorry, but I need to understand why your URL doesn't work. Can you log `this.query` instead of `this.params`? Moreover, what's the results if you do this:

````
 find: function * () {
    ...
    try {
      let entries = yield strapi.hooks.blueprints.find({ref: 'mod-formation'});
      this.body = entries;
    } catch (err) {
      this.body = err;
    }
  }
```

PS: I know this is not the solution. I just want to know if the issue is related to the blueprint method or to the parameters sent to it.

**Comment by sbacem** [comment]
This is my action 

```
  find: function * () {
    console.log("Query : ");
    console.log(this.query);
    this.model = model;
    try {
      let entries = yield strapi.hooks.blueprints.find({ref: 'mod-formation'});
      this.body = entries;
    } catch (err) {
      this.body = err;
    }
  },
```
In log result 
```
Query : 
{ ref: 'mod-formation' }
```
In navigateur
`{}`

**Comment by Aurelsicoko** [comment]
@sbacem Thanks! So, I watched into the code. As I suspected, you have to define your criteria into a `where` key. If not, the criteria will not be considered.

```js
// Look up the model.
const Model = actionUtil.parseModel(_ctx);

// Init the query.
let query = Model.find()
  .where(actionUtil.parseCriteria(_ctx))
  .limit(actionUtil.parseLimit(_ctx))
  .skip(actionUtil.parseSkip(_ctx))
  .sort(actionUtil.parseSort(_ctx));
```

If you don't want to, you should use the native Watermine methods `Category.find(...).exec(...);` instead.

**Comment by sbacem** [comment]
Thanks @Aurelsicoko 
I hope that this type of option we have in strapi v3
