### ISSUE TITLE
Fatal error on import: Invalid schema changes detected during integrity checks

### ISSUE THREAD

**Issue by niklasfjeldberg** [strapi/strapi#15616]
### System information
- Node.js version: 16.19.0
- NPM version: 9.3.1
- Strapi version: 4.6.0
- Database: SQLite
- Operating system: Windows 11 Home, 22H2 22621.1194

### Describe the bug
When trying to use the new import future of Strapi 4.6.0 I get the error below. This is with barebone Strapi, and with a single content type and a few records, nothing else and no plugins.

```
error: [FATAL] Invalid schema changes detected during integrity checks (using the strict strategy). Please find a summary of the changes below:
- admin::permission:
  - Removed ""
- admin::user:
  - Removed ""
- admin::role:
  - Removed ""
- admin::api-token:
  - Removed ""
- admin::api-token-permission:
  - Removed ""
- api::test.test:
  - Removed ""
- plugin::upload.file:
  - Removed ""
- plugin::upload.folder:
  - Removed ""
- plugin::users-permissions.permission:
  - Removed ""
- plugin::users-permissions.role:
  - Removed ""
- plugin::users-permissions.user:
  - Removed ""
- plugin::i18n.locale:
  - Removed ""
```

### Steps to reproduce the behavior

1. Install a new instance of the latest Strapi version.
2. Make a simple content type and some records.
3. Export the data with `npm run strapi export -- --file test --no-encrypt`.
4. Add a few records.
5. Import the old data with `npm run strapi import -- -f test.tar.gz`.

### Expected behavior
The data should be successfully imported.

### Additional context
I have the issue with Yarn also, and I have tried to import the data to an empty and new Strapi instance, but I have the same issue. I have also experienced the issue with a PostgreSQL database.

**Comment by niklasfjeldberg** [comment]
There is more people who are experiencing this issue, from the [Strapi forum](https://forum.strapi.io/t/data-import-fatal-error-on-4-6-0/25285/3).

**System info**:
Strapi version: 4.6.0
Operating System: Windows 10 22H2
Database: SQLite
Node Version: 16.14.0
NPM Version: 8.3.1

![2096274ee455d5824059fd5c55715e039acc3b42](https://user-images.githubusercontent.com/1756738/215272989-3e31656e-6deb-4e2c-b160-082ae479b751.png)

**Comment by xmak** [comment]
I'm having a similar issue, here are the details with steps to reproduce and an archive with my project code:

https://forum.strapi.io/t/data-import-fatal-error-on-4-6-0/25285/6

**Comment by Convly** [comment]
Hi @niklasfjeldberg / @xmak, does this still happen to you on 4.8.2?

**Comment by niklasfjeldberg** [comment]
@Convly sorry I wrote the wrong version in my comment. Yes, this does happen on v4.8.2.

**Comment by derrickmehaffy** [comment]
related to: https://github.com/strapi/strapi/pull/16268
