### ISSUE TITLE
Type ralation in repeatable component is not possible when attaching the component to a collenciton type

### ISSUE THREAD

**Issue by ds-georgiev** [strapi/strapi#15628]
### Required System information

- Node.js version:  **18.12.1**
- NPM version: **8.19.2**
- Strapi version:v **4.5.2**
- Database: **postgres**
- Operating system: **macOS: 13.2 (22D49)**

### Describe the bug

Repeatable component containing type **Relation** resolves to white page when added to a Collection Type.

### Steps to reproduce the behavior

1. Go to *Content-Type Builder*
2. Create a repeatable component (child)
3. Add  two fields: Text field, Relation field
4. Create a non repeatable component
5. Add the child component form step 2 as part form the parent
6. Create a *Collection type* : Page (for example)
7. Go to the *Content Manger*
8. Add the parent component to the collection type create in step 6
9. **White page will occur**
10. Go back to the child component in step 2 and make it **NON** repeatable
11. Go to the *Content Manager*
12. Add the parent component to the collection type create in step 6
13. **It will work since the child component that contains the *Relation* field is not repeatable**

### Expected behavior

One should expect to have a repeatable component that contains a Relation field and use it in a Collection type within the Content Manager context.

Example we have a **Team** that contains a **Team Members** which are part from the Connection Type **Persons**. That means that one will be able to create a team and add multiple team members to that team.

### Screenshots
The only error that is shown in the console is:

![image](https://user-images.githubusercontent.com/60659565/215443944-406cc52c-5c6c-4d20-be13-0dfff8255f49.png)

### Code snippets

The *Team-member* component :
`{
  "collectionName": "components_components_team-member",
  "info": {
    "displayName": "TeamMember",
    "icon": "align-justify",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "component",
      "required": true,
      "component": "components.title"
    },
    "content": {
      "type": "component",
      "repeatable": false,
      "component": "components.title",
      "required": true
    },
    "person": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::person.person"
    }
  }
}`

The *Team* component:

`{
  "collectionName": "components_components_team-carousel",
  "info": {
    "displayName": "TeamCarousel",
    "icon": "file"
  },
  "options": {},
  "attributes": {
    "subTitle": {
      "type": "component",
      "repeatable": false,
      "component": "components.title"
    },
    "title": {
      "type": "component",
      "repeatable": false,
      "required": true,
      "component": "components.title"
    },
    "items": {
      "type": "component",
      "repeatable": true,
      "required": true,
      "component": "components.team-member"
    }
  }
}
` 

### Additional context

It is all possible that I am not doing something in a proper way. But once the ` "repeatable": true,` is removed from the `  "component": "components.team-member"` all works like a charm. But unfortunately the situation requires that `repeatable` to be there.

**Comment by joshuaellis** [comment]
I believe we solved this issue in a more recent release. Please try upgrading & rebuilding your admin panel. If the issue persists please open a new issue with a minimal reproduction guide related to the latest release. Thank you!
