### ISSUE TITLE
Delete function is not correct

### ISSUE THREAD

**Issue by huybuidac** [strapi/strapi#15624]
https://github.com/strapi/strapi/blob/a3ff110fc401ef4fbd6cd90780bf87a83a2cb04b/packages/core/database/lib/entity-manager/index.js#L381

```ts
      await this.createQueryBuilder(uid).where({ id }).delete().execute();
```

The `Delete` function does not check whether the record is really deleted or not.

I think we have to check count as below

```ts
const count = await this.createQueryBuilder(uid).where({ id }).delete().execute();
const deleted = count === 1;
```

**Comment by theVJagrawal** [comment]
Can I work on this one?
