### ISSUE TITLE
Strapi Deep Filtering issue

### ISSUE THREAD

**Issue by red1** [strapi/strapi#15622]
## Bug report
When I try to filter my articles that have a specific tag I try using the deep filtering capability of strapi 
Ex: run on the strapi blog starter 
`http://127.0.0.1:1337/api/articles?categories[slug][$eq]=test-2&populate[categories][populate]=*&pagination[page]=1&pagination[pageSize]=25&sort[0]=publishedAt:desc
`
this is including articles with categories empty

### Required System information

- Node.js version: Node.js v18.13.0
- NPM version:   npm: '8.19.3',
- Strapi version: v4.6.0
- Database: sqlite
- Operating system: Mac OS Monterey

### Steps to reproduce the behavior

1. launch strapi nextjs blog starter
2. tag some content with a category, and others without catgories
3. Go to 'http://127.0.0.1:1337/api/articles?categories[slug][$eq]=test-2&populate[categories][populate]=*&pagination[page]=1&pagination[pageSize]=25&sort[0]=publishedAt:desc'
4. See that content without categories are being surfaced

### Expected behavior
Only articles with the desired category slug should appear in the response of the API

**Comment by red1** [comment]
anyone can help please ?

**Comment by red1** [comment]
@derrickmehaffy why did you closed this bug? It's not a question, it's a real big i provided steps to reproduce the issue

**Comment by red1** [comment]
@derrickmehaffy up ?

**Comment by derrickmehaffy** [comment]
@red1 it's not a bug with main codebase, it's more so of a usage question of our operator filters. Please ask the question in our community spaces.
