### ISSUE TITLE
SQLite database support

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1562]
**What is the expected behavior?**
Hi, I see that Strapi supports [Bookshelf](http://bookshelfjs.org/) and It's support SQLite too. Is it possible to use Strapi with SQLite?
I can't find any information about this in docs.

**My feature request is:** SQLite docs or SQLite database support.

It can be very useful specially as a **default database** for development environment. 
Please add this to https://strapi.io/vote page if you agree with my suggestion. :wink:

**Comment by Aurelsicoko** [comment]
@mnlbox We removed the support because it was the cause of a lot of bugs. It seems that Bookshelf doesn't support well SQLite... We could try to reintroduce it as an official supported database, but we should hard-test it before.

**Comment by mnlbox** [comment]
@Aurelsicoko any news about add this to roadmap?

**Comment by Aurelsicoko** [comment]
I added it on Product Board. Feel free to upvote and give us insights to justify the development of this new database connector (see https://portal.productboard.com/strapi/c/35-support-sqlite-database).
