### ISSUE TITLE
Cannot login via API 

### ISSUE THREAD

**Issue by vladaCizek** [strapi/strapi#15621]
- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.6.0
-  "@strapi/plugin-users-permissions": "4.6.0",
- Database: SQLITE
- Operating system: Window 11

After creating a brand new project and creating a super admin user, I cannot login via api. I can login in the Admin via web interface and everything seems to be working correctly, login via axios or postman on http://localhost:1337/api/auth/local always returns:

```
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "Invalid identifier or password",
        "details": {}
    }
}
```
The  check if user exists in "@strapi/plugin-users-permission/server/controllers/auth" always returns null/
Line 53

```
// Check if the user exists.
  const user = await strapi.query('plugin::users-permissions.user').findOne({
    where: {
      provider,
      $or: [{ email: identifier.toLowerCase() }, { username: identifier }],
    },
  });
```

### Expected behavior

User should get authenticated and the response should return {jwt, user} objects.

The same issue has been previously described in https://github.com/strapi/strapi/issues/13817

<img width="721" alt="image" src="https://user-images.githubusercontent.com/64841591/215356632-0137cab6-f488-47b4-9e7b-cbbd17346548.png">

**Comment by smoothdvd** [comment]
auth api only working for normal user, not for users in administrator group(Super admin, editor, author)

**Comment by derrickmehaffy** [comment]
> auth api only working for normal user, not for users in administrator group(Super admin, editor, author)

Exactly as mentioned, we have two entirely different user sets for the content API and admin APIs that cannot auth each other.

**Comment by Weeks2** [comment]
<img width="1462" alt="Screenshot 2023-07-09 at 23 36 37" src="https://github.com/strapi/strapi/assets/106888385/2680dd00-29e9-4f59-9ea2-84205d461955">
<img width="935" alt="Screenshot 2023-07-09 at 23 36 19" src="https://github.com/strapi/strapi/assets/106888385/d705603a-8c8a-491f-96a9-8f35c3763c8b">

**Comment by alejandrojosue** [comment]
Cuál versión está usando? Actualmente estaba utilizando la versión 4.12.1 y no me permitió hacer login en POSTMAN, actualicé a la actual (4.13.1) y tampoco. Lo probé a ver si estaba haciendo mal con otro proyecto que tiene la versión 4.10.1 y si funcionó.
Luego instalé swagger (estando en el proyecto con la versión 4.13.1) para probarlo desde ahí. Abrí la documentación swagger generado del proyecto y lo ejecuté desde ahí. No funciona, siempre me dió el mismo error:
{
  "data": null,
  "error": {
    "status": 400,
    "name": "ValidationError",
    "message": "2 errors occurred",
    "details": {
      "errors": [
        {
          "path": [
            "identifier"
          ],
          "message": "identifier is a required field",
          "name": "ValidationError"
        },
        {
          "path": [
            "password"
          ],
          "message": "password is a required field",
          "name": "ValidationError"
        }
      ]
    }
  }
}

**Comment by ihor-zinchenko** [comment]
i hhave the same thing but for not existing user, what can be the reason? I believe i need to get some human error but instead i getting 500
