### ISSUE TITLE
Relation fields hidden by default

### ISSUE THREAD

**Issue by benrychter** [strapi/strapi#15631]
### Required System information

- Node.js version: Docker `16.17-alpine`
- NPM version: `8.15.0`
- Strapi version: `4.6.0`
- Database: `postgres:13.6-alpine`
- Operating system: Docker `node:16.17-alpine`

### Describe the bug

After updating from `4.4.5` to `4.6.0,` all relational fields that normally have been in the right column of a specific collection type are now hidden. It happened only for previously created and settled Collection Types. To get the Relation field back, I need to go to the "Configure the view" page and manually add this field by clicking "Insert another field" and moving it to the proper place. 

But when I'm creating a new Collection Type (just for testing), the relation field is showing without any described actions. It just is on the entity page.

**Comment by derrickmehaffy** [comment]
This was most likely related to the fact we moved relations to the main view so the views were not updated properly.
