### ISSUE TITLE
Using draft and publish in a content-type where a component has a unique field causes a validation error

### ISSUE THREAD

**Issue by RafaelMarinho96** [strapi/strapi#15636]
### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.5.0
- Database: Mysql
- Operating system: Linux Ubuntu

### Describe the bug

I had opened a bug report `https://github.com/strapi/strapi/issues/15481` and the issue was closed in favor of  this feature request `https://feedback.strapi.io/feature-requests/p/lifecycle-hooks-for-components`.

But this behaviour where components are inserted in database before validate a content-type causes a bug when using draft/publish feature.  When a component field has the attribute unique i can't save and publish correctly, because the save button insert the component on database and when I click on publish the application will try to check if the field has a unique value but due to the previous insertion this validation will always fail.

### Steps to reproduce the behavior

1. Create a content-type
2. Create a component with a unique field in content-type
3. Enable draft/publish on content-type
4. Fill the content-type and the component 
5. Click on save and then in publish (the validation should failed because the unique field was inserted on save step)

### Screenshots

https://user-images.githubusercontent.com/20724574/215505728-661c0612-0f6f-4959-ac57-f6c5212d2711.mp4

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Masvi** [comment]
is there some  idea about when this problem is gonna be solved?

**Comment by derrickmehaffy** [comment]
Raised sev due to it being from an EE customer

**Comment by RafaelMarinho96** [comment]
**update:** I notice this bug also happen when have the draft and publish feature disable, we tried to update any value in a collection type with has a component with unique value enable and we have the same scenario.

**Comment by derrickmehaffy** [comment]
We (the Strapi support team) have raised this topic directly with our product team who are gonna be taking a deeper look at soon. I believe the topic is more so around how uniqueness should work for various features and not just components.

**Comment by Marc-Roig** [comment]
Closing it in favor of https://github.com/strapi/strapi/issues/12541
