### ISSUE TITLE
ServerError: Inconsistent handling of invalid input

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#15648]
Please try understanding the severity of this issue for running Strapi in production.

### Required System information

Node.js version: 16.14.2
NPM version: 8.5.0
Strapi version: 4.6.0
Database: Postgres
Operating system: Ubuntu 20.04

### Describe the bug

Currently, wherever API data is checked 'manually' and not through the validation mechanism, the default behaviour is throwing a server error. A small excerpt:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/11761828/215775133-ff603879-2306-4e4d-acbd-b0a545835fd2.png">

This leads to two problems: 

1. How is a frontend supposed to know what the issue with some user's input is, if the only reply is a 500 server error? Is it a bug in the code my client's users should report to us, or was there just some issue with a wrong password? 

2. If you throw an error right away every time some user enters a wrong password, your event monitoring tool will look like this and it's impossible to filter out real issues: 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/11761828/215777174-f7c60454-0a8f-495a-acdd-104c28a0ee69.png">

### Expected behaviour

No errors thrown when there isn't actually something _failing_. The correct thing to do here is a proper HTTP response, ideally formatted the same way as the regular validation errors.

Come on guys, I see the amount of hard work you've put in this awesome project, don't let bad execution of basic practices overshadow all the hard effort. 🙏

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/error-codes

Thanks!

**Comment by nikita-fuchs** [comment]
Hey, I made a quick video about the severity of this: https://www.youtube.com/watch?v=bCPx2WE_bus

I also wouldn't call this a feature request, because the user (developer), whose perspective a product needs to be seen from, is used to getting the properly formatted error responses for faulty input data from strapi's content api. And suddenly getting a server error in the same situation is clearly a bug at first glance. One cannot expect users to guess or know that responding to 37 different cases of malformed input at specific certain spots was a deliberate choice made at some point. And at least living up to HTTP status code  practices serving proper 4xx when some password was forgotten instead of everything being a server error is really not an 'enhancement' or feature request.

**Comment by nikita-fuchs** [comment]
hey, @derrickmehaffy sure, done.

**Comment by nikita-fuchs** [comment]
Hey, after 1,5 years https://github.com/strapi/strapi/blob/a64ced5364618f917adb31b8684b4e3c01c58862/packages/plugins/users-permissions/server/controllers/auth.js is still filled with Erorrs being thrown for basic things instead of returning proper API responses, e.g.:

https://github.com/strapi/strapi/blob/a64ced5364618f917adb31b8684b4e3c01c58862/packages/plugins/users-permissions/server/controllers/auth.js#L65-L66

The error log console of my google cloud deployment is clogged with errors for failed logins, can't activate notifications to my mobile phone to be notified about actual errors. I've patched things myself with 

```
 if (!user) {
        // throw new ValidationError('Invalid identifier or password');
        return this.respondWithError(ctx, 'provider', 'This provider is disabled');
      }
      ``` 
      
      using 
      ```
  respondWithError(ctx, path, message) {
    return ctx.send(
      this.generateValidationErrorResponse(
        [this.generateValidationError(path, message)]
        ));
  },

  generateValidationErrorResponse(errors) { 
    return {
      "data": null,
      "error": {
          "status": 400,
          "name": "ValidationError",
          "message": `${errors.length} errors occurred"`,
          "details": {
              "errors": [...errors]
          }
      }
  }
  },  

   generateValidationError(path, message) {
    return {
      path: [path],
      message,
      name: 'ValidationError'
    }},

```
      Feel free to copy this or just take it as an example, but this really needs to be fixed, shouldn't take more than 2h !

**Comment by nikita-fuchs** [comment]
@derrickmehaffy can't help but to ask to reopen? This is really against common best practices and makes strapi really hard to run and monitor, driving any devops insane.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy can't help but to ask to reopen? This is really against common best practices and makes strapi really hard to run and monitor, driving any devops insane.

Given how old this is, it would be better to open a new one, specifically if it can be validated on the v5 beta. At best this would be a medium sev and medium sev bugs most likely won't be fixed on v4

**Comment by nikita-fuchs** [comment]
Given the time we've waited for this to be fixed it's okay to wait a little longer for it to be tackled in v5, _soon_ ;)

It definitely seems to be applicable to v5, just a quick glimpse shows many cases: 
<img width="647" alt="image" src="https://github.com/strapi/strapi/assets/11761828/1b4accb3-15dc-4532-a347-7f7ccb6d7762">
