### ISSUE TITLE
stapi (4.6.0) does not apply changes from extensions directory

### ISSUE THREAD

**Issue by valeriiBerezhniyCollab** [strapi/strapi#15641]
I`m trying to extend default users-permissions plugin.
Do all documentation things, even copy all plugin files from vendor to ext dir, but nothing happens.
using:
- yarn as packet manager
- typescript
- ubuntu 22.04
- node 18.13.0

**Comment by nikita-fuchs** [comment]
I'm not sure if this is your intended approach, but this is how I did it: 

1. create `src/extensions/users-permissions/strapi-server.ts`
2. put 
```
module.exports = (plugin) => {
console.log(plugin)
}

and there you will see all controllers and what not. You can import all sorts of utils and services to use them in there, here are the ones I use:
```
import { Strapi } from '@strapi/strapi';
import * as Koa from "koa"
import * as hooks from './content-types/user/lifecycles';
import { check2FAtoken, eventuallyGenerate2FA } from './content-types/user/twoFA';
const utils = require('@strapi/utils');
const _ = require('lodash');
const { ApplicationError, ValidationError } = utils.errors;
const {  validateCallbackBody } = require('@strapi/plugin-users-permissions/server/controllers/validation/auth.js');
const { getService } = require('@strapi/plugin-users-permissions/server/utils')
const { getService: getAdminService } = require('@strapi/admin/server/utils')
const { respondWithError } = require('./utils')
```
(`respondWithError`,  `'./content-types/user/lifecycles'`;  and `./content-types/user/twoFA` are custom ones written by me 😉)

**Comment by valeriiBerezhniyCollab** [comment]
Thanks, you save my day! This is solution :)
