### ISSUE TITLE
Relationships don't update on locale change within admin panel

### ISSUE THREAD

**Issue by gfragioud** [strapi/strapi#15646]
### Required System information

- Node.js version: 14.21.2
- NPM version: 6.14.17
- Strapi version: 4.6.0
- Database: postgres 14
- Operating system: linux

### Describe the bug

I view a localized entity in admin panel that has localized relationships. I switch to another locale and everything is updated with the appropriate localized values except the **lazy loaded** relationships. I still see the items of previous locale.

Just to mention that if the relationship field is in the top of the page then it works as expected.

### Steps to reproduce the behavior

1. Enable internationalization and add at least two locales.
2. Create a localized collection (let's call it "child") and create an entity in all locales.
3. Create another localized collection or single type (let's call it "parent") with lots of fields and as last field a relationship to "child" collection.
4. Fill all fields in "parent" and set the relation field in all locales and save.
5. View again the "parent" in any locale and scroll down to view the relations. All good until now.
6. Switch to the other locale and scroll down again.
7. You still see the previous relations.

If you refresh the page, the correct relations are displayed.

### Expected behavior

Relations should be reloaded after every locale change.

**Comment by jonadeline** [comment]
#15506 relates the same kind of issue as well.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/12538
