### ISSUE TITLE
Keep dynamic zone accordions closed by default

### ISSUE THREAD

**Issue by MotaZor94** [strapi/strapi#15655]
Hi, I know this is not an issue but it seems like a really nice feature which I can't seem to find. 

It would be really good to have all the accordions in the dynamic zone closed by default even if they have content inside of them. 

I think it's much easier to search for things when you have all the accordions closed.

Is it possible to do this somehow?

<img width="788" alt="Screenshot 2023-01-31 at 17 31 25" src="https://user-images.githubusercontent.com/45624002/215822404-82295431-dd8e-4a30-a013-c7e2a4a98cbc.png">

**Comment by benrychter** [comment]
Definitely! It should behave exactly like in previous versions (before `4.6.0`).

**Comment by Xzandro** [comment]
I agree, or rather buttons should be added to collapse/expand all components. I think they changed it some time in v4.5.x. Especially for dynamic zones with lots of components, this state is really tough to deal with, more so now that you can change the order with drag&drop, which would highly improve from all collapsed components as well.
