### ISSUE TITLE
customFields are not loaded if another customField was loaded before by lazy loading

### ISSUE THREAD

**Issue by ekimv** [strapi/strapi#15665]
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.6.0
- Database: MariaDB
- Operating system: Docker on ubuntu

### Describe the bug

When you have multiple customFields in your project and some customFields are used only in some collection types, if you navigate to another collection type with another customField, the new customField won't be loaded... like if the useLazyComponents was loaded only once
I have 2 custom fields with plugins : One custom for GPS localisation and one for color picker

### Steps to reproduce the behavior

1. Create a type with a customField color picker
2. Create another type with both the customField colorPicker and another customField (multi picklist for example)
3. Go to the first type with only the color picker ; it works
4. Go to the second type with both customFields : only the color picker is shown : the other customField is shown with "Not Supported" field...
5. Refresh the page : both customFields will be loaded and will work

### Expected behavior

All custom fields need to be loaded as needed indepently of the order of the types you access

### Screenshots

![image](https://user-images.githubusercontent.com/75667665/216021612-26f734c8-eee7-4b7f-8713-50c08a5bd452.png)
CustomField correctly loaded when coming directly on my single type

But if I go first to a type with the color picker custom field only, and then I go to the single type with location, the plugin is not loaded :
![image](https://user-images.githubusercontent.com/75667665/216022016-50a60cee-bfda-4487-93c0-b5d47c5bb4cd.png)

**Comment by markkaylor** [comment]
@ekimv I believe 4.6.1 fixed this issue with https://github.com/strapi/strapi/pull/15744. Could you please confirm?

**Comment by ekimv** [comment]
Hello,
Just tested in 4.6.1 and it seems good! Thanks!
