### ISSUE TITLE
stapi connect to a DB, but doesn´t read anything

### ISSUE THREAD

**Issue by F-Y-M** [strapi/strapi#15668]
Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Strapi version: 4.6.0
- Database: MYSQL 8.0.32
- Operating system: ubuntu 22.04.

- Describe the bug
LOCAL 
When I connect to the server, it lets me see the users I have in my BD, it lets me save and everything normal.

actual users
![strapiv4-local-show-users](https://user-images.githubusercontent.com/55666365/216110203-85e8ff0a-32d2-419f-8adb-0034423760a4.png)

creating new user
![strapiv4-local-show-entry-user](https://user-images.githubusercontent.com/55666365/216110134-d408c70d-1de0-4b52-8c92-b6f17504d2fd.png)

showing the new user
![strapiv4-local-show-new-entry-created](https://user-images.githubusercontent.com/55666365/216110292-c657deee-ec70-49af-ac4a-34baa57a41dc.png)

users in BD
![local-users-in-db](https://user-images.githubusercontent.com/55666365/216110382-8029477e-4ccc-40e5-b826-ed75c83f7844.png)
se de datos

PRODUCTION
I run the server and everything seems okay, even at the time of entering a user, and shows that he has stored successfully. But at the time of visualizing the user this does not appear and if I look for it in the database appears

actual users
![strapiv4-prod-show-users-edit](https://user-images.githubusercontent.com/55666365/216115874-9b90f118-793d-46ae-bf06-c559b9458da0.jpg)

creating new user
![strapiv4-prod-show-entry-user-edit](https://user-images.githubusercontent.com/55666365/216116066-27bd9041-6d23-4ec8-bac3-987235aaac4d.jpg)

don´t show any user
![strapiv4-prod-show-users-edit](https://user-images.githubusercontent.com/55666365/216116192-c1a44fcb-dd29-4771-82cd-d1c5b011d714.jpg)

the actual users and
![strapiv4-prod-users-in-db](https://user-images.githubusercontent.com/55666365/216430059-f3189bb5-b85d-400c-b216-32d5aa0d4448.png)
 the new one is in the BD 

Expected behavior
The normal use of the application by creating and visualizing users in the database

 Additional context
MYSQL VERSION: 8.0.32
OS VERSION: .ubuntu 20.04.2

**Comment by Boegie19** [comment]
@F-Y-M Is this issue only for users of for all content types?
Also do you use Typescript or JavaScript 
Does your project information when you restart strapi in the console also say Database MYSQL
![image](https://user-images.githubusercontent.com/34578426/216125815-6bf5cf73-a6bf-4c6a-af12-3cf7f31251b6.png)
When this this issue start for you? I assume after you updated to 4.6.0 what is the version you where on before the update?

**Comment by derrickmehaffy** [comment]
Hello!

To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms. 

Thank you and have a wonderful day!

**Comment by F-Y-M** [comment]
> @F-Y-M Is this issue only for users of for all content types? Also do you use Typescript or JavaScript Does your project information when you restart strapi in the console also say Database MYSQL ![image](https://user-images.githubusercontent.com/34578426/216125815-6bf5cf73-a6bf-4c6a-af12-3cf7f31251b6.png) When this this issue start for you? I assume after you updated to 4.6.0 what is the version you where on before the update?

i had the 4.5.6 version and is using mysql  

![prod-server-shows-strapi](https://user-images.githubusercontent.com/55666365/216150481-101574cd-1a24-4b91-9a97-7858e5b5d601.png)

**Comment by F-Y-M** [comment]
![prod-strapiv4-response-creating-entry](https://user-images.githubusercontent.com/55666365/216152595-bb437db6-7c06-472d-99d8-3caddbbf1974.png)

this is the server answer when i try to create a user

**Comment by F-Y-M** [comment]
> @F-Y-M I'm a bit confused here, the first few screenshots you were working locally correct? In production you are connecting to a different database I assume unless you are also using SQLite in production (which we don't recommend) but your SQLite DB isn't pushed into source control (and shouldn't) so the data held the database is not present on your production application.

i thougth that too, but checking the database (mysql) in production the data is saving but never share in api

**Comment by derrickmehaffy** [comment]
> > @F-Y-M I'm a bit confused here, the first few screenshots you were working locally correct? In production you are connecting to a different database I assume unless you are also using SQLite in production (which we don't recommend) but your SQLite DB isn't pushed into source control (and shouldn't) so the data held the database is not present on your production application.
> 
> i thougth that too, but checking the database (mysql) in production the data is saving but never share in api

What are the permissions set for your DB user?

**Comment by derrickmehaffy** [comment]
> ![prod-strapiv4-response-creating-entry](https://user-images.githubusercontent.com/55666365/216152595-bb437db6-7c06-472d-99d8-3caddbbf1974.png)
> 
> this is the server answer when i try to create a user

Based on the response time from these requests either two things here:

- Your DB is located WAYYYY far away from your Strapi instance
- it is fetching the data (and you have a lot of it)

**Comment by Boegie19** [comment]
@F-Y-M What plugins do you have installed?
Also did this happen 
- randomly
- On install 
- on update

**Comment by F-Y-M** [comment]
> > > @F-Y-M I'm a bit confused here, the first few screenshots you were working locally correct? In production you are connecting to a different database I assume unless you are also using SQLite in production (which we don't recommend) but your SQLite DB isn't pushed into source control (and shouldn't) so the data held the database is not present on your production application.
> > 
> > 
> > i thougth that too, but checking the database (mysql) in production the data is saving but never share in api
> 
> What are the permissions set for your DB user?

this are the db, server and middleware  config file

DATABASE
![database-config](https://user-images.githubusercontent.com/55666365/216430697-9b365b6b-58eb-4f2d-8e5a-1dba816325ab.png)

SERVER
![server-config](https://user-images.githubusercontent.com/55666365/216430761-7ca82fdc-3be8-40ed-87cc-8645a7227170.png)

MIDDLEWARES
![middleware-config](https://user-images.githubusercontent.com/55666365/216431020-b160e7ad-6427-4667-a569-47f1c7bea493.

**Comment by F-Y-M** [comment]
> > ![prod-strapiv4-response-creating-entry](https://user-images.githubusercontent.com/55666365/216152595-bb437db6-7c06-472d-99d8-3caddbbf1974.png)
> > this is the server answer when i try to create a user
> 
> Based on the response time from these requests either two things here:
> 
>     * Your DB is located WAYYYY far away from your Strapi instance
> 
>     * it is fetching the data (and you have a lot of it)

im just create 1 user like sees in this picture

**Comment by derrickmehaffy** [comment]
Is your codebase somewhere we can see it?

**Comment by F-Y-M** [comment]
> @F-Y-M What plugins do you have installed? Also did this happen
> 
>     * randomly
> 
>     * On install
> 
>     * on update

from the strapi marketplace none
from npm "@strapi/provider-email-sendgrid":  "4.6.0",

**Comment by F-Y-M** [comment]
> Is your codebase somewhere we can see it?

no im working in local

**Comment by derrickmehaffy** [comment]
> > Is your codebase somewhere we can see it?
> 
> no im working in local

can you push it into a repo so I can try to reproduce locally?

**Comment by F-Y-M** [comment]
this is the sample project
https://wormhole.app/y4vY2#O6eEHfRCTmJjbA_Z2sCaGw

**Comment by derrickmehaffy** [comment]
> this is the sample project
> https://wormhole.app/y4vY2#O6eEHfRCTmJjbA_Z2sCaGw

It appears you didn't finish the upload.
