### ISSUE TITLE
GraphQL Nested Query Arguments are broken

### ISSUE THREAD

**Issue by rlvk-tc** [strapi/strapi#15666]
### Required System information

- Node.js version: 16.14.0
- NPM version: 9.2.0
- Strapi version: 4.6.0
- Database: PostgreSQL
- Operating system: MacOS Ventura 13.2

### Describe the bug

I am trying to achieve some nested data querying to fetch the exact data needed and take full advantage of the GraphQL nature. However I'm not able to use the arguments in my related entities in my query.

Take this query as an example:
```
query GetUnits($companyId: ID!) {
    units(filters: {company: {id: {eq: $companyId}}}, sort: ["imei"]) {
        data {
            id
            attributes {
                imei
                observations(pagination: {limit: 1}, sort: ["id:desc"]) {
                    data {
                        id
                        attributes {
                            location {
                                data {
                                    id
                                    attributes {
                                        latitude
                                        longitude
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

The arguments passed to the `observations` are completely ignored, so instead of returning the expected 1 entity, I'm getting ALL (which can be thousands), which is clearly not ideal.

The generated schema for the models I have suggest that I should be able to do this, yet it is clearly not working.

I'm unclear about if the behaviour is actually intended and the schema is wrong or if it's the other way around, but I'm pretty sure something needs to be adjusted.

I have found other resources on the internet about this issue, but it's all related to Strapi v3 and actually seems to have been solved back then.

### Steps to reproduce the behavior

1. Create a new Strapi project
2. Enable GraphQL Plugin
3. Create two seperate content-objects with a "belongs to many" relationship
4. Attempt to query with nested arguments

### Expected behavior

In my example above, I would expect to get 1 or less observations

Any help is greatly appreciated.

EDIT: It is specifically the `pagination` argument that is not working. The sort is actually working as expected.

**Comment by Marc-Roig** [comment]
Hello! Thank. you for the detailed issue explanation.
I am closing this in favor of https://github.com/strapi/strapi/issues/14841, so we can have any discussion in the same place.

We will provide a fix in 4.6.1 / 4.6.2 🚀
