### ISSUE TITLE
Helper plugin is not updated with 4.6.0 version

### ISSUE THREAD

**Issue by Louai99k** [strapi/strapi#15660]
### Required System information

- Node.js version: 14.19.x
- NPM version: 6.x.x
- Strapi version: 4.6.0

### Describe the bug

I've updated the strapi version to 4.6.0 but when I compare the helper plugin components in origin with my node_modules (such as the new JSONInput) it seems to be missed. because when I render the `GenericInput` with a type `json` It renders the `NotSupported` component. I logged the `GenericInput` and I got the older version of it and not the updated one.

### Steps to reproduce the behavior

1. If you have older version of strapi such as 4.5.6 just update it and you'll see what I'm talking about.

### Expected behavior

When I update to version 4.6.0 I should be able to use the `GenericInput` component with it's JSONInput.

### Screenshots

On the left side I have my JSON field which named "special" and on the right side I logged the `GenericInput` and I got this. Note that my version of the `GenericInput` is not the same as the one in the helper plugin [here](https://github.com/strapi/strapi/blob/main/packages/core/helper-plugin/lib/src/components/GenericInput/index.js#L139).

![Screenshot](https://user-images.githubusercontent.com/39621424/215993667-335b2749-0fff-424b-8654-4b4fb8d40f98.png)

@derrickmehaffy

**Comment by gu-stav** [comment]
The new `JSONINput` component was added two days ago to the `GenericInput` component and will be released in v4.6.1.

Do you see any other issues with the helper-plugin?

**Comment by Louai99k** [comment]
> Do you see any other issues with the helper-plugin?
Not for the moment I will update this issue if I find any thing else.

**Comment by gu-stav** [comment]
I'll close the issue in the meantime. Feel free to ping me or to open a new one.
