### ISSUE TITLE
Admin User Edit Page cache never gets invalidated

### ISSUE THREAD

**Issue by Torsten85** [strapi/strapi#15673]
### Required System information

- Strapi version: 4.6.0

### Describe the bug

The react-query cache used to fetch the admin user on the settings -> users -> detail page never invalidates

### Steps to reproduce the behavior

1. Go to 'settings -> users'
2. Select an user
3. make any changes
4. go back to the list view
5. reselect the same user
6. see the old stale values before the changes

### Expected behavior

Cache should invalidate after `putUser` is successfully executed

### Code snippets

User gets fetched here:
https://github.com/strapi/strapi/blob/d29403e173d9b7a6994be6d19f94265a55f35ba2/packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js#L52

Update gets executed here:

https://github.com/strapi/strapi/blob/d29403e173d9b7a6994be6d19f94265a55f35ba2/packages/core/admin/admin/src/pages/ProfilePage/utils/api.js#L10

**Comment by joshuaellis** [comment]
i've tested this against the latest version of Strapi and unfortunately can't reproduce this. Please upgrade your Strapi version and if the issue persists we can reopen.
