### ISSUE TITLE
Deepl API plugin crashes after import translate

### ISSUE THREAD

**Issue by JacquesBGit** [strapi/strapi#15675]
### Required System information

- Node.js version: v18.13.0
- NPM version: v8.19.3
- Strapi version: v8.19.3
- Database: sqlite
- Operating system: Mac os Monterey

### Describe the bug
Deepl API seems to crash the website
1. I create an entry 
2. I import data from the French version into a content field on the english locale via "import from other locale".
3. I insert some data (city etc)
3. From this moment on I can't save the entry and when I modify a field I get the error message: "Woops! Something went wrong. Please, try again."

### Steps to reproduce the behavior

1. Go to 'Locales' 
2. Change to another language
3. Click on 'ranslate from another locale'
4. Scroll down to other fields and change some data
5. Try to hit the SAVE button (inactive - no confirmation message)
6. Change any information on the page (like change a relation)
7. "Woops! Something went wrong. Please, try again."

### Expected behavior

SAVE the entry.

**Comment by derrickmehaffy** [comment]
Can you please open an issue on the plugin maintainers repo as we did not develop this plugin.

Thank you!
