### ISSUE TITLE
strapi import: required option --file not specified

### ISSUE THREAD

**Issue by dmarkbreiter** [strapi/strapi#15677]
### Required System information

- Node.js version: `16.14.2`
- NPM version: `8.5.0`
- Strapi version: `4.6.0`
- Database: PostgreSQL 14
- Operating system: macOS 12.1

### Describe the bug

When running `npm run strapi import --file export_20230201170419.tar.gz.enc` I get the following error: 
```
> strapi-test@0.1.0 strapi
> strapi "import" "export_20230201170419.tar.gz.enc"

error: required option '-f, --file <file>' not specified
```

### Steps to reproduce the behavior

I've tried permutations of the above command including: `npm run strapi import -f export_20230201170419.tar.gz.enc` to the same effect.

**Comment by StrapiShaun** [comment]
@dmarkbreiter  this is an `npm` issue. You need to pass an extra flag: npm run strapi import -- --file<file-name-and-path>. We will released improved documentation today. Thanks again for pointing out these issues.

**Comment by StrapiShaun** [comment]
updated documentation is live on https://docs.strapi.io

**Comment by dmnkvd** [comment]
I've gotten it to work! I believe my problem had to do with not using TypeScript.
