### ISSUE TITLE
strapi export --no-encrypt asks for encryption key

### ISSUE THREAD

**Issue by dmarkbreiter** [strapi/strapi#15678]
### Required System information

- Node.js version: `16.14.2`
- NPM version: `8.5.0`
- Strapi version: `4.6.0`
- Database: PostgreSQL 14
- Operating system: macOS 12

### Describe the bug

When using the command `npm run strapi export --no-encrypt` I am prompted to `Please enter an encryption key`. 

### Expected behavior

With the `no-encrypt` option, I would expect there to not be a prompt asking for an encryption key.

**Comment by StrapiShaun** [comment]
@dmarkbreiter This is an `npm` issue, which requires you to pass options with an extra flag: `npm run strapi export -- --no-encrypt`. We are going to release an improvement to the documentation that fixes this later today. Thanks for raising the issue.

**Comment by StrapiShaun** [comment]
updated documentation is live on https://docs.strapi.io

**Comment by yakupensarsayin** [comment]
I am still getting this error.
npm run strapi export --no-encrypt
or
npm run strapi export -- --no-encrypt
still asks for encrytion key.
