### ISSUE TITLE
Updating own profile in settings -or profile page does not persist changes to local storage

### ISSUE THREAD

**Issue by Torsten85** [strapi/strapi#15674]
### Required System information

- Strapi version: 4.6.0

### Describe the bug

When updating the own user data in settings -> users or on the profile page,
the new values are set in `auth.setUserInfo`, but not persisted to local storage. 

### Steps to reproduce the behavior

1. Go to the profile page
2. Change your username
3. See the changes reflected immediately next to your avatar image on the bottom left
4. Reload the page
5. See your old username

### Expected behavior

The changes should be persisted

### Code snippets

`setUserInfo` is executed here on the Profile page:
https://github.com/strapi/strapi/blob/d29403e173d9b7a6994be6d19f94265a55f35ba2/packages/core/admin/admin/src/pages/ProfilePage/index.js#L98

and here on the Settings->User page:
https://github.com/strapi/strapi/blob/d29403e173d9b7a6994be6d19f94265a55f35ba2/packages/core/admin/admin/src/pages/SettingsPage/pages/Users/EditPage/index.js#L90

setting the 2nd argument `auth.setUserInfo` to  `true` will persist those changes to local storage

**Comment by Arav1nd2** [comment]
Hi, Is anyone looking into this issue? This is my first time and would like to take this issue up.

**Comment by Torsten85** [comment]
I've looked deeper in the code and the easy fix I mentioned - simply setting the 2nd parameter to `true` to store the changes in local storage - should only be applied when the users has ticket the "remember me" box on the login page.

Currently I've monkey patched the method in my installation this way:

```ts
const originalSetUserInfo = auth.setUserInfo

auth.setUserInfo = (value: Record<string, any>, isLocalStorage: boolean, userInfo = 'userInfo') => {

  // if userInfo is in localStorage, the user checked "remember me" on the login page
  // so we have to keep the localStorage entry up-to-date
  if (localStorage.getItem(userInfo)) {

    // setUserInfo was either called on his own profile page or from an admin user
    // detail page, which means that an admin updated his own profile
    if (window.location.pathname === '/admin/me' || window.location.pathname.startsWith('/admin/settings/users/')) {
      isLocalStorage = true
    }
  }

  return originalSetUserInfo(value, isLocalStorage, userInfo)
}

**Comment by cacti23** [comment]
Hey, guys can i take up this issue if it still not resolved ?

**Comment by derrickmehaffy** [comment]
> Hey, guys can i take up this issue if it still not resolved ?

https://github.com/strapi/strapi/issues/14577

**Comment by joshuaellis** [comment]
Hey @Torsten85, I've just checked this issue on `main` and `4.6.0` and could not reproduce this issue. Would you be able to share more details – maybe a video? The data for your username comes from the server so when you save your username its persisted in the DB.
