### ISSUE TITLE
Server wasn't able to start properly.

### ISSUE THREAD

**Issue by ADNANALK** [strapi/strapi#15670]
### Required System information

- Node.js version:v16.14.2
- NPM version: 8.5.0
- Strapi version:4.5.5
- Database:mySql
- Operating system: win 11

### Describe the bug

when I add any content-type to my project, the application can't start again: 
server wasn't able to start properly.
 ER_TABLE_EXISTS_ERROR: Table 'menu_item_option' already exists
So each time I change anything or add a content-type to my custom plugin it shows this error.
So I fixed it by dropping the database and creating it again,

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by PaRoxUs** [comment]
I have the same issue, after creating a new content type the server stop and I get this message after running build or/and develop.

```
[2023-02-02 09:08:27.551] debug: ⛔️ Server wasn't able to start properly.
[2023-02-02 09:08:27.553] error: insert into `admin_permissions_role_links` (`permission_id`, `permission_order`, `role_id`) values (195, 19, 1) - ER_DUP_ENTRY: Duplicate entry '195-1' for key 'admin_permissions_role_links_unique'
```

**Required System information**
Node.js version:v19.2.0
NPM version: 9.1.3
Strapi version: 4.5.6
Database:mySQL
Operating system: macOS 13.1 (22C65)

**Comment by PaRoxUs** [comment]
I made to downgrade Node and NPM to the supported versions and still run into the same issue.

**Comment by PaRoxUs** [comment]
Updated to Strapi 4.6 and are still running into the same issue after creating a new content type!

**Comment by ADNANALK** [comment]
@PaRoxUs  me too
also, I updated my strapi version to 4.6.0 but still the same

**Comment by ADNANALK** [comment]
Hi, I am trying to create a new project Strapi V4.0.6 with the following steps:
1- create a new project
2- copy users-permissions to the extensions folder
3- run the project and it works
4- create an admin user
5- add new content type "user-token" from the admin panel 
6- add attributes "firebaseToken", "deviceId",
7- add relation with the user from ("users-permissions.user")

Error:
debug: ⛔️ Server wasn't able to start properly.
[2023-02-08 15:45:43.825] error: Error on attribute users_permissions_user in model user-token(api::user-tok attribute user_tokens not found target plugin::users-permissions.user
[test-relation.zip](https://github.com/strapi/strapi/files/10685481/test-relation.zip)

here is the project

**Comment by elihuvillaraus** [comment]
This is still happening... Does anyone found a solution?

**Comment by Boegie19** [comment]
> This is still happening... Does anyone found a solution?

Just to be clear what error are you getting?

**Comment by derrickmehaffy** [comment]
@Boegie19 wait til we get more reproduction steps before we reopen.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy reopend because of the zip [test-relation.zip](https://github.com/strapi/strapi/files/10685481/test-relation.zip)

You could reproduce?

**Comment by Boegie19** [comment]
Put it on pending reproduction since I did not test it yet.
