### ISSUE TITLE
400 Bad Request when enabling and configuring auth provider

### ISSUE THREAD

**Issue by steadweb** [strapi/strapi#1568]
**Informations**

- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: MongoDB / MySQL
- **Operating system**: Linux Mint 18

**What is the current behavior?**
Configuring and enabling an auth provider throws a `Bad Request 400 (This provider is disabled)` when trying to invoke via `http://localhost:1337/connect/<provider>`. Once I've saved and refresh the provider list, I can see it configured and enabled, but if I stop / start `strapi`, the provider will no longer be enabled and the configuration will be empty.

_Note: I've checked the data store, and I can see the JSON _correct_ values within the `core_store` table._

**Steps to reproduce the problem**
1. Install a new strapi app with either Mongo or MySQL
2. Create an admin user
3. Visit /admin/plugins/users-permissions/providers
4. Configure and Enable "Facebook" provide
5. Visit localhost:1337/connect/facebook (Bad request)
6. Restart strapi service (configuration disappeared)

**What is the expected behavior?**
- /connect/facebook to redirect to Facebook auth
- not throw a 400 bad request
- not lose provider details / enabled status

**Comment by steadweb** [comment]
I'm not using _both_ Mongo / MySQL - I've tried with both configuration and they produce the same issue.

**Comment by synth3tk** [comment]
I just had an interesting find. On server start/restart, the value of the `core_store.plugin_users-permissions_grant` is:
```json
{
   "email":{
      "enabled":true,
      "icon":"envelope"
   },
   ...
}
```

However, when saving the provider settings, it looks like this:
```json
{
   "providers":{
      "email":{
         "enabled":true,
         "icon":"envelope"
      },
      ...
   },
   "roles":{

   }
}
```

My assumption is the former is what it should look like.

**Comment by synth3tk** [comment]
Somehow I missed PR #1513. If it were a snake, it would have bit me. :snake:

**Comment by lauriejim** [comment]
Related of duplicate of this issue https://github.com/strapi/strapi/issues/1512 can you confirm please

**Comment by synth3tk** [comment]
This appears to be a duplicate. I tested that PR last night and it solved the 400 issue.

**Comment by steadweb** [comment]
Apologies, I didn't notice the previous issue already raised. Closing.

**Comment by synth3tk** [comment]
No worries! I clearly didn't see it, either.
