### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by millerone** [strapi/strapi#1569]
**Informations**

Node.js version: 10.6.0
Npm version: 6.1.0
Strapi version: 3.0.0-alpha.12.7.1
Database: MongoDB 4.0.0
Operating system: Windows 10

**What is the current behavior?**

For some reason I can't create a new project.
If i run "strapi new my-project" i can only choose the db (let's stay MongoDB) but i can't type the database name in the next step.
I'm not even getting an error, it closes the dialog.
If I press enter, without trying to type the name, i get the same behavior.

**Steps to reproduce the problem**

1) npm install strapi@alpha -g
2) strapi new my-project
3) try to choose a database name

**What is the expected behavior?**
To get a new project as usual

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1281

@lauriejim

**Comment by millerone** [comment]
Sorry, i didn't see the other open issue.
I can confirm that using Node v8.9.1 it works like a charm.
Thank you.
