### ISSUE TITLE
Throwing error in single-type middleware PUT method results in Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by JgalazanLN** [strapi/strapi#15697]
### Required System information

- Node.js version: 16.6.0
- NPM version: 7.19.1
- Strapi version: 4.5.6
- Database: mysql
- Operating system: Windows 10

### Describe the bug

When throwing an error from a single-type middleware with PUT method with ApplicationError or ctx.badRequest network works ok, but it shows the following:

![image](https://user-images.githubusercontent.com/106330580/216462551-afc8eb06-e183-4dbe-be3c-1b6961d25a21.png)

Just with the PUT method. DELETE method works fine.

### Steps to reproduce the behavior

1. Create a custom single-type (for the example call it 'home')
2. Add the middleware to config file

Example code:

config/middlewares.js

```javascript
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  'api::home.test-middleware'
];
```

3. Create a middleware for that api and throw an ApplicationError

Example:

src/api/home/middlewares/test-middleware.js

```javascript
const utils = require('@strapi/utils');
const { ApplicationError } = utils.errors;

module.exports = (config, { strapi }) => {
    return async (ctx, next) => {
if(ctx.request.body && ctx.request.method === 'PUT' && ctx.request.url === '/content-manager/single-types/api::home.home'){
            // return ctx.badRequest("Something went wrong")
            throw new ApplicationError('Something went wrong', { foo: 'bar' });
        }
        
        if(ctx.request.body && ctx.request.method === 'DELETE' && ctx.request.url === '/content-manager/single-types/api::home-club.home-club'){
            return ctx.badRequest("Forbidden Action")
        }
        await next();
    }
}
```
4. Run the app and go to content manager. Modify the home single-type and hit save. See the error.
5. If you comment the middleware, add something to the single-type and save, uncomment the middleware and hit delete entry, you will see the delete error displaying OK.

### Expected behavior

It's expected to work just like delete. Show error in the Admin UI.

![image](https://user-images.githubusercontent.com/106330580/216465783-b0de1fec-06d7-4b47-9f6a-316fe2f56186.png)

**Comment by gu-stav** [comment]
This will be fixed by the upcoming release (4.6.2) through this PR: https://github.com/strapi/strapi/pull/15321 If you need this urgently you can use the latest experimental release from npm [0.0.0-ffd0a215143bcafd0354d791533a57a084e53ffb](https://www.npmjs.com/package/@strapi/strapi/v/0.0.0-ffd0a215143bcafd0354d791533a57a084e53ffb) which should already include that fix.

If you experience any issues with that please ping me :)
