### ISSUE TITLE
Email - Unable to load plugins.js

### ISSUE THREAD

**Issue by arilanto** [strapi/strapi#15700]
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.19.3
- Strapi version: 4.6.0
- Database: Mysql
- Operating system: Windows 11

### Describe the bug

I try to test mail sending on my localhost via a fresh Strapi 4.6.0 installation

### Steps to reproduce the behavior

1. Create ./config/env/development/plugins.js
```
module.exports = ({ env }) => ({
  email: {
    config : {
      provider: 'nodemailer',
      providerOptions: {
          host: env('SMTP_HOST', 'XXXX'),
          port: env('SMTP_PORT', 'XXXX')
      },
      settings : {
        defaultFrom : 'XXXX',
        defaultReplyTo : 'XXXX'
      }
    }
  }
});
```

2. stop and start strapi with 'yarn develop'
3. Go to Settings > Email Plugin > Configuration
4. Field 'Email provider' is still 'sendmail' (should be 'nodemailer')
5. when trying to test mail (via 'Send test email' button), I get error in console :  
`error: Couldn't send test email: can not connect to any SMTP server`

### Expected behavior

nodemailer provider should be load
mail sh
![Sans titre](https://user-images.githubusercontent.com/4578276/216524880-bd5ceb11-aec5-4c7e-ad5b-96838d60c68f.png)
ould be sent

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by petersg83** [comment]
<img width="869" alt="Capture d’écran 2023-02-14 à 15 00 12" src="https://user-images.githubusercontent.com/11708220/218759761-f47707e1-54ba-4e2f-9c18-10e3ff4b7b7c.png">

I couldn't reproduce the issue, I see nodemailer.

It seems that the config is not correctly loaded. It is possible you have any typo in `./config/env/development/plugins.js`?
