### ISSUE TITLE
Error while importing data using strapi import 

### ISSUE THREAD

**Issue by Jaydeep189** [strapi/strapi#15714]
## Strapi is exporting perfectly but while importing with the cmd below
```npm run strapi import -f export_20230205094627.tar.gz.enc --key XXXXXX```

It gives this error
```error: required option '-f, --file <file>' not specified```
### additional question is that does it export uploads as well or just texts ?
strapi version - 4.6.0

**Comment by StrapiShaun** [comment]
Hello @Jaydeep189 , I think the issue is your `npm` command needs an additional `--`. The following example is from the [documentation](https://docs.strapi.io/developer-docs/latest/developer-resources/data-management.html#example-pass-the-encryption-key-with-the-strapi-import-command): 
```
npm run strapi import -- -f export_20221213105643.tar.gz.enc --key my-encryption-key
```

**Comment by Jaydeep189** [comment]
## That worked thanks,
## but another issue occurred while importing 

```
The import will delete all data in your database. Are you sure you want to proceed? Yes
[2023-02-06 10:56:33.089] error: [FATAL] Invalid schema changes detected during integrity checks (using the strict strategy). Please find a summary of the changes below:
- admin::permission:
  - Removed ""
- admin::user:
  - Removed ""
- admin::role:
  - Removed ""
- admin::api-token:
  - Removed ""
- admin::api-token-permission:
  - Removed ""
- plugin::upload.file:
  - Removed ""
- plugin::upload.folder:
  - Removed ""
- plugin::i18n.locale:
  - Removed ""
- plugin::users-permissions.permission:
  - Removed ""
- plugin::users-permissions.role:
  - Removed ""
- plugin::users-permissions.user:
  - Removed ""
- api::about.about:
  - Removed ""
- api::banner.banner:
  - Removed ""
- api::category.category:
  - Removed ""
- api::certified-partner.certified-partner:
  - Removed ""
- api::contact-us.contact-us:
  - Removed ""
- api::download-installation-guide.download-installation-guide:
  - Removed ""
- api::download-technical-manual.download-technical-manual:
  - Removed ""
- api::download-user-manual.download-user-manual:
  - Removed ""
- api::event.event:
  - Removed ""
- api::home-page.home-page:
  - Removed ""
- api::installation-guide.installation-guide:
  - Removed ""
- api::product.product:
  - Removed ""
- api::products-page.products-page:
  - Removed ""
- api::sector.sector:
  - Removed ""
- api::service-center.service-center:
  - Removed ""
- api::super-stockiest.super-stockiest:
  - Removed ""
- api::technical-manual.technical-manual:
  - Removed ""
- api::user-manual.user-manual:
  - Removed ""
- api::where-to-buy.where-to-buy:
  - Removed ""
- contact-us.india-office:
  - Removed ""
- contact-us.india-team:
  - Removed ""
- contact-us.italy-office:
  - Removed ""
- download.download:
  - Removed ""
- home-page.banner:
  - Removed ""
- home-page.clients:
  - Removed ""
- home-page.credability:
  - Removed ""
- home-page.feature-product:
  - Removed ""
- home-page.testimonials:
  - Removed ""
- product.faq:
  - Removed ""
- product.functional-features:
  - Removed ""
- product.teachnical-features:
  - Removed ""
- product.video:
  - Removed ""
- shared.seo:
  - Removed ""
Import process failed.
```
### I am pretty much sure that was schema is same locally and on my remote postgres db

**Comment by StrapiShaun** [comment]
@Jaydeep189 Thanks for reporting your issue. If you can provide detailed steps for reproducing the error, it will help the team to diagnose and fix the problem.

**Comment by Jaydeep189** [comment]
I have two remote postgres databases, I want to export one db data to another.
First in my database config file in strapi I config my original db and it's credentials,
Then I use this command to export data from db 1 .
```
npm run strapi export 
```
this generates me a export.tar.gz file in the root folder

Then I reconfigure the database config file in strapi to the database 2
and then run the following command
```
npm run strapi import -- -f export.tar.gz --key MYKEY
```

NOTE : 
1. My local strapi server is not running when I am exporting or importing
2. I do not build/run my server after changing the database config file in strapi

Do let me know if I need to give more info, or some specific step

**Comment by innerdvations** [comment]
I haven't been able to reproduce this. Do you have the same issue if you start with an empty Strapi project? If not, would you be able to provide an export without any sensitive information (such as a clean database, only your schema) with the --no-encrypt option?

What appears to be happening (and the error messaging will be improved in the next version 🙂) is that the schema file in the export file isn't able to load -- either it isn't there because it never got exported, or it's there but an error is encountered when trying to read it. If you could provide a failing export file I can determine which of those problems it is. Thanks!

**Comment by Jaydeep189** [comment]
I haven't tried to import it in the same database, as I worry data might get corrupted, as the project is in production I can't take that risk.

Here is the file, you can download it [here](https://drive.google.com/file/d/1lC1W-yC1a1JY1u4KSEUYdvmW-Oe8wQFP/view?usp=sharing)

I hope this helps

**Comment by marcoautiero** [comment]
> I haven't tried to import it in the same database, as I worry data might get corrupted, as the project is in production I can't take that risk.
> 
> Here is the file, you can download it [here](https://drive.google.com/file/d/1lC1W-yC1a1JY1u4KSEUYdvmW-Oe8wQFP/view?usp=sharing)
> 
> I hope this helps

Thank you @Jaydeep189 

We would need the key to decrypt the archive :)

**Comment by Jaydeep189** [comment]
> We would need the key to decrypt the archi

tradesecamc is the key

**Comment by Jaydeep189** [comment]
I have another question regarding export/import,
Is media exported In strapi export ?
how can I transfer my media from one server to another without a data mismatch?

**Comment by xmak** [comment]
I'm having a similar issue, here are the details with steps to reproduce and an archive with my project code:

https://forum.strapi.io/t/data-import-fatal-error-on-4-6-0/25285/6

**Comment by bitmonti** [comment]
Hello!

Same issue here on:

`
strapi import -f export_20230430125013.tar.gz.enc
`

```
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@strapi/plugin-graphql": "^4.10.1",
    "@strapi/plugin-i18n": "4.10.1",
    "@strapi/plugin-users-permissions": "4.10.1",
    "@strapi/provider-email-nodemailer": "^4.10.1",
    "@strapi/strapi": "4.10.1",
    "better-sqlite3": "8.3.0",
    "strapi-plugin-import-export-entries": "^1.19.1",
    "strapi-plugin-translate": "^1.1.3",
    "strapi-provider-translate-deepl": "^1.1.3"
  },
```

```
error: [FATAL] Invalid schema changes detected during integrity checks (using the strict strategy). Please find a summary of the changes below:- api::about.about:
  -  exists in source schema but not in destination schema
- api::blog.blog:
  -  exists in source schema but not in destination schema
- api::category.category:
  -  exists in source schema but not in destination schema
- api::contact.contact:
  -  exists in source schema but not in destination schema
- api::event.event:
  -  exists in source schema but not in destination schema
- api::impressum.impressum:
  -  exists in source schema but not in destination schema
- api::partner.partner:
  -  exists in source schema but not in destination schema
- api::seed.seed:
  -  exists in source schema but not in destination schema
- api::showcase.showcase:
  -  exists in source schema but not in destination schema
- api::support.support:
  -  exists in source schema but not in destination schema
- event.contact:
  -  exists in source schema but not in destination schema
- event.details:
  -  exists in source schema but not in destination schema
- event.pricing:
  -  exists in source schema but not in destination schema
- seed.details:
  -  exists in source schema but not in destination schema
- shared.download:
  -  exists in source schema but not in destination schema
- shared.email:
  -  exists in source schema but not in destination schema
- shared.phone:
  -  exists in source schema but not in destination schema
- text.content:
  -  exists in source schema but not in destination schema
- text.description:
  -  exists in source schema but not in destination schema
Import process failed.
```

**Comment by rohitmeshramcodeb** [comment]
@bitmonti raise a new bug and refer this issue. This issue is marked as close.

**Comment by Sochima-Aristotle** [comment]
Hi there, I am new to strapi and my little experience with it shows that it is a good tool to use, however I am have a serious issue with the dependencies it is requesting something like  this**./node_modules/@strapi/data-transfer/dist/index.mjs
Attempted import error: '@strapi/strapi' does not contain a default export (imported as 'strapiFactory').** has made my development efficiency to drop significantly. I don't know if anyone can help me resolve this issue, I have gone to google and many AI tools to resolve it but it sad to say that I didn't make any progress.

**Comment by soonerdev24** [comment]
I'm having a similar experience as the last user. I get the following error in my export attempt (version 4.23.1)

throw er; // Unhandled 'error' event

Request failed with status code 404
.. /@strapi/data-transfer/dist/index.js:2304:17)
Emitted 'error' event on Duplexify instance at:
emitErrorNT (node:internal/streams/destroy:169:8)
