### ISSUE TITLE
Unable to start the localhost server

### ISSUE THREAD

**Issue by chandhuDev** [strapi/strapi#15713]
### Required System information

Node.js version:16.18.0
NPM version:9.2.0
Strapi version:latest
Database:default
Operating system:windows

### Describe the bug

Get error when I try running the getstarted example 

### Steps to reproduce the behavior

1. Fork and open the workspace in the gitpod to run the getstarted example
2. go to http://localhost:1337/admin 
3. And go to the admin panel for development 
4. shows the error that is specified in the screenshot

### Screenshots
![Screenshot (187)](https://user-images.githubusercontent.com/106800538/216777941-e1aa5b7b-ceba-438f-8ee7-235fbbe8f599.png)

**Comment by derrickmehaffy** [comment]
```
Strapi version:latest
Database:default
```

Can you please actually specify this information?
