### ISSUE TITLE
Error in bold symbol of Rich Text Editor

### ISSUE THREAD

**Issue by 0xdhrv** [strapi/strapi#15729]
### Required System information

- Node.js version: 16.17.1
- Yarn version: 1.22.19
- Strapi version: 4.6.0
- Database: Postgres
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When navigating to a component that uses Rich Text Editor, we have an error in the same.

### Steps to reproduce the behavior

1. Go to a component that is used in Rich Text Editor
2. We have an error in the browser console:
```
Error: <svg> attribute viewBox: Unexpected end of attribute. Expected number, "0 0 24".
g @ main.ee95a013.js:2194
main.ee95a013.js:
```

### Expected behavior

There should not be invalid SVG data for the symbol

### Screenshots

![image](https://user-images.githubusercontent.com/19857414/217224720-1b59fbcf-295b-4581-b8be-d68061023c11.png)

**Comment by gu-stav** [comment]
I believe this has been fixed recently in https://github.com/strapi/design-system/releases/tag/v1.4.2. Did you rebuild your admin app by running `yarn build` ?
