### ISSUE TITLE
Posgresql (relation which contains json fields)  bug

### ISSUE THREAD

**Issue by BenCherif** [strapi/strapi#15728]
After migrate the database from sqlite to posgresql i face this  issue:
![Screen Shot 2023-02-07 at 10 56 27](https://user-images.githubusercontent.com/12634281/217213475-494e5250-012f-44b2-b486-ac90b81c6c0a.png)

after investigation i see that the issue comes from the SQL Query (postgres) :
Select distinct "MyTable".*, ........
Need to replace .* by .id 

so it is an issue with relation which contains json fields.
but i couldn't  fix it by myself.

**Comment by BenCherif** [comment]
### Required System information
- Node.js version: v16.16.0
- NPM version: 9.3.1
- Strapi version: 4.5.0
- Database: postgres
- Operating system: macos

### Describe the bug

After migrate the database from sqlite to posgresql using pgloader i see that the issue comes from the SQL Query (postgres) :
Select distinct "MyTable"., ........
Need to replace . by .id

i'm run strapi with docker

so it is an issue with relation which contains json fields.

 
### Expected behavior

A clear and concise description of what you expected to happen.

### Screenshots

 
![Screen Shot 2023-02-07 at 10 56 27](https://user-images.githubusercontent.com/12634281/217238609-d5d111d6-f56d-47b1-abd1-65028919df7f.png)

**Comment by petersg83** [comment]
Hello :)
I don't think it's an issue of Strapi but more likely that something went wrong when migrating from SQLite to Postgres.
I would propose to start a discussion on the [forum](https://forum.strapi.io) to find help from people that did migration too.

In the meantime I'll close the issue. But don't hesitate to continue ask questions if needed :)
