### ISSUE TITLE
Cannot import data on docker container

### ISSUE THREAD

**Issue by akcyp** [strapi/strapi#15724]
### Required System information

- Node.js version: 18
- Strapi version: 4.6.0
- Database: postgres
- Operating system: node:18-alpine
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

Strapi import not works on `node:18-alpine` container (Alpine Linux)

### Steps to reproduce the behavior

1. Run strapi on docker container
2. Run `docker exec -it [container id] bash`
3. Run `yarn strapi import --force -f strapi-export.tar.gz`

### Expected behavior

Should be able to import data.

### Screenshots

![image](https://user-images.githubusercontent.com/67923777/217074467-4d06cf72-89fb-478e-abba-2a073534ae94.png)

### Code snippets

```dockerfile
FROM node:18-alpine

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ENV NODE_ENV production

WORKDIR /opt/app
COPY ./package.json ./yarn.lock ./
RUN yarn config set network-timeout 600000 -g && yarn install --frozen-lockfile

COPY ./ .
RUN yarn build
EXPOSE 1337

CMD ["yarn", "deploy"]
```
```json
{
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "import:db": "strapi import -f strapi-export.tar.gz --force",
    "deploy": "yarn run import:db && yarn start"
  }
}
```

**Comment by akcyp** [comment]
I probably found the line of code that causes the error: https://github.com/strapi/strapi/blob/main/packages/core/data-transfer/src/strapi/providers/local-destination/index.ts#L159
Suggested fix: use `mv` package to perform rename https://www.npmjs.com/package/mv / perform copy & remove directory instead od renaming

**Comment by akcyp** [comment]
Created PR: https://github.com/strapi/strapi/pull/15737

**Comment by akcyp** [comment]
PR is merged, closing

**Comment by Convly** [comment]
Thanks a lot for your contribution @akcyp :slightly_smiling_face:
