### ISSUE TITLE
Undefined attribute level operator $startsWithi

### ISSUE THREAD

**Issue by fadinasr** [strapi/strapi#15736]
### Required System information

- Node.js version: `v16.18.1`
- NPM version: `8.19.2`
- Strapi version: `4.5.4` and `4.5.6`
- Database: `Postgres`
- Operating system: `MacOS` or `64bit Amazon Linux 2`
- Is your project Javascript or Typescript: `Javascript`

### Describe the bug

Receiving **Undefined attribute level operator `$startsWithi`** when using any case-insensetive filter like `startsWithi` or `endsWithi`

### Steps to reproduce the behavior

1. Create a new collection
2. Add a relation with the user collection (users-permissions)
3. Use the REST API to fetch all the records in the new collection
4. Add a `$startsWithi` filter
5. You'll get the error above 

### Expected behavior

Should filter case-insensitively

**Comment by Marc-Roig** [comment]
Hello, could you try with 4.6.1? this filter was introduced in this version if I am not mistaken https://github.com/strapi/strapi/pull/15046

**Comment by Marc-Roig** [comment]
I will close this issue for now, as it seems to be fixed :)

**Comment by fadinasr** [comment]
It works well on `v4.6.2`
