### ISSUE TITLE
Can not deploy to Digital Ocean droplets, error when run setup

### ISSUE THREAD

**Issue by ghufr** [strapi/strapi#1573]
**Informations**
- **Node.js version**: 9.11.1 (i use nvm)
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongo
- **Operating system**: Ubuntu 16.04.4 LTS

**What is the current behavior?**
```
 91% additional asset processingnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.6 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-14T12_16_44_741Z-debug.log
(node:14349) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
 91% additional asset processingnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.6 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-14T12_16_44_741Z-debug.log
```

**Steps to reproduce the problem**

- Create Digital Ocean droplets (1vCPU 1GB)
- `npm i -g strapi@3.0.0-alpha.12.6`
- `strapi new myProject`
- `cd ./myProject`
- `npm run setup`

**What is the expected behavior?**
- Build without error

**Suggested solutions**
- Scale the Digital Ocean droplets ? 🤷‍♂️
- Using docker? (Build local)

I already test to build on my linux machine but it works without error

Resource usage when building: 
![2018-07-14 19_51_18-window](https://user-images.githubusercontent.com/20156570/42724596-6d9f839a-879f-11e8-8cd7-294a6db00054.png)

**Comment by derrickmehaffy** [comment]
@ghufr can you test without using nvm and install node globally?

**Comment by ghufr** [comment]
@derrickmehaffy  I use nvm on my local machine, same version and it works

**Comment by ghufr** [comment]
I tried to `npm run build` on `admin` folder, it works fine, but the plugins is not built

**Comment by derrickmehaffy** [comment]
Just tossing this here since @maturano noticed it put it on the slack. @soupette any idea whats going on here?

> Maturano [11 days ago]
> ... :confused:
> 
> Results that...
> - `cross-env` is dependency of `strapi-helper-plugin`
> - `strapi-helper-plugin` is listed on `devDependecies`
> 
> ... In the server the var enviroment `NODE_ENV=production` is setted by default. That was causing to `npm` skip installing the `devDependencies`... so ... that was the black magic.
> 
> I'll out to walk a couple of minutes U_U

**Comment by maturano** [comment]
I just have to experiment the same issue and was not related to the `NODE_ENV` variable ... maybe is the same problem.

@ghufr Try to set the environment variable `npm_config_debug` to `true`. Either exporting it in the command:
```
# Option 1
$ export npm_config_debug=true && npm run setup
# Options 2
$ npm_config_debug=true npm run setup
```

If works, hopefully you can see a more verbose output that could help to found the problem.

In my case, I got this:
```
> pngquant-bin@4.0.0 postinstall /project/admin/node_modules/pngquant-bin
> node lib/install.js 

⚠ The `/project/admin/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly  
⚠ pngquant pre-build test failed  
ℹ compiling from source  
✔ pngquant pre-build test passed successfully  
✖ HTTPError: pngquant failed to build, make sure that libpng-dev is installed
    at EventEmitter.ee.on.res (/project/admin/node_modules/pngquant-bin/node_modules/got/index.js:250:24)
    at EventEmitter.emit (events.js:180:13)
    at Immediate.setImmediate (/project/admin/node_modules/pngquant-bin/node_modules/got/index.js:99:8)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

My problem was that I was connected behind an "enterprise restricted network" (an `HTTPError`). I don't know why is connecting to internet if I had all the dependencies installed... in fact, I had `pngquant` installed, the building should not happen at all 😕 

However, that error was interrupting the installation of dependencies and resulting with the same error ...

My 2c

**Comment by ghufr** [comment]
It turns out my problem is caused by memory limit :(

**Comment by seanmavley** [comment]
@ghufr That's a great hint.

I'm on a 5$ digitalocean box. Instead of upgrading, just bumped up swapfile from 1 to 2Gig. Sailed through in peace.

**Comment by niallmurphy-ie** [comment]
Thanks @seanmavley  Adding a swapfile solved my issue, too.
