### ISSUE TITLE
strapi-upload-aws-s3: specify mime type on upload

### ISSUE THREAD

**Issue by jellybeat** [strapi/strapi#1574]
**Informations**

- **Node.js version**: 10.1.0 (with nvm)
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongo
- **Operating system**: macOS 10.12.6

**What is the current behavior?**
When uploading to S3, all objects are saved as application/octet-stream type.

**Steps to reproduce the problem**

- Upload a file with the strapi-upload-aws-s3 plugin
- Click to see the file, get prompted with a download
- Inspect the object uploaded to S3 and check its metadata, `Content-Type` is set to `application/octet-stream`

**What is the expected behavior?**
When uploading to S3, the saved object should have the correct mime type.

**Suggested solutions**
Add the `ContentType` attribute to the S3 upload `params` object and set it with `file.mime`

Disclaimer: First time contributing to the project and Open Source in general, so if there is something that I am doing wrong, sorry.

I have tried and debugged this solution in my project and it worked fine. Maybe this was left out for other use cases, but in the case of images, is handy to have the mime type already declared in the object within the bucket.

I could provide a PR if you want with the snippet I used and worked:
```javascript
S3.upload({
   Key: `${file.hash}${file.ext}`,
   Body: new Buffer(file.buffer, 'binary'),
   ContentType: file.mime,
   ACL: 'public-read'
}
```

**Comment by lauriejim** [comment]
Hello @jellybeat , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by jellybeat** [comment]
Oh, nevermind. Just realized that this PR: (https://github.com/strapi/strapi/pull/1572) included that line on the S3 upload. I'll move my comments out there. Sorry for the inconvenience.
