### ISSUE TITLE
Dynamic zones with relations inside components do not update correctly when switching locales and causes blank page

### ISSUE THREAD

**Issue by thevisualfox** [strapi/strapi#15743]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.6.0
- Database: mysql
- Operating system: CentOS / Local MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When switching between locales (for example Dutch > English) the dynamic zone components of the Dutch locale stay visible on the English locale, eventhough the English locale does not have this component added in that particular dynamic zone. If you then refresh the page, the selected locale is correctly displayed (in this case without the component that is used on the Dutch locale). But then when I switch back to the Dutch locale, the page turns blank and displays the following error in the console:

`TypeError: Cannot read properties of null (reading 'length')`.

The error is inside `RelationInputDataManager.js` on line 58 -> `const currentLastPage = Math.ceil(get(initialData, name, []).length / RELATIONS_TO_DISPLAY);`

If I remove the relation from the component this issue is resolved. 

### Steps to reproduce the behavior

See video's that I added to this post

### Expected behavior

When you switch locales the dynamic zones should be updated according to what's filled in for that particular locale. 

### Screenshots

See video's that i added to this post.

### Code snippets

n.a.

### Additional context

There's a difference in errors whether the relation is filled or not. I added two video's outlining the issues

https://user-images.githubusercontent.com/43511726/217519311-4c041155-fd40-42ed-b28d-b38c26ebd20a.mov

https://user-images.githubusercontent.com/43511726/217519350-c7cbbab7-df98-4afb-8934-8635a6fcd7f7.mov

**Comment by Przemek625** [comment]
I can confirm that there is similar issue in my app.

**Comment by russell-matt** [comment]
I'm experiencing the same issue with dynamic zone components duplicating relations from the previous locale when switching.
<img width="850" alt="Screenshot 2023-02-21 at 09 25 09" src="https://user-images.githubusercontent.com/10886400/220276256-38578a61-29a5-4029-bc5b-5ac08d59c397.png">

I don't currently experience the error when switching back, but the relations carrying over from the previous locale can lead to a lot of confusion.

**Required System information**
- Node.js version: 16.15.0
- NPM version: 9.4.0
- Strapi version: 4.6.1
- Database: mysql
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

**Comment by joshuaellis** [comment]
Seems related to #15638

**Comment by derrickmehaffy** [comment]
> Seems related to #15638

Do you want to close and mark as duplicate or keep both open?

**Comment by russell-matt** [comment]
> Seems related to #15638

In my case, the dynamic zone is localised. So the scenario is not the exact same, but perhaps the root cause is the same.

**Comment by derrickmehaffy** [comment]
Ah alrighty, well that's fine we can keep both open just in case :)

**Comment by joshuaellis** [comment]
Thanks for checking @derrickmehaffy, I'm working on them both at the moment so I reckon it's fine to keep them open.
