### ISSUE TITLE
Blank pages in admin media libraray after upgrade to 4.6.0

### ISSUE THREAD

**Issue by antoineclech** [strapi/strapi#15751]
### Required System information

Node.js version: 18.9.1
NPM version: 8.19.1
Strapi version: 4.5.6
Database: MySQL
Operating system: Ubuntu 64 Bit

### Describe the bug
After upgraded Strapi from 4.5.6 to 4.6.0, we can't access the "Media Library" page (http://my-host/admin/plugins/upload).
When we trace the browser calls, we see that the call https://my-host/upload/configuration returns a null data.

If we pass the sorting in the url, the page is displayed (ex : /admin/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10), the page is displayed.

Moreover, if we try to modify an existing image, we have a similar error

### Screenshots
![image](https://user-images.githubusercontent.com/44360520/217569192-77a55e57-c324-4411-87e2-ff95e5c5283b.png)

![image](https://user-images.githubusercontent.com/44360520/217571106-8e9a0f32-a35a-4553-af9a-42449dbdca9e.png)

**Comment by mgrubinger** [comment]
Maybe this is the cause if your issue as well (it was for me): https://github.com/strapi/strapi/issues/15454 
I "fixed" it by removing all records in `files` table without a mime-type. This was seemingly caused by a third-party editor plugin.

**Comment by joshuaellis** [comment]
👋🏼  thanks for the issue, looks like an oversight on our behalf – we weren't anticipating the `config` to be null.
