### ISSUE TITLE
JSON field input cannot be empty

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#15776]
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.6.1
- Database: mysql8
- Operating system: debian
- Is your project Javascript or Typescript: typescript

### Describe the bug

When creating an entry, it is initially `null`.
When you make changes from here, you must remove `null`, but even if you do, `null` will be restored.
*On rare occasions, you may be able to delete it.

This is not a problem if `null` that is automatically entered is in a form that behaves like a placeholder, but it is inconvenient because it is the same as normal text.

The caret appears to be wrong as well.

### Expected behavior

Do not reinstate `null` while typing.
Or use `null` as a placeholder.

### Screenshots

https://user-images.githubusercontent.com/26789317/218047880-4fa12259-089f-4141-b341-de43a9d376a8.mov

**Comment by markkaylor** [comment]
The JSONInput cannot be empty otherwise it will throw an error "invalid JSON" on submit, that is why it sets the value to null when the user tries to leave it empty.

I believe this has always been the behavior of the JSONInput

**Comment by rktyt** [comment]
@markkaylor
In v4.5.6 I was able to empty it.
If I save the entry as empty, it will be `null`.

There is no problem with setting the value to null at submit.
It is difficult to use to return to `null` while typing.

**Comment by gu-stav** [comment]
I agree that if the field is not a required field, is has to be possible to empty it.

**Comment by rktyt** [comment]
Just to make sure there's no misunderstanding.
I am saying that it is difficult to use as an text editor.

As a text editor, I think this behavior is a bug.

**Comment by markkaylor** [comment]
@rktyt yes you are right it is a bug, I just opened https://github.com/strapi/strapi/pull/15778. I believe the behavior should actually be like 4.5.6 now.
