### ISSUE TITLE
date widget high cpu/ram usage

### ISSUE THREAD

**Issue by jarro** [strapi/strapi#15789]
Editing a collection with a date  causes high cpu/ram  that eventually  crashes the admin panel.

Seen on strapi 4.5.5+  

To reproduce
Add a date object of type datetime  to a  collection, and in the backend set the date  with the required iso date or millis.

In the database you should end up with something like.  2/10/2023 6:56:59 AM.859

When you go to the edit page with date.   
Everything works and there are no errors  but cpu and ram usage go way up  and  eventually lock up the page.  

No issue when you zero out the millis on the  date  before submitting it.   
2/10/2023 6:56:59 AM

backend:
ubuntu 20.04
postgresql 13
node  16 and 18
javascript

frontend:
saw this on mac and windows on all  browsers

**Comment by domfie** [comment]
Can confirm. As soon as I remove the field from the entry view, cpu stays silent
