### ISSUE TITLE
Oneway relation converting itself to OneToOne or OneToMany

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1578]
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: 10.2.16-MariaDB
- **Operating system**: Linux Mint 19 Tara (Ubuntu 18.04)

**What is the current behavior?**

Fair warning this is difficult to produce, I've noticed it only when working with models with either a lot of fields, or other relations.

On some models if you set a oneWay relation, after a restart strapi reads these as another type of relation such as `oneToOne` or `oneToMany` in which it attempts to look for a column on the "source" of the oneway relation (the targeted model) when attempting to save. 

**Steps to reproduce the problem**

Unsure of exact steps to reproduce, I am making this issue in hopes to have others chime in when they encounter this issue so we can track down what is causing it. I am able to reproduce it every single time on my project but not with any consistency outside of it.

**What is the expected behavior?**

When a oneWay relation is set, strapi shouldn't not attempt to use any other type of relation.

**Suggested solutions**

Unsure yet, at this point I'm turning myself bald trying to figure it out.

**Comment by lauriejim** [comment]
Hello @derrickmehaffy. I try to play with models and relations and not able to have your issues...
Really need steps to reproduce this issue.

**Comment by derrickmehaffy** [comment]
@lauriejim I can give you one sure fire way with my project :stuck_out_tongue:

**Comment by derrickmehaffy** [comment]
Example on v13.1:

![image](https://user-images.githubusercontent.com/8593673/44195755-e043cb00-a0ee-11e8-8c35-01e9d238319f.png)

However now if I attempt to save:
![image](https://user-images.githubusercontent.com/8593673/44195802-023d4d80-a0ef-11e8-8d7b-c0978e5bc07a.png)

![image](https://user-images.githubusercontent.com/8593673/44195839-1e40ef00-a0ef-11e8-8650-b845f9ccb46c.png)


It works as expected, I think this is some kind of frontend bug with oneWay relations. @soupette what are your thoughts?

**Comment by derrickmehaffy** [comment]
My current version without these oneWay relation changes: https://github.com/canonn-science/CAPIv2-Strapi

My test version with these changes: https://github.com/canonn-science/CAPIv2-Strapi/tree/removeLocation

( Run a diff and you can see the changes )

**Comment by derrickmehaffy** [comment]
Diff between the two: https://github.com/canonn-science/CAPIv2-Strapi/commit/1d3135f9d2b178960a060bf56203e8006bc7a5f7

**Comment by derrickmehaffy** [comment]
Have confirmed the graphical bug on the AdminUI in Strapi v14, however the models are "working" without breaking. The AdminUI just shows them as being oneToOne or oneToMany when you click on them in the content type builder.

**Comment by soupette** [comment]
So it's front-end related?

**Comment by derrickmehaffy** [comment]
@soupette yes

**Comment by derrickmehaffy** [comment]
Can confirm the visual bug is still happening on v14.1.1 also sometime a random "undefined" relation field shows up on the "source" model that has to be deleted. Note that it doesn't actually create anything in the database on the source nor the destination tables.

**Comment by soupette** [comment]
@derrickmehaffy 
> Fair warning this is difficult to produce, I've noticed it only when working with models with either a lot of fields, or other relations.
> Can confirm the visual bug is still happening on v14.1.1 

How can I reproduce it?

**Comment by lauriejim** [comment]
@derrickmehaffy Any update please.

**Comment by soupette** [comment]
@derrickmehaffy I think it's back-end related.
Here's what the front-end receives:

![screenshot 2018-10-09 at 16 05 30](https://user-images.githubusercontent.com/13311463/46674774-4cb5e480-cbdd-11e8-9da2-8400833bb472.png)

Maybe @lauriejim  can help on that one.

**Comment by derrickmehaffy** [comment]
Yeah so the backend (bookshelf) is sending the wrong relation data. Those `system` and `body` fields should be `oneWay` not `manyToOne`.

I know the `oneWay` code was a quick and dirty addition, most likely related that the source models have a ton of other fields on them, there is likely some kind of parse problem.

**Comment by soupette** [comment]
I'm also pretty sure the bug occurs with `strapi-hook-mongoose` as well, I need to check with your app as well...

**Comment by lauriejim** [comment]
Hey @derrickmehaffy can you take a look with last version of Strapi if it still exist please.

**Comment by derrickmehaffy** [comment]
Yes @lauriejim, it's usually the first thing I check after I updated. It is still happening on 14.4.

**Comment by lauriejim** [comment]
Okay dac. Thank you for this detail.

**Comment by derrickmehaffy** [comment]
FYI still happens on v15

**Comment by derrickmehaffy** [comment]
Confirming this issue still present on v18 & v19

**Comment by derrickmehaffy** [comment]
Bug still exists on v22
![image](https://user-images.githubusercontent.com/8593673/52274431-e67e6b80-2909-11e9-8b6f-78dc81cd28c1.png)

**Comment by Lith** [comment]
Hi, same bug here with V25 !
OneWay is converting to OneToOne :/ 
How to force OneWay ? Do you have an idea how to force it ?

**Comment by derrickmehaffy** [comment]
@Lith It is just a visual bug, if it is defined properly in your model.settings.json file it should be fine unless you are modifying the model. @soupette see I'm not crazy... i swear :laughing:

**Comment by Lith** [comment]
Hi @derrickmehaffy ! Sure, but it's clearly a big bug for me, because when I go to my content-type an error 500 occurs... 
```code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'customers.moto_id\' in \'where clause\'',```

I just add that :
*Table motos* -> *customer* relation "oneWay" to *customer*

I just need a OneWay from moto to customer. But I don't know why Strapi invents a field that does not exist...
 
Do you know how to fix this error ? :(

**Comment by chirag38-unity** [comment]
Hi, I am having the same issue in recent Strapi5 version 5.35.0 (node v24.12.0) . I have a master collection which has a few (more than a few 7-8) relations. My oneway relations are converted to OneToOne & manyWay to OneToMany.

**Comment by derrickmehaffy** [comment]
> Hi, I am having the same issue in recent Strapi5 version 5.35.0 (node v24.12.0) . I have a master collection which has a few (more than a few 7-8) relations. My oneway relations are converted to OneToOne & manyWay to OneToMany. 

please don't resurrect an issue from 7 years ago, please open a new one. the code around this has probably changed 1,000 times since this issue was opened and closed.
