### ISSUE TITLE
How to export media from postgres database to another database

### ISSUE THREAD

**Issue by Jaydeep189** [strapi/strapi#15793]
I have tried, 
`strapi export`
but it does not export images, nor could I find any plugin that helps me do it

My server is in production and I have to shift it to another server, please help.

**Comment by marcoautiero** [comment]
Where do you store your images?

Please, could you provide some more details, otherwise it's difficult to provide you with some help :)

**Comment by eruiz-impact** [comment]
You can always backup the db using pgadmin4 and restore the new db with that backup. Works like a charm for us.
