### ISSUE TITLE
Date format error on update content manager MySQL

### ISSUE THREAD

**Issue by dblinov** [strapi/strapi#1579]
**Informations**node 
- Node.js version: 10.6.0
- npm version: 6.1.0
- Strapi version: 3.0.0-alpha.12.7.1
- Database: MySQL 5.7.2
- Operating system: macOS High Sierra 10.13.5

**What is the current behavior?**

I added to User Content Type a new Field - Birtday with Type Date. When I try to make any changes in User data I receive the following error message:

update `users-permissions_user` set `positions` = 1, `resetPasswordToken` = NULL, `provider` = 'local', `status` = 1, `last_name` = '....', `role` = 1, `username` = '....', `first_name` = '....', `id` = 1, `email` = '....', `birthday` = '1978-12-27T11:00:00Z' where `id` = 1 - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '1978-12-27T11:00:00Z' for column 'birthday' at row 1_

**Steps to reproduce the problem**

**What is the expected behavior?**

No error to be shown and user information is updated

**Suggested solutions**

no idea

**Comment by derrickmehaffy** [comment]
@lauriejim likely related to that issue with the automated created_at and updated_at fields a few versions back.

**Comment by dblinov** [comment]
I have the same issue suing MySQL version 8.

**Comment by derrickmehaffy** [comment]
@dblinov its not an issue with mysql, strapi isn't sending the correct format to mysql

**Comment by derrickmehaffy** [comment]
Not sure on the exact fix @dblinov but I know the problem stems from Strapi using moment.js which doesn't format the `datetime` correctly for mysql. 

I believe @johannpinson has already fixed it in a PR that also adds some other stuff to graphQL, see: https://github.com/strapi/strapi/pull/1439#issuecomment-401714051

Not sure if that PR also includes the fix.

**Comment by pelayomendez** [comment]
Still found this problem while starting a project with strapi 3.0.0-alpha.24.1 when editing a content through the admin panel.

> ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2019-02-21T17:04:06.000Z' for column 'userdate' at row 1

As a workaround the MySQL Server mode can be set to ALLOW_INVALID_DATES.

**Comment by pbredenberg** [comment]
I've also run into the same issue running MariaDB 10.3.13. The workaround suggested @pelayomendez does work, but obviously not a long term solution.

**Comment by selfagency** [comment]
I'm running into this problem with the latest Strapi and MySQL and it's killlllling meeeeeeee.

**Comment by Delta843** [comment]
Why is this closed? This is still an issue in the latest version.

**Comment by renanbronchart** [comment]
I follow this issue on stackoverflow, and my problem is solved:
https://stackoverflow.com/questions/44304777/er-truncated-wrong-value-incorrect-datetime-value

I hope it helps...

**Comment by selfagency** [comment]
Another fix is to just add:

```
sql_mode='ALLOW_INVALID_DATES'
```

to the `[mysqld]` block of your `my.cnf`. That's how I eventually got around it.

**Comment by petre2dor** [comment]
I really hope this gets fixed in the next version. it's a basic need to be able to update an user.
