### ISSUE TITLE
Cannot build, missing Module from Codemirror

### ISSUE THREAD

**Issue by pdavid0** [strapi/strapi#15796]
### Required System information

- Node.js version: `v18.14.0`
- NPM version: `9.3.1`
- Yarn: `3.2.4`
- Strapi version: `4.6.1`
- Database: `postgres 14`
- Operating system: `macos ventura 13.0.1`
- Is your project Javascript or Typescript: `javascript`

### Describe the bug

```bash
➜  backend git:(main) ✗ yarn build
Building your admin UI with development configuration...


● Webpack █████████████████████████ building (64%) 1/1 entries 13730/13834 dependencies 3409/3645 modules 48 active 
 ../../node_modules/date-fns/locale/ko/index.js

ModuleNotFoundError: Module not found: Error: Package path ./addon/display/placeholder is not exported from package
/Users/dev/workspace/monorepo/packages/backend/node_modules/codemirror (see exports field in 
/Users/dev/workspace/monorepo/packages/backend/node_modules/codemirror/package.json)

```

### Steps to reproduce the behavior

1. Upgrade to 4.6.1 from 4.5.1
2. yarn build

### Expected behavior

App builds

### Additional context

Yarn v3 in a monorepo

```json
  "dependencies": {
    "@strapi/design-system": "^1.6.3",
    "@strapi/plugin-documentation": "4.6.1",
    "@strapi/plugin-graphql": "4.6.1",
    "@strapi/plugin-i18n": "4.6.1",
    "@strapi/plugin-users-permissions": "4.6.1",
    "@strapi/provider-email-sendgrid": "4.6.1",
    "@strapi/provider-upload-aws-s3": "4.6.1",
    "@strapi/strapi": "4.6.1",
    "colors": "1.4.0",
    "pg": "8.9.0",
    "pg-connection-string": "^2.5.0",
    "qrcode": "^1.5.1",
    "react": "^17.0.2"
  },
```

From what I can see: 
`@strapi/admin` uses `"codemirror": "^5.65.11",` but the rest of `@strapi/` packages uses `"codemirror": "^6.0.0"`,

`"@strapi/design-system": "@1.6.3"` ~> `"@uiw/react-codemirror": "4.8.1"` ~> `"codemirror": "^6.0.0"`

I `rm -rf node_modules/ .cache/ yarn.lock` etc, nothing seems to work

**Comment by renegadevi** [comment]
I get same issue.

**Comment by renegadevi** [comment]
So, I started a new project and added one plugin after another, and it seems that Strapi 4.6 just broke a lot of plugins. Even official one I can't get installed which says it has been updated for 4.6.1

When I tried to add any of these, it will end up with `ModuleNotFoundError: Module not found: Error:`
```
"@bn-digital/strapi-plugin-field-uuid": "^1.1.7",
"@strapi/plugin-documentation": "^4.6.1"
"@strapi/plugin-sentry": "^4.6.1"
"strapi-plugin-local-image-sharp": "^1.4.0"
"strapi-plugin-multi-select": "^1.1.0"
"strapi-plugin-import-export-entries": "^1.18.0"
"strapi-plugin-navigation": "^2.2.4"
"strapi-plugin-populate-deep": "^2.0.0"
```

**Comment by joshuaellis** [comment]
It looks like a yarn resolution issue. Right now we don't technically support yarn3 so that could be part of your issue. As a possible solution you could try do a resolution – [codemirror](https://yarnpkg.com/configuration/manifest/#resolutions)

However, from the changelog of codemirror, it looks like a complete package change so it might not work.

**Comment by Martijn-Schoenmaker-Webbio** [comment]
For people encoutering this problem and cannot wait for 4.7.2 to release, installing `"codemirror": "5.65.11"` will do the trick.

**Comment by vallerydelexy** [comment]
frikkin hell, ive been installing dependency one by one in the past 1 hour. ffs. please strapi....

**Comment by antokhio** [comment]
this still affects 4.8.2 on windows

**Comment by joshuaellis** [comment]
Hi everyone, you should check your plugins, many plugins do not declare dependencies they use leading to issues like this, see this issue for more information – https://github.com/strapi/strapi/issues/16100

**Comment by pdavid0** [comment]
My solution was to add resolutions to the root `package.json`

```json
"resolutions": {
    "axios": "1.2.2",
    "@strapi/design-system": "^1.6.5",
    "codemirror": "5.65.12"
  }
```

**Comment by rohankm** [comment]
same problem any solution?

**Comment by Boegie19** [comment]
Update to newest strapi version only 3.7 and 3.7.1 should have this bug

**Comment by deevanych** [comment]
strapi 4.14.4, bun 1.0.9 same issue

**Comment by derrickmehaffy** [comment]
> strapi 4.14.4, bun 1.0.9 same issue

We don't support bun yet

**Comment by Katochimoto** [comment]
strapi 4.15.4, node 18, same

**Comment by Boegie19** [comment]
@Katochimoto please open a new issue for this
