### ISSUE TITLE
Lost jpg exif information by uploading and optimize

### ISSUE THREAD

**Issue by vv13** [strapi/strapi#15795]
### Required System information

- Node.js version:v18.12.1
- NPM version:8.19.2
- Strapi version:4.5.6
- Database:mysql@2.18.1
- Operating system:MacOS Venture 13.2
- Is your project Javascript or Typescript:TypeScript

### Describe the bug

Upload image lost Exif when choose size optimization or auto orientation, so I can't get full information of raw jpg.

### Steps to reproduce the behavior

1. Set size optimization to true.
2. Upload JPG in Media Library.
3. Download and see JPG Exif, it lost after uploaded.

### Expected behavior

Media library should remain Exif information.
### Screenshots
Before:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/9440756/218325270-35a4c130-d541-447f-b4eb-16a448916c43.png">
After:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/9440756/218325285-b177a761-fbff-42c7-9841-7bab21f5e047.png">

### Additional context

In `services/image-manipulation.js`, when `sizeOptimization` or `autoOrientation` is Truthy, sharp will work without output metainfo.

**Comment by Marc-Roig** [comment]
Hello there! Thank you for bringing this issue to our attention.

Currently, we do not store file metadata such as exif or other meta, as we believe that it may not be necessary or relevant for most users who use Strapi. Furthermore, storing large amounts of meta data could unnecessarily increase the size of the database.

However, there is a solution available for those who would like to store this metadata. You can create your own custom provider, which would allow you to store any metadata you would like by making use of `file`.`provider_metadata`. We have an example of how to create one in the Strapi monorepo ('packages/providers/upload-aws-s3/src/index.ts'). Another example can be found using our cloudinary provider (https://github.com/strapi/strapi/blob/28d82d333320d119ff5a3c6fae49d1d828e9bcb8/packages/providers/upload-cloudinary/src/index.ts#L72), where we store the metadata provided by Cloudinary.

We hope that helps! Let us know if you have any further questions or concerns.
If this is not enough for your problem or you think we can approach the issue differently I can reopen the issue again 🚀

**Comment by reslear** [comment]
@vv13 how did you resolve this issue?
