### ISSUE TITLE
Strapi REST API sort seems to treat lowercase as "after uppercase Z"

### ISSUE THREAD

**Issue by molul** [strapi/strapi#15803]
### Required System information

- Node.js version: v18.12.1
- NPM version: 9.1.3
- Strapi version: 4.6.1
- Database: postgres
- Operating system: MacOS Mojave
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

When I send a GET request to Strapi, sorting alphabetically, I get something like this:

Depeche Mode, Jamiroquai, Smashing Pumpkins, radiohead

I would expect "radiohead" to be between Jamiroquai and Smashing Pumpkins, but it seems that lowercase gets positioned after uppercase words.

### Steps to reproduce the behavior

1. Make three entries on a collection, with whatever text field set to A, C and b (this one lowercase)
2. Send a GET request to the collection, sortng by that text field
3. Check the results returned
4. They will display A, C, b, instead of A, b, C

### Expected behavior

I would expect uppercase and lowercase letters being treated the same when sorting alphabetically, or at least some method to do that.

**Comment by molul** [comment]
Just noticed a mistype in the "Steps to reproduce" (typed "during" instead of "sorting"). Sorry!

Any hope for this to be fixed anytime soon? I'm currently using a kinda dirty workaround to show my website users list sorted alphabetically and I'd like to get rid of it ^_^U

Thanks beforehand.

**Comment by Marc-Roig** [comment]
Hello! Thank you for raising this issue :) 
Unfortunately this is out of our control, as in Postgres for example, the order by logic (for uper case and lower case ordering) depends on the OS.

Reference: https://dba.stackexchange.com/questions/106964/why-is-my-postgresql-order-by-case-insensitive

We could do something like ORDER BY lower(column), but that would remove any indexing logic from the query, and could impact performance on people having large amounts of data in strapi.

In the future, we are going to implement virtual fields ( a field that derives from another one) , where you could define a column that's the lower case values of another. That would allow you to sort your column without having that issue.

We will continue this conversation internally just to see if there is any workaround that I am missing. I will keep you updated :)

**Comment by molul** [comment]
Oh, that's a pity, but you gave me an idea: just adding a new column which will have the same value as the other one but in lowercase, and then sorting by that column. 

Thanks!

**Comment by Marc-Roig** [comment]
We have debated about this problem internallly and our conclusion is this could be introduced by multiple enhancements:
- Virtual fields. Already explained in the previous comment.
  -  For now this field could be manually computed by using a service in Strapi (but it will not be virtual, as it needs to be stored in DB)
- Custom query functions. 
	- being able to do /api?sort=LOWER(${column}) or something similar
	
Both of this are enhancements we have on our mid/long term roadmap. 
For now I will close this issue as it is fixed for you, and if anyone needs one of those two enhancements I would strongly suggest adding them into https://strapi.canny.io/
