### ISSUE TITLE
RBAC Custom condition not working in Strapi ^4.5.0

### ISSUE THREAD

**Issue by tasola** [strapi/strapi#15835]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.0
- Database: postgres
- Operating system: OSX 12.15.1
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I noticed that since I upgraded Strapi to 4.5.0, one of my custom conditions for RBAC has stopped working. It is a condition handling relations.

I'm checking whether the user's email belongs to one of the allowed users in a list of relations to the content type Author. I'm doing this by simply defining: 

```
type User = {
  id: number
  email: string
}

(...)

async bootstrap({ strapi }) {
    await strapi.admin.services.permission.conditionProvider.register({
      displayName: 'Is in creator list',
      name: 'is-in-creator-list',
      plugin: 'admin',
      async handler(user: User) {
        return {
          Authors: { $elemMatch: { Email: user.email } },
        }
      },
    })
  },
```

This approach works fine on Strapi 4.4.0 and below, but when I try it one 4.5.0 and 4.6.0 - it doesn't. Has I missed any change in these releases which affects my implementation?

### Steps to reproduce the behavior

With ^4.5.0
1. Create a content type A
2. Create an instance of A
3. Create a new user X
4. Create a content type Author with a field 'email'
5. Create an instance of Author, and populate 'email' with the email of X.
6. Add a RBAC custom condition like the one described above.
7. Assign a role to X which only allows them to read A if they fulfil "Is in creator list" (see implementation above).
8. Login with X
9. Try to read the instance of A; you are not allowed to. One interesting fact is that you can still see the list view of A:s (only with instances which the user would have been able to read in 4.4.0). It is when you try to click one of them (to go into the edit view) you are prompted with `Information: You are not allowed to see this document`. If you truly wouldn't be allowed to see the document, it shouldn't even show up in the list view, right?

Try to downgrade to 4.4.0, rebuild etc, and try to read the instance of A again - you are now allowed to.

### Expected behavior

I expect the custom condition to work the same in ^4.5.0 as 4.4.0 - to allow the user to read A in the above example.

I'll of course be happy to provide more information about this issue if needed!

Thanks in advance

**Comment by gu-stav** [comment]
This might be related to another fix we did in 4.5.0: https://github.com/strapi/strapi/pull/14784 I will have a look!

**Comment by derrickmehaffy** [comment]
@gu-stav this feels like another breaking change that happened with relational performance.

**Comment by gu-stav** [comment]
@Marc-Roig Could you have a look?

**Comment by tasola** [comment]
@Marc-Roig have you gotten the chance to look into this?

**Comment by Marc-Roig** [comment]
not yet sorry, I will schedule this for monday.

**Comment by Marc-Roig** [comment]
@tasola  hello :) 
Since 4.5.0 we changed how we handle relations, we do not load relations in the Admin UI or the requests the backend receives from them.

There were a couple of aspects that we did not take into consideration when making this change, such as this one.

I will be checking if there are workarounds for this during this week.

**Comment by tasola** [comment]
@Marc-Roig I see. Thank you for the update!

**Comment by tasola** [comment]
@Marc-Roig @joshuaellis Is it possible to get an estimation on when a fix for this might be released? In case it's possible to reproduce and everything, of course.

**Comment by joshuaellis** [comment]
> @Marc-Roig @joshuaellis Is it possible to get an estimation on when a fix for this might be released? In case it's possible to reproduce and everything, of course.

No unfortunately we cannot give an estimation at this time. We'll update the ticket when we have made progress it on this. Thank you for your patience.

**Comment by webholics** [comment]
We are affected by this, too. Its really frustrating to work with Strapi in its current state. Documentation is not up to date or just not existing. And on top of that changes which are obviously breaking weren't mentioned at all and this issue is open for almost 2 months now.

**Comment by webholics** [comment]
Thanks for the feedback. My main issue with the interface here is that its very intransparent and hard to debug which types of queries you can use here. Seems to strongly depend internally which relations are populated. Maybe it could make sense to completely switch away from that declarative style. e.g. similar to how lifecycles work.

**Comment by Convly** [comment]
Yeah, I agree the custom conditions need better syntax and/or better documentation.
We can't break anything regarding the syntax in V4 (hence why we're trying to find a fix to make the old conditions work again), but it might be something worth looking into for V5.
Thanks for your feedback

**Comment by ryanleung96** [comment]
@Convly for the documentation, would the team plan to add the typescript version?

**Comment by ryanleung96** [comment]
Hi all, any idea when the fix will release?

**Comment by Convly** [comment]
Hi @ryanleung96, we met with other engineers two days ago to find a solution for this. We believe we might have found a way to resolve this issue without impacting the performance for every query.
We will embed that in our next sprint and hopefully resolve this as soon as possible :slightly_smiling_face: 
Thanks for your patience!

**Comment by Convly** [comment]
> @Convly for the documentation, would the team plan to add the typescript version?
That's a nice catch, it would be nice to add that too indeed

**Comment by ryanleung96** [comment]
> Hi @ryanleung96, we met with other engineers two days ago to find a solution for this. We believe we might have found a way to resolve this issue without impacting the performance for every query. We will embed that in our next sprint and hopefully resolve this as soon as possible 🙂 Thanks for your patience!

Thanks, coz I need this feature to restrict user to perform CRUD actions on different collection types with restricted values

**Comment by ryanleung96** [comment]
> > @Convly for the documentation, would the team plan to add the typescript version?
> 
> That's a nice catch, it would be nice to add that too indeed

Sounds good, typescript version really helps
