### ISSUE TITLE
Nothing is logged on login failed

### ISSUE THREAD

**Issue by mithenks** [strapi/strapi#15845]
### Required System information

Node.js version: 16.17
Strapi version: 4.5.6
Database: MariaDB 10.7
Operating system: Linux

### Describe the bug

Strapi doesn't log anything when the auth process failed.

### Steps to reproduce the behavior

Example 1: 
```
curl -X POST -H 'Content-type: application/json' -d '{"identifier":"aaa", "password":"bbb"}' localhost:9000/api/auth/local
```
Example 2: 
```
curl -X POST -H 'Content-type: application/json' -d '{}' localhost:9000/api/auth/local
```

### Expected behavior

If I try to call a `PUT` method on the same route, I have a `405` error logged.
```
[2023-02-16 05:55:54.989] http: PUT /api/auth/local (3 ms) 405
```
Also, if I try to access `/api/users/me` without any auth token I get a `401` logged.
```
[2023-02-16 05:58:41.092] http: GET /api/users/me (14 ms) 401
```
So I expect that Strapi logs:
 * `400` if the payload validation fails
 * `401` if username/password are invalid
 * and so on...

**Comment by derrickmehaffy** [comment]
Confirmed on v4.6.1

**Comment by akshatakulkarni25** [comment]
hey @derrickmehaffy can i work on this issue

**Comment by akshatakulkarni25** [comment]
hey @mithenks can i work on this issue

**Comment by derrickmehaffy** [comment]
> hey @mithenks can i work on this issue

https://github.com/strapi/strapi/issues/14577

**Comment by MaelChemeque** [comment]
I'm not sure I fully understand the problem.
When I try to reproduce your issue with the following command : 
```
curl -X POST -H 'Content-type: application/json' -d '{"identifier":"aaa", "password":"bbb"}' localhost:1337/api/auth/local
```
I get this answer :
```
{"data":null,"error":{"status":400,"name":"ValidationError","message":"Invalid identifier or password","details":{}}}
```

**Comment by alexandrebodin** [comment]
I could not reproduce this error. We do send a 400 error at least in strapi v4.11.4+

I'll close as resolved for now. Feel free to ping us if you want reproduce it in the latest version of Strapi.
