### ISSUE TITLE
Duplicate field in EditView, DynamicZone

### ISSUE THREAD

**Issue by NguyenSon2310** [strapi/strapi#15856]
### Required System information

- Node.js version: v14.21.3
- NPM version: 6.14.18
- Strapi version: v4.6.1
- Database: PostgreSQL
- Operating system: Ubuntu 20.04
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Duplication field in EditView, when I choose an item in field, the field duplicate has same value

### Screenshots
<img width="930" alt="Screen Shot 2023-02-17 at 4 30 21 PM" src="https://user-images.githubusercontent.com/33917382/219995752-ffb243ec-ff9d-4145-a8c6-7c0ed79f27da.png">

<img width="947" alt="Screen Shot 2023-02-17 at 4 35 40 PM" src="https://user-images.githubusercontent.com/33917382/219995764-83557bd2-b2c3-4eb7-b18a-ac30f82c4ccf.png">

**Comment by jhoward1994** [comment]
Hi @NguyenSon2310, thanks for the issue. However, I was unable to recreate the problem with the details you have provided. Are you able to provide more details on your setup?

- What type of relation you are using?
- What content type is on either side of the relation?

Thanks 🙂
