### ISSUE TITLE
Error message accidentally added to the database

### ISSUE THREAD

**Issue by fedecarg** [strapi/strapi#1586]
Information:

- Node.js version: v10.1.0
- npm version: 5.6.0
- Strapi version: 3.0.0-alpha.12.6
- Database: MongoDB
- Operating system: Linux

**What is the current behavior?**

See image attached, the property `vat_rate`:

![error_codes](https://user-images.githubusercontent.com/61066/42822365-c9937d0c-89d2-11e8-8de9-abaee7cea8f7.png)

**Steps to reproduce the problem**

POST an String value to a parameter that only accepts an Integer.

**What is the expected behavior?**

- Error message should not be added to the `var_rate` property.
- Client should be notified whenever there's a data type error.

**Suggested solutions**

None

**Comment by derrickmehaffy** [comment]
@fedecarg there is no validation layer, right now the database is the only real validation and mongo doesn't really have that. MySQL will toss an error about it and won't save it. See the [vote page](https://strapi.io/vote) the validations option is on there.

**Comment by fedecarg** [comment]
@derrickmehaffy Oh I see, thanks for letting me know!

**Comment by fedecarg** [comment]
Updated the title of the issue. Even if there's no validation, error message should not be added to the `vat_rate` field

**Comment by lauriejim** [comment]
Hello @fedecarg , you can easily add a filter on received params and your model's attributes.

Feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
This issue have the same topic of this one https://github.com/strapi/strapi/issues/845

**Comment by fedecarg** [comment]
@lauriejim I think I got it, so it's up to the developer to manipulate user input using `beforeCreate` and similar callback maethods

**Comment by lauriejim** [comment]
Can you confirm your need is the issue I linked please.

**Comment by gabrielFCC** [comment]
> @lauriejim I think I got it, so it's up to the developer to validate user input using beforeCreate and similar callback methods

Can you confirm if it is the right place (models) to implement validation layer? What is your advice on validation, currently is joi the best soltuion?

**Comment by lauriejim** [comment]
This issue will be fix when we will work on validation layer.
On the params received by the request and before requesting the database.

**Comment by lauriejim** [comment]
Caused by this issue https://github.com/strapi/strapi/issues/2591
We move on this one now.
