### ISSUE TITLE
Missing fr translations

### ISSUE THREAD

**Issue by edlefebvre** [strapi/strapi#15862]
### Required System information

- Node.js version: v16.18.0
- NPM version: 8.19.2
- Strapi version: 4.6.1
- Database: MySQL
- Operating system: Linux (Ubuntu)

### Describe the bug

I don't know if there is a better place for that kind of remarks but I'm seeing missing translations in the French version of Strapi, go to admin and them:

In media library, upper buttons are not translated:
![image](https://user-images.githubusercontent.com/1556109/220093683-f24d7b52-6d41-45c6-9ed5-a4eb8e92adcd.png)

In media library, Folders and Assets sub titles:
![image](https://user-images.githubusercontent.com/1556109/220094644-e06558c6-7519-4f4e-80ad-c38e1a334a0d.png)

In content, relation field is not translated:
![image](https://user-images.githubusercontent.com/1556109/220094053-a003ea4b-b3d3-4d65-a9e7-c1a662868799.png)

### Expected behavior

Those texts should be in French.

### Additional context

I would be happy to help translate if there is a way to do it, please let me know.

**Comment by enzoclock** [comment]
Also missing : 
<img width="816" alt="screen" src="https://user-images.githubusercontent.com/98805541/220109119-87a28fe4-5d8a-429c-9606-23a7a642679a.png">

**Comment by edlefebvre** [comment]
Also in post edit:
![image](https://user-images.githubusercontent.com/1556109/220138517-e53397c4-a8ed-4a86-9b1f-7d91fe302d06.png)

And when uploading a file:
![image](https://user-images.githubusercontent.com/1556109/220139008-d9c3ea35-fce8-4c41-a219-4a947831e798.png)

**Comment by edlefebvre** [comment]
I've just updated the issue with the template, thanks

**Comment by joshuaellis** [comment]
You can submit a PR to add these translations if you're interested in helping still :)

**Comment by edlefebvre** [comment]
@joshuaellis here it is :-) : https://github.com/strapi/strapi/pull/15936

**Comment by Boegie19** [comment]
@edlefebvre Have all the issues been fixed so can this issue be closed or are there still once that are not fixed that you talked about above.
