### ISSUE TITLE
Publish-webhook sends publishedAt as `null` when publishing

### ISSUE THREAD

**Issue by tasola** [strapi/strapi#15865]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.6.0
- Database: postgres
- Operating system: OSX 12.15.1
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When I publish an entry, the publish-webhook sends an entry with the field `publishedAt` as `null`.

I use a webhook that currently reacts to all available changes and sends it to one endpoint. I will primarily use this for [on-demand incremental static regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation) in next.js, so I'm very much interested in the field `publishedAt`, which will define if the entry's page should be built or not.

### Steps to reproduce the behavior

1. Create a content type X
2. Create a webhook and check all boxes (let it trigger on every available event). Let the webhook request your endpoint Y.
3. Add a log in Y which prints the request body.
4. Create a new entry of type X. The webhook will send an "entry"-object with `publishedAt` as `null` to Y, which of course is expected since it's not published yet.
5. Publish the new entry. The webhook will now send two requests to Y; one for the update-event, and one for the publish-event. The update-event will have its `publishedAt` field populated with whatever time it was when you published. The direct subsequent publish-event will however have its `publishedAt` field populated with `null`.

If anything I would have expected the update-event to have publishedAt as null, but the fact that the actual publish-event sends `publishedAt` as `null` just makes no sense to me. Am I doing anything wrong?

### Expected behavior

The publish-event triggered by the webhook should have its field `publishedAt` populated with the timestamp for when it was published.

### Screenshots

![Screenshot 2023-02-20 at 14 54 21](https://user-images.githubusercontent.com/24315038/220127683-eb2401dc-3807-49cf-a2c9-bd963cc1727b.jpg)

**Comment by Marc-Roig** [comment]
Hello :) Thank you for that amazing issue description.

We opened a PR to fix that https://github.com/strapi/strapi/pull/15942
We plan to release this in 4.7.1 on the 8th of March .
