### ISSUE TITLE
Provided upload file size is rounded to kilobytes instead of bytes

### ISSUE THREAD

**Issue by ciriousjoker** [strapi/strapi#15875]
### Required System information

- Node.js version: v16.19.0
- NPM version: 9.4.0
- Strapi version: 4.6.0
- Database: PostgreSQL
- Operating system:  macOS Ventura
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When trying to upload a file, Strapi provides a rounded kilobyte size to the provider.

### Steps to reproduce the behavior

1. Set a breakpoint in one of the upload providers
2. Try to upload a file
3. File size is incorrect

### Expected behavior

Strapi should provide the exact number of bytes instead.

### Screenshots

**macOS:**
<img width="77" alt="Bildschirm­foto 2023-02-21 um 16 49 44" src="https://user-images.githubusercontent.com/16866223/220393359-2eb33d5c-86bd-4d85-9307-3a6c30d8f665.png">

**Strapi:**
<img width="132" alt="Bildschirm­foto 2023-02-21 um 16 49 56" src="https://user-images.githubusercontent.com/16866223/220393394-9fbdd1c6-72df-43d9-b8e2-a3e677b72abf.png">

### Code snippets

Example code can be found here:
https://github.com/viveakrt/strapi-provider-upload-vimeo/blob/main/index.js

However, any plugin that exposes `uploadStream` should be affected by this (local provider as well).

### Additional context

Reason for why I think this is a bug:
- Vimeo requires the exact file size during upload, otherwise it will never finish the upload status.
- The data (file size) and the representation (rounded kilobyte number) should be two separate concerns and the data shouldn't be hidden or modified just for convenience

**Comment by Marc-Roig** [comment]
Hello :) 
I agree, the file size should always be in bytes as it's a standard everywhere.

We are in a difficult position with this issue though, as we follow semver, we can not introduce any breaking change.
If we were to change this know, any other provider that uses the file size (in KB) would be broken. :/ 

We will mark this issue to be tackled in V5 (next major version), as I agree, it should not be in kilobytes. I thought your workaround is enough for now, and thank you for sharing it here.

For now, I will be closing the issue as we can not tackle it in v4.X.X
