### ISSUE TITLE
Media Library: `updated_at` url param is appended incorrectly

### ISSUE THREAD

**Issue by ciriousjoker** [strapi/strapi#15885]
### Required System information

- Node.js version: v16.19.0
- NPM version: 9.4.0
- Strapi version: 4.6.0
- Database: PostgreSQL
- Operating system: macOS Ventura
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The url that's used to preview the file is incorrect.

### Steps to reproduce the behavior

1. Upload a file via a provider that returns a url with a `?some=param`at the end
2. The preview url just appends `?updated_at=...` at the end without regard for existing query parameters.
3. Example: `https://player.vimeo.com/progressive_redirect/playback/<some_id>/rendition/360p/file.mp4?loc=external&oauth2_token_id=...&signature=...?updated_at=2023-02-22T15:16:40.206Z`

### Expected behavior

New query parameter should be merged with existing one.

`https://player.vimeo.com/progressive_redirect/playback/<some_id>/rendition/360p/file.mp4?loc=external&oauth2_token_id=...&signature=...&updated_at=2023-02-22T15:16:40.206Z`

### Additional context

Usually this probably has no negative effect, but Vimeo will refuse to return a mp4 file if this is incorrect.

**Comment by ciriousjoker** [comment]
This seems to be the faulty line:

https://github.com/strapi/strapi/blob/bd6c0fc10c8c1e1aedc5fc918034d864bcce7d40/packages/core/upload/admin/src/utils/createAssetUrl.js#L18

**Comment by joshuaellis** [comment]
@jhoward1994 & @Marc-Roig your S3 Bucket work – would this address this issue? I believe it does.

**Comment by jhoward1994** [comment]
> @jhoward1994 & @Marc-Roig your S3 Bucket work – would this address this issue? I believe it does.

I think it would as we would remove the addition of these query params in the admin panel (see https://github.com/strapi/strapi/pull/15773) 

wdyt @Marc-Roig ?

**Comment by Marc-Roig** [comment]
indeed, this will be fixed as we are removing the addition of these query params as @jhoward1994  pointed out!

**Comment by ciriousjoker** [comment]
If you remove the parameter, I assume the only downside is that the preview file could be stale if you were to delete and re-upload a different file that results in the same preview url, at least until the caches are cleared?
