### ISSUE TITLE
"There are no fields yet" but I'm sure for I added a lot of content type field already

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1588]
**Informations**
- **Node.js version**: 10.x.x
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongodb
- **Operating system**: ubuntu 18

**What is the current behavior?**
"There are no fields yet" but I'm sure for I added a lot of content type field already

**Steps to reproduce the problem**
I don't know for this

**What is the expected behavior?**
It should be create collection in my database but it not create any collection but create folder content in api folder

1. **In Content Type Builder**
![image](https://user-images.githubusercontent.com/12433101/42828611-f244a1aa-8a12-11e8-9122-6f968af6e3f9.png)

2. **In My Content Type Menu**
![image](https://user-images.githubusercontent.com/12433101/42828676-fd60fa98-8a12-11e8-823b-2d456463fc42.png)

**Suggested solutions**

**Comment by fedecarg** [comment]
This is because your server is not restarting whenever your make some changes. I'm using `pm2` and this command worked:

`NODE_ENV=development pm2 start strapi --no-pmx --name=commerce-api -- start`

**Comment by xeastcrast** [comment]
@fedecarg  What is --no-pmx option use for?

**Comment by xeastcrast** [comment]
@fedecarg On old version of strapi when I change or modifier some thing in my api, Server will auto restart  But on current version of strapi that I migrated from old version,It don't auto restart when I change anything

Sorry for my englist syntax

**Comment by derrickmehaffy** [comment]
@xeastcrast 

Pmx is something that reports metrics from your application to pm2, which Strapi doesn't have as it wasn't designed to run with pm2.

So it's being disabled to save resources that is looking for events that won't happen.
