### ISSUE TITLE
Localisation relation data carried over when switching locales showing incorrect data

### ISSUE THREAD

**Issue by lachlanagnew** [strapi/strapi#15890]
### Required System information

- Node.js version: 14.21.2
- NPM version: 6.14.17
- Strapi version:  4.6.2
- Database: Postgres
- Operating system: Ubuntu 22.04.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Looks like an issue when changing locales with a relationship, the relation data from the previous locale is carried over until a refresh.

### Steps to reproduce the behavior

1. Create two localization locales
2. Create a new single type with a single relation one and localization on
3. Go to single type and add a relation + save
4. Change to other location that hasn't been created yet and relation is already there
5. refresh and it will disappear

### Expected behavior

When switch location the previous relationships shouldn't be there

### Screenshots

The first locale with the relation saved
<img width="1271" alt="Screenshot 2023-02-23 at 10 43 20 am" src="https://user-images.githubusercontent.com/32250463/220789315-834b6e7d-d128-49fd-89fc-147f11b475e4.png">

Switch to another locale and the previous relation is there
<img width="1274" alt="Screenshot 2023-02-23 at 10 43 29 am" src="https://user-images.githubusercontent.com/32250463/220789327-a2eeff72-e11d-4552-993f-ff3095f6e392.png">

After a refresh it is gone
<img width="1270" alt="Screenshot 2023-02-23 at 10 43 37 am" src="https://user-images.githubusercontent.com/32250463/220789338-ac23e28c-0901-442c-8452-8415e019c547.png">

### Additional context

Might be something I have done wrong but it happens with all of my relations.

**Comment by joshuaellis** [comment]
Thanks for the report, this is it's core, the same issue as #15743 so this will be marked as duplicate.
