### ISSUE TITLE
Admin panel crashes when changing order of components in a dynamic zone

### ISSUE THREAD

**Issue by muffeeee** [strapi/strapi#15893]
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.6.1
- Database: Postgres
- Operating system: Ubuntu Linux 
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When doing one of the following, the admin panel crashes:
- Changing the order of components in a dynamic zone (in content manager)
- Removing any dynamic zone component EXCEPT the last one

...if the components contain relational data.

However, this works just fine if all the components being moved around are collapsed - but the application will crash again if you "uncollapse" those components before saving.

This seems to be an admin panel/front-end issue only.

### Steps to reproduce the behavior

1. Create a dynamic zone 
2. Create some components in that DZ, and add some relational fields to them.
3. Go to "content manager" and start editing the collection type that you created the DZ in
4. Add some component entries to the DZ, save the document
5. Try to change their order, or try to remove the first/middle components. Removing the last one (usually) works fine.

### Expected behavior

I expected reordering and deleting of components in DZ to work flawlessly.

### Screenshots

https://imgur.com/a/gk6NTWY

### Code snippets

This is the error message being produced, although I see that it's probably not very helpful:
```
TypeError: Spread syntax requires ...iterable not be null or undefined
performIteration
(anonymous function) — content-manager.3ca50099.chunk.js:1005:19348
(anonymous function) — main.16aedacf.js:24:43807
Jl — main.16aedacf.js:940:55772
Wr — content-manager.3ca50099.chunk.js:1005:23315
Yu — main.16aedacf.js:940:54505
ws — main.16aedacf.js:940:64251
Dt — main.16aedacf.js:944:990
ge — main.16aedacf.js:944:918
ue — main.16aedacf.js:944:770
Ks — main.16aedacf.js:942:10969
Ks
(anonymous function) — main.16aedacf.js:940:39359
(anonymous function) — main.16aedacf.js:972:3787
vs — main.16aedacf.js:940:39306
Di — main.16aedacf.js:940:39241
Dn — main.16aedacf.js:944:7152
(anonymous function) — main.16aedacf.js:972:3787
(anonymous function) — main.16aedacf.js:944:6321
B — main.16aedacf.js:972:2839
(anonymous function) — main.16aedacf.js:972:1529
```

### Additional context
Given that this works fine if the component is collapsed, I assume this has something to do with iterating over the content of the components in the DZ.

**Comment by joshuaellis** [comment]
Something isn't right here, you're saying you're using `4.6.1` but you've supplied a screenshot:

![image](https://user-images.githubusercontent.com/37798644/220869122-9a144d0a-ff7b-40c6-bc43-3a6049691a9e.png)

That is of a UI we don't have anymore, DZ components should have a drag handler. Have you upgraded recently? Have you rebuilt the admin panel since that upgrade?

**Comment by muffeeee** [comment]
> Something isn't right here, you're saying you're using `4.6.1` but you've supplied a screenshot:
> 
> ![image](https://user-images.githubusercontent.com/37798644/220869122-9a144d0a-ff7b-40c6-bc43-3a6049691a9e.png)
> 
> That is of a UI we don't have anymore, DZ components should have a drag handler. Have you upgraded recently? Have you rebuilt the admin panel since that upgrade?

That's odd, I could have sweared I rebuilt after upgrading. But alas, rebuilding did the trick.

Sorry about that, but thanks for the swift reply :)
