### ISSUE TITLE
forgot-password leads to: TypeError: Cannot read property 'options' of undefined at forgotPassword

### ISSUE THREAD

**Issue by Khanji** [strapi/strapi#1589]
**Informations**
- **Node.js version**: 10.6.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongodb 4.0.0
- **Operating system**: Ubuntu 18.04 LTS

**What is the current behavior?**
http://localhost:1337/admin/plugins/users-permissions/auth/forgot-password 
is giving an error when trying to send for forgot-password. 
The error that is being returned by the server is: 
`TypeError: Cannot read property 'options' of undefined
    at forgotPassword (/api/plugins/users-permissions/controllers/Auth.js:183:49)`

**Steps to reproduce the problem**
step 1: strapi new api
step 2: cd api > strapi start
step 3: navigate to localhost:1337/admin
step 4: create first account with username password and email
step 5: logout
step 6: on login screen press forgot password
step 7: type in valid emailaddress and press "send email" 
ERROR

**What is the expected behavior?**
expected behavior is that after step 7 user receives an email where user can follow instructions to retrieve user-account.

**Suggested solutions**
I've checked the code and it looks like the options is there but is not accessible the way it is defined in the code.

**Comment by derrickmehaffy** [comment]
Can confirm this on a new 12.7.1 project with mysql

**Comment by lauriejim** [comment]
Hello @Khanji , thank you for this repport.

I think it's an easy issue to fix, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by Khanji** [comment]
Hey @lauriejim will do

**Comment by lauriejim** [comment]
Hello @Khanji. Did you migrate your project from an other version ?
And make your you use clean new database for your project.

**Comment by dseedah** [comment]
Any updates or quick fixes for this issue?

**Comment by dseedah** [comment]
MongoDB 4.0

**Comment by dseedah** [comment]
@bahdcoder unfortunately, that didn't work on mine installation

**Comment by bahdcoder** [comment]
@dseedah could you please show me your code so I can see if you did the right thing? Because this works on mine just fine.

**Comment by dseedah** [comment]
@bahdcoder 

updateEmailTemplate: async (ctx) => {
    if (_.isEmpty(ctx.request.body)) {
      return ctx.badRequest(null, [{ messages: [{ id: 'Cannot be empty' }] }]);
    }

    await strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
      key: 'email'
    }).set({value: ctx.request.body['email-templates']});

    ctx.send({ ok: true });
  },

**Comment by svencowart** [comment]
I have reproduced this bug on Strapi version 3.0.0-alpha.13.1 with a fresh strapi install and fresh DB using MongoDB 4.0.0.

**Comment by devaublanc** [comment]
I also have reproduced this bug with v3.0.0-alpha.13.1 version after updating the Email template `UsersPermissions.updateEmailTemplate` maybe an issue related to the strapi.store ?
