### ISSUE TITLE
Validation fires on API imported, non-required fields when trying to publish

### ISSUE THREAD

**Issue by marceldupr** [strapi/strapi#15907]
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.19.3
- Strapi version:  4.6.1
- Database: PostgreSQL
- Operating system: Mac OSX
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When I do a `yarn strapi export` and import the data onto another strapi instance of exactly the same environment (even on the same box), then the data imports as expected, however, when I try to publish then the email field (which is not set as required) tries to validate and gives the message 'Invalid Email'. When I type anything in the box and delete it, and try publishing again, then it works. 

### Steps to reproduce the behavior

1. use strapi export and import
2. Go to a collection with a 'non-required' email field
3. Try to publish
5. Type anything in the box and publish again
6. Works

### Expected behavior

To not fire the validation on publish if field is not required.

**Comment by Convly** [comment]
Hi, while waiting for your answer, I've been trying to replicate the issue but failed to do so. Would you be able to upload a minimal reproduction of the bug?
- Created an app + created data for a content type using draft & publish and that contains both a required string field and a non-required email field.
- Create data with published/non-published entries with and without email.
- Exported the data
- Deleted the entries from my app
- Imported the exported data
- Tried to publish entries with or without email, and it worked fine
