### ISSUE TITLE
Enviroment variables not replaced on `server.json` config file

### ISSUE THREAD

**Issue by maturano** [strapi/strapi#1590]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongo
- **Operating system**: WSL with Ubuntu 18.04 on Windows 10

**What is the current behavior?**
The `database.json` is using environment variables (👍). Trying to use the same patter on `server.json` file is not working.

**Steps to reproduce the problem**
Edit the `server.json` config file (tried for production env) with this content:
```json
{
  "host": "localhost",
  "port": 1337,
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": false  
},
  "admin": {
    "path": "/",
    "build": {
      "host": "/",
      "backend": "${process.env.STRAPI_BACKEND}",
      "plugins": {
        "source": "backend"
      }
    }
  }
}
```

**What is the expected behavior?**
The environment variable been replaced with their value. Instead, if is not defines is replaced with `undefined`; if defined is "not replaced" (the requests go to `/$%7Bprocess.env.STRAPI_BACKEND%7D/`)

**Suggested solutions**
🤷‍♂️

**Comment by maturano** [comment]
🤔 ... I just checked again. There are some replacement but is inconsistent, as far I understand. Let me share a couple of tests:

1. With `STRAPI_BACKEND=coucou`
![serverconfig_nohttp](https://user-images.githubusercontent.com/5768813/42903117-6b94451e-8a96-11e8-82ab-59feaa19266e.PNG)

- All the plugins are requested to the same domain
- Te replacement for plugins are as "basepath" (_domain.com/**replaced_value**/plugin/main.js_)
- The API calls are done at the same domain, without replacement (_domain.com/**${env.variable}**/plugin/main.js_)


2. With `STRAPI_BACKEND=https://coucou`
![serverconfig_withhttp](https://user-images.githubusercontent.com/5768813/42903695-48814fa2-8a98-11e8-9215-8f2d60bc4903.PNG)

- **Half of** the plugins are requested to "correct" domain (_coucou_).
- Te replacement for plugins that are requested to the same domain, is done as an empty string (_domain.com//plugin/main.js_)
- The API calls are done at the same domain, without replacement (_domain.com/**${env.variable}**/plugin/main.js_); shouldn't be done to the _coucou_ domain???

... please help me to understand what I'm doing wrong. But, as an user, I would expect that plugins and API request were done to _coucou_ domain...

**Comment by lauriejim** [comment]
@maturano I miss my C/C try `STRAPI_BACKEND=.... strapi start`
It's not in any build process

**Comment by maturano** [comment]
I got this following the guide to [deploy de admin panel in a different server](https://strapi.io/documentation/advanced/customize-admin.html#deploy-the-administration-panel-on-another-server-aws-s3-azure-etc-than-the-api). So, there should be a build process.

The "funny" thing is that hardcoding the value works. I miss showing that case:

![serverconfig_harcoded](https://user-images.githubusercontent.com/5768813/42962429-356f850e-8b57-11e8-8c39-8a20ad64744a.PNG)

- The API requests go to the correct domain
- The plugins are requested to the correct domain*

So... I would expect the same behavior using an environment variable.

---
* Half of it. I still don't understand why is this, but the point is that works.

**Comment by maturano** [comment]
So, is this a bug or is just some misunderstanding of my side? 🤔

**Comment by maturano** [comment]
I took a look on this and create the PR #1667 With that, I have this behavior:

![serverconfig_patch](https://user-images.githubusercontent.com/5768813/43471942-e1b1aa96-94b1-11e8-905a-714194391555.png)

That is I was expected. What do you thing @lauriejim ?
