### ISSUE TITLE
populate in repeatable component isn't working

### ISSUE THREAD

**Issue by jhackr** [strapi/strapi#15904]
### Required System information

- Node.js version: 18.4.1
- NPM version: 9.3.1
- Strapi version: 4.6.2
- Database: mysql
- Operating system: ubunto
- Is your project Javascript or Typescript: Js

### Describe the bug

I have a repeatable component with a title and text and img
an image dosn't appear even if I do ?populate=*

### Steps to reproduce the behavior

1. Do a new repeatable component with img
2. add one entry and try to fetch them with ?populate=*
3. you will see just the content without an img

### Additional context

I have a multi language in my site.

**Comment by derrickmehaffy** [comment]
This is intended for now as the `*` only populates the first level, you will need to declare the population specifically to go more than 1 level.

Related feature request: https://feedback.strapi.io/developer-experience/p/add-additional-glob-population-options
