### ISSUE TITLE
Change Readme Picture

### ISSUE THREAD

**Issue by cpaczek** [strapi/strapi#15917]
This is the most nit-picky thing but you can use [github image themeing](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) to render a dark version of this screenshot if the user is in GitHub dark mode. If you tell me how to create the screenshot I can make a PR. I thought the screenshot was from food advisor but it seems like its a different place. 

![image](https://user-images.githubusercontent.com/25715982/221353109-d6889600-b378-4270-b7ae-e6020783b7b9.png)

**Comment by rothardo** [comment]
@derrickmehaffy is this issue up for grabs?

**Comment by derrickmehaffy** [comment]
Sure, we don't assign issues, people can just open PRs

**Comment by rothardo** [comment]
may I get some more insight upon this issue so that I can move further with the same

**Comment by bengoh815** [comment]
I assume the task would involve recreating the GIF using a dark-themed Strapi

**Comment by rothardo** [comment]
Hi there, so what should be the credentials for strapi login page? 
I am not able to find any documentation to go about that? can anyone please help here?

**Comment by derrickmehaffy** [comment]
screenshot was already updated, this issue is no longer needed
