### ISSUE TITLE
Deprecation warning logs on Mongo

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1592]
**Informations**
- **Node.js version**:9.0.0
- **npm version**:5.5.1
- **Strapi version**:3.0.0-alpha-12.7.1
- **Database**:MongoDB
- **Operating system**:Linux

**What is the current behavior?**
I see this warning in terminal for a fresh project:
```
(node:12760) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

**Steps to reproduce the problem**
* Install Strapi version 3.0.0-alpha-12.7.1
* Create new project
* Run project.

**What is the expected behavior?**
-

**Suggested solutions**
It seems Strapi core needs some update and refactor to fix this.

**Comment by lauriejim** [comment]
Hello @mnlbox , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by maturano** [comment]
Just to add the information: This warning if from the Mongo driver for NodeJS. I let here the documentation for the new methods:
https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#countDocuments
https://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#estimatedDocumentCount

**Comment by lauriejim** [comment]
Now there is more deprecation:

```
(node:73444) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:73444) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:73444) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:73444) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:73444) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
(node:73444) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
```

**Comment by dannydtk** [comment]
Bump. 

MongoDB: 4.0.3
Strapi: v3.0.0-alpha.14.4.0
Node: 10.12.0
NPM: 6.4.1

1. strapi start
2. Logs:
```
(node:17179) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:17179) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:17179) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
(node:17179) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
```

**Comment by adrianoresende** [comment]
I have same error of @dannydtk 
Someone solved?

**Comment by adrianoresende** [comment]
I get error after I create this fields

![image](https://user-images.githubusercontent.com/798755/50358798-b50c3500-0541-11e9-8733-56745b63c680.png)

**Comment by derrickmehaffy** [comment]
@adrianoresende `pack_size` is the problem, no symbols or spaces: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#model--field-naming-schemes

**Comment by pierrebarbaroux** [comment]
> Bump.
> 
> MongoDB: 4.0.3
> Strapi: v3.0.0-alpha.14.4.0
> Node: 10.12.0
> NPM: 6.4.1
> 
> 1. `strapi start`
> 2. Logs:
> 
> ```
> (node:17179) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
> (node:17179) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
> (node:17179) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
> (node:17179) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
> ```

Same problem here.

MongoDB: v4.0.5
Strapi: v3.0.0-alpha.17
Node: v10.8.0
NPM: 6.2.0

**Comment by pierrebarbaroux** [comment]
> Bump.
> 
> MongoDB: 4.0.3
> Strapi: v3.0.0-alpha.14.4.0
> Node: 10.12.0
> NPM: 6.4.1
> 
> 1. `strapi start`
> 2. Logs:
> 
> ```
> (node:17179) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
> (node:17179) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
> (node:17179) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
> (node:17179) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
> ```

Hello,
Same problem here.

MongoDB: v4.0.5
Strapi: v3.0.0-alpha.17
Node: v10.8.0
NPM: 6.2.0

Any ideas?

**Comment by derrickmehaffy** [comment]
@dannydtk @pierrebarbaroux Unlikely the Strapi team will get to this in the near future unless it breaks something if you wanted to create a PR to fix them.

**Comment by lauriejim** [comment]
@Aurelsicoko fixed it - https://github.com/strapi/strapi/pull/2682
