### ISSUE TITLE
Import, Export, and Transfer Copy Data Between Different Media Providers on Sender and Receiver Side

### ISSUE THREAD

**Issue by maxbraeutigam** [strapi/strapi#15940]
### Required System information

- Node.js version: v18.14.2
- NPM version: 9.3.1
- Strapi version: 4.7.0
- Database: mysql => psql
- Operating system: Linux => Heroku
- Is your project Javascript or Typescript: JS

### Describe the bug

I am trying the new transfer feature as introduced in [v4.7.0](https://github.com/strapi/strapi/releases/tag/v4.7.0) (https://github.com/strapi/strapi/pull/15607). On the sender side my set-up is a mysql database instance of Strapi 4.7.0 with local file support. On the receiver side I am running a Strapi 4.7.0 instance in Heroku with postgres and Amazon AWS S3 bucket. The transfer is working perfectly without any problems reported on the console. Both content and files are transferred but the files are not stored in the AWS bucket but locally. If I am updating a file in Strapi, the updated file can be found in AWS bucket but not the original one after transfer.

### Steps to reproduce the behavior

1. Start transfer.
```sh
NODE_ENV=production yarn strapi transfer --to https://***/admin --to-token ***
```
![grafik](https://user-images.githubusercontent.com/78037966/221698221-aee7bf45-1e29-406f-bc29-665aa2bd9099.png)

2. On the receiver side, I see all files and I can download all of them
![grafik](https://user-images.githubusercontent.com/78037966/221698770-cb7ca15a-e742-428a-b642-f8c6514a1889.png)

3. AWS Bucket is empty (unexpected)
![grafik](https://user-images.githubusercontent.com/78037966/221699229-695bdda0-a0dc-4917-ab0c-e84820593245.png)

4. Replaced files on the receiver side in the Strapi Media Library are stored in AWS bucket again. (expected)
![grafik](https://user-images.githubusercontent.com/78037966/221699584-fd71b12b-8e13-4f6a-941d-e06e9c264a8b.png)

### Expected behavior

All files end up in Amazon AWS S3 bucket after `yarn transfer` is completed.

**Comment by maxbraeutigam** [comment]
Hi @Convly - as you introduced the feature in #15607, I am adding you here. Hope, this is okay. Cheers and thank you very much. Max

**Comment by derrickmehaffy** [comment]
For the moment we are aware of this and the implementation of 3rd party upload providers (excluding local basically) is intended, we will need to iterate on the feature to enable support for 3rd party upload providers.

cc @marcoautiero

**Comment by maxbraeutigam** [comment]
Hi @derrickmehaffy - thanks for the very quick reply.

I am using `@strapi/provider-upload-aws-s3` in version 4.7.0 as well, which is from my point of view not a third-party tool but a Strapi-owned one.

Further, can I circumvent the bug via `export` and `import`?

**Comment by derrickmehaffy** [comment]
Sorry but what I mean by 3rd party is non-local, I wasn't really clear there but the current transfer feature won't send media to any provider other than local at the moment. It's something we are already aware of and was planning to do at a later date. DEITS if the first feature that we are doing rapid iteration on.

**Comment by Convly** [comment]
Hey and thanks for opening this issue

As Derrick rightfully explained, we're not handling any upload provider outside of the local one for the moment (see: https://docs.strapi.io/dev-docs/data-management/transfer), as it would've delayed the release of the feature (quite a complex management behind the scene regarding providers' 'assets).

I guess we could transform this issue into a feature request, what do you think? :thinking:

**Comment by maxbraeutigam** [comment]
Hi @Convly – I am perfectly fine with making it a feature request.

I was thinking that the `transfer` command uses the normal [REST API](https://docs.strapi.io/dev-docs/api/rest) for the data transfer because this would hide all the complexities of database providers and media providers from the transfer. And it would mean that you can keep single models (tables) in sync, which is from my point of view more interesting than copying everything or nothing. The one-to-one copy via `import`, `export`, and `transfer` can normally done with standard replication techniques of the databases and storage. The [GraphQL API](https://docs.strapi.io/dev-docs/plugins/graphql) would also allow for only using the API due to the ability to introspect the models. 

All in all, Strapi is a great product and I highly appreciate your work. Please excuse my escalating remarks.

**Comment by Convly** [comment]
Hey @maxbraeutigam, thanks for sharing your perspective!

Unfortunately using the REST (or GraphQL) content API won't be possible for the transfer feature:
- It doesn't include all the data (automatically remove password and private attributes for instance)
- It would have to bypass routes specifics such as policies or custom user middlewares
- It would suffer from sanitize operations on data creation or update
- It means we lose the ability to stream data through a websocket API (=> big performance drops)

To give you more context, we thought about making use of those APIs when making some research before the feature developement, but we quickly came to the conclusion that we needed a new way of transferring our data to bypass all the Strapi, user and plugins' custom logic.

Hope it helps clarifying things :slightly_smiling_face:

**Comment by maxbraeutigam** [comment]
Hi @Convly – I was pretty sure that you did your homework. No offence. But the new features do not fit my workflows (so it might be a personal problem). I assume that there are two standard use cases:

1. I need a 1-to-1 copy: So I use standard replication features of my existing infrastructure, e.g. `pg_dump` and `pg_restore`.
2. I need to transfer "hand-picked" data, e.g. a few models, from different Strapi installations: in an ideal world, `import`, `export`, `transfer` step in here.

The second workflow might be needed for example to develop a new Strapi environment with different plugins, different providers, different infrastructure. In order to get the `transfer` running, I had to install useless plugins on the source side just to get the command running. In this migration scenario, I don't care much about speed.

Taking the prerequisites (only local files, exactly the same schema, exactly the same plugins between source and destination) into account, one could ask the heretic question: What is the advantage over normal `dump`, `restore` and `cp`/`rsync`?

Again, it might just be my perspective. And again, I highly appreciate your work and I love Strapi. ❤️

**Comment by derrickmehaffy** [comment]
We are currently working on a transfer pull script that should work with converting the different media providers (testing it right now actually) so we should have next week.

For Transfer Push that will take a bit more time, I believe the team plans to work on during the week of April 3rd so at most it should be within the next month.

Export/Import will mirror the transfer respectively.

**Comment by JakeElder** [comment]
I'd love to see this feature released. Thank you for all the excellent work on Strapi 🚀

**Comment by JakeElder** [comment]
@derrickmehaffy - Is there an ETA on when we might see this released? All the best

**Comment by derrickmehaffy** [comment]
I believe they will have it in the next sprint starting this week, it should be done within the next 2 weeks give or take.

**Comment by JakeElder** [comment]
That's great @derrickmehaffy, thank you. Is there any update on this?

**Comment by derrickmehaffy** [comment]
They are still working on it, there is a PR for it here: https://github.com/strapi/strapi/pull/17105 but we are waiting for a fix to the upload provider for Strapi cloud before we merge it.
