### ISSUE TITLE
Unable to get an item from a collection for a specific locale

### ISSUE THREAD

**Issue by 1saifj** [strapi/strapi#15945]
### Required System information

Node.js version: 16.19.1
Yarn version: 1.22.19
Strapi version: 4.7.0
Database: Sqlite
Operating system: Windows 11
Javascript

### Describe the bug

I have a collection `faq-groups` that enabled localization for it, it is working fine when I trying to fetch the locale for the collection, by:

http://localhost:1337/api/faq-groups?locale=ar

```json
{
      "data": [
            {
                  "id": 2,
                  "attributes": {
                        "Name": "عام",
                        "Description": "fssf",
                        "createdAt": "2023-02-22T13:28:46.344Z",
                        "updatedAt": "2023-02-27T07:37:21.103Z",
                        "publishedAt": "2023-02-22T13:33:38.389Z",
                        "locale": "ar"
                  }
            }
      ],
      "meta": {
            "pagination": {
                  "page": 1,
                  "pageSize": 25,
                  "pageCount": 1,
                  "total": 1
            }
      }
}
```

but it failed to retrieve the locale for a specific item from this collection, by:

http://localhost:1337/api/faq-groups/1?locale=ar

and this returned only English locale:

```js

{
      "data": {
            "id": 1,
            "attributes": {
                  "Name": "general",
                  "Description": "srfd",
                  "createdAt": "2023-02-22T13:28:40.645Z",
                  "updatedAt": "2023-02-27T08:31:54.555Z",
                  "publishedAt": "2023-02-22T13:33:25.442Z",
                  "locale": "en"
            }
      },
      "meta": {}
}

```

### Steps to reproduce the behavior

Create a collection of your choice, enable the Internationalization for it, and fetch one item after adding data with its localization. 

### Expected behavior

Getting the data in a requested locale for an item from a collection.

### Screenshots

![image](https://i.imgur.com/z4LirxZ.png)

**Comment by Marc-Roig** [comment]
Hello :) 
Currently, in strapi each locale is assigned to a different id, by looking at your first response, the id of the AR entity is '2'.

However, you can retrieve, for entity 1, the other localizations.

From the[ strapi docs](https://docs.strapi.io/dev-docs/plugins/i18n#getting-localized-entries-with-the-locale-parameter):
The localizations (object) can be included if specifically requested by appending ?populate=localizations to the URL (see [relations population documentation](https://docs.strapi.io/dev-docs/api/rest/populate-select#population). It includes a data array with a list of objects, each of them including the id and attributes of the localization.

Would that be enough for your use case?

**Comment by 1saifj** [comment]
> Hello :) Currently, in strapi each locale is assigned to a different id, by looking at your first response, the id of the AR entity is '2'.
> 
> However, you can retrieve, for entity 1, the other localizations.
> 
> From the[ strapi docs](https://docs.strapi.io/dev-docs/plugins/i18n#getting-localized-entries-with-the-locale-parameter): The localizations (object) can be included if specifically requested by appending ?populate=localizations to the URL (see [relations population documentation](https://docs.strapi.io/dev-docs/api/rest/populate-select#population). It includes a data array with a list of objects, each of them including the id and attributes of the localization.
> 
> Would that be enough for your use case?

This won't be enough if I want to get the questions for this group with id "1" in locale "AR", I have a relationship between the groups and questions (one2many: each group will hold many questions).

http://localhost:1337/api/faq-groups/1?locale=ar&populate=faq_questions

Is there any workaround to make this work?

**Comment by Marc-Roig** [comment]
you could do
http://localhost:1337/api/faq-groups/1?&populate=localizations.faq_questions

this way you could have access to the other locales of that entity with faq_questions populated.

**Comment by Marc-Roig** [comment]
I am closing this issue for now :) As it has a workaround and it would be more of an enhancement or feature request (which could be requested on [canny](https://strapi.canny.io/)

If for some reason the query doesnt work for you we can reopen this issue!

**Comment by 1saifj** [comment]
> 



> you could do http://localhost:1337/api/faq-groups/1?&populate=localizations.faq_questions
> 
> this way you could have access to the other locales of that entity with faq_questions populated.

This didn't resolve my issue, unfortunately, so could you reopen it?

**Comment by Marc-Roig** [comment]
> This won't be enough if I want to get the questions for this group with id "1" in locale "AR", I have a relationship between the groups and questions (one2many: each group will hold many questions).

Don't you get the populated one2many relation when doing the request? It should be inside the localizations object. 
Otherwise there is no other alternative to get that data, based on how localizations is designed in strapi.

**Comment by nicolaselielll** [comment]
I have the same problem

**Comment by nurikaraca** [comment]
solution  ?
