### ISSUE TITLE
Broken admin panel when `url` is set to a relative/absolute path

### ISSUE THREAD

**Issue by eyelash** [strapi/strapi#15948]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.6
- Database: MariaDB
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

The Strapi admin panel is broken when setting the `url` config inside `server.ts` to a relative/absolute path.

### Steps to reproduce the behavior

1. In a new Strapi project, open the `config/server.ts` (or `config/server.js`) config file and set the [`url`](https://docs.strapi.io/dev-docs/configurations/server) option to `/strapi`.
```typescript
// server.ts
export default ({ env }) => ({
  // ... other keys ...
  url: '/strapi',
});
```
2. Run `npm run build` and start the application.
3. Set up a reverse proxy such that `http://localhost:80/strapi/subpath` gets proxied to the Strapi instance at `http://localhost:1337/subpath`, for example with the following nginx config:
```
server {
  listen       80;
  server_name  localhost;
  location /strapi/ {
    proxy_pass http://localhost:1337/;
  }
}
```
4. Open your browser at `http://localhost:80/strapi/admin`.

### Expected behavior

I expect that the admin panel is opened and fully functional.

### Actual behavior

Instead of the admin panel I get the following error:
```
{"data":null,"error":{"status":404,"name":"NotFoundError","message":"Not Found","details":{}}}
```

### Additional information

The admin panel gets set up here with the route `/strapi/admin` which does not work since the proxy redirects `http://localhost:80/strapi/admin` to `http://localhost:1337/admin`.

https://github.com/strapi/strapi/blob/5c9a88be046906e70626d81267bee15243d00b79/packages/core/admin/server/routes/serve-admin-panel.js#L32

The problem originates in the function `getConfigUrls`.

https://github.com/strapi/strapi/blob/5c9a88be046906e70626d81267bee15243d00b79/packages/core/utils/lib/config.js#L6-L63

`serverUrl` gets set to `/strapi`, `adminUrl` gets set to `/strapi/admin` and then since they don't start with `http` the `adminPath` incorrectly gets set to `/strapi/admin` (the same as `adminUrl`). The `adminPath` should be set to `/admin` if the `forAdminBuild` argument is `false`. This would fix the admin panel route.

**Comment by derrickmehaffy** [comment]
URLs should be absolute and you are missing the strip prefix from the config: https://docs.strapi.io/dev-docs/deployment/nginx-proxy

You need to rewrite the subpath out like this: `rewrite ^/test/?(.*)$ /$1 break;` we don't modify the koa router with the prefix for all routes so the actual koa router still expects that the prefix doesn't exist normally all the URL does it change the internal references for uploads, email templates, and changes how the admin communicates with the backend.

If you still can't get it to work with my suggestions, respond back and we can take another look.

**Comment by eyelash** [comment]
According to to the [documentation here](https://docs.strapi.io/dev-docs/configurations/server):

> The url can be relative

Is this a bug in the documentation? I will have to look into rewriting the subpath since I'm not very familiar with configuring nginx. Please note that my nginx configuration already removes the prefix as I wrote in the first post.

**Comment by derrickmehaffy** [comment]
I think those docs need to be changed

You aren't expressly stripping the prefix You're just proxying it. Nginx can get really weird if you're not using direct rewrites.

**Comment by derrickmehaffy** [comment]
If you don't have to use Nginx you may want to try caddy instead, much easier to configure

**Comment by eyelash** [comment]
I will have to use nginx for our production setup but I'm also using a [Vite](https://vitejs.dev/) devserver for local development with the following config:

```
  server: {
    proxy: {
      "^/strapi": {
        target: "http://localhost:1337/",
        ws: true,
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/strapi/, ""),
      },
    },
  },
```

and I'm running into the same issue described in the first post with that setup.

**Comment by eyelash** [comment]
By the way I tested the fix I described in the first post and everything seemed to work. Is there any reason against changing the `getConfigUrls` function as I described since that would allow to actually use a relative/absolute path (without the domain) which would allow for building a single Docker image for example and deploy it to multiple domains without rebuilding.

**Comment by derrickmehaffy** [comment]
The biggest issue is because we are statically building the react application and the koa backend is directly serving that react application.

Since react is CSR it means that the requests to koa backend are being executed from the clients browser which means that browser needs to know exactly where to call the backend.

If you want a single docker container for all environments it's best to eject the admin and serve it elsewhere (either from its own docker container or through simple static site hosting).
