### ISSUE TITLE
npm install error when run this command in admin folder

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1594]
**Informations**
- **Node.js version**: 10.x.x
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alphan.12.6
- **Database**: mongodb
- **Operating system**: ubuntu 18.x

**What is the current behavior?**

**>When I npm install in strapiproject/admin folder**
![image](https://user-images.githubusercontent.com/12433101/42906436-4ff4b090-8b05-11e8-9725-e75b8b0e12ff.png)

**Comment by maturano** [comment]
What are the messages before that?

**Comment by xeastcrast** [comment]
@maturano 
![npminstalladmin](https://user-images.githubusercontent.com/12433101/42961246-74c43220-8bb8-11e8-8286-52914975aa3b.jpg)

**Comment by maturano** [comment]
Ok... Some dependency is trying to build `pngquant`, but apparently you don't have the requirements.

First, see if you have the binary installed. What is the output of executing `pngquant --version`?

Then, you will need to install `libpng-dev` and `cmake`. You can do it executing `sudo apt install libpng-dev build-essential`.

Then, try again and let us know if it works to try to solve it (document it at least somewhere).

**Comment by xeastcrast** [comment]
@maturano Now i can use npm install in admin folder
Thanks for your help :+1:
