### ISSUE TITLE
MySQL/Postgres allow configuration to use UUID instead of ID

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1595]
**What is the expected behavior?**

Currently mongo by default uses a uuid (guid) as its primary ID column, for security and tracking purposes when using MySQL or Postgres, strapi should allow the current `ID` field to instead use the `UUID` field as its primary index.

This should be configurable at the model level and not globally as you can see from this article:
http://kccoder.com/mysql/uuid-vs-int-insert-performance/

Using this globally would cause a severe performance decrease, however in cases like users (especially anon users) you will still want to track them even if they wish to remain anon.

So instead of something like this on the model:
```
create table innodb_auto_increment (
  id integer auto_increment not null,
  primary key (id)
) type=innodb;

create table innodb_integer (
  id integer not null,
  primary key (id)
) type=innodb;

create table innodb_uuid (
  id char(36),
  primary key (id)
) type=innodb;
```

You would instead do something like this:

```
create table innodb_uuid_no_key (
  id char(36)
) type=innodb;

create table innodb_uuid_no_key_indexed (
  id char(36),
  index index1 (id)
) type=innodb;

create table innodb_uuid_no_key_unique_indexed (
  id char(36),
  unique index index1 (id)
) type=innodb;
```

**Comment by lauriejim** [comment]
Hello @derrickmehaffy can you check this issue please https://github.com/strapi/strapi/issues/1202
I think it's the same topic.

**Comment by derrickmehaffy** [comment]
@lauriejim your right, I didn't use the search function first *facepalm*

Closing this in order to promote discussion on linked issue.
