### ISSUE TITLE
Mailgun provider doesn't work with node 18

### ISSUE THREAD

**Issue by danielbitzer** [strapi/strapi#15954]
The provider requires mailgun.js 5.2.2 which doesn't work with node 18.

There seem to be a couple of issues on the mailgun.js repo about node 18 e.g. https://github.com/mailgun/mailgun.js/issues/275

I forced strapi to use mailgun.js 8.1.0 and it worked again.

**Comment by pepijn-vanvlaanderen** [comment]
+1

**Comment by svenvreenen** [comment]
Hi @danielbitzer how did you force strapi to use the other version if i may ask.

**Comment by danielbitzer** [comment]
@svenvreenen with [Yarn selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/). With npm you can use overrides.
