### ISSUE TITLE
Strapi 4.7.0 throws a validation error when trying to create an entry that has a required image field

### ISSUE THREAD

**Issue by Kazdan1994** [strapi/strapi#15951]
## Bug report

Strapi throws a validation error when trying to create an entry that has a required image field. It works when it's not marked as required.

### Required System information

- Node.js version: v16.18.0
- NPM version: 9.4.0
- Strapi version: 4.7.0
- Database: sqlite
- Operating system: linux Fedora 37
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I wrote a test which should create an article with an image. When image is not a field required the test passed successfully, the image is upload and link to the article.

But if I set the image as a required field (simply edit `src/api/article/content-types/article/schema.json` attributes.image.required to true) I have a bad request with the message :
`
{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"ValidationError","message":"ValidationError"}],"errors":{"image":["image must be defined."]}}],"data":[{"messages":[{"id":"ValidationError","message":"ValidationError"}],"errors":{"image":["image must be defined."]}}]} `

### Steps to reproduce the behavior

1. Clone the repo [https://github.com/Kazdan1994/strapi-populate-example.git](https://github.com/Kazdan1994/strapi-populate-example.git)
2. yarn install
3. yarn test
4. Should failed with error

Works if you set image field in article content-type as not required

Works on previous version of Strapi 4.6.2

### Expected behavior

The test should pass if image is required cause files.image is not empty. I should upload an image when an article is created.

Thank you for your answers :)

### Additional context

[Seems similar to this previous closed issue.](https://github.com/strapi/strapi/issues/5418)

**Comment by Marc-Roig** [comment]
Hello, in 4.7.0 we added a validator to check if media is passed in the api https://github.com/strapi/strapi/pull/14670

Could you share how you are sending the file? Maybe the validator doesn't account for that format and we could refactor it.

**Comment by Kazdan1994** [comment]
> Hello, in 4.7.0 we added a validator to check if media is passed in the api #14670
> 
> ~Could you share how you are sending the file? Maybe the validator doesn't account for that format and we could refactor it.~
> 
> Nevermind, completely missed you shared your project!! I will check during today.

Hi. Thank you for your answer. Don't hesitate to ask me more infos :)

**Comment by fabio-nettis** [comment]
Experiencing some issues as well. Starting from version 4.7.0 upwards I am not able to pass an empty media array even if the `required` flag is set to false, was forced to downgrade to 4.6.3.

**Comment by Marc-Roig** [comment]
@fabio-nettis We will provide a fix for 4.7.2 🙏

**Comment by fabio-nettis** [comment]
@Marc-Roig Thank you! Appreciate the hard work. 👍🏻

**Comment by Marc-Roig** [comment]
@Kazdan1994 I am looking at trying to find a solution for your issue. 
We didn't account for direct upload of image on entity creation, I am looking if there is a viable alternative.

**Comment by Kazdan1994** [comment]
@Marc-Roig thank you for your help. Actually I have managed direct upload on entry creation, it will be a cool feature in Strapi. My point is mostly about the validator cause it's hard to find the cause of the error.

**Comment by shommey** [comment]
Facing the same issue with 4.7.x.

@Kazdan1994 Can you please share your solution for uploading during entity creation?
Thanks.

**Comment by Marc-Roig** [comment]
Hello :) We will be reverting the media validator for next release, so we have more time to work on a solution which includes this and a proper required media validation.

**Comment by Kazdan1994** [comment]
Thank you for your help :)
