### ISSUE TITLE
Strapi 4.7.0 other language issues

### ISSUE THREAD

**Issue by ekimv** [strapi/strapi#15956]
### System information

- Node.js version: 16.19.1
- Strapi version: 4.7.0 (but also on 4.6.2)
- Database: MySQL

### Describe the bug

I have some issues with languages :
- When having some relations in a translatable collection type (or single), If I add a relationship in the first language, I save, then I switch language to another, the relation is already filled with the previous one selected in first language (although it is empty) - but even If I save, the relations are not saved
- On single types, sometimes, I try to edit another language, and the front hangs with an error :
```
main.cd8abed7.js:1892 TypeError: Cannot read properties of null (reading 'length')
    at Xt (content-manager.e6d72a08.chunk.js:743:7288)
    at zu (main.cd8abed7.js:1890:54675)
    at Qu (main.cd8abed7.js:1890:64509)
    at dc (main.cd8abed7.js:1894:10061)
    at Bc (main.cd8abed7.js:1894:989)
    at Xc (main.cd8abed7.js:1894:917)
    at Jl (main.cd8abed7.js:1894:768)
    at Cu (main.cd8abed7.js:1892:11072)
    at main.cd8abed7.js:1890:39501
    at n.unstable_runWithPriority (main.cd8abed7.js:1922:3830)
```

The solution I have found to avoid this is to refresh (F5) the page after changing the language, so that previous data is void and current data is correctly loaded. But it is not very user friendly...

**Comment by ekimv** [comment]
Maybe it is connected to this issue :
https://github.com/strapi/strapi/pull/15900

**Comment by ekimv** [comment]
Maybe it is connected to this issue :
https://github.com/strapi/strapi/pull/15900

**Comment by joshuaellis** [comment]
Yes, while it's not 1:1 in the report the issue you're facing is the same as this one – https://github.com/strapi/strapi/issues/15743 that #15900 will fix.

I'm going to close this issue as a duplicate.
