### ISSUE TITLE
No difference between Relations ToOne and ToMany

### ISSUE THREAD

**Issue by ekimv** [strapi/strapi#15960]
### Required System information

- Node.js version: 16.19.1
- Strapi version: 4.7.0
- Database: MySQL

### Describe the bug

Actually, there is no difference between for relationship with multiple choices or only one possible choice.
It is not a real "bug" but an improvment of the visual

For example, I have a component where you have to choose one gallery from a collection (so a relation) ; and you can only choose one gallery.
The current display :
![image](https://user-images.githubusercontent.com/75667665/222155806-efe6ebf2-fd0f-4c0f-aa88-9539ac3e0b79.png)

A user can imagine that he can add multiple Gallery, because there is the "Add relation" label in the dropdown, and the selected value is below

Could it be possible to have this kind of display instead ? :
![image](https://user-images.githubusercontent.com/75667665/222156730-d006cee5-1bc6-4644-9ae4-a2e3b1d4a375.png)

By the way, thank you for all improvements until now ! The system is now faster than it was before on the first v4 versions !

**Comment by joshuaellis** [comment]
Thanks for raising this, we typically hold all enhancement / feature requests in Canny and someone has already raised this with us here – https://strapi.canny.io/customization/p/simplify-input-for-single-relations

Feel free to upvote and follow that canny ticket :)
