### ISSUE TITLE
Start and limit are not working in populate with entity service  v4.7.1 but this was working old version

### ISSUE THREAD

**Issue by ismailerden** [strapi/strapi#15973]
This code was working old version (v4.6.2)

![image](https://user-images.githubusercontent.com/16348119/222446937-693af903-ebcc-4d53-85b8-906a5b515125.png)

this code return courses populate one record. But new version return one record all datas

**Comment by Archao-ME** [comment]
I think this is a big problem. It seems that the data is limited first and then sorted. If limit: 1, then only one data will be populated. There was no problem with the previous version, but after the update the code that used this logic had problems.
