### ISSUE TITLE
Error when I add user from User Model

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1599]
**Informations**
- **Node.js version**: 10
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongodb
- **Operating system**: ubuntu18

**What is the current behavior?**

> ### This Users,Permissions,User,validation,failed,password,Path,password,is,required is already taken

This Error occur when i create user in User model in content type ui

**Comment by lauriejim** [comment]
Hello @xeastcrast , please follow the issue template so we can get a better understanding about the origin of your bug.

I need steps you did and terminal logs.

I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
