### ISSUE TITLE
Docker Strapi export import data restore via CLI not working

### ISSUE THREAD

**Issue by f1sle** [strapi/strapi#15990]
### Required System information

- Node.js version: docker image - node-18:alpine 
- NPM version: 9.5.0
- Strapi version: 4.7.1
- Database: docker image - postgres:14.6-alpine
- Operating system: macOS
- Is your project Javascript or Typescript:
JS

### Steps to reproduce the behavior

1. Start services via: docker compose -f docker-compose-dev.yml up -d (Two services: DB & Strapi backend)
2. Log into strapi docker container via: docker exec -it *container-id* sh
3. Export of the data: yarn strapi export --file backup
4. Copy backup.tar.gz to another machine docker container
5. Log into docker container on another machine: docker exec -it *another-machine-cont-id* sh
6. Restore from a backup: yarn strapi import -f backup.tar.gz

P.S: API_TOKEN_SALT is created and can be seen by: echo $API_TOKEN_SALT

Getting:

`
(node:281) Warning: Missing transfer.token.salt: Data transfer features have been disabled.
Please set transfer.token.salt in config/admin.js (ex: you can generate one using Node with `crypto.randomBytes(16).toString('base64')`)
For security reasons, prefer storing the secret in an environment variable and read it in config/admin.js. See https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/environment.html#configuration-using-environment-variables.
(Use `node --trace-warnings ...` to show where the warning was created)
Starting import...

error: [FATAL] EBUSY: resource busy or locked, rename '/opt/app/public/uploads' -> '/opt/app/public/uploads_backup_1677883195169'
Import process failed.
error Command failed with exit code 1.
`

In the end I'm getting that entities were transferred successfully, but actually they're still missing.

### Expected behavior

Restore should proceed without errors; data collections and relations should be imported successfully.

![image](https://user-images.githubusercontent.com/39921649/222847308-af68989e-e0a5-47d5-8ade-e41820f699b0.png)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/15613
