### ISSUE TITLE
Binding to localhost doesn't work.

### ISSUE THREAD

**Issue by matthias-schulz** [strapi/strapi#1600]
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongoDB v4.0.0
- **Operating system**: ubuntu 16.04

**What is the current behavior?**
Binding to localhost doesn't work. Is there something I'm doing wrong?

```
root@42 /var/www/cms #  strapi start
(node:25141) DeprecationWarning: collection.count is deprecated, and will be removed in a
[2018-07-19T19:10:30.076Z] info Time: Thu Jul 19 2018 21:10:30 GMT+0200 (Central European
[2018-07-19T19:10:30.077Z] info Launched in: 2414 ms
[2018-07-19T19:10:30.077Z] info Environment: development
[2018-07-19T19:10:30.077Z] info Process PID: 25141
[2018-07-19T19:10:30.077Z] info Version: 3.0.0-alpha.12.7.1 (node v10.6.0)
[2018-07-19T19:10:30.077Z] info To shut down your server, press <CTRL> + C at any time

[2018-07-19T19:10:30.078Z] info ☄️  Admin panel: http://localhost:1337/admin
[2018-07-19T19:10:30.078Z] info ⚡️ Server: http://localhost:1337
```

**Steps to reproduce the problem**
I just need to start the server.

**What is the expected behavior?**
The web interface is not only accessible via localhost.

**Suggested solutions**
No idea.

**Comment by derrickmehaffy** [comment]
@matthias-schulz check your firewall, even though it shows as bound to localhost you can still access it on your public ip. :smile:

**Comment by matthias-schulz** [comment]
I'm sorry, I said that wrong. I want it to be accessible only via localhost.

**Comment by derrickmehaffy** [comment]
@matthias-schulz https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-16-04

**Comment by matthias-schulz** [comment]
Too bad I thought it would work without the firewall. Is this behaviour desired?

**Comment by maturano** [comment]
I don't understand if you do a change and was expect a particular behavior 🤔 ...

However, I would say that been a web application and an "API provider", I could expect to been accessible to you (a client) can reach it.

**Comment by derrickmehaffy** [comment]
@matthias-schulz that is just standard practice lol, you should be running a firewall anyway :smiley:

**Comment by derrickmehaffy** [comment]
@maturano realistically Strapi should be firewalled off and nginx should be proxying it with SSL

**Comment by matthias-schulz** [comment]
Excuse me if I'm not clear. English is not my first language.
I haven't made any changes to the configuration. I was expecting strapi to be accessible only through the local address. To make strapi accessible from the internet, I was going to use a proxy. But as already mentioned, strapi can also be reached via public ip on port 1337. This is unexpected for me. If a firewall is the only solution, then so is that.

**Comment by derrickmehaffy** [comment]
@matthias-schulz Yes you will need to use a firewall.

**Comment by matthias-schulz** [comment]
Thanks for your support.
