### ISSUE TITLE
Error with mouse drag and drop reordering with nested repeatable components

### ISSUE THREAD

**Issue by Yizhachok** [strapi/strapi#16004]
### Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Strapi version: 4.7.1
- Database: Any
- Operating system: Any
- Is your project Javascript or Typescript: TS

### Describe the bug

When trying to reorder nested repeatable component with mouse it change order of root components and fall in to error screen. When using keyboard reorder feature all works ok. Seems like drag and drop context one for 2 drag zones that cause mistake with drop target.

### Steps to reproduce the behavior

1. Create component with some fields (for example 'name')
2. Create component with repeatable component field (for example names) and choose previous component
3. Create a collection with repeatable component field (for example groups).
4. Create new entry with such structure
```
groups:
  ---
  groupName: group 1
  names:
    ---
    name: name 1
  ---
  groupName: group 2
  names:
    ---
    name: name 2
    ---
    name: name 3
    ---
    name: name 4
```
5. Save
6. Try reorder name 4 with other name in group 2

### Expected behavior

Name 4 changed his order with other name inside group 2. Group 1 and 2 stay on their places.

### Screenshots

![image](https://user-images.githubusercontent.com/1171048/223116963-6eeb8f88-b8d7-4477-9bb4-60631f2b6631.png)

**Comment by ChamperNet** [comment]
I have an exact error on Strapi v4.6.1 (node 18). I've noticed that error appeared only if the number of elements is more than 10.
