### ISSUE TITLE
Error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly

### ISSUE THREAD

**Issue by arunabhdas** [strapi/strapi#16011]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

Strapi fails with the following error in the logs 

`Error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly`

Full stack trace

```
Mar 6 06:13:41 PM  [2023-03-06 23:13:41.532] error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly
Mar 6 06:13:41 PM  Error: select "t0"."id" from "admin_users" as "t0" limit $1 - Connection terminated unexpectedly
Mar 6 06:13:41 PM      at Connection.<anonymous> (/opt/render/project/src/shopfrontapp/node_modules/pg/lib/client.js:132:73)
Mar 6 06:13:41 PM      at Object.onceWrapper (node:events:627:28)
Mar 6 06:13:41 PM      at Connection.emit (node:events:513:28)
Mar 6 06:13:41 PM      at Connection.emit (node:domain:489:12)
Mar 6 06:13:41 PM      at Socket.<anonymous> (/opt/render/project/src/shopfrontapp/node_modules/pg/lib/connection.js:57:12)
Mar 6 06:13:41 PM      at Socket.emit (node:events:525:35)
Mar 6 06:13:41 PM      at Socket.emit (node:domain:489:12)
Mar 6 06:13:41 PM      at TCP.<anonymous> (node:net:322:12)
Mar 6 06:13:41 PM      at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Mar 6 06:13:41 PM  error Command failed with exit code 1.
Mar 6 06:13:41 PM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Mar 6 06:13:43 PM  ==> Detected Node version 18.14.2
```

### Steps to reproduce the behavior

Restart strapi in PROD
Keep strapi running
See error in logs

### Expected behavior

No runtime errors.

### Env

Node.js version: v18.14.2
Strapi version: v4.6.1
Database: postgres 14

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by mwoelk** [comment]
Relates to: https://github.com/knex/knex/issues/3523

**Comment by Yannvrn** [comment]
When using Docker, change the pool min value to 0 as Docker will kill any idle connections, making it impossible to keep any open connections to the database (https://knexjs.org/guide/#pool)

https://docs.strapi.io/dev-docs/configurations/database#database-pooling-options
