### ISSUE TITLE
How to write node script that has access of strapi.services?

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi#1601]
**How to write node script that has access of strapi.services?**
We want to write some node js scripts to do some database insertions. How can we use strapi.services.xxx.add in our script? Please advise.

**Comment by lauriejim** [comment]
`strapi.services...` have to be called in a running Strapi application.
You can write it in `./config/functions/bootstrap.js`, this file is called when you start your server.

**Comment by ceefour** [comment]
I think what @demobo-com is asking is how to create a Node **script** outside of a Strapi **web server**.

For example, to run maintenance operations.

This would be similar to `yarn run strapi console`, but without the console.

**Comment by ibqn** [comment]
This one should be opened and not closed. There is no solution or workaround suggested. 
Even in this example of strapi usage 

https://github.com/strapi/foodadvisor/tree/master/api

some ugly scripts are used to seed data into strapi. So every one is welcomed to reinvent the wheel :1st_place_medal:

**Comment by guillermodoghel** [comment]
bump

**Comment by derrickmehaffy** [comment]
Locking as this is a question not a bug report.

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
