### ISSUE TITLE
can't start on nodejs 10.x.x

### ISSUE THREAD

**Issue by tarol** [strapi/strapi#1602]
**Informations**
- **Node.js version**: 10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongdb
- **Operating system**: macos

**What is the current behavior?**
npm start throw error
node[20312]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100033d65 node::Abort() [/usr/local/bin/node]
 2: 0x100032dab node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x10005a505 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x10022b83f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x10022a9d8 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x10022a3a7 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x248ef7b041bd
 8: 0x248ef7b0f27d
 9: 0x248ef7b8b8c0
10: 0x248ef7b13a09
11: 0x248ef7b13a09
12: 0x248ef7b13a09
Abort trap: 6

**Steps to reproduce the problem**
npm start

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @tarol , Can't understand your issue, can you please provide us full steps you did to have this issue.

**Comment by tarol** [comment]
1. strapi new test
2. npm start

**Comment by maturano** [comment]
I remember also seen this, but with the latest version at this time (`3.0.0-alpha.13`) I can't reproduce the error.

![node10](https://user-images.githubusercontent.com/5768813/43287624-2b8ea6f2-90eb-11e8-9a13-de05c1b01afb.PNG)

@tarol Are you getting the same error with the latest version?
