### ISSUE TITLE
Getting 403 when the page reloads in content-manager

### ISSUE THREAD

**Issue by shwetaAjmeraInfotech** [strapi/strapi#16039]
### Required System information

- Node.js version: 16.0.0
- Strapi version: 4.6.1
- Database: postgres
- Operating system: Windows

### Describe the bug

Page is redirecting to 403 when the page reloads in content-manager API.

### Steps to reproduce the behavior

1.Strapi login
2. Click on Content Manager
3. View any content-type (collection-type or single-type)
4. Reload the page
5. See the page redirecting to 403 and error "You don't have the permissions to access that content" is displayed.

### Expected behavior

Page should be open correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/100762873/224036233-0c39de9c-26aa-4bfd-b160-28b1fa083ec8.png)

### Additional context
This issue is only seen in production environment.
(Strapi is hosted on ec2)

**Comment by Boegie19** [comment]
I think it is related to https://github.com/strapi/strapi/issues/13121

**Comment by derrickmehaffy** [comment]
I have not been able to reproduce it myself quite yet but I can confirm this as one of our enterprise customers is seeing this as well (I've seen it while on a call with them)

**Comment by shwetaAjmeraInfotech** [comment]
Any update on this one? As we are facing this on production, so we are eagerly waiting to solve this.

**Comment by shwetaAjmeraInfotech** [comment]
@Boegie19 It's related to #13121 but that doesn't solves the problem.

**Comment by derrickmehaffy** [comment]
> Do you confirm that the issue is only in the production environment?
> 
> What are the steps that you're following for the deployment on production?
> None of us internally is able to replicate this issue

@marcoautiero the customer I had a call with could reproduce it (randomly) locally in dev mode too.

**Comment by samimwebdev** [comment]
Still I am Facing this issue in production, I am using latest version of strapi and deployed on railway app. I haven't found this issue on development. And In production it's appearing Often. Not Sure What's causing the issue.

**Comment by Boegie19** [comment]
I found a way to replicate the issue I will see later this week what causes it execlty
