### ISSUE TITLE
upgrade from 4.3.9 to 4.70

### ISSUE THREAD

**Issue by JakeHolcroft** [strapi/strapi#16031]
Hello

I have upgraded from 4.3.9 to 4.7.0 and followed all the migration steps, rebuilt and launched server and it runs fine.

Then when i go to content manager i get 

"Warning: An error has occured"

Console log is :

content-manager.04adfde6.chunk.js:1139 TypeError: q.cancelToken.subscribe is not a function
    at main.dcd03a6e.js:2982:5707
    at new Promise (<anonymous>)
    at xhr (main.dcd03a6e.js:2982:3440)
    at $e.Le (main.dcd03a6e.js:2982:6911)
    at async Promise.all (index 0)
    at async Object.f [as current] (content-manager.04adfde6.chunk.js:1139:14974)

This guy is getting the same issue:
https://forum.strapi.io/t/error-loading-content-manager-after-4-6-1-upgrade/26350

**Comment by joshuaellis** [comment]
Have you rebuilt your admin panel after upgrading?

**Comment by JakeHolcroft** [comment]
Content type builder etc is all fine, just content manager which has this issue.

**Comment by JakeHolcroft** [comment]
further look at where the error is coming from:

try {
                    const [{data: {data: g}},{data: {data: h}}] = await Promise.all(["components", "content-types"].map(P=>p(ce(P), {
                        cancelToken: d.token
                    })));
                    m(u({
                        id: R("App.schemas.data-loaded"),
                        defaultMessage: "The schemas have been successfully loaded."
                    }));
                    const {authorizedCtLinks: y, authorizedStLinks: C} = await Lu(h, a, o)
                      , {ctLinks: D} = c(mt.LK, {
                        ctLinks: y,
                        models: h
                    })
                      , {stLinks: E} = c(mt.dV, {
                        stLinks: C,
                        models: h
                    })
                      , T = wu(D, E, h, g);
                    e(T)
                } catch (g) {
                    if (Ce().isCancel(g))
                        return;
                    **_console.error(g),_**
                    o({
                        type: "warning",
                        message: {
                            id: "notification.error"
                        }
                    })
                }

**Comment by JakeHolcroft** [comment]
@strapi/plugin-users-permissions@4.7.0
│ └─┬ @strapi/helper-plugin@4.7.0
│   └── axios@1.2.2
├─┬ @strapi/strapi@4.7.0
│ └─┬ @strapi/admin@4.7.0
│   └── axios@1.2.2
└── axios@0.21.4

**Comment by JakeHolcroft** [comment]
Upgraded AXIOS to 0.22 when cancelToken was deprecated, fixed my issue! cheers Josh
