### ISSUE TITLE
NULL Primary Key in Relationship Breaks App

### ISSUE THREAD

**Issue by JREAM** [strapi/strapi#1603]
**Informations**
- **Node.js version**: - 9.11.2
- **npm version**: - 6.2.0
- **Strapi version**: - 3.0.0-alpha.12.7.1
- **Database**: - MySQL in this Instance
- **Operating system**: - Ubuntu 18.04 x64

**What is the current behavior?**
Small end-user bug that just needs to be prevented when using a Primary Key. Kills the server.

    UnhandledPromiseRejectionWarning: Error: ER_PRIMARY_CANT_HAVE_NULL: All parts of a 
    PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
    ⛔️ Server wasn't able to start properly.
    [2018-07-20T09:37:23.620Z] error (hook:bookshelf) takes too long to load

**Steps to reproduce the problem**
1: Create a Content Type called "Post" with a text:title
2: Create a Content Type called "Tag" with a text:title
3: Go back to the "Post", create a Relationship with Post Belongs to Many Tags
---- Post field: tag_id / Tag field: id

**What is the expected behavior?**
An error message that it will not work.

**Suggested solutions**
Perhaps a primary key check (Might be SQL only though)

**Comment by derrickmehaffy** [comment]
@JREAM are you using the strapi generate:api command?

If so please check out my bug here: https://github.com/strapi/strapi/issues/1412

There are major differences between how the AdminUI builds the model files and how the generate command does. For now on SQL you will need to use the AdminUI.

I believe @lauriejim was going to take a look at this and re-open that issue.

**Comment by derrickmehaffy** [comment]
Also as a side note, you can't use `id` in a relationship because strapi injects that field already.

**Comment by JREAM** [comment]
@derrickmehaffy Hey there, I was using the GUI. awesome Thanks for the pointer you can close this if you like!
