### ISSUE TITLE
Performance issues with populating files caused by missing index

### ISSUE THREAD

**Issue by willempie96** [strapi/strapi#16038]
### Required System information

- Node.js version: 16
- NPM version: 8.19.3
- Strapi version: 4.6.1
- Database: MariaDB 10.6.5
- Operating system: Mac
- Is your project Javascript or Typescript: JS

### Describe the bug

NOTE: Not really a bug report but more of a suggested performance improvement or question why something is made the way it is. If i need to formulate this different or post it somewhere else please let me know.

We were having some troubles with slow performance on a lot of calls lately. 
In calls with a lot of populates response times could go to 2-4 seconds which was not workable. 
After some in depth analyzing of why those calls where slow we realized that the main time consumers where queries made to populate files. 

I.E.
``
select distinct `t1`.`order`, `t0`.*, `t1`.`related_id`, `t1`.`related_type` from `files` as `t0` left join `files_related_morphs` as `t1` on `t0`.`id` = `t1`.`file_id` and `t1`.`field` = 'images' where (`t1`.`related_id` in (4489, 4387, 4369, 4329, 4122, 3052, 3051, 3050, 3049, 3047, 1386, 50, 47, 45, 43, 37, 34, 33, 31, 30, 29, 25) and `t1`.`related_type` = 'api::location.location') order by `t1`.`order` asc
``

These calls were taking ~150 ms, with around 10 of these file populates this adds up quite quick.
We found out that on the related_id and related_type no indexes were set. After manually setting an index on (for now) only related_id in the files_related_morphs table these calls were running in ~10 ms. 

For our application we have fixed this issue by manually adding the index on bootstrap but I'm wondering if there is a reason this index isn't set on default or if it is a bug.

The structure of the files_related_morphs table reminds me of the entity_component tables which have a unique index.

So, is this a bug or is there a good reason that I'm missing?

**Comment by pcriadoperez** [comment]
Any update on this? Ran into a similar issue and tried to manualy create two indexes to see if it helps:
```sql
CREATE INDEX idx_files_related_morphs_related_id ON files_related_morphs("related_id");
CREATE INDEX idx_files_related_morphs_order ON files_related_morphs("order");
```

**Comment by pcriadoperez** [comment]
Can you tell where the indexes where added?
![image](https://user-images.githubusercontent.com/12142844/233064916-076246b7-2885-4b4e-8cc7-b2e5c3b927d8.png)

**Comment by Marc-Roig** [comment]
Hello, I am in the process to create a PR to add those indexes, thank you for your patience :)
