### ISSUE TITLE
Components don't have custom icons anymore

### ISSUE THREAD

**Issue by Betchika99** [strapi/strapi#16042]
Hello! Find not very clear bug connected with icon of Component

### Required System information
- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.7.1
- Database: MySCQL
- Operating system: MacOS
- Is your project Javascript or Typescript: TS

### Describe the bug

Updated from Strapi 4.1.1 to 4.7.1 (step-by-step, according to Migration guides) and found that my icons for components were replaced by default icon. I use components in Dynamic Zone.

### Steps to reproduce the behavior

1.Install Strapi 4.1.1
2. Create any Component in Content-Type Builder through Admin Panel, set Icon
3. Update Strapi version to 4.7.1
4. See, that Icon was replaced by default one

### Expected behavior

Icon, that was set up earlier (and that is placed in component JSON-config), is displayed. Not the default one.

### Screenshots

Add screenshots of components on 4.1.1 and 4.7.1 down:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/34346716/224118854-e5621855-89a8-4c5d-a8ae-a5ffb37fe3a8.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/34346716/224119112-5f218173-07d2-4465-a259-156438f42944.png">

### Code snippets
Example snippet for understand, how icons were set up (my-component.json):
```
{
  "collectionName": "components_blocks_accordions",
  "info": {
    "displayName": "Accordion",
    "icon": "stream",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "default": "accordion"
    },
    "items": {
      "displayName": "accordionItems",
      "type": "component",
      "repeatable": true,
      "component": "blocks.accordion-items"
    }
  }
}
```

### Additional context
Found [blame](https://github.com/strapi/strapi/commit/287787a550ce2d8e03f8808812b134dc2674ac04#diff-1df92d24e121a72299c7a4a09568dcf22692e17a318c455b18fd4aec864a7bcbL56) where icon was stopped to be a props of component. Maybe this may help

Thanks! Waiting for fixing

**Comment by Boegie19** [comment]
they removed that future to reduce the bundle sizes see https://github.com/strapi/strapi/issues/15291 
if you want it re added please see https://feedback.strapi.io/customization/p/icons-for-components

**Comment by joshuaellis** [comment]
Hey @Betchika99, as @Boegie19 pointed out, we did indeed remove these as they were bloating the bundle size to an unacceptable amount, reiterating upon the above comment, I would encourage you to upvote and track [feedback.strapi.io/customization/p/icons-for-components](https://feedback.strapi.io/customization/p/icons-for-components)
