### ISSUE TITLE
User-permissions plugin - roles lost for other people in a team.

### ISSUE THREAD

**Issue by oziomek1** [strapi/strapi#16043]
### Required System information

- Node.js version: v18.14.0
- NPM version: 9.3.1
- Strapi version: 4.6.2
- Database: sqlite
- Operating system: macos
- Is your project Javascript or Typescript: JS

### Describe the bug

Roles set up in the user-permissions plugin are not saved in the project configuration.
As a result, if somebody sets the roles, they're not available for other people in a team, with manually switching them in the admin panel which is unacceptable.
They're also not available in the project dump file.

Current behavior prevents the backend from being resilient during autoscaling.

### Steps to reproduce the behavior

1. Set any role/permission in user-permissions plugin
2. Commit and push the project to git
3. Clone this repository to another folder
4. Roles/permissions in the copied project are not synced.

### Expected behavior

Plugin settings should be versioned, without the requirement to manually set them up in the admin panel.

### Additional context

It's the first time I'm using Strapi, so I might misunderstood some conventions.

**Comment by Boegie19** [comment]
@oziomek1 See https://market.strapi.io/plugins/strapi-plugin-config-sync for the functionality you want 

Also for auto scalling you should still use 1 db cluster where all request go to since the role data is in the db all scaled strapi instances should use the same db cluster

**Comment by oziomek1** [comment]
@Boegie19 
Thank you for the reply. This is exactly what I was looking for!
