### ISSUE TITLE
[bug?] - Altering schema to get 3 levels of nested components works in admin UI, however API doesn't populate on *

### ISSUE THREAD

**Issue by rihards-simanovics** [strapi/strapi#16050]
# First of all, big thanks for creators and maintainers of this project, I am absolutely loving it! 😍

### Required System information

- Node.js version: **v16.19.0**
- ~~NPM version: **9.2.0**~~ (unused see Yarn version)
- Yarn version: **v1.22.19**
- Strapi version: **v4.7.1**
- Database: **better-sqlite3**
- Operating system: **WSL Ubuntu 22.04**
- Is your project Javascript or Typescript: **JavaScript**

### Describe the bug

The title should be self-explanatory, but I will expand.

I am migrating from WordPress (which used Advanced Custom Fields) to Strapi and have a ton of legacy logic to move over. I have attempted to create 3 levels of nested components however I quickly realised that only 2 are allowed. After some research I found a thread [here](https://feedback.strapi.io/customization/p/allow-nesting-of-components-more-than-2-levels-deep) and [here](https://github.com/strapi/strapi/issues/11319) and understood that it is possible to override the UI limitation by manually editing the schema for the component where more nested levels are needed.
Although I was able to successfully alter the schema and add the third level of nested components in the admin UI, when the time comes to fetching the data with API, the results return only up to level 2. I have read the documentation [here](https://docs.strapi.io/dev-docs/api/rest/populate-select#components--dynamic-zones) and have setup the filtering and population as described.
It's possible that I've misunderstood or misread the instructions but at this point I'm not sure where I went wrong.

### Steps to reproduce the behavior

1. Clone this repo `https://github.com/rihards-simanovics/strapi-bug-demo` (it's stock Strapi with only schema and yarn lock present)
2. run `yarn` to install yarn
3. once ready run `yarn build` 
4. create a page in pages collection type, edit name and nested components (up to level 3)
5. save and publish
6. try api with those populate queries (I omitted filter but in production slug filter would be used):
    1. `http://localhost:1337/api/pages/1/?populate[block][populate]=%2A`
    2. `http://localhost:1337/api/pages/1/?populate[block][populate]=%2A&populate[block][secondLevelComponent][populate]=%2A&`
    3. `http://localhost:1337/api/pages/1/?populate[block][populate]=%2A&populate[block][secondLevelComponent][populate]=%2A&populate[block][secondLevelComponent][thirdLevelComponent][populate]=%2A`

### Expected behavior

response:
```json
{
    "data": {
        "id": 1,
        "attributes": {
            "name": "test page",
            "createdAt": "xxxx-xx-xxTxx:xx:xx.xxxZ",
            "updatedAt": "xxxx-xx-xxTxx:xx:xx.xxxZ",
            "publishedAt": "xxxx-xx-xxTxx:xx:xx.xxxZ",
            "block": [
                {
                    "id": 1,
                    "__component": "common.block",
                    "name": "test block",
                    "secondLevelComponent": {
                        "id": 1,
                        "name": "test second level component",
                        "thirdLevelComponent": {
                            "name": "test third level component"
                        }
                    }
                }
            ]
        }
    },
    "meta": {}
}
```

### Actual behaviour

response:
```json
{
    "data": {
        "id": 1,
        "attributes": {
            "name": "test page",
            "createdAt": "xxxx-xx-xxTxx:xx:xx.xxxZ",
            "updatedAt": "xxxx-xx-xxTxx:xx:xx.xxxZ",
            "publishedAt": "xxxx-xx-xxTxx:xx:xx.xxxZ",
            "block": [
                {
                    "id": 1,
                    "__component": "common.block",
                    "name": "test block",
                    "secondLevelComponent": {
                        "id": 1,
                        "name": "test second level component"
                    }
                }
            ]
        }
    },
    "meta": {}
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/52106095/224528541-7bf018e7-a30b-40c1-924c-8c5d1a42419a.png)

![image](https://user-images.githubusercontent.com/52106095/224528019-e3380374-f7cd-41f8-ba63-b8437f14ce84.png)

### Code snippets

In react JS the following code is used to query the data:
```jsx
const getPageData = async (props) => {
    let slug = "home";

    if (delve(props.params, "pageSlug")) {
        slug = delve(props.params, "pageSlug");
    }

    const pageDataQuery = buildQuery(
        "pages",
        [
            {
                filters: {
                    slug: {
                        $eq: slug
                    }
                },
                populate: {
                    seo: {
                        populate: "*"
                    },
                    block: {
                        populate: "*",
                        heroQuickLinks: {
                            populate: "*",
                            link: {
                                populate: "*"
                            }
                        }
                    },
                    categories: {
                        populate: "*"
                    }
                }
            },
            {
                encodeValuesOnly: true // prettify URL
            }
        ],
        "en-GB"
    );

    const siteDataQuery = buildQuery(
        "site-setting",
        [
            {
                populate: {
                    headerAlerts: {
                        populate: "*"
                    }
                }
            },
            {
                encodeValuesOnly: true // prettify URL
            }
        ],
        "en-GB"
    );

    const pageData = await requestData(pageDataQuery);
    const siteData = await requestData(siteDataQuery);

    const returnVal = {
        siteData: siteData,
        pageData: pageData
    }

    console.log(returnVal)

    return returnVal;
};
```

**Comment by Marc-Roig** [comment]
Hello :) 
I think the issue is the way the populate query param is written

From your query:
http://localhost:1337/api/pages/1/?populate[block][populate]=%2A&populate[block][secondLevelComponent][populate]=%2A&populate[block][secondLevelComponent][thirdLevelComponent][populate]=%2A

I think for your usecase this could work:
http://localhost:1337/api/pages/1/?populate[block][populate][secondLevelComponent][populate]=thirdLevelComponent

When doing nested populates you need to place a [populate] in between each attribute. And I think this should work :)

**Comment by rihards-simanovics** [comment]
@Marc-Roig that seemed to have worked on the bug demo repo, let me give this a try on my actual project, thanks for the help!

**Comment by rihards-simanovics** [comment]
> When doing nested populates you need to place a [populate] in between each attribute. And I think this should work :)

@Marc-Roig so, I was able to partially resolve this, it seems like I can't have a complex populate query in a single URL, what I was hoping to do is to get all blocks and their values at the same time as there would never be too many of them on the page, for that I used this qs query:
```js
{
"pages",
[
    {
        filters: {
            slug: {
                $eq: slug
            }
        },
        populate: {
            seo: {
                populate: "*"
            },
            block: {
                populate: "*",
                heroQuickLinks: {
                    populate: "*"
                }
            },
            categories: {
                populate: "*"
            }
        }
    },
    {
        encodeValuesOnly: true // prettify URL
    }
],
"en-GB"
```

and so i thought i could populate the block and the children recursively:
```js
block: {
    populate: "*",
    heroQuickLinks: {
        populate: "*"
    }
},
```
After further reading I see that populate only does it one level deep.

Also, it appears that this one would work well but then I'm losing the other values as the rest of the query just gets discarded by qs. is there a way to get everything or do I have to query it in chunks? I never worked with GraphQL before, and I was curious if that's something not possible with RestAPI, perhaps I could use GraphQL to achieve this? Any advice would be much appreciated.

**Comment by Marc-Roig** [comment]
@rihards-simanovics I have not tried but maybe you could acomplish this by doing:
```
{
  "pages": [
    {
      "filters": {
        "slug": {
          "$eq": "slug"
        }
      },
      "populate": {
        "seo": {
          "populate": "*"
        },
        "block": {
          "populate": "*",
          "[heroQuickLinks][populate]": "*"
        },
        "categories": {
          "populate": "*"
        }
      }
    },
    {
      "encodeValuesOnly": true
    }
  ],
  "en-GB"
}
```

or something similar , I have not played much with qs, but it seems something like this should work.
Nevertheless, it's possible to do it with the rest api (if you do the string query yourself), but maybe it's super hard with qs.

**Comment by rihards-simanovics** [comment]
@Marc-Roig that's ok, tbh I realised this might be a bad idea anyway, instead I will just use GraphQL as it's a lot easier to write and accomplishes exactly what I need. so essentially, I will load one level of blocks, just enough to get the __component field and just map it to block manager which will then useEffect on ReactJS side to load each block separately rather than in one go. Plus, it has an added benefit of simpler queries since you don't have to account for all fields and just focus on the fields you will encounter in the block.

thank you for taking the time to help, I'm still learning RestAPIs so will sound green, with WP and ACF you don't have to worry about any of this, but WP comes with its own idiosyncrasies.

**Comment by Marc-Roig** [comment]
> instead I will just use GraphQL as it's a lot easier to write and accomplishes exactly what I need
agree :) graphql will give you the flexibility you need for this.

> thank you for taking the time to help, I'm still learning RestAPIs so will sound green, with WP and ACF you don't have to worry about any of this, but WP comes with its own idiosyncrasies.
thank you for your time too! that was one well described issue :) it's always a pleasure when someone starts saying " I am absolutely loving it"
