### ISSUE TITLE
Relation field is not update when change the value by lifecycle

### ISSUE THREAD

**Issue by wai15985** [strapi/strapi#16052]
### Required System information
Node.js version: 16.13.1
NPM version: 9.4.0
Strapi version: 4.7.1
Database: Postgres
Operating system: MacOS 
Is your project Javascript or Typescript: JavaScript
### Describe the bug
Relation field is not update when i change the value by lifecycle 'beforeCreate'.
### Steps to reproduce the behavior
1. Select one option in relation field
2. Change data by lifecycle 'beforeCreate'.
3. Relation field still display same thing (initialData return incorrect data until page refresh).
### Expected behavior
1. Select one option in relation field
2. Change data by lifecycle 'beforeCreate'.
3. Return correct data in initialData (useCMEditViewDataManager hook)
4. Update Relation field

**Comment by joshuaellis** [comment]
The CMS does not do push updates from the server at this time so this is expected behaviour.
