### ISSUE TITLE
ValidationError (source.map is not a function)

### ISSUE THREAD

**Issue by DrMickArtisan** [strapi/strapi#16059]
# Bug report

### Required System information

- Node.js version: V14.21.3
- NPM version: 6.14.18
- Strapi version: 4.6.1
- Database: Mysql 5.7.38
- Operating system: Linux (Ubuntu)
- Is your project Javascript or Typescript: Javascript

### Describe the bug
When trying to import a singleType object containing a component with a relation hasMany, if the connect array contains more than 21 entries, import fail with  returnMessage : 
`'{"data":null,"error":{"status":400,"name":"ValidationError","message":"source.map is not a function","details":{"errors":[{"path":[],"message":"source.map is not a function","name":"ValidationError"}]}}}'`
### Steps to reproduce the behavior
Create a collection Type (Extracts) with some fields. Create at least 22 Extracts objects.
Create a component (Suggestions) with a field "Catalog" which is a relation hasMany Extracts.
Create a single Type (Config) with a field suggestions  which is a Component Suggestions.
use the api endpoint
PUT  /api/config with json data containing  at least 22 entries in connect
`{   
 "suggestions": {
  "catalog": {
   "connect": [210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231]
  }
 }
}`
Strapi return 
`'{"data":null,"error":{"status":400,"name":"ValidationError","message":"source.map is not a function","details":{"errors":[{"path":[],"message":"source.map is not a function","name":"ValidationError"}]}}}'`
Notice that it works if you only have 21 entries  in connect array

### Expected behavior
An update of the Config object with as many relations as asked.

Is there something I did not understood in the documentation ?

**Comment by Boegie19** [comment]
Tried to reproduce the error on windows on both strapi v4.6.1 and 4.7.1 
Also can't follow the reproduction steps since 
`{    "suggestions": { "catalog": { "connect": [210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231] } } }` is not correct it should be `{ "data": { "suggestions": { "Catalog": { "connect": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,22,23] } } } }` so it is missing the data in front + the right capitalization of Catalog 

@DrMickArtisan Are you using any strapi plugins?

**Comment by DrMickArtisan** [comment]
Nope, 
Ok, I forget the data part in my example, sorry. But the real point is that it works with 21 entries, and not with 22.
But I'm beginning to think it's not really a strapi bug, but perhaps my way of posting  data (cakephp http client).

**Comment by Boegie19** [comment]
@DrMickArtisan I ran the one I gave above as the correct one and it worked fine for me so or this is most likely Mysql or Linux  specific so let me do a test with mysql and come back to you if I can maby then replicate it

**Comment by DrMickArtisan** [comment]
ok, so it seems that everything is in line 173 of file /node_modules/@strapi/strapi/lib/services/entity-validator/index.js (validator = createComponentValidator=
I just put some logs like : 
 if (metas.attr.type === 'component') {
console.log("meta")
console.log(metas)
       validator = createComponentValidator(createOrUpdate)(metas, options);
    } else if (metas.attr.type === 'dynamiczone') {

and then in createComponentValidator : 
const createComponentValidator =
  (createOrUpdate) =>
  ({ attr, updatedAttribute }, { isDraft }) => {
    let validator;
    console.log("updatedAttribute")        
    console.log(updatedAttribute)        
    const model = strapi.getModel(attr.component);

Folowing logs are 
for 21 entries : 
meta
{
  attr: {
    type: 'component',
    repeatable: false,
    component: 'all.suggestion',
    required: true
  },
  updatedAttribute: { name: 'suggestions', value: { catalog: [Object] } },
}
updatedAttribute
{ name: 'suggestions', value: { catalog: { connect: [Array] } } }
in this case, object is cast in array
And for 22 entries
meta
{
  attr: {
    type: 'component',
    repeatable: false,
    component: 'all.suggestion',
    required: true
  },
  updatedAttribute: { name: 'suggestions', value: { catalog: [Object] } },
}
updatedAttribute
{ name: 'suggestions', value: { catalog: { connect: [Object] } } }
connect is still an object :(

**Comment by joshuaellis** [comment]
@DrMickArtisan you should format this code with ``` to make code blocks, it's almost unreadable at the moment.

**Comment by DrMickArtisan** [comment]
Ok so I made a few tests and finally found a way. I don't really understand what was the problem, but..
For everybody who might have the same problem, it seems that it was the way I use CakePhp to send the post or put command.
I was doing this: 
```
 $options =  [
            'type' => 'json',
            'headers' => [
                "Authorization" => "Bearer ".$this->token,
            ]
        ];
        $reponse = $this->http->post($path,$data,$options);
```
and the correct way is this :
```
 $options =  [
            'type' => 'json',
            'headers' => [
                'Content-type' => 'application/json',
                "Authorization" => "Bearer ".$this->token,
            ]
        ];
        $reponse = $this->http->post($path,json_encode($data),$options);
```
But, in case there is something wrong (either in the doc or in the code) I attach a zip file with a test project.
It contains the strapi  source (whithout node_modules), with a sqlite file
[testBug.zip](https://github.com/strapi/strapi/files/11026194/testBug.zip)
 and a file (CurlCommands.sh) with an example of curl used to send request.
Hope it could be useful !
