### ISSUE TITLE
Min Max value is not added to the number input

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#16063]
### Required System information

- Strapi version: v4.4.7

### Describe the bug

The number input does not have a max or min value applied and therefore the field is only validated after submitting.
In addition to that the first value when pressing an arrow is always `NaN`.
Using regular HTML attributes should fix this.

### Steps to reproduce the behavior

1. Create a number field in the panel and set a max or min value.
2. Click on the arrows of the number field to set the value. The first value should be `NaN` and you should be able to go above max and below min.
3. Submit your changes and the error message should appear.

### Screenshots

![screenshot 2023-03-13 at 17 18 29@2x](https://user-images.githubusercontent.com/45072099/224763290-758fb294-df32-4ed9-8236-bbb1cf3561a2.jpg)

https://user-images.githubusercontent.com/45072099/224763707-00af8a4b-b68c-4642-ae23-05448588627e.mp4

**Comment by Eventyret** [comment]
Thank you for submitting this issue @AdrianFahrbach could you please try the latest version of Strapi?
The current version of writing is `4.8.2` and let me know.

**Comment by AdrianFahrbach** [comment]
This is still an issue in `4.8.2`.

https://user-images.githubusercontent.com/45072099/228372057-72f48569-331d-4eb5-b4f8-07d7f4566215.mp4

**Comment by AdrianFahrbach** [comment]
Could you reopen this issue? This is still relevant

**Comment by AdrianFahrbach** [comment]
We needed this feature inside a custom field and since the inputs don't seem to be able to be used as controlled inputs, I got min and max limits working with a hack that could be useful for anyone with a similar problem.
The basic idea is to rerender the component with the correct value once it breaks those limits. We do that by changing the key of the Input. Here is a stripped down version of our component:
```ts
const CustomNumberInput: React.FC<StrapiProps> = ({ name, value, onChange }) => {
  const [lastFaultyValue, setLastFaultyValue] = useState<number>(undefined);
  const min = 0;
  const max = 100;

  function handleChange(value: number) {
    if (value < min) {
      setLastFaultyValue(new Date().getTime());
      onChange({ target: { name, value: min } });
      return;
    }
    if (value > max) {
      setLastFaultyValue(new Date().getTime());
      onChange({ target: { name, value: max } });
      return;
    }
    onChange({ target: { name, value: value } });
  }

  return <NumberInput key={lastFaultyValue} value={value} onValueChange={handleChange} />;
};
```

A unrelated note:
We use Strapi in a larger project and in most areas it is working great.
I know that this is free software that you are small team and that there probably is a lot of pressure on releasing new features, but quite some parts of Strapi just feel weirdly unpolished, this being one of them. We dug a lot through Strapis source code because of various issues like this or because of missing documentation.
As I said, it works good most of the times and huge respect for what you built, but I would wish for some kind of a feature freeze just to polish things up.
