### ISSUE TITLE
Nested private fields are not hidden from API response

### ISSUE THREAD

**Issue by petercorrea** [strapi/strapi#16069]
### Required System information
- Node.js version: 18.3.0
- NPM version: 9.2.0
- Strapi version: 4.5.4
- Database: postgres
- Operating system: macOS
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When querying for a collection type, only top level fields marked as private are hidden in the response. Any components within the collection type which contain their own private fields, will not be sanitized. 

### Steps to reproduce the behavior

1. Create a collection type
2. As an attribute on the collection type, add a component which includes its own private field. Ensure that the component itself is not private.
3. Query for the collection type.
4. See that nested private fields are not hidden.

### Expected behavior

For all private fields, top level and nested to be hidden.

### Additional context
Note: I'm not familiar with Strapi code base, I only performed a cursory investigation. 

When the schema is being transversed for sanitation, it doesn't contain enough information about the component to even attempt a recursive search for private fields. The potential solution might include two parts:
1. provide more details about components located further down the schema (model definition) tree (`strapi.getModel()` ?)
2. adjust the sanitation logic to transverse recursively in `traverseEntity()` function

**Comment by Eventyret** [comment]
Thank you for your report @petercorrea 🙌
This issue should have been fixed, so please make sure you are on the latest version.

You can follow the migration guides from here.
[📚 v4.5.1+ to v4.6.1 migration guide](https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.5.1-to-4.6.1)

[📚 v4.6.1+ to v4.7.0 migration guide](https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.6.1-to-4.7.0)
Please note you can bump the version to `4.8.2` when upgrading to `4.7.0`

I have tested the issue and as you stated `4.5.4` this is correct that nested data is not adhering to being sanitised.
But in the latest version, this has been adhered to. 🚀
