### ISSUE TITLE
Local environment build strips out database certificate file from config folder then throws no such file or directory error

### ISSUE THREAD

**Issue by Pixfloage** [strapi/strapi#16072]
### Required System information

- Node.js version: 16.1.1
- NPM version: 8.19.2
- Strapi version: 4.6.0
- Database: Postgres 14
- Operating system: macOS 12.6.1 Monterey
- Is your project Javascript or Typescript: TS

### Describe the bug

Can't read certificates on local dev environment, because the dist folder is missing the required files. The build and dev scripts, TS complier doesn't copy non .js, .ts files from /config to /dist/config.
 
### Steps to reproduce the behavior

1. Got a ca-certificate.crt under /config/env/development/ca-certificate.crt 
2. Got a database.js next to the .crt file that tries to read `${__dirname}/ca-certificate.crt`
3. Run npm run develop or build, it will throw an error `ENOENT: no such file or directory, open '.../dist/config/env/development/ca-certificate.crt'`

Until now, I've always used a local DB without SSL. On production environment I usually read from `/workspace/config/env/${env('ENVIRONMENT')}/ca-certificate.crt` and it works just fine, but not locally

### Expected behavior

I expect the config files (non .ts files) to be present under /dist. 
Tried creating an after develop/build script to copy over the crt manually `cp ./config/env/development/ca-certificate.crt ./dist/config/env/development/` but something overrides it after start the dev server.

**Comment by alexandrebodin** [comment]
Typescript compilation doesn't offer any feature to copy files that are not going to be transpiled. To avoid any unforseen side effect this is something user have to manage already in most cases. 

2 options that you can choose from:

- Use a tool like https://www.npmjs.com/package/copyfiles and add it in your pacakge.json scripts 
- Move your files outside the config folder and reference them with absolute path `path.resolve(__dirname, xxx)`

I will close this issue as it is not a Strapi specific concern. Thank you for contributing!
