### ISSUE TITLE
Knex no longer Returns parsed JSON content from JSON Database Columns

### ISSUE THREAD

**Issue by bozz** [strapi/strapi#16073]
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.6.2
- Database: PostgreSQL 14.1
- Operating system: MacOS / Ubuntu
- Is your project Javascript or Typescript: JS

### Describe the bug

We use knex directly for doing some low level queries (accessed through `strapi.db.connection`). Starting with Strapi v4.6.2 data from JSON columns is no longer returned as objects (JSON is not parsed) but only as strings. This new behaviour breaks many of our API endpoints. I could not find any reference to this change in the Changelog or elsewhere. 

### Steps to reproduce the behavior

1. Given a table with a JSON column (in Postgres) - for example: `content`
2. Run a simple knex query to fetch this data:
```
const knex = strapi.db.connection;
const page = await knex('pages')
    .select('id', 'content').where('id', someId).first();
```
This will return the following object:
```
{
    id: 1234,
    content: '{"foo": "bar"}'  // <-- stringified JSON
}
```

### Expected behavior

I expect the result of the knex query to return the parsed JSON data. This was the case up until Strapi v4.6.1.

If I create a separate project without Strapi, but using knex (v2.4.0) to run the same queries - the data from JSON columns are returned as objects. ==> behaviour as expected

It seems that Strapi is somehow changing the behaviour of knex - but I could not find any reference or information regarding this.

### Additional context

If this is intended behaviour, is there any configuration option to change this?

**Comment by bozz** [comment]
I did some more digging regarding this issue and it comes from this change in v4.6.2: 
https://github.com/strapi/strapi/commit/52bcdad90ba7f2e175efeb17f8c0a2322a1deabc

I don't think the default behaviour of knex should be changed here. Could there at least be a configuration option regarding this?

**Comment by Marc-Roig** [comment]
Indeed this change was introduced in https://github.com/strapi/strapi/pull/15752 and resolved this issue https://github.com/strapi/strapi/issues/15496

Nevertheless, JSON should still be parsed in this file https://github.com/strapi/strapi/blob/main/packages/core/database/lib/fields/json.js

I will check why that is not the case 👀

**Comment by Marc-Roig** [comment]
I see the problem is `strapi.db.connection`, we have our custom database validation & parsing logic in strapi, and so we can not guarantee some parsing or validation will be ommited.

I would personally recommend using the strapi.query and not the db connection directly, but nevertheless I will try to explore using this work https://github.com/strapi/strapi/pull/15672 and revert what is causing your issue :)
