### ISSUE TITLE
Admin crash "Error: Minified React error #130" when upgrade v4.5.6 to v4.6.1 

### ISSUE THREAD

**Issue by suneox** [strapi/strapi#16070]
### Required System information

- Node.js version: v16.19.0
- NPM version: 8.19.3
- Strapi version: v4.5.6 
- Database: Postgres
- Operating system: macOS
- Is your project Javascript or Typescript: TS

### Describe the bug
After upgrading strapi to 4.6.1  or 4.7.1, I can not open admin after login with an "Error: Minified React error #130)"

### Steps to reproduce the behavior

My current version:
"@strapi/design-system": "1.4.2",
"@strapi/icons": "1.4.2",
"@strapi/plugin-graphql": "4.5.6",
"@strapi/plugin-i18n": "4.5.6",
"@strapi/plugin-sentry": "4.5.6",
"@strapi/plugin-upload": "4.5.6",
"@strapi/plugin-users-permissions": "4.5.6",
"@strapi/provider-upload-aws-s3": "4.5.6",
"@strapi/strapi": "4.5.6",

1) updating package to
"@strapi/design-system": "1.4.2",
"@strapi/icons": "1.4.2",
"@strapi/plugin-graphql": "4.6.1",
"@strapi/plugin-i18n": "4.6.1",
"@strapi/plugin-sentry": "4.6.1",
"@strapi/plugin-upload": "4.6.1",
"@strapi/plugin-users-permissions": "4.6.1",
"@strapi/provider-upload-aws-s3": "4.6.1",
"@strapi/strapi": "4.6.1",

2) remove node_modules, yarn.lock, cache, dist
3) run yarn install, strapi build, strapi develop
4) after login web crash with an error "Minified React error #130"
<img width="1421" alt="Screenshot 2023-03-14 at 12 56 25" src="https://user-images.githubusercontent.com/11959869/224909209-5219c524-6506-41a3-ad85-2855d4199b22.png">

5) when run strapi develop --watch-admin
Revieve warning
![Screenshot 2023-03-14 at 12 48 25](https://user-images.githubusercontent.com/11959869/224907990-828332de-2fef-4618-84a5-60776557bd15.png)

And application still crashes after login

I have updated package to "@strapi/design-system": "1.6.2", application will work as expectations 

### Expected behavior

Have to add min dependence version for each release note, migration guide or add peer dependencies

**Comment by joshuaellis** [comment]
👋🏼  Hello! Sorry to hear you're having trouble, I can see you've got:

```json
"@strapi/design-system": "1.4.2",
"@strapi/icons": "1.4.2",
```

in your package.json, is there a reason you've done this? Typically it's not that necessary. I'd advise you update those because the component you're missing has been added in a later version.
