### ISSUE TITLE
This Users,Permissions,User,validation,failed,password,Path,password,is,required is already taken

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#1608]
**Informations**
- **Node.js version**: 10
- **npm version**: 6
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongodb
- **Operating system**: ubuntu18

**What is the current behavior?**
When I try to create new entity , I get this error
![permissionerr](https://user-images.githubusercontent.com/12433101/43025224-138fe8d0-8c9b-11e8-8f2a-ea7f1927f788.png)

**Comment by lauriejim** [comment]
Hello @xeastcrast , please follow the issue template so we can get a better understanding about the origin of your bug.
Need steps to reproduce.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
