### ISSUE TITLE
Content-manager looses the users locale ui-state when saving an entity

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#16087]
### Required System information

- Node.js version: Not applicable
- NPM version: Not applicable
- Strapi version: 4.7.1
- Database: Not applicable
- Operating system: Not applicable
- Is your project Javascript or Typescript: Not applicable

### Describe the bug

When I, as a content-editor, e.g. work on an entity that hasn't been saved yet, the UI will loose it's state after the first save:

https://user-images.githubusercontent.com/2244375/225302048-10c71854-c581-4aec-bf5b-afbf93e59e17.mp4

This is frustrating because all components and dynamic-zones are reset to their original state. This does not happen on the second save.

### Steps to reproduce the behavior

1. Go to the edit view of the content-manager
2. Create an new entity including nested components or dynamic zones
3. Open nested components and enter data
4. Hit save

### Expected behavior

I expect the UI to not loose the local UI state and keep all components as they are (similar to second save).

### Screenshots

Screencast added above

**Comment by joshuaellis** [comment]
Hi Gustav,

Thanks for your bug report, I'm please to announce that this will be resolved in Strapi v5. We hope to see you there!

Best wishes,
Josh
