### ISSUE TITLE
TypeError: plugins.find is not a function

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi#1609]
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: mongodb
- **Operating system**: Mac

**What is the current behavior?**
TypeError: plugins.find is not a function

**Steps to reproduce the problem**
On the admin site, click Roles & Permissions then Public
It will show error "An error occured while fetching the role"

**What is the expected behavior?**
No error and we can manage the permission settings

**Suggested solutions**
plugins/users-permissions/services/UsersPermissions.js:169:52
plugins supposes to be an array
instead it is now an error object
 { message: 'An internal server error occurred',
  statusCode: 500,
  error: 'Internal Server Error' }

The admin might be calling https://marketplace.strapi.io/plugins and get a 500 error

It is really undesirable if our admin site's up time is relying on marketplace.strapi.io.

**Comment by justingosan** [comment]
critical bug right here

**Comment by amiregelz** [comment]
Why should a local build depend on strpi servers? can we make it only access plugins installed locally? it's weird that my local server depends on strapi uptime or downtime

**Comment by amiregelz** [comment]
Shouldn't it go the the `if (err)` block? 500 server error is an error..

**Comment by BroTrue** [comment]
same error

**Comment by dblinov** [comment]
Same issue :(((

**Comment by dillonraphael** [comment]
Also having this issue all of the sudden. I create a new Content Type, then try editing the Public role.

**Comment by dillonraphael** [comment]
@soldatovsh has the hardcode fix. You need todo the same for `admin > admin > src > containers > InstallPlugin > saga` line#52 seems to also be calling the marketplace url.

**Comment by aalbacetef** [comment]
Funny, stumbled upon here seeing if the marketplace bug was really just on my side.

Noticed also that the URL changed, so they might be in the process of moving the marketplace around. 

------

Guys, please get this fixed! I'm trying to propose this at work as I'm in love with how blazing fast it can be to get up and running with an API, but I can't justify hardcoding a fix for a request to fetch plugins when I'm trying to access the user permisions!!!!!!!! My boss would rip me apart and rightly so!

Please change the plugin-checking section, please!

**Comment by nicroto** [comment]
Just hit this as well...

**Comment by derrickmehaffy** [comment]
Same @lauriejim @Aurelsicoko Critical issue breaking all other project.s

**Comment by derrickmehaffy** [comment]
@lauriejim fixed this issue by bringing the site back up, however a more perm fix should be applied to stop this from happening in the future.

**Comment by dblinov** [comment]
@lauriejim wonder why this issue is closed as there is no solution for that yet

**Comment by taylor-knapp** [comment]
@lauriejim this appears to be an issue again (or I'm running into something else that is causing the same error)

**Comment by Heziode** [comment]
Me too @taylor-knapp

**Comment by melodyjs** [comment]
Requesting https://marketplace.strapi.io/plugins gives like below
``{ message: 'An internal server error occurred',
  statusCode: 500,
  error: 'Internal Server Error' }``
I think something went wrong on strapi marketplace server.

**Comment by elhenro** [comment]
Also just encountered this, thank you @soldatovsh for the fix

**Comment by mightypanda-x** [comment]
Running into the same issue. Dont understand why my implementation should be dependent on marketplace.strapi.io. If the site is down, it should be ignored.

**Comment by lauriejim** [comment]
Can you try again please

**Comment by mightypanda-x** [comment]
Working now. But system should ignore this error or fall back on some default response. What if company IT blocks this url/domain at some point?

**Comment by lauriejim** [comment]
Completely agree, we will work on it tomorrow.

**Comment by nolafs** [comment]
This has not been fixed. Currently the marketplace returns a 502.

The fix above works if you change the error status to 502. I don't think is good idea to make the plugin depended on the marketplace.

**Comment by alexandrebodin** [comment]
@nolafs THe issue is related to the marketplace being in 502 error we are going to fix the and create a fix so that it cannot happen again ;)

**Comment by driku** [comment]
Its down again today. Can you provide a fix soon?
