### ISSUE TITLE
REST API publishedAt = null for draft record causes validation error when using form data (application/x-www-form-urlencoded)

### ISSUE THREAD

**Issue by krisdahl** [strapi/strapi#16098]
### Required System information

- Node.js version: v18.15.0
- NPM version: 9.5.0
- Strapi version: 4.7.1
- Database: sqllite & mysql
- Operating system: macos, linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When creating a new record in draft state by setting publishedAt = null, you'll get a validation error when using form data (content-type application/x-www-form-urlencoded) rather than body payload (content-type application/json).

Otherwise using form data works perfectly (can create records in the published state without issue).

### Steps to reproduce the behavior

1. Prepare a REST POST to /api/endpoint
2. Set your payload / form data to be { data : { publishedAt : null}}
3. Use a content type of  application/x-www-form-urlencoded (or default jQuery POST() method)
4. You will get this error

`{
    "status": 400,
    "name": "ValidationError",
    "message": "Invalid format, expected a timestamp or an ISO date",
    "details": {}
}`

### Expected behavior

It should create a new record with a published state of 'draft'.

### Code snippets

jQuery example.

```
var newrecord = {
    name : 'new record',
    publishedAt : null
};

//this will return validation error.  Remove publishedAt key and it will save the record
$.ajax({
    type: "POST",
    url: "http://localhost:1337/api/article",
    data: { data: data },
    contentType: 'application/x-www-form-urlencoded',
    dataType: 'json',
    success: function (data) {
        console.log("success");
        console.log(data);
    }
});

//this will work
$.ajax({
    type: "POST",
    url: "http://localhost:1337/api/listings",
    data: JSON.stringify({ data: article }),
    contentType: 'application/json; charset=utf-8',
    dataType: 'json',
    success: function (data) {
        console.log("success");
        console.log(data);
    },
});
```

### Additional context

If you use the jQuery $.post, this using form data is the default behavior.

**Comment by Marc-Roig** [comment]
hello! thank you for providing such a goodi ssue description :) This seems to be a problem with koa-body / how null values are codified using  application/x-www-form-urlencoded encoding.

I have built an example to test this:

<details>
<summary>Ajax request</summary>

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

</head>

<body>
  <form method='post' action="#">
    <button type="button" id="LoginButton">Request</button>
    <p id="demo"></p>
  </form>
  <div id="list"></div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script>
    $(document).ready(function () {
      $("#LoginButton").click(function () {
        $.ajax({
          type: "POST",
          url: "http://localhost:1337/api/tags",
          data: {
            data: { "name": "test", "publishedAt": "null" }
          },
          contentType: 'application/x-www-form-urlencoded',
          dataType: 'json',
          success: function (result) {
            console.log(result);
            $("#demo").html(result);
          },
          // On error
          error: function (xhr, status, error) {
            console.log(xhr);
            console.log(status);
            console.log(error);
            // print error message
            $("#demo").html(xhr.responseText);
          }
        });
      });
    });
  </script>
</body>

</html>
```

</details>

Indeed this produces exactly the same error as yours and I think I know why.

When you send `{data: { "publishedAt": null }}`, the url is codified as `data%5BpublishedAt%5D=`
When you send `{data: { "publishedAt": "" }}`, the url is codified as `data%5BpublishedAt%5D=` as well.

So effectively the body parser does not know if you are sending a null value or an empty string. I don't think this is something that we can fix and I would encourage people to use application/json if you need to send null values.
