### ISSUE TITLE
After upgrading to v4.8.0/4.8.1 only sorting by "STATE" Published/Draft of collections does not work.

### ISSUE THREAD

**Issue by remulocosta** [strapi/strapi#16099]
### Required System information

- Node.js version: v16.18.1
- NPM version: 9.6.0
- Strapi version: 4.8.0 / 4.8.1
- Database: postgresql
- Operating system: Fedora Linux 37 x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After upgrading to v4.8.0/4.8.1 only sorting by "STATE" Published/Draft of collections does not work.

### Steps to reproduce the behavior

1. Update strapi to v4.8.0 or 4.8.1
2. Go to a collection with a "STATE" field and click to sort the records
3. Confirm that records are not sorted by this column
4. See that there is a log for ordering records

```
#log
[2023-03-16 01:33:55.643] http: GET /content-manager/collection-types/api::state.state?page=1&pageSize=10&sort=publishedAt:ASC (18 ms) 200
[2023-03-16 01:34:03.572] http: GET /content-manager/collection-types/api::state.state?page=1&pageSize=10&sort=publishedAt:DESC (18 ms) 200
```

### Expected behavior

Sort records in ascending or descending order by "STATE" Published/Draft.

### Additional context

Version 4.7.1 of strapi does not have this problem.

**Comment by derrickmehaffy** [comment]
Can you give an example example of how you are applying this sort?

**Comment by remulocosta** [comment]
hey @derrickmehaffy how are you?

Updated the title to better describe the issue.
I made some prints as an example and created a repository to test

Repo: https://github.com/remulocosta/strapiv4-sort-by-state

![sort-by-state-01](https://user-images.githubusercontent.com/6256437/225518996-582c9453-6b6a-4e48-b794-44e7f4bfae52.png)
![sort-by-state-02](https://user-images.githubusercontent.com/6256437/225519003-2dab3981-9594-4e74-a3d8-1c64eba3f52f.png)

**Comment by Marc-Roig** [comment]
In 4.8.0 we remove filters which use fields that don't exist in the schemas.

`State` is a column that does not exist in the schema and is computed by using the 'publishedAt` attribute. @gu-stav do you think the sort could sort by the `publishedAt` and not this virtual `state` column ?


ping @Convly

**Comment by gu-stav** [comment]
@Marc-Roig According to the issue description the query uses `publishedAt`: `&sort=publishedAt:ASC` already, because `state` does not exist in the db. Or did I misunderstand you?

**Comment by Marc-Roig** [comment]
@gu-stav you are right 🤔

**Comment by Marc-Roig** [comment]
Turns out it was something else, we were filtering the publishedAt from the filters and sort query params :) Created a PR to fix this.

**Comment by jordan-vetapp** [comment]
> In 4.8.0 we remove filters which use fields that don't exist in the schemas.

Hi @Marc-Roig, I ran into some issues filtering with relations after 4.8.0 update and found this issue. 

I can't find any documentation on the 4.8.0 filters changes you mentioned. Do you have any related resources or explanations ?

Best regards

**Comment by noire-field** [comment]
I also noticed a very big issue with v4.8.0 to v4.8.2, does not happen with v4.7.1
the filters[] param completely stops working if requesting with authentication (a bearer token is sent)

Not sure if it's related to this issue

**Comment by Marc-Roig** [comment]
@jordan-vetapp the filters should behave the same as before, we did some improvements on the sanitization of them.

@noire-field filters[] should still work with a bearer token , I am trying with one strapi project and seems to be working, could you share this in another issue? and detail an example. Being able to replicate this could help a lot :)
