### ISSUE TITLE
Author role not hiding forbidden items

### ISSUE THREAD

**Issue by bndrgroup** [strapi/strapi#16095]
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.8.0
- Database: postgres
- Operating system: macos
- Is your project Javascript or Typescript: javascript

### Describe the bug

After updating from 4.7.1 to 4.8.0, users with the "Author" role (only able to edit own posts) now see items from other users in the UI. This did not use to be the case. 

### Steps to reproduce the behavior

Update an existing install from 4.7.1 to 4.8.0

### Expected behavior

Normal behaviour expects items that are not created by the user to be hidden completely from the UI. See screenshot below. 

### Screenshots

Before Update: 
<img width="1680" alt="Before" src="https://user-images.githubusercontent.com/50111269/225379957-c9506c14-f4f8-4115-aca9-d2e230c5f99e.png">

After Update: 

<img width="1680" alt="After" src="https://user-images.githubusercontent.com/50111269/225379921-326ce1ae-e942-4c65-bc49-a24bb193abf2.png">

### Additional context

Error occured after updating from 4.7.1 to 4.8.0. This may have something to do with the undisclosed vulnerability that is being patched.

**Comment by derrickmehaffy** [comment]
Most likely conditionals, reproducing now

**Comment by derrickmehaffy** [comment]
Hi @bndrgroup we have a nightly release for this, could you please test and confirm this resolves the issue: `0.0.0-eca2c57a71a9aeceaba8050754d2467019d78be2`

(just swap out the `4.8.0` versions in your package.json for this nightly, reinstall node_modules, and re-run the project)

**Comment by alexandrebodin** [comment]
Hi, The fix was released in v4.8.1. Going to close the issue for now :)
