### ISSUE TITLE
values of model's template field are always "default"

### ISSUE THREAD

**Issue by fishmacs** [strapi/strapi#161]
**5.3.0**:
**2.15.11**:
**1.5.4**:
**OSX**:

I modified 2 source files

1. api/user/controllers/Auth.js:
```
30d29
<     console.log(params)
127c126
<       // template: 'default',
---
>       template: 'default',
130,131d128
<     if (!ctx.request.body.template)
<       ctx.request.body.template = 'default'
```

2. api/user/controllers/User.js
```
94,95c78
<       // const template = _.includes(strapi.api[module].templates, values.template) ? values.template : strapi.models[module].defaultTemplate;
<       const template = (values.template in strapi.api[module].templates) ? values.template : strapi.models[module].defaultTemplate;
---
>       const template = _.includes(strapi.api[module].templates, values.template) ? values.template : strapi.models[module].defaultTemplate;
```

**Comment by Aurelsicoko** [comment]
Can you show me the new entire file, please? Looks great, though.

**Comment by Aurelsicoko** [comment]
As you know, we didn't plan to provide a LTS on the v1. We are focusing on the next version (v3). This issue will not be fixed and we will not release another version of the v1 on npm.

I close this issue. However, we can still work on it to find a solution for your project. Please send me a PM on our Slack.

Thanks for your understanding.
