### ISSUE TITLE
detective-postcss: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by myesn** [strapi/strapi#16106]
### Required System information

- Node.js version: 18.15.0
- NPM version: 9.5.0
- Strapi version: unkonw
- Database: default
- Operating system: Windows 21H1
- Is your project Javascript or Typescript: unknow

### Describe the bug

```
$ yarn create strapi-app my-project --quickstart
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error detective-postcss@5.1.1: The engine "node" is incompatible with this module. Expected version "12.x || 14.x || 16.x". Got "18.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by Eventyret** [comment]
Thank you for reporting your issue @myesn.
Could you please try to use `@latest` as it seems you are using a cached version of `create-strapi-app`

So the command should be `yarn create strapi-app@latest my-project --quickstart` and let me know from there as I'm unable to reproduce this with `node: 18.5.0`

**Comment by myesn** [comment]
Thank you very much for your reply @Eventyret. I have tried to create the project again and cleared the cache, but I still received the same error message.


```bash
$ yarn cache clean
yarn cache v1.22.19
success Cleared cache.
Done in 14.16s.
```
```bash
$ yarn create strapi-app@latest my-project --quickstart
yarn create v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error detective-postcss@5.1.1: The engine "node" is incompatible with this module. Expected version "12.x || 14.x || 16.x". Got "18.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by myesn** [comment]
Hi @Eventyret, I found the reason why. I discovered that the version of this library in the directory `C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\detective-postcss` is indeed `5.1.1`. This should be because I installed other global libraries via` yarn global add`, and one of those global libraries referenced `detective-postcss@5.1.1`, which does not support node v18.x. However, I installed several global libraries and I didn't know which one referenced `detective-postcss@5.1.1`. So, I upgraded all global libraries using `yarn global upgrade-interactive`. After upgrading, the version of `detective-postcss was 5.1.3` and this version supports node v18.x. Now there is no problem. Thank you~.

**Comment by derrickmehaffy** [comment]
> Hi @Eventyret, I found the reason why. I discovered that the version of this library in the directory `C:\Users\user\AppData\Local\Yarn\Data\global\node_modules\detective-postcss` is indeed `5.1.1`. This should be because I installed other global libraries via` yarn global add`, and one of those global libraries referenced `detective-postcss@5.1.1`, which does not support node v18.x. However, I installed several global libraries and I didn't know which one referenced `detective-postcss@5.1.1`. So, I upgraded all global libraries using `yarn global upgrade-interactive`. After upgrading, the version of `detective-postcss was 5.1.3` and this version supports node v18.x. Now there is no problem. Thank you~.

You can use `yarn why detective-postcss` and it will tell you every package path that uses it.
