### ISSUE TITLE
Fields getting left off from populate

### ISSUE THREAD

**Issue by TimLanzi** [strapi/strapi#16114]
## Bug report
I have a deeply nested content type, and on the inner most leaf I have a file field. This field gets left out from all API calls no matter what I have as my populate statement. I am also using `strapi-plugin-populate-deep`, but that doesn't work either. This only started when I upgraded from Strapi 4.6.0 to 4.8.0. It continues to not function properly in Strapi 4.8.2.

### Required System information

- Node.js version: 16.7.0
- Yarn version: 1.22.19
- Strapi version: 4.8.2
- Database: SQLite
- Operating system: Windows 10 & Ubuntu 22
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Deeply nested file field is getting left off of API results

### Steps to reproduce the behavior

1. Create content type similar to:
```json
// Field names with question marks are optional
{
  "title": "string",
  "slug": "string",
  "image?": "file",
  "related_projects": "relation (many to many)",
  "tables": {
    "title": "string",
    "combined_file?": "file",
    "rows": {
      "title": "string",
      "file?": "file"
    }[]
  }[]
}
```

2. Create content. Files can be any type (pdf, zip, xml, etc.).
3. Attempt to query data populating everything. I use `strapi-plugin-populate-deep` version 1.1.2, but I also tried the non-plugin way from the docs.
4. The `file` field at the deepest point in the nesting will not appear in the results.

### Expected behavior

I expect to see the file object in my API results.

**Comment by Eventyret** [comment]
Thank you for your report @TimLanzi.
Could you try it without the `strapi-plugin-populate-deep` And manually construct a deeply nested query? Could you see if that works? From the [Strapi Docs 📚](https://docs.strapi.io/dev-docs/api/rest/populate-select)

**Comment by TimLanzi** [comment]
Hi @Eventyret. I figured out the issue. It turns out that the field in question was set as a private field. When I was setting up the component, I must've clicked the private box instead of the required box by mistake. It was showing up in the API responses until recently. One of the new updates since 4.6.0 must've patched this. My mistake. Closing the issue. Thank you!
