### ISSUE TITLE
Component field data coming as null in api side

### ISSUE THREAD

**Issue by nitintejuja** [strapi/strapi#16116]
### Required System information

- Node.js version: 16.19
- NPM version: 8.19
- Strapi version: 4.8.2
- Database: pg
- Operating system:ubuntu
- Is your project Javascript or Typescript: javascript

### Describe the bug

Open Content manager for array of components and edit pnly one of array component nested field and you will find the rest of entries with null data in api side. 

### Steps to reproduce the behavior

1. Go to Content Manager
2. Create one field with array of components. Create nested component inside array component
3. Edit then one of array component and its nested component field
4. You will find the rest of nested component field entries data as null in api side

### Expected behavior

It should return edited entry data and rest of fields should not be sent with null data

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Marc-Roig** [comment]
@nitintejuja Hello, do you mean the entries are null in your Admin API response? Or by using the Rest API?

Could you share an example of your conte type and compos? I am not able to replicate this issue.

**Comment by nitintejuja** [comment]
when you open the component the its empty in admin panel but its values are coming as null in rest api side

**Comment by Marc-Roig** [comment]
@nitintejuja I am trying to replicate your issue in 4.9.0 and I don't see the nested components coming as null in the admin api, could you give an example of a content type and an api response?

**Comment by Marc-Roig** [comment]
indeed this seems to be fixed in 4.9.0 by https://github.com/strapi/strapi/issues/16111 . I will close it for now, if you find this isssue happening in 4.9.0 we can open it again :)
