### ISSUE TITLE
Can't upload SVG files

### ISSUE THREAD

**Issue by laurentpellet** [strapi/strapi#16128]
### Required System information

- Node.js version: 14.21.3
- NPM version: 7.17
- Strapi version: 4.7
- Database: sqlite
- Operating system: alpine
- Is your project Javascript or Typescript: javascript

### Describe the bug

Since we had updateded Strapi from 4.1 to 4.7, we are unable to upload SVG files on Media Library. But JPG uploads are fine.
And the preview of the file is working (just before uploading)
Here what i got in strapi logs.

> Fontconfig error:
> 0|NODE_ENV=production yarn develop  | Cannot load default config file: No such file: (null)

### Steps to reproduce the behavior

1. Go to Media Library
2. Upload a new asset (from Desktop or Drag'n Drop)
3 . See error : An erro occured while uploading the file

### Screenshots

![Capture d'écran 2023-03-17 121356](https://user-images.githubusercontent.com/11530611/226063250-ebe701ab-24a2-4326-970c-f11e54bdffd0.jpg)

![Capture d'écran 2023-03-17 121314](https://user-images.githubusercontent.com/11530611/226062753-6f2057a7-5e26-4cc4-9f13-0e01f6803be4.jpg)

![Capture d'écran 2023-03-17 122110](https://user-images.githubusercontent.com/11530611/226063226-b12cf7d8-ac64-461e-932c-a8e73d1c8d68.jpg)

**Comment by laurentpellet** [comment]
We just find out that some SVG files works, some don't.
Please find attached one which is not working.
Maybe something in the header of the file ?
![1370 tab1](https://user-images.githubusercontent.com/11530611/228952079-cf984dbb-b401-4378-b63c-84e3e53f5137.svg)

**Comment by laurentpellet** [comment]
![1370-tab1](https://user-images.githubusercontent.com/11530611/228989665-de9aceb4-5088-45b0-874a-5a560b3112be.svg)
![1370 tab1_00001](https://user-images.githubusercontent.com/11530611/228989671-e847997a-591a-41a4-bf86-6217ef0b901c.svg)

**Comment by YannickFi** [comment]
I had a similar issue when uploading svgs.
Adding the following [dependencies](https://docs.strapi.io/dev-docs/installation/docker#production-dockerfile) and updating strapi from 4.7 to 4.9 resolved the issue 
```
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev 
```

**Comment by Marc-Roig** [comment]
I can not reproduce the issue.
Could you try using the dependencies @YannickFi mentioned? Those are necessary for sharp to work. @laurentpellet

**Comment by laurentpellet** [comment]
Hello and thanks for the answer.
Trying from a fresh new project and it worked.
Here is the version I'm using vs the one created from scratch
![image](https://github.com/strapi/strapi/assets/11530611/8e6b3f7b-3e94-424c-8610-fa71baa3c2c0)

I'm updgrading my strapi version and letting you know.

**Comment by laurentpellet** [comment]
With Node 18.16 and Strapi 4.10.5, everything is OK.
Thanks for watching..
