### ISSUE TITLE
Strapi won't start after installing GraphQL on Windows

### ISSUE THREAD

**Issue by nidkil** [strapi/strapi#1612]
**Informations**
- **Node.js version**: 8.10.0
- **npm version**: 3.0.0-alpha.12.7.1
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: MongoDB 3.6.0
- **Operating system**: Windows 10

**What is the current behavior?**
I install GraphQL succesfully with the command:

- strapi install graphql

When I restart Strapi I get the following error message:

- error Cannot find module 'c:\vue\strapi-test\node_modules\strapi\lib\utils'

When I check the node_modules directory there is no directory strapi. Only the following Strapi directories are available: strapi-mongoose, strapi-utils.

**Steps to reproduce the problem**

Follow the above steps

**What is the expected behavior?**

Strapi should start normally with GraphQL functionality.

**Suggested solutions**

Could it be that the directory has moved from '...\node_modules\strapi\lib\utils' to '...\node_modules\strapi-utils'?

**Comment by jukefr** [comment]
https://github.com/strapi/strapi-plugin-graphql appears to have suddenly disappeared, that seems to be the problem for me.
when installing I get an error that tells me to check https://www.npmjs.com/package/strapi-plugin-graphql and following the github repo on that page lands a 404

**Comment by derrickmehaffy** [comment]
@jukefr the missing repo shouldn't be an issue as the development for that plugin is done in:
https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-graphql

I am able to install it on Linux, currently support for windows is very hit or miss. The current solutions are to either work in WSL or use a linux VM if you have to develop on windows. Better support for windows is coming, the strapi team are working on it.

Please try testing within WSL.

**Comment by derrickmehaffy** [comment]
Side note, Strapi generally requires node 9 or greater, I know the work around on windows to get past the database setup is to downgrade to node 8 but the rest of the project doesn't support that.

**Comment by jukefr** [comment]
My issue seems to be completely independent from Strapi after all and a bug with NPM itself, I will investigate some more and open an issue here if needed.

**Comment by otakuf** [comment]
@jukefr as temp fix, after install plugin, just reinstall strapi in project folder. This works for me on windows.
https://github.com/strapi/strapi/issues/971#issuecomment-383117930

**Comment by indiecore-fm** [comment]
> @jukefr as temp fix, after install plugin, just reinstall strapi in project folder. This works for me on windows.
#971 (comment)

This does temp fix it. But bug still persists.

**Comment by mickidum** [comment]
strange resolved for me:
after installing plugin and getting error
npm install strapi-plugin-graphql - still get error
npm remove strapi-plugin-graphql
strapi start - no errors. wow

**Comment by napop** [comment]
after install graph
` strapi install graphql`
you may have to 
`npm install`
again
I can fix this problem with this

**Comment by asharamseervi** [comment]
Thanks @napop !! It's worked for me.
Obviously, we need to install further dependencies & have to update packages via `npm install` after installing plugin.

It would be more better if it would be possible through GUI/Dashboard itself.

**Comment by MartinMuzatko** [comment]
I can't even install via CLI:
![image](https://user-images.githubusercontent.com/2950505/48319311-b2e2bc80-e60c-11e8-8149-8112e5f27bb0.png)
