### ISSUE TITLE
Strapi 4: How to override the “authenticate” method in strategies to implement custom JWT validation logic

### ISSUE THREAD

**Issue by KunalAggarwal** [strapi/strapi#16130]
## System Information
- **Strapi Version**: 4.6.1
- **Operating System**: macOS 13.1
- **Database**: MySQL 8
- **Node Version**: 18.12.1
- **NPM Version**: 8.19.2
- **Yarn Version**: N/A

---

I have implemented a custom JWT by overriding the "callback" method in the file `src/extensions/users-permissions/strapi-server.js`

The JWT now does not contain just the id parameter, but also contains a few other parameters, which are needed for my application.

To validate all API calls, I need to override the `authenticate` method provided in this file `https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/strategies/users-permissions.js`

How do I override this method? I thought placing some code in `src/extensions/users-permissions/strapi-server.js` should work, but I am not able to make it work. Any suggestions on how to do this?

**Comment by koltenfluckiger** [comment]
Hello,
 
This is just a informed guess, but how I've done it through the extensions is like you described as well. It looks like they are importing that file through the registry file.

https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/register.js

So I'm assuming you could make your own registry file, and strategy file and it should override it if you import it in the `./server.js` file.

**Comment by koltenfluckiger** [comment]
I actually just implemented it. You need to copy the entire folder structure of 'users-permissions' plugin to the extensions folder and it should allow you to customize it.

**Comment by kevinvugts** [comment]
> I actually just implemented it. You need to copy the entire folder structure of 'users-permissions' plugin to the extensions folder and it should allow you to customize it.

Can you elaborate more on this? Do you use version 4? 
Maybe can you provide us with some screenshots?
