### ISSUE TITLE
Stripe marketplace?

### ISSUE THREAD

**Issue by Charuru** [strapi/strapi#1614]
I want to use stripe to let users sell their own items. How easy is it to convert the existing stripe plugin into stripe marketplace or does it make sense to just start from scratch instead of looking at the plugin?

**Comment by lauriejim** [comment]
Hello @Charuru. This plugin not exist today. Feel free to upvote it on [vote page](https://strapi.io/vote)

**Comment by Charuru** [comment]
@lauriejim Yes I understand, I was asking about if I should still buy the existing stripe plugin to use as reference or should I not bother. I know I would have to write it myself.
