### ISSUE TITLE
IconButtons in the PreviewBox of Media pickers are transparent

### ISSUE THREAD

**Issue by gfpacheco** [strapi/strapi#16143]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.8.2
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Icon buttons in the preview box of a media picker are transparent

### Steps to reproduce the behavior

1. This is reproducible in a fresh new Strapi app

### Expected behavior

Buttons should have a background

### Screenshots

![image](https://user-images.githubusercontent.com/3705660/226380651-447a4fde-5ea6-4598-8e65-377d0e2c837b.png)

**Comment by joshuaellis** [comment]
Thanks for reporting this, this should be solved in 4.8.3 of strapi.
