### ISSUE TITLE
Cannot find module '@strapi/plugin-graphql/package.json'

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#16146]
### Required System information

v16

- Node.js version: 16
- NPM version: tried version 8 and 9
- Strapi version: 4.8.2
- Database: Postrgresql
- Operating system: Linux
- Is your project Javascript or Typescript: typescript

### Describe the bug

Cannot start strapi, I get the error Cannot find module '@strapi/plugin-graphql/package.json'

### Steps to reproduce the behavior

1. Set version 4.8.2 in package.json 
2. run npm install
3. run npm run strapi dev
4. get error

### Expected behavior

Strapi starts correctly

### Additional context

I downgraded to 4.7.1 and it works correctly. I upgraded back to 4.8.2 and error keeps on happening. Also I ran `npm list graphql` and the package is installed correctly. Tried to remove node_modules, lock file and clean cache to reinstall and get the same error.

**Comment by pcriadoperez** [comment]
it works with yarn but not npm

**Comment by thexpand** [comment]
It may be due to your `npm` version. For some strange reason, as stated in the docs, Strapi doesn't seem to work with `npm` version other than version 6. Given that the latest `npm` version is `9.2.0`, I don't know why Strapi doesn't support it.

**Comment by joshuaellis** [comment]
> It may be due to your npm version. For some strange reason, as stated in the docs, Strapi doesn't seem to work with npm version other than version 6. Given that the latest npm version is 9.2.0, I don't know why Strapi doesn't support it.

I think the docs are a little incorrect and i'll try get that addressed. Strapi should work on those versions of `npm` :)

@pcriadoperez just to humour me, can you delete your `.cache` & `build` folder, run `npm i && npm run build` and see if that works? 🤔  Failing that I think we would need you to provide a repo reproduction of the issue please.
