### ISSUE TITLE
Publish button not working

### ISSUE THREAD

**Issue by JakeHolcroft** [strapi/strapi#16152]
Hi

I am having a publishing issue with a particular collection type, when i press the publish button, nothing happens where as with the other collection types it works fine, no console log unfortunately but in the server log i get this when i press publish:

[2023-03-21 09:18:04.380] http: GET /content-manager/collection-types/api::article.article/61/actions/numberOfDraftRelations (53 ms) 200

**Comment by joshuaellis** [comment]
Hey @JakeHolcroft, please follow the template or the issue will automatically close 🙏🏼
