### ISSUE TITLE
Unable to filter by private field since 4.8.1

### ISSUE THREAD

**Issue by gfpacheco** [strapi/strapi#16169]
### Required System information

- Node.js version:v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.8.2
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: TS

### Describe the bug

Prior to 4.8.1 I could filter by a private field, and that makes sense to me.
Even if I can't read that field (a relation in my case) I should be able to filter by them.

I think this was changed in https://github.com/strapi/strapi/commit/801e3db41563d41e969944e244b5c7df19844f6b

### Steps to reproduce the behavior

1. Create an entity
2. Create a relation with User and make that field private
3. Try to query a list of entities filtered by the relation with User
4. See that the filter isn't applied

**PS: the same thing happens for fields that aren't private, but the user role doesn't have find permission on the related entity (User).**

### Expected behavior

The relation filter should be applied even if I can't get the related entity in the response.

### Code snippets

This filter `{ user: { eq: { id: "1" } } }` will not work if the user relation field is private OR if the caller doesn't have find permission on the User entity.

PS: I'm using GraphQL but I don't think that makes any difference here

**Comment by derrickmehaffy** [comment]
We deemed that this was a security risk and are now completely sanitizing all private field filters.

We are sorry that this would be a breaking change for you but for the security of all of our users it was a required one.

As a work around I would advise changing the field back away from private and perform the sanitization of the field yourself in a route middleware or something similar.

If you have any questions please reach out to us at security@strapi.io
