### ISSUE TITLE
Can't filter by private fields

### ISSUE THREAD

**Issue by lpbonomi** [strapi/strapi#16172]
I have a table in Strapi that has an email field and a name field, both of them required. When I try to filter by name (using $eq) and there are no rows with that name, I get 0 results. When I try to filter by email I get all the rows in my table. The query is identical, it only changes the field being filtered

```
    const query = qs.stringify({
      populate: '*',
      filters: { name: { $eq: 'name' } }
    })
    const url = `${process.env.NEXT_PUBLIC_STRAPI_BASE_URL}/api/app-users?${query}`
```
```
    const query = qs.stringify({
      populate: '*',
      filters: { email: { $eq: 'email' } }
    })
    const url = `${process.env.NEXT_PUBLIC_STRAPI_BASE_URL}/api/app-users?${query}`
```

**Comment by lpbonomi** [comment]
Looks like the email field is not being fetched in the resulting rows

**Comment by lpbonomi** [comment]
I left my code exactly as it is, but downgraded strapi to v4.7 and it works now, looks like a bug in the new version

**Comment by Convly** [comment]
Hey, thanks for opening this issue, could you share the definition of those attributes in your schema.json please?

**Comment by lpbonomi** [comment]
Hi @Convly , thanks for the fast reply.

I've checked the schema and the `email` field has the `private` option set to `true`,  I've tried removing this and it now filters correctly. I'm not sure if this is a bug or not, but the behaviour changes from v4.7 to v4.8 and it is not documented

**Comment by Megoos** [comment]
I have a similar problem, `await this.sanitizeQuery(ctx)` removes {user: user.id} from the ctx.query.filters. In version 4.7 everything worked.

**Comment by derrickmehaffy** [comment]
This is intended as it was part of the security fix. Filtering on private fields was never intended.

I'm sorry if this is a breaking change, but it's one that we will not reverse as security for all of our users is 9ur top priority.

As a work around, you could remove the private attribute and sanitize the response yourself via a middleware or lifecycle.
