### ISSUE TITLE
Strapi transfer does not work

### ISSUE THREAD

**Issue by hassanzadeh** [strapi/strapi#16171]
### Required System information

- Node.js version: Tried v14 , v16(v16.19.1)
- NPM version: 6.14.18
- Strapi version: v4 (latest)
- Database: sqllight
- Operating system: Linux Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The strapi transfer does not work.

### Steps to reproduce the behavior

1. Installed strapi v4 on a remote machine (https://myblog.site.com) configured nginx, redirecting to localhost:1337
2. Installed strapi v4 on local
3. from local ran npm strapi transfer -- --to https://myblog.site.com/admin --to-token mytransfer token

### Expected behavior
Expect the transfer to succeed.

### Screenshots
<img width="1603" alt="image" src="https://user-images.githubusercontent.com/13952413/226749985-e0fd2c1b-7d09-47a2-81a4-c6637ba547f3.png">

### Additional context
On the remote server, log I have this line when I try to initiate the transfer:
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/13952413/226749904-d7ab0931-aeca-4f27-85aa-8bb30e00f808.png">

**Comment by christiancp100** [comment]
If you are forwarding your request to an internal port in your server using nginx, you may have to use this parameters at least to allow the web sockets communication:
```
server {
    listen 80;
    server_name 142.93.98.236;
    location / {
        proxy_pass http://localhost:1337;
        proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
        include proxy_params;
    }
}
```

**Comment by hassanzadeh** [comment]
Thanks for the comments, I was actually thinking along that way. However, I just added the three extra lines (last three) you listed there, but that is still not working, for me it now looks like this:
`server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name blog.mysite.com;


        ssl_certificate /var/www/blog.mysite.com/cert/combined.crt;
        ssl_certificate_key     /var/www/blog.mysite.com/cert/private.key;

        index index.html index.htm ;

        location / {
                # reverse proxy for next server
                proxy_pass http://localhost:1337;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                include proxy_params;
        }

}
`
