### ISSUE TITLE
No way to disable `strapi::cors` middleware

### ISSUE THREAD

**Issue by larbish** [strapi/strapi#16181]
### Required System information

- Node.js version: v18.14.0
- NPM version: 9.3.1
- Strapi version: 4.8.2
- Database: pqsql
- Operating system: MacOS
- Is your project Javascript or Typescript: JS

### Describe the bug

I am overriding Strapi cors in the `config/middleware.js` file and I used to disable it with `config.disabled`:
```
  {
    resolve: './src/middlewares/cors',
    config: {
      ...   
    }
  },
  {
    name: 'strapi::cors',
    config: { enabled: false }
  },
```

Since this config seems to be deprecated I am now facing this [warning](https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/middlewares/cors.js#L23)

But when I try to remove `strapi::cors` from the middleware array as it is described in the warn I am facing an error on strapi bootstrap: `Missing required middlewares in configuration. Add the following middlewares: "strapi::cors"`

What is the solution ?

### Steps to reproduce the behavior

1. Set `config.enable: false` in your middleware array in  `config/middleware.js`
2. Constat the warn
3. Remove `strapi::cors` from the array as it is described in the warn
4. Constat the error

**Comment by Marc-Roig** [comment]
hello, cors was added into the list of required middlewares in strapi. By default the cors configuration is very flexible


const defaults = {
  origin: '*',
  maxAge: 31536000,
  credentials: true,
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
  headers: ['Content-Type', 'Authorization', 'Origin', 'Accept'],
  keepHeadersOnError: false,
};

can you share your usecase when using this cors config does not fit it?

**Comment by larbish** [comment]
Default cors config math my need in all cases but I want to override the cors logic for some routes. The idea is to authorise call from external origin for some routes based on a token send in the request. 

Something like:

```js
const token = ctx.query?.token
const url = ctx.request.url
if (url match my allowed routes) {
  try {
  // decrypt token 
  // check if request is allowed in db based on token data
  } catch (e) {
    // Ignore and fallback to strapi default cors
  }
}

// fallback to strapi default cors
```

**Comment by Marc-Roig** [comment]
Hello, I don't think that is currently possible with how cors is setup and this would fall more as a feature request :)

**Comment by Nitive** [comment]
I would consider this a major vulnerability since most people will use default configuration not knowing it's not secure. One can only imagine how many vulnerable strapi instances there are

**Comment by M1k3-M** [comment]
Yeah, feels like such configurations should be restrictive by default.
It feels like when mongo used 0.0.0.0 as default binding
