### ISSUE TITLE
Unable to view audit logs when user doesn't have permissions to read admin users

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#16184]
### Required System information

- Node.js version: v18
- NPM version: v9
- Strapi version: v4.8.2
- Database: SQLite
- Operating system: Linux Mint 21
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When trying to view the audit logs as another role other than super admin and you don't have access to `read` the admin users it will throw an error

### Steps to reproduce the behavior

1. Grant `Editor` role access to the audit logs and read permissions for admin users
2. Create a new user in the editor role
3. Trying to view audit logs as this new user and successfully see the audit logs
4. As super admin, remove the admin user read permission
5. Try to view audit logs as the new user again
6. See error

### Expected behavior

Either a useful error message should show in the audit logs or the logs should still load but without the admin user information

### Screenshots

![image](https://user-images.githubusercontent.com/8593673/226963688-112137e3-989a-4b63-9c28-6719a3358475.png)
![image](https://user-images.githubusercontent.com/8593673/226963807-76e14068-e5b4-4010-86b1-a641999ff6db.png)

### Code snippets

N/A

### Additional context

Related to internal TID2563

**Comment by maevalienard** [comment]
We have an emptyState variant dedicated to this usecase: https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-emptystatelayout--base

<img width="298" alt="Capture d’écran 2023-03-23 à 10 03 15" src="https://user-images.githubusercontent.com/54801383/227157863-06ea99a8-d646-4a88-97b8-78dffc974068.png">
