### ISSUE TITLE
Translation keys missing in AR language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#1619]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/ar.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/ar.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

📦 strapi-plugin-email - [/packages/strapi-plugin-email/admin/src/translations/ar.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-email/admin/src/translations/ar.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|ConfigPage.description | Configure the email plugin|
|ConfigPage.title | Email - Settings|
|EditForm.Input.number.label | Maximum size allowed (in MB)|
|EditForm.Input.select.inputDescription | Emails can be sent with the default provider (Sendmail) or an external provider|
|EditForm.Input.select.label | Providers|
|EditForm.Input.toggle.label | Enable email send|
|notification.config.success | The settings has been updated|

📦 strapi-plugin-settings-manager - [/packages/strapi-plugin-settings-manager/admin/src/translations/ar.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-settings-manager/admin/src/translations/ar.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|form.server.item.proxy | Proxy Settings|
|form.server.item.proxy.enable | Proxy Enable|
|form.server.item.proxy.host | Proxy Host|
|form.server.item.proxy.port | Proxy Port|
|form.server.item.proxy.ssl | Proxy SSL|

📦 strapi-plugin-users-permissions - [/packages/strapi-plugin-users-permissions/admin/src/translations/ar.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/admin/src/translations/ar.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|Auth.form.error.blocked | Your account has been blocked by the administrator.|
|Auth.form.error.confirmed | Your account email is not confirmed.|
|Auth.form.error.ratelimit | Too many attempts, please try again in a minute.|
|EditForm.inputToggle.description.email-confirmation | When enabled (ON), new registred users receive a confirmation email.|
|EditForm.inputToggle.description.email-confirmation-redirection | After confirmed your email, chose where you will be redirected.|
|EditForm.inputToggle.label.email-confirmation | Enable email confirmation|
|EditForm.inputToggle.label.email-confirmation-redirection | Redirection url|
|Email.template.email_confirmation | Email address confirmation|
|PopUpForm.Providers.discord.providerConfig.redirectURL | The redirect URL to add in your Discord application configurations|
|PopUpForm.Providers.microsoft.providerConfig.redirectURL | The redirect URL to add in your Microsoft application configurations|
|components.Input.error.password.length | Password is too short|

**Comment by xlmnxp** [comment]
- [ ] strapi-admin
- [ ] strapi-plugin-content-manager
- [ ] strapi-plugin-content-type-builder
- [x] strapi-plugin-email

**Comment by lauriejim** [comment]
I close this issue because we are moving to Crowdin to manage translations.
We will update the contribution guide to add information to how contribute to translations.
