### ISSUE TITLE
Translation keys missing in DE language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#1620]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/de.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/de.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

**Comment by lauriejim** [comment]
Yeah ! That is super good news !

**Comment by sennahLessert** [comment]
i'll do that

**Comment by lauriejim** [comment]
I close this issue because we are moving to Crowdin to manage translations.
We will update the contribution guide to add information to how contribute to translations.
