### ISSUE TITLE
Email Plugin doesn't read configuration

### ISSUE THREAD

**Issue by louisunlimited** [strapi/strapi#16209]
### Required System information

- Node.js version: 18.11.10
- NPM version: 8.19.2
- Strapi version: 4.8.2
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Email provider plugin does not read `settings` field in `plugins.ts`. This bug causes the entire mail to not work for `gmail` users.
For non-gmail users, they receive an email from `no-reply@strapi.io`.

<img width="337" alt="Screenshot 2023-03-25 at 16 05 50" src="https://user-images.githubusercontent.com/20884681/227741910-81e93a20-5dba-48a2-889b-cd085d47e736.png">

### Steps to reproduce the behavior

1. Install `@strapi-provider-email-nodemailer@3.6.11`
2. Set the following in `plugins.ts`
```typescript
email: {
    provider: env("EMAIL_PROVIDER"),
    providerOptions: {
      host: env("EMAIL_SMTP_HOST", "smtp.example.com"),
      port: env("EMAIL_SMTP_PORT", 587),
      auth: {
        user: env("EMAIL_SMTP_USER"),
        pass: env("EMAIL_SMTP_PASS"),
      },
    },
    settings: {
      defaultFrom: env("DEFAULT_EMAIL"),
      defaultReplyTo: env("DEFAULT_EMAIL"),
    },
  },
```
3. Then try to send an email (I am using sendinblue, for example), the sender will still get defaulted to `strapi.io`.
4. Since the sender gets defaulted to `no-reply@strapi.io`, email is unusable for gmail users and strapi throws the following error:
```
.
Error: Couldn't send test email: SMTP code:550 msg:550-5.7.26 Unauthenticated email from strapi.io is not accepted due to domain's
550-5.7.26 DMARC policy. Please contact the administrator of strapi.io domain
550-5.7.26 if this was a legitimate mail. Please visit
550-5.7.26  https://support.google.com/mail/answer/2451690 to learn about the
550 5.7.26 DMARC initiative. s68-20020ae9de47000000b00747d1d07938si3368079qkf.237 - gsmtp
.
```
### Expected behavior

Email should be sent from the correct sender configured in `plugins.ts`

### Screenshots

<img width="337" alt="Screenshot 2023-03-25 at 16 05 50" src="https://user-images.githubusercontent.com/20884681/227741910-81e93a20-5dba-48a2-889b-cd085d47e736.png">

This page did not populate as well
<img width="1270" alt="Screenshot 2023-03-25 at 16 06 40" src="https://user-images.githubusercontent.com/20884681/227741941-77b3c6fb-9a40-4632-949e-2fb73ff24be9.png">

### Additional info
This issue is a superset of #16179 because this issue is focused on email plugin being functionally un-usable instead of not populating fields for the admin panel

**Comment by myso-kr** [comment]
same issue.
not send authorized email.

**Comment by louisunlimited** [comment]
@bolg55 Hi, do you mind if I ask if this is still being worked on? If you guys want I can help to try to fix this, could you give me some guidance on how to do this?

**Comment by Marc-Roig** [comment]
hello! :) @louisunlimited, for sure you can work on this!

If you want to start looking at it, the code responsible of reading the settings is in here:
`packages/providers/email-nodemailer/lib/index.js`

This provider is responsible of sending emails using nodemailer, at first it seems that is using the settings config but maybe it's not being passed correctly 🤔 

To actually test the app, you can do in this monorepo:
```
yarn setup
cd examples/getstarted
yarn develop
```

with this you will be able to start a strapi instance, and in the getstarted project you can configure the plugin options too :)

**Comment by louisunlimited** [comment]
> hello! :) @louisunlimited, for sure you can work on this!
> 
> If you want to start looking at it, the code responsible of reading the settings is in here: `packages/providers/email-nodemailer/lib/index.js`
> 
> This provider is responsible of sending emails using nodemailer, at first it seems that is using the settings config but maybe it's not being passed correctly 🤔
> 
> To actually test the app, you can do in this monorepo:
> 
> ```
> yarn setup
> cd examples/getstarted
> yarn develop
> ```
> 
> with this you will be able to start a strapi instance, and in the getstarted project you can configure the plugin options too :)

Hi @Marc-Roig , I tried to reproduce this error on local machine but soon found out it seems like the root cause is because I was using the old `v3` nodemailer provider without noticing it 😅. Interestingly enough, the old provider works with `plugins.js` but not in my `plugins.ts` so it's really confusing at first for me to notice this. If there's nothing more I can do you can mark this issue as closed now, I've already posted comments in other similar issues like #16176
