### ISSUE TITLE
Configuration file is not updated on components with more than 2 layers depth

### ISSUE THREAD

**Issue by flokamps** [strapi/strapi#16206]
### Required System information

- Node.js version: v18.14.2
- NPM version: 9.5.0
- Strapi version: v4.8.2
- Database: MySQL v8.0.32-1.el8
- Operating system: macOS Ventura 13.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

We are currently using components, within components, within components (so 3 layers). Before, we had pre-filled fields, other non-mandatory sections that were folded in (see the screen below)

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/58564956/227578112-c6fb592e-c809-47c8-aea1-bd0bd4dd4e2f.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/58564956/227578151-3ffb5525-775b-4960-a97a-0d030223677d.png">

Now, since the update, these fields are no longer pre-filled ("Taile", "Couleurs", "Contours") and the sections underneath are no longer pre-filled ("Deuxième ligne", "Troisième ligne"...)

After some investigation we noticed that the configuration export does not update the components more than 2 layers deep. To give you an idea of how our components are configured, here are the different layers:

First layer:
```json
"title_line_1": {
      "type": "component",
      "repeatable": false,
      "component": "inner-section.title-line",
      "required": true
    },
```

Second layer:
```json
"title_line_part_1": {
      "type": "component",
      "repeatable": false,
      "component": "inner-section.title-line-parts",
      "required": true
    },
```

Third layer:
```json
"attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "outline": {
      "type": "boolean",
      "default": false,
      "required": true
    },
    "size": {
      "type": "enumeration",
      "enum": ["Petit", "Normal", "Gros"],
      "default": "Normal",
      "required": true
    },
    "color": {
      "type": "enumeration",
      "enum": ["Noir", "Rouge", "Blanc"],
      "default": "Noir",
      "required": true
    }
  }
```

### Steps to reproduce the behavior

1. Create a new component
2. Nested 2 more layers of components to get 3 layers
3. Add prefiled fields to the last layer's component
4. See that the field is not prefiled

### Expected behavior

As shown in my screenshots above, the fields should be pre-filled and the other non-mandatory sections should not be opened

**Comment by joshuaellis** [comment]
Can you update your Strapi version to see if this solves the issue? I can't reproduce on the current version `4.11.4`
