### ISSUE TITLE
uploadFiles graphql filtering is broken

### ISSUE THREAD

**Issue by igarren** [strapi/strapi#16213]
### Required System information

- Node.js version: 14.20.0
- NPM version: 6.14.17
- Strapi version: 4.8.2
- Database: sqllite / postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: typescript

### Describe the bug

Since the new update, uploadfiles filtering is broken. 
meta total yields 0, but data is being returned

### Steps to reproduce the behavior

1. Upload a media file
2. Graphql query to filter files by folder name 
3. meta total yields 0 but data is being returned

### Expected behavior

Files should be filtered by folder name 

### Screenshots

<img width="485" alt="image" src="https://user-images.githubusercontent.com/38416222/227788100-ea5d5c40-e322-46b7-8848-486fec63d248.png">

### Code snippets

```

    query GetFiles($page: Int, $pageSize: Int) {
  uploadFiles(
    filters: { folder : { name : { eq :  "/API up222loads"}}}
    pagination: {pageSize: $pageSize, page: $page}
  ) {
    data {
        id
    }
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }
  }
}
    
```

### Additional context

This wasnt happening prior to the latest upgrade

**Comment by viiiprock** [comment]
same with other fields, i.e: id filter returned 3 but all data shows
 
<img width="1430" alt="Screenshot 2023-05-11 at 08 29 13" src="https://github.com/strapi/strapi/assets/14918259/accb4478-c833-48e1-a1bc-fd7e5d16f490">
