### ISSUE TITLE
Translation keys missing in ES language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#1621]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/es.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/es.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

**Comment by maturanomx** [comment]
🤔 Any details of what is this re-open?

... Anyway, you can assignee it to me if you want ;)

**Comment by lauriejim** [comment]
I update the issue body with missing keys @maturanomx

**Comment by maturanomx** [comment]
Oh!, Thanks for let me know. I will take a look when a have time 👍

**Comment by lauriejim** [comment]
Thank you @maturanomx
