### ISSUE TITLE
I can update content that's not mine with a restricted custom role 

### ISSUE THREAD

**Issue by Nicolas-Deleplace** [strapi/strapi#16233]
### Required System information

- Node.js version: **16.13.0**
- NPM version: **8.1.0**
- Strapi version: **4.8.2**
- Database: **Postgresql 14.0**
- Operating system: **MacOS**
- Is your project Javascript or Typescript: **Typescript**

### Describe the bug

I created a translator role which has the rights to create without constraint, to read without constraint, but to be able to update only its content (the translations).
However, the modification restriction does not seem to be taken into account, I can modify all the content I want.

![Capture d’écran 2023-03-28 à 18 05 05](https://user-images.githubusercontent.com/93121137/228302573-049a4ec6-ea08-4cab-9851-4bc34f2e20ce.png)

![Capture d’écran 2023-03-28 à 18 05 37](https://user-images.githubusercontent.com/93121137/228302605-29f4857a-f94d-4806-89f5-d8e91b8b1b36.png)

### Steps to reproduce the behavior

1. Create a role that can unrestrictedly create and read a collection, but only update its content (Is creator)
2. Create a user
3. Login
4. Create a new local content from another content that is not yours : OK
4. **Try to update a content that is not yours : KO**

### Expected behavior

A role that can create translated articles without being able to modify the basic content

**Comment by Marc-Roig** [comment]
Hello, I am trying to reproduce this issue and can not reproduce it, let me know if I am missing something:

- I have an Editor role, this role can create , read & delete an specific content type, but can only edit if it is the creator
![image](https://user-images.githubusercontent.com/20578351/229793265-e0e08212-f0ee-4615-9d2b-b8d728352164.png)

- I can not update, using an Editor role user (only has that role selected) , when I try to update one entity that has not been created by that same account:
![image](https://user-images.githubusercontent.com/20578351/229794603-ad42e794-5942-4efc-b53c-777abb6ef861.png)


So I now have the following questions:
- Does the user only have the `translator` role?
- Are you sure you are using that specific user with that role? By the list of Content Types that should visualize in picture 1, it seems it can see all of them in picture 2 (listed in the left sidebar)

**Comment by Nicolas-Deleplace** [comment]
Okay I just test, you're right, it's just a little bit confusing that the fields are not in readonly mode. 
You can close this issue.

Thanks !
