### ISSUE TITLE
Can't add a data of type media

### ISSUE THREAD

**Issue by Junaifu** [strapi/strapi#16231]
### Required System information
 

 
- Node.js version: 18.13.0
- NPM version: 8.19.4
- Strapi version: 4.8.2
- Database: Postgres
- Operating system: maxOS Monterey v12.6.3
- Is your project Javascript or Typescript: Javascript
 
### Describe the bug
 
When NODE_ENV=production, we can't add a data of type media.
When NODE_ENV=development, it works.
 
### Steps to reproduce the behavior
 
1. Go to "Content-Manager"
2. Click on a collection type with a media type
3. Click on "Create new entry"
4. Try to add a media to the collection
5. See error: "Woops! Something went wrong. Please, try again.
In console: "TypeError: Cannot read properties of undefined (reading 'toString')"
 
### Expected behavior
 
The media modal shows up and we can select images.
 
### Additional context
 
I looked for the bug and find that the endpoint "/upload/configuration" return the following:
- In Production: `data: null`
- In Development: `data: {pageSize: 10, sort: "createdAt:DESC"}`
 
My first bug was the blank page when I tried to access on the "Media Library" page. I saw that severals issues was already open about this and I followed the different advice, but it didn't work.
Then I saw a pull request was done about this, so I upgraded my strapi version from 4.5.6 to 4.8.2 and the "Media Library" page works well.
 
But, when I tried to add a media in the Content Manager, I have this bug, and the symptoms are similar to the first bug.
 
I tried to do a clean build and I checked the "mime" column in my "files" table from my database, and all the files have a value.
 
Issues links:
- https://github.com/strapi/strapi/issues/15454
- https://github.com/strapi/strapi/issues/15751
 
Pull Request link:
- https://github.com/strapi/strapi/pull/15831

**Comment by derrickmehaffy** [comment]
Unable to reproduce on v4.9.0: https://www.loom.com/share/d9529103976442b4bcb93d2622759e58

**Comment by Junaifu** [comment]
Hello,

Thank's for your reply and the loom link ! 😄 
I think the bug should be link to something in our code 🤔 

I don't know is this can help but the data: null is returned because when I set the NODE_ENV to production in the DB in the table "strapi_core_store_settings", it miss an entry:

<img width="1512" alt="Capture d’écran 2023-04-03 à 11 46 19" src="https://user-images.githubusercontent.com/36692295/229478028-5b33999c-f98e-4b32-ae2b-1e487273681a.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/36692295/229476295-603df85f-4393-4c63-b997-ab896e85b77f.png">

Unfortunatelly, I don't know how to reproduce it.

**Comment by Marc-Roig** [comment]
In your production environment can you access `/admin/plugins/upload/configuration` ? In there you should be able to set the config, it seems some users do not have the configuration , we plan to update the frontend to handle this case and set a default value.

In the meantime setting the config in your environment might help.

**Comment by Junaifu** [comment]
Hello @Marc-Roig,

Thank you for your answer.
Indeed, set the configuration in /admin/plugins/upload/configuration works ! 

In our project we use a plugin call 'config-sync' and found out that adding this: 
`config/plugin.js`
``` return {
    "config-sync": {
      enabled: true,
      config: {
        ...
        excludedConfig: [
          ...,
          "core-store.plugin_upload_view_configuration", // new rule
        ],
      },
    },```

Can avoid this bug too
