### ISSUE TITLE
Email config not updating from plugin.js (Nodemailer)

### ISSUE THREAD

**Issue by Vinayak-Bhanushali** [strapi/strapi#16235]
### Required System information
- Node.js version: 16.17.1
- NPM version: 8.15.0
- Strapi version: 4.7.0
- Database: Postgres
- Operating system: Mac Os 12
- Is your project Javascript or Typescript: Javascript

### Describe the bug
I have installed the official [Nodemailer Plugin](https://market.strapi.io/providers/@strapi-provider-email-nodemailer) and have added the configuration to config/plugins.js as per documentation

![config](https://user-images.githubusercontent.com/47302833/228314158-a56abbe1-da96-46bf-9b90-b5dbbe5d2c94.jpeg)

However when and build and run the server no change is visible in strapi admin panel

### Steps to reproduce the behavior

1. Install strapi/provider-email-nodemailer
2. Setup configs in plugin.js
3. npm run develop
4. Go to admin panel>settings>email plugin
5. The selector for sender email and provider is disabled and incorrect

### Expected behavior
Read and show the proper values from plugin.js . Also all the emails should be sent using that configs.

### Screenshots
![strapi admin](https://user-images.githubusercontent.com/47302833/228314079-288cf952-e1ab-4737-9597-db97af77c37a.jpeg)

**Comment by NoorBayari** [comment]
+1

**Comment by NoorBayari** [comment]
@Vinayak-Bhanushali i faced the same issue and it worked after i renamed plugins.js to plugins.ts

**Comment by Eventyret** [comment]
Thank you for submitting this issue @Vinayak-Bhanushali 🙌
One of the issues I can see in this is that it should be `plugins.js`, not `plugin.js`

Now, this might fix it for you, but just to let you know, if you need more assistance, please use our community platforms.

- 🎙️ [Discord](https://discord.com/invite/strapi)
- 📚 [Forums](https://forum.strapi.io/)


> @Vinayak-Bhanushali i faced the same issue and it worked after i renamed plugins.js to plugins.ts

This would be correct but @Vinayak-Bhanushali is currently using `js` not `ts` so this would have no effect. If you are using a `Typescript` project then this would be a great way too.



I will be closing this issue as it's not actually a bug, but rather it seems the wrong setup or filenames. 🥹

**Comment by Vinayak-Bhanushali** [comment]
Ohh my bad, I was editing the plugin.js file which was auto created when I created the strapi project
