### ISSUE TITLE
Clicking the account confirmation link a second time throws an error in Strapi instead of redirecting

### ISSUE THREAD

**Issue by molul** [strapi/strapi#16232]
### Required System information

- Node.js version: v18.12.1
- NPM version: 9.1.3
- Strapi version: 4.8.2
- Database: postgres
- Operating system: MacOS Mojave
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When I click the account confirmation account, the Strapi URL is opened in the brwoser with this error message:
`{"data":null,"error":{"status":400,"name":"ValidationError","message":"Invalid token","details":{}}}`

In previous versions, I'd swear it just went to the redirection URL or shown a message that the account has already been confirmed (please correct me if I'm wrong).

### Steps to reproduce the behavior

1. Create an account
2. Open the confirmation email and click the confirmation link. It will open your redirection URL
3. Click it again
4. This time, the Strapi URL will be open, showing this error message:
`{"data":null,"error":{"status":400,"name":"ValidationError","message":"Invalid token","details":{}}}`

### Expected behavior

I'd expect to be redirected to the redirection page anyway, or get some message that the account has already been confirmed. Showing an error is confusing to users if they don't remember if they confirmed the account.

**Comment by derrickmehaffy** [comment]
While the default URL for these emails templates is the Strapi server, realistically this should be changed to a frontend URL that can handle the request for the user and handle this error message in the frontend and not directly to Strapi itself.

Users and permissions should not have public facing html based pages and all communication over the content API should be done over REST or GraphQL. We should not be redirecting users in an error.

Closing this for now as it's not something we should be handling.
