### ISSUE TITLE
Private ACL not working properly for DO spaces

### ISSUE THREAD

**Issue by suprMax** [strapi/strapi#16245]
### Required System information

- Node.js version: v18.12.1
- NPM version: 9.1.2
- Strapi version: 4.9.0
- Database: SQLite dev, PostgreSQL 15 prod
- Operating system: macOS/Ubuntu
- Is your project Javascript or Typescript: JS

### Describe the bug

Hello there,

I've experienced some issues with private ACL support that was just released with v4.9.0

1. There is a problem with `getBucketFromUrl` not supporting S3-compatible hosting solutions. I am using DO spaces that produces URLs like this: `https://flashfix-files-staging.fra1.digitaloceanspaces.com/development/partners/lieferando/230329_123123_uvv_certificate_157fbcaa62.pdf`
`getBucketFromUrl` doesn't match. Regular expression like this would work: `^(.+\.)?([a-z0-9-]+)\.` but it would be probably better to store bucket in the file meta somewhere.
2. Signed URLs work fine for images but when I try to copy a link to a document the link is copied broken, perhaps encoding is missing or something
3. It appears that the REST API still serves unsigned links, it would be great if it served pre-signed links with the `signedUrlExpires` parameter
4. Bonus error - env returns a string so people have to manually typecast `signedUrlExpires` via parseInt in the plugins config - a little annoying. Example: `signedUrlExpires: parseInt(env('DO_SPACE_URL_EXPIRES', 60 * 60 * 24), 10),`

**Comment by Marc-Roig** [comment]
Hello! @suprMax 
First of all thank you for providing such a detailed description, really helps fixing issues like this.
I will start working on this and provide a fix for the next patch 4.9.1 🚀

**Comment by suprMax** [comment]
I just noticed that I set expiration for 10s during testing so 2. in the list might be false. Happy to help debug this if necessary, discord thread: https://discord.com/channels/811989166782021633/1090678982741069925/1090678982741069925

**Comment by Marc-Roig** [comment]
> then although the file is placed properly in the magicfolder the fileKey is constructed incorrectly with file.path missing from the file object. Not sure why, it's simply not there.

I spotted the issue, when constructing the fileKey during hte url signing we don't have access to the path that was provided during the upload, I will try to find what we can do about this.

**Comment by Marc-Roig** [comment]
In the meantime I don't know if it could fix your usecase, but you can use the `rootPath` config and that would work, but all uploaded files in your strapi instance would share the same rootPath.

**Comment by Marc-Roig** [comment]
We are not storing the path in DB, we have an ongoing discussion about this and the solution might actually be storing it in DB

I will update you when I have knews about this :) Thank you again for all this feedback, you rock 🚀

**Comment by sjoukedv** [comment]
@Marc-Roig for the content-manager and media library it works fine. Is it possible to add a 'middleware' globally for media content? It should be able to return the signedUrl, with https://github.com/strapi/strapi/blob/main/packages/providers/upload-aws-s3/src/index.ts#L114-139, using the path stored in the media object if the ACL is set to private in the config.

Currently, this is (still) breaking all media content that is consumed from the API

**Comment by Marc-Roig** [comment]
yes, this is a work in progress @sjoukedv https://github.com/strapi/strapi/pull/16518 hopefully in 2 weeks this will be merged :)
