### ISSUE TITLE
Components re-appear after delete and save

### ISSUE THREAD

**Issue by radoslavzeman** [strapi/strapi#16259]
### Required System information

- Node.js version: 16.15.0
- NPM version: 7.24.2
- Strapi version: 4.8.2
- Database: postgres
- Operating system: macOS Monterey

### Describe the bug

When I delete a component in content manager, it sometimes reappears after Save. I also tried to refresh the page, but component stays there.

### Steps to reproduce the behavior

Self-explanatory, see the video.

### Expected behavior

Deleted components stays deleted.

### Screenshots

https://user-images.githubusercontent.com/19418224/229036331-bcd777e7-f99d-4952-9489-9c61cb4884f1.mov

**Comment by derrickmehaffy** [comment]
This has been fixed already in v4.9.0 but if you can still reproduce the error in v4.9.0 do let us know.
