### ISSUE TITLE
Translation keys missing in PT-BR language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#1625]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/pt-BR.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/pt-BR.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.components.EmptyAttributes.title | There are no fields yet|
|app.utils.delete | Delete|

📦 strapi-plugin-content-manager - [/packages/strapi-plugin-content-manager/admin/src/translations/pt-BR.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/translations/pt-BR.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|components.EmptyAttributesBlock.button | Go to settings page|
|components.EmptyAttributesBlock.description | You can change your settings|
|containers.Edit.addAnItem | Add an item...|
|containers.Edit.clickToJump | Click to jump to the entry|
|containers.Edit.seeDetails | Details|
|containers.ListPage.displayedFields | Displayed Fields|
|containers.SettingPage.addRelationalField | Add new relational field|
|form.Input.description | Description|
|form.Input.description.placeholder | Display name in the profile|
|form.Input.disabled | Editable field|
|form.Input.placeholder | Placeholder|
|form.Input.placeholder.placeholder | My awesome value|
|notification.error.displayedFields | You need at least one displayed field|

📦 strapi-plugin-settings-manager - [/packages/strapi-plugin-settings-manager/admin/src/translations/pt-BR.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-settings-manager/admin/src/translations/pt-BR.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|form.server.item.proxy | Proxy Settings|
|form.server.item.proxy.enable | Proxy Enable|
|form.server.item.proxy.host | Proxy Host|
|form.server.item.proxy.port | Proxy Port|
|form.server.item.proxy.ssl | Proxy SSL|

📦 strapi-plugin-users-permissions - [/packages/strapi-plugin-users-permissions/admin/src/translations/pt-BR.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/admin/src/translations/pt-BR.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|Auth.form.error.blocked | Your account has been blocked by the administrator.|
|Auth.form.error.confirmed | Your account email is not confirmed.|
|Auth.form.error.ratelimit | Too many attempts, please try again in a minute.|
|EditForm.inputToggle.description.email-confirmation | When enabled (ON), new registred users receive a confirmation email.|
|EditForm.inputToggle.description.email-confirmation-redirection | After confirmed your email, chose where you will be redirected.|
|EditForm.inputToggle.label.email-confirmation | Enable email confirmation|
|EditForm.inputToggle.label.email-confirmation-redirection | Redirection url|
|Email.template.email_confirmation | Email address confirmation|
|PopUpForm.Providers.discord.providerConfig.redirectURL | The redirect URL to add in your Discord application configurations|
|PopUpForm.Providers.microsoft.providerConfig.redirectURL | The redirect URL to add in your Microsoft application configurations|
|components.Input.error.password.length | Password is too short|

**Comment by jbbn** [comment]
Hi @lauriejim 
I am happy to contribute with the project.

I'm curious, why do you reopened the issue?
Did I miss something?
I would be glad to improve the applied solution :)

Reggards!

**Comment by lauriejim** [comment]
I reopen it before check all translation status. To close/edit manually all issues related to translation files.

**Comment by lauriejim** [comment]
I close this issue because we are moving to Crowdin to manage translations.
We will update the contribution guide to add information to how contribute to translations.
