### ISSUE TITLE
Strapi storing created_at, updated_at, published_at time incorrectly in DB

### ISSUE THREAD

**Issue by AB-WAR** [strapi/strapi#16257]
### System information

- Node.js version: 16.19.1
- NPM version: 9.1.1
- Strapi version: 4.8.0
- Database: MySQL 8.0
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

Strapi storing created_at, updated_at, and published_at time incorrectly in DB without timezone.

When Strapi and Database are run on a server in the PDT timezone and a collection type record is inserted Strapi stores 'created_at', 'updated_at', and 'published_at' in the database as strings in the PDT timezone (like 2023-03-31 00:51:37.029000) without converting it to UTC time.

This type of storing timestamps without converting to UTC creates problems when the replica Database and Strapi servers are run in another timezone like say SGT time.

### Steps to reproduce

- Run Strapi and DB in one timezone say PDT
- Example, Insert a collection type record at say time ' 2023-03-31 01:51:37.029000 ' , the time stored in the 'created_at' column in Database is ' 2023-03-31 01:51:37.029000 ' which was not converted to UTC format while storing in the database, it's the same for the 'updated_at', and 'published_at' fields.
- When the Strapi server and DB are migrated or their replicas run in another timezone say, SGT, the record inserted in the previous step time ' 2023-03-31 01:51:37.029000 ' , is now being considered by the Strapi server in SGT as SGT time. 
- This creates issues when an application has multiple Strapi servers in different timezones with the same replica Databases.

So it would be better if Strapi inserts a record 'created_at', 'updated_at', and 'published_at' or any datetime field converting into UTC time in the Database irrespective of the timezone where the Strapi and DB server is running.

**Comment by derrickmehaffy** [comment]
This isn't really an issue of Strapi but more so the connection driver, Strapi takes the default configuration options and expects the database to be running in UTC: https://github.com/mysqljs/mysql#connection-options

You should be able to pass a `timezone` configuration key in the database configuration thought we STRONGLY recommend that you do not run a database outside of UTC as this is considered an extremely bad practice. Generally speaking all backend parts of an application should all "speak" in UTC and it's the job of the frontend to do the conversion.

See this blog post: https://zachholman.com/talk/utc-is-enough-for-everyone-right
