### ISSUE TITLE
Inconsistent afterCreate Hook Behavior for Video Assets when Uploading Media via API and Strapi Interface

### ISSUE THREAD

**Issue by rodrigogs** [strapi/strapi#16258]
### Required System information

- Node.js version: 18.15.0
- NPM version: 9.5.0
- Strapi version: 4.7.1
- Database: MySQL
- Operating system: MacOS, Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

We are experiencing an issue with our Strapi implementation involving video content. Our video content-type has an afterCreate hook set up to trigger the encoding process when a user adds a video entry with a populated videoAsset(media type) field.

When the videoAsset field is populated through the Strapi interface, the afterCreate hook works as expected. However, the hook does not function correctly when media is uploaded via the API using `POST /api/upload`. Although the media is added and displayed correctly in the content-manager when uploading this way, the afterCreate hook doesn't capture the event correctly, and the videoAsset field is missing the necessary information such as the media's ID.

### Steps to reproduce the behavior

1. Populate the videoAsset field through the Strapi interface, and observe the afterCreate hook functioning properly.
2. Upload media through the API using `POST /api/upload`, then create a video entry with the received ID through `POST /api/video` (passing the ID in the videoAsset field).
3. Notice that the afterCreate hook does not function as intended when uploading via API, and the videoAsset field is missing essential information.

### Expected behavior

The afterCreate hook should capture the event and populate the videoAsset field with the correct information when media is uploaded through API, just like the behavior of uploading through the Strapi interface.

**Comment by derrickmehaffy** [comment]
I'll reference one of our application diagrams (sorry it's a bit complex): https://miro.com/app/board/o9J_kkD8OK8=/?share_link_id=460913365257

The lifecycles exist at a very deep layer (the database layer) and wrap directly around the SQL queries made to the database. At this layer relations not longer "exist" and thus cannot be populated as the Strapi relation abstraction simply isn't there. A single entityService request is broke down into it's individual SQL requests to the database and thus the media information simply isn't there.

![image](https://user-images.githubusercontent.com/8593673/229166449-37dc01dc-cd1a-48b5-a0bf-51ade4680263.png)

You can see this here in the code: 

https://github.com/strapi/strapi/blob/7408df892b5a12da19143747d41f1e9614a29688/packages/core/database/lib/entity-manager/index.js#L213-L249

Specifically these lines:

https://github.com/strapi/strapi/blob/7408df892b5a12da19143747d41f1e9614a29688/packages/core/database/lib/entity-manager/index.js#L213

https://github.com/strapi/strapi/blob/7408df892b5a12da19143747d41f1e9614a29688/packages/core/database/lib/entity-manager/index.js#L247

This means that a single entityService.create() is broken down into it's sub SQL queries (depending on the number of relations, media, etc) and there is no way to currently hook into the media library lifecycles. Eventually we probably just need to add entityService lifecycles instead that could operate at a higher level but that isn't really a bug and more of a feature request.

I've created the following feature request for this here: https://feedback.strapi.io/developer-experience/p/add-lifecycles-at-a-higher-level-entityservice
