### ISSUE TITLE
In certain locales the decimal will change format that is incorrect

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#16267]
### Required System information

- Node.js version: v18
- NPM version: v9
- Strapi version: v4.9.0
- Database: SQLite
- Operating system: Linux Mint 21
- Is your project Javascript or Typescript: Both

### Describe the bug

In certain locales, when entering a decimal (eg 3.14) and clicking away from the field will convert it's format to an unsupported type (generally applies to locales that replace the decimal point with a comma (eg 3,14).

Has been reproduced already by @simotae14 and myself

### Steps to reproduce the behavior

Note: Requires a browser that runs in a different locale than US or UK english, generally a locale that does not use decimal points for decimal values

1. Set a decimal field value
2. Click away
3. See error

### Expected behavior

The frontend should properly convert the value to the proper format, specifically the value in the backend will need to be converted to decimal for the database and likewise on a response should be converted back to the proper locale format.

### Screenshots

https://www.loom.com/share/3a4db91214d740f69371919214cae858

https://www.loom.com/share/436524c7dc5d49a9bb0890bf94804523

### Code snippets

N/A

### Additional context

It appears there is already a fix proposed in the design system: https://github.com/strapi/design-system/pull/945

**Comment by joshuaellis** [comment]
This should be solved with strapi/design-system#945
