### ISSUE TITLE
Not getting latest uploaded media file in afterUpdate hook

### ISSUE THREAD

**Issue by AvinashUtekar** [strapi/strapi#16262]
### Required System information

- Node.js version: 14.21.1.
- NPM version: npm@6.14.17
- Strapi version: 4.4.0
- Database: postgres
- Operating system: Windows 10
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When i am updating entry using REST API , i am sending formdata to upload image and in the lifecycle.js
i am populating all things in **breforeUpdate** to get latest uploaded image to that record in **afterUpdate** hook
but i am getting previous image in the result and not the latest one which i have updated.

### Steps to reproduce the behavior

1. Go to strapi dashboard and create collection
2. add media field with multiple option and also single option
3. create one record to collection add media files respect those fields from strapi admin panel
4. add lifecycle.js file in that collection folder under api folder
5. add code as given in the below Code snippets section
6. now update that record via Postman with formdata with media fields
7. you will get previous files which you uploaded in result of afterUpdate hook not the latest ones
8. same thing happening with multi-upload media fields

### Expected behavior

in result of afterUpdate we should get latest files not oldest one

### Screenshots

Pic 1: i am updating record with new media file
![image](https://user-images.githubusercontent.com/87367466/229079134-4a7a1f00-7891-4171-abf9-039e106f83be.png)

Pic 2: in the afterUpdate still i am getting file which is previously uploaded 
![image](https://user-images.githubusercontent.com/87367466/229079444-fdaf1a72-9290-46cb-9363-106780dc9c55.png)

### Code snippets

`    async beforeUpdate(event) {
        event.params.populate = true
    }
 `

`    async afterUpdate(event) {
        const { result, params } = event;
        console.log(result)
    }
`

**Comment by derrickmehaffy** [comment]
related to: https://github.com/strapi/strapi/issues/16258

**Comment by AvinashUtekar** [comment]
@derrickmehaffy can you tell me workaround for it , like i want to fetch latest attached file in afterCreate hook

**Comment by derrickmehaffy** [comment]
There isn't a workaround other than to refetch the data using entity service and populate the data you need.

**Comment by AvinashUtekar** [comment]
ok. got it
