### ISSUE TITLE
Translation keys missing in PT language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#1626]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/pt.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/pt.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

**Comment by Fausto95** [comment]
Hi there. 
I'll work on it this weekend!

**Comment by lauriejim** [comment]
Awesome @Fausto95 ! Waiting for your PR 👌

**Comment by lauriejim** [comment]
I close this issue because we are moving to Crowdin to manage translations.
We will update the contribution guide to add information to how contribute to translations.
