### ISSUE TITLE
Can't create a new documentation version using Strapi's Documentation Plugin

### ISSUE THREAD

**Issue by freitasfa-bahag** [strapi/strapi#16263]
## Bug report

I can't generate multiple versions of the documentation using the Documentation Plugin.

### Required System information

- Node.js version: 14.21.3
- NPM version: 6.14.18 
- Strapi version: 4.7
- Database: Postgres
- Operating system: Mac OS 
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When attempting to create a new version of the documentation by changing the `info.version` key, the plugin does not generate a new version. Instead, it always updates the current version (1.0.0). Additionally, the version number is only updated in the Swagger page and not in the Admin panel or the URL path, which still appears as http://localhost:1337/documentation/v1.0.0.

### Steps to reproduce the behavior

1. Change `version` key in `settings.json` file  from 1.0.0 to 1.1.0
2. Run the project `yarn develop`
3. Generate a new doc version on admin panel
4. Open the the Swagger documentation

### Expected behavior

On the documentation page, there should appear links to 2 versions of the docs: 1.0.0 and 1.1.0. Instead, it keeps showing just the 1.0.0 version. If it's not possible to handle multiple versions, then it should update the 1.0.0 version to 1.1.0. Finally, when I click on show documentation, the URL path to the docs should be `http://localhost:1337/documentation/v1.1.0`, but it keeps showing like `http://localhost:1337/documentation/v1.0.0`. However, the swagger page displays the doc version properly, as shown in the screenshot attached. 

### Screenshots

<img width="582" alt="image" src="https://user-images.githubusercontent.com/126701423/229088238-020718c7-097f-469b-8fef-103f617532f2.png">

![image](https://user-images.githubusercontent.com/126701423/229086925-09170926-4c44-411a-9878-69fcc445f68b.png)

![Screenshot 2023-03-30 at 18 45 57](https://user-images.githubusercontent.com/126701423/229080763-827910be-79fc-4578-980e-f6ad2d17c7f1.png)

**Comment by freitasfa-bahag** [comment]
I've jut found an [open PR](https://github.com/strapi/documentation/blob/83105de4000756f95d5d94d5b4d5cf5d987dc32b/docusaurus/docs/dev-docs/plugins/documentation.md) that is implementing a change into the Documentation docs. I tried the new suggested way to create doc versions using:

```
module.exports = {
  documentation: {
    enabled: true,
    config: {
      info: { version: "2.0.0" },
    },
  },
};
```

It worked as expected: It automatically create a new folder into `documentation/documentation` folder with the correct version. However, I'm still facing the following issues:
- When I click in any button to open a documentation version, it alway open the last one
- To access a previous doc version, I have to manually change the url
- What should I do with the `version` key in `settings.json` file? If I change the version, it will happen the previous problem I mentioned, where the 1.0.0 documentation is updated.

**Comment by markkaylor** [comment]
The settings.json file is not used anymore in the documentation plugin so you no longer need it. Any updates you were making to the settings.json can be made in the [plugins config](https://github.com/strapi/documentation/blob/83105de4000756f95d5d94d5b4d5cf5d987dc32b/docusaurus/docs/dev-docs/plugins/documentation.md#configuration).

The issue with the last generated documentation always opening is a bug I have reproduced and will work on.
