### ISSUE TITLE
Version 4.9 throws "self-signed certificate in certificate chain" error

### ISSUE THREAD

**Issue by andrejmoltok** [strapi/strapi#16269]
### Required System information

- Node.js version: 18.15
- NPM version: 9.6
- Strapi version: 4.9
- Database: mySQL 8.0.32
- Operating system: Win10Pro
- Is your project Javascript or Typescript: JS

### Describe the bug

When running `yarn develop` right after new installation, it throws an error regarding a database, meaning `self signed certificate in certificate chain`.

### Steps to reproduce the behavior

I dont't know how can it be reproduced, I just can't start Strapi, due to this error.

### Expected behavior

Strapi should run in dev mode.

### Screenshots

![strapi-error](https://user-images.githubusercontent.com/20362038/229230816-2e4fe72f-f13b-4e01-9087-7ca355aa3c97.png)

### Additional context

The `.env` file has all the correct login information for the database and SSL is set to `true`, if set to `false`, it throws a different error, to upgrade mySQL Client, but that's not relevant right now. I have all my database settings correct and yet Strapi won't start.

**Comment by derrickmehaffy** [comment]
Can you please try setting: `DATABASE_SSL_REJECT_UNAUTHORIZED` false?

The new default DB configuration checks if the nested DB vars exist else it uses the normal `DATABASE_SSL` var.

The issue you have isn't really a bug but instead you are either turning SSL on or off with what you've changed, the problem is not related to turning it off but disabling the strictness that the DB's SSL cert is valid.

I'm going to set this as closed since it's not a bug but a configuration issue, do feel free to comment though.

**Comment by andrejmoltok** [comment]
I have MySQL Workbench with the latest version of mysql 8.0.32 and I changed the seeting to false.
So my databse.js file for the mysql looks like this:
```
ssl: env.bool('DATABASE_SSL', false) && {
          key: env('DATABASE_SSL_KEY', undefined),
          cert: env('DATABASE_SSL_CERT', undefined),
          ca: env('DATABASE_SSL_CA', undefined),
          capath: env('DATABASE_SSL_CAPATH', undefined),
          cipher: env('DATABASE_SSL_CIPHER', undefined),
          rejectUnauthorized: env.bool(
            'DATABASE_SSL_REJECT_UNAUTHORIZED',
            false
          ),
        },
```

Now, I get a new error, that I should `upgrade my mySQL Client`.
![image](https://user-images.githubusercontent.com/20362038/229578043-2cc09bc8-7687-4dac-93cb-2f77080c26a9.png)

**Comment by robclancy** [comment]
I have tried to configure postgres with a cacert so much. Been over so many issues with so many different attempts at configuring it. The only thing that works is a full NODE env override with `NODE_TLS_REJECT_UNAUTHORIZED`. 

And lots of the issues are just ignored like this one.

**Comment by Sigmakib2** [comment]
I did `DATABASE_SSL=false` in the .env file and it worked

**Comment by Jack-98k** [comment]
What is the difference between `**DATABASE_SSL_REJECT_UNAUTHORIZED=true**`  and `**DATABASE_SSL_REJECT_UNAUTHORIZED=false**` ?

**Comment by derrickmehaffy** [comment]
> What is the difference between **DATABASE_SSL_REJECT_UNAUTHORIZED=true**  and **DATABASE_SSL_REJECT_UNAUTHORIZED=false** ? @derrickmehaffy 

First one won't allow self signed certs, second one does
