### ISSUE TITLE
Translation keys missing in RU language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#1627]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/ru.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/ru.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

**Comment by segush11** [comment]
Hi! Can I help you with this PR?

**Comment by lauriejim** [comment]
Hello @segush11 ! Yap, feel free to submit a PR with translations changes.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
I close this issue because we are moving to Crowdin to manage translations.
We will update the contribution guide to add information to how contribute to translations.
