### ISSUE TITLE
"Server wasn't able to start properly" after assigning component to another component. Can't start the server

### ISSUE THREAD

**Issue by da-kicks-87** [strapi/strapi#16275]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.5.0
- Strapi version: 4.9.0
- Database: mySQL
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Server won't restart after assign  a component into another component. Strapi crashes and I get this error message on the terminal:

debug: ⛔️ Server wasn't able to start properly.
[2023-04-02 10:07:31.759] error: create table `components_sections_one_column_centered_full_width_images_components` (`id` int unsigned not null auto_increment primary key, `entity_id` int unsigned null, `component_id` int unsigned null, `component_type` varchar(255) null, `field` varchar(255) null, `order` double unsigned null) - ER_WRONG_TABLE_NAME: Incorrect table name 'components_sections_one_column_centered_full_width_images_components'
Error: ER_WRONG_TABLE_NAME: Incorrect table name 'components_sections_one_column_centered_full_width_images_components'

### Steps to reproduce the behavior

1. Go to Strapi Dash Board. 
2. Create a component called "One Column Centered Full Width Image".  Put in a category "sections" 
3. Create a component called "Button". Put in a category called "general"
4. Add the component "Button" to the component "One Column Centered Full Width Image" as an attribute.
5. Save

### Expected behavior

I expect the settings to save and the server to restart.

**Comment by Marc-Roig** [comment]
In mysql table names length is limited to 64 characters if I recall correctly, your generated table name is 68.

This is an annoying behaviour that we do plan to fix and our DX squad has this on their radar.

We have another opened issue  https://github.com/strapi/strapi/issues/14000 so I will close this in favor of the other one.
