### ISSUE TITLE
Admin Crashes when user roles are accessed without create or update rights

### ISSUE THREAD

**Issue by goodhoko** [strapi/strapi#16276]
### Required System information

- Node.js version: 16.20.0
- Strapi version: 4.9.0
- Database: postgres
- Operating system: linux
- Is your project Javascript or Typescript: javascript

### Describe the bug

When the admin roles page (`/admin/settings/roles`) is accessed in the settings by an admin user that does not have `create` or `update` rights for roles, the admin crashes (the whole page goes blank) and the following error is logged into dev console (twice):

```
TypeError: can't access property "onClick", u[1] is undefined
    H admin-roles-list.d239aa8a.chunk.js:65
```
(stack trace truncated)

### Steps to reproduce the behavior

1. Give the `Editor` only the `read` right for admin roles:
    <img width="881" alt="image" src="https://user-images.githubusercontent.com/16712262/229381239-984b3506-c1f5-4d25-b7a5-f82378f38288.png">
3. Log in to the admin panel as an `Editor`
4. Go to `/admin/settings/roles` i.e. Settings => Administration Panel => roles
5. The page crashes

### Expected behavior

The roles are displayed in a read-only mode.

### Additional context

I'm setting this specific set of rights because I want Editors to be able to add other users but not to edit the roles. For creating and generally managing users they need to have the `read` right for roles as well, otherwise they can't eg. pick a role for a new user.

**Comment by simotae14** [comment]
Hello @goodhoko I replicated your error and I am working on a solution, I will let you know when it will be available, thanks

**Comment by simotae14** [comment]
hello @goodhoko the fix will be available in Strapi version 4.9.2, thanks

**Comment by goodhoko** [comment]
My please. Thanks for a swift resolution!

**Comment by simotae14** [comment]
You are welcome 😃
