### ISSUE TITLE
 About videos uploaded to strapi s3

### ISSUE THREAD

**Issue by omerisk1** [strapi/strapi#16272]
Hello 👋

I recently encountered a problem uploading video on aws s3. 

This is the problem, the video I uploaded to the strap goes to the s3 side, okay, but that video in the media library seems broken and cannot be selected. But there is no problem with the video. The video is working. It just looks broken and cannot be selected. When I enter a new entry, I have to upload that video again.

I don't know if the title of this problem has been opened before, but I would appreciate it if you could help with this.

Thanks
Keep coding

**Comment by Marc-Roig** [comment]
Hello, we will be working on this and give some feedback as soon as we find why this is happening.

Are you isng the `baseUrl`config? This issue seems similar to https://github.com/strapi/strapi/issues/16247

**Comment by omerisk1** [comment]
i guess it's not the same problem to #16247

I don't have any problem in baseUrl. It comes from my own bucket in pictures and videos. Everything works fine on the clientside.

My problem is exactly in strapi media library tab. When I enter the media library, there is no problem with the images. however, there is no background image in the uploaded videos and it cannot be selected, so I can neither delete it nor select and upload a video uploaded to another component again. This is actually my problem.

Thanks.

**Comment by Marc-Roig** [comment]
Alright, I am trying to reproduce it and would help to know which version you are using.

Could you edit the issue descriptiong and  use the bug description template https://github.com/strapi/strapi/issues/new?assignees=&labels=&template=BUG_REPORT.md ? That would be very useful.

I am trying to upload an mp4 video using the s3 provider without any problem,you can not see a preview, but I can select the video and even reproduce it.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/20578351/229543392-d54b47d4-83e3-4b49-ac2b-499e89daa2e0.png">
<img width="759" alt="image" src="https://user-images.githubusercontent.com/20578351/229543419-dd2bc2f4-83c3-4685-a566-57de2fbc5025.png">

**Comment by Marc-Roig** [comment]
Could you also provide a video file as an example that is giving you this issue?

**Comment by omerisk1** [comment]
Yes, we are in the same place as you right now.

I've noticed now, the selectability feature needs to be clicked at the top of the tick box. I didn't realize that. Is it also on your side ?

Shouldn't the videos have a preview image like in the detail section?

Also, the video download button in the detail section does not work for me either.

**Comment by Marc-Roig** [comment]
you are right,  the preview image should be displayed and the download button seems to not be working. 

In my case, it seemed it was a Cors error
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20578351/229565631-fff0572e-c7dd-42ec-83ac-4e07eb61b7f7.png">

Changing the CORS config in my s3 bucket fixes the issue:
```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [],
        "MaxAgeSeconds": 3000
    }
]
```

This is a generic CORS configuration just for testing purposes, you should adapt yours to allow headers from your own application origins.

Do you have access to your cors configuration?

**Comment by omerisk1** [comment]
Thank you for the help. 

I don't see any problem on my side right now..

**Comment by Marc-Roig** [comment]
Glad I could help with this :) ! I am closing the issue, if there is anything else we can reopen it.
