### ISSUE TITLE
Cannot read properties of undefined (reading 'forEach') in register-routers.js file

### ISSUE THREAD

**Issue by nhatnguyen233** [strapi/strapi#16281]
## Bug report
[2023-04-03 16:30:40.565] debug: ⛔️ Server wasn't able to start properly.
[2023-04-03 16:30:40.566] error: Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')
    at /home/nhat/Documents/Projects/node_modules/@strapi/strapi/lib/services/server/register-routes.js:99:21
    at /home/nhat/Documents/Projects/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/nhat/Documents/Projects/node_modules/lodash/lodash.js:3032:24)
    
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.5.5
- Database: mysql
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

/**
 * Register api routes
 * @param {import('../../').Strapi} strapi
 */
const registerAPIRoutes = (strapi) => {
  for (const apiName of Object.keys(strapi.api)) {
    const api = strapi.api[apiName];
    const generateRouteScope = createRouteScopeGenerator(`api::${apiName}`);

    _.forEach(api.routes, (router) => {
      // TODO: remove once auth setup
      // pass meta down to compose endpoint
      router.type = 'content-api';
      router.routes.forEach((route) => {
        generateRouteScope(route);
        route.info = { apiName };
      });

      return strapi.server.routes(router);
    });
  }
};
Above is the coding of this issue, I'm trying to log `Object.keys(strapi.api)` and this contains the key is `cvp-challenge  ` but my api.routes value is 
api.routes = {
  'cvp-challenge-d': {},
  'cvp-challenge': { prefix: [Getter], routes: [Getter] }
}
i don't know `cvp-challenge-d` key come from where, that's why can't reading forEach. Pls help me in this problem. Thanks.
### Steps to reproduce the behavior

1. Go to 'node_modules/@strapi/strapi/lib/services/server/register-routes.js'
2. Console.log some value of this function '....'

### Screenshots

![image](https://user-images.githubusercontent.com/37479355/229477446-e13294ed-cd39-4f24-af70-47b928716bf1.png)
![image](https://user-images.githubusercontent.com/37479355/229477538-87918f66-c123-41e7-a1cf-3395b5a5c6d4.png)

**Comment by NathanKun** [comment]
I have the same issue, after some debug I found out that the .d.ts file of my route is included by the api loader:
@strapi/strapi/lib/core/loaders/apis.js in loadDir() method.
It excludes only .map file but not .d.ts file.

So I have to add "declaration": false and "declarationMap": false to the tsconfig.json in the compilerOptions object, to not build any .d.ts file.

Mine strapi project is in a monorepo, the tsconfig.json file extends a base tsconfig which has declaration & declarationMap set to true. On a strapi project created by npx create-strapi-app it may work fine.
