### ISSUE TITLE
strapi import failed as 'violates foreign key constraint' error

### ISSUE THREAD

**Issue by waterzhong2023** [strapi/strapi#16288]
### Required System information

- Node.js version: v16.18.1
- NPM version:
- Strapi version:  v4.7.1
- Database:  postgres in AWS rds
- Operating system:  node:16-alpine
- Is your project Javascript or Typescript:  js

### Describe the bug

**strapi import failed as 'violates foreign key constraint' error**

[2023-04-04 09:14:59.151] [31merror[39m: [ERROR] insert into "xxxx" ("xxxx", "xxxx") values ($1, $2) - insert or update on table "xxxxx" violates foreign key constraint "xxxxxxxx"
Import process failed.
error Command failed with exit code 1.

### Steps to reproduce the behavior

**the commands I ran:**
yarn strapi export --file /app/my-strapi-export  --no-encrypt
yarn strapi import --file /app/my-strapi-export.tar.gz  --force

### Expected behavior
Can import the full data to postgres RDS database.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
merged into https://github.com/strapi/strapi/issues/16363
