### ISSUE TITLE
Error in Strapi Transfer: "Foreign Key Constraint Failed" while using relation to same collection in component

### ISSUE THREAD

**Issue by ecosse3** [strapi/strapi#16308]
### Required System information

- Node.js version: v16.19.1
- NPM version: 8.19.3
- Strapi version: 4.9.0
- Database: mysql
- Operating system: latest macOS
- Is your project Javascript or Typescript: JS

### Describe the bug

When attempting to transfer data from a remote environment (Strapi on AWS) using the Strapi Transfer feature I get the following error:

```bash
error: [ERROR] insert into `components_blocks_similar_offers_job_offers_links` (`offer_id`, `offer_order`, `similar_offers_id`) values (28, NULL, 3) - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`mydatabase`.`components_blocks_similar_offers_job_offers_links`, CONSTRAINT `components_blocks_similar_offers_job_offers_links_fk` FOREIGN KEY (`similar_offers_id`) REFERENCES `components_bloc)
Transfer process failed.
```

### Steps to reproduce the behavior

Use `strapi transfer --from` to transfer data from remote instance (AWS) to local environment (localhost) when one of the components has a relational field to itself. It will fail.

### Expected behavior

It should correctly transfer data. Maybe it should skip insertion to those fields which have a relation to itself? Or there is a better way.

### Code snippets

Field used in component:

```json
"jobOffers": {
  "type": "relation",
  "relation": "oneToMany",
  "target": "api::offer.offer"
},
```

### Additional context

I guess it happens because while I am creating a new content in "Job Offers" collection, the dynamic block which I am trying to use have a `oneToMany` relation with itself. Probably the content to which it's trying to add a relation doesn't exists yet during transfer.

**Comment by derrickmehaffy** [comment]
merged into: https://github.com/strapi/strapi/issues/16363
