### ISSUE TITLE
S3 private ACL returns wrong media url when frontend is querying the api

### ISSUE THREAD

**Issue by ArneOttenVW** [strapi/strapi#16316]
### Required System information

- Node.js version: 16.19.1
- NPM version: 8.19.3
- Strapi version: 4.9.0
- Database: AWS Aurora (MySQL)
- Operating system: Linux (node:16 docker image, probably Alpine)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

We are hosting a strapi backend on AWS ECS and to not loose our media after a redeployment, we use `upload-aws-s3` provider with a private S3 bucket. The plugin works fine on the backend side. We can use the Media-Library to upload/delete/replace images, thumbnails load fine etc. and strapi always generates nice pre-signed urls in the background.

It's another story when our angular frontend tries to load those images though. Angular sends a request to for example here:

`https://example.com/api/header?populate[hero_list][populate]=image`

to get the image url. This url should be a pre-signed url but it isn't. Instead, it's a regular S3 link as if the bucket was public which then results in a 403 error. 

Response:
```
[...]
"ext": ".svg",
"mime": "image/svg+xml",
"size": 2.47,
"url": "https://bucketname-eu-west-1.s3.eu-west-1.amazonaws.com/Frame_1261154589_b7d399ddfa.svg", <-- this is not a pre-signed url
"previewUrl": null,
"provider": "aws-s3",
[...]
```

### Steps to reproduce the behavior

1. Set up a private S3 bucket and configure the `upload-aws-s3` provider
2. Upload some media via the Media Library
3. Use the Content-Type Builder to create some content that uses the image
4. Use the api to query the content and get the image url
5. It should throw a 403 error when trying to access the image url

### Expected behavior

The api should return a pre-signed url.

### Code snippets

plugin.ts
```typescript
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        s3Options: {
          accessKeyId: '',
          secretAccessKey: '',
          region: 'eu-west-1',
          params: {
            ACL: 'private',
            Bucket: env('AWS_BUCKET')
          }
        }
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {}
      }
    }
  }
});
```

**Comment by Marc-Roig** [comment]
We released the feature knowing this might be confusing for some people, but the api does not presign URLs. We are on the process of adding a flag to allow having them presigned in the API, but we started like this for security reasons. 

Some users serve images on public endpoints, so by default we didn't want to expose signed private URLs. 

We had a conversation in this [discord thread ](https://discord.com/channels/811989166782021633/1090678982741069925/1091087442662133903) . I will report there when we have the PR ready for this :)
