### ISSUE TITLE
Collection Type relation returning as null

### ISSUE THREAD

**Issue by thamudi** [strapi/strapi#16311]
### Required System information

- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: 4.6
- Database:postgresql
- Operating system: Ubuntu 18.04.6 LTS

- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have two collection types: comics and archives. Archives have oneToMany relation with the comics collection. 

The bug occurs only during production when I am creating new comic and assigning an archive to it. What happens is that some of the data responses for the comic will randomly have an archive data set to null, even though it is assigned to an archive and it is shown in the dashboard.

The request I am sending is the following:
```
https://strapi-url/api/comics?populate=*&locale=all
```

I was able to mitigate the situation by unpublishing the culprit comics, after doing some digging in the response to find which one, and re-publishing it again.

I will be sharing the schemas for both the Archive and the Comic in case it provides any insights.

### Code snippets

Archive Schema:
```json
{
  "kind": "collectionType",
  "collectionName": "archives",
  "info": {
    "singularName": "archive",
    "pluralName": "archives",
    "displayName": "archive",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string",
      "pluginOptions": {}
    },
    "slug": {
      "type": "uid"
    },
    "comics": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::comic.comic",
      "mappedBy": "archive"
    },
    "thumbnail": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "pluginOptions": {}
    }
  }
}

```

Comics Schema 
```json
{
  "kind": "collectionType",
  "collectionName": "comics",
  "info": {
    "singularName": "comic",
    "pluralName": "comics",
    "displayName": "comic",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "title": {
      "type": "string",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
    "comic": {
      "type": "media",
      "multiple": true,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    },
    "keywords": {
      "type": "string",
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    },
    "archive": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::archive.archive",
      "inversedBy": "comics"
    },
    "releaseDate": {
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      },
      "type": "date"
    },
    "authorsNote": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "text"
    },
    "thumbnail": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ],
      "pluginOptions": {
        "i18n": {
          "localized": false
        }
      }
    }
  }
}
```

### Additional Context
I don't know if this will help. But I have this project deployed on digital ocean Apps. I am using a pro plan with 1 GB of RAM and a Dev Database for testing.

**Comment by Marc-Roig** [comment]
Hello, if I understand correctly, the relations are not appearing in your API but they do appear in the admin dashboard ?

If so, maybe it seems a problem of entities not being published, if you list `https://strapi-url/api/comics?populate=*&locale=all` only published entities AND published relations will appear. In case you want to list also the drafts you can do `https://strapi-url/api/comics?populate=*&locale=all&publicationState=preview`

**Comment by thamudi** [comment]
> Hello, if I understand correctly, the relations are not appearing in your API but they do appear in the admin dashboard ?
> 
> If so, maybe it seems a problem of entities not being published, if you list `https://strapi-url/api/comics?populate=*&locale=all` only published entities AND published relations will appear. In case you want to list also the drafts you can do `https://strapi-url/api/comics?populate=*&locale=all&publicationState=preview`

> Lpi8

@Marc-Roig

They are all published.
Like I mentioned this bug seems to resolve itself if I unpublish the comic and then republish.

**Comment by Boegie19** [comment]
@thamudi Can you replicate the issue in any way or can you give us a bugged project so that we can confirm the bug and figure out what is causing it?

**Comment by thamudi** [comment]
> @thamudi Can you replicate the issue in any way or can you give us a bugged project so that we can confirm the bug and figure out what is causing it?

I can't give away the project since its for a client and it would be a breach of contract.
But I can confirm it is not a bugged code since It is stock strapi 4.6 like I mentioned. 
I can provide the list of dependencies and the config I have for the middleware and plugins.

package.json dependencies
```json
 "dependencies": {
    "@strapi/plugin-i18n": "4.5.6",
    "@strapi/plugin-seo": "^1.7.7",
    "@strapi/plugin-users-permissions": "^4.8.2",
    "@strapi/strapi": "^4.6.1",
    "better-sqlite3": "^7.4.6",
    "pg": "^8.10.0",
    "strapi-plugin-populate-deep": "^2.0.0",
    "strapi-provider-upload-do": "^3.6.8"
  },
``` 
plugins.js
```javascript
module. Exports = ({ env }) => ({
  seo: {
    enabled: true,
  },
  upload: {
    config: {
      provider: "strapi-provider-upload-do",
      providerOptions: {
        key: process.env.DO_SPACE_ACCESS_KEY,
        secret: process.env.DO_SPACE_SECRET_KEY,
        endpoint: process.env.DO_SPACE_ENDPOINT,
        space: process.env.DO_SPACE_BUCKET,
        directory: "media", // optional
      },
    },
  },
});
```

middleware.js
```javascript
module. Exports = [
  'strapi::errors',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", `${process.env.DO_SPACE_CDN}`],
          "media-src": ["'self'", "data:", "blob:", `${process.env.DO_SPACE_CDN}`],
          upgradeInsecureRequests: null,
        }
      }
    }
  }
];
```
