### ISSUE TITLE
[ISSUE] RegeneratorRuntime error to access admin console.

### ISSUE THREAD

**Issue by rafaeleduardoteixeira** [strapi/strapi#16312]
### Required System information

- Node.js version: v14.20.1
- Strapi version: 4.9
- Database: Mysql
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I created a new project strapi, I installed the latest version, and try to publish on AWS. After that the success on pipeline, the server strapi is running ok (I can access the api), however, I can't access the admin console. When I try I got an error:

regeneratorRuntime is not defined

### Steps to reproduce the behavior

1. Go to strapi admin console.
2. See error on console

### Expected behavior

I can open the admin login console and create documents.

### Screenshots

![Screenshot 2023-04-05 at 17 55 56](https://user-images.githubusercontent.com/63987545/230209540-4d22d9c2-a7c8-41e0-bdba-86352e089e9f.png)

![Screenshot 2023-04-05 at 17 56 11](https://user-images.githubusercontent.com/63987545/230209578-93eacb4b-fb63-46aa-8ec8-9dff7042bdc1.png)

**Comment by Eventyret** [comment]
Thank you for your report @rafaeleduardoteixeira 🙌 
Could you try a thing for me before I start investigating it?
First, please make sure the version is correct.
`4.9` should be `4.9.0` 
After that, please make sure you delete `build` `.cache` and `package-lock.json` and or `yarn.lock`
Then do `yarn install` or `npm install` to install the latest version.
You can then try to rebuild it with `npm run develop` or `yarn develop` to rebuild the admin UI.
Once done, you can do a redeployment. If all this fails, How are you deploying and are you using docker or just a normal deployment?

**Comment by rafaeleduardoteixeira** [comment]
Hi @Eventyret thank you for your answer.

I'm using 4.9.0 version.
![Screenshot 2023-04-11 at 08 25 39](https://user-images.githubusercontent.com/63987545/231147366-7154b7b6-8dd7-4bd3-bfce-51fe48534817.png)

The commands that you related there is on my docker file:
![Screenshot 2023-04-11 at 08 26 17](https://user-images.githubusercontent.com/63987545/231147541-e023c3e9-cd08-471d-8cee-f97d89ed8bad.png)

I tried a lot of things, however, keep with the same error, I'm facing this error only on ECS docker, on my computer I can't reproduce, but, I runed the same commands locally :(

**Comment by Eventyret** [comment]
How does your server.js look like?

**Comment by rafaeleduardoteixeira** [comment]
Server file:

![Screenshot 2023-04-11 at 08 56 47](https://user-images.githubusercontent.com/63987545/231155562-fcb91293-c0cb-4dda-8b28-45d4185bcbd7.png)

**Comment by Eventyret** [comment]
So could you test a tool that was created by our community (please make sure you BACKUP your  `docker-compose.yaml` and `Dockerfile` **BEFORE** executing the command.
`npx @strapi-community/dockerize` this is a battle proven Dockerfile also has a docker support I wrote a while ago.
Just compare the output of this dockerfile and your own.
Then try and see if it works and let me know please 🙏 

For reference here is the tool
https://github.com/strapi-community/strapi-tool-dockerize
