### ISSUE TITLE
Couldn't filter if media field is null

### ISSUE THREAD

**Issue by multijump** [strapi/strapi#16322]
### Required System information

- Node.js version: 16.19.1
- NPM version: 8.19.3
- Strapi version: 4.9.0
- Database: postgresql 14
- Operating system: MacOS Ventura 13.2.1
- Is your project Javascript or Typescript: javascript

### Steps to reproduce the behavior

It would be great to filter if media field is null or not.

like filters[photos][$notNull]=true

**Comment by Boegie19** [comment]
duplicate of https://github.com/strapi/strapi/issues/12225
