### ISSUE TITLE
Building strapi 4.9.0 - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#16321]
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.9.0
- Database: Postgresql
- Operating system: Ubuntu
- Is your project Javascript or Typescript: typescript

### Describe the bug

I get the following error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Debugging it loosk like it comes from the graphql plugin because it does not contain the packagePath

### Steps to reproduce the behavior

1. Upgrade to strapi 4.9.0
2. run `npm run build`
3. get error

### Expected behavior

Strapi builds correctly 

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

```javascript
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1098:7)
    at /home/pablo/github/ciudadela/ciudadela/node_modules/@strapi/admin/utils/create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (/home/pablo/github/ciudadela/ciudadela/node_modules/@strapi/admin/utils/create-cache-dir.js:80:6)
    at async Object.build (/home/pablo/github/ciudadela/ciudadela/node_modules/@strapi/admin/index.js:27:3)
    at async module.exports (/home/pablo/github/ciudadela/ciudadela/node_modules/@strapi/strapi/lib/commands/build.js:12:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by csharpee** [comment]
I have the same exact error when upgrading from 4.5.4 to  4.9.0.

**Comment by csharpee** [comment]
I am going to see if it is the plugin: ckeditor. I upgraded this plugin and it may be the reason according to this: https://github.com/strapi/strapi/issues/15592. Supposedly, the configuration has changed since an older version.

**Comment by csharpee** [comment]
Yup, that was the issue; woowi :sweat_smile:  - that was a big config change @pcriadoperez .

![image](https://user-images.githubusercontent.com/18726788/230701165-07ceff18-a6cb-47b0-8041-9cad4a591028.png)

**Comment by pcriadoperez** [comment]
Glad it worked for you! Unfortunately in my case I'm not using creditor, so I think it must be something else.

**Comment by csharpee** [comment]
@pcriadoperez What version of Strapi are you upgrading from? I would assume it is a 3rd party plugin puzzle or maybe a migration issue. I upgraded from 4.54 to 4.9.0.

https://docs.strapi.io/dev-docs/migration-guides

**Comment by sparrow-chik-chrk** [comment]
This might help someone. I encountered an issue where an empty `yarn.lock` folder was being created during development builds, even though I'm using npm. Deleting this folder resolved the error for me.

**Comment by Uriyo** [comment]
I also faced with similar kind of bug , When I am trying to run the develop script 
![image](https://github.com/strapi/strapi/assets/87664057/0d56b6e6-f7b0-4add-86bb-f5b62154913c)

I am geeting this issue in this version
"@strapi/strapi": "5.0.0-beta.17",
    "@strapi/plugin-users-permissions": "5.0.0-beta.17",
    "@strapi/plugin-cloud": "5.0.0-beta.17",

**Comment by derrickmehaffy** [comment]
Locking this, there is a new issue for Strapi 5 please use that one.
