### ISSUE TITLE
Private fields still show in inputs and filters inputs

### ISSUE THREAD

**Issue by gfpacheco** [strapi/strapi#16325]
### Required System information

- Node.js version:v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.8.2
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: TS

### Describe the bug

Following up on #16169 and #16172

Since 4.8.1 private fields can't be filtered by anymore, but they still show up in GraphQL's Inputs and FiltersInputs.

### Steps to reproduce the behavior

1. Add a private field
2. See that they still show in GraphQL's schema (not on the entity, but on the input and filters input)

### Expected behavior

Private fields shouldn't show up on the schema at all.

**Comment by Eventyret** [comment]
Hey there! 👋

Thanks for reaching out and letting us know about the issue you're facing. No worries, we're here to help you stay on the cutting edge of Strapi-nology! 😎

First things first, let's get your Strapi project all "up-to-date and great!" To do that, please upgrade to the latest version. 🆙 You'll be "Strapi-ppreciating" the newest features 🌟 and all the bug-squashing goodness 🐛🔨 that comes with it!

Feeling a bit lost on how to upgrade? Don't sweat it! 🥵 We've got your back, like a well-fitted Strapi backpack 🎒! Just head on over to our 📚 [Migration Documentation](https://docs.strapi.io/dev-docs/update-version) 📚. Our migration guides will walk you through the process, step by step, making sure you're all set with the freshest Strapi experience! 💪📈🔝

📺 If you prefer video guides, check out this [YouTube tutorial]( https://www.youtube.com/watch?v=PtVH6u64AYg ) 📺.  Get your popcorn ready 🍿 and enjoy the upgrade show! 
_But a little note 📝: The video doesn't cover migrations, so be sure to check the guides if you're unsure or need more details._

Once you've upgraded, give your project a whirl 🌪️ and let us know if the issue still "Strapi-zzles" you. We'll be more than happy to jump in and help you sort it out 🕵️‍♂️🔧. But remember, upgrading is the "key" 🔑 to unlock our full support!

Thanks for helping us make Strapi "Strap-tacular"! 👍 🥳

**Comment by derrickmehaffy** [comment]
Reproducible on v4.9.0

![image](https://user-images.githubusercontent.com/8593673/231258385-b4e7e821-d058-44c0-b771-97143c335253.png)

**Comment by derrickmehaffy** [comment]
Reproducible on v4.9.0

![image](https://user-images.githubusercontent.com/8593673/231258385-b4e7e821-d058-44c0-b771-97143c335253.png)
