### ISSUE TITLE
strapi admin panel does not show relation field in sidebar after version update

### ISSUE THREAD

**Issue by javadbat** [strapi/strapi#16330]
### Required System information

- Node.js version: 18.12.1
- NPM version:9.3.1
- Strapi version:4.9.0
- Database:postgres
- Operating system:windows&linux
- Is your project Javascript or Typescript: javascript

### Describe the bug

relation field exists in the content-type builder & data but does not show in the data entry panel
as you see my article data type has a relation with the user and tag data type
![image](https://user-images.githubusercontent.com/11534875/230681663-a87252a1-c824-43ba-9cfc-4a2d6acb5dc1.png)

![Screenshot 2023-04-08 020115](https://user-images.githubusercontent.com/11534875/230681575-b11823a3-3314-4c24-bece-35ff68ad9bc6.png)
but when I enter the data entry form it does not appear in the right-side panel like before the update
![image](https://user-images.githubusercontent.com/11534875/230681925-20fff6f3-d30d-44b0-8d70-cede5a63779b.png)
before update to 4.7 this fields are shown here in sidebar but now they are hidden.
i have to mention that old data still has the value and API work perfectly for my old articles but panel does not show the relations here  so I cant enter new data

### Steps to reproduce the behavior

1. Go to new data entry
2. there is no relation type field in there

### Expected behavior

show the fields in admin panel

### Screenshots

I put theme in description

**Comment by Boegie19** [comment]
Closed since https://github.com/strapi/strapi/releases/tag/v4.5.0 this was put removed from the side bar and put into the main view

**Comment by javadbat** [comment]
![image](https://user-images.githubusercontent.com/11534875/230738223-cf8e75bd-85e6-42ff-a46b-a5cd794d2f10.png)
there is no tags or Author field in main view

**Comment by javadbat** [comment]
sorry I just fix it by going to configure view and adding this fields at the end of the view

**Comment by SetiZ** [comment]
oh I just had the same after updating an old strapi and I got so stressed about loosing all the relations!!
wow so weird I lost all the relations on the view
