### ISSUE TITLE
UID placeholder not meeting naming requirements

### ISSUE THREAD

**Issue by imCorfitz** [strapi/strapi#16349]
## Bug report

UID Field component in Content builder in admin shows field naming examples that won't be possible.

### Required System information

- Node.js version: 18.15.0
- NPM version: 9.5.0
- Strapi version: 4.9.0
- Database: PostgreSQL
- Operating system: Mac OS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When using the admin interface creating an UID field in this example, the placeholder gives an example field name: "SEO URL" which contradicts the message saying "no spaces allowed". And in fact doesn't pass the regex validating the input name.

### Steps to reproduce the behavior

1. Go to Content builder
2. Click on add field > UID
3. See error

### Expected behavior

The examples in the input field should likely reflect what is actually possible: `e.g. slug, seoUrl, canonicalUrl`.

### Screenshots

<img width="397" alt="Screenshot 2023-04-10 at 14 33 06" src="https://user-images.githubusercontent.com/52371939/231366185-a06d4c47-c829-4d79-99d9-ae08f1bf236c.png">

### Priority

🔻 Bottom of the drawer. Merely an observation but nothing that breaks anything.

**Comment by simotae14** [comment]
Close the issue because it is now fixed
