### ISSUE TITLE
Modal does not close

### ISSUE THREAD

**Issue by LuisRodriguezLD** [strapi/strapi#16347]
### Required System information

- Node.js version: v18
- NPM version: 9.5.0
- Strapi version: 4.9.0
- Database: SQLite
- Operating system: MacOS Ventura
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When you configure the view of a entity you are usually allowed to rename the columns but when you click on `Finish` the modal stays visible. This create the illusion that it wasn't saved properly but if you click on the `x` you can see it works fine. It's just the modal that is not closing

### Steps to reproduce the behavior

1. Go to any entity, eg `users`
2. Click on the cog to configure the view
3. Try to edit a column's label
4. Click on Finish
5. Modal stays visible

### Expected behavior

Modal should close when you click on finish

### Screenshots
![Screenshot 2023-04-11 at 1 39 40 PM](https://user-images.githubusercontent.com/16706463/231259220-96403c4f-b159-40fe-89cb-bc30e6a9aa7d.png)

### Code snippets

N/A

### Additional context

If this is truly a bug, I'll be happy to create a PR fixing it.

**Comment by LuisRodriguezLD** [comment]
@Eventyret apologies if my ticket wasn't clear enough.

It works fine while editing the view of an entry.
The problem is when you are editing the view of an **entity**.

I've cleared cache multiple times and the problem persists.
This issue also happens on new strapi projects created using the CLI.


Here's a video better illustrating the situation.

https://user-images.githubusercontent.com/16706463/231515063-620e1565-6844-424a-87c3-d24272b0a11a.mov

**Comment by Eventyret** [comment]
Thank you for the video @LuisRodriguezLD  I was able to reproduce it and flagged it as this.
As you said, if you wanted to create a PR to fix this, feel free to do so feel free to have a read at our [CONTRIBUTING 📃](https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md) doc
