### ISSUE TITLE
Optional components with a required field should not be added automatically to a collection after save

### ISSUE THREAD

**Issue by webholics** [strapi/strapi#16350]
### Required System information

- Node.js version: 16.19.0
- NPM version: yarn 1.22.11
- Strapi version: 4.8.2
- Database: PostgreSQL
- Operating system: MacOS 13.2.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Optional components with a required field should not be added automatically to a collection after save.
Saving a collection is now not consistent. Because it validates on the first save but not on the second.

### Steps to reproduce the behavior

I have a Collection Type “Article” which has a field typed as a Component “Author”. This Author field is an optional field. However, the Component Author defines a required field “name”. Strapi by default adds an Author with empty values after the first save. The second save will fail because the required field is empty.

This is another user which has found the same issue:
https://forum.strapi.io/t/ambiguous-behaviour-optional-component-with-a-required-field/26955

### Expected behavior

Optional components stay empty after save.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

There was a change in strapi lately which introduced this bug. Because the behavior before was that an optional component stays empty after save. I could not find anything mentioning this breaking change in the changelogs. So I assume this behavior was not introduced by intention.

**Comment by joshuaellis** [comment]
Have you tried updating to the latest version of Strapi? I think I resolved this issue in `4.9.0`.

**Comment by derrickmehaffy** [comment]
This is fixed in v4.9.0 closing
