### ISSUE TITLE
Query for one-way-relation-fields where value is null returns 500 error

### ISSUE THREAD

**Issue by goras** [strapi/strapi#1636]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.1.0
- **Strapi version**: 3.0.0-alpha.12.7
- **Database**: Mongo v3.6.6
- **Operating system**: macOs, Ubuntu 18.04

**What is the current behavior?**
A fetch querying a one-way-relation-field for a null value returns a 500-error

For example ``http://localhost:1337/page?parent=null`` returns :

```
{
	CastError: Cast to ObjectId failed for value "null" at path "parent" for model "Page"
	...
}
```

**Steps to reproduce the problem**
- Add a one-way-relation-field to any content-type.
- Try to fetch any entries of that content-type where the one-way-relation-field is null

**What is the expected behavior?**
To get a list of entries where the value of the selected field is null

**Comment by lauriejim** [comment]
Hello @goras thank you to report this issue.
Actually filters on relation is not fully handled. You can search on existing parent but not on null.
Will have to check if this PR https://github.com/strapi/strapi/pull/1467 handle your usecase.

**Comment by lauriejim** [comment]
Is the same as https://github.com/strapi/strapi/issues/1292

**Comment by sseypt** [comment]
Hi.

I stumbled across the same problem.
Is this being considered in https://portal.productboard.com/strapi/c/38-filters-on-relational-attributes?

I like to avoid orphan contents and since there is no cascade delete I don't like the options I'm left with very much:
- iterate over all
- negative filter with all the `<relation>_nin=`
- to trust that all relations will always be deleted first

Cheers,
Steve

**Comment by derrickmehaffy** [comment]
@sseypt it was not added to that as that filter on relation attributes is already done (and in v26/v26.1)

Bit be worthy of a new feature request

**Comment by sseypt** [comment]
@derrickmehaffy I must have been blind 🙈🤣

**Comment by derrickmehaffy** [comment]
It's in the version patch notes :wink: Tis okay though :stuck_out_tongue:

**Comment by sseypt** [comment]
There's not much to say about cascade delete I guess https://github.com/strapi/strapi/issues/3193
