### ISSUE TITLE
blank page on /admin/settings/roles

### ISSUE THREAD

**Issue by namastexlabs** [strapi/strapi#16369]
### Required System information

- Node.js version: NODE LTS 14 (but also happens on node15 present on my remote heroku instance, with the same problem)
- NPM version: 6.4.18
- Strapi version: 4.9.1 (started on 4.9.0)
- Database: postgres
- Operating system: windows and heroku
- Is your project Javascript or Typescript: javascript

### Describe the bug
i get a blank page when accesing /admin/settings/role, in both my local and remote instance

### Steps to reproduce the behavior

1. Go to '/admin/settings/roles' 
2. See error

### Expected behavior
the page will load, it doesnt.
### Screenshots

![image_2023-04-12_221324976](https://user-images.githubusercontent.com/116504299/231620093-730da2ec-b21b-4a36-a448-45b3f6c326a8.png)

### Code snippets

i havent done anything to the original code, other than adding a few content type builder.

### Additional context
console.log

/admin/telemetry-properties:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.82cc80da.js:879 TypeError: (0 , h.default) is not a function
    at de (admin-roles-list.2110724f.chunk.js:1:2245)
    at me (admin-roles-list.2110724f.chunk.js:2:1309)
    at Nc (main.82cc80da.js:877:54223)
    at Mn (main.82cc80da.js:881:9048)
    at rc (main.82cc80da.js:881:985)
    at du (main.82cc80da.js:881:913)
    at ja (main.82cc80da.js:881:767)
    at Md (main.82cc80da.js:879:10914)
    at main.82cc80da.js:877:39163
    at b.unstable_runWithPriority (main.82cc80da.js:909:3969)
ha @ main.82cc80da.js:879
C.callback @ main.82cc80da.js:879
gd @ main.82cc80da.js:877
Yd @ main.82cc80da.js:879
Yc @ main.82cc80da.js:881
b.unstable_runWithPriority @ main.82cc80da.js:909
Ra @ main.82cc80da.js:877
ls @ main.82cc80da.js:881
Md @ main.82cc80da.js:879
(anonymous) @ main.82cc80da.js:877
b.unstable_runWithPriority @ main.82cc80da.js:909
Ra @ main.82cc80da.js:877
Qi @ main.82cc80da.js:877
ko @ main.82cc80da.js:877
qs @ main.82cc80da.js:879
Zu @ main.82cc80da.js:877
(anonymous) @ main.82cc80da.js:62
await in (anonymous) (async)
(anonymous) @ main.82cc80da.js:62
Xc @ main.82cc80da.js:881
b.unstable_runWithPriority @ main.82cc80da.js:909
Ra @ main.82cc80da.js:877
pa @ main.82cc80da.js:881
(anonymous) @ main.82cc80da.js:881
X @ main.82cc80da.js:909
U.port1.onmessage @ main.82cc80da.js:909
main.82cc80da.js:62 TypeError: (0 , h.default) is not a function
    at de (admin-roles-list.2110724f.chunk.js:1:2245)
    at me (admin-roles-list.2110724f.chunk.js:2:1309)
    at Nc (main.82cc80da.js:877:54223)
    at Mn (main.82cc80da.js:881:9048)
    at rc (main.82cc80da.js:881:985)
    at du (main.82cc80da.js:881:913)
    at ja (main.82cc80da.js:881:767)
    at Md (main.82cc80da.js:879:10914)
    at main.82cc80da.js:877:39163
    at b.unstable_runWithPriority (main.82cc80da.js:909:3969)
(anonymous) @ main.82cc80da.js:62
await in (anonymous) (async)
(anonymous) @ main.82cc80da.js:62
Xc @ main.82cc80da.js:881
b.unstable_runWithPriority @ main.82cc80da.js:909
Ra @ main.82cc80da.js:877
pa @ main.82cc80da.js:881
(anonymous) @ main.82cc80da.js:881
X @ main.82cc80da.js:909
U.port1.onmessage @ main.82cc80da.js:909

**Comment by Eventyret** [comment]
Thank you for reporting your issue @namastexlabs 
Could you please try the following?
Upgrade to node 16 and npm 7+ (We don't support 15, only the LTS numbers, so 14,16,18 etc.) 💁‍♂️

Once done, please delete `node_modules`,  `build`, `cache` folders and `yarn.lock` or `package-lock.json` files.
Once done, please do `npm install` or `yarn install` again and try it locally again.

**Comment by HollyII** [comment]
Hello @namastexlabs, i encountered the same issue on node 14.17.1
**an update to node version 16.18.1 fixed it for me.**

**Comment by namastexlabs** [comment]
Turns out going to 18LTS solved my issue as well.

Thanks!

Em qua., 19 de abr. de 2023 09:06, Holly ***@***.***>
escreveu:
