### ISSUE TITLE
"Fill from another locale" is too close at the Locale Select

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#16379]
### Required System information

- Node.js version: not applicable
- NPM version: not applicable
- Strapi version: 4.9.2
- Database: not applicable
- Operating system: macos
- Is your project Javascript or Typescript: JS

### Describe the bug

The "Fill from another locale" text is too close the Select locale component.

### Steps to reproduce the behavior

1. Enable localization on a content-type
2. Navigate to the content-type edit view in the content-manager

### Expected behavior

I expect there to be some space between the link and the select component

### Screenshots

<img width="291" alt="Screenshot 2023-04-13 at 16 56 09" src="https://user-images.githubusercontent.com/2244375/231801611-d0408d21-1aa7-482e-8e2d-e48501097d41.png">

**Comment by gu-stav** [comment]
@maevalienard Do you have opinions here?

**Comment by maevalienard** [comment]
I think this is a regression as it has never been that close to the select. From what I recall the spacing used to be 8px or 12px

**Comment by joshuaellis** [comment]
Hi @gu-stav thanks for reporting this issue, we've opened a PR to resolve it. As always, thank you for being an active community member.
