### ISSUE TITLE
[MediaLibrary]: Clicking the checkbox of one item when there is only one item and a folder checks the folder

### ISSUE THREAD

**Issue by joshuaellis** [strapi/strapi#16377]
### Required System information

- Node.js version: 18
- NPM version: yarn 3
- Strapi version: 4.9.0
- Database: SQLlite
- Operating system: macOS
- Is your project Javascript or Typescript: JS

### Describe the bug

When you're in the list view of the media library and you only have a single item and a folder, clicking the checkbox of the item makes the table thing all items are selected incl. the folder which is wrong (see video)

https://user-images.githubusercontent.com/37798644/231798798-4a0aa13b-9a28-41cb-8fe1-a03152d97a4a.mp4

### Steps to reproduce the behavior

1. Go to Media Library
2. Change the view to table / list
3. Create a new folder
4. Add a single asset in said new folder
5. Click checkbox of table row of the the asset

### Expected behavior

Only the asset should be selected by the checkbox

**Comment by ritiksharmarj** [comment]
You've mentioned "Operating system: macOS". Is this issue device-specific or I can solve this issue in the windows OS too?

**Comment by joshuaellis** [comment]
You should just submit a PR, we do not typically assign issues to members if they're about to solve it.

**Comment by ritiksharmarj** [comment]
Josh, I have created PR #16390. Could you check this PR? I am looking forward to your reply if there is any mistake.
