### ISSUE TITLE
Media library "json too long" log in React 18

### ISSUE THREAD

**Issue by remidej** [strapi/strapi#16384]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.9.1
- Database: sqlite
- Operating system: macos
- Is your project Javascript or Typescript: JS
### Steps to reproduce the behavior

1. Create an app with React 18 using the corporate template:

```sh
npx create-strapi-app@react18 strapi-react18 --quickstart --template corporate
```

2. Open `/admin`
3. Look in the console, you will see a log:

```txt
JSON Formatter: JSON too large to format
```

### Expected behavior

Not seeing that log. Which is the case when starting the latest version of the admin on main against the same Strapi API.

### Additional context

The log seems to be visible from all pages. It seems to come from the upload plugin not liking having too many assets (32).

**Comment by joshuaellis** [comment]
Do you have a video you can share? I can't seem to reproduce :(
