### ISSUE TITLE
CM: Click outside the filter popover does not close it

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#16381]
### Required System information

- Node.js version: not applicable
- NPM version: not applicable
- Strapi version: 4.9.1
- Database: not applicable
- Operating system: macos
- Is your project Javascript or Typescript: JS

### Describe the bug

When I open the filter popover in the CM and click outside it does not close.

### Steps to reproduce the behavior

1. Go to the content-manager edit view
2. Click on Filter
3. Click outside

### Expected behavior

I expect the popover to close.

### Screenshots

https://user-images.githubusercontent.com/2244375/231802936-80482f54-eeed-4d12-8ebd-10e27f2b8569.mp4

**Comment by gu-stav** [comment]
Related to https://github.com/strapi/strapi/issues/16380

**Comment by raph941** [comment]
Hi @gu-stav,

I have noticed that the issue you mentioned appears to be persistent across several instances of Popover usage, including `MediaLibrary`, `ContentManager`, and `MarketPlace`.

I was thinking that it would be a good idea to implement a solution to this problem within the design system repo. By doing this, we would not need to repeat the fix in each of the aforementioned instances.

What are your thoughts on implementing the logic to close the Popover on outside click? One possibility could be to support a new prop called `closeOnClickOut` on the `Popover` component.

Alternatively, we could create a wrapper component similar to `FocusTrap` that toggles the `Popover`'s visibility on outsideClick. Let me know what you think.

cc: @joshuaellis

**Comment by joshuaellis** [comment]
> Hi @gu-stav,
> 
> I have noticed that the issue you mentioned appears to be persistent across several instances of Popover usage, including `MediaLibrary`, `ContentManager`, and `MarketPlace`.
> 
> I was thinking that it would be a good idea to implement a solution to this problem within the design system repo. By doing this, we would not need to repeat the fix in each of the aforementioned instances.
> 
> What are your thoughts on implementing the logic to close the Popover on outside click? One possibility could be to support a new prop called `closeOnClickOut` on the `Popover` component.
> 
> Alternatively, we could create a wrapper component similar to `FocusTrap` that toggles the `Popover`'s visibility on outsideClick. Let me know what you think.
> 
> cc: @joshuaellis

Yes, this should be done in the DS.

I've been actually wondering if we should just refactor our `Popover` component to use `RadixUI` underneath, this would avoid a lot of these incidents from happening. We'd ofc need to preserve the current API.

**Comment by raph941** [comment]
Thanks. I think refactoring to `RadixUI` would help too. Would work on it.

**Comment by raph941** [comment]
Thanks @joshuaellis,
Prior to the refactoring to RadixUI, a temporary fix was [added here](https://github.com/strapi/design-system/pull/982) to support closing the popover on outside click, could you help take a look at it?

**Comment by Aurelsicoko** [comment]
@joshuaellis Could we close this one? It seems to be merged and released?
