### ISSUE TITLE
Documentation Plugin generates faulty path for Single Types

### ISSUE THREAD

**Issue by joshuajeschek** [strapi/strapi#16409]
### Required System information

- Node.js version: 16.19.1
- yarn version: 1.22.19
- Strapi version: 4.9.0
- Database: sqlite
- Operating system: Arch Linux x86_64 6.2.8-arch1-1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

- I have a Single Type in my application, called `index`
- this is how the corresponding generated path in the documentation looks like:
```json
{
  "paths": {
    "/index": {
      "get": {
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/IndexListResponse" }
              }
            }
          }
        }
      }
    }
  }
}
```
- this should actually references the schema `#/components/schemas/IndexResponse`, which also exists and reflects the response of the index path.

### Steps to reproduce the behavior

1. Construct a Single Type
2. Generate Documentation
3. Inspect path of single type - responses - 200 - content - ...

### Expected behavior

The schema `#/components/schemas/IndexResponse` should be referenced

### Additional context

This is pretty important to me, since the openapi generator cli will not generate the correct api client otherwise.

**Comment by Boegie19** [comment]
this issue should be fixed by https://github.com/strapi/strapi/pull/16429
