### ISSUE TITLE
Components are not closed by default in strapi 4.8.2

### ISSUE THREAD

**Issue by maruthasalamr** [strapi/strapi#16412]
As as strapi admin i need to create a new entry in the blog collection. i need to see the page.settings component as closed by default but currently its opened. how to resolve this ?. Need the component to be close by default.

Strapi Version - 4.8.2
OS:Mac OS

Screenshots
Currently i am having like this
![Image 17-04-23 at 1 26 PM](https://user-images.githubusercontent.com/78694065/232421718-b49c276a-9213-45ee-abda-175891094111.jpeg)

I need to have like this 

![Image 17-04-23 at 1 27 PM](https://user-images.githubusercontent.com/78694065/232421938-2e64b0fc-2a6c-441d-937f-cd1cf0d47317.jpeg)

**Comment by joshuaellis** [comment]
This was solved in `4.9.0`
