### ISSUE TITLE
PolicyContext type doesn't include request

### ISSUE THREAD

**Issue by bmpickford** [strapi/strapi#16423]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.9.1
- Database: MySQL
- Operating system: Mac
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When creating a new custom policy, the type for `PolicyContext` doesn't include keys that should be available like `request`
```typescript
import type { Policy } from "@strapi/strapi/lib/core/registries/policies";

const policy: Policy = (policyContext, config, { strapi }) => {
    //  error TS2339: Property 'request' does not exist on type 'PolicyContext'.
    console.log(policyContext.request);
    
    // ...

    return false;
};

export default policy;
```

### Steps to reproduce the behavior

1. Create a new file at: `./src/api/[apiName]/policies/is-authorized.ts`
2. Copy the above code
3. (optional) Add policy into the routes file at `./src/api/[apiName]/routes/[apiName].ts`

### Expected behavior

There are no Typescript errors and I can access the request object

### Screenshots

N/A

### Code snippets
Example with policyContext keys logged
```typescript
import type { Policy } from "@strapi/strapi/lib/core/registries/policies";

const policy: Policy = (policyContext, config, { strapi }) => {
  // logs this: ["is","type","request","response","app","req","res","originalUrl","state","matched","router","_matchedRoute","captures","params","routerPath","routerName"];
  console.log(Object.keys(policyContext));

  //  error TS2339: Property 'request' does not exist on type 'PolicyContext'.
  console.log(policyContext.request);
  return false;
};

export default policy;
```

### Additional context

[Koa's](https://koajs.com/#context) documentation references request/response. Could be that [PolicyContext](https://github.com/strapi/strapi/blob/294b0f6cfaabd423569ed1d19c6a428a41f45336/packages/core/strapi/lib/core/registries/policies.d.ts#L4) should extend Koa's [ExtendableContext](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L720) instead?

Happy to create the PR if that's the case 😄

**Comment by Convly** [comment]
Hi, thanks for opening this issue, indeed instead of extending the base context, we should consider extending the ExtandableContext.
If you have some time to create the PR, I'll happily review it
