### ISSUE TITLE
TS Import Aliases do not work

### ISSUE THREAD

**Issue by dukvanduken** [strapi/strapi#16456]
Strapi do not supply import aliases out of the box? Seems it does.
Usual TS config to require it (it's not work in latest Strapi):

See "paths" and "rootDir"
```
{
  "extends": "@strapi/typescript-utils/tsconfigs/server",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "paths": {
      "@src/*": ["./src/*"]
    }
  },
  "include": [
    "./",
    "./**/*.ts",
    "./**/*.js",
    "src/**/*.json"
  ],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.*",
    "src/plugins/**"
  ]
}
```

In "dist" I see "@src" bt not replacement to "../src" for example. So node confused and give me an error.
Or I do something wrong? Thanks!

**Comment by gregg-cbs** [comment]
@dukvanduken  - did you open a proper issue?
