### ISSUE TITLE
Uploading images when you create a new item removes images for all other items

### ISSUE THREAD

**Issue by MechJosh0** [strapi/strapi#1645]
**Informations**
- **Node.js version**: v9.5.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.13
- **Database**: MySQL
- **Operating system**: Windows & Linux

**What is the current behavior?**
When you have multiple items with images uploaded, when you make a new item with an image it'll remove the images from all other items in that content type.

**Steps to reproduce the problem**
1. Create a content type that has fields, image (file upload) and title.
2. Add a new item with an image and a title.
3. Add a new item with a title.
4. Edit the second item and add an image
-- Note, all items still have an image
5. Add a new item with an image and a title.
-- Items 1 and 2 have now lost their image

My steps show that you can edit items and upload an image to it perfectly fine, it is only when you add a new item with an image that it causes the bug.

**What is the expected behavior?**
Step 5 should not remove the images of other items in the content type.

**Suggested solutions**
Do not remove the images of other items when making a new item.

**Comment by daviyang35** [comment]
When this situation happened.  
Image still at storage and upload_file records is ok.
upload_file_morph records has beed lose.

**Comment by npjonath** [comment]
@lauriejim I think I have same behavior with mongodb. (hosted by Azur cosmodb). My upload are present in the upload folder and visible in strapi upload administration but not present in content type page. When I query it over REST or GraphQL the upload field is null.

**Comment by CKGrafico** [comment]
Still having this error, any update? the `"related": []` property is empty

**Comment by Oneway102** [comment]
For anyone who still visits here: the problem should have been fixed by https://github.com/strapi/strapi/pull/3963
