### ISSUE TITLE
Can not start on Remote server: error: Cannot read property 'singularName' of undefined TypeError: Cannot read property 'singularName' of undefined

### ISSUE THREAD

**Issue by da-kicks-87** [strapi/strapi#16460]
### Required System information

- Node.js version: v14.21.3
- NPM version: 6.14.18
- Strapi version: 4.9.2
- Database: MariaDB
- Operating system: MAC
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Starting on Remote server after running `NODE_ENV=production npm run start` I get this error message.

 `error: Cannot read property 'singularName' of undefined TypeError: Cannot read property 'singularName' of undefined /home/840887.cloudwaysapps.com/tsyeutjqgd/public_html/node_modules/@strapi/strapi/lib/core/loaders/apis.js:52:21`

### Steps to reproduce the behavior

1. On a remote server, follow the deployment guide. (https://docs.strapi.io/dev-docs/deployment)
2.  Run in terminal `NODE_ENV=production npm run build`
3. After successful build,  run `NODE_ENV=production npm run start`
4. See Error

### Expected behavior

I expect it to start the server to run Strapi

**Comment by Boegie19** [comment]
@da-kicks-87 Seems to me like in one of your content-types or single-types you are missing a singularName

**Comment by da-kicks-87** [comment]
@Boegie19 In what sense? I am able to start on my local machine no error. I have checked on my remote's `schema.json` files that all have `singularName` values.

**Comment by Boegie19** [comment]
I need to correct myself you are missing info in the schema

**Comment by da-kicks-87** [comment]
@Boegie19 What am I missing?

**Comment by Boegie19** [comment]
This whole part
```json
"info": {
    "singularName": "header",
    "pluralName": "headers",
    "displayName": "Header",
    "description": ""
  },
  ```

**Comment by da-kicks-87** [comment]
Looks like there was am empty old `home` folder. My deployment did't remove it for some reason. 
I removed all the files and re deployed from Github repo.

Starting the App now works.

Thanks for your help.
