### ISSUE TITLE
Bump aws-sdk-js version for security fix

### ISSUE THREAD

**Issue by CaptShmo** [strapi/strapi#16461]
### Required System information

- Node.js version: 18
- Strapi version: 4.9.2

### Describe the bug

Strapi 4.9.2 is triggering an npm audit warning about the aws-sdk package containing a child module xml2js security issue. This issue seems to have been fixed on their end, confirmation on the fix from the Strapi team and a version bump would be nice when possible. See thread describing the possible fix here:

https://github.com/aws/aws-sdk-js/issues/4392

**Comment by Marc-Roig** [comment]
seems that the version that fixes the vulnerability is v2.1357.0, but it is not yet released. I will set a reminder to check when it's released so we can upgrade.

**Comment by mayrsascha** [comment]
@Marc-Roig [According to NPM, version 2.1357.0 was out there already 2 weeks ago](https://www.npmjs.com/package/aws-sdk?activeTab=versions), the latest version now is 2.1366.0. Please upgrade when possible, thank you.
