### ISSUE TITLE
Charset is reverted if new field is added

### ISSUE THREAD

**Issue by limpep** [strapi/strapi#16476]
### Required System information

- Node.js version: 16+
- NPM version: 8+
- Strapi version: 4.9.2
- Database:  AWS Aurora MySQL
- Operating system: AMI Linux
- Is your project Javascript or Typescript: NextJS with Typescript 

### Describe the bug

Using AWS Aurora MySQL, setting the charset/collation on a column to `utf8mb4_general_ci `and then adding a new  field, reverts the field charset/collation back to default in this case. `latin1_swedish_ci  `

### Steps to reproduce the behavior

Set one of the columns collation in the DB to `utf8mb4_general_ci `
Then create a new field and deploy the change

The pervious set collection on the column is reverted to default instead of sticking with configure charset of `utf8mb4_general_ci `

### Expected behavior

The collection should not change when a new field is added to the db.

### Code snippets

CMS config 
```
module.exports = ({ env }) => ({
  connection: {
    client: env("DATABASE_CLIENT", "mysql"),

    connection: {
      host: env("DATABASE_HOST", "127.0.0.1"),
      port: env.int("DATABASE_PORT", 3306),
      database: env("DATABASE_NAME", "strapi"),
      user: env("DATABASE_USERNAME", "strapi"),
      password: env("DATABASE_PASSWORD", "strapi"),
      charset   : 'utf8mb4',
      collation : 'utf8mb4_unicode_ci'
    },
    debug: false,
  },
});
```

**Comment by derrickmehaffy** [comment]
Settings these are setting Knex.js on how it should read from the database but doesn't configure the database. These need to be set on the database itself (you set the default for the database and any new tables created will use these settings).
