### ISSUE TITLE
Configured list view fields does not persist

### ISSUE THREAD

**Issue by dtjldamien** [strapi/strapi#16474]
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.14.0
- Strapi version: 4.4.3
- Database: MySQL 8.0
- Operating system: MacOS Ventura 13.3.1

### Describe the bug

List view configuration does not persists across sessions

### Steps to reproduce the behavior

1. Go to Content Manager and click on the gear icon - `Configure the view`
2. Add a new field to the view ie `priority`
3. Restart the server / start another session
4. `priority` in the list view does not persist

### Expected behavior

`priority` in the list view should persist

**Comment by derrickmehaffy** [comment]
Unable to reproduce on v4.9.2
