### ISSUE TITLE
Documentation Plugin no longer works?

### ISSUE THREAD

**Issue by oliverkidd** [strapi/strapi#16470]
Since upgrading to strapi latest version the documentation plugin now doesn't seem to work?
It loads in alright but the button to open the docs does nothing.

- Node.js version: 18.14 
- NPM version: 9.3.1
- Strapi version: 4.9.2
- Database: local postgres
- Operating system: Mac
- Is your project Javascript or Typescript: TS

**Comment by oliverkidd** [comment]
Of what? There is nothing to show? The button appears in the admin panel for the plugin but when clicking the "open documentation" button nothing happens. It would normally open in a new tab

**Comment by matheus-rodrigues00** [comment]
Was it solved?
