### ISSUE TITLE
Upgrading to v4.9.2 breaks imports from `@strapi/utils` (Typescript)

### ISSUE THREAD

**Issue by rumbleperson** [strapi/strapi#16488]
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.9.2
- Database: PostgreSQL
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Upgrading to v4.9.2 breaks imports from `@strapi/utils`.

### Steps to reproduce the behavior

1. Import available methods from `@strapi/utils` package with the strapi application.
  
```typescript
import { yup, handleYupError } from "@strapi/utils";
```

2. Build Application
3. See error

```
error TS2614: Module '"@strapi/utils"' has no exported member 'handleYupError'. Did you mean to use 'import handleYupError from "@strapi/utils"' instead?
```

### Expected behavior

Import does not throw an error.

### Additional context

I've created a workaround, but I also have private plugins that are broken due to this issue and thought it should be reported.

```typescript
import strapiUtils from "@strapi/utils";
const { yup, handleYupError } = strapiUtils;
```

**Comment by thatsnotnice** [comment]
Same issue on Linux, NodeJS v18.16.0, npm v9.5.1. yarn v3.5.0, typescript.

Weird thing is that yesterday both an upgrade 4.9.0 -> 4.9.2 and a 4.9.2 fresh install went fine (they had only graphql plugin installed).
It's like if in the meantime something went south with some sub-dependency.

**Comment by alexandrebodin** [comment]
Hi I could not reproduce this with recent version of Strapi. I'll close. Don't hesitate to ping to reopen if this happens again :)
