### ISSUE TITLE
Cannot clear date field

### ISSUE THREAD

**Issue by JGalazan** [strapi/strapi#16493]
### Required System information

- Node.js version: 16.x
- NPM version: 7.19.1
- Strapi version: 4.9.1
- Database: SQL
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

It's not possible to clear any date field (at least tested with date-time field) with the 'x'. So once you choose a date, you can only change it, but not clear it.

Here's the console output when pressing the X button.

![image](https://user-images.githubusercontent.com/38088576/234087582-4d6647d6-ae88-43dc-a653-6ed1c450504f.png)

Note: The 'time' part of the field works fine, it clears the field to 00:00

### Steps to reproduce the behavior

1. Create a content-type with a date field on it (date + time)
2. Get to the content-manager and pick any date on that field.
3. Click the X to clear the field
![image](https://user-images.githubusercontent.com/38088576/234088671-1d87a7e5-9615-47ea-9f32-349bc60c7c29.png)
4. You won't be able to clear it.

### Expected behavior

I expect the field to be cleared, just like before I picked any date.

**Comment by kuji2336** [comment]
Same issue for me, I am using a PostgreSQL database :/

**Comment by didierbrun** [comment]
Hello there, 

This issue is still present in 4.12.0.

Unable to clear an optional date field.

**Comment by kuji2336** [comment]
> Hello there,
> 
> This issue is still present in 4.12.0.
> 
> Unable to clear an optional date field.

I was facing same problem, you can try to downgrade Strapi version to "4.10.5" it works as expected.
