### ISSUE TITLE
Reorder repeatable component crashes page

### ISSUE THREAD

**Issue by beniaminrychter** [strapi/strapi#16496]
### Required System information

- Node.js version: 18.12
- NPM version: 8.19.2
- Strapi version: 4.9.2
- Database: Postgres 13.10
- Operating system: Docker / Node 18.12 Alpine
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Blank page after changing the order of repeatable components.

### Steps to reproduce the behavior

1. Proceed to Strapi CMS
2. Open page with specific repeatable components (at the bottom I'm attaching code snippets)
4. Add 4 or more entities 
5. Change the order of added entities

### Expected behavior

It is always possible to change the order without any errors.

### Video

https://user-images.githubusercontent.com/27733472/234191105-1929c5ff-1f27-4f8c-8861-e12f238c860e.mov

![Screenshot 2023-04-25 at 08 23 14](https://user-images.githubusercontent.com/27733472/234191381-ea58ef49-2f43-4d35-95f4-83da41306de0.png)

### Code snippets

We are using components with this field:

```json
{
  "links": {
    "type": "component",
    "repeatable": true,
    "component": "common.link",
    "max": 10
  }
}
```

Common Link

```json
{
  "collectionName": "components_common_links",
  "info": {
    "displayName": "Link",
    "description": ""
  },
  "options": {},
  "attributes": {
    "label": {
      "type": "string",
      "maxLength": 255,
      "required": false
    },
    "url": {
      "type": "string",
      "maxLength": 255,
      "required": false,
      "regex": "^(https?:\\/\\/|\\/)(www\\\\.)?([a-zA-Z0-9äöüÄÖÜß@:%._\\-\\+~#=\\\\/?&]{1,256})?$"
    }
  }
}
```

**Comment by joshuaellis** [comment]
This _should_ be solved in 4.10 with the release of #16441
