### ISSUE TITLE
[TypeScript] Missing "types" from compilerOptions in tsconfig.json

### ISSUE THREAD

**Issue by Nigtellios** [strapi/strapi#16494]
### Required System information

- Node.js version: 16.16.0
- NPM version: 6.14.17
- Strapi version: 4.9.2
- Database: MySQL
- Operating system: Windows 11
- Is your project Javascript or Typescript: TypeScript

### Describe the bug
        
 As you see from the console below (in code snippet section), there is a problem with `util` from a module called `semver.` It can be easily fixed just by adding `types` into `tsconfig.json` `compilerOptions` object.

### Steps to reproduce the behavior

1. Create Strapi project on the same NPM/NODE versions as me by `npx create-strapi-app@latest <name>`
2. Install dependencies
3. Try to build the project

### Expected behavior

No webpack errors while trying to build.

#### Bug

```
● Webpack █████████████████████████ building (30%) 0/1 entries 6863/6891 dependencies 1869/2227 modules 223 active
 esbuild-loader › .cache\admin\src\content-manager\pages\App\useContentManagerInitData.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'util' in 'C:\laragon\www\bearball-the-saver\application\server\node_modules\semver\classes'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
```
        
#### FIX
 ```
 "types": [
      "node"
 ]
 ```
    
Into `tsconfig.json` inside "compilerOptions" object. Works like a charm.

Updated `tsconfig.json`:

```
{
  "extends": "@strapi/typescript-utils/tsconfigs/server",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "types": [
      "node"
    ]
  },
  "include": [
    "./",
    "./**/*.ts",
    "./**/*.js",
    "src/**/*.json"
  ],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.*",
    "src/plugins/**"
  ]
}
```

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/15225

**Comment by luke-z** [comment]
@derrickmehaffy Sorry for reopening the issue, but it happened to me today with 4.10.4 (and 4.10.5 which I tested just right now) and a fresh install. 
The proposed fix didn't work and I honestly don't think it's a type issue as it's about the semver package missing another package.

It works for me if I use an old yarn.lock in which those packages are still present, but it won't work in a fresh install with `yarn install` and no existing `yarn.lock` for example.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Sorry for posting in this closed issue, but it happened to me today with 4.10.4 (and 4.10.5 which I tested just right now) and a fresh install. 
> The proposed fix didn't work and I honestly don't think it's a type issue as it's about the semver package missing another package.
> 
> It works for me if I use an old yarn.lock in which those packages are still present, but it won't work in a fresh install with `yarn install` and no existing `yarn.lock` for example.

Can you open a new issue with some steps to reproduce.
