### ISSUE TITLE
isUserAuthorized fails to authorize users with a specified role

### ISSUE THREAD

**Issue by fishmacs** [strapi/strapi#165]
**5.3.0**:
**2.15.11**:
**1.5.4**:
**OSX**:

api/user/services/user.js
last part of isUserAuthorized function:
```
    ...
    // Check by roles.
    let userRole;
    for (let i = 0; i < user.roles.length; i++) {
      userRole = user.roles[i].name;
      if (userRole && _.contains(authorizedRoles, userRole)) {
        return true;
      }
    }
    ...
```
The problem is user.roles, user is parsed from jwt directly, which contains no role. 
should be _ctx.user

**Comment by Aurelsicoko** [comment]
This issue has been fixed. You can found the patch and some explanations here (https://github.com/strapi/strapi-generate-users/pull/28).
