### ISSUE TITLE
DateTime & Time pickers not showing seconds field

### ISSUE THREAD

**Issue by amadkor** [strapi/strapi#16504]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: 4.9.0
- Database: Azure Database for MySQL - MySQL Version 8.0
- Operating system: Dev: Windows 11, also deployed on a docker container based on node:16-alpine
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have a Time field where the user needs to input both minutes AND seconds using Strapi admin panel, the time editor only allows for selecting Hour and Minute as per the screenshot
![image](https://user-images.githubusercontent.com/301373/234474025-55148f38-ba25-402e-95cb-c37eeff68c20.png)

The database itself has 00:00:00 format, and if I change the value in the database manually to include seconds the API returns the correct timecoded values with seconds 
![image](https://user-images.githubusercontent.com/301373/234474185-e7c31e09-fa4e-4b6f-bbbd-525a5138c803.png)

Also, the [documentation] (https://docs.strapi.io/user-docs/content-type-builder/configuring-fields-content-type#-date) state that "The Date field can display a date (year, month, day), time (hour, minute, second) or datetime (year, month, day, hour, minute, and second) picker."

### Steps to reproduce the behavior

1. Go to 'Strapi Admin'
2. Go to Content-Type Builder and a new field of type Date in any collection, pick it to be DateTime or Time
3. Go to Content Manager to the collection containing the date field, create a new entry
4. Try to set the Time field to any value with seconds, the UI doesn't allow it 

### Expected behavior

The time portion of DateTime and the Time picker both should allow the user to select Hour, Minute, AND Seconds

### Screenshots

![image](https://user-images.githubusercontent.com/301373/234474025-55148f38-ba25-402e-95cb-c37eeff68c20.png)

**Comment by gu-stav** [comment]
@derrickmehaffy I think we can move this as feature request to Canny.

**Comment by oxenprogrammer** [comment]
@amadkor   Thank you for reporting this issue. I understand that having the ability to select seconds along with hours and minutes would be helpful, but it could potentially lead to performance issues and a cluttered UI. 

As an alternative, we could provide a custom input field where users can manually enter the time in the format `hh:mm:ss` and maintaining the select with the default `hh:mm` format as a dropdown. This would allow for more flexibility without sacrificing performance or UX. 

What do you think about this solution?
Thanks!

Cc: @joshuaellis  @derrickmehaffy

**Comment by joshuaellis** [comment]
> As an alternative, we could provide a custom input field where users can manually enter the time in the format hh:mm:ss and maintaining the select with the default hh:mm format as a dropdown. This would allow for more flexibility without sacrificing performance or UX.

You could make a customInput and serve it as a community plugin for sure. We're currently working on moving the TimePicker to be a combobox by nature and having a prop to dictate whether we want seconds or not could be a future iteration as we'd need to make it configurable in the `content-type-builder`.

**Comment by derrickmehaffy** [comment]
Moved to: https://feedback.strapi.io/customization/p/datetime-time-pickers-not-showing-seconds-field
Per @gu-stav's request
