### ISSUE TITLE
Can't filter components in Rest or Graphql

### ISSUE THREAD

**Issue by M-GRV** [strapi/strapi#16502]
### Required System information

- Node.js version: 18
- NPM version: 9.6.4
- Strapi version:  4.9.2
- Database: included
- Operating system: local

### Describe the bug

When trying to filter a collection with a component, it shows all available component entries instead of the one trying to be filtered. This happens on both rest and graph

### Expected behavior

Filter by collection field and component field

**Comment by derrickmehaffy** [comment]
Please provide detailed reproduction steps, ideally the structure of your content types and the filters used.

**Comment by M-GRV** [comment]
I have.. they are in discord

**Comment by M-GRV** [comment]
@derrickmehaffy I

https://media.discordapp.net/attachments/1100069609324941432/1100069609543049268/query.JPG|
https://media.discordapp.net/attachments/1100069609324941432/1100091062678200420/image.png

There is nothing special about my structure. It's literally any component inside of a collection that is doing this.
