### ISSUE TITLE
Run in path with Apache server

### ISSUE THREAD

**Issue by marceloavf** [strapi/strapi#1651]
**Informations**
- **Node.js version**: 10.5.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: Mongo
- **Operating system**: Windows 10
- **Operating system host**: Linux w/ Apache using .htaccess and internal pm2

**What is the current behavior?**
I sent the app to my host and it return to me a base path and port to use it, configure all normally and it runs in any of these address:
```
hostname.com.br:21034
hostname.com.br/download-api
```
But, the admin and api responses only works in the first address, and the SSL is active in the second one, don't letting me using in production since the consumer only works with `https` access. 

If I try `hostname.com.br:21034/admin` or `hostname.com.br:21034/api/exampleget` everything works fine, but doesn't work the same in `hostname.com.br/download-api/admin` or `hostname.com.br/download-api/api/exampleget`

Tried to use the prefix but doesn't seems to be working, as we can see in #1323 

Also tried some .htaccess methods to try to give it own subdomain

**What is the expected behavior?**
Able to run it with prefix or making possible to edit `routes` and works normally.

**Comment by lauriejim** [comment]
Maybe you can find information here https://github.com/strapi/strapi/issues/1539.

**Comment by marceloavf** [comment]
I'm migrating to DigitalOcean with Nginx to see if I can get it working

**Comment by derrickmehaffy** [comment]
@marceloavf similar questions have been asked about proxying to a subfolder, I explained a bit more here: https://github.com/strapi/strapi/issues/1539#issuecomment-403571806 and included some nginx sample configs.

Typically when working with headless cms systems you use a subdomain rather than a subfolder.

If you own a domain name your host should provide subdomains for free, its just a DNS setting.

**Comment by marceloavf** [comment]
Nice @derrickmehaffy, the problem was that the domain was configured by another host, so what I have to do was CNAME `www.subname` to `subname`, then use A to redirect it to the digitalOcean droplet IP Address, so I use some of your configuration and blog settings to make it work, still don't configurate in case I have more than one subdomain, but I'll manage it latter.

Thank you both for the response and the awesome work on this project!
