### ISSUE TITLE
Strapi Build Not Working in v4.10.0

### ISSUE THREAD

**Issue by awtrimpe** [strapi/strapi#16529]
### Required System information

- Node.js version: v16.19.1
- NPM version: 8.19.3
- Strapi version: v4.10.0
- Database:
- Operating system: Ubuntu 20.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

`npm run strapi build` is not working in the latest version.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/43074742/234600240-93ea706f-6e8f-46a2-ad9f-367d827cd1ba.png">

I tried deleting node_modules completely without any luck.

**Comment by Marc-Roig** [comment]
https://github.com/strapi/strapi/issues/16521

Same as Alex said, the fix was released in 4.10.1 and thank you for the alert 🚀
