### ISSUE TITLE
Unable to build application in new version 4.10.0

### ISSUE THREAD

**Issue by beniaminrychter** [strapi/strapi#16521]
### Required System information

- Node.js version: 18.12.0
- NPM version: 8.19.2
- Strapi version: 4.10.0
- Database: Postrgress
- Operating system: Docker / MacOS

### Describe the bug

As a developer, I cannot build application with `yarn build` command. I tested that in my current project and in a completely new one using `yarn create strapi-app my-app --quickstart`.

In both cases, I'm getting the same error:

![Screenshot 2023-04-26 at 15 16 29](https://user-images.githubusercontent.com/27733472/234586843-e1193afc-c3b0-48da-a1e5-8a4a058e5582.png)

### Steps to reproduce the behavior

1. Build the project with `yarn build`. 

### Expected behavior

I should be able to build a project.

**Comment by M-GRV** [comment]
Yep same issue here when upgrading. great. 

going from 4.9.1 to 4.10

**Comment by 94wogus-quantit** [comment]
same issue here

@strapi/strapi/lib/commands/action/build is not found.

**Comment by jbcrestot** [comment]
same issue here

Node.js: 14.19.3
yarn: 1.22.19
Strapi version: 4.10.0
Database: Postgresql
Operating system: Mac Ventura

**Comment by alexandrebodin** [comment]
Hi the fix was released in 4.10.1. Thank you for your timely alerts 🙏
