### ISSUE TITLE
Can't filter by repeatable component field in Rest or Graphql

### ISSUE THREAD

**Issue by M-GRV** [strapi/strapi#16528]
### Required System information

- Node.js version: 18.15
- NPM version: 9.6.4
- Strapi version:  4.9.1
- Database: sqllite
- Operating system: windows

### Describe the bug

When trying to filter a collection with a component, it shows all available component entries instead of the one trying to be filtered. This happens on both rest and graph

### Expected behavior

Be able to filter not only by a field in a collection, but further filter by a component field inside the entry colection.

### Steps to reproduce the behavior

1. Create a collection
2. Add a repeatable component 
3. Try to filter by collection name and filter by an integer field inside an attached repeatable component.
4. See issue

### Expected behavior

Be able to filter by a collection field and nested component to retrieve only a single entry of the attached repeatable component. 

### Screenshots

![model](https://user-images.githubusercontent.com/130182174/234597226-291ca4cc-396e-4d84-8c89-b11b5ea3426d.JPG)
![query](https://user-images.githubusercontent.com/130182174/234597233-9bf6aa5f-04ff-4458-ad02-82553c296cd0.JPG)

**Comment by derrickmehaffy** [comment]
Appears to work fine on v4.10.1 (tested with both REST and GraphQL against single and repeatable components)

![image](https://user-images.githubusercontent.com/8593673/235740920-7168bc4b-9f77-48b6-a596-28ac023eb206.png)

**Comment by M-GRV** [comment]
Let me upgrade and test.  ty

**Comment by Przecza** [comment]
Hi, 

I have very similar problem with filtering repeatable components in single type. I am not able to filter out. It worked before. 

Node.js version: 18.16
NPM version: 9.6.4
Strapi version: 4.10.8
Strapi graphQL plugin: 4.10.8
Database: postgres
Operating system: MacOS

it started with Strapi graphQL plugin: 4.10.8. It worked fine with previous versions. It is not working with current version (4.11.2). 

Expected output (Strapi version: 4.10.8, Strapi graphQL plugin: 4.10.7):
![image](https://github.com/strapi/strapi/assets/23193643/1d05667f-3747-48b6-9568-50003398b3c8)

Current output (Strapi version: 4.10.8, Strapi graphQL plugin: 4.10.8 to 4.11.2): 
![image](https://github.com/strapi/strapi/assets/23193643/b637e881-42fc-4583-af7f-a17208131566)

**Comment by alicanso** [comment]
still same with last verison.

Can't filter by repeatable component field in Rest or Graphql....
