### ISSUE TITLE
Automatic Image rotation is happening when uploading

### ISSUE THREAD

**Issue by khanharis87** [strapi/strapi#16534]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.9.1
- Database: postgres
- Operating system: macOs Big Sur
- Is your project Javascript or Typescript:

### Steps to reproduce the behavior

1. Upload an image of 4624✕2604 in Media Library
2. The image auto rotates and can not be set to default angle
3. Set the option for Auto Orientation to false in Settings and still it rotates.

### Expected behavior

When uploading the image to media library it should keep the default angle and not rotate.

**Comment by Marc-Roig** [comment]
hello, you can disable this behaviour in your Media Library Settings:
![image](https://user-images.githubusercontent.com/20578351/236388709-0709db87-b0cd-4a3d-bf95-e5832c5a21d8.png)
