### ISSUE TITLE
Save button not working

### ISSUE THREAD

**Issue by Ipriyankrajai** [strapi/strapi#16539]
### Required System information

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Strapi version: v4.9.0
- Database: MySQL (5.7.38)
- Operating system: ubuntu 
- Is your project Javascript or Typescript: Typescript

### Describe the bug

In my Pages Collection when i make any changes and press Save button for few pages its working fine and for few pages its not save data also not throwning any error.

### Steps to reproduce the behavior

1. Go to Pages collection
2. Click on reactjs
3. Make any changes
4. Try to save the changes
5. Button is not performing any action

#### Save Button not working
https://www.awesomescreenshot.com/video/16859003?key=c08751d5198672b580d6328e36c4e46e

#### Save Button working fine
https://www.awesomescreenshot.com/video/16859100?key=60304cc6016a83bfa5046dadbbe8c42b

**Comment by Ipriyankrajai** [comment]
Hey there was no api call in network tab as well as no error in console.

**Comment by derrickmehaffy** [comment]
@Ipriyankrajai I believe the issue is a validation one, most likely one of the fields in the content-type is set to required or something, if scroll down through the content-type one of the fields should be highlighted red with a warning message.

There should still be a popup error message so the bug is valid and I was able to reproduce it.

**Comment by Ipriyankrajai** [comment]
@derrickmehaffy i have attached the link there was no valid. Kindly have a look at that video.

**Comment by Boegie19** [comment]
@Ipriyankrajai can you make as small as possible reproduction on a fresh strapi instance on the newest version?

**Comment by Ipriyankrajai** [comment]
Hello @Boegie19,
I have created a demo. Where can i share you the credentials for it?

**Comment by Ipriyankrajai** [comment]
Hello @Boegie19,
I have created a demo. Where can i share you the credentials for it?

**Comment by joshuaellis** [comment]
> Hello @Boegie19, I have created a demo. Where can i share you the credentials for it?

Is it a github repo? I assume so, i'd just make some dummy accounts if you can and share them here.

**Comment by Ipriyankrajai** [comment]
I have successfully replicated our production environment where we were previously experiencing the issue. In order to facilitate collaborative problem-solving, I would like to share the login credentials for the hosted Strapi instance. This will enable everyone involved to access and examine the replicated environment, which will hopefully lead to a quicker resolution of the issue.

**Comment by joshuaellis** [comment]
> have successfully replicated our production environment 

Is this at all slimmed down to it's core e.g. removing plugins that we don't maintain etc.

**Comment by Ipriyankrajai** [comment]
We are using very few plugins like upload, ckeditor, seo and publisher.

Here is our config/plugins.js
 
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          Bucket: env("AWS_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
  ckeditor: true,
  seo: {
    enabled: true,
  },
  publisher: {
    enabled: true,
  },
});

**Comment by joshuaellis** [comment]
Does the issue persist if you remove "ckeditor, seo and publisher"? I want to be sure this is a minimal reproduction of the issue :) 

Would you feel comfortable emailing me the credentials? Failing that you can DM in Discord?

**Comment by Ipriyankrajai** [comment]
Yes it does with zero plugins. Sure i can share credentials on mail. Can you provide me your email address?

**Comment by joshuaellis** [comment]
> Yes, it does. Even with zero plugins, I face this issue. Sure I can share credentials by mail. Can you provide me with your email address?

josh.ellis@strapi.io

**Comment by Ipriyankrajai** [comment]
Thanks. I`ve mailed you.

**Comment by Ipriyankrajai** [comment]
Hey @joshuaellis,
Here is the schema for content type skillpages.

{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "singularName": "page",
    "pluralName": "pages",
    "displayName": "Skills Page",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Skill": {
      "type": "string",
      "required": true
    },
    "blogs": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::blog.blog",
      "inversedBy": "pages"
    },
    "faqSection": {
      "displayName": "FAQSection",
      "type": "component",
      "required": true,
      "repeatable": false,
      "component": "common.faq-section",
      "max": 7,
      "min": 1
    },
    "skillDetailSection": {
      "displayName": "skillsDetailSection",
      "type": "component",
      "required": true,
      "repeatable": false,
      "component": "common.skills-detail-section"
    },
    "pageSlug": {
      "type": "uid",
      "targetField": "Skill",
      "required": true
    },
    "knowledgeCenter": {
      "type": "component",
      "required": true,
      "repeatable": false,
      "component": "home.blogs"
    },
    "talentListingTitle": {
      "type": "string",
      "required": true,
      "minLength": 30
    },
    "skillCardForCategoryPage": {
      "type": "component",
      "repeatable": false,
      "required": true,
      "component": "shared.skills-card"
    },
    "skillPageTitle": {
      "type": "string",
      "required": true,
      "minLength": 3,
      "unique": true
    },
    "seo": {
      "type": "component",
      "repeatable": false,
      "component": "shared.seo"
    },
    "banner": {
      "type": "component",
      "repeatable": false,
      "component": "home.banner"
    },
    "inquiryFormTitle": {
      "type": "string"
    }
  }
}

**Comment by joshuaellis** [comment]
I'm hoping to recreate your structure (excluding plugins) can you supply the components that are defined in that schema too please? I'll probably omit relations because they cant be required at present.

**Comment by joshuaellis** [comment]
> Hello @joshuaellis ,
> 
> I wanted to inquire about the possibility of sharing a zip file containing the Strapi code with you via email. Would it be convenient for you to receive the file in this manner?

IMO I would share a private repo with me instead, it's easier to manage / download etc.
