### ISSUE TITLE
Dockerhub Official Image is two years old, does this still have support?

### ISSUE THREAD

**Issue by CaptShmo** [strapi/strapi#16535]
Just wondering if this still has support. Also, the "examples" folder linked to on the strapi/strapi page is a broken link. Thanks.

**Comment by derrickmehaffy** [comment]
We don't build official images anymore: https://docs.strapi.io/dev-docs/installation/docker#why-doesnt-strapi-provide-official-docker-images

https://github.com/strapi/strapi-docker

![image](https://user-images.githubusercontent.com/8593673/234710157-007b42a3-227b-4783-a57e-d15857bc4c4e.png)
