### ISSUE TITLE
Ordering issue on repeatable component inside another repeatable component

### ISSUE THREAD

**Issue by ekimv** [strapi/strapi#16547]
### Required System information

- Node.js version: 16.19.1
- NPM version: 8.19.3
- Strapi version: 4.9.2
- Database: mysql

### Describe the bug

I have built a navigation menu single type which is composed by repeatable components inside repeatable components.
When I reorder the level 2, it affects the level 1 orders.
And if I reorder a level 2 which has less entries than its own position in level 1, I got a white page

### Expected behavior

Levels ordering should not be linked so that if I change the level 2 order, it only affects the level 2 (and it does not hang)

### Screenshots

Here is a video record of reordering level 2 that affects level 1 :
![simplescreenrecorder-2023-04-27_16 42 36](https://user-images.githubusercontent.com/75667665/234904134-070fc31e-cb31-448a-a9ba-5ca771b6a631.gif)
https://user-images.githubusercontent.com/75667665/234902515-debf6f55-6c28-49d0-b231-e319c2b1f4e4.mp4

And a video record of reordering level 2 (in position 6, with only 3 items) that makes the app hang
![simplescreenrecorder-2023-04-27_16 40 59](https://user-images.githubusercontent.com/75667665/234904223-d34521d4-b9af-4d90-af3b-9e1d3b15ec57.gif)
https://user-images.githubusercontent.com/75667665/234902800-ff5e80ee-ed9d-44ad-b283-4412205fd073.mp4

Here is the console log when I got the white screen :
![image](https://user-images.githubusercontent.com/75667665/234902299-c0412bf6-088e-4663-9b76-a3ba65367e84.png)

**Comment by joshuaellis** [comment]
This was solved in `4.10` please upgrade your strapi version to the latest and we can reopen if it is :)

**Comment by ekimv** [comment]
Hello,
I think this issue is fixed in v4.12.5 ; thanks ! :)
