### ISSUE TITLE
Issue in data transfer in strapi to local host port : http://127.0.0.1:1337/admin 

### ISSUE THREAD

**Issue by dprabhat670** [strapi/strapi#16568]
I am encountering an issue with data transfer in Strapi to a local host port. Specifically, when attempting to access the admin panel at http://127.0.0.1:1337/admin, I am unable to transfer data from my Strapi instance to my local host. I have checked the port number and verified that I am using the correct one. I have also disabled any firewall or antivirus software that may be blocking the connection, but the issue persists. Additionally, I have checked my Strapi project's CORS configuration to ensure that it is not preventing my request from being processed. I am unsure of what else may be causing this issue and would appreciate any guidance or support in resolving it.

**Comment by GabrielLeandroBS** [comment]
@dprabhat670 Let's solve your problem, could you send a print or code snippet of your database.js, server.js and admin.js file please?
