### ISSUE TITLE
Can't store JSON from content manager

### ISSUE THREAD

**Issue by NoahHahm** [strapi/strapi#1657]
**Informations**
- **Node.js version**: v10
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.13.0.1
- **Database**: mongodb
- **Operating system**: mac

It creates a json type and does not save it when saving the object type.

conversely, if you start with array, it will be saved normally.

[rec_bug.zip](https://github.com/strapi/strapi/files/2237831/rec_bug.zip)

**Comment by lauriejim** [comment]
Hello @NoahHahm , Can you try with non empty object please.

**Comment by NoahHahm** [comment]
the same is true if you try with an empty object.

**Comment by derrickmehaffy** [comment]
@lauriejim mysql Strapi is saving the value as "undefined"

(I can confirm that you can't save if the json text box is empty, you have to put `{}`)

![image](https://user-images.githubusercontent.com/8593673/43374826-8d9f9efa-9366-11e8-8001-5af324adfc3b.png)

![image](https://user-images.githubusercontent.com/8593673/43374836-98488574-9366-11e8-8b79-99e5b031f993.png)

Model:

```
{
  "connection": "default",
  "collectionName": "journaldata",
  "info": {
    "name": "journaldata",
    "description": "Raw journal dumps"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "eventName": {
      "type": "string"
    },
    "systemName": {
      "type": "string"
    },
    "bodyName": {
      "type": "string"
    },
    "stationName": {
      "type": "string"
    },
    "cmdrName": {
      "type": "string"
    },
    "latitude": {
      "type": "float"
    },
    "longitude": {
      "type": "float"
    },
    "isBeta": {
      "type": "boolean"
    },
    "jsonData": {
      "type": "json",
      "required": true
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
Note that saving the value and re-opening it that json value is empty, I pasted that there to show valid json

**Comment by lauriejim** [comment]
After investigate on this issue. It seems it's coming from the input that sending `undefined`

**Comment by derrickmehaffy** [comment]
I believe sending data via the API itself should be fine, Jim and I both took a look on some test projects that it is coming from the frontend.

@NoahHahm can you try testing using something like Postman, I'm about to do the same on all 3 databases.

**Comment by derrickmehaffy** [comment]
Mongo using Postman:

![image](https://user-images.githubusercontent.com/8593673/43382846-f8ef2802-938d-11e8-988f-79889f9fb79f.png)

Postgres using Postman:
![image](https://user-images.githubusercontent.com/8593673/43382863-067449da-938e-11e8-963a-924da75e4d42.png)

MySQL using Postman:
![image](https://user-images.githubusercontent.com/8593673/43382877-1368b5ea-938e-11e8-843a-2bacd7458aac.png)
