### ISSUE TITLE
Admin related items pop-up menu doesn't seem to be working

### ISSUE THREAD

**Issue by simon-online** [strapi/strapi#16572]
### Required System information

- Node.js version: v16.20.0
- NPM version: v8.19.4
- Strapi version: v4.10.1
- Database: PostgreSQL 13.7
- Operating system: Alpine Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

In the Admin > Content Manager, when you select a Collection Type and see the entry list page, if you have a relation field column selected then you see the number of items details which you can click on to bring up a pop-up menu of items, but when you click on these items or the "..." button at the end nothing happens.

### Steps to reproduce the behavior

1. Create a Collection Type with a related field
2. Populate collection type and related collection type with entries
3. Go to the Collection Type entry list page and select the relation field
4. Click on an "X items" dropdown button and click on the options in the related Items pop-up menu

### Expected behavior

I expected when I clicked on any items in the related Items pop-up menu it would take me to that item and the "..." button would show the complete list of related items.

### Screenshots
![Screen Shot 2023-04-30 at 2 13 31 am](https://user-images.githubusercontent.com/10040020/235312589-39b97fa0-b3c5-4dd6-8177-b62f306ee039.png)

**Comment by gu-stav** [comment]
@derrickmehaffy I think we can move this as a feature request to Canny.

**Comment by derrickmehaffy** [comment]
Moved to: https://feedback.strapi.io/customization/p/admin-related-items-pop-up-menu-doesnt-seem-to-be-working
Per @gu-stav's request
