### ISSUE TITLE
`npm run transfer --to (remote-server)` is not using media upload provider

### ISSUE THREAD

**Issue by JakeElder** [strapi/strapi#16582]
### Required System information

- Node.js version: 18.5.0
- NPM version: 9.5.0
- Strapi version: 4.10.1
- Database: SQLite,Postgres
- Operating system: MacOS 12.4/Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am using `npm run transfer --to (url) --to-token (token)` to migrate content from my development environment to production
In my local environment, I am using the default local provider to store media
In production I am using `@strapi/provider-upload-cloudinary`
my `config/plugins.ts` is configured to only add the `@strapi/provider-upload-cloudinary` when `NODE_ENV === production`

⚠️ **My problem**

When I use `npm run transfer`, the production environment does not seem to use `@strapi/provider-upload-cloudinary`
Instead, all media is migrated to the local file system
Is this expected behaviour, or am I missing something?
I can confirm that if I use the media library via the admin panel in production, my images are stored in the associated Cloudinary account correctly

### Steps to reproduce the behavior

1. Set up a Strapi instance that uses local images
2. Set up a strapi instance that uses remote images (`@strapi/provider-upload-cloudinary`)
3. Upload an image to the instance that uses local images
4. Run `npm run transfer --to (remote-image-instance-url) --to-token (token)` (from the local images instance)

### Expected behavior

I expect the images present in the `--from` instance to be migrated to the destination instance. I expect any media to be uploaded using the provider specified in the destination instances config.

### Code snippets

config/plugins.ts
```typescript
export default ({ env }) => {
  const cloudinary = {
    upload: {
      config: {
        provider: "cloudinary",
        providerOptions: {
          cloud_name: env("CLOUDINARY_NAME"),
          api_key: env("CLOUDINARY_KEY"),
          api_secret: env("CLOUDINARY_SECRET")
        },
        actionOptions: {
          upload: {},
          uploadStream: {},
          delete: {}
        }
      }
    }
  };

  if (env("NODE_ENV", "development") === "development") {
    return {};
  }

  return { ...cloudinary };
};

```

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/15225
