### ISSUE TITLE
 users-permissions UI issue

### ISSUE THREAD

**Issue by NoahHahm** [strapi/strapi#1658]
**Informations**
- **Node.js version**: v10
- **npm version**: 5.x.x
- **Strapi version**: v3.0.0-alpha.13.0.1
- **Database**: mongodb
- **Operating system**:Informations

for the advanced page in users-permissions UI does not work normally.

I am using the latest version of Mac chrome.

**Comment by lauriejim** [comment]
Hello @NoahHahm , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
