### ISSUE TITLE
Internal server error when post contains emoji

### ISSUE THREAD

**Issue by kerstenremco** [strapi/strapi#16580]
### Required System information

- Node.js version: v18.16.0
- NPM version: 
- Strapi version: v4.9.2
- Database: MariaDB 10.8
- Operating system: Happens on different OS (Ubuntu and macOS)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When I try to save a post that contains an emoji I get an internal server error.

### Steps to reproduce the behavior

Create a entry that contains an emoji

### Screenshots

![2023-05-01 08_51_38-Content Manager en nog 10 andere pagina's - Profiel 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/55450744/235419442-1659d986-b2ad-4fbc-8da5-3a5d5e134fb0.png)

**Comment by derrickmehaffy** [comment]
Hi @kerstenremco this is most likely due to the charset your database is using, on your MariaDB server you can run this command to check the databases default charset and the one your database it set to:

Global database default charset:

```sql
show variables like "character_set_database";
```

> character_set_database	utf8mb4

Your database charset:

```sql
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'your_db_name';
```

> utf8mb4	utf8mb4_general_ci

Strapi by default expects your database to be using utf8mb4 but it will depend on how your database was configured.

There are already several issues about this: https://github.com/strapi/strapi/issues?q=is%3Aissue+utf8mb4+is%3Aclosed

**Comment by kerstenremco** [comment]
Hi @derrickmehaffy, thanks for your reply!

My database is utf8mb4.

I've been able to find previous bug reports that adding `charset: env("DATABASE_CHARSET", "utf8mb4")` to the _connections.mysql.connection_ in _config/databasje.js_ fixes the problem.

I've tested this, and it certainly works. Now I can add emoji's.

Do you happen to have any explanation for me why this setting is needed separately?

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy, thanks for your reply!
> 
> My database is utf8mb4.
> 
> I've been able to find previous bug reports that adding `charset: env("DATABASE_CHARSET", "utf8mb4")` to the _connections.mysql.connection_ object in _config/databasje.js_ fixes the problem.
> 
> I've tested this, and it certainly works. Now I can add emoji's.
> 
> Do you happen to have any explanation for me why this setting is needed separately?

It shouldn't be required as the mysql itself uses that as the default as well :thinking:

**Comment by Boegie19** [comment]
@kerstenremco what version of mysql are you using?

**Comment by Boegie19** [comment]
@derrickmehaffy default charset for mysql 5.7 and mariadb 10 is latin1 and not utf8

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy default charset for mysql 5.7 and mariadb 10 is latin1 and not utf8mb4

It's not in mysql 8 and I'm pretty sure knex sets it to UTF-8 MB4

**Comment by kerstenremco** [comment]
> > Hi @derrickmehaffy, thanks for your reply!
> 
> > 
> 
> > My database is utf8mb4.
> 
> > 
> 
> > I've been able to find previous bug reports that adding `charset: env("DATABASE_CHARSET", "utf8mb4")` to the _connections.mysql.connection_ object in _config/databasje.js_ fixes the problem.
> 
> > 
> 
> > I've tested this, and it certainly works. Now I can add emoji's.
> 
> > 
> 
> > Do you happen to have any explanation for me why this setting is needed separately?
> 
> 
> 
> It shouldn't be required as the mysql itself uses that as the default as well :thinking: 

I'm using MariaDB

**Comment by kerstenremco** [comment]
> @derrickmehaffy You are contradicting yourself 
> 
> https://github.com/strapi/strapi/issues/16476
> 
> 
> 
> Aka there you say that knex only desided as what to read it
> 
> 
> 
> Just checked and confirmed knex sets it to the database default aka UTF8MB4 for mysql 8 since that is the default but mysql 5.7 and mariadb 10.8.8 defaults to latan1 you can change that 
> 
> 
> 
> knex uses the default of the database so depending on what the default is it will use it

Thanks for your explanation! :)
