### ISSUE TITLE
TypeScript errors when using code from controller examples in documentation

### ISSUE THREAD

**Issue by phmasek** [strapi/strapi#16594]
### Required System information

- Node.js version: 18.14.0
- NPM version: 9.3.1
- Strapi version: 4.10.1
- Database: Mysql
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Copying the code directly for the examples in the documentation does not work.

### Steps to reproduce the behavior

1. Create new strapi project (make sure to use typescript)
2. Install all packages
3. Create new model
4. Extend the controller

### Expected behavior

No typescript errors.

### Screenshots

<img width="801" alt="image" src="https://user-images.githubusercontent.com/1712993/235715929-8ae56310-0ba6-4416-ab1c-6b1501f62aff.png">

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/15225
