### ISSUE TITLE
Wrong z-index for reset overlay

### ISSUE THREAD

**Issue by CupCakeArmy** [strapi/strapi#1660]
**Informations**
- **Node.js version**: 10.7.0
- **npm version**: 6.2.0
- **Strapi version**: v3.0.0-alpha.13.0.1
- **Database**: mongo
- **Operating system**: macOS

**What is the current behavior?**

The reset overlay has wrong z-index, colliding with the file upload box

<img width="1439" alt="screen shot 2018-07-28 at 22 11 15" src="https://user-images.githubusercontent.com/14948823/43360317-d59f6be4-92b3-11e8-8d1f-97489fd291f2.png">

**Steps to reproduce the problem**

1. Install
2. Make a modell
3. Click reset on the top right

**What is the expected behavior?**

The overlay should have the right z-index

**Suggested solutions**

The css class of the reset overlay `modal fade show` has `z-index: 1050`
The css class of the file uploader has `z-index: 9999`
Fix the z-index.

**Comment by lauriejim** [comment]
Hello @CupCakeArmy , thank you for reporting this issue. Can you submit a PR please, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by CupCakeArmy** [comment]
Sure, I'll do it in a couple of days. Very busy right now
