### ISSUE TITLE
Cloudinary upload provider cannot upload files larger than 100 MB

### ISSUE THREAD

**Issue by goodhoko** [strapi/strapi#16601]
### Required System information
- Strapi version: 4.9.0

### Describe the bug

When uploading any file larger than 100 MB using the [Cloudinary provider](https://www.npmjs.com/package/@strapi/provider-upload-cloudinary) the file is rejected with a HTTP 413.
 
### Steps to reproduce the behavior

1. Setup Strapi with the Cloudinary upload provider.
2. Upload a file larger than 100 MB.
3. The upload fails.

### Expected behavior
The file is uploaded just fine.

### Additional context

This happens because Cloudinary limits the file size for the regular upload method to 100 MB. For larger files, they require [chunking the file](https://cloudinary.com/documentation/upload_images#chunked_asset_upload). (See also https://support.cloudinary.com/hc/en-us/community/posts/360009586100/comments/360002140099)

**Comment by Marc-Roig** [comment]
Hello! I am looking into this.  Thank you for taking the initiative and opening a PR 🚀

**Comment by Marc-Roig** [comment]
@MhdSadd yes please, feel free to raise an issue about it if this issue is happening with the digitalocean upload provider.
