### ISSUE TITLE
Path to documentation broken for documentation plugin

### ISSUE THREAD

**Issue by TheInfamousGrim** [strapi/strapi#16617]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.12.1
- Strapi version: 4.9.0
- Database: postgreSQL
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I've managed to generate the documentation for the API using the documentation plugin. However when clicking on the button that links to the documentation it links to the following path:

`http://localhost:1337/documentation/v[object Object]`

Now if change the path to the correct path:

`http://localhost:1337/documentation/v0.1.0`

It works as expected and I am linked to the generated documentation.

### Steps to reproduce the behavior

1. Go to Documentation in the Plugins section
2. Click on the Open documentation plugin
3. See error 404 page

### Expected behavior

When I click on the Open documentation button I expect to be linked to the swagger UI page detailing my documentation

### Screenshots

![Documentaion plugin path error](https://i.imgur.com/ba6hdoP.png)

![Documentation plugin path expected behavior](https://i.imgur.com/KqM631m.png)

### Code snippets

Current plugin.ts in config file:

```TypeScript
export default ({ env }) => ({
  // API Documentation Versioning
  documentation: {
    enabled: true,
    config: {
      info: {
        version: "0.1.0",
      },
    },
  },
  //...
});
```

**Comment by derrickmehaffy** [comment]
Confirmed via @nathan-pichon in our internal Slack
