### ISSUE TITLE
Creating a component called "results" conflicts with Strapi codebase, leading to a breaking error

### ISSUE THREAD

**Issue by dragGH102** [strapi/strapi#16622]
### Required System information

Node v18
Npm 8.13.2
Strapi 4.9.2.
Javascript
SQLite
MacOS Monterey

### Describe the bug

Creating a component called "results" conflicts with Strapi codebase, and no warning or error is provided when doing so.

### Steps to reproduce the behavior

1. Create a single type 'x'
2. Add a new component 'results'
3. Restart strapi (strapi develop)
4. Observe `iterable[symbol.iterator] is not a function` in console and empty UI in strapi

### Expected behavior

Should load as expected

### Code snippets

The error happens in `node_modules/@strapi/plugin-content-manager/server/services/entity-manager.js`: `entities` does in fact contain a `results` property, but that's the name of the component, not what Strapi supposedely expects

```
  async mapEntitiesResponse(entities, uid) {
    if (entities?.results) { // <--This should probably be false as it's a single type, but ends up being true because of the component name
      const mappedResults = await mapAsync(entities.results, (entity) =>
        this.mapEntity(entity, uid)
      );
      return { ...entities, results: mappedResults };
    }
    // if entity is single type
    return this.mapEntity(entities, uid);
  }
```

### Additional context

It seems the same check is done also in the latest Strapi main branch
(commit a7d616e158a9a9f8ecd8d6da1d1e2eaff066be75)

**Comment by Boegie19** [comment]
Closed since there is a tracking issue for this issue https://github.com/strapi/strapi/issues/16222
