### ISSUE TITLE
Custom logo is horizontally stretched on register page

### ISSUE THREAD

**Issue by Sija** [strapi/strapi#16624]
## Bug report

Custom logo on the register page is horizontally stretched.

### Required System information

- Strapi version: 4.10.2

### Steps to reproduce the behavior

1. Go to `<strapi url>/admin/auth/register`
2. See stretched logo

### Screenshots

login:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/988/236316406-89dad606-9c82-4fc5-9eda-aeb3f28241ec.png">

register:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/988/236316176-ff86bab0-8de5-4891-8ab6-ff8a0b0f1903.png">

**Comment by Refrezsh** [comment]
Same
