### ISSUE TITLE
Bug in the @strapi/plugin-upload 

### ISSUE THREAD

**Issue by Abhinegi2** [strapi/strapi#16620]
### **Bug Description**

I am encountering an error while trying to start my Strapi server. Specifically, when I run the command npm run develop, I receive the following error message:

`TypeError: Cannot read properties of undefined (reading 'register Override') at Object.module.exports(\node_modules\@strapi\plugin-upload\server\register.js:31:7\)
`

### **Steps to Reproduce**

- Run the command npm install to install all dependencies in the existing project.

- Run the command npm run develop to start the Strapi existing project.

### **Expected Behavior**

I expected the Strapi server to start without any errors and for the **@strapi/plugin-upload** module to load correctly.

### **Actual Behavior**

Instead, I receive the error message **TypeError: Cannot read properties of undefined (reading 'register Override') at Object.module.exports(\node_modules\@strapi\plugin-upload\server\register.js:31:7\)** and the Strapi server fails to start.

### **Troubleshooting Steps**

**I have already tried the following steps to troubleshoot the issue:**

- Checked that all dependencies are installed by running npm install.
- Checked for and updated to the latest version of the @strapi/plugin-upload module by running npm outdated @strapi/plugin-upload and npm update @strapi/plugin-upload.
- Deleted the node_modules directory and package-lock.json file, then reinstalled all dependencies by running npm install.

  However, none of these steps have resolved the issue.

### **Environment**
 
- **Strapi version**:4.8.2
- **Node.js version**: v16.13.2
- **Operating system**: Windows 11

**Comment by Abhinegi2** [comment]
@Boegie19  Updated the issue with the template

**Comment by Marc-Roig** [comment]
This seems to be related to the documentation plugin

https://github.com/strapi/strapi/blob/main/packages/core/upload/server/register.js#L27-L35

I am not able to reproduce it but I am using a macOS, maybe it's related to windows.

**Comment by Marc-Roig** [comment]
@markkaylor I see this was introduced in this PR.
https://github.com/strapi/strapi/pull/16265/files#diff-403128d43f80a97797070cb926b6b449d85cb684a98df1d3578efa25f3802fcdR31

I imagine theh service('override') returns null, does that might happen when you don't have the documentation plugin installed? (@strapi/plugin-documentation)

**Comment by Abhinegi2** [comment]
> @markkaylor I see this was introduced in this PR. https://github.com/strapi/strapi/pull/16265/files#diff-403128d43f80a97797070cb926b6b449d85cb684a98df1d3578efa25f3802fcdR31
> 
> I imagine the service('override') returns null, does that might happen when you don't have the documentation plugin installed? (@strapi/plugin-documentation)
`
hey, these are my dependencies -
  "dependencies": {
    "@strapi/plugin-documentation": "4.5.1",
    "@strapi/plugin-graphql": "4.5.1",
    "@strapi/plugin-i18n": "4.5.1",
    "@strapi/plugin-upload": "^4.5.3",
    "@strapi/plugin-users-permissions": "4.5.1",
    "@strapi/provider-email-nodemailer": "4.5.1",
    "@strapi/provider-upload-aws-s3": "4.5.1",
    "@strapi/strapi": "^4.8.2",
    "better-sqlite3": "^7.6.2",
    "css-loader": "^6.7.2",
    "docx4js": "^3.2.17",
    "lodash": "^4.17.21",
    "pg": "8.8.0",
    "slugify": "^1.6.5",
    "strapi-plugin-import-export-entries": "^1.18.0",
    "style-loader": "^3.3.1"
  }
  `

**Comment by Abhinegi2** [comment]
Hey @markkaylor, After further investigation, we update the @strapi/plugin-documentation package to the latest version(^4.10.2). 
so now I am not facing any error when running **npm run develop**.
so I think there are some issues with  **@strapi/plugin-documentation** plugin.

**Comment by markkaylor** [comment]
Hi @Abhinegi2 the documentation plugin did introduce a new 'override' service in 4.10 that the upload plugin is now using since 4.10.

In your dependencies the upload plugin will use version 4.10 with ^4.5.3, but you've locked the documentation plugin at 4.5.1 so it will not have the service the upload plugin is trying to use.

Strapi recommends upgrading _all_ of your strapi dependencies: 
https://docs.strapi.io/dev-docs/update-version#upgrade-the-dependencies

As you've seen, with your strapi versions in sync (both documentation and upload at v4.10) you no longer have the error. I hope that helps.
