### ISSUE TITLE
Mysql Error 1062 ER_DUP_ENTRY

### ISSUE THREAD

**Issue by Bryelmo** [strapi/strapi#16669]
## Bug report
I created the 24th menu (id:24) with Navigation UI plugin and Strapi created the relative translated menu (id:25) and, after this, I cannot restart Strapi with `npm run develop` because I get a `MYSQL Error 1062`.

### Required System information

- Node.js version: v18.15.0
- NPM version: v9.5.0
- Strapi version: v4.9.2 or v4.10.2
- Database: Mysql Server v5.7
- Operating system: MacOs Ventura 13.2.1 
- Typescript
- [Navigation UI](https://market.strapi.io/plugins/strapi-plugin-navigation)  v2.2.8 installed plugin

### Describe the bug

It seems that Strapi try to INSERT the last translated menu during the `npm run develop` startup and fails with this error.
I tried with an another database backup with all the last stored navigations until to id:22 (en-EN) and id: 23(it-IT) and everything works fine but every time I try to add another menu (24, 25) I get this error after stopping and restarting Strapi.

### Steps to reproduce the behavior

1. Istall Navigation UI plugin
2. Go to on Navigation UI plugin section
3. Create translated menu until 24th id
4. Stop Strapi
5. Run Strapi with `npm run develop`

### Expected behavior

I would like to add more than 24 menu

**Comment by Bryelmo** [comment]
Update:
I noticed that I had the .strapi.updater.json with:
`{
	"latest": "4.10.2",
	"lastUpdateCheck": 1683634475390,
	"lastNotification": 1683646052673
}`

After deleting it and recreating it now it's:
`{
	"latest": "4.10.2",
	"lastUpdateCheck": 1683703932764
}`

Actually, the issue with this updated file seems solved.

**Comment by joshuaellis** [comment]
We don't maintain that plugin unfortunately, if the problem persists without the plugin then we can look at resolving this :)
