### ISSUE TITLE
While sort by relation "mainField" is an object

### ISSUE THREAD

**Issue by zaycker** [strapi/strapi#16661]
https://github.com/strapi/strapi/blob/c21ac55dba031ac797f748e615e520a289c6394d/packages/core/helper-plugin/src/components/DynamicTable/TableHead/index.js#L54

@gu-stav I have such case with strapi 4.10.2 and default functionality. Not sure why (maybe faulty migration...)
`fieldSchema.type` is `'relation'` but `mainField` is an object:
```
{
  name: "name",
  schema: {
    type: "string"
  }
}
```

as a result I have such sort in the URL and in the request:
`&sort=attr_label.name[[object%20Object]]:ASC` and it is failed with 500 status

**Comment by gu-stav** [comment]
@zaycker Thanks for opening the issue. Could you please attach a schema and reproducible steps? This will make it much easier to investigate and fix the issue.

**Comment by zaycker** [comment]
well, I guess I can share just two of them that produce the relation and the error...
src/api/attr-label/content-types/attr-label/schema.json
```
{
  "kind": "collectionType",
  "collectionName": "attr_labels",
  "info": {
    "singularName": "attr-label",
    "pluralName": "attr-labels",
    "displayName": "AttrLabel"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "uid",
      "required": true,
      "targetField": "name"
    }
  }
}
```

src/api/attr-value/content-types/attr-value/schema.json
```
{
  "kind": "collectionType",
  "collectionName": "attr_values",
  "info": {
    "singularName": "attr-value",
    "pluralName": "attr-values",
    "displayName": "AttrValue",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "uid",
      "targetField": "name",
      "required": true
    },
    "attr_label": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::attr-label.attr-label"
    }
  }
}
```

when I'm trying to sort by attr-label in the table with attr-value it produces 500 and [object%20Object] in the URL
