### ISSUE TITLE
Internal Server error with special character   ≥

### ISSUE THREAD

**Issue by zerbfra** [strapi/strapi#16676]
### Required System information

- Node.js version: 18.16.0
- Strapi version: 4.10.4
- Database: MySQL
- Operating system: Docker (Ubuntu)
- Is your project Javascript or Typescript: JS

### Describe the bug

1. Create a new content with a field of type rich text
2. Create a new entry and use inside the field the character ` ≥ `
3. You get internal server error

### Expected behavior

It should save

### Additional context

Log says: 

```
 insert into `newss` (`created_at`, `created_by_id`, `published_at`, `testo`, `titolo`, `updated_at`, `updated_by_id`) values ('2023-05-10 13:32:31.073', 1, NULL, 'dfd v  ? ', 'tet', '2023-05-10 13:32:31.073', 1) - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE2\x89\xA5 ' for column 'testo' at row 1
strapi-td        | Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE2\x89\xA5 ' for column 'testo' at row 1
```

**Comment by Boegie19** [comment]
You are most likely using the wrong char set in the db you should be using utf8mb4 and are most likely using utf8
