### ISSUE TITLE
Documentation plugin not applying custom settings in vesion >=4.10.0

### ISSUE THREAD

**Issue by adrianjarc** [strapi/strapi#16674]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.6.4
- Strapi version: 4.10.X
- Database: postgres
- Operating system: MacOS Ventura 13.3.1 (a) (22E772610a)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Auto generating documentation does not account for `src/extensions/documentation/config/setting.json` or `config/plugins.ts`.
No matter what I have set in `config/plugins.ts` or in `src/extensions/documentation/config/settings.json` for documentation plugin, it always reverts to default.

### Steps to reproduce the behavior

1. Create `src/extensions/documentation/config/settings.json` file with content: 
```json
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "My custom Title",
    "description": "some documentation"
  },
  "servers": [
    {
      "url": "https://example.com/api",
      "description": "Development server"
    },
    {
      "url": "http://localhost:1337/api",
      "description": "Localhost"
    }
  ]
}
```
2. In `config/plugins.ts` file add settings for documentation plugin: 
```js
export default ({ env }) => ({
  ...  
  documentation: {
    enabled: true,
    openapi: "3.0.0"
    info: {
      version: '0.1.0',
      title: "My custom Title",
      description: "some documentation",
    },
    servers: [
      {
        url: "https://example.com/api",
        description: "Development server"
      },
      {
        url: "http://localhost:1337/api",
        description: "Localhost"
      }
    ],
  },
  ...
});

```
3. Start development server
4. Open documentation and see that none of configs are applied

### Expected behavior

Config for documentation is applied, and custom settings are seen

### Code snippets

See reproduction steps above

**Comment by Boegie19** [comment]
You forgot the config key aka it should be 

```js
export default ({ env }) => ({
  ...  
  documentation: {
    enabled: true,
    config: {
      openapi: "3.0.0"
      info: {
        version: '0.1.0',
        title: "My custom Title",
        description: "some documentation",
      },
      servers: [
        {
          url: "https://example.com/api",
          description: "Development server"
        },
        {
          url: "http://localhost:1337/api",
          description: "Localhost"
        }
      ],
    },
   }
  ...
});
```

**Comment by adrianjarc** [comment]
@Boegie19 thanks for the answer. I have completely missed that. Now it is working. 

Thank you.
