### ISSUE TITLE
STRAPI_ADMIN Environment Variables are not changeable post build for plugin

### ISSUE THREAD

**Issue by PrinzJuliano** [strapi/strapi#16687]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.10.2
- Database: mariadb:10.6.11
- Operating system: Linux Alpine / macOS
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I develop a plugin for strapi. The Plugin creates a custom Field. The custom field relies on data from a third party, which requires an API Key.

When using `process.env.STRAPI_ADMIN_MY_PLUGIN_API_KEY` I found a bug / unexpected behavior.
While developing the Plugin with the env file present during build time, the environment variable is loaded (both in development and production).
When building the docker image without the environment file present, `process.env.STRAPI_ADMIN_MY_PLUGIN_API_KEY` is undefined despite the key being set in the `.env` file.
The only keys available are:
```js
{
  ADMIN_PATH: "/admin/",
  NODE_ENV: "production",
  STRAPI_ADMIN_BACKEND_URL: "",
  STRAPI_TELEMETRY_DISABLED: undefined
}
```

### Steps to reproduce the behavior

1. Setup Strapi
2. Follow the guide in https://docs.strapi.io/dev-docs/plugins-development
3. Follow the guide in https://docs.strapi.io/dev-docs/custom-fields#components
4. Create a new Component to be used as field (e.g. https://github.com/strapi/strapi/blob/main/packages/plugins/color-picker/admin/src/components/ColorPicker/ColorPickerInput/index.js#L71-L82)
5. Define a custom environment variable `STRAPI_ADMIN_MY_PLUGIN_API_KEY` in a `.env` file.
6. In the component, `console.log(process.env.STRAPI_ADMIN_MY_PLUGIN_API_KEY)`
7. Build the plugin, build the admin UI (Since the `.env` file is present the STRAPI_ADMIN_MY_PLUGIN_API_KEY should be defined)
8. Change the key in the .env file: It does not result in any changes on the plugin side.
9. Remove the .env file
10. Build the plugin, build the admin UI
11. The environment variable STRAPI_ADMIN_MY_PLUGIN_API_KEY is no longer available.

### Expected behavior

When using a `STRAPI_ADMIN` prefixed environment variable, it should be present in any Admin UI component, regardless of it being set during build time or not. The environment variable should remain changeable post build.

**Comment by derrickmehaffy** [comment]
Duplicate: https://feedback.strapi.io/developer-experience/p/configure-strapi-backend-url-after-build
