### ISSUE TITLE
Error on User Profile Page (blank page)

### ISSUE THREAD

**Issue by tobecwb** [strapi/strapi#16683]
### Required System information
- Node.js version: 18.16.0
- NPM version: 9.6.5
- Strapi version: 4.10.4
- Database: SQLite
- Operating system: Windows 10 (x64) - 19045.2846
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Create a Quickstart project following the tutorial (https://docs.strapi.io/dev-docs/quick-start), using the following command:
`npx create-strapi-app@latest my-project --quickstart`

After Strapi started, create a new user, and logged on admin page.
Clicked on right bottom corner, then Profile (http://localhost:1337/admin/me), and a blank page appears.
Looking at browser console, got the following errors:

```
TypeError: Cannot read properties of null (reading 'toString')
    at R (main.31bdf27e.js:2237:963)
    at gc (main.31bdf27e.js:779:54213)
    at or (main.31bdf27e.js:783:9048)
    at Fd (main.31bdf27e.js:783:985)
    at rc (main.31bdf27e.js:783:913)
    at nu (main.31bdf27e.js:783:767)
    at Nd (main.31bdf27e.js:781:10915)
    at main.31bdf27e.js:779:39157
    at E.unstable_runWithPriority (main.31bdf27e.js:855:3981)
    at Pi (main.31bdf27e.js:779:38935)
overrideMethod @ react_devtools_backend_compact.js:2367
Au @ main.31bdf27e.js:781
M.callback @ main.31bdf27e.js:781
$s @ main.31bdf27e.js:779
Kd @ main.31bdf27e.js:781
lf @ main.31bdf27e.js:783
E.unstable_runWithPriority @ main.31bdf27e.js:855
Pi @ main.31bdf27e.js:779
Vl @ main.31bdf27e.js:783
Nd @ main.31bdf27e.js:781
(anônimo) @ main.31bdf27e.js:779
E.unstable_runWithPriority @ main.31bdf27e.js:855
Pi @ main.31bdf27e.js:779
Hi @ main.31bdf27e.js:779
Gr @ main.31bdf27e.js:779
Od @ main.31bdf27e.js:781
(anônimo) @ main.31bdf27e.js:790
Promise.then (assíncrono)
me @ main.31bdf27e.js:790
b.flush @ main.31bdf27e.js:790
b.batch @ main.31bdf27e.js:790
g.dispatch @ 3816.2b58bc1a.chunk.js:24
g.setData @ 3816.2b58bc1a.chunk.js:24
onSuccess @ 3816.2b58bc1a.chunk.js:24
L @ main.31bdf27e.js:790
Promise.then (assíncrono)
H @ main.31bdf27e.js:790
O @ main.31bdf27e.js:790
g.fetch @ 3816.2b58bc1a.chunk.js:24
Ke.executeFetch @ main.31bdf27e.js:790
Ke.onSubscribe @ main.31bdf27e.js:790
d.subscribe @ main.31bdf27e.js:790
(anônimo) @ main.31bdf27e.js:790
cf @ main.31bdf27e.js:783
E.unstable_runWithPriority @ main.31bdf27e.js:855
Pi @ main.31bdf27e.js:779
_u @ main.31bdf27e.js:783
(anônimo) @ main.31bdf27e.js:783
ge @ main.31bdf27e.js:855
W.port1.onmessage @ main.31bdf27e.js:855
main.31bdf27e.js:2237 Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at R (main.31bdf27e.js:2237:963)
    at gc (main.31bdf27e.js:779:54213)
    at or (main.31bdf27e.js:783:9048)
    at Fd (main.31bdf27e.js:783:985)
    at rc (main.31bdf27e.js:783:913)
    at nu (main.31bdf27e.js:783:767)
    at Nd (main.31bdf27e.js:781:10915)
    at main.31bdf27e.js:779:39157
    at E.unstable_runWithPriority (main.31bdf27e.js:855:3981)
    at Pi (main.31bdf27e.js:779:38935)
```

### Steps to reproduce the behavior
1. Create a new project with command `npx create-strapi-app@latest my-project --quickstart`
2. Create a first user / admin.
3. On Admin panel, click on "Username", then in "Profile."
4. See error on browser console

### Expected behavior
Show user profile.

### Additional context
The first time I tried the quickstart, the profile page worked.
After that, I deleted the entire directory, create a new project with another name (tried again with same name), tried on another browser and cleared the cache, but got no success.

**Comment by tobecwb** [comment]
Tried again with following commands:

**Command**:
`npx create-strapi-app@latest my-project --quickstart`
**Result**: user profile not working.

**Command**:
`npx create-strapi-app@v4.10.2 my-project --quickstart`
**Result**: user profile working

**Comment by tobecwb** [comment]
Tested on another machine (Ubuntu on WSL)... got the same results:
v4.10.2, the user profile is working.
v4.10.4, user profile it's not working.

**Comment by joshuaellis** [comment]
I think the wrong version of the design-system got into the latest release.

We'll review internally tomorrow and figure out how we'll address this.

Thanks for the report 😊

**Comment by MateuszLas421** [comment]
the same isssue on Typescript
