### ISSUE TITLE
There is no alpha13 of strapi-bookshelf

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1668]
**What is the current behavior?**
So, trying to migrate to new version due to migration guide found this thing

![image](https://user-images.githubusercontent.com/15520510/43443228-f277ef6a-94a8-11e8-822d-b5ead53c4828.png)

But on npm of strapi-bookshelf we don't have 3.0.0-alpha13 and the same with strapi-knex.

![image](https://user-images.githubusercontent.com/15520510/43443362-51b74818-94a9-11e8-97e6-1a22d5b234ee.png)

**What is the expected behavior?**

Please, be more careful when you are writing migration guide.

**Comment by dulgeoion** [comment]
Okay, found that I had to add new dependency `strapi-hook-bookshelf`. You could mention in migration guide that it is not only about `mongoose` hook, but `bookshelf` to.

**Comment by lauriejim** [comment]
Hello @dulgeoion I update the wiki to precise it's also needed for `strapi-bookshelf` and `strapi-knex`
