### ISSUE TITLE
Duplicated links (many-to-many relationship)

### ISSUE THREAD

**Issue by avdeyev** [strapi/strapi#1669]
**Informations**
- **Node.js version: 10.7.0**:
- **npm version: 6.1.0**:
- **Strapi version: v3.0.0-alpha.13.0.1**:
- **Database: MongoDB 4.0.0**:
- **Operating system: CentOS Linux release 7.5.1804**:

I have created a very simple relationship and I have got this:
![1png](https://user-images.githubusercontent.com/3809273/43454206-f87bffde-94c4-11e8-9d3e-60dd509008c4.png)
![2](https://user-images.githubusercontent.com/3809273/43454211-fbe08a5a-94c4-11e8-8b22-1adfd1ab4b03.png)

How to reproduce:
I am using content manager in admin panel

1. Add two content types: for example project, employee
2. Set relationship between them (many-to-many) - I was using content type of 'Project' for that
3. Add project, add test employees
4. Select project, add employee (User 1) - LOOKS GOOD
5. Select employee (User 2) - connect to the same project.
6. The result on the pictures above

What I'm getting from api:
`[{
    "employees": [{
        "_id": "5b60362b2dbcaa2a34035ab1",
        "name": "User 1",
        "createdAt": "2018-07-31T10:12:59.053Z",
        "updatedAt": "2018-07-31T10:19:23.451Z",
        "__v": 0,
        "id": "5b60362b2dbcaa2a34035ab1",
        "projects": null
    },
    {
        "_id": "5b60362b2dbcaa2a34035ab1",
        "name": "User 1",
        "createdAt": "2018-07-31T10:12:59.053Z",
        "updatedAt": "2018-07-31T10:19:23.451Z",
        "__v": 0,
        "id": "5b60362b2dbcaa2a34035ab1",
        "projects": null
    },
    {
        "_id": "5b60362e2dbcaa2a34035ab2",
        "name": "User 2",
        "createdAt": "2018-07-31T10:13:02.979Z",
        "updatedAt": "2018-07-31T10:19:36.657Z",
        "__v": 0,
        "id": "5b60362e2dbcaa2a34035ab2",
        "projects": null
    }],
    "_id": "5b6036252dbcaa2a34035ab0",
    "name": "Project 1",
    "createdAt": "2018-07-31T10:12:53.402Z",
    "updatedAt": "2018-07-31T10:19:36.662Z",
    "__v": 0,
    "id": "5b6036252dbcaa2a34035ab0"
}]`

I guess those dublicates are not expected.
We can remove them directly from relation (select one) and save. And it will work.

I would appriciate any help.

**Comment by lauriejim** [comment]
It has been fixed in this PR https://github.com/strapi/strapi/pull/1675

**Comment by sozedk** [comment]
@lauriejim Sorry for bringing an old thread alive, but it is the closest I found to an issue I have now. While I understand that this issue should be fixed somehow it gives another issue - I have a manyToMany relation where I would like to allow dublicates, imagine a training program split into sessions, where each sessions contains one or more exercises (e.g. E1, E2, E1, E3, E1, E4). As it is now each session needs 3 (or more) manyToMany relations but this is not very flexible and as far as I can see each row in the DB relation table has a unique key so this is not the issue. Could this be fixed or what would be the alternative solution?
