### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')  

### ISSUE THREAD

**Issue by durchdenmonsum** [strapi/strapi#16696]
### Required System information

- Node.js version:16.17.0
- NPM version:8.15.0
- Strapi version:4.10.5
- Database:Mysql
- Operating system:CentOS 7.9.2009 x86_64
- Is your project Javascript or Typescript:Javascript 

### Describe the bug

After the account is logged in, the page is blank and the console reports an error

### Screenshots
![image](https://github.com/strapi/strapi/assets/42568320/e8f4f242-6c92-480a-9566-7ca6cb5d11e6)
![image](https://github.com/strapi/strapi/assets/42568320/a3548976-0750-4135-b520-5f810df6f021)

**Comment by gu-stav** [comment]
@durchdenmonsum Do you have any other plugins installed? It looks to me as if something is logging something. If not: could you please send us a non-minified stack-trace? From the screenshot it is impossible to know what went wrong.

**Comment by durchdenmonsum** [comment]
@gu-stav    Sorry, I'm still a newbie, you can log in and try it yourself
domin:https://www.durchdenmonsum.cn/admin
E-mail:87730848@qq.com
Password:im9nwwBL723?

**Comment by gu-stav** [comment]
@durchdenmonsum Please don't share login credentials in public, if you don't want your site to be taken over.

**Comment by Boegie19** [comment]
mind doing the following to help us out?  if you can add webpack.config.js to src/admin with this:

```js
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config
  config.devtool = 'source-map';
  return config;
};
```
this will source map the error and make it easier for us to find where the error is.

**Comment by durchdenmonsum** [comment]
I've added the code the way you did and rebuild, what should I do next?
![image](https://github.com/strapi/strapi/assets/42568320/7a1f6acc-85e3-403e-a67f-12f7253d6c63)

**Comment by gu-stav** [comment]
@durchdenmonsum Unfortunately, I am not able to reproduce your issue. Could you share your content-types / schema with us please? It might also help if you could share any other plugins you might have installed.

**Comment by gu-stav** [comment]
@Marc-Roig I've replied above too :) The only thing I can think of is that there are no collection-types, which is IMO impossible from the UI, but I don't know what would happen if you delete all of them manually.

**Comment by trsh** [comment]
@durchdenmonsum  did you figure it out? I am having exact same issue. Happened when I switched my server to https.

**Comment by edu-amr** [comment]
any solved it?
