### ISSUE TITLE
Allowing the search to search by specific relationship. 

### ISSUE THREAD

**Issue by Glenncito** [strapi/strapi#167]
It would be great if I could customise the search to allow to search by specific property, such as relationship (parent) or any other specific property. 

Example:

I want to return all 'lesson' entries that have 'Trigonometry' as its relationship value for relationship attribute, 'Section'

or

I want to search for all entries with 'createdBy' attribute with the value of my username.

**Comment by Aurelsicoko** [comment]
Thanks for the suggestion! It could be interesting for the new dashboard. It will not be implemented in the current version, though.

I add an `enhancement` label to assign this issue to future milestones.

**Comment by lauriejim** [comment]
I update the name of this issue because we can search by attributes. See filters documentation
