### ISSUE TITLE
Pressing Enter on a Custom Field TextInput always saves content.

### ISSUE THREAD

**Issue by xenobytezero** [strapi/strapi#16733]
### Required System information

- Node.js version: v16.15.0
- Strapi version: v4.10.5
- Database: Sqlite
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have built a custom field component, which includes a `<Searchbar>` component used for searching a 3rd party API. When the user hits Enter on the search bar, my code uses `onKeyPress()` to look for Enter keypresses to do the search. 

Even with an immediate `ev.stopPropagation();`, it seems like the Enter press makes it up the Component tree and does the equivilent of me hitting the Save button.

This appears to be the default behaviour of all the TextInput based components (including the InputUID).

Is there anyway to stop this from happening?

**Comment by joshuaellis** [comment]
Please make sure you fill out the template, especially steps to reproduce etc. so we can look into this better, if you're using custom code it's typically better to supply a reproduction of your issue as opposed to written steps.
