### ISSUE TITLE
Being able to set the default collapsed state on a dynamic zone field

### ISSUE THREAD

**Issue by TheSpiderPP** [strapi/strapi#16737]
Hi! 👋 
      
Firstly, thanks for your work on this project! So far Strapi serves all of my needs🙂There is one detail though that could improve the experience.

I have a dynamic zone with sometimes more than 15 components. All of which have a good number of fields. The panels in the dynamic zone are open by default, but I would like to have them collapsed so it's easier to scroll to the component I wish to change. Right now I made a temporary patch to collapse them

Here is the diff I made with patch-package that solved my problem:

```diff
diff --git a/node_modules/@strapi/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js b/node_modules/@strapi/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
index 21e81e9..f7fe4b9 100644
--- a/node_modules/@strapi/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
+++ b/node_modules/@strapi/admin/admin/src/content-manager/components/DynamicZone/components/DynamicComponent.js
@@ -84,7 +84,7 @@ const DynamicZoneComponent = ({
   onDropItem,
   onCancel,
 }) => {
-  const [isOpen, setIsOpen] = useState(true);
+  const [isOpen, setIsOpen] = useState(false);
   const { formatMessage } = useIntl();
   const { getComponentLayout } = useContentTypeLayout();
   const { modifiedData } = useCMEditViewDataManager();
```

Is it possible to extend the dynamic field with a setting that allows selecting the default isOpen state for panels?

**Comment by abrorAbdullaev** [comment]
Apparently at strapi5 now the dynamic zone is collapsed by default, but not for strapi4
So here is a plugin that gets dynamic zone collapsed by default for strapi4 if someone needs it

https://market.strapi.io/plugins/strapi-plugin-collapse-dynamic-zone
