### ISSUE TITLE
Media library folders and files can get unintentionally deleted

### ISSUE THREAD

**Issue by dan-strandberg** [strapi/strapi#16734]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.10.5
- Database: SQLite
- Operating system: macOS Monterey
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Critical issue in remove logic for folders in media library. The first folder that's created in root get a path of "/1", the second get path of "/2". At some point we have created enough folders to reach double digits, with path "/10", "/11" and so on. If we delete the first folder with path "/1" then folders with path "/10-/19" gets deleted as well.

The SQL queries uses startsWith and path "/10-/19" all starts with "/1":
https://github.com/strapi/strapi/blob/main/packages/core/upload/server/services/folder.js#L54-L70

Might be related to https://github.com/strapi/strapi/issues/16125 

### Steps to reproduce the behavior

1. Setup a new project 
2. Create 10-20 folders in media library root
3. Remove the first folder that was created
4. Observe that other folders that has a path starting with "/1" will be removed as well

### Expected behavior

To not remove folders and files that was not intentional

### Screenshots

https://github.com/strapi/strapi/assets/91525096/7a40c059-8e26-474f-85b2-8cc39924ad74

**Comment by Marc-Roig** [comment]
Hello, indeed this is probably related to https://github.com/strapi/strapi/issues/16125 . I will start working on this asap.

**Comment by Marc-Roig** [comment]
@fogge that helps a lot! Thank you for spending the time on this, I want to fix this asap and release it next week.
We have an opened PR with a similar solution as yours now! https://github.com/strapi/strapi/pull/16759 Feel free to comment there if you see anything :)
