### ISSUE TITLE
Refresh JWT route

### ISSUE THREAD

**Issue by yusufiga** [strapi/strapi#1676]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 6.2.0
- **Strapi version**: 13.0.1
- **Database**: mysql
- **Operating system**: Debian

**What is the current behavior?**

Hi, I'm trying to use strapi as a backend for my Android project but I have a question regarding JWT. How can I refresh JWT before it expires without requesting user to login again? I can not just ask my app users to login every month. It doesn't fit to mobile app flow.

**Steps to reproduce the problem**

**What is the expected behavior?**
There should be an api to refresh JWT with existing token.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @yusufiga. This feature actually not exist.

We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
@yusufiga Strapi uses an Auth0 Lib for the handling of JWT. There is an entry on its README.md: https://github.com/auth0/node-jsonwebtoken#refreshing-jwts

With some links to an example, an issue, and a PR.
https://gist.github.com/ziluvatar/a3feb505c4c0ec37059054537b38fc48
https://github.com/auth0/node-jsonwebtoken/issues/122
https://github.com/auth0/node-jsonwebtoken/pull/172

But I do agree that a non-refreshing token and logging in every 30 days on an app would be mildly annoying.

**Comment by yusufiga** [comment]
Thanks for hint @derrickmehaffy. Unfortunately without refresh JWT authentication is pretty much useless for mobile. Since I'm not familiar with nodejs or koa, it would be nice if someone can just help me to get refresh JWT feature to strapi.

**Comment by bahdcoder** [comment]
@lauriejim, @derrickmehaffy  are you working on this? If not, I can have a look and implement this feature.

**Comment by derrickmehaffy** [comment]
@bahdcoder No I feel this is probably above my skill level, but it would be nice to have. I know some of the OAuth providers also provide refresh keys (Discord comes to mind) So those should also be taken into account.

If you're up to take a look, it would be really awesome. :)

**Comment by lauriejim** [comment]
Hello @bahdcoder, we are not working on this feature. We will appreciate your contribution on this feature !

**Comment by derrickmehaffy** [comment]
the alternative (and quite a terrible and insecure way to handle it) @yusufiga is to cache their login information and refresh the token on the app side.

**Comment by yusufiga** [comment]
@derrickmehaffy Yes it's an alternative but as a user I wouldn't agree on keeping password on the device. I mean I can keep it encrypted but still it's not nice to keep user's password somewhere in the device.

**Comment by derrickmehaffy** [comment]
I agree completely @yusufiga even encrypted it really shouldn't be stored on the device, just wanted to offer it as a temporary solution until something more proper comes into play.

I am hitting a similar issue with my desktop application :stuck_out_tongue_winking_eye:

**Comment by yusufiga** [comment]
Hi, @bahdcoder are you working on this? It would be nice if you can give a comment if you are not working on it so someone else can take a look. I still desperately need this feature :D Thanks.

**Comment by Aurelsicoko** [comment]
I agree that we should support this feature. There is a public card on Product Board (https://portal.productboard.com/strapi/c/34-refresh-token-jwt), feel free to upvote it and give me more insights.

**Comment by deeq14** [comment]
@Aurelsicoko any progress on this? thought it is an essential feature

**Comment by Aurelsicoko** [comment]
@deeq14 The roadmap is up-to-date and we don't plan to work on this feature this year. However, we would love to see someone in the community trying to implement it 👍

**Comment by derrickmehaffy** [comment]
FYI @Aurelsicoko @deeq14 there is a PR for this already: https://github.com/strapi/strapi/pull/2704

**Comment by fabio-nettis** [comment]
You could definitly handle this on the application side of your project:

When the API returns that the JWT is invalid you'll need to do a background login (maybe via a service?) again and then fetch the updated JWT and user-data into the storage of the application.

This requires you to save the username and password (encrypted!) on the users device. For the time beeing this seems like a reasonable logic.

**Comment by nuno-vieira** [comment]
Why not just increase the expiration of the JWT Token for the mobile app? Since this token will be encrypted on the device it is safer than storing it in a cookie or local storage. Maybe would be nice to control the expiration of the JWT Token

**Comment by tudorilisoi** [comment]
@lauriejim and everybody else :)
The only issue about refreshing the token is storing the hashed password within the token and verifying that upon verifying the token.
Why?
Suppose:
- an user logs in then the mobile device/app gets a token
- the token gets stolen (along with the device or otherwise)
Now what you have is a valid token on a stolen device
If you change Strapi to also store the password hash in the token (which is encrypted is anyway and **only the server knows how to decrypt it**), what happens is:
- the user changes password
- the stolen devices tries to access the API
- the server decodes the token, verifies the password hash within the token against user's password hash
- the old token gets a 401 access denied

Now for the refresh part, as long as you (as an user) don't change your password, you just #send a non-expired token to `/refresh` and you get a new one, essentially prolonging expiration

Just keep in mind only the server can decode the JWT, so its safe to store anything in there

**Comment by vatologic** [comment]
I've been following the project thus far and it works like a charm. However the lack for JWT refresh tokens is kind of a dealbreaker for me for the obvious security reasons. So, a big +1 on this feature; would put the icing on the Strapi cake ;)

**Comment by derrickmehaffy** [comment]
> I've been following the project thus far and it works like a charm. However the lack for JWT refresh tokens is kind of a dealbreaker for me for the obvious security reasons. So, a big +1 on this feature; would put the icing on the Strapi cake ;)

They are certainly taking that into consideration (AFAIK the new RBAC will be using refresh for the admin panel, so I'm sure adding support for it in the normal generated routes will be a focus on v4, and it might be backported to v3 we will have to wait and see)

**Comment by darron1217** [comment]
I've implement it by extending plugin.
Here's my example.

config/routes.json
```json
{
  "routes": [
    {
      "method": "POST",
      "path": "/auth/refresh-token",
      "handler": "Auth.refreshToken",
      "config": {
        "prefix": "",
        "policies": []
      }
    }
  ]
}
```

schema.graphql.js
```js
const _ = require('lodash');

/**
 * Throws an ApolloError if context body contains a bad request
 * @param contextBody - body of the context object given to the resolver
 * @throws ApolloError if the body is a bad request
 */
function checkBadRequest(contextBody) {
  if (_.get(contextBody, 'statusCode', 200) !== 200) {
    const message = _.get(contextBody, 'error', 'Bad Request');
    const exception = new Error(message);
    exception.code = _.get(contextBody, 'statusCode', 400);
    exception.data = contextBody;
    throw exception;
  }
}

module.exports = {
  definition: /* GraphQL */ `
    type UsersPermissionsRefreshTokenPayload {
      jwt: String!
    }
  `,
  mutation: `
    refreshToken(jwt: String!): UsersPermissionsRefreshTokenPayload!
  `,
  resolver: {
    Mutation: {
      refreshToken: {
        description: 'Refresh JWT Token',
        resolverOf: 'plugins::users-permissions.auth.refreshToken',
        resolver: async (obj, options, { context }) => {
          context.query = _.toPlainObject(options);

          await strapi.plugins['users-permissions'].controllers.auth.refreshToken(context);
          let output = context.body.toJSON ? context.body.toJSON() : context.body;

          checkBadRequest(output);

          return output;
        },
      },
    },
  },
};
```

controllers/Auth.js
```js
'use strict';

/**
 * Auth.js controller
 *
 * @description: A set of functions called "actions" for managing `Auth`.
 */

/* eslint-disable no-useless-escape */
const _ = require('lodash');

module.exports = {
  async refreshToken(ctx) {
    const params = _.assign(ctx.request.body);
    // Parse Token
    try {
      const { id } = await strapi.plugins['users-permissions'].services.jwt.verify(params.jwt);
      const user = await strapi.query('user', 'users-permissions').findOne({ id });
      ctx.send({
        jwt: strapi.plugins['users-permissions'].services.jwt.issue({
          id: user.id,
        }),
      })
    } catch (e) {
      console.log(e)
      return ctx.badRequest(null, 'Invalid token')
    }

  },
};
```

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/renew-jwt-token/2665/3

**Comment by jacargentina** [comment]
@darron1217  I tried your code: it requires the sent token to be valid (not expired yet) right?
My idea was to allow a refresh for an already logged in user.

**Comment by aquadesk** [comment]
Best practice for refresh token is to use http only cookie and it could be restrictive since it involes cors and cookie settings. Currently i have my own logic built on graphql plugin and it works great

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/refresh-token
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
