### ISSUE TITLE
How to Add Audit Logs feature in strapi

### ISSUE THREAD

**Issue by maruthasalamr** [strapi/strapi#16769]
As a Strapi admin i need to track the user activities and capture the logs in the separte collection type.I need to add Audi Logs fetaure in strapi Admin panel.Please help me on this 

Required System information

- Node.js version: v14.19.1
- NPM version:9.2.0
- Strapi version:4.9.1
- Strapi Plan - Enterprise Edition (EE)
- Database:postgres
- Operating system:Mac Os
- Is your project Javascript or Typescript: Javascript

**Comment by derrickmehaffy** [comment]
Hi @maruthasalamr can you please open a ticket via the support portal (https://support.strapi.io) or email support@strapi.io
