### ISSUE TITLE
413 - PayloadTooLargeError - Uploading Big Files

### ISSUE THREAD

**Issue by oaragones** [strapi/strapi#16792]
### Required System information

- Node.js version: v18.14.0
- NPM version: 9.3.1
- Strapi version: 4.10.1
- Database: sqlite
- Operating system: Windows 11
- Project in Javascript.

### Describe the bug

Dear all, when w etry to upload a big file ( 1,6GB ) we have an unexpected behaviour.

`{"data":null,"error":{"status":413,"name":"PayloadTooLargeError","message":"230516_VideoEspera_SOL.mov exceeds size limit of 1 GB.","details":{}}}`

We try to modify the `config/middlewares.js` with:

```js
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
   {
    name: "strapi::body",
    config: {
      enabled: true,
      multipart: true,
      textLimit: 10*1024*1024*1024,
      formLimit: 10*1024*1024*1024,
      jsonLimit: 10*1024*1024*1024,
      includeUnparsed: true,
      formidable: {
        maxFileSize: 10*1024*1024*1024 // 10 GB
      },
      providerOptions: {
        sizeLimit:10*1024*1024*1024 // 10 GB
      }
    },
  },
  
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

We are reading that can be from node side... how we can proceed to resolve it?

Thanks in advance,

### Steps to reproduce the behavior

1. Try to load the same middleware file.
2. Try to upload a big file (over 1,6GB)

### Expected behavior

We expect to upload the content from big files.

### Screenshots

![image](https://github.com/strapi/strapi/assets/87125/4f436e36-c507-4df7-9223-8cfaa45984e9)

**Comment by oaragones** [comment]
Another test done with:

[strapi-provider-upload-local-extra](https://www.npmjs.com/package/strapi-provider-upload-local-extra) 

Without success...

**Comment by oaragones** [comment]
Hello,

We download again a fresh new Strapi from npm.

We make the middleware configuration as:

```js
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
   {
    name: "strapi::body",
    config: {
      enabled: true,
      multipart: true,
      textLimit: 10*1024*1024*1024,
      formLimit: 10*1024*1024*1024,
      jsonLimit: 10*1024*1024*1024,
      includeUnparsed: true,
      formidable: {
        maxFileSize: 10*1024*1024*1024 // 10 GB
      },
      providerOptions: {
        sizeLimit:10*1024*1024*1024 // 10 GB
      }
    },
  },
  
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

And the same errors appears:

The first upload steps seems to work fine:

![image](https://github.com/strapi/strapi/assets/87125/1401768f-92d9-4a0c-a6a3-5a53d57d2d5e)

then :

![image](https://github.com/strapi/strapi/assets/87125/ce8afc91-11ff-4ffc-aba5-68e3fd945965)


the RAW json response is the same...

```json
{"data":null,"error":{"status":413,"name":"PayloadTooLargeError","message":"230516_VideoEspera_SOL.mov exceeds size limit of 1 GB.","details":{}}}
```

We attache a new wetransfer with the current file:

https://we.tl/t-vZoRMgaCIP

We don't know if you change something else? Please can your share with us you strapi installation configuration? (strapi version, node version, etc...)

**Comment by oaragones** [comment]
It is possible to upload a big file into strapi system in another way?

**Comment by oaragones** [comment]
More information...

If we run :

`yarn develop --watch-admin`

This screens appears:

![image](https://github.com/strapi/strapi/assets/87125/6b2bdd2b-9c19-4296-81d3-f1baa3f04100)

![image](https://github.com/strapi/strapi/assets/87125/c268d2df-1d31-4b74-8621-c6d38377fea9)

Please, how can we proceed?

**Comment by Marc-Roig** [comment]
hello, that error is thrown by the upload provider, when the sizeLimit is excedeed, so two things can be happening here:

- Size limit is not configured in `config/plugins.js`:
```
upload: {
    config: {
        provider: 'strapi-provider-upload-local-extra',

        providerOptions: /** @type {UploadLocalExtraOptions} */({
            /**
             * @param {LocalProperties} props
             * @returns string
             */
           sizeLimit:10*1024*1024*1024, // 10 GB,
            getLocalPath: props => `uploads/${props.hash}${props.ext}`
        })
    },
}
```

- The upload provider you are using has a 1GB hardcoded limit for files. Which seems the case, https://www.npmjs.com/package/strapi-provider-upload-local-extra says the default is at 1GB, so it seems the problem is the configuration is not getting there.
I would replace this provider for the default local provider, contact the provider owner to fix the issue, or create a custom provider if you need some functionality that you can not get by using the default provider.

**Comment by oaragones** [comment]
Dear Marc, 

We install a fresh strapi without any kind of plugin or upload provider...

Can you share with us your configuration? 

We are working with our own machine... no external hosting services, no external plugins... only strapi itself.

**Comment by Marc-Roig** [comment]
based on the provider config, it seems as it you were using `strapi-provider-upload-local-extra` provider.

Can you try this configuration?
`config/plugins.js`
```
  upload: {
    config: {
      sizeLimit: 10*1024*1024*1024,
    },
  },
```

This works for me.

**Comment by oaragones** [comment]
Dear Marc,

First of all, thanks for your effort, patience and dedication.

Now it seems to work correctly.

We appreciate so hard your support!

Very thanks for all!

Best,

**Comment by Marc-Roig** [comment]
🙌  I appreciate a lot those words, community people like you make this easy :)
