### ISSUE TITLE
Data loss when exporting / importing 

### ISSUE THREAD

**Issue by nagman** [strapi/strapi#16813]
### Required System information

- Node.js version: 18.15.0
- Yarn version: 1.22.19
- Strapi version: 4.10.5
- Database: SQLite
- Operating system: MacOS for local env / node:18-alpine for remote env
- Is your project Javascript or Typescript: Typescript

### Describe the bug

As long as [the issue with `strapi transfer`](https://github.com/strapi/strapi/issues/16473) isn't resolved, I must migrate my data from my local env to my remote env with `strapi export` and `strapi import`.

However, once the migration has completed, all the medias inside components have disappeared.  
Same for all the relations inside components.  
In short: all relations between tables are erased if they are inside components.

And this happens every time.

### Steps to reproduce the behavior

0. Ensure you have a component with a relation field (a media field or a relation to another collection) and fill it with data
1. Run `strapi export --no-encrypt` on your local environment
2. Copy the backup file to your remote environment
3. On your remote env, run `strapi import -f backup.tar.gz --force` (replace backup with the name of your backup)
4. Notice the relation field is empty on the remote strapi

### Expected behavior

Relations should be kept even if they are nested in components.

### Screenshots

| What is backed up: | What is restored: |
| --- | ---- |
| ![image](https://github.com/strapi/strapi/assets/16116486/3b26b86f-1d5f-462f-8f3b-94d85fb49d83) | ![image](https://github.com/strapi/strapi/assets/16116486/d88832d6-fcef-49c8-af5e-c29c62e44137) |
| ![image](https://github.com/strapi/strapi/assets/16116486/94d1f5fd-f26f-4fd8-b53f-fdf52229bde3) |  ![image](https://github.com/strapi/strapi/assets/16116486/5ffc740c-e7e3-4713-a8d0-a948900c763c) |

### Additional context

I must precise that I sometimes got around the limit of 2 nested components (we can't create a component inside a component inside a component) by editing the json files [as specified here.](https://feedback.strapi.io/customization/p/allow-nesting-of-components-more-than-2-levels-deep#:~:text=Released%20in%20v4.2.0.%20The%20content%2Dtype%20builder%20will%20still%20limit%20you%20to%202%20levels%20however%20you%20can%20add%20additional%20levels%20by%20manually%20editing%20the%20schema.json%20files.)

However, the bug happens on every component, **no matter if it's nested or not.**

**Comment by ZirixCZ** [comment]
I am having the same issue on 4.10.5. Downgrading both local strapi and remote solved the issue.

**Comment by nagman** [comment]
Tested with `4.10.7`, still not working.

**Comment by skyZcoding** [comment]
Facing the same issue the only difference is that we're using postgres ( using as well 4.10.7 ).

**Comment by ZirixCZ** [comment]
We're using postgres as well.

**Comment by maxostarr** [comment]
Also having this issue on v4.10.6 with postgres.

**Comment by Lurow** [comment]
Tested it with postgres on `4.11.1`, still not working.

**Comment by uplShreya** [comment]
I am  also having the same issue with strapi version10

**Comment by derrickmehaffy** [comment]
Closing this in favor of https://github.com/strapi/strapi/issues/17343
