### ISSUE TITLE
Collection type relationships missing after CLi Transfer

### ISSUE THREAD

**Issue by chrisyaxley** [strapi/strapi#16811]
### Required System information

- Node.js version: **v16.20.0**
- NPM version: **8.19.3**
- Strapi version: **v4.10.5**
- Database: **SQL**
- Operating system: **macOS=>ASW** & **macOS=>macOS**
- Is your project Javascript or Typescript: **Typescript**

#### Background
We have content/components that are repeated in multiple page. To stop us from adding this content to each page we have a Collection type that stores that content, that is turn is referenced to a component, which is then added to a dynamic zone within a page. This allows us to add multiple new pages, and then add "ConentBlock1" to the dynamic zone of each page. 
#### Bug
When transferring data via the CLi all relationships with Collection Types are lost. 

#### Local instance
<img width="989" alt="Screenshot 2023-05-23 at 12 08 33" src="https://github.com/strapi/strapi/assets/1083918/2b02fed4-3784-40ff-8256-acef37f28e38">

#### Destination instance after transfer
<img width="1015" alt="Screenshot 2023-05-23 at 12 09 13" src="https://github.com/strapi/strapi/assets/1083918/b3d2f02b-960a-4088-8f60-6841b64004c9">

### Steps to reproduce the behaviour
1. Create a Collection type
2. Create a component that has relationship with the above Collection
3. Create a `Page` collection Type
4. Add a `Dynamic Zone` to `Page`
5. Add the component created above to the available components in the `Dynamic Zone`
6. In Content Manager add some data the Collection Type you created, save & publish
7. Add a new page
8. Add content to dynamic zone of page
9. Select the Component above
10. Publish page
11. Ensure content is as expected
12. Perform transfer of data from local instance to remote instance
13. Observe, although the Component in the dynamic Zone is present in the page structure, the link to the instance of that collection type is not. 

### Expected behaviour

Collection Relationships remain intact

#### Successful transfer
<img width="842" alt="Screenshot 2023-05-23 at 12 34 33" src="https://github.com/strapi/strapi/assets/1083918/49e80cae-c859-4f25-82c0-05ddaee5ff43">

**Comment by derrickmehaffy** [comment]
Closing this in favor of https://github.com/strapi/strapi/issues/17343
