### ISSUE TITLE
API rate limit issue since 4.10.x

### ISSUE THREAD

**Issue by ciao-joe** [strapi/strapi#16817]
### Required System information

- Node.js version: 18.13.0
- NPM version: 9.6.7
- Strapi version: 4.10.5
- Database: MySQL
- Operating system: Windows Server 2016
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Since 4.10.x, I am experiencing a rate limit kind of issue in my production server. Whenever my NextJs frontend calls multiple strapi api at the same time, my strapi server will stop responding for around 1 minute, and then allows another few requests until it stop responding again. Below is the logs of the strapi server, my frontend server call these api consecutively, but there are two 1 minute gaps between these calls.
```
[2023-05-24 09:40:42.132] http: GET /api/abc/123 (79 ms) 200
[2023-05-24 09:40:42.149] http: GET /api/users/me (119 ms) 200
[2023-05-24 09:40:43.033] http: GET /api/def (970 ms) 200
[2023-05-24 09:41:44.438] http: GET /api/abc/123 (61 ms) 200
[2023-05-24 09:41:44.449] http: GET /api/users/me (81 ms) 200
[2023-05-24 09:41:45.352] http: GET /api/def (979 ms) 200
[2023-05-24 09:42:47.888] http: POST /api/auth/local (239 ms) 200
[2023-05-24 09:42:47.989] http: GET /api/ghi (31 ms) 200
```
All things get back to normal when I downgrade strapi back to 4.9.2. This only happen since 4.10.x. I tried to delete node_modules and .cache folder and deploy again, still having the same issue. I also tried to play with the rate limit config of the user plugin, nothing change.

### Steps to reproduce the behavior

Upgrade strapi to 4.10.x and call multiple api at the same time

### Expected behavior

No rate limiting issue as 4.9.2

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

My frontend is a NextJs server and it is deployed on the same server as the strapi server. The api requests contains cookies in the header. My production server is Windows Server 2016 and I use pm2 to manage the process.
It seems like I am the only one having this issue and I know it is difficult to reproduce. But I really have no idea how to fix this. Please help.

**Comment by Boegie19** [comment]
Mind adding someting to show the time between request and response of the requests?
