### ISSUE TITLE
GraphQL many-to-many relations not symmetric

### ISSUE THREAD

**Issue by bjnsn** [strapi/strapi#1683]
**Informations**
- Node.js version: 9.9.0
- npm version: 5.6.0
- Strapi version: 3.0.0-alpha.13.0.1
- Database: MongoDB 4.0.0 / x86_64
- Operating system: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-109-generic x86_64)

**What is the current behavior?**
Querying content types that share many-to-many relations do not return expected results.

**Steps to reproduce the problem**
Create two content types: 
`articleTag` which has a field 'name' of type string
`article` which has a field 'articleOverview' of type text (WYSIWIG),
add a many-to-many relation between them

Create one `article` and one` articleTag` and link them with a relationship.

Compare these two queries, where `article` has a many-to-many relation with `articleTag`:
```
{
  articles {
    articleOverview
    articleTags {
      name
    }
  }
}
```
and 
```
{
  articletags {
     name
     articles {
     		articleOverview     		
    } 
  }
}
```
with their respective responses:
```
{
  "data": {
    "articles": [
      {
        "articleOverview": "Something",
        "articleTags": [
          {
            "name": "Access"
          }
        ]
      }
    ]
  }
}
```
and
```
{
  "data": {
    "articletags": [
     {
        "name": "Access",
        "articles": []
      }
    ]
  }
}
```
The first response is as expected, the article has an articleTags collection with a member. However, the reverse is not true in the second response - the articleTag has an articles collection, but that collection has no members.

**What is the expected behavior?**

The second query should include the article:

```
{
  "data": {
    "articletags": [
     {
        "name": "Access",
        "articles": [
          {
            "articleOverview": "Something"
          }
        ]
      }
    ]
  }
}
```

**Suggested solutions**

I don't know enough about the underlying mechanisms to make a valuable suggestion.

Thanks!

**Comment by bjnsn** [comment]
This may be related to camel-case contentType names. I setup a new installation of Strapi using MySQL this time and ran into this error message with a similar query:

```
{
  "data": {
    "articles": [
      {
        "articleTags": null
      }
    ]
  },
  "errors": [
    {
      "message": "Undefined binding(s) detected when compiling SELECT query: select `articletags`.* from `articletags` where `source` = ? and `where` = ? and `sort` = ? and `start` = ? and `limit` = ? and `skip` = ? limit ?",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "articles",
        0,
        "articleTags"
      ]
    }
  ]
}
```

**Comment by lauriejim** [comment]
I think your issue is related to this one https://github.com/strapi/strapi/issues/1139
Can you try to lowercase your content type and attributes please.

**Comment by victorlambert** [comment]
Hey there, I'm having the same issue and my content types and attributes are both lowercase.
Here are the 2 schemas : 
```{
  "connection": "default",
  "collectionName": "study",
  "info": {
    "name": "study",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "missions": {
      "collection": "mission",
      "via": "studies"
    }
  }
}
```
and 
```
{
  "connection": "default",
  "collectionName": "mission",
  "info": {
    "name": "mission",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "studies": {
      "collection": "study",
      "via": "missions",
      "dominant": true
    }
  }
}
```

**Comment by vcolavin** [comment]
@lauriejim I am working on the same codebase as @bjnsn, and I can confirm it's not a casing issue. I've created two new models, `foo` and `bar`, with a many-to-many relationship. They have the same problem.

**Comment by greatwitenorth** [comment]
Also here's some hackey code that seems to fix the issue:

```
if (Array.isArray(queryOpts.query.id.value)){
    queryOpts.query.id.symbol = 'IN';
}
```

When added just above the chuck of code in my previous comment it seems to fix the issue.

**Comment by lauriejim** [comment]
Thank you @greatwitenorth for your investigation, can you submit a PR if you have a fix to offer to the community.

Appreciate.

**Comment by greatwitenorth** [comment]
Just to followup, it looks like my above fix only solves the problem of multiple related models not showing in the nested results for an item. But the original post here was mentioning about the reverse query (when an association is not 'dominant') not showing any results. This case statement seems to be the culprit:

```javascript
case 'manyToMany': {
if (association.dominant) {
  const arrayOfIds = (obj[association.alias] || []).map(related => {
    return related[ref.primaryKey] || related;
  });
  
  // Where.
  queryOpts.query = strapi.utils.models.convertParams(name, {
    // Construct the "where" query to only retrieve entries which are
    // related to this entry.
    [ref.primaryKey]: arrayOfIds,
    ...where.where
  }).where;
  
}
break;
// falls through
}
```

removing the ```if (association.dominant)``` condition seems to fix the problem. I'm not totally sure why it's checking if it's 'dominant' or what that even means. Can anyone here provide some insight as to why that conditional is in there?

**Comment by markcheno** [comment]
Any news on this? I am having the same problem and my app is entirely dependent on a many to many relationship. This one is a deal breaker for me.

**Comment by kamalbennani** [comment]
If the association is dominant we want to grab the IDs from the relation itself otherwise we want to fall through and execute the default behavior which will find all the entries related to given association ID, so the fix would be: (I've already introduced it in this PR: https://github.com/strapi/strapi/pull/1948/files#diff-a056f29ab621b93285370edb48940246)

```JS
case 'manyToMany': {
  if (association.dominant) {
    const arrayOfIds = (obj[association.alias] || []).map(related => {
      return related[ref.primaryKey] || related;
    });
    
    // Where.
    queryOpts.query = strapi.utils.models.convertParams(name, {
      // Construct the "where" query to only retrieve entries which are
      // related to this entry.
      [ref.primaryKey]: arrayOfIds,
      ...where.where
    }).where;

    break;
  }
  // falls through
}
```

**Comment by z-ax** [comment]
Still an issue. Just created 2 types: Publication and Tag, added many-to-many relation and it doesn't respond properly for one of them: publication can query tags, tags can't query publications.

Just in case: Publication has "tags" Array in Mongo when created via admin, none of Tag has "publications".

**Comment by aissa-bouguern** [comment]
When do you think this issue to be fixed ?!!

**Comment by mamartins** [comment]
I'm facing the same issue. I can only query Many to Many from the dominant side of relation, If I query the other side I get:
`Cannot read property 'isMongoId' of undefined`

**Comment by lauriejim** [comment]
Can you try with last version of Strapi (new app and new database) to check if it still happen please.

**Comment by mamartins** [comment]
I'm on latest version and DB too

**Comment by razza12** [comment]
I am also getting the "Cannot read property 'isMongoId' of undefined"
