### ISSUE TITLE
Strapi import with Postgres seems to ignore custom schema

### ISSUE THREAD

**Issue by laagland** [strapi/strapi#16836]
### Required System information

- Node.js version: 16.20.0
- NPM version: 8.19.4
- Strapi version: 4.10.5
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I'm trying to import data that was exported from a different strapi instance. Both strapi instances use the same strapi configuration and the same database configuration. I'm using the same custom database schema for both, defined in database.js.

When importing data I get the following error:

`error: [ERROR] insert into "admin_permissions_role_links" ("permission_id", "permission_order", "role_id") values ($1, $2, $3) - relation "admin_permissions_role_links" does not exist`

But the "admin_permissions_role_links" table exists in the custom schema. 

When changing the configuration of the target instance to not use a custom schema (so it will automatically use the public schema) and rebuild strapi, the import works successfully.

### Expected behavior

Importing should also work with custom postgres schemas

### Screenshots

![error screenshot](https://github.com/strapi/strapi/assets/7661210/fa7aca9f-55ba-406f-b71f-e0830de1948c)

**Comment by derrickmehaffy** [comment]
tested using the experimental that will become `4.12.1`: `0.0.0-experimental.b8add035057504e7feb472f8cc437c83b49e7268`

**Comment by innerdvations** [comment]
For reference once someone gets to this: solution will probably be the same as https://github.com/strapi/strapi/pull/17620 although we should try to find a universal solution so this doesn't keep happening.

**Comment by derrickmehaffy** [comment]
Experimental Version: `0.0.0-experimental.98723a112314341c30a5f2b1fb46125eae3a6503` for testing with (do not recommend this for production!)
