### ISSUE TITLE
DateTime Field unable to be cleared

### ISSUE THREAD

**Issue by michaelcummings** [strapi/strapi#16840]
### Required System information

- Node.js version: 16.13.0
- NPM version: 8.1.2
- Strapi version: 4.9.2
- Database: Postgres 15
- Operating system: Debian 10.9 (Server) MacOS 13.2.1 (User) Brave Browser
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The datetime picker allows you to select a date, and it has an X button that I would expect would clear the date. The hh:mm selector does seem to reset the time back to 00:00, but the date box does not clear at all.

### Expected behavior

I would expect that the value of the date selector would return to null

### Screenshots

![image](https://github.com/strapi/strapi/assets/46293/f238e2aa-1a86-4206-8fdb-0ebb48fcc7c9)

**Comment by N-NeelPatel** [comment]
@michaelcummings - Is it picked by anyone? If not, I can work on this.

**Comment by hossj** [comment]
On top of this the "time" dropdown is not working either. I have written (and posted a video about this in Discord as well).

For me this started on version 4.10.6 (someone else confirmed they are facing the same problem).

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/16493
