### ISSUE TITLE
strapi-upload-local: Edit uploaded file

### ISSUE THREAD

**Issue by kenta88** [strapi/strapi#1685]
**Allow trough api to update a file already uploaded.**
- add a new relationship
- edit a relationship
- update information (name, hash...)

currently the edit method is implemented for services

```  
  edit: async (params, values) => {
    // Use Content Manager business logic to handle relation.
    if (strapi.plugins['content-manager']) {
      params.model = 'file';
      params.id = (params._id || params.id);

      return await strapi.plugins['content-manager'].services['contentmanager'].edit(params, values, 'upload');
    }

    return strapi.query('file', 'upload').update(_.assign(params, values));
  },
```

but is not used by api (no routes and controller can access this service).

not sure if this one is a missing feature of if I missing something.

Thanks

**Comment by lauriejim** [comment]
Hello @kenta88 .
You put log in this function and use the content manager ?

**Comment by lauriejim** [comment]
It's code we have to delete.
This feature not exist. Probably will be integrate in a media manager plugin.

**Comment by pedrosimao** [comment]
Any news about this? I would love to have a route where I could associate the same image / file to multiple objects... Like this I would not need to re-upload the file each time I want to re-use it.

**Comment by roghernandez** [comment]
The service is still availible at:
`strapi.plugins.upload.services.upload.edit()`
