### ISSUE TITLE
I don't write to long text inputs

### ISSUE THREAD

**Issue by xayrullo** [strapi/strapi#16879]
### Required System information

- Node.js version: 16
- NPM version: 8.12.1
- Strapi version: 4.10.7
- Database: postgres
- Operating system: mac/windows
- Is your project Javascript or Typescript: typescript

### Describe the bug
I'm tried type text to long text inputs, but nothing happened. Like defenition inputs
### Screenshots
<img width="663" alt="Screenshot 2023-06-01 at 14 24 09" src="https://github.com/strapi/strapi/assets/45508650/0338a3fb-b403-461f-8195-b56a4bca0f4b">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by dimitrisganotis** [comment]
I'm having the same issue. The text input field doesn't work when the type is long text. This happens only in production mode. In development it works fine!

<img width="588" alt="Screenshot 2023-06-01 at 12 52 27" src="https://github.com/strapi/strapi/assets/37548878/bfbb7c1d-3ea4-4a97-bc9e-d9c63e77dbe2">

**Comment by gu-stav** [comment]
Hello. Did you update from a previous version?

Could you please make sure to delete your `.cache` and `build` directories and rebuild the admin app.

```
rm -rf .cache build && npm run build
```

This will make sure you have a clean build - the issue should disappear then.

**Comment by dimitrisganotis** [comment]
> Hello. Did you update from a previous version?
> 
> Could you please make sure to delete your `.cache` and `build` directories and rebuild the admin app.
> 
> ```
> rm -rf .cache build && npm run build
> ```
> 
> This will make sure you have a clean build - the issue should disappear then.

Hi! Unfortunately this didn't solve the issue.

**Comment by gu-stav** [comment]
@dimitrisganotis I've just tried to setup a completely blank project using `npx create-strapi-app@latest my-project` and I don't see any problems there.

Unfortunately the problem must be somewhere on your system - either cached dependencies, or some old build data. Make sure to invalidate your package manager cache, delete the cache, build and if nothing helps also the node_modules directory.

Afterwards you should be set.

**Comment by dimitrisganotis** [comment]
The issue isn't cache or something like that. But now its fixed with the new version 4.10.7.

I think this was the issue: https://github.com/strapi/strapi/pull/16831
