### ISSUE TITLE
Wrong typing on createMany() function

### ISSUE THREAD

**Issue by Ooyashi** [strapi/strapi#16877]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.7
- Strapi version: 4.10.7
- Database: SQLite 3
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am not able to use the `createMany()` function of Query Engine API due to wrong typing. As for now, this function does not return ids of created entities as it should be by docs:

https://docs.strapi.io/dev-docs/api/query-engine/bulk-operations#createmany

In node_modules\@strapi\database\lib\index.d.ts the  `createMany()` function definition looks like this:

`createMany(params: CreateManyParams<AllTypes[T]>): Promise<{ count: number }>;`

It should look like this:

`createMany(params: CreateManyParams<AllTypes[T]>): Promise<{ count: number, ids: ID[] }>;`

### Steps to reproduce the behavior

1. Create Typescript file, e.g. book.ts
2. Write the `createMany()` Query 
3. Try to fetch `ids` from the result object

### Expected behavior

I am able to fetch the ids with no errors.

### Screenshots

![image](https://github.com/strapi/strapi/assets/73554716/79615811-a3dc-46aa-a961-e111cd6ac8f3)

### Code snippets

```    
    // Create roles with permissions.
    // Source: node_modules/@strapi/plugin-users-permissions/server/services/role.js
    const roles = await strapi.db
      .query('plugin::users-permissions.role')
      .createMany({
        data: missingRoles,
      });

    // We need to fetch ids of created roles from result object
    const { ids } = roles;
```

### Additional context

This problem arose when I started migrating the Strapi project from JavaScript to TypeScript.

**Comment by Marc-Roig** [comment]
hello, I will start working on this right away :) Thank you for reporting the issue
