### ISSUE TITLE
File upload error styling is broken

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#16886]
### Describe the bug

If you upload a file and there is any error uploading it, you see the following.

The X icon should be centered.

### Screenshots

![image](https://github.com/strapi/strapi/assets/20578351/f6c8c936-9755-4c40-83f6-5f9f1d1b4b98)

**Comment by bolg55** [comment]
It looks like this might be affecting successful uploads as well. 


Reported by a user:
![image](https://github.com/strapi/strapi/assets/43022248/e51956f2-c118-413e-a6cc-f0e46ba8aca8)
