### ISSUE TITLE
List view table buttons are not properly aligned

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#16887]
### Required System information
Node.js version: v16.19.0
NPM version: n/a
Strapi version: 4.10.7
Database: n/a
Operating system: MacOS 
Is your project Javascript or Typescript: n/a

### Describe the bug

The top buttons of the List View table are not properly vertically alligend.

### Screenshots

![image](https://github.com/strapi/strapi/assets/20578351/bf572f28-f859-4445-9727-874e4045a9af)

**Comment by razzuSharma** [comment]
Is this issue still available?

**Comment by Marc-Roig** [comment]
@razzuSharma yes, at least in 4.10.7

**Comment by joshuaellis** [comment]
Closing this because its a DS issue, see strapi/design-system#1093
