### ISSUE TITLE
Returning forbidden from a controller results in an internal server error

### ISSUE THREAD

**Issue by Alexnortung** [strapi/strapi#16882]
### Required System information

- Node.js version: v18.15.0
- NPM version: v9.5.9
- Strapi version: 4.10.7
- Database: sqlite
- Operating system: NixOS and Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Returning forbidden from a controller action results in a `500` error instead of returning `403` as it has done in prior versions.

In the logs we can see that there is an unhandled `ForbiddenError`

```
ForbiddenError: Forbidden access
```

### Steps to reproduce the behavior

1. Create a controller with an action and setup a route for it
2. in the action use `ctx.forbidden()` or `ctx.throw(403)` and then return.
3. If you request that route it will now give a 500 status code instead of the 403 that was expected.

### Expected behavior

I expected to get a 403 response

### Code snippets

```typescript
      if (!user) {
        ctx.forbidden(); // or ctx.throw(403)
        return;
      }
```

**Comment by Marc-Roig** [comment]
hello! could you share a bit more about your controller or the route definitions?

I am not able to replicate your problem

**Comment by Alexnortung** [comment]
Alright, it seems to be an issue with `package-lock.json` after updating from `4.10.6`. After deleting it and running `npm install` again, it works.

Why might this be an issue?

**Comment by Marc-Roig** [comment]
Not sure if we changed any dependency or part of the code related to this, but maybe that could be the case.

For now I will close the issue if this is working for you :)
