### ISSUE TITLE
Relations missing after data transfer

### ISSUE THREAD

**Issue by smoogly** [strapi/strapi#16891]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.10.7
- Database: Postgres
- Operating system: Linux Alpine in Docker
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Relations between components missing at destination after data transfer.

### Steps to reproduce the behavior

1. Set up two content types, where one has a relation to another — simple one-to-one works
2. Create entities of both of those types, including populating the relation
3. Initiate transfer to another Strapi instance using `npm run strapi -- transfer --force --to <destination> --to-token <token>`
4. After transfer completed, navigate to the destination instance
5. Find the component with relation, notice the relation field is empty

### Expected behavior

Relation is set up at destination exactly as it existed at source.

**Comment by niklasfjeldberg** [comment]
I also have this issue, have you had any success finding a solution?

**Comment by Blagoj5** [comment]
I'm encountering the exact same thing, however I'm using `strapi export` followed by `strapi import`. The data or the links are present in the .tar directory, however when I ran import nearly half of the links are missing. Here's some images:
- on import:
![image](https://github.com/strapi/strapi/assets/50581470/99a5d69f-83a2-41d9-93c1-1bd88c800512)
- on export:
![image](https://github.com/strapi/strapi/assets/50581470/8c0e6b83-29dc-4ef4-b568-3083ad98a18c)

**Comment by PaulBratslavsky** [comment]
This issue is still present in 4.11.3 reverting back to 4.10.4 works.  Not sure what changes were introduced in 4.10.5 that introduced this bug.  

Reverting Example Video

https://github.com/strapi/strapi/assets/6153188/1a4d3119-483a-4eaf-bdeb-ef4b4fdda83f

**Comment by karl93rus** [comment]
> This issue is still present in 4.11.3 reverting back to 4.10.4 works. Not sure what changes were introduced in 4.10.5 that introduced this bug.
> 
> Reverting Example Video
> 
>  revert.mp4

You are the savior! Thanks a lot! Downgrading Strapi version indeed solved this issue!
