### ISSUE TITLE
Not possible to change email configuration

### ISSUE THREAD

**Issue by lis55** [strapi/strapi#16907]
name: 🐛 Bug Report
about: Create a report to help us improve Strapi.
Bug report
Required System information
STRAPI VERSION v4.10.6
NODE VERSION v14.21.3
Database: postgres
Operating system: windows 11
NPM version: 6.14.18
javascript

Describe the bug
I cannot change the email configuration by modifying the plugin.js file. I installed the nodemailer provider

Steps to reproduce the behavior
yarn strapi create-app appname quickstart
Install nodemailer provider plugin
Modify the config/plugins.js as shown below
See error
Expected behavior
The email configuration should change according to what is provided in the plugins.js file

Screenshots
// EMAIL Plugin

module.exports = ({ env }) => ({
    // ...
    email: {
      config: {
        provider: 'nodemailer',
        providerOptions: {
          host: env('SMTP_HOST', 'smtp.gmail.com'),
          port: env('SMTP_PORT', 465),
          auth: {
            user: env('SMTP_USERNAME', 'example@gmail.com'),
            pass: env('SMTP_PASSWORD', 'xxxxxxx'),
          },
        },
        settings: {
          defaultFrom: 'example@gmail.com',
          defaultReplyTo: 'example@gmail.com',
        },
      },
    },
    // ...
  });
And the same default configuration still remains
![image](https://github.com/strapi/strapi/assets/19789469/877d8b84-50e3-46b2-8e16-3caf31924b84)

Additional context
Add any other context about the problem here

**Comment by tobiasbenkner** [comment]
here is the same issue: https://github.com/strapi/strapi/issues/16179

**Comment by derrickmehaffy** [comment]
Unable to reproduce on v4.13.2
