### ISSUE TITLE
Opening Certain Menus Prevents Interactivity in Admin Panel

### ISSUE THREAD

**Issue by KMcKraken** [strapi/strapi#16903]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.5
- Strapi version: 4.10.7
- Database: SQLite
- Operating system: Windows 11 Pro 10.0.22621
- Is your project Javascript or Typescript: Javascript

### Describe the bug

In the Admin panel, I've noticed when clicking on the help button, or relation dropdowns in the main content builder menu where items are listed, the interface can no longer be interacted with. The only way I've found to close the menu after this is to click an item in the relation dropdown, then click outside the menu, or refresh the page. For the help menu, only refreshing the page fixes it.

### Steps to reproduce the behavior

1. Go to Admin panel -> Content Manager.
2. Click on any collection that has a visible Relation dropdown.
3. Click the dropdown.
4. Click anywhere outside the menu, or the dropdown button you originally clicked.
5. Notice that the menu does not go away, and you cannot interact with/click on any other elements aside from the dropdown content.

OR

1. Click the Help menu button
2. Notice elements within the menu are interactive
3. Click the close button or anywhere outside the menu.
4. Notice the close button does not work, and no elements outside the menu are interactive.

### Expected behavior

Clicking either the original dropdown button, or anywhere outside the menu should close the menu. I feel it's supposed to work the same for the help menu.

### Screenshots

Dependencies, in case something is outdated, or incompatible:
![dep](https://github.com/strapi/strapi/assets/69874029/87c2c2b5-e155-4f9d-9ca7-562f3b7088a1)

### Code snippets

N/A

### Additional context

I am using Google Chrome to access the Admin panel, and I'm running it for local development on localhost.

This certainly doesn't feel like intended behavior. I have already run a build after upgrading to the new version from 4.10.6 to return functionality to Long Text fields. This seems to be the only remaining issue in the interface that I have found. Apologies if this is a duplicate of an existing issue, it is not my intention to waste your time.

**Comment by KMcKraken** [comment]
I went ahead and recorded the video. I apologize for the part where I may sound snarky, but that was more of me being surprised when it actually didn't do anything. It was not intended to sound like I was criticizing.

https://www.youtube.com/watch?v=pDJvXwmosL0

**Comment by smoothdvd** [comment]
Same as datetime picker, the popup calendar block all except itself, only force to select a date to hide the calendar.

**Comment by GregorSondermeier** [comment]
Seems to be fine in v4.10.5, so must have been introduced in v4.10.6 or v4.10.7.

**Comment by KMcKraken** [comment]
UPDATE: Upgrading to 4.11.0 and running "npm build" seems to have fixed the issue I was displaying. I can't speak for what issues others had.

**Comment by KMcKraken** [comment]
I'm unsure whether to close this issue myself, or if I should leave that up to the mods.

**Comment by joshuaellis** [comment]
> UPDATE: Upgrading to 4.11.0 and running "npm build" seems to have fixed the issue I was displaying. I can't speak for what issues others had.

Since your issue is resolved, we can close this issue, if someone is facing a similar / different issue I would encourage them to open a new issue so we can examine accordingly 👍🏼  thanks for updating us.
