### ISSUE TITLE
Cannot find module 'pluralize'

### ISSUE THREAD

**Issue by maturano** [strapi/strapi#1690]
**Informations**
- **Node.js version**: v9.11.2
- **npm version**: v5.6.0
- **Strapi version**: master on 8f2c285cb0b8bffc10601f36d9aa334d0238616b
- **Database**: all
- **Operating system**: WSL

**What is the current behavior?**
Strapi not running and showing this message:

```
debug :no_entry: Server wasn't able to start properly.
error Cannot find module 'pluralize'
```

**Steps to reproduce the problem**
```
$ git clone git@github.com:strapi/strapi.git
$ cd strapi
$ npm run setup
$ cd /some/path/for/a/project
$ strapi new project
$ cd project
$ strapi start
```

**What is the expected behavior?**
Application up and running

**Suggested solutions**
Add missing dependency

**Comment by xnfa** [comment]
You can remove node_modules in your project directory, and then run `npm run setup` to fix this problem.

**Comment by krsnaa** [comment]
@maturano  @xnfa - Alternatively, just copy the pluralize folder from say `/-project-path/plugins/content-type-builder/node_modules/pluralize`,  to the root node_modules at `/-project-path/node_modules`  and  `strapi start` will work just fine!

**Comment by lauriejim** [comment]
@maturano I was not able to reproduce your issue.
Someone else did ?

**Comment by maturano** [comment]
I just tested and I'm still able to reproduce it:
![capture](https://user-images.githubusercontent.com/5768813/44364007-809d4500-a48b-11e8-81e5-5011049f45f7.PNG)

**Clarification**:
- This is cloning Strapi **from the repository**, not with a global installation with `npm`
- This is **without the `--dev` flag**. I believe with that flag is unable to reproduce it.

The thing is, `pluralize` is used inside `strapi-plugin-content-manager`, but is not declared as dependency in their `package.json`:
![capture](https://user-images.githubusercontent.com/5768813/44364484-be4e9d80-a48c-11e8-9d8a-f9d595b03b15.PNG)

I think that's a bug and I created the PR #1693 to solve it, but I don't have experience with the "monorepo" architecture; I thought there was a change to have something like "shared dependencies"... IDK 🤷‍♂️ 

On a quick read, I think my PR is valid, isn't?. If there is not showing that error with a global installation is because the dependency is solved "by accident" by another package... but, still a bug.

---
BTW @xnfa, @krsnaa: I think the easy workaround is just install the dependency: `npm install pluralize`

**Comment by lauriejim** [comment]
Okay it's clear.
It's the missing `--dev` flag.

I think the `pluralize` dependency have to be added in the `content-manager`
But it's will be hard to test because when you run `strapi new ...` without `--dev` flag, plugins are installed from **npm**. 
And the update you will do, will no be published on **npm** now
