### ISSUE TITLE
REST API always populating creator fields

### ISSUE THREAD

**Issue by JWandscheer** [strapi/strapi#16909]
### Required System information
- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.10.7
- Database: postgres
- Operating system: MacOS/Docker
- Is your project Javascript or Typescript: javascript

### Describe the bug

Against stated in the official Strapi [documentation](https://docs.strapi.io/dev-docs/api/rest/populate-select#populating-createdby-and-updatedby), the fields `createdAt`, `updatedAt` and `publishedAt` are populated through the API by default.
For me, it is not possible to deactivate the population of this fields by setting 

`"populateCreatorFields": false`

in the models schema.json. The fields are always populated.

### Steps to reproduce the behavior

1. Create a model in your strapi instance
2. Create en entry for the model in the content manager
3. Fetch the entries via REST api
4. See the creator fields in the response

### Expected behavior

The creator fields should not be populated by default / setting `"populateCreatorFields": false` should have an impact on the behaviour.

**Comment by michaelroth-xx** [comment]
Still the same behaviour :-(

**Comment by derrickmehaffy** [comment]
This is almost certainly due to customization as it's not reproducible on 4.24.2
