### ISSUE TITLE
GET /admin/review-workflows/workflows/?populate=stages throws 403 PolicyError (Issued by Admin Panel)

### ISSUE THREAD

**Issue by GregorSondermeier** [strapi/strapi#16920]
### Required System information

- Node.js version: 18.14.2
- NPM version: 9.5.0
- Strapi version: 4.10.5 Enterprise Edition
- Database: mariadb
- Operating system: Linux
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

The backend throws a _403 PolicyError_ which is logged to Sentry and logged in the browser console. This happens when I navigate to any single entity view (e.g. _/admin/content-manager/collectionType/api::restaurant.restaurant/1_).

### Steps to reproduce the behavior

1. Follow the [quick start guide](https://docs.strapi.io/dev-docs/quick-start) to create a new Strapi instance (`npx create-strapi-app@4.10.5 my-project --quickstart`) and create the collection types _restaurant_ and a _category_. Doesn't matter if you use draft & publish or not.
2. Create a restaurant and a category
3. Edit a restaurant or category => no issue here
4. In the _.env_ file, add a valid STRAPI_LICENSE environment variable
5. Restart Strapi
6. Edit a restaurant or category
7. Notice the 403 Policy Error is logged:

![image](https://github.com/strapi/strapi/assets/11959747/c9654490-7313-4af3-be7a-61af0120c3c5)

If the Sentry Plugin is installed, configured and enabled, this will also be logged to sentry and pollutes the log pretty quickly:

![image](https://github.com/strapi/strapi/assets/11959747/20c62641-e7ca-4d2f-ac2c-e5995cd314f8)

### Expected behavior

No error should be logged.

### Additional context

This issue doesn't seem to appear with the community edition. If there is no STRAPI_LICENSE environment variable, this request is not issued by the admin panel.

Looks to come from the review workflows MVP that was introduced in v4.10 ([Link](https://strapi.io/blog/april-product-updates-v4.10)).

**Comment by GregorSondermeier** [comment]
My current workaround:
Ignore that specific transaction.

```js
// ./config/plugins.js

module.exports = ({ env }) => ({
  // ...
  sentry: {
    enabled: true,
    config: {
      dsn: env('NODE_ENV') !== 'development' ? env('SENTRY_DSN') : null,
      sendMetadata: true,
      init: {
        beforeSend(event) {
          if (event.tags?.transaction === 'GET /admin/review-workflows/workflows') {
            return null;
          }

          return event;
        },
      },
    },
  },
  // ...
});
```

Documentation:
* https://docs.sentry.io/platforms/node/configuration/options/#before-send
* https://docs.sentry.io/platforms/javascript/configuration/filtering/#using-platformidentifier-namebefore-send-

I'm not sure if it really is a transaction in how Sentry understands it or if it is a tag called "transaction". Because [beforeSendTransaction()](https://docs.sentry.io/platforms/node/configuration/options/#before-send-transaction) and [ignoreTransactions](https://docs.sentry.io/platforms/node/configuration/options/#ignore-transactions) don't work, although that could also be because Strapi uses [an older Sentry version](https://github.com/strapi/strapi/pull/16828).

**Comment by gu-stav** [comment]
The issue does not seem present anymore in the upcoming 4.12 release, so I am closing it.
