### ISSUE TITLE
Details of a log crashes after build and starts upgrading from 4.7.1 to 4.10.7

### ISSUE THREAD

**Issue by rivaslive** [strapi/strapi#16928]
### Required System information

- Node.js version: 16.x.x
- NPM version: 9.4.1
- Strapi version: 4.8.x or higher
- Database: Postgresql
- Operating system: MacOS, Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I upgrade Strapi and all its packages from version 4.7.1 to a higher one like 4.9.x or the latest 4.10.7, it breaks only in PROD (running a build). This happens when I try to view the details of a record, but the record in DEV (not running a build) can be displayed. I'm attaching the error. For now, the solution is to stay on 4.7.1 and not update.

### Expected behavior

it is expected that the record details should be visible not only locally but also when creating a build.

### Screenshots

Version 4.10.7

<img width="1288" alt="image" src="https://github.com/strapi/strapi/assets/39039038/a232189f-5a63-470e-b797-cb193cc816d5">

Version 4.7.1

<img width="1329" alt="bbb" src="https://github.com/strapi/strapi/assets/39039038/ce966dc1-b235-4a2a-a1c6-78e09035b7f7">

### Additional context

It is only reproducible when I upgrade to a higher version of 4.7.x.

**Comment by Boegie19** [comment]
No Steps to reproduce the behavior
