### ISSUE TITLE
Strapi GraphQl plugin: Apollo Server v3 is officially deprecated since November 2022

### ISSUE THREAD

**Issue by vicmarcal** [strapi/strapi#16945]
Hi guys!
Seems the plugin for graphql is using "apollo-server-core": "3.12.0", afaik, this package is from the Apollo Server v3 era, superseeded by the @apollo/server package which is new in version 4. So, unless mistaken, the graphql plugin is based on the v3 Apollo Server, which is  deprecated since November 2022, and with an EOL in October 2023 (a couple of months from now):
![image](https://github.com/strapi/strapi/assets/6674048/04c3242f-d074-46e6-a7a1-e25b1cd35e9c)
Are there any plans to release a compatible Apollo Server v4 plugin for Strapi?

**Comment by vicmarcal** [comment]
---
name: 🐛 Apollo Server v3 is officially deprecated since November 2022
about: Outdated package about EOL
---



## Bug report

### Required System information




- Node.js version: 18
- NPM version: N/A
- Strapi version: 4.11.0
- Database: N(A
- Operating system: Ubuntu
- Is your project Javascript or Typescript: JS

### Describe the bug

Seems the plugin for graphql is using "apollo-server-core": "3.12.0", afaik, this package is from the Apollo Server v3 era, superseeded by the @apollo/server package which is new in version 4. So, unless mistaken, the Strapi graphql plugin is based on the v3 Apollo Server, which is deprecated since November 2022, and with an EOL in October 2023 (a couple of months from now):
![image](https://github.com/strapi/strapi/assets/6674048/e31b3201-1e59-4d28-b528-74358b3ce95b)

### Steps to reproduce the behavior

1. Install the Strapi Graphql Plugin
2. Go to the package.json to view the dependencies of the Strapi Graphql Plugin
3. Seems "apollo-server-core": "3.12.0" is a dependency, coming from Apollo Server 3

### Expected behavior

Strapi Graphql Plugin shouldn't be dependant of a library which is not supported anymore and which will come into EOL in 3 months.

**Comment by westende** [comment]
Why is this "Closed as not planned"? Seems like a serious issue to me to distribute a package that has dependencies that are EOL.
