### ISSUE TITLE
API only returning id's of images

### ISSUE THREAD

**Issue by eruiz-impact** [strapi/strapi#16947]
### Required System information

- Node.js version: 16.19.1
- NPM version: 8.19.3
- Strapi version: 4.10.7
- Database: postgres
- Operating system: macOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When fetching images within a post collection type, strapi is only returning the id of the image.
![image](https://github.com/strapi/strapi/assets/76070322/17536408-70d8-4bee-a490-05d3b3fccc12)

I am using the populate parameter since strapi does not return media fields by default. 

This is my endpoint:
{URL}/api/posts?populate=cardImage

![image](https://github.com/strapi/strapi/assets/76070322/08ae5b64-6fe4-4b52-9f6a-b99eead114a5)

I have tried using populate=* as well and that returns the same thing.

**Comment by GregorSondermeier** [comment]
Assets are a hidden relation and need to be populated as well.

Try `GET /api/posts?populate[cardImage][populate]=*`.
Does that help?
