### ISSUE TITLE
Breaking change in `@strapi/utils`

### ISSUE THREAD

**Issue by dmeijboom** [strapi/strapi#16955]
### Required System information

- Node.js version: 20.x
- NPM version: ?
- Strapi version: 4.11.0
- Database: postgresql
- Operating system: alpine
- Is your project Javascript or Typescript: both

### Describe the bug

In `@strapi/utils` version `v4.11.0` the `packages/core/utils/lib/webhook.js` file was removed which was exported and thus part of the public api. I encountered this when the [strapi-plugin-publisher](https://github.com/ComfortablyCoding/strapi-plugin-publisher/issues/78) plugin wasn't working anymore (because of the removal).

A quick Github search reveals that it other plugins as well:
- [strapi-plugin-sso](https://github.com/yasudacloud/strapi-plugin-sso)
- [strapi-plugin-thumbnail](https://github.com/kegaretail/strapi-plugin-thumbnail)

Some follow up questions:
- Does the `strapi` project follow semver? If so, this should be a new major version
- Is the `@strapi/utils` package part of the public api? If not, it would be nice if that was mentioned in the README

**Comment by joshuaellis** [comment]
Hey @dmeijboom,

Thanks for the report – this was a mistake you're correct – we should not have removed this export from the `@strapi/utils` folder. We're going to look at restoring the public API for that package.

CC @Marc-Roig & @nathan-pichon

**Comment by Marc-Roig** [comment]
Hello, we have opened a PR to reintroduce the `packages/core/utils/lib/webhook.js` file. I have marked this file as deprecated  though, as the intent of the original change was to make the webhook event list extendable from any package, which was not possible if we stored this list in a utils file.

So for now, any package using this util file, in v4, will get a deprecation warning.
