### ISSUE TITLE
Relations are not returned in the correct order

### ISSUE THREAD

**Issue by mpuxted** [strapi/strapi#16961]
### Required System information

- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: v4.10.1
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Relations on a content type are not always returned in the order that they display in the Strapi UI.

This issue has been observed on the 1st and 2nd relation being returned in the wrong order, and the 2nd and 3rd relation being returned in the wrong order. 

At the moment I do not know any reliable way to replicate this issue - but I will update this issue as I continue to investigate under what conditions this can happen.

I've found that changing the order and saving, and then reverting the order and saving will fix this issue.

I can see that we are running a few versions behind, but I've had a look at the bug fixes between v4.10.1 and v4.11 and I cannot see anything relevant. Regardless, I will update to the latest version tomorrow and see if the issue goes away.

**Comment by mpuxted** [comment]
I have some more information on what the data actually looks like. 

We have offer_page_templates which each contain a list of offers

With the query:
```
SELECT * FROM offers_offer_page_templates_links 
WHERE offer_page_template_id = 14
ORDER BY offer_order
```

I can see that offer_order numbers are repeated, which I think is leading to them being returned in a different order in the UI vs and the API

![image](https://github.com/strapi/strapi/assets/54951494/5748e8c0-7c33-42e6-9d2e-da0485b58325)

**Comment by mpuxted** [comment]
I've found the inconsistencies in the ordering. 

Both the API and the CMS will sort by offer_order ascending - but when there are duplicate offer_orders it will then sort by the ID of the link.

The CMS displays the offers in:
offer_order descending, ID descending

The API returns the offers in
offer_order descending, ID ascending

This means any offer links with the same ID will be reversed 

----

This is more of a symptom of the bug, rather than a bug itself - but making these two things consistent would help

**Comment by mpuxted** [comment]
@PaulBratslavsky we would like to try to arrange a call with a Strapi developer to go through this issue - is that possible?

**Comment by mpuxted** [comment]
We noticed once the data is fixed (no duplicate numbers) it will then break itself again an unknown amount of time later. @Boegie19 suggests it might be due to the integrity check

**Comment by Boegie19** [comment]
related to https://github.com/strapi/strapi/issues/15558

**Comment by mpuxted** [comment]
Hi @PaulBratslavsky , any news since our chat on Friday? Would be great to get some time pencilled in to go through this issue

**Comment by mpuxted** [comment]
We have figured out how to replicate the issue now. 

We have offers that can belong to many offer page templates (many to many)

If I go to a specific offer page template and remove all the offers linked to it and click save then the ordering of other offer page templates ends up incorrect.

E.g
Offer page template A has 19 offers assigned
I remove all the offers from offer page template A
Offer page template B, C, D and E now have duplicate orderings

**Comment by Boegie19** [comment]
Let me confirm the issue if I can I will put it to an high.
and put it as reproduced

**Comment by Boegie19** [comment]
Took me multiple trys to replicate but I can confirm the issue

**Comment by mpuxted** [comment]
I think I've found out more about how to reproduce this bug. 

We noticed that it was really easy to reproduce in our production environment, but not reproducible in our dev environment. 

I then did a data transfer from prod to dev and now I can reproduce it in dev. 

I've now found a new trend. 

Lets say I have offer page templates 1, 2, 3

and the offers assigned to them are like this:

1: offer 1, offer 2, offer 3, offer 10
2: offer 4, offer, 5, offer 6, offer 10
3: offer 7, offer 8, offer 9, offer 10

If I then remove offer 10 from template 1 then template 1 becomes:
1: offer, 1, offer 2, offer 3

BUT the other templates become
2: offer 10, offer 4, offer 5, offer 6
3: offer 10, offer 7, offer 8, offer 9

----

And the offer_orders will be duplicated, like this:

1: 1, 1, 2, 3
2: 1, 1, 2, 3

------

I can see the query in our logs:

```
SET "offer_order" = b.src_order, "offer_page_template_order" = b.inv_order
              FROM (
                SELECT "id", ROW_NUMBER() OVER (PARTITION BY "offer_page_template_id" ORDER BY "offer_order") AS src_order, ROW_NUMBER() OVER (PARTITION BY "offer_id" ORDER BY "offer_page_template_order") AS inv_order
                FROM "offers_offer_page_templates_links"
                WHERE "offer_page_template_id" = $1 OR **"offer_id" IN ($2)**
              ) AS b
              WHERE b.id = a.id
```

I think this offer_id IN ($2) is causing the offer to be moved in unrelated templates - but I can't see what that $2 is

**Comment by mpuxted** [comment]
This block here is the cause of the bug:

https://github.com/strapi/strapi/blob/83ada24a028428b305b1dcfd2e42dab2bd786261/packages/core/database/lib/entity-manager/regular-relations.js#L225-L232

I see that it is trying to update the relation and the inverse relation, and this is the reason why links with the same offer are also edited.

**Comment by Marc-Roig** [comment]
hello! I am taking a look at this issue and I will try to refactor that `regular-relations.js` reordering query .

That issue description was immensely helpful :) I managed to reproduce it in 5 minutes.

**Comment by patseam** [comment]
For anyone who lands on this issue while investigating relation ordering problems, I’ve opened a feature request that focuses on what I believe is the broader underlying gap:

https://feedback.strapi.io/other/p/editor-defined-relation-order-should-be-retrievable-through-rest-and-graphql-api

My goal is not to revisit the bug reported here, but to address the larger question of how editor-defined relation ordering should be exposed to developers.

Strapi allows editors to reorder relations in the Admin UI, persists that order, and restores it when editing content again. However, there is currently no documented and reliable way for applications consuming the REST or GraphQL APIs to retrieve relations in that same editor-defined order.

The proposal also references the long history of discussions and issues around relation ordering, including this one.

If this affects your use case as well, I’d welcome additional feedback and examples there.
