### ISSUE TITLE
"Cannot read properties of undefined (reading 'attributes')" after picking a component in dynamic zone

### ISSUE THREAD

**Issue by Jelmerovereem** [strapi/strapi#16974]
### Required System information

- Node.js version: v18.14.1
- NPM version: 9.3.1
- Strapi version: 4.11.0
- Database: sqlite
- Operating system: macOS Ventura 13.4 (also happens on my Ubuntu 22.04 VPS)
- Is your project Javascript or Typescript: Typescript (but also happens with Javascript project)

### Describe the bug

"Cannot read properties of undefined (reading 'attributes')" error message pops up in the console after picking a component (that has another component in it) in a dynamic zone. When doing this inside a single type the screen goes blank/white, when doing this inside a collection type it shows "Woops! Something went wrong. Please, try again.".

### Steps to reproduce the behavior

1. Make sure your running Strapi version 4.11.0. (4.10.8 is working fine)
2. Create the following things in the content-type builder:
  - A component with e.g. a text field. (Let's call this ComponentA)
  - Another component that has the component you just made as a field. (Let's call this ComponentB)
  - A single or collection type that has a dynamic zone, the dynamic zone should include the 2nd component(ComponentB) you just made.
3. Go to the content manager and go to the single or collection type .
4. Try to add the component to the dynamic zone.
5. Observe error in console and a blank page or an error message regarding which type you used.

### Expected behavior

I expect the component's inputs to show and be available when picking that component in the dynamic zone.
Like this (Strapi v4.10.8) :
<img width="507" alt="Screenshot 2023-06-11 at 19 49 48" src="https://github.com/strapi/strapi/assets/58043913/f7e5c6c9-4286-430c-9c53-d49f90562608">

### Screenshots

Collection type:
<img width="1439" alt="Screenshot 2023-06-11 at 19 51 20" src="https://github.com/strapi/strapi/assets/58043913/44b9f867-16ed-4e28-bf7d-63cde8cb36d8">

Single type:
<img width="1440" alt="Screenshot 2023-06-11 at 19 51 03" src="https://github.com/strapi/strapi/assets/58043913/e20f8bf0-5a04-41e1-8981-28f586a0ad10">

### Additional context

- When you add ComponentA to the dynamic zone as well, it works as expected.
- In 4.10.8 this is working fine, so I guess this came up in the latest(4.11.0) release.

**Comment by joshuaellis** [comment]
Thanks for the report, this was solved with #16969 and is expected to be released in 4.11.1 – sorry for the inconvenience this may have caused.

**Comment by Jelmerovereem** [comment]
@joshuaellis ah awesome! Couldn't find that ticket because I only looked in the open ticket list. Glad it will be fixed in the new release, thank you!
