### ISSUE TITLE
Date change outside of the box

### ISSUE THREAD

**Issue by terryhuntjr** [strapi/strapi#16987]
### Required System information

- Node.js version: 18.16.0
- NPM version: latest
- Strapi version: latest
- Database: PSQL
[Screencast from 06-12-2023 10:06:47 AM.webm](https://github.com/strapi/strapi/assets/119683861/97b36f3b-13c3-4fd6-9a2b-3f7550c18bb2)

- Operating system: Ubuntu
- Is your project Javascript or Typescript: Javascript

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by terryhuntjr** [comment]
The date change when you click outside of the box repeatedly.

**Comment by joshuaellis** [comment]
can you please fill in the template?
