### ISSUE TITLE
Lifecycle hooks not called on relation update

### ISSUE THREAD

**Issue by alexphiev** [strapi/strapi#16980]
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.2.0
- Strapi version: 4.10.5
- Database: PostgreSQL 
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I noticed that lifecycle hooks like `afterUpdate` will not be triggered after a relation update on a related object. 
I use those hooks for indexing my search engine and relational data is very important to keep up to date. 

### Steps to reproduce the behavior

1. Have content type A and B related with a one-to-one relationship
2. Update an object on A which already has a related B object called 'B1' by changing that to another B object called 'B2'
3. Lifecycle hooks executes properly on the main modified object A
4. BUG: Lifecycle method `afterUpdate` is not called on 'B1' or 'B2'

### Expected behavior

Both B1 and B2 should have been updated since their relation to object A changed. The `afterUpdate` lifecycle hook should have been called on both.

**Comment by Boegie19** [comment]
Is a known thing only thing is the object itself does not get changed only the realtion aka if this should be done a new event should be made for this spesific event. since you don't have a before and after.
