### ISSUE TITLE
Certain SSO providers have issues with case sensitive email addresses 

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#16982]
### Required System information

- Node.js version: v18
- NPM version: v8
- Strapi version: v4.11.0
- Database: SQLite
- Operating system: Linux Mint 21
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When using certain SSO providers (eg Azure AD) and when that SSO provider does not enforce email addresses to lowercase you can run into an issue where Strapi is not automatically forcing the email lowercase during the user lookup function. We had decided back in the beginning of v4 development to force all email addresses into lowercase and already apply this by default for normal user registration.

This same logic should apply to all SSO providers as well.

### Steps to reproduce the behavior

Bit complex to setup a testing environment, if an engineer needs a testing environment, speak with the support team on the internal Slack

### Expected behavior

From the moment an email address is received and before we begin parsing it and using it in duplication check functions, it should be converted to lowercase

### Screenshots

N/A

### Code snippets

https://github.com/strapi/strapi/blob/cc4f58ce387886de4602f4ca85adc856b4a22f2b/packages/core/admin/ee/server/controllers/authentication/middlewares.js#L30

### Additional context

Internal TID4150

**Comment by derrickmehaffy** [comment]
For now we could switch to case-insensitive lookup here: https://github.com/strapi/strapi/blob/c970d7027e1a25f1f89c22d7236747f88083c98f/packages/core/admin/server/src/services/user.ts#L227C1-L232C3

**Comment by Convly** [comment]
fixed by #18883
