### ISSUE TITLE
Incorrect GraphQL Pagination Return

### ISSUE THREAD

**Issue by soranoo** [strapi/strapi#16983]
### Required System information

- Node.js version: v18.15.0
- NPM version: v9.5.0
- Strapi version: v4.11.0
- Database:  8.0.17 - MySQL Community Server
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug
I made a request using GraphQL and REST API with the same filter but come out with a different "total" in pagination. The REST outcome is correct. GraphQL just returns the number of existing db records instead of the number of data.

### Expected behavior

The same "total" in pagination.

### Dependencies
```JSON
{
  "name": "CMS",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "^4.11.0",
    "@strapi/plugin-i18n": "4.11.0",
    "@strapi/plugin-users-permissions": "4.11.0",
    "@strapi/strapi": "4.11.0",
    "build": "^0.1.4",
    "mysql": "2.18.1",
    "strapi-ulid": "^0.1.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

### Screenshots

![image](https://github.com/strapi/strapi/assets/46896789/b6e8723d-ecfc-4710-a7ba-9a80e82acc74)
REST API: http://127.0.0.1:1337/api/posts?filters[labels][$contains]=01H2NG9J3DBWX8CE2Z56W096FX
GraphQL:
```GraphQL 
// Query Document: 
query Posts($filters: PostFiltersInput) {
  posts(filters: $filters) {
    data {
      id
    }
    meta {
      pagination {
        page
        pageSize
        pageCount
        total
      }
    }
  }
}

// Variables: 
{
  "filters": {
    "labels": {
      "contains": "01H2NG9J3DBWX8CE2Z56W096FX"
    }
  }
}
```
Post Structure:
![image](https://github.com/strapi/strapi/assets/46896789/6bf7f133-7477-4e54-934e-6b0c2d27ba28)

**Comment by nagman** [comment]
Same here. Tested with `4.10.7` and the pagination fields are correct.

But as soon as I go on `4.10.8` and upper, it fails and returns false data.

So the bug seems to occur since the `4.10.8` version.

**Comment by IliyaBrook** [comment]
> Same here. Tested with `4.10.7` and the pagination fields are correct.
> 
> But as soon as I go on `4.10.8` and upper, it fails and returns false data.
> 
> So the bug seems to occur since the `4.10.8` version.

Thank you for providing the latest working version =)), I'm looking forward to updates and bug fixes.

**Comment by viiiprock** [comment]
same with 4.11.1, has to roll back 4.10.7

**Comment by viiiprock** [comment]
hmm mine doesn't work at `4.10.7` either

**Comment by laurenskling** [comment]
I can confirm this happens from `4.10.8`. Just got called by a client that the search results counter is broken. Very yikes.

**Comment by ThallesP** [comment]
Are you guys accepting PR on this?

**Comment by IliyaBrook** [comment]
4.10.7 works correctly, guys please do the downgrade correctly, 
and use the build command after,
we just need to be patient waiting for the update

**Comment by callmephilip** [comment]
this looks fixed in `v4.11.3`, as far as i can tell

**Comment by callmephilip** [comment]
sorry. spoke too fast. still an issue

**Comment by 1yzz** [comment]
hope someone can fix this

**Comment by AdiCutitoiu** [comment]
This was solved in https://github.com/strapi/strapi/releases/tag/v4.11.4

**Comment by soranoo** [comment]
The issue was solved~ 👍 

Tested in `4.12.4` and `4.12.5`
