### ISSUE TITLE
Webhooks do not populate nested components like Media Component.

### ISSUE THREAD

**Issue by Emadeddin-eibo** [strapi/strapi#17003]
### Required System information

- Node.js version: 14.21.3
- NPM version: 6.14.18
- Strapi version: 4.11.1
- Database: postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Consider having a `Collection Component` named `Product` that is structured as follows:
```
{
    "name": "...",
    "price" : 100,
    "logo" : media attachment
}
```
Then, consider another `Component` named `Category` which has `one-to-many` relation with product.

Now, the Category has relations to two products, and when getting the results via `Rest API`, it shows the followings:

### Expected behavior
The expected result should be as follows:
```
{
  "data": [
    {
      "attributes": {
        "name": "Category name",
        "products": {
          "data": [
            {
              "attributes": {
                "name": "Product 1",
                "price": 100,
                "logo": {
                  "data": {
                    "attributes": {
                      "url": "some/url"
                    }
                  }
                }
              }
            },
            {
              "attributes": {
                "name": "Product 2",
                "price": 100,
                "logo": {
                  "data": {
                    "attributes": {
                      "url": "some/url"
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
  ]
}
```

However, when setting a **webhook** to send the payload on publish (for example), it sends only the followings:

```
{
  "data": [
    {
      "attributes": {
        "name": "Category name",
        "products": {
          "data": [
            {
              "attributes": {
                "name": "Product 1",
                "price": 100
              }
            },
            {
              "attributes": {
                "name": "Product 2",
                "price": 100
              }
            }
          ]
        }
      }
    }
  ]
}
```
Totally ignoring the media component, or any other custom component for that matter.

### Solutions that didn't work
I've tried to set the webhooks relations key in server.js as follows with no result:

```
webhooks: {
    populateRelations: true,
  },
```

Also, I've tried to set the performance to false as follows with no result:

```
relations: {
    performance: false,
  }
```

**Comment by pasayazici** [comment]
[I found solution. Link](https://forum.strapi.io/t/strapi-api-webhook-trigger-without-population/29231/3)

**Comment by Marc-Roig** [comment]
Hello! Webhook payload exclusively depends on the populated params on the api.
By default, when doing actions in your admin UI, we deep populate all fields , hence why you get all populated fields in webhooks in that case.

This is more an enhancement than a bug, and can be sorted out by populating those fields in your REST API, we plan to work this on the future but for now, if any of you would like to have this functionality I would ask to post it https://strapi.canny.io/.

If there are any more questions or discussions around this we can reopen the issue :)

**Comment by JWandscheer** [comment]
@Marc-Roig Thank you for this clarification. We have the following case, which is related to this behaviour: We are creating entries via GraphQL. A Webhook is triggered by the "entry.create" event and pushs the model into another system, but the Webhook payload doesn't contain the relation components. As explained by @derrickmehaffy in https://github.com/strapi/strapi/issues/11787, it is possible to write a custom middleware to populate all fields and relations. However, this doesn't seem to impact the webhook triggered by GraphQL mutations. Is there any way to populate all fields and relations in the Webhook when the entry is created by a GraphQL mutation?

**Comment by xinhui226** [comment]
> @Marc-Roig Thank you for this clarification. We have the following case, which is related to this behaviour: We are creating entries via GraphQL. A Webhook is triggered by the "entry.create" event and pushs the model into another system, but the Webhook payload doesn't contain the relation components. As explained by @derrickmehaffy in #11787, it is possible to write a custom middleware to populate all fields and relations. However, this doesn't seem to impact the webhook triggered by GraphQL mutations. Is there any way to populate all fields and relations in the Webhook when the entry is created by a GraphQL mutation?

Hi @JWandscheer , may I ask that are you able to solve the issue until now? because I am facing the same issue as yours, thank you.

**Comment by JWandscheer** [comment]
> > @Marc-Roig Thank you for this clarification. We have the following case, which is related to this behaviour: We are creating entries via GraphQL. A Webhook is triggered by the "entry.create" event and pushs the model into another system, but the Webhook payload doesn't contain the relation components. As explained by @derrickmehaffy in #11787, it is possible to write a custom middleware to populate all fields and relations. However, this doesn't seem to impact the webhook triggered by GraphQL mutations. Is there any way to populate all fields and relations in the Webhook when the entry is created by a GraphQL mutation?
> 
> Hi @JWandscheer , may I ask that are you able to solve the issue until now? because I am facing the same issue as yours, thank you.

Unfortunately no. We are now using a workaround, our server which receives the incoming webhooks fetches the missing information via GraphQL everytime a webhooks gets in.

**Comment by xinhui226** [comment]
> > > @Marc-Roig Thank you for this clarification. We have the following case, which is related to this behaviour: We are creating entries via GraphQL. A Webhook is triggered by the "entry.create" event and pushs the model into another system, but the Webhook payload doesn't contain the relation components. As explained by @derrickmehaffy in #11787, it is possible to write a custom middleware to populate all fields and relations. However, this doesn't seem to impact the webhook triggered by GraphQL mutations. Is there any way to populate all fields and relations in the Webhook when the entry is created by a GraphQL mutation?
> > 
> > 
> > Hi @JWandscheer , may I ask that are you able to solve the issue until now? because I am facing the same issue as yours, thank you.
> 
> Unfortunately no. We are now using a workaround, our server which receives the incoming webhooks fetches the missing information via GraphQL everytime a webhooks gets in.

I see, thanks again!

**Comment by cesar3030** [comment]
Hi there!
I'm having the same issue but I figured out `entry.publish` or `event.unpublish` have populated relations but `entry.update` does not. 

I filed a new issue to track this behavior https://github.com/strapi/strapi/issues/18348
