### ISSUE TITLE
Cannot create components with subcomponents

### ISSUE THREAD

**Issue by jwalcher** [strapi/strapi#17002]
### Required System information

- Node.js version: 16.16.0
- NPM version: 1.22.19
- Strapi version: 4.10/4.11
- Database: SQLite
- Operating system: MacOS
- Is your project Javascript or Typescript: TS

### Describe the bug

I have a dynamic zone with multiple components, some of which contain subcomponents (at level 1 only, no higher level nesting), and others that contain only ordinary fields. 

Starting with 4.11.0., I am unable to create components in the dynamic zone that themselves contain other components, receiving a `TypeError: undefined is not an object (evaluating 't[h.component].attributes') — content-manager` and a `Woops! Something went wrong. Please, try again.`

Components in dynamic zone that do not contain subcomponents work fine. Components with subcomponents that are not in dynamic zone work fine also.

### Steps to reproduce the behavior

I have not tried this on a fresh installation. I suspect https://github.com/strapi/strapi/pull/16826 is at fault, since it the one new feature affecting dynamic zone UI in release 4.11.0

### Expected behavior

Level 1 nested components should be supported even in dynamic zone, and should work in latest release as they did up to 4.10.8

**Comment by mogh-hello** [comment]
Getting the same issue. 

Node.js version: 16.18.1
NPM version: 8.19.2
Strapi version: 4.11.0
Database: SQLite
Operating system: Windows 11
Is your project Javascript or Typescript: JS

**Comment by jwalcher** [comment]
**update** the recent issue https://github.com/strapi/strapi/issues/16966 is very closely related, and is claimed to be fixed by https://github.com/strapi/strapi/pull/16969. This is not the case. The issue described here persists in 4.11.1

**Comment by mogh-hello** [comment]
@jwalcher: after a while, I managed to get rid of the issue on my end. 

Delete .cache folder, 
Delete package-lock.json. 
update your package.json to 4.11.1
install
run build

It worked for me, but only after a few tries...

**Comment by jwalcher** [comment]
@mogh-hello  seems to do the trick, thanks a bunch!

**Comment by cooperwfloyd** [comment]
crossposting with what might be a relevant issue in #16966 for those who are still experiencing this issue — https://github.com/strapi/strapi/issues/16966#issuecomment-1598858677
