### ISSUE TITLE
Data transfer is not enabled on the remote host

### ISSUE THREAD

**Issue by shuffgy** [strapi/strapi#17015]
### Required System information

- Node.js version: 18
- NPM version:  7.13
- Strapi version: 4.11.1
- Database: postgres
- Operating system: Win11 Dev Container in VSCode
- Is your project Javascript or Typescript: JS

### Describe the bug

As i stated [here ](https://github.com/strapi/strapi/issues/16473#issuecomment-1578946443) data transfer "from" was working fine. My production site has an transfer-pull token.
But i think after upgrading from Node16 to 18, its not working anymore.
After `yarn strapi transfer --from xxx` and my token, i get the FATAL Error

`error: [FATAL] Failed to initialize the connection: Data transfer is not enabled on the remote host
Transfer process failed.` 

I tried to update my .env with `STRAPI_DISABLE_REMOTE_DATA_TRANSFER=false` but that did not help.

Is it not working with Node18 or am i missing something?

**Comment by Alexnortung** [comment]
I had the same issue, I fixed it by appending `/admin` at the end of the from url.
This might be a common mistake and it would be nice with a better error message here.

**Comment by shuffgy** [comment]
Thanks @Alexnortung , i tried it again on a fresh install, but that does not seem to be the problem.
First it missed the Transfer_token_salt. I forgot that in my .env. After adding that it failed with the same message (Data transfer is not enabled on the remote host.) 
Is there anything else i can look for?

**Comment by derrickmehaffy** [comment]
Can you check if the remote Strapi instance has a proper secret set for the transfer token?

![image](https://github.com/strapi/strapi/assets/8593673/45a0f410-6506-454f-9de3-2ea21be9510c)
