### ISSUE TITLE
Replace Media does not change photo preview

### ISSUE THREAD

**Issue by LishaValiyaparambil** [strapi/strapi#17010]
### Required System information
Node.js version: v16.17.0
Strapi version: v4.10.5
Database: postgres
NPM version: 6.0.0
Operating system: CentOs

### Describe the bug
After using the "Replace Media" option in the media library or by editing a image file in the collection itself, the preview of the image does not change even though the file has been updated.

### Steps to reproduce the behavior
Go to Media Library
Click on a previously uploaded image
Click the "Replace Media" button and select a new image
Click "Finish"
The error now is shown. While the image has been changed on the server, the preview in media library after the modal closes remains the original image.
You can confirm the replacement did work by refreshing the page, but will not see the change before this is done.

### Expected behavior
After replacing media, the preview image should be updated to reduce user confusion.

**Comment by startwarfields** [comment]
I was able to replicate this issue!
OS: Pop!_OS 22.04 LTS x86_64
Version:  4.11.1 (node v18.16.0)  

In Content Manger I created a single type (ads, for example) that is media, single upload.

Replacing an image does not correctly update the preview image, or the underlying image itself.

**Comment by LishaValiyaparambil** [comment]
@Boegie19 , I think the template is valid. Could you please check this before adding the flag.

**Comment by Boegie19** [comment]
The first template missed some information now it is much better thanks

**Comment by LishaValiyaparambil** [comment]
@kasonde any update on this will be appreciated. Thanks

**Comment by LishaValiyaparambil** [comment]
I have upgrded my strapi to latest versio. Yet i am facing the same issue. @danishjoseph. Any suggestions.

**Comment by derrickmehaffy** [comment]
> @LishaValiyaparambil I tested it with the most recent version, and it works fine on my end. Attachments are below. https://github.com/strapi/strapi/assets/104897204/5d9c4e1b-1172-4bbc-893d-cb85e4cd0dc1

Thanks for the confirmation, will close this for now until or unless we get updated reproduction steps.

**Comment by benjaminhera** [comment]
Someone from my team just encountered the issue now, please reopen. I cannot give you information on how to reproduce, but I can see that the preview shows the new file and the when in edit mode it shows the old one... Our frontend relies on the CMS to generate the pages and it's using the old image...
