### ISSUE TITLE
Textarea in Admin-panel is bugged

### ISSUE THREAD

**Issue by matibaski** [strapi/strapi#17028]
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.10.0
- Strapi version: 4.11.1
- Database: MariaDB 10.1.0
- Operating system: MacOS / Ubuntu Server 22.04
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Since upgrading to v4.11.1 all textareas are not functionable.

### Steps to reproduce the behavior

1. Go to any kind of Collection Type
2. Create new entry *or* edit existing entry
3. Click into textarea field
4. See that it's not working.

### Expected behavior

Possibility to change content within a textarea.

### Screenshots

See screenshare video:
https://github.com/strapi/strapi/assets/2587920/1723032c-20b3-41ef-b124-664dd5bb5eeb

### Code snippets

No code snippets, no custom overrides.

**Comment by joshuaellis** [comment]
What version of strapi were you on previously? There was a bug that caused this but we fixed it a few versions ago. I would run `yarn build` after you've upgraded if you haven't and failing that, deleting your `node_modules` and lock file _should_ do it.

**Comment by matibaski** [comment]
Deleting `node_modules`, `.cache` and `yarn.lock` and completely rebuilding solved the issue.
Thank you.

The issue appeared when I recently updated to `v4.11.1`
