### ISSUE TITLE
Unable to set false default value for boolean fields in the content type builder

### ISSUE THREAD

**Issue by soupette** [strapi/strapi#1704]
Node 10.7.0
npm 5.1.0
3.0.0-alpha.13.0.1

**What is the current behavior?**
Currently it's impossible to set the default value to false for boolean fields from the admin panel

**Steps to reproduce the problem**
- Create a content type
- Add a boolean field
- Go in advanced settings tab
- Click to set to true and then uncheck the checkbox (to make sure the value has been taken in account)

**What is the expected behavior?**
- Go to your model.settings.json you should be able to see the default value set to false

**Suggested solutions**
I don't know yet

**Comment by derrickmehaffy** [comment]
> Suggested solutions
> I don't know yet

Well shoot
