### ISSUE TITLE
Images using the S3 upload provider sometimes returns the CDN URL and sometimes the S3 signed URL

### ISSUE THREAD

**Issue by pablote** [strapi/strapi#17042]
### Required System information

- Node.js version:
- NPM version: v18.16.0
- Strapi version: 4.11.1
- Database: Postgresql
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

There's a weird behavior with image URLs and the API. I have @strapi/provider-upload-aws-s3 setup with Cloudfront (see config below), If I query for uploads and their respective URLs I get the Cloudfront URLs, but if I query a related entity, in my case "products" and their respective images and URLs, then I get an S3 URL with a signature. I most definetly don't want to expose the S3 URL to users and just use the Cloudfront one.

The images I'm showing are for the Graphql API, but the same happens with the REST API. I suppose a workaround for this is querying images and products separately and then joining the data myself, but it seems that Strapi should be handling this case better.

The query:

<img width="458" alt="image" src="https://github.com/strapi/strapi/assets/2463995/31799e35-01f1-4d61-95b3-250071d81872">

The uploads with Cloudfront URLs:

<img width="663" alt="image" src="https://github.com/strapi/strapi/assets/2463995/3ada8ce5-09c9-4aa2-820f-2125b4576260">

The products with S3 URLs:

<img width="656" alt="image" src="https://github.com/strapi/strapi/assets/2463995/72865b50-fc53-496e-a6a1-849da5fbb587">

S3 config:

<img width="601" alt="Screenshot 2023-06-20 at 6 43 38 PM" src="https://github.com/strapi/strapi/assets/2463995/752b5e78-609d-42f6-a9c2-34bebfd81ec8">

<img width="680" alt="image" src="https://github.com/strapi/strapi/assets/2463995/ee5aeb1d-e869-4943-b875-9b251c226a67">

### Steps to reproduce the behavior

1. Setup the S3 upload plugin with a config like mine (mostly taken from the docs)
2. Upload some images, create another content type which is related with images
3. Query through the API the URLs of the images
4. See how the related images use S3 URLs

### Expected behavior

I am expecting for Cloudfront URLs to be returned everywhere consistently.

Let me know if you need any more information to diagnose, thanks.

**Comment by Marc-Roig** [comment]
Hello, in the @strapi/provider-upload-aws-s3 settings, do you have your ACL set to private?

**Comment by pablote** [comment]
I do, yes.

**Comment by Marc-Roig** [comment]
Alright, this might have to do with the uploadFiles query not signing files, nevertheless I would not advise using a CDN with ACL set to private here. As the file signing will return the url of your bucket not your CDN.

https://github.com/strapi/strapi/blob/main/packages/providers/upload-aws-s3/src/index.ts#L76

You should see this warning message on startup also. 

Still, what you are showing is an issue that has to be fixed.

**Comment by Marc-Roig** [comment]
If what you needed is having signed URLs from cloudnfront, I would advise creating a custom provider, probably very similar to https://github.com/strapi/strapi/blob/main/packages/providers/upload-aws-s3/src/index.ts , just using  https://www.npmjs.com/package/aws-cloudfront-sign

**Comment by pablote** [comment]
Sorry if this seems confusing, but I don't need/want signed Cloudfront URLs, in part because that would break the browser cache like it's currently happening for the signed S3 URLs. That said, the files do need to be private and not publicly readable directly from S3. The current upload plugin + API setup seems to be confusing a bit the difference between the S3 setup and the Cloudfront setup.

To clarify a bit, I'm following what I understand to be the recommended setup for hosting images publicly. Files are private in S3, ACL are disabled, so no file is publicly readable straight from S3. Only the Cloudfront distribution can read files from S3 by means of a bucket policy. The files through the CDN are then publicly accesible, and the URL is not signed, making it always the same and browser cache friendly.

I'm not sure exactly where the separation between upload pluging and API is, but looking at what the upload does and what the DB data looks like, this seems to be correct:

<img width="1310" alt="image(1)" src="https://github.com/strapi/strapi/assets/2463995/10c4e03c-9ade-472f-b266-77be78694402">

It's the API that then decides, in some cases, not to return this URL and instead it calculates a signed S3 URL and returns that, and it shouldn't be doing that, or it should have an option to opt-out of that.

**Comment by Boegie19** [comment]
@Marc-Roig You forgot to add the status.

**Comment by ifightcrime** [comment]
I believe I'm running into the same issue since upgrading Strapi (and this plugin) from `^4.10.5` -> `^4.11.2` today.

I'm using the REST API. When I query a singular entry (e.g. `/api/entries/1`) the image urls return correctly using the `baseUrl` setting I have set (my CDN url). However, when I query the index page (e.g. `/api/entries`) the image urls are all incorrect and returns the direct S3 urls. This happens for multiple collection types. The singular endpoints always return the correct urls, and the index endpoints do not.

In addition, the Strapi admin started using the incorrect direct S3 urls. I first noticed this because they were all failing to load in the admin panel. Once I added the `xxx.s3.amazonaws.com` domain to my `contentSecurityPolicy` config to allow it they started working again.

Interestingly enough... downgrading Strapi back to what I had manually in `package.json` didn't fix the problem directly. However, doing a full revert on my commit (which also reverted whatever changed in package-lock.json) did! So it's likely some related dependency not directly in my package.json that's causing the issue.

<img width="1159" alt="Screenshot 2023-06-22 at 8 50 49 PM" src="https://github.com/strapi/strapi/assets/616525/caadcbaa-dca9-413e-9afc-b79d342d9ef2">

**Comment by Marc-Roig** [comment]
> It's the API that then decides, in some cases, not to return this URL and instead it calculates a signed S3 URL and returns that, and it shouldn't be doing that, or it should have an option to opt-out of that.

If your upload plugin configuration sets the ACL to be private, you will have that behaviour.
So if you unset the attribute or set it to 'public-read' it should fix the behaviour and always return the cloudfront url

**Comment by Marc-Roig** [comment]
In recent releases, we changed the way we sign URLs, to give a bit of context:
- URLs will always be signed if ACL is set to true. As explained in the docs https://github.com/strapi/strapi/blob/main/packages/providers/upload-aws-s3/README.md#configuration-for-a-private-s3-bucket
- If you are also using a CDN, the upload plugin will just sign the URLs and return the s3 bucket urls, and NOT using the CDN base URL.

Signing urls using a CDN  is a technical limitation that can only be solved by creating a custom upload plugin. If on the contrary you don't need signed URLs, you should not set the ACL to private.

**Comment by pablote** [comment]
```
If your upload plugin configuration sets the ACL to be private, you will have that behaviour.
So if you unset the attribute or set it to 'public-read' it should fix the behaviour and always return the cloudfront url
```
I see, that doesn't seem right though. That's assuming that because I need the objects private in S3 that I want them to be accessed using signed URLs, which might not be the case. I did tried that change btw, and got this:
<img width="787" alt="image" src="https://github.com/strapi/strapi/assets/2463995/0205047f-79c6-475b-887d-c53010960107">

Enabling ACLs in S3 in not a possibility for me, AWS doesn't recommend it and it's seen as a bad practice. I think this should be two different config settings, the current `ACL` one, which just set permissions on the S3 object, and another setting controlling whether you want the public URL signed or not. I guess that if the second setting is not specified, and no CDN is specified, you can assume the current behaviour that ACL=private automatically triggers a signed URL, but othewise, it's just assuming too much.

**Comment by Marc-Roig** [comment]
You are completely right , and your proposal seems a very nice solution here. I will add another parameter to set if files should be signed or not. I will post a follow up this week about this and hopely have a PR ready 🚀 .

**Comment by pablote** [comment]
Awesome, thanks for considering all this. Let me know if I can help with anything, testing maybe.

**Comment by Marc-Roig** [comment]
Hello! Sorry for the delay but I have opened a PR to fix this issue :) 
In case you want to test it I have created an experimental release : `0.0.0-experimental.133ddc2de4e58dc1eb476fda8e0a67b0f1ee6e74`

We will probably be releasing this next week in 4.11.4 though 🚀
