### ISSUE TITLE
Cropping only works in the uploading flow - does not work on images in media library

### ISSUE THREAD

**Issue by muffeeee** [strapi/strapi#17068]
### Required System information

- Node.js version: 18.16.1
- NPM version: 9.5.1
- Strapi version: 4.11.2 - however I have experienced this at least since 4.6, possibly before
- Database: Either
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript
- Browser: Chrome/Safari

### Describe the bug

Cropping an image that has already been uploaded to the media library does not work

### Steps to reproduce the behavior

1. Upload an image to the media library
2. Go to a document/collection item that has a media type in it
3. Add the image to a media field
4. Click the "Edit" button on the image
5. Click the "Crop" button
6. Observe that there is no crop box. You are unable to crop.

### Expected behavior
I expect to be able to crop the image.

### Screenshots
This is what it looks like for already uploaded images:
<img width="829" alt="Screenshot 2023-06-22 at 23 09 44" src="https://github.com/strapi/strapi/assets/3154984/b1dea800-209c-4804-8eb2-ae5aad713b27">

This is what it looks like when you try to crop it as you upload it (expected behaviour):
<img width="842" alt="Screenshot 2023-06-22 at 23 12 14" src="https://github.com/strapi/strapi/assets/3154984/d8fedf46-1257-4407-9cf1-2314e8047b08">

### Additional context
Just note that this works perfectly if you try to crop the image as you upload it, but not when it already exists in the media library. This means that for any image that exist in the media library, if you want to crop it on a later stage, you have to download and re-upload the image as a work-around.

**Comment by jhoward1994** [comment]
Hi, thanks for reporting this issue. I've reviewed it but can't seem to reproduce this behaviour, I am able to crop assets during or after upload. 

https://github.com/strapi/strapi/assets/48524071/5e8a5bed-4a2a-4c57-8526-6ff855060813

Please could you test again with the latest version of Strapi?

**Comment by brendengerber** [comment]
Hi, I am having this issue as well. Cropping works just fine on initial upload, but after returning to the photo, the button is there, but clicking it does nothing. I am pretty new to Strapi, but one thing I can think of is that it has something to do with using S3 as a provider for media uploads. I will leave a link to my github repo with the version and modifications I have done on it in case it helps your reproduce this error. 

https://github.com/brendengerber/strapi-for-dokku-custom.git

I have Strapi hosted on Digital Ocean using Dokku (open source Heroku), it is connected to a postgres database, and is using S3 for media storage.  I am happy to provide any other info you might need for reproduction. Is it alright to post this here, or would it be better to open a new issue?
