### ISSUE TITLE
TypeError: Argument of type 'string' is not assignable to parameter of type 'never'.

### ISSUE THREAD

**Issue by Yum1x** [strapi/strapi#17088]
### Required System information

- Node.js version: **v18.16.0**
- NPM version: **v9.5.1**
- Strapi version: **v4.11.2**
- Database: **Postgres 15**
- Operating system: **Windows 11 & Ubuntu 22.04**
- Is your project Javascript or Typescript: **Typescript**

### Describe the bug
After v4.11.1 this type error messages shows in default controllers/services/router and I didnt know how proceed, i'm learning typescript so I didnt know solve this.
unsure but this (https://github.com/strapi/strapi/pull/16917) should be relationed
### Expected behavior

Default controllers/services/routes shouldnt throw any error.

### Screenshots

![image](https://github.com/strapi/strapi/assets/46856347/84a66894-20b0-4c3c-8a07-3575e7cbce2c)

**Comment by Boegie19** [comment]
Strapi version: v4.12.0 does not exist if you mean v4.11.0 try to go to v4.11.2 and see if that fixes it

**Comment by Yum1x** [comment]
> Strapi version: v4.12.0 does not exist if you mean v4.11.0 try to go to v4.11.2 and see if that fixes it

Fixed! sorry 😅

**Comment by Yum1x** [comment]
Identified as IDE(Webstorm Jetbrains) bug not Strapi Project bug, solved when updating to 2023version, closing the issue.
