### ISSUE TITLE
Expose users to API

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1708]
**What is the expected behavior?**

It is currently not possible to find the users as guest or set that guests are able to find users.
This makes it impossible to create public user lists.

**Comment by sdubrez** [comment]
Did you try to gives some permissions to **Public** group on the **Users Permissions** plugin ?

Role & Permission > Users-Permissions > User > Create
https://i.gyazo.com/8698a0e01fd49eb95ff8d3ad0e711507.png

**Comment by MartinMuzatko** [comment]
By the way, while graphql does not allow access to `users {}` I can get all of the users information via related objects

**Comment by MartinMuzatko** [comment]
@sdubrez thanks for the quick reply! Yes this is the problem! I guess I can close this issue.
I expected it to find it as part of the models, but since it comes from a plugin, this makes perfect sense.
