### ISSUE TITLE
Collection unusable after making changes to dynamic zone and components. Ongoing across many Strapi versions and results in data loss.

### ISSUE THREAD

**Issue by cooperwfloyd** [strapi/strapi#17086]
### Required System information

- Node 18.16
- NPM 9.5.1
- Strapi 4.11.2
- Postgres Database
- Docker deployment on Google App Engine
- JavaScript

### Describe the bug and steps to reproduce

This is a follow-up to [this comment](https://github.com/strapi/strapi/issues/16966#issuecomment-1598858677) on issue #16966. Noticing on most recent Strapi version and below.

After making changes to a component and including it in a dynamic zone, attempting to access a collection in the Strapi admin results in an infinite load. There is a console error appearing and It is a consistent issue because it happens on every component change that is pushed. It's hitting a layouts.edit.reduce in the configuration.json that it's looping through when loading the collection in the CMS, so I pulled the response from that file and found that the new components that were created don't have a layouts.edit property. The components are structured exactly the same as every other component in the build that is working correctly.

Totally bricked on accessing the collection, and restarting the CMS temporarily gets around the error but causes data loss of any uses of that component in entries on that collection. Then, when adding the component back, it might work for a bit, but then bricks up again without any changes after a while. Getting a large number of GraphQL "internal server error" messages when it starts acting up as well.

**Comment by joshuaellis** [comment]
Hey, sorry to see you're having issues, but i can't seem to see any reproduction steps, can you please follow the template? 

It's super hard to debug something when we don't have reproduction steps. Also what plugins are you using? If you're using any external ones have you tried removing those to make sure it's something wrong with the core app as opposed to a plugin?

Thanks in advance.

**Comment by cooperwfloyd** [comment]
Sure, @joshuaellis I'll deconstruct the reproduction steps from that description and list plugins.

## Reproduce
- Create new component and add it to a collection's dynamic zone field
- Merge branch to production and await deployment
- After deployment, component is usable and able to be added to dynamic zone on production
- After saving component in an entry in that collection, attempting to access the collection at `/content-manager/collectionType/api...` results in an infinite load within the UI and provides the console error when hitting a layouts.edit.reduce in the configuration.json that it's looping through when loading the collection in the CMS. Pulled the response from that file and found that the new components that were created don't have a layouts.edit property in the object that the frontend is referencing in the configuration.json. The component is structured exactly the same as every other component in the build that is working correctly.
- Also getting a large number of GraphQL "internal server error" messages when attempting to query data while this is going on.
- Restarting the server after the stall allows the collection to work within the UI again, but results in total data loss of every instance of that component, even though the component is still present and able to be used in the dynamic zone.

## Plugins
- @strapi-community/strapi-provider-upload-google-cloud-storage@latest
- strapi-plugin-config-sync@latest
- strapi-plugin-entity-relationship-chart@latest
- strapi-plugin-preview-button@latest
- strapi-plugin-publisher@latest
- strapi-plugin-sitemap@latest
- strapi-plugin-vercel-deploy@latest

**Comment by cooperwfloyd** [comment]
[this issue](https://github.com/strapi/strapi/issues/16836) and [this issue](https://github.com/strapi/strapi/issues/16893) seem to be closely related, found that we're getting the same 'relation does not exist' in the backend and getting similar behavior to both

**Comment by joshuaellis** [comment]
@cooperwfloyd Thanks for the information, can you remove your plugins and then retest so we can be certain it's not a plugin causing the issue?
