### ISSUE TITLE
Adding SSL certificate on strapi

### ISSUE THREAD

**Issue by haidnvnn18** [strapi/strapi#171]
I want to config SSL or enable https on strapi
I'm seeing place where to config enable SSL but I can't find anywhere to add key or cert into it
Could you help me to clear more details about it?

**Comment by Aurelsicoko** [comment]
Thanks for this issue!

On the next version (v3), Strapi uses [koa-sslify](https://github.com/turboMaCk/koa-sslify/tree/koa2) to handle SSL. Currently, Strapi only supports the reverse proxy case. Despite this, I recommend managing SSL on a higher level which means with a Nginx server in front of your Node.js app.

I know that the support could be more complete, and we have to improve the SSL support on Strapi. But, we should also separate that from the core, IMO. It could be an external hook or a dedicated plugin.

**Comment by Aurelsicoko** [comment]
I'm giving you updates on this one. We decided to remove the SSL middleware from the Strapi core. There are many reasons for that. The first one is that with the new HTTP/2 protocol integrated into the core of Node.js, a lot of things are going to change. Then, we recommend handling SSL using nginx or Caddy. They are better than Node.js to do this and it's a very common architecture. 

We will write tutorials to explain to everyone how to implement SSL with Strapi.

**Comment by derrickmehaffy** [comment]
@SupremeTechnopriest This is not an un-common solution to node.js projects, generally speaking most node.js projects run on localhost and a proxy is generally used to display it over port 80/443. Nginx is extremely simple to setup for proxying SSL to a local service.

**Comment by SupremeTechnopriest** [comment]
You cant set up nginx on heroku.  I dont want proxies in front of my server.

**Comment by SupremeTechnopriest** [comment]
You should have used express instead of koa.  KOA is trash.

**Comment by derrickmehaffy** [comment]
@SupremeTechnopriest then should you feel a feature should be added, maybe you can help develop such a feature or plugin yourself? Else if you feel the project should be done differently I'm sure your welcome to fork the project and rebuild it how you feel, the source code is open source.

**Comment by SupremeTechnopriest** [comment]
Ill just write my own cms.  All good.  Go ahead and thumbs down some more.  Ill be sure to let everyone i know not to use strapi.

**Comment by SupremeTechnopriest** [comment]
No SSL.... LOL

**Comment by derrickmehaffy** [comment]
@SupremeTechnopriest just in case you decide to change your mind, here is a nice guide for node.js and nginx: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by Aurelsicoko** [comment]
@SupremeTechnopriest I recommend you to read [this article from RisingStack](https://blog.risingstack.com/node-js-10-lts-feature-breakdown/).

> There’s a catch, however, as browsers only support HTTP/2 over SSL. SSL termination is a CPU intensive task so it should be handled by the edge proxy. Nginx supports all the functionality HTTP/2 provides since its 1.13.9 release. **It is a best practice to have an edge proxy in front of your Node server**, so you can expose port 80 and 443 as you don’t want your Node process to run as superuser and this way you can setup HTTP push and TLS termination outside your server code.

It's a very common pattern to use a nginx in front of a Node.js server.

**Comment by SupremeTechnopriest** [comment]
Appreciate it.  I've installed 1000s of nginx services in the past.  It's not that I'm lazy, its that its impossible on heroku (my clients preferred deployment).  Stapi is also their preferred backend. So I'm stuck between a rock and hard place. The only solution here is to move ssl to the DNS level with cloudflare.  Thank god for cloudflare.

**Comment by derrickmehaffy** [comment]
And since on linux based systems you can't run a service on a port below 1024 unless your a superuser.

But yes @SupremeTechnopriest cloudflare is another option to secure strapi if you can't run something like nginx in front of it.

**Comment by SupremeTechnopriest** [comment]
It seems a bit premature to be ripping out SSL from your project IMO.  Node wont have http/2 in LTS for a long time... From other issues im seeing here, it looks like you didn't have much choice in the matter, because KOA is not good and still requires iojs or something.

**Comment by Aurelsicoko** [comment]
Okay, it makes more sense! However, it's not the right thing to tell that the project is "shit" because we don't want to handle the SSL part. We're doing the right thing (best practice) and avoid bad performances for our users. I know it can be tricky (especially in your case) but it doesn't mean it's our fault.

This good practice doesn't come with HTTP/2, it has always been the right way to handle SSL with a Node.js server. It's not something new. Also, Koa is one of the best frameworks in Node.js with Express and Hapi. It handles perfectly the `async/await` pattern, it's more lightweight and performant than Express or Hapi. You don't need to agree with it, it's just fact. 

Anyway, I wish you good luck with your project and I hope you'll be able to find a solution.

---- 

Take a look at this middleware https://www.npmjs.com/package/koa-sslify, you can install it in your project and inject it in the Koa stack easily from the `./config/functions/bootstrap.js` file or create a custom middleware.

```js
'use strict';

/**
 * An asynchronous bootstrap function that runs before
 * your application gets lifted.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */

const enforceHttps = require('koa-sslify');

module.exports = cb => {
  // Force HTTPS on all page 
  strapi.app.use(enforceHttps({
    trustProtoHeader: true
  }));
  
  cb();
};
```

**Comment by hrdunn** [comment]
@SupremeTechnopriest Any luck on that SSL script? Would love to know if you were able to figure this out.

**Comment by SupremeTechnopriest** [comment]
@hrdunn It really depends on your use case... If you have Strapi working then thats great.  Its a cool product, when it works.  Unfortunately for me it constantly breaks.  From now on ill be rolling my own api/ cms for any project that needs it.  Theres not that many options in node.js.  Anytime I write a blog I use ghost.  Love ghost.

**Comment by Aurelsicoko** [comment]
@SupremeTechnopriest I'm sorry you encountered some many issues. We are doing our best to make the product better and better. However, please respect our work and the community members who are trying to improve the product every day.

I think you misunderstand what open-source is. It means that if you have bugs you can report them or fix them. You're not paying anything and no one forced you to use Strapi. If you're not happy with it, it's okay but please doesn't tell us it's crap. We are humans, not robots. Nothing is perfect, especially when the project is still in alpha...

I'm locking this conversation, we don't want to see bad comments like this. You can complain but there are some basic rules that need to be respected.
