### ISSUE TITLE
Page can't load if related element is not set yet/main text value is missing

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1710]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 6.0.1
- **Strapi version**: 3.0.0@alpha-13.0.1
- **Database**: pg (same effect on mongo db)
- **Operating system**: WSL/ubuntu

**What is the current behavior?**

Can't load a page of a content element for an element that has related data to an element, the page turns blank after attempting to load and display the contents.
I'm not sure if this is the exact root cause of the problem.

![image](https://user-images.githubusercontent.com/2950505/43786955-2c4a174c-9a6a-11e8-8fac-9c120469f19f.png)

used url: `http://localhost:1337/admin/plugins/content-manager/event/1?redirectUrl=/plugins/content-manager/event?_limit=10&_page=1&_sort=id&source=content-manager`

**Steps to reproduce the problem**

Models:
Event:
``` json
"attributes": {
    "name": {
        "type": "string"
    },
    "createdUser": {
        "model": "user",
        "via": "eventsCreated",
        "plugin": "users-permissions"
    },
    "registrations": {
        "collection": "registration",
        "via": "event"
    },
    "homepage": {
        "model": "page"
    },
    "pages": {
        "collection": "page",
        "via": "event"
    }
}
```

Registration
``` json
"attributes": {
    "user": {
        "model": "user",
        "via": "registrations",
        "plugin": "users-permissions"
    },
    "event": {
        "model": "event",
        "via": "registrations"
    },
    "attendeeStatus": {
        "enum": [
            "new",
            " pending",
            " accepted",
            " waiting",
            " banned"
        ],
        "default": "new",
        "type": "enumeration"
    },
    "paid": {
        "type": "date"
    }
}
```

Page
``` json
"attributes": {
    "user": {
        "model": "user",
        "via": "pages",
        "plugin": "users-permissions"
    },
    "slug": {
        "type": "string"
    },
    "title": {
        "type": "string"
    },
    "metaImage": {
        "model": "file",
        "via": "related",
        "plugin": "upload"
    },
    "metaTitle": {
        "type": "string"
    },
    "metaDescription": {
        "maxLength": 180,
        "type": "text"
    },
    "contentModules": {
        "collection": "contentmodule",
        "via": "page"
    },
    "event": {
        "model": "event",
        "via": "pages"
    }
}
```
ContentModule
``` json
"attributes": {
    "settings": {
        "type": "json"
    },
    "page": {
        "model": "page",
        "via": "contentModules",
        "dominant": true
    }
}
```

This is what the page looks like before the data attempts to load, fails and gets blank:

![image](https://user-images.githubusercontent.com/2950505/43787580-9d46717e-9a6b-11e8-92ac-36284d19888f.png)

**What is the expected behavior?**

Load and display the model/element

**Suggested solutions**

At least show an error message or suggestions how to fix the required data structure

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues.
Please check https://github.com/strapi/strapi/issues/1230
