### ISSUE TITLE
Add component above/below menu options overflows the menu box

### ISSUE THREAD

**Issue by lowlander1982** [strapi/strapi#17107]
### Required System information

- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: 4.11.1
- Database: postgres
- Operating system: macOS Ventura 13.4.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When you have a type with a dynamic zone that has more than 6 different components configured as possible options for the dynamic zone, once you are in the entry editor and you want to add a component above/below you see the menu overflowing the menu white box

### Steps to reproduce the behavior

1. Create a collection type
2. Create a dynamic zone for that collection type
3. Create 7 components inside that dynamic zone
4. Go to the collection type entry editor and create a new entry
5. Add some components to the dynamic zone
6. Notice that if you want to use the new "Add component above" or "Add component below" the component options overflow the menu white box

### Expected behavior

The menu options should not overflow, maybe they could be scrolled inside or the box could grow as much as needed

### Screenshots

<img width="530" alt="Screenshot 2023-06-26 at 11 12 35 AM" src="https://github.com/strapi/strapi/assets/7319562/eae2e3d8-e577-4fbb-af71-b9b861c0b924">

**Comment by joshuaellis** [comment]
Thanks for the report, this has been fixed in our design system and should be released next week.
