### ISSUE TITLE
Publish doesn't work with old records after updating to 4.11.2: "ValidationError field must be defined"

### ISSUE THREAD

**Issue by atresca-globant** [strapi/strapi#17119]
### Required System information

- Node.js version: 14.17.2
- NPM version: 6.14.13
- Strapi version: 4.11.2
- Database: MongoDB
- Operating system: Windows 10
- Is your project Javascript or Typescript: JS

### Describe the bug

We uploaded our dependencies to 4.11.2 and tried to Publish old records (16K records in MongoDB already) getting ValidationError for fields that already exists.

**POST with error**
![image](https://github.com/strapi/strapi/assets/72890641/df94d9ee-e1cd-4816-9861-66697159a483)

 **GET with old records that already have the conflicting fields defined and with data**
![image](https://github.com/strapi/strapi/assets/72890641/4e031e33-5507-44fa-af0a-f6c445b8cf19)

- Notice an old [issue](https://github.com/strapi/strapi/issues/8938#issuecomment-748044896) that it can be a problem with Mongo fields initialization, but I do not understand how that can be our case since we already have all fields defined and with published data.

- Also tried unpublishing records (which does work) and publishing again and the publish fails.

**These are the libraries we updated to latest version:**
 
- "@strapi/logger": "4.11.2",
- "@strapi/plugin-graphql": "4.11.2",
- "@strapi/plugin-i18n": "4.11.2",
- "@strapi/plugin-users-permissions": "4.11.2",
- "@strapi/provider-upload-aws-s3": "4.11.2",
- "@strapi/strapi": "4.11.2",

    
### Steps to reproduce the behavior

1. Go to a any collection using latest Strapi version with Mongo DB
2. Change some data
3. Click on Publish

### Expected behavior

We expect for old records that already have fields defined to be published

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by davimdantas** [comment]
We are facing the same issue. 
Every collection that has a relation field or a single nested component is returning this ValidationError.

**Required System information**
Node.js version: 18.16.0
Yarn version: 1.22.19
Strapi version: 4.11.2
Database: postgres 
Operating system: macOS 13.3.1
Is your project Javascript or Typescript: Typescript

**Comment by flavioms** [comment]
Same problem here, but mostly on collections that use the [SEO plugin](https://market.strapi.io/plugins/@strapi-plugin-seo):

Node.js version: 18.16.0
NPM version: 9.5.1
Strapi version: 4.11.2
Database: PostgreSQL
Operating system: MacOS
Is your project Javascript or Typescript: Typescript

<img width="761" alt="Screen Shot 2023-06-27 at 16 56 35" src="https://github.com/strapi/strapi/assets/11588405/341e2f34-8f27-4b59-a20a-f3a491fc32f6">

```
    "@strapi/design-system": "^1.8.0",
    "@strapi/icons": "^1.8.0",
    "@strapi/plugin-color-picker": "^4.11.2",
    "@strapi/plugin-i18n": "4.11.2",
    "@strapi/plugin-seo": "^1.9.2",
    "@strapi/plugin-users-permissions": "^4.11.2",
    "@strapi/strapi": "4.11.2",
    "@strapi/utils": "^4.11.2",
```

**Comment by atresca-globant** [comment]
Downgrading to 4.10.7 (our previous version) solved the issue. Just in case is useful for someone.

**Comment by Marc-Roig** [comment]
hello, this issue should be fixed in 4.11.3 https://github.com/strapi/strapi/pull/17112
Could you try and see if it solves for you?

**Comment by PandaaAgency** [comment]
I was facing the same issue but upgrading to `4.1.13` has solved it.

**Comment by Marc-Roig** [comment]
I will close the issue for now:) If anyone else reports this is still a problem I will reopen it!
