### ISSUE TITLE
Can't sort or filter related media in graphql

### ISSUE THREAD

**Issue by sambernard** [strapi/strapi#17132]
### Required System information

- Node.js version: v18.15.0
- NPM version: 9.5.0
- Strapi version: 4.10.1
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

1. Create a content type with an attribute that stored multiple media
2. Query the entity and it's associated media. Apply sort and filter args to the media
4. Result: `images` are returned without being sorted or filtered.

### Expected behavior

Sorting or filtering related media should result in a response that is sorted/filtered

### Screenshots
Relevant code setting uid for media association

<img width="872" alt="Screen Shot 2023-06-28 at 4 15 00 PM" src="https://github.com/strapi/strapi/assets/170295/ece83f95-8f23-4b66-b73e-67159aa8b128">

Filtering the sort/filter params based on the model
<img width="932" alt="Screen Shot 2023-06-28 at 4 17 44 PM" src="https://github.com/strapi/strapi/assets/170295/7ec0b3d3-afe2-437a-9618-46dc6d1eba72">

Value of vars present
<img width="522" alt="Screen Shot 2023-06-28 at 4 14 47 PM" src="https://github.com/strapi/strapi/assets/170295/f797814d-5440-412d-bf8d-75a3876b622c">

List of valid uids for strapi instance
<img width="436" alt="Screen Shot 2023-06-28 at 4 15 35 PM" src="https://github.com/strapi/strapi/assets/170295/1c4fd7b2-9749-4937-999d-22669187856a">

### Code snippets

GQL Query
```gql
query SortAndFilter {
  items {
    data {
      id
      attributes {
        name
        images(sort: ["name:asc"], filters: { width: { lt: 100 } }) {
          data {
            id
            attributes {
              name
              width
              height
              provider
            }
          }
        }
      }
    }
  }
}
```

### Additional context

I interactively debugged the code and determined that the incorrect uid (`plugins::upload.file` instead of `plugin::upload.file`)  is being used for the image plugin, which results in any passed sorting/filtering (with the exception of `id`) getting removed from the query by `sanitize.contentAPI.query`.

Relevant Line to fix: https://github.com/strapi/strapi/blob/75275de7f5e35431a002d6228f57544fb4e20b4f/packages/plugins/graphql/server/services/builders/resolvers/association.js#L31

**Comment by alexandrebodin** [comment]
This was fixed end of last year. Closing :)
