### ISSUE TITLE
Running strapi import does not restore images of components in dynamic zones of single types

### ISSUE THREAD

**Issue by canta2899** [strapi/strapi#17134]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.6
- Strapi version: 4.11.3
- Database: PostgreSQL
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Running strapi import does not restore media images inside components of single types. For example, in my "HomePage" single type I have a "Header" component which contains a title and an image. After reimporting from a strapi export, the HomePage contains the header component with the title correctly populated while the image is not. The image is, however, present in the media library.

### Steps to reproduce the behavior

1. Create a component with an image field of type Media
2. Create a single type
3. Add the component to the single type or create a dynamic zone
    - If the dynamic zone was created, populate it with the previously created component
4. Assign an image to the image field of the component
5. Shutdown strapi
6. Run `strapi export --`
7. Clear the database (I'm using docker so I would run a new instance)
8. Run `strapi import -- -f path/to/export.tar.gz.enc`
9. Run `strapi run develop`
10. Login to the admin panel
11. Go to the single type and observe that the component as no image assigned

### Expected behavior

Importing from a previously exported data should reassign images to components event in dynamic zones of single types.

**Comment by canta2899** [comment]
Just found out this was already mentioned in #16813

**Comment by derrickmehaffy** [comment]
Ah thanks @canta2899 will close this as a duplicate in favor of https://github.com/strapi/strapi/issues/16813
