### ISSUE TITLE
Rich text editor scrolls top of the textarea when clicking on any formats in the "More" menu

### ISSUE THREAD

**Issue by sven-ra** [strapi/strapi#17136]
## Rich text editor scrolls top of the textarea when clicking on any formats in the "More" menu

Clicking on any of the formats in the "More" menu scrolls to the top of the rich text textarea field.
For example clicking on bullet list or numbered list.

### Required System information

- Node.js version: LTS
- NPM version: LTS
- Strapi version: 4.11.3
- Database: Postgres
- Operating system: MacOS
- Typescript

### Steps to reproduce the behavior

1. Go to any marddown rich text field which has more content than can fit the textarea
2. Click on 'More' button
3. Click on __any__ of the formats
4. Textarea scrolls to the beginning

### Expected behavior

Textarea not to scroll top, since this makes the text editors life very hard.

### Screenshots
<img width="994" alt="image" src="https://github.com/strapi/strapi/assets/16561130/b78a781f-792b-49a7-a27d-d817316e4e9a">

**Comment by derrickmehaffy** [comment]
I believe we are in the process of completely redoing the WYSIWYG Editor to an entirely new one that will be released within the v4 lifecycle, we may not have the time to fix this issue directly but I would imagine it would be resolved with the new editor.

**Comment by simplypixi** [comment]
Do you have any updates on this? It's totally annoying - especially while long-text editing. :(

**Comment by nick-aj** [comment]
We just noticed that this issue was previous reported in the following GitHub Issue:
https://github.com/strapi/strapi/issues/16847
I will be closing this one as a duplicate and adding the additional info in the comment of the above mentioned one.

Please follow that one for updates instead.
