### ISSUE TITLE
How to use Joi-router to validate API request

### ISSUE THREAD

**Issue by hvmk** [strapi/strapi#1713]
Hi team,

I tried configuring to use joi-router flow this ticker : https://github.com/strapi/strapi/pull/158
But it does not work, can you help me to guide how to use it.

**Informations**

- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13
- **Database**: mongo
- **Operating system**: Windows 10

Thanks.

**Comment by derrickmehaffy** [comment]
@hvmk that issue I believe is from strapi v1 and no longer applies to v3

Validations aren't handled by default right now, I'm sure it can be done with policies and better support for validations are coming.

**Comment by hvmk** [comment]
Hi @derrickmehaffy ,

Thank you for informing.
