### ISSUE TITLE
Error Input Date

### ISSUE THREAD

**Issue by Ironsites** [strapi/strapi#17148]
main.9b975ded.js:77 Uncaught RangeError: Invalid time value

When a date exists in the date input and it is removed, it throws an error and is not written to the database.
I noticed this in version 4.11.0

![Captura de pantalla 2023-06-29 150214](https://github.com/strapi/strapi/assets/90522949/d2c6bff5-00c3-4034-970e-f4a19345f6ae)
![Captura de pantalla 2023-06-29 150316](https://github.com/strapi/strapi/assets/90522949/b1a43038-f381-41fc-8c7d-b7eb14ebb057)

**Comment by joshuaellis** [comment]
Can you try upgrading?
