### ISSUE TITLE
Concurrency bug when uploading files in parallel with API and "API Uploads" directory doesn't exist

### ISSUE THREAD

**Issue by marob** [strapi/strapi#17142]
This is a placeholder issue because https://github.com/strapi/strapi/issues/16071 has been closed for incorrect reasons and has still not been re-opened.

**Comment by joshuaellis** [comment]
I've replied on your other issue. Whilst I appreciate two weeks feels like a long time, this isn't unusual with open source projects so please try not to do this in the future :)

The discord is also a helpful place – have you joined it? https://discord.gg/strapi
