### ISSUE TITLE
S3 Plugin - Private ACL use with CDN Generates Signed URL (Inverted Logic)

### ISSUE THREAD

**Issue by travisdieckmann** [strapi/strapi#17144]
### Required System information

- Node.js version: 18.15.1
- NPM version: 9.5.0
- Strapi version: 4.11.3
- Database: Postgres 15.2
- Operating system: Alpine 3.18
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When setting the S3 Plugin ACL property to `private` and utilizing a CDN, the plugin generated a signed S3 URL instead of utilizing the CDN URL. This is incorrect.

### Steps to reproduce the behavior

1. Configure S3 plugin with S3 bucket and CDN
2. Upload object to Strapi
3. Utilize REST API to retrieve object URL

### Expected behavior

The expected behavior is to set the object ACL in S3 to `private` and return the CDN URL to access the object.

### Screenshots

N/A

### Code snippets

Variable mis-identification resulting in an inverted logic bug.
(https://github.com/strapi/strapi/blame/1b09113fc3d40565c8db3bb3d953e6578b09f081/packages/providers/upload-aws-s3/src/utils.ts#L8)

Recommendation (choose one):
1. In function `isUrlFromBucket`, rename `bucketBaseUrl` to be `baseUrl` and invert URL comparison in return
4. When calling `isUrlFromBucket` from index.ts, pass the bucketUrl in the 3rd argument instead of baseUrl

Additional recommendation post remediation:
[Remove this warning](https://github.com/strapi/strapi/blob/1b09113fc3d40565c8db3bb3d953e6578b09f081/packages/providers/upload-aws-s3/src/index.ts#L74)

### Additional context

N/A

**Comment by Boegie19** [comment]
@Marc-Roig the private url thing is actually a a breaking change if yo where on v4.9.1 
Since back then it gave you the CDN url but made your bucket private.

So strapis output changed without him just updating the version

**Comment by Boegie19** [comment]
related to https://github.com/strapi/strapi/issues/17042

**Comment by Marc-Roig** [comment]
@Boegie19 before 4.9.1 you could not set your ACL to be private

**Comment by travisdieckmann** [comment]
We upgraded to 4.9.1 to have ACL = `private` with CDN usage.

**Comment by Marc-Roig** [comment]
I see, I will check what we can do.

**Comment by Boegie19** [comment]
@Marc-Roig Fix would be simple introduce a new key to set signed or cdn url and just default to the cdn url

**Comment by Marc-Roig** [comment]
Agree, we will not be signing files if using a CDN.

**Comment by travisdieckmann** [comment]
So there are 2 factors to using the S3 plugin:
1. Setting the correct ACL on the S3 objects
2. Returning a pre-signed URL.

These are NOT mutually exclusive. I should be able to set ACL = `private` to satisfy security requirements on the S3 objects themselves in the bucket.

CloudFront accesses the S3 object as an authenticated identity. This allows S3 objects to be private yet the CloudFront URL can be used to access the object in S3.

Therefore, I do not need/want a presigned URL when using a CDN.

**Comment by Marc-Roig** [comment]
you are completely right @travisdieckmann , we did not take that into account when defining `isUrlFromBucket`. I think your proposals are actually what should be done here :) I am creating a PR right now

**Comment by Marc-Roig** [comment]
I created a new PR https://github.com/strapi/strapi/pull/17145 , and I am doing an experimental release so you can test it (if possible)

**Comment by Marc-Roig** [comment]
In case you want to test it here is the experimental release : `0.0.0-experimental.133ddc2de4e58dc1eb476fda8e0a67b0f1ee6e74`

We will probably be releasing it next week in 4.11.4 though 🚀

**Comment by Marc-Roig** [comment]
And thank you again for the feedback and providing such detailed description of the problem, it's a pleasure to work on issues like this one 👏

**Comment by travisdieckmann** [comment]
This has resolved the issue! Thanks for the quick turn-around! :clap:
