### ISSUE TITLE
Support for mysql over unix socket

### ISSUE THREAD

**Issue by adamquaile** [strapi/strapi#1714]
I've marked this as a feature request, because I don't _think_ this functionality exists. If it does, this is either me doing something wrong, or a lack of documentation, or both. 

**What is the expected behavior?**
It'd be great to be able to use a mysql database connecting via a unix socket instead of the host/port combination. 

Ideally this would be an option in the `strapi new` command and the admin ui, but support via the environment config file would suffice, too. 

Per some suggestions in slack I tried the following, with no luck:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 3306}",
        "user": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "database": "${process.env.DATABASE_NAME || 'strapi-production'}",
        "socketPath": "/var/run/mysqld/mysqld.sock"
      },
      "options": {
        "ssl": false
      }
    }
  }
}
```

and 

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 3306}",
        "user": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "database": "${process.env.DATABASE_NAME || 'strapi-production'}"
        
      },
      "options": {
        "ssl": false,
        "socketPath": "/var/run/mysqld/mysqld.sock"
      }
    }
  }
}
```

**Comment by lauriejim** [comment]
Hello @adamquaile , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by Aurelsicoko** [comment]
This issue can be closed because we're supporting it (see https://github.com/strapi/strapi/blob/master/packages/strapi-hook-knex/lib/index.js#L100).

@adamquaile Can you confirm?

**Comment by pelayomendez** [comment]
Helllo.

I have been trying to use this feature to connect an Strapi app installed in Google Cloud App Engine  to Cloud SQL. Connection to the database in this scenario should be perfomed over unix socket.

I keep getting "ECONNREFUSED 127.0.0.1:3306" as if the" socketPath" setting wasn't taken into account. Not sure why the propertie name changes to socket instead of socketPath in the hook code.
 
@adamquaile have you confirmed this workflow? 

My database.json looks as follows:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "database": "${process.env.SQL_DATABASE || 'xxx'}",
        "username": "${process.env.SQL_USER || 'xxx'}",
        "password": "${process.env.SQL_PASSWORD || 'XXX'}",
        "ssl": false,
        "socketPath": "'/cloudsql/INSTANCE_NAME'"
      },
      "options": {
        "pool":{
            "min": 0,
            "max": 10,
            "idleTimeoutMillis": 30000,
            "createTimeoutMillis": 30000,
            "acquireTimeoutMillis": 30000
        }
      }
    }
  }
}
```

**Comment by jopmiddelkamp** [comment]
I just tried to use the socketPath to connect Strapi to a MySQL database on Google Cloud Platform but I cannot get it to work... Am I doing something wrong here? Does anyone else get it to work? @pelayomendez or @adamquaile?

Package.json: dependencies (partial):
```
    ...
    "knex": "latest",
    "lodash": "^4.17.5",
    "mysql": "^2.17.1",
    "sqlite3": "^4.1.0",
    "strapi": "3.0.0-beta.15",
    "strapi-admin": "3.0.0-beta.15",
    "strapi-hook-bookshelf": "3.0.0-beta.15",
    "strapi-hook-knex": "3.0.0-beta.15",
    ....
```

database.json (staging)

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.MYSQL_HOST || '127.0.0.1'}",
        "port": "${process.env.MYSQL_PORT || '3306'}",
        "database": "${process.env.MYSQL_NAME}",
        "username": "${process.env.MYSQL_USERNAME}",
        "password": "${process.env.MYSQL_PASSWORD}",
        "socketPath": "/cloudsql/${process.env.INSTANCE_CONNECTION_NAME}"
      },
      "options": {
      }
    }
  }
}
```

app.staging.yaml
```
runtime: nodejs10
service: strapi

env_variables:
  NODE_ENV: staging
  MYSQL_USER: <hidden>
  MYSQL_PASSWORD: <hidden>
  MYSQL_DATABASE: strapi
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: <hidden>:europe-west1:mysql"
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: "<hidden>:europe-west1:mysql"
```

Deployment command

`gcloud app deploy app.staging.yaml --project <hidden> --quiet`

Then the deployment is successful but when I load the page I get a 500 server error.

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds. 

The App Enigine log

> "GET / HTTP/1.1" 500
>   { Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'undefined'@'cloudsqlproxy~\<hidden-IP\> (using password: YES)
>       at Handshake.Sequence._packetToError (/srv/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>       at Handshake.ErrorPacket (/srv/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
>       at Protocol._parsePacket (/srv/node_modules/mysql/lib/protocol/Protocol.js:291:23)
>       at Parser._parsePacket (/srv/node_modules/mysql/lib/protocol/Parser.js:433:10)
>       at Parser.write (/srv/node_modules/mysql/lib/protocol/Parser.js:43:10)
>       at Protocol.write (/srv/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>       at Socket.<anonymous> (/srv/node_modules/mysql/lib/Connection.js:91:28)
>       at Socket.<anonymous> (/srv/node_modules/mysql/lib/Connection.js:525:10)
>       at Socket.emit (events.js:198:13)
>       at addChunk (_stream_readable.js:288:12)
>       at readableAddChunk (_stream_readable.js:269:11)
>       at Socket.Readable.push (_stream_readable.js:224:10)
>       at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
>       --------------------
>       at Protocol._enqueue (/srv/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>       at Protocol.handshake (/srv/node_modules/mysql/lib/protocol/Protocol.js:51:23)
>       at Connection.connect (/srv/node_modules/mysql/lib/Connection.js:119:18)
>       at Bluebird (/srv/node_modules/knex/lib/dialects/mysql/index.js:68:18)
>       at Promise._execute (/srv/node_modules/bluebird/js/release/debuggability.js:313:9)
>       at Promise._resolveFromExecutor (/srv/node_modules/bluebird/js/release/promise.js:488:18)
>       at new Promise (/srv/node_modules/bluebird/js/release/promise.js:79:10)
>       at Client_MySQL.acquireRawConnection (/srv/node_modules/knex/lib/dialects/mysql/index.js:63:12)
>       at create (/srv/node_modules/knex/lib/client.js:258:21)
>       at utils_1.tryPromise (/srv/node_modules/tarn/lib/Pool.js:389:34)
>       at Object.tryPromise (/srv/node_modules/tarn/lib/utils.js:53:24)
>       at Promise (/srv/node_modules/tarn/lib/Pool.js:389:17)
>       at new Promise (<anonymous>)
>       at callbackOrPromise (/srv/node_modules/tarn/lib/Pool.js:380:12)
>       at Pool._create (/srv/node_modules/tarn/lib/Pool.js:290:9)
>       at Pool._doCreate (/srv/node_modules/tarn/lib/Pool.js:260:36)
>       at Pool._tryAcquireOrCreate (/srv/node_modules/tarn/lib/Pool.js:211:18)
>       at Pool.acquire (/srv/node_modules/tarn/lib/Pool.js:117:14)
>       at Bluebird.try (/srv/node_modules/knex/lib/client.js:312:43)
>       at tryCatcher (/srv/node_modules/bluebird/js/release/util.js:16:23)
>       at Function.Promise.attempt.Promise.try (/srv/node_modules/bluebird/js/release/method.js:39:29)
>       at Client_MySQL.acquireConnection (/srv/node_modules/knex/lib/client.js:312:26)
>     code: 'ER_ACCESS_DENIED_ERROR',
>     errno: 1045,
>     sqlMessage:
>      'Access denied for user \'undefined\'@\'cloudsqlproxy~\<hidden-IP\>\' (using password: YES)',
>     sqlState: '28000',
>     fatal: true }

**Comment by dasw3** [comment]
> Helllo.
> 
> I have been trying to use this feature to connect an Strapi app installed in Google Cloud App Engine to Cloud SQL. Connection to the database in this scenario should be perfomed over unix socket.
> 
> I keep getting "ECONNREFUSED 127.0.0.1:3306" as if the" socketPath" setting wasn't taken into account. Not sure why the property name changes to socket instead of socketPath in the hook code.
> 
> @adamquaile have you confirmed this workflow?
> 
> My database.json looks as follows:
> 
> ```
> {
>   "defaultConnection": "default",
>   "connections": {
>     "default": {
>       "connector": "strapi-hook-bookshelf",
>       "settings": {
>         "client": "mysql",
>         "database": "${process.env.SQL_DATABASE || 'xxx'}",
>         "username": "${process.env.SQL_USER || 'xxx'}",
>         "password": "${process.env.SQL_PASSWORD || 'XXX'}",
>         "socketPath": "/cloudsql/${process.env.INSTANCE_CONNECTION_NAME}"
>       },
>       "options": {
>         "pool":{
>             "min": 0,
>             "max": 10,
>             "idleTimeoutMillis": 30000,
>             "createTimeoutMillis": 30000,
>             "acquireTimeoutMillis": 30000
>         }
>       }
>     }
>   }
> }
> ```
> 
> Connecting to a postgres Cloud SQL database works. So I'm using this as a workaround for the deploy:
> 
> ```
> 
> {
>   "defaultConnection": "default",
>   "connections": {
>     "default": {
>       "connector": "strapi-hook-bookshelf",
>       "settings": {
>         "client": "postgres",
>         "host": "/cloudsql/${process.env.INSTANCE_CONNECTION_NAME}",
>         "database": "${process.env.SQL_DATABASE || 'xxx'}",
>         "username": "${process.env.SQL_USER || 'xxx'}",
>         "password": "${process.env.SQL_PASSWORD || 'XXX'}",
>       },
>       "options": {
>         "pool":{
>             "min": 0,
>             "max": 10,
>             "idleTimeoutMillis": 30000,
>             "createTimeoutMillis": 30000,
>             "acquireTimeoutMillis": 30000
>         }
>       }
>     }
>   }
> }
> ```

Recently had the same issue (local macOS deploying to GCP app engine) and above solution fixed the issue. socketPath approach works well with MySQL but for PostgresSQL, you need to use host with the same value of socketPath as shown in the solution above! Thank you!

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
What is the problem to parse hostname and check whether it is `localhost` and to connect as native mysql utilities do ?
[Official MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/connecting.html) states:
> - The default host name is localhost. On Unix, this has a special meaning, as described later.
> .....
> If the host is not specified or is localhost, a connection to the local host occurs:
> - On Unix, MySQL programs treat the host name localhost specially, in a way that is likely different from what you expect compared to other network-based programs: the client connects using a Unix socket file.
