### ISSUE TITLE
UI Freezing and High CPU Usage when Updating or Adding User Data

### ISSUE THREAD

**Issue by tirth-s-simformsolutions** [strapi/strapi#17156]
@derrickmehaffy @Marc-Roig 

**Describe the Bug**
I am encountering an issue where the Strapi UI freezes and the CPU usage of Google Chrome reaches 100% when I try to update or add new user data. This issue significantly impacts our workflow, and I would appreciate an update or assistance in resolving it.

**Steps to Reproduce**
1. Go to the "user" content type.
2. Click on the "add user" or "update user" option.
3. Fill in the fields with the required information.
4. Observe that the UI hangs.

**Expected Behavior**
The UI should function smoothly without freezing or causing excessive CPU usage.

**Additional Context**
Please find the system information and steps to reproduce the issue below:

Required System Information:

- npm: '9.5.1'
- node: '18.16.0'
- Strapi version: 4.8.2
- Database: local Postgres
- Operating system: Ubuntu 22.04
- Project Language: Typescript

Steps to Reproduce the Behavior:

1. Go to the "user" content type.
2. Click on the "add user" or "update user" option.
3. Fill in the fields.
4. The UI hangs.

If any additional context, error messages, code snippets, or screenshots are relevant to this issue, please provide them.

Thank you for your attention to this matter, and I look forward to your response.

User Schema for Context
https://gist.github.com/tirth-s-simformsolutions/78e071bde9beec3dbe2a67efd7c83507

**Comment by nitinmadelyn** [comment]
@tirth-s-simformsolutions this is probably be fixed once this #17140 got merged. Seems like a problem related to `useRBAC` hook. I've also faced similar issue while navigating to `Settings > Users > Edit User` in Admin.

**Comment by tirth-s-simformsolutions** [comment]
The issue got resolved after I upgraded to ^4.11.1. I appreciate your support.
