### ISSUE TITLE
Unique type Date are not validated

### ISSUE THREAD

**Issue by findorf** [strapi/strapi#1715]
**Informations**
- **Node.js version**:10.8.0
- **npm version**:6.3.0
- **Strapi version**:3.0.0-alpha.13.0.1
- **Database**:Mongodb 4.0.1
- **Operating system**:Windows 10 Enterprise N

**What is the current behavior?**
I have set a field type to Date and set both required and unique to true.
Still, I can create non unique field values.

**Steps to reproduce the problem**
This is my Day.settings.json:
```
{
  "connection": "default",
  "collectionName": "day",
  "info": {
    "name": "day",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "Date": {
      "type": "date",
      "required": true,
      "unique": true
    },
    "person": {
      "collection": "person",
      "via": "day",
      "dominant": true
    },
    "Disabled": {
      "type": "boolean"
    }
  }
}
```
This is what I post:
```
fetch("http://localhost:1337/day/", {
        method: "POST", 
        headers: {
            "Content-Type": "application/json; charset=utf-8",
        },
        body: JSON.stringify({"Date": "2018-08-11T00:00:00.000Z"}),
    })
```

**What is the expected behavior?**
If I do the same with data type decimal, I get a validation error.

**Suggested solutions**
Add validation to date types.

**Comment by derrickmehaffy** [comment]
@findorf currently there is no validation layer on anything at the moment, its a WIP feature (using unique on any field type with mysql I know it doesn't properly set the keys) I imagine mongo also doesn't have any validations.

**Comment by findorf** [comment]
ok, thats why the validation of decimal works and date dont.
Thanks.
