### ISSUE TITLE
Error Field Date in entry

### ISSUE THREAD

**Issue by Ironsites** [strapi/strapi#17151]
### Required System information
- Node.js version:18.14.9
- NPM version:9.6.0
- Strapi version:4.11.3
- Database: mysql
- Operating system: window 10
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Error when entering or replacing the date of a field with an empty value, it shows an error in the console and also does not replace it in the database

### Steps to reproduce the behavior

1. Create Single or Collection Type
2. Add Field Date  and save
3. Create new Entry
4. Select Datatime in Field and save entry
5. Edit entry 
6. Remove datetime view error in console 
7. Save with empty datetime field 
8. Refresh f5, datetime is not empty

### Expected behavior
fix the bug

### Screenshots
Before clear date
![image](https://github.com/strapi/strapi/assets/90522949/514a6530-e513-4662-8004-a012ee3466ce)
After Clear date
![image](https://github.com/strapi/strapi/assets/90522949/339c2cc3-6d1e-4c38-9fcf-83c3aa47aa51)
After refresh page
![image](https://github.com/strapi/strapi/assets/90522949/9972092c-dd69-4c9e-b7c4-79e8ae3ade34)

**Comment by joshuaellis** [comment]
resolved by #17599
