### ISSUE TITLE
Cannot re-order items in list by drag & drop

### ISSUE THREAD

**Issue by ArnoSoontjens** [strapi/strapi#17157]
### Required System information
- Node.js version: v14.21.3
- NPM version: 9.5.0
- Strapi version: v4.9.2
- Database: Postgres
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I cannot reorder items in a list by dragging and dropping. 
We have a collection type 'Page'. In there, there is an instance of Page, which has a dynamic zone with two components. The second component has a list of components. That list component also contains a list of list items (also components). When re-ordering the last list by drag & drop, the app shows an error and we cannot reorder.

### Steps to reproduce the behavior
Recreate this structure, add items to the list and try to drag & drop

### Expected behavior

Items should reorder.

### Screenshots

![image](https://github.com/strapi/strapi/assets/4067834/2ca3a1d2-32ec-450f-9bbc-104b673a88ac)
![image](https://github.com/strapi/strapi/assets/4067834/9406125c-c857-4194-8290-796914ca3459)
![image](https://github.com/strapi/strapi/assets/4067834/cf2564c2-f7fc-41e2-ac82-892f9638cc79)

**Comment by joshuaellis** [comment]
I think this is fixed in a later version of Strapi, have you tried upgrading your app?
