### ISSUE TITLE
Wrong meta.pagination on GraphQL queries with filters

### ISSUE THREAD

**Issue by soamati** [strapi/strapi#17161]
### Required System information

- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: 4.11.3
- Database: postgres
- Operating system: Arch Linux
- Is your project Javascript or Typescript: Typescript
### Describe the bug
"pagination" meta field ignores filters in GraphQL queries, and returns the total of entities in the database.
Works fine on REST API requests.
### Steps to reproduce the behavior
1. Make a graphql query with filters by any field and ask for `meta.pagination`
2. Do the same query in REST api
3. See `meta` field in response
### Expected behavior
`meta.pagination` fields should take into account the filters in the request
#### GrapQL query (incorrect meta.pagination):
***total should be 6 and pageCount 1***
![image](https://github.com/strapi/strapi/assets/31834620/f4f5ecd1-338e-4eb4-8f1f-200194672ec8)
#### REST API with the same filters (correct meta.pagination):
![image](https://github.com/strapi/strapi/assets/31834620/a77803de-14f1-4329-a29c-c053102633dc)

**Comment by derrickmehaffy** [comment]
should be fixed in https://github.com/strapi/strapi/pull/17143 which will be released on Wednesday

**Comment by nagman** [comment]
I can confirm it is not fixed with `4.11.4`.
`total` still returns the total number of items regardless of the `pageSize` or `limit`.

This #17143 hasn't solved it.
