### ISSUE TITLE
Broken link in 'Configuring Users & Permissions plugin settings' docs page

### ISSUE THREAD

**Issue by Dorin-David** [strapi/strapi#17163]
### Describe the bug

On the [Configuring Users & Permissions plugin settings](https://docs.strapi.io/user-docs/settings/configuring-users-permissions-plugin-settings) page, the link to [Setting up the provider](https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#setting-up-the-provider-examples) is broken:

### Steps to reproduce the behavior

1. Go to ['Configuring Users & Permissions plugin settings'](https://docs.strapi.io/user-docs/settings/configuring-users-permissions-plugin-settings)
2. Scroll down to ['Configuring providers'](https://docs.strapi.io/user-docs/settings/configuring-users-permissions-plugin-settings#configuring-providers)
3. Click on [Setting up the provider](https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#setting-up-the-provider-examples) (4th in the bullet list)
4. Will be directed to the 404 page

### Expected behavior

Correctly see the docs for 'Setting up the provider'

**Comment by Boegie19** [comment]
Seems to me like this is a docs thing so this should be moved to strapi/documentation repo

**Comment by Boegie19** [comment]
@derrickmehaffy mind transferring this one to the docs repo?

**Comment by derrickmehaffy** [comment]
Yeah sure, let me pull the tags off
