### ISSUE TITLE
ssoLockedRoles can't be empty

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#17172]
### Required System information

- Node.js version: 18.9.1
- NPM version: 8.19.1
- Strapi version: 4.11.3
- Database: postgres
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug
ssoLockedRoles must be a `array` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

### Steps to reproduce the behavior

1. Go to SSO in settings full everying in and keep ssoLockedRoles empty

### Expected behavior

For it to allow it

**Comment by derrickmehaffy** [comment]
Confirmed with boegie on discord
