### ISSUE TITLE
Upload file deletes before lifecycle hook is run

### ISSUE THREAD

**Issue by aturkewi** [strapi/strapi#17170]
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.9.0
- Database: PostgreSQL 15
- Operating system: MacOS 13.4.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am attempting to use lifecycle methods on `plugin::upload.file` to prevent users from deleting any file that has been uploaded. I can get Strapi to raise an error in `beforeDelete` which prevents the row being removed from the DB table, but the file is deleted from local storage before this lifecycle hook is called thus leaving broken image links. 

### Steps to reproduce the behavior

Add the lifecycle hook to `src/index.ts`

```ts
// src/index.ts

export default {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register(/*{ strapi }*/) {},
  // TODO: Disable all mutations via Shadow Crud.
  // This could possibly be done at the API Token level as well.

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap({ strapi }) {
    // docs on adding lifecycle hooks here for any model
    // https://docs.strapi.io/dev-docs/backend-customization/models#lifecycle-hooks
    strapi.db.lifecycles.subscribe({
      models: ['plugin::upload.file'],
      beforeDelete(event) {
        throw new Error('Deletion is not allowed');
      },
    });
  },
};
```

Run the app with `yarn strapi develop --watch-admin`
Navigate to the Media Library and upload a file. 
Navigate to the media library index. 
Delete the file by checking it off on the left hand side, you to delete at the top of the index and confirming in the modal.
The server raises an error. 
Reload the media library index. The image row is still there, but the file itself has been deleted

### Expected behavior

After the server raises an error and I reload the page, I would expect that nothing would have been deleted and that the file itself would be preserved in local storage

### Code snippets

See above in steps to reproduce

### Additional context

I am looking for any way to be able to safegaurd our system from allowing users to delete files that are in use. [Open forum topic](https://forum.strapi.io/t/how-can-i-prevent-deletion-of-media-files-if-they-are-in-use/29771/3). Any suggestions here would be helpful.

**Comment by Boegie19** [comment]
@aturkewi This is the expected behavior lifecycles are bellow the query engine aka it works on the db layer only. you would have to add a middleware to the route to get the behavior you want

**Comment by aturkewi** [comment]
@Boegie19 I realized I never got back to you on this. Thank you so much for the suggestion to use middleware, that was super helpful!
