### ISSUE TITLE
The settings menu displays items that the user does not have permission to

### ISSUE THREAD

**Issue by holyvikt** [strapi/strapi#17179]
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.11.3
- Database: SQLite
- Operating system: Windows 11
- Is your project Javascript or Typescript: JS

### Describe the bug

The settings menu shows the items that the user do not have permissions to. If such an item is selected, the user is redirected to the dashboard.

### Steps to reproduce the behavior

1. Log in as a user with limited permissions (e.g. editor)
2. Go to settings
3. You will see items that the Editor does not have rights to by default (API Token, Media Library, Transfer tokens, Roles, Users,...)
4. Click on one of these options and you will be redirected to the dashboard

### Expected behavior

The user should not be able to see items to which they do not have permissions, as in previous versions of Strapi.

**Comment by noobCode-69** [comment]
I want to know on what basis you guyz are doing the redirect. 
After debugging I have found this.
```js
            {section.links.map((link) => {
              return (
                <SubNavLink
                  as={NavLink}
                  withBullet={link.hasNotification}
                  to={link.to}
                  onClick={() => handleClickOnLink(link.to)}
                  key={link.id}
                >
                  {formatMessage(link.intlLabel)}
                </SubNavLink>
              );
            })}

 ```
Here each link has a property call isDisplayed , which I think should be the key to determine which link to show.

```js


```

**Comment by noobCode-69** [comment]
But when I do so the opposite happens. All those links which are not supposed to be there appears and those which are supposed to be there disappears. Strange!!

**Comment by noobCode-69** [comment]
I think i know the problem , will make a PR tonight , please review

**Comment by noobCode-69** [comment]
Here is the problem
```js
const { global: globalLinks, admin: adminLinks } = useEnterprise(
    LINKS_CE,
    async () => (await import('../../../../ee/admin/hooks/useSettingsMenu/constants')).LINKS_EE,
    {
      combine(ceLinks, eeLinks) {

        function addPermissions(link) {
          if (!link.id) {
            throw new Error('The settings menu item must have an id attribute.');
          }

          return {
            ...link,
            permissions: permissions.settings?.[link.id]?.main,
          };
        }

        return {
          admin: [...eeLinks.admin, ...ceLinks.admin].map(addPermissions),
          global: [...ceLinks.global, ...eeLinks.global].map(addPermissions),
        };
      },
      defaultValue: {
        admin: [],
        global: [],
      },
    }
  );

```
In the above the addPermissions will never be called since the combine callback will never be called if it's not Enterprise , therefore for globalLinks and adminLinks proper permission will not be added and hence **isDisplayed** will for those links will be true as if permission is an empty arrary or undefined the **hasPermission** function will return true.

**Comment by noobCode-69** [comment]
Please ignore the first commit
