### ISSUE TITLE
Incorrect data displayed in the dynamic zone and component relation fields of a collection when switching locales

### ISSUE THREAD

**Issue by tinam02** [strapi/strapi#17197]
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.19.3
- Strapi version: v4.7.0
- Database: MYSQL prod, sqlite3 dev
- Operating system: macOS
- Is your project Javascript or Typescript: TS

### Describe the bug

Incorrect data is displayed in the components inside the dynamic zone of a collection when some of those components have a relation field to another collection.
An error message is shown when switching from one locale to another if said locales contain a component with a relation to a different collection

### Steps to reproduce the behavior

1. Create two collection types with dynamic zones (Page and Common). Localization is on for everything;
2. Create a few simple components with text, enumeration etc. fields;
3. Put the simple components in the dynamic zones of both Page and Common collection;
4. Create a component with a relation to Common. Put this component in the dynamic zone of the Page collection;
5. Create an entry in Common containing one component from the dynamic zone. Create a localization for it;
6. Create an entry in Page. Insert components from the dynamic zone, and insert the component that has a relation to Common. Do this in two different locales.
7. Switch from one locale to another and see that incorrect data is displayed (e.g. components from English are showing in German, and the components with a relation now have two relations)
8. Refresh to see the correct data
9. Switch back to the first locale, and see the "Whoops, something went wrong" error

### Expected behavior

See the correct data and relations when switching locales in the Page collection

### Video

https://github.com/strapi/strapi/assets/73225709/e1c2208e-688e-48f5-b509-4efbedf566db

**Comment by joshuaellis** [comment]
I think we fixed this in a more recent version of strapi – are you able to upgrade and see if the issue persists? If it does, we can reopen the issue :)
