### ISSUE TITLE
Video meta data doesn't include the duration and the thumbnails of the videos

### ISSUE THREAD

**Issue by Abdulrahman-AL-Sabagh** [strapi/strapi#17193]
## Bug report
Video meta data doesn't include the duration and the thumbnails of the videos
### Required System information

- Node.js version: 18.15.0
- NPM version:  9.7.2
- Strapi version: 4.10.7
- Database: postgres
- Operating system: windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The duration and the thumbnail of the videos are not provided in the response of the /upload api or any api that retrieves some file related data

### Steps to reproduce the behavior

1. go to postman or any rest client you want
2. hit the upload api or any api that returns some file related data
3. check the response and specifically the meta data of the file
4. the duration of the videos and the thumbnails are not included
### Expected behavior

The duration and the thumbnails should  be included in the meta data, because the user can see both of these in the media library. 
Is there a way to get these 2 attributes, without adding 2 extra attributes to the schemas

### Screenshots

![image](https://github.com/strapi/strapi/assets/78429703/093e6c91-842d-4102-bc7a-d6ef8cf7993d)
![image](https://github.com/strapi/strapi/assets/78429703/d0d94140-f2b0-456a-804f-06d71e41306b)

### Code snippets

N/A

### Additional context

N/A

**Comment by Abdulrahman-AL-Sabagh** [comment]
I hope you are happy with the template now

**Comment by noobCode-69** [comment]
Yeah this makes sense now!

**Comment by Abdulrahman-AL-Sabagh** [comment]
any related updates to this issue?
