### ISSUE TITLE
Fuzzy search plugin error on versions 4.11.3 and 4.11.4

### ISSUE THREAD

**Issue by WebShapedBiz** [strapi/strapi#17208]
## Bug report
After upgrading my app from Strapi v4.11.2 to Strapi v4.11.3 and then 4.11.4, the `Strapi-plugin-fuzzy-search` is producing this error:
`Error: Could not load js config file /home/xxxx/Dev/yyyy/strapi/node_modules/strapi-plugin-fuzzy-search/strapi-server.js: Cannot find module '@strapi/utils/lib/errors'` on `npm run develop`. `npm run build` doesn't produce any errors.

After removing Strapi-plugin-fuzzy-search, my app works again. I'm guessing Strapi's patch release has changed something under-the-hood again...

### Required System information
- Node.js version: 16.13.1
- NPM version: 8.19.2
- Strapi version: 4.11.4
- Database: SQLite
- Operating system: Ubuntu 20.04.4
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior
1. Install new Strapi app using Strapi CLI
2. Install Strapi-plugin-fuzzy-search
3. Run `npm run build`
4. Run `npm run develop` and see the error.

**Comment by joshuaellis** [comment]
We don't maintain this plugin unfortunately & from your error message it looks like they were importing from a subpath which is typically a bad idea. I would open the issue on their repo :)

**Comment by WebShapedBiz** [comment]
Thank you @joshuaellis for your reply. I've already opened an issue on their repo, but I've been maintaining this app from Strapi 4.2.0 onwards and never had any problems before the 4.11.3 patch release that broke that plugin, just like one of your previous patch releases broke the SSO plugin if I'm not mistaken. Shouldn't patch releases suppose to fix bugs and not change things under the hood that could cause things to break? I'm always freaked out when I need to update my app.

**Comment by joshuaellis** [comment]
>  Thank you @joshuaellis for your reply. I've already opened an issue on their repo, but I've been maintaining this app from Strapi 4.2.0 onwards and never had any problems before the 4.11.3 patch release that broke that plugin, just like one of your previous patch releases broke the SSO plugin if I'm not mistaken. Shouldn't patch releases suppose to fix bugs and not change things under the hood that could cause things to break? I'm always freaked out when I need to update my app.

I understand that :) in this case though, the developer should not have imported from `@strapi/utils/lib/error` because _typically_ you don't import from subpaths you should always import from the root e.g. `import { module } from '@strapi/utils'`, we don't have to preserve the file structure of our libraries, we simply preserve the exports (or public facing API if you will) – I would assume this has not broken and had the developer correctly written their plugin then I would imagine you would not be in this issue.

> broke the SSO plugin

Do you have a link to this breakage for me? I'm not familiar.

**Comment by WebShapedBiz** [comment]
Couldn't find the issue, I think it was the passwordless plugin, not sure, but this guy is giving a far better description of what I'm trying to say:
https://github.com/strapi/strapi/issues/16873#issuecomment-1570494015

**Comment by joshuaellis** [comment]
Don't worry I know what you're saying, and we're trying to improve the release cycle – I really agree that right now it's not working.

**Comment by WebShapedBiz** [comment]
Thank you @joshuaellis for your time and effort.
