### ISSUE TITLE
Not able to create API token with Token type as "custom" selected.

### ISSUE THREAD

**Issue by de-shine** [strapi/strapi#17212]
- Node.js version: **v16.18.0**
- NPM version: 9.6.7
- Strapi version: 4.11.4
- Database: Postgres
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug

On clicking of save button while creating API token from settings, getting below issue.

### Steps to reproduce the behavior

1. Go to 'settings'
2. Click on 'API Tokens' under global settings
3. Provide the token name and Select Token type as "custom".
4. Click on Save we get an error on the browser as "Warning: An error occurred"

**Console Error:**
_error: insert into "strapi_api_tokens" ("access_key", "created_at", "description", "expires_at", "lifespan", "name", "type", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" - new row for relation "strapi_api_tokens" violates check constraint "strapi_api_tokens_type_check"
error: insert into "strapi_api_tokens" ("access_key", "created_at", "description", "expires_at", "lifespan", "name", "type", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" - new row for relation "strapi_api_tokens" violates check constraint "strapi_api_tokens_type_check"

### Expected behavior

It should allow us to create the API token with **Token type** as "_custom_" without any error.

**Comment by derrickmehaffy** [comment]
tested on v4.11.5 and could not reproduce: 

![image](https://github.com/strapi/strapi/assets/8593673/61ab11c1-6596-4862-bab2-9ca3a2ed42fa)
