### ISSUE TITLE
Date field changes value when out of focus

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#17210]
### Required System information

- Node.js version: 18
- NPM version: 9
- Strapi version: 4.11.4
- Database: mysql8
- Operating system:
- Is your project Javascript or Typescript: typescript

### Describe the bug

Date field changes value when out of focus.

### Expected behavior

Value does not change when out of focus.

### Screenshots

https://github.com/strapi/strapi/assets/26789317/5a50d970-0b33-4fc7-9611-1fae69a476b2

### Additional context

Created in Datetime field

**Comment by noobCode-69** [comment]
The issue is related to timezone .
Date is formatted here using time method
```js
const formattedDate = date ? date.toISOString() : null;
```
Now if you are in different time zone let's say GMT+0530 (IST) .It converts the date to UTC, which is why you see the time being reduced by 5 hours and 30 minutes (IST to UTC conversion).

**Comment by rktyt** [comment]
My environment is GMT+0900 (JST).
Come to think of it, the date shown was also wrong.

It was originally registered as 03/01/2023 00:00 JST before the upgrade.
But it shows 02/28/2023 00:00.
The collection listing screen shows "Wednesday, March 1, 2023 at 12:00 AM" which is correct.

**Comment by yootravel** [comment]
Same here, i'm using GMT+2 (language fr-CH) the dates format are wrong and change on leaving the field

**Comment by derrickmehaffy** [comment]
Confirmed but difficult to reproduce as you need to create the entry basically right around when the date would change given your offset from GMT. This is a regression from many moons ago where we had issues using Node's built in `new Date()`. When it came to dealing with dates and times we basically have to treat them as strings and not force them through the node date function.

**Comment by gu-stav** [comment]
Probably related https://github.com/strapi/strapi/issues/17432

**Comment by joshuaellis** [comment]
Closing this in favour of #17348
