### ISSUE TITLE
Build errors for Strapi project from version 4.11.3 onwards when upgrading

### ISSUE THREAD

**Issue by gabba196** [strapi/strapi#17225]
- Node.js version: 16.13.1
- NPM version: 8.1.2
- Strapi version: 4.11.4
- Database: MySQL
- Operating system: macOs Ventura 13.4.1
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Have followed the official Strapi upgrade instructions and am able to install the required packages but when I go to build the project in development mode I get an error, provided below.

### Steps to reproduce the behavior

1. Bump Strapi version to latest 4.11.4 in package.json
2. Delete the .cache directory, node_modules and package-lock.json
3. run `npm install `followed by `npm run build`
4. See error below in logs

### Expected behavior

Strapi builds the project as normal.

### Code snippets

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'ee_else_ce/pages/AuthPage/utils/forms' in '/Users/marcopolo/Documents/marcopolo-cms/.cache/admin/src/pages/AuthPage'
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/marcopolo/Documents/marcopolo-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/marcopolo/Documents/marcopolo-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/marcopolo/Documents/marcopolo-cms/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'ee_else_ce/pages/AuthPage/utils/forms' in '/Users/marcopolo/Documents/marcopolo-cms/.cache/admin/src/pages/AuthPage'
  Parsed request is a module
  using description file: /Users/marcopolo/Documents/marcopolo-cms/.cache/package.json (relative path: ./admin/src/pages/AuthPage)
    aliased with mapping 'ee_else_ce': '/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin' to '/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms'
      using description file: /Users/marcopolo/Documents/marcopolo-cms/.cache/package.json (relative path: ./admin/src/pages/AuthPage)
        Field 'browser' doesn't contain a valid alias configuration
        root path /Users/marcopolo/Documents/marcopolo-cms
          using description file: /Users/marcopolo/Documents/marcopolo-cms/package.json (relative path: ./Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.tsx doesn't exist
            as directory
              /Users/marcopolo/Documents/marcopolo-cms/Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms doesn't exist
        using description file: /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/package.json (relative path: ./pages/AuthPage/utils/forms)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.js doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.jsx doesn't exist
          .react.js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.react.js doesn't exist
          .ts
            Field 'browser' doesn't contain a valid alias configuration
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.ts doesn't exist
          .tsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms.tsx doesn't exist
          as directory
            /Users/marcopolo/Documents/marcopolo-cms/node_modules/@strapi/admin/pages/AuthPage/utils/forms doesn't exist
```

### Additional context

Our project was using v4.7.1 and we were waiting for a GraphQL pagination bug fix before upgrading, as our project depends on this feature, so we tried to upgrade directly to v4.11.4 and we got the above error in the log. We then tried with v4.11.3 and got the same. However, from v4.11.2 and below we are able to build the project as normal.

**Comment by joshuaellis** [comment]
I would try clearing that `.cache` folder 👍🏼

**Comment by gabba196** [comment]
> I would try clearing that `.cache` folder 👍🏼

We have been doing that every time to no success :(

**Comment by joshuaellis** [comment]
> > I would try clearing that `.cache` folder 👍🏼
> 
> We have been doing that every time to no success :(

I would also try clearing your node modules – if that doesn't help remove your package.json, in short this file – `/Users/marcopolo/Documents/marcopolo-cms/.cache/admin/src/pages/AuthPage` is not the actual 4.11.4 release version where we don't even use that import anymore 🤔

**Comment by gabba196** [comment]
> > > I would try clearing that `.cache` folder 👍🏼
> > 
> > 
> > We have been doing that every time to no success :(
> 
> I would also try clearing your node modules – if that doesn't help remove your lock file, in short this file – `/Users/marcopolo/Documents/marcopolo-cms/.cache/admin/src/pages/AuthPage` is not the actual 4.11.4 release version where we don't even use that import anymore 🤔

As also outlined in the steps to reproduce section, we are currently removing the lock file, node modules and .cache folder before installing and building - however still getting the same error when trying to build. I have just tried it again. Any ideas what could be the issue? For example, when I do the same in 4.11.2 it is able to build but from 4.11.3 I get the same error as above.

**Comment by Boegie19** [comment]
Just to confirm do you guys use comunity or Enterpise edition?

**Comment by gabba196** [comment]
> 

Community

**Comment by Boegie19** [comment]
@gabba196 Any plugins or extentions you use/made?

**Comment by gabba196** [comment]
@Boegie19  Yes -  3 custom plugins and some modification to the default Strapi users-permissions but these have worked for us since v4 and up to v4.11.2. Beyond that we get the errors at build.

**Comment by Boegie19** [comment]
@Boegie19 can you make a temp/test version of your application with all plugins not maintained by strapi and all modifications removed and see if that fixes your issue?

**Comment by gabba196** [comment]
Update from our side: Seems we needed to manually add the useEnterprise() hooks for the AuthPages and replace the ee_else_ce and that did the trick. Was able to build successfully

**Comment by Boegie19** [comment]
@gabba196 Just to confirm one of your extentions/plugins used that so it is not a strapi issue?

**Comment by gabba196** [comment]
> @gabba196 Just to confirm one of your extentions/plugins used that so it is not a strapi issue?

Yes, I can confirm that now.

**Comment by aryalaashish121** [comment]
# This Dockerfile works for strapi with version 5.4
# Creating multi-stage build for production
FROM node:20.10.0-alpine as build
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev git > /dev/null 2>&1
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package*.json ./
RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install
ENV PATH=/opt/node_modules/.bin:$PATH
WORKDIR /opt/app
COPY . .
RUN npm run build


FROM node:20.10.0-alpine
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY --from=build /opt/node_modules ./node_modules
WORKDIR /opt/app
COPY --from=build /opt/app ./
ENV PATH=/opt/node_modules/.bin:$PATH

RUN chown -R node:node /opt/app
USER node
EXPOSE 1337
CMD ["npm", "run", "start"]
