### ISSUE TITLE
Clone entity relations cannot work within components.

### ISSUE THREAD

**Issue by ok1054689** [strapi/strapi#17220]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version:4.11.4
- Database:mysql
- Operating system: windows
- Is your project Javascript or Typescript:Javascript 

### Describe the bug

#16192  Merged , Clone entity relations cannot work within components. I have defined a one-to-one relationship field named 'type' within the component.

"type": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::alie.a-type"
    }

### Steps to reproduce the behavior

1. Go to Content Manager
2. Click on Duplicate item Button
3. The 'type' oneToOne relationship field has not been populated.

### Expected behavior

Populating relationship fields within a component.

### Screenshots

https://github.com/strapi/strapi/assets/31556660/51a48e98-495d-44aa-95f0-c555f3c24df8

**Comment by Pablo-Aldana** [comment]
I'm having similar issue here, but I do not even get the UI error. However on  the safari console  I can see the following error: 

Failed to load resource the server responded with a status of 400 "https://domain/content-manager/collection-types/api::place.place/auto-clone/3507?"

I'm in strapi 4.11.4

**Comment by ok1054689** [comment]
@Marc-Roig @joshuaellis #16192  I kindly request the submitter to provide assistance in resolving this matter. Thank you.

**Comment by vandres** [comment]
I see the same problem, when I localize an entry. All the text values get copied. But the relations get lost. Strapi 4.11.4


https://github.com/strapi/strapi/assets/1436383/6136507f-38ae-452e-b958-b6c93b7c9e58

**Comment by Marcosul** [comment]
I have the same problem. Duplicate Button dont work. lasted version
