### ISSUE TITLE
[v4] problem with admin url

### ISSUE THREAD

**Issue by vandres** [strapi/strapi#17234]
### Required System information

- Node.js version: v16.20.1
- NPM version: 8.19.4
- Strapi version: v4.11.4
- Database: SQLite
- Operating system: MacOS
- Is your project Javascript or Typescript: JS

### Describe the bug

I am not 100% sure if it is a bug or just hard to understand. I will try to explain with my local instance. But the real problem for us occured on the production system with Nginx rewrites.

```
// config/admin.js
module.exports = ({ env }) => ({
  url: env('ADMIN_URL'),
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
});

// .env
ADMIN_URL=/cms/admin
````

The system is supposed to run on "/cms/". So our api is supposed to be under "/cms/v4", the uploads unter "/cms/uploads" and the admin under "/cms/admin". As far as we can see, our Nginx configuration is working and redirecting all urls to Strapi. The problem we are seeing is within the admin.

Now I will explain with my local url. If we call `http://localhost:1337/cms/admin`, we see the admin and are able to login. Within the admin though, all requests are made to "http://localhost:1337/". E.g. "http://localhost:1337/admin/init", "http://localhost:1337/content-manager/init". I was expecting these calls be made to "http://localhost:1337/cms/admin/admin/init" and "http://localhost:1337/cms/admin/content-manager/init". The way it is now, our Nginx rules are not working.

We experimented a little with the `server.js` but with no positive result.

Can you help us with this issue?

**Comment by derrickmehaffy** [comment]
You need to rebuild the admin panel.

**Comment by vandres** [comment]
@derrickmehaffy Thanks for the reply. I did that multiple times, if you mean `yarn build`. The admin is working under that new url. But all (XHR) requests within the admin are still going to the root url.

**Comment by derrickmehaffy** [comment]
Then your ENV vars don't exist while building. Did you set the server URL (not just the admin URL)?

**Comment by vandres** [comment]
We tried now all combinations of admin.js:url and server.js:url. We made it hard coded, so ENV doesn't matter. In our Nginx log we can see, that "/cms/admin" is resolved correctly, but Strapi replies with a 404 JSON response.

**Comment by SheerGeyser** [comment]
strapi does not take into account the url for /admin during the build, as a result, in the folders with the build everywhere url=/admin
**i fixed it with sh script**

package.json
```"build": "strapi build && /bin/sh ./scripts/update_admin_url.sh",```

/scripts/update_admin_url.sh
```
#/bin/sh

SERVER_URL="$SERVER_URL"

if [ -n "$SERVER_URL" ]; then
  find ./dist/build -type f -name "*.js" -exec sed -i "s|/admin|/$SERVER_URL/admin|g" {} +
  sed -i "s|/admin|/$SERVER_URL/admin|g" ./dist/build/index.html
fi
```
/config/server.ts
```
url: env('SERVER_URL', ''),
```
