### ISSUE TITLE
Media Library folders not working

### ISSUE THREAD

**Issue by Xxsource98** [strapi/strapi#17255]
### Required System information

- Node.js version: 16.20.0
- NPM version: 8.19.4
- Strapi version: 4.11.4
- Database: MySQL
- Operating system: Ubuntu Server 20.04 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I can not select Media Image from 'Media Library' subfolder. 

When I Add New Asset in select image asset window in single type, it is uploading to folder and select uploaded image, but later I can not select and even get any image from subfolder.

The problem is only with Folder, when assets are in the "main" directory it displays all assets, and I am able to select any of them.

### Steps to reproduce the behavior

1. Go to your chosen Single Type Element
2. Select Image on Media Field
3. Select any folder from Media Library

### Screenshots

![image](https://github.com/strapi/strapi/assets/36642285/3dea2922-50a4-42b2-bb85-830eb332cb0c)
![image](https://github.com/strapi/strapi/assets/36642285/7fa371e7-9257-4822-83a6-2a915e97135d)

**Comment by joshuaellis** [comment]
Thanks for the report! we've fixed this with #17253 and it should be released in the next release.
