### ISSUE TITLE
Navigation between singles types results in "Information:  You are not allowed to see this document"

### ISSUE THREAD

**Issue by ststaynov** [strapi/strapi#17254]
### Required System information

- Node.js version: v16.13.0
- NPM version: 8.4.0
- Strapi version: 4.11.4
- Database: PostgreSQL
- Operating system: Mac OS Ventura 13.4.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Whenever I navigate throughout the single types in the "Content Editor" (using a superadmin account) I get thrown out to the "/admin/" page with the message: "Information: You are not allowed to see this document". No messages are showing in the console.

### Steps to reproduce the behavior

1. Go to 'Content Editor'
2. Click on 'any Single Type'
3. Navigate to 'any other Single Type'
4. Repeat 3. or go to 5.
5. Strapi navigates you to the "/admin" page with the information message.

### Expected behavior

User is navigated to the desired Singles Type.

### Additional

This bug is introduced after upgrading from Strapi v4.11.3 -> v4.11.4

Behaviour can be witnessed locally and live on a Heroku server

**Comment by kikky7** [comment]
Same bug... Fresh installation of Strapi with quickstart and with custom setup.

**Comment by tom-wenger** [comment]
Same issue here. I upgraded from 4.10.2 with a PosgresDB to 4.11.5 and now randomly get the "Information: You are not allowed to see this document" error when switching between single types. Sometimes i can see the page, sometimes not. 
Additionally to that the data of certain single types was deleted....
I also did set up a new project and got the error there too.

**Comment by Mjb141** [comment]
Same issue here. 4.11.1 -> 4.11.4 -> 4.11.5, Postgres database, randomly getting "You are not allowed to see this document" when switching between types, and it always kicks back to /admin when it happens. It doesn't happen every time.

Our environments on 4.11.1 are not affected.

**Comment by derrickmehaffy** [comment]
Related to internal TID 4374 for an EE customer. Raised Sev based on escalation process

**Comment by derrickmehaffy** [comment]
> We're still experiencing this as of 4.11.7 @joshuaellis 

Make sure you rebuild your admin panel.

**Comment by Mjb141** [comment]
> > We're still experiencing this as of 4.11.7 @joshuaellis
> 
> Make sure you rebuild your admin panel.

We have done so - the admin panel built fine:

```
#12 [ 7/11] RUN yarn build
#12 0.317 yarn run v1.22.19
#12 0.340 $ strapi build
#12 1.859 Starting the compilation for TypeScript files in /srv/app
#12 6.821 Building your admin UI with development configuration...
#12 7.481 ℹ Compiling Webpack
#12 22.62 ✔ Webpack: Compiled successfully in 15.14s
#12 24.48 Admin UI built successfully
#12 24.56 Done in 24.25s.
#12 DONE 24.7s
```

**Comment by derrickmehaffy** [comment]
Reopening as testing for part of an EE ticket where customer still is reporting the issue

**Comment by derrickmehaffy** [comment]
@joshuaellis I've passed you the reproduction from our customer in our internal Slack since I can't place it here.

**Comment by derrickmehaffy** [comment]
> Guys I'm sorry to bring this up again but I believe this issue should be higher priority. It breaks the core usage of the product and sometimes a certain singles type can not be accessed. Furthermore it is present for weeks now. Thank you for the effort and let me know if you need additional details to identify the issue. @derrickmehaffy @joshuaellis 

Currently our problem is accurately reproducing the issue so we can track down the source. As this isn't easy to reproduce at the moment. Raising the severity won't directly mean that we get a fix out faster or change sprint priorities (unless a sev is critical but that is reserved for much worse issues).

Any additional information such as how to consistently reproduce the issue from a fresh Strapi application would be the best way to assist us in finding a long term fix.

**Comment by ststaynov** [comment]
> Any additional information such as how to consistently reproduce the issue from a fresh Strapi application would be the best way to assist us in finding a long term fix.

I can't seem to reproduce this from a fresh installation with 2 single types. Perhaps this bug requires a more detailed schema. I could however provide a project containing this issue for debugging purposes? If that is an option please provide me a way to get in contact.

**Comment by derrickmehaffy** [comment]
> > Any additional information such as how to consistently reproduce the issue from a fresh Strapi application would be the best way to assist us in finding a long term fix.
> 
> I can't seem to reproduce this from a fresh installation with 2 single types. Perhaps this bug requires a more detailed schema. I could however provide a project containing this issue for debugging purposes? If that is an option please provide me a way to get in contact.

Absolutely that would be great, we have a couple of different options, if it's just a GitHub repo you can add me to it as a collaborator but if that's not possible please feel free to send it to my work email: derrick.mehaffy@strapi.io

Thanks :)

**Comment by ststaynov** [comment]
@jhoward1994 this issue persists in Strapi v4.12.4
