### ISSUE TITLE
utils from "@strapi/utils" are not imported

### ISSUE THREAD

**Issue by nickolayArbuzov** [strapi/strapi#17258]
### Required System information

- Node.js version: 18.16.1 or 16.20.0
- NPM version: 9.5.1 or 9.6.4
- Strapi version: 4.11.4
- Database: sqlite or postgres
- Operating system: Windows 10 Pro
- Is your project Javascript or Typescript: Typescript

### Describe the bug

utils from "@strapi/utils" are not imported, which is why we cannot use the utils.errors, for creation of custom errors

### Steps to reproduce the behavior

1. Create any entity by Content-Type Builder from Admin
2. Add lifecycle.ts to src/api/"entity"/content-type/"entity", to the folder where the schema.json is located
3. Add code to lifecycle.ts :
```
import utils from "@strapi/utils"
console.log('utils', utils)
const {ApplicationError} = utils.errors;
      
export default {
  async beforeCreate() {
    new ApplicationError('create-error')
  }
}
```
4. Launch the project to try to create entity and see custom error text
5. The launch of the project crashes, because utils are not imported

### Expected behavior

custom error text(for example - 'create-error') will be displayed in the admin panel, or will come in response from the server when trying to create a new entity - using the admin panel or post-request

### Additional context

in version 4.11.3 - it worked

### Screenshots
![3](https://github.com/strapi/strapi/assets/56513866/9a22e2b0-d9be-4cac-9fbd-e71be2224b6a)

**Comment by joshuaellis** [comment]
I don't believe there's a default export from `@strapi/utils` you could do `import { errors } from "@strapi/utils"` or if you want to keep the naming you've got you could create a namespace – `import * as utils from "@strapi/utils"`

**Comment by nickolayArbuzov** [comment]
Thanks a lot !
this helped: - import {errors} from "@strapi/utils"
