### ISSUE TITLE
Media Library not showing media in folders

### ISSUE THREAD

**Issue by sjorsjes** [strapi/strapi#17261]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.4
- Database: Postgress
- Operating system: Mac OS
- Is your project Javascript or Typescript: Typescript

I run Strapi in Kubernetes using the official Node:16 container.

### Describe the bug
I've got an issue with the Media Library. Users are not able to view the images, in folders, when using the Media component or through the image option in the Rich text component.

- When I just go to the Media Library using the menu item on the left the assets are displayed without issues.
- Images that are in the root (so not in a folder) are shown without issues
- If the user uploads images, to a folder, they are also not visible

### Steps to reproduce the behavior

See the screenshots

### Expected behavior

I expect that any user with all Media Library permissions is able to see all images.

### Screenshots

In the following screenshot you can see that there are 55 assets in the API Uploads but when I click on the API Uploads the folder is shown as empty.

![media-library-issue](https://github.com/strapi/strapi/assets/2182172/826ee75d-f23e-496e-9bce-3dcd6f4a64a2)

But when using the search bar in this view, I do get results.

![Screenshot 2023-07-11 at 09 58 50](https://github.com/strapi/strapi/assets/2182172/1e515433-fbbc-4c5b-8a92-5bed2d8d4922)

The users that have this problem have the follow permissions for the Media Library:

![Screenshot 2023-07-11 at 09 56 16](https://github.com/strapi/strapi/assets/2182172/a904279b-4f7f-48b8-831f-2e134ee3d259)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by joshuaellis** [comment]
This will be fixed in 4.11.5, thank you for your patience and bug reporting :)

**Comment by sjorsjes** [comment]
@joshuaellis I've just updated to patch 4.11.5 and this issue still remains

**Comment by joshuaellis** [comment]
Hey @sjorsjes, i've just spun up a new strapi instance and tested and it all works fine for me – before you got to 4.11.4 did you upgrade from a lower version or is this a relatively new version of strapi?

Did you clear the `.cache | node_modules` folders? failing that did you try delete your lock file too and reinstall and then rebuild the admin panel? :)

**Comment by sjorsjes** [comment]
I updated from 4.11.4. Rebuilding the admin UI fixed the issue 🤦‍♂️. Sorry for the inconvenience!
