### ISSUE TITLE
Media Library - Can`t delete empty folder

### ISSUE THREAD

**Issue by emolchanov** [strapi/strapi#17263]
### Required System information

- Node.js version: v18.16.1
- NPM version: v9.5.1
- Strapi version: v4.11.4
- Database: sqlite
- Operating system: macOS
- Typescript

### Describe the bug

Can`t remove media asset folder from UI.

### Steps to reproduce the behavior

1. Go to 'Media Library'
2. Click on 'Edit folder'
3. Click on 'Delete folder'
4. Click on 'Confirm'
5. See no error and folder in its place

### Code snippets

If edit this file - `node_modules/@strapi/plugin-upload/admin/src/components/EditFolderDialog/EditFolderDialog.js`
like this - the folder will be deleted successfully 
```jsx
<Button
  type="button"
  variant="danger-light"
  onClick={handleDelete} // !!! trigger handleDelete without confirm modal
  name="delete"
  disabled={!canUpdate || isEditFolderLoading}
>
  {formatMessage({
    id: getTrad('modal.folder.create.delete'),
    defaultMessage: 'Delete folder',
  })}
</Button>
```
when debugging - you can see that the `POST` request in the function `bulkRemoveQuery` is canceled at the moment when confirm modal unmount and server API didn't get this request.

`node_modules/@strapi/plugin-upload/admin/src/hooks/useBulkRemove.js`
```jsx
const bulkRemoveQuery = (filesAndFolders) => {
    const payload = filesAndFolders.reduce((acc, selected) => {
      const { id, type } = selected;
      const key = type === 'asset' ? 'fileIds' : 'folderIds';

      if (!acc[key]) {
        acc[key] = [];
      }

      acc[key].push(id);

      return acc;
    }, {});

    return post(url, payload);
};
````

**Comment by codebysid** [comment]
hey, would love to work on this issue ,can you guys assign me this pls ?

**Comment by noobCode-69** [comment]
Hmm, turns out this issue is not specific to empty folders. It folders event though they have some assets inside it.

**Comment by emolchanov** [comment]
Thanks!
