### ISSUE TITLE
Does not show images when trying to assign to an image field

### ISSUE THREAD

**Issue by Ironsites** [strapi/strapi#17289]
### Required System information
Node.js version:18.14.9
NPM version:9.6.0
Strapi version:4.11.3
Database: mysql
Operating system: window 10
Is your project Javascript or Typescript: Javascript

### Describe the bug
Does not show images when trying to assign to an image field

### Steps to reproduce the behavior
1. Open entries
2. Click on Add Image
3. Open folder

### Expected behavior
That the error is solved

### Screenshots
![image](https://github.com/strapi/strapi/assets/90522949/2280ec9c-da46-45d0-8e12-2c548d530374)
![image](https://github.com/strapi/strapi/assets/90522949/700aaf47-ba65-4fc7-b5c1-e6b9fd6d0900)
![image](https://github.com/strapi/strapi/assets/90522949/5253bdfa-4a82-431b-a9da-6005ef1a165f)
![image](https://github.com/strapi/strapi/assets/90522949/4559be36-1fd6-4436-b162-71e79e96b9fe)

**Comment by MonsterDeveloper** [comment]
Same here. Happened after update I guess, but I'm not sure which one exactly.

**Comment by Ironsites** [comment]
> Same here. Happened after update I guess, but I'm not sure which one exactly.

Hello, in version 4.10.3 it works correctly

**Comment by Ironsites** [comment]
Sorry, 4.11.3

**Comment by Ironsites** [comment]
### Required System information
Strapi version:4.11.5

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/17228
