### ISSUE TITLE
GraphQL query results not respecting applied filtering

### ISSUE THREAD

**Issue by pizzaztheo** [strapi/strapi#17303]
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.11.5
- Database: MySQL
- Operating system: macOS
- Is your project Javascript or Typescript: JS

### Describe the bug

My GraphQL queries are not being respected and not returning the correct number of results, neither in the pagination metadata nor in the data results, given the filters applied. The filtering seems to be respected in an earlier version of Strapi I have tested with: 4.7.1.

### Steps to reproduce the behavior

1. Query some content types with GraphQL with filtering setup
2. View the results
3. See all data being returned and filters not respected

### Expected behavior

The GraphQL query results respects the applied filtering

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/16983
