### ISSUE TITLE
Plugin Content-Types, middlewares etc  not registered and visible on v4.11.4/5

### ISSUE THREAD

**Issue by marsicdev** [strapi/strapi#17308]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.5
- Database: pg
- Operating system: macOS
- Is your project Javascript or Typescript: TS

### Describe the bug

Plugin `content-types` are not visible in the UI and are not registered for use if they are defined inside a plugin. After upgrading from v4.11.0 to v4.11.4 and v4.11.5 all `content-types` registered in the plugin are not visible anymore through the `cli` (`yarn strapi content-types:list`) or  Admi UI, the same goes for policies and middleware. The same behavior is happening for the newly generated plugins

### Steps to reproduce the behavior

1. Install strapi v4.11.0 with typescript 
2. yarn strapi generate - new plugin 
3. add some content-types to that plugin and the content types are visible and registered `yarn strapi content-types:list`
4. Upgrate strapi to latest version v4.11.5, do a fresh install and build - content-types from plugin and also middlewares and policies disappear  

Additional
1. Expose some routes from the plugin to content-api and user-permissions on v4.11.0
2. Plugin is visible inside user-permissions plugin
3. After update to v4.11.5 plugin is not visible anymore in user-permissions section

### Expected behavior

Things like this should not break in a patch update, patch updates should maintain backward compatibility. The expected behavior would be to update and all my content types should be visible and exposed on defined routes

### Screenshots

Plugin visible in User permission plugin / Roles  Strapi v4.11.0
![image](https://github.com/strapi/strapi/assets/2347279/8bc0c134-b2fc-453b-81c0-93a15c8bc6f5)

Plugin content types visible in collection types
![image](https://github.com/strapi/strapi/assets/2347279/25573e56-4249-4d37-ae0c-b1b34ef8c9a4)

Content types not visible in version v4.11.4/5
![image](https://github.com/strapi/strapi/assets/2347279/0fff2662-3d44-4a01-8400-6f9aaa85818d)

### Additional context
**1**
Some plugin routes are exposed to content-api like in image below to take advantage on user-permissions plugin
![image](https://github.com/strapi/strapi/assets/2347279/bc44a9b3-5467-4ef3-8a0c-26a001a240fa)

**2**
Install strapi v4.11.5 generate new plugin, enable and start plugin also breaks 
![image](https://github.com/strapi/strapi/assets/2347279/e06685f0-28e0-4fe3-9595-a7737f244ca0)

**Comment by derrickmehaffy** [comment]
Tested on a fresh v4.11.5 project:

![image](https://github.com/strapi/strapi/assets/8593673/1a6ae6bd-9ba2-4806-a1fb-597a72beca77)
![image](https://github.com/strapi/strapi/assets/8593673/83580f3b-4bb4-4cb4-beb5-0131ed0e3b32)
![image](https://github.com/strapi/strapi/assets/8593673/5eed9380-b7bf-4e38-bab5-ffa60e00ebed)

**Comment by Boegie19** [comment]
tested aswell did not replicate the issue

**Comment by derrickmehaffy** [comment]
Marking this as closed until we have updated reproduction steps.
