### ISSUE TITLE
Folder in image field doesn't list correct images when opened

### ISSUE THREAD

**Issue by ChrisCrossCrash** [strapi/strapi#17309]
### Required System information

- Node.js version: 18.16.0
- NPM version: N/A
- Yarn version: 1.22.19
- Strapi version: 4.11.4
- Database: `postgres`
- Operating system: Runs in `node:18.16.0-slim` Docker container
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I'm having an issue where when I try to replace an image in an image field, and that image is in a folder, clicking into the folder lists more than the images in the folder.

### Steps to reproduce the behavior

1. Go to an image field in the Content Manager.
2. Remove the currently assigned image from the field by clicking the trash icon under it.
3. Click the empty image field to open the select image modal.
4. Click on the folder where you want to choose from the images in that folder (it will list the same images as the ones listed in the root folder).

### Expected behavior

The folder should show me only the files that are in that folder. Instead it seems to (at least) list the folders in the root folder.

### Screenshots

Viewing the folder directly in the Media Library works as expected:
![image](https://github.com/strapi/strapi/assets/40023417/d22bd8ed-4adb-44fa-a09c-659452fda8bc)

Viewing the folder from the modal where you can choose a new image shows the incorrect files:

![image](https://github.com/strapi/strapi/assets/40023417/b4137c34-79eb-49e2-9a83-98e28007901d)

### Code snippets

N/A 

### Additional context

My project is part of a Yarn (Classic) Workspaces monorepo, which can cause some things not to work sometimes.

**Comment by joshuaellis** [comment]
Can you upgrade to 4.11.5 please? I believe we fixed this issue for that release.

**Comment by derrickmehaffy** [comment]
(added can not reproduce to wait for them to test with 4.11.5)

**Comment by Katapult1** [comment]
I have a similar problem.
I can upload files to the media gallery folders, but when I try to insert images in the content manager, the contents of the folders are not displayed, only images that are root placed are visible.
V 4.11.7 (node v18.17.0)

**Comment by ChrisCrossCrash** [comment]
Sorry for not responding sooner. Unfortunately the repository where I'm experiencing the problem is private, so I cannot share the code for it. I'll try to reproduce the issue in a new repository if I can find time.
