### ISSUE TITLE
New user invite link won't copy into the clipboard

### ISSUE THREAD

**Issue by Pooyahmti** [strapi/strapi#17306]
System information:

- Node.js version: v18.16.1
- NPM version: 9.5.1
- Strapi version: 4.11.5
- Database: SQlite
- Operating system: Ubuntu 20
- Is your project Javascript or Typescript: Javascript

### Describe the bug

In the users page when I want to add new user, after clicking the "Invite new user" button and filling the form the generated link won't copy into the clipboard no matter how many times I click on the Copy to clipboard button.

### Steps to reproduce the behavior

1. Go to users page
2. Click on Invite new user
3. Fill out the form
4. Click the Copy to clipboard button in front of the generated link
5. Nothing is copied to the clipboard

### Expected behavior

Generated link copied to clipboard

**Comment by derrickmehaffy** [comment]
Tested on Chrome Version 114.0.5735.198 (Official Build) (64-bit) on Linux Mint 21.1 and could not reproduce

**Comment by Pooyahmti** [comment]
Started a fresh project on a clean ubuntu 20.04.6 LTS but the problem persists.
Here's test credentials so you can debug

http://185.218.20.184:1337/admin

***@***.***

Abcd123456
________________________________

**Comment by Pooyahmti** [comment]
> Tested on Chrome Version 114.0.5735.198 (Official Build) (64-bit) on Linux Mint 21.1 and could not reproduce

Started a fresh project on a clean ubuntu 20.04.6 LTS but the problem persists.
Here's test credentials so you can debug 

http://185.218.20.184:1337/admin

test@test.com

Abcd123456

**Comment by creazy231** [comment]
Can reproduce and confirm the error using your provided test environment.

**Comment by bhavesh-chaudhari** [comment]
Having the same issue

**Comment by bhavesh-chaudhari** [comment]
> Having the same issue

Update: I added an SSL certificate to my application using nginx and now the copy to clipboard is working. I guess it doesn't work with http unless it is localhost.

**Comment by Pooyahmti** [comment]
> > Having the same issue
> 
> Update: I added an SSL certificate to my application using nginx and now the copy to clipboard is working. I guess it doesn't work with http unless it is localhost.
Thank you.
I can confirm that too.
It doesn't work over http unless it is localhost.

**Comment by joshuaellis** [comment]
we use the navigator Clipboard API so yes, it requires HTTPS – https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

**Comment by m00nwtchr** [comment]
Can you show the entire url so that it can be copied manually?

**Comment by stromseng** [comment]
Showing the entire url would be nice. I don't want to have to add an SSL cert just for this function to work.

**Comment by SpasojeFR** [comment]
Having the same issue, Showing the entire URL would be nice

**Comment by Fats403** [comment]
The fact that it doesn't show the entire URL by now is pretty crazy as this was posted like a year ago. You should not need an SSL cert just to be able to add users to test it out in dev mode...

For anyone who needs a workaround you can log into your database and query the user you want the token for, an example for postgres

`SELECT * FROM admin_users WHERE email = 'email@admin.com'`

It will be under the registration_token column.
