### ISSUE TITLE
Item "Settings" is shown on the menu even no permission is granted

### ISSUE THREAD

**Issue by thematrixdev** [strapi/strapi#17302]
### Required System information

- Node.js version: v18.16.1
- NPM version: v9.5.1
- Strapi version: v4.11.4
- Database: mysql:8
- Operating system: ubuntu 20.04.6
- Is your project Javascript or Typescript: ts

### Steps to reproduce the behavior

1. Go to /admin
2. Click on "Settings" > "Roles" > "Add new role"
3. Grant "READ" permission to a collection. Click on "Save"
4. Click on "Settings" > "Users" > "Invite new user". Create a new user.
5. Login the new user in another browser.

### Expected behavior

On the menu on the left, only showing items with permission granted.

### Screenshots

![image](https://github.com/strapi/strapi/assets/19472561/49f252e3-3182-4912-a643-aa0c4dee8fc4)

"Settings" is shown. However, none of the items inside could be used.

### Code snippets

N/A

### Additional context

N/A

**Comment by gu-stav** [comment]
I believe this issue is invalid, because application infos is accessible for every user and therefore "Settings" must be visible too.
