### ISSUE TITLE
Enum field validation in component on manual creation with digits only values

### ISSUE THREAD

**Issue by mikenavi** [strapi/strapi#17318]
### Required System information

- Node.js version: 16-20
- NPM version: 8.19.4
- Strapi version: 4.11.5
- Database: Postgres 14
- Operating system: Windows 11 / Ubuntu
- Is your project Javascript or Typescript: TS

### Describe the bug

Manually created **component** scheme accept enum field with digits only values without error.

### Steps to reproduce the behavior

1. create some any_component_scheme.json
2. declare field 
 ```json
"year": {
    "type": "enumeration",
    "required": true,
    "enum": ["2021", "2022", "2023"]
}
```
3. ...no error

### Expected behavior

Some error or warning message on compilation

**Comment by OmPr366** [comment]
@derrickmehaffy can I work on it?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy can I work on it?
> 

You don't need to ask and we don't assign issues. All you have to do is open a pull request.

**Comment by derrickmehaffy** [comment]
Per https://docs.strapi.io/user-docs/content-type-builder/configuring-fields-content-type#-enumeration

> Since Strapi v4.1.3, enumeration values should always have an alphabetical character preceding any number as it could otherwise cause the server to crash without notice when the GraphQL plugin is installed.
