### ISSUE TITLE
Content-Type Builder Enumeration value is invalid

### ISSUE THREAD

**Issue by 1834423612** [strapi/strapi#17316]
### Required System information

- Node.js version:  **v16.20.1**
- NPM version:  **v9.8.0**
- Strapi version:  **v4.11.4 & v4.11.5**
- Database:  **MySQL v5.7.40**
- Operating system:  **CentOS 7.9.2009 x86_64**
- Is your project Javascript or Typescript:  **Javascript**

### Describe the bug

When I use Chinese to make a list at Enumeration, it was told me that the value is invalid.
What should I do to fix it? Because my project need use Chinese.

### Steps to reproduce the behavior

1. Go to **'Content-Type Builder'**
2. Click on '**Add another field**', '**Enumeration**' and fill out the value list with Chinese
3. See error: "**At least one value is invalid. Values should have at least one alphabetical character preceding the first occurence of a number.**"

### Expected behavior

It's should be success to add all the value by the other language except English.

### Screenshots

![image](https://github.com/strapi/strapi/assets/49981661/a9fb9939-a56f-4d57-9d7f-d7ec05143f70)

![image](https://github.com/strapi/strapi/assets/49981661/88e82a8c-7da4-4c35-ad78-4b6eda9fa69e)

![image](https://github.com/strapi/strapi/assets/49981661/f2c6bdfd-9e4c-40c6-b243-279b58aafc84)

### Code snippets

None

### Additional context

None

**Comment by derrickmehaffy** [comment]
Per https://docs.strapi.io/user-docs/content-type-builder/configuring-fields-content-type#-enumeration

> Since Strapi v4.1.3, enumeration values should always have an alphabetical character preceding any number as it could otherwise cause the server to crash without notice when the GraphQL plugin is installed.

Currently enum values only support alpha numeric characters

**Comment by nikita-fuchs** [comment]
@derrickmehaffy is there still a need for this limitation?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy is there still a need for this limitation?

From what I understand yes, to keep compatibility with GraphQL and general enum specs. Enumeration values are a very specific type of field

**Comment by 1834423612** [comment]
okay, thank you for clarifying.
