### ISSUE TITLE
cannot install strapi by (npx create-strapi-app@latest) method tried node version(16/18/20) it shows following error

### ISSUE THREAD

**Issue by shubh2455** [strapi/strapi#17325]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by shubh2455** [comment]
Error while installing dependencies:
warning @strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning @strapi/strapi > @strapi/admin > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/admin > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.11.5" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.11.5" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.11.5" has unmet peer dependency "react-router-dom@5.3.4".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.11.5" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/strapi > @strapi/plugin-email@4.11.5" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email@4.11.5" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email@4.11.5" has unmet peer dependency "react-router-dom@5.3.4".
warning "@strapi/strapi > @strapi/plugin-email@4.11.5" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/strapi > @strapi/plugin-upload@4.11.5" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-upload@4.11.5" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-upload@4.11.5" has unmet peer dependency "react-router-dom@5.3.4".
warning "@strapi/strapi > @strapi/plugin-upload@4.11.5" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/plugin-users-permissions > formik@2.4.0" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.8.1" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.8.1" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.8.1" has unmet peer dependency "react-router-dom@^5.2.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.8.1" has unmet peer dependency "styled-components@^5.2.1".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.11.5" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.11.5" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.11.5" has unmet peer dependency "react-router-dom@^5.3.4".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.11.5" has unmet peer dependency "styled-components@^5.3.3".
warning "@strapi/plugin-users-permissions > @strapi/icons@1.8.1" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/icons@1.8.1" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > react-redux@8.1.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-users-permissions > react-intl@6.4.1" has unmet peer dependency "react@^16.6.0 || 17 || 18".
warning "@strapi/plugin-users-permissions > react-query@3.39.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror@4.21.7" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror@4.21.7" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror@4.21.7" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror@4.21.7" has unmet peer dependency "codemirror@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.7" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.7" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.7" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.7" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.7" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > codemirror > @codemirror/autocomplete@6.8.1" has unmet peer dependency "@lezer/common@^1.0.0".
warning " > @strapi/plugin-users-permissions@4.11.5" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-users-permissions@4.11.5" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-users-permissions@4.11.5" has unmet peer dependency "react-router-dom@5.3.4".
warning " > @strapi/plugin-users-permissions@4.11.5" has unmet peer dependency "styled-components@5.3.3".
warning " > @strapi/plugin-i18n@4.11.5" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-i18n@4.11.5" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-i18n@4.11.5" has unmet peer dependency "react-router-dom@5.3.4".
warning " > @strapi/plugin-i18n@4.11.5" has unmet peer dependency "styled-components@5.3.3".
error /Users/shubham/Desktop/pr2/m/node_modules/better-sqlite3: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild --release
Arguments: 
Directory: /Users/shubham/Desktop/pr2/m/node_modules/better-sqlite3
Output:
prebuild-install warn install No prebuilt binaries found (target=16.16.0 runtime=node arch=arm64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.16.0 | darwin | arm64
gyp info find Python using Python version 3.10.5 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.16.0/SHASUMS256.txt
gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/Desktop/pr2/m/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/shubham/Library/Caches/node-gyp/16.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/shubham/Library/Caches/node-gyp/16.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/shubham/Library/Caches/node-gyp/16.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/shubham/Desktop/pr2/m/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/shubham/Desktop/pr2/m/node_modules/better-sqlite3
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /Users/shubham/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:67:28
    at Array.forEach (<anonymous>)
    at captureStderr (/Users/shubham/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:66:14)
    at createProject (/Users/shubham/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:136:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createQuickStartProject (/Users/shubham/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:21:5)

**Comment by derrickmehaffy** [comment]
FYI you are missing apples dev tools as the error suggests

**Comment by mauriciabad** [comment]
I was having a similar problem, and it got solved for me by installing Python and using the latest node version.
