### ISSUE TITLE
Issue with Role-Based Access Control in Strapi’s Media Library

### ISSUE THREAD

**Issue by ErvinasM** [strapi/strapi#17320]
### Required System information

- Node.js version: **18.16.1**
- NPM version: **9.3.1**
- Strapi version: **4.11.5**
- Database: **mySQL/SQLite**
- Operating system: **Windows OS**
- Is your project Javascript or Typescript: **Javascript**

### Describe the bug

I am encountering a perplexing problem related to Strapi’s Media Library and Role-Based Access Control (RBAC). In my current project, as well as in a newly created one, users assigned the role of “Author” are unable to access the Media Library. The default behavior for the “Author” role should allow access to the Media Library and the ability to upload their own content. Additionally, the “Author” role should only permit visibility of their personally uploaded media.

Regrettably, despite setting up the “Author” role as intended, the expected functionality is not being observed. Instead, when users with the “Author” role attempt to access the Media Library, they are presented with a permission error message, indicating that they lack the necessary permissions.

To provide some context, I have thoroughly reviewed the Role-Based Access Control settings within Strapi and verified that the “Author” role has the appropriate permissions for accessing and managing media in the Media Library. Nevertheless, this does not seem to resolve the issue.

I have sought potential solutions by exploring relevant documentation, forums, and community resources, but to no avail. I would be immensely grateful if anyone could offer insights, suggestions, or possible solutions to rectify this challenge.

### Steps to reproduce the behavior

Create new Strapi project

### Expected behavior

I hoped that when user with Author role logs-in, the user would be able to access Media Library but only see his own content that he has uploaded.

### Screenshots

Author's view
![image](https://github.com/strapi/strapi/assets/73030569/62580cc1-2c6f-4a2c-952d-f9bcd093938e)

Author's role configuration (Default)
![image](https://github.com/strapi/strapi/assets/73030569/82f190cc-f3e3-4055-81f6-672c21603ea4)

**Comment by OmPr366** [comment]
@derrickmehaffy  can I work on it?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy  can I work on it?
> 

Same here you don't need to ask and we don't assign issues just don't put a pull request.

**Comment by derrickmehaffy** [comment]
this is more of a feature request/enhancement. I'll close this in favor of https://feedback.strapi.io/feature-requests/p/permission-management-for-media-library-folders though I know it's not just folders. I'll copy this issue into the feature request.
