### ISSUE TITLE
Arabic characters in text field Issue

### ISSUE THREAD

**Issue by MhmodTayel** [strapi/strapi#17323]
### Required System information

- Node.js version: v18.9.0
- NPM version: 9.6.6
- Strapi version: 4.10.7
- Database: PostgreSQL
- Operating system: Linux Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I write Arabic words in a text field it throws a internal server error: value too long for type character varying(255)

` strapi-db_1      | 2023-07-16 16:30:18.473 UTC [31438] ERROR:  value too long for type character varying(255)
strapi-db_1      | 2023-07-16 16:30:18.473 UTC [31438] STATEMENT:  insert into "public"."news" ("created_at", "created_by_id", "link", "published_at", "title", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5, $6, $7) returning "id"
strapi_1         | [2023-07-16 16:30:18.475] error: insert into "public"."news" ("created_at", "created_by_id", "link", "published_at", "title", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - value too long for type character varying(255)
strapi_1         | error: insert into "public"."news" ("created_at", "created_by_id", "link", "published_at", "title", "updated_at", "updated_by_id") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - value too long for type character varying(255)
strapi_1         |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)`

### Screenshots
![image](https://github.com/strapi/strapi/assets/38634328/dd454778-78ee-4cd9-8ddd-33f4aae51ccf)

### Code snippets
schema 

`  "Title": {
      "type": "string",
      "required": true,
      "maxLength": 100000
    }`

    test value : 
    تحليل خط المستخدم وماذا يكشف عن شخصيته بعد رسالة كتبها في كينيا يثير تفاعلا

**Comment by derrickmehaffy** [comment]
Can you confirm the encoding for your PG database as I'm not able to reproduce the issue.
