### ISSUE TITLE
[v4] API doesn't respect Draft in relations

### ISSUE THREAD

**Issue by vandres** [strapi/strapi#17338]
## Bug report

We found this ticket with a similar problem, but ours is for the REST API [#Graphql returns DRAFT](https://github.com/strapi/strapi/issues/17138)

We have a page content model, which can have content elements, which can links team members:

<img width="673" alt="grafik" src="https://github.com/strapi/strapi/assets/1436383/98362304-5325-4db9-ac2c-8be3ce5518a7">

This is how the page looks like:

![grafik](https://github.com/strapi/strapi/assets/1436383/7f24bbcf-adaf-4781-a481-61157e1f4a4c)

When requesting the team members over the api `http://localhost:1338/api/teams`, the Draft members are not visible. When requesting the page, which has the team content element, the Draft members are visible `http://localhost:1338/cms/pages/24?populate=content.teams`

![grafik](https://github.com/strapi/strapi/assets/1436383/da156463-3ea7-41b7-8ead-142578a95d36)

We are very sure, this worked in Strapi v3.

### Required System information

- Node.js version: v16.20.1
- NPM version: 8.19.4
- Strapi version: v4.11.4
- Database: SQLite
- Operating system: MacOS
- Is your project Javascript or Typescript: JS

**Comment by derrickmehaffy** [comment]
Dang I literally reopened that issue earlier today and didn't see this one. Thank you for the confirmation though as it's certainly not intended.

I'll close this as a duplicate to https://github.com/strapi/strapi/issues/17138 but both are not intended.
