### ISSUE TITLE
strapi 4.11.5 not working with cloudinary

### ISSUE THREAD

**Issue by harryvu** [strapi/strapi#17330]
### Required System information

- Node.js version: 18.16.1
- NPM version: 8.3.1
- Strapi version: 4.11.5
- Database: postgres
- Operating system: linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I followed this [article ](https://strapi.io/blog/add-cloudinary-support-to-your-strapi-application)and read many others and spent more than a day on it, but no matter what I did, it always upload images to the public/uploads folder! Am I missing something? Please help.

Below are some important files:

./config/plugins.js
module.exports = ({ env }) => ({
upload: {
enabled: true,
config: {
provider: "cloudinary",
providerOptions: {
cloud_name: env("CLOUDINARY_NAME"),
api_key: env("CLOUDINARY_KEY"),
api_secret: env("CLOUDINARY_SECRET"),
},
actionOptions: {
upload: {},
uploadStream: {},
delete: {},
},
},
},
});

./config/middlewares.js
module.exports = [
"strapi::errors",
{
name: "strapi::security",
config: {
contentSecurityPolicy: {
useDefaults: true,
directives: {
"connect-src": ["'self'", "https:"],
"img-src": ["'self'", "data:", "blob:", "res.cloudinary.com"],
"media-src": ["'self'", "data:", "blob:", "res.cloudinary.com"],
upgradeInsecureRequests: null,
},
},
},
},
//...
];

package.json
"devDependencies": {},
"dependencies": {
"@strapi/plugin-i18n": "4.11.5",
"@strapi/plugin-users-permissions": "4.11.5",
"@strapi/provider-upload-cloudinary": "4.11.5",
"@strapi/strapi": "4.11.5",
"pg": "8.8.0"
},

**Comment by derrickmehaffy** [comment]
Tested on v4.11.5 and was unable to reproduce

**Comment by harryvu** [comment]
I created a fresh strapi project with same exact same configuration with cloudinary upload plugin, everything works as expected. I am still not sure what caused the issue, but I will close this bug. Will add some notes here if I can nail down the root cause. Thank you.

**Comment by rafaneri** [comment]
@derrickmehaffy I'm getting the same on v 4.11.7.

### Required System information




- Node.js version: 16.20.1
- NPM version: 8.19.4
- Strapi version: 4.11.7
- Database: postgress
- Operating system: macOs Ventura (M1)
- Is your project Javascript or Typescript: Javascript (but Typescript was enabled manually)

```json
{
  "name": "api-core",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@palmabit/strapi-app-version": "^1.1.0",
    "@strapi/plugin-graphql": "^4.11.7",
    "@strapi/plugin-i18n": "4.11.7",
    "@strapi/plugin-users-permissions": "4.11.7",
    "@strapi/provider-upload-cloudinary": "^4.11.7",
    "@strapi/strapi": "4.11.7",
    "better-sqlite3": "8.0.1",
    "pg": "^8.11.1",
    "strapi-chatgpt": "^1.0.2",
    "strapi-location-field-plugin": "^1.2.2",
    "strapi-plugin-import-export-entries": "^1.21.0",
    "strapi-plugin-multi-select": "^1.2.2"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "2d67b701-31ad-4513-b06d-4a9b7e4ccaad"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

#### ./config/plugin.js
```javascript
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: 'cloudinary',
      providerOptions: {
        cloud_name: env('CLOUDINARY_NAME'),
        api_key: env('CLOUDINARY_KEY'),
        api_secret: env('CLOUDINARY_SECRET'),
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
  'import-export-entries': {
    enabled: true,
  },
  'strapi-chatgpt': {
    enabled: true,
  },
  'location-field': {
    enabled: true,
    config: {
      fields: ["rating"], // optional
      // You need to enable "Autocomplete API" and "Places API" in your Google Cloud Console
      googleMapsApiKey: env('GOOGLE_MAPS_API_KEY'),
      // See https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest
      autocompletionRequestOptions: {
        language: 'pt-BR',
        locationBias: 'IP_BIAS',
      },
    },
  },
});
```

#### ./config/middlewares.js
```javascript
module.exports = [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'script-src': ["'self'", "'unsafe-inline'", 'maps.googleapis.com'],
          'connect-src': ["'self'", 'https:'],
          'img-src': ["'self'", 'data:', 'blob:', 'market-assets.strapi.io', 'res.cloudinary.com'],
          'media-src': [
            "'self'",
            'data:',
            'blob:',
            'market-assets.strapi.io',
            'res.cloudinary.com',
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

**Comment by rafaneri** [comment]
Additional information, follow debug print, and the upload configuration uses local when the application is running, but the plugin.js uses cloudinary.

<img width="944" alt="image" src="https://github.com/strapi/strapi/assets/7685408/a5c7a685-4185-4b65-a8c2-d4d4c6fb7745">

**Comment by rafaneri** [comment]
In my case only the file name, was incorrect! **plugin.js** but the correct is **plugins.js**

**Comment by derrickmehaffy** [comment]
Was about to comment and say the file name is wrong. It's plugins not plugin
