### ISSUE TITLE
Strapi relations update doesn't work

### ISSUE THREAD

**Issue by ahmadjoya** [strapi/strapi#17345]
## Bug report

# Strapi relations update doesn't work

### Required System information
- Node.js version: v18.15.0
- NPM version: 9.5.0
- Strapi version: 4.11.5
- Database: PostgreSQL
- Operating system: Windows 10
- Is your project Javascript or Typescript: Javascript

### Bug details
I have the latest version of strapi yet. when I create two collections and enter data in both, then when I update one of the relations from those tables, it says "something wrong".
here I recorded a video of the issue.
video link: https://www.loom.com/share/f89e59789bca487784fbb70cf53ea8ae?sid=6341c7f6-219e-49e2-a24c-bda222949ae7

### Screenshot
![image](https://github.com/strapi/strapi/assets/35627961/10e851fa-7608-4ed7-a39c-28b39289af3f)

**Comment by joshuaellis** [comment]
This was fixed by #17340, you could install our nightly version to resolve this for you, otherwise it'll be released in 4.12

**Comment by ahmadjoya** [comment]
how to install your nightly version?

**Comment by hasebsiddiqui** [comment]
You can use this work around until v12 is released. Add a `short text` field in `carPic`

**Comment by ahmadjoya** [comment]
@hasebsiddiqui thank you
