### ISSUE TITLE
FSEvents error when the admin is running in dev mode

### ISSUE THREAD

**Issue by krsnaa** [strapi/strapi#1734]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: mongoDB v4.0.0
- **Operating system**:  macOS High Sierra v10.13.6

**What is the current behavior?**

I am following the dev-environment progression from https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md. 

I can create a new dev-project using the `--dev` flag and start it with `strapi start` just fine.
But when I try to run `npm start` in the admin folder, I get the following error spew:

(base) iMac:admin username$ npm start
> strapi-admin@3.0.0-alpha.13.0.1 prestart /Users/-- path --/strapi-master/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

> strapi-admin@3.0.0-alpha.13.0.1 start /Users/-- path --/strapi-master/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server

Strapi plugin succesfully started in development mode. ✓

>-----------------------------------
Access URL: http://localhost:4000/admin
>-----------------------------------
Press CTRL-C to stop
    
webpack built c04610cb4e398a7aa005 in 37603ms

>2018-08-08 11:11 node[3013] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
>2018-08-08 11:11 node[3013] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
>2018-08-08 11:11 node[3013] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
>2018-08-08 11:11 node[3013] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
...

**Steps to reproduce the problem**
https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md. 

These are my default file limits:

`launchctl limit`

>cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     2128           3192           
	maxfiles    256            unlimited      

`ulimit -a`
>core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2128
virtual memory          (kbytes, -v) unlimited

I investigated this issue and found that it is mostly caused due to insufficient maxfiles setting and so, tried increasing the maxfiles soft and hardlimits using:
`sudo launchctl limit maxfiles 100000 100000`

and setting the shell open-files limit using:
`ulimit -n 100000`

but still get the exact same error.

**What is the expected behavior?**
To not get the error spew above and for it to work.

**Suggested solutions**

**Comment by krsnaa** [comment]
It appears that https://github.com/webpack/webpack-dev-server/issues/690 might have something to do with this.

**Comment by krsnaa** [comment]
https://github.com/strapi/strapi/issues/1353 seems relevant as well since I get the same errors right after the above ones.

**Comment by soupette** [comment]
Hi @krsnaa I'm aware of the bug it happens because webpack is watching too many files.

Even though the error is present the front-end server works fine. Until we fix it, you can just uninstall a plugin like the settings-manager (`rm -r plugins/settings-manager`) and the error goes away while developing.

**Comment by krsnaa** [comment]
@soupette - thanks for your reply. uninstalling one of the plugins like you had mentioned does make the FSEvents.framework error go away. But, I still get the errors from the helper-plugin saying that it is unable to find the config/layout.js for the plugins, as under:


```
/- path -/strapi-dev/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src/app.js
Module not found: Error: Can't resolve '../../../../config/layout.js' in '/- path -/strapi-dev/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src'
 @ /- path -/strapi-dev/plugins/content-manager/node_modules/strapi-helper-plugin/lib/src/app.js 63:11-50

/- path -/strapi-dev/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src/app.js
Module not found: Error: Can't resolve '../../../../config/layout.js' in '/- path -/strapi-dev/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src'
 @ /- path -/strapi-dev/plugins/content-type-builder/node_modules/strapi-helper-plugin/lib/src/app.js 63:11-50

/- path -/strapi-dev/plugins/email/node_modules/strapi-helper-plugin/lib/src/app.js
Module not found: Error: Can't resolve '../../../../config/layout.js' in '/- path -/strapi-dev/plugins/email/node_modules/strapi-helper-plugin/lib/src'
 @ /- path -/strapi-dev/plugins/email/node_modules/strapi-helper-plugin/lib/src/app.js 63:11-50

/- path -/strapi-dev/plugins/upload/node_modules/strapi-helper-plugin/lib/src/app.js
Module not found: Error: Can't resolve '../../../../config/layout.js' in '/- path -/strapi-dev/plugins/upload/node_modules/strapi-helper-plugin/lib/src'
 @ /- path -/strapi-dev/plugins/upload/node_modules/strapi-helper-plugin/lib/src/app.js 63:11-50
```


The above error results in nothing showing up on the window, but for these toasts:

![image](https://user-images.githubusercontent.com/6718752/43998203-03d40906-9da5-11e8-8748-9b8a1e646d65.png)

**Comment by soupette** [comment]
These warnings don't affect the admin panel, these file aren't required for the admin to work they just add functionalities.

**Comment by soupette** [comment]
If you using a mac I suggest you to install `watchman`:

```bash
brew install watchman
```

Also, this [PR](https://github.com/strapi/strapi/pull/2861) fixes the issue.

Also, since the webpack still runs without major issue I suggest to close this issue.

**cc/** @lauriejim
