### ISSUE TITLE
Modifying Responses in Lifecycle Callbacks

### ISSUE THREAD

**Issue by mindgrub-rkoch** [strapi/strapi#1735]
**What is the expected behavior?**

This may or may not be a feature request. I have looked through the docs and the open and closed issues, and can't seem to find what I'm looking for.

I would like to be able to modify data in lifecycle callbacks, prior to them reaching the database, or after they've been fetched from the database.

As an example, I query a table for products, and the `isFavorite` value is dynamically set on the response based on data retrieved from other API calls before it is sent back to the client.

Is this functionality currently supported? And if not, I would like to add this as a feature request.

Thanks

**Comment by lauriejim** [comment]
Hello @mindgrub-rkoch. In your `api/.../models/....js` you have lifecycle.
Documentation here https://strapi.io/documentation/guides/models.html#lifecycle-callbacks

I think it can help you.

**Comment by mindgrub-rkoch** [comment]
Thanks.

I read through what documentation was there, and did some experimenting. It seems as though you can modify responses only if the key exists on the model before-hand. It's not an ideal situation, but it could work for smaller sets of data.

Preferably, you should be able to modify the response by inserting/removing any key/value pairs necessary, without having to first add the key to the model schema.

**Comment by lauriejim** [comment]
@mindgrub-rkoch did you use **mongoose** or **bookshelf** ?

**Comment by mindgrub-rkoch** [comment]
I believe I'm using mongoose as I am using a MongoDB.

**Comment by sefasaid** [comment]
i need help with this to. i cant find an example for afterFetchAll and i cant modify reponse

**Comment by lauriejim** [comment]
You can't add key that not exist in you model.
Try to update and existing key, it will work.

**Comment by ieow** [comment]
Having issue on extensions/user-permissions/models/user.js
the callback in the extension was not called.
other api's callback is working. Just the user in the extension is not.
Any Idea?
using v3.0.0 beta.15

**Comment by m-farahmand** [comment]
what about server response, how we can change http status code. For example when a data is not valid

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
