### ISSUE TITLE
Starting Strapi TypeScript project with utils.errors causes app to crash

### ISSUE THREAD

**Issue by Ooyashi** [strapi/strapi#17366]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.5.
- Database: SQLite 3
- Operating system: Linux 6.1.38-1 (LTS), Manjaro distro
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I've updated the Strapi and its plugins to the latest version. Running `npm run develop` started throwing the error:

```
Starting the compilation for TypeScript files in /home/dmytro/Projects/calis-books-content
Building your admin UI with development configuration...
Admin UI built successfully
TypeError: Cannot read properties of undefined (reading 'errors')
    at Object.<anonymous> (/home/dmytro/Projects/calis-books-content/dist/src/api/household/services/household.js:14:41)
```

After my own investigation I found the issue. For some reason, this piece of TypeScript code:

```
import utils from '@strapi/utils';

const { PolicyError } = utils.errors;
```

Is translated to such JS code:

```
const utils_1 = __importDefault(require("@strapi/utils"));
const { PolicyError } = utils_1.default.errors;
```

After several attempts I got the project running with the removal of `default` property and `npm start` to not rebuild the dist folder:

`const { ApplicationError, NotFoundError } = utils_1.errors;`

I tested afterwards and errors started working, e.g.

```
{
    "data": null,
    "error": {
        "status": 400,
        "name": "BadRequestError",
        "message": "Household controller error: PolicyError: This user has already been invited.",
        "details": {}
    }
}
```

This is bug with the all JS translated code which uses the Strapi utils, e.g.

```
import utils from '@strapi/utils';

const { PolicyError } = utils.errors;
```

```
import utils from '@strapi/utils';

const { NotFoundError } = utils.errors;
```

### Steps to reproduce the behavior

1. Update Strapi to latest version
2. Make some Entity and endpoint which uses the Strapi errors (https://docs.strapi.io/dev-docs/error-handling#services-and-models-lifecycles)
3. Run the `npm run develop`

### Expected behavior

No errors happen, I can work as usual

### Screenshots

![зображення](https://github.com/strapi/strapi/assets/73554716/8e89821f-7de4-4fd7-abb7-61660d17326d)

![зображення](https://github.com/strapi/strapi/assets/73554716/0e88d79c-bbcf-40bd-9a4b-004cf8cde34f)

### Code snippets

TypeScript Code:

```
import utils from '@strapi/utils';

const { PolicyError } = utils.errors;
```

```
    if (invitation.isAccepted) {
      throw new PolicyError('This user has already been invited.', {
        policy: 'already-invited-user',
      });
    }
```

### Additional context

This happened after updating Strapi from 4.11.1 to 4.11.5, no changes were made in my code at all.

**Comment by Boegie19** [comment]
Workaround

```ts
import {errors} from '@strapi/utils';

const { PolicyError } = errors;
```
