### ISSUE TITLE
Google provider missing session or misconfigured provider

### ISSUE THREAD

**Issue by idesignzone** [strapi/strapi#17370]
### Required System information
- Node.js version:  16.14.0
- NPM version: 8.3.1
- Strapi version: 4.8.2
- Database: postgres
- Operating system: Win
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have followed the [documentation](https://docs.strapi.io/dev-docs/plugins/users-permissions) on how to add Google auth to my Vue.js application, but I keep getting error 400.

### Steps to reproduce the behavior

1. Add google app ID and secret to strapi/providers/google
2. add redirect url to google app (The redirect URL to add in your google application configurations)
3. setup vue.js app and create route for (The redirect URL to your front-end app)
4. get the id_token param and make a request to strapi to get user info

### Expected behavior

Expecting a login but receives 400 application error.

### Screenshots
Strapi provider settings

![strapi-provider-google](https://github.com/strapi/strapi/assets/3501211/a9e803cd-c2cd-4a08-80ce-273bbdbc6cb6)

Strapi console with 302 status

![image](https://github.com/strapi/strapi/assets/3501211/0f62c329-771c-45b7-9105-fc850a333e46)

### Code snippets

```
    fetch(baseUrl + "/api/auth/google/callback?access_token=" + token, {
      method: "GET",
      headers: {
        Authorization: "Bearer " + import.meta.env.AUTH_TOKEN,
        Accept: "application/json",
        "Content-Type": "application/json",
      },
    })
    .then(res => {
      if (res.status !== 200) {
        throw new Error(`Couldn't login to Strapi. Status:`)
      }
      return res
    })
    .then(res => res.json())
    .then(res => {
      console.log(res);
    })
    .catch(err => {
      console.log(err);
    })
```

### Additional context

I've gone through Troubleshooting section in the docs but this problem still exists.

**Comment by idesignzone** [comment]
Any updates on this?

**Comment by AhmedMuhsingez** [comment]
I am currently facing this issue.. did you manage to get it fixed? @idesignzone
