### ISSUE TITLE
Bug or strange behavior  positioning of Fields in Admin Panel

### ISSUE THREAD

**Issue by BroTrue** [strapi/strapi#1738]
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: MongoDB
- **Operating system**: Debian

**What is the current behavior?**

Strange positioning of Fields in Admin Panel

**Steps to reproduce the problem**

1. Creat new Content Type with such fields 

![order](https://user-images.githubusercontent.com/23247940/43919812-62317248-9c17-11e8-98b3-b6f16639ee05.png)

2. Open it 

![look](https://user-images.githubusercontent.com/23247940/43919847-941bf06c-9c17-11e8-9131-9769c1b90856.png)

**What is the expected behavior?**

Show all fields in the same order, as we created

**Suggested solutions**

This bug/behavior usually happeds when I try to add 2x CheckBox (that used class `col-md-3`). It can be a result of boostrap v4 that use "Flex". Maybe change `class` of CheckBox to `col-md-6`? I`m good with styling,css and so on... I could fix it, but I dont know React and cant find there this styles... =(

**Comment by derrickmehaffy** [comment]
@brotrue I've had something similar adding json types. The the PR @soupette submitted we will be able to modify that view. It is pending some code review

**Comment by BroTrue** [comment]
@derrickmehaffy owwww that nice, maybe you can give me date when this PR will available?
But the way, I will finish my small project soon and as a sign of gratitude to StrapiTeam ( that help me a lot) I can prepare tutorial with example such project as my. :)

**Comment by soupette** [comment]
@BroTrue the PR is ready see #1684 however, it won't be released before the 17th of August...

If you have installed from the monorepo you can get it before the release though

**Comment by bts94** [comment]
Any idea when we'll see a new release with it?

**Comment by derrickmehaffy** [comment]
@bts94 It is a *VERY* large PR so prob not any real ETA. The team needs to check it to ensure there are no bugs. As @soupette has said you can use the mono-repo if you want it now (And bug test it for them :stuck_out_tongue: )

**Comment by soupette** [comment]
@derrickmehaffy we've tested it, we just need to review the PR now...

**Comment by derrickmehaffy** [comment]
So not before the 28th then @soupette :stuck_out_tongue_closed_eyes:

**Comment by lauriejim** [comment]
Content Manager customization has been released since 2 versions of Strapi.
