### ISSUE TITLE
`strapi routes:list` no longer listing most routes

### ISSUE THREAD

**Issue by notjosh** [strapi/strapi#17390]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1 (`yarn` version: 1.22.19)
- Strapi version: 4.11.7
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

After upgrading to [v4.11.7](https://github.com/strapi/strapi/releases/tag/v4.11.7), running `yarn strapi routes:list` no longer lists most routes in my project.

### Steps to reproduce the behavior

On any (?) Strapi project, run `yarn strapi routes:list` and only 7 base routes are listed - no plugins, no API, etc:

<details>
<summary>
`yarn strapi routes:list` output
</summary>

```
$ yarn strapi routes:list
yarn run v1.22.19
$ strapi routes:list
Starting the compilation for TypeScript files in /path/to/project
┌────────────────────┬─────────────────────┐
│ Method             │ Path                │
├────────────────────┼─────────────────────┤
│ HEAD|ACL|BIND|CHE… │ /_health            │
├────────────────────┼─────────────────────┤
│ HEAD|GET           │ /uploads/(.*)       │
├────────────────────┼─────────────────────┤
│ HEAD|GET           │ /admin/:path*       │
├────────────────────┼─────────────────────┤
│ HEAD|GET           │ /                   │
├────────────────────┼─────────────────────┤
│ HEAD|GET           │ /index.html         │
├────────────────────┼─────────────────────┤
│ HEAD|GET           │ /assets/images/(.*) │
├────────────────────┼─────────────────────┤
│ HEAD|GET           │ /((?!uploads/).+)   │
└────────────────────┴─────────────────────┘
✨  Done in 9.44s.
```
</details>

### Expected behavior

I would expect to see routes to built-in things, like:

- `/admin/...`
- `/api/...`
- `/content-manager/...`
- `/content-type-builder/...`
- `/i18n/...`
- `/users-permissions/...`

etc

### Additional context

4.11.7 included the changes from [this PR](https://github.com/strapi/strapi/pull/17290). When I add that code back in, I get the full output of all routes.

**Comment by derrickmehaffy** [comment]
Confirmed: 
![image](https://github.com/strapi/strapi/assets/8593673/8e04f20f-8d82-4a7d-9e26-956186a7380e)
