### ISSUE TITLE
Relation filed search not working as before + wrong layout

### ISSUE THREAD

**Issue by radoslavzeman** [strapi/strapi#17391]
### Required System information

- Node.js version: v16.20.1
- NPM version: 7.24.2
- Strapi version: 4.11.7
- Database: postgres
- Operating system: macOS Ventura
- Is your project Javascript or Typescript: ts

### Describe the bug

When searching in relation field, it returns results matching only beginning of the "relation display field". Before, it matched all results.

E.g. we have childPages, using `path` as main relations display field. Typing `ubytovanie` should return `bratislava-pre-ukrajinu/ubytovanie` but it doesn't.

Choosing some relations manually works. Search matching the beginning works.

But the layout is somehow broken.

### Expected behavior

Search in relations field should work correctly. The layout should display correctly.
It would be nice if it also ignores accents (áéšťýö etc...)

### Screenshots

![image](https://github.com/strapi/strapi/assets/19418224/05a92b5e-ce83-4d09-99bf-093f7e9ba5b8)
![image](https://github.com/strapi/strapi/assets/19418224/a647168e-8c6a-41e9-b24a-099bb4f86bb7)

![image](https://github.com/strapi/strapi/assets/19418224/d1bf61bb-70c3-4d78-95e5-80ebc10506aa)

**Comment by dernetzjaeger** [comment]
I can confirm the change in searching behaviour when searching for a relations.

The code what changes it, seems to be in the v4.11.4 release.
Before v4.11.4 the search worked like "contains" filter, after updating to v4.11.4 it works like a "starts with" filter.

Maybe it is caused by #16671

**Comment by nicoXXXXXtitan** [comment]
Hello

I can confirm that we have the same problem. We are currently on 4.13.6 
We preferred to do all the latest updates for security reasons but it's true that it really complicates the work of our editors.

**Comment by vadym-lohvynovych** [comment]
Same here. I'm the one who created the topic on Strapi Community Forum. We had to decrease our strapi version because this issue makes work for our content manager much more complicated.

**Comment by Seyolas** [comment]
> Same here. We had to decrease our strapi version because this issue makes work for our content manager much more complicated.

we are currently on 4.12.5. Which version are you decreased ? Look's like it works correctly in your decreased version.

**Comment by vadym-lohvynovych** [comment]
> > Same here. We had to decrease our strapi version because this issue makes work for our content manager much more complicated.
> 
> I can confirm that we have the same problem. We are currently on 4.12.5 to which version are you decreased ? Look's like it works correctly in your decreased version.

We're using 4.10.2 because this this the one that was working before, I've just reverted PR and did not investigate on which exact version this behaviour changed.

**Comment by radoslavzeman** [comment]
Hello guys,
mentioned PR does not fix this issue (as also the autor stated), please reopen.

**Comment by radoslavzeman** [comment]
Hello guys,
@joshuaellis @derrickmehaffy 
This PR does not solve any of the problems mentioned in this issue. Could you please reopen it?

Is there some plan when the functionality will be back as before? 

Thank you!

**Comment by adrien-may** [comment]
If we can chose between contains/startsWith, it's fine. The problem is : the behavior changed suddenly from contains to startWith without notice and it's a real pain for content teams.
My suggestion : revert to "contains" only and consider adding an option for startsWith in the future if relevant ?

**Comment by jasperhartong** [comment]
This was breaking the admin for us as well. Created a hacky stopgap solution in the form of a middleware, perhaps useful for anyone else in the meanwhile.

1. It changes the filter param to be $containsi
2. It prefixes the results with the query string so they are not filtered out on the client

<img width="573" alt="Screenshot 2023-10-19 at 20 47 02@2x" src="https://github.com/strapi/strapi/assets/47074382/0101a723-3434-4953-a89e-2521dcdccae5">


`/src/middlewares/fix-search-middleware.js`
```
const { prop, flow } = require("lodash/fp");

// Not pretty, but it seems to work and allows our content team to continue to work

module.exports = (config, { strapi }) => {
  return async (context, next) => {
    const isRelationSearch = context.request.url.startsWith(
      "/content-manager/relations"
    );
    const hasQuery = !!context.query._q;

    // Only run fix if we're searching a relation and there's a query
    if (!isRelationSearch || !hasQuery) {
      return await next();
    }

    // Update query to $containsi instead of $startsWith in:
    // https://github.com/strapi/strapi/commit/b39586bf8d6885ecb23ecd22a9136a8675348d67
    context.query._filter = "$containsi";

    // Perform rest of middlewares and the actual query
    await next();

    // Update results to prefix mainField with the query string so it actually shows up and not filtered out client-side with "startsWith"
    // https://github.com/strapi/design-system/blob/0c8968cd9b9c22ed565b17c8de9120e8b4779abc/packages/primitives/src/components/Combobox/Combobox.tsx#L970-L974
    try {
      const mainField = await getMainField(context, strapi);
      context.response.body.results = context.response.body.results.map(
        (r) => ({
          ...r,
          [mainField]: `${context.query._q} ➡ ${r[mainField]}`,
        })
      );
    } catch (error) {
      console.error("Failed patching the search results");
      console.error(error);
    }
  };
};

const getMainField = async (context, strapi) => {
  // Exstracted from: https://github.com/strapi/strapi/blob/b39586bf8d6885ecb23ecd22a9136a8675348d67/packages/core/content-manager/server/controllers/relations.js
  const { targetField, model } = context.params;
  const modelSchema = strapi.getModel(model);
  const isComponent = modelSchema.modelType === "component";
  const modelConfig = isComponent
    ? await strapi
        .plugin("content-manager")
        .service("components")
        .findConfiguration(modelSchema)
    : await strapi
        .plugin("content-manager")
        .service("content-types")
        .findConfiguration(modelSchema);

  const mainField = flow(
    prop(`metadatas.${targetField}.edit.mainField`),
    (mainField) => mainField || "id"
  )(modelConfig);

  return mainField;
};
```

Add `"global::fix-search-middleware",` to the end of `/config/middlewares.js`.

**Comment by derrickmehaffy** [comment]
^^ Indeed that is a good temporarily solution until we can get a proper fix implemented.

**Comment by cdreier** [comment]
the workaround above should also work in v5 - but this is only a workaround. this issue should be reopened and the mr from @apfmelo should receive much more love!

https://github.com/strapi/strapi/pull/23276
