### ISSUE TITLE
API Access with assigned pemession

### ISSUE THREAD

**Issue by moayyadfaris** [strapi/strapi#174]
How can i access a model data like car/{id} via API but this model is given a an admin permission?

**Comment by Aurelsicoko** [comment]
Hi @moayyadfaris! You have to go to the administration panel `http://localhost:1337/admin/` then go to the `Users > Permissions` tab and switch the route to `Public` to be available without authentication.

![NPM Example](http://strapi.io/assets/screenshots/permissions.png)

**Comment by moayyadfaris** [comment]
Is their a way to call the api protected by permission by providing the token returned by the login?

**Comment by Aurelsicoko** [comment]
@moayyadfaris Of course, you need to retrieve the JWT on the `POST /auth/local` url, then using the `Bearers` header or add a `token` key in your response body to be allowed to retrieve the data. Do not hesitate to check the [User documentation](http://strapi.io/documentation/users).

@sylvainlap also published an excellent article on this subject ["How to use the Token Authentication with React and Strapi?"](http://sylvainlap.io/token-based-authentication-with-react-and-strapi/).
