### ISSUE TITLE
Unable to reset password in Strapi EE since v4.11.1

### ISSUE THREAD

**Issue by wtchnm** [strapi/strapi#17409]
### Required System information

- Node.js version: v20.4.0
- NPM version: 9.7.2
- Strapi version: 4.11.7
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Unable to reset password in Strapi EE since v4.11.1

### Steps to reproduce the behavior

1. Reset your password in EE edition.
2. See 'An error occurred' after entering the new password.

### Expected behavior

The password is reset.

### Screenshots

![image](https://github.com/strapi/strapi/assets/37726261/e77db661-6f15-4ae9-b3cf-5aa60c81eed8)

### Code snippets

`/reset-password` response:
```json
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "An application error occured",
        "details": {}
    }
}
```

### Additional context

Possible fix: add await to `isSsoLocked`: https://github.com/strapi/strapi/blob/3cab25b585a0ec6d7ebcc222c2ad389b9366789e/packages/core/admin/ee/server/services/auth.js#L62

**Comment by gu-stav** [comment]
PR has been merged. Thanks for opening the issue and the fix!
