### ISSUE TITLE
Error when updating a one to many array

### ISSUE THREAD

**Issue by sdubrez** [strapi/strapi#1740]
**Informations**
- **Node.js version**: 8.11.1
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.13.0.1
- **Database**: MongoDB
- **Operating system**: Win/10

I have a `Room` model with a `clients` field which is a _one to many_ relation with my `Client` model.

**Room.settings.json**
```
{
  "connection": "default",
  "collectionName": "room",
  "info": {
    "name": "room",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "clients": {
      "collection": "client",
      "via": "room"
    }
  }
}
```

**Client.settings.json**
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "client",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "room": {
      "model": "room",
      "via": "clients"
    }
  }
}
```

When I create a `Room`, the `clients` field is an empty array.
I sent a first PUT request which is working (see above)
```
curl -X PUT \
  http://localhost:1338/room/5b6d7d3cbf5fe15298a6dc3b \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 3a17069d-449f-daf8-6be6-39e7318c3487' \
  -d '{
	"clients": [
		"5b6d7d50bf5fe15298a6dc3c"
	]
}'
```

**What is the current behavior?**
It failed for the second PUT request (see above) which is simply adding another client in the `clients` array.
```
curl -X PUT \
  http://localhost:1338/room/5b6d7d3cbf5fe15298a6dc3b \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 3a17069d-449f-daf8-6be6-39e7318c3487' \
  -d '{
	"clients": [
		"5b6d7d50bf5fe15298a6dc3c",
		"5b6d7d54bf5fe15298a6dc3d"
	]
}'
```
Here is the error trace
> TypeError: Cannot read property 'toString' of undefined
> at _.differenceWith (myapp\strapi\node_modules\strapi-hook-mongoose\lib\relations.js:101:36)

**Steps to reproduce the problem**
Create a model with a field that is a _one to many_ relation with another model.
Send two PUT request that should update the field. The first request will work, the second should fail.

**What is the expected behavior?**
It should update the `clients` field and save the new array of `clients`.

**Suggested solutions**
_.differenceWith (myapp\strapi\node_modules\strapi-hook-mongoose\lib\relations.js:101:36)
`a[this.primaryKey].toString() === b[this.primaryKey].toString()`

A `console.log(a,b)` will show that `a` is a string and `b` is an object.

So I'm wondering if in the body of my PUT request, I should send a `Client` object instead of just the `id` of the `Client` object.

**Comment by sdubrez** [comment]
I was doin't it the wrong way. It seems that we can't update the array of relation directly.

Instead, we have to update the linked attribute of each _many_ model. Here we will have to update the `room` attribute of client to remove or add client in a specific `room`.

**Comment by deepjyotipaulhere** [comment]
@imsamdez Hi, can you paste an example how did you solve this?
