### ISSUE TITLE
Unable to load "it" translation for the plugin users-permissions.

### ISSUE THREAD

**Issue by krsnaa** [strapi/strapi#1741]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: mongoDB v4.0.0
- **Operating system**:  macOS High Sierra v10.13.6

**What is the current behavior?**

Navigating to the http://localhost:1337/admin/ page throws a warning in the browser console:

`Unable to load "it" translation for the plugin users-permissions. Please make sure "it.json" file exists in "pluginPath/admin/src/translations" folder.`

**Steps to reproduce the problem**

```
$ strapi new project
$ cd project
$ strapi start
```

**What is the expected behavior?**
Should not throw the warning.

**Suggested solutions**

This problem occurs because `/project/plugins/users-permissions/admin/src/translations/it.json` contains tab characters within the localized strings.  for eg:

`"Auth.form.error.password.local" : "Questo utente non ha mai impostato una password locale,	accedi gentilmente tramite il provider usato durante la creazione dell'account",`

There is a tab character before the words `locale` and `	accedi`.

Replacing the tab characters with spaces will fix the problem.

**Comment by lauriejim** [comment]
Hello @krsnaa , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/pull/1773
