### ISSUE TITLE
CM: Date attribute filter does not work any longer

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#17432]
### Required System information

- Node.js version: not applicable
- NPM version: not applicable
- Strapi version: 4.12
- Database: not applicable
- Operating system: not applicable
- Is your project Javascript or Typescript: JS

### Describe the bug

The date filter in the CM list-view no longer works. When I try to add a filter:

- a native error message is displayed telling me the date does not match the format
- every click on "Add filter" decreases the date by one day

### Steps to reproduce the behavior

1. Go to the CM list-view
2. Click on Filters
3. Select a date-filter (e.g. created at)

### Expected behavior

I expect the filter to be selected and the date not to chage.

### Screenshots

https://github.com/strapi/strapi/assets/2244375/1a837859-1b59-4caf-bbbf-01ba47595e75

**Comment by joshuaellis** [comment]
resolved by strapi/design-system#1241 & strapi/design-system#1266
