### ISSUE TITLE
[bug] Admin UI - Context menu for selecting components inside a zone is not scrollable and overflows the container

### ISSUE THREAD

**Issue by rihards-simanovics** [strapi/strapi#17447]
## Bug report
When a Zone component has too many child components the "add above" and "add below" buttons, accessed via child component meatball menu, are overflowing the container and disappear of the screen (in my case), see screenshot below

### Required System information

- Node.js version: `v18.16.1`
- ~NPM version: `v9.5.1`~
- Yarn version: `v1.22.19`
- Strapi version: `v4.11.3`
- Database: `sqlite`
- Operating system: `Ubuntu Linux WSL`
- Is your project Javascript or Typescript: `JS`

### Steps to reproduce the behavior

1. Create a collection
2. Add a zone component to a collection
3. add some components inside collection
4. save and head to the collection under the content manager
5. create a single item under collection and try adding some blocks/sections/components to the zone
6. now try adding the block/section/component right above or below the already added component

### Expected behavior

A context menu appears and if the number of items is more than the context menu can hold a scroll bar appears

### Screenshots

![image](https://github.com/strapi/strapi/assets/52106095/f57c1f94-cb6f-4567-ac45-21e10653fb59)

### Code snippets

n/a

### Additional context

n/a

**Comment by gu-stav** [comment]
I believe this has been fixed already in https://github.com/strapi/design-system/pull/1157. Related issue https://github.com/strapi/design-system/issues/1142

The first version that contains the fix should be 4.11.4.
