### ISSUE TITLE
[Media Library] Thumbnail image does not reflects immediately

### ISSUE THREAD

**Issue by NileshKale-Globant** [strapi/strapi#17443]
### Required System information

- Strapi version: 4.11.7

### Describe the bug

When user uses the Media Library plugin and uses the Replace Media option, the Thumbnail Image of the new media objects is not updated immediately. To get the latest thumbnail image of the media object user need to refresh the page or second way is visit another plugin/content manager and comeback to Media Library plugin.

### Steps to reproduce the behavior

1. Create the Strapi project using command `npx create-strapi-app@latest my-project --quickstart`
2. Build and Start the Server.
3. Login to the Strapi Application
4. Go to the Media Library Plugin
5. Add new Image **PNG file** asset for the Media Library and click on the **Upload asset to the library** button
6. The new media asset will be shown in plugin
7. Click on the media asset
8. Click on the **Replace Media** Button and select different image **PNG file** to replace. The thumbnail of the latest image which is replaced will be shown in the preview popup 
9. Click on the Finish

Note: For JPEG Image files, it works as expected. Not sure it is issue or expected behaviour.

### Actual behaviour
After user click on the Finish button, the thumbnail image of the media asset does not get changed as per the new Image.

### Expected behaviour
When user click on the Finish the thumbnail image of the media asset should be changed as per the new Image.

### Screenshots
https://github.com/strapi/strapi/assets/89136696/2abe2d01-b2ba-4638-841c-e4bcce68ce3c

### Additional context
Not sure it is issue or expected behaviour.

**Comment by MuzmmilKhan1** [comment]
Can I complete this task?

**Comment by derrickmehaffy** [comment]
> Can you assign this task to me?

No, we don't assign issues to those outside of the company. You can however just submit a PR.

**Comment by derrickmehaffy** [comment]
Need the information about the yarn install error, yarn setup will only work if all of the packages are installed properly.

Do you have node's required build tools?

**Comment by MuzmmilKhan1** [comment]
So This is the Terminal When I run Yarn Install:
<img width="911" alt="Yarn Error" src="https://github.com/strapi/strapi/assets/77438943/ca858e8d-1ba8-4f14-a20b-1dafb6d45707">

**Comment by derrickmehaffy** [comment]
Looks like sqlite failed to build, it mentions the log file for that error can you share that?

Best gue5though ylis you don't have all of the node build tools.

**Comment by derrickmehaffy** [comment]
Ah actually there is a known issue with better-sqlite not handling spaces in folder paths ATM. Can you move the repo to a different folder instead of "Open Source"?

**Comment by MuzmmilKhan1** [comment]
Ok so I changed the folder to Desktop but it still fails to install, Does the Log file mean the text when I do Yarn Install?

**Comment by derrickmehaffy** [comment]
Ah actually there is a known issue with better-sqlite not handling spaces in folder paths ATM. Can you move the repo to a different folder instead of "Open Source"?

The issue you're heading isn't really directly related to us and has to do with the better-sqlite package.

**Comment by derrickmehaffy** [comment]
To be honest I think we already have someone working on this particular issue

**Comment by MuzmmilKhan1** [comment]
It's Ok I can find some other issue. But I was just willing to contribute to Strapi.

**Comment by NileshKale-Globant** [comment]
@derrickmehaffy 
Looks like this issue is fixed in the Strapi version 4.11.7 with Bug Fix section **[core:upload] Update media thumbnails on replace (https://github.com/strapi/strapi/pull/17455) @jhoward1994**.
The [PR](https://github.com/strapi/strapi/pull/17455) is used to apply the fix.

I have tested this bug again with current latest Strapi version 4.12.4 and current issue is no longer able to reproduce.
We can close the current issue.

Thanks...

**Comment by derrickmehaffy** [comment]
Marking as closed, thanks @NileshKale-Globant looks like someone forgot to set this issue in the PR
