### ISSUE TITLE
Media Library adds wrong Authorization header when downloading from S3 bucket

### ISSUE THREAD

**Issue by drubetti** [strapi/strapi#17454]
### Required System information

- Node.js version: 16.20.1
- NPM version: 9.8.1 (using yarn 1.22.19 actually)
- Strapi version: 4.11.7
- Database: MySQL 8
- Operating system: macOS 12 (development), Linux (production)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When downloading an asset uploaded in the Media Library, and the Strapi project is configured to use an S3 bucket (with `@strapi/provider-upload-aws-s3`), a wrong Authorization header is added to the GET request to the S3 bucket. As a result, the download fails.

### Steps to reproduce the behavior

1. Create a new Strapi project (version 4.11.7 at the moment)
2. Configure the upload plugin with the `aws-s3` provider (`@strapi/provider-upload-aws-s3`). I am using the Digital Ocean Spaces service (not AWS), which is compatible with AWS S3;
3. Upload a file in the Media Library;
4. Try to download the uploaded file from the Details dialog. The download will fail (HTTP error `400`).

### Expected behavior

The file should be downloaded.

### Additional context

I think that the problem is [here](https://github.com/strapi/strapi/blob/main/packages/core/upload/admin/src/utils/downloadFile.js). `getFetchClient` returns an instance which adds the Authorization header.  
If I restore a [previous version](https://github.com/strapi/strapi/blob/cf49ddbbfc33fa6a0145f9ddf50677e31c1d711e/packages/core/upload/admin/src/utils/downloadFile.js), then no header is added and the download works fine.
I have already configured my bucket to accept my Strapi origin and the Authorization header in its CORS configuration. In fact, I get a `400` error, not a CORS error.

**Comment by derrickmehaffy** [comment]
It appears this isn't just the media library, we fixed another issue around upload via url but it looks like the useFetchClient is injecting authorization headers where it shouldn't.

https://github.com/strapi/strapi/pull/17459
