### ISSUE TITLE
Admin log-in loop when domain go throgh CloudFront CDN

### ISSUE THREAD

**Issue by XO39** [strapi/strapi#17451]
### Required System information

- Node.js version: 18.17.0
- NPM version: 9.8.1
- Strapi version: 4.11.7
- Database: Postgres
- Operating system: Rocky Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When we make our domain point to CloudFront that proxies requests to our server, we can’t login to admin anymore, one we type email and password, then click the submit button, it first seems like login was successful, then it redirects back to the login page. The only error shown in the console is 401 for the following pages:

- /information
- /permissions
- /me

When we make the domain point directly to our server, we then can log-in with no issues.

In all cases, we use Nginx that pass requests to the actual Strapi server through `proxy_pass`.

### Steps to reproduce the behavior

1. Make the domain point to CDN service (e.g. CloudFront)
2. Make the CDN service points to the actual server that hosts Strapi
3. Go to Admin log-in page
4. Try to log-in
5. See error

### Expected behavior

We expect to be able to log-in regardless of whether the domain goes through proxy or not

### Screenshots
​​
![20230726-161834](https://github.com/strapi/strapi/assets/47403233/f3b60f66-f43c-471e-87a8-76c28403144b)

### Code snippets

It's almost vanilla Strapi, no modification other than than url and database models.

### Additional context

Why would Strapi fail to login in such case?

**Comment by derrickmehaffy** [comment]
It looks like the admin jwt is missing in the request, most likely being stripped by CF since you wouldn't normally cache authenticated requests.

I'm going to set this as a question (which will close it) as it's not really a bug from us.

**Comment by XO39** [comment]
> 
@derrickmehaffy Thanks for your reply.


Is the sent in the header? If so, does it look like this:
```
Authorization: Bearer eyJhbGc...
```

Because this header does exists, so I don't think jwt being stripped?

Anything I can do to make sure of the problem?
