### ISSUE TITLE
Multiple Files Upload One by One

### ISSUE THREAD

**Issue by danielehrhardt** [strapi/strapi#1745]
**Informations**
- **Node.js version**:
v8.11.3
- **npm version**:
6.3.0
- **Strapi version**:
3.0.0-alpha.13.1
- **Database**:
mysql
- **Operating system**:
Windows 10

**What is the current behavior?**
Add Multiple Files to a Media Field one by one only shows one File. So it deletes the Other Files.
If i upload all by one it is working fine. 

**Steps to reproduce the problem**
Add the Media Field and check the Allow multiple files checkbox

**What is the expected behavior?**
Upload File by File should store all Files

**Suggested solutions**

**Comment by soupette** [comment]
Hi @danielehrhardt I unable to reproduce your issue. I'm using Chrome.

**Comment by danielehrhardt** [comment]
@soupette check out https://github.com/strapi/strapi/issues/1770 he created a more detailed ticket

**Comment by ivan-vilches** [comment]
@danielehrhardt  so how you did ? ineed a field for upload multiples images not sure how i can  do that-
Thanks
