### ISSUE TITLE
Permanent API key, for server-to-server communication, manageable 

### ISSUE THREAD

**Issue by juji** [strapi/strapi#1747]
**What is the expected behavior?**

Administrator should be able to create a pair of key-secret, to be used in server-to-server communication with strapi endpoints.

This key-secret pair can have a role assigned to it. So role-base authorization can be enforced.

**Comment by derrickmehaffy** [comment]
Likely related: https://github.com/strapi/strapi/issues/1086

the gist of this being static keys that can be used to access the API similar to most APIs having a generated "key" instead of typical logins correct @juji ?

**Comment by juji** [comment]
@derrickmehaffy correct

**Comment by derrickmehaffy** [comment]
@juji should probably close this issue and summarize your thoughts on the linked issue as to cut down on the number of duplicates.

**Comment by juji** [comment]
Will do

**Comment by shingjin973** [comment]
I have made strapi already, and want to sell my API with api_key.
So if user buy key then allow accessing to my API.
Please help. Regards.

**Comment by lauriejim** [comment]
Hello! I will soon publish a guide for the implementation of this feature.
Stay tuned on Strapi releases.

**Comment by jeremyccrane** [comment]
Hi @lauriejim – Have you been able to implement this feature yet? Our server-server api request is stopping after the jwt token expires (roughly 30 days). Even our attempts to extend the expiration period has not worked.

**Comment by derrickmehaffy** [comment]
> Hi @lauriejim – Have you been able to implement this feature yet? Our server-server api request is stopping after the jwt token expires (roughly 30 days). Even our attempts to extend the expiration period has not worked.

https://strapi.io/documentation/3.0.0-beta.x/guides/api-token.html

**Comment by SuperCipher** [comment]
Hello from the future.
Is there a guide on how to do this yet?
