### ISSUE TITLE
Add the manyWay data type (Alternative to Array for relations)

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1748]
**What is the expected behavior?**

Similar to the `array` data type which stores the data on the model, I am purposing a oneWay relation type that allows the destination model to have multiple entries.

Linking the array discussion issue here just in case: https://github.com/strapi/strapi/issues/761

Currently the oneWay relation works similar to the oneToOne relation in that the "source" model contains a few entries (Say Tags as an example) and doesn't list any entries that use them.

Whereas the "destination" model references these entries, but can only have one "tag" per entry.

What I am purposing is similar to how the array data type is stored, in that the DB will store a json object that references the "source" entries but would allow for multiple "tags". This could be done with a oneToMany where the "tag" model uses an enum data type, but this is quite messy and is not easy to update in production. This also locks these tags to one "destination" model (at least cleanly)

Relations like these are extremely common in the MySQL world to limit the space used and to de-duplicate the data, where instead of saving the same data over and over, we just reference it.

An example of the stored array for a oneWayToMany: `{ 1, 3, 7, 8 }` which strapi would lookup those values and reference them the same way oneToMany works (although in the oTM stores the reference data on the source model, not the destination)

I realize this is not a priority for the Strapi team, but if there is anyone with the required skills or interest in building this that are familiar with both mongoose and bookshelf, I'm offering up the idea. I think once the array data type is added, building this relationship should be fairly easy.

**Comment by Aurelsicoko** [comment]
Yes, we can call this, the `manyWay` relationship 👍

**Comment by ganeshkbhat** [comment]
I am just getting started with strapi and seems like Array data type is missing. what is the recommended way currently to handle array of values in a schema (especially that is coming from a different collection)? This seems like a stopper for me.

**Comment by lauriejim** [comment]
Hello @ganeshkbhat you can use `JSON` type and store an array inside.

**Comment by derrickmehaffy** [comment]
@lauriejim this `manyWay` is another relation type

**Comment by Aurelsicoko** [comment]
Tell me if I'm wrong but maybe the solution to all our problems should be to distinguish between relations and references.

The relations are strict. It means they impact both models. If you can create a relation in one side, you can populate on the other side.

- oneToOne
- oneToMany
- manyToOne
- manyToMany

The references are just links. You link two entity together, there is no strong relation between both. And also, it only affects one model.

- oneWay
- manyWay

**Comment by derrickmehaffy** [comment]
@Aurelsicoko Good point, that lays it out pretty clearly.

**Comment by awitherow** [comment]
I am creating a content type "retreat" that has some attributes like `feature` which I would like to be a sort of array of strings, that would be "single sentence" in length or so, but would not be pre-defined by the backend, rather freestyle entry from my user. Would this use case be of example of this manyWay feature?

**Comment by Aurelsicoko** [comment]
@awitherow We are developing a feature called `Groups and repeatable fields` which will perfectly fit your use case.

See more details here: https://portal.productboard.com/strapi/1-public-roadmap/c/24-group-of-fields-repeatable-or-not

**Comment by alexandrebodin** [comment]
yep

**Comment by awitherow** [comment]
Just an FYI, due to the lack of this simple LOW priority request, I have switched from ever considering `strapi` to using sanity 🤷‍♂.

**Comment by derrickmehaffy** [comment]
@awitherow uhhh you know this feature has already been built and will be in the next release right? Lol

But good luck to you

**Comment by awitherow** [comment]
Yeah, some people don't have a year to wait Lol, but good luck to you too :)
