### ISSUE TITLE
Route list via `strapi.server.listRoutes` is still incomplete after fix

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#17484]
### Required System information

- Node.js version: v20.4.0
- NPM version: v9.7.2
- Strapi version: v4.12.0
- Database: PostgreSQL
- Operating system: MacOS (Intel Chipset)
- Is your project Javascript or Typescript: JS

### Describe the bug

The latest version still seems to include the issue #17396 and #17407. The `strapi.server.listRoutes()` method returns the following contents after installing and re-building the admin panel with version v4.12.0:

```bash
┌─────────┬──────────────────────────────────────────────────────────────────┐
│ (index) │                               path                               │
├─────────┼──────────────────────────────────────────────────────────────────┤
│    0    │ '/_health'                                                       │
│    1    │ '/uploads/(.*)'                                                  │
│    2    │ '/content-manager/collection-types/:model'                       │
│    3    │ '/content-manager/single-types/:model'                           │
│    4    │ '/admin/:path*'                                                  │
│    5    │ '/'                                                              │
│    6    │ '/index.html'                                                    │
│    7    │ '/assets/images/(.*)'                                            │
│    8    │ '/((?!uploads/).+)'                                              │
│    9    │ '/content-manager/single-types/:model/actions/publish'           │
│   10    │ '/content-manager/single-types/:model/actions/unpublish'         │
│   11    │ '/content-manager/collection-types/:model'                       │
│   12    │ '/content-manager/collection-types/:model/:id/actions/publish'   │
│   13    │ '/content-manager/collection-types/:model/:id/actions/unpublish' │
│   14    │ '/content-manager/collection-types/:model/actions/bulkDelete'    │
│   15    │ '/content-manager/single-types/:model'                           │
│   16    │ '/content-manager/collection-types/:model/:id'                   │
│   17    │ '/content-manager/single-types/:model'                           │
│   18    │ '/content-manager/collection-types/:model/:id'                   │
│   19    │ '/graphql'                                                       │
└─────────┴──────────────────────────────────────────────────────────────────┘
```

When running `yarn strapi routes:list` I now receive all routes as desired after the fix, but calling the method programmatically does indeed not reproduce the same results as in previous versions so this still needs to be fixed.

### Steps to reproduce the behavior

1. Add `strapi.server.listRoutes` inside the bootstrap function
2. Log the output
3. Start the server
4. See incomplete route list

### Expected behavior

As seen in previous versions not containing the contents of PR #17290, all routes including custom routes should be returned so plugins like strapi-plugin-rest-cache can access them properly.

### Screenshots

N/A

### Code snippets

```js
async bootstrap({ strapi }) {
  console.table(strapi.server.listRoutes().map((r) => ({ path: r.path })));
}
```

### Additional context

N/A

**Comment by alexandrebodin** [comment]
Hello, as shared in the related PR, this function isn't supposed to be called like that and isn't considered Public API as it only exposes internals. 

If you really want to use non public APIs you can always use the code in your PR to access the list of the routes but this will not make it into strapi at the moment. 

However this brought the need for accessing the non internal list of routes inside Strapi to our attention. Could you explain more precisely your usecase ? FYI the rest-cache plugin is migrating it's code to use the right method to do what they need in the meantime :)

**Comment by fabio-nettis** [comment]
@alexandrebodin Oh, I see. Well if `strapi-plugin-rest-cache` is making the relevant changes themselves I really can't argue with you or the original change at all. Must've misunderstood the requirements then. Cheers 🤘🏻

**Comment by derrickmehaffy** [comment]
> @alexandrebodin Oh, I see. Well if `strapi-plugin-rest-cache` is making the relevant changes themselves I really can't argue with you or the original change at all. Must've misunderstood the requirements then. Cheers 🤘🏻
> 
> PS: The plugin has [already fixed](https://github.com/strapi-community/strapi-plugin-rest-cache/pull/61) their codebase accordingly.

I intend to do more heavy rewrites in the very near future to move away from the custom route construction it currently does and move to inject the route middlewares properly via strapi.api/ect.

I was discussing with @alexandrebodin though of some future potential strapi.routes shortcut and a proper route container.

Not when we will do it but once I rewrite the cache plugin I'll do a bit of a guide or documentation around it.

**Comment by fabio-nettis** [comment]
@derrickmehaffy That is great news. I'd be interested to contribute for the "heavy rewrites", let me know when I can lend a hand.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy That is great news. I'd be interested to contribute for the "heavy rewrites", let me know when I can lend a hand.

Yeah sure, I'm working in a sandbox right now but I can open up a few issues if you'd like to help out I'd greatly appreciate it. If you got some time this weekend poke me and I can show you around what I'm thinking.
