### ISSUE TITLE
Blocked Users Can Still Login via Provider

### ISSUE THREAD

**Issue by dogusdeniz** [strapi/strapi#17494]
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: 4.12.0
- Database: MySql 8.0.31
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When updating a user registered with Google or another provider and setting the "Blocked" value to true on the 'Users' page, the user can still log in using the provider despite being blocked.

### Steps to reproduce the behavior

1. Go to the 'Users' page.
2. Update a user registered with Google (or other provider).
3. Set the 'Blocked' value to true.
4. Save the user.
5. Attempt to log in with the provider using the blocked user's credentials.
6. Notice that the user can still log in despite being blocked.

### Expected behavior

When a user is blocked, they should not be able to log in using any provider.

### Code snippets

https://github.com/strapi/strapi/blob/8aa758396e71ce1d8f8169c132272ffb69877025/packages/plugins/users-permissions/server/controllers/auth.js#L96-L105

### Recommended Solution

The following solution is suggested to fix the issue:

```js
try { 
   const user = await getService('providers').connect(provider, ctx.query); 
  // Fix
   if (user.blocked === true) {
      throw new ApplicationError('Your account is blocked!');
   }
  // Fix End

   return ctx.send({ 
     jwt: getService('jwt').issue({ id: user.id }), 
     user: await sanitizeUser(user, ctx), 
   }); 
 } catch (error) { 
   throw new ApplicationError(error.message); 
 }
```

This fix checks if the user is blocked before allowing the login process to proceed, and if the user is blocked, an error will be thrown, preventing the login with the blocked account.

Please apply this solution to address the bug in the authentication process.

**Comment by dogusdeniz** [comment]
@derrickmehaffy Hi, 

I'm not sure if this is a security issue.

if so i can delete this issue.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Hi,
> 
> I'm not sure this is a security issue.
> 
> if so i can delete this issue.

It's no problem, usually I would say this should have been submitted as an advisory but it's a very limited impact issue as very few users actually use our "blocked" option but it's already been cached by several of the GitHub issue cache sites so deleting it wouldn't really provide much benefit.

It is a bug we do need to resolve though.

**Comment by KushalKanungo** [comment]
Hi @derrickmehaffy , I have did the suggested changes in this PR #17944 , Could you please review it and suggest me any changes required as this is my first RP.

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy , I have done the suggested changes in this PR #17944 , Could you please review it and suggest me any changes required as this is my first PR.

Thanks for the PR and congrats on it being your first, should be released with the next version on Wednesday!
