### ISSUE TITLE
Unique field in a relation component says that its not unique

### ISSUE THREAD

**Issue by IlirEdis** [strapi/strapi#17501]
## Bug report

I have a Single Type component which im using as a relation field in my Collection Types component. Inside the Single Type i have a unique field `Slug`. Now every time i save the Collection type i get an error that the unique fields from the Single type "must be unique (even though they are). See screenshot below:

<img width="1219" alt="Screenshot 2023-07-28 at 17 05 43" src="https://github.com/strapi/strapi/assets/128377763/00e3ad3e-bb9d-42f9-80c9-7224c739a51f">

Then i have to change all the relation fields `Slug` field to some value that i never used before in order it to recognise them as unique.

**Comment by kasonde** [comment]
Hi @IlirEdis I'm setting this as a duplicate/related to #16918
