### ISSUE TITLE
Duplicate Button dont Working

### ISSUE THREAD

**Issue by Marcosul** [strapi/strapi#17506]
## Bug report

Duplicate Button dont Working

### Required System information
- Node.js version: 16.19.0 
- NPM version: 9.8.1
- Strapi version: 4.11.7
- Database: mysql 8
- Operating system: ubuntu 20.04
- Is your project Javascript or Typescript: JS

### Describe the bug

Duplicate Button dont Working

### Steps to reproduce the behavior

Got to list and click duplicate icon

### Expected behavior

Duplicate register

![image](https://github.com/strapi/strapi/assets/4714018/858e2893-e08a-4e5f-ac05-899ec4ab6138)

**Comment by Marc-Roig** [comment]
Hello, are you getting any specific error when clicking the clone button? Or is the button unresponsive?
Could you specify a bit more what is the behaviour? Thank you!

**Comment by nitinmadelyn** [comment]
@Marcosul It might be the case that you have a field with unique value, In that case you will have the edit window to replace the unique field with some new value.

**Comment by Marcosul** [comment]
@Marc-Roig Hello! the button unresponsive!

**Comment by Marc-Roig** [comment]
@Marcosul that's definetly odd!

Could you show or share the `Account` schema? that way I could try to replicate your setup.

The current behaviour should be the one @nitinmadelyn mentions.

**Comment by Marcosul** [comment]
I'm sharing a schema from another simpler collection. Coin Collection.
But the duplicate button is not working in any collection as of the latest versions. I'm not sure, but I think that since version 4.11.3 the duplicate button was no longer working.



{
  "kind": "collectionType",
  "collectionName": "coins",
  "info": {
    "singularName": "coin",
    "pluralName": "coins",
    "displayName": "Coin"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "symbol": {
      "type": "string",
      "required": true,
      "unique": true
    }
  }
}


![image](https://github.com/strapi/strapi/assets/4714018/a9881a36-432f-4cd2-b606-45839437ec2c)

**Comment by jhoward1994** [comment]
Hi, I'm afraid I am unable to replicate this behaviour using the Coin schema you provided. See video below

https://github.com/strapi/strapi/assets/48524071/ddbf09fb-c8e8-4067-8845-405a3dcd4a25

Could you try rebuilding your application following the steps in https://docs.strapi.io/dev-docs/update-version

Failing that if you could provide more details that could help us replicate the issue. Thanks 🙂

**Comment by MuH3gPaB** [comment]
Hi all,
I am not sure if @Marcosul experienced the same issue, but for me duplicate button also doesn't work properly.
The issue occurs when I have horizontal scroll on ListView.

It seems that if I scroll to the right and click `Duplicate` some of event listeners move scroll back to the left before button event listener executed, and it behave as if I click the row, entity is just opened without any clone. 
Post request is not sent to `auto-clone` endpoint.

_Browser: Chrome Version 115.0.5790.170 (Official Build) (arm64)
Node.js version: 16.20.0
NPM version: 8.19.4
Strapi version: 4.12.5
Database: mysql
Operating system: MacOs Ventura 13.4.1 
Is your project Javascript or Typescript: TS_

**Comment by avoytik** [comment]
Hi all,
Regarding duplicate issue: please make sure you don't have axios or have the same axios version in your local. I had the same issue that was related to checking error type on auto-clone request.

Regarding not clickable: it is related to design-system table. There are some problems with tabIndexes in table. After data is loaded all inputs have tabindex="-1" (which are set by hook inside TdCell). Once you click on checkbox table becomes "active" and tabindexes are recalculated and set to 0. After it you can click on buttons. **This is happening when you have horizontal scroll in the table.**.

**Comment by MuH3gPaB** [comment]
@jhoward1994 could you fix an issue with horizontal scroll?
Thanks!
