### ISSUE TITLE
Problem resizing content type fields if set to 100% and want to change

### ISSUE THREAD

**Issue by TheDigitalGuru** [strapi/strapi#17518]
- Node.js version: 18
- NPM version: .39.4
- Strapi version: 4.12
- Database: 
- Operating system:
- My project is in Javascript

### Describe the bug

when I edit my content type view - if I set the view to 100%, I can no longer adjust this sizing - I would like to change it from 100% but it refuses to allow this opportunity now that it is set at 100%

### Steps to reproduce the behavior

1. Go to 'content-types'
2. Click on 'configure the view'
3. Set field to 100%
4. Try to resize the field 
5. Now it won't let you

### Expected behavior

I thought I'd be able to adjust the view of the field

**Comment by gu-stav** [comment]
Unfortunately I am not able to reproduce this issue on the latest version. Does this only happen for certain field-types to you? Would it be possible to add a video showing what exactly happens?
