### ISSUE TITLE
Bug in relations search dropdown with "contains" and "start with" filtering

### ISSUE THREAD

**Issue by alexiolan** [strapi/strapi#17521]
### Required System information

- Node.js version: 16.18.1
- NPM version: 8.19.2
- Strapi version: 4.12.0
- Database: "pg": "^8.11.1"
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When we write keyword in relations search, by database is used "contains" approach, but results are filtered by "start with" approach.

### Steps to reproduce the behavior

*Assuming that we have list of items with next titles 
- my.test
- my.test2
- game.test
- work.test
- test.info
- test2.info

1. Go to "Content Manager"
2. Found collection with relation one-to-many
3. Try to search item in "Add relation" dropdown using work "test"
4. Check network, results property in request shows all items which contains word "test", but dropdown shows only last two items which starts with word "test"

### Expected behavior

Expected to see in dropdown all items with "test" word, or only items which starts with "test" word

### Screenshots

<img width="641" alt="Screenshot 2023-08-01 at 12 09 07" src="https://github.com/strapi/strapi/assets/12134913/87fa3ba4-fe3e-40f8-977a-97ecaec815ab">
<img width="967" alt="Screenshot 2023-08-01 at 12 09 15" src="https://github.com/strapi/strapi/assets/12134913/c2aa8fa7-13ba-4768-812b-8f4109e1c3cd">

**Comment by derrickmehaffy** [comment]
Closing this in favor of https://github.com/strapi/strapi/issues/17391
