### ISSUE TITLE
Entries in "Content Available in" Column are empty after update

### ISSUE THREAD

**Issue by schlotterich** [strapi/strapi#17523]
### Required System information

- Node.js version: v16.20.1
- Strapi version: v4.12.0
- Database: Postgres
- Operating system: Debian 11
- NPM Version: 8.19.4
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After the update to the latest strapi version v4.12.0 I do not see the entries in the collection type overview column: "CONTENT AVAILABLE IN" anymore. The Translations still work, but the entries in the overview are gone.

In my local environment with the same strapi version but a different node version the fields are still visible.

### Steps to reproduce the behavior

1. Update to Strapi 4.12.0
2. Go to any Collection Type in the Content Type that has Internationalizion activated
3. The entries in the "CONTENT AVAILALABLE IN" are empty

### Screenshots

Production:
<img width="788" alt="image" src="https://github.com/strapi/strapi/assets/13986509/1f1d317e-53af-4e3b-bf92-fd0ca729927c">

Dev (Local):
<img width="662" alt="image" src="https://github.com/strapi/strapi/assets/13986509/434f2ace-e1ff-4540-add2-c11f774511c5">

**Comment by gu-stav** [comment]
This should be fixed in the upcoming 4.12.2 release by https://github.com/strapi/strapi/pull/17590.
