### ISSUE TITLE
Datetimepicker date

### ISSUE THREAD

**Issue by Martijn-Schoenmaker-Webbio** [strapi/strapi#17538]
### Required System information

- Node.js version: 18.21.1
- NPM version: 8.19.2
- Strapi version: 4.12.0
- Database: sqlite
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When using the datetimepicker as a field or as a component within a plugin, the date will roll back one day as you open and close the picker.

### Steps to reproduce the behavior

1. Add a datetimepicker to a content type
2. Select a date and close the datetimepicker.
3. The date will roll back one day every time you open and close the datetimepicker.

### Expected behavior

The date should stay the same value as selected.

### Screenshots

https://share.getcloudapp.com/5zuOvq5D

### Additional context

When setting the time to the offset of your timezone (in my case +2), the date will stay the same. It seems to have something to do with

**Comment by erinnovations** [comment]
Same here.

Also the shown date and the date in the URL is mismatching.
![Képernyőkép 2023-08-02 105705](https://github.com/strapi/strapi/assets/253455/cea5a432-0f10-483d-90e5-e4998d82bded)

**Comment by marob** [comment]
> Same here.
> 
> Also the shown date and the date in the URL is mismatching. ![Képernyőkép 2023-08-02 105705](https://user-images.githubusercontent.com/253455/257759383-cea5a432-0f10-483d-90e5-e4998d82bded.png)

I don't think this is the same issue (nor if it is an issue at all).
22:00:00.000Z is 10PM in UTC. It's the same as 12AM (+1day) in UTC+2.

Note that the original issue (about day changing when clicking in datetime picker) is solved here: https://github.com/strapi/design-system/pull/1241

**Comment by derrickmehaffy** [comment]
duplicate https://github.com/strapi/strapi/issues/17348
