### ISSUE TITLE
services undefined

### ISSUE THREAD

**Issue by reutopiaer** [strapi/strapi#1754]
**Informations**
- **Node.js version**:v9.11.1
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.13.1
- **Database**:mysql
- **Operating system**:windows

**What is the current behavior?**
```
debug GET \video\count (17 ms)
TypeError: Video.count(...).where is not a function
    at Object.count (\api\video\services\Video.js:68:8)
    at count (api\video\controllers\Video.js:46:34)
```

**Steps to reproduce the problem**
1. generate:api
```
strapi generate:api video filename:string hash:string
```
2.  http://localhost:1337/video/count
{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}

**What is the expected behavior?**

get count of videos.
**Suggested solutions**

use mongo is ok

**Comment by derrickmehaffy** [comment]
@reutopiaer this one threw me through a loop also. It seems the `strapi generate:api` command defaults to mongo (thus mongoose).

You need to define the hook you want to use so in your case:

```
strapi generate:api -t bookshelf video filename:string hash:string
```

You can find the, very well hidden, part of the docs on this here: https://strapi.io/documentation/cli/CLI.html#strapi-generateapi

Specifically this part:

> strapi generate:api <name> --tpl <template>
> Generates an API called <name> in the ./api folder which works with the given <template>. By default, the generated APIs are based on Mongoose.
> 
> Example: strapi generate:api product --tpl bookshelf

**Comment by derrickmehaffy** [comment]
@Aurelsicoko @lauriejim I think this command should instead use the default database type instead of just defaulting to mongo :stuck_out_tongue: 

Should pull from the development environment `database.json`

**Comment by reutopiaer** [comment]
@derrickmehaffy 'strapi generate:api -t bookshelf' works  
Thank you very much!
ps: Strapi is awesome! You did a god job!

**Comment by maturano** [comment]
I would suggest keep the issue open (or open a new one). Add the `-t` parameter sounds like a workaround. I think should be optional and this is a real bug; isn't?

**Comment by derrickmehaffy** [comment]
@maturano yeah me personally I don't think the CLI should preference a backend hook by default and should use the one defined as your primary DB in your database.json file the -t (or --tpl) is what defines the hook.
