### ISSUE TITLE
I cannot create new entries for collections

### ISSUE THREAD

**Issue by alexandrepaiva-dev** [strapi/strapi#17553]
### Required System information

- Node.js version: Node.js v16.18.0
- Yarn version: 1.22.19
- Strapi version: 4.12.0
- Database: Postgres
- Operating system:
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Hey guys!

These days I started getting an error when I try to add new entries to the collections (any collection). The console log displays the message:

main.319d3d93.js:31 ReferenceError: step is not defined
    at fo (content-manager.ce66d755.chunk.js:823:6117)
    at wl (main.319d3d93.js:29:20862)
    at Od (main.319d3d93.js:31:46450)
    at Qf (main.319d3d93.js:31:41974)
    at dg (main.319d3d93.js:31:41902)
    at Of (main.319d3d93.js:31:41752)
    at Gf (main.319d3d93.js:31:37916)
    at bf (main.319d3d93.js:31:36806)
    at A (main.319d3d93.js:55:1602)
    at MessagePort.de (main.319d3d93.js:55:1974)

I'm not sure why that happend nor how to fix it. The Strapi version (the latest one, 4.12.0) was working before. It just suddenly stopped working.

Can anyone spot the issue?

Thanks!

### Steps to reproduce the behavior

- When I try to add a new entry to a collection (any collection I have that happens)

### Screenshots

![Screenshot 2023-08-02 181931](https://github.com/strapi/strapi/assets/12596316/2c4557c0-8e91-4823-8b19-74f6fcb9c38b)
![Screenshot 2023-08-02 181831](https://github.com/strapi/strapi/assets/12596316/acdbc0e7-d0fb-491c-afc4-26ca95facb61)

**Comment by derrickmehaffy** [comment]
Can you please provide a copy of your package.json and also could you try removing any of the community plugins you are using? Specifically the import/export plugin as there are known issues with that.

**Comment by alexandrepaiva-dev** [comment]
> Can you please provide a copy of your package.json and also could you try removing any of the community plugins you are using? Specifically the import/export plugin as there are known issues with that.

Hey @derrickmehaffy thanks for you message! 

I've done it but actually no success. 

It's werd that it was working before and I didn't install any new plugin or updated Strapi version, also locally on development mode it doesn't happen.

Follow my package.json and plugins config:

```
{
  "name": "api-xraves",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application for Xraves API",
  "scripts": {
    "develop": "yarn prebuild && strapi develop",
    "develop-watch-admin": "yarn develop --watch-admin",
    "start": "yarn prebuild && strapi start",
    "build": "yarn prebuild && strapi build",
    "generate-plugin": "yarn strapi generate plugin",
    "strapi": "strapi",
    "prebuild": "node ./.scripts/index.js"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.12.0",
    "@strapi/plugin-users-permissions": "4.12.0",
    "@strapi/provider-email-amazon-ses": "4.12.0",
    "@strapi/provider-upload-aws-s3": "4.12.0",
    "@strapi/strapi": "4.12.0",
    "@strapi/utils": "4.12.0",
    "nodemailer": "6.7.8",
    "pg": "8.8.0",
    "reach": "1.0.1",
    "react-cool-onclickoutside": "1.7.0",
    "react-datetime-picker": "3.5.0",
    "react-google-maps": "9.4.5",
    "sharp": "^0.32.1",
    "slugify": "1.6.5",
    "strapi-plugin-config-sync": "1.0.4",
    "strapi-plugin-cookie-manager": "^1.1.3",
    "strapi-plugin-email-designer": "2.1.1",
    "strapi-plugin-entity-relationship-chart": "4.1.0",
    "strapi-plugin-import-export-entries": "1.14.1",
    "strapi-plugin-notes": "1.0.1",
    "strapi-plugin-placeholder": "4.3.6",
    "strapi-plugin-publisher": "1.1.3",
    "stripe": "^11.13.0",
    "use-places-autocomplete": "4.0.0"
  },
  "author": {
    "name": "Xraves - Alexandre Paiva"
  },
  "strapi": {
    "uuid": "2c439f35-2e97-487c-85a6-f2e2f3709097",
    "telemetryDisabled": true
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```


```
module.exports = ({ env }) => ({
	email: {
		config: {
			provider: 'amazon-ses',
			providerOptions: {
				key: env('AWS_SES_KEY'),
				secret: env('AWS_SES_SECRET'),
				amazon: env('AWS_SES_REGION'),
			},
			settings: {
				defaultFrom: env('EMAIL_ADDRESS_FROM'),
				defaultReplyTo: env('EMAIL_ADDRESS_FROM'),
			},
		},
	},
	'import-export-entries': {
		enabled: false,
	},
	'entity-notes': {
		enabled: true,
	},
	'publisher': {
		enabled: true,
	},
	/* 'encryptable-field': {
		enabled: true,
	}, */
	'koeaboa-custom-fields': {
		enabled: true,
		resolve: './src/plugins/koeaboa-fields'
	},
	'placeholder': {
		enabled: true,
		config: {
			size: 10,
		},
	},
	'upload': {
		config: {
			provider: 'aws-s3',
			providerOptions: {
				accessKeyId: env('STORAGE_ACCESS_KEY_ID'),
				secretAccessKey: env('STORAGE_ACCESS_SECRET'),
				s3ForcePathStyle: true, // needed for minio or other s3 compatible services
				endpoint: env('STORAGE_ENDPOINT'),
				params: {
					Bucket: env('STORAGE_BUCKET'),
				},
				baseUrl: env('STORAGE_BUCKET_BASE_URL'),
			},
			upload: {
				ACL: null
			},
			uploadStream: {
				ACL: null
			},
		},
	},
	'email-designer': {
		enabled: true,

		// ⬇︎ Add the config property
		config: {
			editor: {
				// optional - if you have a premium unlayer account
				//projectId: [UNLAYER_PROJECT_ID],

				tools: {
					// heading: {
					// 	properties: {
					// 		text: {
					// 			value: 'This is the new default text!',
					// 		},
					// 	},
					// },
				},
				options: {
					// features: {
					// 	colorPicker: {
					// 		presets: ['#D9E3F0', '#F47373', '#697689', '#37D67A'],
					// 	},
					// },
					fonts: {
						showDefaultFonts: false,
						/*
						 * If you want use a custom font you need a premium unlayer account and pass a projectId number :-(
						 */
						customFonts: [
							{
								label: 'Lato',
								value: "'Lato', Tahoma, Verdana, sans-serif",
								url: 'https://fonts.googleapis.com/css?family=Lato',
							},
							// ...
						],
					},
					mergeTags: [
						{
							name: 'Email',
							value: '{{= USER.username }}',
							sample: 'john@doe.com',
							urlfront: env('FRONTEND_URL'),
						},
						// ...
					],
				},
				appearance: {
					theme: 'dark',
					panels: {
						tools: {
							dock: 'left',
						},
					},
				},
			},
		},
	},
});
```

**Comment by alexandrepaiva-dev** [comment]
Hey @derrickmehaffy , any idea on how to fix that? I've reverted all the last few updates I've made last days but no success. Could it be an issue with the database maybe? I just don't know where to go for fixing that.
