### ISSUE TITLE
Email id validation on signup

### ISSUE THREAD

**Issue by zeroby0** [strapi/strapi#1756]
**What is the expected behavior?**
Allow signups only from emails that match a format. This can be used to restrict signups to users from my organisation, etc.

This can probably be done my changing the model & controller, but an option in the GUI would be very helpful.

**Comment by MartinMuzatko** [comment]
Also, avoid users signing up from `mail@gmail.com` and `mail@googlemail.com`
Any way to hook into the plugin and change that behavior?

**Comment by derrickmehaffy** [comment]
AFAIK there is no current way to do this as there is no real "validation" layer on anything. But I do think something like this is planned

**Comment by derrickmehaffy** [comment]
> Framework - Validations
> Make a better integration of Joi to validate the upcoming request parameters and add a strong validation layer into Strapi.

https://strapi.io/vote

**Comment by lauriejim** [comment]
Hello @zeroby0. Thank you for reporting this feature request.
Actually you can custom the register function and add you validation.
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L266

**Comment by zeroby0** [comment]
Thanks @lauriejim :)
Should I keep the issue open so you can track feature requests, or shall I close it?

**Comment by lauriejim** [comment]
Let it open

**Comment by Aurelsicoko** [comment]
I'm closing this issue to keep the repository as clear as possible. We have a public roadmap available on Product Board, and there is a feature called "validations" that matches perfectly with this feature request (see https://portal.productboard.com/strapi/c/14-validations).

**Comment by IvanAdmaers** [comment]
All the links here are 404. Good job, Strapi team 👍
