### ISSUE TITLE
CellFormatter not support plugins again in 4.12.x

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#17568]
### Required System information

- Node.js version: 18.7.0
- NPM version: 9.6.7
- Strapi version: 4.12.0-4.12.1
- Database: PostgreSQL 
- Operating system: macOS/Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

CellFormatter not support plugins again in 4.12.x

### Steps to reproduce the behavior

1. Create a content-type with i18n support
2. Click on list view
3. See error

### Expected behavior

CellFormatter support plugins again in 4.12.x

### Screenshots

![](https://user-images.githubusercontent.com/22420/257692538-a9ef32da-5760-46c8-92e8-dc4ccebbae97.png)

### Additional context

Looks ListView component does not use TableRows component anymore.

**Comment by gu-stav** [comment]
Fixed in https://github.com/strapi/strapi/pull/17590
