### ISSUE TITLE
User: Display field for role not working (always set to ID)

### ISSUE THREAD

**Issue by biancajs** [strapi/strapi#17561]
- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: v4.12.1
- Database: mysql
- Operating system: macOS
- Is your project Javascript or Typescript: js

### Describe the bug

There might be a minor bug: when creating a new user the related role fields only shows the IDs as a dropdown list (the display field is explicitly set to "name"). That's a bit confusing for content editors.

### Steps to reproduce the behavior
1. Go to: Content Manger -> User
2. Click on: Create new Entry (or open an existing one)
3. Instead of the name ("authenticated", "public", etc.) the ID is referenced
4. (Check if: Content Type Builder -> User -> Configure the view -> Role: is set to "name")

### Expected behavior

Instead of the ID the name of the role should be shown ("authenticated" etc.)

### Screenshots
![user-role](https://github.com/strapi/strapi/assets/24716157/c4343f81-71f5-4556-af66-5f3e2e64b8ea)

![role-view](https://github.com/strapi/strapi/assets/24716157/851365bb-8f12-4325-b4eb-8be9f4994a6a)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by bglidwell** [comment]
Actually unable to change roles for existing users as well. Getting internal server error. Downgrading version restores functionality, so it seems to be with this update. 

023-08-03T17:49:50.034819+00:00 app[web.1]: [2023-08-03 17:49:50.034] error: UPDATE "strapiv4"."up_users_role_links" as a
2023-08-03T17:49:50.034821+00:00 app[web.1]: SET "user_order" = b.inv_order
2023-08-03T17:49:50.034821+00:00 app[web.1]: FROM ( select "id", row_number() over (partition by "role_id" order by "user_order") as inv_order from "up_users_role_links" where "role_id" in ($1) ) AS b
2023-08-03T17:49:50.034822+00:00 app[web.1]: WHERE b.id = a.id - relation "up_users_role_links" does not exist
2023-08-03T17:49:50.034826+00:00 app[web.1]: error: UPDATE "strapiv4"."up_users_role_links" as a
2023-08-03T17:49:50.034826+00:00 app[web.1]: SET "user_order" = b.inv_order
2023-08-03T17:49:50.034827+00:00 app[web.1]: FROM ( select "id", row_number() over (partition by "role_id" order by "user_order") as inv_order from "up_users_role_links" where "role_id" in ($1) ) AS b
2023-08-03T17:49:50.034827+00:00 app[web.1]: WHERE b.id = a.id - relation "up_users_role_links" does not exist

**Comment by derrickmehaffy** [comment]
I believe this was related to a security fix that we implemented recently where it will block certain fields if they don't have the permission to view them but that shouldn't impact some of the admin content-types :thinking: 

Thoughts @alexandrebodin / @Convly / @innerdvations ?

**Comment by vagelisp** [comment]
Hello all, 
I have the same issue with an admin::user relation field that could be related to this.

```
"admin_users": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "admin::user"
    }
```
    
It will always display the ID no matter what I set it to display.

**Comment by McSego1990** [comment]
same here to :)

**Comment by delta-source** [comment]
same issue for me

**Comment by innerdvations** [comment]
> I believe this was related to a security fix that we implemented recently where it will block certain fields if they don't have the permission to view them but that shouldn't impact some of the admin content-types 🤔
> 
> Thoughts @alexandrebodin / @Convly / @innerdvations ?

Yeah, that sounds right, it was just changed so that if a user doesn't have permissions on a relation they can only select the id. We may need to add an exception for role name if it needs to be visible to users without role read permissions.

**Comment by innerdvations** [comment]
@derrickmehaffy I've confirmed this is actually a bug with the permissions check, it's not an issue with users needing to set additional permissions

**Comment by bglidwell** [comment]
If it helps, the database error only seems to be happening on Postgres. Our local with SQLite is fine. Will look into it more this week to get a better root cause.

**Comment by Badestrand** [comment]
> This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:
> 
> https://forum.strapi.io/t/user-roles-broke-from-upgrade/30939/3

This was me but I don't have more details.

One of the latest update broke my production, temporarily fixed it by reverting to an older Strapi version. And the problem appears to a brand new Strapi installation with SQLite as well. Waiting for the fix now :)

**Comment by derrickmehaffy** [comment]
We know roughly where the issue is and the cause but can't speak to detail on it as it was part of a security fix that isn't disclosed yet (disclosure will happen on the 30th).

Patch should be coming soon.

**Comment by adwinang** [comment]
> If it helps, the database error only seems to be happening on Postgres. Our local with SQLite is fine. Will look into it more this week to get a better root cause. 

I am encountering this problem even with SQLite on local

**Comment by adwinang** [comment]
What would be the latest version where the bug doesn't happen? As we will be launching for production use soon

**Comment by vagelisp** [comment]
@adwinang 4.12.0 seems to be working fine here

**Comment by adwinang** [comment]
@vagelisp that works, thank you!

**Comment by marmotz** [comment]
@adwinang it's always buggy here on 4.12.4 :-/

**Comment by derrickmehaffy** [comment]
Sev raised from high to critical as the issue impacts an EE customer. Internal TID3949

**Comment by matepaiva** [comment]
meanwhile you can workaround this bug by extending the "up_roles" content-type and changing the `pluginOptions.content-manager.visible` to `true`. 

To do that, create a json file like below  at `extensions/users-permissions/content-types/role/schema.json`:

```
{
  "collectionName": "up_roles",
  "info": {
    "name": "role",
    "description": "",
    "singularName": "role",
    "pluralName": "roles",
    "displayName": "Role"
  },
  "pluginOptions": {
    "content-manager": {
      "visible": true
    },
    "content-type-builder": {
      "visible": true
    }
  },
  "attributes": {
    "name": {
      "type": "string",
      "minLength": 3,
      "required": true,
      "configurable": false
    },
    "description": {
      "type": "string",
      "configurable": false
    },
    "type": {
      "type": "string",
      "unique": true,
      "configurable": false
    },
    "permissions": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "plugin::users-permissions.permission",
      "mappedBy": "role",
      "configurable": false
    },
    "users": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "plugin::users-permissions.user",
      "mappedBy": "role",
      "configurable": false
    }
  }
}
```

**Comment by kareraisu** [comment]
Hello! Thanks to the reporter and to the devs for all the hard work.
I am experiencing this as well in v4.15.5.
Cheers!

**Comment by Convly** [comment]
Hi @kareraisu, would you mind opening a new issue with a clear description of your issue?

That would help narrow down what's causing the issue in your particular context as well as allow us to track this potential regression better.

Thanks a lot!

(don't hesitate to reference this issue as the initial one)

**Comment by AO-IO** [comment]
Still exists on strapi v4.20.0 🫤
