### ISSUE TITLE
Title: Media Library List View Not Responding to Clicks in Strapi v4.12.1

### ISSUE THREAD

**Issue by slav-weber** [strapi/strapi#17567]
**Required System information**
Node.js version: 18.16
NPM version: 9.5.1
Strapi version: 4.12.1
Database: PostgreSQL 8.11.2
Operating system: Windows 11 x64
Is your project Javascript or Typescript: Typescript

**Describe the bug**
In the Strapi admin panel, the Media Library List View is not responding to clicks. This issue does not occur in Grid View. The folders and images appear visually correct, but they do not respond to user interaction in List View.

**Steps to reproduce the behavior**
Navigate to the Media Library in the Strapi admin panel.
Switch to List View.
Try to click on a folder or image.

**Expected behavior**
The clicked folder or image should open or be selected.

**Additional context**
Upon inspecting the network requests made when attempting to use Grid View and List View, the following differences were found:

**Grid View:**
```
GET /upload/files?page=1&sort=createdAt:DESC&pageSize=100&filters[$and][0][folderPath][$eq]=/3&folder=11
GET /upload/folders?page=1&sort=createdAt:DESC&pageSize=100&filters[$and][0][parent][id]=11&folderPath=/3&pagination[pageSize]=-1
GET /upload/folders/11?populate[parent][populate][parent]=*
```

**List View:**
```
GET /upload/files?page=1&sort=createdAt:DESC&pageSize=100&filters[$and][0][folderPath][$eq]=/&folder=11
GET /upload/folders?page=1&sort=createdAt:DESC&pageSize=100&filters[$and][0][parent][id]=11&pagination[pageSize]=-1
GET /upload/folders/11?populate[parent][populate][parent]=*
```

The main difference is in the folderPath parameter in the first two requests. In Grid View, the folderPath is set to /3, while in List View, it is set to /.

Currently, the only workaround is to use Grid View instead of List View.

**Comment by MrTheFirst** [comment]
After updating to 4.12.1, the admin panel broke: Content-Type Builder, Documentation, Plugins.
![2023-08-04_08-52-38](https://github.com/strapi/strapi/assets/4955590/dbe24c0f-391d-496e-a24b-6ed12279fe8b)

I cleaned the folders build and .cache, rebuilt the project several times, the error remained.

**Comment by noobCode-69** [comment]
Hey @slav-weber the issue of not being able to click on folder links is related to these two issues `Folder Links Not Clickable In List View #17564` and `Media Library List View navigation issues #17560` , I have made a PR for this , that will fix this problem

**Comment by slav-weber** [comment]
@noobCode-69 Thank you for information
