### ISSUE TITLE
Process fails when importing data using strapi import

### ISSUE THREAD

**Issue by david-vaclavek** [strapi/strapi#17578]
### Required System information

- Node.js version: 18.4.0
- NPM version: 8.12.1
- Strapi version: 4.11.1
- Database: SQLite
- Operating system: macOS Ventura 13.5 (22G74)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I experience an issue while importing exported data from the project into my local copy.
I ensured that both instances run the same versions of Strapi.

### Steps to reproduce the behavior

There are two scenarios I tried:
A.
1. `npx strapi import -f ./__import/import.tar`
2. Warning is shown
```bash
(node:54964) Warning: Error on attribute "thisArticleInOtherArticles" in model "other-article" (api::other-article.other-article). Please modify your other-article schema by renaming the key "inversedBy" to "mappedBy". Ex: { "inversedBy": "otherArticles" } -> { "mappedBy": "otherArticles" }
```
4. `Are you sure you want to continue? Yes`
5. See the process failed.
<img width="660" alt="image" src="https://github.com/strapi/strapi/assets/49518842/ca99c215-1cdc-4cf2-bf69-b871c87453a0">

---
B.
1. Based on the advice provided in A.2., I changed the `schema.json`.
1.1. Before:
<img width="390" alt="image" src="https://github.com/strapi/strapi/assets/49518842/54f2f15a-0468-4070-85d4-69cdbfdca4d8">

1.2. After:
<img width="400" alt="image" src="https://github.com/strapi/strapi/assets/49518842/05c49f73-4fc4-40f0-99d2-f0eaf83121cd">

2. `npx strapi import -f ./__import/import.tar`

3. A warning is shown:
<img width="671" alt="image" src="https://github.com/strapi/strapi/assets/49518842/dd302094-df7f-4998-9785-57ca450a3bfa">

4. `Are you sure you want to continue? Yes`

5. See the process failed.
<img width="669" alt="image" src="https://github.com/strapi/strapi/assets/49518842/cd02dd11-4541-4aaa-9fd2-2fcf96f8905d">

### Expected behavior

I expect the data to be imported and present in the Strapi instance.

### Additional context

I'd like to debug the [Localazy Strapi Plugin](https://market.strapi.io/plugins/@localazy-strapi-plugin) locally on the imported data.

**Comment by derrickmehaffy** [comment]
Please upgrade to v4.12.1 as we have fixed several bug with DTS

Closing for now, if the issue still happens in 4.12.1 comment back and we can reopen.

**Comment by david-vaclavek** [comment]
Hello.

I upgraded Strapi to v4.12.1 and still encounter the very same issue.

**Comment by derrickmehaffy** [comment]
Confirmed via multiple users and @LB22 via Discord

**Comment by shapeshifta78** [comment]
I have a similar issue with strapi transfer:
`? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
Starting transfer...
✔ entities: 302 transfered (size: 186.2 KB) (elapsed: 379 ms) 
✔ assets: 0 transfered (size: 0) (elapsed: 0 ms) 
✖ links: 64 transfered (size: 12.4 KB) (elapsed: 5 ms) 
[2023-10-18 11:04:47.225] error: [ERROR] insert into `components_layout_pd_destinations_links` (`pd_id`, `populardestination_id`, `populardestination_order`) values (1, 131, 9) - FOREIGN KEY constraint failed
Transfer process failed.
`

**Comment by crispyyv** [comment]
Have the same error when run strapi import/ strapi transfer

Node.js version: 18.1.0
NPM version: 8.8.0
Strapi version: 4.14.6
Database: Postgres
Operating system: Ubuntu 22.04.3 LTS
Is your project Javascript or Typescript: Typescript

<img width="1968" alt="image" src="https://github.com/strapi/strapi/assets/44894965/678de099-fb27-4cb1-978a-a6a75d59b4c2">

**Comment by chrisli-sas** [comment]
same error on 4.15.4, any updates on this?

**Comment by Tjerk-Haaye-Henricus** [comment]
Same here.

**Comment by othecos** [comment]
Any update on this? Facing the same issue as well

**Comment by schliesser** [comment]
Same here

Node.js version: 18.18.0
NPM version: 10.2.0
Strapi version: 4.16.0
Database: Sqlite
Operating system: MacOS 14.2.1
Is your project Javascript or Typescript: Javascript

```
? The import will delete your existing data! Are you sure you want to proceed? Yes
Starting import...
✔ entities: 21 transfered (size: 6.3 KB) (elapsed: 36 ms) 
✔ assets: 3 transfered (size: 362.9 KB) (elapsed: 10 ms) 
⠋ links: 0 transfered (size: 0) (elapsed: 0 ms) [2023-12-21 08:06:58.188] error: [ERROR] insert into `components_elements_pricing_cards_services_links` (`pricing_card_id`, `service_id`, `service_order`) values (1, 7, 1) - FOREIGN KEY constraint failed
Import process failed.
```

Only did the stuff of the video tutorial:
https://www.youtube.com/watch?v=RceLeh9D85o&t=155s
