### ISSUE TITLE
Strapi Export/Transfer when using a private upload provider will fail to fetch files and stall

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#17571]
### Required System information

- Node.js version: 18
- NPM version: 8
- Strapi version: 4.12.1
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When an upload provider that uses some kind of private access to the files is used the Strapi export command will fail with a 4xx error (depends on configuration) but generally a 400, 401, or 403.

### Steps to reproduce the behavior

1. Install the `@strapi/provider-upload-aws-s3` provider
2. Configure it for private signed urls (sample config below)
3. Setup or use an example S3 private bucket (for Strapi team members see 1password for a private testing S3 bucket)
4. Upload a file
5. Try to run a strapi export ex: `yarn strapi export --no-encrypt --no-compress -f testPrivate`
6. See error

### Expected behavior

File export should work properly regardless of the provider configs if the admin is able to fetch the file, we may need to add an option or default to fetching the files proxied through the Strapi instance or adding a `get()` function to the providers to enable secure downloads.

### Screenshots

![image](https://github.com/strapi/strapi/assets/8593673/0b950cda-e33b-4d3e-a74d-92de8b4ac931)

### Code snippets

Sample config for private S3 bucket:

```js
module.exports = ({ env }) => ({
  // ...
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          ACL: "private", // <== set ACL to private
          signedUrlExpires: env("AWS_SIGNED_URL_EXPIRES", 15 * 60),
          Bucket: env("AWS_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
  // ...
});
```

### Additional context

Related to two EE tickets:
- TID4484
- TID4490

**Comment by christiancp100** [comment]
The error is here: https://github.com/strapi/strapi/blob/3b504a5284f4e0eeaec73af89fc7c1604a953214/packages/core/data-transfer/src/strapi/providers/local-source/assets.ts#L75 when we are doing HTTP requests to get the image metadata and the image stream using the HTTP library. We should try to find a way to use the strapi uploads provider instead of the HTTP library. In order to do that, it would be necessary to implement a method to get the image object from AWS S3. Something like:
```typescript
// packages/providers/upload-aws-s3/src/index.ts
get(url: string) {
        const extractS3KeyFromUrl = (url: string) => {
          const urlObj = new URL(url);
          const parts = urlObj.pathname.split('/');

          // The key is usually after the bucket name in the URL
          const key = parts.slice(1).join('/'); // Skip the first two parts (empty and bucket name)

          return key;
        };
        const fileKey = extractS3KeyFromUrl(url);
        const params = { Bucket: config.params.Bucket, Key: fileKey };

        return new Promise((resolve, reject) => {
          S3.getObject(params, (err, data) => {
            if (err) {
              reject(new Error(`Error fetching data ${err}`));
            }
            resolve(data);
          });
        });
      },
    };
``` 

And then, just use it in `packages/core/data-transfer/src/strapi/providers/local-source/assets.ts` updating these methods:
```typescript
async function getFileStats(
  filepath: string,
  provider: any,
  isLocal = false
): Promise<{ size: number }> {
  if (isLocal) {
    return stat(filepath);
  }
  const file = await provider.get(filepath);
  return {
    size: file.ContentLength ? parseInt(file.ContentLength, 10) : 0,
  };
}

async function getFileStream(filepath: string, provider: any, isLocal = false): Promise<Readable> {
  if (isLocal) {
    return createReadStream(filepath);
  }

  const readableStream = new PassThrough();

  const file = await provider.get(filepath);

  return Readable.from(file.Body);
}

```

**Comment by Marc-Roig** [comment]
I would be careful when extracting the s3 key from a url. People might be using cdn's or other s3 compatible services that might have completely different things (not sure about it but I would check cloudflare cdn and DO spaces format )

We are constantly facing issues with not storing the file path in database, and we might want to consider that in the near future.

@christiancp100 feel free to ping me if you want to collab and work on this together :)

**Comment by christiancp100** [comment]
Good point 🤔 I'll take a closer look when we get to the implementation part. Thanks!

**Comment by y-nk** [comment]
I'm having exactly the same error, also with `aws-s3` as provider but:

1. config is more "default" (not explicitly signed urls)
2. when `npx strapi export --only content` i can see some of the media records having `provider: null` and s3 urls. i don't know how it happened.

Config:

```ts
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_SECRET_ACCESS_KEY'),
        region: env('AWS_REGION'),
        params: {
          Bucket: env('AWS_BUCKET_NAME'),
        },
      },
    },
  },
```

Example of broken record:

```json
{"type":"plugin::upload.file","id":51,"data":{"name":"Laptop.svg","alternativeText":"Laptop.svg","caption":"Laptop.svg","width":null,"height":null,"formats":null,"hash":"Laptop_47c7e81ba6","ext":".svg","mime":"image/svg+xml","size":1.82,"url":"https://tw-marketing-cms.s3.us-west-1.amazonaws.com/Laptop_47c7e81ba6.svg","previewUrl":null,"provider":null,"provider_metadata":null,"createdAt":"2022-06-01T08:16:36.927Z","updatedAt":"2022-06-01T08:16:36.927Z","folderPath":null}}
```

To be noted: this media does NOT appear in the media library but DOES appear when searching for keyword - which is quite annoying as well.

**Comment by kduprey** [comment]
Is this going to be fixed with v5 or is it getting prioritized with v4 minor releases currently?
