### ISSUE TITLE
[User-Permissions] Change schema.json from User doen't have effect on default fields 

### ISSUE THREAD

**Issue by ArthurPedroti** [strapi/strapi#17595]
### Required System information

- Node.js version: v16.20.0
- NPM version: 9.19.4
- Strapi version: 4.12.1
- Database: sqlite
- Operating system: Linux
- Is your project Javascript or Typescript: Javasript

### Describe the bug

Creating a new project with strapi quickstart script, and creating the User schema.json file to update the default fields doesn't work.

Schem.json:
```json
{
  "kind": "collectionType",
  "collectionName": "up_users",
  "info": {
    "name": "user",
    "description": "",
    "singularName": "user",
    "pluralName": "users",
    "displayName": "User"
  },
  "options": {
    "draftAndPublish": false
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": false // add this line
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true,
      "searchable": false
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true,
      "searchable": false
    },
    "confirmationToken": {
      "type": "string",
      "configurable": false,
      "private": true,
      "searchable": false
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.role",
      "inversedBy": "users",
      "configurable": false
    }
  }
}

```

### Steps to reproduce the behavior

1. yarn create strapi-app my-project --quickstart
2. create the file "src/extensions/users-permissions/content-types/user/schema.json"
3. yarn develop
4. try to create a user without email

### Expected behavior

The User schema.json changes reflect on Strapi.

### Screenshots

![image](https://github.com/strapi/strapi/assets/52859409/9deb8c61-76db-4d04-9a29-d1c4a1bd2df1)

### Additional context

It seems like the Strapi UI interface reflects the changes that you did on schema,json, but the default validation persists.
![image](https://github.com/strapi/strapi/assets/52859409/77aa03a0-2b32-48af-8042-16d6f25f237a)

**Comment by alicanso** [comment]
I have a smiliar problem. When I add new content types on development and deploy the schama files to prod, I cant see the new content types. (databases are different)

**Comment by derrickmehaffy** [comment]
This plugin doesn't follow the same structure as the rest of Strapi as it's still largely based on the v3 code and the email is hard coded to be required. For now it's not something we can/will fix in this package and our plan is to build a new replacement package for users-permissions.

Closing this as won't fix for now.
