### ISSUE TITLE
content type dialog style bug on safari

### ISSUE THREAD

**Issue by khasbilegt** [strapi/strapi#17591]
### Required System information

- Node.js version: v20.1.0
- NPM version: 9.8.1
- Strapi version: 4.12.1
- Database: SQLite
- Operating system: MacOS Ventura
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

This appears to be only happening in Safari browser. Relation and UID content type buttons are can't be clicked because the Component and Dynamic Zone buttons overlapping them, from inside the "Add another field" dialog in Content Type Builder.

### Steps to reproduce the behavior

1. Use Safari browser
2. Go to Content Type Builder plugin
3. Click on Add another field button of existing CT
4. Scroll down to the end of the content type list
5. Try to click on either Relation or UID

### Expected behavior

<img width="1920" alt="image" src="https://github.com/strapi/strapi/assets/9023312/b72e7d6f-c947-4d44-ab99-ee5ec1b69592">

### Screenshots

<img width="1920" alt="image" src="https://github.com/strapi/strapi/assets/9023312/09354681-e9be-49c2-a3e9-70f2e74fa994">

**Comment by exotexot** [comment]
Tbh: I also described this bug in Late June: https://github.com/strapi/strapi/issues/17066
And this is still not fixed. Its really sad to ignore your Safari users :(
