### ISSUE TITLE
missing `manifest.json` when running setup after upgrade

### ISSUE THREAD

**Issue by krisballistiq** [strapi/strapi#1760]
**Information**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: Mongo
- **Operating system**: MacOS High Sierra

**What is the current behavior?**
Upgraded from 12.7 to 13.1, and got a missing `packages/strapi-admin/admin/src/config/manifest.json` file error when running `npm run setup:build`.

I checked my repo and it's not there, checked strapi's repo and it IS there https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src/config/manifest.json. So I added it, and `npm run setup:build` worked, but when I went to commit it, it says it's ignored by `.gitignore` here https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/.gitignore#L4 

**Steps to reproduce the problem**
delete `packages/strapi-admin/admin/src/config/manifest.json`, run `npm run setup:build`

**What is the expected behavior?**
`npm run setup:build` should generate the manifest file if it does not exist

**Suggested solutions**
Determine if it does need to be committed, if so remove it from .gitignore, or determine why it's not auto generating if it doesn't need to be committed.

**Comment by lauriejim** [comment]
Hello @krisballistiq I can't reproduce your issue. 
When you say you `upgrade strapi`, what did you exactly do ?

**Comment by lauriejim** [comment]
Why did you loose the `manifest.json` file ?
