### ISSUE TITLE
Cannot update content due to wrong sql query

### ISSUE THREAD

**Issue by landoephan** [strapi/strapi#17605]
## Bug report

Since v4.12.0 (also exists in v.4.12.1, but not in v4.11.7) I am not able to update any content anymore. I'm getting an error on database level, I assume because the query is wrong.
I'm using postgres as my database and I have two strapi database schemas, one for a live version and one for preview purpose.
Based on the error message, it looks like the schema is not present in the query at all places. 

I couldn't print out the query for version 4.11.7 since the error doesn't occur there and everything works fine, so I couldn't compare it and verify my guess.

### Required System information

- Node.js version: 18.14.2
- NPM version: 9.5.0
- Strapi version: 4.12.0
- Database: postgres:15.1
- Operating system: macOS 13.4.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Once I hit the Save button on updating any content type, I get the following error message:

```
error: UPDATE "my_schema"."articles_components" as a
            SET "order" = b.src_order
            FROM ( select "id", row_number() over (partition by "entity_id" order by "order") as src_order from "articles_components" where "entity_id" = $1 ) AS b
            WHERE b.id = a.id - relation "articles_components" does not exist
```
My guess would be that the schema is missing in front of the second "articles_components" call. So instead of `... as src_order from "articles_components"` it should be `... as src_order from "my_schema"."articles_components"`
 
### Steps to reproduce the behavior

1. Set up two database schemas based on the same code
2. Start strapi with any content type and a linked component, let auto migrations run in both database schemas 
3. Create a content and try to update it afterwards

### Expected behavior

I am able to update content.

**Comment by bglidwell** [comment]
Also having this issue. Also Postgres

Issue is present in >4.12.0 and works fine as late as 4.11.7

**Comment by derrickmehaffy** [comment]
Validated by a community member, will validate again myself in a bit

**Comment by derrickmehaffy** [comment]
For reproducing this you need to ensure the `public` schema doesn't exist on the database.
This should only happen for users that use a non-public schema.

**Comment by skwaugh** [comment]
I've run into the same issue.  I use schema `strapi` and it's worked great up until very recently.

Adding my custom schema `strapi` to my search path (`alter role postgres set search_path = "$user", public, extensions, strapi ;`) has not improved things; I get the same `relation "xyz" does not exist.
