### ISSUE TITLE
File Upload Explorer showing GB instead of MB

### ISSUE THREAD

**Issue by sbastias** [strapi/strapi#1761]
**Informations**
- **Node.js version**: 10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.13
- **Database**: MongoDB
- **Operating system**: Ubuntu 14.04

**What is the current behavior?**
The file upload system is indicating GB instead of MB.
![image](https://user-images.githubusercontent.com/1007243/44214640-a39fc000-a13e-11e8-8518-e7862161188f.png)

**Steps to reproduce the problem**
Upload a large file (video?), navigate to "Files Upload"

**What is the expected behavior?**
Should be MB, not GB

**Suggested solutions**
Not sure!

**Comment by danielehrhardt** [comment]
Can confirm this

**Comment by lauriejim** [comment]
Hello @sbastias and @danielehrhardt , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by sbastias** [comment]
I can't do a PR because I didn't fork the repo, I cloned it to make a bunch of other customizations.

It's a simple fix though! I just tested it on KB MB and GB files:

![image](https://user-images.githubusercontent.com/1007243/44353306-92272280-a474-11e8-9a69-889787d323ed.png)

It's this function `getUnit` in:
strapi/packages/strapi-plugin-upload/admin/src/components/Li/index.js

**Currently:**
```
getUnit = (value) => {
    let unit;
    let divider;
    
    switch (true) {
      case value > 10000:
        unit = 'GB';
        divider = 1000;
        break;
      case value < 1:
        unit = 'B';
        divider = 1;
        break;
      case value > 1000:
        unit = 'MB';
        divider = 1000;
        break;
      default:
        unit = 'KB';
        divider = 1;
    }

    return { divider, unit };
  }
```
    
**Should be:**

```
getUnit = (value) => {
    let unit;
    let divider;
    
    switch (true) {
      case value > 1000000:
        unit = 'GB';
        divider = 1000000;
        break;
      case value < 1:
        unit = 'B';
        divider = .001;
        break;
      case value > 1000:
        unit = 'MB';
        divider = 1000;
        break;
      default:
        unit = 'KB';
        divider = 1;
    }

    return { divider, unit };
  }
```

**Comment by danielehrhardt** [comment]
Thank you @sbastias
