### ISSUE TITLE
Issue with Role Selection and Deletion in User Entry Form

### ISSUE THREAD

**Issue by zakipuzo** [strapi/strapi#17615]
I am encountering an issue while using Strapi LTS version 4.12.1. Upon attempting to add **a new user entry**, I've observed the following problems:

**Role Display Issue:** In the user entry form, the select box for assigning roles **displays numbers (e.g., 1, 2, 3)** instead of the corresponding role names. This makes it difficult to accurately assign roles to users, as the displayed numbers do not provide meaningful information.

**Role Selection and Removal Error:** When I select a role from the list and subsequently choose a different role, then attempt to remove the selected role by clicking the "remove" button, an error occurs. The error message displayed is: **"Woops! Something went wrong. Please, try again."**

These issues significantly impact the usability and functionality of the user entry form.

## Steps to Reproduce: 

- Install Strapi LTS version 4.12.1.
- Navigate to the user entry form.
- Observe the role select box displaying numbers instead of role names.
- Select a role from the list, then choose a different role.
- Attempt to remove the selected role using the "remove" button.
- Encounter the "Woops! Something went wrong. Please, try again." error message.

## Expected Behavior:

- The role select box should display the names of roles instead of numbers.
- Users should be able to easily select and assign roles without encountering errors when removing selected roles.

I kindly request the Strapi development team to investigate and resolve these issues to enhance the usability and reliability of Strapi's user management features.

Thank you for your attention to this matter.

**Comment by derrickmehaffy** [comment]
Duplicate https://github.com/strapi/strapi/issues/17561
