### ISSUE TITLE
Clearing DateTime field in Content Manager does not result in enabled Save button

### ISSUE THREAD

**Issue by ntarandek** [strapi/strapi#17614]
### Required System information

- Node.js version: 18.14.0
- NPM version: 9.3.1
- Strapi version: 4.11.1 & 4.12.1
- Database: PostgreSQL
- Operating system: MacOS Monterey
- Is your project Javascript or Typescript: JS

### Describe the bug

Clearing value from date time field does not enable Save button and record can not be saved.

### Steps to reproduce the behavior

1. Go to any edit view screen with date time field that has a value
2. Clear it either manually or clicking on X
3. Value is cleared
4. Save button on top of the edit view is not enabled

### Expected behavior

Save button should be enabled as clearing the field constitutes a record data change.

### Screenshots
![image](https://github.com/strapi/strapi/assets/5468733/a8aab304-5bfa-4520-b5d8-f76899a3cf20)
![image](https://github.com/strapi/strapi/assets/5468733/7985b1e0-3978-4962-af07-2b1459a27117)

**Comment by joshuaellis** [comment]
This was fixed with #17599 and will be released in 4.12.4
