### ISSUE TITLE
Bug: 405 error when configuring components

### ISSUE THREAD

**Issue by bogdaaamn** [strapi/strapi#17629]
#### Development 

- Node.js version: v18.17.0
- NPM version: 9.6.7
- Strapi version: 4.12.1
- Database: sqlite
- Operating system: MacOS Sonoma
- Is your project Javascript or Typescript: js

#### Production

The bug is reproducible in two other production envs, both of the deployed on Strapi Cloud, not sure of the sys specs.

### Describe the bug

I get a 405 error when trying to save the configuration of a component in both dev and production versions of Strapi 4.12.1. 

Being on the **Configure the view — Colour theme** page (i.e. /admin/content-manager/components/components.colour-theme/configurations/edit), I press **Save**, and it shows that **Warning: An error occurred**. Also wrong style on the button (delete instead of confirm). 

The server log says `PUT /components/components.colour-theme/configuration (1 ms) 405`

The full console log says 

```
{
    "message": "Request failed with status code 405",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 405\n    at Vt (http://localhost:1337/admin/main.e8f996b4.js:2856:1042)\n    at XMLHttpRequest.mn (http://localhost:1337/admin/main.e8f996b4.js:2856:4454)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Authorization": "Bearer xxx",
            "Content-Type": "application/json"
        },
        "paramsSerializer": {},
        "baseURL": "",
        "signal": {},
        "method": "put",
        "url": "/components/components.colour-theme/configuration",
        "data": "{\"layouts\":{\"list\":[\"id\",\"colour\"],\"edit\":[[{\"name\":\"colour\",\"size\":6}]]},\"metadatas\":{\"id\":{\"edit\":{},\"list\":{\"label\":\"id\",\"searchable\":false,\"sortable\":false}},\"colour\":{\"edit\":{\"label\":\"Colour\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"colour\",\"searchable\":true,\"sortable\":true}}},\"settings\":{\"bulkable\":true,\"filterable\":true,\"searchable\":true,\"pageSize\":10,\"mainField\":\"id\",\"defaultSortBy\":\"id\",\"defaultSortOrder\":\"ASC\"}}"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 405
}
```

### Steps to reproduce the behavior

1. Go to component menu
2. Click **Configure the view** on a component
3. Click **Save** after renaming the labels of some fields
4. Click **Confirm** on the dialog

### Expected behavior

To save the new configuration, including the new labels of the fields.

### Screenshots

![Screenshot 2023-08-09 at 13 09 56](https://github.com/strapi/strapi/assets/22895284/1c4132f7-6d25-4d8a-8e97-608b94a8bde3)

### Additional context

- This happens only on components, not on content types or single types
- This happens on all components
- I have been trying to reproduce this on a fresh setup of Strapi 4.12.1, but I cannot find the problem with the components. Hence I guess there is problem with the configuration of certain components that I have? Willing the share those, but I find it strange it happens in three different envs..

**Comment by dgrebb** [comment]
@bogdaaamn take a look at #17579 

and upgrade to [v4.12.4](https://github.com/strapi/strapi/releases/tag/v4.12.4), which includes the fix :)

**Comment by gu-stav** [comment]
Fixed by https://github.com/strapi/strapi/pull/17579
