### ISSUE TITLE
Can't customize Primary Key type or name

### ISSUE THREAD

**Issue by ferminminetto** [strapi/strapi#1762]
**Informations**
- **Node.js**: 10.0.8
- **npm**: 6.2.0
- **Strapi**: 3.0.0-alpha.13.1
- **Database**: MySQL
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
I'm using Strapi to connect with an existing table in a MySQL table. Sadly, the id column of such table it's not called `id`, it's called `work_id`. To solve this I used in my model's JSON settings file the following configuration:
```
{
  "connection": "default",
  "collectionName": "works",
  "primaryKey": "work_id",
  "info": {
    "name": "Works",
    "description": "",
    "mainField": "work_id"
  },
  "attributes": {
    "work_id": {
      "type": "integer",
      "required": true
    },
   ...
```
It lists the objects from the database well, but when I try to enter the details of an object it throws an error saying: ``
Error: Undefined binding(s) detected when compiling SELECT query: select `works`.* from `works` where `works`.`work_id` = ? limit ?`
``

**Steps to reproduce the problem**
Connect to an existing table of a database using a different PK name.

**What is the expected behavior?**
I should be able to enter the detail view of the object from that type of content.

**Suggested solutions**
I'm not sure!

**Comment by lauriejim** [comment]
Hello @ferminmine , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by takahiro-yonei** [comment]
I really appreciate if there is any update.
Is there any update?

Thank you always for great works!

**Comment by lauriejim** [comment]
We (Strapi core team) don't have time now to work on. Need you (the community) investigate and work  on this issue.

**Comment by chaitanyya** [comment]
While working on the custom timestamps I discovered the hardcoded primary key name. I can pick this issue and use the `idAttribute` to create custom primary key column name.

For further clarification can you guys tell me how is `primaryKey` attribute different from `idAttribute`?

**Comment by chaitanyya** [comment]
I believe that's `idAttributeType`, from the documentation: 

> **idAttribute:** This tells the model which attribute to expect as the unique identifier for each database row (typically an auto-incrementing primary key named 'id'). Only valid for strapi-hook-bookshelf

This seems very similar to what `primaryKey` does. Is there a reason for having them both?

**Comment by junioreuripedes** [comment]
Are there any fixe?

**Comment by puco** [comment]
What is the progress of this feature?

**Comment by lauriejim** [comment]
Hello! It's not a priority for us, we will add a comment if we start something to fix this issue.

**Comment by veitbjarsch** [comment]
I digged deeper into this problem and it looks like there are multiple drawbacks that need to be handled. If you use a custom primary key that is not autogenerated (uuid, autoIncrement). The user should be able to set the primary key via the UI. Which means there should be some attributes like "required" or  "configurable" for it. Maybe I will check this out the next days.

**Comment by maxbaluev** [comment]
Any updates?

**Comment by jonathanmach** [comment]
Also waiting for updates on this.

**Comment by lauriejim** [comment]
Changed to feature request because we stoped the support of it.

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/bookshelf-custom-id/719/2

**Comment by saintego** [comment]
Any progress?

**Comment by derrickmehaffy** [comment]
> Any progress?

No, not at this time. We don't have an ETA for when we will look at this.

**Comment by JakubLog** [comment]
Is there any progress with this feature?

**Comment by niklasfjeldberg** [comment]
Is there any update/news on this?

**Comment by bluengreen** [comment]
Any update? Does Strapi do anything other than blog posts? This seems like an MVP requirement.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/allow-customization-of-primary-key-id-type-and-name
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
