### ISSUE TITLE
CAN ... WHEN Has same role as creator condition is not working with Media Library access

### ISSUE THREAD

**Issue by mchtugr** [strapi/strapi#17627]
### Required System information

- Node.js version: 16.19.1
- NPM version: 8.19.3
- Strapi version: 4.10.5
- Database: sqlite3
- Operating system: macOS Monterey
- Is your project Javascript or Typescript: JS

### Describe the bug

Custom Roles and Permissions are not working as expected with Media Library. `CAN ... WHEN Has same role as creator` condition is not working with Media Library access. Users can see all of the media files regardless of their role. This feature works as expected in version 4.4.6. However, In 4.10.5, it's not possible to restrict media files depending on the creator role.

### Steps to reproduce the behavior

1. Go to 'Settings > Roles' and click on 'Add new role button'.
2. Click on 'Plugins' tab and open 'Upload' accordion.
3. Check 'Access the Media Library' checkbox and click on 'Settings' button inside 'GENERAL' section.
4. Check 'Has same role as creator' option and hit the 'Apply' button.
5. Save the changes and create the new custom role.
6. Go to 'Settings > Users' and click on 'Invite new user'. button.
7. Create a new user with recently created custom role.
8. Login to Strapi admin panel with a super admin user and upload a media file.
9. Login to Strapi user in another browser with recently created user.
10. Click on 'Media Library' button.
11. There you will see the file uploaded by a super admin user

### Expected behavior

Users should only see the content they are allowed to. Only media files created by a user with the same role should be available to the users with custom role.

### Screenshots

Create a custom role: <br>

<img width="1306" alt="create-custom-role" src="https://github.com/strapi/strapi/assets/55500916/27e693bf-2dda-4d1f-9a6d-634a201ef13d">

<br><br>

Create a user with the recently created custom role: <br>

<img width="1030" alt="create-user" src="https://github.com/strapi/strapi/assets/55500916/1ed69bee-e468-49df-8206-a69c9c560133">

<br><br>

Upload a file with a super admin user: <br>

<img width="1340" alt="upload-super-admin only-file" src="https://github.com/strapi/strapi/assets/55500916/65a4dc46-00e9-40e9-8fcd-2af02339b6b1">

<br><br>

User with a custom role can see the file uploaded by super admin user: <br>

![Screen Shot 2023-08-09 at 10 29 14](https://github.com/strapi/strapi/assets/55500916/97953078-568d-4b82-90b0-155cdb63e60f)

### Additional context

Although the visibility issue is resolved with the latest version of Strapi (4.12.1), Custom Roles and Permissions still do not work as expected. With the same config above, users with custom role cannot see even their own files.

**Comment by TOZXII** [comment]
I have the same issue where I want each user only can see his own uploaded assets by using **(Is creator)**
but it seems like the Custom Roles and Permissions still do not

**Comment by derrickmehaffy** [comment]
feature request is here for media library RBAC and folders RBAC: https://feedback.strapi.io/feature-requests/p/permission-management-for-media-library-folders
