### ISSUE TITLE
 Enable WAL mode for Sqlite databases

### ISSUE THREAD

**Issue by Stuhl** [strapi/strapi#17625]
- Node.js version: v16
- NPM version: 9.xx
- Strapi version: 4.5.6
- Database: SQLite
- Operating system: WIndows | Ubuntu 22 on VPS
- Is your project Javascript or Typescript: JavaScript

### Enable WAL mode for Sqlite databases

It seems like that strapi isn't using `db.pragma('journal_mode = WAL')` in the initiliazation method of the database. WAL mode is quite important for performance and a no-brainer to enable since it's only 1 line. The author of better-sqlite3 (which strapi is using) is [recommending to enable WAL mode](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/performance.md).

Now I know that Sqlite3 doesn't have the best reputation here but enabling WAL mode is very simple and for alot of websites you don't need a sophisticated database system like Postgres or MySQL.

### Steps to reproduce the behavior
none

### Expected behavior
SQlite should use pragma WAL just as the better-sqlite authors recommend.

### Screenshots
none

### Code snippets
I looked through the files but haven't found any pragma sets except this one. This is from the file packages/core/database/lib/dialects/sqlite/index.js

```
async initialize() {
    await this.db.connection.raw('pragma foreign_keys = on');
  }
```

### Additional context
Additionally there is one more pragmas to improve performance for almost no cost:
`pragma synchronous = normal;`

This will skip waiting FSYNC for every update. It's 100% corruption safe if WAL mode is enabled because only the WAL checkpoints have to wait for FSYNC. This should be used in conjuction with WAL mode.

Further read (5-10 min): [SQLite performance tuning](https://phiresky.github.io/blog/2020/sqlite-performance-tuning/)

**Comment by Stuhl** [comment]
Hello, I updated the initial post with the template.

**Comment by derrickmehaffy** [comment]
Normally we wouldn't reopen this since it's not really a bug but more of a feature request but I'll add an exception here as it seems simple and worth it to look into.

**Comment by ASCE-D** [comment]
Hey @derrickmehaffy I would like to contribute to this feature request please assign me.
