### ISSUE TITLE
Jest-tests not running

### ISSUE THREAD

**Issue by nickolayArbuzov** [strapi/strapi#17641]
### Required System information

- Node.js version: 18.16.1
- NPM version: 9.5.1
- Strapi version: 4.12.4
- Database: sqlite
- Operating system: Windows 10 Pro
- Is your project Javascript or Typescript: Typescript

### Describe the bug

jest-tests not running; error appears: 

> Middleware "strapi::session": App keys are required. Please set app.keys in config/server.js (ex: keys: ['myKeyA', 'myKeyB'])

project creating according to the doc's, the main recommendations are used, tried various options

### Steps to reproduce the behavior

1. Create a new project from scratch
2. Install test tools, and add this to package.json according to https://docs.strapi.io/dev-docs/testing#install-test-tools
3. Set up a testing environment according to https://docs.strapi.io/dev-docs/testing#set-up-a-testing-environment
4. Create a helper with Strapi instance according to https://docs.strapi.io/dev-docs/testing#create-a-strapi-instance
5. Create a entry-point for test a Strapi instance according to https://docs.strapi.io/dev-docs/testing#test-a-strapi-instance; if necessary to increase the allowed test execution time, add to the 3rd line of this file(./tests/app.test.js) - `jest.setTimeout(60 * 1000)` (for example 1 minute)
6. Just run yarn test 

### Expected behavior

see a success result of your first test

### Screenshots

![3](https://github.com/strapi/strapi/assets/56513866/2df43a4b-1cad-4138-95b5-af24008f22f4)
![4](https://github.com/strapi/strapi/assets/56513866/bad200c7-b8bb-4a71-ab8e-d83dc34ba5f8)
![5](https://github.com/strapi/strapi/assets/56513866/c926e1e2-091d-4c1f-a4eb-f7a6d7abd389)

### Additional context

.env file with APP_KEYS variable exists

tried other different options, as in the screenshots

**Comment by stb13579** [comment]
@nickolayArbuzov 2 things come to mind:
- There is a warning at the top of the documentation that the SQLite database does not work with Windows. Though I don't know why this would trigger an error with the session middleware.
- setting up unit tests for TypeScript projects is different as I understand (have not done so myself). Some community discussion on the forum: https://forum.strapi.io/t/v4-unit-testing/14818/33
