### ISSUE TITLE
pnpm build & start with production is not working

### ISSUE THREAD

**Issue by vKongv** [strapi/strapi#17644]
### Required System information

- Node.js version: v16.18.1
- NPM version: 8.19.2
- PNPM version: 8.5.1
- Strapi version: 4.12.4
- Database: Sqlite
- Operating system: MacOS 13.4.1 (M1)
- Is your project Javascript or Typescript: JS

### Describe the bug

I am using pnpm to install, build and start Strapi application for production but I am getting a blank `/admin` page after navigating to it. I am seeing the following error from browser console:

```
Uncaught TypeError: (0 , o.default) is not a function
    at yt (main.23896a44.js:1548:16710)
    at main.23896a44.js:1548:17101
    at Array.reduce (<anonymous>)
    at ut (main.23896a44.js:1548:17027)
    at main.23896a44.js:1548:20083
    at main.23896a44.js:1563:3969
    at main.23896a44.js:1563:3428
    at Me (main.23896a44.js:1563:2556)
    at Me (main.23896a44.js:1563:2903)
    at J (main.23896a44.js:1563:3390)
```

For the same project, I am able to get it working simply by using `npm`

### Steps to reproduce the behavior

1. Start a fresh project with latest Strapi using Quickstart and JS
2. `pnpm i --shamefully-hoist`
3. `NODE_ENV=production pnpm build`
4. `NODE_ENV=production pnpm start`
5. Navigate to `localhost:1337/admin` and you shall see a blank page with the error in console

### Expected behavior

pnpm build and start should work

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I am following this issue https://github.com/strapi/strapi/issues/16202 regarding pnpm issue. I manage to build and start but hitting this final roadblock :(

**Comment by gu-stav** [comment]
Hi, thanks for opening the issue. You could help us understand what the error is about by running `STRAPI_ENFORCE_SOURCEMAPS='true' yarn build`. This will build the admin panel with source maps and give more detail about the error context.

**Comment by smoothdvd** [comment]
@vKongv You should run pnpm i twice:

**Comment by smoothdvd** [comment]
@vKongv You should run pnpm i twice:
pnpm i --shamefully-hoist
pnpm i --config.node-linker=hoisted

Then build and start

**Comment by DevDengChao** [comment]
Will these settings be updated to the .npmrc in starter template project?

**Comment by sangdth** [comment]
> @vKongv You should run pnpm i twice: pnpm i --shamefully-hoist pnpm i --config.node-linker=hoisted
> 
> Then build and start

If I set the `node-linker=hoisted`, the build for my Nextjs `frontend` will be broken. Does anyone know how to avoid it?

**Comment by sangdth** [comment]
> Hi, thanks for opening the issue. You could help us understand what the error is about by running `STRAPI_ENFORCE_SOURCEMAPS='true' yarn build`. This will build the admin panel with source maps and give more detail about the error context.

After adding the sourcemap env, this is the error message:

```
TypeError: (0 , o.default) is not a function
    at dt (react-router.js:525:16)
    at react-router.js:567:24
    at Array.reduce (<anonymous>)
    at lt (react-router.js:563:16)
    at react-router.js:836:26
    at react.production.min.js:19:182
    at react.production.min.js:18:85
    at Fe (react.production.min.js:16:230)
    at Fe (react.production.min.js:17:24)
    at ue (react.production.min.js:18:52)
```

**Comment by vKongv** [comment]
Hey, I actually gave up using `pnpm` for setting up Strapi in my project. I still use monorepo to group the code together but I am ignoring the project from pnpm workspace and just use `npm` for the project instead. It just work out of the box and save me tons of time to wrestling with pnpm and strapi :( .

Most of the time the package that I use on the other project is not sharable with strapi so I am fine with this setup at the moment. I haven't got a time to go back setting a pnpm build again with the suggestion, might try again when I have some spare time

**Comment by sangdth** [comment]
Thanks for your suggestion @vKongv , I also gave up on pnpm and switch to yarn. It works out of the box.

**Comment by joshuaellis** [comment]
we don't explicity support pnpm and there's an open issue for this, im going to close this one as duplicate #15992

**Comment by TechQuery** [comment]
> @vKongv You should run pnpm i twice: pnpm i --shamefully-hoist pnpm i --config.node-linker=hoisted
> 
> Then build and start

@smoothdvd Yes, it fixed in https://github.com/strapi/strapi/issues/15511#issuecomment-1792679398
