### ISSUE TITLE
Deep populating not working for dynamic zones in v4.12.1 and newer

### ISSUE THREAD

**Issue by beornf** [strapi/strapi#17654]
### Required System information

- Node.js version: 16.20.2
- NPM version: 8.19.4
- Strapi version: 4.12.4
- Database: Sqlite
- Operating system: Debian
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When running a REST query that deeply populates a dynamic zone the nested component field is no longer returned.

### Steps to reproduce the behavior

1. Create a component with a repeatable component field.
2. Add the component to dynamic zone.
3. Execute the query `GET /api/entities?populate[zone][populate]=*`
4. See that the `zone[0].nested` field is no longer returned.

### Expected behavior

The nested field should be returned and populated with an array of objects.

### Code snippets

See the code example https://docs.strapi.io/dev-docs/api/rest/populate-select#example-deeply-populate-a-dynamic-zone-with-2-components.

### Additional context

The deep population was working in version 4.12.0. The bug might be due to https://github.com/strapi/strapi/pull/16507.

**Comment by moedech** [comment]
I can confirm this issue. The documented method https://docs.strapi.io/dev-docs/api/rest/populate-select#example-deeply-populate-a-dynamic-zone-with-2-components for a shared population strategy is currently not working anymore. However, the detailed population strategy is still working, but this would imply changing all the request.

**Comment by tvvignesh** [comment]
A query like this stopped working in the latest version:

`const global = await fetchAPI('/global?populate[0]=*&populate[metadata][populate][1]=*&populate[favicon][populate][2]=*&populate[metadata][populate][shareImage][populate][3]=*&populate[footer][populate][columns][populate][links][populate][4]=*&populate[footer][populate][logo][populate][5]=*')`

**Comment by mgrubinger** [comment]
I am experiencing the same issue. v4.12.1 seems like an important version due to the security fixes, downgrading to v4.12.0 as a temporary workaround feels wrong, but required for my use case at the moment.

**Comment by derrickmehaffy** [comment]
Can't reproduce on v4.13.2: 
![image](https://github.com/strapi/strapi/assets/8593673/05a762e6-b972-4cea-941c-0dd3becf907d)

**Comment by molund** [comment]
@derrickmehaffy 
I think we are having the same issue with a repeatable component.
![image](https://github.com/strapi/strapi/assets/547803/1264eaec-6641-4379-8a1e-a30b2045f4fc)

**Comment by matthijsch** [comment]
We've encountered the same error and were able to fix it by changing the populate fields:

before
```
{
  dynamic_content: {
    populate: {
      repeatable_component: '*'
      },
    },
  }
}
```

after
```
{
  dynamic_content: {
    populate: {
      repeatable_component: {
        populate: {
          image: '*',
        },
      },
    },
  }
}
```

hope this helps you

**Comment by beornf** [comment]
I have created a strapi project able to reproduce a bug you can `git pull` from https://github.com/beornf/strapi-demo. The login details are:

Email:  demo@strapi.io
Password: Demo1234

Example query:
`http://localhost:1337/api/articles?populate[testDZ][populate]=*`

Strapi 4.14.0 response:
```
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "testString": "test1",
        "createdAt": "2023-09-30T07:31:53.427Z",
        "updatedAt": "2023-09-30T10:01:51.136Z",
        "publishedAt": "2023-09-30T07:35:48.866Z",
        "testDZ": [
          {
            "id": 1,
            "__component": "test.test-compo",
            "testString": "test1",
            "testNestedCompo": [
              {
                "id": 1,
                "testNestedString": "testNested1"
              },
              {
                "id": 2,
                "testNestedString": "testNested2"
              }
            ]
          },
          {
            "id": 1,
            "__component": "test.test-compo2",
            "testInt": 1
          }
        ]
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 25,
      "pageCount": 1,
      "total": 1
    }
  }
}
```

The nested repeatable components are returned when created from a 4.14.0 project from scratch. However the many-to-one relational field `authors` is missing from the response see:

<img width="522" src="https://github.com/strapi/strapi/assets/1625782/36f48e16-12c9-4ce9-8f26-638d342dff5b">

Could there be a requirement to migrate the data/schema when created in a project in version 4.12.0 or older? I can perform more testing if needed.
