### ISSUE TITLE
S3 pre-signed URL for images on Media Library page contains additional data in X-Amz-SignedHeaders parameter

### ISSUE THREAD

**Issue by shamikatamazon** [strapi/strapi#17655]
### Required System information

- Node.js version: v18
- NPM version: 9.6.7
- Strapi version: 4.12.4 (node v18.17.1) 
- Database: postgres
- Operating system: Amazon Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When loading the Media Library page, all the thumbnails are broken, however, clicking on them loads the image in the modal dialog

When 

### Steps to reproduce the behavior

1. Go to Media Library (thumbnails are broken)
2. Click on a thumbnail 
3. Thumbnail loads up 

### Expected behavior

Media Library thumbnails are displayed

### Screenshots

<img width="1181" alt="image" src="https://github.com/strapi/strapi/assets/82420633/b002d8c8-f149-43c9-bc87-4a45da885aba">
<img width="1135" alt="image" src="https://github.com/strapi/strapi/assets/82420633/b9140f75-d946-4b1b-8550-3e613bab9065">

### Code snippets

HTTP call for images from the media library (does not work)
https://<bucketname>.s3.eu-west-2.amazonaws.com/thumbnail_image1_568bc16303.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<>%2F20230811%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230811T222801Z&X-Amz-Expires=900&X-Amz-Signature=<>&X-Amz-SignedHeaders=host?2023-08-11T19:27:25.593Z

notice that X-Amz-SignedHeaders=host?2023-08-11T19:27:25.593Z

and has error 
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><HeadersNotSigned>host</HeadersNotSigned>

HTTP call for images from details window: (works)

https://<BucketName>.s3.eu-west-2.amazonaws.com/thumbnail_image1_b7e8f55b8b.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<>%2F20230811%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20230811T222801Z&X-Amz-Expires=900&X-Amz-Signature=<>&X-Amz-SignedHeaders=host

X-Amz-SignedHeaders=host

**Comment by jbgtmartin** [comment]
I can confirm the issue, this is due to the following lines in `ImageAssetCard.js`. An additional param is added to the URL for cache busting (`thumbnail` prop here), but the URL already contains query params from the signed URL.

```js
export const ImageAssetCard = ({ height, width, thumbnail, size, alt, ...props }) => {
  // Prevents the browser from caching the URL for all sizes and allow react-query to make a smooth update
  // instead of a full refresh
  const urlWithCacheBusting = props.updatedAt ? `${thumbnail}?${props.updatedAt}` : thumbnail;

  return (
    <AssetCardBase {...props} subtitle={height && width && ` - ${width}✕${height}`} variant="Image">
      <CardAsset src={urlWithCacheBusting} size={size} alt={alt} />
    </AssetCardBase>
  );
};
```

**Comment by yclgkd** [comment]
I'm having the same problem and I'm using the Tencent Cloud COS.
https:// xxx.cos.ap-shanghai.myqcloud.com/xxx.png?q-sign-algorithm=sha1&q-ak=AKIDBas57xxd5L3aw6x3nX7VJvNdgXDi1INUUH&q-sign-time=1692321618;1692325218&q-key-time=1692321618;1692325218&q-header-list=host&q-url-param-list=&q-signature=7c62a3471fa710f07358xdadc3x5ecd9e7f5a400f4 **?2023-08-17T09:13:07.623Z**
![image](https://github.com/strapi/strapi/assets/31514100/81fb7124-02b0-41bb-8fba-bcac48b362ba)
![image](https://github.com/strapi/strapi/assets/31514100/5344582e-e498-458e-9d4c-e0b7dd78ff49)

**Comment by jbgtmartin** [comment]
Hi,
Thanks for the changes. I tried the fix, and I get the following error from AWS:
```xml
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
```

If I remove the `updatedAt` param from the URL, it works fine. I think that AWS uses the full URL to compute and validate the signature, so we can not add anything to the URL otherwise it breaks the signature.

In fact, AWS signed URLs already contain a timestamp (`X-Amz-Date` param), so maybe the `updatedAt` param can just be removed when using AWS as the upload provider? As `X-Amz-Date` should already prevent browser caching I guess.
