### ISSUE TITLE
Warning: an error occurred while requesting the api

### ISSUE THREAD

**Issue by Dawsoncodes** [strapi/strapi#17653]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.7
- Database: Postgres
- Operating system: Windows 10
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When building the Strapi project, the admin dashboard will not work unless the link in the browser is http://localhost:1337, and it will show this error "Warning: an error occurred while requesting the API"

When I change the ports, gets me the same error.

I even tried hosting the project on a domain, still doesn't work.

Seems like it has something to do with the domain in the browser.

Using Docker, the port inside of the container doesn't matter as long as the port outside of the container (showing in the browser) is 1337.

### Steps to reproduce the behavior

1. Change the port to any port rather than 1337, try 8000
2. Install dependencies (yarn)
3. Run `yarn build`
4. Go to http://localhost:8000/admin
5. You'll see "Warning: an error occurred while requesting the api"

### Expected behavior

Admin dashboard should show as always.

### Screenshots

![image](https://github.com/strapi/strapi/assets/101001810/3e824e5c-49ff-4ea5-9a7e-2ba81b557d73)

**Comment by gu-stav** [comment]
Sounds like as if you are running into this bug: https://github.com/strapi/strapi/issues/17634 Please let me know if the workaround in there works for you.

**Comment by Dawsoncodes** [comment]
## Workaround

Inside of the `src/admin/app.example.tsx` added `@ts-ignore` on top of the `bootstrap()` function.

```tsx
//@ts-ignore
bootstrap(app) {
  console.log(app);
},
```

**Comment by yijinc** [comment]
has the same error

i discover the api `admin/init` is 404
