### ISSUE TITLE
Request failed with status code 404 on 4.12.4 when publish entity

### ISSUE THREAD

**Issue by v-fpavlik** [strapi/strapi#17661]
### Required System information

- Node.js version: 18.17.0
- NPM version: 9.6.6
- Strapi version: 4.11.5 -> 4.12.4
- Database: postgres
- Operating system: windows
- Is your project Javascript or Typescript: TS

### Describe the bug

After saving entity in strapi version `4.12.4` I can't publish it. Receiving 404 error on frontend side. Backend logs are clear. In console 
you can see next 2 errors.
First one: 
`GET http://localhost:1337/content-manager/collection-types/api::game.game/20/actions/numberOfDraftRelations 404 (Not Found)`
Second one: 
`Request failed with status code 404` 
for url `http://localhost:1337/content-manager/collection-types/api::game.game/20/actions/numberOfDraftRelations`
(screenshot below)

Downgrading strapi to 4.11.5 resolves the problem

### Steps to reproduce the behavior

Not sure about entity type or types of components, but
1. Update strapi to 4.12.4
2. Create entity and save
3. Try to publish
4. See error in console

### Expected behavior

Entity will by published

### Screenshots

![image](https://github.com/strapi/strapi/assets/102483248/5bd8bbad-85b4-45e4-b40c-cbd09342ca15)
![image](https://github.com/strapi/strapi/assets/102483248/cbc1372e-39a3-436c-994a-6d0b0310c2d6)

**Comment by v-fpavlik** [comment]
Hey @Feranchz! Thank for answering. Yes I did all as you told and now I have a problem with build
- I deleted `.cache/`, `.dist/` and `node_modules/`
- I run `yarn && yarn build`
Now I received next message 
```
✖ Webpack
  Compiled with some errors in 16.28s

[
  {
    file: './src/admin/app.example.tsx:\x1B[32m\x1B[1m32:13\x1B[22m\x1B[39m',
    message: "\x1B[90mTS7006: \x1B[39mParameter 'app' implicitly has an 'any' type.\r\n" +
      '  \x1B[0m \x1B[90m 30 |\x1B[39m     ]\x1B[33m,\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 31 |\x1B[39m   }\x1B[33m,\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 32 |\x1B[39m   bootstrap(app) {\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m    |\x1B[39m             \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 33 |\x1B[39m     console\x1B[33m.\x1B[39mlog(app)\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 34 |\x1B[39m   }\x1B[33m,\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 35 |\x1B[39m }\x1B[33m;\x1B[39m\x1B[0m',
    details: undefined,
    stack: "Error: \x1B[90mTS7006: \x1B[39mParameter 'app' implicitly has an 'any' type.\r\n" +
      '  \x1B[0m \x1B[90m 30 |\x1B[39m     ]\x1B[33m,\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 31 |\x1B[39m   }\x1B[33m,\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 32 |\x1B[39m   bootstrap(app) {\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m    |\x1B[39m             \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 33 |\x1B[39m     console\x1B[33m.\x1B[39mlog(app)\x1B[33m;\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 34 |\x1B[39m   }\x1B[33m,\x1B[39m\x1B[0m\r\n' +
      '  \x1B[0m \x1B[90m 35 |\x1B[39m }\x1B[33m;\x1B[39m\x1B[0m\n' +
      '    at C:\\Users\\User\\Desktop\\launcher\\lela\\strapi-backend\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:42:27\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at C:\\Users\\User\\Desktop\\launcher\\lela\\strapi-backend\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:41:16\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (C:\\Users\\User\\Desktop\\launcher\\lela\\strapi-backend\\node_modules\\fork-ts-checker-webpack-plugin\\lib\\hooks\\tap-after-compile-to-get-issues.js:5:58)'
  }
]
Admin UI built successfully
Done in 46.97s.
```
And now there is no `.dist/build/` folder only `.dist/src/`, `.dist/config/` and `tsconfig.tsbuildinfo`

**Comment by v-fpavlik** [comment]
UPD: Returning to `4.11.5` resolves bug with a build

**Comment by Lars-** [comment]
I'm facing the same problem and I tried the workaround, but it doesn't work. I also don't have the `src/admin/app.example.tsx` file, but `src/admin/app.example.js`. I tried adding the `@ts-ignore` anyways, but it doesn't do anything.

**Comment by Namstel** [comment]
The workaround doesn't seem to be working for me.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/17634
