### ISSUE TITLE
Disappears after creating a component

### ISSUE THREAD

**Issue by 777shuang** [strapi/strapi#17660]
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.8.1
- Strapi version: v4.12.4
- Database: default
- Operating system: Linux Mint
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Disappears after creating a component

### Steps to reproduce the behavior

1. Go to 'Content-Type Builder'
2. Click on 'Create a new  component'
3. Create a component
4. Click on 'Save'
5. See error

### Expected behavior

component is created

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I tried running `yarn create strapi-app my-project --quickstart` and the result was the same.

**Comment by derrickmehaffy** [comment]
can't reproduce on a fresh v4.12.4 project, not enough information from user.
