### ISSUE TITLE
Failed to load strapi blog post on production admin dashboard

### ISSUE THREAD

**Issue by ghufr** [strapi/strapi#1766]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: Mongo
- **Operating system**: Ubuntu 18.04.1

**What is the current behavior?**
Blog post won't load
![2018_08_18_10_01_06_window](https://user-images.githubusercontent.com/20156570/44295172-2d31c800-a2ce-11e8-817b-bf9b215a0613.png)

**Steps to reproduce the problem**
Deploy strapi and use domain

**What is the expected behavior?**
Blog post loaded

**Suggested solutions**
- Delete Blog post on admin dashboard
- Enable CORS

**Comment by lauriejim** [comment]
Hello @ghufr ! Thank you for this report, will try to fix it.

**Comment by amartincolby** [comment]
What's the status of this? It's still listed as an open issue and I'm encountering the problem in Beta.

**Comment by cadavre** [comment]
Same problem here, still in 2020. It's kind of a ridiculous because I cannot create any more admin accounts now. :)

**Comment by derrickmehaffy** [comment]
@cadavre you are testing with the latest beta right? (beta.18.4)?

**Comment by cadavre** [comment]
Yes, beta.18.4. In fact I cannot reach any CMS menu now...

Any workaround?

How frustrating is that whole CMS fails because of feature called "get news from blog". Argh.

**Comment by derrickmehaffy** [comment]
Can you dump a screenshot of your network tab errors?

**Comment by cadavre** [comment]
```
Access to fetch at 'https://blog.strapi.io/ghost/api/v0.1/posts/?client_id=ghost-frontend&client_secret=1f260788b4ec&limit=2' from origin 'xxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by derrickmehaffy** [comment]
That CORS error shouldn't prevent the admin from loading :thinking:

**Comment by cadavre** [comment]
I'll try to investigate. BTW Can't simply remove this feature? Not really sure its that useful.

**Comment by derrickmehaffy** [comment]
It's embedded into the `strapi-admin` package I believe, you can customize that package via the over-ride system. https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html (there won't be a direct guide to remove that but the general flow of how you tweak that package is there)

**Comment by asherccohen** [comment]
Hi, is this still a thing. 
I'm getting something similar.
In my case deploying to prod doesn't let me see content-types (or any other entry from db).

My issue links to this since I also see the same network error about cors.does this mean the user cookies are not stored correctly therefore I'm logging in but can't link to the right db entries?

Any workaround?it makes my strapi instance rather useless in prod.
