### ISSUE TITLE
./utils folder not found in .cache on v4.12.4

### ISSUE THREAD

**Issue by lawathib** [strapi/strapi#17671]
### Required System information

- Node.js version: v18.17.1
- NPM version: v9.5.1
- Strapi version: v4.12.4
- Database: MySQL 8.0.23
- Operating system: Win10 64-bit, x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Since upgrading to v4.12.4, the `build` script fails with this error:
ModuleNotFoundError: Module not found: Error: Can't resolve './utils' in 'C:\Users\<me>\repos\<my repo>\.cache\admin\src\pages\App'

### Screenshots

![image](https://github.com/strapi/strapi/assets/131718562/19b9b900-d4c6-445c-be43-d6c144a5d75d)

### Additional context

There used to be a utils folder found in that specific path in the .cache folder, but now with the new version it seems to delete or never create that directory. Not sure what is going on, we've tried reinstalling, rebuilding, deleting .cache, deleting node_modules, reinstalling again... no indication of where this came from.

**Comment by dennism501** [comment]
Hi, @lawathib what version were you on before upgrading to `4.12.4`?

**Comment by lawathib** [comment]
> Hi, @lawathib what version were you on before upgrading to `4.12.4`?

@dennism501 version 4.11.1

**Comment by lawathib** [comment]
Discovered the problem. We had some code we were writing onto a node_modules file when we run a build, and with the version release that file has some changes. We fixed the issue, this ticket can be closed.
