### ISSUE TITLE
Start failure after installing graphql plugin

### ISSUE THREAD

**Issue by flosd** [strapi/strapi#1767]
**Informations**
- **Node.js version**:  8.11.3
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: mongodb
- **Operating system**: WIndows

**What is the current behavior?**
`[2018-08-18T20:19:06.150Z] debug ⛔️ Server wasn't able to start properly.
[2018-08-18T20:19:06.152Z] error Cannot find module 'C:\Users\Mikk\Desktop\Personaalne\rest\node_modules\strapi\lib\utils'`

**Steps to reproduce the problem**
Make a new project with strapi, and install graphql plugin

**What is the expected behavior?**
It shouldn't produce errors and I should successfully be able to start the project.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues.
Please check https://github.com/strapi/strapi/issues/1612
