### ISSUE TITLE
deloy on vercel ; " /bin/sh: hostname: command not found"

### ISSUE THREAD

**Issue by liu874396180** [strapi/strapi#17670]
Running build in Cleveland, USA (East) – cle1
--
00:09:50.726 | Cloning github.com/liu874396180/strapi-vercle-site (Branch: main, Commit: 887d155)
00:09:51.153 | Cloning completed: 427.312ms
00:09:51.480 | Restored build cache
00:09:51.510 | Running "vercel build"
00:09:52.010 | Vercel CLI 31.2.3
00:09:52.589 | Installing dependencies...
00:09:52.886 | yarn install v1.22.17
00:09:52.950 | warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
00:09:52.952 | [1/5] Validating package.json...
00:09:52.955 | [2/5] Resolving packages...
00:09:54.493 | [3/5] Fetching packages...
00:11:11.307 | [4/5] Linking dependencies...
00:11:11.309 | warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.7.0" has unmet peer dependency "@strapi/design-system@1.6.3".
00:11:11.309 | warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.7.0" has unmet peer dependency "@strapi/icons@1.6.3".
00:11:11.309 | warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.7.0" has unmet peer dependency "styled-components@5.3.3".
00:11:11.319 | warning "@strapi/strapi > @strapi/admin > @strapi/design-system > @uiw/react-codemirror > codemirror > @codemirror/autocomplete@6.9.0" has unmet peer dependency "@lezer/common@^1.0.0".
00:11:30.381 | [5/5] Building fresh packages...
00:11:32.330 | success Saved lockfile.
00:11:32.336 | Done in 99.45s.
00:11:32.755 |  
00:11:32.756 | > my-project@0.1.0 build
00:11:32.756 | > strapi build
00:11:32.756 |  
00:11:34.376 | Starting the compilation for TypeScript files in /vercel/path0
00:11:35.985 | **/bin/sh: hostname: command not found**
00:11:36.051 | Building your admin UI with development configuration...
00:11:36.592 | [info] [webpackbar] Compiling Webpack
00:11:51.467 | [success] [webpackbar] Webpack: Compiled successfully in 14.87s
00:11:53.152 | Admin UI built successfully
00:11:53.393 | Build Completed in /vercel/output [2m]
00:11:53.549 | Deploying outputs...
00:11:55.576 | Deployment completed
00:12:09.067 | Uploading build cache [52.46 MB]...
00:12:10.689 | Build cache uploaded: 1.621s

**Comment by hugonasciutti** [comment]
I am getting this error message too, I am using with `NX`, I do not know yet if is some `node_module` executing `hostname` or `Vercel` the problem.

It goes away when I redeploy manually.

![image](https://github.com/strapi/strapi/assets/14843959/fd715f44-f9dc-426e-ac8f-8cd8d0ad64ea)

**Comment by AvinashVinod** [comment]
<html>
<body>

Running build in Washington, D.C., USA (East) – iad1
--
18:30:15.954 | Cloning github.com/AvinashVinod/Avidmart-Backend (Branch: main, Commit: b805d8f)
18:30:16.553 | Cloning completed: 598.929ms
18:30:16.652 | Previous build cache not available
18:30:16.875 | Running "vercel build"
18:30:17.420 | Vercel CLI 33.0.1
18:30:18.126 | Warning: Detected "engines": { "node": ">=18.0.0 <=20.x.x" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
18:30:18.139 | Installing dependencies...
18:31:35.791 |  
18:31:35.791 | added 1276 packages in 1m
18:31:35.792 |  
18:31:35.792 | 164 packages are looking for funding
18:31:35.792 | run `npm fund` for details
18:31:35.831 | Detected `package-lock.json` generated by npm 7+
18:31:35.831 | Running "npm run build"
18:31:36.580 |  
18:31:36.581 | > api@0.1.0 build
18:31:36.581 | > strapi build
18:31:36.582 |  
18:31:38.326 | - Building build context
18:31:38.326 |  
18:31:38.354 | /bin/sh: hostname: command not found
18:31:38.403 | [INFO] Including the following ENV variables as part of the JS bundle:
18:31:38.403 | - ADMIN_PATH
18:31:38.403 | - STRAPI_ADMIN_BACKEND_URL
18:31:38.403 | - STRAPI_TELEMETRY_DISABLED
18:31:38.414 | ✔ Building build context (89ms)
18:31:38.415 | - Building admin panel
18:31:38.415 |  
18:31:55.339 | ✔ Building admin panel (16926ms)
18:31:55.432 | Build Completed in /vercel/output [2m]
18:31:55.518 | Deploying outputs...
18:31:56.495 |  
18:31:56.769 | Deployment completed
18:32:11.971 | Uploading build cache [56.15 MB]...
18:32:13.947 | Build cache uploaded: 1.976s


</body>
</html>

**Comment by derrickmehaffy** [comment]
We do t support running Strapi on Vercel
