### ISSUE TITLE
Copy token button error in watch mode

### ISSUE THREAD

**Issue by crissCM** [strapi/strapi#17678]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.3
- Database: PostgreSQL
- Operating system: Windows 10 Pro, 64bit
- Is your project Javascript or Typescript: Javascript 

### Describe the bug

When Strapi is started in watch mode, the API token copy button click will result in an error screen.

### Steps to reproduce the behavior

1. Run Strapi in watch mode: `strapi develop --watch-admin`.
2. Go to [http://localhost:8000/admin/](http://localhost:8000/admin/) in the browser.
3. Click on Settings -> API Tokens -> Create new API Token.
4. Fill in the required data and then click on the Save button.
5. Click on the 'Copy to clipboard' button.
6. See error.

### Expected behavior

The token copy should not cause any errors.

### Screenshots
1. Go to the token creation page:
![Screenshot_9](https://github.com/strapi/strapi/assets/78145538/3de82072-f84f-4289-85bb-a2868dc8ed61)

2. Fill in the required data and click Save:
![Screenshot_7](https://github.com/strapi/strapi/assets/78145538/235ccdd2-9d87-486b-8a97-f092e8f83095)

3. Click the copy icon:
![Screenshot_5](https://github.com/strapi/strapi/assets/78145538/e6e370cf-6236-4475-8871-cdcea9087e09)

4. See error:
![Screenshot_6](https://github.com/strapi/strapi/assets/78145538/968856b5-ea74-44a8-8970-4f5f74535da5)

### Additional context

This error only occurs in watch mode.

**Comment by derrickmehaffy** [comment]
Please update to the latest version as I believe we have already patched this, see: https://github.com/strapi/strapi/issues/17187

Marking as closed for now but if the issue still happens let us know and we can reopen this.
