### ISSUE TITLE
Cannot Start Project In Development Mode

### ISSUE THREAD

**Issue by MWalid** [strapi/strapi#1768]
**Informations**
- **Node.js version**: v10.9.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: monogodb v4.0.1
- **Operating system**: macOS High Sierra

**What is the current behavior?**
Trying to start the strapi in plugin development mode, getting an error: 

`[2018-08-19T21:56:26.626Z] error ENOENT: no such file or directory, stat '/path/to/my/project/plugins/content-manager'`

**Steps to reproduce the problem**

```
$ strapi new project --dev
$ cd project/admin && npm start
$ cd ../ && strapi start
```

**What is the expected behavior?**
The project should start in plugin develoment mode

**Suggested solutions**
?

**Comment by soupette** [comment]
Hi @MWalid did you follow the [CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#setup-development-environment) recommendations?

**Comment by MWalid** [comment]
Hi @soupette,

I followed the [quick start guide](https://strapi.io/documentation/plugin-development/quick-start.html), will try once again with the contributing guide and let you know.

**Comment by soupette** [comment]
As a reminder here's my workflow:

1. Create a repository folder and clone strapi : `mkdir repositories && cd repositories && git clone git@github.com:strapi/strapi.git`
2. Install strapi `cd repositories/strapi && npm run setup:build`
3. In another folder create a `dev` app `mkdir sandbox && cd sandbox && strapi new my-app --dev`
4. Usually I remove the `settings-manager` in dev mode so webpack doesn't complain : `cd my-app && rm -r plugins/settings-manager`;
5. Launch the servers : `cd my-app && strapi start`
6. In another terminal window : `cd my-app/admin && npm start`

**Comment by redni** [comment]
There is no need to create a new Issue so I will post it here. Yesterday I followed this workflow with the recommended `npm run setup` instead of` npm run setup:build`. 

The effect is that the `strapi start` in the main application directory works very well while `npm start` in the admin directory hangs on `building...` checked on 2 separate machines. Server and laptop. Can not build on any of them.

**Comment by MWalid** [comment]
Hi @soupette, the contribution guide worked for me, thank you.

When I followed the quick start guide I thought I should start from [plugin development setup section ](https://strapi.io/documentation/plugin-development/quick-start.html#plugin-development-setup) since I wanted to create a plugin (not to contribute to the core). It's more clear in the contributing guideline that I have to follow all steps from the beginning.

**Comment by MWalid** [comment]
@redni it builds with `npm run setup` it hangs little bit then the link opens ... 

However I still have the following error in the terminal (although everything seems to be working just fine)

```
2018-08-21 12:52 node[10894] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by derrickmehaffy** [comment]
@MWalid check which version of Jest you have installed: `npm -v jest`

In my case `6.2.0`

**Comment by MWalid** [comment]
@derrickmehaffy it's the same version as yours,
I just realised that the webpack is not rebuilding the project on file change.
So to see my changes I had to stop the development server and then run it again ... `cd admin && npm start`

**Comment by soupette** [comment]
@MWalid webpack is watching a lot of files until I fix the FS error I recommend to delete some plugins like the `settings-manager` and if you don't need it the `content-type-builder` then if you relaunch `webpack` you should have the hot reload working again.

**Comment by MWalid** [comment]
@soupette I removed both, now no errors in the terminal, however still no hot reloading, webpack doesnt rebuild when my plugin files changed ...

**Comment by MWalid** [comment]
Hi @soupette, any updates how I can get the hot reloading to work?

**Comment by soupette** [comment]
@MWalid the hot reloading is not implemented in strapi admin meaning that you'll only see your modifications when you add something in the render method. Otherwise you need to reload the view yourself
