### ISSUE TITLE
REST API cannot be used inside custom plugin

### ISSUE THREAD

**Issue by crissCM** [strapi/strapi#17688]
### Required System information

Node.js version: v18.16.0
NPM version: 9.5.1
Strapi version: 4.11.3
Database: PostgreSQL
Operating system: Windows 10 Pro, 64bit
Is your project Javascript or Typescript: Javascript

### Describe the bug

When you try to make a POST/GET request from a plugin either with **fetchClient** or **request** it will fail and even log you out from the admin.

### Steps to reproduce the behavior

1. Create a plugin.
2. In the plugin frontend code file implement a POST/GET request using the post method of the fetchClient to a Strapi backend endpoint like `/api/yourPluralEntity`.
3. Run your HTTP request.
4. You will see a **401 (Unauthorized)** error message in the console and you get logged out from Strapi. 
The console error message says: `POST http://localhost:1337/api/yourPluralEntity 401 (Unauthorized)`
It doesn't help if I make the endpoints public or authorized. The request should work either way.

### Expected behavior

A POST or GET request to a Strapi backend endpoint should run successfully.

### Code snippets

```js
import { useFetchClient } from '@strapi/helper-plugin';

const { get, post } = useFetchClient();

post('/api/yourPluralEntity', {
  data: {
    entityValue: 1
  }
})
  .then((response) => {
    console.log(response);
  })
  .catch((error) => console.log(error));
```

### Additional context

The same problem occurs with request() from the helper-plugin as well.
It used to work perfectly in Strapi v3.

**Comment by derrickmehaffy** [comment]
This is normal as admin JWTs cannot hit the content-api routes as you need a content-api token issued either by the users-permissions plugin or the API tokens. Alternatively you can disable auth entirely but plugins with an admin panel component should have admin APIs defined and not use the content-api.

Marking this as closed as the logic is intended.

**Comment by derrickmehaffy** [comment]
Follow up to this, the way it worked in v3 was not something we wanted but couldn't change because it would have been breaking, it was a massive security issue that it worked in v3 and it's why we removed it.
