### ISSUE TITLE
Populate * is not return full data

### ISSUE THREAD

**Issue by lchhieu** [strapi/strapi#17696]
`?api/homepage?populate=*` only return all relations of level 1. Is there any way to return for all levels?

**Comment by sjoukedv** [comment]
https://docs.strapi.io/dev-docs/api/rest/populate-select#populate-2-levels

**Comment by dennism501** [comment]
@lchhieu you have to specify the level when populating as @sjoukedv has mentioned https://docs.strapi.io/dev-docs/api/rest/populate-select#populate-2-levels. There currently isn't a default method of returning all the levels, there would a be performance issue with that.

**Comment by derrickmehaffy** [comment]
Closing this in favor of https://feedback.strapi.io/developer-experience/p/add-additional-glob-population-options
