### ISSUE TITLE
can not create project

### ISSUE THREAD

**Issue by mukhlim** [strapi/strapi#1769]
Informations

    Node.js version: v10.9.0
    npm version: 6.4.0
    Strapi version: 3.0.0-alpha.13.1
    Database: monogodb v4.0.1
    Operating system: windows 10 enterprise

What is the current behavior?
cli sleep about 10 seconds before exit when specifying database.

![image](https://user-images.githubusercontent.com/6600262/44314749-55443700-a446-11e8-9766-b61c484202b8.png)

Steps to reproduce the problem
$ strapi new project project1

- fyi, i have accidentally installed stable release of strapi before alpha one (alpha->stable->alpha again)

What is the expected behavior?
- able to create project

**Comment by derrickmehaffy** [comment]
There are known issues with Windows, please use WSL or a Linux VM. The Strapi team is working on better Windows support.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues.
Please check https://github.com/strapi/strapi/issues/1281
