### ISSUE TITLE
ReferenceError: inputStep is not defined

### ISSUE THREAD

**Issue by Smith-Smith** [strapi/strapi#17698]
Node.js version: 16.20.2
NPM version:8.19.4
Strapi version:4.12.5
Database: Postgres
Operating system: Windows
Project Javascript or Typescript: Javascript

After updating strapi to from v4.9.1 to 4.12.5 am getting error : Woops! Something went wrong. Please, try again.
when I check in console the error states as follow: ReferenceError: inputStep is not defined

This error appears when I click on any content in a collection type

Steps to reproduce the behavior

1. Go to Collection Type
2. Click on any of the collections
3. 
<img width="329" alt="image" src="https://github.com/strapi/strapi/assets/120161708/949e1878-7314-4c3e-8e2f-861588d793f5">

<img width="334" alt="image" src="https://github.com/strapi/strapi/assets/120161708/da7878f6-5592-46cc-aacb-895de6811751">

**Comment by dennism501** [comment]
Hi @Smith-Smith did you delete your `.cache && node_modules` when updating?
