### ISSUE TITLE
UI issue "No entry yet. Click on the button below to add one"

### ISSUE THREAD

**Issue by jeffski** [strapi/strapi#17706]
This isn't really a bug, but UI observation which could do with some polish to avoid confusion. When you have an optional component on a page while editing it looks like this:

![image](https://github.com/strapi/strapi/assets/1064199/8ab359bc-226e-4fcb-964d-68b550de0881)

The text is "No entry yet. Click on the button below to add one" - but there is no button below. Perhaps all it needs to say is ""No entry yet. Click to add one".

**Comment by rishabhdwivedii** [comment]
@derrickmehaffy Can I work on this issue?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Can I work on this issue? 

You don't need to ask, we don't assign issues outside of our organization, anyone can open a PR

**Comment by rishabhdwivedii** [comment]
Sorry for bothering you, I've opened the PR.
