### ISSUE TITLE
knex: Required configuration option 'client' is missing.

### ISSUE THREAD

**Issue by abdulhadi240** [strapi/strapi#17741]
HELLO ,  i am receiving an error when deploying strapi to render . ever thing goes fine until npm start and it shows the following error
![Screenshot 2023-08-22 134539](https://github.com/strapi/strapi/assets/70109681/b08d4a08-ea4d-456b-accd-240aa99a17ec)
please guide what should i do next.

**Comment by byoungd** [comment]
I have this problem too and don't know how to solve.
