### ISSUE TITLE
Upload Plugin route /files always returns 404

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1774]
**Informations**
- **Node.js version**: v10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: 10.2.17-MariaDB
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

When uploading a file either directly in the plugin menu, POST request, or via a model relation, you can grab the file information from the model. However if you attempt to use `localhost:1337/files/ID` you will always get a 404 message

**Steps to reproduce the problem**

Use Mysql and create a model that contains a media field, upload a picture of file and query the model you should get the proper response with relation data, however you try and GET the same ID at `/files/` you will get a 404 error.

**What is the expected behavior?**

`/files` should also give the proper data (If you have your permissions setup correctly, and I do in this case)

**Suggested solutions**

Best guess per @Aurelsicoko the error falls in this file: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/config/queries/bookshelf.js

**Comment by lauriejim** [comment]
@derrickmehaffy The route you have to try is `/upload/files`, the plugin name prefix is missing.
https://github.com/strapi/strapi/issues/1765

**Comment by derrickmehaffy** [comment]
@lauriejim you are correct thank you. FYI this should be be documented, I'll take a look at making a PR on the guide for the upload plugin.
