### ISSUE TITLE
Wrong types in createCoreService

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#17757]
### Required System information

- Node.js version: 16
- Strapi version: 4.12.5
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

We just updated from 4.9.x to the latest 4.12.5 and it seems like the createCoreService function has wrong types.

I got a services that should return a transformed version of the results.
The types expect to to return an array of results in the find functions, but the route only works when I return an object with results and the pagination (like it says in the docs).

Here is an example where findOne throws this error:
```
Type '(params: any) => Promise<{ results: any; pagination: any; }>' is not assignable to type '(params: object) => unknown[] | Promise<unknown[]>'.
  Type 'Promise<{ results: any; pagination: any; }>' is not assignable to type 'unknown[] | Promise<unknown[]>'.
    Type 'Promise<{ results: any; pagination: any; }>' is not assignable to type 'Promise<unknown[]>'.
      Type '{ results: any; pagination: any; }' is missing the following properties from type 'unknown[]': length, pop, push, concat, and 31 more.
```

No type error but not working:
```ts
export default factories.createCoreService('api::foo.bar', {
  async find(params: any) {
    const { results } = await super.find(params);
    return results.map(page => transformResults(page));
  },
});
```

Type error but working
```ts
export default factories.createCoreService('api::foo.bar', {
  async find(params: any) {
    const { results, pagination } = await super.find(params);
    return { results: results.map(page => transformResults(page)), pagination };
  },
});
```

### Steps to reproduce the behavior

1. Create a new API route with a service similar to the first one
2. Test the route. It will always return 404
3. Change the API route to the second example and add ts-ignore to ignore the error
4. Test the route. It will work as expected.

**Comment by AdrianFahrbach** [comment]
I compared find to findOne in my original text, which doesn't really make sense since they behave differently.
I adjusted that to make the issue easier to understand.

**Comment by folkscreative** [comment]
4.12.5 also having an issue with types on createCoreService. Here I've added a content type in the local admin, then it crashes and can't build because of type error.

<img width="1196" alt="image" src="https://github.com/strapi/strapi/assets/82582444/665e00bf-ef34-4094-ae19-07395fe98057">

**Comment by AdrianFahrbach** [comment]
I think with the recent Strapi updates this is probably not relevant anymore since the types changed a lot.
