### ISSUE TITLE
Relation field

### ISSUE THREAD

**Issue by Mourad-Ouerghi** [strapi/strapi#17761]
## Bug report

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.12.6
- Database: postgres
- Operating system: windows
- Is your project Javascript or Typescript: javascript

### Describe the bug

relation field can be overridden with just text

### Steps to reproduce the behavior

1. Go to a relation field 
2. You can see that you can write text beside choosing from predefined values which can cause a lot of errors and that's what happened in our case

**Comment by derrickmehaffy** [comment]
That is both not possible and provides no context, that text field is for searching only and it is not possible to save that as it would be throwing database errors before even letting it save.

No reproduction steps provided or context provided.
