### ISSUE TITLE
JSON field breaks Content Manager entry view

### ISSUE THREAD

**Issue by esiao** [strapi/strapi#17764]
### Required System information

- Node.js version: 18.17.0
- NPM version: Yarn 1.22.19
- Strapi version: 4.12.6
- Database: PostgreSQL
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am unable to access the entries in my Content Manager as soon as there is a JSON field featured.
I get the following error "Woops! Something went wrong. Please, try again."

Looking at the console I have this error:
```
Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at w (main.d00fd8d1.js:5444:19590)
    at w (main.d00fd8d1.js:5444:19169)
    at dh (main.d00fd8d1.js:5444:19783)
    at r6.resolve (main.d00fd8d1.js:5444:18247)
    at ja.create (main.d00fd8d1.js:5444:27374)
    at main.d00fd8d1.js:5458:33268
    at Fo (main.d00fd8d1.js:4380:25362)
    at V1 (main.d00fd8d1.js:4380:44240)
    at h1 (main.d00fd8d1.js:4380:42976)
    at Ge (main.d00fd8d1.js:4380:41993)
```

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Add a JSON Field to a Single or Collection Type
3. Attempt to edit or create a new entry

### Expected behavior

I should be able to see my JSON field.

### Additional context

Inspecting the error and using `yarn list --pattern codemirror` I was able to verify there are two different versions installed:
- `codemirror@6.0.1`: @strapi/plugin-i18n
- `codemirror5@5.65.14`: @strapi/admin

I didn't have this issue before upgrading and even downgrading doesn't seem to have made it go away. The data is present in my database and manipulating it works, it's just the display that doesn't.

Adding a JSON field to any of my existing entries also breaks their display.
Cleaning up node_modules and yarn.lock followed by reinstalling the dependencies didn't work.

Removing the JSON field from my Content Type allows it to display again properly.

**Comment by esiao** [comment]
Upgrading to 4.13.1 seems to have resolved the issue.

**Comment by Throttle** [comment]
The issue is still reproduced: version v4.14.6

**Comment by philohelp** [comment]
Same here with 4.16.2. I had to delete & rebuild the yarn.lock. Codemirror fantasy I guess.
