### ISSUE TITLE
Creating relation fields fail because of index name truncating

### ISSUE THREAD

**Issue by philippsteinberg** [strapi/strapi#17777]
### Required System information

- Node.js version:  18.12.1
- NPM version: 9.2.0
- Strapi version: 4.12.6
- Database: postgres
- Operating system: windows
- Is your project Javascript or Typescript: typescript

### Describe the bug
When I add an relation field to a component and the component and collection field name is very long the restart fails with the following issue

create index __  - relation ___ already exists

I assume the source of the issue is the postgres behaviour to truncate index names longer than 63 chars described here https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes

If I understand it correct strapi creates for relation fields two index on the db they end with:  
- _fk
- _inv_fk

When the overall index name is to long the endings are removed by the trucating and strapi tries to create two index with the same name.

### Steps to reproduce the behavior

1. Create a new collection with the name: test-collection-name
2. Create a new component with the name: my-test-component 
3. Add a rellation field to the component which links to the previous created collection
4. Save => the restart will not work and the issue will be shown in the command line
5. See error

### Expected behavior
It should be able to create relations no mather how long the collection or component names are.

**Comment by derrickmehaffy** [comment]
Duplicate https://github.com/strapi/strapi/issues/13117
