### ISSUE TITLE
`@strapi/data-transfer@4.12.6` has incorrect peer dependency `@strapi/strapi@4.12.4`

### ISSUE THREAD

**Issue by BorysShulyak** [strapi/strapi#17792]
### Required System information

- Node.js version: v18.17.0
- NPM version: v9.6.7 
- PNPM version: v8.6.10
- Rush version: v5.94.1,
- Strapi version: v4.12.6
- Database: Postgres
- Operating system: MacOS Ventura 13.0
- Is your project Javascript or Typescript: JS

### Describe the bug

`@strapi/data-transfer@4.12.6` has incorrect peer dependency `@strapi/strapi@4.12.4` that blocks the upgrading on the `@strapi/strapi@4.12.6` version due to failing on `peerDependencies`

### Steps to reproduce the behavior

1. Set up Strapi v4.12.6 project using rush.js monorepo or simply in `strict-peer-dependency` mode.
2. Run `rush install` command or install the dependencies using the package manager directly.
3. Get the following error:
```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

../../cms/strapi
└─┬ @strapi/strapi 4.12.6
  └─┬ @strapi/admin 4.12.6
    └─┬ @strapi/data-transfer 4.12.6
      └── ✕ unmet peer @strapi/strapi@4.12.4: found 4.12.6

hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
```

### Expected behavior

There should be no error with peerDependencies, on the installation phase.

### Screenshots
![Issue Image](https://github.com/strapi/strapi/assets/55171497/e047ef55-126f-4274-91e5-ad96e65d6184)

### Related Issues
- [@strapi/data-transfer@4.12.1" has incorrect peer dependency "@strapi/strapi@4.11.5" #17619](https://github.com/strapi/strapi/issues/17619)

**Comment by joshuaellis** [comment]
@innerdvations any reason you didn't do `^4.X.X` (whenever we released data-transfer)? :)

**Comment by innerdvations** [comment]
I think it was just a mistake. I've got this https://github.com/strapi/strapi/pull/17677 to fix it

**Comment by innerdvations** [comment]
This has now been fixed on main
