### ISSUE TITLE
New content type: repeatable group of fields

### ISSUE THREAD

**Issue by kapik** [strapi/strapi#1779]
**What is the expected behavior?**

Hi 👋 !
Have you considered adding a field type to repeat a group of fields?
For example, to have an article with steps and display several fields for each step.
[Prismic.io](https://user-guides.prismic.io/browse-documents-and-edit-content/editing-content/repeatable-elements-in-a-group) has this type of field and it's really top !

Thanks for your reply  😄

**Comment by derrickmehaffy** [comment]
@kapik This is just a standard model? Looks like there is a few string fields, a web field, and an image field. All of which can be done currently with Strapi?

**Comment by kapik** [comment]
@derrickmehaffy All fields in the groups are standard but you can repeat the group as many times as you want.
We can't have this kind of fields (group) with Strapi (or maybe I missed something).

**Comment by derrickmehaffy** [comment]
@kapik I think I'm missing the point here, can you provide a better example (That link and its picture is way too small resolution).

**Comment by kapik** [comment]
@derrickmehaffy of course :) I think I understood your misunderstanding.

I did an exemple on Prismic: I would like to have a content type to explain how to assembly something.
So my main content type is called: "assembly instructions" (like blog post).
This is the definition of this type: 

![2018-08-21_21-26-38](https://user-images.githubusercontent.com/511247/44424570-c93b2800-a589-11e8-83cc-413e94bb4a97.png)

1. Title of this assembly instructions
2. Description of this assembly instructions
3. Step who contains title, description and image => This group of fields is repeatable

And if I create a new "assembly instructions" (like a new post article), I can have several step.
Like this: 

![2018-08-21_21-27-50](https://user-images.githubusercontent.com/511247/44424650-09020f80-a58a-11e8-82ef-d3cd0cdcd966.gif)

I hope my explanations are clear.
Do you understand ? 😃 
This kind of behaviors is not possible with Strapi I think

**Comment by derrickmehaffy** [comment]
@kapik this just looks like a relationship.

You would create the first model in this case:

* Title
* Description

Then you would add a `oneToMany` relationship to the child model which would have:

* Step Title
* Step Description
* Step Image (which itself is a relationship to the upload plugin)

This is pretty standard CMS stuff, adding something like this all contained in a single model would be complex and honestly far more limiting than just using relationships.

**Comment by kapik** [comment]
@derrickmehaffy I understand your point. But in this case, we considere that each step can be reused and the main model is friendlyless (because we have to create each step separately).

**Comment by kapik** [comment]
@derrickmehaffy I have tested with Strapi and you right, we can do this but it take long time and there is to much navigation steps.
Thx @lauriejim 🙂  I am following this feature with great attention 🚀

**Comment by Aurelsicoko** [comment]
@kapik You're not the first one to ask about this feature! We could certainly add this in the future, we are open to merging a PR if you have enough time to develop it.

@derrickmehaffy Do you remember the recipe's example? It's almost the same thing in this case. You don't want to create a relationship because it's too long and not necessary. You just want to add multiples entries inside a field.

For example, I have a field `Ingredients`, it will be an array of ingredients. Each ingredient has a name and a picture. The repeater field allows you to do that easily 👍

**Comment by derrickmehaffy** [comment]
@Aurelsicoko Ah yeah hadn't really thought about that but I suppose it makes sense :stuck_out_tongue:

**Comment by Aurelsicoko** [comment]
I'm closing this issue because we'll add this feature soon. Please give me more insights about your needs on Product Board (https://portal.productboard.com/strapi/c/24-list-components-repeatable-field).

**Comment by smakman** [comment]
Board says Q1 2019, any specific release date planned?

**Comment by Aurelsicoko** [comment]
@smakman At the end of Q1, we should start the development at the beginning of March.

**Comment by jamesgorrie** [comment]
@Aurelsicoko this is a really important feature - when the work starts, is it going to be internal, or will there be input from the community required?

**Comment by Aurelsicoko** [comment]
Mostly internal, but we will share a prototype with the core contributors. This feature is too complex to be developed by someone in the community without working with us fulltime.

**Comment by jasonday** [comment]
Status?

**Comment by Aurelsicoko** [comment]
@jasonday We are currently developing the feature. The groups & repeatable fields will look like this 

👇👇👇

![image](https://user-images.githubusercontent.com/4144726/61222370-dcfbf980-a71a-11e9-98c6-b8b61eb23b87.png)

**Comment by t1gu1** [comment]
Could we use a repeatable fields in a repeatable fields? 
That would be perfect!

If not, could we see that feature in a V2 of The groups & repeatable fields?

**Comment by lauriejim** [comment]
Hello! This is not planned in the v1 of the feature.
And not planned for v2 now (no v2 is planned for now)

**Comment by LeeWalpole** [comment]
Any update on when the repeaters will be added please?

**Comment by stivmartinez** [comment]
i'm awating for this cool features :D

**Comment by jpvaillancourt** [comment]
I'm currently trying to use this new feature, but I have a bug when I click "Add Another Field" during the Group creation.

Here's the details:
![image](https://user-images.githubusercontent.com/4520731/65369972-effede80-dc21-11e9-898a-e9f95be3c7e1.png)

**Comment by jpvaillancourt** [comment]
I have just figured out I had to create the Group before adding it to the Content Type... My bad.

**Comment by theshanergy** [comment]
How does one go about appending a new group entry to a piece of content via api? do you need to send your new object along with the full existing array and PUT the whole big array, or can you just PUT the new group data only somehow?

**Comment by ben-markato** [comment]
why the group field feature is gone in V4?
