### ISSUE TITLE
GraphQL query on related data returns unrelated values

### ISSUE THREAD

**Issue by Hubel** [strapi/strapi#178]
To get a quick impression of **strapi** I tried out a simple set up of the two models _City_ and _Country_. See the [settings.json](https://github.com/strapi/strapi/files/711004/models.zip)-files attached.
There is a Many-to-One relation between _City_ and _Country_ specified:
![image](https://cloud.githubusercontent.com/assets/10436633/22020906/e6c49fbc-dcba-11e6-800a-cedae2a01d7c.png)

The following data is inserted:
**Countries**
1. Deutschland
2. Belgien

**Cities with Country**
1. Stuttgart, Deutschland
2. Brüssel, Belgien
3. München, Deutschland

Querying the countries via REST is fine, ie. it results in Brussels belonging to Belgium and Stuttgart and Munich belonging to Germany.

**But for the GraphQL query**
![image](https://cloud.githubusercontent.com/assets/10436633/22021201/2ae2d794-dcbc-11e6-831d-76c7b67b09cc.png)
**all 3 cities are listed in each country**:
![image](https://cloud.githubusercontent.com/assets/10436633/22021213/3a1ddf74-dcbc-11e6-8fa4-4d44964099c5.png)

**Node.js version**: 5.9.1
**npm version**: 3.7.3
**Strapi version**: 1.5.4
**Operating system**: Windows 10

Maybe this is related to #73.

**Comment by Aurelsicoko** [comment]
@Hubel Thanks for pointed this out! It seems related to the https://github.com/strapi/strapi/issues/73 but it's has been fixed https://github.com/strapi/waterline-graphql/commit/21b4ab3715374f0ba8104bf74df99bdd8b1a3b07.

I will try to reproduce the issue and fix this again, tomorrow morning.

**Comment by lunchboxer** [comment]
I can confirm the same problem. I made a new strapi server with two models: category and thing. Things have a many-one relationship with category.

this query:
```
query {
  categorys {
    name
    thing {
      name
    }
  }
}
```

returns this response:
```
{
  "data": {
    "categorys": [
      {
        "name": "animal",
        "thing": [
          {
            "name": "table"
          },
          {
            "name": "chair"
          },
          {
            "name": "cabinet"
          },
          {
            "name": "cat"
          },
          {
            "name": "dog"
          },
          {
            "name": "pig"
          }
        ]
      },
      {
        "name": "furniture",
        "thing": [
          {
            "name": "table"
          },
          {
            "name": "chair"
          },
          {
            "name": "cabinet"
          },
          {
            "name": "cat"
          },
          {
            "name": "dog"
          },
          {
            "name": "pig"
          }
        ]
      }
    ]
  }
}
```
You can see that pigs are listed as both furniture and animals, same with all the things. I did nothing but start a new app and add these two api through studio.strapi.io then make the query.

Versions:
Node - 8.6.0
npm - 5.4.2
strapi - 1.6.4

**Comment by Aurelsicoko** [comment]
@lunchboxer It seems that there is a real issue here. We are not maintaining the v1 except for critical issues (security). However, we are still accepting PRs and we are able to publish the patches very quickly.

If you have time, you can make a PR on [this repository ](https://github.com/strapi/waterline-graphql)to fix that issue.

**Comment by lunchboxer** [comment]
Does that mean that this issue isn't present on v3. I couldn't test it as I was unable to get v3 up and running and gave up immediately

**Comment by Aurelsicoko** [comment]
@lunchboxer For the moment, we don't support GraphQL on v3. However, we will provide a `strapi-plugin-graphql` by the end of the year.
