### ISSUE TITLE
Make managing permissions per created item possible

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1780]
**What is the expected behavior?**

Simplest example: if you were to build a doodle clone, you wouldn't be able to limit the userbase to only edit that one poll they created. Right now as the situation in strapi is, once you are authenticated to update/delete/create one type of a model, you can edit the model of anyone.

**Requirements**

Be able to
- Make an authenticated user own a created item
- Make that original author able to add or remove collaborators (multiple authors) to one created item.
- Check if users have permissions to edit a specific item. (API! - right now the permissions api is unusable)

**Proposal**

Right now, what I'm doing, is that I add an `author` relation (linking to `user`)
It becomes more complex if you have a tiered author system. So one field for the original poster and one for collaborators. 
This could work in a similar fashion how the `created_at` and `updated_at` base fields work. Just that those should not be hidden and possible to set via API. (at least the collaborators, author should be automatically generated)

**Comment by lauriejim** [comment]
I think you are talking about this issue - https://github.com/strapi/strapi/issues/624
