### ISSUE TITLE
Strapi `4.12.6` - Custom Local Host - Admin Panel Hangs after Login

### ISSUE THREAD

**Issue by dgrebb** [strapi/strapi#17807]
### Required System information

```bash
❯ npm run strapi -- report --all

> my-project@0.1.0 strapi
> strapi report --all

Launched In: 190 ms
Environment: development
OS: darwin-arm64
Strapi Version: 4.12.6
Node/Yarn Version: npm/9.6.7 node/v18.17.1 darwin arm64 workspaces/false
Edition: Community
Database: sqlite
UUID: 9e70c041-c8f3-4046-aaab-de6e3cdde4e0
Dependencies: {
  "@strapi/strapi": "4.12.6",
  "@strapi/plugin-users-permissions": "4.12.6",
  "@strapi/plugin-i18n": "4.12.6",
  "better-sqlite3": "8.5.0"
}
Dev Dependencies: {}
```

- Operating system: macOS Ventura 13.5.1
- Is your project Javascript or Typescript: JavaScript
  - note: this is a base install

### Potential `AuthenticatedApp` Regression

In Strapi `4.12.6`, the admin panel does not initialize/load using a custom local host.

### Steps to reproduce the behavior

1. set up a host entry in `/etc/hosts` eg `127.0.0.1       strapi.dev`
2. run the Strapi installation script: `npx create-strapi-app@latest my-project —quickstart`
3. stop the Strapi process
4. open the project and edit/save:
  - `File: .env Line 1: HOST=strapi.dev`
  - `File: config/server.js Line 2:   host: env(‘HOST’, ‘strapi.dev’),`
5. `npm run build`
6. `npm run develop`
7. note application logs reflect the new host
8. enter new admin account credentials
9. click “Let’s start”
9. see the admin panel hang

### Expected behavior

After creating a user, the admin panel should load. Also, after stopping and restarting the server, the admin credentials will authenticate, and the admin panel should load.

### Screenshots

_Note: Brave blocking telemetry in the first example_

#### Account Creation

![2023-08-25 10 13 13](https://github.com/strapi/strapi/assets/445891/aca28db7-7dab-47fa-a7ec-0afe97392b45)

#### Account Login
 
![2023-08-25 10 25 40](https://github.com/strapi/strapi/assets/445891/0b8d08ae-4716-4e02-bc5f-8f93ea4f5a0d)

#### Account Login - `localhost:1337` Succeeds

![2023-08-25 10 29 44](https://github.com/strapi/strapi/assets/445891/d1377fb4-debd-4599-841d-f1b2c435b737)

#### Application Reflects Custom `host`

```bash
Admin UI built successfully
❯ npm run develop

> my-project@0.1.0 develop
> strapi develop


 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Fri Aug 25 2023 10:10:32 GMT-0400 (Eastern Dayl… │
│ Launched in        │ 478 ms                                           │
│ Environment        │ development                                      │
│ Process PID        │ 36402                                            │
│ Version            │ 4.12.6 (node v18.17.1)                           │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
└────────────────────┴──────────────────────────────────────────────────┘

 Actions available

One more thing...
Create your first administrator 💻 by going to the administration panel at:

┌──────────────────────────────┐
│ http://strapi.dev:1337/admin │
└──────────────────────────────┘

[2023-08-25 10:10:36.618] http: GET /admin (12 ms) 200
[2023-08-25 10:10:36.747] http: GET /admin/project-type (13 ms) 200
[2023-08-25 10:10:36.813] http: GET /admin/init (3 ms) 200
[2023-08-25 10:13:15.688] http: POST /admin/register-admin (101 ms) 200
[2023-08-25 10:13:15.725] http: GET /i18n/locales (13 ms) 200
[2023-08-25 10:13:15.746] http: GET /admin/users/me/permissions (18 ms) 200
[2023-08-25 10:13:15.750] http: POST /admin/renew-token (2 ms) 200
[2023-08-25 10:13:15.750] http: GET /admin/information (23 ms) 200
[2023-08-25 10:13:15.755] http: GET /admin/users/me (24 ms) 200
[2023-08-25 10:13:15.763] http: GET /admin/telemetry-properties (6 ms) 200
```

### Additional context

- no errors in application logs — indicates client issue
- happens in both production and development modes
- does _not_ happen in higher environments (only local)
- appears to affect Docker installs (see [this conversation](https://discord.com/channels/811989166782021633/1144212275423629322/1144212275423629322) on Discord)

#### Further Triage

- follow all reproduction steps above
- load the admin panel via `http://localhost:1337`
- if session is still active, see the admin panel load without issue
  - if session went inactive, login and see the admin panel load without issue
- setting `.env` and `server.js` back to `0.0.0.0` yields the same results
  - `File: .env Line 1: HOST=0.0.0.0`
  - `File: config/server.js Line 2:   host: env(‘HOST’, ‘0.0.0.0’),`

---

Happy to help triage! Thanks to everyone on the team and in the community for a great ecosystem 🧡

**Comment by Eventyret** [comment]
Did you set host or export host in the system btw? Asking since the step says just host but normally you want to export it

What does the output of echo $HOST

**Comment by derrickmehaffy** [comment]
Generally host should not be a domain.

Can you please try setting the server URL and move the domain back to either 127.0.0.1 or 0.0.0.0

**Comment by dgrebb** [comment]
@derrickmehaffy thanks for taking a peek! After updating with `127.0.0.1`, and adding the `url` value in `server.js`, this persists.

![2023-08-25 17 51 57](https://github.com/strapi/strapi/assets/445891/e1c61c5b-69ef-409d-93d2-22b45352e772)

What has me scratching my head—I haven't touched a thing with `.env` and overall Strapi configuration in six months.

Rolling my project back to `4.12.5` fixes the issue.

**Comment by dgrebb** [comment]
Saw https://github.com/strapi/strapi/commit/fefc4a24acc60a59c00049e67a99ec1069be2add — closing for now but will reopen if it comes up again.

**Comment by derrickmehaffy** [comment]
4.12.7 is basically just an exact copy of 4.12.5, we just republished for the weekend until the team can take a look on Monday. So gonna reopen this for then.

**Comment by derrickmehaffy** [comment]
I think it was the gigantic PR that got merged that included the authenticated app changes for now we've rolled it back. 

I did mention this issue though in our internal crisis communication so the lead front end engineer should see this on Monday.

**Comment by gu-stav** [comment]
@dgrebb What browser (+version) are you using? I am very surprised you run into this issue looking at the browser-support matrix: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest

**Comment by dgrebb** [comment]
@gu-stav tested in Firefox, Chrome, and Safari. Moved to Brave for cleaner GIFs above. FWIW I'm about to fresh install my system while on vacation this week :) Will test this with zero system changes and report back.

Food for thought: `crypto.subtle.digest` has been around for a while, and this doesn't throw an error in `4.12.5` or `4.12.7`, which leads me to think it isn't browser-specific. The [changes here](https://github.com/strapi/strapi/blob/c1935e70041b440f2a78178c4a9fda79b722d1ab/packages/core/admin/admin/src/utils/uniqueAdminHash.js#L13) might be something to look at?
