### ISSUE TITLE
Maximun and minimun length is set to 0 i.e. default value

### ISSUE THREAD

**Issue by Yash-Var** [strapi/strapi#17806]
Maximun and minimun length is set to 0 i.e. default value

but when we increase the value it should not remove the zero form it.

I want to fix it . assign it to me 
[![image](https://www.linkpicture.com/q/Screenshot-from-2023-08-25-19-35-16.png)](https://www.linkpicture.com/view.php?img=LPic64e8b9b2a24b82042275265)
[![image](https://www.linkpicture.com/q/Screenshot-from-2023-08-25-19-35-09.png)](https://www.linkpicture.com/view.php?img=LPic64e8bd2037697152792975)

**Comment by Yash-Var** [comment]
@Sija @thomaspockrandt @albatrocity @madx check it and assign it to me.

**Comment by madx** [comment]
> @Sija @thomaspockrandt @albatrocity @madx check it and assign it to me.

I don't understand, why are you tagging me?
