### ISSUE TITLE
Some of the translations for Strapi admin panel are not working.

### ISSUE THREAD

**Issue by Kinta5** [strapi/strapi#17824]
### Required System information

- Node.js version: v19.5.0
- NPM version: 9.3.1
- Strapi version: v4.12.7
- Database: MySQL
- Operating system: Windows (local) / Almalinux9 (production)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I wanted to change locale to **'cs'**, so I added _locales: ['cs']_ to config and edited **node_modules/@strapi/admin/admin/src/translations/cs.json**. Most of them are working fine, but for example "Media Library" and it's whole section is not.  Even if I change the language back to **en** and change the translation in **en.json**, the translation is not changing.

### Steps to reproduce the behavior

1. Go to 'node_modules/@strapi/admin/admin/src/translations/en.json' // or whatever language you are using
2. Change "Media Library": "Test",
3. Rebuild and start Strapi
4. See nothing is changing

### Expected behavior

I expect to see a new translation which was inserted into the json.

### Screenshots
![image](https://github.com/strapi/strapi/assets/39614169/2b6449ba-fb0a-4789-9768-4c43f64e40d1)
![image](https://github.com/strapi/strapi/assets/39614169/2945bcde-83df-4871-a3db-3d26bd5881ba)

**Comment by yashpatel21102002** [comment]
@Kinta5 

Steps I have done

1. Gone to 'node_modules/@strapi/admin/admin/src/translations/en.json'
2. and changed "documentations" : "test" and "media-library": "test"
3. rebuild it and started strapi
4. nothing changed

ok this is unwanted behavior but I didn't understand the issue thoroughly,

If you have time can you please elaborate more?

**Comment by Kinta5** [comment]
> ok this is unwanted behavior but I didn't understand the issue thoroughly,
> 
> If you have time can you please elaborate more?

I just want to translate "Media Library" to my language (cs). But it is not possible at the moment.

**Comment by derrickmehaffy** [comment]
That's not how you should update locales, see: https://docs.strapi.io/dev-docs/admin-panel-customization#locales

Marking as closed as you shouldn't edit the node modules directly.
