### ISSUE TITLE
Server does not restart when a file is updated since the v3.0.0-alpha.13.1 migration

### ISSUE THREAD

**Issue by devaublanc** [strapi/strapi#1782]
**Informations**
- **Node.js version**: v9.10.0
- **npm version**: v5.6.0
- **Strapi version**: v3.0.0-alpha.13.1
- **Database**: Mongo
- **Operating system**: Mac OS High Sierra 10.13.3

**What is the current behavior?**
Since the migration v3.0.0-alpha.13.1. When I start the local server and I edit a file (a controller for instance) the app detect changes but the the server never restart. 
```
api_1  | [2018-08-21T20:27:55.438Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
api_1  | [2018-08-21T20:28:00.442Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
api_1  | [2018-08-21T20:28:05.456Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
api_1  | [2018-08-21T20:28:10.461Z] info File changed: /usr/src/api/api/bootstrap/controllers/Bootstrap.js
```

**Steps to reproduce the problem**

1. `strapi start`
2. Edit a file from your api

**What is the expected behavior?**

The dev server have to restart when when a file is updated

**Comment by lauriejim** [comment]
Probably be fixed with this PR https://github.com/strapi/strapi/pull/1712
