### ISSUE TITLE
Deep populating content type returns null

### ISSUE THREAD

**Issue by JelaniThompson** [strapi/strapi#1783]
9.11.2

5.6.0

v3.0.0-alpha.13

**Information**
- **Database**: MongoDB
- **Operating system**: Ubuntu

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/11928206/44430226-068ebe00-a568-11e8-8029-04c7ae8dff7e.png)

Uploaded media (audio, images, etc.) return null when they're nested in a relation. Here, tour has many toursections.

I've tried to apply the solution from Issue #877 but haven't had much luck as of yet.

![image](https://user-images.githubusercontent.com/11928206/44430766-be709b00-a569-11e8-8499-d1fb1d0b6089.png)

**Steps to reproduce the problem**
I've created a Tour content type and a Toursection content type. Tour has many Toursections. The descriptions and anything text-based aren't null, but the media is. 

**What is the expected behavior?**
To have data available where null is returned.

**Suggested solutions**
I've tried modifying the deep populating myself as that's the only solution I've been able to find but am still stuck. Any help would be appreciated!

**Comment by peckhouse** [comment]
I'm having the same issue.

**Steps to reproduce the problem**
I've created a `Casestudy` and `Client` content type.
`Casestudy` has many `Client`.
All the fields for the text, WYSIWYG, textarea are behaving correctly.
media fields from `Client` return null when calling a `Casestudy`.
from `Casestudy` :
![screen shot 2018-08-29 at 12 27 18](https://user-images.githubusercontent.com/700371/44763835-dbb7f180-ab87-11e8-8813-b9f012318cdb.png)

from `Client` :
![screen shot 2018-08-29 at 12 27 04](https://user-images.githubusercontent.com/700371/44763850-ea060d80-ab87-11e8-97a8-a66f6d4dd543.png)

**What is the expected behavior?**
To have data available where null is returned.

Is there anything I am missing?

**Comment by creativeesprit** [comment]
@peckhouse and @JelaniThompson not sure if you managed to solve this, but my scenario/solution was the following (please note I'm using Strapi v3.0.0-alpha.14):

I have `Page` and `Contentblock` content types where a `Page` has many `Contentblock`'s. Therefore I updated the fetchAll method in `api/page/services/Page.js` only. This file now looks like the following:

`fetchAll: (params) => {
    const filters = strapi.utils.models.convertParams('page', params);

    return Page
      .find()
      .where(filters.where)
      .sort(filters.sort)
      .skip(filters.start)
      .limit(filters.limit)
      .populate([{
        path: 'image' 
      }, {
        path: 'contentblocks',
        populate: {
          path: 'images'
        }
      }]);
  },`

Where `path: 'contentblocks'` is the pluralised name of the related content type and `images` is the field name inside Contentblock.

Please note that in my example I required that .populate be an array as I had another relation  (image) in my Page content type. If no other relation exists in yours, you can simple use:

`.populate({
        path: 'contentblocks',
        populate: {
          path: 'images'
        }
  })`

Hope this helps.

**Comment by Kinark** [comment]
@creativeesprit But it breaks another "related" content types.
E.g:
This is my default `api/game/services/Game.js`:
`
  fetchAll: (params) => {
    // Convert `params` object to filters compatible with Mongo.
    const filters = strapi.utils.models.convertParams('game', params);
    // Select field to populate.
    const populate = Game.associations
      .filter(ast => ast.autoPopulate !== false)
      .map(ast => ast.alias)
      .join(' ');
    return Game
      .find()
      .where(filters.where)
      .sort(filters.sort)
      .skip(filters.start)
      .limit(filters.limit)
      .populate(populate);
  },
`
I added a `console.log(populate)` to see what it returns, and it returns this:
`Screenshots MediaKit press rewards GamesListCover GameCover Logo`
However, those are media inputs I added, not related content types. And if I do what you said, all those returns null when I fetch data.

I tried to do something like this:
`
      .populate([
         populate,
        {
          path: 'rewards',
          populate: {
            path: 'Badge'
          }
        },
      ]);
`
But it didn't work :c

**Comment by creativeesprit** [comment]
@Kinark I'd need a bit more info. As I understand `Screenshots MediaKit press rewards GamesListCover GameCover Logo` are all media fields of Game.js. If that's the case, which related content type are you trying to pull in and what media fields do they have?

Thakns

**Comment by Kinark** [comment]
@creativeesprit Sure. I'm sorry if I wasn't clear enough.  

_CT = Content Type, RCT = Related Content Type_  

So, I have 2 R_(to `Games`)_CT: `press` and `rewards`.  
In `Games` CT I have many inputs, and 5 of them are media fields (`Screenshots, MediaKit, GamesListCover, GameCover, Logo`).   I don't know why, but those are returned here (along with the actual RPCs:
```
const populate = Game.associations
  .filter(ast => ast.autoPopulate !== false)
  .map(ast => ast.alias)
  .join(' ');
```  
When I fetch the data, everyhing is fine, except for the `rewards` RCT. It is successfully included, but it has a media field that returns null.  
  
That's what I'm trying to include, the media field called `Badge` from `rewards` RCT.

**Comment by creativeesprit** [comment]
Ok, try the following:

```
fetchAll: (params) => {
  // Convert `params` object to filters compatible with Mongo.
  const filters = strapi.utils.models.convertParams('game', params);

  return Game
    .find()
    .where(filters.where)
    .sort(filters.sort)
    .skip(filters.start)
    .limit(filters.limit)
    .populate([{
       path: 'Screenshots'
     }, {
       path: 'MediaKit',
     }, {
       path: 'GamesListCover',
     }, {
       path: 'GameCover',
     }, {
       path: 'Logo'
     }, {
       path:  'press'
     }, {
       path: 'rewards',
       populate: {
          path: 'Badge'
       }
     }]);
},

``` 
The reason the original Strapi code has the `const populate` is to combine these in one go instead of having to have all those objects, however it doesn't pull in related media types (the problem everyone is having).  Thinking about it, you can try having two `.populate()`'s. Haven't tested but that'd look like:

```
fetchAll: (params) => {
  // Convert `params` object to filters compatible with Mongo.
  const filters = strapi.utils.models.convertParams('game', params);
  // Select field to populate.
  const populate = Game.associations
    .filter(ast => ast.autoPopulate !== false)
    .map(ast => ast.alias)
    .join(' ');
  return Game
    .find()
    .where(filters.where)
    .sort(filters.sort)
    .skip(filters.start)
    .limit(filters.limit)
    .populate(populate)
    .populate({
        path: 'rewards',
        populate: {
           path: 'Badge'
        }
     });
},

```
I don't know enough about mongo to know whether that'd would, but worth a go.

**Comment by Kinark** [comment]
@creativeesprit Really appreciate your help! Thank you :)
I thought about the two populates and it worked, I've updated my previous answer.

Thanks again!

**Comment by creativeesprit** [comment]
@Kinark No probs!

Glad it worked.

**Comment by AndroAmater** [comment]
Hey guys,

Has anyone found a workaround with bookshelf? Any help would be greatly appreciated.

**Comment by lauriejim** [comment]
Fix media populate https://github.com/strapi/strapi/pull/2693
