### ISSUE TITLE
Author role does not have access to its assets in media library

### ISSUE THREAD

**Issue by tomasmezdej** [strapi/strapi#17840]
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.12.4
- Database: Postgres
- Operating system: Windows 10
- Is your project Javascript or Typescript: JS

### Describe the bug

Hello, i found a bug with "Author" role where you can not access your content when you upload it in media library. 
Can you please take a look on this ? Thanks

### Steps to reproduce the behavior

1. log in as superadmin
2. go to settings/Users
3. Create two users with "Author" role
4. log in as first user
5. upload image to media library
6. try to uploaded image in media library (its not there)
7. log in as second user
8. upload image to media library
9. try to access image in media library (it is not there)

### Expected behavior

Expected behavior is that when user with role "Author" uploads image into media library, he should be able to manipulate with that image

### Screenshots
logged as "Author"
![image](https://github.com/strapi/strapi/assets/78046221/773a12a5-e9de-4df9-a85a-90c81a392794)

logged as "superadmin" (image on left side was uploaded by "author")
![image](https://github.com/strapi/strapi/assets/78046221/a5da8521-a6c3-44b8-8e1a-ceb2bfce0114)

**Comment by meck93** [comment]
## Reproduction with Strapi v4.13.5
A user with role 'Author' is unable to see its own uploaded images. 

https://github.com/strapi/strapi/assets/22457755/15d7cfab-dd24-4d9e-be9d-21be2d0d08e7

## Repo
The test repository contains two users: 1x admin (test@test.ch) & 1x author (test@author.ch) -  password for both users is `Test1234!!`. 

[test-v4.13.5.zip](https://github.com/strapi/strapi/files/12591048/test-v4.13.5.zip)

## Screenshots
### Author
<img width="1668" alt="Screenshot 2023-09-12 at 23 24 11" src="https://github.com/strapi/strapi/assets/22457755/fccb6dc7-9cbe-4422-8e05-e6e8a9c9490f">
<img width="1668" alt="Screenshot 2023-09-12 at 23 24 20" src="https://github.com/strapi/strapi/assets/22457755/88706681-12c9-441a-a577-88cd07ebb3f1">

### Admin
<img width="1668" alt="Screenshot 2023-09-12 at 23 24 39" src="https://github.com/strapi/strapi/assets/22457755/c4c17ba3-5f37-413b-b269-2b7bc82497b6">
<img width="1668" alt="Screenshot 2023-09-12 at 23 24 43" src="https://github.com/strapi/strapi/assets/22457755/db727478-7432-469a-bfaa-d8d58162adc8">
<img width="1668" alt="Screenshot 2023-09-12 at 23 24 49" src="https://github.com/strapi/strapi/assets/22457755/d34e75ca-6987-40b5-865d-213050c9845c">

**Comment by meck93** [comment]
## Possible Reason
The `check` API request is failing when logged in as Author. The error message is: "permissions[0].subject must be a `string` type, but the final value was: `null`."

The API request is not made when the user is an admin. 

### Author 
<img width="1668" alt="Screenshot 2023-09-12 at 23 37 36" src="https://github.com/strapi/strapi/assets/22457755/d7b6be5b-2562-4226-87a3-38f16482d01f">


### Admin
<img width="1668" alt="Screenshot 2023-09-12 at 23 38 35" src="https://github.com/strapi/strapi/assets/22457755/3f1863b1-905a-4b64-b775-36bd6486ef2b">

**Comment by meck93** [comment]
@joshuaellis @kasonde can you have a look at this issue please? 

It is really bothering since we rely on different authors not seeing each others content due to privacy reasons.

**Comment by meck93** [comment]
@derrickmehaffy @Convly sorry for the ping but it seems the issue has been inactive/lost.

Could someone comment that you consider this an issue too? 

I'd be happy to help getting it fixed.

**Comment by meck93** [comment]
## Update

I have found a possible issue: 
1. The permission schema requires that `subject` is either a string or `undefined/absent`. See here: https://github.com/strapi/strapi/blob/a472dbc4105dfb3d20417ae98a0d40419cda4a31/packages/core/admin/server/validation/permission.js#L7-L18
2. The initial values of the permissions use `subject: null`. See here: https://github.com/strapi/strapi/blob/a472dbc4105dfb3d20417ae98a0d40419cda4a31/packages/core/upload/admin/src/constants.js#L178-L216
3. The useRBAC hook which is used in the media library passes the subject even if it is `null` (which is not allowed by the Yup Schema): https://github.com/strapi/strapi/blob/a472dbc4105dfb3d20417ae98a0d40419cda4a31/packages/core/helper-plugin/src/hooks/useRBAC.ts#L14-L81 and, especially, this part: https://github.com/strapi/strapi/blob/a472dbc4105dfb3d20417ae98a0d40419cda4a31/packages/core/helper-plugin/src/hooks/useRBAC.ts#L75-L78

@markkaylor or @joshuaellis does this help with further debugging the issue? I have seen that you've recently touched the files. 

## Possible "ugly" Workaround 

I was able to fix the issue by overriding the following code: https://github.com/strapi/strapi/blob/a472dbc4105dfb3d20417ae98a0d40419cda4a31/packages/core/admin/server/controllers/permission.js#L12-L16 with an additional mapping/filtering step that removes the `subject` entry if it is `null`. 

```typescript
   async check(ctx) {
-    const { body: input } = ctx.request;
+    const { body } = ctx.request;
     const { userAbility } = ctx.state;
 
+    // FIXME: this is a workaround as passing subject=null will throw a validation error
+    const input = {
+        permissions: body.permissions.map(p => {
+        const permission = { action: p.action }
+        if (p.subject) {
+          permission.subject = p.subject;
+        }
+        if (p.field) {
+          permission.field = p.field;
+        }
+        return permission;
+      })
+    };

```

I don't think that's a great solution, I'd rather remove the values beforehand in the `useRBAC` hook. Or, change the initial values of the permissions from `null` to `undefined` which would be allowed by Yup's schema validation. 

Let me know if I can be of any help!

**Comment by AlisonTahiri** [comment]
Same here. I just tried with v4.13.7 with a fresh install. Can confirm with the check as in the screenshot: 
![Screenshot from 2023-09-24 22-20-59](https://github.com/strapi/strapi/assets/68166032/27e62dce-116a-4a54-9c82-58dab739f120)

**Comment by AlisonTahiri** [comment]
@strapi/admin/server/validation/permission.js

I added .nullable() to the subject property and everything works fine.

`
const checkPermissionsSchema = yup.object().shape({
  permissions: yup.array().of(
    yup
      .object()
      .shape({
        action: yup.string().required(),
        subject: yup.string().nullable(),
        field: yup.string(),
      })
      .noUnknown()
  ),
});
`

**Comment by AlisonTahiri** [comment]
How about adding .nullable() to the subject property in the validation? I tried and it worked for me.

**Comment by amerikan** [comment]
@joshuaellis I just started experimenting with Strapi about a week ago, so far it's been pretty nice experience other than this issue. 😄  

I encountered the problem outlined in this issue and wanted to get more familiar with the guts of Strapi. I explored the code base a bit and noticed the Yup schema has been as it is now for a while? The solution mentioned is to just make it `.nullable()`, but since at one point that schema was working fine (which I think it was?) then something else must have broken the flow?

I don't fully understand how the RBAC is implemented, but I noticed out of the **Super Admin**, **Editor**, and **Author** roles created, **only** Author is the only one that gets `admin::is-creator` **condition** and that is why only for Author the admin front-end checks the permission via the `useRBAC` hook. It does a backend api call since it's the only one with a set `condition` value. If I comment out the `useRBAC` logic where it checks `condition` as it is doing in L57-L62, then it also starts working fine with out using `nullable()`. 

https://github.com/strapi/strapi/blob/4d6918a3fca8bb44d5c1a69f0e5ae9728833aac8/packages/core/helper-plugin/src/hooks/useRBAC.ts#L39-L96

I'm completely new to Strapi, so I'm not 100% sure of about my findings, but maybe you can give me some pointers where I can read up more on the design and implementation of the RBAC. 😅
