### ISSUE TITLE
Cannot update a richtext field after sibling deletion within dynamic components

### ISSUE THREAD

**Issue by g-lapeyre** [strapi/strapi#17858]
### Required System information

- Node.js version: v18.17.1
- NPM version: 8.19.3
- Strapi version: v4.12.7
- Is your project Javascript or Typescript: Javascript

### Describe the bug

We've faced a quite blocking crash when using dynamic components in our projet. Especially with rich texts fields causing a crash when trying to update the text after deleting a component above it.

### Steps to reproduce the behavior

1. Add 2 components in a dynamic zone, one must contain a richtext
2. Remove a component **before** the richtext one
3. Try to type in the richtext, you'll face an error _Woops! Something went wrong. Please, try again._
4. In the console there is an error `TypeError: Cannot read properties of undefined (reading 'icon')`

### Expected behavior

The richtext state should be updated with no error.

### Screenshots

![image](https://github.com/strapi/strapi/assets/60349428/12087d68-e25d-43f5-aa4e-69032ab8bdfd)
[Screencast from 30-08-2023 10:46:06.webm](https://github.com/strapi/strapi/assets/60349428/834f5979-789e-4ce9-9090-7fa46223fd10)

**Comment by prkash66** [comment]
Hii
