### ISSUE TITLE
Accidentally creating config/plugin.js vs config/plugins.js

### ISSUE THREAD

**Issue by Juksefantomet** [strapi/strapi#17868]
### Required System information
- Node.js version: 20.5.1
- NPM version: 9.8.0
- Strapi version: 4.12.7
- Database: SQLite3
- Operating system: Ubuntu 22.04
- Javascript project

### Describe the bug

After a long and very frustrating round of trying to implement aws-s3 for media library, it turned out i created config/plugin.js and not config/plugins.js

This under NO circumstances is picked up by Strapi and leads to a multitude of troubleshooting steps with no errors provided during the course of trying to implement AWS-S3.

A simple warning / error / alert regarding plugin vs plugins.js would counter this and provide the end-user with a working aws-s3 implementation.

### Steps to reproduce the behavior

1. `touch config/plugin.js`
2. npm install @strapi/provider-upload-aws-s3
3. Follow all steps and watch the entire setup continue as everything was working
4. The only way to notice something is off is that your files end up in public/uploads.
5. optional step to actually fail and get on the right track is to delete public/uploads folder.

### Expected behavior

Strapi warning: config/plugin.js detected, did you mean plugins.js?

or 

 expected config/plugins.js, found config/plugin.js - loading that instead.

### Additional context

Simply as a Quality of life there should be a pointer to counter such mistakes :smile:

**Comment by rohitPandey469** [comment]
It is config/plugins.js already

**Comment by Juksefantomet** [comment]
The issue is regarding lack of information when `not` creating the expected `config/plugins.js`.

Leading to a long troubleshooting journey with slim to no errors provided.

**Comment by derrickmehaffy** [comment]
Trust me I've been asking for us to create that file by default for a long time :D we have a WIP RFC for Strapi v5 where I believe part of the plan is to generate full config files (just commented) or move primarily to an entirely env var based config instead. TBD

**Comment by Zharkan** [comment]
@derrickmehaffy Can you take a quick look at my PR, I think I would have loved something like this, it happened to me and some other people too ?

**Comment by hccap** [comment]
fuck me, I had the same typo issue! cost me hours to find.

**Comment by innerdvations** [comment]
> Trust me I've been asking for us to create that file by default for a long time :D we have a WIP RFC for Strapi v5 where I believe part of the plan is to generate full config files (just commented) or move primarily to an entirely env var based config instead. TBD

As the highest priority issue at Strapi, we have this roadmap planned during v5:

- plugins.js generated by default
- generated config files will have comments
- env variable fallbacks for if you don't want a plugins.js config file at all
- 'plugin' will be a reserved config filename so you'll get an error if you have the wrong filename

(kidding about highest priority obviously, those are all in relation to other features we're working on, but I saw this thread and found it funny how many of them will squash this issue)

**Comment by derrickmehaffy** [comment]
fixed in v5 since we are creating this by default (I believe it was also recently added to v4 too). closing

**Comment by poldilite** [comment]
I still had the issue in Strapi 5.10.3, when creating a plugin with the sdk-plugin
