### ISSUE TITLE
Error after upgrade try do upgrade from v4.12.7 to v4.13.1 in npm run build command

### ISSUE THREAD

**Issue by rafaelmelope** [strapi/strapi#17872]
### Required System information

- Node.js version: v16.20.1
- NPM version: 8.19.4
- Strapi version: v4.13.1 
- Database: Mysql
- Operating system: Mac OS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Error after upgrade try do upgrade from v4.12.7 to v4.13.1 in npm run build command

### Steps to reproduce the behavior

Update package.json to from v4.12.7 to v4.13.1

![Screenshot 2023-08-30 at 16 23 46](https://github.com/strapi/strapi/assets/2935563/e084679f-072b-42d5-9309-5571bc9297c2)

npm install (ok)
npm run build   (error)

### Screenshots

![Screenshot 2023-08-30 at 16 20 52](https://github.com/strapi/strapi/assets/2935563/12db0f6c-ad42-4a9f-94da-cd34cf75838e)

### Code snippets

ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src'

### Additional context

➜  strapi-aresmotos git:(main) ✗ npm run build            

> whitelabel@0.1.0 build
> strapi build

Building your admin UI with development configuration...

● Webpack █████████████████████████ building (10%) 0/1 entries 69/81 dependencies 2/68 modules 28 active 
 json|/Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src/translations/zh-Hans.json

ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src'
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules
        existing directory /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom
          using description file: /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client doesn't exist
              .js
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.js doesn't exist
              .jsx
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client doesn't exist
      /Users/rafaelmelo/dev/strapi/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/dev/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in '/Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src'
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/Compilation.js:2022:28
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:817:13
    at eval (eval at create (/Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:448:22
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:689:25
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:893:8
    at /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/webpack/lib/NormalModuleFactory.js:1013:5
resolve 'react-dom/client' in '/Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src'
  Parsed request is a module
  using description file: /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/src/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/admin/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/dev/strapi/strapi-aresmotos/.cache/node_modules doesn't exist or is not a directory
      looking for modules in /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules
        existing directory /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom
          using description file: /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/package.json (relative path: .)
            using description file: /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/package.json (relative path: ./client)
              no extension
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client doesn't exist
              .js
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.js doesn't exist
              .jsx
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.jsx doesn't exist
              .react.js
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.react.js doesn't exist
              .ts
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.ts doesn't exist
              .tsx
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client.tsx doesn't exist
              as directory
                /Users/rafaelmelo/dev/strapi/strapi-aresmotos/node_modules/react-dom/client doesn't exist
      /Users/rafaelmelo/dev/strapi/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/dev/node_modules doesn't exist or is not a directory
      /Users/rafaelmelo/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

**Comment by RazvanCretu** [comment]
I also got the same issue trying to upgrade from 4.12.6 on windows

**Comment by derrickmehaffy** [comment]
Please follow this documentation: https://docs.strapi.io/dev-docs/update-version

And more specifically:
![image](https://github.com/strapi/strapi/assets/8593673/2b112577-43bf-4418-948e-de3fd6ebcf87)

**Comment by rafaelmelope** [comment]
@derrickmehaffy tks! It's work :)
