### ISSUE TITLE
Missing `schema` in `validateQuery` after upgrading to `v4.13.1`

### ISSUE THREAD

**Issue by rafiandria23** [strapi/strapi#17875]
### Required System information

- Node.js version: `v20.5.1`
- NPM version: `v9.8.1`
- Strapi version: `v4.13.1`
- Database: `PostgreSQL`
- Operating system: `macOS`
- Is your project JavaScript or TypeScript: `TypeScript`

### Describe the bug

Missing `schema` in `validateQuery` after upgrading to `v4.13.1` when trying to `findOne` and `find` a content type that has media attribute. When trying to get data from REST API, I know I need to use `?populate=*`, but when I try to query using GraphQL plugin, I get this error.

### Steps to reproduce the behavior

1. Go to GraphQL sandbox.
2. Make a query that contains the media attribute.
3. Execute the query.
4. See error.

### Expected behavior

Before upgrading to `v4.13.1`, I was using `v4.12.7`.

### Screenshots

<img width="1680" alt="Screenshot 2023-08-31 at 10 30 32 AM" src="https://github.com/strapi/strapi/assets/53303941/c8b8bc07-9516-48da-9b26-d5f7734b5040">

<img width="1680" alt="Screenshot 2023-08-31 at 10 30 50 AM" src="https://github.com/strapi/strapi/assets/53303941/05c99d37-3b94-4504-8bcd-83a918a0fdf9">

### Code snippets

I only upgraded Strapi and its related dependencies to `v4.13.1`

### Additional context

Not applicable.

**Comment by imran-hossain03** [comment]
Facing the same issue with the entity having media query.

**Comment by imran-hossain03** [comment]
The strange thing is I have downgraded to my previous version 4.12.7 but still getting the same error. Can anyone please tell me how to solve that?

**Comment by jooler** [comment]
mee toooooooooooooooooo.....

**Comment by gwynhokkers** [comment]
Having the same issue here. Can't query any UploadFileEntityResponse. Can we please have some direction here as this is blocking any work at the moment. If downgrading from 4.13.1 doesnt work, my instance is going to be a little borked too.

**Comment by gwynhokkers** [comment]
Reverting to 4.12.7 works for me. Reinstalling and running yarn build works. Can't upgrade to 4.13.1 until this is fixed or guidance is given as to what is wrong with the query, if that is the issue.

**Comment by imran-hossain03** [comment]
@gwynhokkers I tried everyway to delete build, cache, node_modules but couldn't make it work. Don't know what is wrong 😞

**Comment by gwynhokkers** [comment]
> @gwynhokkers I tried everyway to delete build, cache, node_modules but couldn't make it work. Don't know what is wrong 😞

I'm running node 18.17.1 with this in my package manager:
"@strapi/strapi": "4.12.7"

Make sure that is **not** something like "@strapi/strapi": "^4.12.7"
Using yarn as the package manager. Try deleting the node_modules and any lockfiles. Good luck!

**Comment by imran-hossain03** [comment]
My "@strapi/plugin-graphql": "4.12.7", was "@strapi/plugin-graphql": "^4.12.7".
That was causing issue after downgrading. Thank's man @gwynhokkers 😌

**Comment by lastnamearya** [comment]
I'm started facing this issue today with `4.12.0` version, not upgraded anything recently.

**Comment by PeterBowater** [comment]
Also happening here, 4.12.4.

**Comment by Convly** [comment]
Thanks for reporting this issue, we'll take a look as soon as possible.

**Comment by PeterBowater** [comment]
Downgraded to 4.12.4 and its working OK.

**Comment by pencill-ram** [comment]
Downgrading to 4.12.4 did not work for me.

**Comment by PeterBowater** [comment]
> Downgrading to 4.12.4 did not work for me.

Downgraded Strapi or "@strapi/plugin-graphql": "4.12.4" ?

Agree, Strapi downgraded to 4.12.4 won't work, you need to downgrade the graphql package, which by default is ^4.12.4, so jumped to 4.13.1 today.

**Comment by FrontendCrypto** [comment]
Same problem here. I tried downgrading until 4.12 but is not working.

**Comment by z0lo13** [comment]
Same Problem here.
Downgrading to
`"@strapi/plugin-graphql": "4.13.0",`
fixes the issue.

**Comment by unsalted** [comment]
Also not working.

**Comment by kasun-sonic-devs** [comment]
Downgraded graphql package version to 4.12.4 and It is working.
` "@strapi/plugin-graphql": "4.12.4"`
but ` "@strapi/plugin-graphql": "^4.12.4"`  version not working

**Comment by Collinvdv** [comment]
Same problem

**Comment by diacu** [comment]
For me the issue seems to be on the media files association. Any query that has an image relation fails to pass this validation.

**Comment by diacu** [comment]
I pointed in the PR where the problem is. Feel free to change it if I didn't do it properly, it's the first time opening one 😄

**Comment by gwynhokkers** [comment]
If that is the issue, and it is caused by a typo, it does make me concerned that there isn't enough testing in place.

**Comment by derrickmehaffy** [comment]
Escalating issue per our internal escalation policy as this is now impacting an EE customer. Internal TID reference: 4490

**Comment by derrickmehaffy** [comment]
I am generating an experimental version related to the PR that was submitted by @diacu right now, once I have that version I'll share it so users can test with it in their applications.

https://github.com/strapi/strapi/actions/runs/6051019399

**Comment by derrickmehaffy** [comment]
Experimental Version: `0.0.0-experimental.f0f8d365a96bb312d6f9e8f40d6cdd061b9a2892`

You should only need to use this with the `@strapi/plugin-graphql` package to test with but since I based the experimental on our `main` branch you may need to modify all `@strapi/*` packages with it. I do not advise using this version in production.

**Comment by derrickmehaffy** [comment]
FYI the fix has been merged, this will be released as part of v4.13.2 on Wednesday Sept 6th, in the meantime you should be good to use the experimental and I did confirm you only need to change the @strapi/plugin-graphql package to it.

**Comment by broksonic21** [comment]
I can confirm this fixes our repro as well

But as a customer who ran into this (and isn't going to run an experimental release) -- My opinion: If 14.3.1 has [security fixes in it](https://github.com/strapi/strapi/releases/tag/v4.13.1) with a recommendation to update to it, and is recommend via the dialog inside STRAPI admin to update to it, which all of the ecosystem will see (even before we get to companies using dependabot/renovatebot/etc), it seems weird to leave a critical fix until Wednesday to get out.

**Comment by derrickmehaffy** [comment]
> I can confirm this fixes our repro as well - thanks for quick resolution.
> 
> But as a customer who ran into this (and isn't going to run an experimental release) -- My opinion (and take it for what it's worth, just mine!): If 14.3.1 has [security fixes in it](https://github.com/strapi/strapi/releases/tag/v4.13.1) with a recommendation to update to it, and is recommend via the dialog inside STRAPI admin to update to it, which all of the ecosystem will see (even before we get to companies using dependabot/renovatebot/etc), it seems weird to leave a critical fix until Wednesday to get out.
> 
> If nothing else, seems prudent to update the release notes for 14.3.1 to mention there's a critical issue if you use graphql.
> 

I can try talking to the team to push out a hot fix on Monday, we just have pretty strict rules about not releasing on Fridays.

**Comment by derrickmehaffy** [comment]
Cc @alexandrebodin / @Convly / @Marc-Roig

**Comment by Cretezy** [comment]
Since it's a security issue _and_ a major fix to be included in the release, it should be done ASAP.

**Comment by MrRosario** [comment]
I downgraded  @strapi/plugin-graphql, @strapi/plugin-i18n, @strapi/plugin-users-permissions, @strapi/strapi to "4.12.4" its working fine. I will upgrade when the strapi team fix this issue.

**Comment by Slowl** [comment]
> Hey there, thanks for your comments & suggestions, we're going to make a new patch release today (with the fix) to unlock apps asap.

Hi, is this still being released today ? I need to know when will I be able to make a production release of our website, if I need to downgrade until wednesday or exceptionally postpone our usual monday release

**Comment by derrickmehaffy** [comment]
It was released: https://github.com/strapi/strapi/releases/tag/v4.13.2
