### ISSUE TITLE
Table captures events when it's scrolled so actions do not work

### ISSUE THREAD

**Issue by jastrand** [strapi/strapi#17880]
### Required System information

- Node.js version: 18
- NPM version:
- Strapi version: Tested both 4.12.0 and 4.12.7
- Database: postgres
- Operating system: ios
- Is your project Javascript or Typescript: javascript

### Describe the bug

When clicking Duplicate Item in Content Manager > Collection Type the resource does not duplicate, instead it opens the item that was clicked. It is causing content managers to make many mistakes by editing and saving items that they thought were duplicated.

### Steps to reproduce the behavior

1. Go to Content Manager and any Collection Type
2. Click on Duplicate Item
3. Now instead of duplicating, the item that was clicked is opened. 
4. I get the following logs: 

![image](https://github.com/strapi/strapi/assets/57670121/8e924329-954d-4772-a48b-0c7fb1020a14)

### Expected behavior

Expected that the item would be duplicated

### Screenshots

![image](https://github.com/strapi/strapi/assets/57670121/465824d5-1603-42a6-a4e7-07225bdce362)

**Comment by oxenprogrammer** [comment]
The duplication works fine as seen below, it just opens the newly duplicated entry with a chance to edit.
Perhaps we need a toast saying `Success Duplication`

https://github.com/strapi/strapi/assets/7220167/2c52fdfe-a4a1-48d8-825b-c22ba43efbae

**Comment by jastrand** [comment]
It seems like in your case it does duplicate, this is not the case for me. Here I am trying to delete the entry, and the same thing happens that the current entry is opened instead of deleted: 

https://github.com/strapi/strapi/assets/57670121/cfe85410-643f-41d2-ba65-d112628dcf5a

**Comment by jastrand** [comment]
Here is another case when duplicating, here the first duplicating is not working but the second one does. The second also shows the toast for duplicating entries with relational fields 


https://github.com/strapi/strapi/assets/57670121/f25c715f-0476-4a67-954f-efe88c790968

**Comment by joshuaellis** [comment]
I have cleared up the title to what the real issue is and due to the number of reports updated the severity 👍🏼

**Comment by julesrenaud** [comment]
Seems to me like the severity is pretty high because a user could unwittingly edit existing content which leads to a permanent loss of data

**Comment by amerikan** [comment]
@joshuaellis just opened PR as a possible fix for this.

**Comment by amerikan** [comment]
@joshuaellis I have opened a PR for this.
