### ISSUE TITLE
Spaces or punctuation in field name breaks Strapi

### ISSUE THREAD

**Issue by adamkhan** [strapi/strapi#1789]
If I use two words in a field name or add some punctuation to it — say a question mark for a boolean field — Strapi will not load.

It would be good to allow these in field names — they are what is displayed on the admin screen after all.

**Comment by derrickmehaffy** [comment]
@adamkhan These are not support, in future updates Strapi will allow the "view" to change but currently that is not possible with data on the left menu.

Currently you can change the field names listed in the "content view" and after this PR: https://github.com/strapi/strapi/pull/1684 is merged you will be able to do the same in the "content edit view"

As of right now, you will need to create models that are all lowercase and include no special characters.

**Comment by adamkhan** [comment]
Thanks for the heads-up. Good to know this functionality is coming soon along with more configurability on the content manager's layout.
