### ISSUE TITLE
Strapi graphql "Missing schema in validateQuery" issue when data fetching

### ISSUE THREAD

**Issue by nipunaDev** [strapi/strapi#17892]
We found a critical issue when we fetch data from strapi project using graphql. Its’s also a build error.
If we add an image field for the graphql query, we got this error called “Missing schema in validateQuery”. We tried to fix this issue by creating a brand new strapi app but It’s also got this error again. If we fetch that data without any image, It’s working fine. How can we solve this problem?

Versions that we tried:
"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@ckeditor/ckeditor5-media-embed": "^37.1.0",
    "@strapi/plugin-graphql": "^4.7.1",
    "@strapi/plugin-i18n": "4.9.2",
    "@strapi/plugin-users-permissions": "4.9.2",
    "@strapi/provider-upload-aws-s3": "^4.7.1",
    "@strapi/strapi": "4.9.2",
    "mysql": "2.18.1",
    "strapi-provider-upload-aws-s3-use-cdn": "^1.0.3"
  }

---

"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.2",
    "@ckeditor/ckeditor5-media-embed": "^37.1.0",
    "@strapi/plugin-graphql": "^4.12.7",
    "@strapi/plugin-i18n": "4.12.7",
    "@strapi/plugin-users-permissions": "4.12.7",
    "@strapi/provider-upload-aws-s3": "^4.12.7",
    "@strapi/strapi": "4.12.7",
    "mysql": "2.18.1",
    "strapi-provider-upload-aws-s3-use-cdn": "^1.0.3"
  }

---

"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@ckeditor/ckeditor5-markdown-gfm": "^39.0.1",
    "@strapi/plugin-graphql": "^4.13.1",
    "@strapi/plugin-i18n": "^4.13.1",
    "@strapi/plugin-users-permissions": "^4.13.1",
    "@strapi/provider-upload-aws-s3": "^4.13.1",
    "@strapi/strapi": "^4.13.1",
    "mysql": "^2.18.1",
    "strapi-provider-upload-aws-s3-use-cdn": "^1.0.3"
  }

![image (2)](https://github.com/strapi/strapi/assets/104132619/f8cf832f-0b7f-4f5b-981c-619f4cc22787)
![image (1)](https://github.com/strapi/strapi/assets/104132619/1490a452-fe17-4735-9f08-94e1569282f5)

**Comment by kasun-sonic-devs** [comment]
Downgraded graphql package version to 4.12.4 and It is working.
` "@strapi/plugin-graphql": "4.12.4"`
but ` "@strapi/plugin-graphql": "^4.12.4"`  version not working

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/17875
