### ISSUE TITLE
Woops! Something went wrong. Please, try again. after updating to v4.13.1 on all Collection Types

### ISSUE THREAD

**Issue by AndColla** [strapi/strapi#17894]
### Required System information

- Node.js version: v16.20.2
- NPM version: 8.19.4
- Strapi version: v4.13.1
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript: JS

### Describe the bug

After updating to Strapi v4.13.1 I cannot edit any Collection Type from the integrated admin panel as it shows "Woops! Something went wrong. Please, try again.".
In the browser console an error is shown: `TypeError: Cannot read properties of undefined (reading 'list') at content-manager.f7bc1541.chunk.js:1080:3774`

### Steps to reproduce the behavior

1. Update to v4.13.1
2. Open admin panel
3. Try to edit any collection type

### Expected behavior

I should see a list of entries.

### Screenshots

![image](https://github.com/strapi/strapi/assets/14584600/29bd706c-57b5-4fcb-bba3-b545febf8010)

**Comment by Mcastres** [comment]
The same happens when upgrading FoodAdvisor to 4.13.1 on the User & Page collection types **only** (🤔)
However, the error is different: `TypeError: Cannot destructure property 'firstname' of 'object null' as it is null.`

**Comment by joshuaellis** [comment]
> The same happens when upgrading FoodAdvisor to 4.13.1 on the User & Page collection types **only** (🤔) However, the error is different: `TypeError: Cannot destructure property 'firstname' of 'object null' as it is null.`

If the error is different then please open a new issue.

**Comment by alexphiev** [comment]
Same error here after upgrading to `4.13.1`, when going to Content Manager and selecting a Content Type (Strangely, it only happens on around 50% of my collection types): 
`TypeError: (destructured parameter) is null`

![image](https://github.com/strapi/strapi/assets/14188358/a9163789-0f07-4036-a240-c4a697a3da60)

**Comment by StGeass** [comment]
Same error after upgrading to `4.13.2`
<img width="584" alt="image" src="https://github.com/strapi/strapi/assets/906496/dd5f7913-094a-4ecb-af87-8c04015c8726">

**Comment by GalloDaSballo** [comment]
The Admin Panel is trying to get user info from a content you created programmatically

I resolved by removing the "createdBy" from the default view

**Comment by Nirajn2311** [comment]
I looked into this a bit today. On restarting the server after upgrading the strapi version, there were some configs which needed to be exported. Basically there are 2 new properties, `createdBy` and `updatedBy`, and these missing properties were what was causing the above error to pop up.

**Comment by AndColla** [comment]
> I looked into this a bit today. On restarting the server after upgrading the strapi version, there were some configs which needed to be exported. Basically there are 2 new properties, `createdBy` and `updatedBy`, and these missing properties were what was causing the above error to pop up.

After some trial and errors i got to the same conclusion. The problem was caused by importing the old config via `strapi-plugin-config-sync`

**Comment by jobe451** [comment]
I also have 

`Cannot` destructure property 'firstname' of 'object null' as it is null.

It matches to what @Nirajn2311 describes.

- It started happening when I tried to view a Collection in the content manager
- It appeared after I inserted a new record via API/POST to that collection
- "firstname" is not an attribute in any of my data structures. So it quite likely this refers to a user record (createdBy/updatedBy)
- The API-insert was done unauthenticated, as I gave insert-rights to public/anonymous users
- coursly enough, this does not happen in the test environment (production and test run with the same packages, fershly rebuilt)

**Comment by jobe451** [comment]
Looks like the issue I addressed above was already addressed in #17897 chown. Fixed in 4.13.2

**Comment by adecruz-avg** [comment]
Is there a solution to this yet? Having the same problem as the original poster.

**Comment by joshuaellis** [comment]
This was fixed in 4.13.2. If you are still getting the error beyond this, please open a new issue…
