### ISSUE TITLE
A possible typo in Router documentation

### ISSUE THREAD

**Issue by gamtiq** [strapi/strapi#179]
I suppose there is a typo at the bottom of [Router documentation page](http://strapi.io/documentation/router):
> For example to access DELETE /post/:id, the request will go through the isAdmin policy first. If the policy allows the request, then the *show* action from the Post controller is executed.

It seems that `delete` action should be specified instead of `show`.

**Comment by Aurelsicoko** [comment]
Thanks for pointed this out! It fixed (see https://github.com/strapi/strapi-docs/commit/af4f9de07fee09f9177de27b80174dea582e44fc)
