### ISSUE TITLE
Configure View Entry Title for Relation field with User (from admin) not working

### ISSUE THREAD

**Issue by adwinang** [strapi/strapi#17904]
### Required System information
- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.13.1
- Database: sqlite
- Operating system: MacOS
- Is your project Javascript or Typescript: TypeScript

### Describe the bug
I am having the same issue in #17646 despite it being supposedly fixed in v4.13.1. The details are the same as #17646 

### Screenshots
![Screenshot 2023-09-02 at 12 39 24 AM](https://github.com/strapi/strapi/assets/34839258/9c220218-551e-40db-9870-96813d2d65a4)

**Comment by joshuaellis** [comment]
Can you please fill out the bug template explaining what you're facing even if it's similar to another issue? :)
