### ISSUE TITLE
Potential regression introduced by #17799

### ISSUE THREAD

**Issue by liarco** [strapi/strapi#17906]
### Required System information

- Node.js version: `v18.17.0`
- NPM version: `9.6.7`
- Strapi version: `4.13.1`
- Database: `SQLite`
- Operating system: `macOS 13.4.1`
- Is your project Javascript or Typescript: Typescript

### Describe the bug

New types introduced by #17799 mark `findMany(...)`'s return type to `Promise<AnyEntity | AnyEntity[]>` which sounds weird since it should always return an array.

### Steps to reproduce the behavior

The picture below shows a very simple controller that I created in a test project. I fetch the `api::post.post` objects and then I loop through them with both `.map(...)` and a for loop to show the issue. No TS types have been generated  in this case.

**Picture A:**
<img width="815" alt="Screenshot 2023-09-02 at 02 09 22" src="https://github.com/strapi/strapi/assets/1532277/03768041-c737-4257-96fb-160031dc44d9">

The problem can be solved by generating the types using `strapi ts:generate-types` as you can see in the picture below...

**Picture B:**
<img width="815" alt="Screenshot 2023-09-02 at 02 12 09" src="https://github.com/strapi/strapi/assets/1532277/a7562d9f-2c02-4e45-8ac2-39ccbf07672f">

But I had to comment out the for loop before running `strapi ts:generate-types` otherwise it fails due to a typecheck error:
```
Type 'AnyEntity | AnyEntity[]' must have a '[Symbol.iterator]()' method that returns an iterator.ts(2488)
```

Commenting out pieces of code any time you wanna build the types is impossible in a complex project...

### Expected behavior

I would expect the following behavior:
1. `findMany(...)` should always return an array (this might apply to other entity service functions too, but I didn't investigate further)
2. currently, the `strapi ts:generate-types` command needs to compile the whole codebase before the types can be generated, I find this pretty inconvenient because it makes the compilation fail due to the lack of types, but the types generation fails too because it can't compile the code... I face the same issue any time I create a new content type from the admin dashboard while having the types already built from the previous codebase: the server needs to restart after the code is compiled again, but the old types do not include the new content type so the compilation fails and the server dies. The only solution is to remove the types folder and re-generate the types

I hope it's just me doing something wrong here, but I couldn't find a proper solution...

Thank you for your time.

---

## Edit (04-09-2023)

I also noticed that a the following pattern stopped working with the new version:
<img width="681" alt="Screenshot 2023-09-04 at 19 22 52" src="https://github.com/strapi/strapi/assets/1532277/5d86da6b-1e02-44f1-904e-14cae7fe4ee5">

Using the `id` field here is pretty useful, especially when other fields are optional.

**Comment by Convly** [comment]
Hey, thanks for sharing this issue, appreciate the thorough explanation.

> findMany(...) should always return an array (this might apply to other entity service functions too, but I didn't investigate further)

It returns `Entity[]` for queries on collection types and `Entity | null` for queries on single types. The typings will adapt based on the given content type UID.

> currently, the strapi ts:generate-types command needs to compile the whole codebase before the types can be generated, I find this pretty inconvenient

This is a [known issue](https://github.com/strapi/strapi/issues/17084) & we're [trying to find a pleasant solution](https://github.com/strapi/strapi/pull/17349) at the moment. The main issue is that we have to take into account the code loaded by customizations (plugins, user) that need to be executed (thus compiled). The linked PR is a first draft of a potential solution but we're exploring more ideas at the same time.

**Comment by rktyt** [comment]
I don't know if this is the same problem, but `fineOne()` and `count()` also give type errors in 4.13.1.

```typescript
const uid = 'api:xxx.xxx'
const pickOne = await strapi.entityService.findOne(
  uid,
  100,
  {
    publicationState: 'preview',
  },
)
const total = await strapi.entityService.count(uid, {
  locale: 'all',
  publicationState: 'preview',
});
```

The following errors will occur:
> error TS2345
> 'publicationState' does not exist in type '{ fields?: Any<"api::xxx.xxx">; } & { populate?: Any<"api::xxx.xxxs">; }'
> 'locale' does not exist in type '{ fields?: Any<"api::xxx.xxx">; } & { populate?: Any<"api::xxx.xxxs">; }'

Notes:
- The above code will  be the code used in my plugin of mono repo.

**Comment by liarco** [comment]
Hi @Convly, thank you for the precious insights, now I get what's going on and I can adapt to it.

If I may, I would say that having a `findMany(...)` function return either a collection or a single entity depending on a text param can be very confusing (especially when TS types are not generated for the project). I'm used to many other tools which return an array containing a single element in that same scenario. If I really want a single item, maybe because I know I'm dealing with a **single type**, then I would expect to have a `findFirst(...)` function since `findOne(...)` expects an ID to be passed which is absolutely reasonable.

For instance, this is what **Prisma** does (just to name an existing project, but the same applies to others):
- [`findUnique(...)`](https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-record-by-id-or-unique-identifier): fetches one record based on its unique ID (same as Strapi's `findOne(...)`
- [`findMany(...)`](https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-all-records): fetches all records and supports filters (same as Strapi's `findMany(...)`
- [`findFirst(...)`](https://www.prisma.io/docs/concepts/components/prisma-client/crud#get-the-first-record-that-matches-a-specific-criteria): is the same as `findMany(...)` but limits the result to the first matching result. This one is missing in Strapi but it can be extremely convenient and can also work perfectly fine with **single types**

The reason why I care so much about such a minor detail is because, IMHO, having a consistent `findMany(...)` return type would make the API behavior much more predictable and avoid useless checks on reusable code that shouldn't really care about which type of entity it's interacting with. In the end of the day, app devs are supposed to know the data structure and can use either `findMany(...)` or `findFirst(...)` according to the context.

I hope this makes sense and I would really appreciate if you could share your opinion about this. 🙏

**Comment by liarco** [comment]
I just added another change [(see above)](https://github.com/strapi/strapi/issues/17906#issue-1878207021) that might be breaking compatibility with previous versions. Please let me know if you think I should open a dedicated issue for it, didn't want to flood the team as it's still somehow related to the same PR.

**Comment by Convly** [comment]
> I hope this makes sense and I would really appreciate if you could share your opinion about this. 🙏

I do agree with the essence of what you've said in your message. We should have a better content API to interact with the data.
For now, we need to maintain compatibility and avoid breaking changes by updating public APIs such as the entity service one, but we'll definitely improve them for V5.

I'll share your comments & ideas internally so that we can take them into account while designing the new APIs

**Comment by liarco** [comment]
> For now, we need to maintain compatibility and avoid breaking changes by updating public APIs such as the entity service one, but we'll definitely improve them for V5.

That makes perfect sense @Convly, thank you.

I'm gonna leave a quick workaround here in case anyone else bumps into this:
```typescript
  // ...
  getPosts: async (ctx) => {
    const posts = await strapi.entityService.findMany('api::post.post', {
      fields: [ 'title', 'content' ],
    });

    // This doesn't make the compilation fail,
    // but it's just a side-effect
    posts.map(post => console.log(post.content?.toUpperCase()))

    // TODO: Remove this in the future...
    if (!Array.isArray(posts)) {
      /*
       * findMany(...) can return a single entity for "single types".
       * The runtime will never enter this if statement in normal conditions
       * (unless you specify a single-type UUID for the query by mistake), but
       * this explicit check ensures the type-safety and avoids compilation errors.
       */
      throw new Error('Unexpected result.');
    }

    // This breaks because it expects the value
    // to be iterable but AnyEntity is not!
    for (let post of posts) {
      console.log(post.content?.toUpperCase());
    }

    ctx.body = {
      data: posts,
    };
  },
  // ...
```

Not the cleanest solution, but it does the job.

**Comment by Convly** [comment]
**Update**: We're gonna work on the main issue over the next few weeks and hope to release a fix in the month (don't want to overpromise, but that's our goal :slightly_smiling_face:)

**Comment by Convly** [comment]
Hey, we had a discussion yesterday afternoon and ended up with a proposal.
You can read more about it here: https://github.com/strapi/strapi/pull/17956
Experimental release:  `0.0.0-experimental.3cadca87513eebfb388e8328d166fc3112020c51`

**Comment by liarco** [comment]
Thank you @Convly: https://github.com/strapi/strapi/pull/17956#issuecomment-1709772382
