### ISSUE TITLE
Dev strapi project fail to go to Marketplace and Plugin

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1791]
**Informations**
- **Node.js version**:  v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: mongodb
- **Operating system**: macOS

**What is the current behavior?**
Trying to use dev strapi project to debug plugin. 
Followed the [steps in contribution docs](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to create a dev strapi project, `admin/install-plugin` and `admin/list-plugins` keep loading, and there are a few console errors.

![screen shot 2018-08-23 at 11 24 23 am](https://user-images.githubusercontent.com/3782817/44544731-e6761080-a6c7-11e8-874f-f2861eaea8b3.png)

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**
It is not urgent. The only problem is hard to debug and test plugin.

**Comment by soupette** [comment]
@yummyelin is it still happening? Can yo do a new setup with the following command from the monorepo `npm run setup:build` and check if you still have the `babel-polyfill` error when running the admin on the build?
