### ISSUE TITLE
Concurrency issue with two nodes Postgres cluster

### ISSUE THREAD

**Issue by TheoZanchiAppstud** [strapi/strapi#17929]
### Required System information

Strapi Version: 4.12.6
Operating System:
Database: Postgres
Node Version: 16.15.1
NPM Version: 8.11.0
Yarn Version:

### Describe the bug

Hello,

I’ve got a problem with my Production Strapi. I have to synchronize a list of projects from my client API (several hundred of objects) into a Strapi collection.

Each project have to be stored in three locales resulting in a lots of calls to Strapi for deleting, updating or creating collection entries depending on my clients projects list.

The Strapi instance is connected to a two nodes Postgres SQL cluster.

Once the sychronisation is running, some entries cannot be created as I get a Strapi error

Cannot read properties of null (reading 'id')
TypeError: Cannot read properties of null (reading 'id')
    at createComponents (/opt/node_modules/@strapi/strapi/lib/services/entity-service/components.js:67:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (/opt/node_modules/@strapi/strapi/lib/services/entity-service/index.js:162:27)
    at async Object.<anonymous> (/opt/node_modules/@strapi/strapi/lib/services/entity-service/index.js:416:20)
    at async Object.create (/opt/node_modules/@strapi/plugin-i18n/server/services/entity-service-decorator.js:130:19)
    at async Object.create (/opt/node_modules/@strapi/strapi/lib/core-api/controller/collection-type.js:63:22)
    at async returnBodyMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /opt/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
    at async /opt/node_modules/@strapi/strapi/lib/middlewares/logger.js:9:5
    at async /opt/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/opt/node_modules/@koa/cors/index.js:61:32)
    at async /opt/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/opt/node_modules/koa-session/index.js:41:7)
    at async /opt/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5
None of these error occurs if I delay two projects synchronisations by 5 seconds or if I remove one of the two nodes of the Postgres cluster.

Is it possible that I run into a concurrency error or something like that during my projects synchronisation ?

Thank by advance for the help.

**Comment by derrickmehaffy** [comment]
This looks like an odd sync in the cluster, I'm marking this as a question since it's not really a bug with us since both us and Knex don't natively support clusters (it's gonna auto-close this) but we can continue to discuss.

What software are you using to handle the cluster? PG-Pool II?

**Comment by TheoZanchiAppstud** [comment]
Thanks for your quick answer.

Yes exactly, we use PG-Pool II via Bitnami helm. Do you have some experience using thing tool with Strapi ?

**Comment by derrickmehaffy** [comment]
I've not used PG-Pool before (as I'm more of a MariaDB user) but I have used ProxySQL (which is a MySQL/MariaDB tool that is very similar).

Generally the "sync" in a DB cluster is typically non-blocking but it will depend on the cluster setup. You have a primary PG node and a read-replica yeah? 

Or I guess the better question is what "mode" is your PG cluster set to for replication?
https://www.postgresql.org/docs/current/different-replication-solutions.html

**Comment by TheoZanchiAppstud** [comment]
No it's exactly that, we have two nodes in master slave setup with load balancing to distribute the read load between master and slave.

Maybe in this configuration, with a large amount of insertions, the nodes are messing up breaking the sync, what do you think ? Is this a configuration you already run with Strapi ?

**Comment by TheoZanchiAppstud** [comment]
Yeah, I'll check the sync behaviour of pg pool to see if the problem could come from that. Another solution would be to diable load balancing and keep the second node as backup in case of first one falling

**Comment by derrickmehaffy** [comment]
TBH for multi-node speed and fault tolerance I would generally recommend MariaDB. PG is best for single-node performance but their clusters are less than great (personal bias here).

MariaDB's Galera cluster (with multi-master support) is far superior especially if your application is write heavy.

This is a little diagram for one of my old personal Strapi projects from a high level:
![image](https://github.com/strapi/strapi/assets/8593673/4c6bb7f9-721d-4271-9876-c681e1bf5602)

And I did a talk about some deployment best practices here: 

https://www.youtube.com/watch?v=uvToiJCzgEY&feature=youtu.be

**Comment by derrickmehaffy** [comment]
> Yeah, I'll check the sync behaviour of pg pool to see if the problem could come from that. Another solution would be to diable load balancing and keep the second node as backup in case of first one falling.

Certainly yeah but I assume you also want to have some load balancing, active failover though I assume would be your most critical concern with the LB part just being a "bonus"

**Comment by derrickmehaffy** [comment]
One of the other simp options for MariaDB you can do is run all master nodes and just do simple tcp load balancing without the need for ProxySQL. Useful if you don't need to scale out read-nodes massively and you can just throw something simple like HAProxy in front of the Galera Cluster. No other database I'm aware of can do that (at least ones we support) as PG/MySQL both really only have single-master cluster options.

(MySQL technically can work with Galera too but it doesn't do the id-offset the same)

**Comment by derrickmehaffy** [comment]
> Yep our priorities are exactly in this order.
> 
> Thanks for the tip about MariaDB, could be an interesting choice for future projects and thanks a lot for your time discussing about this multi node sync problem 👍

No problem at all, eventually I would love to see Knex.js support native clusters but so far they aren't interested in it: https://github.com/knex/knex/issues/2253

Ideally one day I would hope we might be able to add native support for it too but might be a while.
