### ISSUE TITLE
Media library - sending updatedAt header while fetching thumbnails will return signature error

### ISSUE THREAD

**Issue by kperanovic** [strapi/strapi#17938]
### Required System information
- Node.js version: `v16.12.0`
- NPM version: `8.19.4`
- Strapi version: `4.13.2`
- Database: `Postgres`
- Operating system: `macOS 13.4.1`
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When media library is trying fetch assets from s3 (presigned URLS) to show thumbnails, it returns error `the request signature we calculated does not match the signature you provided. check your key and signing method`. The bug appears to be in the extra `updatedAt` header sent in the request. Removing the header will return a valid thumbnail.

### Steps to reproduce
1. Setup s3 upload plugin described in the `strapi-aws-s3` [documentation](https://strapi.io/blog/how-to-set-up-amazon-s3-upload-provider-plugin-for-our-strapi-app). Set `ACL` to `private`
2. Upload an asset using strapi media library.
3. Asset thumbnail will be broken.
4. Get the link used by media library to fetch thumbnails, remove the `updatedAt` header.
5. S3 will return a valid asset.

**Comment by KarsjenKoop** [comment]
I am currently having the same issue. I am using GCP storage bucket.
The request payload has an added updatedAt attribute, this attribute will cause a signature error. If it is removed, it does work.
Is there a way to stop strapi from appending this to the request?

**Comment by jaymcguinness** [comment]
Hacky workaround, but got the previews working for me whilst this is fixed:

1. Create a middleware file - eg. config/middlewares/fix-s3-media/index.js

```
module.exports = () => {
  return async (ctx, next) => {
    await next();

    if (ctx.response.body && typeof ctx.response.body === 'object') {
      const serializedBody = JSON.stringify(ctx.response.body);

      if (serializedBody.includes('updatedAt')) {
        const cleanedBody = serializedBody.replaceAll('updatedAt', '');
        ctx.response.body = JSON.parse(cleanedBody);
      }
    }
  };
};

```
2. Add this to the very end of your config/middlewares.js

```
 {
    resolve: 'middlewares/fix-s3-media/index.js'
  }
```
3. Restart and Voila! 

Not tested in production so not sure what else it breaks, but it got me through a demo.

**Comment by Boegie19** [comment]
Confirmed by volume.

**Comment by datamaker** [comment]
updatedAt Is the issue resolved? Even the latest version does not solve the problem.

**Comment by romatou** [comment]
**+1** to this issue. Found out that the problem is not with the upload or custom provider, but with the _Media Library_ page and it's unreasonable action to add `updatedAt` to the end of a signed url. Gotta fix that.

```
<Error>
  <Code>SignatureDoesNotMatch</Code>
</Error>
```
