### ISSUE TITLE
How do i upload image to a particular row of content type (Product) on strapi server . below is my code but it not working it throw me error 404

### ISSUE THREAD

**Issue by amit-deligence** [strapi/strapi#1793]
import React from 'react'

class AddProduct extends React.Component{

constructor(props){
	super(props);

	this.state = {
		value:false,
	}
 this.changeValue = this.changeValue.bind(this)
 this.handleSubmit = this.handleSubmit.bind(this)
}

changeValue(e){
	this.setState({value:!this.state.value})

	console.log("this.state.value ===> " , typeof this.state.value)
}

handleSubmit(event){

		event.preventDefault();
		var image = document.querySelector('input[type="file"]')
		console.log("image data ===> " , image.files[0])
		console.log("image ====> " , image);

		var formData = new FormData()

		console.log("formdata before ===> ", formData);
		formData.append('file',image.files[0])
console.log("formdata after ===> ", formData);
		 for(var pair of formData.entries()) {
      		console.log( "Actual data ====> " , pair[0]+', '+pair[1]);
   		 }

		console.log("Event target ===> " , event.target.title.value);

		let opts = {
			title:event.target.title.value,
			description:event.target.description.value,
			qty:event.target.qty.value,
			price:event.target.price.value,
			catagory_name:event.target.category.value,
			is_visible:this.state.value
		}
		console.log("data collected succesfully")

			fetch('http://localhost:1337/product',{

				method: 'post',
				headers: {
            		"Content-Type": "application/json; charset=utf-8",
            		// "Content-Type": "application/x-www-form-urlencoded",
        		},
				body: JSON.stringify(opts)
			})
			.then(
	    function(response) {

	    	console.log("response :" , response)
	      if (response.status !== 200) {
	        console.log('Looks like there was a problem. Status Code: ' +
	          response.status);
	        return;
	      }

	      // Examine the text in the response
	      response.json().then(function(data) {

	        console.log("data === > " ,data);
	        console.log("formData ===> " , formData)
			fetch('http://localhost:1337/upload',{

				method: 'post',
				header:{
					// "Content-Type": "application/x-www-form-urlencoded",
					// "Content-Type": "application/json; charset=utf-8",
					'Accept': 'application/json',
				    'Content-Type': 'multipart/form-data',
				},
				body: formData
			}).then(
				function(res){
					if (res.status !== 200) {
						console.log("image not uploaded : " , res.status);
						return ;
					}

					res.json().then(function(data){
						console.log("upload image ====> " , data);
					})
				}
			)

	      });
	    }
	  )
	  .catch(function(err) {
	    console.log('Fetch Error :-S', err);
	  });

	}

	render(){
		console.log("this.props ===> " , this.props)
		return(
			<div>
				<h1>Add Product</h1>

				<form method="post" encType="multipart/form-data" onSubmit={this.handleSubmit}>
				<table>
					<tr>
						<td>Title</td>
						<td><input type="text" name="title"/></td>
					</tr>
					<tr>
						<td>Description</td>
						<td><input type="text" name="description"/></td>
					</tr>
					<tr>
						<td>Quantity</td>
						<td><input type="number" name="qty"/></td>
					</tr>
					<tr>
						<td>Price</td>
						<td><input type="number" name="price"/></td>
					</tr>
					<tr>
						<td>Category</td>
						<td><select name="category">
						{this.props.data.allStrapiCategory.edges.map(document =>

							<option key={document.node.id} value={document.node.name}>{document.node.name}</option>
								 
						)}
						</select></td>
					</tr>
					<tr>
						<td>Active</td>
						<td><input type="checkbox" name="active" value={this.state.value} onChange={this.changeValue}/></td>
					</tr>
					<tr>
						<td>Add Image</td>
						<td><input type="file" name="file"/></td>
					</tr>
					<tr>
						<td><input type="submit" value="Add"/></td>
					</tr>
				</table>
				</form>
			</div>

		)
	}
}

export default AddProduct

export const categoryQuery = graphql`  
  query CategoryQuery {
    allStrapiCategory {
      edges {
        node {
          id
          name
        }
      }
    }
  }
 `

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1792

**Comment by cpres** [comment]
After some painstaking trail and error I finally figured out uploading as form data to upload:
```
            var formData = {
                files: [fs.createReadStream(image_path)],
                path: 'folder_to_upload'
            }
            request.post({url:`${strapiUrl}/upload`, formData: formData}, ()=>{});
```

I could NOT get it working with axios, but going straight to source with using 'request' made it through. Sending in as formData allowed request to set the content types correctly. I did this in node, but I'd imagine it would work in front-end react code as well
