### ISSUE TITLE
Media library broken - strapi 4.13.2

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#17931]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.7.1
- Strapi version: 4.13.2
- Database: Mysql
- Operating system: Debian
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I open the media library, I get a white page and the following error
> TypeError: Failed to construct 'URL': Invalid URL

### Expected behavior

The media library page should appear.

### Screenshots

![スクリーンショット 2023-09-05 12 02 33](https://github.com/strapi/strapi/assets/26789317/bb467357-16da-4580-ace2-d97cd8ba4b92)

![スクリーンショット 2023-09-05 11 13 33](https://github.com/strapi/strapi/assets/26789317/8c4ce93b-2271-4c7e-b98c-aebb2c226ee7)

### Additional context

| Command | Result |
| --- | --- |
| `npx strapi develop --watch-admin` | works fine |
| `npx strapi develop` | broken |
| `npx strapi build --no-optimization && npx strapi develop --no-build` | broken |

No change after deleting .cache and dist folders.

----

Updates:
In my data, all the `files.url` values in the database start with a slash.
This appears to be the cause.

**Comment by smoothdvd** [comment]
same here

**Comment by larsniet** [comment]
> If url is a relative url. should be called const urlObj = new URL(url, baseUrl) or the constructor will raise the exception.

Same issue here. This should be implemented asap, weird that no-one noticed this earlier. For now, downgrading to 4.13.1 seems to do the job.

**Comment by imaestri** [comment]
Any returns?

**Comment by kevinvugts** [comment]
Yup. I can confirm this error occurs in the latest version

**Comment by Chipsnet** [comment]
I have same issue

**Comment by maksymenkoml** [comment]
Same issue

**Comment by mhzendehpey** [comment]
same issue here.

**Comment by mhzendehpey** [comment]
same issue here.
AFAIK the problem is passing a relative path to `new URL(url)`.
`base` as the second parameter for relative paths, or an absolute path is required to create a URL object.

**Comment by gacek1123** [comment]
Also can confirm, started happening after upgrading to newest version.

**Comment by agentx3** [comment]
It should be noted that the thumbnails in the files.format are also affected, as even interacting with the admin panel will error out when trying to load image files (and probably other media too).

**Comment by derrickmehaffy** [comment]
Marking as confirmed from volume of replies

**Comment by Chipsnet** [comment]
If you are in a hurry, you can resolve this issue by downgrading to v4.13.1

**Comment by riblee** [comment]
I also run into this problem, but only when building the project and running it via `npm start`.

It works in development mode.

Downgrading to v4.13.1 solved the issue.

**Comment by itsramiel** [comment]
I am getting the following error in production `Uncaught TypeError: URL constructor: /uploads/thumbnail_tierra_mallorca_rg_J1_J8_SDEAY_unsplash_16d53c553b.jpg is not a valid URL.`, but not locally.

What is the workaround for now?

**Comment by derrickmehaffy** [comment]
Raising Sev due to Internal TID4730

**Comment by ventsislavnikolov** [comment]
I can confirm too, started happening after upgrading to newest version. I updated from 4.13.1 to 4.13.3 and happened, revert back to 4.13.1 and the media is working again.

Current solution, revert back all packages for strapi to 4.13.1.

**Comment by Torsten85** [comment]
this is the (extremely ugly) workaround I'm using right now:

`src/admin/app.js`
```js

class FixedURL extends URL {
  constructor(url, base) {
    try {
      super(url, base)
    } catch {
      super(url, window.strapi.backendURL || window.location.origin)
    }
  }
}

window.URL = FixedURL
```

**Comment by ivangonzalezg** [comment]
Hi @joshuaellis

This error persist on [v4.13.4](https://github.com/strapi/strapi/releases/tag/v4.13.4). The only way I found to solve/fix was set _url_ on `config/server.js`

**Comment by jonaslingren** [comment]
Just tried to run a new version of 4.13.4 just released and get the exact same error when uploading to my Media Library on this url "http://localhost:1337/admin/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10" 
<img width="879" alt="Screenshot 2023-09-11 at 20 53 54" src="https://github.com/strapi/strapi/assets/72208908/3692ed97-fbb9-4b63-8310-8ed101af9fe7">

**Comment by itekaf** [comment]
I have the same Error. I updated `Strapi` to last version (4.13.4) 
I found to solve/fix was set `STRAPI_ADMIN_BACKEND_URL` to `.env` file like `STRAPI_ADMIN_BACKEND_URL=http://localhost:1337`

Problem was that window configuration doesn't find `backendUrl` 

```javascript
window.strapi = {
  backendURL: process.env.STRAPI_ADMIN_BACKEND_URL,
  isEE: false,
  telemetryDisabled: process.env.STRAPI_TELEMETRY_DISABLED ?? false,
  features: {
    SSO: 'sso',
    AUDIT_LOGS: 'audit-logs',
    REVIEW_WORKFLOWS: 'review-workflows',
  },
  projectType: 'Community',
};
```

but this value is `''` (empty string)
![image](https://github.com/strapi/strapi/assets/10900467/78ab420f-e70b-4c13-a041-a2e1c6f87ca1)

my sugestion to change from `??` to `||`

**Comment by Dinuz** [comment]
> @jonaslingren
> 
> I have the same Error. I updated `Strapi` to last version (4.13.4) I found to solve/fix was set `STRAPI_ADMIN_BACKEND_URL` to `.env` file like `STRAPI_ADMIN_BACKEND_URL=http://localhost:1337`
> 
> Problem was that window configuration doesn't find `backendUrl`
> 
> ```js
> window.strapi = {
>   backendURL: process.env.STRAPI_ADMIN_BACKEND_URL,
>   isEE: false,
>   telemetryDisabled: process.env.STRAPI_TELEMETRY_DISABLED ?? false,
>   features: {
>     SSO: 'sso',
>     AUDIT_LOGS: 'audit-logs',
>     REVIEW_WORKFLOWS: 'review-workflows',
>   },
>   projectType: 'Community',
> };
> ```
> 
> but this value is `''` (empty string) ![image](https://user-images.githubusercontent.com/10900467/267133274-78ab420f-e70b-4c13-a041-a2e1c6f87ca1.png)
> 
> my sugestion to change from `??` to `||`

This is actually the only thing that really works! @derrickmehaffy @joshuaellis Could we implement this modification? I changed ?? into || and now I am able to use again the media library. I am using last version (4.13.4)

**Comment by imaestri** [comment]
same here =/

**Comment by Gogoro** [comment]
Same here 👀

**Comment by gfsd3v** [comment]
this issue needs to be re-opened, issue is still present on `4.13.6` and as @itekaf mentioned is a one line change (apparently)

**Comment by exotexot** [comment]
I'm running a dockerizsed version of strapi. And hence this is incredibly difficult to patch via patch-package...
@derrickmehaffy

**Comment by exotexot** [comment]
Is it safe to assume, that this bug was introduced in 4.13.2 ? So downgrading to 4.13.1 will fix it for now?

**Comment by imaestri** [comment]
> Is it safe to assume, that this bug was introduced in 4.13.2 ? So downgrading to 4.13.1 will fix it for now?

4.13.5 resolved this problem

**Comment by halilbrhmtrn** [comment]
It’s not good to ignore such cases and just throw an error. I’ve spent quite a bit of time on this. If you check the files table in the database you're using for Strapi, you should find a record where the URL is somehow corrupted, which prevents it from being parsed correctly and causes the 'Invalid URL' error. If you remove that record, it should resolve the issue.

**Comment by tlchatt** [comment]
> this is the (extremely ugly) workaround I'm using right now:
> 
> `src/admin/app.js`
> 
> class FixedURL extends URL {
>   constructor(url, base) {
>     try {
>       super(url, base)
>     } catch {
>       super(url, window.strapi.backendURL || window.location.origin)
>     }
>   }
> }
> 
> window.URL = FixedURL

Thank god for you sir @romanrostislavovich
Saved my life inherited this problem and stuck on Strapi 4.13.2. Tried for weeks to upgrade this or manually migrate to newer Strapi or Strapi cloud etc, literally impossible, nothing but headaches and dead ends, Having to operate off this old Strapi version I rebuilt from scratch till I can migrate to a different CMS. When I upload a new image this error threw. Thank god for your fix, which took me about 8 hours to track down.
