### ISSUE TITLE
Tables blink instead of making the selection in the content-manager (Table on the design system too)

### ISSUE THREAD

**Issue by marco-villanueva** [strapi/strapi#17942]
### Required System information

- Node.js version: 18
- NPM version: 8.3.0
- Strapi version: 4.12.4
- Database: Posgress
- Operating system: Windows
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When there are enough records to scroll vertically, the first time the table is visited, and the user scrolls down, selecting an entry causes the component to blink, taking the user to the top of the page, without making a selection. 

### Steps to reproduce the behavior

1. Go to a collection type
2. Make sure you have at least enough entries to achieve vertical scrolling. 
3. Scroll down to the lsat entry
4. Select last entry on the checkbox
5. See how it is brought to the top edge of the table without selecting the entry

### Expected behavior

Do the selection without scrolling or blinking.

### Screenshots

https://github.com/strapi/strapi/assets/19434129/a54cf293-e0c7-4841-93db-5c8f237386e5

### Additional context

The problem also occurs with the table component of the design system.

**Comment by amerikan** [comment]
@joshuaellis I have opened a PR for this.
