### ISSUE TITLE
Can't use relational fields in filters since 4.13.2

### ISSUE THREAD

**Issue by omerkim** [strapi/strapi#17945]
- Node.js version: 18
- NPM version: 6.4.16
- Strapi version: 4.13.2
- Database: MySQL
- Operating system: MacOS (Using Docker)
- Is your project Javascript or Typescript: TS

### Describe the bug

When trying to use a field from a component in another single type we get an error.
Doesn't happen in earlier versions (4.12.5 verified)

### Steps to reproduce the behavior

1. Create a component
2. Use it in a single type
3. Try to use it in a GraphQL filter.
4. Error: ApolloError: Invalid parameter <parameter>

### Expected behavior

Should work since:
1. We have a scheme
2. This is not a private field
3. This is not a password field

**Comment by derrickmehaffy** [comment]
Could be related to the security fix we did, need to try and reproduce

**Comment by omerkim** [comment]
I can verify it's related.
If I remove the throw inside validotrs.ts in line 40 it works.

**Comment by bglidwell** [comment]
Also getting this issue 4.13.3

Had to downgrade to 4.12.5

**Comment by omerkim** [comment]
This prevents us from upgrading our version and leaving us vulnerable to the security issues that was fixed.
Please fix this as soon as possible!

**Comment by derrickmehaffy** [comment]
Are any of you getting the 4xx error response when you try? If so that's intended and is what the security fix implemented.

**Comment by omerkim** [comment]
@derrickmehaffy Does that means we can't use relational fields in filters???
It wasn't documented and it's a huge blow for us, we need this to work.
We have a list of hotels for example and one of the relations fields is a boolean that indicates if the hotel is working or not.

**Comment by derrickmehaffy** [comment]
No but it means that they need to have the permission to do so

**Comment by derrickmehaffy** [comment]
I cannot filter anything that they don't have the permission for.

**Comment by rafikmoreira** [comment]
Hello, everyone. I'm also experiencing issues with the filters. If I include an optional variable but don't send it to the query, it returns as an invalid value. However, in certain situations, such as during the initial rendering of a page, I don't want to apply all the filters. This used to work correctly before the update.

**Comment by derrickmehaffy** [comment]
> Hello, everyone. I'm also experiencing issues with the filters. If I include an optional variable but don't send it to the query, it returns as an invalid value. However, in certain situations, such as during the initial rendering of a page, I don't want to apply all the filters. This used to work correctly before the update.

Can you provide more contextual information about the filters you are using and does the user have the proper permissions to do so?

**Comment by DevDengChao** [comment]
@derrickmehaffy Here is an example to reproduce the issue: [example.zip](https://github.com/strapi/strapi/files/12710943/example.zip)

You can try running unit test on strapi 4.12.7 and 4.13.+.

**Comment by innerdvations** [comment]
@derrickmehaffy Would you be able to reproduce and see if it is fixed by https://github.com/strapi/strapi/pull/18168 ?

**Comment by derrickmehaffy** [comment]
Duplicate of https://github.com/strapi/strapi/issues/17995
