### ISSUE TITLE
Database automatically crashed

### ISSUE THREAD

**Issue by 0xNaim** [strapi/strapi#17943]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.13.1
- Database: better-sqlite3  v8.5.0
- Operating system: Kali Linux
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

When I used the Strapi default database and deployed it on Render.com, the database crashed automatically after a few minutes. I had to create a new admin account and add the data again and again. I didn't face this issue when I used the PostgreSQL database.

### Steps to reproduce the behavior
-

### Expected behavior

I want to keep my data when it is deployed.

### Screenshots

-

### Code snippets

-
### Additional context

-

**Comment by derrickmehaffy** [comment]
Please add some actual reproduction steps, error logs or something. We can't do anything with just this information.

**Comment by 0xNaim** [comment]
I did not receive any error or warning message. After a few minutes, when I tried to log in to my admin panel, I was redirected to the admin sign-up page. When I signed up again, I had to add all of the data from the beginning.

![image](https://i.ibb.co/YjYG4gj/strapi.png)

**Comment by derrickmehaffy** [comment]
Your deployment is probably using SQLite instead of your actual database.

Not a Strapi bug, please open a ticket with your hosting provider or review your configuration.
