### ISSUE TITLE
Media Library doens't work with GraphQL plugin

### ISSUE THREAD

**Issue by bart-1990** [strapi/strapi#17951]
### Required System information

- Node.js version: v18.17.1
- NPM version:v 9.6.7
- Strapi version:  4.13.2
- Database: MySQL  8.1.0-arm64
- Operating system: macOS 12.3
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I cannot open the Media library after I install the GraphQL plugin (also 4.13.2) and when the library contains at least one file.
When accessing the Media Library of the admin panel, the URL of the media library redirects to http://localhost:1337/admin/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10, the page is blank and in the console I see the error 'TypeError: Failed to construct 'URL': Invalid URL at a (main.0094f2ff.js:1138:8419)'.

My database and the folder public/uploads do contain file information. When I remove the GraphQL plugin the error is gone.
The error also occurs with SQLite (quickstart), so it's not MySQL related.

### Steps to reproduce the behavior

1. Setup strapi quickstart
2. Add a file with the Media Library of the admin panel
3. Install the strapi GraphQL plugin
4. Check the Media Library again, the error occurs.

### Expected behavior

The Media Library  opens without errors.

### Screenshots

<img width="1725" alt="Screenshot 2023-09-06 at 11 09 50" src="https://github.com/strapi/strapi/assets/7540719/db64fc84-9a5e-4fd3-a283-37500e33eee7">

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/17931
