### ISSUE TITLE
npx @latest is using the wrong Strapi version

### ISSUE THREAD

**Issue by stb13579** [strapi/strapi#18012]
### Required System information

- Node.js version: 18
- NPM version: 9.8.1
- Strapi version: n/a
- Database: SQLite
- Operating system: mac
- Is your project Javascript or Typescript: js

### Describe the bug

The command `npx create-strapi-app@latest`is creating 4.14 alpha and not the last stable release. 

### Screenshots
<img width="611" alt="Capture d’écran 2023-09-11 à 12 45 45" src="https://github.com/strapi/strapi/assets/97027841/4322ae97-bc3f-425b-bb90-e4977c0f2e89">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by joshuaellis** [comment]
Thanks for letting us know, this has been mentioning internally and we will look at resolving.

**Comment by joshuaellis** [comment]
This should be fixed now :) thanks!
