### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'scrollToItem')

### ISSUE THREAD

**Issue by zjjtm** [strapi/strapi#18025]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.8.1
- Strapi version: 4.13.4
- Database: Mysql 5.7.8
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Here are two collection types:
**RoomDatePrice**, **RoomType**
RoomDatePrice has a **relation** with RoomType: **RoomDatePrice has one RoomType**

### Steps to reproduce the behavior

1. Go to Content Manager - 'RoomDatePrice'
2. Click on 'Creat new entry' or edit any exits item
3. Follow the steps as the following:
Choose  a room type like Deluxe room
![微信截图_20230912094504](https://github.com/strapi/strapi/assets/144752602/3e93db38-3482-409f-813f-4608fe6b3062)

Then choose a room type like Standard room
![微信截图_20230912094529](https://github.com/strapi/strapi/assets/144752602/600a1c73-c9da-45fa-bc68-c418e09939de)

Finally delete Standard room
![微信截图_20230912094554](https://github.com/strapi/strapi/assets/144752602/c37b9be5-82c7-49d1-8f12-033b5108b901)

4. Error comes
![微信截图_20230912094653](https://github.com/strapi/strapi/assets/144752602/50422239-ee05-49dc-81bf-d7469ced3400)

**Comment by poudyalamit** [comment]
Is this issue open? I want to solve this issue
