### ISSUE TITLE
Failed to construct 'URL': Invalid base URL. Media Libriary doesn't work  in v4.13.4  

### ISSUE THREAD

**Issue by sleeporsmile** [strapi/strapi#18024]
### Required System information

- Node.js version: 18.17.0
- NPM version: 9.6.7
- Strapi version: 4.13.4
- Database: sqlite
- Operating system: mac os
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Media Libriary doesn't work. It's look like white screen and error in console: Failed to construct 'URL': Invalid base URL
Everything is fine in v4.13.1

### Screenshots
<img width="1728" alt="Screenshot 2023-09-11 at 23 42 45" src="https://github.com/strapi/strapi/assets/43747618/048bf3eb-4080-45a6-8c63-fa64b12fb11c">

### Additional context
package.json:
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "Strapi CMS of web site",
  "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@retikolo/drag-drop-content-types": "^1.3.9",
    "@strapi/plugin-i18n": "4.13.4",
    "@strapi/plugin-seo": "^1.9.5",
    "@strapi/plugin-users-permissions": "4.13.4",
    "@strapi/strapi": "4.13.4",
    "better-sqlite3": "8.6.0",
    "qs": "^6.11.2",
    "react-select": "^5.7.4",
    "strapi-plugin-config-sync": "^1.1.3",
    "strapi-plugin-placeholder": "4.4.0",
    "strapi-plugin-preview-button": "1.1.3",
    "strapi-plugin-rest-cache": "^4.2.8",
    "strapi-provider-rest-cache-memory": "^4.2.8"
  },
  "strapi": {
    "uuid": "****"
  },
  "engines": {
    "node": ">=16.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

**Comment by MohmadHafiz** [comment]
i encountered the same prob from version 4.13.1 - 4.13.4

**Comment by derrickmehaffy** [comment]
Can you please delete node modules and lock files + reinstall/rebuild.

I tested this quite a bit before we released it including setting different urls that worked fine.

**Comment by hoqkhanh** [comment]
Hi @derrickmehaffy 
I got the same issue when I access the media library on Strapi 4.13.4, It's not appear on 4.13.2. 

main.93f61d66.js:1535 TypeError: Failed to construct 'URL': Invalid base URL
    at c (main.93f61d66.js:1482:8370)
    at be (main.93f61d66.js:1195:666)
    at z (main.93f61d66.js:1533:20696)
    at Rn (main.93f61d66.js:1535:45915)
    at mh (main.93f61d66.js:1535:41497)
    at nh (main.93f61d66.js:1535:41425)
    at yd (main.93f61d66.js:1535:41276)
    at Gd (main.93f61d66.js:1535:37490)
    at vd (main.93f61d66.js:1535:36386)
    at C (main.93f61d66.js:1618:1643)
qc @ main.93f61d66.js:1535
main.93f61d66.js:1535 Uncaught TypeError: Failed to construct 'URL': Invalid base URL
    at c (main.93f61d66.js:1482:8370)
    at be (main.93f61d66.js:1195:666)
    at z (main.93f61d66.js:1533:20696)
    at Rn (main.93f61d66.js:1535:45915)
    at mh (main.93f61d66.js:1535:41497)
    at nh (main.93f61d66.js:1535:41425)
    at yd (main.93f61d66.js:1535:41276)
    at Gd (main.93f61d66.js:1535:37490)
    at vd (main.93f61d66.js:1535:36386)
    at C (main.93f61d66.js:1618:1643)

Please help to reproduce this issue again

**Comment by yclgkd** [comment]
I got the same issue in v4.13.4
![image](https://github.com/strapi/strapi/assets/31514100/38e1e892-78c0-42e1-8d8c-bc2b49645bf4)

**Comment by matthewyu-ptr** [comment]
I have the same issue.

When I was on Strapi 4.13.3, I can upload an image file. However, when I go to the media library, it crashes with the same error messages like other people had.

Now, I am on Strapi 4.13.4 now. It crashes after I am trying to upload the same image. Not even upload successfully.

I have removed `node_modules` and `*.lock` and reinstall.

**Comment by ls-ramos** [comment]
Same problem here, I use the provider:`"strapi-provider-upload-do": "^3.6.9"`.

Adding the url, as @themaxaboy suggested above, fixed for me as well.

**Comment by umarsalah** [comment]
I was facing this problem, adding the `url: env("URL", "http://localhost:1337")`  fixed it.

**Comment by joshuaellis** [comment]
I've locked this because we're aware of the issue & there's a PR to solve it and i know people are going to repeat comments a lot – the immediate workaround is to add a `url` in your `config/server`. But the PR should solve this long term, thank you for your patience and I apologise for the inconvenience.
