### ISSUE TITLE
Renaming dynamic zones deletes all data inside of them. 

### ISSUE THREAD

**Issue by cluster309** [strapi/strapi#18023]
### System information

- Node.js version: 18.17.1
- NPM version: 9.8.1
- Strapi version: 4.7.0
- Database: pg
- Operating system: windows
- Is your project Javascript or Typescript: Javascript 

###  bug

When I rename a dynamic zone in Strapi, all the data within its components gets deleted. However, if I revert the name back to its original, the data reappears. I'm unsure if this is intended behavior.

**Comment by derrickmehaffy** [comment]
This is intended as we don't do alter table SQL commands.

We have a feature request to change this.
