### ISSUE TITLE
Content-type for old database

### ISSUE THREAD

**Issue by pravosleva** [strapi/strapi#1803]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: mongod version: 3.6.6 (MMAPv1)
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
New project could not be connected to old database.

**Steps to reproduce the problem**
I have created new strapi-alpha project successfully.
![0_new-project-with-strapi-alpha](https://user-images.githubusercontent.com/19761493/44622927-5f918580-a8cb-11e8-807d-0e4f83922bb5.gif)
And also I have my old remote database.
How can I create new Content-Type wich should be used with my old database?

[This is my new project with trouble](https://github.com/pravosleva/strapi-things-alpha)
[This is my old project to reincarnation](https://github.com/pravosleva/get-offer-3)

I have problems when I try to create this by content-builder.
![img_20180819_140501](https://user-images.githubusercontent.com/19761493/44622968-05dd8b00-a8cc-11e8-8276-02c26b6f3713.jpg)

And also, new user could not be created...
![img_20180819_141507](https://user-images.githubusercontent.com/19761493/44622969-0d049900-a8cc-11e8-9060-a144c2173114.jpg)

**What is the expected behavior?**
I want to create new content-type with the following fields
```
{
  header: srt,
  description: str,
  done: bool,
  priority: num,
}
```
And I'm going to use socket.io like this: http://selection4test.ru:3003/blog/post/strapi-customization
Is it possible with new strapi-alpha version?

**Suggested solutions**
I have no ideas yet...

**Comment by pravosleva** [comment]
Ubuntu 16.04

**Comment by avallete** [comment]
Hi, it looking weird to me that your mongoDB has an username and password, but no authentication database. 

Did you try to set the 'Authentication database' to 'admin', as mongo set it by default ?

**Comment by lauriejim** [comment]
Did you check migration guides ? https://github.com/strapi/strapi/wiki
