### ISSUE TITLE
Issue with Strapi v4 Migration - Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by oussabba** [strapi/strapi#18030]
**Issue Description:**
After migrating to Strapi version 4, I encountered the following error when trying to start the server:

```
[2023-09-12 09:47:47.561] debug: ⛔️ Server wasn't able to start properly.
[2023-09-12 09:47:47.562] error: Cannot read properties of undefined (reading 'kind')
TypeError: Cannot read properties of undefined (reading 'kind')
```
I followed all the proposed guides step by step. Also, I have checked all the content-types schemas they are all good.

**Expected Behavior:**
The server should start without errors after the migration to Strapi v4.

**Actual Behavior:**
The server fails to start, and the error mentioned above is displayed.

**Environment:**
- Strapi Version: 4.2.3
- Node.js Version: 16.20.2
- Database: PostgreSQL
- Operating System: Mac OS v12.5.1

Your assistance in resolving this issue is greatly appreciated!

**Comment by derrickmehaffy** [comment]
Not a bug, most likely case is one of your content types is incorrectly configured, specifically a relationship is missing on one side (generally users-permissions modifications)

Please seek assistance in community spaces.
