### ISSUE TITLE
I updated strapi version from 4.4.5 -> 4.5.1 -> 4.6.1 and facing issue with export command, how to fix ?

### ISSUE THREAD

**Issue by fenil233** [strapi/strapi#18033]
<img width="1087" alt="image" src="https://github.com/strapi/strapi/assets/108258908/f1af39fa-774e-45f5-b1cb-eb442aabaf90">

**Comment by JuliusGudni** [comment]
Have you started the Strapi instance after updating, before running the export command to make sure the DB is accessible by Strapi and to allow all DB migrations to run?

**Comment by fenil233** [comment]
> Have you started the Strapi instance after updating, before running the export command to make sure the DB is accessible by Strapi and to allow all DB migrations to run?

Yes, I have done build and also yarn develop. Everything working fine only export is creating trouble

**Comment by fenil233** [comment]
> > This is a templated message
> 
> Hello @fenil233,
> 
> We ask that you please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md). A proper issue submission let's us better understand the origin of your bug and therefore help you. We will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue with the template and we can reopen this report.
> 
> Thank you.

Updated

**Comment by derrickmehaffy** [comment]
Advise you upgrade to 4.13.6 as the version you are on is quite old
