### ISSUE TITLE
Enumeration is empty, but value is set on the model, field is required and there is a default value

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1804]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: alpha 13.1
- **Database**: pg
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**

Value is set on model, model has a default value, field is required, but I get `null` via API.
Only if the value is the second entry, I get the correct string.

**Steps to reproduce the problem**

Value is set in the created item:
![image](https://user-images.githubusercontent.com/2950505/44627679-0a3c8f00-a932-11e8-9d27-19a42d0994da.png)

Model has a field called `usage` that is either `general` or `event`
![image](https://user-images.githubusercontent.com/2950505/44627644-87b3cf80-a931-11e8-8b85-baca61b47534.png)

Has a default set, and is required
![image](https://user-images.githubusercontent.com/2950505/44627654-a4500780-a931-11e8-8232-1b2278d40b22.png)

API shows `null`
![image](https://user-images.githubusercontent.com/2950505/44627636-6ce15b00-a931-11e8-811a-80b9ee1cda21.png)

**What is the expected behavior?**

Show the correct string (general) 

**Suggested solutions**

Check if default is used and give advice/hint if the default is not valid?
Am I using a reserved keyword or something?
Maybe the bookshelf adapter for non-mongo dbs has the enum not implemented correctly?

**Comment by derrickmehaffy** [comment]
@MartinMuzatko was this posted using something other than the AdminUI. Currently the adminUI is the only thing that by default uses that default value AFAIK (confusing I know)

There is no real validation layer in strapi yet ( it is on their list of things to do ) so the bookshelf/knex hooks don't process this. If you enable the debug option you see if the value is being applied from bookshelf.

For the moment you will likely need to code it into your frontend to ensure the default value is being sent if `null`

**Comment by MartinMuzatko** [comment]
Nope, I created these via the admin UI. While the admin ui shows these values properly, the GET request does not.

**Comment by lauriejim** [comment]
Hello @MartinMuzatko , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
@MartinMuzatko I just tried with last version of strapi and clean new database and it works fine.
Can you test and tell me if this issue still happen please.

**Comment by MartinMuzatko** [comment]
Seems to be fixed with 14.x
I'll keep an eye on it. thanks!
