### ISSUE TITLE
Build fails when updating to v4.13.5. ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client'

### ISSUE THREAD

**Issue by IlirEdis** [strapi/strapi#18054]
### Required System information

- Node.js version:  node/v18.16.0
- NPM version: npm/9.6.7
- Strapi version: 4.13.5
- Database: better-sqlite3
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After changing the strapi (and other dependencies) version from 4.12.1 to 4.13.5 and running `npm install`, when i run `npm run build` i get this error in the terminal:

`ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client'`

My whole list of dependency versions: 

```
 "dependencies": {
    "@strapi/plugin-graphql": "^4.13.5",
    "@strapi/plugin-i18n": "4.13.5",
    "@strapi/plugin-seo": "^1.9.5",
    "@strapi/plugin-users-permissions": "4.13.5",
    "@strapi/strapi": "4.13.5",
    "better-sqlite3": "8.6.0"
  }
```

### Screenshots

<img width="1164" alt="Screenshot 2023-09-13 at 12 13 04" src="https://github.com/strapi/strapi/assets/128377763/930638d4-4a72-4857-92f6-cb87bd6f5554">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by IlirEdis** [comment]
Deleting ".cache", "node-modules" and "package-lock.json" and then running `npm install` & `npm run build` again fixed this issue. 
Sorry for the inconvenience!

**Comment by vdhpieter** [comment]
@IlirEdis can you reopen this issue please? Deleting `package-lock.json` is definitely not an option for a lot of users and we need a way to solve this without it

**Comment by derrickmehaffy** [comment]
> @IlirEdis can you reopen this issue please? Deleting `package-lock.json` is definitely not an option for a lot of users and we need a way to solve this without it

That's our official solution to the issue as well, lock files are notorious or caching old package versions that it shouldn't.

See this doc for upgrading version and the special call out to delete your lock file.

https://docs.strapi.io/dev-docs/update-version#upgrade-the-dependencies

![Screenshot_20230914_100210_Chrome.jpg](https://github.com/strapi/strapi/assets/8593673/a98989aa-880b-4f90-9f19-f3e58bb9ac32)

**Comment by vdhpieter** [comment]
@derrickmehaffy well that's ~interesting~ scary... If a lockfile is caching an old dependency it shouldn't libraries can resolve this by making sure there dependencies & peerDependencies are exactly what they need...
[Here](https://stackoverflow.com/questions/54124033/deleting-package-lock-json-to-resolve-conflicts-quickly) is only one of the many sources out there that explain why removing lock files is a really bad idea and it should definitely not be the official way to solve errors...

By digging deeper into this issue the issue is that Strapi is relying in some way on react dependencies but it's not correctly part of the (peer)Dependencies... By removing the lock file a newer version of react gets installed and it works again...

**Comment by IlirEdis** [comment]
Reopening the issue since other users reported the same problem. I personally think that it had to do with React v18. Probably some Strapi dependencies were not updated to React v18

**Comment by joshuaellis** [comment]
We can't reproduce this error, if someone can share a repro of it then we can investigate.

**Comment by jabiinfante** [comment]
We found into the same issue within a monorepo using latest version of strapi (4.13.7).

We found out another dependency in the project (forgotten and not used anymore😅) was requiring **react-dom@^17.0.2**.
removing package-lock.json and reinstalling deps wouldn't fix the issue... which made little sense since @strapi/admin requires **react-dom@^18.2.0**

Anyways, in our case, removing that forgotten dependency and reinstalling everything clean fixed the issue.

Hope it helps.

**Comment by flutcon** [comment]
@jabiinfante , I ran into same issue - what exactly did you add - 'react-dom/client'? Thanks

**Comment by jabiinfante** [comment]
@flutcon In my case, I removed an unused dependency which was installing react-dom@17.

Looks like @strapi/admin needs [react-dom@^18.0.2](https://github.com/strapi/strapi/blob/791b174e83a8fd5374a9f670ad527165fe79981b/packages/core/admin/package.json#L105), but in my case a previous version was installed inside node_modules/
(I would have guessed react-dom was installed inside node_modules/@strapi/admin/node_modules/ but was not there 🤷) 

Check which version of react-dom is installed on your repo... I would say everything should work with anything matching ^18.0.2.

Also make sure you delete package-lock before reinstalling your dependencies again.

**Comment by minht11** [comment]
This shouldn't have been closed. I am using Strapi inside monorepo and experiencing this issue also.

**Comment by Boegie19** [comment]
strapi can't reproduce the issue. this means that we need a way to reproduce it to reopen the issue,

**Comment by ainsleyclark** [comment]
Same issue here. Although this error is only occuring in Docker for some reason.

**Comment by minht11** [comment]
The way I fixed the issue for myself was to remove every non Strapi plugin from package.json, npm install, bring back dependencies I removed, npm install again. The package-lock updated and everything works for now.

I can't make create full reproduction but my Strapi contained these deps:
```
    "@strapi/plugin-i18n": "4.14.5",
    "@strapi/plugin-sentry": "4.14.5",
    "@strapi/plugin-seo": "^1.9.5",
    "@strapi/plugin-users-permissions": "4.14.5",
    "@strapi/strapi": "4.14.5",
    "better-sqlite3": "8.3.0",
    "pg": "8.11.3",
    "strapi-plugin-multi-select": "^1.2.2",
    "strapi-plugin-populate-deep": "^3.0.0",
    "strapi-plugin-publisher": "^1.5.0",
    "strapi-plugin-rest-cache": "^4.2.8",
    "strapi-plugin-transformer": "^3.1.2"
```

**Comment by Boegie19** [comment]
Again if somone could give strapi replication staps for this issue then we can reopen it,

**Comment by pjamieson** [comment]
Adding a dependency to my EC2 Strapi Server project for react-dom@18.2.0 resolved the errors for me.
