### ISSUE TITLE
$ne, $notIn, $notContains, $notContainsi don't work on populated fields (oneToMany or manyToMany)

### ISSUE THREAD

**Issue by Namstel** [strapi/strapi#18066]
### Required System information
- Node.js version: 18.17.1
- NPM version: 10.1.0
- Strapi version: 4.13.6
- Database: MySQL2
- Operating system: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster) (Kubuntu)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I don't seem to be able to apply the filter $ne, $notIn, $notContains, $notContainsi on populated fields of the type  `manyToMany`.

For example:
_Doesn't work:_
`GET api/contents/?populate=categories&filters[categories][id][$ne]=11&pagination[limit]=50`

```json
{
  "populate": [
    "categories"
  ],
  "filters": {
    "categories": {
      "id": {
        "$ne": "11"
      }
    }
  },
  "pagination": {
    "limit": "50"
  }
}
```

I still get items with categories where there's a category with id 11.

_Does work_:
`GET /api/contents?populate=categories&filters[categories][id][$eq]=6&pagination[limit]=50`
```json
{
  "populate": [
    "categories"
  ],
  "filters": {
    "categories": {
      "id": {
        "$eq": "6"
      }
    }
  },
  "pagination": {
    "limit": "50"
  }
}
```

I only get items with categories where there's a category with id 6

### Steps to reproduce the behavior
I'm also able to reproducde this behaviour in the Strapi Admin panel.

1. Go to 'Content Manager'
2. Click on a Collection Type with a (manyToMany) relation
3. Click on Filters and select the relation field
4. Select `is not` from the dropdown
5. Enter a value you know exists
6. See the item returning in the list

### Expected behavior

I expect all items that contain a category with that id to be filtered out.

### Screenshots

![image](https://github.com/strapi/strapi/assets/7203421/d908f0a8-4851-40d7-b8a1-b59ec1037ca0)

**Comment by Namstel** [comment]
**Additional information:**
The specific items I want to filter have more than one category with ID 11.


With debug enabled in the database config, I found this to be the query:
```sql
select distinct `t0`.`id` from `contents` as `t0` 
left join `content_categories_contents_links` as `t1` 
  on `t0`.`id` = `t1`.`content_id` 
left join `content_categories` as `t2` 
  on `t1`.`content_category_id` = `t2`.`id` 
where 
(
  (`t0`.`locale` = 'nl' and `t2`.`id` <> '11') 
and 
  `t0`.`published_at` is not null) 
limit 50
```

Logically it makes sense. This does however mean that if a record with has a category with ID 11 and one with ID 12, it will still return said record because when it encounters the relationship with ID 12 it will say "Ah yes, that doesn't match 11, so through you go."

So I'm looking for a way to build a query that will do a subselect on the category ID's incase of a relation where multiple items are possible.

**Comment by Boegie19** [comment]
@Namstel Is this the same issue you where having?

**Comment by Boegie19** [comment]
closed in favor of https://github.com/strapi/strapi/issues/14953
