### ISSUE TITLE
`deleteAllAssets` Operation During Transfer Causes Request Timeout

### ISSUE THREAD

**Issue by austinnebel** [strapi/strapi#18071]
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.6.7
- Strapi version: 4.13.1
- Database: SQLite / MySQL
- Operating system: Windows WSL / Docker (Alpine)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When transferring assets via `strapi transfer`, the assets are first deleted on the destination one by one. This is problematic when remote asset providers such as AWS S3 are used because it takes too long to delete all of them due to network delay, causing the transfer request to time out.

The source of the issue is in the nested for loop here: 

https://github.com/strapi/strapi/blob/aec9541f67f6c3fa9d8966638b6721eedd45d3dc/packages/core/data-transfer/src/strapi/providers/local-destination/index.ts#L117C10-L117C25

I experimented with using a more asynchronous approach, which was able to delete all assets within a few seconds:

```typescript
    const promises: Promise[] = [];
    for await (const file of stream) {
      promises.push(this.strapi.plugin('upload').provider.delete(file));
      if (file.formats) {
        for (const fileFormat of Object.values(file.formats)) {
          promises.push(this.strapi.plugin('upload').provider.delete(fileFormat));
        }
      }
    }

   const deleteResults = await Promise.all(promises);
```

### Steps to reproduce the behavior

1. Start a Strapi instance 
2. Start a second Strapi instance to serve as the transfer destination that has a large amount of files on it (>100)
3. Generate a transfer token on the destination Strapi instance
4. Run npx strapi transfer --to [destination-url] --to-token [destination-token] on the source Strapi instance
5. Wait for transfer to fail with a timeout error.

### Expected behavior

All files on the destination should be quickly deleted and the transfer should start normally.

**Comment by derrickmehaffy** [comment]
closing in favor of https://github.com/strapi/strapi/issues/17749
