### ISSUE TITLE
Bug tests infinite loop of 'Database connection failed!'

### ISSUE THREAD

**Issue by avallete** [strapi/strapi#1807]
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: *
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

When setting up a 'development' environment to contribute, then, running `npm run test` to check if everything is setup properly. I've seen that when a database connection fail for one the the test, the program get stuck into an infinite 'Database connection attempt failed!' loop.

**Steps to reproduce the problem**
Git clone project.
Setup dev environment as explained in documentation.
Setup a valid mongo database.
Don't setup postgres database.
`npm run test`

**What is the expected behavior?**
Display an error message, then, continue to run the tests on other databases.

**Suggested solutions**
I think I've identified the error, it come from `test/start.js`.

First, a promise rejection into `generate` are not properly handled. Resulting of an 'unhandled promise' error.
Then, `exec` is used to spawn the child process, but some of this child process (appCreate) spawn sub-childrens. Making the `child.kill()` not properly killing all the child process: see https://github.com/nodejs/node-v0.x-archive/issues/1811

A solution to fix this is to use `spawn` instead of `exec` with the proper options, to kill all the subchildrens (cf: https://azimi.me/2014/12/31/kill-child_process-node-js.html).

I've already made the changes on my side, can submit a PR if the bug are confirmed as impacting other people.

**Comment by lauriejim** [comment]
Yesterday I fix jest start https://github.com/strapi/strapi/pull/1806
But bugs still happen in test suites.

And feel free to submit a PR, help is appreciate !

**Comment by avallete** [comment]
@lauriejim PR has been made (maybe unnecessary ping, but since I don't remember if referencing an issue trigger the notification :flushed: )
