### ISSUE TITLE
Transfer process failing / Unexpected server response 200

### ISSUE THREAD

**Issue by onesoftwareengineer** [strapi/strapi#18088]
### Required System information

- Node.js version: 16.20.0
- NPM version: 8.19.4
- Strapi version: 4.12.0
- Database: postgres
- Operating system: MacOs bash terminal in VSCode / Remote server is ubuntu
- Is your project Javascript or Typescript: Javascript

### Describe the bug

While trying to transfer from remote server to localhost, transfer process failing with Unexpected server response 200.

### Steps to reproduce the behavior

1. On my localhost I am running the following CLI command:
yarn run strapi transfer --from https://api.domain-name.com/make-good-habits-admin --from-token xyztokentakenfromstrapiadmin --force

2. The localhost console displays afterwards the following error message:
error: [FATAL] Failed to initialize the connection: Unexpected server response 200
Transfer process failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

3. On the ubuntu server, the console, where the app is started through docker-compose is displaying a:
strapi     | [2023-09-17 04:27:32.405] http: GET /make-good-habits-admin/transfer/runner/pull (4 ms) 200

### Expected behavior

Would expect transfer to happen :)

### Additional context

I copied the token generated from the strapi admin, si it should be the right one. I also double checked the admin url to be the right one, and it is. 

On a similar issue someone mentioned something about a proxy ... The server is behind a cloudflare cdn / and then on the server it has a traefik in front of it to direct traffic to the api/app subdomains.

Thanks for helping out!

**Comment by sg-code** [comment]
I have found that you must explicitly use the "/admin"  path to successfully initiate the `strapi transfer ...` command. This is regardless of whatever you may have changed your Strapi admin url to be in `./config/admin.js`. I was experiencing the same status 200 error prior to the aforementioned revelation.

E.g. Try `https://api.domain-name.com/admin` assuming your Strapi installation is at `https://api.domain-name.com/`

**Comment by Boegie19** [comment]
@onesoftwareengineer I assume the answer above solved your issue if it did not please respond to this issue and I will reopen it.

**Comment by drmahikbov** [comment]
I've still got the issue even with the `/admin` on the url. I'm running `npm run strapi transfer -- --from https://strapi.lets-med.com/admin --to-token <my-token>` and also with `--from-token` but neither work.

**Comment by drmahikbov** [comment]
This is my nginx config file

```# HTTPS for the both domains
server {
    server_name 92.205.23.204 strapi.dnhfarma.com strapi.lets-med.com;  # Replace with your VPS's IP address or domain name

    root /home/sites/letsmed/build/; # Path to your frontend's build directory
    index index.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    location /api/ {
        proxy_pass http://localhost:1337; # Adjust if Strapi is on a different port or host
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/strapi.lets-med.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/strapi.lets-med.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}



# HTTP to HTTPS redirects
server {

    if ($host = strapi.dnhfarma.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = strapi.lets-med.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name 92.205.23.204 strapi.dnhfarma.com strapi.lets-med.com;
    return 404; # managed by Certbot

}

# HTTPS strapi admin panel
server {
    server_name adminpanel.lets-med.com;

    location / {
        proxy_pass http://localhost:1337; # Assuming Strapi runs on port 1337
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
	proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
	proxy_pass_request_headers on;
	include proxy_params;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/adminpanel.lets-med.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/adminpanel.lets-med.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}





# This could be on the same server block as the other redirects
server {
    if ($host = adminpanel.lets-med.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name adminpanel.lets-med.com;
    return 404; # managed by Certbot


}```
