### ISSUE TITLE
Configuring the display of a relationship field does not work depending on the role since 4.12.1

### ISSUE THREAD

**Issue by nicoXXXXXtitan** [strapi/strapi#18108]
### Required System information

- Node.js version:16
- Strapi version: 4.13.6 
- Database: sqlite 
- Operating system: linux-x64 ubuntu 
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Looks like this [issue](https://github.com/strapi/strapi/issues/18072). 
A temporary solution has been found (see end of issue).  
After several attempts, the bug is present from  **4.12.1**

We have our users with the `editor` role who are having display problems on certain components that relate to certain types of content.  
The super admin has configured the view so that a label appears in this component. Unfortunately, it's the **component id** that's displayed. 
If I'm logged in as super admin, the display is correct. 
If I'm logged in as editor, the display is incorrect. It's the id that's displayed.

### Steps to reproduce the behavior

1. With editor role 
2. Go to a content type containing a component with a relationship to another content type. 
3. The super admin has configured the view for this content type to display a particular field (e.g. its label). 
4. The relationship field displays only the component identifier. 

### Expected behavior

I expect the input field to display the value of the selected field of the configured view, in my case the label.

### Workaround solution 
 
Grant the "editor" role read permission to content with the relationship. Display is correct again.

**Comment by Boegie19** [comment]
This change was made for security reasons see. the following advisories for more information if you have more questions feel free to ask them in here or join the discord and come to Open Office Hours (Mon - Friday 12:30 PM CST)
https://github.com/strapi/strapi/security/advisories/GHSA-m284-85mf-cgrc and https://github.com/strapi/strapi/security/advisories/GHSA-v8gg-4mq2-88q4

**Comment by nicoXXXXXtitan** [comment]
Hi

Thanks for the reply. 
What I think is a shame is that we don't know about this change to the view configuration. I've read all the releases but I haven't read anything that explains this change.
I have my editors who find themselves in their view, with fields not visible since the last strapi updates.
As you say, the super admin has to give them access to content types to solve this problem. 
But in our case, it's adding visible content types to their dasboards when they don't really need them.


Have a nice day!

**Comment by derrickmehaffy** [comment]
> Hi
> 
> Thanks for the reply. 
> What I think is a shame is that we don't know about this change to the view configuration. I've read all the releases but I haven't read anything that explains this change.
> I have my editors who find themselves in their view, with fields not visible since the last strapi updates.
> As you say, the super admin has to give them access to content types to solve this problem. 
> But in our case, it's adding visible content types to their dasboards when they don't really need them.
> 
> 
> Have a nice day!
> 
> 

What was being done was certainly never intended and was fixed as a security issue. According to our security policy: https://github.com/strapi/strapi/blob/main/SECURITY.md we will release the patches without detailed information in order to give time for users to update prior to publicly disclosing the details, of which were released  in our blog post: https://strapi.io/blog/security-disclosure-of-vulnerabilities-sept-2023

**Comment by nicoXXXXXtitan** [comment]
Hello

Sorry  @Boegie19 , I thought you worked at Strapi :)
And thanks also to @derrickmehaffy for your reply. I understand your security processes. 
My opinion is that it's annoying to come across regressions in the use of Strapi without it being considered a bug. 
Have a nice day

**Comment by derrickmehaffy** [comment]
> Hello
> 
> Sorry  @Boegie19 , I thought you worked at Strapi :)
> And thanks also to @derrickmehaffy for your reply. I understand your security processes. 
> My opinion is that it's annoying to come across regressions in the use of Strapi without it being considered a bug. 
> Have a nice day

Certainly I can agree, sadly we really don't have a choice here as the security implications are generally the most important, albeit, not the only factor when we need to take these decisions but we do take them with the best intentions for all of our users. We would rather a user have a minor inconvenience then to be at risk for data leaking in this particular case.

**Comment by nicoXXXXXtitan** [comment]
Obviously safety is the most important thing, I understand. 
Have a nice day
