### ISSUE TITLE
Admin crashes when editing the advanced settings of a datetime field

### ISSUE THREAD

**Issue by ivangonzalezg** [strapi/strapi#18123]
### Required System information

- Node.js version: v16.19.0
- NPM version: 8.19.3
- Yarn version: 1.22.19
- Strapi Version: 4.13.7
- Database: mysql
- Operating system: darwin-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When I am trying to edit the advanced settings of a datetime field of a collection type the admin crashes

```
TypeError: Be?.toDate is not a function
```

### Steps to reproduce the behavior

1. Go to Content-Type Builder
2. Click on any collection type or on create new collection type
3. Edit a datetime field or add date field and choose datetime as type
4. Click on advanced settings

### Expected behavior

Admin should allow edit the advanced settings of a datetime field.

### Screenshots

<img width="1552" alt="image" src="https://github.com/strapi/strapi/assets/42500072/066fbfbc-f39d-4a3d-b247-0dad1070f961">

<img width="1552" alt="image" src="https://github.com/strapi/strapi/assets/42500072/26bcf0ab-1c7e-4918-abb7-525cd66a23b6">

**Comment by modbender** [comment]
Yup having the same problem

**Comment by Sheikh-JamirAlam** [comment]
The problem is at the package `@strapi/design-system` line [195](https://github.com/strapi/design-system/blob/6233e279f773ccedd38dd179d2d3d21951bc1538/packages/strapi-design-system/src/DateTimePicker/DateTimePicker.tsx#L195)

**Comment by KKKaisar** [comment]
Same problem

**Comment by Simone-cm** [comment]
Having the same issue on a fresh project.

**Comment by andresmv94** [comment]
Same here
