### ISSUE TITLE
Error: could not upload provider "cloudinary". Vague error 

### ISSUE THREAD

**Issue by klammm** [strapi/strapi#18122]
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: `"@strapi/strapi": "4.1.8"`
- Database: Postgres
- Operating system: macOS 13.4.1 (c) (22F770820d)
- Is your project Javascript or Typescript: JS

### Describe the bug

Goal: To deploy my production env strapi application onto Heroku. 
Problem: Cloudinary is not being deployed properly. 

Vague error message of `Error: Could not load upload provider "cloudinary".` I have the strapi application working with Cloudinary on my development environment, however when I want to deploy to production, this is when I start to experience errors. 

Error in question:

<img width="1229" alt="Screenshot 2023-09-20 at 11 35 38 AM" src="https://github.com/strapi/strapi/assets/19962586/d785c3ec-a93e-401a-a6f5-98161a827b1e">

I've checked Heroku to ensure that my Cloudinary variables are in the Heroku env variables. I've even ensured that my `NODE_ENV` is set to `production`. 

<img width="821" alt="Screenshot 2023-09-20 at 11 41 45 AM" src="https://github.com/strapi/strapi/assets/19962586/353f6889-b4da-47f9-9497-4c001c4eca7f">

I suspect it's because of my folder structure. I've created a separate directory for production, where I've copied the exact same files into the production directory with the exception of `env/production/database.js` using postgres and `config/database.js` using sqlite .  `config/env/production`

Here's my current folder structure:

```
config 
  - env
    - production
      - database.js
      - middlewares.js
      - plugins.js
      - server.js
  - admin.js
  - api.js
  - database.js
  - middlewares.js
  - plugins.js
  - server.js
```

### Expected behavior

Successful strapi w/ Cloudinary deployment to Heroku

### Code snippets

my `package.json` dependencies: 

```
"dependencies": {
    "@strapi/plugin-i18n": "4.1.8",
    "@strapi/plugin-users-permissions": "4.1.8",
    "@strapi/provider-upload-cloudinary": "^4.11.7",
    "@strapi/strapi": "4.1.8",
    "better-sqlite3": "7.4.6",
    "pg": "^8.10.0",
    "pg-connection-string": "^2.5.0"
  },
```

Production files:

```
// config/env/production/database.js
const { parse } = require("pg-connection-string");

module.exports = ({ env }) => {
  const { host, port, database, user, password } = parse(env("DATABASE_URL"));

  return {
    connection: {
      client: "postgres",
      connection: {
        host,
        port,
        database,
        user,
        password,
        ssl: { rejectUnauthorized: false },
      },
      debug: false,
    },
  };
};

```

```
// config/env/production/middlewares.js
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "res.cloudinary.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "res.cloudinary.com",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];

```

```
// config/env/production/plugins.js
module.exports = ({ env }) => ({
  "users-permissions": {
    config: {
      jwtSecret: env("JWT_SECRET"),
    },
  },
  upload: {
    config: {
      provider: "cloudinary",
      providerOptions: {
        cloud_name: env("CLOUDINARY_NAME"),
        api_key: env("CLOUDINARY_KEY"),
        api_secret: env("CLOUDINARY_SECRET"),
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
});

```

```
// config/env/production/server.js
module.exports = ({ env }) => ({
  proxy: true,
  host: "0.0.0.0",
  port: process.env.PORT,
  url: env("MY_HEROKU_URL"),
  app: {
    keys: env.array("APP_KEYS"),
  },
  auth: {
    secret: env("ADMIN_JWT_SECRET"),
  },
});

```

```
// config/admin.js
module.exports = ({ env }) => ({
  auth: {
    secret: env("ADMIN_JWT_SECRET", "someStringNumber"),
  },
  apiToken: {
    salt: env("API_TOKEN_SALT"),
  },
});
```

```
// config/api.js
module.exports = {
  rest: {
    defaultLimit: 25,
    maxLimit: 100,
    withCount: true,
  },
};

```

```
// config/database.js
const path = require('path');

module.exports = ({ env }) => ({
  connection: {
    client: 'sqlite',
    connection: {
      filename: path.join(__dirname, '..', env('DATABASE_FILENAME', '.tmp/data.db')),
    },
    useNullAsDefault: true,
  },
});

```

The rest of the config files are exactly the same as the production files. 

### Additional context

I've been following the strapi/cloudinary guide on how to upload and deploy

**Comment by derrickmehaffy** [comment]
Please upgrade to a newer version of Strapi as the version you are on is quite old.
