### ISSUE TITLE
inaccurate floating-point in averagePrice Field When Creating a Restaurant.

### ISSUE THREAD

**Issue by bilal-auz** [strapi/strapi#18138]
### Required System information

- Node.js version: v18.17.1
- NPM version: yarn v1.22.19
- Strapi version: v4.13.6
- Database: sqlite
- Operating system: Win10
- Is your project Javascript or Typescript: Javascript 

### Describe the bug

When filling restaurant fields, a bug occurs when selecting an averagePrice of 0.06 using the arrow controls. The arrows provide inaccurate precision, resulting in 0.0600000001 instead of 0.06 when reaching this value. This issue randomly affects other values greater than 0.06.

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. From the 'Content' menu Click on 'Restaurant'
3. Click on 'Create new entry' in the top right.
4. Scroll down to 'averagePrice'
5. Using the arrow button increase the value until 0.06.
6. See the error 0.060000000000000005.

### Expected behavior

The averagePrice should display 0.06 and not 0.060000000000000005. 
The arrows should always return an accurate precision.

### Screenshots

![AveragePrice-Bug](https://github.com/strapi/strapi/assets/68505433/a3cf0da0-9883-4c84-857b-4d56c297bbb6)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by yurimutti** [comment]
Hi, I would work in this issue, can assign to me ?

**Comment by bilal-auz** [comment]
Hey,
I already patched it. I will open a PR now.
