### ISSUE TITLE
Upload API `/upload?id={id}` doesn't respect OpenAPI3 standard

### ISSUE THREAD

**Issue by jphuc96** [strapi/strapi#18130]
### Required System information

- Node.js version: v16.20.0
- NPM version: 8.19.4
- Strapi version: v4.13.7
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The API `/upload?id={id}` of Upload plugin doesn't respect OpenAPI3 standard, affecting validation and code generation tools.

### Steps to reproduce the behavior

1. Install official Documentation plugin
2. Generate any `full_documentation.json` file
3. Put the content into https://editor.swagger.io
4. It will tell validation error on `/upload?id={id}`: `Declared path parameter "id" needs to be defined as a path parameter at either the path or operation level`

### Expected behavior

It should follow OpenAPI3 api format, e.g: `/upload/info/{id}`

### Screenshots
<img width="815" alt="image" src="https://github.com/strapi/strapi/assets/11723964/37ccc35d-307e-4bed-988b-29b38fb73e39">

**Comment by derrickmehaffy** [comment]
We are no longer planning to focus on being compatible with OpenAPI and are focusing on the JSON API standard instead. See my comment on the linked PR.

I'll go ahead and close this one but thank you.

**Comment by DavithkbY** [comment]
Will this mean the swagger documentation plugin will stop being supported? @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> Will this mean the swagger documentation plugin will stop being supported? @derrickmehaffy 

In Strapi 5 we will give that package to a community member to maintain as indeed we do not plan to maintain it any longer ourselves since we choose not to use Open API as our standard.

**Comment by derrickmehaffy** [comment]
We plan on building our own way to generate types for the frontend in the future.

**Comment by Francoisbeche** [comment]
It's time to do it then. or maybe strapi is dead?
