### ISSUE TITLE
Media Library: creating thumbnail even when responsive is false

### ISSUE THREAD

**Issue by gregg-cbs** [strapi/strapi#18140]
### Describe the bug
Even though in the settings of Strapi I have set Responsive Media to false:
![270153724-bf26d6e5-310c-47c3-8daa-32abe2f8abf4](https://github.com/strapi/strapi/assets/57114335/b2e0e7c6-b744-42e5-a9b2-88dac9326970)

Two images are being created on each upload: thumbnail and normal:
![270153753-b4790c4b-e154-4332-b8df-e2c0020a62a7](https://github.com/strapi/strapi/assets/57114335/787a49f1-b1fc-450f-8ca3-b9062b3e93b0)

I did not expect this to be the behavior because I am using an external media manager like ImageKit which has the ability to transform images on the fly, i dont need the thumbail image that strapi creates. In fact I need strapi to use ImageKits urls and transforms instead.

Is there any way to turn off strapis default thumbnail creation?

### Steps to reproduce the behavior
1. Go to Media settings, turn off responsive
2. Notice in the uploads folder that two images get created
3. Thumbnail image is the one I am curious about

### Expected behavior
No thumbnail image to be made when response turned off.

**Comment by Boegie19** [comment]
@gregg-cbs I am 99% sure that this is not a bug but a feature in strapi's eyes. This is done to always have thumbnail images to use in the admin  the responsive upload disables.
https://github.com/strapi/strapi/blob/d62456ea471e44d21b938f21f0e91a567cdc6483/packages/core/upload/server/services/image-manipulation.js#L125-L129

Still will not close this Issue until a strapi employ confirms it so I can be 100% sure.

**Comment by Boegie19** [comment]
talked with somone of strapi and they confirmed this behavior is as intended and they won't change it. closing the issue.

**Comment by ngotrongphuc** [comment]
I found a way to disable thumbnail generation in Strapi v5. Simply add this file at ./src/extensions/upload/strapi-server.ts - it overrides the generateThumbnail method of the Upload plugin. Now thumbnails in the media library will use the original image URL as a fallback.
```ts
export default (plugin) => {
  // Override upload plugin to disable thumbnail generation
  plugin.services['image-manipulation'].generateThumbnail = () => {}
  return plugin
}
```
