### ISSUE TITLE
Datetime Input Field has weird design layout

### ISSUE THREAD

**Issue by exotexot** [strapi/strapi#18159]
### Required System information

- Node.js version: 18.17.1 (using latest node:18-alpine version)
- NPM version: 9.6.7
- Strapi version: 4.13.1
- Database: Postgres 14.5
- Operating system: Ubuntu 22
- Is your project Javascript or Typescript: JS

I'm using a Datetime Field. The width of the DATE is unnecessary wide, where's the width of the TIME component is too small.
In the Screenshot attached the field is 66% wide. The space usage isn't optimal. I think this could require a fix :)

![Screenshot 2023-09-25 at 17 53 34](https://github.com/strapi/strapi/assets/10153413/58d68b25-2e8b-4f77-a7b5-db5fd6d84133)

**Comment by M27afk** [comment]
Hey! I can try fixing this!
@exotexot @derrickmehaffy

**Comment by RakeshKumar010** [comment]
ok can you assign this issues? Because i am working on it.

**Comment by hustlerZzZ** [comment]
Hello sir (@exotexot ), Can you please assign this to me?
Thanks and Regards

**Comment by amerikan** [comment]
I have fixed issue and the PR is approved, just waiting for it to get merged.
