### ISSUE TITLE
Create new collection entry via GraphQL in a multi-node cluster environment returns no data (but entry was created)

### ISSUE THREAD

**Issue by DevPhilB** [strapi/strapi#18161]
### Required System information
- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.12.5
- Database: PostgreSQL 14 (Pgpool-II)
- Operating system: Alpine Linux (Docker)
- Is your project JavaScript or TypeScript: JavaScript

### Describe the bug

In our multi-node cluster environment (each node has a running Strapi Docker container) the creation via GraphQL yields sometimes no data. But the entry was created in the database and is visible in the Strapi Dashboard.
We tried to query the entry after the create mutation but we get the same empty result (even trying it multiple times leads to the same result).
We can't reproduce it in a local (no cluster) environment.

### Steps to reproduce the behavior

1. Set up a cluster with at least two nodes (each with a dockerized Strapi instance) and a PostgreSQL cluster with Pgpool-II
2. Strapi instances need at least one collection type
3. Create a new instance of any collection type via GraphQL mutation
4. Log the response (or try to query the created instance and log that response)

### Expected behavior
Response should always include the created collection entry.

### Additional context
We can't share code snippets but maybe with your tips and tricks, how to (better) debug/analyze this problem, we can share more details.

**Comment by policeakshithreddy** [comment]
"Would you kindly assign this task to me? I would greatly appreciate it."

**Comment by derrickmehaffy** [comment]
We don't assign issues outside the company but you can submit a PR.

To me this sounds like replication lag in the PG cluster which there is nothing we can do about that.

Can you check each node of your DB cluster to confirm the data is being properly replicated?

**Comment by DevPhilB** [comment]
Hi @derrickmehaffy,
thank you for your response.
The PG cluster has Streaming replication as clustering mode, so we expect that PostgreSQL takes care of it.
But we will take a closer look at the DB cluster and hopefully I can share more details soon.

**Comment by DevPhilB** [comment]
I have good news, the problem was that the nodes of the PG cluster were out of sync.
After synchronizing them we could no longer reproduce this issue.

**Comment by derrickmehaffy** [comment]
> I have good news, the problem was that some nodes of the PG cluster were out of sync.
> After synchronizing them we could no longer reproduce this issue.

Good to hear 😊
