### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'type') when click on the "filters" button on any collection type

### ISSUE THREAD

**Issue by riverus-dev** [strapi/strapi#18174]
### Required System information

- Node.js version: 18.17.0
- NPM version: 9.6.7
- Strapi version: 4.13.7
- Database: mysql
- Operating system: macOS Ventura 13.6
- Yarn version: 3.6.3
- Edition: Community
- Is your project Javascript or Typescript: Tested with Javascript and Typescript

### Describe the bug

When I click on the "filters" button on any collection type nothing happens

### Steps to reproduce the behavior

1. Go to Content Manager > Choose any collection
2. Click on Filters button
3. Choose createdBy option
4. See error in console

### Expected behavior

Show createdBy options box and choose an user to create a filter

### Screenshots

<img width="1240" alt="Screenshot 2023-09-26 at 16 31 09" src="https://github.com/strapi/strapi/assets/17548789/1a392c51-212e-4dd8-9a9e-508ab7ed88dc">

### Code snippets with STRAPI_ENFORCE_SOURCEMAPS=true

`Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at rd (helper-plugin.esm.js:51:1558)
    at rr (helper-plugin.esm.js:39:11056)
    at Re (SingleSelect.mjs:56:13)
    at Object.onChange [as current] (ui-primitives.mjs:681:31)
    at index.mjs:14:141
    at Object.onValueChange (index.mjs:18:33)
    at Ti (ui-primitives.mjs:1195:90)
    at index.mjs:4:149
    at Object.pt (react-dom.production.min.js:54:317)
    at ue (react-dom.production.min.js:54:471)`

**Comment by sumaiya2908** [comment]
The same issue is for updatedBy filter field as well.

**Comment by sumaiya2908** [comment]
Can I work on this issue? I have already fixed it on my local.

**Comment by riverus-dev** [comment]
How did you solved it? @sumaiya2908

**Comment by amerikan** [comment]
@sumaiya2908 I think you can just open a PR and they'll decide whether it's a valid fix.

**Comment by sumaiya2908** [comment]
Okay will. Can I assign it to myself then?
