### ISSUE TITLE
Monitor dependencies updates / vulnerabilities

### ISSUE THREAD

**Issue by avallete** [strapi/strapi#1818]
**What is the expected behavior?**

Since strapi is going to the 'one repo' model. And each package have specific dependencies. It would be great to still monitor each module individually (at least for the dependencies part).

I would like to propose the [Snyk](https://app.snyk.io) solution. 
> A developer-first solution that automates finding & fixing vulnerabilities in your dependencies

Why Snyk ?

1. He allow to generate report about security issues into dependencies periodically.
2. He propose detailed explanation of the vulnerability, and how to fix it.
3. He come with a really convenient tool to setup, update, and check repo.
4. He have github, travis,slack and more integration.
5. He is easy to setup.
6. He have unlimited, free tests limits for open sources projects.

I think this kind of control in addition of good test coverage will hugely improve the way that the new contributors can integrate to the project without code regression or security flaw injection.

**Comment by derrickmehaffy** [comment]
PR merged: https://github.com/strapi/strapi/pull/2435 will be in the next release
