### ISSUE TITLE
Handle auth provider as plugin

### ISSUE THREAD

**Issue by avallete** [strapi/strapi#1819]
**What is the expected behavior?**

Actually, to add a new auth provider, we must make several changes into the core of the `strapi-user-permissions` plugin.

It would be great to refactor this part to handle provider as in the 'upload' or 'email' plugin. By simply creating a new 'strapi-auth-xxxprovider' plugin.

To do that, we will need to refactor the `user-permissions` plugin, can take example on [plugin-email](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-email).

We will also probably need to extract each of the actual auth-providers into his own plugin (see: [here](https://github.com/strapi/strapi/tree/master/packages/strapi-email-mailgun) or [here](https://github.com/strapi/strapi/tree/master/packages/strapi-upload-rackspace) for examples).

**Comment by derrickmehaffy** [comment]
@avallete I spoke with @lauriejim on Slack and he also agrees these should be broken down into separate plugins to make it easier. This will be a big core change especially with the adminUI I think.

Also as a foot note and talking with Jim again, I think a change from grant/purest to passport is also something that should be looked at.

@Aurelsicoko do you have any ideas for making a move like this? If one of providers could be created, I could probably clone that and mirror it for a bunch of providers based from passport.

**Comment by derrickmehaffy** [comment]
Some examples based on current providers:

**Local**
https://github.com/jaredhanson/passport-local
https://github.com/cholalabs/passport-localapikey
https://github.com/pferretti/passport-local-token

**Discord**
https://github.com/nicholastay/passport-discord
https://github.com/RafaelVidaurre/passport-discord-oauth2

**Facebook**
https://github.com/jaredhanson/passport-facebook#readme

**Google**
https://github.com/jaredhanson/passport-google-oauth#readme

**Github**
https://github.com/jaredhanson/passport-github#readme

**Microsoft**
https://github.com/seanfisher/passport-microsoft

**Twitter**
https://github.com/jaredhanson/passport-twitter#readme

**Comment by derrickmehaffy** [comment]
To sum up my thinking is breaking the providers into separate plugins such as:

- strapi-provider-local
- strapi-provider-localkey
- strapi-provider-Discord
- strapi-provider-Facebook
- strapi-provider-Google
- strapi-provider-Github
- strapi-provider-Microsoft
- strapi-provider-Twtitter

Thus allowing other people to quickly and easily add and debug specific providers.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy It makes sense to me as well to split into different providers, I would prefer to wait until we introduce the plugin architecture updates and features. As I already said on Slack, we are thinking a lot about the plugins and how we can make them more flexible, more extensible & more everything. 

Each plugin should be thinking as an independent application... it's not the case right now.

**Comment by derrickmehaffy** [comment]
I hate to ask @Aurelsicoko any timeline on that, I've been waiting to try and fix the providers (PR: https://github.com/strapi/strapi/pull/1851 ) until we know if this type of change is going to be made.

Especially since it would make that PR pointless :stuck_out_tongue_closed_eyes:

**Comment by Aurelsicoko** [comment]
We will support this feature for sure! Please give me more insights on Product Board (https://portal.productboard.com/strapi/c/32-authentication-providers). I'm closing this issue because the need has been explained enough to me. However, feel free to comments and ping me if you want 👍

**Comment by derrickmehaffy** [comment]
No extra comments needed @Aurelsicoko :stuck_out_tongue_winking_eye: If you get the gist of what I was thinking I think it would make everything much easier in the future.

**Comment by adriatic** [comment]
Assuming that almost two years after the initial assignment of this task to @Aurelsicoko is still "alive" I would like to revisit the **[content proposal](https://github.com/strapi/strapi/issues/1819#issuecomment-422746896)** by @derrickmehaffy. Derrick's list of **[Identity Mangement](https://en.wikipedia.org/wiki/Identity_management)** Providers should start with three most often used ones, assuming that Strapi has the ambition to appeal to "serious" distributed application developers.

- **[Auth0](https://auth0.com/)**
- **[Okta](https://www.okta.com/)**
- **[AWS](https://aws.amazon.com/iam/)**

Current focus on basing Strapi Identity Management on **[Passport - Simple, unobtrusive authentication for Node.js](http://www.passportjs.org/)**, would most often be not perceived as sufficient.

I have many years long IM (Identity Management) experience and would like to offer advisory / project management help if this task gets activated.

**Comment by derrickmehaffy** [comment]
I hate to be that guy but you realize that auth0 started and maintains passport core right? Their entire lineup also uses passport in the backend

**Comment by adriatic** [comment]
Not sure that I understand the meaning of "I hate to be that guy but" - is it that you hate to disappoint  me with a reminder that my **[comment above](https://github.com/strapi/strapi/issues/1819#issuecomment-624893536)** is not as useful as I thought it to be?. 

My impression is that compared to my list of three providers Passportjs is a toy (based on my experience with using Auth0 in the context of mission critical applications). So, the validity of my **[today's comment](https://github.com/strapi/strapi/issues/1819#issuecomment-624893536)** is a function of the future Strapi plans - would it become a development tool for very secure apps.

Note that I am discussing adding these three providers - not replacing passportjs with them.

Lastly the links like http://www.passportjs.org/packages/passport-okta-oauth/ describe the "projection" of the "full bore" IM provider into passportjs context space.

**Comment by derrickmehaffy** [comment]
The key point @adriatic is simply not relaying on the current Grant/Purest framework and moving to something that is easier split into multiple providers, regardless of -who- the providers are is not the concern here, it's having a direct framework for others to build provider packages on top of. 

Strapi **will not** force users to use some outside software such as Auth0 to handle all their upstream providers as that goes against the self-hosted nature of Strapi (and likewise the open source)

Moving to passport means that anyone could create their own providers, and likewise Strapi can split providers outside of the users-permissions plugin. It has nothing to do with the providers themselves and is only acting as a middleware.

**Comment by adriatic** [comment]
Wow - feel like coming to a concert expecting Chopin's recital and finding a hip-hop performance. This is the first time seeing Grant/Purest framework, which you tagged as strapi's current, so I am clearly pass my depth ***in this ocean***. 😄 

If my suggestions **[above](https://github.com/strapi/strapi/issues/1819#issuecomment-624893536)** are just a subject of our **dialog** (meaning that nobody else plans to comment), than, please accept my apology (assuming that you perceived my suggestion too forceful). My intent was to see if strapi plans to appeal some "bigger players", by offering support for the state of the art Identity management.

**Comment by derrickmehaffy** [comment]
> assuming that you perceived my suggestion too forceful

I didn't, it's all good :wink: 

But the end goal is to not directly loop in outside service, but provide a middleware layer to allow users to incorporate them (hence providers)

Instead of `Strapi => Auth0` it would be `Strapi => Auth0 Provider (Passport) => Auth0` with the key benefit being anyone can make a provider for any service and it doesn't have to be directly committed into core code that Strapi then has to manage and maintain.

**Comment by adriatic** [comment]
I like when things are good 😉. Please check my **[added comment](https://github.com/strapi/rfcs/issues/9#issuecomment-626317856)**.
