### ISSUE TITLE
Sponsored issue: Forgot-password: no email sent with sendmail

### ISSUE THREAD

**Issue by fikewa22** [strapi/strapi#18192]
When interacting with Strapi through its API, I've noticed that email notifications are not being sent as expected. Specifically, I have set up email notifications to be triggered when users perform certain actions on my website, such as signing up, resetting passwords, or receiving important updates. However, no emails are being delivered to the recipients.

## Priority Support

- @fikewa22 is using  [Mintycode](https://mintycode.io) to fund this issue.
- If you would like to accept ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) bounty for solving this issue join [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=9253f811-e80a-450e-b0cc-d589aecfb440&owner=strapi&name=strapi).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by Janaki4** [comment]
Hey @fikewa22 , Can i take this issue ?
Do you mind to explain about thus MintyCode
