### ISSUE TITLE
Enhance error UI if the image upload process had an error

### ISSUE THREAD

**Issue by trungnouden1108** [strapi/strapi#18202]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.13.6
- Database: SQLite
- Operating system: Linux
- Is your project Javascript or Typescript: JS

### Describe the bug
I used the plugin extension to require the alternative Text field when uploading an image.
Then I uploaded the image without alternativeText. 
The error UI appears but I can't add alternativeText right now. Instead I had to turn off the modal and upload the image again. 
So can we improve this error UI or not?
### Steps to reproduce the behavior

1. Using plugin extension to require alternativeText
2. Upload image without alternativeText
3. See error

### Expected behavior
During the process of uploading images, if any image has an error, it can be edited at that time.
### Screenshots
![image](https://github.com/strapi/strapi/assets/55272632/9c4a6bb4-c5c0-415e-a79b-389cf8655e00)

**Comment by harshitkandpal** [comment]
can i handle this issue ?
