### ISSUE TITLE
List view preview for new blocks editor shows [object Object]

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#18203]
### Required System information

- Node.js version: v18
- NPM version: v9
- Strapi version: 4.14.0
- Database: SQLite
- Operating system: Linux Mint 21.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When using the alpha blocks editor, the list view doesn't render the content itself and tries to show the raw JSON structure.

### Steps to reproduce the behavior

1. Create a new content-type
2. Add the new editor
3. Create some content and save
4. Go back to the list view
5. See malformed preview

### Expected behavior

We should parse the JSON structure in the admin and render a normal preview such as with the markdown editor

### Screenshots

![image](https://github.com/strapi/strapi/assets/8593673/ab1aceda-85e8-4d8a-8cab-3d2b7254c47b)

### Code snippets

N/A

### Additional context

N/A

**Comment by rayyyyofsunshine** [comment]
Hey can you assign this to me? So i can work on this?

**Comment by amerikan** [comment]
@derrickmehaffy I tried to see how the older Markdown editor previews currently appear, but actually they don't even show up as previews on the List View so not sure if that's a bug on itself or expected.

**Comment by derrickmehaffy** [comment]
> Hey can you assign this to me? So i can work on this?

Sorry no, we will work on this ourselves, a lot of code going around already from internal team members

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I tried to see how the older Markdown editor previews currently appear, but actually they don't even show up as previews on the List View so not sure if that's a bug on itself or expected. 

On just 4.14 or also 4.13? 

(Didn't check on 4.14)

**Comment by amerikan** [comment]
> > @derrickmehaffy I tried to see how the older Markdown editor previews currently appear, but actually they don't even show up as previews on the List View so not sure if that's a bug on itself or expected.
> 
> On just 4.14 or also 4.13?
> 
> (Didn't check on 4.14)

I was on main branch.

**Comment by markkaylor** [comment]
> render a normal preview such as with the markdown editor

This is a known issue we are currently working on. I have a PR open https://github.com/strapi/strapi/pull/18207

Thank you for reporting. I do not believe we show anything in the ListView for the markdown editor and we are planning to do the same for the new Rich Text Editor (blocks)
