### ISSUE TITLE
some issues with model lifecycle and component

### ISSUE THREAD

**Issue by trungnouden1108** [strapi/strapi#18219]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.13.6
- Database: SQLite
- Operating system: Linux
- Is your project Javascript or Typescript: JS

### Describe the bug

I use lifecycle `beforeUpdate, beforeDelete` to verify data before Update/Delete.
When I update the data component. The lifecycle throw error as expected but when I press F5, the data is still update.

**_Component in dynamic zone also has the same error_**

### Steps to reproduce the behavior

1. Create schema content component
2. Create data
3. Write hook beforeUpdate to verify
4. The UI show error but data is still update when press F5

### Expected behavior
The data can not update
### Screenshots
**- Schema**
![image](https://github.com/strapi/strapi/assets/55272632/8a6811a6-4027-4743-8bba-2583ec22e1d7)

- **The example lifecycle model**
![image](https://github.com/strapi/strapi/assets/55272632/2f27e801-b6c0-400f-bbbe-51b76c182d51)

- **The data created**
![image](https://github.com/strapi/strapi/assets/55272632/96c55328-5c88-4c83-bfe8-17a1d60b5553)

- Update data with error
![image](https://github.com/strapi/strapi/assets/55272632/f6f4a33a-ce8c-4d52-99ec-0933106d1a97)

- The data is still updated when press F5
![image](https://github.com/strapi/strapi/assets/55272632/cb9307ad-e1b1-4e9f-b03b-6610c3f78046)

**Comment by Boegie19** [comment]
This is expected behavior and not possible since this is done on such a low layer query engine layer last thing it does before sending it to the database layer. that it does not know about the components anymore.
See https://feedback.strapi.io/feature-requests/p/lifecycle-hooks-for-components for the suggestion for lifecycle hooks for components.
