### ISSUE TITLE
npx create-strapi-app@latest only works on gallium (Node v16.20.2) on some architectures

### ISSUE THREAD

**Issue by dinosoeren** [strapi/strapi#18222]
### Required System information

- Node.js version: 18.18.0
- NPM version: 9.8.1
- Strapi version: latest (4.14.0)
- Database: SQLite (`--quickstart`)
- Operating system: WSL 2 (Ubuntu) and Ubuntu LTS 22.04 inside Distrobox on Arch
- Is your project Javascript or Typescript: Javascript

### Describe the bug

The `create-strapi-app` command fails when running on the described architecture above, as well as when using node `v20.8.0` (npm `10.1.0`).

Specifically, it hangs and gets stuck while installing, frequently on `idealTree:root` or `sill idealTree builddeps`. I tried rebooting, disabling IPv6 in my Network settings & setting it to "Link-Local", using flags to disable HTTPS `--registry http://registry.npmjs.org --strict-ssl false`, running `npm cache clear --force` and using another registry, all to no avail.

I was only able to get a (mostly) successful run of the command using node `v16.20.2` (npm `8.19.4`). The only error was the port 1337 was already in use by something else.

### Steps to reproduce the behavior

1. Run `$ npx create-strapi-app@latest strapi-test --quickstart` in an Ubuntu terminal
2. Observe first `npm fetch` might hang forever, or any from second to fifth `npm fetch`
3. command never completes

### Expected behavior

The install should either error out immediately with a suggestion to use the compatible version of node, or it should finish installing and create the app directory.

### Screenshots

![1 Attached: Console npm info logs](https://i.ibb.co/n63g2q3/strapi-debug-Screenshot-20231001-161540.png)

### Code snippets

N/A

### Additional context

N/A

**Comment by Boegie19** [comment]
@dinosoeren Does this only happen with strapi or also with other packages?
