### ISSUE TITLE
Query to DB doesn't return same results depending in lifecycle hooks

### ISSUE THREAD

**Issue by ulysse-lacour** [strapi/strapi#18229]
### Required System information

Environment: development
OS: darwin-x64
Strapi Version: 4.13.5
Node/Yarn Version: yarn/1.22.19 npm/? node/v16.19.0 darwin x64
Edition: Community
Database: postgres
Typescript: yes

### Describe the bug

I'm tryin to have truly localized unique values for slug but facing a very weird issue, my query is finding entry with same slug when querying inside beforeCreate (legit) but doesn't find anything inside beforeUpdate, which doesn't really make sense to me...

### Expected behavior

Having consistant query results

### Code snippets

```javascript
let slugify = require("slugify");
const { ApplicationError } = require("@strapi/utils").errors;

export default {
  async beforeCreate(event) {
    await uniqueValidator(event);
  },

  async beforeUpdate(event) {
    await uniqueValidator(event);
  },
};

const uniqueValidator = async (event) => {
  console.log(event);

  const uid = event.model.uid;
  const { data } = event.params;

  // Generate Slug if not provided
  if (!data.Slug && data.Name) {
    data.Slug = slugify(data.Name, { lower: true });
  }

  // Check for uniqueness of specified fields within the current locale
  if (await isUniqueInLocale(data, uid)) {
    throw new ApplicationError(
      "Slug must be unique within the current locale."
    );
  }
};

const isUniqueInLocale = async (data, uid) => {
  const existingEntry = await strapi.query(uid).findOne({
    where: { Slug: data.Slug, locale: data.locale },
  });

  console.log(existingEntry);

  return existingEntry;
}; 
```

**Comment by Boegie19** [comment]
the update only returns that data that could have changed when send from the admin and the data the user send from the api. locale is not in the object. since object should never change after it has been set. that is why it is returning noting since it is searching for local undefined what does not exist.

**Comment by ulysse-lacour** [comment]
@Boegie19 thanks a lot for your answer, so it's not possible to use local as a search params within update hook ?
I haven't find anything regarding that in Strapi doc...

**Comment by ulysse-lacour** [comment]
I'm at the point where I'm actually needing a way to have the currently edited item locale to check if "doublon" is from same locale (=> raise uniqueness error) or different one (all good)

**Comment by Boegie19** [comment]
@ulysse-lacour you always get the id and the content-type. so what you can do is get the data you need from there.
add/remove the changes made that the lifecyle got and you should be able to use the same function.
