### ISSUE TITLE
Allow any valid JSON data in the JSON field - not just objects

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1823]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: .6.2.0
- **Strapi version**: alpha 13.1
- **Database**: pg
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**
Maybe also related to #784 - being able to input an array would be nice.
I'd expect any valid JSON to be allowed in a JSON field. But this is not true.
![image](https://user-images.githubusercontent.com/2950505/44689102-a8297a00-aa56-11e8-9f1a-e4e223664697.png)

Actually, internally the type is `unknown` for postgres. Shouldn't this be a `text`?

![image](https://user-images.githubusercontent.com/2950505/44689188-eb83e880-aa56-11e8-923e-b02995b76bc4.png)

**Steps to reproduce the problem**

- Create a JSON field
- enter in any non-object JSON, such as `true` `"true"`, `0`, `[1,2,3]` or `[{"json": "valid"}]`

![image](https://user-images.githubusercontent.com/2950505/44689350-88468600-aa57-11e8-9c7b-2e29aef157ae.png)

By the way, I don't get `invalid` for an array, but for strings, numbers and boolean values.

**What is the expected behavior?**

Allow any valid JSON and use a real JSON validator instead.

**Suggested solutions**

Even though it looks like the database reports that problem, I don't believe that its the dbs fault.
This is a task for both back and front-end either way. 
1. Correctly showing if the JSON is valid
2. adjust type for DB or fix validation for JSON in bookshelf (if there is any)

**Comment by Aurelsicoko** [comment]
@soupette How do we process this? In my memories, we are trying to JSON.parse() the value inserted in the field. If the parsing doesn't throw an error, it's valid if not we consider the value as an invalid JSON.

**Comment by soupette** [comment]
@Aurelsicoko yes we do the following check 
```
try {
  JSON.parse(JSON.stringify(value);
catch(e) {
  // Display invalid json
}

```

**Comment by derrickmehaffy** [comment]
Related branch: https://github.com/strapi/strapi/tree/fix/1823
