### ISSUE TITLE
Provider: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ainsleyclark** [strapi/strapi#18244]
### Required System information

- Node.js version: v20.1.0
- NPM version: 9.6.4
- Strapi version: 4.14.0
- Database: Postgres
- Operating system: MacOS Arm
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When creating a provider from the documentation, a `SyntaxError: Cannot use import statement outside a module` error is thrown when trying to run dev.

```
backend:dev: /providers/strapi-provider-upload-myprovider/src/index.ts:1
backend:dev: import * as utils from '@strapi/utils';
backend:dev: ^^^^^^
backend:dev: 
backend:dev: SyntaxError: Cannot use import statement outside a module
```

### File Structure:

`/package.json`
```
"strapi-provider-upload-myprovider": "file:providers/strapi-provider-upload-myprovider", 
```

`/providers/strapi-provider-upload-myprovider/src/index.ts`
```ts
import * as utils from '@strapi/utils';

export default {
	init(providerOptions) {
               //etc
        }
}
```

`/providers/strapi-provider-upload-myprovider/package.json`
```ts
{
	"name": "strapi-provider-upload-myprovider",
	"version": "1.0.0",
	"main": "./src/index.ts",
	"license": "MIT",
	"dependencies": {},
	"engines": {
		"node": ">=16.0.0 <=20.x.x",
		"npm": ">=6.0.0"
	}
}

```

### Expected behavior

No error thrown.

**Comment by Boegie19** [comment]
You need to build your plugin. to JS before loading it into strapi.

**Comment by ainsleyclark** [comment]
@Boegie19 thanks for your reply.
I didn't think there was a specific build script for providers as it wasn't on the docs. Would you mind pointing me in the right direction?

**Comment by Boegie19** [comment]
in the plugin folder you run yarn build or npm run build.

**Comment by ainsleyclark** [comment]
Whats the script for building providers? On the offical upload ones it's `run -T tsc`. Is that along the right lines?

**Comment by ainsleyclark** [comment]
Anyone looking in the future for npm:

```
{
	"scripts": {
		"build": "tsc --build",
		"build:ts": "run -T tsc"
	},
	"main": "./dist/index.js",
	"types": "./dist/index.d.ts",
	"files": [
		"./dist"
	],
}
```
