### ISSUE TITLE
TypeScript error after upgrading to Strapi 4.14.2

### ISSUE THREAD

**Issue by lucasprins** [strapi/strapi#18259]
## Required System information
- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.14.2
- Database: PostgreSQL
- Operating system: Linux
- Is your project Javascript or Typescript: TypeScript

```sh
$ yarn build
yarn run v1.22.19
$ strapi build
src/index.ts:56:88 - error TS2345: Argument of type 'ID' is not assignable to parameter of type 'import("/home/Strapi/node_modules/@strapi/types/dist/modules/entity-service/params/attributes").ID'.
  Type 'string' is not assignable to type 'ID'.

56           const link = await strapi.entityService.update('api::restaurant.restaurant', restaurantId, {
                                                                                          ~~~~~~~~~~~~

Found 1 error(s).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JuliusGudni** [comment]
Is this happening in a custom controller? If so, where does "restaurantId" come from?

**Comment by Boegie19** [comment]
can you run `yarn strapi ts:generate-types --debug` or `npm run strapi ts:generate-types --debug` and see if it fixes the error?

**Comment by lucasprins** [comment]
Sorry this was a issue in the custom bootstrap function. Sorry for wasting your time.
