### ISSUE TITLE
Media Kit redirect you to Not Found page

### ISSUE THREAD

**Issue by mozi47** [strapi/strapi#18273]
**BUG REPORT**
The Media Kit page redirects to the "Not Found" or "Page Not Exist" Page.
![image](https://github.com/strapi/strapi/assets/20722868/ff9300af-f15d-4b61-a084-684b6b1168cb)

**SOLUTION**
Either it should be Redirecting to the handbook page "https://handbook.strapi.io/" or marketing manual page "https://handbook.strapi.io/marketing-manual"

**Comment by Gowrish7** [comment]
I can work on this .

**Comment by Boegie19** [comment]
@mozi47 where is the origin of the link?

**Comment by Boegie19** [comment]
@Gowrish7 This is the strapi employ handbook so I don't think you can work on that.
