### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1828]
**What is the expected behavior?**

Recently I started to dive a little bit into development with Strapi.
I were following the guide outlined on the [contributing](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#setup-development-environment) page and I found it is barely possible to get started.

I'm using WSL/Ubuntu on Windows and after 20 minutes I get package linking errors.

Is this _THE_ preferred way to work on strapi? change a line and wait for the build, before I can test again?

Clearly there must be a better and saner way to debug and develop the core strapi packages.
I wonder if the Strapi team uses a different approach internally.

**Problems with the current approach**
The problem with debugging strapi, is that essentially every package works in isolation with links to other packages within the same mono-repo. Also, the documentation does not state, if the setup is required again after changing something in the software. Usually `npm link` creates symlinks. But I wouldn't need strapi to be in my global scope at all **anyway**. Because this way, I can only develop for **one** single installed repository. If I want to debug a fork, a pull request or something else, I would have to run the entire `npm run setup` again, and have it replaced with my other global `strapi` install!

**Proposal:**

I wouldn't need to have the global cli tool linked to the packages. I'd be happy to generate the project using the direct script path. This way, I can also use `node --inspect`. The only problem then, is that with `strapi new` does not support other paths than the current folder. Generally all strapi scripts work like that.

This would allow developers to benefit from the following:

- Strapi development works faster without linking (only the dependencies have to be referenced via `file:../strapi-utils`
- Strapi can be debugged using native node debugger protocols. (`node --inspect`)
- Any strapi project can be simply `git pull`ed and debugged without overloading the global cli

I would love to help in achieving this. If there are any technical constraints that do not allow that flexibility or make it hard to achieve, please let me know!

**Comment by derrickmehaffy** [comment]
2nd this from me, especially when helping others out, I really don't want to blow out my global/local installed strapi just to work on another project.

I am aware of running the adminUI separately with live updates and not having to rebuild, but you can't even connect to this if it isn't running on your local machine (using remote VMs to not ~~f*ck~~ up my local strapi install)

A Strapi project should be self contained, I realize there may be limits when dealing with the global package for creating a new strapi project via the CLI, but as @MartinMuzatko has stated if you are trying to debug multiple projects at a time this can be quite difficult.

**Comment by MartinMuzatko** [comment]
A few more thoughts:

Generated projects rely on the globally installed strapi installation if I'm not mistaken.
This is also easily resolvable by pointing the package in the generated projects package.json to the local strapi.

When debugging strapi, I have some dependencies on my project, and some on strapi. I'd love to be able to debug both at the same time.

**Comment by Aurelsicoko** [comment]
I like a lot of things in your thoughts! You've pointed out a pain that we have when developing with Strapi. Everytime, we move from a branch to another, it's safer to run a complete setup by running `npm run setup` to avoid mislinking packages. Also, our current approach doesn't allow us to work on different issues at the same time without making a brand new setup. You can but it's not easy as it can be.

**Things I would love to be able to do when contributing:**

- Install multiple mono-repo of Strapi on my computer. 
- Create a new app and choosing the mono-repo to be linked with by passing the path in the CLI. (`strapi new app --linkTo /Users/xxx/Workspace/strapi`).
- Be able to have a global install of Strapi (installed from npm) and many others install using the mono-repo.

**Comment by Restry** [comment]
@derrickmehaffy @Aurelsicoko  if i have run 'strapi new projectname' in my home mac, it running good . so i push it to my github. i pull my repo when i'm go to office mac with save env.  now problem it coming , how can i run it ?

 i have try 
`
npm install
npm run setup 
npm start
`

i can open admin panel . but the plugin its missing . content type it's missing .

so do we support this ?  anybody help me ? thanks :(

**Comment by derrickmehaffy** [comment]
@Restry this isn't the issue for problems, this is feature discussion. Please create a new issue.

**Comment by lauriejim** [comment]
Hello! I close this issue since we are changing the project architecture and the setup of the mono repo.
We are working on making this stuff really easier!
