### ISSUE TITLE
Error: v4.14.3 fatal: unable to access 'https://github.com/strapi/ts-zen/

### ISSUE THREAD

**Issue by franckadil** [strapi/strapi#18299]
### Required System information

- Node.js version: 18 latest
- Yarn version: v1.22.19
- Strapi version: v4.14.3
- Database: MySQL 5.7
- Operating system: Base-alpine Latest
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Error when trying to run `yarn install `  : **fatal: unable to access 'https://github.com/strapi/ts-zen/**

```console
Output:
2023-10-04 18:21:48 fatal: unable to access 'https://github.com/strapi/ts-zen/': Could not resolve host: github.com
2023-10-04 18:22:45 error Command failed.
2023-10-04 18:22:45 Exit code: 128
2023-10-04 18:22:45 Command: git
2023-10-04 18:22:45 Arguments: ls-remote --tags --heads https://github.com/strapi/ts-zen
2023-10-04 18:22:45 Directory: /srv/app
```

**Comment by Boegie19** [comment]
issue is most likley related to this line. https://github.com/strapi/strapi/blob/ddcbafe9d95cdf6c68a607bc6dc3da2ca44a65f2/packages/core/types/package.json#L57

**Comment by Boegie19** [comment]
https://github.com/strapi/strapi/pull/17905

**Comment by Convly** [comment]
Hey there, I could not reproduce your issue with a fresh install. (Were you able to @Boegie19?)

Could you guide me through the steps you took in order to get this error?

**Comment by joshuaellis** [comment]
@Convly it's because git is not installed in docker environments (or equivalent – probably)

**Comment by Convly** [comment]
Nice catch on the fact that this is on docker :eyes: 

Could you share with us your docker config @franckadil?

**Comment by Convly** [comment]
From my very brief search, several people are talking about upgrading docker itself to fix the issue

https://github.com/composer/docker/issues/165

But most of those resources are from 2021. Not sure it's related 100%. (the issue looks the same though)

**Comment by Boegie19** [comment]
Did not confirm it myself the issue is more why are we even using a github link and not just publishing the package?

**Comment by Boegie19** [comment]
Did not confirm it myself the issue is more why are we even using a github link and not just publishing the package?
