### ISSUE TITLE
Use locale config on frontend-side

### ISSUE THREAD

**Issue by ghost** [strapi/strapi#1829]
**What is the expected behavior?**

Documentation has a [language config](https://strapi.io/documentation/configurations/configurations.html#language) . `defaultLocale` set a default locale on app. But on frontend-side  not fetching defaultLocale from server and calc this by simple algorithm `foundLanguage || first(languages) || 'en'`. I suggest add api method `appConfig` or something else and use server-config in frontend-side

**Comment by lauriejim** [comment]
Hello @nobodywithbody!
It's just to give more information about translations.

Language configs on the back-end part is based on `./config/locales/xxx.json` files.

And the front-end part is based on `./admin/src/translations/xxx.json` files.

So it can manage completely different languages between back-end and front-end.

A sugg

**Comment by nobodywithbody** [comment]
What a case should be in different language on backend and frontend? IMHO, language is user specific option. User enter in CMS, set language and frontend display in selected language and backend generate message in this language.
