### ISSUE TITLE
Creating a "has many" relation with self-referencing content-types breaks the Admin Panel.

### ISSUE THREAD

**Issue by rorybokser** [strapi/strapi#18327]
### Required System information

- Node.js version: v20.4.0
- NPM version: 9.7.2
- Strapi version: v4.11.5
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When attempting to create a relationship between two entities of the same content-type in the Strapi Admin Panel, I encounter : "Woops! Something went wrong. Please, try again.".

I am able to create these relations programmatically with no issue, so it appears to be an Admin Panel bug only.

### Steps to reproduce the behavior

1. Create a content-type with a "has many" relationship to itself, e.g. Post has many Posts.
2. Create a first Post.
3. Create a second Post, and attempt to link it to the former.

### Expected behavior

The relation should be created and displayed in the admin panel.

### Screenshots
<img width="845" alt="Screenshot 2023-10-05 at 2 58 20 PM" src="https://github.com/strapi/strapi/assets/10871891/9184b71b-74bf-457a-83d0-ec3733aef142">
<img width="638" alt="Screenshot 2023-10-05 at 2 58 07 PM" src="https://github.com/strapi/strapi/assets/10871891/ef9628cc-1869-437f-bd13-e942741ac79d">
<img width="878" alt="Screenshot 2023-10-05 at 3 04 33 PM" src="https://github.com/strapi/strapi/assets/10871891/f73f7840-4aaa-4e51-b64d-7c6c3c79a96f">
<img width="1210" alt="Screenshot 2023-10-05 at 3 03 29 PM" src="https://github.com/strapi/strapi/assets/10871891/de033a22-991f-4937-bf47-b289ce24a7c4">

### Code snippets

Here is the console error:
```
main.22cb1a11.js:29 TypeError: ci.normalize is not a function
    at startsWith (main.22cb1a11.js:7005:40229)
    at main.22cb1a11.js:7005:51109
    at Cl (main.22cb1a11.js:27:20601)
    at Cc (main.22cb1a11.js:29:1593)
    at Pm (main.22cb1a11.js:29:47476)
    at sm (main.22cb1a11.js:29:41046)
    at pp (main.22cb1a11.js:29:40974)
    at xg (main.22cb1a11.js:29:40826)
    at nd (main.22cb1a11.js:29:37073)
    at au (main.22cb1a11.js:29:37882)
```

**Comment by Boegie19** [comment]
@rorybokser can you try to and update to the latest version and then try to `yarn build`

**Comment by rorybokser** [comment]
This seems to be fixed, thanks

**Comment by ye1dos** [comment]
@Boegie19  which version should I update to?

**Comment by derrickmehaffy** [comment]
Will go ahead and mark this as resolved

@ye1dos I'd recommend at minimum 4.14.6 but 4.15.5 or 4.16.2 are both fine also.
