### ISSUE TITLE
Missing default router-prefix value

### ISSUE THREAD

**Issue by SimpleCookie** [strapi/strapi#1832]
Version 3.0.0 alpha

**What is the current behavior?**
Strapi router prefix value is empty by default, however it is set to '/' I guess...

**Steps to reproduce the problem**
Change the value to /api
test the api and it works
remove the value to empty string
Results in "missing parameter" ..

**What is the expected behavior?**
Should either automatically set the value to '/' or have '/' as a default value in the input

**Suggested solutions**
Should either automatically set the value to '/' or have '/' as a default value in the input

**Comment by SimpleCookie** [comment]
And after changing the value to /api, if you go to `content manager`, then the images will not load.
If page is refreshed after this, then following error message will be shown:
`{"statusCode":404,"error":"Not Found","message":"Not Found"}`

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1323

**Comment by SimpleCookie** [comment]
@derrickmehaffy It's not a duplicate.
I am also mentioning that the input field is missing the default value.

**Comment by derrickmehaffy** [comment]
@SimpleCookie the "/" is not needed as a default, changing the prefix right now is known to break stuff.

**Comment by SimpleCookie** [comment]
@derrickmehaffy the solution is simple, just set the value to '/' as default. I tested it myself. Was gonna send in a PR but did not because I had no time for it. If the value in the logic is /, then the input should mirror that value imo. It makes sense, right?
