### ISSUE TITLE
Media Music file upload error

### ISSUE THREAD

**Issue by OsborneWafer** [strapi/strapi#18349]
Hello Team,
                  I keep getting this error when submitting a form with Media file. Does anyone have any idea what this is about?
![image (3)](https://github.com/strapi/strapi/assets/112384491/7e87943c-69a8-48ac-9eed-bc230dfd0075)

**Comment by nikita-fuchs** [comment]
It looks like it cannot find `ffprobe`, which is a tool to read metadata from media files. In my `package-lock.json` I can't find the `node-ffprobe` package (but I'm also not not the latest strapi version), where 'does it come from' in your case?

In your case, strapi or some plugin tries to run a system process, ffprobe, to extract media info, which as a solution is a bit over the top imho, as there are more lightweight, node-based alternatives. Will follow this curiously. There is a similar issue here: https://github.com/strapi/strapi/issues/15505

**Comment by OsborneWafer** [comment]
Hello @nikita-fuchs thanks for the response. I get this when trying to submit a form which allows uploading media files. It happens after I call the insert api call. Also I am not using the latest Strapi version.
