### ISSUE TITLE
Strapi admin panel now just showing "success forbidden" and not the error message

### ISSUE THREAD

**Issue by adwinang** [strapi/strapi#18371]
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.6.7
- Strapi version: 4.14.3
- Database: sqlite
- Operating system: macOS and Ubuntu
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I recently upgraded from Strapi v4.13.7 to v4.14.3. I am encountering a problem that I didn't have in 4.13.7, where when the ForbiddenError is thrown, the message is not being shown in the Admin Panel. And just showing "Success Forbidden"

### Steps to reproduce the behavior

1. Throw a ForbiddenError in any content-type lifecycle hooks
2. Attempt to perform the action corresponding to the lifecycle hook on the admin panel
3. See that the error is appearing in admin panel, but the message is not showing in the admin panel

### Expected behavior

This is before I updated Strapi
![Screenshot 2023-10-10 at 1 06 14 AM](https://github.com/strapi/strapi/assets/34839258/346d7990-cfd0-4639-b659-f70bb81fdac7)

### Screenshots

This is what I am seeing
![Screenshot 2023-10-10 at 1 03 05 AM](https://github.com/strapi/strapi/assets/34839258/99fc3a38-b681-4d34-acc4-cff08ec74451)

### Code snippets

```
import utils from "@strapi/utils";

const { errors } = utils;

export default {
    async beforeCreate(event) {
        throw new errors.ForbiddenError("Sample error");
    }
}
```

### Additional context

The message is important to let the admin users know what is the error related to.

**Comment by Boegie19** [comment]
If you use an application error instead that should fix this issue.

**Comment by Boegie19** [comment]
fixed in https://github.com/strapi/strapi/pull/18372 so will be fixed in the next release

**Comment by adwinang** [comment]
@Boegie19 the problem is not fixed. It still exists
