### ISSUE TITLE
Media url should be contains folder name

### ISSUE THREAD

**Issue by trungnouden1108** [strapi/strapi#18385]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.13.6
- Database: SQLite
- Operating system: Linux
- Is your project Javascript or Typescript:

### Describe the bug
Media url should be `host/uploads/<folder_name>/<file_name>` instead of `host/<file_name>`
### Steps to reproduce the behavior

1. Go to Media library
2. Create new folder **Test**
3. Go to the folder **Test**
4. Upload file capture.png
5. Save
6. See error

### Expected behavior
The media url should **localhost:1337/uploads/test/capture.png**
### Screenshots
![image](https://github.com/strapi/strapi/assets/55272632/0debca29-1747-4e33-a53e-90a13bbf3e45)
![image](https://github.com/strapi/strapi/assets/55272632/25fd1428-ee60-4e43-895a-093d1a2f0ad9)

**Comment by Rohits20** [comment]
@trungnouden1108 Hi Nouden, if you need help with this bug then please assign it to me. I would be happy to resolve this.

**Comment by derrickmehaffy** [comment]
These aren't physical folders, just logical so what exists currently is intended.

Marking as closed as this isn't a bug.
