### ISSUE TITLE
Crash in HeaderParser in dicer

### ISSUE THREAD

**Issue by rkristelijn** [strapi/strapi#18398]
## Bug report

@strapi/plugin-graphql@4.14.3 uses a vulnerable version of dicer. 

```
└─┬ @strapi/plugin-graphql@4.14.3
  └─┬ graphql-upload@13.0.0
    └─┬ busboy@0.3.1
      └── dicer@0.3.0
```

### Required System information

-  "@strapi/plugin-graphql": "^4.14.3"

- Node.js version: `v18.17.0`
- NPM version: `v9.6.7`
- Strapi version: `v4.14.3`

### Describe the bug

Using a vulnerable version of dicer. https://github.com/strapi/strapi/issues/16193 says upgrading can't be done because of breaking changes in depending packages. Related: https://github.com/strapi/strapi/pull/14439

```
# npm audit report

dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
No fix available
node_modules/dicer
  busboy  <=0.3.1
  Depends on vulnerable versions of dicer
  node_modules/graphql-upload/node_modules/busboy
    graphql-upload  <=14.0.0
    Depends on vulnerable versions of busboy
    node_modules/graphql-upload
      @strapi/plugin-graphql  *
      Depends on vulnerable versions of graphql-upload
      node_modules/@strapi/plugin-graphql

4 high severity vulnerabilities
```

### Steps to reproduce the behavior

1. `npm install @strapi/plugin-graphql@latest`
2. `npm audit fix`

### Expected behavior

No vulnerabilities

### Additional context

Adding this in `package.json` resolves the issue, unsure if the package still works.

```json
{
  "[..]": "",
  "overrides": {
    "@strapi/plugin-graphql": {
      "busboy": "1.0.0"
    }
  },
  "[..]": ""
}
```

busboy's first release is `1.0.0` after `0.3.1`, see https://www.npmjs.com/package/busboy?activeTab=versions. They stopped using `dicer` after release `0.3.1` in dec 1 2022 mentioned in https://github.com/mscdex/busboy/issues/328

Also mail sent to [security@strapi.io](mailto:security@strapi.io)

**Comment by kasonde** [comment]
Duplicate of #16193
