### ISSUE TITLE
Docker with Ngnix  Config

### ISSUE THREAD

**Issue by Flowbook** [strapi/strapi#1839]
**Informations**
- **Node.js version**: 10.7
- **npm version**: 6.1
- **Strapi version**:13.0.1
- **Database**:Mongo
- **Operating system**:Ubuntu

**What is the current behavior?**

I'm trying to make my strapi project working with the latest strapi version (the 13.1) with a docker & proxy Nginx and I'm facing the following problem : when I'm logging onto the dashboard and going on the "role and permissions" page, when I click on any item shown in the page, I can't see anything but a loading wheel...and nothing in the strapi logs (I've modified the "request.json" file in order to see, if possible, error/warn logs or else) and no errors in Nginx logs...even if I add some options related to "CORS" settings.

**Steps to reproduce the problem**

Test which I made:
1-Strapi Version 
2-Docker Local 
3-Remarque k.o (Docker Local)
4-NGNIX Rproxy  (config Docker locale == Docker Prod ) 
5-Docker Prod
6-Remarque k.o (Docker Prod)

Table references :
-1- | -2- | -3- | -4- | -5- | -6-
12.1.3 | ok | RAS | ok | ok | RAS
13.0.1 | ok | RAS | ok | ko | Rubric Roles & Permissions Time out
13.1 | ok | RAS | ok | ko | Rubric Roles & Permissions Time out
14 | ok | RAS | ok | ko | Rubric Roles & Permissions Time out

**What is the expected behavior?**
Role and permissions  should work and it should not have a time out?

Nginx config:
upstream strapi {
    server strapi:1337  max_fails=1 fail_timeout=5s;
}

server {
    listen       80;
    server_name cms.one.test.com;
#       server_name strapi;
    access_log "/var/log/nginx/strapi.access.log";
    error_log "/var/log/nginx/strapi.error.log";
    location /{
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Max-Age' 1728000;
#               add_header 'Content-Type' 'text/plain; charset=utf-8';
#               add_header 'Content-Length' 0;
            proxy_pass http://strapi;
            proxy_redirect  off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $http_host;
            proxy_cache_bypass $http_upgrade;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
              proxy_connect_timeout 90;
              proxy_send_timeout 90;
              proxy_read_timeout 12000;
              proxy_buffer_size 32k;
              proxy_buffers 4 32k;
              proxy_busy_buffers_size 64k;
              proxy_temp_file_write_size 64k;
              client_max_body_size  32M;
              client_body_buffer_size       512k;
    }
}

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@Flowbook ahhh my eyes! Codeblocks please :stuck_out_tongue_winking_eye:
