### ISSUE TITLE
Start using yarn?

### ISSUE THREAD

**Issue by gusgard** [strapi/strapi#184]
Hi, it would be useful to have a yarn.lock file to minimize the bugs with different version of packages.

**Strapi version**: 3

**Comment by Aurelsicoko** [comment]
@gusgard Great suggestion! There was already a task in the ROADMAP dedicated to this (see https://github.com/strapi/strapi/projects/1#card-454004), however, I added it into the current ROADMAP to check again if we are doing the things right.

**Comment by simoami** [comment]
I'd suggest to be careful with yarn. It still has issues where some nested dependencies end up being ignored. I has 686 open issues at the moment.

**Comment by Aurelsicoko** [comment]
@simoami Thanks for reminding us this. But the project is moving fast, and we are just talking here about having a yarn.lock file. It still lets the ability to the Strapi' users to use `npm` if they want to.
