### ISSUE TITLE
Strapi creates a new entry record without images

### ISSUE THREAD

**Issue by suchetnocnoc** [strapi/strapi#18403]
### Required System information

- Node.js version: 18.18.1
- NPM version: 9.8.1
- Strapi version: 4.14.3
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When creating a new entry record from a duplicate item button, Strapi will create a new record without images.

### Steps to reproduce the behavior

1. Create a new collection type and add a media field.
2. Go to 'Content Manager' and create a new entry with an image.
3. Click on the 'Duplicate item' button
4. Strapi creates a new entry record without images.

### Expected behavior

Strapi should create a new entry record with images. 

### Screenshots

https://github.com/strapi/strapi/assets/106718660/d3769193-5e7b-47ec-8204-8b7b085b403c

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Sohailsaifi** [comment]
I want to work on it. Can you assign it to me?

**Comment by Boegie19** [comment]
pr https://github.com/strapi/strapi/pull/18409 seems to fix the issue no more PRs for this issue are needed.

**Comment by rishabh1S** [comment]
Anyone up? Who can review my PR #18409
