### ISSUE TITLE
Is npm supported?

### ISSUE THREAD

**Issue by jdgcj** [strapi/strapi#18410]
Is `npm` still supported?

I'm doing this:

```bash
git clone https://github.com/strapi/strapi.git
cd strapi
nvm install 18
nvm use 18
npm install
```

And I get this:
```bash
% npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

Am I doing something wrong or is this a bug in `main`?

**Comment by Boegie19** [comment]
@jdgcj I am not sure if npm is suported in the strapi mono repo but `yarn` is

**Comment by jdgcj** [comment]
I think I was confused and thought I needed to check out the strapi github repo in order to create a new project. That doesn't appear to be the case. nvm. Closing.
