### ISSUE TITLE
Database authentication fail after upgrade to alpha.14

### ISSUE THREAD

**Issue by goras** [strapi/strapi#1842]
**Informations**
- **Node.js version**: 10.0.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: mongo 3.6.6
- **Operating system**: macOS High Sierra 10.13.6 

**What is the current behavior?**
The database authentication fails when generating a new Strapi project.

**Steps to reproduce the problem**
1. Install alpha.14 ``npm install strapi@3.0.0-alpha.14 -g``
2. Generate a new project ``strapi new myNewProject`` with the following props:
- **Choose your main database**: MongoDB (recommended)
- **Database name**: mydb
- **Host**: ds237192.mlab.com
- **+srv connection**: false
- **Port (It will be ignored if you enable +srv)**: 37192
- **Username**: admin
- **Password**: test123
- **Authentication database**:
- **Enable SSL connection**: false
3. The authentication fails and gives the error:

```
Database connection has failed! Make sure your database is running.
? Choose your main database: (Use arrow keys)
❯ MongoDB (recommended)
  Postgres
  MySQL (node:2142) UnhandledPromiseRejectionWarning: MongoError: Authentication failed.
    at /private/var/folders/4p/509nqpvn2nv158d8w19b7r2w0000gn/T/strapi13e0b8c4b33f/node_modules/mongodb-core/lib/connection/pool.js:581:63
    at authenticateStragglers (/private/var/folders/4p/509nqpvn2nv158d8w19b7r2w0000gn/T/strapi13e0b8c4b33f/node_modules/mongodb-core/lib/connection/pool.js:504:16)
    at Connection.messageHandler (/private/var/folders/4p/509nqpvn2nv158d8w19b7r2w0000gn/T/strapi13e0b8c4b33f/node_modules/mongodb-core/lib/connection/pool.js:540:5)
    at emitMessageHandler (/private/var/folders/4p/509nqpvn2nv158d8w19b7r2w0000gn/T/strapi13e0b8c4b33f/node_modules/mongodb-core/lib/connection/connection.js:310:10)
    at Socket.<anonymous> (/private/var/folders/4p/509nqpvn2nv158d8w19b7r2w0000gn/T/strapi13e0b8c4b33f/node_modules/mongodb-core/lib/connection/connection.js:453:17)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
(node:2142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What is the expected behavior?**
The database connection should have been established and the new project generated.

**PS: Same mLab database and credentials works fine on alpha.13.1.

**Comment by goras** [comment]
I set up another db on mlab and updated the ticket with real credentials for testing purposes.

**Comment by lauriejim** [comment]
@sundaycrafts can you check that please.

**Comment by sundaycrafts** [comment]
Hi @goras . I tried it in same environment.

I think your issue does not depend on Strapi, it is mlab's trait.
You have to set database name to **Authentication database:**.

For example, auth DB is `sandbox` in this picture👍

<img width="1184" alt="mlab__cloud-hosted_mongodb-2" src="https://user-images.githubusercontent.com/4732821/44869590-ee860f80-acc8-11e8-8fea-8534fe19bbe4.png">

**Comment by goras** [comment]
Aha, I had no idea about this. I've changed the value of "Authentication database" to same as the database name, "mydb" and it works! I guess something's changed in alpha.14 then, since I've used a blank field for Authentication database in previous Strapi versions. Thanks for your help!

**Comment by coding-saints** [comment]
Since this issue wasn't closed, I'm having the same issue, but with WSL. Same environment, and I DID get caught up with the `auuth db` . I fouund this thread and tried making the correction but "unhandledPromiseRejectionWarning" stating that authentification failed. I can open up a new issue if it would be better. Thanks.
