### ISSUE TITLE
Alpha Rich text (blocks) not returning data through graphQL

### ISSUE THREAD

**Issue by matthieunelmes** [strapi/strapi#18430]
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.19.3
- Strapi version: 4.14.4
- Database: sqlite
- Operating system: MacOs Ventura 13.0
- Is your project Javascript or Typescript: Javascript

### Describe the bug

On testing the Alpha Rich text (blocks) editor, the data is not available through the graphQL endpoint

### Steps to reproduce the behavior

1. Create or edit existing content type
2. Add Field and select Rich text (blocks) and Save
3. Go to content page and populate the field, Save/Publish
4. Go to localhost:1337/graphql and populate query (at this point the Rich text (blocks) parameter does not appear in the intellisense nor in the graphQL playground docs tab)
5. Go to localhost:1337/api/<content-page> and the Rich text (blocks) data is present

### Expected behavior

Expected Rich text (Blocks) json to be in the response and available in the graphql playground intellisense and docs as per other content-type fields

**Comment by patriciorivera** [comment]
same problem here I confirm

**Comment by psparthsahni** [comment]
Same problem for me.

**Comment by remidej** [comment]
Thanks for the reports, the fix will be part of next week's release

**Comment by Bladeofgodol** [comment]
it still isn't fixed sadly. moving back to markdown temporarily.

**Comment by matthieunelmes** [comment]
> it still isn't fixed sadly. moving back to markdown temporarily.

What version are you using?
