### ISSUE TITLE
'TypeError:strapi.plugins.email.services.send is not a function' console error

### ISSUE THREAD

**Issue by NikhilNanjappa** [strapi/strapi#1843]
**Informations**
- **Node.js version**: `10.4.0` (replicable in `8.9.4` and `9.9.0`)
- **npm version**: `6.2.0` (also used `5.6.0`)
- **Strapi version**: `3.0.0-alpha.14`
- **Database**: MongoDB
- **Operating system**: macOS Sierra

**What is the current behavior?**

My intention is to send emails using the default strapi email provider. Using the below code(in `api/email/controllers/Email.js`) gives a `TypeError:strapi.plugins.email.services.send is not a function` error in the console when I hit the `http://localhost:1337/email` API.

```
module.exports = {
  send: async (ctx) => {
    const {email} = ctx.request.body;
    await strapi.plugins['email'].services.email.send({
            to: email,
            from: 'your@email.address',
            replyTo: 'your@email.address',
            subject: 'It is my message',
            text: 'Coucou',
            html: 'Coucou'
          });

    ctx.send('ok');
  }
};
```

Screenshot of the complete stack trace is as shown below :

<img width="750" alt="screen shot 2018-08-30 at 15 09 29" src="https://user-images.githubusercontent.com/5576981/44857017-c665c480-ac66-11e8-84b6-1728140fdc56.png">

Also, the response given by the `/email` API is 

```
{
    "message": "An internal server error occurred",
    "statusCode": 500,
    "error": "Internal Server Error"
}
```

**Steps to reproduce the problem**

1. Create a new API by running `strapi generate:api email`
2. Delete the model folder and clean routes, services and controller content
3. Add POST `/email` route

```
{
      "method": "POST",
      "path": "/email",
      "handler": "Email.send",
      "config": {
        "policies": []
      }
}
```
4. Then in Email controller(`api/email/controllers/Email.js`), create an action named `send` (as shown in the above section)
5. Next, use an app like Postman to make a POST request to `http://localhost:1337/email` (no request body). 

**What is the expected behavior?**

The API should respond with an `ok` message and an email should be sent to the destination address.

**Suggested solutions**

I have added a `send` action within the Email controller at `api/email/controllers/Email.js` path. Should the `send` action at `plugins/email/controllers/Email.js` be amended instead ? It seems for some reason its not able to find the `send` function under `plugins/email/services` even though its there.

**Comment by NikhilNanjappa** [comment]
I moved the send action code from `api/email/controllers/Email.js` to `plugins/email/controllers/Email.js` and gave all permissions to the 'Public' role. This fixed the 'plugins.email.services.send is not a function' issue but **now I'm getting** `Error: Cannot wrap non-Error object` error in my console. Complete stack trace is below :

<img width="1016" alt="screen shot 2018-08-30 at 18 38 42" src="https://user-images.githubusercontent.com/5576981/44869059-831a4e80-ac84-11e8-9b8d-63c585bc6986.png">

Any help please ?

**Comment by lauriejim** [comment]
Try `strapi.plugins.email.services.email.send`.

**Comment by NikhilNanjappa** [comment]
@lauriejim - This issue is fixed.

I have mentioned the steps for the fix in the above comment. Could you also clear the doubt asked ?
