### ISSUE TITLE
Poor word wrapping in language settings

### ISSUE THREAD

**Issue by jbergstroem** [strapi/strapi#1844]
**Informations**
- **Node.js version**: node 10.9
- **npm version**:  6.2
- **Strapi version**: 3.0.0-alpha14
- **Database**: postgresql
- **Operating system**: macos

Language wraps very unfortunately if the width of the browser is not "wide enough":
<img width="638" alt="screen shot 2018-08-30 at 11 56 39 am" src="https://user-images.githubusercontent.com/176984/44860172-09666e80-ac4c-11e8-9717-06851b8ebdae.png">

**Comment by derrickmehaffy** [comment]
@jbergstroem this isn't just with the language it is with the entire site :stuck_out_tongue: 

I don't think it is a priority for them at the moment but I'm sure @soupette is working on something.

**Comment by jbergstroem** [comment]
> @derrickmehaffy said: @jbergstroem this isn't just with the language it is with the entire site 😛

Thanks for letting me know. Is there perhaps another issue that is more relevant?

**Comment by soupette** [comment]
@jbergstroem it's really hard to make admin responsive with our current style configuration.
If you feel like contributing for improving this part of strapi we would really appreciate since it's not our priority for the moment.

**Comment by jbergstroem** [comment]
> @soupette said: If you feel like contributing for improving this part<snip>

My styling skills are likely as limited as your time constraints 😢  Lets at least keep this open, perhaps you have a "low hanging fruit" tag that eager frontend contributors can find?

Lets keep
