### ISSUE TITLE
[Media Library] Thumbnail auto append datetime for img src

### ISSUE THREAD

**Issue by lianghua1987** [strapi/strapi#18443]
### Required System information

- Node.js version: 19.1.0
- NPM version: 8.19.3
- Strapi version: 4.14.4
- Database: postgres
- Operating system: Windows 10
- Is your project Javascript or Typescript: javascript

### Describe the bug

A timestamp auto appends to img src after add a new asset (images) which breaks the signedUrl. Similar: #14070

### Steps to reproduce the behavior

1. Go to 'Media Library'
2. Click on 'Add new asset and upload an image'
3. Go to browser inspect
4. See the datetime append at the end of src attribute

### Screenshots

![image](https://github.com/strapi/strapi/assets/11912143/3521166b-a528-4e31-b2b8-816f5b1f32af)

### Code snippets

```javascript
// strapi/packages/core/upload/admin/src/components/AssetCard/ImageAssetCard.js
export const ImageAssetCard = ({ height, width, thumbnail, size, alt, ...props }) => {
  // Prevents the browser from caching the URL for all sizes and allow react-query to make a smooth update
  // instead of a full refresh
  const urlWithCacheBusting = appendSearchParamsToUrl({
    url: thumbnail,
    params: { updatedAt: props.updatedAt },
  });

  return (
    <AssetCardBase {...props} subtitle={height && width && ` - ${width}✕${height}`} variant="Image">
      <CardAsset src={urlWithCacheBusting} size={size} alt={alt} />
    </AssetCardBase>
  );
};```

**Comment by lianghua1987** [comment]
Actually I was able to find a workaround(#17938) by adding this middleware, but would be nice to see if there's a fix.

```javascript
module.exports = () => {
  return async (ctx, next) => {
    await next();
    if (ctx.request.url.includes("upload/files")) {
      if (ctx.response.body && typeof ctx.response.body === "object") {
        for (let file of ctx.response.body.results) {
          if (file.url.includes(".s3.")) delete file.updatedAt
        }
      }
    }
  };
};
```

**Comment by Shub3am** [comment]
Can i Work On this?

**Comment by Shub3am** [comment]
Have Fixed the issue and Verified the Code

**Comment by thanos982** [comment]
@lianghua1987 I've been unable to reproduce. I am using the [S3 AWS provider](https://market.strapi.io/providers/@strapi-provider-upload-aws-s3) with a private bucket and the signed URL images show up ok, even with the updatedAt param appended. My urls look different to your screenshot though, there is a `&updatedAt=2023-10-19xxxx` appended at the end which doesn't interfere with the signature param. But maybe I'm missing something. What plugin are you using?

**Comment by lianghua1987** [comment]
> @lianghua1987 I've been unable to reproduce. I am using the [S3 AWS provider](https://market.strapi.io/providers/@strapi-provider-upload-aws-s3) with a private bucket and the signed URL images show up ok, even with the updatedAt param appended. My urls look different to your screenshot though, there is a `&updatedAt=2023-10-19xxxx` appended at the end which doesn't interfere with the signature param. But maybe I'm missing something. What plugin are you using?

Yes, @thanos982, it's weird that my imgSrc dose not contains 'updateAt=' for some reason, but it appears to work if a specifically delete the keyword from  object.

Here is my plugins.js "@strapi/provider-upload-aws-s3": "^4.14.4",

```javascript
module.exports = ({env}) => {
  return {
    upload: {
      enabled: true,
      config: {
        provider: 'aws-s3',
        providerOptions: {
          rootPath: "rootPath",
          s3Options: {
            signatureVersion: 'v4',
            sslEnabled: true,
            accessKeyId: '*********',
            secretAccessKey: '*********',
            sessionToken:  '*********',
            region:  '*********',
            params: {
              ACL: "private",
              Bucket:  '*********',
              SSEKMSKeyId:  '*********',
              ServerSideEncryption: 'aws:kms',
              signedUrlExpires:  '*********',
              Metadata: {
                'x-amz-server-side-encryption': 'aws:kms',
                'x-amz-server-side-encryption-aws-kms-key-id':  '*********',
                'x-amz-acl': 'private',
              },
            },
          },
        },
        actionOptions: {
          upload: {},
          uploadStream: {},
          delete: {},
        },
      },
    },
  }
};

```

**Comment by Boegie19** [comment]
> Also, it seems signedUrl doesn't return from api in singleType mode with one-to-may relation to collection types, where the collection type has an image attribute, only returns the unsignedUrl. Should I open another ticket or keep this openning?

if it has noting todo with the data being appended to the end please open an other issue for it.

**Comment by thanos982** [comment]
Thanks @lianghua1987, I was able to reproduce now. For context, I see that it is related to issue #17655 and occurs in particular when using [AWS Signature Version 4 authentication with query params](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html).

From what I understand one solution for this would be to include the updatedAt param when generating the presigned URL in the [S3 provider](https://market.strapi.io/providers/@strapi-provider-upload-aws-s3). I don't think cache busting is practically required here though, because the S3 presigned URLs already contains query params with unique/temporary values, including a current timestamp param (X-Amz-Date).

Another possible solution: look for a timestamp in the existing URL query params (especially one of ISO 8601 format) and cache bust only if it doesn't exist. This doesn't resolve the SignatureDoesNotMatch issue in general, but at least solves the current issue in a more pragmatic way. I've already started working on this but @Boegie19, could you or any other maintainers please let me know if it sounds okay, or if you see any issues with this approach?

**Comment by Boegie19** [comment]
@thanos982 I am not a maintainer am part of the comunity and help strapi with triage of issues. I think that @Marc-Roig can best answer this question since he made the AWS sign system on the strapi end.

**Comment by lianghua1987** [comment]
@thanos982 This also happens when cropping the image. This time a property named 'timestamp' is append to the imgSrc. 
e.g. 4e3bdc0&X-Amz-SignedHeaders=host&timestamp=1698134425828

**Comment by Fryuni** [comment]
This issue also applies to any other provider that signs the entire URL and not just some parameters. Minio (using the S3 provider) and Google Cloud Storage (using the plugin from `strapi-community`) also have the same problem.

**Comment by Fryuni** [comment]
Wouldn't it be simpler if there was a parameter indicating that the asset URL is private and as such should not employ the cache busting?

The URLs are only signed if the `isPrivate` method returns true for the asset so that value could be passed down all the way to the `ImageAssetCard` component.

**Comment by thanos982** [comment]
@Fryuni thanks for the help. Pull request updated.
