### ISSUE TITLE
Duplicating/Cloning a record is not working

### ISSUE THREAD

**Issue by bledar** [strapi/strapi#18454]
### Required System information
- Node.js version: 16
- NPM version: 8.19.2
- Strapi version: 4.12.1
- Database: MySQL2
- Operating system: Node-16-Alpine
- Is your project Javascript or Typescript: Yes
- 
### Describe the bug
 After updating Strapi from version 4.7.x we are not able to duplicate records anymore.
This is happening on development and production.
Clicking on duplicate button nothing will happen.
Inspecting network request will show a request with 400 error:
```JOSN
 {
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "Entity could not be cloned as it has unique and/or relational fields. Please edit those fields manually and save to complete the cloning.",
        "details": {}
    }
}
```

### Steps to reproduce the behavior

1. Go to content manager
2. Click on one of the collection types
3. Click duplicate item button 
4. Nothing will happen

### Additional context

I have multiple content types some of them have slugs' field that should be unique, and some other collections don't have unique slugs.
This error is showing also on the collection types that don't have a unique slug field.
Previously records with unique fields like slugs were duplicated just fine. 
The validation was failing when trying to save the duplicated record until you change the slug to be unique, but this was okay.
I have noticed that only some very basic collection types were able to be duplicated. Those collection types don't have a unique field or relation with other collections.
It seems that the problem is with unique fields or relations. Even if this is an intentional behavior (previous before was working) at least an error message needs to be displayed for non-technical users.

**Comment by joshuaellis** [comment]
> Previously records with unique fields like slugs were duplicated just fine.
The validation was failing when trying to save the duplicated record until you change the slug to be unique, but this was okay.

So no they weren't duplicated at all, you had to save them to duplicate them and you couldn't because they had those unique fields. So this is intended behaviour

**Comment by Zwooosh** [comment]
How is this intended behaviour? I'm running into the same issue. It used to show 'semi-cloned' content type in the editor with a warning you'd need to update the unique keys. But now it doesn't show anything. (Except the error in the network tab).

**Comment by joshuaellis** [comment]
> How is this intended behaviour? I'm running into the same issue. It used to show the 'semi-cloned' content type in the editor with a warning you'd need to update the unique keys. But now it doesn't show anything. (Except the error in the network tab).

If you try to clone an entity and it cannot do it automatically because you have unique fields (as an example) then it should redirect to you to a clone route with the data from the entity you were trying to clone so you can press save when you have amended the necessary fields – if this does not work then please provide a reproduction of the issue to illustrate this.

**Comment by Zwooosh** [comment]
The steps and description @bledar provided are the exact steps needed to reproduce the issue. Perhaps his additional context was a bit confusing, but the actual bug is that is no longer redirects to the clone route if a content type has unique fields. 

The post to the clone-route (`http://localhost:1337/content-manager/collection-types/api::area-group.area-group/auto-clone/4?plugins[i18n][locale]=en`)  fails with a 400: 
```json
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "Entity could not be cloned as it has unique and/or relational fields. Please edit those fields manually and save to complete the cloning.",
        "details": {}
    }
}
```

**Comment by joshuaellis** [comment]
Thanks for this information, the issue still looks like a duplicate of #17399 though – so i'd keep an eye on that issue instead :)

**Comment by diacu** [comment]
I still get the error on 4.20.3 when using unique fields (e.g. slug).

**Comment by AlvaroDeen** [comment]
I still get the error  when using unique fields (e.g. slug).
