### ISSUE TITLE
[User Roles ADMIN]

### ISSUE THREAD

**Issue by alejandrojosue** [strapi/strapi#18465]
## Bug report
No permite agregar condiciones para el acceso de usuarios del panel de administración
### Required System information
Windows 10 Pro

- Node.js version: 18.15.0
- NPM version: 9.7.2
- Strapi version: 4.14.4
- Database: Mysql y Sqlite
- Operating system: win32-x64
- Is your project Javascript or Typescript: JS

### Describe the bug
Necesito crear usuarios que puedan modificar los usuarios de Strapi, los del panel de administración. Cuando selecciono la opción de poder ver y actualizar los usuarios y roles siempre y cuando los haya creado o tienen el mismo rol de quién los creó, sí pueda realizar dichas acciones (Ver y actualizar), pero al parecer, independientemente de que ponga o no la opción, siempre puedo visualizarlos. Estas condiciones únicamente funciona con los usuarios que se utilizan para una aplicación frontend.
Uso la verisón Community y en modo development.

### Steps to reproduce the behavior

1. Ir a Cofiguraciones
2. Seleccionar Roles en la sección de Panel Administración
3. Crear un rol
4. Ir a la pestaña de Configuraciones y seleccionar Usuarios y Roles
5. Seleccionar Crear, actualizar y leer
6. Poner condición de que pueda realizar dicha acción cuando tiene  el mismo rol que el creador. Aplicarlo para todas las acciones.

### Expected behavior
Que cuando le asigno ese rol a un usuario de Strapi y luego inicie sesión en strapi con ese usuario, me permita ver únicamente los usuarios creados por ese usuario o los usuarios creados por los usuarios que tienen el mismo rol. Lo mismo que aplique para usuarios.

### Screenshots

En las siguientes dos imágenes se aprecia la asignación de permisos al rol **Editor**.
![Captura de pantalla (1386)](https://github.com/strapi/strapi/assets/67884952/2ce77075-abad-48f0-a02d-06d4faffef64)
![Captura de pantalla (1387)](https://github.com/strapi/strapi/assets/67884952/36d846c8-c3fc-4818-a1f1-3d2bf1cad8a7)

En la siguiente imagen, se ven todos los roles que existen en el panel de administración y **no deberían verse**, solamente el Date ya que es el que este usuario creó. El usuario tiene rol de Editor.
![Captura de pantalla (1388)](https://github.com/strapi/strapi/assets/67884952/b16dbd8b-7904-4e4f-8eb7-4b8336905b20)

En la siguiente captura, tampoco debería verse los roles **Super Admin**, **Editor**,... únicamente debería verse el rol Date, ya que este usuario de tipo **Editor** es quién lo creó
![Captura de pantalla (1389)](https://github.com/strapi/strapi/assets/67884952/a82883e2-db9d-414a-b6e6-195a45f899e4)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Boegie19** [comment]
All issues need to be summited in English.
