### ISSUE TITLE
Update upload plugin sharp dependency to version 0.32.6

### ISSUE THREAD

**Issue by vojthor** [strapi/strapi#18479]
Hey,

not sure if this is correct place but... would it be possible to update `sharp` library to in `packages/core/upload/package.json` to version **0.32.6**?

There is critical vulnerability reported (https://security.snyk.io/vuln/SNYK-JS-SHARP-5922108) and our CI keeps getting it flagged.

Cheers!

**Comment by joshuaellis** [comment]
PRs are welcome - ask for a review from @Marc-Roig if you create one 😊

**Comment by Boegie19** [comment]
closed since 18480 got merged
