### ISSUE TITLE
Field types aren't properly escaped in search queries

### ISSUE THREAD

**Issue by jbergstroem** [strapi/strapi#1849]
**Informations**
- **Node.js version**: 10.9
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha14
- **Database**: postgres 10
- **Operating system**: macos 10.14

1. Create a data model in style with:
```sql
CREATE TABLE "foo" (
id SERIAL NOT NULL PRIMARY KEY,
"a date" timestamp with time zone,
"a title" varchar(255),
"a enumeration" varchar(255),
"created_at" timestamp with time zone,
"updated_at" timestamp with time zone
	                        )
```

2. Add content to data model

3. Attempt to search via the top bar:
<img width="939" alt="screen shot 2018-08-30 at 3 09 51 pm" src="https://user-images.githubusercontent.com/176984/44870468-c665c480-ac66-11e8-8d18-899a84b1ff29.png">

Generated sql looks like this:
```sql
2018-08-30 18:09:48.843 UTC [165] ERROR:  syntax error at or near "date" at character 43
2018-08-30 18:09:48.843 UTC [165] STATEMENT:  select "foo".* from "foo" where LOWER(a date) LIKE '%baz%' or LOWER(a enumeration) LIKE '%baz%' or to_tsvector(a title) @@ to_tsquery($1) order by "id" ASC limit $2
```

The column names need to be properly escaped.

**Comment by jbergstroem** [comment]
Looks like this is the problem: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/config/queries/bookshelf.js#L72

**Comment by lauriejim** [comment]
Hello @jbergstroem , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
Update: You can't use space in you column name. Please use lowerCase names
