### ISSUE TITLE
TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by io777** [strapi/strapi#185]
**Node.js version**: 7.4.0
**npm version**: 4.0.5
**Strapi version**: 1.5.4
**Operating system**: macOS Sierra v 10.12.3

When I typed in the command line **strapi start** i was given an error.

TypeError: Promise.defer is not a function at Object.exports.create (/newApp/api/user/config/fixtures/route.js:18:28)

In file (/newApp/api/user/config/fixtures/route.js:18:28) i deleted **const deferred = Promise.defer();**
and paste the code below and it worked!

```javascript
function defer() {
    var deferred = {};
    var promise = new Promise(function(resolve, reject) {
        deferred.resolve = resolve;
        deferred.reject  = reject;
    });
    deferred.promise = promise;
    return deferred;
}
const deferred = defer();
```

**Comment by io777** [comment]
Sorry, not working, changes in Strapi Studio are not applied in local server.

**Comment by Aurelsicoko** [comment]
Hi @io777, this a very common issue on Strapi v1. To fix it you need to downgrade to Node 4 LTS and it will work like a charm. FYI, the next version (v3) of Strapi will be compatible with Node 7.

**Comment by io777** [comment]
Thanks, I'll wait Strapi v3.

**Comment by pierreburgy** [comment]
@io777 Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
