### ISSUE TITLE
User permissions createRole returns undefined

### ISSUE THREAD

**Issue by gregg-cbs** [strapi/strapi#18501]
### Required System information
    Node.js version: 16
    NPM version: 8.9
    Strapi version: 4.5.6
    Operating system: Ubuntu
    Typescript

### Describe the bug

When creating a role programmatically, like in Jest, createRole returns undefined and it should return the role. The role is created. I think this will also fail silently if there is an error.

### Steps to reproduce the behavior
In code run:
```javascript
// create role
const role = await strapi.plugins['users-permissions'].services.role.createRole({
  name: "Role",
  description: "Open testing role",
})
// ^ notice role is undefined

// get all roles
const roles = await strapi.plugins['users-permissions'].services.role.find();
// ^ notice role has been created
```

### Expected behavior
Role to be returned

**Comment by Boegie19** [comment]
@gregg-cbs You need to update your strapi version the version you have is to old + has a lot of security issues.

also this is a none issue since it works as expected on the latest version
