### ISSUE TITLE
Media fields in components don't show in queries with populate=*

### ISSUE THREAD

**Issue by colin-precisionos** [strapi/strapi#18515]
### Required System information

- Node.js version:v18.15.0
- NPM version: npm/8.19.2
- Strapi version: 4.14.3
- Database: MySql
- Operating system: win32-x64 (and linux)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When querying collections with component embedded, any media fields of the component will not show with populate=*

### Steps to reproduce the behavior

1. Create a component with a single media field
2. Add the component to a collection
3. Set the media field inside an entry of the collection
4. Query the collection with populate=*, the media field doesn't show up

### Expected behaviour

The media field of a component should output in a query with populate=*.

**Comment by derrickmehaffy** [comment]
This is normal behavior as those media fields are a relationship themselves and are nested below one level.
