### ISSUE TITLE
'Advanced' tab on date field settings resulting in white page

### ISSUE THREAD

**Issue by antonieIPR** [strapi/strapi#18522]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.6.7
- Strapi version: 4.14.5
- Database: SQLite - better-sqlite3 v9.0.0
- Operating system: Debian 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug

In the **content type builder**, when navigating to the '**advanced**' tab on a **date** (datetime) field, the whole UI disappears. 

### Steps to reproduce the behavior

1. Go to 'Content type builder'
2. Add a date field to any collection, if not already available
3. Open the settings dialogue screen of any date field
4. Click on 'advanced'
5. See a white screen

### Expected behavior

I expect to see the **advanced** tab and settings, as is the case with other field types.

### Screenshots

White screen, not very useful :)

### Code snippets

--

### Additional context

--

**Comment by theavitw** [comment]
Add Visuals

**Comment by antonieIPR** [comment]
![image](https://github.com/strapi/strapi/assets/64540868/c8662a45-0ca5-4afe-8bf7-950fe73dfff5)
![image](https://github.com/strapi/strapi/assets/64540868/b963b80e-2c17-4fa6-97c9-bf9f25dfa5f0)
![image](https://github.com/strapi/strapi/assets/64540868/78443764-e39e-4fd5-93b0-4c62a07c98fb)
![image](https://github.com/strapi/strapi/assets/64540868/70657888-3178-4b52-adb4-d29e644c2ab4)

I am using MS Edge 118.0.2088.46

**Comment by sumaiya2908** [comment]
I am getting this error as well. Trying to find a fix. I will raise a PR.
![image](https://github.com/strapi/strapi/assets/58825865/de694d6a-14e8-45ad-be5c-ac3b65530138)

**Comment by joshuaellis** [comment]
Closed by #18506
