### ISSUE TITLE
408 on large request upload

### ISSUE THREAD

**Issue by Simerca** [strapi/strapi#18543]
### Describe the bug

When uploading a file that takes longer than 5 minutes to process in production with Node.js version 18, a client-side error 408 occurs. This is due to the default timeouts of Node.js version 18.

### Steps to reproduce the behavior

1. Use Node.js version 18 in production.
2. Attempt to upload a file that takes more than 5 minutes to process.
3. Observe the client-side error 408.

### Expected behavior

I expect that timeouts can be configured or customized in Strapi, as the new default values in Node.js version 18 can result in error 408 for long operations such as file uploads.

https://fek.io/blog/what-is-new-in-node-js-18/

### Additional context

I couldn't find information in the Strapi documentation about the possibility of configuring these timeouts via configuration variables.

**I can fix it with downgrade to node 16**

**Comment by derrickmehaffy** [comment]
@innerdvations I thought you had a fix for this in DTS but I can't find the PR or if it was merged but I know we were planning on adding our own config option to configure the timeout.

**Comment by innerdvations** [comment]
Yeah, it's the default timeouts that were added in Node 18. This can be solved pretty easily by adding a config option. I'll see if I can do that this week.
