### ISSUE TITLE
Exception in querying data about folders in the Media Library component

### ISSUE THREAD

**Issue by zhenzhenChange** [strapi/strapi#18555]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.14.5
- Database: MySQL 8.1.0-ARM64
- Operating system: macOS 14 Sonoma
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When using the media library component, after closing the nested modal window, the outermost popup window data query is incorrect, after checking the interface call, it should be missing the `folder.path` pass.

https://github.com/strapi/strapi/assets/51586637/76038f2e-8046-4460-93e2-6cd4b38870d3

### Steps to reproduce the behavior

Actual code, opened by an external button click:

```tsx
import React from 'react'
import { prefixFileUrlWithBackendUrl, useLibrary } from '@strapi/helper-plugin'

interface Props {
  isOpen: boolean
  onChange: (ffs: FormattedFile[]) => void
  onToggle: () => void
}

export interface FormattedFile {
  alt: string
  url: string
  mime: string
}

const MediaLib = ({
  isOpen = false,
  onChange = () => {},
  onToggle = () => {},
}: Props) => {
  const { components } = useLibrary()
  const MediaLibraryDialog = components?.['media-library'] as any

  const handleSelectAssets = (files: any) => {
    const formattedFiles: FormattedFile[] = files.map((f: any) => ({
      alt: f.alternativeText || f.name,
      url: prefixFileUrlWithBackendUrl(f.url),
      mime: f.mime,
    }))

    onChange(formattedFiles)
  }

  if (!isOpen) {
    return null
  }

  return (
    <MediaLibraryDialog
      onClose={onToggle}
      onSelectAssets={handleSelectAssets}
    />
  )
}

export default MediaLib
```

### Expected behavior

Ability to correctly query the data in the current folder.

### Screenshots

![image](https://github.com/strapi/strapi/assets/51586637/3f825e9e-7690-42b6-8eaf-03a4c13aec01)

### Code snippets

None.

### Additional context

It's working in `@strapi/strapi - v4.10.8` version, haven't verified it in other versions.

**Comment by zhenzhenChange** [comment]
It seems to be similar to this problem with https://github.com/strapi/strapi/issues/18540 .

**Comment by nick-aj** [comment]
Hello @zhenzhenChange,

Thank you for reporting.
As you noticed, this issue was already reported in:
https://github.com/strapi/strapi/issues/18540
So we will close this issue and continue working on it in that one.

Thank you!
