### ISSUE TITLE
PolicyError are replaced by ForbiddenError

### ISSUE THREAD

**Issue by alexzrp** [strapi/strapi#18566]
### Required System information

- Node.js version: v16
- NPM version:
- Strapi version: v4.14.3
- Database: PostgreSQL
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript
 
### Describe the bug

It seems that when throw a policyError, the response are always a ForbiddenError without PolicyError custom message.

### Steps to reproduce the behavior
Create and use any policy.
Throw a new PolicyExceptionError
Call the endpoint that uses that policy.
You'll receive a Forbidden Exception

This example from documentation

https://docs.strapi.io/dev-docs/backend-customization/examples/policies#sending-custom-errors-through-policies

### Expected behavior
I expect receive PolicyError,

[@strapi+strapi+4.14.3.patch](https://github.com/strapi/strapi/files/13166861/%40strapi%2Bstrapi%2B4.14.3.patch)

**Comment by nick-aj** [comment]
Hello @alexzrp,

Thank you so much for reporting this issue to us, we can confirm that we are able to reproduce it.
_Here are some of my details:_
I tried the following scenarios:

- Throw a `PolicyError` within a custom policy
- Return `false` within a custom policy (Which should throw a generic `PolicyError`, not a generic `403`)
- Throw a `PolicyError` within a custom api middleware

All 3 cases throw a generic `403` forbidden instead of the expected `PolicyError`.

**Comment by derrickmehaffy** [comment]
Confirmed internally with several team members on v4.15.4

**Comment by EmJee1** [comment]
I found this issue because I encountered this in a project. Is there any ETA for a fix, or is there any available workaround?

**Comment by derrickmehaffy** [comment]
> I found this issue because I encountered this in a project. Is there an ETA for a fix, or is there any available workaround?

In your middleware config file move the `strapi::logger` to the top of the array

**Comment by EmJee1** [comment]
> > I found this issue because I encountered this in a project. Is there an ETA for a fix, or is there any available workaround?
> 
> In your middleware config file move the `strapi::logger` to the top of the array

First off, thanks @derrickmehaffy for the quick reply. I changed the middleware array order, it now looks like the following, but it still returns the generic error.

```ts
export default [
  "strapi::logger",
  "strapi::errors",
  "strapi::security",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

**Comment by derrickmehaffy** [comment]
Can you share the policy code?

**Comment by EmJee1** [comment]
In this sample, it is logging `Sending token expired error`, but the response I get is:

```json
{
  "data": null,
  "error": {
    "status": 403,
    "name": "ForbiddenError",
    "message": "Forbidden",
    "details": {}
  }
}
```

```ts
export default async (policyContext, config, { strapi }) => {
  const activeDirectoryToken =
    policyContext.req.headers["x-activedirectory-token"];
  if (!activeDirectoryToken) {
    return false;
  }

  try {
    const decoded = await verifyAzureAdJwt(activeDirectoryToken);
    policyContext.state["azure-ad-email"] = decoded.email;
    policyContext.state["azure-ad-id"] = decoded.id;
  } catch (err) {
    if (err.name === "TokenExpiredError") {
      strapi.log.info("Sending token expired error");
      throw new PolicyError("Token expired", {
        policy: "is-authenticated",
        code: "E_TOKEN_EXPIRED",
      });
    }

    return false;
  }

  return true;
};
```

**Comment by innerdvations** [comment]
It appears that this been the behavior for a considerable amount of time, so to avoid introducing a security issue by displaying error messages that some users are expecting to be hidden from the content API:

- in Strapi v4 we've updated the documentation to reflect this
- in Strapi v5 we will change the behavior to allow for the messages to be viewable on the content API
