### ISSUE TITLE
Display fields component is not working in firefox

### ISSUE THREAD

**Issue by ArkhipovK** [strapi/strapi#1856]
**Informations**
- **Node.js version**: 8.11.1
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.14
- **Database**: postgress
- **Operating system**: windows 10

**What is the current behavior?**
Display fields component just closes (without filed hiding) after click on any element in firefox. In chrome it works as expected.
![alt text](https://screenshotscdn.firefoxusercontent.com/images/41483ee0-f94d-404a-ae28-4c98769a7143.png)

**Steps to reproduce the problem**

Try to hide any field in firefox from ListView.

**What is the expected behavior?**

Element should not be closed after click on checkboxes.

**Comment by lauriejim** [comment]
@ArkhipovK You can confirm it works on Google Chrome ?

**Comment by ArkhipovK** [comment]
@lauriejim sure, in chrome it works.

**Comment by soupette** [comment]
Is this still happening? Can we close the issue or should I take a closer look?

**Comment by ArkhipovK** [comment]
Unfortunately yes. This still happening on firefox (win 10 / strapi 14.2)
