### ISSUE TITLE
Strapi Color Picker Plugin Causes White Blank Screen on "Custom" Tab Selection

### ISSUE THREAD

**Issue by jarren15** [strapi/strapi#18575]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.2.1
- Strapi version: 4.14.4
- Database: PostgreSQL 16.0
- Operating system: Windows 11 64 bit
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After installing the Strapi Color Picker plugin, selecting the "Custom" tab in the field selector results in a white blank screen.

### Steps to reproduce the behavior

1. Install the Strapi Color Picker plugin.
2. Go to the field selector.
3. Click on the "Custom" tab.
4. See error (white blank screen).

### Expected behavior

The "Custom" tab should display color picker options instead of a white blank screen.

### Screenshots

![image](https://github.com/strapi/strapi/assets/81326232/3d843681-d71c-4611-8a32-714509482300)

**Comment by joshuaellis** [comment]
Does this still happen if you watch the admin panel? Or what about is you prefix NODE_ENV=production to your build command for the admin panel?

**Comment by jarren15** [comment]
> Does this still happen if you watch the admin panel? Or what about is you prefix NODE_ENV=production to your build command for the admin panel?

Yes. I find it weird because I just followed the installation process of the plugin. I even updated my node and npm to the latest versions but still no success

**Comment by joshuaellis** [comment]
Have you tried updating your versions to the latest 4.15.0? Otherwise it'll be helpful to enable sourcemaps

**Comment by jarren15** [comment]
> Have you tried updating your versions to the latest 4.15.0? Otherwise it'll be helpful to enable sourcemaps

Can you tell me how to enable sourcemaps? Sorry for the noob question

**Comment by karan-kissht** [comment]
Hi,
Will this be fixed in the upcoming release? 
Whatever we try - rebuilding, deleting .cache, build & node module it doesn't seem to work

Current System information
Node.js version: 18.16.1
Strapi version: 4.15.0
Database: MySQL 8.0
Operating system: Docker (node:18.16-alpine)
Is your project Javascript or Typescript: Javascript

**Comment by joshuaellis** [comment]
Looking at the pr, the next release

**Comment by StevenJPx2** [comment]
this still hasn't been fixed... when is the next release

**Comment by chestongo** [comment]
Same error here...

**Comment by carljustineoyales** [comment]
Is this fixed? It still produce a white blank screen
