### ISSUE TITLE
[BUG] Failed to install with current node LTS version: 20.9.0

### ISSUE THREAD

**Issue by 101sam** [strapi/strapi#18578]
## Bug report

The current [LTS version is 20.9.0 ](https://nodejs.org/en)

This module is broken on all our servers using strapi 

### Required System information

- Node.js version: 20.9.0 LTS
- NPM version: 10.2.1
- Strapi version: 4.15.0
- Database: MySQL
- Operating system: Tested on: Linux & Mac
- Project Javascript

### Describe the bug

failed to install 

`yarn install `or `npm install`

### Expected behavior

Need to bump up the plugin packages

### Screenshots

NA

### Code snippets

NA

### Additional context

It would be nice to have some automatic process to test all strapi marketplace plugins before bumping versions with the latest LTS.  It does not make sense to have a marketplace plugin with limited versions that are less than the current strapi version. It's breaking servers.

I will add to the marketplace a field test on LTS: version(s) and date so at least before upgrade nodes we will know

**Comment by derrickmehaffy** [comment]
We have no control of community plugins and advise users to open an issue on the maintainer's GitHub.

I'm marking this as closed as there is nothing that we at Strapi can do here.

**Comment by 101sam** [comment]
In your marketplace [Color picker]( https://market.strapi.io/plugins/@strapi-plugin-color-picker) report bug is linked to this section and also the github code maintainer is say its strapi 

https://market.strapi.io/plugins/@strapi-plugin-color-picker
