### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by bl96** [strapi/strapi#18576]
### Required System information
- Node.js version: 20.9.0
- NPM version: 10.2.1
- Strapi version: 4.14.4 and up (4.15.0 included)
- Database: MariaDB 10.6
- Operating system: Windows 11 64 bit
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Hello,
I have a project which is now a mix of .js and .ts/.tsx files. From version 4.14.4, when I run the strapi develop command and the dist and .cache folder is created then the tsx files in the .cache folder are missing import React from "react" causing React is not defined error. For example, the UnauthenticatedLogo.tsx is created with the following content (missing import React):

```
import styled from 'styled-components';

import { useConfiguration } from '../hooks/useConfiguration';

const Img = styled.img`
  height: ${72 / 16}rem;
`;

const Logo = () => {
  const {
    logos: { auth },
  } = useConfiguration();

  return <Img src={auth?.custom ?? auth.default} aria-hidden alt="" />;
};

export { Logo };

```

For the 4.14.4 version and up everything works fine when I add the missing import into the .cache .tsx files manually.

This is generated with the version up to 4.14.3:

UnauthenticatedLogo/index.js

```
import React from 'react';

import styled from 'styled-components';

import { useConfigurations } from '../../hooks';

const Img = styled.img`
  height: ${72 / 16}rem;
`;

const Logo = () => {
  const {
    logos: { auth },
  } = useConfigurations();

  return <Img src={auth?.custom ?? auth.default} aria-hidden alt="" />;
};

export default Logo;

```

This is my tsconfig:

```
{
  "extends": "@strapi/typescript-utils/tsconfigs/server",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "allowJs": true,
    "jsx": "react"
  },
  "include": [
    "./",
    "./**/*.ts",
    "./**/*.tsx",
    "./**/*.js",
    "src/**/*.json"
  ],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.*"
  ]
}
```

Should there be something added into the tsconfig for version 4.14.4 and up?

Thank you in advance for the response

### Steps to reproduce the behavior

1. Have a project which is a mix of .ts/.tsx and .js files.
2. Start strapi with command strapi develop
3. Wait for the admin UI build to finish and create dist and .cache folders
4. Wait for the start of the Strapi server and load of the Admin login page
5. The error React is not defined is thrown

### Expected behavior

The react import should be part of the .tsx cache files.

**Comment by pezexd** [comment]
Same problem, tell me if you fix this

**Comment by joshuaellis** [comment]
That TS config you've shared specifically ignores the admin folder incl. the cache, do you have another tsconfig in your project? 🤔

**Comment by bl96** [comment]
Hi @joshuaellis,

yes there is additional tsconfig in the src/admin with the following content:

```
{
  "extends": "@strapi/typescript-utils/tsconfigs/admin",
  "include": [
    "../plugins/**/admin/src/**/*",
    "./"
  ],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    "**/*.test.ts"
  ]
}
```

**Comment by joshuaellis** [comment]
I've just tried to reproduce by setting up a new project and everything seems to be working, can you share an example of "Have a project which is a mix of .ts/.tsx and .js files." please? Alternatively, if you're able to share a minimal repo of your issue that would be good too :)

**Comment by ofbgames** [comment]
I am experience this as well.  I will add that only when the GuidedTour is triggered will this occur.  For example, if I am already logged, or I have dismissed the tour then this error does not appear.

3 files required editing in total to resolve.

[PR18572](https://github.com/strapi/strapi/pull/18572#issuecomment-1780558255)

**Comment by joshuaellis** [comment]
Great reproduction steps @bl96 👍🏼

**Comment by joshuaellis** [comment]
Okay, after review the conclusion is this:

The `esbuild-loader` for `tsx` is automatically loading the root `tsconfig.json` of your project but this interferes with how we've been developing the admin panel internally at Strapi which is to use `jsx: "react-jsx"` due to the fact the `.cache` folder is a copy of untranspiled source-code from the admin codebase. Hence the issues some are facing.

The immediate quick solution is to do one of the following:

* remove `jsx` from your root `tsconfig` – this is a server designed tsconfig and in theory doesn't require the jsx flag
* set the `jsx` option to `react-jsx` this also solves the issue
* if none of that is preferable, you can "block" esbuild-loader from loading a tsconfig by adding this to your webpack.config file:
```ts
  config.module.rules = config.module.rules.map((rule) => {
    if (rule.options?.loader === "tsx") {
      return {
        ...rule,
        options: {
          ...rule.options,
          tsconfigRaw: {}, // this is the "magic" bit.
        },
      };
    }

    return rule;
  });
```

#18539 might fix all this because we remove the cache folder & all our code is transpiled before publishing to npm so you're no longer loading TSX code from our codebase, I'm yet to test it but a prerelease is being done at time of writing...

**Comment by bl96** [comment]
I could not remove ```jsx``` from the ```compilerOptions``` as I have the .js files with the JSX syntax, maybe a different tsconfig would be needed for that to work outside of the main tsconfig file, however, the second option - to change the ```jsx``` to ```react-jsx``` solved the issue for me.

Thank you for a prompt find!

**Comment by neilmaynard** [comment]
I am also encountering this error. My strapi is not on typescript so I do not have this `tsconfig.js` file to update. Does anyone has an idea how to fix it on Strapi that is not on typescript?

**Comment by joshuaellis** [comment]
> I am also encountering this error. My strapi is not on typescript so I do not have this `tsconfig.js` file to update. Does anyone has an idea how to fix it on Strapi that is not on typescript?

you should supply reproduction steps like bl96 did :)

**Comment by neilmaynard** [comment]
> you should supply reproduction steps like bl96 did :)

I see. Below is the easy way to reproduce this issue. 

1. Install Strapi like how you normally do 
```
npx create-strapi-app@latest my-project
```
2. After installing, it automatically starts the project. You can try stopping it and do
```
npm run build
```
3. Build is fine. But when you `np run develop` your Strapi project again and access it into your browser, you can only see a white screen. Below are the errors found in console.

<img width="683" alt="Screenshot 2023-10-27 at 10 59 40 AM" src="https://github.com/strapi/strapi/assets/40382287/b046edb6-c92e-473e-bd51-443173960566">

**Comment by alex-brukhty** [comment]
Confirming the error persists on v4.15.0

**Comment by DanCookeWillow** [comment]
I am encountering the same problem - `strapi develop` does not work at all, but this issue does not seem to occur when building strapi for production in a Docker container.

It seemingly happened after installing a new plugin, but it seems the issue is with the latest `strapi` version as @neilmaynard 's repro works for me every time as well

**Comment by hanpaine** [comment]
@derrickmehaffy we think this one can be closed; would you mind revalidating please? Thanks!
