### ISSUE TITLE
Unexpected behavior in users-permissions module (middleware)

### ISSUE THREAD

**Issue by BenyaChef** [strapi/strapi#18571]
- Node.js version:  v18.17.1
- Yarn version: 1.22.19
- Strapi version: 4.15.0
- Database: PostgreSQL
- Operating system: Linux 20.04.1-Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Users-permissions module integrated as a middleware in bootstrap() function accepts only incorrect Bearer tokens

### Steps to reproduce the behavior

1. Create a file src/common/users-permissions.ts 
2. Put the code from Strapi GitHub (https://github.com/strapi/strapi/blob/main/packages/plugins/users-permissions/server/strategies/users-permissions.js)
3. Put `console.log("I'm here")` in `authenticate` function in `try` code block
4. Register authStrategy in `bootstrap()` (`await strapi.container.get("auth").register("content-api", authStrategy`))
5. Send graphQL query with correct Bearer token 

### Expected behavior

Output "I'm here" in console

### Additional context

If Bearer token is incorrect there is an output in console

**Comment by Boegie19** [comment]
@BenyaChef this is a none issue since you give it a Bearer token. 
the authenticate function is used to check bear tokens if does not `return {authenticated: true}` 
then it will deny the authentication so it is normal for this function to still run even if the bear token is not correct.
