### ISSUE TITLE
[4.15.0] Adding plugins causes webpack errors 

### ISSUE THREAD

**Issue by rub1e** [strapi/strapi#18594]
### Required System information

- Node.js version: 18.12.1
- NPM version: yarn/1.22.19
- Strapi version: 4.15.0
- Database: sqlite
- Operating system: WSL2 / linux-x64
- Is your project Javascript or Typescript: TS

### Describe the bug

Adding a plugin causes webpack errors

### Steps to reproduce the behavior

1. `yarn create strapi-app my-app --ts --quickstart --no-run`
2. `yarn add [plugin]` - tested with @ckeditor/strapi-plugin-ckeditor / strapi-advanced-uuid / strapi-auto-nanoid
3. `yarn develop`
4. See errors

```
✖ Webpack
  Compiled with some errors in 11.29s

[
  {
    moduleIdentifier: '/home/rubie/dmt-cms/node_modules/highlight.js/lib/languages/arduino.js',
    moduleName: './node_modules/highlight.js/lib/languages/arduino.js',
    loc: '312:15',
    message: 'Module parse failed: Unexpected token (312:15)\n' +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      '|     variants: [\n' +
      '|       {\n' +
      '>         begin: /=/,\n' +
      '|         end: /;/\n' +
      '|       },',
    moduleId: 1232,
    moduleTrace: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object]
    ],
    details: undefined,
    stack: 'ModuleParseError: Module parse failed: Unexpected token (312:15)\n' +
      'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
      '|     variants: [\n' +
      '|       {\n' +
      '>         begin: /=/,\n' +
      '|         end: /;/\n' +
      '|       },\n' +
      '    at handleParseError (/home/rubie/dmt-cms/node_modules/webpack/lib/NormalModule.js:982:19)\n' +
      '    at /home/rubie/dmt-cms/node_modules/webpack/lib/NormalModule.js:1101:5\n' +
      '    at processResult (/home/rubie/dmt-cms/node_modules/webpack/lib/NormalModule.js:806:11)\n' +
      '    at /home/rubie/dmt-cms/node_modules/webpack/lib/NormalModule.js:866:5\n' +
      '    at /home/rubie/dmt-cms/node_modules/loader-runner/lib/LoaderRunner.js:407:3\n' +
      '    at iterateNormalLoaders (/home/rubie/dmt-cms/node_modules/loader-runner/lib/LoaderRunner.js:233:10)\n' +
      '    at /home/rubie/dmt-cms/node_modules/loader-runner/lib/LoaderRunner.js:224:4\n' +
      '    at /home/rubie/dmt-cms/node_modules/webpack/lib/NormalModule.js:840:15\n' +
      '    at Array.eval (eval at create (/home/rubie/dmt-cms/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)\n' +
      '    at runCallbacks (/home/rubie/dmt-cms/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:15)'
  },
[...]
```

All errors seem to relate to highlight.js

* `/node_modules/highlight.js/lib/languages/c.js',`
* `/node_modules/highlight.js/lib/languages/cpp.js`
* `/node_modules/highlight.js/lib/languages/crystal.js`
* etc

### Expected behavior

Build with no errors

**Comment by hugofabricio** [comment]
I'm getting the same error here.

**Comment by axelraymundo** [comment]
I'm getting the same error here as well when I try to rebuild my admin

**Comment by philiptse1** [comment]
I got the same error when upgraded to 4.15.0. Then I fresh installed the release 4.15.0 to test it, encountered the same problem.

**Comment by werty37** [comment]
I had a similar issue. Not sure why it was marked spam. #18597

**Comment by DanielZhui** [comment]
I had a similar issue. Does anyone solve this promblem

**Comment by maksymenkoml** [comment]
Same

**Comment by joshuaellis** [comment]
> I had a similar issue. Not sure why it was marked spam. #18597 

Sorry that should have been duplicate.

**Comment by M-Nasser-M** [comment]
i had the same problem and running the build command while setting node end to development worked with me 

`node_env=development npm run build`

**Comment by PrathibhaPA** [comment]
i have the same issue with strapi v.4.13.1.. any solution for this?

**Comment by 523299338** [comment]
4.13.5     getting the same error here.

**Comment by joshuaellis** [comment]
Can anyone verify if this happens:

- when you _only_ create a new strapi app
- when you install plugins that **we maintain**

**Comment by 523299338** [comment]
> 4.13.5 getting the same error here.

in windows ,  
It seems the error occurred suddenly starting today

**Comment by DanielZhui** [comment]
you can used yarn to replace npm install, i use yarn to fixed the isssue

**Comment by schminkel** [comment]
using the build command like this fixes the issue
`node_env=development sudo npm run build`

**Comment by M-Nasser-M** [comment]
> Can anyone verify if this happens:
> 
> * when you _only_ create a new strapi app
> * when you install plugins that **we maintain**

it happened to me after i upgraded my versions to 4.15.0, so wasn't a new project and wanted to do a fresh build and npm install so i deleted cache and node modules and after looking into some old issues it suggested that some plugins need the node_env to be explicitly set i think if it can help here is  a list of  my package

`    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@notum-cz/strapi-plugin-content-versioning": "^1.1.4",
    "@strapi/plugin-color-picker": "^4.15.0",
    "@strapi/plugin-i18n": "4.15.0",
    "@strapi/plugin-seo": "^1.9.6",
    "@strapi/plugin-users-permissions": "4.15.0",
    "@strapi/provider-upload-cloudinary": "^4.15.0",
    "@strapi/strapi": "4.15.0",
    "pg": "8.11.3",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-local-image-sharp": "^1.7.0",
    "strapi-plugin-meilisearch": "^0.10.0",
    "strapi-plugin-placeholder": "^4.4.0",
    "strapi-plugin-publisher": "^1.5.2",
    "strapi-plugin-transformer": "^3.1.2"`

**Comment by essj** [comment]
I’m on 4.5.6 with a stable app, triggered a build today without any package changes and it failed with this error.

These are the plugins I use:
```
"@strapi/plugin-i18n": "4.5.6",
"@strapi/plugin-users-permissions": "4.5.6",
```

I also have a custom plugin and a patched version of `@strapi/provider-upload-aws-s3` as a custom provider.

**Comment by hugofabricio** [comment]
> Can anyone verify if this happens:
> 
> * when you _only_ create a new strapi app
> * when you install plugins that **we maintain**

Yes, I got the error when installing any of these 4 plugins in a new project or in the project I am working on.

```
    "strapi-plugin-multi-select": "^1.2.2",
    "strapi-plugin-populate-deep": "^3.0.0",
    "strapi-plugin-transformer": "^3.1.2",
    "strapi-plugin-vercel-deploy": "^1.4.0"
```

**Comment by joshuaellis** [comment]
> > Can anyone verify if this happens:
> 
> > 
> 
> > * when you _only_ create a new strapi app
> 
> > * when you install plugins that **we maintain**
> 
> 
> 
> Yes, I got the error when installing any of these 4 plugins in a new project or in the project I am working on.
> 
> 
> 
> ```
> 
>     "strapi-plugin-multi-select": "^1.2.2",
> 
>     "strapi-plugin-populate-deep": "^3.0.0",
> 
>     "strapi-plugin-transformer": "^3.1.2",
> 
>     "strapi-plugin-vercel-deploy": "^1.4.0"
> 
> ```

I'm not sure those are our plugins..? We normally namespace wit

**Comment by hugofabricio** [comment]
@joshuaellis these are community plugins, only with your plugins the error does not occur, I made a new attempt now (I had done the same thing a few times yesterday), removing package-lock.json and installing again, build done successfully.

@rub1e @ axelraymundo can you also test if it still happens?

**Comment by hugofabricio** [comment]
@joshuaellis, i tested now with the plugins mentioned by @rub1e, the build was carried out successfully.

```
@ckeditor/strapi-plugin-ckeditor
strapi-advanced-uuid
strapi-auto-nanoid
```

1. Removed node_modules
2. I removed package-lock.json
3. `npm install`

**Comment by brandsquare** [comment]
Same problem and finally this worked for me:

1. Removed node_modules
2. Removed package-lock.json
3. npm install

**Comment by derrickmehaffy** [comment]
Closing this since several people confirm it's resolved

**Comment by werty37** [comment]
I had removed `strapi-plugin-multi-select` plugin. Deleted the node_modules and package_lock.json and did npm install. But the error still persists. This is my dependencies block from package.json.

```
"dependencies": {
    "@strapi/plugin-documentation": "4.15.0",
    "@strapi/plugin-graphql": "4.15.0",
    "@strapi/plugin-i18n": "4.15.0",
    "@strapi/plugin-users-permissions": "4.15.0",
    "@strapi/strapi": "4.15.0",
    "better-sqlite3": "8.6.0",
    "pg": "^8.11.3",
    "pg-connection-string": "^2.6.2"
  },
```

**Comment by derFunk** [comment]
I have the same issue also after deleting node_modules and removing package_lock.json.

My dependencies:

```
"dependencies": {
    "@strapi/plugin-documentation": "^4.15.0",
    "@strapi/plugin-i18n": "^4.15.0",
    "@strapi/plugin-users-permissions": "^4.15.0",
    "@strapi/strapi": "^4.15.0",
    "pg": "^8.7.3",
    "pg-connection-string": "^2.5.0",
    "sqlite3": "^5.0.2",
    "strapi-location-field-plugin": "^1.2.2",
    "strapi-plugin-import-export-entries": "^1.21.1"
  },
```
