### ISSUE TITLE
Strapi does not work on a custom port.

### ISSUE THREAD

**Issue by maksymenkoml** [strapi/strapi#18596]
I've been using Strappy for over a year now.
Today I updated to version 4.15.0 and Strapi stopped working on a port other than the default.

I tried a fresh clean install of Strapi with the command: `yarn create strapi-app my-project --quickstart`
After running the command, Strapi runs on port 1337.
But if you change the PORT value in the .env file, and restart Strapi with the `strapi develop` or `strapi start` command, it starts on the new port, but we get the following errors in the browser:
<img width="1277" alt="image" src="https://github.com/strapi/strapi/assets/122663362/ca065dc3-7ecb-4acc-abdc-1ec794ee319d">

**Comment by maksymenkoml** [comment]
@joshuaellis, I've updated the description by template. Please reopen.

**Comment by derrickmehaffy** [comment]
No need to reopen, the answer is you need to rebuild the admin once you change the port.

Run `yarn build` or `npm run build`

**Comment by maksymenkoml** [comment]
> No need to reopen, the answer is you need to rebuild the admin once you change the port.
> 
> Run `yarn build` or `npm run build`

I don't know if you've tried to reproduce this problem, but `yarn develop' also does a project build.
So the problem is still there.

**Comment by derrickmehaffy** [comment]
It's a fake build, realistically it uses the one we ship by default however there is a PR that will solve this and make it easier for users who don't know in the near future as in develop mode it's going to run the react app as a service and not statically compile it.

Production usage will still require an admin build
