### ISSUE TITLE
Blank Screen on Custom Field Tab After Installing “@strapi/plugin-color-picker

### ISSUE THREAD

**Issue by jarren15** [strapi/strapi#18595]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.2.1
- Strapi version: 4.15.0
- Database: PostgreSQL 
- Operating system: Windows 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After installing the “@strapi/plugin-color-picker” plugin, I’m encountering an issue where I just get a blank screen when I navigate to the custom field tab. 

### Steps to reproduce the behavior

1. Install the “@strapi/plugin-color-picker” plugin.
2. Navigate to the custom field tab.
3. See error

### Expected behavior

The custom field tab should load correctly and display the appropriate fields.

### Screenshots

![image](https://github.com/strapi/strapi/assets/81326232/98e52ce4-3ab6-4def-bc0d-fd65a7d558fb)

**Comment by joshuaellis** [comment]
Closed by #18583
