### ISSUE TITLE
Error with color-picker-plugin

### ISSUE THREAD

**Issue by pezexd** [strapi/strapi#18604]
### Required System information
- Node.js version: 21.0.0
- Strapi version: 4.15.0
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Get error when enter to edit a content-type that use color-picker plugin.

### Screenshots

![Screenshot 2023-10-28 163224](https://github.com/strapi/strapi/assets/59552060/2f684e3e-ffa0-4551-9053-9ff8c3d43c98)

### Additional context

I see that the development team has upload a pull request to fix this issue, but I have deleted node_modules & package-lock.json and runned npm install and rebuilded the admin panel without any success for this error related to jsxDev is not a function. Please, not attach the pull request to it thread, give me some temporally solution.

**Comment by Boegie19** [comment]
temp work around would be settings NODE_ENV in your env to production and rebuilding.

**Comment by SoniGuptaKissht** [comment]
tried above solution but still facing the color picker issue

**Comment by Boegie19** [comment]
did you rebuild the admin?

**Comment by SoniGuptaKissht** [comment]
> did you rebuild the admin? `npm run build` `yarn build`

yes @Boegie19

**Comment by Boegie19** [comment]
Then Idk I guess you have to wait for the next release.

**Comment by kiendv-3143** [comment]
@SoniGuptaKissht try to install v4.14.5, it is working well with me

**Comment by SoniGuptaKissht** [comment]
> @SoniGuptaKissht try to install v4.14.5, it is working well with me

@kiendv-3143 have tried v4.14.5 still facing issue

package.json file 

 "dependencies": {
    "@strapi/plugin-color-picker": "^4.14.5",
    "@strapi/plugin-documentation": "4.14.5",
    "@strapi/plugin-i18n": "4.14.5",
    "@strapi/plugin-sentry": "^4.14.5",
    "@strapi/plugin-users-permissions": "4.14.5",
    "@strapi/provider-upload-aws-s3": "^4.14.5",
    "@strapi/strapi": "4.14.5",
    "mysql2": "3.6.0",
    "strapi-plugin-multi-select": "^1.2.2",
    "strapi-plugin-populate-deep": "^3.0.0",
    "strapi-plugin-publisher": "^1.4.0",
    "strapi-plugin-transformer": "^3.1.0"
  }

**Comment by kiendv-3143** [comment]
@SoniGuptaKissht try the steps below:
1. Remove **node_modules**
2. yarn install
3. yarn build
4. yarn develop

**Comment by SoniGuptaKissht** [comment]
@kiendv-3143 tried rebuilding the project. but still same issue

**Comment by SoniGuptaKissht** [comment]
@kiendv-3143 thanks for support. working now for me

updated package.json with below 
"dependencies": {
"@strapi/plugin-color-picker": "4.14.5",
"@strapi/plugin-documentation": "4.14.5",
"@strapi/plugin-i18n": "4.14.5",
"@strapi/plugin-sentry": "^4.14.5",
"@strapi/plugin-users-permissions": "4.14.5",
"@strapi/provider-upload-aws-s3": "^4.14.5",
"@strapi/strapi": "4.14.5",
"mysql2": "3.6.0",
"strapi-plugin-multi-select": "^1.2.2",
"strapi-plugin-populate-deep": "^3.0.0",
"strapi-plugin-publisher": "^1.4.0",
"strapi-plugin-transformer": "^3.1.0"
}

**Comment by jramstedt** [comment]
Hi @Boegie19 and @Marc-Roig 

This is still problem with 4.15.0.

It may be that @strapi/plugin-color-picker is built wrong in 4.15.0:

If you take a look at file "/@strapi/plugin-color-picker/dist/_chunks/ColorPickerInput-6f0d1bb5.js" the [released npm package](https://www.npmjs.com/package/@strapi/plugin-color-picker/v/4.15.0?activeTab=code) 

You can see there is jsxDevRuntime in the code. I think it should be jsxRuntime.
There is also very ugly debug stuff around like file paths such as: "/Users/marcroig/Documents/strapi/strapi/packages/plugins/color-picker/admin/src/components/ColorPickerInput.tsx"
