### ISSUE TITLE
Strapi v4.15.0: Admin panel crashes on clicking ADVANCED SETTINGS tab for datetime field

### ISSUE THREAD

**Issue by bhishekprajapati** [strapi/strapi#18602]
### Required System information

- Environment: development
- Node.js version: 18.18.1
- yarn version: 1.22.19
- Strapi version: **4.15.0**
- Database: mysql
- Operating system: linux-x64 (ubuntu 22.04)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When adding a new datetime field to a collection type and clicking the ADVANCED SETTINGS tab, the screen goes blank!

### Expected behavior

To be able to see and interact with the ADVANCED SETTINGS tab of the datetime field I'm trying to configure.

### Screenshots

![Screenshot from 2023-10-28 21-51-04](https://github.com/strapi/strapi/assets/91626944/00d38c5e-b869-45e5-95d3-709cf5bc319d)
![Screenshot from 2023-10-28 21-51-27](https://github.com/strapi/strapi/assets/91626944/75e14f47-7f1c-4dcf-8cbf-56b4fa6d7382)

### Additional context
Referencing a related issue #18573

**Comment by Boegie19** [comment]
@bhishekprajapati Just to confirm you ran `npm run build` or `yarn build` after updating?

**Comment by bhishekprajapati** [comment]
@Boegie19 No!

After upgrading to v4.15.0 I just ran `yarn develop` and got the bug. I tried deleting the `node_modules` and reinstalling dependencies. Also, didn't work!

**Comment by Boegie19** [comment]
Please run the yarn build or npm run build command that fixes your problem

**Comment by bhishekprajapati** [comment]
Thanks! That solved my problem.

How did it worked this time? can you please help me understand?

**Comment by Boegie19** [comment]
admin UI was still on your old version admin does not auto rebuild if you update your strapi version.

so if you run build you tell strapi to rebuild the admin ui

**Comment by bhishekprajapati** [comment]
ohh...Thank you!
