### ISSUE TITLE
Strapi keeps localhost instead production URL

### ISSUE THREAD

**Issue by gabsmariapdev** [strapi/strapi#18605]
Hi everyone, i dont know if its a bug but lets do this.. maybe i just need some help to understand how things works...

### Required System information

- Node.js version: 14.1
- NPM version: 6.14.17
- Strapi version: 4.3.8
- Database: postgresql
- Is your project Javascript or Typescript: TS

### Describe the bug

My strapi always tries to hit localhost:1337/admin/init or admin/project-type, the other files like main.js runtime-main.js manage to be resolved, this is my server.ts and my production/server.ts

```
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
});

config/server.ts
```

```
export default ({ env }) => ({
    url: env('MY_CMS_URL'),
});

config/env/production/server.ts
```

and not less important my dockerfile

```
FROM some-docker-base/nodejs-14:1.1.0.RELEASE AS dependencies

ARG BUILD_ARGS
ENV APP_HOME "/opt/app/nodejs"

USER root

WORKDIR ${APP_HOME}
VOLUME node_modules:/usr/local/lib/node_modules/

RUN npm get cache

ADD .ci/files/local.repo /etc/yum.repos.d/local.repo
COPY .ci/files/.npmrc ./package.json ./

RUN export NODE_ENV= \
  && export NODE_TLS_REJECT_UNAUTHORIZED=0 \
  && export http_proxy=http://some_proxy.corp:80 \
  && export https_proxy=$http_proxy \
  && export no_proxy=.corp \
  && npm install --verbose --unsafe-perm


FROM dependencies AS unit_tests

COPY . ./
RUN ls -la
RUN npm run test


FROM unit_tests AS build

RUN ls -la
RUN npm run build


FROM some-docker-base/nodejs-14:1.1.0.RELEASE
ARG NAME
ARG VERSION
LABEL VENDOR=COMPANY_NAME
LABEL NAME=$NAME
LABEL VERSION=$VERSION
LABEL MAINTAINER="developer@company.com.br"

ENV NODEJS_PORT 8080
ENV APP_HOME "/opt/app/nodejs"

EXPOSE $NODEJS_PORT
WORKDIR ${APP_HOME}

COPY --from=build $APP_HOME/ .

USER root
RUN chown -R nodejs:nodejs $APP_HOME

USER xxxx

COPY Dockerfile $IMAGE_SCRIPTS_HOME/Dockerfile

ENTRYPOINT [ "/bin/sh", "/opt/app/nodejs/entrypoint.sh" ]

```

I'm using Red Hat's OpenShift so I have some envs like MY_CMS_URL and  NODE_ENV defined in env.conf files, something like:

```
NODE_ENV=production
MY_CMS_URL=xpto.corp/
```

What am I forgetting so that my localhost:1337 is replaced by xpto.corp?

<img width="1234" alt="Screenshot 2023-10-28 at 21 11 38" src="https://github.com/strapi/strapi/assets/149277238/4ae1ece9-a9cf-46fe-928c-839778828451">

**Comment by jasontheiler** [comment]
I've just run into the same problem on Strapi `v4.10.7` using Node.js `v18.18.2` in Docker.
The admin panel always tries to request from `http://localhost:1337/admin/init` and `http://localhost:1337/admin/project-type` instead of the set `url`, eventhough `proxy` is set to `true`.

**Comment by derrickmehaffy** [comment]
> I've just run into the same problem on Strapi `v4.10.7` using Node.js `v18.18.2` in Docker.
> The admin panel always tries to request from `http://localhost:1337/admin/init` and `http://localhost:1337/admin/project-type` instead of the set `url`, eventhough `proxy` is set to `true`.

You probably aren't setting the URL during build (env var) or in a multi stage container you aren't copying the build directory.

If you don't run a yarn build or npm run build it will not work.

We can dang near promise this isn't a bug and is 99.99% your docker file.

**Comment by jasontheiler** [comment]
Okay, yeah, that was it ... we forgot to add `strapi build` before running `strapi develop`.

But to be fair, this behaviour doesn't really fall in line with most other tools and frameworks from my experience. Without prior knowledge, I would've assumed that the `develop` command automatically bootstraps everything that is necessary to use Strapi during development.

But in any case, thank you for the quick help! 🚀

**Comment by derrickmehaffy** [comment]
No we have a recompiled version of the admin that ships with the localhost:1337 since most of our users don't use docker locally this speeds up the start time since the admin doesn't need to be built (it already is).

If you don't build, don't have a build folder, then it uses the recompiled one from node_modules.

I personally don't like that but the decision was made far above me so. If it were me, I'd make it build every time.

**Comment by jasontheiler** [comment]
Ah, this actually makes a lot of sense. Thank you for going the extra mile by explaining this. I really appreciate that!

**Comment by derrickmehaffy** [comment]
> Ah, this actually makes a lot of sense. Thank you for going the extra mile by explaining this. I really appreciate that!

No problem at all, it's a common issue I've seen over the years :)

**Comment by SharbelWired** [comment]
@derrickmehaffy any chance you can shed some light on if the hitting of localhost when deployed can be traced to the fact that when yarn build occurs, there are errors listed in the output, even though the admin app compiles successfully according to the logs?  The docker file has yarn build before the final CMD['yarn', 'start'] and I have also tried setting an entry point to an => entrypoint.sh bash script that would yarn build / start in there as I read that the env vars may not be getting applied.  

I do see the logs to access the admin panel / server and it does show the correct URL.  The service works, meaning the front-end app can hit the APIs.  It's just the /admin endpoint always tries to hit localhost. 

If I am seeing this message in my container logs, does this mean that everything compiled properly? =>  

```
Actions available
Welcome back!
To manage your project 🚀, go to the administration panel at:
https://{my-custom-domain}/admin

To access the server ⚡️, go to:
https://{my-custom-domain}
```

**Comment by derrickmehaffy** [comment]
No that is the backend server only. The build command compiled the react app into a static output and serves it as a typical webserver would. We automatically include a pre built admin by default with the localhost:1337 so if there is no build folder it's using our default from the node modules.

Best guess is your build of the admin fails and it falls back to using ours, or you are successfully building but if it's a multi-step container build then the build folder isn't being copied to the runtime directory.

**Comment by SharbelWired** [comment]
Thanks @derrickmehaffy for explaining that.  You did mention this above in another post, but I wasn't grasping the point that the it's two different builds.  So I am looking at the output when I run yarn or npm build, and I see a lot webpack `Module parse failed: Unexpected token` errors.  That being said, It ends with a success message like this => 
```
Building your admin UI with development configuration ...

× Webpack
  Compiled with some errors in 4.28s
{webpack-module-parse-errors-repeat-here}

Admin UI built successfully
```
Is this indicative of a failed build even though it says it succeeded? Do I need to solve all of the Module Parse errors in order for the admin app to really succeed? If so, do you have advise on how to solve the module parse failed errors?

**Comment by derrickmehaffy** [comment]
I believe that message is a bit misleading, the actual build failed and onced that happened it would have pulled "our build" from the node_modules so it does "see" a successful build but in reality it's the one using localhost:1337 most likely.

I'm guessing you are using at least a two step docker container build meaning the admin build fails in step 1 but during runtime it "builds successfully" because of the build from the node_modules.

I'd start by trying to debug those webpack errors as it could be an issue with my 3rd party plugins, missing "system packages" in the container, or various other reasons.

Based on that error though it seems to be some variable that is required isn't being defined.

**Comment by SharbelWired** [comment]
Thanks @derrickmehaffy I was able to solve the issue.  There was a plugin that was the culprit.  Once I disabled it, the webpack compile errors disappeared and I was able to access the admin panel on the deployed stage.   Thanks again for your help!
