### ISSUE TITLE
New user has no provider value after created by admin 🤔

### ISSUE THREAD

**Issue by hhmx** [strapi/strapi#18606]
### Required System information

- Node.js version: 16.20.2
- NPM version: 8.19.4
- Strapi version: 4
- Database: Postgres
- Operating system: Windows (local)
- Is your project Javascript or Typescript: JS

### Describe the bug

When I create a new user via Admin, ‘provider’ has the value “null”. Why is “null” the default value here instead of “local”?

Every time I have to enter 'local' in the database myself, because without this value, the new user cannot log in at all. I think this must be a bug. 🐛

### Expected behavior

'local' should be a default value.

### Screenshots

![image](https://github.com/strapi/strapi/assets/38818304/5fe02e8c-113b-4c4c-b662-cdb54a52d0c5)

![image](https://github.com/strapi/strapi/assets/38818304/e8e758ac-921b-420a-8c21-7cc2610fff03)

![image](https://github.com/strapi/strapi/assets/38818304/a92dde99-f16e-43f0-8e38-86f8693de46c)

**Comment by Boegie19** [comment]
Tried to reproduce this issue on 1.15.0 the provider is using local for me.
did you make change any of the strapi logic for creating users? if not can you try and reproduce this on a fresh strapi instance and give us the replication staps
