### ISSUE TITLE
Facebook provider is broken: wrong request_uri

### ISSUE THREAD

**Issue by jrodriguesimg** [strapi/strapi#1861]
**Informations**
- **Node.js version**: v9.11.2
- **npm version**:5.6.0
- **Strapi version**: 3.0.0-alpha-14
- **Database**: MySQL
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**

request_uri for the facebook provider is generated with http. http uris are rejected by facebook (except localhost uris for dev)

**Steps to reproduce the problem**

Setup facebook provider and send GET <host>/connect/facebook

**What is the expected behavior?**

request_uri is accepted by facebook.

**Suggested solutions**

Use a configurable protocol instead of an hard coded one in `plugins/users-permissions/controllers/Auth.js` in the following lines:

```
_.defaultsDeep(grantConfig, {
      server: {
        protocol: 'http',
        host: `${strapi.config.currentEnvironment.server.host}:${strapi.config.currentEnvironment.server.port}`
      }
});
```

I tried just hard coding https so that facebook accepts the request_uri, but it will trigger another error down the line in the `plugins/users-permissions/services/Providers.js`. More specifically in the following lines:

```
const users = await strapi.query('user', 'users-permissions').find({
          where: {
            email: profile.email
          }
});
```

It will throw an object as error that is caught and passed to the reject function. The error object is empty so I have no idea for what might be the cause.

**Comment by derrickmehaffy** [comment]
PR In progress: https://github.com/strapi/strapi/pull/1851

**Comment by abdonrd** [comment]
I am not able to setup providers on staging/production too!
