### ISSUE TITLE
Upgrading from alpha13.1 - 14 breaks Content Manager screen

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#1862]
**Informations**
- **Node.js version**:
v10.9.0
- **npm version**:
6.4.0
- **Strapi version**:
alpha 14
- **Database**:
MySQL
- **Operating system**:
macOS 10.13.6 (17G65)

**What is the current behavior?**
I visit the a specific model in the Content Manager and I get a blank screen and a javascript error in my console.

**Steps to reproduce the problem**
- I had an existing installation of alpha 13.1
- I followed the upgrade steps from the migration guide exactly
- I visited http://localhost:1337/admin/plugins/content-manager/ctm-configurations/my-model
- I see a blank screen

**What is the expected behavior?**
I expect to see a screen that will allow me to configure my-model

**Suggested solutions**
Not sure as I don't have any source maps for the javascript. I see this in the console though:

```
main.js:56 uncaught at o TypeError: Cannot read property 'forEach' of undefined
    at e.value (http://localhost:1337/admin/content-manager/main.js:46:271113)
    at new e (http://localhost:1337/admin/content-manager/main.js:46:269880)
    at http://localhost:1337/admin/content-manager/main.js:40:571962
    at Me (http://localhost:1337/admin/content-manager/main.js:6:14396)
    at Me (http://localhost:1337/admin/content-manager/main.js:6:14486)
    at Me (http://localhost:1337/admin/content-manager/main.js:6:14486)
    at Me (http://localhost:1337/admin/content-manager/main.js:6:14486)
    at Me (http://localhost:1337/admin/content-manager/main.js:6:14486)
    at Me (http://localhost:1337/admin/content-manager/main.js:6:14486)
    at de.updateIn (http://localhost:1337/admin/content-manager/main.js:6:36002)
```

if I prettify the code in chrome, the issue is happening here in main.js:

```javascript
key: "getLinesBound",
value: function() {
    var e = this
      , t = []
      , n = 0;
    return this.list.forEach(function(r, o) { // <---- this is where the issue is.
        var i = e.getAttrInfos(o)
          , s = i.bootstrapCol
          , a = i.index
          , l = i.name;
```

I can also confirm that ```this.list``` is 'undefined' when debugging the above code which is what is causing the issue.

**Comment by derrickmehaffy** [comment]
Did you do the following?

> The stored data format has been changed. That is why you will have to delete in the core_store collection/table the entry with the key plugin_content-manager_schema.

**Comment by greatwitenorth** [comment]
@derrickmehaffy yes I did that step.

**Comment by derrickmehaffy** [comment]
@greatwitenorth I wasn't able to reproduce this issue, I would suggest you do a "clean" upgrade using my steps here: https://github.com/strapi/strapi/issues/1880

**Comment by greatwitenorth** [comment]
Closing as I tried the above steps again on a backup and now it's working as expected. Not sure what went wrong.

**Comment by yummyelin** [comment]
I met the same issue. Exactly the same steps to reproduce, and the same console error.

```
main.js:16 TypeError: Cannot read property 'forEach' of undefined
    at e.value (main.js:66)
    at new e (main.js:66)
    at main.js:60
    at Me (main.js:6)
    at Me (main.js:6)
    at Me (main.js:6)
    at Me (main.js:6)
    at Me (main.js:6)
    at Me (main.js:6)
    at de.updateIn (main.js:6)
```

- **Node.js version**:  v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: mongodb
- **Operating system**: macOS

It would be a great help if there is a better way to clean upgrade except #1880. Because I have 15-20  content-types, and I modified services/controllers/models files.

**Comment by lauriejim** [comment]
@soupette any idea ?
