### ISSUE TITLE
The media library doesn't display the items even they exist?

### ISSUE THREAD

**Issue by matsukky** [strapi/strapi#18631]
### Required System information

Environment: production
OS: linux-x64
Strapi Version: 4.15.0
Node/Yarn Version: npm/9.8.1 node/v18.18.2 linux x64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

the Media Library displays all the folders correctly (in my case 2), the second containing 3 images (published before the migration from 4.10 to 4.15) are visible. The main folder containing the images from my projects correctly displays the 3 sub-folders, which themselves show the correct number of images that should be in them. But when I open the sub-folder, no image is visible, I'm prompted to drop files... the most disturbing thing is that the image link works fine, and the previews too.
Even more disturbing, when I copy the db and upload folder to my dev environment (MacOS Ventura, npm/9.8.1 node/v18.18.2) the bug doesn't occur... Incomprehensible.

My docker application is built by a github action. There doesn't seem to have been any problem during creation that would explain this only happening on the production application.

### Steps to reproduce the behavior

Honestly, I haven't the slightest idea...

### Expected behavior

Images are displayed correctly

### Screenshots

![image](https://github.com/strapi/strapi/assets/46320254/55e839f1-35d1-457a-9867-65e16627d8c6)
![image](https://github.com/strapi/strapi/assets/46320254/4f7b6801-6131-4011-87db-43d2a7815235)

**Comment by derrickmehaffy** [comment]
You are probably missing this migration script: https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.7.0-to-4.11.4

**Comment by matsukky** [comment]
I try [this step](https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.7.0-to-4.11.4#installing-database-migration-script-optional) and those after in prod and dev environment. Dev already works fine, so I didn't see any change. Prod test doesn't work.

**Comment by matsukky** [comment]
so... i think it's work now... i downgrade to 4.11.4 and change account and it's work

**Comment by rwadud** [comment]
> You are probably missing this migration script: https://docs.strapi.io/dev-docs/migration/v4/migration-guide-4.7.0-to-4.11.4

I tried this migration script but it did not do anything.

I ran this in mysql and fixed it. 
`
UPDATE files
INNER JOIN files_folder_links ON files.id = files_folder_links.file_id
INNER JOIN upload_folders ON files_folder_links.folder_id = upload_folders.id
SET files.folder_path = upload_folders.path;
`
