### ISSUE TITLE
Adding new required field with default value does not fill existing entries

### ISSUE THREAD

**Issue by passionate-bram** [strapi/strapi#18636]
### Required System information

- Node.js version: v21.1.0
- NPM version: 10.2.0
- Strapi version: v4.13.2
- Database: postgres
- Operating system: `Linux 9a299620-a9fd-4903-b8f6-9a2ce2b005bc 4.4.0-1104-aws #109-Ubuntu SMP Tue May 10 11:27:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Is your project Javascript or Typescript: typescript

### Describe the bug

I've ran into an issue with Strapi in terms of schema consistency, after adding a new field to an existing component type.
In this case the component already had records/rows in the database already.

I added a new field to the component, see here its definition from the `.json`:

```json5
"appearance": {
    "type": "enumeration",
    "enum": [
      "bleach",
      "box"
    ],
    "default": "bleach",
    "required": true
  }
}
```

From this, I expected existing records to automatically get the default value filled in, but this did not happen.

In the database the column `appearance` was created and set to `varchar(255)`, without a `not null` constraint.
This does not matter entirely for the resulting problem but is perhaps a point of attention.

The real problem manifested itself after the database migrated. In our case we are using the GraphQL api, and the schema is presenting the field `appearance` as non-optional. What happened next is that any query that included component instances (database records) pre-`appearance` would trigger a server-side error because the GraphQL engine would throw a fit for having non-optional data missing.

Thus there are two parts of the strapi system in conflict:

1. The GraphQL api assumes the schema for components is true, and that a required field cannot be empty / null.
2. The migration strategy of strapi permits schema violations for existing entities.

### Steps to reproduce the behavior

1. Have a component, with existing records in the database
2. Add a new field (in my case an enum), make it required and set a default value
3. Migrate
4. Use GraphQL to query for the existing data

### Expected behavior

Existing instances of the component have the new field set with the default value during migration

### Screenshots

N/A

### Code snippets

N/A

### Additional context

N/A

**Comment by passionate-bram** [comment]
> In order to keep our GitHub issues clean and for valid bug reports this issue will be marked as closed

So the default behaviour of Strapi migrations breaking the supported GraphQL API is not a bug, somehow?

**Comment by Sydfg** [comment]
"appearance": {
    "type": "enumeration",
    "enum": [
      "bleach",
      "box"
    ],
    "default": "bleach",
    "required": true
  }
}

**Comment by passionate-bram** [comment]
@Sydfg that is exactly what I have in the schema json file, and is what led to the described behaviour. So if you expect to set `required:true` with a `default: ???` then it will not fill the column on existing records.

Isn't a straightforward solution to create the column with a `default` clause, and if you find having a `not null` clause on the db problematic then you can drop the constraint afterwards. Either that or create the column and then do an update that fills out the default into all existing records.
