### ISSUE TITLE
Blank white screen appears when trying to add a component in dynamic zones in version 4.15.0

### ISSUE THREAD

**Issue by aryav-022** [strapi/strapi#18633]
### Required System information

- Node.js version: 20.9.0
- YARN version: 1.22.19
- Strapi version: 4.15.0
- Database: postgres and sqlite (didn't tested for others)
- Operating system: win32-x64 (windows11)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When i try to add a component in dynamic zone, a blank white screen appears as shown in the image below:

<img width="960" alt="image" src="https://github.com/strapi/strapi/assets/69618788/5c59b12b-0dbe-4495-ba45-fddacf4c7409">

and browser console throws the error: 
```console
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
at La (content-type-builder.a43000f9.chunk.js:149:5319)
at Ji (main.08cd748f.js:744:20470)
at Pd (main.08cd748f.js:746:45155)
at ld (main.08cd748f.js:746:40774)
at fh (main.08cd748f.js:746:40702)
at Wc (main.08cd748f.js:746:40556)
at Uc (main.08cd748f.js:746:36811)
at bf (main.08cd748f.js:746:37616)
at bs (main.08cd748f.js:744:3278)
at main.08cd748f.js:746:35128
```

**This problem does not arrise in strapi@4.14.0**

The problem has been discussed on strapi forums here: 
https://forum.strapi.io/t/error-when-clicking-on-add-a-component-in-dynamic-zone-typeerror-cannot-read-properties-of-undefined-reading-length/33211

### Steps to reproduce the behavior

1. Create a strapi app (quick-start) in version 4.15.0
2. Start the development environment using `yarn develop`
3. Create a components using admin panel and save
4. Create a single/collection type using admin panel and add a dynamic zone type in it
5. In dynamic zone type, add the component previously made
6. Now create another component
7. in the earlier made single/collection type, try to add a component to dynamic zone
8. A blank white screen should appear as discussed above and browser console should show the error message

**Comment by derrickmehaffy** [comment]
Can you confirm if this is in the content type builder or manager?

**Comment by aryav-022** [comment]
it is in content type builder

**Comment by bmarianome** [comment]
Hey @aryav-022, did you find any version working? I already tried 4 downgrades

In my case, this is the component in the dynamic zone: 
```
{
  "collectionName": "components_componentes_medidas_disponibles",
  "info": {
    "displayName": "Medidas disponibles",
    "description": ""
  },
  "options": {},
  "attributes": {
    "medida": {
      "type": "enumeration",
      "enum": [
        "medida_190x80",
        "medida_190x90",
        "medida_190x100",
        "medida_190x140",
        "medida_200x160",
        "medida_200x180",
        "medida_200x200"
      ],
      "required": true
    },
    "precio": {
      "type": "integer",
      "required": true
    }
  }
}
```

And this is the error: 
![Screenshot 2023-11-01 131000](https://github.com/strapi/strapi/assets/70652590/433d6ea8-6101-4840-83a2-ae20bbcf9035)

**Comment by aryav-022** [comment]
> In my case, this is the component in the dynamic zone:
> 
> ```
> {
>   "collectionName": "components_componentes_medidas_disponibles",
>   "info": {
>     "displayName": "Medidas disponibles",
>     "description": ""
>   },
>   "options": {},
>   "attributes": {
>     "medida": {
>       "type": "enumeration",
>       "enum": [
>         "medida_190x80",
>         "medida_190x90",
>         "medida_190x100",
>         "medida_190x140",
>         "medida_200x160",
>         "medida_200x180",
>         "medida_200x200"
>       ],
>       "required": true
>     },
>     "precio": {
>       "type": "integer",
>       "required": true
>     }
>   }
> }
> ```
> 
> And this is the error: ![Screenshot 2023-11-01 131000](https://user-images.githubusercontent.com/70652590/279732051-433d6ea8-6101-4840-83a2-ae20bbcf9035.png)

i didn't saw any problem in strapi version 4.14.0, so i would reccommend trying that version if not already.
In my case the error message isn't displayed on admin ui... you can check the browser console to see if it matches the error i pasted in the bug report.

You can try reproducing the problem in an isolated environment with the steps i mentioned above... If the problem still exists, i think it will be the same problem of this issue

**Comment by bmarianome** [comment]
@aryav-022 Yes, `4.14.0` is working.

You're right, is another error, but I think it's related
![Screenshot 2023-11-01 142836](https://github.com/strapi/strapi/assets/70652590/0f6ef3b6-3437-4184-8a1c-3842f60b3e00)

Should I open another issue?

**Comment by bmarianome** [comment]
> @bmarianome Did you run `yarn build` or `npm run build` after chancing the version

Yes, initially I forgot to do it, I already edited the first comment. `4.14.0` is working

**Comment by eveyrat** [comment]
Same issue here

**Comment by 1danii** [comment]
Same issue on new 4.15 app
<img width="407" alt="Screenshot 2023-11-07 at 8 37 34" src="https://github.com/strapi/strapi/assets/34248806/bb848893-74d8-458c-9ec7-5bd05ba8f9c4">

**Comment by 1danii** [comment]
Same issue here on a new 4.15 app, is there a way to downgrade to a version where this works?
<img width="407" alt="Screenshot 2023-11-07 at 8 37 34" src="https://github.com/strapi/strapi/assets/34248806/e28f2003-9c34-4b62-9768-f0f5a39818b0">

**Comment by red-made** [comment]
Same problem:

main.d306032f.js:6293 TypeError: Cannot read properties of undefined (reading 'length')
    at qn (9667.bbb60d57.chunk.js:151:5146)
    at Er (main.d306032f.js:6291:20860)
    at md (main.d306032f.js:6293:46444)
    at kh (main.d306032f.js:6293:41968)
    at ef (main.d306032f.js:6293:41896)
    at dh (main.d306032f.js:6293:41746)
    at Gc (main.d306032f.js:6293:37910)
    at Qc (main.d306032f.js:6293:38747)
    at ql (main.d306032f.js:6291:3352)
    at main.d306032f.js:6293:36154
overrideMethod @ console.js:213
ld @ main.d306032f.js:6293
ve.callback @ main.d306032f.js:6293
Yu @ main.d306032f.js:6291
at @ main.d306032f.js:6293
Re @ main.d306032f.js:6293
Bd @ main.d306032f.js:6293
jf @ main.d306032f.js:6293
hh @ main.d306032f.js:6293
Qc @ main.d306032f.js:6293
ql @ main.d306032f.js:6291
(anonymous) @ main.d306032f.js:6293
Show 1 more frame
Show less

**Comment by rac-andreharry** [comment]
hey this is happening to me too, we're using v4.15.2

**Comment by EugeneDraitsev** [comment]
This PR should fix the issue: #18757

**Comment by bronkula** [comment]
v4.17.1 this is happening to me.

**Comment by Boegie19** [comment]
@bronkula Please open a new issue with replication staps for your issue
