### ISSUE TITLE
Custom editor components - expl.: ECharts

### ISSUE THREAD

**Issue by FinnFrotscher** [strapi/strapi#1863]
**What is the expected behavior?**
Is it possible to add custom components to the body of the content?

For example, we would like to add Charts from [ECharts](https://github.com/apache/incubator-echarts) to our Articles.
Our App is rendered by Gatsby.

**Comment by soupette** [comment]
@FinnFrotscher sorry for answering so late... I've been working on some other features for Strapi...

Did you figure it out? Because honestly, I'm not sure how to do it myself and I don't have the time to try...

***Maybe you can post your solution in this issue if you get it working?***

**Comment by FinnFrotscher** [comment]
I am currently on the fence about whether to use strapi as a backend or to build it from scratch. 
i will need a lot of flexibility, so maybe it would be better for me to use something like `nextjs` that provides me with the building blocks, rather than an integrated solution.
what do you think?

**Comment by FinnFrotscher** [comment]
if i do decide for strapi and figure it out, i will share the solution.
