### ISSUE TITLE
Strapi crashed on dashboard on datetime selected field

### ISSUE THREAD

**Issue by fiderosado** [strapi/strapi#18642]
Strapi crashed on dashboard on datetime selected field
STRAPI VERSION
v4.14.5

NODE VERSION
v18.16.1

![asda 2023-11-02 042714](https://github.com/strapi/strapi/assets/15683590/26843467-05e6-4080-abdf-28b958a460e4)
![dasdasdaaaa](https://github.com/strapi/strapi/assets/15683590/39dc8ad2-e210-443e-80d7-06b192bcc996)

**Comment by Boegie19** [comment]
@fiderosado Please update to the latest strapi version since it is fixed there and run `yarn build` or `npm run build`
