### ISSUE TITLE
Creating a new ressource with 'ref' as property break the ressource list

### ISSUE THREAD

**Issue by Asthonishia** [strapi/strapi#18643]
### Required System information

- Strapi Version: 4.14.5
- Operating System: docker container node:18.17.0-alpine
- Database: mysql Ver 14.14 Distrib 5.7.35
- NPM Version: multiple version with nvm
- Yarn Version: 3.6.1
- TS

### Describe the bug

Actually we can use the name 'ref' for ressource prop and it cause problem because this is a protected name in React for refs.
You can see my related post here : https://forum.strapi.io/t/woops-something-went-wrong-with-a-simple-ressource-list/33127

### Steps to reproduce the behavior

1. Create a simple ressource with the name you want
2. Add a property with 'ref' as name
3. Go to the ressource list and see the error

"Woops! Something went wrong..."

### Expected behavior

We can use any name we want without breaking anything.

**Comment by Boegie19** [comment]
closing this as there is a tracking issue for this. https://github.com/strapi/strapi/issues/16222
