### ISSUE TITLE
Collection's entry content validation is only triggered before attempting to publish 

### ISSUE THREAD

**Issue by CyberSteelX** [strapi/strapi#18644]
## Bug report

I've noticed this strange behaviour which involves the validation of the content of a Collection entry. Long story short, I see no validation triggered when I'm in Draft mode and as soon as I try to publish the entry all the validation logic is correctly triggered. Wouldn't it be correct to also validate the content in Draft mode?

### Required System information
- Node.js version: `v18.14.1`
- NPM version: `9.7.2`
- Strapi version: `v4.14.2`
- Database: `10.6.2-MariaDB-1:10.6.2+maria~focal`
- Operating system: macOS `14.0 (23A344)`
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Content validation is only triggered while attempting to publish a Collection's entry.

### Steps to reproduce the behavior

1. Create a new entry for a Collection
2. Insert info for the new entry
3. Leave out a required field (let's say a required "title" field)
4. You can successfully save the entity with the blank "title" field, unless you try to Publish the content

### Expected behavior

It would be more correct to allow validation in Draft mode as well (maybe through an environment variable that let's you decide whether you want or not validation for Draft mode editing).

**Comment by Boegie19** [comment]
@CyberSteelX I don't think so lets say you make a draft and you miss lets say half of the required fields are now empty since you did not get the information yet. if we validate on draft that means you can't have half done drafts with missing information.

**Comment by derrickmehaffy** [comment]
This is intended as you may not finish a draft while working on it, closing this as we won't change it. If you want validation active all the time, you'll need to disable D&P and filter out content being accepted in another way (such as route middlewares)
