### ISSUE TITLE
cannot use pg and cloudinary installation commands in version 4.15.1 

### ISSUE THREAD

**Issue by 7999999166** [strapi/strapi#18653]
i cannot use these installation commands in version 4.15.1
npm install pg --save
npm install @strapi/provider-upload-cloudinary --save

its showing error , please help

**Comment by cooperwfloyd** [comment]
@7999999166 please provide the error message that you're seeing. might be related to #18652

**Comment by 7999999166** [comment]
$ npm install pg --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @strapi/plugin-cloud@4.15.1
npm ERR! Found: styled-components@5.3.3
npm ERR! node_modules/styled-components
npm ERR!   peer styled-components@">= 2" from babel-plugin-styled-components@2.1.4
npm ERR!   node_modules/babel-plugin-styled-components
npm ERR!     babel-plugin-styled-components@">= 1.12.0" from styled-components@5.3.3
npm ERR!   styled-components@"5.3.3" from @strapi/admin@4.15.1
npm ERR!   node_modules/@strapi/admin
npm ERR!     @strapi/admin@"4.15.1" from @strapi/strapi@4.15.1
npm ERR!     node_modules/@strapi/strapi
npm ERR!       peer @strapi/strapi@"^4.3.4" from @strapi/admin@4.15.1
npm ERR!       3 more (@strapi/data-transfer, @strapi/plugin-cloud, the root project)
npm ERR!   8 more (@strapi/design-system, @strapi/helper-plugin, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.3.6" from @strapi/plugin-cloud@4.15.1
npm ERR! node_modules/@strapi/plugin-cloud
npm ERR!   @strapi/plugin-cloud@"4.15.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: styled-components@5.3.11
npm ERR! node_modules/styled-components
npm ERR!   peer styled-components@"^5.3.6" from @strapi/plugin-cloud@4.15.1
npm ERR!   node_modules/@strapi/plugin-cloud
npm ERR!     @strapi/plugin-cloud@"4.15.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\acrot\AppData\Local\npm-cache\_logs\2023-11-02T19_07_38_845Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\acrot\AppData\Local\npm-cache\_logs\2023-11-02T19_07_38_845Z-debug-0.log

**Comment by 7999999166** [comment]
npm install @strapi/provider-upload-cloudinary --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @strapi/plugin-cloud@4.15.1
npm ERR! Found: styled-components@5.3.3
npm ERR! node_modules/styled-components
npm ERR!   peer styled-components@">= 2" from babel-plugin-styled-components@2.1.4
npm ERR!   node_modules/babel-plugin-styled-components
npm ERR!     babel-plugin-styled-components@">= 1.12.0" from styled-components@5.3.3
npm ERR!   styled-components@"5.3.3" from @strapi/admin@4.15.1
npm ERR!   node_modules/@strapi/admin
npm ERR!     @strapi/admin@"4.15.1" from @strapi/strapi@4.15.1
npm ERR!     node_modules/@strapi/strapi
npm ERR!       peer @strapi/strapi@"^4.3.4" from @strapi/admin@4.15.1
npm ERR!       3 more (@strapi/data-transfer, @strapi/plugin-cloud, the root project)
npm ERR!   8 more (@strapi/design-system, @strapi/helper-plugin, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer styled-components@"^5.3.6" from @strapi/plugin-cloud@4.15.1
npm ERR! node_modules/@strapi/plugin-cloud
npm ERR!   @strapi/plugin-cloud@"4.15.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: styled-components@5.3.11
npm ERR! node_modules/styled-components
npm ERR!   peer styled-components@"^5.3.6" from @strapi/plugin-cloud@4.15.1
npm ERR!   node_modules/@strapi/plugin-cloud
npm ERR!     @strapi/plugin-cloud@"4.15.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\acrot\AppData\Local\npm-cache\_logs\2023-11-02T19_08_44_129Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\acrot\AppData\Local\npm-cache\_logs\2023-11-02T19_08_44_129Z-debug-0.log
