### ISSUE TITLE
Plugin directory creation fails after running `strapi new app_name` with Yarn

### ISSUE THREAD

**Issue by qubbit** [strapi/strapi#1866]
**Informations**
- **Node.js version**: v10.9.0
- **npm version**:  - (yarn was used, more to come here)
- **Strapi version**: 3.0.0 alpha
- **Database**: Postgres
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

Plugin directory creation fails while running `strapi new app_name`. App can still be run even when the installation succeed while failing plugin installation steps, the plugins cannot be installed from the market place.

**Steps to reproduce the problem**

Install strapi using `yarn global add strapi@alpha` and then `strapi new app_name` and follow the on-screen instructions

**What is the expected behavior?**

Should succeed in creating the plugins directory and install the standard set of plugins

**Suggested solutions**

The `pluginPath` variable needs to be set correctly if the app is not installed using npm.

https://github.com/strapi/strapi/blob/f5eae7d4c226017e8a5d975a907ada04360cd7fe/packages/strapi/bin/strapi-install.js#L61-L67

**Comment by lauriejim** [comment]
Hello @qubbit can you precise the strapi version please.
There is many alpha version https://github.com/strapi/strapi/tags

**Comment by lauriejim** [comment]
I suggest you to use **npm** instead of **Yarn**
Yarn is not well supported by Strapi. We have done some work on, but nor a priority for now.

**Comment by qubbit** [comment]
@lauriejim Oddly enough it worked on a macos. The problem was on a Linux machine (Ubuntu 18.04). I will close this for now. Thanks!
