### ISSUE TITLE
4.15.1 npm run build requires console interaction on every build

### ISSUE THREAD

**Issue by broksonic21** [strapi/strapi#18666]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 4.15.1
Node/Yarn Version: npm/10.2.2 node/v20.9.0 darwin arm64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

We use dependabot to create upgrade PRs automatically. Normally, they just run our tests and are pretty clean.

With 4.15.1's admin build refactoring https://github.com/strapi/strapi/pull/18539, it now asks for

```
[INFO] The Strapi admin needs to install the following dependencies:
   - react@^18.0.0
  - react-dom@^18.0.0
  - react-router-dom@^5.0.0
  - styled-components@^5.0.0
? Would you like to install these dependencies now? These are not required but are recommended, from V5 these will be
required. (Y/n)
```

when you run `npm run build`. 

As an optional addition, this shouldn't block builds or require a TTY/console to answer - there should at minimum be a cli flag or config setting we can use to skip past this if we aren't prepared (yet) to add these optional dependencies

In addition, this isn't called out as a breaking change in release notes ( https://github.com/strapi/strapi/releases/tag/v4.15.1 ) nor in migration guides ( https://docs.strapi.io/dev-docs/migration-guides ) even those it's a required breaking change for every environment as you _have_ to interact with it on _every build_. Saying no doesn't persist - so you get asked on every build

### Steps to reproduce the behavior

1. Upgrade to 4.15.1
2. Run `npm install`
3. Run `npm run build` in a CI environment

### Expected behavior

Optional upgrades shouldn't require TTY interaction to avoid CI issues - have a config or cli to skip this check while it's still optional

### Screenshots

<img width="836" alt="image" src="https://github.com/strapi/strapi/assets/24306571/c98a815a-92a1-403f-8dc0-75f368d7dcb8">

**Comment by joshuaellis** [comment]
Thanks for the report! It'd be great to understand a bit more the issue you're facing – you're running `yarn build` – is it not right to assume you'd be building production mode of `strapi`?

**Comment by broksonic21** [comment]
our production runs production mode, but our CI runs development (it builds to confirm it can, well, build still!)

**Comment by broksonic21** [comment]
but also, every dev runs in dev mode too - so if I say no locally, I don't want to have to answer every time after (nor have other devs have to answer no)

**Comment by gilzow** [comment]
+1 on this issue.
Just spent the last two hours trying to figure out what was breaking our CI/CD processes with a strapi project. Is there a way to bypass the user prompt, set it up for no user interactions, and/or automatically select `n` ???

**Comment by gilzow** [comment]
also, why was this change added in what should be a minor version update?

**Comment by joshuaellis** [comment]
> our production runs production mode, but our CI runs development

Okay, well it sounds like the solution is a CLI flag that could say "no" to prompts etc. I would encourage you to install those dependencies though, they will be required from V5 😃
