### ISSUE TITLE
UnauthorizedError and ForbiddenError don't return error's message and details data

### ISSUE THREAD

**Issue by wusuopu** [strapi/strapi#18672]
### Required System information

- Node.js version: v18.15.0
- Yarn version: v1.22.19
- Strapi version: v4.14.5
- Database: sqlite3
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

it don't return error's message and details data of UnauthorizedError and ForbiddenError .

### Steps to reproduce the behavior

1. run `throw new UnauthorizedError('detail message', 'detail info')` or `throw new ForbiddenError('detail message', 'detail info')`
2. the response data in client is like this: `{"data":null,"error":{"status":401,"name":"UnauthorizedError","message":"Unauthorized","details":{}}}` or `{"data":null,"error":{"status":403,"name":"ForbiddenError","message":"Forbidden","details":{}}}` . it don't contain `message` and `details`.

**Comment by derrickmehaffy** [comment]
Those 2nd parameters need to be objects not strings.
