### ISSUE TITLE
pinned versions in peerDeps

### ISSUE THREAD

**Issue by y-nk** [strapi/strapi#18681]
### Describe the bug

The `@strapi/plugin-i18n` has styled-components peer dep at `5.3.3` (pinned version) which is a pain when authoring a plugin because the plugin generator creates a package.json with `"styled-components": "^5.3.6"` - when publishing the plugin it cannot be installed because there's a dep conflict.

### Expected behavior

The DX should be nicer, as in, we should not fix package.json versions manually

### Additional context

I understand deps and especially peer deps is a pain.

**Comment by derrickmehaffy** [comment]
We moved to pinned intentionally to prevent issues with certain users. Yes it's not as nice to maintain but was necessary for now.

Will close this out as I don't believe it's something we plan to change anytime soon.

**Comment by y-nk** [comment]
@derrickmehaffy maybe a fix could be to either set the generated template to `^5.3.3` so that it doesn't break with the i18n plugin, or upgrade the i18n plugin to `5.3.6`?
