### ISSUE TITLE
Strapi cannot connect to mlab when used by second admin on second computer

### ISSUE THREAD

**Issue by oznekenzo** [strapi/strapi#1869]
node v8.11.1
strapi 3.0.0-alpha.14
npm 6.1.0
mlab
macOS 10.13.6

**What is the current behavior?**
Strapi boots after strapi start works as expected on my computer.
When my partner boots strapi after strapi start, his dashboard cannot access data from mlab from new content types, but *can* access data from the default "Users" content type.

If my partner creates a new content type on his computer from his strapi dashboard, I am not able to access that data.

**Steps to reproduce the problem**
Create new strapi project and connect to [Database1].
Create new content type in dashboard.
Now, on second computer with second user, connect new strapi project to [Database1].
Go to new content type created in previous computer / account.

**What is the expected behavior?**
Computer #2 / Admin #2 should be able to retrieve data from [Database1] created by Computer #1 / Admin #1

Instead, we are getting an error message "An error occured" in the interface, and "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" in the console.

**Comment by derrickmehaffy** [comment]
@oznekenzo enable debug mode in your database.json file to see more detailed errors.

If I had to guess however, this is likely a limit of mlab and not one with strapi, or your database is not configured correctly to handle multiple connections.

**Comment by lauriejim** [comment]
@oznekenzo any new about this issue ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
