### ISSUE TITLE
Getting error and unable to connect to strapi studio

### ISSUE THREAD

**Issue by Jatinbalodhi96** [strapi/strapi#187]
**Node.js 6.9.1**:
**npm 4.2.0**:
**Strapi 1.5.4**:
**ubuntu 16.04 LTS**:

I am unable to connect to studio strapi and getting error while starting local server i followed all steps
![err](https://cloud.githubusercontent.com/assets/10434201/22949767/5acfe478-f329-11e6-9bbd-1c34c6b9f919.png)

**Comment by pierreburgy** [comment]
Hi @Jatinbalodhi96, Strapi v1.x is compatible only with Node 4. But, of course, Strapi v3 will be compatible to the latest Node versions.

**Comment by pierreburgy** [comment]
@Jatinbalodhi96 Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
