### ISSUE TITLE
Can't build Admin due to @strapi/plugin-i18n v4.15.2

### ISSUE THREAD

**Issue by esiao** [strapi/strapi#18711]
## Bug report

Installing Strapi v4.15.2 doesn't allow me to build the Admin Panel anymore.
```
⠋ Creating admin[ERROR] Module not found: Error: Package path ./admin/src/hooks/useContentTypePermissions is not exported from package /Users/esiao/Sites/skin-office-backend/node_modules/@strapi/plugin-i18n (see exports field in /Users/esiao/Sites/skin-office-backend/node_modules/@strapi/plugin-i18n/package.json)
```

### Required System information

Environment: development
OS: darwin-x64
Strapi Version: 4.15.2
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.17.0 darwin x64
Edition: Community
Database: postgres
Typescript Project

### Describe the bug

I tried installing the latest version of Strapi but can't build my Admin panel.

### Steps to reproduce the behavior

Install latest "@strapi/strapi" and "@strapi/plugin-i18n"

### Expected behavior

I should be able to build my Admin Panel.

**Comment by JonnyBro** [comment]
I also have this error while building production (node v18, npm 9.5.0, yarn v1.22):
```
⠦ Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/hooks/useLocales is not exported from package /home/USER/my-project/node_modules/@strapi/plugin-i18n (see exports field in /home/USER/my-project/node_modules/@strapi/plugin-i18n/package.json)
```

**Comment by joshuaellis** [comment]
@esiao, can you please write a detailed description? there's a lot of context missing so unfortunately for now, I can't reproduce this.

**Comment by RemcoLankhorst** [comment]
Same issue here. Upgrading from 4.15 to 4.15.2. If I go back to version 4.15 I get the same issue. Went back to 4.14.6.
Suggestion above to try a new install is useless as we are trying to update an existing version.

**Comment by Kapcash** [comment]
Hello,
I also reproduce this bug after upgrading to v4.15.2.

> $ strapi build
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
    - STRAPI_ADMIN_BRANCH_NAME
✔ Building build context (52.40758275985718ms)
⠋ Building admin panel
⠏ Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/hooks/usePluginsQueryParams is not exported from package /Users/myuser/projects/verychic/verychic-strapi/node_modules/@strapi/admin (see exports field in /Users/myuser/projects/verychic/verychic-strapi/node_modules/@strapi/admin/package.json)
✖ Building admin panel

**Using the version v4.15.0 works fine.**

I'll try to work on a reproduction repo this weekend.

**Comment by esiao** [comment]
I cleaned up node_modules and yarn.lock

@joshuaellis following are my project's dependencies

```
  "dependencies": {
    "@ckeditor/strapi-plugin-ckeditor": "^0.0.7",
    "@strapi/plugin-color-picker": "^4.15.2",
    "@strapi/plugin-i18n": "4.15.2",
    "@strapi/plugin-seo": "^1.9.2",
    "@strapi/plugin-users-permissions": "4.15.2",
    "@strapi/strapi": "4.15.2",
    "pg": "8.8.0",
    "pg-connection-string": "^2.5.0",
    "react-dom": "^18.2.0",
    "strapi-plugin-menus": "^1.4.3",
    "strapi-plugin-preview-button": "^2.0.0",
    "strapi-plugin-publisher": "^1.4.1",
    "strapi-plugin-rest-cache": "^4.2.8",
    "strapi-plugin-translate": "^1.2.3",
    "strapi-provider-translate-deepl": "^1.1.11",
    "strapi-provider-upload-dos": "^4.0.5"
  },
```

When I run the dev or build command I get this message
```
[INFO] The Strapi admin needs to install the following dependencies: 
   - react@^18.0.0
  - react-router-dom@^5.2.0
  - styled-components@^5.2.1
```
Press Y

I then get this error
```
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (349.24456787109375ms)
⠹ Creating admin[ERROR] Module not found: Error: Package path ./admin/src/selectors/selectI18nLocales is not exported from package /Users/aureliendias/Sites/skin-office-backend/node_modules/@strapi/plugin-i18n (see exports field in /Users/aureliendias/Sites/skin-office-backend/node_modules/@strapi/plugin-i18n/package.json)
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

[ERROR] Command failed with exit code 1: /Users/aureliendias/.nvm/versions/node/v18.17.0/bin/node /Users/aureliendias/Sites/skin-office-backend/node_modules/.bin/strapi develop
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I downgrade `@strapi/plugin-i18n` and `@strapi/strapi` to v4.14.6 it builds.

In my ENV file I have the following variables. (removed the sensitive values)
```
HOST=0.0.0.0
PORT=1337
APP_KEYS=
API_TOKEN_SALT=
ADMIN_JWT_SECRET=

DATABASE_PORT=
DATABASE_NAME=
DATABASE_USERNAME=
DATABASE_PASSWORD=
JWT_SECRET=

MAILCHIMP_API_KEY=
MAILCHIMP_SERVER_PREFIX=
MAILCHIMP_LIST_ID=

WEBSITE_URL=

DEEPL_API_KEY=
DEEPL_API_URL=
```

Let me know what other information I can provide.

**Comment by thenglong** [comment]
For me it was because of some third party plugins that still use old strapi imports

**Comment by joshuaellis** [comment]
@esiao, does this still happen when you uninstall your third part plugins?

**Comment by bitmonti** [comment]
Can't use "strapi-plugin-translate" anymore!

You are right, uninstalling and remove its plugin.config removed the error and let me build admin panel. But reinstalling once admin panel is build, throws back the error. Unfortunately...

That said, it depends on a plugin update, right?

**Comment by joshuaellis** [comment]
> Can't use "strapi-plugin-translate" anymore!
> 
> You are right, uninstalling and remove its plugin.config let the error disappear and let me build admin panel. But reinstalling once admin panel is build, throws back the error. Unfortunately...
> 
> That said, it depends on a plugin update, right?

I think it might, plugins were incorrectly using direct imports from our packages – this was never something we explicitly supported for numerous reasons, I would therefore encourage plugin developers to address these direct imports.

**Comment by DarrylWalkerJacobs** [comment]
> Hello, I also reproduce this bug after upgrading to v4.15.2.
> 
> > $ strapi build
> > ⠋ Building build context
> > [INFO] Including the following ENV variables as part of the JS bundle:
> > - ADMIN_PATH
> > - STRAPI_ADMIN_BACKEND_URL
> > - STRAPI_TELEMETRY_DISABLED
> > - STRAPI_ADMIN_BRANCH_NAME
> > ✔ Building build context (52.40758275985718ms)
> > ⠋ Building admin panel
> > ⠏ Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/hooks/usePluginsQueryParams is not exported from package /Users/myuser/projects/my-strapi/node_modules/@strapi/admin (see exports field in /Users/myuser/projects/my-strapi/node_modules/@strapi/admin/package.json)
> > ✖ Building admin panel
> 
> **Using the version v4.15.0 works fine.**
> 
> I'll try to work on a reproduction repo this weekend.

Confirming I get this exact issue when upgrading strapi from v4.15.0 to v4.15.4. The error is in @strapi/admin which needs to be addressed urgently, as there are admin UI bugs in v4.15.0 that need fixed ASAP. Parts of the content type builder are unusable on v4.15.0.

**Comment by SVronskiy** [comment]
Have the same issue when upgrade strapi 4.15.0 to v4.15.1, v4.15.2, v4.15.3 or v4.15.4.

**Comment by muammerkeles** [comment]
Plugins cannot found after upgrading Strapi to 4.15 and above.
Maybe 4 hours I tried to find bug in the plugin. Till i saw the comments here.
Then i reverted strapi version as before, so plugins started working properly.
---------------

Also just an info for strapi team
.strapi/client/app.js was creating plugin path incorrect like this "....srcplugins/"

**Comment by joshuaellis** [comment]
This issue unfortunately exists with external packages trying to utilise our sourcecode which is something we do not support, as such there is no action we can take here. I would recommend deducing which plugin is causing the issue and write a report on their repo.

**Comment by CTOlet** [comment]
I've just installed that packages and it works 👍

STRAPI VERSION
v4.15.4

**Comment by niklissad** [comment]
Hello. I'm still got this error on clean installation after `npx create-strapi-app@latest cms`

I got an arror

```
npm run build

> cms@0.1.0 build
> strapi build

[WARN] [@strapi/strapi]: The NODE_ENV is not set to production. This may result in unexpected behavior.
✔ Compiling TS (994ms)
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (260ms)
⠋ Building admin panel
✔ Building admin panel (8123ms)

Process finished with exit code 0
```

in my package.json:
```
"dependencies": {
    "@strapi/strapi": "4.18.0",
    "@strapi/plugin-users-permissions": "4.18.0",
    "@strapi/plugin-i18n": "4.18.0",
    "@strapi/plugin-cloud": "4.18.0",
    "mysql": "2.18.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
  ```

**Comment by ingmanuelcaicedo** [comment]
> I faced this issue as well. Updating to `strapi-plugin-translate@1.2.4` with all of my `@strapi/*` at `4.15.5` worked for me.

I have the same problem, but I would like to update my Strapi version from 4.14.5 to 4.20.1, but I get  this error: 

```
npm run build

> example--strapi@0.5.000 build
> strapi build

[WARN] [@strapi/strapi]: The NODE_ENV is not set to production. This may result in unexpected behavior.
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (195ms)
⠋ Building admin panel
⠧ Building admin panel[ERROR] Module not found: Error: Can't resolve '@strapi/plugin-graphql/strapi-admin' in 'D:\Development\strapi\example\.strapi\client'
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information
```
Does someone have the same issue?

**Comment by derrickmehaffy** [comment]
It's trying to import a react component we don't export

**Comment by netzpixel** [comment]
> > I faced this issue as well. Updating to `strapi-plugin-translate@1.2.4` with all of my `@strapi/*` at `4.15.5` worked for me.
> 
> I have the same problem, but I would like to update my Strapi version from 4.14.5 to 4.20.1, but I get this error:
> 
> ```
> npm run build
> 
> > example--strapi@0.5.000 build
> > strapi build
> 
> [WARN] [@strapi/strapi]: The NODE_ENV is not set to production. This may result in unexpected behavior.
> ⠋ Building build context
> ⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
>     - ADMIN_PATH
>     - STRAPI_ADMIN_BACKEND_URL
>     - STRAPI_TELEMETRY_DISABLED
> ✔ Building build context (195ms)
> ⠋ Building admin panel
> ⠧ Building admin panel[ERROR] Module not found: Error: Can't resolve '@strapi/plugin-graphql/strapi-admin' in 'D:\Development\strapi\example\.strapi\client'
> ✖ Building admin panel
> [ERROR]  There seems to be an unexpected error, try again with --debug for more information
> ```
> 
> Does someone have the same issue?

Yes, same here with 4.20.4.

**Comment by gregg-cbs** [comment]
I have just started seeing this on 4.20.4 . I recently installed a node package "strapi-plugin-schemas-to-ts" and this started happening. I have since removed it but i am still seeing the error now. Even after node_modules reinstall.

**Comment by gregg-cbs** [comment]
Also getting npm warnings when installing:
![image](https://github.com/strapi/strapi/assets/57114335/5afacdc5-7b17-4416-9a94-f88dcbf97f01)

**Comment by Judechuks** [comment]
Building build context (260ms)
⠼ Creating admin[ERROR] assets by status 8.53 MiB [cached] 208 assets
Entrypoint main = runtime~main.ceb42b97.js main.86fcab5f.js
orphan modules 3.88 MiB [orphan] 1551 modules
runtime modules 12.2 KiB 16 modules
cacheable modules 12.7 MiB
  modules by path ./node_modules/ 12.7 MiB
    javascript modules 12.6 MiB 1397 modules
    json modules 62.4 KiB
      ./node_modules/markdown-it-emoji/lib/data/full.json 34 KiB [built] [code generated]
      ./node_modules/markdown-it/node_modules/entities/lib/maps/entities.json 28.4 KiB [built] [code generated] 
  + 8 modules

ERROR in ./node_modules/date-fns/esm/startOfISOWeekYear/index.js
Module build failed (from ./node_modules/esbuild-loader/dist/index.js):
Error: Transform failed with 1 error:
C:\...obaji_strapi\node_modules\date-fns\esm\startOfISOWeekYear\index.js:29:31: ERROR: Expected ")" but found end of file
    at failureErrorWithLog (C:\...obaji_strapi\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:1604:15)
    at C:\...obaji_strapi\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:837:29
    at responseCallbacks.<computed> (C:\...obaji_strapi\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:701:9)
    at handleIncomingPacket (C:\...obaji_strapi\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:756:9)
    at Socket.readFromStdout (C:\...obaji_strapi\node_modules\esbuild-loader\node_modules\esbuild\lib\main.js:677:7)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
 @ ./node_modules/date-fns/esm/index.js 213:0-78 213:0-78
 @ ./node_modules/@strapi/plugin-upload/dist/admin/index.mjs 10:0-18
 @ ./node_modules/@strapi/strapi/dist/admin.mjs 4:0-56 13:6-12
 @ ./.strapi/client/app.js 4:0-51 5:0-11

webpack 5.91.0 compiled with 1 error in 31701 ms
[ERROR]  There seems to be an unexpected error, try again with --debug for more information
