### ISSUE TITLE
Disable certain plugins

### ISSUE THREAD

**Issue by hansemannn** [strapi/strapi#1871]
**What is the expected behavior?**

Is it possible to disable certain plugins? I noticed they are inside the plugins/ directory, but deleting them feels weird, so I am looking for a configuration file that manages those. Is that existing already? Great project btw!

**EDIT**: There is the `admin/admin/src/config/plugins.json` file, but it seems to be regenerated on every `strapi start`.

**Comment by derrickmehaffy** [comment]
@hansemannn the default "plugins" are pretty bare basic and there are depends that might break strapi core. What plugins are you looking to disable?

**Comment by hansemannn** [comment]
I am thinking of a way to hand over a dashboard to a customer. If they want to use it to manage basic content received via the API, they should not be able to see anything else than the content types and their data.

**Comment by derrickmehaffy** [comment]
@hansemannn I would look into "Admin-On-Rest" there is already someone working on a connector for it, but this is more geared towards your usecase: https://github.com/marmelab/admin-on-rest

The Strapi dashboard can be "de-coupled" from the actual API server but the API server can really only reference one dashboard and if you disabled the plugins on it, then the server also would not have them.

The dashboard/AdminUI right now isn't designed for "customer" use, and that will come later with a more refined roles option that hasn't been developed yet: https://strapi.io/marketplace/administrators-roles

**Comment by hansemannn** [comment]
For now, I found a configuration in the React code that I can simply use to hide the left-bar widgets on production. Do you prefer keeping this one open for keeping track of it? I'm fine either way! Thanks again!

**Comment by derrickmehaffy** [comment]
@hansemannn just a heads up that while in production those entries are hidden they can still be accessed and used by direct URL. 

I don't think there is anything in the plan to allow for this type of use-case as it would require a major rewrite of how Strapi works. The AdminUI itself does not communicate to the server like a standard CRUD page would, and it uses the internal strapi API to modify data and such.

I could be wrong in this assumption, as I am not a member of the Strapi team, but as I have been following development for some time I do feel it is highly unlikely unless someone in the community wanted to take this on.

**Comment by derrickmehaffy** [comment]
This is a very "niche" case so to speak.

**Comment by hansemannn** [comment]
Ok 😗

**Comment by igghera** [comment]
> For now, I found a configuration in the React code that I can simply use to hide the left-bar widgets on production. Do you prefer keeping this one open for keeping track of it? I'm fine either way! Thanks again!

@hansemannn I'm looking for the same thing. Any chance you could point me in the right direction?

**Comment by emahuni** [comment]
My use-case kinda makes sense in this way. When I run tests, I don't need to run the documentation plugin, for instance, but I need it in development when I run `Strapi develop`. The point here is to make tests run faster by disabling certain custom or even irrelevant Strapi plugins during tests. I hoped that plugins would be disabled as easily as hooks are, as per-environment configuration.

**Comment by emahuni** [comment]
I think it'd make Strapi more consistent across its API. I should be able to disable a plugin should the need arise, regardless of being expected or not. The developer should be the judge, whether it's important or not to keep a plugin enabled. This makes it more flexible. Another case for instance is when I run migrations, that depend on Strapi core, and family of plugins, but not any other plugin or hook. For instance, I need Strapi to create the DB and its schema for me only, then I seed the DB using knex. The config for this env is supposed to be lean and shouldn't do anything else coz it can mess things up. EG: I don't want it to run certain plugin lifecycle hooks when I insert certain data during seeding. So a way to just disable certain plugins when run using this environment is something that is lacking.

**Comment by emahuni** [comment]
I hope you understand and see that the use-cases for this are unlimited. This always crops up and I have to make hacks to make it work, like 🙈  renaming the node_modules plugins that I need to disable during tests or migrations. 😫. I know right? But that's one of the only ways I can think of that this can be easily done. Or reading plugins config and then proxy require modules of plugins that are disabled in current env plugin.js.

**Comment by emahuni** [comment]
Another way is to remove a plugin entry in package.json. By the way, you will have to restore these renames or removals after quitting the app. So it's like this: 

`backup package.json -> remove package.json entries of plugins we don't want -> start Strapi -> do your doings -> end Strapi -> restore original package.json`

Yes, all that trouble just to disable plugins we don't want to load for a particular environment or reason. EG: I may not even want the documentation plugin to run in production, at all, but need it during development.
