### ISSUE TITLE
Strapi Rest Cache Plugin Is Not Working 

### ISSUE THREAD

**Issue by ST-Wasi** [strapi/strapi#18714]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.6.6
- Strapi version: 4.15.0
- Database: postgres
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I was implementing the Rest API's in the my Strapi Application but i was not satisfied with the time it taking to fetch the Database and I hosted the database RDS in amazon and the Strapi too in the same region so there is no issue related to the region it hosted but when i am trying to get it in local it also takes a lil bit more time like 2 sec for a simple images and all. So I Find in Strapi forum to use the Rest Cache Plugin But I Followed full documentation but the plugin did not start. I don't know why it is not getting started. Can anyone pls look into this matter.

### Steps to reproduce the behavior

1. Go to https://strapi.io/blog/caching-in-strapi-with-rest-cache-plugin
2. Follow The Documentation
3. It Shows This In Conssole 

![image](https://github.com/strapi/strapi/assets/144717974/389537c1-d07d-4ad2-a2ed-9ad7e02a1e14)

4. Plugin.TS code

`"rest-cache": {
    config: {
      provider: {
        name: "memory",
        options: {
          max: 32767,
          maxAge: 3,
          updateAgeOnGet: false,
        },
      },
      strategy: {
        debug: true,
        maxAge: 3600,
        updateAgeOnGet: false,
        contentTypes: [
          // list of Content-Types UID to cache
          { contentType: "api::popular-course.popular-course", maxAge: 60*60*100 },
        ],
      },
    },
  },`

**Comment by Boegie19** [comment]
Please open this issue on the rest-cache repo and not the strapi one.
