### ISSUE TITLE
"Couldn't find AWS credentials." when using EC2 Instance Profile

### ISSUE THREAD

**Issue by denisgoryaynov** [strapi/strapi#18718]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.2.3
- Strapi version: 4.15.2
- Database: PostgreSQL 16.0
- Operating system: macOS 13.6.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After updating to strapi 4.15.2 the provider @strapi/provider-upload-aws-s3 keeps throwing the error "Couldn't find AWS credentials" on our production server. Since we are using EC2 we don't pass the accessKeyId and secretAccessKey to the configuration and instead let the sdk use the EC2 Instance Profile.

We had no errors with strapi 4.15.0

### Steps to reproduce the behavior

1. Create a new project
2. Setup @strapi/provider-upload-aws-s3 without accessKeyId and secretAccessKey
3. The server won't start and will throw "Couldn't find AWS credentials"

**Comment by derrickmehaffy** [comment]
Nothing changed in this provider for the latest version, I don't believe this is a bug from us.

**Comment by limpep** [comment]
Having the same issue running in an ECS cluster, without providing the  accessKeyId and secretAccessKey or baseUrl as it is not need, seems like the plugin expects these values instead it should be optional

**Comment by denisgoryaynov** [comment]
Hi @derrickmehaffy , I created a simple project with a reproduction: https://github.com/denisgoryaynov/strapi-s3-provider-error

Branch main has the latest strapi version (4.15.2) and is affected by the issue, while branch 4.15.0 runs without problems.
The only difference between those branches is the strapi version.

To reproduce the issue it should be enough to clone the repo, install dependencies and then execute `npm run develop`.

I also did some digging to help debugging and I think that the issue is caused by the function extractCredentials at line 92 of upload-aws-s3/src/utils.ts:
https://github.com/strapi/strapi/blob/d999ad0b00ff427885462051cdc96626b7946472/packages/providers/upload-aws-s3/src/utils.ts#L92C12-L92C12

This function is not present on version 4.15.0:
https://github.com/strapi/strapi/blob/6e44e1e68db5153e485e61bdc03f42efb0311406/packages/providers/upload-aws-s3/src/utils.ts

This is the commit on which it was added, so somewhere between 4.15.0 and 4.15.2: https://github.com/strapi/strapi/commit/02973d45cb703d682fe23dde96c66f256ce31220

The comments inside the file indicate that the function extractCredentials was added to check between the legacy provider configuration and the strapi v5 configuration, but it doesn't seem to account for the fact that credentials can be omitted when strapi is deployed on and EC2 instance or on another AWS service that supports IAM Profiles instead of accessKeyId and secretAccessKey.

**Comment by innerdvations** [comment]
@derrickmehaffy There was actually a change to the S3 credentials handling when we replaced the deprecated S3 package. DX can take this one and will fix it asap.

**Comment by christiancp100** [comment]
@denisgoryaynov I've created an experimental for you to test in your project and see if the fix in [this PR](https://github.com/strapi/strapi/pull/18733) works: 0.0.0-experimental.e8b0ff5fe299b24567f51c4c8f17f5aa8bc9fb15.
Let me know when you have more information to merge the PR ASAP.

**Comment by denisgoryaynov** [comment]
Hi @christiancp100 , I just tried the experimental version. The server now starts correctly but when I tried to upload a test file I got the following error:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Resolved credential object is not valid
    at SignatureV4.validateResolvedCredentials (/home/ubuntu/lagostina-cms/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:182:19)
    at SignatureV4.signRequest (/home/ubuntu/lagostina-cms/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:107:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jpouvrard** [comment]
For information, I have the same problem when I upgrade Strapi from 4.15.0 to 4.15.2 (I didn't change anything, just upgrade Strapi).
I've got this error : `Error: Couldn't find AWS credentials.`
Here is my plugin configuration:
```
      provider: "aws-s3",
      providerOptions: {
        s3Options: {
          accessKeyId: env("AWS_ACCESS_KEY_ID"),
          secretAccessKey: env("AWS_ACCESS_SECRET"),
          endpoint: env("AWS_S3_ENDPOINT_URL"),
          params: {
            Bucket: env("AWS_STORAGE_BUCKET_NAME"),
          },
          s3ForcePathStyle: true,
        },
      },
```

**Comment by christiancp100** [comment]
> Hi @christiancp100 , I just tried the experimental version. The server now starts correctly but when I tried to upload a test file I got the following error:
> 
> ```
> You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
> Error: Resolved credential object is not valid
>     at SignatureV4.validateResolvedCredentials (/home/ubuntu/strapi-app/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:182:19)
>     at SignatureV4.signRequest (/home/ubuntu/strapi-app/node_modules/@smithy/signature-v4/dist-cjs/SignatureV4.js:107:14)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

@denisgoryaynov Can you try again with this experimental? I think now that we removed the credentials object you shouldn't have any problem. I tried it in an AWS instance with IAM profile with access to S3 and it works on my side without passing the AWS credentials.

**Comment by denisgoryaynov** [comment]
Hi @christiancp100, I can confirm that experimental 0.0.0-experimental.e52ced96a510dcff85d35ad0cf7ac04f15ee2484 works as expected!

**Comment by karan-kissht** [comment]
Hi @christiancp100 & @denisgoryaynov, will this be fixed in the next release as we are also stuck on the same issue?
