### ISSUE TITLE
Broken peer dependencies for @strapi/plugin-users-permissions@4.15.2

### ISSUE THREAD

**Issue by alanraison** [strapi/strapi#18717]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.15.2
- Database: n/a
- Operating system: Linux (node:18 container)
- Is your project Javascript or Typescript: TS

### Describe the bug

NPM install fails when `@strapi/plugin-users-permissions@4.15.2` is a dependency;

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: @strapi/strapi@4.15.2
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"4.15.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@4.15.2
npm ERR! node_modules/@strapi/plugin-users-permissions
npm ERR!   @strapi/plugin-users-permissions@"4.15.2" from the root project
npm ERR! 
```

### Steps to reproduce the behavior

1. Create a strapi project with version 4.15.2
2. Install the `users-permissions` plugin; `npm install --save @strapi/plugin-users-permissions@4.15.2`
3. See error

### Expected behavior

`@strapi/plugin-users-permissions` is correctly installed, with no errors.

**Comment by alanraison** [comment]
Appears to cause #18706

**Comment by kevinblanco** [comment]
@joshuaellis I'd love the severity of the issue to be higher, all our automated scripts and deployment in production workloads are failing because of this, and It's hard to rebuild our images to add that flag when installing the dependencies, I will downgrade the strapi version to avoid this, but I do think the severity is higher for your audience and existing customers.

**Comment by LucaNerlich** [comment]
We are still facing this issue, even on 4.15.5-alpha.6.
The problematic library is `@strapi/plugin-users-permissions` now.
