### ISSUE TITLE
Auth Local Sign In failed

### ISSUE THREAD

**Issue by OsborneWafer** [strapi/strapi#18728]
Hello everyone, 
                           I am facing issue with the /auth/local/signin api. Everytime I attempt it the api call returns error code 401. Check the image attached below. Anyone else facing this issue. Please help me out here.

Thanks,
Osborne D'Silva

![newImg](https://github.com/strapi/strapi/assets/112384491/15a21a4b-2aea-4aeb-abd0-7651dea01cd8)

**Comment by sjoukedv** [comment]
Did you grant permissions to the public role to be able to call this endpoint? http://localhost:1337/admin/settings/users-permissions/roles > public > Users-permissions > check `callback`
