### ISSUE TITLE
Types are not generated when create a new collection type

### ISSUE THREAD

**Issue by dsolay** [strapi/strapi#18738]
### Required System information

- Node.js version: `20.9.0`
- NPM version: `10.1.0`
- Strapi version: `4.15.2`
- Database: `Postgres 15`
- Operating system: `ArchLinux x64, Kernel 6.4.12-arch1-1`
- Is your project Javascript or Typescript: `Typescript`

### Describe the bug

When creating a new collection type, adding some fields, and then saving, the Strapi server stops due to TypeScript errors, specifically: `Argument of type '"uid"' is not assignable to parameter of type 'ContentType.'` After manually executing `yarn strapi ts:generate-types`, it works as expected.

### Steps to reproduce the behavior

1. Create new collection type and add some fields
2. Save collection type

### Expected behavior

Strapi should generate types for new collection type

**Comment by innerdvations** [comment]
[Fix has been released in 4.15.5](https://github.com/strapi/strapi/pull/18775)
