### ISSUE TITLE
Error at first publish of a single type with internationalization

### ISSUE THREAD

**Issue by alan29450** [strapi/strapi#18737]
### Required System information

    Node.js version: v16.20.2
    Strapi version: v4.11.5
    Database: mysql
    current plan: Community Edition

### Describe the bug

When i create a new single type and try to publish it it works for the first language but failed for the second one.
I have to manualy update the "published_at" in database to force the publication, once it done it works fine.

### Steps to reproduce the behavior

1. Create a new single type
2. populate and publish the singletype in a language
3. populate the second language an click publish

### Expected behavior

Being able tu publish without having to manualy update my database.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18703
