### ISSUE TITLE
Custom Plugin: saving JSON type for custom field silently fails when type is wrong

### ISSUE THREAD

**Issue by rc9** [strapi/strapi#18741]
### Required System information

- OS: darwin-arm64
- Strapi Version: 4.15.2
- Node/Yarn Version: npm/9.8.1 node/v18.18.0 darwin arm64 workspaces/false
- Edition: Community
- Database: postgres
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When attempting to save a custom field that has input of type JSON, but is being saved as a javascript object instead of `JSON.stringify()`ed the save fails silently.

The network shows no attempt to make a request to the server so there must be some JS validation on the type before making an API request to save but nothing is logged in the console. The input component also does not report any error and the error field remains set to `''`.

### Steps to reproduce the behavior

1. use `npm run strapi plugin:build` to bootstrap a new plugin
2. register a custom field of json type of in `../server/register.ts`
3. register a custom field of json type in the `../admin/source/index.tsx`
4. build a simple input component that sets the `value` via `onChange` to as a javascript "json" (re: object, e.g: `{ name: "my name", age: 16 }`)
5. in the admin attempt to save an item of this custom type
6. when clicking the save button notice the following:
    1. no green bubble of successful save
    2. no error related to saving in the browser console
    3. no request in the network tab (therefore client side error blocking API request)
    4. no change in the `error` prop of the component

### Expected behavior

Some indication that converting the value to a proper JSON type to be saved to the DB failed, probably best set in the `error` prop of the input component so it can show in the UI.

### Screenshots

N/A

### Code snippets
// .../server/register.ts
```
...
strapi.customFields.register({
    name: 'user-property',
    plugin: 'user-property-submission',
    type: 'json',
  });
```

// .../admin/src/index.tsx
```
...
app.customFields.register({
      name: 'user-property',
      pluginId: pluginId,
      type: 'json',
      intlLabel: {
        id: 'user-property-submission.user-property.label',
        defaultMessage: 'User Property',
      },
      intlDescription: {
        id: 'user-property-submission.user-property.description',
        defaultMessage:
          'Select the user property to a given value. This must match the type entered.',
      },
      icon: InputIcon,
      components: {
        Input: async () =>
          import(
            /* webpackChunkName: "input-component" */ './components/UserPropertyBlock'
          ),
      },
...
```

// .../components/UserPropertyBlock
```
...
const value = {name: "my name", age: 16 }
onChange({
      target: {
        name,
        value,
        type: attribute.type,
      },
)
...
```

### Additional context

JSON.stringify() on javascript object leads to correctly saving as expected.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18073
