### ISSUE TITLE
App.js with wrong path to plugin

### ISSUE THREAD

**Issue by GabrielGallina** [strapi/strapi#18742]
## Bug report

App.js with wrong path to plugin, after upgrading to 4.15.2

Strapi Version: 4.15.2

### Describe the bug

When running the yarn build command I receive the following error:

Module not found: Error: Can't resolve '....srcpluginsvideo-uploader/strapi-admin'

The path to the plugin is always generated without any /

Note: the plugin is a auto generated by strapi generate

Import in the app.js:
import videoUploader from "....srcpluginsvideo-uploader/strapi-admin";

**Comment by umair-me** [comment]
Having the same issue with v4.15.4, the path generated is without any `/`

**Comment by Vampire-V** [comment]
@joshuaellis 
windows 11 doesn't work
File examples\getstarted\.strapi\client\app.js : import customisations from "....srcadminapp.js";

**Comment by gagal18** [comment]
Is this fixed for windows 11 ?
