### ISSUE TITLE
Subpath files are not exported from packages anymore

### ISSUE THREAD

**Issue by g0shed** [strapi/strapi#18743]
## Bug report

After upgrading to the latest version of strapi I get the following error ehn trying to build

```
$ strapi build
✔ Compiling TS (1307.0721920728683ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (111.18539905548096ms)
⠋ Building admin panel
⠼ Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package <path>/node_modules/@strapi/admin (see exports field in <path>/node_modules/@strapi/admin/package.json)
```

### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.15.2
- Database: mysql
- Operating system: Linux
- Is your project Javascript or Typescript: TypeScript

### Expected behavior

Should be able to run stripe after upgrade

**Comment by deBasMan21** [comment]
I have the same issue here. All of a sudden it stopped working. No changes were made on my side. For me the module that cannot be found is `./admin/src/content-manager/hooks/usePluginsQueryParams`. The rest of the error message is the same.

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.15.4
- Database: mysql
- Operating system: MacOs
- Is your project Javascript or Typescript: Javascript

**Comment by ThewBear** [comment]
I think it's because of adding `exports` to the `package.json` file in this commit https://github.com/strapi/strapi/commit/0e69461383292883156617d3d81ae7e03f75dd76#diff-d92ce1b3e295cd4b7db37a8b660078f2cca3e8b164fdba78a95b106774e94d6c which affects v4.15.2 and above.

From https://nodejs.org/api/packages.html#package-entry-points
> Existing packages introducing the ["exports"](https://nodejs.org/api/packages.html#exports) field will prevent consumers of the package from using any entry points that are not defined, including the [package.json](https://nodejs.org/api/packages.html#nodejs-packagejson-field-definitions) (e.g. require('your-package/package.json')). **This will likely be a breaking change.**

This broke my build since my code relies on `getPaginationInfo` from `@strapi/strapi/dist/core-api/service/pagination`. If the issue above is not fixed, Strapi should export `getPaginationInfo` function in the utils since this function is very useful when creating a paginated custom controller.

**Comment by M-Nasser-M** [comment]
adding the following lines int the strrapi node modules seems to have fixed the issue for me 

    "./admin/src/content-manager/utils": {
      "types": "./server/utils/index.d.ts",
      "source": "./server/utils/index.js",
      "require": "./server/utils/index.js",
      "default": "./server/utils/index.js"
    },

![image](https://github.com/strapi/strapi/assets/34859699/b30ac976-941c-4eb8-9465-5a11d96eeecb)

can you please try and let me know if anybody had the same error after doing this so i can maybe make a pull request for it

**Comment by AndColla** [comment]
Same issue here
- Node.js version: 18.9.1
- Yarn version: 1.22.19
- Strapi version: 4.15.4
- Database: postgres
- Operating system: Linux (Docker)
- Is your project Javascript or Typescript: Javascript

I get the error `Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package /opt/app/node_modules/@strapi/admin`

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18771

**Comment by g0shed** [comment]
@derrickmehaffy this is not a duplicate, and in the mentioned issue, it's stated that something that is breaking existing installations wont be fixed, how? why? if it's breaking either tell us a way to fix it or push a proper fix, simple

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy this is not a duplicate, and in the mentioned issue, it's stated that something that is breaking existing installations wont be fixed, how? why? if it's breaking either tell us a way to fix it or push a proper fix, simple

I don't agree with the decision myself but it was made above me. Best to discuss it on the main issue I linked but it is a duplicate.

**Comment by aviddv1** [comment]
@ThewBear  I added 

`"./dist/core-api/service/pagination": {
      "types": "./dist/core-api/service/pagination.d.ts",
      "source": "./dist/core-api/service/pagination.js",
      "import": "./dist/core-api/service/pagination.mjs",
      "require": "./dist/core-api/service/pagination.js",
      "default": "./dist/core-api/service/pagination.js"
    },`

to the exports in package.json in @strapi/strapi. Not ideal, but it's a temporary fix
