### ISSUE TITLE
Show thumbnails of images in the contents list-view

### ISSUE THREAD

**Issue by hansemannn** [strapi/strapi#1874]
**What is the expected behavior?**

It would be awesome to see a preview of content with the "image" type inside the contents list-view.  Going even further, a slick React library could be used to enable a hover-preview of them, giving the content curators the best possible UX.

**Comment by Aurelsicoko** [comment]
@hansemannn +100 👍 

We already thought about implementing the preview of images but I think the implementation of the relational field is more important. But, you're right, it'll be done in the next versions, I can't give you a date though...

**Comment by hansemannn** [comment]
@sbastias I meant in the collection-list of entities that use the "photo" type.

**Comment by Aurelsicoko** [comment]
I added this feature in our Product Board (not in the public roadmap though) to think about it. I'm closing this issue to keep the repository as clear as possible and references the features requests in one place.
