### ISSUE TITLE
Creating new component: "The value does not match the regex"

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#18753]
I create new component and connect it to other component. 
Component name: question-items

Strapi admin says: "The value does not match the regex"

What is regex for this field? What can I use and what can't?

Environment: development                                
Version: 4.15.4 (node v18.18.1)
Edition: Community
Database: sqlite  

<img width="1439" alt="Screenshot 2023-11-11 at 13 08 53" src="https://github.com/strapi/strapi/assets/1038168/4549b043-c6e2-40a8-a337-5f51c56cc391">

**Comment by teinett** [comment]
Steps to reproduce: 
- create component with dash in the name, for example, "question-items" 
- observe the message, that doesn't give proper information, what exactly the pattern should be in this case, and what is wrong.

**Comment by skliarovartem** [comment]
did you found the solution?
