### ISSUE TITLE
Admin panel customization via config object in ./src/admin/app.js not working anymore

### ISSUE THREAD

**Issue by Babm71** [strapi/strapi#18758]
### Required System information
Environment: development
OS: win32-x64
Strapi Version: 4.15.4
Node/Yarn Version: npm/10.2.3 node/v20.9.0 win32 x64 workspaces/false
Edition: Community
Database: sqlite
- Is your project Javascript or Typescript: Javascript (started from npx create-strapi-app@latest my-project)

### Describe the bug

As described in https://docs.strapi.io/dev-docs/admin-panel-customization#extending-translations one can customize the Admin panel texts as well add locales, I had it working in a prior version of strapi, but now it doesn't anymore, so the text remain the same is the original ones, like a step of loading and using the config object has been skipped, or has this customization method changed and hasn't been documented yet?

### Steps to reproduce the behavior
Content app.js
const config = {
  locales: ["nl"],
  translations: {
    en: {
      "Auth.form.welcome.title": "Welcome to Company Back Office",
      "Auth.form.welcome.subtitle": "Log in to your Company account",
      "app.components.LeftMenu.navbrand.title": "Company ",
      "app.components.LeftMenu.navbrand.workplace": "Dashboard",
    },
    nl: {
      "Auth.form.welcome.title": "Welkom bij Company Back Office",
      "Auth.form.welcome.subtitle": "Inloggen met je Company account",      
      "app.components.LeftMenu.navbrand.title": "Company ",
      "app.components.LeftMenu.navbrand.workplace": "Dashboard",
    },
  },
};

const bootstrap = (app) => {
  console.log(app);
};

export default {
  config,
  bootstrap,
};

### Expected behavior

That the interface would show the texts in the config in stead of the strapi language.json files

Kind Regards
Bart

**Comment by senna-cheil** [comment]
I am also facing this issue
