### ISSUE TITLE
How to deploy plugins locally or switch between development and production version?

### ISSUE THREAD

**Issue by mockbirds** [strapi/strapi#1875]
**Informations**
- **Node.js version**: v10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongoDB v3.6.6
- **Operating system**: macOS 10.12.6

**What is the current behavior?**
1. Managed to setup the dev environment for strapi
2. Created a new strapi project in dev mode
3. Added a new custom array field type to strapi by making
changes to the content-manager and content-type-builder plugins
and the mongoose hook (see file list below)<img width="645" alt="bildschirmfoto 2018-09-02 um 12 55 35" src="https://user-images.githubusercontent.com/24314119/44955365-5481bb00-aeb2-11e8-8a30-98a5425abd55.png">
4. Successfully started the strapi dev server with live-updates
5. Result: The custom array field type is available in the
content-manager and content-type-builder plugins and can
be used in the backend and frontend. Everything is working!
6. Now it comes to deployment...
7. Created a new strapi project in non-dev mode (without `--dev`)
8. Rebuild all strapi plugins of the cloned and modified strapi
repository with `npm run setup:build`
9. Copied the result of the build
From:
`strapi/packages/strapi-plugin-content-manager/admin/build/`
`strapi/packages/strapi-plugin-content-type-builder/admin/build/`
To:
`[my_project]/plugins/content-manager/admin/build/`
`[my_project]/plugins/content-type-builder/admin/build/`
10. Started the new non-dev project with `npm start` or `strapi start`
11. Result: content-type-builder plugin works and can be used.
content-manager plugin doesn't work at all. Page doesn't load
and screen shows endless loading wheel. Can't create any new
items of the new content type. Same UI-behavior. Page doesn't
load and screen shows endless loading wheel.
![bildschirmfoto 2018-09-02 um 13 17 54](https://user-images.githubusercontent.com/24314119/44955385-b04c4400-aeb2-11e8-933b-9b2621891be8.png)![bildschirmfoto 2018-09-02 um 13 17 58](https://user-images.githubusercontent.com/24314119/44955391-c8bc5e80-aeb2-11e8-8c43-e10db2766bcc.png)

12. I also tried to rebuild the admin panel with `npm run setup`,
but that doesn't work either.
13. I also tried this procedure with a plane strapi version
without modifications of the content-manager and content-type-builder
plugins and mongoose hook. It doesn't work either.

[Update]

14. I also modified the `strapi.js` and `strapi-install.js` script in a way
that it is now possible to install plugins from a local module path. But
it doesn't work either. 

**Steps to reproduce the problem**
See descriptions above.

**What is the expected behavior?**
Working content-manager plugin an ability to create new items
of the new content type.

**Suggested solutions**
Best practice guides:
How can I deploy locally developed plugins in my strapi project?
How can I switch between development and production mode of a strapi project?

**Comment by soupette** [comment]
Can you give the error you get from the chrome console?

**Comment by mockbirds** [comment]
Thanks for getting back to me. Unfortunately there was no really an error
in the chrome console, just an empty `<div>` respectively React component.
But I will collect all logs and provide them later today.

In the meantime, is there something I can do differently or how is the preferred way
to deploy my locally modified versions of the content-manager, content-type-builder
and strapi-hook-mongoose to my newly created strapi application?

Thanks for your help!

**Comment by nandiheath** [comment]
I have got the exactly the same problem. What have I done is to remove the content management plugin completely and then reinstall it through the admin panel, after a reboot it works. However when I tried to create a new entry for a model through the page, it got stuck again.

My project is build without --dev and was working very well. The problem appears when I checkout it on another laptop.

**Comment by soupette** [comment]
@sbastias @mockbirds I'm going to have a hard reproducing your bug do you have a repository or a registry to give me so I can try to see what's happening?

**Comment by soupette** [comment]
@sbastias you don't have the right workflow it should be the following

```
git clone git@github.com:strapi/strapi.git
cd strapi && npm run setup:build
# in another window
strapi new appName --dev
````

Once you're done with your modifications `cd strapi && npm run setup:build`

And in another window `strapi new myapp`

**Comment by sbastias** [comment]
So content-manager won't work under :1337 anymore? It was working until the
past couple of days.

**Comment by sbastias** [comment]
I started a new test project.

It worked, partially...

I was able to import api from current project and browse entries in db, but
if I try to add a new content-type, or I try to change a relation (or
update database name) it leads to a blank page, and in console:
```
main.js:16 Uncaught Error: Minified React error #188; visit
https://reactjs.org/docs/error-decoder.html?invariant=188 for the full
message or use the non-minified dev environment for full errors and
additional helpful warnings.
```

**Comment by soupette** [comment]
I got the same issue I'm currently debugging it...

The only problem is that I don't know where the error is coming from...

**Comment by sbastias** [comment]
Just following up....

I did as you advised and started a new project from the re-built strapi, and imported my data.

This is what the relational part looks like in DEV:
![image](https://user-images.githubusercontent.com/1007243/45228989-b10a1f00-b292-11e8-8eee-985302d2c284.png)


This is what it looks like in non-DEV strapi installation:
![image](https://user-images.githubusercontent.com/1007243/45230679-99816500-b297-11e8-82bf-a6ecb5892d4c.png)


It actually looks better, but - my other custom admin changes aren't showing up!

**Comment by soupette** [comment]
what's your version strapi?

**Comment by sbastias** [comment]
3.0.0-Alpha.13

I had 14 installed for a quick test....

**Comment by hansemannn** [comment]
Same here. My installation was working fine until yesterday and now it's giving blank pages all around the place.

**Comment by mockbirds** [comment]
@soupette I seems to be fixed now. I took the latest master (see information below), put my changes on top and did a local release (see descriptions below). After installation `npm install strapi@alpha -g` I've created a new strapi project `strapi new strapi-project` and luckily all of my changes in the content-manager and content-type-builder were working. No more blank pages! Great!

I don't know which commits or changes fixed the "blank pages" problem since a full release takes about 14 minutes and switching commits back and forth would take to much time ;)

Note: I had to add the `cross-spawn` dependency to the following file `strapi/packages/strapi/package.json` otherwise `strapi/packages/strapi/lib/utils/openBrowser.js` would report an error in the locally released version of strapi if you do a `strapi start` in the newly created strapi project.

**Informations**
- **Node.js version**: v10.9.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-master (Commit SHA: b4dedc12f16b087ccf4cf7a51c1ff34e742e23fe)
- **Database**: MongoDB v3.6.6
- **Verdaccio**: 3.7.1
- **Operating system**: macOS 10.12.6

**Local Release**
1. Installed verdaccio as local package registry
2. Did a clean checkout of strapi 3.0.0-master (Commit SHA: b4dedc12f16b087ccf4cf7a51c1ff34e742e23fe)
3. Put all of my changes on top of the master
4. Removed any previous strapi installations
5. Cleaned all local npm and verdaccio caches
6. Removed all node_modules and build folders
7. Removed all package-lock.json files
8. Changed the version of all strapi modules to v3.0.0-custom
9. Did a `TAG=alpha npm run release` to the local package registry
10. Did a `npm install strapi@alpha -g`
11. `strapi -v` shows `v3.0.0-custom`
11. Created a new strapi project with `strapi new strapi-project`
12. Created a new content type with the content-type-builder plugin
13. content-manager and content-type-builder plugins show all of my changes.
14. No more blank pages :)
15. Great :)

**Comment by mockbirds** [comment]
@maturanomx I remember having similar errors during the build, especially the one with the `layout.js` file. So, I think clean up config files, build directories, databases is really important here and to make sure that there are no changes in your cloned repo. Even a `npm run setup` or `npm run setup:build` slightly changes some files. Secondly it is really important to change/increase the version numbers within the `package.json` files and also to update the version numbers of the dependent strapi modules (forgot to mention this). I will update my previous answer to reflect all of my changes and give more details.

**Comment by maturanomx** [comment]
> is really important here and to make sure that there are no changes in your cloned repo

As I said, I worked from a clean clone and following your guide step by step. That's why I asked if that's all what you did and nothing further. 

The `plugins.json` file [doesn't exist in the repository](https://github.com/strapi/strapi/tree/master/packages/strapi-admin/admin/src/config) and I think I saw the file is created running a setup.

... I'll try again, but is really strange we have different result. It will be difficult for you tracking when that file is created??... if is created at all 🤔

**Comment by sbastias** [comment]
If you installed with npm run setup:build, go to your npm globals directory
and delete strapi links.... And then run npm run setup:build again.

**Comment by maturanomx** [comment]
>  the plugins.json is created when you generate your app that's why you can't locate it in the monorepo

So, It's a requirement create a new project do the release? 🤔. I can't do that in our CI environment. Is valid created it with and empty array (`[]`) as content as workaround?

**Comment by sbastias** [comment]
Hello all,

I ran into the SAME problem after making some additional edits.

Here is what fixed it for me...

After installing strapi (from a private github repo):

strapi> **npm run setup:build** *(this creates global links to strapi plugins!)*

Then I deleted node_modules from both strapi-plugin-content-manager and strapi-plugin-users-permissions, and reinstalled them with **npm install**

I made changes to strapi-helper-plugin, so I deleted the strapi-helper-plugin directory from the freshly installed node_modules for **both** plugins, and linked to it with **npm link strapi-helper-plugin**

And for good measure, I relinked both plugins in their root directories with **npm link**

Then **strapi start** in my app directory and PROBLEM SOLVED!!!

**Comment by MWalid** [comment]
Actually it's difficult like hell to deploy the development project,

Strapi is easy to start with, to build some endpoints, and to kick off your app, however if you need to modify anything, literally anything you are left on your own, 

I've developed a full functional plugin, but i'm unable to deploy it .... 

I'm totally stuck, there should be a **bug-free** guide to deploy a development project,

**Comment by maturanomx** [comment]
> Actually it's difficult like hell to deploy the development project,

Totally  agree!

> I've developed a full functional plugin, but i'm unable to deploy it ....

I'm deploying the library and and a project in a private registry. I share part of my script (remove private things and stuff). Hope helps; if not reduce your problem and maybe I can help you.

```bash
#!/usr/bin/env bash

export HTTP_PROXY="needed_because_some_dependencies_download_things"
export HTTPS_PROXY="$HTTP_PROXY"
export NO_PROXY="XXX"

# Define with default value if not defined previously
: "${REGISTRY:=internal_registry_uri}"

# Workaround.
echo '[]' > packages/strapi-admin/admin/src/config/plugins.json

# In my case, the deploy happens in a CI environments, from a clean clone. Nothing to clean and already had an `install` task
# npm run clean:all &&
# npm install &&
npm run createsymlinkdependencies &&
lerna exec --concurrency 1 -- npm install --registry=$REGISTRY &&
npm run removesymlinkdependencies &&
node ./scripts/publish.js $TAG
```

**Comment by soupette** [comment]
@MWalid  can you detail your issue a bit more, I'm not sure if you're trying to deploy a custom plugin or try to deploy a dev app as we understand it ( created with the `--dev` flag).

**Comment by MWalid** [comment]
I created a custom plugin with a dev app (created with `--dev` flag), it's not clear from the documentation that I should use the `--dev` flag when writing a custom plugin or no ....

**Comment by maturanomx** [comment]
So, you created a strapi project with and then you begin coding in a new directory under `/plugins`? 🤔

**Comment by MWalid** [comment]
Yep I think so

**Comment by maturanomx** [comment]
So, when you said you are deploying your project, you mean all this created code along with you plug-in, right?.

If that's the case, forget about the `--dev` flag and share your deployment process and your error...

**Comment by lauriejim** [comment]
https://portal.productboard.com/strapi/c/12-migrate-across-environments
