### ISSUE TITLE
Setting maximum length setting on string type doesn't alter the column length in the database

### ISSUE THREAD

**Issue by uino95** [strapi/strapi#18756]
### Required System information

- Node.js version: v18.12.1
- NPM version: yarn/1.22.19 
- Strapi version: v4.10.5
- Database: Postgres
- Operating system: Heroku Dyno
- Is your project Javascript or Typescript: Typescript

### Describe the bug

While creating a field of type String (Short Text) I set the maximum length advanced settings to a value higher than 255 like 2048, this upper limit should be reflected in the database column data type of VARCHAR(2048). Instead I still see a VARCHAR(255).
I know that there is the Long Text option, but this still seems to be a bug to me. 

### Steps to reproduce the behavior

1. Go to the Content-Type Builder in strapi admin
1. Create a new Collection 
1. Create a new Text field of type "Short Text" in the newly created collection
2. Set Maximum Length to a value higher than 255
3. Save
4. Go to Content Manager 
5. Create a new entry in the newly created collection
6. Set a value longer than 255 characters in the Text field with maximum length set
7. Save 
8. Receive the following 500 error
``` 
error: insert into "new_collection" ("created_at", "created_by_id","updated_at", "updated_by_id", "value") values ($1, $2, $3, $4, $5) returning "id" - value too long for type character varying(255)
``` 

### Expected behavior

Being able to set a string value with a length longer than 255 character on a field of type "Short Text" when maximum length is set to a value higher than 255

### Additional context

This issue was already signaled here https://github.com/strapi/strapi/issues/11253, and closed as solved in strapi v4

**Comment by derrickmehaffy** [comment]
This is intended because that is validated inside the application, if you want to apply additional constraints to the database layer you will need to do it manually using this experimental validation options: https://docs.strapi.io/dev-docs/backend-customization/models#database-validations-and-settings
