### ISSUE TITLE
Strapi Plugin development show-stopping error after 4.14.6 and beyond updated

### ISSUE THREAD

**Issue by guerillacodester** [strapi/strapi#18759]
- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 4.15.4, 4.15.2,4.15.1,4.15.0
- Database: mysql
- Operating system: windows 11
- Typescript:

To reproduce, follow these steps:

npx create-strapi-app@4.15.4
Ok to proceed? (y) y

? What would you like to name your project? testserver
? Choose your installation type Custom (manual settings)
? Choose your preferred language
? Choose your preferred language TypeScript
? Choose your default database client
? Choose your default database client mysql
? Database name: (testserver)
? Database name: testserver
? Host: (127.0.0.1)
? Host: 127.0.0.1
? Port: (3306)
? Port: 3306
? Username: root
? Username: root
? Password: ****
? Password: ****
? Enable SSL connection: (y/N) y
? Enable SSL connection: Yes

I code . into the main project and did this from vscode terminal: 
yarn strapi generate->plugin->testplugin->typescript

I added the result t the plugins.ts file in the /config folder
export default {
  // ...
  'testplugin': {
    enabled: true,
    resolve: './src/plugins/testplugin'
  },
  // ...
}

In the plugin folder I then did a yarn install and yarn build and this completed without issue.

in the root project folder I then did a yarn build:

this immediately returned the error:
$ strapi build
Debugger attached.
✔ Compiling TS (1306.9113999996334ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (1110.938000000082ms)
⠋ Building admin panel
⠴ Building admin panelDebugger attached.
[ERROR] Module not found: Error: Can't resolve '....srcplugins  estplugin/strapi-admin' in 'E:\temp\testserver\testserver\.strapi\client'
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information

Waiting for the debugger to disconnect...
error Command failed with exit code 1.

the issue is here: [ERROR] Module not found: Error: Can't resolve '....srcplugins where the generator fails to add a "/" to the path of the plugin.

I traced the culprit to the auto-generated file in the E:\temp\testserver\testserver\.strapi\client\app.js folder.

in this file, you can clearly see the problem on line 8:

\.strapi\client\app.js

import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import testplugin from "....srcplugins\testplugin/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "users-permissions": usersPermissions,
    i18n: i18N,
    "strapi-cloud": strapiCloud,
    testplugin: testplugin,
  },
});

This problem occurs for all version updates beyond strapi 4.14.6, rendering any further releases completely useless for plugin development. If you ask me, this is a major problem and needs to be addressed as a matter of urgency!

**Comment by Jellepa** [comment]
Experiencing the exact same problem, hope this will be reopened and a fix is found soon
