### ISSUE TITLE
after update to strapi 4.15.4 -> i18n installed but no language except english is in the backend selectable

### ISSUE THREAD

**Issue by svenali** [strapi/strapi#18762]
### Required System information

- Node.js version: v20.5.1
- NPM version: 9.8.0
- Strapi version: 4.15.4
- Database: mysql
- Operating system: Ubuntu Linux
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

Only english is in the personal profile selectable. In strapi 4.15.0 I installed the i18n package and uncommented under src/admin/app.js the wanted locales. But now, under 4.15.4 is only English selectable. If I select English, strapi shows also an error. 

### Steps to reproduce the behavior

1. Go to your personal profil on left side
2. Click on your name
3. Choose "Profile"
4. Click on "Interface Language"
5. Only English appears

### Expected behavior

Like in 4.15.0 I want to see the uncommented languages by src/admin/app.js

**Comment by jorshen** [comment]
me too

**Comment by svenali** [comment]
Excuse me, but it seems, that [joshuaellis](https://github.com/joshuaellis) fixed the bug, but how can I get this fix?

regards+ thanks,
Sven

**Comment by svenali** [comment]
> me too

@jorshen : Does it work in your installation now?
