### ISSUE TITLE
Adding new elements to existing dynamic zone

### ISSUE THREAD

**Issue by svenali** [strapi/strapi#18760]
### Required System information

- Node.js version: v20.5.1
- NPM version: 9.8.0
- Strapi version: 4.15.4 (Bug exists since 4.15.0)
- Database: mysql
- Operating system: Ubuntu and MacOS
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

After creating a component, I added these components to a so called dynamic zone in an article collection. If I want to add new created components, strapi is showing a blank page only.

### Steps to reproduce the behavior

1. Go to Content-Type Builder
2. Click on a collection type (like by me -> Article)
3. Press the Button "Add  a component"
4. See error (here a blank page and nothing happens).

### Expected behavior

I expect that a window is opening where I can choose the newly created component.

### Screenshots

<img width="1274" alt="screenshot" src="https://github.com/strapi/strapi/assets/7927414/6267bc53-ab81-48e7-95da-257a33e5be2f">

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18633
