### ISSUE TITLE
AWS S3 compatible services upload fail on compatible storage (Linode Object Storage)

### ISSUE THREAD

**Issue by claudiobgit** [strapi/strapi#18761]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 4.15.4
- Database: postgres
- Operating system: linux-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When using the AWS S3 upload provider on a private bucket on Linode Object Storage (eu-central-1 region) the server crashes. It was working fine until Strapi v14.4.4 and then stopped.

### Steps to reproduce the behavior

1. Set up a Strapi backend that uses @strapi/provider-upload-aws-s3 configure it and let it run
2. Go to the 'Media Library' in the Strapi Dashboard
3. Click on '+ Add new assets'
4. Select a small image to test and click on 'Upload 1 asset to the library.'
5. See error saying 'An error occurred while uploading the file.' in the Strapi Dashboard
6. Strapi server crashes in the backend

### Expected behavior

It would be expected to save the image on the S3 bucket as it was doing until around Strapi version 4.14.4

### Logs

Logs from the host running Strapi tell:
```
node:internal/url:775
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at parseUrl (/opt/node_modules/@smithy/url-parser/dist-cjs/index.js:7:38)
    at toEndpointV1 (/opt/node_modules/@smithy/middleware-endpoint/dist-cjs/adaptors/toEndpointV1.js:12:38)
    at Object.customEndpointProvider [as endpoint] (/opt/node_modules/@smithy/middleware-endpoint/dist-cjs/resolveEndpointConfig.js:10:99)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Upload.__uploadUsingPut (/opt/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:66:26)
    at async Upload.__doConcurrentUpload (/opt/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:128:28)
    at async Promise.all (index 0)
    at async Upload.__doMultipartUpload (/opt/node_modules/@aws-sdk/lib-storage/dist-cjs/Upload.js:211:9) {
  code: 'ERR_INVALID_URL',
  input: 'eu-central-1.linodeobjects.com'
}
```

### Additional context

Environment variables are configured using the endpoint option for Not-Amazon S3 services, as per documentation:
```

# AWS S3 provider for Linode S3 compatible Object Storage
LINODE_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
LINODE_ACCESS_SECRET=XXXXXXXXXXXXXXXXXXXX
LINODE_ENDPOINT=eu-central-1.linodeobjects.com
LINODE_BUCKET=XXXXXXXXXXXXXXXXXXXX
JWT_SECRET=XXXXXXXXXXXXXXXXXXXX
```

File plugins.js has the following content: 

```
module.exports = ({ env }) => ({
  // AWS S3 provider for Strapi uploads to S3 compatible services
  // https://market.strapi.io/providers/@strapi-provider-upload-aws-s3
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('LINODE_ACCESS_KEY_ID'),
        secretAccessKey: env('LINODE_ACCESS_SECRET'),
        endpoint: env('LINODE_ENDPOINT'),
        params: {
          Bucket: env('LINODE_BUCKET'),
        },
      },
    },
  },
});
```

**Comment by derek-maurer** [comment]
I'm having the same issue. Haven't figured it out either.

**Comment by derek-maurer** [comment]
What's super weird is that my local setup is working fine when running with "yarn develop", but when I build my docker image and run the image locally or on my server it fails to upload a file to Linode saying the region is missing. However, I've confirmed that my .env file is the same when running locally with "yarn develop" or in the docker image. 

plugins.js

`module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        rootPath: env("CDN_ROOT_PATH"),
        s3Options: {
          accessKeyId: env("AWS_ACCESS_KEY_ID"),
          secretAccessKey: env("AWS_ACCESS_SECRET"),
          endpoint: env("CDN_URL"),
          params: {
            Bucket: env("AWS_BUCKET_NAME"),
          },
        },
      },
    },
  },
  "strapi-plugin-populate-deep": {
    config: {
      defaultDepth: 5, // Default is 5
    },
  },
});
`

.env

`CDN_URL="https://us-southeast-1.linodeobjects.com"
CDN_ROOT_PATH="<redacted>"
AWS_ACCESS_KEY_ID="<redacted>"
AWS_ACCESS_SECRET="<redacted>"
AWS_BUCKET_NAME="<redacted>"`

**Comment by jruizuv** [comment]
I have exactly the same issue. Using mysql as a database. I've tested with the latest version of strapi, and only adding the aws s3 plugin and configuring to an s3 compatible service that works on previous versions and I get in the console a INVALID_URL error. Specifically:

```
node:internal/url:775
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at parseUrl (C:\Users\Julio\Documents\strapilab\node_modules\@smithy\url-parser\dist-cjs\index.js:7:38)
    at toEndpointV1 (C:\Users\Julio\Documents\strapilab\node_modules\@smithy\middleware-endpoint\dist-cjs\adaptors\toEndpointV1.js:12:38)
    at Object.customEndpointProvider [as endpoint] (C:\Users\Julio\Documents\strapilab\node_modules\@smithy\middleware-endpoint\dist-cjs\resolveEndpointConfig.js:10:99)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async Upload.__uploadUsingPut (C:\Users\Julio\Documents\strapilab\node_modules\@aws-sdk\lib-storage\dist-cjs\Upload.js:66:26)
    at async Upload.__doConcurrentUpload (C:\Users\Julio\Documents\strapilab\node_modules\@aws-sdk\lib-storage\dist-cjs\Upload.js:128:28)
    at async Promise.all (index 0)
    at async Upload.__doMultipartUpload (C:\Users\Julio\Documents\strapilab\node_modules\@aws-sdk\lib-storage\dist-cjs\Upload.js:211:9) {
  code: 'ERR_INVALID_URL',
  input: 'ewr1.vultrobjects.com'
}
```

Hope this helps someone resolve it.

**Comment by danielkamin** [comment]
I have found out that error originates in @aws-sdk package and downgrading plugin to version 4.4.0 fixes the issue.
Maybe related to [#14654](https://github.com/strapi/strapi/pull/14654) or [#14127](https://github.com/strapi/strapi/pull/14127)

**Comment by Boegie19** [comment]
@derek-maurer please don't downgrade plugins form the strapi core repo aka everyting what has the same release versions as main. to diffrent versions this could cease a lot of problems I would personaly downgrade to 4.14.6 until this is fixed.

**Comment by derek-maurer** [comment]
Good to know, thank you. I'll give the minor downgrade a try this weekend. Thanks everyone!

**Comment by claudiobgit** [comment]
It's referenced at #18836 too. In case others are looking for temporary solutions see comments.

**Comment by christiancp100** [comment]
@claudiobgit Sorry for the late reply but we wanted to make sure to test everything right before providing an answer to your issue. What we did in the AWS provider was updating the aws dependency, going from AWS V2 to AWS V3. And this update of version changed the format of the URLs, as you said and it's specified in [this document](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access). TLDR: AWS recommends the new URL format (called virtual-hosted–style URI with the format ), since the Path-style URI is going to be deprecated at some point. [This is another post](https://aws.amazon.com/es/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) that justifies better their decision. If Linode only allows using the old format and you want to make it work with 4.15.x versions without migrating anything, you can set a `baseUrl` property in the plugin with your desired URL format, as shown in the example below:
```
  upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        baseUrl: 'https://s3.{region}.amazonaws.com/{bucket}, // THIS LINE IS THE IMPORTANT ONE
        params: {
          ACL: env('AWS_ACL', 'public-read'),
          signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 15 * 60),
          Bucket: env('AWS_BUCKET'),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
```

**Comment by claudiobgit** [comment]
@christiancp100 thanks a lot for this! 
I confirm it's working on Akamai/Linode S3 compatible too, adding a `region` property (and respective env variable) and with the following code used to build the URL compatible in the _endpoint way_:

```
upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        accessKeyId: env('LINODE_ACCESS_KEY_ID'),
        secretAccessKey: env('LINODE_ACCESS_SECRET'),
        region: env('LINODE_REGION'), // need to set this env var even if not used in endpoint building below
        endpoint: 'https://eu-central-1.linodeobjects.com', // need to explicit the S3 region here to make it work
        params: {
          Bucket: env('LINODE_BUCKET'),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
 },
```

It has been tested and confirmed working on local dev environment and in a production container.

**Comment by ainsleyclark** [comment]
Does this fix also apply to Digital Ocean Spaces? I've applied the above but I'm stiill gtting the same error.

```js
	upload: {
		config: {
			provider: 'aws-s3',
			providerOptions: {
				endpoint: env('SPACES_ENDPOINT'),
				rootPath: env('SPACES_DIRECTORY'),
				s3Options: {
					accessKeyId: env('SPACES_ACCESS_KEY'),
					secretAccessKey: env('SPACES_SECRET_KEY'),
					region: 'ams3',
					params: {
						Bucket: env('SPACES_BUCKET'),
						CacheControl: 'public, max-age=31536000',
					},
				},
			},
			actionOptions: {
				upload: {},
				uploadStream: {},
				delete: {},
			},
		},
	},
```

**Comment by jruizuv** [comment]
Hey ainsley. I'm using this with Vultr's bucket storage which is the same as digital ocean. This worked for me.
`upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        s3Options: {
          accessKeyId: env('VULTR_ACCESS_KEY_ID'),
          secretAccessKey: env('VULTR_ACCESS_SECRET'),
          region: env('VULTR_REGION'), // xxxx
          endpoint: env('VULTR_ENDPOINT'), // https://xxxx.vultrobjects.com/
          params: {
            Bucket: env('VULTR_BUCKET')
          },
          sizeLimit: 250 * 1024 * 1024 // 256mb in bytes
        }
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    }
  },`

Take note that the endpoint now has to have the https prefix in it and you also have to add the region.

**Comment by ainsleyclark** [comment]
Thanks @jruizuv 

Just to be doubly sure, if we are defining the endpoint, does that mean we can omit the `Bucket` from `params`?
(As the bucket is included within the endpoint).

**Comment by claudiobgit** [comment]
> Just to be doubly sure, if we are defining the endpoint, does that mean we can omit the `Bucket` from `params`? (As the bucket is included within the endpoint).

From my experience (Linode S3 compatible Object Storage) you can't omit `Bucket` from params as you can't omit `region` (as before the update that broke functioning) even if you have it in the `endpoint` as indicated in [this comment](https://github.com/strapi/strapi/issues/18761#issuecomment-1826024346).

There is no way to use `baseUrl` or at least I didn't find any so I sticked with `endpoint`.

**Comment by fabianmu** [comment]
I just had this issue when upgrading from strapi 4.15 to 4.24.4 and our digitalocean spaces upload. Putting this in here as it might help someone having this issue as well.

This configuration works with the updates aws package:

```
   provider: "aws-s3",
      providerOptions: {
        baseUrl: `https://${env("AWS_BUCKET")}.${env("AWS_ENDPOINT")}`,
        endpoint: `https://${env("AWS_ENDPOINT")}`,
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: "us-east-1",
        params: {
          Bucket: env("AWS_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      }
```
where
```
AWS_ENDPOINT=fra1.digitaloceanspaces.com
AWS_BUCKET=bucketname
```
