### ISSUE TITLE
GraphQL Subscriptions

### ISSUE THREAD

**Issue by TokenChingy** [strapi/strapi#1877]
**What is the expected behavior?**

Feature request for adding support for creating GraphQL Subscriptions.

Once the mutations are tested and merged, it would be really nice to have subscriptions supported in the auto-generated shadow crud. This would save network resources as we wouldn't need to poll.

**Comment by kamalbennani** [comment]
I already have a working implementation based on the Mutation PR. I'd love to submit a PR for it once the mutation one is well tested + merged.
![image_720](https://user-images.githubusercontent.com/14129459/44957985-abe75180-aed9-11e8-956c-e5bfa4b25f61.png)

**Comment by TokenChingy** [comment]
Can I get access to the implementation?

**Comment by Aurelsicoko** [comment]
I've created a new card on Product Board (https://portal.productboard.com/strapi/c/45-graphql-subscriptions). Please upvote and share your insights through PB, I'm closing this issue.

**Comment by fakedob** [comment]
Checkout my PR #3165 for this feature. I also followed the mutation implementation and added shadowCRUD and policy checks

**Comment by AnirudhaGohokar** [comment]
Hey,
Can we define subscription in schema manually for a specific collection? Will it work if I just define it in `./api/*/config/schema.graphql`

**Comment by DennieMello** [comment]
Hello. Can we expect subscriptions to appear in the Database layer api v4?

**Comment by derrickmehaffy** [comment]
> Hello. Can we expect subscriptions to appear in the Database layer api v4?

Most likely not, but the database refactoring will be a step in the right direction. The database refresh is about a massive functional improvement to the database layer and not directly adding new features.
