### ISSUE TITLE
.cache folder, delete files inside instead of rm -rf the entire folder

### ISSUE THREAD

**Issue by migs35323** [strapi/strapi#18787]
### Required System information

 

- Node.js version: v18
- NPM version: yarn 1.22.19
- Strapi version: 4.15
- Database: mariadb
- Operating system: linux ubuntu lts
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am trying to build a strapi instalation in k8s
I would like to being able to edit the models on the UI so i am running in development mode.
However, by using strapi develop it tries to delete the .cache folder which i did mount as an emptydir or pvc and it's crashing the app.
can strapi delete just the contents of the folder instead the whole dir? 
or make it so we can customize where this folder is located?

### Steps to reproduce the behavior

1. .cache is a mount point or a directory that the app is not able to manage
2. strapi build -> error can't delete .cache folder

### Additional context

i believe this does not only apply to k8s or docker enviroments, 
maybe an user would like to make the .cache folder being a symlink for another location or mount it into ram/other fs for whatever reason (i know, very unlikely, but still..)

**Comment by joshuaellis** [comment]
We got rid of the cache folder in 4.15.4. I would upgrade.
