### ISSUE TITLE
Windows Strapi New Knex Issue

### ISSUE THREAD

**Issue by danielehrhardt** [strapi/strapi#1879]
![image](https://user-images.githubusercontent.com/19570043/44961820-9bee6280-af17-11e8-89fc-df0012f58a3b.png)

Node 9.11.1

Npm 6.4.1

Alpha 14

**Informations**
- **Node.js version**:
- **npm version**:
- **Strapi version**:
- **Database**:
- **Operating system**:

**What is the current behavior?**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Can you check @danielehrhardt if the strapi temp app has this module installed.
If you try again, does this issue still happening

**Comment by lauriejim** [comment]
@joseshiru you are with a Windows machine ?

**Comment by joseshiru** [comment]
@lauriejim 
Yeah, Windows 10 (64). 

With and without NVM, I've tried it with different versions of nodejs (from 8.11.4 to 10.9.0) and it always displays the same issue.

It happens with all the database engine options.

**Comment by ochanje210** [comment]
having same issue here..

**Comment by NickBolles** [comment]
This should be fixed by #1941

**Comment by NickBolles** [comment]
@joseshiru @danielehrhardt  @ochanje210  do you guys want to test this now that my PR is merged? let me know if this isn't fixed.

**Comment by danielehrhardt** [comment]
Thank you @NickBolles !!!

**Comment by ochanje210** [comment]
@NickBolles I have tested it and it works! 👍 Thanks!

**Comment by Xgamefactory** [comment]
have same issue with latest strapi and node v10
