### ISSUE TITLE
Package path ./admin/src/content-manager/hooks/usePluginsQueryParams is not exported from package.json

### ISSUE THREAD

**Issue by DaDlugosch** [strapi/strapi#18806]
### Required System information

- Node.js version: v18.16.1
- NPM version: 9.5.1
- Strapi version: 4.15.4 (but also reproducible on every version from 4.15.1 to 4.15.5-alpha.3)
- Yarn version: yarn/1.22.21
- Database: MySQL
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After upgrading packages I have installed Strapi through `yarn install` command and installation has been successful. But, when I tried to build Strapi through command `yarn build`, this error message appeared:

```bash
yarn run v1.22.21
$ strapi build
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (47.42908298969269ms)
⠋ Building admin panel
⠦ Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/hooks/usePluginsQueryParams is not exported from package /Users/iam/Sites/strapi-app/node_modules/@strapi/admin (see exports field in /Users/iam/Sites/strapi-app/node_modules/@strapi/admin/package.json)
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

and the Strapi has not been built. Can you please fix it, or help me to go through this? Thank you.
I also tried to completely remove `node_modules`, `yarn.lock` and `.cache` and install fresh packages again.

**Comment by nasraldin** [comment]
Also, I head the same issue.

**Comment by joshuaellis** [comment]
We are not planning to fix this, because we never supported importing internal hooks, components or utilities. In case you need it, please consider opening a feature request on [feedback.strapi.io](https://feedback.strapi.io/) explaining your usecase.

**Comment by nasraldin** [comment]
I have checked the installed plugins dependencies in package.json tried to remove some of them to see if there's any plugin use this issue and in my case found "strapi-plugin-duplicate-button": "1.1.13", cause this build error I just removed from dependencies and build the project successful.
