### ISSUE TITLE
Issue installing new plugins and generating the path to it in admin/client/app.js

### ISSUE THREAD

**Issue by kodi24fever** [strapi/strapi#18807]
### Required System information

- Node.js version: 20.9
- NPM version: 10.1
- Strapi version: 4.15.4
- Database: sqlite
- Operating system: Windows 11 X64
- Is your project Javascript or Typescript: javascript

### Describe the bug

After following all the steps to generate a new plugin, adding it to config.js, installing plugin modules, and running npm run build or npm run develop.
An error shows when creating admin after running npm run build or develop. The path generated in ./admin/client/app.js is not the path to the recently created plugin.

### Steps to reproduce the behavior

1. Install new strapi project using npm or npx
3. Generate plugin using npm run strapi generate
4. Select Javascript 
5. Add new plugin to config.js and enable it
6. Install modules in the local plugin folder
7. Run npm run build or npm run develop
8. See error

### Expected behavior

Strapi builds the admin with no issues and plugin can be seen in admin panel.

### Code snippets
```
PS C:\Users\user\Desktop\strappiapp> npm run develop

> strappiapp@0.1.0 develop
> strapi develop

- Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
√ Building build context (237.89919999986887ms)
- Creating admin[ERROR] Module not found: Error: Can't resolve '....srcplugins  odo/strapi-admin' in 'C:\Users\user\Desktop\strappiapp\.strapi\client'
[ERROR]  There seems to be an unexpected error, try again with --debug for more information
```

### Path created in app.js
```
/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import todo from "....srcplugins\todo/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "users-permissions": usersPermissions,
    i18n: i18N,
    "strapi-cloud": strapiCloud,
    todo: todo,
  },
});
```
### config.js file
```
module.exports = {
    // ...
    'todo': {
      enabled: true,
      resolve: './src/plugins/todo',
    },
    // ...
}
```

### Additional context

I tried this in an old strapi project and I also created a new version of it to test it with all the new updates and the result was the same. Also I generated a typescript plugin and build it in the local folder and the error persisted. It might be a path generating issue when generating app.js in admin/client folder.

**Comment by joshuaellis** [comment]
Would you be able to test against `4.15.5-alpha.4`? :)

**Comment by kodi24fever** [comment]
It is working for `4.15.5-alpha.4`,

### These are the dependencies
```
  "dependencies": {
    "@strapi/strapi": "4.15.5-alpha.4",
    "@strapi/plugin-users-permissions": "4.15.5-alpha.4",
    "@strapi/plugin-i18n": "4.15.5-alpha.4",
    "@strapi/plugin-cloud": "4.15.5-alpha.4",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
```
### Correct path in admin/client/app.js: import todo from "../../src/plugins/todo/strapi-admin";

Plugin is clearly showing in admin panel.

**Comment by joshuaellis** [comment]
I'm going to close this for now, as we've fixed it and it will be released in stable.

**Comment by LefBoutham** [comment]
> I'm going to close this for now, as we've fixed it and it will be released in stable.

Any estimates on next stable release date?

**Comment by derrickmehaffy** [comment]
> > I'm going to close this for now, as we've fixed it and it will be released in stable.
> 
> Any estimates on next stable release date?

We have a few more issues to solve before we can do a stable release: https://github.com/strapi/strapi/milestone/260
