### ISSUE TITLE
Strapi 4.15.4 missing directory @strapi/admin/admin/

### ISSUE THREAD

**Issue by adln** [strapi/strapi#18801]
### Required System information

- Node.js version: 18
- Strapi version: 4.15.4
- Database: sqlite
- Operating system: Linux, Windows
- Is your project Javascript or Typescript: JS

### Describe the bug

Strapi @v4.15.4 doesn't have the "@strapi/admin/admin/src/translations", I was trying to add a new language "fr" to /src/admin/app.js but it wasn't working, when i viewed the package of @strapi, there is no @strapi/admin/admin anymore

### Steps to reproduce the behavior

1. Go to 'node_modules'
2. Click on '@strapi'

**Comment by fabriciomelosilva** [comment]
I have the same problem, a collection only disappears when I delete the dist folder
