### ISSUE TITLE
after Update to node 18.8 and strapi v4.15.4 i cannot Build admin panel 

### ISSUE THREAD

**Issue by meganoob1337** [strapi/strapi#18826]
### Required System information

- Node.js version: 18.8
- NPM version: 9.8.1
- Strapi version: 4.15.4
- Database: PostgreSQL
- Operating system: Mac OS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After Updating to node 18.8 (because v16 was deprecated in 4.15? ) and strapi packages to 4.15.4
i get the following error while building:

⠸ Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/selectors/selectI18nLocales is not exported from package /Users/user/Projects/project/new/strapi-v4/node_modules/@strapi/plugin-i18n (see exports field in /Users/user/Projects/project/new/strapi-v4/node_modules/@strapi/plugin-i18n/package.json)

I saw some other issue about problems with languages or i18n in 4.15.4 , that should be fixed in 4.15.5 , is this something that would be fixed aswell?

im using locales 'en' and 'de' with 'de' beeing the default
### Steps to reproduce the behavior

Run strapi build.

### Expected behavior
it should build the admin panel

### Additional context
My Packages :

```json
"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@ckeditor/ckeditor5-markdown-gfm": "^36.0.0",
    "@ckeditor/ckeditor5-source-editing": "^36.0.0",
    "@ckeditor/ckeditor5-style": "^36.0.0",
    "@strapi/plugin-content-type-builder": "4.15.4",
    "@strapi/plugin-documentation": "4.15.4",
    "@strapi/plugin-i18n": "4.15.4",
    "@strapi/plugin-seo": "^1.7.4",
    "@strapi/plugin-users-permissions": "4.15.4",
    "@strapi/strapi": "4.15.4",
    "js-yaml": "^4.1.0",
    "minio-for-strapi-v4": "^1.0.7",
    "node-fetch": "2",
    "patch-package": "^7.0.0",
    "pg": "^8.7.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^5.2.0",
    "strapi-plugin-config-sync": "^1.0.3",
    "strapi-plugin-import-export-entries": "^1.18.0",
    "strapi-plugin-populate-deep": "^3.0.1",
    "strapi-plugin-translate": "^1.2.3",
    "strapi-plugin-website-builder": "^2.2.1",
    "strapi-provider-translate-deepl": "^1.1.11",
    "strapi-provider-translate-libretranslate": "^1.0.10",
    "styled-components": "^5.2.1"
  },
  ```

**Comment by Boegie19** [comment]
This is a issue with the `strapi-plugin-translate` please open a bug report on this plugin since it is not maintained by strapi.
