### ISSUE TITLE
TypeError: Cannot read property 'unique_email' of undefined

### ISSUE THREAD

**Issue by jrodriguesimg** [strapi/strapi#1882]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**:  5.6.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MySQL
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**

When registering a new user the server crashes:

```
TypeError: Cannot read property 'unique_email' of undefined
    at register (app/plugins/users-permissions/controllers/Auth.js:288:106)
    at <anonymous>
```

**Steps to reproduce the problem**

The request coded below will cause the error on the server.

```
fetch('https://<host>/auth/local/register', {
  body:"{\"username\":\"a@a.com\",\"email\":\"a@a.com\",\"password\":\"aa\"}",
  method: "POST",
  headers: {
    "Content-Type":"application/json"
  }
})
```

**What is the expected behavior?**

That the server successfully creates a new user.

**Suggested solutions**

--

**Comment by lauriejim** [comment]
Hello @jrodriguesimg thank you to report this issue.

**Comment by jrodriguesimg** [comment]
Well... with that fix the server does not have an internal error. Still the response is 400. How can I set loggers to show what's wrong with my request?

**Comment by jrodriguesimg** [comment]
Oh. The fetch was giving me an absurd response object. With Postman I got this:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Please provide your password."
}
```

As you can see in the postman window, I'm setting the password.

![wrong-password-postman](https://user-images.githubusercontent.com/39995657/44992306-c7f8fa80-af8e-11e8-92e2-28599c5743d5.png)

**Comment by jrodriguesimg** [comment]
@lauriejim I looked into the git blame for the line you changed. Before your fix, that code remained unchanged for 8 months. Some one must have tried to use the register by email since then. I'm I using the wrong release. Which version should I be using?

**Comment by jrodriguesimg** [comment]
@lauriejim do you know what might have caused the bug to me but not to others?

**Comment by lauriejim** [comment]
Did you migrate your app from older version ?
