### ISSUE TITLE
Queries are run in different way

### ISSUE THREAD

**Issue by andfk** [strapi/strapi#1883]
**Informations**
- Node v10.6.0
- NPM 6.1.0
- Strapi 3.0.0-alpha.14 (current tested) / 3.0.0-alpha.13 (tested too)
- Mongo v4.0.0
- Mac OSX 10.13.6

**Issue**
Trying to use any method from `mongoose` into model hook returns unexpected results. Running `Model.remove({ _id: model.id })` returns `{ n:0, ok:1 }` or `Model.findOne({ _id: model.id })` returns `null`. I wanted to confirm my queries were correct so i started strapi with `DEBUG=mquery*` and noticed the same queries are being run when i delete stuff from admin but there it works.

Log from model hook:
`mquery remove project { _id: 5b8d242c8ed455254a124969 } {} +12ms`

Log after deleting from admin:
`mquery remove project { _id: 5b8d242c8ed455254a124969 } {} +2ms`

**Steps to reproduce the problem**
in `afterCreate` hook of any model:
```
// After creating a value.
// Fired after an `insert` query.
afterCreate: async (model) => {
  const res = await Model.remove({ _id: model.id || model._id });
  console.log(res); // { n:0, ok: 1 }
}
```
**What is the expected behavior?**
All methods called from global model should run correctly.
```
// After creating a value.
// Fired after an `insert` query.
afterCreate: async (model) => {
  const res = await Model.remove({ _id: model.id || model._id });
  console.log(res); // { n:1, ok: 1 }
}
```

**Suggested solutions**
Still investigating this odd issue as the query looks exactly the same but dont get the reason why it works for admin by using `strapi.query().deleteOne()` and not `Model.deleteOne()` for example.

**Comment by lauriejim** [comment]
Hello @andfk , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by andfk** [comment]
Hi @lauriejim i can't remember 100% what was happening and maybe this has been already solved already so im going to close this and test later if this is still happening. Thanks
