### ISSUE TITLE
Relations pagination not working

### ISSUE THREAD

**Issue by TimoZikeli** [strapi/strapi#18842]
### Required System information

- Node.js version: 18.11.0
- NPM version: 0.39.3
- Strapi version: 4.15.4
- Database: MySQL
- Operating system: Ubuntu 20.04.3
- Is your project Javascript or Typescript: JS

### Describe the bug

When searching for entries in the relation dropdown in the content manager, **only one page is returned and repeated infinitely in the virtual scroll items.**

### Steps to reproduce the behavior

I have an entity `blog-entry`:
```
    "related_entries": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::blog-entry.blog-entry"
    }
```

1. Open the content manager, edit a blog entry and open the relation's select dropdown 
2. When there are 12 or more of those entries, only 10 are shown and repeated constantly via scrolling

The problem is the following – this HTTP request is sent: `/content-manager/relations/api::blog-entry.blog-entry/related_entries?entityId=2&pageSize=10&_q=&_filter=$startsWithi&page=2`

But the answer is:

```
{
    "results": [
...
    ],
    "pagination": {
        "page": 1, // ← -----THIS-----
        "pageSize": 10,
        "pageCount": 2,
        "total": 17
    }
}
```
...no matter what page parameter is set in the query. When I remove the `entityId` query param, the `page` param works. The `q` parameter does not work either – when searching for a specific blog entry which is not on the first page, I get no results.

### Expected behavior

All of the other entries should appear at some point. The page parameter in the query URL should not be ignored.

**Comment by Boegie19** [comment]
Look at the docs https://docs.strapi.io/dev-docs/api/rest/sort-pagination#pagination you forgot to add the pagination object before pages. aka it should be ?pagination[page]=1&pagination[pageSize]=10

**Comment by TimoZikeli** [comment]
Sorry, this was my mistake. Had a proxy that removed the `page` query param... 🤣
