### ISSUE TITLE
Build pipeline changed

### ISSUE THREAD

**Issue by TriPSs** [strapi/strapi#18848]
Hi, I'm the maintainer of @nx-extend/strapi, an package that makes it possible to use Strapi within a NX workspace, since version 4.15.1 (PR #18539) the complete build pipeline is changed for the admin panel causing our package to no longer work. When checking the new code I also see a lot of messages like this:
```
the build api exported from this package is now deprecated. We don't plan to expose this for public consumption and this will be removed in V5.
```

Is there a way for us, like we had on v4.15.0 and prior to keep building the admin panel? We cannot use the normal `strapi build` command as we need the input (and output) directory to be placed on different places (See our current [implementation here](https://github.com/TriPSs/nx-extend/blob/master/packages/strapi/src/executors/build/build.impl.ts)).

**Comment by joshuaellis** [comment]
Thanks for your questions. I think it's important we understand the why's a bit more around this, can you elaborate on:

> we need the input (and output) directory to be placed on different places

please?

Some thoughts on the implementation: 
* your `tsUtils.compile` might not be necessary since the build command of the admin runs this internally. 
* You're also importing from `'@strapi/strapi/dist/commands/builders/admin'` which we don't support so this was _very_ likely to break at some point...

A short answer to your question

> Is there a way for us, like we had on v4.15.0 and prior to keep building the admin panel?

would be not really. But that doesn't mean there's not a more future proof way to handle what your package is trying to achieve, I just don't fully understand it all at the moment :)

**Comment by TriPSs** [comment]
Within the plugin it's possible for the users to define where there there Strapi project is located, so for example `/apps/cms`, if I look at the code of the new builders `process.cwd()` is always used which is an issue since the root of the project is never where the code ls; now that could be solved by executing the build command inside the root of that app but this will not solve the case where users use the same code for multiple CMS, example: `apps/cms-one` and `apps-cms-two` both use `apps/cms` as root directory but with a different output directory, so for that we still need to be able to customise the output directory.

> * You're also importing from `'@strapi/strapi/dist/commands/builders/admin'` which we don't support so this was _very_ likely to break at some point...

Correct, I updated this already multiple times to keep working, which on it's own is not necessarily an issue but it looks like when I want to update now to the new builders I'm not allowed to import them as they are not inside the `exports` of the package.json, also some things are not exported at all.

I think, now looking at it all, we could solve all issues by adding `--outputDir` to the `strapi build` command, that way we can keep adjust the build executor to be the same again as the [serve one ](https://github.com/TriPSs/nx-extend/blob/master/packages/strapi/src/executors/serve/serve.impl.ts#L30-L41)

**Comment by joshuaellis** [comment]
> I think, now looking at it all, we could solve all issues by adding --outputDir to the strapi build command, that way we can adjust the build executor to be the same again as the serve one

I'd also propose you use the build command from the admin package, you can import it like:

```ts
import { build as nodeBuild } from '@strapi/admin/cli'
```

You can pass a custom `cwd` that way. But you will be expected to pass a `logger` and optionally (but i'd recommend it) a tsconfig see:

https://github.com/strapi/strapi/blob/e741a4a0c03191c45777bd1c92a0f1861299e521/packages/core/admin/_internal/node/build.ts#L12

This would give you a lot more control

For the output we load their strapi instance and check the `dirs.dist.root` property and append `build`. Are you trying to overwrite the `build` part or the `dirs.dist.root`? Is there a reason people aren't setting these in their projects?

**Comment by TriPSs** [comment]
> > I think, now looking at it all, we could solve all issues by adding --outputDir to the strapi build command, that way we can adjust the build executor to be the same again as the serve one
> 
> I'd also propose you use the build command from the admin package, you can import it like:
> 
> ```ts
> import { build as nodeBuild } from '@strapi/admin/cli'
> ```

I actually tried to use that one (but than the `@strapi/admin/dist/cli` as `@strapi/admin/cli` does not exist) but that is when I got this error:
```
Package subpath './dist/cli' is not defined by "exports"
```

**Comment by TriPSs** [comment]
> For the output we load their strapi instance and check the `dirs.dist.root` property and append `build`. Are you trying to overwrite the `build` part or the `dirs.dist.root`? Is there a reason people aren't setting these in their projects?

Could you elaborate a bit? Where would I configure `dirst.dist.root`?

**Comment by TriPSs** [comment]
Okay If I just ignore that error from the import and follow what is [being done here](https://github.com/strapi/strapi/blob/a1c8cbb8a8e03dae8cfd464ff586b8bd49e342fc/packages/core/admin/index.js) the build is working except that it keeps trying to load the app.js from the root.

```
Module not found: Error: Can't resolve './.strapi/client/app.js' in 'root of project'
```

**Comment by joshuaellis** [comment]
`@strapi/admin/cli` doesn't have types due to circular dependencies so your IDE will say it's not there. I would use this over accessing dist.

> Where would I configure dirst.dist.root? Or do you mean the outDir inside the tsconfig.json?

If a user is using a TS project we should load the TS config and pass it to the admin's build command. Otherwise you can configure where the dist folder is (this will contain the `build` folder from the admin command) in a strapi configuration – https://docs.strapi.io/dev-docs/configurations/server#available-options (I can't like to rows in the table)

> after digging in the core I noticed that the original build creates a [Strapi instance](https://github.com/strapi/strapi/blob/a1c8cbb8a8e03dae8cfd464ff586b8bd49e342fc/packages/core/admin/index.js#L130), but this one is not passed to the createBuildContext and in there it always generates a new one. 

That's because some commands generate a strapi instance and strapi is used as a global at the moment unfortunately, so we check if `strapi` is in the global scope and use that instead.

> the build is working except that it keeps trying to load the app.js from the root.

There's not enough information for me to help you with this, but it needs to create a runtime directory _somewhere_ in the project so it can access it.

**Comment by TriPSs** [comment]
> If a user is using a TS project we should load the TS config and pass it to the admin's build command. Otherwise you can configure where the dist folder is (this will contain the build folder from the admin command) in a strapi configuration – https://docs.strapi.io/dev-docs/configurations/server#available-options (I can't like to rows in the table)

If I where to set `dirs.dist.root` and log the strapi instance that is being created it looks like that value is being overwritten.

> > after digging in the core I noticed that the original build creates a [Strapi instance](https://github.com/strapi/strapi/blob/a1c8cbb8a8e03dae8cfd464ff586b8bd49e342fc/packages/core/admin/index.js#L130), but this one is not passed to the createBuildContext and in there it always generates a new one.
> 
> That's because some commands generate a strapi instance and strapi is used as a global at the moment unfortunately, so we check if `strapi` is in the global scope and use that instead.

Sorry, the code from `createBuildContext` what i meant was [this one](https://github.com/strapi/strapi/blob/develop/packages/core/admin/_internal/node/createBuildContext.ts#L95), strapi could be passed down but never is, therefore it always creates a new one.


> > the build is working except that it keeps trying to load the app.js from the root.
> 
> There's not enough information for me to help you with this, but it needs to create a runtime directory _somewhere_ in the project so it can access it.

When I change the implementation to the following, and update that `strapi` is passed down to `createBuildContext`:
```ts
const strapiInstance = strapi({
    // Directories
    appDir: strapiRoot,
    distDir,
    // Options
    autoReload: false,
    serveAdminPanel: false
  })

  const tsConfig = loadTsConfig({
    cwd: strapiRoot,
    logger,
    path: options.tsConfig
  })

  tsConfig.config.options.rootDir = strapiRoot
  tsConfig.config.options.outDir = distDir

  await nodeBuild({
    ignorePrompts: true,
    minify: Boolean(options.production),
    cwd: process.cwd(),
    tsConfig,
    logger,
    strapi: strapiInstance
  })
```

I have a working admin (besides that it still creates a `.strapi` in the root), this does not build the server (api/components etc) though.

**Comment by TriPSs** [comment]
Thanks for your @joshuaellis, looks like I have a working version again by also modifying the webpack config of the admin panel!

**Comment by joshuaellis** [comment]
Feel free to tag me in the PR and i can give it a read over and highlight any concerns just so you know them :)

**Comment by zapplebee** [comment]
> Is there a way for us, like we had on v4.15.0 and prior to keep building the admin panel?

This feels like a pretty breaking change here.

We also use the webpack configuration to alias some of the Strapi internal components and replace them with some custom versions for our application. The prebuilt admin package is a pretty fundamental change to the system.

Looking at the actual admin module, it seems that the actual FE source is no longer included, just what is pre-bundled, meaning that it doesn't seem that even an escape hatch to rebuild it ourselves would work. Am I understanding correctly?

**Comment by joshuaellis** [comment]
Editing our source code like that was never something we supported. This is the same as users importing components from the src folder either because you were relying on the exact paths of our source code.
