### ISSUE TITLE
   /upload/files?sort=createdAt:DESC&page=1&pageSize=10&filters[$and][0][folderPath][$eq]=/ 403 (Forbidden)

### ISSUE THREAD

**Issue by hsnbsst** [strapi/strapi#18843]
## Bug report
   /upload/files?sort=createdAt:DESC&page=1&pageSize=10&filters[$and][0][folderPath][$eq]=/ 403 (Forbidden)
### Required System information

- Node.js version: v18.18.2
- NPM version:9.8.1
- Strapi version:4.15.4
- Database: mysql
- Operating system: ubuntu 20
- Is your project Javascript or TypeScript:Javascript?

### Explain the error

It connects to the media library on the local server, but the console does not open on the server and the following error occurs: /upload/files?sort=createdAt:DESC&page=1&pageSize=10&filters[$and][0][folderPath][$eq]=/ 403 (Forbidden)

Normally, it shows updates etc. on sites through the API, but it also accesses other parts of the panel, just not there.

### Steps to reproduce behavior

I booted the whole system normally

### Expected behavior

opening

### Screenshots

![Ekran Resmi 2023-11-19 09 56 16](https://github.com/strapi/strapi/assets/25246736/56ba4c4f-b57f-46cc-9f4b-ad3252b81abe)

### Code snippets

--
### Additional context

---

**Comment by GoNiazi** [comment]
It seems like you are suggesting that there might be an issue with permissions in roles, specifically related to the upload plugin
<img width="785" alt="Screenshot 2023-11-22 102228" src="https://github.com/strapi/strapi/assets/64166117/0be38be1-6162-4360-8e7c-a8b2a7efcde5">

**Comment by hsnbsst** [comment]
I found the problem. It caused this problem when the modsecurity feature and fileban feature of the Plesk panel were turned on. When I turned it off, the problem was solved.****
