### ISSUE TITLE
Installing Alpha with create-strapi-app@alpha fails, because of peerDependencies.

### ISSUE THREAD

**Issue by Yaren-IT** [strapi/strapi#18847]
## Bug report
Installation is unable to resolve dependency tree, because of unproper version in this [line](https://github.com/strapi/strapi/blob/6a4fcc93af2f8955e8f981da3d264561253f2a3b/packages/plugins/users-permissions/package.json#L84).

### Steps to reproduce the behavior

1. Install strapi with `npx create-strapi-app@alpha backend`
2. `cd backend`
3. `npm i`

### Additional context

Should be gone if the refered line changes to something like following:
`    "@strapi/strapi": "4.15.5-alpha.4",`

**Comment by derrickmehaffy** [comment]
We don't provide support for Alpha releases as they are only for testing.
