### ISSUE TITLE
Deleting collection items does not delete their relations to a file in files_related_morphs table

### ISSUE THREAD

**Issue by vkurlyan** [strapi/strapi#18856]
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.8.2
- Strapi plugin-upload version: 4.8.2
- Database: postgres (PostgreSQL) 14.5
- Operating system: MacOS 10.13.6
- Is your project Javascript or Typescript: JS

### Describe the bug

Deleting collection items does not delete their relations to file in files_related_morphs table.

### Steps to reproduce the behavior

1. Go to Strapi Admin -> Content Manager
2. Select a collection which has an item with an image assigned.
3. Select and delete this item/items on "entries list page". The same would be if you delete an item with Strapi DB api: strapi.db.query(...).deleteMany(...)
4. View files_related_morphs table in DB. It still has relations from files to the deleted items.

### Expected behavior

File-item relations should be removed in files_related_morphs table when items are removed.

### Additional context

Usually, It should not be a big problem, because a new item in a collection would be created with a new incremented ID. But somehow in my case, new IDs got reset, probably after restoring DB from a dump. And newly created items in the collection got wrong images from old deleted items.

Update: Issue does not happen if you delete 1 item on "Edit entry" page, only when deleting it on "entries list" page.

**Comment by derrickmehaffy** [comment]
Cascade deleting must not be working but needs to be reproduced :thinking:

**Comment by GoNiazi** [comment]
strapi.db.query(...).deleteMany(...) only deletes the records but not their relations, so you might have to use entity.service

**Comment by vkurlyan** [comment]
I tested it again, strapi.db.query(...).deleteMany(...) deletes relation records in all related `*_links` tables. Only files_related_morphs stays untouched.

**Comment by derrickmehaffy** [comment]
Can you please test with the entityService, no one should really be using the query engine if you can avoid it.

**Comment by hanpaine** [comment]
Hi @vkurlyan please may you confirm if this is still an issue you are encountering? Have you tried testing with the Entity Service too? Or the Document Service on Strapi 5, if you have upgraded

**Comment by vkurlyan** [comment]
Hi @hanpaine, sorry, I won't have time for this
