### ISSUE TITLE
Media library incorrect folder permissions

### ISSUE THREAD

**Issue by afonsobspinto** [strapi/strapi#18851]
Environment: development
OS: linux-x64
Strapi Version: 4.15.4
Node/Yarn Version: npm/10.1.0 node/v20.8.0 linux x64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

An author user seems to be able to view and delete a folder created by a super admin / editor user, even tho author permissions are set to deny that.

### Steps to reproduce the behavior

1. Start a new project from scratch with `npx create-strapi-app my-project --quickstart`
2. Add a folder in the media library using a super admin or editor role.
3. Login in with an author role, visit the media library page and delete the folder.

### Expected behavior

The author role should not be able to see the folder created by the super admin or at least not be able to delete it.

### Screenshots

https://github.com/strapi/strapi/assets/19196034/2ae01dd6-2399-4df6-adb5-bae5630602ba

**Comment by derrickmehaffy** [comment]
Currently the media library and folders within it do not have advanced RBAC controls.

**Comment by afonsobspinto** [comment]
Thanks for the reply @derrickmehaffy .

I wouldn't say that the media library doesn't have role base access controls because it does as you can see in the following video:

https://github.com/strapi/strapi/assets/19196034/d6fbf34f-a91a-40d4-8a22-6e809f3974fc

The problem is that those controls doesn't seem to apply to folders and that's the issue I'm reporting

**Comment by derrickmehaffy** [comment]
Yeah it's something we are aware of but not a bug per say: https://feedback.strapi.io/feature-requests/p/permission-management-for-media-library-folders
