### ISSUE TITLE
auth/user not returning images/media

### ISSUE THREAD

**Issue by gkarmas** [strapi/strapi#1886]
Hello and thank you for the great work.
I have the following problem when trying to get images from "user"

Everything else returns, but media/images.

![user 2018-09-03 13-10-28](https://user-images.githubusercontent.com/8575682/44997504-d0483a00-af7c-11e8-92dd-71f7e0e08a1e.png)

![users js lensexec 2018-09-03 12-30-47](https://user-images.githubusercontent.com/8575682/44997501-ce7e7680-af7c-11e8-9702-0aa68b3016fd.png)

**Comment by lauriejim** [comment]
Hello @gkarmas , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

**Comment by gkarmas** [comment]
Sorry @lauriejim 

**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: v3.0.0-alpha.14
- **Database**: mongo
- **Operating system**: CentOS Linux 7 (core) 


**What is the current behavior?**
Simple object without using graphql on strapi, does not return anything else but string objects ! Is it a vuex problem? Everything works fine when using graphql and calling an array but I have to call the user data twice since i am already authenticating the user via object. seems like the object doesn't load anything with sub-arrays.


**Steps to reproduce the problem**
I tried to call the object via multiple vuex projects, user array doesn't return anything but string objects.



**What is the expected behavior?**
![lensexec - corporate photography 2018-09-06 21-46-34](https://user-images.githubusercontent.com/8575682/45194430-00176c00-b221-11e8-8ceb-41d755239d28.png)


**Suggested solutions**
I have nothing in mind, i tried everything I could think of.

**Comment by lauriejim** [comment]
My default Strapi has one populating level, then it will give you id of the entity.
Check populate/deepPopulate on mongoose for more information.
Related issue here https://github.com/strapi/strapi/issues/1783

**Comment by gianniskarmas** [comment]
I also have this question and know how to do this for other collections (populate etc) but what is the suggested way for adding an image directly in the Users? How can we read it back directly?

**Comment by gkarmas** [comment]
@lauriejim thank you for the response. No, strapi does populate multiple levels for all custom items BUT users. I don't understand the reason why strapi is granting full multiple level access to graphql plugin and strapi's internal api but not direct object calls to strapi's sdk. Thanks for your great work and support.

**Comment by lauriejim** [comment]
@gkarmas A good thing to add is a config to manage how many levels can be handled by default.

**Comment by gkarmas** [comment]
thank you so much @lauriejim  - I would need a bit of guidance on how to achieve that. I tried multiple times and couldn't figure it out. Any help would be much appreciated. I am struggling with this very issue for a while.

**Comment by gkarmas** [comment]
I just did [https://github.com/strapi/strapi/issues/1980](url) thanks @lauriejim
