### ISSUE TITLE
Problems with building extending webpack config for running scss compiler in plugins

### ISSUE THREAD

**Issue by lau1961** [strapi/strapi#18865]
### Required System information

- Node.js version: 18
- NPM version: using yarn
- Strapi version: 4.15.
- Database: mysql
- Operating system: mac osx
- Is your project Javascript or Typescript: Javascript

### Expected behavior
To not get these errors and webpack compiles correctly.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by xandervandijck** [comment]
Bump

**Comment by kevinvugts** [comment]
@derrickmehaffy could you elaborate more on this open issue? It happens to me as well.
