### ISSUE TITLE
The policies are not executed in my GraphQL custom schema

### ISSUE THREAD

**Issue by jrperdomoz** [strapi/strapi#1887]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: mongo:4.0.1
- **Operating system**: OSX 10.13.6

**What is the current behavior?**
The policies are not executed in my graphql custom schema

**Steps to reproduce the problem**
This is my schema.graphql into api/contacts/config/
```js
module.exports = {
  definition: `
    type Contacts {
      count: Int!
      rows: [Contact]!
    }
  `,
  query: `
    _contacts(sort: String, limit: Int, start: Int, where: JSON): Contacts
  `,
  resolver: {
    Query: {
      _contacts: {
        description: `Contacts`,
        policy: ['plugins.users-permissions.isAuthenticated'],  // <-------
        resolver: async (obj, options, ctx) => {
          let params = {
            _limit: options.limit ? options.limit : 10,
            _sort: options.sort ? options.sort : '',
            _start: options.start ? options.start : 0
          }

          if ( options.where ) {
            params = Object.assign(params, { ...options.where })
          }

          const rows = await strapi.services.contact.fetchAll(params);
          const count = await strapi.services.contact.count(params);
          return { count, rows };
        }
      }
    }
  }
};
```

**What is the expected behavior?**
The policy executed

**Suggested solutions**

**Comment by kamalbennani** [comment]
Rename the property to policies instead of policy.

**Comment by jrperdomoz** [comment]
@kamalbennani I have already tried doing this before opening the issue. I'm also following the documentation: https://strapi.io/documentation/guides/graphql.html#execute-a-policy-before-a-resolve

**Comment by jrperdomoz** [comment]
I can see that the strapi-plugin-graphql/services/Graphql.js service look up the property "policies" and not "polity", but it does not work anyway.

https://github.com/strapi/strapi/blob/fa94519c1d6a4daba2ed5238afc1060e97f47ea1/packages/strapi-plugin-graphql/services/GraphQL.js#L695

**Comment by kamalbennani** [comment]
That's weird, normally it should work :thinking: I think that you need to keep this issue open

**Comment by kamalbennani** [comment]
I probably know why it's doing that, I'll submit a PR to fix it :+1:

**Comment by jrperdomoz** [comment]
The local resolve of the "schema.graphql" is not preceded by the policies.

**Comment by Aurelsicoko** [comment]
@jrperdomoz Good catch! Thank you for sharing the alternative solution but it's still an issue and we need to fix it.

**Comment by greatwitenorth** [comment]
Just wondering the status on this issue. I did a bit of digging and it appears as though the `queryName` is always set to the model name. This means that if someone creates a custom query, then the policy code referenced here:

https://github.com/strapi/strapi/blob/fa94519c1d6a4daba2ed5238afc1060e97f47ea1/packages/strapi-plugin-graphql/services/GraphQL.js#L695

will never find the policy for the custom query. Still unsure of how to fix this though.

**Comment by nikosolihin** [comment]
I found that custom resolvers like `'Promotion.send'` remains a string during schema generation and never points to an actual controller function because `queryName` always includes the variable `action` which in the case of custom resolvers is undefined: 

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L40

This affects policies(#1887) and resolver function retrieval(#2766):

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L43

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L57

The fix is a simple conditional based on the presence of `action`:
```const queryName = action ? `${action}${_.capitalize(name)}` : `${name}`;```

**Comment by lauriejim** [comment]
Thank you @nikosolihin !
Can you submit a PR to let us review that point.

**Comment by canhkieu** [comment]
It's not working again. ( working on: strapi: 3.0.0-beta.18.4, strapi-plugin-graphql: 3.0.0-beta.18.4 )

```
error Ignored attempt to bind to GraphQL query "comments" with unknown policy "isOwner"
```

**api\comment\config\policies\isOwner.js**
```
module.exports = async (ctx, next, args) => {
  console.log("Enter isOwner");
  await next();
};
```

**api\comment\config\schema.graphql.js**
```
module.exports = {
  resolver: {
    Query: {
      comments: {
        description: "get comments",
        policies: [
          "plugins.users-permissions.isAuthenticated",
          "isOwner"
        ],
        resolver: "Comment.index"
      }
    }
  }
};
```

**api\comment\controllers\comment.js**
```
module.exports = {
  index: async ctx => {  
    return await strapi.services.comment.find();
  }
};
```

**Comment by alexandrebodin** [comment]
@canhkieu This is not the same issue. Can you please open a new one :)

**Comment by centogram** [comment]
@canhkieu I have same issue you're describing on beta.18.6 .  Custom local policy works well on routes but are not being called with graphql.  Documentation on routes has key as policies and in scheme as policy even trying both still custom policy is not being entered.  Did you open a new ticket somewhere?
