### ISSUE TITLE
V4.15.4 developing plugins

### ISSUE THREAD

**Issue by cihanSrb** [strapi/strapi#18872]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.15.4
- Database: PostgreSQL
- Operating system: Win 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am entering the plugin path in the "./config/plugins.ts" file as specified in the documentation. During the build process, I am encountering an error in the ".strapi/client/app.js" file.

./config/plugins.ts
```
export default {
  'test': {
    enabled: true,
    resolve: './src/plugins/test'
  },
}
```

## It is incorrectly adding the plugin path here.
.strapi/client/app.js
```
/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import test from "....srcplugins\test/strapi-admin";  //incorrecct path
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "users-permissions": usersPermissions,
    i18n: i18N,
    test: test,
  },
});
```

**Comment by cohenAlberic** [comment]
Hi! It seems that this issue is linked only to Windows 11 as we tried on MacOs, Unix and Windows 11 and only the latter got the problem.

**Comment by joshuaellis** [comment]
This was solved and released in an alpha, i'd encourage you to test `4.15.5-alpha.5`
