### ISSUE TITLE
Unable to change theme

### ISSUE THREAD

**Issue by monolithed** [strapi/strapi#18878]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.15.4
- Database: sqlite
- Operating system: macOS Sonoma, 14
- Is your project Javascript or Typescript: Typescript and Javascript

### Describe the bug

https://github.com/strapi/strapi/assets/803674/d9b60154-0253-4583-a476-7425349fd261

### Steps to reproduce the behavior

1. Go to 'admin/me'
2. Click on 'Interface mode'
3. Select 'Light mode'

### Expected behavior

The interface shouldn't hang

**Comment by joshuaellis** [comment]
This issue has been fixed in #18789 but not yet release – the latest alpha should work for you.
