### ISSUE TITLE
Users-Permissions Plugin sanitization breaking change for private attributes (> v4.13.x )

### ISSUE THREAD

**Issue by hellerdejanuar** [strapi/strapi#18876]
## Bug report

Since version 4.13.x the Users-Permissions plugin seems to be implementing a new sanitization routine that removes the fields tagged as "Private" before creating the requested User Entity. 

This bug seems to be present in every update since 4.13.2 and works fine in 4.12.5.

This is not an issue with custom entities.

### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version:  4.13.2 > 4.15.4
- Database: Postgres
- Operating system: MacOs Monterrey
- Is your project Javascript or Typescript: Javascript

### Describe the bug

No private fields ever gets to the user's CreateEntity function, when sent through the RestAPI. 

### Steps to reproduce the behavior

1. To reproduce the bug create a new project, 
2. add a text field to User and mark it as Private. 
3. When trying to create a new User from RestAPI, and sending the field as part of the request the field gets deleted before creating the new User. 
4. This is especially bad for Required AND private attributes, that block the creation of users altogether.

**Comment by hellerdejanuar** [comment]
Am I the only one with this error?

**Comment by derrickmehaffy** [comment]
Yes it was a breaking change but an unavoidable one as it was a security risk. We added an option in the users-permissions config that allows you to configure what fields can be set during registration but private fields are forcefully excluded from these.
