### ISSUE TITLE
Wrong count for users in admin panel

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1888]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: .6.2.0
- **Strapi version**: alpha 13.1
- **Database**: **pg**
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**

The count for users on the overview is wrong. This is probably a problem with bookshelf/mysql/postgres.

![image](https://user-images.githubusercontent.com/2950505/45014955-79943c00-b020-11e8-85fe-9a4ace7b6547.png)

This is especially meaningless for guests.

**However**

If I click on detail view, I get only one user: 

![image](https://user-images.githubusercontent.com/2950505/45015461-12778700-b022-11e8-9001-8bf4291f9357.png)

Now if I add the user instead to `admin` instead of authenticated, the overview just shows the total amount of globally existing users, but not per role.

**Steps to reproduce the problem**

- create a second user
- check overview

**What is the expected behavior?**

- show 1 for guest - always
- show 1 for authenticated
- show 1 for admins

**Suggested solutions**

Is there something wrong with the `count` function/rest call in pg/mysql? that is where I would first investigate.

**Comment by MartinMuzatko** [comment]
When I have time, I will look into it :)

**Comment by MartinMuzatko** [comment]
Can someone confirm that this behavior only appears on mysql/pg installations?

**Comment by soupette** [comment]
@MartinMuzatko I'm wondering how you managed to access the `administrator` role edit view it's supposed to not be available...

**Comment by derrickmehaffy** [comment]
@soupette It is easy, click on another role and then change the ID to 1 instead of 2 or 3 :stuck_out_tongue: 

`http://localhost:1337/admin/plugins/users-permissions/roles/edit/1

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/45042138-ddb60080-b01e-11e8-9d78-d3ced7dafa5f.png)

**Comment by soupette** [comment]
@MartinMuzatko regarding the original issue is this still happening because it's working as expected on my projects

**Comment by derrickmehaffy** [comment]
@soupette can confirm the issue still happens on v19/v21 with MySQL: 
![image](https://user-images.githubusercontent.com/8593673/52256931-d2207b80-28d5-11e9-895b-c8ba8c58d38c.png)

**Comment by lauriejim** [comment]
Ho yes no surprise, we didn't worked on it.

**Comment by derrickmehaffy** [comment]
@lauriejim no big, just saw the last update was quite a while ago. and @soupette said he couldn't reproduce. likely an issue with bookshelf DBs 

(I also saw it on the project as a quick fix, so figured I'd confirm it)

**Comment by Nyeedz** [comment]
i'm having this same issue on MongoDB to
