### ISSUE TITLE
When deleting fields in the collection, they are also removed in the components.

### ISSUE THREAD

**Issue by monolithed** [strapi/strapi#18880]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.15.4
- Database: sqlite
- Operating system: macOS Sonoma, 14
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When deleting fields in a collection, they are also removed in the components. 
I'm not sure if this is a bug or a feature, but this behavior is definitely non-obvious and unsafe.

https://github.com/strapi/strapi/assets/803674/8b49228f-f621-4987-96c9-1a615db5ffbe

**Comment by Boegie19** [comment]
Expected behavoir since everyting inside of a component is global the reason it is done this way is to allow for easy changes witout having to switch screens
