### ISSUE TITLE
Strapi removes database tables, breaking permissions plugin

### ISSUE THREAD

**Issue by Pixfloage** [strapi/strapi#18893]
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.14.3
- Database: Postgres 14
- Operating system: 
- Is your project Javascript or Typescript: TS

### Describe the bug
This never happened before, but after some innocent content type changes, Strapi removes 5 cardinal database tables namely:
`up_permissions` `up_permissions_role_links` `up_roles` `up_users` and `up_users_role_links` 
This causes API breaks, no Media Library, Content-Type Builder or Plugin settings are available. Restored the databases many times to test safely with a forked version and every time it breaks the DB on startup. Tried removing `strapi_database_schema` to regenerate the missing tables but it ignores these 5 tables. 
We didn't "touch" Strapi for a while now, before we upgraded from 4.9.0 to 4.14.3 but this issue didn't come up. The only change I did was to introduce some new types and changed one existing type. No error logs, Strapi is able to start up as usual, but with missing pages as I mentioned above. 

What's more interesting, that when I run `strapi ts:generate-types` I see that it removes `PluginI18NLocale` `PluginUsersPermissionsPermission` `PluginUsersPermissionsRole` `PluginUsersPermissionsUser` so seems like it's getting rid of these plugins but why? 

If I checkout a previous commit, Strapi regenerates the missing tables correctly if I delete the `strapi_database_schema`  table first. It also breaks a brand new fresh database as well as existing ones. 

### Steps to reproduce the behavior

1. I don't have exact repro steps, only in my use case and the only thing I did was an update to a couple of content types

### Expected behavior

Obviously Strapi shouldn't touch unrelated database schemas, especially not permission plugin related ones. 

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Pixfloage** [comment]
If I log the database with `debug: true` I literally see this along the logs
```
[ { sql: 'drop table if exists "i18n_locale"', bindings: [] } ]
[ { sql: 'drop table if exists "up_permissions"', bindings: [] } ]
[ { sql: 'drop table if exists "up_roles"', bindings: [] } ]
[ { sql: 'drop table if exists "up_users"', bindings: [] } ]
[

**Comment by Pixfloage** [comment]
Upgrading to Strapi version 4.15.4 solved this issue, the missing tables are regenerating. I'm not seeing anything like this in the changelog, but I'm glad it's sorted out!

**Comment by derrickmehaffy** [comment]
Will close since this is solved but probably was due to a bug causing Strapi not to see the plugins. How you got it to boot is a mystery 😨 be either way should be solved.
