### ISSUE TITLE
Strapi generate broken path to plugin

### ISSUE THREAD

**Issue by greatUzumaki** [strapi/strapi#18895]
### Required System information

- Node.js version: v18.18.2 
- NPM version: 8.4.1
- Strapi version: 4.15.4
- Operating system: Windows
- JS

## Description

When starting Strapi dev, an error appears stating that strapi cannot determine the path to the plugin, although such a path is indicated in the file app.js
Error:
```
[ERROR] Module not found: Error: Can't resolve '....srcplugins   est/strapi-admin' in 'D:\Projects\strapi\.strapi\client'
```
.strapi/client/app.js:
```
import test from "....srcplugins\test/strapi-admin";
```

but in file config/plugins.js i have this:
```
...
  test: {
    enabled: true,
    resolve: "./src/plugins/test",
  },
  ...
```

**Comment by joshuaellis** [comment]
Please try out `4.15.5-alpha.5`, this issue should have been resolved there.
