### ISSUE TITLE
Unable to add a new component for Dynamic zone

### ISSUE THREAD

**Issue by monolithed** [strapi/strapi#18892]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.15.4
- Database: sqlite
- Operating system: macOS Sonoma, 14
- Is your project Javascript or Typescript: Javascript and TypeScript

### Describe the bug

I tried installing a clean build both in JS and TS, and the behavior is identical:

https://github.com/strapi/strapi/assets/803674/56c03285-2fdc-4a62-bff7-9e04ab422c83

After clicking on 'Add a component,' a blank page is displayed. Physically, the user remains on the same page, but its content becomes empty.

**Comment by misterboe** [comment]
Same here

**Comment by wizzer711** [comment]
Also having the exact same issue with same error, running strapi verison v4.15.0

**Comment by joshuaellis** [comment]
> Downgrading react-router-dom package from ^6.x.x to ^5.2.x fixed this issue for me.

We don't support react-router-dom@6 so that would make some sense.

However, overall this issue *was* solved in `4.15.5`.

**Comment by joshuaellis** [comment]
we don't support react-router-dom 6, i would not use it. If you can reproduce the error without using that library then we can investigate further.
