### ISSUE TITLE
downgrade nodejs

### ISSUE THREAD

**Issue by zhoub** [strapi/strapi#189]
**Node.js version**:
7.7.1
**npm version**:
4.1.2
**Strapi version**:
1.5.5
**Operating system**:
OSX 10.12.3

Sorry I have this issue on 1.5.5, installed the nodejs from brew.

```
warn: Oups..., we cannot start the server.
warn: Your Node.js version is greater than 4.8.0.
warn: Please use downgrade your Node.js version.
```

**Comment by sbacem** [comment]
Prerequisites
Strapi needs node.js 4.0 to run. Newer node.js versions will be supported in the upcoming Strapi 3.0
[http://strapi.io/documentation](http://strapi.io/documentation)

**Comment by Aurelsicoko** [comment]
Thanks @sbacem for your perfect answer. @zhoub as the logs tell you, you have to downgrade to Node >= 4.8.0 to use Strapi v1.5.5.

I close the issue.

**Comment by pierreburgy** [comment]
@zhoub @sbacem Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
