### ISSUE TITLE
Admin panel - Roles and permissions don't seem to apply for child entities

### ISSUE THREAD

**Issue by afgallo** [strapi/strapi#18900]
## Bug report

Permissions should apply to related entities in administrator panel

### Required System information

- Node.js version: **18.18.2**
- NPM version: **10.2.4**
- Strapi version: **v4.14.5**
- Database: **postgres**
- Operating system: **MacOS**
- Is your project Javascript or Typescript: **Javascript**

### Describe the bug

We are evaluating the security model of the [administrator panel](https://docs.strapi.io/user-docs/users-roles-permissions/configuring-administrator-roles). Here is our use case for setting up roles & permissions:
1. Super Admin - Super Admins can access and manage all features and settings.
2. Joe Doe - Content manager from Company A - Only manages content for company A
3. Jane Smith - Content manager from Company B - Only manages content for company B

It seems that even though we have created roles and permissions for Joe and Jane correctly (we think!) they can see each other's content where they shouldn't.

### Steps to reproduce the behavior

1. Go to administration panel, access **Roles** and configure the appropriate roles paying special attention to [custom permissions](https://docs.strapi.io/user-docs/users-roles-permissions/configuring-administrator-roles#setting-custom-conditions-for-permissions) which is where we believe we can effectively say "content managers only manage content they create" (screenshots 1 and 2).
2. Log in with two different accounts, one for Joe, another for Jane (use incognito mode in your browser).
3. Assuming you have created basic content types for **articles** and **tags**, check that you can successfully create articles and tags for Joe and Jane. Joe should not see Jane's articles and tags and vice versa (screenshots 3 and 4).
**4. So far so good. Now if you try to associate an article with tags, unfortunately Joe can now see Jane's tags. (screenshot 5)** 

### Expected behavior

Associated entities respect the permissions set on the parent entity i.e. Joe should not see Jane's tags when creating an article and vice versa.

### Screenshots

**Screenshot 1**
<img width="1874" alt="image" src="https://github.com/strapi/strapi/assets/9999415/a8f76c6a-7e08-4bec-a1f3-cb0b3bd89f6d">

**Screenshot 2**
<img width="1843" alt="image" src="https://github.com/strapi/strapi/assets/9999415/7f43470b-6291-498e-a028-284b1347e31d">

**Screenshot 3**
<img width="1736" alt="image" src="https://github.com/strapi/strapi/assets/9999415/4eab6465-3789-4410-b86c-ff4a039f00d9">

**Screenshot 4**
<img width="1647" alt="image" src="https://github.com/strapi/strapi/assets/9999415/3bf41155-53f7-4d3e-98e8-406d555731bf">

**Screenshot 5**
<img width="1792" alt="image" src="https://github.com/strapi/strapi/assets/9999415/8e865246-08bd-4ebf-8e2d-6912780ce2d0">

**Comment by afgallo** [comment]
Hi @derrickmehaffy thanks for looking into this issue. This seems to be related to how Strapi enforces authorisation and we respectfully consider this a high priority issue that needs urgent attention. We are looking into how we could potentially fix this issue by customising api queries that provide data to the admin panel. Could you point us to the right direction here please? Not sure if this is the best place to start? https://docs.strapi.io/dev-docs/admin-panel-customization

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy thanks for looking into this issue. This seems to be related to how Strapi enforces authorisation and we respectfully consider this a high priority issue that needs urgent attention. We are looking into how we could potentially fix this issue by customising api queries that provide data to the admin panel. Could you point us to the right direction here please? Not sure if this is the best place to start? https://docs.strapi.io/dev-docs/admin-panel-customization

Relationships in the admin don't currently have this capability and the RBAC conditions currently don't function properly with these. While the conditionals being broken is a bug the lack of RBAC capabilities 9n relations directly we do not consider a bug but rather a feature request: https://strapi.canny.io/feature-requests/p/apply-rbac-conditionals-to-relations-list

If you are looking for the code for the content manager plugin it's split in two parts:

Backend here: https://github.com/strapi/strapi/tree/develop/packages/core/content-manager/server

Admin here: https://github.com/strapi/strapi/tree/develop/packages/core/admin/admin/src/content-manager

Fixing that directly with be fairly difficult and normal extensions won't apply, you'd need to use patch-package and given the work we are currently doing subject to change quite often so maintaining that patch might be a challenge.

Not trying to discourage you but simply want to be candid with you. Strapi is not built to handle multi-tenancy if that's what you are doing we don't advise it.

I'm going to set this as closed since it's a feature request and we already have a bug report about conditionals but they likely won't be fixed in v4 and instead will be addressed in v5.

**Comment by afgallo** [comment]
Hi @derrickmehaffy thanks for getting back to me.

> Relationships in the admin don't currently have this capability and the RBAC conditions currently don't function properly with these. While the conditionals being broken is a bug the lack of RBAC capabilities 9n relations directly we do not consider a bug but rather a feature request: https://strapi.canny.io/feature-requests/p/apply-rbac-conditionals-to-relations-list

I respectfully disagree with this interpretation and I do think this should be considered a bug. The reason being Strapi's architecture indicates that careful thinking has been put in place with the ability to customise roles and permissions by selecting "conditions" where you set "records can change by their creator or someone with the same role". Applying the same RBAC restrictions in relationships should be something that the framework can deal with in IMHO.

> Not trying to discourage you but simply want to be candid with you. Strapi is not built to handle multi-tenancy if that's what you are doing we don't advise it.

I would love to understand more the rationale behind this. My view is that Strapi has a mature feature set and very good architecture so not sure why multi-tenancy is not advisable. The product is really good so I'm very intrigued.

> I'm going to set this as closed since it's a feature request and we already have a bug report about conditionals but they likely won't be fixed in v4 and instead will be addressed in v5.

I look forward to seeing the great work behind v5 and it's great to learn that this will be addressed then.

Thank you.
