### ISSUE TITLE
The localizations object is not populated when the route is public (auth: false)

### ISSUE THREAD

**Issue by volvotrax** [strapi/strapi#18917]
### Required System information

- Node.js version: v16.19.1
- PNPM version: 8.6.2
- Strapi version: 4.15.4 (also tested with 4.12.0)
- Database: postgres
- Operating system: linux-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

The `localizations` object is not populated when the route is public (auth: false).

### Steps to reproduce the behavior

1. Go to the administration panel
2. In the _Settings/Internationalization_ section, create the English and French locales
3. Create a new collection type `test` in the Content-Type Builder, select _Internationalization_ in the advanced settings tabs.
4. Add a Text field `name` and enable localization for it
5. Create a new localized entry in English for this collection
6. From this entry, create a French version
7. Grant access to the public role for this entity in _Settings/Roles/Public_
8. Get the localized entries by using the `populate=localizations` parameter
Everything is going fine, the `localizations` object is populated
```
curl 'http://localhost:1337/api/v1/test/1?populate=localizations'
{"data":{"id":1,"attributes":{"name":"test_name_en", ...,"locale":"en","localizations":{"data":[{"id":2,"attributes":{"name":"test_name_fr",....,"locale":"fr"}}]}}},"meta":{}}
```

8. Remove access to the public role for this entity but make the route publicly available by setting the auth config to false :
```
    findOne: {
      auth: false
    }
```
9. Try again to get the localized entries by using the `populate=localizations` parameter
The `localizations` object is not part of the response.
```
curl 'http://localhost:1337/api/v1/test/1?populate=localizations'
{"data":{"id":1,"attributes":{"name":"test_name_en", ...,"locale":"en"}},"meta":{}}
```

### Expected behavior

Since the route is public, we should get the `localizations` field.

### Debug information

In the controller, the `sanitizeOutput` function is called
https://github.com/strapi/strapi/blob/da634b09510db5ec9ab7163670ae903f44929752/packages/core/strapi/src/core-api/controller/collection-type.ts#L30

But the `auth` object passed to the `sanitize.contentAPI.output` function is an empty object:
```
const getAuthFromKoaContext = (ctx) => _.prop("state.auth", ctx) ?? {};
const auth = getAuthFromKoaContext(ctx);
return sanitize.contentAPI.output(data, contentType, { auth });
```

Then `sanitizeOutput` calls `hasAccessToSomeScopes` and the error `Cannot read properties of undefined (reading 'verify')` is thrown and caught (because `auth` is an empty object).

```
const hasAccessToSomeScopes = async (scopes: string[], auth: unknown) => {
  for (const scope of scopes) {
    try {
      await strapi.auth.verify(auth, { scope });
      return true;
    } catch {
      continue;
    }
  }
  return false;
};
```

Consequently, the localizations relation is removed from the output.

**Comment by Boegie19** [comment]
@volvotrax The role needs to have find permission on the collection type else it would be filtered out like happend in you case
