### ISSUE TITLE
500 server error on login with invalid username or password.

### ISSUE THREAD

**Issue by justindmyers** [strapi/strapi#1891]
**Informations**
- **Node.js version**: v8.11.4
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongoDB
- **Operating system**: Windows 10 64-bit

**What is the current behavior?**

`/user/local` is throwing a 500 server error if username or password is incorrect.

`TypeError: Cannot read property 'blocked' of null at callback (...\plugins\users-permissions\controllers\Auth.js:59:16)`

**Steps to reproduce the problem**

Log in a user with an incorrect username/password.

**What is the expected behavior?**

`/user/local` should return bad request with error message.

**Suggested solutions**

 `user.blocked` is being checked for a value before checking if `user` exists in Auth.js. User null check should be done first.

This is the the current Auth.js:

**`strapi/packages/strapi-plugin-users-permissions/controllers/Auth.js`**

```
if (user.blocked === true) {
    return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Auth.form.error.blocked' }] }] : 'Your account has been blocked by the administrator.');
}

if (!user) {
      return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Auth.form.error.invalid' }] }] : 'Identifier or password invalid.');
 }
```

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/pull/1895
