### ISSUE TITLE
Custom Field errors

### ISSUE THREAD

**Issue by miracode-richard** [strapi/strapi#18923]
### Required System information

- Node.js version: 20.7.0
- NPM version: 10.1.0
- Strapi version: 4.14.0
- Database: sqlite
- Operating system: Win 10
- Is your project Javascript or Typescript: TS

### Describe the bug

Created a plugin using the default generate and added a custom field to it.
After adding the custom field in a collection, strapi crashes.
This was working previously and did without a change not work anymore.
But even past this error, the editing of a collection entry would endlessly load without an error.

### Steps to reproduce the behavior

1. Create a collection
2. Add the custom field of this plugin to the collection
3. Save and wait for restart
4. See error "Could not find Custom Field: plugin::retejs.rete"

### Expected behavior

Clear documentation on how to add a custom field and receiving meaningful errors what is wrong.
Especially in the case where the site endlessly loads without any notice on what is wrong.

### Additional context

[Repo](https://www.mediafire.com/file/561j4ruttjvsbnl/test-repo.zip/file)

**Comment by humbleEwan** [comment]
Getting the same issue on the most up to date version of Strapi. From the forums I can tell that the issues with custom fields were started flowing in form around half a year ago. It should be a very simple and easy fix (just update the order). Why isn't this fixed??

**Comment by Boegie19** [comment]
Tryed using the repo you added to it but I have no custom fields being loaded in it
