### ISSUE TITLE
Cannot access admin panel from cloned strapi application

### ISSUE THREAD

**Issue by atlas365** [strapi/strapi#1892]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**:6.2.0
- **Strapi version**:3.0.0-alpha.14
- **Database**:Mongo
- **Operating system**:OSX

**What is the current behavior?**
Cannot access the admin panel from a strapi application that was cloned from a git repo.  

**Steps to reproduce the problem**
My team is trying to standardize strapi setup for the dev environment. One of our members has gone through the process of building users, permissions, roles, controllers and has populated the mongo db. I have pulled down her work and used mongorestore to populate my mongo instance with what she had in her tables.  The endpoints work fine but I cannot access the admin panel or the login screen. I only see the index.html page.

**What is the expected behavior?**
I think I should be able to log in using the admin user in the database and access the admin panel. Why is strapi always routing to index.html?

**Comment by TokenChingy** [comment]
Have you done the following?

- `npm install` in the project root directory.
- `npm run setup` in the project root directory.

**Comment by derrickmehaffy** [comment]
@atlas365 make sure you purge the package-lock.json file (if there is one) then run `npm run setup`

**Comment by atlas365** [comment]
Ok so running npm run setup got me access to the admin panel, but I don't see any plugins..
<img width="1354" alt="screen shot 2018-09-04 at 11 39 59 am" src="https://user-images.githubusercontent.com/25470131/45043296-cbe25680-b03a-11e8-9ab0-26907a5205bc.png">

I ran npm install inside each of the plugins but still nothing. Is there another setup method I need to run?

**Comment by derrickmehaffy** [comment]
@atlas365 that looks like something is very broken. Is this project public on github somewhere? My guess is that the build folders aren't being uploaded so you may need to run `npm run setup:build` (I haven't done this on a non --dev project so I have no clue if that will actually rebuild them)

**Comment by atlas365** [comment]
Unfortunately this isn't on a public github.   And I tried to run 'npm run setup:build' but I got an error message saying 'missing script: setup:build' and I didn't see an option for setup:build in the package.json.

**Comment by derrickmehaffy** [comment]
Yeah @atlas365 typically that is only for --dev projects. If you look on the private repo in `plugins/content-manager/admin/build` you should see a ton of files in there. If that directory isn't there or there is no files then it wasn't properly uploaded.

**Comment by atlas365** [comment]
Yeah no build folder. I can see it's being ignored in the .npmignore.  Is the best way to fix that to change the .npmignore? Should I restart my project using --dev?

**Comment by atlas365** [comment]
Oh wait nevermind that's not gitignore

**Comment by derrickmehaffy** [comment]
@atlas365 no don't use --dev unless you are modifying the adminUI.

.npmignore shouldn't matter, but if it is in .gitignore then remove it. You should however be able to create a new project and grab all the `api/*/models/*.settings.json` files and dump them into the new project to quickly spin up a new one so long as there were no major modifications.

**Comment by atlas365** [comment]
Perfect I think that's what I'm going to do then. Thank you very much for your helpful and very timely replies!

**Comment by KrunalDholakiya** [comment]
Even after following above given steps, I'm also facing this issue:
🏗  Building the admin...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! strapi-admin@3.0.0-alpha.25.2 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_
modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.25.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gkadmin/.npm/_logs/2019-05-16T19_25_37_469Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.25.2 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.25.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gkadmin/.npm/_logs/2019-05-16T19_25_41_341Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! API@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the API@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gkadmin/.npm/_logs/2019-05-16T19_25_41_382Z-debug.log
gkadmin@kanban00:~/tfs_trello/API$ tail -f /home/gkadmin/.npm/_logs/2019-05-16T19_25_41_341Z-debug.log
22 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "setup"
23 verbose node v11.14.0
24 verbose npm  v6.9.0
25 error code ELIFECYCLE
26 error errno 1
27 error strapi-admin@3.0.0-alpha.25.2 setup: `node ./scripts/setup.js`
27 error Exit status 1
28 error Failed at the strapi-admin@3.0.0-alpha.25.2 setup script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

**Comment by PabloZarate01** [comment]
I ran `strapi develop` and admin panel works

**Comment by FarhadMohseni** [comment]
i got this solved by using `npx strapi build` in the root directory

**Comment by oscarBack** [comment]
I got this solved by deleting the build folder from .gitignore file
