### ISSUE TITLE
Field named 'ref' causes an error of the admin panel when internationalization is enabled

### ISSUE THREAD

**Issue by aitalvivem** [strapi/strapi#18935]
### Required System information

- Node.js version: 18.0.0
- Yarn version: 1.22.15
- Strapi version: 4.11.1 (error reproduced in 4.15.4)
- Database: sqlite
- Operating system: win10
- Is your project Javascript or Typescript: javascript

### Describe the bug

An error appears in the admin panel when it is try to display the entries of a collection type. 
The error occured on a collection type having a field named `ref` and internationalization enabled.

### Steps to reproduce the behavior

1. Create a new project
2. In the `Settings/Internationalization` section, create the English and French locales
3. Create a new collection type with internationalization enabled
4. Add a short text field named `ref`
5. In the content manager, add a new entry for the default locale
6. Go back to the list of entries in the content manager, the error appears.

### Expected behavior

Be able to view the list of entries in the content manager.

### Additional context

- Strapi's backend and APIs are working as expected.
- The error only appears when internationalization is enabled on the collection type.
- This error seems related to a reserved word `ref` in REACT, an error appearing in the browser console is pointing to those errors in the REACT documentation :
    - [https://legacy.reactjs.org/docs/error-decoder.html/?args%5B%5D=ref1&invariant=290](https://legacy.reactjs.org/docs/error-decoder.html/?args%5B%5D=ref1&invariant=290)
    - [https://legacy.reactjs.org/warnings/refs-must-have-owner.html](https://legacy.reactjs.org/warnings/refs-must-have-owner.html)

### Screenshots

1. Admin panel error
![admin_panel_error](https://github.com/strapi/strapi/assets/52562995/3531da1d-f5a8-4aa4-b485-3eca9d4cf1ff)
2. Browser error
![browser_error](https://github.com/strapi/strapi/assets/52562995/8730ca8e-81fe-4a58-ba91-2d38b1133e85)

**Comment by Boegie19** [comment]
Part of tracking issue https://github.com/strapi/strapi/issues/16222
