### ISSUE TITLE
Drag and drop causing issue with dynamic zone rich text components

### ISSUE THREAD

**Issue by rahulc-globant** [strapi/strapi#18939]
### Required System information

- Node.js version: v20.5.0
- NPM version: v9.8.0
- Strapi version: v4.15.4
- Database: Any
- Operating system: Linux, Windows
- Is your project Javascript or Typescript: Found in both

### Describe the bug
When we create a dynamic component with **Rich Text** field, it is causing issues on reordering elements of Dynamic Zone.
This issue is found with default strapi editor as well as custom wysiwyg (CKEditor)
Refer to below video to get more details on the issue
https://github.com/strapi/strapi/assets/89125459/2efb5a67-f61c-4ef4-84ea-2ebb7d81560e

### Steps to reproduce the behavior

1. Go to Content Builder. Create new type to recreate this issue.
2. In this new type add a dynamic zone with rich text field.
3. Create new element for this new type. Add two dynamic zone elements.
4. Add any text in the rich text field.
5. Save element.
6. Try to reorder the dynamic zone elements and observe the changes.

### Expected behavior
Content should be preserved when order is changed.

### Code snippets

Use this code to reproduce the issue.
[my-project.zip](https://github.com/strapi/strapi/files/13499808/my-project.zip)

**Comment by dgrebb** [comment]
Been bothering me for months.

For Strapi squad awareness, this is not new. Possibly around since ~4.13.2.

**Comment by rahulc-globant** [comment]
Hi Team,
Any updates on this issues

**Comment by rahulc-globant** [comment]
Hi Team,
Any updates on this issues
