### ISSUE TITLE
Clean install of Strapi with TypeScript breaks after first content type is created!

### ISSUE THREAD

**Issue by diacu** [strapi/strapi#18940]
### Required System information

- Node.js version: v18.17.1
- Yarn version: 1.22.19
- Strapi version: 4.15.4
- Database: any (sqlite, mysql)
- Operating system: Linux / Unix / Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Setup a new project with `yarn create strapi-app my-project` and then create a new content type (e.g. `test`). After hitting save, server will reload and crash. Project no longer compiles.

Running `yarn develop` again will show same errors:
```
ERROR in ./src/api/test/controllers/test.ts:7:47
TS2345: Argument of type '"api::test.test"' is not assignable to parameter of type 'ContentType'.
    5 | import { factories } from '@strapi/strapi'
    6 |
  > 7 | export default factories.createCoreController('api::test.test');
      |                                               ^^^^^^^^^^^^^^^^
    8 |

ERROR in ./src/api/test/routes/test.ts:7:43
TS2345: Argument of type '"api::test.test"' is not assignable to parameter of type 'ContentType'.
    5 | import { factories } from '@strapi/strapi';
    6 |
  > 7 | export default factories.createCoreRouter('api::test.test');
      |                                           ^^^^^^^^^^^^^^^^
    8 |

ERROR in ./src/api/test/services/test.ts:7:44
TS2345: Argument of type '"api::test.test"' is not assignable to parameter of type 'ContentType'.
    5 | import { factories } from '@strapi/strapi';
    6 |
  > 7 | export default factories.createCoreService('api::test.test');
      |                                            ^^^^^^^^^^^^^^^^
    8 |

webpack 5.89.0 compiled with 3 errors in 20165 ms
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

error Command failed with exit code 1.
```

### Steps to reproduce the behavior

Just follow the description of the bug.

### Expected behavior

Strapi should successfully restart if a new content type is created.

### Additional context

If you run `yarn strapi ts:generate-types`, and then again `yarn develop`, it works! Until you create a new content type.

**Comment by beumerr** [comment]
Add `typescript.ts` to your `config` folder with the content;

`export default {
  autogenerate: true,
};`

And make sure to exclude `"types/generated/**"` from your `tsconfig.json`

![image](https://github.com/strapi/strapi/assets/36204079/7998292f-69a5-4619-9820-d3e4656828a6)

**Comment by monolithed** [comment]
@diacu agreed. I also had trouble with a TypeScript build. In the few days of using Strapi, I encountered numerous issues that, in my opinion, shouldn't be present in mature products.

**Comment by Zenb0t** [comment]
Happened to me when using docker in a recent version, namely `4.22.1 `

I followed what beumerr did, but added also    `      - ./back/types:/opt/app/types` to my docker-compose.yml volumes and it fixed my issue.

> I had the same problem, very annoying that this isn't automatically set after installation.
> 
> Add `typescript.ts` to your `config` folder with the content;
> 
> `export default { autogenerate: true, };`
> 
> And make your excludes contains `"types/generated/**"` in `tsconfig.json`
> 
> ![image](https://private-user-images.githubusercontent.com/36204079/286647128-7998292f-69a5-4619-9820-d3e4656828a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTEyMjksIm5iZiI6MTcxMjc5MDkyOSwicGF0aCI6Ii8zNjIwNDA3OS8yODY2NDcxMjgtNzk5ODI5MmYtNjlhNS00NjE5LTk4MjAtZDNlNDY1NjgyOGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDIzMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTJjYWNlODk4MGVjYWE2MjlkNjdjYWQzNjE1Yzk3NmRmOGNkYjFmMjU5NjEwNWEyMTZiNDg2OTU3OTc0YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_o1Ju5hNMUaRAtFKuBw_TcYmjZOr3Q0IfywU56q7ks)
