### ISSUE TITLE
trying to run npm install strapi@alpha -g Failed

### ISSUE THREAD

**Issue by adityakmr7** [strapi/strapi#1894]
```
C:\projects>npm install strapi@alpha -g
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
C:\Users\adity\AppData\Roaming\npm\strapi -> C:\Users\adity\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js
+ strapi@3.0.0-alpha.14
updated 1 package in 55.671s
```

this is the error i get while installing strapi

- node version :  10.9.0
-npm : 6.4.1
-database : mongodb
-operating system : windows 10

How can i fix this ?

**Comment by derrickmehaffy** [comment]
@adityakmr7 that isn't a failure message, that is a success message.

Also as a footnote, Windows support is very limited and isn't recommended. I suggest you use either WSL or a Linux VM

**Comment by adityakmr7** [comment]
But when I try to run 
strapi new myProject terminal says strapi is not a internal or external command. 
Why is that??

**Comment by derrickmehaffy** [comment]
@adityakmr7 it is likely your global npm packages are not mapped to your path.

**Comment by adityakmr7** [comment]
@derrickmehaffy can you please tell me how to map path for npm package

**Comment by maturanomx** [comment]
@adityakmr7 I noticed you close the issue one hour after questioning how to modify your path. Did you found the solution? Can you share it with us?

In Unix is modifying the `PATH` environment variable. On Windows should be something similar, but I don't have idea what variable is and how to modify it...

**Comment by adityakmr7** [comment]
No I didn't found the way to modify the path. I reinstalled it and after that it was working so I closed the issue.
