### ISSUE TITLE
Generated path to custom plugin is not well constructed in .strapi/client/app.js

### ISSUE THREAD

**Issue by gundall** [strapi/strapi#18949]
### Required System information

- Node Version: 18.17.0
- NPM Version: 9.6.7
- Strapi Version: 4.15.4
- Database: Postgres
- Operating System: Windows 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Hi! I’ve been working on a custom plugin lately. To ease the process, I’ve been using:

```
npm run strapi develop --watch-admin.
```

Everything was working fine until I upgraded my app from 4.15.0 to 4.15.4. Now, the path to my custom plugin in .strapi/client/app.js is not well constructed; there’s a screenshot of my code in the Screenshots section.

I've also tried with a newly created plugin via `strapi generate`, and I got the same error.

### Steps to reproduce the behavior

1. Upgrade your Strapi app to version 4.15.4.
2. Run `strapi develop --watch-admin` with a custom plugin created and configured.
3. Open `.strapi/client/app.js` (if exists) to watch live how the error occurs.

### Expected behavior

The paths to the custom plugins should be well constructed, like this:

```
// .strapi/client/app.js
...
import pluginTemplate from "../../src/plugins/plugin-template/strapi-admin";
...
```

### Screenshots

![image](https://github.com/strapi/strapi/assets/27724595/fd3df78a-3fb8-449f-a68b-0069b4e7ccf0)
As you can see, the path slashes are missing.

**Comment by derrickmehaffy** [comment]
Can you please test this on V4.15.5 that was released today as it should be fixed

**Comment by gundall** [comment]
Yes, it's working, as you said. Thank you ver much!
