### ISSUE TITLE
Cannot upload to specific folder anymore

### ISSUE THREAD

**Issue by donkeycomm** [strapi/strapi#18955]
plugin: @strapi/provider-upload-aws-s3 gives error: Bucket name shouldn't contain '/'

In the latest strapi version the Bucket name cannot contain a '/', so you cannot specify to which folder you want to upload on digital ocean spaces.

This is the config;

`  upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("DO_SPACE_ACCESS_KEY"),
        secretAccessKey: env("DO_SPACE_SECRET_KEY"),
        region: env("DO_SPACE_REGION"),
        endpoint: env("DO_SPACE_ENDPOINT"),
        params: {
          Bucket: env("DO_SPACE_BUCKET") + "/" + env("DO_SPACE_DIRECTORY"),
        },
      },
    },
  },`

**Comment by chhaysotheara** [comment]
Check out this guide: https://market.strapi.io/providers/@strapi-provider-upload-aws-s3

Basically, you just need to remove the string concat from your bucket name and put the prefix(folder) that you want in the **rootPath** property instead.

```
upload: {
  config: {
    provider: 'aws-s3',
    providerOptions: {
      baseUrl: env('CDN_URL'),
      rootPath: env('CDN_ROOT_PATH'), <=== put your env("DO_SPACE_DIRECTORY") here
      s3Options: {
        accessKeyId: env('AWS_ACCESS_KEY_ID'),
        secretAccessKey: env('AWS_ACCESS_SECRET'),
        region: env('AWS_REGION'),
        params: {
          ACL: env('AWS_ACL', 'public-read'),
          signedUrlExpires: env('AWS_SIGNED_URL_EXPIRES', 15 * 60),
          Bucket: env('AWS_BUCKET'),
        },
      },
    },
    actionOptions: {
      upload: {},
      uploadStream: {},
      delete: {},
    },
  },
},
```

**Comment by jy-choo** [comment]
@chhaysotheara thanks for the heads up, this has fixed the issue for me not being able to upload to a specific folder under AWS CDN, the official guide was a bit vague for me about this.
