### ISSUE TITLE
data import/transfer of dynamic zone field data fails with a FOREIGN KEY constraint error message

### ISSUE THREAD

**Issue by thanos982** [strapi/strapi#18964]
### Required System information

- Node/Yarn Version: yarn/1.22.19 npm/? node/v20.2.0 darwin x64
- NPM version: 9.6.6
- Strapi version: 4.15.5
- Database: sqlite (problem occurs in pg as well)
- OS: darwin-x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Data import/exports fail with a FOREIGN KEY constraint error when the following conditions are met:
- a collection contains a dynamic zone field which contains at least two components. 
- one of the components contains another component, which contains a relation field, linking to another collection
- the component mentioned above is second or later within the order of the dynamic zone field data
- there is already data in the database for the collection

### Steps to reproduce the behavior

1. Create a new project and replace your src folder with this one: [src.zip](https://github.com/strapi/strapi/files/13523350/src.zip)
2. Import this non-encrypted export file once: 
[export_20231201100522.tar.gz](https://github.com/strapi/strapi/files/13523468/export_20231201100522.tar.gz). The import should be successful 
3. Import the same export file again. You should see the error `error: [ERROR] insert into 'components_shared_actions_destination_links' ('action_id', 'destination_id') values (7, 3) - FOREIGN KEY constraint failed`

### Expected behavior

The import should be successful and data for all entities and links should be updated without issues.

### Additional context

After debugging I found out that the issue is [here](https://github.com/strapi/strapi/blob/dfec2ca3fc4a3b390f514b40194d0ad37039e362/packages/core/data-transfer/src/strapi/providers/local-destination/strategies/restore/entities.ts#L70). The mapping table is being updated with the incorrect value because the type returned by the resolveType function is incorrect.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18350
