### ISSUE TITLE
Issue with Compatibility between Strapi (v4.15.5) and Localazy Plugin

### ISSUE THREAD

**Issue by david-vaclavek** [strapi/strapi#18969]
### Required System information
- Node.js version: v18.4.0
- NPM version: v8.12.1
- Strapi version: v4.15.5
- Database: SQLite
- Operating system: MacOS 14.0 (23A344)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I am having a clean Strapi v4.15.5 instance. After installing the latest Localazy Strapi Plugin on such version and clicking on the Localazy menu item in the Strapi Administration, a blank loading page is rendered. There's no console error in Dev Tools. Therefore there are no leading signs of where to start debugging.

### Steps to reproduce the behavior

1. Install clean Strapi v4.15.5 project.

```json
  "dependencies": {
    "@localazy/strapi-plugin": "^0.2.3",
    "@strapi/plugin-cloud": "4.15.5",
    "@strapi/plugin-i18n": "4.15.5",
    "@strapi/plugin-users-permissions": "4.15.5",
    "@strapi/strapi": "4.15.5",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
```

2. Install and setup the [latest Localazy Strapi Plugin](https://www.npmjs.com/package/@localazy/strapi-plugin/v/0.2.3).
4. Build the admin panel and run the project (+ create the first admin user).
5. Click on the Localazy flag in the admin panel menu.
6. Blank loading page is rendered.

### Expected behavior

I expect the Localazy Strapi Plugin to work like with e.g. Strapi v4.14.5.

### Screenshots

<img width="1727" alt="image" src="https://github.com/strapi/strapi/assets/49518842/d1445a48-63cc-4763-9c17-993cbb220734">

**Comment by erdemyunsel** [comment]
same issue on me.

<img width="926" alt="image" src="https://github.com/strapi/strapi/assets/8062528/98c1c318-11b8-413a-aaad-4b2bce6ae7aa">

**Comment by joshuaellis** [comment]
I've tried to look into this and I can't even build my admin panel because i see:
```shell
[ERROR] Module not found: Error: Can't resolve 'http' in '/release-4155/node_modules/socket.io/dist'
```
Which makes me wonder if you're importing node code in your browser environment in the plugin?

**Comment by david-vaclavek** [comment]
Hello, @joshuaellis.

The reason you cannot build the admin panel is that the instructions were not followed correctly from the link I provided in my report. I admit, I should have probably added them here directly so you don't have to read between the lines. Generally, they are [here](https://localazy.com/docs/strapi/strapi-plugin-introduction-installation#install-plugin-via-npm).

Anyway, I attached a ZIP file with the project.
[Uploading strapi-gh-issue-replicated.zip…]()

Just run `npm ci`. I used the latest Strapi version (the problem still persists).

Thank you!

**Comment by pascalbur** [comment]
I have the same issue with the following versions:

Strapi: 4.17,1 / 4.20.0 (tried both)
Strapi Localazy Plugin: 0.2.3
Node: 18.17.0
npm: 10.4.0

**Comment by joshuaellis** [comment]
I don't think there's an issue with Strapi here, the app loads your plugin and probably gets stuck on the first request it makes `const identity = await LocalazyUserService.getIdentity();` because it never calls `setIsLoadingApp(false)`. Have you debugged it from your side to understand the cause more?

**Comment by david-vaclavek** [comment]
I have done some investigation and found out that the version(s) of Strapi where the plugin works is that during the plugin initialization, the `process` variable is not defined.

It then throws an error, which is completely silent by default.

@joshuaellis How to force newer versions of Strapi to have the `process.env` variables available during the plugin init?

**Comment by joshuaellis** [comment]
Can you share where this is done? `process.env` should be available as soon as the admin panel is running because we use it ourselves :)

**Comment by david-vaclavek** [comment]
During the time of plugin initialization [here](https://github.com/localazy/strapi-plugin/blob/main/admin/src/index.js#L57), in the [App/index.js](https://github.com/localazy/strapi-plugin/blob/main/admin/src/pages/App/index.js#L37) file, [i18.js](https://github.com/localazy/strapi-plugin/blob/main/admin/src/i18n.js#L18) file is loaded. This is one of the places where `process.env` is used.

**Comment by david-vaclavek** [comment]
We managed to fix it in the latest release [v0.2.4](https://www.npmjs.com/package/@localazy/strapi-plugin/v/0.2.4).

**Comment by Mexx77** [comment]
still see the issue with v0.2.4 and v0.2.5 :/

**Comment by david-vaclavek** [comment]
@Mexx77 Did you follow the steps from the [docs](https://localazy.com/docs/strapi/strapi-plugin-introduction-installation#install-plugin-via-npm)?

**Comment by Mexx77** [comment]
@david-vaclavek thanks, setting  STRAPI_ADMIN_LOCALAZY_ENV did the trick. 😄 . The alternative (adjusting webpack.config.js), however, doesn't work for me
