### ISSUE TITLE
Strapi (v4) should handle GraphQL queries over GET HTTP requests

### ISSUE THREAD

**Issue by daniele-orlando** [strapi/strapi#18979]
### Required System information

- Strapi version: 4.15.5

### Describe the bug

In Strapi 4, GraphQL queries sent over **HTTP GET** requests receive a `Forbidden access` error.
**Everything works as expected running the same queries over POST requests.**

The GraphQL endpoint is `/graphql` and serves successfully POST queries/mutations and the Playground Web Interface.

### Steps to reproduce the behavior

1. Open a browser console
2. Run

```js
fetch("https://<HOST>/graphql?query=query%7Bpages%7Bdata%7Bid%20attributes%7Bslug%7D%7D%7D%7D", {
  "method": "GET",
}).then(it => it.json()).then(console.log)
```

### Expected behavior

I should receive the GraphQL data as response.

### Actual behavior

I receive the error:

```json
{
    "errors": [
        {
            "message": "Forbidden access",
            "extensions": {
                "error": {
                    "name": "ForbiddenError",
                    "message": "Forbidden access",
                    "details": {}
                },
                "code": "FORBIDDEN"
            }
        }
    ],
    "data": {
        "offers": null
    }
}
```

### Additional context

The issue is related to this portion of code that skips the authentication logic.

https://github.com/strapi/strapi/blob/dc96169c3f41dab4ab75d828d3fb39dd1a2dae27/packages/plugins/graphql/server/bootstrap.js#L110

Removing this block of code, the GET requests work as expected and the Playground is still reachable on the same endpoint.

```diff
-          // allow graphql playground to load without authentication
-          if (ctx.request.method === 'GET') return next();
```

**Comment by gauravruhela07** [comment]
@daniele-orlando I want to work on this issue, can you please assign it to me? Thanks.

**Comment by daniele-orlando** [comment]
https://feedback.strapi.io/feature-requests/p/strapi-v4-should-handle-graphql-queries-over-get-http-requests

**Comment by daniele-orlando** [comment]
Reopened as https://github.com/strapi/strapi/issues/19073.
