### ISSUE TITLE
While trying to install strapi installation get aborted

### ISSUE THREAD

**Issue by adityakmr7** [strapi/strapi#1898]
I am on windows  10 

- node : 10
- npm: 6
-strapi latest version 
-database mongodb

when i run strapi new mydashboard

-it ask for default database  i provided it mongodb
after that it asks for database name (mydashboard)

after this installation is aborted.
anyone help me to fix this

**Comment by adityakmr7** [comment]
@TokenChingy  can you please tell me what is the command i have to run. I am not getting it, I am new here just started to learn strapi.

**Comment by TokenChingy** [comment]
`strapi new --dbclient=mongo --dbhost=INSERT_YOUR_DB_URL --dbport=INSERT_YOUR_DB_PORT` --dbname=WHAT_YOU_WANT_TO_CALL_YOUR_DB --dbusername=LEAVE_BLANK_OR_DB_USERNAME --dbpassword=LEAVE_BLANK_OR_DB_USERNAME --dbssl=LEAVE_BLANK_OR_DB_SSL_CERT --dbauth=LEAVE_BLANK_OR_DB_AUTH_URL

**Comment by adityakmr7** [comment]
it gives error saying module not found  'mongoose'. 

-althought i have mongoose installed globally.

**Comment by maturanomx** [comment]
Interesting 🤔 ...
