### ISSUE TITLE
Error Uploading image on live server

### ISSUE THREAD

**Issue by emman24** [strapi/strapi#1900]
Cant upload images on my content media when i click save throws an error

ENOENT: no such file or directory, open '/home/ubuntu/aws_strapi/public/uploads/fa155c2299674f869347bc4b60a086fc.png'

![capture](https://user-images.githubusercontent.com/25625894/45104660-6c8e5000-b0e7-11e8-976d-1dd72de74570.PNG)

I follow the tutorials on deploying strapi on ubuntu

node version : 10.9.0
-npm : 6.2.0
-database : mongodb
-operating system : ubuntu server 16.04

**Comment by lauriejim** [comment]
Hello @emman24 , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

**Comment by lauriejim** [comment]
Hello @emman24, I tried with a fresh EC2 instance and it works well.
Make sure it's not comme from any configuration of your server that block upload files.

**Comment by lauriejim** [comment]
Hello @sgrund14 , you can't upload file on Heroku. 
Please check this article https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

You have to use a AWS S3 provider for example.
More info about upload providers here https://strapi.io/documentation/guides/upload.html#install-providers

**Comment by TetHat** [comment]
I know this has been closed for a while, but just a suggestion on this. Your blog has a tutorial explicitly deploying the Strapi API to Heroku, in which that project uses uploaded images. I don't believe anywhere in here is it mentioned that you have to install upload providers, nor that Heroku will delete the files uploaded through Strapi admin. Would be pretty beneficial for this tutorial to at the very least mention that's going to take place when uploading Strapi to Heroku, and provide the above links on that topic. Thanks!

https://blog.strapi.io/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-dishes-list-part-3-7/

**Comment by derrickmehaffy** [comment]
@TetHat 

https://github.com/strapi/strapi/wiki/Create-files-on-Heroku
https://github.com/strapi/strapi/wiki/Deploy-on-Heroku

**Comment by TetHat** [comment]
@derrickmehaffy 

Thanks for the links, however I was not looking for links on the issue. My point was that the tutorial in my above comment is rather misleading and should provide users with links explaining that it would occur. Alas, the tutorial does not include any mention of this. It merely says "deploy the Strapi API to Heroku and you're done!" Which is far from the truth. Any newcomer to both Strapi and/or Heroku would have no idea this takes place, and adding in any of the links either you or @lauriejim mentioned into that tutorial seems like a pretty easy thing to do for anyone who comes to that tutorial in the future. Thanks again!

**Comment by derrickmehaffy** [comment]
I believe that tutorial makes the assumption that the user is slightly familiar with how heroku works. Given I am not on the Strapi team and only contribute. I would argue that heroku really isn't the best platform to test with, and certainly is not good for production usage.

**Comment by davidkartuzinski** [comment]
> @derrickmehaffy
> 
> Thanks for the links, however I was not looking for links on the issue. My point was that the tutorial in my above comment is rather misleading and should provide users with links explaining that it would occur. Alas, the tutorial does not include any mention of this. It merely says "deploy the Strapi API to Heroku and you're done!" Which is far from the truth. Any newcomer to both Strapi and/or Heroku would have no idea this takes place, and adding in any of the links either you or @lauriejim mentioned into that tutorial seems like a pretty easy thing to do for anyone who comes to that tutorial in the future. Thanks again!

@TetHat - Hello. I'm the new Dev Advocate at Strapi.  I just requested a pull request from the team on new Getting Started and Introduction documentation.  Both a more advanced version and a real step by step version. The point is we're definitely hearing you about the documentation and have started really focusing on it! 

I have noted exactly what you said about deploying to Heroku and have added your points of having a clearer explanation (re Heroku) to the docs.  Thank you.

**Comment by prashantsankhyan** [comment]
Hello  
on live server image is doing disappear 
after some 
and in loachalhoast image is working

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
