### ISSUE TITLE
`unique` not working for type `enumeration`

### ISSUE THREAD

**Issue by y-nk** [strapi/strapi#19002]
When creating a component, we can do `type: string` and `unique: true` but it's not the case for `type: enumeration` although they're the same in the end.

Is it a defect or intended behavior?

**Comment by derrickmehaffy** [comment]
Enums really shouldn't be unique honestly.

**Comment by y-nk** [comment]
@derrickmehaffy why not?

If i were to create a form select component with controlled values for an option set, i would want the option key to be part of an enum, yet i wouldn't want twice the same enum value in the set.
