### ISSUE TITLE
Can add new content but cannot save existing content

### ISSUE THREAD

**Issue by hyphenclub** [strapi/strapi#19028]
### Required System information

- Node.js version: v20.10.0
- NPM version: Using Yarn (1.22.21)
- Strapi version: v4.15.4
- Database: mysql 8 (mysql2)
- Operating system: Ubuntu (linux-x64)
- Is your project Javascript or Typescript: Javascript

### Steps to reproduce the behavior

1. Go to an existing entry that was modified recently.
2. Make an edit.
3. Saving gives the error.

This doesn't happen for any other content type.

### Expected behavior

```
[strapi] [2023-12-11 11:09:55] [2023-12-11 11:09:55.429] error: db.getConnection(...).raw is not a function
[strapi] [2023-12-11 11:09:55] TypeError: db.getConnection(...).raw is not a function
[strapi] [2023-12-11 11:09:55]     at updateOrderColumn (/workspace/node_modules/@strapi/database/dist/index.js:4559:34)
[strapi] [2023-12-11 11:09:55]     at cleanOrderColumns (/workspace/node_modules/@strapi/database/dist/index.js:4608:23)
[strapi] [2023-12-11 11:09:55]     at deleteRelations (/workspace/node_modules/@strapi/database/dist/index.js:4525:13)
[strapi] [2023-12-11 11:09:55]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[strapi] [2023-12-11 11:09:55]     at async Object.updateRelations (/workspace/node_modules/@strapi/database/dist/index.js:5528:15)
[strapi] [2023-12-11 11:09:55]     at async Object.update (/workspace/node_modules/@strapi/database/dist/index.js:5084:9)
[strapi] [2023-12-11 11:09:55]     at async /workspace/node_modules/p-map/index.js:57:22
```

### Code snippets

The problem is probably here:
https://github.com/strapi/strapi/blob/a8709d897e844533ed67c635528aaac3616ad46f/packages/core/database/src/entity-manager/regular-relations.ts#L258-L270

**Comment by hyphenclub** [comment]
@StevenJPx2 for reference.

**Comment by StevenJPx2** [comment]
Any update on this?

**Comment by StevenJPx2** [comment]
Found the fix here.
https://github.com/strapi/strapi/issues/14832#issuecomment-1311637379
Changed the package manager from yarn to npm, and commented out the schema key.
