### ISSUE TITLE
The data transfer progress error.ER_LOCK_WAIT_TIMEOUT

### ISSUE THREAD

**Issue by codeErrorSleep** [strapi/strapi#19033]
### Required System information

- Node.js version:v18.18.2
- NPM version:9.8.1
- Strapi version:v4.11.1
- Database: mysql 8.0.28 
- Operating system: centos
- Is your project Javascript or Typescript:Typescript

### Describe the bug
I need to use two Strapi instances to deploy separately in China and the United States. I hope to use data transfer for synchronization.

I can transfer data normally during local testing. However, when I deploy them on the servers, I always encounter this error. I am currently unsure how to resolve it and would appreciate any help.

order info 
```
 yarn strapi transfer   --from ....... --from-token tokeninfo.... --exclude config --force
```

error info
```
Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction

code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sqlMessage: 'Lock wait timeout exceeded; try restarting transaction',
  sqlState: 'HY000',
  index: 0,
  sql: 'update `strapi_core_store_settings` set `value` = \'{\\"admin::permission\\":{\\"collectionName\\":\\"admin_permissions\\",\\"info\\":{\\"name\\":\\"Permission\\",
```

### Expected behavior

data tansfer success

### Screenshots

![screenshot-20231212-163040](https://github.com/strapi/strapi/assets/20470033/33b164b7-bc06-46a6-84ef-9cee14afa51b)

![screenshot-20231212-163125](https://github.com/strapi/strapi/assets/20470033/a4712b6e-cf42-4d5d-b2ff-40c4315bb8ec)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by codeErrorSleep** [comment]
table strapi_core_store_settings.This table seems to be used for storing plugin information, but even though my command has already specified --exclude config, it still synchronized, and it looks like a deadlock has occurred.

**Comment by codeErrorSleep** [comment]
I found that the main issue was that a certain transaction was constantly occupying resources. After clearing it, there were no more problems.

**Comment by dkottas-nelios** [comment]
I am having a very simmilar problem. Could you give a bit more info about what kind of transaction was causing the problem or how did you identify it?

**Comment by Kulimeya** [comment]
I have the same error. Updated to the newest version etc. but it always randomly stops importing assets at some point and throws this:
`Emitted 'error' event on Job instance at:
    at /root/backend/node_modules/node-schedule/lib/Invocation.js:277:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sqlMessage: 'Lock wait timeout exceeded; try restarting transaction',
  sqlState: 'HY000',
  index: 0,
  sql: 'update `strapi_core_store_settings` set `value` = \'{\\"weeklySchedule\\":\\"38 16 15 * * 5\\",\\"lastWeeklyUpdate\\":1716563798044}\', `type` = \'object\' where (`id` = 36)'
}`

**Comment by cap340** [comment]
You can also set the value manually in the ``strapi_core_store_settings`` table.
Check the **lastWeeklyUpdate** value of the error in the **sql** line.  
Here the value to change is **1747943087073** for the **plugin_upload_metrics** key (record with id 262) of the **strapi_core_store_settings** table
```
{
  code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sqlState: 'HY000',
  sqlMessage: 'Lock wait timeout exceeded; try restarting transaction',
  // error details to check
  sql: 'update `strapi_core_store_settings` set `value` = \'{\\"weeklySchedule\\":\\"47 44 21 * * 4\\",\\"lastWeeklyUpdate\\":1747943087073}\', `type` = \'object\' where (`id` = 262)'
}
```
Column no longer needs to be updated and the import can complete successfully.

**Comment by IvanAdmaers** [comment]
This helped me:

```sql
SET GLOBAL innodb_lock_wait_timeout = 999999999;
SET SESSION innodb_lock_wait_timeout = 999999999;
```

To check:
`SELECT @@innodb_lock_wait_timeout;`
