### ISSUE TITLE
Entities aren't deleted completely (Content Type, Fields)

### ISSUE THREAD

**Issue by igor-mihalitsin** [strapi/strapi#1903]
**Informations**
- **Node.js version**: v9.11.2
- **npm version**: v5.6.0
- **Strapi version**: v3.0.0-alpha.14
- **Database**: mongodb v3.6.3
- **Operating system**: Ubuntu 18.04 LTS (on VirtualBox)

**What is the current behavior?**
We receive 500 error code on attempt to re-create content type with old name which recently was removed

**Steps to reproduce the problem**
1. Start empty project and login with admin account
2. Create Content Type with name "test1" (and String filed with name "Name") through "Content Type Builder"
3. Remove "test1" Content Type
4. Try to create Content Type with name "test1" (and Number filed with name "Priority") through "Content Type Builder"

**What is the expected behavior?**
We should be able to re-create content type with old name

**Suggested solutions**
-

**Comment by arjohnson97** [comment]
It's super frustrating, I feel like there should be a 'clear cache' option, or something similar.

**Comment by TokenChingy** [comment]
This problem is causing massive headaches... When you refresh or click into another Type, the unsaved fields dissappear but stay in the DB. So when you go and save or create a new field, it throws errors. When you delete a field or Type and use the same name, it throws an error.
