### ISSUE TITLE
Inconsistent environment

### ISSUE THREAD

**Issue by ShahriarKh** [strapi/strapi#19039]
When I `npm start` without setting `NODE_ENV`, the application shows `development` both in welcome page and terminal, but prevents me from accessing Content-type Builder by showing an alert:
> [!NOTE] 
> Information:
> Strapi is in production mode, editing content types is disabled. Please switch to development mode by starting your server with strapi develop.

This inconsistent behavior causes frustration.
The solution is to add `NODE_ENV=production` (in `.env` or script), but I think if strapi already knows the app in production mode (like in content-type builder), this should be reflected in other parts as well.

### Required System information

- Node.js version: 18.17.0 | 20.5.1
- NPM version: 10.2.3 | 9.8.0
- Strapi version: 4.15.5
- Database: MySQL
- Operating system: Windows 10 | Linux (CloudLinux)
- Is your project Javascript or Typescript: Javascript

**Comment by derrickmehaffy** [comment]
The current logic is intended and the error message is as clear as we can make it.

Marking this as closed.

**Comment by ShahriarKh** [comment]
How is that intended to show 'development' in terminal and welcome page, but say 'production' in admin panel and prevent editing content-types?

**Comment by derrickmehaffy** [comment]
The warning tells you that the develop command should be used. The two requirements are:

- use the develop command
- use the development node environment

We can't make that any easier and we can't just depend on one of them as both those options set different things.

**Comment by derrickmehaffy** [comment]
It has been this way since 2015 and has not been an issue for others.
