### ISSUE TITLE
Field help tip for content manager settings

### ISSUE THREAD

**Issue by tonyberetini** [strapi/strapi#1905]
**What is the expected behavior?**
Each content field should have an optional field to define help text explaining what the field is for or is doing. This is very common when building usable user experiences.

**Comment by derrickmehaffy** [comment]
@tonyberetini 
![image](https://user-images.githubusercontent.com/8593673/45122511-e428a300-b118-11e8-9f47-984a8a29faec.png)

**Comment by tonyberetini** [comment]
Exactly my point... how is anyone supposed to know what that field is for if it is not explained with a help tip.

**Comment by derrickmehaffy** [comment]
@tonyberetini that feature is new, I'm sure the Strapi team would love a PR if you find it confusing 😛

**Comment by tonyberetini** [comment]
Ha Ha Ha… question shouldn’t this be defined in content type builder instead of content builder. This should be an annotation to a field in content builder not an annotation to a record within the content field. Am I looking at this from a wrong angle.

**Comment by Aurelsicoko** [comment]
The Content-Type Builder defines the schema of your database. If you set a description to a field, this is the description dedicated to the developer or database manager.

The Content-Manager defines the layout and allows you to contribute data. If you set a description to a field, this is the description dedicated to the content marketing people. 

IMO, it shouldn't be the same description and the description can be really different. For example, if I have a field `Price`, I would like to set in the column's description in database `Price of the product` and `Set the price of the product (two decimals allowed) (ex: 93,30)` in the create/edit view.

Does it make sense to you too?

**Comment by lauriejim** [comment]
Thank you for this feedback. We will work on this point.
