### ISSUE TITLE
Changing "Maximum size allowed (in MB)" doesn't affect the max upload limit

### ISSUE THREAD

**Issue by reinisriekstins** [strapi/strapi#1906]
**Informations**
- **Node.js version**: 9.4.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: Mongodb
- **Operating system**: OS X

**What is the current behavior?**
Going to admin panel -> Plugins -> File Upload and changing the "Maximum size allowed (in MB)" doesn't do anything. Calling a method where a file is uploaded that is larger than 1 MB will throw:
`
{ PayloadTooLargeError: request entity too large
    at readStream (/usr/local/lib/node_modules/strapi/node_modules/raw-body/index.js:155:17)
    at executor (/usr/local/lib/node_modules/strapi/node_modules/raw-body/index.js:112:5)
    at new Promise (<anonymous>)
    at getRawBody (/usr/local/lib/node_modules/strapi/node_modules/raw-body/index.js:111:10)
    at /usr/local/lib/node_modules/strapi/node_modules/co-body/lib/json.js:41:14
    at <anonymous>
  message: 'request entity too large',
  expected: 6572413,
  length: 6572413,
  limit: 1048576,
  type: 'entity.too.large' }
`
even when the allowed size is updated to 100000 MB

Tried changing it in all the tabs (development/staging/production), doesn't do anything.

**Steps to reproduce the problem**

**What is the expected behavior?**
Raising to allowed size should allow larger files to be uploaded

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @reinisriekstins I'm not able to reproduce. I think it can come from your server configuration.

**Comment by geometrybase** [comment]
If you server is behind nginx, it maybe nginx problem. try change `client_max_body_size 1000M;` in http or server config

**Comment by derrickmehaffy** [comment]
@reinisriekstins Geo is right if you are using a proxy like Nginx or Apache you need to increase the limits there as well.

**Comment by Froelund** [comment]
I just the same problem. For me, the issue was that the form being submitted exceeded the allowed limit for a form.
Luckily this can be configured for strapi in `request.json` configuration.
In the `parser` section you can define these limits:
```
...
  "parser": {
    "enabled": true,
    "multipart": true,
    "formLimit": "5mb",
    "jsonLimit": "5mb"
  }
...
```

**Comment by prawee** [comment]
@geometrybase solved for me

**Comment by cube-dan** [comment]
Sorry in advance for the thread jacking but [google led me here](https://www.google.com/search?q=%22strapi%22+%22413+%22Payload+Too+Large%22).

@Froelund's suggestion worked perfectly for me. Specifically, I've dropped this...
```
...
  "parser": {
    "enabled": true,
    "multipart": true,
    "formLimit": "5mb",
    "jsonLimit": "5mb"
  }
...
```
... into: {strapi-root}/config/environments/development/request.json 

After that change strapi allows me to send larger text strings into a text field: 
![image](https://user-images.githubusercontent.com/8559668/67150274-518a8b00-f26a-11e9-9c2d-4dacb3ce8436.png)

Without @Froelund's suggestion I get this error on the client side:
```
Failed to load resource: the server responded with a status of 413 (Payload Too Large)
```
(full error text, from [strapi/pino](https://strapi.io/documentation/3.0.0-beta.x/concepts/logging.html#logging), at bottom )

It seems like formLimit and jsonLimit should be available here:

![image](https://user-images.githubusercontent.com/8559668/67150384-c9a58080-f26b-11e9-8532-f32f0a57dced.png)

I'll upgrade to the latest strapi (I'm still on beta.11) and open a feature request if the feature and a feature request doesn't already exist.

Thanks guys. Again, sorry for the threadjacking.

[2019-10-19T19:18:56.951Z] error PayloadTooLargeError: request entity too large
    at readStream ([...]/src/node_modules/raw-body/index.js:155:17)
    at executor ([...]/src/node_modules/raw-body/index.js:112:5)
    at new Promise (<anonymous>)
    at getRawBody ([...]/src/node_modules/raw-body/index.js:111:10)
    at [...]/src/node_modules/koa-body/node_modules/co-body/lib/json.js:41:14

**Comment by lauriejim** [comment]
Hello @cube-dan !
Thank you for this feedback.
We will remove the UI of the settings manager to let all these configurations editable by updating the wite files directly.
We will document this issue and the fix.

**Comment by Renishpr** [comment]
It seems like after the update all the files like 
```
{strapi-root}/config/environments/development 
{strapi-root}/config/environments/staging
{strapi-root}/config/environments/production 
```
have been removed.
i am not able to find `{strapi-root}/config/environments/development/request.json` anywhere

**Comment by kzkr** [comment]
Same here. I can't find these files, it does not work even if I try to create such a file in my config folder.
Working locally on the --quickstart environment.

Thanks for your help!

**Comment by devpascoe** [comment]
same here @kzkr

**Comment by TheChileanKink** [comment]
I'm not able to find those files either.

**Comment by derrickmehaffy** [comment]
Hi everyone, please open up a new issue (following the bug template) so we don't bring up old issues.
