### ISSUE TITLE
Changing field name wipes fields data for all entries

### ISSUE THREAD

**Issue by gregg-cbs** [strapi/strapi#19075]
## Bug report
In strapi you make it easy to change a fields name as if doing so would have no consequences. Changing a fields name is destructive, it deletes all data for that field but nothing tells you of this fact. Strapi should retain the fields data, im not sure why you wouldnt rename the table column or move the data from the old column to new column if you are deleting the old column.

### Required System information
- Node.js version: 18
- NPM version: 9.5.1
- Strapi version: 4.15.0
- Database: postgres
- Operating system: Windows
- Is your project Javascript or Typescript: TS

### Describe the bug

Changing a field name in the strapi admin panel results in loss of all data in all rows for that field.

### Steps to reproduce the behavior

1. Go to content type builder
2. Click on a collection
3. Edit a field and change its name, save
4. See now that fields data has been wiped out
5. Notice no warnings were mentioned that this action is destructive

### Expected behavior
When renaming a field I would expect the data to stay in tact.

### Screenshots
![image](https://github.com/strapi/strapi/assets/57114335/85895504-3a08-4288-beb5-771631478851)
![image](https://github.com/strapi/strapi/assets/57114335/14c4c57d-b1c5-4d16-82a7-43d96af2a7f0)

**Comment by gregg-cbs** [comment]
I guess you can only rename fields on development so this would never happen on live.

**Comment by derrickmehaffy** [comment]
The problem is the context of a rename isn't known. When you rename a field and that's saved to the schema file, when the app restarts it looks at the schema file and makes the schema changes it needs to, but effectively it sees that rename as you deleted a field and added a new one since the schema file has no history, it's effectively a diff.

**Comment by gregg-cbs** [comment]
Thanks for responding even though i had closed the issue. I guess each field could get given an ID so the diff becomes a bit more sophisticated. Also when renaming a field it loses all its interface settings - width, placement on the page, settings etc.

I think an alert should show when renaming a field so the user can know its destructive on many levels because I did not expect renaming to have so many repercussions because it was so easy to do.

But overall understandable.
