### ISSUE TITLE
Handle correctly the \u202F unicode character

### ISSUE THREAD

**Issue by EwenQuim** [strapi/strapi#19108]
### Required System information

- Typescript:
- OS: darwin-arm64
- Strapi Version: 4.15.4
- Node/Yarn Version: yarn/3.2.3 npm/? node/v20.9.0 darwin arm64
- Edition: Community
- Database: mysql

### Describe the bug

Strapi returns a 500 error with no further logs when trying to POST or PUT a ressource with this character. It's really hard to debug since it just looks like a normal space character, except it isn't

### Expected behavior

To accept the \u202F unicode character

https://www.fileformat.info/info/unicode/char/202f/index.htm

**Comment by derrickmehaffy** [comment]
This is not a bug within Strapi but the charset you are using in your database.

https://dev.mysql.com/doc/refman/8.0/en/charset-mysql.html
