### ISSUE TITLE
Package subpath './server/utils' is not defined by "exports"

### ISSUE THREAD

**Issue by MoeedthePessimist** [strapi/strapi#19117]
### Required System information

- Node.js version: v18.19.0
- NPM version: v10.2.3
- Strapi version: v4.12.4
- Database: Postgres
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug
Error occurs when running **strapi develop**

Package subpath './server/utils' is not defined by "exports" in project-path\node_modules\@strapi\plugin-users-permissions\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server/utils' is not defined by "exports" in L:\personal projects\dispatch-one\node_modules\@strapi\plugin-users-permissions\package.json

    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (L:\personal projects\dispatch-one\dist\apps\backend\src\extensions\users-permissions\controllers\auth.js:7:24)

### Steps to reproduce the behavior

1. Go to project directory
2. Run **yarn install** to install all the dependencies
3. Run **strapi develop --watch-admin**
4. Error is shown

### Expected behavior

It should build the admin panel and run the backend successfully.

### Screenshots

![image](https://github.com/strapi/strapi/assets/63580699/f0f60e82-93b4-4370-9388-b2a39ae0d0dd)

### Additional context

This error recently occured after the strapi package was accidentally upgraded to v4.15, after downgrading this error started to show up and haven't been resolved yet. Is there a quick resolution to this error as this has become a road block in our development process.

**Comment by BasharOsman** [comment]
I faced the same problem when i was import service from the plugin-users-permissions:
the code i was importing is:

`
import { getService } from '@strapi/plugin-users-permissions/server/utils';
`

work around is to copy the function the file i want to use

i think you did import function from server/utils in src\extensions\users-permissions\controllers\auth.js

**Comment by MoeedthePessimist** [comment]
> I faced the same problem when i was import service from the plugin-users-permissions: the code i was importing is:
> 
> `import { getService } from '@strapi/plugin-users-permissions/server/utils';`
> 
> work around is to copy the function the file i want to use
> 
> i think you did import function from server/utils in src\extensions\users-permissions\controllers\auth.js

yes thats correct, it was working fine for the previous 4-5 months but recently due to upcoming updates it started causing this error.

Another possible work around is to use `strapi.plugin('users-permissions').users.services` which is the correct way to use services  provided by the plugins. However due to poor documentation it wasn't discoverable until now where I came across another issue mentioning this.

**Comment by ArtKuz** [comment]
@MoeedthePessimist could you please tell me where you found the instruction with `strapi.plugin('users-permissions').users.services`?
