### ISSUE TITLE
Media Library Admin ui crash

### ISSUE THREAD

**Issue by BasharOsman** [strapi/strapi#19129]
### Required System information

- Node.js version: v18.19.0
- NPM version: 10.2.3
- Strapi version:14.16.2
- Database: sqlite
- Operating system: ubuntu
- Is your project Javascript or Typescript: Javascript

### Describe the bug

the Media Library in strapi admin ui crash and give 
main.f134dfdf.js:487 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
in the browser console, i tried to down the strapi to 14.15.5 same error the error show only after upload file ore create folder

### Steps to reproduce the behavior

1. install new strapi with quickstart comand
2. Go to Media Library  
3. create folder or upload file 
4. See error on console and the page go blank 

### Expected behavior

i should open and upload files and folders without any errors

### Screenshots

xxx

### Code snippets

xxx

### Additional context

i faced the error before i think it was because i was upload file without mimeType but this time every thing as expected and the error happens even for creating a folder
it maybe just my case 
 i try it on other production typescript strapi 14.16.2 and there no problem

**Comment by jianhuatu** [comment]
这个问题一直存在，我新安装了strapi，进入后台后，点击关闭弹层就会出现，或者点其他目录也会出现，很常见的问题。
"dependencies": {
    "@strapi/strapi": "4.17.1",
    "@strapi/plugin-users-permissions": "4.17.1",
    "@strapi/plugin-i18n": "4.17.1",
    "@strapi/plugin-cloud": "4.17.1",
    "mysql": "2.18.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
我安装在mac pro 连接mysql

**Comment by Ben-Zahler** [comment]
@BasharOsman were you able to resolve this? A customer of us has reported exactly the same issue, it does not happen for us.

**Comment by kaue-delmonte-acn** [comment]
Same here.

**Comment by petibekesi7** [comment]
Same here! It never occurs to me as the Super Admin, but for one customer of mine who has Editor rights, it happens every single time she tries to upload media. Advice would be highly appreciated.
