### ISSUE TITLE
npx create-strapi-app error while installing dependencies 

### ISSUE THREAD

**Issue by bengodev** [strapi/strapi#19121]
### Required System information

- Node.js version: v20.5.1
- NPM version: 9.8.0
- Strapi version: 4.16.2
- Database: none yet
- Operating system: macOS ventura 13.6
- Is your project Javascript or Typescript:  Javascript

### Describe the bug
Just trying to get started with Strapi. Running this command in terminal: `npx create-strapi-app@latest cms --quickstart` and getting the below error message.
```bash
Need to install the following packages:
create-strapi-app@4.16.2
Ok to proceed? (y) y
Creating a quickstart project.

Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm ERR! code 1
npm ERR! path /Users/username/www/cms/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /Users/username/www/cms/node_modules/esbuild/install.js:132
npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Expected "0.19.2" but got "0.18.20"
npm ERR!     at validateBinaryVersion (/Users/username/www/cms/node_modules/esbuild/install.js:132:11)
npm ERR!     at /Users/username/www/cms/node_modules/esbuild/install.js:285:5
npm ERR!
npm ERR! Node.js v20.8.0

npm ERR! A complete log of this run can be found in: /Users/username/.npm/_logs/2023-12-26T05_17_11_808Z-debug-0.log
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /Users/username/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/Users/username/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/Users/username/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (/Users/username/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)
```

### Steps to reproduce the behavior

1. Open `terminal'
2. Run this command '`npx create-strapi-app@latest cms --quickstart`'
3. See error

### Expected behavior

`npm install` should complete without errors.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by khuongduy354** [comment]
I don't think this is a problem with Strapi, I run your commands on my machine which works fine. 
Check this out: [stackoverflow](https://stackoverflow.com/questions/72776325/npm-warning-config-production-use-omit-dev-instead)

**Comment by kiyoshi-satoo** [comment]
Same

**Comment by PBHAHAHA** [comment]
Same

**Comment by falnos24865** [comment]
Not sure why this is closed, its clearly still an issue and preventing me from using Strapi entirely.

**Comment by DyncEric** [comment]
Creating a quickstart project.
Creating a new Strapi application at /root/qika-demo.
Creating files.
Error while installing dependencies:
error Couldn't find any versions for "@strapi/strapi" that matches "0.0.0-experimental.8c0ce630983672c5ddb15e4a853fabb826def95e"
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /root/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/utils/usage.js:34:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/root/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/utils/usage.js:33:37)
    at createProject (/root/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (/root/.npm/_npx/363c03cf1fb7d8d1/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:18:3)

**Comment by derrickmehaffy** [comment]
You are using an experimental which isn't supported.

**Comment by shahalam22** [comment]
Facing same problem. How can get rid of this problem???

**Comment by adamsimonini** [comment]
Same issue here. Both my colleagues with Macbooks, exact same version, can run the quickstart command flawlessly. For me, I get this error:

```
Error while installing dependencies:

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
```

**Comment by jonrigerths2** [comment]
Same issue here - also a duplicate of https://github.com/strapi/strapi/issues/19478

Why are these just getting auto-closed?

**Comment by klaudiaaaj** [comment]
For me there was problem that strapi had in the default template references to better-sqlite3 (8.6.0).

Node ^18 does not fully support this version.

Upgrading better-sqlite3 package worked:

npm install better-sqlite3@^9.0.0

**Comment by reslear** [comment]
Go to error path like `cd /Users/admin/.npm/_npx/6858f854713ad077/`
open terminal in folder and run `npm install esbuild` 
(is need switch node version `fnm use 20`)
fixed!
