### ISSUE TITLE
Content manager getting blank

### ISSUE THREAD

**Issue by nidhin077** [strapi/strapi#19130]
### Required System information

- Node.js version: v20.10.0
- NPM version: 10.2.3
- Strapi version:v4.16.2
- Database: mysql
- Operating system: windows 2016
- Is your project Javascript or Typescript:Typescript

### Describe the bug

Actullay I'm attempting to deploy the Strapi on an IIS Windows server. We were able to see the user interface after the deployment was successful, but we were met with a blank screen when we attempted to access the content management. We attempted a few remedies, but they were ineffective. Would you kindly check the issue and give a solution?

### Steps to reproduce the behavior

Try to deploy the latest version strapi on a Windows machine and configure the same in IIS, then try to access the content manager 

### Expected behavior

Load with proper content

### Screenshots

![image](https://github.com/strapi/strapi/assets/107123789/3b558a34-813e-430a-9953-0f6bebea7db0)

**Comment by nidhin077** [comment]
Hi,

I tried a new project, but I encountered the same problem. Could you perhaps try deploying it in IIS? If you are unable to reproduce the problem, could you kindly give the IIS deployment steps for the strapi?

**Comment by derrickmehaffy** [comment]
> Hi,
> 
> I tried a new project, but I encountered the same problem. Could you perhaps try deploying it in IIS? If you are unable to reproduce the problem, could you kindly give the IIS deployment steps for the strapi?

We didn't recommend nor officially support IIS as a reverse proxy. Strapi itself cannot just be deployed in a web server.

**Comment by fated-x** [comment]
I am also experiencing this in both Windows and Linux. Running `strapi build` and `strapi develop` both appear to work in the CLI. But when you try to load the Admin Panel, the following frontend is generated:

`Uncaught TypeError: (0 , y.defaultMemoize) is not a function
    at main.73fd53fb.js:5846:15826
    at 20699 (main.73fd53fb.js:5846:41225)
    at f (runtime~main.8292a421.js:1:141)
    at 60821 (main.73fd53fb.js:393:485)
    at f (runtime~main.8292a421.js:1:141)
    at a (main.73fd53fb.js:5895:264940)
    at main.73fd53fb.js:5895:264951
    at b (runtime~main.8292a421.js:2:230)
    at main.73fd53fb.js:1:101`
    
It's worth mentioning that the root URL works just fine. But going to /admin throws the error:

<img width="606" alt="image" src="https://github.com/strapi/strapi/assets/14049283/f8f6b095-d9a2-46ab-aee5-dd234b467d64">

**Comment by VanessaEly** [comment]
Hi team, we are getting the exact same `defaultMemoize` error in all strapi versions after v4.15.5, as reported above. We are trying to update it because of some vulnerabilities but admin panel doesn't work anymore. Not sure why you weren't able to reproduce, but seems this is a real issue.
<img width="749" alt="image" src="https://github.com/strapi/strapi/assets/9198120/71a557c9-9048-4521-93f9-503095521789">

**Comment by derrickmehaffy** [comment]
Can you all share your package.json files please as I'm guessing this is probably a community plugin

**Comment by VanessaEly** [comment]
I removed some infos that are probably not relevant
```
{
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "unit-test": "cross-env NODE_ENV=test jest",
    "unit-test:coverage": "cross-env NODE_ENV=test jest --coverage",
  },
  "devDependencies": {
    "@commitlint/cli": "^18.0.0",
    "@commitlint/config-conventional": "^18.0.0",
    "eslint": "^8.14.0",
    "husky": "^8.0.0",
    "jest": "^29.7.0",
    "webpack": "^5.76.3"
  },
  "dependencies": {
    "@jest/types": "^29.6.3",
    "@strapi/plugin-i18n": "^4.6.0",
    "@strapi/plugin-users-permissions": "^4.6.0",
    "@strapi/strapi": "^4.15.0",
    "config": "^3.3.7",
    "dotenv": "^16.3.1",
    "lodash": "^4.17.21",
    "pg": "^8.11.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^5.3.4",
    "reselect": "^5.0.1",
    "strapi-plugin-populate-deep": "^3.0.0",
    "styled-components": "^5.3.11"
  },
  "engines": {
    "node": ">=12.x.x <=18.x.x",
    "npm": ">=6.0.0"
  },
}
```

**Comment by nidhin077** [comment]
@derrickmehaffy, If possible, please setup the strapi for IIS deployment that would be good.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy, If possible, please setup the strapi for IIS deployment that would be good.

I haven't used windows in probably 8 years and it's highly unlikely a bug within Strapi itself would cause a problem with IIS as it works fine with basically any other reverse proxy.

**Comment by preist** [comment]
I had the same issue when the version of `@strapi/strapi` was different from other `@strapi/****` libraries.

Try updating `@strapi/plugin-i18n`, `@strapi/plugin-users-permissions` to the latest versions @nidhin077

**Comment by VanessaEly** [comment]
Issue is still happening, even when I try to use `@strapi/strapi`, `@strapi/plugin-i18n` and `@strapi/plugin-users-permissions` all in the same and latest version (4.19.0). This is not related to windows nor ISS, I'm running this on a Macbook M1 and still have the same exact issue as already reported, I already shared the `package.json` and tried to update the libs to the latest version that is available today, nothing changed and the error is still there, admin panel doesn't open at all. We are unable to update Strapi because of this issue (which we need to because of identified vulnerabilities), and we don't reference the function that is throwing the error anywhere in our own code.

`Uncaught TypeError: (0 , y.defaultMemoize) is not a function at main.73fd53fb.js:5846:15826 at 20699 (main.73fd53fb.js:5846:41225) at f (runtime~main.8292a421.js:1:141) at 60821 (main.73fd53fb.js:393:485) at f (runtime~main.8292a421.js:1:141) at a (main.73fd53fb.js:5895:264940) at main.73fd53fb.js:5895:264951 at b (runtime~main.8292a421.js:2:230) at main.73fd53fb.js:1:101`

**Comment by betoflakes** [comment]
I have the same issue runing in unix based system, blank screen at admin route, but with the next error
![CleanShot 2024-01-31 at 10 00 02](https://github.com/strapi/strapi/assets/1946702/5835cfad-938e-486e-9c5d-cb5124985a71)

**Comment by derrickmehaffy** [comment]
Can you please set the following env var `STRAPI_ENFORCE_SOURCEMAPS=true` and provide the logs you previously mentioned after doing so. It'll provide more useful information for the admin in the console.

**Comment by derrickmehaffy** [comment]
Both of your errors are also entirely different and most likely are not related to this issue.

**Comment by VanessaEly** [comment]
In my case setting `STRAPI_ENFORCE_SOURCEMAPS=true` didn't throw any errors, the error is happening in the browser console. Should I open a new issue related to the defaultMemoize bug? Error is still happening, was reported here more than once and seems like no one is looking at it

**Comment by VanessaEly** [comment]
Just found out the cause of the issue, new strapi version's admin page breaks when using  `reselect` library, removing it solves the issue, which means that if you tested with the `package.json` I sent you would be able to replicate the issue

**Comment by joshuaellis** [comment]
This would make sense since `reselect` is list in our dependency alias list. Good news is it won't be an issue in v5 though. Did you try keeping the dependency and working with the `vite` bundler we now have?

**Comment by davidsonsns** [comment]
for those who landed here too, as suggested [here](https://github.com/strapi/strapi/issues/16679#issuecomment-1876069745), i downgraded the `reselect` version to `^4.1.8` and it worked beautifully

**Comment by sabir-Hussain** [comment]
> I had the same issue when the version of `@strapi/strapi` was different from other `@strapi/****` libraries.
> 
> Try updating `@strapi/plugin-i18n`, `@strapi/plugin-users-permissions` to the latest versions @nidhin077

Thanks a lot. It solved my issue :)
