### ISSUE TITLE
Data Loss in Content-Type Table After Schema Modification

### ISSUE THREAD

**Issue by savyjs** [strapi/strapi#19141]
### Required System information

Launched In: 1607 ms
Environment: production
OS: linux-x64
Strapi Version: 4.16.2
Node/Yarn Version: yarn/1.22.21 npm/? node/v20.10.0 linux x64
Edition: Community
Database: mysql2 (MySQL v8)
 
### Describe the bug

Hello,

I've encountered a recurring issue of data loss, happening approximately 5 or 6 times in the last month. I operate a Strapi instance on PM2 with ```NODE_ENV=production```, initiated using the yarn develop command. At the time of the incident, there were approximately 68,000 records in my content-type.

The problem arose when I modified the schema by setting draft options to false and introducing a new boolean attribute, ```is_active```, with a default value of true. Subsequently, I executed the usual command on the server:

```
git fetch && git reset --hard origin/develop && pm2 reload 0
```
Upon Strapi restarting, I observed that the changes were applied, but to my dismay, all records were deleted.

I also researched this issue and noticed similar occurrences reported by others. However, the Strapi team consistently asserted statements such as 'we don't delete all data,' 'we cannot reproduce it, so it's untrue,' 'you are using Docker and Docker with SQLite, and this is the reason,' and 'only unknown columns and tables get deleted.' Despite these explanations, I consider this a very serious bug.

Imagine utilizing Strapi for a critical project, and suddenly, with a minor modification, thousands of essential data are deleted in production. This scenario demands serious attention and corrective action.

I appreciate any insights or guidance on resolving this critical issue. Thank you.

### Steps to reproduce the behavior

Attempting to reproduce the issue by modifying and adding other columns proved unsuccessful. This erratic behavior is concerning, as it has occurred a few times, and I am troubled by the lack of clarity on why it happened.

### Expected behavior

1- If a column is added or removed, the system should retain all other data and only modify or delete the specific column.
2- The system should not drop unknown tables without permission or explicit user consent. Throwing exceptions and crashing the backend is preferable to losing important data.
3- If a DROP TABLE operation is needed, the system should ask for permission.
4- Consider adding a rename option to prevent the loss of important data during schema modifications.

### Screenshots

![image](https://github.com/strapi/strapi/assets/24469125/c24f2620-c971-450e-902c-5ed7b93dfc13)

![image](https://github.com/strapi/strapi/assets/24469125/21f3df94-7826-4094-987f-08a46645a703)

### Additional context

There should be better documentation addressing this critical issue. 
Clarifications on the differences between runMigration and forcedMigration in the database configuration would be helpful. The current documentation is unclear and does not explain the exact behavior of these variables. a practical solution to enhance data safety during such operations is crucial.
 
I think this is a very important issue and has occurred to me multiple times. However, I don't have a clue as to why it happens, and I cannot confidently reproduce it whenever I want. But it does happen, both to me and to others. In the coming days, I will make an effort to find out why it happens and understand the exact reasons behind it. If I discover the exact reason, I will share a test repository to help address and resolve this issue more effectively.

**Comment by savyjs** [comment]
I successfully reproduced the issue again, and this time, I documented the changes. Unfortunately, I can't share them due to privacy concerns, but I'll outline the exact steps:

1- I had a table filled with approximately 120,000 customer records.
![image](https://github.com/strapi/strapi/assets/24469125/dd5ab2b1-116c-40ae-8255-0c956d79904c)


2- I modified the schema, setting the draft to false, and added a default value for the is_active column.
![image](https://github.com/strapi/strapi/assets/24469125/02c87afd-8ce9-45c2-82c7-eec6868ba389)


3- I used the command below to rebuild Strapi in the production environment (same as before):

```
git fetch
git reset --hard origin/develop
yarn build
yarn start
```

Environment: production
OS: linux-x64
Strapi Version: 4.16.2
Node/Yarn Version: yarn/1.22.21 npm/? node/v20.10.0 linux x64
Edition: Community
Database: mysql2 (MySQL v8)

4- Boom! Most crucial data in my production environment got deleted! I restarted the migration to seed the database again. (504 records were added when I took the screenshot)
![image](https://github.com/strapi/strapi/assets/24469125/bc21c572-f815-4ff5-b445-91d50e7c176e)



I am attempting to share this as a repository or using an alternative method so that you can check it yourself.

**Comment by savyjs** [comment]
I've identified several issues in the code, including some TODOs in the database files. 

I completely understand if the development team is currently occupied and may not have time to address these concerns. If there's any way I can assist, please let me know.

![image](https://github.com/strapi/strapi/assets/24469125/d69e7943-1603-4bff-bc33-3353643b058c)


Concerning the default value of forceMigration, I strongly recommend changing it. Having it always set to true by default is not a rational choice.
![image](https://github.com/strapi/strapi/assets/24469125/6c555ec6-74bc-44d2-a170-e60750eafda8)

 Here are scenarios where it's appropriate to be true:
1- During the first startup to create necessary schemas.
2- When there is no data in the table.
3- In development when the user expects the table to be dropped.
4- In production, the default value should be` false`. It should only be set to `true` when the user explicitly agrees with the deletion or has configured the environment accordingly.

Additionally, it's advisable for a function to consistently return the same data type. In this scenario, returning an Exception instead of void would be preferable. (Also, note that the `if` statement used here is not considered best practice.)
![image](https://github.com/strapi/strapi/assets/24469125/dec9e9b0-d6d8-483a-a476-a4a88890c4e8)

**Comment by derrickmehaffy** [comment]
I don't at the moment have time to expand but I will in a little bit, removing tables and columns that don't match the Strapi schema in the database is absolutely 100% intentional and is related to #1114

The only time you would normally lose data is during a field rename since the context of "renaming" doesn't exist and the schema sync happens on boot up of which Strapi works on a binary diff so it sees that a field has been "deleted" and a new one "created" hence the data loss but this can be worked around using our built in data migration scripts.

Strapis schema source of truth is the schema stored on the filesystem not the database and it's intentional that orphaned tables and columns that don't exist in Strapi are purged from the DB, that is not something we will be willing to change. However properly informing and educating users is absolutely doable.

**Comment by derrickmehaffy** [comment]
Expanding a bit here (there is quite a lot of information here to go through so I'll do it bit by bit).

Your original problem was disabling draft & publish and the resulting data in a draft state being deleted however the issue is you modified the schema manually (which is fine but we can't exactly trigger a warning here that requires user input else that would be a breaking change and practically impossible to do without impacting the less technical users).

What we do instead is that if you disable this via the content-type builder we do in fact show a warning:
![image](https://github.com/strapi/strapi/assets/8593673/d4244b9d-8c8a-41f0-9271-71f0a6c695fe)

---

Regarding renaming a field and losing data that is something we want to address but it would require quite a bit of effort to include a "context awareness" to the content-type builder that Strapi's automated schema sync (or as I call it the sanity check) on bootup to read and understand: https://feedback.strapi.io/developer-experience/p/gracefully-handle-renaming-of-content-types-and-fields-in-the-ctb

What will most likely happen here is that we will completely refactor the content-type builder as a whole and include this as a feature of it as it's something we have wanted to do for a while but lack the time on while there are other more important issues and features to work on.

---

To the point of whether or not orphaned or custom tables/columns should be purged to begin with; this is extremely subjective to a user or honestly software in general. At some point we need to make a choice and for now we have already made that choice of no, if the Strapi source of truth (the schema files on the file system) are not aware of something then it should not be in the database hence it's dropped/removed. Leaving orphaned tables, columns, constraints, indexes, ect in the database that Strapi isn't aware of is a problem we have had several times over the years and especially during version migrations (mainly the v3 to v4 migration) and caused countless issues. 

While it doesn't expressly mention this particular case we do have a big warning on the database configuration page here: https://docs.strapi.io/dev-docs/configurations/database that expressly states:

![image](https://github.com/strapi/strapi/assets/8593673/87346955-8002-4903-a7c9-8bdbb63a9e5f)

And in one of your cases you reset your local base branch to that of the remote HEAD which reverted the local Strapi schema on the file system and during bootup the database was "forced" to match this updated version of the schema so that is by all accounts completely intended.

---

Finally as to a workaround for renaming the field (or even disabling draft & publish) if you did want to rename the column or force set the publishedAt date to force everything from a draft to published state you can write a small migration script using our native custom database migrations: https://docs.strapi.io/dev-docs/database-migrations

I will go ahead and set this issue as closed as I don't consider it a bug but I won't lock it to allow you (or others) to comment in case I'm missing something and there is actually a bug here. I'm not trying to be rude or anything we are just quite strict to limit the GH issues to valid bug reports and not feature requests, enhancements, or discussions.

**Comment by savyjs** [comment]
Hi @derrickmehaffy,

I completely agree with your emphasis on education and documentation. 
While my primary concern isn't just about renaming a column and deleting its data, there's a unique situation where preserving existing data while renaming the column becomes crucial. In a production environment, finding a practical approach without disrupting service or risking data loss is paramount.

Specifically, I'm addressing the potential risk of losing ALL IMPORTANT DATA ON PRODUCTION due to a column modification and changing draft status. This issue takes precedence given its potential impact.

Regarding your mention that Strapi currently has no plans to support unknown tables (which could be considered a weakness), I would like to draw your attention to some relevant TODOs outlined in the codebase:
https://github.com/strapi/strapi/blob/762abbf7f8a8cae3cda9b6affcea50be8abc3ce9/packages/core/database/src/schema/index.ts#L79
```
// TODO: support options to migrate softly or forcefully
// TODO: support option to disable auto migration & run a CLI command instead to avoid doing it at startup
// TODO: Allow keeping extra indexes / extra tables / extra columns (globally or on a per table basis)
```


While I acknowledge that the Strapi team may currently lack the bandwidth for even minor adjustments, such as checking the environment before dropping the entire table to add a default value to a column, I wanted to highlight this as a significant concern. My intention is to address a potentially serious bug, as I have a deep appreciation for Strapi and want to prevent any harm to its reputation or cause trust issues among users. If there's any way I can contribute to a resolution, I would be more than willing to assist.

**Comment by derrickmehaffy** [comment]
The problem there is not so much the deleting of the data it's the order of operations. We do not support nor want users running development mode in a deployed environment meaning the expectation for users is to do the following (taking for example the draft & publish use-case here).

1) The user disables draft & publish on a content-type and wants all data previously in a draft state to be published
2) This is done on a local environment where the data doesn't matter
3) User disables D&P
4) User writes a migration script https://docs.strapi.io/dev-docs/database-migrations to automatically modify all the data in the content-type
5) User shuts down application and pulls a snapshot copy from production
6) User starts application locally to test the intended script does as expected
7) User deploys to staging again to test in a real world deployment that script functions as intended
8) User **takes a database backup before deploying changes** 
9) User deploys into production

If something bad happens there should be backups (one of the reasons we have backups in Strapi Cloud and likewise why we developed the DTS feature for import/export/transfer)

**Comment by derrickmehaffy** [comment]
Regarding the TODO comments, keep in mind those comments were written 3 years ago:

![image](https://github.com/strapi/strapi/assets/8593673/f8eceb6d-c964-449a-b13a-45daa749fca2)

And we haven't had the time nor justification to implement them given the needs of most of our users

**Comment by savyjs** [comment]
Thank you for the guidance, and your patience.

i agree, backup is a crucial step in every deployment, regardless of the framework or system. It's a mandatory practice to ensure the safety of data.

also the data transfer feature is excellent and very helpful. I find it to be a valuable asset.

However, I have some concerns.
In my scenario, I find it necessary to pause the real-production process because new data may be introduced to the system, and this data could be critical. I want to avoid losing anything, so my users have to wait until the system becomes operational again. Firstly, this approach goes against the concept of rolling deployment. 
(and, worse, it becomes challenging when two Strapi instances with different schemas, current version and new version, are connected to the same database.)

Secondly, when I run Strapi locally—particularly based on my two past experiences shared above—all customer data is wiped. While I understand this is expected, I proceed to backup, write a migration script dedicated to the required change, and thoroughly test it. During this time, my production remains inactive, and users are waiting. I then explore solutions to adapt my old data into the new structure. If fortunate, this process can be completed within 10 minutes, resulting in fresh and correct data and data structure.

Following this, the challenge arises of publishing my local changes to the server. Should I replace my local database with the production database? Running Strapi, even in production, leads to the dropping of table and the deletion of the entire dataset. If this is the case, I must wait until my data is transferred to the server. This transfer may take some time, especially when dealing with a substantial amount of data. (Not to mention, there may be relational issues that need addressing.)

Once the data transfer is complete, I can restart Strapi and resume receiving fresh data again.

I'm not sure if this is exactly what you said; it was my point of view. For my case, where I use Ubuntu and MySQL, On-Premis.


I don't know if having a migration script will help or not. I'm uncertain about when and under which conditions all data will be deleted, and I don't know how migration scripts will prevent this or if a smooth deployment is possible with migrations. 
If it is possible to prevent dropping the whole table, I can consider testing it.

**Comment by derrickmehaffy** [comment]
DTS is indeed not the greatest for live applications, my point of pulling the data from production to staging or local should have no impact on production it's only used for testing against real data.

> Should I replace my local database with the production database?

Absolutely not. 

If you are working locally you should pull a snapshot copy of the production database **to test against** but after the testing that data should not be mirrored back to production. If I summarize this a bit more clearly

- Development (local env) is used to build and test **code changes**
- Staging (local or deployed) is used to test code modifications against production data to ensure code modifications don't negatively impact the data
- Production is self-explanatory :wink:  

If you'd like I can probably explain this a bit better over voice instead, every business day (M-F excluding holidays) from 10:30am to 12:30pm PST (California time) we do a daily office hours in our Discord where me and @PaulBratslavsky sit and chat with community users. If you'd like to hop on I can explain this with some demo examples. https://discord.strapi.io

**Comment by savyjs** [comment]
My apologies. Since I was using my mobile phone, I didn't see this part of your answer, and I was confused about why my data got deleted, so I was nervous. However, if you are certain that data loss occurred because they were draft items and with a simple migration, it is possible to change the status to publish, and then schema change won't delete them anymore, it's okay for me. It solves my problem, and I can sleep better tonight knowing my customer data won't be deleted anymore. 😊

> Your original problem was disabling draft & publish and the resulting data in a draft state being deleted however the issue is you modified the schema manually (which is fine but we can't exactly trigger a warning here that requires user input else that would be a breaking change and practically impossible to do without impacting the less technical users).
> 
> What we do instead is that if you disable this via the content-type builder we do in fact show a warning: ![image](https://private-user-images.githubusercontent.com/8593673/293996080-d4244b9d-8c8a-41f0-9271-71f0a6c695fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTM4OTQsIm5iZiI6MTcwNDMxMzU5NCwicGF0aCI6Ii84NTkzNjczLzI5Mzk5NjA4MC1kNDI0NGI5ZC04YzhhLTQxZjAtOTI3MS03MWYwYTZjNjk1ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMjAyNjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM3ZjViMjJlMTFhNjBjNWI0NGFmZTBhYTI1NDE0Y2RjOGQ5MjBiNTcyN2E5ZTA0MTdlOWJkN2ZlZTdiODg0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-Lm2_Ijw4nFGytvO3K0YGMndQVyrdomthBeA8XJoZLk)
> 
> Regarding renaming a field and losing data that is something we want to address but it would require quite a bit of effort to include a "context awareness" to the content-type builder that Strapi's automated schema sync (or as I call it the sanity check) on bootup to read and understand: https://feedback.strapi.io/developer-experience/p/gracefully-handle-renaming-of-content-types-and-fields-in-the-ctb
> 
> What will most likely happen here is that we will completely refactor the content-type builder as a whole and include this as a feature of it as it's something we have wanted to do for a while but lack the time on while there are other more important issues and features to work on.

Thanks for the invitation. I'm not sure if I can join, but it would be my pleasure. Besides that, I still have a little concern about the rolling deployment and multi-instance scenario that I mentioned. I want to find an easy and certain approach to have multiple running Strapi instances with the same database without any conflict or data loss.

**Comment by derrickmehaffy** [comment]
Rolling deploys have always been difficult for many many reasons and I'm probably the biggest supporter of horizontally scaling Strapi in production (I practically wrote all of the documentation and guides about this when I was just a community member before Strapi hired me).

The best way I explain it to our customers to do proper horizontal scaled deployments is either one of two ways:

- Blue/Green deployments (difficult if you have a very noisy write application)
- Scale back the cluster to a single node, update, scale back up (this is generally what most of our enterprise customers do)

For the scale down/up method you generally want to do this when you know you have the least amount of traffic or you schedule a degraded service maintenance period where you can null route the traffic during the upgrade.

Something else many of our customers do is they run two cluster with the same code/database where you have the primary "traffic cluster" with the auto-migration system turned off and you have a separate "master cluster" (which is actually just one node) that does all of the database migration. You could temporarily run into a few 4xx or 5xx errors during the upgrade period but that usually only lasts a few seconds.

We have a fairly wide enterprise customer base where many are using very large horizontally scaled instances (of course I can name them for many reasons but those that I can are listed on our website) and what we have currently works fairly decent for them. Most generally just opt for the "15 minute downtime window" option usually on a Sunday morning at like 3am when their traffic would be the lowest.

**Comment by derrickmehaffy** [comment]
> However, if you are certain that data loss occurred because they were draft items and with a simple migration, it is possible to change the status to publish, and then schema change won't delete them anymore, it's okay for me

I can promise you the reason those entries got deleted was because they were in a draft state and you disabled D&P which purged them on the next reboot since there is a function that searches the database if an entry has `publishedAt: null` and if D&P is disabled it deletes them specifically.

**Comment by savyjs** [comment]
Thanks in advance for the detailed description. Yes, rolling deployment can sometimes be hard and challenging.
I prefer the "traffic cluster" with the auto-migration system turned off. In a high TPS system, it could be off for a few seconds, although it might not cause any serious problems most of the time. 

> In Strapi v5 D&P and i18n won't be able to be disabled (though they don't have to be used) so technically in v5 the D&P delete issue won't be a problem anymore since it'll be forced on for all content-types (though you'll have the option to auto-publish by default or if new content should be a draft state).

I hope the migration from Strapi v4 to V5 will be easy and without any serious breaking changes. 🥲

**Comment by derrickmehaffy** [comment]
> Thanks in advance for the detailed description. Yes, rolling deployment can sometimes be hard and challenging.
> I prefer the "traffic cluster" with the auto-migration system turned off. In a high TPS system, it could be off for a few seconds, although it might not cause any serious problems most of the time. 
> 
> > In Strapi v5 D&P and i18n won't be able to be disabled (though they don't have to be used) so technically in v5 the D&P delete issue won't be a problem anymore since it'll be forced on for all content-types (though you'll have the option to auto-publish by default or if new content should be a draft state).
> 
> I hope the migration from Strapi V4 to V5 will be easy and without any serious breaking changes. 🥲

Breaking changes yes there will be as thats basically the whole point of us doing major versions is to do the breaking changes we need to build bigger and newer features (like content versioning and history).

But yes the migration process should be much easier than v3 to v4 since most of the core concepts introduced in v4 really aren't being touched.

We should have a release candidate for v5 around the end of March (betas launching around the end of this month)

Stable v5 will probably be around May/June-ish at the latest and when stable releases there will still be 18 months of support for v4:

- 12 months of high/critical bug fixes + security updates
- 6 months of additional security updates

**Comment by savyjs** [comment]
Sounds amazing! 
Content versioning and history are two features that I've always been waiting for. Good job!

**Comment by ppuvanasingam** [comment]
I give up with Strapi, 2nd time it broke our production app with data loss, doesn't seem production ready. Moving back to PHP
