### ISSUE TITLE
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

### ISSUE THREAD

**Issue by offbeat-dev** [strapi/strapi#19146]
### Required System information

Launched In: 4394 ms
Environment: development
OS: darwin-arm64
Strapi Version: 4.16.2
Node/Yarn Version: npm/10.2.3 node/v20.10.0 darwin arm64 workspaces/false
Edition: Community
Database: sqlite
Typescript NextJS Project

### Describe the bug

I created a strapi project using npx create-strapi-app@latest strapi --quickstart and when trying to run it I keep getting the following error

<img width="1477" alt="strapi-bug" src="https://github.com/strapi/strapi/assets/109253600/d140748c-15f4-42d7-9002-879e4b581c1e">

### Steps to reproduce the behavior

1. create a strapi project using:  npx create-strapi-app@latest strapi --quickstart
2. See error when trying to run npm run develop

### Expected behavior

I would expect Strapi to run normally after using the quickstart 

### Screenshots

<img width="1477" alt="strapi-bug" src="https://github.com/strapi/strapi/assets/109253600/d140748c-15f4-42d7-9002-879e4b581c1e">

**Comment by offbeat-dev** [comment]
no worries, seems the issue had to do with trying to create the strapi project inside a nextjs app folder. I was following this tutorial [https://www.youtube.com/watch?v=c_-b_isI4vg](https://www.youtube.com/watch?v=c_-b_isI4vg)

I created the project in a separate folder and everything worked fine. 

thank you

**Comment by oghenetefa** [comment]
I highly doubt that.
**The steps to recreating the error remains the same. I've been developing fine for a couple of days up untill yesterday.** 

![strapi shit](https://github.com/strapi/strapi/assets/93017833/8649edd4-72d2-4245-8e4a-0ec94aedbf9e)

You might have to reopen the issue

**Comment by SandeepMahawar27** [comment]
⠴ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 
  AggregateError                                      
      at internalConnectMultiple (node:net:1114:18)   
     at afterConnectMultiple (node:net:1667:5)

**Comment by gregg-cbs** [comment]
Yeah im seeing this now too.

⠹ Loading Strapi[ERROR] There seems to be an unexpected error, try again with --debug for more information 
TypeError: Cannot read properties of undefined (reading 'attributes') at Module.getNonVisibleAttributes(D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\@strapi\utils\dist\index.js:756:11) at getNestedFields (D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\@strapi\admin\dist\server\index.js:3300:54) at D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\@strapi\admin\dist\server\index.js:3311:31at D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\lodash\lodash.js:928:11 at D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\lodash\lodash.js:4967:15 at baseForOwn(D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\lodash\lodash.js:3032:24) at D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\lodash\lodash.js:4936:18 at baseReduce (D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\lodash\lodash.js:925:5)at Function.reduce(D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\lodash\lodash.js:9749:14) at getNestedFields (D:\Devbox\cbs\bigtickets\bigtickets-server\node_modules\@strapi\admin\dist\server\index.js:3301:29)

**Comment by aleksejdom** [comment]
have the same error message 
![image](https://github.com/strapi/strapi/assets/45975492/bd82bafb-e622-481e-8ca4-6d5ea4819c3f)
