### ISSUE TITLE
Cannot use pagination on the users page

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#19158]
### Required System information

- Node.js version: v18.18.0
- Strapi version: v4.16.2

### Describe the bug

Pagination is broken on the users' page. If you set the limit of users displayed to 10 on the page and you try to go to the next page by clicking on the right arrow, nothing happens.

If you want to see the next users, you have to click on a higher number of users displayed.

### Steps to reproduce the behavior

1. Go to Settings > Users
2. Click on the right arrow under the table
3. See error

### Expected behavior

It should display the following users.

### Screenshots

https://github.com/strapi/strapi/assets/47896922/243126e7-a33f-45f1-b960-93e749c1b36e

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by devarsh-mavani-19** [comment]
@yanniskadiri i tried to reproduce it, seems to be working fine for me. i added 20 users, and then switched from 10 per page to 20 per page but works fine. I am on develop branch

**Comment by yanniskadiri** [comment]
Thanks for checking @devarsh-mavani-19.

The issue is not about the number of users displayed but about the pagination. When you have 20 users in total but you choose to display 10, you cannot click on the right arrow in the pagination to display the next 10.

**Comment by devarsh-mavani-19** [comment]
> Thanks for checking @devarsh-mavani-19.
> 
> The issue is not about the number of users displayed but about the pagination. When you have 20 users in total but you choose to display 10, you cannot click on the right arrow in the pagination to display the next 10.

That's really weird, i tried clicking right arrow and works for me. maybe it's fixed @derrickmehaffy @joshuaellis can u confirm this please? I am on develop branch

![image](https://github.com/strapi/strapi/assets/55136047/ef2154f4-364e-4ee7-910e-5386b599b8bf)
![image](https://github.com/strapi/strapi/assets/55136047/52154ad8-ad3a-4e56-ba2b-02b327630406)

**Comment by radarfox** [comment]
Our team has updated Strapi to v4.20.5 and the bug is still present. Exactly the same one as @yanniskadiri reported, where the page numbers in the pagination are missing.
