### ISSUE TITLE
Blank page and error while switching locale or saving new localized content

### ISSUE THREAD

**Issue by JulienRamel** [strapi/strapi#19159]
### Required System information

- Node.js version: v20.10.0 (same behavior with v18.19.0)
- NPM version: 10.2.3
- Strapi version: 4.16.2
- Database: MySQL 5.7.34
- Operating system: MacOS 14.1.2
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I created a Single Content Type and also activated the Internationalization (i18n) plugin and enabled internationalization for the Content Type. When I switch from a locale to another, I get a white page with errors:

`Rendered more hooks than during the previous render.`

It also happens when I save a new localized content for the Single Content Type, with the same error message.

While switching from a locale to another, I have an additional error message:

`ue.current is null`

It only happens on Single Content Types, not on Collection Content Types.

### Steps to reproduce the behavior

First scenario :

1. Go to Content-Type Builder
2. Create a Single Type with internationalization enabled
3. Go to Content Manager
4. Click on the already-created Single Type content
5. Switch the locale in the right panel
6. See error

Second scenario :

1. Go to Content-Type Builder
2. Create a Single Type with internationalization enabled (even with an unique string property for title)
3. Go to Content Manager
4. Click on the Single Type to create it
5. Fill the form and save
7. See error

### Expected behavior

The locale switch or content creation of Single Content Types should not display a blank page and error message.

### Screenshots

<img width="1007" alt="image" src="https://github.com/strapi/strapi/assets/1608342/d94a8a3e-6b1c-43cb-b39b-bde46f2d18a9">

**Comment by JulienRamel** [comment]
The issues was fixed by removing the Publisher plugin, so I guess this is not the right place to handle this.

**Comment by abhijithkmpixel** [comment]
Can anyone tell me the proper fix as im using strapi latest version and i still have the same error while switching from one locale to another.
Please provide more info
