### ISSUE TITLE
generated types on Attribute:BigInteger SetMinMax with string values

### ISSUE THREAD

**Issue by iamtofr** [strapi/strapi#19150]
### Required System information

- Node.js version: 20.10.0
- NPM version: 10.2.3
- Strapi version: 4.16.2
- Database: mySQL 8
- Operating system: linux-arm64 (Docker)
- Is your project Javascript or Typescript: Javascript

### Steps to reproduce the behavior

i have a property in my collection wich is a BigInteger with min max values.

then I bumped Strapi version from 4.12.4 to 4.16.2 in steps referenced by migration guide.

now the generated types are showing an error: Type string is not assignable to type number.

```
propertyLivingSpace: Attribute.BigInteger &
            Attribute.SetMinMax<{
                min: '1';
                max: '9999999';
            }>;
```

Error Message: 

TS2344: Type { min: "1"; max: "9999999"; } does not satisfy the constraint MinMaxOption<number>
Types of property min are incompatible.
Type string is not assignable to type number

### Expected behavior

```
propertyLivingSpace: Attribute.BigInteger &
            Attribute.SetMinMax<{
                min: 1;
                max: 9999999;
            }>;
```

### Screenshots

![image](https://github.com/strapi/strapi/assets/41756893/dba40fe6-c19d-4254-86fb-ea562ae993df)

![image](https://github.com/strapi/strapi/assets/41756893/f352f8c9-e9b6-40c1-a1f4-4f633605f397)

**Comment by Convly** [comment]
Hey, I've proposed a fix in the PR mentioned above, and have released an experimental version containing the fix

`0.0.0-experimental.b5b7b8260a4549f3bd7443fbd68be5ccc9857cd7`

If you have the time, I would appreciate it if you can test it and tell me if it fixes your issue

Thanks!
