### ISSUE TITLE
generate build files when npm install not only strapi new

### ISSUE THREAD

**Issue by sundaycrafts** [strapi/strapi#1915]
**What is the expected behavior?**
I think files in `build/` directory necessary for correctly work so it can't ignore from git. Isn't it?

But I don't want to include files in `build/` directory to git because it is not human readable.
So I think it is good that it is generated when `npm install` not only `strapi new`.

I don't know it is easy to change or not because I haven't read the code deeply yet.
So please tell me your opinion about this issue🤔

I want to fix it if I can do it.

**Comment by sundaycrafts** [comment]
Maybe related issue #1892.

**Comment by lauriejim** [comment]
Related to the issue you linked.
