### ISSUE TITLE
Relations one-to-one are breaking after saving in admin panel

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1918]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0@alpha.14
- **Database**: pg
- **Operating system**: mac

**What is the current behavior?**

So, this problem is very old and still appears. 

When you are trying to save (update already created before) model, which has one to one relation in admin panel, it will update that model  but when you will open the same model again (the same row), relation fields will be empty. Look at screens below
![image](https://user-images.githubusercontent.com/15520510/45251038-2edc3200-b348-11e8-86bb-516b5bf7489f.png)
![image](https://user-images.githubusercontent.com/15520510/45251040-3bf92100-b348-11e8-9d92-f5f5ce8435ab.png)
![image](https://user-images.githubusercontent.com/15520510/45251047-62b75780-b348-11e8-95c2-f9a28ee4efca.png)
![image](https://user-images.githubusercontent.com/15520510/45251049-7367cd80-b348-11e8-95fe-1a011076fc4f.png)
![image](https://user-images.githubusercontent.com/15520510/45251067-b75ad280-b348-11e8-8232-3d903437dfb1.png)

**Steps to reproduce the problem**

I guess I showed it in previous paragraph.

**What is the expected behavior?**

These related fields won't get empty after open them again

**Suggested solutions**

Don't have any

**Comment by lauriejim** [comment]
Hello @dulgeoion, it have been fixed in alpha.14.1.1 https://github.com/strapi/strapi/pull/1852
