### ISSUE TITLE
Strapi admin panel form validations not Working 

### ISSUE THREAD

**Issue by hassan-debug** [strapi/strapi#19193]
- Node.js version:v20.9.0
- NPM version:
- Strapi version: v4.15.5
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug
I created a Player collection and Marked fields as Required and then i submit empty form  using admin panel
and it is saved as empty record in my player collection below is screenshot of bug
<img width="1303" alt="Screenshot 2024-01-10 at 9 34 52 pm" src="https://github.com/strapi/strapi/assets/66749023/67d5dcb8-44ad-44b1-af72-350277d45912">

### Steps to reproduce the behavior

1.  create a collection and add 5,6 fields and mark all of them required 
2. Click on create new entity button and then click on save button and submit empty form
3. you will see even after marking them required you can submit form without any value

### Expected behavior

admin panel should highlight missing fields and show validation errors

**Comment by derrickmehaffy** [comment]
You are editing a draft version, validations only apply when you publish.

If you want validations to apply always you need to turn off draft and publish for the content type.

Closing as this is intended.
