### ISSUE TITLE
Issue with SCSS // SASS loader within webpack config within strapi plugin folder.

### ISSUE THREAD

**Issue by xandervandijck** [strapi/strapi#19203]
There is a issue that sustains and that is that when i add sass // scss loader to webpack config after installing scss and node sass it says there's a conflict with the email plugin. 

Can you guys solve this issue please.

**Comment by kevinvugts** [comment]
I would like to re-open this issue. Despite the fact that @xandervandijck didn't use the template @derrickmehaffy . Since having the webpack.config.js below will result in an error in yarn develop --watch-admin. 

```'use strict';

module.exports = (config, webpack) => {
  // Log the existing configuration for debugging purposes
  // console.log('Original Webpack Config:', config);

  // Integrate sass-loader, css-loader, and style-loader for .scss and .sass file handling
  config.module.rules.push({
    test: /\.(scss|sass)$/,
    use: [
      'style-loader', // Adds CSS to the DOM by injecting a <style> tag
      {
        loader: 'css-loader', // Interprets @import and url() like import/require() and will resolve them
        options: { importLoaders: 1 }, // 0 => no loaders (default); 1 => sass-loader
      },
      'sass-loader' // Loads a Sass/SCSS file and compiles it to CSS
    ]
  });

  // Optional: If you have specific configurations for resolving paths or other aspects, adjust accordingly
  // Example: Adding an alias or adjusting extensions
  config.resolve = {
    ...config.resolve, // Spread existing configurations
    extensions: ['.js', '.jsx', '.ts', '.tsx', '.scss'], // Include .scss if not already present
    // Define any necessary aliases here
    alias: {
      ...(config.resolve.alias || {}), // Spread existing aliases
      // Add custom aliases if needed
    },
  };

  // Return the modified configuration
  return config;
};```

This is the error from the console

```
 Error: Could not load js config file /Users/user/React/StrapiHub/my-project/node_modules/@strapi/plugin-email/strapi-server.js: Cannot read properties of undefined (reading 'get')   │
│       at loadJsFile (/Users/user/React/StrapiHub/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:18:13)                                          │
│       at Module.loadFile (/Users/user/React/StrapiHub/my-project/node_modules/@strapi/strapi/dist/core/app-configuration/load-config-file.js:37:14)                                     │
│       at Object.loadPlugins (/Users/user/React/StrapiHub/my-project/node_modules/@strapi/strapi/dist/core/loaders/plugins/index.js:90:41)               
```

And this is happening on the last version of Strapi.
