### ISSUE TITLE
Switching locales in the content-manager leads to infinite loading

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#19206]
### Required System information

- Node.js version: v20
- NPM version: v10
- Strapi version: 4.17.0
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When switching locales in the content-manager it will lead to an infinite loading screen

### Steps to reproduce the behavior

1. Create a new content-type with i18n enabled and a single text field called "test"
2. Add an additional locale in your project settings besides the default
3. Go to new content-type and create an entry (save)
4. Use the right side menu to switch to the non-default locale
5. See loading page

### Expected behavior

Should switch to new locale

### Screenshots

Reproduction video: https://www.loom.com/share/7392b6949fc84698996265a427558bd3?sid=69cb8c1e-045e-4d06-95c9-51e0d14887b3

### Code snippets

N/A

### Additional context

Normally would be set to sev high but elevated to sev critical based on internal escalation process
Related TID5735

**Comment by Torsten85** [comment]
What might be related to this issue: Switching the locale on a singe type has no effect at all. You always just edit the default locale.

**Comment by antoine054** [comment]
> What might be related to this issue: Switching the locale on a singe type has no effect at all. You always just edit the default locale.

Same here, whenever I switch the locale on the single type or on a collection, nothing happens. 
Also, when I edit the content on one locale, changes apply on all locales. 

This only happens since the newest update (4.17.0)

**Comment by sixtineio** [comment]
Same problem with single types, the data is shared between locales while the localization is enabled and the field translation is active.
However, it's working correctly with collection types in the mean time.

**Comment by sixtineio** [comment]
> This should be solved in `4.17.1` via #19209

Thanks @joshuaellis.
I confirm that it's working in our project.

**Comment by antoine054** [comment]
I just updated to 4.17.1 and the problem still occurs...
