### ISSUE TITLE
Media data isnt saved into contentTypes document, only `Upload_File` collection

### ISSUE THREAD

**Issue by Mr-Chilly** [strapi/strapi#1920]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: mLab
- **Operating system**: Windows10

**What is the current behavior?**
upload plugin saves an image into a collection (`upload_file`) - but not into the collection/document the image upload was initiated. the `upload_file` document in the Db contains the ref for the 'uploading document' (let's say -> product/cheesypizza's id), however, the uploading doc's media field is null.

I am currently using the cloudinary, however, this behaviour happens when saving to the file system also.

**Steps to reproduce the problem**
Create a media field within a content type, upload an image. Calling the content type's document results in `mediaField: null`

**What is the expected behavior?**
`mediaField` in the uploading document will contain an array of objects, with the same data stored in the corresponding `upload_file` collection.

**Comment by Mr-Chilly** [comment]
after more investigation, I've found where I was going wrong.

I've two related types; `products` and `categories` - and was calling the category API for a selection of related products. Relation only works '1 deep` so as `media` is a relation it only works calling the type directly...

This isn't ideal so I'd like to update my original post to a feature request:

- treat `media` as an exception to the relationship rule and include it wherever that type's data is requested
- give the users the option to choose if the relations work nested.

**Comment by Aurelsicoko** [comment]
@Mr-Chilly Thank you for this feature request! I agree with you we should make an exception for the files relationships. As we are handling the files like a relational field, they don't appear when there is already one level of population.

If I understand it correctly, in your second suggestion, it means that we should let the user chooses the depth level of nested relations?

**Comment by lauriejim** [comment]
Was an issue in fact - and is fixed in last version of Strapi.
You have access to media in deep populate REST and GraphQL
