### ISSUE TITLE
Uncaught type error in content manager after update to strapi v4.17.0

### ISSUE THREAD

**Issue by L-Weisz** [strapi/strapi#19218]
### Required System information

- Node.js version: 18
- NPM version: yarn/1.22.21
- Strapi version: 4.17
- Database: PostgreSQL
- Operating system: macOs
- Is your project Javascript or Typescript: typescript

### Describe the bug

Blank page when loading content manager page due to type error

### Steps to reproduce the behavior

My Strapi instance is deployed with Strapi Cloud, problem replicates on prod
1. sign in to strapi
2. click on "content manager"
3. See blank page

### Expected behavior

We should see the collections

### Screenshots

<img width="874" alt="image" src="https://github.com/strapi/strapi/assets/117728108/7bae3586-0cf6-4982-ac36-63c7c64e0129">

error is 
```
Uncaught TypeError: Cannot destructure property 'params' of '(0 , te.$B)(...)' as it is null.
    at sa (main.c37e9ba9.js:4497:5723)
    at Fl (main.c37e9ba9.js:894:20697)
    at Yc (main.c37e9ba9.js:896:45888)
    at ip (main.c37e9ba9.js:896:41471)
    at _h (main.c37e9ba9.js:896:41399)
    at Yu (main.c37e9ba9.js:896:41250)
    at U0 (main.c37e9ba9.js:896:37464)
    at rp (main.c37e9ba9.js:896:36360)
    at G (main.c37e9ba9.js:974:1646)
    at MessagePort.se (main.c37e9ba9.js:974:2026)
```

**Comment by L-Weisz** [comment]
I rollbacked to 4.16 and dont have the issue anymore , it seems to be specific to 4.17

**Comment by davidporos92** [comment]
I'm experiencing the same issue, but with different error. Rollback to 4.16 solves the issue here as well.
![image](https://github.com/strapi/strapi/assets/13367585/a1cc4e61-f9f7-425d-bc05-3bce55cd8b35)

**Comment by JulienRamel** [comment]
I can confirm the issue on the very last 4.17.1 version.
I deleted the dist folder and rebuilt, same result.
Same with the .strapi or build or whatever...

**Comment by TerryBerk** [comment]
> I can confirm the issue on the very last 4.17.1 version. I deleted the dist folder and rebuilt, same result. Same with the .strapi or build or whatever...

also 4.17.1 version

**Comment by kusyka911** [comment]
> also 4.17.1 version

I have same issue.

**Comment by Un-dev** [comment]
I get a similar issue but with a slightly different error message on `4.17.0` : `TypeError: Cannot destructure property 'params' of '(0 , Me.$B)(...)' as it is null.`

**Comment by vcbui-GAH** [comment]
Hi, is there any update for this or any information we can provide to help investigate?  This is preventing us from upgrading at this point of time.  CC: @jacobmaarse

**Comment by derrickmehaffy** [comment]
Can someone check a more recent release as on 4.22.0 I'm not able to reproduce this.

**Comment by parsagholipour** [comment]
> Can someone check a more recent release as on 4.22.0 I'm not able to reproduce this.

I get `TypeError: Cannot destructure property 'params' of '(0 , V.W5)(...)' as it is null.` with `4.25.20`

![Image](https://github.com/user-attachments/assets/344553d2-e5eb-4252-8127-594fa29f6bc8)

**Comment by parsagholipour** [comment]
I had a similar error
`TypeError: Cannot destructure property 'params' of '(0 , V.W5)(...)' as it is null.` and fixed it by updating the plugin packages to the same version as `@strapi/strapi`
