### ISSUE TITLE
Relations aren't populated within bulkCreate/Update/Delete lifecycles

### ISSUE THREAD

**Issue by Sid-Turner-Ellis** [strapi/strapi#19215]
I have some lifecycles:
- afterDeleteMany
- afterUpdateMany
- afterCreateMany

and i'm not able to access the relations of those in question even when fetching them again in the hook. I've tried using the db and the service layer and the result is the same:

```
// with the query layer 
    const recordsToBeDeleted = await strapi.db
      .query("api::myapi.myapi")
      .findMany(merge(ev.params, { populate: { relationA: true, relationB: true } })); 

// with the service layer
    const recordsToBeDeleted = await strapi.service
      .query("api::myapi.myapi")
      .find(merge(ev.params, { populate: { relationA: true, relationB: true } }));
```
In both cases the relations are null, from what I can tell from the documentation, you cannot update relations in bulk operations but I can't see why I wouldn't be able to access relations, is this intended behaviour?

If this is intended behaviour I think there should be a way of disabling bulk actions altogether, I can't think of any use case where you would want a lifecycle to run on a create event but not a createMany event

**Comment by alexandrebodin** [comment]
Hello, In order for your PR to get triaged you will need to update the issue description to follow the template. 

In the meantime, can you also provide a complete example of the lifecycles file you have. 

We do not have any code preventing a populate anywhere. 

I see you are using merge. What merge function is this ?
