### ISSUE TITLE
graphql error caused by enumeration latin characters

### ISSUE THREAD

**Issue by davutkara** [strapi/strapi#1922]
**Informations**
- **Node.js version**: node:9.11.1-alpine (on docker)
- **npm version**: ?
- **Strapi version**: strapi@3.0.0-alpha.14
- **Database**: mongodb
- **Operating system**: docker on LinuxMintMate

**What is the current behavior?**

graphql error 
```
api_1  | /usr/src/api/strapi-app/node_modules/mongodb/lib/operations/mongo_client_ops.js:466
api_1  |       throw err;
api_1  |       ^
api_1  | GraphQLError: Syntax Error: Cannot parse the unexpected character "\u015F".
api_1  |     at syntaxError (/usr/src/api/strapi-app/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)

```

**Steps to reproduce the problem**

I added latin character ( 'ş' ) as enumeration value. Then I installed graphql, when app was restarting. Graphql gave error which is the log above.

**What is the expected behavior?**

Should be no error or not let write unapproved chars

**Suggested solutions**

I guess converting unsupported chars can be bad solution. You can control approved characters for enumeration. Just put regex and give warning for unapproved chars.

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/issues/1698
