### ISSUE TITLE
Cannot run from source (outdated CONTRIBUTING.md)

### ISSUE THREAD

**Issue by khuongduy354** [strapi/strapi#19224]
### Required System information

- Node.js version: 20.6.1
- NPM version: 10.1.0
- Strapi version: 4.xx
- Operating system: Debian
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I follow this [CONTRIBUTING.md](https://github.com/strapi/strapi/blob/develop/CONTRIBUTING.md) here and try to run strapi admin from source, but it doesn't worked, there's no yarn develop scripts inside packages/cores/admin 

### Steps to reproduce the behavior

Just follow the doc above, at step 5, it should report there's no develop script found

### Expected behavior

Strapi admin should run and accessible at localhost:4000

### Screenshots

![image](https://github.com/strapi/strapi/assets/42113313/06ff8395-fa08-40bd-be1e-cf6d66d27400)

### Additional context

I see there's a yarn watch script, i don't know what it does, but may related to this

**Comment by derrickmehaffy** [comment]
We are aware that the contrib is 9ut of date and will address it after v5 us released.

For now we are on a change freeze.

Marking as closed since we are already aware and this doesn't classify as a bug.

**Comment by anil1712** [comment]
@derrickmehaffy but how to run the Admin from source?
