### ISSUE TITLE
response for preflight is invalid (redirect) chrome 

### ISSUE THREAD

**Issue by amit-deligence** [strapi/strapi#1923]
when i try to login using given api url  **http://eworldstrapi.herokuapp.com/auth/local**  then **Chrome** 
throw me error **response for preflight is invalid (redirect) chrome**  but it perfectly running on firefox and safari i have tried many options  like below 

        headers: {
                'Accept': 'application/json',
            		"Content-Type": "application/json; charset=utf-8",
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Methods':' OPTIONS, GET, POST',
                'Access-Control-Allow-Headers':'Content-Type, Depth, User-Agent, X-File-Size, X-Requested-With, If-Modified-Since, X-File-Name, Cache-Control',
                'Access-Control-Allow-Credentials':true,

            		// "Content-Type": "application/x-www-form-urlencoded",
        		},

but it not working

**Comment by lauriejim** [comment]
Hello @amit-deligence , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
