### ISSUE TITLE
Theme color change Incomplete

### ISSUE THREAD

**Issue by zlaazlaa** [strapi/strapi#19237]
### Required System information

- Node.js version: v18.19.0
- NPM version: v9.8.1
- Strapi version: v4.15.5
- Database: MySQL
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Change color in ./src/admin/app.ts, modify all primary color from purple to green but still display purple in somewhere.

### Steps to reproduce the behavior

My ./scr/admin/app.ts:
```typescript
export default {
    config: {
      theme: {
        light: {
          colors: {
            primary100: "#eafbe7",
            primary200: "#c6f0c2",
            primary500: "#5cb176",
            primary600: "#328048",
            primary700: "#2f6846",
          },
        },
      },
    },
    bootstrap(app) {
      console.log(app);
    },
  };
```

### Expected behavior

All element which is purple before should be green now.

### Screenshots

![image](https://github.com/strapi/strapi/assets/72907523/6656ff46-131e-4a37-bda9-3698bbe4e321)
![image](https://github.com/strapi/strapi/assets/72907523/36894037-1bcb-49d9-b875-8ec4a57ddec6)

**Comment by talalong** [comment]
you should you `buttonPrimary500` and `buttonPrimary600` for those buttons

**Comment by zlaazlaa** [comment]
> @zlaazlaa you should you `buttonPrimary500` and `buttonPrimary600` for those buttons

You mean I should change color like this?
```
export default {
    config: {
      theme: {
        light: {
          colors: {
            primary100: "#eafbe7",
            primary200: "#c6f0c2",
            primary500: "#5cb176",
            buttonPrimary500: "#5cb176",
            primary600: "#328048",
            buttonPrimary600: "#328048",
            primary700: "#2f6846",
          },
        },
      },
    },
    bootstrap(app) {
      console.log(app);
    },
  };
```

**Comment by zlaazlaa** [comment]
> > @zlaazlaa you should you `buttonPrimary500` and `buttonPrimary600` for those buttons
> 
> You mean I should change color like this?
> 
> ```
> export default {
>     config: {
>       theme: {
>         light: {
>           colors: {
>             primary100: "#eafbe7",
>             primary200: "#c6f0c2",
>             primary500: "#5cb176",
>             buttonPrimary500: "#5cb176",
>             primary600: "#328048",
>             buttonPrimary600: "#328048",
>             primary700: "#2f6846",
>           },
>         },
>       },
>     },
>     bootstrap(app) {
>       console.log(app);
>     },
>   };
> ```

@talalong Thanks, it worked! 👍
