### ISSUE TITLE
[Single type] Warning "already.published" but the entity is not published after v4.17.1 update

### ISSUE THREAD

**Issue by sixtineio** [strapi/strapi#19240]
### Required System information

- Node.js version: v20.11.0
- Yarn version: 1.22.19
- Strapi version: 4.17.1
- Database: Postgresql 15.4
- Operating system: Alpine Linux (Docker 20.11.0-alpine)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I try to publish a single type entity translation in the Strapi back office, a warning "already.published" is displayed but the entity is not published. If I check the entity published_at in the database, it's set to [NULL].

### Steps to reproduce the behavior

1. Create a single type
2. Enable i18n for this single type and check that you have at least another language active
3. Create an entity in the default language
4. Translate the entity and fill from main language
5. Save translation
6. Try to publish
7. You should have a warning blocking the publication

### Expected behavior

Publish the entity and display a notification "Published".

### Screenshots

N/A

### Code snippets

N/A

### Additional context

It occurs after the resolution of this issue => https://github.com/strapi/strapi/issues/19206
No problem with collection types, I can publish translations.

**Comment by imran-hossain03** [comment]
Facing the same issue on `Single Type` on Strapi v4.17.1

**Comment by sixtineio** [comment]
Same Issue flagged by Strapi team => #19289

**Comment by pepegablaza** [comment]
Hey, im facing same problem on 4.19.0, and i read in comments when you want to publish desired locale it has to be default one, so it works in that way atm, hope for fast fix!

**Comment by sixtineio** [comment]
Hi @pepegablaza, there is a similar issue in PR status : https://github.com/strapi/strapi/issues/19289
This is why I closed this one.
