### ISSUE TITLE
Switching locales when viewing a collection-type entity won't load the entity data for the locale even if it exists

### ISSUE THREAD

**Issue by gaspop** [strapi/strapi#19267]
### Required System information

- Node.js version: 18.19.0
- NPM version: 10.2.3
- Strapi version: 4.17.1
- Database: mysql
- Operating system: macOS Sonoma 14.2.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

If you are viewing a collection entity and switch locale in the menu to the the right, Strapi will assume you are creating a new entity with that locale even if one exists.

### Steps to reproduce the behavior

1. Create a new collection content-type with i18n enabled and add a single text field
2. Add an additional locale to your project
3. Create a new entity of the new content-type in your default locale and save it
4. When viewing the new entity, select the other locale in the menu to the right, add some data and save it
5. Switch back to the other locale in the menu to the right, and Strapi enters create-mode rather than edit mode, it won't load the existing entity

### Expected behavior

When switching to another locale from an entity and that entity exists, it should load the existing entity.

### Screenshots

<img width="1288" alt="strapi-locale-bug-1" src="https://github.com/strapi/strapi/assets/22764296/64d2c722-ddc4-4298-af60-0eb1f3431985">
<img width="1286" alt="strapi-locale-bug-2" src="https://github.com/strapi/strapi/assets/22764296/0c8e405c-5b18-478f-8e9d-d3362fe0b367">
<img width="1283" alt="strapi-locale-bug-3" src="https://github.com/strapi/strapi/assets/22764296/4cc0bfa2-5172-4f3f-9989-9811bef8d05c">

**Comment by alex-lechner** [comment]
Localization does not seem to work properly. I have a different problem (reference #17314) but maybe it has the same root cause.

**Comment by xyzones** [comment]
@gaspop I can reproduce this. if the schema.json has `"draftAndPublish": false` the described behaviour is seen.

**Comment by tjablonski** [comment]
Hi, I noticed that this should be fixed in v4.19.1 but after update to v4.20.0 I still see this issue appear. I tested it on collection with draft & publish enabled. 

Node.js version: 18.16.0
NPM version: 9.5.1
Strapi version: 4.20.0
Database: postgres
Operating system: Windows 10 
Is your project Javascript or Typescript: Typescript

**Comment by pandeyprafull** [comment]
Any update for the fix @derrickmehaffy  ?
