### ISSUE TITLE
I can't create a new strapi project

### ISSUE THREAD

**Issue by Nyeedz** [strapi/strapi#1927]
**Informations**
- **Node.js version**: 10.9.0
- **npm version**:6.2.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongDB
- **Operating system**: Windows 10 64 bits

**What is the current behavior?**
when i tried to create a new project with "strapi new project", i stay stuck, i choose MongoDB and when i chose my database name, console don't do anything.

![image](https://user-images.githubusercontent.com/17225811/45314185-73fa9280-b507-11e8-9a75-2262c670b599.png)

**Steps to reproduce the problem**
when i choose 8.11.4 version of node, the problem dont show again

**What is the expected behavior?**
create a new project

**Suggested solutions**

**Comment by maturanomx** [comment]
Know issue on Windows. No fix by now.

Can you work on a VM or with WSL?

**Comment by maturanomx** [comment]
You can take a look on this issue: #1281

**Comment by wisniewski94** [comment]
I don't think it has something to do with Windows. This function doesn't work in Powershell and CMD but with Git Bash you can install strapi normally. Just look around for other cmd-type programs. Maybe even emulators will do it.

**Comment by derrickmehaffy** [comment]
I mean if your going to use bash on windows, you might as well just use WSL and get all the benefits of linux.... lol.

**Comment by jrasm91** [comment]
I actually was running into the same, or a very similar problem. I was able to get the new project to create by bypassing the prompt and running the command with the cli arguments. 

`strapi new myApp --dbclient=mongo --dbhost=<host> --dbport=27017 --dbname=development --dbusername=admin --dbpassword=admin --dbssl=true --dbauth=admin`

**Comment by wisniewski94** [comment]
@jrasm91 in my case that also didn't work. I got same error as here -> https://github.com/strapi/strapi/issues/1355#issue-330891506
