### ISSUE TITLE
Transfer Token 400 Error - Token Time Duration

### ISSUE THREAD

**Issue by kduprey** [strapi/strapi#19271]
### Required System information

- Node.js version: 18.17.0
- NPM version: 8.16.0
- Strapi version: 4.17.1
- Database: MySQL
- Operating system: Linux Runtime
- Is your project Javascript or Typescript: TypeScript

### Bug Description

When going to create a transfer token, with valid values for the name, token type, and duration, if selecting 'Unlimited' for a duration, the page does not return any error, but the network API request to Strapi's backend returns a 400 error, with the body of the response as follows:

```json
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "lifespan must be one of the following values: , 604800000, 2592000000, 7776000000",
        "details": {
            "errors": [
                {
                    "path": [
                        "lifespan"
                    ],
                    "message": "lifespan must be one of the following values: , 604800000, 2592000000, 7776000000",
                    "name": "ValidationError"
                }
            ]
        }
    }
}
```

### Steps to reproduce the behavior

1. Go to Admin Panel
2. Go to Settings tab
3. Select Transfer Tokens
4. Create new Transfer Token
5. Fill out required fields, specifically choosing "Unlimited" as "Token duration" option
6. Click "Save"
7. Nothing happens visually to the user on the page. To see the network error that occurs, open browser DevTools, view the network tab and see that the recent request to the Strapi Admin endpoint `/admin/transfer/tokens` returned a 400 error.

### Expected behavior

I expected all possible duration options from the dropdown menu to be valid and allow me to successfully create a new transfer token.

**Comment by kynatro** [comment]
Also experiencing this issue. Worth noting that I can still create a token of specified duration (e.g. 90 days).

**Comment by kasonde** [comment]
Confirmed

**Comment by Eventyret** [comment]
Confirmed too, 7,30,90 days works. Unlimited does not work Strapi  4.20

**Comment by kasonde** [comment]
As it's only Unlimited that's not working, I've knocked the sev down by one.
