### ISSUE TITLE
Project will not run after running quickstart

### ISSUE THREAD

**Issue by dnikomon** [strapi/strapi#19280]
### Required System information

- Node.js version: v18.12.0
- NPM version: 8.19.2
- Strapi version: 4.17.1
- Database: sqlite3
- Operating system: darwin-x64
- Is your project Javascript or Typescript: ~~typescript~~  javascript

### Describe the bug

After creating a new project with --quickstart flag, it will not run. 

### Steps to reproduce the behavior

1. Create project with command `yarn create strapi-app my-project --quickstart`
2. Run with develop command
3. Server does not start

### Expected behavior

1. Create project with command `yarn create strapi-app my-project --quickstart`
2. Run with develop command
3. Server runs

### Screenshots

<img width="1106" alt="Screenshot 2024-01-19 at 15 15 09" src="https://github.com/strapi/strapi/assets/62984212/bf7abeee-aa8b-4f61-9a4d-900cfdeacf69">

**Comment by dnikomon** [comment]
yarn version: 1.22.18

**Comment by dnikomon** [comment]
This issue also happens when running `npx create-strapi-app@latest my-project --quickstart`

**Comment by dnikomon** [comment]
this only happens with --quickstart flag. It almost seems like it expects typescript files to be there even though default seems to be plain js

**Comment by bolg55** [comment]
@dnikomon do you know what the `latest` release was when you tried it? I cannot reproduce using the latest:

![image](https://github.com/strapi/strapi/assets/43022248/3d2fb490-f226-42c5-ab8e-e489106a5159)
