### ISSUE TITLE
Development server cannot start

### ISSUE THREAD

**Issue by murkrow92** [strapi/strapi#1930]
**Informations**
- **Node.js version**:v9.0.0
- **npm version**:5.5.1
- **Strapi version**:3.0.0-alpha.14
- **Database**:MySQL 5.7.23
- **Operating system**: macOS High Sierra

**What is the current behavior?**

I'm developing a strapi plugin following the [plugin development guide](https://strapi.io/documentation/plugin-development/quick-start.html)  . But when i stopped the development server and restart it i got this error.

1) When i run npm start inside the admin folder

> > strapi-admin@3.0.0-alpha.14 prestart /Users/ductrung/Projects/NodeJS/strapi/packages/strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js
(node:20561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'config' of undefined
(node:20561) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

i try to run Ctrl+C and it looks good

> strapi-admin@3.0.0-alpha.14 start /Users/ductrung/Projects/NodeJS/strapi/packages/strapi-admin
>node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server
Strapi plugin succesfully started in development mode. ✓

2) But when i try to run strapi start , it doesn't work 

<img width="1280" alt="screen shot 2018-09-11 at 10 33 14 am" src="https://user-images.githubusercontent.com/22515983/45336932-e4f58500-b5af-11e8-9222-9110aa457269.png">

**Steps to reproduce the problem**

1) run npm start inside the admin folder
2) run strapi start inside the root folder

**What is the expected behavior?**

Same as the plugin development guide and before i restart the development server

**Suggested solutions**

**Comment by jrperdomoz** [comment]
I would like to know what is the procedure to have my development environment on my local machine and be uploading deployments to my production server, for example in digitalOcean. I have it not clear...

```
Development mode
Note that to modify the administration panel, your project needs to be created with using the dev flag, an example of such would be: strapi new strapi --dev.

#1 — Install its own dependencies

Run npm install from the ./admin folder.

#2 — Launch the development server

Run npm start from the ./admin folder. That's all.

#3 — Go to the browser

You should be able to see the admin at http://localhost:4000/admin.
```

Is this still valid? A little light please

**Comment by soupette** [comment]
@jrperdomoz this is not valid anymore.

See the [CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md)  to see how to customise a plugin/ create a new one

**Comment by soupette** [comment]
@murkrow92 do you still have an error or did you get it working?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
