### ISSUE TITLE
Release 4.17.1 is breaking Content Manager loading of Single Types

### ISSUE THREAD

**Issue by blockmar** [strapi/strapi#19319]
### Required System information

- Node.js version: 20
- NPM version: 10.2.3
- Strapi version: 4.17.1
- Database: mysql
- Operating system: linux
- Is your project Javascript or Typescript: js

### Describe the bug

After upgrading from 4.17.0 to 4.17.1 we can no longer access the Content Manager. It flickers and ends up in a blank screen.
Seems to be related to loading one of our Single Types. (JS errors below)

Seems like the only change in 4.17.1 is related to Single type:
https://github.com/strapi/strapi/compare/v4.17.0...v4.17.1

### Steps to reproduce the behavior

Note: The issue seems to apply for all single type. If I manually type in a path to a collection-type the page renders correctly. But if I press any Single Type the error occures.

Login to Strapi Admin, click on Content Manager.

Seems like the UI is trying to find a ID or similar. Notice the _undefined_ it the API url requested. Results in a 404:

```
GET http://localhost:1337/content-manager/relations/api::app-store-link.app-store-link/undefined/internalDesktopLink?pageSize=5&page=1 404 (Not Found)
```

My guess is that the promise gets cancelled as a result of the 404.

```
main.dacaea87.js:4561 Uncaught (in promise) 
vn {message: 'canceled', name: 'CanceledError', code: 'ERR_CANCELED', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_CANCELED"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"canceled"
name
: 
"CanceledError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 0, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
stack
: 
"CanceledError: canceled\n    at AbortSignal.Ar (http://localhost:1337/admin/main.dacaea87.js:4561:6044)\n    at http://localhost:1337/admin/main.dacaea87.js:4162:698\n    at Or (http://localhost:1337/admin/main.dacaea87.js:583:23357)\n    at ra (http://localhost:1337/admin/main.dacaea87.js:583:25166)\n    at lf (http://localhost:1337/admin/main.dacaea87.js:583:43427)\n    at vh (http://localhost:1337/admin/main.dacaea87.js:583:38178)\n    at Eu (http://localhost:1337/admin/main.dacaea87.js:581:3311)\n    at http://localhost:1337/admin/main.dacaea87.js:583:35736"
[[Prototype]]
: 
bn
```

Before the 404 the following url is being called. With the included result:
`http://localhost:1337/content-manager/single-types/api::app-store-link.app-store-link/`

Result:
```
{
    "id": 1,
    "appleStoreUrl": "https://apps.apple.com/us/app/qapital-set-forget-finances/xxx",
    "googlePlayStoreUrl": "https://play.google.com/store/apps/details?id=xxx&hl=en_US&gl=US",
    "createdAt": "2023-02-28T14:23:38.526Z",
    "updatedAt": "2023-10-25T11:35:49.267Z",
    "publishedAt": null,
    "internalDesktopLink": {
        "id": 20,
        "slug": "download",
        "pageId": "15",
        "pageType": "page",
        "parentSlug": null,
        "published": false,
        "parentPagePublished": null,
        "createdAt": "2023-02-28T14:24:08.048Z",
        "updatedAt": "2023-12-01T12:14:11.633Z",
        "parentPageId": null,
        "internalDesktopLink": null,
        "appleStoreUrl": null,
        "googlePlayStoreUrl": null
    },
    "createdBy": null,
    "updatedBy": {
        "id": 7,
        "firstname": "xxx",
        "lastname": "xxx",
        "username": null
    }
}
```

### Expected behavior

We are expecting to see our content but we get a blank screen.

### Code snippets

Our single type that it tries to load:
```
{
  "kind": "singleType",
  "collectionName": "app_store_links",
  "info": {
    "singularName": "app-store-link",
    "pluralName": "app-store-links",
    "displayName": "App store links",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "appleStoreUrl": {
      "type": "text",
      "required": true
    },
    "googlePlayStoreUrl": {
      "type": "text",
      "required": true
    },
    "internalDesktopLink": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::link.link"
    }
  }
}
```

### Additional context

Reverting to 4.17.0 fixes the issue. Upgrading to 4.19.0 does not fix the issue.

**Comment by hoqkhanh** [comment]
**Required System information**
Node.js version: 18.9
NPM version: 10.2.3
Strapi version: 4.17.1
Database: postgresql
Operating system: linux
Is your project Javascript or Typescript: js


I got the same issue with some crashing in CMS when clicking through the collection types in the content manager when upgrade to **4.17.1**  (seen video below).


https://github.com/strapi/strapi/assets/8230519/1d4f4902-09cf-4f23-ad70-dd0537973f3f

<img width="1659" alt="Screenshot 2024-01-25 at 09 36 40" src="https://github.com/strapi/strapi/assets/8230519/9787402f-652a-4473-8ad1-c2d6b1a2570d">


It doesn't happen on Strapi 4.15.5

**Comment by hoqkhanh** [comment]
**Required System information**
Node.js version: 18.9
NPM version: 10.2.3
Strapi version: 4.17.1
Database: postgresql
Operating system: linux
Is your project Javascript or Typescript: js


I got the same issue with some crashing in CMS when clicking through the collection types in the content manager when upgrade to **4.17.1**  (seen video below).

https://github.com/strapi/strapi/assets/8230519/0aa234e8-9b91-423c-b06e-b862ef64a769

<img width="1659" alt="Screenshot 2024-01-25 at 09 36 40" src="https://github.com/strapi/strapi/assets/8230519/9787402f-652a-4473-8ad1-c2d6b1a2570d">


It doesn't happen on Strapi 4.15.5

**Comment by jmprice18** [comment]
For me, I can reproduce this by adding a JSON field to a collection and view it's details, or trying to view a single type.

**Comment by hoqkhanh** [comment]
It's happened for collection type too clicking through the collection types in the content manager

**Comment by derrickmehaffy** [comment]
We aren't able to reproduce on v1.19.0: https://www.loom.com/share/fa93aa8f01f6460eaee1d3cd9dfdc59d?sid=9cea56bc-18ef-4a09-8053-652a22d9d27a

If you have any additional information to help us confirm this please let us know.

**Comment by jmprice18** [comment]
I wasn't able to reproduce this issue on a new project.  So I tried deleting **node_modules** and **yarn.lock** and reinstalling dependencies.  That worked for the project I was having exceptions thrown when viewing details of content type that had JSON fields.

**Comment by blockmar** [comment]
Just deleting `yarn-lock` and `node_modules` and re-running `yarn install` did not solve my issue, I still see the same blank screen. I will try to reproduce in a fresh environment.

**Comment by blockmar** [comment]
Some not so good news. I was able to re-create the issue on Strapi 4.17.0, the version where everything previously worked for my. I deleted `yarn-lock` and `node_modules` and reran `yarn install`. Does this mean that the issue is related to a child dependency? Either Strapi or something strapi depends on is using a non version fixed dependency that got updated by forcing a new install. Will continue my efforts to replicate on an fresh install.

**Comment by derrickmehaffy** [comment]
Indeed I was testing on a fresh install, if you can accurately reproduce the issue on an existing project, I'll need the codebase. If you don't want to send it in public you are welcome to contact me at derrick.mehaffy@strapi.io and you are welcome to share it in private.

If you need an NDA to do so, let me know as I'm authorized to sign an NDA on behalf of Strapi.

**Comment by blockmar** [comment]
Thank you @derrickmehaffy. I apologies for not getting back to you sooner. I'm still trying to package this up in a repeatable way. Our custom types have a lot of inter-dependencies and I wanted to make the package as small as possible. While I continue, can you point me to any documentation on how to run Strapi un-minimized? If I could test this in an environment where I can run debug maybe I could better understand the difference in behavior.

**Comment by Drunkenpilot** [comment]
We got the same issue after upgrade to 4.19.0. 
After remove this plugin "strapi-plugin-notes", the single-types pages went back to normal.

May be you could create a new project,   test the additional plugins which has UI interface one by one.

**Comment by blockmar** [comment]
> We got the same issue after upgrade to 4.19.0. After remove this plugin "strapi-plugin-notes", the single-types pages went back to normal.
> 
> May be you could create a new project, test the additional plugins which has UI interface one by one.

We also have that plugin installed. I tried removing it (together with other extra plugins) unfortunately I did not see any change in behavior.

Currently I'm stuck recreating our setup in a fresh project because other types refuse to load. (When I click create XXXXXX I only get a spinner and no UI. Unfortunately neither any error) I do still see the 404s of trying to load some components with ID `undefined`. But I see those in other parts of the install that are working too.

I aslo though it might have been a difference between mysql and sqlite, not that did not seem to be the case.

**Comment by blockmar** [comment]
We also have `@ckeditor/strapi-plugin-ckeditor` installed but I can't easily remove it due to dependencies in custom content types. But will try to in my fresh test install.

**Comment by blockmar** [comment]
@derrickmehaffy I can confirm that our problem went away after removing the `@ckeditor/strapi-plugin-ckeditor` plugin (v 0.0.10) and replacing the field type with `text`. I guess it's a dependency conflict between the plugin and the Strapi version.

**Comment by Drunkenpilot** [comment]
We're using this one for wysiwyg, got no issue with V4.19.0
https://www.npmjs.com/package/@_sh/strapi-plugin-ckeditor

**Comment by derrickmehaffy** [comment]
There was a few other bugs reported recently that leads me to believe the root cause was possibly some updates to some various react router related packages (and I'm no frontend engineer). I'll talk to @joshuaellis in the morning and see if he has any ideas.

**Comment by anil1712** [comment]
I am still getting the same issue withe latest version. Any solution for this?
