### ISSUE TITLE
Configuration Server Host IP does not get saved

### ISSUE THREAD

**Issue by fezproof** [strapi/strapi#1931]
**Informations**
- **Node.js version**: latest
- **npm version**: latest
- **Strapi version**: 3.00@alpha14
- **Database**: MongoDB latest stable with GraphQL API
- **Operating system**: Linux Ubuntu 18.04

**What is the current behavior?**
Configuration Server Host IP does not get saved. When I change the IP and save settings it automatically resets back to localhost. This is a problem as I am trying to develop using a digital ocean server instance so that my team can all use the same database, but it also means that email confirmation will not work because the auth link is always set to localhost:1337.

**Steps to reproduce the problem**

1. Go to configurations
2. Server
3. enter new IP in IP field
4. Click save
5. Bug appears

**What is the expected behavior?**
It should update to what is inputed

**Comment by derrickmehaffy** [comment]
@fezproof this will be fixed in 14.1 with my proxy PR here: https://github.com/strapi/strapi/pull/1813

@lauriejim this can probably be closed.

Also as a side note that isn't for IP it is only for hostname.

**Comment by TokenChingy** [comment]
Good to know, I'll let @fezproof know in the morning when I see him. Will 14.1 be released today/tomorrow?

**Comment by derrickmehaffy** [comment]
@TokenChingy Pretty sure it is supposed to be tomorrow. @lauriejim and I were trying to fix providers before release, but I don't think that is gonna happen.

**Comment by lauriejim** [comment]
Can you try again with last version of Strapi.
It works well on my side.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
