### ISSUE TITLE
Contribution documentation is misleading

### ISSUE THREAD

**Issue by ilnytskyi** [strapi/strapi#19349]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

[A clear and concise description of what the bug is.](https://github.com/strapi/strapi/blob/develop/CONTRIBUTING.md#5-running-the-administration-panel-in-development-mode)

When following step 5 it throws an error `Usage Error: Couldn't find a script named "develop".`
```
cd ./packages/core/admin
yarn develop
```

### Steps to reproduce the behavior

1. Go to CONTRIBUTING.md
2. Follow steps till 5
3. Try step 5
4. See error `Usage Error: Couldn't find a script named "develop".`

### Expected behavior

Contribution version of repo works as expected or documentation updated on how to work with dev version of strapi.

### Screenshots

![image](https://github.com/strapi/strapi/assets/3192770/9ad1dabc-34dc-4680-ba7a-2193f5578100)

### Code snippets

The package json does not contain the script suggested in documentation

**Comment by deepak41** [comment]
Facing this issue. Any update on this?

**Comment by ls-ramos** [comment]
I found the same issue, I noticed the develop command was removed on [this commit](https://github.com/strapi/strapi/commit/116339ad8657ad2cf62135506bf64a1373295230#diff-5d090f32ed9aa7e29de2f7356f625871c39412ba66bbf302d47c2e949d0958c6L29)

Apparently we need to use `yarn watch` now, that is what I am trying.
