### ISSUE TITLE
NOT NULL is not applied to the database

### ISSUE THREAD

**Issue by dev-abir** [strapi/strapi#19347]
### Required System information

- Node.js version: v20.10.0
- NPM version: 10.2.3
- Strapi version: v4.19.0
- Database: sqlite
- Operating system: Ubuntu 22.04.2 LTS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

`NOT NULL` constraint isn't applied while creating the table.
Is it a feature or a bug? This won't matter much while creating a table, but it might be an issue while updating a table with new columns.

If you add new column to an existing table, if you add `NOT NULL` (similar to strapi's `required`), what you expect is an error, because the what will be the value for pre-existing records? You are bound to make it `NULL` or just add a default value for pre-existing rows.

Strapi uses SQL databases like postgres, so I believe strapi should be consistent with what's there in the database.

If you add a new required column in strapi it creates a weird state: new records will hold a value, pre-existing are `NULL`, but the new column is required - very contradictory.

### Steps to reproduce the behavior

1. Create a new collection type (like `Post`).
2. Add few fields.
3. Create a new `Post`.
4. Add a boolean field (text fields may be blank, instead of `NULL`).
5. Now you can see that older posts have that boolean field as `NULL`, but to create a new `Post`, or update existing you must provide a value to that column - thus inconsistent.

### Expected behavior

If you add new **required** column to an existing collection type, we must get a SQL NOT NULL constraint error sort of.
Also, we should not allow blank for text / character fields? This option should be explicit.

**Comment by derrickmehaffy** [comment]
This is intended as we apply those validations on the app side for our draft and publish feature (required isn't required in a draft and is applied on publish)

If you want DB constraints: https://docs.strapi.io/dev-docs/backend-customization/models#database-validations-and-settings
