### ISSUE TITLE
The hook _config failed to load

### ISSUE THREAD

**Issue by dualitysol** [strapi/strapi#1934]
**Informations**
- Node.js: v10.8
- npm version: 6.4.1
- Strapi version: 14
- Database: MongoDB: 3.6.5
- Operating system: Ubuntu 18

**What is the current behavior?**
After I create new project using `strapi new` and trying to start it by `strapi start`, I got an error `error: The hook _config failed to load!`.

**Steps to reproduce the problem**
I have tried to create new one using `sudo` also trieng to run `npm run setup`, but nothing helps.

**What is the expected behavior?**
Expecting started server after `strapi start`

**Comment by lauriejim** [comment]
Hello @dualitysol, can you give use the exact name of the Strapi version you use please.

**Comment by lauriejim** [comment]
Try to re-install `npm i strapi@alpha -g` and create new project.

**Comment by lauriejim** [comment]
Should install `3.0.0-alpha.14.1.1`.

**Comment by dulgeoion** [comment]
@lauriejim have almost the same story on mac with pg. On creating new project I have this error 
![image](https://user-images.githubusercontent.com/15520510/45633091-995b4380-baa7-11e8-8ae9-0341f0d65819.png)
If I will try to start this project, I will catch this 
![image](https://user-images.githubusercontent.com/15520510/45633141-b5f77b80-baa7-11e8-908b-8d451e30d707.png)

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
