### ISSUE TITLE
4.19.0 Review Workflows: No longer able to assign users to stage or update roles that can manage a stage

### ISSUE THREAD

**Issue by markkaylor** [strapi/strapi#19340]
### Required System information

- Node.js version: 20.5.1
- NPM version: 9.8.0
- Strapi version: 4.19.0
- Database: sqlite
- Operating system: Mac OS Ventura 13.3.1 (darwin-arm64)
- Is your project Javascript

### Describe the bug

It is not possible to assign any user, even a super-admin user, to a Review Workflow stage. It is also not possible to update the roles that can manage a stage in Review Workflows.

### Steps to reproduce the behavior

Unable to assign a user to a stage
1. Go to any content-type with Review Workflows enabled
2. Try to assign a super-admin to a stage, see error `you should pass a valid id to the body of a put request`

Unable to update the roles that can manage a stage
1. Go to settings -> Review Workflows
2. Select a review workflow
3. Select any stage 
4. In the "Roles that can change this stage" select, select some roles.
5. Click save and refresh
6. Go back to the select you where you made an update
7. See that the update did not persist

### Expected behavior

I should be able to update the roles that can manage a stage. As a role that can manage a stage I should be able to assign myself or other users with the correct permissions.

### Screenshots

![Screenshot 2024-01-25 at 18 12 58](https://github.com/strapi/strapi/assets/26598053/aa516855-a59d-45e8-ad03-1af99bfb6054)

https://github.com/strapi/strapi/assets/26598053/2608129b-93f1-4f72-b1ef-21a05e9412e9

### Additional context

I confirmed this bug is NOT present in 4.17.1

**Comment by dennism501** [comment]
Internal TID: 5907
