### ISSUE TITLE
Primary key can be updated

### ISSUE THREAD

**Issue by dev-abir** [strapi/strapi#19346]
### Required System information

- Node.js version: v20.10.0
- NPM version: 10.2.3
- Strapi version: v4.19.0
- Database: sqlite
- Operating system: Ubuntu 22.04.2 LTS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

The strapi's default primary key for all content types (id) can be overwritten using a update API end point.
Example: Let's say you create a `Post` collection type. Now if you try to update it using API, put any random id in the JSON body, strapi just blindly updates the id - then returns a 404.

### Steps to reproduce the behavior

1. Create a new content type (like `Post`).
2. Add some fields.
3. Create an API key, or just give anonymous access (settings -> under 'USERS & PERMISSIONS PLUGIN' click on Roles -> Public -> allow update permission for Public).
4. Now create a `Post` entry.
5. Use any API client like Bruno or curl, send this JSON body to: `http://localhost:1337/api/posts/1`
```JSON
{
  "data": {
    "id": -999,
    "Name": "Whatever"
  }
}
```
6. You will receive a 404, now check the updated `Post` - the id has been changed.

### Expected behavior

The primary key (id) should not be updated merely just using an API.

### Additional context

Now, maybe it is an expected feature not a bug (although I can't see practical use cases of updating primary key merely using API).
I am sure that this wasn't expected, because it breaks when you add a relation (gives 500 if another content type references `Post`).

**Comment by sph-e** [comment]
its a feature not a bug

**Comment by Boegie19** [comment]
Tested back on version 4.6.0 on this version the issue still exists.
This issue also exists in postgres

**Comment by derrickmehaffy** [comment]
Boegie and we're walking through this in the Discord office hours and it's been around for a while it appears which is extremely concerning we haven't noticed it before.

It absolutely isn't intentional and now I'm wondering about the other validation for system fields like createdAt, updatedAt, createdBy, and updatedBy.

This has some fairly damaging consequences though at least the impact scope is slightly reduced as it would require create/update permissions so it's not -exactly- a security risk but it's borderline honesty.

**Comment by dev-abir** [comment]
Should I be bountied for discovering this security issue? 🙂

Also, let me know if you need any help from me regarding this issue....

**Comment by dev-abir** [comment]
Oh another thing: I am not sure if this happens or not, I will check and let you know - probably you can also update related fields.

Like let's say a `Customer`  has a one-to-one field to the `User` model - one can update the underlying `User` through the update `Customer` API (or at least the ID of the `User` can be updated).

Again, this might be a feature not a bug - but does it check for the new id's existence?

**Comment by derrickmehaffy** [comment]
> Oh another thing: I am not sure if this happens or not, I will check and let you know - probably you can also update related fields.
> 
> Like let's say a `Customer`  has a one-to-one field to the `User` model - one can update the underlying `User` through the update `Customer` API (or at least the ID of the `User` can be updated).
> 
> Again, this might be a feature not a bug - but does it check for the new id's existence?

That it should but there's also need permission checking there to.
