### ISSUE TITLE
permissions is undefined in SETTINGS > COMMENTS PLUGIN > CONFIGURATION (strapi latest)

### ISSUE THREAD

**Issue by MarinosTBH** [strapi/strapi#19348]
I just followed this tuto line by line : https://strapi.io/blog/how-to-build-a-photo-sharing-app-with-nuxt-3-graph-ql-cloudinary-postgres-and-strapi
when i access => SETTINGS > COMMENTS PLUGIN > CONFIGURATION
i get this error :TypeError permissions is undefined, 
even though i followed the guide as it is ? 
![Screenshot from 2024-01-27 16-01-43](https://github.com/strapi/strapi/assets/96175731/63e442f6-f6d2-4521-9756-dba725b93098)
![Screenshot from 2024-01-27 16-03-23](https://github.com/strapi/strapi/assets/96175731/eec87786-e254-420e-b8b9-2e90200d8e77)

I use node 18.18.0
strapi 4.19.0

**Comment by derrickmehaffy** [comment]
Not our plugin, open an issue on the maintainers repo

**Comment by MarinosTBH** [comment]
Understood, thanks for clarifying

**Comment by MarinosTBH** [comment]
But still strapi blog provides an unsuccessful guide mentioned above,  https://strapi.io/blog/how-to-build-a-photo-sharing-app-with-nuxt-3-graph-ql-cloudinary-postgres-and-strapi
Should be fixed or hidden for the moment

**Comment by derrickmehaffy** [comment]
> But still strapi blog provides an unsuccessful guide mentioned above,  https://strapi.io/blog/how-to-build-a-photo-sharing-app-with-nuxt-3-graph-ql-cloudinary-postgres-and-strapi
> Should be fixed or hidden for the moment 

Blog posts are our marketing department and there isn't much I can do there, best to just leave a comment on the blog post.

For GitHub's sake, only our repos and documentation are considered "official"
