### ISSUE TITLE
Introduce a real type for the media values

### ISSUE THREAD

**Issue by sawden** [strapi/strapi#19353]
This issue is created to address an open **TODO** in the v4 & v5 codebase regarding the typing of `MediaValue`. 
The current implementation uses `any` and `any[]`, which is not ideal for type safety.

https://github.com/strapi/strapi/blob/6d59515520a3850456f256fb0e4c54b75054ddf4/packages/core/types/src/types/core/attributes/media.ts#L28

**Comment by LucaNerlich** [comment]
V5 is supposed to have full typescript support. So I suppose, that this is already in the works.
