### ISSUE TITLE
Swagger dose not generate filters, fields and parameters correctly 

### ISSUE THREAD

**Issue by FaryarKankash** [strapi/strapi#19350]
i use to generate client fetch with swagger-typescript-api but it give me error when i want to filter my for example courses, the type of filters was an object , i check my documentation.json file and see swagger dosent even generate the filters, fields and parameters correctly its like this:
`          {
            "name": "fields",
            "in": "query",
            "description": "Fields to return (ex: title,author)",
            "deprecated": false,
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "populate",
            "in": "query",
            "description": "Relations to return",
            "deprecated": false,
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filters",
            "in": "query",
            "description": "Filters to apply",
            "deprecated": false,
            "required": false,
            "schema": {
              "type": "object"
            },
            "style": "deepObject"
          },`

type of filters is object, it will give me error when i want to filter my articles like this filters: {
 title: {
   $eq: "name"
}
}

**Comment by fsbtmo** [comment]
I seem to have the same issue, when I visit the URL directly filters work as expected:

http://localhost:1337/api/pages?filters[path][$eq]=abcd
<img width="418" alt="image" src="https://github.com/strapi/strapi/assets/131470263/394fc264-be3c-46ed-85e9-cafe014e7fc1">

But when using the filters with the generated API like this:
```
const pageFilters = {
    path: {
      $eq: 'abcd',
    },
}

this.pageApi.getPages({ filters: pageFilters }).subscribe((pages:PageListResponse) => {
  this.pages = pages.data;
})
```

it does not work:
<img width="475" alt="image" src="https://github.com/strapi/strapi/assets/131470263/b0a5a2fb-17d8-4499-8946-fec6ff4c272b">

**Comment by alexandrebodin** [comment]
Hello, In order for your issue to be triaged it needs to follow the issue template.

We will close the issue in the meantime.
