### ISSUE TITLE
Component view with dynamic zone crashes app when trying to add more fields to said component

### ISSUE THREAD

**Issue by joshuaellis** [strapi/strapi#19362]
### Required System information

- Node.js version: 20
- Strapi version: 4.17.0 (still happening on `main` and `develop`)
- Is your project Javascript or Typescript: JS

### Describe the bug

When you add a dynamic zone to your schema in the CTB the UI is broken – the CTB thinks you want to add fields to the dynamic zone instead of the highlighted component within the CTB. If you press `add another field to this component` the app crashes because:

https://github.com/strapi/strapi/blob/a96121ddeb090c38e7553f9a520a4d97da965ebf/packages/core/content-type-builder/admin/src/components/FormModalHeader.tsx#L62

should have two optional chains because you can't index `undefined`. If you fix this, you then start adding fields directly to the DZ breaking schema validation. See image attached, there should be a list of fields for the selected component (a string called title).

### Steps to reproduce the behavior

1. Go to CTB
2. Make a component with just a title
3. make a content-type with a DZ field and add the aforementioned component
4. click "add another field to this component"
5. app will crash.

### Expected behavior

You should be able to see a list of the fields for each component listed in the DZ & then modify those components in situ of the DZ. Adding fields should only attach to the component & therefore validation of the schema should pass.

### Screenshots

![CleanShot 2024-01-29 at 14 17 06@2x](https://github.com/strapi/strapi/assets/37798644/8c6e3bd9-030e-4475-8ae4-ffcbe2af1352)

**Comment by spalz** [comment]
I also ran into that error.
