### ISSUE TITLE
Textbox don't open

### ISSUE THREAD

**Issue by sehrish30** [strapi/strapi#19385]
### Required System information

- Node.js version:  18.18.2
- NPM version: 9.8.1
- Strapi version: 4.19.0
- Database: mysql
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The textboxes don't open neither locally nor in production mode

### Steps to reproduce the behavior

1. Create a Rich text (Markdown) 
2. go to Content Manager and check it 
3. It never shows textbox

### Expected behavior
I want to see the textbox field opened, I have tried in browser without any extension and even in macos same issue

### Screenshots
<img width="470" alt="image" src="https://github.com/strapi/strapi/assets/66527974/01a81834-8662-46b9-8a13-8a51bbfd0eed">

**Comment by LucaNerlich** [comment]
I cannot reproduce this :/

**Comment by sehrish30** [comment]
> I cannot reproduce this :/
 make sure u have same versions
    "@strapi/helper-plugin": "4.19.0",
    "@strapi/plugin-i18n": "4.19.0,
    "@strapi/plugin-users-permissions": "4.19.0",
    "@strapi/strapi": "4.19.0",

**Comment by LucaNerlich** [comment]
if this is all thats needed, could you create a public repo with this setup?

**Comment by sehrish30** [comment]
> if this is all thats needed, could you create a public repo with this setup? Including your broken content setup.

install these packages and check the textbox

 "@notum-cz/strapi-plugin-content-versioning": "^0.4.7",
    "@sklinet/strapi-plugin-tinymce": "^1.0.4",
    "@strapi/helper-plugin": "4.19.0",
    "@strapi/plugin-i18n": "4.19.0",
    "@strapi/plugin-seo": "^1.9.8",
    "@strapi/plugin-users-permissions": "4.19.0",
    "@strapi/strapi": "4.19.0",
    "better-sqlite3": "8.6.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-hook-form": "^7.44.3",
    "react-router-dom": "5.3.4",
    "strapi-plugin-multi-select": "^1.2.3",
    "strapi-plugin-populate-deep": "^3.0.1",
    "strapi-plugin-preview-button": "^1.1.2",
    "strapi-plugin-redis": "^1.0.1",
    "strapi-plugin-rest-cache": "^4.2.6",
    "strapi-plugin-sitemap": "^3.0.6",
    "strapi-provider-rest-cache-redis": "^4.2.6",
    "strapi-provider-upload-bunnynet": "^1.0.3",
    "styled-components": "5.3.3",
    "tsc": "^2.0.4",
    "typescript": "^4.9.5"
    
    u can recreate it

**Comment by LucaNerlich** [comment]
Please provide a minimal reproduction example in a seperate repository. Thanks.

**Comment by sehrish30** [comment]
https://github.com/sehrish30/textbox-bug-strapi-project

you can check in the repo the issue is the installation of "@sklinet/strapi-plugin-tinymce" once removed the textbox works fine

**Comment by LucaNerlich** [comment]
well, that you've answerd your question yourselve. This is not an issue with strapi 😅

**Comment by Boegie19** [comment]
This is not a issue with strapi but with the @sklinet/strapi-plugin-tinymce plugin please open a issue on that repo instead.
