### ISSUE TITLE
 change user email as non required field

### ISSUE THREAD

**Issue by imHowie** [strapi/strapi#19389]
[[ change user email as non required field](url)](https://github.com/strapi/strapi/issues/5061)

和上述Issue一样，我也遇到了需要把Email改成非必填字段，因为我的用户账号体系是可以通过手机号注册，也可以通过邮箱注册，这两者是二选一的关系，也可以是二者皆有的关系，所以我非常希望能够能到帮助，解决此问题

**Comment by imHowie** [comment]
https://github.com/strapi/strapi/issues/5061#issuecomment-1895838703

这个解决方案并不管用了，我用的是Strapi 4.14.4版本

**Comment by derrickmehaffy** [comment]
Hello!

To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms. 

Thank you and have a wonderful day!

**Comment by imHowie** [comment]
> Hello!你好！
> 
> To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms.为了包容社区中的每个人，并提供每个人都可以参考的最佳答案，我们要求每个人都在我们各自的所有平台上使用英语。
> 
> Thank you and have a wonderful day!谢谢你，祝你有美好的一天！

https://github.com/strapi/strapi/issues/5061#issuecomment-1895838703
Like the above Issue, I also encountered the need to change the Email to an optional field, because my user account system can be registered through either mobile phone number or mailbox, which is a relationship of choice between the two, or both, so I very much hope to be able to help solve this problem.
