### ISSUE TITLE
@strapi/admin module not found

### ISSUE THREAD

**Issue by jasper-msrl** [strapi/strapi#19388]
### Required System information

 

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.19.0
- Database:
- Operating system: Macos
- Is your project Javascript or Typescript: Ts

### Describe the bug

I'm trying to update the strapi from v4.13.6 to 4.16.0 or above. No matter in which version, there's the same error when running the strapi:

`Creating admin[ERROR] Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package /Users/xx/node_modules/@strapi/admin (see exports field in /Users/xxx/node_modules/@strapi/admin/package.json)`

Here's my  package.json

```
"scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@bn-digital/strapi-plugin-field-uuid": "^1.2.12",
    "@palmabit/strapi-app-version": "^1.1.0",
    "@strapi/plugin-color-picker": "^4.13.6",
    "@strapi/plugin-documentation": "4.13.6",
    "@strapi/plugin-i18n": "4.13.6",
    "@strapi/plugin-seo": "^1.8.0",
    "@strapi/plugin-users-permissions": "4.13.6",
    "@strapi/provider-email-sendgrid": "^4.14.2",
    "@strapi/provider-upload-aws-s3": "4.13.6",
    "@strapi/strapi": "4.13.6",
    "pg": "^8.10.0",
    "reading-time": "^1.5.0",
    "strapi-plugin-publisher": "^1.3.4",
    "strapi-plugin-sitemap": "^2.0.10"
  },
```

### Steps to reproduce the behavior

1. Change strapi version to 4.16.0 or above in package.json
2. npm i
3. npm run develop
4. install react? n
5. Building build context...
6. See error

### Expected behavior

Should be able to run.

**Comment by derrickmehaffy** [comment]
You have a plugin importing something it shouldn't. You'll need to figure out which plugin and report it to the maintainer as it's not something we can/will fix.
