### ISSUE TITLE
Mongoose Hook connectivity fails on project creation on Windows

### ISSUE THREAD

**Issue by NickBolles** [strapi/strapi#1939]
**Informations**
- **Node.js version**: 8.12.0/9.11.2
- **npm version**: 6.4.1/5.6.0
- **Strapi version**: alpha14
- **Database**: Mongo
- **Operating system**: Windows 10

**What is the current behavior?**

`Strapi new` connection test fails when creating a mongodb project. The CLI also reports it as a success.

**Steps to reproduce the problem**

Since `strapi new` is currently broken in node 9 on windows, use the CLI to init a project
```
PS C:\newsync\Projects\RestaurantApp\app> strapi new server --dbclient=mongo --dbhost=lcalhost --dbport=27017 --dbname="mydb" --dbusername="" --dbpassword=""
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
Database determined by CLI args: mongo

⏳ Testing database connection...
{ <strong>Error: Cannot find module 'C:\Users\Nick\AppData\Local\Temp\strapifd3e9ff2ccd8\node_modules\mongoose'</strong>
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\Nick\AppData\Local\Temp\strapifd3e9ff2ccd8\node_modules\strapi-hook-mongoose\lib\utils\connectivity.js:8:20)
    at Promise.all.then (C:\Users\Nick\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js:259:126)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) code: 'MODULE_NOT_FOUND' }
<strong>The app has been connected to the database successfully!</strong>

🏗  Application generation:
√ Copy dashboard
√ Install plugin settings-manager.
√ Install plugin content-type-builder.
√ Install plugin content-manager.
√ Install plugin users-permissions.
√ Install plugin email.
√ Install plugin upload.
√ Link strapi dependency to the project.

👌 Your new application server is ready at C:\newsync\Projects\RestaurantApp\app\server.

⚡️ Change directory:
$ cd server

⚡️ Start application:
$ strapi start
```

First we have the path that is executed
![image](https://user-images.githubusercontent.com/7891759/45462761-d3ef6580-b6ce-11e8-963b-faf2d89efc8f.png)

In connectivity.js
![image](https://user-images.githubusercontent.com/7891759/45463332-4feaad00-b6d1-11e8-8c4d-81d3f57d131c.png)

But the structure is
<pre>
${tempPath}/node_modules/
    strapi-hook-mongoose/
       lib/
       package.json
       ...some other stuff
       node_modules/
           ...a bunch of modules... including
           <strong>mongoose/</strong>
</pre>

**What is the expected behavior?**

1. Mongoose is imported correctly and the project is created correctly.
2. When something errors, the success callback shouldn't be called...

**Suggested solutions**

Why do we even need to do some hacky path building to require mongoose? part of the whole point of require is that it's relative to the module. Just `require('mongoose')` should be fine right?

**Comment by lauriejim** [comment]
Hello @NickBolles , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
