### ISSUE TITLE
When I click off a dropdown, it closes the whole admin modal with unsaved data

### ISSUE THREAD

**Issue by watjuaninacio** [strapi/strapi#19409]
Admin Modals close without warning when forms have unsaved data which leads to data loss.

We're using Strapi V4.14.15 and Node V18.19.0

Is there any woraround for this?

https://github.com/strapi/strapi/assets/74307229/0915f8ac-ce7e-4e98-81cd-b74610bd0c3e

**Comment by Eventyret** [comment]
Thanks for reporting this, it's a known issue and should have a small workaround here
https://github.com/strapi/strapi/issues/18293#issuecomment-1872512293
Could you test that and let me know if that resolves it ?

**Comment by watjuaninacio** [comment]
Hi there,

Thanks for your comment.

Unfortunately , I installed both those modules but the problem persisted
after restarting / rebuilding strapi.

  "dependencies": {
    ***@***.***/strapi-plugin-awesome-seo": "^1.0.0-beta.1.2",

*    ***@***.***/react-dialog": "^1.0.5",
***@***.***/react-dismissable-layer": "^1.0.5",*
    ***@***.***/plugin-color-picker": "^4.15.5",
    ***@***.***/plugin-documentation": "^4.15.5",
    ***@***.***/plugin-i18n": "v4.14.5",
    ***@***.***/plugin-seo": "^1.9.6",
    ***@***.***/plugin-users-permissions": "v4.14.5",
    ***@***.***/strapi": "v4.14.5",
    "mailchimp-api-v3": "^1.15.0",
    "pg": "8.8.0",
    "strapi-plugin-config-sync": "^1.2.2",
    "strapi-plugin-import-export-entries": "^1.23.1",
    "strapi-plugin-local-image-sharp": "^1.7.0",
    "strapi-plugin-navigation": "^2.2.16",
    "strapi-plugin-responsive-image": "^1.2.0",
    "strapi-plugin-translate": "^1.2.4",
    "strapi-provider-translate-deepl": "^1.1.12",
    "strapi-utils": "^3.6.11",
    "yarn": "^1.22.19"
  },

If you have any other possible solutions for this, I appreciate your
feedback.

Kind regards,

Juan

**Comment by watjuaninacio** [comment]
> Thanks for reporting this, it's a known issue and should have a small workaround here [#18293 (comment)](https://github.com/strapi/strapi/issues/18293#issuecomment-1872512293) Could you test that and let me know if that resolves it ?

Hi there,

Thanks for your comment.

Unfortunately , I installed both those modules but the problem persisted after restarting / rebuilding strapi.

  "dependencies": {
    "@exfabrica/strapi-plugin-awesome-seo": "^1.0.0-beta.1.2",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-dismissable-layer": "^1.0.5",
    "@strapi/plugin-color-picker": "^4.15.5",
    "@strapi/plugin-documentation": "^4.15.5",
    "@strapi/plugin-i18n": "v4.14.5",
    "@strapi/plugin-seo": "^1.9.6",
    "@strapi/plugin-users-permissions": "v4.14.5",
    "@strapi/strapi": "v4.14.5",
    "mailchimp-api-v3": "^1.15.0",
    "pg": "8.8.0",
    "strapi-plugin-config-sync": "^1.2.2",
    "strapi-plugin-import-export-entries": "^1.23.1",
    "strapi-plugin-local-image-sharp": "^1.7.0",
    "strapi-plugin-navigation": "^2.2.16",
    "strapi-plugin-responsive-image": "^1.2.0",
    "strapi-plugin-translate": "^1.2.4",
    "strapi-provider-translate-deepl": "^1.1.12",
    "strapi-utils": "^3.6.11",
    "yarn": "^1.22.19"
  },

If you have any other possible solutions for this, I appreciate your feedback. 

Kind regards,

Juan




On Mon, 5 Feb 2024 at 06:06, Simen Daehlin <notifications@github.com> wrote:
Thanks for reporting this, it's a known issue and should have a small workaround here
[#18293 (comment)](https://github.com/strapi/strapi/issues/18293#issuecomment-1872512293)
Could you test that and let me know if that resolves it ?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/18293
