### ISSUE TITLE
Build scripts fail on windows

### ISSUE THREAD

**Issue by NickBolles** [strapi/strapi#1940]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: Master branch
- **Database**: n/a
- **Operating system**: Windows 10

**What is the current behavior?**

any commands that run the clean or clean:all scripts fail on windows because they run "rm"

**Steps to reproduce the problem**

run `npm clean` on windows

**What is the expected behavior?**

clean script completes correctly

**Suggested solutions**

Switch to a cross-platform npm module like rimraf.

**Comment by maturanomx** [comment]
That's just one of many other known issues on Windows. Can you try working on a VMs or with WSL?. I'm working with the second one :)

**Comment by NickBolles** [comment]
I'm making a pull request right now. What are some of the other issues? 

I know the `strapi new` command can simply be worked around with passing all the parameters in. Are there any other issues that I could work on to get more familiar with the code?
