### ISSUE TITLE
Release 4.19.1 is breaking relation field "load more" functionality

### ISSUE THREAD

**Issue by kalahooo** [strapi/strapi#19402]
### Required System information

Node.js version: 20
NPM version: 10.2.3
Strapi version: 4.19.1
Database: mysql
Operating system: macos
Is your project Javascript or Typescript: ts

### Describe the bug

"load more" link is missing near a relation field if count of relations more than 5

### Steps to reproduce the behavior

1. Create relation field
2. Add more than 5 relations

### Expected behavior

There is "load more" link near a relation field if count of relation more than 5

### Screenshots

<img width="549" alt="image" src="https://github.com/strapi/strapi/assets/5232408/c2d22c9b-81cd-43c9-a701-46ba69765312">

**Comment by AndreasFaust** [comment]
We are experiencing the same severe problem. 
Is there a workaround?

**Comment by kalahooo** [comment]
@AndreasFaust downgrade to 4.19.0

**Comment by JWesorick** [comment]
Also seeing this.

**Comment by MarionLemaire** [comment]
Reproduced today on 4.19.1 using CMS QA environment : 
- adding 7 relations to a Collection type entry
- "load more" icon is not displayed
- countdown displays "7" before saving, "5" after saving

**Comment by ogrodopedia** [comment]
Confirming this is an issue in 4.19.1 and in 4.19.0 is not.

**Comment by patrikalbertsson** [comment]
Confirming that downgrade to 4.19.0 shows the "load more"-button. But i noticed that it is showing the 5 last items before clicking load more, then prepending the incoming items.

**Comment by VichetN** [comment]
I faced the same issue, after i downgrade to 4.19.0 working fine.
