### ISSUE TITLE
@strapi/provider-upload-cloudinary Unwanted extra characters (hash) added to the public_id

### ISSUE THREAD

**Issue by ShaneDigi400** [strapi/strapi#19404]
### Required System information

- Node.js version: v18.18.2
- NPM version: v9.8.1
- Strapi version: 4.14.5
- Database: Postgres
- Operating system: 
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When I upload a file, Eg: test0014.pdf, 

Its public ID is set as “CMS-DEV/test0014_96b84ad0bf”

I want to keep my file & image names clear. Can I only have the public ID as follows
“CMS-DEV/test0014”
without an additional random string at the end.

### Steps to reproduce the behavior

1. Just upload file with @strapi/provider-upload-cloudinary
Can not have a clean public ID without that hash.

### Expected behavior

Need an option to upload the image without adding the hash to the end

### Screenshots

![Screenshot 2024-02-01 at 14 02 13](https://github.com/strapi/strapi/assets/116261037/5bee9b1c-3dc3-41c4-b77a-5fb5323522bc)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
This is intended and we don't plan on changing it as it prevents duplicate file issues where if two files uploaded with the same name would cause a conflict and could overwrite one file with another.

**Comment by ShaneDigi400** [comment]
@derrickmehaffy , If we make it optional, users can take on the responsibility. Cloudinary also allows this option. So, why can't Strapi?

Additionally, what is the solution for users who need clean URLs? How would it contribute to SEO scores?

Your insights on feasibility and potential advantages would be appreciated.

![Screenshot 2024-02-05 at 10 04 21](https://github.com/strapi/strapi/assets/116261037/3825a65f-e674-4ea4-8841-74ddba1e8a95)

**Comment by derrickmehaffy** [comment]
That would be a feature request/enhancement and you can add it here: https://feedback.strapi.io

It would require a much tighter integration with the providers than we currently have and would not be very high on our priority list as this topic has come up several times in at least the past 7 years I'm aware of but the potential issues out-weigh the benefits from what I've seen.

Clean URLs (at least for images) aren't required for SEO, that is a common and widely disproven myth.
