### ISSUE TITLE
Any content changes in strapi is not reflecting after restart.

### ISSUE THREAD

**Issue by saicharan-reddy1** [strapi/strapi#19417]
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.3
- Database: Postgress
- Operating system: windows

### Describe the bug

I have hosted application in Azure web app, whenever I add collection type and save, Strapi is getting in to restart and shows "restart taking longer duration" error.

My changes reflect after refreshing the page multiple times. The content that is added is not being consistent on UI. 

### Steps to reproduce the behavior

1. host application on Azure web app
2. try to add any content and save
3. it will show the error "warning: an error occurred"

### Expected behavior

Whenever we add content in strapi. It should show even after restart or page refresh

### Screenshots

<img width="960" alt="image" src="https://github.com/strapi/strapi/assets/142844794/138f25ca-d18f-4fbe-b471-5b3d24dc3de3">
<img width="960" alt="image" src="https://github.com/strapi/strapi/assets/142844794/55d1f3ba-84f7-4e0f-ba76-1027c49a7b7b">

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/19378
