### ISSUE TITLE
Pass parameters to policy

### ISSUE THREAD

**Issue by mrfrase3** [strapi/strapi#1942]
It would be nice to specify route-specific parameters in the api's routes.json

I think [URI style parsing](https://nodejs.org/api/querystring.html) would be the nicest solution.

so in the routes.json file:
```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/item",
      "handler": "Item.find",
      "config": {
        "policies": ["global.nameBanList?minLen=23&names=rock&names=paper&name=scissors"]
      }
    },
    {
      "method": "GET",
      "path": "/item/count",
      "handler": "Item.count",
      "config": {
        "policies": ["global.nameBanList?minLen=5&names=foo&names=bar"]
      }
    },
...
```
which then are available in the policy:
```js
module.exports = async (ctx, next) => {
  console.log(ctx.params); //logs: {minLen: 5, names: ["foo", "bar"]}
  return await next();
};
```

**Comment by kamalbennani** [comment]
Would be much easier if we can pass a payload, this way we won't need to parse the string and you'll be receiving the payload as the last param of the policy function.

```
policies: [{
  policy: 'global.nameBanList',
  payload: {} // Whatever
}]
```

**Comment by Aurelsicoko** [comment]
Oh, you're talking about validations? We started some work on this part (see https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/router/utils/routerChecker.js#L67). We are using Joi inside our router to be able to define request/response validations in the future.

**Comment by Aurelsicoko** [comment]
I recommend to read the full explanations of how the current implementation of the validators works (see https://github.com/strapi/strapi/pull/158#issue-90647904).

I'm closing this issue because there is already a public card on Product Board (https://portal.productboard.com/strapi/c/14-validations).
