### ISSUE TITLE
Error when importing content from a file -> metadata not found

### ISSUE THREAD

**Issue by pepegablaza** [strapi/strapi#19430]
### Required System information

- Node.js version: v18.13.0
- NPM version: v8.19.3
- Strapi version: v4.17.1
- Database: Postgres
- Operating system: MacOS Sonoma 14.3
- Is your project Javascript or Typescript:
Typescript

### Describe the bug

Me and my partner are working seperately through git on project, and usually i would export him through npm run strapi export command, and since my last push on git he is getting this error
![Screenshot 2024-02-05 at 13 30 33](https://github.com/strapi/strapi/assets/72709905/7e32c793-da38-4aea-956d-b7a3a7669efa) we have 1 on 1 code as i said through github repo and using same encryption key, it worked 3hrs ago atm its not working and it is really frustrating, also when i import that file everything works.

**Comment by pepegablaza** [comment]
Btw, i just tried to delete all of these components and create new ones,and i created new one and when i click save it says the same error for component which i deleted so im stuck.

**Comment by welschmoor** [comment]
same here `yarn strapi import -f export_20240222085110.tar.gz`, same machine, just different DBs, I wanted to move production DB to local, which I've done in the past.

**Comment by pepegablaza** [comment]
I figured out that it was problem with one component and its relations to database, so when i deleted it in database and in strapi, everything was fine
