### ISSUE TITLE
Apply changes from a dev strapi to a non dev strapi

### ISSUE THREAD

**Issue by betomoretti** [strapi/strapi#1943]
**Informations**
- **Node.js version**: 10.7.0
- **npm version**: 6.4.0
- **Strapi version**: alpha.13.1.0
- **Database**: mongodb
- **Operating system**: ubuntu 17.10

**What is the current behavior?**
My goal is to customize the strapi admin. I'm being able to so following the admin panel customization guide. What's not clear for me is how can apply those changes to my real project where I already have created some api endpoints and models and it's already deployed.

**Steps to reproduce the problem**
Create a project without `--dev` option.
Work on it.
Setup another strapi project in dev, following the respective guides to do that.
Customize the admin panel.

**What is the expected behavior?**
After reproduce the problem, apply the admin panel changes to non dev strapi project.

**Suggested solutions**
Copy file from --dev admin panel to the non --dev admin? I'm not sure.

Thanks! :)

**Comment by derrickmehaffy** [comment]
This is more so of how --dev works and what it does. Right now you create the --dev and it symlinks to the globally installed packages, so any modifications you make to the --dev are then pushed globally so all new projects will use these changes.

As far as I know there is no project based rebuild process, which makes managing multiple Strapi projects very complex as you have to swap out the globally strapi packages.

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/1828
(Not technically a duplicate but close)

**Comment by derrickmehaffy** [comment]
Not that I know (note I'm not a Strapi Team member) @soupette would be the best person to ask. But I do believe that in the future this won't be how the Admin is built. Realistically you should be able to modify the src directly in the project and then rebuild it without touching the global packages. But as of right now i don't believe that is the case (normal projects don't have the script :build).

**Comment by soupette** [comment]
@betomoretti currently the only way to apply changes to your project is to copy paste your build folder from your custom app into your production app.

**Comment by betomoretti** [comment]
@soupette I ended up coping my api endpoints to the dev started project. The thing now is that when I'm trying to run a container with the dev project is failing. Here's the process that I'm using:

```
# Dockerfile
FROM node:10-alpine

WORKDIR /usr/src/strapi-app

RUN npm i -g strapi@3.0.0-alpha.13.1

COPY . .
RUN chmod +x ./script.sh

EXPOSE 1338

CMD [ "./script.sh" ]
```
```
# script.sh
#!/bin/sh
cd /usr/src/strapi-app

npm install
npm run postinstall
NODE_ENV=production npm start
```
Do you know if I need an extra step? This building process is already working on the non --dev strapi app.

Thanks!

**Comment by soupette** [comment]
@betomoretti yes you should make just make sure that its `strapi-helper-plugin` dependency version is the same one as your app.

**Comment by soupette** [comment]
@betomoretti @derrickmehaffy here's how I handle the switch from a dev app to a prod 

## Steps to modify the front-end

### 1. Setup
*Here I'm going to detail my setup*

- Node.js version : v.10.10.0
- Npm version : 6.4..1
- Database: Mongod, Postgresql
- O.S: MacOs Mojave v.10.14.1 Beta

*Install the dev environment :*

```
# In a terminal window clone the strapi repository
$ mkdir repositories && cd repositories
$ git clone git@github.com:strapi/strapi.git && cd strapi
$ npm run setup
```

### 2. Once the setup is completed create a dev app

```
# In a new terminal window
$ mkdir sandbox && cd sandbox
# Create a dev app
$ strapi new my-app --dev

# Start your db
$ mongod

# Start the strapi server
$ cd sandbox/my-app && strapi start

# Start the front-end server to make modify the front-end
# In a new terminal window
$ cd sandbox/my-app/admin && npm start
```

### 3. Switch from your dev app to a prod one

*To switch from your dev app to your prod app you will have to build the admin and the plugins in the strapi repository and create a prod app.*

```
# In a terminal window navigate to the strapi repository
$ cd repositories/strapi

# Build the plugins with your modification
$ npm run setup:build
```

If the setup completed successfully you can create a new app with your modifications

```
# In a new terminal window
$ cd sandbox
$ strapi new my-prod-app
$ cd my-prod-app && strapi start
```

You should see your modifications in your prod app and be able to deploy it.

## Steps to create a plugin and install it in all your strapi projects

To create a plugin and install it in all your projects follow the first two steps from above.

### 1. Create a plugin

```
# In a terminal window
$ cd sandbox && strapi new my-app --dev
$ cd my-app && strapi generate:plugin my-plugin
```
Once the plugin is created copy the `my-plugin` folder into the `repositories` folder (where strapi is cloned).

### 2. Link the `strapi-helper-plugin`

```
$ cd repositories/my-plugin && npm link strapi-helper-plugin
```

### 3. Install the plugin in your dev app to modify it

```
# Navigate to the dev app (generated with the --dev flag)
$ cd sandbox/my-app/plugins
$ ln -s ../../../repositories/my-plugin ./
```

### 4. Build the plugin admin

To build the plugin's admin you will have to run the following commands inside your dev app where the plugins is installed:

```
$ cd sandbox/my-app
$ npm run setup --plugins
```

### 5. Install your plugin in a prod app

To install into your production application you just need to copy the folder of your plugin into your prod application `plugins` one.
