### ISSUE TITLE
rewirte media url not correct if url start with //

### ISSUE THREAD

**Issue by aouicher** [strapi/strapi#19437]
### Required System information

- Node.js version:
- NPM version: 18.19.0
- Strapi version: 4.19.1
- Database: PG
- Operating system: Ubuntu

### Describe the bug

All images are not displayed in Media Library if BaseUrl = "//cdn.domain.com"

### Steps to reproduce the behavior

1. Go to Media Library
4. See error: All images are not displayed if BaseUrl = "//cdn.domain.com"

### Expected behavior

Url have to be not rewrite with https//admin.domain/com//cdn.domain.com....
### Additional context

In plugin.js

Upload > config > 

baseUrl: `//${env('CDN_BASE_URL')}`

**Comment by derrickmehaffy** [comment]
Base URLs need to be absolute bug please provide your entire config. User issues with applying a configuration aren't entirely a bug it's more of question on "how do I configure this"

**Comment by derrickmehaffy** [comment]
The base URL shouldn't be configured this way, sure you can dynamicly build it but constructing the URL that way will lead to all kinds of problems and would not be a supported option for us.

**Comment by derrickmehaffy** [comment]
We specifically check the URL and if the protocol is not specified it's assumed to be relative not absolute

Modifying that would be a giant breaking change

**Comment by derrickmehaffy** [comment]
Changing it is not complicated you are correct but it's a breaking change and could cause a ton of problems elsewhere in the codebase that we are not willing to accept.

In the roughly 7 years I've been working for or on Strapi (as I've only worked for them for 4 of those) I have never seen anyone configure it like this.

This type of configuration is extremely subject and niche and we have to consider all of our users.

I understand this puts you in a bind but the way you are trying to configure this is just simply not supported. Any URL configuration in Strapi is either with or without the complete protocol / absolute or relative. It's always been that way and if this did work before, frankly I'd consider that a bug that it did.

Those mobile apps should be pretty much exclusively loading https content unless your in a dev environment.

**Comment by derrickmehaffy** [comment]
> Thank your for your answer. 
> I understand your point of view. 
> We will see in the future to make in place a force update on our mobile app. 
> 
> In the meantime we'll develop a plugin to take this into consideration.
> Thanks again.

No problem and sorry again
