### ISSUE TITLE
How to filter for NULL value (empty value)

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1944]
**Informations**
- **Node.js version**: 10
- **npm version**: 6
- **Strapi version**: 14.1
- **Database**: MariaDB 10.2
- **Operating system**: Linux Mint 19

**Question**

How do you filter based on an empty value?

For instance on my project here: https://api.canonn.tech:2083/body?edsmID=null

I'ved all the typical ways and always get returned an empty array `[]`

**Comment by lauriejim** [comment]
This case is not handle by our filter layer.

If you want it, you will have to code it yourself in your Controller and Service file.

**Comment by derrickmehaffy** [comment]
Hmmmm =/ I think this is something that should be added by default. I'll look into it to see if adding it globally is do-able with my minimal skills.

**Comment by Aurelsicoko** [comment]
We could add a specific filter for this particular case... Something like http://localhost:1337/body?edsmID_isNull=true or http://localhost:1337/body?edsmID_isNull=false?

**Comment by seanpowell** [comment]
Just want to second this.  It's an extremely useful feature.

**Comment by derrickmehaffy** [comment]
I haven't had the time to take look. Got a lot of other stuff going on atm FYI

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I'm going to reopen this as I don't see a card on the product board and I don't want this FR to get lost in the issues.

**Comment by Aurelsicoko** [comment]
As I said, the card is private on PB, you can't see it 🙈

**Comment by derrickmehaffy** [comment]
psttttt @Aurelsicoko make it public so people stop asking about it 😛

**Comment by Aurelsicoko** [comment]
I want to keep the public roadmap understandable... if we make everything public, it will be a mess.

**Comment by derrickmehaffy** [comment]
added: https://github.com/strapi/strapi/pull/3562

**Comment by Darrel-Collinsworth** [comment]
hmmmm, seems like a pretty useful feature that honestly should be out of the box.

**Comment by derrickmehaffy** [comment]
> hmmmm, seems like a pretty useful feature that honestly should be out of the box. 

This exists on Strapi v4. Locking as we already have both filters.
