### ISSUE TITLE
Version display

### ISSUE THREAD

**Issue by ahmadjoya** [strapi/strapi#19464]
##Version display
it's a while that the strapi version display is not working correctly. here is an example:
my current version is v4.20.0
and the latest version is also v4.20.0
but in the settings section, it shows a highlight notification which previously was for version displaying.

plz look at the screenshot bellow:
![image](https://github.com/strapi/strapi/assets/35627961/7cf0be94-85ae-415f-a537-f4652d395cf6)

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/19199
