### ISSUE TITLE
v4.20.0 translations of content, not linked

### ISSUE THREAD

**Issue by boardmain** [strapi/strapi#19476]
Hi i just upgraded to v4.20.0 from v.4.19.1

VERSIONE NODE
v20.11.0

i had 2 locale ( it and en, with it as default )

now i added 3 more locales

when i create content, ( for example italian )

i save it, i click on locale select to translate it in another language,

i save it (in english for example )  i come back to italian,but the content in italian is missing,

but it is saved without the link from the two items ( is it created as standalone content if i switch locale form the collection list i see both italian and english version)

**Comment by boardmain** [comment]
downgraded to 4.19.1 and it work again

**Comment by KasperiP** [comment]
Yeah same issue. I have companies and companies_localization_links on my db (generated by strapi). After I updated to v4.20.0 it doesn't add anything to the linking table anymore. Temporary fixed the issue by manually creating linking on the companies_localization_links table but can't recommend doing that.
