### ISSUE TITLE
"Last updated by" user of a record is incorrect after connecting or editing a related field. 

### ISSUE THREAD

**Issue by cody-fjorge** [strapi/strapi#19475]
### Required System information
Environment: development
OS: darwin-x64
Strapi Version: 4.9.2
Node/Yarn Version: npm/8.2.0 node/v16.6.1 darwin x64 workspaces/false
Edition: Community
Database: mysql
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

When connecting or updating related entities (children) to another entity (parent) the parent entity updates the updated at time but keeps the same last updated by user. 

This behavior caused confusion concerning security in the admin during content entry recently. We received a report from a user that they updated a relation and saw that the parent of that relation was updated around the same time by a user who was not in the system at that time. This triggered a security audit to scan for someone hacking into a user account for a user that was verified to be not logged in at the time. 

### Steps to reproduce the behavior

1. Create 2 users in the admin
2. Create an entity. (Ex. Book)
3. Create a field in that entity that is a relation to the same entity. (Ex. Book Variants)
4. Create the first record for the entity using USER1 (Ex. Book no.1)
5. Observe the "Last updated by" user is USER1
6. Create the second record for the entity using USER2 (Ex. Book no.1 Paperback)
8. Assign the first record to the relation field of the second record and save. (Ex. Book no.1 Paperback now has a variant relation to Book no.1)
9. Observe the "Last updated by" for the second record user is USER2
10. Go back to the first record's screen and observe the Last updated by time has changed to be the same as the second record **but** the Last updated by user is USER1

### Expected behavior

When a user updates a related field that triggers an update to its connected relations, the connected relations should reflect the user that triggered the updates as the last updated by user for the effected relations records.

**Comment by derrickmehaffy** [comment]
These are system fields controlled by the database, the issue is that those timestamps are not updated by Strapi, they are updated by the database directly and the user information isn't stored on the same table so the database doesn't see the primary data table being updated.

There isn't really anything we can do about that because the primary data does have "an update" it's the middle relation joining table.

**Comment by derrickmehaffy** [comment]
We do have an audit logs feature in our enterprise edition that has more advanced logging: 

- https://strapi.io/pricing-self-hosted
- https://strapi.io/pricing-cloud
