### ISSUE TITLE
Internationalization (i18n) plugin not working well on admin panel in v4.20.0

### ISSUE THREAD

**Issue by PenguinOfWar** [strapi/strapi#19486]
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.6.7
- Strapi version: v4.20.0
- Database: sqlite, mysql (reproducible on both)
- Operating system: MacOS, darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Apologies if this is a duplicate, I couldn't find anything that matched this issue on Github or the forums.

Using the i18n plugin via the strapi admin panel yields unexpected results when creating related localizations. Creating a record, selecting another locale from the edit page, populating fields, and then saving the localised record does not relate the two records together. This is verifiable by switching back to the original language where you are presented with a 'create new entry' page instead of the expected 'edit entry' page.

Rolling back to `v4.16.2` and trying this again works exactly as expected. The two records are nicely related together.

It's hard to demonstrate in screenshots, but see the screenshots below. Can provide a video of it in action if helpful.

### Steps to reproduce the behavior

1. Go to create entry
2. Populate some content in fields for the default locale
3. Save your entry
4. Click on another locale from the dropdown
5. Observe related entity ID in URL to confirm (`plugins[i18n][relatedEntityId]=12`)
6. Populate some content in fields for your localised entry
7. Save
8. Switch back to default locale, you will see the 'Create entry' screen
9. Return to entry list for your content type and verify the two entries are not related as localizations

### Expected behavior

As in `v4.16.2`, localized entries should be related by entity ID. Note that relation works when using the end-user REST API. 

#### Not working on `v4.20.0`

<img width="946" alt="Screenshot 2024-02-12 at 15 14 40" src="https://github.com/strapi/strapi/assets/1913241/1302d30e-7698-4155-ac34-ff6d67cb09d1">
<img width="907" alt="Screenshot 2024-02-12 at 15 26 07" src="https://github.com/strapi/strapi/assets/1913241/0cd114cd-5346-43d2-bdcc-cd2912b8de6f">
<img width="944" alt="Screenshot 2024-02-12 at 15 14 55" src="https://github.com/strapi/strapi/assets/1913241/40761336-a450-4a51-a923-b50f39609ef0">
<img width="911" alt="Screenshot 2024-02-12 at 15 15 01" src="https://github.com/strapi/strapi/assets/1913241/b097be15-cc6b-4c8f-ae93-ccd2793b44b8">
<img width="912" alt="Screenshot 2024-02-12 at 15 15 10" src="https://github.com/strapi/strapi/assets/1913241/2164d929-183e-4641-a443-46d8764b2e1a">

#### Working on `v4.16.2`

<img width="932" alt="Screenshot 2024-02-12 at 15 13 35" src="https://github.com/strapi/strapi/assets/1913241/d3c0a808-1bb4-4bce-b675-941a9b51905b">
<img width="944" alt="Screenshot 2024-02-12 at 15 13 42" src="https://github.com/strapi/strapi/assets/1913241/d8dfb6b5-8533-4e37-aca4-70ca959c9f1d">
<img width="903" alt="Screenshot 2024-02-12 at 15 13 52" src="https://github.com/strapi/strapi/assets/1913241/3a7b8428-b500-498d-b1c8-8b8baf1908ce">

**Comment by codymorgan** [comment]
Can confirm this same bug. It does not appear to affect existing translation relationships, thankfully.

**Comment by WomaWoma** [comment]
I Have the same bug. It seems to be a problem in the latest version(4.2.0) it occurs only with the content Type Collection I tested it with Single Types works fine.

**Comment by beeb** [comment]
Can confirm, it's very broken. Also, the data returned by the API has an empty `attributes.localizations` object instead of providing the other language items.

**Comment by PenguinOfWar** [comment]
> Can confirm, it's very broken. Also, the data returned by the API has an empty `attributes.localizations` object instead of providing the related language items.

As a workaround, the REST API still seems to work. Not ideal but it'll do in a pinch.

`POST http://localhost:1337/api/restaurants/8/localizations`

```json
{
  "locale": "en",
  "name": "She's Cake",
  "description": "description in English"
}
```

https://docs.strapi.io/dev-docs/plugins/i18n

**Comment by kasonde** [comment]
Confirmed in v4.20.0. The `<content_type>_localizations_links` table is not being populated/persisted.

**Comment by beeb** [comment]
Thanks for the quick fix! It works now for newly created related items. Is there a way to link again the unlinked versions that were created with 4.20.0 ?

**Comment by PenguinOfWar** [comment]
> Thanks for the quick fix! It works now for newly created related items. Is there a way to link again the unlinked versions that were created with 4.20.0 ?

@beeb Unfortunately I'm not sure there's a simple way of doing this as those relationships were never captured to begin with. I tried the typical `connect` method for relationships via `PUT` on the REST API but it didn't seem to work.

```json
{
    "data": {
        "localizations": {
            "connect": [3]
        }
    }
}
```

Result:

```json
{
    "data": {
        "id": 6,
        "attributes": {
            "someText": "New unrelated FR",
            "createdAt": "2024-02-15T08:59:29.110Z",
            "updatedAt": "2024-02-15T09:06:52.202Z",
            "locale": "fr",
            "localizations": {
                "data": []
            }
        }
    },
    "meta": {}
}
```

Would you be helpful if this feature worked, but will need a feature request (unless I've missed something!).

**Comment by magom001** [comment]
Tested in 4.20.1. It works better but still fails when trying to publish by switching the locale from an entry page. I am getting:

`The related entity doesn't exist or the entity already exists in this locale`

 You need to change the locale on the collection page, navigate to an entry and then publish.

**Comment by shivarajnaidu** [comment]
I just upgraded to 4.22.1 ... still whenever I switch the language , the localization content is not available..

If I add a new record it is working fine, but existing content is not working instead it is displaying draft mode form


<img width="611" alt="Screenshot 2024-04-07 at 6 24 51 AM" src="https://github.com/strapi/strapi/assets/12374494/5436e28a-e7c7-4e78-a730-85b5a94c2313">

**Comment by conradgellel** [comment]
I've also upgraded to v4.23.0 and having the same issue.
