### ISSUE TITLE
Plugin React Component - preventDefault() on form submit does not work

### ISSUE THREAD

**Issue by welschmoor** [strapi/strapi#19484]
### Required System information

Strapi, Node

- Node.js version:  v18.19.0
- Strapi version: ^4.19.1
- Database: Azure postgres
- Operating system: MacOS
- Javascript

### Describe the bug

I have created a plugin, which is a React/JSX form with an onSubmit event. The bug is that
e.preventDefault() does not work / has no effect, the strapi:1337/admin page simply refreshes

### Steps to reproduce the behavior

Use something like this in your custom admin Component:
```
  const [data, setData] = useState('')

  const submitData = async (e) => {
    e.preventDefault()
    e.stopPropagation()
    console.log('clicked:::')
  }

  return (
    <>
      <form
        onSubmit={submitData}
        id="previewform"
        style={{
          position: 'absolute',
          top: '100px',
          right: '100px',
          zIndex: 999,
          background: 'white',
        }}
      >
        <input
          type="text"
          id="my-message"
          value={data}
          onChange={(e) => {
            setData(e.target.value)
          }}
        />
        <button type="submit">submit</button>
      </form>
```

### Expected behavior

The page should not refresh

**Comment by joshuaellis** [comment]
Do you have a reproduction of this? We use a lot of forms this way and don't have any issues :)
