### ISSUE TITLE
s3 bucket name limitations in @strapi/provider-upload-aws-s3

### ISSUE THREAD

**Issue by simondriesen** [strapi/strapi#19494]
At my company we always use dots (`.`) in our S3 Bucket names. These names with a dot causes SSL certificate issues in this plugin. Would it be possible for you to structure the `Object URL's` used by this plugin differently?

Instead of:

**bucketName.withDot**.s3.eu-west-1.amazonaws.com/file-name.png

have:

s3.eu-west-1.amazonaws.com/**bucketName.withDot**/file-name.png

**Comment by simon-roland** [comment]
I think you can solve this using by setting "s3ForcePathStyle" to true in the plugin config.

My config looks like this. Note that I do not use Amazon's s3 servers.

`upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        baseUrl: env('AWS_URL'),
        s3Options: {
          s3ForcePathStyle: true,
          endpoint: env('AWS_ENDPOINT'),
          credentials: {
            accessKeyId: env('AWS_ACCESS_KEY_ID'),
            secretAccessKey: env('AWS_ACCESS_SECRET'),
          },
          region: 'default',
          params: {
            Bucket: env('AWS_BUCKET'),
          },
        }
      },
    },
  }`
