### ISSUE TITLE
Error classes ValidationError, ApplicationError toast not surfacing on the Admin panel

### ISSUE THREAD

**Issue by Pixfloage** [strapi/strapi#19495]
### Required System information

OS: darwin-x64
Strapi Version: 4.19.1
Node/Yarn Version: npm/10.2.3 node/v20.10.0 darwin x64 workspaces/true
Edition: Community
Database: postgres
Is your project Javascript or Typescript: Typescript

### Describe the bug

When throwing a ValidationError, the error toast/ notification is not visible on the admin panel. Previously it was working correctly (around 4.9.0).

### Steps to reproduce the behavior

I'm importing the ValidationError like this, and throwing a custom error inside a lifecycle method currently.
```
import { errors } from '@strapi/utils'

const { ValidationError } = errors
...
throw new ValidationError('Cannot publish...')
```

### Expected behavior

If I throw an ApplicationError or a ValidationError, it should be visible on the Admin panel as a toast, error message as it previously did. It worked before and the documentation also confirms that I didn't hallucinate it.
The error itself is visible on the network tab, and the error handling part is working correctly. Just the toast went missing.

### Screenshots

https://github.com/strapi/strapi/assets/12548918/1652c198-6620-42ea-91a3-a2a410d8e794

**Comment by WDeenik** [comment]
I ran into this as well on 4.17.0 but after updating Strapi to 4.20.2 it worked again like expected.

**Comment by Pixfloage** [comment]
Tried with latest 4.20.3 - still doesn't work neither with ValidationError nor ApplicationError. I see a correct http 400 on the Network call, but the toast is still missing, no sign of the actual error on the admin panel.

**Comment by GabrielGallina** [comment]
@Pixfloage 
I'm having the same problem in my project, do you have any updates?

**Comment by 00sapo** [comment]
See https://github.com/strapi/strapi/issues/18041

**Comment by WDeenik** [comment]
Had this issue before and like I said above, when updating Strapi it worked again. Now we're running into it again, but I seem to have managed to find what was causing it: we had a version mismatch between the `@strapi/strapi` and `@strapi/utils` packages. This caused Strapi to use a different version of `@strapi/utils` internally than we were using in our lifecycles, which in turn made Strapi not recognize our ApplicationErrors as such, treating it like any other generic error instead of nicely formatting it.

**Solution**: make sure the `@strapi/utils` package you use in your lifecycles has the same version number as the `@strapi/strapi` package you're using.

**Comment by 00sapo** [comment]
I'm not sure why you people continuously state that this is not a bug and that it is not reproducible. It's easy: create an ubuntu docker, install node nad yarn and use the above `package.json`. 

@WDeenik your solution (i.e. adding `"@strapi/strapi": "4.22.1",  "@strapi/utils": "4.22.1"` simply doesn't work and is not a solution for this bug.

**Comment by Adaphath** [comment]
Came to the same conclusion. But v4.17.0 was a huge update and I cannot identify any direction where this comes from.
Without this, our content team is not able to work...

Any workaround do enable them temporarily?

**Comment by PoliPH** [comment]
I see this change in 4.17.0 https://github.com/strapi/strapi/pull/19093/commits/1107713a66e9caafa0e748e56c5c0a7701639af2 that has relation to utils and maybe ApplicationError, It could be this?

**Comment by PoliPH** [comment]
It could be something related to this feat https://github.com/strapi/strapi/commit/728d614ca4116060132514ba8c504a2d136c3c4c#diff-efa4b33d0020a450f18d1261ac1b053e4389615ceb9484ba4674dffd21b46212 has a lot of changes in errors.ts file

**Comment by LexLuengas** [comment]
Related #15017

**Comment by kasonde** [comment]
Bumping up sev high. Ref TID 6677.

**Comment by stevensturkop** [comment]
I can confirm this bug in
4.24.1
4.24.2

**Comment by PoliPH** [comment]
We need a solution for this bug, our team is stuck on version 4.16.2 and we need to update strapi. We have some logical validations in the life cycles and without error messages our team is not able to work.

**Comment by sergixnet** [comment]
I can confirm this bug when updating from 4.15 to 4.25.2.

With a fresh install of 4.25.2 it works ok.

I try these fresh installs that work ok:

![image](https://github.com/strapi/strapi/assets/3718414/b8431c57-69e0-4580-ad56-30e6854f5341)

![image](https://github.com/strapi/strapi/assets/3718414/85354116-6458-4b17-b878-fa0fdea9e099)

Please we need a solution. We are stuck too in versión 4.16.2. like @PoliPH 

Thanks

**Comment by 00sapo** [comment]
> With a fresh install of 4.25.2 it works ok.

Can you report on OS version, Node version, and paste your packages.json?

**Comment by sergixnet** [comment]
OS: Ubuntu 24.04
Node version: v20.11.0

The strapi is installed inside a NX monorepo as a ["package based"](https://nx.dev/concepts/integrated-vs-package-based#packagebased-repos). 

This is the `package.json` of the strapi:

```json
{
  "name": "backend-manager",
  "private": true,
  "version": "0.0.13",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.25.2",
    "@strapi/plugin-users-permissions": "4.25.2",
    "@strapi/provider-email-nodemailer": "^4.25.2",
    "@strapi/strapi": "4.25.2",
    "mysql2": "3.6.2",
    "qr-image": "^3.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-router-dom": "^5.3.4",
    "@types/react-router-dom": "^5.3.3",
    "strapi-plugin-country-select": "^1.0.3",
    "styled-components": "^5.3.11"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "7ae58613-b37d-4e85-bd58-f433d04df1b3"
  },
  "engines": {
    "node": ">=16.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by derrickmehaffy** [comment]
We will need a reproduction of this in a fresh app without any of the "extras" like nx pm and others.

Npm or yarn and no workspaces.

**Comment by sergixnet** [comment]
It seems that the error is located for example in this line: https://github.com/strapi/strapi/blob/8991df149bf14762f53e135330a8e84ca6b7e983/packages/core/admin/admin/src/content-manager/components/ContentTypeFormWrapper.tsx#L499

When trying to check that the variable `err` is an instance of `AxiosError`.

If the variable `err` is printed, this appears: 

```json
{
    "message": "Request failed with status code 400",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 400\n    at pc (http://localhost:1337/admin/main.44e82885.js:4173:1133)\n    at XMLHttpRequest.Oi (http://localhost:1337/admin/main.44e82885.js:4173:4659)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": "Bearer SECRET"
        },
        "paramsSerializer": {},
        "baseURL": "http://localhost:1337",
        "signal": {},
        "params": {},
        "method": "put",
        "url": "/content-manager/collection-types/api::license.license/14",
        "data": "SECRET"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 400
}
```

**Comment by sergixnet** [comment]
Finally strapi 4.25.2 in a NX monorepo works OK.

I had axios 1.7.0 installed and strapi is using axios 1.6.0

I changed the version of axios to 1.6.0 and works well :+1:

**Comment by PoliPH** [comment]
@sergixnet We already have axios installed in our project, 1.6.8 in our case. I will install 1.6.0 to check if notifications works with that version.

**Comment by PoliPH** [comment]
@sergixnet it's works fine with 1.6.0. Thanks!!

**Comment by Pixfloage** [comment]
Can verify, pinning down axios to 1.6.0 fixed the issue in our monorepo setup as well! 🎉

**Comment by abaksha-sc** [comment]
Trying to upgrade strapi to the latest v4.25.24 (and then later to v5). And nothing helps for me to show custom error messages...
Tried to use axios ^1.6.0, tried to add middleware from this comment: https://github.com/strapi/strapi/issues/20343#issuecomment-2316954584

This issue is pretty critical as we use it as server validation and user will not understand what is wrong.
