### ISSUE TITLE
ids showing instead of names after clicking "load more" on relation field 

### ISSUE THREAD

**Issue by sracela** [strapi/strapi#19507]
### Required System information

- Node.js version: v18
- NPM version: 8.6.0
- Strapi version: 4.20.0
- Database: Postgres
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

As you can see in the first screenshots below , the first time you go into some of my Client Collection item everything works as expected. As soon as you clicked on "load more" on Brand relation field, the new items that appear show themselves with their ids instead of their names.

### Steps to reproduce the behavior

1. Go to some collection where their types have at least one relational field with a good amount of items
2. Click on any of the items of the collection
3. Click on "load more" for the relational item

### Expected behavior

I would expect the new items to appear with the field is selected as entry field, in my case "name" instead of "id"

### Screenshots
First screenshot before clicking on "load more". Second screenshot after clicking "load more"

<img width="547" alt="sc1" src="https://github.com/strapi/strapi/assets/43761621/79f783bd-9131-4644-a871-7a09b42c0c5e">
<img width="566" alt="sc2" src="https://github.com/strapi/strapi/assets/43761621/5bcfcb1f-ebd6-43d9-85bf-1f69dc9a48a4">

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/19625
