### ISSUE TITLE
Contact Component Data Not Included in Sign-in Response

### ISSUE THREAD

**Issue by Lawrenxz** [strapi/strapi#19501]
### **Bug report**

I am encountering an issue with my Strapi application where the user data from the Contact component is not included in the response when signing in. Despite having populated data in the Contact component for users, the response from the sign-in endpoint does not include this information.  However, upon further investigation, it has been observed that when triggering the API request to retrieve user information after logging in, the Contact component data is indeed populated in the response. I need it in sign-in response.

Sign-in 
![image](https://github.com/strapi/strapi/assets/100080440/0b23c12c-81cb-4017-9275-aad6d92bf346)

### **Expected Response**
![image](https://github.com/strapi/strapi/assets/100080440/c743089c-3731-4133-b2ef-0b45e7bf3113)

### **System**
Node.js version: v20
NPM version:
Strapi version: v4
Database: Postgres 
Operating system: Windows 10

**Comment by joshuaellis** [comment]
Can you please reformat your issue to follow the template? thank you
