### ISSUE TITLE
Content block text is duplicated after deleting another content block

### ISSUE THREAD

**Issue by mauromontano** [strapi/strapi#19517]
### Required System information

- Node.js version: v18.18.0
- NPM version: 9.8.1
- Strapi version: 4.15.5
- Database: MySQL
- Operating system: MAC Monterey
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When you have multiples content blocks in your blog, after deleting one, in the others the text it contains is duplicated and spaces are added. Saving and refreshing fixes it, but generates confusion when previewing and working.

### Steps to reproduce the behavior

1. Have a blog with more than one content block added
2. Remove one content block
3. Content block will be removed but the text inside of the others content blocks will show duplicated

### Expected behavior

Remove just that content block without affecting the others

### Screenshots

Before delete one content block I have this text in another :

![Screen Shot 2024-02-15 at 09 44 06](https://github.com/strapi/strapi/assets/42441560/885d872c-3ea9-4849-948c-45966ec2f0e7)

I deleted this content block:

![Screen Shot 2024-02-15 at 09 44 40](https://github.com/strapi/strapi/assets/42441560/70bc0551-39c6-462f-b39c-8334a97cc4aa)

After deleting one content block the text are duplicating like in this one:

![Screen Shot 2024-02-15 at 09 45 19](https://github.com/strapi/strapi/assets/42441560/a64ceeb4-42eb-4a5a-b4d2-7c07b6899a10)

content_block is:

![Screen Shot 2024-02-15 at 10 10 21](https://github.com/strapi/strapi/assets/42441560/c114f067-fddf-45c2-8e7f-40ea1f44feae)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by simotae14** [comment]
Hello @mauromontano thanks a lot for your github issue.
We have already a similar bug opened time ago https://github.com/strapi/strapi/issues/17858 so I am gonna close yours. We are working on a solution, https://github.com/strapi/strapi/pull/19480.
Thanks again
