### ISSUE TITLE
Cannot hide or replace all tech info in the welcome page

### ISSUE THREAD

**Issue by nbro10** [strapi/strapi#19516]
## Bug report

I think this is actually a bug and not just a feature request, so let me open the issue.

### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.16.2
- Database: PostgreSQL
- Operating system: Ubuntu 20.04
- Is your project Javascript or Typescript: JS

### Describe the bug

I'm unable to remove all tech info from the welcome page. My users have no programming knowledge at all.

### Steps to reproduce the behavior

1. Launch any 4.16.2 app
2. Go to the welcome page
3. See that you have all tech info that is useless and noisy to most users and you're unable to quickly remove that

### Expected behavior

I'm able to remove all tech info from the welcome page and are able to add my own custom links. 

### Screenshots

![Screenshot 2024-02-15 at 13 31 06](https://github.com/strapi/strapi/assets/106664639/8bc06daf-3440-475e-9b53-35d2070de140)

### Additional context

This has been requested many times. It's clearly a very needed feature, and it's just a bug now, because it's not yet been implemented. See e.g. https://feedback.strapi.io/feature-requests/p/customize-the-admin-dashboard-welcome-page-v4 and https://feedback.strapi.io/feature-requests/p/allow-easy-replacement-of-welcome-to-your-strapi-app-page or many other ignored posts in the Strapi forum https://forum.strapi.io/t/customize-the-dashboard-welcome-page.

We're able to remove the tutorials, so I don't see why we should not also be able to remove or at least hide (to most users) all other links. Note: as an admin and developer, I don't care if I see these pages, but I don't want regular users to see them. 

If you want to advertise Strapi, it's ok to leave a message at the bottom that says "Developed with Strapi" (I think this is more than enough), although, again, it would be nice if users didn't have to know what we're actually using. In fact, they don't care at all. Again, I don't care if I see this info.

**Comment by derrickmehaffy** [comment]
While I understand you believe this is a bug, it is not and should be considered a feature request and posted on: https://feedback.strapi.io

**Comment by romitkarmakar** [comment]
This is a very high priority feature that the Strapi team need to focus. Even we are facing huge difficulties in making the clients understand why this ui exists in the dashboard.
