### ISSUE TITLE
Content Blocks does not allow for `mailto:` email links

### ISSUE THREAD

**Issue by preist** [strapi/strapi#19524]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 4.20.0
Node/Yarn Version: npm/10.2.4 node/v21.6.1 darwin arm64 workspaces/false
Edition: Community
Database: mysql
Project is in TypeScript

### Describe the bug

The new rich text editor does not allow for `mailto:` links.

### Steps to reproduce the behavior

1. Open any content type featuring Content Blocks rich text editor
2. Add an email link (e.g. `mailto:example@email.com`)
3. Save the article
4. Observe a `Warning: url must be a valid URL`

![2024-02-16 11 09 02](https://github.com/strapi/strapi/assets/14940633/17853bb7-d65d-4f21-b0c0-c4bb1018258c)

### Expected behavior

I expect to be able to add an email link.

**Comment by turbek** [comment]
Hi!

I'd like to add, that we'd like to use internal linking. It seems that it is currently not supported.

We'd like to use `/page` format instead of `https://*`.

**Comment by martinlarka** [comment]
> Hi!
> 
> I'd like to add, that we'd like to use internal linking. It seems that it is currently not supported, since the `save` button remains disabled.
> 
> We'd like to use `/page` format instead of `https://*`.

Hello!

I wish to do the same. I need to be able to set both mailto:-links and relative links. Maybe a config flag to disable url validation would be a good solution. Or maybe I missed why the url needs to have a scheme and everything.

**Comment by djoohl** [comment]
i second this. I need to be able to use mailto:-links and relative links.

**Comment by ezaniljazi23** [comment]
Any updates on this like will it be in the near future available to add mailto?

**Comment by Eventyret** [comment]
I just tested this on v4.23.0 and I do not get the error message.
![image](https://github.com/strapi/strapi/assets/977232/6ee8d529-7cc6-474a-bf92-b8a899785111)
![image](https://github.com/strapi/strapi/assets/977232/071ed3bb-273a-40d7-8c63-9b12739d7220)

**Comment by designtology** [comment]
Can anyone confirm this is still working in v4.24.4?

**Comment by tcmalcomb** [comment]
I was also able to verify that mailto and relative page links are able to be inserted and the page saved/published without error on Strapi v5.0.0.

![richTextBlock_MailtoLink](https://github.com/user-attachments/assets/32d1d206-3daa-4de1-be98-391258a03bf9)

![richTextBlock_RelativeLink](https://github.com/user-attachments/assets/22bb9952-9b5f-4954-ba6b-c4c2b9b291b0)

**Comment by preist** [comment]
This seems fixed and can be closed.
