### ISSUE TITLE
Data disappeared from panel

### ISSUE THREAD

**Issue by signorekai** [strapi/strapi#1952]
**Informations**
- **Node.js version**: 10.7
- **npm version**: 6.30
- **Strapi version**: 3.0.0-alpha.14.1
- **Database**: mongo
- **Operating system**: Mac OS (but running inside docker, linux alpine image)

**What is the current behavior?**
After upgrading to alpha.14.1, my panel's data was all gone. Turns out the format has changed.

**Steps to reproduce the problem**

Prior to 3.0.0-alpha.14.1 (and maybe 3.0.0-alpha.14, though I did not encounter this), in order to use srv, this is the `database.json`:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "uri": "mongodb+srv://<user>:<pass>0@<host>/<database>"
      },
      "options": {
        "ssl": true
      }
    }
  }
}

```

The new format is now as follows:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "<host>",
        "srv": true,
        "port": 27017,
        "database": "<db>",
        "username": "<user>",
        "password": "<password>"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**What is the expected behavior?**
It should connect to the correct database.

**Suggested solutions**
Update your `database.json` in your `/config/environments/**/`
Probably want to make sure this is also mentioned in the migration guide?

**Comment by derrickmehaffy** [comment]
@signorekai I would suggest in this case since you are using docker that you use the URI as an environment variable and pass it to your docker container.

**Comment by signorekai** [comment]
@derrickmehaffy any particular reason why?

**Comment by lauriejim** [comment]
I think you failed something during your migration.
Change version not affect your configs files.

https://github.com/strapi/strapi/wiki/migration-guide-alpha.14-to-alpha.14.1

**Comment by signorekai** [comment]
That wasn't what I meant; I know it doesn't change my config files. I'm just saying the config file format was updated.

I had this as my config previously:
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "uri": "mongodb+srv://<user>:<pass>0@<host>/<database>"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

And after updating to alpha.14 (or alpha.14.1), strapi is not connecting to my db properly. I started a new project with `strapi new` and compared the config file, and found that the new project had a new format for the config, as such:

```


{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "<host>",
        "srv": true,
        "port": 27017,
        "database": "<db>",
        "username": "<user>",
        "password": "<password>"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**Comment by lauriejim** [comment]
It's because you update your database.json file on your previous project nop ?
