### ISSUE TITLE
Issue directly publishing a translated entity after translating

### ISSUE THREAD

**Issue by iwap** [strapi/strapi#19528]
### Describe the bug

When creating a translation of an entity and directly publishing it we get an error that complains about the related entity not existing or the entity already existing the locale.

Warning:
The related entity doesn't exist or the entity already exists in this locale

Possibly related to this recent fix in Strapi 4.20.1?
https://github.com/strapi/strapi/pull/19510

### Steps to reproduce the behavior

1. Have 2 localizations set up
2. Create an entity
3. Create a translation for the entity
4. Save the translated entity
5. Publish the translated entity

### Expected behavior

The entity is published

### Additional context

When creating a translation you end up on an URL like this:
http://localhost:1337/admin/content-manager/collection-types/api::page.page/create?plugins[i18n][locale]=sv&plugins[i18n][relatedEntityId]=4

When the new entity is saved you end up on an URL like this:
http://localhost:1337/admin/content-manager/collection-types/api::page.page/21?plugins[i18n][locale]=sv&plugins[i18n][relatedEntityId]=4

Publishing the entity from that URL generates an error (as describe above).

If you remove the `relatedEntityId` part of the URL (`&plugins[i18n][relatedEntityId]=4`) and trying to publish it does not give an error and the entity gets published.

There seems to be a validation check when publishing the entity that throws an error. Either this check should not be done when publishing the entity, or once you save the entity the `relatedEntityId` part should be removed from the URL.

**Comment by DavithkbY** [comment]
I have the same problem.

**Comment by jeystaats** [comment]
Occurs here as well. Can't seem to publish any other languages atm as that url that @iwap mentions breaks the `publish` functionality.

It does work when you remove the relatedEntity part of the query

**Comment by MAxiaq** [comment]
Same here with version 4.20.2

**Comment by Marc-Roig** [comment]
Hello! thank you for the report @iwap  we are working on a solution that will be release on 4.20.3 soon :)

**Comment by MAxiaq** [comment]
HI all, have you tested this out? I just updated strapi to 4.20.3 and now it will not even let me publish the default language nor the other locals. So from my testing it's a step backwards.

**Comment by VoltagePower** [comment]
@Marc-Roig 
The bug is fixed in the current version 4.20.3 for the collection-type, however for the single-type the bug still exist
Get
Warning: Not Found
