### ISSUE TITLE
Content Blocks does not work with smaller images

### ISSUE THREAD

**Issue by preist** [strapi/strapi#19521]
## Bug report

When uploading an image of around 100x100 pixels and adding it to Content Blocks editor, it fails to save – due to the fact that the image does not generate a thumbnail.

**System Information**

Environment: development
OS: darwin-arm64
Strapi Version: 4.20.0
Node/Yarn Version: npm/10.2.4 node/v21.6.1 darwin arm64 workspaces/false
Edition: Community
Database: mysql

### Describe the bug

It seems that the Slate editor is configured to expect an image thumbnail. When a thumbnail isn't present you can't save the article.

### Steps to reproduce the behavior

Use this test image:

![tiny_image](https://github.com/strapi/strapi/assets/14940633/929caf6a-114a-4937-a9e9-132da9ade2dc)

1. Open any content type that uses the Content Blocks editor
2. Upload any image of a size at around 100x100 pixels and add it to your Content Blocks rich text editor
3. Hit the save button
4. Note the error: `image.formats must be a `object` type, but the final value was: `null`.`

### Expected behavior

I expect to be able to add images that are small and be able to save.

### Screenshots

![2024-02-15 22 30 49](https://github.com/strapi/strapi/assets/14940633/e58598b9-d320-4eda-bd29-99adfd61dc47)

**Comment by dan-hu** [comment]
I'm having exactly the same problem

**Comment by tcmalcomb** [comment]
I'm able to reproduce this issue in v5.0.0

**Comment by tcmalcomb** [comment]
This also appears to be a duplicate of: RichText (Block) fails on save if an image is too small to have formats https://github.com/strapi/strapi/issues/19400

**Comment by preist** [comment]
Closing in favor of #19400
