### ISSUE TITLE
Cannot filter using "does not contain" operation on a relation

### ISSUE THREAD

**Issue by nbro10** [strapi/strapi#19532]
### Required System information

- Node.js version: v20.9.0
- NPM version: 10.1.0
- Strapi version: 4.20.1 or 4.17 (I suppose any version from 4.17 to 4.20.1)
- Database: PostgreSQL
- Operating system: Ubuntu and Mac
- Is your project Javascript or Typescript: JS

### Describe the bug

In Strapi 4.16.2, I could filter (in the Content Manager) a table using the `Does not contain (case insensitive)` operation for an attribute, which is a relation. In Strapi 4.20.1, I can no longer see this operation in the Strapi admin interface (in the Content Manager).

The API with the relation looks like this

```
{
  "kind": "collectionType",
  "collectionName": "users",
  "info": {
    "singularName": "user",
    "pluralName": "users",
    "displayName": "User",
    "name": "user",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
   // ... 
    "project": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::project.project"
    }
  }
}
```

So, clearly, the relation here is `project`. 

For completeness, the project API looks like this

```
{
  "kind": "collectionType",
  "collectionName": "projects",
  "info": {
    "singularName": "project",
    "pluralName": "projects",
    "displayName": "Project",
    "name": "project"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
  //...
```

So, clearly, the name attribute is a string and I should be able to filter using the "does not contain" operation.

I didn't change the API. I only updated Strapi to version 4.20.1 from version 4.16.2. 

I've just downgraded to version 4.17.0, where this bug already shows up, so it was introduced in version 4.17.0: https://github.com/strapi/strapi/releases/tag/v4.17.0

**Can you please solve this bug as soon as possible?**  

I'd highly recommend that you have tests for every UI feature (not just unit tests). It can't or shouldn't happen that I update to a minor version and my users lose the only feature that made me switch to version 4

### Expected behavior

I can filter with the `Does not contain`, `Contain`, `Does not contain (case insensitive)` and `Contains (case insensitive)` operations in the Strapi admin interface for relations.

### Screeshot

Just in case you don't believe me.

![Screenshot 2024-02-16 at 16 49 12](https://github.com/strapi/strapi/assets/106664639/9d0f07dc-82b8-4fdc-ae3f-3939a0dfbc55)

### Additional info

Would it also be possible to add the "does not start" and "does not end" operations (both case-sensitive and case-insensitive versions)? We have the "starts with" and "ends with" and we have the negations for all other operations but these.

**Comment by derrickmehaffy** [comment]
Closing as should be fixed by https://github.com/strapi/strapi/pull/19970 to be released in 4.22.1
