### ISSUE TITLE
Audit log filter by user not working

### ISSUE THREAD

**Issue by dennism501** [strapi/strapi#19539]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.15.0, 4.16.2
- Database: SQLite
- Operating system: Mac OS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When a user tries to filter the Audit logs by the user option, the option is not clickable and there is an error is displaying the console (see screenshot attached). 

### Steps to reproduce the behavior

1. Go to the Audit logs in the settings page
2. Click on the Filter button
3. Then select the `User` option

### Expected behavior

This action should Filter the logs by user.

### Screenshots

![image](https://github.com/strapi/strapi/assets/15628660/71005779-7b06-462f-800d-c11f31a60c11)

### Code snippets

N/A.

### Additional context

N/A.

**Comment by dennism501** [comment]
Internal TID: 6009

**Comment by simotae14** [comment]
Hello @dennism501 , I am gonna close this issue because it is fixed since v 4.17, thanks
