### ISSUE TITLE
How to deploy modified Strapi admin - help please!

### ISSUE THREAD

**Issue by sbastias** [strapi/strapi#1954]
**Informations**
- node v10.6.0
- npm v6.1.0
- Strapi v3.0.0-alpha.14
- MongoDB
- Ubuntu 14.04

This is my process:
- Cloned strapi@3.0.0-alpha.14
- > npm run setup
- created new dev app 
- > strapi new cms-dev --dev
- worked in development mode to alter:
-- strapi-plugin-content-manager
-- strapi-plugin-content-type-manager
-- strapi-admin
-- strapi-upload-local

At this point I have Strapi customized and working locally on port 4000!

Next, in Strapi monorepo
> npm run setup:build

And created a new project:
> strapi new cms-project

But all my customizations are gone. In fact, the plugins are all the most recent versions!

What am I doing wrong? Please help!

**Comment by lauriejim** [comment]
Hello @sbastias you have to stay in you `dev` app and run `npm run setup --plugins` to rebuild admin part.
Then there is still symlink in your app, we will have to remove it.
So you will have to copy `strapi-admin` from your mono repo to you app and rename `strapi-admin` to `admin`
And to the same for `strapi-plugins-***` you use in you app. Copy from mono repo to the plugin folder of your app and rename it.

Then push all your app to your server.

**Comment by sbastias** [comment]
THANK YOU.

**Comment by betomoretti** [comment]
Hi @sbastias, How is the final process to do it? I'm trying the same but without success. Thanks!

**Comment by sbastias** [comment]
I'm so sorry I was slow on this - but I just launched yesterday, and this is the process:

@betomoretti Here's what I ended up doing

**Development**
* Cloned the repo from http://github.com/strapi/strapi
* Inside clone (this is the _"monorepo"_)  `monorepo> npm run setup`
* Then I initiated a new DEV project `mypath> strapi start strapiproject --dev`
* In 2 separate consoles, you need to run the strapi application and the admin separately:
  * `mypath/strapiproject> strapi start` to run strapi
  * `mypath/strapiproject/admin> npm run start` to run admin interface in dev mode

At this point, you should be able to access your project admin interface at **localhost:4000**

Then I made customizations to:
* monorepo/packages/strapi-plugin-content-manager
* monorepo/packages/strapi-plugin-content-type-builder
* monorepo/packages/strapi-upload-local

**To use my customized strapi monorepo:**
* I started a new project: `mypath> strapi new realproject`
* I built the admin: `mypath/realproject> npm run setup`
* I _replaced_ the plugins I customized with the monorepo versions
* I built the plugins: `mypath/realproject> npm run setup --plugins`

And then I ran the new straps admin!
`mypath/realproject> strapi start`

Everything seems to be working now (with strapi-plugin-grarphql **v3.0.0-alpha.13** because of [this bug](https://github.com/strapi/strapi/issues/1911))
