### ISSUE TITLE
Single Type (i18n) deletes first entry only

### ISSUE THREAD

**Issue by Eventyret** [strapi/strapi#19559]
### Required System information

- Node.js version: 18.18.2 / 20.11.1
- NPM version: npm 10.2.4 / yarn 1.22.19
- Strapi version: 4.20.1
- Database: sqlite
- Operating system: MacOS Sonoma
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When using i18n for a single page it will always default to delete the default locale entry.
So if you have a `Single Type` with 3 languages, you delete any of them it will always delete the default one.

### Steps to reproduce the behavior

1. Create a strapi project `npx create-strapi-app@latest i18n-bug`
2. Create multiple locale's (in this test we have english, french, Northen Kurdish _note: the language doesn't matter_ but we are setting **english to default.**

3. Create a `Single Type`
4. Create a field any field is fine

5. Use the `Content Manager` and create some content, for for each language.
6. **Delete** a non-default language
7. It has now deleted the default language, and swapping back to the one you deleted that one already exists.

### Expected behavior

It should delete the correct locale entry, and not the default one.

### Screenshots

![image](https://github.com/strapi/strapi/assets/977232/12b162b3-a4c7-4439-b055-015797c1e598)
![image](https://github.com/strapi/strapi/assets/977232/4d880697-b4a1-438f-8a37-f7ab81d39884)
VIDEO: https://github.com/strapi/strapi/assets/977232/7e9e7b81-3e36-4dc9-a43d-3ba57cc8b254

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Eventyret** [comment]
Raised to medium EE customer effected - Internal ID: 6032

**Comment by derrickmehaffy** [comment]
Raised from Medium -> High due to escalation (was never low because there was no workaround to be considered low)
