### ISSUE TITLE
Generated API controller.action conflict with plugins controller.action in routes files

### ISSUE THREAD

**Issue by NikhilNanjappa** [strapi/strapi#1955]
**Informations**
- **Node.js version**: `10.4.0` (replicable in `8.9.4` and `9.9.0`)
- **npm version**: `6.2.0` (also used `5.6.0`)
- **Strapi version**: `3.0.0-alpha.14`
- **Database**: MongoDB
- **Operating system**: macOS Sierra

**What is the current behavior?**
Hitting the `/email` API calls the `send` action in `plugins/email/controllers/Email.js` rather than its own controller within `api/email/controllers/Email.js`.

**Steps to reproduce the problem**
Create an email API using `strapi generate:api email`. Then, edit the newly generated `routes.json` to target a `send` action within its controller. 

```
{
  "routes": [
    {
      "method": "POST",
      "path": "/email",
      "handler": "Email.send",
      "config": {
        "policies": []
      }
    }
  ]
}
```
Now create a new `send` action within `api/email/controllers/Email.js`. 
```
// within 'api/email/controllers/Email.js'
module.exports = {
  send: async (ctx) => {
    console.log("This is not called")
  }
}
```
Any code within this action will not be called rather the call goes directly to the `send` action in  `plugins/email/controllers/Email.js` even though we have explicitly specified in the `routes.json` to make use of `send` within the controller of that specific API.

**What is the expected behavior?**
As the `routes.json` is specified to call the `send` action within its own controller, the call should be going to `send` in `api/email/controllers/Email.js`.

**Suggested solutions**
No suggested solutions.

**Comment by lauriejim** [comment]
There is a conflict with Email plugins controller `Email.send` and your generated API with `Email.send`.

**Comment by lauriejim** [comment]
@alexandrebodin Can you confirm this issue will be resolved with the new architecture we are working on.

**Comment by alexandrebodin** [comment]
@NikhilNanjappa @lauriejim 

This behaviour is intended and won't be changed in the next release. If you want to change the plugin's route you should overwritte it or create a custom route (other path) rather than creating the same new route.
