### ISSUE TITLE
Broken images in Media Library

### ISSUE THREAD

**Issue by leyla-mammadova** [strapi/strapi#19569]
I copied images from the PROD CMS public/uploads folder and PROD CMS DB to the DEV environment. Now, the images are broken. But if I upload images through the admin panel, then the images work well.
Also from my Next.js project I can’t access these images. The links to the images show a 404 error.

MySQL:
Node 16:
Strapi 4:
Next JS:

![image](https://github.com/strapi/strapi/assets/107697241/1c622989-23cd-4219-ad25-4923c7146cf3)

**Comment by lauriejim** [comment]
Hello 👋

I answered you on Stackoverflow: https://stackoverflow.com/questions/78026683/broken-images-in-strapi-media-library
