### ISSUE TITLE
Themes for Admin Panel

### ISSUE THREAD

**Issue by NikhilNanjappa** [strapi/strapi#1956]
**What is the expected behavior?**
A user should be able to customize the UI of the Admin Panel easily. As part of this feature, a user could provide his/her own logo, UI Panel colors etc.

**Comment by Aurelsicoko** [comment]
Totally agree with this! This is a feature we will provide in the future. I can't give you a date though...

**Comment by lauriejim** [comment]
I close this feature request - please ref to this item in the Roadmap https://portal.productboard.com/strapi/c/11-administration-user-interface
