### ISSUE TITLE
Load More not showing up in relation field in production 🐛

### ISSUE THREAD

**Issue by sehrish30** [strapi/strapi#19570]
### Required System information

- Node.js version: 18
- NPM version: 9.81
- Strapi version: 14.19.1
- Database: mysql
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I cannot see "Load more" button on select option in my collection when multiple items selected

### Steps to reproduce the behavior

1. Go to 'any collection'
2. Click on 'relation field'
3. Select more than 5 options

### Expected behavior

Expected "Load More" on reload to load other options, works in development but in production

### Screenshots

In development 
<img width="236" alt="image" src="https://github.com/strapi/strapi/assets/66527974/ccdefb33-bfc0-4e4b-9b98-c2d156407a0e">

In production(wrong count and missing "Load More")
<img width="265" alt="image" src="https://github.com/strapi/strapi/assets/66527974/b947c931-654f-4d8e-a2e5-16142cd45994">

**Comment by kubarazny** [comment]
any update?

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/19625
