### ISSUE TITLE
[@strapi/plugin-i18n] NOT Working?

### ISSUE THREAD

**Issue by JakiChen** [strapi/strapi#19598]
### Required System information

- Node.js version: v20.10.0
- NPM version: 10.2.3
- Strapi version: v4.20.2
- Database: sqlite? (default)
- Operating system: macOS Big Sur (v11.7.10)
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Unable to enable **i18n** functionality even though I added the target language in the International plugin settings panel.

### Steps to reproduce the behavior

1. Created the project via `npx create-strapi-app@latest my-project` command.
2. Settings→Internationalization→Add Locale
3.  Content-type Builder→create a new collection type （For example create a post but I can't see the `Locales` option on the Infromation sidebar.
4. Edit the fields → edit → advanced setting →enable/disable Localization. （There is no such option）

### Expected behavior

I'm a newbie and I'm not sure if I have configured it correctly step by step.

I even added the `STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE=en` configuration in the `.env` file.

I'm really eager to take advantage of the capabilities of the i18n plugin (but can't seem to see the results I expect in the cms I build from the reference).

**_I look forward to getting immediate feedback and help from the team, thank you very much._**

### Screenshots

![localhost_1337_admin_settings_internationalization(1100x825)](https://github.com/strapi/strapi/assets/3423524/2bfc55c8-29b0-4596-a019-abcf26a5e2e9)
![localhost_1337_admin_settings_internationalization(1100x825) (1)](https://github.com/strapi/strapi/assets/3423524/9e1f25a9-fb42-4879-883c-afddefba2362)
![localhost_1337_admin_settings_internationalization(1100x825) (2)](https://github.com/strapi/strapi/assets/3423524/8eb4048b-ddc5-4e6f-8a40-f5b83ad29c36)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by JakiChen** [comment]
##  The bug may be solved by type conversion

But it is not the best solution) and it is impossible to predict whether there are still potential problems.

### It works on `SINGLE TYPES`?

![localhost_1337_admin_content-manager_single-types_api__index index_plugins i18n locale =en(1100x825)](https://github.com/strapi/strapi/assets/3423524/8d81f6c4-5653-40a4-9be0-f3a4bd07df1b)

### **_So converting "single" to "collection" will solve this unknown error?_**
![localhost_1337_admin_content-manager_single-types_api__index index_plugins i18n locale =en(1100x825) (1)](https://github.com/strapi/strapi/assets/3423524/568adfe7-73e8-4972-b18f-c7f45e4139d4)

### Please forgive me if I'm intrusive.

I'm not good at strapi development, and I don't know if there is any advanced way to customize rest-api.

Currently I am learning and referring to the code of the official strapi+astro blog (see how the official obtains data).

Unfortunately, there are no official (blog/enterprise website) related cases of i18n yet (and how to store astro form data into your own database through strapi).

**Comment by JakiChen** [comment]
## There should be an unexplained **BUG**
Everything seems to be working fine with CMS Front-End in the old version 4.16.2

### Enable i18n adaptation
![23](https://github.com/strapi/strapi/assets/3423524/05d35f23-940d-4774-907d-3f30b0949315)

### Unable to publish (unknown reason)
![2](https://github.com/strapi/strapi/assets/3423524/6d025c37-c583-4978-b9d2-e8893cd2757b)

**Comment by alexandrebodin** [comment]
Hello, 

This was fix in the latest release
