### ISSUE TITLE
Support for .native on models?

### ISSUE THREAD

**Issue by gkweb** [strapi/strapi#196]
**Node.js version**:4.8.0
**npm version**: 2.15.11
**Strapi version**: 1.5.5
**Operating system**: Mac Os Sierra

Hello, I am creating a web app that requires the use of MongoDB geospatial fields.This requires the use of `modelName.native()`. When running through sails guides for implementing people are saying to follow this solution:
[Geospatial example in Sails.js using native MongoDB query](
https://gist.github.com/PascalAnimateur/b73617f0a27475fd4ccb)

Can someone breakdown the differences to implement such a thing in Strapi 1.5.x I have tried adding this to the boostrap.js file but the .native function is **undefined**. Also would be great to know if mongo geospatial field support will be available in strapi 3? See below:

### bootstrap.js
```
module.exports.bootstrap = function (cb) {
  const fixtures = require('../../api/user/config/fixtures/index');

  fixtures.role.create()
    .then(function () {
      return fixtures.route.create();
    })
    .then(function () {
      console.log(strapi.models.location.native)
      // logs as undefined
      cb();
    })
    .catch(function (err) {
      strapi.log.error(err);
      cb(err);
    });
};
```

### Mongo adapter defined in databases.json.
(credentials omitted)
```

{
  "orm": {
    "adapters": {
      "disk": "sails-disk",
      "mongo": "sails-mongo"
    },
    "defaultConnection": "localMongo",
    "connections": {
      "default": {
        "adapter": "disk",
        "filePath": ".tmp/",
        "fileName": "default.db",
        "migrate": "alter"
      },
      "localMongo": {
        "adapter": "mongo",
        "host": "localhost",
        "port": 27017,
        "user": "user",
        "password": "publicpasswordforalltosee",
        "database": "somedatabase"
      },
      "permanent": {
        "adapter": "disk",
        "filePath": "./data/",
        "fileName": "permanent.db",
        "migrate": "alter"
      }
    }
  }
}

```

Much respect and thank you

**Comment by Aurelsicoko** [comment]
@gkweb Sorry for the delay... Did you take a look at the `strapi.adapters.mongo` object to check if the `native` method is exposed or not? 

Reference: https://github.com/strapi/strapi/blob/v1.5.5/lib/configuration/hooks/waterline/index.js#L76

**Comment by gkweb** [comment]
This has solved my initial problem, but I've moved to an express / mongoose stack until Strapi has matured more. Thanks
