### ISSUE TITLE
Custom indexes removed from schema.json after adding new field via Content Type Builder

### ISSUE THREAD

**Issue by ilnytskyi** [strapi/strapi#19609]
### Required System information

- Node.js version: 20.+
- NPM version:
- Strapi version: 4.20.2
- Database: sqlite
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

1. Add custom index into schema.json
2. Restart server, see index
![image](https://github.com/strapi/strapi/assets/3192770/ebd15c0f-647f-4d01-9cc8-44ccd9321b12)

3. Edit content type via content type builder, e.g. add new field
4. After restarting the server, custom indexes removed from both schema.json and database

Before editing:
![Selection_20240226_016](https://github.com/strapi/strapi/assets/3192770/e5f6c803-565a-4d88-8459-c3c218379b67)
![image](https://github.com/strapi/strapi/assets/3192770/ebd15c0f-647f-4d01-9cc8-44ccd9321b12)

After editing:
![image](https://github.com/strapi/strapi/assets/3192770/6616da37-cfab-4dd4-a58b-015009af3f57)
![image](https://github.com/strapi/strapi/assets/3192770/ee6edf4a-3945-4abc-a920-1b2147a3e931)

### Expected behavior

- Custom indexes are persistent when in schema.json when editing content type via admin
- Indexes are edited or removed only when corresponding fields are removed

### Screenshots

Above

### Code snippets

schema.json

```
{
  "kind": "collectionType",
  "collectionName": "address_coordinates",
  "info": {
    "singularName": "address-coordinate",
    "pluralName": "address-coordinates",
    "displayName": "Address Coordinates",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "address": {
      "type": "string",
      "unique": true
    },
    "lat": {
      "type": "float",
      "required": true
    },
    "lon": {
      "type": "float",
      "required": true
    },
    "details": {
      "type": "json"
    },
    "province": {
      "type": "integer"
    }
  },
  "indexes": [
    {
      "name": "address_coordinates_address_index",
      "columns": [
        "address"
      ],
      "unique": false
    }
  ]
}
```

**Comment by ztxone** [comment]
try to guess... if you add some fields directly to the database and then editing them in admin ui - your database will be cleared after editing through admin ui.
This is because the source of truth is schema.json files and when you adding some stuff directly to database - it will be removed from db if it not the same as in the schema.json
mb it helps in your case

**Comment by ilnytskyi** [comment]
@ztxone 

> This is because the source of truth is schema.json files and when you adding some stuff directly to database - it will be removed from db if it not the same as in the schema.json
mb it helps in your case

To be clear: after editing content type in Admin, e.g. adding new field, the indexes section got removed form schema.json along with indexes from the database, that is not expected to behavior.

It seems more like content type model to schema.json conversion issue. schema.json supports indexes but, content type model not, except for slug-type field as unique index.

**Comment by derrickmehaffy** [comment]
> @ztxone 
> 
> > This is because the source of truth is schema.json files and when you adding some stuff directly to database - it will be removed from db if it not the same as in the schema.json
> mb it helps in your case
> 
> To be clear: after editing content type in Admin, e.g. adding new field, the indexes section got removed form schema.json along with indexes from the database, that is not expected to behavior.
> 
> It seems more like content type model to schema.json conversion issue. schema.json supports indexes but, content type model not, except for slug-type field as unique index.

Schema.js does not support indexes currently: https://feedback.strapi.io/developer-experience/p/custom-indexes-in-the-schema
