### ISSUE TITLE
"hour" field in DatePicker of content manager decrease by 7 

### ISSUE THREAD

**Issue by hinsxd** [strapi/strapi#1960]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: postgres v10.5
- **Operating system**: macOS High Sierra

**What is the current behavior?**
When using content-manager to Edit/Add entries with fields of `date` type, either up or down arrow of the `hour` will cause the value `hour` to decrease by 7 on releasing mouse button.

**Steps to reproduce the problem**
Add a Content Type with a field of type `date`. Then edit or add entries in Content Manager

**What is the expected behavior?**
Function normally as a time picker should.

**Suggested solutions**

**Comment by Tonours** [comment]
@hinsxd @soupette it seems that this is due to UTC format which is lost when we re-format date value passed to redux action `changeData`.

**Comment by j-rewerts** [comment]
It also seems like the text field can't be edited directly. I can take a look at this.

**Comment by kameas** [comment]
same problem, but i have decrease by 3 (GMT+0300)

**Comment by abdonrd** [comment]
Yes! I have the same problem!

**Comment by derekshull** [comment]
Same issue here too.  Glad I'm not crazy :-D

**Comment by derrickmehaffy** [comment]
Yeah can confirm, I believe they are working on replacing that date picker

**Comment by fabricioanciaes** [comment]
These are the problems I've found for the date picker, hope it helps:

#### Problem 1:
After saving, the hour decreases by 3:

This is what I set on the admin:
![https://i.imgur.com/dgzNEBo.png](https://i.imgur.com/dgzNEBo.png)

This is what it looks like after saving:
![https://i.imgur.com/OafsSB9.png](https://i.imgur.com/OafsSB9.png)

#### Problem 2:
Date picker only increases by 4 and decreases by 2, but decreasing actually increases the hour:
![https://i.imgur.com/DyGWlA0.gif](https://i.imgur.com/DyGWlA0.gif)

#### Problem 3:
Not being able to edit date directly by text:
![https://i.imgur.com/VIMXRRw.gif](https://i.imgur.com/VIMXRRw.gif)

**Comment by lauriejim** [comment]
Thank you @fabricioanciaes for these details.

**Comment by thkdog** [comment]
Is there any alternative solutions for now? It seems be a critical problem...

**Comment by lauriejim** [comment]
We are working on a new input (component library) for the date and will be release soon and implemented in this plugin.

We will give you more informations when time will come. (big things are coming)

**Comment by thkdog** [comment]
Sounds amazing! Just to make sure the new component is a pure web side improvement, fully compatible with the current db structure so I can merge it into current version out of box :D

在 2019年1月17日，02:22，Jim LAURIE <notifications@github.com<mailto:notifications@github.com>> 写道：


We are working on a new input (component library) for the date and will be release soon and implemented in this plugin.

We will give you more informations when time will come. (big things are coming)

**Comment by aaronweatherall** [comment]
Also stuck on this one team! Dates are probably the thing stopping me deploying right now.
