### ISSUE TITLE
"Save" button still active after saving

### ISSUE THREAD

**Issue by ztxone** [strapi/strapi#19603]
### Required System information

Node.js version: node v18.19.0
NPM version: yarn -v 1.22.19, npm -v 10.2.3
Strapi version: 4.20.2 Community
Database: sqlite
Operating system: macOs Sonoma 14.2.1
Is your project Javascript or Typescript: ts

### Describe the bug

Admin Ui lives separate of background stuff... "Save" button still active after saving and goes make errors...

### Steps to reproduce the behavior

Watch screencast

### Expected behavior

"Save" button should be disabled after saving changes

### Screenshots

https://github.com/strapi/strapi/assets/39146381/be5d023d-8d84-47dc-a42c-e913795d6868

**Comment by jkefc** [comment]
Hey, I'm a backend developer, not exactly experienced with FE frameworks... but Is it possible you have a custom plugin or doing any data manipulation in the content lifecycle functions like beforeUpdate? 
Some plugins, if the state handling of the react part of the plugin is not implemented correctly, or there is a plugin state change that happens after the update (for examplee you use ckeditor for rich content, and manipulate the html in your lifecycle functions, then after save, all fields are re-rendered, and if ckeditor is seeing a change in content, will try to reformat it, and if it succeeds, it will signal a state change to Strapi, and that in turn will enable the save button). Been there with a few cases like that :)

**Comment by ztxone** [comment]
If it is question to me - IDK ))
This behaviour exists in fresh install strapi after "create-strapi-app@latest my-project --quickstart" command
I believe that i was facing sometimes same thing in more mature builds of strapi, but in this case it's clean version without any additional plugins or whatever...

**Comment by tofikwest** [comment]
> ztxone
I'll check this problem as well

P.S what is your font family in vscode and font size?)

**Comment by ztxone** [comment]
> P.S what is your font family in vscode and font size?)

![Screenshot 2024-02-26 at 22 34 43](https://github.com/strapi/strapi/assets/39146381/1a7c29d1-c6cd-4f72-9100-653018f96e19)

**Comment by hanpaine** [comment]
Believed to be fixed by #19811
