### ISSUE TITLE
Localizations field does not show in the API to take the translated posts

### ISSUE THREAD

**Issue by Ada-Bardho** [strapi/strapi#19613]
### Required System information

- Node.js version: v18
- NPM version: v18
- Strapi version: 4.20.2
- Database: PostgreSQL
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug
Hello, we've faced an issue we can't resolve.
We have 4 languages in our website and we want to make slugs for our collection type posts unique for every language so that we can translate them based on the article title in different languages. The problem is that we can't redirect between languages on these pages on our website, because data which is sent to frontend doesn't include slugs for related posts in other languages. However, when the post is opened in strapi in Network/Preview we can see localizations field which includes information we need but we can't access it in frontend.
Our backend developer suggested that we probably don't have support for that data or don't use specific plugin for that. Could you help us with that and provide a solution for getting localizations field and its data?

1. Go to '...' A Strapi Instalation where you can create a collection type Post with these fields:

 ![image](https://github.com/strapi/strapi/assets/103948223/ef0dcb51-659f-4cfa-8c26-35e98f0daa55)

2. Make sure you can translate this collection type with localization, I have done it with these five languages: 
![image](https://github.com/strapi/strapi/assets/103948223/2f3004f3-4f7c-4589-ad29-a53f70267fdb)

3. And as we can see here in Strapi we see the translated posts with data: 
![image](https://github.com/strapi/strapi/assets/103948223/371430f4-f216-4f25-8a0c-222f3ca5b2fd)

5. But when we try to get them by an API call we can't see the data. https://web.postman.co/workspace/My-Workspace~e86b59d0-66c4-4205-84af-38f2c8029024/request/33363688-c06fbba9-0c4c-4eb6-a150-66e449fc04e7?tab=auth.
![image (1)](https://github.com/strapi/strapi/assets/103948223/14e89fae-b0f4-4e8b-a7e4-8361d5941945)

7. How can we populate these data ?
8. Scroll down to '....'
9. See error

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by kasonde** [comment]
There's a possible customization somewhere in your Strapi codebase. Either in the `posts` controller or a middleware of some sort. Ideally no API request made to Strapi will ever populate relations and media without specifying that in the API request. Currently your API request only asks for `localizations` but other relations are populated as well.
