### ISSUE TITLE
Missing some features visibility on Strapi Cloud

### ISSUE THREAD

**Issue by kibwashere** [strapi/strapi#19619]
### Required System information

- Node.js version: 20.11.1
- Strapi version: 4.20.2

### Describe the bug

Review Workflows, Single Sign-On and Audit Logs menus are not visible in the Settings panel (screenshot 1) with the following setup:
- Strapi Cloud `Developer` plan (certainly the same for `Pro` and `Team` plans - depending if the features are enabled or not)
- EE plan (all Cloud projects are EE plans by default)

(cc @simotae14)

### Steps to reproduce the behavior

1. Create a v4.20.2 Strapi Cloud `Developer` project
2. Wait for the build and deployment
3. Open the app and go in the `Settings` page.
4. The features listed above are not visible

### Expected behavior

- I understand these features are not included in the `Developer` plan, but locally I can see them with a "locked" icon (screenshot 2) - which is not the case when using Strapi Cloud); please note that the `Releases` feature seems to have the good behavior
- Also, I believe the wording `Review Workflows is only available as part of the Enterprise Edition. Upgrade to create and manage workflows.` (screenshot 3) - needs to be changed since Cloud projects are all EE, but features depend of Cloud plans (and not CE/EE)

### Screenshots

Not visible (using Strapi Cloud and with an EE plan):
<img width="1492" alt="image" src="https://github.com/strapi/strapi/assets/3426213/e83961fc-8f70-4872-9354-e0d0ec4c6ccc">

Visible (locally or with an CE plan):
<img width="1481" alt="image" src="https://github.com/strapi/strapi/assets/3426213/7fc3b2f2-4734-4821-801a-1371fa10af5d">

Locked feature:
<img width="1485" alt="image" src="https://github.com/strapi/strapi/assets/3426213/18d81dec-b082-4aee-ad1e-d615eec1a0b8">

**Comment by Eventyret** [comment]
For cloud issues, please use the feedback / help widget under the cloud panel for assistance.

**Comment by simotae14** [comment]
Hello @kibwashere , the fix is already been merged https://github.com/strapi/strapi/pull/19855, and it is part of 4.21.1 release, thank you
