### ISSUE TITLE
How to add line breaks or apply grouping for Strapi collection's Create and update page.

### ISSUE THREAD

**Issue by mukesh-thakur-dy** [strapi/strapi#19616]
### Required System information
- Node.js version: **18.18.2**
- NPM version: **9.8.1**
- YARN version: **1.22.19**
- Strapi version: **4.19.0**
- Database: **MySql**
- Operating system: **Ubuntu**
- Is your project Javascript or Typescript: **Javascript** 

### Describe the bug
I cannot add line breaks or grouping the form fields in the Create or Update collection page.

I want to add a line break or  Grouping as per below image.
![image](https://github.com/strapi/strapi/assets/148182953/c085c78d-d8bc-4621-b66b-bcb28090984f)

Please provide any solution to add a line inside the add and edit page or arrange the field in the group.

**Comment by AnkitGujaria1018** [comment]
I need this functionality for a good user experience. Please provide a solution.
