### ISSUE TITLE
Gitlab webhook integration

### ISSUE THREAD

**Issue by heihachi88** [strapi/strapi#1962]
**What is the expected behavior?**
Integration with Gitlab webhook, so when we push to our repository, then it automatically being pulled from the repository

**Comment by derrickmehaffy** [comment]
@heihachi88 I think this is something environment specific depending on how the application is being run. I don't think this is something that strapi can do itself, there are many other factors at play such as updating node modules, dependants, ect.

My suggestion to you would to be to use some kind of CI/CD system to automate deployment, maybe using something like docker.

**Comment by heihachi88** [comment]
What do you use yourself? With docker you still need to rebuild the image after each push.

**Comment by derrickmehaffy** [comment]
@heihachi88 my process is a bit more complex due to my environment. With Github I have TravisCI doing some basic testing, and a homebrew script running to build and deploy the build to multiple servers for load balancing.

But you can use many different CI/CD to rebuild the docker build.

**Comment by heihachi88** [comment]
Basically, i can just create my own route (that would fire `git pull`) and point gitlab webhook to it. Is that correct way?

**Comment by derrickmehaffy** [comment]
Not how I would recommend that, especially when the strapi version changes, you would need to reinstall the new modules which can't be done while strapi is running.
