### ISSUE TITLE
Lack of providers when using the plugin:build command

### ISSUE THREAD

**Issue by boazpoolman** [strapi/strapi#19634]
### Required System information

- Node.js version: v18.18.2
- NPM version: 9.8.1
- Strapi version: 4.19.0
- Database: Postgres
- Operating system: MacOs
- Is your project Javascript or Typescript: Typescript

### Describe the bug

_I've started expirimenting with the new `plugin:build` and `plugin:watch` commands as a potential alternative build strategy for one of my plugins when ran into this issue._

_I know the new plugin CLI is expirimental, though I still figured it could be helpful to submit this issue here._

Basicly the issue I'm facing is that all of a sudden I'm getting error's about missing providers. Though before using the new plugin commands I had no issues with this.

One of the error's is:

```
No QueryClient set, use QueryClientProvider to set one
```

The place this originates at is from a page that is registered using the `createSettingsSection` api in the main admin index.js file. [See example](https://github.com/pluginpal/strapi-webtools/blob/master/packages/core/admin/index.ts#L69-L84).

That will register [this page](https://github.com/pluginpal/strapi-webtools/blob/master/packages/core/admin/screens/Patterns/index.tsx) for me which uses the `CheckPagePermissions` component which indeed needs a `QueryClientProvider`.

I'm wondering if I should just add the provider myself, or if this is a bug with the new plugin commands.

The same happends for the `react-router` `Switch` and `Route` components. They also require a provider and will throw an error because of it.

### Steps to reproduce the behavior

1. Create a simple plugin
2. Create a page using the `createSettingsSection` api
3. In that page use the `CheckPagePermissions` component
4. Build the plugin with the `strapi plugin:build` command
5. Install the plugin in a Strapi instance
6. Witness the issue

### Expected behavior

I will have no errors about missing providers and the plugin will work just like it would before I started using the plugin:build command.

**Comment by joshuaellis** [comment]
We have plugins that use these commands and do what you're saying and do not face this issue. Can you provide an example repo please?

**Comment by boazpoolman** [comment]
Allright,
I've pushed a branch to our `strapi-webtools` repo in which you can witness the issue.
https://github.com/pluginpal/strapi-webtools/tree/feature/updated-build-strategy

Please follow the contributing guidelines to get started with the repo.
https://github.com/pluginpal/strapi-webtools/blob/feature/updated-build-strategy/CONTRIBUTING.md

Then if you strart the playground with `--watch-admin` and navigate to `http://localhost:1337/admin/settings/webtools/patterns` you'll see the following error:

![Scherm­afbeelding 2024-02-29 om 09 20 01](https://github.com/strapi/strapi/assets/9551934/aa606fcd-30ff-446f-b597-dc718b23f920)

**Comment by joshuaellis** [comment]
Looking at your package, you don't declare any of the dependencies you use, so it won't know they're external and bundle them – this is probably causing these issues. IMO i would declare all your dependencies & go from there, from V5 we won't be aliasing any dependencies anyway, so plugins have more control over what dependency version they're using :)

**Comment by boazpoolman** [comment]
Ah, that's interesting.
Let me try that later today and I'll report back.

**Comment by boazpoolman** [comment]
You were right, the issue lies within the dependency management.

So in this example I'm using the `<CheckPagePermissions />` component from `@strapi/helper-plugin`.
By adding `@strapi/helper-plugin` as a dependency (which has `react-query` as a dependency) it will solve the error I showed in my screenshot.

Note that I have to explicitly add this as a **dependency**, either `devDependency` or `peerDependency` won't work.

I might not be seeing the bigger picture here, but I kinda liked that these kind of dependencies we're just inferred.
I just put `@strapi/strapi` as a peerDependency and I can be sure to use `@strapi/helper-plugin` as it will be there, when using Strapi.

By explicitly declaring these dependencies I feel like you're bound to end up with multiple versions of `@strapi/helper-plugin` in your Strapi project, right?

**Comment by joshuaellis** [comment]
Yes, you'll technically have multiple versions. But it means we can upgrade our packages without breaking the plugin ecosystem etc. 

We can also release a breaking change of the design system too.

**Comment by boazpoolman** [comment]
Also, I noticed using the `watch` command can be very slow. Is this normal?
Sometimes I'm waiting 5 seconds for the watch command to finish, and after that Strapi itself has to re-compile as well 😅

**Comment by joshuaellis** [comment]
It depends how you have your app set up. For example, if you have aliasing for the FE it's quite quick. But the downside is we don't have hot reloading for the node application, so yeah it can take some time.

I would look at using out vite bundler with the watch-admin flag, it's the quickest way to develop the FE.

**Comment by boazpoolman** [comment]
Yeah, using the vite bundler is probably the best way to go.
Though that bundler is still waiting for the `plugin:watch` command to finish before it starts compiling, right?

How can I setup aliasing for the FE? 🤓

**Comment by joshuaellis** [comment]
> How can I setup aliasing for the FE? 🤓

you'll need to make a vite config see https://docs.strapi.io/dev-docs/admin-panel-customization#vite and in the example it shows you how to make an alias, you can do the same for packages if you use the same name :)

**Comment by boazpoolman** [comment]
Ah that's interesting!

If I use aliasing this way, do I still need to run the `plugin:watch` command during development?

**Comment by joshuaellis** [comment]
If you alias to the source code then no you don't, but it won't work for server code. We do this in the FE for the monorepo already: https://github.com/strapi/strapi/blob/chore/helper-plugin-components/packages/core/strapi/src/node/core/aliases.ts#L12

**Comment by boazpoolman** [comment]
Allright, so I've fiddled a bit with the dependencies and was able to make it work AS LONG as do not use `--bunlder=vite` for compiling Strapi.

If I use `strapi develop --bunlder=vite` the I still get this error, eventough the correct dependencies are in the package.json

<img width="804" alt="Scherm­afbeelding 2024-03-03 om 16 48 49" src="https://github.com/strapi/strapi/assets/9551934/141fd2ee-57b9-474d-95fb-dcc9b0aadb7b">

**Comment by boazpoolman** [comment]
Just an FYI, I still have this issue :)
