### ISSUE TITLE
No error UI Notification after installed axios

### ISSUE THREAD

**Issue by schtiewen** [strapi/strapi#19646]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 4.20.1
Node/Yarn Version: npm/10.2.4 node/v20.6.1 darwin arm64 workspaces/false
Edition: Community
Database: sqlite

### Describe the bug

i've created a fresh strapi projekt with a test collection

`{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "singularName": "test",
    "pluralName": "tests",
    "displayName": "test",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "aa": {
      "type": "string",
      "unique": true
    }
  }
}
`
i added a new entry. if i create a new entry with the same content, i get the error message.
Then, i installed axios (1.6.7). i did the same agin (created a new entry with the same content). no error message is visible.
I see only the http response, that an error is there, but not visible ui notification.

it looks like, that after the axios installation, all ui notification triggered by the http response are disabled.
(i tested it also with a hook "before create" and throwed an exception)

### Steps to reproduce the behavior

- create a nerw strapi instance
- create a new collection with an unique field
- create an entity
- create a second entity the the same content
- i should see the notification

### Expected behavior

after i installed axios, i should see the same error message like before.

**Comment by joshuaellis** [comment]
does still happen if you build the admin panel with `--bundler=vite`? I think its probably because we alias dependencies with webpack in v4.

**Comment by schtiewen** [comment]
Hi, with the options `--bundler=vite` it works. but how could i fixed this without the vite bundler?

**Comment by joshuaellis** [comment]
That's good to know, you could probably edit the webpack config to not alias the `axios` dependency – https://docs.strapi.io/dev-docs/admin-panel-customization#webpack
