### ISSUE TITLE
Add a Create Button in relation DropDown in the admin of content types

### ISSUE THREAD

**Issue by marcellovetro** [strapi/strapi#1965]
**What is the expected behavior?**
In Content Type Administration may be very usefull have a button or link to create directly a related element. 
The button should work only in editing because the actual record have to be existing.
When the user click on the create button of the relation I'm expected that:
1. The current form will be saved 
2. It jump to the related content type in creation
3. the relation is auto filled with the source record and is locked
4. after creation it redirect to the source record

In Content Manager Plugin I want to edit the relation propertis to activate the create button for same relation

**Comment by marcellovetro** [comment]
I'm trying to solve the issue myself but I'm encountering some problems, the first is:

I've edited the file strapi-plugin-content-manager/admin/src/containers/EditPage/index.js adding the function that jump to the related content type in creation and want to set the relation with the current record, I've added the code:

````
addRelatedElement = (relation) => {

    const target = {
      name: `record.${relation.via}`,
      value: (relation.nature == 'oneToMany' ? this.props.editPage.record: [this.props.editPage.record]),
      type: 'select'
    };

    this.props.match.params = {
      slug: relation.collection,
      id: 'create'
    };

    this.props.resetProps();
    this.componentDidMount();
    const url = `/plugins/content-manager/${relation.collection}`;
    this.props.history.push({
      pathname: `${url}/create`,
      search: `?redirectUrl=${url}?source=content-manager`
    });
  
    console.log("relation", relation);
    console.log("this.props", this.props);
    this.props.changeData({ target });
  };
````
and into the "render()" function, I've exposed the function "addRelatedElement=this.addRelatedElement}"
````
  render() {
                      ...
                      <EditRelations
                        addRelatedElement={this.addRelatedElement}
                      ...
  }
````
This code jump correctly to the create page but the console.log("this.props" ... ) seems to be linked to the previous page (not the create page) and the code "this.props.changeData({ target });"  has no effect.

This code worked well in the alpha version 12.3 when I had done some experiments, but now not anymore. Do you have any suggestions?

**Comment by lauriejim** [comment]
@soupette Is the good guy to help you on this point.

**Comment by marcellovetro** [comment]
@soupette and other interested programmers I've created a DEMO pull request to give you all my code, I await your suggestions!

**Comment by lauriejim** [comment]
It's not something we will do right now. I close this issue - feel free to submit feature request here https://portal.productboard.com/strapi
