### ISSUE TITLE
content-type-builder fails with a blank page and Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 

### ISSUE THREAD

**Issue by lgt** [strapi/strapi#1966]
Hi I just installed strapi and was giving a try. I use

**strapi 3.0.0-alpha.14**

**node v10.0.0**

**mongo db version v3.6.7**

**npm v5.6.0**

**centos 7.5**

**nginx**

I can start up strapi but if I try to access add content type I get a blank.

I get couple of warnings on start:

``(node:21020) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(node:21020) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:21020) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
(node:21020) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.``

In console I have the following error:

``Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional ``

**Comment by derrickmehaffy** [comment]
@lgt what OS are you using?

**Comment by lgt** [comment]
I'm using centos server v7.5

**Comment by derrickmehaffy** [comment]
@lgt please use mongo 3.x as I don't think Strapi fully supports mongo v4.x yet

**Comment by lgt** [comment]
ok thanks I give a try with a mongo downgrade

**Comment by lgt** [comment]
After downgrade mongo to v3.6  the problem still persist

**Comment by derrickmehaffy** [comment]
I didn't think it would, hmmmm. I'm honestly not sure where this is coming from, what modifications have you made. Is this a fresh project, and updated one?

I've never seen this error before.

**Comment by lgt** [comment]
erased created project with strapi
downgraded mongo
created a new strapi project and going through by install process

**Comment by chrishawes** [comment]
Same error occurs running Strapi following the example in the `strapi-docker` repo:
https://github.com/strapi/strapi-docker#then-run-image

(With both the `mongo:3` and `mongo` images.)

**Comment by RobinPel** [comment]
I have the same problem since a few days on the latest version with docker, already mentioned it in #1325.

**Comment by lauriejim** [comment]
About mongoose logs, we have an issue here: https://github.com/strapi/strapi/issues/1592

**Comment by lauriejim** [comment]
And can you try to install the last version of Strapi (3.0.0-alpha.14.1.1)

**Comment by RainKolwa** [comment]
Same problem with version 3.0.0-alpha.14.1.1 here.
env
node: v10.10.0
mongo db: v3.4

**Comment by lauriejim** [comment]
What is your OS ?

**Comment by chydaya** [comment]
just run command `npm run setup`

**Comment by soupette** [comment]
@chydaya what's your setup? Are you using the version from npm or from the monorepo?

**Comment by chydaya** [comment]
@soupette I'm had this problem with latest docker image on macos

**Comment by soupette** [comment]
@Moldieman can you upgrade to the latest version of strapi? Also don't forget to delete the `plugin_content_manager_schema` entry in your `core_store`.

**Comment by quasarom** [comment]
I had same problem. After installing with nvm newest node v10.10.0 version and installing latest (14.1.1) strapi cli newly generated project has working content type builder. Maybe problem was with already downloaded npm package's versions?

**Comment by eden6** [comment]
@soupette I get the same error on a new v14 project with mongo:3 (using Docker as well).

**Comment by charleshamesse** [comment]
I got the same error using strapi-docker. Tl;dr: manually installing `bash` and `libpng-dev` fixed it for me.

I tried  `npm run setup` and got an error saying it couldn't find the module  `cross-env `.
Found in #1006 that  `npm link strapi-helper-plugin` might solve it and got an error about `pngquant` not compiling correctly. 
Then I installed `bash` and `libpng-dev` as in [this issue](https://github.com/imagemin/pngquant-bin/issues/36), re-ran `npm run setup` and the error was gone.

Hope that helps!

**Comment by SharkeyO** [comment]
Still not working with bash and libpng-dev installed. Something seems to be messed up.

**Comment by leighayanid** [comment]
I got the same error after updating to the latest version. Uninstalling strapi globally and then installing it again fixed it for me

**Comment by soupette** [comment]
So we can close the issue?

**Comment by eden6** [comment]
Installing a new version of node made it work. Reinstalling Strapi wasn't enough on my side.

**Comment by johncalvinroberts** [comment]
Also having this issue. Tried installing new global version of strapi, updating all dependencies, deleting all records in `core_store` in database, still no luck.

**Comment by RainKolwa** [comment]
Updating Strapi to 3.0.0-alpha.14.1.1 works on my side.

**Comment by eden6** [comment]
Updating Node made it work on my side

**Comment by cosydney** [comment]
> @Moldieman can you upgrade to the latest version of strapi? Also don't forget to delete the `plugin_content_manager_schema` entry in your `core_store`.

Can you elaborate on that ?

**Comment by cosydney** [comment]
I've tried all solutions provided, recreating new project I have same error ```content-type-builder fails with a blank page and Minified React error #188;```

**Comment by cosydney** [comment]
Resolved: 
It seemed I had conflict between Strapi installed on my computer (here 14.4) and the one I was running (which I saw in the bottom left of the admin panel 'powered by 3.0.0-alpha.14.2.0).... 
![image](https://user-images.githubusercontent.com/10532381/48305415-47132d80-e500-11e8-924c-17b837b35983.png)

I just had to follow the migration guide for React minified error to disappear:
https://github.com/strapi/strapi/wiki/migration-guide-alpha.14.3-to-alpha.14.4

**Comment by Dezzign** [comment]
Strapi docs all going to 404 for the last few hours: https://strapi.io/documentation/developer-docs/latest/migration-guide/#migrations-guides

**Comment by MattieBelt** [comment]
@Dezzign this is not related to this issue, but the docs have had a restructure and they are working on the 404's. 
https://strapi.io/documentation Should get you to the new docs. For more info on the restructure, checkout [this forum post](https://forum.strapi.io/t/new-developer-documentation-structure-release-contributions-unfreeze/3240?u=mattiebelt )
