### ISSUE TITLE
version 4.20.3 breaks User & Permissions Plugin

### ISSUE THREAD

**Issue by ayhid** [strapi/strapi#19673]
### Required System information

Environment: development
OS: darwin-x64
Strapi Version: 4.20.3
Node/Yarn Version: npm/10.2.4 node/v20.11.1 darwin x64 workspaces/true
Edition: Community
Database: postgres

### Describe the bug

On strapi 4.20.3 I can't see the User & Permissions Plugin
Downgrading to 4.20.2 I can see it again

### Screenshots

<img width="1753" alt="Capture d’écran 2024-03-04 à 18 19 21" src="https://github.com/strapi/strapi/assets/235381/e5c4b32e-c0ce-4f30-b83d-d1a6297d1f5d">

<img width="1754" alt="Capture d’écran 2024-03-04 à 18 23 59" src="https://github.com/strapi/strapi/assets/235381/91505d53-31ce-44dc-b1e4-8eb97abbb5cc">

**Comment by derrickmehaffy** [comment]
Brand new 4.20.3 projects looks fine:

![image](https://github.com/strapi/strapi/assets/8593673/47d0db39-e51f-4dd8-a7eb-b77fad32c968)

Created a fresh 4.19.1 project and upgraded it incrementally from v4.20.0, 4.20.1, 4.20.2, and v4.20.3 and noticed no issues

4.19.1
![image](https://github.com/strapi/strapi/assets/8593673/2ea26243-7327-4f21-8f22-afd3269fee68)

4.20.0
![image](https://github.com/strapi/strapi/assets/8593673/3ed59fc5-5ac0-4fc3-83d8-2f194bd0d3c2)

4.20.1
![image](https://github.com/strapi/strapi/assets/8593673/28c3b2e5-e790-4a5a-b9e6-11204b5afd54)

4.20.2
![image](https://github.com/strapi/strapi/assets/8593673/fc91edc5-5e6e-4a3b-baca-fc3ba5618c70)

4.20.3
![image](https://github.com/strapi/strapi/assets/8593673/288a2c86-f45b-4173-81f6-d29e837d7a71)
