### ISSUE TITLE
Polymorphic fields can't be added to View for content editors to set via Admin panel when creating entries

### ISSUE THREAD

**Issue by stevebutler2210** [strapi/strapi#19684]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 4.20.3
- Database: sqlite
- Operating system: MacOS Sonoma (14.3.1)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When creating a polymorphic relation through schema customisation (as this feature does not appear to be supported directly in the Admin panel), it seems to be impossible to add this field to the content editor view.

### Steps to reproduce the behavior

1. Ensure you have three basic models setup—`Article`, `Brand` (each with a single `Text` title field) and the default `User` model
2. Add the following to the `"attributes"` config in `src/api/brand/content-types/brand/schema.json`
```
"articles": {
    "type": "relation",
    "relation": "morphMany",
    "target": "api::article.article",
    "morphBy": "owner",
    "configurable": "false"
  }
```
3. Add the following to the `"attributes"` config in `src/extensions/users-permissions/content-types/user/schema.json`
```
"articles": {
    "type": "relation",
    "relation": "morphMany",
    "target": "api::article.article",
    "morphBy": "owner",
    "configurable": "false"
  }
```
4. Add the following to the `"attributes"` config in `src/api/article/content-types/article/schema.json`
```
"owner": {
    "type": "relation",
    "relation": "morphToMany",
    "configurable": false
  }
```
5. save all and restart the server using `npm run develop`
6. open the admin panel and navigate to `Content-Type Builder` -> `Article` -> `Configure the view`

### Expected behavior

The field should either be included already, or should be addable via the `Insert another field` prompt.

Actual behaviour is that there is no way to add the field, even though it appears correctly in the `Content-Type Builder` forms.

The upshot is that there is no way for a content editor creating an entry to set a value for the polymorphic field.

### Screenshots

Article Content-Type Builder - relation field displayed
![Screenshot 2024-03-05 at 16 02 25](https://github.com/strapi/strapi/assets/25485564/d5186128-54e7-48fd-a5fd-665e85be6b3c)

Brand Content-Type Builder - relation field displayed (correctly noted as polymorphic)
![Screenshot 2024-03-05 at 16 02 32](https://github.com/strapi/strapi/assets/25485564/3e95e6a1-5931-43b4-866b-8d7329cf424a)

User Content-Type Builder - relation field displayed (correctly noted as polymorphic)
![Screenshot 2024-03-05 at 16 02 40](https://github.com/strapi/strapi/assets/25485564/9596b583-1af2-4ae2-9bc5-3760a8dc9676)

Article View configuration pane - field missing and option to add fields greyed out
![Screenshot 2024-03-05 at 16 02 52](https://github.com/strapi/strapi/assets/25485564/eb0684ab-4a1f-4bd6-88c2-8dc33d7d8a8d)

**Comment by derrickmehaffy** [comment]
Closing this as a feature request rather than a bug report as we do not support polymorphic relationships in the admin.

See this feature request here: https://feedback.strapi.io/customization/p/manage-polymorphic-relations-in-the-admin
