### ISSUE TITLE
Relation field is showing Content ID instead of Content name when loading more

### ISSUE THREAD

**Issue by fernandonmenezes** [strapi/strapi#19698]
### Required System information

- Node.js version: 18.15.0
- NPM version: 9.5.0
- Strapi version: 4.20.2
- Database: MySql
- Operating system: win32-x64
- Is your project Javascript or Typescript:

### Describe the bug

We have a relation field and it works fine until we try to click on “load more”, then the new values loaded only show the Content ID. I have inspected the requests and for some strange reason the only field returned on page 2(or higher) is the id, the name and published_at are not returned.

### Steps to reproduce the behavior

1. Go to the colletion type where you have the relation field
2. Add more than 5 items
3. Save changes
4. Refresh page
5. The relation field will load first 5 items and show a button to load more
6. Click "load more"
7. New items will show only the id, instead of the field you selected and won't show it object is published or not

### Expected behavior

I expect the relation field to always show the text contained on the field selected when configuring the view for that collection type, in my example here it would have been the "name" field.

### Screenshots

![image](https://github.com/strapi/strapi/assets/41285169/d99e0319-69e3-4a72-81e9-87a3fa88b404)

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/19625
