### ISSUE TITLE
How I can run the alpha.4 branch?

### ISSUE THREAD

**Issue by ellipticaldoor** [strapi/strapi#197]
I want to try the alpha.4 branch but I can install it through the cli.

I tried this:
```
npm i -g git://github.com/strapi/strapi.git#alpha.4
```

But I get this error:
```
npm ERR! addLocal Could not install /var/folders/5k/zmz0q1y146dffjbnghq8mv800000gn/T/npm-93525-e7c3720b/git-cache-93e2a463/4645e7fd00f8fea35d1d7073f72693fa79e06059
```

**Comment by Aurelsicoko** [comment]
@ellipticaldoor Thanks for your concern about the v3! We fixed the installation process this morning on the `alpha.4` branch. You can run the following command to install Strapi v3 on your computer.

```
git clone git@github.com:strapi/strapi.git -b alpha.4 --single-branch && cd strapi && npm run setup
```

**Comment by ellipticaldoor** [comment]
Thanks! I will try it.
