### ISSUE TITLE
4.20.4: Typescript Error: Spreading of JSON field is giving typescript error "Spread types may only be created from object types"

### ISSUE THREAD

**Issue by gregg-cbs** [strapi/strapi#19722]
### Required System information

- Node.js version: 18.6.0
- NPM version: 9
- Strapi version: 4.20.4
- Typescript: TS

### Describe the bug
Seems I can spread JSON fields because strapi types dont match TS types
![image](https://github.com/strapi/strapi/assets/57114335/42da849f-cc03-4b6e-b919-a339ede1f0fb)

### Steps to reproduce the behavior

1. Create a collection
2. Add a json field
3. Fetch an entry from the collection
4. Try spread the json field

### Expected behavior
Types to match

**Comment by a-h-m-e-d-a-z-i-z** [comment]
@gregg-cbs Please provide more context about the error (file/line)

**Comment by kasonde** [comment]
Hi @gregg-cbs from what I can see here, it seems a bit more like a usage issue. From the screenshots you sent, you're trying to spread a field into an object, as well as in the second shot, you're trying to assign a field in a json object to an actual datatype (`checkout`). You'd have to stringify checkout to set it correctly.
