### ISSUE TITLE
Cannot edit entries of a content-type with a field with maxLength

### ISSUE THREAD

**Issue by schmitzl** [strapi/strapi#1973]
**Informations**
- **Node.js version**: 10.4.1
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1
- **Database**: Postgres
- **Operating system**: MacOS

**What is the current behavior?**
After adding a field of type text or string with a maxLength, entries can no longer be edited. Creating new ones still works fine.
When I remove the maxLength, I can edit entries again.

**Steps to reproduce the problem**
1.  Create content-type "Comment"
2. Add a field "body" with type String or Text and add a maxLength of 140 character
3. Create an entry
4. Try to edit and save the entry - it fails for me here

**What is the expected behavior?**
I can edit entries that have a field with a maxLength.

**Comment by lauriejim** [comment]
Hello @schmitzl , I tried your steps, and I was not able to reproduce it.
Can you install last version of Strapi (alpha.14.1.1) and try again please.

**Comment by schmitzl** [comment]
I installed the last version and now it works. I do not know what went wrong before. Thanks for your answer.
