### ISSUE TITLE
onChange prop from Plugin Custom Fields not saving empty string 🐞

### ISSUE THREAD

**Issue by sehrish30** [strapi/strapi#19736]
### Required System information

- Node.js version: 18.18.2
- NPM version:  9.8.1
- Strapi version: 4.20.4
- Database: mysql
- Operating system: MacOs 14.4
- Is your project Javascript or Typescript: Typescript

### Describe the bug

onChange prop from Plugin Custom Fields not saving empty string "" and the value always shows the last character even though you try to remove the last character. PS: If you enter other characters it works fine the issue is only **when clearing input**. I have checked onChange event properly sends an empty string when the user clears input but the last character is never removed.

### Steps to reproduce the behavior

1. Based on this documentation here "https://docs.strapi.io/dev-docs/custom-fields" I have created a custom text field
2. I can backspace and delete text but cannot remove the last letter
3. onChange never removes the last character
4. The last character always stays, although I have pressed backspace
5. <img width="752" alt="Screenshot 2024-03-12 at 12 48 28 PM" src="https://github.com/strapi/strapi/assets/66527974/0c943877-a5e0-4887-ac0e-cc4efbfd3457">
6. the above is my settings for the custom input field which is basically a search field and shows a dropdown as well but I want to let the user type in the input field as well!

### Expected behavior
When a user enters the 'Backspace' key in a text input field, it removes the character immediately preceding the cursor position or the selected text if any.

### Screenshots

I'm never able to backspace and remove "d"
<img width="346" alt="Screenshot 2024-03-12 at 1 02 24 PM" src="https://github.com/strapi/strapi/assets/66527974/a63a4bed-db0e-40dc-803d-b50b6554c577">

### Code snippets

If applicable, add code samples to help explain your problem.
<img width="552" alt="Screenshot 2024-03-12 at 1 07 59 PM" src="https://github.com/strapi/strapi/assets/66527974/9a0a5295-6592-4119-b105-a3c13dc2c3dd">

I'm saving empty save to remove last character as a _workaround_

**Comment by joshuaellis** [comment]
Yes, this is a quirk of the EditView in V4. To clear values we expect `null`.

**Comment by sehrish30** [comment]
> Yes, this is a quirk of the EditView in V4. To clear values we expect `null`.

Tried null still not able to delete last character

<img width="739" alt="Screenshot 2024-03-12 at 2 01 46 PM" src="https://github.com/strapi/strapi/assets/66527974/5151669f-b547-414f-82e0-b302f1e5100a">
<img width="412" alt="Screenshot 2024-03-12 at 2 02 12 PM" src="https://github.com/strapi/strapi/assets/66527974/c7a529b8-ac53-4eac-81ed-d98b573c016e">

**Comment by sehrish30** [comment]
https://github.com/sehrish30/check-plugin-strapi

I checked there was no issue with the onChange function I had another function that was modifying the logic of onChange. Refer to my attached repo to check how I created a custom textbox that works fine.

Thanks Team.
