### ISSUE TITLE
Snake case field names break content manager/entity service

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#19742]
This is the narrowed-down cause of https://github.com/strapi/strapi/issues/19669 which I closed in favour of this issue.
### Required System information
Node.js version: 18.17.1
NPM version: 9.6.7
Strapi version: 4.5.6
Database: Postgres
Operating system: OSX
Is your project Javascript or Typescript: TS

### Describe the bug

Having relation field names written in snake case in a datatype as depicted in this example breaks the content manager (both admin dashboard and code) as the db query gets screwed up. The result is you can't add data of this type through your code via the entity service or the admin dashboard. The regular CRUD APIs still work though, funnily.

### Steps to reproduce the behavior

1. Create this basic datatype:
```{
  "kind": "collectionType",
  "collectionName": "debugs",
  "info": {
    "singularName": "debug",
    "pluralName": "debugs",
    "displayName": "debug"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "created_by_id": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::users-permissions.user"
    },
    "updated_by_id": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::users-permissions.user"
    }
  }
}
```

2. Try creating an entry for it via the admin dashboard or entity service.
3. See error: 
```
[2024-03-12 17:11:26.478] error: insert into "debugs" ("created_at", "undefined", "updated_at") 
values ($1, $2, $3) returning "id" - column "undefined" of relation "debugs" does not exist
```

### Expected behavior

Creating the datatype works as expected.

### Screenshots

<img width="775" alt="image" src="https://github.com/strapi/strapi/assets/11761828/cd14b938-a68e-497f-b32d-48ba92d401e3">

**Comment by Boegie19** [comment]
fixed by https://github.com/strapi/strapi/pull/19345/files
