### ISSUE TITLE
ER_LOCK_DEADLOCK on component update (4.20.2 / mysql8)

### ISSUE THREAD

**Issue by ryanengland** [strapi/strapi#19748]
### Required System information

- Node.js version:  node/v18.17.1
- NPM version: yarn/1.22.19
- Strapi version: 4.20.2
- Database: MySQL 8 (hosted on Digital Ocean - 16Gb RAM, 4 VCPU with modes: ANSI_QUOTES, ERROR_FOR_DIVISION_BY_ZERO, IGNORE_SPACE, NO_ENGINE_SUBSTITUTION, NO_ZERO_DATE, NO_ZERO_IN_DATE, ONLY_FULL_GROUP_BY, PIPES_AS_CONCAT, REAL_AS_FLOAT, STRICT_ALL_TABLES)
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When running a large number of updates on the database, as part of a migration script, and making use of the Entity Service to update models (in this case a 'Place' model) that contain components, the following error occurs:

`{
    "code":"ER_LOCK_DEADLOCK",
    "errno":1213,
    "sqlState":"40001",
    "sqlMessage":"Deadlock found when trying to get lock; try restarting transaction",
    "sql":"UPDATE 'places_components' as a, ( select 'id', row_number() over (partition by 'entity_id' order by 'order') as src_order from 'places_components' where 'entity_id' = 765 ) AS b SET 'order' = b.src_order WHERE b.id = a.id"
}`

At lower transaction rates (1 update per second), this error does not occur. When testing at 10 updates per second, the error occurs. This has previously been mentioned in other tickets, but marked fixed and closed: #15202 

### Steps to reproduce the behavior

1. Create a model with a component (unsure if number of fields within component makes a difference)
2. Create a cron job to iterate over multiple records in a for loop, using the Entity Service (in my case, Place): `await strapi.entityService.update('api::place.place', id, { data });`
3. Allow to run for upwards of 20+ seconds, deadlocks start occurring.

### Expected behavior

Regardless of pace of updates, using the Entity Service, I should be able to update models as fast as my database is able to handle.

### Additional context

Although this was marked fixed in a previous version, this is perhaps a regression. I'm happy to provide my schema if it would help.

**Comment by derrickmehaffy** [comment]
We really need clean reproduction steps because this is like finding a hay colored needle in a hay stack, it would only happen under very specific conditions.

**Comment by hsnbsst** [comment]
I encountered the same problem @derrickmehaffy 

values (110573, 14618) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction

MariaDB: 10.3.39

**Comment by derrickmehaffy** [comment]
> I encountered the same problem @derrickmehaffy 
> 
> values (110573, 14618) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
> 
> MariaDB: 10.3.39	

We need reproduction steps
