### ISSUE TITLE
Conflict Error with API ID (Plural) When Enabling i18n on New Single Type or Collection

### ISSUE THREAD

**Issue by Eventyret** [strapi/strapi#19750]
### Required System information

- Node.js version: 20.11.1
- NPM version: 10.2.4
- Strapi version: 4.20.4
- Database: sqlite
- Operating system: Mac
- Is your project Javascript or Typescript: javascript

### Describe the bug

When editing a single-type or collection in Strapi to enable i18n, an error is encountered. The API ID (plural) throws an error message indicating that the value is already in use by another content-type, even though this is not the case as it was newly created.

### Steps to reproduce the behavior
- Create a new single type or collection (without i18n)
- Save the single type or collection.
- Edit this single-type or collection by enabling i18n.
- Save the changes.
- An error is displayed in the Basic Settings regarding the API ID (plural) stating “this value is already in use by another content-type”.

### Expected behavior

The expectation is that once i18n is enabled for a single type or collection, it should save without any errors regarding the API ID (plural), as it should not conflict with other content types if it is unique and newly created.

### Screenshots

![image](https://github.com/strapi/strapi/assets/977232/a75d4423-c8ac-4140-80ac-c15f786a3210)

**Comment by rGillyazanov** [comment]
If there is a hyphen in the API ID name, an error is displayed.

**Comment by AdityaBanik** [comment]
Facing the same bug

**Comment by zirho** [comment]
You can edit `schema.json` as a workaround.

**Comment by Tsun4mii** [comment]
Facing the same bug. It appears not only on single types but on some collection types in my case
