### ISSUE TITLE
Large file upload in strapi fails

### ISSUE THREAD

**Issue by balarayen** [strapi/strapi#1975]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: Mongodb
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
Using strapi 3.0.0-alpha.14.1.1, upload-local file provider and mongodb, it fails to upload a 500 MB file. Though the "Maximum size allowed (in MB)" is set to 10000 MB, it throws the following error:

Using curl:

> curl -X POST -F 'files=@/development/TestFiles/largefile.zip' http://localhost:1337/upload
> {"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}

Using admin panel:

> Error: maxFileSize exceeded, received 209780558 bytes of file data
> at Stream.<anonymous> (/usr/lib/node_modules/strapi/node_modules/formidable/lib/incoming_form.js:222:19)
> at emitOne (events.js:116:13)
> at Stream.emit (events.js:211:7)
> at MultipartParser.parser.onPartData (/usr/lib/node_modules/strapi/node_modules/formidable/lib/incoming_form.js:387:14)
> at callback (/usr/lib/node_modules/strapi/node_modules/formidable/lib/multipart_parser.js:102:31)
> at dataCallback (/usr/lib/node_modules/strapi/node_modules/formidable/lib/multipart_parser.js:112:11)
> at MultipartParser.write (/usr/lib/node_modules/strapi/node_modules/formidable/lib/multipart_parser.js:305:3)
> at IncomingForm.write (/usr/lib/node_modules/strapi/node_modules/formidable/lib/incoming_form.js:159:34)
> at IncomingMessage.<anonymous> (/usr/lib/node_modules/strapi/node_modules/formidable/lib/incoming_form.js:125:12)
> at emitOne (events.js:116:13)
> at IncomingMessage.emit (events.js:211:7)
> at IncomingMessage.Readable.read (_stream_readable.js:475:10)
> at flow (_stream_readable.js:846:34)
> at resume_ (_stream_readable.js:828:3)
> at _combinedTickCallback (internal/process/next_tick.js:138:11)
> at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Steps to reproduce the problem**
Create a new strapi project and upload a file of size 500 MB.

**What is the expected behavior?**
Upload should work.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Based on that error there is a cap being placed at ~209MB `Error: maxFileSize exceeded, received 209780558 bytes of file data`

Is this using local storage, can you confirm the local free space is > 209MB (stupid question I know, but have to ask)

**Comment by balarayen** [comment]
@derrickmehaffy Yes, it uses local storage and it has more than 250GB free space.

**Comment by derrickmehaffy** [comment]
Side note @balarayen do you actually have the intention of uploading 10GB files?

**Comment by balarayen** [comment]
@derrickmehaffy Now it can be up to 1.5GB but in future, it will increase. So yes.

**Comment by Flux159** [comment]
In config/environments/development/request.json, you need to change the koa body parser config for formidable:

Example: Setting maxFileSize to 500MB for formidable (number is in bytes so 500\*1024\*1024):
```
...
"parser": {
    "enabled": true,
    "multipart": true,
    "formidable": {
      "maxFileSize": 524288000
    }
  },
...
```

This setting isn't changed when you change the upload plugin settings from the GUI so you will need to keep it synced manually (although I guess it should be). I think that you need to change it in both places otherwise there will be an error (see https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/controllers/Upload.js#L37 for when its using strapi upload's config.sizeLimit).

You will also need to do this for other environments if you change the values there (ie staging/production). 

I believe that a proper fix for this would be the strapi-upload-plugin updating the koa body parser config (seems like strapi is using koa-body for multipart parsing: https://github.com/dlau/koa-body).

**Comment by balarayen** [comment]
@Flux159 It works great for me. Thanks!

**Comment by nguyenminhtienhust** [comment]
> In config/environments/development/request.json, you need to change the koa body parser config for formidable:
> 
> Example: Setting maxFileSize to 500MB for formidable (number is in bytes so 500*1024*1024):
> 
> ```
> ...
> "parser": {
>     "enabled": true,
>     "multipart": true,
>     "formidable": {
>       "maxFileSize": 524288000
>     }
>   },
> ...
> ```
> 
> This setting isn't changed when you change the upload plugin settings from the GUI so you will need to keep it synced manually (although I guess it should be). I think that you need to change it in both places otherwise there will be an error (see https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/controllers/Upload.js#L37 for when its using strapi upload's config.sizeLimit).
> 
> You will also need to do this for other environments if you change the values there (ie staging/production).
> 
> I believe that a proper fix for this would be the strapi-upload-plugin updating the koa body parser config (seems like strapi is using koa-body for multipart parsing: https://github.com/dlau/koa-body).
In current version, i can't find out this config/environments/development/request.json. please help me ?

**Comment by Flux159** [comment]
@nguyenminhtienhust This issue is 2 years old and formidable and strapi's configuration system has changed - see https://github.com/strapi/strapi/issues/7035 and it may be more up to date / relevant.

**Comment by maertz** [comment]
for anyone who comes from 2021
https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#configuration

**Comment by SanjulaD** [comment]
check your nginx conf that you have specified a limit. Default the limit will be 1mb
