### ISSUE TITLE
Editing a user using MySQL as a database fails

### ISSUE THREAD

**Issue by johhansantana** [strapi/strapi#1977]
**Informations**
- **Node.js version**:
v10.9.0
- **npm version**:
6.2.0
- **Strapi version**:
3.0.0-alpha.14.1.1
- **Database**:
MySQL
- **Operating system**:
Mac

**What is the current behavior?**
When trying to edit a user using MySQL database, it will fail.

**Steps to reproduce the problem**
Using MySQL as the Strapi database
![err](https://user-images.githubusercontent.com/9933887/45692814-afa9e380-bb29-11e8-8f27-c5267769c0a0.gif)

**What is the expected behavior?**
Should let me edit the user

**Suggested solutions**
While using MongoDB as the database, it will let me edit the user. Also noticed that the password is getting populated with the hash when using MongoDB as well.

**Comment by derrickmehaffy** [comment]
After talking with @johhansantana on Slack, I also noticed that adding a user with the proxy enabled will result in an error.

![image](https://user-images.githubusercontent.com/8593673/45699761-9b60e900-bb1f-11e8-9874-c78ddc7e447a.png)

It also appears that the redirect url *might* be wrong, not sure on that.

@soupette

**Comment by derrickmehaffy** [comment]
Also @soupette I was pretty sure this part was fixed but it seems to have regressed:

`Also noticed that the password is getting populated with the hash when using MongoDB as well.`

Huge security risk, there is no reason to display that hash on the adminUI, what I find odd is it only happens with mongoose and not bookshelf.

**Comment by lauriejim** [comment]
I'm not able to reproduce.

Why you don't have password ?
How did you create this user ?

**Comment by johhansantana** [comment]
@lauriejim after creating a new user, it let me edit user 🤔 I'm not sure if I have to close the issue or continue for the hash password fix?

Sorry for the noise.

**Comment by derrickmehaffy** [comment]
@lauriejim what database type did you test on?

**Comment by derrickmehaffy** [comment]
Testing done on localhost:1337 for creating a user works fine, however in a production deployment it fails with the above screenshot.

Also @soupette on both MySQL and bookshelf the password hash is being displayed while using localhost:1337

As stated above there should be no reason to display this hash on the adminUI ever, that password box should be for a quick reset of a user password if manual password reset is required. A normal admin should never be able to grab that hash, as it poses a large security risk (and likely doesn't follow some law in the UK about personal information). That type of data should only exist in one place and that is on the DB.

**Comment by derrickmehaffy** [comment]
In my test I had the proxy config enabled, so that error is likely related to the redirect, no errors show up in the console.

**Comment by lauriejim** [comment]
@johhansantana Did you get you issue in local or production environment ?

**Comment by johhansantana** [comment]
It was locally. I haven't got the issue anymore.
