### ISSUE TITLE
yarn build does not exit the process when using Apollo GraphQL with Redis

### ISSUE THREAD

**Issue by cwillinx** [strapi/strapi#19797]
### Required System information

- Node.js version: v18.17.1
- Yarn version: 1.22.19
- Strapi version: 4.20.3
- Database: mysql
- Operating system: MacOS 14.3.1
- Is your project Javascript or Typescript: mostly Javascript

@apollo/utils.keyvadapter 3.1.0
@keyv/redis 2.8.4
@strapi/plugin-graphql 4.20.3
@strapi/strapi 4.20.3
keyv 4.5.4

### Describe the bug

In a setup using Apollo Server with Redis Cache, when you run `yarn build`, the build process is completed but `yarn build` command never exited and this causes problems for automated deployments, next command cannot be executed because `yarn build` command was not exited.
The same behaviour happens on the staging environment.

It seems to be related to https://github.com/strapi/strapi/issues/13614.

### Steps to reproduce the behaviour

0. Setup Apollo Server with Redis Cache.
1. Open a terminal
2. Navigate to the Strapi app folder
3. Run `yarn build`
4. Build is completed but the `yarn build` command is never exited

### Expected behavior

The build process should be exited when it is completed.

### Screenshots

<img width="848" alt="Screenshot 2024-03-15 at 17 43 11" src="https://github.com/strapi/strapi/assets/7781140/3f2bb261-306d-466a-b897-4696684957cf">

### Code snippets

In `config/plugins.ts`:

```javascript
graphql: {
    config: {
      endpoint: '/graphql',
      apolloServer: {
        // https://www.apollographql.com/docs/apollo-server/performance/cache-backends/#configuring-redis
        // this breaks the `yarn build` admin interface build for unknown reason. When we comment out the cache, the build succeeds and the build process is exited.
        cache: new KeyvAdapter(new Keyv('redis://localhost:6379')),
      },
    },
  },`

**Comment by cwillinx** [comment]
@derrickmehaffy there seems to be a misunderstanding. 

I don’t have a question, this is clearly a bug report. 

The build process should exit but it doesn‘t when redid together with graphQL is used. 

This is the bug. 

Please reopen the issue and reconsider the label.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy there seems to be a misunderstanding. 
> 
> I don’t have a question, this is clearly a bug report. 
> 
> The build process should exit but it doesn‘t when redid together with graphQL is used. 
> 
> This is the bug. 
> 
> Please reopen the issue and reconsider the label. 

It was marked as a question since we ourselves don't natively support using Apollo's cache system.

If you can reproduce the issue within Strapi without the customization I can reopen this.
