### ISSUE TITLE
I18n: Truncating the "Content available in" column value too early even with enough space

### ISSUE THREAD

**Issue by luke-z** [strapi/strapi#19790]
### Required System information

- Node.js version: 20.11.0
- yarn version: 1.22.21
- Strapi version: 4.20.5
- Database: sqlite
- Operating system: Ubuntu WSL
- Is your project Javascript or Typescript: TS

### Describe the bug

In our existing project and a new one I setup to verify, the "Content available in" Column fails to display the existing languages. It is cut off far too early and only displays "E..." in our case.

![image](https://github.com/strapi/strapi/assets/37207714/6e49869d-a2ca-4812-be01-662fa76fbcf8)

If I add a width of 100% to the element, the content is shown as desired (compare row 1 and row 2 on the screenshot).

### Steps to reproduce the behavior

1. Create a new strapi project
2. Create a content type with i18n
3. Add an item to the content type
4. Check the content type overview table

### Expected behavior

The existing languages should not be truncated if there's enough space for them to be displayed.
I know there's an arrow that could be clicked to see all available content languages, but if the screen is large enough it would be nice to see the languages without having to click on each arrow.

**Comment by Ceda** [comment]
I have same problem...  width="2rem" causing this issue..
https://github.com/strapi/strapi/blob/1e46ca925484dd19eea4cd25f16982eb69881043/packages/plugins/i18n/admin/src/components/LocaleListCell.tsx#L63

**Comment by SpeedAD** [comment]
Hey @derrickmehaffy 
has anyone taken this up? I've been wanting to contribute and it seems like its a good first issue. I'd like to work on it as my first contribution. let me know :)

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy has anyone taken this up? I've been wanting to contribute and it seems like its a good first issue. I'd like to work on it as my first contribution. let me know :)

We will be working on it ourselves as v4 is currently in a change freeze and we are doing a lot of changes in Strapi 5 right now

**Comment by SpeedAD** [comment]
> > Hey @derrickmehaffy has anyone taken this up? I've been wanting to contribute and it seems like its a good first issue. I'd like to work on it as my first contribution. let me know :)
> 
> We will be working on it ourselves as v4 is currently in a change freeze and we are doing a lot of changes in Strapi 5 right now

Oh all right. 

I'm not exactly sure how, but if v5 repository is open to contributions, I'd love to help out fix some bugs :)

**Comment by simotae14** [comment]
Fixed in this PR https://github.com/strapi/strapi/pull/20059, thanks
