### ISSUE TITLE
Don't limit  strapi v1.5.X to node 4.8.0 !

### ISSUE THREAD

**Issue by zengxinle** [strapi/strapi#198]
Don't limit  strapi v1.5.X to node 4.8.0 !

I install  strapi v1.5.X ,then  new  proxxx.

strapi  start .   warn: Your Node.js version is greater than 4.8.0.

my node only is 4.8.2.     why  can't run ???   it's necessary ？！

**Comment by Aurelsicoko** [comment]
@zengxinle Thanks for this issue! I published a patch `strapi@1.5.6`, let me know if it fixes the issue on your side (https://github.com/strapi/strapi/commit/087cb6e5ecadf20b2b980881d88555c5076d8033).

**Comment by zengxinle** [comment]
THANKS.

**Comment by pierreburgy** [comment]
@zengxinle Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
