### ISSUE TITLE
Error when installing using "npx create-strapi-app@latest my-project"

### ISSUE THREAD

**Issue by roninaruka** [strapi/strapi#19815]
### Required System information

- Node.js version: 20.9..0
- NPM version: 10.1.0
- Strapi version: letest
- Database: postgresql
- Operating system: ubuntu 20.04
- Is your project Javascript or Typescript: typescript

### Describe the bug

when installing strapi using "npx create-strapi-app@latest my-project" got error 
`Creating files.
Error while installing dependencies:
warning ../../../package.json: No license field
warning @strapi/strapi > @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
warning @strapi/strapi > @strapi/types > @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
warning @strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning @strapi/strapi > @strapi/admin > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/admin > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @strapi/strapi > @strapi/database > umzug > @rushstack/ts-command-line > @rushstack/terminal > @rushstack/node-core-library > z-schema@5.0.6: has issues with node 14
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error An unexpected error occurred: "/home/chhayya/.cache/yarn/v6/npm-semver-7.6.0-1a46a4db4bffcccd97b743b5005c8325f23d4e2d-integrity/node_modules/semver/.yarn-metadata.json: Unexpected end of JSON input".
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /usr/local/lib/node_modules/create-strapi-app/node_modules/@strapi/generate-new/dist/utils/usage.js:36:31
    at Array.forEach (<anonymous>)
    at Module.captureStderr (/usr/local/lib/node_modules/create-strapi-app/node_modules/@strapi/generate-new/dist/utils/usage.js:35:37)
    at createProject (/usr/local/lib/node_modules/create-strapi-app/node_modules/@strapi/generate-new/dist/create-project.js:133:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`
![image](https://github.com/strapi/strapi/assets/29303378/11666d63-a429-4249-9346-b6afafde1fe4)

### Steps to reproduce the behavior

1. Install using `npx create-strapi-app@latest my-project`
2. Select custom installtion and select postgresql and typescript as options
3. after enter database details installtion start

**Comment by derrickmehaffy** [comment]
You have a cache problem as it shows in the error message, advise clearing your yarn cache.

**Comment by roninaruka** [comment]
@derrickmehaffy thanks, its working
