### ISSUE TITLE
SQL ER_PARSE_ERROR: [object Object]

### ISSUE THREAD

**Issue by simon-tannai** [strapi/strapi#19829]
### Required System information

- Node.js version: `v18.18.2`
- NPM version: `v9.8.1`
- Strapi version: `4.20.5`
- Database: `MySQL`
- Operating system: `darwin-x64`
- Is your project Javascript or Typescript: `JavaScript`

### Describe the bug

```
error: update `scans` set `id` = 2, `deleted_at` = '2024-01-07 15:08:34.000', `informations_de_livraison_id` = {"disconnect":[],"connect":[{"id":13,"position":{"end":true}}]}, `updated_by_id` = 12, `updated_at` = '2024-03-18 18:49:22.521' where (`id` = 2) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `connect` = '[object Object]', `updated_by_id` = 12, `updated_at` = '2024-03-18' at line 1
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `connect` = '[object Object]', `updated_by_id` = 12, `updated_at` = '2024-03-18' at line 1
```

After a fresh `oneToOne` relationship creation with the `useJoinTable` key set to `false`, I'm creating a new content from the Content Management UI.

I set a value to te `oneToOne` relation with the dropdown menu.

### Steps to reproduce the behavior

1. Create a `oneToOne` relationship with the Content-Type Builder UI.
2. Add the key `"useJoinTable"` to `false` into the `schema.json`.
3. Create a new Content with the Content Management UI.
4. Save, you should get the error.

### Expected behavior

Should create the Content without any error.

### Code snippets

The relationship definition into the `schema.json`
```JSON
    "informations_de_livraison": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::delivery-information.delivery-information",
      "useJoinTable": false
    }
```

**Comment by derrickmehaffy** [comment]
> useJoinTable

We don't support using this by users, it's designed as an internal API only.

We have no plans to allow relationships without the join table due to technical complexity requirements.
