### ISSUE TITLE
Admin Console-> go to settings leads to a blank page

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#1984]
**Informations**
- **Node.js version**:10.10.0
- **npm version**:6.4.1
- **Strapi version**:3.0.0-alpha.14.1.1
- **Database**:Postgres
- **Operating system **:Mac high Sierra

**What is the current behavior?**
When the user gets presented with the empty fields page on the Edit screen belonging to the Content Manager Plugin, and empty page gets displayed.
That is when you click on a content-type -> edit a record: you get taken to a screen where you meant to see all the attributes of the associated model. 
For some reason this specific model does not render the attribute like others, hence the go to settings button gets presented instead and when clicked this leads you to a blank page.

**Steps to reproduce the problem**
That is when you click on a content-type -> edit a record: you get taken to a screen where you meant to see all the attributes of the associated model. 
For some reason this specific model does not render the attribute like others, hence the go to settings page button gets presented instead and when clicked this leads you to a blank page.

**What is the expected behavior?**
I expect only to be pointed out to a place to look at least or a documentation of what this plugin does in the case scenario.
As otherwise it means we have to go through the whole code and try to understand what and how is done and it can take a huge amount of time to discover what is missing.

**Suggested solutions**
Provide with a documentation page for this specific plugin so we can contribute with you wth some bug fixes.
Thank you in advance.

**Comment by derrickmehaffy** [comment]
@jmchza try deleting the column: `plugin_content-manager_schema` in the table `core_store`

I'm guessing somewhere along the line something was generated properly there.

**Comment by soupette** [comment]
@jmchza did you get it working after deleting the entry in the core store?

**Comment by jmchza** [comment]
Yes resetting DB did the work, thanks.
