### ISSUE TITLE
KnexTimeoutError while transferring data from cloud

### ISSUE THREAD

**Issue by IlirEdis** [strapi/strapi#19871]
### Required System information

- Node.js version: local: v20.9.0, cloud: v18.19.1
- NPM version: 10.1.0
- Strapi version: v4.21.0
- Database: better-sqlite3
- Operating system: MacOS Sonoma 14.2.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Trying to transfer the data from cloud to local machine but i get this error after the transfer starts:

<img width="1001" alt="Screenshot 2024-03-21 at 13 36 58" src="https://github.com/strapi/strapi/assets/128377763/2a3f86ea-3bc8-4907-a608-025cd9e06cc3">

What i noticed is that i had a big video file (about 80mb) in assets, then after deleting that, the transfer went further then the first time but stuck again at this stage that you see in the screenshot.

I tried adding 

```
pool: {
        acquireTimeoutMillis: env.int(
          "DATABASE_POOL_ACQUIRE_TIMEOUT_MILLIS",
          60000
        ),
      },
```

to `database.ts` but it didnt fix the issue.

<img width="652" alt="Screenshot 2024-03-21 at 13 48 55" src="https://github.com/strapi/strapi/assets/128377763/13939b3e-7d4b-43f8-9155-fea9fe006b24">

### Steps to reproduce the behavior

//

### Expected behavior

//

### Screenshots

//

### Code snippets

//

### Additional context

I also have this when i run the development server:

<img width="735" alt="Screenshot 2024-03-21 at 13 49 51" src="https://github.com/strapi/strapi/assets/128377763/5734d9ae-12ea-409f-9c8c-d3613941bf07">

Should i add these variables on my `.env` file?
If so, whats the difference between `ADMIN_PATH` and `STRAPI_ADMIN_BACKEND_URL`?

**Comment by derrickmehaffy** [comment]
You'll want to decrease the pool max for SQLite since it's just a single file, while that shouldn't really impact you on Mac (it will on windows since windows you can only have a pool max of 1).

I would set min: 0, max: 2 for local sqlite instances

**Comment by IlirEdis** [comment]
It works, 
Thanks!
