### ISSUE TITLE
"Cannot read properties of null" random error message when trying to reach a page

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19882]
- Strapi version: 5.0.0-alpha.2

When trying to reach a page (here : Settings, CTB, then CM), I randomly get this Error page :
![image](https://github.com/strapi/strapi/assets/97893822/3054caed-c886-4a54-becb-99c97c98399f)
![image](https://github.com/strapi/strapi/assets/97893822/00c983ac-0be2-4121-9538-07ede1af1867)
When refreshing, I can finally access my page.

**Comment by derrickmehaffy** [comment]
Wasn't able to reproduce in beta.4, closing
