### ISSUE TITLE
Can't leave JSON empty in Content Manager

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1989]
**Informations**
- **Node.js version**:  v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: mongodb
- **Operating system**: macOS

**What is the current behavior?**
Can not leave JSON fields empty when using Content Manager. It keeps reminding 'This doesn't match JSON format'.

**Steps to reproduce the problem**
1. Add a new field in JSON format in Content Type Builder.
2. Open in Content Manager and save.

![wx20180919-151221](https://user-images.githubusercontent.com/3782817/45784824-15c46280-bc1f-11e8-9e4d-fd9cfb668f96.png)

**What is the expected behavior?**
I expect JSON format fields support null or undefined, just like other formats. Thanks.

**Comment by Blacknosaur** [comment]
You can fill the JSON field with {} but yes, it would be nice the possibility of leaving it blank

**Comment by derrickmehaffy** [comment]
It should automatically fill with {} at least it has previously unless something has changed.

**Comment by soupette** [comment]
Please use the latest version of strapi this has been fixed I'm closing the issue.
