### ISSUE TITLE
Many security vulns showing with npm install/audit on a clean install?

### ISSUE THREAD

**Issue by psoleckimoj** [strapi/strapi#19899]
### Required System information

- Node.js version: v20.11.0
- NPM version: 10.4.0
- Strapi version: 4.21.0 community edition
- Database: Postgres 15
- Operating system: Alpine Linux (Docker node 20 Alpine image)
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

There are various issues when doing a clean `npm i` on strapi community edition. Currently 1 medium security vuln and 15 high security vulns showing if I don't use `override` in the `package.json`

### Steps to reproduce the behavior

1. Download strapi
2. Run `npm i`

### Expected behavior

There should be zero security issues

### Code snippets

```
rm -rf ./yarn.lock && rm -rf ./node_modules && rm -f ./package-lock.json && npm i

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @koa/router@10.1.1: **IMPORTANT 10x+ PERFORMANCE UPGRADE**: Please upgrade to v12.0.1+ as we have fixed an issue with debuglog causing 10x slower router benchmark performance, see https://github.com/koajs/router/pull/173
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated buildmail@3.10.0: This project is unmaintained

added 1577 packages, and audited 1578 packages in 2m

268 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (1 moderate, 15 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

### Additional context

I've attempted to report a security vuln for one module and the issue was closed as I didn't provide a way to show how it affects strapi.

I believe all that is required is to update some dependencie and minor versions on some of those. `overrides` can be used in `package.json` for some of them but it's not really the desired way of doing this.

I understand you're priority is v5 but this has been a consistent issue and putting me off wanting to move to the paid model yu have.

**Comment by derrickmehaffy** [comment]
Not a valid bug report, we understand there are some dependencies showing as vulnerable and we will update them in due time. We focus primarily on vulnerabilities that are proven to have an impact on Strapi applications and not just for the sake of updating dependencies. Strapi should not and will not always run on bleeding edge dependencies as that path leads to instability.

**Comment by psoleckimoj** [comment]
Exactly how is updating patch releases of modules you use "bleeding edge"? I suspect you are concentrating on your paid for cloud solutions and v5 with little regard to existing community customers whose security pipelines break because you won't spend time updating modules.

If you have a decent regression pipeline then what's the problem in updating? In the time it took you to reply and close this bug you could've updated it.

**Comment by derrickmehaffy** [comment]
> Exactly how is updating patch releases of modules you use "bleeding edge"? I suspect you are concentrating on your paid for cloud solutions and v5 with little regard to existing community customers whose security pipelines break because you won't spend time updating modules.
> 
> If you have a decent regression pipeline then what's the problem in updating? In the time it took you to reply and close this bug you could've updated it.

I'd invite you to go look at our pull requests, mine specifically and correct your tone.

We dont just take some audit report at face value, we actually test all of them to see if we are impacted and if we aren't they are considered a lower priority.

**Comment by psoleckimoj** [comment]
> I'd invite you to go look at our pull requests, mine specifically and correct your tone.
> 
> We dont just take some audit report at face value, we actually test all of them to see if we are impacted and if we aren't they are considered a lower priority.

I apologise for jumping down your throat about this. It's just I noticed I have a growing manual `overrides` block in Strapi's `package.json` and it's not something I have on other external dependencies, especially since we get alerted every day about projects failing npm audit.

**Comment by derrickmehaffy** [comment]
I agree it's important to check the audit report but more than half the time those don't really apply to us.

We focus on updating dependencies with vulnerabilities that actually matter rather than just updating for the sake of having a clear audit report.

The CVE system was designed to inform not force people to upgrade nor was it designed to push fear or pressure.

It's possible and common for CVEs to be issued maliciously (eg my opinion on the @koa/cors one) but in this case were weren't even impacted by the vite (in v4 it's not even used normally, it's there as an expirmental option) or webpack-dev-server ones that were recently reported.

---

We are human like anyone else but we refuse to just blindly update dependencies for the sake of having a false sense of security from the npm audit system. It's proven several times over the years to be extremely unreliable.
