### ISSUE TITLE
npm install (BROKEN) V5

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#19903]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

`npm i` no longer works

### Steps to reproduce the behavior

1. run `npx create-strapi-app@beta my-project`
2. run `npm i`
3. See error

### Expected behavior

for it to run witout errors 

### Screenshots

![2f164f194e3d027c24add2267faeeb75](https://github.com/strapi/strapi/assets/34578426/0dfdafb5-15c8-43cc-aa4e-af3d157e3cc0)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by jaimesalebe** [comment]
Same problem.

**Comment by Boegie19** [comment]
@jaimesalebe workaround is using yarn
