### ISSUE TITLE
Upload plugin caused app no more launch!  Cannot read properties of undefined (reading 'service') 

### ISSUE THREAD

**Issue by longnight** [strapi/strapi#19907]
- Node.js version: 20.11
- Strapi version: v4.19.0
- Database: MySQL
- Operating system:  Ubuntu 20
- Is your project Javascript or Typescript:  Typescript

### Describe the bug

Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

```
┌─────────┐
│                                                                                                                              │
│   TypeError: Cannot read properties of undefined (reading 'service')                                                         │
│       at Object.<anonymous> (~/prj/dist/src/api/upload-asset/services/upload-asset.js:9:46) 

```

that `upload-asset.js ` was compiled from my `upload-asset.ts`, and the line it complaining is like: 

```
const uploadService = strapi.plugin('upload').service('upload')
```

The logic of this line of code was fine before; however, after I deleted the `/node_modules` and reinstalled these dependencies, an error occurred here.

Edit: 

This errors seem occupied when I delete some ContentTypes collection from the admin page. So I have to rollback code to let strapi app launchable again.

adding version details.

**Comment by Boegie19** [comment]
please be more spesific about the strapi version v4 is not spesific enough

**Comment by longnight** [comment]
> please be more spesific about the strapi version v4 is not spesific enough and fill in the empty fields

thank, now updated.

**Comment by longnight** [comment]
Fixing this issue by: put this line ` const uploadService = strapi.plugin('upload').service('upload') ` inside the function that used it , instead of place this line at top of the module/file.
