### ISSUE TITLE
No admin button on production configuration

### ISSUE THREAD

**Issue by yanckst** [strapi/strapi#19902]
## Bug report

I'm not sure if it's a bug or a missing configuration for the production, but the admin button is not showing in the production build on strapi.

### Required System information

- Node.js version:  18.16.0
- NPM version: yarn@1.22.19
- Strapi version: 4.21.0
- Database: sqlite
- Operating system: Windows 10
- Is your project Javascript or Typescript: Typescript

```
┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Fri Mar 22 2024 12:15:35 GMT-0400 (heure avancé… │
│ Launched in        │ 971 ms                                           │
│ Environment        │ production                                       │
│ Process PID        │ 36736                                            │
│ Version            │ 4.21.0 (node v18.16.0)                           │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
└────────────────────┴──────────────────────────────────────────────────┘
```

### Describe the bug

Using `NODE_ENV=production` to start strapi doesn't show the admin button

#### Create a default user
1. Create a strapi CMS project on typescript by doing `npx create-strapi-app my-project --quickstart`
2. Navigate to `my-project` folder project
3. Install the dependencies by doing `yarn`
4. Start the project by using `yarn develop`
5. On the Welcome page, create a user and save it.
6. Kill the process

#### Navigating to the dashboard page
7. Go to the `env` file and change the `HOST` for `localhost` instead of `0.0.0.0`
8. Go to the `package.json` file
9. Change the `develop` script for `NODE_ENV=production strapi develop`
10. Start the script by doing `yarn develop`

### Actual behavior

The application shows that the server is running, but there's no blue admin button
![image](https://github.com/strapi/strapi/assets/30554401/61f5092b-45e4-4356-a8cc-8c7b53ebd75a)

**NOTE:** Adding `/admin` in the URL works fine, it's just the missing button in the UI

### Expected behavior

We should see the admin button like the development environment

#### Using the production NODE_ENV=production
![image](https://github.com/strapi/strapi/assets/30554401/61f5092b-45e4-4356-a8cc-8c7b53ebd75a)

#### Using the production NODE_ENV=development
![image](https://github.com/strapi/strapi/assets/30554401/7ccd5e9b-c8fa-4768-be0b-b9438fba4dda)

### Code snippets

No code snippet

### Additional context

I have another application released and living in an AzureWebApp. It does the same problem with the missing admin button. On localhost everything works, it's just in a production config that the button is missing.

I thought the problem was in my other project, so I decided to start a new app and I noticed it does the same behavior.

Is it a bug or a missing configuration on my hand?

Thanks!

**Comment by Eventyret** [comment]
Don't think this is a bug, this is intended.
You don't want to advertise your admin server for security purposes on a production server while on development it's fine to show it for easy access.

**Comment by yanckst** [comment]
Okay, I understand that this is not designed.

In my context, I was using Strapi as a CMS and the admin panel is accessible for some users. The application is self-hosted on an Azure WebApp where only logged users on the machine can access the WebApp.

I just wanted to have the same button in dev to be accessible for those users, instead of adding `/admin` in the URL.

Thanks for the quick reply!
