### ISSUE TITLE
Removing a relation from a draft is not saved after publishing

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19910]
In a content type with a relation to another content type
- edit the draft removing the relation 
- publish
- the publish button is still active
- refresh the page
- the relation still appears on the draft

Tested on 0.0.0-experimental.94632b9dc1ff6c9600db6db51cd6dd2d693f5204 and reproduced.

**Comment by Marc-Roig** [comment]
This seems to be fixed (5.0.0-beta.13)
