### ISSUE TITLE
Cannot select multiple images in multi media field (strapi v5 beta)

### ISSUE THREAD

**Issue by manuel-schoebel** [strapi/strapi#19944]
## Bug report
I have this simple images field that should allow multiple images. Schema is:

```
    "images": {
      "type": "media",
      "multiple": true,
      "required": false,
      "allowedTypes": ["images"],
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    },
```

When I want to select multiple images in the "Add new assets" -> "Browse" tab, the UI will not let me select multiple ones. I can only select one. This way I cannot select or add multiple images.

Even if i drag multiple images on an empty images field, after they were uploaded only one is selected.

### Required System information

Launched In: 328 ms
Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.1
Node/Yarn Version: npm/9.8.1 node/v18.18.2 darwin arm64 workspaces/false
Edition: Community
Database: sqlite
Typescript

### Steps to reproduce the behavior

1. create collection with multi image field
2. create one
3. drag 2 images into the field
4. see that you only ever can have one selected

### Expected behavior

Multiple images should be selectable.

Love the new data schema of v5 😍

**Comment by alexandrebodin** [comment]
this is fix in the latest beta :)
