### ISSUE TITLE
Any providers return "This provider is disabled". 

### ISSUE THREAD

**Issue by olehvoitenko** [strapi/strapi#1994]
**Informations**
- **Node.js version**: 8.11.3
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: Mongo
- **Operating system**: MacOS

**What is the current behavior?**
I am trying to connect the providers such a google and facebook. Unfortunately, I always get the error: 
`{"statusCode":400,"error":"Bad Request","message":"This provider is disabled."}`. 

I have searched for the reason and understand that in the DB I have correct set parameters. 
Google and FB are enabled. 

I went over the code and understand that the reason in `Auth.js` file: 

[Link to the image](http://prntscr.com/kwqmx1)

From the first point of view everything working correctly, but if we debug, will understand that those lines of the code have been called twice. 

[Link to the debug image](http://prntscr.com/kwqnmi)

**Steps to reproduce the problem**
1. Enable Providers;
2. Try to use according to the instructions;
3. Will get the error; 

**What is the expected behavior?**
1. Enable Providers;
2. Try to use according to the instructions;
3. Get the user and JWT token; 

**Suggested solutions**
Debug `Auth.js` file and try to understand why this happens. 

If anyone can help with it, will be appreciated.
Thanks!

**Comment by lauriejim** [comment]
Hello @olehvoitenko , did you try with this provider login example ?
https://github.com/strapi/strapi-examples/tree/master/login-react

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
