### ISSUE TITLE
D&P x Relations : no Draft relations displayed when switching from draft to published tabs

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19957]
Version : 5.0.0-beta.0 

Description : 

No relations are displayed on Draft version, when switching back and forth between draft and published tabs

See Loom here : 
https://www.loom.com/share/838af2621e4842f08aa331103c86273e?sid=93658aa7-f8de-463b-9565-f05bcf6caebe

This does not appear when relation field is in Published status

Might be related to https://github.com/strapi/strapi/issues/19959

**Comment by Marc-Roig** [comment]
this looks to be fixed as in the latest beta (13)
