### ISSUE TITLE
Enabling D&P on a CT : draft documents get the "modified" status instead of "draft"

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19956]
Version : 5.0.0-beta.0

Description : 
Enabling the D&P on a content type that didn’t have it enabled before makes its draft entries appear as “modified” (even if the content matches with the published version)

Steps to reproduce : 
Create a CT with D&P disabled
Create some documents in CM for this CT
Go back to CTB, enable D&P for this CT, save
Go back to CM : previously created documents have the Modified status instead of Draft status

![image](https://github.com/strapi/strapi/assets/97893822/de99cfc0-0321-4e99-bf22-26e98d3d989c)

**Comment by Marc-Roig** [comment]
This is fixed as of the latest beta (13) status should be "published" when enabling D&P on a content type
