### ISSUE TITLE
Disabling Draft & Publish modal doesn't close or doesn't appear

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19953]
Description : 

Using 5.0.0-beta.0 :
Disabling draft&publish on a content type in the CTB: it asks for confirmation, but once I click on “confirm” the modal doesn’t close (I can proceed by clicking somewhere in the surrounding space)

Steps to reproduce : 
Go to the CTB section
Create a new Collection Type
In Advanced settings tab, uncheck "Draft&Publish" checkbox
Get the confirmation popup
Click "Confirm"

https://www.loom.com/share/7bc97cc547354ba4a98fee2b609f4ba9?sid=c0d00802-03a3-4de1-aa2c-b792e07f718f

Re-tested today on v5/main : confirmation popup is not displayed anymore (but should be)

**Comment by SalahAdDin** [comment]
In my case, It didn't close the modal:

![Image](https://github.com/strapi/strapi/assets/5034215/455bcbeb-b509-4602-bf19-45029f80face)

**Comment by alexandrebodin** [comment]
FIx in latest beta

**Comment by SalahAdDin** [comment]
Confirmed, it is fixed on the RC.
