### ISSUE TITLE
Draft relations are not displayed correctly

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19959]
Version :  5.0.0-beta.0

Description : 

With a content type having a relation to another content type → select a relation to a draft document → publish → switch to the publish version = the relation doesn’t appear to be set; 
Then, switch back to draft = the relation doesn’t appear to be set; then switch to public = the relation appears.

Reproduced also like this : 
 Published tab → Relations weren’t set / switch to Draft tab → Relations were set / switch to Published tab → Relations were set / switch to Draft tab → Relations weren’t set anymore !

https://www.loom.com/share/838af2621e4842f08aa331103c86273e?sid=a2a1b44b-1904-4832-a96c-5344ce5412be

Might be related to : https://github.com/strapi/strapi/issues/19957

**Comment by MarionLemaire** [comment]
Issue remaining in latest beta (tested today on `v0.0.0-experimental.a53a4b1c8f7981a689823cdd719105671e1c6392` (beta10)

**Comment by Marc-Roig** [comment]
If the target relation is only a draft, it will not appear in the published tab! only when you publish the other side you will see the relation appearing in the published tab :)
