### ISSUE TITLE
API tokens and Transfer tokens “Create new token” have a text decoration

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19961]
Version : 5.0.0-beta.0

API tokens and Transfer tokens “Create new token” have a text decoration (underlined with blue)

![image](https://github.com/strapi/strapi/assets/97893822/877a5a81-0878-4093-b059-f3fdbe0e23fd)

**Comment by sajdakabir** [comment]
@MarionLemaire, I would like to work on this issue.

**Comment by laurenskling** [comment]
This is also present in v4 :) Also on the transfer tokens screen. Not on the webhooks screen tho

**Comment by derrickmehaffy** [comment]
> @MarionLemaire, I would like to work on this issue.

We don't assign issues, you just open the pull request

**Comment by derrickmehaffy** [comment]
Looks like it's fixed in beta.4, closing
