### ISSUE TITLE
When enabling i18n on an existing CT with existing published versions on by default locale, it creates a Draft in the new locale automatically 

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#19960]
Version : 5.0.0-beta.0

Description

When enabling i18n on an existing CT with existing published versions on by default locale, it creates a Draft in the new locale automatically 

Steps To reproduce

- Create a Content type without i18N
- Create documents with this Content Type, save and publish them
- Go to settings, in Internationalization, add a new locale,
- Go to CTB, enable i18n for the Content Type above (Edit icon next to CT title > Advanced settings tab > check Internationalization checkbox), Finish
- Go to CM, go to an existing document for this CT in by default locale
- In the right upper corner, check the dropdown : there’s already a Draft version for the new locale you just created

Expected behaviours instead

Draft version label shouldn’t already exist

Discussed with @Marc Roig Campos : already exists in V4

**Comment by Marc-Roig** [comment]
Checked, this is not the case in v4.
Also, I do think this is a cosmetic issue, but one we should fix regardless (if its not intended), empty locales are displayed as Draft in the locale dropdown 

(Second locale does not exist)
![image](https://github.com/strapi/strapi/assets/20578351/9f977a45-d228-4ac3-9550-b5453c0df4ce)

@lucasboilly was this intended?

**Comment by yanniskadiri** [comment]
Lucas worked on some designs, let's go with [this option](https://www.figma.com/proto/Tt8uHuQezEP0CsWunbulb5/Draft-%26-Publish?page-id=3390%3A70176&node-id=6748-38808&viewport=544%2C224%2C0.1&t=7wnkIa6TjjvQNJCG-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=6748%3A38808&show-proto-sidebar=1)

**Comment by simotae14** [comment]
I am gonna close it because it was fixed by @Feranchz with this Pr https://github.com/strapi/strapi/pull/21199 👏🏽
