### ISSUE TITLE
Can`t create Content Type

### ISSUE THREAD

**Issue by rapidexact** [strapi/strapi#1996]
**Informations**
- **Node.js version**: 10.10.0
- **npm version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongoDB 3.1.5
- **Operating system**: MacOS 10.13.6, Linux 4.9.93

**What is the current behavior?**
Blank page after click on "Add content type", or after click on edit something.
A lot of actions generates folowing error:
Uncaught Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

**Steps to reproduce the problem**
1. Go to /admin page
2. Try co create new Content Type

**What is the expected behavior?**
After clicking on "Add content type" i should see create content type form

**Suggested solutions**

**Comment by soupette** [comment]
Can you upgrade to 14.1.1?

**Comment by rapidexact** [comment]
> Can you upgrade to 14.1.1?

Thanks a lot.
It did help.

**Comment by Rilliano** [comment]
How do u upgrade strapi?

**Comment by derrickmehaffy** [comment]
@Rilliano 

Either Migration Guides: https://github.com/strapi/strapi/wiki

Or my method: https://github.com/strapi/strapi/issues/1880

**Comment by mkasprzyk** [comment]
@soupette I've got the same issue in v3.0.0-alpha.14.3 🐙 
The same error occurs, when i want to chose Role from dropdown menu for new user.

**Comment by gagnonsimon** [comment]
I've got the same issue with v3.0.0-alpha.17 I can add on dev mode but when I go on prod mode nothing show up for add field.

**Comment by seanmavley** [comment]
@simoncrypta Same here, and I don't think it has anything to do with permissions.

In prod, the "Configurations" and "Content Type Manager" tabs are missing. They're not showing.
