### ISSUE TITLE
[v5] (admin panel) Dialog modal not closing after deleting RBAC role

### ISSUE THREAD

**Issue by MattieBelt** [strapi/strapi#19962]
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-beta.1
- Node/Yarn Version: yarn/1.22.19 npm/? node/v18.18.0 darwin arm64
- Edition: Community
- Database: sqlite
- Browser: Chrome
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The dialog modal doesn't close after a successful deletion of a RBAC role.

### Steps to reproduce the behavior

1. `npx create-strapi-app@beta strapi-v5-delete-role --quickstart`
2. Create super admin
3. Go to Settings > ADMINISTRATION PANEL > Roles
4. Delete role Editor

### Expected behavior

Dialog modal should close after role deletion.

### Screenshots

https://github.com/strapi/strapi/assets/31662805/658a4948-261e-4d1a-984a-36ccdd379053

**Comment by remidej** [comment]
Already fixed by #20000
