### ISSUE TITLE
v5: required relation errors the UI

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#19976]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.1
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.20.0 darwin arm64
Edition: Community
Database: sqlite

### Describe the bug

Having a `relation` set to `required` results in an error:
<img width="664" alt="Scherm­afbeelding 2024-03-31 om 19 32 07" src="https://github.com/strapi/strapi/assets/6753724/db6299ac-deb1-48ee-bf52-242cdcdb77ac">

### Steps to reproduce the behavior

1. create a relation and set `required: true`
2. go to the entry
3. save
4. error shows at relation selector

### Expected behavior

no error, allowed to save, required

**Comment by derrickmehaffy** [comment]
Throws a proper error in beta.4, closing:



![Image](https://github.com/strapi/strapi/assets/8593673/72bdd4c4-cba4-4089-a23e-255a08b657ab)

**Comment by laurenskling** [comment]
Hey @derrickmehaffy , thanks for working on it. 
It throws a proper error when not selecting a required relation, yes.
But it also throws errors when you *do* select required relations.

Another screenshot: 
<img width="593" alt="Scherm­afbeelding 2024-05-10 om 16 43 35" src="https://github.com/strapi/strapi/assets/6753724/7f5d400e-1560-4ab5-9aa4-46127238cb3d">

tested on beta.7

**Comment by alexandrebodin** [comment]
did you set the relation to required in the schema ? we removed this from the UI as we do not support this for now, seems we have to remove some code to ignore it in the validators @Marc-Roig

**Comment by laurenskling** [comment]
I don't use the content type builder, but create my content types manually, if that is what you mean.

**Comment by alexandrebodin** [comment]
Yes, indeed, required relations are not something we implemented I think you are in a loop hole where we apply a generic validator that should be there as we don't really support required relations

**Comment by Marc-Roig** [comment]
Indeed @alexandrebodin we should prevent relations to be set as required in the schema, is not something we support atm.

**Comment by derrickmehaffy** [comment]
> Yes, indeed, required relations are not something we implemented I think you are in a loop hole where we apply a generic validator that should be there as we don't really support required relations 

Yeah that loophole existed since v3 (albeit that it did work in v3/v4 mostly)

**Comment by alexandrebodin** [comment]
Ok so for whever does the fix: 

- Disallow requried options in the relation schemas
- Remove the require validator in entity-validator for relations
