### ISSUE TITLE
Cannot Entry to Repeatable Component inside Another Repeatable Component

### ISSUE THREAD

**Issue by ayhankerim** [strapi/strapi#19985]
### Required System information
- Node.js version: v18.17.0
- NPM version: 9.4.1
- YARN version: 1.22.19
- Strapi version: 5.0.0-beta.1
- Database: sqlite
- Operating system: darwin-x64 - MacOS Sonoma 14.2.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I created a new BETA install with "npx create-strapi-app@beta beta --quickstart". To manage multiple menus, I created repeatable component named as Menu, inside that I added a text field to name this menu, and another repeatable component to add menu items which have link name and link target fields. Of course, my role is Super Admin and checked permissions. 

### Screenshots

<img width="1448" alt="image" src="https://github.com/strapi/strapi/assets/5948982/bf2505d0-3b82-421f-93a7-3d7876bac432">
<img width="1521" alt="image" src="https://github.com/strapi/strapi/assets/5948982/d59b1de2-e946-4ef1-b7f9-c9df572a563a">
<img width="1519" alt="image" src="https://github.com/strapi/strapi/assets/5948982/a6237e45-162a-44dd-a5cf-a440917ae04c">

**Comment by joshuaellis** [comment]
Solved in the next beta release.
