### ISSUE TITLE
strapi new does not work

### ISSUE THREAD

**Issue by GlennCarroy** [strapi/strapi#1998]
**Informations**
- **Node.js version**: Node: 10.11 
- **npm version**: NPM: 6.4.1
- **Strapi version**: v3 alpha 14.1.1
- **Database**: mongo 4.0
- **Operating system**: windows

**What is the current behavior?**
When entering `strapi new` , the project creation do not go over "project name" assignation

**Steps to reproduce the problem**

**What is the expected behavior?**
Project creation should run properly

**Suggested solutions**
Please help ^^

**What is the expected behavior?**

**Comment by heyimbrucelee** [comment]
Had same issue, stuck after choosing database without any informations/errors.
It may be related to nodejs version.
Fun fact strapi new works on nodejs 9.4.0 ( but they suggest NodeJS >= 10.x) so probably lead to other issues

**Comment by NickBolles** [comment]
It depends on if it is hanging at the database prompt or not. If it is it's a node 9+ compatibility issue, see #1281  and multiple others. 

If it's the database connection check it should be fixed by #1941 

Also, admin build wont build on windows, I'm putting together a PR for this. see #2004

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1281

Recommend closing
