### ISSUE TITLE
v5 plugin contentType lifecycles are broken

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#19983]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.1
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.20.0 darwin arm64
Edition: Community
Database: sqlite

### Describe the bug

lifecycles registered on contentTypes in plugins don't run anymore 

### Steps to reproduce the behavior

1. create a contentType in a plugin
2.
```
my-plugin/server/content-types/vehicle/lifecycles.js
...
module.exports = {
  beforeCreate,
  beforeUpdate,
};


my-plugin/server/content-types/index.js
'use strict';

const vehicle = require('./vehicle/vehicle');
const vehicleLifecycles = require('./vehicle/lifecycles');

module.exports = {
  vehicle: { schema: vehicle, lifecycles: vehicleLifecycles },
};
```
3. create or update a vehicle
4. see that the lifecycle is not triggered

### Expected behavior

registering lifecycles in plugin contentTypes seem to be broken in v5
`strapi.db.lifecycles.subscribe({` still work tho.

**Comment by innerdvations** [comment]
This may have been fixed with https://github.com/strapi/strapi/pull/20975
