### ISSUE TITLE
Problems with savingSingle Type content on another locale

### ISSUE THREAD

**Issue by petrovicdorde** [strapi/strapi#19997]
I have the following issue:
My default language is Serbian (sr), I fill out my Single Type with data, and when I switch to another language and fill in the data, then click Save, I receive the following message:
"Warning:
1 relation(s) of type api::search.search associated with this entity do not exist".

Can someone help me?

**Comment by nevosol** [comment]
This seems to be bug since version 4.20.3, it must be fixed ASAP, otherwise it's unusable.
Version 4.20.2 is working fine!
