### ISSUE TITLE
Decimal field saves an error when empty

### ISSUE THREAD

**Issue by Blacknosaur** [strapi/strapi#2000]
**Informations**
- **Node.js version**: 10.5
- **npm version**: 6.1.0
- **Strapi version**: Alpha 14
- **Database**: MongoDB v3.6.5
- **Operating system**: Amazon Linux AMI release 2018.03

**What is the current behavior?**
When sending a POST request to a model with empty decimal fields inside saves the object
`{
   kind: "The value you passed should be number"
   message: "Cast to The value you passed should be number failed for value "undefined" at path "undefined""
   name: "CastError"
   stringValue: ""undefined""
}` instead of null. If the field is integer instead of decimal there's no problem.

**Steps to reproduce the problem**
Just create a model with a decimal field and make a POST request to it without sending any data to this field.

**What is the expected behavior?**
If the field is sent empty it should be filled with null, like every other data type.

**Suggested solutions**
It seems to be a problem with the decimal data type and Mongoose but I don't know how to fix it.

**Comment by JZFLei** [comment]
This should be fixed in the next release when #1924 gets merged, hopefully the end of the week.

**Comment by JZFLei** [comment]
For the time being, if you really want it fixed immediately, edit `packages/strapi-hook-mongoose/lib/utils/index.js` if you're building from source or `node_moduels/strapi-hook-mongoose/lib/utils/index.js` if you are wanting to hotfix your project.

Replace the contents with:

```
'use strict';

/**
 * Module dependencies
 */

module.exports = mongoose => {
  var Decimal = require('mongoose-float').loadType(mongoose, 2);
  var Float = require('mongoose-float').loadType(mongoose, 20);

  return {
    convertType: mongooseType => {
      switch (mongooseType.toLowerCase()) {
        case 'array':
          return Array;
        case 'boolean':
          return 'Boolean';
        case 'binary':
          return 'Buffer';
        case 'date':
        case 'datetime':
        case 'time':
        case 'timestamp':
          return Date;
        case 'decimal':
          return Decimal;
        case 'float':
          return Float;
        case 'json':
          return 'Mixed';
        case 'biginteger':
        case 'integer':
          return 'Number';
        case 'uuid':
          return 'ObjectId';
        case 'email':
        case 'enumeration':
        case 'password':
        case 'string':
        case 'text':
          return 'String';
        default:
      }
    },
  };
};
```

**Comment by lauriejim** [comment]
Merged and fixed

**Comment by marcioferlan** [comment]
The solution works for MongoDB, but I have the same issue for a PostgreSQL database. I'm not able to clear a decimal field and save it in the admin app. I'm able to set the value to null using a GraphQL mutation though. How should I fix it? Thanks.

**Comment by lauriejim** [comment]
Hello! You will have to check how `strapi-hook-bookshlef` manage it.
