### ISSUE TITLE
[v5] Root path not redirecting to configured admin.url

### ISSUE THREAD

**Issue by MattieBelt** [strapi/strapi#20013]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.1
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.18.0 darwin arm64
Edition: Community
Database: sqlite

### Describe the bug

Since the defaultIndex page is removed, the root path redirects you to /admin while not respecting the admin.url config.

### Steps to reproduce the behavior

1. `npx create-strapi-app@beta strapi-root-redirect --quickstart`
2. Add an `'/dashboard'` or `'https://example.com'` to the `url` option in config/admin.js
3. Navigate to http://localhost:1337
4. Incorrectly redirected to hardcoded /admin

### Expected behavior

Redirect to configured relative or absolute path `admin.url`.

### Screenshots

![image](https://github.com/strapi/strapi/assets/31662805/39dc719e-782d-4692-a64a-4d482d65940c)

### Code snippets

```js
module.exports = ({ env }) => ({
  // (..)
  url: '/dashboard',
});

```
### Additional context

Also missing breaking change documentation for removal of `defaultIndex`.

**Comment by alexandrebodin** [comment]
PR merged
