### ISSUE TITLE
V5: Languages are reset when upgrading strapi

### ISSUE THREAD

**Issue by smoove** [strapi/strapi#20025]
### Required System information
- Node.js version: v18.18.2
- Yarn version: 1.22.19
- Strapi version: v5.0.0-beta.2
- Database: sqlite
- Operating system: Arch Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When i updated strapi from v5.0.0-beta.1 to v5.0.0-beta.2, the languages i configured where reset.
Settings > Internationalization shows only english (default), but i previously changed it to be german (default) & english.

Translations for content types i translated earlier are still accessible via the REST API (?locale=de), but not in the admin panel.

After setting up the languages again (german (default) & english) everything seems to work fine again.

### Steps to reproduce the behavior

1. Install v5.0.0-beta.1
2. Set up languages under Settings
3. Upgrade to v5.0.0-beta.2
4. Languages are missing under Settings > Internationalization

### Expected behavior

Languages settings to survive version upgrades.

### Screenshots

N/A

### Code snippets

N/A

### Additional context

N/A

**Comment by Convly** [comment]
Hey, thanks a lot for opening an issue!

This should definitely not happen, we're gonna investigate this as soon as possible :slightly_smiling_face:

**Comment by Marc-Roig** [comment]
We have raised this issue as critical and we are taking a look at this.

We introduced an improvement to handle long names on db , and it is accidentally affecting the table we use to store locales.
