### ISSUE TITLE
v5: rich-text blocks slate editor crashes when hit `Enter` key to new line and hit `save`

### ISSUE THREAD

**Issue by uptonking** [strapi/strapi#20028]
### Required System information

- Node.js version: v20.12.0
- NPM version: 10.1.0
- Strapi version: v5.0.0-beta.2
- Database: sqlite
- Operating system: ubuntu 22.04
- Is your project Javascript or Typescript: ts

### Describe the bug

- content manager edit view page with rich-text blocks slate editor crashes when hit `Enter` key to new line and hit `save`

### Steps to reproduce the behavior

1. npx create-strapi-app@beta test-page11 --quickstart  --ts
2. npm run develop
3. create a new collection type, with a plain text field `title11` and rich text blocks field `rich11`
4. in content manager, type in the `rich11` slate editor, hit `Enter` key to new line and hit `save`, the page will crash
5. if no crash happens, try to reproduce by hitting `Enter` key twice and hit `save`, then hitting `Enter` key and hit `save`

### Expected behavior

- in rich text slate editor, hit `Enter` key to new line and hit `save`, the content should be saved normally

### Screenshots

![image](https://github.com/strapi/strapi/assets/11391549/141ec8c4-daf8-4bea-b567-522e89221ef5)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

- I've test on v4. v4 doesn't have this issue

**Comment by SalahAdDin** [comment]
Does it use Slate? Nice to know it
