### ISSUE TITLE
Could not resolve dependency: npm WARN peer @strapi/admin@"^5.0.0" from the root project 

### ISSUE THREAD

**Issue by code4reason** [strapi/strapi#20031]
### Required System information
- Node.js version: 18.19.1 & 20.12.1
- NPM version: 10.2.4 & 10.5.0
- Strapi version: 5.0.0-beta.2
- Database: "better-sqlite3": "9.4.3",
- Operating system: Mac OS Ventura 13.1
- Is your project Javascript or Typescript: Default install using: npx create-strapi-app@beta beta --quickstart

### Describe the bug
Running npx create-strapi-app@beta beta --quickstart 
Installation runs for a few seconds and then end up trying to resolve dependency as described in title.
The folder with content is created, byt installation does not finish.

Tried two different Node/npm versions.

### Steps to reproduce the behavior

1. Running npx create-strapi-app@beta beta --quickstart 
2. Watch the console log
3. See error

### Expected behavior

Working instance of Strapi 5 beta

### Screenshots

Just this text from the console: Installing dependencies: npm WARN  npm WARN Could not resolve dependency: npm WARN peer @strapi/admin@"^5.0.0" from the root project

### Code snippets

Standard code/content when running:  npx create-strapi-app@beta beta --quickstart 

### Additional context

n/a

**Comment by nino-magazinovic** [comment]
Yeah,

The issue is in the content-manager 5.0.0-beta.2 peerDependencies at https://github.com/strapi/strapi/blob/v5.0.0-beta.2/packages/core/content-manager/package.json#L115

Works with `npm install --legacy-peer-deps` or add permanent `legacy-peer-deps=true` in `.npmrc`

**Comment by joshuaellis** [comment]
this is solved in the latest beta `3`.
