### ISSUE TITLE
Can't deploy existing project inside docker-container

### ISSUE THREAD

**Issue by rapidexact** [strapi/strapi#2003]
**Informations**
- **Node.js version**: 10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: MongoDB 3.1.5
- **Operating system**: Linux 4.9.93 (node:alpine docker image)

**What is the current behavior?**
`
ub@0.1.0 start /app
api_1  | > node server.js
api_1  |
api_1  | internal/modules/cjs/loader.js:583
api_1  |     throw err;
api_1  |     ^
api_1  |
api_1  | Error: Cannot find module 'immutable'
api_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
api_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
api_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
api_1  |     at require (internal/modules/cjs/helpers.js:20:18)
api_1  |     at Object.<anonymous> (/app/plugins/content-type-builder/services/ContentTypeBuilder.js:7:31)
api_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
api_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
api_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
api_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
api_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
api_1  | npm ERR! code ELIFECYCLE
api_1  | npm ERR! errno 1
api_1  | npm ERR! ub@0.1.0 start: `node server.js`
api_1  | npm ERR! Exit status 1
api_1  | npm ERR!
api_1  | npm ERR! Failed at the ub@0.1.0 start script.
api_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1  |
api_1  | npm ERR! A complete log of this run can be found in:
api_1  | npm ERR!     /root/.npm/_logs/2018-09-22T18_24_16_365Z-debug.log
`

**Steps to reproduce the problem**

1. Create Dockerfile with following content
`
FROM node:alpine
WORKDIR /app
COPY ./strapi-app /app 
RUN npm install 
EXPOSE 1337 
CMD ["npm", "start"] 
`
2. try to build this image

**What is the expected behavior?**
Strapi server starts properly

**Comment by NickBolles** [comment]
Looks like the same error message as #1840, which is also in a docker container on gitlab-ci. Duplicate?

**Comment by rapidexact** [comment]
@NickBolles Looks similar. But versions of node, npm, strapi are lower than in requirements.

**Comment by rapidexact** [comment]
@johncalvinroberts `npm run setup` also throws error. 
Something with cross-env dependency in `strapi-helper-plugin/node_modules/.bin/` directory.

**Comment by derrickmehaffy** [comment]
Unless you are building from source, `npm run setup` should not be run. Instead use `npm install` which will trigger some pre/post scripts

**Comment by rapidexact** [comment]
@derrickmehaffy I have tried both options.

**Comment by johncalvinroberts** [comment]
I resolved my issue by making sure the `admin/admin/build` folder is copied into the docker container, then using `npm install --production && npm start` to start the app

**Comment by MoQ93** [comment]
I think it's the same issue as this:
https://github.com/strapi/strapi-docker/issues/49
I resolved this by adding `.npmrc` file to the home directory in the docker-container with the flag `unsafe-perm` set to `true`

**Comment by jkbaseer** [comment]
@MoQ93 Good to know that you have solved this. Could you share a bit explanation on how you have done this?

**Comment by MoQ93** [comment]
@jkbaseer I just create an .npmrc file in the docker container see this for the change: https://github.com/strapi/strapi-docker/pull/53/files
