### ISSUE TITLE
CORS origin can't be set in middleware.js in 4.22.0

### ISSUE THREAD

**Issue by jumptrnr** [strapi/strapi#20033]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.22.0
- Database: mysql
- Operating system: OSX Sonoma 14.4.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Setting explicit CORS origins no longer works after updating from 4.21.1 to 4.22.
Get 

`InternalServerError:  is not a valid origin"
(/node_modules/koa/lib/context.js:97:11)`

### Steps to reproduce the behavior

1. in middleware.js, list "origin as "http://localhost:3000" 
2. access api request from that address
3. See error
4. also deleted node_modules, and lock file - still issue persisted

Revert to 4.19 and issue goes away
Or list origin as ['*'] and it also goes away in 4.22

### Expected behavior

Setting origins as array of allowed URL works without wildcard

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Another user reported setting @koa/cors to this also fixed but know cors was updated recently
`  "resolutions": {
    "@koa/cors": "3.4.1"
},`

**Comment by 7999999166** [comment]
facing same issue with core 
{
    name: 'strapi::cors',
    config: {
      enabled: true,
      headers: '*',
      origin: ['http://localhost:5173','http://localhost:1337','netlify & Railway app http address']
    }
this thing is not working

**Comment by derrickmehaffy** [comment]
related to: https://github.com/strapi/strapi/pull/19921

Will test reproducing but in testing that PR it shouldn't modify anything as we set our own defaults for CORs

**Comment by zirho** [comment]
> facing same issue with core { name: 'strapi::cors', config: { enabled: true, headers: '*', origin: ['http://localhost:5173','http://localhost:1337'] } this thing is not working

try https://github.com/strapi/strapi/issues/20018

**Comment by 7999999166** [comment]
no , i tried the Recommended Addition to package.json but its not resolving the Problem

**Comment by derrickmehaffy** [comment]
Alright from what I can see (and I'm not sure why) the browser isn't actually sending the `Origin` header, so it's not a config problem, those are being used properly but what I'm not understanding is why there is no origin.

The issue is here: 

https://github.com/strapi/strapi/blob/5ab818b8ee36a4f090027477a602736c6adbd1a4/packages/core/strapi/src/middlewares/cors.ts#L51

Origin is undefined and the request headers don't include origin at all, I'm guessing it's an issue in the pre-flight request and something is disabling the browser from properly setting that header.

**Comment by derrickmehaffy** [comment]
![image](https://github.com/strapi/strapi/assets/8593673/ed7e6824-70b4-4252-846c-2b931973cee8)

**Comment by jumptrnr** [comment]
If it is helpful - I see this when I run an introspection query on my graphql instance at http://localhost/graphql from my strapi instance right after it has started up.  

No browser - just an axios "post" from inside strapi

"axios": "^1.6.8"

**Comment by derrickmehaffy** [comment]
I believe this is related to the fact that `same-origin` type requests don't set an origin header. Which makes sense based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

Only cross-origin requests should give the origin header

**Comment by derrickmehaffy** [comment]
For now we are gonna revert the `@koa/cors` upgrade and release a hotfix release tomorrow in v4.22.1 until we can figure out whats going on with @koa/cors

**Comment by derrickmehaffy** [comment]
Note to Strapi engineers if you pick up this issue, come talk to me or @alexandrebodin as we were looking into this today and we have some other information.

**Comment by ivangonzalezg** [comment]
> > facing same issue with core { name: 'strapi::cors', config: { enabled: true, headers: '*', origin: ['http://localhost:5173','http://localhost:1337'] } this thing is not working
> 
> try #20018

adding resolution in package.json worked to me

```
...
  },
  "resolutions": {
    "@koa/cors": "3.4.3"
  },
...
```

![image](https://github.com/strapi/strapi/assets/42500072/7ec84533-f7a4-46d0-ab82-0f31fecb733d)

**Comment by alexandrebodin** [comment]
We released the revert PR in 4.22.1. Thank you all for the help !

**Comment by derrickmehaffy** [comment]
Hey all, we rewrote the cors middleware to be more in spec with the cors intended spec in this PR: https://github.com/strapi/strapi/pull/20044

We also have an experimental version you can test with here: `0.0.0-experimental.469f8c0fe2f5ae4a405ec89049706cd7debab0f7`

**Comment by eugle** [comment]
I haven't solved the Cors problem since I started using Stratpi. I need to use wildcards, but I saw the developer say that by default, it's wildcard and any endpoint can be connected. Just keep "strapi:: cors" and that's it. But I can't.


Origin must be set:[“ http://localhost:3000 Only then can I, but I really need origin: [*]. Is there any way?

```
  {
    name: "strapi::cors",
    config: {
      origin: ["*"],
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
      headers: ["Content-Type", "Authorization", "Origin", "Accept"],
      keepHeaderOnError: true,
      credentials: false,
    },
  },
```

How to solve this cors problem? Don't worry about security issues, I just hope it can run normally. I have many subdomains that will call the backend API of Stratpi. Thanks

```
Access to fetch at 'https://beta.x.com/graphql' from origin 'https://www.x.com' has been blocked by CORS policy: Request header field x-custom-delay is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by ddsdevelopers** [comment]
Hello there, 

I think there are still issues with this @derrickmehaffy 

I'm currently on version 4.25.8 and with the following cors configuration:

`
{
      name: 'strapi::cors',
      config: {
        headers: '*',
        origin: process.env.CORS_ACCEPTABLE_URLS?.includes(",")
          ? process.env.CORS_ACCEPTABLE_URLS.split(",")
          : process.env.CORS_ACCEPTABLE_URLS,
      },
    },
`

Where CORS_ACCEPTABLE_URLS has the following format: `http://localhost:5173,http://localhost:1337`

And I'm able to log in from other domains or ports and I see the Access-Control-Allow-Origin empty.

Could you check this, please?
Thank you!

**Comment by derrickmehaffy** [comment]
> Hello there, 
> 
> I think there are still issues with this @derrickmehaffy 
> 
> I'm currently on version 4.25.8 and with the following cors configuration:
> 
> ```
> {
>       name: 'strapi::cors',
>       config: {
>         headers: '*',
>         origin: process.env.CORS_ACCEPTABLE_URLS?.includes(",")
>           ? process.env.CORS_ACCEPTABLE_URLS.split(",")
>           : process.env.CORS_ACCEPTABLE_URLS,
>       },
> },
> ```
> 
> Where CORS_ACCEPTABLE_URLS has the following format: `http://localhost:5173,http://localhost:1337`
> 
> And I'm able to log in from other domains or ports and I see the Access-Control-Allow-Origin empty.
> 
> Could you check this, please?
> Thank you!

We have never supported that format, it should be a string or an array of strings. If comma separated values worked before it wasn't intended.

**Comment by pwn0xfff** [comment]
I am not sure why this is a security issue considering that  Strapi doesn't use cookie sessions for authentication?
