### ISSUE TITLE
@strapi/admin locks in vite and webpack-dev-middleware, so entire projects can't upgrade

### ISSUE THREAD

**Issue by broksonic21** [strapi/strapi#20032]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 4.22.0
Node/Yarn Version: npm/10.5.1 node/v20.12.1 darwin arm64 workspaces/false
Edition: Community
Database: mysql2

### Steps to reproduce the behavior

1. Install @strapi/admin
2. try using a later patch version of vite or webpack-dev-middleware in your package.json - you can't

### Expected behavior

Strapi to support any patch version of common dependencies, not lock entire project in

Right now it's

https://github.com/strapi/strapi/blob/develop/packages/core/admin/package.json#L164

https://github.com/strapi/strapi/blob/develop/packages/core/admin/package.json#L167

These should be:

    "vite": "^5.0.11",

and

    "webpack-dev-middleware": "^6.1.1",

This impacts other dependencies too, which are now locked in for the entire project, but those are the two most impacting us right now.

### Additional context

There are security and other important fixes in vite 5.0.13 and webpack-dev-middleware 6.1.2 we'd like to have.

**Comment by derrickmehaffy** [comment]
We are not vulnerable to these issues but have a PR open to upgrade them, they can be safely ignored
