### ISSUE TITLE
Unique constraint not stored in Postgresql database

### ISSUE THREAD

**Issue by khuongtp** [strapi/strapi#20043]
### Required System information

- Node.js version: 20.11.0
- Yarn version: 1.22.2
- Strapi version: 4.22.0
- Database: Postgresql
- Operating system: Macos
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Setting field to unique on the admin interface doesn't store a unique constraint in database.

### Steps to reproduce the behavior

1. Create new project with `yarn create strapi-app`
2. Create a new content type and add a field, go to advanced settings add check the unique field checkbox
3. Inspect the database using pgadmin4
4. View the table of that content type
5. See no unique constraint is created

### Expected behavior

Set field as unique should reflect the unique constraint to the database.

### Screenshots

<img width="825" alt="image" src="https://github.com/strapi/strapi/assets/62872729/dc5892ab-fbfe-4644-b52d-3d900e20c7e9">
<img width="604" alt="image" src="https://github.com/strapi/strapi/assets/62872729/1af67759-1e24-49ea-8a66-7bc8832a5116">

**Comment by lmlTimolml** [comment]
Also there is an issue when trying to update info on a page with a unique field. It won't save if the value in the field is not changed. And publishing is impossible, as you can't publish when the field is unique.

https://github.com/strapi/strapi/assets/23234762/4ca4c75f-6ea1-49a1-ad53-7f68ab78d1ee

**Comment by derrickmehaffy** [comment]
We don't apply the database constraints at the database level intentionally due to both i18n and draft/publish in Strapi 5 and we have no plans to add it.
