### ISSUE TITLE
Strapi not storing cloudinary public_id

### ISSUE THREAD

**Issue by hunter-isaiah96** [strapi/strapi#2005]
**Informations**
- **Node.js version**: v10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: Mlab.com Sandbox
- **Operating system**: Windows 10

**What is the current behavior?**
When I use the cloudinary provider, for some reason it does not store the public_id from the upload in the mongo object, this makes it so that when I try to delete an image from the database I'm given an error because public_id doesn't exist inside of the object.

**Steps to reproduce the problem**
Start a new project and implement the cloudinary provider, upload and image and see if public_id appears in the object.

**What is the expected behavior?**
When you upload the image, public_id should be an attribute of the object to allow deletion of an image

**Suggested solutions**
I have not been able to find the source of the issue so I don't have an idea as of now.

**Comment by lauriejim** [comment]
Hello @hunter-isaiah96 , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by dorelljames** [comment]
Not sure if it's appropriate to raise this here but I noticed that while this works perfectly on image types, it does not work with "video" format.

I submitted PR #2390 fixing video format uploads and checked out this PR. Please this video: https://www.useloom.com/share/e368fe788a754ae5bb09e34cf5e404a7

I'm not so sure but the `public_id` is correct. Might have something to do with Cloudinary's package.
