### ISSUE TITLE
Edit a transfer token brings to an empty section

### ISSUE THREAD

**Issue by maccomaccomaccomacco** [strapi/strapi#20051]
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 5.0.0-beta.2
- Database: sqlite
- Operating system: Mac
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Trying to edit a transfer token bring to an admin page that it essentially empty.

### Steps to reproduce the behavior

1. access the list of transfer tokens ensuring to have some already created
2. click on the edit button for a transfer token in the list
you'll get an empty screen

### Expected behavior

Access the view to edit the transfer token

**Comment by derrickmehaffy** [comment]
fixed in beta.3
