### ISSUE TITLE
Unable to create Strapi beta project with NPM

### ISSUE THREAD

**Issue by john-szetho** [strapi/strapi#20061]
### Required System information

- Node.js version: v21.7.2
- NPM version: 10.5.0
- Strapi version: Strapi 5 beta
- Database: —
- Operating system: MacOS Montery
- Is your project Javascript or Typescript: —

```
> strapi@0.1.0 strapi
> strapi report
```

### Describe the bug

I am unable to download the Strapi beta package and install via NPM. Upon creating, it stalls on an error and ends up looping so I have to terminate the terminal.

### Steps to reproduce the behavior

1. Open terminal
2. Use command 'npx create-strapi-app@beta strapi --quickstart'

### Expected behaviour

For the packages to install and for Strapi to be ready to use

### Code snippets

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/design-system@1.16.0
npm WARN Found: react-router-dom@6.21.1
npm WARN node_modules/react-router-dom
npm WARN   react-router-dom@"^6.0.0" from the root project
npm WARN   3 more (@strapi/plugin-cloud, @strapi/strapi, @strapi/plugin-users-permissions)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-router-dom@"^5.2.0" from @strapi/design-system@1.16.0
npm WARN node_modules/@strapi/design-system
npm WARN   @strapi/design-system@"1.16.0" from @strapi/plugin-cloud@5.0.0-beta.2
npm WARN   node_modules/@strapi/plugin-cloud
npm WARN   1 more (@strapi/plugin-users-permissions)
npm WARN 
npm WARN Conflicting peer dependency: react-router-dom@5.3.4
npm WARN node_modules/react-router-dom
npm WARN   peer react-router-dom@"^5.2.0" from @strapi/design-system@1.16.0
npm WARN   node_modules/@strapi/design-system
npm WARN     @strapi/design-system@"1.16.0" from @strapi/plugin-cloud@5.0.0-beta.2
npm WARN     node_modules/@strapi/plugin-cloud
npm WARN     1 more (@strapi/plugin-users-permissions)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/plugin-content-manager@5.0.0-beta.2
npm WARN Found: peer @strapi/admin@"^5.0.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @strapi/admin@"^5.0.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/plugin-content-manager@5.0.0-beta.2
npm WARN Found: peer @strapi/admin@"^5.0.0" from the root project
```

### Additional context

I tried killing the process and installing the rest via 'npm install'.
However, this still doesn't work as it throws the error 'Could not resolve dependency...'

**Comment by Deliana90** [comment]
me too, installing dependencies . . . never finished . . .

**Comment by fgrsource** [comment]
> ## Bug report
> ### Required System information
> * Node.js version: v21.7.2

Just have a look at the package.json. Strapi only supports NodeJS LTS versions. To be clear you need NodeJS Version 18.X.X or NodeJS Version 20.X.X.

Just have a look at [the docs](https://docs-next.strapi.io/dev-docs/quick-start) 

> [Node.js](https://nodejs.org/): Only [Active LTS or Maintenance LTS versions](https://nodejs.org/en/about/previous-releases) are supported (currently v18 and v20). Odd-number releases of Node, known as "current" versions of Node.js, are not supported (e.g. v19, v21).

**Comment by Deliana90** [comment]
node -v
v20.11.1

**Comment by john-szetho** [comment]
@fgrsource 

I used the command `nvm use 20 --lts`
So confirming I am using Node v20.12.1 and it still is not working

**Comment by joshuaellis** [comment]
This will be fixed in the latest beta, released this week.

**Comment by john-szetho** [comment]
Ok, thanks for the update
