### ISSUE TITLE
Primary Key and Compound keys in Content Type Editor

### ISSUE THREAD

**Issue by sajjad-shirazy** [strapi/strapi#2006]
**What is the expected behavior?**

It would be great if we had some facilities for determining Primary Key or Compound keys of a Content Type in Content Type Editor.
I see that we don't have such options even programmaticaly in model setting:
https://strapi.io/documentation/3.x.x/guides/models.html

**Comment by Aurelsicoko** [comment]
The option isn't documented but you can add a `primaryKey` key at the root of each model definition.

```json
{
  "connection": "default",
  "primaryKey": "_id",
  "attributes": {
    "firstname": {
      "type": "string"
    }
  }
}
```

**Comment by sajjad-shirazy** [comment]
Thanks @Aurelsicoko it's great, is any option for compound keys too? i mean for indexing

**Comment by Aurelsicoko** [comment]
No, we don't support compound (foreign) keys for now. There is also @dj-hedgehog which is waiting for this feature. 

We already talk a little bit about how we are handling SQL databases (table, columns, keys) in this issue (https://github.com/strapi/strapi/issues/1114) as well. Feel free to add your thoughts 👍

**Comment by derrickmehaffy** [comment]
*raises hand* I've brought it up a number of times as well. Right now strapi doesn't generate DB constraint keys either like `unique`

**Comment by Aurelsicoko** [comment]
I'm closing this issue, we can continue the discussion in the #1114 issue.
