### ISSUE TITLE
User Permissions Modification

### ISSUE THREAD

**Issue by YouhannaSabry** [strapi/strapi#2007]
**Informations**
- **Node.js version**: v9.5.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.3
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04 Bionic Beaver

**What is the current behavior?**
Posting to /auth/local/register sets the role of the user to Public by default (I changed the advanced settings)
Post Request Data Sent:
`{
     "username": "test",
    "email": "test@test.com",
    "password": "testpassword"
}`
I am trying to set the default role to Public and only admins can approve the user and change his role to "Authenticated", I figured out how to make the default role "Public" but I need to know how to change a role of a user from "Public" to "Authenticated" using patch request.
What data should I send and to what endpoint?
I tried using slack but something is wrong.

**Comment by derrickmehaffy** [comment]
@YouhannaSabry Public is for non-authenticated users, authenticated is default because the user is then registered. I wouldn't recommend setting that to public.

If you need to add more groups you can, and also change the group permissions.

Note that no other group except administrator can access the adminUI

**Comment by lauriejim** [comment]
By default on Strapi, default role is **Authenticated** when a user is registered with `/auth/local/register` route. You can update permissions to this role if you want.
Or you can create an new role with specifics permissions and set it as default.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
