### ISSUE TITLE
Create additional type that looks like JSON consisting of existing plain types(sting, text, media, etc.)

### ISSUE THREAD

**Issue by pulpiks** [strapi/strapi#2008]
**What is the expected behavior?**

We will be able to fill in the data for JSON type with values by hand using existing interactive fields for data hence we will have the possibility to make if from existing fields. For example, I need to describe the field steps as an array from following values as `[{"title": "The page title", "image": "http://localhost:1337/uploads/a38e544b32b04f1aac041f0e68698e17.webp", "description": "Detailed info about the item"}]`. For now, I do this tough work manually (fill all the content for JSON object by hand). I wish to have the interface from existing fields for each item included in JSON.  Is it going to happen in the near feature or how to manage this issue by more elegantly way?

**Comment by fpetrouchka** [comment]
Hi @pulpiks thanks for constructive proposition :)
that seems great if we had inline-JSON editor in there, but im afraid this feature could fatten up the application.
wonder if there were Strapi-esque simple way to make key-value editor like Content Type Builder though.

**Comment by Aurelsicoko** [comment]
@pulpiks What could be the use case behind this feature? I'm not sure to understand the need...

**Comment by pulpiks** [comment]
Let's say we need to create a structure looks like a set of questions(format type as an object from title and image) with nested answers(type format text). For now, as long as JSON type was implemented as JSON without a visual presentation that means user can add text in "textarea" block, but I would rather fill the data from primitive types via visual presentation. Did you get it now?

**Comment by Aurelsicoko** [comment]
@pulpiks Oh yes, I get it! You are speaking about something like Matrix field or Repeatable field. You define a block of fields (text, pictures and textarea) and you want to be able to repeat this schema as many time you want and everything is stored in a single field finally.

@lauriejim I know there are others issues talking about the same topics, can we reference them in this issue as well? Thank you 👍

**Comment by derrickmehaffy** [comment]
Related: https://github.com/strapi/strapi/issues/1779

Your welcome @Aurelsicoko

**Comment by Aurelsicoko** [comment]
Thank you @derrickmehaffy!
