### ISSUE TITLE
Unable to discard draft on SingleTypes

### ISSUE THREAD

**Issue by joshuaellis** [strapi/strapi#20085]
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-beta.2
- Node/Yarn Version: yarn/4.0.1 npm/? node/v20.12.0 darwin arm64
- Edition: Enterprise
- Database: sqlite

### Describe the bug

When discarding changes on a single-type under certain circumstances, the changes are not propagated correctly. It works on some single-types but not others, I've also had issues with dynamic zones with the error: `Some of the provided components in content are not related to the entity` during discarding, these may be related.

### Steps to reproduce the behavior

This video shows the bug:

https://github.com/strapi/strapi/assets/37798644/26d2475d-fa41-4c71-a342-dbc11563203f

### Expected behavior

I should be able to discard the changes of any document given it is modified

### Additional context

There is an E2E test under `content-manager/editview` that should pass, it's currently not running with the `fixme` call.

**Comment by julesrenaud** [comment]
this also happens to me on Strapi v4

**Comment by Marc-Roig** [comment]
This seems to be fixed in 5.0.0-beta.9
