### ISSUE TITLE
Cannot select Multiple files in a  Multiple files Media field in Strapi V5

### ISSUE THREAD

**Issue by creative-ae** [strapi/strapi#20083]
## Bug report
Cannot select Multiple files in a  Multiple files Media field in Strapi V5

### Required System information
- Node.js version:
- NPM version:
- Strapi version: V5 BETA 3
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

Cannot select Multiple files in a  Multiple files Media field in Strapi V5. The field is only limited to select 1 files only

### Steps to reproduce the behavior

1. login to admin
2. create a new collection type
3. add Media field
4. select multiple media
5. save
6. go to add a content
7. add content with image
8. i can select only 1 file

### Expected behavior
i should be able to select multiple files

**Comment by creative-ae** [comment]
![Screenshot 2024-04-10 at 22 50 02](https://github.com/strapi/strapi/assets/46525762/33a036ca-7d2d-4595-b8a6-2c13f2743b94)
![Screenshot 2024-04-10 at 22 47 24](https://github.com/strapi/strapi/assets/46525762/1a140bdb-4748-41f7-9914-9b17133a84c1)

**Comment by Eventyret** [comment]
Confirmed `5.0.0-beta.8`

**Comment by alexandrebodin** [comment]
Merged the fix
