### ISSUE TITLE
Review where Strapi use core store and JSON file to store configs

### ISSUE THREAD

**Issue by Flux159** [strapi/strapi#2009]
**Informations**
- **Node.js version**: 8.9.4
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: Postgres
- **Operating system**: MacOS

**What is the current behavior?** When trying to use strapi for uploading files to AWS S3, the upload plugin puts credentials into the database by using ```strapi.store({}).set({...})``` instead of storing them in a config file / reading from environment variables.

See here: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/controllers/Upload.js#L97

**Steps to reproduce the problem**
Create new strapi project, setup file upload plugin with s3 provider: https://strapi.io/documentation/guides/upload.html#install-providers , then use the GUI to set AWS credentials. They won't be stored in a file, but will be in your database.

**What is the expected behavior?**
This seems like a security risk / non-standard behavior for storing credentials.

**Suggested solutions**
Upload-plugin should set/get credentials from a json / config file that can read from environment variables like other configs.

**Comment by Aurelsicoko** [comment]
@Flux159 Sure but if it also means that you can switch to another bucket or provider without restarting the server...

**Comment by Flux159** [comment]
The minor benefit of not having to restart your server doesn't seem to be worth it in this case - if someone wants to change their bucket or provider in production they're already going to have to run some job to transfer over files to a different place & ensure that transfers completed successfully (for this example, say AWS S3 to Google cloud). Restarting their server(s) after changing environment variables is trivial compared to changing providers entirely.

Using environment variables is also one of the recommended ways that AWS says to store access credentials (the other being a configuration file): https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html#iam-user-access-keys

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I made a similar suggestion to @lauriejim and @soupette there should be options to manually override these settings. In this case a manual config file that can have a dynamic env variable similar to how the database.json is ran. These should override anything stored in the DB and allow for static configs (More or less enforcing that this *can't* be changed in production.)

**Comment by Aurelsicoko** [comment]
You've convinced me... we should certainly store this configuration in a JSON file. We allow dynamic environment variable in our JSON configurations file so we can switch pretty easily to the new way to handle this configuration.

**Comment by derrickmehaffy** [comment]
:stuck_out_tongue_closed_eyes: @Aurelsicoko there are just some things that shouldn't be changed in production :wink:

**Comment by derrickmehaffy** [comment]
@Aurelsicoko As another suggestion, with regards to providers (OAuth providers) I also think this should be something either json config based // environment variable based. You aren't likely to modify these settings often enough in production in my opinion.

**Comment by SMR39** [comment]
Any ETA for these changes ?

**Comment by Aurelsicoko** [comment]
@SMR39 No... it's not our priority, I would love to see this issue fixed. Do you think that you will have time to make a PR?

**Comment by lauriejim** [comment]
We wrote an article about this topic to explain why we are doing that.
http://help.strapi.io/configurations/why-configurations-are-sometimes-stored-into-files-or-database

We are doing our best to make it easiest as we can.
Thank you for your feedback, I close this topic.
