### ISSUE TITLE
Can't make a relationship between two models

### ISSUE THREAD

**Issue by alhill** [strapi/strapi#2010]
**Informations**
- **Node.js version**: v10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.1.1, fresh installed
- **Database**: 3.6.6 (MMAPv1), mLab 
- **Operating system**: Ubuntu Server 18.04 (Bionic Beaver)

**What is the current behavior?**

Strapi fails to make a relationship between two models

**Steps to reproduce the problem**

Just create two models and try to make a relationship between them. When server is trying to restart it gives an error like this.

```
[2018-09-23T18:50:21.588Z] error Something went wrong in the model `Receta` with the attribute `comentarios`
[2018-09-23T18:50:21.591Z] error The attribute `receta` is missing in the model Comentario 
```

In the above example, I created a one-to-many relationship between Receta and Comentario. Reading Receta.settings.json everything is normal, but in Comentario.settings.json Strapi hasn't created the relationship.

```
{
  "connection": "default",
  "collectionName": "receta",
  "info": {
    "name": "receta",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "nombre": {
      "default": "",
      "type": "string"
    },
    "comentarios": {
      "collection": "comentario",
      "via": "receta"
    }
  }
}

```

```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "comentario",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "titulo": {
      "default": "",
      "type": "string"
    }
  }
}
```

It fails with all kind of relationship althogh in one-to-one the second line of the error is different

```
[2018-09-23T19:23:20.638Z] error Something went wrong in the model `Test1` with the attribute `test2`
[2018-09-23T19:23:20.643Z] error Cannot read property 'hasOwnProperty' of undefined
```

If the faulty model settings.json is fixed manually, Strapi works again and the relationship haven't any problem.
The problem doesn't seem to happen when the relationship is made with a model of the users-permissions-plugin.

**What is the expected behavior?**

Make the relationship without problems

**Suggested solutions**

I have seen similar issues closed some time ago, maybe some changes of last version have broken something in relationship system

**Comment by lauriejim** [comment]
@soupette can you give an update about your test.

**Comment by mnlbox** [comment]
I think it's related to: #2097

**Comment by soupette** [comment]
@lauriejim what test?
