### ISSUE TITLE
Plugins version matching with Strapi version

### ISSUE THREAD

**Issue by MoQ93** [strapi/strapi#2011]
**Informations**
- **Node.js version**: 9.11.1 
- **npm version**: 5.6.0
- **Strapi version**: Any older version 
- **Database**: not relevant
- **Operating system**: not relevant

**What is the current behavior?**
If you have strapi installed with an older version and try to init a new project. The root Project and the admin Panel would have the same version as the globally installed strapi but all the plugins are installed with the newest available version. This makes the system not working properly and leads to crashes.

**Steps to reproduce the problem**
- Install an older version of Strapi
- Init a new Project with it
- You will see that the plugins using newest version and in the admin panel you will notice that you cannot add for example a new type properly and so on.

**What is the expected behavior?**
Strapi should use the version of root project for all strapi related dependencies to avoid this problems.

**Suggested solutions**
Strapi should use the version of root project for all strapi related dependencies

**Comment by Aurelsicoko** [comment]
Good catch! I think we could increase the priority of this feature (cc @lauriejim)?
