### ISSUE TITLE
Can't connect to mlab

### ISSUE THREAD

**Issue by johhansantana** [strapi/strapi#2013]
**Informations**
- **Node.js version**: 10.9.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.14.1.1
- **Database**: mongodb/mlab
- **Operating system**: mac

**What is the current behavior?**
Trying to connect to a database hosted at mlab doesn't work.
![image](https://user-images.githubusercontent.com/9933887/45981104-e8fabb80-c021-11e8-9f1b-75f079f2519c.png)

**Steps to reproduce the problem**
Create a database at mlab.com

Create a database user

go to `/config/environments/development/database.json` and configure it using your credentials:

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "*****.mlab.com",
        "srv": false,
        "port": "*****",
        "database": "johhansantana",
        "username": "jsantana",
        "password": "********"
      },
      "options": {
        "authenticationDatabase": "", // I tried johhansantana as well
        "ssl": true // tried false as well
      }
    }
  }
}

```

**What is the expected behavior?**
Be able to connect to mlab

**Suggested solutions**
There are a few questions on the cli and configurations that aren't explaind.

For example:
```json
"options": {
  "authenticationDatabase": "",
  "ssl": true
}
```

It's not clear what `authenticationDatabase` is for
and `ssl` not sure either.

This is my database user at mlab:
![image](https://user-images.githubusercontent.com/9933887/45981342-a71e4500-c022-11e8-9128-b00a4797d497.png)

**Comment by coding-saints** [comment]
For the cli `authentiicationDatabase` value you need to use whatever the name was when creating it on mLab. So if you created a new deployment named `my-sandbox`, it would display something like `ds100100/my-sandbox`. Whatever the name is after the `/` is your authenticated DB (`my-sandbox` in this example). If I can find the reference then I'll edit this for your own research. I hope this helps. All I can say is I had a heck of a time getting started, also. Stay persistent!

**Comment by johhansantana** [comment]
Tried putting what's after the `/` but no luck.

Tried from the beginning but still no luck:
![image](https://user-images.githubusercontent.com/9933887/45986228-3d109a80-c038-11e8-9775-8c80390a2a73.png)

This time, cli says it connected but when I run it fails.

**Comment by yummyelin** [comment]
I am able to connect to mLab by using:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "settings": {
        "client": "mongo",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME || 'strapi-development'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}"
      },
      "options": {
        "ssl": false
      },
      "connector": "strapi-hook-mongoose"
    }
  }
}
```

**Comment by johhansantana** [comment]
tried your way but no luck :(

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "******.mlab.com",
        "port": "******",
        "database": "johhansantana",
        "username": "jsantana",
        "password": "********"
      },
      "options": {
        "ssl": false
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/9933887/45987419-56691500-c03f-11e8-87c2-3b95150673b8.png)

**Comment by derrickmehaffy** [comment]
@johhansantana Never used mlab but there are a host of closed issues related this for instance with your auth db:

![image](https://user-images.githubusercontent.com/8593673/45996530-67228680-c051-11e8-9ccf-cfd069e0f203.png)

**Comment by sundaycrafts** [comment]
How about the port number is correct?

Or can you connect to the DB from other clients like [Robo 3T](https://robomongo.org/) or [Compass](https://www.mongodb.com/products/compass) or mongo shell?

**Comment by johhansantana** [comment]
I was able to connect via Robo 3T:
![screen shot 2018-09-25 at 52](https://user-images.githubusercontent.com/9933887/46045342-69392380-c0eb-11e8-955e-94417c71407c.jpg)
![screen shot 2018-09-25 at 5](https://user-images.githubusercontent.com/9933887/46045343-69392380-c0eb-11e8-8e9a-37d9492d8dde.jpg)
![screen shot 2018-09-25 at 53](https://user-images.githubusercontent.com/9933887/46045412-a2719380-c0eb-11e8-8d1f-fe29a8f2fa1c.jpg)

I tried again to see if I just needed to have some data in the mlab database but failed again:
![screen shot 2018-09-25 at 54](https://user-images.githubusercontent.com/9933887/46045489-dcdb3080-c0eb-11e8-9b67-3e1ec52d256b.jpg)

**Comment by sundaycrafts** [comment]
Thank you for your report! But I'm sorry I can't detect the problem.
If you have some time, please try to edit the module source code directly and get error full message.

Strapi may throw error from [this line](https://github.com/strapi/strapi/blob/v3.0.0-alpha.14.1.1/packages/strapi-hook-mongoose/lib/index.js#L94). Just inject `console.log(error.message)`. You can access this file from `node_modules/strapi-hook-mongoose` in your project (it may be link).

**Comment by johhansantana** [comment]
I tried that and I get the following log:

![image](https://user-images.githubusercontent.com/9933887/46088472-781ae700-c17a-11e8-987e-f2d1b21d6641.png)

If I put a wrong username or password I get:
![image](https://user-images.githubusercontent.com/9933887/46089386-57539100-c17c-11e8-9ef4-4badde8d329a.png)

Doesn't matter what I put in `authenticationDatabase`.

**Comment by maturanomx** [comment]
Hi o/ I just give a quick eye on the conversation. I have one question: What's the value of `NODE_ENV`?

In the past I tried mlab without problems. No value for `authenticationDatabase`, just host, port, username, password and database, plain and simple.

As far I saw, I'm betting that when strapi runs is reading the configuration file other than when create the project. I think that could be because you have a value for the environment variable `NODE_ENV`, not strange if you are in a infrastructure server (not running in local or so...).

So... when you create the project, strapi writes to `config/environment/develop/database.json`, but when you try to run it, reads from `config/environment/WHATEVER_NODE_ENV_IS/database.json`. If that's the case, the fix is just copy the file, or set the data to the correct env variables that are in the file.

Hope it helps. Let me know o/

**Comment by yummyelin** [comment]
Do you have `@` sign in your password? It seems it does not support `@` sign.

https://github.com/mrvautin/adminMongo/issues/147

**Comment by derrickmehaffy** [comment]
@yummyelin nice thinking

**Comment by BraydenGirard** [comment]
> For the cli `authentiicationDatabase` value you need to use whatever the name was when creating it on mLab. So if you created a new deployment named `my-sandbox`, it would display something like `ds100100/my-sandbox`. Whatever the name is after the `/` is your authenticated DB (`my-sandbox` in this example). If I can find the reference then I'll edit this for your own research. I hope this helps. All I can say is I had a heck of a time getting started, also. Stay persistent!
> Edit: Also I believe you just leave SSL to the default (press enter). If I'm mistaken just type it explicitly then. I'll look for the issue where I found this from...

This was the solution for me. You can not leave Authentication Database empty when using MLab. You need to specify the name of your database here.

**Comment by deevolutionism** [comment]
The [mlab tutorial](https://medium.com/strapi/using-mlab-with-strapi-e3f968a9c530) should be updated to mention authenticationDatabase as an important input - I think the image is outdated. Problem with using medium is community members can't make changes to it...

**Comment by sujeetbuddiga** [comment]
@deevolutionism can you please conclude the solution if you were able to work it out.

**Comment by johhansantana** [comment]
@yummyelin it was this all along.... thank you! and everyone that also replied. Sorry for the noise.

> Do you have @ sign in your password? It seems it does not support @ sign.
> mrvautin/adminMongo#147

**Comment by derrickmehaffy** [comment]
@johhansantana If you could do me a huge favor and make a PR to include a note about this in the docs.

That would be great. Just so we can reference users to it in the future.

**Comment by sujeetbuddiga** [comment]
Specifying **authenticationDatabase** in **options**.

I have assigned  **authenticationDatabase** to the value of **database** and it worked for me.

I made this change in **database.json** file

```
{
  "defaultConnection": "myapp-aws-mongod",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "ds115613.mlab.com",
        "port": 15610,
        "database": "myapp-aws-mongod",
        "username": "myapp",
        "password": "myapppwd1"
      },
      "options": {
        "ssl": "false",
        "authenticationDatabase": "myapp-aws-mongod"
      }
    }
  }
}

```

**Comment by derrickmehaffy** [comment]
@johhansantana I'm thinking maybe a new block around here: https://strapi.io/documentation/configurations/configurations.html#database

To answer some of the common MLab questions

**Comment by dommythekid** [comment]
What about if you get an error saying "URL is not defined"  when running the command of **strapi start**

<img width="343" alt="screen shot 2018-12-03 at 9 13 10 pm" src="https://user-images.githubusercontent.com/22457573/49420440-502e9d80-f740-11e8-86c5-9a713cb3ebbc.png">

**Comment by derrickmehaffy** [comment]
@dommythekid Use node 10.

Node v8 is End-Of-Life (EOL)
Node v11 is still in development and is not ready for any production usage.

**Comment by dommythekid** [comment]
@derrickmehaffy Worked instantly - thanks so much!

**Comment by derrickmehaffy** [comment]
@dommythekid no problem

**Comment by johnnyz** [comment]
Node v11 worked for me. I just needed to provide "strapi-test" which was the name of my mLab instance as my authentication database.

**Comment by Attrash-Islam** [comment]
```js
"authenticationDatabase": "myapp-aws-mongod"
```

Worked for me! 🎉

**Comment by jimmymam18** [comment]
<img width="714" alt="Screen Shot 2019-06-17 at 2 50 33 AM" src="https://user-images.githubusercontent.com/5707436/59596138-fbcf8780-90ab-11e9-8563-6ddcbbf91d88.png">

**Comment by jimmymam18** [comment]
i still have an error

**Comment by davidkartuzinski** [comment]
@jimmymam18 - Did you follow these instructions? https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#mongodb-installation

**Comment by jimmymam18** [comment]
I tried to use the terminal on my visual studio and when running the mongoDB I get an error stating that my database connection failed and it also state that my database name: already file exists

**Comment by jimmymam18** [comment]
I did everything and nothing seems to work someone please help me

**Comment by davidkartuzinski** [comment]
@jimmymam18 - hello.  Sorry about what is happening.  
Can you confirm that you have successfully gotten MongoDB running in the background? 

If you did, are you using the alpha or beta versions of Strapi?

**Comment by jimmymam18** [comment]
how do I know if MangoDB is running in the background? I'm using the alpha Strapi.

**Comment by davidkartuzinski** [comment]
@jimmymam18 - you can check in your terminal with the command ```service mongod status```.  Did you follow the documentation for installing MongoDB on your local computer? https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#install-mongodb-locally

**Comment by derrickmehaffy** [comment]
depending on the OS you are using `systemctl status mongod` @jimmymam18

**Comment by jimmymam18** [comment]
It still does not work, is there's a way someone can either skype or facetime and explain over skype?

**Comment by derrickmehaffy** [comment]
@jimmymam18 google would probably be a bit easier. There are tons of guides on mongodb on a linux host. :)

**Comment by jimmymam18** [comment]
I'm working on a flutter mobile app and using Visual Studio as a terminal to try to run MangoDB but it seems to not to connect at all.

**Comment by davidkartuzinski** [comment]
@jimmymam18 - I would suggest not using the terminal in VS Code but the default terminal.  I am not sure what OS you're on, but [this page](https://www.youtube.com/playlist?list=PLS1QulWo1RIZtR6bncmSaH8fB81oRl6MP) has a few different videos on how to install MongoDB and get it running.  

Please take the time to separate the issue and see if this is an issue of MongoDB running or Strapi running or their connection.  At this point, start with ensuring you got MongoDB running independently of Strapi.

**Comment by suiteappdev** [comment]
working on mlab editing  timeout on hook.json to 100000,  and setting port in connection as string work for me.

**Comment by kgrosvenor** [comment]
authentication database is the same as your database name in mlab, that's all you should need to do, an then match the port mlab displays to you.

**Comment by thanhtam4692** [comment]
> working on mlab editing timeout on hook.json to 100000, and setting port in connection as string work for me.

Ok so I have to comment on this silly little bloody bug. Setting the port as string and ssl = false work for me!
