### ISSUE TITLE
A duplicated entry can be saved even if a unique field shares the same value as the original one

### ISSUE THREAD

**Issue by lucasboilly** [strapi/strapi#20141]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.23.1
- Database: sqlite
- Operating system: macOS 14.4.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When an entry is duplicated, it's still possible to save it even if a unique field have the same value as in the original one. However, if the value is changed, saved and that we write the identical value again, the error is displayed.

### Steps to reproduce the behavior

1. Create a Content-Type with a unique field in it
2. Create an entry and fill the unique field
3. Go to the List View
4. Duplicate the entry
5. Click "Save"

### Expected behavior

I'm supposed to see an error on the unique field an not being able to save.

### Screenshots

https://github.com/strapi/strapi/assets/45385696/20a1908b-d642-4d03-96fa-00e35c381bbb

### Additional context

Maybe is it linked to https://github.com/strapi/strapi/issues/20001 ?

**Comment by Sruthi-Palle** [comment]
hi @lucasboilly this is sruthi a frontend developer , i can resolve this issue, can you assign this to me.

**Comment by joshuaellis** [comment]
We don't assign issues. Just feel free to open a PR 😄

**Comment by dplumptre** [comment]
i have a PR for this issue: https://github.com/strapi/strapi/pull/20221

**Comment by hanpaine** [comment]
This has been fixed on Strapi 5 and a fix will be ported to V4 in coming weeks

**Comment by hanpaine** [comment]
Fixed on V4 here: https://github.com/strapi/strapi/pull/20963
