### ISSUE TITLE
Making another model authenticatable

### ISSUE THREAD

**Issue by Kunoacc** [strapi/strapi#2015]
**Informations**
- **Node.js version**: 8.11.4
- **npm version**: 6.3.0
- **Strapi version**: 3.0.0-alpha.13.1
- **Database**: Mongodb
- **Operating system**: Windows

**What is the current behavior?**
Is it possible to make multiple models authenticatable? Like a drivers and users model and both are authenticatable?

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**What is the expected behavior?**

**Comment by lauriejim** [comment]
Hello @Kunoacc , by default this option not exist.
But you can update/customize users-permissions plugin and Auth controller, to allow this feature.

Here we check if `User` exist https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L53

You have to make a double check with your Driver model.
