### ISSUE TITLE
[ STRAPI 5 BETA ] Components Created Show No Permission To See This Field

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/strapi#20159]
### Required System information

Environment: development

- Node.js version: v20.11.1
- NPM version: 10.2.4
- Strapi version: 5.0.0-beta.4
- Database: sqlite
- Operating system:
- Javascript 

### Describe the bug

When creating a new component get "no permission to see this field message"

### Screenshots

<img width="1508" alt="Screenshot 2024-04-19 at 11 19 07 AM" src="https://github.com/strapi/strapi/assets/6153188/214124d8-989b-46e5-834e-70b792753ca9">

### Steps to reproduce the behavior

Here is a video showing the steps.

https://github.com/strapi/strapi/assets/6153188/c9da8048-efbe-42d6-96a6-8c0f46239c2b

### Expected behavior

Should allow you to have access to the felds

**Comment by shanewg** [comment]
It appears to happen if a component is nested in another component.
<img width="1396" alt="Screen Shot 2024-05-01 at 11 24 14 AM" src="https://github.com/strapi/strapi/assets/3527946/ab721bbf-94ca-41cd-81c7-db8fe78246da">
<img width="1389" alt="Screen Shot 2024-05-01 at 11 17 55 AM" src="https://github.com/strapi/strapi/assets/3527946/cae33d60-e3b7-42b2-b6c6-9bc22d386d9f">

**Comment by shanewg** [comment]
This may be helpful.

It appears to happen when a component is nested in another component.

<img width="1389" alt="Screen Shot 2024-05-01 at 11 17 55 AM" src="https://github.com/strapi/strapi/assets/3527946/fb028e97-5f53-4733-bf7a-22be992ef45c">
<img width="1408" alt="Screen Shot 2024-05-01 at 3 22 52 PM" src="https://github.com/strapi/strapi/assets/3527946/4b848aa8-1b5e-4648-a688-3bc3cfa29d7a">

**Comment by lgt** [comment]
I'm facing the same issue as @shanewg.

**Comment by HaniElhamwi** [comment]
I am facing the same isssue  ?!

**Comment by PaulBratslavsky** [comment]
@HaniElhamwi what version of Strapi are you on.
