### ISSUE TITLE
Email field is disabled for new registration

### ISSUE THREAD

**Issue by kaseraSwastik** [strapi/strapi#20153]
### Required System information

- Node.js version:18.19.1
- NPM version:10.2.0
- Strapi version:4.23.1
- Database:postgres
- Operating system: Window 10
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have installed strapi and register for the first time. Then I created a user of "Editor role". After it, now I open "/admin/auth/register", it is showing me disabled email field.

### Steps to reproduce the behavior
Sorry, but I dont remember the proper steps.

### Expected behavior

Email field should not be disabled

### Screenshots

![Screenshot 2024-04-18 at 21-02-23 Strapi Admin](https://github.com/strapi/strapi/assets/156778533/87507dc1-06bb-4820-97c0-e8ebb5fe9875)

Correct me if I am wrong at any step....

**Comment by kasonde** [comment]
In order for the new user to be able to register onto the Strapi admin, you need to send them the invite link that you get in the dialog box that pops up after successfully creating the user. That invite link will automatically fill in all detail that you, the admin, created and only allow the editor user to set a new password and confirm it. 

Please let us know if that helped. For now, I'll go ahead and close this issue.
