### ISSUE TITLE
if mongo shuts down all data is lost

### ISSUE THREAD

**Issue by mikkokotila** [strapi/strapi#2017]
**Node.js version** >> 10.1
**npm version** >> 5.6
**Strapi version** >> 3.0.0-alpha.12.2
**Database** >> mongodb
**Operating system** >> centos

**What is the current behavior?**

When mongodb was shut down (maybe not gracefully if that's a thing with mongo) all the data except the initial user was lost from strapi

**Steps to reproduce the problem**

Follow the getting started instruction, and start mongo not as a service but from:

`mongod
`
...terminate the terminal session.

**What is the expected behavior?**

It seems that losing all your data because of a database issue is undesirable. Or did miss something?

**Comment by lauriejim** [comment]
Hello @mikkokotila. I think the error come from your side.
Did you have a tool to connect to your Mongo database when it's running (like Robo Mongo)

**Comment by mikkokotila** [comment]
@lauriejim No it was a fresh centOS where I did nothing but install node and mongo and then strapi.

**Comment by lauriejim** [comment]
Try with last version of Strapi.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
