### ISSUE TITLE
Plugin missing from admin build

### ISSUE THREAD

**Issue by johncalvinroberts** [strapi/strapi#2018]
**Informations**
- **Node.js version**:v10.6.0
- **npm version**:6.4.1
- **Strapi version**:3.0.0-alpha.14
- **Database**:mongo
- **Operating system**:mac os

**What is the current behavior?**
Plugin `Content-type-builder` missing from admin build. When I try to go directly to `/plugins/content-type builder` it displays a notifications telling me to turn on auto reload in `server.json`.

I also tried deleting the `/plugins/content-type-builder` and re-installing via `strapi install content-type-builder`, but to no avail. Same behavior.

**Steps to reproduce the problem**
To be honest not sure, it kind of just disappeared at some point in time after I ran `npm run setup` a few times

**What is the expected behavior?**
Plugin `Content-type-builder`appears in admin build in list of plugins

**Suggested solutions**
Not sure sorry 😭

**Comment by soupette** [comment]
Can you make sure the autoReload config is activated?

You can check by in `my-app/config/development/server.json` file.

```
{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": false
  },
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
```

**Comment by johncalvinroberts** [comment]
@soupette yep, autoReload is enabled.

Is this related to production environment? Does `content-type-builder` get hidden in production mode?

**Comment by johncalvinroberts** [comment]
My mistake -- content-type-builder is not accessible in production mode, when `NODE_ENV=production`

Closing this out, my bad

**Comment by soupette** [comment]
Yes!

**Comment by derrickmehaffy** [comment]
@johncalvinroberts you shouldn't be "testing" or building in production ;)

That being said you can still kinda access, @soupette just hid the link lol

**Comment by soupette** [comment]
@derrickmehaffy I'm going to remove it completely from the admin since I'm improving the way a plugin is registered...

**Comment by derrickmehaffy** [comment]
That is a good idea :wink:
