### ISSUE TITLE
Strapi transfer does not work with aws waf standard rules

### ISSUE THREAD

**Issue by imfrostii8** [strapi/strapi#20183]
### Required System information

- Node.js version: v21.5.0
- NPM version: 10.2.4
- Strapi version: 4.15.5
- Database: postgresql

### Describe the bug

When running strapi transfer from or to a remote hosted on aws with a standard waf it shows: error: [FATAL] Failed to initialize the connection: Authorization Error
Transfer process failed.

The waf runs the core rule set based on vulnerabilities published by OWASP.

### Steps to reproduce the behavior

1. Start a new strapi project.
2. Deploy it to aws with a waf in front of it.
3. Run the strapi transfer command from or to the remote instance.

### Expected behavior

It should transfer data normally to and from the remote instance.

### Additional context

Disabling the wof solves the issue

**Comment by derrickmehaffy** [comment]
DTS auth is no different than normal user auth since it uses a bearer token in an authorization header.

Closing as a question since this really isn't related to us and is more so about properly configuring the WAF for authorization header usage.
