### ISSUE TITLE
[Strapi 5 Beta]  Maximum call stack size exceeded error when using a self-referencing relationship

### ISSUE THREAD

**Issue by anderland** [strapi/strapi#20187]
## Bug report

Environment: development
Node.js version: v18.18.2
NPM version: 9.8.1
Strapi version: 5.0.0-beta.4
Database: postgreSQL
Operating system: macOS
Javascript

### Description

When populating a self-referencing relationship I consistently get `error: Maximum call stack size exceeded`. This is true for oneToOne, oneToMany and manyToMany.

### Expected behavior

The self-referencing relationship would work like it did in Strapi 4, without errors

### Screenshots

<img width="700" alt="Screenshot 2024-04-23 at 12 44 13 PM" src="https://github.com/strapi/strapi/assets/6415892/a31c32c0-0cbd-48de-94d3-cfca9c4257e4">

### Code snippets

`"parent": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::module.module",
      "inversedBy": "children"
    },
    "children": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::module.module",
      "mappedBy": "parent"
    }`

### Additional context (console log)

`[2024-04-23 10:27:57.767] error: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
at String.indexOf (<anonymous>)
at wrapString (/my-project/node_modules/knex/lib/formatter/wrappingFormatter.js:139:39)
at wrapString (/my-project/node_modules/knex/lib/formatter/wrappingFormatter.js:154:20)
at wrap (/my-project/node_modules/knex/lib/formatter/wrappingFormatter.js:95:14)
at get tableName [as tableName] (/my-project/node_modules/knex/lib/query/querycompiler.js:1472:11)
at QueryCompiler_PG.del (/my-project/node_modules/knex/lib/dialects/postgres/query/pg-querycompiler.js:85:13)
at QueryCompiler_PG.toSQL (/my-project/node_modules/knex/lib/query/querycompiler.js:75:29)
at unwrapRaw (/my-project/node_modules/knex/lib/formatter/wrappingFormatter.js:102:41)
at Client_PG.parameter (/my-project/node_modules/knex/lib/client.js:409:12)
at QueryCompiler_PG.\_valueClause (/my-project/node_modules/knex/lib/query/querycompiler.js:988:21)`

I tried to reproduce the error in a quickstart instance but it seems to work there so it must be in some way related to the db.

**Comment by petrmifek** [comment]
Might be related to #19977 - observing the behaviour with all relation, not only self-referencing ones.

Re repro - from my observation, a small catch is that it works for first time, which makes it easy to overlook. It starts failing only after the relation is cleared first time.

**Comment by anderland** [comment]
In my case, I am not encountering any errors with all relations, only with the self-referencing ones, even after repeating the steps described in [#19977](https://github.com/strapi/strapi/issues/19977)

**Comment by derrickmehaffy** [comment]
> Might be related to #19977 - observing the behaviour with all relation, not only self-referencing ones.
> 
> Re repro - from my observation, a small catch is that it works for first time, which makes it easy to overlook. It starts failing only after the relation is cleared first time.

That's great reproduction information

**Comment by derrickmehaffy** [comment]
Can't reproduce with beta.5

**Comment by petrmifek** [comment]
Unfortunately we're still seeing this issue with beta.5

I took the liberty to prop up a repository with a sample docker compose environment to reproduce the issue, I still can reproduce it on beta5, hopefully it's not just used wrong...

The repository is at https://github.com/anapol/strapi5-repro

It contains 3 branches and a readme how to repro:
- main: this is for testing with a fresh start with a new a strapi project
- selfreferencing: includes strapi project demonstrating #20187
- intracollection:  includes strapi project demonstrating #19977

Thanks!

**Comment by petrmifek** [comment]
The issue seems to be exclusively related to PostgreSQL, SQLite and MySQL seems to be working fine in both cases.

**Comment by derrickmehaffy** [comment]
> The issue seems to be exclusively related to PostgreSQL, SQLite and MySQL seems to be working fine in both cases.

Gotcha, I was testing with SQLite so that makes sense. Will test with PG then.

**Comment by kasonde** [comment]
Confirmed

**Comment by alexandrebodin** [comment]
Fixed

**Comment by DavidCodesDev** [comment]
I have this issue in strapi 5.0.2, I have programmatically enabled dynamic zones inside of components (which allows me to have components inside of components via dynamic zones). So having a self referencing component inside of a component causes this crash. I know this is not supported by Strapi before you guys grill me on this, but this might be an issue in other parts of Strapi?

**Comment by siarheiSiniauski** [comment]
```
RangeError: Maximum call stack size exceeded
    at Function.values (<anonymous>)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BHDQUVS6.js?v=46a708f1:870:44
    at Array.reduce (<anonymous>)
    at getComponents (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BHDQUVS6.js?v=46a708f1:867:24)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BHDQUVS6.js?v=46a708f1:873:42
    at Array.reduce (<anonymous>)
    at getComponents (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BHDQUVS6.js?v=46a708f1:867:24)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BHDQUVS6.js?v=46a708f1:873:42
    at Array.reduce (<anonymous>)
    at getComponents (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BHDQUVS6.js?v=46a708f1:867:24)
```
