### ISSUE TITLE
Dependency of koa-body has a critical vulnerability

### ISSUE THREAD

**Issue by Rowan-Paul** [strapi/strapi#20181]
### Required System information

- Node.js version: v18.19.0
- NPM version: 10.2.3
- Strapi version: 4.23.1
- Database: sqlite
- Operating system: MacOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

There's a critical vulnerability in `formidable`, a dependency of `koa-body` that Strapi uses in both v4 and the v5 beta.

### Steps to reproduce the behavior

1. Run `yarn audit` or `npm audit` inside Strapi project

### Expected behavior

There's a critical vulnerability in the `koa-parser`, specifically the `formidable` dependency.

### Screenshots

<img width="731" alt="image" src="https://github.com/strapi/strapi/assets/46132597/c79579bf-9020-455b-b0da-ca99e791771c">

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

The vulnerability is solved in version 3.2.4 of `formidable`, there's already a [pull request open for the `koa-body` repository](https://github.com/koajs/koa-body/pull/232) that updates the version of formidable used there. Doesn't look like that will be merged soon, as it has been open since October.

- [GitHub advisory](https://github.com/advisories/GHSA-8cp3-66vr-3r4c)

**Comment by briankandersen** [comment]
I get this as well. SysDig is reporting this! 

![image](https://github.com/strapi/strapi/assets/32012293/5bb6f2b1-0371-4022-a956-fcbb9cb0643d)

**Comment by derrickmehaffy** [comment]
Closing this as is violates our security policy, we are aware and are looking into it.

**Comment by derrickmehaffy** [comment]
see: https://github.com/strapi/strapi/issues/20189
