### ISSUE TITLE
Node v6 support

### ISSUE THREAD

**Issue by GreenGremlin** [strapi/strapi#202]
Are there plans to support node v6 in Strapi v3, as it is the current LTS branch of node? Many companies are only willing to run LTS versions of node, as such it would be a shame if Sami v3 did not support any LTS version.

**Comment by dj-hedgehog** [comment]
Strapi v3 is using Koa v2 and therefore needs native `async..await` which is only available in Node v7.0+.

While this may drive away some companies it is a good strategy because this means there will be less breaking changes in the future.

**Comment by Aurelsicoko** [comment]
Perfect answer @dj-hedgehog! Thanks 👍

**Comment by Aurelsicoko** [comment]
I close this issue, we just released the v1.6.0 of Strapi which supports Node v4+.

http://blog.strapi.io/release-v1-6/
