### ISSUE TITLE
Delete an associated file/image upon deletion of row

### ISSUE THREAD

**Issue by hunter-isaiah96** [strapi/strapi#2020]
**What is the expected behavior?**
It would be awesome if when you delete a row from a content type, you can have the option to delete any associated files from it as well. I'm using a cloudinary provider and I don't want unnecessary images stored in my account upon changing the image of the post

**Comment by minvedacat** [comment]
You may dig into `api/your_content_type_name/`, modify `controllers` and `services` to satisfy yourself.
In generated `services/Entry.js` you can find
```
await Promise.all(
      Entry.associations.map(async association => {
        const search = _.endsWith(association.nature, 'One') || association.nature === 'oneToMany' ? { [association.via]: data._id } : { [association.via]: { $in: [data._id] } };
        const update = _.endsWith(association.nature, 'One') || association.nature === 'oneToMany' ? { [association.via]: null } : { $pull: { [association.via]: data._id } };

        // Retrieve model.
        const model = association.plugin ?
          strapi.plugins[association.plugin].models[association.model || association.collection] :
          strapi.models[association.model || association.collection];

        return model.update(search, update, { multi: true });
      })
    );
```
If you store file association then you probably check any file association to call its `remove` and make sure there is corresponding removal code in the services code of your file content type.

I am also trying to generate image with Strapi, good luck🍀

**Comment by henrych4** [comment]
How about adding delete file action in controllers of `strapi-plugin-content-manager`?


Check [here](https://github.com/strapi/strapi/blob/c5df8f16087fb0560604b602c856da7a8641c6d4/packages/strapi-plugin-content-manager/controllers/ContentManager.js#L98), every time you delete a row of a content type from admin panel, `ContentManager.delete` is called. And you can get the model and row id from `ctx.params`. Once you have the model and id, you can first get associated files by `fetch` method in `api/[model_name]/service/`, and then call [remove](https://github.com/strapi/strapi/blob/c5df8f16087fb0560604b602c856da7a8641c6d4/packages/strapi-plugin-upload/services/Upload.js#L138) method provided in `plugins/upload/services/Upload.js` to delete file.

Looking forward to official implementation.

**Comment by Aurelsicoko** [comment]
It should be an option in the Content Manager but it's more complicated than you can imagine. An image can theoretically be associated with multiple entries. So it means that the image shouldn't be deleted until it still related to another entry. But, if it was the latest entry related to this image, the image should be deleted, only if, the option has been checked.

**Comment by Aurelsicoko** [comment]
Recently, we decided to close issues which are not real issues. However, everyone can still comment and give his thoughts on the issue. Some features requests will be transfered on the Product Board, sometimes privately or in the public roadmap.

This is the reason, I'm closing the issue. The debate is still open though...

**Comment by Selva1994cse** [comment]
![Uploading buildings-with-trees.jpg…
![279f1e3c0f4f42ca9c8137add5ff4a80](https://user-images.githubusercontent.com/56438430/68563226-d8e6ab00-0472-11ea-8933-c970a19c6ae1.jpg)
]()
