### ISSUE TITLE
Installation withMariaDB

### ISSUE THREAD

**Issue by samkonix** [strapi/strapi#20210]
Hi,

i want to test strapi to see if i can install it on o2switch

My installation is going wrong

I'm on a Win11 PC, here is my CLI installation command line:
`
npx create-strapi-app@latest lcdr --typescript --dbclient=mysql --dbhost=localhost --dbport=3306 --dbname=lcdr --dbusername=strapi --dbpassword=@I5yV@#Y4% --dbssl=false --dbforce --debug
`

I have no error at the installation but I can't run strapi, it seems it can't connect to database

PS C:\Users\Sam\Documents\Projets\lcdr\lcdr> npm run develop

> lcdr@0.1.0 develop
> strapi develop

✔ Cleaning dist dir (13ms)
⠋ Building build context
⠙ Building build context[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (245ms)
✔ Creating admin (21185ms)
⠼ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                             │
│   Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'strapi'@'localhost' (using password: YES)                                          │
│       at Sequence._packetToError (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)     │
│       at Handshake.ErrorPacket (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)     │
│       at Protocol._parsePacket (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\Protocol.js:291:23)                │
│       at Parser._parsePacket (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\Parser.js:433:10)                    │
│       at Parser.write (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\Parser.js:43:10)                            │
│       at Protocol.write (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\Protocol.js:38:16)                        │
│       at Socket.<anonymous> (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\Connection.js:88:28)                           │
│       at Socket.<anonymous> (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\Connection.js:526:10)                          │
│       at Socket.emit (node:events:518:28)                                                                                                   │
│       at Socket.emit (node:domain:488:12)                                                                                                   │
│       --------------------                                                                                                                  │
│       at Protocol._enqueue (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\Protocol.js:144:48)                    │
│       at Protocol.handshake (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\protocol\Protocol.js:51:23)                    │
│       at Connection.connect (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\mysql\lib\Connection.js:116:18)                          │
│       at C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\knex\lib\dialects\mysql\index.js:66:18                                       │
│       at new Promise (<anonymous>)                                                                                                          │
│       at Client_MySQL.acquireRawConnection (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\knex\lib\dialects\mysql\index.js:61:12)   │
│       at create (C:\Users\Sam\Documents\Projets\lcdr\lcdr\node_modules\knex\lib\client.js:262:39)                                           │
│                                                                                                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

MariaDB is running and I have created the lcdr database and the strapi user.

`PS C:\Users\Sam> mysql.exe -u strapi -p@I5yV@#Y4% -h localhost lcdr
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 18
Server version: 11.3.2-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [lcdr]>

Environment: development
OS: win32-x64
Strapi Version: 4.24.0
Node/Yarn Version: npm/10.5.2 node/v20.12.2 win32 x64 workspaces/false
Edition: Community
Database: mysql (MariaDB win32 11.3)

Could you help me ?

**Comment by samkonix** [comment]
It work when I change the password.
Something is bad with @I5yV@#Y4%

**Comment by derrickmehaffy** [comment]
This doesn't look like a Strapi bug but most likely an issues with the SQL driver itself, will mark this as closed since it's largely unrelated to us and is either an issue with Knex.js or the mysql packages
