### ISSUE TITLE
Condensed Main Nav:  icons are misaligned + Strapi logo redirecting to Homepage is not clickable anymore

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20227]
### Required System information

- Node.js version: 20.9.0
- Strapi version: v5.0.0-beta.5
- Operating system: Windows

### Describe the bug

When you look at the left Main Nav sidebar, in condensed mode, icons are not aligned with Strapi Logo which is not clickable to reach the Homepage (as it is in non-consensed mode).

### Steps to reproduce the behavior

1. Login 
2. Click on arrow button on bottom left of your screen next to User name
3. Check consensed main nav buttons are not aligned with Strapi logo anymore
4. Try to click on Strapi logo to reach the Homepage

### Expected behavior

In condensed mode, main nav icons should be aligned with Strapi logo and Strapi logo should be clickable to reach the Homepage.

### Screenshots

![image](https://github.com/strapi/strapi/assets/97893822/92e48983-1286-49b6-9a22-eefa58049b7c)

**Comment by simotae14** [comment]
Thanks Marion, the behaviour (no behaviour) of the logo is the correct one for the new Main nav and regarding the misalignment it is just a matter of new ui versus old ui, I am currently working on change the UI dimension of the condensed nav

**Comment by alexandrebodin** [comment]
Test in beta-9 it's fixed
