### ISSUE TITLE
[BUG] Strapi loses the connection to the server after saving changes on entities

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#20220]
### Required System information

- Environment: development
- OS: linux-x64
- Strapi Version: 5.0.0-beta.5
- Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
- Edition: Community
- Database: sqlite
- Typescript

### Describe the bug
Every time we save changes on any entity, either creating or updating it, the admin panel disconnects from the backend and we have to manually refresh the browser to get the admin back.

### Steps to reproduce the behavior

1. Go to the **Content Manager**.
2. Click on the Collection Type you will work with.
3. Create/Update any entity from the Collection Type.
4. Fill the fields.
5. Save the changes.
6. Wait until the animation is finished.
7. See the error.
8. Click on Try Again.
9. See the admin back.

### Expected behavior
It should refresh itself instead of losing connection to the backend.

### Screenshots
![StrapiDoesNotRefreshAfterSavingEntities](https://github.com/strapi/strapi/assets/5034215/502cfadf-9ee3-48d3-aa99-d66059699ecf)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context
It is a basic project, with not third-party plugins on it.

**Comment by derrickmehaffy** [comment]
I've noticed this as well but I just get a "can't connect" page which looks quite ugly.

**Comment by pwizla** [comment]
Having the same on Firefox, and it's 100% reproducible with the CTB (see my screen capture below).
It seems purely front-end (🤔?) as the terminal (backend) does not log any connection issue.

https://github.com/strapi/strapi/assets/4233866/e92085b3-0ff2-49af-b035-d9044179af7f

**Comment by derrickmehaffy** [comment]
It.is absolutely the switch to vite that is the cause since it refreshes before the backend has restarted. Most browsers will try again but Firefox does not it seems.

**Comment by derrickmehaffy** [comment]
It appears to partially restart if the `.env` changes when I'm not really sure if it should restart at all or at the very least it should do a full restart.

**Comment by SalahAdDin** [comment]
> It appears to partially restart if the `.env` changes when I'm not really sure if it should restart at all or at the very least it should do a full restart.

I don't change it in any time.
