### ISSUE TITLE
Issue template on github is not updated.

### ISSUE THREAD

**Issue by henrych4** [strapi/strapi#2023]
**Informations**
- **Node.js version**: *
- **npm version**: *
- **Strapi version**: *
- **Database**: *
- **Operating system**: *

**What is the current behavior?**
The bug report template on github is not updated with homepage.
On [homepage](https://github.com/strapi/strapi), the node requirements of strapi are:
* NodeJS >= 10.x
* NPM >= 6.x
 
However bug report template, it shows:
```
<!-- ⚠️ Before writing your issue make sure you are using:-->
<!-- Node 9.x.x -->
<!-- npm 5.x.x -->
<!-- The latest version of Strapi. -->
```
This can be quite confusing.

**Steps to reproduce the problem**
Open a bug report on issue of github and you can see the outdated template.

**What is the expected behavior?**
Show the correct node requirement.

**Suggested solutions**
Update bug report template under .github folder.

**Comment by derrickmehaffy** [comment]
Nice catch @henrych4, I think a quick PR should resolve this if you want to create one?

**Comment by maturanomx** [comment]
Actually, is not the requirements wrong? 🤔

I remember Strapi supports Node 9.x, when and what change that?

**Comment by derrickmehaffy** [comment]
@maturanomx https://github.com/nodejs/Release#release-schedule

When I spoke with the Strapi team they gave me the expected requirements. Since LTS node version will be v10 in october of this year that was the intended version. Node v9 was a testing release to fix bugs in v8. Was never actually ment to be used in production.

**Comment by derrickmehaffy** [comment]
Note V9 is actually EOL already: `2018-06-30`

**Comment by maturanomx** [comment]
Fine then. Thanks for the information 👍

BTW, the PR related is #2026

**Comment by soupette** [comment]
If I may add we should also update the engines...

**Comment by derrickmehaffy** [comment]
@lauriejim The issue templates were fixed in my PR:

https://github.com/strapi/strapi/pull/2039

Not sure what else needs to be changed for this to be closed.

**Comment by lauriejim** [comment]
Yap, can you next time add `fix #issue` in the PR description or in the commit message to automatically close related issue when the PR is merged. 

Thank you for the PR you did.

**Comment by derrickmehaffy** [comment]
noted thanks @lauriejim
