### ISSUE TITLE
GET /upload/files or any GET from content-types always returns 401. 

### ISSUE THREAD

**Issue by Luis-txd** [strapi/strapi#20244]
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.21
- Database: PostgresSQL
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am developing my own plugin and i need access to the admin content-types and the files in the Media Library. 
While using the useFetchClient, and properly setting the authorization token as the one in the local storage, any request to the content types or the media library return 401 (Unauthorized).

This issue happens even when the find and findOne are allowed for public access (and through the browser, i am able to acess that data).

### Code snippets

~~~
const { get } = useFetchClient()

const fetchTags = async() => {
      await get("/api/news-tags", {
        headers: {
          "Authorization": "Bearer " + localStorage.getItem("token"),
        }
      })
        .then((response: any) => {
          console.log(response)
        })
        .catch((err:any) => {
          console.log("Err:", err);
        })
    }

fetchTags();
~~~

Thanks in advance for the help

**Comment by shubham9069** [comment]
Hi @Luis-txd  can you please describe more about it? please share the details about bug?

**Comment by Luis-txd** [comment]
What more information should i provide?
Basically any request to get the different content types from the admin return 401. Even if they are publicly accessible (i can access them through the browser, but never in the plugin).

That solution did not resolve the problem @shubham9069

**Comment by shihanjun19** [comment]
**Description**

I have configured the routes for a plugin in Strapi, but some routes return a 401 error when called. Below is the specific route configuration and error log.

**Error Log**

[2024-06-07 20:45:16.824] http: POST /wechat-auth/phone (13 ms) 401

yaml
复制代码

**Route Configuration**

```javascript
export default [

  {
    method: 'POST',
    path: '/login',
    handler: 'wechatController.login',
    config: {
      auth: false,
      policies: [],
    },
  },
  {
    method: 'POST',
    path: '/phone',
    handler: 'wechatController.getUserPhoneNumber',
    config: {
      policies: [],
    },
  },
];
```
Strapi Version: v4.24.4
Plugin Name: wechat-auth

![微信截图_20240607204552](https://github.com/strapi/strapi/assets/10006241/f3fd136a-c9b9-43cf-b053-a69964be7071)
