### ISSUE TITLE
Filter by text field with "&" symbol doesn't work

### ISSUE THREAD

**Issue by amazhukin** [strapi/strapi#20271]
### Required System information
- Node.js version: 18.20.2
- Yarn version: 1.22.22
- Strapi version: v4.24.1
- Database: postgres
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Filter by text field with "&" symbol doesn't work. Search string is cut up to & symbol and no results with "is" operand

### Steps to reproduce the behavior

1. Create any entity at collection type that text field contains ampersand (&) symbol.
  Eg, create article with title "Test article & issue reproduce"
![image](https://github.com/strapi/strapi/assets/46565276/45583861-aee0-4676-a799-e95fd37bd7c9)
2. Go to list of collection type and using "Filters" button select text field, "is" operand and text with & symbol
![image](https://github.com/strapi/strapi/assets/46565276/9f4de5c7-ebe8-4cc0-a419-741dec696377)
3. Click "Add filter"
4. Check what filter is applied
![image](https://github.com/strapi/strapi/assets/46565276/8358f163-5c7b-4177-ad09-520b90d967cb)

### Expected behavior

Filter should be applied correctly and display found record, like if there are no & symbol in search:
![image](https://github.com/strapi/strapi/assets/46565276/415c28ca-fb0a-447e-940f-7aa27f65afed)

### Additional context
Some details from network tab:
Request URL:
`http://127.0.0.1:1337/content-manager/collection-types/api::article.article?page=1&pageSize=10&sort=title:ASC&filters[$and][0][title][$eq]=Test%20article%20&%20issue%20reproduce=`
Query parameters that applied:
```
page: 1
pageSize: 10
sort: title:ASC
filters[$and][0][title][$eq]: Test article 
 issue reproduce: 
```
![image](https://github.com/strapi/strapi/assets/46565276/fa98341b-2dcd-4b3f-9883-54c8c2e48e86)

**Comment by simotae14** [comment]
I am gonna close it because it was fixed with this PR https://github.com/strapi/strapi/pull/21406
