### ISSUE TITLE
Strapi 5.0.0-beta.6 doesn't show Users & Permissions plugin in settings

### ISSUE THREAD

**Issue by circular-dependency** [strapi/strapi#20279]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 5.0.0-beta.6
- Database: default (when using quickstart)
- Operating system: MacOS 14
- Is your project Javascript or Typescript: Javascript (same issue using Typescript)

### Describe the bug

When creating a new Strapi (5.0.0-beta.6) project using `npx create-strapi-app@beta my-project --quickstart`, the `Users & Permissions Plugin` doesn't show up in settings in the admin panel. I'm using the default Super Admin user, so access permissions shouldn't be a problem.

I also made an API call to the plugin and got the correct response. Only the UI doesn't seem to show up.

I tried downgrading all beta.6 versions to beta.5 in my package.json file. It then worked using beta.5.

I hope there isn't already an open issue regarding this problem. I looked through the issue list, but couldn't find any.

### Steps to reproduce the behavior

1. Create a new Strapi app from the command line: `npx create-strapi-app@beta my-project --quickstart`
2. Wait for Strapi to start up and create your admin user
3. See `Users & Permissions Plugin` is missing in the settings section

### Expected behavior

`Users & Permissions Plugin` to show up in the admin panel under `Settings`.

**Comment by derrickmehaffy** [comment]
Is it listed in your package.json?

**Comment by circular-dependency** [comment]
@derrickmehaffy Hi, thanks for your response. Yes it is. These are the dependencies from my package.json:

    "dependencies": {
        "@strapi/strapi": "5.0.0-beta.6",
        "@strapi/plugin-users-permissions": "5.0.0-beta.6",
        "@strapi/plugin-cloud": "5.0.0-beta.6",
        "better-sqlite3": "9.4.3",
        "react": "^18.0.0",
        "react-dom": "^18.0.0",
        "react-router-dom": "^6.0.0",
        "styled-components": "5.3.3"
    }
    
All I did was create a new Strapi app, using the CLI: `npx create-strapi-app@beta my-project --quickstart`

**Comment by derrickmehaffy** [comment]
Hmm interesting 🤔

**Comment by circular-dependency** [comment]
I noticed 5.0.0-beta.7 just got released. With this version `Users & Permissions Plugin` is now visible again in the admin panel. Thank you!
