### ISSUE TITLE
Strapi date format for "date" based fields unknown

### ISSUE THREAD

**Issue by hansemannn** [strapi/strapi#2029]
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: latest
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**
When using the `date` based fields, it is unknown how the type is expected to look like. I would expect it to be a unique timestamp (number-based), but it seems like submitting that to the field results in `1970-01-18 19:13:00`. In the other hand, returning the date through an API should also return the timestamp, since it's the easiest way to convert /format it across all platforms. Instead, it looks like some kind of mixed format that needs to be converted manually. Please advice here, thanks!

**Steps to reproduce the problem**
Create a `date` based type and work with it (POST / GET)

**What is the expected behavior?**
The type should be returned as a timestamp

**Suggested solutions**
See above, or advice which format to use. Thanks!

**Comment by lauriejim** [comment]
Can you precise the version of Strapi you use please. *Latest* is not enough.

**Comment by hansemannn** [comment]
3.0.0.alpha-14.2

**Comment by yummyelin** [comment]
`Date` field in Strapi is in JS date format:
```
Fri Sep 28 2018 12:00:00 GMT-0700 (Pacific Daylight Time)
```

In database (mongodb), `Date` is stored like this:
```
"createdAt": {
        "$date": "2018-09-15T00:17:11.790Z"
 },
```

When setting or returning `Date` through API, it is in ISO date format:
```
"createdAt": "2018-09-15T00:17:11.790Z"
```

I think date format is better than timestamp. So when printing the `Date` field, I can know the exact date and time directly without getting lost in the numbers(timestamp)

**Comment by hansemannn** [comment]
I agree if the environment remains JavaScript. For larger scale multi-platform clients that consume an API (e.g. iOS and Android), the date needs to be manually specified with the format in order to be parsed as a native date. Timestamps on the other side can be used in nearly every native `Date` constructor, so the developer can decide if only the day/month/year or a special format is used in the end. Just my 2 cents. For now, I workarounded it by specifying a format for it that matches this string.

**Comment by lauriejim** [comment]
Thank you for your feedback. There is PR about that https://github.com/strapi/strapi/pull/1439
