### ISSUE TITLE
Database name keeps reverting to 'postgresql'

### ISSUE THREAD

**Issue by mraak** [strapi/strapi#203]
**Node.js version**: 7.4
**npm version**: 4.0.5
**Strapi version**:  1.6.1
**Operating system**: Windows 7

In Studio I set up a new DB connection for Postgres. Then I went to edit the Connection Identifier, and when I saved it, it changed the ID successfully, but it also changed the Database Name to 'postgresql' and when I try and change it again, it again always defaults to 'postgresql' and I get an amber warning saying "Connection pg1 already defined".

This happens for any field I change in connection edit form. The workaround is to create a new connection but that is impossible once you have API's defined.

**Comment by Aurelsicoko** [comment]
This feature is not on our roadmap and we won't do it. Thanks for the suggestion though.

**Comment by mraak** [comment]
It wasn't a feature suggestion but a bug report 👎
