### ISSUE TITLE
I can't add one component to another component

### ISSUE THREAD

**Issue by JAZzmiX** [strapi/strapi#20302]
### Required System information

- Node.js version: node/v18.12.1 linux x64
- NPM version: 8.19.2
- Strapi version: 4.24.2
- Yarn version: 1.22.19
- Database: PostgreSQL 12.18
- Operating system:  linux-x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug
if I add the component to the component gives me an error

> error: create index "components_trip_coverage_section_trip_coverage_sections_component_type_index" on                                                                              ││   "public"."components_trip_coverage_section_trip_coverage_sections_components" ("component_type") - relation "components_trip_coverage_section_trip_coverage_sections_compone"      ││   already exists                                                                                              
<img width="1420" alt="Screenshot 2024-05-13 at 15 48 18" src="https://github.com/strapi/strapi/assets/3510648/bb54e29a-dd91-414c-b63a-bd84420e9e9f">

### Steps to reproduce the behavior

I add one component to another
<img width="518" alt="Screenshot 2024-05-13 at 16 01 35" src="https://github.com/strapi/strapi/assets/3510648/7b733aa4-3fd4-43f9-adeb-ca83f0bd1532">

**Comment by joshuaellis** [comment]
Can you write actual reproduction steps please? what you've provided is not enough for anyone to debug.

**Comment by JAZzmiX** [comment]
> Can you write actual reproduction steps please? what you've provided is not enough for anyone to debug.


created  component name: "`trip_coverage_section`"   then created component  name: "`birthday`",   added component "`birthday`" to component "`trip_coverage_section`"  
then the console shows the error:

> error: create index "components_trip_coverage_section_trip_coverage_sections_component_type_index" on ││ "public"."components_trip_coverage_section_trip_coverage_sections_components" ("component_type") - relation "components_trip_coverage_section_trip_coverage_sections_compone" ││ already exists

**Comment by joshuaellis** [comment]
And you created this in the `ui`? :)

**Comment by derrickmehaffy** [comment]
The UI in v4 restricts component nesting to 2 levels, we will allow deeper nesting beyond 2 levels via the UI in Strapi 5 but nothing is planned for v4
