### ISSUE TITLE
Make DB connection options more transparent

### ISSUE THREAD

**Issue by maturanomx** [strapi/strapi#2030]
**What is the expected behavior?**
Strapi uses Knexjs for manage DB connections, but it's not using all the options available.

---

This story begins with me trying to deploy Strapi on [Pivotal](https://pivotal.io/)'s [Could Foundry](https://www.cloudfoundry.org/) using the free MySQL service plan with a limitation up to 4 connections:
![capture](https://user-images.githubusercontent.com/5768813/46105799-9bef2480-c19c-11e8-999e-2c05e194196d.PNG)

Apparently, Strapi is using more that than just for starting according the logs:
```
[APP/PROC/WEB/0] ERR (node:147) UnhandledPromiseRejectionWarning: Error: ER_USER_LIMIT_REACHED: User 'bf662ec45746cc' has exceeded the 'max_user_connections' resource (current value: 4)
```

Looking for a solution, I see [Knexjs allows to configure the pool connection](https://knexjs.org/#Installation-pooling):

> To change the config settings for the pool, pass a pool option as one of the keys in the initialize block

But seeing the code:

1. Strapi pick just [some specific options](https://github.com/strapi/strapi/blob/bf355c89110dde969cdc1648d1f959cb1cf3dc7e/packages/strapi-hook-knex/lib/index.js#L104)
 2. Some options are limited by engine ([like this, the pool one](https://github.com/strapi/strapi/blob/bf355c89110dde969cdc1648d1f959cb1cf3dc7e/packages/strapi-hook-knex/lib/index.js#L113)]

**Question**: Wouldn't it be better to make this configuration match Knexjs? The Strapi database configuration should match Knexjs available options.

Request for comments before begin to work with a patch.

**Comment by derrickmehaffy** [comment]
+1

**Comment by Aurelsicoko** [comment]
@maturanomx Good catch! We could remove the limitation, your use case justifies the changes. Can you make a PR for this?

**Comment by Aurelsicoko** [comment]
Awesome!!

**Comment by petersg83** [comment]
Is this issue still ongoing?

**Comment by derrickmehaffy** [comment]
> Is this issue still ongoing?

I don't believe it's an issue anymore as we now pass along the tarn.js option parameters through to knex (connection pooling options). Going to mark this as closed, please let us know if we missed something and we can reopen.
