### ISSUE TITLE
Cloning icons on the panel

### ISSUE THREAD

**Issue by dmitriyKvant** [strapi/strapi#20300]
### Required System information

- Node.js version: v20.12.2
- Yarn version: v4.2.2
- Strapi version: v5.0.0-beta.7
- Database: postgres
- Operating system: Windows 11, version 23H2
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Whenever you interact with the interface, a new Releases icon appears in the panel

### Steps to reproduce the behavior

1. Create a new project strapi v5 with yarn pnp
2. Add all required dependencies to work with pnp(code below)
3. Add `enableGlobalCache: false` to .yarnrc.yml to work correctly with vite 

### Expected behavior

No unnecessary icons should appear when interacting with the interface 

### Screenshots

![image](https://github.com/strapi/strapi/assets/157316564/0e7fd3c8-3611-47d4-be8d-2605f2c52f18)

### Additional context

```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@codemirror/state": "^6.4.1",
    "@codemirror/view": "^6.26.3",
    "@strapi/admin": "5.0.0-beta.7",
    "@strapi/content-manager": "5.0.0-beta.7",
    "@strapi/content-releases": "5.0.0-beta.7",
    "@strapi/content-type-builder": "5.0.0-beta.7",
    "@strapi/data-transfer": "5.0.0-beta.7",
    "@strapi/email": "5.0.0-beta.7",
    "@strapi/i18n": "5.0.0-beta.7",
    "@strapi/icons": "2.0.0-beta.3",
    "@strapi/plugin-cloud": "5.0.0-beta.7",
    "@strapi/plugin-users-permissions": "5.0.0-beta.7",
    "@strapi/review-workflows": "5.0.0-beta.7",
    "@strapi/strapi": "5.0.0-beta.7",
    "@strapi/upload": "5.0.0-beta.7",
    "koa": "2.13.4",
    "pg": "8.8.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-redux": "^9.1.2",
    "react-router": "^6.23.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
  "strapi": {
    "uuid": "cd6b77f9-660f-4a6e-b9c3-83dce0d8ea27"
  },
  "license": "MIT",
  "devDependencies": {
    "@strapi/typescript-utils": "5.0.0-beta.7",
    "@types/koa": "^2",
    "@types/node": "^20.12.11"
  },
  "packageManager": "yarn@4.2.2"
}
```

**Comment by Eventyret** [comment]
`v5.0.0-beta.8` can't replicate this BUT will report it as a bug  as it still starts off with 2x `releases` icons

![Image](https://github.com/strapi/strapi/assets/977232/e0c3d585-6438-48ff-b3fc-b611e8d18aed)

**Comment by simotae14** [comment]
I closed the issue because I am not able to replicate it with the last version
