### ISSUE TITLE
Odd number generated every time a new entry is created

### ISSUE THREAD

**Issue by SSG-Adam** [strapi/strapi#20319]
### Required System information

Node.js version: v20.6.1
NPM version: 9.8.1
Strapi version: 5.0.0-beta.3
Database: sqlite
Operating system: Ubuntu 22.04.4 LTS
Is your project Javascript or Typescript: TypeScript

### Describe the bug

Example: If you have a Collection Type named "Skills" with a simple name field of text.
Every time you populate the numbers do not increment uniformly. Instead it's always increment at either a even or odd number.

### Steps to reproduce the behavior

1. Create a Collection Type. e.g: Skills
2. Add in only one field of type text.
3. Populate the collection type
4. Publish/save
5. Numbers either go from 1, 3, 5... or 2, 4, 6...

### Expected behavior

It should produce numbers naturally without skipping any of them

**Comment by Eventyret** [comment]
Confirmed `5.0.0-beta.9`

![Image](https://github.com/strapi/strapi/assets/977232/daa38baa-d245-4482-8755-11ae9a675b1d)

**Comment by joshuaellis** [comment]
This is actually by design and not a bug. The ID of an entry is incremental, and because a document contains two entries e.g draft & publish, you will get this odd/even jumping.
