### ISSUE TITLE
Selecting multiple "Add relation" in a Collection Type too quickly causes the tab to become unresponsive.

### ISSUE THREAD

**Issue by SSG-Adam** [strapi/strapi#20320]
### Required System information
Node.js version: v20.6.1
NPM version: 9.8.1
Strapi version: 5.0.0-beta.3
Database: sqlite
Operating system: Ubuntu 22.04.4 LTS
Is your project Javascript or Typescript: TypeScript
- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

If a user was to add multiple Skills relation too quickly without saving the web page becomes unresponsive.
This causes the user to lose all previous work not saved.

### Steps to reproduce the behavior

1. Create 2 Collection Types: Skill and Team
2. Skill will contain one field named "Skill" of type "text".
3. Teams will contain a relation of one to many to Skills.
4. In Content Manager, starting adding multiple Skills in Teams Collection Type.
5. The entire web page becomes unresponsive and will only be operable on reload of the web page.
6. Reload the web page will also not have the selected Skills relation saved.

### Expected behavior

User should be able to add an indefinite amount of relations to a Collection Type without the web page freezing or becoming unresponsive.

**Comment by Eventyret** [comment]
Can't reproduce this in `5.0.0-beta.9` unable to do Step 4 here as when trying to add anything it's blank and you can't choose anything or vice versa.
