### ISSUE TITLE
Typeof - date (ex: 01/01/2024) field decrements from the selected date

### ISSUE THREAD

**Issue by SSG-Adam** [strapi/strapi#20321]
### Required System information

Node.js version: v20.6.1
NPM version: 9.8.1
Strapi version: 5.0.0-beta.3
Database: sqlite
Operating system: Ubuntu 22.04.4 LTS
Is your project Javascript or Typescript: TypeScript

### Describe the bug

A user selects a date through the date picker which is a field in Strapi.
When the user selects a date and proceeds to the next field or just clicks outside of the calendar field the date decrements by one.
For example: If a user were to select 2nd March 2019 on the date picker and proceeds to click outside the calendar or another field the date then decrements by one count and displays 1st March 2019.

### Steps to reproduce the behavior

1. Create a Collection Type with any name
2. Add a "Date" field to the Collection Type.
3. Navigate to Content Manager and select a date through the newly created "Date" field for the Collection Type.
4. User selects 5th Feb. 2020 
5. User clicks or tabs to the next field
6. The date is now decremented by one and now displays 4th Feb. 2020.

### Expected behavior

When a user chooses a date and clicks on it then that date should remain and not be decremented or incremented.

**Comment by Eventyret** [comment]
Confirmed `5.0.0-beta.9`

**Comment by joshuaellis** [comment]
related #20236
