### ISSUE TITLE
Not all entries available to be assigned from related collection - limited to 20

### ISSUE THREAD

**Issue by justinshea** [strapi/strapi#2032]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: MongoDB v4.0.1
- **Operating system**: Alpine Linux v3.6

**What is the current behavior?**
When attempting to assign entries from a related collection to an entry in the content manager ui, only the first 20 entries from that related collection are available to be assigned.

**Steps to reproduce the problem**

- Create two content types in content type builder
- Create a "many-to-many" relation between content type "a" and content type "b" in content type builder
- Populate content type "b" with 20+ entries
- Using content manager from admin ui, create an entry in content type "a" and attempt to assign related values from content type "b"
- there is a limit of 20 entries to choose from 

**What is the expected behavior?**
When trying to assign entries from a related content type while using the content manager ui, all values from related collection should be discoverable and assignable, not limited to 20.

**Suggested solutions**
When editing or creating a new entry for a content type, the content manager plugin will pull in the top 20 entries for each select menu associated with a *-to-many related collection. 

The URL the plugin uses to make the request looks like this for each related collection field:
`http://localhost:1337/content-manager/explorer/story?_limit=20&_start=0&source=content-manager`

The limit should be removed. But for very large collections this would maybe be a bottleneck. So, there should be some lazy loading or an ability to do text searches against the api and populate options based on that.

**Comment by lauriejim** [comment]
Can you precise the version of Strapi you use please.

**Comment by justinshea** [comment]
@lauriejim

How do I give you more precise version then what is mentioned in original post?

**Comment by lauriejim** [comment]
Run `strapi -v` and give me the output.

**Comment by DejvG** [comment]
+1

**Comment by justinshea** [comment]
> @lauriejim
> 
> How do I give you more precise version then what is mentioned in original post?

3.0.0-alpha.14

**Comment by lauriejim** [comment]
Can you please try with `3.0.0-alpha.14.2` it's our latest version.

**Comment by justinshea** [comment]
Yes, I'll try.

I'm a little confused by the migration guide. If I install new version globally, all I have to do is `npm install --save strapi@3.0.0-alpha.14.2`  in root of current project?

If it is not that simple how would I go about preserving / reestablishing the following customization's during migration? 

- api models (and a custom service generated within the api directory along side models)
- a custom hook (in hooks directory)
- various values in config including custom and all connections.

Thanks

**Comment by DejvG** [comment]
Hi there.
I tryied with version aplha.14.2 but without any luck.
Select is still limited to 20 items.

**Comment by justinshea** [comment]
> Hi there.
> I tryied with version aplha.14.2 but without any luck.
> Select is still limited to 20 items.

Thanks for the heads up.  Are your relationships "many-to-many"? 

I have tested using "one way" and "many-to-many" relationships. The "one way" relationships are working if I search by text in the select field and, there appears to be some lazy loading after the initial 20 are populated as well.

So, one way relationships seem to be working as intended but many-to-many and other relationship types (??????) are not...

**Comment by lauriejim** [comment]
This issue has been fixed (don't remember the version, the link has not been made with this issue.)
But not present in last version of Strapi (3.0.0-alpha.14.4.0)
