### ISSUE TITLE
[BUG] [Strapi v5 Beta]`defPropValFN` is not a function

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20328]
### Required System information

- Node.js version: 20.10.0
- NPM version: pnpm/8.12.0 npm/? node/v18.17.0 darwin arm64
- Strapi version: 5.0.0-beta.7
- Database: mysql
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

`defPropValFN is not a function`

It happens while creating content types, switching to advanced settings tab.

Could you please investigate?

### Steps to reproduce the behavior

1. Go to 'content type builder'
2. Click on 'create new collection type'
3. 'Click on advanced settings tab'.

### Expected behavior

No error happens while creating content types.

### Screenshots

<img width="1538" alt="Screenshot 2024-05-17 at 15 58 59" src="https://github.com/strapi/strapi/assets/8948363/e1d1c98f-f01d-40a7-a9a7-0386f94746a8">

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Dependencies:

```
    "@strapi/logger": "^5.0.0-beta.7",
    "@strapi/plugin-cloud": "^5.0.0-beta.7",
    "@strapi/plugin-documentation": "^5.0.0-beta.7",
    "@strapi/plugin-i18n": "^5.0.0-beta.5",
    "@strapi/plugin-users-permissions": "^5.0.0-beta.7",
    "@strapi/strapi": "^5.0.0-beta.7",
    "@strapi/typescript-utils": "^5.0.0-beta.7",
    "@strapi/utils": "^5.0.0-beta.7",
    "mysql2": "^3.9.7",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
```
It could be related to some plugins like, `plugin-content-manager` and `plugin-i18n` are using `styled-components@5.2.1`.

**Comment by joshuaellis** [comment]
You shouldn't need to install ` "@strapi/plugin-i18n": "^5.0.0-beta.5",` can you remove this and try again please? i18n is installed by default via `@strapi/strapi`

**Comment by burakozdemir32** [comment]
Tried it out just now, it's now working as expected. Thanks for the swift assistance 🙌
