### ISSUE TITLE
On Initial Install Get "You don't have permission to access content error"  when looking at User collection type until you refresh.

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/strapi#20332]
### Required System information

- Node.js version: v20.11.1
- NPM version: 10.2.4 
- Strapi version: 5.0.0-beta.7
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript:

### Describe the bug

After initial install when you navigate to `COLLECTION TYPES` and click on `User` you get the following message.
```
You don't have permission to access content error
```
![2024-05-19_18-31-35](https://github.com/strapi/strapi/assets/6153188/40573b5e-6966-4d30-b3ec-c9655746ee13)

as well as don't see the rest of the menu options until you reload the app.

### Steps to reproduce the behavior

1. Install Strapi
2. Click on the content manager link
3. Select `User` collection type

### Expected behavior

Should not see the message and have all the available items in menu.
![2024-05-19_18-32-35](https://github.com/strapi/strapi/assets/6153188/0578fd8b-03da-47c0-8188-2bbc76f52239)

### Screenshots

Video showing the steps to reproduce

https://github.com/strapi/strapi/assets/6153188/5605c4d3-f4a9-4aee-9977-f0534dc514f7

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Not a breaking issue but can hurt initial perception when trying out Strapi.  Due to most users being frustrated before figuring out that restarting or refreshing fixes the issue.

**Comment by mirkonasato** [comment]
> Due to most users being frustrated before figuring out that restarting or refreshing fixes the issue.

I didn't actually figure it out until I read it here. 🤭

**Comment by Eventyret** [comment]
confirmed `5.0.0-beta.8`
Restarting it will clear the "no permission"

**Comment by Simran-B** [comment]
With beta 10, after workarounds for other issues (`npm install`, set `DATABASE_FILENAME=.tmp/data.db` in .env), I ran `npm run develop`, entered credentials for the admin user and then also got a limited set of menu options:

![image](https://github.com/strapi/strapi/assets/7819991/121e11c3-b041-493e-8666-8e7878899512)

Clicking **Create your first content type** resulted in
> You don't have the permissions to access that content

Opening the **Profile** shows a toast message with no further information:
> Warning: An error occurred

Restarting the develop server apparently fixes it.

**Comment by remidej** [comment]
fixed by https://github.com/strapi/strapi/pull/20609
