### ISSUE TITLE
Lifecycle hooks can't access previous values of components

### ISSUE THREAD

**Issue by kmertozen** [strapi/strapi#20346]
### Required System information

- Node.js version: 18
- NPM version: 8.19.4
- Strapi version: 4.8.1
- Database: mysql

### Describe the bug

I can't access the previous data of the component in collections when using lifecycle hooks

**Comment by derrickmehaffy** [comment]
This is intended due to the layer at which lifecycles function and will not be addressed in v4, we have added a new layer in v5 where this is possible.

**Comment by kmertozen** [comment]
how can i do that in v5?

**Comment by derrickmehaffy** [comment]
DocumentService Middlewares instead of lifecycles.

**Comment by derrickmehaffy** [comment]
https://docs-next.strapi.io/dev-docs/api/document-service/middlewares

**Comment by dmnkvd** [comment]
Could you please provide an example on how to access the previous value of a property before update, using the middlewares approach? I have been attempting to write it out, unsuccessfully.
