### ISSUE TITLE
CastError with NumberDecimal values

### ISSUE THREAD

**Issue by brunofigalveskk** [strapi/strapi#2034]
I'm getting a cast error when I try to get some data of a collection.

`          { message: 'Cast to The value you passed should be number failed for value "undefined" at path "undefined"',
            name: 'CastError',
            stringValue: '"undefined"',
            kind: 'The value you passed should be number' }`

In the last versions of strapi I think that number values had being savesd as NumberDecimal and now I think that is saved as double. I think that doesn't make sense not support compatibilities like these between releases.

**Comment by lauriejim** [comment]
Hello @, please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
