### ISSUE TITLE
Translation keys missing in NL language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#2035]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/nl.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/nl.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

**Comment by DaanDD** [comment]
Noted. Will have a look tomorrow.

**Comment by lauriejim** [comment]
Yeah @DaanDD that is an super good news :) 
Thank you. Waiting for your PR.

**Comment by lauriejim** [comment]
I close this issue because we are moving to Crowdin to manage translations.
We will update the contribution guide to add information to how contribute to translations.
