### ISSUE TITLE
"Add new API token" button has not the right style

### ISSUE THREAD

**Issue by maccomaccomaccomacco** [strapi/strapi#20359]
### Required System information

- Node.js version: 20
- NPM version: 10.1.0
- Strapi version: v5.0.0-beta.7
- Database: sqlite
- Operating system: mac
- Is your project Javascript or Typescript: Javascript

### Describe the bug
New API token button has not the right style

### Steps to reproduce the behavior

1. Go to Api tokens settings
2. Notice the api token list when is empty

### Expected behavior

The "Add a new API token" button should have the correct style following the design system guidelines.

### Screenshots
<img width="1216" alt="Screenshot 2024-05-23 at 18 08 38" src="https://github.com/strapi/strapi/assets/2686869/10db3815-f6cc-406b-8b88-cb5bd0795af9">

**Comment by alexandrebodin** [comment]
This is fixed in beta.10 :)
