### ISSUE TITLE
Content history "back" link doesn't work

### ISSUE THREAD

**Issue by innerdvations** [strapi/strapi#20350]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.7
Node/Yarn Version: yarn/4.0.1 npm/? node/v20.9.0 darwin arm64
Edition: Enterprise
Database: sqlite

### Describe the bug

On the "content history" page, clicking the back button in the top left of the page causes a new browser window to open to the login rather than going back

### Steps to reproduce the behavior

1. Create an entity in the content manager
2. Click on the ... menu in the top right
3. Select "Content History"
4. On the content history page, click on the "back" button in the top left
5. See that it doesn't work and instead opens a new browser window

### Expected behavior

Clicking "back" should go back

### Screenshots

![image](https://github.com/strapi/strapi/assets/999278/e75d7179-401a-4114-b7bf-4273f8729e08)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by alexandrebodin** [comment]
Fixed in beta-9
