### ISSUE TITLE
[missing feature] Doesn't V4 "Fill in from another locale feature" exist in V5 so far ?

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20369]
### Describe the bug

Not a bug here but a missing feature : 
In v4 I used to have access to the Fill on from another locale feature : 
![image](https://github.com/strapi/strapi/assets/97893822/d7fe3e3e-3c69-448f-b562-8c911160b528)

Now on v5/main, using the latest beta, this feature is not present anymore. 
As it was useful, should we implement it asap ?

**Comment by Eventyret** [comment]
confirmed `5.0.0-beta.8`

**Comment by joshuaellis** [comment]
It was declared to be OOS for D&Pv2, there should be tickets to re-implement it cc @Marc-Roig
