### ISSUE TITLE
Long titled Collection Type breaks buttons display

### ISSUE THREAD

**Issue by maccomaccomaccomacco** [strapi/strapi#20366]
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: 5.0.0-beta.7
- Database: sqlite
- Operating system: mac
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When the collection type name is too long, the UI gets broken 

### Steps to reproduce the behavior

1. Create a collection type with a very long name
2. Save the content type
The content type name breaks the Ui and the nearest buttons style.

### Expected behavior

The content type name should be truncated with ellipses if it's too long and not break the style of the surrounding elements

### Screenshots

![U`ntitled](https://github.com/strapi/strapi/assets/2686869/3cc91d46-14ca-4b1d-a0bd-dcea7faa38da)
![Untitled](https://github.com/strapi/strapi/assets/2686869/2980b45d-bed8-4799-85c2-9d90855b9c0e)

**Comment by hanpaine** [comment]
@derrickmehaffy what's the reasoning on this being a High? Do we know the maximum content length and that it is frequently exceeded?

**Comment by simotae14** [comment]
Closed because it was fixed with this PR https://github.com/strapi/strapi/pull/20770
