### ISSUE TITLE
Editing a token opens a new admin tab

### ISSUE THREAD

**Issue by maccomaccomaccomacco** [strapi/strapi#20361]
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: v5.0.0-beta.7
- Database: sqlite
- Operating system:mac
- Is your project Javascript or Typescript: Javascript

### Describe the bug
When the command to edit an API token is clicked, a new tab is also opened with the login page

### Steps to reproduce the behavior

1. Go to the API token settings with some API tokens already existing
2. Click on the command to edit an API token
A new tab gets opened

### Expected behavior

Any new tab shouldn't be opened.

**Comment by Eventyret** [comment]
Confirmed `v5.0.0-beta.8`

**Comment by remidej** [comment]
I'm not able to reproduce it as of v5 RC.0
