### ISSUE TITLE
Strapi fetches old single type data randomly

### ISSUE THREAD

**Issue by OGReabon** [strapi/strapi#20368]
### Required System information
Using Strapi v.4.24.2
Node version 19.9.0. on Heroku
PostgreSQL DB on Heroku

- Node.js version: 19.9.0.
- NPM version: 9.6.3
- Strapi version: 4.24.2
- Database: PostgreSQL
- Operating system:
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

I have an app with multiple pages, all being fetched from Strapi deployed on Heroku using Heroku PostgreSQL as database. 
Strapi works fine except for one Single Type (page), where ,only in my default locale, it fetches data with old ID, and it is also inconsistent. There are now several records for each component in this Single Type and Strapi fetches one maybe 8 times and then randomly fetches different one that is not the most recent. 
For better understanding see screenshot below with an explanation of what's happening.

In this image is one of my components, Strapi saves new updates just fine, but fails to fetch the most recent version of this component (and other components as well), what happens instead is that Strapi is fetching ID 20 for several tries and then suddenly returns 19 or something else.

### Expected behavior

I excpect Strapi to always return the most recent content for Single Types.

### Screenshots
![image](https://github.com/strapi/strapi/assets/82502110/bc2b9e2c-e5ff-4eea-8775-af925bf55407)

**Comment by derrickmehaffy** [comment]
Most likely unrelated to us and instead relates to some kind of caching, would advise reaching out to heroku support.
