### ISSUE TITLE
Command plugin:init is missing file

### ISSUE THREAD

**Issue by vuletiki** [strapi/strapi#20374]
### Required System information

- Node.js version: 18.20.3
- NPM version: 10.7.0
- Strapi version: 4.24.3
- Database: mysql
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Cmd `yarn strapi plugin:init` is not create file : `strapi-admin.js` in plugin directory

### Steps to reproduce the behavior

1. Run `yarn strapi plugin:init` and follow step by step

### Expected behavior

`strapi-admin.js` should be existed

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by joshuaellis** [comment]
If you're creating a plugin using this method, you shouldn't need the strapi-admin file, can you explain why you think you need it?

**Comment by vuletiki** [comment]
> If you're creating a plugin using this method, you shouldn't need the strapi-admin file, can you explain why you think you need it?

My local plugin is not loaded in .strapi/app.js and when debugging, I see it required here:
https://github.com/strapi/strapi/blob/develop/packages/core/admin/_internal/node/core/plugins.ts#L180

**Comment by joshuaellis** [comment]
in theory it should work from this line:

https://github.com/strapi/strapi/blob/bb2e16aa064f446907390a674fa0eb556b5b75a1/packages/core/admin/_internal/node/core/plugins.ts#L183

which is what we do with the internal plugins.
