### ISSUE TITLE
Strapi 4 Following Contributing Guide to run custom fork of strapi with admin panel changes does not work with localhost:4000

### ISSUE THREAD

**Issue by Cerlancism** [strapi/strapi#20378]
### Required System information

- Node.js version: v20.11.1
- NPM version: 10.2.4
- Strapi version: 4.24.3
- Database: Sqlite
- Operating system: Mac 12.7.4
- Is your project Javascript or Typescript:

### Describe the bug

Following the documentation till `yarn watch`, it does not serve at `localhost:4000`

### Steps to reproduce the behavior

1. Follow
  https://github.com/strapi/strapi/blob/c80d4d9b205f7844215758ba333894819685e6c1/CONTRIBUTING.md?plain=1#L89-L107

### Current behavior

In order to develop customization to the admin panel, I have to instead

`yarn develop --watch-admin` at `./examples/getstarted`

`yarn watch` at `./packages/core/admin`

then hot changes from `./packages/core/admin/admin/src` are reflected at `localhost:1337` instead

**Comment by SalahAdDin** [comment]
This is not a question, I have the same issue with the v5.
