### ISSUE TITLE
Clicking on Load More button for Relations Shows ID's of Entries instead of the Selected Entry Title

### ISSUE THREAD

**Issue by bpetrov98** [strapi/strapi#20390]
### Required System information

- Node.js version: 16.20.2
- NPM version: 8.19.4
- Strapi version: 4.21.1
- Database: PostgreSQL
- Operating system: Windows 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Clicking on Load More button for showing more relations shows ID's of entries instead of the selected entry title.

### Steps to reproduce the behavior

1. Go to a collection that has many relations
2. Click on Load More button
3. See error

### Expected behavior

All entries should have their entry title displayed and not the default one (ID).

### Screenshots
![before-load-more](https://github.com/strapi/strapi/assets/121244434/f6c4bffb-d19e-4712-95c0-01a2131d4d0c)
![after-load-more](https://github.com/strapi/strapi/assets/121244434/97042e06-3cbe-46f2-98ba-f0ca4390eb45)

**Comment by derrickmehaffy** [comment]
Fixed in later versions, please update your version
