### ISSUE TITLE
DTS Import Unique Constraint Failed

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/strapi#20394]
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-beta.8
- Node/Yarn Version: npm/10.2.4 node/v20.11.1 darwin arm64 workspaces/false
- Edition: Community
- Database: sqlite
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Get  `UNIQUE constraint failed` error when doing a DTS import on SQlite Database.

### Steps to reproduce the behavior

1. Run `strapi import`

https://github.com/strapi/strapi/assets/6153188/ee200c62-fccd-4be1-bdd5-010241f2486f

### Expected behavior

Should not fail with `Unique constrain` error.

**Comment by Convly** [comment]
Hey, this should be fixed by https://github.com/strapi/strapi/pull/20385

**Comment by alexandrebodin** [comment]
Closing 👍
