### ISSUE TITLE
How to force model (table) creation? 

### ISSUE THREAD

**Issue by mraak** [strapi/strapi#204]
I followed the tutorial and added PostgreSQL connection, and with it created a simple API through Studio. I can see the JS code that got generated, but Admin section reports there are no models. In Postgres DB there are no tables.

What might affect this is that I changed the DB password after I already created API because it didn't want to connect.

How can I now create models from my defined API's and a working connection?

**Comment by pierreburgy** [comment]
@mraak this issue is probably due to a bug we had in Strapi 1.6.1.

We just released Strapi 1.6.2, which solves this problem. Please try to update your Strapi version (`npm install strapi -g`) and create a new application (`strapi new myApp`).

**Comment by mraak** [comment]
I can see my table being created and in admin I can see the model. However, when I try to save new model through admin, I get "Internal server error" red message, and my table is empty.

**Comment by pierreburgy** [comment]
What are your Node, npm and Strapi versions?

**Comment by mraak** [comment]
Node.js version: 7.4
npm version: 4.0.5
Strapi version: 1.6.1
Operating system: Windows 7

**Comment by pierreburgy** [comment]
@mraak please try using Strapi 1.6.2.

**Comment by mraak** [comment]
Sorry, I *am* using Strapi 1.6.2, I copy pasted from the other issue I posted, but other versions are correct.

**Comment by pierreburgy** [comment]
Do you have any error log in your terminal?

**Comment by pierreburgy** [comment]
@mraak do you still have this issue?

**Comment by mraak** [comment]
Ok, now it's slightly different. Running strapi start again after a week, and going to /admin, I can not see any models any more. Table in PG is still there and it is correct one. No errors in the console. 
```

E:\dev\projects\_testarea\strap\produkt>strapi start
warn: Setting the migrate strategy of the `organization` model to `alter`.
info: Server started in E:\dev\projects\_testarea\strap\produkt
info: Your server is running at http://localhost:1337
info: Your admin panel is available at http://localhost:1337/admin/
debug: Time: Tue May 02 2017 12:46:52 GMT+0200 (W. Europe Daylight Time)
debug: Environment: development
debug: Process PID: 16244
debug: Cluster: master
info: To shut down your server, press <CTRL> + C at any time

info: Connection with the Studio server found, please wait a few seconds...
info: Connected with the Studio server.
debug: GET /admin/ (4ms)
debug: GET /admin/vendors.min.css (4ms)
debug: GET /admin/frontend.min.css (4ms)
debug: GET /admin/vendors.min.js (4ms)
debug: GET /admin/frontend.min.js (5ms)
debug: GET /admin/config (7ms)
debug: GET /admin/config (3ms)
debug: GET /admin/assets/images/logo.png (1ms)
debug: GET /admin/assets/images/user-picture.png (1ms)
debug: GET /admin/fonts/fontawesome-webfont.woff2?v=4.3.0 (1ms)

```

**Comment by pierreburgy** [comment]
Do you have this issue from a brand new project generated from Strapi 1.6.2?

**Comment by mraak** [comment]
Yes, I think so. Did you try with PG and it works for you?

**Comment by Aurelsicoko** [comment]
As you may know, we are actively working on the new version (v3). We won't develop this feature in v1. So I'm closing this issue.
