### ISSUE TITLE
Referring to a Collection Type, Selecting right side collection type dropdown appears behind the dialog box

### ISSUE THREAD

**Issue by SSG-Adam** [strapi/strapi#20405]
### Required System information

Node.js version: v20.6.1
NPM version: 9.8.1
Strapi version: 5.0.0-beta.8
Database: mysql2
Operating system: Ubuntu 22.04.4 LTS
Is your project Javascript or Typescript: TypeScript

### Describe the bug

When creating a new component and adding a relation from one collection type, when user tries to select a collection type from the right hand side the following bugs are shown:
1) There is no drop down arrow or border around the text, so it is not automatically assumed that it is selectable.
2) Once clicked on "Brand", the dropdown box will display behind the dialog box as shown in the screenshot. 

### Steps to reproduce the behavior

1) Create a new component
2) Add a new field called "Relation"
3) Select from the right hand side which collection type it should be related to.
4) The dropdown box will appear behind it. (It is still selectable, but you cannot view it.)

### Expected behavior

There should be a border around the "Collection Type", so it is understood that it is possible to change the Collection Type.
On click of the type, the drop down should be displayed in front of the dialog box.

### Screenshots

![image](https://github.com/strapi/strapi/assets/142774514/be52a4f6-49e0-42d3-b3dc-23539a21fba0)

**Comment by Eventyret** [comment]
Confirmed ` 5.0.0-beta.9`

**Comment by hanpaine** [comment]
Fixed with beta-10
