### ISSUE TITLE
how to Specify return column in api reqeust?

### ISSUE THREAD

**Issue by Restry** [strapi/strapi#2044]
**What is the expected behavior?**
how to Specify return column in api reqeust?

. I.E. something like this

http://localhost:1337/api/reference?select=["name"]

Would ideally return something of the form

[{"name": "Ref1"}]

**Comment by derrickmehaffy** [comment]
Via rest that isn't currently possible you can filter but it will return all data on that model entry. If you need specific data and complex queries I would suggest GraphQL

**Comment by Restry** [comment]
okay thansk
