### ISSUE TITLE
is:issue is:open Can´t install @strapi/provider-email-sendgrid even any strapi librery, ENOTFOUND registry.strapi.io, I was checking on Down For Everyone Or Just Me, answer: Is Registry.strapi.io down? It's not just you! registry.strapi.io is down. Last updated: Jun 5, 2024, 6:57 PM (1 second ago), can you help me?

### ISSUE THREAD

**Issue by Zynvit** [strapi/strapi#20445]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
We dont have a registry? Where did year hear that lol.
