### ISSUE TITLE
[Relation] Relation field icons are tiny

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20450]
### Required System information

- Node.js version: v20.9.0
- Strapi version: v5.0.0-beta.9
- Operating system: Windows WSL

### Describe the bug

When adding a Relation field to a Collection type, the icons for relation types are all wrongly displayed and look tiny (might be related to DS updates though, to be checked)

### Steps to reproduce the behavior

1. Create a Collection type with a Relation field
2. When defining the type of Relation, check the icons

### Expected behavior

Right size icons for Relation type.

### Screenshots

https://app.dashcam.io/replay/666189580899dd007172ad27?share=plAL0wu9ETo4sng4m99ZCQ
![image](https://github.com/strapi/strapi/assets/97893822/64987198-4b7e-4a46-92f7-d9cd3621425c)

**Comment by Eventyret** [comment]
Confirmed ` v5.0.0-beta.9`

![Image](https://github.com/strapi/strapi/assets/977232/da244425-65c0-4f61-b30f-863d678fc389)

**Comment by alexandrebodin** [comment]
Fixed for me in beta.10 can you check ?

**Comment by MarionLemaire** [comment]
Fixed for me too in beta.10 : 
<img width="774" alt="image" src="https://github.com/strapi/strapi/assets/97893822/ef8c264e-a8b7-45a7-bf63-e75e238a29e4">
