### ISSUE TITLE
[Webhooks] Not enough space between header rows 

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20457]
Required System information

Node.js version: v20.9.0
Strapi version: v5.0.0-beta.9
Operating system: Windows WSL

Describe the bug

There is not enough space between header rows + I don’t think we should have one “create new header” button per header, just one at the end would be enough.

### Steps to reproduce the behavior

1. Go to Settings
2. Go to Webhooks
3. Click on Create a new webhook
4. On Headers section, click on + Create new header
5. Check the spacing

### Expected behavior

There should be more spacing between headers and + Create new header button 
And as an improvement, only one + Create new header at the end of the Headers section might be enough.

### Screenshots

![image](https://github.com/strapi/strapi/assets/97893822/48fdd94f-4b97-4f68-9066-22838f2c974c)

**Comment by Eventyret** [comment]
Confirmed ` v5.0.0-beta.9`

**Comment by oiorain** [comment]
![Image](https://github.com/user-attachments/assets/2472db6c-73e6-4ad6-bba8-2501c1304aa3)

Fixed in rc.7
