### ISSUE TITLE
[Webhooks] Create new webhook button has color issues

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20455]
### Required System information

Node.js version: v20.9.0
Strapi version: v5.0.0-beta.9
Operating system: Windows WSL

### Describe the bug

[Create new webhook] Button has color issues.

### Steps to reproduce the behavior

1. Go to 'Settings
2. Click on 'Webhooks
3. Check [Create new webhook] button

### Expected behavior

Check in FIgma ? @lucasboilly 

### Screenshots

![image](https://github.com/strapi/strapi/assets/97893822/fc0f096e-7a51-4da0-9722-8198fd6ac723)

**Comment by Eventyret** [comment]
Confirmed `v5.0.0-beta.9`
