### ISSUE TITLE
 [Review Workflows] Feature is broken : stage never changes properly.

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20459]
### Required System information

Node.js version: v20.9.0
Strapi version: v5.0.0-beta.9
Operating system: Windows WSL

### Describe the bug

Review Workflow feature is broken : stage never changes properly.

### Steps to reproduce the behavior

https://app.dashcam.io/replay/6661cdaa392f570073957668?share=eDvKKSVChmOtCNHb5UbO7A

1. Go to Settings > RW
2. Relate the by default workflow to an existing CT
3. In the CM, create an entry for this CT and Save
4. Change workflow step (with or without assignee)
5. Change again
6. You have confirmation message but stage doesn't actually change (check on both Edit and List view)
7. Publish with a stage
8. Go to List view : stage is still different from Edit view

### Expected behavior

At every step change from the user, the stage should be saved and displayed correctly.

**Comment by Eventyret** [comment]
Confirmed `v5.0.0-beta.9`

**Comment by oiorain** [comment]
This is fixed on rc.7. Also Dupplicate of #20585
