### ISSUE TITLE
Translating content literals for admin does not work as before 

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#20461]
### Required System information

- Environment: development
- OS: Linux-x64
- Strapi Version: 5.0.0-beta.5
- Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
- Edition: Community
- Database: SQLite
- Operating system: 6.6.32-1-MANJARO
- Typescript

```
Launched In: 382 ms
Environment: development
OS: linux-x64
Strapi Version: 5.0.0-beta.5
Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
Edition: Community
Database: SQLite
[2024-06-07 00:15:05.490] info: Shutting down Strapi
[2024-06-07 00:15:05.491] info: Strapi has been shut down
```

### Describe the bug
We are working on localizing all the content types we create for our project, we followed the existing [documentation](https://docs-next.strapi.io/dev-docs/admin-panel-customization#locales), but it seems to be deprecated.

When checking the literals on the admin panel, only the content type names are translated, but the rest of the literals are in English yet.

This does not happen in Strapi 4.

### Steps to reproduce the behavior

1. Add the localization files to the folder.
2. Write the function for loading the translation files on the admin.
3. Load the translations on the admin app file.
4. Run the server.
5. Go to the admin panel.
6. Check the content manager.
7. Click on a content type.
8. Check the missing translations.

### Expected behavior

All the translation literals should be shown properly as it happens in Strapi 4.

### Screenshots

Strapi 5:
![image](https://github.com/strapi/strapi/assets/5034215/8292c87c-2989-4d80-93dc-758a0a13a7e9)

![image](https://github.com/strapi/strapi/assets/5034215/5aa9fdef-5cf5-4f34-8781-d9f4623084a6)

Strapi 4:
![image](https://github.com/strapi/strapi/assets/5034215/2c1c9c7d-bdfa-468f-8674-49b0b86ae8a5)

![image](https://github.com/strapi/strapi/assets/5034215/c6497588-4992-4524-980b-55daf37ce42e)

### Code snippets

You can check the files in [this commit](https://github.com/SalahAdDin/strapi-template/commit/c6a4777b0848e939f5fc2998a089d32708381e38).

### Additional context

It also has a lot of reports of missing translation literals:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://analytics.strapi.io/api/v2/track. (Reason: CORS request did not succeed). Status code: (null).

Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "cloud.plugin.name" for locale "es", using default message (Deploy) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    children LeftMenu.tsx:175
    LeftMenu LeftMenu.tsx:155
    React 16
[utils.js:20:16](http://localhost:1337/node_modules/@formatjs/intl/lib/src/utils.js)
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "cloud.plugin.name" for locale "es", using default message (Deploy) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    children LeftMenu.tsx:175
    LeftMenu LeftMenu.tsx:155
    React 10
[utils.js:20:16](http://localhost:1337/node_modules/@formatjs/intl/lib/src/utils.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://analytics.strapi.io/api/v2/track. (Reason: CORS request did not succeed). Status code: (null).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "content-manager.plugin.name" for locale "es", using default message (Content Manager) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    Layout2 layout.tsx:46
    React 12
[utils.js:20:16](http://localhost:1337/node_modules/@formatjs/intl/lib/src/utils.js)
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "content-manager.plugin.name" for locale "es", using default message (Content Manager) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    Layout2 layout.tsx:46
    React 15
[utils.js:20:16](http://localhost:1337/node_modules/@formatjs/intl/lib/src/utils.js)
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "content-manager.plugin.name" for locale "es", using default message (Content Manager) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    Layout2 layout.tsx:46
    React 10
[utils.js:20:16](http://localhost:1337/node_modules/@formatjs/intl/lib/src/utils.js)
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "content-manager.plugin.name" for locale "es", using default message (Content Manager) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    Layout2 layout.tsx:46
    React 10
[utils.js:20:16](http://localhost:1337/node_modules/@formatjs/intl/lib/src/utils.js)
Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "content-manager.plugin.name" for locale "es", using default message (Content Manager) as fallback.
    IntlError2 error.js:19
    MissingTranslationError2 error.js:79
    formatMessage message.js:65
    formatMessage2 createIntl.js:29
    Layout2 layout.tsx:87
```

**Comment by SalahAdDin** [comment]
Could it be you did change the literals?

**Comment by SalahAdDin** [comment]
For the List View Page title,  we have that [the title is not translatable](https://github.com/strapi/strapi/blob/develop/packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx#L196).

**Comment by SalahAdDin** [comment]
Yeah, while in the Strapi 4 the [labels are translatable](https://github.com/strapi/strapi/blob/v4/packages/core/admin/admin/src/content-manager/pages/ListView/ListViewPage.tsx#L465), in [Strapi 5 they are not](https://github.com/strapi/strapi/blob/develop/packages/core/content-manager/admin/src/pages/ListView/ListViewPage.tsx#L153):
Strapi 4:
```tsx
 const tableHeaders: TableHeader[] = React.useMemo(() => {
    const headers = runHookWaterfall(INJECT_COLUMN_IN_TABLE, {
      displayedHeaders,
      layout,
    });

    const formattedHeaders = headers.displayedHeaders.map((header) => {
      if (header.fieldSchema.type === 'relation') {
        return {
          ...header,
          metadatas: {
            ...header.metadatas,
            label: formatMessage({
              id: getTranslation(`containers.ListPage.table-headers.${header.name}`),
              defaultMessage: header.metadatas.label,
            }),
          },
          name: `${header.name}.${header.metadatas.mainField?.name ?? ''}`,
        } satisfies TableHeader;
      }

      return {
        ...header,
        metadatas: {
          ...header.metadatas,
          label: formatMessage({
            id: getTranslation(`containers.ListPage.table-headers.${header.name}`),
            defaultMessage: header.metadatas.label,
          }),
        },
      } satisfies TableHeader;
    });

    if (hasDraftAndPublish) {
      formattedHeaders.push({
        key: '__published_at_temp_key__',
        name: 'publishedAt',
        fieldSchema: {
          type: 'custom',
        },
        metadatas: {
          label: formatMessage({
            id: getTranslation(`containers.ListPage.table-headers.publishedAt`),
            defaultMessage: 'publishedAt',
          }),
          searchable: false,
          sortable: true,
        },
      } satisfies TableHeader);
    }

    if (reviewWorkflowColumns) {
      formattedHeaders.push(
        ...reviewWorkflowColumns.map((column) => {
          return {
            ...column,
            metadatas: {
              ...column.metadatas,
              label: formatMessage(column.metadatas.label),
            },
          } satisfies TableHeader;
        })
      );
    }

    return formattedHeaders;
  }, [
    runHookWaterfall,
    displayedHeaders,
    layout,
    reviewWorkflowColumns,
    hasDraftAndPublish,
    formatMessage,
  ]);
```

Strapi 5:
```tsx
/**
   * Run the waterfall and then inject our additional table headers.
   */
  const tableHeaders = React.useMemo(() => {
    const headers = runHookWaterfall(INJECT_COLUMN_IN_TABLE, {
      displayedHeaders,
      layout: list,
    });

    const formattedHeaders = headers.displayedHeaders.map<ListFieldLayout>((header) => {
      return {
        ...header,
        label: typeof header.label === 'string' ? header.label : formatMessage(header.label),
        name: `${header.name}${header.mainField?.name ? `.${header.mainField.name}` : ''}`,
      };
    });

    if (schema?.options?.draftAndPublish) {
      formattedHeaders.push({
        attribute: {
          type: 'custom',
        },
        name: 'status',
        label: formatMessage({
          id: getTranslation(`containers.list.table-headers.status`),
          defaultMessage: 'status',
        }),
        searchable: false,
        sortable: false,
      } satisfies ListFieldLayout);
    }

    return formattedHeaders;
  }, [displayedHeaders, formatMessage, list, runHookWaterfall, schema?.options?.draftAndPublish]);
  ```
  
  Why did you guys forget it?
  
  A solution could be:
  ```tsx
  const formattedHeaders = headers.displayedHeaders.map<ListFieldLayout>((header) => {
      return {
        ...header,
        label: formatMessage({
              id: getTranslation(`containers.list.table-headers.${header.name}`),
              defaultMessage: header.label,
            }),,
        name: `${header.name}${header.mainField?.name ? `.${header.mainField.name}` : ''}`,
      };
    });
```
  
  Following the format defined by `containers.list.table-headers.status`.
  
  What do you think?

**Comment by SalahAdDin** [comment]
@markkaylor 

How to translate the Content Type name for the Edit View?

And the list headers?

**Comment by markkaylor** [comment]
> How to translate the Content Type name for the Edit View?

Where do we see the content type name in the Edit View? Do you mean in the side navigation?

To translate attributes in the list view and edit you should be able to provide a translation key following this pattern:

`content-manager.content-types.{contentTypeUid}.{attributeName}`

Example config:

`src/admin/app.jsx`

```
const config = {
  locales: ['it', 'es', 'en', 'en-GB', 'fr'],
  translations: {
    fr: {
      // Translate content type names
      'Kitchen Sink': 'Évier de cuisine'
      // Translate attribute names
      'content-manager.content-types.api::kitchensink.kitchensink.short_text': 'texte_court',
      // Translate new entry title
      'content-manager.containers.edit.title.new': 'Créer une entrée'
    },
  },
};
```

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/9b2c9aaa-718e-414e-bdbd-f77807b61c23" />

There is a bug where the translation isn't applied for the list view page title. I'll look into it.

**Comment by SalahAdDin** [comment]
> 'content-manager.containers.edit.title.new': 'Créer une entrée'

It should be translated on Strapi itself.

**Comment by SalahAdDin** [comment]
> 'content-manager.content-types.api::kitchensink.kitchensink.short_text': 'texte_court',

In this way, we have a big issue:

![Image](https://github.com/user-attachments/assets/bcd76883-e7c9-49ef-9296-c2ca48319c82)

In Strapi 4, translating the label itself is enough to replace it everywhere; in Strapi 5, as you can see, it is not. It becomes an issue cause we have to repeat translation everywhere the field name is required:

![Image](https://github.com/user-attachments/assets/be73c25a-f6ba-4411-a0f9-07c67dd781fb)

It becomes problematic for automatically appended fields, like `createdAt`, `createdBy`, `updatedAt`, etc.

![Image](https://github.com/user-attachments/assets/3ef329c0-a922-4b5b-919b-211f5b1954a0)

How can we tackle it?

**Comment by SalahAdDin** [comment]
Similar issue with Status:

![Image](https://github.com/user-attachments/assets/345812d8-35e3-4480-a9e6-130fbf563d07)

But in this case, it can be fixed easily by adding `containers.list.table-headers.status": "Durum",` to the content manager (see [here](https://github.com/strapi/strapi/pull/22715)).

It does not work for createdAt, createdBy, updatedAt, etc.

**Comment by SalahAdDin** [comment]
> I understand that you may have an attribute that is the same across content-types and you would like to provide a single translation for it. I'll see if it can be improved to handle that case. That being said I do not agree with having the attribute translations at the root of the translation object so _if_ the api changes it will not be the same as strapi 4.

We will be waiting for this enhancement, it will be a great improvement! Meanwhile, we just duplicated the literals.

Thank you very much

**Comment by julesrenaud** [comment]
@markkaylor

> There is a bug where the translation isn't applied for the list view page title. I'll look into it.

Apparently it's only fixed on collection types, it's still broken on single types

**Comment by SalahAdDin** [comment]
> [@markkaylor](https://github.com/markkaylor)
> 
> > There is a bug where the translation isn't applied for the list view page title. I'll look into it.
> 
> Apparently it's only fixed on collection types, it's still broken on single types

So, let's open an issue.
