### ISSUE TITLE
[BUG] Configure view button is not in Content Type panel anymore

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#20460]
### Required System information

- Environment: development
- OS: Linux-x64
- Strapi Version: 5.0.0-beta.5
- Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
- Edition: Community
- Database: SQLite
- Operating system: 6.6.32-1-MANJARO
- Typescript

```
Launched In: 382 ms
Environment: development
OS: linux-x64
Strapi Version: 5.0.0-beta.5
Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
Edition: Community
Database: SQLite
[2024-06-07 00:15:05.490] info: Shutting down Strapi
[2024-06-07 00:15:05.491] info: Strapi has been shut down
```

### Describe the bug

From Strapi 4 we have a _Configure View_ button in the Content Type Builder entity view, which is unavailable in Strapi 5.

It makes it complicated to edit the view since we have to go to the Content Manager, choose the entity, create a new entity, and look at the upper right-corner option menus only to change that view.

It becomes 5 steps from 3 steps required on the older version.

### Steps to reproduce the behavior

1. Go to Content-Type Builder.
2. Click on the wanted Content Type, let's say Profile.
3. Check the upper corner, you won't find the button.

### Expected behavior

The button should be in the Content-Type Builder entity's view, easy to access for the content developers like it is in Strapi 4.

### Screenshots
Strapi 5:
![image](https://github.com/strapi/strapi/assets/5034215/093aea78-e5a3-4969-a8e9-6e0e575cf1fc)

Strapi 4:
![image](https://github.com/strapi/strapi/assets/5034215/73d494d9-2934-4c0a-a8bf-5069f72026e9)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
It's been moved into the gear icon as seen here on rc.6

![image](https://github.com/user-attachments/assets/84ba4236-ed3f-450b-89b4-91ce13150524)
