### ISSUE TITLE
Importing data from another base (content only) causes adming panel content manager to be out of sync with builder

### ISSUE THREAD

**Issue by Ariseni** [strapi/strapi#20465]
### Required System information

Environment: development
OS: darwin-x64
Strapi Version: 4.24.5
Node/Yarn Version: npm/9.8.0 node/v20.11.0 darwin x64 workspaces/false
Edition: Community
Database: postgres

### Describe the bug

I've imported a (content only) db into my new environment. Since then I've got an issue with content manager not being in sync with the db.

Content builder has everything, and db is filled (no data was lost) however content manager doesn't show the types which are visible in builder (i've tried rebuilding and reimporting). Everything is visible in following screenshots.
P.S. if you go to the link of the missing type (example in screenshots) it will be shown normally, but the content manager won't have it.

### Steps to reproduce the behavior

import data into new environment with strapi import commands (only content)
build the app
content manager isn't in sync with content builder.

### Expected behavior

content manager should have all the types declared in builder

### Screenshots
1. content builder is fine
![Screenshot 2024-06-07 at 14 26 48](https://github.com/strapi/strapi/assets/20567672/ebc45042-ff91-46e3-b344-d2417af532fb)
2. content manager out of sync with builder
![Screenshot 2024-06-07 at 14 26 56](https://github.com/strapi/strapi/assets/20567672/7174d7b1-2d34-44b0-8a8d-b9ddd495033c)
3. content is actually accessible 
![Screenshot 2024-06-07 at 14 42 42](https://github.com/strapi/strapi/assets/20567672/0881d3f2-de44-4ec7-ac29-977b331eb71e)

**Comment by derrickmehaffy** [comment]
When you do an import of data the server needs to be restarted as on bootstrap a cache of the content-type structure is saved to the DB which if you restore data is now reverted.

**Comment by ivo-ljubicic** [comment]
I've restarted it a few times. Tried removing the dist folder. Doing a npm run build first. Nothing helped. 

The thing that helped was getting a new exported db and doing the same thing.

I dont think this should be closes so soon.
