### ISSUE TITLE
config/env/x structure is not working

### ISSUE THREAD

**Issue by lolafkok** [strapi/strapi#20462]
### Required System information
- Node.js version: v18
- Strapi version: 4.24.4
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Sadly the documented way of configuration of strapi does not work (atleast in 4.24.4).
You can't use the "old structure" with like  `/config/env/development` or `/config/env/production` - customFields / plugins do not load.

It's not in the Migration guides and still documented as working in the (worthless) developer docs.

Documentation:
https://docs.strapi.io/dev-docs/configurations#additional-configuration-for-specific-features
https://docs.strapi.io/dev-docs/configurations/environment#environment-configurations

### Steps to reproduce the behavior

1. Create a new 4.24.4 strapi
2. Adjust the config to match something like  `/config/env/development`
3. Visit a customField or something from a plugin
4. No error in console, endless loading.

### Expected behavior

No undocumented changes when updating.

**Comment by derrickmehaffy** [comment]
You should not be using `./config/env/development` those files should live at the base directory of `./config` and only use the `env` folders for other, non-development environments.
