### ISSUE TITLE
Phishing Attack Report

### ISSUE THREAD

**Issue by selormofmars** [strapi/strapi#20478]
Please note that a website hosted strapapi is being used to conduct a phishing attack. It is available at the following URL:

https://elegant-hope-040979b489.media.strapiapp.com/url_email_protection_7a1c1a87d9.html#

Please assist us with shutting it down as soon as possible, we appreciate your swift response in this regard.

**Comment by derrickmehaffy** [comment]
We are already aware and this is not the medium to report these, please use security@strapi.io
