### ISSUE TITLE
[Design] Inconsistent height of UI elements (e.g. search and sort)

### ISSUE THREAD

**Issue by jhoward1994** [strapi/strapi#20475]
### Required System information

- Node.js version:
- NPM version:
- Strapi version: v5.0.0-beta.9
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

Inconsistent height of UI elements - search bars and sort drop downs

### Steps to reproduce the behavior

1. Go to Upload plugin
### Screenshots

Example from upload plugin

<img width="1397" alt="Screenshot 2024-06-10 at 11 07 42" src="https://github.com/strapi/strapi/assets/48524071/039f11ee-9b73-4d90-b63e-922432c98d46">

**Comment by Eventyret** [comment]
Confirmed `v5.0.0-beta.9` seems filters and other minor buttons are smaller while search and dropdown box is larger.

**Comment by lucasboilly** [comment]
@remidej the select height was fixed but the issue remains for the search. What we need to do is update the design of the search bar in the design system.

**Comment by lucasboilly** [comment]
Should we close the issue?

**Comment by jhoward1994** [comment]
Yes I would say so. Closing now, I will double check and open again in the DS repo if it's still relevant 🙏🏻

**Comment by lucasboilly** [comment]
@jhoward1994 the sort is already fixed and the search bar will be fixed by https://github.com/strapi/design-system/pull/1833.

We can keep it closed 👍
