### ISSUE TITLE
Documentation password validations not surfaced

### ISSUE THREAD

**Issue by jhoward1994** [strapi/strapi#20476]
### Required System information

- Node.js version:
- NPM version:
- Strapi version: v5.0.0-beta.9
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

There is new password validation for documentation plugin in v5
If I fail the password validation (e.g. < 8 chars) there is no error surfaced in the UI. It'll seem like it's impossible to set a password

### Steps to reproduce the behavior

https://github.com/strapi/strapi/assets/48524071/9168f461-24d8-48f0-aceb-0f0736ca8bb2

### Expected behavior

Either no constraints on the password (current V4 behaviour)
Or validation errors surfaced in form

**Comment by Eventyret** [comment]
Confirmed `v5.0.0-beta.9`

There is no feedback it just toggles back to "off" or false. There is however UI feedback when success the validation is correct.
