### ISSUE TITLE
Strapi Registry Downtime - Impacting Package Installation and Project Development

### ISSUE THREAD

**Issue by Zynvit** [strapi/strapi#20471]
Summary

This report details the issue of Strapi registry (registry.strapi.io) downtime and its adverse impact on users' ability to install packages and develop projects. The registry has been inactive for 5 days, posing a significant hindrance to the Strapi developer community.

System Information:

Node.js version: v20.14.0
NPM version: 10.8.1
Strapi version: 4.20.0
Database: MySQL
Operating system: Windows
Project language: Typescript
Error Description:

An "ENOTFOUND" error occurs when attempting to install the @strapi/utils package using npm. The complete error message is:

npm error code ENOTFOUND
npm error syscall getaddrinfo
npm error errno ENOTFOUND
npm error network request to https://registry.strapi.io/npm/@strapi%2futils failed, reason: getaddrinfo ENOTFOUND registry.strapi.io
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network If you are behind a proxy, please make sure that the 'proxy' config is set properly. See: 'npm help config'
npm error A complete log of this run can be found in: C:\Users\a-sap\AppData\Local\npm-cache\_logs\2024-06-07T19_43_38_603Z-debug-0.log
This error indicates that npm cannot connect to the Strapi package registry to retrieve the package information due to a hostname resolution issue (getaddrinfo ENOTFOUND).

Steps to Reproduce the Error:

Start a Strapi project in your terminal.
Execute the command npm install @strapi/utils.
Observe the "ENOTFOUND" error in the console output.
Expected Behavior:

The installation of the @strapi/utils package is expected to complete without errors.

Additional Context:

It has been verified that the Strapi registry (registry.strapi.io) is currently inactive using services like Downdetector and Strapi's social media channels. This downtime has persisted for 5 days, impeding Strapi project development for many users.

Request:

Given the urgency of the matter and the impact on the developer community, we request an immediate investigation into the Strapi registry downtime. Prompt action is required to restore access to the registry and allow users to continue their project development. We appreciate your attention to this issue and look forward to a prompt response with information on the progress of the resolution.

Additional Information:

If you require any further information or specific details about the error, please do not hesitate to contact us. We are willing to collaborate in resolving this issue as quickly as possible.
![2](https://github.com/strapi/strapi/assets/170771519/72cd3605-4bd8-46ab-83ad-e3cf2b892512)
![Sin título](https://github.com/strapi/strapi/assets/170771519/031226cd-15a5-4612-b4da-2cfb6a5f0584)

**Comment by derrickmehaffy** [comment]
We don't have a registry. Closing
