### ISSUE TITLE
Navigating back from configure the view in the upload opens a new tab 

### ISSUE THREAD

**Issue by jhoward1994** [strapi/strapi#20477]
### Required System information

- Node.js version:
- NPM version:
- Strapi version: v5.0.0-beta.9
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug
Navigating back from configure the view in the upload opens a new tab which takes you to the login screen

### Steps to reproduce the behavior
https://github.com/strapi/strapi/assets/48524071/3387b84b-0bd5-4883-a8bd-3a07ce140cdd

### Expected behavior

Expect v4 behaviour as shown in video above

**Comment by remidej** [comment]
Looks like it's been fixed somehow 🤷 @Marc-Roig and I are not able to reproduce
