### ISSUE TITLE
While creating a new project Strapi hangs on Creating admin

### ISSUE THREAD

**Issue by ivokeereweer** [strapi/strapi#20488]
Hello, I am facing an issue with creating a new project with Strapi
Within my folder I run: npx create-strapi-app@latest <foldername>

After a while the setup is running Creating admin. But this does not end, the setup won't launch Admin panel to create user and so on.
Why is the setup looping on the Creating admin?
Manually tiping localhost:1337/admin does not give the main panel...

### Required System information

Environment: development
OS: win32-x64
Strapi Version: 4.24.5
Node/Yarn Version: npm/10.7.0 node/v18.20.3 win32 x64 workspaces/false
Edition: Community
Database: do not use sqlite just MSSsql but not yet configured in the project
- Is your project Javascript or Typescript: typescript

**Comment by derrickmehaffy** [comment]
Also we don't support MSSQL
