### ISSUE TITLE
Can not sign in using provider: google, error 400.

### ISSUE THREAD

**Issue by nurielmeni** [strapi/strapi#20489]
### Required System information

- Node.js version: v20.11.0
- NPM version: v10.2.4
- Strapi version: 4.24.5
- Database: postgres
- Operating system: MAC 14.5 (23F79), M1 Chip
- Is your project Javascript or Typescript: TS

### Describe the bug

Followed the Docs [https://docs.strapi.io/dev-docs/plugins/users-permissions#providers](url), all seem to work fine to the point the Frontend app tries to get the JWT token with the access_token, it raises a 400 error unfortunately. 

### Steps to reproduce the behavior

Just follow the steps in the docs, with the example app provided. and the error will rais.

### Expected behavior

Get the JWT and have the user signed in

**Comment by derrickmehaffy** [comment]
Lacking information, please add additional context, configs, frontend tech and setup, error mess details, etc.
