### ISSUE TITLE
Duplicating entries allows records to bypass uniqueness checks

### ISSUE THREAD

**Issue by Nniol** [strapi/strapi#20490]
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.22.1
- Database: Postgres
- Operating system: Dev: Windows, iOS  Prod: Linux
- Is your project Javascript or Typescript: JavaScript

### Describe the bug

We have created a schema which is unique fields set to true for two fields. Is we choose Duplicate Item Line x then we get the warning message saying we have unique checks in place for some fields.
However if we do nothing and just click Save then the record saves and can be published bypassing any uniqueness checks hence causing issues in the solution.

### Steps to reproduce the behavior

1. Create an pickem_group , save and publish
2. Then choose Duplicate Item on line 2 (Picture 1)
3. You get a warning message, good (Picture 2)
4. Click Create
5. Click Save 
6. Go to list view and see duplicate values for both pickemGroupId and name which are unique according to the schema (Picture 3)
7. Click back on item
8. Click Publish
9. Still no warning or stop

### Expected behaviour

At step 5 a warning should appear preventing the creation of the record

### Screenshots
Picture 1
![image](https://github.com/strapi/strapi/assets/1842296/8ababbbd-903e-4297-bdba-6febd89c04e1)

Picture 2
![image](https://github.com/strapi/strapi/assets/1842296/ab02b78b-3324-48d6-8b6c-ce2267de1dbe)

Picture 3
![image](https://github.com/strapi/strapi/assets/1842296/e4895243-5b65-4b85-b00b-eb1766816176)

### Code snippets

pickem_group schema:

{
  "kind": "collectionType",
  "collectionName": "pickem_groups",
  "info": {
    "singularName": "pickem-group",
    "pluralName": "pickem-groups",
    "displayName": "Pickem Group",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "attributes": {
    "pickemGroupId": {
      "type": "string",
      "required": true,
      "unique": true,
      "minLength": 5,
      "regex": "^[a-zA-Z0-9-]+$"
    },
    "name": {
      "type": "string",
      "unique": true,
      "required": true,
      "minLength": 5
    },
    "pickemOpens": {
      "type": "datetime",
      "required": true
    },
    "pickemCloses": {
      "type": "datetime",
      "required": true
    },
    "event": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::event.event",
      "inversedBy": "pickem_groups"
    },
    "races": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::race.race",
      "mappedBy": "pickem_group"
    }
  }
}

**Comment by hanpaine** [comment]
This has been fixed on Strapi 5 and a fix will be ported to V4 in coming weeks
