### ISSUE TITLE
Plugin order now is based on the package.json installs

### ISSUE THREAD

**Issue by Martijn-Schoenmaker-Webbio** [strapi/strapi#20499]
Since Strapi introduced the new builder (around 4.15/4.16) with `.strapi/client/app.js` the plugins that are included there are in the order that is defined in the `package.json`. It used to be the order of `plugins.ts`. We need to customize the order because it messes with the injectable zones (these are displayed based of plugin order).

I found this after a lot of research (after upgrading from 4.14.0 to 4.24.5) in this file: [get-enabled-plugins.ts](https://github.com/strapi/strapi/blob/8cc7465152430e22c7d5b1b883b82b49ab00f9bd/packages/core/strapi/src/core/loaders/plugins/get-enabled-plugins.ts#L83)

Note: changing the `package.json` order is not a fix since that order is changed automatically (to ascending) by tools like Prettier after a new install.

**Comment by Martijn-Schoenmaker-Webbio** [comment]
Guys, seriously... All the information is given in the issue, i've even given the file where the issue's origin is from. I'm getting quite tired of my application breaking after every single update you guys bring out and having to patch and fix things myself. But sure, here ya go:

---
name: 🐛 Bug Report
about: Plugin order now is based on the package.json installs
---

## Bug report

### Required System information

- Node.js version: 20.11.1
- NPM version: 10.5.0
- Strapi version: 4.24.5
- Database: MySql
- Operating system: Mac
- Is your project Javascript or Typescript: Typescript (why would you even use JS)?

### Describe the bug

Since Strapi introduced the new builder (around 4.15/4.16) with `.strapi/client/app.js` the plugins that are included there are in the order that is defined in the `package.json`. It used to be the order of `plugins.ts`. We need to customize the order because it messes with the injectable zones (these are displayed based of plugin order).

I found this after a lot of research (after upgrading from 4.14.0 to 4.24.5) in this file: [get-enabled-plugins.ts](https://github.com/strapi/strapi/blob/8cc7465152430e22c7d5b1b883b82b49ab00f9bd/packages/core/strapi/src/core/loaders/plugins/get-enabled-plugins.ts#L83)

Note: changing the `package.json` order is not a fix since that order is changed automatically (to ascending) by tools like Prettier after a new install.

### Steps to reproduce the behavior

1. Create a `plugins.ts` and enter some plugin configs
2. Build project
3. See the order of the plugins in `./strapi/client/app.js` that's now based on the `package.json` instead of `plugins.ts`

### Expected behavior

The order of the plugins should be like it was: like the `plugins.ts` config file.

**Comment by joshuaellis** [comment]
> We need to customize the order because it messes with the injectable zones (these are displayed based of plugin order)

This sounds like a potentially niche use-case, are you able to share more on this? I would expect injection-zones to all be registered in the `register` function & then used in the `bootstrap` function? 🤔 I'm not sure we ever actually supported the order of plugin loading so interested to learn more about how you're using it etc.

**Comment by Martijn-Schoenmaker-Webbio** [comment]
Since we have multiple plugins that inject content into the edit-view sidebar, the order matters. Per plugin we use the register and bootstrap functions to inject these components. But inside the project we don't have access to this right?

**Comment by joshuaellis** [comment]
> Since we have multiple plugins that inject content into the edit-view sidebar, the order matters.

I think thats more of a problem with our api then as opposed to how it used to "just work" which i do appreciate is frustrating for yourself. In V5 that API is deprecated for things like `panels` where you can define the order by using a reducer like fashion.

You do have access to the `bootstrap` function for the project if you have a `src/admin/app.ts` file, I don't think you'll have register available in V4 – It's being added in V5 though (I can't tell you why it wasn't already there).

**Comment by Martijn-Schoenmaker-Webbio** [comment]
But what do you mean by using the bootstrap function of `app.ts`? If the component is already begin injected inside the external plugin, I don't have a way to order them differently right?

Example:

* Plugin 1 adds a box to view SEO data to the edit-view
* Plugin 2 adds a page preview button to the edit-view

This order is now unchangeable. How would I change this with the project's `app.ts`?

**Comment by joshuaellis** [comment]
>  I don't have a way to order them differently right?

No not in V4. This is a limitation of the API we offer in V4.

**Comment by Martijn-Schoenmaker-Webbio** [comment]
Ok, then we'll have to use the css order prop to hack in some order. 

Thanks for your time

**Comment by joshuaellis** [comment]
I think that's probably best yes, hopefully you won't have that issue in v5. If you do, let's revisit the issue and figure out how to make that API better?
