### ISSUE TITLE
Relation <> does not exists

### ISSUE THREAD

**Issue by morohon** [strapi/strapi#20509]
### Required System information

- Node.js version: 20.11.1
- NPM version: 10.2.4
- Strapi version: 4.25.0
- Database: postgres
- Operating system: macos m1 chip (app in docker node:20.11.1-alpine3.19)
- Is your project Javascript or Typescript: Typescript

### Describe the bug
Hi all.
When I try to click the duplicate entry button in colletion types, I get an Internal Server Error error on the UI admin panel.
In this case, the following error is displayed in the log:
```sh
strapi-1  | [2024-06-13 13:52:28.056] error: update "products_by_region_ep_product_links" as "t1" set "product_by_region_order" = (select max(product_by_region_order) + 1 from "products_by_region_ep_product_links" as "t2" where t2.ep_product_id = t1.ep_product_id) where "t1"."product_by_region_id" = $1 - relation "products_by_region_ep_product_links" does not exist
strapi-1  | error: update "products_by_region_ep_product_links" as "t1" set "product_by_region_order" = (select max(product_by_region_order) + 1 from "products_by_region_ep_product_links" as "t2" where t2.ep_product_id = t1.ep_product_id) where "t1"."product_by_region_id" = $1 - relation "products_by_region_ep_product_links" does not exist
```
I looked in the database and there is a created table `products_by_region_ep_product_links`. I also found a ticket that talks about a similar problem: https://github.com/strapi/strapi/issues/17672. I did what was recommended there (cleared the `strapi_database_schema` table) and it didn't help.
Looking at the error, you can understand that he has some problems with relation to another collection type.

### Steps to reproduce the behavior

1. Go to 'Content manager'
2. Click on 'Open collection type'
3. Select a line and click the duplicate button

### Expected behavior

The recording was successfully duplicated

### Screenshots

![image](https://github.com/strapi/strapi/assets/12433983/1c532c85-fd59-4139-ae99-1c7fe6a18cbc)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by morohon** [comment]
Found that if you change the schema in postgresql to public, then creating a duplicate works.
It seems that somewhere in the request for a double they forgot to specify the schema for executing the request and it expects a table in the default public schema

**Comment by morohon** [comment]
![image](https://github.com/strapi/strapi/assets/12433983/a14502ae-5733-47a0-be0e-fe70e1e05309)
Вот так выглядит структура запросов. Видно, что при выполнении одного запроса отсутствует указание схемы

**Comment by morohon** [comment]
If I researched correctly, then apparently the problematic code is located [here](https://github.com/strapi/strapi/blob/main/packages/core/database/src/entity-manager/regular-relations.ts#L508), it was added as part of this https://github.com/strapi/strapi/pull/16192. 
It's as if this code is missing an extra method call [addSchema](https://github.com/strapi/strapi/blob/main/packages/core/database/src/utils/knex.ts), like this is done [here](https://github.com/strapi/strapi/blob/main/packages/core/data-transfer/src/strapi/queries/link.ts#L236) or [here](https://github.com/strapi/strapi/blob/main/packages/core/database/src/entity-manager/regular-relations.ts#L275)

**Comment by morohon** [comment]
@Marc-Roig I apologize for tagging you, but maybe you will have the opportunity to watch my investigation?

**Comment by MikolJ** [comment]
Any info on when this fix will be included in an upcoming patch/minor version? It's still in PR, but it seems like a simple issue.
