### ISSUE TITLE
Database tables pruned on random unclear occasions (data loss)

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#20513]
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.6.7
- Strapi version: 4.5.6
- Database: PostgreSQL
- Operating system: MacOS
- Is your project Javascript or Typescript: TS

### Describe the bug

Data is selectively wiped from my DB and a certain pattern emerges. I've talked about this issue to a handful of members now which encouraged me to open this issue. 

On restarting of Strapi, sometimes(!) a variously large set(!) of my data is wiped. Just right now, from 13 collection types 11 are entirely wiped (the DB shows the correct table/column structure though), one collection remained filled with seemingly all data, and here comes the interesting part: Only the _non-standard_ columns of the user collection were wiped:

<img width="541" alt="Bildschirmfoto 2024-05-23 um 12 18 56" src="https://github.com/strapi/strapi/assets/11761828/d780c147-8aa8-418b-9305-ea354dc65f20">

Some time ago I've caught this error on launch: 

![image](https://github.com/strapi/strapi/assets/11761828/f9b43d36-18be-4f8f-a199-d45832bc7e69)

which literally means nodejs had issues reading a file that was of course existing. 
Out of the around 12 times this issue happened to me by now, only around 2 times the full user table was wiped, too.

One very rough explanation this leads me to is: I don't know about the various steps the DB management is done on startup, but as strapi does not complain about not finding files it is not expecting to find, it just drops tables in the first step, and then luckily finds the schema files in a next step and recreates them. For the users though it assumes some minimum to be there as a "fallback" seemingly, which both doesn't explain the emptied user table I mentioned before. Also, I don't know how that would go with the screenshot where it complains about the missing file. Maybe there is some way to activate logging of what is actually going on in the back with db management in startup?

### Steps to reproduce the behavior

If I only knew ! It both happened after quick subsequent restarts and after not touching the codebase for a long time.

### Expected behavior

Data would stay in place.

### Additional context

For the longest time, I've attributed this issue to postgres running in docker, but after getting a proper explanation of how and when postgres actually interacts with the filesystem, I don't think this is the issue. If anything, then the DB would be just corrupted, but not emptied in such a suspicious pattern. I have now finally enabled full SQL query logging on postgresql (mea culpa, I should have done it ages ago) and will update this issue if this problem appears again and I find some logs that would shed some light into this.

**Comment by maxgeor** [comment]
Seconding this, getting a similar issue with some Postgres tables & data getting (seemingly) randomly dropped https://discord.com/channels/811989166782021633/1258130358520778782

**Comment by derrickmehaffy** [comment]
This is almost certainly not a Strapi issue and instead something else is happening on your system where those files can't be read. 

We've discussed it at length but do not intend on changing the logic around keeping the database clean for Strapi tracked DB tables and columns.

Referencing #1114 and https://github.com/strapi/strapi/pull/20580

**Comment by nikita-fuchs** [comment]
@derrickmehaffy help me make sure I understand this correctly.

We run our projects, products, companies on top of your solution because we trust the team to do good engineering and adequately care for the issues of it's _customer base_. It then appears that for certain customers a part of their data** gets lost repeatedly - the core of their business, which can happen to the very best engineered products at times, no doubt, because that's how tech products sometimes happen to end up working. It appeared not only once, not only on one machine (for me it was a 2019 Intel Mac and 2024 Macbook Pro M3 Max), and you are _**almost certain**_ that the reason we lose our data lies not in the way you engineer your product, but in _the file system_ ? That software, which is probably the most best engineered and heavily tested thing behind the linux kernel, serving countless requests correctly every day on my and billions of other machines?

**Comment by derrickmehaffy** [comment]
We have discussed this at length on Discord with you, the problem is not on our end, we have hundreds of thousands of users and I've only seen this issue mentioned a handful of times all of which have been back traced to either improper configuration (using sqlite instead of PG), people connecting multiple environments to the same database (which we don't support and is clearly warned about in the docs), or improper deployment where some of the schema files can't be read or don't exist likely due to permission issues or corrupted container builds.

**Comment by derrickmehaffy** [comment]
So far you have not been able to give any evidence or reproduction steps, nor throughout the probably 80 hours I've spent trying to reproduce this am I able to get anywhere near a valid reproduction that wouldn't just involve doing something that no one would do in production
