### ISSUE TITLE
[Strapi v5 RC] Action Button (⋮) Disappears When Entity List View is Shrunk and Horizontally Scrollable

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20517]
### Required System information

- Node.js version: 18.17.0
- NPM version: yarn/1.22.19
- Strapi version: 5.0.0-rc.2
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

_The issue occurs when the entity list view is shrunk and becomes horizontally scrollable._

**Invisible Action Button:** The action button (three dots) becomes invisible when the entity list view is shrunk and horizontally scrollable.

### Steps to reproduce the behavior

1. Navigate to the entity list view.
2. Resize the window or adjust the view so that the entity list becomes horizontally scrollable.
3. Observe that the action button (three dots) is no longer visible.

### Expected behavior

The action button (three dots) should remain visible and accessible even when the entity list view is shrunk and horizontally scrollable.

### Screenshots

<img width="355" alt="Screenshot 2024-06-14 at 15 56 40" src="https://github.com/strapi/strapi/assets/8948363/f434e878-3c32-4ec5-acca-0d2fd7551a2e">

### Code snippets

N/A

**Comment by yanniskadiri** [comment]
Duplicate issue: https://github.com/strapi/strapi/issues/20595

**Comment by derrickmehaffy** [comment]
Closing as duplicate
