### ISSUE TITLE
[Strapi v5 RC] Unable to Remove 'Available In' Column from Entity List View

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20520]
### Required System information

- Node.js version: 18.17.0
- NPM version: yarn/1.22.19
- Strapi version: 5.0.0-rc.2
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

_I am unable to remove the 'Available In' column from the entity list view._

### Steps to reproduce the behavior

1. Navigate to the entity list view.
2. Attempt to remove the 'Available In' column through the UI options.
3. Observe that the column remains visible and cannot be removed.

### Expected behavior

The 'Available In' column should be removable through the UI options in the entity list view.

### Screenshots

<img width="902" alt="Screenshot 2024-06-14 at 15 53 14" src="https://github.com/strapi/strapi/assets/8948363/6a020fb8-5fda-4a21-b1d9-7844f0d456ec">

### Code snippets

N/A

**Comment by yanniskadiri** [comment]
Confirmed in rc.7 (more of an improvement than a bug)

**Comment by alexandrebodin** [comment]
Hi, I'm going to set this as a feature request as this is already like this in v4 and was intentionnal :)
