### ISSUE TITLE
[MediaLib] Impossibility to upload several files ([Upload] button not reachable by scrolling)

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20539]
### Required System information

- Node.js version: 20.9.0
- Strapi version: beta 10 experimental v0.0.0-experimental.a53a4b1c8f7981a689823cdd719105671e1c6392
- Operating system: Windows WSL

### Describe the bug

When you add a big amount of assets in the MediaLib at the same time (here : 73 assets), you can't upload them as in the uploading modal, you can't scroll at the end of the modal to click on the [Upload] button

### Steps to reproduce the behavior

1. Go to MediaLibrary
2. Click on Add new assets
3. Click on Browse files and select several files (around 50) or drag and drop files
4. Try to scroll until you reach [Upload] button
5. Check that your selected files are anyway "assets ready to upload"

### Expected behavior

User should be able to scroll until reaching the [Upload] button and the files should be actually uploaded.

### Screenshots

https://app.dashcam.io/replay/667031d52d1e3d007642e9e1?share=SaZAjls9OZss9KhyymhqBw

**Comment by alexandrebodin** [comment]
Fix merged
