### ISSUE TITLE
The value of a saved DateTime or Time field returns the initial one when you save

### ISSUE THREAD

**Issue by simotae14** [strapi/strapi#20538]
### Required System information

- Node.js version: 20
- NPM version: 10.1.0
- Strapi version: v5.0.0-beta.9
- Database: sqlite
- Operating system: MacOs
- Is your project Javascript or Typescript: TS

### Describe the bug

When you use a DateTime field or a time field and try to save a new time, then after saving the initial value is shown in the Dropdown instead of the last one

### Steps to reproduce the behavior

1. Create a Collection with a Time and a DateTime field
2. Open the CM and add a new entry for the collection, try to add some values to the Time dropdown for both fields, and Save
3. After saving the initial value is shown in the Time dropdown

### Expected behavior

Show the last saved value

### Screenshots

https://github.com/strapi/strapi/assets/2589748/586e23e5-e6c5-48a0-85cf-0b588bb70ad3

**Comment by oiorain** [comment]
Couldn't reproduce in rc.7 
I believe this has been fixed.
