### ISSUE TITLE
Strapi update from 4.8.2 to 4.25 loses date sorting

### ISSUE THREAD

**Issue by majkl-zumberi** [strapi/strapi#20533]
### Required System information

- Node.js version:20.10.0
- NPM version:10.2.3
- Strapi version:4.25
- Database:sqlite
- Operating system:macos sonoma
- Is your project Javascript or Typescript: jsvascript

### Describe the bug
hi i migrated my strapi project from 4.8.2 to the latest stable version 4.25
i noticed my frontend breaks because of a failing fetch over the backend api
localhost:1337/api/products?locale=it-IT&populate=deep%2C4&sort=date%3Adesc&pagination%5Blimit%5D=-1

the error i receive from strapi is the following
{“data”:null,“error”:{“status”:400,“name”:“ValidationError”,“message”:“Invalid parameter date”,“details”:{}}}

how can i sort based on the date in strapi@4.25?

### Steps to reproduce the behavior

1. Go to 'localhost:1337/api' and try to sort any collection with date:desc
4. See error "Invalid parameter date"

### Expected behavior

to sort collection with date as it was working without any issues like in strapi@4.8.2

**Comment by delapasionm** [comment]
we're also experiencing the same issue with the new strapi version about sort date by desc
