### ISSUE TITLE
[Content Manager] Repeatable components are randomly not saved 

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20542]
### Required System information
Node.js version: v20.9.0
Strapi version: v5.0.0-beta.10 (experimental : v0.0.0-experimental.a53a4b1c8f7981a689823cdd719105671e1c6392)
Operating system: Windows WSL and OS

### Describe the bug

In the Content Manager, when you have a Collection Type with a repeatable component, when hitting [Save] your data is randomly lost.

First case I've tried :  if you fill in an entry with more than 2 components, the first 2 ones are correctly saved, the 3rd one is never saved. When I went back to the CT later, the 3rd component was surprisingly saved.
Second case I've tried : no component at all was saved after many trials. When I went back later, only the first one was saved.
Third case I've tried : adding a 4th component to my first entry with already 3 components. 4th one was never saved.

Already confirmed by @alexandrebodin (first case).

### Steps to reproduce the behavior

1. Go to CTB, create a collection type including a repeatable component
2. Go to CM, create an entry for this CT
3. Create 1 repeatable component, Save
4. Create a second repeatable component, Save
5. Create a 3rd component, Save .

### Expected behavior

All repeatable components should be saved.

### Screenshots

https://app.dashcam.io/replay/667064c22d1e3d007642e9ec?share=Q3Tn2TeuQfBwpslyoRnRYA

**Comment by alexandrebodin** [comment]
should be fixed by https://github.com/strapi/strapi/pull/20558
