### ISSUE TITLE
[Strapi v5 RC] Unable to upload asset on Safari; buttons are hidden

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20556]
### Required System information

- **Node.js version**: 18.17.0
- **NPM version**: yarn/1.22.19
- **Strapi version**: 5.0.0-rc.2
- **Database**: sqlite
- **Operating system**: darwin-arm64
- **Is your project Javascript or Typescript**: Typescript

### Describe the bug

I am unable to upload an asset on Safari; the buttons are hidden.

### Steps to reproduce the behavior

1. Open Safari and navigate to the asset upload page.
2. Attempt to upload an asset.
3. Observe that the upload buttons are hidden and the asset cannot be uploaded.

### Expected behavior

The asset upload buttons should be visible and functional on Safari, allowing for successful asset uploads.

### Screenshots

<img width="1206" alt="Screenshot 2024-06-19 at 12 02 32" src="https://github.com/strapi/strapi/assets/8948363/e77ed219-3847-4f37-8fb2-d4bda8673bd3">

### Code snippets

N/A

### Additional context

N/A

**Comment by simotae14** [comment]
It seems similar to this ticket https://github.com/strapi/strapi/issues/20574 fixed with this PR https://github.com/strapi/design-system/pull/1759 we need just to release the new version of the DS and use it in the CMS and check if it solves the issue

**Comment by remidej** [comment]
@simotae14 you're right, I'll close it now so we know it's been addressed
