### ISSUE TITLE
graphql plugin totalCount support

### ISSUE THREAD

**Issue by isabolic** [strapi/strapi#2055]
Hi guys,

I'm using graphql plugin and looking from the code "totalCount" or "totalNumberOfRows" attribute is missing. I'm using Postgres database. Since API already supports count method. 

Best regards
isabolic

**Comment by derrickmehaffy** [comment]
@isabolic Please use the proper template and also: https://github.com/strapi/strapi/pull/1407

**Comment by lauriejim** [comment]
Hello @isabolic , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
