### ISSUE TITLE
[Content Manager] Eye icon in Password field is wrongly positioned

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20568]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL and OS

### Describe the bug

Eye icon in Password field is not well positioned

### Steps to reproduce the behavior

1. Create a CT with Password field
2. Go to CM and create an entry for this CT
3. Check Password field  : eye icon is not well positioned

### Expected behavior

The eye icon should be positioned better.

### Screenshots

![image](https://github.com/strapi/strapi/assets/97893822/6098c900-34b8-4961-830f-41a4c599871b)

**Comment by KhachiSahil** [comment]
i can fix this issue instantly assign it to me

**Comment by simotae14** [comment]
it seems solved in the last version of v5
