### ISSUE TITLE
[Releases] Scheduling asks for a Date even if it's set

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20570]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL and OS

### Describe the bug

Content Releases: Scheduling asks for a Date even if it's set

### Steps to reproduce the behavior
- Start creating a new scheduled release
- Set all the required fields, except the *Date* , which is set to “today” by default.
- Press continue, and a field error will prompt asking for the date field (that is set to today)

### Expected behavior

Error message shouldn't be displayed, today's date should be set up correctly.

### Screenshots

https://github.com/strapi/strapi/assets/97893822/60344571-dbe1-458f-827c-43d718924359

**Comment by MarionLemaire** [comment]
Additional comment : the error message is wrong (displaying "date is a required field" instead of not proposing a passed date/time)

**Comment by MarionLemaire** [comment]
https://github.com/strapi/strapi/assets/97893822/69828a2a-4c88-4a4d-b7d6-c3817d48fa9e

**Comment by harshit078** [comment]
Hi @MarionLemaire, Can I take this issue up ?

**Comment by remidej** [comment]
https://github.com/user-attachments/assets/2c7f663d-b8b6-48fe-aa33-a324a5bfc64b

@MarionLemaire I'm not able to reproduce the issue on v5/main for now, so I'll close the ticket for now, let me know if you still see the issue and I'll reopen if needed
