### ISSUE TITLE
Publish workflow

### ISSUE THREAD

**Issue by aljacinto** [strapi/strapi#2057]
**A moderator role should be included so that content can be reviewed and approved before making it available to REST api or graphql**

**Comment by derrickmehaffy** [comment]
@aljacinto that will likely come with admin permissions, currently it is not possible. The Strapi team have already stated that right now the AdminUI is for admins only and that more in depth permissions will come in a new plugin.

**Comment by aljacinto** [comment]
@derrickmehaffy thanks!  I saw the images in this plugin (https://strapi.io/marketplace/content-manager) and was looking at how it has author and ispublished column.  Is that a mockup only??

**Comment by derrickmehaffy** [comment]
yes @aljacinto that is a sample mock up

**Comment by lauriejim** [comment]
Thank you for this feedback

**Comment by candreoliveira** [comment]
@derrickmehaffy Do you have any ETA for this feature? It seems to be a very common use case for CMS. Or at least any thread or discussion about this plugin implementation? It'd like to watch and contribute.

**Comment by derrickmehaffy** [comment]
@candreoliveira I do not work for Strapi thus cannot provide an ETA. I am only a contributor.

If there is a feature you want to see, I welcome you to summit your own pull request for it, else features are built based on the highest votes from the product board and based on the Strapi teams focus.

As an open source project, everyone is welcome to build features and submit them.

**Comment by ChasLui** [comment]
@aljacinto You can look at [n8n](https://n8n.io)

**Comment by imp-dance** [comment]
Is there no way of doing an approval flow as-is? 

If we were able to set roles to specific fields inside of content types then we could just do a boolean "published", and not allow anyone but "moderator" to touch it.

**Comment by derrickmehaffy** [comment]
> Is there still no way of doing an approval flow, as-is?
> 
> If we were able to set roles to specific fields inside of content types then we could just do a boolean "published", and not allow anyone but "moderator" to touch it.

@imp-dance you could restrict based on policy simply checking the `ctx.state.user.role` ID vs an "approved" set of roles that can view/edit.

**Comment by imp-dance** [comment]
@derrickmehaffy Interesting, but I've got to be honest and say this doesn't tell me much. Could you point me in the right direction? Where would I go about adding these policies?

**Comment by derrickmehaffy** [comment]
@imp-dance

https://strapi.io/documentation/3.0.0-beta.x/concepts/policies.html

Policies run after the users-permission plugin but before the controller is called, they are also executed in order based on their order in your routes.json file.

You could accomplish the same thing by overriding the controller (such as here: https://strapi.io/documentation/3.0.0-beta.x/guides/is-owner.html ) but it's more "user-friendly" to handle it in a dynamic and reusable global policy instead of overriding the controller.

This also prevents issues in the future if the core controller structure changes in that you don't need to update your controller code.

**Comment by imp-dance** [comment]
@derrickmehaffy Perfect! Thank you 🎉
