### ISSUE TITLE
Continue/Cancel Buttons do not Display on Safari

### ISSUE THREAD

**Issue by CodeToTee** [strapi/strapi#20574]
### Required System information
- Node.js version: v20.12.0
- Yarn version: 1.22.22
- Strapi version: 5.0.0-beta.13
- Database: mysql (MariaDB 10.5 in a Docker container)
- Operating system: MacOS Sonoma 14.5 - darwin x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug
When on the Admin panel, in the Content-type Builder screen, when you try to 'Create new collection type', 'Create new single type', or 'Create new component', the CancelContinue dialog buttons do not display when using Safari or Duck Duck Go Browser (on a Mac).

The bug is that within the dialog, there is a <header> tag, followed by a `<form>` tag, then a `<footer>` tag within the `<form>`.  If/when I manually move the footer outside the form, then the buttons display properly.  See attached screenshots (before/after moving the footer outside the form).

### Steps to reproduce the behavior
1. Go to Admin Panel
2. Click on Content-Type Builder
3. Click 'Create new single type' (or any other type)
4. No buttons appear when using Safari

### Expected behavior
Buttons appear on Safari.

### Screenshots
With no buttons (and Dev Tools showing):
<img width="1385" alt="Screenshot 2024-06-20 at 4 32 54 PM" src="https://github.com/strapi/strapi/assets/16628720/0d272f74-011f-4bf3-8f74-9878a2c62bd8">

With buttons (after manually dragging the footer outside the form)
<img width="1423" alt="Screenshot 2024-06-20 at 4 33 10 PM" src="https://github.com/strapi/strapi/assets/16628720/750291f4-e4b5-4055-b92e-d4dd3daad9cf">

**Comment by Eventyret** [comment]
Confirmed in `v5.0.0-rc.3` effecting `Safari` Tested side by side in Arc, Chrome, Firefox all working Safari does not show the buttons.

**Comment by CodeToTee** [comment]
Please note that PR #20652 fixes this issue.  It's been 'in review' for two weeks.
