### ISSUE TITLE
Problem with encoding - Strapi saves special characters as '?'

### ISSUE THREAD

**Issue by Defozo** [strapi/strapi#2058]
**Informations**
- **Node.js version**: v10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: MySQL / MongoDB
- **Operating system**: Ubuntu

**What is the current behavior?**

When I create a new article and type for example 'żółć' it gets saved and displayed as '?ó??'.

**Steps to reproduce the problem**

Install Strapi, create a new article with title or content 'żółć'.

**What is the expected behavior?**

I'd like to see 'żółć' when I type in the title box 'żółć'.

**Suggested solutions**

I switched locales on my operating system to `pl_PL.UTF-8` but that resulted in no change in Strapi's behavior.
I tried with different databases - MySQL on AWS RDS and MongoDB hosted on the same machine using Docker.

**Comment by derrickmehaffy** [comment]
Couldn't reproduce this on Strapi v14.2 using MariaDB (MySQL) 10.2.

Both the adminUI:

![image](https://user-images.githubusercontent.com/8593673/46362633-b0607080-c625-11e8-8779-ff87eff18b7a.png)


And API response:
![image](https://user-images.githubusercontent.com/8593673/46362653-bd7d5f80-c625-11e8-8a52-c4e65bbd6440.png)

**Comment by Defozo** [comment]
Okay, I set up a new project and it's working fine with MongoDB. Thank you. Though I still don't know why it wasn't working alright in the first place.

**Comment by Zuluseq** [comment]
I came across the same problem.
I don't understand why you don't define columns in mysql as UTF8?
