### ISSUE TITLE
[i18n] Cannot scroll up and down in the locale selection dropdown

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20599]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL and OS

### Describe the bug

When adding a new locale by searching, I cannot see the result of what I’m typing in the field, and I cannot scroll up or down in the dropdown

### Steps to reproduce the behavior

1. Go to Settings > Internationalization
2. Add a new locale
3. Search "german" by typing "GER"
4. See that you can't see what you're typing
5. See that you can't scroll to see all results

### Expected behavior

Scrolling up through the searching results should be possible (in addition, seeing my research typing should also be possible instead of displaying "Select")

### Screenshots

https://github.com/strapi/strapi/assets/97893822/14a8f067-b035-4927-9411-4ccb101f5c4f

**Comment by KhachiSahil** [comment]
i can fix this issue assign it to me
