### ISSUE TITLE
[Content Manager] List view options menu is not visible on small displays

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20595]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: OS

### Describe the bug

List view options menu is not visible on small displays

### Steps to reproduce the behavior

1. Go to CM
2. Create an entry
3. Reduce your screen
4. See List view options : they are not visible

### Expected behavior

List view options should be visible for every display

### Screenshots

https://github.com/strapi/strapi/assets/97893822/dcd46eb7-88f7-4276-8b6c-ad086a68c205

**Comment by yanniskadiri** [comment]
Confirmed in rc.7

**Comment by Feranchz** [comment]
This is fixed at rc15
