### ISSUE TITLE
[Content Manager] Wrong behaviour of UID field status

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20598]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL

### Describe the bug

UID field displays “Unavailable” in a saved entry.

### Steps to reproduce the behavior

1. Create a CT with UID field
2. Go to CM, create an entry for this CT
3. Fill in UID field
4. Save this entry
5. Check the entry : UID status says "unavailable"

### Expected behavior

UID status shouldn't display unavailable (must not display anything when entry is already saved maybe ?)

### Screenshots

My only entry for this CT is saved : 
![image](https://github.com/strapi/strapi/assets/97893822/675d11c0-b345-4c67-b544-0f5bddbf75e6)

Still the status of UID field says it's unavailable : 
![image](https://github.com/strapi/strapi/assets/97893822/ce8a762e-aeae-4756-98f6-703844153416)

**Comment by oiorain** [comment]
Confirmed in rc.7.  
But it seems to work at first when you create the entry and then not work anymore. i'm not sure but there is still a problem with uid showed as unavailable when it should be available.

**Comment by remidej** [comment]
done in #20922 and #20985
