### ISSUE TITLE
[Releases Scheduling] Date/time picker issue

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20594]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.14
Operating system: Windows WSL

### Describe the bug

Date/time picker field has a weird behaviour when selecting a scheduled time for a release.

### Steps to reproduce the behavior

1. Create a new scheduled release

Don’t select another date (today’s date is already displayed)

Try to select a time : you can’t scroll to find the time further than 00:45

Select 00:30

Click [Continue]

You get an error message which is wrong : “Date is a required field”

Try to click the cross of the Date field : you can’t erase the field

Erase the date by selecting the whole field

Pick up another date to come

The error message “Date is a required field” is still displayed

Click [Continue]

It works

### Expected behavior

Date/time picker should work correctly.

### Screenshots

https://app.dashcam.io/replay/66758a8ee4ec3e0074793cd4?share=xoIfktm6s5Iv1lK4EcrKlw

**Comment by Marc-Roig** [comment]
closing in favor of https://github.com/strapi/strapi/issues/20570
