### ISSUE TITLE
[Releases] Going back from Content Manager to Content Releases doesn't work as expected

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20591]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL and OS

### Describe the bug

If I click the “Go to Content Manager” button in a release, the go back button doesn't work as expected, it is not redirecting me to the release page.

### Steps to reproduce the behavior

1. Go to Releases
2. Create a new release
3. Click on [Open the Content Manager]
4. From CM page, click Back arrow button

### Expected behavior

Go back button should redirect me to my release page.

### Screenshots
https://app.dashcam.io/replay/667589bebcbf70007514e420?share=wjlj2PxoYlWfcizWJ7F9ww

**Comment by yanniskadiri** [comment]
Confirmed

**Comment by alexandrebodin** [comment]
cc @oiorain
