### ISSUE TITLE
Filtering on relations does not populate data like the unfiltered list does in Admin UI

### ISSUE THREAD

**Issue by verdverm** [strapi/strapi#20604]
### Required System information

- Node.js version: 20
- NPM version:
- Strapi version: v5.0.0-beta.14
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

Following up on #20058, while this no longer errors, the result is missing the relation data for the field that is filtered on

### Steps to reproduce the behavior

Same as #20058

### Expected behavior

Should still be able to see the data in the relation. In this case, we are setting multiple tags on documents. We want to be able to search by tag and have the results

1. show the tags that match the filter
2. show all tags, so that we might refine our filter(s)

Generally, I would expect the same relation population to occur in the filtered list as the unfiltered list.
The relation population does work if filtering by a direct field on the content-type

It would be great if the UI colored the matching entries different from the non-matching.

### Screenshots

Relation filter, not populated

<img width="1071" alt="Screenshot 2024-06-21 at 12 55 23 PM" src="https://github.com/strapi/strapi/assets/1390600/46c8af67-a092-4125-b70e-46d5c3c6358c">

Field filter, does populate

<img width="1088" alt="Screenshot 2024-06-21 at 1 03 37 PM" src="https://github.com/strapi/strapi/assets/1390600/71da4e44-08c7-4114-8332-032406a28c21">

**Comment by derrickmehaffy** [comment]
Confirmed on v5.0.0-rc.6

**Comment by alexandrebodin** [comment]
FIxed in rc.13 :)
