### ISSUE TITLE
Issue with Duplicate Item Creation When Throwing Errors in Lifecycle Hooks

### ISSUE THREAD

**Issue by DanMoveo** [strapi/strapi#20644]
## Bug report
Required System information

Node.js version: v18.19.0
NPM version: 10.2.3
Strapi version: 4.10.8
Database: (Specify your database, e.g., PostgreSQL, MySQL, SQLite)
Operating system: Darwin Kernel Version 23.5.0 (MacOS)
Is your project Javascript or Typescript: Typescript

## Describe the bug
When an error is thrown within a lifecycle hook (afterCreate or afterUpdate), it results in the creation of a duplicate item in the database. This behavior is unexpected and causes multiple entries for what should be a single operation.

## Steps to reproduce the behavior
Go to Strapi admin panel and create a new item in a collection (e.g., a game entry).
Save the item with a missing required field (e.g., the season).
An error is thrown within the lifecycle hook.
Instead of the operation being stopped, a new item is created with a new ID.
Expected behavior
When an error is thrown during the lifecycle hook execution, the operation should be rolled back, and no new item should be created.

## Code snippets
Here is the code for the lifecycle hook where the issue occurs:

typescript
import { IGameServerResponse } from "../../../../interfaces";
import { gameService } from "../../../../services/game.service";
import { ApiTypes } from "../../../../types/enums";
import { gamePopulate } from "../../../../populates/game/game.populate";

import { IGameServerResponse } from "../../../../interfaces";
import { gameService } from "../../../../services/game.service";
import { ApiTypes } from "../../../../types/enums";
import { gamePopulate } from "../../../../populates/game/game.populate";

async function handleAfterEvent(event) {
    const result = event.result;
    const { id, locale } = result;

    try {
        const game = (await strapi.entityService.findOne(ApiTypes.GAME, id, {
            ...gamePopulate.populateSingleGame(),
        })) as IGameServerResponse;
        const sessionId = game?.session?.id ?? null;
        if (!sessionId) {
            throw new Error("לא הוכנסה עונה למשחק הנוכחי");
        }
        await gameService.updateGameTeamBySession(game);
        await gameService.updateGameAgainstTeamBySession(game);
        await gameService.updateGameLeagueStageBySession(game);
        const afterGameExist = game?.afterGame ? true : false;
        const beforeGameExist = game?.beforeGame ? true : false;
        if (!beforeGameExist || !afterGameExist) {
            await gameService.createBeforeGameAndAfterGameEntries(
                id,
                locale,
                beforeGameExist,
                afterGameExist,
            );
        }
        await gameService.updateEntryDescription(id, game);
    } catch (error) {
        const ctx = strapi.requestContext.get();
        const gameId = ctx?.request?.body?.id;
        const isPublishedAt = ctx?.request?.body?.publishedAt;
        if (isPublishedAt) {
            await strapi.db.connection("games").where({ id: gameId }).update({
                published_at: null,
            });
        }
        ctx.throw(400, {
            message: error.message,
            name: "ApplicationError",
        });

        return ctx;
    }

    return;
}

export default {
    afterCreate: handleAfterEvent,
    afterUpdate: handleAfterEvent,
};

## Additional context
The problem appears to be that throwing an error within the lifecycle hook causes Strapi to create a new item upon each error occurrence. Instead, the operation should stop, and no new item should be created.

Thank you for your assistance.

**Comment by rayvego** [comment]
Hey, I am trying to fix this issue, it seems like transactions can fix it. However, I am not able to find the file you are talking about. 

This is my setup:

Launched In: 775 ms
Environment: development
OS: darwin-arm64
Strapi Version: 4.25.1
Node/Yarn Version: yarn/4.0.1 npm/? node/v20.0.0 darwin arm64
Edition: Community
Database: sqlite

Could you please help me where am I going wrong?

**Comment by derrickmehaffy** [comment]
You are on a really old strapi version, I wasn't able to reproduce this on v4.25.1

**Comment by DanMoveo** [comment]
Hello,

Thank you for your patience. Below are the complete environment details, including the specific versions of Strapi and related plugins. This information should assist in diagnosing the issue with duplicate item creation when errors are thrown in lifecycle hooks:

- **Node.js version**: v18.19.0
- **Yarn version**: 1.22.22
- **Strapi version**: 4.10.8
- **Operating System**: Darwin ip-192-168-1-211.eu-central-1.compute.internal 23.5.0 Darwin Kernel Version 23.5.0; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103 arm64
- **Database**: PostgreSQL 
- **Project Type**: TypeScript

**Installed Strapi Packages:**
- `@strapi/admin@4.10.8`
- `@strapi/plugin-content-manager@4.10.8`
- `@strapi/plugin-content-type-builder@4.10.8`
- `@strapi/plugin-email@4.10.8`
- `@strapi/plugin-upload@4.10.8`
- `@strapi/plugin-users-permissions@4.10.2`
- `@strapi/plugin-graphql@4.11.0`
- Additional plugins as listed in the previous output
