### ISSUE TITLE
Strapi 5 rc0 - populate on dynamic zones not working

### ISSUE THREAD

**Issue by shamglam** [strapi/strapi#20653]
### Required System information

- Node.js version: v20.12.2
- NPM version: 10.5.0
- Strapi version: v20.12.2
- Database: mysql
- Operating system: ubuntu
- Is your project Javascript or Typescript: typescript

### Describe the bug

The v5 docs - presumably up to date regarding using populate for dynamic zones states that it is possible to use "*" to populate a dynamic zone using the shared strategy - yet doing so returns an internal server error.

Error message in strapi - Expected a fragment ("on") or "count" but found {"populate":"*"}

### Steps to reproduce the behavior

1.  Create a collection of a type which has a dynamic zone 
2. try using populate syntax for rest api i.e. - /api/articles?populate[blocks][populate]=*

### Expected behavior
Dynamic zone data should be returned

**Comment by derrickmehaffy** [comment]
We removed the old population option (this should be documented as a breaking change) but you'll need to use the new fragment syntax: 

https://docs-next.strapi.io/dev-docs/api/rest/guides/understanding-populate#detailed-population-strategy

**Comment by Convly** [comment]
Just a quick note here, we're discussing internally whether to open the populate: * for morphs or not.
I'll link further discussions, thanks for opening the issue
