### ISSUE TITLE
Server Shuts Down

### ISSUE THREAD

**Issue by harshchaudhari9** [strapi/strapi#20651]
to reproduce my issue : 
1. do all the normal/ basic steps that is step strapi server (works fine)
2. create content (even that works fine)
3. create a component (and server shutsdown )
4. 
 Error i get : 
[2024-06-27 23:16:53.018] http: GET /content-manager/collection-types/api::user-resume.user-resume?page=1&pageSize=10&sort=title:ASC (2905 ms) 200  {all good working server before creating component}
[2024-06-27 23:17:25.285] http: POST /content-type-builder/components (1027 ms) 201
[2024-06-27 23:17:25.290] info: Shutting down Strapi
[2024-06-27 23:17:25.507] info: Strapi has been shut down
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (103ms)
✔ Creating admin (434ms)
⠦ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information

┌──────────────────────────────────────────────────┐│                                                  ││   TypeError [ERR_INVALID_ARG_TYPE]: The "path"   ││   argument must be of type string. Received      ││   undefined                                      ││   at Object.join│   @strapi\core\dist\loaders\index.js:12:3)       ││   at async Object.register (C:\vscodefiles\ai-   ││   res-backend\node_modules\@strapi\core\dist\p   ││   roviders\registries.js:26:5)                   ││   at async Strapi.register                       ││   (C:\vscodefiles\ai-res-backend\node_modules\   ││   @strapi\core\dist\Strapi.js:322:7)      
 

my system : window 11
node v 20
npm v 10
database tried working with both postgrsql and mysql gives same problem

**Comment by harshchaudhari9** [comment]
video :
https://drive.google.com/file/d/1JrPX4kUrF8OuSuBTQ263uHvLHAeQxpj8/view?usp=sharing

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/20650
