### ISSUE TITLE
Not able to Tranfer data from local to cloud Strapi project.

### ISSUE THREAD

**Issue by alirazasdk** [strapi/strapi#20673]
### Required System information
Node.js version: v20.13.1
NPM version: npm/10.5.2
YARN version: yarn/1.22.22
Strapi version: 4.23.1
Database: mysql
Operating system: Ubuntu :- 22.04.4 LTS And Windows 11
Is your project Javascript or Typescript: Javascript

### Describe the bug
Previously i was able to tranfer data from local to strapi cloud using following command.

> yarn strapi transfer --to https://mystrapi.com/admin

But from previous two weeks, i got this error whenever i trasfer data from local to cloud.

```
Transfer process failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
But i'm able to trasfer data from cloud to local project.

As a workaround to this problem, i tranfer data from different PCs using window 10 and 11. 

But from previous two days, i'm not able to transfer data from local to cloud on any machine.

**Comment by Garvitpant777** [comment]
can i work on this ? please let me know . thank you

**Comment by butcherZ** [comment]
Hi @alirazasdk , I have just tested the data transfer from local to strapi cloud with the latest v4 version, and I couldn't reproduce the issue you have mentioned. Could you please upgrade to v4.25.11 and let us know if the problem still persists? If so, we might need a bit more information to assist you :)
