### ISSUE TITLE
Unable to start the Strapi project

### ISSUE THREAD

**Issue by nataliarosa9** [strapi/strapi#20684]
Hello! 

I successfully set up a Strapi project following the guide. When I tried to run it using "npm run develop," I encountered the following error:

![Screenshot 2024-07-04 093701](https://github.com/strapi/strapi/assets/6066985/ce2aae04-1f9e-4a39-b68d-a7ba62c856c7)

![Screenshot 2024-07-04 094606](https://github.com/strapi/strapi/assets/6066985/d073cd34-dde6-461e-9eb6-4257b7efefe2)

![Screenshot 2024-07-04 094527](https://github.com/strapi/strapi/assets/6066985/d2353a9c-5da4-4bf3-8aff-53b2dbf28cae)

**Comment by Convly** [comment]
Hi, it seems to be a mysql error (or at least an error originating from the mysql adapter for NodeJS from what I've digged online).

Unfortunately, without more information, it'll be hard to reproduce this one. Is this on a fresh Strapi install? new MySQL DB? What version of MySQL are you using?

Thanks in advance!

**Comment by nataliarosa9** [comment]
Hello! 

Thank you for your answer. 

Yes, it is a new Strapi installation and a new MySQL DB. The version of my MySQL is "Ver 8.0.37-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))".

I also created a new user with all grants for this specific database but encountered the same problem. I have other databases that work perfectly at the moment.

**Comment by Convly** [comment]
Interesting, are the other databases mysql instances too?

**Comment by nataliarosa9** [comment]
Yes, the other databases are database MySql instances, too. I also tried to redo the installation from the beginning. However, I used the Squilte database and had the same problem. 

![Screenshot 2024-07-10 112644](https://github.com/strapi/strapi/assets/6066985/038b06b8-7733-415f-a95b-fcf2c77c44f2)

![Screenshot 2024-07-10 112704](https://github.com/strapi/strapi/assets/6066985/c94daf78-8774-4ce3-9ee8-c5ff741216a8)
