### ISSUE TITLE
[Strapi v5 rc] Unable to scroll list of locales or type in box in internationalization configuration

### ISSUE THREAD

**Issue by ls-ramos** [strapi/strapi#20681]
### Required System information

- Node.js version: v20.15.0
- NPM version: yarn/4.3.1
- Strapi version: 5.0.0-rc.0
- Database: postgres
- Operating system:  linux-x64 - Ubuntu 22.04.4 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

On the modal Settings ->  Internationalization -> Add new locale

It is not possible to scroll the list of locales only move up and down with the arrows of the keyboard.

![image](https://github.com/strapi/strapi/assets/29318376/0cc7ae29-93f1-427f-93e0-18ccaad560e6)

### Steps to reproduce the behavior

1. Go to Settings ->  Internationalization -> Add new locale
2. Click on locales
3. Try to scroll the list and see that it is only possible with the keyboard 

### Expected behavior

It is expected that I could scroll that list normally

### Additional context

At first I thought that it was impossible to scroll at all, so I was struggling to select the locale I wanted, after a few minutes I noticed that it worked with the keyboard. So it is less critical since I can select whatever I want still, just a little annoying and not the best user experience.

**Comment by derrickmehaffy** [comment]
Not only can I confirm this but we also can't type in the box like `fr` on rc.6

**Comment by simotae14** [comment]
This issue will be fixed with the upgrade in the CMS of the last DS version

**Comment by simotae14** [comment]
Fixed in the last version of v5
