### ISSUE TITLE
[Strapi v5 rc.0] Unable to retrieve pre-signed URL from API neither in the content;

### ISSUE THREAD

**Issue by luispiresgympass** [strapi/strapi#20683]
### Required System information

- Node.js version: v20.11.1
- NPM version: v10.2.4
- Strapi version: v5.0.0-rc.0
- Database: PostgreSQL
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

As discussed with @PaulBratslavsky on the Open Office Hours I've noticed the following case

Installing an S3 Provider and using `AWS_ACL` as `private` the upload part succeeded, but, retrieving any models with the `media` type will cause an issue with S3 URLs coming without signature and causing a no-loading image scenario. 

Looking down into the code I noticed that it had been commented: [[Click Here](https://github.com/strapi/strapi/blob/v5.0.0-rc.1/packages/core/upload/server/src/services/extensions/core/entity-service.ts)]

### Steps to reproduce the behavior

1. Install plugin `@strapi/provider-upload-aws-s3` version 5.0.0-rc.0;
2. Do the following configuration:
`
upload: {
    config: {
      provider: 'aws-s3',
      providerOptions: {
        region: env('AWS_REGION'),
        params: {
          ACL: env('AWS_ACL', 'private'),
          Bucket: env('AWS_BUCKET'),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  }
`
3. Go to admin interface and click to `Media Library`;
4. Upload a file;
5. Create a model with `media` with one of the types;
6. Create model using a media;
7. Save and Publish the model;
8. Bug happen

(If you do the API request the problem persists);

### Expected behavior

If I do the configuration setting the `AWS_ACL` to `private` everything that uses `media` from the ADMIN Ui or through the API should return Presigned URLs;

### Screenshots

![image](https://github.com/strapi/strapi/assets/58981184/36e3b64a-4687-4559-8416-e0f7ec157f28)

### Code snippets

[[Click Here](https://github.com/strapi/strapi/blob/v5.0.0-rc.1/packages/core/upload/server/src/services/extensions/core/entity-service.ts)]

**Comment by Garvitpant777** [comment]
Can I work on this ?

**Comment by luispiresgympass** [comment]
Hello @derrickmehaffy how are you? Any news about it?

**Comment by Marc-Roig** [comment]
Hello :) We are currently working on this https://github.com/strapi/strapi/pull/20861
