### ISSUE TITLE
[Strapi v5 rc] Switching locales causing warning "An error occurred while fetching draft relations on this document."

### ISSUE THREAD

**Issue by ls-ramos** [strapi/strapi#20682]
### Required System information

- Node.js version:  v20.15.0
- NPM version: yarn/4.3.1
- Strapi version: 5.0.0-rc.0
- Database: postgres
- Operating system: linux-x64 - Ubuntu 22.04.4 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Switching between locales for the first time gives an error and makes the localization to be in a incorrect state.

### Steps to reproduce the behavior

1. Go to a content type that has internationalization enabled
2. Create a document in a locale and publish it
3. Switch to another locale
4. See warning message (An error occurred while fetching draft relations on this document.) 
5. See that on the list of locales the content that was previously published is not marked as published anymore

### Expected behavior

After switching to the other locale, I expect no warning and that the list of locales stays in a consistent state. Displaying what was published before as published

### Screenshots

Here is a video of the bug being reproduced

https://github.com/strapi/strapi/assets/29318376/b4a0920a-3831-4912-9f7e-b813bd77f7f3

### Additional context

I don't think it is super critical since this seems to happen only when I go to a locale that has no content for it yet. If I save some content in the locale then everything works as expected. Anyway it is a little confusing for the user.

**Comment by derrickmehaffy** [comment]
unable to reproduce on rc.6

**Comment by violabg** [comment]
I'm on 5.0.0-rc.8 and I see exactly the behaviour in the attached video

**Comment by Skuallpa** [comment]
I'm experimenting the same issue with `5.0.0-rc.10`. I face the issue only with collection types. It seems to work fine with single types content.
