### ISSUE TITLE
v5: admin panel crash with single DZ and single type

### ISSUE THREAD

**Issue by CodeToTee** [strapi/strapi#20696]
## Bug report
When doing a fresh install of Strapi v5 (rc2), if you create a Single Type with a single DZ, and an additional single Text type, then go to the Content Manager for the DZ, it will crash, displaying a Javascript error: `Cannot read properties of undefined (reading 'push')`

### Required System information
Repo with schema that causes the failure: [https://github.com/CodeToTee/strapi-dz-crash](https://github.com/CodeToTee/strapi-dz-crash)

### Describe the bug
A Content Manager Single Type with a single DynamicZone and a single Type will cause Javascript to attempt to `push()` an item onto an undefined value.

### Steps to reproduce the behavior

Here are the steps I used to create this crash:
* Install and initialize a fresh Strapi v5 project
```
npx create-strapi-app@5.0.0-rc.2 strapi-dz-crash --use-yarn
cd strapi-dz-crash
yarn develop
```
* Open admin at `http://localhost:1337` and configure admin email
* Navigate to Content-Type Builder
* Create a component called 'comp' with a single text field 'text'
* Create a Single Type called 'home' with a single Dynamic Zone that includes the 'comp' created above
* Save
* Navigate back to the Content-Type Builder
* Navigate to the 'home' Single Type
* Add a single Text type called 'text'
* Navigate to Content Manager
* It will crash with an error saying `Cannot read properties of undefined (reading 'push')`

Note: You may see other errors along the way of replicating this issue.  I haven't logged those, but rather just went past them by refreshing the browser window.

### Expected behavior

It should not crash.  😬

### Screenshots
<img width="809" alt="Screenshot 2024-07-05 at 1 36 00 PM" src="https://github.com/strapi/strapi/assets/16628720/46b2b3f6-fd66-4c33-a048-577d1a20fb25">

### Code snippets

Repo: [https://github.com/CodeToTee/strapi-dz-crash](https://github.com/CodeToTee/strapi-dz-crash)

The README for the repo has comments on this issue.

### Additional context

As noted in the repo, I experienced other crashes along the way while creating this bug report.  Below is one of the issues:
* After creating the first Component with a single Text type, and then trying to create the first Single Type ('home'), when adding the components it will crash.  To get past this issue, simply refresh the browser, then try again to create the Single Type ('home').
* In general, when I hit an issue, I would simply refresh the browser page to continue-forward.

**Comment by ktx-kirtan** [comment]
Got the same error

**Comment by derrickmehaffy** [comment]
can not reproduce on rc.6: 

![image](https://github.com/user-attachments/assets/b7b5b11e-66a0-4fe7-903b-e8472a76b796)
