### ISSUE TITLE
How to i18n for attributes and models show name in admin panel

### ISSUE THREAD

**Issue by JunQiGenYuan** [strapi/strapi#207]
**Node.js version**:
**npm version**:
**Strapi version**: 1.5.4
**Operating system**:

I want to show Chinese in admin panel. Is there a way to implement it?

**Comment by Aurelsicoko** [comment]
@JunQiGenYuan I'm sorry but you have to implement it manually. See the [Customization Section](http://strapi.io/documentation/admin#Customization) in the doc.

**Comment by JunQiGenYuan** [comment]
thanks
