### ISSUE TITLE
How to generate a token that will never expire?

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi#2070]
**What is the expected behavior?**
How to generate a token that will never expire? so we can use some strapi APIs that are protected by token in our other backend servers.

**Comment by derrickmehaffy** [comment]
Related: 
* https://github.com/strapi/strapi/issues/1086
* https://github.com/strapi/strapi/issues/1676

@demobo-com not currently possible but has been suggested before.

**Comment by lauriejim** [comment]
You can change [default jwt options](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Jwt.js#L12)

**Comment by akalitenya** [comment]
What is a proper way to change  default jwt options?

**Comment by akalitenya** [comment]
already solved by placing modified copy of Jwt.js to extensions/users-permissions/services/Jwt.js

**Comment by FaysalBsata** [comment]
@akalitenya  I couldnt find services directory,
![Screenshot 2020-03-19 at 13 52 37](https://user-images.githubusercontent.com/55600792/77054230-f01d4280-69e8-11ea-9ab1-9aebadd6c292.png)
can you help a bit more

**Comment by akalitenya** [comment]
@FaysalBsata you need to explore node_modules strapi library related to users-permissions

then you can copy and modify files to your project dir

Strapi will use your version of these files instead of those that in node_modules, just make sure that you name and place these files correctly

**Comment by FaysalBsata** [comment]
@akalitenya  Well noted, thank you I'll try and find it

**Comment by kevinadhiguna** [comment]
Thanks @gersur !

By the way, the link has moved to : 
https://strapi.io/documentation/developer-docs/latest/development/plugins/users-permissions.html#jwt-configuration
