### ISSUE TITLE
SSL Wrong Version Number

### ISSUE THREAD

**Issue by Jonas1015** [strapi/strapi#20719]
Requirements:
- Spin up new strapi application with typescript. version 4.25.2
- @strapi/provider-email-nodemailer 4.25.2

`
[Error: 00C8E465FF7A0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:]
{
  library: 'SSL routines',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}`

I can't get though this with every mailserver I have tried. I have come to think it's nodemailer provider issue. Kindly assist as soon as you see this issue.

**Comment by pavitpim40** [comment]
@Jonas1015 set `port` for 465 and `secure` true in `plugin.js` or your `.env`

` email: {
    config: {
      provider: "nodemailer",
      providerOptions: {
        host: env("SMTP_HOST", "smtp.example.com"),
        port: 465,
        secure: true,
        auth: {
          user: env("SMTP_USERNAME"),
          pass: env("SMTP_PASSWORD"),
        },
        // ... any custom nodemailer options
      },
      settings: {
        defaultFrom: env("EMAIL_ADDRESS_FROM"),
        defaultReplyTo: env("EMAIL_ADDRESS_REPLY"),
      },
    },
  },`

**Comment by Jonas1015** [comment]
Thanks.. Port 465 worked. Though the error message is misleading. I have used some bluehost mailservers that used port 587 and they were fine. I was looking to work with a problem related to SSL Versioning.
