### ISSUE TITLE
question on template, is it a typo?

### ISSUE THREAD

**Issue by caoer** [strapi/strapi#2071]
I'm not sure if it is a bug report or feature request. Maybe strapi can have a general issue template? 

checkout https://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/templates/bookshelf/service.template#L123

![image](https://user-images.githubusercontent.com/225856/46438465-8081ac00-c790-11e8-9088-5e4b5f2bfe9d.png)

I've not able to find the {path} param in the documentation of bookshelf. however, it does have patch, see: [save](http://bookshelfjs.org/#Model-instance-save). 
Is it a typo?

**Comment by maturanomx** [comment]
🤔 Really looks like a typo 😲. Good catch! 🥇

**Comment by lauriejim** [comment]
Yap looks like a typo, will update and test it.
