### ISSUE TITLE
Strapi v5.0.0-rc.3: The relationship is reset when updating the collection

### ISSUE THREAD

**Issue by koddr** [strapi/strapi#20727]
### Required System information

- Node.js version: v20.14.0
- NPM version: v10.7.0
- Strapi version: v5.0.0-rc.3
- Database: SQLite
- Operating system: macOS 14.5 (23F79)
- Is your project Javascript or Typescript: TS

### Describe the bug

I'm not sure if this bug is present in other DB configurations, but it always plays for me (video below).

### Steps to reproduce the behavior

1. Go to the dependent collection;
2. Make any changes in any field, save & publish;
3. Go to the main collection (or REST API call);
4. Relation to the dependent collection was reset;

### Expected behavior

So that dependencies are not reset when changing.

### Video

https://github.com/strapi/strapi/assets/11155743/3f6d3d40-c774-4d23-9a8b-7020d41656e1

### Code snippets

N/A

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
unable to reproduce on rc.6

**Comment by alexander-aleman** [comment]
I can reproduce this in rc.10.

I created 2 new collection types type1 and type2:
Type1 only has a text field "label"
Type2 has text a field "label" and a relation to Type1 (Type2 has many type1s)

Then create a Type1 and publish it. Next create a Type2 with a relation to the created Type1 and publish it.
When you check in the published tab of Type2 it looks ok now.

Next edit the label of the Type1 and publish it again.
Go to the created Type2 and check the draft, here you still see the link, now check the published and the relation seems to be missing. In the rest api you also get this behaviour, the way to fix the relation is by removing and adding the same relation again. Maybe it is somehow linked to a draft version?

**Comment by NEDDL** [comment]
@derrickmehaffy I am having the same problem using rc.11. Please see: #21062
