### ISSUE TITLE
Content type builder disappear on production heroku

### ISSUE THREAD

**Issue by xargr** [strapi/strapi#2072]
**Informations**
- **Node.js version**:  v10.11.0
- **yarn version**: 1.10.1
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: mlab mongod version: 3.6.8
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
After complete install and deploy a new application in herolu content type builder disappear only from production

![screenshot from 2018-10-04 06-11-42](https://user-images.githubusercontent.com/5754929/46451368-91d1b500-c79e-11e8-9564-07195da6627d.png)

content type builder plugin as you show has installed but unfortunately don't show in sidebar

**Comment by soupette** [comment]
The content-type-builder is disable by default in production. This is an intended feature.

**Comment by rahimimo** [comment]
I have a question @soupette If strapi uses three different database for production, staging and development and the content type which is built in development is not available in production and production does not have content type builder. Then what is the way to create a content type in production database ? Other than making the databases the same

**Comment by lauriejim** [comment]
Hello @rahimimo .

Not sure to understand `the content type which is built in development is not available in production`
If you create your content type in development (on your local machine) and you push your code in production (Heroku for example), you will find your content type in production...

**Comment by Vivsss** [comment]
HI, I've the same issue..
so, for example, in production I can't choose for a **text field with  WYSIWYG Editor** ?
that's available only in development environment?

**Comment by lauriejim** [comment]
@Vivsss I confirm your issue. 
Can you check if one already exist and if not create one please.

To manually fix it you will have to migrate your `core_store` key `plugin_content-manager_schema` value from your `dev`database to `production` database.

**Comment by johndows** [comment]
How can this be a intended feature?
We can't add new fields online, having a user doing it

**Comment by lauriejim** [comment]
@johndows It's simple, it's because you never update your data schema in production (that is the main reason)

We can add a second point, when you create/update/delete content type we write/delete files.
If you use multi servers we can't delete files on all of your servers (it's impossible)
Then if you create files on prod, how did you send them to your GitHub ? 
Common processes or to go from development to your production environment.

So we decide to block `development` stuffs/tools in production.

About the markdown editor, it's an issue, it's have to be possible.
Please check the message I wrote before.

**Comment by johndows** [comment]
@lauriejim Thanks for the answer. 

Why would you update the schema? Prepare the schema to support those fields and when you create a new type of content in production just post / other the DB.

And why creating files anyway? (And if you really need them, couldn't you create a script to check for updates in the DB and update files everywhere?) 

I'm sorry if I'm not seeing the picture here. Can you explain why you are not doing just using a simple CRUD mechanism here?

Big thanks

**Comment by lauriejim** [comment]
@johndows When you say:
> @soupette How can this be a intended feature?
We can't add new fields online, [...]

Adding a field it's modifying your data schema right ?
And I can't imagine modify something like that in production. For us it's `no way` and our position is to provide you (our users) good practice to create and manage your APIs.
We will never see someone add a new field in an e-commerce app for it's product on production without testing, running data migration, etc... 

The question `And why creating files anyway?` is a part of the `why we create Strapi?`
When you create a new content type via the UI its provide you a CRUD API and an interface in the admin to manage your data.
We create files to lets your fully customize your API. 
- If you want to modify sended data to add calculaed values you can.
- If you want create custom endpoint you can

We provide you all the code that make your app working. And you can do what you want with.

We don't store your models, data structure or something that make the CRUD work in database.

I thing it answer also to your last question.

**Comment by derrickmehaffy** [comment]
For one they save the schema in a file to track code changes in git easily, some of the stuff they have migrated into the database are now also having this issue. How do you track changes? I mentioned to the Strapi team that there should be file based overrides in many of these cases (permissions being one of them) so we can force file based storage as you *really* should not be changing this stuff in production. I support their choice on this 100% as someone who works in the enterprise world, you never ever develop/test in production.

**Comment by petre2dor** [comment]
@lauriejim migrating `core_store` is a bit of a pain. Is there an open issue for this? I could not find one.
I am interested in helping contributing to Strapi and this might be something I can fix.

**Comment by sylvaingirardbe** [comment]
> @Vivsss I confirm your issue.
> Can you check if one already exist and if not create one please.
> 
> To manually fix it you will have to migrate your `core_store` key `plugin_content-manager_schema` value from your `dev`database to `production` database.

@lauriejim is there an issue tracking this? I seem to be running into the same problem and can't quite figure out how to easily copy that from one database into the other.

**Comment by lauriejim** [comment]
Hum I don't think an issue is open about that.
It's a topic we know but it can be a good thing to open one about that.

**Comment by sylvaingirardbe** [comment]
I'll open one up.

**Comment by denveloperj** [comment]
Did this ever get fixed or do we still have to copy over the "plugin_content-manager_schema" every time a change is made in development?

**Comment by derrickmehaffy** [comment]
Still need to copy it over, it is being fixed in the rewrite I believe.

**Comment by yykoypj** [comment]
Maybe you can try to change the create-content_type operation in a databse way,which may really help to reduce the misunderstanding of this part of system.Creating content_types is always not a job of one single person,not to mention a developer.
