### ISSUE TITLE
Windows only: Strapi 4.25.3: Server crashes when creating a Component

### ISSUE THREAD

**Issue by RndUsername** [strapi/strapi#20730]
### Required System information
- Node.js version: v20.15.1
- NPM version: 10.7.0
- Strapi version: 4.25.3
- Database: SQLight
- Operating system: Windows 11
- Is your project Javascript or Typescript: JS

### Describe the bug

When creating a new component and saving it, the server crashes with: 
```
> strapi develop

⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (90ms)
✔ Creating admin (13337ms)
⠙ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                    │
│   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                                                 │
│       at Object.join (node:path:433:7)                                                                                                             │
│       at C:\Users\...\strapi-project\node_modules\@strapi\strapi\dist\core\loaders\components.js:17:31                           │
│       at Array.forEach (<anonymous>)                                                                                                               │
│       at C:\Users\...\strapi-project\node_modules\@strapi\strapi\dist\core\loaders\components.js:14:32                           │
│       at Array.reduce (<anonymous>)                                                                                                                │
│       at Object.loadComponents (C:\Users\...\strapi-project\node_modules\@strapi\strapi\dist\core\loaders\components.js:13:27)   │
│       at async Strapi.loadComponents (C:\Users\...\strapi-project\node_modules\@strapi\strapi\dist\Strapi.js:320:23)             │
│       at async Promise.all (index 6)                                                                                                               │
│       at async Strapi.register (C:\Users\...\strapi-project\node_modules\@strapi\strapi\dist\Strapi.js:341:5)                    │
│       at async Strapi.load (C:\Users\...\strapi-project\node_modules\@strapi\strapi\dist\Strapi.js:425:5)                        │
│                                                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
(System Paths abbreviated for anonymity)

### Steps to reproduce the behavior

1. Make a new project with `npx create-strapi-app@latest my-strapi-project --quickstart`.
2. Go to Content Type Builder and create a new component.
3. Fill out Display Name and Category.
4. Select Text Field.
5. Give the Text Field a name.
6. Click Finish.
7. Click Save.
8. Screen > "Waiting for Restart".
9. Server crashes.

When trying `npm run develop` the server crashes immediately with the same error.

### Expected behavior

I should be able to create components with out any errors

**Comment by DanielASMPT** [comment]
Just as a reference https://github.com/strapi/strapi/issues/20057#issuecomment-2221285775
I faced the Same issue on Microsoft Windows Server 2016.

**Comment by RndUsername** [comment]
I tried the same thing in v4.25.2 and it works fine. I think the newest version is just borked...

**Comment by thanhnha0706** [comment]
Latest version breaks

**Comment by zjjtm** [comment]
Same problem on 4.25.3

**Comment by sagar947** [comment]
Same problem in 4.25.3. Works fine in a relatively older version 4.13.5.

**Comment by derrickmehaffy** [comment]
Thank you all, I've set this one as critical and triggered our crisis process. Our engineering team will review this on Monday in the meantime we advise remaining on 4.25.2 if you need to use windows.

Mac and Linux users should not be impacted.

**Comment by abhijithkmpixel** [comment]
Looking forward to this
I also face issues installing the latest version
the dependency installation takes forever to complete
and the installation gets stuck at creating admin
