### ISSUE TITLE
Disable admin page

### ISSUE THREAD

**Issue by sravanireddyl** [strapi/strapi#2073]
**What is the expected behavior?**
There should be a way to disable admin page access.

**Comment by soupette** [comment]
@sravanireddyl  Could you be more specific?

**Comment by ishakuta** [comment]
to make it impossible to use it, e.g. removing it is not an option, imagine it should work only if there's some env var set to true, otherwise should not be accessible

**Comment by Aurelsicoko** [comment]
You can remove the folder if you don't want the admin. Or, you can create policy an apply it on every admin route `strapi.admin.config.routes`. In this policy, you'll be able to check if the option is set to true or not.

`./config/functions/bootstrap.js`
```js
'use strict';

module.exports = cb => {
  strapi.admin.config.routes = strapi.admin.config.routes.map(route => {
    route.policy = (route.policy || []).push('global.shouldAccessToAdmin');

    return route;
  });

  cb();
};
```

`./config/policies/shouldAccessToAdmin.js`
```js
module.exports = async (ctx, next) => {
  if (strapi.config.myCustomConfig || process.env.myCustomConfig) {
    return ctx.notFound();
  }

  await next();
};
```

As there is an easy workaround, I'm closing this issue... Feel free to comment on it or ping me if needed.

**Comment by kevinvugts** [comment]
> You can remove the folder if you don't want the admin. Or, you can create policy an apply it on every admin route `strapi.admin.config.routes`. In this policy, you'll be able to check if the option is set to true or not.

Can you elaborate more on this how to do this in Strapi V4?
