### ISSUE TITLE
v5: `countDraftRelations` is called for every entry in the list view

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#20736]
### Required System information

- Node.js version: 20
- Yarn version: 1.22
- Strapi version: 5 rc 3
- Database: sqlite
- Operating system: macOS
- Is your project Javascript or Typescript: JS

### Describe the bug

Just gave the RC3 a spin. Something I notice is that the list view is significantly slower because it calls `countDraftRelations` for every entry in view. If you set it to 100 entries, it will DDoS it's own backend with 100 tiny API calls. Is this really necessary?

### Steps to reproduce the behavior

1. Go to a list view
2. Set viewing entries to 100
3. Wait until the UI stops crashing
4. See the logs go crazy with API calls

### Expected behavior

I think this could be solved smarter than calling the API so many times, all of the time.

### Additional context

As discussed in the v5 beta discord channel

**Comment by derrickmehaffy** [comment]
fixed by: https://github.com/strapi/strapi/pull/20958
