### ISSUE TITLE
[Design] Missing disabled aspect for delete locale and delete document

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20759]
https://www.notion.so/strapi/Missing-disabled-aspect-for-delete-locale-and-delete-document-cd91baa7a6e649d598af958315345432?pvs=4

https://github.com/user-attachments/assets/6fbbf5a6-ca7a-431d-b0ff-e2038c96d6a7

**Comment by simotae14** [comment]
fixed with https://github.com/strapi/strapi/pull/20851
