### ISSUE TITLE
If no related entry has been created yet, I cannot save my entry

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20750]
https://www.notion.so/strapi/If-no-related-entry-has-been-created-yet-I-cannot-save-my-entry-49ae63e8eafa4a54839f59188aa4a765?pvs=4

**Comment by alexandrebodin** [comment]
Should we close if we cannot reproduce ?

**Comment by yanniskadiri** [comment]
Could not reproduce in the latest rc, I'll close it.
