### ISSUE TITLE
[Design] The focused state of the short/long text selector changes the size of the whole modal 

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20761]
https://www.notion.so/strapi/The-focused-state-of-the-short-long-text-selector-changes-the-size-of-the-whole-modal-d3d28f4e267849b7b094dfdfb1376b77?pvs=4

https://github.com/user-attachments/assets/7066e2b6-ec16-48df-9d58-c98a9dba2777

**Comment by oiorain** [comment]
Fixed.
