### ISSUE TITLE
[Design] IconButtons of the edit view are not squares and their icons are not centered

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20764]
https://www.notion.so/strapi/IconButtons-of-the-edit-view-are-not-squares-and-their-icons-are-not-centered-4d4429405d4f40f685205547bfec7c46?pvs=4

![CleanShot 2024-07-04 at 16 59 53@2x](https://github.com/user-attachments/assets/1294a5b7-6e29-41a4-a303-e604bb0c7389)

**Comment by simotae14** [comment]
fixed with https://github.com/strapi/strapi/pull/20855
