### ISSUE TITLE
[Design] The color of the field name and type should be Neutral800

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20762]
https://www.notion.so/strapi/The-color-of-the-field-name-and-type-should-be-Neutral800-e1901ad0c7754e66ba739a4276d7e74e?pvs=4
![CleanShot 2024-07-04 at 16 54 12@2x](https://github.com/user-attachments/assets/3f706ada-d321-4308-b36d-acea2785b88e)

**Comment by yanniskadiri** [comment]
Confirmed in rc.7

**Comment by alexandrebodin** [comment]
This is now fixed
