### ISSUE TITLE
[Design] Wrong icon color on save button in different pages

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20767]
https://www.notion.so/strapi/Wrong-icon-color-on-save-button-in-different-pages-0e640298a1814d61ae7f7c4bd7f84076?pvs=4

<img width="179" alt="Schermata 2024-07-09 alle 11 40 29" src="https://github.com/user-attachments/assets/20cf0a74-a806-47a6-928b-693c4ffdf459">

**Comment by yanniskadiri** [comment]
Could not reproduce in rc.7

**Comment by oiorain** [comment]
fixed
