### ISSUE TITLE
[Design] Multiple media input — chevron icons are tiny

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20763]
https://www.notion.so/strapi/Multiple-media-input-chevron-icons-are-tiny-85d0a6013cf44c719606d9a180fb3372?pvs=4

- we can barely see chevron icons
- icon buttons don’t have any margin
<img width="415" alt="CleanShot 2024-07-09 at 14 51 40@2x" src="https://github.com/user-attachments/assets/d9282dff-d143-4aa3-bb5a-51b0b569acc7">

**Comment by yanniskadiri** [comment]
I'm closing it then, thanks!
