### ISSUE TITLE
Subdocument property saved as undefined

### ISSUE THREAD

**Issue by Christilut** [strapi/strapi#2076]
Node 8.12.0
Latest strapi, just installed

**Informations**
- **Node.js version**: 8.12.0
- **npm version**:  5.x
- **Strapi version**: Latest, just installed
- **Database**: Mongo 3.6.8
- **Operating system**: Linux

**What is the current behavior?**
Trying out Strapi and it looks very promising for me but I noticed that after I saved an object that all subdocument properties were saved as `undefined`. I didn't define these properties in the Content Type so I assumed they would be saved as is (unchanged). Scalar properties that arent in the Content Type are saved unchanged.

After adding a subdocument property to the Content Type, it does get saved properly. Other subdocuments are still not saved.

Example document from mongodb to illustrate:
```js
{
    "_id" : ObjectId("5bb6577879fa633283eff5ed"),
    "status" : "ready",
    "createdAt" : ISODate("2018-10-04T18:10:00.867Z"),
    "updatedAt" : ISODate("2018-10-04T18:10:12.469Z"),
    "__v" : 0,
    "costSpecification" : "undefined", // This was a subdocument. Not specified in Content Type, it did have data before saving it
    "invoiceData" : { // Added in Content Type
        "subtotal" : 22,
    }
}
```

**Steps to reproduce the problem**
Add data to mongo with subdocument. Create content type, dont add all properties. Save an existing object through strapi.

**What is the expected behavior?**
Expect all properties to be saved even if they aren't in the content type.

**Comment by lauriejim** [comment]
Hello @Christilut!

Can you precise the exact version of Strapi you use please.
And can you precise how you create your entry. With POST route or via the Content Manger interface.
If you use the POST route, can you give me params you sent please.

**Comment by Christilut** [comment]
I created it through the Content Manager.
```json
    "strapi": "3.0.0-alpha.14.2",
    "strapi-hook-mongoose": "3.0.0-alpha.14.2"
```

**Comment by lauriejim** [comment]
Can you use lowerCase for your relation attribute name please.

**Comment by Christilut** [comment]
I'm not sure what you mean by relation attribute name. I don't have the attributes defined in Strapi which seems to cause this.

I've tried it some more now and what I'm seeing now is that all my subdocuments that are not defined in the Content Manager are replaced with an ObjectId as string, eg:
```json
{
  "costSpecification": {
      something: 123
  }
}
```
turns into:

```json
{
  "costSpecification": "5b9d3458b9ec1a5a654af467"
}
```

**Comment by lauriejim** [comment]
I mean use `costspecification` instead of `costSpecification `

**Comment by lauriejim** [comment]
It's define in your `Model.settings.json` file and also in the model you made the relation with.
