### ISSUE TITLE
[Design] The eye icon in the password inputs is sticked to the edge of the inputs

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20760]
https://www.notion.so/strapi/The-eye-icon-in-the-password-inputs-is-sticked-to-the-edge-of-the-inputs-b84a459446114f4c8d1dd89fc84a624a?pvs=4

![CleanShot 2024-07-04 at 16 49 14@2x](https://github.com/user-attachments/assets/a6a37f1c-209e-4535-b277-7c49c4ae6b38)

Also happening on number fields with arrows (I put it here because it’s probably the same bug):

![Screenshot 2024-07-09 at 10 39 21](https://github.com/user-attachments/assets/3948e5e7-60e1-4fb0-8ee4-1c9f075223ee)

**Comment by simotae14** [comment]
it is solved in the last version of v5
