### ISSUE TITLE
[Design] Missing bottom space on the Create user modal

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20765]
https://www.notion.so/strapi/Missing-bottom-space-on-the-Create-user-modal-9e7b11d5472e4e96b3e1da6d9bcde8d2?pvs=4

<img width="901" alt="Schermata 2024-07-09 alle 11 49 17" src="https://github.com/user-attachments/assets/bc2f9ed3-d758-4684-9a8f-47c4347bc784">

**Comment by alexandrebodin** [comment]
Fixed
