### ISSUE TITLE
[Design] Inconsistencies in clear crosses sizes

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20773]
https://www.notion.so/strapi/Inconsistencies-in-clear-crosses-sizes-4404bb214a444e64bfc73c5e36938a3f?pvs=4

![CleanShot 2024-07-04 at 17 01 38@2x](https://github.com/user-attachments/assets/0569b3db-3e3b-4bd4-92fa-7f42424c7b5e)

**Comment by yanniskadiri** [comment]
Confirmed in rc.7 but more of an improvement than a bug
