### ISSUE TITLE
[Design] The background of “Danger” rows in a popover should be red (Danger100)

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20777]
Current design

![CleanShot 2024-07-04 at 18 07 36@2x](https://github.com/user-attachments/assets/fca86723-8223-4cc6-b4cb-2b32d2b89d2b)

https://github.com/user-attachments/assets/801babab-b792-4de4-a31d-fee8892c6697

Expected design

![CleanShot 2024-08-29 at 11 19 16@2x](https://github.com/user-attachments/assets/0091af57-6e9c-456d-b772-fe3842d37382)

**Comment by simotae14** [comment]
I am gonna close the issue because it was fixed with this PR https://github.com/strapi/strapi/pull/21541#pullrequestreview-2432285483 thanks
