### ISSUE TITLE
[Design] Multiple issues in the DZ 

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20789]
https://www.notion.so/strapi/Multiple-issues-in-the-DZ-wrong-border-color-on-hover-small-icons-and-wrong-colors-when-hovering-t-4d7dcd96ce8542a4b8b5f5776d778dba?pvs=4

--> wrong border color on hover, small icons and wrong colors when hovering the button

https://github.com/user-attachments/assets/e9849f8a-6280-4e1e-98e4-37c2f498f643

**Comment by yanniskadiri** [comment]
Confirmed in rc.7
