### ISSUE TITLE
[Design] Not the right color for the check 

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20785]
https://www.notion.so/strapi/Not-the-right-color-for-the-check-I-guess-it-should-be-white-87d4ceb05e4b4b549bc2ea47dd5dd5c6?pvs=4

The user should see a white check next to the Save button or when selected a content type a workflow needs to be associated with
<img width="1510" alt="Capture d’écran 2024-07-09 à 10 19 30" src="https://github.com/user-attachments/assets/c30c4380-76e0-437a-bc94-8f89959fa131">

**Comment by oiorain** [comment]
Confirmed in rc.7

![Image](https://github.com/user-attachments/assets/9d8595a3-1098-4909-adef-b9dc32ba5a81)

**Comment by yanniskadiri** [comment]
Duplicate: https://github.com/strapi/strapi/issues/20817
