### ISSUE TITLE
[Design] There’s a border around the drag icon in Blocks (it should not)

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20781]
**Current design**
![CleanShot 2024-07-09 at 11 10 42@2x](https://github.com/user-attachments/assets/e391f4dc-0be8-4f08-b029-ba82dc19c5c7)

**Expected design**
![Image](https://github.com/user-attachments/assets/dcace0c3-e5b8-41c4-9b8f-a75340a45ad1)

**Comment by PapatMayuri** [comment]
@MarionLemaire Can you add some steps to check this issue.

**Comment by pandeyprafull** [comment]
@PapatMayuri Did you start working on it or should I pick this up ?
