### ISSUE TITLE
[Design] Missing space between the Content manager title and the search icon

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20786]
<img width="316" alt="Schermata 2024-07-09 alle 11 32 51" src="https://github.com/user-attachments/assets/451ce8b0-65a1-4514-b5da-1442154f168a">

**Comment by archanaagivale30** [comment]
@MarionLemaire is the issue still present because I am not able to reproduce it?

**Comment by lucasboilly** [comment]
@archanaagivale30 the issue has been fixed :)
