### ISSUE TITLE
[Design] Dynamic Zones disappear in the published tab

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20790]
https://www.notion.so/strapi/Dynamic-Zones-disappear-in-the-published-tab-603467d37ae34c6c9fbe8de365102a87?pvs=4

https://github.com/user-attachments/assets/f9b69701-151b-460f-8231-1d991a51938f

**Comment by yanniskadiri** [comment]
Could not reproduce in rc.7

**Comment by Feranchz** [comment]
Closing this after QAed, everything looks fine
