### ISSUE TITLE
[Design] Review Workflows : pointer is not the right one when clicking on a workflow or on [Create new workflow]

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20792]
https://www.notion.so/strapi/Review-Workflows-pointer-is-not-the-right-one-when-clicking-on-a-workflow-or-on-Create-new-workfl-b9a8e684b5a14c0eb35982c9a34ab576?pvs=4

**Comment by yanniskadiri** [comment]
Could not reproduce in rc.7 but there is a design issue with the "+" icon in "+ Create a new workflow" (see screenshot)

![Image](https://github.com/user-attachments/assets/41e98bdd-c02e-49c6-bdfb-ec18af43b8c4)

**Comment by yanniskadiri** [comment]
Discussed with @lucasboilly, we want the cursor when we hover on the entire row.

**Comment by yanniskadiri** [comment]
And we need to put a real icon there, not a "+" icon in a circle.

![image](https://github.com/user-attachments/assets/bfbca058-0555-442e-a20d-384ae23a3edb)

**Comment by yanniskadiri** [comment]
Here are the specs:
- 32px for the icon
- 8px of padding with the text

**Comment by sg1asgard** [comment]
@yanniskadiri  To replace the icon we need to update the design-system.
I have a meeting with @HichamELBSI on Monday to introduce me to the design-system and see if I can start doing some work in there / fixes.
