### ISSUE TITLE
[Design] Issue with the sticky header in the “Configure the view” page

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20795]
**Current design**
![Image](https://github.com/user-attachments/assets/caec0d63-80fb-4e0d-85dc-aef98ee4c294)

**Expected design**
![Image](https://github.com/user-attachments/assets/b0323f48-44ba-47f7-95fd-a2cd3e36c710)

**Comment by lucasboilly** [comment]
Fixed.
