### ISSUE TITLE
The contributing guide on Wiki page is wrong.

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#2080]
**What is the current behavior?**
The contributing guide link on Wiki page is wrong.
https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Suggested solutions**
Please change to https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment]
File to change for wiki is `_Footer.md` on the strapi.wiki
