### ISSUE TITLE
[Design] Small icons in Blocks

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20803]
https://www.notion.so/strapi/Small-icons-in-Blocks-43b9b5e537fb4039be3d3048eb2b960e?pvs=4

![CleanShot 2024-07-09 at 10 28 48@2x](https://github.com/user-attachments/assets/f88a31ca-78a4-4a16-bf9e-e96b22660726)

! It’s just about making the icons 16x16 instead of 12x12 in the text modifiers. I remember asking Rémi to make them 12x12 when it was developed because we still had the v4 icons and they were feeling too big. With the new ones, it will look perfect in 16x16

**Comment by oiorain** [comment]
Fixed
