### ISSUE TITLE
[Design] In the “Publish multiple locales” modal, the text style of the name is not the right one and there’s unexpected capital letters

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20808]
### Steps to reproduce
- Go to the edit view of an entry with at least 2 locales
- Click on the 3 dots next to the Publish button
- Click on "Publish multiple locales"
- See that the locale is written in capital letters and the second word starts with a capital letter

### Expected behavior

We should use small letters and not capital letters for the locale's name.
We should not use a capital letter for the second word in the status column.

### Screenshots

**Current design:**
![CleanShot 2024-07-05 at 11 21 06@2x](https://github.com/user-attachments/assets/6e98a1cd-4100-4217-a232-d678d4413411)

**Expected design:**
![Image](https://github.com/user-attachments/assets/18d45076-5289-4522-b0bd-4d8d1bb2127b)

**Figma file here:** https://www.figma.com/design/Tt8uHuQezEP0CsWunbulb5/Draft-%26-Publish?node-id=6865-43455&t=Bde7KX17urNDkv9p-0

**Comment by yanniskadiri** [comment]
Confirmed in rc.7
