### ISSUE TITLE
[Design] Issues in the role page (sticky header, border radiuses and centered texts)

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20819]
https://www.notion.so/strapi/Issues-in-the-role-page-sticky-header-border-radiuses-and-centered-texts-a027db8dac364fb09ae0724414ea995a?pvs=4

https://github.com/user-attachments/assets/90ba5620-6b2a-4d1c-b914-fe265572dbef

**Comment by yanniskadiri** [comment]
Partially confirmed in rc.7: issues with sticky headers and border radiuses, but not with centered text

**Comment by lucasboilly** [comment]
Fixed.
