### ISSUE TITLE
[Design] After clicking on Review Workflow, all icons are becoming black

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20817]
https://www.notion.so/strapi/After-clicking-on-Review-Workflow-all-icons-are-becoming-black-9b2725f727924ac3836b68cc1767e50d?pvs=4

https://github.com/user-attachments/assets/020790d5-6cf1-4c7a-a605-d54a3e2165e5

**Comment by yanniskadiri** [comment]
Confirmed in rc.7
