### ISSUE TITLE
This xxxxx,dev,users,permissions is already taken

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#2081]
**Informations**
- **Node.js version**:  v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14.1
- **Database**: mongodb
- **Operating system**: macOS

**What is the current behavior?**

I added another register API in `/plugins/users-permissions/controllers/Auth.js`. When calling this API to register, it catches following error message:

```
{
 message: 'This xxxxx123,dev,users,permissions is already taken',
 field: [ 'xxxxx123', 'dev', 'users', 'permissions' ] 
}
```

- The error is catched on this line: 
`const user = await strapi.query('user', 'users-permissions').create(params);`
- My database name is: `xxxxx123-dev`

Then I went back to use original register API: `/auth/local/register`. It catches the same error on the same line.

It may related to #1608.

**Steps to reproduce the problem**
I'll add later.

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@yummyelin per the Issue template please ensure you submit all issues after testing on the latest release.

You are currently one release behind: `Strapi version: 3.0.0-alpha.14.1` Current version is `Strapi version: 3.0.0-alpha.14.2`

**Comment by derrickmehaffy** [comment]
```
<!-- ⚠️ If you do not respect this template your issue will be closed. -->

<!-- =============================================================================== -->
<!-- ⚠️ If you are not using the current Strapi release, you will be asked to update. -->
<!-- Please see the wiki for guides on upgrading to the latest release. -->
<!-- =============================================================================== -->
```

**Comment by YannMLD** [comment]
f

**Comment by YannMLD** [comment]
The solution which worked for me was to delete my model in Strapi CMS, delete data in my database (don't know if you have to), and recreate my model (with exactly the same name) in the Strapi CMS.
Still don't know why I had this problem but I think it cames when i edited my model attributes

**Comment by yummyelin** [comment]
Hey, for those who have the same issue, just search `is already taken` in your project. 
Look for the sentence `This ${field} is already taken`, it usually appears in two files:

```
strapi-app/plugins/content-manager/config/queries/bookshelf.js
strapi-app/plugins/content-manager/config/queries/mongoose.js
```

If you believe your error occurred in **Content Manager**, then open these two.
If you believe is **User Permissions**, then replace `content-manager` with `users-permissions`, for example: 
```
strapi-app/plugins/users-permissions/config/queries/bookshelf.js
```

Then console.log the error from try catch, you will know what is the real cause.
