### ISSUE TITLE
[Design] Bulk Publish modal is inside of another modal

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20811]
https://www.notion.so/strapi/Bulk-Publish-modal-is-inside-of-another-modal-e5b8dd0dd30846f78ec90585872891bb?pvs=4

![CleanShot 2024-07-05 at 11 07 04@2x](https://github.com/user-attachments/assets/a146de23-79a8-4f52-88dc-914b173c3417)

**Comment by yanniskadiri** [comment]
Could not reproduce in rc.7

**Comment by madhurisandbhor** [comment]
not reproducible
