### ISSUE TITLE
[Design] The colors of the “Draft” status are not the right ones

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20814]
**Current design**
![CleanShot 2024-07-05 at 10 19 33@2x](https://github.com/user-attachments/assets/99fd5275-51b8-481c-aa78-4d0f7e041393)

Expected design:
![Image](https://github.com/user-attachments/assets/49b4cafb-8ec0-4cc2-b94b-833ba230c160)

Figma file: https://www.figma.com/design/NmL2GP7zw2bS4G5CW1xVqm/%5BEXPERIMENTAL%5D-Strapi-CMS---UI-Kit?node-id=16977-54024&node-type=frame&t=rZ6qBKlOastilo3g-0

**Comment by pandeyprafull** [comment]
As per the Contrubition guidelines I forked the repo from `develep` branch and checked throughout the codebase , 
the button seems to be looking as expected and the issue were reproducing with `"@strapi/strapi": "5.0.0-rc.4",` @derrickmehaffy what should I do to make PR of the fix ? ..
