### ISSUE TITLE
[Design] In the locale popover, the status should appear after the locale name

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20813]
### Steps to reproduce
- Go to a given entry with D&P enabled
- Click on the locale dropdown
- See that the status is given before the locale

### Expected behavior

The status should appear after the locale (see screenshots)

### Screenshots

**Current design:**
![CleanShot 2024-07-05 at 10 19 01@2x](https://github.com/user-attachments/assets/fff5ba58-096b-4cb5-a323-af9f49a13da1)

**Expected design:**
![Image](https://github.com/user-attachments/assets/645104b0-7312-446b-8fce-615974efa185)

**Comment by yanniskadiri** [comment]
Confirmed in rc.7

**Comment by archanaagivale30** [comment]
@yanniskadiri  is this issue fixed ?

**Comment by yanniskadiri** [comment]
Yes it's been fixed, thank you for checking. I'll close this issue.
