### ISSUE TITLE
[Design] In the edit view, the labels of “Delete locale” and “Delete document” are not the right ones

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20812]
### Steps to reproduce
- Go to the edit view of an entry with at least 2 locales
- Click on the 3 dots
- See that you can delete locale or delete document

### Expected behavior

We should say "Delete entry ([Name of the locale])" and "Delete entry (all locales)"

### Screenshots

**Current wording:**
![CleanShot 2024-07-05 at 10 22 24@2x](https://github.com/user-attachments/assets/d9838c7f-b617-4ed3-9fc4-786b3852954e)

**Expected wording:**
![Image](https://github.com/user-attachments/assets/fe4a2733-6a38-4491-bd18-85bfc0970d9c)

**Comment by yanniskadiri** [comment]
Confirmed in rc.7

**Comment by yanniskadiri** [comment]
Yes, thank you for having a look. I'll close this issue.
