### ISSUE TITLE
[Design] The role page has a back button but it shouldn’t

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20818]
### Steps to reproduce
- Go to U&P plugin > Roles
- See the Back button

### Expected behavior

There should not be a back button on this page

### Screenshots

![CleanShot 2024-07-04 at 17 54 04@2x](https://github.com/user-attachments/assets/57390b2b-b40d-4d3f-aba9-aacd15b330fd)

**Comment by yanniskadiri** [comment]
Could not reproduce in rc.7
