### ISSUE TITLE
[Design] A cloud is cutted in half in Cloud’s plugin

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20824]
https://www.notion.so/strapi/A-cloud-is-cutted-in-half-in-Cloud-s-plugin-07fd9726bd664a768947f8c85c547a60?pvs=4

![CleanShot 2024-07-04 at 17 32 53@2x](https://github.com/user-attachments/assets/03680e52-e736-4318-bef7-8e429a9242e8)

**Comment by simotae14** [comment]
fixed with the https://github.com/strapi/strapi/pull/20862 PR
