### ISSUE TITLE
[Design] Search bars are visually broken

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20823]
https://www.notion.so/strapi/Search-bars-are-visually-broken-4659d78195804dd38e7abe423d33ab3a?pvs=4

![CleanShot 2024-07-04 at 17 34 29@2x](https://github.com/user-attachments/assets/f944c976-fdd0-4cb4-bfde-47ba5a9ae868)

![CleanShot 2024-07-04 at 17 34 57@2x](https://github.com/user-attachments/assets/dd48e473-525a-4b5a-b96d-fbda3eddea3c)

![CleanShot 2024-07-04 at 17 35 07@2x (1)](https://github.com/user-attachments/assets/e807ee3e-57df-4dd4-861a-98d7fef5a8be)

**Comment by yanniskadiri** [comment]
Confirmed in rc.7
