### ISSUE TITLE
Wrong date in datetime field after timezone offset

### ISSUE THREAD

**Issue by abaksha-sc** [strapi/strapi#20826]
- Strapi version: 4.11.5
- Operating system: Windows 10
- Browser: Chrome 126.0.6478.127

### Describe the bug

My timezone is UTC +2 hours and datetime like "2024-07-16T22:37:02.414Z" I see as date "2024-07-**16**" and time "00:37".
It seems like only time part offsets to my timezone, but not date. I should see next date "2024-07-**17**"

![image](https://github.com/user-attachments/assets/c4212672-d705-4f50-879f-34fc0c02c4a9)

### Steps to reproduce the behavior

0. Change your timezone to UTC + 2 hours
1. Create any type with datetime field
2. Fill it with datetime where UTC time is the end of day (like "2024-07-16T23:59:59.000Z")
I can't do it manually due to another bug (see at the end of this issue)
4. Open the record
5. See that date field is "2024-07-16" but time field is "01:59"

### Expected behavior

For datetime "2024-07-16T22:37:02.414Z" it's necessary to show date "2024-07-**17**" and time "00:37"

### Additional context

One more problem is that I can't manually choose necessary date when time "00:15" is chosen. It moves date to previous on each focus and blur event:

![datetime-bug](https://github.com/user-attachments/assets/cebb0266-d90d-4a58-b780-ff15f1724a7e)

**Comment by derrickmehaffy** [comment]
You are on a really old version, we have made several improvements to this since 4.11.5
