### ISSUE TITLE
When adding a new locale, then if we go to an existing published entry and we try to translate it into the freshly new added locale, we got 3 errors notification, but it seems to work.

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20836]
https://www.notion.so/strapi/When-adding-a-new-locale-then-if-we-go-to-an-existing-published-entry-and-we-try-to-translate-it-in-1e91b30cb0b64462a861072314a2216a?pvs=4

**Comment by yanniskadiri** [comment]
Confirmed in rc.7

**Comment by Feranchz** [comment]
Fixed at rc.15
