### ISSUE TITLE
On the edit view, when switching to a different locale I get an error

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20839]
https://www.notion.so/strapi/On-the-edit-view-when-switching-to-a-different-locale-I-get-an-error-0425a19aba6647ba9483d9f6964c0874?pvs=4

**Comment by yanniskadiri** [comment]
Confirmed in rc.7, maybe a duplicate of this issue: https://github.com/strapi/strapi/issues/20836

**Comment by Marc-Roig** [comment]
indeed is a dup of https://github.com/strapi/strapi/issues/20836, will close this in favor of the former
