### ISSUE TITLE
When I switch to a new locale in the CTM, but the default one is published, it doesn’t appear as published in the sub-menu

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20835]
https://www.notion.so/strapi/When-I-switch-to-a-new-locale-in-the-CTM-but-the-default-one-is-published-it-doesn-t-appear-as-pub-ffbeb4e9bef445cda5d860f8e301359a?pvs=4

**Comment by yanniskadiri** [comment]
Confirmed in rc.7

**Comment by remidej** [comment]
Unable to reproduce in rc.20
