### ISSUE TITLE
Single type name not applied in the content manager

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20844]
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: 5.0.0-rc-2
- Database: sqlite
- Operating system: mac
- Is your project Javascript or Typescript: javascript

### Describe the bug

Single types in the content manager have “Untitled” as title

### Steps to reproduce the behavior

1. create a single type
2. switch to the content manager

notice the title of the single type, it’s “Untitled’

### Expected behavior

The title of the single type should be the single type name

### Screenshots

![Image](https://github.com/user-attachments/assets/49b7907d-9828-4138-8428-2585e7269db4)

**Comment by davemo** [comment]
I'm still encountering this bug in strapi `5.1.0`

**Comment by StrapiBartosh** [comment]
Double checked in Strapi 5.1.1, it is still present and visible on the "global" single-type in the Launchpad application.
