### ISSUE TITLE
Option to exclude relations by default?

### ISSUE THREAD

**Issue by Mat-thieu** [strapi/strapi#2084]
Is there an option to exclude relations by default and only include them using some query parameter?

If not I'll open a feature request for it (couldn't find it).

Awesome cms guys, really looking forward to its completion :)

**Comment by derrickmehaffy** [comment]
@Mat-thieu if you mean in the restAPI not currently no, for grabbing data you may want to look at graphQL as you can define custom queries (including going more than 1 level deep on relations)

**Comment by Mat-thieu** [comment]
@derrickmehaffy Alright, thanks, might look some more into graphQL. Nonetheless I still think it'd be a nice feature for the REST api, you wouldn't want all relations all the time.

Perhaps a more general approach would be better? An option on every model property to exclude it by default, and an additional filter to add properties that are excluded by default?

Or perhaps relations shouldn't be included by default unless specified, which is the way I usually see it happen.

What do you think?

**Comment by derrickmehaffy** [comment]
I agree that the relation depth should be optional as a filter (default of 1 is fine, max would probably be 3? After that especially if you having looping relations you could cause some serious issues)

something like `_depth` with the default being applied `_depth=1` and allowing the option of `_depth=0`

**Comment by Mat-thieu** [comment]
@derrickmehaffy Or perhaps more targeted, so when there's multiple depth 1 relations you can pick which one you need.

Something like this
`?include=products`

Or when you need to get deeper into nested relations
`?include=products.reviews`

This is also stated in the [JSON API spec](http://jsonapi.org/format/#fetching-includes) and I think it's a very clear way of going about it.

**Comment by Mat-thieu** [comment]
@derrickmehaffy Gonna close this now, thanks for your responses, I made a feature request https://github.com/strapi/strapi/issues/2086
