### ISSUE TITLE
[Strapi v5 RC] Assets Cannot be Moved to Folders

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20853]
### Required System information

- **Node.js version**: 18.17.0
- **NPM version**: yarn/1.22.19
- **Strapi version**: 5.0.0-rc.2
- **Database**: sqlite
- **Operating system**: darwin-arm64
- **Is your project Javascript or Typescript**: Typescript

### Describe the bug

Assets cannot be moved to folders. When attempting to move an asset, the destination folder options are not displayed correctly.

### Steps to reproduce the behavior

1. Open the Media Library.
2. Select an asset to move.
3. Click on the "Move" button.
4. Observe that the destination folder options are not correctly displayed.

### Expected behavior

The destination folder options should be displayed correctly, allowing for the asset to be moved to the selected folder.

### Screenshots

<img width="1557" alt="Screenshot 2024-07-19 at 16 25 33" src="https://github.com/user-attachments/assets/0d595656-18f8-42e8-9618-3a0c954af6f0">

### Code snippets

N/A

### Additional context

N/A

**Comment by derrickmehaffy** [comment]
unable to reproduce on rc.6
