### ISSUE TITLE
[Strapi v5] Documentation plugin is not compatible

### ISSUE THREAD

**Issue by heitara** [strapi/strapi#20859]
### Required System information

- Node.js version: 18.16
- NPM version: 9.5.1
- Strapi version: strapi@"5.0.0-beta.10
- Database: mysql
- Operating system: macOS Sonoma 14.5
- Is your project Javascript or Typescript: Typescript

Environment: production
OS: darwin-x64
Strapi Version: 5.0.0-beta.10
Node/Yarn Version: npm/9.5.1 node/v18.16.0 darwin x64 workspaces/false
Edition: Community
Database: mysql

### Describe the bug

Unable to use Documentation plugin with Strapi V5

### Steps to reproduce the behavior

1. Setup a Strapi v5 instance. 
2. Try to install the Documentation plugin from Terminal with the following command:
```
npm i @strapi/plugin-documentation
```

### Expected behavior

To be able to use the core plugins when testing Strapi RC.

### Additional context

As a developer, who wants to support an OpenSource product (using it internally, evaluating it and helping with fixes) it's really important to keep the core plugins in sync (compatible), before announcing a RC that can be used. 
If there is any real reason that is preventing any of the plugins to work with the new release, please add that to the documentation so every developer can decided whether to proceed with the new version upfront or to stick to the old one. I believe there are different people who can keep using the v4 and who will move to v5 earlier.

**Comment by SebastianGode** [comment]
Please use `@strapi/plugin-documentation@rc` to install the release candidate branch and that will work.
The non-rc branch isn't compatible with an rc branch of strapi. Makes sense, right?

**Comment by derrickmehaffy** [comment]
unable to reproduce on rc.6
