### ISSUE TITLE
Small icons in Settings > U&P Plugin > Email templates

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#20869]
Not sure if it's a visual bug or if it's intended, but icons for "Reset password" and "Email address confirmation" look pretty small to me 🤔

![Image](https://github.com/strapi/strapi/assets/4233866/ad71f680-6b8a-4f34-b52f-f4159241075a)

**Comment by harshit078** [comment]
<img width="1352" alt="Screenshot 2024-07-25 at 1 34 44 AM" src="https://github.com/user-attachments/assets/212ab59c-5e1a-4b47-bb74-a409e914d3c5">

Hey @derrickmehaffy, It seems normal on the local dev for me. Could you share some more info on it ?

**Comment by lucasboilly** [comment]
Fixed.
