### ISSUE TITLE
Custom hook isn't loading

### ISSUE THREAD

**Issue by FaustTheThird** [strapi/strapi#2087]
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.14 
- **Database**: postgresql
- **Operating system**: Linux

**What is the current behavior?**

I just created a custom hook but strapi don't wants to load it. It says:
warn (hook:custom-hook) wasn't loaded due to missing key `enabled` in the configuration. I tried to write 'enabled' in many places but that didn't helped. Still getting this message.

**Steps to reproduce the problem**

Created a custom hook in  the _project/hooks/_ and added index.js into that folder

**Comment by lauriejim** [comment]
Hello @FaustTheThird !

Did you follow this structure https://strapi.io/documentation/advanced/hooks.html#custom-hooks ?

**Comment by lauriejim** [comment]
Sorry for the delay.

Follow the same instructions as the activation of the `strap-hook-ejs` ([link](https://github.com/strapi/strapi/tree/master/packages/strapi-hook-ejs))

I had updated the readme but forgot to update the documentation. 
I will update it soon as possible.

**Comment by FaustTheThird** [comment]
@lauriejim 

Thanks, I just figured it out right now by myself. Anyway thank you for your help :)

**Comment by wsalazar-peakactivity** [comment]
Are you going to bother to share @FaustTheThird ?

**Comment by TheBoroer** [comment]
@wsalazar-peakactivity @lauriejim 

I struggled with this today too ..... the issue was a typo in the `strap-hook-ejs` readme.
It says `hooks.json` when it should be `hook.json`. I tried so many different combinations and even made a new file called hooks.json trying to figure out how to turn the hook on lol.

For anyone running into the same or a similar issue or is confused on how to enable custom hooks: 
here is what my `hook.json` looks like for my custom pug hook:
```
{
  "timeout": 3000,
  "load": {
    "before": [],
    "order": [
      "Define the hooks' load order by putting their names in this array in the right order"
    ],
    "after": []
  },
  "strapi-hook-pug": {
    "enabled": true
  }
}
```

**Comment by micahbule** [comment]
Similar to @TheBoroer, if anyone is having problems enabling hooks on the current version of Strapi, just rename `./config/hooks.js` to `./config/hook.js`. Singular, not plural.

**Comment by fredycampino** [comment]
I have the same problem in the 3.1.0 (node v12.18.3),  i follow the same intructions as:  [hooks](https://strapi.io/documentation/3.0.0-beta.x/concepts/hooks.html#structure) but it is no  loading the hooks 

i have both custom and strap-hook-ejs hoosk, here the json

```
{

  "timeout": 3000,
  "load": {
    "before": [],
    "order": [
      "strapi-hook-ejs","strapi-render"
    ],
    "after": []
  },
  
  "strapi-hook-ejs": {
    "enabled": true,
    "layout": "layout",
    "viewExt": "ejs",
    "partial": true,
    "cache": false,
    "debug": true
  },

  "strapi-render": {
    "enabled": true
  }
}
```

**Comment by alexandrebodin** [comment]
Hello, you ar enot following the right documentation. Please read the current version doc: https://strapi.io/documentation/v3.x/concepts/hooks.html#structure

**Comment by fredycampino** [comment]
Thank it works, the json activation is not use any more, it need a hook.js

**Comment by sauldeleon** [comment]
I think this is not working for v4. I have created the files acording to documentation and yet the hook is not being initialized.

Do we need to migrate the hooks to plugins in order to get this to work? what have changed?

thanks in advance!
