### ISSUE TITLE
When trying to save a Date field with the default value it returns a error

### ISSUE THREAD

**Issue by EP-KHoeper** [strapi/strapi#20875]
### Required System information
- Node.js version: v20.5.0
- NPM version: 9.8.0
- Strapi version: 5.0.0-rc.6
- Database: sqlite
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

Create a new Date field (type time) with a Default value.
Try to save without setting the time value.

[Screencast from 24.07.2024 16:09:46.webm](https://github.com/user-attachments/assets/e6a9d74a-6f6e-4ce6-ab1a-9e8b9ff2f56e)

### Expected behavior

When saving the date should be saved with its default value. 

### Screenshots

![image](https://github.com/user-attachments/assets/ae87d7e1-182a-474e-a4ac-e203f9dce681)

**Comment by ymohit1603** [comment]
Assign me this issue i can fix this.

**Comment by punitive1729** [comment]
@derrickmehaffy i have raised a PR for this issue to merge into v5/main since develop branch is still on v4 i hope its fine let me know if for v5 you are maintaining a separate base branch

**Comment by butcherZ** [comment]
Hey there, this issue has been fixed, and @punitive1729 thank you for your contribution :)
