### ISSUE TITLE
Strapi 5 uses deprecated NodeJS modules

### ISSUE THREAD

**Issue by planv** [strapi/strapi#20885]
## Bug report

It uses a lot of deprecated NodeJS Modules

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/a15df5fc-0e67-44ea-adbe-38db22358c89">

Also one of them

### inflight@1.0.6: **This module is not supported, and leaks memory. Do not use it.**

It is a dependency of `yalc` module 
https://github.com/strapi/strapi/blob/533533434d099f3c083ef83c8f7e1f7a5cd5ac60/package.json#L153

**btw, Strapi version 4 does not use this module.**

### Required System information

- Node.js version: v20
- NPM version: v10
- Strapi version: 5.0.0-rc.7

**Comment by ananta6d595** [comment]
Same but with v4
![Screenshot from 2024-07-28 22-22-08](https://github.com/user-attachments/assets/bd2f54c6-ea1d-4d3c-8437-8f72e9821377)

**Comment by ananta6d595** [comment]
Same issue with v4 also. Showing some vulnerabilities. 
![Screenshot from 2024-07-28 22-26-40](https://github.com/user-attachments/assets/ef060b39-e0ad-43ac-bf6e-619af6f27688)

**Comment by derrickmehaffy** [comment]
We upgrade dependencies as needed not just because there are deprecation warnings. Likewise with vulnerabilities, we test if those actually apply to us and aren't just pointless ones (like DDoS vulns in build libraries.

Closing this as it isn't a bug but subjective opinion.

**Comment by jordiyapz** [comment]
So memory leaks is just a pointless one?
