### ISSUE TITLE
Installed plugins missing from production deployment

### ISSUE THREAD

**Issue by deevolutionism** [strapi/strapi#2088]
**Informations**
- **Node.js version**: 10.7
- **npm version**: 6.1
- **Strapi version**: v3.0.0-alpha.14.1
- **Database**: Mongo
- **Operating system**: OSX, Heroku 

**What is the current behavior?**
Running Strapi locally vs deployed on Heroku results in different admin panels. 

For me, the **local** version shows the following plugins in the admin panel: 
- Content Manager
- Content Type Builder
- Roles and Permissions

The **deployed** version show the following plugins in the admin panel
- Content Manager
- Roles and Permissions

Plugins page tells me that content type builder is installed, but when I go to admin/plugins/content-type-builder I get a 404.

**Steps to reproduce the problem**
1. create mlab database and user - note username, password, db name, port, uri, and host
2. create a new strapi project, select mongo as the db and enter mongo creds. *note* when it asks for authentication_database, provide the db name.
3. install each plugin via CLI `strapi install <plugin-name>`.
4. create a new heroku project
5. edit strapi environment database config files to hook up the database
6. run `heroku local`, navigate to strapi. Notice the number of plugins that appear in the side panel.
7. For production deployment on heroku, set heroku environment variables for mongo via GUI or CLI: 
--`heroku config:set VARIABLE_NAME=value`
-- set env vars for: DATABASE_AUTHENTICATION_DATABASE, DATABASE_HOST, DATABASE_NAME, DATABASE_PASSWORD, DATABASE_PORT, DATABASE_URI, DATABASE_USERNAME
8. deploy app to heroku, notice that the number of plugins that appear in the side panel does not match the local deployment of Strapi.

**What is the expected behavior?**
The plugins that were installed should appear in both development and production deployments.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@deevolutionism Content-Type builder cannot be used in production (even if you load up development on Heroku it can't be used either)

That plugin writes files directly to the local storage which Heroku doesn't support.

Please see closed issues related to Heroku.

**Comment by derrickmehaffy** [comment]
FYI that plugin is disabled on both Production and Staging no matter where it is ran (you shouldn't be modifying the models in production *shakes finger*)

**Comment by derrickmehaffy** [comment]
@lauriejim 

Duplicate: https://github.com/strapi/strapi/issues/2072

Recommend closing

**Comment by deevolutionism** [comment]
Out of curiosity... What exactly does it write to local storage and why has it been designed this way?

**Comment by derrickmehaffy** [comment]
It writes the model definitions (the fields you add) and the hooks use these to build the database (hence you can't store them in the database if there is no database to start with lol)

With nodeJS when a new file is written it has to restart to use it, thus strapi auto restarts on a file change.

In the case of production, if something goes wrong your production strapi can be taken offline if it falls to start and Heroku cannot store new files (limit by them not strapi)

**Comment by derrickmehaffy** [comment]
Realistically you should be running 3 servers of strapi.

Your production for live use
Staging for testing (public or not) and should mirror production as much as possible
And development which is usually locally on your machine

That is just standard practice for building, testing, and deploying almost anything on the web :p
