### ISSUE TITLE
Can't Save content types containing JSON fields in the admin.  This doesn't match the JSON format

### ISSUE THREAD

**Issue by gfritzdev** [strapi/strapi#20882]
### Required System information

- Node.js version: v20.14.0
- NPM version: 10.8.1
- Strapi version: 5.0.0-rc.7
- Database: MySql v 8
- Operating system: OSX
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After upgrading to `@strapi/strapi` version `5.0.0-rc.7`, I encountered an issue where I can no longer save content types that have JSON fields in the admin panel. The error message displayed is "This doesn't match the JSON format." However, sending the same JSON via a POST request works without any errors.

### Steps to reproduce the behavior

1. Upgrade to `@strapi/strapi` version `5.0.0-rc.7`.
2. Open the admin panel.
3. Navigate to a content type that has a JSON field.
4. Attempt to save the content type.
5. Observe the error message "This doesn't match the JSON format."

### Expected behavior

I expected to be able to save content types with JSON fields in the admin panel without encountering any errors.

### Screenshots
![Screenshot 2024-07-25 at 1 47 46 PM](https://github.com/user-attachments/assets/35bd79b6-502a-42d6-a3ba-2db964042d30)

https://github.com/user-attachments/assets/ad10e870-05db-4611-bb30-b518ff950cca

### Code snippets
Value i'm trying to save:
{"type": "doc", "content": [{"type": "paragraph", "content": [{"text": "Lets see if this works", "type": "text"}]}]}

**Comment by derrickmehaffy** [comment]
I was testing this out with the user in Discord during office hours and I could kinda reproduce it but he was going to record a video and add it

**Comment by gfritzdev** [comment]
Added a video showing that I can save the JSON via post request,  but then if i try to save the same value in the admin it throws an error.

**Comment by gfritzdev** [comment]
Here's one more video for debugging purposes.  I've noticed that if I copy the value from my mysql database and paste it into the json field it allows me to save.  But if i make a change then try to save again it throws the error on the field that I didn't modify?  Very odd,  not seeing any console errors either. 

https://github.com/user-attachments/assets/355e976e-df03-49c7-9ccf-ac3c13423cb1

**Comment by remidej** [comment]
Thanks for the report, the fix will land in the next RC on Wednesday
