### ISSUE TITLE
There is issue Occurs at the time of the creation of the new component via the strapi admin/server

### ISSUE THREAD

**Issue by rahulkamble2026rk** [strapi/strapi#20891]
### Link to the documentation page or resource

there is no link

### Describe the bug

[2024-07-29 03:29:01.209] http: POST /content-type-builder/components (139 ms) 201
[2024-07-29 03:29:01.214] info: Shutting down Strapi
[2024-07-29 03:29:01.221] info: Strapi has been shut down
⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (83ms)
✔ Creating admin (463ms)
⠧ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                              │
│   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                                                           │
│       at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)                                                                                │
│       at new NodeError (node:internal/errors:405:5)                                                                                                          │
│       at validateString (node:internal/validators:162:11)                                                                                                    │
│       at Object.join (node:path:433:7)                                                                                                                       │
│       at C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\loaders\components.js:17:31                                   │
│       at Array.forEach (<anonymous>)                                                                                                                         │
│       at C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\loaders\components.js:14:32                                   │
│       at Array.reduce (<anonymous>)                                                                                                                          │
│       at loadComponents (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\loaders\components.js:13:39)                  │
│       at async Promise.all (index 5)                                                                                                                         │
│       at async Module.loadApplicationContext (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\loaders\index.js:12:3)   │
│       at async Object.register (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\providers\registries.js:26:5)          │
│       at async Strapi.register (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\Strapi.js:322:7)                       │
│       at async Strapi.load (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\core\dist\Strapi.js:314:5)                           │
│       at async Module.develop (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\strapi\dist\node\develop.js:177:28)               │
│       at async action (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\strapi\dist\cli\commands\develop.js:18:5)                 │
│       at async Command.parseAsync (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\commander\lib\command.js:923:5)                       │
│       at async runCLI (C:\Users\rohit\OneDrive\Intern Project\ai-resume-admin\node_modules\@strapi\strapi\dist\cli\index.js:75:3)                            │
│                                                                                                                                                              │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

### Additional context

Sir this is generating same error , I am trying to solve this one but this is not solved yet ! please help me to solve this one ! when I am trying to create  the new component and click on the save button this issues occur ! there is no any reference that how to solve this issue ! to solve this one , Every time I install whole setup but it still gives the same error ! please help me to solve this issue !

**Comment by pwizla** [comment]
Hello @rahulkamble2026rk, I'm transferring the issue to the `strapi/strapi` repo as this seems to be a product issue, not an issue with the Strapi documentation itself.

**Comment by rahulkamble2026rk** [comment]
Ok, Please solve that issue as soon as possible !

**Comment by rahulkamble2026rk** [comment]
Sir I am college student currently my exam's are going on and after that
there is final project submission ! I don't have the enough time to make
this template , this is my humble request that please open my issue , if
any extra information is needed then I will give the reply , so please look
into this matter!
