### ISSUE TITLE
Impossible to use URL to add a new asset (media library)

### ISSUE THREAD

**Issue by nathan-pichon** [strapi/strapi#20899]
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-rc.3
- Node/Yarn Version: yarn/1.22.19 npm/? node/v20.15.0 darwin arm64
- Edition: Community
- Database: sqlite
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The URL input "FROM URL" on the modal to add a new asset cannot be changed (not possible to write in it or copy/paste)

### Steps to reproduce the behavior

1. Go to Media Library
2. Click on Add new assets
3. Click on FROM URL
3. Try to input text in the URL field

### Expected behavior

I should be able to write or paste my urls in this input.

### Screenshots

![image](https://github.com/user-attachments/assets/510a1600-5c35-46c6-a8e4-6786984c4b0d)

**Comment by alexandrebodin** [comment]
cc @oiorain
