### ISSUE TITLE
Implicitly updating component fields on a record fails silently

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#20898]
### Required System information

Environment: development
OS: darwin-x64
Strapi Version: 4.11.4
Node/Yarn Version: npm/9.6.7 node/v18.17.1 darwin x64 workspaces/false
Edition: Community
Database: postgres
Is your project Javascript or Typescript: TS

### Describe the bug

When updating a record and providing data for populated fields, the update operation fails silently.

### Steps to reproduce the behavior

1. Have a user record like this: 
```
let original = 
{
  id: 74,
  username: 'su-tech',
  email: 'something@somethingsomething.com',
  provider: 'local',
  confirmed: true,
  blocked: false,
  createdAt: '2024-07-29T08:44:45.503Z',
  updatedAt: '2024-07-29T12:53:27.778Z',
  matricule: null,
  notes: 'technical admin account',
  validuntil: '2038-06-30T22:00:00.000Z',
  phone: null,
  markedForDeletion: false,
  firstName: 'N',
  lastName: 'N',
  birthDate: null,
  address: null,
  mobile: null,
  version: '0',
  hide_from_children: true,
  twoFA: { id: 151, twoFAmethod: 'email' }
}
```

where  twoFA is a component, consisting only of an enum called `twoFAmethod`.

2. Have a cloned JSON object of this record and alter one or more properties, e.g. `firstName`, omit `id` of course, but leave the populated field `twoFA` :

``` 
let alteredClone = {
username: 'su-tech',
  email: 'something@something.com',
  provider: 'local',
  confirmed: true,
  blocked: false,
  createdAt: '2024-07-29T08:44:45.503Z',
  updatedAt: '2024-07-29T12:53:27.778Z',
  matricule: null,
  notes: 'technical admin account',
  validuntil: '2038-06-30T22:00:00.000Z',
  phone: null,
  markedForDeletion: false,
  firstName: 'Foo',
  lastName: 'Bar',
  birthDate: null,
  address: null,
  mobile: null,
  version: '0',
  hide_from_children: true,
  twoFA: { id: 151, twoFAmethod: 'email' }
  }
```

3. Update the first record with the clone: 
```
let updatedAdminRecord = await strapi.entityService.update('plugin::users-permissions.user', original.id , { 
                    data: clone})
```

At this point, the execution of everything beyond this code is interrupted and a `500` server error is returned in the request, but there is no error thrown in the console itself. If you wrap this into a try-catch clause, you never land inside the catch clause and it seems like the operation was successful, although it wasn't performed.

### Expected behavior

An error is thrown, signaling I did something I should have done in a different way.

Feel free to close if this is fixed in a more recent version, of course.

**Comment by nikita-fuchs** [comment]
I was able to narrow it down a bit: the `id` on the nested data is what is causing this issue. If you change the updating data  to

 ```
...
  twoFA: { twoFAmethod: 'email' }
  }
```

  this issue doesn't appear.

**Comment by derrickmehaffy** [comment]
Unable to reproduce on latest version of v4, advise upgrading to a newer version as 4.11.x is quite old now.
