### ISSUE TITLE
Connection identifier changes, through studio, lead to "strapi start" failure.

### ISSUE THREAD

**Issue by GHNewbiee** [strapi/strapi#209]
**Node.js version**: 7.9.0
**npm version**: 4.2.0
**Strapi version**: 1.6.2
**Operating system**: Mint Linux

I tried to change, through studio, "default" and "permanent" connection identifiers to "default-disk" and "permanent-disk" and strapi refused to start.

_PS: I am not an IT folk!_ So, don't start shooting me!

**Comment by Aurelsicoko** [comment]
@GHNewbiee What are the logs in your terminal?

**Comment by GHNewbiee** [comment]
Sorry, I do not remember! What I did was to search all project files for "default" and "permanent" words. I found 1-2 remaining of each one. I renamed them manually to "default-disk" and "permanent-disk" and started the server. That was OK, then.
Imho, I believe that the rename procedure failed to make all appropriate changes or "-disk" pattern created an unexpected side effect.

**Comment by Aurelsicoko** [comment]
Thanks for the feedback!
