### ISSUE TITLE
Can't pull V5/Main on windows since NTFS does not allow :id as a file name 

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#20907]
### Required System information

- Node.js version:  N/A
- NPM version: N/A
- Strapi version: V5
- Database: N/A
- Operating system: Windows
- Is your project Javascript or Typescript: N/A

### Describe the bug

When ever I try to pull v5/main I get the following error  `error: unable to create file packages/core/review-workflows/admin/src/routes/settings/:id.tsx: Invalid argument`
Since NTFS does not allow files to start with `:` 
### Steps to reproduce the behavior

1. Try to pull v5/main on windows
4. See error `error: unable to create file packages/core/review-workflows/admin/src/routes/settings/:id.tsx: Invalid argument`

### Expected behavior

For it to pull v5/main sucessfuly on windows

**Comment by derrickmehaffy** [comment]
I was able to reproduce this on Windows 11:

![Image](https://github.com/user-attachments/assets/761af48b-8a16-43f6-a79b-22c9c32234f6)
