### ISSUE TITLE
Error on build : @strapi/typescript-utils@5.0.0-rc.3 fixed

### ISSUE THREAD

**Issue by tombombadilom** [strapi/strapi#20904]
### Required System information

- Node.js version: 20
- NPM version: 10.7.0
- Strapi version: 5.0.0-rc.3
- Database: PostgreSQL
- Operating system: Archlinux
- Is your project JavaScript or Typescript: Typescript

### Describe the bug
```
 TSConfckParseError: [vite:esbuild] failed to resolve "extends":"@strapi/typescript-utils/tsconfigs/admin" in                            │
│   /home/tom/build/Nugreen/Plateforme-V2/Back-End/Back-End-partners/src/admin/tsconfig.json
```
### Steps to reproduce the behavior

1. yarn build

### Expected behavior

The builder can't find the admin.json file, it just doesn't exist in @strapi/typescript-utils/tsconfig/

### Solution

in src/admin/tsconfig.ts
change the: 
```
"extends": "@strapi/typescript-utils/tsconfig/admin"
```
by 
```
"extends": "@strapi/typescript-utils/tsconfig/server"
```
fix the bug

**Comment by hanpaine** [comment]
Fixed by https://github.com/strapi/strapi/pull/20865

**Comment by tombombadilom** [comment]
sorry i was on vacation , after upgrade to rc11 , bug is gone .
