### ISSUE TITLE
error saving new collection

### ISSUE THREAD

**Issue by luizfilipeschaeffer** [strapi/strapi#20927]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by pandeyprafull** [comment]
@luizfilipeschaeffer can you please describe  in brief that how you interact with the issue .?

**Comment by luizfilipeschaeffer** [comment]
claro, eu estava criando nova coleção com tabelas relacionadas, quando eu colocava o relacionamento de muitas para muitas e salvava acontecia este erro.

![image](https://github.com/user-attachments/assets/072c5772-4dc4-4e14-a7cb-c287344417b3)

**Comment by pandeyprafull** [comment]
@luizfilipeschaeffer can you please answer the below points as per your system where you noticed the bug ?
Required System information
Node.js version:
NPM version:
Strapi version:
Database:
Operating system:
Is your project Javascript or Typescript:
