### ISSUE TITLE
Blank screen when creating content

### ISSUE THREAD

**Issue by RichieMerchant** [strapi/strapi#2092]
**Informations**
- **Node.js version**: 10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: MongoDB v4.0.1
- **Operating system**: Mac OS High Sierra Version 10.13.6

**What is the current behavior?**
- Unable to create content type entry because I get a blank screen. The URL for the content manager is `http://localhost:1337/admin/plugins/content-manager/node/create?redirectUrl=/plugins/content-manager/node?_limit=10&_page=1&_sort=_id&source=content-manager`

There is an error in the console
<img width="624" alt="screen shot 2018-10-07 at 01 11 40" src="https://user-images.githubusercontent.com/425535/46576885-08082e80-c9ce-11e8-9016-2241ceceb2b8.png">

The Node content type settings are
```
{
  "connection": "default",
  "collectionName": "node",
  "info": {
    "name": "node",
    "description": "The main sections that make up the site"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "title": {
      "default": "",
      "type": "string",
      "required": true
    }
  }
}
```

**Steps to reproduce the problem**
- Create new API from Admin
- Create new content type called node
- Create new field called title, Type String, Required
- Save
- Create new Node from content type
- Get a blank screen

**What is the expected behavior?**
Should see a form with the title field

**Suggested solutions**
Maybe instead of a black page, something that helps you debug the problem. Maybe a stack trace

**Comment by derrickmehaffy** [comment]
Reserved words:

https://github.com/strapi/strapi/blob/d8a2c9a833629d311e0b5a60a5105c2ac38d9105/packages/strapi-plugin-content-type-builder/admin/src/containers/Form/utils/attributeValidations.js#L39-L61

**Comment by derrickmehaffy** [comment]
if `node` is causing issues then it will need to be added to that list

**Comment by technical1000heads** [comment]
I am getting this same issue even when not using a reserved word (that I can see). An example of my settings.json file for one of the models in question.

`{
  "connection": "default",
  "collectionName": "programmes",
  "info": {
    "name": "programme",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string",
      "required": true
    },
    "startdate": {
      "default": "",
      "type": "date"
    },
    "enddate": {
      "default": "",
      "type": "date"
    },
    "objective": {
      "default": "",
      "type": "text"
    },
    "workstreams": {
      "collection": "workstream",
      "via": "programme"
    },
    "roi": {
      "default": "",
      "type": "string"
    },
    "secondarymetric": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "views",
        "clicks",
        "shares"
      ]
    },
    "secondarymetrictarget": {
      "default": "",
      "type": "string"
    },
    "goals": {
      "collection": "goal",
      "via": "programme"
    }
  }
}`

It returns the exact same error in the console and also presents a blank page.

**Comment by RichieMerchant** [comment]
This is an ongoing issues and was not resolved as I expected. The blank screen happens intermittently. 

After creating a content type called `page`, I added  fields via admin. This worked fine. I later added a field manually via `Page.settings.json`, after which, I was not able to visit `Content Manager > Content Types > Page`

I get a blank screen with the following console error

<img width="1440" alt="screen shot 2018-10-10 at 00 49 04" src="https://user-images.githubusercontent.com/425535/46705186-544dab80-cc26-11e8-8cce-24811aabc07f.png">

The Content Type list for `Page` no longer shows the correct data, just the ID
<img width="1147" alt="screen shot 2018-10-10 at 00 52 39" src="https://user-images.githubusercontent.com/425535/46705327-eeadef00-cc26-11e8-8582-4df65cd0c831.png">

Any help resolving this would be great.

**Comment by soupette** [comment]
@RichieMerchant your schema in the `core_store` might be corrupted. Can you delete your `plugin_content_manager_schema` document in your db and restart your server?

**Comment by technical1000heads** [comment]
Deleting those from the core_store looks like it might have done the job.

**Comment by ChunAllen** [comment]
I tried to delete the `plugin_content_manager_schema` in `core_store` but it also deletes the content_type (table) corrupted. Is it possible not to delete the whole content_type? It's dangerous if happened in production

**Comment by ChunAllen** [comment]
I think the cause of this is when adding a `relational field` and change the field name. 

In this screenshot
I have **attractions** content type with **poi_uuid** string unique field
then I have **reviews** content type and associated it to attractions thru **poi_uuid**
<img width="777" alt="screenshot 2018-10-16 15 13 12" src="https://user-images.githubusercontent.com/2100728/46998742-053bd500-d156-11e8-9be8-c27144f551f4.png">

**Comment by lauriejim** [comment]
Actually nop, the format of the `plugin_content_manager_schema` value changed between last version.
It was write in the migration guide.

**Comment by nickkrein** [comment]
I have a similar problem. I created a Guest user and then logged out and attempted to log in as the guest to make sure the proper permissions were in place. I was unable to access the admin panel, and when logging in again as admin I received a blank white screen when attempting to access anything related to me users. Let me know if I need to open a separate issue or provide additional information.

**Comment by avirankatzsofi** [comment]
I'm experiencing this bug on a new strapi installation when trying to add a new user from the admin panel. Blank screen, and the same minified error.

**Comment by derrickmehaffy** [comment]
@avirankatzsofi I had a similar issue: https://github.com/strapi/strapi/issues/2310

@soupette is already working on a fix that will come out with the next release. It's a problem with the content manager plugin and the `core_store`

**Comment by soupette** [comment]
@avirankatzsofi Did you try a with a complete new app and db or did you migrate your data?
