### ISSUE TITLE
Could not find a generator for "plugin"

### ISSUE THREAD

**Issue by luchanan** [strapi/strapi#20928]
### Required System information

- Node.js version:v20.15.1
- NPM version:10.7.0
- Strapi version: 5.0.0-rc.8
- Database:sqlite
- Operating system:window 11
- Is your project Javascript or Typescript:Javascript 

### Describe the bug

Could not find a generator for "plugin"

### Steps to reproduce the behavior

1. npm run strapi generate plugin
2. See error

```
> strapi@0.1.0 strapi
> strapi generate plugin

[PLOP] Could not find a generator for "plugin"
```

### Expected behavior

generator plugin success

### Screenshots

![image](https://github.com/user-attachments/assets/f56fe8bd-a825-4552-aed3-706f48ff861c)

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/19942
