### ISSUE TITLE
Deleting or renaming a component does not delete/update the relational linking data for the component

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#20931]
### Required System information

- Node.js version: node/v20.11.1 linux x64
- NPM version: yarn/1.22.22 npm/? 
- Strapi version: 4.25.6
- Database: SQLite
- Operating system: Linux Mint 21.3
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When a component is deleted or rename the related component data is not properly deleted or updated (updating may not be easily possible).

In certain cases or certain database types this can lead to an error similar to:

```
error: Metadata for "category.component" not found
```

I was not able to reproduce this error but I can see the remaining artifacts within the database

### Steps to reproduce the behavior

1. Create a content-type containing several components or dynamic zones with components
2. Create some test data on the content-type including some component data
3. Delete or rename the component (renaming requires doing it manually through the schema files)
4. Check the database component linking tables (using something like dbeaver)
5. See that the component data still exists

### Expected behavior

When a component is deleted all references in the database to that component should also be deleted. In the case of renaming we may not be able to do that automatically until we refactor the CTB (similar to renaming a normal field)

### Screenshots

Content Structure prior to modification:
![image](https://github.com/user-attachments/assets/2e994003-e6e1-4058-9d04-3ef0f2fa9322)

Example entry containing the data:
![image](https://github.com/user-attachments/assets/f50aeae1-3776-4c7b-84c8-8e783dec7404)

Database Prior to deleting the component:
![image](https://github.com/user-attachments/assets/a9eac3d3-76d8-48e1-8a02-815597529565)

Deleting a component and the data within the database:
![image](https://github.com/user-attachments/assets/0e4647c2-3105-4230-a9b6-9acf07b8bcbd)

### Code snippets

N/A

### Additional context

Related to TID7662

**Comment by smoove** [comment]
Same issue, after deleting a component that was still assigned to a dynamic zone in a page.
Stack trace:

```
strapi | [2024-08-05 09:16:20.721] error: Metadata for "dev.test-delete" not found
strapi | Error: Metadata for "dev.test-delete" not found
strapi |     at Metadata.get (/opt/node_modules/@strapi/database/dist/index.js:2676:13)
strapi |     at morphToMany (/opt/node_modules/@strapi/database/dist/index.js:3704:22)
strapi |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
strapi |     at async applyPopulate (/opt/node_modules/@strapi/database/dist/index.js:3831:9)
strapi |     at async Object.execute (/opt/node_modules/@strapi/database/dist/index.js:4704:11)
strapi |     at async Object.findMany (/opt/node_modules/@strapi/database/dist/index.js:5329:22)
strapi |     at async /opt/node_modules/@strapi/database/dist/index.js:6821:21
strapi |     at async Array.databaseErrorsMiddleware (/opt/node_modules/@strapi/core/dist/services/document-service/middlewares/errors.js:13:12)
strapi |     at async CollectionTypeService.find (/opt/node_modules/@strapi/core/dist/core-api/service/collection-type.js:16:21)
strapi |     at async Object.find (/opt/node_modules/@strapi/core/dist/core-api/controller/collection-type.js:16:39)
```

**Comment by derrickmehaffy** [comment]
Assigned this as both a v4 and v5 issue

**Comment by derrickmehaffy** [comment]
Raising this to high as it does completely break the ability to perform updates on content-types that used to have that previous component in the past. The only way to fix it is to manually go into the database and clear out all old references to the old component name

**Comment by derrickmehaffy** [comment]
Another related cloud ticket: TID8640

**Comment by gituser** [comment]
There is also a related bug if you use transfer function and synchronize DB somewhere else some of your synced data might be incorrect.

The reason is: transfer makes new posts IDs sequential and if you have some hanging attributes in the DB they will be applied instead of the actual properties.

E.g. let's say you created posts: 1,2,3,4 and added attributes to each one of them and then you delete post 2 and create same post but with id 5, so you will have posts: 1,3,4,5

When you do transfer on such DB to other strapi instance you will get posts: 1,2,3,4, where post with id=2 will be with old attributes instead of the new ones.

**Comment by kasonde** [comment]
Referencing Internal TID: 8724

**Comment by innerdvations** [comment]
For anyone experiencing this issue in v5, would you be able to try out https://github.com/strapi/strapi/pull/21928 (v5 experimental: 0.0.0-experimental.8e52d29d243dccc7c24beb53412cf1c9c0b36d11 ) and confirm it fixes the problem?

**Comment by bolg55** [comment]
Also related to internal TID8927
