### ISSUE TITLE
The project cannot be started for unknown reasons

### ISSUE THREAD

**Issue by tuyangJs** [strapi/strapi#20934]
### Required System information

- Node.js version:20.16
- NPM version:10.2.5
- Strapi version:4.25.5
- Database:
- Operating system:Windows11 22631.3958
- 
### Describe the bug

I created some data tables during use, but after saving them, the project automatically restarted and couldn't start
I can't start even after reinstalling the module

### Steps to reproduce the behavior

1.npm run dev 

### Expected behavior

Can be started normally

### Screenshots

![image](https://github.com/user-attachments/assets/d3dc7270-47d8-4f0d-a363-731b0542a80f)

### Code snippets

https://stackblitz.com/~/github.com/tuyangJs/strapi_Bug

### Additional context

`
Debugger attached.
⠦ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                         │
│   Error: Could not load the "sharp" module using the win32-x64 runtime                                                                  │
                                                                        │
│   \\?\F:\UGit\BiGeng Serve\node_modules\.store\@img+sharp-win32-x64@0.33.4\node_modules\@img\sharp-win32-x64\lib\sharp-win32-x64.node   │
│   Possible solutions:                                                                                                                   │
│   - Ensure optional dependencies can be installed:                                                                                      │
│       npm install --include=optional sharp                                                                                              │
│       yarn add sharp --ignore-engines                                                                                                   │
│   - Ensure your package manager supports multi-platform installation:                                                                   │
│       See https://sharp.pixelplumbing.com/install#cross-platform                                                                        │
│   - Add platform-specific dependencies:                                                                                                 │
│       npm install --os=win32 --cpu=x64 sharp                                                                                            │
│   - Using the canvas package on Windows?                                                                                                │
│       See https://sharp.pixelplumbing.com/install#canvas-and-windows                                                                    │
│   - Check for outdated versions of sharp in the dependency tree:                                                                        │
│       npm ls sharp                                                                                                                      │
│   - Consult the installation documentation:                                                                                             │
│       See https://sharp.pixelplumbing.com/install                                                                                       │
│       at Object.<anonymous> (F:\UGit\BiGeng Serve\node_modules\.store\sharp@0.33.4\node_modules\sharp\lib\sharp.js:114:9)               │
│       at Module._compile (node:internal/modules/cjs/loader:1358:14)                                                                     │
│       at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)                                                              │
│       at Module.load (node:internal/modules/cjs/loader:1208:32)                                                                         │
│       at Module._load (node:internal/modules/cjs/loader:1024:12)                                                                        │
│       at Module.require (node:internal/modules/cjs/loader:1233:19)                                                                      │
│       at require (node:internal/modules/helpers:179:18)                                                                                 │
│       at Object.<anonymous> (F:\UGit\BiGeng Serve\node_modules\.store\sharp@0.33.4\node_modules\sharp\lib\constructor.js:10:1)          │
│       at Module._compile (node:internal/modules/cjs/loader:1358:14)                                                                     │
│       at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)                                                              │
│                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Waiting for the debugger to disconnect...
`

**Comment by derrickmehaffy** [comment]
This looks like an environmental issue with sharp unrelated to us.
