### ISSUE TITLE
Content-type builder dialogues are broken in Strapi v5

### ISSUE THREAD

**Issue by Matb85** [strapi/strapi#20932]
### Required System information

- Node.js version: v20.11.0
- NPM version: yarn 1.22.2 npm 10.2.4
- Strapi version: 5.0.0-rc.8
- Database: postgres
- Operating system: MacOS Sonoma 14.5
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I just initialised Strapi with ```npx create-strapi@rc``` and ran ```yarn dev```

The dialogues for entering the collection's name and adding fields are broken

### Steps to reproduce the behaviour

1. Go to 'Content-type builder'
2. Click on 'Add a new collection type'
3. Type the collection's name

### Expected behavior

1. The first dialogue should have a footer with "cancel" and "continue" buttons
2. The second dialogue should display available fields to choose from

### Screenshots

<img width="1470" alt="Screenshot 2024-08-03 at 10 41 32" src="https://github.com/user-attachments/assets/25c88b33-f1f2-43d8-89a8-116a5a10c5ed">
<img width="1470" alt="Screenshot 2024-08-03 at 10 44 07" src="https://github.com/user-attachments/assets/8d37a000-f8bb-425e-b7ac-bdbfef9eff1d">

### Code snippets

---

### Additional context

---

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/20660
