### ISSUE TITLE
Strapi 5 Upgrade tool does not properly detect Old plugin structure to execute proper codemods (es to ds)

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#20944]
### Required System information

- Node.js version: node/v20.11.1
- NPM version: yarn/1.22.22
- Strapi version: 5.0.0-rc.8
- Database: SQLite
- Operating system: Linux Mint 21.3
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When running the upgrade tool against a plugin directly, the upgrade tool does not properly detect the plugin structure to run the codemods properly. In this example running the upgrade tool against a newly generated Strapi plugin from v4 (with some minor modification to add the entityService.

Ex: `npx @strapi/upgrade@rc codemods run --project-path ./src/plugins/test-plugin`

### Steps to reproduce the behavior

1. Create a plugin in v4 (using the legacy `yarn strapi generate plugin` command
2. Copy that plugin to a Strapi RC project
3. Setup the plugin properly as normal (install modules, ect)
4. Try to run the upgrade tool
5. See that only 2 of the codemods actually did anything since Strapi 4 plugins have an old structure

### Expected behavior

We should be doing all required modifications to the plugin that we can such as:

- Migrating plugins to the new structure if required (moving to ./src and removing the no-longer required `strapi-admin.js` file)
- Have codemods look through all files within the directory tree for things we can migrate (es to ds, and config namespace)
- Warn the user on things we cannot migrate

### Screenshots

![image](https://github.com/user-attachments/assets/1bf0bf84-08bc-4346-8a1a-f13f7531c98d)

### Code snippets

```
"use strict";

module.exports = ({ strapi }) => ({
  index(ctx) {
    let data = strapi.entityService.find("admin::user");

    console.log(data);

    ctx.body = strapi
      .plugin("test-plugin")
      .service("myService")
      .getWelcomeMessage();
  },
});
```

### Additional context

Related to @PaulBratslavsky and my work with Mux on migrating their plugin

**Comment by hanpaine** [comment]
@derrickmehaffy I'm not sure we are supporting the creation of new plugins on v4 so is this use case valid? Or is the context the same whether it's a new v4 plugin vs and existing one?

**Comment by hanpaine** [comment]
@derrickmehaffy confirmed with Product that new v4 plugin creation will be supported until end of 2024 btw 🙏

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I'm not sure we are supporting the creation of new plugins on v4 so is this use case valid? Or is the context the same whether it's a new v4 plugin vs and existing one?

This is more about migrating previously created Strapi 4 plugins but in theory it should be supported until v4 is EOL which depends on when v5 is released but should be 12 months.

**Comment by Convly** [comment]
Just a heads up, but 

> Migrating plugins to the new structure if required (moving to ./src and removing the no-longer required strapi-admin.js file)

Won't be doable using either the codemods or the upgrade tool. The goal of this tool is to perform breaking change code migrations, not structural changes like moving files.

Adding support for such a feature would most likely be done in a v2
