### ISSUE TITLE
Crash on Rich Text Block Editor: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":0}

### ISSUE THREAD

**Issue by frinux** [strapi/strapi#20943]
### Required System information

- Node.js version: 20.x
- NPM version: Yarn 4.1
- Strapi version: 5.0.0-rc.8
- Database: PgSQL
- Operating system: Ubuntu (on Heroku)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

On Firefox 128.0.3
When removing existing content from Rich Text Block Editor, a crash happens:

![image](https://github.com/user-attachments/assets/5788f434-6a10-4b91-82da-136e522cdb3c)

### Steps to reproduce the behavior

1. Go to Content Manager
2. Click on an existing item with existing content in a Rich Text Block Editor,
3. Select all content and type any char

### Expected behavior

Text should be removed and replaced by the new one

### Screenshots

https://github.com/user-attachments/assets/bf5df30a-178b-43f4-b6a3-d70f0d712b31

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by bolg55** [comment]
Confirmed. A few notes:

- Seems to be triggered by selecting the actual block icon itself. 
- If you cmd/ctrl + a or drag from right to left over all of the content it is reproducible. 
- If you only highlight the text itself (double-click the word, or highlight carefully), it works as expected.
- Also broken in Chrome/Brave


https://github.com/user-attachments/assets/47934b81-77a5-4388-b0f3-cb1bc9125e13

**Comment by alexandrebodin** [comment]
Hi @bolg55 Can you confirm it's v5 only ?

**Comment by alexandrebodin** [comment]
So I tested, the issue is well known with slate and it is in v4. Removing from v5 board

**Comment by alexandrebodin** [comment]
cc @oiorain
