### ISSUE TITLE
Middleware for core (createCoreRouter) does not fire

### ISSUE THREAD

**Issue by fmlukaszmatusik** [strapi/strapi#20951]
### Required System information

- Node.js version: 18.14.2
- NPM version: - (we use yarn 1.22.22)
- Strapi version: 4.25.5
- Database: Postgres
- Operating system: MacOs Sonoma
- Is your project Javascript or Typescript: TS

### Describe the bug

This is my core router, located in backend/src/api/blog-item/rotes/blog-item.ts

```
/**
 * blog-item router
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreRouter('api::blog-item.blog-item', {
  config: {
    find: {
      middlewares: ["api::blog-item.link"],
    },
    findOne: {
      middlewares: ["api::blog-item.link"],
    },
    read: {
      middlewares: ["api::blog-item.link"],
    },
    update: {
      middlewares: ["api::blog-item.link"],
    },
  },
});
```

Ad this is my middlewar, located in backend/src/api/blog-item/middlewares/link.ts

```
import { Strapi } from '@strapi/strapi';

export default (config, { strapi }: { strapi: Strapi }) => {
  return async (ctx, next) => {
    strapi.log.info('In link middleware.');
    strapi.log.info('Ctx', ctx);

    console.log('ABC');

    await next();
  };
};
```

The problem is, it does not log anything into console. What's more, if I throw inside, nothing happens on any operation. It seems it does not fire at all, but if I provide invalid name in route config, it tells me this middleware does not exist. I've followed official docs, still nothing...

### Steps to reproduce the behavior

1. Create any API middleware, throw inside or log
2. Attach it to a `createCoreRouter()` method as a second param in `config.find.middlewares[]` for example.
3. See nothing happens

### Expected behavior

Middleware should fire

**Comment by fmlukaszmatusik** [comment]
@derrickmehaffy Okay, did not know! Sorry! Is there any way I can fire something on "save/publish" in Admin CMS, other than lifecycle hooks?

**Comment by derrickmehaffy** [comment]
There is an undocumented and unstable way to do it in v4 (directly inject middlewares on the Admin APIs): https://github.com/strapi-support-demo-apps/strapi-example-v4-ctm-route-middleware/blob/main/src/index.js

Once Strapi 5 stable/GA is out then I would advise switching to the documentService Middlewares: https://docs-next.strapi.io/dev-docs/api/document-service/middlewares

**Comment by derrickmehaffy** [comment]
I'm going to go ahead and flag this as a question (which will auto-close it) since it's not really a bug.
