### ISSUE TITLE
Migrations for relations between Published contentTypes and contentTypes with no Draft and publish are broken

### ISSUE THREAD

**Issue by Bassel17** [strapi/strapi#20953]
### Required System information

- Node.js version: 20.13.1
- NPM version: 10.5.2
- Strapi version: latest V5 (v5/main)
- Database: sqlite
- Operating system: Macos
- Is your project Javascript or Typescript: JS

### Describe the bug

- In the examples getstarted project, add and publish some categories, add some address data with a relation to a published category (done on develop branch)
- switch to `v5/main` run the project, migrations will fail and through an error
![image](https://github.com/user-attachments/assets/af3941e8-d77c-42e3-8e90-4b6fbc45083b)

### Expected behavior

- migrations should run successfully with no error

**Comment by innerdvations** [comment]
Just a note, this wasn't actually a bug, it was just the error that will be seen when someone tries to add something to their schema in between migrating from v4->v5, which strictly not allowed and expected to throw an error.
