### ISSUE TITLE
[Strapi v5 RC] Localized `Has-Many` Field Values Not Differentiated Across Locales

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20957]
### Required System information

- **Node.js version**: 18.17.0
- **NPM version**: yarn/1.22.19
- **Strapi version**: 5.0.0-rc.8
- **Database**: sqlite
- **Operating system**: darwin-arm64
- **Project type**: Typescript

### Describe the bug

I have a `has-many` field in one of my collection types. This collection type is localized, but whenever I change the many-to-many field for one locale, it also changes for all other locales. It appears that the field cannot have different values across locales. Is it expected?

### Steps to reproduce the behavior

1. Create a collection type X with a required, unique `name` field. Disable localization for the collection type. Add 3-5 entries for X using the content entry creator.
2. Create another collection type Y which has a `many-way` relation to this X, so it can hold multiple X entries in one Y instance. Enable localization for the content type. 
3. Add an entry for one language by selecting some entries from X.
4. Localize this entry (select another locale), fill in the fields, select other X instances, and save.
5. After refreshing, both localized entries have the same X instances attached; they can't have different ones.

### Expected behavior

The `has-many` field should allow different values across locales. Each locale-specific entry should be able to have its own set of related entries.

### Screenshots

![image](https://github.com/user-attachments/assets/567ae2ed-63d7-42f3-a671-f1af838d35c3)

### Code snippets

N/A

### Additional context

N/A

**Comment by hanpaine** [comment]
Hi @burakozdemir32 thanks for raising - this is indeed by design

**Comment by burakozdemir32** [comment]
> Hi @burakozdemir32 thanks for raising - this is indeed by design

Hi! Could you please provide a link to this design decision from the docs? If it's by design, it should not allow creating this relationship.
