### ISSUE TITLE
Unable to create a component

### ISSUE THREAD

**Issue by SachinMS4** [strapi/strapi#20964]
### Required System information
- Node.js version: v20.12.2
- NPM version: 10.8.2
- Strapi version: 5.0.0-rc.8
- Database: Postgres
- Operating system: macOS 14.6 (23G80)
- Is your project Javascript or Typescript: Typescript
- Browser: chrome v127.0.6533.89 (Official Build) (arm64)

### Describe the bug
Using the Strapi admin panel, unable to create a new component as the "Configure the component"/"Next" button isn't available.

### Steps to reproduce the behavior

1. Go to "Content-Type Builder"
2. Select a collection to edit
3. Click on "Add another field"
5. Scroll down and select "Component"
6. After filling in all fields, there is no option to proceed

### Expected behaviour
Able to create a new component

### Screenshots
<img width="1437" alt="Screenshot 2024-08-07 at 10 29 10 PM" src="https://github.com/user-attachments/assets/3ea442b9-dc80-48fb-89f2-92740218e77c">

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/20660
