### ISSUE TITLE
Unable to run Strapi on initial setup - Connection Refused Error on MySQL 9.0

### ISSUE THREAD

**Issue by HeisUser** [strapi/strapi#20983]
### Error on Strapi :
Error: connect ECONNREFUSED 127.0.0.1:3306 | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
![Screenshot 2024-08-09 at 09 45 55](https://github.com/user-attachments/assets/4cb90abb-45b3-4ba1-be18-c48cf08048c7)

### Error caused by _mysql_native_password_ Legacy Authentication of MySQL Plugin 
**mysql_native_password** had been removed on MySQL 9 now.
_any replacement to resolve MySQL 9 make connection to Strapi?_

**Official Announcement** on MySQL 9 as link below
https://dev.mysql.com/doc/relnotes/mysql/9.0/en/news-9-0-0.html

### Required System information
![Screenshot 2024-08-09 at 09 46 33](https://github.com/user-attachments/assets/ee4bb967-55fc-4987-abb0-bc3f75292999)
![Screenshot 2024-08-09 at 09 46 54](https://github.com/user-attachments/assets/c0f17687-4593-43e2-aeeb-d119e8f412ab)

- Node.js version: v20.15.1
- NPM version: 10.8.2
- Database: MySQL 9.0.1
- Operating system: MacOS Latest Updated
- Is your project Javascript or Typescript: Javascript

![Screenshot 2024-08-09 at 11 54 48](https://github.com/user-attachments/assets/3f00469c-2495-4c30-8677-0c049e1e7e9e)

**Comment by derrickmehaffy** [comment]
Unrelated to us, either your database isn't running, or you have an authentication problem.
