### ISSUE TITLE
Error persisting Entity in DB with standard service structure on an UPDATE/PATCH request

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#2098]
**Informations**
- **Node.js version**:10.10.0
- **npm version**:6.4.1
- **Strapi version**:3.0.0-alpha.14.2
- **Database**:Postgres
- **Operating system**:Mac high Sierra

**What is the current behavior?**
a creation of an entity fails when this lines get executed:
error on this line: User.forge(data).save();

the Error message is: Undefined binding(s) detected when compiling SELECT query ........

> const relations = _.pick(values, User.associations.map(ast => ast.alias));
>     const data = _.omit(values, User.associations.map(ast => ast.alias));
> 
>     // Create entry with no-relational data.
>     const entry = await User.forge(data).save();
> 
>     // Create relational data and return the entry.
>     return User.updateRelations({ id: entry.id , values: relations });
> 

**Steps to reproduce the problem**
That is the standadrd service created after a new model gets created with the new admin console

**What is the expected behavior?**
Persisting that entity even with no associated reaction exists for the attributes that are marked as nullable in the DB.

**Suggested solutions**

**Comment by jmchza** [comment]
Hi @lauriejim, sorry about the delay. but yes that is a POST request.
and yes Ideally this should work out of the box right ?

The POST is really a previous request with only one attribute changed to test the update through the whooe data structure/tree.

The interesting thing here is that there is no Error thrown, bear in mind that this is running with strapi-hook-knex and strapi-hook-bookshelf with postgres DB.

Thank toy very much in advance.
Cheers.

**Comment by lauriejim** [comment]
Can you give me the file and line of code you copy in your issue please.

**Comment by jmchza** [comment]
Sorry I think I haven't explained properly the problem.
Let me try it again: the issue is only on the persistence of the relations of a model.when an update/create relations of a model get called.
Let's say we have a model user that contains a relation called usersetting, whenever a change on any of the attributes of the usersetting occurs that update does not hav any effect on the reference of that relation.

In the above example will be the next line that worst case scenario should throw an Error: 
```
return User.updateRelations(Object.assign(params, { values: relations }));
```
which does not throw any error.

Please let me know if that did help. I will actively be looking at assisting in this ticket.
Thank you very much.

**Comment by lauriejim** [comment]
Hum to be sure to understand, can you give me your `User`model and your `usersetting` model.

And when the suite of request I have to do to show the issue.

Thank you.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
