### ISSUE TITLE
[Design] The button in the filters of the list view is broken

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20986]
### Steps to reproduce
- Go to the List View in the Content Manager
- Click on the Filters button
- See that the Add Filter CTA in the dropdown is broken

### Expected behavior

The Add Filter button should be centered.

### Screenshots

![Image](https://github.com/user-attachments/assets/f14d6d07-8486-4a86-8658-a9cf8f449be7)

**Comment by simotae14** [comment]
I am gonna close the issue because it was already fixed with this release of the DS https://github.com/strapi/design-system/pull/1779 thanks
