### ISSUE TITLE
File Upload of an existing file in Media causes an Uncaught Exception

### ISSUE THREAD

**Issue by thzero** [strapi/strapi#20988]
### Required System information
- Node.js version: v20.12.2
- NPM version: 10.5.0
- Strapi version: 4.25.5 (node v20.12.2) 
- Database: mariadb
- Operating system: Windows 11 Pro
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Using the Media Library to upload a file an uncaught error is thrown when the file being uploaded already exists in Strapi's media folder.    This errors  occurs when using the 'Add new assets' as well as when replacing an asset.

~~~
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EBUSY: resource busy or locked, unlink '...\upload_f9d59df7bd667eeae1c98589ed811af7'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: '...\upload_f9d59df7bd667eeae1c98589ed811af7'
}
~~~

More than likely due to an environment issue on the particular machine, but should be able to be handled more gracefully than crashing the entire Strapi application,

### Steps to reproduce the behavior

1. Go to 'Media Library.'
2. Click on 'Add new assets'
3. Add a new asset in the dialog
4. Click 'Upload ... asset to the library'
2. Click on 'Add new assets'
3. Add the same asset as in step 3.
4. Click 'Upload ... asset to the library'
5. See error

### Expected behavior

An error message in the Strapi UI telling the user that there was an issue with the upload.   Strapi4 application handles the exception and does not crash the application.

**Comment by axis-devanagari-pin** [comment]
I'm also getting this error.
