### ISSUE TITLE
Issue in GraphQL array-type parameters

### ISSUE THREAD

**Issue by aschick82** [strapi/strapi#20994]
There is a significant issue in the GraphQL API of v5.

There is no way you can pass an array parameter like [String].

An error keeps coming up from the graphql-depth-limit package as below:

 `TypeError: Cannot read properties of undefined (reading 'kind')`

**Comment by pandeyprafull** [comment]
@aschick82 can you please provide the system details +  versions (strapi, npm , node, mysql), also can you please share some steps that how you can reproduce  the issue ..

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
