### ISSUE TITLE
Add Media on "public/uploads" Folder but Media Library of Admin Panel is Not SYNCHRONIZING

### ISSUE THREAD

**Issue by HeisUser** [strapi/strapi#20993]
### Error (Describe the bug)
Directly Add or Delete Media onto "public/uploads" Folder of local at first place but Media Library of Strapi Admin Panel is not synchronizing together. 
![Add or Delete Media at First Place onto uploads directory](https://github.com/user-attachments/assets/fce213d3-df89-4a1c-ac12-37ad80a14d86)
![Media files no synchronizing to Admin Panel](https://github.com/user-attachments/assets/de7bd19f-0a7e-4702-bda6-1d7cdb2c5a27)

### Your Consultation
_**Hope your guys kindly provide resolution to resolve this error**_

### Information of _npm run strapi report_
![Screenshot 2024-08-11 at 17 03 11](https://github.com/user-attachments/assets/e8a3d37c-2d6e-41ad-b368-c8b3ca44f2a4)
### Operating System
![Screenshot 2024-08-11 at 17 05 25](https://github.com/user-attachments/assets/e7afd6b4-b994-4daa-b400-058b84e5898b)
### Node.js Version
![Screenshot 2024-08-11 at 17 06 28](https://github.com/user-attachments/assets/ba0333ad-2c16-438d-8310-7fab7a048310)
### MySQL Version
![Screenshot 2024-08-11 at 17 05 11](https://github.com/user-attachments/assets/83bb3ce2-d9f4-40d9-a49b-0c36c57cb49b)
- Database: MySQL 8.4.1
- Is your project Javascript or Typescript: Javascript

**Comment by kasonde** [comment]
Thanks for submitting this. I'm closing this issue as it's incorrect usage of the media library, i.e this is not now the media library is intended to function. All media files must be uploaded through strapi and not the file system directly as Strapi creates records of the media at the time of upload.
