### ISSUE TITLE
Error during locale switch while you are adding a new content and no content has been entered for the other locale

### ISSUE THREAD

**Issue by aschick82** [strapi/strapi#20991]
I am using version RC.9 and this issue is still there.

When a content type has **Internationalisation** enabled and you want to add new content for that, when you switch to a locale for which no content has been added yet, a couple of red errors comes up and also those fields which are not localized are not pre-filled automatically.

**Comment by kasonde** [comment]
Hi @aschick82 

Thanks a lot for taking the time to submit these issues. However, I've noticed that this is the 3rd issue I've seen of yours (recently) where you aren't respecting the issue template. Please respect our template and fill it in correctly *each time* you create an issue. Failure to do so will have your issue flagged for an invalid template and eventually closed. Thanks.
