### ISSUE TITLE
Dynamic Zone: Required fields not working.

### ISSUE THREAD

**Issue by renegarcia225** [strapi/strapi#20998]
Hello, when using custom components inside a dynamic zone with required fields, they appear as required but page is still being saved, is there a way to throw error to the user if one or more components or sub-components have required fields unfilled ?

**Comment by LoadJulz** [comment]
I have the same issue. I define a dynamic zone as required field but even if I don't fill it out I can save the entry.

**Comment by LoadJulz** [comment]
A workaround for this is to set the minimum to 1
