### ISSUE TITLE
Data Diagram or Entity-Relationship (ER) chart

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2100]
**What is the expected behavior?**

I think it's very handy and have good UX if we can have a simple **Data Diagram or Entity-Relationship (ER) chart** of the current state in http://localhost:1337/admin/plugins/content-type-builder page.
Something like this:

![01-entity-relationship-diagram](https://user-images.githubusercontent.com/25859075/46664944-3d2f9f00-cbcf-11e8-9e8b-6d6f008c4ef1.png)

**Comment by Aurelsicoko** [comment]
Oh yeah! It could be so coooool 👍 

I'm closing this issue, as it's a feature request we continue on ProductBoard https://portal.productboard.com/strapi/c/25-data-diagram-or-entity-relationship-chart

**Comment by romanmandryk** [comment]
Hi,
I have created a version of the entity-relation-chart here: 
https://www.npmjs.com/package/strapi-plugin-entity-relationship-chart
https://github.com/node-vision/strapi-plugin-entity-relationship-chart
It shows entities, field and relations. All can be moved around and zoom in/out.

I hope to get some feedback to improve it.
