### ISSUE TITLE
Can't open the edition modal in the configure the view page

### ISSUE THREAD

**Issue by lucasboilly** [strapi/strapi#21006]
### Required System information

- Node.js version: 18.17.1
- Strapi version: 5.0.0-rc.9

### Screenshots
https://github.com/user-attachments/assets/685fabc1-1143-4766-bbdb-745690dbd09a

**Comment by hfersu** [comment]
Just as a clarification to add a little more context and a workaround, if instead of clicking on the pencil icon you click on the name, it opens the modal correctly.
