### ISSUE TITLE
Unable to config tests after following the docs for strapi V4

### ISSUE THREAD

**Issue by garryismael** [strapi/strapi#21019]
### Required System information

- Node.js version: v20.16.0
- NPM version: 10.8.2
- Strapi version: 4.25.7
- Database: Postgres for dev and sqlite3 for test
- Operating system: MacOS Big Sur
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I followed the official [docs](https://docs.strapi.io/dev-docs/testing) about unit testing but tests fail.

### Steps to reproduce the behavior

1. Run ```yarn tests```
4. Errors:  
   - SqliteError: select `t0`.* from `up_permissions` as `t0` where (`t0`.`id` = 1) limit 1 - database is locked
   - Jest has detected the following 1 open handle potentially keeping Jest from exiting:

### Expected behavior

Basic tests from docs pass

### Screenshots
<img width="887" alt="Screen Shot 2024-08-16 at 10 25 30" src="https://github.com/user-attachments/assets/fcb800cc-7f47-4e21-a057-e42e9bb81a9a">

<img width="887" alt="Screen Shot 2024-08-16 at 10 25 42" src="https://github.com/user-attachments/assets/c6aaab82-8558-4a62-85bb-43a3e173edba">

### Code snippets

```javascript
tests/helpers/strapi.js

const Strapi = require("@strapi/strapi");
const fs = require("fs");

let instance;

async function setupStrapi() {
  if (!instance) {
    await new Strapi().load();
    instance = strapi;

    await instance.server.mount();
  }
  return instance;
}

async function cleanupStrapi() {
  const dbSettings = strapi.config.get("database.connection");
  //close server to release the db-file
  await strapi.server.httpServer.close();
  // close the connection to the database before deletion
  await strapi.db.connection.destroy();
  //delete test database after all tests have completed
  if (dbSettings && dbSettings.connection && dbSettings.connection.filename) {
    const tmpDbFile = dbSettings.connection.filename;
    if (fs.existsSync(tmpDbFile)) {
      fs.unlinkSync(tmpDbFile);
    }
  }
}
module.exports = { setupStrapi, cleanupStrapi };
```

```javascript
// tests/app.test.js
const fs = require("fs");
const { setupStrapi, cleanupStrapi } = require("./helpers/strapi");

beforeAll(async () => {
  await setupStrapi();
});

afterAll(async () => {
  await cleanupStrapi();
});

it("strapi is defined", () => {
  expect(strapi).toBeDefined();
});

```
### Additional context
jest config inside package.json

"jest": {
    "testPathIgnorePatterns": [
      "/node_modules/",
      ".tmp",
      ".cache"
    ],
    "testEnvironment": "node",
    "testTimeout": 15000
  }

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/documentation/issues/2179
