### ISSUE TITLE
Upload file in media library without hash

### ISSUE THREAD

**Issue by JeanJacque** [strapi/strapi#21029]
### System information

- Node.js version: 20.12.1
- NPM version: 10.5.0
- Strapi version: 4.22.0
- Database: PostgreSQL 
- Operating system: 
- Is your project Javascript or Typescript: Typescript

### Question

Hi,

I know it's not a bug report, but I already posted a question on Strapi forum but with no answer (https://forum.strapi.io/t/direct-link-to-media-library-files/40396).

So, is there a easy way to disable the addition of a hash during file upload in media library please ? If the only way is to create a custom provider, can I find somewhere an example of a custom provider for file uploads ?

Thanks in advance.

**Comment by derrickmehaffy** [comment]
No at the moment it's not possible and we have no plans to disable it as it's a duplicate file name protection.

**Comment by JeanJacque** [comment]
Hi @derrickmehaffy, thanks for your "answer". But is there a documentation with an example of a custom upload provider please ? The only doc I found on this is one : https://docs.strapi.io/dev-docs/providers but a few informations are missing, like what each method has to return and an example would be a great help.

Thanks in advance

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy, thanks for your "answer". But is there a documentation with an example of a custom upload provider please ? The only doc I found on this is one : https://docs.strapi.io/dev-docs/providers but a few informations are missing, like what each method has to return and an example would be a great help.
> 
> Thanks in advance

Providers don't have control of the names directly, those are set by the upload plugin and likewise our image processing library sharp.

**Comment by derrickmehaffy** [comment]
I'm being blunt here because we get this question often and do not support / nor will we help people trying to do this for various reasons (seo, ect).

The hash suffix is there for a very good reason and we do not want to be responsible when someone inevitably ends up losing data because someone uploads a file with the same name.

**Comment by JeanJacque** [comment]
So it's not possible at all with a custom upload provider to do this ?

My goal is to handle the case where our client delete a file and reupload it without using the fonctionnality "Replace media", because they are sharing links of resources hosted on Strapi to their clients so they don't want to have to share thoses links again. But may be there is another solution for that ?

**Comment by derrickmehaffy** [comment]
No that's not possible and it's why the replace exists, to keep the same url.

The hash is there for protection and we have taken the decision years ago not to support disabling it. The hash is implemented above the providers within the upload plugin itself.

**Comment by JeanJacque** [comment]
Okay thanks for those information.

Best regards.
