### ISSUE TITLE
server url parameter in config - not working

### ISSUE THREAD

**Issue by Matb85** [strapi/strapi#21031]
### Required System information

- Node.js version: v20.11.0
- NPM version: yarn 1.22.2 npm 10.2.4
- Strapi version: 5.0.0-rc.10
- Database: postgres
- Operating system: MacOS Sonoma 14.5
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After building for production, the frontend has incorrect urls for script files

### Steps to reproduce the behavior

1. Go to set a custom url in config.ts
2. Build and deploy the project
3. See error (See https://domekuwiktorka.pl/api/admin)

### Expected behavior

The admin login view should show up

### Screenshots

nginx.conf:

<img width="630" alt="Screenshot 2024-08-20 at 12 36 55" src="https://github.com/user-attachments/assets/52794649-33a9-4d50-a4e3-f2065ac7b17b">

config/server.ts

<img width="566" alt="Screenshot 2024-08-20 at 12 38 28" src="https://github.com/user-attachments/assets/68685667-78c0-45e5-b403-20d0978028b5">

### Code snippets

probably something to do with Vite's config

### Additional context

the error:
<img width="1470" alt="Screenshot 2024-08-20 at 12 39 56" src="https://github.com/user-attachments/assets/f34c6dff-e698-4c41-8847-f26a6186c86a">

<img width="402" alt="Screenshot 2024-08-20 at 12 40 09" src="https://github.com/user-attachments/assets/95a0dd8c-04f5-498f-9d09-157b39657142">

the path should be /api/admin instead of /admin

<img width="414" alt="Screenshot 2024-08-20 at 12 40 20" src="https://github.com/user-attachments/assets/710ca975-13a6-4d98-b606-3a7346896a25">
ff5">

**Comment by derrickmehaffy** [comment]
We no longer support spit base proxying as there are just too many sub paths you have to configure for every plugin.

**Comment by Matb85** [comment]
but as you can see here:

![image](https://github.com/user-attachments/assets/e4849363-60ed-4e7b-bd23-964ce9e0aa50)

I don't use split base proxying here, I have used the code available here: https://forum.strapi.io/t/nginx-proxing-with-strapi/40618

I just want all strapi routes to have the "/api" prefix

But when I run strapi build with the url set to `mydomain.com/api`, the index.html does not have the correct paths to scripts (/admin/file.js instead of /api/admin/file.js)
