### ISSUE TITLE
Set model's primary key as uuid does not work properly. 

### ISSUE THREAD

**Issue by caoer** [strapi/strapi#2104]
**Informations**
- **Node.js version**: 10.11.0
- **npm version**: 6
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: postgres 10
- **Operating system**: mac

**What is the current behavior?**

* what's working
  * PR [1202: Make type of id configurable](https://github.com/strapi/strapi/pull/1682) made it possible to set uuid type as model's primary key. I'm able to create a model with it's id set to uuid type
* what's not working
  * idAttribute is not working, I've try to set it to `uuid`, but query related to model's relation will not be able to work. The id name of the table should be `uuid`, but it still is `id`. it is not created correctly. I found that it does not respect it when we create the table, in https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/index.js#L530

  * if such model has a relationship, one to one to user, any request to the change of the model failed. got error: 
		```
		update "ducks" set "id" = $1, "message" = $2, "user" = $3, "updated_at" = $4 where "id" = $5 - invalid input syntax for type uuid:
		 "1"
		```
   * if such model has a one to many relation with user, for example, user has many ducks. the application enters a strange state, I am not able to login to admin panel anymore. 

   * I've tested deleted user table, and set user's primary key as uuid type. then the whole application won't start anymore. got error:

```
(node:28889) UnhandledPromiseRejectionWarning: error: invalid input syntax for type uuid: "1"
```

I think the first issue is easy to fix, but the 2, 3, 4 probably has something to do with model relations. any ideas? 

**What is the expected behavior?**

model can have id as uuid field and user can configure it as they want. 

**Suggested solutions**

**Comment by maturanomx** [comment]
> The id name of the table should be uuid, but it still is id. 

Disagree. The changes is about the data type of the column, not about the name of the primary key. Changing the name of the primary key have a lot of other implications... could be done, yes, but is not the scope of the changes that you mention and is not required to use UUID as datatype for primary key.

> I think the first issue is easy to fix, but the 2, 3, 4 probably has something to do with model relations. any ideas?

The first issue is what I comment before.. 2, 3 and 4 I think are real issues, I detected them working on #1932 

Could you provide us an step by step to reproduce in the most simple way?; One-to-one relation maybe?. Would be a lot of help.

**Comment by caoer** [comment]
> The options key on the model-json states.
> idAttribute: This tells the model which attribute to expect as the unique identifier for each database row (typically an auto-incrementing primary key named 'id').
> idAttributeType: Data type of idAttribute, accepted list of value bellow:

regarding the first issue, I can totally live with not changing the name of the primary key! but in the latest [documentation](https://strapi.io/documentation/guides/models.html#model-options). it provides such option to change idAttribute, if we do not support it, probably should not put it in the documentation, or put a warning notice...

> Could you provide us an step by step to reproduce in the most simple way?; One-to-one relation maybe?. Would be a lot of help.

for 2 & 3. they are pretty much the same:
   * create a new application, with database type postgres
   * create a data model `duck` with a attribute `name` as string
   * set idAttributeType to uuid
   * try add one entry, it should works fine. 
   * modify the model, add a relationship to User, one to one (issue 2), or one to many (issue 3, user has many ducks)
   * save the modification to the model 
   * > try add any new entry, via admin panel, or api, error throws. 

for 4. 
   * create a new application
   * before application starts, we can see empty database with not table being created. 
   * set idAttributeType to uuid for User in 'users-permissions' plugin. 
   ```
      //User.setting.json
       "options": {
         "idAttributeType": "uuid"
       },
   ```
   * > not able to start the application

**Comment by lauriejim** [comment]
Related uuid issue on MySQL https://github.com/strapi/strapi/issues/1826

**Comment by lauriejim** [comment]
Duplicated to https://github.com/strapi/strapi/issues/1762
