### ISSUE TITLE
The published relationship is reset when updating the content in the related collection type

### ISSUE THREAD

**Issue by alexander-aleman** [strapi/strapi#21054]
### Required System information

- Node.js version: 20.15.1
- NPM version: 10.7.0
- Strapi version: 5.0.0-rc.11
- Database: MySQL 8
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The relation to a collection type is lost when the related item is changed and published.

### Steps to reproduce the behavior

1. Create a collection type "TypeA" with a text field
2. Create a collection type "TypeB" with a relation to collection TypeA
3. Create a TypeA item and publish it
4. Create a TypeB item and relate it to the previously create type A and publish it
5. You can see in the published tab, that everything seems to be ok.
6. Now edit the previously created TypeA and publish it
7. Now inspect the TypeB item, it seems ok in the draft, but the relation is lost on the published tab.
8. This relation is also gone when requesting TypeB using the REST api

### Expected behavior

The relation remains intact after editing and publishing the related item.

### Screenshots

Video 
https://www.loom.com/share/85b6b3115f064dc18f80c88ca4990979?sid=bda92b69-dc0f-433b-aab2-c4d369c5f190
(added mp4 just in case since I used a trial) https://github.com/user-attachments/assets/dc2fa0a1-e0d0-4d2d-87cf-5519b1933df9

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

To fix the relation I need to remove and add the relation and publish again.
Also see issue https://github.com/strapi/strapi/issues/20727, I could also reproduce this issue in 5.0.0-rc.10

**Comment by NEDDL** [comment]
@kasonde @derrickmehaffy @dennism501 @Convly any way to prioritize this? the bug is quite blocking in the project. I cannot continue data entry because when I make changes relations are lost. let me know if I can help in anyway.

**Comment by derrickmehaffy** [comment]
Moved to backlog without reproducing as the support team is already pretty slammed.

Engineering team sorry but you'll need to do the reproducing here.

**Comment by NEDDL** [comment]
Hi @derrickmehaffy thanks for your reply,

Hoping this would help..

Here is the repo you can use.
I created 2 collections to simulate.
https://github.com/NEDDL/relations-bug-reproduction

I don't know if it keeps database. If so:
Login: admin@admin.com
Password: 123456ABc

I created 2 entry in the "Nested related collection", I connected them in an entry of "Parent collection".
After modifying the entries in "Nested related collection" the relation is disappearing.

This picture is after creating a relation:
![Image](https://github.com/user-attachments/assets/11561216-232f-415f-ae70-2c7f821fe159)

This picture is after modifying entries in "Nested related collection". The screen is "Parent collection" entry.
![Image](https://github.com/user-attachments/assets/e5ff4283-bcac-48c1-a9df-7fa03d2b50e0)


I created all relation types so you can see which ones are braking.

Let me know if anyone has a question.

**Comment by Marc-Roig** [comment]
fix should be in the next rc release :)

**Comment by NEDDL** [comment]
@Marc-Roig it's great to hear! :) thank you
