### ISSUE TITLE
Dynamic dropdown/type-ahead from external sources

### ISSUE THREAD

**Issue by dutchakdev** [strapi/strapi#2105]
**What is the expected behavior?**
Load list or type-ahead input from third-party sources.

**Example:**
1. (https://api.github.com/users/dutchakdev/gists)
Create drop-down with name `gist_id` and make map config, to map key-value: `{id, description}`.

2. Render drop-down with items (simple example) (in content-type builder):
```html
<select>
   <option value = "{id}"> {description} </ option>
    ...
</select>
```

3. In content we see 
```
{
...
gist_id={id}
...
}
```

**Additional**
When an endpoint has something like a param, we can do better lazy-load + [type-ahead] (https://twitter.github.io/typeahead.js/)

**Comment by soupette** [comment]
@lauriejim @Aurelsicoko Is it something that we should plan in the core code?

I believe that our new hook system will allow a user to develop such feature really easily.

**Comment by Aurelsicoko** [comment]
@soupette I think we will introduce a new kind of input called "search". It will work as a select input but it will display a dropdown with the type-ahead feature.

We can close it, we won't do it this year though. If you really need this feature, please add your comment below and ping me.
