### ISSUE TITLE
[Strapi 5] Field selection modal not responsive

### ISSUE THREAD

**Issue by mattisvensson** [strapi/strapi#21069]
### Required System information

- Node.js version: v20.13.1
- NPM version: 10.8.2
- Strapi version: 5.0.0-rc.11
- Database: sqlite
- Operating system: Linux/Ubuntu
- Is your project Javascript or Typescript: Typescript
- Browser viewport: 1536 x 864

### Describe the bug

Some fields and buttons are missing in the modal when I try to add a nested component to a component, because the overlay is not fully responsive. This appears only on my notebook. Overflow auto would probaly fix this. 

### Steps to reproduce the behavior

1. Set resolution to 1536 x 864
2. Create a component
3. Select "component" as a field
4. The icons overflow the modal and the buttons at the bottom are not visible

### Expected behavior

The modal is scrollable (or in some other way responsive for notebook screens)

### Screenshots

![strapi5_nested_component](https://github.com/user-attachments/assets/277b8d5f-074d-43d0-9113-231d261de2de)

**Comment by Boegie19** [comment]
Seems to be fixed on latest
