### ISSUE TITLE
Plugin i18n when following localized relations locales dropdown always default

### ISSUE THREAD

**Issue by Xaz16** [strapi/strapi#21064]
### Required System information

- Node.js version: node/v18.16.0
- NPM version: npm/9.5.1
- Strapi version: v4.25.8
- Database: sqlite
- Operating system: linux-x64
- Is your project Javascript or Typescript: js

### Describe the bug

When you follow links from relation field with different than default locale you will see right content, but locales dropdown will be not switched right. As example on recording below I going to de entry with de contnet but locales dropdown is setted in en
![image](https://github.com/user-attachments/assets/d93e5c28-8658-40d3-a9b0-714f8bd82d60)

### Steps to reproduce the behavior

I think it is already good described in bug description, as well all steps was recorded (check it below)

### Expected behavior

When I follwing link from relation field I should see proper locale in locales dropdown

### Screenshots

![Animation1](https://github.com/user-attachments/assets/978bbb31-8f60-45f5-a68b-4b3c5ad39497)

### Code snippets

Repo with reproduce: https://github.com/Xaz16/strapi-locale-issues

### Additional context

No context, it is reproducable from newly created strapi project

**Comment by Xaz16** [comment]
Hello!
Maybe it is not clear or I don't provide something important. Could you elaborate on that issue? It is quite critical for us, and we want to migrate to strapi

**Comment by Xaz16** [comment]
Hello @Convly 
I see that you was last who changed something in i18n plugin, if it possible could you please address your attention to this issue? Looks like critical.
 
Thank you in advance

**Comment by sixtineio** [comment]
Bug confirmed here #20447

**Comment by Xaz16** [comment]
Looks like fixed in V5
