### ISSUE TITLE
[v5] Related entry, after modifying it, returns null on the API call to the parent

### ISSUE THREAD

**Issue by NEDDL** [strapi/strapi#21062]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-rc.11
Node/Yarn Version: npm/10.1.0 node/v20.9.0 darwin arm64 workspaces/false
Edition: Community
Database: postgres

### Describe the bug

I have a relation between a single type and a collection. 

When I modify the entry of a collection that is related to the single type, the API call to this single type returns null for the related entry.

See below the screenshot to explain better:

Home Page is related to Page collection types.
The related Page is **Home**
If I modify Home, I still see the relation on Global single type. Until here there is no problem.

After modifying Home, when I make an API call to get the information, homePage returns null.
If I remove the relation and select Home on the list again, then it fixes.

![Screenshot 2024-08-22 at 21 04 16](https://github.com/user-attachments/assets/0ebefee8-1bfb-46f8-8757-86255cf880ed)

homePage returns null:
<img width="938" alt="Screenshot 2024-08-22 at 21 10 57" src="https://github.com/user-attachments/assets/c6b4ec71-2701-4b67-8dfa-a4bc08f28b9c">

When I remove the relation, publish, and select again, publish, then it fixes:
<img width="910" alt="Screenshot 2024-08-22 at 21 12 17" src="https://github.com/user-attachments/assets/862d4550-0fd1-4839-8e5d-3a69411622c4">

### Steps to reproduce the behavior

1. Create a single type with a relation to a collection
2. Select an entry in the single type from this collection
3. Make a GET API Call to this single type. 
4. You successfully received the related collection.
5. Modify the selected entry of the collection.
6. Make a GET API Call to this single type.
7. The related collection will return **null**

### Expected behavior

As a user, when I make a modification in the related entry of the collection, the data of the relation should maintain in the API call.

**Comment by alexander-aleman** [comment]
Seems similar to my issue https://github.com/strapi/strapi/issues/21054

**Comment by NEDDL** [comment]
@alexander-aleman I saw your video before opening this issue, I thought it was slightly different problem.

But you are right, it is totally related. I just tested and as soon as I make a modification on the related item, it is no longer related in the **published** tab.

**Comment by Boegie19** [comment]
Seems to be fixed on latest
