### ISSUE TITLE
Trying to filter by createdBy or updatedBy won't work beyond the first 10 admin users

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#21079]
### Required System information

- Node.js version: node/v20.11.1
- NPM version: yarn/1.22.22 npm/?
- Strapi version: 4.25.8
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When filtering based on createdBy in the content-manager if you try to filter for an admin user beyond the 10th it isn't found as the search for the filter box is not passing that to the backend, it's only doing it on the data previously fetched which is only the first 10.

### Steps to reproduce the behavior

1. Create a Strapi app
2. Register 11 admin users
3. Create a content-type
4. Add data for the 1st and 11th user
5. Try to filter the data for createdBy is `test11`
6. See that they aren't shown in the list
7. Try to apply the filter and see that nothing happens

### Expected behavior

We should be using the `_q` operator to pass the search input to the backend to grab additional users

### Screenshots

https://www.loom.com/share/77128c2e661342f6bcb263b0020ff5e6?sid=2acee795-6383-4f37-924f-137f6879ae1c

### Code snippets

N/A

### Additional context

Related to TID7760

**Comment by derrickmehaffy** [comment]
While the user reported this issue to us on v4, I can also confirm it on v5

**Comment by alexandrebodin** [comment]
v4 fix was merged

**Comment by alexandrebodin** [comment]
v5 fix was merged too. Closing
