### ISSUE TITLE
Localization Error Strapi 5

### ISSUE THREAD

**Issue by devmoatassem** [strapi/strapi#21076]
### Required System information

- Node.js version:20x
- NPM version: 10.2.3
- Strapi version: 5.0.0-rc.11
- Database: sqlite
- Operating system: Windows 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug
See the random error when creating new localized entry

https://github.com/user-attachments/assets/8a02ec7a-787d-4af9-9e22-26c15d3196d6

### Steps to reproduce the behavior

1. Go to any new collection entry and create basic entry in default localization
2. Click on Urdu localization to create entry for urdu localization you'll receive random errors 
![image](https://github.com/user-attachments/assets/2523d66f-2b0d-4435-9cab-1c32a94cfac2)

### Expected behavior

This should just open the new entry for that localization like it did for english

**Comment by derrickmehaffy** [comment]
fixed in rc.12
