### ISSUE TITLE
Password Reset redirects authenticated users to admin

### ISSUE THREAD

**Issue by hansemannn** [strapi/strapi#2108]
**Informations**
- **Node.js version**: 10.4.1
- **npm version**: 6.4.1
- **Strapi version**: Beta 14.2
- **Database**: MongoDB
- **Operating system**: macOS 

**What is the current behavior?**
When using the password reset link below, the user is redirected into the admin
area, which he/she should not have access to. After trying to click any link then,
an error occurs and nothing works.

**Steps to reproduce the problem**
1. Send a POST request to `http://localhost:1337/auth/forgot-password` with the following body:
```json
{ 
	"email": "john@doe.com", 
	"url": "https://localhost:1337/admin/plugins/users-permissions/auth/reset-password"
}
```

**What is the expected behavior?**
After the password reset, redirect the user either to a specified URL or to the main page. But in any case, do not redirect the user to the /admin area.

**Suggested solutions**
Either add a redirect URL or redirect users based on their roles.

**Comment by Sejori** [comment]
I don't think this issue has been solved. Can we reopen it? 

I am currently trying to change the redirect URI found in the source code here: https://github.com/strapi/strapi/blob/4b2f261604ec367c87d13d140538548789c3b32b/packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/index.js#L73

After changing '/plugins/users-permissions/auth/login' to 'https://www.example.com' users are still redirected to the Strapi admin login page. 

Redirect URI after email confirmation is editable in the 'Advanced Settings' tab in the Roles & Permissions tab. I haven't tested this as not using email confirmation yet but I would have though password reset redirect URI would be found there too.

**Comment by lauriejim** [comment]
Exactly! it's a misstake with a commit link.

**Comment by codypersinger** [comment]
I'm having a hard time understanding what the actual issue is based on the description and my investigation. I can see the problem is regarding users who are not administrators being redirected to an admin url, but I'm not clear on the exact steps to reproduce the issue. Does this occur _after_ landing on a reset-password page and completing the form to set a new password?

**Comment by Sejori** [comment]
This occurs after completing the form to reset password. 

The flow is as follows: 
User enters email address and clicks reset password link on Client (frontend app) -> 
Client sends email address as parameter to Strapi (backend app) /auth/forgot-passward endpoint -> 
Strapi sends password reset link to given email address -> 
User clicks link in email from Strapi and is directed to Stapi reset password webpage -> 
User inputs new password, submits --(error occurs here)-> 
User is directed to Strapi admin login and cannot be directed to Client login.

**Comment by lauriejim** [comment]
Hello!
We are working on the split of Users and Admin.
So you will have the API available to reset password of Users and you will have to implement an UI in your application. And one for the Admin.
Admin will always redirect to the admin so this issue have to be closed.

In any case thank you for your feedback.

**Comment by MatheusRV** [comment]
Plase remove from https://github.com/strapi/strapi/projects/22#card-19380411
