### ISSUE TITLE
strapi.entityService.findMany() always returns 1 record with locale='en' using strapi-translate-plugin

### ISSUE THREAD

**Issue by fmlukaszmatusik** [strapi/strapi#21095]
### Required System information

- Node.js version: 18.20.4
- NPM version: we use yarn
- Strapi version: 4.25.8
- Database: PostgreSQL
- Operating system: macos
- Is your project Javascript or Typescript: TS

### Describe the bug

This is what I have in a table responsible for holding api::test.test (table name: 'test')

![Screenshot 2024-08-28 at 11 24 36](https://github.com/user-attachments/assets/896c3763-0d90-48c8-aa13-b5d90323e03e)

This is my code snippet

```
console.log('contentType', contentType);
  console.log('findMany', await strapi.entityService.findMany(contentType));
  console.log('populated findMany', await strapi.entityService.findMany(contentType,
    {
      filters: {
        locale: 'pl',
      },
      // populate: dotSeparatedComponentNames
    }
  ));
```

And this is a result

```
contentType api::test.test
findMany [
  {
    id: 49,
    description: [ [Object] ],
    asd: 'Whenever',
    createdAt: '2024-08-28T06:36:43.773Z',
    updatedAt: '2024-08-28T08:38:48.634Z',
    publishedAt: '2024-08-28T06:36:44.415Z',
    locale: 'en'
  }
]
populated findMany []
```

As you can see, `findMany(contentType)` - solely - returns only one record from DB. Always returns it for `locale='en'`. When I put any other locale to filter param, it returns `[]`.

I do this queries inside function in middleware, I intercept request from strapi-plugin-translate as I am trying to implement richtext translations. But this should not matter as entityService.findMany() should return all the entires for this **collection type** (this is not a single type).

### Steps to reproduce the behavior

1. Install `strapi-plugin-translate`, which will add "locale" into your tables.
2. Add two records to any table holding values for any collection type (e.g. 'test')
3. Query strapi.entityService.findMany('test') <- put your schema uuid
4. See the result.

### Expected behavior

findMany (especially without any other params) should return all the records from DB for given collection type uuid.

It works through `strapi.db.entityManager.findMany()` but populate does not work there, meaning I cannot get nested component. 

### Possible solution?

It seems additional locales are added to - for api::test.test - DB table 'test'. I see one entity in CMS with many locales. May entityService returns always this "main locale" entity? If yes, how can I possibly query other locales with `populate` option?

**Comment by tomaszdziedzio** [comment]
Same issue

**Comment by 2Bartek2** [comment]
Same issue

**Comment by derrickmehaffy** [comment]
This issue is with a plugin that we don't maintain, I'd advise contacting the author.
