### ISSUE TITLE
[Strapi 5] Can't edit field in view configuration

### ISSUE THREAD

**Issue by mattisvensson** [strapi/strapi#21093]
### Required System information

- Node.js version:  v20.15.0
- NPM version: 10.7.0
- Strapi version: 5.0.0-rc.11
- Database: sqlite
- Operating system: Linux/Ubuntu
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

I can't update the view for a field in the "Configure the view" page. When I click on the pen icon, the modal opens for a split-second and then closes again. A toast with "Success: saved" is displayed and some http request are made to the backend.

### Steps to reproduce the behavior

1. Create a collection or single type
2. Add any field
3. Create a new entity and go to the "Configure the view" page
4. Click on the pen icon on the field.

### Expected behavior

Modal to edit the field view opens

**Comment by derrickmehaffy** [comment]
Should be fixed in v5 stable, marking as closed
