### ISSUE TITLE
Help replace Text Editor default in strAPI with CKEditor

### ISSUE THREAD

**Issue by cuvanhung** [strapi/strapi#2111]
**Informations**
- **Node.js version**: 8.12.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: MongoDB
- **Operating system**:  Windown 10 Home

Hi everyone, my English is not good. 

I want to replace Text Type default in strapi with CK Editor. But i can not find documentation to help. Please help me how to replace Text Editor Type Default ( StrAPI) with CKeditor. Thanks so much

**Comment by soupette** [comment]
You will need to replace the [WYSIWYG component](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg) with the [CK Editor)(https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)

**Comment by cuvanhung** [comment]
> You will need to replace the [WYSIWYG component](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/admin/src/components/Wysiwyg) with the [CK Editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)

Thanksyou so much. But i dont know how to replace the WYSIWYG component with CK Editor. I can find any document guide . Can you guide me?

**Comment by soupette** [comment]
@cuvanhung here are my thoughts on how to change the current editor:

## 1. Create a dev application 

[Please refer to this issue](https://github.com/strapi/strapi/issues/1943#issuecomment-430533710)

## 2. Install CKEditor

```
# In your dev app
$ cd my-app/plugins/content-manager
$ npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic
```

## 3. Create the following structure

```
- my-app
 └─ admin
 └─ plugins
        └─ content-manager
               └─ admin
                      └─ src
                            └─ components
                                   └─ Edit // This one already exists
                                   └─ CKEditor
                                          └─ index.js
                                          └─ styles.scss // If needed
                                   └─ CKEditorWithErrors
                                          └─ index.js
                                          └─ styles.scss
```

## 4. Create the CKEditorWithError

This component should be the wrapper of the CKEditor which handles the :
- `<Label />`
- `<CKEditor />`
- `<InputDescription />`
- `<InputErrors />`

**NOTE :**

You have access to these `props` from the `Edit` component:

```
CKEditorWithErrors.propTypes = {
  autoFocus: PropTypes.bool,
  className: PropTypes.string,
  customBootstrapClass: PropTypes.string,
  deactivateErrorHighlight: PropTypes.bool,
  didCheckErrors: PropTypes.bool,
  disabled: PropTypes.bool,
  errors: PropTypes.array,
  errorsClassName: PropTypes.string,
  errorsStyle: PropTypes.object,
  inputClassName: PropTypes.string,
  inputDescription: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
    PropTypes.shape({
      id: PropTypes.string,
      params: PropTypes.object,
    }),
  ]),
  inputDescriptionClassName: PropTypes.string,
  inputDescriptionStyle: PropTypes.object,
  inputStyle: PropTypes.object,
  label: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
    PropTypes.shape({
      id: PropTypes.string,
      params: PropTypes.object,
    }),
  ]),
  labelClassName: PropTypes.string,
  labelStyle: PropTypes.object,
  name: PropTypes.string.isRequired,
  noErrorsDescription: PropTypes.bool,
  onBlur: PropTypes.oneOfType([
    PropTypes.bool,
    PropTypes.func,
  ]),
  onChange: PropTypes.func.isRequired,
  placeholder: PropTypes.string,
  resetProps: PropTypes.bool,
  style: PropTypes.object,
  tabIndex: PropTypes.string,
  validations: PropTypes.object,
  value: PropTypes.string.isRequired,
};
```

You can refer to this [file](https://github.com/strapi/strapi/blob/add-description-to-plugins-routes/packages/strapi-plugin-content-manager/admin/src/components/WysiwygWithErrors/index.js#L118) to see which props you should pass to the `CKEditor`.

## 5. Implement the CKEditor

Please refer to the [documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) for this part.

## 6. Change the default WYSIWYG

In the `Edit` component 
```
// ...
import CKEditorWithErrors from 'components/CKEditorWithErrors;

class Edit extends React.Component {
  // ...

  renderAttr = (attr, key) =>{
    // ...

    return (
     <Input
        // ...
        customInputs={{ json: InputJSONWithErrors, wysiwyg: CKEditorWithErrors }} // Change this line
        // ...
      />
    );
  }
```
---

## NOTES

**I haven't tried to implement it so the best I can do is give you these guidelines. According to the documentation you might need to change the `webpack` configuration. It's located in this [package](https://github.com/strapi/strapi/tree/add-description-to-plugins-routes/packages/strapi-helper-plugin/lib/internals)**

*If you need to change the `webpack` configuration you will need to install the `ckeditor` in the `strapi-helper-plugin`*

Add the following after this [line](https://github.com/strapi/strapi/blob/add-description-to-plugins-routes/packages/strapi-helper-plugin/lib/internals/webpack/webpack.dev.babel.js#L218)

```
// ...
{
  'react-dnd-html5-backend': path.resolve(
      rootAdminpath,
      'node_modules',
      'strapi-helper-plugin',
      'node_modules',
      'react-dnd-html5-backend',
    ),
   '@ckeditor/ckeditor5-react': path.resolve(
      rootAdminpath,
      'node_modules',
      'strapi-helper-plugin',
      'node_modules',
      '@ckeditor/ckeditor5-react',
    ),
    '@ckeditor/ckeditor5-build-classic': path.resolve(
      rootAdminpath,
      'node_modules',
      'strapi-helper-plugin',
      'node_modules',
      '@ckeditor/ckeditor5-build-classic',
    ),
}
```

Same in this [file](https://github.com/strapi/strapi/blob/add-description-to-plugins-routes/packages/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js#L236-

```
{
   // ..
    'styled-components': path.resolve(
      rootAdminpath,
      'node_modules',
      'strapi-helper-plugin',
      'node_modules',
      'styled-components',
    ),
   '@ckeditor/ckeditor5-react': path.resolve(
      rootAdminpath,
      'node_modules',
      'strapi-helper-plugin',
      'node_modules',
      '@ckeditor/ckeditor5-react',
    ),
    '@ckeditor/ckeditor5-build-classic': path.resolve(
      rootAdminpath,
      'node_modules',
      'strapi-helper-plugin',
      'node_modules',
      '@ckeditor/ckeditor5-build-classic',
    ),
```

And finally in the [webpack dll](https://github.com/strapi/strapi/blob/add-description-to-plugins-routes/packages/strapi-helper-plugin/lib/internals/webpack/webpack.dll.babel.js#L72)

```
// ...
{
    'styled-components': path.resolve(rootAdminpath, 'node_modules', 'strapi-helper-plugin', 'node_modules', 'styled-components'),
    },
    '@ckeditor/ckeditor5-build-classic': path.resolve(rootAdminpath, 'node_modules', 'strapi-helper-plugin', 'node_modules', '@ckeditor/ckeditor5-build-classic'),
    },
  '@ckeditor/ckeditor5-react': path.resolve(rootAdminpath, 'node_modules', 'strapi-helper-plugin', 'node_modules', '@ckeditor/ckeditor5-react),
    },
```

Don't hesitate if you need a bit more guidelines.

**Comment by buixuanlam** [comment]
@soupette Thanks for your instructions! I followed each step in the tutorial but I am having difficulty in step 5: implements the ckeditor. You can provide more detailed instructions on step 5? Thank you!

**Comment by derrickmehaffy** [comment]
@HoangDinhVan see Soupette's above comment for instructions, this is not an easy process and is beyond the scope of this github issue. Issues are related to Strapi core, modifications are not.

**Comment by cuvanhung** [comment]
sorry. My English is not good. i have issue that when i used postman to get data from sever. It return markdown text format not html code format. So my front-end team can not work with it. i want to get html code format from server. i try replace Wysiwyg by CKEditor. But not easy. i can't do it. Please help me how to get html code format from Wysiwyg of strapi. Thanks a lot.

**Comment by soupette** [comment]
@cuvanhung why don't you try to convert the markdown to html?

**Comment by Dogtiti** [comment]
so who has successfully solved it? 
I have trouble in replacing it with CKEditor,who can show more details?
Thanks so much !

**Comment by derrickmehaffy** [comment]
@dottgonzo The issue here is that it is not good practice to store direct html in a database.

1) It's bit and bloated, taking up far more space than just standard markdown
2) It opens up to security concerns on malicious html being loaded on the frontend
3) It's a very ugly solution and is difficult to maintain.

Markdown is being used because it basically looks like normal text and is much smaller. There are hundreds of tools and scripts that can automate converting from markdown to html. Most WYSIWYG do not store text in html format. The literal meaning of WYSIWYG is "What you see is what you get".

If you want a better solution, then I urge you to fork it yourself and build it yourself. :smiley:

**Comment by cuvanhung** [comment]
Hi. Thank you so much @sdubrez  and @derrickmehaffy . I followed your instructions and have successfully implemented. I have replace the WYSIWYG component with the CK Editor successed.  But I have a problem saving the data. After I entered the data it was not saved. 
Example :" If I write text then i choose "save" . It not save.  Check out my pictures for more information. Help me please. Sorry for my English not good. Thank you. 
![22222](https://user-images.githubusercontent.com/43987276/48655976-7d493380-ea51-11e8-81dc-ca39893a5208.png)

**Comment by Dogtiti** [comment]
@cuvanhung I have successfully replace it with CKEditor,also it can save.Here is some details maybe can help you .However,I think the CKEitor's upload is so complicated，and I was failed to upload successfully.So I replace CKEditor with other `WYSIWYG Editor`,this is all the details I can remember with CKEditor.


`CKEditor(index.js)`

```
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

 class App extends Component {

const onChange=()=>{
this.props.onChange({
            target: {
                name: this.props.name,
                type: this.props.type,
                value: this.props.value
            }
        })
}

   render() {
   return (
<div className="App">
      <CKEditor
       editor={ ClassicEditor }
       onChange={onChange}
       ref={this.props.setRef}
        />
 </div>
);
}
}

App.defaultProps = {
    setRef: () => { },
    onChange: () => { },
    name: "",
    type: "",
    value: "",
};

export default App; 
```
`Edit (index.js)`

```
import React from 'react';
import PropTypes from 'prop-types';
import {
findIndex,
get,
has,
isEmpty,
isFunction,
upperFirst,
} from 'lodash';
// You can find these components in either
// ./node_modules/strapi-helper-plugin/lib/src
// or strapi/packages/strapi-helper-plugin/lib/src
import Input from 'components/InputsIndex';
import InputJSONWithErrors from 'components/InputJSONWithErrors';
import CKEditorWithErrors from 'components/CKEditorWithErrors';
import styles from './styles.scss';

const getInputType = (type = '') => {
switch (type.toLowerCase()) {
case 'boolean':
return 'toggle';
case 'bigint':
case 'decimal':
case 'float':
case 'integer':
return 'number';
case 'date':
case 'datetime':
return 'date';
case 'email':
return 'email';
case 'enumeration':
return 'select';
case 'password':
return 'password';
case 'string':
return 'text';
case 'text':
return 'textarea';
case 'file':
case 'files':
return 'file';
case 'json':
return 'json';
default:
return 'text';
}
};

class Edit extends React.Component {
getInputErrors = (attr) => {
const index = findIndex(this.props.formErrors, ['name', attr]);
return index !== -1 ? this.props.formErrors[index].errors : [];
}

/**
* Retrieve the Input layout
* @param {String} attr [description]
* @return {Object} Object containing the Input's label customBootstrapClass, ...
*/
getInputLayout = (attr) => {
const { layout } = this.props;

return Object.keys(get(layout, ['attributes', attr], {})).reduce((acc, current) => {
acc[current] = isFunction(layout.attributes[attr][current]) ?
layout.attributes[attr][current](this) :
layout.attributes[attr][current];

return acc;
}, {});
};

/**
* Retrieve the input's validations
* @param {String} attr
* @return {Object}
*/
getInputValidations = (attr) => {
const { formValidations } = this.props;
const index = findIndex(formValidations, ['name', attr]);

return get(formValidations, [index, 'validations'], {});
}

/**
* Retrieve all relations made with the upload plugin
* @param {Object} props
* @return {Object}
*/
getUploadRelations = (props) => (
Object.keys(get(props.schema, 'relations', {})).reduce((acc, current) => {
if (get(props.schema, ['relations', current, 'plugin']) === 'upload') {
acc[current] = {
description: '',
label: upperFirst(current),
type: 'file',
};
}

return acc;
}, {})
)

fileRelationAllowMultipleUpload = (relationName) => has(this.props.schema, ['relations', relationName, 'collection']);

orderAttributes = () => get(this.props.schema, ['editDisplay', 'fields'], []);

renderAttr = (attr, key) => {
if (attr.includes('__col-md')) {
const className = attr.split('__')[1];

return <div key={key} className={className} />;
}

const details = get(this.props.schema, ['editDisplay', 'availableFields', attr]);
// Retrieve the input's bootstrapClass from the layout
const layout = this.getInputLayout(attr);
const appearance = get(layout, 'appearance');
const type = !isEmpty(appearance) ? appearance.toLowerCase() : get(layout, 'type', getInputType(details.type));
const inputDescription = get(details, 'description', null);
const inputStyle = type === 'textarea' ? { height: '196px' } : {};
let className = get(layout, 'className');

if (type === 'toggle' && !className) {
className = 'col-md-4';
}

const onChange = (v) => {
      this.props.onChange(v)
    }

return ( 
<Input
autoFocus={key === 0}
customBootstrapClass={className}
customInputs={{ json: InputJSONWithErrors, wysiwyg: CKEditorWithErrors }}
didCheckErrors={this.props.didCheckErrors}
disabled={!get(details, 'editable', true)}
errors={this.getInputErrors(attr)}
inputDescription={inputDescription}
inputStyle={inputStyle}
key={attr}
label={get(layout, 'label') || details.label || ''}
multiple={this.fileRelationAllowMultipleUpload(attr)}
name={attr}
onBlur={this.props.onBlur}
onChange={onChange}
placeholder={get(layout, 'placeholder') || details.placeholder || ''}
resetProps={this.props.resetProps}
selectOptions={get(this.props.attributes, [attr, 'enum'])}
type={type}
validations={this.getInputValidations(attr)}
value={this.props.record[attr]}
/>
);
}

render(){
return (
<div className={styles.form}>
<div className="row">
{this.orderAttributes().map(this.renderAttr)}
</div>
</div>
);
}
}

Edit.defaultProps = {
attributes: {},
formErrors: [],
formValidations: [],
layout: {},
onBlur: () => {},
onChange: () => {},
record: {},
resetProps: false,
schema: {},
};

Edit.propTypes = {
attributes: PropTypes.object,
didCheckErrors: PropTypes.bool.isRequired,
formErrors: PropTypes.array,
formValidations: PropTypes.array,
layout: PropTypes.object,
onBlur: PropTypes.func,
onChange: PropTypes.func,
record: PropTypes.object,
resetProps: PropTypes.bool,
schema: PropTypes.object,
};

export default Edit;
```
