### ISSUE TITLE
High CVE vulenrabilites in 4.25.8 

### ISSUE THREAD

**Issue by piotrwalczak1** [strapi/strapi#21128]
## Bug report
Strapi dependenices have high severity audit issues.

### Required System information

- Node.js version: v18.0
- NPM version: 10.1.0
- Strapi version: 4.25.8
- Database: postgres
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug
running npm audit @strap/strapi package has high serverity vulenrabilites

```
@strapi/strapi:

Affected by vulnerabilities in axios, ws, tar, and other dependencies.
@strapi/admin:

Affected by vulnerabilities in axios, and possibly indirectly by other dependencies.
@strapi/plugin-content-type-builder:

Affected by vulnerabilities in axios and braces.
@strapi/plugin-email:

Affected by vulnerabilities in axios.
@strapi/plugin-upload:

Affected by vulnerabilities in axios.
@strapi/plugin-users-permissions:

Affected by vulnerabilities in axios.
@strapi/plugin-i18n:

Affected by vulnerabilities in axios.
@strapi/helper-plugin:

Affected by vulnerabilities in axios.
@strapi/cloud-cli:

Affected by vulnerabilities in axios and tar.
@strapi/generators:

Affected by vulnerabilities in braces.
@strapi/data-transfer:

Affected by vulnerabilities in tar and ws.

```

### Steps to reproduce the behavior
run npm audit

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
Thanks for the report but we have dependabot, we will get to them once we can but for now none of those actually impact us.
