### ISSUE TITLE
Edit date and save in content manager causing infinite loop in browser

### ISSUE THREAD

**Issue by butcherZ** [strapi/strapi#21157]
### Required System information

Node.js version: v20.17.0
NPM version: 10.8.2
Strapi version: v5.0.0-rc.14
Database: sqlite
Operating system: MacOS 14.6.1 (23G93)
Is your project Javascript or Typescript: TypeScript

### Describe the bug

When creating a new entry in a collection with `date` or `datetime` type, editing the date will cause an infinite loop in the browser and can cause browser freeze.

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Click on Any collection that has a date field with `date` or `datetime` type, create a new entry.
3. entry is now correctly created,
4.  right click to check the console in browser, try to update the date or time value
5. See error

### Expected behavior

document being updated without causing browser freeze

### Screenshots

<img width="390" alt="Screenshot 2024-09-05 at 14 34 28" src="https://github.com/user-attachments/assets/f6bbd59a-1dff-44b2-a08f-da83a77cb10b">

### Additional context
this warning is also shown in the terminal.
<img width="603" alt="Screenshot 2024-09-05 at 14 37 51" src="https://github.com/user-attachments/assets/c74f7106-9491-4c10-9c50-006a77f713ce">

However, even with the errors in the console, the updated value seemed to be saved correctly.
Also, field with only `time` type works perfectly fine here.

**Comment by oiorain** [comment]
Hey @simotae14 , can i close this issue?

**Comment by simotae14** [comment]
nope, the PR is still in review and we need to QA it carefully
