### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'getIn' of undefined" when loading new Content Model

### ISSUE THREAD

**Issue by rw3iss** [strapi/strapi#2115]
**Informations**
- **Node.js version**:  v10.11.0
- **npm version**: v6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: postgresql
- **Operating system**: mac osx high sierra

**What is the current behavior?**
Made a new content type, then tried to add new content in the Content Manager, but the page won't load, gives console error:
![screen shot 2018-10-09 at 12 42 46](https://user-images.githubusercontent.com/372120/46684677-8e389680-cbc1-11e8-96f1-84b15ffe5d95.png)

    main.js:16 TypeError: Cannot read property 'getIn' of undefined
        at e.value (main.js:66)
        at main.js:66
        at We.__iterate (main.js:6)
        at We.forEach (main.js:6)
        at e.value (main.js:66)
        at new e (main.js:66)
        at main.js:60
        at Me (main.js:6)
        at Me (main.js:6)
        at Me (main.js:6)

**Steps to reproduce the problem**
    Make a new content type with two string fields, save, then go to Content Manager and click on the new type in the list...

**What is the expected behavior?**
   Clicking on the new type should load the page to add new content for it.

**Suggested solutions**
    Not sure where these JS errors are coming from. Maybe it's an issue with using postgresql, tried mysql but it wouldn't connect no matter host/port/user/pass.

**Comment by derrickmehaffy** [comment]
@rw3iss did you update from a previous version? Try deleting your content-manager_schema entry in the `core_store` table.

Also with MySQL did you create a database, user, and give permissions?

**Comment by rw3iss** [comment]
No this is a totally new installation.

With mysql I have the DB, and the user and password works for the rest of my apps, and command line... 

I removed the key='plugin_content-manager_schema' entry in the core_store table and that seemed to have fixed the issue! New content types are working, must have been an initial setup kinda bug or something...

**Comment by sgrund14** [comment]
@derrickmehaffy @rw3iss I'm getting this error too, but using a MongoDB database. `Cannot read property 'getIn' of undefined`. It's also a completely new installation. Happening when I click on a new content type I've created from the content manager.

**Comment by lauriejim** [comment]
You tried with fresh new app and fresh new database ?

**Comment by rcpassos** [comment]
Some problem here using MySQL database

**Comment by rw3iss** [comment]
> You tried with fresh new app and fresh new database ?
> 
> I'm not able to reproduce your issue with fresh new app and fresh new database.

Hi lauriejim, could you please tell me your exact environment setup, OS, npm version, node version, db version, etc?

**Comment by jacargentina** [comment]
Can be related to #2186, fix here https://github.com/strapi/strapi/pull/2203

**Comment by soupette** [comment]
@brandonin do you have repo that I can check?

**Comment by donaldr** [comment]
Actually, it happens when you try to create a camelCase entry.

**Comment by lauriejim** [comment]
And please use lowercase keys for now.

**Comment by adrianoresende** [comment]
@lauriejim Why don't add validation in field or save with lowercase or camelCase?

**Comment by derrickmehaffy** [comment]
@adrianoresende "WIP" You're more than welcome to submit a PR though to help out! :smiley:

**Comment by craftery** [comment]
> Actually, it happens when you try to create a camelCase entry.

For the record it also happens with underscores in field names. Although tedious, as henrych4 says you can amend the core collection (make fields lowercase) to work around the problem.

**Comment by cayrescript** [comment]
> @rw3iss did you update from a previous version? Try deleting your content-manager_schema entry in the `core_store` table.
> 
> Also with MySQL did you create a database, user, and give permissions?

Ty, It's works for me!

**Comment by cpres** [comment]
I was getting this for having an underscore for one of my collections in mongo
