### ISSUE TITLE
Error When Modifying Records Post-Migration to Strapi 5 

### ISSUE THREAD

**Issue by vinda2401** [strapi/strapi#21166]
Required System information
Node.js version: 18+
NPM version: 18.6
Strapi version: 5.0.0-rc.15
Plugin version:
Database: mysql
Operating system: Ubuntu 22.04.4 LTS

Describe the bug
We migrated  to Release Candidate 15. The migration went smoothly, and strapi is now operational.

We are preparing for the V5 migration and need to make some adjustments to the old data. But when I try to modify a record, I get this error.

To determine what is causing the problem, we searched for the document ID displayed in the warning pop up, which corresponds to the database table 'upload_folders'.

Steps to reproduce the behavior
Prerequisite: Perform migration from v4 to rc.15.

- Open a collection containing images.
- Click to open a record in editing mode. 
- Try changing any of the details, then save or publish.
- A warning pop-up will appear, as illustrated in the screenshot below.

Expected behavior
It should have saved the record, without showing error.

Screenshots

![image](https://github.com/user-attachments/assets/572c0841-9fb5-46d7-bca0-321c269007ff)

**Comment by laurenskling** [comment]
Just had the same error when changing or adding a image

**Comment by vinda2401** [comment]
@innerdvations @laurenskling 
This seems like an blocker for us. Is this scheduled to be resolved soon?

**Comment by alexandrebodin** [comment]
@vinda2401 There hae been multiple new rc release that fixed the localization migrations. 

Make sure to migrade your app again from the original database backup when testing a new rc.

**Comment by laurenskling** [comment]
@alexandrebodin just tested with rc 29, still happening.

**Comment by alexandrebodin** [comment]
We are going to need some more information to reproduce this issue. Could you share a reproduction repo with a v4 dataset so we could replicate your process ?

**Comment by laurenskling** [comment]
Now tested with 5.0.0 ;) 
It's happening on media _in folders_ after a migration. Outside of folders it doesn't happen. I'm trying my best to get a steady reproduction happening.

**Comment by vinda2401** [comment]
@alexandrebodin 
is this getting picked up soon?

**Comment by laurenskling** [comment]
seems to be fixed in 5.0.4! <3
