### ISSUE TITLE
[v5.rc15] Cannot publish the other locale without saving first

### ISSUE THREAD

**Issue by NEDDL** [strapi/strapi#21164]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-rc.15
Node/Yarn Version: npm/10.1.0 node/v20.9.0 darwin arm64 workspaces/false
Edition: Community
Database: postgres

### Describe the bug

I cannot Publish an entry after I fill in from the main locale to another locale. If I save it before publishing it, it works.

Edit: Actually it is not related to fill in from the other locale. Even if you fill by yourself, publishing without saving causes this error.

### Steps to reproduce the behavior

1. Create and entry with 2 locales
2. Fill the initial locale.
3. Fill in the second locale from the other one.
4. Try to publish it without saving
5. See the error

### Expected behavior

It should publish directly without needing to save it first.

### Screenshots

https://github.com/user-attachments/assets/d0ae1b61-abd3-47b8-94c3-0f11fe5c5573

**Comment by derrickmehaffy** [comment]
Tested on v5.1.1 and cannot reproduce so will go ahead and mark as closed

![image](https://github.com/user-attachments/assets/59e2035d-6bfe-4fd1-9f3a-ba8baa2f9697)
![image](https://github.com/user-attachments/assets/55760b13-4345-4014-a730-05483e0788fe)

**Comment by derrickmehaffy** [comment]
Tested on v5.1.1 and could not reproduce, so I'll go ahead and mark this one as resolved.
