### ISSUE TITLE
sql query cacheing with redis

### ISSUE THREAD

**Issue by labolado** [strapi/strapi#2117]
Is it possible cache sql query with redis?

**Comment by labolado** [comment]
In production it's common to have a redis server working as cache between application servers and database server:

app1, app2, app3... ------> cache in memory/redis/.. ------> database server

**Comment by hyingreborn** [comment]
need it too...

**Comment by lauriejim** [comment]
Thank you for this feedback.
Actually you have to check `ioredis` options for that or in your redis server.
