### ISSUE TITLE
I see the review workflows injection zone even if its not enabled for the content type

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21172]
### **Steps to reproduce**
- You will need a Strapi paid license
- Go to a content-type without review workflows enabled
- Go to an entry of this content-type
- See the review workflows box available

### **Expected behavior**

Review workflows assignee & stage dropdowns should only be visible when the content type is assigned to a workflow, not always.

### **Screenshots**

![Image](https://github.com/user-attachments/assets/16aca96d-a52e-4019-be5f-9abbeb44a3f9)

**Comment by Marc-Roig** [comment]
This looks fixed ot me , @yanniskadiri could you try to replicate at some point if you have time? 🙏

**Comment by yanniskadiri** [comment]
I checked and I confirm it's fixed, thanks for having a look!
