### ISSUE TITLE
Content history fields don’t have the right size

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21176]
### **Steps to reproduce**
- Edit an entry with media inputs, relations and dynamic zones
- Go to the history (you will need a paid license)
- See that the fields are not given the space they should have and the DZ when closed don't use the whole space

### **Expected behavior**

- Content history fields should fill the space they’re given
- The custom relation and media inputs should be block type, not inline
- The DZ should be full width when a component is opened and closed

### **Screenshots**

![Image](https://github.com/user-attachments/assets/7e993cb3-88b6-4cea-9944-a9deeb38104c)

https://github.com/user-attachments/assets/766edaf2-9cfb-4d2e-b714-4c57bb7e9787

**Comment by lucasboilly** [comment]
@yanniskadiri this one is fixed right?

**Comment by yanniskadiri** [comment]
Yes I'll close it thanks!
