### ISSUE TITLE
The confirmation message doesn’t make sense if D&P is not enabled

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21175]
### **Steps to reproduce**
- Edit an entry of a content-type without D&P enabled
- Go to the content history of this entry (you will need a paid license)
- Restore a past version of the entry
- See the notification saying that the version was restored on top of a published one

### **Expected behavior**

The notification should just say that a past version was restored and not say that it's not published yet.

### **Screenshots**

![Image](https://github.com/user-attachments/assets/c67f8b96-d7cb-47e1-b50c-b3e53e9b4dbf)

**Comment by sg1asgard** [comment]
@yanniskadiri  The issue is closed now.
https://github.com/strapi/strapi/pull/22223
