### ISSUE TITLE
strapi transfer Command Fails with Integer Syntax Error in *_localizations_lnk Tables After Upgrading to rc.17

### ISSUE THREAD

**Issue by tammyhart** [strapi/strapi#21189]
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-rc.17
- Node/Yarn Version: yarn/1.22.22 npm/? node/v20.17.0 darwin arm64
- Edition: Community
- Database: sqlite

### Describe the bug

Running the `strapi transfer` command failed due to an attempt in insert data into *_localizations_lnk tables. The transfer is trying to insert a record using the `document_id` **string** where the table is expecting an **integer**, probably the `id` of that record.

I wasn't able to track down which release candidate introduced these tables, but this error started after upgrading from rc.13 to rc.17. I've rolled back to rc.13 for now to avoid the transfer error.

Error:
```error: [ERROR] insert into "i_18_n_locale_localizations_lnk" ("inv_locale_id", "locale_id", "locale_ord") values ($1, $2, $3) - invalid input syntax for type integer: "fzgtea87itb49x4u767jav50"```

### Steps to reproduce the behavior

1. run `strapi transfer` CLI command
2. See error

### Expected behavior

Transfer data without errors

### Additional context

- I am only using English
- All of my *_localizations_lnk tables are empty locally, so not sure why the transfer is trying to insert records into them

**Comment by paweszw608** [comment]
Same here on 5.0.0-rc.20. 
Bug also exists when transferring files:
 
`[ERROR] insert into "public"."files_localizations_lnk" ("file_id", "file_ord", "inv_file_id") values ($1, $2, $3) - invalid input syntax for type integer: "ei47bv4wrto59dmt605tm33i"`
