### ISSUE TITLE
[RW] Sort by stage in List view is broken

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21180]
https://www.notion.so/strapi/RW-Sort-by-stage-in-List-view-is-broken-ef2fc005a4304b1ba29634519ec60d40?pvs=4

**Comment by simotae14** [comment]
We have the same issue even when we try to sort by Assignee

**Comment by simotae14** [comment]
fixed with this PR https://github.com/strapi/strapi/pull/21198
