### ISSUE TITLE
 Migration core::5.0.0-discard-drafts (up) crashes on restricted keywords (like: 'to')

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#21185]
### Required System information

- Node.js version: 18
- Strapi version: 5 rc 17
- Database: sqlite
- Operating system: macos
- Is your project Javascript or Typescript: js

### Describe the bug

After https://github.com/strapi/strapi/issues/20225, this migration crashes again for me.

Migrating from v4 to v5 crashes core::5.0.0-discard-drafts, because it doesn't escape the values on this line: https://github.com/strapi/strapi/blob/46d57caa24827fde44e3cce8d2300acddae1c288/packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts#L80
I have a form model with a `to` field. `to` is a restricted keyword in an SQL statement.

### Steps to reproduce the behavior

1. create a v4 with a model that has a `to` field.
2. migrate to 5.
3. MigrationError.

### Expected behavior

no Error.

### Screenshots

<img width="1388" alt="Scherm­afbeelding 2024-09-07 om 13 05 43" src="https://github.com/user-attachments/assets/b85e379f-0bb5-432f-8b8e-a0f0f277da9b">

**Comment by innerdvations** [comment]
Merged #21247 with fix, will be in next RC
