### ISSUE TITLE
Models not returning images on relations

### ISSUE THREAD

**Issue by Moldieman** [strapi/strapi#2118]
**Informations**
- **Node.js version**: 10
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: MySQL 5.7.23
- **Operating system**: osx10.9 

**What is the current behavior?**

Images / Media are not being returned on relational models.

**Steps to reproduce the problem**

Create 2 models, call one products and the other brands. Have multiple images on a single product and then associate that product to a single brand (one-to-one). Try query the API for brands and the associated products images are not returned or even come back as NULL.

**What is the expected behavior?**

All media and images that are associated to the models should be returned in the response.

**Suggested solutions**

Spoken with @derrickmehaffy about this and he also has more clarity on the issue.

**Comment by filipburian** [comment]
Same here

**Comment by Moldieman** [comment]
@lauriejim any progress with this? I would really like to finish off my app and deploy to production 👍

**Comment by Moldieman** [comment]
Hey @lauriejim unfortunately I haven't been able to get this working. Is there anyway you could steer me in the right direction so I can get images/media? 

```fetch: params => {
    // Select field to populate.
    const populate = Brand.associations.filter(ast => ast.autoPopulate !== false).map(ast => ast.alias)

    return Brand.forge(_.pick(params, 'id')).fetch({
      withRelated: populate,
      // I need this to also return the images,
      // it currently returns everything related to the product expect the images
    });
  },```

My relational model is called product but I can't seem to get any media from product to display.

Thanks

**Comment by Moldieman** [comment]
@lauriejim any update on the relational image data being returned? I am really really stuck and can't move on with my project unless I get past this issue. Thx

**Comment by Moldieman** [comment]
Hello @lauriejim 
Can you please assist me with this issue. I have got so far into this project already and just need the media / images to be included in the API call as described above. I would really appreciate it if you could steer me in the right direction to get this working or give me some examples to try get it working.

Thanks

**Comment by derrickmehaffy** [comment]
Users still reporting issues with this on slack and on the PR.

@lauriejim

**Comment by lauriejim** [comment]
@derrickmehaffy Do you have the steps to reproduce ?

**Comment by tomsutton1984** [comment]
> @derrickmehaffy Do you have the steps to reproduce ?

@lauriejim - I'm see this issue on 3.0.0-alpha25.2 

Steps to replicate:

1. New Strapi install using MongoDB / Cosmos DB Mongo Driver
2. Add a new Content Type "Company"
3. Add a media field "logo"
4. Add new company and upload a logo
5. Call /companies API, the logo field is null

**Comment by polgiron** [comment]
Hello I have a similar problem.

I've just installed a fresh strapi from your getting started guide, made a collection content type and an image content type, a collection can be populated by several images.

When I'm reaching the API http://localhost:1337/collections I can see the images, but a lot of properties are missing especially the "url" one which is the most important.
I'm only getting id, created_at and updated_at. If I reach http://localhost:1337/images it's all working fine.

Thank you!

**Comment by lauriejim** [comment]
This issue have been fixed in the deep filtering PR.

To custom the deep populate this article can help you http://help.strapi.io/customize/custom-populate-data-rest-api

**Comment by vhejda** [comment]
Hi guys! I am also completely missing the media type field in the API response if it's in a relation. What's the status on this? Has the fix not been released yet? I'm on `3.0.0-alpha.26.2`.

I have created a `hero` model with `image` media field type in it, which is exposed when I `GET /heroes`:

<img width="441" alt="obrazek" src="https://user-images.githubusercontent.com/11331661/58312858-79d1a300-7e0c-11e9-9c37-3da541c60a2f.png">

But I have a `page` model with OneToOne relation with a `hero`, and when I `GET /pages/home`, the image is completely missing under `hero`:

<img width="398" alt="obrazek" src="https://user-images.githubusercontent.com/11331661/58312927-abe30500-7e0c-11e9-9db5-208d340b6b32.png">

I tried to explicitely "deep populate" it following the article above:
```
fetch: (params) => {
    const populate = Page.associations
      .filter(ast => ast.autoPopulate !== false)
      .map(ast => ast.alias);

    populate.push('hero.image');

    return Page.forge(_.pick(params, 'slug')).fetch({
      withRelated: populate
    });
  },
```
But result is the same. I can confirm that the custom populate works well for normal relations' nesting, but I can't get the media "object" exposed in my response.

**Comment by ahmetskilinc** [comment]
Also having issues on this. Cannot seem to get images to show up when using relational data. tried `?populate=*`. Does anyone have any updates on this?

**Comment by derrickmehaffy** [comment]
As this is a very old issue completely unrelated to anything v4 I'm gonna lock this, if you have questions and need help I would advise checking out our community platforms. Either https://discord.strapi.io or https://forum.strapi.io
