### ISSUE TITLE
Strapi Admins filter by email (Invalid parameter email)

### ISSUE THREAD

**Issue by Sheryoo** [strapi/strapi#21193]
### Required System information

- Node.js version: 20.12.1
- NPM version: 10.5.0
- Strapi version:  v4.23.0
- Database: sqlite
- Operating system: macOs
- Is your project Javascript or Typescript: Typescript

### Describe the bug

this issue happens when you try to filter the admin users using the email in the admin dashboard or the API requests

### Steps to reproduce the behavior

1. Go to Settings > Administration Panel > Users
2. Click on filters
3. Select email and write any email 
4. the request will fail and the filter will be ignored

### Expected behavior

Get the admin users using the given filters

### Screenshots
<img width="1293" alt="Screenshot 2024-09-09 at 12 00 52 PM" src="https://github.com/user-attachments/assets/9398d6d7-522c-43ab-af3f-e0d31b2de504">

### Demo URL
 http://localhost:1337/admin/users?filters[$or][0][firstname][$containsi]=&filters[$or][1][lastname][$containsi]=&filters[$or][2][email][$containsi]=&populate=*

Thanks for any suggestions!

**Comment by Sheryoo** [comment]
Also the isActive filters are not working

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/20968
