### ISSUE TITLE
How and where do I create calculated fields?

### ISSUE THREAD

**Issue by jrperdomoz** [strapi/strapi#212]
**Node.js version**: v7.10.0
**npm version**: 4.2.0
**Strapi version**: 1.6.3
**Operating system**: OSX

Hello! I would like to know how to create calculated properties.

**Comment by Aurelsicoko** [comment]
What do you mean by calculated properties? Do you have an example of what you're doing? Thanks for your answer, it could help us to add this use case during the design of the new version.

**Comment by Aurelsicoko** [comment]
@kudo108 Not in our plan right now, but we could definitely add that in the future 👍

**Comment by kudo108** [comment]
I think I found the way, Hope it can help somebody
- custom in model: afterFetchAll function, calculate the value
- edit model.settings.json to show the value in admin page 
the only problem is it can not be sorted or filter

**Comment by MartinMuzatko** [comment]
This would also be helpful for `slug` #752

**Comment by minhdo89** [comment]
> I think I found the way, Hope it can help somebody
> 
> * custom in model: afterFetchAll function, calculate the value
> * edit model.settings.json to show the value in admin page
>   the only problem is it can not be sorted or filter

Do you have an example? I am very eager to see this

**Comment by kudo108** [comment]
> > I think I found the way, Hope it can help somebody
> > 
> > * custom in model: afterFetchAll function, calculate the value
> > * edit model.settings.json to show the value in admin page
> >   the only problem is it can not be sorted or filter
> 
> Do you have an example? I am very eager to see this
Example: I have a Model name Track, which have 2 value, count_wrong & count_right
this is model function:
```
afterFetchAll: async (model, results) => {

    results.forEach(function(data){
# calculate the current_stats 
      data.current_stats = parseInt(data.count_right - data.count_wrong);
    });

# this part support sort
    if (typeof model.options.sort.current_stats != 'undefined')
    {
      function compare(a,b) {
        if (a.current_stats < b.current_stats)
          return -1 * model.options.sort.current_stats;
        if (a.current_stats > b.current_stats)
          return 1 * model.options.sort.current_stats;
        return 0;
      }

      results.sort(compare);
    }
  },
```
this is Track.settings.json in /models folder (this will show the variable current_stats to view)
`"attributes": {
    "count_right": {
      "type": "integer"
    },
    "count_wrong": {
      "type": "integer"
    },
    "current_stats": {
      "type": "integer"
    }
  }`

**Comment by zecka** [comment]
> > > I think I found the way, Hope it can help somebody
> > > 
> > > * custom in model: afterFetchAll function, calculate the value
> > > * edit model.settings.json to show the value in admin page
> > >   the only problem is it can not be sorted or filter
> > 
> > 
> > Do you have an example? I am very eager to see this
> 
> Example: I have a Model name Track, which have 2 value, count_wrong & count_right
> this is model function in file /api/Track/models/Track.js
> 
> ```
> afterFetchAll: async (model, results) => {
> 
>     results.forEach(function(data){
> # calculate the current_stats 
>       data.current_stats = parseInt(data.count_right - data.count_wrong);
>     });
> 
> # this part support sort
>     if (typeof model.options.sort.current_stats != 'undefined')
>     {
>       function compare(a,b) {
>         if (a.current_stats < b.current_stats)
>           return -1 * model.options.sort.current_stats;
>         if (a.current_stats > b.current_stats)
>           return 1 * model.options.sort.current_stats;
>         return 0;
>       }
> 
>       results.sort(compare);
>     }
>   },
> ```
> 
> this is in /api/Track/models/Track.settings.json (this will show the variable current_stats to view)
> `"attributes": { "count_right": { "type": "integer" }, "count_wrong": { "type": "integer" }, "current_stats": { "type": "integer" } }`

But by doing so, you add the data to the database. How to define a virtual property (calculated) without defining it in model.settings.json?
