### ISSUE TITLE
Generated component.d.ts file doesn't sort it's interfaces which leads to issues with version control.

### ISSUE THREAD

**Issue by JensPenneman** [strapi/strapi#21208]
### System Information

- **Node.js version**: v20.17.0  
- **NPM version**: v10.8.2 / Yarn v4.4.0  
- **Strapi version**: v4.25.8  
- **Database**: Amazon RDS (Postgres) for staging and production; SQLite for development  
- **Operating system**: macOS (darwin-arm64 for development)  
- **Project language**: TypeScript

### Bug Description

The auto-generated TypeScript files for components are consistently ordered differently upon each server restart or admin panel change. This causes each Git commit to include thousands of line changes, and merge conflicts occur frequently with the main development branch.

The issue could be resolved by ensuring that interfaces are sorted consistently during the file generation process.

### Steps to Reproduce

1. Run the `strapi develop` command to start local development.
2. Wait for the server to fully start.
3. Open the `components.d.ts` file generated by Strapi.
4. Compare the diffs with the previously committed version of the file.

### Expected Behavior

The generated `components.d.ts` file should have a consistent and predictable order for the interfaces.

### Screenshots

![Screenshot 2024-09-10 at 15:33:00](https://github.com/user-attachments/assets/e307b00f-e3b0-421d-908a-de5a7803182b)

### Code Snippets

Not applicable.

### Additional Context

Due to project confidentiality, I cannot provide further details beyond the scope of this issue.

**Comment by Anxium** [comment]
We have the same issue. It's really annoying as it creates a conflict when we merge our dev branch with the prod one (whatever the branches at the end).

**Comment by Convly** [comment]
Hey there, thanks for opening this issue

Weird that happens, the read/write order should always be the same :thinking: 

Nevertheless, that seems like a perfectly reasonable change.
Just to be sure, do you want to only order the interface declarations alphabetically, or also their own properties?

**Comment by JensPenneman** [comment]
> @Convly
> Hey there, thanks for opening this issue
> 
> Weird that happens, the read/write order should always be the same 🤔
> 
> Nevertheless, that seems like a perfectly reasonable change. Just to be sure, do you want to only order the interface declarations alphabetically, or also their own properties?

As of right now, the order for **both the properties and the interfaces themselves** in a steady order would be nice.
But only the interfaces would make it a little easier to begin with.

In our company, this makes for a lot of wasted time, due to GitHub merge issues.
Also, **this issue applies to Strapi V4**. But we're planning to upgrade in the near future and check if this is still present in there. (When all implemented plugins support the newer Strapi-version)

When there is more information needed from our project, or the source code all together, I would be happy to arrange legal needs to further amend to this issue. If this is possible from my end at all.

**Comment by JensPenneman** [comment]
Thanks a lot! We'll definitely be implementing this workaround until proper support exists in Strapi.
As of today, we haven't changed the setup yet to sort these files pre commit.

Thanks a lot for the suggestion nonetheless, @davidesigner!

PS. I still hope they'll be looking into this at Strapi themselves. I suppose this would be a welcome fix for many users on the CMS.

**Comment by Convly** [comment]
Hey there, I've opened a PR to mitigate this behavior.

https://github.com/strapi/strapi/pull/21868

You can test the change using this experimental version: `0.0.0-experimental.2b7dc44ce2c49ae5fc338d31586adda583eae259`

**Comment by psullivan6** [comment]
My apologies for being naive to the process, but will get backported to version 4 as well? Or just version 5? I'm seeing it merged to `develop`, but I'm unsure if that can be released as either version.

Thank you for the speedy work to get this resolved :)

**Comment by Convly** [comment]
Hey, thanks for asking!

PRs targeting `develop` are v5 related. As v5 is out, all of our efforts are targeted toward fixing and maintaining this version.

For v4, we still fix and port critical and security issues but won't fix low issues like this one.

To be fair, this code hasn't changed at all between v4 and v5, so it's the perfect opportunity if someone wants to contribute for the first time (or not) and open a PR to port the fix, I'll happily review it.

The next planned release is next Wednesday, so if there is a PR that we can test and merge before Tuesday, it should make it to the next v4 version.

**Comment by JensPenneman** [comment]
I'll definitely take the opportunity to add the changes to V4 in a new PR.
I'll also mention this issue thread there.
