### ISSUE TITLE
Admin role with all the permissions receives forbidden error on single types

### ISSUE THREAD

**Issue by maccomaccomaccomacco** [strapi/strapi#21213]
### Required System information

- Node.js version: 20
- NPM version: 9
- Strapi version: 5.0.0-rc.19
- Database: sqlite
- Operating system: mac
- Is your project Javascript or Typescript: JS

### Describe the bug
I installed a new project populating it with the default data (--example option); I invited a new user as an author; when the new user access the single types, he receives a list of forbidden error messages, even though it has the right permissions to access them.

### Steps to reproduce the behavior

1. Install rc.19 with sample data
2. Add a new user to the Author role
3. Access as an author
4. Access the existing single types
5. See error

### Expected behavior

The Author should have access to the single types

### Screenshots

![image](https://github.com/user-attachments/assets/62a89c5b-1285-471d-9e6a-88e003c5aa1e)

**Comment by MarionLemaire** [comment]
Reproduced on RC19 with same loop of "Warning : forbidden" error messages.

script.js:1 
 GET http://localhost:1337/content-manager/single-types/api::about.about? 403 (Forbidden)

script.js:1 
 GET http://localhost:1337/content-releases/getByDocumentAttached?contentType=api::about.about&hasEntryAttached=true 403 (Forbidden)
script.js:1 useRBAC: The first argument should be an array of permissions, not an object. This will be deprecated in the future.
script.js:1 useRBAC: The first argument should be an array of permissions, not an object. This will be deprecated in the future.
![image](https://github.com/user-attachments/assets/9b8b8645-08ff-4567-a302-24481ea7cf2a)



https://github.com/user-attachments/assets/c69659bd-7060-4b58-b9d0-81b8b9ed129d

**Comment by alexandrebodin** [comment]
A few notes

- This only happens on the example app apparently as starting whit and empty app and creating a ST and adding the perm in the author works like a charm.

**Comment by alexandrebodin** [comment]
Some more info. The single type isn't a list of entries so we load the data directly. Here the data auto generated isn't owned by the author that was created so it's normal that it's forbidden. 

ℹ️  We have to fix the infinite loop only. I'll move it back to high as the user should not have access anyway so we are not preventing them from doing sth they should be able to do

**Comment by yanniskadiri** [comment]
There is no design solution that we can implement easily before the release. So for now we will go for a redirect to collection types to avoid the infinite loop and we'll improve the feature later.

**Comment by yanniskadiri** [comment]
Small correction: we will show an error message as a temporary solution (see recording).

Uploading Registrazione schermo 2024-09-13 alle 15.56.00.mov…

**Comment by simotae14** [comment]
fixed with PR https://github.com/strapi/strapi/pull/21264

**Comment by ABoyd002** [comment]
Did this ever get resolved? As have ran into the same issue after I migrated a project from one server to another.

<img width="1920" height="974" alt="Image" src="https://github.com/user-attachments/assets/e8fbb4d0-de57-482c-a2ae-962da85fbf46" />

**Comment by ABoyd002** [comment]
Container logs

```
[2025-08-06 18:18:41.245] http: GET /content-manager/content-types/api::home.home/configuration (65 ms) 200
[2025-08-06 18:18:41.259] http: GET /content-manager/single-types/api::home.home? (82 ms) 403
      at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17)


  Error: read ECONNRESET
      at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```
Environment: production
Version: 5.21.0 (node v22.18.0)
Edition: Community
Database: postgres
Database name: strapi
Database schema: public
