### ISSUE TITLE
Deploy admin panel in different server doesn't work as documented

### ISSUE THREAD

**Issue by maturanomx** [strapi/strapi#2122]
**Informations**
- **Node.js version**: v10.7.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.14.3 
- **Database**: MySQL
- **Operating system**: Ubuntu 18.04 under WLS

**What is the current behavior?**
From [the documentation for deploying the administration panel in another server](https://strapi.io/documentation/advanced/customize-admin.html#deploy-the-administration-panel-and-the-plugins-on-another-server-than-the-api):
```
  "admin": {
    "build": {
      "host": "http://yourfrontend.com/dashboard", // Note: The custom path has moved directly in the host URL.
      "backend": "http://yourbackend.com",
      "plugins": {
        "source":  "host", // What does it means? The script tags in the index.html will use the host value to load the plugins (ex: http://yourfrontend.com/dashboard/plugins/content-manager/main.js).
        "folder": "/plugins"
      }
    }
  }
```
Especial attention on the value for `admin.build.host` and how should be used by `admin.build.plugins.source`. Well, is not doing nothing what the documentation said at all...

---

### Steps to reproduce the problem:

* Create a new project.
* Use this configuration on `config/environments/production/server.json`
```json
{
  "host": "localhost",
  "port": "${process.env.PORT || 1337}",
  "proxy": {    "enabled": false  },
  "autoReload": {    "enabled": false  },
  "cron": {    "enabled": false  },
  "admin": {
    "autoOpen": false,
    "build": {
      "host": "http://localhost:8000/",
      "backend": "http://api-app.tld",
      "plugins": {
        "source":  "host",
        "folder": "/plugins"
      }
    }
  }
}
```
* Build the admin panel with `NODE_ENV=production npm run setup`
* Run the build result as static content (use port 8000)

### What is the expected behavior?
1. ✓ Admin panel served locally -- This is doing right

2. X Plugins files should be requested locally -- This is wrong. The request have an initial slash: `/http://localhost:8000/plugins/XXXXX/main.js`

3. ✓ Request to the API should be done to the correct domain -- This is done correctly.
![capture](https://user-images.githubusercontent.com/5768813/46768027-86095580-ccac-11e8-8e77-5547f2a2ea3f.PNG)
(Proof of 2 & 3)

4. X Plugins files should be copied to the `build` directory -- It's not doing this.
![capture](https://user-images.githubusercontent.com/5768813/46767739-763d4180-ccab-11e8-9c64-776593bb6ae2.PNG)

-- Repo for testing: https://github.com/maturanomx/strapi-app/tree/bug/2122

**Comment by maturanomx** [comment]
After write this issue I [began working in a fix](https://github.com/maturanomx/strapi/commit/e3c1ac60bd42929e2d4136ab31a88c012f3536f8)...

I found that [the `host` is always prepend with an slash](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/plugins.js#L27,L30). Changing that all the requests are done as I would expect:

![capture](https://user-images.githubusercontent.com/5768813/46818137-1c3d8a00-cd46-11e8-8de5-e63b133b9f63.PNG)

The problem now is that the files are not there. I think I saw a peace of code that copy those files...

... **however**, I just realize that those request should not be done at all, not that way. The request should be by the chunks that webpack build, isn't??? 😕

I will continue working in this way (fix the requests as is now) because I need this working ASAP. But, again, any help to understand the original idea, or the best workflow...

**Comment by Aurelsicoko** [comment]
This part is not automated at all... I stopped my work at this step because everyone can have a different deployment workflow. You should create a script that copies the plugins build into a `/plugins/*` folders on the front-end server.

It perfectly normal that the `host` is always prepended with a slash but the real issue is the value after the first slash, why is there **/http://localhost:8000**/plugins/XXXXX/main.js.

**Comment by maturanomx** [comment]
> It perfectly normal that the `host` is always prepended with a slash but the real issue is the value after the first slash, why is there `http://localhost:8000`?

As use a domain as the documentation says; just replacing `http://yourfrontend.com/dashboard` by `http://localhost:8000`:
![deployhostparam](https://user-images.githubusercontent.com/5768813/47389774-45153600-d6db-11e8-8290-f09547ce3264.png)

But nothing (even the structure of the build) is as the documentation said.

> You should create a script that copies the plugins build into a /plugins/* folders on the front-end server.

I [worked on a fix for that](https://github.com/maturanomx/strapi/commit/4664658792b982095835d430aa8f50c379360cff#diff-bbd5e7501a12ae06b4497be9990e2c6dR125), but then I realize that all that parameter make no sense. As you said, should be always a relative path, could be needed a "basepath", but not a "host"...

I'm keeping this in mind 🤔 ...

**Comment by thejettdurham** [comment]
After spending a few fruitless hours around this problem, I feel like it's reasonable to request that the (at the very least) the admin deployment docs be updated to help keep others from wasting their time as well, especially since this issue has been known for nearly 3 months at this point 🤔.

To elaborate, it seems that there are a few hard-coded `/admin` references that need to be fixed. Specifying only an `admin.path` param in my environment's `server.json` to override the default `/admin` route, I see a handful of requests being made to `/admin` anyhow:

- `/admin/gaConfig`
- `/admin/strapiVersion`
- `/admin/currentEnvironment`
- `/admin/layout`

**Comment by Aurelsicoko** [comment]
I agree and I'm sorry about this. We have a lot of progress to do to simplify the deployment of a project. Especially, when you want to deploy the front-end on another server than the backend.

We'll do our best to improve this but we also need your help. Can you find some time to make a PR and update the hardcoded `/admin` URLs by using the `strapi.backendURL` variable instead?

**Comment by soupette** [comment]
@Aurelsicoko 
> Can you find some time to make a PR and update the hardcoded /admin URLs by using the strapi.backendURL variable instead?

the `/admin/<endpoint>` is the prefix of the "admin" plugin so I believe it's kind of needed.

the `strapi.backendURL` is used there https://github.com/strapi/strapi/blob/8bbccad86280d362685a1a881e8bb9762b0c74e8/packages/strapi-helper-plugin/lib/src/utils/request.js#L129-L135

**Comment by Aurelsicoko** [comment]
@soupette You're right! I made a mistake, the backend routes don't change so the list above isn't an issue and shouldn't impact the deployment on another server.

**Comment by lauriejim** [comment]
@soupette Can you confirm we can close this issue because all the front end documentation will be re write with the new architecture.
