### ISSUE TITLE
How can I integrate CKEditor 5 into Content-manager plugin of strapi?

### ISSUE THREAD

**Issue by dangvinh** [strapi/strapi#2124]
Node version: 10.11.0
NPM version: 6.4.1
MongoDB version: 4.0.2
strapi version: 3.0.0-alpha.14.2
Operating System: Windows 10 Professional 64-bit

Description: 
I installed Ckeditor 5 through NPM with follow command in my strapi project:
**npm install --save @ckeditor/ckeditor5-build-classic**
Then, I import CKeditor 5 to Content-manager plugin, in my-strapi-project/plugins/content-manager/src/component/Edit/index.js:
![image](https://user-images.githubusercontent.com/30401708/46778984-3ffdd180-cd40-11e8-9da4-a1fd9de95057.png)
Finally, I add this line to above file:
![image](https://user-images.githubusercontent.com/30401708/46779088-9bc85a80-cd40-11e8-91ba-c9ff0b65863c.png)

My goal is to replace all <textarea> tags with CKeditor 5, but the result is nothing to change.
So, how can I do that?

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/issues/2111
