### ISSUE TITLE
[CM][I18N] Cannot publish new locale directly

### ISSUE THREAD

**Issue by alexandrebodin** [strapi/strapi#21249]
**Steps**

- Create a new document
- Save or publish in any locale for the 1st time
- Switch locale, add some content. Try to "publish" directly without saving. See the error.

**Expected behavior**
- Should publish correctly

<img width="1800" alt="Screenshot 2024-09-11 at 22 00 03" src="https://github.com/user-attachments/assets/e9062f8d-5b65-46c3-a1d9-98b7089c1c32">

**Comment by simotae14** [comment]
The error is "Document not found"

**Comment by simotae14** [comment]
fixed with PR https://github.com/strapi/strapi/pull/21251
