### ISSUE TITLE
[Design] Select Files tab content on the Asset Field

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21253]
### **Steps to reproduce**
- Go to an entry with a media input
- Click on Add an asset
- Go to the selected files tab
- See that there is an issue and 2 sentences should be spaced

### **Expected behavior**

The 2 sentences should be split.

### **Screenshots**

![Image](https://github.com/user-attachments/assets/2526a709-56ad-47a8-a451-223c502afe40)

**Comment by yanniskadiri** [comment]
Design made by Lucas is available here: https://www.figma.com/design/dXVERkEdUoX3R7JmqoaIUi/CMS-pages?node-id=587-9653&node-type=instance&t=0Bf9pQXucJQCHrSg-0

**Comment by simotae14** [comment]
Fixed with this PR https://github.com/strapi/strapi/pull/21587
