### ISSUE TITLE
Users can register users-permissions users that violate the validations and minimum requirements

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#21255]
### Required System information

- Node.js version: 20
- NPM version: yarn v1
- Strapi version: 5.0.0-rc.20
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When registering a user within users-permissions (via the API `/api/auth/local/register`) the validations for password length do not apply.

### Steps to reproduce the behavior

1. Create a Strapi v5 RC application
2. Use an API Client (postman) to register a user via `POST /api/auth/local/register`
3. Set the password to something like `t1`
4. Send the Request
5. See that the user is properly created and a JWT is issued

### Expected behavior

Min/Max and complexity requirements should be respected

### Screenshots

![image](https://github.com/user-attachments/assets/0245cb43-6a28-41f0-a07d-c985ea383249)

### Code snippets

Request payload:

```json
{
    "username": "test2",
    "email": "test2@test.com",
    "password": "t1"
}
```

### Additional context

N/A

**Comment by r0ld3x** [comment]
its working fine in mine

```typescript
import axios from 'axios';
axios
  .post('http://localhost:1337/api/auth/local/register', {
    username: 'test2',
    email: 'test2@test.com',
    password: 't1',
  })
  .then((response) => {
    console.log('Well done!');
  })
  .catch((error) => {
    console.log('An error occurred:', error.response.data);
  });
```

**Returns**
```
{
    status: 400,
    name: 'ValidationError',
    message: 'password must be at least 6 characters',
    details: { errors: [Array] }
  }
  ```

**Comment by hanpaine** [comment]
Thanks @devarsh-mavani-19 that's a really kind offer! Due to the nature of the issue (high sev and security related) as well as the current intensity around Strapi 5, we will take this one into the team to resolve this week. I really appreciate you reaching out to though 🙏
