### ISSUE TITLE
Copy to cliboard triggering form submission in settings -> administration panel -> invite new user

### ISSUE THREAD

**Issue by MDSilviu** [strapi/strapi#21258]
When you press the copy to clipboard button in the invite new user modal the form is also being submitted.
![image](https://github.com/user-attachments/assets/94bc4abd-d062-4a9f-b87f-967a94df0145)

**Comment by hanyBaghrzadeh** [comment]
من پرستارم وبسیارگرفتاریه روش واسه انجام کارهای ارزی ساده وراحت که بتونم دروقت بیکاری که خیلی کمه ومادربزرگ آلزایمر دا ره به درآمد ارزی هم برسم ممنونم

**Comment by r0ld3x** [comment]
ok let me check I will fix

**Comment by r0ld3x** [comment]
okay I started in localhost 

I couldn't find anything wrong in invite new user

**Comment by MDSilviu** [comment]
When you press on the button to copy the link to clipboard the form is submitted again, that button needs added a "type='button'" to it

**Comment by r0ld3x** [comment]
@MDSilviu still not submitting any kind of form. make a video if possible with network log
