### ISSUE TITLE
Confirmation email is not being sent

### ISSUE THREAD

**Issue by vanpana** [strapi/strapi#2126]
Information

Node.js version: 10
npm version: 6.4.0
Strapi version: 3.0.0-alpha.14.3
Database: mongodb v4.0.2
Operating system: macOS 10.14

What is the current behavior?
If email confirmation is enabled, user is created, but the request times out and email isn't sent.

Steps to reproduce the problem
Make a POST request to /auth/local/register with the specified body in the documentation. You'll see the user created, but not the email sent.

What is the expected behavior?
The email should be sent.

Suggested solutions
I don't really know what the issue is

**Comment by lauriejim** [comment]
Hello, I supposed you are using your computer as SMTP server. And it can fail because it's a not verified server.

I suggest you to use https://github.com/audiomancer/strapi-email-nodemailer email provider.
Documentation: https://github.com/audiomancer/strapi-email-nodemailer

**Comment by MartinMuzatko** [comment]
@lauriejim  My assumption was that when I install the plugin, that I have it available in the list of providers.
This is not the case with  strapi-email-nodemailer. @audiomancer
