### ISSUE TITLE
Strapi redirects back to login on successful login to admin

### ISSUE THREAD

**Issue by mosesharrisjr** [strapi/strapi#2128]
**Informations**
- **Node.js version**: v10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**:  MongoDB
- **Operating system**:   OSX High Sierra

**What is the current behavior?**
on successful login, strapi redirects back to login page.

**Steps to reproduce the problem**
1. Login to strapi running in dev mode.
2. Strapi redirects back to login page.

**What is the expected behavior?**
Logging in should take you back to the admin panel.

**Suggested solutions**
Not sure.

It goes from here:
<img width="625" alt="screen shot 2018-10-11 at 4 25 47 pm" src="https://user-images.githubusercontent.com/12969233/46834909-56bd1c00-cd72-11e8-8fc5-b56dc9a829b1.png">

To here for a split second (It's not showing anything close to all of the APIs):
![image](https://user-images.githubusercontent.com/12969233/46835020-9be14e00-cd72-11e8-8ae6-ab9c437c6156.png)

Then back to here:
<img width="625" alt="screen shot 2018-10-11 at 4 25 47 pm" src="https://user-images.githubusercontent.com/12969233/46834909-56bd1c00-cd72-11e8-8fc5-b56dc9a829b1.png">

I get no errors in the console, logging in with Postman works fine.

The only thing that might be something is a few red entries in the Network tab:

> Request URL: http://localhost:1337/content-type-builder/autoReload
> Request Method: GET
> Status Code: 401 Unauthorized
> Remote Address: [::1]:1337
> Referrer Policy: no-referrer-when-downgrade
> 
> Request URL: http://localhost:1337/content-manager/models
> Request Method: GET
> Status Code: 401 Unauthorized
> Remote Address: [::1]:1337
> Referrer Policy: no-referrer-when-downgrade
> 
> Request URL: http://localhost:1337/user/me
> Request Method: GET
> Status Code: 404 Not Found
> Remote Address: [::1]:1337
> Referrer Policy: no-referrer-when-downgrade
> 
> Request URL: https://blog.strapi.io/ghost/api/v0.1/posts/?client_id=ghost-frontend&client_secret=1f260788b4ec&limit=2
> Referrer Policy: no-referrer-when-downgrade

Here is my user model:
```{
  "connection": "default",
  "info": {
    "name": "user",
    "description": ""
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "history": {
      "default": false,
      "type": "json"
    },
    "bookmarks": {
      "default:": false,
      "collection": "bookmark",
      "via": "user"
    }
  },
  "collectionName": "users-permissions_user"
}

**Comment by mosesharrisjr** [comment]
One of the Content Types was named 'function.'   On correcting this, everything seems to be working now.

**Comment by tugal** [comment]
Same issue here, how do you find out that this fields cause redirect ?

thanks,

**Comment by ahmdsdk** [comment]
Same issue here, but I do not have a Content Type name 'function'. Also not getting 401 in the Network tab all is 200. Able to log in from Postman.

**Comment by thomasrrl** [comment]
> Same issue here, how do you find out that this fields cause redirect ?
> 
> thanks,

Facing the same issue, any suggestions on finding the problematic field?

**Comment by ahmadsdk** [comment]
As I have faced this problem before it's usually one or a mixture of either enum fields / JSON types / date fields, since they cannot be left empty when signing up.

What I usually do is I use the default User.settings.json and hide the api folder when signing up with the first Admin user and then after that I replace it with my modified User.settings.json and put the api folder back where it should be.
