### ISSUE TITLE
Docker startup issues Strapi 5-rc22

### ISSUE THREAD

**Issue by jvdbrink-netpulse** [strapi/strapi#21283]
## Bug report

First of all I would like to compliment everyone who worked on Strapi 5, it is looking promising, I especially like the minimized REST interface! Running: npx create-strapi-app@rc my-project --quickstart worked great! However I'm having some performance / connecting issues using Docker, as outlined below:

System information

- Node.js version: 20.14
- NPM version: 10.7.0
- Strapi version: 5.0.0-rc.22
- Database: Mysql
- Operating system: Docker (on windows using WSL2)
- Is your project Javascript or Typescript: combined

### Description:

I'm having some issues running Strapi 5 in docker, coming from Strapi 4. First is the speed, step:
Loading Strapi (98032ms) averages about 100 sec to start.

Once started I'm having issues with Vite, browser console blocked wss stating, Content-Security-Policy blocked due to breaking:  ‘connect-src 'self' http: https:’ rule. The wss connection is connecting to port 5173. And Strapi is running on 0.0.0.0 behind a Traefik reverse proxy at domain: https://next.netpulse-dev.nl/admin. I had the same approach working on Strapi 4.x and it worked fine because there was no extra wss connection.

I have tried various port / host / url changes in config/server.ts and in newly created vite.config.ts. None of them seem to resolve the issue. Perhaps I can overwrite the Content-Security-Policy in development? Hoping someone can point me in the right direction.

**Comment by jvdbrink-netpulse** [comment]
Issues seem to have resolved using the new 5.0 release following https://docs.strapi.io/dev-docs/installation/docker, new release does require different Traefik rules (if you use traefik).

**Comment by derrickmehaffy** [comment]
You shouldn't need a reverse proxy configure with relation to the vite port as we do not support nor recommend running development mode as production or in a deployed environment and that vite port is only used for development mode
