### ISSUE TITLE
[Content Manager] Required field validations

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21285]
Issue 1:
- Create an entry of a CT with a required field
- Fill in content other than the required field
- Save (this works fine)
- Publish - see the error message is overly technical where it should be `this value is required`

Issue 2:
- Save and publish content with the required field filled - this works as expected
- From the published entry clear the required field
- Directly publish - This succeeds when it should fail due to required validation

https://github.com/user-attachments/assets/17b5ab1c-a13f-4289-9f1d-c2860fe157ee

**Comment by Agam1997** [comment]
Hi, is this ticket picked up by the strapi team?

I was looking to contribute to Strapi. Is there any bug that the team would recommend me to start off with?

**Comment by oiorain** [comment]
Hi @Agam1997! 

Yes, this has been picked up already. 

If you want to find little bugs to fix to start you can check the Low and Medium bugs in the [Strapi 5 - Bug Tracker](https://github.com/orgs/strapi/projects/34/views/1?sliceBy%5Bvalue%5D=Low) board. The ones in the Backlog column have been confirmed. If there is someone assigned they're already picked up. 

Cheers! 😊
