### ISSUE TITLE
[Releases] Release is blocked while everything is ready to published

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21290]
I have only one entry, ready to publish and the release is blocked.

![Capture d’écran 2024-09-16 à 17 23 34](https://github.com/user-attachments/assets/6de5e578-6f6d-4bf0-84a6-aea640869b06)

**Comment by alexandrebodin** [comment]
@yanniskadiri Can you add more details (CT options, D&P, i18N, the actions you did) please.

**Comment by alexandrebodin** [comment]
Fixed by https://github.com/strapi/strapi/pull/21302
