### ISSUE TITLE
[RBAC/RW] I cannot assign someone to an entry while having the permissions to do so

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21292]
I cannot assign someone to an entry with RW whereas I’m at a stage when I have the permissions.

Steps to reproduce:

- Create a CT “Article” with whatever fields
- Create an entry “Test” with the Admin Role
- Create a new role “Writer” with full access to the “Article”
- Create a new user with the Writer role assigned
- Update the Default workflow and let the new role “Writer” update the stage when reaching “Ready to Review”

- Open a new private tab, connect to the second user
- Go to the entry “Test”, see that you cannot edit the stage, you cannot assign either.
- Use the Admin to move to “Ready to Review” stage, and try to assign again with the second user, it still doesn’t work

![Image](https://github.com/user-attachments/assets/fe89828b-be0e-4d68-b6d9-0b6139dba407)

**Comment by remidej** [comment]
I'm currently testing if Alex's PR fixed this
