### ISSUE TITLE
[RBAC/RW] RW isn’t visible/working for ST

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21293]
I enabled the Default RW on the ST “Cookie Banner”, it isn’t visible.

![Image](https://github.com/user-attachments/assets/34ad3444-0d51-4019-962b-3271ef36e08a)
![Image](https://github.com/user-attachments/assets/dec1de51-8fbf-4584-9f9e-e73c1677ad01)

**Comment by alexandrebodin** [comment]
Fixed

**Comment by oiorain** [comment]
@alexandrebodin 
I can see the RX box now but it seems i dont have the rights to change the status 
https://www.loom.com/share/fa4a271b02404a81987539c697adf392?sid=651eceb1-279e-466d-8bda-6ca4cf7bde6e
