### ISSUE TITLE
Newly added fields don't show up in Content Types browser

### ISSUE THREAD

**Issue by dannydtk** [strapi/strapi#2130]
**Informations**
- **Node.js version**: 10.12.0
- **npm version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.14.3
- **Database**: MongoDB v4.0.2
- **Operating system**: macOS Sierra 10.12.6

**What is the current behavior?**
When I add a new field after the Content Type is created it isn't visible in its browser but when adding a new object it is. It isn't visible in the Content Manager too.

**Steps to reproduce the problem**
1. Create a new Content Type named _test_ in Content Type Builder with a string field called _name_ and save.
2. Go to _Tests_ visible on the left in the menu.
3. The _name_ field is visible.
4. Go to Content Type Builder and edit _test_ Content Type.
5. Add a new number field named _number_ and save.
6. Go to _Tests_ visible on the left in the menu.
7. The _name_ field is visible in the table but _number_ is not.

**What is the expected behavior?**
The _number_ field should be visible as a column in the table.

**Suggested solutions**
-

**Comment by lauriejim** [comment]
Hello @dannydtk thank you to repport this issue.

You can fix your UI by going in `Content Manager` link on the left menu, click on your content type name (Test in your example) and update display attributes in the list view (click on `Add a new field` in `List — Settings` section)

**Comment by soupette** [comment]
can we close this issue it happened on v14 ?
