### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by Yum1x** [strapi/strapi#21315]
### Required System information

- Node.js version: v18.20.4 (same problem on v21.7.3)
- NPM version: 10.7.0
- Strapi version: 4.25.11
- Database: postgres
- Operating system: linux-x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Uploading a image<sup><sub>(tried a .pdf and work's fine)</sub></sup> file gives the following error: _munmap_chunk(): invalid_ pointer.

### Steps to reproduce the behavior

https://streamable.com/av2za8

### Expected behavior

Stop crashing and upload the images successfully

### Screenshots

![image](https://github.com/user-attachments/assets/4e09258f-ac9c-499e-8a93-d126da9a0006)
![image](https://github.com/user-attachments/assets/c11f5e93-8178-467f-a082-c810493a91a3)

**Comment by derrickmehaffy** [comment]
Tested on v4.25.14 and cannot reproduce:

![image](https://github.com/user-attachments/assets/4eda3335-95bf-4980-9a92-83f694cc9c6a)
