### ISSUE TITLE
Image File name not updating on filename change

### ISSUE THREAD

**Issue by sehrish30** [strapi/strapi#21318]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.25.5
- Database: mysql
- Operating system: Macos
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Filename does not update in link, when I update the filename from media in strapi.

### Steps to reproduce the behavior

1. Go to the Media library in the side panel under "Plugins" 
<img width="222" alt="Screenshot 2024-09-18 at 3 10 16 PM" src="https://github.com/user-attachments/assets/b3806c59-5f51-4fe8-8c93-8b9ffefdee6f">

2. Click on any image and copy its link
3. Change its filename
4. Copy the link of the file
5. Both links are the same

### Expected behavior

I expect the path to change when I change the filename.

### Screenshots
<img width="890" alt="Screenshot 2024-09-18 at 3 08 02 PM" src="https://github.com/user-attachments/assets/648c2f3c-c450-47d4-8003-41d369fead0f">

**Comment by Sam-Phillemon9493** [comment]
@sehrish30, I believe this is the intended behavior and not an issue. The copy link and the file name are separate entities, so updating the URL path when the filename changes wouldn’t be logical.

**Comment by derrickmehaffy** [comment]
This is intended behavior to ensure that any frontend usage of the file doesn't break if it's hard coded or something.
