### ISSUE TITLE
camelCase content-type names break content-manager and creation page

### ISSUE THREAD

**Issue by tacone** [strapi/strapi#2131]
**Informations**
- **Node.js version**: v8.11.4
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: mongodb
- **Operating system**: Ubuntu 18.04.1 LTS

**What is the current behavior?**
Adding a content type with a camel cased name (e.g. containing an uppercase letter) breaks the content manager and crud editor.

**Steps to reproduce the problem**
- create a product named `sampleContent`, add a string field and save it.
- try to edit it again, a blank page will appear: http://localhost:1337/admin/plugins/content-manager/ctm-configurations/samplecontent.
- also trying to insert a new document in the db won't work, the creation page will display the loading spinner forever  ( http://localhost:1337/admin/plugins/content-manager/samplecontent/create?redirectUrl=/plugins/content-manager/samplecontent?_limit=10&_page=1&_sort=_id&source=content-manager )

**What is the expected behavior?**

Everything should work as with lowercased collections.

Here's the content-manager blank page stacktrace.

```
TypeError: this.layout is undefined main.js:66
	value main.js:66
	value/< main.js:66
	../strapi-admin/node_modules/strapi-helper-plugin/node_modules/immutable/dist/immutable.js/</e.exports</We.prototype.__iterate main.js:6
	forEach main.js:6
	value main.js:66
	e main.js:66
	o/< main.js:60
	Me main.js:6
	Me main.js:6
	Me main.js:6
	Me main.js:6
	Me main.js:6
	Me main.js:6
	../strapi-admin/node_modules/strapi-helper-plugin/node_modules/immutable/dist/immutable.js/</e.exports</de.prototype.updateIn main.js:6
	o main.js:60
	./node_modules/strapi-helper-plugin/node_modules/redux-immutable/dist/combineReducers.js/t.default/</</< main.js:76
	forEach self-hosted:268:13
	./node_modules/strapi-helper-plugin/node_modules/redux-immutable/dist/combineReducers.js/t.default/</< main.js:76
	../strapi-admin/node_modules/strapi-helper-plugin/node_modules/immutable/dist/immutable.js/</e.exports</de.prototype.withMutations main.js:6
	./node_modules/strapi-helper-plugin/node_modules/redux-immutable/dist/combineReducers.js/t.default/< main.js:76
	c main.js:76
	r/</</< main.js:76
	e/</< main.js:76
	r/< main.js:76
	value main.js:60
	tn main.js:16
	en main.js:16
	Qo main.js:16
	sn main.js:16
	Be main.js:16
	Be self-hosted:1031:17
```

**Comment by lauriejim** [comment]
It's not a duplicate @derrickmehaffy.

I can confirm this issue. Thank you for the report @tacone .

**Comment by derrickmehaffy** [comment]
@lauriejim This is the same case problem there have been multiple issues with previously the relations are not properly handling case types, a lot of that is documented in https://github.com/strapi/strapi/issues/1139

In many cases if you attempt to use camelCase or capitals in a relation it will break because it cannot find "Blah" because the related model is "blah".

As I suggested in the linked issue, Strapi should convert all of these to lowercase by default even if the user enters a different case.

**Comment by derrickmehaffy** [comment]
Another related issue: https://github.com/strapi/strapi/issues/2097

**Comment by soupette** [comment]
I agree with @derrickmehaffy it will be easier for both the backend and the front-end. Especially when the backend breaks when editing or removing a new entry it messes up with the `plugin_content_manager_schema` thus breaking the content manager.

**Comment by Downloaddave** [comment]
If we are encountering the same issue as @tacone what's the best way of reverting something that was already done in camelCase (or anything, someone might have messed up making in the Content Type Builder)?

So far my guess would be to do the following

1. Stop the Strapi Server
1. Drop the collection "samplecontent" in MongoDB (with the assumption you created "sampleContent"
1. Go to the Strapi Project Code (installed locally) and then delete the entire "samplecontent" folder.
1. Start the Strapi Server
1. Go to Strapi CMS -> Content Type Builder
1. Create a new Content Type, this time all lowercase
1. Go to the api/samplecontent/samplecontent.settings.json and change the following...

FROM
```  
"info": {
    "name": "samplecontent",
    "description": ""
  },
```

TO
```
  "info": {
    "name": "Sample Content",
    "description": ""
  },
```

Out of curiosity, has there been any issues with spacing; for example creating a "Sample Content" content type?

Can the above steps be used to resolve spacing as well?

Thanks in advance!

**Comment by soupette** [comment]
@Downloaddave the best way to revert it is a bit simpler:
Delete the `plugin_content_manager_schema` document in your `core_store` and restart your strapi server.

> Out of curiosity, has there been any issues with spacing; for example creating a "Sample Content" content type?
Can the above steps be used to resolve spacing as well?

Strapi can't handle spacing for the moment.

**Comment by Downloaddave** [comment]
Is there a recent ticket relating to the Spacing in in the Content Type Builder so we can see "Sample Content" in the Content Types CMS?
