### ISSUE TITLE
When using the Fill with another locale with a password as a required field, the behavior isn’t optimal

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21332]
### **Steps to reproduce**
- Create a content type with a password field required
- Use the Fill with another locale
- The password field isn’t filled (why not after all?)
- However, when click “Publish”, I get an error
- The state of the page is reset
- All my content is lost :o

### **Expected behavior**

Display the error, don’t reset or refresh the page

### **Screenshots**

![Image](https://github.com/user-attachments/assets/5dde26f8-a6c3-4e18-94b7-aaf2a37fe0a7)

**Comment by Marc-Roig** [comment]
Just realized that it is a bit complicated to publish an entry with a password field that is required.

Having said that, I tried to replicate your setup and when publishing I only get the warning error but I don't lose my data, so this looks fixed
![image](https://github.com/user-attachments/assets/5111bbfc-e2b0-495d-a03d-e12cbe170bef)
