### ISSUE TITLE
Respect ordering of related content items

### ISSUE THREAD

**Issue by andrewmee** [strapi/strapi#2134]
In the Strapi admin interface you can drag and drop related content items within their lists;

<img width="215" alt="screen shot 2018-10-12 at 14 46 35" src="https://user-images.githubusercontent.com/24985/46873085-b3c9d800-ce2d-11e8-8949-9c2ce6f7218b.png">

However this doesn't seem to save anywhere, or have any effect on the way that data is returned when querying.

**What is the expected behavior?**

The order of related items should be stored when content is saved, and this should provide the default sort order of the content when it's returned by the API.

**Comment by bjnsn** [comment]
Seeing this behavior also. :-/

**Comment by lauriejim** [comment]
Hello @andrewmee , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

**Comment by andrewmee** [comment]
@lauriejim Oh I intended this as a feature request, so I used that template instead.  Is the behaviour I've described something you expect should already be happening?

I assumed this would be a new feature.

**Comment by lauriejim** [comment]
In fact it's already working. I tested and it works.
So I think you have an issue.
