### ISSUE TITLE
[Design] Missing white border between selected item and hover state in the list box

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21348]
![Image](https://github.com/user-attachments/assets/35948b2e-9691-40cb-9354-7607e31adf17)

**Comment by yanniskadiri** [comment]
Comment from Lucas: the real issue here is that the selected item shouldn’t have any background.

![Image](https://github.com/user-attachments/assets/02dcbe9c-f45f-4f1a-bc12-ad45e323bc88)

**Comment by lucasboilly** [comment]
@yanniskadiri I'm closing it as it's in fact a DS issue (https://github.com/strapi/design-system/issues/1808).
