### ISSUE TITLE
[Design] HP logos are misaligned

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21342]
### **Steps to reproduce**
- Login
- Go to Homepage
- Check Join the community section on the right of the page

### **Expected behavior**

Logos should be aligned

### **Screenshots**

![Image](https://github.com/user-attachments/assets/698811e0-c90f-46cc-912f-88ebd083df44)

**Comment by MarionLemaire** [comment]
Confirmed in 5.0.0
![Image](https://github.com/user-attachments/assets/1f343f1a-3c84-4993-8557-f1e03392d8bd)

Steps : 
- Login
- Go to Homepage
- Check Join the community section on the right of the page
