### ISSUE TITLE
Broken Image Upload using DigitalOcean Spaces

### ISSUE THREAD

**Issue by javdevruent** [strapi/strapi#21371]
**OS**: win32-x64
**Strapi Version**: 4.25.10
**Node**: v20.17.0
**NPM**: 10.0.0 

**PROJECT TYPE**: JAVASCRIPT

Im configuring strapi upload I follow the documentation and use these below configurations

/config/plugin.js
`
![image](https://github.com/user-attachments/assets/88482056-ed42-41d6-88a7-c7a384e713db)

/config/middleware.js

![image](https://github.com/user-attachments/assets/5b2c439a-5873-4608-b1b3-7c8955b00c38)

I manage to upload the images using the obove donfiguration but the problem is when displaying it, Strapi show a broken images like this

![image](https://github.com/user-attachments/assets/df9fabec-f28f-4459-8252-15acfb8f30c4)

There are no error showing in console tab,

![image](https://github.com/user-attachments/assets/b77b212a-ebf1-404c-9d81-ff528b82b33a)
But this is the error when you check it in network tab,

Im stuck , can someone help me with this issue?

**Comment by guymunday** [comment]
Try changing your middlewares.js directives to a wildcard like this: 

```
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "*.digitaloceanspaces.com",
            "*.strapi.io",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "*.digitaloceanspaces.com",
            "*.strapi.io",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
```
