### ISSUE TITLE
[Bug]: Can't unit test my Strapi routes

### ISSUE THREAD

**Issue by jefersoneiji** [strapi/strapi#21385]
### Required System information

- Node.js version: 20.11.1
- NPM version: pnpm v8.15.6
- Strapi version: v5
- Database: postgresql
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I'm unable and without any clue on how to unit test my Strapi routes.

### Steps to reproduce the behavior

1. I created a project by following the [quick start guide](https://docs-v4.strapi.io/dev-docs/quick-start) by [using the CLI](https://docs-v4.strapi.io/dev-docs/quick-start#-part-a-create-a-new-project-with-strapi)
2. Went to the testing section and did [all the steps](https://docs.strapi.io/dev-docs/testing)
3. Installed vitest a test runner
4. Runned [this test](https://docs.strapi.io/dev-docs/testing#test-a-strapi-instance)

### Expected behavior

For this strapi instance to work properly without any errors

### Screenshots

![image](https://github.com/user-attachments/assets/e1d786ba-9699-4d52-b798-ab453a6e24b2)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by jefersoneiji** [comment]
This issue is tagged wrong. Strapi has no up to date docs in regard to testing. I repeat its not a question. The current strapi class throws the error I mentioned whenever I follow the docs on testing. It's not a question on wheter strapi works or not. Its an affirmation that it does not work whenever I follow the official strapi documentation on testing. 

How can I test stripe routes without throwing an error?  @derrickmehaffy

**Comment by artsiompeshko** [comment]
+1

**Comment by dannyh79** [comment]
@jefersoneiji Hope this helps:

```ts
// tests/helpers/strapi.ts
import strapiFactory from '@strapi/strapi';
import fs from 'fs';

type Strapi = ReturnType<typeof strapiFactory.createStrapi>;

let instance: Strapi;

const setupStrapi = async (): Promise<Strapi> => {
  if (!instance) {
    instance = await strapiFactory.createStrapi().load();
    instance.server.mount();
  }
  return instance;
};

const cleanupStrapi = async () => {
  const dbSettings = strapi.config.get<Record<string, any> | undefined>('database.connection');

  strapi.server.httpServer.close();

  await strapi.db.connection.destroy();

  if (dbSettings && dbSettings.connection?.filename) {
    const tmpDbFile = dbSettings.connection.filename;
    if (fs.existsSync(tmpDbFile)) {
      fs.unlinkSync(tmpDbFile);
    }
  }
};

export { setupStrapi, cleanupStrapi };
```

**Comment by ancashoria** [comment]
I was unable to get it working. Is anyone having a working Vitest setup for Strapi?

**Comment by dannyh79** [comment]
> I was unable to get it working. Is anyone having a working Vitest setup for Strapi?

@ancashoria If it's not too late for you to switch, you might want to take a look at https://github.com/payloadcms/payload. 

Too much pain in TypeScript integration and for-frontend schema generation with Strapi. Payload is almost all-code but it serves the needs for me for the 3 projects that I work on.
