### ISSUE TITLE
Content History shows error when editing components in a dynamic zone

### ISSUE THREAD

**Issue by StrapiBartosh** [strapi/strapi#21405]
### Required System information

- Node.js version: v20.15.0
- NPM version:10.8.2
- Strapi version: 5.0.0
- Database:sqlite
- Operating system: Darwin-arm64
- Is your project Javascript or Typescript: JS

### Describe the bug

When attempting to restore piece of content that has a dynamic zone, occasionally Strapi is unable to restore. 

### Expected behavior

The content should restore with not issue.

### Screenshots

Loom issue below

https://www.loom.com/share/1ce57833d6a14669bedc59df16a0e350

**Comment by srinidhi-s-dev** [comment]
i too got these issues several times when editing content in dynamic zone it returns null or undefined
