### ISSUE TITLE
Custom route/controller/service for many-to-many user relationships?

### ISSUE THREAD

**Issue by visagegod** [strapi/strapi#2141]
**Informations**
- **Node.js version**: 8.12.0
- **npm version**: 6.4.1
- **Strapi version**: latest
- **Database**: PostgreSQL
- **Operating system**: Ubuntu

**Background**
I have created a many-to-many relation between the user-permissions-user model and a custom model called tracks, by giving user an attribute called 'likedTracks' and giving track an attribute called 'likedByUsers'. As a result of this a table is created called 'tracks_liked_by_users__users_liked_tracks'. I have then written a custom end point ('/queue') in the 'Track' controller that calls a custom service (fetchQueue()).

api/track/controllers/Track.js
```
queue: async (ctx) => {
  return strapi.services.track.fetchQueue(ctx)
}
```

api/track/services/Track.js
```
fetchQueue: (params) => {
  let userId = params.state.user.id
  
  const filters = {
    where: { 'likedByUsers': { symbol: 'like', value: userId } },
    sort: '',
    start: 0,
    limit: 10
  }

  const populate = Track.associations
    .filter(ast => ast.autoPopulate !== false)
    .map(ast => ast.alias);

  return Track.query(function(qb) {
    _.forEach(filters.where, (where, key) => {
      if (_.isArray(where.value)) {
        for (const value in where.value) {
          qb[value ? 'where' : 'orWhere'](key, where.symbol, where.value[value])
        }
      } else {
        qb.where(key, where.symbol, where.value);
      }
    });

    if (filters.sort) {
      qb.orderBy(filters.sort.key, filters.sort.order);
    }

    qb.offset(filters.start);
    qb.limit(filters.limit);
  }).fetchAll({
    withRelated: populate
  });
}
```

**What is the issue?**
I am trying to write a filter to return all Track objects where 'userId' is NOT contained in 'likedByUsers'?

This is what I have so far... (this is wrong):

```
const filters = {
   where: { 'likedByUsers': { symbol: 'like', value: userId } },
   sort: '',
   start: 0,
   limit: 10
}
```

This returns this error: 

`error: column "likedByUsers" does not exist`

Which is obvious because the 'likedByUsers' attribute is stored within it's own 'tracks_liked_by_users__users_liked_tracks' table (as mentioned above).

I love Strapi for it's simplicity, but limited documentation is making tasks like this more difficult than other more heavyweight options.

Thanks in advance!

**Comment by kamalbennani** [comment]
For now you can't do this, you probably need to wait for this PR (https://github.com/strapi/strapi/pull/1948) to be merged.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
