### ISSUE TITLE
Error with Vite on Docker installation - Failed to fetch dynamically imported module - CSS asset outside Vite allow list: /opt/node_modules/highlight.js/styles/solarized-dark.css

### ISSUE THREAD

**Issue by sbastias** [strapi/strapi#21413]
I can confirm this is still an issue.

<img width="600" alt="image" src="https://github.com/user-attachments/assets/959c951a-9549-4c83-8176-a004c79d7df6">

The terminal shows:
```
The request url "/opt/node_modules/highlight.js/styles/solarized-dark.css" is outside of Vite serving allow list.
```

I'm using Strapi v5 in a docker installation. It seems to be intermittently failing. Ctrl + Shift + R occasionally solves the problem, but right now I'm unable to edit any entries.

I don't think running 'start' instead of 'develop' is a great solution? How was this moved to **Done**?

_Originally posted by @sbastias in https://github.com/strapi/strapi/issues/20870#issuecomment-2365027989_

**Comment by sbastias** [comment]
I solved this by enabling /src/admin/vite.config.js (CJS)

First, the provided example file **is not valid** in CJS because mergeConfig is not available from Vite in CJS.

I used lodash merge to deep merge Strapi and Vite config, adding the node /opt/node_modules path to the allow list:

```
const { defineConfig } = require('vite');
const {merge} = require('lodash');

module.exports = (config) => {

  // Important: always return the modified config

  // console.log(config, '<<< config')

  let viteConfig = defineConfig({
    server: {
      fs: {   
        allow: [
          '/opt/node_modules',// this is the abs path OUTSIDE the project root causing the Vite error
          '/opt/app',
        ],
      }
    }
  })

  let mergedConfig = merge(config, viteConfig)

  // console.log(mergedConfig, '<<< mergedConfig')

  return mergedConfig

};
```

Thanks ChatGPT! :-)

**Comment by sbastias** [comment]
Further, I needed to do some magic to the Dockerfile to get Vite to write to file after enabling the vite.config.js. Vite was trying to write to a non-existent folder and didn't have permissions on node_modules....
```
FROM node:20-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package.json yarn.lock ./
RUN yarn global add node-gyp
RUN yarn config set network-timeout 600000 -g && yarn install
ENV PATH /opt/node_modules/.bin:$PATH

WORKDIR /opt/app
COPY . .
RUN chown -R node:node /opt/app
USER node
RUN ["yarn", "build"]

# EXTRA VITE STUFF HERE
# switch back to root to make node:node owner of node_modules after build
USER root
RUN chown node:node /opt/app/node_modules
# switch back to node user to create vite writeable directory
USER node
RUN mkdir -p /opt/app/node_modules/.strapi/vite

EXPOSE 1337
EXPOSE 5173
CMD ["yarn", "develop"]

**Comment by KaarelMetsaots** [comment]
I also needed to add `RUN mkdir -p /opt/app/node_modules` after the `USER root` command in Dockerfile. For me it was not able to create the admin user all together and got Uncaught token "M" error on submit. But thanks this workaround works 🙌

**Comment by rgmvisser** [comment]
Thanks for opening this issue @sbastias ! This is my solution that seemed to work:
```
import { mergeConfig, type UserConfig } from "vite";

export default (config: UserConfig) => {
  // Important: always return the modified config
  return mergeConfig(config, {
    resolve: {
      server: {
        fs: {
          allow: [
            "/opt/node_modules", // this is the abs path OUTSIDE the project root causing the Vite error
            "/opt/app",
          ],
        },
      },
      alias: {
        "@": "/src",
      },
    },
  });
};
```

**Comment by ace-of-aces** [comment]
> This is my solution that seemed to work

Hey @rgmvisser I tried your solution, but only got it working by omitting `resolve` key.

The `src/admin/vite.config.ts` that worked for me:
```typescript
import {mergeConfig, type UserConfig} from "vite";

export default (config: UserConfig) => {
    return mergeConfig(config, {
        server: {
            fs: {
                allow: [
                    "/opt/node_modules",
                    "/opt/app",
                ],
            },
        },
        alias: {
            "@": "/src",
        },
    });
};
```

Thanks guys!🙏🏻
I hope this issue and some other Docker related pain points will be addressed by the Strapi team at some point.

**Comment by remi-viau** [comment]
Hello all,

I tried all of your solution and no one is working in 5.9.0.

Can you confirm that the problem is completely gone from your side ?

Thanks
