### ISSUE TITLE
How to do plugins config override?

### ISSUE THREAD

**Issue by caoer** [strapi/strapi#2142]
**What is the expected behavior?**

for example, in the following file
```
plugins/users-permissions/config/request.json
```
the content is
```
{
  "ratelimit": {
    "interval": 60000,
    "max": 10
  }
}
```

I'd like to change the `max` to 100. Is it possible for me to change it without modify the plugin? Or it is recommend to just modify the above file.

**Comment by lauriejim** [comment]
Hello @caoer thank you for this question.

When we will work on plugin interactions / configurations etc... we will make it configurable from your project config instead of override the plugin core code.

So today you have to modify the plugin file.
