### ISSUE TITLE
Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by prabhat-cn** [strapi/strapi#21438]
### Required System information

- Node.js version: 18
- NPM version: 9
- Strapi version:5.0.0
- Database:better-sqlite3
- Operating system: mac m1
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

![image](https://github.com/user-attachments/assets/9be65d48-133e-4af1-aa4f-4fd13bb0ae91)

**Comment by alexandrebodin** [comment]
Closing as duplicate https://github.com/strapi/strapi/issues/21267
