### ISSUE TITLE
[BUG] Forgot Password respond with "ok" for non-existent users or blocked users 

### ISSUE THREAD

**Issue by damancodes** [strapi/strapi#21450]
### Required System information

- Node.js version: v20.0.0
- NPM version:10.2.4
- Strapi version:5.0.0
- Database:
- Operating system:MacOs 14.5
- Is your project Javascript or Typescript:

### Describe the bug

Forgot password always returns ok even for blocked or non-existent users, causing unintended behavior

### Screenshots

<img width="721" alt="image" src="https://github.com/user-attachments/assets/a97158bc-9527-4d5c-9b15-60ba943bfd38">

**Comment by derrickmehaffy** [comment]
This is intended so that we do not leak if the user exists or is blocked: https://github.com/strapi/strapi/blob/146a31b564bc8232686331f6b28f7ff966817963/packages/plugins/users-permissions/server/controllers/auth.js#L247-L249
