### ISSUE TITLE
Error : update strapi v4 to v5

### ISSUE THREAD

**Issue by ra-devmaster** [strapi/strapi#21462]
- Node.js version: v20.17.0
- NPM version: 10.8.3
- Strapi version: 4.25.11 to 5.0.0
- Database: "mysql2": "^3.11.1",
- Operating system: LocalHost windows
- Is your project Javascript or Typescript: JS

### The bug

Hi, 
I managed to upgrade my strapi 4.25.10 to 4.25.11, however when I want to go from v4 to v5 I get this error after running npx @strapi/upgrade major as on the documentation

### Screenshots

![image](https://github.com/user-attachments/assets/43d012e5-32c8-4b43-8939-a4e43de95a71)
![image](https://github.com/user-attachments/assets/b8cf0d63-be4a-4617-8468-1bbace07d375)

And on github i have only that change :
![image](https://github.com/user-attachments/assets/14b30617-cc04-4f94-9a5f-63465525b7ac)

After that, if I run npx strapi -v, I'm obviously still in 4.25.11.

**Comment by zjjtm** [comment]
I got same problem.

**Comment by derrickmehaffy** [comment]
Weird because that package absolutely does exist: https://www.npmjs.com/package/@strapi/plugin-cloud

What is your npm registry set to?

**Comment by zjjtm** [comment]
> Weird because that package absolutely does exist: https://www.npmjs.com/package/@strapi/plugin-cloud
> 
> What is your npm registry set to?
npmjs.com

The commentsBot said try to clean the node_modules dir before running the migration script, I did that way but still the error.

**Comment by ra-devmaster** [comment]
All the minor updates on v4 work, but the problem persists when trying to upgrade to v5. Perhaps `--force` or `--legacy-peer-deps` is missing in your script when you're running the installation to avoid the issues we're experiencing here.

I deleted the `node_modules` folder, but that didn’t help—I’m still getting the error. And if I run `npm i`, I get the same error.

---

I then tried deleting the `node_modules` folder and running `npm i --legacy-peer-deps`. This time, the installations complete but with warnings:  
![image](https://github.com/user-attachments/assets/a36847df-2a7f-43eb-a83b-f3e78369052b)

After doing that, I ran `npx @strapi/upgrade major` and got this message:  
![image](https://github.com/user-attachments/assets/688afebe-744a-4b4b-988b-57780cf17f40)

But in the end, it doesn’t change anything, and I still have the same error as before.

For your information, I’m working locally, and the site has never been hosted—I started it two weeks ago.

**Comment by gbgabo** [comment]
@ra-devmaster The warnings regarding packages' vulnerabilities doesn't seem to be inherently a upgrade problem, as I just installed a brand new project (current 5.0.1) and on the process it showed many similar packages warnings. Not sure if it helps for the issue, but just so everybody knows:

![image](https://github.com/user-attachments/assets/b0c2b498-223c-4b1c-8631-466c7630056d)

Also, coincidentally I was facing the same issue for upgrading and I share the same situation on being a project never deployed and started around 2 weeks.

In my case, conveniently I was able to simply restart a project, as I was still testing a lot with no real data. Hope everything gets solved for you!

**Comment by ra-devmaster** [comment]
No, nothing works, and even doing a V5 project causes problems.

**Comment by abinici** [comment]
If you are getting the above npm error, try running the following command:

```
npm i @strapi/strapi@latest @strapi/plugin-users-permissions@latest
```

This will install the latest version of the two packages, which should be version 5.0.1. After running this command, I was able to build and run Strapi without any issues.

**Comment by derrickmehaffy** [comment]
Related TID: 8306, setting as high as a result.

While we with the Strapi Support team have not been able to reproduce this issue it's not the first we have seen of it so marking as confirmed just based on pure volume.

Likely related to: https://github.com/strapi/strapi/issues/20298

**Comment by ra-devmaster** [comment]
Thank you for all your answers. I ended up just recreating a new project, I lost everything but that's okay.

**Comment by stefan-golus** [comment]
Recreating a new project is not a solution.
I also cannot upgrade v4 (4.25.13) to v5

**Comment by zjjtm** [comment]
> We have also issues upgrading to v5 from v4 (4.25.13).

The upgrade always fails. Given the situation that v5 has so many issues right now, I think it's better to keep v4, upgrading the version is too risky for production.

**Comment by zjjtm** [comment]
> We have also issues upgrading to v5 from v4 (4.25.13).

Problem solved.

Step 1: Before the upgrade, **remove** "@strapi/plugin-graphql" or any other plugins which may affect the upgrade in the package.json, save file
Step 2: Run "npx @strapi/upgrade latest"(After I did step 1, this time it goes very well)
Step 3: Run build
Step 4: Strapi 5 can only use the mysql2 package for MySQL databases, and the **client value** for it **must be** set to mysql
Step 5: Run develop, and enjoy v5 :)

**Comment by ShahnawazHussain28** [comment]
I am too facing this errors while upgrading to v5 from v4.25.13. 

```
[WARN]  [2024-11-20T07:41:19.643Z] Please make sure you've created a backup of your codebase and files before upgrading
[INFO]  [2024-11-20T07:41:21.985Z] Upgrading from v4.25.13 to v5.4.0
[INFO]  [2024-11-20T07:41:21.997Z] (1/4) Checking requirement...
[ERROR] [2024-11-20T07:41:21.998Z] Requirement failed: Doing a major upgrade requires to be on the latest v4 version, but found 3 versions between the current one and 5.4.0. Please upgrade to 4.25.16 and try again. (REQUIRE_LATEST_FOR_CURRENT_MAJOR)

```

Now I am stuck. Please reopen this ticket. Waiting for a valid fix.

**Comment by mtte** [comment]
@ShahnawazHussain28 The issue you are facing is not a bug. Before upgrading to v5 you have to be on the latest v4 version. Run `npx @strapi/upgrade minor` first, then the upgrade to v5. Check if it works or if you then run into the same error as reported in this issue.

**Comment by ShahnawazHussain28** [comment]
In the documentation it is mentioned to run `npx @strapi/upgrade minor`. But doing so doesn't upgrade the strapi version at all.

Here is a complete log of running `npx @strapi/upgrade minor`
```
❯ npx @strapi/upgrade minor
[WARN]  [2024-11-20T11:16:09.322Z] Please make sure you've created a backup of your codebase and files before upgrading
[INFO]  [2024-11-20T11:16:10.024Z] Upgrading from v4.25.13 to v4.25.16
[INFO]  [2024-11-20T11:16:10.035Z] (1/4) Checking requirement...
[INFO]  [2024-11-20T11:16:10.059Z] (2/4) Applying the latest code modifications...
[INFO]  [2024-11-20T11:16:10.072Z] (3/4) Upgrading Strapi dependencies...
[INFO]  [2024-11-20T11:16:10.074Z] (4/4) Installing dependencies...
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/content-releases@4.25.13
npm WARN Found: styled-components@5.3.11
npm WARN node_modules/styled-components
npm WARN   styled-components@"^5.3.11" from the root project
npm WARN   15 more (@strapi/admin, @strapi/helper-plugin, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer styled-components@"5.3.3" from @strapi/content-releases@4.25.13
npm WARN node_modules/@strapi/content-releases
npm WARN   @strapi/content-releases@"4.25.13" from @strapi/strapi@4.25.13
npm WARN   node_modules/@strapi/strapi
npm WARN 
npm WARN Conflicting peer dependency: styled-components@5.3.3
npm WARN node_modules/styled-components
npm WARN   peer styled-components@"5.3.3" from @strapi/content-releases@4.25.13
npm WARN   node_modules/@strapi/content-releases
npm WARN     @strapi/content-releases@"4.25.13" from @strapi/strapi@4.25.13
npm WARN     node_modules/@strapi/strapi

up to date, audited 1566 packages in 9s

183 packages are looking for funding
  run `npm fund` for details

21 vulnerabilities (7 low, 11 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
[INFO]  [2024-11-20T11:16:19.094Z] Completed in 9.770sms
❯ npx strapi -v
4.25.13
```

This did not upgrade the strapi to the latest v4 version. That's why `npx @strapi/upgrade major` still not working.

**Comment by ShahnawazHussain28** [comment]
Any updates so far on this? @mtte ? Anyone ? 
At some point I have to upgrade to v5 before v4 gets deprecated. Any help is appreciated.

**Comment by mchaurais-procore** [comment]
I was having a similar problem and what solved was to remove package-lock.json file and run npm install again. I hope it helps. :/

**Comment by mSenad** [comment]
Hi everyone,

I was trying to resolve the issue and what I come up with that works for me is following.

- I had all of my Strapi libraries set to `v4.25.17` and made sure that everything is working locally
- Removed `package-lock.json` and `node_modules`
- I was using NPM for my packages ( I see cases above that people are using npm as well ), but I've switched to yarn and made sure that my packages were installed with yarn before I ran `npx @strapi/upgrade major`.

This actually resolved my issue just by switching from npm to yarn. Hope will resolve to some of you too.

**Check the screenshots as well for more inform
<img width="1224" alt="Screenshot 2024-11-27 at 10 45 59 AM" src="https://github.com/user-attachments/assets/2273af6b-34c8-4dc0-8def-51dfe32c9bca">
ation**
<img width="1468" alt="Screenshot 2024-11-27 at 10 43 33 AM" src="https://github.com/user-attachments/assets/04bb62ed-a394-4759-aef3-9a34597b71c3">
<img width="1466" alt="Screenshot 2024-11-27 at 10 43 57 AM" src="https://github.com/user-attachments/assets/914c9c52-c2b8-4861-8ab3-0e551dee19f1">

**Comment by JeysonOrellano** [comment]
Hola a todos lo que realize 
1.- Actualizar strapi 4 a su ultima version 
2.- Agregar el comando npx @strapi/upgrade major--- en este caso solo actulizaba y eliminaba el packete "@strapi/plugin-i18n"  en mi caso no actulizaba a strapi 5 
3.- Eliminacion de paketes que no tiene compatibilidad con strapi 5 para luego actualizar manual a la version 5.4
![image](https://github.com/user-attachments/assets/257c8e0e-0aef-484b-a088-f754bca4c082)
4.- Instalacion de mysql2...Con ello te pedira actualizar   ssl: env.bool('DATABASE_SSL') ? { rejectUnauthorized: false } : false, 
5.- Npm run build y npm run start 
![image](https://github.com/user-attachments/assets/04c12df5-bc3e-4815-868a-81b7a21b9955)

**Comment by JeysonOrellano** [comment]
Hello everyone, what I did:
1.- Update Strapi 4 to its latest version
2.- Add the npx command @strapi/upgrade major--- in this case it only updated and removed the package "@strapi/plugin-i18n" in my case it did not update to Strapi 5
3.- Removal of a package that is not compatible with Strapi 5 and then manually updating to version 5.4
![image](https://github.com/user-attachments/assets/257c8e0e-0aef-484b-a088-f754bca4c082)
4.- Installation of mysql2...With this it will ask you to update ssl: env.bool('DATABASE_SSL') ? { rejectUnauthorized: false } : false,
5.- Npm run build and npm run start
![image](https://github.com/user-attachments/assets/04c12df5-bc3e-4815-868a-81b7a21b9955)

**Comment by GintokiYT** [comment]
@JeysonOrellano me cagastes el dia con tu solucion

**Comment by GintokiYT** [comment]
@JeysonOrellano ya pero presenta a tu flaca :3
