### ISSUE TITLE
When creating a localized entry, non-localizable fields are deleted

### ISSUE THREAD

**Issue by Nicolas-Deleplace** [strapi/strapi#21476]
### Required System information

Node.js version: 18.17.0
Yarn version: 1.22.22
Strapi version: 5.0.1
Database: PostgreSQL
Operating system:  darwin-arm64 (Mac OS)
Environment: development
Is your project Javascript or Typescript: Typescript

### Describe the bug

When I create a localized entry in Strapi, fields that are non-localizable are unexpectedly deleted from the entry.

### Steps to reproduce the behavior

1. Go to the content manager and create a new entry for a localized content type.
2. Fill in all the fields, including non-localizable ones.
3. Save the entry and switch to another locale.
4. Observe that the non-localizable fields are missing from the newly created localized entry.

### Expected behavior

The non-localizable fields should be retained when creating localized entries and should not be deleted.

### Screenshots

https://github.com/user-attachments/assets/46c7c11f-8396-43cd-9a1a-da1f9431d746

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/21594
