### ISSUE TITLE
Strapi 5 with nginx proxy pass not loading admin panel

### ISSUE THREAD

**Issue by giorgiocolombo** [strapi/strapi#21479]
Environment: development
OS: linux-arm64
Strapi Version: 5.0.1
Node/Yarn Version: npm/10.8.2 node/v20.17.0 linux arm64 workspaces/false
Edition: Community
Database: postgres

admint.ts
```
export default ({ env }) => ({
  auth: {
    secret: env("ADMIN_JWT_SECRET"),
  },
  apiToken: {
    salt: env("API_TOKEN_SALT"),
  },
  transfer: {
    token: {
      salt: env("TRANSFER_TOKEN_SALT"),
    },
  },
  flags: {
    nps: env.bool("FLAG_NPS", true),
    promoteEE: env.bool("FLAG_PROMOTE_EE", true),
  },
  url: `${env("STRAPI_BASE_URL", "http://localhost:1337")}/admin`,
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
});

```
servert.ts
```
export default ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  url: env("STRAPI_BASE_URL", "http://localhost:1337"),
  app: {
    keys: env.array("APP_KEYS"),
  },
});

```

.env
`STRAPI_BASE_URL= http://localhost/strapi
`

nginx.conf
```
...
location /strapi/ {
            rewrite ^/strapi/?(.*)$ /$1 break;
            proxy_pass http://strapi:1337;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_pass_request_headers on;
        }
...
```

with this configuration i'm only able to fetch api in my app and enter admin panel directly at localhost:1337, but **following the url at proxy the admin panel tries to reach some files at the root directory and not the proxy directory**:
![image](https://github.com/user-attachments/assets/da0f582c-e851-4cc0-8287-7e7bba3e10ca)

**Comment by raphaelbadawi** [comment]
Same issue than => https://github.com/strapi/strapi/issues/21452

Very critical IMO (breaking production).

**Comment by mad-zephyr** [comment]
Hello and sorry, any updates related to this bug?

**Comment by raphaelbadawi** [comment]
> Hello and sorry, any updates related to this bug?

Yes. [This PR, currently being reviewed](https://github.com/strapi/strapi/pull/21507). Personally I've put manually the changes of the PR in my Strapi instance, it's currently working on production on my side.
