### ISSUE TITLE
Broken links on your website

### ISSUE THREAD

**Issue by flawyte** [strapi/strapi#2148]
**Informations**
- **Operating system**: Windows 10

**What is the current behavior?**
Some links on the website are broken.

**Steps to reproduce the problem**
- Go to https://strapi.io/overview
- Scroll down to the section named **Robust Node.js framework layer**
- Click on the following links to get a 404 :
![image](https://user-images.githubusercontent.com/1585006/47013946-1b8f6400-d149-11e8-9da7-c717d16cd2ff.png)

**What is the expected behavior?**
Links should redirect to the relevant section in the online documentation.

**Suggested solutions**
I think they're all missing `/3.x.x` after the `/documentation` part of the URL.

For example :
`https://strapi.io/documentation/configurations/configurations.html#database`
should be
`https://strapi.io/documentation/3.x.x/configurations/configurations.html#database`

--
I'll try to submit a PR to fix that, if it's okay.

*EDIT:* Can't find the source for strapi.io, I guess it's not public.

**Comment by lauriejim** [comment]
Thank you to report this issue. 
You can't fix it on your side. I will update our website soon as I can.

Thank you.
