### ISSUE TITLE
Unable to add relation to collection/single types with User from Content-Type Builder

### ISSUE THREAD

**Issue by Dudy83** [strapi/strapi#21482]
### Required System information

- Node.js version: 18.19.1
- NPM version: 10.2.4
- Strapi version: 5.0.1
- Database: psql
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Hello,
After installing the new Strapi v5, we are unable to create relation to the collection/single types with users-permissions plugin.
Relations `User (from: admin) ` & `User (from: users-permissions)` aren't appearing in the choices list.

### Steps to reproduce the behavior

1. Go to 'Content Type Builder'
2. Click on 'Any collection/single type'
3. Add 'Relation field'
4. User choice doesn't appear
![image](https://github.com/user-attachments/assets/0f8bbe3f-6b10-443c-8363-83c92997ffe3)

### Expected behavior

User should appear in the list of relations to be able to create admin or normal users relation to the collection/single types.

### Additional context

Adding manually the relation in the schema.json works, and field appear in the Content-Type Builder and is modifiable in the Content Manager
![image](https://github.com/user-attachments/assets/58f51e1b-cbbb-4662-a6eb-f7a972c4ecc6)
![image](https://github.com/user-attachments/assets/8261af8c-ae8b-4ed9-a935-365277d21b38)
![image](https://github.com/user-attachments/assets/2fbb3fb9-6dce-4c75-863e-f04fa386255c)

It also works retrieving it in the controller and populate it in the api.
![image](https://github.com/user-attachments/assets/5117f4b8-3968-4f34-8253-0ee89c3ad1ed)
![image](https://github.com/user-attachments/assets/2d24e024-1763-4bd6-8fbb-27f8a060643f)

**Comment by IskanVa** [comment]
Same problem

**Comment by derrickmehaffy** [comment]
this has been fixed in later versions of Strapi 5
