### ISSUE TITLE
Copying API token to clipboard triggers "save" action

### ISSUE THREAD

**Issue by innerdvations** [strapi/strapi#21499]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.2-beta.0
Node/Yarn Version: yarn/4.5.0 npm/? node/v20.9.0 darwin arm64
Edition: Enterprise
Database: sqlite
### Describe the bug

When clicking the "copy to clipboard" icon after creating an API token, I get a "Success: API Token successfully edited" toast message

It actually sends a 200 PUT  network request as well to update the token, which could potentially cause some issues

Note: I noticed similar behaviour on the role permissions editor as well, where clicking on the configure button triggered a save, so the bug is probably at a higher level than api tokens

### Steps to reproduce the behavior

1. Create an API token
2. Click the copy to clipboard icon
3. the "edited" popup appears

### Expected behavior

Should not see "API Token successfully edited"

### Screenshots

![image](https://github.com/user-attachments/assets/65f546d8-e05b-4e7c-b9bb-627d7f0a1d19)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by sah246ir** [comment]
do i need to get this issue assigned to me so that i can work on it ?

**Comment by innerdvations** [comment]
Hi @sah246ir , we don't assign issues but you're free to work on it if you'd like to contribute!

**Comment by sah246ir** [comment]
understood!
