### ISSUE TITLE
Setup fails under Node 8 / npm 5

### ISSUE THREAD

**Issue by dj-hedgehog** [strapi/strapi#215]
**Node.js version**: v8.1.2
**npm version**: 5.0.3
**Strapi version**: alpha.4
**Operating system**: macOS 10.12.5

**Reproduction steps:**
```
git clone git@github.com:strapi/strapi.git
git checkout alpha.4
npm run setup
```

**Expected result:**
Strapi is successfully installed

**Actual result:**
```
➜  strapi git:(alpha.4) ✗ npm run setup

> @3.0.0-alpha.3 setup /Users/ali/storyx/faktoora/strapi3/strapi
> npm install && node ./scripts/setup.js

added 32 packages, removed 218 packages and updated 63 packages in 17.748s
module.js:487
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
```

**Comment by dinoRkz** [comment]
Strapi 3.0 is under construction. So can work only with strapi 1.0 which runs smoothly when you have node v4.4.3 and mongodb v3.0.5

**Comment by Aurelsicoko** [comment]
Thanks for reporting this issue! As you know the v3 is still under active development so it will be fixed quickly and more especially thanks to the release of the `alpha.4` on npm.

**Comment by dj-hedgehog** [comment]
What do you mean? Wasn't alpha.4 released weeks ago when there was not even Node 8 released?

**Comment by Aurelsicoko** [comment]
The `alpha.4` isn't released yet. We are aware of this issue and we will fix it for the `alpha.4` release.

**Comment by YUFENGWANG** [comment]
when will the 3.0 get done? I am looking forward to it. hhh

**Comment by Aurelsicoko** [comment]
@YUFENGWANG We plan to release at the end of September. The release also means a brand new website and documentation. However, we will release new alpha versions before and you will be able to test it.

**Comment by dj-hedgehog** [comment]
@Aurelsicoko I run `npm run setup` with the latest master on Node v8.2.1 and got these 2 errors and 1 warning. The setup finished nonethless Here are they in order of appearance.

Error #1
```
> strapi-generate@3.0.0-alpha.4.8 prepublish /Users/ali/projects/nodejs/node8/strapi/packages/strapi-generate
> npm prune

npm ERR! May not delete: /Users/ali/projects/nodejs/node8/strapi/packages/strapi-generate/node_modules/.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ali/.npm/_logs/2017-07-25T14_17_18_234Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-generate@3.0.0-alpha.4.8 prepublish: `npm prune`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-generate@3.0.0-alpha.4.8 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ali/.npm/_logs/2017-07-25T14_17_18_268Z-debug.log
npm notice created a lockfile as package-lock.json. You should commit this file.
+ strapi-utils@3.0.0-alpha.4.8
added 1 package in 0.555s
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
```

Warning #1 

```
> ngrok@2.2.2 postinstall /Users/ali/projects/nodejs/node8/strapi/packages/strapi-admin/files/public/node_modules/ngrok
> node ./postinstall.js

(node:36082) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
```

Error #2 
```
> strapi-mongoose@3.0.0-alpha.4.8 prepublish /Users/ali/projects/nodejs/node8/strapi/packages/strapi-mongoose
> npm prune

npm ERR! May not delete: /Users/ali/projects/nodejs/node8/strapi/packages/strapi-mongoose/node_modules/.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ali/.npm/_logs/2017-07-25T14_19_41_138Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-mongoose@3.0.0-alpha.4.8 prepublish: `npm prune`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-mongoose@3.0.0-alpha.4.8 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ali/.npm/_logs/2017-07-25T14_19_41_175Z-debug.log
npm notice created a lockfile as package-lock.json. You should commit this file.
```

**Comment by chunnguyenninja** [comment]
I got the same isssue above, something wrong with `strapi-generate@3.0.0-alpha.4.8`, and `strapi-mongoose@3.0.0-alpha.4.8`. I look forward to hear from you guys soon. @Aurelsicoko

**Comment by chunnguyenninja** [comment]
thanks @pierreburgy for this answer:
1. dev environment: `node 8.1.4`, `npm 5.3.0`
2. `npm link strapi-mongoose` then `strapi start`
3. if you have this error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: watch ~/admin/public/node_modules/micromatch/README.md ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1384:19)
    at Object.fs.watch (fs.js:1410:11)
```
try to remove rm `your_project_dir/admin/public/node_modules`
@dj-hedgehog

**Comment by Aurelsicoko** [comment]
@dj-hedgehog These are just warning, the installation process should work though. They are due to npm@5 which seems to not well support the `npm prune` command with the new `package-lock.json` file. That's why, we decided to not commit these files until hile npm@5 is more stable.

**Comment by Aurelsicoko** [comment]
I'm closing the issue, it has been fixed in the next release `alpha@5`.
