### ISSUE TITLE
Aggregation not send correct values

### ISSUE THREAD

**Issue by jrperdomoz** [strapi/strapi#2151]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3 
- **Database**: mongo 4.01
- **Operating system**: macOS 10.14

**What is the current behavior?**
using the ${model}Connection query I do not receive the correct values

**Steps to reproduce the problem**
I'm trying to get the number of documents from a query. I have a Contact model, so I have the following query:
![contacts_aggregation](https://user-images.githubusercontent.com/2061711/47039693-3257aa00-d18d-11e8-921f-16436a168978.png)

(I know that only 2 documents fulfill this filtering.) The count is correct but in the values ​​those fields that I used for the filtering are not solved correctly.

**What is the expected behavior?**
Get the correct count and the correct values.
At the moment I had to do this:
![resultadoesperado](https://user-images.githubusercontent.com/2061711/47042480-07248900-d194-11e8-899d-0dd5e4b15040.png)

**Suggested solutions**
no suggestion

**Comment by kamalbennani** [comment]
Weird, I'll try to investigate this afternoon, I'll keep updated. thanks for reporting this bug.

**Comment by byoungd** [comment]
@lauriejim 
version-
strapi: v3.0.0-alpha.24.1
node: 10.15.1
OS: CentOS 7.2

Still has the problem as shown above.

Any progress?

**Comment by kamalbennani** [comment]
Fixed by https://github.com/strapi/strapi/pull/2452
