### ISSUE TITLE
hasOne relationship dropdown not populating correctly in a repeatable component

### ISSUE THREAD

**Issue by gmoigneu** [strapi/strapi#21517]
### Required System information

- Node.js version: v20.17.0
- NPM version: yarn/1.22.22
- Strapi version: 5.0.1
- Database: Postgres
- Operating system: MacOS Sequoia
- Is your project Javascript or Typescript: TS

### Describe the bug

When adding or edting a repeatable component that has a `hasOne` relation, the dropdown for that relationship is empty at first. You have to `Save` the type for the dropdown to populate. 

Sometimes it is required to save multiple times. Some other times, some entities are not in the list and you need to Save again so they appear.

The problem appears on all relations no matter the type in the project. Tested on a blank new project as well.

Strapi generates a SQL error:

```
[2024-09-28 08:47:10.026] error: select "t0".*, "t0"."id" from "public"."components_pages_icon_text_blocks" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "kutz88nv52j0tus2p3ajodn2"
error: select "t0".*, "t0"."id" from "public"."components_pages_icon_text_blocks" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "kutz88nv52j0tus2p3ajodn2"
    at Parser.parseErrorMessage (/Users/nls/projects/arkea-rebuild/backend/node_modules/pg-protocol/src/parser.ts:368:69)
    at Parser.handlePacket (/Users/nls/projects/arkea-rebuild/backend/node_modules/pg-protocol/src/parser.ts:187:21)
    at Parser.parse (/Users/nls/projects/arkea-rebuild/backend/node_modules/pg-protocol/src/parser.ts:102:30)
    at Socket.<anonymous> (/Users/nls/projects/arkea-rebuild/backend/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

It actually tries to find the component (`IconTextBlock`) instance by document ID instead of integer ID.

### Steps to reproduce the behavior

1. Edit a dynamic zone with a repeatable component with a `hasOne` relation
2. Add an instance of the component
3. Try to select the related entity, the dropdown is empty
4. Save
5. Now the dropdown is populated

### Expected behavior

The relation dropdown should be populated with all published entities by default.

### Screenshots

![2024-09-28 08 32 41](https://github.com/user-attachments/assets/fbcc36df-d829-407a-b374-4fdc48f7dacc)

![2024-09-28 08 46 16](https://github.com/user-attachments/assets/10d7626f-4491-43e2-b912-c67584b53efb)

### Code snippets

N/A

### Additional context

N/A

**Comment by karpov3** [comment]
Hello @Marc-Roig ,
I had the same problem.

### Required System information

- Strapi - 5.0.6
- Mysql 8.0.39 (MySQL Community Server - GPL)
- Npm 10.8.3
- Node v20.17.0

To reproduce error:
1. Install 
npx create-strapi-app@latest

> ? Please log in or sign up. Skip
> ? Do you want to use the default database (sqlite) ? No
> ? Choose your default database client mysql
> ? Database name: strapi3
> ? Host: 127.0.0.1
> ? Port: 3306
> ? Username: root
> ? Password: ********
> ? Enable SSL connection: No
> ? Start with an example structure & data? Yes
> ? Start with Typescript? Yes
> ? Install dependencies with npm? Yes
> ? Initialize a git repository? No

2.  Add Collection Type "ranking" with field Text.
![Screenshot 2024-10-15 at 17 29 45](https://github.com/user-attachments/assets/9f567f03-36f5-433f-a96a-cc71cb8390ff)

Add 2 rows with values 1, 2

3. Create "ranking" component with field "Relation" from Collection Types "ranking".
![Screenshot 2024-10-15 at 17 36 51](https://github.com/user-attachments/assets/1e511618-f87b-45f4-a68e-ad9ece4801dc)

4. Add "raking" Component (repeatable) to Article. And Save.
![Screenshot 2024-10-15 at 17 39 37](https://github.com/user-attachments/assets/43156149-e633-4b9f-982c-82f0f05e0687)

5. In Content Manager in article add ranking value. **Here not working. No relations available**.

![Screenshot 2024-10-15 at 17 40 48](https://github.com/user-attachments/assets/a6ce5e07-b213-4e8b-91ad-44f2cb733ea1)

**Comment by Marc-Roig** [comment]
@karpov3 thank you!! I will try to reproduce

**Comment by Brdnn** [comment]
I am having same issue

**Comment by Marc-Roig** [comment]
could you try reproducing the issue in 5.1.0 , @karpov3  I have tried your setup (thank you for the steps) and I can not manage to reproduce!

**Comment by karpov3** [comment]
@Marc-Roig Everything works fine with the new version (5.1.0)—no problems on my side. Thank you.

**Comment by ZahraaMahmood** [comment]
I'm facing the same issue - thinking about using plugin to overwrite the view [still searching]
I use strapi v5 - typescript project, I created one to many relationship in one of my content types and the component doesn't show proper elemnt when I pick an element, and if I send request by the API it shows the number of element but not the relation element which made me think I'm doing it wrong - checked the network it's there but not being displayed in the dashboard just the number of the item is correct while the item isn't visible 

<img width="1005" height="325" alt="Image" src="https://github.com/user-attachments/assets/c6608f2f-0e73-4ca5-8b33-c850d56fc8e0" />

<img width="761" height="291" alt="Image" src="https://github.com/user-attachments/assets/b46fdc26-879d-4543-b71d-989dab9e2ce9" />
It has 86 element made by api but not showing any in the dashboard
