### ISSUE TITLE
Rename custom schema.graphql to schema.graphql.js

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#2152]
**What is the expected behavior?**
I'd like the custom graphql schema defined in ```./api/*/config/schema.graphql``` to allow the use of a ```.js``` file ending. 

Since these files are not actually .graphql formatted files it causes a lot of issues with syntax highlighting in IDE's. Also they aren't truly .graphql files so they should really be labelled as such.

I'd propose that to acheive backward compatibility that the system would allow for either ```schema.graphql``` or ```schema.graphql.js``` as a valid file name.

**Comment by Aurelsicoko** [comment]
Sure! Can you make a PR? A good start point could be the hook which loads the files into the AST https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/hooks/graphql/index.js#L34
