### ISSUE TITLE
Bug Report: Unable to filter/sort/search admin users by email - ValidationError

### ISSUE THREAD

**Issue by mythuong1306** [strapi/strapi#21536]
When accessing the admin user section and attempting to filter, sort, or search by email, I encountered the following error message:

{
  status: 400,
  name: "ValidationError",
  message: "Invalid parameter email",
  details: {}
}
It appears that 'email' is not included in the **ADMIN_USER_ALLOWED_FIELDS** for filtering or sorting, which is unexpected. Since email is a critical field for identifying admin users, I believe it should be included in the allowed fields for these operations.

**Steps to Reproduce:**

1. Navigate to the Admin Users section.
2. Attempt to filter, sort, or search users by email.
3. Observe the error message.

**Expected Behavior:** Admin users should be filterable, searchable, and sortable by their email addresses without triggering a validation error.
Let me know if additional information is required. Thank you for your support!

**Comment by Ruwaid884** [comment]
Can i take it under the Octoberfest . Can you assign me this ?

**Comment by kavyamohan2000** [comment]
I would like to work on this under hacktoberfest

**Comment by AayushhGoyal** [comment]
I would like to work on it

**Comment by FurquanAnwer** [comment]
Please assign this to me
