### ISSUE TITLE
useFetchClient only handles json responses

### ISSUE THREAD

**Issue by cdreier** [strapi/strapi#21534]
### Describe the bug

we are migrating several local admin plugins to strapi5 - which is pretty awesome btw, so many great new apis to work with :heart: 

we want to download a zip file, which is created on the server. obviously zip files cannot be parsed as json - therfore the new `useFetchClient` with its responseInterceptor takes over, and just returns an empty list without any error

https://github.com/strapi/strapi/blob/develop/packages/core/admin/admin/src/utils/getFetchClient.ts#L123

### Steps to reproduce the behavior

1. use the new useFetchClient
2. return anything than json from a plugin api
3. wonder why you get any empty file

### Expected behavior

depending on the content-type, return `text()` / `blob()` or `json()`

**Comment by cdreier** [comment]
@Boegie19 from my pov this is more a regression as this worked pretty well in v4 for example 

```jsx
const { get } = useFetchClient();
//[...]
get(url, {
  responseType: 'blob',
})
```

anyway, i would take care of it to implement a similar api in the new fetchClient?

**Comment by alexandrebodin** [comment]
Hi @cdreier if you are interesting in contributing I think this wouldn't hurt to allow the fetchClient to support other responseTypes. We never really considered someone would be using it for this but why not :)

**Comment by cdreier** [comment]
Hi @alexandrebodin i fiddled around, and tbh i am not able to create appropriate typings  - we solved the main problem in another way, using the fetch client with the jwt. wdyt, is it worth to give it another try? from my pov we also can close this issue

**Comment by alexandrebodin** [comment]
Let's close it for now and we will see if we get more request like that before investing too much time :) 
Thanks for looking into it ! I'll flag it as feature request so it gets the right treatment 👍

**Comment by ericbf** [comment]
This is still required, and shouldn’t be closed. The workaround shouldn’t be to just not use `useFetchClient`, which handles other things like authorization.

**Comment by NawfelBengherbiaSfeir** [comment]
We stumbled on the same issue when updating our plugin to work on Strapi 5.

The current limited API does not let us request non JSON data from the server. This is quite frustrating as we need to go through workarounds to do basic things.

Excuse me, but the current design is half-arsed and needs fixing.

**Comment by yunusyuksel** [comment]
That issue still exists

**Comment by yunusyuksel** [comment]
> Hi [@alexandrebodin](https://github.com/alexandrebodin) i fiddled around, and tbh i am not able to create appropriate typings - we solved the main problem in another way, using the fetch client with the jwt. wdyt, is it worth to give it another try? from my pov we also can close this issue

How do you get the jwt token in custom plugin admin code ?  , I could not figure it out where its stored

**Comment by cdreier** [comment]
> How do you get the jwt token in custom plugin admin code ? , I could not figure it out where its stored

we are using this snippet, at least it is working...

```ts
import Cookies from "js-cookie";


const STORAGE_KEYS = {
  TOKEN: 'jwtToken',
  USER: 'userInfo',
};

const getToken = () =>
  JSON.parse(
    localStorage.getItem(STORAGE_KEYS.TOKEN) ??
    sessionStorage.getItem(STORAGE_KEYS.TOKEN) ??
    '""'
  ) || Cookies.get(STORAGE_KEYS.TOKEN);


export const getAuthHeader = () => {
  return {
    Authorization: `Bearer ${getToken()}`,
  };
}
```

**Comment by Adzouz** [comment]
Hi there! So sorry for the delay and lack of response but we wanted to find a solution that satisfy everyone.
I'm glad to tell you that there's a new `responseType` parameter that you can use now:
```
const { get } = useFetchClient();
const { data: blob, headers } = await get(url, { responseType: 'blob' });
```
It can be one of the following value: `json` | `blob` | `text` | `arrayBuffer`

I hope it will give you more flexibility and solve this issue 🙏
It will be part of the release of Strapi on Wednesday April 29th 🚀
