### ISSUE TITLE
afterCreate() being called twice - strapi v5

### ISSUE THREAD

**Issue by oismaelash** [strapi/strapi#21535]
### Required System information

- Node.js version: v20.12.1
- NPM version: 10.5.0
- Strapi version: 5.0.1
- Database: postgres
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

My Code into afterCreate run twice

### Expected behavior

My Code into afterCreate run once

### Code snippets

```ts
import { SendMessageCommand, SQSClient } from "@aws-sdk/client-sqs";

export default {
    async afterCreate(event) {
        const { result } = event;

        const document = await strapi.documents("api::broadcast.broadcast").findOne({
            documentId: result.documentId,
            populate: {
                messages: {
                    fields: ["text", "messageRetry"],
                    populate: {
                        group: {
                            fields: ['number', 'name']
                        }
                    }
                },
                users_permissions_user: {
                    fields: ["campaignCount"]
                }
            }
        });

        const { users_permissions_user, messages, onePayment } = document
        console.log(users_permissions_user, messages)
        
        if (!onePayment) {
            console.log("campaignCount current", users_permissions_user.campaignCount)
            const documentUser = await strapi.documents("plugin::users-permissions.user").update({
                documentId: users_permissions_user.documentId,
                data: {
                    campaignCount: users_permissions_user.campaignCount + 1
                }
            });
            console.log("campaignCount updated:", documentUser.campaignCount)
        }
        
        const client = new SQSClient({
            credentials: {
                accessKeyId: process.env.STRAPI_AWS_ACCESS_KEY,
                secretAccessKey: process.env.STRAPI_AWS_SECRET_KEY
            }
        });
        const SQS_QUEUE_URL = process.env.STRAPI_AWS_SQS_URL

        messages.forEach(async message => {
            const command = new SendMessageCommand({
                QueueUrl: SQS_QUEUE_URL,
                MessageGroupId: users_permissions_user.id.toString(),
                MessageBody: JSON.stringify(message)
            });

            await client.send(command);
            console.log('sent to aws sqs', message)
        });

    },
};
```

**Comment by jackbuehner** [comment]
Have you reviewed https://docs.strapi.io/dev-docs/migration/v4-to-v5/breaking-changes/lifecycle-hooks-document-service? `afterCreate()` can be triggered multiple times due to the way locales and published/draft versions now work.

**Comment by franckadil** [comment]
@jackbuehner, I reviewed the documentation, but I am not able to find any example on how to control this behavior in order to avoid calling afterCreate() more than one time. Any example would be helpful.

**Comment by franckadil** [comment]
To ensure that the [`afterCreate`](command:_github.copilot.openSymbolFromReferences?%5B%22%22%2C%5B%7B%22uri%22%3A%7B%22scheme%22%3A%22file%22%2C%22authority%22%3A%22%22%2C%22path%22%3A%22%2Fhome%2Ffranck%2FProjects%2Fapps%2Fjunglewp-api%2Fapp%2Fsrc%2Fapi%2Fcontact%2Fcontent-types%2Fcontact%2Flifecycles.js%22%2C%22query%22%3A%22%22%2C%22fragment%22%3A%22%22%7D%2C%22pos%22%3A%7B%22line%22%3A1%2C%22character%22%3A8%7D%7D%5D%2C%22c79c6a71-b935-451e-bac6-3b756c1c1390%22%5D "Go to definition") lifecycle hook is triggered only once, you can add a check to see if the entry is in the draft state or published state. You can do this by checking the `publishedAt` field, which is `null` for drafts and has a date for published entries.

Here's how you can modify your 

lifecycles.js

 file:

1. Check if the `publishedAt` field is `null`.
2. If it is `null`, return early to avoid sending the email.

```javascript
module.exports = {
    async afterCreate(event) {    // Connected to "Save" button in admin panel
        const { result } = event;

        // Check if the entry is a draft
        if (result.publishedAt === null) {
            return;
        }

        try {
            await strapi.plugin('email').service('email').send({
              to: 'valid email address',
              from: 'your verified email address', // e.g. single sender verification in SendGrid
              cc: 'valid email address',
              bcc: 'valid email address',
              replyTo: 'valid email address',
              subject: 'The Strapi Email plugin worked successfully',
              text: '${fieldName}', // Replace with a valid field ID
              html: 'Hello world!', 
            });
        } catch (err) {
            console.log(err);
        }
    }
}
```

This way, the email will only be sent when the entry is published, not when it is saved as a draft.

**Comment by jackbuehner** [comment]
It would be better to create a document service middleware. `ctx.params.status` will equal `'published'` or `'draft'` based on its status. You can await `next()` to ensure the middleware runs last.

You can see examples under the parameters heading and at the end of the page at https://docs.strapi.io/dev-docs/api/document-service/middlewares
