### ISSUE TITLE
Strapi "type value is already exists" when I create any relation between specific models.

### ISSUE THREAD

**Issue by alling1505** [strapi/strapi#2154]
**Informations**
- **Node.js version**: 10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: mongo
- **Operating system**: Amazon Linux AMI

**What is the current behavior?**
I have some content types that I can not create the field relation with other content types, but just with specifc content types.
When I try to create any type of relation, in the Content Type Builder, I get the error that it says "type value is already exists", but there's no any relation between any content type in all the proyect.
I deleted all of the content types and I created it again without any relation, so I started to create the relations with the content types with problem but it appears the error again.
For example, I have so many content types but when I want to create the relation between the Terms content type with Language content type, it appears the error and no matter what kind of relation I try to create, the error always appears. But this doesn't happen when I create a relation between Terms content type and Country content type also doesn't appear when I create a relation between Buy model and Language content type.
![image](https://user-images.githubusercontent.com/38534086/47097054-c8bbb800-d1ed-11e8-80d1-119afa001e14.png)

**Steps to reproduce the problem**
-Create the content type language, with two string fields, name and code.
-Create another content type, terms with a json field, terms, and a relation with country and other with language.

**What is the expected behavior?**
Create the content type with the relation with any other content type without problems.

**Suggested solutions**
FIx it or tell me in what other way can I create the content type or the relations.

**Comment by derrickmehaffy** [comment]
@alling1505 are you using firefox? If yes please try with chrome. That error has been around for a while and is difficult to track down the exact cause, you should just be able to hit continue. You can try selecting another relation then reselect the oneWay.

This bug is usually only isolated to Firefox.

**Comment by derrickmehaffy** [comment]
@soupette I could of swore this got a fixed a while back?

**Comment by alling1505** [comment]
I am using Chrome and the problem is there. At first time in some content types it allowed me to create the  relations but when I checked the relation had been changed but later in other content types I tried to select another relation but the error continues with alm type of relations.

**Comment by lauriejim** [comment]
Not happen in last version of Strapi (alpha.16), will reopen if it appears again.

**Comment by vanpana** [comment]
Just happened to me...
<img width="742" alt="already exist" src="https://user-images.githubusercontent.com/13353799/56018612-48dd5900-5d0b-11e9-924b-6b7776a55d37.png">

**Comment by soupette** [comment]
Which version are you running? BTW, a cleaner version of the plugin will be released on monday.

**Comment by vanpana** [comment]
I'm on the latest version.

**Comment by daveleee** [comment]
Everytime I try to add Comment collection it shows me the similar behavior.
<img width="776" alt="image" src="https://github.com/strapi/strapi/assets/18183671/9718ab72-fece-437a-ae1f-23ed1f5081d3">
