### ISSUE TITLE
Replacing wysiwyg editor with a custom one doesn't work in Strapi 5

### ISSUE THREAD

**Issue by JakubVavra** [strapi/strapi#21548]
Hi, is this a still valid tutorial for replace default editor with custom?

https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi

I have a problem that app.addFields({ type: 'wysiwyg', Component: Wysiwyg }); will not replace default editor.

Plugin in loaded, but replacement did not happend.

Thanks for asnwer.

**Comment by derrickmehaffy** [comment]
That is a really old blog post that really shouldn't be used anymore since we have custom fields.

I'd suggest looking at some of the community custom field plugins instead.
