### ISSUE TITLE
Issue with Component Identification in Draft mode because of changing IDs in the API and no existing documentId field in components

### ISSUE THREAD

**Issue by Anubiso** [strapi/strapi#21565]
### Required System information

- Node.js version: yarn/1.22.22 npm/? node/v20.16.0 darwin arm64
- Strapi version: 5.0.1
- Database: postgres
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When using a collection type which is configured to use `draft & publish` and then using an inline component it is currently impossible to identify the entries of the component. Depending on the use case this is really important, because we may need to identify these records consistently. 

Example:

We have a collection which is called survey and each survey can have multiple options. Each option can have a title and an image. 
We want to use draft & publish and we really like the inline editing function of components as field in an entity. One Survey-Option is specific for one Survey and can never be re-assigned or shared with another survey. 

Now when we collect the data for showing of the surveys and also collection votes we can identify the surveys by the documentId, even if multiple changes were published and the id always incremented. But we can't identify the Survey Option. The ID always increments and the user is able to re-sort the components, so we can also not do something like: the first element of the options is Option 1. Only because you resorted the options or renamed them we don't want to loose for example the votes per option. 

Currently the only way around this is to either not use draft & publish at all to prevent always changing ids and thus not identifiable "components" because they have no documentId. Or to use relation fields, which are not as nice to use as components, because they don't allow inline editing and can also lead to errors like re-assigning an option to a wrong survey. 

### Expected behavior

Include a documentId in components or enable getting the original id of the component.

**Comment by Anubiso** [comment]
bump

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/22053
