### ISSUE TITLE
The list view settings popover is not scrollable

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#21572]
### Steps to reproduce
- Go to the list view of a content-type with many different fields
- Click on the settings of the list view
- See the long popover and the inability to scroll

### Expected behavior

You should be able to scroll

### Screenshots

![Image](https://github.com/user-attachments/assets/a5d10e19-79e1-4ab9-87c8-caa91cffe3c5)

**Comment by PrathameshGujar08** [comment]
Hey, I would like to work on this issue.
