### ISSUE TITLE
Error: Failed to load native binding

### ISSUE THREAD

**Issue by insivika** [strapi/strapi#21584]
### Required System information

- Node.js version: 20.17.0
- NPM version: 10.8.2
- Strapi version: 5.0.1
- Database: Postgres
- Operating system: NA (deployed to heroku)
- Is your project Javascript or Typescript: Typescript

### Describe the bug
When deploying my app to heroku I see this error: Error: Failed to load native binding  

### Steps to reproduce the behavior

1. Update engines settings in package.json to
```
   "engines": {
    "node": "20.17.0"
  },
```
2. Deploy to heroku

Removing  the package.json and pushing the project up then deploys successfully. 

### Expected behavior

I should see the app deploy successfully 
### Additional context
Removing  the package.json and pushing the project up will allow the project build successfully. 

When I try using the default engines setting I see this error:

```
  "engines": {
    "node": ">=18.0.0 <=20.x.x",
    "npm": ">=6.0.0"
  },
```

-----> Installing binaries
       engines.node (package.json):   >=18.0.0 <=20.x.x
       engines.npm (package.json):    >=6.0.0
       
       Resolving node version >=18.0.0 <=20.x.x...
       Downloading and installing node 19.9.0...
       Bootstrapping npm >=6.0.0 (replacing 9.6.3)...
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.9.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.9.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"9.6.3","node":"v19.9.0"}

**Comment by insivika** [comment]
Following up here. Are you still supporting self hosting on heroku?

**Comment by derrickmehaffy** [comment]
> Following up here. Are you still supporting self hosting on heroku?

We specifically support any hosting providers but I see no reason why there would be an issue with heroku

**Comment by derrickmehaffy** [comment]
This isn't an issue with us, we have never supported odd versions of node but heroku should be resolving node 20 from that engines config. I'd recommend reaching out to heroku support on this.

**Comment by gilliardmacedo** [comment]
Specifically for "Failed to load native binding"

Try: `npm update` and `npm i @swc/core --save-dev`

**Comment by DennisRauscher** [comment]
Tried reinstalling und updating.

Finally resolved it by using `yarn` to reinstall the deps.
