### ISSUE TITLE
Make setup script prompts more descriptive

### ISSUE THREAD

**Issue by jwlawrence** [strapi/strapi#2158]
**Informations**
- **Node.js version**: 10.12.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: MongoDB 4.0.2
- **Operating system**: MacOS 10.13.6

**What is the current behavior?**
After setting up MongoDB with Homebrew on mac, the `strapi new <project>` script fails to connect to the running DB.

**Steps to reproduce the problem**
Install MongoDB following the directions here: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/?_ga=2.125117514.1344412850.1539804218-1073495034.1539804218#install-mongodb-community-edition-with-homebrew

Rather than running `mongod` I instead ran `brew services start mongodb` and verified it was running via `mongo`.

Run `strapi new my-project`, answer questions with defaults, get error:
`Database connection has failed! Make sure your database is running.`

**What is the expected behavior?**
The project would be created

**Suggested solutions**
If I'm missing a setup step, it should be added to the onboarding docs. If this is an actual bug with the strapi cli, find the issue and fix.

**Comment by typerory** [comment]
Is Mongo running on port 27017?

**Comment by jwlawrence** [comment]
According to lsof, yes:
mongod  20864 ... TCP localhost:27017 (LISTEN)

**Comment by jwlawrence** [comment]
Ok, figured it out. I mistakenly thought the prompt for Username and Password was to create credentials for the admin user of the app, rather than for the db itself. Leaving them blank worked.

So, I think this ticket should be changed to make the fields in the setup process clearer. You already have "Database name" so why not prefix all of them with "Database"? For example:

? Choose your main database: MongoDB (recommended)
? Database name: 
? Database Host: 127.0.0.1
? +srv connection: false
? Database Port (It will be ignored if you enable +srv): 27017
? Database Username:
? Database Password:
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: false

**Comment by lauriejim** [comment]
Hello @jwlawrence! Thank you for this feedback.

There is a sentence of the beginning of the form: `Lets configurate the connection to your database:`
Then all questions are about your database connection (Name, Host, Port ...) it's natural to have `Username` and `Password` to be connected to the database.

For now we will let the form like it is. If more user have the same feedback we will reconsider this issue.

Thank you.
