### ISSUE TITLE
[Migration x Relations data] Many-to-Many published entries seem to be lost when migrating to V5

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#21599]
### Required System information

- Node.js version: v20.9.0
- Strapi version: from 4.25.13 to V5 experimental v0.0.0-experimental.fd55b75e545ef2b5c16b5f49a04e0db294663d8d (from [this PR](https://github.com/strapi/strapi/pull/21588))
- Database: sqlite
- Operating system: WSL

### Describe the bug

When migrating from v4 to V5, my many-to-many publishes relations data were lost (not the draft ones, not the published one to one or unilateral ones).

### Steps to reproduce the behavior

Dataset (created in 4.25.13, ask me for the data.db if easier) : 

2 locales : English + French
4 Collection Types : 
- Dog : D&P and i18n disabled
- Owner : D&P and i18n enabled
- Cat : D&P enabled, i18n disabled
- Bird : D&P disabled, i18n enabled
Relations : 
- Dog and Owner : many to many
- Owner and Cat : one to one
-Bird to Cat : unilateral one from Bird to cat

1. Go to Content Manager, create entries for every CT in every language, add relations, publish some and let others in draft
2. Upgrade to V5 experimental
3. Go to Content Manager again and check your entries
4. Many to Many relations that are published seem to have been erased (between Dog & Owner)

### Expected behavior

All data must be correctly migrated.

### Screenshots

My Published Owner has lost its relations to Dog (many to many) : 
<img width="787" alt="image" src="https://github.com/user-attachments/assets/3950f07e-a84f-495c-9cb3-3d4b266226e0">

My Draft Owner still has its relations to Dog : 
<img width="591" alt="image" src="https://github.com/user-attachments/assets/dcb7077c-de59-4516-91d8-1c9a060e97d6">

### Additional context

I'll try to upgrade to V5 directly (not with the experimental) to check again (poke @Marc-Roig )

**Comment by monolithed** [comment]
@MarionLemaire, did you manage to find a workaround? I'm facing the same issue — relation fields aren't being returned after upgrading to version 5.

**Comment by IvanGrassoGX** [comment]
@MarionLemaire This is still happening for me on Strapi v5.11.3. Dis you managed to find a workaround? Thanks

**Comment by Marc-Roig** [comment]
@IvanGrassoGX could you detail your usecase? Having the exact schemas would help

**Comment by IvanGrassoGX** [comment]
Hi @Marc-Roig I opened a new Issue report with more details [here](https://github.com/strapi/strapi/issues/23209)

Please let me know what else you need and I be more then happy to provide.
