### ISSUE TITLE
GraphQL: file URLs are not signed when using aws-s3 together with private bucket

### ISSUE THREAD

**Issue by romain-hasseveldt** [strapi/strapi#21592]
### Required System information

- Node.js version: v20.10.0
- NPM version:
- Strapi version: 5.0.2
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I'm using GraphQL with the AWS S3 upload provider, configured for a private S3 bucket with signed URLs, following the documentation [here](https://github.com/strapi/strapi/blob/main/packages/providers/upload-aws-s3/README.md#configuration-for-a-private-s3-bucket-and-signed-urls).

The issue is that when querying files through GraphQL, I only receive unprotected URLs instead of the expected signed URLs.

### Expected behavior
When querying files through GraphQL with the AWS S3 upload provider configured for signed URLs, I expect to receive signed URLs that grant temporary access to the files stored in the private S3 bucket.

**Comment by aleandro-coppola** [comment]
Same for: #21749

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/21749
