### ISSUE TITLE
@strapi/plugin-i18n v4.25.13 not tagged as latest on nmpjs

### ISSUE THREAD

**Issue by 20x-dz** [strapi/strapi#21601]
### Describe the bug

[v4.25.13](https://github.com/strapi/strapi/releases/tag/v4.25.13) was released 5 days ago. [@strapi/plugin-i18n](https://www.npmjs.com/package/@strapi/plugin-i18n) is still on v4.25.12 on npmjs:
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/4f599793-0dc1-4a93-9dc4-955910bfe4ab">

Probably because v4.25.13 wasn't promoted to the "latest" tag:
<img width="764" alt="image" src="https://github.com/user-attachments/assets/8b467696-24e9-40b8-92c9-e18d0693605e">

**Comment by Convly** [comment]
Thanks for pointing it out, it should be fixed now :slightly_smiling_face: 
https://www.npmjs.com/package/@strapi/plugin-i18n
