### ISSUE TITLE
5.0.0-discard-drafts migration fails for content types with uid fields

### ISSUE THREAD

**Issue by rb-ami** [strapi/strapi#21604]
### Required System information

Environment: development
OS: linux-arm64
Strapi Version: 4.25.13 -> 5.0.2
Node/Yarn Version: yarn/1.22.22 npm/? node/v20.17.0 linux arm64
Edition: Community
Database: postgres

### Describe the bug

Updating from 4.25.13 to 5.0.2 fails when content types have `uid` fields because of a violation of uniqueness constraints when running the `5.0.0-discard-drafts` migration. For example, if the content type contains these fields
```json
"title": {
  "type": "string",
  "required": true,
  "unique": true
},
"slug": {
  "type": "uid",
  "targetField": "title",
  "required": true
}
```
then the migration will fail because it violates the uniqueness constraint on `slug`.

**Comment by rb-ami** [comment]
This is still broken in 5.1.0. I get errors like
```
insert into "activities" ("document_id", "title", "slug", "summary", "created_at", "updated_at", "published_at", "locale")
select "document_id", "title", "slug", "summary", "created_at", "updated_at", NULL as "published_at", "locale"
from "activities"
where "published_at" is not null
- duplicate key value violates unique constraint "activities_slug_unique"
```

**Comment by EmmasBox** [comment]
I was able to reproduce this error as well. I was pulling my hair out trying to figure out the issue and I noticed it was complaining about the UID field in my collection and type and when I removed it then everything started working.

**Comment by rb-ami** [comment]
Still broken in 5.2.0

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/21607
