### ISSUE TITLE
Field Level Permissions - Users-Permissions - Discussion

### ISSUE THREAD

**Issue by NickBolles** [strapi/strapi#2161]
# Edited by @derrickmehaffy on 2021/0329

I have morphed this feature request to point at the Users-Permissions specifically to support Field level permissions.

---

## Summary
**This feature request is for permissions on fields.** 

### Currrently
Currently we have permissions on controller actions by roles. This is good for completely restricting access to certain actions, but there are some big issues with it, especially when paired with Graphql. 

### Background
We stumbled across this issue with the `me()` query that I created in #2116. Essentially the `UserPermissionsUser` GraphQL type exposed the `UserPermissionsRole` type, which itself exposed the `Users` array of all users with that role. This would allow access to all of the users with the same role. This is a fairly serious exposure of information if steps aren't taken to mitigate it.

I solved this instance with a custom return type `UserPermissionsMe` and `UserPermissionsMeRole` that doesn't have `Users` on it. But that shouldn't have to be done for every type. Also, this `UserPermissionsMe` type doesn't get updated with any of the fields that are added to `UserPermissionsUser`, so currently I have to do separate requests for more fields on the users object.

> Huge thank you @kamalbennani and @danielmahon for helping me identify and fix these issues!

## Potential Solution?

> **_First off, I'm pretty new to Strapi, so this is just my initial take, and by no means a definitive solution. Please give feedback and suggestions!_**

I think the best way to solve this issue, other issues, and while adding a bunch of functionality and flexibility, is to expand on the permissions plugin to add field level permissions. I am approaching the `field permissions` similar to the `policy` field on the permissions model.

I think there are a few parts to it...
### 1. Config
I see this as an additional section on the permissions edit page in the `Advanced Settings` section after you've allowed access to an action. This section could list out the fields and have check marks for what is accessible.

### 2. Storage
These field permissions could be an array on the permissions model. I think just an array of objects with a `field` property, and an `allow` property, at least for now.

### 3. Enforcement
I think the biggest issue comes down to how to enforce these field level permissions. My initial impression is whenever something is returned by a controller, we run it through a processor for the permissions to omit any fields before returning it to the caller. 

It seems like almost everything goes through a controller, so this would be a pretty central change, and help to be consistent. 

#### 3b. GraphQL
For GraphQL I think we would need another layer, or if not, it might be helpful. 

GraphQL Directives are almost exactly what this is for, and could be a standard directive for every field/type.

#### Owner concept
Making a `owner` concept would be really neat. Basically this would apply to any model that has a `user` on it. If the `user` ID on the model matches the authenticated user, you would have access to that document, very similar to the `me` query. Of course we'd have to allow this to be turned off. And I'm not quite sure how this would work, But I think it would be very cool to just say, `give me all of my stuff`.

**Comment by PashalisN** [comment]
If I understand it correctly I think you have the same issue as I have. 
What is the meaning of relations when for Example: 
I have a new content type 'articles' and the pre-installed users.
If I have 2 users (user A, user B) in authenticated role and each user has for example 2 articles and I want to find (display) only these articles which are related to user A and not just every single article in the database, how can I do that without switching in coding?

**Comment by NickBolles** [comment]
Exactly! This is exactly what I proposed the "owner" concept for. Maybe it would make sense for this to be a property on the field. So any model that has a relationship to `users` and has the field property `owner` the user would be able to access if that user is the logged in user.
________________________________

**Comment by PashalisN** [comment]
So, then I ask you guys (devs) why do you release a version with user roles and permission without having such an essential thing like this. In my opinion it doesnt make sense.
use case:
Imagine, If I have a bank account and I am related to my account with "MY" sensitive data, and any other authenticated user can make a request to all bank accounts, so for what do I need these user permission role thing??? 
 I thought I am wrong with my way of thinking and had overlook something in the admin panel, but these essential thing should be the first thing to think about when I try to understand how user driven data are made for

**Comment by PashalisN** [comment]
another solution could be to make api endpoints more flexible, if I want to have my own articles I should be able to define it like this:
api/user/articles ... this could make sense if you dont use nonsql databases.

**Comment by NickBolles** [comment]
You do have a point, we could just add a "my<data model name>" controller action for everything. That could be a way to do it, which is basically the work around right now, to make a custom controller that forces adding a filter to the query. but we could add it as part of the generation of a model. I think that's a lot less flexible than field level permissions, and it's more of the "owner" concept.

**Comment by Aurelsicoko** [comment]
I completely agree with all of you about this security issue. Currently, the policy system that we have is great but it only works for REST. I think we could reuse/extend this system and apply it to the field level. Or maybe we should rethink it entirely.

IMHO, the issue is specific to GraphQL. We do not have that kind of issues with REST because the queries are not nested like it can be using GraphQL.

I don't like the idea of extending the UI because the UI has to be agnostic or support the feature both for REST and GraphQL. What do you think if we support a new property `fields` when you can apply a new level of policy?
```js
module.exports = {
  resolver: {
    Query: {
      bank: {
        description: 'Return a single post',
        policy: ['plugins.users-permissions.isAuthenticated'],
        fields: {
          users: {
            allow: true,
            policy: ['isBankOwner']
          }
        }
      }
    }
  }
};
```

However, I already see the limitation of this solution... how can we support more than one level of policy? What happens if inside the `users` field I can access to the bank account, etc. 

Imagine a query like this`bank(id: 1) { users { bankAccount { id, name, total } } }`... I shouldn't let the bank owner to access to the total of every account in the bank (the example doesn't make sense but you understand the idea behind).

**Comment by NickBolles** [comment]
@Aurelsicoko thanks for your comments. 

I think the idea here is that all of the other plugins respect the core plugins. So for graphql it should respect the user-permissions permissions policies. I think that there was a pull request out there to fix this deficiency in the graphql plugin. 

I really think that this should be a field level policy, not a query level setting. 
If it's a field level policy it can be a lot more dynamic, e.g. are we logged in, okay then allow, are we an admin, okay, allow, etc. 

I'm prototyping a system like this that modularizes policies to a set of functions that can be called to compose a policy for any object in strapi, as well as an owner policy that will look to the model definition to determine which field should be equal to the current user's ID, that can be used from other policies too. 

Keep an eye out for a PR, I'll try to have this done by next Tuesday.

**Comment by Aurelsicoko** [comment]
@NickBolles Oh, I like this approach of field policy. I think we should add the support a new `policy` attribute in the model instead. So, the GraphQL plugin will be able to easily retrieve policies associated with a field and execute them in order to let the user access to the data or not.

```json
{
  "connection": "default",
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false,
      "policy": ["isOwner"]
    }
  }
}
```

However, I'm worried about the format of our current policy. I would like to keep a generic format of policy for routes and fields if possible.

```js
module.exports = async (ctx, next) => {
  // Do stuff

  await next();
};
```

**Comment by danielmahon** [comment]
@NickBolles @Aurelsicoko Might be worth looking into: https://github.com/maticzav/graphql-shield

**Comment by jdmann** [comment]
I found this thread while searching for a way to customize Strapi so that I can completely separate user or organization-level data from each other, without having to use multiple applications. If users could belong to an "organization" and all access was restricted within that organization, that would seem very useful.

**Comment by NickBolles** [comment]
@danielmahon graphql-shield, and graphql-yoga look awesome, and perfect for a framework like strapi. It seems like it would allow the schema to be modularized a ton, so that each plugin could maintain it's own schema and queries could be routed to the right places. On top of that shield (or even just a schema directive), could enforce permissions

It seems like a good direction for strapi to go, but too big of a project for me. I'm hoping to finish up this initial iteration of attribute permissions soon, hopefully it's easy to use from everwhere though.

**Comment by TechupBusiness** [comment]
+1 for field level permissions. This is an very important feature when it comes to complex backend applications.

**Comment by MarcCoet** [comment]
Hi, I landed here for a similar use case as @jdmann.
I am just discovering and playing with Strapi to see if it is already flexible enough to power some of my projects. I thought I could give my 2 cents by sharing a use case.
Unlike jdmann I mostly don't mind creating multiple backends for different apps but I would need each User of an app to only be able to edit the data linked to her.
Simplest example: let's say a User with 'Editor' Permissions can create Blog Posts and edit its own Posts only.
I hope it is clear and it helps to have specific use cases to think about for the work ahead.
Best of luck

**Comment by Aurelsicoko** [comment]
@MarcCoet so you want to apply an `isOwner` policy to a field or a mutation?

**Comment by MarcCoet** [comment]
@Aurelsicoko you are the expert, you tell me. haha ^^
What I want is the admin to reflect the workflow I described. So an editor should only see / be able to edit its own content but an admin rules the world. Basically a more powerful role handling through the API and the admin interface.

**Comment by Aurelsicoko** [comment]
@MarcCoet Okay got it! We call this feature "Data ownership", then you will be able to apply policy based on the owner of the data. You can find more details here https://portal.productboard.com/strapi/c/44-data-ownership

**Comment by MarcCoet** [comment]
@Aurelsicoko nice to read. Thanks.

**Comment by lauriejim** [comment]
Thank you all for the discussion, all information is noted.
We can close the discussion.

**Comment by TechupBusiness** [comment]
@lauriejim Data Ownership is not the only issue, just one small use-case. The request would be to be able to display different fields to a user based on his roles. One object can have different views... think of an HR system where normal employees can only see name and email (of the object "employee") whereas an HR can see the personal address and bank account. Or see but not edit them. Can you please reopen or create a ticket for this on your roadmap? Its a mapping of roles to single fields.

**Comment by derrickmehaffy** [comment]
@TechupBusiness There is an open FR on the product board that more or less covers this: https://portal.productboard.com/strapi/1-public-roadmap/c/8-administrators-roles-permissions

@Aurelsicoko might be good to include this at the REST/GraphQL level on permissions as well and maybe link this issue to that product board for discussion?

**Comment by Aurelsicoko** [comment]
Not the same issue to me. The administrators' permissions will be related to the UI like X should be allowed to access page Y or X can only create a new entry for the content type Z? 

The field-level permissions are different. We talk about the end-users, not administrators. It's more related to the framework itself, maybe there will be an interface to manage the field-level permissions but I'm not sure about that.

Anyway, I'm going to create a dedicated card on product board to keep it in mind.

**Comment by congthang1** [comment]
Hey any update on this? I see on current version 3.0.6 can still query relation data without permission. I can get all user info from a review record that is public.

**Comment by TechupBusiness** [comment]
> Hey any update on this? I see on current version 3.0.6 can still query relation data without permission. I can get all user info from a review record that is public.

You can vote also on https://portal.productboard.com/strapi/1-public-roadmap/c/63-field-level-permissions

**Comment by congthang1** [comment]
> > Hey any update on this? I see on current version 3.0.6 can still query relation data without permission. I can get all user info from a review record that is public.
> 
> You can vote also on https://portal.productboard.com/strapi/1-public-roadmap/c/63-field-level-permissions

@TechupBusiness it says launched!

**Comment by derrickmehaffy** [comment]
> Is this feature is already out?

Only within the AdminUI currently, not via the normal user generated routes

**Comment by derrickmehaffy** [comment]
@Jessinra the advanced field level permissions (specific actions per field) is only available within EE edition (Bronze, Silver, and Gold).

You can see pricing here: https://strapi.io/pricing

**Comment by atovik** [comment]
*Too bad. :-(*

**Comment by emregency** [comment]
> @Jessinra the advanced field level permissions (specific actions per field) is only available within EE edition (Bronze, Silver, and Gold).
> 
> You can see pricing here: https://strapi.io/pricing

Your pricing page shows that there are 30 roles which I have no clue about :) I would have loved to explore the EE edition, couldn't find any page that gives the details of the advantages.

**Comment by derrickmehaffy** [comment]
> > @Jessinra the advanced field level permissions (specific actions per field) is only available within EE edition (Bronze, Silver, and Gold).
> > You can see pricing here: https://strapi.io/pricing
> 
> Your pricing page shows that there are 30 roles which I have no clue about :) I would have loved to explore the EE edition, couldn't find any page that gives the details of the advantages.

Yup we realize there is a void in information about the RBAC option and we are actively working on adding additional information to our documentation about this.

**Comment by ravolta-io** [comment]
Am I the only one that finds putting field level permissions behind a paywall to be an issue? Please correct me if I'm wrong, but that means that all CE Strapi deployments are basically just very insecure?

**Comment by derrickmehaffy** [comment]
@ravolta-io we have a feedback post on our forum if you wanted to add your feedback there as well: 

https://forum.strapi.io/t/rbac-role-based-access-control-feature-discussion/433/22

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/rbac-role-based-access-control-feature-discussion/433/23

**Comment by dennis-hh** [comment]
I am having the same issue as @congthang1. Even when running the latest version with an Enterprise license, I can not change the permissions on a field-based level for users/roles in the Users&Permissions settings.
Example:
Users can create entries on our page, and list entries of others. An entry has a relation to `user`, but users are forbidden to query `users`. However, every user can get entry->user->role->users via a simple GraphQL query, essentially getting all emails of all registered users. This is a huge data-privacy issue, and I have no idea how to solve that.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/privacy-issue-with-graphql-users-permissions-plugin/3212/1

**Comment by Tyler-RCSD** [comment]
I agree with @dennis-hh and am in a similar predicament.  Trying to find a headless CMS for a project but field-level permissions at the API level are a must.  [This card](https://portal.productboard.com/strapi/1-public-roadmap/c/63-field-level-permissions) says 'launched' but that's really only half true.  It was launched for the AdminUI but not GraphQL.  I don't even see a card for the GraphQL side of things. (Unless I missed it).

**Comment by evanmcd** [comment]
I'm honestly surprised that this hasn't been fixed. We've been considering Strapi for a big new project (was just about to try v4!), but knowing this is a hole that seems not to be a priority to fix could be a deal breaker for us. 

Does anyone from the Strapi side have an update on this?

**Comment by ravolta-io** [comment]
> I'm honestly surprised that this hasn't been fixed. We've been considering Strapi for a big new project (was just about to try v4!), but knowing this is a hole that seems not to be a priority to fix could be a deal breaker for us.
> 
> Does anyone from the Strapi side have an update on this?

We've had the same feelings and have moved on to Directus at this point as it provides a much better secured and performant API. Sad, as I used to like Strapi a lot back in the beta-days.

**Comment by Nik96i** [comment]
What is the last status of this issue? 
It's not been implemented in v4.

**Comment by Nik96i** [comment]
@ravolta-io Directus has field-level permissions? in both REST and GraphQL or just REST?

**Comment by adanielyan** [comment]
> @ravolta-io Directus has field-level permissions? in both REST and GraphQL or just REST?

Yes, it work in GQL too. However, since in GQL you have to explicitly specify fields you request, it will throw a GRAPHQL_VALIDATION_EXCEPTION error if you request a field that a user doesn't have access to. But will work just fine if you don't request that particular field.

**Comment by ravolta-io** [comment]
> @ravolta-io Directus has field-level permissions? in both REST and GraphQL or just REST?

Yeah and it has more nice DX-features. But it feels wrong promoting a different/competing product here but by all means check it out.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/field-level-permissions-end-user-management
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
