### ISSUE TITLE
"public.admin_permissions_role_links" does not exist

### ISSUE THREAD

**Issue by HamzaAli121** [strapi/strapi#21619]
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.6.7
- Strapi version:4.15.0
- Database: postgres
- Operating system: darwin-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug
i am getting this bug whenever i run strapi develop 

`[2024-10-08 00:29:24.170] warn: Users-permissions registration has defaulted to accepting the following additional user fields during registration: socialId,socialType,iosToken,androidToken,phone,avatar,reviewScore,profilePicture,shippingAddress,firstName,lastName
error: select distinct "t0".*, "t0"."id" from "public"."admin_permissions" as "t0" left join "public"."admin_permissions_role_links" as "t1" on "t0"."id" = "t1"."permission_id" left join "public"."admin_roles" as "t2" on "t1"."role_id" = "t2"."id" where ("t2"."id" = $1) - relation "public.admin_permissions_role_links" does not exist`

### Expected behavior

it's very weird because it was working fine few days ago i didn't install any library and didn't update the project 
in the databse when i see there is a table with admin_permissions_role_lnk but now it requires public.admin_permissions_role_links i have no idea why suddenly i am getting this error.

### Screenshots
<img width="894" alt="Screenshot 2024-10-08 at 12 45 55 AM" src="https://github.com/user-attachments/assets/278fd12b-e846-4f14-8d1f-b638c7707889">

### Additional context

I tried to remove and re install the node modules and also tried with remove build and cache folders but facing the same issue

**Comment by derrickmehaffy** [comment]
Looks like you have a Strapi 4 application connecting to a Strapi 5 database and those are not mutually compatible
