### ISSUE TITLE
Could not re-login using Facebook provider due to error "Email is already taken."

### ISSUE THREAD

**Issue by trieutritam** [strapi/strapi#2162]
**Informations**
- **Node.js version**: 8.12.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: MongoDB 4.0.3
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
Could not re-login by call callback "auth/facebook/callback" due to error "Email is already taken."

**Steps to reproduce the problem**
- Call auth/facebook/callback?access_token=<TOKEN>
- API return success (user created)
- Call auth/facebook/callback?access_token=<TOKEN>
- API return "Email is already taken."

**What is the expected behavior?**
- API should return created user and jwt token.

**Suggested solutions**
Step 1: I found that new user created in MongoDB doesn't contains attribute: "provider" so below code in Provider.js cannot resolve user:
`const user = _.find(users, {provider});`
 `if (!_.isEmpty(user)) {
          return resolve([user, null]);
 }`

Step 2: I found that "users-permissions" plugin already config to save "provider" as below code (in Provider.js file):

`Line 78: // Create the new user.`
`const params = _.assign(profile, {
          provider: provider,
          role: defaultRole._id || defaultRole.id
        });`
`const createdUser = await strapi.query('user', 'users-permissions').create(params);`

Step 3: I try to add "provider" attribute to User.settings.json file of "users-permissions" plugin as below: 
`"provider": {`
      `"type": "string",`
      `"default": ""`
    `}`
=> Result "provider" attribute always contains empty value ("provider" attribute is not being saved).

Step 4: I've continue debug and found the root cause: "provider" attribute being remove from "User" schema while application start by bootstrap of "content-manager" plugin, I've to comment out below code  and everything work fine.
- content-manager's bootstrap.js
`fieldsToRemove.forEach(field => {`
`_.unset(fields, field);`
`// I comment out this line _.unset(schemaModel.attributes, field);`
`});`

**Comment by GuillaumeLe** [comment]
I'm faced with the same issue with the Discord provider.

I think the true question is why the provider field is removed from the the schema ?

**Comment by derrickmehaffy** [comment]
I have also noticed some odd issues with providers, I believe the plan in the future is to split them into their own plugins (one per provider similar to the upload plugins).

If you guys have example code to try and reproduce I think it would be helpful to track the problem down.

**Comment by lauriejim** [comment]
Hello @trieutritam can you try with last version of Strapi (3.0.0-alpha.14.4.0) it was fixed normally.

**Comment by trieutritam** [comment]
@lauriejim: I've just tried with latest version (14.4.0) and this issue was fixed.
