### ISSUE TITLE
can't filter by status inside populate using document

### ISSUE THREAD

**Issue by dzakki** [strapi/strapi#21623]
### Required System information

- Node.js version: v20.11.1
- NPM version: 10.2.4
- Strapi version: 5.0.2
- Database: Mysql 8.0
- Operating system: Mac OS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I tried to filter by status inside populate using the document, but it doesn't work. the document throwing an error 
`ValidationError invalid key status`

### Steps to reproduce the behavior

1. try to create a custom API
2. Use `document` to communicate between databases. you can use `findOne` method.
3. add filter by status inside of populate

```
await strapi .documents(uid).findOne({
  documentId: "....",
  populate: {
     categories: {
        filters: {
           status: "published"
        }
      }
  }
})
```

### Expected behavior

it's should works fine like in the strapi v4, we can use `publishedAt`.

**Comment by sumitxae** [comment]
I would like to handle this issue, can you 
assign me to this ?

**Comment by Marc-Roig** [comment]
hello! we don't currently support filtering by status, so this would fall more onto a feature request .
If you don't care about the "modified" status, you can still filter by publishedAt :)
