### ISSUE TITLE
Content filter not exactly matched in strapi 5

### ISSUE THREAD

**Issue by ZhengAudrey** [strapi/strapi#21620]
### Required System information

- Node.js version:  20.17.0
- NPM version: 10.8.2
- Strapi version:  5.0.2
- Database: Mysql
- Operating system: Windows 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The  rest api (GET) of strapi 5 cannot differ texts with slight difference, while there is no such problem in strapi 4.

I have a record in the table, one field of its contents is: yì 
But when I filter by yī (which is different from yì ), the record returns, while it shouldn't since it not matched.

In rest api, the record returns.
In admin dashboard filter, the record returns also.

Encode for yī is:  y%C4%AB
Encode for yì is:  y%C3%AC

Since they are different contents, I guess it is a bug in strapi. And such problem doesn't happen in strapi 4.

### Steps to reproduce the behavior

Create a document with content field, and add a record with yì as its content.
1. Go to dashboard admin, filter by: content is yī
OR
2. Send rest api request (GET), with url like, ...?filters%5Bcontent%5D=y%C4%AB

This records will show up, while it shouldn't. 

### Expected behavior

The filter can exactly match.

### Screenshots

1. yī and yì are different, they have different enconder
![Screenshot 2024-10-07 215719](https://github.com/user-attachments/assets/9968c5d4-5c1c-47a7-8762-5331a05c6594)
![Screenshot 2024-10-07 215913](https://github.com/user-attachments/assets/81715127-dbf1-422d-8b6e-9797b384b51c)

2. In admin dashboard
![Screenshot 2024-10-07 215452](https://github.com/user-attachments/assets/6a5630ca-a4f4-4353-85bc-c7c13b76c032)

3. in rest api
![Screenshot 2024-10-07 215543](https://github.com/user-attachments/assets/a5e131d8-9c3a-40eb-be20-4dff9c63c453)

**Comment by ZhengAudrey** [comment]
To make it more clear. I searched by two different texts, but the record returns for both.

I search by yì  (which encoded as y%C3%AC), it appears. This is expected
![Screenshot 2024-10-07 221120](https://github.com/user-attachments/assets/851518bc-231c-4595-b14f-8edae3e7546f)

I search by yī  (which encoded as y%C4%AB), it also appears. This is unexpected
![Screenshot 2024-10-07 215543](https://github.com/user-attachments/assets/e5951990-5c31-4511-a8da-3b523bf0dc0f)

BTW, another problem is, the returned id seems kind of random number, which is different from the value in database. Not sure if it is by design.

**Comment by ZhengAudrey** [comment]
it may be related to db configs. Closed for now.

**Comment by derrickmehaffy** [comment]
> it may be related to db configs. Closed for now.

Yeah it's most likely related to the encoding format selected in the DB
