### ISSUE TITLE
Error during assigning/re-assigning roles for user via admin panel 

### ISSUE THREAD

**Issue by Throttle** [strapi/strapi#21653]
### Required System information

- Node.js version:v20.10.0
- NPM version:10.2.3
- Strapi version:5.4.0
- Database:postgres
- Operating system:darwin-x64
- Is your project Javascript or Typescript:Typescript

### Describe the bug
Error appears if role is changed for user.

### Steps to reproduce the behavior

1. Go to any user page in admin panel
2. Modify role from authenticated to public
3. Press save button

### Expected behavior

Role must be changed and saved.

### Screenshots

<img width="606" alt="image" src="https://github.com/user-attachments/assets/f5e5b323-d8e8-48dd-9e29-950a796bb6b0">

**Comment by edwinfadul** [comment]
Tengo el mismo problema

**Comment by BayBreezy** [comment]
I can't even create a user from the admin panel. I just get an error that says Not Found and this is logged to the console
`http: POST /content-manager/collection-types/plugin::users-permissions.user? (31 ms) 404`
