### ISSUE TITLE
DeprecationWarning :  `punycode`

### ISSUE THREAD

**Issue by AdrianDroid** [strapi/strapi#21685]
### Required System information

- Node.js version: 22 LTS
- NPM version: PNPM v9.12.1
- Strapi version: v5.0.3
- Database: postgres
- Operating system: ubuntu 
- Is your project Javascript or Typescript: Javascript 

### Describe the bug
⠋ Loading Strapi(node:1727052) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Steps to reproduce the behavior

$ pnpm run develop

### Expected behavior

no DeprecationWarning

### Screenshots

![image](https://github.com/user-attachments/assets/2e464be8-7a89-4878-b815-4700c6816a19)

**Comment by kaaax0815** [comment]
As seen in `package.json` the engines field lists
```json
"node": ">=18.0.0 <=20.x.x"
```
you are using Node 22 which is not supported and which deprecated the punycode module.
You should use Node 20

**Comment by bolg55** [comment]
Closing as this is not a Strapi issue. Please see @kaaax0815 comment for resolution.

**Comment by romatou** [comment]
@kaaax0815, are you planning to add support for Node 22?

My package.json says
```
"node": ">=14.20.1 <=18.x.x",
```

**Comment by kaaax0815** [comment]
@bolg55 This should be reopened, as Strapi now supports Node 22 and 24, and it doesn't seem like this issue is fixed
