### ISSUE TITLE
Warning:  role.connect[0].id is a required field

### ISSUE THREAD

**Issue by giangdn** [strapi/strapi#21709]
### Required System information

- Node.js version: v18.20.1
- NPM version: 10.5.0
- Strapi version: v5.0.3
- Database: mysql 8.3.0 (Homebrew)
- Operating system: macos14.2   (arm64)
- Is your project Javascript or Typescript: Typescript
- Environment: development

### Describe the bug

Cant create new fontend user. Always receive warning message **Warning:  role.connect[0].id is a required field**

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Click on 'Collection Types > User'
3. Click on 'Create new entry' button
4. Fill all fields + choose one role
5. Click on 'Save' button
6. See error

### Screenshots
<img width="1392" alt="Screenshot 2024-10-09 at 13 29 58" src="https://github.com/user-attachments/assets/7d0e6468-27fb-487a-91a4-88d12e4af0dc">

### Additional context
A pure project just created by strapi cli

**Comment by Marc-Roig** [comment]
closing this one in favor of https://github.com/strapi/strapi/issues/21709

**Comment by IsmaeelAkram** [comment]
Me too, anyone know why this is happening?

**Comment by enzzoperez** [comment]
same error here, I tried a new and clean project with version 5.0.3 and 5.0.4

**Comment by larissajusten** [comment]
same error here

**Comment by shubham-covrzy** [comment]
Same here here

**Comment by shubham-covrzy** [comment]
![image](https://github.com/user-attachments/assets/b5e20ab9-52cf-4d33-a347-0c736503168f)
Can any one confirm what is going on ??

**Comment by alyssonbrito** [comment]
@Marc-Roig I guess you meant
https://github.com/strapi/strapi/pull/21726

**Comment by geronda94** [comment]
![Uploading Снимок экрана от 2024-10-10 18-32-09.png…]()

**Comment by geronda94** [comment]
![image](https://github.com/user-attachments/assets/e4a7fba5-b662-4b7b-aa09-22743d6243b2)

**Comment by geronda94** [comment]
![image](https://github.com/user-attachments/assets/7eac9952-f7ce-41ac-aabc-b6972c85acc9)

There is the same problem with both the custom installation with my own database and the quick installation.

**Comment by sergiocl23** [comment]
I solved it using version 5.0.0. In that version it works correctly

**Comment by manuelffernandez** [comment]
> I solved it using version 5.0.0. In that version works correctly

I installed the v5.0.5, and it works correctly. Using v5.0.4 doesn't work.

**Comment by Marc-Roig** [comment]
🤦‍♂️ My bad, I referenced the wrong link https://github.com/strapi/strapi/issues/21653 , indeed in the stable versions should work. If possible I would use the latest v5 version, or at least 5.1.0
