### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by sp9324** [strapi/strapi#21713]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug
"Follow us on Product Hunt" button overlaps with the footer text.
<img width="1470" alt="Screenshot 2024-10-09 at 12 04 50 PM" src="https://github.com/user-attachments/assets/62628b2f-c7f3-4326-92dc-f5ddd820edee">

### Steps to reproduce the behavior

1. Go to any page
2. Scroll down to the bottom

### Expected behavior

The button should not overlap. It should be moved above the footer.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Marc-Roig** [comment]
Hi, I will report this internally but close the ticket here as we want this to be the source of the cms tool only :) thank you for the report!
