### ISSUE TITLE
Relations user driven data

### ISSUE THREAD

**Issue by PashalisN** [strapi/strapi#2172]
Informations

Node.js version: 10.12.0
npm version: 6.4.1
Strapi version: 3.0.0-alpha.14.3
Database: MongoDB 4.0.2
Operating system: MacOS 10.13.6

What is the current behavior?
What is the meaning of relations for example when:
I have a new content type 'articles' and the pre-installed users.
If I have 2 users (user A, user B) in authenticated role and each user has for example 2 articles and I want to find (display) only these articles which are related to user A and not just every single article in the database, how can I do that without switching in coding?

**Comment by NickBolles** [comment]
See my response in #2161 even though you deleted your response :)

I think the only way to do this right now is with custom controller actions such as `findMine` that do something like this. (warning, this is not tested, treat this as psuedo code)
```
  findMine: async (ctx) => {
    const user = ctx.state.user;

    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
    }
    // Setup the filter
    ctx.query.where.author = user._id || user.id
    // Run the query with filters
    return strapi.services.articles.fetchAll(ctx.query);
  },
```

**Comment by lauriejim** [comment]
There is an  PR for that https://github.com/strapi/strapi/pull/1948
