### ISSUE TITLE
Can't populate user_permission_user relational field in strapi v5

### ISSUE THREAD

**Issue by praharshaAdhikari** [strapi/strapi#21742]
### Required System information

- Environment: development
- OS: linux-x64
- Strapi Version: 5.0.0
- Node/Yarn Version: npm/10.9.0 node/v20.17.0 linux x64 workspaces/false
- Edition: Community
- Database: postgres
- Is your project Javascript or Typescript: JS

### Describe the bug
I can't populate the relational field with relation to user_permission_user. I get null instead. I have already given the permission to find the user to an authenticated user in the permissions section.

### Steps to reproduce the behavior

1. Create a content-type with a relation to user_permission_user.
2. Add populate the type and select a user for the field.
3. Make an api call to get the content-type with query params `{populate: "*"}`.

### Expected behavior
The relational field to user_permissions_user should be populated.

### Screenshots

![image](https://github.com/user-attachments/assets/8c74b04a-6251-404c-876f-f13d7716c0ca)
![image](https://github.com/user-attachments/assets/c5837871-82c5-4717-84db-5c3e0c9a2dc9)
![image](https://github.com/user-attachments/assets/788118cd-5552-4edf-a4a7-30b7de1e2093)
![image](https://github.com/user-attachments/assets/f06ae90a-6b09-4940-985b-15d85c6d83cd)

**Comment by monolithed** [comment]
I’m in the same boat. In my Course collection, there's a field called 'modules' that has a relation with the Module collection, but it's not being returned. It worked fine in version 4. I'm not sure how to work around this issue.


<img width="1158" alt="Screenshot 2024-10-11 at 07 53 28" src="https://github.com/user-attachments/assets/a102fa59-9d0c-4855-9012-0a19c898bb80">

**Comment by praharshaAdhikari** [comment]
Yes, I also had it working on v4. I was using a middleware to automatically populate a "isOwner" field in my content and using another policy to restrict users access to content created by them only, in v4. But with this not working, my server breaks and nothing works. Are we doing something wrong?

This is a huge bug and I believe there would be more talk if this was truly an issue. Unfortunately, I can't find anything.

**Comment by praharshaAdhikari** [comment]
Nvm. I upgraded to 5.1.0 and it worked again.

**Comment by praharshaAdhikari** [comment]
Nvm. I upgraded to 5.1.0 and it worked again.
