### ISSUE TITLE
Error when creating a new User entry "Warning: role.connect[0].id is a required field"

### ISSUE THREAD

**Issue by fazaamal** [strapi/strapi#21743]
### Required System information

- Node.js version: 20.17.0
- NPM version: 10.8.2
- Strapi version: 0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27
- Database: postgres 
- Operating system: macos Sonoma 14.5
- Is your project Javascript or Typescript: ts

### Describe the bug

Error when creating a new User entry "Warning: role.connect[0].id is a required field"

### Steps to reproduce the behavior

1. Create new strapi project and usual setup 
2. Login to admin panel
3. Try to create new entry
4. Error pops up unable to create new user entry

### Expected behavior

Should create new user 

### Screenshots

![Screenshot 2024-10-09 at 22 25 33](https://github.com/user-attachments/assets/bc3e3422-2998-4be9-9183-b76199018cd4)

**Comment by enzzoperez** [comment]
same error, I tried with 5.0.3 and 0.4 versions, new and clean project

**Comment by sergiocl23** [comment]
I solved it using version 5.0.0. In that version works correctly

**Comment by derrickmehaffy** [comment]
fixed in: https://github.com/strapi/strapi/pull/21726 & https://github.com/strapi/strapi/releases/tag/v5.0.5
