### ISSUE TITLE
Implementation of soft delete

### ISSUE THREAD

**Issue by MTM-Suhail** [strapi/strapi#2175]
Hello, I would like to have soft delete functionality for graphql and normal API. what should i do?

**Comment by lauriejim** [comment]
By default this feature is not offered by Strapi.

You have to add `deleted` attribute to all your models.
Then update all delete functions (in your `./**/services/**.js` and `./**/queries/**.js`) to set `update` instead of `delete` by setting  `deleted` to `true`.
And update `fetch` and `fetchAll` functions to add an excluding filter based on `deleted` attribute value.

**Comment by MTM-Suhail** [comment]
Thank you for the support

**Comment by MTM-Suhail** [comment]
I think it's better to add in framework level than api level. We may ask by the time of api creation in admin panel.

**Comment by mnlbox** [comment]
interesting +1

**Comment by mtmsuhail** [comment]
can you explain a bit?

**Comment by lauriejim** [comment]
I think this issue is related to your message @Aurelsicoko  https://github.com/strapi/strapi/issues/2257

**Comment by Aurelsicoko** [comment]
I'm closing this issue, but I've added a new private card on Product Board to consider it in the roadmap. It doesn't seem to be a priority (that's why the card isn't public for now), but feel free to upvote this issue and comment if you've more insights. As I said, the feature can be easily added, PRs are welcomed as usual 👍

**Comment by Melf11** [comment]
> There are packages available for Bookshelf (https://www.npmjs.com/package/bookshelf-soft-delete) and Mongoose (https://github.com/Kubide/k-mongoose-soft-delete). It could be easily added as an option to the connectors (strapi-bookshelf & strapi-mongoose).

is there an documentation how to implement [booksheld](https://www.npmjs.com/package/bookshelf-soft-delete) ? i'm not getting it...

**Comment by derrickmehaffy** [comment]
> > There are packages available for Bookshelf (https://www.npmjs.com/package/bookshelf-soft-delete) and Mongoose (https://github.com/Kubide/k-mongoose-soft-delete). It could be easily added as an option to the connectors (strapi-bookshelf & strapi-mongoose).
> 
> is there an documentation how to implement [bookshelf-soft-delete](https://www.npmjs.com/package/bookshelf-soft-delete) ? i'm not getting it...

It won't be possible in the v4 as we have removed bookshelf and are just using Knex.js so unless Knex support soft-delete (not that I'm aware of)

**Comment by Xander-SquareKicker** [comment]
HI, solution provided for softdelete - it is custom implemented/imported in index.ts>bootstrap({strapi}
```
export default (strapi) =>
  strapi.db.lifecycles.subscribe({
    // Model must include a "deleted" boolean field in each of the models' schema, set as private and default to false
    models: [ ], // eg models: ["api::api_name.content_type_name"],

    async beforeFindOne(event) {
      event.params.where = { ...event.params.where, delete: false };
    },

    async beforeFindMany(event) {
      event.params.where = { ...event.params.where, delete: false };
    },

    async beforeDelete(event) {
      await strapi.db.query(event.model.uid).update({
        where: { ...event.params.where },
        data: {
          deleted: true,
        },
      });
      event.params.where = { id: null };
    },

    async beforeDeleteMany(event) {
      await strapi.db.query(event.model.uid).updateMany({
        where: { ...event.params.where },
        data: {
          deleted: true,
        },
      });
      event.params.where = { id: null };
    },
  });

```

**Comment by seleckis** [comment]
@Xander-SquareKicker hi, thanks for the snippet. Unfortunately your solution does not work as expected. First of all you have different fields there: `deleted` and `delete`, it causes an error in database query. If I name all of them `deleted` it works, but in this case deleted records would not be visible in Strapi, not only by fetching through api. I would appreciate a better solution.

**Comment by iamamjad** [comment]
Hey @seleckis did you find something else? I am having the same issue on my nextjs 13 along with Strapi 4 unable to read the soft deleted record

**Comment by seleckis** [comment]
> Hey @seleckis did you find something else? I am having the same issue on my nextjs 13 along with Strapi 4 unable to read the soft deleted record

I have created custom query like this:
```js
const deleteEntitySoft = () => ({
  typeDefs: `
    type Mutation {
      deleteEntitySoft(id: ID!): EntityEntityResponse
    }
  `,
  resolvers: {
    Mutation: {
      deleteEntitySoft: {
        resolve: async (_, { id }) => {
          const { toEntityResponse } = strapi.service(
            "plugin::graphql.format"
          ).returnTypes;

          const entityEntry = await strapi.entityService.update(
            "api::entity.entity",
            id,
            {
              data: {
                deleted: true,
              },
            }
          );

          return toEntityResponse(entityEntry);
        },
      },
    },
  },
});
```
register it in index file of strapi:
```js
export default {

  register({ strapi }) {
    const extensionService = strapi.service("plugin::graphql.extension");
    extensionService.use(deleteEntitySoft);
  },
  ...
}
```
Then just use `deleteEntitySoft` mutation from app side.
