### ISSUE TITLE
Upgrade tool does not provide a useful error message if you are already on the latest version

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#21750]
### Required System information

- Node.js version: v20
- NPM version: Yarn v1
- Strapi version: 5.0.4
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When running the `npx @strapi/update@latest minor` if you are already on the latest version does not provide a useful error message.

### Steps to reproduce the behavior

1. Create a new application on the latest version
2. Attempt to run upgrade command using `major`, `minor`, or `patch`
3. See error

### Expected behavior

A useful error message should be given that they are already on the current latest version for their selection

### Screenshots

![image](https://github.com/user-attachments/assets/0d245292-a872-4952-bdde-732f30d9ff19)

### Code snippets

N/A

### Additional context

N/A

**Comment by Convly** [comment]
Related PR: https://github.com/strapi/strapi/pull/21751

**Comment by Convly** [comment]
Experimental: `0.0.0-experimental.46fff2fd7a1218580f8f7852e7e33574f2082fed`
