### ISSUE TITLE
Dynamic Database Change on MongoDB

### ISSUE THREAD

**Issue by MTM-Suhail** [strapi/strapi#2176]
How can I change database name from controller or Service? One of my project need to access multiple DB based on logged in user.  I am using mongoDB,

**Comment by lauriejim** [comment]
Can you be little more precise of what you want to do please.
I'm not sure to understand.

**Comment by MTM-Suhail** [comment]
I need to know is there any option to change database name at runtime without restart or downtime.

**Comment by derrickmehaffy** [comment]
@MTM-Suhail no as that info is stored in a file, in order for those changes to take effect the server as to be restarted (that is a node.js thing, not a strapi thing. Any file modifications require a restart)

**Comment by MTM-Suhail** [comment]
i can do it by using mongoose, I need to backup local db to server db. did it by adding a crone job


'use strict';
const mongoose = require('mongoose');
var _ = require('lodash');
var Helper = require('./custom/helper');
var isCompleted=[];
var models = [];
var isInitialRun = true;
var isErrorToReset = false;
var server = '127.0.0.1:27017';
var database = 'default';
var username = '';
var password = '';


/**
 * Cron config that gives you an opportunity
 * to run scheduled jobs.
 *
 * The cron format consists of:
 * [MINUTE] [HOUR] [DAY OF MONTH] [MONTH OF YEAR] [DAY OF WEEK] [YEAR (optional)]
 */

module.exports = {
  
 '* * * * * *': async () => {
  try{

    if(isInitialRun){
      let dbConfig = strapi.config.environments.staging.database
      let settings = dbConfig.connections[dbConfig.defaultConnection].settings

      server = settings.host 
      database = settings.database
      username = settings.username
      password = settings.password

      mongoose.connect('mongodb://'+ username + ':' + password + '@'+ server + ',' +
      '/' + database + '?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true');
      for (var key in strapi.api) {
        for (var subkey in strapi.api[key].models) {
          let subval = strapi.api[key].models[subkey]
          isCompleted[subval.globalName] = true
          models [subval.globalName] = mongoose.models[subval.globalName] || mongoose.model(subval.globalName, new mongoose.Schema(Helper.modelToMongoose(subval.attributes)))
        }
      }
      isInitialRun = false
    }

    if(Helper.isCompletedAll(isCompleted)){
      isErrorToReset = false
      let syncData = await strapi.services.sync.fetchAll({})

      for(let item of syncData){
        let name = item.collection_name
        let id = item.related_id

        // set is completed to false to avoid repeatation
        isCompleted[name] = false

        // Load collection data by id
        let data = await strapi.services[name.toLowerCase()].fetch( { _id:id } )

        // save data to corresponded collection
        models[name].findOneAndUpdate({_id:id}, data, {upsert:true}).then(async (result)=>{
          
          // mark completed
          isCompleted[name] = true

          // remove from sync
          await strapi.services.sync.remove( { _id: item._id } )

          console.log('saved ', name)
        }).catch(e=>{
          
          // mark compled true for next try
          isCompleted[name] = true

          // mark error to reset
          isErrorToReset = true

          // reset if isErrorToReset and completed all false (it may lost internet or faced any error that may cleared after 5 seconds)
          setTimeout(()=>{
            if(isErrorToReset && !Helper.isCompletedAll(isCompleted)){
              // set initial run to true
              isInitialRun = true
            }
          },5000)

          console.log('Error ', e)
        })

      }
    }
  }catch(err){
    isCompleted=[]
    models = []
    isInitialRun = true
    console.log(err)
  }
}
};

**Comment by rafaneri** [comment]
I have a similar question, is possible use a different datasource for each content type? For example, Users model are stored in Security mongodb database, while uses Content database for Articles.

**Comment by NikolasMelui** [comment]
I try to do the same, but found this is a great problem, solving by change **schema.graphql** file in `plugins/graphql/config/generated` path.
