### ISSUE TITLE
strapi content-type-builder not installing.

### ISSUE THREAD

**Issue by ikennobunga** [strapi/strapi#2179]
Am using os mojave
node v 10.12.0
npm v 6.4.1
strapi v 3.0.0-alpha.14.3
database mongodb v 4.0.2

when running strapi new project all the plugins install fine appart from the content type builder i get this error.
 An error occurred during content-type-builder plugin installation.
{ Error: Command failed: node /usr/local/lib/node_modules/strapi/bin/strapi.js install content-type-builder

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /usr/local/lib/node_modules/strapi/bin/strapi.js install content-type-builder ' }

when i navigate to the admin panel the content type builder is not avilable. I tried to install it fron the admin panel but it failed to install. 
when looking at the the project folder plugin the folder is there but empty.
I have tried to unistall strapi and installing it but still the content type builder will not install.
pls i need assistance.

**Comment by ikennobunga** [comment]
Hi Jim

Have a look at this error and maybe u can have a clear picture of the issue am having

✔ Copy dashboard
✔ Install plugin settings-manager.
⚠ An error occurred during content-type-builder plugin installation.
{ Error: Command failed: node /usr/local/lib/node_modules/strapi/bin/strapi.js install content-type-builder

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /usr/local/lib/node_modules/strapi/bin/strapi.js install content-type-builder ' }
✔ Install plugin content-manager.
✔ Install plugin users-permissions.
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

As u can see the rest of the plugin are instal in just ok apart from the content-type-builder.

**Comment by lauriejim** [comment]
Did you re-install Strapi and re-create a new app ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
