### ISSUE TITLE
ID in API response is the same for every component.

### ISSUE THREAD

**Issue by at-woutervanderschagt** [strapi/strapi#21799]
### Required System information

- Node - 20.17.0
- NPM - 10.8.3
- Strapi - 5.0.5
- Database: SQLite
- OS - Mac OS 14.6.1
- TypeScript - 5.2.2

### Describe the bug

Using the API to request a Single Type called "GlobalPage" (containing a dynamic zone with 2 components followed by 1 textbox) and endpoint variables: `/${endpoint}?populate=*` returns the same ID for every field. In this case it is "6" everywhere.

```
{
    "data": {
        "id": 6,
        "documentId": "w2osdxytqogupkz1luu9kabi",
        "Textbox1": "test",
        "createdAt": "2024-10-11T06:54:00.058Z",
        "updatedAt": "2024-10-11T08:06:47.801Z",
        "publishedAt": "2024-10-11T08:06:47.808Z",
        "locale": null,
        "Row1": [
            {
                "__component": "lists.benefit-list",
                "id": 6,
                "Headline": "1_header",
                "Byline": "1_byline"
            },
            {
                "__component": "lists.top-4-benefits",
                "id": 6,
                "Header": "2_header"
            }
        ],
        "localizations": []
    },
    "meta": {}
}
```

I would expect the ID to be different for every component. Or perhaps I'm missing something.

**Comment by at-woutervanderschagt** [comment]
After a few more tests, the behaviour is stranger, some IDs get changed "sometimes". After adding 2 components to the dynamic zone, the result is:

```
{
    "data": {
        "id": 8,
        "documentId": "w2osdxytqogupkz1luu9kabi",
        "Textbox1": "test",
        "createdAt": "2024-10-11T06:54:00.058Z",
        "updatedAt": "2024-10-11T08:19:26.451Z",
        "publishedAt": "2024-10-11T08:19:26.457Z",
        "locale": null,
        "Row1": [
            {
                "__component": "lists.benefit-list",
                "id": 9,
                "Headline": "1_header",
                "Byline": "1_byline"
            },
            {
                "__component": "lists.top-4-benefits",
                "id": 10,
                "Header": "2_header"
            },
            {
                "__component": "lists.top-4-benefits",
                "id": 11,
                "Header": "3_header"
            },
            {
                "__component": "lists.benefit-list",
                "id": 10,
                "Headline": "4_h1",
                "Byline": "4_b1"
            }
        ],
        "localizations": []
    },
    "meta": {}
}
```

**Comment by Brenosalv** [comment]
I’m not sure if it’s the same issue, but in one of my Strapi collections, some documents share the same IDs, causing conflicts. When I update a field in one document, the same field in another document with the same ID also gets updated. It seems like an internal Strapi issue.

**Comment by Brenosalv** [comment]
I’m not sure if it’s the same issue, but in one of my Strapi collections, some documents share the same IDs, causing conflicts. When I update a field in one document, the same field in another document with the same ID also gets updated. It seems like an internal Strapi issue since it should generate different IDs for new fields.

**Comment by Brenosalv** [comment]
I’m not sure if it’s the same issue, but in one of my Strapi collections, some documents share the same IDs, causing conflicts. When I update a field in one document, the same field in another document with the same ID also gets updated. It seems like an internal Strapi issue since it should generate different IDs for new fields.

I did not change anything like API code/model or Strapi version.

**Comment by derrickmehaffy** [comment]
This is intended as the integer IDs are not entirely unique, the document ID of the parent is the unique ID

**Comment by at-woutervanderschagt** [comment]
> This is intended as the integer IDs are not entirely unique, the document ID of the parent is the unique ID

Alright, but then - out of curiosity - what do they represent? They can be the same within a parent / as siblings.

**Comment by derrickmehaffy** [comment]
> > This is intended as the integer IDs are not entirely unique, the document ID of the parent is the unique ID
> 
> Alright, but then - out of curiosity - what do they represent? They can be the same within a parent / as siblings.

It might be a bit easier to understand if you look at the database table structure. Every component type has its own table and there will be a relational joining table between the component data table and the parent content-type table.

I'd suggest popping open your sqlite database or whatever your using in dbeaver and taking a look and I think you'll understand.

**Comment by shekler** [comment]
I wonder why this issue has been closed. Following the **official** guide from Strapi (https://strapi.io/blog/getting-started-with-next-js-and-strapi-5-beginner-s-guide), I encountered the same issue: 

```
{
  id: 8,
  documentId: 'aeh5m8s1vqqfansmfaugdstm',
  name: 'Sven',
  descrption: "Hello, I'm Sven.",
  slug: 'sven',
  createdAt: '2025-01-03T15:21:58.233Z',
  updatedAt: '2025-01-03T18:00:14.746Z',
  publishedAt: '2025-01-03T18:00:14.757Z',
  photo: {
    id: 1,
    documentId: 'ftvbagyg9br2i41tbszliuiz',
    alternativeText: null,
    name: '118_crop.jpg',
    url: '/uploads/118_crop_60bc315eb5.jpg'
  },
  blocks: [
    {
      __component: 'blocks.testimonial',
      id: 13,
      authorName: 'Felix',
      quote: "Felix' Quote",
      photo: {
        id: 1,
        documentId: 'ftvbagyg9br2i41tbszliuiz',
        alternativeText: null,
        name: '118_crop.jpg',
        url: '/uploads/118_crop_60bc315eb5.jpg'
      }
    },
    {
      __component: 'blocks.testimonial',
      id: 14,
      authorName: 'Stephan',
      quote: "Stephan's Quote",
      photo: {
        id: 1,
        documentId: 'ftvbagyg9br2i41tbszliuiz',
        alternativeText: null,
        name: '118_crop.jpg',
        url: '/uploads/118_crop_60bc315eb5.jpg'
      }
    },
    {
      __component: 'blocks.spoiler',
      id: 7,
      title: 'Titel',
      content: 'Text'
    },
    { __component: 'blocks.rich-text', id: 7, content: null }
  ]
}
```

This outputs the following console error with Next.js:

```
Encountered two children with the same key, `7`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
