### ISSUE TITLE
_q search broken due to query param encoding

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#21791]
### Required System information

- Node.js version: v20
- NPM version: yarn v1
- Strapi version: 5.0.4
- Database: SQLite
- Operating system: Linux Mint 21.2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When searching in the content-manager the encoding of the search request is wrong.

Looking at the database query logs it appears the encoded characters are being escaped and are being searched for literally.

### Steps to reproduce the behavior

1. Create some entries in a content-type like `test 1` and `test 2`
2. Try to search specifically for `test 1`
3. Look at REST query logs and database query logs and see that the space is being encoded into `%20`
4. Within the database query see that the `%` is being escaped: `'%test\\%202%'` 
5. See error

### Expected behavior

We should decode the request before handing it off to the database

### Screenshots

![image](https://github.com/user-attachments/assets/36f14d8f-8ceb-4e13-acc1-f3199565f80b)

### Code snippets

N/A

### Additional context

N/A

**Comment by SANGET** [comment]
I have same issue when the parameter is not English.

<img width="1405" alt="image" src="https://github.com/user-attachments/assets/a43d4525-447b-4bb0-a3c7-111c6faeaa45">

Required System information
Node.js version: v20
NPM version: yarn v1
Strapi version: 5.1.0
Database: Postgre

**Comment by artsiompeshko** [comment]
+ 1.

**Comment by derrickmehaffy** [comment]
Bumping sev due to a customer ticket, reference is TID8982
