### ISSUE TITLE
Database installation fails

### ISSUE THREAD

**Issue by Jan10** [strapi/strapi#2181]
**Informations**
- **Node.js version**:  v10.7.0
- **npm version**:  6.1.0
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**:  
- **Operating system**:  Windows 10 Enterprise

**What is the current behavior?**
After I have selected the database, nothing happens. I'm not sure if it's a problem with our corporate 
proxy.

![Uploading 2018-10-22-000014.png…]()

**Steps to reproduce the problem**
- Strapi new newProject
- Select MongoDB

**Suggested solutions**
An error message or debug mode would be cool :)

**Comment by lauriejim** [comment]
We can't access to your log image

**Comment by maturanomx** [comment]
Search; it's a know issue on Windows. One workaround is pass all parameters to the cli.
