### ISSUE TITLE
CORS policy Error in Production

### ISSUE THREAD

**Issue by BayBreezy** [strapi/strapi#21836]
### Required System information

- Node.js version: v20.14.0
- NPM version: 10.7.0
- Strapi version: 5.0.6
- Database: MYSQL 8
- Operating system: MacOs
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The application works flawlessly in development.

When I run the build command and start the Strapi app in production mode, My frontend(Nuxt 3 application) is unable to get any data from the api.

I get this error each time I send a request

```
Access to fetch at 'http://localhost:1337/api/auth/local' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Middleware Config

This is what My middleware looks like

```ts
export default [
  "strapi::logger",
  "strapi::cors",
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "script-src": ["'self'", "'unsafe-inline'", "editor.unlayer.com"],
          "frame-src": ["'self'", "editor.unlayer.com"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  {
    name: "strapi::poweredBy",
    config: {
      poweredBy: "Me",
    },
  },
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::responseTime",
  "strapi::public",
  { resolve: "./src/middlewares/confirmation-error-redirect" },
];
```

### What did you try?

I followed the stuff outlined here: https://github.com/strapi/strapi/issues/20971 but it did not help.

I also tried changing between `localhost:1337` & `127.0.0.1:1337` for the API URL on the frontend.

I tried passing in a custom cors config and added `localhost:3000` to the list of origins but that did not make a change.

### Steps to reproduce the behavior

1. Create a strapi 5 app
2. Create a frontend app (vue,react,nuxt)
3. Build your strapi app for production `npm run build && NODE_ENV=production npm run start`
4. Send a login request to the API

### Expected behavior

I expect the api to respond with an actual response.

### Current behaviour

The request is blocked by CORS

### Screenshots

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/0fc72dee-d186-48dc-beaf-c14b5fbddbe0">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Dharaneesh0745** [comment]
Hii @BayBreezy 

If you're using Typescript and facing a CORS error in production means, just write the ORIGIN as usual in your code. Before pushing your code to production, don't forget to run the build command, `npm run build`. Because in production, it always runs the Javascript code not the Typescript code. Once you have built your code using the build command, where the build Javascript files have been stored inside a dist or build folder based on your `tsconfig.json` configuration. Every time you make changes in typescript code, don't forget to run the build command before pushing your code to the production environment.

Sample code of mine,

```
const allowedOrigins = ["http://localhost:3000", "https://mudomain.com"]

app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin || allowedOrigins.includes(origin)) {
        callback(null, true);
      } else {
        callback(new Error("Your client url is not allowed by CORS"))
      }
    },
    credentials: true
  })
)
```
This one fixed my CORS error.

![image](https://github.com/user-attachments/assets/7d3f0516-31c2-4114-80b4-91d7cded2886)

**Comment by BayBreezy** [comment]
Hey @Dharaneesh0745 ,

I did use `npm run build` and then `NODE_ENV=production npm run start` to start the api in production mode.

As fro the sample code, can you say where exactly you added it?

**Comment by BayBreezy** [comment]
Found what the issue was. I added some custom code that was silently ignoring an error being thrown. Found the error and removed it. the endpoint now works
