### ISSUE TITLE
Incorrect endpoint api call with getFetchClient from admin panel for custom admin routes

### ISSUE THREAD

**Issue by WardenCommander** [strapi/strapi#21832]
### Required System information

- Node.js version: v20
- NPM version: 10.9
- Strapi version: 5.0.6
- Database: sqlite
- Operating system: win10
- Is your project Javascript or Typescript: Typescript

### Describe the bug

there is issue with custom admin route when, when making get request to custom admin route in strapi admin panel.
example route: /user-permissions/locations ( this is the route i defined and it was working, and returning values)
sometime for same request i get in logs request to: /admin/plugins/undefined/user-permissions/locations

maybe i defined route in wrong way but it shoudnt sometine work sometimes not

### Steps to reproduce the behavior

build custom admin route for plugin, and try to interact with it in plugin page or content-manager sidebar

### Expected behavior
to have unified api calls

### Screenshots

![2024-10-14_15-52-47](https://github.com/user-attachments/assets/d38a95d1-e012-4428-9556-e5de9e298194)

**Comment by dmitrysmagin** [comment]
In case someone finds this issue again, I have my own explanation.
When fixing this kind of warning for my plugin:

> [Media Library]: [deprecated] addSettingsLink() was called with an async Component from the plugin "Media Library". This will be removed in the future. Please use: `Component: () => import(path)` ensuring you return a default export instead.

It is important to do strictly as this warning says. If you try to:

````React
import App from "path";

....
Component: () => App,

````

You will get exactly the same error with corrupt endpoint paths when using getFetchClient()
