### ISSUE TITLE
Migration issue in Postgres

### ISSUE THREAD

**Issue by vedbhanushal1** [strapi/strapi#21848]
## Bug report

MigrationError: Migration 5.0.0-05-drop-slug-fields-index (up) failed: Original error: select * from information_schema.tables where table_name = $1 and table_schema = current_schema() - current transaction is aborted, commands ignored until end of transaction block

### Required System information

- Node.js version: V18.20.3
- NPM version:
- Strapi version: V5.0.6 (have tried with all patches of V5 getting in all)
- Database: Postgres
- Operating system: Ubuntu 22.04.3 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

earlier I was on Strapi Version : 5.0.0-beta.17 and when I have upgraded the version to 5.0.6
and building my application ```npm run build``` facing database migration issue.

**Comment by kaue-delmonte-acn** [comment]
Same issue here.

**Comment by kauedelmonte** [comment]
Same issue here.

**Comment by kauedelmonte** [comment]
@Marc-Roig can you help us?

My and @vedbhanushal1 case was migrating from 5.x.x-beta.xx to 5.0.x.

Some prints:

Strapi log:
![image](https://github.com/user-attachments/assets/6cfbf147-b95a-4147-9d34-48a5c653543c)

Postgres log:
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/a141f759-ae71-4b82-ac60-a412dda4f5d8">

**Comment by joojp17** [comment]
Did you manage to find a solution?

**Comment by innerdvations** [comment]
It appears this issue is only caused by migrating from a v5 beta to a release v5, so we are unable to support it. However, I can guess at the workaround based on the error message to get you up and running again :)

If you create unique indexes on based on the errors shown, each time you add one, it will give an error with the new one to create. Eventually (once you've created all the missing indexes) it should work.

That is, with the example shown by @kauedelmonte you would need to create a unique index called "blogs_slug_unique" on your "blogs" table

**Comment by innerdvations** [comment]
Closing because it only appears to affect beta; if anyone faces this issue upgrading from a 4.x version, we can reopen

**Comment by fmlukaszmatusik** [comment]
My solution

1. yarn add patch-package
2. create /patches directory (e.g. backend/patches)
3. create file `@strapi+database+5.26.0.patch` (with your strapi version in name)
4. add content below to this file

```
diff --git a/node_modules/@strapi/database/dist/migrations/internal-migrations/5.0.0-05-drop-slug-unique-index.js b/node_modules/@strapi/database/dist/migrations/internal-migrations/5.0.0-05-drop-slug-unique-index.js
index cc1b216..8dbae1e 100644
--- a/node_modules/@strapi/database/dist/migrations/internal-migrations/5.0.0-05-drop-slug-unique-index.js
+++ b/node_modules/@strapi/database/dist/migrations/internal-migrations/5.0.0-05-drop-slug-unique-index.js
@@ -1,43 +1,16 @@
 'use strict';
-
-/**
- * In V4 slug fields contained a unique index.
- * In V5 slug fields should not have a unique index.
- *
- * This migration drops existing unique indexes from slug fields so downstream migrations
- * can work on the data without violating the unique index.
- */ const dropIndex = async (knex, tableName, columnName)=>{
-    try {
-        await knex.schema.alterTable(tableName, (table)=>{
-            // NOTE: Can not use "identifiers" utility, as the 5.0.0-01 migration does not rename this particular index
-            // to `tableName_columnName_uq`.
-            table.dropUnique([
-                columnName
-            ], `${tableName}_${columnName}_unique`);
-        });
-    } catch (error) {
-    // If unique index does not exist, do nothing
-    }
-};
-const dropSlugFieldsIndex = {
-    name: '5.0.0-05-drop-slug-fields-index',
-    async up (knex, db) {
-        for (const meta of db.metadata.values()){
-            const hasTable = await knex.schema.hasTable(meta.tableName);
-            if (!hasTable) {
-                continue;
-            }
-            for (const attribute of Object.values(meta.attributes)){
-                if (attribute.type === 'uid' && attribute.columnName) {
-                    await dropIndex(knex, meta.tableName, attribute.columnName);
-                }
-            }
-        }
-    },
-    async down () {
-        throw new Error('not implemented');
-    }
-};
-
-exports.dropSlugFieldsIndex = dropSlugFieldsIndex;
-//# sourceMappingURL=5.0.0-05-drop-slug-unique-index.js.map
+// PATCHED MIGRATION: skip problematic slug index migration (Postgres 25P02 issue)
+
+const dropIndex = async (knex, tableName, columnName) => {};
+
+const dropSlugFieldsIndex = {
+  name: '5.0.0-05-drop-slug-fields-index',
+  async up(knex, db) {
+    console.log('⚠️ Skipping migration 5.0.0-05-drop-slug-unique-index.js due to Postgres conflict.');
+  },
+  async down() {
+    // nothing to revert
+  },
+};
+
+export { dropSlugFieldsIndex };
```

6. run in CLI: `patch-package`

It should apply a patch to skip this problematic migration (you can also try to fix it in any other way)

**Comment by Zelatrixx** [comment]
I tried migrating Strapi from 4.26.1 to 5.36.1 and encountered the same issue.

Database: PostgreSQL 18.0
Node.js: v20.20.0
pnpm: v10.30.1
OS: Ubuntu 24.04.3 LTS

The problem occurs in migration 5.0.0-05-drop-slug-fields-index, where dropUnique may fail if the expected constraint name does not exist. This causes PostgreSQL to abort the transaction and stops the migration process.

**Fix**. Replace the contents of the dropIndex function with a raw SQL statement using IF EXISTS. Full function:

<pre>
const dropIndex = async (knex, tableName, columnName)=>{
    await knex.raw(`ALTER TABLE "${tableName}" DROP CONSTRAINT IF EXISTS "${tableName}_${columnName}_unique"`)
};
</pre>

Using DROP CONSTRAINT IF EXISTS prevents PostgreSQL from throwing an error if the constraint is already absent, making the migration idempotent and avoiding transaction aborts.

A good way to apply this fix is to create a patch for @strapi/database.

**Comment by fmlukaszmatusik** [comment]
@innerdvations I think you should guys re-open
