### ISSUE TITLE
V5: Headers missing in OPTIONS request

### ISSUE THREAD

**Issue by HRRED** [strapi/strapi#21846]
### Required System information

- Node.js version: v20.15.0
- NPM version: 10.7.0
- Strapi version: 5.0.5
- Database: MySQL
- Operating system: MacOS Sonoma 14.5
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When sending an `OPTIONS` request to Strapi V5, none of the headers configured in the `strapi::cors` or the `strapi::security` middleware are set, unlike Strapi V4 as shown in the screenshots section. This causes CORS issues when sending requests with `withCredentials` set to `true`.

### Steps to reproduce the behavior

1. Create a Strapi V5 project
2. Configure the CORS middleware with origin (Example in the Code Snippets section)
3. Send an `OPTIONS` request to an endpoint with an `Origin` header configured and an `Access-Control-Request-Method` header set to `POST`.
4. None of the headers from the Strapi middlewares are set.

### Expected behavior

The response should include Access-Control headers as well as any headers configured by the `strapi::security` middleware. 

### Screenshots

The response in Strapi V4:
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/f19bfacd-2827-4ae0-89d7-2680111ed42e">

The response in Strapi V5:
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/643250aa-5cee-45a8-8482-357795e85122">

### Code snippets

The `strapi::cors` middleware configuration:
```Javascript
{
    name: 'strapi::cors',
    config: {
      headers: [
        'Content-Type',
        'Authorization',
        'Origin',
        'Accept',
      ],
      origin: [
        // Local API
        'http://localhost:1337',
        'http://localhost:1338',

        // Local Frontend
        'http://localhost:3000',
        'http://localhost:5173',
      ],
      keepHeaderOnError: true,
    }
  }
  ```

**Comment by praharshaAdhikari** [comment]
Same issue here. It broke my auth that set refreshToken and accessToken as server-side-cookie.

**Comment by derrickmehaffy** [comment]
Possible related cloud ticket: TID8590

**Comment by derrickmehaffy** [comment]
> Reported a similar issue yesterday: #21836 Sending a request to auth/local sends back a cors error. I too tried to configure the cors middleware with no success

Looks quite similar but that one is touching the security middleware rather than the CORs one :thinking:

**Comment by BayBreezy** [comment]
Are you saying the error I am getting is because of the security configuration I have setup?

**Comment by alexandrebodin** [comment]
Hi 👋 

Ok so when you run yarn build and then yarn start with strapi  (so production mode) the headers work correctly. In dev mode I believe the vite middleware for rendering is messing up with our middlewares. 

Can you confirm everything is working in production mode please ?

**Comment by alexandrebodin** [comment]
I release an experimental version that aims at fixing this. Could you try it please `0.0.0-experimental.73ff3d9f3b7e8959f6c88caa89c356b1d3695824`

**Comment by okotajarvi** [comment]
@alexandrebodin Tried the version you mentioned.
My middleware configuration:
```
export default [
    'strapi::logger',
    'strapi::errors',
    'strapi::security',
    'strapi::poweredBy',
    {
        name: 'strapi::cors',
        config: {
            origin: ['http://localhost:4200'],
            methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD'],
            headers: [
                'Origin',
                'Accept',
                'Content-Type',
                'Authorization',
                'X-Frame-Options',
                'X-Forwarded-For',
                'Access-Control-Allow-Credentials',
                'Access-Control-Allow-Origin',
            ],
            credentials: true,
            keepHeaderOnError: true,
        },
    },
    'strapi::query',
    'strapi::body',
    'strapi::session',
    'strapi::favicon',
    'strapi::public',
    'global::token-middleware',
];
```
Response to `OPTIONS` request via postman:
![Screenshot 2024-10-22 at 9 29 05](https://github.com/user-attachments/assets/b396868b-4758-4c12-9799-fde9bcd84285)

This was with `NODE_ENV=development`, `Access-Control-Allow-Origins` is set to `*`. With `NODE_ENV=production` the result of the `OPTIONS` fetch is a bit different, but `Access-Control-Allow-Origin` is still missing
![Screenshot 2024-10-22 at 9 30 41](https://github.com/user-attachments/assets/2fb3adfb-6dcb-4e5c-a0e0-2fde0388db0f)

**Comment by alexandrebodin** [comment]
@okotajarvi Can you share the request headers please ?

**Comment by HRRED** [comment]
@alexandrebodin I managed to replicate the response from @okotajarvi.

My middleware config:
```Javascript
{
  name: 'strapi::cors',
  config: {
    headers: [
      'Content-Type',
      'Authorization',
      'Origin',
      'Accept',
    ],
    origin: [
      'http://localhost:5173',
    ],
    keepHeaderOnError: true,
  }
}
```

When running in production mode, I got the following response:
![image](https://github.com/user-attachments/assets/f0d1048d-818d-4d11-8d74-e89f76b88388)
All `Access-Control` headers are missing even with my `Origin` header present.

When running in development, I got the following response:
![image](https://github.com/user-attachments/assets/196bc7ce-552b-4687-9662-e9eb151e65fa)
The `Access-Control` headers are now present, but the `Access-Control-Allow-Origin` is set to `*` eventhough an `Origin` header is present in the request headers.

**Comment by derrickmehaffy** [comment]
Note the way CORs functions is that if you are on the same domain (say localhost) then CORs generally isn't gonna respond or give you a * response. (There is some debate around the spec as to whether the port is part of the origin or not)

CORs = Cross-Origin Resource Sharing meaning it's expected to only kick in if the origin is actually different 

Typically if you want to test CORs locally you should test with a reverse proxy and a locally resolving domain (doesn't need to be real, and you resolve it from your hosts file). But you can fake it like you are doing in postman.

Can you try running a test using postman but set your Origin to something besides a localhost address? (And of course configure that in Strapi too).

Ideally the "request" should be coming from a "different" origin that what Strapi is running on. Our code for CORs is very minimal and we are primarily relying on the spec implemented by Koa itself: 

https://github.com/strapi/strapi/blob/develop/packages/core/core/src/middlewares/cors.ts

**Comment by derrickmehaffy** [comment]
Also FYI `keepHeaderOnError` should be `keepHeadersOnError`

See: https://github.com/koajs/cors/blob/master/index.js#L14

**Comment by HRRED** [comment]
@derrickmehaffy I setup Strapi to use some testing domain and configured a different origin with the same result.

Development output:
![image](https://github.com/user-attachments/assets/aa1d750e-e8a7-4c70-aed7-73d7acd6461c)

Production mode output:
![image](https://github.com/user-attachments/assets/3eba6cb6-9841-49eb-ba5d-95c065d34a4a)

While i've seen some discussion about the port being part of the origin, Chrome will treat different ports as different origins anyway, which causes CORS errors. Strapi V4 did treat different ports as different origins, as can be seen in the screenshots in the original report.
