### ISSUE TITLE
please help im using it during my exam right now

### ISSUE THREAD

**Issue by 1ilshi** [strapi/strapi#21845]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

 ``` TypeError: Cannot read properties of undefined (reading 'list')     at http://localhost:1337/node_modules/.strapi/vite/deps/ListViewPage-CELx2ysp-LSRD54RV.js?v=89167e8f:191:71     at Array.map (<anonymous>)     at http://localhost:1337/node_modules/.strapi/vite/deps/ListViewPage-CELx2ysp-LSRD54RV.js?v=89167e8f:186:7     at mountMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=89167e8f:12214:27)     at Object.useMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=89167e8f:12538:24)     at Object.useMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BCGHH3YY.js?v=89167e8f:1094:29)     at FiltersImpl (http://localhost:1337/node_modules/.strapi/vite/deps/ListViewPage-CELx2ysp-LSRD54RV.js?v=89167e8f:173:34)     at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=89167e8f:11568:26)     at mountIndeterminateComponent (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=89167e8f:14946:21)     at beginWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=89167e8f:15934:22) ```       

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Marc-Roig** [comment]
We would need a bit more context to identify whats causing the issue, e.g. saying when that issue occurs and at which step.

Hope your exam turned out ok!
