### ISSUE TITLE
Self referencing content types many to many

### ISSUE THREAD

**Issue by wdavidw** [strapi/strapi#2185]
I am trying to model a relation of type many-to-many between records of the same content types.

Here is an example use case. I am creating articles. Each article can be translated into multiple languages. I wish to end up with a list of translated articles. Here is how my WordPress looks like:

![Wordpress Translations](http://www.adaltas.com/wp-content/uploads/2018/10/wordpress_translations.png)

The current implementation implies creating two fields (for example "articles_targetting" and "articles_referencing"). It works but it is quite inconvenient. It implies managing the translated articles on a per document basis. If a new translation is added, the relation must be created for every document. It would be more convenient to only have one field which references other records of the same content type.

It feels to me like this is a new type of many-to-many relation, or maybe is there another way to modelize this scenario which I didn't think about?

Note, this is related to #1507

Thank for your hard work, I just discover Strapi and it looks very promising.

**Comment by wdavidw** [comment]
Without a direction, I could think of a few use cases:
- friends in a user content type
- related pages in a page content type

Also, we could have a checkbox option to filter out the current entity (eg, related pages should not propose the current page being edited)

**Comment by Aurelsicoko** [comment]
Interesting... IMO, there is another way to modelize the scenario. You can create a first entry which will be the parent. Then, every other entry is linked with this parent entry (one-to-many relationship).

Let's take an example, this is my parent entry.
```json
{
  "id": 1,
  "title": "Parent entry",
  "parentEntry": null,
  "relatedArticles": [2, 3]
}
```

You can easily display the related articles by populating the `parentArticle` relationship to retrieve the `relatedArticles` property.
```json
{
  "id": 2
  "title": "Child entry",
  "parentArticle": {
    "id": 1,
    "title": "Parent entry",
    "relatedArticles": [2, 3]
  },
  "relatedArticles": []
}
```

**Comment by wdavidw** [comment]
Yes, I have been thinking about this solution. I came to the conclusion that even if I can apply it to myself, it would be very hard to explain it to my content editors. Also, it is error-prone to creating parent records without children over time.

**Comment by Aurelsicoko** [comment]
@wdavidw Did you try to create the association without using the UI? Does it work?

**Comment by andrewmee** [comment]
@Aurelsicoko I'm not sure if this is what you mean, but I just tried creating a many-to-many relationship from a content type ("product") to itself, manually using this in `product.settings.json`

```
    "products": {
      "collection": "product",
      "via": "products"
    }
```

It looks as though it works, but then when I try to associate one product with another and save, I get a loop in strapi;

```
Mongoose: product.update({ _id: ObjectId("5b969f1a149030087fd98d74") }, { '$setOnInsert': { createdAt: new Date("Wed, 07 Nov 2018 13:44:11 GMT") }, '$set': { updatedAt: new Date("Wed, 07 Nov 2018 13:44:11 GMT"), _id: ObjectId("5b969f1a149030087fd98d74") } }, { strict: false, overwrite: undefined })
Mongoose: product.findOne({ _id: ObjectId("5b96a0ae149030087fd98d7e") }, { projection: {} })
Mongoose: product.find({ products: { '$in': [ ObjectId("5b96a0ae149030087fd98d7e") ] } }, { projection: {} })
Mongoose: product.findOne({ _id: ObjectId("5b96a0ae149030087fd98d7e") }, { projection: {} })
Mongoose: tag.find({ products: { '$in': [ ObjectId("5b96a0ae149030087fd98d7e") ] } }, { projection: {} })
Mongoose: drop.find({ _id: { '$in': [ ObjectId("5b9669b72c0af0482ee57fd1") ] } }, { projection: {} })
Mongoose: collaborator.find({ products: { '$in': [ ObjectId("5b96a0ae149030087fd98d7e") ] } }, { projection: {} })
Mongoose: birthday.find({ products: { '$in': [ ObjectId("5b96a0ae149030087fd98d7e") ] } }, { projection: {} })
Mongoose: product.find({ products: { '$in': [ ObjectId("5b96a0ae149030087fd98d7e") ] } }, { projection: {} })
Mongoose: editorial.find({ products: { '$in': [ ObjectId("5b96a0ae149030087fd98d7e") ] } }, { projection: {} })
Mongoose: upload_file.find({ 'related.kind': 'Product', 'related.field': 'heroImage', 'related.ref': ObjectId("5b96a0ae149030087fd98d7e") }, { sort: { createdAt: -1 }, projection: {} })
Mongoose: upload_file.find({ 'related.kind': 'Product', 'related.field': 'teaserImage', 'related.ref': ObjectId("5b96a0ae149030087fd98d7e") }, { sort: { createdAt: -1 }, projection: {} })
Mongoose: upload_file.find({ 'related.kind': 'Product', 'related.field': 'productImages', 'related.ref': ObjectId("5b96a0ae149030087fd98d7e") }, { sort: { createdAt: -1 }, projection: {} })

```

**Comment by wdavidw** [comment]
@Aurelsicoko I haven't tried to create the association manually. I am not sure how I would create the model to support it while preserving the integrity of the content type in case one of the sides of the relation is deleted or modified. Also, I am using a MongoDB backend but my understanding is that Strapi also using some additionnal ORM to interact with other DBMS.

**Comment by Aurelsicoko** [comment]
I would love to see someone trying to dig into the `strapi-mongoose/lib/relation.js` file to understand what happens... It should work but it doesn't seem to work. I guess this is a case which is not handled.

Currently, we have others priorities. @wdavidw or @andrewmee are you able to take a look?

**Comment by neopit** [comment]
I am facing the same issue on PostGreSQL, I am trying to create a recursive relation on Users-permissions_user.

The idea is users can have several relations with other users (friends).

**Comment by connectwithub** [comment]
I am also facing a similar problem with Mysql. Only one side of the relationship is being updated in my case. I am trying to set up a parent child relation within my model. But if I add one thing as child the parent relation on the other product is being added but the child relation on the product is not being added and vice versa.

**Comment by tristantbg** [comment]
> I am also facing a similar problem with Mysql. Only one side of the relationship is being updated in my case. I am trying to set up a parent child relation within my model. But if I add one thing as child the parent relation on the other product is being added but the child relation on the product is not being added and vice versa.

Same problem with MySQL on a many-to-many relationship on the same model. If it could be fixed soon it would be amazing.

<img width="747" alt="capture d ecran 2019-02-18 a 16 23 44" src="https://user-images.githubusercontent.com/4832038/52965861-19af0900-33a6-11e9-9f57-fbff7d7cf18c.png">

Projects are never saved inside "Projects" and only one is saved at a time on "Project_of" :

<img width="544" alt="capture d ecran 2019-02-18 a 17 53 12" src="https://user-images.githubusercontent.com/4832038/52965873-1f0c5380-33a6-11e9-955d-a8f63b29a909.png">

**Comment by lauriejim** [comment]
It work on last version of Strapi (alpha.26.1)
