### ISSUE TITLE
Getting a 500 error when search by id in relation fields

### ISSUE THREAD

**Issue by danchistyakov** [strapi/strapi#21854]
### Required System information
- Node.js version: 18
- Strapi version: 5.0.6
- Database: Postgres
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When I'm trying to search an entry in relation fields I can't make it due 500 error from Strapi backend. Besides I see documentIds in UI instead of numeric ids. Moreover I see a Postgres error in my strapi logs:

error: select "t0"."id", "t0"."document_id", "t0"."published_at", "t0"."updated_at" from "public"."matches" as "t0" where (("t0"."published_at" is null and "t0"."id" not in (select distinct "t1"."id" from "public"."tournaments" as "t0" left join "public"."tournaments_group_stage_matches_lnk" as "t2" on "t0"."id" = "t2"."tournament_id" left join "public"."matches" as "t1" on "t2"."match_id" = "t1"."id" where ("t1"."id" is not null and "t1"."document_id" is not null and "t0"."document_id" = $1 and "t1"."published_at" is null)) and LOWER("t0"."id") LIKE LOWER($2))) order by "t0"."id" asc limit $3 - function lower(integer) does not exist
error: select "t0"."id", "t0"."document_id", "t0"."published_at", "t0"."updated_at" from "public"."matches" as "t0" where (("t0"."published_at" is null and "t0"."id" not in (select distinct "t1"."id" from "public"."tournaments" as "t0" left join "public"."tournaments_group_stage_matches_lnk" as "t2" on "t0"."id" = "t2"."tournament_id" left join "public"."matches" as "t1" on "t2"."match_id" = "t1"."id" where ("t1"."id" is not null and "t1"."document_id" is not null and "t0"."document_id" = $1 and "t1"."published_at" is null)) and LOWER("t0"."id") LIKE LOWER($2))) order by "t0"."id" asc limit $3 - function lower(integer) does not exist
    at Parser.parseErrorMessage (/opt/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/opt/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/opt/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/opt/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:517:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

### Expected behavior

I can search documents in relation field of entry by numeric ID.

### Screenshots

<img width="1470" alt="Снимок экрана 2024-10-15 в 18 11 24" src="https://github.com/user-attachments/assets/c25cd455-85ac-44ef-8de1-0f2194712230">

**Comment by Marc-Roig** [comment]
hello @danchistyakov
I am currently trying to reproduce the issue, I am able to search relations like you are doing, so I will track from the query you shared (super helpful)

As an alternative, I recommend updating the relation "title"  of your relation.
That way the title of relations will not be the documentId, but a more readable name.

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/ff9fe481-eaa2-48b0-b20d-e53a4c5fba5b">
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/b595d076-b440-481d-a6e2-45a69aee128e">
<img width="947" alt="image" src="https://github.com/user-attachments/assets/4c5921dd-9960-4947-a68f-07979e483bf1">

**Comment by danchistyakov** [comment]
@Marc-Roig, I don't have a title or similar field in my entity. Can I help you to reproduce a 500 error when searching by id or date fields? Now I choose a createdAt field in "Configure view" screen. First, it continue displaying documentIds fields instead of createdAt field. Besides search returns 500 error.
<img width="1468" alt="Снимок экрана 2024-10-23 в 11 31 48" src="https://github.com/user-attachments/assets/80247498-d051-4605-b351-7b2bbe784751">
<img width="842" alt="Снимок экрана 2024-10-23 в 11 33 56" src="https://github.com/user-attachments/assets/51636b37-aa0a-4b2e-a284-67c557acaedd">
