### ISSUE TITLE
Review Workflows and Assignees are deleted when EE license is lost

### ISSUE THREAD

**Issue by StrapiBartosh** [strapi/strapi#21862]
### Required System information

- Node.js version: 20.15.0
- yarn version: 1.22.22
- Strapi version: 5.0.6
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When an EE license experience/is removed and then reinstated, Review Workflows and Assignees are lost. This is different from content history and audit log features, whose db tables stay when an EE license is gone, though aren't updated. 

### Steps to reproduce the behavior

1. Create workflow in EE
2. Add workflows and assignees to content type
3. Remove EE license
4. Add back EE license

### Expected behavior

Review Workflows return

### Screenshots

https://www.loom.com/share/fc68b8036c5b44c296ab74b73914a8ef

### Additional context

In the Loom recording, I am using 5.0.4, but the issue is present in 5.0.6 as well.

**Comment by StrapiBartosh** [comment]
One additional note, if there were RBAC controls set in an RW stage prior to an EE license being lost/expiring, those items are also lost.

**Comment by Marc-Roig** [comment]
Should be ready in the next release! https://github.com/strapi/strapi/pull/21984
