### ISSUE TITLE
Plugin Development Documentation

### ISSUE THREAD

**Issue by diana4397** [strapi/strapi#2187]
**Informations**
- **Node.js version**: 10.12.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: MongoDb
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
$ is not defined

**Steps to reproduce the problem**
1) Generate a plugin using strapi generate: plugin my-plugin
2) Link with npm link strapi-helper-plugin
3) I am using  generated api routes to fetch the data from database
4) I am using ajax call to execute the api.
5) But it occurs me a error saying '$ is not defined'

**What is the expected behavior?**
- The expected behavior is to get the records from database

**Suggested solutions**

**Comment by diana4397** [comment]
I have solved this issue but can you provide the plugin development documentation with example where data is fetch from API

**Comment by lauriejim** [comment]
@soupette Something for you here.
