### ISSUE TITLE
bug: hide or better dynamic zone component name `dynamicContent.0.content`

### ISSUE THREAD

**Issue by reslear** [strapi/strapi#21880]
## Bug report

maybe hide dynamic zone component name `dynamicContent.0.content` or display as `content` ?

### Required System information

- Node.js version: 22
- NPM version: pnpm latest
- Strapi version: 5.1.0
- Database: pg
- Operating system: macos 15
- Is your project Javascript or Typescript: ts

### Steps to reproduce the behavior

1. Create dynamic component & dynamic component with text 
2. add to article 
3. add first item in article 

### Expected behavior

clean text

### Screenshots

![CleanShot 2024-10-16 at 15 54 08@2x](https://github.com/user-attachments/assets/f41711e9-9589-4085-8696-d02b7f8e2847)

**Comment by Convly** [comment]
Hey, thanks for opening this issue. 

Is the field in this component custom-made (e.g. plugin)?

I can't reproduce this issue with our rich text or Markdown editor.

**Comment by reslear** [comment]
hi @Convly yes this is https://market.strapi.io/plugins/@ckeditor-strapi-plugin-ckeditor

**Comment by Marc-Roig** [comment]
As this is an issue with an external plugin I will close this one, and suggest you open it in that repo :) !
