### ISSUE TITLE
Create db schema from models

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#2189]
**What is the expected behavior?**

Hey there!

It would be nice to have the Schema generated based on the schema. This would help to easily migrate between servers where I do not need the data. Also, the tables that strapi created during adding models is incomplete or missing.

Having a mechanism to regenerate the schema or have the schema saved as file would be very nice.

**Comment by Aurelsicoko** [comment]
Excellent feature request as always 👍

**Comment by Aurelsicoko** [comment]
I'm closing the issue to keep the repository as clear as possible. If anyone has any feedback, please send us on Product Board, instead, you can still use this issue, if you want to discuss the feature because Product Board doesn't allow public comments for now.

**Comment by SeedyROM** [comment]
Any update on this feature?

**Comment by derrickmehaffy** [comment]
@SeedyROM no update, you are welcome to submit a PR though.

**Comment by dafang** [comment]
+1

**Comment by choudharypravesh03** [comment]
+1

**Comment by MartinMuzatko** [comment]
Can someone maybe point to the function where the fields/tables are generated by using the content type generator?
Then we can easily re-use this for an existing JSON schema

**Comment by lauriejim** [comment]
In fact, the content-type-builder not generate table in the database.
It only generates model files.
Then during the server restart, the ORM you use checks and generates table/column if necessary.
[Here](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js) is for Bookshelf for example.

**Comment by storm1er** [comment]
Duplicates of #672

**Comment by paolodina** [comment]
Bookshelf example updated url: https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js

**Comment by matheusramos** [comment]
and yet, the bookshelf example updated url: https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/build-database-schema.js
