### ISSUE TITLE
MigrationError: Migration 5.0.0-02-created-document-id (up) 

### ISSUE THREAD

**Issue by tomh4** [strapi/strapi#21899]
## Bug report
Migrating from Strapi 4 to 5 results in the following error when running the app the first time in v5

`
MigrationError: Migration 5.0.0-02-created-document-id (up) failed: Original error:
││   SELECT "regions".id as id, string_agg(DISTINCT "inv_region_id"::character varying, ',') as other_ids
││   FROM "regions"
││   LEFT JOIN "regions_localizations_links" ON "regions".id = "regions_localizations_links"."region_id"
││   WHERE document_id IS NULL
││   GROUP BY "regions".id, "region_id"
││   LIMIT 1;
││   - column reference "region_id" is ambiguous
││   at /.../node_modules/umzug/lib/umzug.js:169:27
││   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
││   at async Umzug.runCommand
││   (/.../node_modules/umzug/lib/umzug.js:125:20)
││   at async Object.up
││   (/.../node_modules/@strapi/database/dist/index.js:6532:7)
││   at async Object.up
││   (/...node_modules/@strapi/database/dist/index.js:6556:11)
││   at async Object.sync
││   (/.../node_modules/@strapi/database/dist/index.js:2246:9)
 ││   at async Strapi.bootstrap
││   (/.../node_modules/@strapi/core/dist/Strapi.js:351:5)
││   at async Strapi.load
││   (/.../node_modules/@strapi/core/dist/Strapi.js:315:5)
││   at async Module.develop
││   (/.../node_modules/@strapi/strapi/dist/node/develop.js:177:28)
││   at async action (/.../node_modules/@strapi/strapi/dist/cli/comm
││   ands/develop.js:18:5)
`
### Required System information
- Node.js version: 20
- Strapi version: v4 latest to v5
- Database: PostgreSQL
- Operating system: macOS

### Describe the bug

Migrating from Strapi 4 to 5 results in the following error when running the app the first time in v5

**Comment by killthekitten** [comment]
@tomh4 @balavigs having the same issue, and just checking: do you have a content type called "document"? It could be that the column referenced in the migration is clashing with a foreign key of your content type's table.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/21607

**Comment by killthekitten** [comment]
Hey @derrickmehaffy, the issue you referenced is related to a different migration. Are you sure this is a duplicate?

**Comment by killthekitten** [comment]
@derrickmehaffy I have more details on this error. Turns out, every `localizations_links` table has a foreign key column that matches the content type's singular name, i.e. `homepages_localizations_links` would have a `homepage_id` column and the `documents_localizations_links` would have a `document_id` column of type `integer`: 

```

                                     Table "public.documents_localizations_links"
     Column      |       Type       | Collation | Nullable |                          Default                          
-----------------+------------------+-----------+----------+-----------------------------------------------------------
 id              | integer          |           | not null | nextval('documents_localizations_links_id_seq'::regclass)
 document_id     | integer          |           |          | 
 inv_document_id | integer          |           |          | 
 document_order  | double precision |           |          | 
Indexes:
    "documents_localizations_links_pkey" PRIMARY KEY, btree (id)
    "documents_localizations_links_fk" btree (document_id)
    "documents_localizations_links_inv_fk" btree (inv_document_id)
    "documents_localizations_links_order_fk" btree (document_order)
    "documents_localizations_links_unique" UNIQUE CONSTRAINT, btree (document_id, inv_document_id)
Foreign-key constraints:
    "documents_localizations_links_fk" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
    "documents_localizations_links_inv_fk" FOREIGN KEY (inv_document_id) REFERENCES documents(id) ON DELETE CASCADE




                                     Table "public.homepages_localizations_links"
     Column      |       Type       | Collation | Nullable |                          Default                          
-----------------+------------------+-----------+----------+-----------------------------------------------------------
 id              | integer          |           | not null | nextval('homepages_localizations_links_id_seq'::regclass)
 homepage_id     | integer          |           |          | 
 inv_homepage_id | integer          |           |          | 
 homepage_order  | double precision |           |          | 
Indexes:
    "homepages_localizations_links_pkey" PRIMARY KEY, btree (id)
    "homepages_localizations_links_fk" btree (homepage_id)
    "homepages_localizations_links_inv_fk" btree (inv_homepage_id)
    "homepages_localizations_links_order_fk" btree (homepage_order)
    "homepages_localizations_links_unique" UNIQUE CONSTRAINT, btree (homepage_id, inv_homepage_id)
Foreign-key constraints:
    "homepages_localizations_links_fk" FOREIGN KEY (homepage_id) REFERENCES homepages(id) ON DELETE CASCADE
    "homepages_localizations_links_inv_fk" FOREIGN KEY (inv_homepage_id) REFERENCES homepages(id) ON DELETE CASCADE
```

When the migration takes care of the `documents_localizations_links` table, it runs into a naming conflict on this line:
https://github.com/strapi/strapi/blob/3fdd03038d558a8190aa7e17574020c5f65395e6/packages/core/database/src/migrations/internal-migrations/5.0.0-02-document-id.ts#L36

I believe `WHERE document_id IS NULL` should become `WHERE :tableName:.document_id is NULL`. The migration is quite complex, so I am not sure which other issues this naming conflict could have caused, but there could be more. In particular, I would like to understand whether this line would run for every table in the DB or only for the document tables:

https://github.com/strapi/strapi/blob/3fdd03038d558a8190aa7e17574020c5f65395e6/packages/core/database/src/migrations/internal-migrations/5.0.0-02-document-id.ts#L161

**Comment by killthekitten** [comment]
I've opened a PR to fix this:

https://github.com/strapi/strapi/pull/22049

**Comment by derrickmehaffy** [comment]
Ah I see what you mean yeah not a duplicate sorry

**Comment by balavigs** [comment]
> @tomh4 @balavigs I ran into the same issue, and I wanted to check: do you have a content type called "document"? It could be that the column referenced in the migration is clashing with a foreign key of your content type's table.

@killthekitten you are right. I had a collection named document and hence i believe, we ran into this migration error. Also, just observed that the patch is supporting only postgres DB. You could update the same fix for the other supported dbs as well.

**Comment by killthekitten** [comment]
@balavigs I believe I added all three DBs to the PR. By the way, would you have a chance to test it? You could apply it with [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by tomh4** [comment]
@killthekitten I have no type called "document" unfortunately, as you can see from my first message it is affecting the "region", but I think I found the problem: 
I have a field called regionID, which is some ID assigned by myself. So I guess the upgrade fails as there would be two region_id fields? So this is still another issue than the "document" one but not sure if your patch solves both?
<img width="623" alt="image" src="https://github.com/user-attachments/assets/f6caa566-6e04-484c-a252-3d091f1cafba">

**Comment by killthekitten** [comment]
@tomh4 I believe it would solve both, yes!

**Comment by balavigs** [comment]
> GROUP BY :tableName:.id, :joinTableName:.:joinColumn:

@killthekitten , my bad. in the message 
https://github.com/strapi/strapi/issues/21899#issuecomment-2452008246
, only lines 36 & 37 were highlighted. I couldn't get the chance to look into the PR earlier.

I got a chance to apply the patch and it is working fine. My migration is complete after this patch is used.

**Comment by derrickmehaffy** [comment]
@killthekitten got an update from our engineering team that your PR is next on this list to review to confirm it fixes the issue. We should be able to merge it within the next week or two if all looks good.
