### ISSUE TITLE
Component Registration in Strapi Plugin Breaks Content-Type Creation: 'Path Argument Undefined'

### ISSUE THREAD

**Issue by Blovario** [strapi/strapi#21903]
### Required System information

- **Node.js version**: v18.x
- **NPM version**: 8.x
- **Strapi version**: 4.25.0
- **Database**: SQLite
- **Operating system**: macOS
- **Is your project Javascript or Typescript**: Typescript

### Describe the bug

I'm encountering an issue with a custom Strapi plugin where I'm registering components and using them in content types. Whenever I include a registered component in a content type inside the plugin, the admin UI throws an error when trying to create a new content type.

The error message is as follows:

```
[2024-10-17 11:56:04.767] error: Error writing schema files
[2024-10-17 11:56:04.767] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
.....
.....
.....
[2024-10-17 11:56:04.767] error: Error rolling back schema files. You might need to fix your files manually
[2024-10-17 11:56:04.768] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1171:7)
```

This issue only occurs when a component is registered and used in the plugin's content type. If I remove the component from the content type, everything works as expected.

### Steps to reproduce the behavior

1. Create a custom Strapi plugin.
2. Register a component within the plugin (`server/register.ts`).
3. Include the registered component in a content type inside the plugin (`content-types/article/index.ts`).
4. Try to create a new content type through the Strapi admin UI.
5. Observe the error.

### Expected behavior

I expect to be able to create new content types through the Strapi admin UI, even when a registered component is used within a plugin's content type.

### Code snippets

1. **Content type in the plugin (`content-types/article/index.ts`)**:

```typescript
"use strict";

export default {
  collectionName: 'articles',
  info: {
    singularName: 'article',
    pluralName: 'articles',
    displayName: 'Articles',
  },
  options: {
    draftAndPublish: true,
  },
  attributes: {
    title: {
      type: 'string',
      required: true,
      configurable: false,
    },
    body: {
      type: 'text',
      configurable: false,
    },
    slug: {
      type: 'uid',
      targetField: 'title',
      required: true,
      configurable: false,
    },
    metadata: {
      type: 'component',
      repeatable: false,
      component: 'article.metadata',
      configurable: false,
    },
  },
};
```

2. **Component registration in the plugin (`server/register.ts`)**:

```typescript
import { Schema, Strapi } from '@strapi/strapi';

export default ({ strapi }: { strapi: Strapi }) => {
  const articleMetadata: Schema.Component = {
    collectionName: "components_article_metadata",
    category: "article",
    modelName: "metadata",
    globalId: "ComponentArticleMetadata",
    uid: "article.metadata",
    modelType: "component",
    attributes: {
      author: { type: "string" },
      publishedAt: { type: "datetime" },
      keywords: { type: "string" }
    },
    options: {},
    pluginOptions: {},
    info: {
      displayName: "Metadata",
    },
  };

  // Registering the component
  strapi.components[articleMetadata.uid] = articleMetadata;
};
```

### Additional context

This problem occurs only when registering a component inside a plugin and using it in a content type. Removing the component allows content type creation to work fine. Could there be an issue with how components are handled inside plugins?

**Comment by derrickmehaffy** [comment]
Components are not currently supported in plugins
