### ISSUE TITLE
[Strapi - Enterprise Edition] How to enable the Content History feature on the Strapi 5 with STRAPI_LICENSE 

### ISSUE THREAD

**Issue by hoqkhanh** [strapi/strapi#21908]
### Required System information

- Node.js version: 18
- NPM version: 10.7.0
- Strapi version: 5.1.0
- Database: Mysql
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After activating the Enterprise license, most features like SSO, Review Workflow, and Audit Log are visible. However, the Content History feature is missing.

### Steps to reproduce the behavior
1. Add the STRAPI_LICENSE key to your .env file.
2. Run the following commands:

yarn install
yarn build
yarn develop

3. Navigate to the content edit page.
4. Notice the absence of the Content History feature.

### Expected behavior
The Content History feature should be visible when editing collection or single content items.

### Screenshots

<img width="1498" alt="Screenshot 2024-10-18 at 13 22 20" src="https://github.com/user-attachments/assets/f690ac95-cae5-4b6d-be0a-6a4b9830706f">
<img width="1212" alt="Screenshot 2024-10-18 at 13 21 52" src="https://github.com/user-attachments/assets/2ea1a145-9de1-417e-a278-626aa2232f26">

**Comment by alexandrebodin** [comment]
Hi @hoqkhanh. Could you please reach out to support so we can get some more details please :)

**Comment by derrickmehaffy** [comment]
Closing, please open a ticket with our support team
