### ISSUE TITLE
Graphql data includes all relational objects when no relation is selected

### ISSUE THREAD

**Issue by pbov** [strapi/strapi#2192]
**Informations**
- **Node.js version**: v10.0.0
- **npm version**: 6.0.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**:  MySQL 5.7.24
- **Operating system**: macOS 10.14 (Mojave)

**What is the current behavior?**
Having a many-to-many relation, graphql shows the list of all foreign elements of a relation when none is selected in an element.

**Steps to reproduce the problem**
1. fresh strapi install + graphql
2. create content types:
- song with title (string)
- artist with name (string)
3. add relation between song and artist (many to many)
4. add some artists (A1, A2, A3...)
5. add some songs (S1, S2, S3...)
6. add in S1: A1
7. add in S2: A2, A3
8. request in graphql:

`query {
  songs {
    title
    artists {
      name
    }
  }
}`

and get the result:

`{
  "data": {
    "songs": [
      {
        "title": "S1",
        "artists": [
          {
            "name": "A1"
          }
        ]
      },
      {
        "title": "S2",
        "artists": []
      },
      {
        "title": "S3",
        "artists": [
          {
            "name": "A1"
          },
          {
            "name": "A2"
          },
          {
            "name": "A3"
          },
          {
            "name": "A4"
          }
        ]
      }
    ]
  }
}`

Here you can see, song "S3" shows the complete list of artists, although S3 has no artists.

Optional: Verify REST call (correct result):

Visit http://localhost:1337/songs and get:

`[{"id":1,"title":"S1","created_at":"2018-10-24T11:13:15.000Z","updated_at":"2018-10-24T11:13:46.000Z","artists":[{"id":1,"name":"A1","created_at":"2018-10-24T11:13:26.000Z","updated_at":"2018-10-24T11:13:26.000Z"}]},{"id":2,"title":"S2","created_at":"2018-10-24T11:13:18.000Z","updated_at":"2018-10-24T11:23:50.000Z","artists":[{"id":3,"name":"A3","created_at":"2018-10-24T11:13:30.000Z","updated_at":"2018-10-24T11:13:30.000Z"},{"id":2,"name":"A2","created_at":"2018-10-24T11:13:28.000Z","updated_at":"2018-10-24T11:13:28.000Z"}]},{"id":3,"title":"S3","created_at":"2018-10-24T11:13:20.000Z","updated_at":"2018-10-24T11:43:22.000Z","artists":[]}]`

Here you can see: the artists array is empty for S3.

**What is the expected behavior?**

Empty list/array when no objects are related.

**Suggested solutions**

Fix code for graphql ;)

**Comment by Aurelsicoko** [comment]
@pbov I've followed the instructions and I wasn't able to reproduce using MongoDB and MySQL. I'm closing this issue. Can you try to re-test with the latest version of Strapi and ping me if needed.
