### ISSUE TITLE
Strapi 5 with Postgresql is extremely and unreasonably slow.

### ISSUE THREAD

**Issue by eran-colors** [strapi/strapi#21924]
### Required System information

Launched In: 184 ms
Environment: development
OS: darwin-arm64
Strapi Version: 5.1.0
Node/Yarn Version: yarn/1.22.22 npm/? node/v20.17.0 darwin arm64
Edition: Community
Database: postgres
Using typescript

### Describe the bug

I was using SQLite when i started the strapi project and all was fine, after switching to postgresql the performance has become ridiculous.

The postgresql is hosted on GCP and it is a v2 cpu with 8gb of RAM, it also hosts a test environment that works great.

Loading a single page with popoulate=* can take 10 seconds, publishing even a simple page with just 2 fields can take nearly 1 minutes. Its nuts. I dont understand what i am missing here.

In the ts the pool is configured with min:4 and max:10.

Network throughput is also very high on the sql instance so network should not be an issue

### Steps to reproduce the behavior

Setting up strapi 5 with postgresql connection

### Expected behavior

Acceptable performance

### Screenshots
![image](https://github.com/user-attachments/assets/2bfb5c41-4b84-4582-999c-bba045380a12)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

When publishing with sql there is at least 100 queries being executed i may be crazy but that does not sound right to me.

I will try to setup a local instance to check if it happens there too

**Comment by eran-colors** [comment]
I tried with local instance and it works. I guess having even the smallest latency really screws up everything, i assume lots of query chaining and perhaps not running asynchronously?

**Comment by derrickmehaffy** [comment]
> I tried with local instance and it works. I guess having even the smallest latency really screws up everything, i assume lots of query chaining and perhaps not running asynchronously? 

Most services using SQL expect extremely small latency, best practice is less than 10ms, anything above that is likely to start causing bottlenecks
