### ISSUE TITLE
[V5] can't use `useContentManagerContext` on custom field

### ISSUE THREAD

**Issue by dzakki** [strapi/strapi#21933]
### Required System information

- Node.js version: v20.11.1
- NPM version:  10.2.4
- Strapi version: 5.1.0
- Database: mysql
- Operating system: Mac OS
- Is your project Javascript or Typescript:  Typescript

### Describe the bug
 i was using  useContentManagerContext from `helper-plugin` on Strapi 4 before, and it's working well. but after migrating to v5 from `'@strapi/strapi/admin'` it doesn't work well. it returned an error: `useDocumentLayout` must be used within StrapiApp``.

this error only appear when running in the prod mode (npm run build & npm run start) 

### Steps to reproduce the behavior

1. create a custom field
2. import useContentManagerContext
3. build the strapi `npm run build`
4. run the strapi `npm run start`

### Expected behavior

it's should be working well without error

### Screenshots

<img width="513" alt="Screenshot 2024-10-22 at 12 09 10" src="https://github.com/user-attachments/assets/045aaafb-6598-47a5-b8e2-0e32dcc7826f">

### Code snippets

```
import {
  unstable_useContentManagerContext as useContentManagerContext,
} from '@strapi/strapi/admin';

const customField = () => {
  const ContentData = useContentManagerContext()
  ....
}
```

**Comment by michalkos** [comment]
@dzakki why is this closed? it's still an issue with 5.3.0

**Comment by dzakki** [comment]
Hi @michalkos , are you using the `useContentManagerContext` on your custom field?

**Comment by michalkos** [comment]
> Hi @michalkos , are you using the `useContentManagerContext` on your custom field?

yes

**Comment by michalkos** [comment]
Interesting. I tried to just add workspace and everything else as it was before it worked as well. Thanks!

**Comment by dzakki** [comment]
> Interesting. I tried to just add workspace and keep everything else as it was before it worked as well. Thanks!

Great! Just fyi, if you do rebuild again and got error, perhaps you need to repeat the solutions. Mostly what I did is not commit the workspaces after build.
