### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')     at @strapi/plugin-users-permissions/server/services/users-permissions.js:115:39

### ISSUE THREAD

**Issue by khuongtp** [strapi/strapi#21942]
### Required System information

- Node.js version: 20.16.0
- NPM version: 10.8.1
- Strapi version: 4.25.13
- Database: PostgreSQL
- Operating system:macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When attempting to edit a role in the Strapi admin panel, the following error occurs:

`TypeError: Cannot read properties of undefined (reading 'type')`  
At: `@strapi/plugin-users-permissions/server/services/users-permissions.js:115:39`

### Steps to reproduce the behavior

1. Go to 'Roles & Permissions' in the Strapi admin panel.
2. Click on a role to edit.
3. The error is displayed, still can edit the role tho, after a bit the table appears with warning internal server error.

### Expected behavior

The table appears without any error

**Comment by zirho** [comment]
does not seem to fix my issue

if I print out route.info in the code

I changed the code to see why `type` is missing like this

```
      }).filter((route) => {
        console.log('route.info', route.info);
        return route.info.type === 'content-api';
      });

```

and I get like this. 


```

route.info { apiName: 'campaign', type: 'content-api' }
route.info undefined
```

just FYI. 
I am digging in.

**Comment by zirho** [comment]
for me, some of route.info is `undefined` 
those content uid are not being created when I create a new content type either.
I don't see the new uid either in `up_permissions` nor `admin_permissions` either.

I think there's something wrong with my setup and I don't think I can find the reason for now. 
I will come back when I find the reasons later. 

Thank you!

**Comment by thomcrielaard** [comment]
In my experience this happened when one of my single types was unsynct with my database. I fixed it by removing the single type and recreating it. An easy way to find which single (or collection) type is causing the issue, is by checking which one is missing in "roles". That one is most likely causing the issue

**Comment by khuongtp** [comment]
Hi @thomcrielaard , did you mean remove the type or just the record, and will the data on production be affected if I delete the type?

**Comment by zirho** [comment]
Mine was resolved.
My issue was we made some changes in `routes.ts` files and there was no endpoint available. 
once, we revert it back, the issue was gone.

Just FYI.

**Comment by khuongtp** [comment]
Thanks @zirho! It is actually my case, I export default {} in one of my route.ts, I changed it to export default { routes: [] } now it's good
