### ISSUE TITLE
I'm confused on the bug I encountered

### ISSUE THREAD

**Issue by Yennego** [strapi/strapi#21949]
```
TypeError: Failed to fetch dynamically imported module: https://1337-idx-teachersfarm-1727342101702.cluster-blu4edcrfnajktuztkjzgyxzek.cloudworkstations.dev/node_modules/.strapi/vite/deps/Layout-D6aFOKIt-SNA55GNY.js?v=9f71bcd1
```
      
<img width="344" alt="Screenshot 2024-10-23 101309" src="https://github.com/user-attachments/assets/9cd422bd-1d46-42ce-8bfb-f3ce0b6ce5dd">

**Comment by kasonde** [comment]
Hello, please follow the issue template.

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.
