### ISSUE TITLE
cannot build plugins/@strapi-plugin-i18n in strapi 5.1.0

### ISSUE THREAD

**Issue by jihadkamil** [strapi/strapi#21968]
### Required System information

- Node.js version: v20.18.0
- NPM version: 10.9.0
- Strapi version: 5.1.0
- Database: postgres
- Operating system: macos
- Is your project Javascript or Typescript: Javascript

### Steps to reproduce the behavior

1. package.json  

  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^4.0.8",
    "@strapi/plugin-cloud": "5.1.0",
    "@strapi/plugin-graphql": "^5.1.0",
    "@strapi/plugin-i18n": "^4.25.13",
    "@strapi/plugin-users-permissions": "5.1.0",
    "@strapi/strapi": "5.1.0",
    "better-sqlite3": "11.3.0",
    "pg": "^8.13.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "strapi-plugin-sso": "^1.0.0",
    "styled-components": "^6.0.0"
  },

2. npm install 
3. npm run build

 [vite]: Rollup failed to resolve import "@strapi/design-system/v2" from                                                                                                   ││   "/Users/jhdkml/Documents/xapiens/antam/antam-backend/node_modules/@strapi/helper-plugin/dist/index.mjs".                                                                  ││   This is most likely unintended because it can break your application at runtime.                                                                                          ││   If you do want to externalize this module explicitly add it to                                                                                                            ││   `build.rollupOptions.external`     

### Expected behavior

can run these 2 commands normally
>npm run build 
>npm run develop 

### Screenshots

![image](https://github.com/user-attachments/assets/24922a21-2bc6-4982-8ccd-2ca8180e91ed)

### Code snippets

-

### Additional context

-

**Comment by derrickmehaffy** [comment]
the i18n plugin no longer exists in Strapi 5, it was merged into the core

**Comment by jihadkamil** [comment]
thank you @derrickmehaffy
