### ISSUE TITLE
"Powered by version" should link to changelog

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#2197]
**What is the expected behavior?**

Hey there!

Right now, the link in the bottom left corner goes to `strapi.io`

![image](https://user-images.githubusercontent.com/2950505/47501906-dc5ac480-d866-11e8-8453-ba4d3f517f70.png)

I think it would make sense to have this link to the changelog.
Either overall or specific: https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.14.3

**Comment by derrickmehaffy** [comment]
Agreed that is a solid idea

**Comment by soupette** [comment]
Agreed!
