### ISSUE TITLE
webhook URLs are limited to public URLs (when not sending to the root path)

### ISSUE THREAD

**Issue by cdreier** [strapi/strapi#21981]
### Required System information

Node.js version: v20.12.0
NPM version: 10.5.0
Strapi version: 5.1.0
Database: sqlite
Is your project Javascript or Typescript: typescript

### Describe the bug

we are using strapi in a docker environment, and when trying to setup a webhook to a local service, we see an error that webhook urls needs to be public

![image](https://github.com/user-attachments/assets/aae2acab-d567-4acd-8bbb-34fe86fd2205)

even if i do not understand why this should be limited, when dropping the path and send the webhook to the root url, it is working. 

### Expected behavior

all urls should be accepted, even local dns names - if there are valid reasons to not accept all urls, strapi should handle all urls consistently and also check webhook urls without a path. 

as not exposing the webhook reciever is much more secure than adding a token to a public url, this inconsitent limitation should be removed?

**Comment by cdreier** [comment]
looks like strapi is doing an actual online check - when using my-service.local without `dns_search` or `hostname` options, this is working - when setting the options, doing the same, strapi blocks updates and creations

**Comment by Marc-Roig** [comment]
Hello!
While unfortunate, this change was implememnted to prevent a security fix.
This has been discussed in https://github.com/strapi/strapi/issues/21981, we will work on a fix and there is a workaround in that thread 🙏

**Comment by cdreier** [comment]
@Marc-Roig thanks for your response! you linked this issue - can you point me to the thread with a workaround?

**Comment by Maus3rSR** [comment]
Hello, I'm facing the same issue about this. How can we do as workaround?
I see the issue was marked as "Done", but I don't find any information about this.

@Marc-Roig

Thank you very much.

🙏

**Comment by Maus3rSR** [comment]
I maybe find another issue that is telling to run instance in Dev mode

#22177
