### ISSUE TITLE
i18n support for user register and login

### ISSUE THREAD

**Issue by ZhengAudrey** [strapi/strapi#21997]
## Bug report
Two potential issues:

1) Strapi always returns default language even with specifying locale in query string or body request for built-in functionality
    e.g.   for user login, if there is some error happened in the request to /api/auth/local?locale=fr , like password not correct,
    the returned error message is English, instead of French.  I also try put locale inside request body, but still not working.

2) Is there built-in method to get current request locale? Although, I can get it from request on my own, but just check if there is a more elegant way. 

* I have added more locales in admin setting page to enable internationalization.

### Required System information

- Node.js version: 20.17.0
- NPM version: 10.8.2
- Strapi version: v5.0.4
- Database: Mysql
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

**Comment by JellieBeanz** [comment]
Having the same issues, we will now potentially need to handle this on the frontend in a hacky way. what would be helpful at least is to add something into the details value of the error object to make it easier to deal with the errors 
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ValidationError",
        "message": "Invalid identifier or password",
        "details": {}
    }
}
