### ISSUE TITLE
Strapi v4: Node 22 Support

### ISSUE THREAD

**Issue by broksonic21** [strapi/strapi#22016]
### Required System information

- Node.js version: 22.11.0
- NPM version: 10.9.0
- Strapi version: 4.25.14

### Describe the bug

Node 22 went LTS today, but STRAPI  v4 requires 20 only in the package.json, so you get this warning/error

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@strapi/types@4.25.14',
npm warn EBADENGINE   required: { node: '>=18.0.0 <=20.x.x', npm: '>=6.0.0' },
npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
npm warn EBADENGINE }
```

We can't upgrade to strapi v5 yet until some plugins upgrade, so can v4 be updated to support 22 so it can stay on supported versions? Thanks!

### Steps to reproduce the behavior

1. Update to Node 22 (or LTS)
2. run `npm install`
3. see warning (or error if in engine-strict mode)

### Expected behavior

Support latest Node LTS

### Additional Info

Node LTS announcement: [https://nodejs.org/en/blog/release/v22.11.0](https://nodejs.org/en/blog/release/v22.11.0)

**Comment by teddybee** [comment]
It is also an issue with V5
```
error @strapi/pack-up@5.0.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "22.11.0"
```

**Comment by derrickmehaffy** [comment]
We will be adding node 22 support once we get the chance, we have already started on it but typically we do lag a few months behind the current LTS while we switch all of our tests over.

Thanks,
