### ISSUE TITLE
Enum difference v4/v5 - "Choose here" as null value

### ISSUE THREAD

**Issue by alex-strapi** [strapi/strapi#22026]
### Required System information

- Node.js version: 20
- Yarn version: 4.3.1
- Strapi version: 5.0.6 - 5.1.1
- Database: N/A
- Operating system: Mac
- Is your project Javascript or Typescript: N/A

### Describe the bug

In Strapi v4 a user could create an enum - a content editor could select values but could also select "Choose here" as a an empty string value.

![image](https://github.com/user-attachments/assets/7646f8ec-b9b7-43c2-a2ea-97fb5caeaca1)

In Strapi v5 a user can create an enum - a content editor cannot select anything other than a value, is this expected? 
Should users have to create an enum with their own empty string value option?

![image](https://github.com/user-attachments/assets/9059722e-ef74-422b-8d3c-1df056996c72)

### Steps to reproduce the behaviour

1. Create an enum on Strapi v4 - check content editor experience (choose here option exists)
2. Create an enum on Strapi v5 - check content editor experience (no choose here option)

### Expected behaviour

If we're basing expected behaviour on what v4 had, we should have a 'Choose here' option. If it's expected in v5 that a empty string value option needs to be added by the user we should update the documentation to reflect this. 

https://docs.strapi.io/user-docs/content-type-builder/configuring-fields-content-type#-enumeration

Edit: Changed null to empty string

**Comment by alex-strapi** [comment]
> just an annotation, in v4 the value passed when we selected the label "Choose here" was an empty string and not a null value, is it ok for you replicate the old behaviour?

Updated the issue to reflect this.

**Comment by simotae14** [comment]
I am gonna close the issue because it is fixed with this PR https://github.com/strapi/strapi/pull/22139 thanks
