### ISSUE TITLE
Date Field Changing values according to Locale while editing on CMS

### ISSUE THREAD

**Issue by sulavsssmc** [strapi/strapi#22023]
- Node.js version: 20.18.0
- NPM version: 10.8.2
- Strapi version: 5.1.0
- Database: postgresql
- Operating system: Mac os
- Is your project Javascript or Typescript: Typescript

I'm using the Date field in Strapi CMS using the Calendar Date Picker. The problem is, when the date is saved let's say for example "02/05/1980" is mm/dd/yyyy format, it is showing as a different date as "01/06/1980" to another editor who is from different country with wide time zone gap when editing from the cms. However when i check the postgres database and at the collections table list, the date is correctly shown as "02/05/1980". 

This is a serious problem because the nature of date being captured is a date that should not change based on locale such as "Date of a certain Historic Event" or "Date of Birth". 

Is there any option to prevent the automatic date conversion because it would create a massive confusion when date of birth is showing a day earlier or ahead on cms.

Also how do i change the "MM/DD/YYYY" format to "DD/MM/YYYY" and force it to be the standard for any user who edits the content regardless of where they are from?

**Comment by bolg55** [comment]
Related to EE Internal TID8980


https://github.com/user-attachments/assets/367403d3-6900-46d0-832e-aa3631e8ba7f

**Comment by leosantacruz** [comment]
+1 Same here

- Strapi v5.4.1
- No plugins installed

**Comment by lucasrcorreia23** [comment]
+1 Same here

Strapi v5.4.2
No plugins installed

**Comment by devincrandall** [comment]
+ 1 5.5.0
