### ISSUE TITLE
Plugin Development: CMS components not exported

### ISSUE THREAD

**Issue by brianjd** [strapi/strapi#22044]
CMS Components (ie. HeaderLayout) that were removed from `@strapi/design-system` and into core are not properly exported.  

https://github.com/strapi/design-system/pull/1703#issuecomment-2450710211

**Comment by chohner** [comment]
Note: You can import `Layouts` from `@strapi/strapi/admin` and then reference the nested Components:

```typescript
import { Layouts } from "@strapi/strapi/admin";

const HomePage = () => {
  return (
    <Main>
      <Layouts.Header title="title" />
      <Layouts.Content>Main Content</Layouts.Content>
    </Main>
  );
};
```

**Comment by brianjd** [comment]
@chohner Noted.  I did discover this on my own as well.  Thanks
