### ISSUE TITLE
The icon for "Code block" and "Inline code" are the same in Blocks

### ISSUE THREAD

**Issue by lucasboilly** [strapi/strapi#22058]
### Why should we do it?
Users may confuse the them, but they are very different. One is a block and the other is simply a text modifier. 

![CleanShot 2024-11-04 at 11 54 26@2x](https://github.com/user-attachments/assets/5711d96e-11a5-468b-94c1-ab3471ba772a)

### Solution
We should use the [code-block](https://phosphoricons.com/?q=%22code+block%22&weight=%22fill%22) icon from Phosphor (our new icon library implemented for Strapi 5) to illustrate the "Code block" block. In order to do it, we'll have to add the icon to our design system as explained in [this issue](https://github.com/strapi/design-system/issues/1804) in the [Strapi Design System](https://github.com/strapi/design-system) repository.

![CleanShot 2024-11-04 at 11 56 26@2x](https://github.com/user-attachments/assets/c1b3fd95-c0e2-4162-b1ac-24d453783350)

**Comment by sg1asgard** [comment]
It is fixed with the following PR:
https://github.com/strapi/strapi/pull/22218
