### ISSUE TITLE
'Schema hasn't been registered for model "ModelName".\nUse mongoose.model(name, schema)',

### ISSUE THREAD

**Issue by stiko** [strapi/strapi#2205]
**Informations**
- **Node.js version**: v10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: Mongo
- **Operating system**: Mac

**What is the current behavior?**
When navigating to `Files upload` it gives an error 
```
 message:
   'Schema hasn't been registered for model "ModelName".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' }
```

**Steps to reproduce the problem**
Upload images to content_type then remove the files from uploads folder.

**What is the expected behavior?**
It should load with no errors regardless of missing files.

**Suggested solutions**
So, after lots of digging I looked at the DB and removed all uploaded files. That fixed the issue.

**Comment by lauriejim** [comment]
Hello @stiko Can you precise steps to reproduce please. 
I'm not able to reproduce.

**Comment by stiko** [comment]
@lauriejim I don't seem to able to reproduce. It happened while I was developing and testing.

**Comment by engmagdy87** [comment]
the same error appears to me

**Comment by painty** [comment]
I met the same error but figured it out :
In my case, I have one uploaded file `related` to a deleted model.
After empty the `related` array of this file, the error is gone.
PS: I used the MongoDB Compass Comminity to do this empty operation.
![tim 20190201181036](https://user-images.githubusercontent.com/5387771/52116727-dd14ab00-264c-11e9-9ad0-b32eb8e882c9.png)

**Comment by marcoleong** [comment]
Same issue happened to me, but for different reason. I forgot to make all the related models using the same db connection.
