### ISSUE TITLE
Strapi v5. When adding icon -> svg blue background is turned on

### ISSUE THREAD

**Issue by NeilRiver** [strapi/strapi#22052]
5.2.0 
I just added an icon and it shows up as a blue circle
![image](https://github.com/user-attachments/assets/f8c5408f-105e-4500-a1aa-3b7ed0d28cd0)

**Comment by BalramMardi** [comment]
What are the step to reproduce it ?

**Comment by NeilRiver** [comment]
![fddpmtc35rqu60pvhcg2cnnw8ua1lc5v](https://github.com/user-attachments/assets/0de9ed96-6e96-431a-ad3f-a72e59276ba5)

here is svg. just create media type and upload svg to it

**Comment by mukulpadwal** [comment]
@NeilRiver, I investigated this issue and found that it specifically affects SVG files. The `Avatar` component, which is used from the `strapi/design-system` repository, isn’t processing SVGs correctly. As a result, when the image fails to load, it defaults to a solid color fallback.

To resolve this, the `Avatar` component will need adjustments to properly support SVG rendering. I may be mistaken, but this is what I understood after reviewing the codebase. I’ll continue looking into it and see what changes can be made to address this.

Hope this helps clarify the issue!
