### ISSUE TITLE
Configuring createCoreRouter disables relations on request

### ISSUE THREAD

**Issue by JK-Effects** [strapi/strapi#22061]
## Bug report
If the `createCoreRouter` function is configured to no auth needed, there is no transfer of ‘Relation’ fields.

### Required System information
- Node.js version: 20.11.1
- NPM version: 10.8.2
- Strapi version: 5.1.1
- Database: mysql
- Operating system: win32-x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug
I use ‘Relation’ fields to set references to instances of pages. To avoid having to use API keys or set the public role, I have set every `createCoreRouter` function for the auth functions to false. This means that page is not passed as part of the result.
As soon as the config object is removed and the public role is configured accordingly, the relation page is displayed again.
The fields are all populated by a middleware.

### Steps to reproduce the behavior
1. Create a single type using a relation and configure the `createCoreRouter` so that it does not use authentication for requests.
2. Request the type and check if the relation is passed.

### Expected behavior
Passing the relation field no matter the config inside the `createCoreRouter` Function.

### Screenshots
![image](https://github.com/user-attachments/assets/68e1db8f-5e3a-404f-9d0c-8b65a4ed282a)

### Code snippets
Does not pass relation:
```
export default factories.createCoreRouter('api::global.global', {
  config: {
    find: {
      auth: false,
    },
  }
});
```

Does pass relation:
```
export default factories.createCoreRouter('api::global.global');
```

**Comment by derrickmehaffy** [comment]
If auth is false we cannot check the required permissions to populate (it doesn't even call the permissions code to check) so it won't be possible to populate.

If you need to populate you should not use the auth: false but instead should set the proper public role permissions.

We don't currently plan on changing this logic
