### ISSUE TITLE
@strapi/plugin-i18n v4.25.15 not tagged as latest on nmpjs

### ISSUE THREAD

**Issue by 20x-dz** [strapi/strapi#22068]
This is basically a copy of #21601, but for https://github.com/strapi/strapi/releases/tag/v4.25.15 (released on October 30).

![image](https://github.com/user-attachments/assets/d55aebad-df03-4548-b9c1-292609e0ff7a)

Is there a tagging issue in the pipeline or something? 😅

**Comment by derrickmehaffy** [comment]
This is intended as we cannot set all of the packages as latest on NPM due to the release of Strapi 5 so for all Strapi 4 packages they are tagged with the "legacy" tag.
