### ISSUE TITLE
strapi start 报错

### ISSUE THREAD

**Issue by xiehai001** [strapi/strapi#2206]
![image](https://user-images.githubusercontent.com/24218743/47540863-96a30800-d909-11e8-900f-9d4838e84a62.png)

**Comment by derrickmehaffy** [comment]
Please follow the bug report format, failure to do so will result in your issue being closed until the issue is updated.

**Comment by lauriejim** [comment]
Hello @xiehai001 , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.
