### ISSUE TITLE
Users permissions creation is very bad

### ISSUE THREAD

**Issue by vitalijalbu** [strapi/strapi#22066]
- at least a redirect after creation?
- why it says username already taken? even if i want to edit a filed??? is not more creation, it's update....

https://github.com/user-attachments/assets/4a3fedbf-6b06-4c74-995c-63b4b597f74a

**Comment by amina-sab** [comment]
Hello,
I'm Sabrina Student at Paris saclay university. I would like to contribute in your project, so i'm looking ti find opned and non assinged issues, and i found this one interesting. So could you please tell me if I can this take this issue? and if it s possible to have more information about it.
Thanks,
Sabrina
