### ISSUE TITLE
Controllers not running when posting via content-manager

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#2207]
Strapi newbbie here. Are controllers supposed to be run when:

1. using the API (via POST)
2. using the content-manager UI

2 is no happening at all.

Maybe my understanding of controllers is incorrect?

**Comment by lauriejim** [comment]
API and content manager use differents controller.
API use generated controllers in `api` folder.
Content manager use controllers inside the plugin folder.

**Comment by jacargentina** [comment]
@lauriejim where do I put this logic ( ONE central place ): for a given created API model
1. Get the current authenticated user
2. Assign the user ID to a field on the model

Thanks

**Comment by lauriejim** [comment]
In the Model.js file of your API models folder (before create function)

**Comment by jacargentina** [comment]
So... How do I get "the current user" there? AFAIK there is no "ctx" in there (it is available on controllers)

**Comment by lauriejim** [comment]
To do that you have to update controllers (API and Content-Manager), it's not possible to get the context in lifecycle of models

**Comment by jacargentina** [comment]
So, it is not possible what i've asked first (the part where i put _ONE central place).

Following the reasoning, i think content-manager controllers could call the API controllers. If you agree, i could try to make a PR to implement it.

I think it _is a must_: to have a central place to make centralized logic for the models. Dont you?
