### ISSUE TITLE
Is correct that the custom endpoint generated is under node_modules folder and not inside api folder ?

### ISSUE THREAD

**Issue by vitalijalbu** [strapi/strapi#22077]
### Required System information

- Node.js version: 22
- NPM version: 10
- Strapi version: 5.2.0
- Database: pg
- Operating system: mac
- Is your project Javascript or Typescript: JS

### Describe the bug

Basically when I `run npx strapi generate` it shows me correctly what i would like to generate, that's correct... But the geenrated **api** is under **node_modules** folder

### Steps to reproduce the behavior

1. Install strapi with JS
2. Run nxpm strapi generate
3. Choose api
4. Give a name (summary in my case)
5. Folder summary is not under src/api/ folder but it's in node_modules (see screenshot)
6. If want to see the folder path, just retry to create again the api with same name, it will tell you already exists

### Expected behavior

Api should be in **src/api/**

### Screenshots

<img width="793" alt="Screenshot 2024-11-06 alle 09 17 13" src="https://github.com/user-attachments/assets/b087d700-b93a-4e84-a927-8a1a085e6e86">

### Code snippets

No code

### Additional context

Seems everything clear

**Comment by gabrielrra** [comment]
This is also happening with me on Strapi 5.2.0

**Comment by derrickmehaffy** [comment]
You shouldn't use NPX for this the local script to properly determine the root path:

- `npm run strapi generate`
- `yarn strapi generate`

Closing as using NPX for this isn't supported.

**Comment by gabrielrra** [comment]
This is also happening using yarn

**Comment by vitali-bc** [comment]
> You shouldn't use NPX for this the local script to properly determine the root path:
> 
> * `npm run strapi generate`
> * `yarn strapi generate`
> 
> Closing as using NPX for this isn't supported.

then update strapi docs please
