### ISSUE TITLE
Translation keys missing in JA language

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#2208]
This is a list of missing translation keys. Feel free to submit a PR to help us.

📦 strapi-admin - [/packages/strapi-admin/admin/src/translations/ja.json](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/translations/ja.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|app.utils.delete | Delete|

📦 strapi-plugin-content-manager - [/packages/strapi-plugin-content-manager/admin/src/translations/ja.json](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/translations/ja.json)

| Translation key | English default value |
|-----------------|:---------------------:|
|components.FiltersPickWrapper.hide | Hide|

**Comment by feysalikbal** [comment]
Hi,
I am working on it :)

**Comment by feysalikbal** [comment]
#2209

**Comment by feysalikbal** [comment]
https://github.com/strapi/strapi/pull/2209
