### ISSUE TITLE
[ BUG ] Not Able To Add Component Into Injection Zone In Plugins Bootstrap Function

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/strapi#22099]
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.2.0
- Node/Yarn Version: npm/10.8.1 node/v20.16.0 darwin arm64 workspaces/false
- Edition: Community
- Database: sqlite

### Describe the bug

When following the documentation example to add a component into dynamic zone via this code snippet.

```
export default {
  bootstrap(app) {
    app.getPlugin('content-manager').injectComponent()('editView', 'informations', {
      name: 'my-plugin-my-compo',
      Component: () => 'my-compo',
    });
  }
}
```

When you pass a component, VS code will complain that you are in an `index.ts`  file and not `index.tsx` 

### Steps to reproduce the behavior

Here is quick video covering the steps and how I was able to fix it.  

https://github.com/user-attachments/assets/58a90d0f-3e51-4321-93f1-7849c711b7f0

I also in the video had a follow up question.  

Why the following style of import also did not work.

```
  bootstrap(app: any) {
    app.getPlugin('content-manager').injectComponent('editView', 'right-links', {
      name: "content-embeddings",
      Component: async () => {
        const { HelloWorld } = await import('./components/HelloWorld');
        return HelloWorld;
      },
    })
  },
  ```
  
  It is the simillar way we are importing App component in the register function.

```
  Component: async () => {
        const { App } = await import('./pages/App');
        return App;
      },

```
### Expected behavior

Should inject the component .

**Comment by jhoward1994** [comment]
And the reason this approach wont work is due to the internals of the `injectComponent` function
```
const { HelloWorld } = await import('./components/HelloWorld');
```

https://github.com/strapi/strapi/blob/af7e4e2471a04cc7f17b8ed3474530810efc02bc/packages/core/admin/admin/src/core/apis/Plugin.ts#L40-L50

We would need to change it to do something similar to addMenuLink and I think thats a unnecessary complication e.g.
https://github.com/strapi/strapi/blob/af7e4e2471a04cc7f17b8ed3474530810efc02bc/packages/core/admin/admin/src/core/apis/router.tsx#L179-L194

Let me know what you think :)

**Comment by PaulBratslavsky** [comment]
@jhoward1994, so this should probably just be an update to the docs instead, using your provided example that you references  here https://github.com/strapi/strapi-plugin-seo/blob/5bbdf02f276aa3e3aa5bd29048ba3267cf1a1dca/admin/src/index.js#L36-L41

**Comment by jhoward1994** [comment]
Yeah I would say here https://docs.strapi.io/dev-docs/plugins/admin-panel-api#injecting-components we should add an example along the lines of:

```
Example: In order to inject a component imported from elsewhere in the informations box of the Edit View of the Content Manager:
my-plugin/admin/src/index.js

import HelloWorld from './components/HelloWorld'

export default {
  bootstrap(app) {
    app.getPlugin('content-manager').injectComponent()('editView', 'informations', {
      name: 'my-plugin-my-compo',
      Component: HelloWorld
    });
  }
}

NOTE: in this case you will need to change the file extension to jsx/tsx
export default {
  bootstrap(app) {
    app.getPlugin('content-manager').injectComponent()('editView', 'informations', {
      name: 'my-plugin-my-compo',
      Component: () => {
        // Introducing side effects or props to the component
      	return <HelloWorld />
  	  }
    });
  }
}

```

**Comment by PaulBratslavsky** [comment]
@pwizla, I wanted to pull you into this conversation.  But I will make a PR for the docs to clarify this point.

**Comment by akshay50001132** [comment]
is this really fixed, its still not working for me. And documentation is still not updated.

**Comment by pwizla** [comment]
@akshay50001132 I'll have a look at it early next week
