### ISSUE TITLE
Cleaner fallback for files preview

### ISSUE THREAD

**Issue by lucasboilly** [strapi/strapi#22100]
### Why should we do it?

In the Media Library, the current fallback for files doesn't look great on the cards and even look buggy in the details modal. We should clean it a bit and let users know that it's normal.

![image](https://github.com/user-attachments/assets/fc5704cf-8093-4d0d-9e8a-deaa342b938e)

![image](https://github.com/user-attachments/assets/1a342a00-6384-48a8-aa6d-99d44d7912ab)

### Solution

- Update icon style with a 24px size and use `Neutral500` for the color
- Add the text "No preview available" below the icon
- Add the french version of the text ("Aucun aperçu disponible") in the french translation file
- Center the icon and the text vertically and horizontally in their container
- While keeping them centered, offset down the icon and the text from 8px for visual balance

![CleanShot 2024-11-07 at 15 28 10@2x](https://github.com/user-attachments/assets/4966000c-4bc6-4b73-ba4f-c9b3c2e97791)

![CleanShot 2024-11-07 at 15 28 13@2x](https://github.com/user-attachments/assets/6c162fc7-eb67-4bf9-94c0-3a135a8d0c2f)

**Comment by ar53n** [comment]
I agree with you and i think this component should be reworked. 

#22097

**Comment by markkaylor** [comment]
Closed by: https://github.com/strapi/strapi/pull/22351
