### ISSUE TITLE
Unable to type color value using keyboard

### ISSUE THREAD

**Issue by KamilPieronczyk** [strapi/strapi#22123]
### Required System information

- Node.js version: 20.10.
- NPM version: 9.6.3
- Strapi version: 5.3.0
- Database: Postgres
- Operating system: MacOs 15.0.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

User is not able to change the color unsing a keyabord in the color picker component 

### Steps to reproduce the behavior

1. Go to Content Manager, pick some component which has a color picker component
2. Click on color field
3. Try to edit the color input using keyboard
4. The component doesn't acknowladge these changes

### Expected behavior

The color is being change after user provides a color hex value using keyboad 

### Additional context

PR with a fix: https://github.com/strapi/strapi/pull/22122

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/21838
