### ISSUE TITLE
Strapi 5 content manager creates 2 entries in database

### ISSUE THREAD

**Issue by stewpete** [strapi/strapi#22124]
Strapi v5.3.0
npm 10.8.2 
5.3.0 (node v20.17.0)  
Typestript
MariaDB
Ubuntu 24.04

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Click on 'Create new entry'
3. Fill Form
4. Hit 'Save' and 'Publish'
5. Inspect corresponding table in database
6. See two entries of submitted row/entry

### Expected behavior

Obviously one entry only.

### Screenshot

![image](https://github.com/user-attachments/assets/0a7ad1f4-d9e8-40ca-8ab2-2fa4ad54c7b7)

**Comment by jannescb** [comment]
@stewpete 

First row is the draft version of your entry, second row is the published version.
When publishing, both versions have the same content. 
When saving, only the draft version is being updated.

**Comment by derrickmehaffy** [comment]
This is intended functionality as was mentioned in the previous comment. One is the draft and the other is the published entity.
