### ISSUE TITLE
Strapi CLI `generate` command saving files in `node_modules/strapi/@generators/dist`

### ISSUE THREAD

**Issue by gabrielrra** [strapi/strapi#22127]
### Required System information

- Node.js version: v18.20.4
- NPM version: 10.7.0
- Strapi version: 5.2.0
- Database: mysql
- Operating system: linux-x64 - Ubuntu 24.04.1 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

While running the strapi cli using yarn (`yarn strapi generate`) the files generated end up being stored under `node_modules/strapi/@generators/dist`

### Steps to reproduce the behavior

1. Create a new strapi project using the cli `yarn create strapi`
2. Try to generate a new API endpoint using the CLI `yarn strapi generate` following all the necessary steps
3. It will succeed but the files won't be in `src/api` folder
4. Try to generate the API endpoint again using the same name
5. It will fail and print the location of the files previously generated

### Expected behavior

The files should be generated at the folder `src`

### Screenshots

![image](https://github.com/user-attachments/assets/d2e40b5d-5f26-4d17-8ecb-e76d91b0a9c0)

### Code snippets

_N/A_

### Additional context

Tried the command using `npx`, `npm run` and `yarn`, all yielding the same result

**Comment by gabrielrra** [comment]
Opening this because https://github.com/strapi/strapi/issues/22077 was closed before resolving

**Comment by vitalijalbu** [comment]
npm run strapi generate also doing that, it paklces the folder inside:
`node_modules/@strapi/generators/dist/api/`

**Comment by vitalijalbu** [comment]
> Opening this because #22077 was closed before resolving

yeah, they like to close issues where people have difficulties... ugliest headless cms ever!

**Comment by derrickmehaffy** [comment]
Tested using yarn and npm with the following specs:

```
dmehaffy@dm-desktop-lm:~/Development/test22127$ yarn strapi report --all
yarn run v1.22.22
$ strapi report --all
Launched In: 287 ms
Environment: development
OS: linux-x64
Strapi Version: 5.3.0
Node/Yarn Version: yarn/1.22.22 npm/? node/v20.18.0 linux x64
Edition: Community
Database: sqlite
UUID: 40da9120-329a-4e67-a352-96722e7bf579
Dependencies: {
  "@strapi/plugin-cloud": "5.3.0",
  "@strapi/plugin-users-permissions": "5.3.0",
  "@strapi/strapi": "5.3.0",
  "better-sqlite3": "11.3.0",
  "react": "^18.0.0",
  "react-dom": "^18.0.0",
  "react-router-dom": "^6.0.0",
  "styled-components": "^6.0.0"
}
Dev Dependencies: {}
[2024-11-13 07:54:31.442] info: Shutting down Strapi
[2024-11-13 07:54:31.445] info: Strapi has been shut down
Done in 1.86s.
```

Yarn
![image](https://github.com/user-attachments/assets/362a8bbd-d542-4172-acd1-a631ac05ead7)

NPM
![image](https://github.com/user-attachments/assets/a6cf334d-f572-4792-911a-ea0cb35ad583)

**Comment by gabrielrra** [comment]
A created a new repository which is just a bare `yarn create strapi`: https://github.com/gabrielrra/strapi-generate-test

1. Clone the repository
2. Run `yarn install`
3. Run `yarn strapi generate`, choose "api" and fill the required fields
4. Run `yarn strapi generate` with the same information as the previous step
5. Error shows that the files are being generated on the wrong folder (inside `node_modules`):
![image](https://github.com/user-attachments/assets/bd04970c-78e7-456a-961a-6147f1ae3578)

**Comment by gabrielrra** [comment]
@derrickmehaffy  Did the files end up in the right folder? These success messages don't exactly mean the files were generated on the correct path...

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy  Did the files end up in the right folder? These success messages don't exactly mean the files were generated on the correct path...

Yes they did, I've never seen them not be generated in the correct path like that but typically something like that can only happen if the root directory of the project is incorrect (eg running using NPX or running the command from some nested directory).

I wouldn't close issues without validation unless it doesn't follow the issue template and I did test this in the old issue too (not using NPX, because we have never supported that other than to generate the project itself with create-strapi-app).

As for our documentation on the CLI commands, we dont include the package manager as part of the command and I agree that's confusing. I'll talk to @pwizla about that.

**Comment by derrickmehaffy** [comment]
The question for you all is are you using some kind of special tooling like turbo repo or workspaces or something else that could be causing some kind of conflict?

**Comment by gabrielrra** [comment]
I am using `nvm` to manage node versions, but can't think of anything else that might interfere. I tried on a fresh new repo

**Comment by derrickmehaffy** [comment]
> A created a new repository which is just a bare `yarn create strapi`: https://github.com/gabrielrra/strapi-generate-test
> 
> 1. Clone the repository
> 2. Run `yarn install`
> 3. Run `yarn strapi generate`, choose "api" and fill the required fields
> 4. Run `yarn strapi generate` with the same information as the previous step
> 5. Error shows that the files are being generated on the wrong folder (inside `node_modules`):
> ![image](https://github.com/user-attachments/assets/bd04970c-78e7-456a-961a-6147f1ae3578)
> 

I pulled your code, ran the commands and works exactly as intended so my guess is you have some kind of environmental factor that's at play on your system.

I use Linux Mint 22 (literally just reinstalled my OS over this past weekend and have barely finished setting anything up on it).

**Comment by vitalijalbu** [comment]
I use node v20 & v22 and the same issue happens.

**Comment by gabrielrra** [comment]
I added docker and the exact same thing happened... @derrickmehaffy can you try again with the latest changes from my test repo?

Here's a breakdown of what I did:

```sh
docker build -t strapi-test-generate:latest .
docker run -d --name strapi-test-generate strapi-test-generate:latest

docker exec -it strapi-test-generate sh
yarn strapi generate
# > api
# ? API name > test
# ? Is this API for a plugin? (Y/n) > n
yarn strapi generate
# > api
# ? API name > test
# ? Is this API for a plugin? (Y/n) > n
```

It should error with a message like:

![image](https://github.com/user-attachments/assets/3acd02c9-c326-488d-a2d6-e0226f102be9)

**Comment by gabrielrra** [comment]
@derrickmehaffy I just updated the repo with instructions on README.md

**Comment by pwizla** [comment]
> we dont include the package manager as part of the command and I agree that's confusing. I'll talk to @pwizla about that.

What do you mean exactly, @derrickmehaffy? 🤔
Would you like to have NPM/Yarn tabs everywhere on this page: https://docs.strapi.io/dev-docs/cli

If yes, could someone please create a [documentation issue](https://github.com/strapi/documentation/issues) for it so that we can track the project down? 🙏  

As a reminder, we warn the users at the top of the CLI reference page, though: 
![Screenshot 2024-11-14 at 16 13 05](https://github.com/user-attachments/assets/9f1d61ea-7070-4e78-b14f-c91ab006769e)

**Comment by derrickmehaffy** [comment]
In the code blocks themselves using the tab syntax like we do elsewhere.

**Comment by derrickmehaffy** [comment]
I'm not able to reproduce this myself but my peer @kasonde was able to reproduce it

**Comment by derrickmehaffy** [comment]
I even tested with TS also and can't reproduce: 

![image](https://github.com/user-attachments/assets/ad0cc037-d825-428a-856e-4d9682d0eebb)

**Comment by gabrielrra** [comment]
Did you try the Docker though? @derrickmehaffy

**Comment by derrickmehaffy** [comment]
> Did you try the Docker though? @derrickmehaffy

I don't use docker at all, refuse to install it on my system as I have some security concerns with the docker network code-base but I run on native linux and I don't think the OS should matter here but if anyone has some windows/mac systems to test with it might be worth it to check.

I'm guessing it's something to do with some kind of package cache issue.

**Comment by oakband** [comment]
I've encountered the same issue, and it can be reproduced in both the latest versions 5.4 and 5.11. I'm using JavaScript, and I'm not sure if it's related to my environment, as I'm using Node version 20. Also, in my previous project with version 5.0, the output was correctly generated in the right directory, and I haven't changed the environment.

**Comment by derrickmehaffy** [comment]
Hmmmmm something odd is going on here 🤔

**Comment by phunck2112** [comment]
The same issue happened to me. After you generated it and got this message, are you sure the folder appears in the src/api directory? Have you checked?

> I even tested with TS also and can't reproduce:
> 
> ![image](https://private-user-images.githubusercontent.com/8593673/386337016-ad0cc037-d825-428a-856e-4d9682d0eebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3Mzk3MDMsIm5iZiI6MTczMTczOTQwMywicGF0aCI6Ii84NTkzNjczLzM4NjMzNzAxNi1hZDBjYzAzNy1kODI1LTQyOGEtODU2ZS00ZDk2ODJkMGVlYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMDY0MzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE3NGE2MTU5MDYwOWViOGQ1MGJlZGE3MDdmMDhlZDcyMzllYmQzZmNkNjcwNGFmMGUwZTg2OGU2MGQ5ODc5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oY7hYZuHZnp9sb_twGbpEc03bdfPYIU4j7U41RvGJ4c)

The same issue happened to me. After you generated it and got this message, are you sure the folder appears in the src/api directory? Have you checked?

**Comment by Kathenae** [comment]
I also have the same issue, the command runs successfully without any errors but the generated files are placed in the `node_modules/strapi/@generators/dist/api` directory instead of `./src/api`. I'm relatively new to strapi so not sure if the generated files supposed to be placed in that folder?

**Comment by Kathenae** [comment]
> > I even tested with TS also and can't reproduce:
> > ![image](https://private-user-images.githubusercontent.com/8593673/386337016-ad0cc037-d825-428a-856e-4d9682d0eebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3Mzk3MDMsIm5iZiI6MTczMTczOTQwMywicGF0aCI6Ii84NTkzNjczLzM4NjMzNzAxNi1hZDBjYzAzNy1kODI1LTQyOGEtODU2ZS00ZDk2ODJkMGVlYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTZUMDY0MzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE3NGE2MTU5MDYwOWViOGQ1MGJlZGE3MDdmMDhlZDcyMzllYmQzZmNkNjcwNGFmMGUwZTg2OGU2MGQ5ODc5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.oY7hYZuHZnp9sb_twGbpEc03bdfPYIU4j7U41RvGJ4c)
> 
> The same issue happened to me. After you generated it and got this message, are you sure the folder appears in the src/api directory? Have you checked?
> 
> For anyone experiencing issues, please try using an older version to resolve the problem. I’ve downgraded to version 5.0.6, and everything is working fine now.

Also downgraded to v5.0.6 and the api files are created in the correct directory

**Comment by armespavong** [comment]
Same issue here. At first I can't find where it was located until I ran the same command.
<img width="684" alt="Screenshot 2567-11-21 at 16 20 02" src="https://github.com/user-attachments/assets/05b5da40-980c-4fdd-8f21-6fa6d24747bb">

**Comment by BangHuynh0404** [comment]
I have the same issue too, any fix?

**Comment by 3askaal** [comment]
I also have this issue, I'm running `npm run strapi generate` since I've read installing strapi globally is not recommended, could this have to do with it?

**Comment by vptcnt** [comment]
Same issue...😭

**Comment by dineshvemula** [comment]
Same issue here....

**Comment by nuromirzak** [comment]
Same issue here, I tried using both npx and npm run

**Comment by carzoomotesting** [comment]
I am using, '"@strapi/strapi": "5.5.0",

Same issue. 

```
strapihw1> npm run strapi generate

> strapihw-1@0.1.0 strapi
> strapi generate

? Strapi Generators service - Generate a service for an API
? Service name shopify
? Where do you want to add this service? Add service to new API
✔  ++ \api\shopify\services\shopify.ts
```
and the same thing happens with controllers too.

```
strapihw1>npm run strapi generate

> strapihw-1@0.1.0 strapi
> strapi generate

? Strapi Generators controller - Generate a controller for an API
? Controller name shopify
? Where do you want to add this controller? Add controller to an existing API
? Which API is this for? shopify
✔  ++ \api\shopify\controllers\shopify.ts
```

In both case, files end up getting created under the 

1. strapihw1\node_modules\@strapi\generators\dist\api\shopify\controllers
2. strapihw1\node_modules\@strapi\generators\dist\api\shopify\services

I have not modified anything. It's a straight forward strapi installation with zero changes.

**Comment by harish2704** [comment]
I created a fresh strapi project and I am also facing this issue. 
Node version: v20.11.1
My package.json 
```{
  "name": "my-strapi-project",
  "version": "0.1.0",
  "private": true,
  "description": "A Strapi application",
  "scripts": {
    "build": "strapi build",
    "deploy": "strapi deploy",
    "develop": "strapi develop",
    "start": "strapi start",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-cloud": "5.5.0",
    "@strapi/plugin-documentation": "^5.5.0",
    "@strapi/plugin-users-permissions": "5.5.0",
    "@strapi/strapi": "5.5.0",
    "better-sqlite3": "11.3.0",
    "mysql2": "^3.11.5",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  },
  "engines": {
    "node": ">=18.0.0 <=22.x.x",
    "npm": ">=6.0.0"
  },
  "strapi": {
    "uuid": "92b6320c-8f7e-46be-8d48-b351cf9c1203"
  }
}
```

**Comment by hanpaine** [comment]
Morning folks, thank you for your patience here - we're taking a look this week 🙏
