### ISSUE TITLE
Computed Attributes

### ISSUE THREAD

**Issue by jacobgelman** [strapi/strapi#2215]
**What is the expected behavior?**

I have a basic product model with the following attributes:
- title [string]
- description [text]
- price [decimal]
- stock [int]

When fetching products for use in my frontend, I need to know whether or not the product is in stock without revealing the actual number of items in stock.

Is it currently possible to have a computed attribute: an attribute that is not actually in the model but is computed dynamically in response to an API call?

**Example:**

The following product is in the database:
- title: "T-Shirt"
- description: "A basic T-Shirt."
- price: 9.99
- stock: 23

When fetching this product with the API, the response contains a computed `isInStock` property—a boolean—based off of the number in stock (if stock is 0, the value is false whereas if stock is > 0, the value is true):
```json
[{
    "title": "T-Shirt",
    "description": "A basic T-Shirt.",
    "price": 9.99,
    "isInStock": true
}]
```
<small>Note: I have omitted some properties from this response such as `_id` for brevity.</small>

**Comment by masiya255** [comment]
Does not work when upgrading from version 14.3 (

**Comment by mnlbox** [comment]
I like it :heart: 
It can be a code block and anyone can write simple code snippet there for manage computed fields. :thinking:

**Comment by Aurelsicoko** [comment]
We don't plan to develop it for now... so there is no news or progress about this one. I'm closing the issue but you can still upvote it or comment above to show your interest.
