### ISSUE TITLE
Webhooks do not allow URLs not reachable over the public network

### ISSUE THREAD

**Issue by canta2899** [strapi/strapi#22177]
### Required System information

- Node.js version: 18.20.4
- Strapi version: 5.3.0
- Database: postgres
- Operating system: debian
- Is your project Javascript or Typescript: typescript

### Describe the bug

I'm running strapi in production on a VPS in a Docker container. I'd like to use a webhook to trigger revalidation of my frontend server which is a NextJS app running in another container. Both containers are under a docker network with custom IPs assigned. 

When I try to use the frontend container's IP as the webhook URL (i.e. http://192.168.0.12:3000/api/revalidate), I get an error saying "Url is not supported because it isn't reachable over the public internet" and I'm unable to save. I understand the motivations, but I think this should be allowed so that I don't have to generate unnecessary traffic over the public network and keep the revalidation safe in my VPS network.

I've always been doing revalidation this way, so I guess this is something that was introduced with strapi 5 because it's the first time I'm encountering this issue.

### Steps to reproduce the behavior

1. Go to Settings > Webhooks
2. Create a new Webhook
3. Use a URL which contains an IP from a private range (i.e. 172.16.0.0/12 or 192.168.0.0/16)
4. Observe the inability to save

### Expected behavior

Strapi shouldn't force me to use URLs available over the public network and I should be able to use webhooks for private traffic as well.

### Screenshots

![image](https://github.com/user-attachments/assets/e5fe248e-c880-4c74-a261-bdc3587dfa22)

**Comment by derrickmehaffy** [comment]
This is intentional as locally calling internal networks is a security risk, we patched this in Strapi 4 as part of this vulnerability: https://github.com/strapi/strapi/pull/20487

We have absolutely no plans to revert this change.

**Comment by canta2899** [comment]
Alright, thanks for replying so quickly! I'll read more about the issue mentioned and use public URIs in my future projects 💪

**Comment by bennyhoyer** [comment]
@derrickmehaffy 
Please re-read my recently closed issue. Your condition and test are too strict. 
I have a publicly accessible URL within the webhook. This URL also has an SSL certificate and is **not** an IP address. 
I am not asking to remove the check for a local IP address and port. 
But the used package does not only check if the input is an IP address that matches the IP of the application. 
It also checks if a public URL points to the local IP address. 
It can't be your intention that your security check forces me to not use strapi and my frontend on the same machine.

**Comment by grdddj** [comment]
Just had the same issue - not being able to call any endpoints on the same server, even though it was normally reachable via public domain.

Looked in the strapi code for the webhook validator:

```ts
const webhookValidator = yup.object({
  name: yup.string().required(),
  url: yup.string().matches(urlRegex, "url must be a valid URL").required().test(
    "is-public-url",
    "Url is not supported because it isn't reachable over the public internet",
    async (url) => {
      if (process.env.NODE_ENV !== "production") {
        return true;
      }
      try {
        const parsedUrl = new URL(punycode.toASCII(url));
        const isLocalUrl = await isLocalhostIp(parsedUrl.hostname);
        return !isLocalUrl;
      } catch {
        return false;
      }
    }
  ),
```

See that the check does not run when `process.env.NODE_ENV !== "production"`.

So in the end it was possible to workaround it just by starting with `NODE_ENV=development`

**Comment by davimdantas** [comment]
We are facing the same problem our system is only available through a VPN and it is been caught by the strict validation 

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/0d2004af-2bee-4792-a5c0-ac3e8d6946b9" />

**Comment by yarlson** [comment]
> We are facing the same problem our system is only available through a VPN and it is been caught by the strict validation
> 
> <img alt="Image" width="1101" src="https://private-user-images.githubusercontent.com/38892983/449240187-0d2004af-2bee-4792-a5c0-ac3e8d6946b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE0NTEzMzIsIm5iZiI6MTc1MTQ1MTAzMiwicGF0aCI6Ii8zODg5Mjk4My80NDkyNDAxODctMGQyMDA0YWYtMmJlZS00NzkyLWE1YzAtYWMzZThkNjk0NmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzAyVDEwMTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTQxNDU0ZTdkNWEyZjNjOTQxN2U1YTFhMTRjMWIwNjI0ZjNkZDE1OGYyZmQyNDNiYzExZjM0YmJhNDZiNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jkoc-A_z0L4uwIJsu7wZRBzVkhMTIfATaDCNm-iVjyY">

We are facing the same. I recon it's not "strict validation", it's literally a bug.

**Comment by yunusyuksel** [comment]
any fix to the issue ?

**Comment by xTrimy** [comment]
Same issue here with a public URL

<img width="960" height="331" alt="Image" src="https://github.com/user-attachments/assets/ac848550-c7e1-4bda-934c-fa304e2e90a0" />

**Comment by edgrejo** [comment]
Same issue here since the public URL resolves inside the company network to an internal IP I can't use webhooks to invalidate caches even if I try and use an external FQDN.

**Comment by pademirov** [comment]
Does someone find the correct way to fix it? It seems to me that run a production app in dev mode is not the best idea.

**Comment by roserens** [comment]
> Does someone find the correct way to fix it? It seems to me that run a production app in dev mode is not the best idea.

I fixed it by entering a public URL in the UI and then changing the address in the database.

Here the SQL code I use for updating SQLite Strapi instance:

```sql
SELECT * from strapi_webhooks;
UPDATE strapi_webhooks SET url = 'http://localhost:5000/v1/strapi/webhook' WHERE name = 'my internal server with webhook';
SELECT * from strapi_webhooks;
```

You need to restart strapi after that.

```bash
systemctl restart strapi
```

Hope this helps.

**Comment by varloc2000** [comment]
Not sure what security risk was mitigated by such validation mentioned here. 
I'm glad trick with updating DB webhook value and restarting srapi works. 

Services communicating in same internal network and being exposed to public through some proxy like traefik is pretty common thing and in this case http webhook seems the only way.

**Comment by jakub-gawryl** [comment]
> [@derrickmehaffy](https://github.com/derrickmehaffy) Please re-read my recently closed issue. Your condition and test are too strict. I have a publicly accessible URL within the webhook. This URL also has an SSL certificate and is **not** an IP address. I am not asking to remove the check for a local IP address and port. But the used package does not only check if the input is an IP address that matches the IP of the application. It also checks if a public URL points to the local IP address. It can't be your intention that your security check forces me to not use strapi and my frontend on the same machine.

@derrickmehaffy would you mind to address this please? I ran into the exact same problem. I have two services on the same server, but I expose a webhook URL publicly (token-protected). I try to call it, but it doesn't work.

**Comment by renannprado** [comment]
@derrickmehaffy So if I understood correctly, the security issue was about preventing the webhook mechanism to be used to access anything in localhost (i.e. strapi itself), right?

But you're also preventing access to things like `http://http-api.my-namespace.svc.cluster.local/api/v1/strapi/webhook` (i.e. kubernetes cluster-internal hostname). So if I have a cluster-internal webhook receiver I would be forced to expose the receiver to the public internet without need. This part of the fix makes no sense whatsoever.

Nobody is asking for the fix to be reverted, but perhaps either the check could be relaxed somehow (to make sure container/machine local IP is not used) or maybe create an extra flag like `ALLOW_UNSAFE_WEBHOOK_URL` or something like this.

The current state of things here is imposing an architecture restriction on everyone which **actually** forces people to choose a **less safe** architecture by exposing things that don't necessarily need to be exposed otherwise.
