### ISSUE TITLE
Excel files (xlsx) in Media Library - wrong MIME type

### ISSUE THREAD

**Issue by pawelhoros** [strapi/strapi#22203]
### Required System information

- Node.js version: 20.18.0
- NPM version: 10.9.0
- Strapi version: 5.4.0
- Database: PostgreSQL 12
- Operating system: Linux / Ubuntu 24 / docker from strapi:latest
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

Excel file content type is broken in 5.4.0. It worked well in 4.x.x. 

### Steps to reproduce the behavior

1. Go to Media Library.
2. Upload test.xlsx file to Media Library.
3. Get link to that file and try it in browser.
4. File is treated as text and displays garbage.

### Expected behavior

Browser should offer to display correct Excel file or offer to download and save it.

**Comment by derrickmehaffy** [comment]
This is unrelated to Strapi itself I believe, we have nothing specific that enables or disables how a file is read by the browser.

**Comment by pawelhoros** [comment]
It's related. Response content type is sent from server in response headers.

It's behaves correct with for example pdfs or zip files.
If I paste (direct) link to pdf file from media library, response header contains correct content type: application/pdf. 
Zip file contains correct content type: application/zip.

But Excel file content type is blank. What's expected: Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

It's easy to reproduce, just use network tab in dev tools.
