### ISSUE TITLE
Relation field does not keep order in published version

### ISSUE THREAD

**Issue by marciusl** [strapi/strapi#22228]
## Bug report

- Node.js version: 18.18
- NPM version: 10.8.2
- Strapi version: 5.3.0
- Database: mysql
- Operating system: Ubuntu
- Is your project Javascript or Typescript: TS

### Describe the bug

Field which is Relation and you select items in what order you want and it keeps it when returning from API. But in published version it is returning sorted Relation field items by "id".

### Steps to reproduce the behavior

1. Go to draft version, select in relation field items for example: item A with id 3, item B with id 10, and item C with id 1
2. Save it and publish it
3. In draft version it returns in same order you saved items: A (id 3), B (id 10), C (id 1)
4. In published it returns: C (id 1), A (id 3), B (id 10)

### Expected behavior

In published version it should return: A (id 3), B (id 10), C (id 1)

**Comment by simon-roland** [comment]
I can confirm that I am also seeing this bug.

When I inspect the table, it seems that the order column is null for the published version.

![{A17D318F-4C17-4F94-A428-B722C3F8A37F}](https://github.com/user-attachments/assets/35e7ac0c-8d04-491e-9949-9dc9d2969d1c)

**Comment by dimitrisganotis** [comment]
This issue is a duplicate of [#22170](https://github.com/strapi/strapi/issues/22170). Unfortunately, it hasn’t been resolved yet, and given its “severity: medium” label, I don't think it's going to be addressed anytime soon. It is clear that it directly impacts production environments. Unfortunately it’s becoming increasingly challenging to rely on Strapi for production environments on v5.

**Comment by alex-strapi** [comment]
Bump for this issue - impacting enterprise customers migration to v5

**Comment by derrickmehaffy** [comment]
This issue is in relation to 3 issues total impacting components, relations, and dynamic zones:

- Components: https://github.com/strapi/strapi/issues/22250
- Relations: https://github.com/strapi/strapi/issues/22228
- Dynamic Zones: https://github.com/strapi/strapi/issues/22170

**Comment by hanpaine** [comment]
Thanks for your additional comments and patience folks, we're taking a look now 🙏

**Comment by derrickmehaffy** [comment]
We have an experimental version for users to test with: `0.0.0-experimental.7bc5339b0393e53f9f568301594621e7fb466e2f`

Please don't use this in production, if you aren't sure how to use the experimental you just change all of the `@strapi/*` packages in your package.json to use this (except the SEO plugin), reinstall node_modules, and re-run the application.

If all goes well, we plan to merge this into tomorrow's release.

**Comment by hanpaine** [comment]
Fixed in 5.5.1, released today

**Comment by ZahraaMahmood** [comment]
@hanpaine I'm facing something similar in version 5.18.1 production, I have dynamic zone that has multiple component, one of the component has a relation many to many with another collection field called containers so when I'm in the dashboard, dynamic zone, updating my component relation with containers, changing the order adding or deleting the published version doesn't take the last updated draft even when I published the order of the elements is wrong and the deleted containers are still in the publsihed version, the one I newly added isn't being added
