### ISSUE TITLE
Dropdown issue in relationship UI 

### ISSUE THREAD

**Issue by semilmore** [strapi/strapi#22221]
## Bug report

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

When attempting to create a new relation field in the Strapi Admin Panel, the dropdown menu for selecting relationship types is partially obscured or difficult to see due to poor contrast/visibility in the dark theme. This causes users to waste time by having to delete and recreate collections when they cannot properly see or select their desired relationship type.
### Steps to reproduce the behavior

1. Navigate to Content-Type Builder
2. Select a collection type
3.Click "Add new Relation field"
4.Try to view and select relationship type from the dropdown menu
5.Notice that the relationship options are difficult to see/select

### Expected behavior

- Relationship type options are difficult to see due to poor contrast
- Users may miss available options due to visibility issues
- Interface usability is compromised, leading to workflow inefficiencies.
- Only first 4 options are visible. For other options there should be a scrollbar.

![stripe issue](https://github.com/user-attachments/assets/0b6bd674-935b-4590-a9e5-d6f210f79739)

**Comment by derrickmehaffy** [comment]
Can you please fill out the related version information

**Comment by yasir7942** [comment]
same issue i am facing Strapi Version  5.15.1 , Node Version 20.14.0
in Relationshup UI dropdown collections are missing show just first 4 connections. 

![Image](https://github.com/user-attachments/assets/c518bf3b-75d0-4db3-943b-88777646c8f7)
