### ISSUE TITLE
There is no way to retrieve all published strapi.documents

### ISSUE THREAD

**Issue by solovieved** [strapi/strapi#22225]
### Required System information

- Node.js 20.5.0:
- NPM 10.9.0:
- Strapi version: 5.4.0
- Database: mysql 8.3
- Operating system: Ubuntu 20.04
- Typescript:

### Describe the bug

When trying to retrieve one or more records via e.g. stripe.documents(‘api::name.name’).findMany(). I get only unpublished records. Attempts to add a not null condition do not help.

### Expected behavior

The expectation was that I would get only published records or possibly all of them. But it's not clear why the decision to give unpublished records is chosen. Below on the screens I will show you why this happens, but I didn't find anything about this behaviour in the documentation.

<img width="896" alt="image" src="https://github.com/user-attachments/assets/923aa139-090b-4d68-b5d9-26a0f3141912">
On the screenshot you can see that there is no condition with the field publishedAt.But if you look at the debug mode of the query, you can see the condition.
<img width="856" alt="image" src="https://github.com/user-attachments/assets/be009f68-87d8-4d8f-b158-439e8e85c593">

You can try adding a condition to the query
<img width="893" alt="image" src="https://github.com/user-attachments/assets/b39c6c2f-db76-415b-b0de-0b93bd851463">

As a result, we will see this sql query
<img width="939" alt="image" src="https://github.com/user-attachments/assets/3dc05c37-1624-486f-a57f-220916bb3eed">

The condition is applied, but for what reason publishedAt is null is finally added is not clear

**Comment by derrickmehaffy** [comment]
tested using the strapi console `yarn strapi console` for ease here but setting `{status: "published"}` works as intended 

![image](https://github.com/user-attachments/assets/82a811fe-83c2-4ba1-a83d-db56f52a2aa3)
![image](https://github.com/user-attachments/assets/1b07b468-5216-420d-8e72-d1b58f3a1330)


Tested using Strapi v5.4.0 and related documentation for this on the document service: https://docs.strapi.io/dev-docs/api/document-service/status#find-many

**Comment by derrickmehaffy** [comment]
Going to go ahead and close as "cannot reproduce" here since it appears to be working
