### ISSUE TITLE
What to save on github?

### ISSUE THREAD

**Issue by GlennCarroy** [strapi/strapi#2222]
Hey there, 

I am curently using a docker-compose containing the official images used to make strapi run. 

I would like to know which folders have to be saved on github when you want to commit your code? 

For now, after some research, it looks llike everything (all folders) are pushed, which might get pretty heavy with a project growing up, is there a reason for that? Cannot the admin / functionnal part not be pushed while commiting since the docker-compose will rebuild everything anyway? 

Thank you in advance for your answers!

**Comment by lauriejim** [comment]
Hi @GlennCarroy can you create this issue on https://github.com/strapi/strapi-docker repo please.
Thank you.
