### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by xiehai001** [strapi/strapi#2223]
![image](https://user-images.githubusercontent.com/24218743/47641527-4c3bb880-dba1-11e8-925e-fc1c293620fa.png)

start error

**Comment by derrickmehaffy** [comment]
You have multiple auto_update timestamp fields on a single model O_o FYI by default all models already have `created_at` and `updated_at` with the updated field being `on update`

Check your models and delete any manual auto_update date fields.

Also please follow the issue template, without providing additional information your issue will be closed.

**Comment by lauriejim** [comment]
Hello @, please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.
Thank you.
