### ISSUE TITLE
Webhooks do not work if a target URL is used that resolves to the same IP as strapi 

### ISSUE THREAD

**Issue by bennyhoyer** [strapi/strapi#22238]
### Required System information

- Node.js version: 18.19.0
- NPM version: yarn@1.22.22
- Strapi version: 5.3.0
- Database: postgres
- Operating system: ubuntu
- Is your project Javascript or Typescript: js

### Describe the bug

We use strapi as a headless CMS for a client's website. We have a next.js frontend which uses ISR with revalidation.
To update the frontend we use a webhook via admin -> settings -> webhooks -> new webhook
As always, the Strapi application is deployed on the same VPS server as the front end.

The strapi application is running on 
`https://strapi.example-domain.com`
and the frontend on 
`https://example-domain.com`.
This is obviosly a 'normal' setup for a CMS/frontend system (maybe also with subpath, but currently not possible in strapi v5).

I want to insert the URL `https://example-domain.com/api/revalidate` to trigger an POST endpoint in the next.js application.

The URL somehow isn't valid and the error is `Url is not supported because it isn't reachable over the public internet`.

Please consider removing the too strict check of localhost domains, as the [is-localhost-ip](https://github.com/tinovyatkin/is-localhost-ip/blob/master/index.js) package not only checks if the URL is localhost, but also if the host of the URL is resolved to the same IP as the strapi application. This is obviosly the case for this setup.
The check is inside [this controller](https://github.com/strapi/strapi/blob/v5.4.1/packages/core/admin/server/src/controllers/webhooks.ts).

For all others running into this problem: 
We had to add an api route on another server and then redirect it to the original server to achieve the expected result.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/22177
