### ISSUE TITLE
Sorting data using GraphQL

### ISSUE THREAD

**Issue by nilsontan** [strapi/strapi#2227]
**Informations**
- **Node.js version**:  10
- **npm version**:  6.4.1
- **Strapi version**: 0.14.4
- **Database**: mongodb
- **Operating system**: Win 10

I have a model like this
```javascript
Person {
  name: String,
  dob: Date,
  ...
}
```
I am trying to sort by date using graphQL.
```javascript
query {
  persons (sort: "dob DESC") {
    _id
    name
    dob
    ...
  }
}
```

**What is the current behavior?**
the query does not throw an error but returns same result as "dob ASC"

**Steps to reproduce the problem**
as above

**What is the expected behavior?**
persons should be sorted with dob desc

**Suggested solutions**
None

**Comment by lauriejim** [comment]
Hello @nilsontan.
Please check the documentation about GraphQL.
Your sort syntax is not correct https://strapi.io/documentation/3.x.x/guides/graphql.html#configurations

**Comment by nilsontan** [comment]
Oops I was looking at 1.x.x docs.
Thanks @lauriejim

**Comment by lauriejim** [comment]
No problem!
