### ISSUE TITLE
[V5:19330] Deployment on different servers not working

### ISSUE THREAD

**Issue by hanpaine** [strapi/strapi#22284]
**Dupe of #19330 for tracking V5 fix**

Required System information
Launched In: 166 ms
Environment: development
OS: darwin-arm64
Strapi Version: 4.19.0
Node/Yarn Version: npm/10.2.3 node/v20.10.0 darwin arm64 workspaces/false
Edition: Community
Database: sqlite

Describe the bug
I'm following the [deployment guide](https://docs.strapi.io/dev-docs/admin-panel-customization#different-servers) for different servers (I want to deploy the admin panel - react app - to Netlify and the server to a droplet or similar). Still, the generated index.html file contains invalid paths to the generated js files.

Steps to reproduce the behavior
Create a Strapi example project using the quick start guide - https://docs.strapi.io/dev-docs/quick-start
Configure the server.js and admin.js files as described in the different server configuration guide - https://docs.strapi.io/dev-docs/admin-panel-customization#different-servers
Run NODE_ENV=production npm run build
The generated paths to the js files contain an extra slash, generating 404 errors:
src="//runtime~main.35ff75f1.js"
src="//main.19186bea.js"

Expected behavior
Create the index.html with the correct paths with only one slash to access the admin site using the http://yourfrontend.com/ URL. I think in this context the proxy recommendation not apply because this is a front-end app with the index.html file and js files, must work with any static hosting provider.

**Comment by ashisherc** [comment]
if this help anyone, I could fix this for me by adding a custom vite config under src/admin/vite.config.ts

```
import { mergeConfig, type UserConfig } from 'vite';

export default (config: UserConfig) => {
  // Important: always return the modified config
  return mergeConfig(config, {
    resolve: {
      alias: {
        '@': '/src',
      },
    },
    base: '',
  });
};

```

**Comment by ashisherc** [comment]
@hanpaine the 5.5.1 release doesnt fix anything. the frontend now makes API calls to the domain of the frontend itself

**Comment by ashisherc** [comment]
the backend URL is nowwhere included in the static admin panel build

**Comment by ashisherc** [comment]
this is the issue,

https://github.com/strapi/strapi/pull/21914/files#r1883687885
