### ISSUE TITLE
[Preview] Edit view : The Back button redirects to the Preview

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#22299]
### Required System information

- Edition: Community
- OS: Mac and WSL
- Environment: Local

### Describe the bug

When opening the preview of an entry, then closing the preview and clicking on the back button, I’m redirected to the preview

### Steps to reproduce the behavior

1. Go to the list view and go to an entry
2. Open the preview, then close it
3. Click on the back button and you will be redirected to the preview

### Expected behavior

It should redirect to the list view (or at least the previous page in the CMS)

### Screenshots

https://github.com/user-attachments/assets/a407821b-4717-43b7-bc6d-568da993863c

**Comment by nevil2** [comment]
I raised similar issue three weeks ago, see https://github.com/strapi/strapi/issues/22132

Any sort of pre-launch testing should have spotted this.

**Comment by EliezerMCR** [comment]
hello I am interested in contributing to this issue, can it be assigned to me please?
