### ISSUE TITLE
[Preview] LaunchPad adjustement about Single Types

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#22302]
### Required System information

CE

### Describe the bug

Some entrie’s preview button are leading to the homepage. For example, if I’m in the product single type and that I click the preview button, I will see the homepage. However, a product page exists on the frontend.

### Steps to reproduce the behavior

1. Use LauchPad to test Preview feature
2. Go to the product single type
3. Click the preview button
4. See the homepage

### Expected behavior

The right page should be displayed (Product preview)

### Screenshots

https://github.com/user-attachments/assets/1f9bb2ee-d6de-4877-8165-a9c113db0168

**Comment by remidej** [comment]
fixed by https://github.com/strapi/LaunchPad/pull/19/commits/6ef83bc625eabe994aa48bf3b8686af0cd17fd6b and https://github.com/strapi/LaunchPad/pull/19/commits/faa960bf8ca824f5b92dc984c4627abeb87b85eb
