### ISSUE TITLE
WYSIWYG  not working properly

### ISSUE THREAD

**Issue by betomoretti** [strapi/strapi#2231]
**Informations**
- **Node.js version**: 10.7.0
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.14.1
- **Database**: Mongo
- **Operating system**: Linux 

**What is the current behavior?**
On my local setup, I'm changing an text attribute to show it as WYSIWYG text attribute. After the server is restarted, the attribute is showed as WYSIWYG text attribute but no file has change. So, I haven't changes to commit and apply it to production. Also, the content type builder is not enabled in production mode. That is, I don't know how to change this in my remote environments. 

**Steps to reproduce the problem**
1. Add a text attribute to a model
2. Mark the option display as wysiwyg
3. Save
4. Check that no file has change

**What is the expected behavior?**
A file change so I can push it and apply it to remote environments

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
`3.0.0-alpha.14.1`

As stated in the issue template, please update to the latest version.

**Comment by soupette** [comment]
In order to display the WYSIWYG you will need to migrate your `core_store` collection

**Comment by betomoretti** [comment]
Hi @soupette, thanks for answer!
Do you mean copy everything in core_store from my local db to my production db?

**Comment by betomoretti** [comment]
To give some context, if change the layout.json file, delete de plugin-content_manager-schema document in the core_store db, and then restart the server, the new document is created empty. That is, the attributes appearance value stay empty and the text areas don't shows with wysiwyg.

**Comment by lauriejim** [comment]
Just `plugin_content-manager_schema` key.
