### ISSUE TITLE
Strapi Asset Export Freezing with AWS S3 Upload Provider

### ISSUE THREAD

**Issue by KamilNahotko** [strapi/strapi#22329]
### Required System information

- Node.js version: v20.17.0
- NPM version: 10.8.2
- Strapi version: 5.0.1
- Database: Postgres
- Operating system: macOS on ARM
- Is your project Javascript or Typescript: Typescript

### Describe the bug

During the data export process in Strapi, the system freezes and stops progressing specifically when trying to export media assets. I am using the @strapi/provider-upload-aws-s3 as the upload provider. However, if I perform the export without including images, the process completes successfully.

### Steps to reproduce the behavior

1. Run the command: npm run strapi export -- --no-encrypt.
2. The export process starts, successfully exporting data such as schemas and entities.
3. When the export reaches the media assets, the process freezes and does not continue.

### Expected behavior

The export process should complete successfully, including the media assets, without freezing or stopping at any point.

### Screenshots

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/7dd5b9c0-62b5-4ab4-ba36-2c82dcb5d86c">

### Additional context

I even tried setting up a fresh, latest version of Strapi. I installed the @strapi/provider-upload-aws-s3 plugin, added a single image, and attempted to export the data. However, the issue remained the same, with the process freezing when exporting media assets.

**Comment by IWhitebird** [comment]
@KamilNahotko i am running in a similar issue ,can you provide some detail on , how did you fixed it ?
