### ISSUE TITLE
How to deploy using dist alone?

### ISSUE THREAD

**Issue by tumintu** [strapi/strapi#22320]
I have completed development on my own project, now i want to deploy it on a windows server. 
when i follow the official guide book to deploy my project, i found that the built dir "dist" cannot deploy alone, it requires node_mudules to start the server.js. it's weird because normal JavaScript project can deploy alone using built dir "dist".

Here is my first attempt deploy dir:
- dist
  | - build
  | - config
  | - src (js file with raw code convert from ts file)
  | - tsconfig.tsbuildinfo
- start-server.js (server.js to start starpi)

Also, i found that after building, the database config no longer effect. i use mysql for my project, but when i start server.js using command "node server.js", i got error says it requires "better-sqlite3".

Here is my second attempt deploy dir:
- dist
  | - build
  | - config
  | - src (js file with raw code convert from ts file)
  | - tsconfig.tsbuildinfo
- node_modules
- package.json
- pnpm.lock.yaml
- start-server.js (server.js to start starpi)

So here is my questions:
1. Is there anyways to deploy built dir "dist" alone without node_modules?
2. Why my database config not working after building?
3. If strapi doesn't support deploy using "dist" dir alone, how am i suppose to deploy my project without direct expose raw code on server?

Here is my development environment:
Node.js version: 20.17.0
NPM version: pnpm 9.12.1
Strapi version: 5.4.0
Database: mysql
Operating system: windows10
Is your project Javascript or Typescript: ts

**Comment by derrickmehaffy** [comment]
This is not possible no
