### ISSUE TITLE
Vite handshake error

### ISSUE THREAD

**Issue by bgyooPtr** [strapi/strapi#22343]
### Required System information

- Node.js version: 18.20.5
- NPM version: 10.8.2
- Strapi version: 5.4.2
- Database: postgres
- Operating system: docker compose (node:18-alpine)
- Is your project Javascript or Typescript: typescript

### Describe the bug
I modified vite.config.ts to solve the CORS issue. ([reference](https://github.com/strapi/strapi/issues/20971#issuecomment-2455967859))

Fortunately, the cors issue has been resolved, but strapi admin occasionally encounters errors. It also periodically fails to connect to port 5173 while doing a handshake.

- ERROR message in admin panel
```
Failed to fetch dynamically imported module: https://<apiserver>.com/node_modules/.strapi/vite/deps/EditConfigurationPage-CKK-5LfX-ADTJOEX6.js?v=e6b6a8b0
```
- ERROR message in admin console
```
GET https://<apiserver>:5173 net ERR_CONNECTION_RESET
ping @ client.ts 338
waitforsuccessfulPing @ clinet.ts 359
```

```typescript
// src/admin/vite.configs.ts
import { mergeConfig, type UserConfig } from 'vite';

export default (config: UserConfig) => {
  // Important: always return the modified config
  return mergeConfig(config, {
    resolve: {
      alias: {
        '@': '/src',
      },
    },
    server: {
      cors: {
        origin: ['http://localhost:3000',],
        credentials: true,
      },
    },
  })
}
```
```typescript
// config/middlewares.ts
export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  {
    name: 'strapi::cors',
    config: {
      origin: ["http://localhost:3000"],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
      headers: ['Content-Type', 'Authorization', 'Origin', 'Accept'],
      keepHeaderOnError: true,
    },
  },
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by hahamini** [comment]
@kasonde You can easily reproduce it. Because I'm using @strapi-community/dockerize.
- Database postgres
- Use typescript and Yarn

1. Create stapi project
```sh
npx create-strapi@latest
pjt name > my-strapi-project
log in > Skip
use the default database (sqlite)> n
database client> postgres
Database name> strapi
Host> 127.0.0.1
Port> 5432
Username> strapi
```
and then
2. Dockerize project using Dockerize.
```sh
cd my-strapi-project
npx @strapi-community/dockerize
> Yarn
> Yes (? Do you want to create a docker-compose file?)
```

3. Run 
```sh
docker compose build -f docker-compose.yml build
docker compose build -f docker-compose.yml up
```

I found out that the reason this error occurred was because I did not open the `5173` port used by `vite` in the docker network.
So I mapped not only 1337 but also 5173 to the docker compose port, and the connection error did not occur.
However, a new SSL error occurred, so I am not sure if this is the right way to fundamentally solve it.

**Comment by bgyooPtr** [comment]
@kasonde You can easily reproduce it. Because I'm using @strapi-community/dockerize.
- Database postgres
- Use typescript and Yarn

1. Create stapi project
```sh
npx create-strapi@latest
pjt name > my-strapi-project
log in > Skip
use the default database (sqlite)> n
database client> postgres
Database name> strapi
Host> 127.0.0.1
Port> 5432
Username> strapi
```
and then
2. Dockerize project using Dockerize.
```sh
cd my-strapi-project
npx @strapi-community/dockerize
> Yarn
> Yes (? Do you want to create a docker-compose file?)
```

3. Run 
```sh
docker compose build -f docker-compose.yml build
docker compose build -f docker-compose.yml up
```

I found out that the reason this error occurred was because I did not open the `5173` port used by `vite` in the docker network.
So I mapped not only 1337 but also 5173 to the docker compose port, and the connection error did not occur.
However, a new SSL error occurred, so I am not sure if this is the right way to fundamentally solve it.
