### ISSUE TITLE
Role Dropdown List Limited Visibility Issue

### ISSUE THREAD

**Issue by tenzan** [strapi/strapi#22342]
# Role Dropdown List Limited Visibility Issue

## Description
The role selection dropdown in the user creation/edit form only shows a limited number of roles (approximately 4 items) in the default view, even when more roles exist in the system. All roles are visible in the main Roles list view, but the dropdown doesn't show all available options unless the user starts typing to filter the roles.

## Expected Behavior
- All available roles should be visible in the dropdown
- If there are many roles, the dropdown should either:
  - Have a scrollbar to view all options
  - Or implement pagination
  - Or clearly indicate that search is required to see more options

## Current Behavior
- Dropdown only shows ~4 items at a time
- No scrollbar or pagination controls
- No visual indication that more roles exist
- Users must type to filter/search to see roles that aren't in the initial visible set
- The roles are sorted alphabetically, but due to the limit, roles later in the alphabet might not be visible at all

## Steps to Reproduce
1. Create more than 4 roles in the system (e.g., "hub-admin", "hub-staff", "tenant-admin", "tenant-location-manager")
2. Go to Users & Permissions > Users
3. Click "Create new entry"
4. Click the "role" dropdown
5. Observe that only ~4 roles are visible
6. Type "te" or any other prefix to see that more roles exist but weren't visible

## Workaround
Users can type the first few letters of the role they want to see all matching roles, but this is not intuitive and requires prior knowledge of the role names.

## Environment
- Strapi Version: 5.4.2
- Node.js Version: v20.18.0
- Issue appears consistently across different browsers

## Additional Context
This limitation affects user management workflows where administrators need to assign roles but can't see all available options without knowing to search for them. This is especially problematic in systems with many custom roles.

## Screenshots
![image](https://github.com/user-attachments/assets/b0a9111c-b15c-44fe-96fa-0e710a907384)
![image](https://github.com/user-attachments/assets/c3a41910-dc59-4892-9fa3-fdcf6993b5c4)
![image](https://github.com/user-attachments/assets/62d6b8c3-5ec3-4423-bbdd-efe22cd36bb7)

**Comment by kasonde** [comment]
Hi @tenzan if possible, could you please the result of the content-manager GET request in the admin panel when you click on the role drop down? I just tried to load up 10 roles (on top of the two default) and everything worked just fine.

**Comment by tenzan** [comment]
Hi all,

Here's the app created from scratch with README descriped the steps.
https://github.com/[tenzan/my-strapi-project](https://github.com/tenzan/my-strapi-project)

But I will share the steps here as well:

1. Created 4 customer roles under `Users & Permissions plugin>Roles`:
    - custom-role-1 (with some random permissions on `Organization`)
    - custom-role-2 (with some random permissions on `Organization`)
    - custom-role-3 (with some random permissions on `Organization`)
    - custom-role-4 (with some random permissions on `Organization`)

2. Go to Content Manager

3. Click on `Create an entry` on User

4. Click on drop-down list

# Result

Only the 1st 4 roles displayed:
  - Authenticated
  - Public
  - custom-role-1
  - custom-role-2

# Expected result
  - drop-down list should show all available roles or provide a scroll bar
  
  
![image](https://github.com/user-attachments/assets/13619c02-b0c7-4df6-a610-11a7d8595c5b)
![image](https://github.com/user-attachments/assets/143c0c8c-26dc-4452-bb98-6349ba80ac9c)
