### ISSUE TITLE
[BUG] Document ID Incrementing by 2 Instead of 1 with PostgreSQL

### ISSUE THREAD

**Issue by hahamini** [strapi/strapi#22359]
### Required System information

- Node.js version: 20.18.1
- NPM version: 10.8.2
- Strapi version: v5
- Database: PostgreSQL
- Operating system: Ubuntu22.04
- Is your project Javascript or Typescript: TS

### Describe the bug

When creating a new entry via POST request in Strapi (v5), the ID of the content increments by 2 instead of the expected increment by 1. However, when using PostgreSQL directly to increment the ID via `nextval`, the ID increments correctly by 1. 

### Steps to reproduce the behavior

1. Setup Strapi v5 with PostgreSQL.
2. Create a new entry via POST request to any content type.
3. Check the `id` field of the new entry.
4. Observe that the ID increments by 2 instead of 1.

### Expected behavior

The ID of each new entry should increment by 1 as per the database sequence configuration.

### Screenshots

N/A

### Code snippets

**PostgreSQL sequence details:**
```sql
sequence_catalog: strapi
sequence_schema: public
sequence_name: tests_id_seq
data_type: integer
numeric_precision: 32
numeric_precision_radix: 2
numeric_scale: 0
start_value: 1
minimum_value: 1
maximum_value: 2147483647
increment: 1
cycle_option: NO
```
When running:

```sql
SELECT nextval('tests_id_seq');
The sequence increments correctly by 1. However, when creating content via Strapi POST request, the ID skips by 2.
```

**Comment by laurenskling** [comment]
`documentId` is a hash, not a number. the `id` is a number, which is _one of the versions_ of the document. If you have, for example, Draft and Publish enabled. Two versions of the document will be created, the draft and the published. Thus, 2 `id`s have been created.

**Comment by derrickmehaffy** [comment]
> `documentId` is a hash, not a number. the `id` is a number, which is _one of the versions_ of the document. If you have, for example, Draft and Publish enabled. Two versions of the document will be created, the draft and the published. Thus, 2 `id`s have been created.

Exactly this, which is intended

**Comment by bgyooPtr** [comment]
@laurenskling Thank you. I understand perfectly. I think I was mistaken because the content-manager of cms shows the id of the original content, and the GET method shows the id of the published content.

**Comment by hahamini** [comment]
@laurenskling Thank you. I understand perfectly. I think I was mistaken because the content-manager of cms shows the id of the original content, and the GET method shows the id of the published content.

**Comment by lamtupro** [comment]
please help me about this issue, auto increment skipped not increment +1, 

![Image](https://github.com/user-attachments/assets/ddee03aa-e256-40c8-a14f-ddd0de35f956)
