### ISSUE TITLE
plugin i18n doesn't support LTS Node version 22.12.0

### ISSUE THREAD

**Issue by fpavlik** [strapi/strapi#22358]
## Bug report
Latest plugin i18n doesn't support LTS Node version 22.12.0

### Required System information

- Node.js version: v22.12.0
- NPM version: 9.6.6
- Strapi version:  5.5.0
- Database: postgres
- Operating system: win/linux
- Typescript

### Describe the bug

After upgrade node version to 22 LTS I can't install any packages because I receive 
```
error @strapi/plugin-i18n@5.0.0-beta.5: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "22.12.0"
error Found incompatible module.
```

I understand that I can downgrade my node version and I'll do it. Or I can run installer in unsecure mode but it's not the good way. 

### Steps to reproduce the behavior

1. Install LTS Node v22.12.0
2. Install `"@strapi/plugin-i18n": "5.0.0-beta.5"`
3. Try to install something else with yarn - on `[3/5] Fetching packages...` stage you will receive an error

### Expected behavior

You can use LTS Node versions

**Comment by Boegie19** [comment]
@fpavlik in strapi v5 the @strapi/plugin-i18n no longest exists i18n is now build in in the core of strapi itself witout the plugin
