### ISSUE TITLE
Additional Fields Issue

### ISSUE THREAD

**Issue by elsayed-ghibaish** [strapi/strapi#22390]
### Required System information

- Node.js version: 22.12.0
- NPM version: 10.9.0
- Strapi version: 5.5.0
- Database: sqlite
- Operating system: win 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

1- In the latest version, Strapi does not allow adding additional fields directly to the User Model of users-permissions.

The solution you tried involves adding extra fields like city and phone through the users-permissions plugin configuration in the plugin.ts file. 

2- Issue with the city field relationship:

When trying to add a value to the city field (which represents a relationship with another model), the value is not accepted if the documentId is used.
However, other relationships seem to work fine, which suggests the issue might be specific to the User Model.

3- ( id ) has become unavailable in GraphQL, although it still exists. However, ( documentId ) still has issues and doesn't work well in relationships, especially with the User model.

### Screenshots

![Screenshot 2024-12-11 124442](https://github.com/user-attachments/assets/5618a35e-7d30-4f6d-9c86-60281f948c93)

![Screenshot 2024-12-11 1246362](https://github.com/user-attachments/assets/d3d0f41f-e7da-4c22-bda3-d0f19ef08c86)

![Screenshot 2024-12-11 1246162](https://github.com/user-attachments/assets/5a465440-9a72-465b-aaff-ebe06222c786)

### thanks strapi 

I hope all these issues are resolved in the latest version so that it can be reliably depended upon.

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/22053
