### ISSUE TITLE
Unable to perform CRUD operations (read/update/delete) on `users` using `documentId`

### ISSUE THREAD

**Issue by mohammadGh** [strapi/strapi#22406]
## Bug report
The data retrieval and update API endpoints for `users` exhibit inconsistent behavior depending on the identifier used. 

* **GET request with `documentId`:** 
    * Expected behavior: Returns user information (status code `200`).
    * Actual behavior: Returns "No Content" (status code `204`).
* **PUT request with `documentId`:** 
    * Expected behavior: Updates user information (status code `200`).
    * Actual behavior: Returns "Not Found" (status code `404`).

However, both retrieval and update functionalities work as expected when using the `user.id` instead of `documentId`.

For example a simple get user info using `documentId`:
```sh
curl  'http://localhost:1337/api/users/<a-document-id>' \
--header 'Authorization: Bearer <jwt-token>'
```
The above API returns **`204 No Content`**. However, if you use `user.id`, it works and returns the user's information.

Similarly, for updating using `documentId`, it returns **`404 Not Found`**. But it works when using user.id instead. For example:

```sh
curl  --request PUT 'http://localhost:1337/api/users/<a-document-id>' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <jwt-token>' \
--data '{
     "displayName": "Mr Bug"
}'
```
###  System information

```

 Project and System information  (OS: Ubuntu 24)
┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Thu Dec 12 2024 18:48:59                         │
│ Environment        │ development                                      │
│ Version            │ 5.5.0 (node v20.18.1)                            │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
│ Database name      │ .tmp/data.db                                     │
```

**Comment by derrickmehaffy** [comment]
This is currently intended functionality as the users-permissions plugin doesn't currently use the documentService and we will be unable to switch this to the document service as it would be a breaking change.
