### ISSUE TITLE
[Homepage] Vertical align issue in the cells

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#22428]
### Required System information
- CE
- Local

### Describe the bug

The texts are not aligned vertically in the cells.

### Steps to reproduce the behavior
1. Create or publish entries
2. Go to the homepage
3. Check the texts are not vertically aligned

### Expected behavior
 they should be aligned vertically

### Screenshots

![image](https://github.com/user-attachments/assets/ac3a5408-09c1-48d1-8ad2-a3c3f66944d4)

**Comment by remidej** [comment]
fixed in https://github.com/strapi/strapi/pull/22346/commits/e0dcac9c6d37e34e277f9f8cde4d02d7444bea37
