### ISSUE TITLE
Strapi v5 Returns ID and DocumentId Same Time

### ISSUE THREAD

**Issue by enesutku** [strapi/strapi#22420]
### Required System information

- Node.js version: v20.15.0
- NPM version: 10.7.0
- Strapi version: v5.5.0
- Database: MYSQL
- Operating system: Ubuntu 20
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When we send an API request, the response still shows the ID value, and in Strapi's admin panel, the content also displays the ID. As far as I know, in version 5, it's supposed to use `documentId` instead of `id`. This might be intentional for migration purposes, but I want to create a brand-new Strapi project, and it feels a bit confusing. 

Is it possible to completely disable the ID feature?

### Steps to reproduce the behavior

1. Send an API request to the Strapi backend.
2. Check the response returned by the API.
3. Observe that the response includes the id field alongside the documentId.

### Expected behavior

The id field should be entirely replaced by documentId in all API responses and the Strapi admin panel for a cleaner and consistent experience.

**Comment by derrickmehaffy** [comment]
It's not currently possible to remove the ID from the response (but should be ignored as it exists for compatibility reasons from Strapi 5)
