### ISSUE TITLE
generateBreakpoint() is not optimazing image resizes leading to larger files in bytes

### ISSUE THREAD

**Issue by agafonovdmitry** [strapi/strapi#22436]
### Describe the bug

When uploading images which can be optimized and fall into some breakpoint ranges strapi calls generateBreakpoint() function which do not honor optimization rules which is actually applyed to the original image.

This leads to smaller (is bytes) of bigger (in pixels) images in the media library which is not somewhat logical and optimal for content management.

Similar applies to generateThumbnail() for even smaller (in pixels) files.

### Steps to reproduce the behavior

Upload images to Media Library and inspect files in uploads directory and their size in bytes.

### Expected behavior

When enabled and possible, strapi should optimize original images, responsive resizes and thumbnails as well.

### Code snippets

See strapi/packages/core/upload/server/src/services/image-manipulation.ts

**Comment by codeThanvi** [comment]
Can you explain is the image you are uploding is getting shorter or larger with respect to its dimensions? like, is the imagesize reducing or increasing?

**Comment by codeThanvi** [comment]
I added a 2.8 mb file and got the following file sizes
uploaded file=2.5 mb
large=157kb
medium=97.1kb
small=47.7kb
thumbnail=10.6kb

**Comment by codeThanvi** [comment]
what should be the expected result?

**Comment by agafonovdmitry** [comment]
Thank you for feedback!

Oh, it seems it is hugely depends on images. We have many design images which are png of medium sizes with transpanency. Around 1000 - 1500 px for larger dimension. So, small variant of 500 px without optimisation is aroud x1.5 of size of original optimized image (80% quality according to source code).

Do not why, but I cannot use webp images with strapi5 now, will investigate separately.

**Comment by agafonovdmitry** [comment]
Turns out this issue is a duplicate of #20162, which is marked as completed... but no changes made to code.
