### ISSUE TITLE
New local entries does not take values from default local

### ISSUE THREAD

**Issue by CihanNewSenses** [strapi/strapi#22445]
### Required System information

- Node.js version: v21.1.0 
- NPM version: 10.2.0
- Strapi version: v5.5.1
- Database: sqlite
- OS: darwin-x64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

If Internationalization is enabled in Collection-Type and text field is common to all locales, it does not take the value from default, when creating new entry for different local.  

### Steps to reproduce the behavior

1. Go to 'Content-Manger'
2. Click on a Collection-Type
3. Click on local option and 'create .... local'
4. See error that common value is not there

### Expected behavior

If Internationalization is enabled in Collection-Type and text field is common to all locales, it should take the value from default, when creating new entry for different local.  

Tutorial Video shows also expected behavior https://www.youtube.com/watch?v=TyZRyPIqzMo

### Screenshots

https://github.com/user-attachments/assets/4569ffd9-bc38-48c2-a51d-61a4d5711911

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/21594
