### ISSUE TITLE
Customized id field not working when trying to query with GraphQL

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#2244]
**What is the expected behavior?**
I've customized my model to have a `String` as the `id`. Then tried to query with graphql like this:
```
const POST_QUERY = gql`
  query BlogPost($id: String!) {
    blog(id: $id) {
      title
      text
      createdAt
      author {
        username
        avatar {
          url
        }
      }
    }
  }
`;
```
I've got the error:

`variable "$id" of type "String!" used in position expecting type "ID!"`

By looking at the sources, i see that the graphql plugin, defines Query for any given model with `(id: ID)` without even looking at the model customization (change `ID` by `String`)

## Proposed solution

Modify the logic to detect if there is a definition for the `id` attribute on the model, and use its type on the graphql Resolver definition.

**Comment by lauriejim** [comment]
Hello @jacargentina , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by jacargentina** [comment]
@lauriejim already fixed in my PR... Maybe you don't saw that 😄

**Comment by lauriejim** [comment]
I saw that just after posting my message.

**Comment by jacargentina** [comment]
@lauriejim that Travis thing about formating, the files are different from the ones involved. If you want I can apply the needed changes?

**Comment by scorpionking90** [comment]
@jacargentina when are we planning to have a release for this?
