### ISSUE TITLE
Strapi 5.5.0, options config for routes in particular API not working

### ISSUE THREAD

**Issue by davidwiniarz** [strapi/strapi#22444]
## Bug report

Having this kind of config in any routes

```
import {factories} from '@strapi/strapi';

export default factories.createCoreRouter('api::favourite.favourite',
    {
        prefix: '',
        only: ['find', 'findOne'],
        except: ['create', 'update', 'delete'],
        config: {
            find: {
                auth: false,
                policies: [],
                middlewares: [],
            },
            findOne: {},
            create: {},
            update: {},
            delete: {},
        },
    });
```

make NO effect to application.

**In this scenario, 'create', 'update', 'delete' still works, but it should not.**

### Required System information

- Node.js version: 20.11
- NPM version: 10.9.0
- Strapi version: 5.5.0
- Database: postgres
- Operating system: macOS
- Is your project Javascript or Typescript: TS

**Comment by derrickmehaffy** [comment]
only and except cannot be used together, it's one or the other (one is inclusive and the other is exclusive).
