### ISSUE TITLE
CORS security API

### ISSUE THREAD

**Issue by usb248** [strapi/strapi#2245]
**Informations**
- **Node.js version**: 8.12.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: mongoDB
- **Operating system**: Win10

**Question**
I develop a web application with a framework (NUXT) and i would like to know how api is secured. (yes we can required a authentificated user, but in my most cases, my endpoints need to be public (pagination, insert post in specific content type etc ...)

For example, i need to send mail, so in strapi we have "api_url_of_strapi/email" url (POST request) with json body for the send() method in the plugin (in my case, another provider : strapi-email-nodemailer). It works but, i'm doubious and septic. In security section, i see "Cors" section, we can put an Origine. I've tested with postman, it works too...while i call api outside from my node app 
(I get this message in my console : Cross-Origin Request Blocking: The Same Origin policy does not allow you to view the remote resource located at http://localhost:1337/temoignages/count?approuver=true. Reason: The CORS header "Access-Control-Allow-Origin" does not match "http://localhost:3000." [Read more] but the request still succeed) ? Why ? It means that any malicious people can call these url from any others domains ?? Thus, spamming with my custom smtp (for example) ?

I develop other PHP application, to secure public POST request, we have token (in hidden field in the form) which is checked on server side ([info](https://book.cakephp.org/3.0/en/controllers/components/security.html#form-tampering-prevention)). Is there a solution (except the use of authentication) with strapi ? 

thanks
regards

**Comment by lauriejim** [comment]
Hello @usb248.

What is you CORS configurations ?

The PHP method you speak about is `csrf`. You can do it when you have server side rendering.
1 page = 1 token and if the request come from an invalide page, it's blocked.

**Comment by usb248** [comment]
i've put my local base url, Origine : http://localhost:3000.
Yes exactly, my node app have server side rendering, but i use strapi to render my pages. for example : what are security policies to prevent form tampering in create() ( = PUT request) on my sign up page ?

**Comment by lauriejim** [comment]
Your cors config looks good. If your request come from the correct url you set...

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
