### ISSUE TITLE
Strapi 5  connectivity issue with google cloud bucket 

### ISSUE THREAD

**Issue by suavelad** [strapi/strapi#22459]
When I attempt to install this the package, I get the error shown below
I am using strap 5

npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'strapi-provider-upload-google-cloud-storage@4.0.0',
npm warn EBADENGINE   required: { node: '>=12.x.x <=16.x.x', npm: '>=6.0.0' },
npm warn EBADENGINE   current: { node: 'v18.20.5', npm: '10.8.2' }
npm warn EBADENGINE }

Please can I get a guide on how to implement the google cloud storage plugin on strapi 5.

Regards

**Comment by CodeDruid13** [comment]
Share your plugins.ts code. Are you using @strapi-community/strapi-provider-upload-google-cloud-storage?

**Comment by suavelad** [comment]
export default ({ env }: { env: (key: string) => string }) => ({
    'users-permissions': {
      config: {
        jwtSecret: env('ADMIN_JWT_SECRET'),
      },
    },
    'upload': {
        provider: '@strapi-community/strapi-provider-upload-google-cloud-storage',
        providerOptions: {
          bucketName: 'mercurie_blog',
          publicFiles: true,
          uniform: false,
          baseUrl: 'https://storage.googleapis.com/mercurie_blog',
          basePath: '',
        },
      },
  });

**Comment by suavelad** [comment]
I tried to for install it using the --legacy flag,

then I updated the package.json for the node version
  "engines": {
    "node": ">=18.x.x <=20.x.x",
    "npm": ">=6.0.0"
  },
  
  
  then I rebuilt and ran it but it is still storing the record in my local and not google cloud storage.
  Please what am I missing ?

**Comment by suavelad** [comment]
I tried to for install it using the --legacy flag,

then I updated the package.json for the node version
  "engines": {
    "node": ">=18.x.x <=20.x.x",
    "npm": ">=6.0.0"
  },
  
  
  then I rebuilt and ran it but it is still storing the record in my local and not google cloud storage.
  Please what am I missing ?

**Comment by CodeDruid13** [comment]
Follow the plugin docs:

[Setup Plugin ](https://github.com/strapi-community/strapi-provider-upload-google-cloud-storage#-setting-up-google-authentication)

The only way I made mine work was using a service account

**Comment by suavelad** [comment]
Thank you for the help. 

I followed the steps but when I run it using NODE_ENV=dev npm run build && npm run develop

It returns no error but it uploads to my local PC (in the upload folder)

**Comment by Boegie19** [comment]
closing it since this issue is related to a strapi plugin and not a package maintained by the strapi team
