### ISSUE TITLE
Date field picker displays incorrect date in content manager

### ISSUE THREAD

**Issue by birdzai** [strapi/strapi#22452]
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.5.1
Node/Yarn Version: yarn/1.22.22 npm/? node/v20.18.0 darwin arm64
Edition: Community
Database: postgres

### Describe the bug

The dates displayed in the content manager are off by 1 day from what is stored in the database (and returned by the Rest API)

### Steps to reproduce the behavior

1. Go to content manager
2. Click on a entry that contains a simple "date" field (no time, or seconds, just DD/MM/YY)
3. Date displayed appears to be off by 1 (displayed as 1 day earlier). If I click on the field to bring up the date picker and then click away, the date changes (even though it shouldn't).

### Expected behavior

The date displayed in the date field should match the date stored in the database.

### Screenshots

Returned from Rest API:

<img width="358" alt="Screenshot 2024-12-17 at 8 08 01 AM" src="https://github.com/user-attachments/assets/0403635f-2773-4fbe-a68f-0f70dc6714ef" />

Displayed in content manager:

<img width="437" alt="Screenshot 2024-12-16 at 10 26 36 PM" src="https://github.com/user-attachments/assets/8ffe6bf9-5880-4eb1-8b69-ef9a95c5b030" />

Field definition in Content Type-Builder:

<img width="827" alt="Screenshot 2024-12-16 at 10 36 21 PM" src="https://github.com/user-attachments/assets/a52dbaa4-18b6-4084-8298-8951ce98f40b" />

**Comment by FurquanAnwer** [comment]
Please assign this to me !

**Comment by birdzai** [comment]
I highlighted the wrong date in the screenshot from the Rest API...I uploaded a newer image with the right field highlighted.

**Comment by birdzai** [comment]
Closing. Fixed by #22410
