### ISSUE TITLE
Roles assigned to review workflow stages went missing after importing an exported data file

### ISSUE THREAD

**Issue by a6i-palo** [strapi/strapi#22474]
### Required System information

- Node.js version: 18.18.2
- NPM version: 9.8.1
- Strapi version: 4.25.17 
- Database: SQLite
- Operating system: OSX
- Is your project Javascript or Typescript:

### Describe the bug

Roles assigned to stages of a review workflow are not restored after importing a exported data dump.

### Steps to reproduce the behavior

1. Create a review workflow with a couple of stages.
2. Assign a role to each of the stages
3. Run data export
4. Modify the review workflow in step 1 by removing a stage
5. Import the exported data in step 3
6. The review workflow has been restored, but all role assignment are gone

Other permutation tested include not making any modification to the review workflow before importing the exported data, deleting the entire workflow and testing with the default review workflow. The outcome of the other permutation are the roles will be gone after exported is imported. 

Please note that the browser has to be refresh for render the updated data in the UI after the import.

### Expected behavior

The assigned roles are restored along with the rest of the review workflow.

### Screenshots

https://github.com/user-attachments/assets/61d1f4b5-70c7-4a03-ab91-01e1aa303352

### Additional context

I am not able to test this in the latest version 5 due to the following issue
https://github.com/strapi/strapi/issues/22381

**Comment by derrickmehaffy** [comment]
This is currently intended as we do not export admin users from DTS at this time.

**Comment by a6i-palo** [comment]
I verified that this is the case. I am using `strapi-plugin-config-sync` as well, thus is able to recover custom roles, although the assignment to the review workflow stage roles is still lost.

I wonder why would roles be coupled with users when it's essentially a logical grouping of permissions and can be exported without the users. I imagine for setup with very granular access control setup across collections and plugins with multiple roles, it can be a very frustrating process to setup after an import.
