### ISSUE TITLE
Creating nested models

### ISSUE THREAD

**Issue by rejifald** [strapi/strapi#2247]
**What is the expected behavior?**
When I send object with nested model, for example Company: {name: "newCompany", CompanyBanner: {
url: "example.com/newCompany.jpg"
}}
Saving both models is expecting result.
Also if CompanyBanner has _id field, then update this model too.
So, WDYT ?
I saw FR where been proposed create related models directly from same page, where created parent model.
Best.

**Comment by lauriejim** [comment]
Hello @rejifald , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.
Thank you.
