### ISSUE TITLE
Strapi 5.6.0 | Content Manager ListView - Entries always showing up as "Draft"

### ISSUE THREAD

**Issue by Xzandro** [strapi/strapi#22470]
### Required System information

- Node.js version: 20
- NPM version: 8
- Strapi version: 5.6.0
- Database: PostgreSQL
- Operating system: Windows 11 Pro
- Is your project Javascript or Typescript: Javascript

### Describe the bug

If you go to any content type within the Content Manager, in the list view the table indicates that all entries are a "Draft", although they are Published. They will also show up as published if you click into an entry in the EditView. This does not seem the case if a collection tyle uses the Draft & Publish system AND Internationalization.
This behavior does not appear to happen in Strapi v5.5.2.

### Steps to reproduce the behavior

1. Go to any collection type which has Draft & Publish enabled.
2. Make sure that you have a published entry available in the ListView.
3. You will see that all entries are wrongly marked as a "Draft"

### Expected behavior

The list view of the content manager should correctly reflect if an entry is a "Draft" or "Published"

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment]
I'm able to reproduce this in v4.6.0, downgrading to v5.5.2 it works as intended

https://www.loom.com/share/b8686712df3243448af3e36b0aea724c?sid=c501c023-6318-4e49-8a8d-cb402cf2fc48

**Comment by derrickmehaffy** [comment]
Per @Marc-Roig: it's quite likely this is related to https://github.com/strapi/sdk-plugin/issues/68

As it should only happen on content-types that have i18n disabled
