### ISSUE TITLE
Adding a file to api config folder disables those api

### ISSUE THREAD

**Issue by ykit9** [strapi/strapi#2248]
**Informations**
- **Node.js version**:  v10.10.0
- **npm version**:  6.4.1

- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: 3.6.4
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

Generated api returns 404 response on all related routes.

**Steps to reproduce the problem**

1. Install new project using command `strapi new projectname`
2. Perform commands
```
cd projectname
strapi generate:api test
strapi start
```
3. Make sure generated api is working correctly, sending request from postman or browser:
```
GET http://localhost:1337/tests
```
Expected response:
```
{
    "statusCode": 403,
    "error": "Forbidden",
    "message": "Forbidden"
}
```
We did not set up any permissions for this api, therefore it's forbidden by default.

4. Create file with name v.js ( this could be any filename starting from letter 'v' - 'v123456.js', etc. ) at the folder `$PROJECT_ROOT/api/test/config `;
This file must export function, like this:
```
function testFunction() {
  console.log("this function is not called");
}

module.exports = testFunction;

```

5. Server will restart automatically. 
6. Perform the same request from step 3. Result will be:
```
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}
```

**What is the expected behavior?**

Expected the same response as in step 3.

**Suggested solutions**
Have no idea.

**Comment by lauriejim** [comment]
Hello @ykit9 , thank you for reporting this issue. Really strange...
We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
Hello @ykit9 !

config folder allow only JSON files.

There is a `./config/functions` folder for JS functions/script.
