### ISSUE TITLE
I Can't upload image

### ISSUE THREAD

**Issue by ouizz** [strapi/strapi#22482]
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by hebersolano** [comment]
Make sure the user have permission or is able to use that endpoint

**Comment by ouizz** [comment]
how to i check this issue?


thank you

นายวีระ  แซ่เบ๊ (อุ้ย)
MR.Weera Saebe (Oui)
Mobile:086-500-2581
E-mail : ***@***.***
--------------------------------------------------
