### ISSUE TITLE
Content manager LeftMenu (search/filter) keyword should match in whole string not from start

### ISSUE THREAD

**Issue by AmmonLin** [strapi/strapi#22492]
### Required System information

- Node.js version: 22.12.0
- NPM version: 9.9.3
- Strapi version: 5.x / 4.x
- Database: sqlite / mysql
- Operating system: Ubuntu 20.04.6 LTS in WSL
- Is your project Javascript or Typescript: Javascript / TypeScript

### Describe the bug

When using the "Search for a content type" feature in the Content Manager, entering a keyword only lists items that start with the keyword. In general understanding, keyword searching and filtering typically means the string contains the keyword. So, I consider it a bug not a feature request and report it here.

### Steps to reproduce the behavior

1. Create three Collection/Single types as `Homepage`, `Work From Home` and `About Us`
2. Go to 'Content Manager'
3. Click on 'Magnifier Icon' on the top of LeftMenu
4. In the shown input box type `Home` 
5. Only `Homepage` will show on the list

### Expected behavior

Both `Homepage` and `Work From Home` show on the list  

### Screenshots

N/A

### Code snippets

N/A

### Additional context

Drill down into the [LeftMenu.tsx](https://github.com/strapi/strapi/blob/146a31b564bc8232686331f6b28f7ff966817963/packages/core/content-manager/admin/src/components/LeftMenu.tsx#L83)

**Comment by derrickmehaffy** [comment]
This is currently intended as we use `containsi` rather than `startsWith`: https://github.com/strapi/strapi/issues/20643

**Comment by AmmonLin** [comment]
Apologies for bothering you. The same issue also occurs in ContentTypeBuilderNav.  Should I create another issue to report ?

drill down to [L184](https://github.com/strapi/strapi/blob/develop/packages/core/content-type-builder/admin/src/components/ContentTypeBuilderNav/useContentTypeBuilderMenu.ts#L184)

**Comment by derrickmehaffy** [comment]
If the search is 'working' but is looking like it uses contains rather than starts with that's intended as well.

We have swapped back and forth a few times and most of users prefer contains as it's a bit easier to work with.
