### ISSUE TITLE
Unique field not working

### ISSUE THREAD

**Issue by mastermsd** [strapi/strapi#2249]
**Informations**
- **Node.js version**: v10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: PostgreSQL 10.5
- **Operating system**: MacOS Mojave (v 10.14)

**What is the current behavior?**
Setting a field to be unique still makes it possible to fill in ununique value.

**What is the expected behavior?**
Should throw an error.

**Suggested solutions**
I have no suggested solution, but an alternative.
Set the field as a unique constraint manually in pgAdmin.
But would be better if Strapi team solving it on their side.

**Comment by lauriejim** [comment]
Related to this issue https://github.com/strapi/strapi/issues/1189
