### ISSUE TITLE
Published Content Not Reflecting in Table View

### ISSUE THREAD

**Issue by VatthanaB** [strapi/strapi#22490]
### Bug Report: Published Content Not Reflecting in Table View

**Project Details:**
- **Project Name:** Matatini Strapi
- **Version:** 0.1.0
- **Strapi Version:** 5.6.0
- **Node.js Version:** >=18.0.0 <=22.x.x
- **Database Used:** Better SQLite3 (Version 11.3.0)

---

**Bug Summary:**
When publishing content via the Strapi Admin Panel, the content does not reflect as "Published" in the table view. This discrepancy persists despite the content showing as published in the individual entry view.

---

**Steps to Screenshots:**
1. Navigate to the "Region" collection type in the Strapi Admin Panel.
2. Create a new entry with the name "Aotea."
3. Save the entry as a draft.
4. Publish the entry.
5. Return to the table view for the "Region" collection.

---

**Expected Behavior:**
The table view should update to reflect the published status of the content.

---

**Observed Behavior:**
The content remains listed as "Draft" in the table view, even though the entry displays as "Published" in the individual entry view.

---

**Screenshots:**
![Screenshot 2024-12-23 at 10 33 27 AM](https://github.com/user-attachments/assets/86d5b398-97f0-49b8-9c07-5db2c3d913c2)
![Screenshot 2024-12-23 at 10 32 59 AM](https://github.com/user-attachments/assets/82e1cba6-b48d-44a0-aacb-ba4b2aa2f6a7)
![Screenshot 2024-12-23 at 10 32 51 AM](https://github.com/user-attachments/assets/22b905f3-2f9e-47ff-8597-f78ce0cbf52b)

---

**Environment Details:**
- **Dependencies:**
  ```json
  {
    "@strapi/plugin-cloud": "5.6.0",
    "@strapi/plugin-users-permissions": "5.6.0",
    "@strapi/strapi": "5.6.0",
    "better-sqlite3": "11.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  }
  ```
- **Dev Dependencies:**
  ```json
  {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  }
  ```

---

**Additional Context:**
- The API response correctly shows the `publishedAt` field with a valid timestamp, but this change is not reflected in the table UI.
- The issue may be related to table view caching or an API call that doesn't fetch updated status values.
- I created another empty project on version 5.6.0, and the same bug appears.
- I have another project running on version 5.4.2, and this issue does not occur there.

**Comment by radu5121** [comment]
I noticed that when you try to publish it a new record is created in the DB, but in the UI it shows the old one which is not published

![image](https://github.com/user-attachments/assets/930d592f-14e4-4e97-90bd-a76bae84a54f)

![image](https://github.com/user-attachments/assets/b6eaedb7-29dd-4ec8-ab2f-175af4f9327b)

**Comment by jorrit** [comment]
See #22473

**Comment by abhi-ideal** [comment]
Still not working for me i am using the latest version mentioned in the Release notes 

![Screenshot from 2024-12-30 18-22-52](https://github.com/user-attachments/assets/1abe8b3c-0a18-4b9d-a4bc-6afe0c30546c)


`"dependencies": {
    "@strapi/plugin-cloud": "5.6.0",
    "@strapi/plugin-users-permissions": "5.6.0",
    "@strapi/strapi": "5.6.0",
    "better-sqlite3": "11.3.0",
    "fs-extra": "^10.0.0",
    "mime-types": "^2.1.27",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  },`

**Comment by derrickmehaffy** [comment]
4.6.1 hasn't been released yet but it'll be fixed in that release

**Comment by abhi-ideal** [comment]
> 4.6.1 hasn't been released yet but it'll be fixed in that release

Do you mean 5.6.1? But when it will be available I am getting the version not found 

npm ERR! notarget No matching version found for @strapi/plugin-cloud@5.6.1.

**Comment by derrickmehaffy** [comment]
Yeah sorry old muscle memory, 5.6.1 yes. And most likely next Wednesday during our regular release schedule (not this week).

We paused our normal release schedule for the holidays, once we go back to normal we do a new release every Wednesday.

**Comment by abhi-ideal** [comment]
Thanks @derrickmehaffy and Happy New Year :)

**Comment by abhi-ideal** [comment]
Hello, @derrickmehaffy. Are there any updates for the 5.6.1 version update? I appreciate any help you can provide.

**Comment by derrickmehaffy** [comment]
> Hello, @derrickmehaffy. Are there any updates for the 5.6.1 version update? I appreciate any help you can provide. 

5.6.1 got skipped and instead this was released in 5.7.0

**Comment by abhi-ideal** [comment]
Thanks @derrickmehaffy

**Comment by abhi-ideal** [comment]
Hi @derrickmehaffy,

The updates in version 5.7.0 look awesome, thank you for that! I’ve been trying to manage the home page contents based on the logged-in user's role. However, all recently edited and published entries appear to be showing up, rather than just content specific to the logged-in user.

Is there a way to filter the displayed content so that each user only sees content they created or that’s relevant to their role? This would help in ensuring proper access control and personalization.

Looking forward to your guidance!

**Comment by abhi-ideal** [comment]
Hello, @derrickmehaffy Any update for above mentioned point.

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy,
> 
> The updates in version 5.7.0 look awesome, thank you for that! I’ve been trying to manage the home page contents based on the logged-in user's role. However, all recently edited and published entries appear to be showing up, rather than just content specific to the logged-in user.
> 
> Is there a way to filter the displayed content so that each user only sees content they created or that’s relevant to their role? This would help in ensuring proper access control and personalization.
> 
> Looking forward to your guidance!

That's more of a question unrelated to this issue, for stuff like that you should join the community Discord: https://discord.strapi.io

But the feature you're looking for is RBAC conditionals: https://docs.strapi.io/dev-docs/configurations/guides/rbac
