### ISSUE TITLE
[Strapi v5] During database migration locales were lost

### ISSUE THREAD

**Issue by Johann-S** [strapi/strapi#22504]
## Bug report

Hello 👋 

I'm currently working on updating an existing Strapi v4 to v5 and when I ran the migration tool I thought I lost all my data but everything was in my database.
In reality I found that during the migration my french local was removed and all my data had a `locale` field empty in database.

If I manually add the french locale in Strapi and if I update manually my `locale` fields in database everything is working just fine.

Maybe there is something to improve?

### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: v5.6.0
- Database: PostgreSQL
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

**Comment by Johann-S** [comment]
Hey @derrickmehaffy I updated my issue following the template 🙏

**Comment by Gkleinereva** [comment]
Hi!  I just ran into this same problem.  Is there any chance we can take another look at it?  I'd be happy to provide some additional information if I can!

**Comment by Johann-S** [comment]
I don't know if I should create a new issue or @derrickmehaffy will take another look 🤔

**Comment by Gkleinereva** [comment]
@Johann-S I actually hopped onto office hours in the Strapi Discord server on Thursday to talk about this problem.  Derrick was in there, and he said that this was an issue in the past, but was fixed.  He told me to revert my database back to the v4 schema using a backup, and then to start strapi up on 5.8.0 (thus running the most up-to-date migrations).  And it worked!  So I suggest you (or other future explorers) do that.

**Comment by derrickmehaffy** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1689750?s=64&amp;v=4">@Johann-S](https://github.com/Johann-S?rgh-link-date=2025-01-18T23%3A42%3A38.000Z) I actually hopped onto office hours in the Strapi Discord server on Thursday to talk about this problem. Derrick was in there, and he said that this was an issue in the past, but was fixed. He told me to revert my database back to the v4 schema using a backup, and then to start strapi up on 5.8.0 (thus running the most up-to-date migrations). And it worked! So I suggest you (or other future explorers) do that. Thanks Derrick - you're the best!!

Always welcome man <3

**Comment by Johann-S** [comment]
Thanks @Gkleinereva for letting me know and thanks @derrickmehaffy for the solution 👌

**Comment by meesakveld** [comment]
@Gkleinereva, this worked for me as well! I tried it first on v5.49.0 but that lost all localized data, then tried it on v5.8.0 and that worked! Thank you very much!

**Comment by Gkleinereva** [comment]
Glad it helped!  Strange that upgrading to `v5.49.0` caused the issue, but that upgrading to `v5.8.0` worked...  Is it possible that there was a regression?

**Comment by meesakveld** [comment]
I just tried it again with the same backup data on v5.49.0 and after that on v5.50.0, and it worked this time on both versions. Not sure what happened previously, but I'm glad it's working now!
