### ISSUE TITLE
Required attributes are inferred as optional when generating types

### ISSUE THREAD

**Issue by LuizPelegrini** [strapi/strapi#22509]
### Required System information

- Node.js version: 18
- NPM version: 10.2.3
- Strapi version: 5.6.0
- Database: sqlite
- Operating system: macos 14.7.2
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Attribute types for both Content-Types and Components are set as optional, even though they're marked as required when generating the types via `strapi ts:generate-types` command. The issue comes from the optional operator set it [here](https://github.com/strapi/strapi/blob/146a31b564bc8232686331f6b28f7ff966817963/packages/core/types/src/data/content-type.ts#L26C50-L26C55) and null type [here](https://github.com/strapi/strapi/blob/146a31b564bc8232686331f6b28f7ff966817963/packages/core/types/src/data/content-type.ts#L29)

### Steps to reproduce the behavior
1. Generate project types by running `npm run strapi ts:generate-types`
2. Update tsconfig to strict mode
3. Anywhere in your codebase, import Data type from `@strapi/strapi`
4. Create a variable and assign the type `Data.ContentType<'api::post.post'>` or `Data.Entity<'api::post.post'>`
5. Variable attributes are all optional

### Expected behavior

Required attributes should not be inferred as optional

### Screenshots
Generated types
![image](https://github.com/user-attachments/assets/e747effe-476e-45bc-ba28-f262c53e9e60)

As you can see in the image, all fields (including required fields like `title` and `seo`) are set as optional.
![image](https://github.com/user-attachments/assets/a4bf5739-ce3d-40d7-8110-73a7140b3f4a)
![image](https://github.com/user-attachments/assets/7353f48d-e2ec-44fb-8728-3e35a553b933)

### Code snippets

Example repo [here](https://github.com/LuizPelegrini/strapi-ts-issue)

**Comment by LuizPelegrini** [comment]
since I'm exporting Strapi type utilities to be used in my frontend applications, I set strict mode here just to give an example of potential issues frontend apps will get once we update to strapi 5

**Comment by Boegie19** [comment]
the way how you will be suposed to do this once it is fully released is the strapi sdk https://github.com/strapi/sdk-js

**Comment by derrickmehaffy** [comment]
That's because internally they are still optional until they are published, as @Boegie19 mentions the frontend types we will generate for the SDK will be more strict to the content-api but there are type differences between the content-api and admin-api.

**Comment by derrickmehaffy** [comment]
Will transfer this over to the sdk repo so the team can take a look and as a reminder to them on the differences in the content-api types

**Comment by derrickmehaffy** [comment]
Ah I can't because of the repo permissions. @LuizPelegrini Can you please open a new issue on that sdk-js repo and link to this one?

**Comment by LuizPelegrini** [comment]
sure thing, thanks guys

**Comment by LuizPelegrini** [comment]
@derrickmehaffy done, transferred to [here](https://github.com/strapi/sdk-js/issues/23). 

Until the sdk is ready to use, is there a workaround/better way to "massage" those types? We were using [Attribute.GetValues](https://github.com/strapi/strapi/blob/97e7c7b8ae2a5bc5ff48d10ff66e08e15840a726/packages/core/types/src/types/core/attributes/utils.ts#L101) in strapi 4. But it has been [updated](https://github.com/strapi/strapi/blob/d08f965fdae7b8811b54bdbfd331a9834d1bfdea/packages/core/types/src/modules/documents/params/attributes/index.ts#L78) in Strapi 5, especially when it comes to [relations](https://github.com/strapi/strapi/blob/d08f965fdae7b8811b54bdbfd331a9834d1bfdea/packages/core/types/src/modules/documents/params/attributes/relations.ts#L32C13-L32C31) which resolves to `XOneInput` and `XManyInput` :/ we built a custom sdk around those generated types, but now it's unusable due to this

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy done, transferred to [here](https://github.com/strapi/sdk-js/issues/23). 
> 
> Until the sdk is ready to use, is there a workaround/better way to "massage" those types? We were using [Attribute.GetValues](https://github.com/strapi/strapi/blob/97e7c7b8ae2a5bc5ff48d10ff66e08e15840a726/packages/core/types/src/types/core/attributes/utils.ts#L101) in strapi 4. But it has been [updated](https://github.com/strapi/strapi/blob/d08f965fdae7b8811b54bdbfd331a9834d1bfdea/packages/core/types/src/modules/documents/params/attributes/index.ts#L78) in Strapi 5, especially when it comes to [relations](https://github.com/strapi/strapi/blob/d08f965fdae7b8811b54bdbfd331a9834d1bfdea/packages/core/types/src/modules/documents/params/attributes/relations.ts#L32C13-L32C31) which resolves to `XOneInput` and `XManyInput` :/ we built a custom sdk around those generated types, but now it's unusable due to this

I have no idea, I'm not a typescript person myself (I honestly hate using TS personally). I know the types structure and why it is the way it is but unless I'm contributing to the main codebases I'm a CJS user.

**Comment by Convly** [comment]
> Until the sdk is ready to use, is there a workaround/better way to "massage" those types? We were using [Attribute.GetValues](https://github.com/strapi/strapi/blob/97e7c7b8ae2a5bc5ff48d10ff66e08e15840a726/packages/core/types/src/types/core/attributes/utils.ts#L101) in strapi 4. But it has been [updated](https://github.com/strapi/strapi/blob/d08f965fdae7b8811b54bdbfd331a9834d1bfdea/packages/core/types/src/modules/documents/params/attributes/index.ts#L78) in Strapi 5, especially when it comes to [relations](https://github.com/strapi/strapi/blob/d08f965fdae7b8811b54bdbfd331a9834d1bfdea/packages/core/types/src/modules/documents/params/attributes/relations.ts#L32C13-L32C31) which resolves to XOneInput and XManyInput :/ we built a custom sdk around those generated types, but now it's unusable due to this

Hey there, thanks for opening the issue. The issue is indeed not related to the SDK but with how we make sure types are compatible with all versions of a document (in this case the draft versions) and forces us to choose the looser one.

Can you open a question/thread on our [Discord](https://discord.com/channels/811989166782021633/1019655562092355594) and tag me? We can discuss what types you're missing/your needs. Maybe we already have something that could fit your requirements

**Comment by LuizPelegrini** [comment]
@Convly apologies for delay on this, but thanks for getting back! I raised a [question](https://discord.com/channels/811989166782021633/1330447852672909402/1330447852672909402) in discord, I'd love to get your input on it 🙇
