### ISSUE TITLE
Admin 4-minute renew-token is annoying, disruptive and causes data loss

### ISSUE THREAD

**Issue by CodeToTee** [strapi/strapi#22519]
## Bug report
After a recent upgrade to 5.6.0, I noticed then when I'm in the middle of making content updates in the admin panel, every four minutes, the screen will refresh and all data I've enter (without saving) is lost.  It's very annoying and causing considerable disruption and loss of time.  The renewal time-period feels too invasive.

### Required System information
- Environment: development
- OS: darwin-x64
- Strapi Version: 5.6.0
- Node/Yarn Version: yarn/4.5.3 npm/? node/v22.12.0 darwin x64
- Edition: Community
- Database: mysql

### Describe the bug
Admin panel issues a POST to /renew-token every 4 minutes, which causes a screen refresh, which discards any unsaved changes.

### Steps to reproduce the behavior
1. Go to admin panel
2. Open some collection with an input field
3. Type in some changes to a field
4. Wait 4 minutes for the POST /renew-token to be issued
5. Screen refreshes and input is lost

### Expected behavior
Renew token should not discard all input data.

**Comment by pawelhoros** [comment]
5.6.0, unable to confirm. 
No token renewal for about 15 minutes or more, no page refresh. 
Default config, no custom user & permission plugin settings (jwt).

**Comment by CodeToTee** [comment]
Thanks for checking.  I'm going to close this, as for some unknown reason I'm no longer seeing this issue either.  I didn't upgrade anything, but it seems to have gone away.  Perhaps a system restart I did cleared the issue.  If I see this again, I'll let you know.  Thank you for testing.

**Comment by derrickmehaffy** [comment]
We don't even have a route built into Strapi for that, my guess, this is either a custom endpoint or something from a plugin. The tokens we issue by default have an expiration of 30 days.

**Comment by CodeToTee** [comment]
FWIW, I do see the link in the [admin panel source](https://github.com/strapi/strapi/blob/146a31b564bc8232686331f6b28f7ff966817963/packages/core/admin/server/src/routes/authentication.ts#L12).

I figured out how to replicate the issue.  When I have the admin panel open in two different browsers, I see the renew-token API being hit every four minutes.  In my case, I'm using Safari and Chrome.  If I close one of the windows, the problem goes away.  This probably isn't a supported case.

**Comment by derrickmehaffy** [comment]
> FWIW, I do see the route in the [admin panel source](https://github.com/strapi/strapi/blob/146a31b564bc8232686331f6b28f7ff966817963/packages/core/admin/server/src/routes/authentication.ts#L12).
> 
> I figured out how to replicate the issue.  When I have the admin panel open in two different browsers, I see the renew-token API being hit every four minutes.  In my case, I'm using Safari and Chrome.  If I close one of the windows, the problem goes away.  This probably isn't a supported case.
> 
> 

How nice find, I was searching through the codebase and didn't see that. 🤔

**Comment by derrickmehaffy** [comment]
I am curious on why it would be hitting it though.

**Comment by CommandString** [comment]
I am facing this issue myself actually. I'm currently on 5.7.0 and have checked the docs for any information on the ability to change this to no avail.

**Comment by CodeToTee** [comment]
Do you have two browser tabs open on the admin panel?  That's the only time I see this issue.  In my case, the two tabs were on different browsers (i.e. Safari and Chrome).

**Comment by CommandString** [comment]
Nope, only using chrome.

**Comment by SaschaNanny** [comment]
I have the same issue. I have two tabs open with Strapi but one is the productive environment and the other my local dev, so that would be weird if that has anything to do with the problem. I waited for the refresh to happen and this is from my dev tools network tab > initiator:

![Image](https://github.com/user-attachments/assets/b750310b-97a4-4aac-b9a6-8c01a6a46fe3)

So maybe a project specific problem where Vite refreshes the page? I think maybe this is related: https://stackoverflow.com/questions/72527929/vite-keeps-refreshing-the-entire-page

**Comment by CommandString** [comment]
Hmm, I know for me it just went away. I'm not sure what it was, I had a *separate* project that used Vite. However, I don't think that would've affected Strapi? At least it's gone now.

**Comment by semiaddict** [comment]
I had a similar issue with the strapi admin refreshing every 60 seconds or so.
I was running another vite project in dev mode on another port, and the problem stopped as soon as I stopped the other project.
The refreshes coincided with web socket messages sent by vite from the other project. So I guess it's more of a vite issue here; at least in my case.

**Comment by CommandString** [comment]
That actually makes a lot of sense @semiaddict

**Comment by CodeToTee** [comment]
Interesting observation.  I also have a second (unrelated) Vite project running, and that was also true when I originally saw this issue.  At that time (in the other project), I was using Vite version 5.2.10.  I've since upgraded Vite and Strapi on both projects, and avoided keeping two Strapi admin panels open, and have not seen the issue.
