### ISSUE TITLE
Just updated from 5.4.2 to 5.6.0 and got this "Invalid key title at localizations.booking_form.fields" , it work well on 5.4.2

### ISSUE THREAD

**Issue by fathurayana** [strapi/strapi#22517]
## Bug report
Hi guys i just updating my Strapi from 5.4.2 to 5.6.0 ,
i start seeing this error on my collection types that have booking_form.fields , it never happen on 5.4.2

> {
>     "data": null,
>     "error": {
>         "status": 400,
>         "name": "ValidationError",
>         "message": "Invalid key title at localizations.booking_form.fields",
>         "details": {
>             "key": "title",
>             "path": "localizations.booking_form.fields"
>         }
>     }
> }

i believe there is no schema related changes from 5.4.2 to 5.6.0 , and i use the same database.

here is the JSON and interface for my form builder and the fields

form-builder.json
`{
  "collectionName": "components_booking_form_form_builders",
  "info": {
    "displayName": "Form-builder",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "description_top": {
      "type": "text",
      "required": true
    },
    "cta_copy": {
      "type": "string",
      "default": "Continue"
    },
    "fields": {
      "type": "component",
      "repeatable": true,
      "component": "booking-form.field"
    },
    "description_bottom": {
      "type": "text"
    },
    "chat_department": {
      "type": "string",
      "required": false
    }
  }
}
`

field.json
`{
  "collectionName": "components_booking_form_fields",
  "info": {
    "displayName": "Field",
    "description": ""
  },
  "options": {},
  "attributes": {
    "field_title": {
      "type": "string",
      "required": true
    },
    "field_placeholder": {
      "type": "text",
      "required": true
    },
    "field_type": {
      "type": "enumeration",
      "enum": [
        "SHORT_ANSWER",
        "PARAGRAPH",
        "DATETIME",
        "SINGLE_CHOICE",
        "MULTIPLE_CHOICE"
      ],
      "required": true
    },
    "mandatory": {
      "type": "boolean",
      "required": true
    },
    "datetime_timeslot": {
      "type": "text"
    },
    "choices_list": {
      "type": "text"
    },
    "field_helper": {
      "type": "string"
    }
  }
}`

`export interface BookingFormField extends Struct.ComponentSchema {
  collectionName: 'components_booking_form_fields';
  info: {
    description: '';
    displayName: 'Field';
  };
  attributes: {
    choices_list: Schema.Attribute.Text;
    datetime_timeslot: Schema.Attribute.Text;
    field_helper: Schema.Attribute.String;
    field_placeholder: Schema.Attribute.Text & Schema.Attribute.Required;
    field_title: Schema.Attribute.String & Schema.Attribute.Required;
    field_type: Schema.Attribute.Enumeration<
      [
        'SHORT_ANSWER',
        'PARAGRAPH',
        'DATETIME',
        'SINGLE_CHOICE',
        'MULTIPLE_CHOICE',
      ]
    > &
      Schema.Attribute.Required;
    mandatory: Schema.Attribute.Boolean & Schema.Attribute.Required;
  };
}

export interface BookingFormFormBuilder extends Struct.ComponentSchema {
  collectionName: 'components_booking_form_form_builders';
  info: {
    description: '';
    displayName: 'Form-builder';
  };
  attributes: {
    chat_department: Schema.Attribute.String;
    cta_copy: Schema.Attribute.String & Schema.Attribute.DefaultTo<'Continue'>;
    description_bottom: Schema.Attribute.Text;
    description_top: Schema.Attribute.Text & Schema.Attribute.Required;
    fields: Schema.Attribute.Component<'booking-form.field', true>;
    title: Schema.Attribute.String & Schema.Attribute.Required;
  };
}`

i just realize the error is come from this line on validatePopulate() on @strapi/utils/dist/index.js
` if (includes?.populate?.includes("nonAttributesOperators")) {
            throwInvalidKey({ key, path: path.attribute }, "validatePopulate5");
          }`

### Required System information

- Node.js version: 18
- NPM version: 10
- Strapi version: 5.6.0
- Database: postgres
- Operating system: linux
- Is your project Javascript or Typescript: javascript

### Steps to reproduce the behavior

1. Go to content manager
2. Click on collection types that have booking form fields

### Expected behavior

- the list of data should be displayed

**Comment by fathurayana** [comment]
just found the solution for this issue , 
just change the name of "fields" properties on form-builder.json , 
i think the strapi team should consider adding "fields" to reserved keywords on their documentation

**Comment by cesosag** [comment]
I had a similar issue when upgrading from 5.3.0 to 5.9.0. In my case I had some components that had `"private": true` in some of their `"attributes"` in the model. According to the documentation that should be valid, but apparently it is not for components. Might this be a bug?

**Comment by thematrixdev** [comment]
My code suddenly does not work.

This is the `POST` body:
```
{
Event: { set: [ 'walw2vy6y4sc2ol1uhbp1voy' ] },
Location: { set: [ 'zv6omnsbtbfww11ml20tmbu7' ] },
TicketTier: { set: [ 'qqp02ar20rbm7lnspha9p2rr' ] },
Verifications: { set: [ 'cn2lqab8gufbak31ybvlg1yl', 'r4c3nttcd6dhokt8fv5m4en7' ] },
DateTime: 2024-12-31T03:00:00.000Z,
FirstName: '',
LastName: '',
CountryCode: '',
Phone: '',
Email: '',
DirectMarketing: true,
TermsAndConditions: true
}
```

I have got this error:
```
{
	"data": null,
	"error": {
		"status": 400,
		"name": "ValidationError",
		"message": "Invalid key Event",
		"details": {
			"key": "Event",
			"path": "Event",
			"source": "body"
		}
	}
}
```

The key should exist in the content-type:
```
{
  kind: 'collectionType',
  collectionName: 'registrations',
  info: {
    singularName: 'registration',
    pluralName: 'registrations',
    displayName: 'Registration',
    description: ''
  },
  options: { draftAndPublish: false },
  pluginOptions: {},
  attributes: {
    Event: {
      type: 'relation',
      relation: 'manyToOne',
      target: 'api::event.event'
    },
    TicketTier: {
      type: 'relation',
      relation: 'manyToOne',
      target: 'api::ticket-tier.ticket-tier',
      inversedBy: 'Registrations'
    },
    Location: {
      type: 'relation',
      relation: 'manyToOne',
      target: 'api::location.location',
      inversedBy: 'Registrations'
    },
    DateTime: { type: 'datetime' },
    FirstName: { type: 'string', required: true, pluginOptions: {} },
    LastName: { type: 'string', required: true, pluginOptions: {} },
    CountryCode: { type: 'string', required: true, pluginOptions: {} },
    Phone: { type: 'string', required: true, pluginOptions: {} },
    Email: { type: 'email' },
    TermsAndConditions: { type: 'boolean', required: true, pluginOptions: {} },
    DirectMarketing: { type: 'boolean', required: true, pluginOptions: {} },
    QRCode: { type: 'text' },
    Messages: {
      type: 'relation',
      relation: 'oneToMany',
      target: 'api::message.message',
      mappedBy: 'Registration'
    },
    Verifications: {
      type: 'relation',
      relation: 'oneToMany',
      target: 'api::verify.verify',
      mappedBy: 'Registration'
    },
    CheckInDateTime: { type: 'datetime' },
    createdAt: { type: 'datetime' },
    updatedAt: { type: 'datetime' },
    publishedAt: {
      type: 'datetime',
      configurable: false,
      writable: true,
      visible: false,
      default: [Function: default]
    },
    createdBy: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'admin::user',
      configurable: false,
      writable: false,
      visible: false,
      useJoinTable: false,
      private: true
    },
    updatedBy: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'admin::user',
      configurable: false,
      writable: false,
      visible: false,
      useJoinTable: false,
      private: true
    },
    locale: {
      writable: true,
      private: true,
      configurable: false,
      visible: false,
      type: 'string'
    },
    localizations: {
      type: 'relation',
      relation: 'oneToMany',
      target: 'api::registration.registration',
      writable: false,
      private: true,
      configurable: false,
      visible: false,
      unstable_virtual: true,
      joinColumn: [Object]
    }
  },
  apiName: 'registration',
  globalId: 'Registration',
  uid: 'api::registration.registration',
  modelType: 'contentType',
  __schema__: {
    collectionName: 'registrations',
    info: {
      singularName: 'registration',
      pluralName: 'registrations',
      displayName: '03 Registration',
      description: ''
    },
    options: { draftAndPublish: false },
    pluginOptions: {},
    attributes: {
      Event: [Object],
      TicketTier: [Object],
      Location: [Object],
      DateTime: [Object],
      FirstName: [Object],
      LastName: [Object],
      CountryCode: [Object],
      Phone: [Object],
      Email: [Object],
      TermsAndConditions: [Object],
      DirectMarketing: [Object],
      QRCode: [Object],
      Messages: [Object],
      Verifications: [Object],
      CheckInDateTime: [Object]
    },
    kind: 'collectionType'
  },
  modelName: 'registration',
  actions: {},
  lifecycles: {}
}
```

**Comment by thematrixdev** [comment]
I have found the cause of my issue.
It is due to the permission configuration of the API token.
`Registration` `create` is permitted.
However, `Event` (etc.) has no permission.
Granting `find` on `Event` solves the "invalid key" issue.

**Comment by ddsdevelopers** [comment]
I’m facing a similar issue. I have two collections: Group and Item, connected via a one-to-many relationship (Group → Item).

In the Public role, I’ve only enabled `findOne` for Group, and `create` and `findOne` for Item.

The problem arises when a public user tries to POST a new Item and includes the `documentID` of the Group they want to associate it with, Strapi returns the `Invalid key Group` error.

The error disappears if I enable the `find` permission for the Group collection for Public role. However, since the user already has the Group `documentID`, this shouldn't be necessary.

My workaround was to enable the `find` permission in the Public role but modify the Group controller to return nothing unless the user is authenticated. This way, the error doesn't show, but the data is still protected.

**Comment by EstebanPiacentino** [comment]
I’m facing a similar issue. I have two collections: Group and Item, connected via a one-to-many relationship (Group → Item).

In the Public role, I’ve only enabled `findOne` for Group, and `create` and `findOne` for Item.

The problem arises when a public user tries to POST a new Item and includes the `documentID` of the Group they want to associate it with, Strapi returns the `Invalid key Group` error.

The error disappears if I enable the `find` permission for the Group collection for Public role. However, since the user already has the Group `documentID`, this shouldn't be necessary.

My workaround was to enable the `find` permission in the Public role but modify the Group controller to return nothing unless the user is authenticated. This way, the error doesn't show, but the data is still protected.

**Comment by IvanAdmaers** [comment]
Strapi 5.16.1 and this issue is still actual

In my case this error happens when I change a field in my component to private
