### ISSUE TITLE
Error file url, no access url

### ISSUE THREAD

**Issue by narule** [strapi/strapi#22534]
I think this is a great tool, but there is one resource access issue that is not practical enough. 

I use S3 to upload files. Directus has implemented the control of public or private resource access by configuring ACL parameters, but the images in the Directus system are proxied and it is not convenient to obtain the image access URL. 

And when adding uploaded images to the rich text editor, the URL is local instead of the public access path of Digitalocean. 
Including inserting images in the markdown rich text editor will cause image path errors and access failures.
![image](https://github.com/user-attachments/assets/7f8ab7af-6dfa-46be-8a7d-d08a8b006760)

**Comment by derrickmehaffy** [comment]
If you are using local upload you need to set the url in the server config. If you use a 3rd party provider it'll get the absolute url from the 3rd party
