### ISSUE TITLE
The FE crashes when going through the content types

### ISSUE THREAD

**Issue by dannydtk** [strapi/strapi#2253]
**Informations**
- **Node.js version**: 10.12.0
- **npm version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.14.4.0
- **Database**: MongoDB 4.0.3
- **Operating system**: macOS Mojave 10.14.1

**What is the current behavior?**
The app crashes when viewing the content types. Refreshing the page fixes the issue.
Screen recording: https://streamable.com/udfwa

**Steps to reproduce the problem**
See the recording posted above.
1. Create a new app.
2. Add a content type.
3. View the content type.
4. The page doesn't load with an error in the console.

**What is the expected behavior?**
The app shouldn't crash.

**Suggested solutions**
-

**Comment by lauriejim** [comment]
Can you try to remove in your DB `core_store` > key: `plugin_content-manager_schema`

**Comment by soupette** [comment]
I'm going to need more info do you have a repo to share?

**Comment by dannydtk** [comment]
> I'm going to need more info do you have a repo to share?

@soupette [https://github.com/dannydtk/barn-io-be](https://github.com/dannydtk/barn-io-be) - not much has been done there.

**Comment by soupette** [comment]
@dannydtk I manage to reproduce the bug.

I have found a way to fix it, you can make the following changes :
**Path -**: `./plugins/content-manager/admin/src/components/TableRow`

```
getDisplayedValue: (type, value, name) {
  if (!value) {
    return '-';
  }
 
  // ...
}
```
Then you'll just need to run `npm run setup --plugins` at the root of your app.
