### ISSUE TITLE
Use mongoose plugins

### ISSUE THREAD

**Issue by wemod123** [strapi/strapi#2257]
**Informations**

**Node.js** version: v10.13.0
**npm version:** 6.4.1
**Strapi version:**
**Database:** MongoDB
**Operating system:** Windows

**A general question:**
There are many powerful mongoose plugins, which may improve coding experience significantly, especially who are used to it.  "mongoose-mpath" plugin for example.

is that possible we integrate it in a simple way in case we use the mongoose connection?

**Comment by mtmsuhail** [comment]
I think strapi used mongoose with some custom functionalities that have devoloping and maintaining with strapi. If you want to use any other plugin you may required to alter core functionalities. Or you can also try for side by side with both.

**Comment by wemod123** [comment]
@mtmsuhail, correct.
When I look into the module 'strapi-hook-mongoose', there was integration with mongoose in a way, and plugin to mongoose can be implemented just as what need be done as with only mongoose.
So simply say, we can use mongoose plugins within 'strapi-hook-mongoose'.
While I think further issues of this kind of integration need be tested case by case.

**Comment by lauriejim** [comment]
Hello @wemod123 , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by Aurelsicoko** [comment]
We should expose the Mongoose connection initialized in the hook `strapi-mongoose`, so we'll be able to apply plugin in the `bootstrap.js` files.

For example, we have a similar system for Bookshelf which requires a `bookshelf.js` inside the `./config/functions` folder (see https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/index.js#L57).

It lets us create a `bookshelf.js` like this to load plugins. We could certainly do something like that for Mongoose too.
```js
'use strict';

const _ = require('lodash');
const softDelete = require('bookshelf-paranoia');
const cacheRedis = require('bookshelf-cache-redis');

/**
 * This gives you the opportunity to customize your Bookshelf instance.
 * For example, this file is very helpful to add plugins.
 */

module.exports = (bookshelf, connection) => {
  try {
    bookshelf.plugin(softDelete);
    bookshelf.plugin(cacheRedis, {
      instance: Redis,
      disabled: true
    });
  } catch (err) {
    console.error(err);
  }
};
```

**Comment by lauriejim** [comment]
Same type of issue with bookshelf https://github.com/strapi/strapi/issues/2030

**Comment by jacargentina** [comment]
So, currently it is not possible to use any mongoose plugin, right? @lauriejim i can make a PR to work on this if you like

**Comment by jacargentina** [comment]
@Aurelsicoko after the PR, I went and looked on the plugin I'm trying to use

```
var random = require('mongoose-simple-random');
 
var s = new Schema({
  message: String
});
s.plugin(random);
 ```

It seems in this plugin type it should be applied to the `Schema`, not the connection. So, besides the already done PR which can serve other purposes, plugins, etc... maybe there should be another hook after schemer are built, and allow putting schema plugins there, right?

**Comment by Aurelsicoko** [comment]
Awesome! Great job @jacargentina 👍

**Comment by qivhou** [comment]
@jacargentina  @lauriejim Any idea on plugin specified for only one Schema (Content Type), for example [mongoose-mpath](https://www.npmjs.com/package/mongoose-mpath),  which for tree structure, seems current plugin works for global. 

BTW.
Thanks for your awesome work!

**Comment by lauriejim** [comment]
Hello @qivhou !
You can find documentation here https://strapi.io/documentation/3.x.x/configurations/configurations.html#functions
to customise your mongoose connection.

**Comment by gtamas** [comment]
@lauriejim 
@qivhou 
@Aurelsicoko 

The above link doesn't contain information about how to register a plugin with a single Schema.
Is it even possible to alter the schemas in this function?

I would like to register mongoose-delete plugin, but only with one of my models. How do I do that?

**Comment by cube-dan** [comment]
@gtamas 

Updated link [for this post](https://github.com/strapi/strapi/issues/2257#issuecomment-480207262) allowing you to hookup a mongoose plugin: https://strapi.io/documentation/v3.x/concepts/configurations.html#database-orm-customization

I'm unsure what you're trying to do with the mongoose-delete plugin, but maybe use a [model lifecycle hook](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks) if you want to do ops against a single model when entries are deleted? => beforeDelete(params) or afterDelete(result, params)

You might be able to get a reference to your models schema through [strapi.models](https://strapi.io/documentation/v3.x/global-strapi/api-reference.html#strapi-models)?

**Comment by periabyte** [comment]
> @lauriejim
> @qivhou
> @Aurelsicoko
> 
> The above link doesn't contain information about how to register a plugin with a single Schema.
> Is it even possible to alter the schemas in this function?
> 
> I would like to register mongoose-delete plugin, but only with one of my models. How do I do that?
> 
> I actually need to call this function:
> 
> https://mongoosejs.com/docs/api/schema.html#schema_Schema-plugin
> 
> But how do I obtain a reference to the schema? Only a Mongoose instance appears to be passed and some custom connection object.

did you find a solution for this?
