### ISSUE TITLE
Replacing /admin with a different route for production results in endless loading. 

### ISSUE THREAD

**Issue by pauldariye** [strapi/strapi#2259]
**Informations**
- **Node.js version**: v11.0.0
- **npm version**: v6.4.0
- **Strapi version**: 3.0.0-alpha.14.4.0 
- **Database**: Mongo 
- **Operating system**: macOS Mojave 10.14

**What is the current behavior?**

Per the instructions in the documentation, I updated my server configuration for production only to get a loading screen that just keeps loading.
<img width="1326" alt="screen_shot_2018-11-03_at_11_57_43" src="https://user-images.githubusercontent.com/3650761/47954479-ccc33600-df60-11e8-833c-3a08cdcfb0f5.png">

**Steps to reproduce the problem**

1. Follow [instructions here](https://strapi.io/documentation/3.x.x/guides/deployment.html) and update admin path to `/dashboard`. 
2. Deploy to a production environment (I'm using heroku). 
4. Navigate to `/dashboard`

**What is the expected behavior?**

Per the docs, updating this improves security and should work like the default /admin

**Suggested solutions**

**Comment by soupette** [comment]
Do you have any error on the chrome console?

**Comment by pauldariye** [comment]
I'll retry this again @soupette and share any errors on the console.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by flowen** [comment]
I'm not sure but maybe this is related, when I change the 'path' variable of the admin panel in `strapi/config/environments/development/server.json` I cannot start the server. I have the same information as OP.

**Comment by petre2dor** [comment]
I can replicate this on multiple instances. 
Here is the browser console error:
```
TypeError: "e.map is not a function"

    r main.js:1
 js main.js:1
 promise callback*./admin/src/app.js/< main.js:1
 js main.js:1
 t main.js:1 
<anonymous> main.js:1 
<anonymous> main.js:1 
```

Will continue to dig into it.

**Comment by petre2dor** [comment]
If I change the `path` in `config/production/server.json` and run `NODE_ENV=production npm start` it will fail because `strapi.remoteURL` wasn't updated. After running `npm run setup` and re-starting, it works.
The curious thing that I don't get yet is that in development environment, changing the admin path works without `npm run setup`. 

 Will continue to dig into it.

**Comment by petre2dor** [comment]
@flowen @pauldariye I had the same problem because I missed one important step from the documentation: `npm run setup` 
> ⚠️ If you changed the path to access to the administration, the step #2 is required.
Was that the case for you too?

**Comment by pauldariye** [comment]
You're right @petre2dor! I just tried this and it works. when you run `npm run setup` and I've deployed it to production.

**Comment by soupette** [comment]
@pauldariye great! Can we close the issue then?

**Comment by pauldariye** [comment]
Happy to help there @soupette.

**Comment by JDoGlass** [comment]
Hello, I have this same exact problem, however, when trying to run `npm run setup` I get the message "Missing script: "setup"". When checking, the only scripts available are `develop`, `build`, and `strapi`, and I can't seem to find what the setup command is supposed to run. Any ideas on... 
1- What does the `npm run setup` command is supposed to run?
2- Why is the command not available to me? 

I thank you in advance!

**Comment by derrickmehaffy** [comment]
@JDoGlass this issue is from 3 years ago, that script hasn't existed in a longgggggg time.

Create a new bug report and completely and properly fill out the template.
