### ISSUE TITLE
403 when making PUT request /users/:id

### ISSUE THREAD

**Issue by vanpana** [strapi/strapi#2263]
Node.js version: v11.1.0
npm version: 6.4.1
Strapi version: v3.0.0-alpha.14.3
Database: MongoDB
Operating system: macOS Mojave

**What is the current behavior?**
When making a PUT request at /users/:my_id with the user's JWT as Authentication Header with correct json body, you get 403 Forbidden.

**Steps to reproduce the problem**
Create a non-admin user,  make a PUT request at /users/:id with the user's JWT as Authentication Header.

**What is the expected behavior?**
The user should update

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Check your permissions on the users plugin. I don't believe update is enabled by default on /me

**Comment by vanpana** [comment]
/me was enabled. But if I make a PUT request on /me, it gives me an error that "me" isn't an id. If I check the user update permission, one user can update another user, so that's not really the behaviour I was expecting.

**Comment by lauriejim** [comment]
`PUT /users/me` not exist.

**Comment by vanpana** [comment]
I know /users/me does not exist. I was wondering how to update an user if /:id does not work

**Comment by lauriejim** [comment]
More documentation about polices here https://strapi.io/documentation/3.x.x/guides/policies.html#how-to-create-a-policy

**Comment by geosigno** [comment]
@vanpana possible for you to share here the steps you did so you can put the data?

**Comment by mikekoro** [comment]
> `PUT /users/me` not exist.
> You will have to apply a custom policy to `PUT /users/_:id` that control `_id` is the same as `ctx.state.user._id`

Hi how do you exactly apply the new policy to that route?

I tried putting routes.json:

```

{
  "routes": [
    {
      "method": "PUT",
      "path": "/users/:id",
      "handler": "User.update",
      "config": {
        "policies": ["global.canEditProfile"]
      }
    }
  ]
}
```

under /eextensions/user-permissions/config but it doesnt get triggered

**Comment by lauriejim** [comment]
Hello! I just tried and it works well.
Here is what I did - https://www.loom.com/share/86dd38aed3ca4ebc9107ad96c44ac494

**Comment by mikekoro** [comment]
@lauriejim 
oh thats a mystery. Maybe I dont see something obvious but you have exactly what I have:

1. canEditProfile.js in config/policies/
2. routes.json in /extensions/user-permissions/config/

:((((

<img width="940" alt="Screenshot 2020-01-21 13 27 28" src="https://user-images.githubusercontent.com/2127545/72831946-da420a00-3c51-11ea-8dbb-61c711795486.png">
<img width="855" alt="Screenshot 2020-01-21 13 27 37" src="https://user-images.githubusercontent.com/2127545/72831948-da420a00-3c51-11ea-8a95-2f87da92e21e.png">

**Comment by arnespremberg** [comment]
Hey, sorry to dig this up, but in my opinion PUT endpoint at /users/me should really be implemented. Would you mind me doing a PR on this?

**Comment by lauriejim** [comment]
Hello! Here is a video to implement it in your applications 
https://www.youtube.com/watch?v=ITk-pYtOCnQ&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=3&t=0s

**Comment by fkrishna** [comment]
Hi There, I keep getting 403 error "Forbidden"  when trying to console.log a string when hitting  "PUT /users/me" endpoint
am I missing something?

<img width="1440" alt="Screen Shot 2021-01-09 at 9 30 56 PM" src="https://user-images.githubusercontent.com/26485083/104113007-687c2980-52c3-11eb-9def-594d99d8dd92.png">

<img width="1440" alt="Screen Shot 2021-01-09 at 9 32 16 PM" src="https://user-images.githubusercontent.com/26485083/104113014-6e720a80-52c3-11eb-9d7c-f7fc5b294735.png">

**Comment by derrickmehaffy** [comment]
Your routes.json extension needs to contain the full routes.json from the plugin, not just your single route.

**Comment by kansoadi** [comment]
/api/users/:id gets 403 for an Authenticated user, even if the "update" was selected for such a role
