### ISSUE TITLE
Duplicate fields

### ISSUE THREAD

**Issue by stiko** [strapi/strapi#2266]
**Informations**
- **Node.js version**: 10.11.0
- **npm version**: 6.4.1
- **Strapi version**:  v3.0.0-alpha.14.3
- **Database**: Mongo
- **Operating system**: macOS 10.14.1

**What is the current behavior?**
If I modify `models/model.settings.json` and move a field up/down, it will duplicate that field on the frontend. If I put it back to the old order it will duplicate it again. And if I remove it, it will give a white page because it's looking for that field.

**Steps to reproduce the problem**
Above ^

**What is the expected behavior?**
It should respect the `settings.json` file.

**Suggested solutions**
In the DB `core_store.plugin_content-manager_schema` I found the duplicate. This is not the first time I have to modify this value.  Can anyone please tell me at least why this happens if it's not a bug?

**Comment by soupette** [comment]
@stiko There's a PR waiting to be merged that fixes this bug #2203 you can apply the modifications directly in your project and the bug won't happen again.
