### ISSUE TITLE
Cannot edit role permissions

### ISSUE THREAD

**Issue by slecorvaisier** [strapi/strapi#2269]
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MongoDB v4.0.2
- **Operating system**: macOS v10.14

**What is the current behavior?**
While accessing to role permission edition page, the app goes full white and 2 errors appear in dev tools:
```
main.js:16 Error: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

```
uncaught at s Invariant Violation: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
 ```

**Steps to reproduce the problem**
I came across this issue while following the [Nuxt.js + Strapi tuto](https://blog.strapi.io/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-authentication-part-4-7/), and was able to configure the public permissions. My guess is it started to bug after the first user creation in step 4. Starting from this point, the public permission page has the same issue when clicking on the edit link (as for the authenticated one).

![](https://thumbs.gfycat.com/JubilantPrestigiousAmericanshorthair-size_restricted.gif)

**What is the expected behavior?**
Accessing the the edit page for the selected role

**Comment by slecorvaisier** [comment]
Can be related to #1912 as every content-builder fails the same way. 
I tried to purge the content-manager schema in the core_store, but no success.  I should add that I didn't migrate from a previous version of Strapi.

**Comment by soupette** [comment]
@slecorvaisier It's not related to #1912 can you try to rebuild your app? `npm run setup --plugins` at the root of your strapi project?

**Comment by hunterbecton** [comment]
I had the same issue @soupette, but everything is back to normal after running the `npm run setup --plugins`

**Comment by slecorvaisier** [comment]
@soupette `npm run setup --plugins` solved the problem, thank you.
I close this issue.
