### ISSUE TITLE
Generate api doc with ReDoc

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2272]
**What is the expected behavior?**

Hi,
I think if we can integrate Strapi with ReDoc it can very useful feature. :wink: 

https://github.com/Rebilly/ReDoc

**Comment by Aurelsicoko** [comment]
We will release the documentation plugin at the end of the year! Like @derrickmehaffy said, the plugin is using SwaggerUI. It automatically generates an OpenAPI file based on the models of the project.

**Comment by mnlbox** [comment]
@Aurelsicoko So please update [in progress tab in productboard](https://portal.productboard.com/strapi/tabs/5-in-progress) :wink:

**Comment by Aurelsicoko** [comment]
The plugin is already at the "Testing" stage ;)

**Comment by SalahAdDin** [comment]
@Aurelsicoko Where can we find that plugin?
