### ISSUE TITLE
Button show translate id in register page

### ISSUE THREAD

**Issue by quangchien** [strapi/strapi#2277]
**Informations**
- **Node.js version**: v9.11.1
- **npm version**: v6.4.1
- **Strapi version**: v3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: macOS High Sierra

**What is the current behavior?**
I want to enable register page and show a register button in login page to move register but I have no find it, I goto advanced settings in user permission and I have seen that the register is enabled, but it still no register button show in login page and then I open routes of user permission and I found the way to go register page is /auth/local/register, but I don't see any input fields here, only button with message id "users-permissions.Auth.form.button.local"

**Steps to reproduce the problem**
go to /auth/local/register to see error

**What is the expected behavior?**
How can I make register page work ?

![screen shot 2018-11-08 at 11 28 31 am](https://user-images.githubusercontent.com/26131959/48178030-46389b00-e34a-11e8-8efa-607b7d352331.png)

**Comment by soupette** [comment]
@quangchien the url is wrong it should be `/admin/plugins/users-permissions/auth/register` to enable the register page you will need to modify the following file:

https://github.com/strapi/strapi/blob/d377da29cab7f59e9d721eda28dd2de9e7e47715/packages/strapi-admin/admin/src/containers/AdminPage/index.js#L98-L105

**Comment by quangchien** [comment]
@soupette I see there is a hasAdminUser function so it means that the register page only work when there is no admin user. Is it correctly ? and what do I need to modify these files bro ?

**Comment by soupette** [comment]
Yes exactly!
