### ISSUE TITLE
Unable construct Graphql query for current user in production (heroku)

### ISSUE THREAD

**Issue by pauldariye** [strapi/strapi#2278]
**Informations**
- **Node.js version**: 10.11.0 
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.3 
- **Database**: Mongo
- **Operating system**:  macOS Mojave 10.14

**What is the current behavior?**
I'm trying to query the current authenticated user's profile but it keeps loading without providing any results.

This feature was implemented [here](https://github.com/strapi/strapi/pull/2116)

**Steps to reproduce the problem**

**What is the expected behavior?**

Return current user (`me`) with `query me {}`

**Suggested solutions**

**Comment by lauriejim** [comment]
This PR will be published in next version of Strapi https://github.com/strapi/strapi/pull/2116

**Comment by pauldariye** [comment]
hey @lauriejim, when is the next version of Strapi scheduled for release?

**Comment by derrickmehaffy** [comment]
@pauldariye https://github.com/strapi/strapi/projects

Release "estimates" are always on the project :smile:

**Comment by pauldariye** [comment]
Got it :D. Thanks ... Happy Thanksgiving from NY
