### ISSUE TITLE
Running the server with 'npm start' bugs when editing content-type fields

### ISSUE THREAD

**Issue by eduardotkoller** [strapi/strapi#2280]
**Informations**
- **Node.js version**:  10.8.0
- **npm version**:  6.4.0
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
Some NodeJS server providers require your start script to be `npm start`, but when you start strapi by using it, anytime you create a field on a content type, the server doesn't restart itself and then it gives you an error anytime you try to edit the content-type again until you restart it manually.

**Steps to reproduce the problem**
Create a new project using `strapi new testProject`, run the server using `npm start`, create a new content-type, add any field and save, click to edit another content-type and then click to edit your newly created content-type. It should give you a popup saying `An error ocurred.` and doesn't change the page, and only works again when you manually restart.
![image](https://user-images.githubusercontent.com/18473447/48208727-991a4e80-e35a-11e8-8573-14cd39b93fa5.png)

**What is the expected behavior?**
To restart the server automatically after editing fields on a content-type just like when you run it by using `strapi start` does

**Suggested solutions**
Node 9.0.0 (minimum required to run Strapi as in your website) comes with `npx`, and you already put strapi as a dependency on the `package.json`, so just changing the `start` script on `package.json` to `npx strapi start` worked for me.

**Note** -- Just noticed that if you use `NODE_ENV=production` you can't even change content-types. For some reason the server provider I am using doesn't set `NODE_ENV` to `production` and I stumbled on this by chance, I don't know if this should be a bug.

**Comment by lauriejim** [comment]
Hello @eduardotkoller !

Content type builder need `auto reload` feature. And it's only available on `strapi start` (https://github.com/strapi/strapi/issues/1008)
So when you create content type with `npm start` or `npx strapi start` it will fire an error (you have to restart the server).

Maybe we can display a specific message to tell `You have to restart your server`.

For production mode, when your app is in production you don't have to (1) update your server setting and (2) create new content type. That is why we block it in production.
You have to develop/create your app in dev mode and then publish it in your server.

You will find more explication in our doc and wiki.

**Comment by CKGrafico** [comment]
Please, add the message. We were 1 hour with this problem :)

**Comment by derrickmehaffy** [comment]
@CKGrafico you're welcome to submit a PR, else run strapi with `strapi start` while in development mode
