### ISSUE TITLE
Wrong Decimal/Float precision

### ISSUE THREAD

**Issue by Leo1003** [strapi/strapi#2282]
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0 (dev mode)
- **Database**: mongodb 4.0.3
- **Operating system**: Archlinux
- **mongoose version**: 5.3.8
- **mongoose-float**: 1.0.2

**What is the current behavior?**
Decimal: 3.14159265358979
Float: 3.14159265358979

**Steps to reproduce the problem**
Create a content type containing a decimal and a float
Fill both with pi = 3.1415926535897932384626
The result in admin panel is not correct...

**What is the expected behavior?**
Decimal: 3.14 **(Only two digits precision)**
Float: 3.14159265358979

**Suggested solutions**
This issue was discovered when I trying to fix #2251 
Because mongoose-float will set the schema types when loadType() is called, actually there is only one float type exists in the mongoose instance's schema types. Therefore, both Decimal and Float would point to the the last type set by mongoose-float (Currently Float). 

I have no idea how to fix this (submit PR), so I open this issue.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko I believe this is related to: https://github.com/strapi/strapi/issues/1330 in some way, I'm not sure how mongo handles accuracy for decimal/float

**Comment by Leo1003** [comment]
Maybe I can do this. But I don't know when can I complete it.
