### ISSUE TITLE
An error occurd on upload page

### ISSUE THREAD

**Issue by masehitam** [strapi/strapi#2288]
**Informations**
- **Node.js version**: v11.1.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: OSX

**What is the current behavior?**
I got this error message on upload page, and the list images that I've upload empty, even though I have uploaded several pictures 
<img width="1440" alt="strapi - files upload 2018-11-11 16-05-22" src="https://user-images.githubusercontent.com/16290327/48311074-3f20bf80-e5cc-11e8-9a7b-dfd4708a3dd1.png">

**Comment by lauriejim** [comment]
Hello @masehitam 

Did you use the default provider (upload on your local machine) ?
Did you have error logs ?

Need more informations.

**Comment by masehitam** [comment]
yes it's fresh install

but when I tried to create new project, error is gone.

I am sorry, I can't give you another information
