### ISSUE TITLE
Error occurs when the field only consists of json input

### ISSUE THREAD

**Issue by masehitam** [strapi/strapi#2289]
**Informations**
- **Node.js version**: v11.1.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: OSX

**What is the current behavior?**
<img width="1440" alt="never ending" src="https://user-images.githubusercontent.com/16290327/48311700-5f557c00-e5d6-11e8-873a-aef22f4f0c1d.png">

**Steps to reproduce the problem**
when input field is only JSON input

**What is the expected behavior?**
showing json input only

**Comment by lauriejim** [comment]
Please check open issue about your load error.
Check your chrome console. I'm sure your issue already exist.
