### ISSUE TITLE
Can not use(or request) retryable writes with multi=true

### ISSUE THREAD

**Issue by sravanireddyl** [strapi/strapi#2291]
**Informations**
- **Node.js version**:  v8.10.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.11.2 
- **Database**: MongoDB
- **Operating system**: windows

**What is the current behavior?**
When I use multiple true for update query , throwing error as follows :
can not use(or request) retryable writes with multi=true

**Steps to reproduce the problem**

**What is the expected behavior?**
It should update multiple records in DB

**Suggested solutions**
This issue got fixed in latest  MongoDB native driver version . But strapi still using 3.0.4.

**Comment by lauriejim** [comment]
Hello @sravanireddyl 

Can you precise your issue. Need more information. I don't understand what you did.

**Comment by sravanireddyl** [comment]
> Hello @sravanireddyl
> 
> Can you precise your issue. Need more information. I don't understand what you did.

I am using mongo update query to update multiple records at a time (with multi=true option).
And also using **retrywrites** option in database.json in the db connection uri.

When i use these two options together (retrywrites and multiple update) am getting error as 
**can not use(or request) retrywrites with multi=true**

**Comment by lauriejim** [comment]
Can you provide line of code.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
