### ISSUE TITLE
Ignore public/uploads directory in git

### ISSUE THREAD

**Issue by yann-yinn** [strapi/strapi#2293]
Hey here, Strapi is a very great experience so far , thanks for the hard work !
 
![screencapture-localhost-3000-2018-11-11-18_20_10](https://user-images.githubusercontent.com/335495/48333508-fa426a80-e657-11e8-80fb-5cc1d6497c56.png)

**What is the expected behavior?**

I'm went to the admin, added the above photos for my users fake accounts, for fun.
A then, I typed on my terminal `git add . && git commit -m "save" && git push `. 

Surprise ! my git repository has now a 12 Mo weight :D

Files uploaded by user should not be versionned by default

**Comment by lauriejim** [comment]
Hey @yann-yinn. thank you for this feedback.
Feel free tp submit a PR. Appreciate your contribution on this issue.
