### ISSUE TITLE
Workflow Feature

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2294]
**What is the expected behavior?**
Hi guys,
I think http://orchardproject.net is a great CMS for get some idea. For example it's [workflow](http://docs.orchardproject.net/en/latest/Documentation/Workflows/) feature is very attractive for me:

![screenshot from 2018-10-22 16-25-10](http://docs.orchardproject.net/en/latest/Upload/workflows/addingsendemail.PNG)

We can integrate this with web hook too.

Any other idea?

**Comment by Aurelsicoko** [comment]
Oh, is it like Zappier?

**Comment by mnlbox** [comment]
@Aurelsicoko yes something like this but I think we can implement and integrate this with webhook (visual webhook based workflow designer)

**Comment by lauriejim** [comment]
I close this issue.
It will probably be a mix between webhook and zapier.
But not managed from Strapi.
Will reopen this issue if we need more feedback.
