### ISSUE TITLE
GraphQL get objects by relation ID

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#2298]
**Informations**
- **Node.js version**:  10.8.0
- **npm version**:  6.2.0
- **Strapi version**: alpha 14.4
- **Database**: pg
- **Operating system**: windows/wsl

**What is the current behavior?**

When I define the `where` clause of a related object for the parent ID, I get wrong information for nested properties.

**Steps to reproduce the problem**

So my model `event` consists of multiple `registrations`.
I can ask either for 
1: `event(id: 6) {registrations{}}`
or for
2: `registrations(where: {event: 6}) {}`

while `event(id)` delivers the correct data, `registrations(where)` does not.

**Query 1:**
``` 
event(id: 6) {
    registrations{
        user {
            id
            username
        }
    }
}
```
**Response 1:**
```
"event": {
    "registrations": [
        {
          "user": {
            "id": "87",
            "username": "kio"
          }
        },
        {
          "user": {
            "id": "26",
            "username": "chitatz"
          }
        },
        {
          "user": {
            "id": "10",
            "username": "akiru"
          }
        },
        {
          "user": {
            "id": "56",
            "username": "famis"
          }
        }
    ]
}
```

**Query 2:**
```
registrations(where: {event: 6}) {
    id
    user {
        id
        username
    }
}
```
**Response 2:**
```
{
    "registrations": [
        {
            "id": "17",
            "user": {
                "id": "39",
                "username": "dawn"
            }
        },
        {
            "id": "18",
            "user": {
                "id": "39",
                "username": "dawn"
            }
        },
        {
            "id": "19",
            "user": {
                "id": "39",
                "username": "dawn"
            }
        },
        {
            "id": "20",
            "user": {
                "id": "39",
                "username": "dawn"
            }
        }
    ]
}
```

**What is the expected behavior?**

relation where selectors should behave as object(id) selector

**Suggested solutions**

I believe this might be sql specific, but I can't be sure.
Make sure the related objects are properly resolved, I don't know why a user is returned that is not even in the list of registrations.

**Comment by lauriejim** [comment]
Hello @MartinMuzatko It look to be fixed in last version of Strapi (alpha.16)
