### ISSUE TITLE
If GraphQL playground isn't enabled you cannot reach the graphQL endpoint

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2309]
**Informations**
- **Node.js version**: v10
- **npm version**: v6
- **Strapi version**: 14.5
- **Database**: MySQL (MariaDB 10.2)
- **Operating system**: Ubuntu 18.04 Server

**What is the current behavior?**

If you don't have the graphQL playground enabled (such as in production) the /graphql endpoint responses with `GET query missing.` And will not provide the schema to the client.

**Steps to reproduce the problem**

Start Strapi in production without the playground enabled and attempt to make a query (such as using an example graphQL client like this one: https://altair-gql.sirmuel.design/

You can use in my case my servers as an example:
Dev: https://api.canonn.tech:2083/graphql
Prod: https://api.canonn.tech/graphql

Dev works fine as playground is enabled, prod does not as it is disabled there.

**What is the expected behavior?**

GraphQL should still respond even if playground is disabled.

**Suggested solutions**

Fix routes

**Comment by derrickmehaffy** [comment]
This was using a locally installed (as in the snap package in ubuntu) version of playground testing both servers:

![image](https://user-images.githubusercontent.com/8593673/48474394-b1092c80-e7b7-11e8-9242-e52fd6b02749.png)

**Comment by mroverton1** [comment]
I think playground should have a different path than the API. How about using /graphiql/ for the playground.

**Comment by Aurelsicoko** [comment]
We are following the initial implementation made by the Apollo team. I'm not sure we should change it... 

@derrickmehaffy As I'm working on GraphQL right now, I'll try to find time to take a look at this issue too.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy There is no issue here. It works as excepted. The GraphQL endpoint is available through POST request by sending the query using the body or GET request by passing a `query` parameter.

See more details in the Apollo documentation (https://www.apollographql.com/docs/apollo-server/requests.html).

**Comment by selfagency** [comment]
I am having this same exact problem right now. I can reach GraphQL just fine locally, but in production, I get `GET query missing`, whether I `POST` or `GET` my query.

**Comment by shivashanmugam** [comment]
@selfagency It was mentiond graphql is disabled in production environment and we need to enable it by  changing `playgroundAlways` to true in `Path — ./plugins/graphql/config/settings.json.`
.
Refer here for more details https://strapi.io/documentation/3.0.0-alpha.x/guides/graphql.html#configurations
.
And unfortunately I am using 3.17.6  beta in which the file path is not present

**Comment by zeeshanaligold** [comment]
@shivashanmugam you can create settings.json file in above path **./extensions/graphql/config/settings.json**

```
{
  "endpoint": "/graphql",
  "tracing": false,
  "shadowCRUD": true,
  "playgroundAlways": true,
  "depthLimit": 7,
  "amountLimit": 100
}
```
