### ISSUE TITLE
Attempting to edit or create a user results in blank screen when using proxy

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2310]
**Informations**
- **Node.js version**: v10
- **npm version**: v6
- **Strapi version**: 14.5
- **Database**: MySQL (MariaDB 10.2)
- **Operating system**: Ubuntu 18.04 Server

**What is the current behavior?**

When using Strapi in production and you attempt to click on a user or create a new one you are given a white screen with the following error:

Edit User:
![image](https://user-images.githubusercontent.com/8593673/48476277-d9932580-e7bb-11e8-938c-0af66c976f7e.png)

Add user:
![image](https://user-images.githubusercontent.com/8593673/48476288-e6177e00-e7bb-11e8-835f-92a248a45b0f.png)

**Steps to reproduce the problem**

I think this is related to maybe the proxy? I'm unsure as this works fine in localhost, my guess is there is something wrong with CORS when using strapi in production

**What is the expected behavior?**

The Users page should load :smile: 

**Suggested solutions**

Unsure @soupette @aDEVE throughts?

**Comment by derrickmehaffy** [comment]
Worked with @soupette via slack, he is deploying a fix. Marking as resolved for now.

**Comment by merijnponzo** [comment]
Hi, sure this is fixed?
I get this blank screen of depth when edit / create a user in production

Using a digital ocean droplet,  Ubuntu 16.04.6 x64
Node v11.14.0
Npm 6.7.0
PostgreSQL 11.2

I've used derricks tutorial on seting strapi up with pm2, and proxy
https://medium.com/@derrickmehaffy/using-strapi-in-production-with-https-717af82d1445

But I started different with creating a strapi new application. 

![Schermafbeelding 2019-04-25 om 23 03 17](https://user-images.githubusercontent.com/23075300/56768526-f0986380-67ae-11e9-8339-77c47552dd4f.png)
![Schermafbeelding 2019-04-25 om 23 03 08](https://user-images.githubusercontent.com/23075300/56768527-f0986380-67ae-11e9-93c6-5ff33032e1e4.png)

**Comment by derrickmehaffy** [comment]
Related fix for Nginx Proxy with SSL: https://github.com/strapi/strapi/issues/2424#issuecomment-467851988
