### ISSUE TITLE
LDAP and CAS authentication support

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2312]
**What is the expected behavior?**
Hi guys,
I suggest to add LDAP and CAS authentication support too.
Please add new productboard card if you agree with this. :wink:

**Comment by derrickmehaffy** [comment]
I agree but this is going to be a bit tricker than normal oauth, more than likely won't happen until the provider plugins are split and use passport

**Comment by mnlbox** [comment]
@lauriejim I submit request in productboard. Can you mark that as public for voting?

**Comment by derrickmehaffy** [comment]
@mnlbox That would be @Aurelsicoko that does the product board

**Comment by Aurelsicoko** [comment]
@mnlbox I will display this card as public when there will be more than one person asking for it. Currently, you're the only one who wants this feature. I want to keep the public roadmap clear and understandable. I hope you'll understand 👍

**Comment by mnlbox** [comment]
So anyone that want this can add a :+1: to first post.

**Comment by andreoav** [comment]
@Aurelsicoko Any updates on this one? For me its a blocker to have a CMS without ldap.
Can you mark that as public for voting?

**Comment by chebanenko** [comment]
> @mnlbox I will display this card as public when there will be more than one person asking for it. Currently, you're the only one who wants this feature. I want to keep the public roadmap clear and understandable. I hope you'll understand 👍

It will be nice to add support for LDAP. I think it's very important feature for medium and large companies.

**Comment by derrickmehaffy** [comment]
I also support LDAP @Aurelsicoko.

And based on the number of 👍 on the OP I think a card needs to be added publically

**Comment by Aurelsicoko** [comment]
Go, go, go ⬇️

 https://portal.productboard.com/strapi/1-public-roadmap/c/61-ldap-and-cas-authentication-support!

**Comment by polarathene** [comment]
OpenID Connect would be good, it's a popular choice for SSO and can be supported in a generic manner, not service specific. It's been a while but last I looked into passport.js, I recall having concerns about it. 

The author has been employed by Auth0, and iirc - has refused to update Passport to support promises or async/await, keeping it with the dated callback API. Look at the commit history and you'll see bar 1-2 PRs, there's been no real development for years on the project. Most by the author are to update the README regarding sponsors, patreon accounts, adding advertisements, changing the license, etc.

**Comment by minhvn** [comment]
any update with ldap :)

**Comment by lauriejim** [comment]
Here is the item in the roadmap - https://portal.productboard.com/strapi/1-public-roadmap/c/61-authentication-providers-sso

**Comment by jmaferreira** [comment]
Is anyone working on this issue?

**Comment by derrickmehaffy** [comment]
> Is anyone working on this issue?

@jmaferreira per the roadmap this isn't planned until likely sometime in 2021. When work starts on it you will see an update here, for the time being there is no current plans on it's development just that "we want to do it"

**Comment by ayhid** [comment]
Any news on this feature yet ?

**Comment by ersenbasaransen** [comment]
This is a must have feature for enterprise environments, any update on this?

**Comment by derrickmehaffy** [comment]
Currently in development, planned release sometime in late Q4 (end of the year) or early Q1 2021

**Comment by jonatanalava** [comment]
@derrickmehaffy can users help the testing process?

**Comment by jmaferreira** [comment]
Sure!

**Comment by derrickmehaffy** [comment]
@jonatanalava we currently had a private beta for the Admin SSO as it's planned to be released in the Gold License, we don't currently have an auth method for user endpoints (REST/GraphQL) yet

**Comment by SagePacheco** [comment]
@derrickmehaffy, are there any plans for the user endpoints? Or is that completely out of scope for this? My plan is for users to login to our SPA via AD credentials. I was going to implement something myself, but I noticed this feature coming down the pipeline. Hadn't realized that it was just for the admin panel on Strapi itself.

**Comment by alexandrebodin** [comment]
Hi @SagePacheco you might be looking for this if you want to use CAS https://github.com/strapi/strapi/pull/8058 :) The code seems good to go but need to be QAed. If you want to give it a try ping the user on the PR ;)

**Comment by SagePacheco** [comment]
@alexandrebodin, thanks for the quick response! I should have specified that I use LDAP for my organization's applications. Can't say I am familiar with CAS, but I will certainly explore it! Thanks!

**Comment by alexandrebodin** [comment]
@SagePacheco  you can check this file to see the currently supported providers. packages/strapi-plugin-users-permissions/services/Providers.js among them we have auth0 which itself supports ldap so might be worth exploring too

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/ldap-authentication/3242/5

**Comment by maxim-green** [comment]
Any updates in 2024?
