### ISSUE TITLE
js file is too big for admin

### ISSUE THREAD

**Issue by vfan** [strapi/strapi#2314]
first open admin panel,8M js files without compressed will be loaded,so slow.
you need to load js dynamically and compress them

**Comment by derrickmehaffy** [comment]
Hello @vfan , please follow the issue template so we can get a better understanding about the origin of your bug.

Please update your issue.

**Comment by derrickmehaffy** [comment]
Side note not sure where you are seeing 8Mb worth of JS files:

![image](https://user-images.githubusercontent.com/8593673/48533629-87590f80-e862-11e8-92db-3d5691acec08.png)

**Comment by vfan** [comment]
> Side note not sure where you are seeing 8Mb worth of JS files:
> 
> ![image](https://user-images.githubusercontent.com/8593673/48533629-87590f80-e862-11e8-92db-3d5691acec08.png)
![2018-11-15 16-06-30](https://user-images.githubusercontent.com/1477088/48538864-8b337300-e8f0-11e8-95e3-672382545906.png)

**Comment by derrickmehaffy** [comment]
@vfan update your OP with version information, it honestly looks like you are running an older version with the size of those main.js files. They should be about half that:

![image](https://user-images.githubusercontent.com/8593673/48541171-48828400-e879-11e8-807f-123471f82567.png)
