### ISSUE TITLE
How to retrieve the knex function when using strapi-hook-knex, strapi-hook-bookshelf

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#2317]
**What is the expected behavior?**
I expect execute complex queries through the knex function:

How can I retrieve the knex function from the context to execute queries like this one:
```
const myModels = await MyModel.forge()
  .query(qb => {
    qb.select(knex.raw('EXTRACT(MONTH FROM ??)', 'lastPaymentDate'))
    qb.select(knex.raw('count(??)', 'lastPaymentDate'))
    qb.groupBy(knex.raw('EXTRACT(MONTH FROM ??)'), 'lastPaymentDate'))
  })
  .fetch()
```
my connection configuration is as follow: "connector": "strapi-hook-bookshelf",
and importing the knex module doesn't suppose to be a good practice
> const knex = require('knex');

my project includes: 
* strapi-hook-knex
* strapi-hook-bookshelf

Thank you in advance.

**Comment by lauriejim** [comment]
In you `./config/functions/bootstrap.js` log `strapi.connections` you will find all functions you need.

**Comment by danielocampo2** [comment]
@jmchza Hi, have you figured out how to do this? 
I tried logging strapi.connections and I see that there is a raw function, but I get qb.raw is not a function. Also tried with qb.knex with no success.

Thanks.

**Comment by lauriejim** [comment]
Hello! since we released `beta` version of strapi, you can get the collection with `strapi.query('MyModel`).model`

**Comment by danielocampo2** [comment]
Hi @lauriejim, thanks for your answer. Sorry, maybe I wasn't clear. I can get the collection and execute queries with bookshelf, but I am not being able to execute a raw query (I need to do a complex query that I can't do otherwise).
And qb.raw or qb.knex don't seem to be working.

So my question would be how to execute a raw query through knex / bookshelf.

Thanks!

**Comment by lauriejim** [comment]
Here is how to access the raw function.
I recorded it for you https://www.loom.com/share/17a714f8b7fa4ab48c05faeb140486a4

**Comment by chanhnv91** [comment]
Hi @lauriejim, How can I pass parameters into native sql using knex in strapi
My codes:
const myId = 78;
const res = await strapi.connections.default.raw('select * from notifications where id 
                                                                                     =`${myId}`');
return res;

>>res = undefined

**Comment by brookskindle** [comment]
@lauriejim would it be possible to re-upload the recording, or write down how to do this? The linked recording returns a 404 page for me. Thanks in advance!

**Comment by lucascherifi** [comment]
@lauriejim would it be possible to re-upload the recording ? Thanks in advance!

**Comment by brookskindle** [comment]
I figured out how to access the knex object for raw queries. This is what my `config/functions/bootstrap.js` file looks like, though it should work anywhere you have access to the `strapi` global object.

```js
module.exports = async () => {
  const knex = strapi.connections.default
  const result = await knex.raw('SELECT * FROM my_table LIMIT 2')
  console.log(result.rows)
}
```
gives me
```js
[
  {
    id: 1,
    created_at: 2020-08-11T18:37:03.683Z,
    updated_at: 2020-09-16T18:11:39.824Z,
    ...
  },
  {
    id: 2,
    created_at: 2020-08-11T18:37:03.683Z,
    updated_at: 2020-09-16T18:11:39.826Z,
    ...
  }
]
```

For context, I'm running strapi `3.0.5` (2020-06-23, [release](https://github.com/strapi/strapi/releases/tag/v3.0.5))

**Comment by lauriejim** [comment]
Thank you, that's it. I'm locking the issue.
