### ISSUE TITLE
Enhance pre-commit hook with Prettier

### ISSUE THREAD

**Issue by bohdan-shulha** [strapi/strapi#2321]
**Steps to reproduce the problem**
Navigate to different files of the project, look at endless lines and inconsistent code.

**What is the expected behavior?**
The code looks clean and neat ;)

**Suggested solutions**
Use [Prettier](https://prettier.io) to automatically format the source code and maintain consistency. It would require one extra large commit to fix the styling or it can be done incrementaly as the source code evolves.

**Comment by soupette** [comment]
I'm closing this issue since [Husky](https://www.npmjs.com/package/husky) has been added to the repository.
