### ISSUE TITLE
Dashboard for content contributors only

### ISSUE THREAD

**Issue by maxime1992** [strapi/strapi#2322]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

As an admin I can create update remove edit content types, add plugins etc.
But as an admin I'm the one taking care of the architecture, not the one supposed to write the content.

I'd like to be able to give access to `contributors` as a new role permission, and those people should be able to access the admin dashboard (or just a dedicated panel) where they can only edit the content, not the plugins, content types or anything admin related.

**Comment by derrickmehaffy** [comment]
Duplicate: https://portal.productboard.com/strapi/c/8-administrators-roles-permissions

**Comment by derrickmehaffy** [comment]
@lauriejim recommend closing issue

**Comment by lauriejim** [comment]
Correct @derrickmehaffy .
