### ISSUE TITLE
Auto-reload does not work when adding new files. 

### ISSUE THREAD

**Issue by donaldr** [strapi/strapi#2326]
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: Mongo
- **Operating system**: Alpine

Auto-reload does not work when adding new files. For example, running strapi generate:api hello does not cause a reload in development mode.

**Comment by derrickmehaffy** [comment]
@donaldr are you running it with `strapi start`?

To be honest you really shouldn't be using the generate command while the server is running, it isn't really designed for that (other than when Strapi itself calls that function)

**Comment by derrickmehaffy** [comment]
Also just a heads up `Strapi version: 3.0.0-alpha.14.4.0` Issues created here should be running the latest version to get any real support. Issues created with an older version are going to be closed until testing is done on the latest.

See the following note in the issue template:

```
<!-- =============================================================================== -->
<!-- ⚠️ If you are not using the current Strapi release, you will be asked to update. -->
<!-- Please see the wiki for guides on upgrading to the latest release. -->
<!-- =============================================================================== -->
```

**Comment by donaldr** [comment]
I'll update to the latest and test but the behavior will be the same as the code in strapi-start.sh hasn't changed. 

I'm create a development docker instance and would prefer not to have to restart the docker instance when developing. You're already restarting when modifying files just not when adding them. I'm wondering if this functionality got dropped when switching from forever-monitor to using fs. 

I fixed the issue by having fs watch the directories for "rename" (i.e. file creation) events:

Changed restart code within the setFilesToWatch function in start-start.sh from:
```
          const filePath = `${src}/${file}`;
          if (fs.statSync(filePath).isDirectory()) setFilesToWatch(filePath);
          else fs.watchFile(filePath, () => restart(filePath));
``

to:
```
          const filePath = `${src}/${file}`;
          if (fs.statSync(filePath).isDirectory()) {
            setFilesToWatch(filePath);
            fs.watch(filePath, eventType => eventType == "rename" && restart(filePath));                                                                                    
          }
          else {
            fs.watchFile(filePath, () => restart(filePath));
          }
```

This might not be the best solution as there are two watches going on. Is restart being called twice in quick succession when a file is deleted? Possibly. 

In general, I don't think using fs manually is a good idea for this given cross-platform issues. I would look at chodikar as a wrapper for cross-platform fs functionality.

**Comment by derrickmehaffy** [comment]
```
I'll update to the latest and test but the behavior will be the same as the code in strapi-start.sh hasn't changed.
```

I understand your concern there, that bit was added as blanket "no more of this" on people submitting issues for Strapi versions a good 3 or 4 behind on bugs that were already fixed. Hence the change, it isn't directly aimed at your issue.

Trying to make @lauriejim 's life easier :stuck_out_tongue:

**Comment by donaldr** [comment]
Verified on 3.0.0-alpha.14.5

**Comment by lauriejim** [comment]
Hello @donaldr , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
Fixed in this PR https://github.com/strapi/strapi/pull/2967

**Comment by max-ivaneychyk** [comment]
try it https://github.com/strapi/strapi/issues/1008#issuecomment-489678542
