### ISSUE TITLE
Creating custom content type fields (Dynamic)? 

### ISSUE THREAD

**Issue by StefKors** [strapi/strapi#2328]
I'm looking to use an application like Strapi for buliding custom / interactive articles. Is it possible to have a more dynamic content fields system?

Like a system where it's possible to dynamically change the order of text, image, data, video ect (possibly code) to build an article post?

Would it be possible to build a plugin like that? or is the Content type builder a quite rigid system?

**Comment by derrickmehaffy** [comment]
@StefKors Strapi is built to be a headless CMS. It's goal is to just provide a restAPI and a GraphQL API.

That is a bit outside the scope of what strapi is designed to do. Most of that should be handled by your frontend.

**Comment by derrickmehaffy** [comment]
You're welcome to request the feature on the product board if you want (please update your original post to follow the feature request template)

https://portal.productboard.com/strapi/tabs/2-under-consideration/submit-idea

**Comment by derrickmehaffy** [comment]
```
<!-- ⚠️ If you do not respect this template your issue will be closed. -->

<!-- ⚠️ Make sure to browse the opened and closed issues before submitting your issue. -->

<!-- 
Please also submit your idea on the Strapi Product Board:
https://portal.productboard.com/strapi/tabs/2-under-consideration/submit-idea

If your request on the product board is accepted this feature request issue will be closed,
but will still accept public discussion.
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by StefKors** [comment]
Thanks for the info!
