### ISSUE TITLE
How do I compile my plug-ins to my build folder(e.g  rootproject/plugins/content-manager/builder)? Who can help me?

### ISSUE THREAD

**Issue by halower** [strapi/strapi#2330]
`npm run setup` only rebuild the main project ,but plugins ？

**Comment by donaldr** [comment]
npm run setup:build

**Comment by halower** [comment]
$ npm run setup:build
npm ERR! missing script: setup:build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-19T12_47_07_463Z-debug.log

**Comment by derrickmehaffy** [comment]
@halower check your package.json if you don't see that script then you aren't in a `--dev` project. In order to build plugins/modify the adminUI you need to use a --dev project.

This is not an easy process and is quite complex.

**Comment by soupette** [comment]
@halower here are the commands that allows to build your plugins.

- **`npm run setup:build`** only available at the root of the Strapi repository it will install Strapi and build the plugins that are in the `monorepository`
See https://github.com/strapi/strapi/blob/b16fd8c452d7d7f7a16ba6ae5b204a27855a0041/scripts/setup.js#L166

So if you want to be able to build your plugin from the monorepo you will need to prefix it by `strapi-plugin`, put it inside the `./packages` directory and add it to the `pluginsToBuild` Array.

- **`npm run setup`** if used inside the strapi `monorepo` it will only install strapi globally
- **`npm run setup`** when launched at the root of your app it will install all the dependencies and build only the `strapi-admin` (`./admin` folder of your app).
- **`npm run setup --plugins`** is only available in a generated application. This command will install all the dependencies of you application and will build all the plugins that are inside your app.

**Comment by halower** [comment]
@donaldr @derrickmehaffy @soupette thank you very much for your answer. Please allow me to ask a question. If you are in non-dev mode, how can I recompile the default plugin (e.g email) directly?

**Comment by derrickmehaffy** [comment]
@halower right now you can't, you would need to rebuild it in a --dev and copy over the build folder.

@soupette is working on fixing that.

**Comment by halower** [comment]
thanks, I just started experimenting yesterday, so I am not familiar with it, but I can feel that this project is very good.chinese multi-language support seems to be a little problem, so I will confirm and submit a new issue.
