### ISSUE TITLE
Can we merge attributes when search?

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2332]
**Informations**
- **Node.js version**: v10.13.0
- **npm version**: v6.4.1
- **Strapi version**: v3.0.0-alpha.14.5
- **Database**: MongoDB
- **Operating system**: macOS

## Setup

Create this `Battle` model:

```json
{
  "connection": "default",
  "collectionName": "battle",
  "info": {
    "name": "battle",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "date": {
      "default": "",
      "type": "date"
    },
    "team1": {
      "collection": "user",
      "via": "battles1",
      "dominant": true,
      "plugin": "users-permissions"
    },
    "team2": {
      "collection": "user",
      "via": "battles2",
      "dominant": true,
      "plugin": "users-permissions"
    },
    "winner": {
      "default": "team1",
      "type": "enumeration",
      "enum": [
        "team1",
        "team2"
      ]
    }
  }
}
```

Add these attributes to the User model:

```json
{
  ...
  "attributes": {
    ...
    "battles1": {
      "collection": "battle",
      "via": "team1"
    },
    "battles2": {
      "collection": "battle",
      "via": "team2"
    }
  }
}
```

## Question about search

I will use a fragment in the example:

```
fragment battleFields on Battle {
  _id
  date
  team1 { 
    username
  }
  team2 { 
    username
  }
  winner
}
```

If I want to get the battles of a user I can do:

```
{
  users(where: { username: "abdon" }) {
    battles1 {
      ...battleFields
    }
    battles2 {
      ...battleFields
    }
  }
}
```

But what I really want is to receive the battles together. Like:

```
{
  users(where: { username: "abdon" }) {
    battles {
      ...battleFields
    }
  }
}
```

Also sort by date or limit. Like:

```
{
  users(where: { username: "abdon" }) {
    battles(sort: "date:desc", limit: 10) {
      ...battleFields
    }
  }
}
```

Maybe something manual with the hooks?

Thanks in advance!

**Comment by Aurelsicoko** [comment]
@abdonrd You need to custom the generate `User` type and add this custom field `battles`. Also, you've to change the default behaviour of the controller to return the results following this new response format.

**Comment by abdonrd** [comment]
@Aurelsicoko after add the `battles` field:

```
"speaker": {
  "type": "array",
  "model": "battle"
},
```

I add this to the controller:

```
data.battles = [...data.battles1, ...data.battles2];
```

But the `plugins/graphql/config/generated/schema.graphql` it's wrong.

The `battles` field in the `UsersPermissionsUser` type is:
```
battles: String
```
Instead of:
```
battles(sort: String, limit: Int, start: Int, where: JSON): [Battle]
```

And the `battles` field in the `UserInput` type is:
```
battles: String
```
Instead of:
```
battles: [ID]
```

**Comment by Aurelsicoko** [comment]
Can you show me the `battles` field in the UserPermissionsUser model? Is it a collection?

**Comment by abdonrd** [comment]
@Aurelsicoko you mean this?

```
"battles": {
  "type": "array",
  "model": "battle"
},
```

**Comment by Aurelsicoko** [comment]
The `battles` is a `String` because the GraphQL plugin detects the `model` property. It makes no sense to define a `type: array` with the `model` property for the same attribute. Can you change the `model` property to `collection` instead?

```json
"battles": {
  "type": "array",
  "collection": "battle"
},
```

**Comment by abdonrd** [comment]
@Aurelsicoko with this, `strapi start` doesn't work:

```
[2018-12-20T10:22:32.052Z] error Something went wrong in the model `User` with the attribute `battles`
[2018-12-20T10:22:32.053Z] error Cannot read property 'nature' of undefined
```

**Comment by Aurelsicoko** [comment]
@abdonrd Oh you're right... it's because we don't support the manyWay relationship for now. Once it'll be the case, it should work. So I don't have a clean solution in mind to find a workaround for this issue :/

**Comment by abdonrd** [comment]
@Aurelsicoko can we reopen the issue then? 🙂

**Comment by Aurelsicoko** [comment]
Sure, it will certainly be fixed with the "Repeater Field" feature ;)

**Comment by mashiro11** [comment]
If I got it right, this issue is similar to the one I'm facing, please forgive me if I got it wrong:
Have a model Topic, which has a Response collection, and each response has a User. By default, requesting a Topic retrieves something like this
```
{
   _id: 'someid72371' 
   title: 'Some topic title',
   response: [{
      _id: '766757788',
      responseText: 'some response text',
      user: '7876878789'
   }]
}
```

But I want to configure so the server retrieves more than just the user id, like his name:
```
{
   _id: 'someid72371' 
   title: 'Some topic title',
   response: [{
      _id: '766757788',
      responseText: 'some response text',
      user: {  //like this
          _id: '7876878789',
          username: 'John Doe'
      }
   }]
}
```

**Comment by lauriejim** [comment]
Hello @mashiro11 you will have to customise the populate value you send in your services/controller functions.

**Comment by lauriejim** [comment]
@abdonrd I close this issue case it reference to this issue https://github.com/strapi/strapi/issues/1748
