### ISSUE TITLE
Crash occurred while adding a new content type from admin dashboard

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#2335]
**Informations**
- **Node.js version**:  10.13.0
- **npm version**: 6.4.1
- **Strapi version**:   3.0.0-alpha.14.4.0
- **Database**:  Mongo DB
- **Operating system**: Linux (Debian 9 )

**What is the current behavior?**

I was adding a content type but suddenly server stopped with this log : 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'globalId' of undefined
    at _.forEach (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:345:141)
    at /opt/dashboard/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/opt/dashboard/node_modules/lodash/lodash.js:2996:24)
    at /opt/dashboard/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/opt/dashboard/node_modules/lodash/lodash.js:9344:14)
    at _.forEach (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:301:15)
    at /opt/dashboard/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/opt/dashboard/node_modules/lodash/lodash.js:2996:24)
    at /opt/dashboard/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/opt/dashboard/node_modules/lodash/lodash.js:9344:14)
    at mountModels (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:250:13)
    at _.forEach (/opt/dashboard/node_modules/strapi-hook-mongoose/lib/index.js:449:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I believe this was happening because my model add multiple relations. But now i even deleted that content type but it won't work and showing me same error. Help please!

**Steps to reproduce the problem**
I don't have any idea about that yet.

**What is the expected behavior?**
It should not stopped and let me add the content type.

**Suggested solutions**
Do not know it yet.

**Comment by derrickmehaffy** [comment]
@sidsaxena0 ```
'globalId'
```

All lowercase on everything, known issue that is being fixed in the next release.

Also:
```
Strapi version: 3.0.0-alpha.14.4.0
```

All issues need to be tested on the latest release (14.5), any issues created on older releases are closed without further support. Please see this note in the Bug Report template:

```













```

**Comment by sidsaxena0** [comment]
OK sorry for not checking my version when i asked question but what do i do now to fix this issue? Is there any work around for this for the time being.

**Comment by lauriejim** [comment]
You have to delete references to the model you delete in all models a relations was made with.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Comment by j-zimnowoda** [comment]
It can also happen if you forget to add referenced component/model to your git repo ;)
