### ISSUE TITLE
How to update relation many-to-many correctly

### ISSUE THREAD

**Issue by estel1591** [strapi/strapi#2336]
**Informations**
- 11.0.0
- 6.4.1
- 3.0.0-alpha.14.5
- mongo 
- Ubuntu 16.04

**What is the current behavior?**
Can't update relation between User model and custom Widget model (many-to-many).
Request example:
http://joxi.ru/xAebk50Hp8wzZr

Could anybody explain how to do it correctly pls?

**Comment by lauriejim** [comment]
We fix it https://github.com/strapi/strapi/pull/2316 - will be published in next version of Strapi
Can you try to push the widget object instead of just the ID.

**Comment by zcapin** [comment]
Please mark its just for mongoose and not for SQL db, its confusing
