### ISSUE TITLE
Update the grant-koa version

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2338]
- ❌ **I have created my request on the Product Board before I submitted this issue**
- ✅ **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Update the `grant-koa` (`users-permissions` plugin) to `v4.0`: [Grant changelog](https://github.com/simov/grant/blob/master/CHANGELOG.md).

https://github.com/strapi/strapi/blob/b16fd8c452d7d7f7a16ba6ae5b204a27855a0041/packages/strapi-plugin-users-permissions/package.json#L26

**Comment by Aurelsicoko** [comment]
@abdonrd I can't find the request on Product Board... Are you sure you've validated your email?

**Comment by abdonrd** [comment]
@Aurelsicoko how is the update of a package, and not a real feature, I didn't send this to the Product Board. Should I do it?

**Comment by lauriejim** [comment]
Hello @abdonrd , thank you for reporting this issue. We are currently on another feature and bug fix. 

Can you submit a PR please.

**Comment by Aurelsicoko** [comment]
@abdonrd You don't need to send this to Product Board. We are only referencing new features (not small changes or enhancements). Sorry, my answer was confusing...
