### ISSUE TITLE
Data lost

### ISSUE THREAD

**Issue by ronaldohoch** [strapi/strapi#2339]
**Informations**
- **Node.js version**:  10.13
- **npm version**:  6.4
- **Strapi version**: Yes
- **Database**:  mongodb
- **Operating system**:  Windows 10

Hello!
Analyze my situation:

I had to register clients in a camp where there was no internet connection, but before I went to the place, I had two banks set up. One place and another on the internet in backup form, but when I arrived at this place, I had to route the mobile data on my phone in order to run the application.

By doing this, I was able to make the Strapi work, enter the setup and remove the "Set as default connection" from the online bank and use the offline application.

There were no sockets around, so my laptop, before ending the battery, had finished signing up all of the camp and going off it, though, I usually turn it off with the windows command: "shutdown / s / t 1" I did this with Strapi still running.

Today, after 2 days, I come and discover that no data has been saved, what do you mean? Was not anything saved from what I did?

Does anyone know where my data may have gone?

Is there a secret log file in the folder structure?

**Comment by lauriejim** [comment]
I close this issue, your are doing deep custom usage of data storage management.
Can't provide custom support for that since time is lacking on our side.
I let this issue OPEN for 17 days to hope someone of the community can help you. I close it now.
