### ISSUE TITLE
Can't establish a mysql connection

### ISSUE THREAD

**Issue by rw3iss** [strapi/strapi#2345]
**Informations**
- **Node.js version**: 10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: mysql
- **Operating system**: OSX high sierra

**What is the current behavior?**
Lets configurate the connection to your database:
? Choose your main database: MySQL
? Database name: strapi
? Host: 127.0.0.1
? Port: 3306
? Username: root
? Password: ****

⏳ Testing database connection...
⚠️ Database connection has failed! Make sure your "strapi" database exist.

**Steps to reproduce the problem**
Just try to connect to mysql with 'strapi new <project>'. I've tried other/new users with full permissions. Have also tried 'localhost' instead of '127.0.0.1', other ports, other databases. Database exists.

**What is the expected behavior?**
It should establish a connection to mysql and create the project using it. I know the library suggests MongoDB, but a client would prefer mysql.

**Suggested solutions**
Not sure why it can't connect. If you have any ideas on where to start looking I can possibly help.

**Comment by jay7793** [comment]
I have the same problem, can not connect database with mongodb using mLabs.

**Informations**

Node.js version: v10.13.0
npm version: 6.4.1
Strapi version: 3.0.0-alpha.14.5
Database: mongo (mLabs)
Operating system: OSX Mojave

⏳ Testing database connection...
⚠️ Database connection has failed! Make sure your database is running.

```
strapi new strapi --dbclient=mongo --dbhost=ds127321.mlab.com --dbport=27321 --dbname=strapi --dbusername=jayjay --dbpassword=jayjay123 --dbssl=true --dbauth=jayjay
```

By the way I trying connect database using this command 

```
mongo ds127321.mlab.com:27321/strapi -u jayjay -p jayjay123
```

It can connect to databse with message

_MongoDB shell version v3.6.2
connecting to: mongodb://ds127321.mlab.com:27321/strapi
MongoDB server version: 3.6.6
rs-ds127321:PRIMARY>_

**Comment by rw3iss** [comment]
> @rw3iss are you able to connect with a client like DBeaver or HeidiSQL?

Thanks @derrickmehaffy, turns out it was some issue with the server locally. Whenever I started through MAMP, it wouldn't work (even though MAMP Is set to use default port of 3306), but when I started the mysqld daemon manually, I'm able to create a new strapi project with it. 

@jay7793 I was able to connect with mongodb. My prompt asks for the authentication table, and I specify "admin", and I also leave "username" and "password" both blank (default in mongodb install), and that seems to work:

Lets configurate the connection to your database:
? Choose your main database: MongoDB
? Database name: strapi
? Host: 127.0.0.1
? +srv connection: false
? Port (It will be ignored if you enable +srv): 27017
? Username:
? Password:
? Authentication database (Maybe "admin" or blank): admin
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

**Comment by rw3iss** [comment]
> > @rw3iss are you able to connect with a client like DBeaver or HeidiSQL?
> 
> Thanks @derrickmehaffy, turns out it was some issue with the server locally. Whenever I started through MAMP, it wouldn't work (even though MAMP Is set to use default port of 3306), but when I started the mysqld daemon manually, I'm able to create a new strapi project with it. Figured this out by trying a third party tool (DataGrip and MySQL Workbench), both of which couldn't connect. For some reason I could still connect through command line 'mysql' all the time. Thank you.
> 
> @jay7793 I was able to connect with mongodb. My prompt asks for the authentication table, and I specify "admin", and I also leave "username" and "password" both blank (default in mongodb install), and that seems to work:
> 
> Lets configurate the connection to your database:
> ? Choose your main database: MongoDB
> ? Database name: strapi
> ? Host: 127.0.0.1
> ? +srv connection: false
> ? Port (It will be ignored if you enable +srv): 27017
> ? Username:
> ? Password:
> ? Authentication database (Maybe "admin" or blank): admin
> ? Enable SSL connection: false
> 
> ⏳ Testing database connection...
> The app has been connected to the database successfully!

**Comment by jay7793** [comment]
@rw3iss Thank you very much. it work by leave "username" and "password" both blank

**Comment by jay7793** [comment]
@rw3iss After I successfully installed I have tried to run starpi start command, it will display the message `MongoError: there are no users authenticated`

After that, I went to set up the file database.json In folders `config/environments/development` to enter mongo username and password, but not successful. It displays the error message: `Authentication failed.`

**Comment by rw3iss** [comment]
@jay7793 Can you connect to the mongodb instance from your terminal, with just the 'mongo' command? If so, next try stopping the mongod daemon, and then starting it again without access control enabled: mongod --port 27017 --dbpath /data/db1
If your db path doesn't exist, just make it for this test, and then try to connect again either way.
I don't really ever use mongodb, so I can't be of much help, but it's working for me locally, node v.10.11.0, npm v6.4, strapi latest alpha 3.0.0, mongodb v4.0.2

**Comment by AnaHdez2816** [comment]
@rw3iss I had the same error, what I did was create the database from MySQL.

**Comment by AnaHdez2816** [comment]
The problem I have now is that it does not happen to me:

C:\pruebas_korinver\prueba_de_la_prueba_de_la_prueba
λ strapi start
[2018-11-23T16:51:41.183Z] info Time: Fri Nov 23 2018 10:51:41 GMT-0600 (Hora estándar, América Central)
[2018-11-23T16:51:41.184Z] info Launched in: 3523 ms
[2018-11-23T16:51:41.185Z] info Environment: development
[2018-11-23T16:51:41.186Z] info Process PID: 19592
[2018-11-23T16:51:41.187Z] info Version: 3.0.0-alpha.14.5 (node v8.12.0)
[2018-11-23T16:51:41.187Z] info To shut down your server, press <CTRL> + C at any time

[2018-11-23T16:51:41.188Z] info ☄️  Admin panel: http://localhost:1337/admin
[2018-11-23T16:51:41.188Z] info ⚡️ Server: http://localhost:1337

[2018-11-23T16:51:42.144Z] info File changed: C:\pruebas_korinver\prueba_de_la_prueba_de_la_prueba/plugins/users-permissions/config/actions.json

Any suggestions?

**Comment by rw3iss** [comment]
What isn't starting? Doesn't show error in that message... ? What do you see when you go to http://localhost:1337 in your browser?

**Comment by AnaHdez2816** [comment]
Thanks, that solved me
So far I work with MySQL.
With MongoDB I was used to opening strapi automatically in the browser.

**Comment by sebastian-ludwig** [comment]
For anyone working with MAMP and having the same Problem:
Make sure "Allow network access to MySQL" is enabled in your MySQL settings

**Comment by iurynadin** [comment]
To enable "Allow network acess to MySQL" in MAMP (Mac):
1. Create a file **my.cnf** , in ``/Applications/MAMP/tmp/mysql``
2. Insert ``bind-address = 0.0.0.0`` in my.cnf
3. Restart MAMP
