### ISSUE TITLE
Using Azure Blob Storage with Strapi

### ISSUE THREAD

**Issue by snhoby** [strapi/strapi#2350]
Hi,
I would like to know, how to use Azure blob storage with strapi for file upload, I found this provider https://www.npmjs.com/package/strapi-upload-azure. However, this is empty. 

Any input is highly appreciated.

**Comment by lauriejim** [comment]
This provider doesn't exist. Juste the package exist but there is nothing behind.

**Comment by stefanmaretic** [comment]
I'm trying to create a package that would handle storing in azure blob storage.

I'm using the aws package as reference https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-aws-s3/lib/index.js

Do I just need to provide functioning upload and delete functions as the return statement of the module?

**Comment by lauriejim** [comment]
Yap that it.

**Comment by roycornelissen** [comment]
@stefanmaretic did you ever manage to finish this Azure Blob Storage package?

**Comment by stefanmaretic** [comment]
I found this one that I contributed to:
https://github.com/sylvaingirardbe/strapi-provider-upload-azure

**Comment by roycornelissen** [comment]
@stefanmaretic thanks for the quick reply and the link. Installed the provider, but I can't figure out how to configure it - I'm kind of a Strapi n00b and the documentation on it is really scarce :(

**Comment by apoorvpandey0** [comment]
I still cannot figure out where are all the endpoints it asks for!

**Comment by nguyenlamlll** [comment]
@apoorvpandey0: I haven't used this one yet but I think it looks kinda promising. Did you try this one? [jakeFeldman/strapi-provider-upload-azure-storage](https://github.com/jakeFeldman/strapi-provider-upload-azure-storage)
