### ISSUE TITLE
Variable contentTypesToShow in LeftMenuLinkContainer is always undefined

### ISSUE THREAD

**Issue by henrych4** [strapi/strapi#2353]
**Informations**
- **Node.js version**: 10.10.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: mongodb
- **Operating system**: mac OS

**What is the current behavior?**
The variable contentTypesToShow is always undefined.
https://github.com/strapi/strapi/blob/c8d5fd1499d8b129814d8d7d486ca6156e6f7ed4/packages/strapi-admin/admin/src/components/LeftMenuLinkContainer/index.js#L44

**Steps to reproduce the problem**
Create a project, add log to print the value 

**What is the expected behavior?**
It should give contentTypes as shown in /admin/layout

**Suggested solutions**
After reading the source codes, it probably relates to the following line:
https://github.com/strapi/strapi/blob/c8d5fd1499d8b129814d8d7d486ca6156e6f7ed4/packages/strapi-admin/admin/src/containers/AdminPage/saga.js#L19

Previously, `layout` is assigned by:
```
const layout = yield call(request, '/admin/layout', { method: 'GET' });
```
And it looks like this: { layout: { contentTypesToShow: {...} } } and hence ```get(layout, 'layout.contentTypesToShow');``` retrieves correct value.

Since shorthand property is used, "layout" is no longer needed in path.

**Comment by soupette** [comment]
@henrych4 thanks for reporting it I've noticed it and I think I will simply remove this from the admin.
