### ISSUE TITLE
Bugs with Media field type: Trying to add new content entry says 'no fields exist', and Media fields are not showing in relationship data.

### ISSUE THREAD

**Issue by rw3iss** [strapi/strapi#2358]
**Informations**
- **Node.js version**: 10.11.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: mysql 
- **Operating system**: OSX High Sierra

**What is the current behavior?**
If I add a new content type that only defined fields that are 'Media' fields, then save it, then go to try and add content, it says that no fields exist for this content type. If I then add any other field type, I can add a new content entry. 
It also does not show these Media fields as selectable 'Attribute fields' in the Content Manager type editor.
Furthermore, if I define a relationship between an object and this other type (with Media fields), then when I query the api for the first object data, it returns the relationship data, but does not include the Media fields. This is a larger bug.

As an elaboration/example:
If I make a content type 'product', with Media fields, then query the /products api, I see the Media fields. If I then have a content type such as 'productgroup', that defines a relationship to 'products', then when I query the /productgroups api, it returns the related data, but omits the Media fields (seems to not respect the upload_file_morph table?)

**Steps to reproduce the problem**
Define a new Content Type with only 'Media' fields. Then try to add a new piece of content for it.
Define a new relationship to a content type with media fields, and ask for the former, and you will not see the Media fields in the relationship data.

**What is the expected behavior?**
It should allow new content to be added using types that only define Media fields. It should also return the Media fields in the relationship data.

**Suggested solutions**
For now I'll just add a dummy field, but perhaps the Media field is new and not being recognized by the content entry validation system. As far as the relationship data goes, I will have to query the api after the first data is returned (ie. manually retrieve the relationships).

**Comment by rw3iss** [comment]
Thanks @derrickmehaffy As far as the actual relationship data returned by the API... it doesn't seem to return the Media field data if it is related to a parent object, when querying the parent object API. Is this non-functional and we're supposed to manually request the related/nested data separately from parent object api queries, if you're familiar with this?

Here's the data returned by the parent object (which contains productmodels), without the Media fields (image-top and image-bottom define on productmodel):
![screen shot 2018-11-21 at 20 52 08](https://user-images.githubusercontent.com/372120/48877043-68f99380-edcf-11e8-9b96-06d077ebd96f.png)
 
But here is actual productmodel data if queried directly (containing the image-top and image-bottom Media fields):
![screen shot 2018-11-21 at 20 53 58](https://user-images.githubusercontent.com/372120/48877097-9cd4b900-edcf-11e8-9a4e-60aa3e226d2d.png)

**Comment by rw3iss** [comment]
Suppose it's known that strapi doesn't support loading of nested data: #877 (https://github.com/strapi/strapi/issues/877)

Thanks for that fix @soupette !! Do you know the best way to incorporate it into the build? Does strapi have some way to pull latest code and recompile the global package? Or does it all have to be updated manually kinda?

**Comment by soupette** [comment]
You can apply the changes in the corresponding file of your app and run `npm run setup --plugins` at the root of your project.

**Comment by rw3iss** [comment]
> You can apply the changes in the corresponding file of your app and run `npm run setup --plugins` at the root of your project.

It worked! Thanks a lot for the fix, man, awesomely fast too. Cheers.
