### ISSUE TITLE
Database with Heroku postgres

### ISSUE THREAD

**Issue by rexliu0715** [strapi/strapi#2360]
**Informations**
- **Node.js version**: v11.2.0
- **npm version**: 6.4.1
- **Strapi version**: 
- **Database**: Postgres
- **Operating system**: Heroku

**What is the current behavior?**
Commond: strapi new 'project'
try to configurate the connection to my Heroku Postgres database. got failed.

Error:
Database connection has failed! Make sure your "database name" database exist.

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @rexliu0715 , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.
Thank you.

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/wiki/Deploy-on-Her

**Comment by yao-dev** [comment]
I was correct the bug with adding this code at line 213 of the file /usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js (where strapi is installed globally on your machine) : 
```
scope.database.settings.ssl = scope.database.settings.client === 'postgres' ? true : false;
```

Now I'm able to generate a project with a remote postgres database

**Comment by rob-gordon** [comment]
@yao-dev thank you! I just had this exact problem. Do you mind explaining why this works?

**Comment by genu** [comment]
I think this is still a problem in the recent versions of strapi. For example, Heroku sets `DATABASE_URL` as an env, and rotates the credentials periodically.

However, strapi is not able to connect to database using the connection string, but seems to require you to split up the connection string in to `host`, `user`, `pass` etc.
