### ISSUE TITLE
Request users returns only _id field in mongodb and id filed is missing.

### ISSUE THREAD

**Issue by agthumoe** [strapi/strapi#2361]
**Informations**
- **Node.js version**: v11.2.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: mongodb
- **Operating system**: Ubuntu 18.04.1 LTS

**What is the current behavior?**
api request to get all users (/users) and get one user(/users/{id}) return values with missing id field. There is still an _id field, which is a mongo object id. I know we can use that _id field. But it will make it very database oriented since we need to change keymap value if we change the database. It's only happening in users table. All other resources contain both id and also _id value. And it's only happening with mongodb.

**Steps to reproduce the problem**
1) create new project with mongodb.
2) send ajax request to /users and /users/{id}

**What is the expected behavior?**
It would be great if the user object contains id field, not just _id.

**Suggested solutions**
Add id filed to user object.

**Comment by lauriejim** [comment]
Hello @agthumoe.

We are agree to say `_id` and `id` has the same value.
So only one it needed in GraphQL schema I think.

In any case we will work on it https://github.com/strapi/strapi/issues/1274 and this issue will not be a topic.

In any case thank you for this report.
