### ISSUE TITLE
How to update relation many-to-many by custom field (not IDs)

### ISSUE THREAD

**Issue by estel1591** [strapi/strapi#2362]
Informations

11.0.0
6.4.1
3.0.0-alpha.14.5
mongo
Ubuntu 16.04

What is the current behavior?
Now I can update relation between User model and custom Widget model (many-to-many) by IDs of  Widgets. http://joxi.ru/v29aENlt3D9L62 But in my case I haven't to use IDs, only code of Widgets (custom field). http://joxi.ru/LmGJljDtejKdMr

Help wanted to do this right.

**Comment by henrych4** [comment]
How about modifying default handler for handling "PUT" request to "/users/:_id"? You can find the default handler [here](https://github.com/strapi/strapi/blob/0f6d597b8cc6c6c8a71cded24c4659686fc7c2b5/packages/strapi-plugin-users-permissions/controllers/User.js#L111).

**Comment by lauriejim** [comment]
Hello @estel1591. It's not possible to do what you want by default in Strapi.
As suggest @henrych4 you can update your controller function to feet with your needs.
