### ISSUE TITLE
model detele errors

### ISSUE THREAD

**Issue by Dogtiti** [strapi/strapi#2366]
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: mongoDB v3.6.4
- **Operating system**: MacOS 10.14.1

**What is the current behavior?**
when I have created a model,it reported an error`an error occurred`,and in the content-type-list 
a model appeared named `newSlider`，but not in `content-manager` and `content-type-builder` as follow images:
![image](https://user-images.githubusercontent.com/38354472/48934394-d415a800-ef3e-11e8-9ed1-10f89c4c5482.png)

![image](https://user-images.githubusercontent.com/38354472/48934404-e5f74b00-ef3e-11e8-876f-1a6d2c59b85e.png)

it means I can't update it or delete it.Then I click it : 
![image](https://user-images.githubusercontent.com/38354472/48934507-438b9780-ef3f-11e8-9b8e-22a9f42d087c.png)
go on : 
![image](https://user-images.githubusercontent.com/38354472/48934524-51411d00-ef3f-11e8-9fe0-74ce8873220c.png)
Fall into an infinite loop.And the `api` folder doen't have it too
![image](https://user-images.githubusercontent.com/38354472/48934610-bac12b80-ef3f-11e8-8f18-4cd3eec7c922.png)

so how can I do ?

**Comment by dstuff** [comment]
Same behavior. In my case I've created a model (new content type) and then trying to change the model's name. The server didn't start at all, so I just removed this model in my IDE (delete directory) but is still in my Content Types list. Any thoughts on how to delete it completely?

**Comment by lauriejim** [comment]
Please use lowercase content type name and attribute name.
https://github.com/strapi/strapi/issues/2131
