### ISSUE TITLE
Middleware Views package has wrong README

### ISSUE THREAD

**Issue by franz-josef-kaiser** [strapi/strapi#2372]
The built–in package `strapi-middleware-views` still has the README from the redis package. 
Direct link to curr/last commit [here](https://github.com/strapi/strapi/tree/48b3d534fe720835cb295a70f7b34cbdfd4f01ed/packages/strapi-middleware-views).

**Comment by lauriejim** [comment]
Thank you this feedback, will fix it.

**Comment by VlnRbn** [comment]
It would be helpful if there is an integration example.

**Comment by lauriejim** [comment]
Hello! I suggest you check this https://www.npmjs.com/package/strapi-hook-ejs
