### ISSUE TITLE
Not able to call populate method on DB models when using MySQL

### ISSUE THREAD

**Issue by rw3iss** [strapi/strapi#2373]
**Informations**
Node.js version: 10.11.0
npm version: 6.4.1
Strapi version: 3.0.0-alpha.14.5
Database: mysql
Operating system: OSX High Sierra

**What is the current behavior?**
I'm trying to call .populate({path:'submodel'}) on a content type, but it says the method does not exist. I've tried doing this in the model's controller, service, and the lifecycle methods, but not sure if there is a way when using mysql. It seems the MongoDB usage is different, relying on the Mongoose model. 

**Steps to reproduce the problem**
Setup a site using mysql DB, define a content type, then another, then a relationship from the first to the second, and try to populate it in either the service or controller, ie:
```
 let home = Homepage.forge(_.pick(params, 'id'))
      .populate('models')
```

**What is the expected behavior?**
There should be a way to populate nested relationship data when using MySQL.

**Suggested solutions**

Does anyone know how to populate nested data when using MySQL?
There should be some convenience to auto-populate, as in MongoDB's implementation, or otherwise specify an example to manually load relationship data on a particular content type model.

**Comment by Moldieman** [comment]
@rw3iss I am having the same issue and have referenced it here - #2118 . If you ever get this right please let me know? Thx

**Comment by lauriejim** [comment]
Hello @rw3iss can you give me your 2 models please.
What it the type of your relation ?

@Moldieman it's not the same issue as you link. Your issue is specific to `Media` relations.
