### ISSUE TITLE
Editing content type creates second table in Postgres

### ISSUE THREAD

**Issue by forsetius** [strapi/strapi#2374]
**Informations**
- **Node.js version**:  v10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: postgres
- **Operating system**: Linux Mint 18.3

**What is the current behavior?**

When creating a new content type user needs to fill in the content type name and user is asked to use singular form. After adding few fields and saving, in the database a new table appears, named in plural form. If user re-enters the content manager, adds more fields and saves, in the database a new table appears, named in singular form this time, that contains all the fields already defined. Plural-named stays there but contains only fields that were added with the first save.

**Steps to reproduce the problem**

1. In admin enter Content Type Builder and click "Add new type"
2. Name it "Article" and save
3. Click "Add new field", choose string field type, name it "name", click "Continue" and save
4. After app restarts check the database (using phpPgAdmin for example) - there is a new "articles" table. It contains `id`, `name`, `created_at` and `updated_at` fields
5. Return to Content Type Builder, "Article" content type
6. Click "Add new field", choose string type, name it "other" and save
7. After app restarts check the database again - there is a new "article" table. It contains `id`, `name`, `other` `created_at` and `updated_at` fields. The `articles` table still exists with `id`, `name`, `created_at` and `updated_at` fields (missing the newly added one)

**What is the expected behavior?**

Once a table is created (either in singular or plural form) it should be consistently used afterwards.

**Suggested solutions**

Disable initial conversion to plural form, stick with what's entered by user. Of course lower-casing and perhaps camel-casing should stay.

**Comment by lauriejim** [comment]
Hello it's not an issue.

When you update a attribute of a content type we create a new column in the database (if you use bookshelf) cause we don't want to delete anything else in your database.

It's the same for your content type name.

You will have to migrate data from old table/collection.

You will find some issue about delete column and we speak about this topic.
