### ISSUE TITLE
Uploads for a custom model issue

### ISSUE THREAD

**Issue by dstuff** [strapi/strapi#2375]
**Informations**
- **Node.js version**: v10.13.0
- **npm version**: v6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MongoDB 4.0.4
- **Operating system**: McaOS 10.14.1

**What is the current behavior?**
I create new content type Post and set 2 fields: title and images. The title defines as a String and Images defines as Media with multiple file uploading available. When I tried to upload files to the new saved Post I used the following API endpoint "localhost:1337/upload" and my Postman looks:
![image](https://user-images.githubusercontent.com/7025939/48972034-d148af00-f033-11e8-9cb7-6fb7addc0110.png)
And I got a response with newly uploaded files and I can see it in my local directory "public/uploads". But when I requested my Post there are no images, just empty array.
My model looks like this:
![image](https://user-images.githubusercontent.com/7025939/48972054-41efcb80-f034-11e8-9997-ccf46a47143e.png)
And API response like this:
![image](https://user-images.githubusercontent.com/7025939/48972058-546a0500-f034-11e8-9ed1-1a3ff7aa3d57.png)

**Steps to reproduce the problem**
1. Create new Content type via the admin dashboard
2. Create 2 fields "title: String" and "images: Media" with multiple files uploading checkbox
3. Create new Post record using Postman
4. Upload files using new created Post
5. Files saved but there is nothing in "images" filed of Post

**What is the expected behavior?**
Uploaded files should appear in "images" field

**Suggested solutions**
No

Any help will be very appreciated. Also, same behavior if I set images field as a single Media file.

**Comment by dstuff** [comment]
It's weird and now with the same conditions srver responds me with an error:
```TypeError: Cannot read property 'globalId' of undefined
    at acc.(anonymous function).params.values.(anonymous function).map.obj (/Users/andrew/Work/api/node_modules/strapi-hook-mongoose/lib/relations.js:162:71)
    at Array.map (<anonymous>)
    at params.parseRelationships.Object.keys.reduce (/Users/andrew/Work/api/node_modules/strapi-hook-mongoose/lib/relations.js:160:51)
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/Users/andrew/Work/api/node_modules/strapi-hook-mongoose/lib/relations.js:28:129)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by lauriejim** [comment]
Hello @dstuff !

We don't support `form-data` from Postman.

To upload file please use curl request :
`curl -X POST -F 'files[]=@/path/to/pictures/fileX.jpg' -F 'files[]=@/path/to/pictures/fileY.jpg' -F 'refId=5c041980214b1a831eb52895' -F 'ref=post' -F 'field=images' http://localhost:1337/upload`

And you don't need `source` params cause your `Post` model is not a plugin.

**Comment by lauriejim** [comment]
Related issue https://github.com/strapi/strapi/issues/1316

**Comment by e-ndrus** [comment]
Tried to upload from react-admin using axios. Got success response, but the file was not uploaded and didn't link with the content type. Is there any example on how to implement file upload from react to strapi?

**Comment by lauriejim** [comment]
Here is an example: https://github.com/strapi/strapi-examples/blob/8f601df45bcaddf2b4d4ccd8968c763ea4920e01/good-old-react-authentication-flow/src/containers/EditPage/index.js#L78-L117

**Comment by e-ndrus** [comment]
Thank you! Successfully ported parts of this code to react-admin. And it worked!

**Comment by hkovacs** [comment]
> Here is an example: https://github.com/strapi/strapi-examples/blob/8f601df45bcaddf2b4d4ccd8968c763ea4920e01/good-old-react-authentication-flow/src/containers/EditPage/index.js#L78-L117

looks like nobody ever tested this example file :)

line 91: body.apprend most likely meant to be body.append

**Comment by lflucasferreira** [comment]
> Hello @dstuff !
> 
> We don't support `form-data` from Postman.
> 
> To upload file please use curl request :
> `curl -X POST -F 'files[]=@/path/to/pictures/fileX.jpg' -F 'files[]=@/path/to/pictures/fileY.jpg' -F 'refId=5c041980214b1a831eb52895' -F 'ref=post' -F 'field=images' http://localhost:1337/upload`
> 
> And you don't need `source` params cause your `Post` model is not a plugin.

When do you believe Strapi will allow us to use Postman in order to upload files? I thought the `multipart/form-data` would work with Postman. Thank you in advance.
