### ISSUE TITLE
Authenticating a user with Google is throwing 500 on the 2nd login

### ISSUE THREAD

**Issue by kueronya** [strapi/strapi#2383]
**Informations**
- **Node.js version**: 10.13.0
- **npm version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.14.5
- **Database**: mongodb 3.6.5
- **Operating system**: Win10

**What is the current behavior?**
After the first successful authentication with google, additional attempts to authenticate, at least within the next minutes, fail at redirecting to GET /auth/google/callback as long as the user remains signed in with google in the browser. 
Response is 500 at http://localhost:4200/auth/callback/google?error%5Berror%5D=invalid_grant&error%5Berror_description%5D=Malformed%20auth%20code.

Signing off from Google fixes this issue and returns jwt and user response after redirecting to GET /auth/google/callback

**Steps to reproduce the problem**
Authenticate with google
Stay signed in with google
Authenticate again with google

**What is the expected behavior?**
After the first authentication subsequent authentication attempts should also issue a new token.

**Suggested solutions**
I'm not quite sure why this happens since the initial redirect from accounts.google.com/o/oauth2/auth to /connect/google/callback looks pretty much the same on the first and subsequent calls, only difference i could recognize was that the first redirect is encoded while the next ones are not

First attempt, working:
http://localhost:1337/connect/google/callback?code=4%2FogD_bJ10kjNs7l8gqTF25hLsYQPUU-rkatS6jK5shBXcw-lLN0wlJpbSDbyx8zFP2yuDyVLDA1ScgSxLaZxxxxx&scope=openid+email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.me

Next attempt, failing: 
http://localhost:1337/connect/google/callback?code=4/ogCWJEaBayzfL2PoY4NJ3rL-11Wu4FNjrPOxRlFG003qPuGCy7nV6qCnlX1vvh_Dt1cUmJZrFn5ESxxxxx&scope=openid+email+https://www.googleapis.com/auth/plus.me+https://www.googleapis.com/auth/userinfo.email

**Comment by lauriejim** [comment]
Did you follow the documentation about the facebook authentication ?

**Comment by kueronya** [comment]
> facebook

I followed the google example from the provider section https://strapi.io/documentation/3.x.x/guides/authentication.html#providers. 

The error also occurs in the react example app, so i guess there is nothing i did wrong. 

So basically if there is a active browser session with google (check google.com if the/a user is already signed in) then the redirect back to strapi throws "500 server error - malformed_auth_code".

**Comment by kueronya** [comment]
After some further research i think i nailed down the problem.

For all google accounts i tested so far the returned token (code parameter) by google contains a slash '/'.  
?code=4/xxxxxxxxxxxxx

If there is no active google session in the browser instance, the redirect uri and the query parameters are url-encoded and thus the request is handled by strapi correctly. ?code=4%2Fxxxxxxxxxxxxx

As soon as there is already a active google session in the browser, google redirects back to strapi with the code parameter unencoded, which cannot be handled by, i guess, the oauth middleware and is throwing the malformed_auth_token error.

I don't know who is doing wrong here, google by redirecting unencoded or strapi/middleware by not handling both cases, encoded and unencoded parameters. 
I would be glad if someone can shed some light on this, since it actually makes it impossible for me to authenticate users without asking them to logoff from google prior doing so.

**Comment by derrickmehaffy** [comment]
@kueronya There have been quite a few issues with providers. In the short to mid term future I believe the plan is to break out each provider into their own plugin and then move them all to using passport.js which will be far easier to handle and not require breaking down the redirectURI as difficult. Right now what is being used is Grant/Purest.

You can pop though the users-permission plugin that currently handles these requests to take a look at the code:

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Providers.js

Specifically here: https://github.com/strapi/strapi/blob/b77c3bbf07d6b623c4f2095eb53897bb26bc073d/packages/strapi-plugin-users-permissions/services/Providers.js#L163-L179

**Comment by lauriejim** [comment]
I just tried the Google Auth documentation process and all works fine.
With last version of Strapi (alpha.16) and mongo database.

**Comment by kueronya** [comment]
Sorry @lauriejim, can't confirm that. I tried once again with the react sample app running against strapi alpha.16 and the error is still thrown. 
I uploaded a video https://streamable.com/4452w to make clear what's not working for me. Can you confirm that even if there is a google account already signed in you get an access_token on the redirect back to the client app?

**Comment by lauriejim** [comment]
Okay that is strange!
Can you give me the full url of the network url you click.
I saw an error in the url and I want to now what it is.
Did you have an error in your terminal ?

**Comment by kueronya** [comment]
> Okay that is strange!
> Can you give me the full url of the network url you click.
> I saw an error in the url and I want to now what it is.
> Did you have an error in your terminal ?

The url i showed in the video is the failing redirect back to the client app. Usually it should contain the jwt and user object but in case of an error it just redirects with the error object instead: 

> http://localhost:1337/auth/google/callback?error%5Berror%5D=invalid_grant&error%5Berror_description%5D=Malformed%20auth%20code

And yes, just realized there is also an error thrown in the console:

> null: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
> data: null
> isBoom: true
> isServer: true
> message: "Cannot read property 'Symbol(Symbol.iterator)' of object: Cannot read property 'Symbol(Symbol.iterator)' of object"
> output: Object {statusCode: 500, payload: Object, headers: Object}
> headers: Object {}
> __proto__: Object {constructor: , __defineGetter__: , __defineSetter__: , …}
> payload: Object {message: "An internal server error occurred", statusCode: 500, error: "Internal Server Error"}
> error: "Internal Server Error"
> message: "An internal server error occurred"
> statusCode: 500
> __proto__: Object {constructor: , __defineGetter__: , __defineSetter__: , …}
> statusCode: 500
> __proto__: Object {constructor: , __defineGetter__: , __defineSetter__: , …}
> reformat: function () { … }
> [[FunctionLocation]]: internal#location
> [[Scopes]]: Scopes[2]
> arguments: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
> caller: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
> length: 0
> name: ""
> prototype: Object {constructor: }
> __proto__: function () { … }
> stack: "TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
>     at callback (c:\VisualStudioCodeProjects\Castelli\strapi\strapi-3.0.0-alpha.16\castelli-strapi\plugins\users-permissions\controllers\Auth.js:94:23)
>     at process._tickCallback (internal/process/next_tick.js:68:7)"
> __proto__: Error {constructor: , name: "TypeError", message: "", …}

**Comment by lauriejim** [comment]
Can you check again with last version of Strapi, we fix things about provider connection.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by kueronya** [comment]
> Can you please give us an update about this issue?

Sorry @lauriejim , i was quite busy last weeks. 

Just setup strapi v3.0.0-alpha.23.1 (mongodb), [login-react](https://github.com/strapi/strapi-examples/tree/master/login-react) and configured google provider following [this example](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md). 
Unfortunately the problem still exists:

![strapi-log](https://user-images.githubusercontent.com/5357444/52530432-047f0e00-2d06-11e9-9a5b-5e5b80db6c22.png)

First authentication (green box) issued from a chrome guest window in this example is working as expected. Subsequent auth requests fail (red box)

**Comment by 242** [comment]
Hey guys, the error is that await strapi.authenticateProvider isn't sent with the query, it receives an empty object on which symbol iterator can't iterate.
  ```
async asyncData (context) {
    await strapi.authenticateProvider(provider, context.query)
}

```
Will do the trick

**Comment by Mateussmo** [comment]
@kueronya I have the same issue. And I can resolve the problem, just do the same thing on this link https://github.com/hackmdio/codimd/issues/259 . I change the settings on URIs on google developers. From localhost:1337/connect/google/callback to localhost/connect/google/callback.

**Comment by juliosouza-pushstart** [comment]
I've been running into this same issue, and it looks like it's caused and obscured by a chain of errors:

- Strapi replaces "/" in query with "\" (I have no idea where, @lauriejim might be able to find it)
- Some OAuth codes contain the "/" character, and it's passed via `code` param in the query of /connect/google/callback
- When Strapi asks koa to verify the code, it uses the incorrect on, so Google returns a 4XX error
- Strapi handles that error by redirecting us to ` ?error[error]=invalid_grant&error[error_description]=Malformed auth code`, but Auth.js doesn't handle that query and ends up throwing and causing a 500

As a workaround, you can modify `connect` method in strapi-plugin-users-permissions/controllers/Auth.js:

```javascript
    const Grant = require('grant-koa');
    const grant = new Grant(grantConfig);

    ctx.query.code = ctx.query.code.replace("\\", "/"); // ADD THIS LINE

    return compose(grant.middleware)(ctx, next);
```

**Comment by JulioC** [comment]
(Oops! I accidentally deleted my previous more-detailed comment. If someone has a copy, feel free to post it)

The error is caused by a "/" being replaced with a "\\" in the `code` query param received by /connect/google/callback. Strapi does this somewhere, I can't find it though. 

As a workaround, add these lines to `connect` method in strapi-plugin-users-permissions/controllers/Auth.js:

```js

    const Grant = require('grant-koa');
    const grant = new Grant(grantConfig);

    ctx.query.code = ctx.query.code && ctx.query.code.replace("\\", "/"); // ADD THIS LINE

    return compose(grant.middleware)(ctx, next);
```

**Comment by LucasMatuszewski** [comment]
@JulioC - Thanks a lot! Works for me as a temporary dirty fix.

Can't wait for Passport :)
Google+ API still works but who knows how long?
Facebook also inform about new API version, but as far as I see Strapi works fine with it.
