### ISSUE TITLE
Windows - MySQL - Unable to connect to database 

### ISSUE THREAD

**Issue by engineertdog** [strapi/strapi#2387]
- **Node.js version**:  8.9.1
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MySQL
- **Operating system**: Windows 

**What is the current behavior?**
Upon trying to create a new project with a fresh install of Strapi, I am unable to connect to the local database. Note, I had to downgrade to Node v8.9.1 from v10.13.0 because the installer would freeze after selecting a database type. I can connect to the database with powershell and with MySQL Workbench. The database does exist, and the user does have CRUD access.

**Steps to reproduce the problem**

- npm install strapi@alpha -g
- strapi new project
- Select MySQL as database
- Enter details
- Database connection has failed! Make sure your "api" database exist.

**What is the expected behavior?**
I should be able to connect to the database

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

**Comment by engineertdog** [comment]
That's quite laughable.

**Comment by lauriejim** [comment]
Make sure you `api` database exist.

**Comment by engineertdog** [comment]
The table does exist, and I can perform queries on that database with both the CLI and with a client like MySQL Workbench.

**Comment by lauriejim** [comment]
Where is hosted your database ?

**Comment by engineertdog** [comment]
The MySQL database is installed on the Windows machine. If there is a place that had more information about why the database check failed, that could be useful.

**Comment by Paratron** [comment]
Have the same problem on a ubuntu machine. mysql-server is running fine, the database exists but strapi refuses to connect. Well, `npm remove strapi@alpha -g` then...

**Comment by lauriejim** [comment]
In the last version of Strapi we add `--debug` tag when you run `strapi new projec --debug` it will show you all error logs.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Comment by swappsshinde** [comment]
So we are facing **Database connection has failed! Make sure your "api" database exist.** because : we are not specifying the username and password for the MySQL database while connecting with the strapi project

**Comment by derrickmehaffy** [comment]
@swappsshinde with MySQL you need to have a database, a user, a password, and that user needs to have permissions on that database.
