### ISSUE TITLE
Changes in the content type fields are discarded

### ISSUE THREAD

**Issue by gyldcs** [strapi/strapi#2393]
**Informations**
- **Node.js version**: 11.3.0
- **npm version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.14.5 
- **Database**: MongoDB
- **Operating system**: MacOs Mojave 

**What is the current behavior?**
If you create a content type field, you are not able to  edit it later (the changes are discarded)

**Steps to reproduce the problem**
1) add a new string typed content type field with the required checkbox unchecked
2) edit the same field by checking the "required" checkbox
3) save

**What is the expected behavior?**
to save my changes

**Comment by timruiterkamp** [comment]
Did you run ```strapi start``` and not ```npm start``` ? ```npm start``` let's you change anything but it doesn't really update it, ```strapi start``` does.

**Comment by gyldcs** [comment]
yeah, I used `strapi start`

**Comment by timruiterkamp** [comment]
Do you have any logs when trying to edit the field? Strapi logs every action you do, so maybe there is something that points to where the problem is.

**Comment by gyldcs** [comment]
sorry, seems that after I upgraded my mongo the old instance were still running, now it seems to work fine
