### ISSUE TITLE
The GraphQL sort desc doesn't work

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2397]
**Informations**
- **Node.js version**: v10.0.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.15
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

The GraphQL sort desc doesn't work

**Steps to reproduce the problem**

After upgrading from `v3.0.0-alpha.14.5` to `v3.0.0-alpha.15`, this query doesn't work:

```javascript
{
  seasons {
    slug
    editions {
      slug
      matchdays(sort: "date:desc") {
        slug
        date
      }
    }
  }
}
```

Error:

```
"message": "Unkown order value: \"desc\", available values are: ASC, DESC",
```

And after update to:

```javascript
{
  seasons {
    slug
    editions {
      slug
      matchdays(sort: "date:DESC") {
        slug
        date
      }
    }
  }
}
```

The error is:

```
"message": "Unkown field: \"date\"",
```

But if I remove the `(sort: "date:DESC")`, it works:

```javascript
{
  seasons {
    slug
    editions {
      slug
      matchdays {
        slug
        date
      }
    }
  }
}
```

**What is the expected behavior?**

Working :)

**Comment by abdonrd** [comment]
But this works:

```javascript
{
  matchdays(sort: "date:DESC") {
    name
    date
  }
}
```

**Comment by kamalbennani** [comment]
I think that it has to do with my PR (https://github.com/strapi/strapi/pull/1948) I'll try to look into it today, sorry for the inconvenience

**Comment by abdonrd** [comment]
@kamalbennani thanks in advance!

(For now, I had to rollback the Strapi version)

**Comment by Aurelsicoko** [comment]
This PR https://github.com/strapi/strapi/pull/2380 should fix this issue. I've faced the same issue while I was developing so I fixed it inside the same PR.

**Comment by abdonrd** [comment]
@Aurelsicoko is there a "simple" fix or is all the PR necessary?
This bug does not let me update to the new `v3.0.0-alpha.15` version.

**Comment by kamalbennani** [comment]
It fixed on this PR too (https://github.com/strapi/strapi/pull/2419)
![image](https://user-images.githubusercontent.com/14129459/49344365-4d677600-f676-11e8-8acc-d666d75ea670.png)

**Comment by abdonrd** [comment]
Yay! Thanks @kamalbennani!

I hope there will be a version `v3.0.0-alpha.15.1` very soon with it! 🤞

**Comment by derrickmehaffy** [comment]
We -might- be able to talk @lauriejim into pushing a fix sooner than the expected release date :stuck_out_tongue_closed_eyes: maybe lol

**Comment by kamalbennani** [comment]
> We -might- be able to talk @lauriejim into pushing a fix sooner than the expected release date  maybe lol

:pray:

**Comment by kamalbennani** [comment]
But this time we need to test everything out before merging this PR, We need to implement/re-enforce integration tests

**Comment by lauriejim** [comment]
It's fixed in alpha.16 since I revert the filter PR that caused this issue.
Please confirm to delete this issue.

**Comment by abdonrd** [comment]
@lauriejim it works on alpha.16, yes!
