### ISSUE TITLE
Geolocation based queries support?

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#2398]
**Informations**
- **Node.js version**: 10.12.0
- **npm version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: MongoDB
- **Operating system**: Ubuntu

**What is the current behavior?**

Hi i have a problem with queries, i want to search some items based on it's location (lat and long). Is there anything right now built in in strapi to help me with it.

Is there anyway i can write my own query for a specific  request or is there any plugin or something to help me. Any help would be grateful.

**Comment by lauriejim** [comment]
Hello @sidsaxena0 !

Did you check filters https://strapi.io/documentation/3.x.x/guides/filters.html

If it doesn't match with your needs, you can create your own route and controller to make your request:
- https://strapi.io/documentation/3.x.x/guides/routing.html
- https://strapi.io/documentation/3.x.x/guides/controllers.html

And then you will have Mongoose collection instance of your model to create your own query. (Check the service of your API to show how make queries)
