### ISSUE TITLE
Determine many to many linking

### ISSUE THREAD

**Issue by estel1591** [strapi/strapi#2402]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Is there any easy way to determine that some content of type A was linked/unlinked with another content of type B (many to many relation) like turn on/off feature?

**Comment by lauriejim** [comment]
Hello @estel1591 !

I'm not sure to understand your need.
Are you talking about that https://strapi.io/documentation/3.x.x/guides/filters.html#available-operators ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
