### ISSUE TITLE
GraphQL Filtering not working as expected on Bookshelf

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2405]
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: v15
- **Database**: MariaDB 10.2
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

Attempting to make strict queries with GraphQL on MySQL is not properly returning data.

Using my dev server: https://api.canonn.tech:2083/graphql

If I attempt this query:
```
query {
  grsites(limit: 10, start: 10, where: {
    siteID_contains: "28"
  }) {
    id
    siteID
  }
}
```

I get a proper response:
```
{
  "data": {
    "grsites": [
      {
        "id": "287",
        "siteID": 287
      },
      {
        "id": "288",
        "siteID": 288
      },
      {
        "id": "289",
        "siteID": 289
      }
    ]
  }
}
```

However if I go one step further and attempt this query:
```
query {
  grsites(limit: 10, start: 10, where: {
    siteID: "287"
  }) {
    id
    siteID
  }
}
```

I get the following:
```
{
  "data": {
    "grsites": []
  }
}
```

As you can see from the first example an entry with the contents of `287` exists.

**Steps to reproduce the problem**

See above example

**What is the expected behavior?**

Filters on GraphQL should function close to or exactly like it does with the RestAPI: https://api.canonn.tech:2083/grsites?siteID=287

**Suggested solutions**

Likely related to https://github.com/strapi/strapi/issues/2397

**Comment by derrickmehaffy** [comment]
Tested these queries which also do not work as expected per: https://strapi.io/documentation/3.x.x/guides/graphql.html#configurations

```
query {
  grsites(siteID: "287") {
    id
    siteID
  }
}
```

```
query {
  grsites(id: "287") {
    id
    siteID
  }
}
```

**Comment by kamalbennani** [comment]
How would this query work and you're excepting the grsites to return 1 element (and you're offsetting by 10 elements?)?
```
query {
  grsites(limit: 10, start: 10, where: {
    siteID: "287"
  }) {
    id
    siteID
  }
}
```

**Comment by kamalbennani** [comment]
> Tested these queries which also do not work as expected per: https://strapi.io/documentation/3.x.x/guides/graphql.html#configurations
> 
> ```
> query {
>   grsites(siteID: "287") {
>     id
>     siteID
>   }
> }
> ```
> ```
> query {
>   grsites(id: "287") {
>     id
>     siteID
>   }
> }
> ```

Are these even a valid Strapi GraphQL Signatures? did you forget to use where?

**Comment by kamalbennani** [comment]
I'm sorry buddy but I took at least 1h to try to set up the same environment as you to see how I can fix the probelm that you're reporting but it seems that there is no problem ...

**Comment by kamalbennani** [comment]
![image](https://user-images.githubusercontent.com/14129459/49257365-5bc55000-f432-11e8-84d5-d05c3e8208d7.png)

**Comment by kamalbennani** [comment]
![image](https://user-images.githubusercontent.com/14129459/49257370-654eb800-f432-11e8-9c5f-dbf5bdcb3f0d.png)

**Comment by derrickmehaffy** [comment]
@kamalbennani it seems running this:
```
query {
  grsites(where: { siteID: "287"}) {
    id
    siteID
  }
}
```

Works fine you're right. Not enough sleep. :laughing: Getting the hang of filtering with GraphQL
