### ISSUE TITLE
Error 403 in JS only but POSTman works

### ISSUE THREAD

**Issue by 6lackknight** [strapi/strapi#2406]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.14.5
- **Database**: Mongo
- **Operating system**: MacOS 10

**What is the current behavior?**
Whenever I try to create objects from the front-end JS I get error 403 forbidden, even though I supply a valid jwt. I can be able to use Postman and create objects without getting error 403

**Steps to reproduce the problem**
I used this code:
```
    newPost: function () {
      // Request API.
      axios
        .post(`http://localhost:1337/posts`, {
          headers: {
            Authorization: `Bearer ${this.$session.get('jwt')}`
          },
          caption: this.caption + '',
          profile: this.$session.get('profile_id')
        })
        .then(response => {
          // Handle success.
          console.log(
            'Well done, your post has been successfully created: ',
            response.data
          )
        })
        .catch(error => {
          // Handle error.
          console.log('An error occurred:', error)
        })
    }
```

**What is the expected behavior?**
I should be able to get the Post back in the response object

**Suggested solutions**
No idea

**Comment by derrickmehaffy** [comment]
@6lackunicorn `application/json` as a header, and post request data needs to be the same. :smiley:

**Comment by 6lackunicorn** [comment]
I updated to this:

```
     // Request API.
      axios
        .post(`http://localhost:1337/posts/`, {
          headers: {
            Authorization: `Bearer ${this.$session.get('jwt')}`,
            'Content-Type': 'application/x-www-form-urlencoded'
          },
          caption: this.caption + '',
          profile: this.$session.get('profile_id')
        })
        .then(response => {
          // Handle success.
          console.log(
            'Well done, your post has been successfully created: ',
            response.data
          )
        })
        .catch(error => {
          // Handle error.
          console.log('An error occurred:', error)
        })
    }
```

which still is not working, the CORS from the server is accepting wildcard origin.

**Comment by derrickmehaffy** [comment]
@6lackunicorn depends on what your sending but in talking with @lauriejim it is best not to send `application/x-www-form-urlencoded`. That can cause way too many errors, you should be sending rawJSON data for now until more testing and work is done on the `application/x-www-form-urlencoded`

**Comment by 6lackunicorn** [comment]
Changed post request data to match application/json header
 
 ```
  newPost: function () {
      // Request API.
      axios
        .post(`http://localhost:1337/posts/`, {
          headers: {
            Authorization: `Bearer ${this.$session.get('jwt')}`
          },
          data: {'caption': this.caption + '', 'profile': this.$session.get('profile_id') + ''}
        })
        .then(response => {
          // Handle success.
          console.log(
            'Well done, your post has been successfully created: ',
            response.data
          )
        })
        .catch(error => {
          // Handle error.
          console.log('An error occurred:', error)
        })
    }
```

I've been coding all night please forgive me if I am missing something simple 😬

**Comment by mashiro11** [comment]
Old post, but for future ones who end up here like me:
Got exactly same situation: authorized only POST method working on postman, not working with axios.
Fixed it instead of calling axios.post(), calling:
```
axios({
        method: 'POST',
        url: 'http://localhost:1337/post',
        headers: {
          Authorization: `Bearer ${localStorage.getItem('token')}`
        },
        data: payload
      })
```
got hint here:
 https://stackoverflow.com/questions/45524973/always-failed-when-post-data-with-json-body-raw

**Comment by notTHATmsn** [comment]
> Old post, but for future ones who end up here like me:
> Got exactly same situation: authorized only POST method working on postman, not working with axios.
> Fixed it instead of calling axios.post(), calling:
> 
> ```
> axios({
>         method: 'POST',
>         url: 'http://localhost:1337/post',
>         headers: {
>           Authorization: `Bearer ${localStorage.getItem('token')}`
>         },
>         data: payload
>       })
> ```
> 
> got hint here:
> https://stackoverflow.com/questions/45524973/always-failed-when-post-data-with-json-body-raw

This ended up being the answer for me. I'd love to understand the difference between `axios.post` and `axios` with `method: 'POST'` in the options and why that would matter.

**Comment by derrickmehaffy** [comment]
```
axios({
        method: 'POST',
        url: 'http://localhost:1337/post',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('token')}`
        },
        data: payload
      })
```

Need to include the content-type

**Comment by aikhan** [comment]
I am doing a simple fetch call, I have cross checked everything 3 times. For some reason fetch failing but postman is working.

```
const fetchCountryInfo = async () => {
	const jwtToken = sessionStorage.getItem('jwtToken');
	const response = await fetch(URL_COUNTRIES, {
		method: 'GET',
		headers: {
			Accept: 'application/json',
			'Content-Type': 'application/json',
			Authorization: jwtToken
		}
	});
	const data = await response.json();
	if (response.status >= 400) {
		throw new Error(data.errors);
	}
	return data;
};
```

My token has bearer already appended to it.

**Comment by derrickmehaffy** [comment]
@aikhan 

```

Authorization: `Bearer ${jwtToken}`

```

**Comment by StringsOfArrays** [comment]
```
await axios({
        method: 'POST',
        url: `${process.env.GATSBY_API}/auth/send-email-confirmation`,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${jwt}`
        },
        data: email
      });
```

Well, I am doing exactly as it was told here in the post ... yet I get a 400 response :(
What am I missing?

**Comment by rotarrares** [comment]
This problem is a real bummer, I have it too.

**Comment by derrickmehaffy** [comment]
> This problem is a real bummer, I have it too. Nothing seems to work on fixing it. I get a 403 error back from the server.

Can you post up a question on our forum: https://forum.strapi.io/c/support/7 and include some of your sample code you are using to make the request?

**Comment by Tellisense** [comment]
> > Old post, but for future ones who end up here like me:
> > Got exactly same situation: authorized only POST method working on postman, not working with axios.
> > Fixed it instead of calling axios.post(), calling:
> > ```
> > axios({
> >         method: 'POST',
> >         url: 'http://localhost:1337/post',
> >         headers: {
> >           Authorization: `Bearer ${localStorage.getItem('token')}`
> >         },
> >         data: payload
> >       })
> > ```
> > 
> > 
> > got hint here:
> > https://stackoverflow.com/questions/45524973/always-failed-when-post-data-with-json-body-raw
> 
> This ended up being the answer for me. I'd love to understand the difference between `axios.post` and `axios` with `method: 'POST'` in the options and why that would matter.

Thanks a bunch man that worked for me, I wish that the Strapi team can update their documentation.  This took hours to figure out something so simple.

**Comment by AsmaRahimAliJafri** [comment]
Really strange but when I consoled the bearer token on my backend, it showed me spaces and a colon in my Authorization parameter. **_I removed the colon and spaces after the bearer token and it worked!_**

```
axios({
    method: "get",
    headers: {
      'Authorization': `Bearer ${props.jwtToken}`, **// see how the bearer token now has a single space**
      'Content-Type': 'application/json'
    },
    url: `${process.env.url}${props.companyId}/${props.date}`,
  })
```
