### ISSUE TITLE
Additional options to mongodb connector

### ISSUE THREAD

**Issue by rosinwang** [strapi/strapi#2409]
Mongoose may cause a disconnected exception when there has been no data communication for a long time between strapi and mongodb server. This is caused by the setting `server: { auto_reconnect: false }` in the default mongoose setting, and currently there may be no way to add settings such as `{
server: {
          auto_reconnect: true,
          reconnectTries: Number.MAX_VALUE,
          reconnectInterval: 1000,
          socketOptions: {keepAlive: 1, connectTimeoutMS: 30000}
        }
}` to the `connectOptions` in `strapi-mongoose/lib/index.js`. 

So, the feature that allows users to add customised options to the connectOptions would bring more flexibility to dive in mongoose or mongodb, which is expected.

**Comment by lauriejim** [comment]
Related to https://github.com/strapi/strapi/issues/2257

**Comment by lauriejim** [comment]
A PR is open about this issue.
