### ISSUE TITLE
Webpack reference path unreachable during setup

### ISSUE THREAD

**Issue by Zealder-Jude** [strapi/strapi#2410]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: MySQL
- **Operating system**: MacOS 10.14.1

**What is the current behavior?**
`npm run setup` produces error:

`/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js:65
    throw new Error('Impossible to access to ${serverConfig}');`

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**
I was able to fix by updating:
`/strapi/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js:47`
to:
`const templateConfiguration = require(path.join(adminPath, 'node_modules', 'strapi-utils', 'lib', 'templateConfiguration'));`

**Comment by lauriejim** [comment]
Hello @Zealder-Jude .

I need more information to be sure to understand.

Did you run `npm run setup` in the mono repo bu following the contribution guide ?
Or in an app generated by a global install of Strapi ?
Or a dev mode app ?

**Comment by Zealder-Jude** [comment]
Hi @lauriejim, 

I followed the instructions [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to create a local **repo** and **--dev** version  of strapi (which I believe symlink the `./admin` folder from my local repo). All works well but when I want to build using `npm run setup` per instructions [here](https://strapi.io/documentation/3.x.x/advanced/customize-admin.html#build), that's when the error occurs. 

According to this code:
https://github.com/strapi/strapi/blob/585800b7b98093f596759b296a43f89c491d4f4f/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js#L47

It expects to find an exported module`templateConfiguration` in the path as per url below, but it doesn't exist in repo:
https://github.com/strapi/strapi/blob/master/packages/strapi-utils/index.js

The correct path is according to repo:
https://github.com/strapi/strapi/blob/master/packages/strapi-utils/lib/templateConfiguration.js

So the code should be changed to:
`const templateConfiguration = require(path.join(adminPath, 'node_modules', 'strapi-utils', 'lib', 'templateConfiguration'));`

**Comment by lauriejim** [comment]
Okay thank you for these details.
@soupette can help you when he will have time.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
