### ISSUE TITLE
Integer value not work for filter

### ISSUE THREAD

**Issue by wiseideal** [strapi/strapi#2411]
**Informations**
- **Node.js version**: 11.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0 alpha.15
- **Database**: Mongodb 4.0.3
- **Operating system**: mac 10.13.6

**What is the current behavior?**

I cant query data by integer field

**Steps to reproduce the problem**
simply add a integer filed named vcode under model Apps, 

**What is the expected behavior?**

then query Apps?vcode=12 or Apps?vcode_gt=12 
it returns an empty array allways

change the query to http://localhost:1337/Apps?vcode_ne=12 It pulls all the data out

**Suggested solutions**
dont have a clue.I am new to nodejs

**Comment by lauriejim** [comment]
Reverted the PR that open this issue.
