### ISSUE TITLE
Can't filter on decimal value

### ISSUE THREAD

**Issue by paul11223** [strapi/strapi#2412]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MongoDB v4.0.4
- **Operating system**: macOS 10.14.1

**What is the current behavior?**

Unable to query data by decimal field.

**Steps to reproduce the problem**

Create a content type called test.
Add three fields, a string, a decimal number, an integer number. Input the same value for all three fields.

Then I added two entries. This is my data below: http://localhost:1337/tests
<img width="690" alt="screen shot 2018-11-30 at 19 04 30" src="https://user-images.githubusercontent.com/37067618/49326960-772f7880-f562-11e8-9c40-222d8e9ea6cd.png">

When I run the following query(filtering the integer field) http://localhost:1337/tests?payrollInteger_gt=2
I get the first entry that is greater than 2 
<img width="690" alt="screen shot 2018-11-30 at 19 04 24" src="https://user-images.githubusercontent.com/37067618/49326967-a9d97100-f562-11e8-9921-8f729c53eab1.png">

When I want to filter the decimal field. The data is empty. http://localhost:1337/tests?payrollDecimal_gt=2 or 2.00
<img width="690" alt="screen shot 2018-11-30 at 19 04 16" src="https://user-images.githubusercontent.com/37067618/49326974-d097a780-f562-11e8-8777-2783fa5e1ced.png">

Here's my model file at Test.settings.json :
<img width="263" alt="screen shot 2018-11-30 at 19 06 19" src="https://user-images.githubusercontent.com/37067618/49326976-e4430e00-f562-11e8-90b7-0442a187725c.png">

**What is the expected behavior?**

Should be able to filter the query for the decimal values.

**Suggested solutions**

**Comment by lauriejim** [comment]
This issue has been fixed in the `beta` version of strapi.
I haven't be able to reproduce with the `beta.11`
