### ISSUE TITLE
Can't save session to Redis 

### ISSUE THREAD

**Issue by wemod123** [strapi/strapi#2418]
**Informations**
- **Node.js version**: v11.0.0
- **NPM version**: v6.4.1
- **Strapi version**: alpha.15
- **Database**: redis
- **Operating system**: ubuntu 18

**background**
There is session/redis features in documents, and I try to save the session to local redis db (can be online redis db in productoin), while when I look into the document, there was no clear guideline how to do this, I tried with my poor understanding, but it not wok.

**Steps to reproduce the problem**

with the default setting of `./config/environments/developments/request.json`:
```
{
  "session": {
    "enabled": true,
    "client": "cookie",
    "key": "strapi.sid",
    "prefix": "strapi:sess:",
    "secretKeys": ["mySecretKey1", "mySecretKey2"],
    "httpOnly": true,
    "maxAge": 86400000,
    "overwrite": true,
    "signed": false,
    "rolling": false
  },
  "logger": {
    "level": "info",
    "exposeInContext": true,
    "requests": false
  },
  "parser": {
    "enabled": true,
    "multipart": true
  }
}
```
I change it to below code, following [this instruction](https://strapi.io/documentation/3.x.x/configurations/configurations.html#request)
```
{
  "session": {
    "enabled": true,
    "client": "redis",
    "settings": {
      "database": 2,
      "port": 6379,
      "host": "127.0.0.1",
      "password": ""
    },
    "key": "strapi.sid",
    "prefix": "strapi:sess:",
    "secretKeys": ["mySecretKey1", "mySecretKey2"],
    "httpOnly": true,
    "maxAge": 86400000,
    "overwrite": true,
    "signed": false,
    "rolling": false
  },
  "logger": {
    "level": "debug",
    "exposeInContext": true,
    "requests": true
  },
  "parser": {
    "enabled": true,
    "multipart": true
  }
}
```
but the above code obviously do not consistent with other [database setting](https://strapi.io/documentation/3.x.x/configurations/configurations.html#database) ( it have settings field, by do not have connector etc, ), but anyway I try it firstly, run strapi start, below error will following:
`error (middleware:session) please provide connection for the session store
`
then I add "connection" key to the request.json file:
```
...
 "session": {
    "enabled": true,
    "client": "redis",
    "connection":"redis",
    "settings": {
      "database": 2,
      "port": 6379,
      "host": "127.0.0.1",
      "password": ""
    },
    "key": "strapi.sid",
...
```
and also add database setting in `./config/environments/developments/database.json`, and install strpi-hook-redis :
```
...
    "redis": {
      "connector": "strapi-hook-redis",
      "settings": {
        "client": "redis",
        "database": 2,
        "port": 6379,
        "host": "127.0.0.1",
        "password": ""
      },
      "options": {
        "debug": false
      }
    }
...
```
after that, run strapi start again, will got bellow error:
```
debug ⛔️ Server wasn't able to start properly.
error Cannot find module '....../node_modules/koa-redis'
```
Then I install the koa-redis module,
After these steps,  no errors was reported when server started normally.

**but:** I could not get session stored in redis db (I had tested local redis db work well);

I had not dive in core code to figure out how to debug this, 
Or probably I made some simple mistake, please check

**Suggested solutions**
not yet

**Comment by lauriejim** [comment]
Hello @wemod123 , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by wemod123** [comment]
Hello @lauriejim,

Have you reproduce this?
I have actually reproduced this in the latest version alpha17.

And one obvious [help documents ](https://strapi.io/documentation/3.x.x/configurations/configurations.html#database)dis-consistence is:
![image](https://user-images.githubusercontent.com/26819270/50499639-3013a500-0a86-11e9-9a33-e01e23b2d4d9.png)

Here the connection is `strapi-redis` but it should be `strapi-hook-redis`,  right?
While this `strapi-hook-redis` module firstly missing the `kao-redis` dependencies... and will not be work.

**Comment by derrickmehaffy** [comment]
@wemod123 Redis plugin hasn't been ported over to v3 currently AFAIK. Only Postgres/MySQL

**Comment by wemod123** [comment]
Hi @derrickmehaffy , thank you for your reply.
In that case, the documents about redis need be update, to avoid some mis-understanding.

> Also, I noticed in the [repo package](https://github.com/strapi/strapi/tree/master/packages/strapi-hook-redis), there are `strapi-hook-redis` pacakge seems keep updating. 
> Probably better to document the redis-plugin road-map, good for others understanding.
