### ISSUE TITLE
Images attribute duplicate entries in response

### ISSUE THREAD

**Issue by JayWelsh** [strapi/strapi#2420]
**Informations**
- **Node.js version**: v10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: MongoDB 
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
I am receiving duplicate entries for each item when queried via GraphQL

**Steps to reproduce the problem**
Created new content type:
![screenshot from 2018-12-02 14-48-03](https://user-images.githubusercontent.com/14224459/49341758-b2ad6e00-f65a-11e8-917d-60e7545c41e2.png)

Made a GraphQL request as follows:
![screenshot from 2018-12-02 14-46-30](https://user-images.githubusercontent.com/14224459/49341765-c22cb700-f65a-11e8-9560-412bdb7ed730.png)

Duplicate records in response, despite MongoDB showing 4 distinct records:
![screenshot from 2018-12-02 14-47-21](https://user-images.githubusercontent.com/14224459/49341769-d83a7780-f65a-11e8-9465-c1a7a7ab01a3.png)

**What is the expected behavior?**
4 items in response. Received 16. Each Carouselslide is returned 4 times in the response.

**Suggested solutions**
I am not sure why this is happening. I apologise if I am doing something wrong. :)

**Comment by JayWelsh** [comment]
Thanks a lot @lauriejim , I really appreciate the response! :+1:

**Comment by lauriejim** [comment]
This issue have been fixed with this PR - https://github.com/strapi/strapi/pull/2380
