### ISSUE TITLE
Can't store JSON string format in string attribute

### ISSUE THREAD

**Issue by berniezhao11** [strapi/strapi#2421]
**Informations**
- **Node.js version**:  10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: MongoDB
- **Operating system**: Ubuntu and Windows

**What is the current behavior?**
Using admin UI, when doing a `PUT` to a document with string filed, and supply the string field with a JSON string like `{"foo":"bar"}`, it fails with error `Cast to string failed for value \"{ foo: 'bar' }\" at path ...`

**Steps to reproduce the problem**
Create a document type with a string field.
Create a new document for that type in Admin UI.
Type `{"foo":"bar"}` into the string field and click save.
Error shows up and document is not saved.

**What is the expected behavior?**
String field should allow any valid string input as long as it's a valid unicode string.

**Suggested solutions**
Thanks

**Comment by lauriejim** [comment]
Hello @berniezhao11 !

Thank you to report this issue!
I suggest you to use `JSON` attribute type to store your json value.

**Comment by crushy26** [comment]
Hi, even I came across the same issue. 

'Cast to string failed for a [json] value' while updating the record containing JSON string.

I am able to store but not update the record containing the JSON string. 
/PUT request works successfully, for now adjusting with it whenever I have to update an record.

If it can be solved by you guys, it would be really helpful.

**Comment by derrickmehaffy** [comment]
@crushy26 It's likely your JSON string in the JSON field isn't valid JSON if it is throwing an error.

**Comment by soupette** [comment]
@crushy26 I believe that the issue will be solved with the group features.

<img width="1138" alt="Screenshot 2019-07-31 at 14 50 15" src="https://user-images.githubusercontent.com/13311463/62213172-9f49d280-b3a2-11e9-88b7-52876c9d23c2.png">
