### ISSUE TITLE
beforeUpdate (and other hooks) not including all attributes

### ISSUE THREAD

**Issue by funkhauscreative** [strapi/strapi#2422]
**Informations**
- **Node.js version**: v8.9.0
- **NPM version**: 5.5.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MySQL/Bookshelf
- **Operating system**:  MacOS Mojave

**What is the current behavior?**
When I create a new entry, the beforeCreate method is fired. I already found out, that because of relations, a beforeUpdate is also fired in order to set relations on the newly inserted entry. But the model in that hook only includes the relation attributes

**Steps to reproduce the problem**
1.  Use admin panel to create a new entry that has a relation
2. Check beforeUpdate hooks overgiven model.

**Suggested solutions**
Always overgiving the "whole" model to the hooks.

**Main reason**
I would like to create some more things with the new entry (or an updated entry), i.e. calling a foreign API, auto generate specific fields etc. **So I need a hook with a complete set of attributes for a "insert" event as well as an "update" event..** Whats the best way to do this? Currently only "afterSave" gives me all attributes, but thats one event to late, because the dataset is already saved...

**Comment by lauriejim** [comment]
Hello @funkhauscreative !

LifeCycle function are bind to `Model` instance of bookshelf.

When your request a POST route it call the `add` service of your API.
To be able to manage well relation we first create the entry without relations
```
// Extract values related to relational data.
const relations = _.pick(values, Work.associations.map(ast => ast.alias));
const data = _.omit(values, Work.associations.map(ast => ast.alias));

// Create entry with no-relational data.
const entry = await Work.forge(data).save();
```
And then we manage relations
```
// Create relational data and return the entry.
return Work.updateRelations({ id: entry.id , values: relations });
```

That is why in your beforeCreate you don't receive relations data.
