### ISSUE TITLE
i create one type and show 2 type in sidebar

### ISSUE THREAD

**Issue by mehdiraized** [strapi/strapi#2423]
how to fix this problem ?

<img width="589" alt="screen shot 1397-09-12 at 10 53 45" src="https://user-images.githubusercontent.com/4368004/49359139-6c075480-f6ea-11e8-8f16-2179d7a5c2e7.png">

**Informations**
- **Node.js version**: 11.2.0
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.14.3
- **Database**: Mongodb
- **Operating system**:  Macos

**Comment by lauriejim** [comment]
Hello @mehdiraized , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.
Thank you.

**Comment by mehdiraized** [comment]
hi @lauriejim 
i create content type with name health_center and see this issue

**Comment by lauriejim** [comment]
Please use lowercase name.
In last version of strapi we force to lowercase to avoid this issue.
