### ISSUE TITLE
 POST /auth/local/register times out if "Enable email confirmation" is ON

### ISSUE THREAD

**Issue by logicware** [strapi/strapi#2425]
**Informations**
- **Node.js version**: v10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.15
- **Database**: PostgreSQL
- **Operating system**: Linux Mint 19

**What is the current behavior?**
I am running a test project on Heroku. It sends password reset emails fine, but the "send email" code gets stuck.

**Steps to reproduce the problem**
1. Turn "Enable email confirmation" ON.
2. Set response email address in the templates.
3. Create a user with POST /auth/local/register. It times out if "Enable email confirmation" is ON, the user is created though.

**What is the expected behavior?**
It should send an email at the users email address to confirm the email.

**Suggested solutions**
use `to: user.attributes.email,` in the options in `strapi.plugins['email'].services.email.send` instead of just `user.email` or convert `user` to JSON before using the attributes directly. It fixed it for me.

**Comment by lauriejim** [comment]
Hello @logicware.

I think the Heroku server is not able to send email from your Node.js instance.
By default Strapi use `nodemailer` to send email. I suggest you to move to an other email provider that use a online service to send email.

More documentation here: https://strapi.io/documentation/3.x.x/guides/email.html#usage

**Comment by logicware** [comment]
But it is sending emails!

**Comment by Elfoslav** [comment]
Still not working in v3.2.5
