### ISSUE TITLE
Strapi breaks when creating a one-to-many-relation

### ISSUE THREAD

**Issue by OriginUnknown** [strapi/strapi#2426]
**Informations**
- **Node.js version**: 11.2.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.5
- **Database**: MongoDB
- **Operating system**: High Sierra (v10.13.6 )

**Background information**
- A merchant can have one or more locations
- Each location BELONGS TO one merchant

**What is the current behaviour?**
- View hangs with the the spinner icon spinning indefinitely
- No errors are printed out to the console

![merchant_record_selected_broken_journey](https://user-images.githubusercontent.com/11762349/49368845-c521b900-f6e7-11e8-93d3-91f82a279bfc.png)

**Steps to reproduce the problem**
GIVEN
- that the `content type builder` option is selected on the dashboard AND
- the location content type is selected AND
- the `Add new field` button is selected AND
- the `relation` option is selected AND
- the merchant collection is selected from the RHS drop down menu AND
- the **HAS MANY** relation button is created and saved AND
- the continue button is clicked AND
- the save button is clicked AND
- the merchant collection is selected from the dashboard on the LHS AND
- a list of merchant records appear

WHEN
- a record is selected from the merchant collection list

**What is the expected behaviour?**
- the merchant record should load with details about that selected merchant AND
- a list of locations associated with that merchant should populate the drop down component for that merchant

**Suggested solutions**
- Each object within the Merchant collection/model has an `userId` property, a unique id which is identical to and matches with the `merchantId` property for each object within the Location collection/model. I don't know whether this is possible as I'm new to Strapi and mongoDB/Mongoose but seeing as there's a key within both collections that connects each location with a merchant, is there a way to make that connection either via the admin panel or by manually writing some code within the strapi app to forge this behaviour

**Comment by soupette** [comment]
Hi @OriginUnknown Do you have a demo repository that we can check?

**Comment by OriginUnknown** [comment]
It's a company repository that has some sensitive data on there so I have to be very careful about sharing the repo over the net. Sorry to be a pain :/

**Comment by OriginUnknown** [comment]
If it helps, I've been told that there's an issue with strapi and mongoDB when it comes to camel casing. I can't confirm whether that's the case because I cannot find any errors in the console log or the network tab within the browser. I had a read of your comment in https://github.com/strapi/strapi/issues/2131#issuecomment-430580261 and I want to try and delete the core_store schema to see if that helps but I can't locate the file at the moment

**Comment by derrickmehaffy** [comment]
@OriginUnknown it isn't a file it is in your database

**Comment by derrickmehaffy** [comment]
But yes you should not be using any camelcase, spaces, or symbols in your model name or any fields

**Comment by OriginUnknown** [comment]
Hi @derrickmehaffy; Thanks for getting back to me - much appreciated. TBH I'm new to mongoDB so concepts like 'core store' are pretty alien to me so please bear with me. Nonetheless, there is a `core_store` file inside the mongoDB that I'm using to extract data from and looking at its construct, it's also using camel casing to reflect the properties already within the mongoDB I'm using (I guess??). I don't think I'm supposed to alter the camel cased properties within the DB so I'll need to come up with a work around or some sort solution to get passed this.

**Comment by OriginUnknown** [comment]
Will revisit at a later date

**Comment by jeremyrajan** [comment]
@OriginUnknown, this is still happening. I am using MySQL though :/
