### ISSUE TITLE
Content type Builder doesn't work

### ISSUE THREAD

**Issue by mikinovation** [strapi/strapi#2429]
My Content type Builder doesn't work when I deploy strapi@3.00-alpha15.0 with pm2 but it can work without pm2, only "strapi start". Content type Builder doesn't show on left side bar.
How to deploy strapi? Please help,  thanks.

**Comment by lauriejim** [comment]
Hello @mikinovation !

In production env you are not supposed create/edit/delete content type. So we hide it from the menu in production env
