### ISSUE TITLE
Refused to load data:image/jpeg;base64 ... because it does not appear in the img-src directive of the Content Security Policy

### ISSUE THREAD

**Issue by stiko** [strapi/strapi#2434]
**Informations**
- **Node.js version**:  v10.11.0
- **NPM version**: 6.4.1
- **Strapi version**:  v3.0.0-alpha.16
- **Database**: Mongo
- **Operating system**: OS X

**What is the current behavior?**
When I drag & drop an image into a media field it does not show the image and gives an error in the console log
`Refused to load data:image/jpeg;base64 ... because it does not appear in the img-src directive of the Content Security Policy`
This happens only in production

**Steps to reproduce the problem**
It has to be in production. Drag and drop an image into a media field

**What is the expected behavior?**
It should behave the same way local does. it should show the image even before saving

**Suggested solutions**

**Comment by stiko** [comment]
For those who get this error
Add `data:` to `csp.policy.img-src` in `config/environment/your_env/security.json`
```
"csp": {
    "enabled": true,
    "policy": [
      {
        "img-src": "'self' http: data:"
      },
      "block-all-mixed-content"
    ]
  },
```

**Comment by naru6be** [comment]
I have fixed the issue by modifying Springboot security configurtion header class .

Please find screenshots of the problem and the issue.


https://www.ittechnical.solutions/2019/12/images-not-loading-in-angular8-app-with.html
