### ISSUE TITLE
 cannot find module 'strapi-utils'

### ISSUE THREAD

**Issue by narayanan-git** [strapi/strapi#2436]
**Informations**
- **Node.js version**: 
- **npm version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 

**What is the current behavior?**
After upgrading to alpha-16,  I'm getting cannot find 'strapi-utils' error message. Looks like 'strapi-utils' package is missing in package.json

**Steps to reproduce the problem**
upgrade strapi to alpha-16

**What is the expected behavior?**

  
![strapi-error](https://user-images.githubusercontent.com/310446/49559309-65403380-f8dc-11e8-8d32-d1464fe3f1de.png)

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Version DIFF between Strapi v15 to Strapi v16:

![image](https://user-images.githubusercontent.com/8593673/49559935-be549b00-f8cd-11e8-943e-329eedca7266.png)

Told @narayanan-git to re-add the package to his `package.json` and re-run `npm i` and that seems to have fixed the issue.

@lauriejim was there a reason the utils package was removed by default from the `package.json`?

**Comment by lauriejim** [comment]
It's because you don't follow the Mongoose migration.
I think you still have `const { models: { mergeStages } } = require('strapi-utils');` in your services and you have to remove it.

**Comment by lauriejim** [comment]
Migration guide: https://github.com/strapi/strapi/wiki/migration-guide-alpha.15-to-alpha.16
