### ISSUE TITLE
Add support for GraphQL Apollo server tracing

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2437]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

(Feature Request not submitted to Product board as I plan to start playing with adding this via a PR myself.)

**Please describe your feature request:**

Per the following: 
https://github.com/apollographql/apollo-server/tree/master/packages/apollo-tracing
https://github.com/apollographql/apollo-tracing

I'm requesting that the Apollo server tracing be enabled so that we can see live performance metrics of a GraphQL based query to determine load and plan out/negate potential damaging query and mutation requests.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy we should create a configuration file and disable the tracing by default.

**Comment by derrickmehaffy** [comment]
I agree, I haven't looked in depth with this yet, but I could see where they may be small performance decreases with it enabled. I only noticed it as playground supports the tracing feature.
