### ISSUE TITLE
AWS S3 upload provider is not showing

### ISSUE THREAD

**Issue by dajer93** [strapi/strapi#2439]
**Informations**
- **Node.js version**: v10.13.0
- **NPM version**: v6.4.1
- **Strapi version**: v3.0.0@alpha.16
- **Database**: mongoDB 3.6.3
- **Operating system**: ubuntu 18.04

**What is the current behavior?**
The AWS S3 upload provider is not showing up in the Upload plugin's Provider settings. 

**Steps to reproduce the problem**
I have run `npm install strapi-provider-upload-aws-s3@alpha --save` to install the provider inside the `plugins/upload/` folder. 

**What is the expected behavior?**
To be able to select the AWS S3 provider.

**Suggested solutions**
I realized that the method `loadProviders` in `plugins/upload/config/functions/bootstrap.js` is responsibe for loading the providers. Since the AWS S3 provider's foldername starts with `strapi-provider-...`, I changed the
```js
const uploads = _.filter(node_modules, (node_module) => {
        return _.startsWith(node_module, ('strapi-upload'));
});
``` 
to
```js
const uploads = _.filter(node_modules, (node_module) => {
        return _.startsWith(node_module, ('strapi-provider'));
});
```
and it works like a charm for me. My suggestion is to check for both strings `strapi-upload` and `strapi-provider` when loading providers.

**Comment by lauriejim** [comment]
Hello @dajer93 !
I think you migrate from older version of Strapi to alpha.16
You not migrate your plugin upload. 
- Alpha.16 bootstrap file: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/config/functions/bootstrap.js#L30
- Migration guides: https://github.com/strapi/strapi/wiki
