### ISSUE TITLE
"Special" characters in Mongo passwords are not being escaped

### ISSUE THREAD

**Issue by tomsutton1984** [strapi/strapi#2441]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0@alpha.16
- **Database**: CosmosDB (mongo)
- **Operating system**:  WSL

**What is the current behavior?**
```
strapi start
[2018-12-06T15:36:08.487Z] debug ⛔️ Server wasn't able to start properly.
[2018-12-06T15:36:08.489Z] error Unescaped slash in userinfo section
```

**Steps to reproduce the problem**
Use a mongo password that includes special characters, such as / or =

**What is the expected behavior?**
Special characters should be escaped or URL encoded

**Suggested solutions**
Editing [strapi-hook-mongoose #85](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js#L85) to URL encode the password string, appears to resolve the issue.

```
await instance.connect(uri || `mongodb${isSrv ? '+srv' : ''}://${username}:${encodeURIComponent(password)}@${host}${ !isSrv ? ':' + port : '' }/`, connectOptions); ```

**Comment by lauriejim** [comment]
Hello @tomsutton1984 , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by tomsutton1984** [comment]
Thanks @lauriejim - I'll review the contributing guide and get a PR over to you

**Comment by derrickmehaffy** [comment]
@tomsutton1984 I posted the spot I believe that needs to be changed. I believe the password just needs to be URI encoded if you are using the SRV address for authentication see the following comment in the duplicate issue here: https://github.com/strapi/strapi/issues/2466#issuecomment-446276453

**Comment by tomsutton1984** [comment]
> @tomsutton1984 I posted the spot I believe that needs to be changed. I believe the password just needs to be URI encoded if you are using the SRV address for authentication see the following comment in the duplicate issue here: [#2466 (comment)](https://github.com/strapi/strapi/issues/2466#issuecomment-446276453)

You're absolutely correct, my mistake. I'll update accordingly.

**Comment by joshwnj** [comment]
Hi @tomsutton1984 thanks for posting this. I also ran into this issue today :)

Just wanted to check, is there a reason the PR #3091 was closed without being merged?

**Comment by tomsutton1984** [comment]
Hi @joshwnj, no problem - glad that it was useful!

I closed the PR as I hadn't pulled from the latest master branch - I'll be submitting another PR once the freeze is over
