### ISSUE TITLE
Controller ctx.throw(400, 'msg') goest to client with a duplicated message

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#2444]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**:  6.4.1
- **Strapi version**: alpha.16
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

body.message has duplicated text

**Steps to reproduce the problem**

In a simple controller, when signaling an error like this:

```javascript
api_method = async (ctx, next) {
  ...
  if (error_ condition) {
      return ctx.throw(400, 'msg');
  }
  ...
}
```

You get this: 

```javascript
{
   message: 'msg: msg',
   statusCode: 400,
   error: 'Bad Request'
}
```
**What is the expected behavior?**

On client get this:

```javascript
{
   message: 'msg',
   statusCode: 400,
   error: 'Bad Request'
}
```
**Suggested solutions**

Fix by not duplicating the message.

**Comment by lauriejim** [comment]
Hello @jacargentina !

I don't find the method you use in the documentation https://github.com/hapijs/boom#http-4xx-errors
Use `badRequest` to fire `400` error code

**Comment by jacargentina** [comment]
I'm using ctx.throw from strapi context, why do you point me on the boom docs? Boom is used by strapi...I'm not using it directly. Maybe If u look my PR you can get what the problem is?

**Comment by lauriejim** [comment]
I point Boom cause you want to fire 400 status code and Boom is by default in Strapi and offer this feature.

Will check your PR when I will have time.
