### ISSUE TITLE
Creating model instance returns 404 error (but creates the instance)

### ISSUE THREAD

**Issue by pwkrz** [strapi/strapi#2447]
**Informations**
- **Node.js version**: 10.12.0
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MongoDB (4.0.4)
- **Operating system**: Windows 10 

**What is the current behavior?**

When sending a POST request to `<server>/<modelName>` the server returns a 404 error, but correctly creates an instance of the model.

**Steps to reproduce the problem**

1. Create a new model in the Strapi dashboard.
2. Using a global admin account I send a `POST` request to the model path (e.g. `.../zunos`) with a body, e.g.:
```
{"_id":null,"wid":null,"firstName":"Jan","lastName":"Kowalski","description":"// 123","email":"jan@kowalski.pl","telephone":"123","password":null,"media":null}
```

**What is the expected behavior?**

If the model is successfully created, the response should indicate success.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello! Can you give me the name of the content type you create please.
And send me also the model attributes you set to your content type.

Did you custom something else in Strapi or you just create your content type and try to use the generated API ?

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by pwkrz** [comment]
Hi, sorry about the delay responding.

Here is an example content type that causes the problem:
```
{
  "connection": "default",
  "collectionName": "zuno",
  "info": {
    "name": "zuno",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "xname": {
      "default": "",
      "type": "string"
    },
    "wid": {
      "default": "",
      "type": "string"
    }
  }
}
```
I send a POST request to `http://localhost:1337/zunos` with the payload: `{ wid: null, _id: null, xname: 'whatever' }`

The response is: `{"statusCode":404,"error":"Not Found","message":"Not Found"}`

In the problematic model I do not introduce any customizations, but I did customize the User model as per these instructions: https://github.com/WINKgroup/winkit-cli-angular/#conf-server-strapi

**Comment by lauriejim** [comment]
Okay, you haven't to send `_id` key when you create an entry.
