### ISSUE TITLE
Checking internet connectivity leads to unnecesary failure

### ISSUE THREAD

**Issue by lunchboxer** [strapi/strapi#245]
**Node.js version**: 8.4.0
**npm version**: 5.4.0
**Strapi version**: 1.6.3
**Operating system**: Ubuntu 17.04

https://github.com/strapi/strapi/blob/9e406db588eab7eecd15235e76211bc7a14577d1/bin/strapi-login.js#L39

The strapi cli commands "login" and "link" both start with a preliminary check that internet access is available before beginning. It does a quick dns.resolve(google.com) which fails on my system with an error "warn: no internet access..." and exit(1). I live in China where this check fails, but I have working internet access. I don't expect the internet to rebuild itself around my edge case, but it's an unnecessary failure. "link" and "login" both only need to be able to access http://studio.strapi.io so why not check for access to that address instead? Whether the rest of the internet is accessible or google.com is irrelevant to the task. In my case, I have access to all three, but it still fails.

My proposed fix:
bin/strapi-login.js#L39 and bin/strapi-link.js#56
-dns.resolve('google.com', function (err) {
+dns.lookup('studio.strapi.io', function (err) {

Eventually I'll figure how to do this as a pull request.

This should check for what really matters, and get around any weird dns resolution set-ups that cause it to unnecessarily fail when in China, using a VPN, etc.

**Comment by Aurelsicoko** [comment]
@lunchboxer Sorry for the delay... You're right, this is a mistake, we should definitely check the URL of the Studio instead of pinging Google. I'll be happy to merge your pull request. You can make one on the [1.6.3 branch](https://github.com/strapi/strapi/tree/1.6.3).

**Comment by lunchboxer** [comment]
My very first pull request. Forgive any unconventional practice, also tell me if there is something I should have done or written differently.

**Comment by Aurelsicoko** [comment]
I merged your PR in the 1.6.3 branch. We will release the 1.6.4 with your updates this Friday. Thanks again for your contribution!
