### ISSUE TITLE
Add db argument to srv

### ISSUE THREAD

**Issue by lvnilesh** [strapi/strapi#2451]
**Information**
- **Node.js version**:  v10.14.1 
- **NPM version**:  v6.4.1
- **Strapi version**: commit hash 2edd056
- **Database**:  mongo with replicas and +srv string
- **Operating system**:  Google Kubernetes Engine running linux and custom docker based on commit 2edd056 

**What is the current behavior?**

There is no ENV to specify `+srv`

**Steps to reproduce the problem**

Can't setup mongo replicas without resorting to manually editing configuration database.json

`strapi new appname` is missing a parameter where I could specify `+srv=true`

    strapi new <name> \
    --dbclient=<dbclient> \
    --dbhost=<dbhost> \
    --dbport=<dbport> \
    --dbname=<dbname> \
    --dbusername=<dbusername> \
    --dbpassword=<dbpassword> \
    --dbssl=<dbssl> \
    --dbauth=<dbauth>

https://strapi.io/documentation/3.x.x/cli/CLI.html#strapi-new

**What is the expected behavior?**

Specifically, the command line `strapi new app` should take `command line params` to `NONINTERACTIVELY` save `database.json` like this. 

    {
      "defaultConnection": "default",
      "connections": {
        "default": {
          "connector": "strapi-hook-mongoose",
          "settings": {
            "client": "mongo",
            "host": "some.mongodb.net",
            "srv": true,
            "port": 27017,
            "database": "strapi",
            "username": "username",
            "password": "password"
          },
          "options": {
            "authenticationDatabase": "admin",
            "ssl": true
          }
        }
      }
    }
Need ENV to set `+srv connection: true (default false)` that sets -> `scope.database.settings.srv`

Related to https://github.com/strapi/strapi-docker/issues/71 and https://github.com/strapi/strapi-docker/issues/52

**Comment by lauriejim** [comment]
Hello @lvnilesh , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check this file: https://github.com/strapi/strapi/blob/master/packages/strapi/bin/strapi-new.js#L48

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
