### ISSUE TITLE
Multiple roles per user

### ISSUE THREAD

**Issue by EvgeniyZo** [strapi/strapi#2455]
Is there any way to have users with 2 or 3 roles?

**Comment by lauriejim** [comment]
Hello @EvgeniyZo thank you for this question.

Actually it's not possible.

But we plan to add it in next version of users and permissions https://portal.productboard.com/strapi/c/8-administrators-roles-permissions

**Comment by developerc4fl** [comment]
Hello
am using strapi 3.6.3 and would like to know if the above feature is now available

**Comment by EvgeniyZo** [comment]
Checked month ago. It`s not, at least in community edition. Enterprise edition may have this.

**Comment by derrickmehaffy** [comment]
> Checked month ago. It`s not, at least in community edition. Enterprise edition may have this.

The Enterprise RBAC does have this yes, but even in enterprise the users-permissions plugin doesn't.

**Comment by baermathias** [comment]
@derrickmehaffy will the users-permission plugin (community edition) have this in v4 ?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy will the users-permission plugin (community edition) have this in v4 ?

Not initially no, I'm not sure if/when we plan to implement this.

**Comment by jusiho** [comment]
2024 and nothing

**Comment by lyova011** [comment]
It is 2024 and strapi hasn't solved this yet.
Strapi is used for big projects by many developers and in big projects there are many cases that users roles are merged, how you are not solving this ? 
@strapi-cla @lauriejim
