### ISSUE TITLE
Install fail: npm WARN react-ga@2.5.6 requires a peer of prop-types@^15.6.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by anhhai2810** [strapi/strapi#2456]
**Informations**
- **Node.js version**: v10.14.1
- **npm version**: 6.4.1
- **Strapi version**: strapi@3.0.0-alpha.16
- **Database**: MySQL
- **Operating system**: Windows

**What is the current behavior?**

$ npm install strapi@alpha -g
npm WARN deprecated joi@10.2.2: This version is no longer maintained. Please upg                                                                                                                                                 rade to the latest version.
C:\Users\datlp6\AppData\Roaming\npm\strapi -> C:\Users\datlp6\AppData\Roaming\np                                                                                                                                                 m\node_modules\strapi\bin\strapi.js
npm WARN react-ga@2.5.6 requires a peer of prop-types@^15.6.0 but none is instal                                                                                                                                                 led. You must install peer dependencies yourself.
npm WARN react-ga@2.5.6 requires a peer of react@^15.6.2 || ^16.0 but none is in                                                                                                                                                 stalled. You must install peer dependencies yourself.

**Steps to reproduce the problem**
⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:

👌 Your new application videos is ready at D:\Strapi\videos.

⚡️ Change directory:
$ cd videos

⚡️ Start application:
$ strapi start

$ strapi start
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Strapi\videos\admin\controllers\Admin.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
**What is the expected behavior?**

**Suggested solutions**

**Comment by aurelienbobenrieth** [comment]
I actually have this error as well. 

npm WARN deprecated joi@10.2.2: This version is no longer maintained. Please upgrade to the latest version.
C:\Users\aurel\AppData\Roaming\npm\strapi -> C:\Users\aurel\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js
npm WARN react-ga@2.5.6 requires a peer of prop-types@^15.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ga@2.5.6 requires a peer of react@^15.6.2 || ^16.0 but none is installed. You must install peer dependencies yourself.

I can't even create a new project. The creation seems to crash when I am asked to choose a the kind of DB I want. And it crashes no matter which DB type I select.

**Help wanted here as well.**

**Comment by aurelienbobenrieth** [comment]
Little up right there ! 

Any solutions anyone ? I am not managing to do any proper installation no matter on which comp I try (each one running on Windows).

**Comment by lauriejim** [comment]
Did you check this part of the wiki.
Maybe can help https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

**Comment by CTBUdzy** [comment]
hello.I first use strapi.I report an error when I install strapi with the statement "npm install strapi@alpha -g".It display ‘**npm WARN deprecated joi@10.2.2: This version is no longer maintained. I still can't understand the solution you mentioned above.Please upgrade to the latest version**.Can you tell me in detail how to solve this problem.
’

**Comment by aurelienbobenrieth** [comment]
There is apparently no proper solution to our problems. The only work-around seems to use a Linux distros (even though I did not have the time to try it yet).

**Comment by derrickmehaffy** [comment]
@CTBUdzy Windows isn't support meaning no support is provided for it here. Your welcome to look into it, but right now it isn't a priority for the Strapi team. You will need to use WSL (Windows Subsystem Linux) or a linux virtual machine. (Google WSL, lots of helpful guides)

But yes @aurelienbobenrieth not right now, eventually but considering 99.99% of users will be hosting on linux, the development environment reflects that.

**Comment by derrickmehaffy** [comment]
@stact Windows isn't supported, see my previous comment

**Comment by derrickmehaffy** [comment]
When you install with `npm install strapi -g` you are installing Strapi-v1 which is no longer maintained.

**Comment by tlchatt** [comment]
Having this problem on Ubuntu also.

**Comment by aurelienbobenrieth** [comment]
I'll add to that topic that the use of WSL is not really optimal since you won't be able to use MongoDB as it is not yet supported yet in WSL.

**Comment by justinriggio** [comment]
I get the same warnings on macOS and Unbutu 18.x

Is there a fix for this issue?

**Comment by tlchatt** [comment]
I believe accidentally running the npm install command as sudo was what caused this issue for me in Ubuntu and uninstall and reinstall without sudo fixed it.

**Comment by justinriggio** [comment]
@tlchatt  What node and npm ver are you running on Ubuntu? and did you use apt or NVM?

**Comment by tlchatt** [comment]
Ubuntu 18.04.1 LTS, 
node --v11.6.0
npm 6.5.0-next.0
Not sure about that last question.

**Comment by soupette** [comment]
WelThe prop-types dependency is installed in the `strapi-helper-plugin` package which the admin has in its dependencies like React and so on. So I sure that the installation failed because you are on a Windows. @lauriejim and @Aurelsicoko fixed the installation on Windows.

@lauriejim I'll let you close the issue if you feel like so, I'm convinced that React-ga is not the primary cause of a failed install.
