### ISSUE TITLE
Get stuck with add new data in production env.

### ISSUE THREAD

**Issue by ssshooter** [strapi/strapi#2458]
**Informations**
- **Node.js version**: v11.4.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.2
- **Database**: mLab
- **Operating system**: Heroku-18 stack, based on Ubuntu 18.04

**Informations**
It work in local dev env, the problem occur after deploy to heroku.

**What is the current behavior?**
infinite loading after click add new data
![image](https://user-images.githubusercontent.com/13051472/49718158-405d0f00-fc94-11e8-8eb9-aacbecfa8af8.png)
no error after click
![image](https://user-images.githubusercontent.com/13051472/49718249-84e8aa80-fc94-11e8-86ca-62b34fb0b6a1.png)
post data and got 500
![image](https://user-images.githubusercontent.com/13051472/49718282-96ca4d80-fc94-11e8-9336-c0ed9dd97413.png)

**Steps to reproduce the problem**
I add content type with content type builder as the documentation. absolutely work in dev env.

**Suggested solutions**
/

**Comment by lauriejim** [comment]
Hello @ssshooter , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.
Thank you.

**Comment by ssshooter** [comment]
@lauriejim updated

**Comment by lauriejim** [comment]
Please can you try with the last version of Strapi (alpha.16)

**Comment by lauriejim** [comment]
For your Postman screen, please use `raw` format

**Comment by derrickmehaffy** [comment]
Form-data is not supported for normal post requests, only for the upload plugin. As Jim has said, all other requests need to be sent as application/json

**Comment by petre2dor** [comment]
@ssshooter I think I've seen this issue before. It seems that after certain changes in content types, there is a schema stored in the DB that needs to be deleted. Have a look here: https://github.com/strapi/strapi/issues/1957#issuecomment-430567677
That seems to be just an workaround, I do know if an actual fix is available.

**Comment by ssshooter** [comment]
@petre2dor thank you 😊
delete `plugin_content-manager_schema` -> redeploy ->work

**Comment by buithuyen** [comment]
@ssshooter I'm facing the same problem. How can I delete `plugin_content-manager_schema`. 
I use Heroku and mLab.
Thank you in advance.

**Comment by lauriejim** [comment]
You have to connect your Database UI software to the mLab database and delete the raw.

**Comment by har17bar** [comment]
> @petre2dor thank you 😊
> delete `plugin_content-manager_schema` -> redeploy ->work

sorry can you explain how to delete , i am using on server postgrSQL

**Comment by har17bar** [comment]
> > @petre2dor thank you 😊
> > delete `plugin_content-manager_schema` -> redeploy ->work
> > @lauriejim
> 
> sorry can you explain how to delete , i am using on server postgrSQL

**Comment by har17bar** [comment]
if you using postgreSQL
1. go to heroku type in terminal value of Heroku CLI
![Screen Shot 2019-06-23 at 02 15 04](https://user-images.githubusercontent.com/26884501/59969393-5b6edc80-955d-11e9-9bb4-0ef17bfa3c13.png)
2. to se all datatables in psql command line interface type \dt 
![Screen Shot 2019-06-23 at 02 23 16](https://user-images.githubusercontent.com/26884501/59969443-f23b9900-955d-11e9-8aa8-a20633ae4d57.png)
