### ISSUE TITLE
I can't see the auth providers in the User content type

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2467]
**Informations**
- **Node.js version**: v10.0.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.16
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

In the admin panel, in the User content type...
I can't see the auth provider with which the user has registered.

**Steps to reproduce the problem**

Go to: `/admin/plugins/content-manager/user?source=users-permissions`

**What is the expected behavior?**

In the past I see the auth provider.

**Comment by derrickmehaffy** [comment]
@abdonrd it looks like it got accidentally added to be removed from the content manager. I'll be submitting a PR to fix but in the mean time you can just remove this block here and it should show up again:

https://github.com/strapi/strapi/blob/568626c0a206d1d6f25f75dfd2425304df7a8c1b/packages/strapi-plugin-users-permissions/config/layout.js#L16-L18
