### ISSUE TITLE
PUT on a given model with relations throws error

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#2470]
**Informations**
- **Node.js version**: 10 
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.16
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

When trying to `PUT /model/THE_ID` with an instance which has subitems (relation) i get this error

```
TypeError: Cannot read property 'parent' of null
    at params.parseRelationships.Object.keys.reduce (/Users/javiercastro/git/strapi/packages/strapi-hook-mongoose/lib/relations.js:98:32)
```

**Steps to reproduce the problem**

Create two models Parent and Chils. Try to update a given Parent via default generated API. When trying to update a given Parent, adding some childs, the `PUT` api call fails

**What is the expected behavior?**

Just work (tm)

**Suggested solutions**

Generated controllers for mongoose, have the routes declared like this:

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/features",
      "handler": "Feature.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/features/count",
      "handler": "Feature.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/features/:_id",
      "handler": "Feature.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/features",
      "handler": "Feature.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/features/:_id",
      "handler": "Feature.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/features/:_id",
      "handler": "Feature.destroy",
      "config": {
        "policies": []
      }
    }
  ]
}
```

Where the primary key is `_id`, which goes directly to the `ctx.params`

But looking at the `packages/strapi-hook-mongoose/lib/relations.js` file, it tries everywhere to get the `id` from params, NOT the `_id` as it comes really from `params` parameter.

So, i see two possible solutions:

- Refactor `packages/strapi-hook-mongoose/lib/relations.js` file everywhere is needed. _I think this is the best solution_
- Refactor controller template in `packages/strapi-generate-api/json/routes.json.js` to use `:id`, not `:id`

I'm open to work on a PR to fix this.

**Comment by derrickmehaffy** [comment]
@jacargentina your trying to send a nested PUT request?

like:
```json
{
    "title": "blahblah",
    "body": "blahblah",
    "comments: [
        {
            "id": 1
            "comment": "blahblah"
        },
        {
            "id": 2
            "comment": "blahblah"
        }
    ]
}
```

Right now I don't think it is possible but has been asked for, also with POST'ing multiple entries aka Bulk post requests

**Comment by jacargentina** [comment]
@derrickmehaffy exactly like that. So if it is not supported, this should be clossed ?

**Comment by derrickmehaffy** [comment]
Yes I believe so, I will close it for now, we can reopen in the future if/when it becomes supported

**Comment by abbeyseto** [comment]
Hi @derrickmehaffy is this now supported? I need to do something along this lines

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy is this now supported? I need to do something along this lines

No, nested relation PUT/POST is something we are looking at for the v4 but it's not something we will backport to the v3. You will need to send either the id or an array of ids.
