### ISSUE TITLE
Enumeration value is not set by default

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2471]
**Informations**
- **Node.js version**: v10.0.0
- **NPM version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.16
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**
**Steps to reproduce the problem**

I have `Battle` model with an `stage` attribute like this, because is an optional field:

```
"stage": {
  "default": "",
  "type": "enumeration",
  "enum": [
    "",
    "final",
    "semiFinal",
    "thirdAndFourthPlace",
    "quarterFinals",
    "roundOf16",
    "groupStage"
  ]
},
```

It works with this query:

```
{
  battles {
    _id
    team1 {
      slug: username
    }
    team2 {
      slug: username
    }
  }
}
```

But it doesn't work if I add the `stage` attribute:

```
{
  battles {
    _id
    team1 {
      slug: username
    }
    team2 {
      slug: username
    }
    stage
  }
}
```

The error is:

> `"message": "Expected a value of type \"ENUM_BATTLE_STAGE\" but received: \"\"",`

**What is the expected behavior?**

Allow empty `stage`, because it is not required and the default value is and empty string (`""`).

**Comment by abdonrd** [comment]
In fact, I would like it to be unnecessary to add empty string `"'` as an option in the `enum` array.
I think not adding the `required` field should be enough.

**Comment by Aurelsicoko** [comment]
The enumeration field should be converted to `null` if the value is empty instead of trying a workaround like that. What happens if you remove the `""` value at the beginning of allowed values?

**Comment by abdonrd** [comment]
@Aurelsicoko I can't select empty option:

<img width="430" alt="screenshot 2018-12-13 at 15 32 05" src="https://user-images.githubusercontent.com/1007051/49945080-4cdba480-feec-11e8-900e-cd1870016778.png">

**Comment by abdonrd** [comment]
Perhaps the solution is to allow dropdowns of enumerations that are not required to have an option to leave the field empty?

**Comment by Aurelsicoko** [comment]
@abdonrd The second solution seems the good one. The issue is coming from the frontend. It should allow an empty option. However, it should consider the `required` property. If the field is required, the empty option should not be available. Otherwise, it should be the case.

Can you submit a PR to handle this new use case?

**Comment by abdonrd** [comment]
@Aurelsicoko If you (or @soupette) can guide me a little, I can try it next week!

**Comment by Aurelsicoko** [comment]
@soupette is the guy you're looking for 👍

**Comment by soupette** [comment]
@abdonrd  I have tried something but the back-end doesn't allow to save an enumeration field has null.

I'm not sure if this is what you expect but here's my attempt and some code:

```
{
  "connection": "default",
  "collectionName": "product",
  "info": {
    "name": "product",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string"
    },
    "enum": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "a",
        "b",
        "c"
      ]
    }
  }
}
```

## Front-end modifications
```
// File: strapi-plugin-content-manager/admin/src/containers/EditPage/index.js

renderEdit = () => {
  // ...
  <Edit
    // ...
    isCreating={this.isCreating()}
  />
}

// File: strapi-plugin-content-manager/admin/src/components/Edit/index.js

class Edit extends React.Component {
  state = { shouldUpdateEnumFields: true };

  componentDidUpdate() {
    if (this.state.shouldUpdateEnumFields && this.props.isCreating) {
      this.orderAttributes()
        .forEach(attr => {
          const details = get(this.props.schema, ['editDisplay', 'availableFields', attr]);
          // Retrieve the input's bootstrapClass from the layout
          const layout = this.getInputLayout(attr);
          const appearance = get(layout, 'appearance');
          const type = !isEmpty(appearance) ? appearance.toLowerCase() : get(layout, 'type', getInputType(details.type));

          // TODO: need to handle required && default value ....
          if (type === 'select') {
            const target = {
              type: 'select',
              name: attr,
              value: '',
            };
  
            this.props.onChange({ target });
          }
        });

        this.setState({ shouldUpdateEnumFields: false });
    } 
  }
}

```

**Comment by abdonrd** [comment]
@soupette something like this #2531?

Take care that `selectOptions` from https://github.com/strapi/strapi/pull/2531/files#diff-ae65e6ec17e7002037c903bbf1dd943cR79 doesn't work. How should we do it?

**Comment by soupette** [comment]
@abdonrd the selectOptions isn't read by the logic you need to send the value in the target see my comment in #2531. The only problem is trying to set the enum field with an empty value, I unable to make it with Mongoose and I pretty sure it will work the same with bookshelf

**Comment by kenberkeley** [comment]
My current solution is:

```
non_specific,A,B,C,...
```

**Comment by abdonrd** [comment]
Any news here? Thanks in advance!

**Comment by Aurelsicoko** [comment]
@abdonrd No news here. I can only suggest you submit a PR to make it happen 👍

**Comment by soupette** [comment]
@Aurelsicoko I can add a placeholder for the select it will fix the issue

**Comment by abdonrd** [comment]
Hello @soupette!

I just tried the `@next` npm tag and I have see the placeholder. Thanks!

But the placeholder is only the first time:

<img width="468" alt="Screenshot 2019-08-30 at 09 37 23" src="https://user-images.githubusercontent.com/1007051/64002353-1e4d3a80-cb0a-11e9-9c7d-9b27d737df0a.png">

When I select an option, the placeholder disappears:

<img width="458" alt="Screenshot 2019-08-30 at 09 37 28" src="https://user-images.githubusercontent.com/1007051/64002376-2ad19300-cb0a-11e9-9ddc-2eb0e89097dc.png">

**Could we have the placeholder also for when we want to delete a selected option?**

**Comment by abdonrd** [comment]
I also just realized that if the `Enumeration` is marked as required field, the placeholder does not appear, and the first option is selected by default.

Could we keep the placeholder, and show a red warning (like the other fields) that it is necessary to select one of the options? Not letting select the placeholder, of course.

**Comment by abdonrd** [comment]
And one last thing!

1. Create a new `Battle` with the empty `stage` Enumeration.
2. Make this query in GraphQL:
```
{
  battles {
    _id
    stage
  }
}
```

I have an error:

```
"message": "Expected a value of type \"ENUM_BATTLE_STAGE\" but received: \"\"",
```

**Comment by soupette** [comment]
> Hello @soupette!
> 
> I just tried the `@next` npm tag and I have see the placeholder. Thanks!
> 
> But the placeholder is only the first time:
> 
> <img alt="Screenshot 2019-08-30 at 09 37 23" width="468" src="https://user-images.githubusercontent.com/1007051/64002353-1e4d3a80-cb0a-11e9-9c7d-9b27d737df0a.png">
> 
> When I select an option, the placeholder disappears:
> 
> <img alt="Screenshot 2019-08-30 at 09 37 28" width="458" src="https://user-images.githubusercontent.com/1007051/64002376-2ad19300-cb0a-11e9-9ddc-2eb0e89097dc.png">
> 
> **Could we have the placeholder also for when we want to delete a selected option?**

We can work something out however, the option should disabled in case it is a required field.



> I also just realized that if the `Enumeration` is marked as required field, the placeholder does not appear, and the first option is selected by default.
> 
> Could we keep the placeholder, and show a red warning (like the other fields) that it is necessary to select one of the options? Not letting select the placeholder, of course.

Yes we can do that but I have added the behaviour of selected the first item in case of a required field that doesn't have a default value.

**Comment by abdonrd** [comment]
> We can work something out however, the option should disabled in case it is a required field.

Yes, makes sense! Thanks @soupette!

> Yes we can do that but I have added the behaviour of selected the first item in case of a required field that doesn't have a default value.

I get it! I think this new option would be better.
To have a default option, we could always use the `default` attribute.

**Comment by soupette** [comment]
> To have a default option, we could always use the default attribute.

Exactly! Currently the fields are also populated with the default values.

**Comment by abdonrd** [comment]
Hi @soupette!

There are any news about this? We continue to have problems with this.

Thanks in advance!

**Comment by abdonrd** [comment]
JFI, I just tried with the last version (`v3.0.0-beta.18.1`), and it still happens.

**Comment by soupette** [comment]
Ok I will take a look at it

**Comment by abdonrd** [comment]
Since it has been a long time, I will summarize how I would like it to work.

Adding this `enumeration` field with five options.
It is a not required field, since it doesn't have `"require": true`.

```json
"stage": {
  "type": "enumeration",
  "enum": [
    "final",
    "thirdAndFourthPlace",
    "semifinals",
    "quarterfinals",
    "eighthFinals"
  ]
},
```

The admin show a placeholder:

<img width="458" alt="Screenshot 2019-12-19 at 14 04 23" src="https://user-images.githubusercontent.com/1007051/71175736-8e71fe80-2268-11ea-9893-3434d5a62ba9.png">

When click the selector:

<img width="454" alt="Screenshot 2019-12-19 at 14 04 31" src="https://user-images.githubusercontent.com/1007051/71175771-a21d6500-2268-11ea-9bf0-374eb65b4d94.png">

Select an option:

<img width="453" alt="Screenshot 2019-12-19 at 14 04 45" src="https://user-images.githubusercontent.com/1007051/71176340-f07f3380-2269-11ea-8be0-0e7cc0b4b0ee.png">

And if now you want to remove the selected option, select the placeholder option:

<img width="458" alt="Screenshot 2019-12-19 at 14 04 23" src="https://user-images.githubusercontent.com/1007051/71175736-8e71fe80-2268-11ea-9893-3434d5a62ba9.png">

And if you add the `"require": true` to the field, the placeholder is disabled:

<img width="451" alt="Screenshot 2019-12-19 at 14 24 59" src="https://user-images.githubusercontent.com/1007051/71177052-620bb180-226b-11ea-882f-e77d5827a159.png">

**Comment by Tansito** [comment]
Same use case here!
