### ISSUE TITLE
Cannot add new user

### ISSUE THREAD

**Issue by eComEvo** [strapi/strapi#2472]
**Informations**
- **Node.js version**: 11.4.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MySQL 5.7
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
When I login to the admin panel, go to user management and click "Add new user" I am taken to a blank page at this URL:
http://example.com/admin/plugins/content-manager/user/create?redirectUrl=/plugins/content-manager/user?_limit=10&_page=1&_sort=id&source=users-permissions

**Steps to reproduce the problem**
1) login to the admin panel
2) go to user management
3) click "Add new user" button

**What is the expected behavior?**
New user creation page should show.

**Suggested solutions**

**Comment by javialon26** [comment]
@eComEvo are you behind a reverse proxy? see this issue #2424

**Comment by eComEvo** [comment]
@javialon26 yep! I'll look into that issue.

**Comment by eComEvo** [comment]
@javialon26 the following snippet posted by @gksander fixed this issue with the users:
```
location /content-manager {
  proxy_set_header X-Forwarded-Host 'strapi';
  proxy_pass http://localhost:1337;
}
```

**Comment by derrickmehaffy** [comment]
Marking this as closed as it is directly related to proxying, please see the linked issue here: https://github.com/strapi/strapi/issues/2424

And the user @eComEvo has stated it was resolved using the fix in the linked issue
