### ISSUE TITLE
Strapi new project freezes

### ISSUE THREAD

**Issue by sudip1072** [strapi/strapi#2474]
Strapi new project freezes with database name mongodb.I am using windows 8.1,node 10 LTS, npm>6,mongodb latest version. 
Pls help.

**Comment by lauriejim** [comment]
Hello @sudip1072 , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

And please check existing issue(closed)/ FAQ(in the wiki), there is the fix of your issue.

Thank you.

**Comment by derrickmehaffy** [comment]
@sudip1072 https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows
