### ISSUE TITLE
Special characters from attributes name break GraphQL

### ISSUE THREAD

**Issue by vesyrgy** [strapi/strapi#2477]
**Informations**
- **Node.js version**: 11.4.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MongoDB
- **Operating system**: Mac OS 10.12.6

**What is the current behavior?**
If I create and save content types with fields that contain spaces or special characters (like "@") in the name, the server attempts to restart and fails due to GraphQL syntax errors in the names of the content types.

**Steps to reproduce the problem**
1) Start Strapi
2) add GraphQL to the project
3) create a content type
4) add fields to the content type where the field names of the content type include special characters or spaces. 

**What is the expected behavior?**
There should be some kind of input validation on the content type fields so that they can't be saved if they are invalid (i.e. would produce GraphQL syntax errors)

**Suggested solutions**
1) Add input validation to the field input forms for Content Type Builder so that it's no longer possible to save inputs that generate GraphQL syntax errors. Allowed Content Type field names should follow GraphQL specs:
https://facebook.github.io/graphql/June2018/#sec-Names
2) Possibly convert spaces to underscores

**Comment by derrickmehaffy** [comment]
This should likely fall under: https://portal.productboard.com/strapi/c/14-validations

@Aurelsicoko can you modify the product board FR to include adminUI field level validations as well?

**Comment by Aurelsicoko** [comment]
This special case should be handled by the GraphQL plugin which should sanitize the name's attributes.

**Comment by maciejcieslik** [comment]
It's bigger problem as attributes names can't contain any special characters, this is big issue for localized backend where I want to add - for example - as post title attribute to post model "tytuł" and for content "Treść" - when i do that strapi throw error:

`(node:3576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-30T00:11:50.156Z] debug ⛔️ Server wasn't able to start properly.
[2019-03-30T00:11:50.157Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load`

and it will not start again.

So if strapi have something like alias for attribute, this would save the day, then I could just add attribute 'title' for API with alias name for backend "Tytuł" and voila...

**Comment by Aurelsicoko** [comment]
@soupette Did you fix this issue with the work you did on the content-type builder plugin?

**Comment by soupette** [comment]
No I didn't I can make a fix in a new PR though

**Comment by Aurelsicoko** [comment]
@maciejcieslik You can already have a different name for the attribute and the displayed label. The real issue is to sanitize the attribute name (remove special characters, spaces, etc).

We already started to enhance the CTB on this part, the frontend will sanitize the attribute name.

**Comment by MatheusRV** [comment]
Related with #1698?

Why not prevent special characters on web ui?

**Comment by Aurelsicoko** [comment]
I've already answered this question on the other issue.
