### ISSUE TITLE
Weir behaviour with the controller name of a generated API

### ISSUE THREAD

**Issue by soupette** [strapi/strapi#2478]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: I'm using the `master` branch
- **Database**: Mongodb
- **Operating system**:  Mac OSX Mojave

**What is the current behaviour?**

Given that I have created two different models:
- **Product**:
  - **name**: `string`
- **Tag**:
  - **name**: `string`

If I add two new routes in the `Product` model (`./api/product/config/routes.json`) as follows:

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/products",
      "handler": "Product.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/products/count",
      "handler": "Product.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/products/:_id",
      "handler": "Product.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/products",
      "handler": "Product.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/products/:_id",
      "handler": "Product.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/products/:_id",
      "handler": "Product.destroy",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/dummy",
      "handler": "Tag.dummy",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/foo",
      "handler": "Tag.find",
      "config": {
        "policies": []
      }
    }
  ]
}
```

And a `Tag.js` controller in `./api/product/controllers/` as follows

```
'use strict';

module.exports = {
  dummy: async (ctx, next) => {
    return { foo: 'bar' };
  },

  find: async (ctx, next) => {
    return { baz: 'bat' };
  },
};
```

 I'm expecting that if I request to `http://localhost:1337/dummy` or  `http://localhost:1337/foo` it should it the Tag controller from my Product model. Or what's currently happening is that the request hits the Tag controller from the Tag model

**Steps to reproduce the problem**

Explained above.

**What is the expected behavior?**
Well, it should hit the Tag controller from my Product model.

**Suggested solutions**

Let's find out!🤓🤯

**Comment by Aurelsicoko** [comment]
Not sure to understand this one. It seems to be the correct behavior, no?

**Comment by soupette** [comment]
@Aurelsicoko it definitely is the correct behaviour but I think that we should add a warning or something that says "Hey you can't create a Tag.js controller in the './api/product/controllers' folder since you already have a tag api..".

In fact with the example from above I'm expecting to hit the `./api/product/controllers/Tag.js` `dummy` method when requesting `/dummy` where in fact strapi tries to find the method in `./api/tag/controllers/Tag.js` which doesn't exist. Thus, leading to an error

**Comment by lauriejim** [comment]
I'm okay with you @soupette .
In fact it's the same issue as https://github.com/strapi/strapi/issues/1955 but for generated API.
I close this issue to have just one with the same topic.
In any case there is a link between these issue.
