### ISSUE TITLE
waterline hook migrate in production reset is not right

### ISSUE THREAD

**Issue by JunQiGenYuan** [strapi/strapi#248]
Hi.
I read the source code of v1.6.3. And found a line code like below, which seems not correct. 

https://github.com/strapi/strapi/blob/9e406db588eab7eecd15235e76211bc7a14577d1/lib/configuration/hooks/waterline/index.js#L117

strapi.config.orm.connections[definition.connection].migrate === **('alter' || 'drop')**

It would skip the drop migrate

Thanks.

**Comment by Aurelsicoko** [comment]
Hi @JunQiGenYuan, thanks for pointing this out! I'll be happy to merge your pull request if you can make one. We didn't have time to fix the issues on v1.6.3, the entire team is focused on the new version.
