### ISSUE TITLE
Error on save content with required decimal field

### ISSUE THREAD

**Issue by sontranhcm** [strapi/strapi#2491]
**Informations**
- **Node.js version**: 10.14.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MongoDB version 4.0.3
- **Operating system**: Windows 10

I got problem on save new content with required decimal field. I create a new content-type Product. Inside it I created a field price (decimal) and this is a required field. When I enter the data and click save it show a toast for error "This Product,validation,failed,price,this,constructor is already taken". I created a new content type for testing with a decimal field and without required and this one can be saved normally. Please help me.

Thanks

**Comment by derrickmehaffy** [comment]
@sontranhcm Windows is not supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Please test using a supported OS.

**Comment by gonzochic** [comment]
@sontranhcm 
I have the same issue on Linux (Ubuntu 16.04).

I have a required filed of type decimal, and it errors when I am adding new items

```bash
[2018-12-23T08:30:09.852Z] debug POST /products (51 ms)
{ ValidationError: Product validation failed: price: this.constructor._checkRequired is not a function
    at ValidationError.inspect (/home/admin/clickr/node_modules/mongoose/lib/error/validation.js:59:24)
    at formatValue (util.js:561:31)
    at inspect (util.js:371:10)
    at Object.formatWithOptions (util.js:225:12)
    at Console.(anonymous function) (console.js:193:15)
    at Console.warn (console.js:210:31)
    at strapi.app.use (/usr/lib/node_modules/strapi/lib/middlewares/boom/index.js:34:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errors:
   { price:
      { ValidatorError: this.constructor._checkRequired is not a function
          at new ValidatorError (/home/admin/clickr/node_modules/mongoose/lib/error/validator.js:29:11)
          at validate (/home/admin/clickr/node_modules/mongoose/lib/schematype.js:893:13)
          at /home/admin/clickr/node_modules/mongoose/lib/schematype.js:946:11
          at Array.forEach (<anonymous>)
          at Float.SchemaType.doValidate (/home/admin/clickr/node_modules/mongoose/lib/schematype.js:902:19)
          at /home/admin/clickr/node_modules/mongoose/lib/document.js:1920:9
          at process._tickCallback (internal/process/next_tick.js:61:11)
        message: 'this.constructor._checkRequired is not a function',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'price',
        value: 2.98,
        reason:
         TypeError: this.constructor._checkRequired is not a function
             at Float.checkRequired (/home/admin/clickr/node_modules/mongoose/lib/schema/number.js:140:27)
             at model.requiredValidator (/home/admin/clickr/node_modules/mongoose/lib/schematype.js:695:18)
             at /home/admin/clickr/node_modules/mongoose/lib/schematype.js:928:28
             at Array.forEach (<anonymous>)
             at Float.SchemaType.doValidate (/home/admin/clickr/node_modules/mongoose/lib/schematype.js:902:19)
             at /home/admin/clickr/node_modules/mongoose/lib/document.js:1920:9
             at process._tickCallback (internal/process/next_tick.js:61:11),
        [Symbol(mongoose:validatorError)]: true } },
  _message: 'Product validation failed',
  name: 'ValidationError' }
```

Node.js version: 10.10
NPM version: 6.4.1
Strapi version: 3.0.0-alpha.17
Database: MongoDB version 4.0.2

**Comment by sontranhcm** [comment]
I use docker strapi on docker hub and still get the same error. Seem it's a bug of strapi.

**Comment by micbra** [comment]
I get the same error on MacOS X 10.13.6

**Comment by 8ctopotamus** [comment]
Same issue with trying to save required floats.

**Comment by lauriejim** [comment]
I confirm this issue thank you all for your feedback!
We will work on it soon as possible.

If any one can submit a PR to fix it, we will appreciate.

**Comment by lauriejim** [comment]
Same as this issue https://github.com/strapi/strapi/issues/2591#issuecomment-457830493

**Comment by gridviewdesign** [comment]
Has there been any progress on this bug yet?

**Comment by yodacom** [comment]
looking for a resolution too!

**Comment by lauriejim** [comment]
I was not able to reproduce this issue in last version of Strapi `alpha.26`

**Comment by janober** [comment]
I am running into the same problem when I have a required date field (createdAt):
```
This Workflow,validation,failed,created,At,Path,created,At,is,required is already taken
```

Totally unable to create any entries (at least unless I delete the "createdAt" field).

Version used: Strapi v3.0.0-alpha.26.2
On Ubuntu 18.04.2 LTS
Running the current docker-setup (without any changes) with MongoDb.

**Comment by derrickmehaffy** [comment]
@janober the created_At and updated_at (without the underscores on mongo) are generated by default. Most likely this is causing you a conflict.

**Comment by janober** [comment]
I just tried and with a different name it works fine. So that was really the problem.

Thanks a lot!

**Comment by TxHawks** [comment]
I'm having this with a `date` field, which is, well, a date.

Strapi 3.1.1 with a MongoDB database

**Comment by TxHawks** [comment]
It seems to only happen when a field is both `required` and `unique`. Can also reproduce with an SQLite database

**Comment by AlexNasonov** [comment]
The same thing happens with required boolean field
