### ISSUE TITLE
Graphql : set a specific role to registered user. [help]

### ISSUE THREAD

**Issue by ronaldaug** [strapi/strapi#2492]
#### This is not a bug related.

I try to update user role and it returns an error as below. 

## Expected type ID, found {_id:"5c10b5438928981467835ff9"}

<img width="600" alt="grapql error" src="https://user-images.githubusercontent.com/33022876/50039287-39e8e180-005e-11e9-84e8-bb12873dbebb.png">

It expects **_id** type to be **ID!**.
But, I don't know how to declare the **type of ID** in mutation.

Thanks in advance.

**Comment by ronaldaug** [comment]
As I am trying update users data,
Ok I am going to close this and wait for this [PR](https://github.com/strapi/strapi/pull/2380) .

**Comment by lauriejim** [comment]
Sorry for the trouble. We are doing our best to fix it soon as possible.
