### ISSUE TITLE
[Improvement request] Content Type: Enumeration

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2494]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Currently `Enumeration` only supports `value1,value2,value3`, but mostly we might prefer:

```js
[
  { label: 'label1 bla bla bla', value: 'value1' },
  { label: 'label2 bla bla bla', value: 'value2' },
  { label: 'label3 bla bla bla', value: 'value3' }
]
```

While `Relation` is too cumbersome for this scenario.

**Comment by kenberkeley** [comment]
For example, I am migrating from other CMS to Strapi
There is a field `stage<Enum Integer>: 0-dev, 1-testing, 2-staging, 3-prod`

Strapi's `Enumeration` only supports `0,1,2,3`, which is hard to understand without labels:

![image](https://user-images.githubusercontent.com/13287948/50042837-aa731b00-00bd-11e9-84c0-ca514673d9b1.png)

**Comment by derrickmehaffy** [comment]
@kenberkeley the problem is when using GraphQL, there are very strict standards that are put in place by graphQL that using those types of values is not possible. GraphQL is built by facebook and thus if you were to use those types of values, then attempt to install the GraphQL plugin it would break your project.

Right now there is currently no way to support them, you would need to pass this request to GraphQL itself, then once implemented there, Strapi could support it.

**Comment by derrickmehaffy** [comment]
You should be able to use:

```
0dev
1testing
2staging
3prod
```

and do some sort of translation on your frontend.

**Comment by kenberkeley** [comment]
You might misunderstand me... The preferred format should look like below:

```js
[{
  id: 1,
  stage: 0,
  title: 'Hello World'
}, {
  id: 2,
  stage: 3,
  title: 'Foo Bar'
}]
```

However, Strapi can only support the below format (if not using `Relation`):

```js
[{
  id: 1,
  stage: 'dev',
  title: 'Hello World'
}, {
  id: 2,
  stage: 'prod',
  title: 'Foo Bar'
}]
```

**Comment by kenberkeley** [comment]
My temporary solution:

```js
// models/<model_name>.settings.json
{
  "connection": "...",
  "collectionName": "...",
  "info": {...},
  "options": {...},
  "attributes": {
    ...
    "stage": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "dev",
        "testing",
        "staging",
        "prod"
      ]
    }
    ...
  }
}
```

```js
// models/<model_name>.js
module.exports = {
  // Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: async (model, attrs, options) => {
    model.stage = ({
      'dev': 0,
      'testing': 1,
      'staging': 2,
      'prod': 3
    })[model.stage]
  },

  // Before fetching a value.
  // Fired before a `fetch` operation.
  beforeFetch: async (model, columns, options) => {
    model.stage = ({
      0: 'dev',
      1: 'testing',
      2: 'staging',
      3: 'prod'
    })[model.stage]
  }
}
```

**Comment by derrickmehaffy** [comment]
@kenberkeley no I understand what you want, but in terms of symbols in enums with graphql installed there is no other way but to remove them. :disappointed:

**Comment by derrickmehaffy** [comment]
This is not a problem directly in strapi but a problem with GraphQL itself (upstream package) In what your trying to do, it might be best to have a `oneWay` relation as this does exactly what you want.

**Comment by kenberkeley** [comment]
OK, fine...

**Comment by kenberkeley** [comment]
Could it be this way?

```js
// api/project/models/Project.settings.json (current)
{
  "connection": "default",
  "collectionName": "project",
  "info": {
    "name": "project",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "stage": {
      "default": "",
      "type": "enumeration",
      "required": true,
      "enum": [
        "0",
        "1",
        "2",
        "3"
      ]
    },
    "title": {
      "default": "",
      "type": "string",
      "required": true
    }
  }
}
```

```js
// api/project/models/Project.settings.json (expected)
{
  "connection": "default",
  "collectionName": "project",
  "info": {
    "name": "project",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "stage": {
      "default": "",
      "type": "enumeration",
      "required": true,
      "enum": [
        { "label": "dev", "value": 0 },
        { "label": "testing", "value": 1 },
        { "label": "staging", "value": 2 },
        { "label": "prod", "value": 3 }
      ]
    },
    "title": {
      "default": "",
      "type": "string",
      "required": true
    }
  }
}
```

**Comment by farzer** [comment]
marked, i need this feature : )
