### ISSUE TITLE
Split the frontend date picker into 3 new types; date, datetime, and time

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2497]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Using the following react frontend parts I think we can easily split the current date field option into these three:

- date (2018/12/30) => https://www.npmjs.com/package/react-date-picker
- datetime (2018/12/30 01:02:03) => https://www.npmjs.com/package/react-datetime-picker
- time (01:02:03) => https://www.npmjs.com/package/react-time-picker

This FR falls in line with the current focus on bookshelf date functions: https://github.com/strapi/strapi/issues/2495

**Comment by Aurelsicoko** [comment]
I've created a card on Product Board https://portal.productboard.com/strapi/c/48-split-date-and-time-fields-in-multiple-components.

**Comment by derrickmehaffy** [comment]
Reopening this as I am going to start working on the backend

**Comment by derrickmehaffy** [comment]
you are correct @jasongitmail that was a typo, indeed it would be something like YYYY-MM-DD

**Comment by iRoachie** [comment]
Hey @derrickmehaffy is there any update on this?

**Comment by derrickmehaffy** [comment]
Last I spoke with @soupette he was in the process of adding in the buffetjs.io stuff. Once that is added it will be trivial to add in the new date stuff. No ETA yet but I think the buffet stuff will be in beta.18

**Comment by iRoachie** [comment]
Is there an ETA for beta.18 though? I'm not seeing buffetjs stuff on the product board.

**Comment by derrickmehaffy** [comment]
It won't be because it's not really a feature but a drop of legacy code and fixing with updated code. Not everything being worked on is directly in the roadmap. No ETA but typically distances between major releases is normally a few weeks.

I was testing out some of the new stuff in the develop branches and most looks okay but I know there is some other things in progress as well.

**Comment by iRoachie** [comment]
Very insightful! Thanks 🙏🏽

**Comment by soupette** [comment]
We talked with @Aurelsicoko and @alexandrebodin and we will split the date into these three fields. The feature will be available when we release the dynamic zones features. And here's what the new [datepicker will look like](https://buffetjs.io/storybook/?path=/story/custom--datetime).

**Comment by iRoachie** [comment]
Looks great @soupette. I'm guessing these changes are being made internally and not by external contributors?

**Comment by derrickmehaffy** [comment]
Yes they are

**Comment by iRoachie** [comment]
Alrighty, was just wondering if I could help anyway, but cool! Looking forward to it 💯

**Comment by scottydev** [comment]
This is really exciting, and just in time for our implementation 👍 Following

**Comment by aindong** [comment]
looking forward into these, I think it is logical to split
