### ISSUE TITLE
Case not respected on save data Postgres

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#2498]
**Informations**
- **Node.js version**: 10.10.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14
- **Database**: Postgres
- **Operating system**: Mac and Ubuntu

**What is the current behavior?**
the big I gets converted to small i: azure.interior24@example.com

**Steps to reproduce the problem**
executing the standard v3 code:
```
add: async (values) => {
    // Extract values related to relational data.
    const relations = _.pick(values, Userlogin.associations.map(ast => ast.alias));
    const data = _.omit(values, Userlogin.associations.map(ast => ast.alias));

    // Create entry with no-relational data.    
    const entry = await Userlogin.forge(data).save();

    // Create relational data and return the entry.
    return Userlogin.updateRelations({ id: entry.id , values: relations });
  },
```

**What is the expected behavior?**

Encounter in DB the exact same value: azure.Interior24@example.com

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@jmchza what strapi version are you using? `3.0.14` isn't a valid version, do you mean 3.0.0-alpha.14? If so you are quite a few versions behind

**Comment by jmchza** [comment]
Yes I meant that one: 3.0.0-alpha.14. sorry about that.

**Comment by derrickmehaffy** [comment]
@jmchza can you please test with the latest version (3.0.0-alpha.16) as v14 is quite old now and there was a major hotfix for it already.

**Comment by lauriejim** [comment]
What is the type of the attribute you use to store your email ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
