### ISSUE TITLE
The Many to Many relationship does not work correctly in Plugins

### ISSUE THREAD

**Issue by ririen** [strapi/strapi#2499]
**Informations**
- **Node.js version**: 10.14.2
- **NPM version**: 6.5.0
- **Strapi version**: Latest Git
- **Database**: MongoDB 4.0.4
- **Operating system**: Arch Linux

**What is the current behavior?**

The Many to Many relationship does not work correctly in Plugins. Each new "create" entry deletes all relations from all previous entries and the relation remains only in the newest "create".

**Steps to reproduce the problem**
1. Create a plugin using the official manual: https://strapi.io/documentation/3.x.x/plugin-development/quick-start.html
2. Create a Many to Many relationship with own plugin and the `users-permissions` plugin with the `users` table.
3. Add the entry with relations to the plugin.
4. Add another entry with relation to the plugin.

**What is the expected behavior?**
Creating a new entry with the relationship should not clean up the relationship of all previously created entries.

**Comment by lauriejim** [comment]
Did you have a projet on GitHub with the issue ?
It will help me to help you.

**Comment by yummyelin** [comment]
I have a similar issue. 

For example, a `user` has a many-many relationship `friends`. When adding a new friend into `friends`, I used:

 ```
await strapi.plugins['users-permissions'].services.user.edit(
  { _id: id }, 
  { friends: [newFriend.id]}
);
```

It doesn't insert `newFriend` into `friends`, instead, it overwrites `friends`. Now the user only has one friend left in `friends`.

Did I insert many-many relationship correctly?

**Comment by ririen** [comment]
@lauriejim I'm sorry for the lack of response. Unfortunately, I do not have such opportunities to do it because the project is private. It will co-create something, maybe create a test project.

@yummyelin Yes, indeed a very similar bug. For me, always a new relationship overwrites all previous ones not only in a given element but in all, as if there was a loop on the entire table.

**Comment by lauriejim** [comment]
Can you give me:
- The plugin name
- The model name
- and your relations attributes name

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
