### ISSUE TITLE
add model instances' method

### ISSUE THREAD

**Issue by JunQiGenYuan** [strapi/strapi#250]
version: v3.0

Is it a way to add custom to model instance that find or create?

If no, then I think could add code below into the strapi-mongoose
```
if (!_.isEmpty(definition.methods)) {
  _.forEach(definition.methods, (fn, methodName) => {
    collection.schema.method(methodName, fn);
  })
}
```
at https://github.com/strapi/strapi/blob/3d7b26df8f656c6c69463d2058503200ce6e684e/packages/strapi-mongoose/lib/index.js#L141

and use like this in [model].js:
```
module.exports = {
  methods: {
    validatePassword: function () {  ...some code goes here... }
  },
...
}
```

**Comment by Aurelsicoko** [comment]
Interesting... I like the idea but you can also use a service for that? Our goal is not to override the ORM we are using such as Mongoose or Bookshelf to be able to follow the new releases and patches the maintainers are doing on them.

**Comment by Aurelsicoko** [comment]
I'm closing this issue, feel free to submit this feature request on the [Community Vote](https://strapi.io/vote) page.
