### ISSUE TITLE
Graphql update mutation not updating, delete not deleting on mysql

### ISSUE THREAD

**Issue by merijnvanessen** [strapi/strapi#2503]
Hello,
I followed the documentation on graphql mutations : create, update and delete
https://strapi.io/documentation/3.x.x/guides/graphql.html

Create does work however, update doesnt update, and delete gives me an error.
Maybe I'm doing it al wrong here, but I'm stuck for hours now, so let's see.

nodejs v10.6.0
**fresh installation**
"strapi": "3.0.0-alpha.16",
"strapi-hook-bookshelf": "3.0.0-alpha.16",
"strapi-hook-knex": "3.0.0-alpha.16",
graphql "version": "3.0.0-alpha.16"

- Contenttype 'help', with one field 'title'
- Permissions authenticated all checked

mutation **update**
```
mutation {
  updateHelp(input: {
    where: {
      id: 1
    },
    data: {
      title: "John"
    }
  }) {
    help {
      title
    }
  }
}
```

gives me back
```
{
  "data": {
    "updateHelp": {
      "help": {
        "title": "test"
      }
    }
  }
}

```
So nothing is updated

And mutation **delete**
```
mutation {
  deleteHelp(input: {
    where: {
      id: 1
    }
  }) {
    help {
      title
    }
  }
}
```
_throws an error:_

`"message": "A model cannot be destroyed without a \"where\" clause or an idAttribute."
`
```
 "stacktrace": [
            "Error: A model cannot be destroyed without a \"where\" clause or an idAttribute.",
            "    at Sync.<anonymous> (/AMPPS/www/strapi/project/server/node_modules/bookshelf/lib/sync.js:219:13)",
```

**Comment by merijnvanessen** [comment]
I tested with mongo DB and both update or delete mutations are working

update
![schermafbeelding 2018-12-26 om 10 32 01](https://user-images.githubusercontent.com/23075300/50441229-0ded1c00-08fa-11e9-8972-5151b21c4f5b.png)

delete
![schermafbeelding 2018-12-26 om 10 36 24](https://user-images.githubusercontent.com/23075300/50441247-24937300-08fa-11e9-9784-87af566e248b.png)

**Comment by lauriejim** [comment]
Here is the same issue with the fix https://github.com/strapi/strapi/issues/2530
