### ISSUE TITLE
Markdown editor does not support split line ( divider / dividing line / <hr> )

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2505]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/13287948/50123801-449db380-02b6-11e9-8473-f9c98bcc5e12.png)

**Steps to reproduce the problem**

Copy and paste:
```
## Hyphens

---


## Asterisks

***


## Underscores
___
```

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/13287948/50124001-d0afdb00-02b6-11e9-8465-771e6a57e37d.png)

![image](https://user-images.githubusercontent.com/13287948/50124052-05bc2d80-02b7-11e9-9a82-be2e7a35f74c.png)

**Suggested solutions**

**Comment by soupette** [comment]
I am closing this issue as it has already been fixed.


![Screenshot 2020-08-07 at 14 15 52](https://user-images.githubusercontent.com/13311463/89644593-867ad380-d8b8-11ea-85bf-b2b7d27b9fe9.png)
