### ISSUE TITLE
config database it not work on 

### ISSUE THREAD

**Issue by blackcatpolice** [strapi/strapi#2506]
**Informations**
- **Node.js version**: v10.14.1 
- **NPM version**:  pm@6.4.1 
- **Strapi version**: 3.0.0@alpha 
- **Database**: 
- **Operating system**: windows 10

**What is the current behavior?**
When I select db option : MogonDB, the terminal not work on 

**Steps to reproduce the problem**
npm install strapi@alpha -g
strapi new test

� Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: MongoDB
......(here it's wait ...)

**What is the expected behavior?**
create strapi project

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0@alpha` What version?
`Operating system: windows 10` FYI windows isn't supported, try testing with WSL or linux
`Database:` make sure you fill out this spot even if it is referenced elsewhere

And as @wptheme4me said, Windows isn't supported see: https://github.com/strapi/strapi/issues/1281

I'm marking this issue as a duplicate.
