### ISSUE TITLE
Best practice to modify/map/trim APIs' output (for less verbose)

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2507]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

For example, there is a API `GET /companies`:

```json
[
  {
    "id": 23,
    "name": "Apple Inc",
    "code": "APPL",
    "industry": {
      "id": 5,
      "name": "Tech",
      "created_at": "2018-12-17T00:17:49.681Z",
      "updated_at": "2018-12-17T00:17:49.685Z"
    },
    "logo": {
      "id": 46,
      "name": "apple.png",
      "hash": "b2849a80c90043b3bba220637829a947",
      "sha256": "np5WzGw29OMAcW3wYK4YGxb-kvtsACSSUBMISt2yv8Y",
      "ext": ".png",
      "mime": "image/png",
      "size": "12.80",
      "url": "https://bucket.s3.region.amazonaws.com/b2849a80c90043b3bba220637829a947.png",
      "provider": "aws-s3",
      "public_id": null,
      "created_at": "2018-12-17T09:31:11.597Z",
      "updated_at": "2018-12-17T09:31:11.597Z"
    }
  },
  {
    "id": 24,
    "name": "Walmart Inc",
    "code": "WMT",
    "industry": {
      "id": 4,
      "name": "Retail",
      "created_at": "2018-12-17T00:19:34.381Z",
      "updated_at": "2018-12-17T00:19:34.185Z"
    },
    "logo": {
      "id": 48,
      "name": "walmart.png",
      "hash": "811f389a0eac4ca1be0b34192f7cc291",
      "sha256": "dh-rkjilH3i70qpd3v_dM3t1jZT4L1Afch9snVRcag8",
      "ext": ".png",
      "mime": "image/png",
      "size": "11.30",
      "url": "https://bucket.s3.region.amazonaws.com/811f389a0eac4ca1be0b34192f7cc291.png",
      "provider": "aws-s3",
      "public_id": null,
      "created_at": "2018-12-17T09:32:34.117Z",
      "updated_at": "2018-12-17T09:32:34.117Z"
    }
  }
]
```

It's too verbose. What the frontend merely needs is:

```json
[
  {
    "id": 23,
    "name": "Apple Inc",
    "code": "APPL",
    "industry": "Tech",
    "logo": "https://bucket.s3.region.amazonaws.com/b2849a80c90043b3bba220637829a947.png"
  },
  {
    "id": 24,
    "name": "Walmart Inc",
    "code": "WMT",
    "industry": "Retail",
    "logo": "https://bucket.s3.region.amazonaws.com/811f389a0eac4ca1be0b34192f7cc291.png"
  }
]
```

We need to trim the original output. However, there is no best practice or guides for this scenario.

***

Of course, we can do it in the controller:

```js
// api/company/controllers/Company.js
module.exports = {
  ...
  find: async (ctx) => {
    if (ctx.query._q) {
      const company = strapi.services.company.search(ctx.query).toJSON()
      ctx.body = trimmer(company) 
    } else {
      const companies = strapi.services.company.fetchAll(ctx.query).toJSON()
      ctx.body = companies.map(trimmer)
    }
  },
  ...
}

function trimmer (company) {
  return {
    ...company,
    industry: company.industry.name,
    logo: company.logo.url
  }
}
```

Well, it works but is hardly elegant.

***

How about do it in the model's lifecycle? Let's see:

```js
// api/company/models/Company.js
module.exports = {
  ...
  afterFetch: async (model, columns, options) => {
    model.set('industry', model.get('industry').name)
    model.set('logo', model.get('logo').url)
  },
  ...
}
```

However, the output is quite the same with the original one... What happened???

***

Fine, how about do it in the service?
After taking a look at `api/company/services/Company.js`, I gave up. It's too complicated...

***

Any suggestions?

**Comment by derrickmehaffy** [comment]
@kenberkeley while not directly related to your version, having the bare minimum bug report ect template is required can you please add the following to the top of your original post and fill it out.

I know it doesn't directly relate to what your doing, but is required, else issues are closed out without it:

```
**Informations**
- **Node.js version**: <!-- Please ensure you are using the Node LTS version (v10) -->
- **NPM version**: 
- **Strapi version**: <!-- Please make sure you are on the latest version -->
- **Database**: 
- **Operating system**: 
```

**Comment by derrickmehaffy** [comment]
@lauriejim I think it would be a good idea to add in a code sample for this, as it is really highly asked for on slack

**Comment by kenberkeley** [comment]
Info added

**Comment by derrickmehaffy** [comment]
Thank you

**Comment by acidcrash2005** [comment]
I have error 
`TypeError: strapi.services.lessons.fetchAll(...).toJSON is not a function`
pleas help ((((

**Comment by acidcrash2005** [comment]
I did trimming like this
`return strapi.services.lessons.fetchAll(ctx.query).then(function (lessons) {
        return lessons.map( (lesson) => (
          {
            id: lesson._id,
            title: lesson.title
          }
        ))
      });`

Work well!.

**Comment by lauriejim** [comment]
For me your first solution is the best because you export your data filter in an other function and you can specify when you want to apply it.

If you use the second solution, it will apply your filter in any case of you are fetching data.
And in a specific case you maybe want to be able to fetch all the data.

So it really depending of what are your needs. The impact of this two solutions are not the same.
