### ISSUE TITLE
Best practices for sharing newly created email providers

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#2510]
I've recently created an email provider for Sparkpost. I'm wondering what is the Strapi team's preferred method for publishing this package? Should I open a pull request to this repo with the new package? Or should I publish the package on npm under my own account?

**Comment by derrickmehaffy** [comment]
@greatwitenorth npm under your own account, the Strapi team are currently reworking the plugin framework to allow for 3rd party plugins and modules.
