### ISSUE TITLE
Query not avaiable for model

### ISSUE THREAD

**Issue by odelucca** [strapi/strapi#2511]
**Informations**
- **Node.js version**: 11.1.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MySQL
- **Operating system**: Ubuntu 18

**What is the current behavior?**
I'm developing a plugin. When I try to query a model I got the following output:
```
error There is no query available for the model notification.
```

**Steps to reproduce the problem**
I've created the plugin following the docs. After some basic setup, I've created a model, in the folder:
`plugins/notifications/models`.
My Notification.settings.js are:
```
{
  "connection": "default",
  "collectionName": "notifications",
  "info": {
    "name": "notification",
    "description": "All users notifications"
  },
  "attributes": {
    "user": {
      "model": "user",
      "plugin": "users-permissions"
    },
    "notification": {
      "type": "text",
      "required": true
    },
    "url": {
      "type": "string",
      "required": true
    },
    "unread": {
      "type": "boolean",
      "default": true
    },
    "type": {
      "type": "enumeration",
      "enum": [
        "-- Selecione um",
        "newUser",
        "alert",
        "newMessage",
        "error"
      ]
    }
  }
}
```

The model was created. The DB received a new table, according to the settings. After that, I've created a simple controller, at `/plugins/notifications/controllers/Notification.js`:
```
'use strict';

/**
 * Notification.js controller
 *
 * @description: A set of functions called "actions" of the `notification` plugin.
 */

module.exports = {

  /**
   * Return user notifications
   *
   * @return {Array}
   */

  getUserNotifications: async (ctx) => {
    let data = await strapi.plugins['notifications'].services.notification.fetchAll(ctx.params);
    console.log(data)

    // Send 200 `ok`
    ctx.send({
      message: 'ok'
    });
  }
};
```

Then, I've created a service at: `/plugins/services/Notification.js`:
```
'use strict';

/**
 * Notification.js service
 *
 * @description: A set of functions similar to controller's actions to avoid code duplication.
 */

module.exports = {
  fetchAll: params => {
    return strapi.query('notification', 'notifications').find(strapi.utils.models.convertParams('user', params));
  }
};
```

And, finally, I've created the query at `plugins/notifications/config/queries/bookshelf.js`:
```
module.exports = {
  find: async params => {
    return Notification.fetchAll(params);
  }
}
```

But, when I run to get it I got the following error:
`error There is no query available for the model notification.`

I've tried differents combinations of the queries. I've tryied to put it at `/plugins/notifications/api/config/queries` following the docs, but without success. I've also tried to copy another plugin find query, but also without success

I'm out of options =/

**What is the expected behavior?**
It should run the query with success.

**Comment by odelucca** [comment]
After many hours trying, I figured it our.

*Solution*
The problem is with the path of my services file. I debbuged the Strapi.js inside node_modules and found out this code that handle the plugin path:
```
let pluginPath = undefined;

    if (file.indexOf('strapi-plugin-') !== -1) {
      pluginPath = file.split(path.sep).filter(x => x.indexOf('strapi-plugin-') !== -1)[0];
    } else if (file.indexOf(path.sep + 'plugins' + path.sep) !== -1) {
      const pathTerms = file.split(path.sep);
      const index = pathTerms.indexOf('plugins');

      if (index !== -1) {
        pluginPath = pathTerms[index + 1];
      }
    }

    if (!pluginPath) {
      return this.log.error('Impossible to find the plugin where `strapi.query` has been called.');
    }

    // Get plugin name.
    const pluginName = pluginPath.replace('strapi-plugin-', '').toLowerCase();
    const queries = get(this.plugins, `${pluginName}.config.queries.${connector}`);
    console.log(`${pluginName}.config.queries`)

    if (!queries) {
      return this.log.error(`There is no query available for the model ${model}.`);
    }
```

After some time, I figured it out looking of the abs path of my services file:
`/home/odelucca/Servers/yurah/web/admin/plugins/notification/plugins/notifications/services/Notifications.js`

So, in that Strapi.js code, the const `pathTerms` was:
```
[ '',
  'home',
  'odelucca',
  'Servers',
  'yurah',
  'web',
  'admin',
  'plugins',
  'notification',
  'plugins',
  'notifications',
  'services',
  'Notifications.js' ]
```

Then, it looks for the first index of the word "plugins" and add 1 to get the plugin name... The problem is that I was organizing my folders using the name `plugins`.

*To solve this* I simply changed the folder `plugins` to `strapi-plugins`. Now, my new abs path is: ``/home/odelucca/Servers/yurah/web/admin/strapi-plugins/notification/plugins/notifications/services/Notifications.js`

It is VERY dangerous to use file names to handle system logic, specially this way. I suggest changing this and using the parameters that we already send in the query:
`strapi.query('notification','notifications').find(strapi.utils.models.convertParams('user', params));`

If we use the second parameter, it would be WAY better to understand the logic of the code.


Can someone close the issue please?

**Comment by derrickmehaffy** [comment]
resolving issue per user request
