### ISSUE TITLE
[Upload file] Please provide an option NOT to use relation

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2512]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I know Strapi is built for universal usage and limitless scenarios.
However, this is an issue about performance and necessity.

For example, I built an API with Strapi, which is shown as below:

```js
// api/company/models/Company.settings.json
{
  "connection": "default",
  "collectionName": "company",
  "info": {
    "name": "company",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string",
      "required": true
    },
    "code": {
      "default": "",
      "type": "string",
      "required": true,
      "unique": true
    },
    "logo": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": true
    }
  }
}
```

```js
// HTTP GET /companies
[
  {
    "id": 23,
    "name": "Apple Inc",
    "code": "APPL",
    "logo": {
      "id": 46,
      "name": "apple.png",
      "hash": "b2849a80c90043b3bba220637829a947",
      "sha256": "np5WzGw29OMAcW3wYK4YGxb-kvtsACSSUBMISt2yv8Y",
      "ext": ".png",
      "mime": "image/png",
      "size": "12.80",
      "url": "https://bucket.s3.region.amazonaws.com/b2849a80c90043b3bba220637829a947.png",
      "provider": "aws-s3",
      "public_id": null,
      "created_at": "2018-12-17T09:31:11.597Z",
      "updated_at": "2018-12-17T09:31:11.597Z"
    }
  },
  {
    "id": 24,
    "name": "Walmart Inc",
    "code": "WMT",
    "logo": {
      "id": 48,
      "name": "walmart.png",
      "hash": "811f389a0eac4ca1be0b34192f7cc291",
      "sha256": "dh-rkjilH3i70qpd3v_dM3t1jZT4L1Afch9snVRcag8",
      "ext": ".png",
      "mime": "image/png",
      "size": "11.30",
      "url": "https://bucket.s3.region.amazonaws.com/811f389a0eac4ca1be0b34192f7cc291.png",
      "provider": "aws-s3",
      "public_id": null,
      "created_at": "2018-12-17T09:32:34.117Z",
      "updated_at": "2018-12-17T09:32:34.117Z"
    }
  }
]
```

Actually, what I really need is as simple as below:

```js
// HTTP GET /companies (expected)
[
  {
    "id": 23,
    "name": "Apple Inc",
    "code": "APPL",
    "logo": "https://bucket.s3.region.amazonaws.com/b2849a80c90043b3bba220637829a947.png"
  },
  {
    "id": 24,
    "name": "Walmart Inc",
    "code": "WMT",
    "logo": "https://bucket.s3.region.amazonaws.com/811f389a0eac4ca1be0b34192f7cc291.png"
  }
]
```

Not only simple, but also avoid the performace issue of join query.
(Especially for schemas with multiple image fields, such as `logo` / `large_cover` / `small_cover` / ...)

In most cases we just care about the file url, not the whole verbose upload info.
(The field named `logo` is self-documenting and clear enough)

Hereon, I have to clarify that keeping the track of upload files is necessary for a better management.
However, it would be better if Strapi **offered an option which assigns the url to the upload field directly**.
(This is how WYSIWYG does it currently: copy an image and paste it to the markdown editor, only the url markup presents instead of a bunch of verbose upload info)

**Comment by kenberkeley** [comment]
Could be the best CMS-like framework, Strapi, has numerous of potential users who are using other CMSs.

However, what stops these potential users migrating to Strapi, might be the limitations that Strapi inheres.

I am merely one of them, and still struggling to make the migration as smooth / compatible as possible.

**Comment by kenberkeley** [comment]
If the original data looks like:

```js
[
  {
    "id": 23,
    "name": "Apple Inc",
    "code": "APPL",
    "logo": "https://bucket.s3.region.amazonaws.com/b2849a80c90043b3bba220637829a947.png"
  },
  {
    "id": 24,
    "name": "Walmart Inc",
    "code": "WMT",
    "logo": "https://bucket.s3.region.amazonaws.com/811f389a0eac4ca1be0b34192f7cc291.png"
  }
]
```

That would not be possible to migrate the schema to Strapi easily, since `logo` in Strapi is defined as below:

```js
{
  "connection": "default",
  "collectionName": "...",
  "info": {...},
  "options": {...},
  "attributes": {
    ...
    "logo": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": true
    },
    ...
  }
}
```

I can't assign a string to `logo` directly.

Also, I can't even make a workaround shown as below:

```js
// api/company/models/Company.settings.json
{
  "connection": "default",
  "collectionName": "...",
  "info": {...},
  "options": {...},
  "attributes": {
    ...
    "logo": {
      "default": "( Will be filled in automatically )",
      "type": "string",
      "required": true
    },
    "_logo": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": true
    },
    ...
  }
}
```

```js
// api/company/models/Company.js
module.exports = {
  // Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: async (model, attrs, options) => {
    model.set('logo', model.attributes._logo.url); // TypeError: Cannot read property 'url' of undefined
    // `_logo` is a file type so that it's not in Company model !!!
  },
  ...
};
```

**Comment by Aurelsicoko** [comment]
I do understand the need but as you said, we have to handle as most cases as needed. I might be possible to make a cleaner response with only the file URL like that:

```json
[
  {
    "id": 23,
    "name": "Apple Inc",
    "code": "APPL",
    "logo": "https://bucket.s3.region.amazonaws.com/b2849a80c90043b3bba220637829a947.png"
  },
  {
    "id": 24,
    "name": "Walmart Inc",
    "code": "WMT",
    "logo": "https://bucket.s3.region.amazonaws.com/811f389a0eac4ca1be0b34192f7cc291.png"
  }
]
```

However, the join query will still be done because our system is developed like that. And why, we did it like that? Simply because the same image can be associated with any kind of entries (multiples kind of content-types and entries). But, you can still say to me that you don't care and we can still store in the Company row in the table the raw URL as a string. Yes, but what happens if you delete the file? It means that you have to parse all your database and remove the URL in each entry of each content-type which are linked with this image.

So, I know it can be surprising at the beginning to see a relational field for an image. But, trust me. We did a good choice, and we anticipated many future issues (media library, etc).

About the performances issues, until you've more than 50/100k entries, you won't see them. Then, you can easily build indexes to speed up the join query. I'm closing the issue because we won't do it but feel free to answer though.
