### ISSUE TITLE
Custom plugin won't build

### ISSUE THREAD

**Issue by odelucca** [strapi/strapi#2513]
**Informations**
- **Node.js version**: 11.1.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MySQL
- **Operating system**: Ubuntu 18

**What is the current behavior?**
I've just finished a custom plugin and I'm trying to add it to my project admin. When I copy the plugin folder and try to run `npm run setup --plugins` on the root folder, I got the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! strapi-plugin-notifications@0.0.0 build: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production node node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the strapi-plugin-notifications@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/odelucca/.npm/_logs/2018-12-19T05_49_49_984Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.16 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.16 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/odelucca/.npm/_logs/2018-12-19T05_49_50_003Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yurah-admin@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yurah-admin@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/odelucca/.npm/_logs/2018-12-19T05_49_50_011Z-debug.log
```

If I just run npm run setup it works, but, when I do strapi start to test it I got only a loading screen on the browser, and nothing more.

**Steps to reproduce the problem**
1. I've created a admin
2. Then, I've configurated that admin, adding some Contents Types and so on
3. Afterwards, I've created another project, following the docs, setting it to be --dev and developed the plugin there
4. With the plugin finished, I copied the plugin folder and pasted it on my other admin
5. Then, the problems starts

**What is the expected behavior?**
I want to migrate my plugin from one project to another one

**Comment by soupette** [comment]
Hi @odelucca do you have a repo that I can check I need a more informations...

**Comment by odelucca** [comment]
Hi @soupette sorry, I was off for xmas and new year's

I am uploading it on a repo and will send here soon. 

In the meantime, do you have any docs about deploying a --dev project with custom plugins? Maybe this would help me

**Comment by odelucca** [comment]
@soupette I was trying to generate the repo with the error and noticed that, when I run the strapi start (after creating a new strapi project and copying the folder/running npm i) I receive the following code on the browser console:
```
Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (main.js:1)
    at Object.../../../strapi-plugins/schedule/admin/node_modules/strapi-helper-plugin/node_modules/babel-polyfill/lib/index.js (main.js:1)
    at t (main.js:1)
    at Object.<anonymous> (main.js:1)
    at Object.../../../strapi-plugins/schedule/admin/admin/src/app.js (main.js:1)
    at t (main.js:1)
    at main.js:1
    at main.js:1
```

**Comment by odelucca** [comment]
@soupette I found out the problem. The strapi-plugin-helper has a webpack config. I was trying to use the [React HTML Parser](https://www.npmjs.com/package/html-react-parser) on a plugin and it was broking during build.

I found out running the `npm run build` inside the plugin folder.

There is a way to add a config to ignore a specific plugin or load custom configs on the Webpack?

**Comment by soupette** [comment]
@odelucca 

> There is a way to add a config to ignore a specific plugin or load custom configs on the Webpack?

Currently no, unless you modify [this file](https://github.com/strapi/strapi/blob/d435e2396964547e1c848ae70d02cac75a09780d/packages/strapi-admin/scripts/setup.js#L27) so you don't build your custom plugin. You will need to build it manually.

The other way to get rid of the `babel-polyfill error` would be to put your dependency in the strapi-helper-plugin and to make it available as follows:

- [Modify the webpack.dev.babel.js](https://github.com/strapi/strapi/blob/d435e2396964547e1c848ae70d02cac75a09780d/packages/strapi-helper-plugin/lib/internals/webpack/webpack.dev.babel.js#L232)
```
'html-react-parser': path.resolve(
  rootAdminpath,
  node_modules',
  'strapi-helper-plugin',
  'node_modules',
   'html-react-parser',
),
```

- [Modify the webpack.dll.babel.js](https://github.com/strapi/strapi/blob/d435e2396964547e1c848ae70d02cac75a09780d/packages/strapi-helper-plugin/lib/internals/webpack/webpack.dll.babel.js#L148)

```
'html-react-parser': path.resolve(
  rootAdminpath,
  node_modules',
  'strapi-helper-plugin',
  'node_modules',
   'html-react-parser',
),
```

- [Modify the webpack.prod.babel.js](https://github.com/strapi/strapi/blob/d435e2396964547e1c848ae70d02cac75a09780d/packages/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js#L249)

```
'html-react-parser': path.resolve(
  rootAdminpath,
  node_modules',
  'strapi-helper-plugin',
  'node_modules',
   'html-react-parser',
),
```

Hope this helps

**Comment by odelucca** [comment]
Thanks @soupette 

I've solved it just by changing the depedency itself :)

You can close the issue if you want!
