### ISSUE TITLE
Be able to override for tags to sort easier documentation plugin

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2514]
**Informations**
- **Node.js version**: Node v10
- **NPM version**: NPM v6
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MariaDB 10.2
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: [Link](https://github.com/canonn-science/CAPIv2-Strapi/tree/update/autoDocsUpdate)

**What is the current behavior?**

Currently the model level overrides generate the openapi schema file based on their alphabetical ordering (model name), this can make for an "ugly" view on the swaggerUI because even if you define the tags in the core override for the docs the models will force the listing to follow their order. (confused yet?)

**Steps to reproduce the problem**

Difficult to describe on reproduction, you can follow my project to see what I'm doing.

Example image:

![image](https://user-images.githubusercontent.com/8593673/50218033-c7228380-0347-11e9-9317-7c1799c8599c.png)

As you can see in the image above two of my models aren't following the rest because the model `Guardian Beacons` ranks higher in the alphabetical sorting system than the related `Report` model.

**What is the expected behavior?**

See Suggestion

**Suggested solutions**

In addition to the core documentation settings.json file I think another should be included basically like tags.json. The order in which the overrides should happen:

1. Core `settings.json`
2. Model overrides
3. Core `tags.json`

In this case the user can define the "sort" order of how the swagger/openapi doc file is laid out.

**Comment by soupette** [comment]
I completely agree, I need to talk with @Aurelsicoko to see if we can include more sorting features on that plugin.

**Comment by derrickmehaffy** [comment]
I managed to get some hacky solution done for mine but it isn't something I enjoy fixing everytime I add a new model ;)

**Comment by Aurelsicoko** [comment]
I agree on this as well... we should offer an easy way to sort and reorganize the tags in a specific order. @derrickmehaffy what do you think by doing it in a separate file?

**Comment by derrickmehaffy** [comment]
@Aurelsicoko yes doing it in a separate file would be best, basically all you need to do is call that override after everything else.

Right now its taking the `settings.json` in the doc plugin, then the model doc files, and lastly the model overrides. All you need to do is add one more step and grab the tags file override after the rest and it will sort based on that order AFAIK.

**Comment by derrickmehaffy** [comment]
Everything with swagger/openAPI docs is about the order, It follows the order in the final build of the doc file.

**Comment by Aurelsicoko** [comment]
I've created a private feature on Product Board to keep this in mind. I would love to see a contribution from the community to develop this feature.

**Comment by derrickmehaffy** [comment]
The override system you guys are using is way above my head, remember I was writing this by hand before :rofl:

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/be-able-to-override-for-tags-to-sort-easier-documentation-plugin

Thanks!
