### ISSUE TITLE
Duplicated records / entries if you press buttons quickly

### ISSUE THREAD

**Issue by D4n1984** [strapi/strapi#2515]
**Informations**
- **Node.js version**: Node v10.14.2
- **NPM version**: npm v6.4.1
- **Strapi version**: Strapi 3.0.0-alpha.16 
- **Database**:  Mongodb 4.0.4
- **Operating system**:  Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When you create a new content and press in "+ Add New {content}" if you press twice or more times quickly, you can create duplicate records.

**Steps to reproduce the problem**
Go to create a new content and press in "+ Add New {content}" twice or more times quickly.

**What is the expected behavior?**
Control the unintended clicks and create a single record.

**Suggested solutions**
Control the unintended clicks.

**Comment by soupette** [comment]
Well I'm not sure that this is actually a bug. Let's say that you have a model with only one field for instance `name` that is not required. Since the field is not required the user is allowed to create an empty entry, therefore the content-manager lets you create such entry.

I can add a delay that will prevent you from clicking `add new field` and `save` too rapidly.

**Comment by D4n1984** [comment]
I thini that is the best choice.

Regards,

**Comment by soupette** [comment]
@Aurelsicoko do you confirm?

**Comment by Aurelsicoko** [comment]
It might be a bug... When you said "create a new content and press in "+ Add New {content}" twice or more times quickly.", does it mean that you create a new content type, then clicks on save, then you go back on the list view, and so on...?

**Comment by lauriejim** [comment]
I close the issue, in fact, it just creates an empty entry.
You click on create an entry button then on the save button.
So it creates an empty entry and it's normal.
