### ISSUE TITLE
An error ocurred while fetching permissions

### ISSUE THREAD

**Issue by LuisHCK** [strapi/strapi#2520]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: Mongo 4.0.4-1
- **Operating system**: Arch Linux
- **(Optional) Link to your Project**: https://github.com/LuisHCK/api

**What is the current behavior?**
When I try to create a new role it shows me an error notification.
![screenshot_20181220_160010](https://user-images.githubusercontent.com/5175137/50314415-617fe580-0474-11e9-916f-57724774f459.png)
There are also no errors in the terminal 

If I save the Role, I can not change the permissions of the role because it stays loading
![strapi roles permissions2](https://user-images.githubusercontent.com/5175137/50315198-67c39100-0477-11e9-9a08-da74efc08e9a.png)

**Steps to reproduce the problem**
Clone my repo

**What is the expected behavior?**
To edit a role as the default roles
![strapi roles permissions](https://user-images.githubusercontent.com/5175137/50315232-8c1f6d80-0477-11e9-9fe4-62bf0e3e81b6.png)

**Suggested solutions**
Downgrading to 3.0.0-alpha.16 fix the problem for now

**Comment by lauriejim** [comment]
Thank you for this report ! 
We will fix it soon as possible.

**Comment by TNkemdilim** [comment]
I'm also facing this challenge... Thanks a lot.

**Comment by LuisHCK** [comment]
> I'm also facing this challenge... Thanks a lot.

Downgrading to `3.0.0-alpha.16` fix the problem for now

**Comment by msarfaraz** [comment]
This issue is in latest release.downgrade and install it will work.
**Installing 3.0.0-alpha.16**
sudo npm install strapi@v3.0.0-alpha.16 -g

**Comment by lauriejim** [comment]
Yes it's one of our priority!
Thank you all for this feedback.
