### ISSUE TITLE
Update nullish values in mongoose hooks

### ISSUE THREAD

**Issue by download13** [strapi/strapi#2521]
**Informations**
- **Node.js version**: node 10.12.0
- **NPM version**: 6.4.1
- **Strapi version**: alpha.17
- **Database**: mongodb
- **Operating system**: windows 10

I'm getting this error when updating a document using GraphQL:
```
TypeError: Cannot read property 'assignee' of undefined"
    at params.parseRelationships.Object.keys.reduce (C:\Users\downl\code\work-e9\ems\crm-server\node_modules\strapi-hook-mongoose\lib\relations.js:43:119)"
    at Array.reduce (<anonymous>)"
    at Function.update [as updateRelations] (C:\Users\downl\code\work-e9\ems\crm-server\node_modules\strapi-hook-mongoose\lib\relations.js:28:129)"
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

You can see [the code that causes the error](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/relations.js#L43)
```javascript
case 'oneToOne':
     if (response[current] !== params.values[current]) {
          const value = _.isNull(params.values[current]) ? response[current] : params.values;
          const recordId = _.isNull(params.values[current]) ? getValuePrimaryKey(value, this.primaryKey) : value[current];
          const model = module.exports.getModel(details.model || details.collection, details.plugin);
```

[Line 43](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/relations.js#L43) throws the exception, but I think the real problem is on [line 41](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/relations.js#L41).

The error occurs if a property on an existing document is null, and the update attempts to set it to `undefined`. The conditional sees that the old and new values are not exactly the same and seems to assume the new value is an object of some kind.

I'm not totally sure what needs to change to fix this issue. I worked around it for now by adding some code around line 31

```
if(params.values[current] === undefined) {
  params.values[current] = null;
}
```

to ensure that incoming undefined values are converted to null. Does this need to be fixed in the graphql plugin though? Should it be converting undefineds to nulls before passing the params to mongoose?

EDIT: It also happens if the document has no property for the update key, but the updated value is `null`. Workaround was instead to replace line 41 with

`if (response[current] !== params.values[current] && !(response[current] == null && params.values[current] == null)) {`

**Comment by download13** [comment]
Sure, here's the [sample files](https://gist.github.com/download13/8183ee4ee5d816031f33cead10cfdd7b).

The sample document I included has no `assignee` property deliberately. If you try to set assignee to `null` using `updateWorkorder` it should trigger the error.

**Comment by lauriejim** [comment]
Hello please follow the [documentation example](https://strapi.io/documentation/3.x.x/guides/graphql.html#update-an-existing-entry) to update an entry with GraphQL.

I just try to update to `null` with REST API and GraphQL and it works well.

Let me know if you have a question.
