### ISSUE TITLE
Support for GeoJSON Content Type 

### ISSUE THREAD

**Issue by arogyakoirala** [strapi/strapi#2527]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

### Background

**Context**
I have been working over the last few days with the strapi code-base add support for geographical data types (GeoJSON, to be more precise). I was pleased to see that strapi already had support for JSON, so I repurposed the code for `InputJSON` and `InputJSONWithErrors` components to create the GeoJSON content-type. To do so, I've followed the instructions posted on [this issue](https://github.com/strapi/strapi/issues/483#issuecomment-358971985) 

 **Why a separate GeoJSON content-type? (A real world use-case)**
Our organization primarily works with local governments in Nepal to build official portals that help them connect with their citizens. In doing so, some offices have realized a need to include a feature that allows them to visualize all of capital-projects for the fiscal year. See image below:

![image](https://user-images.githubusercontent.com/24402285/50380691-535ddf00-0697-11e9-9e77-2cad4e1674d7.png)

We want government officials to be able to upload geographic information on their own. Due to their limited technical knowledge, we found that the best way to get this done is by providing them with a user-interface to draw out the project.

I've gone ahead and created a component to facilitate the same. 

### Steps taken:

**Steps to display new input in the content type builder**

- To display my new field I have added it it in the `/plugins/content-type-builder/admin/src/containers/Form/forms.json`file.

- I've also populated the corresponding translations in the `/plugins/content-type-builder/admin/src/translations` folder. However, since I don't know language other than English, I've used english everywhere.

- I added another `switch-case` statement inside  `strapi/plugins/strapi-hook-mongoose/lib/utils/index.js` file for my new content-type (geojson), simply copy pasting the one for json. The plugin didn't run until I did that.

- I have also added images for my new content type in the `AttributeRow` and `AttributeCard` components.

- I was thus able to display my new attribute in the plugin (this might have an impact on the plugin's component)

**Using my new type in the content manager**

- I had to add a few new packages npm packages `(mapbox gl-js, @mapbox/mapbox-gl-js-draw, @mapbox/geojson-extent etc.)` and css files, I did not know how to add CSS files so i directly used the index.html file in  the `admin/admin/src/index.html` I know this is not optimal, what are my options?

  - When adding `@mapbox/mapbox-gl-js-draw` I ran into issues as I rebuilt the  `content-manager` plugin. So for my present purpose, I have served the CDN through my public directory `/public`, I’m aware this is not the best way to do things. Looking forward to your inputs here too.

- I also had to update the `containers/saga.js` and update the following line :
`const cleanedData = (attrType === 'json' || attrType==='geojson') ? record[current] : cleanData(record[current], 'value', 'id');`

- In the content manager plugin I modified the `Edit` container and its children in order to display my new field type.

- I created the `InpuGJSON` and `InputGJSONWithErrors` component and served them through the `Edit` component as suggested. 

### How it looks
![image](https://user-images.githubusercontent.com/24402285/50380851-b05c9380-069d-11e9-8525-9452bbb743fa.png)

### Features:
The GeoJSON input component allows a user to:
- Upload a `.geojson` file.
- Preview and modify uploaded `.geojson` in the browser.
- Draw custom points, lines and polygons (multiple points, lines and polygons also allowed) directly through the tool.
- Search for a place using a search box (using `mapbox-generic-geocoder` with OSM Nominatim), and zoom in to the location.

### Questions/Comments:
- What is the right way to use CDNs for JS and CSS in strapi? Im not sure if i followed standard practices for the same.
- Currently I've used [Maptiler Cloud](https://cloud.maptiler.com/) for hosting my vector tiles. This service allows upto 100000 free views in a month. If needed I can set up a map tile server for the same.
- All of my changes can be found at [my fork of strapi here](https://github.com/arkoblog/strapi).
- I'm looking forward to someone from strapi going through my code and pointing out blunders, mistakes so that I can work on the same. I've also submitted a pull request to facilitate the same.

**Comment by soupette** [comment]
Hi @arogyakoirala thanks for your inputs here are some answers:

> What is the right way to use CDNs for JS and CSS in strapi? Im not sure if i followed standard practices for the same.

Maybe you can try something like this in the `content-manager/admin/src/components/InputGJSONWithErrors`:
```
import '<my-package/dist/<stylesheet>.css';
// ... rest of the code
```

If it doesn't work, well you can try to create the tag manually and insert it into the dom or just hardcode it in the index.html like you did. I prefer the first option which is to import the stylesheet.

> Currently I've used Maptiler Cloud for hosting my vector tiles. This service allows upto 100000 free views in a month. If needed I can set up a map tile server for the same.

I think that @lauriejim or @Aurelsicoko are the one who could answer this question


> All of my changes can be found at my fork of strapi here.


That's awesome thanks for providing your fork! I'll take a look into it!

> I'm looking forward to someone from strapi going through my code and pointing out blunders, mistakes so that I can work on the same. I've also submitted a pull request to facilitate the same.

You can DM on Slack (@soupette) I answer most of the time!


Thanks again for providing a such detailed issue!

**Comment by merijnvanessen** [comment]
finding a way to search geo locations within my frontend (nuxt), from the strapi backend.
https://mongoosejs.com/docs/geojson.html

I believe I need a point schema, is it possible to add something like this to the model? 
Since point is currently not available as a strapi type (from the mongoose docs):

```
location: {
    type: {
      type: String,
      enum: ['Point'], 
      required: true
    },
    coordinates: {
      type: [Number],
      required: true
    }
  }
```
It would be awesome if a resolver for finding GeoJSON values would be baked in within strapi,
for both API and graphql.. or some clear documentation where to implement:

```
db.locations.find({
   location: {
     $nearSphere: {
       $geometry: {
         type: 'Point',
         coordinates: [-122.5, 37.1]
       },
       $maxDistance: 900 * 1609.34
     }
   }
 })
```
thanks

**Comment by Aurelsicoko** [comment]
The GeoJSON field wasn't one of priority. The GeoPoint (aka Map) is a priority for example. However, the work done here seems pretty good. I would love to see it merged to the project.

I'm not sure to understand the questions:

- Where do you expect to store the vectors tiles?
- Can you submit the PR so we'll be able to review the code and continue the work together,

**Comment by arogyakoirala** [comment]
> The GeoJSON field wasn't one of priority. The GeoPoint (aka Map) is a priority for example. However, the work done here seems pretty good. I would love to see it merged to the project.
> 
> I'm not sure to understand the questions:
> 
>     Where do you expect to store the vectors tiles?

The vector tiles that I'm currently using comes from MapTiler Cloud ([see pricing here](https://www.maptiler.com/cloud/plans/)). I'm currently using the free plan which allows upto 100,000 requests a month. I guess what I'm asking is if that would be enough. If not, we will have to look for other free options (which I'm sure are available, I just haven't spent enough time researching on the same).

>     Can you submit the PR so we'll be able to review the code and continue the work together,

I did this the same time I opened this issue. You can find it [here.](https://github.com/strapi/strapi/pull/2526)

**Comment by arogyakoirala** [comment]
> The GeoJSON field wasn't one of priority. The GeoPoint (aka Map) is a priority for example.

@Aurelsicoko I'm not sure if I understand what a GeoPoint is. Can you elaborate?

**Comment by merijnvanessen** [comment]
Should I open a different feature request?

I 'just' :-) need a field within contenttypes to add points (geojson)

So I can add markers to my strapi model
```
"marker":{
      "type": "Point",
      "default":[],
      "coordinates": [0,0]
    },
```
These markers can be found with something like

```
Message.find({
  marker: {
   $near: {
    $maxDistance: 1000,
    $geometry: {
     type: "Point",
     coordinates: [long, latt]
    }
   }
  }
 }).find((error, results) => {
  if (error) console.log(error);
  console.log(JSON.stringify(results, 0, 2));
 });
```
and display on any map library client sided

**Comment by Aurelsicoko** [comment]
@arogyakoirala So if we have to depend on a third-party, we should add a provider system to this new type of field.

About the GeoPoint is nothing more than a pin that you put on Map. It just works like a GPS (lat, lon coordinates).

**Comment by Aurelsicoko** [comment]
@arogyakoirala Is it possible to change the map background in your field? In the beginning, I was thinking about using something like OpenStreetMap ;)

**Comment by arogyakoirala** [comment]
@Aurelsicoko this is OpenStreetMap. However I've used vector tiles (mapboxgljs) as opposed to raster (leafletjs).

**Comment by sign0** [comment]
@arogyakoirala 
Your fork is only for MongoDB ? Not for PostgreSQL/PostGIS ?
I am starting the same, but with PG and the "geometry" data type...

**Comment by arogyakoirala** [comment]
@sign0 I've merely customized the JSON input type to easily take geometries in GeoJSON format. I do see value in extending this functionality to 'geometry' data type, as it would enable backend geospatial querying.

**Comment by sign0** [comment]
@arogyakoirala Yes, especially since the latest versions of PostgreSQL efficiently manage the JSON with the JSONB type.

Postgres is also suitable for storing vector or raster tiles (I use that: https://openmaptiles.org/ with SQLite/MBTile or Postgres/gis, and it's compatible with the mapbox-gl workflow like gl-style). 

Unfortunately, I'm not familiar with Knex ORM, especially when it comes to interacting with PostGIS (I more familiar with Sequelize ORM).

And the management of geometry type would mean that it would be an "exclusive feature" for Postgres : which would go may be against the philosophy of this project which claims to be a NoSQL / SQL compatible CMS... But for example, Wordpress is "optimized" for MySQL).

I have not yet tried your contribution, but the description is impressive ! :)

**Comment by cupofnestor** [comment]
@arogyakoirala -  Awesome work.  I was pleasantly surprised to see that you are working on this.  I was planning on having to do this on my own.   I look forward to checking out your fork.  I'd love to help if I can.       Assuming the strapi folks can see the obvious benefits of this, a few areas that I'd love to work on:

1. Topojson - an extension to GeoJSON that encodes topology rather than discrete geometries, allowing for smaller files and on-the-fly simplification.
2. GeoJSON model -  I haven't checked out the fork yet and I don't know if it is your intent to fully model the GeoJSON spec. It would be great to have the ability for instance to create relations between GeoJSON `Features` and other strapi models.

**Comment by cupofnestor** [comment]
> Postgres is also suitable for storing vector or raster tiles (I use that: https://openmaptiles.org/ with SQLite/MBTile or Postgres/gis, and it's compatible with the mapbox-gl workflow like gl-style).
There's postGIS as well https://mapserver.org/input/vector/postgis.html

**Comment by sign0** [comment]
> > Postgres is also suitable for storing vector or raster tiles (I use that: https://openmaptiles.org/ with SQLite/MBTile or Postgres/gis, and it's compatible with the mapbox-gl workflow like gl-style).
> 
> There's postGIS as well https://postgis.net/

Yes it is!
Postgis also supports geometry -> TopoJSON with AsTopoJSON() function.

**Comment by arogyakoirala** [comment]
> @arogyakoirala - Awesome work. I was pleasantly surprised to see that you are working on this. I was planning on having to do this on my own. I look forward to checking out your fork. I'd love to help if I can. Assuming the strapi folks can see the obvious benefits of this, a few areas that I'd love to work on:
> 
>     1. Topojson - an extension to GeoJSON that encodes topology rather than discrete geometries, allowing for smaller files and on-the-fly simplification.
> 
>     2. GeoJSON model -  I haven't checked out the fork yet and I don't know if it is your intent to fully model the GeoJSON spec. It would be great to have the ability for instance to create relations between GeoJSON `Features` and other strapi models.

@cupofnestor  thanks for your appreciation, I'm really glad (first open-source contribution woot woot). I feel both of the features you suggest will ad significant value. TopoJSON will reduce the load, and a GeoJSON model should help facilitate spatial queries which would be awesome. Feel free to fiddle with my fork and make changes. Do let me know how I can help.

**Comment by simonmaris** [comment]
Just wanted to chime in to say (and maybe up the priority a bit :)), that currently this is the only thing holding me back to fully switch to strapi for a project, since it needs an easy way for editors to input location information. datocms has a similar field which works really well for addresses, I think that would be a great start which could further be extended to more complex geodata.

**Comment by lucaswerner90** [comment]
It would be nice to support this GeoJSON type, so more applications could be developed with Strapi.

**Comment by lauriejim** [comment]
This will come with the custom field feature. With that, every field type will be able to be supported.
I'm locking this issue. We well understood the need.
Thank you all for your contribution.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/plugin-requests/p/geo-mapping-plugin
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
