### ISSUE TITLE
GraphQL mutation error column "_id" on SQL

### ISSUE THREAD

**Issue by ayushkamadji** [strapi/strapi#2530]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: PostgreSQL 11.1
- **Operating system**:  Ubuntu 16.04
- **(Optional) Link to your Project**: N/A

**What is the current behavior?**
During a graphql update mutation, when using the where filter to specify the id of the model, an Error is thrown as follows:
`Unhandled rejection error: column "_id" of relation <<relation name>> does not exist`

This is causing a weird behavior where a table that does not contain a JSON field will NOT FAIL to update, but tables that do WILL FAIL to update.

**Steps to reproduce the problem**
1. Create a strapi project with graphql plugin installed
2. Create two models, one with no JSON fields (modelA), and the other with a JSON field (modelB). Create seed data for them.
3. Suppose we have a `Post` model that contains only `id` -> ID and `description` -> string fields. And another model `Article` with `id` -> ID and `json_data` -> json fields.
4. Open your playground or graphiql and execute the following mutations:
```
mutation {
  updatePost(
    input: { 
      where: { id: 1 }, 
      data: { description: "abcd" } 
    }
  ){
    post {
      id,
      description
    }
  }
}
```

```
mutation {
  updateArticle(
    input: {
      where: { id: 1 },
      data: {
        json_data: "[5, 4, 3]"
      }
    }
  ){
   article {
     id,
     json_data
   }
  }
}

```
5. Check your console. You will see the errors I mentioned above.
6. Check your database. You will find that `Post` with `id = 1` was updated and `Article` with `id = 1` was not updated.

**What is the expected behavior?**
No errors are thrown regarding the `_id` or `id` and model row should be updated

**Suggested solutions**
I have tried changing `convertToParams` function to not change the filter params if it equals "id" and it works. I'm not sure whether this is a proper solution since I'm not aware if it will break other databases/naming conventions.
```
/* /strapi/packages/strapi-plugin-graphql/services/Query.js:20 */

  convertToParams: params => {
    return Object.keys(params).reduce((acc, current) => {
      return Object.assign(acc, {
        [`_${current}`]: params[current],
      });
    }, {});
  },
```
```
  convertToParams: params => {
    return Object.keys(params).reduce((acc, current) => {
      if (current === "id") return Object.assign(acc, { [current]: params[current] })
      return Object.assign(acc, {
        [`_${current}`]: params[current],
      });
    }, {});
  },
```

**Comment by lauriejim** [comment]
Hello @ayushkamadji for this issue!
You are right to point this issue.

Your solution work well but can you optimize your code and submit a PR please.
We will appreciate that!

**Comment by ayushkamadji** [comment]
I was about to work and realized this is fixed already in 51b5ea7b3f4e8c333f3f894ce20054542e0c4f32 by @pierreburgy . I'll close this issue.

**Comment by azamuddin** [comment]
I still found a similar error 
`Unhandled rejection Error: ER_BAD_FIELD_ERROR: Unknown column '_id' in 'field list'`

When I checked the fix here https://github.com/strapi/strapi/commit/51b5ea7b3f4e8c333f3f894ce20054542e0c4f32

And investigate` primaryKey === current`, it returns `false` for field `id`. So I tried made a change to also check if `current === 'id'` like below, and it works:

```
convertToParams: (params, primaryKey) => {
    return Object.keys(params).reduce((acc, current) => {
      return Object.assign(acc, {
        [`${
          primaryKey === current || "id" === current ? "" : "_"
        }${current}`]: params[current]
      });
    }, {});
  },

```

**Comment by lauriejim** [comment]
We have big work done about that here https://github.com/strapi/strapi/pull/2452

**Comment by azamuddin** [comment]
@lauriejim hmm so I need to wait for it before being able to use GraphQL plugin on strapi?

**Comment by lauriejim** [comment]
Yes
