### ISSUE TITLE
add / remove response header item

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2535]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
How to add / remove response header item to an endpoint?
I want add some response header item (key/value) to an endpoint. Can you guide me?

**Comment by lauriejim** [comment]
Hello @mnlbox there is documentation here about response https://strapi.io/documentation/3.x.x/guides/responses.html
You will also find documentation about Koa.

**Comment by mnlbox** [comment]
@lauriejim Thanks for your reply, based on that link I create a file in `/middlewares/custom_header/index.js` with below content:
```
'use strict';

const _ = require('lodash');

module.exports = () => {
  return {
    /**
     * Initialize the hook
     */

    initialize: function(cb) {
      strapi.app.use(async (ctx, next) => {
        await next();
        ctx.set('X-Custom', 'Custom header value');
      });
      cb();
    }
  };
};
```

And also modify `/config/middleware.json` as below: (add `"custom_header"` to `load.before` section)
```
{
  "timeout": 100,
  "load": {
    "before": [
      "responseTime",
      "logger",
      "cors",
      "responses",
      "gzip",
      "custom_header"
    ],
    "order": [
      "Define the middlewares' load order by putting their name in this array is the right order"
    ],
    "after": [
      "parser",
      "router"
    ]
  }
}
```
Then I restart my strapi server but it's still old response header when I check in swagger documentation.

Can you guide me how to fix this?

**Comment by lauriejim** [comment]
Did you have this error in you logs `(middleware:custom_header) wasn't loaded due to missing key `enabled` in the configuration`?

**Comment by mnlbox** [comment]
Yes I have this error in console. :thinking:

**Comment by lauriejim** [comment]
Okay so your middleware is not loaded, please follow the first instruction of this documentation
https://strapi.io/documentation/3.x.x/advanced/middlewares.html
> Enable the middleware in environments setting

**Comment by mnlbox** [comment]
Oh I need `ejs` I think we need some clarify in that document.

**Comment by mnlbox** [comment]
@lauriejim 
I can add response header now successfully.
How we can modify or remove one response header??
For example I add `ctx.set('X-Powered-By', 'API Owner');` but it's still show:
```
x-powered-by: Strapi <strapi.io> 
```

**Comment by mnlbox** [comment]
@lauriejim

**Comment by nikosolihin** [comment]
@mnlbox I was in a similar situation and simply calling`ctx.set` to another value worked fine. To remove the header use `ctx.remove` per the [Koa docs](https://github.com/koajs/koa/blob/master/docs/api/response.md).

**Comment by abhagsain** [comment]
@lauriejim  I did everything that the docs say but I'm still getting ```(middleware:m_custom) wasn't loaded due to missing key 'enabled' in the configuration?```
I've created a ```middleware.json``` inside ```cms/config/environments``` Where I've added 
```
{
  "m_custom": {
    "enabled": true
  }
}

```
Then inside ```cms/config/middlewares.json``` I've added my middleware in the ```before``` array
```
 "load": {
    "before": [
      "responseTime",
      "m_custom",
      "logger",
      "cors",
      "responses",
      "gzip"  
    ]
}
```
and my custom middleware structure is
``` cms/middlewares/m_custom/index.js```

Can you tell me what I did wrong! 🙄
Thank you.

**Comment by lauriejim** [comment]
Hello @abhagsain !
I don't know :/ what you did looks well.
I just tried and it works well on my side.
