### ISSUE TITLE
strapi is not defined

### ISSUE THREAD

**Issue by Dogtiti** [strapi/strapi#2538]
**Informations**
 * Node.js version: 10.13.0
* npm version: 6.4.1
* Strapi version: 3.0.0-alpha.17
* Database: mongoDB v3.6.4

**What is the current behavior?**
I don't know what happened. And I have to rollback to the working version. after I rollback, it works correctly，but a few time later, I haven't changed any code,I just restart the project.it doesn't work.
![image](https://user-images.githubusercontent.com/38354472/50428792-2870c680-08f5-11e9-8021-3989d627bb2a.png)
Then, I go to the `i18n.js` to `console.log(strapi)` as this 
![image](https://user-images.githubusercontent.com/38354472/50428838-7ede0500-08f5-11e9-91c0-27eae54b1641.png)
Now:
![image](https://user-images.githubusercontent.com/38354472/50428850-90bfa800-08f5-11e9-97f7-ef7fa923c6f0.png)

**Comment by Dogtiti** [comment]
I have found it's because I import a component from antd as `import Upload from 'antd/lib/upload'` in `packages/strapi-plugin-content-manager/admin/src/components/BraftEditor/index.js`(I replace the defalut `editor` with `braft-editor`), and it will report an error `strapi is not defined`, I tried to not import `antd`, it works correctly. I don't know why.
Anyone can provide some suggestions?

**Comment by soupette** [comment]
Hi @Dogtiti can you tell me where you installed the editor? Maybe provide me with your fork?

**Comment by Dogtiti** [comment]
@soupette  I’m sure the editor I use it worked well, just because of the component from `antd`, since I use the `antd`, it performed wrong. So I remove it just now,  whole things work well.
And the editor,  I installed it as [this](https://github.com/strapi/strapi/issues/2111) without doing these as follow img:
![image](https://user-images.githubusercontent.com/38354472/50473267-40c90a00-09f7-11e9-8664-992af1773194.png)

**Comment by Dogtiti** [comment]
@soupette 
```
import React from 'react'
import BraftEditor from 'braft-editor'
import { ContentUtils } from 'braft-utils'
import { Upload } from 'antd'
//....
    const extendControls = [
      {
        key: 'antd-uploader',
        type: 'component',
        component: (
          <Upload
            accept=".doc,.xlsx,.pdf,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            showUploadList={false}
            customRequest={this.uploadHandler}
          >
            <button type="button" className="control-item button upload-button" data-title="插入附件">
              Upload
            </button>
          </Upload>
        )
      }
    ]
//...

 return (
      <div>
        <div className="editor-wrapper">
          <BraftEditor
            value={editorState}
            onChange={this.handleChange}
            ref={this.props.setRef}
            media={{ uploadFn: myUploadFn }}
            extendControls={extendControls}
          />
        </div>
      </div>
)

```

**Comment by soupette** [comment]
Ok I might try to install antd and check it out. 
For the upload component can't you make one or use [this one](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/admin/src/components/WysiwygDropUpload)

**Comment by Dogtiti** [comment]
@soupette yeah,  I have changed another one

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by Dogtiti** [comment]
@lauriejim I don't know why, and I didn't use `antd` anymore in `strapi`,all things are ok

**Comment by pnl107** [comment]
so, how to use antd in strapi project :(
