### ISSUE TITLE
Cannot create new project with 3.0.0-alpha.17

### ISSUE THREAD

**Issue by sangjs** [strapi/strapi#2539]
i can not create new project with strapi new my-project command. it is very long time to wait. i try close terminal and create again sometime can choose option db and config. but it not connect. and i try to create again but not possible.
![image](https://user-images.githubusercontent.com/22710371/50441073-989a3f00-092b-11e9-822f-c0e5a0076887.png)
it not work...
Thank you

**Comment by derrickmehaffy** [comment]
@sangjs please follow the issue template and add the required options. I am closing this issue until they are added.

Please note Windows is not supported https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows
