### ISSUE TITLE
View relation fields and filter and sort based on realtion field

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2543]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I think it can be very useful if we can see relation field in content manager and also sort and filter through relation field in admin panel.
Maybe this Feature Request is a combination of these two features but in admin panel (rather than API):
#2457 
#1292 
#2452

**Comment by Aurelsicoko** [comment]
Yes, I agree! I've created a card on Product Board https://portal.productboard.com/strapi/c/49-display-relational-field-in-list-view 👍
