### ISSUE TITLE
Define a selection of available role on signup

### ISSUE THREAD

**Issue by Ketcap** [strapi/strapi#2545]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

User can select role while signup process. 

ex: Parent, Teacher, Boss roles created by manually or using default roles,
User will select those specific roles. Still can be default roles.

updated code base on my project
```
const roleQuery = params.role ? { _id: params.role } : { type: settings.default_role };
const role = hasAdmin === false ? root : await strapi.query('role', 'users-permissions').findOne(roleQuery, []);
```

**Comment by Aurelsicoko** [comment]
It seems to be a security issue... The user shouldn't be able to choose his role because it could use the parameters to choose the `admin` role and bypass the real administrators.

**Comment by derrickmehaffy** [comment]
> It seems to be a security issue... The user shouldn't be able to choose his role because it could use the parameters to choose the `admin` role and bypass the real administrators.

I agree 100%, default role, users should not be able to pick or choose their own role. Admins/Mods/whatever need to set them.

**Comment by lauriejim** [comment]
In my understanding of this feature is:

You have roles `Admin`, `Manager`, `Public`, `Client`, `Enterprise` in your app.
And you can chose roles available on register `Client` and `Enterprise` only.
In this case you have only one `/register` route.
In any case you will never be able to register as `Admin` or `Manager` cause there are not allow.

If this feature will not be developed you have to duplicate the register route & controller function to have one by role you want able to register.

**Comment by lauriejim** [comment]
We are not planning to develop this feature.
I close this issue.
If you want to have it in your application feel free to implement it by overriding the `register` function.
Here is where stuff happens: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L407
