### ISSUE TITLE
Add login/register mutation GraphQL

### ISSUE THREAD

**Issue by mikaelgramont** [strapi/strapi#2546]
I'm looking at the GraphQL schema definition in the users permissions plugin [schema.graphql file](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/schema.graphql) and I think missing from it is how to perform login/logout operations (which are available at /auth/local on the Strapi REST server).

... or am I missing something? :)

**Informations**
- **Strapi version**: 3.0.0-alpha.17

**Comment by derrickmehaffy** [comment]
@mikaelgramont GraphQL is only a query language, it isn't designed for something like authentication.

**Comment by derrickmehaffy** [comment]
(Also it would be far more complex to build something into the GraphQL schema to auth, when you get basically zero benefit from it over the rest route. The best way to handle REST vs GraphQL is to just use both for their strong points, in this case REST just handles authentication much easier and faster)

**Comment by mikaelgramont** [comment]
I'm really surprised to hear this argument, which IMHO is wrong on many levels:

- GraphQL is not "only a query language", it supports mutations as well, which are meant to change the state of the server, just what we need.
- There's nothing special about authentication. Send identifier and password in, get a JWT out. It's the same type of transaction as creating any other business object, only here we're dealing in JWTs. One example of this: https://www.howtographql.com/react-apollo/5-authentication/
- Why would it be particularly complex to do that? We need mutations in the schema, and resolvers that point to the Users Permissions Auth controller.
- If nothing else, one benefit you get is having a single way to talk to your backend with no need to fork your code to handle talking GraphQL or REST.

**Comment by derrickmehaffy** [comment]
@mikaelgramont :

https://graphql.org/

![image](https://user-images.githubusercontent.com/8593673/50472965-5f3bf080-0978-11e9-90b8-5c58d891e11e.png)

If you want to add it then by all means submit a PR 😄 Adding a simple route in your frontend with REST is easily. Both sides have their benefits and drawbacks. I'm a firm believer in using both,

**Comment by derrickmehaffy** [comment]
FYI a mutation is a type of query, it is just one that can do updates.

**Comment by mikaelgramont** [comment]
We can argue over semantics regarding queries and mutations, but I think it's fair to say that logging in through GraphQL can be done :)

The fact that it's not done tells me that either GraphQL is not a priority or just starting out, which worries me a little.

I'll look into a PR, and may also look into writing my own custom GraphQL server tailored to only what I need.

**Comment by Aurelsicoko** [comment]
@mikaelgramont You're right! The mutations were missing. There is already a PR which is going to be merged to fix this (see https://github.com/strapi/strapi/pull/2380).

**Comment by yareyaredesuyo** [comment]
refs about graphql auth 

- https://www.apollographql.com/docs/apollo-server/features/authentication.html
- https://github.com/accounts-js/accounts
- https://github.com/accounts-js/accounts/tree/master/examples/graphql-server-typescript
- https://github.com/Volst/graphql-authentication

**Comment by Aurelsicoko** [comment]
This PR hasn't been solved due to a lack of time. I had only added the create, update and delete mutations for the users. If someone can continue my work and add the login/logout and register mutations it could be awesome 👍

**Comment by emahuni** [comment]
@derrickmehaffy please read this so that you have a better understanding of GraphQL: https://blog.apollographql.com/the-anatomy-of-a-graphql-query-6dffa9e9e747
This is a very simple explanation of terms etc. It will help you in the future.

**Comment by kalanyuz** [comment]
@Aurelsicoko @lauriejim I want to contribute to the login/register mutation because I need it myself. How do I approach this? Since Auth controllers does not have any models belong to it, adding just a resolver inside /configh/schema.graphql file gives you "x is declared in resolver but not in schema." 

I'm also new to GraphQL so sorry if the question is too simple.

**Comment by mustafa-kahraman** [comment]
Strapi graphql mutation
```gql
mutation Login($input: UsersPermissionsLoginInput!) {
  login(input: $input) {
    jwt
    user {
      id
      email
      confirmed
      blocked
      role {
        id
        name
        description
        type
      }
    }
  }
}


```

**Comment by Ajithp** [comment]
Mustafa,
Thanks a lot man. I was searching for this exact answer. This is working fine in my project.

> Strapi graphql mutation
> 
> ```graphql
> mutation Login($input: UsersPermissionsLoginInput!) {
>   login(input: $input) {
>     jwt
>     user {
>       id
>       email
>       confirmed
>       blocked
>       role {
>         id
>         name
>         description
>         type
>       }
>     }
>   }
> }
> ```
> 
> variables for mutation
> 
> ```graphql
> {
>   "input": {
>     "identifier": "user@exaple.com",
>     "password": "123456",
>     "provider": "local"
>   }
> }
> ```

Mustafa,
Thanks a lot man. I was searching for this exact answer. This is working fine in my project.

**Comment by DominiqueBertrand** [comment]
it works well, but it is not dynamic (i.e. the query does not allow you to retrieve additional fields which can be added to the Users type)

**Comment by thexpand** [comment]
@mustafa-kahraman 
What is the provider field for in the `UsersPermissionsLoginInput` input type? I see that you're setting it to `"local"` in the variables for the mutation, but can't understand its purpose. It's not documented on Strapi's documentation https://docs.strapi.io/developer-docs/latest/plugins/graphql.html#authentication

**Comment by mustafa-kahraman** [comment]
@thexpand My solution was version 3 (old strapi) maybe its changed in v4. You should follow the docs.

**Comment by tahaMage4** [comment]
> 

Hello i use that query for signup mutation in starpi but getting 400 error 

mutation Register($input: UsersPermissionsRegisterInput!) {
		register(input: $input) {
			jwt
			user {
				email
				username
				password
			}
		}
	}

**Comment by tahaMage4** [comment]
Any Solution?
