### ISSUE TITLE
Group content type

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2548]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I think we need an ability to group content type together just for find simply and better UX. For example I create two content type called `location` and `location type` that link together with a relation. For me it's better if we can group these two content type with a single drag and drop feature.

Exactly same as this feature request but for content type: #2219
This feature can be very handy and useful specially when we work with a large number of content type.

**Comment by mnlbox** [comment]
I think we can also add `tag title` and `tag color` to each content type and show this in admin panel. Something like something now we have for users content type: (tag title = user mermissions, tag color = blue)

![content type tag](https://user-images.githubusercontent.com/25859075/51110644-ac401380-180e-11e9-9123-406b76c68a53.png)

Then I can add something similar through admin panel for all content type. :wink: 

@Aurelsicoko

**Comment by Aurelsicoko** [comment]
So you want to group them in the menu? I'm not sure to clearly understand the proposal...

**Comment by GoogolHz** [comment]
I recommend that it be a menu (hierarchy) grouping.

**Comment by lauriejim** [comment]
This feature request has been added to ProductBoard so I close this issue.

**Comment by feitzi** [comment]
Any news? I can't find this on your ProductBoard and I really miss the option to group collections types. We have a huge amount of types and grouping will improve the handling a lot!

**Comment by marc-thomas** [comment]
I also can't find it in product board, would like to know the status!

**Comment by derrickmehaffy** [comment]
https://portal.productboard.com/strapi/1-roadmap/c/13-administration-menu

**Comment by hsnassaad** [comment]
Is this feature added to the Strapi v4? and if yes where can i find it.

**Comment by maximiliano-gt** [comment]
> Is this feature added to Strapi v4? and if yes where can i find it.

Looking for something similar, how can we group fields ?

**Comment by derrickmehaffy** [comment]
No we have not added this
