### ISSUE TITLE
Can not access to the admin folder

### ISSUE THREAD

**Issue by AminZibayi** [strapi/strapi#2549]
**Informations**
- **Node.js version**: v11.5.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MongoDB version 3.6
- **Operating system**: Windows 10 version 1803 build 17134.471 (Using ubuntu 18.04 WSL)

**What is the current behavior?**

I can not find any `./admin` folders.

![issue](https://user-images.githubusercontent.com/43344360/50474647-0c455600-09d7-11e9-8dae-42d7c538ebeb.png)

I also used both windows and ubuntu (VM) file explorers; however, I encountered the same problem.

**Steps to reproduce the problem**

I followed [this guideline](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md); also, i tried both `yarn run setup` and `yarn run setup:build`. _npm didn't work!_

**What is the expected behavior?**

There should be a `./admin` folder

**Comment by soupette** [comment]
Since you're using Windows can you try uninstalling strapi with yarn and install it with npm instead?

**Comment by derrickmehaffy** [comment]
Windows isn't supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows
Yarn isn't supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#yarn

**Comment by AminZibayi** [comment]
Thank you @derrickmehaffy and @soupette.
npm installs strapi using command `npm install strapi@alpha -g`; the problem is using command `npm run setup`, yarn finishes the process with no error.

**Comment by soupette** [comment]
@AminZibayi so there's no issue anymore?

**Comment by AminZibayi** [comment]
Command `npm install strapi@alpha -g` works.
I followed [this guideline](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md);
i ran `strapi -v` and `npm ls strapi`:
![sttitled](https://user-images.githubusercontent.com/43344360/50658062-76e52b80-0fad-11e9-8ac6-d5416e602661.png)
then i ran command `npm run setup` several times and tried to solve the problem...
![sttitled](https://user-images.githubusercontent.com/43344360/50665254-2bd71280-0fc5-11e9-92cb-9ccace940006.png)

**Comment by soupette** [comment]
Well I'm not sure it's related to Strapi.

contributing with windows is kind of difficult currently

**Comment by AminZibayi** [comment]
It is bash not windows! @soupette

**Comment by AminZibayi** [comment]
Thank you for your intelligent suggestion @derrickmehaffy! and sorry for answering late... i was fighting with an army of errors and problems...!
Yes, it is a Windows drive... should i setup strapi at `AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\`?
can i instead of using the command `npm run setup`, just run `npm install strapi@alpha -g`? what is the exact difference between them?

**Comment by derrickmehaffy** [comment]
@AminZibayi I honestly have no idea if that is the actual problem. 

Installing Strapi globally allows you to run the CLI tools, the strapi package also is used by your project. (In theory you could just link the package in your project directories node modules folder into your bashrc path but that is complex and honestly not needed, hence the global install)

npm i (don't use run setup unless your working with the source code) just installs the packages that Strapi needs. At the moment a single project cannot rebuild the admin build folders so if yours are missing you need to create a new temporary project and copy them over (you can delete it afterwards).

Honestly at this point it seems to me something is seriously broken in your project. I recommend you follow my "update" guide (in this case you are "fixing" your project) that is listed here: https://github.com/strapi/strapi/issues/1880

**Comment by AminZibayi** [comment]
I have no project now, just want to create a new admin panel following material design concepts for strapi.
Is it possible by running `npm install strapi@alpha -g` then `strapi new my-project --dev`?

**Comment by lauriejim** [comment]
No you can't. To generate a project with `--dev` you have to follow the contributing guide.

**Comment by AminZibayi** [comment]
Thanks @lauriejim, Yes... the problem still exists and i'm still interested to know the solution!

**Comment by jacargentina** [comment]
Hey I'm also having a similar error when doing `npm run setup:build`, but i'm  on `Linux`!

<img width="1428" alt="captura de pantalla 2019-02-04 a la s 10 14 23" src="https://user-images.githubusercontent.com/517228/52210374-abc2f780-2865-11e9-90d4-f5b2a7dba319.png">

I see `@babel/helper-annotate-as-pure` in common with previous screenshot by @AminZibayi

**Comment by lauriejim** [comment]
Can you be sure there is no `package-lock.json` file present and can you clear you npm cache `npm cache clear`

And you confirm you DON'T use yarn?

**Comment by jacargentina** [comment]
@lauriejim i've just did this to confirm:

```
git clone https://github.com/strapi/strapi.git jimlaurie
cd jimlaurie
npm run setup:build
```
And got the very same error

```
npm ERR! path /home/javiercastro/git/jimlaurie/packages/strapi-admin/node_modules/.staging/strapi-helper-plugin-36dc82f6/node_modules/@babel/helper-annotate-as-pure
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/javiercastro/git/jimlaurie/packages/strapi-admin/node_modules/.staging/strapi-helper-plugin-36dc82f6/node_modules/@babel/helper-annotate-as-pure' -> '/home/javiercastro/git/jimlaurie/packages/strapi-admin/node_modules/.staging/@babel/helper-annotate-as-pure-01f439f9'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javiercastro/.npm/_logs/2019-02-05T15_30_57_127Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.22 setup: `npm run clean:all && npm install ./packages/strapi-lint --save-dev && npm install && node ./scripts/setup.js && npm run clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @3.0.0-alpha.22 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javiercastro/.npm/_logs/2019-02-05T15_30_57_181Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @3.0.0-alpha.22 setup:build: `npm run setup --build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @3.0.0-alpha.22 setup:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/javiercastro/.npm/_logs/2019-02-05T15_30_57_237Z-debug.log
```

As it is a clean clone, there is not `package-lock.json` at all (verified btw!)

**Comment by jacargentina** [comment]
```
Fedora release 29 (Twenty Nine)
node and npm: both are from  nodejs-10.15.1-1nodesource.x86_64
```
