### ISSUE TITLE
ctx.render is not a function

### ISSUE THREAD

**Issue by MatteoGioioso** [strapi/strapi#2551]
**Informations**
- **Node.js version**: v10.14.1
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: Mongo db
- **Operating system**: Windows 10 pro

**What is the current behavior?**
I am trying to render a view with Strapi
but I get this error
`TypeErro: ctx.render is not a function`

If I try with `send` it works find however when I try `render `it does not work

**Steps to reproduce the problem**
my controller
```
module.exports = {
  //GET /home
  home: async (ctx) => {
    ctx.render('home', {message: 'Hello world'});
  }
};

```

my package.json
```
{
  "name": "test-app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application.",
  "main": "./server.js",
  "scripts": {
    "setup": "cd admin && npm run setup",
    "start": "node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "ejs": "^2.6.1",
    "lodash": "^4.17.5",
    "strapi": "3.0.0-alpha.17",
    "strapi-hook-mongoose": "3.0.0-alpha.17",
    "strapi-views": "^3.0.0-alpha.6.4"
  },
  "author": {
    "name": "A Strapi developer",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "A Strapi developer",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "packageManager": "npm",
    "uuid": "f9dbf540-b7ec-4868-ab6e-863740f99b29"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}

```

my custom.json

```
{
  "views": {
    "enabled": true,
    "map": {
      "ejs": "ejs"
    },
    "viewExt": "ejs",
    "debug": true,
    "cache": true
  }
}
```
My `./views` folder is placed in the root directory:
`./views/home.ejs`

**What is the expected behavior?**
To render a view

**Suggested solutions**
I am pretty sure I am missing some dependencies.
The docs states that:

> You need to add strapi-views into your app's dependencies

but when I went to the npm page of `strapi-views`: https://www.npmjs.com/package/strapi-views
It is written `strapi-redis`. Quite confusing on what that package really is.

PS: also the documentation is unclear, especially on 

> It works exactly as before.

What does that mean? The code snippet referred as 'before' is this one? 
```
yield this.render('user', {
  firstname: 'John',
  lastname: 'Doe'
});
```

Or we have to use the new `ctx` object? Because otherwise there is no reference for this 'before'

**Comment by lauriejim** [comment]
By default Strapi is not for render views. That is why there is no documentation about that point.

**Comment by fauzandotme** [comment]
@MatteoGioioso hi, could you show me example how to render a view?
I look everywhere, but i coudn't find it.

**Comment by lauriejim** [comment]
Here in the readme of this hook, you will fin information you want https://github.com/strapi/strapi/tree/master/packages/strapi-hook-ejs

**Comment by yurijmikhalevich** [comment]
@lauriejim is there a way to use something like `strapi-hook-pug`?

**Comment by lauriejim** [comment]
Hello! `pug` can you tell me more.
For now there is only to hook to connect to databases.
- `strapi-hook-mongoose` for MongDB
- `strapi-hook-bookshelf` for MySQL (MariaDB) Postgres and SQLite$
For now it's too complicated to create it's own new hook to connect to an other database.

**Comment by yurijmikhalevich** [comment]
@lauriejim it's `jade` template engine rebranded. Already figured out that there is no such hook and made one myself :-) 
Sorry for the disturbance.

**Comment by indatawetrust** [comment]
if there is a source code on this topic can you share? I can't find any code examples for version 3.

**Comment by mahish** [comment]
@yurijmikhalevich Im about to start a new PUG project. Wanted to try Strapi. You might share your hook maybe? I would be interested!

**Comment by Ayush-Rajniwal** [comment]
Here is a guide on How to use EJS with Strapi

- Installed strapi-hook-ejs 
- Update the .config/hook.json with
```
...
{
  "views": {
    "enabled": true,
    "map": {
      "ejs": "ejs"
    },
    "viewExt": "ejs"
    "debug": true,
    "cache": true
  }
}
...
```
- Added this to the controller, say _./api/api-name/controllers/api-name.js_
```
module.exports = {
  //GET /index
  index: async (ctx) => {
    ctx.render('home', {title: 'Hello world'});
  }
};
```
- Create a directory views in root folder
- Add your ejs templates in the ./views
- Example ./views/home.ejs
`<%= title %>`

> Side note: In the above example, I have used the "index" in the controller api-name.js file. Make sure your API  _./api/api-name/config/routes.json_ point to it.
