### ISSUE TITLE
JSON API Support

### ISSUE THREAD

**Issue by srsgores** [strapi/strapi#2554]
As per #13, what are any current solutions for closely adhering to the specification?  And since the feature is not planned for immediate work, what can developers do in the mean time who wish to be compliant and still use strapi?

**Comment by lauriejim** [comment]
Hello @srsgores !

I suggest you to create a middleware and modify the content of the response to match with JSON API format.

You can find middleware documentation here https://strapi.io/documentation/3.x.x/advanced/middlewares.html

**Comment by srsgores** [comment]
Hi @lauriejim 

I have a VERY basic example running, but it doesn't handle pagination or nested relations:

```
const JSONAPISerializer = require("jsonapi-serializer").Serializer;
const jsonapi = require("koa-jsonapi-middleware");

module.exports = strapi => {
	return {
		initialize: function(cb) {
			strapi.app.use(jsonapi());
			strapi.app.use(async (ctx, next) => {
				await next();
				const {body} = ctx.response;
				let response = body.toJSON();
				if (body["model"] && body.model["collectionName"]) {
					response = new JSONAPISerializer(body.model.collectionName, {attributes: Object.keys(body.model.attributes)}).serialize(response);
				}
				ctx.body = response;
			});

			cb();
		}
	};
};
```

I think for nested relations, [this library](https://github.com/scoutforpets/bookshelf-jsonapi-params) should help, but I wasn't able to determine how to access the `knex` query from within the middleware.  Perhaps you can advise.

**Comment by lauriejim** [comment]
Ho yap it's really not well documented but you have access to it with `strapi.connections.default`
