### ISSUE TITLE
Email confirmation link hangs [using heroku]

### ISSUE THREAD

**Issue by pauldariye** [strapi/strapi#2560]
**Informations**

Steps to reproduce the problem
- **Node.js version**: v11.0.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.17 
- **Database**: Mongo v4.0.2
- **Operating system**: MacOS Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I'm using a diferent host (`*.herokuapp.com`) for my server. The link that I get 

```
http://.herokuapp.com:18845/auth/email-confirmation?confirmation%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzI2YTU2NjA3ODg1ZjAwMTdmMGNlZTIiLCJpZCI6IjVjMjZhNTY2MDc4ODVmMDAxN2YwY2VlMiIsImlhdCI6MTU0NjAzNjU4MiwiZXhwIjoxNTQ4NjI4NTgyfQ.9s0S71-dM0kF9cxPVvbJ3AtGzvNtU0M1KLOuoJMuJVo&source=gmail&ust=1546122989184000&usg=AFQjCNHpkCRYDZ8IIrfPGW93T3tfFBFAvQ
```

keeps loading without redirecting. By the way this works when I'm using localhost. 

**Steps to reproduce the problem**
1. Update production configuration for the server host and deploy to production server. 
2. Enable email confirmation
3. Register new user
4. Click on emailed link

**Comment by lauriejim** [comment]
Hello @pauldariye.

The server still working on `localhost` with Heroku.
You have to use `proxy` config to make it works correctly.

Here is an example of `server.js` config

```json
{
  "host": "localhost",
  "port": "${process.env.PORT || 1337}",
  "proxy": {
    "enabled": true,
    "ssl": true,
    "host": "strapi-simple-deploy.herokuapp.com",
    "port": 443
  },
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
```

**Comment by pauldariye** [comment]
Thanks, @lauriejim !!!
