### ISSUE TITLE
Cannot read property 'globalId' of undefined (error on GraphQL Types)

### ISSUE THREAD

**Issue by HelenDias** [strapi/strapi#2564]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: 6.5.0-next.0
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MySQL 14.14
- **Operating system**: ElementaryOS 5.0

**What is the current behavior?**
I am trying to run strapi start, but the error "Cannot read property 'globalId' of undefined" appear and project crashed.
The error is that one:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'globalId' of undefined
    at Object.convertType (/home/helen/Pracas/strapi-api-pracas/plugins/graphql/services/Types.js:79:30)
    at Object.keys.filter.reduce (/home/helen/Pracas/strapi-api-pracas/plugins/graphql/services/Resolvers.js:87:34)
    at Array.reduce (<anonymous>)
    at models.reduce (/home/helen/Pracas/strapi-api-pracas/plugins/graphql/services/Resolvers.js:85:10)
    at Array.reduce (<anonymous>)
    at Object.shadowCRUD (/home/helen/Pracas/strapi-api-pracas/plugins/graphql/services/Resolvers.js:40:19)
    at /home/helen/Pracas/strapi-api-pracas/plugins/graphql/services/Schema.js:163:24
    at Object.generateSchema (/home/helen/Pracas/strapi-api-pracas/plugins/graphql/services/Schema.js:164:11)
    at Function.initialize (/home/helen/Pracas/strapi-api-pracas/plugins/graphql/hooks/graphql/index.js:148:50)
    at /home/helen/Pracas/strapi-api-pracas/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/home/helen/Pracas/strapi-api-pracas/node_modules/strapi/lib/hooks/index.js:122:39)
    at /home/helen/Pracas/strapi-api-pracas/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/home/helen/Pracas/strapi-api-pracas/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:276:13)
    at Strapi.emit (events.js:188:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at loadedModule.initialize.call.err (/home/helen/Pracas/strapi-api-pracas/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (/home/helen/Pracas/strapi-api-pracas/node_modules/strapi-hook-bookshelf/lib/index.js:1003:7)
(node:30163) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30163) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the problem**
I was able to run the project and I installed the GraphQL plugin.
I even created some models and accessed them in http://my-url/graphql, but when I trying to fix a model to remove a rule (removing the not null rule), the strapi crashed and when I executed the project again, this error appear and I could not run it anymore.

**What is the expected behavior?**
The project run.

**Suggested solutions**
The error occurs somewhere in the types of GraphQL, but I could not fix it. In fact, I see why the 'globalId' became undefined, but I don't know how to fix it.
I tried to remove the table that I was updating, but not works too.
I tried to increase the execution time in hook.json, but didn't work too.

Please, anyone can help me?

**Comment by HelenDias** [comment]
Sorry, the error happened when I change a column name, and I forgot this.
I changed a column name and this one was referenced in another column, as a foreign key.
So I looked for that one name in my project and find a file that wasn't changed the name.
The file is api/myModel/models/Model.settings.json. When I changed that name, the error doesn't showed up.

Closing that issue because it's a duplicated from #2335
I thought it wasn't duplicate, but it's the same error :/

**Comment by laurenskling** [comment]
Ran into this as well (again). Maybe we should look into throwing a nicer error?

**Comment by SuiOni** [comment]
> Ran into this as well (again). Maybe we should look into throwing a nicer error?

I think that would be awesome. 
Especially when you edit larger projects, having a mistake somewhere and trying to figure the location out is painful.

**Comment by peisenmann** [comment]
The lack of clear error message is still an issue.  Would it make sense to add something like
https://github.com/strapi/strapi/blob/main/packages/plugins/graphql/server/services/builders/input.js#L98-L101
```javascript
            else if (isComponent(attribute)) {
              const isRepeatable = attribute.repeatable === true;
              const component = strapi.components[attribute.component];
              if (!component) {
                console.error(`FATAL: Could not find component for ${attribute.component}. Does ${attribute.component}.json exist?`)
              }
```

I imagine this isn't a complete solution, but this was how I tracked down what was actually wrong in my project (I renamed a component, but I forgot to rename the file)

**Comment by OmarMtya** [comment]
I had the same problem and I found that I was missing a component json file because the name of the component was "log.name-component". Be aware that that kind of folders name can be ignored by .gitignore, when you put your Strapi in production you're missing that file
