### ISSUE TITLE
CORS origin still posting

### ISSUE THREAD

**Issue by nickngqs** [strapi/strapi#2566]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: 6.5.0-next.0
- **Strapi version**: 3.0.0-alpha.17
- **Database**: Mongodb
- **Operating system**: MacOS

**What is the current behavior?**
Setting up CORS origin with a specific domain like http://example.com. But when I tested, CORS Read Blocking blocked cross origin response. But the POST data still went through. What's the correct way to allow only POST data from a certain website. For example my frontend is hosted on another domain and backend is my STRAPI api.

**Comment by lauriejim** [comment]
Hello @nickngqs , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.

Please update your issue.
We need to know exact steps to reproduce.

Thank you.
