### ISSUE TITLE
Strapi not installing plugin dependencies

### ISSUE THREAD

**Issue by shash7** [strapi/strapi#2568]
**Informations**
Node 10.15.0
npm 6.4.1
Strapi 3.0.0-alpha.17
Mongodb
Ubuntu 16

**What is the current behavior?**
After setting up a sample project locally, I git repo the whole folder and clone it on my digital ocean droplet. There I do npm install and npm run setup. Npm install is fine but npm run setup throws an error and states that it cannot find immutable package.
On further investigation I found that packages for plugins aren't installed. Is there another command to install packages for the plugins or do I manually install the packages?

**Comment by derrickmehaffy** [comment]
`npm run setup:build`

That should install everything you need, you will get warnings about missing plugin "depends" that aren't actually needed. Note for the build step on ubuntu you need a local package installed called `libpng-dev` just install with apt get.

**Comment by lauriejim** [comment]
In your generated app you can run:
- `npm i` it install all node modules in your project, admin and plugins
- `npm run setup` it build the admin
- `npm run setup --plugins` it build admin and all plugins

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/is-there-a-proper-way-to-install-local-plugins-dependencies/720/1
