### ISSUE TITLE
Ability to make fields private in Content Builder plugin

### ISSUE THREAD

**Issue by chaitanyya** [strapi/strapi#2573]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Currently, we do have the ability to make fields private using the following attribute in the model `settings.json` file. 
```json
"address": {
  "default": null,
  "type": "string",
  "private": true
}
```

**UI Suggestion for Content Type Builder**
The content-type-builder plugin doesn't yet support this, maybe having a **Private field** checkbox on the advanced settings would do. Something like:

![Suggested Checkbox Example](https://drive.google.com/uc?export=view&id=18XOsumOgb2dXFW0QzNcj769QAJu3VFc_)

**Comment by lauriejim** [comment]
Thank you @chaitanyya for your contribution.
