### ISSUE TITLE
Support the latest version of node

### ISSUE THREAD

**Issue by patrickblackjr** [strapi/strapi#2576]
What is stopping you from supporting v11.6.0 of node? I haven't scoped out the codebase to see what might be holding back support for it. How difficult would this be to implement?

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/50706936-20f79e80-1014-11e9-9ea5-19760f0d2538.png)


^^^ Schedule for LTS

From what I've seen Node 11 causes extremely high CPU usage with no benefits.

**Comment by derrickmehaffy** [comment]
That and Node 11 will not be a core LTS version thus pointless to support it for now. Similar to Node 9
