### ISSUE TITLE
GraphQL plugin not functioning when following Deliveroo clone with Nuxt tutorial

### ISSUE THREAD

**Issue by patrickblackjr** [strapi/strapi#2577]
**Information**
- **Node.js version**: v10.11.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.18
- **Database**: MongoDB / GraphQL
- **Operating system**: macOS

**What is the current behavior?**
After running `npm install graphql@0.13.2 --save` per the instructions of the tutorial found [here](https://blog.strapi.io/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-restaurants-list-part-2-7/), I get this error:

```bash
Cannot find module '.../server/plugins/graphql/config/environments/development/server.json'
```

**Steps to reproduce the problem**
Follow the tutorial linked above.

**What is the expected behavior?**
To work like the tutorial says.

**Comment by sonovice** [comment]
@patrickblackjr Any hints on what went wrong or how you resolved it?
