### ISSUE TITLE
addRelation is not a function

### ISSUE THREAD

**Issue by anitricks** [strapi/strapi#2581]
**Informations**
- **11.4.0**: 
- **NPM version**: 
- **3.0.0-alpha16**: 
- **MySQL**: 
- **MacOS**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
```TypeError: strapi.services.order.addRelation is not a function```

**Steps to reproduce the problem**
Create a new model
Try to update relation with a PUT request

I just started with strapi (great product btw) so I dont know if these are controller functions have been removed or just not working. i read documentaion but couldn't see it. I was trying to find way to update a relation while also updating the model. is it possible with these routes or are they something else? Haven't got them to work at all ( Any of the relation routes generated with the models) 

Thanks for the help

**Comment by derrickmehaffy** [comment]
@anitricks if I understand right your trying to be able to send nested relational data?

**Comment by anitricks** [comment]
@derrickmehaffy yes.

**Comment by derrickmehaffy** [comment]
At the moment @anitricks it isn't possible without some major modification. The only relational data you can send is the ID of the relation entry

**Comment by anitricks** [comment]
@derrickmehaffy oh ok. ill create a card in the upcoming board for strapi then. thanks for quick responses

**Comment by anitricks** [comment]
so what is the use case for those functions then? (createRelation, updateRelation and destroyRelation)

**Comment by derrickmehaffy** [comment]
honestly no idea @lauriejim @Aurelsicoko thoughts on what those routes do?

**Comment by derrickmehaffy** [comment]
He is talking about these: 
![image](https://user-images.githubusercontent.com/8593673/50734174-eb57d000-114f-11e9-9dfa-2b8acbd257aa.png)

**Comment by derrickmehaffy** [comment]
And their permissions

**Comment by lauriejim** [comment]
Hello @anitricks.

We delete services but routes and controller function have to be deleted.
Actually if you want to manage your relations, you will find request to do here https://strapi.io/documentation/3.x.x/guides/models.html#relations
