### ISSUE TITLE
WYSIWYG Editor disappear on production heroku

### ISSUE THREAD

**Issue by Vivsss** [strapi/strapi#2582]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
In production environment, the WYSIWYG Editor disappear

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**
Thanks to @lauriejim for the answer ! 
To manually fix it you will have to migrate your 'core_store' key 'plugin_content-manager_schema' value from your 'dev' database to 'production' database.

**Comment by derrickmehaffy** [comment]
Closing due to missing information and the user already has the correct answer to migrate their database
