### ISSUE TITLE
Deploy Strapi to Netlify

### ISSUE THREAD

**Issue by edoardolunardi** [strapi/strapi#2586]
**Informations**
- **Node.js version**: v10.7.0 
- **NPM version**: 6.1.0 
- **Strapi version**: 3.0.0-alpha.18 
- **Database**: MongoDB 
- **Operating system**: 
- **(Optional) Link to your Project**: 

Hi guys, is there any guide to deploy Strapi to Netlify? I followed the Getting Started guide. Running locally, I can open my admin page with `http://localhost:1337/admin` and see my posts in json format here `http://localhost:1337/posts`. I have uploaded the project to a repo in Github, then deployed to Netlify. The problem is that the routes are not working as you can see https://affectionate-villani-fba24c.netlify.com/admin. How can I solve this? Sorry for the maybe dumb question but I'm very new to the APIs world and then to Strapi. Thank you for the support.

(update: sorry for the typo error, I always confuse Strapi with Stripe)

**Comment by gustavpursche** [comment]
@edoardolunardi I can't suggest anything, because I just stumpled upon your question :) Heroku, DigitalOcean, AWS, Azure or any virtual server - any service, that let's you host a node web application, depending on your level of knowledge. Heroku makes it quite easy to setup everything.

**Comment by edoardolunardi** [comment]
Thank you for the clarification!

**Comment by sarneeh** [comment]
@gustavpursche Worth to mention, that the documentation actually suggests Netlify as a deploy platform 😄 

![image](https://user-images.githubusercontent.com/11553624/68853809-19486200-06db-11ea-97ee-1a7448451773.png)

**Comment by Crytiqal** [comment]
Would this not just require to use an external database instead of the sqlite default? It could then be deployed to netlify afaik?

**Comment by sarneeh** [comment]
> Would this not just require to use an external database instead of the sqlite default? It could then be deployed to netlify afaik?
> 
> Correct me if I'm wrong.

It requires a place to run a **server**. You can't run a server on Netlify - you can only put static files there (html, js, css, etc.)

**Comment by okuninoshi** [comment]
> @gustavpursche Worth to mention, that the documentation actually suggests Netlify as a deploy platform 
> 
> ![image](https://user-images.githubusercontent.com/11553624/68853809-19486200-06db-11ea-97ee-1a7448451773.png)

the one who wrote this was thinking about SSG,

**Comment by bornakke** [comment]
Can strapi be run on Netlifys function the same way as graphql today can be hosted there?

**Comment by nicknijenhuis** [comment]
> Can strapi be run on Netlifys function the same way as graphql today can be hosted there?

I guess technically it could be done these days if you have an external database somewhere and you stay within the limits. Probably need some magic to get it working fully though. Best just use Railway.app, or similar.

https://docs.netlify.com/functions/overview/#default-deployment-options
