### ISSUE TITLE
ContentTpyes naming conversation for Russian locale

### ISSUE THREAD

**Issue by denisinvader** [strapi/strapi#2587]
**Informations**
- **Node.js version**: v10.12.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.18
- **Database**: MongoDB
- **Operating system**: macOS Mojave Version 10.14.2
- **(Optional) Link to your Project**: local test project

**What is the current behavior?**

Menu item text for ContentTypeBuilder plugin is different from the title and Content Types translation to Russian on the `/admin/plugins/content-type-builder` page for Russian locale.

**Steps to reproduce the problem**

Just navigate to `/admin/plugins/content-type-builder`

**What is the expected behavior?**

Translations of "Content Types" to Russian are the same everywhere.

**Suggested solutions**

It seems like in the `strapi-admin` package "Content Types" was translated as "Типы Контента" but in the `strapi-plugin-content-type-builder` package it was translated as "Типы данных".

"Типы данных" means "Data Types" not "Content Types". I would recommend to translate "Content Types" as "Типы Контента" everywhere in admin. I can create PR for this issue if someone approves the correct translation.

**Comment by denisinvader** [comment]
No. I didn't want to fix it without a discussion about what naming should we use.

By the way, I would also rename "Конструктор Типов Данных" to "Типы данных" in the left menu.

**Comment by lauriejim** [comment]
Arg for this type of wording, I would like @Aurelsicoko assign.

**Comment by denisinvader** [comment]
"Данные" (data) in Russian language associates more with raw data like .csv file or SQL tables. "Контент" (content) is an abstraction over data like classes and OOP. In my experience, CMS usually provides such abstractions. 
  
"Тип данных" (data type) usually uses in fields or variables description (string, number, stack, array etc).

For example, article or user is a content type (it's "тип контент") and we can say that all articles in the site are "контент". Articles' title, user login or password are "данные": they are of string type and have some values in a database. 

I think "данные" it's more about importing some values or filling the table by UI, "контент" it's what the end user is working with.

**Comment by Aurelsicoko** [comment]
@denisinvader Thank you for noticing this. We should use the word "Content", so it means that it should be translated to "Типы Контента" (feel free to correct my Russian 🙈). Can you submit a PR, we'll be happy to merge it? 👍

**Comment by denisinvader** [comment]
@Aurelsicoko I will update it in #2589
