### ISSUE TITLE
Error: Cannot find module 'immutable' on existing project deploying on server

### ISSUE THREAD

**Issue by jkbaseer** [strapi/strapi#2588]
**Informations**
- **Node.js version**: v10.15.0 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.18 
- **Database**: PostegreSQL
- **Operating system**:  Ubuntu 16.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
`root@ed-api-v1:~/ed-api# strapi start
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'strapi-generate'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/ed-api/plugins/content-type-builder/services/ContentTypeBuilder.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
^C
`

**Steps to reproduce the problem**
If you have hosted this on ubuntu 16.04 with a code that is pulled from your bitbucket (A) , it may not work. but it works when we create a new project.

**What is the expected behavior?**

The app should strart running in the localserver:1337 as everytime it does. 

**Suggested solutions**
While researching, people are suggesting this is due to the new node version https://github.com/node-inspector/node-inspector/issues/1044 

1. 
Few people ask to delete node_modules directory and package.json. it doesn't work

2.  but if i see the problem is with lodash module, so i deleted the folder, removed from package folder. And tried strapi start ( am not sure whether it is stupid, then i got node module not found, so i installed fresh of Lodash and again the same issue. 

And i got this npm audit as well, in case it helps
![image](https://user-images.githubusercontent.com/968274/50741284-b3bf5580-122d-11e9-95dc-bb2136f594c9.png)

**Comment by ntloi95** [comment]
The script doesn't npm install all dependency in the plugins folder. You need to cd to all subfolder in the plugins folder and run npm install.
I think they don't document this or there is another alternative way.
![image](https://user-images.githubusercontent.com/9493402/50747784-601e2d80-1268-11e9-8552-09a3c1256b8f.png)
As you can see, all subfolders in the plugins folder have a file package.json

**Comment by ntloi95** [comment]
In your generated app you can run:

npm i it install all node modules in your project, admin and plugins
npm run setup --plugins it build admin and all plugins

**Comment by jkbaseer** [comment]
Thanks Man @ntloi95 

Yes, i went to do it again. 

` **root@ed-api-v1:~/projectname/ed-api# npm i**
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN checkPermissions Missing write access to /root/projectname/ed-api/node_modules/strapi
npm WARN bookshelf@0.12.1 requires a peer of knex@>=0.6.10 <0.15.0 but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-source-filesystem@1.5.39 requires a peer of gatsby@^1.9.250 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint@^3.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@10.0.1 requires a peer of eslint@^3.9.1 but none is installed. You must install peer dependencies yourself.

npm ERR! path /root/projectname/ed-api/node_modules/strapi
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/root/projectname/ed-api/node_modules/strapi'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-07T10_45_33_952Z-debug.log
`


`**root@ed-api-v1:~/projectname/ed-api# npm run setup --plugins**

> projectname@0.1.0 setup /root/projectname/ed-api
> cd admin && npm run setup


> strapi-admin@3.0.0-alpha.17 presetup /root/projectname/ed-api/admin
> node ./scripts/preSetup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...

Packaged installed successfully

> strapi-admin@3.0.0-alpha.17 setup /root/projectname/ed-api/admin
> node ./scripts/setup.js

🏗  Building the admin...
internal/modules/cjs/loader.js:583
    throw err;
Error: Cannot find module '/root/projectname/ed-api/node_modules/strapi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/ethisdigital/ed-api/admin/node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
` 
same as last time.

**Comment by derrickmehaffy** [comment]
@jkbaseer did you install the strapi package globally?

If no, you can't use the strapi command (as your system isn't aware of the location)

There are two places the `strapi` package is "kept":
1) In your global node_modules folder to be used as an executable IE `strapi start`
2) In your project's node_modules/package.json for use by strapi

The reason for the split is, it is possible you may not need the global CLI based tool while running in production if you are using `npm start server.js`

Please run `npm i -g strapi@alpha` to use `strapi start` globally (or any of the CLI based commands like generate)

**Comment by derrickmehaffy** [comment]
I'm marking this issue as closed for now, please update if this didn't fix the issue and we can re-open it.

**Comment by jkbaseer** [comment]
Hey Guys, I would request to open up this issue because i tried running commands like

1) installing strapi alpha on the global using npm i -g strapi@alpha


2) root@ed-api-v1:~/ed/ed-api# ls
README.md  admin  api  config  favicon.ico  node_modules  package.json  plugins  public  server.js

`root@ed-api-v1:~/ed/ed-api#` strapi start
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/ed/ed-api/plugins/content-type-builder/services/ContentTypeBuilder.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`


it doesn't seem to help.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko @lauriejim maybe you can assist here. I think he is using Node Version Manager (NVM) which I believe is causing the issue.

**Comment by Aurelsicoko** [comment]
Did you try to delete the package-lock.json file?

**Comment by thkdog** [comment]
> I have met the same problem,'Cannot find module 'immutable'' ...
> I have strapi new a project, commit to git repo, and setup a dockerfile, build, start, then fail.
> My dockerfile basically just do the `npm i` and then `npm run start`
> 
> ```
> COPY package.json /usr/src/app/package.json
> 
> # 安装npm依赖(使用淘宝的镜像源)
> # 如果使用的境外服务器，无需使用淘宝的镜像源，即改为`RUN npm i`。
> RUN npm i
> 
> # 拷贝所有源代码到工作目录
> COPY . /usr/src/app
> 
> # 暴露容器端口
> EXPOSE 1337
> 
> # 启动node应用
> CMD npm start
> ```
> ```
> website-service_website-service_1 | 2019-01-15T08:19:34.239423918Z Error: Cannot find module 'immutable'
> website-service_website-service_1 | 2019-01-15T08:19:34.239426477Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
> website-service_website-service_1 | 2019-01-15T08:19:34.239429120Z     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
> website-service_website-service_1 | 2019-01-15T08:19:34.239431538Z     at Module.require (internal/modules/cjs/loader.js:637:17)
> website-service_website-service_1 | 2019-01-15T08:19:34.239433806Z     at require (internal/modules/cjs/helpers.js:22:18)
> website-service_website-service_1 | 2019-01-15T08:19:34.239436145Z     at Object.<anonymous> (/usr/src/app/plugins/content-type-builder/services/ContentTypeBuilder.js:7:31)
> website-service_website-service_1 | 2019-01-15T08:19:34.239441299Z     at Module._compile (internal/modules/cjs/loader.js:689:30)
> website-service_website-service_1 | 2019-01-15T08:19:34.239443780Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> website-service_website-service_1 | 2019-01-15T08:19:34.239446116Z     at Module.load (internal/modules/cjs/loader.js:599:32)
> website-service_website-service_1 | 2019-01-15T08:19:34.239448487Z     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> website-service_website-service_1 | 2019-01-15T08:19:34.239450742Z     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> website-service_website-service_1 | 2019-01-15T08:19:34.248909316Z npm ERR! code ELIFECYCLE
> website-service_website-service_1 | 2019-01-15T08:19:34.248926192Z npm ERR! errno 1
> website-service_website-service_1 | 2019-01-15T08:19:34.248929080Z npm ERR! website-service@0.1.0 start: `node server.js`
> website-service_website-service_1 | 2019-01-15T08:19:34.248931989Z npm ERR! Exit status 1
> website-service_website-service_1 | 2019-01-15T08:19:34.248934377Z npm ERR! 
> website-service_website-service_1 | 2019-01-15T08:19:34.248936820Z npm ERR! Failed at the website-service@0.1.0 start script.
> website-service_website-service_1 | 2019-01-15T08:19:34.248939532Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> website-service_website-service_1 | 2019-01-15T08:19:34.253740516Z 
> website-service_website-service_1 | 2019-01-15T08:19:34.253754630Z npm ERR! A complete log of this run can be found in:
> website-service_website-service_1 | 2019-01-15T08:19:34.253757906Z npm ERR!     /root/.npm/_logs/2019-01-15T08_19_34_248Z-debug.log
> website-service_website-service_1 | 2019-01-15T08:20:01.384962830Z 
> website-service_website-service_1 | 2019-01-15T08:20:01.384999292Z > website-service@0.1.0 start /usr/src/app
> website-service_website-service_1 | 2019-01-15T08:20:01.385003054Z > node server.js
> website-service_website-service_1 | 2019-01-15T08:20:01.385005672Z 
> website-service_website-service_1 | 2019-01-15T08:20:02.272182831Z internal/modules/cjs/loader.js:583
> website-service_website-service_1 | 2019-01-15T08:20:02.272242194Z     throw err;
> ```

I have checked the server files, it turns out that the node_modules in plugins are not installed although I have run `npm i` in DOCKERFILE.

**Comment by thkdog** [comment]
> Did you try to delete the package-lock.json file?

I have solved the problem, you can fixed it in 2 ways:
1.
```
npm install --unsafe-perm
```
2.
```
npm i
npm run postinstall
```
Check this related issue: [npm WARN cannot run in wd node-gyp](https://github.com/nodejs/docker-iojs/issues/72)

Which causing the problem is the node_modules in plugins are not installed.
When using `npm i` in dockerfile, when compling, the `postinstall` scrips won't be excuted, as below:
```
npm WARN lifecycle website-service@0.1.0~postinstall: cannot run in wd website-service@0.1.0 node node_modules/strapi/lib/utils/post-install.js (wd=/usr/src/app)
```
So you have to execute it manually or using `--unsafe-perm` options.
