### ISSUE TITLE
Error cast to number failed for value GraphQL

### ISSUE THREAD

**Issue by merijnvanessen** [strapi/strapi#2591]
--specs--
node v10.6.0
strapi": "3.0.0-alpha.18
strapi-plugin-graphql@3.0.0-alpha.17
npm: npm: '6.1.0',
db: mongodb
os: mac osx El capitan 10.11.6
--/specs--

**what**
Hello, i'm having a graphql error on a simple query to number fields (decimals)
The field is not required, so I suppose I could leave it blank. i can save it within the admin without errors. But in the frontend I get an error.

The apollo error
```
Error: "GraphQL error: Cast to Number failed for value "{ message: 'Cast to Number failed for value "" at path "dadsweight"',
  name: 'CastError',
  stringValue: '""',
  kind: 'Number',
  value: '',
  path: 'dadsweight',
  reason: null }" at path "dadsweight"
GraphQL error: Cast to Number failed for value "{ message: 'Cast to Number failed for value "" at path "momsweight"',
  name: 'CastError',
  stringValue: '""',
  kind: 'Number',
  value: '',
  path: 'momsweight',
  reason: null }" at path "momsweight"
GraphQL error: Cast to Number failed for value "{ message: 'Cast to Number failed for value "" at path "price"',
  name: 'CastError',
  stringValue: '""',
  kind: 'Number',
  value: '',
  path: 'price',
  reason: null }" at path "price""
	ApolloError http://localhost:3000/_nuxt/vendors.app.js:3979:21
	queryListenerForObserver http://localhost:3000/_nuxt/vendors.app.js:2994:41
```

**steps**
Field in contenttype with a number: decimal
![schermafbeelding 2019-01-07 om 08 43 06](https://user-images.githubusercontent.com/23075300/50755830-850ba400-125a-11e9-8d71-0aaf515847e7.png)

the query
```
//get the puppies by a slug
export const GET_PUPPY = gql`
query findPuppy($id: ID!) {
  puppy(id: $id) {
    _id
    name
    gender,
    birthdate,
    colors,
    pattern,
    registry,
    dadsweight,
    momsweight,
    price
    breed{
      _id
      name
    }
    images{
      url
    }
    kennels {
      _id
    }
  }
}`;
```
If i fill in all the fields there is no error

```
 {
  "_id": "5c330764f6971f04016e5b68",
  "name": "test 3",
  "gender": "female",
  "birthdate": null,
  "colors": {},
  "pattern": "harlequin",
  "registry": "11",
  "dadsweight": 11,
  "momsweight": 11,
  "price": 11,
  "breed": null,
  "images": [],
  "kennels": null,
  "__typename": "Puppies"
}
```

**Comment by derrickmehaffy** [comment]
@merijnvanessen can you replace your `--specs--` with the proper bug report template values.

Also if you have a link to your project code for us to look at to help debug that would be great.

Can you also provide your query (assuming it's a query and not a mutation).

**Comment by derrickmehaffy** [comment]
Bug report template for reference: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

**Comment by merijnvanessen** [comment]
@derrickmehaffy i should write down those specs :-)

**Comment by merijnvanessen** [comment]
@derrickmehaffy 
Hi derrick, I created an almost empty project with monkeys instead of puppies 
https://github.com/merijnvanessen/strapi-nuxt-apollo-graphql

**Comment by derrickmehaffy** [comment]
@merijnvanessen can you give me the graphQL query you used to generate the error?

**Comment by merijnvanessen** [comment]
yes, within in the repo, you can find it in the frontend/graphql
{QUERY_SINGLE_MONKEY}

https://github.com/merijnvanessen/strapi-nuxt-apollo-graphql/blob/master/frontend/graphql/monkeys.js

**Comment by lauriejim** [comment]
Can you try with also version alpha.18 of the GraphQL.

**Comment by merijnvanessen** [comment]
"raw": "strapi-plugin-graphql@3.0.0-alpha.18"

since I installed it fromout the strapi UI, in this repo its the latest version
https://github.com/merijnvanessen/strapi-nuxt-apollo-graphql

but its still giving me 

```
Error GraphQL error: Cast to Number failed for value "{ message: 'Cast to Number failed for value "" at path "dadsweight"',
  name: 'CastError',
  stringValue: '""',
  kind: 'Number',
  value: '',
  path: 'dadsweight',
  reason: null }" at path "dadsweight"
```
important, i didn't give the field a default value, since this field isn't required within the field advanced settings tab, I would think I can leave this empty
And therefore, save a new item with empty values instead of '0' or something

![schermafbeelding 2019-01-07 om 16 14 42](https://user-images.githubusercontent.com/23075300/50775848-99ba5d00-1297-11e9-84eb-5b8c752969f3.png)

this would result in saving an object somehow within the strapi ui

![schermafbeelding 2019-01-07 om 16 14 14](https://user-images.githubusercontent.com/23075300/50775948-e9008d80-1297-11e9-92e2-718a6955f277.png)

and then, the error is actually saved within the mongo db

![schermafbeelding 2019-01-07 om 16 19 33](https://user-images.githubusercontent.com/23075300/50776003-1baa8600-1298-11e9-9954-d911fa78a750.png)

**Comment by lauriejim** [comment]
I will have to take a look. 
Please for next time can you share your screen in english please.

**Comment by lauriejim** [comment]
I leave an issue on `mongoose-float` about this issue.
https://github.com/Vnkitaev/mongoose-float/issues/6
I hope we will have an answer and maybe a new release of this module soon to be able to fix this issue.
