### ISSUE TITLE
Create project problem - 3.0.0-alpha.18

### ISSUE THREAD

**Issue by EdenLiang** [strapi/strapi#2592]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.18
- **Database**: MySQL
- **Operating system**: Windows10
**What is the current behaviour?**

I follow the guideline but blocked at "strapi new my-project".
When I select the database (MySQL), it does not keep going.
PS: It works well at version '3.0.0-alpha.17'.

![k w57jwb_ zzn j0 6 p 6o](https://user-images.githubusercontent.com/9131600/50760039-a3e15900-12a1-11e9-82d0-c89ba869ddbd.png)
Figure: Stopped after selecting the database, already wait for a long time.

**Steps to reproduce the problem**
1. npm i strapi@alpha -g
2. strapi new my-project

**What is the expected behavior?**
Next step comes out

**Comment by EdenLiang** [comment]
I have uninstall the nodejs (v10.14.2) and reinstall the old version (v8.15.0) and it's worked now.

![1546854115 1](https://user-images.githubusercontent.com/9131600/50761007-44d11380-12a4-11e9-89c5-fa9250e6ac04.jpg)
Figure: It can create the database

So I need to reinstall the nodejs (v10.14.2) after I create the project.

**Comment by derrickmehaffy** [comment]
Windows is not supported: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Marking as closed as this is a duplicate issue: https://github.com/strapi/strapi/issues/1281

**Comment by derrickmehaffy** [comment]
@EdenLiang Please use WSL, windows is not supported due to changes between node 8 and node 10 (Strapi no longer supports the EOL node 8, and the server won't start on node 8)

**Comment by EdenLiang** [comment]
@derrickmehaffy 
Yes
So, for windows user, we can use node 8 to create the project and use node 10 to use Strapi

**Comment by derrickmehaffy** [comment]
If that works for you then great. But any issues that come up while working outside of WSL, Linux, or Mac won't be supported. Just an FYI

**Comment by janjag** [comment]
U can also try using ```npx strapi new <your-project-name>``` to create new project (works for me on windows + node 11.6.0)

**Comment by EdenLiang** [comment]
@janjag @derrickmehaffy 
Thanks for your suggestions, :)
