### ISSUE TITLE
Users can create and delete data in content manager api

### ISSUE THREAD

**Issue by deeq14** [strapi/strapi#2593]
**Informations**
- **Node.js version**:  11.60
- **NPM version**:  6.50
- **Strapi version**:  3.0.0-alpha.17
- **Database**: MongoDB
- **Operating system**:  Windows 10

**What is the current behavior?**
Authenticated users can **CREATE UPDATE & DELETE**  in via **content manager plugin API** after they pass the bearer token as header, they have full access via the content manager plugin API

**Steps to reproduce the problem**
Create a content type then add fields, after that use postman to create, update or delete the relevant content manager model url.

-------

Authenticated users can **CREATE UPDATE & DELETE**  in via **content manager plugin API**, yes I did pass an authorization bearer token as the header but there is no way out a user can be allowed to do such things.

Here it is

In the Roles & Permissions for authenticated user role - there is

![](https://i.imgur.com/LfFPGFb.png)

As you can see nothing is ticked for that particular role and the public one......... but out of curious I opened postman and just tried out to see what happens

and this happened 

![](https://i.imgur.com/0e4hHOD.png)

I was able to delete the data even though nothing is ticked for the permissions.

How is this happening ?

**Comment by derrickmehaffy** [comment]
@deeq14 please add in the required bug report template details. Template can be found here: https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

**Comment by derrickmehaffy** [comment]
@lauriejim @Aurelsicoko can you two test this, if true this could be a critical security hole

**Comment by deeq14** [comment]
@derrickmehaffy I did it.. I will also try this again on a new strapi and fresh environment to see if it will reproduce the critical problem.

**Comment by derrickmehaffy** [comment]
@deeq14 I poked Jim on slack and he couldn't reproduce it for GET, he didn't have time to test POST/PUT/DELETE.

**Comment by deeq14** [comment]
I will just close this as it seems the problem is caused by something on my end and I will investigate.

**Comment by Aurelsicoko** [comment]
@deeq14 Can you confirm that the Content-Manager's routes weren't opened for the public role?

**Comment by deeq14** [comment]
@Aurelsicoko Yes, there weren't open and somehow it was still possible to do CRUD.

but at the moment im using a new strapi I created few days ago, tested all endpoints with postman and works as expected.
