### ISSUE TITLE
GraphQL: SQL query generation error when using "where" conditions on a subset

### ISSUE THREAD

**Issue by Sigma-90** [strapi/strapi#2599]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MySQL 5.7.23
- **Operating system**: Windows 10 (dev) / Ubuntu 16.04 (prod)

**What is the current behavior?**
Using a "where" filter on a subset of a query does not get interpreted correctly and ultimately results in a broken SQL query (can't provide info on what happens with MongoDB, might be affected as well). Using "where" on the root set is fine, the issue seems to occur only when the "where" prop gets merged with a generated "where" condition that limits the selection to the id of a parent data record.

**Steps to reproduce the problem**
1. Create a strapi project with the graphql plugin installed
2. Create two content types, type A and type B, where type A has a one-to-many relation to type B
3. Create at least two entries for type A and at least four for type B, link the first half of the type B entries to entry 1 of type A and the other half to entry 2 of type A.
4. Open your playground and write a query that fetches all records of type A containing its sub-records of type B, but limit both the main set and its subset to those records where "id" is greater than 1.
Example:
```
query {
  categories(sort: "name:asc", where: { id_gt: 1 }) {
    id
    name
    entries(where: { id_gt: 1 }) {
      id
      name
    }
  }
}

```
5. Execute and observe the output. You will be informed that there is an error in the SQL syntax, because the generated query is broken. For the example code used above, the broken query listed in the error message will look like this:
``"select `entries`.* from `entries` where `category` = 1 and `id` = {\"symbol\":\">\",\"value\":1} limit 100``
The data will contain a list of "Category" records, but the "entries" property of each will have a value of null (not even an empty array, which would be the expected result for a collection type).

**What is the expected behavior?**
Following the code example above, there should be no error messages in the returned data set and it should contain a list of "Category" records (containing only one record unless more than two were created), each of which containing an array of "Entry" records (again, should also contain one record, unless more than two were linked to the parent "Category" record). Internally, the generated SQL query string for the "entries" subset for the first record of "categories" should look like this:
``"select `entries`.* from `entries` where `category` = 1 and `id` > 1 limit 100``

**Suggested solutions**
The root of the problem seems to be the merge operation of the implicit "where" condition that limits the sub-records to those belonging to the current parent in the loop and the explicitly defined one in the query. For some reason it seems to expect the second argument to be a number or string but of course the parser correctly recognized this as a custom condition and provides an object containing information about the type of comparison and the value to be compared. That object will therefore be simply put through a toString conversion and thus breaks the query. 
It seems pretty obvious, that instead of queueing up chains of what will likely look like this:
`field_name + ' = ' + data`
the operation to perform should be something along the lines of this instead:
``(typeof data === 'Object' ? `${field_name} ${data.symbol} ${data.value}` : `${field_name} = ${data}`)``
This is of course all hypothetical pseudo code and surely incomplete because it doesn't even account for more complex "where" clauses that would generate a join (to filter for example for all entries of which the name starts with the letter A), those fail as well and generate a bunch of "mixed.hasOwnProperty is not a function" error messages. 
I have no idea where the actual responsible piece of code might be located, I've been searching for it, but sadly to no avail.

**Comment by lauriejim** [comment]
This have been fixed in last version of Strapi
