### ISSUE TITLE
Strapi + Frontend Framework

### ISSUE THREAD

**Issue by brillout** [strapi/strapi#2602]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Focusing on being headless seems a sensible goal.

An additional goal could be to integrate Strapi with a frontend framework.
A user ends up needing writing a frontend and such integration would ease the user's life.

[Reframe](https://github.com/reframejs/reframe) is a frontend framework and has been designed from the ground up to be plugin based.

Integrating Strapi with Reframe would enable "full-stack" plugins.
That is, plugins that add functionally to both Strapi and Reframe.

For example authentication: currently, using auth with Strapi requires frontend work for the user.
Instead, a full-stack auth plugin could be a drop-in solution with zero work for the user.

Another example are custom CMS view components.
Let's say I'm building a portfolio website for an architect.
The architect wants a very specific design to showcase his projects,
and he wants to be able to add new projects without my help.
I would create a new CMS view component "project-view" so that the architect can add new projects via the Strapi admin interface.
This "project-view" component needs to be able to integrate to both Strapi and Reframe.
I believe such custom CMS view components to be important in the long run.

The ideal situation would be that Strapi and Reframe share the same plugin system.
With a single plugin marketplace.

If the user wants Strapi without Reframe, then the user only adds Strapi plugins.

If the user wants Reframe without Strapi, then the user only adds Reframe plugins.

If the user wants Strapi + Reframe, then the user adds both Strapi plugins and Reframe plugins.

The headless CMS goal remains.

**Comment by derrickmehaffy** [comment]
```
For example authentication: currently, using auth with Strapi requires frontend work for the user.
Instead, a full-stack auth plugin could be a drop-in solution with zero work for the user.
```

https://github.com/strapi/strapi-sdk-javascript
