### ISSUE TITLE
BadRequestError: request aborted 

### ISSUE THREAD

**Issue by reutopiaer** [strapi/strapi#2608]
**Informations**
- **Node.js version**:  v10.11.0
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.17
- **Database**:  Mongodb
- **Operating system**:  Windows
- **(Optional) Link to your Project**: 

**What is the current behavior?**

post request aborted when behind proxy

**Steps to reproduce the problem**
``` js
import proxy from 'koa-proxies'
app.use(proxy('/', {
    target: 'http://localhost:1337/',
    changeOrigin: true,
    logs: true
}))
```
``` bash
[2019-01-10T08:14:42.568Z] debug GET \auth\local\callback (107 ms)
{ BadRequestError: request aborted
    at IncomingMessage.onAborted (\Roaming\nvm\v10.11.0\node_modules\strapi\node_modules\raw-body\index.js:231:10)
    at IncomingMessage.emit (events.js:182:13)
    at abortIncoming (_http_server.js:444:9)
    at socketOnClose (_http_server.js:437:3)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:606:12)
  message: 'request aborted',
  code: 'ECONNABORTED',
  expected: 47,
  length: 47,
  received: 0,
  type: 'request.aborted' }
[2019-01-10T08:16:51.816Z] debug POST /auth/local (120040 ms)
````
**What is the expected behavior?**
Post request returns data as normal as get request.

**Suggested solutions**
GET  \auth\local\callback  run callback function at plugins/users-permissions/controllers/Auth.js line 15,
but Post  \auth\local not run callback function.

**Comment by derrickmehaffy** [comment]
@reutopiaer a few things:

1) Please always ensure you are testing on the latest version (v18)
2) Windows isn't support: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows
3) For proxying, I recommend you use an external applicaton such as Nginx or Apache.

**Comment by reutopiaer** [comment]
@derrickmehaffy thanks for your reply!
1. I have tried the latest version (v18), but still have problems.
2. I deploy my app to ubuntu server 18.04, but still have problems.
3.  I have tried Nginx, it's works 

May be caused by  koa-proxies, but  request aborted by strapi :(
