### ISSUE TITLE
Content ID generation

### ISSUE THREAD

**Issue by deeq14** [strapi/strapi#2610]
It seems strapi makes the id of the follow in order in some kind way and I will say that is not good for security purposes..

Imagine I have a game where users points will be stored, so each user relates to a particular one and can be updated by sending put request to /games/:_id... and so a malicious user can just change the last number/letter and send unintended put request...

Here is the example what I mean  

![](https://i.imgur.com/pO62q6Z.png)

You can see all those id's are similar in some cases and follow in order..

Is there a way to lock a particular ID to a particular user only? --- or a way the ID generation to be completely random and don't follow in order?

IF not it must be put for security reasons.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/50959226-af8a7680-147f-11e9-8fbf-e0237ab4f536.png)

**Comment by deeq14** [comment]
@derrickmehaffy yea but still they are look very close and one can just guess.. and because strapi doesn't have a way to lock a particular id for a user that can send put request

**Comment by deeq14** [comment]
just some other id's.. 

https://imgur.com/KlN16eM

now what is the difference only c instead of a and 13, 14

**Comment by derrickmehaffy** [comment]
@deeq14 again Strapi does not generate these IDs they are done via mongoose/mongo. And since strapi also supports bookshelf and relational databases, this is common.

**Comment by deeq14** [comment]
@derrickmehaffy If they don't generate them, then have a way to lock a particular ID to a particular user only.. so my point still stands though.

**Comment by derrickmehaffy** [comment]
@deeq14 data ownership is not a new suggestion :wink: https://portal.productboard.com/strapi/c/44-data-ownership

**Comment by derrickmehaffy** [comment]
I'm marking this request as closed as it is a duplicate of: https://github.com/strapi/strapi/issues/624

**Comment by pragone** [comment]
@deeq14  ... I'll add my 2 cents here:
- The fact that a few letters/digits change is not necessarily bad. I understand that you'd want more randomness, but look at it this way. Given an id you do know, try to guess another one. Give yourself 100 attempts or 1,000 and see if you can find another one. Again, the fact that just a few positions change does not mean that this provides little security.

In the meantime though, I'd suggest that you can lock it down by using a middleware: https://strapi.io/documentation/3.x.x/advanced/middlewares.html#structure
You could create a middleware that if the url patter matches, checks whether the authenticated user if matches the user id that is coming in the payload. If the answer is "no". Just throw an error.
Makes sense?
