### ISSUE TITLE
PluginHeader/ListPage layout issues with medium viewport

### ISSUE THREAD

**Issue by joshmorel** [strapi/strapi#2611]
**Informations**
- **Node.js version**: Docker quickstart (node:11.1.0-alpine)
- **NPM version**: Docker quickstart (node:11.1.0-alpine)
- **Strapi version**: Docker quickstart (strapi@3.0.0-alpha.16)
- **Database**: Docker quickstart (MongoDB)
- **Operating system**: Kubuntu 18.04, tested on both Firefox 64.0 (64-bit) and Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**What is the current behavior?**

In the content type admin page, when I vertically panel my browser the Add New X button is only clickable in the top part while also the bottom of filters menu is unexpectedly displayed.

**Steps to reproduce the problem**

Decrease the width of the viewport to Bootstrap medium:

![strapi-plugin-header-layout-issue](https://user-images.githubusercontent.com/10546720/50965679-ab228580-14a0-11e9-9abc-a92cc9939fb8.gif)

**What is the expected behavior?**

1. Can still click on the entire Add New X button
2. Do not see the bottom of the filters menu

**Suggested solutions**

Unsure - perhaps something to do with use of margins? Willing to take a stab although it might take some time.

**Comment by derrickmehaffy** [comment]
@joshmorel is known :stuck_out_tongue: https://portal.productboard.com/strapi/c/20-administration-responsive

**Comment by joshmorel** [comment]
Ah I see. So basically there is a larger issue around responsiveness. I guess you can close this one then.
