### ISSUE TITLE
Deep filter cannot work (A.B.C.name_contains)

### ISSUE THREAD

**Issue by Nowhy** [strapi/strapi#2613]
**Informations**
- **Node.js version**: v10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: " "^3.0.0-alpha.18"
- **Database**: "mongoose": "5.3.16",
- **Operating system**: Windows 10

**What is the current behavior?**
cannot deep filter...

**Steps to reproduce the problem**
I have a schema model like this
A has a list of properties and one of them is B.
B also has a lost of properties and one of them is C.
C has its "id", "name" and "code".
I need to find A through typing C's name(not full name).
Thus, I think it should be http://hereislink/A?B.C.name_contains="XXX"

However, Strapi cannot support this kind deep filter...
How to solve this kind of problem? Help!!!!

**What is the expected behavior?**
I need  http://hereislink/A?B.C.name_contains="XXX" can work

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Closing as this is a duplicate issue related to this PR: https://github.com/strapi/strapi/pull/2452
