### ISSUE TITLE
After selecting the database the strapi stops

### ISSUE THREAD

**Issue by WojciechKonieczny** [strapi/strapi#2614]
**Informations**
- **Node.js version**:  v10.15.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-aplpha.18
- **Database**: Mongo v4.0.5
- **Operating system**: Windows 7

**What is the current behavior?**
Hello, I'm newbie user of Strapi. I have a problem with creating a new project. After selecting my main database, strapi stops and does not ask for the rest of the information.
https://imgur.com/kNx1pzT

**Steps to reproduce the problem**
npm i strapi@alpha -g
strapi new my-project

**What is the expected behavior?**
How to repair it?

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @WojciechKonieczny !

It's because you are using windows.
Please check https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions to be able to fix the issue.
It will be fixed in next version of Strapi. A PR have been merge to fix that.
