### ISSUE TITLE
Delete entry with an Media relation error Parameter "obj" to Document()

### ISSUE THREAD

**Issue by jimnordb** [strapi/strapi#2619]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.18
- **Database**:  MongoDB 3.6.9
- **Operating system**:  Debian 9

**What is the current behavior?**
Issuing delete requests causes 500 internal error. but the entry gets deleted anyway. in a non-custom install. only some content types added

The delete request: /products/5c3a52af383fe663810f0abc

```
(node:613) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
{ ObjectParameterError: Parameter "obj" to Document() must be an object, got 5c3a995fc4859602655bfe33
    at new ObjectParameterError
```

**Steps to reproduce the problem**
setup insomina. create content type. issue delete request

**What is the expected behavior?**
No internal error

**Suggested solutions**
No idea atm.

**Comment by jimnordb** [comment]
Figured it was caused by relation

Products:
```
{
  "connection": "default",
  "collectionName": "products",
    "deliveries": {
      "collection": "deliveries",
      "via": "products"
    }
}
```
now gone.

in my Deliveries i had:
```
"products": {
      "model": "products",
      "via": "deliveries"
    },
```

now 

```
"products": {
      "model": "products"
},
```

**Comment by kalms** [comment]
Hi @lauriejim 

We're also experiencing it. The issue appeared suddenly when calling the `/contenttype/:_id` with a `DELETE` request, hitting the remove() service.

`  /**
   * Promise to remove a/an workshop.
   *
   * @return {Promise}
   */

  remove: async params => {
    // Select field to populate.
    const populate = Workshop.associations
      .filter(ast => ast.autoPopulate !== false)
      .map(ast => ast.alias)
      .join(' ');

    // Note: To get the full response of Mongo, use the `remove()` method
    // or add spent the parameter `{ passRawResult: true }` as second argument.
    const data = await Workshop
      .findOneAndRemove(params, {})
      .populate(populate);

    if (!data) {
      return data;
    }

    await Promise.all(
      Workshop.associations.map(async association => {
        if (!association.via || !data._id) {
          return true;
        }

        const search = _.endsWith(association.nature, 'One') || association.nature === 'oneToMany' ? { [association.via]: data._id } : { [association.via]: { $in: [data._id] } };
        const update = _.endsWith(association.nature, 'One') || association.nature === 'oneToMany' ? { [association.via]: null } : { $pull: { [association.via]: data._id } };

        // Retrieve model.
        const model = association.plugin ?
          strapi.plugins[association.plugin].models[association.model || association.collection] :
          strapi.models[association.model || association.collection];

        return model.update(search, update, { multi: true });
      })
    );`

The error appears to be during the final promise to update the different relations. It's consistent when there's a relation, so it's not specific to a content type.

**Comment by kalms** [comment]
Added note: We just update to alpha-18 from 16, to see if that would fix it, but didn't happen.

**Comment by kalms** [comment]
Another observation: When calling the endpoint, I get this output and complete error message in console:

`(node:44198) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
warning.js:18
ObjectParameterError {message: "Parameter "obj" to Document() must be an object, g…", name: "ObjectParameterError", stack: "ObjectParameterError: Parameter "obj" to Document(…"}`

Can it be related to the deprecated method that is being called?

**Comment by lauriejim** [comment]
Hi @kalms thank your for these detail! I will have to make some investigations.

**Comment by ggarcia92** [comment]
Hi @lauriejim I am having the same issue that @kalms . I already update to alpha.21. To reproduce the error this is my model:

```js
{
  "connection": "default",
  "collectionName": "configuration",
  "info": {
    "name": "configuration",
    "description": "Description"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "logo": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "tooltip": {
      "default": "",
      "type": "string",
      "required": true
    },
    "background": {
      "default": "",
      "type": "string",
      "required": true
    },
    "order": {
      "default": 1,
      "type": "integer",
      "required": true
    },
    "visible": {
      "default": false,
      "type": "boolean",
      "required": true
    }
  }
}
```
Regards

**Comment by lauriejim** [comment]
Okay good. Similar with https://github.com/strapi/strapi/issues/2731

**Comment by naeluh** [comment]
I am also having the same issue with v25 

  message:
   'Parameter "obj" to Document() must be an object, got 5ca7c0dbf1f6161244053fe3',
  name: 'ObjectParameterError' }

**Comment by lauriejim** [comment]
All works fine in the last version of Strapi `alpha.26`
