### ISSUE TITLE
Duplicated relations in relation dropdown

### ISSUE THREAD

**Issue by jhfgloria** [strapi/strapi#2622]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.18
- **Database**: PostgreSQL
- **Operating system**: MacOS High Sierra 10.13.6

**What is the current behavior?**
When adding new items to a relation, the select component (UI) presents duplicates. This happens if I click the select dropdown twice (the first time says there are no more items, but the second time it shows an already selected item). This is a many-to-many relation.
I recorded the problem:
[relations_bug.zip](https://github.com/strapi/strapi/files/2753293/relations_bug.zip)

**Steps to reproduce the problem**

1. Create a simple model with no relations
2. Create a second model with many-to-many relations with the previous model
3. Create a record of the first type of model
4. Create a record of the second type of model and add the previous record as a relation (don't save yet)
5. Click the select dropdown once: it says "No results found" as it should.
6. Click the select dropdown again: it shows the first record erroneously.

**What is the expected behavior?**
The second click should say "No results found"

**Suggested solutions**
I've not looked into the code yet, because I'm still testing Strapi in a spike to assert if it is the best option for a project of a client of mine. So far, nice job guys 👍 🚀

**Comment by lauriejim** [comment]
It looks happen when the dropbox is empty.
