### ISSUE TITLE
Need some help update (fetch all schemas endpoint)

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2624]
Hi guys,
I need to get schemas from REST api. I think it's an undocumented feature that now exist in core because I see that documentation plugin display schemas now and also admin dashboard display it too. Is it possible to fetch all schemas through REST? Which endpoint?
I can't find any docs about this.

![schemas](https://user-images.githubusercontent.com/25859075/51099701-910ddd80-17e7-11e9-8b83-dd2095a116f2.png)

**Comment by derrickmehaffy** [comment]
@mnlbox the schemas are just built off your model.settings.json file, it is specific to the OpenAPI/Swagger spec

You can't grab those via REST right now.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/51099817-1fef0b80-1790-11e9-8b60-a30227f5cc1f.png)

Example from one of mine

**Comment by soupette** [comment]
There should be an endPoint in the content type builder that allows you to retrieve one model schema.
Or you can create one in the documentation plugin that retrieves all the components from your `documentation.json` file
