### ISSUE TITLE
File size sorting by numeric order rather than actual file size

### ISSUE THREAD

**Issue by suttonmay** [strapi/strapi#2625]
<img width="1380" alt="screen shot 2019-01-14 at 8 47 49 pm" src="https://user-images.githubusercontent.com/11130449/51157843-f3de9380-183e-11e9-8875-5f5e10b18683.png">

**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.18
- **Database**: MongoDB
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
When sorting your uploaded files by the Size, it is sorting by numerical value, rather than actual file size.

i.e. When sorting by ascending order,  a filesize of 80kb will be sorted higher than a file of 4mb (see screenshot)

**Steps to reproduce the problem**
Upload multiple file sizes such as 4mb --> 80kb --> 150 kb. The sort order would be 150kb --> 4mb --> 80kb

**What is the expected behavior?**
Should sort by the actual file size, so the largest file is at the end of the list.

**Suggested solutions**
You could sort by the value rather than the size. 
`
const { divider, unit } = this.getUnit(item[value]);
                const size = item[value]/divider;
`
pass the value along with the size, display the size but sort by value.

**Comment by lauriejim** [comment]
Hello @suttonmay , thank you for reporting this issue.
Can you please submit a PR to fix it.
Will appreciate your contribution!
