### ISSUE TITLE
GraphQL query "me" get related content

### ISSUE THREAD

**Issue by deeq14** [strapi/strapi#2627]
**What is the current behavior?**
I am using GraphQL plugin and the query 'me' doesn't have for example a related content by the user, just the basics, id, username, email e.t.c..

for example I have to do this way, 

```
query {
  user(id: "5c38667108f3c10d9fe2981f") {
    articles {
      posts
    }
  }
}
```
which means I have to allow a user to access /user:_id which also exposes that the user can get other users content! 

**Steps to reproduce the problem**
Create a content add a field and relation to a user and do a query "me" with the related content

**Suggested solutions**
It will be nice to have a way we can do this

```
query {
  me {
    articles {
      posts
    }
  }
}
```

which means a user has access to only his/her content.

**Comment by Aurelsicoko** [comment]
@deeq14 Thank you for raising this issue! Do you have time to implement it? We'll be happy to merge it to the codebase 👍

**Comment by deeq14** [comment]
@Aurelsicoko Unfortunately I am just a beginner/intermediate in js and lack of skills may hinder.. but I will try 👍

**Comment by lauriejim** [comment]
@Aurelsicoko the me Query exist but the topic is about related data of the user.

**Comment by deeq14** [comment]
@Aurelsicoko I meant to actually get the related content of the user, like lauriejim said.

**Comment by Aurelsicoko** [comment]
Okay, I got it! If you want to be able to retrieve a relational field through the query `me`, you have to change this line https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/schema.graphql#L25. Instead of returning `UsersPermissionsMe`, you need to change this line by `UsersPermissionsUser`.

**Comment by yareyaredesuyo** [comment]
I had the same issue before, so I changed UserPermissionsMe config file's scheme directly.  And it worked.

Edit like this 

```
    type UsersPermissionsMe {
      _id: ID!
      username: String!
      email: String!
      confirmed: Boolean
      blocked: Boolean
      role: UsersPermissionsMeRole
      description: String  // <- add this line (change what you want to add from User scheme. )
    }
```

But this issue is maybe not documented. 

So, the answer is maybe... 

1. Add document about how to change UserPermissionsMe scheme.
2. Allow user to edit UsersPermissionsMe from admin panel.

**Comment by Aurelsicoko** [comment]
The `UsersPermissionMe` isn't a model and it's only available when you're using GraphQL. So, option 1 is the only option we have.

@yareyaredesuyo can you make a PR and update the documentation, please? Thank you :)

**Comment by miguelangeltorresfp** [comment]
@Aurelsicoko , is there any way to do it through the ./extension/users-permissions/config folder?
I mean, it works, but I prefer not to modify packages ( plugins ) directly.

**Comment by alexandrebodin** [comment]
@miguelangeltorresfp you can add a schema.graphql file in the `extensions` ;)

**Comment by morganwm** [comment]
fyi, I ran into this issue with Strapi 3.0.0-beta.16.7. When I attempted to apply the fix referenced by @Aurelsicoko by adding a `schema.graphql` file to `extensions/users-permissions/config` I ran into error messages from Strapi

```
[2019-10-02T20:00:59.614Z] error Error: There can be only one type named "UsersPermissionsMe".
Field "UsersPermissionsMe.id" can only be defined once.
Field "UsersPermissionsMe.username" can only be defined once.
Field "UsersPermissionsMe.email" can only be defined once.
Field "UsersPermissionsMe.confirmed" can only be defined once.
Field "UsersPermissionsMe.blocked" can only be defined once.
Field "UsersPermissionsMe.role" can only be defined once.

There can be only one type named "UsersPermissionsMeRole".
Field "UsersPermissionsMeRole.id" can only be defined once.
Field "UsersPermissionsMeRole.name" can only be defined once.
Field "UsersPermissionsMeRole.description" can only be defined once.
Field "UsersPermissionsMeRole.type" can only be defined once.

Field "Query.me" can only be defined once.
    at assertValidSDL (/Users/mwmorris/git/lnd-strapi/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/Users/mwmorris/git/lnd-strapi/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/mwmorris/git/lnd-strapi/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (/Users/mwmorris/git/lnd-strapi/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/mwmorris/git/lnd-strapi/node_modules/strapi-plugin-graphql/services/Schema.js:300:22)
    at Object.initialize (/Users/mwmorris/git/lnd-strapi/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at /Users/mwmorris/git/lnd-strapi/node_modules/strapi/lib/hooks/index.js:43:28
```

I believe this is due to some error with how Strapi handles the process of merging or replacing files with ones provided by the developer, possibly relating to `.graphql` extension files.

My fix for this was to create a new root type `self` that could be set as type `UsersPermissionsUser`.

```
// extensions/users-permissions/config/schema.graphql
module.exports = {
    query: `
        self: UsersPermissionsUser
    `,
    resolver: {
        Query: {
            self: {
                resolverOf: 'User.me',
                resolver: {
                    plugin: 'users-permissions',
                    handler: 'User.me',
                },
            },
        },
    }
};
```

This custom definition leverages the existing `User.me` resolver while simply providing a new type off of the root that has any relations your `User` type has, for example:

```
query {
  self {
    articles {
      posts
    }
  }
}
```

Hope this helps.

**Comment by lauriejim** [comment]
A add some context about the security issue that can happen if you set `UsersPermissionsUser`
You will be able to get `Me > Group > Users` all the users base of a group.

**Comment by damtsnkff** [comment]
I'm not using GraphQL, but in case it helps anyone, here's what I did:

In `extensions/users-permissions/controllers/User.js` (file that I created to "override" some methods and add my own)

_At the top of the file_
``` javascript
// [At the top of the file]
const { sanitizeEntity } = require('strapi-utils');
const sanitizeUser = user => sanitizeEntity(user, {
  model: strapi.query('user', 'users-permissions').model,
});

// ... [All your other methods, like "findOneByUsername" etc..]

/**
  * Retrieve authenticated user and fetch its first related model (no deep models).
  * @return {Object|Array}
  */
async me(ctx) {
  const user = ctx.state.user;

  if (!user) {
    return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
  }

  let data = await strapi.plugins['users-permissions'].services.user.fetch({
    id: user.id,
  });

  if (data) {
    data = sanitizeUser(data);
  }

  ctx.send(data);
},
```

Note that it'll work with the first related model only. Example:
```
user: {
  posts: [
    title: '...'
    tags: [...]  <-- won't fetch "deep" models and will retrieve only the ids of each elements.
  ]
}
```

**Comment by ssuvorov** [comment]
```
// extensions/users-permissions/config/schema.graphql.js
module.exports = {
  definition: `
    extend type UsersPermissionsMe {
      user: UsersPermissionsUser
    }
  `,
  resolver: {
    UsersPermissionsMe: {
      user: user => user
    },
  },
}
```

```gql
// e.g.
{ 
me  
  {
     user {
       last_name
    }
  }
}

**Comment by shih-js** [comment]
Thanks @ssuvorov, this solution worked brilliantly for me, but I wonder if there are any security implications 🤔

**Comment by ssuvorov** [comment]
@shih-js not sure. Better to ask Strapi devs. But I guess it's similar to the case when you would request User. A token has to be provided.

**Comment by derrickmehaffy** [comment]
Going to close this one, as by default we don't populate relations for REST or GraphQL, user modification is required on both.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/extend-user-permissions-graphql-schema/995/3

**Comment by benderillo** [comment]
The solution provided by @ssuvorov needs to be updated now. This is what worked for me:
```
module.exports = {
  query: `
        self: UsersPermissionsUser!
    `,
  resolver: {
    Query: {
      self: {
        resolverOf: 'plugins::users-permissions.user.me',
        resolver: 'plugins::users-permissions.user.me',
      },
    },
  },
};
```
Shame that this still has to be worked around with a plugin extension. One would expect that the `ME` query would return custom fields defined for a User model not just a statically defined (i.e. hardcoded) set of data.

**Comment by VishSinha** [comment]
> ```
> // extensions/users-permissions/config/schema.graphql.js
> module.exports = {
>   definition: `
>     extend type UsersPermissionsMe {
>       user: UsersPermissionsUser
>     }
>   `,
>   resolver: {
>     UsersPermissionsMe: {
>       user: user => user
>     },
>   },
> }
> ```
> 
> ```graphql
> // e.g.
> { 
> me  
>   {
>      user {
>        last_name
>     }
>   }
> }
> ```
> 
> "strapi": "^3.1.4",

Thank you. You helped me to extend the user for me query.

**Comment by nguyenchan** [comment]
Hi there, I got the same problem, I add a relation 1-1 to the user model, it works  in development mode but when I build production the extended part seems like it doesn't exist, and the admin panel got this err
<img width="1442" alt="Screen Shot 2021-07-25 at 01 18 08" src="https://user-images.githubusercontent.com/25972697/126877837-43752b4a-c05e-4644-ae23-3ea4830c4ee7.png">

When switching back to development mode it works again.
does anyone have this issue?

**Comment by nguyenchan** [comment]
> > ```
> > // extensions/users-permissions/config/schema.graphql.js
> > module.exports = {
> >   definition: `
> >     extend type UsersPermissionsMe {
> >       user: UsersPermissionsUser
> >     }
> >   `,
> >   resolver: {
> >     UsersPermissionsMe: {
> >       user: user => user
> >     },
> >   },
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```graphql
> > // e.g.
> > { 
> > me  
> >   {
> >      user {
> >        last_name
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > "strapi": "^3.1.4",
> 
> Thank you. You helped me to extend the user for me query.

Does it work in production?

**Comment by JMartinCollins** [comment]
Strapi Version 3.6.6

```
// extensions/users-permissions/config/schema.graphql.js
module.exports = {
  definition: `
    extend type UsersPermissionsMe {
      user_profile: UserProfile
    }
  `,
  resolver: {
    UsersPermissionsMe: {
      user_profile: async (obj, options, context) => {
        if (typeof obj.user_profile === 'number') {
          return await strapi.services['user-profile'].findOne({ id: obj.user_profile });
        } else if (typeof obj.user_profile === 'object') {
          return obj.user_profile
        }
      }
    },
  }
}
```
This was my rather sophomoric approach to getting this to work in a more recent version of Strapi.
One thing that I noticed when doing a `login` mutation is that the `obj` object which is passed to the resolver function already contains the `user_profile` object with the related fields, while the `me` query `obj` object has a key with the id of the related collection item, i.e.
```
//me query obj
{ ...
user_profile: 15,
...}

//login mutation obj
{ ...
user_profile {
    field1: value
    field2: value
}
... }
```
It's for this reason that there's a check for the type of the `obj.user_profile` value.
I suppose that this data is included in the `login` mutation after providing simply the `extend type UsersPermissionsMe`, whereas for you to be able to request the fields in the `me` query you'll have to perform the `findOne` action on the userProfile field.

Anyway, this way it ensures that you can define the gql query for me in a similar structure as you would for querying a `user`, without having to further nest into a self or user object.  

I think that this is a fairly common use case for the product and if the mods could provide some more information on how to make a more robust and secure solution the community would greatly appreciate, as it's been requested for a number of years in this thread as well as https://github.com/strapi/strapi/issues/4878

**Comment by thigrush** [comment]
thank you @ssuvorov, your solution worked for me.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-cant-access-custom-fields-from-users-me-via-graphql/13744/1
