### ISSUE TITLE
Documentation not detect server port (only works with 1337)

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2635]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MongoDB
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I change my Strapi server port in `config/environment/development/server.json` file from 1337 to 8888 but documentation plugin still want to use 1337 because of that endpoint `Execute` break.

**Steps to reproduce the problem**
* Change server port.
* Go to documentation page.
* Try to login or call any other endpoint

**What is the expected behavior?**
Read server port in documentation from config files.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Marking this as closed as @lauriejim is correct, you need to manually override the location in settings.json. You can see an example of this on my project: https://github.com/canonn-science/CAPIv2-Strapi/blob/7a17e97ed8ff46d9cc6f1b9e0064e572bcf71b8b/plugins/documentation/config/settings.json#L22-L39
