### ISSUE TITLE
Allow search Users in the API

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2639]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

With https://github.com/strapi/strapi/pull/1520 we add a new query filter for the generated API, but the User model from the `users-permissions` plugin does not have it.

**Comment by projik** [comment]
You can search for users by username and email on the following API path:

/users-permissions/search/[search-term]

It returns an array of users that match.

Were you looking for something more from the user search?

**Comment by abdonrd** [comment]
@projik I mean the same as: https://github.com/strapi/strapi/pull/1520#issue-199412384

**Comment by Aurelsicoko** [comment]
@abdonrd Will you have time to implement it?

**Comment by abdonrd** [comment]
@Aurelsicoko starting at #2685!

**Comment by abdonrd** [comment]
This is fixed in beta?

**Comment by lauriejim** [comment]
Yap absolutely. We can close this issue.
Thank you @abdonrd for the suggestion of this feature.
