### ISSUE TITLE
Content-manager and user-permissions plugin params are different

### ISSUE THREAD

**Issue by projik** [strapi/strapi#2641]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0 alpha 18
- **Database**: Postrges
- **Operating system**: Linux/Mac
- **(Optional) Link to your Project**: 

**What is the current behavior?**
This is related to issue #2631 and PR #2632 

The content-manager routes us the parameter name id in updates to plugin data. 
The user-permissions routes to update a user record uses _id as the route parameter. 

The update function in the Users controller receives a different parameter depending on whether the update is made in the admin portal or from an API.

In the user update function it performs a check to make sure that the email address is not already in the database

**Steps to reproduce the problem**
Update a user record using the Admin portal.

Try updating the same user record, but this time using an API call

**What is the expected behavior?**

The user record should be updated in the same way in the Admin portal and via an API call.

**Suggested solutions**

I have submitted a PR that fixes this issue

**Comment by lauriejim** [comment]
Thank you @projik !
I will take a look soon as possible.
