### ISSUE TITLE
Relational fields only show first 4 items

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2643]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MongoDB
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I add 5 child (relational field) but it's just show first 4 item. See below image for more info.
![relational feild](https://user-images.githubusercontent.com/25859075/51299742-b7798600-1a3e-11e9-8950-bf476d146a4b.png)

**Steps to reproduce the problem**
Create simple content type called `category` with just single `title` attribute. Create a self reference relation for this content type.
Category [parent] has many (sub)category [child].
Then add some data and relation. (more than 4 item)

**What is the expected behavior?**
Have a `see more` button and can show all relation item after click that button.

**Suggested solutions**

**Comment by henrych4** [comment]
You should be able to view all items by scrolling down. Correct me if I am wrong.

**Comment by mnlbox** [comment]
@henrych4  No page not have any scroll for this.

**Comment by lauriejim** [comment]
Hello! Yap there is a scroll here!
On your screen shot we can see the border shadow on the bottom of the list.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.
