### ISSUE TITLE
Non required JSON fields

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2644]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MongoDB
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
JSON fields must be contain `{}` content if we don't mark JSON field as `required` otherwise we need add a `{}` manually to prevent form error and submit data.
![json default value error](https://user-images.githubusercontent.com/25859075/51300926-b8acb200-1a42-11e9-8553-d10c4c95a705.png)

![json defaul value](https://user-images.githubusercontent.com/25859075/51300792-5b186580-1a42-11e9-8ea8-31da81f66574.png)

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@mnlbox send an empty array `{}` this is known about.

**Comment by mnlbox** [comment]
Yes but when I don't check `required` in content type builder then I don't want add any data manually. (because I have 10 JSON field in this content type and If we force add `{}` for all of them It's kill my time)
What is the different between required and non-required JSON field if we need enter some data for both of them? :thinking: 

@derrickmehaffy I think it's a UI bug and we need fix this for this content-type :wink:

**Comment by lauriejim** [comment]
Here we decide about that - https://github.com/strapi/strapi/issues/1989

And it's what is happen, you don't have to set manually `{}`. When you create an entry it's automatically set to `{}`.

I just tested it and it works well.

**Comment by mnlbox** [comment]
@suhaboncukcu It will be fix after merge @soupette update on JSON input.
I think it's better to close after complete fix.
@lauriejim It's still not working in my side I think we need some fix base on @soupette change. :wink:

**Comment by soupette** [comment]
@mnlbox I haven't submitted the PR yet I'm still thinking on what should be the correct implementation for this.

I have noticed that when you create a JSON field that is required with the content-type-builder it sets the `default` key as an empty string in your `model.settings.json` which I think is incorrect.

So, in order to solve this issue I think that the default value should be an empty object when the required option is selected and null in the other case.

This way we won't have to make any update in the content-manager.

**Comment by abdonrd** [comment]
Any news on this?

**Comment by MartinN3** [comment]
@soupette JSON is valid with string, array, object as default... What thinking goes behind enforcing empty object then. 

But of course, its json so no one in code can really depend on type set defaultly - on this argument default value by itself doesn't matter that much to me.

Maybe ppl what people want is to set default and enforce JSON type validation on first level.

**Comment by soupette** [comment]
@MartinN3 I agree the required option on the json field kind of seems odd, if think the only thing that needs to be checked is that the `JSON` format is valid
