### ISSUE TITLE
Filter add and remove button not vertically align

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#2645]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MongoDB
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Filter add and remove button not vertically align. See below image:
![filter buttons align](https://user-images.githubusercontent.com/25859075/51301591-0c1fff80-1a45-11e9-89fb-7e573ab22975.png)

**Steps to reproduce the problem**
I'm using Firefox and my add/remove buttons not align vertically.

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
We will not work on that point for now. So if you want this fix, feel free to open a PR.

**Comment by mnlbox** [comment]
@lauriejim Please mark this as ` Good for new contributors` and reopen.
