### ISSUE TITLE
Strapi with MySQL: Error: ER_TOO_MUCH_AUTO_TIMESTAMP_COLS

### ISSUE THREAD

**Issue by ArthurKnoep** [strapi/strapi#2647]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.19
- **Database**: MySQL
- **MySQL version**: 5.5.60
- **Operating system**: Debian 8

**What is the current behavior?**
I am not able to start any new strapi project configured with mysql. On each attempt to `strapi start`, I get this error: 
```
UnhandledPromiseRejectionWarning: Error: ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```
Here is a complete startup log (with debug on): https://pastebin.com/Xh5tCWkW

**Steps to reproduce the problem**
```bash
strapi new test    # Make sure to configure it with a mysql db
cd test
strapi start
```

**What is the expected behavior?**
Start the server :smile:

**Comment by lauriejim** [comment]
Hello @ArthurKnoep ! Thank you to report this issue.
I'm not a MySQL expert but I thing some one can help you in the community.

**Comment by suhaboncukcu** [comment]
Hi @ArthurKnoep, It's because timestamp definitions have difference between MySQL 5.5 and higher versions. [Strapi supports Mysql versions >= 5.6](https://strapi.io/documentation/3.x.x/getting-started/installation.html). 

You can check the related query works on 5.6 and not on 5.5 [here](https://www.db-fiddle.com/f/fLhCtfRnSXdprNx5S6XaMc/0)

**Comment by ArthurKnoep** [comment]
Hi @suhaboncukcu,

Thank you for your answer, I will try

**Comment by ArthurKnoep** [comment]
Hi,

Thanks again for you help, the problem seems fixed

**Comment by lauriejim** [comment]
Thank you @suhaboncukcu for your help in the issue!

**Comment by ibjorn** [comment]
If I am unable to upgrade MySQL, how and where can I alter this:

` 'created_at' timestamp DEFAULT CURRENT_TIMESTAMP,
    'updated_at' timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`

Or is there some other workaround by any chance?

**Comment by derrickmehaffy** [comment]
@ibjorn would probably be better to open a discussion than to post on a year old closed issue.
