### ISSUE TITLE
alpha@6 - Port field 

### ISSUE THREAD

**Issue by rogueSF** [strapi/strapi#265]
Just an FYI, The Port field appears to limit input to just numbers, however, the character 'e' is allowed! 

![screen shot 2017-10-04 at 1 59 46 pm](https://user-images.githubusercontent.com/3733218/31199582-b1e5c126-a90c-11e7-84c5-bf144c44597d.png)

**Node.js version**: 8.6
**npm version**: 5.4.2
**Strapi version**: alpha@6
**Operating system**: os x 10.11

**Comment by soupette** [comment]
Hi thanks for notifying us!
The input type number accepts floating points numbers including negative symbols and the `e` or `E` character.

If you try to submit your form with the same inputs as the screenshot it should display an error on the `Port`field.

**Comment by soupette** [comment]
I'll close the issue, feel free to reopen it
