### ISSUE TITLE
strapi start not working

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [strapi/strapi#2654]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.19
- **Database**: mongodb
- **Operating system**: macOS

**What is the current behavior?**

`strapi start` fails, I guess because of the "userspermissions" plugin.

```js
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/benjamin/remove me/strapi/test/plugins/users-permissions/config/functions/bootstrap.js:167:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

the following line is this one failing, as `services` seems to be undefined:

```js
strapi.plugins['users-permissions'].services.userspermissions.initialize(cb);
```

Due to this, the page is not served.

**Steps to reproduce the problem**

```sh
strapi new my-project
cd my-project
# npm install is required here as some deps are missing, like lodash
strapi start
```

**What is the expected behavior?**

No error, and thus, the dashboard to be up and running

**Comment by rdbmax** [comment]
Maybe related,
Error when i try to create an app, when strapi install plugins `users-permissions` and `upload`:

```
⚠ An error occurred during users-permissions plugin installation.
{ Error: Command failed: node /Users/[******]/.config/yarn/global/node_modules/strapi/bin/strapi.js install users-permissions
- Install users-permissions plugin
✖ An error occurred during plugin installation.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/[******]/.config/yarn/global/node_modules/strapi/bin/strapi.js install users-permissions ' }
```

```
⚠ An error occurred during upload plugin installation.
{ Error: Command failed: node /Users/[******]/.config/yarn/global/node_modules/strapi/bin/strapi.js install upload
- Install upload plugin
✖ An error occurred during plugin installation.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node /Users/[******]/.config/yarn/global/node_modules/strapi/bin/strapi.js install upload ' }
```

**Comment by derrickmehaffy** [comment]
@rdbmax https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#yarn

**Comment by lauriejim** [comment]
@BenjaminVanRyseghem Sorry for the delay.

Can you try with new install of the last version of Strapi and a clean collection.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by bencehusi** [comment]
I have the same issue when trying to connect to a mLab mongodb instance.
Everything worked just fine on an other project with local mongodb.

My setup is exactly as described in [strapi blog](https://blog.strapi.io/using-mlab-with-strapi/). The database connection seems to work since the initial schemas are created, however user-permission documents seem to be empty - not sure if that's a problem though.

<img width="1137" alt="screenshot 2019-02-16 14 14 10" src="https://user-images.githubusercontent.com/10700975/52900409-acf50c80-31f5-11e9-88dd-e0aca76364b4.png">

**Comment by lauriejim** [comment]
@bencehusi what is the version of Strapi you use please ?
Did you have an error log or something that can help us to understand your issue.

**Comment by n3n** [comment]
I have the same issue.

* **Node.js version**: 10.15.0
* **NPM version**: 6.4.1
* **Strapi version**: 3.0.0-alpha.24.1
* **Database**: sqlite
* **Operating system**: macOS

```
(node:73207) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/n3n/Workspace/strapi-demo/plugins/users-permissions/config/functions/bootstrap.js:167:48)
(node:73207) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:73207) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-19T16:58:10.823Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-02-19T16:58:10.825Z] warn Perhaps you forgot to call it?
```

**Comment by bencehusi** [comment]
Thank you @lauriejim getting back on this.
I've used the strapi CLI and regarding my package JSON the strapi version is:
"strapi": "3.0.0-alpha.23.1",
"strapi-hook-mongoose": "3.0.0-alpha.23.1"

This is all I get:
```
(node:17589) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/bencehusi/DEV/strapi/plugins/users-permissions/config/functions/bootstrap.js:167:48)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:17589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17589) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-19T17:14:23.089Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-02-19T17:14:23.090Z] warn Perhaps you forgot to call it?

```
And mongodb log seems to be fine as every line states "[listener] connection accepted..." and "[conn4] Successfully authenticated as principal..."

I've also tried to turn on debugging in database.json but there's nothing to see.

* **Node.js version**: 11.10.0
* **NPM version**: 6.7.0
* **Strapi version**: 3.0.0-alpha.23.1 ==> **I've also tried 24.1, but no luck**
* **Database**: mongodb
* **Operating system**: macOS

**Comment by n3n** [comment]
@bencehusi Can you try on **npm**?

**Comment by bencehusi** [comment]
@n3n npm

**Comment by BenjaminVanRyseghem** [comment]
I lost interest in this project, so I bail out

**Comment by elv1n** [comment]
I had the same issue when strapi installed with yarn global. When I installed with npm it starts working

**Comment by angad777** [comment]
I can't bootstrap and start a fresh strapi install.

`➜  strapisandbox strapi new strapisandbox
🚀 Start creating your Strapi application.

? Choose your installation type Quickstart (rec
ommended)

✅ Connected to the database

🏗  Application generation:
✔ Copy dashboard
⚠ An error occurred during settings-manager plugin installation.
- Install settings-manager plugin
✖ An error occurred during plugin installation.

✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
- Install users-permissions plugin
✖ An error occurred during plugin installation.

✔ Install plugin email.
⚠ An error occurred during upload plugin installation.
- Install upload plugin
✖ An error occurred during plugin installation.

✔ Link strapi dependency to the project.

👌 Your new application strapisandbox is ready at /Users/Angad/Desktop/Developer/strapisandbox/strapisandbox.

⚡️ Change directory:
$ cd strapisandbox

⚡️ Start application:
$ strapi start

(node:2124) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/Angad/Desktop/Developer/strapisandbox/strapisandbox/plugins/users-permissions/config/functions/bootstrap.js:167:48)
(node:2124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-13T02:07:15.285Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-03-13T02:07:15.285Z] warn Perhaps you forgot to call it?

`

**Comment by lauriejim** [comment]
Please can you uninstall Strapi globally and install the last version (alpha.24.1)

**Comment by angad777** [comment]
Thank You :)

**Comment by TotomInc** [comment]
I installed the latest version of Strapi (3.0.0-alpha.25.2) globally with Yarn (1.15.2) and after creating a quickstart project I have the same issue (Node 10.15.0):

```js
➜ node server.js
(node:7092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
	at module.exports (/Users/totominc/Desktop/Git/strapi/cms/plugins/users-permissions/config/functions/bootstrap.js:167:48)
```

@lauriejim, please re-open issue for Yarn users.

**Comment by lauriejim** [comment]
Please check our wiki. We did non support Yarn for now.

**Comment by fcpauldiaz** [comment]
You still don't support yarn?

**Comment by derrickmehaffy** [comment]
@fcpauldiaz Yarn is supported and recommended but you will need to be running the beta version.

**Comment by JuanGrauGGG** [comment]
Same here in latest alpha version 3.0.0-alpha.26.2
Creating a project from scratch with mongodb (initial cnn check is passing)
`strapi start
(node:66402) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:66402) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'userspermissions' of undefined
    at module.exports (/Users/juangg/devel/gigigo/workshop/strapi/cms/plugins/users-permissions/config/functions/bootstrap.js:167:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:66402) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:66402) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-10-11T12:36:01.407Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-10-11T12:36:01.408Z] warn Perhaps you forgot to call it?
`

**Comment by Thawzino** [comment]
How can i uninstall global strapi and local strapi
