### ISSUE TITLE
Strapi Documentation Plugin Host Incorrect

### ISSUE THREAD

**Issue by sskhokhar** [strapi/strapi#2656]
**Informations**
- **Node.js version**: 11.6.0
- **NPM version**: 6.5.0-next.0
- **Strapi version**: 3.0.0-alpha.19
- **Database**: 
- **Operating system**: Ubuntu
- **(Optional) Link to your Project**: 

**What is the current behavior?**
The documentation plugin sends request to incorrect URL on server.

![capture](https://user-images.githubusercontent.com/13753852/51426741-ba2bd500-1c10-11e9-9fde-67899414d904.PNG)

**Steps to reproduce the problem**

**What is the expected behavior?**

The URL must be of the server where strapi is hosted.

**Suggested solutions**

**Comment by soupette** [comment]
@sskhokhar this is not a bug, you need to set your hosts in the plugin's settings file.
You can refer to the [documentation](https://strapi.io/documentation/3.x.x/guides/api-documentation.html#basic-configurations) or the [article](https://blog.strapi.io/api-documentation-plugin/) if you need more informations about this plugin.
