### ISSUE TITLE
Strapi won't install via yarn due to koa-ssl requiring iojs 1.2.0

### ISSUE THREAD

**Issue by joeyfigaro** [strapi/strapi#266]
**Node.js version**:
`8.4.0`
**npm version**:
`5.3.0`, but I use yarn
**Strapi version**:
`N/A`
**Operating system**:
`OS X 10.12.6`

![](http://joeysharesthings.com/34403m3Y2J3L/Image%202017-10-05%20at%2011.24.36%20AM.public.png)

Strapi won't install via yarn due to `koa-ssl` requiring iojs `1.2.0`.

[Relevant ticket from their repo](https://github.com/jclem/koa-ssl/issues/1)

### Suggestion
Add instructions to installation docs for yarn that details how to bypass this issue:
`yarn global add strapi --ignore-engines`

**Comment by Aurelsicoko** [comment]
We removed this middleware a few weeks ago so it should not be an issue anymore. Thanks 👍
