### ISSUE TITLE
Changes for Google auth provider

### ISSUE THREAD

**Issue by nicksp** [strapi/strapi#2660]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Google is going to [shut down the consumer version of Google+](https://www.blog.google/technology/safety-security/project-strobe/) over the next several months and that means that Google provider will stop working as it relies on Google+ as I can see. Are there any plans to migrate existing Google provider to use a recommended [Google Sign-In API](https://developers.google.com/identity/sign-in/web/sign-in#before_you_begin)? Existing apps using Google provider might be impacted once Google+ is taken down. Or do I miss anything and existing provider won't require any changes given the announcement?

**Comment by derrickmehaffy** [comment]
This is honestly a good question. After the plugin framework rewrite is finished I believe the plan was to move over to using passport.js and split each provider into their own separate plugins.

I'm sure there is probably one that doesn't use the G+ API but my guess is even though Google is shutting down + they will keep the API alive or offload users to the normal one.

**Comment by mccrodp** [comment]
I think this is more of a hard shutdown due to security concerns with the Google+ APIs, so when they say they are shutting it down, might be risky to bank on them offloading requests to another newer API. https://www.theverge.com/2018/12/10/18134541/google-plus-privacy-api-data-leak-developers

We've updated our app recently to migrate to a more recent Google API and were considering integrating with Strapi via Google Auth as our first steps to making it our new CMS, but this is a blocker at the moment. 

If the solution we used using Sign-in API is of benefit it'd be great to share any detail on that here, @nicksp. I cannot remember if we used a custom approach to implementing that, or an available npm solution, but it's working well.

Looking forward to hearing more on this and if there's anything the open source community can do to help, let us know here also. Cheers

**Comment by mccrodp** [comment]
Hey @lauriejim, had you any thoughts on this one / the above? Have you had any users complain of dropped connections yet here, is this a common feature in Strapi? I'm not sure if APIs are failing yet, but looks like a hard shutdown in March, so I'm curious why it's labelled as an enhancement if things might break here very soon for anyone using Strapi via Google Auth. https://developers.google.com/+/api-shutdown

**Comment by lauriejim** [comment]
We will work on it soon as we can. For now we are busy on other tasks.
If you want to make the update to make it work with the Google+ shut down you can submit a PR.

- Here is the [Grant configuration](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/functions/bootstrap.js#L61)
- Here is [Purest configuration](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Providers.js#L161)

We really appreciate if you can submit a PR.

**Comment by mccrodp** [comment]
Great, thanks for the update here, @lauriejim, that is completely understandable. I will definitely see if we can fit this into our upcoming roadmap. Will sync up with you here soon if we can proceed with that (I really hope so!)

**Comment by lauriejim** [comment]
Thank you @mccrodp !

**Comment by fattomhk** [comment]
Here is my hot fix, waiting for passport ver.: 
```
case 'google': {
      
      const config = {
        "google": {
          "https://www.googleapis.com": {
            "__domain": {
              "auth": {
                "auth": {"bearer": "[0]"}
              }
            },
            "{endpoint}": {
              "__path": {
                "alias": "__default"
              }
            },
            "oauth/[version]/{endpoint}": {
              "__path": {
                "alias": "oauth",
                "version": "v3"
              }
            }
          }
        }
      }
      var google = new Purest({provider: 'google', config})

      google.query('oauth').get('tokeninfo').qs({id_token: access_token}).request((err, res, body) => {
        if (err) {
          callback(err);
        } else {
          const { name, email, issued_to } = body;
          const clientIDs = [IOS_CLIENT, ANDROID_CLIENT, WEB_CLIENT];
          if(_.findIndex(clientIDs, function(o) { return o === issued_to; }) >= 0) {
            callback(null, {
              username: body.email.split("@")[0],
              email: email,
              name: name
            });
          } else {
            callback(new Error("Invalid client ids"));
          }
        }
      });
      break;
    }

```

**Comment by derrickmehaffy** [comment]
@fattomhk good for a PR as the passport stuff will still be a while, likely after the beta (as the plugin framework rewrite is included in the beta PR)

**Comment by rnasif** [comment]
> Here is my hot fix, waiting for passport ver.:
> 
> ```
> case 'google': {
>       
>       const config = {
>         "google": {
>           "https://www.googleapis.com": {
>             "__domain": {
>               "auth": {
>                 "auth": {"bearer": "[0]"}
>               }
>             },
>             "{endpoint}": {
>               "__path": {
>                 "alias": "__default"
>               }
>             },
>             "oauth/[version]/{endpoint}": {
>               "__path": {
>                 "alias": "oauth",
>                 "version": "v3"
>               }
>             }
>           }
>         }
>       }
>       var google = new Purest({provider: 'google', config})
> 
>       google.query('oauth').get('tokeninfo').qs({id_token: access_token}).request((err, res, body) => {
>         if (err) {
>           callback(err);
>         } else {
>           const { name, email, issued_to } = body;
>           const clientIDs = [IOS_CLIENT, ANDROID_CLIENT, WEB_CLIENT];
>           if(_.findIndex(clientIDs, function(o) { return o === issued_to; }) >= 0) {
>             callback(null, {
>               username: body.email.split("@")[0],
>               email: email,
>               name: name
>             });
>           } else {
>             callback(new Error("Invalid client ids"));
>           }
>         }
>       });
>       break;
>     }
> ```

I tryed this but did not work, however this one works for me:

`    case 'google': {
      
      const config = {
        "google": {
          "https://www.googleapis.com": {
            "__domain": {
              "auth": {
                "auth": {"bearer": "[0]"}
              }
            },
            "{endpoint}": {
              "__path": {
                "alias": "__default"
              }
            },
            "oauth/[version]/{endpoint}": {
              "__path": {
                "alias": "oauth",
                "version": "v3"
              }
            }
          }
        }
      }
      var google = new Purest({provider: 'google', config})
      
      google.query('oauth').get('tokeninfo').qs({access_token}).request((err, res, body) => {
        if (err) {
          callback(err);
        } else {
          callback(null, {           
            username: body.email.split("@")[0],
            email: body.email
          });
        }
      });
      break;
    }`

**Comment by fattomhk** [comment]
@rnasif it is because i don't know how to setup the client ids in config page.

I added a checking here for security: 
```
 const clientIDs = [IOS_CLIENT, ANDROID_CLIENT, WEB_CLIENT];
          if(_.findIndex(clientIDs, function(o) { return o === issued_to; }) >= 0) {
            ...
          }
```
Simply replace the enums to your client ids would be fine.

**Comment by AndreiLucaci** [comment]
@lauriejim What about the grant scopes, why is it restricting only to `email`? Shouldn't the grant also cover the `profile` as well?

```javascript
google: {
      enabled: false,
      icon: 'google',
      key: '',
      secret: '',
      callback: '/auth/google/callback',
      scope: ['email'],  // <----- here it should also contain the profile, scope: ['email', 'profile']
    },
```

Currently, when google is used to create accounts, the only response we get from them is the email, without for example, the name of that user that is has in Google. I need to be able to get that information, so that I can setup correctly user accounts on my website.

Google handles the oauth2 login differently from FB, in which you can specify the scope asa a query string. Google needs to explicitly request the scope when generating the access_token for their googleapis (https://developers.google.com/identity/protocols/googlescopes#oauth2v2).

If the grant cannot be done, is there any way of requesting the `profile` scope with `purest` configuration?

**Comment by AndreiLucaci** [comment]
> @lauriejim What about the grant scopes, why is it restricting only to `email`? Shouldn't the grant also cover the `profile` as well?
> 
> ```js
> google: {
>       enabled: false,
>       icon: 'google',
>       key: '',
>       secret: '',
>       callback: '/auth/google/callback',
>       scope: ['email'],  // <----- here it should also contain the profile, scope: ['email', 'profile']
>     },
> ```
> 
> Currently, when google is used to create accounts, the only response we get from them is the email, without for example, the name of that user that is has in Google. I need to be able to get that information, so that I can setup correctly user accounts on my website.
> 
> Google handles the oauth2 login differently from FB, in which you can specify the scope asa a query string. Google needs to explicitly request the scope when generating the access_token for their googleapis (https://developers.google.com/identity/protocols/googlescopes#oauth2v2).
> 
> If the grant cannot be done, is there any way of requesting the `profile` scope with `purest` configuration?

I have created an override bootstrap method which overrides custom settings form the existing grant configuration, before running any code.

```javascript
const _ = require('lodash');

const grantConfigOverrides = {
  google: {
    scope: ['email', 'profile']
  }
};

module.exports = {
  initWithOverrides: async () => {
    const pluginStore = strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
    });

    let grantConfig = (await pluginStore.get({ key: 'grant' })) || {};

    if (grantConfig && !_.isEmpty(grantConfig)){
      grantConfig = _.merge(grantConfig, grantConfigOverrides);
    
      await pluginStore.set({ key: 'grant', value: grantConfig });
    }
  }
};
```
You should invoke this module in your application bootstrap part, such as:
```javascript
// your bootstrap function
const { initWithOverrides } = require('./grant-bootstrap'); // previous module
/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */
module.exports = cb => {
  const promises = [
    // initializes grants for auth providers with custom overrides
    initWithOverrides()
  ];

  Promise.all(promises).then(() => cb());
};
```

I don't know why this is not documented anywhere on the website 😥 ! 
Hope this helps!

**Comment by rithuacharya** [comment]
@AndreiLucaci @lauriejim 
The above mentioned code generates error (error: cb is not a function)
I added the profile scope for google by editing the database (in table core_store, key plugin_users-permissions_grant)
```
scope: ['email', 'profile']
```
(only in google)

But the response I received does not contain profile info.
Looked into the controller Auth.connect and service Provider.connect functions, packages grant and purest but couldn't get any help.

And how to perform an action after receiving the response from google and before creating a strapi user (say if I want to create users in strapi only if they are from particular domain).

**Comment by AndreiLucaci** [comment]
> @AndreiLucaci @lauriejim
> The above mentioned code generates error (error: cb is not a function)
> I added the profile scope for google by editing the database (in table core_store, key plugin_users-permissions_grant)
> 
> ```
> scope: ['email', 'profile']
> ```
> 
> (only for google)
> 
> But the response I received does not contain profile info.
> Looked into the controller Auth.connect and service Provider.connect functions, packages grant and purest but couldn't get any help.
> 
> And how to perform an action after receiving the response from google and before creating a strapi user (say if I want to create users in strapi only if they are from particular domain).
> 
> Is there something like a controller (where we can add our code) for that.

Hi @rithuacharya 
The above coed was written to strapi beta version 16. Upon upgrading to latest version, the cb (callback) function was remove. It looks like this:

```javascript
// your bootstrap function
const { initWithOverrides } = require('./grant-bootstrap'); // previous module
/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */
module.exports = async () => {
  const promises = [
    // initializes grants for auth providers with custom overrides
    initWithOverrides()
  ];

  await Promise.all(promises);
};
```

**Comment by rithuacharya** [comment]
@AndreiLucaci 
Thank you. The error has gone but adding the profile in the scope doesn't seem to work.
The response received from strapi doesn''t contain profile information like firstname and lastname.
Or is there any other configuration to be done to include profile info in the strapi response @lauriejim

**Comment by jonathanmach** [comment]
@rithuacharya , @AndreiLucaci  - did you make any progress on this matter of getting additional Google  user info (not only its email)?
I have been stuck on this for a while now...

**Comment by rithuacharya** [comment]
@jonathanmach you'll have to extend the getProfile function, in  users-permissions/services/Provider.js file.
under switch case for google, I changed the endpoint

```google
        .get("https://www.googleapis.com/oauth2/v3/userinfo")
        .auth(access_token)
        .request((err, response, body) => {
          if (err) {
            callback(err);
          } else {
            callback(null, {
              username: body.email.split("@")[0],
              email: body.email,
              name: body.name,
            });
          }
        });
```

The body contains additional info about user.
@lauriejim I'm not sure if this is a good approach, but I was able to get the firstname and lastname of the user.

**Comment by jonathanmach** [comment]
@rithuacharya , thanks! I'm going to stick to this solution for now.
PS: I had to extend the `extensions\users-permissions\config\functions\bootstrap.js` and change the scope from the google provider to `scope: ["email", "profile"],`.

Thanks!

**Comment by alearm246** [comment]
> @jonathanmach you'll have to extend the getProfile function, in users-permissions/services/Provider.js file.
> under switch case for google, I changed the endpoint
> 
> ```
>     google
>         .get("https://www.googleapis.com/oauth2/v3/userinfo")
>         .auth(access_token)
>         .request((err, response, body) => {
>           if (err) {
>             callback(err);
>           } else {
>             callback(null, {
>               username: body.email.split("@")[0],
>               email: body.email,
>               name: body.name,
>             });
>           }
>         });
> ```
> 
> The body contains additional info about user.
> @lauriejim I'm not sure if this is a good approach, but I was able to get the firstname and lastname of the user.

I did the same thing but was unable to get the firstname and lastname. Is there a way to also return the user's google profile picture image url

**Comment by trangchongcheng** [comment]
> > @jonathanmach you'll have to extend the getProfile function, in users-permissions/services/Provider.js file.
> > under switch case for google, I changed the endpoint
> > ```
> >     google
> >         .get("https://www.googleapis.com/oauth2/v3/userinfo")
> >         .auth(access_token)
> >         .request((err, response, body) => {
> >           if (err) {
> >             callback(err);
> >           } else {
> >             callback(null, {
> >               username: body.email.split("@")[0],
> >               email: body.email,
> >               name: body.name,
> >             });
> >           }
> >         });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The body contains additional info about user.
> > @lauriejim I'm not sure if this is a good approach, but I was able to get the firstname and lastname of the user.
> 
> I did the same thing but was unable to get the firstname and lastname. Is there a way to also return the user's google profile picture image url

That right, it only return picture and email, i want get name but currenly not found solution...anyone help?

**Comment by shonsirsha** [comment]
> > > @jonathanmach you'll have to extend the getProfile function, in users-permissions/services/Provider.js file.
> > > under switch case for google, I changed the endpoint
> > > ```
> > >     google
> > >         .get("https://www.googleapis.com/oauth2/v3/userinfo")
> > >         .auth(access_token)
> > >         .request((err, response, body) => {
> > >           if (err) {
> > >             callback(err);
> > >           } else {
> > >             callback(null, {
> > >               username: body.email.split("@")[0],
> > >               email: body.email,
> > >               name: body.name,
> > >             });
> > >           }
> > >         });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The body contains additional info about user.
> > > @lauriejim I'm not sure if this is a good approach, but I was able to get the firstname and lastname of the user.
> > 
> > 
> > I did the same thing but was unable to get the firstname and lastname. Is there a way to also return the user's google profile picture image url
> 
> That right, it only return picture and email, i want get name but currenly not found solution...anyone help?

Me too. Anyone??

**Comment by rithuacharya** [comment]
@trangchongcheng @shonsirsha 
Along with updating the getProfile function, do override the scopes  as mentioned here


> > @AndreiLucaci @lauriejim
> > The above mentioned code generates error (error: cb is not a function)
> > I added the profile scope for google by editing the database (in table core_store, key plugin_users-permissions_grant)
> > ```
> > scope: ['email', 'profile']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (only for google)
> > But the response I received does not contain profile info.
> > Looked into the controller Auth.connect and service Provider.connect functions, packages grant and purest but couldn't get any help.
> > And how to perform an action after receiving the response from google and before creating a strapi user (say if I want to create users in strapi only if they are from particular domain).
> > Is there something like a controller (where we can add our code) for that.
> 
> Hi @rithuacharya
> The above coed was written to strapi beta version 16. Upon upgrading to latest version, the cb (callback) function was remove. It looks like this:
> 
> ```js
> // your bootstrap function
> const { initWithOverrides } = require('./grant-bootstrap'); // previous module
> /**
>  * An asynchronous bootstrap function that runs before
>  * your application gets started.
>  *
>  * This gives you an opportunity to set up your data model,
>  * run jobs, or perform some special logic.
>  */
> module.exports = async () => {
>   const promises = [
>     // initializes grants for auth providers with custom overrides
>     initWithOverrides()
>   ];
> 
>   await Promise.all(promises);
> };
> ```

**Comment by tvqqq** [comment]
I use the code of @rithuacharya but do not get the name. I found the workaround way by adding the below code into `src/index.js`

```
async bootstrap({strapi}) {
    const pluginStore = strapi.store({
      environment: '',
      type: 'plugin',
      name: 'users-permissions',
    });
    // Ensure profile scope for Google Auth
    const grantConfig = await pluginStore.get({key: 'grant'})
    if (grantConfig) {
      if (grantConfig.google && grantConfig.google.scope) {
        grantConfig.google.scope = ['openid', 'email', 'profile']
        await pluginStore.set({key: 'grant', value: grantConfig});
      }
    }
  },
```
