### ISSUE TITLE
Compatibility with Maria DB 

### ISSUE THREAD

**Issue by msarfaraz** [strapi/strapi#2662]
The following option are not working in Maria DB.

1)2 timestamp is not support by maria db in single table.However it is noticed we have two cols in UploadFile Table 
2) Table name with "-" is making issue 

As maria DB is most popular used Open source Database and alternate to MySQL for commercial version it will be great if there us work around

**Comment by derrickmehaffy** [comment]
@msarfaraz please update your issue with the proper bug report template. I am marking this as closed until your issue is updated with the template information
