### ISSUE TITLE
The drop down for adding relation doesn't show all the contents.

### ISSUE THREAD

**Issue by ryubro** [strapi/strapi#2665]
**Informations**
- **Node.js version**: v10.11.0
- **NPM version**: v6.4.1
- **Strapi version**: v3.0.0-alpha.19
- **Database**: Mongo
- **Operating system**: Mac
- **(Optional) Link to your Project**: 

**What is the current behavior?**

In the editing page of a content with relations, the relation drop down menu only shows up to 20 items.

For instance, let's say the content type A has a relation to the content type B. When we add or edit a content that is of type A, we'll see a dropdown menu that lists the existing contents that are of type B. When we have more than 20 contents of type B, we'll see only the first 20.

**Steps to reproduce the problem**

1. In the content type builder, create two types A and B (but the name doesn't matter, of course) that has one-to-one relationship (but the type of relationship doesn't matter) to each other
2. Create 30 contents of type B
3. Create a content of type A and open the dropbox to make a relation to a content of type B
4. You only see 20 contents of type B out of 30

**What is the expected behavior?**

User should be able to see all contents

**Suggested solutions**

The line `_limit: 20,` in the following blocks seem to cause this issue.

https://github.com/strapi/strapi/blob/c3c24ca7ad415ecdebe53d95ab777eb793c43526/packages/strapi-plugin-content-manager/admin/src/components/SelectMany/index.js#L53-L57

https://github.com/strapi/strapi/blob/c3c24ca7ad415ecdebe53d95ab777eb793c43526/packages/strapi-plugin-content-manager/admin/src/components/SelectOne/index.js#L41-L45

I can come up with three suggestions:
1. Removing the limit at all.
2. Make the number of limit configurable.
3. Make the field auto-completable, so that when the number of the contents of the relevant type is too big, it still works without a performance issue.

Thank you for the project and reading this issue.

**Comment by yummyelin** [comment]
Related to #2032

**Comment by ryubro** [comment]
Sorry,

Actually what happened is it loads the next 20 items when the scroll reaches the end in the dropdown menu.

I have no idea why my previous experience didn't work in that way, but I just checked that it works. I'll close this issue.

**Comment by loongmxbt** [comment]
Same problem. @ryubro  I tested both my local and strapi demo, not seeing the automatic load feature. What am I missing?

```
Actually what happened is it loads the next 20 items when the scroll reaches the end in the dropdown menu.
```

**Comment by 19Sean96** [comment]
Anyone still having this issue? I'm experiencing the same thing, except when you scroll to the bottom, it only loads one at a time. Makes bulk adding pretty slow. 

Any way I can change this? I'm using version 3.0.0-beta.18.3

**Comment by francescostella** [comment]
I'm using version 3.0.0-beta.18.7 and I'm experiencing the same issue, but I wasn't able to find traces of a know issue anywhere else than here.

@19Sean96 were you able to find a solution?

**Comment by ytachi0026** [comment]
Hey guys, I am facing the same issue as your, i am using Strapi 18.3

**Comment by daviddelpuerto** [comment]
Same here, dropdown loads first items but then it loads one at a time, and searching for a known item doesn't return the item. Still no solutions?

**Comment by 19Sean96** [comment]
@francescostella @ytachi0026 @daviddelpuerto Unfortunately, I was not able to find a solution. 

I ended up finding an alternative open source headless CMS ([Directus](https://directus.io/)). Kinda sucks that I had switch gears from strapi due to a single bug, but so far I haven't had any problems with dropdowns

**Comment by francescostella** [comment]
Thanks @19Sean96 for following up. 
For everyone on the thread, I'm currently on  `3.0.0-beta.19.3` and the issue is resolved, the dropdown lazy-load works perfectly.
cc @daviddelpuerto @ytachi0026
