### ISSUE TITLE
Allow to count search queries in count API route.

### ISSUE THREAD

**Issue by driku** [strapi/strapi#2666]
**Informations**
- **Node.js version**: v11.4.0
- **NPM version**:  6.6.0
- **Strapi version**: 3.0.0-alpha.17 (node v11.4.0)
- **Database**:  Mongo DB (v4.0.5)
- **Operating system**:  Mac
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Query to get count having _q=some_search_term always returns 0

**Steps to reproduce the problem**

hit any url to calculate the count i.e pluralized_entity/count?_q=search Keyword

**What is the expected behavior?**
It should give the count as it gives in content manager plugin in which countSearch implementation is there

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello [mention], please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

We need to know the exact version of Strapi and the database you use.

Thank you.

> This is a templated message

**Comment by driku** [comment]
I have updated the strapi & database version.

**Comment by lauriejim** [comment]
This feature is available in `alpha.26`
