### ISSUE TITLE
Cannot update user - Email already taken

### ISSUE THREAD

**Issue by aaronweatherall** [strapi/strapi#2668]
**Informations**
- **Node.js version**: 
v10.0.0
- **NPM version**: 
5.6.0
- **Strapi version**: 
v3.0.0-alpha.19
- **Database**:
Mongo 
- **Operating system**: 
OSX Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When I attempt to update a user in the admin, I receive the following error `Email is already taken.`.

**Steps to reproduce the problem**
1. Add a field to user e.g Phone Number.
2. Click edit on a user, enter a phone number and click save.
3. User cannot be saved as the `Email is already taken`.

**What is the expected behavior?**
I expect to be able to update the user without issues.

**Suggested solutions**
I assume the validation should be for create only and not update.

**Comment by aaronweatherall** [comment]
![](https://ucd3095231e2aef843ca712d7818.previews.dropboxusercontent.com/p/thumb/AAWF2c0fZ-Nq5LdXmlNgR6D3KAFUdw7QxgOYimZ8-5kXmJzlRFlxtmn0Jx9z7WowUgMf-SPOykpzWMScWMeTMa4l4YdM1zbfjcHaOo3r7nb6l1hWaxrUreCmvUu-YA8NvTqWKeLOgJq_xCk2PXLGRi3W5CIxjX2qhfCJFtz86pSf3WuJkAc1wF0eqiTnfKC7aV_Ziqp8_u_sUELJAAtx7nFCV5UTonAbgiaSbL9WqOWQuR31U9Cg9hoeMj_y12wSjK9Vo25yt5nSSGtxhbZpPLRTDKrLcjI7AxdPq3Em17dfeAEnubgzlzjqmH6PvqFDL2MnZ_7S5xcGp3ThWYlijp6qEUonaaoyRkZkerSm1ScqjQ/p.png?size=1280x960&size_mode=3)

**Comment by alphapseudo** [comment]
This should be fixed and released in [v3.0.0-alpha.20]( https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.20) from #2669.

**Comment by lauriejim** [comment]
Have been fixed in `alpha.20` please update your Strapi application.

**Comment by msaglietto** [comment]
@lauriejim 
I have the same problem on `alpha.25.2` ... maybe a regression issue ? 

Not sure what version I used to generate the project but I did a npm install of the latest and I cant update users without modifying the email

**Comment by lauriejim** [comment]
Hello @msaglietto !
I just try and it works well.
I you update you app, make sure you also update your users-permissions plugin.
