### ISSUE TITLE
Boolean where clause not working with graphql

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#2672]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: 6.5.0
- **Strapi version**: alpha 20
- **Database**: mysql
- **Operating system**: macOS 10.14.2
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When searching on a boolean value using graphql I get incorrect results.

**Steps to reproduce the problem**
Given this query:
```
query{
  projects(where: {completed: true}){
    name
    completed
    is_published
  }
}
```
I see results where `completed = false`.

**What is the expected behavior?**
I expect to only see results where `completed = true`.

**Suggested solutions**
The problem seems to lie in the following code. It's only expecting boolean types which have been set by a string value of `true` or `false`. But when using graphql since it's strongly typed, it's actually passing in boolean `true` or `false` values.

https://github.com/strapi/strapi/blob/86d6ba62ac17973db48588781b58b611212cda4e/packages/strapi-utils/lib/models.js#L486-L490

Possible something like this might work?
```js
const suffix = key.split('_');
// Mysql stores boolean as 1 or 0
if(typeof value === 'string'){
  formattedValue = value === 'true' ? '1' : '0';
} else {
  formattedValue = value;
}	
```

**Comment by lauriejim** [comment]
Thank you to report this issue. We will check that soon as possible.

**Comment by jeecrypt** [comment]
I faced the same problem.
Is work being done to correct this issue?

**Comment by derrickmehaffy** [comment]
> I faced the same problem.
> Is work being done to correct this issue?

This was fixed over 2 years ago, if you still get the issue then please open a new issue (see the templated message below)

---

Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
