### ISSUE TITLE
Register and forgot-password entry points in users-permissions plugin do not return errors in a consistent way

### ISSUE THREAD

**Issue by luc-plamondon** [strapi/strapi#2673]
**Informations**
- **Node.js version**:  v10.15.0
- **NPM version**: 6.5.0
- **Strapi version**:  3.0.0-alpha.18
- **Database**: mongodb
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When an error occurs while trying to send an email, the API responds with a bad request bearing an object as the error message:

{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.form.error.email.invalid"}]}]} 

**Steps to reproduce the problem**
Create a user with email: "abc+1@gmail.com".

Call /auth/forgot-password with that email as a parameter.

**What is the expected behavior?**
"Message" in response should have the same format as everywhere else in the plugin module and Strapi generated controllers, that is: contain only a string, not an object. For example:
{"statusCode":400,"error":"Bad Request","message":"This email is invalid."}  

**Suggested solutions**
In plugins/users-permissions/controllers/Auth.js, function forgotPassword and function register, in the following block of code:

    try {
      // Send an email to the user.
      await strapi.plugins['email'].services.email.send({
        to: user.email,
        from: (settings.from.email || settings.from.name) ? `"${settings.from.name}" <${settings.from.email}>` : undefined,
        replyTo: settings.response_email,
        subject: settings.object,
        text: settings.message,
        html: settings.message
      });
    } catch (err) {
      return ctx.badRequest(null, err);
    }

Replace last line with:
`return ctx.badRequest(null, err.message);`

The replacement I suggest is based on the last line of function register:
`ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: adminError }] }] : err.message);`

**Comment by luc-plamondon** [comment]
The incorrect line is the one I pointed out but the replacement should not be err.message, it is a bit more complicated than that. Either the string to return has to be looked up using the message ID, either the email service has to generate its error in a "non-admin" context. If it helps: I'm using Sendmail.

I would have preferred the other way around, all bad requests in Strapi returning an error ID instead of an error message (I probably have the same needs in my app than the Strapi team has for the admin app), but I am not sure of the side effects of setting ctx.request.admin to true (if it's possible) when calling the API outside Strapi's admin. Until I investigate this matter, the error format should at least be predictable.

**Comment by lauriejim** [comment]
Hello @luc-plamondon , thank you for reporting this issue.
Can you please submit a PR to fix it.
Will appreciate your contribution!

**Comment by lauriejim** [comment]
Have a topic about the error messages!
Closing this issue - related to another main topic.
