### ISSUE TITLE
How to manager transaction

### ISSUE THREAD

**Issue by ngoalongtb** [strapi/strapi#2675]
I have a Post and a Comment
First, I save post success,
Second, I save Comment with errors,

but Post saved without rollback.

I can't find it in document, I thinks transaction manager is important.
Thanks you

**Comment by lauriejim** [comment]
Hello @ngoalongtb , please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

Thank you.

> This is a templated message

**Comment by luwes** [comment]
needs some custom code, I've not tried it but looks like it should work.

https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html#custom-queries
https://bookshelfjs.org/api.html#Bookshelf-instance-transaction

**Comment by zadorozhny** [comment]
@taminhluan did you solve this problem?
