### ISSUE TITLE
Can't upgrade from alpha.19 to alpha.20

### ISSUE THREAD

**Issue by crashlab** [strapi/strapi#2683]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.20
- **Database**: MySQL
- **Operating system**: Mac OSX
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Cannot upgrade from alpha.19 to alpha.20 because the plugins directory is empty in the new project created with alpha.20.

**Steps to reproduce the problem**

create a new project and check the files inside plugins.

**What is the expected behavior?**

the directory plugins of alpha.20 should contain the files to be copied over the old project created with alpha.19

**Suggested solutions**

**Comment by lauriejim** [comment]
Can you try to re-install Strapi and try to create a new project.
I just install Strapi, create a project and all plugins are present. So your issue looks weird.

**Comment by crashlab** [comment]
I did with the version alpha.21 and everything was fine.
