### ISSUE TITLE
Querying multiple items with graphql doesn't return data

### ISSUE THREAD

**Issue by alexKwonIsAwesome** [strapi/strapi#2686]
**Informations**
- **Node.js version**: v10.9.0 
- **NPM version**: v6.2.0
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: mongodb
- **Operating system**: macOS mojave 10.14.2 (18C54)
- **(Optional) Link to your Project**: 

**What is the current behavior?**
After creating a content type(model), I activated graphql plugin and created some items on the admin. Then I queried the model on the graphql playground but no results are returning.

It returns:
```
{
  "data": {
    "posts": []
  }
}
```

**Steps to reproduce the problem**

1. Create content type. For me, I created a content type called "Post" with attribute "title"
2. Create items. e.g. `{ title: "love strapi" }, { title: "awesome library" }`
3. Install graphql plugin
4. Query the model on graphql playground with the following query:
```
query {
  posts {
    title
  }
```

**What is the expected behavior?**

The returning data should include the items as:
```
{
  "data": {
    "posts": [
        { title: "love strapi" },
        { title: "awesome library" }
    ]
  }
}
```

**Suggested solutions**

I'm really new to the library so I might be wrong, but I found out that the '_populate' attribute on `ctx.query` is causing the problem.

On the `fetchAll`method in `services/Post.js`, the `filters` variable contains `_populate` attribute with value of empty array([]). When I removed the `_populate` attribute of the `filters` object, the data is returned as I expected.

I think there is a better way to solve the problem.

Please help 😁
Thanks.

**Comment by Aurelsicoko** [comment]
It seems that you're using an old version of Strapi (alpha.12.6). Can you try to upgrade to the latest version?

**Comment by alexKwonIsAwesome** [comment]
After I update to newest version(3.0.0-alpha.21), it works like a charm. I thought I was using the latest version. 
Thanks a lot @Aurelsicoko !

**Comment by vshirguppi** [comment]
New to Strapi.
On version 3.0.0-alpha.14.3 and I am encountering a similar problem. The `fetchAll` query returns an empty array.
    `"posts": []`

Commenting all the filters on the `fetchAll` method in `services/Post.js` returns all posts but obviously the filers wont work.
Please let me know if I am missing something. Appreciate your time and insights.
