### ISSUE TITLE
Timestamps missing in GraphQL queries

### ISSUE THREAD

**Issue by NeOMakinG** [strapi/strapi#2688]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.21
- **Database**:  10.0.36-MariaDB
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**

The GraphQL plugin is generating schemas without createdAt and updatedAt field, but they're correct in the database and model is correctly configured (timestamps: true in options)

**Steps to reproduce the problem**

Used a fresh install, migrated my models to it, installed GraphQL plugin and still starting the app.

**What is the expected behavior?**

Should have createdAt and updatedAt in graphql schemas to query these fields.

**Suggested solutions**

**Comment by NeOMakinG** [comment]
Found the issue, it's related to  #2556

The problem is the graphql plugin in services folder Resolver.js at the add timestamps attribute the conditions has not been updated since the custom timestamps columns feature has been added.

Doing the PR in some hours
Thanks to @derrickmehaffy for the help finding the PR.

**Comment by derrickmehaffy** [comment]
@NeOMakinG thats what I'm here for :stuck_out_tongue:
