### ISSUE TITLE
Overwritten i18n translations

### ISSUE THREAD

**Issue by brooth** [strapi/strapi#2695]
Just faced an issue that strapi created `en_us.json` locale file next to `en_US.json`, language.json:

```
{
  "enabled": true,
  "defaultLocale": "en_us",
  "modes": [
    "query",
    "subdomain",
    "cookie",
    "header",
    "url",
    "tld"
  ],
  "cookieName": "locale"
}
```

so both, filename `en_US.json` and `defaultLocale` by default (cli strapi new). Thus all my translations gone. I might add that It happened after I pushed my docker container to production.

Let me know if you need more details. I'll help if I can.

strapi: v.3.0.0-alpha.19
node: 11.1.0 (docker node:11.1.0-alpine)

**Comment by lauriejim** [comment]
Hello [mention], please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

I don't understand your issue. What did you try to do and what is the issue you have.

Thank you.

> This is a templated message
