### ISSUE TITLE
521 server error when using pm2 but "strapi start" works

### ISSUE THREAD

**Issue by eComEvo** [strapi/strapi#2696]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.21
- **Database**: PostgreSQL 11
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
When I try to start strapi using pm2, it always produces a 521 server error. Strapi only works properly when I simply do `sudo strapi start` or `sudo npm start`.

Strapi also complains about `hook:mongoose` even tho I am using `bookshelf`.

**Steps to reproduce the problem**
The command `sudo pm2 start npm --no-automation --watch --name strapi -- start` produces a continuous output of this message when I view the pm2 log:
```
0|strapi  | [2019-01-26T02:27:42.459Z] warn (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
0|strapi  | > staging.strapi.example.com@0.1.0 start /home/forge/staging.strapi.example.com
0|strapi  | > NODE_ENV=development node server.js "/home/user/staging.strapi.example.com"
```

The command `sudo pm2 start strapi --no-automation --watch --name strapi -- start` produces a continuous output of this message when I view the pm2 log:
```
0|strapi  | [2019-01-26T02:27:42.459Z] warn (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
```

However, this is the output of `sudo npm start` which causes the site to load properly when the admin URL is accessed:
```
> staging.strapi.example.com@0.1.0 start /home/forge/staging.strapi.example.com
> NODE_ENV=development node server.js

[2019-01-26T02:43:40.582Z] warn (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
[2019-01-26T02:43:41.479Z] info Time: Sat Jan 26 2019 02:43:41 GMT+0000 (Coordinated Universal Time)
[2019-01-26T02:43:41.479Z] info Launched in: 2660 ms
[2019-01-26T02:43:41.479Z] info Environment: development
[2019-01-26T02:43:41.479Z] info Process PID: 21176
[2019-01-26T02:43:41.479Z] info Version: 3.0.0-alpha.21 (node v10.15.0)
[2019-01-26T02:43:41.479Z] info To shut down your server, press <CTRL> + C at any time

[2019-01-26T02:43:41.480Z] info ☄️  Admin panel: http://staging.strapi.example.com/dashboard
[2019-01-26T02:43:41.480Z] info ⚡️ Server: http://staging.strapi.example.com
```

**What is the expected behavior?**
pm2 runs strapi without error as if I ran `strapi start` or `sudo npm start` commands by themselves.

Everything is default except for the following files...

`package.json`:
```
{
  "name": "staging.strapi.example.com",
  "private": true,
  "version": "0.1.0",
  "description": "Strapi API",
  "main": "./server.js",
  "scripts": {
    "setup": "cd admin && npm run setup",
    "start": "NODE_ENV=development node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "dotenv": "4.0.0",
    "dotenv-expand": "4.2.0",
    "knex": "latest",
    "lodash": "^4.17.5",
    "pg": "7.8.0",
    "strapi": "3.0.0-alpha.21",
    "strapi-hook-bookshelf": "3.0.0-alpha.21",
    "strapi-hook-knex": "3.0.0-alpha.21",
    "strapi-hook-mongoose": "^3.0.0-alpha.13"
  },
  "author": {
    "name": "user",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "user",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "packageManager": "npm",
    "uuid": "9a7c4d6d-70e3-41e1-b912-4eb97e42c3f4"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}
```

`config/environments/development/server.json`:
```
{
  "host": "${process.env.HOST}",
  "port": "${process.env.PORT || 80}",
  "production": false,
  "proxy": {
    "enabled": false
  },
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "path": "/dashboard",
    "autoOpen": false
  }
}
```

`config/environments/development/database.json`:
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "127.0.0.1",
        "srv": false,
        "port": 5432,
        "database": "strapi",
        "username": "strapi",
        "password": "somerandompassword",
        "ssl": false
      },
      "options": {}
    }
  }
}
```

`server.js`:
```
#!/usr/bin/env node
'use strict';

/**
 * Use `server.js` to run your application without `$ strapi start`.
 * To start the server, run: `$ npm start`.
 *
 * This is handy in situations where the Strapi CLI is not relevant or useful.
 */

process.chdir(__dirname);

(() => {
  require('dotenv').config();

  const strapi = require('strapi');
  strapi.start();
})();
```

**Comment by lauriejim** [comment]
Hello @eComEvo !

The error log is caused because you have `strapi-hook-mongoose` installed (see you `package.json`) and you don't have `Mongo` database in your application. 

You use a PG database so you should only have `strapi-hook-bookshelf` and `strapi-hook-knex`.

I don't know what you did to have both `mongoose` and `bookshelf` in your `package.json`.

So just remove this package and it will stop this error log.

**Comment by eComEvo** [comment]
@lauriejim I installed Strapi using the package.json it generated right after I ran `strapi new staging.strapi.example.com`.

This didn't fix the 521 server issue. It only removed the mongoose warning. Strapi still repeatedly outputs these lines instead of actually running under pm2:
```
0|strapi  | > staging.strapi.example.com@0.1.0 start /home/user/staging.strapi.example.com
0|strapi  | > NODE_ENV=development node server.js
```

By accident I noticed that if I start strapi with pm2, then stop it, then start the existing pm2 processagain, that the server error goes away.

Any idea what's causing this behavior?

**Comment by derrickmehaffy** [comment]
@eComEvo try generating a project without any special chars in the name (ie periods)

**Comment by eComEvo** [comment]
@derrickmehaffy I figured out the issue. Strapi does not like it when the `--watch` flag is used with pm2. When pm2 is not watching, the server boots fine.

Eliminating the periods from the project name didn't fix the issue. I simply named the project "strapi" but it still crashes the server on a clean install under pm2 with the `--watch` flag.
