### ISSUE TITLE
GraphQL aggregation incomplete with required numeric fields

### ISSUE THREAD

**Issue by JBuijgers** [strapi/strapi#2697]
**Informations**
- **Node.js version**: 10.8.0
- **NPM version**: 6.6.0
- **Strapi version**: 3.0.0-alpha.21
- **Database**: Mongo DB 4.0.4
- **Operating system**: Linux (Ubuntu)
- **(Optional) Link to your Project**: -

**What is the current behavior?**
Required fields do not have sum/avg/min/max added to the generated aggregator types in the GraphQL plugin.

**Steps to reproduce the problem**
1. Setup Strapi with the GraphQL plugin enabled
2. Add a content type with a number field that is required.
3. Go to localhost:1337/graphql and open the (green) schema button
4. Navigate to the aggregator for the content type we just created and it has only the count attribute 

**What is the expected behavior?**
Every numeric type (required or not) should be part of the aggregate.

**Suggested solutions**
As a workaround, I disabled the field from being required. Actual solution would be in plugins/graphql/services/Aggregator.js:454, where the numeric fields are extracted, the main error is caused by the function isNumericType on line 60. If the field is required, the type would be Int! or Float!, which will fail the isNumberType check. The code below would fix this.
```js
  isNumberType: type => {
    if (type.endsWith('!')) {
      type = type.slice(0, -1);
    }

    return type === 'Int' || type === 'Float';
  },
```

**Comment by lauriejim** [comment]
Hello @JBuijgers , thank you for reporting this issue.
Can you please submit a PR to fix it.
Will appreciate your contribution!

**Comment by lauriejim** [comment]
Yes you are right! 

Can you open a PR to fix it please.
Appreciate!

**Comment by TeosVerdi** [comment]
The issue still stands, when will it be fixed?

**Comment by lauriejim** [comment]
It's not fixed.
