### ISSUE TITLE
GraphQL doesn't install when pressing download in admin

### ISSUE THREAD

**Issue by andylobel** [strapi/strapi#2701]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**

It doesn't install because the git repo is missing:
https://github.com/strapi/strapi-plugin-graphql

To solve the problem manually I had to clone strapi and copy the `packages/strapi-plugin-graphql` to my projects `plugins/graphl` folder, then ran `npm install`.

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @andylobel , please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

All informations are missing.

Thank you.

> This is a templated message
