### ISSUE TITLE
Strapi heroku deployment show /index.html and not permitting /admin

### ISSUE THREAD

**Issue by gungorkocak** [strapi/strapi#2703]
**Informations**
- **Node.js version**: 10.14.2
- **NPM version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.17
- **Database**: mongoDB
- **Operating system**: macOS Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I already have an existing project that I have been developing on my local workstation. I am trying to deploy this to Heroku. I have resolved many things and now able to see `/index.html` file is rendered. It says go to `/admin` as a link, but no matter how I try it always renders the index.html file. That means I am also not able to login/set up an admin account. Javascript console does not give any errors.

**Steps to reproduce the problem**
1 - Have a already initialized and under active development strapi project in you local environment.
2 - Deploy it to Heroku
3 - Resolve out package-lock.json and database issues.
4 - See `index.html` file is rendered.
5 - Try to go '/admin' and see same `index.html` file is rendered, therefore it does not allow to do anything else.

**What is the expected behavior?**
It needs to ask initial admin user/password combo when I try to go '/admin'.

**Suggested solutions**
I have alse tried building admin both in my local environment-then-deploy and trying to build on heroku side.

Trying to build admin on Heroku also fails for me:

1. Naive try

```
$ heroku run "npm run setup" -a my-heroku-app
Error: Cannot find module '/app/packages/backend/admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
```

2. Try linking: 

```
$ heroku run "cd admin && npm link strapi-helper-plugin && cd .. && npm run setup" -a my-heroku-app
...
The '/app/packages/backend/.heroku/node/lib/node_modules/strapi-helper-plugin/node_modules/pngquant-bin/vendor/pngquant' binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/app/packages/backend/.heroku/node/lib/node_modules/strapi-helper-plugin/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
...
```

Not sure what to do here, I may need more of a direction if I am missing something or not.

**Comment by b3rday** [comment]
try to use == > https://github.com/strapi/strapi-heroku-app , its work for me :)

**Comment by gungorkocak** [comment]
@b3rday I have already made lots of changes on existing codebase, link seems to me for bootstrapping a strapi project.

In any case, I exhausted heroku buildpack options for me, tried docker container approach and it works like charm.

Closing this.
