### ISSUE TITLE
Creating Many to Many relation in Users plugin with the Content-Type builder fails 

### ISSUE THREAD

**Issue by Blacknosaur** [strapi/strapi#2708]
**Informations**
- **Node.js version**: v11.6
- **NPM version**: v6.5
- **Strapi version**: Alpha 21 (confirmed too in Alpha 14.1.1 and Alpha 18)
- **Database**: MongoDB 3.6.3
- **Operating system**: Amazon Linux AMI release 2017.09

**What is the current behavior?**
If you create a Many to Many relation with the Content-Type builder between the Users-Permissions plugin it fails because the relation it creates isn't bidireccional

**Steps to reproduce the problem**
If you create a relation like this one...
![image](https://user-images.githubusercontent.com/37783365/51904236-711d1300-23be-11e9-8fbc-9feeba6bf08f.png)

...you get this...
```
[2019-01-29T10:51:53.934Z] error Something went wrong in the model `User` with the attribute `followed`
[2019-01-29T10:51:53.937Z] error The attribute `followedBy` is missing in the model User (plugin - users-permissions)
```

... because it only writes this in User.settings.json
```
    "followers": {
      "collection": "user",
      "via": "followedBy",
      "dominant": true,
      "plugin": "users-permissions"
    }
```

**What is the expected behavior?**
It should create a bidirectional relation in between the same plugin, like this
```
    "followers": {
      "collection": "user",
      "via": "followedBy",
      "dominant": true,
      "plugin": "users-permissions"
    },
    "followedBy": {
      "collection": "user",
      "via": "followers",
      "plugin": "users-permissions"
    }
```

In fact, if you edit User.settings.json manually it work as expected.

This issue seems related to #2499 but not completely, I have problems with the model but not with the database, and a manual edit of the model fix the problem.

**Comment by lauriejim** [comment]
Thank you [mention] for your issue.
I will take a look soon as possible.

**Comment by lauriejim** [comment]
I checked it and it work well on generated APIs and it fail with User model.
I see in the request that update the model `PUT http://localhost:1337/content-type-builder/models/:model` in the generated API both attributes are sent `followers` and `followedBy`.
But in User model, just `followers` is send.
