### ISSUE TITLE
JSON data type is still not working in graphql

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2715]
**Informations**
- **Node.js version**:  v11.3.0
- **NPM version**: 
- **Strapi version**:  3.0.0-alpha.18
- **Database**:  mlab
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I cannot pass a JSON object even though the type is defined as JSON. If I use graphql plugin:

mutation {
                    createExam(input: {
                      data: {
                        questions: [{"gf": "hello"},{"a": "g"}]
                        subjects: ["5c468e2d61670b25b46ccdfe"]
                      }
                    }) {
                      exam {
                        questions
                        
                      }
                    }
                  }

Graphql simply won't let me add parenthesis around the properties, and so I cannot use JSON.stringify on the object before I pass it with javascript. Also passing the object without JSON.stringify will return [null, null]:

let a = {a: "hello"}

mutation {
                    createExam(input: {
                      data: {
                        questions: ` + a + `
                        subjects: ["5c468e2d61670b25b46ccdfe"]
                      }
                    }) {
                      exam {
                        questions
                        
                      }
                    }
                  }

What does work however is to stringify the object to JSON and then remove the parenthesis around the properties:

let p = JSON.stringify(parsedQuestions)
        p = p.replace(/\"([^(\")"]+)\":/g,"$1:");

But I'm afraid it's prone to problem?

Thanks in advance

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @omerfaran can you try with last version of Strapi please.

**Comment by omerfaran** [comment]
Hey lauriejim I did solve it, my syntax was wrong. I couldn't find that in the graphql plugin documentation, but it seems that to pass a JSON object you need to write:

const response = await strapi.request('POST', '/graphql', {
  data: {
    query: `mutation UpdateExam($input: updateExamInput!) {
      updateExam(input: $input) {
        exam { 
          questions 
        }
      }
    }`,
    variables: {
      input: {
        where: {
          id: examInfo.id
        },
        data: {
          questions: [{ gf: "hello" }]
        }
      }
    }
  }
});

With the help of a fellow on stackoverflow
