### ISSUE TITLE
Get dominant color from images uploaded using upload plugin

### ISSUE THREAD

**Issue by dainikinsider** [strapi/strapi#2720]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Hi Team,

Upload plugin provided by strapi is already doing great work. For image heavy websites, finding dominant color for all images is heavy weight in nature and also it will increase number of http requests( by ~2X). There are library like **dominant-color,node-vibrant, color-thief etc**. which can be used in front end to accomplish the same but it is not feasible to do so.

However just by adding few lines of code in upload plugin will do this magic.

**One of critical project is on hold just because of this feature.**

Thanks,

**Comment by Aurelsicoko** [comment]
@dainikinsider Thank you for raising this issue! I'm sorry to say that but it's clearly not a priority to implement this kind of features. It's too specific and I think the new plugin architecture/framework will allow you to do that. You might already be able to add a new field `dominantColor:string` in the File model, then using the model's lifecycles `beforeSave` where you could set the value.

**Comment by lauriejim** [comment]
I close this issue cause it's not a priority for us now. Will reopen it if it's needed.
Any way thank you for your proposition.
