### ISSUE TITLE
Org namespaced email providers do not get registered

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#2723]
**Informations**
- **Node.js version**: 11.6.0
- **NPM version**: 6.5.0
- **Strapi version**: alpha 20
- **Database**: 10.3.8-MariaDB
- **Operating system**: macos 10.14.2
- **(Optional) Link to your Project**:  https://www.npmjs.com/package/@teamgi/strapi-provider-email-sparkpost

**What is the current behavior?**
I'm not seeing my custom email provider in the admin after installing it via npm.

**Steps to reproduce the problem**
- I run the following command in my project root:
`npm i @teamgi/strapi-provider-email-sparkpost --save`
- I start strapi
- I visit `/admin/plugins/email/configurations/development`
- Under providers I only see `Sendmail`

**What is the expected behavior?**
I expect to see a provider named `Sparkpost`

**Suggested solutions**
The issue seems to be in `plugins/email/config/functions/bootstrap.js`. It looks like it does not support org namespaced package names. I think it would be better to try to programmatically retrieve the list of npm packages rather than simply relying on the folder names.

**Comment by lauriejim** [comment]
Ho yap! We have to manage this point.

How to fix this issue is to find where we find all installed providers and update the way we detect them.
I think it's `_.startWith()` and we have to improve it.

**Comment by lauriejim** [comment]
`📖info` Here is the code that manage provider detection:
- **Email** https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-email/config/functions/bootstrap.js#L30
- **Upload** https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/config/functions/bootstrap.js#L30

**Comment by greatwitenorth** [comment]
Executing something like this might be a bit more bullet proof for package detection:
```
npm list --depth=0 --json
```

Although I have found that it adds to the startup time. npm-pogrammatic might help as well although I have an open issue here since there's some issues currently with their package detection on some systems:
https://github.com/Manak/npm-programmatic/issues/21

**Comment by lauriejim** [comment]
To replace the `fs.readDir` ?

Our way check all installed node modules (based on the `node_modules` folder).
Your way check installed node modules saved in the `package.json`.

If we want this information we already have it in `strapi.config.info.dependencies`
And if you don't install your provider in dependencies with `--save` that will be unpossible to deploy it correctly.

We can improve this part yes.

**Comment by greatwitenorth** [comment]
This doesn't seem to be working anymore. If I install a package under a org namespace it does not show in the admin area. Was there a regression in one of the betas?
