### ISSUE TITLE
error  Cannot query field "allStrapiArticle" on type "Query"  graphql/template-strings

### ISSUE THREAD

**Issue by thommedia** [strapi/strapi#2730]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Can you add one article in your database please.

**Comment by lauriejim** [comment]
Hello @thommedia , please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

Thank you.

> This is a templated message
