### ISSUE TITLE
$pull error deleting entry with dominant model of many-to-many relation

### ISSUE THREAD

**Issue by gilhardl** [strapi/strapi#2731]
**Informations**
- **Node.js version**:  v10.15.0
- **NPM version**: v6.4.1
- **Strapi version**:  v3.0.0-alpha.21
- **Database**: MongoDB v4.0.5
- **Operating system**: Windows 10 Pro or Ubuntu 18.04 or Manjaro 18.0
- **(Optional) Link to your Project**:  https://github.com/gilhardl/strapi-delete-error

**What is the current behavior?**
Removing an entry of the dominant model of a many-to-many relation will right remove the entry and update associated models but will return a Mongo error : 
```
{ MongoError: '$pull' is empty. You must specify a field like so: {$pull: {<field>: ...}}
    at Function.create (C:\Users\LG\Work\LG\strapi-delete-error\node_modules\mongodb-core\lib\error.js:43:12)
    at toError (C:\Users\LG\Work\LG\strapi-delete-error\node_modules\mongodb\lib\utils.js:149:22)
    at coll.s.topology.update (C:\Users\LG\Work\LG\strapi-delete-error\node_modules\mongodb\lib\operations\collection_ops.js:1399:39)
    at C:\Users\LG\Work\LG\strapi-delete-error\node_modules\mongodb-core\lib\connection\pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  driver: true,
  name: 'MongoError',
  index: 0,
  code: 9,
  errmsg:
   '\'$pull\' is empty. You must specify a field like so: {$pull: {<field>: ...}}',
  [Symbol(mongoErrorContextSymbol)]: {} }
```

But, this works well when I try to remove the same model from Strapi Admin panel...

**Steps to reproduce the problem**
1.  clone my example repo : https://github.com/gilhardl/strapi-delete-error
2. install dependencies and start the app
3. create the first admin user
4. go to "Roles & Permission" > "Public" and allow all actions for Teams and Supporters
5. create a Team using the Content Manager plugin
6. remove created team using a tool like Postman

**What is the expected behavior?**
Don't return an error

**Comment by lauriejim** [comment]
Thank you @gilhardl  for your issue.
I will take a look soon as possible.

**Comment by lauriejim** [comment]
Okay I reproduce your issue. Will try to work on it soon as I can.

`📝note` this come from this line of code 
https://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/templates/mongoose/service.template#L137

**Comment by gilhardl** [comment]
Hi @lauriejim, thanks to your note I think I've found the problem.

Tell me if I'm wrong, but I think we don't need to update associated documents if the association is dominant.

In my DB I have these Teams : 
```
[
  {
    "_id": "5c61ac15a4b3575eb65dd7fd",
    "label": "A",
    "supporters": [
      "5c619413ed2b674e76cb1d95",
      "5c61942bed2b674e76cb1d97",
      "5c6194de71b29f5396463dbe"
    ],
    "createdAt": "2019-02-11T17:08:37.881Z", 
    "updatedAt":"2019-02-11T17:08:37.899Z",
    "__v":0,
    "id":"5c61ac15a4b3575eb65dd7fd"
  },
{
    "_id":"5c6193c7ed2b674e76cb1d7c",
    "label":"B",
    "supporters": [
      "5c61941bed2b674e76cb1d96",
      "5c6194c371b29f5396463dbc",
      "5c6194de71b29f5396463dbe"
    ],
    "createdAt": "2019-02-11T15:24:55.462Z",
    "updatedAt": "2019-02-11T15:29:34.363Z",
    "__v": 0,
    "id": "5c6193c7ed2b674e76cb1d7c"
  }
]
```
and these Supporters : 
```
[
  {
    "_id": "5c619413ed2b674e76cb1d95",
    "lastname": "A",
    "firstname": "1",
    "createdAt": "2019-02-11T15:26:11.743Z",
    "updatedAt": "2019-02-11T15:26:29.981Z",
    "__v": 0,
    "id": "5c619413ed2b674e76cb1d95"
  },
  {
    "_id": "5c61942bed2b674e76cb1d97",
    "lastname": "A",
    "firstname": "2",
    "createdAt": "2019-02-11T15:26:35.009Z",
    "updatedAt": "2019-02-11T15:26:41.967Z",
    "__v": 0,
    "id": "5c61942bed2b674e76cb1d97"
  },
  {
    "_id": "5c6194de71b29f5396463dbe",
    "lastname": "AB",
    "firstname": "1",
    "createdAt": "2019-02-11T15:29:34.329Z",
    "updatedAt": "2019-02-11T15:29:34.345Z",
    "__v": 0,
    "id": "5c6194de71b29f5396463dbe"
  }
]
```
When we want to delete a Supporter, we have to look in each Team if there is the Supporter in Team's supporters array.
But, on the other side, when we want to delete a Team, we don't have to look into Supporter's teams array because it doesn't exists.

So, in my mind, we just have to return true in associations.map() if association.dominant == true. Line: https://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/templates/mongoose/service.template#L132

**Comment by lauriejim** [comment]
Thank you for your PR. That could be that. I have to take time to check / test that.
