### ISSUE TITLE
Provider checkbox input not met validation requirements providers config

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2734]
**Informations**
- **Node.js version**: node 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.21
- **Database**: mysql
- **Operating system**: Linux

**What is the current behavior?**

Layout very strange and error "This value is required." is displayed

**Steps to reproduce the problem**

1. Create provider with
`
auth: {
  any_field_name: {
    label: 'any_description',
    type: 'checkbox'
  }
}
`
2. Try to save auth config in admin panel

**What is the expected behavior?**

Form should be saved.

**Comment by lauriejim** [comment]
Hello @EpicUsaMan , can you give us the exact steps to reproduce.
Your description is not enough complete to be able to reproduce and help you.

**Comment by EpicUsaMan** [comment]
Hi, @lauriejim 
I create new provider like this:
`
module.exports = {
  provider: 'gmail',
  name: 'Gmail',
  auth: {
    gmail_default_from: {
      label: 'Gmail Default From',
      type: 'text'
    },
    gmail_default_replyto: {
      label: 'Gmail Default Reply-To',
      type: 'text'
    },
    gmail_login: {
        label: 'Gmail login',
        type: 'text'
    },
    with_mjml: {
        label: 'Enable mjml for gmail provider',
        type: 'checkbox'
    },
    gmail_password: {
        label: 'Gmail password',
        type: 'text'
    }
  },
`

But when I try to submit this form I receive next error:

![untitled](https://user-images.githubusercontent.com/18231021/52179405-08c99980-27e3-11e9-8819-8b1bddaef0ac.png)

(Also form have strange/broken layout)

**Comment by garretua** [comment]
Is it possible to mark config fields as optional somehow? Can't find it in the documentation.

**Comment by lauriejim** [comment]
Hello! It's possible, but you will have to customize the admin ConfigPage container of the plugin.
I think we have to add this config (require) in the `auth` object of each provider.

**Comment by lauriejim** [comment]
Hello! Since configurations for email and upload providers are now files, this is no longer an issue.
