### ISSUE TITLE
Payload is too large - when trying to send a json object larger than 1mb

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2737]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.20
- **Database**: mlab
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Hey guys!

When trying to send a json object larget than 1 million bytes to the server, I get the error "payload is too large". The object is infact an array of base64 images, and upon checking its length I can see that above around 1 million bytes, the sending cannot be done.

For some reason, after trying to send the same query a few times, it sometimes gets through successfully.

The object that I'm trying to pass is around 1.3mb

My query:

```
const response = await strapi.request('POST', '/graphql', {
            data: {
              query: `mutation UpdateExam($input: updateExamInput!) {
                updateExam(input: $input) {
                  exam { 
                    questions 
                  }
                }
              }`,
              variables: {
                input: {
                  where: {
                    id: this.props.match.params.id
                  },
                  data: {
                    questions: obj
                  }
                }
              }
            }
          });
```

Which settings should I try to change in order to incrase the maximum payload?
Please notice that I'm not uploading a file, but trying to pass an object.

Thanks a lot in advance

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @omerfaran !
Can you add you npm version and well format your query please, it's not readable like that.

**Comment by omerfaran** [comment]
Hey Lauri thnaks a lot for your help,
I edited as you asked.

Please note that, at least to my knowledge, the query itself is probably not related to the problem.
Also, it might be confusing, but I'm sending a JSON object and not uploading a file.

Thanks in advance,
Omer

**Comment by lauriejim** [comment]
Can you send me the full error message you get please.

**Comment by jacargentina** [comment]
@omerfaran i'm uploading big files to strapi with this configuration:
**Path**: `web-api/config/environments/development/request.json`

```
{
  "session": {
    "enabled": true,
    "client": "cookie",
    "key": "strapi.sid",
    "prefix": "strapi:sess:",
    "secretKeys": ["mySecretKey1", "mySecretKey2"],
    "httpOnly": true,
    "maxAge": 86400000,
    "overwrite": true,
    "signed": false,
    "rolling": false
  },
  "logger": {
    "level": "debug",
    "exposeInContext": true,
    "requests": true
  },
  "parser": {
    "enabled": true,
    "multipart": true,
    "formLimit": "500mb",
    "jsonLimit": "200mb",
    "formidable": {
      "maxFileSize": 524288000
    }
  }
}
```

Is it the solution for your use case?

**Comment by omerfaran** [comment]
Thanks jacargentina I'll check it out!

**Comment by omerfaran** [comment]
Hello jacargentina yes it's working!

Thanks a lot

**Comment by dr-martin** [comment]
Thanks, @jacargentina. This works for me, too.

**Comment by ssshammi** [comment]
Hi am able to post files using postman but not using 64bytes encoded data together with json. I get {"data":null,"error":{"status":413,"name":"PayloadTooLargeError","message":"request entity too large"}}  It is a 1MB audio file using post method to a content endpoint

**Comment by tejasghlade** [comment]
I resolved payload is too large issue on strapi graphql , in REST apis after I configure json limit and formlimit its working but not in graphql strapi in new version. so I find out the solution. and its working great.

config/plugins.js

```
module.exports = {
  graphql: {
    config: {
      endpoint: "/graphql",
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7,
      amountLimit: 2000,
      apolloServer: {
        tracing: false,
        bodyParserConfig: {
          // koa-bodyparser/node_modules/co-body/lib/json.js#36
          limit: "256mb",
          // koa-bodyparser/index.js#69
          formLimit: "256mb",
          jsonLimit: "256mb",
          textLimit: "256mb",
          xmlLimit: "256mb",
        },
      },
    },
  },
};
```

**Comment by GraemeFulton** [comment]
this one worked for me in v4, increasing the `jsonLimit` is the one that did the trick for me..the others not sure:

```
{
    name: 'strapi::body',
    config: {
      jsonLimit: '256mb',
      formLimit: "256mb", // modify form body
      textLimit: "256mb", // modify text body
      formidable: {
        maxFileSize: 250 * 1024 * 1024, // multipart data, modify here limit of uploaded file size
      },
    },
  },
```

**Comment by davidpustai** [comment]
> this one worked for me in v4, increasing the `jsonLimit` is the one that did the trick for me..the others not sure:
> 
> ```
> {
>     name: 'strapi::body',
>     config: {
>       jsonLimit: '256mb',
>       formLimit: "256mb", // modify form body
>       textLimit: "256mb", // modify text body
>       formidable: {
>         maxFileSize: 250 * 1024 * 1024, // multipart data, modify here limit of uploaded file size
>       },
>     },
>   },
> ```

Might save someones time if I say that this goes into `config/middlewares.js`. Just replace the `strapi::body` line that's already there.
