### ISSUE TITLE
Content type builder not saving fields on production heroku

### ISSUE THREAD

**Issue by lukkyjoe** [strapi/strapi#2743]
I browsed through prior issues. My issue seems similar to but not exactly the same as https://github.com/strapi/strapi/issues/1300 and https://github.com/strapi/strapi/issues/487.  Those two issues are also closed and the conversation from those threads did not help me. 

**Informations**
- **Node.js version**: 10.11.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0.alpha.21
- **Database**: heroku mlab add-on; mongod version: 3.6.9
- **Operating system**: macOS 10.14.2
- **(Optional) Link to your Project**: https://github.com/lukkyjoe/myProject

**What is the current behavior?**
After creating a content type, when I try to create and save fields to the content type, it gets an error and the content type fields do not get saved. This happens on a deployed Heroku instance, but not on local. 

After trying to build content type fields, I get a prompt telling me the content type got created. 
![image](https://user-images.githubusercontent.com/6954716/52194107-44765a80-2807-11e9-839d-8ca7c9b57f86.png)

but when I go to the newly created content type, the fields are gone and i'm back to square one. 
![image](https://user-images.githubusercontent.com/6954716/52194054-00835580-2807-11e9-854a-0ea4a8a17ca2.png)

**Steps to reproduce the problem**
1. build new content type
2. add fields to new content type
3. go to new content type to see that they're never saved properly

**What is the expected behavior?**
Create a new content type
Add fields to content type
Save fields
Fields save properly

**Suggested solutions**
For debugging purposes, I don't mind sharing the admin credentials here so you could try it for yourself: 
https://whispering-bastion-91696.herokuapp.com/admin/plugins/users-permissions/auth/login
username is: lukkyjoe
pw is: `b00tStrapi!`

**Comment by derrickmehaffy** [comment]
@lukkyjoe you cannot use the content-type builder on heroku please see: https://github.com/strapi/strapi/wiki/Create-files-on-Heroku

Due to how models are created (new files, modifying files, ect), Heroku can only be used for production.

Marking this as closed

**Comment by hallya** [comment]
@derrickmehaffy so how should we do to create a model and have it available on heroku ?

**Comment by hallya** [comment]
Ok I think I've got it ; I have to create the new model locally then push to heroku the newly created folder located in `/api` and other related files that may have been changed by this creation in the project. 

Am I right ?
