### ISSUE TITLE
function fetchall output in mysql

### ISSUE THREAD

**Issue by rezabojnordi** [strapi/strapi#2744]
**Informations**
- **Node.js version**: 
v10.15.1
using node lts
- **NPM version**: 
6.4.1
- **Strapi version**: 
Version: 3.0.0-alpha.21 (node v10.15.1)
- **Database**: 
mysql-server
Server version: 5.7.25-0ubuntu0.18.04.2 (Ubuntu)
- **Operating system**: 
ubuntu0.18.04.2
- **(Optional) Link to your Project**: 

**What is the current behavior?**
hi. i use this code. but output is not compatible with my NODE JS.
so i have to use another way. i use below code to get array of objects.
 have you any suggestion for this problem?

**Steps to reproduce the problem**
 return strapi.services.posts.fetchAll(ctx.query);

**What is the expected behavior?**
hi. i use this code. but output is not compatible with my NODE JS.
so i have to use another way. i use below code to get array of objects.

[{"id":1,"name":"reza","lname":"bojnordi","phone":3,"information":"noting","created_at":"2019-02-04T08:05:30.000Z","updated_at":"2019-02-04T08:05:31.000Z"}]

 have you any suggestion for this problem?
yes 
using
 let a = JSON.stringify(await strapi.services.posts.fetchAll(ctx.query);)
return JSON.parse(a);

**Suggested solutions**

**Comment by rezabojnordi** [comment]
The output of the function is not a presentation of the objects 

let a = await strapi.services.posts.fetchAll(ctx.query);
      console.log(JSON.stringify(a));
      return strapi.services.posts.fetchAll(ctx.query);

[{"id":1,"name":"reza","lname":"bojnordi","phone":3,"information":"noting","created_at":"2019-02-04T08:05:30.000Z","updated_at":"2019-02-04T08:05:31.000Z"}]

**Comment by rezabojnordi** [comment]
your code output for mysql
`CollectionBase {
  model:
   { [Function]
     super_: [Function: Events],
     extend: [Function: extend],
     extended: [Function: extended],
     __super__:
      constructor {
        hidden: null,
        visible: null,
        toJSON: [Function: toJSON],
        fetchPage: [Function: fetchPage] },
     NotFoundError: [Function: ErrorCtor],
     NoRowsUpdatedError: [Function: ErrorCtor],
     NoRowsDeletedError: [Function: ErrorCtor],
     forge: [Function: forge],
     collection: [Function: collection],
     count: [Function: count],
     fetchAll: [Function: fetchAll],
     where: [Function],
     query: [Function],
     fetchPage: [Function],
     connection: 'default',
     collectionName: 'posts',
     info: { name: 'posts', description: '' },
     options: { increments: true, timestamps: [Array], comment: '' },
     attributes:
      { name: [Object],
        lname: [Object],
        phone: [Object],
        information: [Object] },
     globalId: 'Posts',
     globalName: 'Posts',
     orm: 'bookshelf',
     client: 'mysql',
     primaryKey: 'id',
     primaryKeyType: 'integer',
     associations: [],
     _attributes:
      { name: [Object],
        lname: [Object],
        phone: [Object],
        information: [Object] },
     updateRelations: [AsyncFunction: update] },
  length: 1,
  models:
   [ constructor {
       attributes: [Object],
       _previousAttributes: [Object],
       changed: [Object: null prototype] {},
       relations: {},
       cid: 'c796',
       id: 1,
       _events: [Object],
       _eventsCount: 6 } ],
  _byId:
   [Object: null prototype] {
     '1':
      constructor {
        attributes: [Object],
        _previousAttributes: [Object],
        changed: [Object: null prototype] {},
        relations: {},
        cid: 'c796',
        id: 1,
        _events: [Object],
        _eventsCount: 6 },
     c796:
      constructor {
        attributes: [Object],
        _previousAttributes: [Object],
        changed: [Object: null prototype] {},
        relations: {},
        cid: 'c796',
        id: 1,
        _events: [Object],
        _eventsCount: 6 } },
  _knex: null,
  _events: [Object: null prototype] {},
  _eventsCount: 0 }
`

**Comment by rezabojnordi** [comment]
plz open issue

**Comment by derrickmehaffy** [comment]
Please finish updating your template:
```
Informations

Node.js version: ~~using node lts~~
NPM version: 6.4.1
Strapi version: **Need this**
Database: mysql >=5.
Operating system: linux ubuntu 18.4
``

**Comment by rezabojnordi** [comment]
Informations

Node.js version: **Need this**
NPM version: 
6.4.1
Strapi version: **Need this**
Version: 3.0.0-alpha.21 (node v10.15.1)
Database:
mysql-server
Server version: 5.7.25-0ubuntu0.18.04.2 (Ubuntu)

Operating system: 
ubuntu0.18.04.2

**Comment by lauriejim** [comment]
You have to use `.toJSON()` to convert the bookshelf response in a JSON object.
It's not an issue.

**Comment by rezabojnordi** [comment]
ok thank you :)

**Comment by lauriskuznecovs** [comment]
By the way, latest Strapi does not have method like *fetchAll*

Here is all current methods:
find
findOne
count
create
delete
update
