### ISSUE TITLE
Working content lost when clicking on Author

### ISSUE THREAD

**Issue by adamkhan** [strapi/strapi#2746]
Bonjour,

While editing an entry, I clicked on the selected author's name and was immediately taken to edit that person, losing any work I did on the original entry. It might be good to disable that link or provide a popup asking whether I really want to leave unsaved work.

**Comment by derrickmehaffy** [comment]
@adamkhan please update your original post following the bug report template.

I'm marking this as closed until the required information is added, once you have updated it and replied that you have done so this can be reopened.

Per the bug report template: `<!-- ⚠️ If you do not respect this template your issue will be closed. -->`

**Comment by derrickmehaffy** [comment]
Sure will do, in the future @adamkhan there is a feature request template also. Please do use them where possible, this repo gets a lot of issues/FRs created and I blindly close them if the template isn't there to try and keep it semi-clean
