### ISSUE TITLE
Using `strapi-plugin-upload` with `strapi-provider-upload-local` can leave temp device without  space

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#2752]
**Informations**
- **Node.js version**: v11.9.0
- **NPM version**: 6.5.0
- **Strapi version**:  v3.0.0-alpha.22
- **Database**: mongoDB
- **Operating system**: linux

**What is the current behavior?**
Batch data migration, with lots of files to upload

**Steps to reproduce the problem**
Batch data migration, with lots of files to upload, with a 16gb /tmp partition. After a while, the `/tmp` fs gets full, and the data migration stops with error `No space left on device`

**What is the expected behavior?**
All data migrated fine

**Suggested solutions**
After uploaded files are moved by the plugin to the final destination on `/uploads`, remove them from `/tmp`

**Comment by lauriejim** [comment]
Hello @jacargentina can you update the version of Strapi you use. 
Cause I'm sure the version you test when you create this issue is not the last version of Strapi (since I release yesterday)

**Comment by jacargentina** [comment]
@lauriejim Doing that right now; but what is your motivation? Do you think something on latest release will affect (fix) this issue  ?

**Comment by jacargentina** [comment]
@lauriejim Verified, with latest version **_the issue is there_**, lots of `/tmp/upload_......` files there, not being removed after upload

**Comment by lauriejim** [comment]
Update the version in `* **Strapi version**: current stable sources`

**Comment by jacargentina** [comment]
Hey, done!

**Comment by sercanov** [comment]
I think this issue re-occured. I'm using dockerized containers managed by dokku. There were no space on disk, turned out .tmp folder was sitting on 12gb upload data
![image](https://user-images.githubusercontent.com/10291644/112154613-7e786580-8bf5-11eb-8dc6-e5f72e039ba8.png)

**Comment by derrickmehaffy** [comment]
@sercanov can you open a new issues this one is over 2 years old.

See: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

Specifically:

> You have already searched for related issues, and found none open (if you found a related closed issue, please link to it from your post).

**Comment by tomastoews** [comment]
> @lauriejim Verified, with latest version **_the issue is there_**, lots of `/tmp/upload_......` files there, not being removed after upload

Still in 2024 this issue exists... :(
