### ISSUE TITLE
Cannot execute deep query postgres many to many GraphQL

### ISSUE THREAD

**Issue by giona69** [strapi/strapi#2757]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.7.0
- **Strapi version**: alpha.21
- **Database**: mysql 5.7
- **Operating system**: macosx mojave
- **(Optional) Link to your Project**: https://github.com/giona69/strapi.21.graphql

**What is the current behavior?**

this query will note execute:
in the case of many-to-many relation (ex: modules under courses) it will respond with an empty array, in the case of a one-to-many relation (ex: language under modules) it will give an error “message”: “The operator \“undefined\” is not permitted”
until version strapi.19 it was working.

```
{
  courses {
    name
    modules {
      id
      title
    }
  }
  languages {
    idLang
  }
  modules {
    id
    title
    summary
    language {
      idLang
    }
  }
}
```

**Steps to reproduce the problem**
install strapi version alpha.21
strapi new project
install graphql plugin
create tre content types:
course (has many modules)
module (has one language) 
languages
create two record in languages
create two records in modules and associate to one language each
create one record in course
launch this query

```
{
  courses {
    modules {
      id
    }
  }
  languages {
    id
  }
  modules {
    id
    language {
      id
    }
  }
}
```

**What is the expected behavior?**
should return the query as expected

**Suggested solutions**
must investigate

**Comment by lauriejim** [comment]
We fixed GraphQL stuff in last version (alpha.22) can you confirm it still exist in the last version please.

**Comment by ejalfonzo** [comment]
I am having the same one-to-many relation issue.
**Informations**

* **Node.js version**: 11.8.0
* **NPM version**: 6.50
* **Strapi version**: alpha.22
* **Database**: posgressql
* **Operating system**: macosx mojave
* **(Optional) Link to your Project**: https://github.com/giona69/strapi.21.graphql

Query:
```
{
  categories {
    id
    name
    subcategories {
      id
      name
    }
  }
}
```

Error:
```
{
      "message": "The operator \"undefined\" is not permitted",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "subcategories",
        0,
        "category"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: The operator \"undefined\" is not permitted",
            "    at Formatter.operator (/proj_path/server/node_modules/knex/lib/formatter.js:179:13)",
            "    at QueryCompiler_PG.whereBasic (/proj_path/server/node_modules/knex/lib/query/compiler.js:567:100)",
            "    at QueryCompiler_PG.where (/proj_path/server/node_modules/knex/lib/query/compiler.js:350:34)",
            "    at components.map.component (/proj_path/server/node_modules/knex/lib/query/compiler.js:96:67)",
            "    at Array.map (<anonymous>)",
            "    at QueryCompiler_PG.select (/proj_path/server/node_modules/knex/lib/query/compiler.js:96:35)",
            "    at QueryCompiler_PG.toSQL (/proj_path/server/node_modules/knex/lib/query/compiler.js:50:29)",
            "    at Builder.toSQL (/proj_path/server/node_modules/knex/lib/query/builder.js:72:44)",
            "    at /proj_path/server/node_modules/knex/lib/runner.js:37:34",
            "    at processImmediate (timers.js:632:19)",
            "    at process.topLevelDomainCallback (domain.js:120:23)",
            "From previous event:",
            "    at Runner.run (/proj_path/server/node_modules/knex/lib/runner.js:33:30)",
            "    at Builder.Target.then (/proj_path/server/node_modules/knex/lib/interface.js:23:43)"
          ]
        }
      }
    }
```

Response
```
"data": {
    "categories": [
      {
        "id": "2",
        "name": "Category 1",
        "subcategories": null
      },
      {
        "id": "1",
        "name": "Category 1",
        "subcategories": null
      }
    ]
  }
```

**Comment by giona69** [comment]
With alpha 22?

I’m trying to upgrade now

**Comment by giona69** [comment]
I just upgraded to alpha.22 and now it is working on my side 👍

**Comment by kenberkeley** [comment]
alpha.22, same issue

**Comment by kenberkeley** [comment]
@lauriejim May I ask, is this bug confirmed?

**Comment by giona69** [comment]
maybe this is on postgres? I tried with mysql & sqllite and it works, both with a scratch project and upgrding an existing project on my side

**Comment by giona69** [comment]
no in effect doesn't work in sqllite too here is an example scratch https://github.com/giona69/strapi.22

**Comment by giona69** [comment]
ok I got it, one-to-many is working, and many-to-many still not working. also we have this bug open too https://github.com/strapi/strapi/issues/2771 so for the moment as for alpha.22 graphql is not usable. last version that I can use is alpha.19

**Comment by lauriejim** [comment]
Yap it's confirmed, I tried your steps and it's a bug ya

**Comment by juandav** [comment]
I have the same bug and I have to do custom schemas while not fix.

**Comment by giona69** [comment]
hi guys any news on this?

**Comment by derrickmehaffy** [comment]
@giona69 no news, you'll see a PR linked when it is being worked on

**Comment by lauriejim** [comment]
It have been fixed in last version of Strapi `alpha.16`
