### ISSUE TITLE
Rename link to Strapi Documentation link on adminUI

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2758]
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: v19 (also with v20/v21
- **Database**: MySQL
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: N/A

**What is the current behavior?**

Link to Strapi docs and Swagger plugin are too similar: 
![image](https://user-images.githubusercontent.com/8593673/52257077-6db1ec00-28d6-11e9-98e7-010cf0d85a2d.png)

**Steps to reproduce the problem**

N/A Fresh project

**What is the expected behavior?**

Should rename one or the other as could cause confusion to end users

**Suggested solutions**

Rename `Documentation` to something like `Strapi Docs`

**Comment by derrickmehaffy** [comment]
Alternative rename the swagger link to `Swagger Docs`, `OpenAPI Docs`, or `Auto Documentation`

**Comment by derrickmehaffy** [comment]
@soupette thoughts?

**Comment by soupette** [comment]
What about API documentation?

**Comment by derrickmehaffy** [comment]
Fine with me @soupette just had someone ask me which one was our swagger and it made sense.

**Comment by lauriejim** [comment]
We need @Aurelsicoko feedback on this point.

**Comment by derrickmehaffy** [comment]
side note, the way the scrollbar shows up is also a tad ugly in my opinion, I'm wondering if it would be better just to add it into the scroll menu instead of it's own separate container

**Comment by Aurelsicoko** [comment]
The link "Documentation" at the bottom of the menu is going to be removed in a few weeks. So don't worry about this issue anymore 🙈
