### ISSUE TITLE
Resolver in String is not working in custom GraphQL

### ISSUE THREAD

**Issue by cc07** [strapi/strapi#2766]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: strapi@3.0.0-alpha.21
- **Database**: mongo
- **Operating system**: Mac OS

**What is the current behavior?**
Even a string is defined in custom graphql schema, it did nothing when executing the mutation and no error reported.

**Steps to reproduce the problem** 
1. Setup custom graphql schema in ./api/**/config/schema.graphql
```
resolver: {
    Mutation: {
      sendPromotion: {
        description: 'Send promotion coupon to customer',
        resolver: 'Promotion.send'
      }
    }
  },
```
2. Run the graphql mutation

**What is the expected behavior?**
It will executed `send` function defined in `Promotion` controller.

**Suggested solutions**
It works after i modified some changes in the GraphQL plugin
Schema.js:211
```
case 'Mutation':
              // TODO: Verify this...
              acc[type][resolver] = Mutation.composeMutationResolver(
                strapi.plugins.graphql.config._schema.graphql,
                plugin,
                acc[type][resolver],
              );
              break;
```

Mutation.js
```
const controller = _.get(
        controllers,
        action !== undefined
          ? `${name}.${action === 'delete' ? 'destroy' : action}`
          : _.toLower(name),
      );
```

Clearly, it is not a sophisticated fix, please advise an appropriate solution.

**Comment by lauriejim** [comment]
Can you give me the error you get please.

**Comment by cc07** [comment]
> Can you give me the error you get please.

When i called the mutation, it just returned null without any error.

**Comment by lauriejim** [comment]
Can you give me a screenshot of you GraphQL Playground please.

**Comment by cc07** [comment]
<img width="1305" alt="screenshot 2019-02-13 at 5 41 14 pm" src="https://user-images.githubusercontent.com/26186634/52702118-9ad95b00-2fb6-11e9-8abf-f1451a7cf977.png">

**Comment by nikosolihin** [comment]
I can confirm this issue on a fresh strapi install.

- Node.js version: v10.15.0
- NPM version: 6.9.0
- Strapi version: strapi@3.0.0-alpha.24.1
- Database: mongo
- Operating system: Mac OS

In `./api/**/config/schema.graphql` this works:
```
resolver: {
    Mutation: {
      sendPromotion: {
        resolver: strapi.controllers.promotion.send
        resolver: 'Promotion.send'  // <----  but not this
      }
    }
  }
```

**Comment by lauriejim** [comment]
Thank you for this details.

**Comment by nikosolihin** [comment]
I found that custom resolvers like `'Promotion.send'` remains a string during schema generation and never points to an actual controller function because `queryName` always includes the variable `action` which in the case of custom resolvers is undefined: 

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L40

This affects policies(#1887) and resolver function retrieval(#2973):

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L43

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L57

The fix is a simple conditional based on the presence of `action`:
```const queryName = action ? `${action}${_.capitalize(name)}` : `${name}`;```

**Comment by daymont87** [comment]
@nikosolihin I also found that if i call in resolver default (autogenerated) functions from api/mymodel/controllers/mymodel.js, for example "find: async (ctx)"

```
resolver: (obj, options, context) => {
          return Mpack.find(obj);
        }
```
it works fine, but if i create custom function, for example "getPacks" (even with the same code that default "find: async (ctx)" function) - i getting an error "TypeError: Pack.getPacks is not a function". 

Is it also a bug, or i do something wrong?

**Comment by sberryman** [comment]
Still seeing this issue on beta 12. The resolver never gets executed using a graphql mutation but works fine using an http post against the controller. Graphql simply returns `null`.
