### ISSUE TITLE
strapi-provider-upload-aws-s3 is out of date on npm

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2768]
According to https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.21-to-alpha.22.html#update-aws-s3-provider , the S3 plugin should be updated. However, the current version is still `3.0.0-alpha.15`, I have to `npm i -S strapi-provider-upload-aws-s3@3.0.0-alpha.22` manually.

**Comment by lauriejim** [comment]
Hello @kenberkeley !
If you check the documentation here https://strapi.io/documentation/3.x.x/guides/upload.html#install-providers we note if you use one provider located in the mono repo you will have to use `@alpha`
But I'm ok it's not intuitive. We will try to update that.
