### ISSUE TITLE
Hour/Minutes/Seconds field in DatePicker exhibit unexpected behavior

### ISSUE THREAD

**Issue by fabricioanciaes** [strapi/strapi#2774]
**Informations**
- **Node.js version**: 10.0.0
- **NPM version**: 6.0.0
- **Strapi version**: strapi@3.0.0-alpha.22
- **Database**: MongoDB 
- **Operating system**: Linux through windows (WSL), production is on heroku
- **(Optional) Link to your Project**: https://github.com/fabricioanciaes/fighthub-api

**What is the current behavior?**
Input dates aren't working right. Increments only occour on large steps. Minutes and seconds also increments hours

**Steps to reproduce the problem**

![Footage of the problem](https://camo.githubusercontent.com/762b7809ff4385663e36b9047c87b61e21532b55/68747470733a2f2f692e696d6775722e636f6d2f30326b32364d742e676966)

Issue still persists to me even after updating.

**What is the expected behavior?**
Hours,minutes and seconds should be only incremented and decremented by 1 for each click.
Minutes and seconds shouldn't increment hours.

**Suggested solutions**

This issue was reported before the alpha 22 release. #1960 
There was a PR that fixes it and it was merged into the alpha22 release: #2659

The issue still persists to me for some reason.

I should also mention that I'm on UTC-2 (Brazil: Brasília). Not sure if this have any relation to the bug.

**Comment by lauriejim** [comment]
I see your `strapi-hook-mongoose` is on `alpha.17` version.
So you juste `strapi` version but you don't follow migrations guide.
https://strapi.io/documentation/3.x.x/migration-guide/

**Comment by remi2j** [comment]
I'm still having this issue.
From my `package.json`
```
"strapi": "^3.0.0-alpha.25.2",
"strapi-hook-mongoose": "^3.0.0-alpha.25.2"
```

**Comment by remi2j** [comment]
I've got a recording of this bug:
https://www.useloom.com/share/7e3a8be8747e468e8e34006ef667bacc

It's basically impossible to set the date and time correctly, making my app unusable.

**Comment by lauriejim** [comment]
Hello @remi2j !
I think you did not update your plugins.

**Comment by remi2j** [comment]
@lauriejim You're right, it's working now.

**Comment by remi2j** [comment]
@lauriejim Why did you reopen the issue ? Did it happen again ? It's working fine for me now.

**Comment by lauriejim** [comment]
Miss click I think!
