### ISSUE TITLE
strapi new doesn't seem to use updated local plugins

### ISSUE THREAD

**Issue by krsnaa** [strapi/strapi#2777]
**Informations**
- **Node.js version**: v11.9.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.22
- **Database**: mongoDB
- **Operating system**: Mac OS X
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I follow the progression to create a clean installation:

- git clone https://github.com/strapi/strapi.git
- npm run setup
- strapi -v -> 3.0.0-alpha.22

then, I create a dev project to modify the admin and other plugins
- strapi new strapi-dev --dev
- cd strapi-dev
- strapi start 
- cd strapi-dev/admin
- npm start 
- navigate to http://localhost:4000/admin -> shows the changes in effect in the admin UI and the plugin UI

then, I build the plugins using:
- npm run setup --plugins -> I can see the build folders getting created in the plugins' folders

then, I try to use these updated plugins in my production project
- strapi new strapi-production -> everything works 
- cd strapi-production
- strapi start

At this point, I still see the old plugin UI and not the updated UI/functionality.

I tried looking into this more deeply and see that the plugin installation is handled by  ⁨strapi ▸ ⁨packages⁩ ▸ ⁨strapi⁩ ▸ ⁨bin⁩ ▸ ⁨strapi-install.js and it is installing them using npm or yarn.

`npm install ${pluginID}@${packageJSON.version} --ignore-scripts --no-save --prefix ${pluginPath}` or 
`yarn --cwd ${pluginPath} add ${pluginID}@${packageJSON.version} --ignore-scripts --no-save`

And the reason that it appears to work in --dev mode is because it links to the built plugins: `fs.symlinkSync(path.resolve(__dirname, '..', '..', pluginID), path.resolve(process.cwd(), pluginPath), 'dir');`

**What is the expected behavior?**

I would have thought that `strapi new` would make use of the updated plugins.

Guidance appreciated on what the expected behavior is and how to deploy modified/custom plugins.

**Comment by lauriejim** [comment]
if you want to have your `dev` update in a production app, you will have to manually copy and paste your `packages/strapi-plugins...` in the `plugins` folder of your new application.
