### ISSUE TITLE
Cannot restart strapi after strapi freeze when adding new content type

### ISSUE THREAD

**Issue by izzuddinnatsir** [strapi/strapi#2778]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: MongoDB v4.0.6
- **Operating system**: Centos 7.5
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When I start strapi app in development mode it will show these lines and failed:

```
(node:3148) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: near "ALTER": syntax error
    at Client_SQLite3._query (/home/natsi/kabobs-admin/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/home/natsi/kabobs-admin/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/home/natsi/kabobs-admin/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /home/natsi/kabobs-admin/node_modules/knex/lib/runner.js:47:21
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (/home/natsi/kabobs-admin/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/home/natsi/kabobs-admin/node_modules/knex/lib/interface.js:23:43)
(node:3148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-07T03:17:13.058Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-07T03:17:13.060Z] error (hook:bookshelf) takes too long to load
```

**Steps to reproduce the problem**
Loading forever when adding new data type in UI (the name of the new data type include '&'), force stop strapi, restart strapi.

**What is the expected behavior?**
It should not freeze when adding new data type. And I should be able to restart strapi when that happens.

**Suggested solutions**
I don't know, Need help please. Thanks.

**Comment by izzuddinnatsir** [comment]
The hook:bookshelf is not the problem, I already change it to 20 seconds but still failed. I only have 7 data types created. Hope this information makes it clearer.

**Comment by lauriejim** [comment]
Hello @izzuddinnatsir !

I don't understand why you have `bookshelf` installed. 
You look using Mongo database so you user `mongoose` and you have a `SQLITE_ERROR` error.

It look strange.

I need more info about your app and what you did.

**Comment by natsirizzuddin** [comment]
Hello @lauriejim, thanks for responding. But I'm so sorry I already delete the app to continue my project. But here is what I did:
1. Install mongodb and start mongo as root user on Centos 7.5
2. Install strapi globally as root, than start a new app as non-sudoer user
3. Install graphql and downgrade the version to 0.13.2 and install nginx as reverse proxy for localhost:1337
4. Start Strapi in development mode using PM2 by creating start_strapi.sh file containing strapi start command
5. Create my first user
6. Creating content types, at first it run smoothly.
7. It freeze when I tried to save a Content Type with fields: 'Posisi' and 'Deskripsi&Kualiafikasi'
8. The usual popup window saying it need to restart to save the new content type was keep loading
9. I decide to close the browser window and try to access it again but it keep showing nginx code 5 error
10. I decide to stop strapi on pm2 and start it manually with strapi start
11. Then the above error message is showing and strapi refuse to start

**Comment by natsirizzuddin** [comment]
Now I'm running Strapi on docker container and setting up SEL according to Juriy video on youtube, because he said it needed for nginx to run properly. But I dont think SEL is related to strapi error based on what displayed in the message. I also do not understand why it shows sqlite error while I'm using mongodb

**Comment by codivist** [comment]
I'm getting the same error. I followed the quick start guide and was on this step https://strapi.io/documentation/3.x.x/getting-started/quick-start.html#_3-create-a-content-type when it restarted from saving it threw that error and now I can't get it to start back up.

I'm running in Mac OS X 10.14.2 not in a docker container. Just following the quickstart guide so `hook:bookshelf` was installed with strapi as I did not install it.

**Comment by lauriejim** [comment]
Please not use PM2 in dev mode, that could be the source of the issue.

**Comment by lauriejim** [comment]
@codivist I what is the db you use ?

**Comment by codivist** [comment]
Mongo

**Comment by lauriejim** [comment]
Something is wrong here.

You can not have `Error: SQLITE_ERROR: near "ALTER"` error if you are using a Mongo database.
This error come from `strapi-hook-bookshelf` that is used for SQL databases (Postgre, Mysql and SQLite).

But I find the cause of the error log but it's for SQL applications not Mongo.
https://github.com/strapi/strapi/issues/2794

**Comment by derrickmehaffy** [comment]
@lauriejim If I had to guess this user generated their project with bookshelf first, then switched over to mongo. @codivist can you please start a new project and set it up with mongo

**Comment by shoan** [comment]
I am having the same problem when adding a new field to an existing content type.

**Comment by natsirizzuddin** [comment]
@lauriejim Noted, thanks!

**Comment by deck1187hw** [comment]
Same issue here, using mongo, but still getting `(node:18232) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: near "ALTER": syntax error
    at Client_SQLite3._query (/var/www/gdadmin/gdcms/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/var/www/gdadmin/gdcms/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/var/www/gdadmin/gdcms/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /var/www/gdadmin/gdcms/node_modules/knex/lib/runner.js:47:21
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (/var/www/gdadmin/gdcms/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/var/www/gdadmin/gdcms/node_modules/knex/lib/interface.js:23:43)
(node:18232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-10T10:47:37.896Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-10T10:47:37.897Z] error (hook:bookshelf) takes too long to load`

**Comment by shoan** [comment]
Steps to reproduce:

1. Install strapi as per the documentation. I installed version 3.0.0-alpha.23.1
1. Create the admin account
2. Create a content type. I created Book.
3. Add a single string field. I created Name.
4. Create a record.
5. Edit the Book content type and add a WYSIWYG Text field. 
6. The server does not restart after hitting save.

[2019-02-11T02:41:18.868Z] info The server is restarting

```
(node:11707) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: near "ALTER": syntax error
    at Client_SQLite3._query (/Volumes/Home/Users/shoan/Projects/ptl-strapi-bug-three/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/Volumes/Home/Users/shoan/Projects/ptl-strapi-bug-three/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Volumes/Home/Users/shoan/Projects/ptl-strapi-bug-three/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Volumes/Home/Users/shoan/Projects/ptl-strapi-bug-three/node_modules/knex/lib/runner.js:47:21
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (/Volumes/Home/Users/shoan/Projects/ptl-strapi-bug-three/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/Volumes/Home/Users/shoan/Projects/ptl-strapi-bug-three/node_modules/knex/lib/interface.js:23:43)
(node:11707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-11T02:41:24.319Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-11T02:41:24.320Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load

```

**Comment by codivist** [comment]
@derrickmehaffy set up a new one with just Mongo and added a content type WITHOUT the wysiwyg field and it worked. Added the wysiwyg field and it gives me the bookshelf error.

**Comment by lauriejim** [comment]
@codivist  & @shoan did you use Mongo as database ?

**Comment by derrickmehaffy** [comment]
I think what @lauriejim is asking did you choose custom -> Mongo instead of quickstart (which I believe uses SQLite)

**Comment by shoan** [comment]
@lauriejim @derrickmehaffy I used the default Quickstart option. I am assuming this is sqlite.

**Comment by GeorgWa** [comment]
Had the same error installing strapi, on a fresh, clean quickstart installation.
```
> strapi start
(node:5376) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: near "ALTER": syntax error
    at Client_SQLite3._query (C:\...\node_modules\knex\lib\dialects\sqlite3\index.js:108:12)
    at Client_SQLite3.query (C:\...\node_modules\knex\lib\client.js:192:17)
    at Runner.<anonymous> (C:\...\node_modules\knex\lib\runner.js:138:36)
From previous event:
    at C:\...\node_modules\knex\lib\runner.js:47:21
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (C:\...\node_modules\knex\lib\runner.js:33:30)
    at Raw.Target.then (C:\...\node_modules\knex\lib\interface.js:23:43)
(node:5376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-11T15:14:14.312Z] debug ⛔️ Server wasn't able to start properly.
[2019-02-11T15:14:14.315Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
```

**Comment by natsirizzuddin** [comment]
It seems the quickstart installation need to be avoided for now.

**Comment by dnszero** [comment]
I'm having the same issue as @shoan.

strapi 3.0.0-alpha.23.1
node 10.15.0
macos 10.13.6

1. Made a new project with quickstart.
2. Created a content type and added 3 string fields.
3. Created a quick test entry for it.
4. Deleted the third field, re-added it as text with WYSIWIG checked and hit Save.
5. Strapi crashed and won't restart (same error output as above).

**Comment by dkb868** [comment]
Same error using Quickstart and adding a number field to a new content type.

**Comment by shoan** [comment]
I can confirm that the problem is limited to the quickstart. If you choose Custom and enter the database details, everything appears to work as expected.

**Comment by lauriejim** [comment]
If you are using the quickstart way, we know that and we open a PR to fix that.
Here the issue is if you use Mongo database and you have this issue. That is not normal.

**Comment by narkowicz** [comment]
@lauriejim thanks for update - I couldn't find the PR - could you link so we can track progress? Currently assessing using Strapi and hit this issue. Cheers.

**Comment by MarcelBlockchain** [comment]
> I'm having the same issue as @shoan.
> 
> strapi 3.0.0-alpha.23.1
> node 10.15.0
> macos 10.13.6
> 
> 1. Made a new project with quickstart.
> 2. Created a content type and added 3 string fields.
> 3. Created a quick test entry for it.
> 4. Deleted the third field, re-added it as text with WYSIWIG checked and hit Save.
> 5. Strapi crashed and won't restart (same error output as above).

same

**Comment by lauriejim** [comment]
Please update to the last version of Strapi @MarcelBlockchain (alpha.24.1)

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by MarcelBlockchain** [comment]
Works now. The one thing I did differently is that I first installed GraphQL and then added the new content type. Cannot say it was also because of an update, because I think it was already installed. Thanks for asking
