### ISSUE TITLE
Lifecycle methods not firing - beforeUpdate, afterUpdate, beforeDestroy, afterDestroy

### ISSUE THREAD

**Issue by krsnaa** [strapi/strapi#2779]
**Informations**
- **Node.js version**: * v11.9.0
- **NPM version**: * 6.5.0
- **Strapi version**: * 3.0.0-alpha.22
- **Database**: mongoDB
- **Operating system**: * Mac OSX

**What is the current behavior?**

In 3.0.0-alpha.22, before/afterUpdate lifecycle methods do not fire when updating a value using the content manager or using a PUT request.

before/afterDestroy do not fire when deleting using the UI, but they work when sending a DELETE request.

Very frustrating when trying to implement a websocket model to sync with downstream systems as there is no data consistency anymore.

**Comment by krsnaa** [comment]
https://github.com/strapi/strapi/issues/1443

**Comment by krsnaa** [comment]
Testing the same setup with the SQLite backend works *PERFECTLY*.  
What would it take to get the same level of reliability on the mongoDB backend?

**Comment by lauriejim** [comment]
I will close this issue because it's the same topic as the issue you link.

But it's because of Mongoose and Bookshelf function we use.
The life cycle is based on Mongoose and Bookshelf function and not on Strapi actions.

We have to harmonize all of this stuff.

**Comment by krsnaa** [comment]
@lauriejim, how does it explain the difference in the behavior of lifecycle methods between different versions of STRAPI (on the same mongo backend)? For instance, the beforeUpdate and afterUpdate will fire on alpha.21, but afterSave will not.

**Comment by lauriejim** [comment]
I think it's related to the update we did here https://github.com/strapi/strapi/pull/2682
