### ISSUE TITLE
View issue after editing connection without modification

### ISSUE THREAD

**Issue by edimitchel** [strapi/strapi#278]
**Node.js version**:
5.4.2
**npm version**:
v8.6.0
**Strapi version**:
3.0.0-alpha.6.3
**Operating system**:
CentOS 7

On save of an existing connection but no modification applied, modal is blocked and loading button still alive.

![image](https://user-images.githubusercontent.com/2922851/31619041-e77c9c20-b293-11e7-81b2-36e51394629a.png)

**Comment by soupette** [comment]
Thank you for your feedback! This should be fixed in alpha.7 (https://github.com/strapi/strapi/pull/277/commits/fb3e78245eb471e9062a07997e53551c0626f212)

I'm closing the issue, it should be available in the next release.
