### ISSUE TITLE
Not Supporting MySql 8 caching_sha2_password authentication type

### ISSUE THREAD

**Issue by puneetverma05** [strapi/strapi#2782]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**:3.0.0-alpha.22
- **Database**: MySql
- **Operating system**: Ubuntu 18.10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
ER_NOT_SUPPORTED_AUTH_MODE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Steps to reproduce the problem**
Create new project with strapi using MySql as Database.

**What is the expected behavior?**
Generate the new project.

**Suggested solutions**
Needed Support for New Auth Mode that comes with MySql 8 (caching_sha2_password)

**Comment by lauriejim** [comment]
Hello @puneetverma05 !
Thank y ou for this issue.

Can you give me the full error you get.

Can you please investigate on this issue and submit a PR to fix it.
Will appreciate your contribution!

**Comment by puneetverma05** [comment]
Sure, Will do @lauriejim  :) now I just revert back to Standard Auth, but the following issue still persists #2790

**Comment by dominusbelial** [comment]
i'm getting the same error, same scenario on my ubuntu machine, node version 11.10 npm 6.7

**Comment by derrickmehaffy** [comment]
This is an upstream issue with MySQL.

@dominusbelial in the mean time you are welcome to use MariaDB 10.3 which is a drop in replacement of MySQL 8 (supports all the same features). The alternative is to drop your MySQL version.

**Comment by derrickmehaffy** [comment]
Example of another package with similar problems: https://github.com/mysqljs/mysql/pull/1962

**Comment by dominusbelial** [comment]
> This is an upstream issue with MySQL.
> 
> @dominusbelial in the mean time you are welcome to use MariaDB 10.3 which is a drop in replacement of MySQL 8 (supports all the same features). The alternative is to drop your MySQL version.

thank you for your quick response, i will try with mariadb.

**Comment by dominusbelial** [comment]
> This is an upstream issue with MySQL.
> 
> @dominusbelial in the mean time you are welcome to use MariaDB 10.3 which is a drop in replacement of MySQL 8 (supports all the same features). The alternative is to drop your MySQL version.

it works, creating new content type updates db! and moving to MariaDB is a valid option for me, thank you.

**Comment by derrickmehaffy** [comment]
@dominusbelial For your info (and others who come across this)

Provided by MariaDB a comparison between the two versions: https://mariadb.com/kb/en/library/function-differences-between-mariadb-103-and-mysql-80/

**Comment by derrickmehaffy** [comment]
Also for any incompatibilities between them: https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/

**Comment by dominusbelial** [comment]
while it does work using the recommended settings workflow, if i try to create a clean strapi-site using the MySql option with same credentials, it will return "Database connection has failed! Make sure your "cmsmaria" database exist." , database does exist.

**Comment by derrickmehaffy** [comment]
@dominusbelial are you on the slack?

**Comment by dominusbelial** [comment]
> @dominusbelial are you on the slack?
no, im just following 'Cooking a Deliveroo clone', but i would love to have all the strapi tables ...user,roles,and all other cms related tables (sqlite), within the same mysql database, is this possible?

**Comment by derrickmehaffy** [comment]
Yes @dominusbelial you should join the slack, easier to provide support. So we aren't spamming a bunch of people with github emails.

https://slack.strapi.io
