### ISSUE TITLE
Can't save entry with empty input date

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2783]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: v6.7.0
- **Strapi version**: v3.0.0-alpha.23
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

After update to `v3.0.0-alpha.22` (also after update `v3.0.0-alpha.23`):
When I click on the Save button from an existed User, it doesn't work:

<img width="687" alt="screenshot 2019-02-06 at 22 59 32" src="https://user-images.githubusercontent.com/1007051/52406868-0a3ede80-2acf-11e9-9e3e-29b2d9f49856.png">

> TypeError: Cannot read property 'payload' of undefined

**Steps to reproduce the problem**

Create a project and add this to the User model attributes:

```json
"birthdate": {
  "default": "",
  "type": "date"
},
```

**What is the expected behavior?**

Working :)

**Comment by lauriejim** [comment]
Sorry for this trouble @abdonrd .
If I create an app from `alpha.23` and follow you steps, it works well.

I think it come from the migration, we miss something.
https://github.com/strapi/strapi/pull/2659/files
Here is update on the `alpha.22` aboute dates.

**Comment by abdonrd** [comment]
It's a bit strange, but it seems that after updating the User model from the Content Manager of the admin panel... it works well again 🤷‍♂️

**Comment by abdonrd** [comment]
Ouch! Now I have the same issue with other models. 😢

**Comment by derrickmehaffy** [comment]
@abdonrd likely related to the content manager, delete the schema, restart the server. Then go into content manager plugin -> Users -> Remove the following:

List View: Password
Edit View: Provider

After that it should work

**Comment by abdonrd** [comment]
@derrickmehaffy thanks, but I just did that and it still doesn't work. 😕 
Maybe I had a false positive.

**Comment by lauriejim** [comment]
Maybe @soupette will be able to help you.

**Comment by soupette** [comment]
I'm unable to reproduce the bug on my side what I can tell you is that the error is coming from these lines: https://github.com/strapi/strapi/blob/34ff5a3680ab95472f4511aa8fa84fce800267aa/packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js#L158-L173

**Comment by abdonrd** [comment]
Ouch :/

How can I debug this? As it is in `admin/src/` I guess it does not run, and it runs the `admin/build/`.

**Comment by abdonrd** [comment]
@lauriejim @soupette I just created a new project with Strapi `v3.0.0-alpha.23`.

1. Register the root user.
2. Go to the edit user view. Change email and click "Save" button. It works!
3. Add new user field (`birthdate`) from the Content Type Builder. It adds to the `User.settings.json`:
```
    "birthdate": {
      "default": "",
      "type": "date"
    }
```
4. The server auto-restarts.
5. Go to the edit user view. Change email and click "Save" button. It doesn't work! 😢 

<img width="771" alt="screenshot 2019-02-14 at 02 24 49" src="https://user-images.githubusercontent.com/1007051/52755862-b74db580-2fff-11e9-88b5-4556fc0c455b.png">

**Comment by lauriejim** [comment]
Ho okay, it's caused by the empty value of the date input.

**Comment by abdonrd** [comment]
@lauriejim Your welcome! Right now it affects a couple of my projects, so it's been easy to locate.

**Comment by vince1995** [comment]
I have the same error but in a content type object.

**Comment by abdonrd** [comment]
Any news?

I would like to be able to update version `v3.0.0-alpha.21` of several applications.

Thanks in advance!

**Comment by kenberkeley** [comment]
Same issue here, thanks for this issue

**Comment by roghernandez** [comment]
I'm getting this in one of my projects as well

**Comment by lauriejim** [comment]
This issue is fixed in the last version of Strapi (alpha.26)
