### ISSUE TITLE
Error: Cannot find module strapi/lib/utils/success.js

### ISSUE THREAD

**Issue by ahmed-hyd** [strapi/strapi#2787]
**Informations**
- **Node.js version**: 10.0.0
- **NPM version**:  6.7.0
- **Strapi version**: 3.0.0
- **Database**:  SQL Server
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I am trying to install STRAPI using npm install strapi@alpha -g and the installation is failing with the following error:
npm WARN deprecated joi@10.2.2: This version is no longer maintained. Please upgrade to the latest version.
/root/.nvm/versions/node/v10.0.0/bin/strapi -> /root/.nvm/versions/node/v10.0.0/lib/node_modules/strapi/bin/strapi.js

> strapi@3.0.0-alpha.23.1 postinstall /root/.nvm/versions/node/v10.0.0/lib/node_modules/strapi
> node lib/utils/success.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/node/v10.0.0/lib/node_modules/strapi/lib/utils/success.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm WARN react-ga@2.5.7 requires a peer of prop-types@^15.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ga@2.5.7 requires a peer of react@^15.6.2 || ^16.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 8
npm ERR! strapi@3.0.0-alpha.23.1 postinstall: `node lib/utils/success.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the strapi@3.0.0-alpha.23.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-07T17_22_25_780Z-debug.log

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @ahmed-hyd can you precise the version of Strapi you use.
What is the `alpha` ?

**Comment by lauriejim** [comment]
And can you give me the full log please.

**Comment by lauriejim** [comment]
Can you try to re-run `npm i strapi@alpha -g` and let me know if the issue still happen

**Comment by ahmed-hyd** [comment]
I tried to re-run `npm i strapi@alpha -g` but I still faced the same issue.

Attaching below the logs for your reference.

[2019-02-08T14_43_02_570Z-debug.log](https://github.com/strapi/strapi/files/2845577/2019-02-08T14_43_02_570Z-debug.log)

**Comment by lauriejim** [comment]
Are you behind a poxy ?

**Comment by ahmed-hyd** [comment]
No, this is on an Amazon EC2 instance.

**Comment by lauriejim** [comment]
I just tried and it works well.
- New AWS instance
- Install Node 10
- Install MySQL 8
- Install Strapi alpha.23.1
- Generate new app ✅

**Comment by ahmed-hyd** [comment]
I was able to successfully install Strapi alpha.19. I will work with it for 
Thanks,

**Comment by davixyz** [comment]
I also got this issue, I can confirm that I was able to install only alpha.19; Not the latest. Same error.
This was on Digital Ocean droplet

**Comment by optimalbliss** [comment]
> I also got this issue, I can confirm that I was able to install only alpha.19; Not the latest. Same error.
> This was on Digital Ocean droplet

I have the same issue with alpha 24.
Digital Ocean, Ubuntu 18.04.2 x64, Node.js v10.15.2.

```
134.209.128.36 > npm ERR! file sh
134.209.128.36 > npm ERR! code ELIFECYCLE
134.209.128.36 > npm ERR! errno ENOENT
134.209.128.36 > npm ERR! syscall spawn
134.209.128.36 > npm ERR! strapi@3.0.0-alpha.24 postinstall: `node lib/utils/success.js`
134.209.128.36 > npm ERR! spawn ENOENT
134.209.128.36 > npm ERR!
134.209.128.36 > npm ERR! Failed at the strapi@3.0.0-alpha.24 postinstall script.
134.209.128.36 > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by paescuj** [comment]
Same here on Ubuntu 18.04, 3.0.0-alpha.24.1.
Apparently "unsafe-perm = true" is required for it to work. 
See https://github.com/strapi/strapi-docker/blob/master/Dockerfile.

**Comment by tjmichelin** [comment]
Same problem here. Tried on a fresh installation of Ubuntu 18.04 x64, Strapi 3.0.0-alpha.25.2, Nodejs 10.15.3 and NPM 6.4.1.

**Comment by qivhou** [comment]
Thanks @paescuj !!!

@tjmichelin ,you can add following code in you `~/.npmrc` , it's working for me on latest strapi @3.0.0-alpha.26.2

```
unsafe-perm=true
```
