### ISSUE TITLE
GraphQL cannot update user

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2788]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23
- **Database**: mongodb
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I was trying to updateUser in Graphql and it didn't work. After seeing this thread:
https://github.com/strapi/strapi/issues/2327

I upgraded strapi to the latest version. I hope I did everything correctly, the strapi admin panel works and I see the version as the latest.

I'm trying to update a user:

```
mutation {
  updateUser(input: {
    where: {
      id: "5c43cd1fa2980a09b46e7760"
    },
    data: {
      username: "newname"
      email:"gf@gmail.com" 
    }
  }) {
    user {
      username
      email
    }
  }
}
```

And getting the error:  values.hasOwnProperty is not a function

Full message:

```
{
  "error": {
    "errors": [
      {
        "message": "Bad Request",
        "locations": [
          {
            "line": 3,
            "column": 5
          }
        ],
        "path": [
          "updateUser",
          "user"
        ],
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "data": "values.hasOwnProperty is not a function",
            "isBoom": true,
            "isServer": false,
            "output": {
              "statusCode": 400,
              "payload": {
                "statusCode": 400,
                "error": "Bad Request",
                "message": "Bad Request"
              },
              "headers": {}
            },
            "message": "Bad Request",
            "stacktrace": [
              "Error: Bad Request",
              "    at Object.strapi.app.response.(anonymous function) [as badRequest] (E:\\projects\\cms23-users\\server\\node_modules\\strapi\\lib\\middlewares\\boom\\index.js:68:34)",
              "    at Object.proto.(anonymous function) [as badRequest] (E:\\projects\\cms23-users\\server\\node_modules\\delegates\\index.js:40:31)",
              "    at update (E:\\projects\\cms23-users\\server\\plugins\\users-permissions\\controllers\\User.js:153:11)",
              "    at process.internalTickCallback (internal/process/next_tick.js:77:7)"
            ]
          }
        }
      }
    ],
    "data": {
      "updateUser": {
        "user": null
      }
    }
  }
}
```

This is exactly the same as another user reported in the other thread.

What should I do?

ps I wasn't sure if I should open a new thread for this or comment in the other thread I hope I did it correctly

Thanks in advance
Omer

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by omerfaran** [comment]
btw an alternative with axios could be ok, but when trying:

axios
  .put('http://localhost:1337/user/:5c43cd1fa2980a09b46e7761', {
    username: 'Strapi user',
    email: 'user@strapi.io',
  })

I'm getting an error: 404 not found.

Is there a way to achieve updating a user with axios as an alternative?
Of course doing it with the graphql plugin would be better.

Thanks in advance

**Comment by derrickmehaffy** [comment]
@omerfaran I'm guessing the error there is the `:` in the location

**Comment by omerfaran** [comment]
Oh silly man thanks derrickmehaffy it's working! Plus I had to write 'users' and not 'user'.

It was just pure luck.

Is there a dedicated area to all available axios functions in the Strapi documentation?

Here I was just guessing...

Also regarding the original post, is the error I'm getting when trying to mutate a user in the graphql plugin is indeed a bug that still hasn't been fixed?

Thanks a lot in advance and have a nice weekend everyone

**Comment by derrickmehaffy** [comment]
@omerfaran Not sure on that bug, just saw your issue and pointed out the typo I suspected :stuck_out_tongue:

**Comment by omerfaran** [comment]
Thanks derrickmehaffy(:

Do you happen to know how I can associate a user with a collection/model? For example I have a collection named 'institution' and I want to associate it with a user:

axios
  .put('http://localhost:1337/user/:5c43cd1fa2980a09b46e7761', {
    username: 'Strapi user',
    email: 'user@strapi.io',
    institution: "5c58bb58f4cb151d808388cb"
  })

I get an error: 400 bad request.

I also tried plural institutions.

I'm guessing that my syntax is wrong, because in the strapi panel I can associate a user to a collection with no problem

Thanks again in advance!

**Comment by omerfaran** [comment]
Sorry the request is coming through but the relationship with institution is not being updated

**Comment by lauriejim** [comment]
I create a fresh new app and make your request and I haven't be able to reproduce your issue.

**Comment by omerfaran** [comment]
Did you try to create/mutate a user with graphql plugin and it wokred fine?

**Comment by lauriejim** [comment]
Yap yap!
<img width="1077" alt="screenshot 2019-02-08 at 17 59 15" src="https://user-images.githubusercontent.com/5716596/52493244-45263c80-2bcb-11e9-929a-6a014cfdac00.png">

**Comment by omerfaran** [comment]
So I guess my upgrade didn't go well
I'll start a new project
Thanks Laurie and sorry for the hassle

**Comment by lauriejim** [comment]
No prob! I close this issue and let us know if it works with new app.
