### ISSUE TITLE
Requests to my database became very slow since I upgraded to the latest version

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2789]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23
- **Database**: mongodb
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Since I upgraded from alpha19 to alpha23 my requests to the server (mlab) have become very slow, about 20 seconds for a simple query.

In the documentation you ask to do the following:

Update services
For both bookshelf and mongoose, you will have to update all services of your generated API.

You will have to update one line of the fetchAll function.

Mongoose replace .populate(populate); by .populate(filters.populate || populate);. Bookshelf: replace withRelated: populate by withRelated: filters.populate || populate.

I didn't understand how to update the fetchAll function for my Mongoose. Where can I locate the function and change the line?

Thanks in advance

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by omerfaran** [comment]
`****`

**Comment by kamalbennani** [comment]
For each of your generated models inside of `/api/<your_model>` you'll find a file that has the same name as your model located in `/api/<your_model>/services/<your_model>.js` and there you'll find a function called fetchAll

**Comment by lauriejim** [comment]
Hello @omerfaran !
Hum can you give us more information please.

What is the request you try ?

**Comment by lauriejim** [comment]
I just created a new app and connected it to a mlab database and all works well.

**Comment by omerfaran** [comment]
Hey Laurie,
Since I changed what kamalbennani suggested it's working very well for me too thanks

When you have time, could you please check about the issue I'm having with user mutation and creation in graphql? Thank you very much

https://github.com/strapi/strapi/issues/2788
