### ISSUE TITLE
Email confirmation and JWT

### ISSUE THREAD

**Issue by crashlab** [strapi/strapi#2791]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23
- **Database**: MySQL
- **Operating system**: Mac OSX
- **(Optional) Link to your Project**: 

**What is the current behaviour?**

If I enable the "email confirmation" for new users, I receive successfully an email with a link which includes a token. That token is actually the same JWT token that I receive on the JSON payload when I register. That means that someone could register a new user with a fake email, store the JWT token received on the JSON payload and without having to open the confirmation email, inject the token in the confirmation link and the user is confirmed.

**Steps to reproduce the problem**

1. Register new user: POST /auth/local/register (with username, email, password);
2. Copy the value of the "jwt" property received in the JSON payload after executing the above request;
3. Open /auth/email-confirmation?confirmation=**paste jwt value here** ;
4. The user is confirmed without validating the email;

**What is the expected behavior?**

If there's an email confirmation, the user shouldn't be able to confirm it without actually receiving and opening an email.

**Suggested solutions**

As a quick fix (not an ideal solution) we shouldn't send the jwt token when registering if email confirmation is on.

In the **register** method of the **Auth.js** Controller, we could modify a line with the following code:

``` javascript
ctx.send({
  jwt: !settings.email_confirmation ? jwt : null,
  user: _.omit(user.toJSON ? user.toJSON() : user, ['password', 'resetPasswordToken'])
});
```

**Comment by lauriejim** [comment]
Hello @crashlab , thank you for reporting this issue.
Can you please submit a PR to fix it.
Will appreciate your contribution!

We have to manage it with 2 different token you are right!
If we set `undefined` instead of `null` the key will be not send I think.
And we can have an other JWT to manager the confirmation with the user `id` and a `confirmation` key set to `true`

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by crashlab** [comment]
Hello @lauriejim,
I'll do as soon as possible. Today I was inspecting the code and I noticed another related issue.
If the email confirmation setting is on, I can still bypass it just sending 'confirmed: true' in the payload.

The following condition is the cause:

```javascript
if (!settings.email_confirmation) {
   params.confirmed = true;
}
```
I just changed the above into:

```javascript
params.confirmed = !settings.email_confirmation;
```

I'll doublecheck other few things and I'll send a pull request really soon.

**Comment by kairauer** [comment]
@lauriejim I just stumbled upon this issue and I think this issue still (or again?) exists. Today I created a new Strapi project with strapi@3.0.0-beta.9 and enabled email confirmation. I registered a new user and the jwt was sent in the response body.
I was taking a look at the code: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L525
It seems like, the implemented fix for this is no longer present.
Original fix:
```javascript
ctx.send({
    jwt: !settings.email_confirmation ? jwt : undefined,
    user: _.omit(user.toJSON ? user.toJSON() : user, ['password', 'resetPasswordToken'])
});
```
Current implementation:
```javascript
ctx.send({
    jwt,
    user: _.omit(user.toJSON ? user.toJSON() : user, ['password', 'resetPasswordToken'])
});
```

**Comment by lauriejim** [comment]
Thank you! You are right! During the migration from old users to the new admin & user - we had a merge issue.

About your proposition, this use case is really interesting.

We will review all the **users&permissions** later.
So for now I suggest you to custom by using https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions

**Comment by DekiGk** [comment]
@lauriejim Is the merge issue now fixed for this one?

**Comment by lauriejim** [comment]
Yap!

**Comment by DekiGk** [comment]
@lauriejim Thanks for the response. Which beta version has this change? I am using this one: `v3.0.0-beta.18.6` and the behaviour is still the one from the top of this thread.

**Comment by DaniloPootaren** [comment]
Hello I noticed something while learning Strapi. Does the redirect URL for email confirmation works as expected.
