### ISSUE TITLE
Error: SQLITE_ERROR: near "ALTER": syntax error

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#2794]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: SQLite
- **Operating system**: MacOS
- **(Optional) Link to your Project**: -

**What is the current behavior?**

When I update a content type, I have `Error: SQLITE_ERROR: near "ALTER": syntax error` error

**Steps to reproduce the problem**

1. Create a content type `article`
2. Add `title` attribute (string)
3. Save the content type
4. Visit an other page to ovoid this issue https://github.com/strapi/strapi/issues/2793
5. Add `content` attribute (text)
6. Save the content type

**What is the expected behavior?**

I should not have an error.

**Suggested solutions**

Source of the issue https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/index.js#L625

**Comment by krsnaa** [comment]
+1 - able to reproduce this on alpha.23.1.

**Comment by pyrbin** [comment]
Using an enumeration has caused this as well

**Comment by pyrbin** [comment]
Been able to reproduce without an relationship attribute
