### ISSUE TITLE
Add granularity of `Maximum size allowed` for file upload

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2795]
### Informations
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

**What is the current behavior?**
Can not input decimals in `Maximum size allowed (in MB)`,  
meaning you don't have a fine-grained control over the upload file size (e.g. `<= 250 KB`).

**Steps to reproduce the problem**
1. Login to the admin panel
2. GENERAL > Plugins > FILES UPLOAD
3. Try to input `0.5` or `1.5` in `Maximum size allowed (in MB)`, but you can't.  
    It will always trim the dot, which will always result in `0` or `1`

**What is the expected behavior?**
Be able to input decimals in `Maximum size allowed (in MB)`.

**Comment by lauriejim** [comment]
Hum that could be interesting yes.
Have to check if changing this input can change something https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/admin/src/components/EditForm/index.js#L74

Can you please submit a PR to fix it.
Will appreciate your contribution!
