### ISSUE TITLE
Unable to start server after re-adding pre-existing Content Attribute

### ISSUE THREAD

**Issue by PaddingtonTheBear** [strapi/strapi#2797]
**Informations**
- **Node.js version**: 10.13.0 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.18 
- **Database**: PostgreSQL 11.1
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Server refuses to start and produces an error:

(node:15592) UnhandledPromiseRejectionWarning: error: operator class
"gin_trgm_ops" does not accept data type numeric

This requires going to the database and manually deleting the table attribute, then manually deleting the Content Attribute from Strapi's model settings.

**Steps to reproduce the problem**
Add a content field, such as a "String" field. This creates a matching column in the database. Then delete that content field, and attempt to re-add the field but with a different type, such as Numeric. Strapi will then throw errors.

**What is the expected behavior?**
Strapi starts successfully and properly handles the situation of trying to add Content Attributes with different types than the DB attribute and for DB columns that already exist.

**Suggested solutions**
Strapi allows you to modify a Content Attribute's datatype after it has been created. This would provide a workflow for deleting / migrating the attribute column from your table in the DB. 

Another option is to prevent the user from re-adding a Content Attribute that has a different data type than that of the existing attribute in the DB table.

**Comment by lauriejim** [comment]
Can you confirm it's the same issue as https://github.com/strapi/strapi/issues/1114

**Comment by PaddingtonTheBear** [comment]
Definitely associated to that issue and I read through part of that one before posting this one. I see your comment that it isn't being worked on at present now. I figured this was a bad situation for the server to be prevented from starting for a relatively simple use case. 

It's not difficult to work around this manually, just annoying. You're likely not going to be trying to modify the Content Attribute type either, I'm just running into this as I'm starting a new project so things are changing quickly.

Feel free to close this issue, apologies for clogging up the issue log!

**Comment by lauriejim** [comment]
Related so the issue is linked.
