### ISSUE TITLE
Limit user access to associated models only

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2799]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23
- **Database**: mongodb
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Hey guys,

I hope it's the right place to ask, since it's not about a bug at all but just a simple (hopefully) question of knowledge.

I created a model called institution, and I created a relationship the users have with this model - each user can have one or more institutions related to it.
For example, here I'm updating a relationship a user has with one institution (using axios):

```
axios.put('http://localhost:1337/users/5c43cd1fa2980a09b46e7760', {
    institutions: ['5c58bb58f4cb151d808388cb'],
  })
```

It also can be achieved from strapi control panel of course.

My questions is how can I limit the fetching of quries the authenticated user can make only to their institutions associated with them? In other words, the user should be restricted to fetch data only about the institution they have relationship with.

How could it be done?

If it's a whole concept could you please direct me to relavant documentation?

Thanks a lot in advance!
Omer

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by omerfaran** [comment]
Hey guys I think I made it.

I'm very new to this whole thing of ctx but I managed to restrict access of the users to their associated institution models only. 

Again this is not a post about reporting a bug, so please close and delete it if it's not the correct place for it to be.

To achieve what I did I had to modify the model controller:

```
find: async (ctx) => {
    const user = ctx.state.user;
    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'User is not authenticated' }] }]);
    }
      var data;
      if (ctx.query._q) {
            data = await strapi.services.institution.search({user:user.id});
          } else {
            data = await strapi.services.institution.fetchAll({user:user.id});
          }

    if(!data){
      return ctx.notFound();
    }
    ctx.send(data);
  },
```

**Comment by lauriejim** [comment]
So you successfully did it. I can close now this issue.

**Comment by emrahc** [comment]
@omerfaran Hello. I have smilar issue. I have a profile model related to user model. But when authenticated a user could access other profiles as well. How can i restrict authenticated users to see other profiles. Tried your code but not worked.

**Comment by omerfaran** [comment]
Hello Emrahc, please do it inside the controller. ctx.state.user should be null if the user is not authenticated.

**Comment by emrahc** [comment]
Hello @omerfaran  thanks for reply. I already changed it according to your code. projectfolder/plugins/user-permissions/controllers/User.js
but doesn't work. Still any authenticated user access other profiles.
