### ISSUE TITLE
Forgot password route never responds to POST request

### ISSUE THREAD

**Issue by svencowart** [strapi/strapi#2800]
**Informations**
- **Node.js version**: 10.7.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: MongoDB 4.0.0
- **Operating system**: macOS Mojave 10.14

**What is the current behavior?**
A POST request on `http://localhost:1337/auth/forgot-password` route does not return any response at all.

**Steps to reproduce the problem**
1. Spin up local instance of MongoDB 4.0.0
2. Run `strapi new test-app`
3. Run `cd test-app`
4. Run `strapi start`
5. Create your first user at localhost:1337/admin
6. With Postman or any other mechanism, run a POST request on `http://localhost:1337/auth/forgot-password` with body as described in docs here: https://strapi.io/documentation/3.x.x/guides/authentication.html#forgotten-password

**What is the expected behavior?**
To receive either a successful response or to receive an error response.

**Suggested solutions**
N/A

**Comment by lauriejim** [comment]
Hello @svencowart !
Sorry for this trouble.

I think it's because the email can't be sent from your machine.
Can you try to [install an email provider](https://strapi.io/documentation/3.x.x/guides/email.html#install-providers) and try again.
