### ISSUE TITLE
Controller endpoint: what is `next` parameter ?

### ISSUE THREAD

**Issue by sylvainbaronnet** [strapi/strapi#2801]
Hello,

What is `next` parameter in controller endpoint generated with content type builder ?

for exemple here : 
`update: async (ctx, next) => {`

it's not documented here : https://strapi.io/documentation/3.x.x/guides/controllers.html#adding-endpoints

**Comment by kamalbennani** [comment]
A controller an either be used as a controller or a middleware so the next is a function that is invoked to execute the downstream middleware. Please refer to: https://github.com/koajs/koa#common-function
