### ISSUE TITLE
Expose upload files' buffers (or provide a middleware mechanism) for developers to deal with compression / resize / watermark / etc

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2803]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

### Related source code
* https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/controllers/Upload.js#L35
* https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L42

### Related requests
* https://portal.productboard.com/strapi/c/21-custom-plugin
* https://portal.productboard.com/strapi/c/28-media-library-with-edit-crop-resize-capabilities
* https://portal.productboard.com/strapi/c/26-new-plugin-architecture

### Related questions
* https://stackoverflow.com/questions/51997319/how-to-customize-strapi-image-upload-to-use-third-party-library-for-image-compre/52026301

### Related repo
* https://github.com/merijnvanessen/strapi-provider-upload-local-resize/blob/master/lib/index.js

**Comment by kenberkeley** [comment]
### Proposal
If there is a dir `api/_upload/`, Strapi will read its content to *enhance* the original upload plugin.

e.g.

```js
// api/_upload/index.js
module.exports = async function uploadPluginEnhancer (bufferizedFiles) {
  // deal with the buffers
  return bufferizedFiles
}
```

**Comment by kenberkeley** [comment]
Well, now I turn to https://imagekit.io for help, haha

**Comment by lauriejim** [comment]
Can you share all these information to this card https://portal.productboard.com/strapi/c/28-media-library-with-edit-crop-resize-capabilities

We manage this topic from ProductBoard.
Thank you for this feedback.
