### ISSUE TITLE
Cannot install graphql plugin

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2805]
**Informations**
- **Node.js version**: 6.4.1
- **NPM version**: v11.3.0
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mlab
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I installed a the newest strapi version glocally, then created a new project with "strapi new", then chose custom settings to connect it to my mlab.

Everything works fine but when I go to my marketplace to download graphql plugin, it restarts the server in order for the changes to take effects, and then I can see again the 'download' button, and it hasn't been installed.

[2019-02-11T11:52:46.278Z] debug GET /admin/plugins (182 ms)
[2019-02-11T11:52:50.433Z] info Installing graphql...
[2019-02-11T11:52:50.617Z] debug POST /admin/plugins/install (362 ms)
[2019-02-11T11:52:50.620Z] info The server is restarting

I tried logging in and out of strapi cms and reinstall graphql but it didn't help.

Maybe it's because an older version of strapi project (in another folder) is already connected to my mlab?

Please tell me what additional information you need for the issue

Thanks in advance,
Omer

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@omerfaran Can you please look in the /plugins folder of your Strapi project to see if the GraphQL plugin is showing there.

Also as a footnote, windows 10 is not supported, please also test this bug in either WSL (Not using a mapped windows drive) or a Linux Virtual Machine.

https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

**Comment by derrickmehaffy** [comment]
I am marking this request as closed as it based on an OS that is not supported, should the bug also exist on a supported platform and a new update is posted then the bug report can be reopened.

**Comment by omerfaran** [comment]
Hello derrickmehaffy,

I understand that the support for windows 10 is currently limited, it's just that on previous versions of strapi graphql worked fine, so I hoped to install it on the latest version as well.

i checked at the /plugins folder and it doesn't exist there.

Is there by any change some settings or configurations to check so that it can be fixed? If it's a more complicated issue that might be related to windows 10, I'll just stick to the older version of strapi.

Thanks in advance and have a good day

**Comment by frankc60** [comment]
I am running Strapi in Linux Mint 19. I get it saying 
```
info Installing graphql...
info The server is restarting
debug POST /admin/plugins/install (8177 ms)
```
the graphql folder is created in the plugins folder, but it is empty. 

I resolved this by downloading the plugin directly: [https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-graphql](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-graphql)
place the files in the plugin/graphql folder on my local machine, running an npm install, and restarting strapi, and it works !

**Comment by jonathanleahy** [comment]
I'm running Ubuntu 18.10 and after installing, the folder is created but empty. I followed Franks suggestion previous and copied the files, ran npm install and restarted strapi and it's up and running !

**Comment by BattleSpunk** [comment]
Had a similar issue, also using windows 10 trying to install from the marketplace wasn't installing the entire plugin.

By deleting the graphql plugin folder and manually installing it with `strapi install graphql` worked for me.

**Comment by djsethi09** [comment]
I am still having this issue on Linux Ubuntu (Mint) 18.3. 
Tried by downloading the plugin from the link and did npm install, while starting the strapi, I further got this error
Error: Cannot find module 'apollo-server-koa' 
Any help?

**Comment by thatsnotnice** [comment]
@djsethi09 I had the same problem on CentOS7.

as a workaround i deleted node_modules folder, manually copied the graphql plugin folder from the git repo, then i ran a fresh `yarn install`

if i start strapi after a `npm install` i get `Error: Cannot find module 'apollo-server-koa'`, but for some reason with yarn it works.

it's a crappy workaround btw...

**Comment by Ulibka68** [comment]
I am still having this issue on Windows 10.
Tried by downloading the plugin from the link and did npm install, while starting the strapi, I further got this error
Error: Cannot find module 'strapi/lib/load'
Any help?
