### ISSUE TITLE
MongoError: cursor does not exist, was killed or timed out -  CosmosDB (Mongo API)

### ISSUE THREAD

**Issue by vaskort** [strapi/strapi#2809]
*Not an actual Strapi bug*

**Informations**
- **Node.js version**: v10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.21
- **Database**: CosmosDB (Mongo API)
- **Operating system**: Mac

Opening this issue so everyone that is using CosmosDB with Mongo API has to be aware.

In case you start getting the error: `MongoError: cursor does not exist, was killed or timed out` you have to open a ticket with Microsoft to enable the "persisted cursor support feature". Yes it's a manual process that they do for you. 

**What is the current behavior?**
Since our Product Content type have been scaled I started getting `MongoError: cursor does not exist, was killed or timed out` error.

**Steps to reproduce the problem**
I think this starts appearing after your query returns 1000+ documents but didn't confirm this. Microsoft confirmed that this happens in a high load scenario.

**Suggested solutions**
Open a ticket through Azure portal.

**Comment by derrickmehaffy** [comment]
Interesting issue, good to know @vaskort
