### ISSUE TITLE
Sentry can not catch the errors

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2810]
### Informations
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

**What is the current behavior?**
Strapi crashes, but [`@sentry/node`](https://www.npmjs.com/package/@sentry/node) can not catch the errors.

![image](https://user-images.githubusercontent.com/13287948/52610285-a7858280-2ed4-11e9-9788-89f28be64f1e.png)

**What is the expected behavior?**
Strapi should emit the errors

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/52611115-08628a00-2ed8-11e9-8ca7-1bb00c719329.png)

**Comment by lauriejim** [comment]
What is the error you have (and you want to catch ?)

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/52685481-f4815b80-2f9d-11e9-922a-d9869d9e7b9e.png)

**Comment by kenberkeley** [comment]
any news?

**Comment by lauriejim** [comment]
It doesn't help me, can you make a sentence please of what you are trying to do exactly.
And give us more details you can.

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/53058730-7296b280-3508-11e9-8ee7-2be30c7df9e8.png)

![image](https://user-images.githubusercontent.com/13287948/53058743-7d514780-3508-11e9-8e97-fcd16c2c1f8c.png)

**Comment by lauriejim** [comment]
Can not help you more, I suggest you to go on our Slack channel, you will find help.

**Comment by cosydney** [comment]
@kenberkeley the way I did it was to put sentry in bootstrap.js. 

like so: 
![image](https://user-images.githubusercontent.com/10532381/65059046-92466a00-d975-11e9-9ed6-9330bde2a078.png)

**Comment by ceefour** [comment]
@kenberkeley @cosydney the documented way to this is: https://strapi.io/documentation/3.0.0-beta.x/guides/error-catching.html#handle-errors

**Comment by raphaelsoul** [comment]
not working following latest doc like below
 ```
const Sentry = require('@sentry/node');
Sentry.init({
  dsn: strapi.config.middleware.settings.sentry.dsn,
  environment: strapi.config.environment,
});

module.exports = strapi => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        try {
          await next();
        } catch (error) {
          Sentry.captureException(error);
          throw error;
        }
      });
    },
  };
};

```

 ```
module.exports = {
  load: {
    before: ['boom', 'sentry',], // ['sentry', 'boom'] and official doc example also not working
  },
  "after": [
    "parser",
    "router",
    "sentry"
  ],
  settings: {
    sentry: {
      dsn: 'https://[RECARD]@[RECARD].ingest.sentry.io/[RECARD]',
      enabled: true,
    },
  },
};

```

**Comment by Antoine-lb** [comment]
Same, followed step by step but nothing happens:

- `./config/middleware.json`
I don't know what `parse` and `router` is for, I just copied the [doc](https://strapi.io/documentation/3.0.0-beta.x/guides/error-catching.html#configure-the-middleware)
```
{
  "load": { "after": ["parser", "router", "sentry"] }
}
```


- `./config/production/middleware.json` and `./config/development/middleware.json`
```
{
  "sentry": {
    "enabled": true
  }
}
```


- `./middleware/sentry/index.js`
```
const Sentry = require("@sentry/node");
Sentry.init({
  dsn:
    "https://my@num.ingest.sentry.io/key",
  environment: strapi.config.environment,
});

module.exports = (strapi) => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        try {
          await next();
        } catch (error) {
          Sentry.captureException(error);
          throw error;
        }
      });
    },
  };
};

```

No errors, no logs, I don't really know what to do

**Comment by raphaelsoul** [comment]
> Same, followed step by step but nothing happens:
> 
> * `./config/middleware.json`
>   I don't know what `parse` and `router` is for, I just copied the [doc](https://strapi.io/documentation/3.0.0-beta.x/guides/error-catching.html#configure-the-middleware)
> 
> ```
> {
>   "load": { "after": ["parser", "router", "sentry"] }
> }
> ```
> 
> * `./config/production/middleware.json` and `./config/development/middleware.json`
> 
> ```
> {
>   "sentry": {
>     "enabled": true
>   }
> }
> ```
> 
> * `./middleware/sentry/index.js`
> 
> ```
> const Sentry = require("@sentry/node");
> Sentry.init({
>   dsn:
>     "https://my@num.ingest.sentry.io/key",
>   environment: strapi.config.environment,
> });
> 
> module.exports = (strapi) => {
>   return {
>     initialize() {
>       strapi.app.use(async (ctx, next) => {
>         try {
>           await next();
>         } catch (error) {
>           Sentry.captureException(error);
>           throw error;
>         }
>       });
>     },
>   };
> };
> ```
> 
> No errors, no logs, I don't really know what to do

your error was caught and handled by boom. Try this
```
module.exports = ({ env }) => ({
  load: {
    before: ["boom", "sentry", "responseTime", "logger", "cors", "responses", "gzip"],
  },
  settings: {
    sentry: {
      dsn: env('SENTRY_DSN'),
      enabled: false,
    },
  },
});

```

**Comment by michaelstokes** [comment]
Cheers @raphaelsoul 

Your snippet helped particularly where to put sentry enabled:

```
module.exports = {
  timeout: 100,
  load: {
    before: ["responseTime", "logger", "cors", "responses", "gzip"],
    order: [
      "Define the middlewares' load order by putting their name in this array is the right order"
    ],
    after: ["parser", "router", "sentry"]
  },
  settings: {
    public: {
      path: "./public",
      maxAge: 60000
    },
    sentry: {
      enabled: true
    }
  }
};
```

config/middleware.js

```
const Sentry = require('@sentry/node');
Sentry.init({
  dsn: 'YOUR_DSN',
  environment: strapi.config.environment,
});

module.exports = strapi => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        try {
          await next();
        } catch (error) {
          Sentry.captureException(error);
          throw error;
        }
      });
    },
  };
};
```

middlewares/sentry/index.js
