### ISSUE TITLE
Date type fields (on Admin panel) are inconsistent with database's

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2811]
### Informations
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

**What is the current behavior?**
* Admin panel (11h slower, maybe it's displayed in UTC format):
  ![image](https://user-images.githubusercontent.com/13287948/52612545-4bbff700-2ede-11e9-8c07-5e511d27e2f5.png)

* Database GUI:
  ![image](https://user-images.githubusercontent.com/13287948/52612551-54183200-2ede-11e9-9a92-e43fee0d0f15.png)

> P.S. Here is Melbourne (AEDT, UTC+11)

**Suggested solutions**
Admin panel should respect the original data, or allow to set a default timezone.

**Comment by kenberkeley** [comment]
https://github.com/strapi/strapi/pull/1437

**Comment by kenberkeley** [comment]
https://strapi.io/documentation/3.x.x/configurations/configurations.html#database

![image](https://user-images.githubusercontent.com/13287948/52613029-6004f380-2ee0-11e9-802f-7a2543740aa4.png)

**Comment by derrickmehaffy** [comment]
I didn't even know there was a timezone option there, good to know

**Comment by kenberkeley** [comment]
😂

**Comment by lauriejim** [comment]
You will fin information here https://github.com/mysqljs/mysql#connection-options

**Comment by kenberkeley** [comment]
I set `timezone` to `local` / `+10:00` / `AET` etc, but nothing changed.

**Comment by lauriejim** [comment]
Here is where it's set in Strapi https://github.com/strapi/strapi/blob/master/packages/strapi-hook-knex/lib/index.js#L99

Can you check if you value is well setup by using logs.

**Comment by kenberkeley** [comment]
After some researches, I don't think it's the problem of the db or server's timezone.
Instead, it might be the problem of the front-end datetime formatter's timezone ONLY.

In the following I will show you the steps I tested:
( *P.S.* the timezone of the browser, server and db are all `Australia/Sydney` )


1. Create a new content type `Test`:
![image](https://user-images.githubusercontent.com/13287948/52754384-716c0e00-304e-11e9-8c33-74c11c83ffaa.png)

2. Add new entry
![image](https://user-images.githubusercontent.com/13287948/52754420-8fd20980-304e-11e9-9d09-b2c13060027b.png)

Request:

```yaml
Form Data
  start_dateime: 2019-02-14 02:14:00
  end_datetime: 2019-02-28 14:28:00
```

![image](https://user-images.githubusercontent.com/13287948/52754519-ef301980-304e-11e9-85e4-697272a66009.png)

Response:

```yaml
start_dateime: "2019-02-13T15:14:00.000Z" // Thu Feb 14 2019 02:14:00 GMT+1100 (Australian Eastern Daylight Time)
end_datetime: "2019-02-28T03:28:00.000Z" // Thu Feb 28 2019 14:28:00 GMT+1100 (Australian Eastern Daylight Time)
```

![image](https://user-images.githubusercontent.com/13287948/52755034-ac6f4100-3050-11e9-9dd0-7ed7c575ae7f.png)

As you can see on the page, the datetimes are display in UTC timezone directly, disregarding the current timezone `Australia/Sydney`.

**Comment by kenberkeley** [comment]
OK, here is the finale:

4. Add 1s to both `start_datetime` and `end_datetime`:
![image](https://user-images.githubusercontent.com/13287948/52761729-b735d000-3068-11e9-9a11-ae3a3141eaba.png)

5. Click the *Save* button, inspect the request and response again:

Request:
```yaml
start_dateime: 2019-02-13 15:14:01
end_datetime: 2019-02-28 03:28:01
```

![image](https://user-images.githubusercontent.com/13287948/52761801-f7954e00-3068-11e9-9760-f64dfd1edcb3.png)

Reponse:
```yaml
start_dateime: "2019-02-13T04:14:01.000Z" // Wed Feb 13 2019 15:14:01 GMT+1100 (Australian Eastern Daylight Time)
end_datetime: "2019-02-27T16:28:01.000Z" // Thu Feb 28 2019 03:28:01 GMT+1100 (Australian Eastern Daylight Time)
```

![image](https://user-images.githubusercontent.com/13287948/52761831-1c89c100-3069-11e9-9516-746e8795cac4.png)

6. Let's take a look at the db table `tests` again:
![image](https://user-images.githubusercontent.com/13287948/52761958-a9cd1580-3069-11e9-8b10-2a65cb27bb45.png)

**Comment by kenberkeley** [comment]
Proposal solution: respect the original input

**Comment by Thanseem007** [comment]
Use moment to convert the date time value into utc

**Comment by rizedr** [comment]
@lauriejim I want to add to this, on a `mysql` db setup, when updating (`PUT`) a resource that uses `Date` type attribute and not editing the `Date` attribute, it results in a `ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value`.

As @kenberkeley stated:
> Proposal solution: respect the original input

Basically, what happens:
1. POST: `date: 2019-03-04 00:00:00`
2. GET: `date: 2019-03-04T00:00:00.000Z`
3. PUT: `date: 2019-03-04T00:00:00.000Z` <- **w/ no edit**
4. PUT: `date: 2019-03-05 00:00:00` <- **w/ edit**

MySQL doesn't seem to like that Zulu notation at the end... 🤷‍♂ 
![image](https://user-images.githubusercontent.com/3323353/59170454-5fefca00-8b47-11e9-9120-494a50fd06de.png)

https://dev.mysql.com/doc/refman/5.7/en/date-and-time-literals.html

**Comment by lauriejim** [comment]
Thank you for this feedback.

**Comment by soupette** [comment]
I am closing this issue since the date field has been fixed with beta.16

**Comment by fl034** [comment]
@soupette I guess this is fixed by displaying UTC everywhere? 
Would be great to have timezone support for the front-end. I submitted an idea on the product board for it :).

**Comment by cullylarson** [comment]
This is really confusing, especially for average users. Selecting a date, hitting save, and then immediately seeing another date is non-intuitive. I had to search around bit and find this issue before realizing it isn't a bug. Having the date displayed in the browser timezone makes sense since that's the timezone used to select the date, or even have an option to select a display timezone.

**Comment by bskimball** [comment]
How do we change the date displayed in admin to a different timezone?

**Comment by cpontet** [comment]
Would it be possible for the date time picker in the Admin UI to offer the possibility to pick the timezone? I created a TimeZone Select plugin, but there is no way to link it to the date field at the moment.
https://market.strapi.io/plugins/strapi-plugin-timezone-select
