### ISSUE TITLE
Is there any way to display content types in left menu as camelCase or as many words?

### ISSUE THREAD

**Issue by kret13** [strapi/strapi#2813]

**Comment by lauriejim** [comment]
Hello!

Actually it's not possible to customise the content type name that is displayed in the menu via the UI.

But as you have access to the source code you can customise your admin.
Check the documentation here https://strapi.io/documentation/3.x.x/advanced/customize-admin.html
Then to update the way content types are injected in the left menu it's here in your content manager plugin https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/bootstrap.js#L10
