### ISSUE TITLE
Adding new field in Content Type gets rendered multiple times - Also crashes Content Manager plugin

### ISSUE THREAD

**Issue by vaskort** [strapi/strapi#2815]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.21
- **Database**: Cosmos DB (Mongo)
- **Operating system**: Mac

**What is the current behavior?**
A new field that recently have been added to the Content Type gets rendered multiple times when I want to add a new Content Type item (Product
<img width="1729" alt="screen shot 2019-02-12 at 11 40 33" src="https://user-images.githubusercontent.com/4882345/52633420-389c2f80-2ebc-11e9-98e8-c50b08b59cc2.png">
). 

**Steps to reproduce the problem**
Add a new field (string) in your Content Type. Purge your plugin_content-manager_schema in core_store and restart the app. Then every time you restart it the new field will be rendered +1 times. 

The new field has been added by adding the below in `api/ContentType/models/ContentType.settings.json`

```
"year": {
      "default": "",
      "type": "string"
    }
```

Also when you go to Content Manager plugin of that particular Content Type (Product) then the app crashes. 

Please can someone point me to the right direction? I would like to make a PR on this. 

Thanks!

**Comment by vaskort** [comment]
Thanks for adding tags @lauriejim. 

I rebuilt the admin thinking that it could be a cause but it happened again.

I can see that at some point a `core_store.update` happens in the init of the app. That object has two `years`.

<img width="592" alt="screen shot 2019-02-12 at 18 02 22" src="https://user-images.githubusercontent.com/4882345/52657464-a6624e80-2ef0-11e9-9e89-c567dbe31bef.png">

Do you know where this `core_store.update` happens? Try to find it with no luck. Then I might go backwards and see where it is happening :)

**Comment by lauriejim** [comment]
I need to know the `key` witch is updated here.

**Comment by vaskort** [comment]
@lauriejim
```
Mongoose: core_store.update({ _id: ObjectId("5c630877e09180184cb27c3c") }, { '$set': { __v: 0, type: 'object', value: '{"generalSettings".......
```

**Comment by lauriejim** [comment]
What is the `key` of the value please.

**Comment by lauriejim** [comment]
Ho okay! Can you try to remove in the `core_store` the document that have `plugin_content-manager_schema` as key. Then restart your app.

**Comment by vaskort** [comment]
hey @lauriejim, that indeed solves it but it happens again eventually when I start the app. I'll try to find the cause of this issue.

**Comment by vaskort** [comment]
@lauriejim do you think the errors comes from `node_modules/strapi-hook-mongoose/lib/relations.js`?

Previously we were patching the manyToMany case with the below code: 

```
patch-package
--- a/node_modules/strapi-hook-mongoose/lib/relations.js
+++ b/node_modules/strapi-hook-mongoose/lib/relations.js
@@ -131,7 +131,11 @@ module.exports = {
                     .lean()
                     .then(entry => {
                       if (_.isArray(entry[details.via])) {
-                        value[details.via] = entry[details.via].map(entry => _.get(entry, '_id', entry)).concat(value[details.via]);
+                          value[details.via] = entry[details.via]
+                              .map(entry => _.get(entry, '_id', entry).toString())
+                              .concat(value[details.via])
+
+                          value[details.via] = _.uniq(value[details.via])
                       }
 
                       return module.exports.addRelation.call(model, {
```

Now we updated Strapi to `alpha.21` and the `relations.js` code seems to be updated but not sure if it got fixed the correct way. Any thoughts?

**Comment by vaskort** [comment]
hey @lauriejim I think the bug was happening because different environments with different schemas were pointing to the same DB. I can't reproduce it now. Let's leave it open for 2-3 days and I'll close it.
Thanks!

**Comment by lauriejim** [comment]
Okay! Thank you for detail.
It's look good now I close this issue.
