### ISSUE TITLE
Catch error for auto open browser

### ISSUE THREAD

**Issue by siffash** [strapi/strapi#2817]
**What is the current behavior?**

Starting strapi with the command "strapi start" works but throws the following error:

> { Error: Command failed: osascript resources/openChrome.applescript "http://localhost:1337/admin"
>     at checkExecSyncError (child_process.js:601:13)
>     at execSync (child_process.js:641:13)
>     at startBrowserProcess (/Users/user/projects/project/node_modules/strapi/lib/utils/openBrowser.js:79:7)
>     at Strapi.openBrowser (/Users/user/projects/project/node_modules/strapi/lib/utils/openBrowser.js:151:14)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
>   error: null,
>   cmd: 'osascript resources/openChrome.applescript "http://localhost:1337/admin"',
>   file: '/bin/sh',
>   args: 
>    [ '/bin/sh',
>      '-c',
>      'osascript resources/openChrome.applescript "http://localhost:1337/admin"' ],
>   options: 
>    { cwd: '/Users/user/projects/project/node_modules/strapi/lib/utils',
>      stdio: [ [Object], [Object], [Object] ],
>      shell: true,
>      file: '/bin/sh',
>      args: 
>       [ '/bin/sh',
>         '-c',
>         'osascript resources/openChrome.applescript "http://localhost:1337/admin"' ],
>      envPairs: 
>       [ 'NODE_ENV=development',
>         '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0',
>         '_=/Users/user/.npm-global/bin/strapi',
>         'LC_CTYPE=UTF-8',
>         'LOGNAME=user',
>         'SHLVL=1',
>         'HOME=/Users/user',
>         'XPC_SERVICE_NAME=0',
>         'XPC_FLAGS=0x0',
>         'PWD=/Users/user/projects/project',
>         'PATH=/Users/user/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
>         'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.T2XNP6K4cC/Listeners',
>         'USER=user',
>         'TERM_SESSION_ID=E98923CE-61CE-43B9-8A8E-87C506DB9337',
>         'TERM_PROGRAM_VERSION=421.1',
>         'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Wp4Llg1ENz/Render',
>         'TMPDIR=/var/folders/7v/t7z0bggn75x_wpd9t3v8m3400000gn/T/',
>         'SHELL=/bin/bash',
>         'TERM=xterm-256color',
>         'TERM_PROGRAM=Apple_Terminal' ],
>      killSignal: undefined },
>   envPairs: 
>    [ 'NODE_ENV=development',
>      '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0',
>      '_=/Users/user/.npm-global/bin/strapi',
>      'LC_CTYPE=UTF-8',
>      'LOGNAME=user',
>      'SHLVL=1',
>      'HOME=/Users/user',
>      'XPC_SERVICE_NAME=0',
>      'XPC_FLAGS=0x0',
>      'PWD=/Users/user/projects/project',
>      'PATH=/Users/user/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
>      'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.T2XNP6K4cC/Listeners',
>      'USER=user',
>      'TERM_SESSION_ID=E98923CE-61CE-43B9-8A8E-87C506DB9337',
>      'TERM_PROGRAM_VERSION=421.1',
>      'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Wp4Llg1ENz/Render',
>      'TMPDIR=/var/folders/7v/t7z0bggn75x_wpd9t3v8m3400000gn/T/',
>      'SHELL=/bin/bash',
>      'TERM=xterm-256color',
>      'TERM_PROGRAM=Apple_Terminal' ],
>   stderr: null,
>   stdout: null,
>   pid: 1565,
>   output: [ null, null, null ],
>   signal: null,
>   status: 1 }

**Steps to reproduce the problem**

At one point the terminal asked me if I allow it to control Chrome and I chose No.

**What is the expected behavior?**

The error not to be thrown.

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue.
Can you please investigate on this issue and submit a PR to fix it.
Will appreciate your contribution!

**Comment by siffash** [comment]
@lauriejim no problem, will try to find some time to work on that.
BTW do you know is there a way to disable opening the admin panel in a browser every time strapi starts/reloads?

**Comment by lauriejim** [comment]
In the last version of Strapi, the admin open just during the first start.
So it look like you are using and old version of Strapi.

You can update it in `./config/environments/:env/server.json` - `admin.autoOpen` have to be false.
