### ISSUE TITLE
Add route for an authenticated user to update its own profile

### ISSUE THREAD

**Issue by capaci** [strapi/strapi#2818]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Currently an user cannot update its own profile unless it has permission to update users. 

This happens because the only method to update an user profile is to make a `PUT` request to `users/:_id`, and if we give permissions to any authenticated user to use it, this user can update any other user, and we don't want that.

I think could exist a route to do that, something like `PUT users/me`, where just the profile of authenticated user is updated, so anyone could update its own profile.

**Comment by lauriejim** [comment]
Hello @capaci !
Thank you for this feedback.

Can you send it in this card please https://portal.productboard.com/strapi/c/8-administrators-roles-permissions
We are managing this topic on PB.

If you can't wait, you can manage it manually by creating your route manually based on the update function of the User controller.

**Comment by capaci** [comment]
Hello @lauriejim !

I've sent  this request to PB and and I'm creating a new route right now :)

Thanks!

**Comment by lauriejim** [comment]
Okay thank you for the update.

**Comment by cesconix** [comment]
> Hello @capaci !
> Thank you for this feedback.
> 
> Can you send it in this card please https://portal.productboard.com/strapi/c/8-administrators-roles-permissions
> We are managing this topic on PB.
> 
> If you can't wait, you can manage it manually by creating your route manually based on the update function of the User controller.

I'm using user-permissions as strapi plugin for acl management but I cannot see user controller in api directory. Instead I've "users-permissions" inside "extensions" directory but it contains only config and models. Where is User controller file?

**Comment by bhartendu27** [comment]
I would recommend using the extension functionality
do the following
![Screenshot 2020-04-13 at 4 49 04 PM](https://user-images.githubusercontent.com/28601206/79116994-7ab64f00-7da7-11ea-8623-d4a468f7423e.png)

**Comment by dangercris** [comment]
> I would recommend using the extension functionality
> do the following
> ![Screenshot 2020-04-13 at 4 49 04 PM](https://user-images.githubusercontent.com/28601206/79116994-7ab64f00-7da7-11ea-8623-d4a468f7423e.png)

Excellent! @bhartendu27 a question what is the route for that service, in my case the route is :
![Captura de Pantalla 2020-06-16 a la(s) 17 22 09](https://user-images.githubusercontent.com/1825234/84833955-faee7000-aff5-11ea-9849-644766186c82.png)
![Captura de Pantalla 2020-06-16 a la(s) 17 21 56](https://user-images.githubusercontent.com/1825234/84833962-fc1f9d00-aff5-11ea-9d3e-c72022ac35e1.png)

**Comment by michael-lawrence** [comment]
> I would recommend using the extension functionality
> do the following
> ![Screenshot 2020-04-13 at 4 49 04 PM](https://user-images.githubusercontent.com/28601206/79116994-7ab64f00-7da7-11ea-8623-d4a468f7423e.png)

I'm trying to do what was suggested here and I'm having issues. I get 403 errors when trying to PUT at /users/me. I've made sure to give access to this route in the admin for both authenticated and public users (just in case). I'm passing the jwt token the same way I do when calling the GET /users/me route. I even added a console.log statement inside of the User.updateme method to see if it's even getting called and I never see my logged message in the console. Any idea why this isn't working? Am I missing something?

Thanks so much!

**Comment by derrickmehaffy** [comment]
@michael-lawrence can you open up a github discussion so we can work through the issue specifically for your usecase?

**Comment by michael-lawrence** [comment]
Sure thing. Thanks!

**Comment by landorid** [comment]
> > I would recommend using the extension functionality
> > do the following
> > ![Screenshot 2020-04-13 at 4 49 04 PM](https://user-images.githubusercontent.com/28601206/79116994-7ab64f00-7da7-11ea-8623-d4a468f7423e.png)
> 
> I'm trying to do what was suggested here and I'm having issues. I get 403 errors when trying to PUT at /users/me. I've made sure to give access to this route in the admin for both authenticated and public users (just in case). I'm passing the jwt token the same way I do when calling the GET /users/me route. I even added a console.log statement inside of the User.updateme method to see if it's even getting called and I never see my logged message in the console. Any idea why this isn't working? Am I missing something?
> 
> Thanks so much!

If anybody is struggling with this, just put a `/` to the path: `/users/me`

**Comment by alexisvisco** [comment]
Such a shame to not handling that defaultly

**Comment by melihoeztuerk** [comment]
> > I would recommend using the extension functionality
> > do the following
> > ![Screenshot 2020-04-13 at 4 49 04 PM](https://user-images.githubusercontent.com/28601206/79116994-7ab64f00-7da7-11ea-8623-d4a468f7423e.png)
> 
> I'm trying to do what was suggested here and I'm having issues. I get 403 errors when trying to PUT at /users/me. I've made sure to give access to this route in the admin for both authenticated and public users (just in case). I'm passing the jwt token the same way I do when calling the GET /users/me route. I even added a console.log statement inside of the User.updateme method to see if it's even getting called and I never see my logged message in the console. Any idea why this isn't working? Am I missing something?
> 
> Thanks so much!

To avoid security vulnerabilities be sure that this implementation avoid updating everything from the user input. Then the user could update attributes like role by his own. 

> Such a shame to not handling that by default

I think it's not a shame like @alexisvisco mentioned, because there is more logic needed as expected. You either need to define a model, which contains only specified attributes, which are going to be picked from the body request and used to update the user document, but then you must always update the code when updating the user model in de Admin Panel. The other way would be to delete specified attributes like role from the request body before using the data to update the user. But what if you create another attribute in the content type builder and this should not be able to be updated by the user either? Then you need to update the code inside the plugin again...

I believe that a dynamic implementation is therefore not so easy.

**Comment by derrickmehaffy** [comment]
> I believe that a generic implementation is therefore not so easy.

Nail meet head, exactly as you stated. The implantation from our side on the core team is not an easy one.
