### ISSUE TITLE
Return "id"  whose value the same as "_id" at http://localhost:1337/auth/local

### ISSUE THREAD

**Issue by PGzxc** [strapi/strapi#2820]
**Informations**
- **Node.js version**: v10.1.0
- **NPM version**: v5.6.0
- **Strapi version**: 3.0.0-alpha.16
- **Database**: mongodb
- **Operating system**:  win7 x64

**What is the current behavior?**
 I use postman to send the request,  url is http://localhost:1337/auth/local, its response.data.user has parameter "_id", how can i add a response parameter "id" whose value the same as "_id"

**Steps to reproduce the problem**
1. use http://localhost:1337/auth/local/register register an user    
2. use http://localhost:1337/auth/local login

**What is the expected behavior?**
 I hope login api(response.data.user) return an extra parameter "id" whose value the same as "_id"

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @PGzxc !

This is a normal thing when you use Mongoose. It's not caused by Strapi itself.
We have an issue here about get only `id` here https://github.com/strapi/strapi/issues/1274

**Comment by PGzxc** [comment]
use content manager add user whose response has  _id and id ，mongodb has id field；but only use strapi register user, id has no field

**Comment by PGzxc** [comment]
Hello @lauriejim 
Thanks for ansking my question  
but，what can i do if i want to get id and _id fields in the mongodb ,at the time  login response(user.id) has value
