### ISSUE TITLE
Content types created in dev cannot be instantiated in staging & prod after release

### ISSUE THREAD

**Issue by sylvaingirardbe** [strapi/strapi#2821]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**: v6.7.0
- **Strapi version**: alpha.23
- **Database**: mongo
- **Operating system**: osx & node:11.1.0-alpine for staging & production
- **(Optional) Link to your Project**: N/A

**What is the current behavior?**
After creating a content type in development, committing and pushing the code and then deploying to staging and production, we cannot create new instances of that content type on staging and production. There's just a page with the menu and a spinner, indicating something is loading. On development this does work, however.

**Steps to reproduce the problem**
See above.

**What is the expected behavior?**
That we're able to create new instances of of newly created and deployed content types on staging and production.

**Suggested solutions**
As a workaround, we now copy the `plugin_content-manager_schema` document from `core_store` in dev over to staging and production, which obviously is a hassle.

**Comment by anitricks** [comment]
hi @sylvaingirardbe we were having the same problem. So this is what we did.. https://github.com/strapi/strapi/issues/1957#issuecomment-426587938

deleting the `plugin_content-manager_schema` value from the prod database and then restarting strapi fixed the infinite load on creating a new entry.

**Comment by sylvaingirardbe** [comment]
I tried that, @anitricks, based on a recommendation of @derrickmehaffy. Didn't work, however. The admin UI wouldn't even load and I didn't go as far as to also look into that.

**Comment by jonmhutch7** [comment]
@anitricks Same issue, tried deleting that schema value and ran into exactly what @sylvaingirardbe ran into. It comes down to the server not being able to be restarted on a deployed environment to regenerate that schema value. If you can manage to run the project locally with your staging/prod database you can regenerate it that way. But, like you said, its quite a hassle.

**Comment by anitricks** [comment]
@sylvaingirardbe @jonmhutch7 hmm.. that might be server related then as we were using heroku so we shut the dyno, deleted the entire row from database and then just restarted the dyno. it might be because of different DB's as well. (we are using MySQL)

**Comment by sylvaingirardbe** [comment]
@anitricks we're running MongoDB in a container on Azure. Restarting the container should do the trick, I'd guess. No such luck.

**Comment by jonmhutch7** [comment]
@anitricks Yea we're running mongo in kubernetes and restarting didn't have any effect.

**Comment by georgepapas** [comment]
Same issue when using postgres. need to delete the entry for `plugin_content-manager_schema` from the `core_store` table and then restart strapi. 

This is not ideal. I tried doing this in `bootstrap.js`, but it is too late by that point. So you end up having to somehow delete an entry from the db before strapi is restarted for the new deployment that contains content type changes.  Not very nice. 

Would be great to see this solved, or at least a reasonable place to make this change.

**Comment by derrickmehaffy** [comment]
@georgepapas the content manager plugin is being reworked but no ETA yet.

**Comment by soupette** [comment]
@derrickmehaffy and don't worry we will split that schema and simplify it a lot!

**Comment by derrickmehaffy** [comment]
@soupette I know, we had discussed it, just relaying that info to others :wink:

**Comment by georgepapas** [comment]
Just further to this for anyone that is interested, the issue only arises when *new* content types are added. Adding attributes to an existing content type works fine, in the sense new attributes migrate across environments without issue.

**Comment by bpainter** [comment]
Similar issue for me.

I used the boilerplate Strapi/Heroku setup. Thanks for that – made things much easier. I add new content types through the Content Type Builder locally then push the new changes to Heroku. The new content type appears in the main navigation list but not in the Content Manager.
![content-type-missing](https://user-images.githubusercontent.com/29330/57228348-99ca2f80-6fe1-11e9-8e9e-d97571ff03f6.png)

When I try to add a new content entry for the new content type I just get the spinner mentioned here and in a few other tickets.
![spinner](https://user-images.githubusercontent.com/29330/57228464-d9911700-6fe1-11e9-939a-324657c12178.png)

I'll try the suggested solution here to see if the workaround works for me.
