### ISSUE TITLE
Media is not saved into the content type object.

### ISSUE THREAD

**Issue by vince1995** [strapi/strapi#2823]
**Informations**
- **Node.js version**:  10.4.1
- **NPM version**:  6.1.0
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: MongoDB Version 4.0.6
- **Operating system**: wsl ubuntu 16.04

**What is the current behavior?**
When I add media to a content type it isn't saved to the object but it's stored in the database.

**Steps to reproduce the problem**
![strapi](https://user-images.githubusercontent.com/15120985/52713666-37403500-2f98-11e9-9cab-4acd70256def.gif)

**Comment by lauriejim** [comment]
Thank you for your issue.
I will take a look soon as possible.

**Comment by vince1995** [comment]
Hm. I've recreated a new project and now it works. I've nothing changed.

**Comment by lauriejim** [comment]
Your issue came after a project upgrade ?

**Comment by vince1995** [comment]
Nope, it was a brand new setup.

**Comment by lauriejim** [comment]
What is the browser you use please.

**Comment by vince1995** [comment]
Chrome Version 72.0.3626.109

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by vince1995** [comment]
As I said, I tried with new setup and it worked. You can close this issue. If it occurs again I try to reproduce and open after that a new issue. :)

**Comment by lauriejim** [comment]
Thank you for the update.

**Comment by tomsutton1984** [comment]
I believe that others are having this issue (see https://github.com/strapi/strapi/issues/2118#issuecomment-478892353), myself included, could we reopen this issues and centralise the discussion here? 

The screen capture that @vince1995 has included is _exactly_ the problem I am having.

**Comment by derrickmehaffy** [comment]
@tomsutton1984 it should be fixed in the next release

**Comment by tomsutton1984** [comment]
@derrickmehaffy - I had forked the master branch to test, I guess that I'd jumped the gun!

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy - I had forked the master branch to test, I guess that I'd jumped the gun!

Is the issue still happening on the master branch? I'm fairly certain the deep filtering PR should have fixed this.

**Comment by tomsutton1984** [comment]
I believe so, I've tested the master branch on WSL (Ubuntu)/CosmosDB.

**Comment by tomsutton1984** [comment]
I'm clutching at straws here. 

It looks as though all relations are being built/populated correctly, except for media uploads. 

I'm currently looking at the Content Type Builder to see whether it might be the problem:
https://github.com/strapi/strapi/blob/196fa038bd213710798d3bb5b8e7602fc00e9f5d/packages/strapi-plugin-content-type-builder/services/ContentTypeBuilder.js#L177

**Comment by derrickmehaffy** [comment]
@tomsutton1984 are you on slack so we can kinda chat about this real time?
