### ISSUE TITLE
Add a relation on a model dynamically

### ISSUE THREAD

**Issue by anitricks** [strapi/strapi#2825]
- [] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
we are developing a plugin for strapi and I am looking for a way to add a relation on a model dynamically. I am currently looking at the boostrap.js of the plugin to add the relation through the content-type-builder plugin services. but the problem is that modifying attributes or relations on a model forces a restart to save it thus it can't be done in bootstrap.js either. There were services on models itself before to manage relations but they have been removed. 

Is there a way of adding a relation dynamically because I couldn't find any other plugin doing it.

**Comment by lauriejim** [comment]
Hello @anitricks !
Models are mounted before the execution of bootstrap functions.
So I think the thing you want to do it to plug a script before we mount models and it's actually not possible :/

**Comment by lauriejim** [comment]
If you can can you give us the exact use case. Maybe we can found a trick.

**Comment by anitricks** [comment]
@lauriejim  ok so we have a plugin that allows the Users model to send text messages. so every user models needs to have a relation to a Message model. (one-to-many) so we want to add a "messages" relation on the User model as soon as the plugin is installed and configured

**Comment by lauriejim** [comment]
Hum if you want to add relation on the plugins installation, you can write a post-install script.

You rewrite the User attributes by adding your relation to you new model.

**Comment by Aurelsicoko** [comment]
You should develop a custom hook for that, then loads it before/after the strapi-hook-mongoose or strapi-hook-bookshelf (see https://strapi.io/documentation/3.x.x/advanced/hooks.html#structure).
