### ISSUE TITLE
Wrong http code during an upload with an empty files attribute

### ISSUE THREAD

**Issue by rsinelle** [strapi/strapi#2827]
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23
- **Database**: MongoDB
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When we upload files, if the files are empty we received an HTTP Code 200 with a body equals to true

**Steps to reproduce the problem**
Call upload api with an empty files attribute

**What is the expected behavior?**
We more expect to receive an error message with an http code 400

**Suggested solutions**
In plugins\upload\controllers\Upload.js replace the line 
`if (_.isEmpty(files)) {
      return ctx.send(true);
    }`
by
`if (_.isEmpty(files)) {
    return ctx.badRequest(null, 'Files are empty');
    }`

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue.
Can you please submit a PR to fix it.
Will appreciate your contribution!

**Comment by rsinelle** [comment]
Hello
Done https://github.com/strapi/strapi/pull/2850
