### ISSUE TITLE
Unable to install strapi -  ERR! Command failed: git -c core.longpaths=true clone --template=C:

### ISSUE THREAD

**Issue by TheAnimeSenpai** [strapi/strapi#283]
Hi,

I'm currently unable to install strapi on my pc. I keep getting this error

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit  git+https://github.com/aheckmann/koa-router.git#19e60d9 resetting remote C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-aheckmann-koa-router-git-19e60d9-704f0691 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/aheckmann/koa-router.git C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-aheckmann-koa-router-git-19e60d9-704f0691: Cloning into bare repository 'C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-aheckmann-koa-router-git-19e60d9-704f0691'...
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "strapi@alpha" "-g"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/aheckmann/koa-router.git C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-aheckmann-koa-router-git-19e60d9-704f0691
npm ERR! Cloning into bare repository 'C:\Users\**\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-aheckmann-koa-router-git-19e60d9-704f0691'...
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Node.js version**: 6.11.0
**npm version**: 3.10.10
**Strapi version**: v3 alpha 6
**Operating system**: windows 10

p.s. : working behind a proxy...if it matters at all...

Please help anyway you can...

Thanks.

**Comment by Aurelsicoko** [comment]
@TheAnimeSenpai It seems related to our router. There is already an issue with a [PR opened](https://github.com/koajs/joi-router/pull/55/files) on this package. We are thinking to fork this repository and publish it ourselves to fix this issue.

**Comment by TheAnimeSenpai** [comment]
@Aurelsicoko ...thanks...Will wait for the fix...

**Comment by Aurelsicoko** [comment]
We just forked `koa-router-joi` on our own organization. We made fixes and updated the package the `koa-router` dependency to the latest version available (https://github.com/strapi/strapi/pull/293/commits/7b02da60b2312ec7ef1ceec3c2611fdf1be7d4d5)

**Comment by Aurelsicoko** [comment]
This issue should be fixed thanks to the [v3.0.0@alpha.6.4](https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.6.4) release. Feel free to re-open it if it's not the case.
