### ISSUE TITLE
[Proposal] Move PR description to the top

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2830]
Then when you share a link, the description go first.
Right now we the link summary does not provide much information, just labels.

Example with Slack:
<img width="332" alt="screenshot 2019-02-14 at 21 23 34" src="https://user-images.githubusercontent.com/1007051/52815372-d2233700-309e-11e9-90f3-c525f3d319b9.png">

**Comment by lauriejim** [comment]
Absolutely OK with that! 
Can you submit a PR that update the template please.

Thank you.
