### ISSUE TITLE
dot(.) disappear in url when sending email

### ISSUE THREAD

**Issue by Nowhy** [strapi/strapi#2833]
Informations

Node.js version: v10.13.0
NPM version: 6.4.1
Strapi version: " "^3.0.0-alpha.18"
Database: "mongoose": "5.3.16",
Operating system: Mac OSX 10.13.6
What is the current behavior?
When I send a link in an email and the dot(.) in url disappears.

Steps to reproduce the problem:
=============================================
When I send a link in an email and the url is
https://domainname.com.cn/#/app/modelname/model?id=5c6658431e1716678949f28e&filterkey=filtervalue

In dev environment, I have not seen such problem before.
But when I tried in stg enviroment, the domainname is longer than dev environment. It has some problem:
https://domainname.comcn/#/app/modelname/model?id=5c6658431e1716678949f28e&filterkey=filtervalue

I notice that ".com.cn" changed to ".comcn." 

In addition, I put some static files and the url also has same problem:
url (correct): https://api.domainname.com.cn/image-a-very-long-name.jpg
url (wrong):https://api.domainname.com.cn/image-a-very-long-namejpg
It also only appears in stg environment and it passed test in dev environment. The only different thing is the domain name in dev is shorter. Thus, I changed the "image-a-very-long-name.jpg" to "image.jpg". It works.
![image](https://user-images.githubusercontent.com/14275418/52849435-f9840d80-314b-11e9-836a-d0099f1f6d56.png)
The correct url only has 90 characters... I have on idea why I change the image name then it works.

What is the expected behavior?
url works.

Suggested solutions
I have no idea but I don't want to change the url.

**Comment by lauriejim** [comment]
Hello @Nowhy !

I'm not sure to follow you.
In your issue title your talk about send email with link, in your description you talk about static files and I can also see and hash (#) from an front end application.

So I don't understand your issue.

**Comment by Nowhy** [comment]
@lauriejim the actual problem is the url link. And this url link comes from the front-end. I need to send this url link through email. However, the url link sometimes went wrong. It should be ".com.cn" but the result shows me ".comcn".

In addition, I have same problem when I send some urls about static files. These static files are stored in back-end. If I want to access to these files, I also need to send links through emails. Then I fixed this problem by making url shorter.

**Comment by lauriejim** [comment]
Sorry but I don't understand what you are talking about.

> I need to send this url link through email
How ? Via Strapi email service feature or you want to send an email from somewhere else ?

> The url link sometimes went wrong
Don't understand who it can be **sometime** 

Please can you give me steps like that:
1. Do that
2. and then do that
To let me fully understand what you are trying to do.

**Comment by Nowhy** [comment]
I don't know why but there is no such problem appearing...
