### ISSUE TITLE
Add plugins and admin to .gitignore file

### ISSUE THREAD

**Issue by dj-hedgehog** [strapi/strapi#2834]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

With a fresh installation of Strapi the `plugins`, `node_modules` and `admin` folder amount to a whooping 190 MB. They should be inside the `.gitignore` file per default.

If you agree with this I will create a MR for it so what is your opinion, dear Strapi-team? I posted this as an issue because I wanted to ask you first whether I am overlooking something.

![image](https://user-images.githubusercontent.com/7140800/52853162-0b998800-311b-11e9-9ba7-d6e0e4af5976.png)

**Comment by derrickmehaffy** [comment]
@dj-hedgehog you can't regenerate the admin build folders in a project so they can't to be included in the .gitignore file.

Plugins also can contain custom settings per the user, so they also can't be included.

node_modules already is I believe.

**Comment by dj-hedgehog** [comment]
> @dj-hedgehog you can't regenerate the admin build folders in a project so they can't to be included in the .gitignore file.

@Aurelsicoko Will you address problems like this with the new plugin API? Having a fresh 148 MB repo is not the right way to go imo

**Comment by derrickmehaffy** [comment]
I do not believe that is part of the plugin framework rewrite no. @soupette would be the man to ask about that.

**Comment by derrickmehaffy** [comment]
Plugins most certainly won't be, since users can customize a lot of the logic for a plugin themselves.

Models, routes, services, controllers, ect.

Once the admin folders can be rebuilt on demand than I agree but I believe that is quite a ways out.

**Comment by soupette** [comment]
I think the real problem is the size of the builds, they are way too big! We will work on reducing their size but we need to first develop the new plugin system which also comes with a new admin lifecycle (you can check [this PR](https://github.com/strapi/strapi/pull/2798) to have an idea), then we need to integrate the new UI lib in all the plugins.

**Comment by dj-hedgehog** [comment]
Thank you @derrickmehaffy and @soupette. I will close this issue for the time being since my initial suggestion is rendered useless until there is a way to regenerate the admin and plugin folders.
