### ISSUE TITLE
Search fails if the content manager when there is a Date type

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2835]
**Informations**
- **Node.js version**: 10.4.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: PostgreSQL 10.6 or 11.1
- **Operating system**: OSX 10.11.6

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/13287948/52893181-d27e1800-31ed-11e9-81f6-57bcccb110d9.png)

```
error: function lower(timestamp with time zone) does not exist
```

![image](https://user-images.githubusercontent.com/13287948/52893200-022d2000-31ee-11e9-81f7-c14e6a384588.png)

***

## Steps to reproduce the problem

1. Install the latest Strapi and run:

```shell
$ npm i -g strapi@alpha
$ strapi new strapi23
...
$ strapi start
```

2. Add an content type **Activity**:
![image](https://user-images.githubusercontent.com/13287948/52893248-88496680-31ee-11e9-83e6-a0eac879610d.png)

3. Add an new activity and save:
![image](https://user-images.githubusercontent.com/13287948/52893275-ca72a800-31ee-11e9-8665-dbc3b72986a7.png)

4. Search and an error occurs:
![image](https://user-images.githubusercontent.com/13287948/52893285-e5ddb300-31ee-11e9-9e13-083daa83e05c.png)

**Comment by kenberkeley** [comment]
I think the reproduction steps provided above are quite sufficient.

**Comment by inoisy** [comment]
I have the same bug but with JSON

bug POST /products (19 ms)
created
{ error: function lower(jsonb) does not exist
    at Connection.parseE (/mnt/c/Users/dev/Desktop/strapi-postgres/node_modules/pg/lib/connection.js:601:11)
   .....

**Comment by lauriejim** [comment]
This issue is fixed in the last beta version.
