### ISSUE TITLE
Admin panel: a new content type (all the fields are Relation type) added successfully, but it says `There are no fields yet. Add your first field to your Content Type`

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2836]
**Informations**
- **Node.js version**: 10.4.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: PostgreSQL 10 or 11
- **Operating system**: OSX

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/13287948/52893937-ff362d80-31f5-11e9-8a8d-1741edbb1a03.png)

![image](https://user-images.githubusercontent.com/13287948/52893943-1117d080-31f6-11e9-9ad2-666eefdfc9b4.png)

![image](https://user-images.githubusercontent.com/13287948/52893958-3c022480-31f6-11e9-806e-91b6dd3b90e1.png)

***

**Steps to reproduce the problem**
1. Install the latest Strapi and run:

```shell
$ npm i -g strapi@alpha
$ strapi new strapi23
...
$ cd strapi23
$ strapi start
```

2. Add content types *Article* and *ArticleSetting*
![image](https://user-images.githubusercontent.com/13287948/52893984-a61ac980-31f6-11e9-994c-3674163fc488.png)

![image](https://user-images.githubusercontent.com/13287948/52894004-e0846680-31f6-11e9-8cee-58f46b8c2133.png)

3. Go to *ArticleSettings* and...
![image](https://user-images.githubusercontent.com/13287948/52894013-01e55280-31f7-11e9-9743-94c077403e14.png)

**What is the expected behavior?**
It should be allowed to add an entry for *ArticleSettings*, even all the fields are Relation type

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/52894029-5a1c5480-31f7-11e9-8420-b47e541290fa.png)

![image](https://user-images.githubusercontent.com/13287948/52894034-686a7080-31f7-11e9-828d-8b03eb408de0.png)

**Comment by lauriejim** [comment]
It have been fixed by @soupette .
