### ISSUE TITLE
Adding New Role doesn't give access to users-permissions

### ISSUE THREAD

**Issue by PaddingtonTheBear** [strapi/strapi#2838]
**Informations**

* **Node.js version**: 10.13.0
* **NPM version**: 6.4.1
* **Strapi version**: 3.0.0-alpha.18
* **Database**: PostgreSQL 11.1
* **Operating system**: Windows 10
* **(Optional) Link to your Project**:

**What is the current behavior?**
After adding a new role, there are no permissions written to the users-permissions type and there is no apparent way in the UI to modify permissions to the "users-permissions" section.

This makes it impossible to query data from some of the important endpoints, like /users/me (to get all information about the logged in user) as it will always be forbidden.

**Steps to reproduce the problem**
Create a new project, and add a couple new Roles for users. Then attempt to make an authenticated JWT call to http://localhost:1337/users/me as a user that belongs to one of those new groups, Strapi will return forbidden.

Confirm by looking at the Database Table, users-permissions_permission:

![image](https://user-images.githubusercontent.com/24558328/52906474-f58be480-324c-11e9-871f-b1e16eb9e99d.png)

My custom Roles are id's '4' and '5', which I have manually added permissions in via my Database editor. You'll notice that '4' and '5' did not get any permissions added for other actions.

**What is the expected behavior?**
A logged in user should be able to query for their information (/users/me) if they belong to a custom Role.

**Suggested solutions**
Strapi has a way for editing the Role's permissions to the underlying user-permissions type via the UI, and Strapi creates entries out of the box for these permissions when you create a new Role.

**Comment by PaddingtonTheBear** [comment]
Closed because I see that once I added in the properties manually to my users-permissions_permission table, it will now display in the UI, however it still doesn't appear to be properly writing the base permissions when creating a new role (upload permissions missing too...)

**Comment by lauriejim** [comment]
Hello @PaddingtonTheBear !

The following test I did is with laster version of Strapi (alpha.24.1)

Create a new role (with allow `users/me`), create a new user linked to this role, use user login route to get the JWT and then fetch `/users/me` with the JWT I got.

All these steps work well.
But maybe I miss something in your issue.

**Comment by PaddingtonTheBear** [comment]
Thanks @lauriejim !

I tried adding a new role via the UI and it was giving an error via the UI that setting the permissions wasn't successful (or something related to that, I can look and test again later). When I checked the database table, it didn't create any entries for any of the permissions in my plugins (such as upload). This made it so that the plugin permissions weren't even showing up for my newly created role. 

Perhaps doing it directly with the users/me endpoint works better...or my alpha.18 version has some issues. 

It's likely just an issue with my environment; recommend you can close this and if I encounter it again with repeatable tests / error logs I'll come back to this. Apologies for any wasted time.

**Comment by lauriejim** [comment]
Hum okay, I really suggest to use UI for this type of actions.
