### ISSUE TITLE
Does strapi fetches the whole contect of each model on fetchall?

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2840]
**Informations**
- **Node.js version**: 11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mlab
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Hello,

I have a model called exam and each instance of the modal has a somewhat large json object (500k).
However when fetching all the ids of the model, the fetching is extremely slow even though i'm only interested in the ids and the json object inside each instance:

```
query {
                    exams {
                      name,
                      _id,
                    }
                  } 
```

Also on strapi control panel, when I go to the Exam model, the fetching of the ids and names is very slow. This is in comparison with fetching of other models which is very fast.

Does strapi read through the whole content of each instance of a model? Is there a way to change this behaviour?

This is not a bug, just asking for help.

Thanks a lot in advance!
p.s sorry I cannot upgrade my strapi since on latest version, graphql doesn't work on windows 10

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@omerfaran 

https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Also you can enable database debugging to see the raw queries (and what is being pulled. If something is acting slow you can also enable graphQL tracing to see what is taking the most time. 

https://strapi.io/documentation/3.x.x/guides/graphql.html#configurations

```
You can also enable the Apollo server tracing feature, which is supported by the playground to track the response time of each part of your query. To enable this feature just change/add the "tracing": true option in the GraphQL settings file. You can read more about the tracing feature from Apollo here.
```

I'm closing this issue as it isn't a bug report but please do feel free to reply, also closing as issue is on an unsupported OS.

**Comment by omerfaran** [comment]
Thank you derrickmehaffy
