### ISSUE TITLE
How to uplod an image to an image field?

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2841]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mongodb
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I understand how to upload an image using the strapi-sdk:

```
let a = new FormData(this.form);
    const response = await strapi.upload(a);
```

But the response just recieves the value of true. It is possible to upload an image to a specific Image field, as can be done on the strapi control panel?

Thanks in advance!

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.x.x/guides/upload.html#usage

https://github.com/strapi/strapi-sdk-javascript/blob/bd442dad2df8c8442f544e079c96bccb9059307b/src/lib/sdk.ts#L336-L369

Please don't use the issues for basic questions, to try and help keep the issues clean. You can join the slack to ask questions. Thank you!

http://slack.strapi.io/

**Comment by omerfaran** [comment]
Thanks derrickmehaffy and I'm sorry, I didn't mean to get things out of order.

I did try to understnad the docs as explained in both the links but couldn't really get it...

Thanks anyways and I'll try slack

**Comment by Jbmanllr** [comment]
The documentation is just for client example, it is a real pain finding out how to upload from node.

**Comment by impactcolor** [comment]
@Jbmanllr any example on how to upload from node?

**Comment by descyther** [comment]
ye the docs are a joke tbh, why use a client and not just show a request, I dont see anything outlining collection type or field via the API
