### ISSUE TITLE
Cannot add new entry in UI after generate:api in CLI

### ISSUE THREAD

**Issue by romj** [strapi/strapi#2844]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: sqlite
- **Operating system**: Mac OS 10.14

**What is the current behavior?**
When I create an API via the CLI, and try to create a new entry for this object via the UI, the 'new entry' form is stuck with a spinner

**Steps to reproduce the problem**
- Create a new api:
`strapi generate:api test title:string description:text price:integer`
OR
`strapi generate:api -t bookshelf test title:string description:text price:integer`
- Start strapi
`strapi start`
- Login, and in the admin panel, in the `Content Type` section, visit the 'Test' page
- Click on 'New Entry'
- I am stuck at a not loading page

**What is the expected behavior?**
- The form loads and I can create a new entry

**Suggested solutions**
- There may be something I should have added beforehand - let me know what I missed!
- Maybe an actual bug

**Notes**
I have seen #154, #637 and #2101, but couldn't find the right answer

Thanks for your help!

**Comment by lauriejim** [comment]
Thank you for this report @romj !

Since this issue is not fixed I suggest you to use the content type builder plugin to create new API.

**Comment by romj** [comment]
Thanks for the heads up @lauriejim !

I had trouble with the content type builder UI because of #2847, but I guess now I should be fine.

**Comment by EpicUsaMan** [comment]
Also met this problem.

**Comment by botzill** [comment]
I also have this issue, any updates?

**Comment by buithuyen** [comment]
I have the same one

**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: MacOS

**What is the current behavior?**
- Admin UI always loading when add new entry (Production).
![Screen Shot 2019-03-14 at 3 48 55 PM](https://user-images.githubusercontent.com/5087522/54343245-fa3b9100-4670-11e9-99b4-f64aa2d1c4d5.png)
- Everything is fine in Local
![Screen Shot 2019-03-14 at 3 49 23 PM](https://user-images.githubusercontent.com/5087522/54343329-1e976d80-4671-11e9-97a2-449568ba8389.png)

**Steps to reproduce the problem**
- Create a model like this:
![Screen Shot 2019-03-14 at 3 52 35 PM](https://user-images.githubusercontent.com/5087522/54343393-41c21d00-4671-11e9-8006-95c50d73b806.png)

**Comment by lauriejim** [comment]
@buithuyen it's cause by the `plugin_content-manager_schema`.
Can you delete in the `core_store` table/collection the raw/document that have `plugin_content-manager_schema` as `key`

**Comment by thangnguyen095** [comment]
I have the exact same issue on beta version. Another thing worth mentioning is after creating an api, it shows up on sidebar and content type builder but not on content manager

![image](https://user-images.githubusercontent.com/20066498/59910099-692c4100-943b-11e9-9514-3dbb68edfd66.png)

**Comment by lauriejim** [comment]
It's due to the same issue.
We are working an this feature [Group of fields repeatable](https://portal.productboard.com/strapi/1-public-roadmap/c/24-group-of-fields-repeatable-or-not)
So a review of the Content Manager and Content Type Builder will be done. We will fix it at this time.
