### ISSUE TITLE
error: The hook `_config` failed to load!

### ISSUE THREAD

**Issue by kidandcat** [strapi/strapi#2845]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: sqlite
- **Operating system**: Ubuntu 18.10

**What is the current behavior?**

npx strapi@alpha new test
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

? Choose your installation type Quickstart (recommended)

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
✔ Install plugin users-permissions.
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application test is ready at /home/jairo/test.

⚡️ Change directory:
$ cd test

⚡️ Start application:
$ strapi start
error: The hook `_config` failed to load!

**Steps to reproduce the problem**

npx strapi@alpha new test

**What is the expected behavior?**

To work

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @kidandcat 

I just did it and it works well.

<img width="867" alt="screenshot 2019-02-19 at 15 39 01" src="https://user-images.githubusercontent.com/5716596/53022949-93093300-345c-11e9-8805-c93f17843aac.png">

Can you try with last version of Strapi please (alpha.24.1)

**Comment by kidandcat** [comment]
It works perfectly with latest version!

**Comment by lauriejim** [comment]
Happy to read that!
