### ISSUE TITLE
chrome --inspect

### ISSUE THREAD

**Issue by q-jason** [strapi/strapi#2846]
Sorry my English is not very good.
I want to use chrome --inspect feature.
Excuse How to use?

```bash
node --inspect main.js
```

**Comment by Nowhy** [comment]
![image](https://user-images.githubusercontent.com/14275418/52995405-8208f380-3455-11e9-8047-a714bfeea6d4.png)

**Comment by Nowhy** [comment]
yes... node --inspect server.js
My project works.

**Comment by q-jason** [comment]
@Nowhy

node server.js not hot load...

**Comment by Nowhy** [comment]
==
which file contains "strapi.start()"...pls use that one

**Comment by derrickmehaffy** [comment]
@q-jason As this is not a bug report nor a feature request I am marking this issue as closed. For questions please use the Slack: https://slack.strapi.io

You may still reply on this issue, but it is marked as closed.
