### ISSUE TITLE
Add option to disable automated timestamps & configure timestamps in the adminUI

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2848]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

As we can configure the default timestamp (created_at & updated_at) within the model.settings.js file these should also be added to the AdminUI to allow users to turn off the automated timestamps

This would be a good issue for new contributors to work on and get familiar with working on the AdminUI and submitted PRs

**Comment by Aurelsicoko** [comment]
You can already disable them (see https://strapi.io/documentation/3.x.x/guides/models.html#model-options).

**Comment by petersg83** [comment]
If I'm not mistaken, we've chosen to force the use of timestamps and they are not configurable in the schema anymore. Should we close this issue since we will probably never do that?

**Comment by derrickmehaffy** [comment]
> If I'm not mistaken, we've chosen to force the use of timestamps and they are not configurable in the schema anymore. Should we close this issue since we will probably never do that?

Yup makes sense
