### ISSUE TITLE
Edit links on the strapi docs page don't work

### ISSUE THREAD

**Issue by spruce** [strapi/strapi#285]
Just wanted to test those links and the seem to not work.

**Comment by Aurelsicoko** [comment]
@spruce Can you give me the concerned links?

**Comment by spruce** [comment]
The link right in the top on this page: https://strapi.io/documentation/getting-started/installation.html#

**Comment by pierreburgy** [comment]
Good catch @spruce! This is actually due to the following setting: https://github.com/strapi/strapi/blob/master/docs/3.x.x/book.json#L20.

**Comment by Aurelsicoko** [comment]
This issue has been fixed on [v3.0.0@alpha.6.4](https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.6.4).
