### ISSUE TITLE
Tags field type

### ISSUE THREAD

**Issue by Truemedia** [strapi/strapi#2863]
I would like to able to use a new field type called tags.

The idea behind this is I can assign an array of values to a content entry to group similar content together in a way I can make use of elsewhere (I only need via the graphQL api but others might find a frontend for it useful).

My thoughts are content entry is done by an input field that populates with autofill suggestions based on previously entered tags on the content type (or globally across content types). Seperated by comma or pressing enter maybe.

Currently I can implement tags using the JSON field but it looks unproffesional from a customer perspective, aswell as no reference/interface to speed up and make sure picking the relevant tags I want.

I wouldn't mind developing this myself and submitting as PR, Iv'e helped contribute to several emerging high profile code bases recently that are often brought up in discussions relevant to a headless CMS.

**Comment by Aurelsicoko** [comment]
I've received the idea on Product Board. We call that feature `manyWay relationship` but it will work as you described. Thank you for submitting the idea :)

**Comment by derrickmehaffy** [comment]
For reference: https://github.com/strapi/strapi/issues/1748
