### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by hansswanson** [strapi/strapi#2865]
**Informations**
- **Node.js version**:  10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: alpha 24.1 
- **Database**: MySQL
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When I install strapi I get these errors causing strapi to not work in browser:
npm WARN deprecated joi@10.2.2: This version is no longer maintained. Please upgrade to the latest version.
C:\Users\AppData\Roaming\npm\strapi -> C:\Users\Hans Swanson\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js

> strapi@3.0.0-alpha.24.1 postinstall C:\Users\AppData\Roaming\npm\node_modules\strapi
> node lib/utils/success.js

npm WARN react-ga@2.5.7 requires a peer of prop-types@^15.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ga@2.5.7 requires a peer of react@^15.6.2 || ^16.0 but none is installed. You must install peer dependencies yourself.

+ strapi@3.0.0-alpha.24.1
added 507 packages from 374 contributors in 25.395s

**Steps to reproduce the problem**
I typed npm install strapi@alpha -g into the command prompt as shown in the installation guide

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Please use either WSL or a Linux VM for the moment, windows is not currently supported (thought it is being worked on)

I am marking this as closed due to the unsupported OS, please do feel free to continue the discussion.
