### ISSUE TITLE
Cannot select first item of enum when creating an object with admin

### ISSUE THREAD

**Issue by luc-plamondon** [strapi/strapi#2866]
**Informations**
- **Node.js version**: 10.15.1 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1 
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When saving a new instance of an object using the admin panel, an error will occur if one of the fields is an enum and the selected value for this field is the first one in the list. The error message I got from the UI is: "This Question,validation,failed,type,is,not,a,valid,enum,value,for,path,type is already taken" (the extraneous commas in the error message are a bug too).

**Steps to reproduce the problem**
With the Content Type Builder, create an objet type and name it Question. 

Add one field named "type", of type "enumeration", and put "text,number,boolean,choice" as possible values for the enum. 

Still with the admin UI, create one object of type Question. In field "type", select "text" (the first item). Then save.

An red rectangle will briefly appear, saying "This Question,validation,failed,type,is,not,a,valid,enum,value,for,path,type is already taken".

**What is the expected behavior?**
Object should be saved successfully.

**Suggested solutions**
The problem does not occur when creating object through the api.

The problem does not occur when selecting another value other than the first one (index 0) in the enum.

The problem does not occur when updating an existing object. You can create a Question, select another type like "number" (the second choice), then save it, and then changing type for "text" (the first choice) and this time it will save successfully.

The problem occurs even if there is no other object, so the "is already taken" part of the error message is hard to explain.

I looked for the error message in the source code and found it in packages/strapi-hook-mongoose/node_modules/mongoose/lib/schema/string.js, function SchemaString.prototype.enum. Therefore, it might happen only with MongoDB. However, I can't trace the problem further.

It might be a conversion problem of index "0" to empty string or null when passing parameters when creating the object, but I am wild-guessing here.

**Comment by lauriejim** [comment]
Thank you to report this issue.
Can you please check this one https://github.com/strapi/strapi/issues/2471
It's the same topic.

**Comment by luc-plamondon** [comment]
It is not the same issue. Unlike issue #2471, I am not trying to save a null or empty value, nor requesting a new functionality. I am trying to set the enum with the first value in the list, whatever that value is.

I understand though that the problem might reside in the same area of code that is under scrutiny in issue #2471.

In the experiments I described above, I didn't meddle with "required" and "default" options. Reading issue #2471 gave me the idea to set the first item as the default value to my enum field. It is a workaround, but it worked.

**Comment by derrickmehaffy** [comment]
Reopening @lauriejim as the user states it isn't the same issue. I too have noticed this, you have to select another option other than the first, then reselect the first.

@soupette this one I believe is frontend based dealing with enumeration

**Comment by JaniPM** [comment]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/9007736/53203826-158f1f80-3622-11e9-8e0c-62602e78f289.png">

I just noticed the issue with first item as well. I have category field with enum values: meals,drinks,snacks,desserts Error message in the image above.

**Comment by JaniPM** [comment]
What if the UI shows default option "Select" in case where enum don't have default value? In that case user is forced to select one of the options and redux state will get correct record value which then will be correctly posted to api.

In case there is default value this don't seem to be an issue since it will be handled in the api model level.

**Comment by soupette** [comment]
Well the enum behavior is quite tricky since some users wants to have the first item auto selected and others don't. I think the best to deal with it until we figure out what is the best solution is to set your first item as the default value in your <model>.settings.json.

It will prevent the error from happening.

**cc/** @Aurelsicoko

**Comment by Aurelsicoko** [comment]
We should base the logic on this field on the default value.

- `Default value: "default"` means the enumeration field won't select any value and it'll display "Choose a category".
- `Default value: "meals"` means the enumeration field will select the `meals` as a default value.

**Comment by soupette** [comment]
ok, I'll add it then

**Comment by derrickmehaffy** [comment]
@soupette If default is empty `default: ""` then nothing should be auto select & nothing should be sent in the POST/PUT request IMO

**Comment by derrickmehaffy** [comment]
There may be a case where a user has an enum that uses the `default` as an option (while rare) it is possible and would likely cause issues down the line

**Comment by soupette** [comment]
Well I think that I should fix the select first it's not normal that you can't select the first item

> @soupette If default is empty `default: ""` then nothing should be auto select & nothing should be sent in the POST/PUT request IMO

My understanding is that and enum always needs a value right ?

**Comment by derrickmehaffy** [comment]
@soupette Seems to be mixed views on that. I've seen it where some say they need to have a value, others say that `null` is fine :man_shrugging:

**Comment by soupette** [comment]
I think that using the default value might be the best option!

**Comment by luc-plamondon** [comment]
I agree with @soupette that selecting the first item can be fixed in the first place, independently from the outcome of the rest of the discussion. However, since currently the admin UI presents the first option when you create a new object, then _saving the object without touching the field should save the first option nonetheless_, not the default value of the field. Otherwise, what you see when you save the object is not consistent with what is saved, and that's where confusion begins.

That is not the ideal behaviour but that is step number 1: it would remove the error message I encountered while doing a "legitimate" action and it would keep the UI coherent to the user, and you could close the issue.

If you want to work on step number 2, **I would strongly suggest to automatically present an empty option when displaying the enum field**. This option can be named "Select..." or be left empty, it doesn't matter _as long as the underlying behaviour is to clear the field the same way entering nothing in a text field clears it in the database_.

With that, people who need enum fields to allow empty values are happy, and people who require enum fields to always have a value are happy too because they can achieve their goal by ticking the Required attribute just like for any other field. I don't see any technical justifications to force enum fields to have a value and therefore prevent many users from using Strapi, though the feasability should be checked by the experts who wrote the different database hooks (can enum fields be nulled in any database management system? If not, is it acceptable to use a text field?).

As for when default values are set for the field, there should be no difference than with any other type of field: if a default value is set, then it is used to pre-fill (pre-select) the field when creating a new object (that is already the case). If no default value is set, then it makes sense that the empty option is pre-selected. And, if a default value is set but the user selects the empty option nonetheless, it has to work like any other field: the field is saved _with_ the default value.

**Comment by Aurelsicoko** [comment]
@luc-plamondon As discussed with @soupette will do exactly what you defined in your message.

**Comment by kenberkeley** [comment]
My current solution is:

```
non_specific,A,B,C,...
```
