### ISSUE TITLE
Cannot query "me" because of undefined model

### ISSUE THREAD

**Issue by dassany-ekino** [strapi/strapi#2867]
**Informations**
- **Node.js version**: v10.9.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.21
- **Database**: MongoDB
- **Operating system**: mac os

**What is the current behavior?**

When I try to query "me" from graphql ui, I get the error "Cannot read property 'associations' of undefined'". The error :

```
{
  "errors": [
    {
      "message": "Cannot read property 'associations' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'associations' of undefined",
            "    at .../api/plugins/graphql/services/Query.js:270:32",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "me": null
  }
}
```
**Steps to reproduce the problem**

Query "me" from graphql ui with this query : 

```
{
   me {
      _id
      username
      email
   }
}
```
and the headers : 

```
{
   "Authorization": "mytokenhere"
}
```
**What is the expected behavior?**

Returning the user with selected fields :

```
{
  "data": {
    "me": {
      "_id": "xxxxxxx",
      "username": "username",
      "email": "email"
    }
  }
}
```
**Suggested solutions**

Do not care about population when model is not defined :

```
const _populate = model 
   ? model.associations.filter(a => !a.dominant && _.isEmpty(a.model)).map(a => a.alias)
   : [];
```

**Comment by lauriejim** [comment]
Since we made update on this part there is also an issue on `...this.convertToParams(_.omit(_options, 'where'), model.primaryKey),` cause the `model` is undefined.

`Cannot read property 'primaryKey' of undefined`

**Comment by sorensenjg** [comment]
Just ran into this as well.. any idea on a fix ETA? Thanks!

**Comment by renyuanz** [comment]
Having the same issue, any updates? Thanks!

**Comment by derrickmehaffy** [comment]
I am unable to reproduce this on an admin user on Strapi v26.1

@sorensenjg & @renyuanz Can you please provide the following basic information:

```
* Node.js version: 
* NPM version: 
* Strapi version: 
* Database: 
* Operating system: 
```

**Comment by renyuanz** [comment]
```
* Node.js version:  11.7.0
* NPM version: 6.9.0
* Strapi version: v26.1
* Database: MySQL
* Operating system: macOS
```

I also just tested on a fresh install and I still can not query on "me" type as described by the original reporter, but the error message is a bit different: 

```
{
  "errors": [
    {
      "message": "Cannot read property 'primaryKey' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'primaryKey' of undefined",
            "    at /Users/renyuan/Code/issue-3113/plugins/graphql/services/Query.js:252:72"
          ]
        }
      }
    }
  ],
  "data": {
    "me": null
  }
}
```

**Comment by derrickmehaffy** [comment]
@renyuanz You are correct, I was testing with REST not graphQL.

The problem here is `_id` is being injected into graphQL instead of `id`

@lauriejim this is certainly confirmed, attempting to actually use `id`:

![image](https://user-images.githubusercontent.com/8593673/56600145-e73fa900-65ac-11e9-97e5-38f9e7cae850.png)

**Comment by derrickmehaffy** [comment]
@renyuanz for now if you need access to this route use the REST route: `/users/me` until this is fixed

**Comment by renyuanz** [comment]
@derrickmehaffy yes, I was doing that. Get us informed when it's fixed, thanks!

**Comment by derrickmehaffy** [comment]
@renyuanz I've submitted a PR that I believe fixes this, testing on my own project it appears to work but will need to make sure this works on mongo as well.

**Comment by PeterKow** [comment]
@alexandrebodin  I think this is not solved yet, at least on `Porstrgess` with `3.0.0-alpha.26.2`

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/10186048/71518275-598e2900-28b2-11ea-98d1-a9627a6dedd3.png">

**Comment by derrickmehaffy** [comment]
@PeterKow Strapi Alpha hasn't been supported in almost a year. Please test with the latest beta version (beta.18.3)

**Comment by PeterKow** [comment]
hmmm right! not sure why... when I've created new project I got alpha, but after running `yarn create strapi-app strapiBeta2` it works. This feature works, so all good. Thanks @derrickmehaffy 👍

**Comment by himanshu199728** [comment]
How will I initialize all models in business logic and use it in the context of graphqlHTTP({...})?

**Comment by onsombal** [comment]
I'm encountering similar problem on Strapi-3.1.4, but with a different error: `"errors": [{"message": "Cannot return null for non-nullable field UsersPermissionsMe.id.",`

The `GET /users/me` endpoint works perfectly.

<img width="1426" alt="Screen Shot 2020-09-13 at 7 21 23 PM" src="https://user-images.githubusercontent.com/1588266/93031125-6eece400-f5f6-11ea-8ac7-65fcc701a5e6.png">

**Comment by derrickmehaffy** [comment]
@onsombal have you made extensions to the users-permissions plugin?

**Comment by onsombal** [comment]
No, I have not made any extensions. I also configured Strapti's roles and permissions to allow "me" queries.
