### ISSUE TITLE
`strapi-hook-strapi-mongoose` is missing in your dependencies - project doesn't exist

### ISSUE THREAD

**Issue by shershen08** [strapi/strapi#2870]
**Informations**
- **Node.js version**:  10
- **NPM version**: 6.8
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: SQLite --> MonogoDB
- **Operating system**: MacOS
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Trying to add MongoDB connection

```
$: npm run start

> my-api@0.1.0 start /.../my-api
> node server.js

[2019-02-21T19:52:53.659Z] warn (hook:strapi-mongoose) `strapi-hook-strapi-mongoose` is missing in your dependencies. Please run `npm install strapi-hook-strapi-mongoose`
[2019-02-21T19:52:53.806Z] warn (hook:bookshelf) wasn't loaded due to missing key `enabled` in the configuration
```
then trying to install

```
$: npm install strapi-hook-strapi-mongoose
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/strapi-hook-strapi-mongoose - Not found
```
OK i thought maybe a typo in error message, found this
https://www.npmjs.com/package/strapi-hook-mongoose
installed - but still get the same error

**Steps to reproduce the problem**

change default database.json config from SQLite to Mongo,
run start strapi

**What is the expected behavior?**

either install needed plugin or give meaningful error message

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@shershen08 you will need to regenerate your models, models built with the bookshelf connector will not work with mongoose until the templates are merged (which has been discussed just for this reason)

An easy way to do this is to follow my "upgrade" guide: https://github.com/strapi/strapi/issues/1880

Also when installing the mongoose plugin `npm install strapi-hook-strapi-mongoose@alpha` This won't be needed in the future once Strapi moves out of beta, hence why that message is shown.

**Comment by derrickmehaffy** [comment]
You can view the template files used between bookshelf and mongoose to note the differences if you wanted to update the manually:

https://github.com/strapi/strapi/tree/master/packages/strapi-generate-api/templates/bookshelf

https://github.com/strapi/strapi/tree/master/packages/strapi-generate-api/templates/mongoose

**Comment by shershen08** [comment]
It seemed to me that the project is in early betta version so, leaving it aside for now. So  I'm not following this issue anymore. feel free to close

**Comment by asotoglez** [comment]
@shershen08  You solved the problem?

**Comment by ttawan** [comment]
Same here! please help

**Comment by dkarski** [comment]
@asotoglez, @ttawan Did you delete the .cache and build folders. before `yarn develop`.
[#rebuilding-your-administration-panel](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.16-to-beta.17.4.html#rebuilding-your-administration-panel)
