### ISSUE TITLE
Error with project cloned

### ISSUE THREAD

**Issue by Geoide** [strapi/strapi#2874]
**Informations**
- **Node.js version**: 11.2.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mongodb
- **Operating system**: OSX
- **(Optional) Link to your Project**: 

**What is the current behavior?**
with npm run I'm getting:

```
(node:10761) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_id' of null
    at permissions.reduce (/Users/javi/repos/ayto2/ayto2-backend/plugins/users-permissions/services/UsersPermissions.js:319:120)
    at Array.reduce (<anonymous>)
    at Object.removeDuplicate (/Users/javi/repos/ayto2/ayto2-backend/plugins/users-permissions/services/UsersPermissions.js:315:31)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:10761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10761) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-02-23T11:10:06.468Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-02-23T11:10:06.469Z] warn Perhaps you forgot to call it?
```

**Steps to reproduce the problem**

I've configured a strapi project in a computer (OSX Mojave). I've created some collections and documents included a user admin. All working correctly. 

I've push the project in my bitbucket private repository.

In a second computer (OSX High Sierra) I've cloned the project and I've run "npm install" (I've also tried with/without "npm run setup" after" npm i") and mongorestore my data base.

When I run "npm start" (or "strapi start") I'm getting the error.

When I delete the data restored in mongo strapi works and I can go to the admin panel but when I try to create a new collection I'm getting a "internal server error". I can't create any new data.

The same repository pushed on prod env (aws linux), all is working as expected following the same steps and mongo data.

**What is the expected behavior?**

Show no error

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @Geoide !
Can you give me the full output of `strapi -v` because version `6.4.1` of Strapi doesn't exist.

**Comment by Geoide** [comment]
3.0.0-alpha.23.1

6.4.1 is the npm version, sorry.

**Comment by lauriejim** [comment]
Can you try with last version of Strapi (alpha.24.1) please.

**Comment by derrickmehaffy** [comment]
@Geoide delete your package-lock.json file and make sure it is in your .gitignore

**Comment by mrzapp** [comment]
@lauriejim I'm experiencing this exact error, and I don't have a `package-lock.json` file.

I'm using the latest docker image, 3.3.4
