### ISSUE TITLE
GraphQL where relation aggregate count null

### ISSUE THREAD

**Issue by atomxsk8** [strapi/strapi#2875]
**Informations**
- **Node.js version**: v11.1.0
- **NPM version**: 6.4.1
- **Strapi version**: * 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: OSX
- **(Optional) Link to your Project**: 

**What is the current behavior?**

GraphQL where relation aggregate count null

**Steps to reproduce the problem**
- Install Strapi & New Project & Install plugins GraphQL
- Create Model with relation "has one"
<img width="1058" alt="screen shot 2019-02-23 at 7 53 14 pm" src="https://user-images.githubusercontent.com/15246539/53286679-b3aaf300-37a4-11e9-863b-3320b0d09c4b.png">

- Go to http://localhost:1337/graphql and try search with relation
<img width="320" alt="screen shot 2019-02-23 at 7 49 54 pm" src="https://user-images.githubusercontent.com/15246539/53286652-5616a680-37a4-11e9-9042-76c5de4c7efb.png">

**What is the expected behavior?**

When GraphQL search with relation can count

**Suggested solutions**

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2151

> This is a templated message
