### ISSUE TITLE
Non required float

### ISSUE THREAD

**Issue by phmatray** [strapi/strapi#2876]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: Last Docker version (Strapi v3.0.0-alpha.24.1)
- **Database**: MongoDB
- **Operating system**: MacOS
- **(Optional) Link to your Project**: 

**What is the current behavior?**

<img width="536" alt="capture d ecran 2019-02-23 a 16 37 13" src="https://user-images.githubusercontent.com/9035444/53288522-5a819600-3789-11e9-9d6e-3231edecd596.png">

**Steps to reproduce the problem**

<img width="750" alt="capture d ecran 2019-02-23 a 16 29 45" src="https://user-images.githubusercontent.com/9035444/53288541-88ff7100-3789-11e9-8717-afffeadffde0.png">

<img width="747" alt="capture d ecran 2019-02-23 a 16 29 57" src="https://user-images.githubusercontent.com/9035444/53288527-6f5e2980-3789-11e9-8465-f5c53ed53f8b.png">

**What is the expected behavior?**
The field in the DB must not be saved.

**Suggested solutions**

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2591

> This is a templated message
