### ISSUE TITLE
Boolean parameters written as Integer to SQLite

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2879]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: SQLite
- **Operating system**: Linux

**What is the current behavior?**

Boolean parameters written as Integer to SQLite (email-confirmation -> confirmed: true written as confirmed: 1)

So that (as example) user can't use any routes, because system expect true in confirmed.

**Steps to reproduce the problem**

1. Enable email confirmation in admin panel
2. Register account
3. Confirm it via email link

**What is the expected behavior?**

Strapi writes boolean params as boolean,
so that after confirmation user can use routes for his permission group.

**Comment by lauriejim** [comment]
Hello @EpicUsaMan!

See the documentation about SQLite https://www.sqlite.org/datatype3.html

`2.1` **Boolean storage** SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).

So it's normal.

> because system expect true in confirmed.

Can you explain what you are talking about please.

**Comment by EpicUsaMan** [comment]
Hi, @lauriejim .

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js

Check line 35:
```
if (_.get(await store.get({key: 'advanced'}), 'email_confirmation') && ctx.state.user.confirmed !== true) {
      return handleErrors(ctx, 'Your account email is not confirmed.', 'unauthorized');
}
```

```
ctx.state.user.confirmed !== true
```

With SQLite this condition equals to

```
1 !== true
```

Also, check https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js on line 60

```
if (_.get(await store.get({key: 'advanced'}), 'email_confirmation') && user.confirmed !== true) {
        return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Auth.form.error.confirmed' }] }] : 'Your account email is not confirmed.');
}
```

Where
```
user.confirmed !== true
```
Equals to
```
1 !== true
```

And so one. In scope of this behavior of SQLite need review all cases where anyVariable !== true or  anyVariable === true
