### ISSUE TITLE
Can't store array with JSON input

### ISSUE THREAD

**Issue by Vadorequest** [strapi/strapi#2882]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**: 
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: Postgre 10
- **Operating system**: MacOS

**What is the current behavior?**

I'm encountering several issues, I believe they're related to the data type JSON.

At first, I was using node 11 (forgot to change) and I was getting `this found is already taken` as toast error message when creating an entity. I switched to node 10 and encounter the following:

![image](https://user-images.githubusercontent.com/3807458/53304855-95afc200-387a-11e9-9d39-00e3cc613833.png)

![image](https://user-images.githubusercontent.com/3807458/53304859-9ba5a300-387a-11e9-97fd-06a0355b3d12.png)
> [2019-02-24T20:23:05.938Z] error update "campuses" set "formationTypes" = $1, "name" = $2, "programs" = $3, "state" = $4, "contacts" = $5, "label" = $6, "school" = $7, "id" = $8, "updated_at" = $9 where "id" = $10 - invalid input syntax for type json

If I replace my array by an empty object, it saves the entity properly.
I believe a better error message would be useful, especially by identifying the error field.

Also, aren't arrays valid JSON? And if they're not supported, why does the editor doesn't warn about it?

I tried saving a JSON object as a property as follow, and it worked fine:

```json
{
  "a": []
}
```

But the following didn't work:
```json
[{}, {}]
```

I guess arrays aren't allowed at top level? Is it designed behaviour or a DB limitation?

My use case with arrays was that I expect the structure to change soon in the future and want to avoid creating a whole Content Type for something that'll likely change a lot in a short future.

**Comment by lauriejim** [comment]
Thank you for this report.
Feel free to investigate on this issue. We will appreciate your contribution on this issue.
Still we work on other issues and product evolution we will not have the time for this issue.

**Comment by Vadorequest** [comment]
@lauriejim Could you please clarify the usage of the JSON data field? Are only objects allowed and not arrays?

**Comment by derrickmehaffy** [comment]
@Vadorequest both objects and arrays should work as they are both valid JSON options

**Comment by Vadorequest** [comment]
Thanks, that's what I assumed first. I guess something is broken then.

I won't investigate further since I won't be using Strapi furthermore, not stable enough yet for production-grade product (as stated, still in beta)

Still, looks like a really cool project, I'd totally have used it it it had been stable, having a CMS+API is a great thing, especially if they can both live in their own environment (as it is possible today) 🚀

**Comment by lauriejim** [comment]
@Vadorequest Feel free to help us to make it more stable faster to let you use it in production soon.
We need community help. The community is the strong of Strapi, but we need your contribution.

**Comment by Vadorequest** [comment]
I wish I could, really. Don't have the time though. Someday I must find some time to participate to cool open source projects like Strapi.

**Comment by ly525** [comment]
@lauriejim I meet the same issue, Strape could not save Array JSON when Postgre as DB

**Comment by rejifald** [comment]
It probably related to https://github.com/bookshelf/bookshelf/issues/1328

**Comment by rejifald** [comment]
I think solution is to use this bookshelf plugin https://github.com/seegno/bookshelf-json-columns

**Comment by doublemarked** [comment]
It seems that there's an incoming fix via #3664 , but in the meantime I've written the following snippet to work around the problem:
```
    Object.keys(model.constructor.attributes).forEach(k => {
      if (model.constructor.attributes[k].type === 'json') {
        const value = model.get(k);

        if (Array.isArray(value)) {
          model.set(k, JSON.stringify(value));
        }
      }
    });
```

Stick it in a `beforeSave` to coerce your Arrays into strings, which Bookshelf will pass on to PG without processing, and which PG will dutifully parse and store as a JSON array.

**Comment by doublemarked** [comment]
I'm still experiencing this problem in 3.0.0-beta.16

**Comment by guoyunhe** [comment]
I still have this issue with strapi 3.2.3 and mongodb...

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by guoyunhe** [comment]
My issue was solved by upgrading to 3.2.4.

**Comment by digitaldesigndj** [comment]
I think I am seeing this issue in `3.2.5`?

**Comment by derrickmehaffy** [comment]
> I think I am seeing this issue in `3.2.5`?

Can you provide an example of your request and any error response you get (if it's a 400 code it will be returned directly to you, if it's a 500 code you'll need to check the server console.
