### ISSUE TITLE
Decimal/Float field gives an error when empty

### ISSUE THREAD

**Issue by secretlifeof** [strapi/strapi#2884]
**Informations**
- **Node.js version**: v11.9.0
- **NPM version**: 6.5.0
- **Strapi version**: v3.0.0-alpha.24.1
- **Database**: MongoDB v4.0.3
- **Operating system**: MacOs Mojave 10.14.3

**What is the current behavior?**
Similar to this graphQL does not seem to return null when field is empty.
[https://github.com/strapi/strapi/issues/2000](url)

```
graphQLErrors:
   [ { message: 'Cast to Number failed for value "" at path "price"',
       locations: [Array],
       path: [Array],
       extensions: [Object] } ],
  networkError: null,
  message:
   'GraphQL error: Cast to Number failed for value "" at path "price"',
  extraInfo: undefined 
```

**Steps to reproduce the problem**
Add a decimal or float field a try to graphQL this empty field.

**What is the expected behavior?**
I don't now much about graphQL but how I understand it from the other issue it is suppose to return null.

**Suggested solutions**
I don't know how to fix it. Adding default value to "0" is a quick-fix.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2591

> This is a templated message

**Comment by secretlifeof** [comment]
Sorry
