### ISSUE TITLE
How to fetch all user from another webhook model ?

### ISSUE THREAD

**Issue by MatthD** [strapi/strapi#2885]
**Informations**
- **Node.js version**: v10.9
- **NPM version**: 6.2
- **Strapi version**: v3.0.0-alpha.24
- **Database**:  mongodb
- **Operating system**: OSX mojave

**What is the current behavior?**

I need to get the User list in a webhook after a create on a model (the webhook is not about user , it's another one). I did not found the way to be able to do it.

For exemple when adding a new post I need to fetch all the user to send them a notification;

**Steps to reproduce the problem**

**I tried with graphql first:** 
In v3 I did not found the way to use the global variable as graphql, in V1 it was possible :
https://strapi.io/documentation/1.x.x/graphql.html#execute-simple-query

**Then I tried with the[ axios method](https://strapi.io/documentation/3.x.x/guides/webhooks.html),**
but I am sure this is not the right way, (I Should log in, get the admin token, request my own api ... )
😅

Finaly I tried to found a way to call controller in the variable strapi.plugins["users-permissions"].controller. but got an error .

Please could you explain the right way to fetch a model inside another webhook model

**What is the expected behavior?**

Get the list of users inside another webhook model

Ps: I am using the user-permissions model & I do not have any model called "User" inside my strapi.models because I use an extended model.

**Comment by lauriejim** [comment]
Hello @MatthD !

I think you can write in your `.api/:model/servise/:mode.js` a function `sendNotification` that fetch users and send them an email.

Then in life cycle `afterSave` function you call this service with `strapi.api[:model].services[:model].sendNotification();`

To fetch user in your service function you can use the fetchAll service function of the **Users & Permissions** plugin with `strapi.plugins['users-permissions'].services.user.fetchAll()`

And then you map the value you got to send email.

> Hop it help! Let me know if you have other questions.
