### ISSUE TITLE
The save button in the content manager does not work!

### ISSUE THREAD

**Issue by Sentinas** [strapi/strapi#2886]
**Informations**
- **Node.js version**: 10.5.0
- **NPM version**: 6.1.0
- **Strapi version**: v3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**:  SMP Debian 3.16.59-1

**What is the current behavior?**
The save button in the content manager does not work if the model contains fields with the date type.
I use translator.

**Steps to reproduce the problem**
1. Create a new model in the content manager.
2. Create a date field in the model
3. Add an entry to the collection.
4. Click to edit the added entry.
5. The Save button does not work. Any changes cannot be saved.

**What is the expected behavior?**
When changing data, the save button leads to saving the changes in the database.

**Suggested solutions**
If the model removes all fields with the date type, everything works correctly.

**Comment by benforshey** [comment]
Hi, @Sentinas . I think you'll find this related to #2783.

**Comment by Sentinas** [comment]
I will add. I deleted the content manager in version 23.1 via plugins and installed the manager again. An error has occurred. Before reinstalling the content manager, the ability to save collections with date type fields was.

**Comment by lauriejim** [comment]
What are logs your have in the update request or in your terminal or in your browser console.
