### ISSUE TITLE
Default false for boolean field

### ISSUE THREAD

**Issue by chochihim** [strapi/strapi#2888]
**Informations**
- **Node.js version**:  v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.24.1
- **Database**: PostgreSQL
- **Operating system**: macOS 10.13.6
- **(Optional) Link to your Project**: 

**What is the current behavior?**
If I save a new entry for a content type with boolean field (without clicking the toggle which shows "OFF" by default), the field will be saved as NULL in database.

**Steps to reproduce the problem**

**What is the expected behavior?**
That field should be saved as false.

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
Related: https://github.com/strapi/strapi/pull/2781

All of the "metadata" options on fields in a model are not currently being used on bookshelf.

This includes:

- Required
- Unique
- Default

**Comment by chochihim** [comment]
I close this issue since it is addressed in other PR.
