### ISSUE TITLE
Problem generating ids from providers

### ISSUE THREAD

**Issue by Tansito** [strapi/strapi#2889]
**Informations**
- **Node.js version**: >=10.0.0
- **NPM version**: >=6.0.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: Mongo
- **Operating system**: MacOS Mojave 10.14.3

**What is the current behavior?**
Users return sometimes the fields `id` and `_id` and other times return only `_id`. Example:
```
[{
  blocked: false,
  confirmed: true,
  id: "5c4a5121026f81005561f3e9",
  provider: "local",
  role: {_id: "5c4a494e414922005bca9ed2", name: "Authenticated", type: "authenticated" },
  _id: "5c4a5121026f81005561f3e9",
},
{
  blocked: false,
  confirmed: false,
  provider: "google",
  role: {_id: "5c4a494e414922005bca9ed3", name: "Authenticated", type: "authenticated" },
  _id: "5c5c525817c4bf00567e8c89"
}]
```

**Steps to reproduce the problem**
If I generate the user from the panel administrator everything is correct but If I use a provider to generate the user automatically this generates the `_id` but no the `id`. 

**What is the expected behavior?**
Every entity should return `_id` and `id`.

**Comment by lnanhkhoa** [comment]
i have same issue

**Comment by Tansito** [comment]
Going more in depth with the issue I found a curious scenario. If you use the **Users** API to retrieve the users data (`GET /users` or `GET /users/:_id`) the original issue persist, example:
```
{
  "_id": "5c5c7f5eb228c600547cb05e",
  ...
  "provider": "google"
  ...
}
```
But If the user's data comes from the relation between `users` and other model it comes with the `id`, example:
```
{
  "identifier": 2,
  "users": [
    {
      "_id": "5c5c7f5eb228c600547cb05e",
       .....
      "provider": "google",
      "role": "5c4a494e414922005bca9ed3",
      "__v": 0,
      ........
      "id": "5c5c7f5eb228c600547cb05e"
    }
  ]
}
```
I hope this helps a bit.

**Comment by lauriejim** [comment]
Thank you fir this report! 
Actually we have an issue here https://github.com/strapi/strapi/issues/1274 about using only `id`.

So I close this issue.
