### ISSUE TITLE
SQLite existing table

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2892]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: * 3.0.0-alpha.23.1
- **Database**: SQLite
- **Operating system**: Linux

**What is the current behavior?**

SQLITE_ERROR: table `basket` already exists
logged in console
strapi can't start

**Steps to reproduce the problem**
1. Create many api when strapi is started
2. Try to change one of them

**What is the expected behavior?**

Strapi should start

**Suggested solutions**
Recreate table from model settings

**Comment by derrickmehaffy** [comment]
@EpicUsaMan you will need to open up your SQLite DB in an editor and delete the table, there is likely a conflict preventing SQLite from updating it.

SQLite support is new, and is expected to have bugs like this.

**Comment by EpicUsaMan** [comment]
@derrickmehaffy I know, but bug report is bug report ;)

**Comment by derrickmehaffy** [comment]
@EpicUsaMan the problem here is, there really isn't a "simple" solution to modifying an existing table in SQLite. Since SQLite doesn't have a real `alter table` function. What Strapi is basically doing right now is copying your existing tables data to a temp one and renaming it.

**Comment by kenzicode** [comment]
> 
> 
> @EpicUsaMan you will need to open up your SQLite DB in an editor and delete the table, there is likely a conflict preventing SQLite from updating it.
> 
> SQLite support is new, and is expected to have bugs like this.

How can to do that?? I'm using mongodb not sqlite.

**Comment by eminx** [comment]
I also use MongoDB and do not know why there's even SQLite in the context... 

Could anyone please update me on this? @derrickmehaffy

**Comment by derrickmehaffy** [comment]
@kenzicode @eminx you both likely started a project using quickstart which uses SQLite. In that case your models were also built using the bookshelf hook.

You will need to make sure you have the mongoose hook installed, configured the mongoDB in your database.json and regenerate all your models as the configs, controllers, and services are based on the hook template you choose. You can use my method: https://github.com/strapi/strapi/issues/1880

With regards to moving between different database types (Mongo/SQL) there is a feature request that is required to be able to do that: https://github.com/strapi/strapi/issues/2912

**Comment by lauriejim** [comment]
This issue look fixed in the last beta version (beta.15)
I close this issue.
