### ISSUE TITLE
Add id option in filter of content manager

### ISSUE THREAD

**Issue by kenberkeley** [strapi/strapi#2893]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: PostgreSQL 10
- **Operating system**: Windows 10

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/13287948/53456820-ee05e000-3a83-11e9-9920-f5822c10b15a.png)

**What is the expected behavior?**
There should be an "id" option

**Comment by kenberkeley** [comment]
In other words, how can I filter by id?

**Comment by derrickmehaffy** [comment]
@kenberkeley I don't believe you can using the filters yet. The entire content-manager plugin is in the process of being rebuilt.

**Comment by soupette** [comment]
I'm just questioning the use of filtering by id, maybe you can use the search?

**Comment by kenberkeley** [comment]
@soupette ID match is the most efficient way. Also, fulltext search does not work for Chinese from time to time.

**Comment by Aurelsicoko** [comment]
Interesting... @soupette how difficult it would be to add the id attribute?

**Comment by soupette** [comment]
@lauriejim it has been added in #3633 

<img width="761" alt="Screenshot 2019-07-31 at 14 57 43" src="https://user-images.githubusercontent.com/13311463/62213608-94dc0880-b3a3-11e9-8d05-e18e71eeed3a.png">

**Comment by Mikkou** [comment]
I have a problem with filter by id.
I try to use this value from one item in the collection - 5e13da19ae4c080062d7b12e.
![image](https://user-images.githubusercontent.com/22446720/76152020-f7308080-60cb-11ea-85a9-e088b91c8253.png)
![image](https://user-images.githubusercontent.com/22446720/76152027-0d3e4100-60cc-11ea-8951-34fc4105b8a5.png)
