### ISSUE TITLE
How to work with existing table with column name being a reserved word?

### ISSUE THREAD

**Issue by chochihim** [strapi/strapi#2894]
**Informations**
- **Node.js version**:  v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**:  * 3.0.0-alpha.24.1
- **Database**: * PostgreSQL
- **Operating system**: * macOS 10.13.6
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Below words are not allowed to be used as attribute name
```js
const reserved = [
    'id',
    'set',
    'value',
    'emit',
    'on',
    'once',
    'listeners',
    'removeListener',
    'collection',
    'db',
    'isModified',
    'isNew',
    'get',
    'modelName',
    'save',
    'schema',
    'toObject',
    'validate',
    'remove',
    '_pres',
    '_posts',
  ];
```
But one of my existing table has column name being one of the above

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**
I would like to confirm if it is possible to workaround it. If not, I would like to know if it is difficult to support this (if it is easy enough I can submit PR)

**Comment by derrickmehaffy** [comment]
@chochihim the short answer is no due to most of these being javascript reserved, the reserve list was added to help prevent any errors that come up when building models. It would probably be best to structure a different name for the column.

**Comment by chochihim** [comment]
@derrickmehaffy It feels wrong that naming a database column should take limitation of the framework into consideration. Please consider re-visiting this problem in the future.

Anyway, I find that `value` might be able to be removed from the reserved list (I have a table which consists of three columns only (id, key, value) and this is what leads me to open this bug report)

There was an issue [https://github.com/strapi/strapi/issues/1027](https://github.com/strapi/strapi/issues/1027) about it. After a rough check, it looks like the error is really due to [https://github.com/strapi/strapi/blob/c10124161108fda9710fc49ae15154e4612846f4/packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js#L102](https://github.com/strapi/strapi/blob/c10124161108fda9710fc49ae15154e4612846f4/packages/strapi-plugin-content-manager/admin/src/containers/EditPage/saga.js#L102)

I tried to create simple content type and log the results:
```js
const record = {
}
```

**Comment by derrickmehaffy** [comment]
@chochihim I'm not a member of the Strapi team. You are welcome to try and debug it and find a solution to submit a PR.

**Comment by lauriejim** [comment]
Yap that it's a good point. I share this with the team.

**Comment by Aurelsicoko** [comment]
I've no answer for now... the only workaround that I've in mind is to rename the column name in the existing table. If you use one of these reserved words it might produce an error later.
