### ISSUE TITLE
Custom installation,manual settings - fail 

### ISSUE THREAD

**Issue by DanLahav-TG** [strapi/strapi#2897]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**:  mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64)
- **Operating system**: 	Ubuntu 18.04.2 LTS
- **(Optional) Link to your Project**: 

**What is the current behavior?**
on installation:
 internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/tmp/strapi8d602a19837c/node_modules/mysql/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at shell.exec (/home/dan/Public/strapi/packages/strapi-generate-new/lib/before.js:324:26)
    at /home/dan/Public/strapi/packages/strapi-generate-new/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:970:16)

**Steps to reproduce the problem**

start custom installation

**What is the expected behavior?**
successful installation  

**Suggested solutions**

**Comment by Ilane91** [comment]
👍 
Happens to me as well when I select a custom installation.
Error is thrown a few seconds after custom installation is selected, regardless of which database option. is selected

**Comment by derrickmehaffy** [comment]
@DanLahav-TG @Ilane91 try cleaning your npm cache

**Comment by DanLahav-TG** [comment]
sudo npm cache clear --force

didn't help

**Comment by ikesler-tenengroup** [comment]
Seems working for me. MariaDB, nodej 11 (installed using nvm) - maybe depends on Node version?

**Comment by derrickmehaffy** [comment]
@DanLahav-TG I believe the problem is with your npm install, you should never need to use sudo to run npm commands. I would suggest that you move your npm global packages to your user, reinstall strapi "globally" then try again.

A simple guide to moving your npm global packages to your user is here: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

I am unable to duplicate this issue using the above changes or as the root user on a fresh install.

**Comment by DanLahav-TG** [comment]
installing node with nvm solved it

**Comment by ShreyashSalian15** [comment]
Hello there I wanted to integrate MariaDB in strapi but when I execute this command "npx create-strapi-app my-project
" and select custom setting I am not getting an option of selecting MariaDB I am getting only these three options did anyone know how am I supposed to do this?

![image](https://user-images.githubusercontent.com/105337128/168775566-6464d9b7-a2f1-4606-9a6d-8de23fa704d0.png)

**Comment by derrickmehaffy** [comment]
You just select MySQL. We no longer set custom values for that list as it's based on the Knex dialects and MySQL/MariaDB both use the same dialect (mysql). You can use MariaDB still.
