### ISSUE TITLE
SQLITE_READONLY: attempt to write a readonly database

### ISSUE THREAD

**Issue by Kriskasz** [strapi/strapi#2898]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: mongodb v4.0.6
- **Operating system**: Ubuntu 16.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I installed Strapi 4 day ago to test it. Then I run server and everything was ok. I even created api, sent something to it and all was working. Yesterday I had some time so I want to test this system again but for my  surprise when I type npm start it showed me SQLITE_READONLY: attempt to write a readonly database. I'm using mongodb so I don't now why I'm getting error about sqlite? Any suggestion?     

**Steps to reproduce the problem**

 

**What is the expected behavior?**

 

**Suggested solutions**

**Comment by lauriejim** [comment]
Hum that's strange!
Did you have `strapi-hook-bookshelf` installed some where, or did you try to migrate from SQL to NoSQL database ?

**Comment by Kriskasz** [comment]
No, I just installed strapi with Mongodb and that's all. Where can I find
file to change db configuration? Why it want to connect to SQLITE not to
Mongodb?

**Comment by derrickmehaffy** [comment]
@Kriskasz likely because you setup your project as quick start. all of your models are setup to use bookshelf templates, you will need to regenerate them and copy over your `model.settings.json` files. you can use my "Upgrade" guide to fix your project.  https://github.com/strapi/strapi/issues/1880

**Comment by Sonicfury** [comment]
I just had a flash. I just had the same issue for the third time (three different projects) in a few days. If you, like me, are on macOs and especially on Catalina, fixing permissions may solve the issue. It did for me.
You shoud be able to use the First Aid in Disk Utility but if not just type the following command in a shell `diskutil resetUserPermissions / `id -u`
