### ISSUE TITLE
Showing/Filtering on parent related field in child list view in admin UI

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#2900]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
What is the recommended approach to show and filter on a parent related field on the child list view in the admin UI.
For example, on the child Product list view I want to see/filter the parent Category name related to the Product. Right now I can only see the Category name on the Product detail/edit view.

Would be helpful to see this Category instead of having to click through every products to see it.

**Comment by derrickmehaffy** [comment]
Related fields current are not able to be added to the list view. I believe @soupette does plan to add this in the future but he is quite busy working on other stuff at the moment.

**Comment by laportem** [comment]
@[derrickmehaffy] thanks for the quick response, understood how busy the guys are. I was also hoping to get some best practices to do it ourselves

**Comment by derrickmehaffy** [comment]
@laportem It would require some heavy modification to the adminUI

**Comment by Aurelsicoko** [comment]
I'm closing this issue because there is already a dedicated card on our public roadmap (see https://portal.productboard.com/strapi/c/49-display-relational-field-in-list-view).
