### ISSUE TITLE
Babel 7: Back End Support

### ISSUE THREAD

**Issue by DaneTheory** [strapi/strapi#2904]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**NOTE**
_This applies to new Strapi projects built using_ `strapi new <PROJECT_NAME> --dev`

## CURRENT
Currently, Strapi supports newer JavaScript features for Front End related development (the Admin panel specifically).

## ISSUE
However, utilizing the same development flow for Back End related development is restrictive in implementation. 

## FUTURE
This feature request aims to address this issue by utilizing common, well maintained modules that support this design architecture.  

**Specifically**
- _devDependencies_
  - @babel/core
    - https://babeljs.io/docs/en/babel-core
  - @babel/register
    - https://babeljs.io/docs/en/babel-register
  - @babel/preset-env
    - https://babeljs.io/docs/en/babel-preset-env
- _dependencies_
  - @babel/polyfill
    - https://babeljs.io/docs/en/babel-polyfill

### IMPLEMENTATION
Before the earliest point in Strapi's lifecycle (bootstrap.js?), include a "pre-bootstrap" file which runs:

**_pre-bootstrap.js_**
```
require('@babel/register')({
  presets: [
    [
      require.resolve('@babel/preset-env'),
      {
        targets: {
          node: 'current'
        },
        useBuiltIns: 'entry'
      }
    ]
  ],
});
require('@babel/polyfill');
```

**So that, by the time bootstrap is run, the ability to write the following code in works**

> **_Assumes `pwd` returns something to the effect of_**
> `/Users/<YOUR_USER>/<PATH_TO_STRAPI>/config/functions`

**_FooBar.js_**
```
const foo = bar => {
  const baz = 'Some baz Stuffs'
  return `
    ${baz}
    -------------------
    Now Bar Argz Stuffs:
    ${bar}
    -------------------
  `
}
const FooBar = msg => {
  foo(msg)
  return `Hello From FooBar! ${msg}`
}
export default FooBar
```

**_bootstrap.js_**
```
'use strict';

import FooBar from './FooBar'

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 */

module.exports = cb => {
  console.log(FooBar('A message...'))
  cb();
};
```

**And when running `strapi start`**

> **_Assumes `pwd` returns something to the effect of_**
> `/Users/<YOUR_USER>/<PATH_TO_STRAPI>/`

The output to the console is 
> `Hello From FooBar! A message...`

**Other benefits could also include**
- Using `async/await` in place of callbacks to handle bootstrap

**Comment by DaneTheory** [comment]
Apologies if this is documented elsewhere. I'm having difficulty implementing this now on my end, and have looked through Strapi documentation heavily. I've gone through every tutorial online I can find, PR's and previously closed issues on the Strapi repo. However, I cannot find a working solution. Thanks!

**Comment by DaneTheory** [comment]
If anything, documentation covering Strapi's lifecycle would be very helpful Something equivalent to Fastify. 
For reference:
https://lmammino.github.io/fastify/docs/lifecycle/
If this isn't the level of extendability Strapi is meant to offer developers, please let me know.

**Comment by alexandrebodin** [comment]
Hi @DaneTheory 

Thanks you for your feedback 👍 

I think you could try to had your babel logic in the `server.js` file generated in the root directory. 
Let me know if that helps :)

Generally speaking `@babel/register` isn't supposed to be used for production so you would need to build the codebase with babel before deployment.

**Comment by DaneTheory** [comment]
Hi @alexandrebodin 

Thanks for taking the time to reply :beers:

I agree with foregoing `@babel/register` and instead utilizing **one** of the **two** following options:

### ONE
* **devDependencies**
  - @babel/cli
    - https://babeljs.io/docs/en/babel-cli
  - @babel/core
    - https://babeljs.io/docs/en/babel-core
  - @babel/node
    - https://babeljs.io/docs/en/babel-node
  - @babel/preset-env
    - https://babeljs.io/docs/en/babel-preset-env
  - babel-plugin-dynamic-import-node-babel-7
    - https://github.com/shelldandy/babel-plugin-dynamic-import-node-babel-7#readme

With the addition of a `.babelrc` file containing:
```
{
    "presets": ["@babel/preset-env"],
    "plugins": ["dynamic-import-node-babel-7"]
}
```
Then replacing scripts run using `node` to `babel-node`. Such as:
`"start": "node server.js"`
to
`"start": "babel-node server.js"`

The downside to this approach is it removes `strapi` as a `CLI` tool for the dev tool belt. Not cool.  

### TWO
_Not to double post on purpose, but..._

> If anything, documentation covering Strapi's lifecycle would be very helpful Something equivalent to Fastify.
For reference:
https://lmammino.github.io/fastify/docs/lifecycle/
If this isn't the level of extendability Strapi is meant to offer developers, please let me know.

As of now, ESNext features work as expected by the time `server.js` is run. So simply swapping out:
- `const strapi = require('strapi')`
for
- `import strapi from 'strapi'` 
in `server.js` does work.

**However**,
The problem I'm looking to solve requires a solution that is run at the same time as either `hooks` or `functions` are executed. The way the documentation reads, I assumed `functions`.  Particularly, bootstrap.js`

> _**For reference:** https://strapi.io/documentation/3.x.x/configurations/configurations.html#functions_

Because of the line:
_The bootstrap function is called at every server start. You can use it to add a specific logic at this moment of your server's lifecycle._
_Here are some use cases:_
_**Create an admin user if there isn't.**_

Bingo. It's that particular piece of functionality I'd like to implement, alongside a couple of other needed tweaks to get Strapi working correctly behind my API Gateway. 

**At the moment**
1. Running `npm i axios`
2. Adding `import axios from 'axios'` into `./config/functions/bootstrap.js`
3. Running `strapi start` 

**Yeilds**
* debug ⛔️ Server wasn't able to start properly.
* error Unexpected identifier /<PATH>/<TO>/<PROJECT>/config/functions/bootstrap.js:8

> import axios from 'axios'
> SyntaxError: Unexpected identifier
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Strapi.loadFile (/<PATH>/<TO>/BASE_STRAPI>/packages/strapi/lib/utils/index.js:30:12)
    at Object.setConfig (/<PATH>/<TO>/BASE_STRAPI>/lib/utils/index.js:39:19)
    at p (/<PATH>/<TO>/BASE_STRAPI>/packages/strapi/lib/utils/index.js:115:26)
    at /<PATH>/<TO>/BASE_STRAPI>/packages/strapi/node_modules/async/dist/async.js:1135:9
    at eachOfArrayLike (/<PATH>/<TO>/BASE_STRAPI>/packages/strapi/node_modules/async/dist/async.js:1069:9)
    at eachOf (/<PATH>/<TO>/BASE_STRAPI>/packages/strapi/node_modules/async/dist/async.js:1117:5)

**Comment by alexandrebodin** [comment]
@DaneTheory If your are running babel-node all the code will be run with babel. What you are trying to do should work.

Can you share your `.babelrc` file / a repo to test ?
