### ISSUE TITLE
Model definition error is not handled

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2908]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: * 3.0.0-alpha.23.1
- **Database**: SQLite
- **Operating system**: Linux

**What is the current behavior?**

When `modelOne` is not have relation attribute, but `modelTwo` have relation attribute with next code `{ "collection": "modelOne"` (without via) I receive next unhandled error:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toLowerCase' of undefined
    at Function.plural (src/backend/node_modules/pluralize/pluralize.js:133:24)
    at _.get._.map.table (src/backend/node_modules/strapi-hook-bookshelf/lib/index.js:857:80)
```

After fixing it I receive `SQLITE_ERROR: near "ALTER": syntax error`

When I destroy all tables all works as expected

**Steps to reproduce the problem**
1. Create model with settings like this one:

```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "featureKey",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "key": {
      "type": "string",
      "required": true
    }
  }
}
```

2. Create second model with settings like this:
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "feature",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "key": {
      "collection": "featureKey"
    }
  }
}
```

3. Run strapi

**What is the expected behavior?**

Should display error message like "Something wrong with `modelTwo`"

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue.
Can you please investigate on this issue and submit a PR to fix it.
Will appreciate your contribution!

**Comment by EpicUsaMan** [comment]
@lauriejim Hi ;)
Okay ;)

**Comment by lauriejim** [comment]
I close this issue -  there is no update about the PR to add this management.
This only happen if you create your relation manually - using the admin panel there is not issue.
and something you not notify is you have a message before that say the key you have an issue with.
