### ISSUE TITLE
Query users and other resource in one step with graphQL does not work

### ISSUE THREAD

**Issue by sebastian-ludwig** [strapi/strapi#2913]
**Informations**
- **Node.js version**: 11.8.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: MacOS

**What is the current behavior?**
I have a query to get all users (users-permissions_user) and a custom Content-Type (e.g. categories):
```
query ListCategoriesAndUsers {
  categories {
    _id
  }
  users {
      _id
    }
  }
```
sometimes it returns correct:
```
{
  "data": {
    "categories": [
      {
        "_id": "5c697c9ba801582375a3d487"
      },
      {
        "_id": "5c697caba801582375a3d488"
      },
      {
        "_id": "5c697cb9a801582375a3d489"
      },
      {
        "_id": "5c697cc4a801582375a3d48a"
      }
    ],
    "users": [
      {
        "_id": "5c695b204dded412739eaef3"
      },
      {
        "_id": "5c7704ea2811721acd75139c"
      },
      {
        "_id": "5c77ab6387cd83139588b1ae"
      }
    ]
  }
}
```
but sometimes it returns just a duplicate of users for categories:
```
{
  "data": {
    "categories": [
      {
        "_id": "5c695b204dded412739eaef3"
      },
      {
        "_id": "5c7704ea2811721acd75139c"
      },
      {
        "_id": "5c77ab6387cd83139588b1ae"
      }
    ],
    "users": [
      {
        "_id": "5c695b204dded412739eaef3"
      },
      {
        "_id": "5c7704ea2811721acd75139c"
      },
      {
        "_id": "5c77ab6387cd83139588b1ae"
      }
    ]
  }
}
````

**Steps to reproduce the problem**
- `strapi install graphql`
- Create a Custom ContentType "Category"
- Create users and categories
- Run query in GraphQL Playground

**What is the expected behavior?**
Always return the correct data

**Comment by lauriejim** [comment]
Can you check with the last version of Strapi `alpha.26` with a fresh new app.
We fix many thing on GraphQL.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
