### ISSUE TITLE
Cannot install documentation plugin

### ISSUE THREAD

**Issue by IceOnFire** [strapi/strapi#2917]
**Informations**
- **Node.js version**: 10.15.2 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0 
- **Database**: MongoDB 3.6.3
- **Operating system**: Ubuntu 18.10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Installing the documentation plugin doesn't yield the expected result. Here's the output:

```
antony@amon ~/strapi-project> strapi install documentation
[2019-03-01T15:42:07.120Z] debug Installation in progress...
[2019-03-01T15:42:07.121Z] debug Installing the plugin from npm registry.
[2019-03-01T15:42:08.516Z] error An error occurred during plugin installation. 
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-documentation
```

**Steps to reproduce the problem**

1. Create a strapi app
2.  Install plugin with `strapi install documentation`

**What is the expected behavior?**

The plugin should be correctly installed.

**Suggested solutions**

Maybe check that the plugin was published to npm with all the relevant metadata. Is `"private": false` in the package.json?

**Comment by derrickmehaffy** [comment]
The documentation plugin requires at least strapi version 17 or higher. Plugins are not back ported to older versions as older versions are not supported.

I marking this as resolved since the issue won't happen on latest release
