### ISSUE TITLE
Websocket Plugin : Access Models/Core lifecycles events from plugin perspective

### ISSUE THREAD

**Issue by npjonath** [strapi/strapi#2919]
**Informations**
- **Node.js version**: 10.13 
- **NPM version**: 6.7
- **Strapi version**: v3.0.0-alpha.24.1
- **Database**: mongodb
- **Operating system**: os X

**What is the current behavior? (Context)**
I'm working on a Websocket plugin for strapi based on WAMP Protocol. 
 - I check all models from strapi in order to build a list of basic core events and policies that should publish data each time a life-cycle event is triggered. (Model AfterCreate, BeforeUpdate, ...)
 - Then, I get a list of com.appName.modelName.EventName ready to be Publish, Subscribe, Register or Call on/from my WAMP Router. 
 
Question : Is there a way to intercept or subscribe to strapi's life-cycle events from models and plugins inside another plugin ? 

More about the context : I need each of this events to trigger a function in my plugin services. I can already go and write in each life-cycle callback a call to my plugin. but it's pointless in order to automatize this behavior. In the best scenario : User go in Admin UI plugin, for each model it can disable, enable or restrict publication from each life-cycle events.

**Steps to reproduce the problem**
config/bootstrap.js
```
module.exports = cb => {
  // import autobahn
  var autobahn = require('autobahn');
  // configure realm crossbar connection
  var connection = new autobahn.Connection({
    realm: 'realm1', 
    url: 'ws://127.0.0.1:9000/ws',   //crossbar router 
    tlsConfiguration: { // optional tls
      ca: '',
      cert: '',
      key: '',
    }
  });

  // save connection for later use
  strapi.autobahn = connection;

  // start listenning
  strapi.autobahn.open();

  // try to publish something interesting.
  setInterval(function() {
    if(strapi.autobahn.isOpen && strapi.autobahn.isConnected){
      strapi.autobahn.session.publish('com.strapiproject.heartbeat', ['beat']);

     //Register here life-cycle event callback for each models.
     // strapi.autobahn.session.publish('com.strapiproject.user.beforeCreate', [model]);
    // ...
    }
  }, 5000);

  cb();
};
```

**What is the expected behavior?**
Be able to subscribe to strapi life-cycle events emitter from inside a plugin.

<img width="1150" alt="capture d ecran 2019-03-01 a 20 14 03" src="https://user-images.githubusercontent.com/1402097/53662162-89ed4280-3c62-11e9-93c7-8863b4955324.png">

**Comment by lauriejim** [comment]
Hello @npjonath !
It's an interesting topic.

Here is the way we manage bookshelf life cycle [Code here](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js#L214)
A thing you can try, it's in you beforeInitialize function, to update `target[model.toLowerCase()][fn]` (that is the model function for the life cycle) by mapping on each model to make you stuff.

**Comment by npjonath** [comment]
Hi guys, 

@lauriejim I have checked your example, but it's seems like moving database logic from database plugin to websocket plugin. I'm not sure it's the best way to do this.

I double check if the concept could work by implementing the example in the first message manualy in each of my model and it's work great in production for now. My goal is now to integrate this feature in a plugin.

Here is an example of what should be shown in the Plugin Crossbar Admin Area. 
For UI, I based my work on Content Type Builder plugin.

example:

| WAMP URI                         | WAMP Realm | WAMP Methode        | WAMP Authorization (Role)  | WAMP Authentication | STRAPI Handler      |  STRAPI Policy    |
| :------------------------------: | :--------: | :-----------------: | :------------------------: | :-----------------: | :-----------------: | :---------------: | 
| com.appName.user.find            |   public   | Register, Publish   | Authenticated              |  WAMP_CRYPTOSIGN    |  user.find()        |  isOwner          | 
| com.appName.user.create          |   public   | Register            | Authenticated              |  WAMP_CRYPTOSIGN    |  user.create()      |  isAdmin, isOwner | 
| com.appName.user.update          |   public   | Register            | Authenticated              |  WAMP_CRYPTOSIGN    |  user.update()      |  isOwner          | 
| com.appName.user.delete          |   backend  | Register            | serverAdmin, workerAdmin   |  WAMP_CRA           |  user.delete()      |  isAdmin          | 
| com.appName.user.onCreate        |   backend  | Publish             | serverAdmin, workerAdmin   |  WAMP_CRA           |  user.onCreate()    |  isAdmin          | 
| com.appName.user-%id%.onCreate   |   public   | Publish             | Authenticated              |  WAMP_CRYPTOSIGN    |  user.onCreate()    |  isOwner          | 


1. WAMP URI 
   a- Should respect com.appName.modelName.*
2. WAMP Realm
   a- Should respect naming according crossbar's .json config file
3. WAMP Methode describe the type on Autobahn Call made through websocket.
   a- Available WAMP Methode using Autobahn are : {call, register, publish, subscribe}
   b- From STRAPI perspective, I'm not sure if UI should display something else than register and publish methode.
4. WAMP Authorization allow role based authentication. 
   a- It define if a role can call, register, publish or subscribe an handler on a specific realm
   b- Should respect naming according crossbar's .json config file
5. WAMP Authentication define one of available authentication methode for the websocket layer. 
   a- Can be static or dynamic handler, with symetric or asymetric key) 
   b- Available Authentication are {CRA, Ticket, TLS, COOKIE, CryptoSign ...}
6. STRAPI Handler define the service methode to call when receiving an websocket event.
7. STRAPI Policy should restrict response from Handler according to existing STRAPI Policy.

The goal for now is to know :
 1. How Authentication & Authorization layer of Crossbar and STRAPI should interoperate. 
 we can use dynamic auth for querying directly STRAPI, but token send by STRAPI should be compliant with one of the crossbar authentication methode.
 2. How STRAPI policy can be used to restrict websocket layer.
 3. If STRAPI should deploy itself a crossbar router in order to manage it. (aka. generating the config file and run the crossbar router)

Then implementing it in a plugin package.

**Comment by lauriejim** [comment]
I close this issue - will reopen it when it will be needed.
Thank you @npjonath for all this content! 
Really appreciate.
