### ISSUE TITLE
Show proper error messages for `File Upload` plugin

### ISSUE THREAD

**Issue by dev-drprasad** [strapi/strapi#2921]
**Informations**
- **Node.js version**: v10.14.2
- **NPM version**: v6.4.1
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: mongodb
- **Operating system**: UBUNTU 16.04
- **(Optional) Link to your Project**: 

**What is the current behaviour?**
When uploaded file size is greater than configured size/ when file upload disabled, show proper error messages instead of **An error occurred**

**Steps to reproduce the problem**
 
- Upload file bigger than configured size. you will see message **An error occurred**. but not specifically
 - Upload file with file upload is disabled. you will see message **An error occurred**. but not specifically

**What is the expected behavior?**
Proper error messages

**Suggested solutions**
Issue is in plugin's `saga` file. currently we are just showing plain error message. we have to read error message from backend and show it in notification

**Comment by dev-drprasad** [comment]
please ignore first pull request.
I added only english translations for error messages.
is it possible to generate translations for other languages automatically ?? or do we need to write manually ??

**Comment by soupette** [comment]
> please ignore first pull request.
> I added only english translations for error messages.
> is it possible to generate translations for other languages automatically ?? or do we need to write manually ??

Hi @dev-drprasad we have to do it manually although there is an open PR [Crowdin](https://github.com/strapi/strapi/pull/2553).

**Comment by sebastianmarines** [comment]
I am still getting a message saying **An error occurred** while uploading a big file, even when the file size is smaller than the configured size

**Comment by derrickmehaffy** [comment]
@sebastianmarines If you are using a proxy like nginx you will also need to make sure it's maximum size is also increased
