### ISSUE TITLE
The relation dropdown doesn't call the search API on input change.

### ISSUE THREAD

**Issue by richardaiko** [strapi/strapi#2927]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1 
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: Postgres
- **Operating system**: MacOs Mojave

**What is the current behavior?**
In the Content Manager Plugin, the SelectMany Dropdown does not query the API when the initial `getOptions` response contains matching entries as the search term.

**Steps to reproduce the problem**
1) Click to Edit a content type with a relationship (many-to-many in my case)
2) (Optional) Open the network request inspector
3) Type in a search term in the relationship Dropdown
4) No API Requests (filters initial options list)

**What is the expected behavior?**
Input change triggers a search request.

**Suggested solutions**
Modify this bug fix, to always hit the API?
https://github.com/strapi/strapi/pull/1963/commits/5eed701b2289e476f1cf508e641d379b6fa369a3

**Comment by lauriejim** [comment]
Fixed on `alpha.26`
