### ISSUE TITLE
Documentation is not support array method

### ISSUE THREAD

**Issue by EpicUsaMan** [strapi/strapi#2929]
**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: SQLite
- **Operating system**: Linux

**What is the current behavior?**

Error throwed, documentation is not generated
```
UnhandledPromiseRejectionWarning: TypeError: current.method.toLowerCase is not a function
    at routes.reduce (src/backend/plugins/documentation/services/Documentation.js:433:35)
```

**Steps to reproduce the problem**

1. Create routes.json with next content
```
{
"routes": [
{
      "method": ["GET", "POST"],
      "path": "/example",
      "handler": "Example.example",
      "config": {
        "policies": []
      }
    }
]
}
```
2. Start strapi and observe result

**What is the expected behavior?**

Documentation should be generated

**Comment by derrickmehaffy** [comment]
@EpicUsaMan You should probably split up your routes instead of trying to combine them into a single route. This would be a very niche case where you would use the same controller/service for both `GET` and `POST`.

For now I'm making this as resolved as this isn't really a bug, but more a feature request. @lauriejim can take a look when he gets in the office to see if it should be re-opened

**Comment by EpicUsaMan** [comment]
@derrickmehaffy 
https://strapi.io/documentation/3.x.x/guides/routing.html#how-to-create-a-route

Maybe I mistake, but this functionality described as supported in documentation for version 3.x.x

Also, createOrUpdate / findOrCreate is not rare case ;)
All temporary storages works using GET / POST and PUT / POST combination.

**Comment by derrickmehaffy** [comment]
@EpicUsaMan you are right my mistake :wink: even I didn't RTFM this time lol

**Comment by soupette** [comment]
Thanks @EpicUsaMan for reporting the issue!

Do you feel like submitting a PR to fix it?

**Comment by EpicUsaMan** [comment]
@soupette Hi. Okay, I can do it;)
