### ISSUE TITLE
SQLITE_ERROR: Cannot add a column with non-constant default

### ISSUE THREAD

**Issue by heyarne** [strapi/strapi#2930]
**Informations**
- **Node.js version**: 10
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: SQLite
- **Operating system**: Linux 

**What is the current behavior?**
After having added a date field, the server repeatedly crashes and cannot be started again. The error message after running `npm start`:

```
(node:17401) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: Cannot add a column with non-constant default
(node:17401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-04T07:32:54.448Z] debug ⛔ Server wasn't able to start properly.
[2019-03-04T07:32:54.449Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
```

**Steps to reproduce the problem**
Create a new content type, add a date field. The server will crash. The content type I had had a couple of extra fields; some enums, one text field and a relation (n to 1). I don't know if this is relevant.

**What is the expected behavior?**
The provided fields should work without any hiccups?

**Comment by jegardiner** [comment]
I am also having this issue. It's because the SQLite ALTER TABLE syntax doesn't allow the addition / modification of date and time fields without an acceptable default value: https://www.sqlite.org/lang_altertable.html

**Comment by nolafs** [comment]
I am still having this issue with 3.0.0-beta.2. Just added date field and sqlLite crashed. Now I cannot even restart the project.

**Comment by alexandrebodin** [comment]
@nolafs Can you share the steps to reproduce your error ? and the associated models plz

**Comment by nolafs** [comment]
Yes,

1. I created a content-type Blog
2. Created a Blog
3. Edit the content-type by adding an additional Date field
4 Saved and it crashed.

I removed the field from the setting file and I was able to start it again. I will see if  I can recreate it.

`{
  "connection": "default",
  "collectionName": "blogs",
  "info": {
    "name": "blog",
    "description": "Blog"
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "Body": {
      "type": "text",
      "required": true
    },
    "header": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    },
    "posted": {
      "type": "date"
    }
  }
}`
