### ISSUE TITLE
Plugin development flow - locally, custom plugins seem not to work.

### ISSUE THREAD

**Issue by DanLahav-TG** [strapi/strapi#2931]
**Informations**
Node.js version: v10.15.1
NPM version: 6.4.1
Strapi version: 3.0.0-alpha.24.1
Database: mysql Ver 14.14 Distrib 5.7.25, for Linux (x86_64)
Operating system: Ubuntu 18.04.2 LTS

**Steps to reproduce the problem**
i'm doing what written in the documentation.

1. Fork + cd strapi && npm run setup
2. cd .. && strapi new myDevelopmentProject --dev.
3. cd myDevelopmentProject && strapi start To start the strapi project
4. cd /path/to/myDevelopmentProject && strapi generate:plugin my-plugin
5. cd ./admin && npm run setup
6. **fix test plugin errors - replace "-" with "_" in selectors; fix translations**
7. npm start => error on strapi helper, we solve it in 2 ways 
7.1 cd myDevelopmentProject/plugins/my-plugin && npm install.
7.2 cd /path/to/myDevelopmentProject && npm run setup ---plugins.
**Would you recommend the above? If so which one would be the better option?** 

8. cd ~/strapi && npm run setup:build 
9. strapi new project

**What is the current behavior?**
no plugin in strapi packages
no plugin in the new project  

we solve it by copy&&paste the plugin from the dev project 
**what is the correct way/approach, is there a better way to accomplish that.
what do i miss ?** 

**What is the expected behavior?**
my plugin in the parent repo so i can crate new projects with my custom plugins 

**Suggested solutions**

**Comment by lauriejim** [comment]
Has been fixed in `alpha.26`
