### ISSUE TITLE
Want to Modify/Add more fields in User Content Type

### ISSUE THREAD

**Issue by puneetverma05** [strapi/strapi#2932]
**Detail:**
I have added the custom fields (like gender, phone number etc.)  in User content type.
**Issue:**
 How we can pass more info like phone etc. via strapi SDK for register function  do we need to modify the function in sdk.js directly? 
Any Suggestions on how to overcome this?

**Comment by matheuschimelli** [comment]
I don't know if that is the best practice to do it, but I've edited the User model on plugins folder. There are the controllers too. But i advice you again that I don't know if that is the best practice.

**Comment by lauriejim** [comment]
The register function send specific params so you will have to update the SDK 
Check here https://github.com/strapi/strapi-sdk-javascript/blob/master/src/lib/sdk.ts#L106
