### ISSUE TITLE
Mp4 video stream problem from Android

### ISSUE THREAD

**Issue by FunnyDevs** [strapi/strapi#2934]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0 alpha 24.1
- **Database**: MongoDb
- **Operating system**: Windows 10

**What is the current behavior?**

Error: write ECONNRESET
      at WriteWrap.afterWrite [as oncomplete] (net.js:782:14)

The smartphone isn't able to play video and it remainings in loop opening and closing stream.

**Steps to reproduce the problem**

Try to play an uploaded video from an Android smartphone.

**What is the expected behavior?**

The smartphone plays the mp4 video from url without problems

**Suggested solutions**

**Comment by matheuschimelli** [comment]
Ok, It looks like not be a strapi issue. I suggest you to close the issue and check your code.

**Comment by FunnyDevs** [comment]
I have same problem when i try to play with vlc every mp4 file uploaded on strapi throgh its url, so i think is  problem of strapi / koajs

**Comment by matheuschimelli** [comment]
Are you using a custom file storage like S3 bucket? And, are you using a custom code on controller?

**Comment by FunnyDevs** [comment]
No, i'm using default file storage plugin that stores files in "public/uploads" folder

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.

**Comment by angeltonio** [comment]
Why it's closed???...I have the same issue

**Comment by angeltonio** [comment]
> I have same problem when i try to play with vlc every mp4 file uploaded on strapi throgh its url, so i think is problem of strapi / koajs

Do you know the why are this problem?

**Comment by angeltonio** [comment]
This is the error on strapi logs when that problem happen 

  Error: write ECONNRESET
      at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)

**Comment by ckswopnera** [comment]
same issue. 
  Error: write ECONNRESET
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
