### ISSUE TITLE
Add a public field to device if response entry

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2935]
- ❌ **I have created my request on the Product Board before I submitted this issue**
- ✅ **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I want a `public` field for several of my models to use it to decide internally whether to return that record in the response. I have done the following (in all the models), and it works! Buuut it doesn't work when filling relationships :slightly_frowning_face:

Example: when this model `Competition` model has a relationship with a `Season` model. If I request one competition, it comes with all the seasons, even those that are not public

<img width="797" alt="screenshot 2019-03-03 at 23 32 38" src="https://user-images.githubusercontent.com/1007051/53790282-e41e2a00-3f26-11e9-95d0-8319406214e6.png">

**Comment by lauriejim** [comment]
To do it with your relations you have to customise the `populate` value you send in your request.

**Comment by lauriejim** [comment]
Try with last update we did with filtering on deeep populate.

**Comment by abdonrd** [comment]
@lauriejim code updated!

Competition.js | Edition.js
------------ | -------------
![Screenshot 2019-04-23 at 17 19 44](https://user-images.githubusercontent.com/1007051/56593031-0b6eaa80-65ec-11e9-9568-45efa268ebc0.png) | ![Screenshot 2019-04-23 at 17 19 55](https://user-images.githubusercontent.com/1007051/56593033-0b6eaa80-65ec-11e9-8ded-b0ccc6fcf9b8.png)

But same behavior. 😕

**Comment by lauriejim** [comment]
Did you also update the query builder for your queries.
Create a new app and a new content type to see how new queries are made.

**Comment by abdonrd** [comment]
What file do you mean when you talk about query builder?

**Comment by abdonrd** [comment]
@lauriejim can we reopen it? Thanks!

I am not sure of the best solution, but I would like to find a solution for this use case.
