### ISSUE TITLE
View, Sort, and Filter by Created_At and Updated_At within the AdminUI

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#2936]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Note**: Request was not made on the product board as this is such a small addition, I don't believe it warrants a product board request.

**Please describe your feature request:**

This request is basically split into two part:

1. Viewing the `Created_at // createdAt` and the `Updated_at // updatedAt` fields within the adminUI, both in the List and Edit views. However __**they should not be editable**__ as strapi handles the backend.

2. Allowing for the AdminUI List view to allow sorting and filtering on created and updated.

@soupette not sure how much free time you have or maybe if @virginieky wanted to work on this? I think it should be fairly easy to add in although it exceeds my skills within react.

**Comment by Aurelsicoko** [comment]
Thank you Derrick! 

I've created a card on ProductBoard https://portal.productboard.com/strapi/c/56-view-sort-and-filter-by-created_at-and-update_at-fields. It should not be too long to display the fields but the sorting/filtering could be more difficult because we will manipulate dates.
