### ISSUE TITLE
Unable to scroll down strapi crm ?

### ISSUE THREAD

**Issue by huzaifazafar4725** [strapi/strapi#2937]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**:6.8.0 
- **Strapi version**: 3
- **Database**:  MongoDB
- **Operating system**:  Windows 10 64
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I have installed strapi for first time. its fine but the problem is there is no scroll in whole strapi crm. So i am unable to see the content which needs to scroll down. I tried it on google chrome. 

**What is the expected behavior?**
There should be a scroll on strapi crm so that i can scroll it down and see the whole screen content

**Comment by lauriejim** [comment]
Hello @huzaifazafar4725 !

Can you give us the exact Strapi version you user please. `3` is not enough.
And can you give us some screen shot and detail about where you try to scroll.

**Comment by lauriejim** [comment]
Will reopen this issue when all informations will be updated.

**Comment by JeanLEUNG** [comment]
Hello @lauriejim,
same issue for me, I am using the v3.0.0-beta.20.2 (docker image), with chrome, and there is no slider when the content of your collection type does not fit your screen : 

![image](https://user-images.githubusercontent.com/26717079/82162020-ab574000-98a1-11ea-8338-5b5f753f2c87.png)

![image](https://user-images.githubusercontent.com/26717079/82162064-0426d880-98a2-11ea-85f2-ac29fb95f9a7.png)

**Comment by JeanLEUNG** [comment]
Sorry for all, the bar now appears on the right (same browser page, computer did not restart, only STRAPI restarted a couple of times after model changes). I am not able  to reproduce the issue.

**Comment by airhead-dom** [comment]
hi is there any update on the scrolling issue
