### ISSUE TITLE
Documention plugin screen displays "An error occurred"

### ISSUE THREAD

**Issue by Mr-Chilly** [strapi/strapi#2939]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**:  mongodb
- **Operating system**: windows10

**What is the current behavior?**
After upgrading Strapi (and dependancies) to the latest, and installing the 'Documentation' plugin noly displays "An error occurred"

**Steps to reproduce the problem**
Project includes:

    "lodash": "4.x.x",
    "moment": "^2.23.0",
    "strapi": "3.0.0-alpha.24.1",
    "strapi-email-mailgun": "^3.0.0-alpha.14.5",
    "strapi-hook-mongoose": "^3.0.0-alpha.24.1",
    "strapi-provider-email-mailgun": "^3.0.0-alpha.24.1",
    "strapi-upload-cloudinary": "^3.0.0-alpha.14.5",
    "stripe": "^6.23.0"

With some business logic in controllers (I know!) and services
and a single cron. General update was from 3.0.0-alpha.13.1

**What is the expected behavior?**
Documentation plugin display swagger interface

**Suggested solutions**
I'm not actually getting any console errors at all - can you talk me through debugging it?

**Comment by tanmaiaccion** [comment]
@Mr-Chilly  sam issue here.

**Comment by tanmaiaccion** [comment]
For anyone landing on this issue you need to update strapi version to strapi@3.0.0-alpha.24.1. That fixes the issue.

**Comment by lauriejim** [comment]
Did you follow each migration guide ?

**Comment by Mr-Chilly** [comment]
I don't think so - it definitely could be the problem! I have always been on 3.x - Im just looking for the original version now:

initial commit:

` "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^3.12.2",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^6.8.0"
  },
  "dependencies": {
    "lodash": "4.x.x",
    "strapi": "3.0.0-alpha.13.1",
    "strapi-hook-mongoose": "3.0.0-alpha.13.1"
  },`


current: 
`"devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint-config-slimmingworld": "https://bitbucket.org/milesbram/slimmingworld.platform.ESLintConfig#7d20d6c",
    "jest": "^23.6.0",
    "lint-staged": "4.2.2",
    "prettier": "1.7.0",
    "prettier-eslint": "8.8.2",
    "stylelint-config-slimmingworld": "https://bitbucket.org/milesbram/slimmingworld.platform.StylelintConfig#feature/prettier-config-rules#1.2.2"
  },
  "dependencies": {
    "lodash": "4.x.x",
    "moment": "^2.23.0",
    "strapi": "3.0.0-alpha.24.1",
    "strapi-email-mailgun": "^3.0.0-alpha.14.5",
    "strapi-hook-mongoose": "^3.0.0-alpha.24.1",
    "strapi-provider-email-mailgun": "^3.0.0-alpha.24.1",
    "strapi-upload-cloudinary": "^3.0.0-alpha.14.5",
    "stripe": "^6.23.0",
    "yup": "^0.26.10"
  }`

**Comment by lauriejim** [comment]
Here is migration guides https://strapi.io/documentation/3.x.x/migration-guide/

You will see how update your app.
So make sure you also update your plugins.
