### ISSUE TITLE
can i override api?

### ISSUE THREAD

**Issue by neneji** [strapi/strapi#2940]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I'd like to use strapi for my next project. But i have a big question, can i override the automatic generated apis? and how?
Should i edit directly the controllers' js files?

**Comment by derrickmehaffy** [comment]
@neneji yes you can override any of the auto generated files. I am going to mark this as closed as it isn't not a feature request or a bug report. You are welcome to join the slack to talk and ask questions.

https://slack.strapi.io
