### ISSUE TITLE
HTML content from WYSIWYG editor

### ISSUE THREAD

**Issue by ChristianLJ** [strapi/strapi#2947]
I have a content model (blog) wherein I have a field with a WYSIWYG editor.

Calling the endpoint /blog returns the following data:

 ```json
[{
    "content": "test\n![text](/uploads/705ad80f2d3448c3ae785141643699fd.jpg)"
}] 
 ```

Is it possible to get the images added in the editor as html? E.g. in a <img /> tag? 

It makes it hard to use the content from the editor as it is, since it's not HTML.

**Comment by derrickmehaffy** [comment]
@ChristianLJ Please follow the issue template, for now I will mark this as closed, please update your original post using the template and reply here and the issue can be reopened.

the WYSIWYG editor saves as markdown, you would need to convert from markdown to html as it typically is not recommended that you store html within a database.

**Comment by derrickmehaffy** [comment]
(You could, however the built in editor won't save as html and thus you would need your own editor to do so)
