### ISSUE TITLE
withRelated typo issue in search Bookshelf template

### ISSUE THREAD

**Issue by absolux** [strapi/strapi#2949]
Hello, I'm not sure yet, but I think there's a typo in `bookshelf/service.template`

**What is the current behavior?**

```js
model.fetchAll({
  width: populate
  ^^^^^
})
```
https://github.com/strapi/strapi/blob/f2bac2a59abfb0d05ddda3883b854718614245a7/packages/strapi-generate-api/templates/bookshelf/service.template#L239:L241

**Suggested solutions**

```js
model.fetchAll({
  withRelated: populate
})
```

**Comment by lauriejim** [comment]
Hello @absolux !

Yap it look like to be an issue.
Feel free to submit a PR to fix this. We will appreciate your contribution on this point.
