### ISSUE TITLE
Cannot install strapi@alpha

### ISSUE THREAD

**Issue by mehdiraized** [strapi/strapi#2951]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: alpha24.1
- **Database**: mysql
- **Operating system**: ubuntu

**What is the current behavior?**
i can't install strapi last version
`npm install strapi@alpha -g`

this is error
```
npm WARN deprecated joi@10.2.2: This version is no longer maintained. Please upgrade to the latest version.
/root/.npm-global/bin/strapi -> /root/.npm-global/lib/node_modules/strapi/bin/strapi.js

> strapi@3.0.0-alpha.24.1 postinstall /root/.npm-global/lib/node_modules/strapi
> node lib/utils/success.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/strapi/lib/utils/success.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN react-ga@2.5.7 requires a peer of prop-types@^15.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ga@2.5.7 requires a peer of react@^15.6.2 || ^16.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi@3.0.0-alpha.24.1 postinstall: `node lib/utils/success.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi@3.0.0-alpha.24.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-08T11_04_41_589Z-debug.log
```

**Comment by lauriejim** [comment]
Hello, please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

Thank you.

> This is a templated message

**Comment by mehdiraized** [comment]
> Hello, please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.
> 
> I will reopen your issue as soon as it follows the templating guidelines.
> Please update your issue.
> 
> Thank you.
> 
> > This is a templated message

plz reopen and help to install strapi in my server for deploy project

**Comment by lauriejim** [comment]
I suggest you to remove all globals node module of Strapi and then retry to install it globally.

**Comment by mehdiraized** [comment]
i install with yarn add global
its work for me
