### ISSUE TITLE
How to override plugin?

### ISSUE THREAD

**Issue by madonzy** [strapi/strapi#2955]
I want to override user plugin, and don't want to make changes in core plugin, so not to have issues with updates.

How can I do that?

**Comment by derrickmehaffy** [comment]
@madonzy please use the bug report or feature request template. For now I will mark this as closed, you are also welcome to ask questions on the slack here: https://slack.strapi.io

With regards to overrides within the user plugin, there is no other way then to modify the files within the `plugins/users-permissions` directory. Minor config changes are fairly easy to track while doing updates (for now all updates are manual) of course if you are overriding large parts of the plugin that will be more difficult and will need a solid testing/staging environment before you push it out into production.

**Comment by madonzy** [comment]
@derrickmehaffy Really? So let's say if I want to override logic to send mail after Content Type item was saved I must override the core files?

**Comment by derrickmehaffy** [comment]
@madonzy depends if you are talking about a plugin like say send a mail to the admins when a user signs up yes. At this path `plugins/users-permissions/models/User.js` there are lifecycle call backs you can use to send an email or whatever. but you are still modifying the core files, this is intended.
