### ISSUE TITLE
Deleting file from 'Files Upload' breaks any other content that has it as a 'Media' relation

### ISSUE THREAD

**Issue by chanon** [strapi/strapi#2956]
**Informations**
- **Node.js version**: v10.15.2
- **NPM version**: 6.4.1
- **Strapi version**: Strapi v3.0.0-alpha.24.1
- **Database**: Postgresql 11
- **Operating system**: Ubuntu 18.04
- **Browser**: Firefox 65.0.2 (64-bit)

**What is the current behavior?**
(Just read Steps to reproduce below, might be easier to understand.)
Suppose we have a content type "Post".
In "Post" we have an "Images" field with type "Media" that has "Allow multiple files" checked.
If any of the files added in "Media" for a Post are deleted in the "Files Upload" section under Plugins, then the Post will no longer be editable. When saving there will be a javascript error in the console:

```
uncaught at a at a 
 at o 
 at r 
 at s 
 s/<@http://thedomain.com:1337/admin/content-manager/main.js:48:528484
....
```

**Steps to reproduce the problem**
1. Create a content type "Post" and add a field named "Name".
2. Add a field named "Images" of type "Media" and check "Allow multiple files"
3. Create a new "Post" and upload an image file to its "Images" field. Add a Name and save the Post.
4. On the left side under Plugins click "Files Upload"
5. Delete the file that was uploaded in step 3 using the trash can icon.
6. Go back and edit the Post created in step 3. See that it showing as if there is a file, but no image is displayed.
7. Try changing the Name of the Post. Then click Save. See that nothing happens.
8. Open Browser JavaScript error console and see JavaScript error.
9. See that can no longer save changes to this Post.

**What is the expected behavior?**
I'm not sure if I'm doing anything wrong, but strapi shouldn't allow deleting the file from the "Files Upload" screen in this case, because the file is being used by another content entry. 

Ideally it should be possible to see all content entries that are referencing a file, and see files that are not referenced at all. At least through the 'Media' type fields. If can also scan for the file in WYSIWYG text fields too then would be a plus.

Without this functionality, there isn't much use to having Media type fields as they don't help with managing which content owns which files.

**Suggested solutions**
- The "File Uploads" plugin should check for references to files before allowing to delete them (or at least asking for confirmation)
- Content entries whose files are missing should still allow saving without JavaScript errors.
- The "File Uploads" plugin should allow viewing all references to each file.
- In the other direction, ideally, when deleting a content entry that references uploaded files, it should offer to also delete any uploaded files that are no longer referenced by any other content entries.
- Also same as above for when removing or replacing a file from a Media field

I think these suggestions would greatly improve strapi in terms of "content management" as someone who is going to use it to manage content.

EDIT: Just tried it without "Allow multiple files" and it also breaks the same way.

EDIT: Reviewing the actual database, it looks like there is an `upload_file_morph` table that stores the references. However, upon deletion of files and content entries, this upload_file_morph still contains all the relations. It is good though that this relation data is available to implement the above suggested solutions ... and for umm manual queries / cleanup if needed.

**Comment by cupofnestor** [comment]
I cannot reproduce this with `3.0.0-alpha.24.1 (node v10.11.0)` mongoDB/OSX

**Comment by chanon** [comment]
@cupofnestor what happens in your case? Does it allow deleting the file? Or does it allow saving the Post with missing file?

**Comment by cupofnestor** [comment]
Behaves as expected.  File is deleted without error and related model is updated in respect to the deletion

**Comment by lauriejim** [comment]
Hello!

I strictly follow each steps and was not able to reproduce your issue.
Maybe I miss something.

In my case it successfully update the entry without any error message.

**Comment by chanon** [comment]
Hmm... I guess something might be wrong with my setup/config. I don't know how or why though.

If no one can reproduce, then feel free to close.

**Comment by pouyamiralayi** [comment]
Hi @lauriejim i am experiencing this issue on v16.8
when i delete my referenced file from **File Upload** section, then returning to my content type that holds a reference to that file, it will show me this:
![image](https://user-images.githubusercontent.com/53266765/67575108-b0f40980-f748-11e9-92ff-4a31621533e8.png)
this is the full error:
```
TypeError: Cannot read property 'split' of undefined

    in Es
    in td
    in As
    in withRouter(undefined)
    in tr
    in t
    in styled.tr
    in tbody
    in table
    in t
    in styled.table
    in Cs
    in Cs
    in withRouter(undefined)
    in div
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in hi
    in ac
    in ac
    in k
    in t
    in t
    in Unknown
    in _g
    in k
    in mainComponent
    in t
    in div
    in ar
    in ar
    in t
    in t
    in div
    in div
    in div
    in t
    in k
    in withSaga(Connect(t))
    in withReducer(withSaga(Connect(t)))
    in t
    in ro
    in t
    in div
    in div
    in io
    in k
    in t
    in t
    in IntlProvider
    in t
    in k
    in t
```
my content type has a media field with **allowed multiple files** checked. 
one interesting point that may help is that i tried to remove the file using destroy endpoint ("upload/files/:id") and when i retrieved the content type, the field holding file references was an array with one empty object and i guess that's the problem:
![image](https://user-images.githubusercontent.com/53266765/67575664-e816ea80-f749-11e9-87a3-9ebcd97ba1ff.png)
cheers!

**Comment by neverbe10** [comment]
Is this issue fix? it's a bug
