### ISSUE TITLE
Graphql with mysql not working after migration

### ISSUE THREAD

**Issue by thomaskvael** [strapi/strapi#2957]
I migrated from 3.0.0-alpha.21 to 3.0.0-alpha.24.1

The way i did it.
1. Created new project: strapi new my-project
2. Created my two models with: strapi generate:api modelname blah:string
3. Copied model.settings.json from my old project to the new project.
4. installed mysql: npm install mysql --save
5. Copied database.json from my old project to the new project.
6. Run strapi start
7. Install Graphql plugin.

I can see my content in Strapi admin. Everything looks fine. find and findOne has public permissions for my two models/content types.

When i run http://localhost:1337/graphql and tries this query (that works in the old project)  
`  {
    posts {
      id
      type
      published
    }
  }`

I get this error  

`{  
  "errors": [  
    {  
      "message": "Post.find is not a function",  
      "locations": [  
        {  
          "line": 2,  
          "column": 3  
        }
      ],
      "path": [
        "posts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Post.find is not a function",
            "    at Object.fetchAll (C:\\some_folder\\alpha241_2\\api\\post\\services\\Post.js:30:8)",
            "    at find (C:\\some_folder\\alpha241_2\\api\\post\\controllers\\Post.js:21:35)",
            "    at C:\\some_folder\\alpha241_2\\plugins\\graphql\\services\\Query.js:279:41"
          ]
        }
      }
    }
  ],
  "data": {
    "posts": null
  }
}`

Do i have to recreate all of my content?  
Is there a breaking change in strapi with mysql that prevents me from using my existing mysql db and tables?

**Comment by derrickmehaffy** [comment]
`C:\\some_folder\\alpha241_2\\api\\post\\controllers\\Post.js:21:35`

https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

Windows isn't fully supported yet, work is being made on it but for now you should test using WSL (not with a windows mapped drive) or a linux Virtual Machine

**Comment by thomaskvael** [comment]
This issue is not related to the the "Windows issue"

Same problem with Ubuntu  

`{
  "errors": [
    {
      "message": "Post.find is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "posts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Post.find is not a function",
            "    at Object.fetchAll (/home/test/api/post/services/Post.js:30:8)",
            "    at find (/home/test/api/post/controllers/Post.js:21:35)",
            "    at /home/test/plugins/graphql/services/Query.js:279:41"
          ]
        }
      }
    }
  ],
  "data": {
    "posts": null
  }
}`

**Comment by derrickmehaffy** [comment]
@thomaskvael how did you update your project?

**Comment by thomaskvael** [comment]
I installed the latest strapi in a new folder. 
Then I ran **strapi generate:api post title:string** and copied over the **post.settings.json** file from the old strapi api/models folder. The instructions of what I did is more or less in my first post.

I noticed that I can query content of a new content type that i created after the migration. But i can't query the old content. 

I will try to compare the content of /api/ and my db table to see if I can find any differences.

**Comment by thomaskvael** [comment]
My problem was i did not read your [post ](https://github.com/strapi/strapi/issues/1880) good enough. I was missing:  

Notes:
If you are using MySQL or Postgres you need to do strapi generate:api -t bookshelf modelname blahblah:string
