### ISSUE TITLE
No linebreaks in text fields in api response

### ISSUE THREAD

**Issue by elhenro** [strapi/strapi#2962]
I am using: [strapi-docker](https://github.com/strapi/strapi-docker)

**Informations**
- **Node.js version**: 10.0.1
- **NPM version**:  npm 6.4.1
- **Strapi Version**: Strapi Docker
- **Database**:  mongo
- **Operating system**:  Ubuntu 18.04 Server
- **Server Type:**: Nginx Proxy

**What is the current behavior?**

When I create any text fields (with and w/o wysiwyg) the editor and edit view works as expected.
But when I request a list of items or the item itself there is nothing indicating the line breaks in the string,
it is just separated by single spaces.

**Steps to reproduce the problem**
* Setup Strapi Docker
* Make a simple text field with multiple lines
* request the item via api

**What is the expected behavior?**
Api response includes information about linebreaks, so simple text blocks can be rendered as intended.
\n, \r, or double spaces (markdown)

**Suggested solutions**
store strings encoded in mongodb?

**Comment by elhenro** [comment]
@lauriejim thanks for the effort!
strange, i still cant seem to get it working.. only thing that works for me is using raw html code in the strapi text fields and then rendering it as v-html (vue) in my frontend. could it be because of cloudflare? or nginx forwarding to the docker container?

**Comment by lauriejim** [comment]
Hum I have no idea about what can cause this issue.
It's really strange.

**Comment by elhenro** [comment]
>It's really strange.

it is..

I'll try some (alpha) testing without the docker container.
I will update if I find out what could cause those missing line breaks.

**Comment by elhenro** [comment]
@lauriejim 
I just tried a fresh strapi install with `node v10.15.3`
on my local machine (not on the server, no cloudflare, no nginx, no docker)

And I have the exact same problem..

my simple text field contains:
``` markdown
test
new line

another new line
```

the api response is 
``` json
[
{
id: 1,
text: "test new line another new line",
created_at: 1552495580580,
updated_at: 1552495580658
}
]
```

**Comment by elhenro** [comment]
Nevermind. 
I found it is because of a [chrome plugin i was using](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc) :laughing: 
It seems to hide `\n`, for no obvious reason, but does not show linebreaks either..
Sorry for wasting your time on this.

**Comment by lauriejim** [comment]
Haha okay! Good to know.

**Comment by kozborn** [comment]
![image](https://user-images.githubusercontent.com/382005/65428255-5a777080-de14-11e9-851d-8e3f101a12fc.png)

I have a similar problem, It seems that you can only have one break? Or in another words, how to enter empty paragraphs if I need more space between texts?

**Comment by marcelo-haytek** [comment]
Also having the same problem here... The API return with \n i tried <br /> also and didn't work either... i'm using front with angular...

**Comment by zhampu** [comment]
I'm having same Issue here.
also not using any Extensions.

**Comment by marcelo-haytek** [comment]
@zhampu  i used a "work-around" and used the parse from react

`var parse = require('html-react-parser');`
`parse('<div>text</div>');`

**Comment by Cally99** [comment]
Strapi is a waste of time if these simple issues can't be done within the editor and using a frontend to render the markdown? How many years old is wordpress and this basic bloody requirement works? Working with strapi is one of the most frustrating projects I've ever encountered.
