### ISSUE TITLE
Add support for folders in Cloudinary

### ISSUE THREAD

**Issue by juiceo** [strapi/strapi#2972]
- [* ] **I have created my request on the Product Board before I submitted this issue**
- [ *] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Currently the `strapi-provider-upload-cloudinary` plugin does not, as far as I can tell, support defining a folder under which to upload your files. Currently all files uploaded via strapi just go into the root of the Cloudinary media library, which is far from ideal. This means that if I have several apps uploading files to my Cloudinary account, there's no way for me to identify which files have been uploaded from which app, and thus no way to e.g. delete all of the files uploaded from a given app.

See `folder` under the Upload API Reference for more info: https://cloudinary.com/documentation/image_upload_api_reference

Please allow users to configure a folder to which the uploads from a given environment should go to. This should be a very trivial fix and frankly I'm a bit surprised it's not in there by default :)

Thanks!

**Comment by Aurelsicoko** [comment]
@lauriejim it could be tagged as a `good first issue` 👍

**Comment by absolux** [comment]
Hi, I think that an optional object could be passed as second argument to `upload` function. Such object could simply contain the `folder` option:
```js
// usage
upload(file, { folder: 'folder_name' })
```
https://github.com/strapi/strapi/blob/aeee19bdfdf66fc77e6cfb62184537df1b77048a/packages/strapi-provider-upload-cloudinary/lib/index.js#L38:L50

**Comment by lauriejim** [comment]
Feel free to open a PR :) will appreciate contributors on this topic.

**Comment by absolux** [comment]
@lappalj4 , @lauriejim ,

After reading the [documentation](https://strapi.io/documentation/3.x.x/guides/upload.html#usage), and the source of `strapi-provider-upload-aws-s3`, I suggest to use `file.path` as used by `aws` provider.

```js
let options = { resource_type: "auto", folder: file.path }

cloudinary.uploader.upload_stream(options, cb)
```

**Comment by ValYouW** [comment]
Hi @absolux 
Using the `file.path` can be problematic as I don't see it is being used when uploading files from the Admin panel. Maybe I am missing something, but when I create a content-type that has a "file" field, in the Admin UI all I can do is "drag" a file into the input field and it is uploaded, attached screenshot:

![image](https://user-images.githubusercontent.com/4539636/54882860-0ee50980-4e67-11e9-82f5-cd3ebae7ff6f.png)

I think that having a global `upload_folder` settings in the `strapi-provider-upload-cloudinary` will be useful, something like this:
![image](https://user-images.githubusercontent.com/4539636/54882983-b6167080-4e68-11e9-9cac-e6923e626ad2.png)

of course it can be override with the `file.path` if wanted...
Thoughts?

**Comment by Torone** [comment]
It is not the `folder` missing here... The totality of Cloudinary option configuration is missing here...
Options like: Transformations, format, eager, quality, folder, etc...
Cloudinary `upload_stream` accept an object as first parameter that should be used for this configuration.
Looking at the code on `strapi/packages/strapi-provider-upload-cloudinary/lib/index.js` that parameter is hard coded as an empty object: `{}`. Actually it is not accepting a variable that could be very useful for this purpose.
After that small change on the provider it would need to be updated on Strapi too.

**Comment by derrickmehaffy** [comment]
@Torone you are more than welcome to submit a PR if you wanted to work on adding these features!

**Comment by Torone** [comment]
@derrickmehaffy  Here we are: https://github.com/strapi/strapi/pull/3351

**Comment by yassinebridi** [comment]
any updates on this?

**Comment by jwynveen** [comment]
This would be incredibly useful. Any chance this will happen? I see that the pull request previously made was not accepted because of architecture changes.

**Comment by derrickmehaffy** [comment]
@jwynveen if someone wanted to pick up the old PR and refresh it for the new architecture they would be welcome to. For the moment it's not high on the Strapi team's priority list.

**Comment by ChristopherLMiller** [comment]
the above code by @ValYouW still works even post architecture changes.  I've been manually updating my file with it since.  I use Cloudinary and i'm still not exactly sure how to use all of those features or i'd work on a PR to add support for all the different options.  Bare minimum I'd love to see the folder part pulled in to stop having to manually edit the file after each strapi update

**Comment by derrickmehaffy** [comment]
@ChristopherLMiller someone would need to add the UI stuff to the admin (which I am not adept at or I would) Until someone has time to pick it up and make a full PR.

**Comment by ChristopherLMiller** [comment]
simply adding the upload_folder to the config adds it to the UI for myself.  I don't remember if i added that manually at some point though, but if so then folders are covered already

**Comment by abdonrd** [comment]
I'm interested in this!

I understand that the name of the folder should go in the "Content Type Builder > Model > Field > Advanced Settings", right? So that each field can have a different folder.

**Comment by abdonrd** [comment]
Very draft PR: https://github.com/strapi/strapi/pull/5069

**Comment by Seybo** [comment]
Guys any updates here?

**Comment by Canice-James** [comment]
Bump.

**Comment by SalahAdDin** [comment]
Any update about this?

**Comment by neilpoulin** [comment]
I think this has been resolved in both v3 via the `actionOptions.upload.folder` option in the provider configs, as well as in v4 with this upcoming PR: #12838

**Comment by SalahAdDin** [comment]
@neilpoulin is there any documentation about it?

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/media-folders
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
