### ISSUE TITLE
Cannot override default GraphQL schema

### ISSUE THREAD

**Issue by IceOnFire** [strapi/strapi#2973]
**Informations**
- **Node.js version**:  v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.24.1
- **Database**: MongoDB v3.6.3
- **Operating system**: Linux Ubuntu 18.10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Possibly related to #1887, I'm just trying to apply some policies to the default Shadow CRUD but I can't seem to make the custom schema to work.

**Steps to reproduce the problem**

1. Create a strapi project and add the graphql plugin.

2. Create a Patient API with the command:

```bash
strapi generate:api Patient
```

3. Create a custom schema for the Patient API:

```js
module.exports = {
  definition: ``,
  query: ``,
  mutation: ``,
  type: {},
  resolver: {
    Query: {
      patients: {
        policies: ['global.filterByOwner'],
      }
  }
}
```

4. Run strapi: it won't boot due to the following error:

```
(node:24953) UnhandledPromiseRejectionWarning: Error: Resolver Query.patients must be object or function
```

5. Add a resolver to every query/mutation:

```js
module.exports = {
  definition: ``,
  query: ``,
  mutation: ``,
  type: {},
  resolver: {
    Query: {
      patients: {
        resolver: 'Patient.find',
        policies: ['global.filterByOwner'],
      }
  }
}
```

6. Run strapi: server boots this time

7. Perform a query on GraphiQL:

```graphql
query {
  patients {
    _id
  }
}
```

Query breaks, even if I comment out the policy from the custom schema. Here's the error message on GraphiQL:

```js
{
  "errors": [
    {
      "message": "Cannot read property 'primaryKey' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "patients"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'primaryKey' of undefined",
            "    at <PROJECT_DIR>/plugins/graphql/services/Query.js:263:72",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "patients": null
  }
}
```

8. Remove the custom query "patients", boot strapi, perform the query: everything works as expected

**What is the expected behavior?**

The custom schema should have just applied my policies, even without specifying a resolver. Instead, when I create a custom schema I cannot seem to make it work properly.

The issue is different from #1887 in that I'm just trying to override default behavior, not add new one.

**Suggested solutions**

Sorry, no clue

**Comment by nikosolihin** [comment]
@IceOnFire I think this issue is similar to #2766 where `'Patient.find'` remains a string during schema generation and never points to an actual controller function because of an undefined var `queryName`

https://github.com/strapi/strapi/blob/9b20f27657320e20f3255a2ec261ceb5a6b8be78/packages/strapi-plugin-graphql/services/Mutation.js#L40

Custom string resolvers and policies work after I modify `queryName` based on the presence of `action`:

```
const queryName = action ? `${action}${_.capitalize(name)}` : `${name}`;
```

**Comment by IceOnFire** [comment]
Hi @nikosolihin,

I think you're right and thanks to you I can now perform the queries by replacing "Patient.find" with "strapi.controllers.patient.find". So now the issue I'm having is indeed similar to #1887, because queries and mutations work but policies are not called.

**Comment by nikosolihin** [comment]
I also found a few other bugs in Mutation.js that were causing my custom [controller function to return null](https://github.com/strapi/strapi/issues/2766#issuecomment-463129085) if I make the request using graphql. I'll see if I can submit a PR soon.

**Comment by IceOnFire** [comment]
I'm doing some tests too, and I found out a strange thing: if I don't specify a resolver in my custom schema, it is correctly resolved both on the Query.js and Mutation.js modules. For example I can console.log the patient controller that was found by Query.js, and it looks the right one:

```js
async ctx => {
    if (!ctx.params._id.match(/^[0-9a-fA-F]{24}$/)) {
      return ctx.notFound()
    }

    return strapi.services.patient.fetch(ctx.params)
  }
```

But then the server still fails to start somewhere else due to

```
Error: Resolver Query.patient must be object or function
```

**Comment by nikosolihin** [comment]
Strange...I haven't encountered that error message before. Could you paste your custom schema?

**Comment by IceOnFire** [comment]
Sure. my last one is like this:

```js
module.exports = {
  definition: ``,
  query: ``,
  mutation: ``,
  type: {},
  resolver: {
    Query: {
      patients: {
        resolver: 'Patient.find',
        policies: ['plugins.users-permissions.permissions', 'global.filterByOwner']
      }
  }
}
```

My tests lead me to these conclusions:

1. If I don't specify the resolver, it is found automatically at startup but then fails to boot with the message `Error: Resolver Query.patients must be object or function`

2. If I do specify it like `Patient.find` then the server boots, the policies are applied, but the query fails with the following stacktrace:

```
TypeError: Cannot read property 'primaryKey' of undefined
at <PROJECT_DIR>/plugins/graphql/services/Query.js:263:72
```

3. If I specify it like `strapi.controllers.patient.find` then the server won't find the controller.

4. Also, my policy `global.filterByOwner` relies on the `ctx.state.user` variable which has no value when it is called because the policy `plugins.users-permissions.permissions' gets added internally by the GraphQL plugin as the last policy. The workaround for this issue is explicitly adding `plugins.users-permissions.permissions` as first policy in the custom schema, but I think it should always be prepended.

**Comment by IceOnFire** [comment]
Model is undefined because at a certain point at startup it does

```
const model = plugin
      ? strapi.plugins[plugin].models[name]
      : strapi.models[name];
```

where `name` is 'patients', not 'patient'.

**Comment by IceOnFire** [comment]
Yup, it definitely breaks when overriding plurals such as `patients`. `patient` works instead.

**Comment by lauriejim** [comment]
Hello, can you confirm your issue is the same as issues you linked?

**Comment by IceOnFire** [comment]
Hey @lauriejim,

I'm not sure yet, let me make some other tests tomorrow morning.

**Comment by IceOnFire** [comment]
Hi @lauriejim,

This is what I found after some more digging:

There are a lot of issues when customizing GraphQL schemas. Some are addressed in other issues, some other maybe not completely.

1. When redefining a plural query such as `patients` in the custom schema like this:
```
patients: {
  resolver: 'Patient.find'
}
```
the query breaks with the `Cannot read property 'primaryKey' of undefined` message just like you stated in comment https://github.com/strapi/strapi/issues/2867#issuecomment-466038696. The result is the same, but I don't know if the cause is.
2. Policies such as `plugins.users-permissions.permissions` are being applied *after* custom policies. This is bad because custom policy such as `isOwner` cannot take advantage of having the user already populated in context. It is better to unshift that policy instead of pushing it, otherwise developers need to explicitely add `plugins.users-permissions.permissions` as first policy in our custom schemas.
3. A mutation such as `createPatient` adds the patient to the db but does not return it when defining the mutation in the custom schema:
```
createPatient: {
  resolver: 'Patient.create',
},
```
4. I'm not sure about what's happening in issue #1887, because @jrperdomoz was talking about a query and the solution provided by @nikosolihin seems relative to mutations. The solution does not solve point 1 for me, nor it affects point 3. I really struggled understanding the train of thought inside the service files of the GraphQL plugin and couldn't really find any clue.

**Comment by Throttle** [comment]
Hi @IceOnFire!
Did you find a solution?
I also have "Cannot read property 'primaryKey' of undefined" error, and I did reproduce your case.

**Comment by IceOnFire** [comment]
Hi @Throttle,

Actually I gave up on using GraphQL for now since it has so many issues. I'm monitoring issue https://github.com/strapi/strapi/issues/2867#issuecomment-466038696 and believe that everything will sort itself out automatically after a good rewrite of that part.

**Comment by komocode** [comment]
Also having the same issue.

**Comment by tention** [comment]
Anyone manage to find a workaround?

**Comment by carlows** [comment]
I'm getting the same error when trying to apply a policy to a CRUD resolver:

```
module.exports = {
  resolver: {
    Mutation: {
      createSuite: {
        policy: [
          "plugins.users-permissions.isAuthenticated",
          "global.canUpdateResource"
        ]
      }
    }
  }
};
```

So we can't override the graphql schema right now? Or am I doing something wrong?

**Comment by lauriejim** [comment]
I tested it with the last version of Strapi (beta.17.7) and all work well.

@carlows in your case the key to use is `policies` and not `policy`
And you will have to specify also the resolver.

```js
module.exports = {
  resolver: {
    Mutation: {
      createSuite: {
        resolver: 'Suite.create',
        policies: ['global.canUpdateResource']
      }
    }
  },
};
```
