### ISSUE TITLE
Import error in custom plugin

### ISSUE THREAD

**Issue by ArthurKnoep** [strapi/strapi#2976]
**Informations**
- **Node.js version**: 11.10.1
- **NPM version**: 6.7.0
- **Strapi version**: alpha21 (I cannot update)
- **Database**: mongo
- **Operating system**: Linux Deepin 15.9

**What is the current behavior?**
When I'm launching strapi in dev mode (`cd admin && npm run start`),  
I get this error :
```Module not found: Error: Can't resolve 'routes.json' in '<path_to_strapi_project>/digipermis-back/plugins/<plugin_name>/node_modules/strapi-helper-plugin/lib/src'```

Utilmately I have an issue with all import in my plugin. For example, in the ExamplePage this import does not work:
`import Button from 'components/Button';`
(For the moment I have just comment this line and it's usage)

I'm working with the alpha 21 but I can't update since the tool for creating new strapi projetc won't work

**Steps to reproduce the problem**

```
strapi generate:plugin <plugin_name>
npm run setup && npm run setup --plugins
cd plugins/<plugin_name> && npm link strapi-helper-plugin
```

**Comment by soupette** [comment]
@ArthurKnoep can you check in the `strapi-helper-plugin/lib/src/**.js` if you there is a `require('../../***/routes.json');`somewhere and try to remove it?
