### ISSUE TITLE
Any plan for a beta or a stable version?

### ISSUE THREAD

**Issue by MatheusRV** [strapi/strapi#2978]

**Comment by gustavpursche** [comment]
@MatheusRV https://blog.strapi.io/goodbye-2018-hello-2019/

> ## From alpha to stable version

> Currently, Strapi is still in alpha version. Even if it is used by thousands of companies in production, this flag can be alarming for business projects. Releasing a stable version is one of our highest priorities. We plan to release the Beta version in April and the stable one in August.
