### ISSUE TITLE
Restore database MongoDB

### ISSUE THREAD

**Issue by jimmi2051** [strapi/strapi#2979]
**Informations**
- **Node.js version**: v11.10.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: Linux/Ubuntu 18.04
- **(Optional) Link to your Project**:

**What is the current behavior?**
Restore database success but can't use it. 

**Steps to reproduce the problem**
I restored database success, but i can't use it. Because, some data of Content Type lost Relation. I have to remove and add again relation with every record. 

**What is the expected behavior?**
Backup and restore database (MongoDB) success and don't lost anything in database. 

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello!

I'm not sure to understand your issue.
Can you explain me step by step what you did and what is the issue you had.

Thank you.

**Comment by jimmi2051** [comment]
Steps to reproduce the problem: 
1) Restore database MongoDB
2) strapi start 
3) I use localhost:1337/graphql to query 
Ex: 2 Content Type: School and Student. Relations School - Student : 1 - n
With data: {
id:"1"
name:"SchoolA"
      students{
         [
              student1{
                name:"A"
                },
              student2{
                name:"A"
                }
         ]
      }
}.
And Query: 
{
school(id:"1"){
          students{
                name
               }
        }
}
==> Result is null after i restored database.

**Comment by lauriejim** [comment]
If the relations doesn't work after a dump and restore it's can not come from Strapi but from your database migration.
If the issue come from GraphQL please try our last version `alpha.26.1` we fix many issues.
