### ISSUE TITLE
convertParams convert null to empty string

### ISSUE THREAD

**Issue by xeastcrast** [strapi/strapi#2981]
- [] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I'm not sure this is a bug or new feature request but I think this is a feature I need.

This feature can convert params to null but not '' (Empty string)

In a present when I convert a { deletedAt: null } to query params, It be {where: { deletedAt: '' }, ... }, So I can't where a null field.

**Comment by lauriejim** [comment]
Hello @xeastcrast !

Thank you for this report! Appreciate.
You are right. if should be converted to `null`.

But in any case there is an other issue (already exist normally) about the search off `null`
This feature doesn't exit. You can't search `null` value.

**Comment by lauriejim** [comment]
This issue is related to alpha function.
