### ISSUE TITLE
Cors, csrf, csp, hsts, p3p modules all completely bypassed if x-forwarded-host header passed in

### ISSUE THREAD

**Issue by markjlaney** [strapi/strapi#2982]
10.0.0
 6.0.0
yes

**Informations**
- **Node.js version**: 10.0.0
- **NPM version**: 6.0.0
- **Strapi version**: latest
- **Database**: Mongo 
- **Operating system**: MacOS 10.14.1
- **(Optional) Link to your Project**: 

**What is the current behavior?**

If you pass in x-forwarded-host, nearly all security modules are completely bypassed. This is a dangerous vulnerability that should be fixed immediately as it nearly renders the app completely insecure. 

**Steps to reproduce the problem**

Enabled all of the policies and then pass in that header. You'll see the security isn't there. Here is one example:

1. Enable the cors policy in the correct environment and set origin to whatever domain you want:
```
"cors": {
    "enabled": true,
    "origin": "https://fun-app.com",
    "expose": [
      "WWW-Authenticate",
      "Server-Authorization"
    ],
    "maxAge": 31536000,
    "credentials": false,
    "methods": [
      "GET",
      "POST",
      "PUT",
      "PATCH",
      "DELETE",
      "HEAD"
    ],
    "headers": [
      "Content-Type",
      "Authorization",
      "X-Frame-Options",
      "Origin"
    ]
  }
```

2. Run this curl command:
```
curl -isk -X OPTIONS 
-H 'x-forwarded-host: strapi' 
-H 'Access-Control-Request-Method: GET' 
-H 'Origin: https://fake.com' 
http://localhost:1337/content-manager/explorer/marketingtemplate/\?source\=content-manager
```

**What is the expected behavior?**
The expected behavior is that it will say https://fake.com is not a valid origin. Instead it allows the request through the app.

**Suggested solutions**

This should really be removed. It's only in the codebase to make interactions with the admin panel easier. However, it would be better if security were in place between the admin panel and the server.

**Comment by lauriejim** [comment]
Same as https://github.com/strapi/strapi/issues/2969
