### ISSUE TITLE
Password input shows encrypted password in user edit page

### ISSUE THREAD

**Issue by bykclk** [strapi/strapi#2987]
**Informations**
- **Node.js version**: 11.12.0
- **NPM version**: 6.70
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: SQLite
- **Operating system**: Ubuntu

**What is the current behavior?**
When you go to user edit page and show the password for the user, the input shows encrypted password.

**Steps to reproduce the problem**
Go to a user's edit page and click the eye icon right to the password input.

**What is the expected behavior?**
We can show the real password (which might be impossible beacuse it is encrypted) or replace the password input with a change password form.

**Suggested solutions**
Replace the password input with a change password form.

**Comment by lauriejim** [comment]
Thank you for this feedback - same topic as this issue https://github.com/strapi/strapi/issues/2769

**Comment by hkovacs** [comment]
im using Strapi v3.0.0-beta.17.4

this is still a problem.

i see the hashed value when i click the eye.

i also commented in 2769.

**Comment by hkovacs** [comment]
my comment in 2769 can be disregarded. 

i am curious why this is marked as closed if it is still possible to see the hashed value when i click the eye.

seems that if i click the save button, the password would be saved improperly.

**Comment by derrickmehaffy** [comment]
@hkovacs It was closed because it is a duplicate:

`same topic as this issue #2769` The other was closed from a PR however it doesn't exactly solve the direct issue so I will reopen that one to make a note.

**Comment by hkovacs** [comment]
i did a test and interestingly the password did not get improperly changed when i saved the edit form. so that's good news.
