### ISSUE TITLE
Can't modify Roles & Permissions with a large number of users

### ISSUE THREAD

**Issue by Tansito** [strapi/strapi#2992]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: v6.9.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: MacOS

**What is the current behavior?**
When I have a good number of users (let's say +6000 users) assigned to the `Authenticated` role I can't modify the `Roles & Permissions` for that specific Role due to the next error:
```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```
And I suppose that this is due to the body of the request because we are sending all the users in the request:
```
{
  description: "Default role given to authenticated user."
  name: "Authenticated",
  permissions: { ... },
  users: [ ... ] (array with more than 6000 objects)
}
```

**Steps to reproduce the problem**
- Have 6000 users assigned to `Authenticated` role.
- Modify the permissions of `Authenticated` role.

**Comment by Tansito** [comment]
How this is blocking us a bit right now do you have some kind of recommendation or work-around? We can modify the table `user-permissions-permission` directly but I don't know If you recommend this (taking into account the problem, of course).

**Comment by abdonrd** [comment]
Same problem here! Any recommendation?

**Comment by alexandrebodin** [comment]
We need to stop sending the list of users as it's not really needed to update the permissions. 

Don't hesitate to open a PR with a fix for that ;)

In any case we fix it as quickly as we can

**Comment by Krunalvaghasiya** [comment]
Is this issue fixed?

**Comment by lauriejim** [comment]
You will see commits and PR linked to this issue when we will work on ;)
For now we are focused on other topics.

**Comment by liming** [comment]
Any update of this issue? We cannot move forward without this being fixed. Is there any workaround of this bug?

I noticed the high priority label has been removed... How is this not high priority if there is not workaround provided?

**Comment by robclouth** [comment]
So I've done a workaround to reduce the size of the query:
```
"use strict";

/**
 * UsersPermissions.js controller
 *
 * @description: A set of functions called "actions" of the `users-permissions` plugin.
 */

const _ = require("lodash");

module.exports = {
  async getRole(ctx) {
    const { id } = ctx.params;
    const { lang } = ctx.query;
    const plugins = await strapi.plugins[
      "users-permissions"
    ].services.userspermissions.getPlugins(lang);
    const role = await strapi.plugins[
      "users-permissions"
    ].services.userspermissions.getRole(id, plugins);

    if (_.isEmpty(role)) {
      return ctx.badRequest(null, [{ messages: [{ id: `Role don't exist` }] }]);
    }

    // THE PART I ADDED: remove unnecessary fields to reduce the data size
    role.users = role.users.map(user => ({
      id: user.id,
      username: user.username
    }));

    ctx.send({ role });
  }
};

```
Put this in ```extensions/user-permissions/controllers```

This now works with 9000 users. (Still slow though)
