### ISSUE TITLE
How to use relation in mysql with "id" field?

### ISSUE THREAD

**Issue by daymont87** [strapi/strapi#2993]
I'm using MySQL and not understand how to use relations, for example:
I have 2 models "pack" and "sticker"
Table "packs" have an "id" field autoincrement and primary
Table "sticker" have a "pack_id" field

I want to make "One to Many" relation between pack "id" and sticker "pack_id" 
but when i try to make relation it writes me that "id field is reserved". How to make it properly? 
Am i need to make two duplicate  column in my table "id" and "_id"? Or there is some better way?

**Comment by lauriejim** [comment]
Hello, please follow the issue template so we can get a better understanding about the origin of your bug and to be able to help you.

I will reopen your issue as soon as it follows the templating guidelines.
Please update your issue.

Thank you.

> This is a templated message

**Comment by daymont87** [comment]
@lauriejim ok, made it by guidelines)
