### ISSUE TITLE
Can only fetch 100 items out of an array with graphql

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#2996]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**:  mlab
- **Operating system**:  windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I have an array of objects I'm trying to fetch, the array contains 108 items. When I'm fetching it using graphql plugin, I can only receive the first 100 items. When viewing the model on strapi, it shows the whole 108 items without any problem.

What could be the cause?
Are there settings that I can manipulate in order to fix it?

If it matters, the array looks somewhat like this:
0: {name: "בעיות דרך והספק רמה 4", type: "normal", _id: "5c6826fbb8fd082cf06cc28f"}
1: {name: "nameeee", type: "normal", _id: "5c6fc47e3d3ec43654bab998"}
2: {name: "nameeee", type: "normal", _id: "5c6fca423d3ec43654bab999"}
3: {name: "ניסיון דוגמאות", type: "normal", _id: "5c73f682d2802b20600e24ec"}
4: {name: "gfgg", type: "normal", _id: "5c742f2e2ce6da16b0e5a966"}
5: {name: "nameeee", type: "normal", _id: "5c78c2692e8aa703502a0c2e"}
6: {name: "nameeee", type: "matrice", _id: "5c7a05d99c320211bcc1f778"}

The fetching is standard:

```
    async fetchExams()  {
        const response = await strapi.request('POST', '/graphql', {
            data: {
                query: `query {
                    exams {
                      name,
                      type
                      _id,
                    }
                  }`
            }
        })
        console.log(response.data.exams.length) // prints 100
```

I know that I'm using windows 10 which is not supported, but please - this problem is probably not related to the os.

Thanks a lot in advance

**Steps to reproduce the problem**
Store in the db an array with more than 100 items

**What is the expected behavior?**

**Suggested solutions**

**Comment by xi-osman** [comment]
Please read this [document](https://strapi.io/documentation/3.x.x/guides/graphql.html#configurations)

**Comment by omerfaran** [comment]
Hello xi-osman I tried and it's not working. I changed the "amountLimit": 200
And still getting only the 100 first items.

Any ideas?
Thanks

**Comment by xi-osman** [comment]
Sorry @omerfaran not familiar with GraphQL or Strapi that much, You might be better asking on Slack.

**Comment by derrickmehaffy** [comment]
There is no count option in the graphql plugin yet no. Marking as closed as there is no issue and question resolved.

**Comment by omerfaran** [comment]
Thanks derrickmehaffy 

Don't you think that the docs should be updated? I mean, it's not intuitive at all that you need to explicitly specify the limit: > 100 once you change the settings.json

I would love to contribute and udpate the docs if you like

**Comment by omerfaran** [comment]
And xi-osman  thank you for your help!
