### ISSUE TITLE
Double quotes getting removed in string field

### ISSUE THREAD

**Issue by kesla** [strapi/strapi#2997]
**Informations**
- **Node.js version**:  10.14.2 
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.25.2 
- **Database**: mongodb 
- **Operating system**: Mac OS X and Linux (heroku)
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Double qoutes are sometimes removed from a text field.

I currently have some string fields that are double quotes and the quote-chars are removed when I saved the field.

**Steps to reproduce the problem**

Add a text field with the text `"foo"` save and the quotes are removed.

**What is the expected behavior?**

The double quotes are not removed

**Suggested solutions**

**Comment by henrych4** [comment]
I can confirm that the problem occurs in SQLite db as well. Both text field and string field are affected.

**Comment by henrych4** [comment]
Did some investigations on the problem. Probably related to the following code:
https://github.com/strapi/strapi/blob/124d0b1ebbebd7dca712cd71a512c0cbac758f1e/packages/strapi-plugin-content-manager/services/ContentManager.js#L63

When add/edit a text field or string field eg. "d", the original value is `'"d"'` and after `JSON.parse` method, value becomes `'d'`.

**Comment by lauriejim** [comment]
Thank you for this report!
Can you submit a PR to fix it. Thank you fort your contribution.
