### ISSUE TITLE
Is this project the best wet dream possible for any full-stack developer?

### ISSUE THREAD

**Issue by gotexis** [strapi/strapi#3001]
Hi, I just found out about this project 5 minutes ago and I couldn't believe what I saw.

I used to be a Django developer then I am trying to do Django+Vue+GraphQL then I find out the need for a Python backend server has diminished significantly so I am trying to switch from Django to Apollo/Express server but I could never trust a bloated API-as-a-Service plus I love my dear Generic CRUD Class-Based Views in Django.

And now I see this.

To me, this seems to be a godsend, customisable, self-hosted API builder with a GUI, and I can see how development speed will be on steroids with this.

**Too bad my current project is halfway done.** I have an opportunity cost of switching, so before scrapping everything and switching to this, I wonder if everyone here agrees that strapi is **THE FASTEST WAY** in full-stack development (given that I must use Vue.js / GraphQL).

The reason I ask this is that I don't want to keep switching stacks over and over... I would like to use the SHIT OUT OF the same fastest tool AGAIN AND AGAIN to earn MORRRRRRE MONEY in a EASY FASHION~!

Please share your thoughts, thanks ~

**Comment by harlyon** [comment]
I bet you it is.... but alot of plugins are still yet to be implemented but i tell you strapi is kool

**Comment by derrickmehaffy** [comment]
Please keep the GitHub issues clean except for bug reports and feature requests (and pg13)

Closing

**Comment by lauriejim** [comment]
Thank you @gotexis for this feedback!
I shared it with the team. Appreciate your words!
Feel free to tweet your feeling about Strapi it make big impact for us.
