### ISSUE TITLE
Help Videos cover last row actions

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#3006]
**Informations**
- **Node.js version**: 10.8.0
- **NPM version**: 6.2.0
- **Strapi version**: alpha 25
- **Database**: mysql
- **Operating system**: WSL/Ubuntu

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/2950505/54690897-a7575300-4b22-11e9-982c-d3aa145b7b09.png)

As you can see, the element of the help with the videos covers the last row.

**Steps to reproduce the problem**

create many content types  or fields or resize the window to see that the last item can't be edited.

**What is the expected behavior?**

Should be able to click the last rows actions. There is also no more space to scroll :)

**Suggested solutions**
have the floating action button either:
* Only be as big as the button, when videos are hidden
* Or make the button/videos dismissable
* Or move button to lower left into the menu
* Add more space to EVERY single admin page.

**Comment by lauriejim** [comment]
Thank you @MartinMuzatko for this feedback!
