### ISSUE TITLE
How to serve static react frontend from Strapi?

### ISSUE THREAD

**Issue by lappalj4** [strapi/strapi#3007]
Hey, sorry if this doesn't conform to the issue templates but I didn't find a template for questions and not sure where else to ask.

I'm building a React frontend to consume my Strapi API in a monorepo, and have some issues serving the static React build from my Strapi server. 

I have the React app built in a `build` directory under my Strapi backend, and I'm successfully serving it with `koa-static`, with the following code in `server.js`:

```
(() => {
  const strapi = require('strapi');
  strapi.app.use(require('koa-static')('./build'));
  strapi.start();
})();
```

I've also prefixed all of my strapi api routes with `/api/` so that they don't get mixed up with my frontend routes. It all works well enough if I navigate to `http://mysite.com` in a browser (the react app gets served, and routing within that works)

However, if I use my address bar to navigate to a route other than the site root, say `http://mysite.com/myroute`, strapi no longer serves my React app but instead responds with a 404:

```
{
"statusCode":404,
"error":"Not Found",
"message":"Not Found"
}
```

**So the question really is** how do I set this up so that the strapi app would serve my static React app on all requests except for `/api/*` and `/admin/*`?

Thanks in advance :)

**Comment by lauriejim** [comment]
Hello!
You can join the Slack channel to get help from the community (https://slack.strapi.io)

You will find information here 
- https://stackoverflow.com/questions/55074616/strapi-front-end-react-hosting/55130583#55130583
- https://stackoverflow.com/questions/55090339/strapi-custom-routes-to-redirect-to-public-directory/55130475#55130475

**Comment by firma777** [comment]
There are lots of questions in the web how to host a react app in public folder but there is no answer how to config strapi to achive it. I would like my front-end app is being loaded from the root of the website without any subfolders. Here is an exaple https://domainname.com/ not http://domainname.com/subfolder
Can some one tell me how can I achive it?
Currently when I put react app in /public it works but when I navigate for exaple to http://domainname.com/somearticle and then refresh the page I got 404 - page nit found.

**Comment by derrickmehaffy** [comment]
@firma777 while it may be possible, it's not something we support at this time, my suggestion would be to keep the two split and use a frontend proxy like Nginx, HAProxy, Traefik, Apache, ect to handle the routing. We have detailed guides on our docs to handle this: https://strapi.io/documentation/v3.x/getting-started/deployment.html#optional-software-guides
