### ISSUE TITLE
Can't query GraphQL with name collection "Contactsection1Intro"

### ISSUE THREAD

**Issue by jimmi2051** [strapi/strapi#3011]
**Informations**
- **Node.js version**: v11.10.0
- **NPM version**: 6.7.0
- **Strapi version**:  3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: Linux/Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Can't query GraphQL with name the same "contactsection1intros"

**Steps to reproduce the problem**
1) Strapi start
2) Create new Content type with name "contactsection1intro" | Format "string|number|string"
3) Add data
4) Query with GraphQL <--- errors 
-- "message": "Cannot read property 'fetchAll' of undefined",
**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @jimmi2051 !

Can you please not use numbers in your content type name.
With that not only GraphQL crash but REST route too.

We will block the possibility to add numbers in content type. It's not a good practice
