### ISSUE TITLE
Can't create plugin

### ISSUE THREAD

**Issue by q-jason** [strapi/strapi#3013]
**Informations**
- **Node.js version**: v10.15.3 
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**:  mongo
- **Operating system**:  win10（wsl Ubuntu）
- **(Optional) Link to your Project**:  null

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/28495915/54755739-93dee180-4c21-11e9-8567-3762310763e2.png)

**Steps to reproduce the problem**
> According to the official website
```bash
git clone git@github.com:strapi/strapi.git
-
cd strapi && npm run setup
-
cd .. && strapi new myDevelopmentProject --dev
-
cd myDevelopmentProject && strapi start
-
cd /path/to/myDevelopmentProject && strapi generate:plugin my-plugin
-
cd plugins/my-plugins
-
npm link strapi-helper-plugin
-
cd /admin && npm run setup
-
npm start
-
-> localhost：4000 / admin
```

**What is the expected behavior?**
I'm sorry that my English is not very good, I want to write a plug-in, but at this stage I can't make progress because of the error

**Suggested solutions**

**Comment by soupette** [comment]
Hi @q-jason it appears you have a selector error, can you please check the generated selectors.js files in your created plugin?

**Comment by ChristopherDosin** [comment]
@soupette I've the same error - If you create a plugin an click on the new menu entry, you will get the above output and a blank white site.

**Comment by lauriejim** [comment]
@soupette I think the plugin generator is not up to date.
