### ISSUE TITLE
Eslint crashing because of babel-eslint

### ISSUE THREAD

**Issue by arsenx** [strapi/strapi#3017]
**Informations**
- **Node.js version**: v11.10.0
- **NPM version**:  6.7.0
- **Strapi version**: 
- **Database**: 
- **Operating system**:  MacOS Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When using babel-eslint ^6.0.0 eslint console output breaks. Are there any breaking changes in upgrading to ^7.0.0?

**Steps to reproduce the problem**
I use VScode and eslint breaks

**What is the expected behavior?**
Not to break

**Suggested solutions**
I upgraded babel-eslint package from ^6.0.0 to ^7.0.0 current version is around 10 and seems to have fixed the issue for myself but need someone to take a look

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

Please give us more details
