### ISSUE TITLE
afterCreate is the only model action working for webhook workaround

### ISSUE THREAD

**Issue by mdxprograms** [strapi/strapi#3018]
**Informations**
- **Node.js version**: 11.7
- **NPM version**: 6.9
- **Strapi version**: v3.0.0-alpha.25.2
- **Database**: mongo
- **Operating system**: Ubuntu 

**What is the current behavior?**
I'm using this guide https://strapi.io/documentation/3.x.x/guides/webhooks.html#webhooks
Which details to use 3 different actions to post to a webhook when triggered.
The `afterCreate` is the only action that actually fires.
I've tried removing an item and updating an item and neither triggered a webhook for me.

**Steps to reproduce the problem**
I added an item and the webhook triggered on netlify immediately.
When updating a title of an item and saving it did not trigger a webhook.
When removing/deleting an item it did not trigger a webhook.

**What is the expected behavior?**
All model actions should trigger a webhook as documented here https://strapi.io/documentation/3.x.x/guides/webhooks.html#webhooks

**Suggested solutions**
I don't have one at the moment

**Comment by mdxprograms** [comment]
I'm going to close this after reading a previous issue where it was stated that `afterUpdate` is always triggered. If this is the case then I can rely on that event to post the webhook.

**Comment by kapoko** [comment]
I'm on strapi@beta.14 and MongoDB and having a problem with webhooks.

`afterSave` seems to trigger on `insert` but not on `update`. `afterUpdate` and `afterDestroy` don't seem to do anything.
