### ISSUE TITLE
Sending an email on contact form filled

### ISSUE THREAD

**Issue by lappalj4** [strapi/strapi#3021]
I'd like to send an email notification to site admins whenever someone fills my contact form, and I'm wondering what would be the idiomatic way to do that. The docs don't go into much detail on how to accomplish things like this, and I'm a bit unsure of how to plug in to the strapi model lifecycle callbacks so I'd appreciate some help :)

So what I've done is created a content type for "contact requests" and I'm using the strapi endpoint `POST /contactrequests` whenever someone fills the form, and a new contactrequest gets created. 

I'd like to hook into that process to send an email to e.g. support@mycompany.com so that people are notified whenever someone fills the contact form. 

I'd like to use the Sendgrid plugin for emails, and ideally there would be a way to set the email where the notifications get sent in an env variable or similar. 

Any help / examples where this has been done? Thanks.

**Comment by derrickmehaffy** [comment]
@lappalj4 please use the slack: https://slack.strapi.io for questions like this. 

We try to limit the number of issues to feature request/discussion and bug report related to strapi as a whole. Else it can be quite taxing and difficult to track new bug reports and such.

For now I'll mark this as closed, you are welcome to continue discussion here even after it's closed. Just trying to help keep the open issues to a minimum 😉

**Comment by lappalj4** [comment]
Ok yeah thanks, was unaware of a better channel for these sorts of questions! :)
