### ISSUE TITLE
Which algorithm is used to generate the sha256 field for the upload_file documents?

### ISSUE THREAD

**Issue by steampixel** [strapi/strapi#3023]
I want to convert some data from another headless cms to Strapi. But I am not able to figure out how to generate the sha256 field for my uploaded files inside the strapi database. If I upload some file through the Strapi backend I can see this value inside the database. This is definitily not a sha256 value. A hash of this kind should consist only of lower case hex values. But this looks very different to the value calculated with my importer script. Can you please tel me how this values gets calculated? Is this a special variant of sha256?

**Comment by derrickmehaffy** [comment]
@steampixel please send questions like this on the Slack: https://slack.strapi.io

We try to keep the github issues to bug reports and feature requests only. You are welcome to continue the discussion here, but I am marking this as closed to help keep the issue list clean and easier to find open issues.

**Comment by lauriejim** [comment]
Feel free to open a question on Stackoverflow for this kind of need.
