### ISSUE TITLE
Returns 403 While using MySQL and Windows system

### ISSUE THREAD

**Issue by arajchalise** [strapi/strapi#3024]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
While using Windows platform, the admin login/register is not loading and respond with 403 error. 

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@arajchalise please fill out the required template and post once that has been updated and this can be reopened. Please see the following comment in the template:

`<!-- ⚠️ If you do not respect this template your issue will be closed. -->`
