### ISSUE TITLE
development admin pannel run error

### ISSUE THREAD

**Issue by yinglau** [strapi/strapi#3025]
**Informations**
- **Node.js version**:  v10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: mysql
- **Operating system**:  macos mojave

**What is the current behavior?**
when i `npm start` in my project created with `--dev`, there are some problem like this:
![image](https://user-images.githubusercontent.com/16402665/55003150-ca966c80-5012-11e9-84f4-a2c0377e2662.png)

**Steps to reproduce the problem**
1. `strapi new project --dev`
2. `cd project && cd admin`
3. `npm run start`

**Comment by lauriejim** [comment]
Hello! 
Did you follow the [contribution guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#setup-development-environment) to install strapi ?

If you try to install strapi with `npm i strapi@alpha -g` and the to create a project with `--dev` it's normal if it doesn't work.

**Comment by yinglau** [comment]
> Hello!
> Did you follow the [contribution guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#setup-development-environment) to install strapi ?
> 
> If you try to install strapi with `npm i strapi@alpha -g` and the to create a project with `--dev` it's normal if it doesn't work.

OK, I will try to follow the contribution guide, thank you.

**Comment by yinglau** [comment]
> Hello!
> Did you follow the [contribution guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#setup-development-environment) to install strapi ?
> 
> If you try to install strapi with `npm i strapi@alpha -g` and the to create a project with `--dev` it's normal if it doesn't work.

Hello, I have tried to follow the `CONTRIBUTING.md` and create a new project with `--dev`, but here are another problem, I open a new issue #3034

**Comment by lauriejim** [comment]
So I can close this issue, you have the issue cause you did not install the mono repo before creating the app with `--dev`
