### ISSUE TITLE
Testing, 1, 2, ...3? 

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#3026]
- [x ] **I have created my request on the Product Board before I submitted this issue**
- [√ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Greets team strapi!

Is the testing document for 1.x still valid for 3.x? this => https://strapi.io/documentation/1.x.x/testing.html#setup

-Dan

**Comment by derrickmehaffy** [comment]
@cube-dan +10 points for the creative title.

Closing due to this not being a feature request though :cry: 

Please use the Strapi Slack for questions: https://slack.strapi.io

**Comment by cube-dan** [comment]
I've only recently learned to read ... this: https://github.com/strapi/strapi/#community-support

Thanks for the slack tip!

**Comment by derrickmehaffy** [comment]
@cube-dan no problem, for clarification I submitted a pull request to help others that find themselves in the same situation: https://github.com/strapi/strapi/pull/3027
