### ISSUE TITLE
(node:21221) UnhandledPromiseRejectionWarning: error: column "id" is in a primary key

### ISSUE THREAD

**Issue by tshelver** [strapi/strapi#3028]
**Informations**
- **Node.js version**: v11.12.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: Postgresql 11.2  (my production DB for other systems.
- **Operating system**: Ubuntu 18.04 
- **(Optional) Link to your Project**:Once I have a successful non-trivial test....

**What is the current behavior?**
THis is as much a question on usage as anything. See the question below the procedure I followed to get here
What I did prior to this.
1. Added Category content type and entered a category
1.a.  Started to add product and realised I needed a brand.  Clicked out of Content Type plugin and back in again to reject Product
2. Added Brand content type, and entered a brand
3. Added Product content type
(note: Fairly complex content type with 2 foreign keys (relationships), 4 image fields, one multiple images allowed.)
What I did that maybe caused this.  When creating the brand and category relationships, I pointed the Product.category_id to the Catebory.id column.
And, product.brand_id to Brand.id column 
--

Question:
Is this illegal usage in Strapi?  It's pretty much how one would usually define a foreign key in any RDBMS.
And.......  Is there anyway to recover this without starting all over again from scratch?

After this, server refused to restart 

Checked in Postgres: all the above tables were added.  (Note Indexes created on columns seemingly based on the column name, but NOT on the foreigh key columns).

Checked in /API: all of the above entries (Category, Brand, Product) were created.

Log messages below:

tshelver@T540p:~/git/surehome_cms$ strapi start
[2019-03-26T18:10:42.492Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
[2019-03-26T18:10:42.499Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
[2019-03-26T18:10:42.504Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
(node:21221) UnhandledPromiseRejectionWarning: error: column "id" is in a primary key
    at Connection.parseE (/home/tshelver/git/surehome_cms/node_modules/pg/lib/connection.js:601:11)
-
-
Lots more inconsequential messagess
-
-
(node:21221) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21221) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-26T18:10:45.330Z] debug ⛔️ Server wasn't able to start properly.
[2019-03-26T18:10:45.331Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load

**Steps to reproduce the problem**
Tried to restart server

**What is the expected behavior?**
To work?

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello!

> Can you please take time to update you issue template, it's not easily readable.
> Code, log and commands are not well templated.
> I read and answer ~100 issues per day it will help in my work. Thank you.

Did you create all your content type via the Admin UI ? or you did some custom files update ?

**Comment by tshelver** [comment]
Apologies for the weird template thing.  I am not a markdown expert, whatever I did it kept bolding that text.

Everything was done through the template.

As for the question I asked, I have worked out that it's not a good idea to do anything or refer to the generated content type id column.  I got around this by creating a 'natural key' column as an additional field to act as the relational target.

Since then I have had other issues.  Facing a bit of a project deadline so having to reassess what i am really trying to achieve with Strapi.  
I hacked out something today that I will test tomorrow that can buy me some time until Strapi is a bit more mature.

You can close this for now. Maybe an obvious usage note in the documentation somewhere would be a sufficient fix.

**Comment by lauriejim** [comment]
Hum okay.
The update you did in your database look not be liked by Bookshelf.
It's not recommended to update manually things in the database without using the Admin UI

**Comment by tshelver** [comment]
As I said, I didn't touch the database.  Everything was done through the content manger.

Worked with enough systems over the decades that generated database structures to be very, very cautions about touching the DB directly.
