### ISSUE TITLE
Dates can't be updated anymore on MySQL

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#3031]
**Informations**
- **Node.js version**: 10.8.0 
- **NPM version**:  6.2.0
- **Strapi version**: alpha 0.25 
- **Database**:  mysql
- **Operating system**: WSL/Ubuntu 
- **(Optional) Link to your Project**: 

**What is the current behavior?**

I can't update dates anymore via strapi admin
![image](https://user-images.githubusercontent.com/2950505/55040531-0a684e80-5029-11e9-93e7-07afbc2f8651.png)

**Steps to reproduce the problem**

create a model with a date field
change field with built-in datepicker
press save

**What is the expected behavior?**

dates should be written in correct format

**Suggested solutions**

**Comment by milanffm** [comment]
same without any date field:
[https://github.com/strapi/strapi/issues/3036](url)

**Comment by MartinMuzatko** [comment]
This is my very unbeautiful fix, in the model hooks:

```js
function convertMysqlDate(date) {
  return new Date(date)
    .toISOString()
    .slice(0, 19)
    .replace('T', ' ')
}

module.exports = {
  // Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: async (model, attrs, options) => {

    attrs.startDate = convertMysqlDate(model.attributes.startDate)
    attrs.endDate = convertMysqlDate(model.attributes.endDate)
    attrs.registrationStartDate = convertMysqlDate(model.attributes.registrationStartDate)
    attrs.registrationEndDate = convertMysqlDate(model.attributes.registrationEndDate)
    return true
  },
```
