### ISSUE TITLE
how to post an array to strapi

### ISSUE THREAD

**Issue by SuperRun** [strapi/strapi#3033]
I try to use curl to test the post request, but it shows the "500" error.

`curl -H "Content-Type: application/json" -X POST -d '[{"username": "user1", "password": "123456"},{"username":"user2","password":"123456"}]' http://localhost:1337/yomusers`

`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`

**Comment by derrickmehaffy** [comment]
@SuperRun please make sure to follow the templates, github issues is only for Bug reports or Feature requets.

Side note: you can't bulk post data, see the following feature request on the product board: https://portal.productboard.com/strapi/c/42-bulk-route-to-create-multiple-entries

I am marking this as closed as it does not follow a template.
