### ISSUE TITLE
development admin run error

### ISSUE THREAD

**Issue by yinglau** [strapi/strapi#3034]
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: mysql
- **Operating system**: macos mojave

**What is the current behavior?**
I'm following the `CONTRIBUTING.md` to do, and create a new project with `--dev`, but when I `npm start` in floder `admin` that the view page is loading for long time, I can't see the view content, but the loading icon is always see.

![image](https://user-images.githubusercontent.com/16402665/55070171-a2fddd80-50c0-11e9-8f1b-0ccb1292ce6b.png)

**Steps to reproduce the problem**
```bash
strapi new devapp --dev
cd devapp && cd admin
npm run start
```

**Comment by soupette** [comment]
What's is the error in the chrome console ?

**Comment by yinglau** [comment]
> What's is the error in the chrome console ?

chrome console:

![image](https://user-images.githubusercontent.com/16402665/55083224-1cf08f80-50de-11e9-965b-71da977e6132.png)

**Comment by soupette** [comment]
Honestly I have never encountered this bug before...

**Comment by theonlydaleking** [comment]
Can confirm after following the contrib.md setup instructions i get the spinny wheel of death too after a webpack build

**Comment by lauriejim** [comment]
Hum I have a question, why your admin run on port 3000 ? By default it's 4000.

**Comment by enricobuehler** [comment]
Also having the exact same problem. Tested on 2 Linux machines and one macOS.

**Comment by yinglau** [comment]
> Honestly I have never encountered this bug before...
> 
> What steps did you follow to get started?

Following the CONTRIBUTING.md, copy the repo to my github, and clone to my local system, then into the `strapi` floder run `npm build`, then we can use the `strapi` commander.

Create a new project with `--dev`, the front is run success. Go into `admin` floder, then `npm start`,  finaly see my problem.

**Comment by yinglau** [comment]
> Hum I have a question, why your admin run on port 3000 ? By default it's 4000.

Because I edit the `package.json`,  `prestart` and `start` item I change it to 3000.

**Comment by yinglau** [comment]
I create anther project, also with `--dev`, now show the errors like it:
![image](https://user-images.githubusercontent.com/16402665/55458619-0edfc900-5620-11e9-9ab6-5283a2c5c802.png)

chrome console msg:
![image](https://user-images.githubusercontent.com/16402665/55458656-2ae36a80-5620-11e9-9a07-e1188cac484a.png)

**Comment by yinglau** [comment]
hello, @lauriejim @soupette , I get the solutions in issue 1768, finally run success. Thank you so much @soupette.
