### ISSUE TITLE
MySQL  ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value

### ISSUE THREAD

**Issue by milanffm** [strapi/strapi#3036]
**Informations**
- **Node.js version**: 
Node v10.14.2
- **NPM version**: 
npm 6.4.1
- **Strapi version**: 
strapi 3.0.0-alpha.25.2
- **Database**: 
MySql MariaDB 10
- **Operating system**: 
MAC
- **(Optional) Link to your Project**: 

**What is the current behavior?**
you cannot update via strapi admin.

**Steps to reproduce the problem**

install a fresh version strapi 3.0.0-alpha.25.2
width MySQL as Database

**What is the expected behavior?**
Update Modals via Admin Panel.

**Suggested solutions**
In Version 3.0.0-alpha.24.1 ist works correctly on the same local machine

**Comment by lauriejim** [comment]
Hello!

Please give us exact steps to reproduce and understand your issue.
It's currently not understandable.

**Comment by milanffm** [comment]
now it works. I dry to reproduce the error and it don't happend again :-)
