### ISSUE TITLE
API Integration Testing for Strapi 3.x

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#3040]
- [√] **I have created my request on the Product Board before I submitted this issue**
- [√] **I have <del>looked at all</del> skimmed the titles of the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I'd like the have testing integration analogous to what was available in 1.x => https://strapi.io/documentation/1.x.x/testing.html#setup

Thanks for your consideration guys.

**Comment by Aurelsicoko** [comment]
I've created a private card on our Product Board, it means that you won't see it in the public roadmap but don't worry, I will consider it. The priority is not high but it's not so low too.

**Comment by cube-dan** [comment]
Thanks Aurélien. I appreciate your teams efforts; greatly!

**Comment by kaiwen-lin** [comment]
It would defs be awesome to get testing back!
For now, I've been using https://github.com/bahmutov/start-server-and-test as a workaround. Not ideal, but it works.

**Comment by iamfeek** [comment]
@kaiwen-lin Thanks for the resource.

Did you also configure your CI to run it?
