### ISSUE TITLE
[Question] Should I put build directories to git repository?

### ISSUE THREAD

**Issue by gustawdaniel** [strapi/strapi#3041]
I following tutorial

> https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/

When I wanted to `git add .` I saw that 

```
git status | grep build | wc -l
858
```

My intuition tells that it is wrong, but it is my first contact with strapi. Can you explain? It should be ignored or no? If no why?

**Comment by derrickmehaffy** [comment]
@gustawdaniel Yes you should include them as you can't rebuild them at the project level yet.
