### ISSUE TITLE
Many-to-many relations for users-permissions plugin not working

### ISSUE THREAD

**Issue by shalvah** [strapi/strapi#3042]
**Information**
- **Node.js version**: 10.12.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MySQL 5.7
- **Operating system**: Windows 10/Linux

**What is the current behavior?**
When a many-to-many relation is set up between a model and the User model, queries to fetch the model fail with this error:

```sql
select `users-permissions_user`.*, `stores_administrators__users_stores`.`store_id` as `_pivot_store_id`, 
`stores_administrators__users_stores`.`user_id` as `_pivot_user_id`
 from `users-permissions_user` 
inner join `stores_administrators__users_stores` 
on `stores_administrators__users_stores`.`user_id` = `users-permissions_user`.`id`
 where `stores_administrators__users_stores`.`store_id` in (1) 
- ER_BAD_FIELD_ERROR: Unknown column 'stores_administrators__users_stores.user_id' in 'field list'
```
It seems that the wrong field name is being used on the pivot table (`user_id` instead of `userspermissionsuser_id`).

**Steps to reproduce the problem**
1. Set up a model in your project (Store):

```{
  "connection": "default",
  "collectionName": "store",
  "info": {
    "name": "store",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    }
  }
}
```
2. Create a new instance of this model
3. Add  a `users` relation to the Store model:

```
    "administrators": {
      "collection": "user",
      "via": "stores",
      "plugin": "users-permissions"
    }
```
4. Add the stores relation to the attributes in the user model:

``` 
   "stores": {
      "collection": "store",
      "via": "administrators"
    }
```

5. Make a request for a store in your database (using the graphql plugin):

```
{
    store (id: 1) {
      name
    administrators { id }
    }
  }
```

**What is the expected behavior?**
Querying for a store should return the users belonging to it.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello! Did you create your relation by editing manually files or via the admin UI ?

**Comment by lauriejim** [comment]
I just reproduce your steps via the UI and it works on my side

**Comment by shalvah** [comment]
I did this via code.

**Comment by vanpana** [comment]
I also have this problem. Created the relation via UI for the user. It restarts the server and never lets me log back in.

**Comment by shalvah** [comment]
Yup, observed the login behaviour as well.

**Comment by lauriejim** [comment]
I suggest you to create your relation via the dashboard, it will avoid you issues.
`dominant` key is missing in your example, that is why it doesn't work.
Documentation here if you want https://strapi.io/documentation/3.x.x/guides/models.html#relations
But in any case please use the UI, it's safer.

**Comment by shalvah** [comment]
Does the `dominant` key apply here? I'm using a MySQL database?

Also, yes, the UI might be safer, but there's a reason strapi also allows a
code-based setup. The idea is that someone can clone the project and run
`strapi start` and have the same configuration as the production
environment.

**Comment by lauriejim** [comment]
Yap you have to follow the documentation. The dominant key is required here.
