### ISSUE TITLE
Can't query with mongoose ObjectID / Strapi String in the { where } clause. GraphQL

### ISSUE THREAD

**Issue by timkulich** [strapi/strapi#3045]
**Informations**
- **Node.js version**: v11.9.0
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: MacOS Mojave 10.14.3 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Using the GraphQL plugin, a query such as:
```
query {
    books( where: { author: "57027b84e43ecf0287d7ba0e" } ) {
        author
        (...)
    }
}
```
returns an empty array instead of the books where the author field matches the string. 
The author id in the where clause is an ObjectID in the database and saved as a String in Strapi.
A query such as:
```
query {
    books {
        author
        (...)
    }
}
```
returns books where the author has the same id as the one used in the above " where " clause, so it does exist. 

If I create a book in the Strapi UI with the same string ("57027b84e43ecf0287d7ba0e" in this case) and try the query, it returns the correct result. 

**Steps to reproduce the problem**

- Connect Strapi project to a mongoDB database in which a collection includes at least one field with an ObjectID. Let's say a Books collection with an Author field of type ObjectID.

- Create a Book document with a proper ObjectID in the Author field. 

- In Strapi, create a Content type matching that of the DB. Only difference is that the Author field is of type String instead of ObjectID.

- Try to do a query such as described above.

**What is the expected behavior?**

The query should return the book/-s matching the condition.

**Suggested solutions**

**Comment by lauriejim** [comment]
An issue exist about the deep filtering.
And a PR will be merger next week to allow this feature https://github.com/strapi/strapi/pull/2961
