### ISSUE TITLE
Reorder images via GUI

### ISSUE THREAD

**Issue by Huc91** [strapi/strapi#3049]
**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Unable the reorder multiple uploaded images in Media via GUI

**Steps to reproduce the problem**
Add a Media field, upload images

**What is the expected behavior?**
Being able to reorder them
[example](https://i.imgur.com/uIHuERs.png)

**Suggested solutions**
Someone knows if there is a way to reorder images via GUI? Or it will be a feature in the upcoming releases?  It will be really useful, it's going to happen with the [media library](https://strapi.io/marketplace/media-library) plugin release?

**Comment by Aurelsicoko** [comment]
@Huc91 Yes, the Media Library plugin will be an extension of the Upload plugin, and it will allow the reorder of the images. In consequence, I'm closing the issue 👍

**Comment by Huc91** [comment]
@Aurelsicoko Thanks for the answer, looking foward to it, keep up the good work

**Comment by goodok21** [comment]
Is it feature already implemented?

**Comment by derrickmehaffy** [comment]
> Is it feature already implemented?

Currently no as we don't support ordering of relations: https://strapi.io/documentation/developer-docs/latest/getting-started/troubleshooting.html#relations-aren-t-maintaining-their-sort-order

**Comment by DjovDev** [comment]
Just checking in, is it possible that this is still not possible?

**Comment by andymark-by** [comment]
Hi, how about now, I see this item has been removed from the FAQs
How can we order the images in the GUI?
