### ISSUE TITLE
Removing content type doesn't remove data from api

### ISSUE THREAD

**Issue by imkrunal** [strapi/strapi#3055]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Removing the content type removes the relation from other content type but doesn't remove data.

**Steps to reproduce the problem**
1. Create 2 content types
2. Add relation
3. Add content to both
4. Delete one content type
5. Check API old content still exists

**What is the expected behavior?**
It should remove the data from API.

**Suggested solutions**

**Comment by alexandrebodin** [comment]
@imkrunal Can you provide more context ? 

Errors in the console / the models you are trying to delete etc. 

Thanks

**Comment by lauriejim** [comment]
We need the know the relation between your models and the way you use to delete your data.

**Comment by imkrunal** [comment]
I don't have any error I had many-many relations between two tables added some data to both tables and then deleted one table(content-type-builder). But the data which I inserted still exist in the API. it should be removed if we delete whole content type.

**Comment by soupette** [comment]
@imkrunal we don't delete your data when you remove a content type, so the best way to do it is first delete all your data either with a script or the UI and then remove your table.

**Comment by Aurelsicoko** [comment]
It's related to this issue https://github.com/strapi/strapi/issues/1114... 

@imkrunal I'm closing this one, please read carefully the linked issue above and feel free to give your thoughts about it. Thank you :)
