### ISSUE TITLE
Change admin url path not working

### ISSUE THREAD

**Issue by MatteoGioioso** [strapi/strapi#3056]
**Informations**
- **Node.js version**:  10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mongoddb
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**
I am using https://github.com/strapi/strapi-docker slightly modified to fit my needs.
I have tried to change the admin url on my `./config/environment/production/server.json` as showed in the docs
```
{
  "host": "www.admin.domain.com",
  "port": "${process.env.PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": false
  },
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
    "path": "/03810031"
  }
}
```
When I navigate there, the page does not load giving me the following error
`cannot find main.js`

**Steps to reproduce the problem**
Just change try to change url

**What is the expected behavior?**
It should navigate to the admin page

**Suggested solutions**

**Comment by mlindemu** [comment]
@MatteoGioioso, you need to run step #2 of the deployment guide in your project directory.  It is not optional if you change your admin path.  See:
https://strapi.io/documentation/3.x.x/guides/deployment.html

**Comment by lauriejim** [comment]
Thank you @mlindemu for your help!

**Comment by PiecePaperCode** [comment]
solution link is 404

**Comment by MattieBelt** [comment]
Hey @PiecePaperCode,

You can check out the `server.js` configuration here: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#server
And how to only configure it for your production env, here: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#environment
