### ISSUE TITLE
Deploy on AWS script - to launch strapi on AWS lambda

### ISSUE THREAD

**Issue by tomakali** [strapi/strapi#3060]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
strapi is a great tool to create/manage api
can someone create a "deploy on AWS" script to launch strapi on AWS lambda?

**Comment by lauriejim** [comment]
Hello, there is already issue about that.
I let you check here https://github.com/strapi/strapi/issues/1908
