### ISSUE TITLE
Using amazon RDS (mySql) showing forbidden error on admin but working fine with mongodb

### ISSUE THREAD

**Issue by ianmacalisang** [strapi/strapi#3062]
Informations:
- Nodejs version: 10.15.3
- NPM Version: 6.4.1
- Strapi Version: 3.0.0-alpha.25.2
- Database: Amazon RDS (mysql)
- Operating System: Windows 10

**What is the current behavior?**
Showing a forbidden error and showing only blank screen on /admin

![Screenshot from 2019-04-01 14-14-51](https://user-images.githubusercontent.com/39157186/55320735-e96c8700-5488-11e9-9a4b-ab529ec98444.png)

**Comment by lauriejim** [comment]
Hello!
This is a weird issue.
Can you try to delete your tables and restart your application.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
