### ISSUE TITLE
<Model>.find is not a function

### ISSUE THREAD

**Issue by RiesvGeffen** [strapi/strapi#3064]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MySQL
- **Operating system**: Windows 10

**What is the current behavior?**
When trying to fetch I get <model>.find is not a function.

**Steps to reproduce the problem**
1. Create a new strapi project with MySQL
2. Generate API with: `strapi generate:api brand`
3. Go into admin panel (register because it is the first time)
4. Add string attribute with name: `name`
5. Add a brand via admin panel
6. Go to this link: http://localhost:1337/brands
Terminal will now give: `TypeError: Brand.find is not a function`

**What is the expected behavior?**
Receive a list of all brands.

**Suggested solutions**
Got none, this should work I assume.

**Comment by lauriejim** [comment]
Hello, your issue look the same as https://github.com/strapi/strapi/issues/2844
