### ISSUE TITLE
[Question] Is strapi will be suitable for following use-case?

### ISSUE THREAD

**Issue by asharamseervi** [strapi/strapi#3069]
Hi there, as I'm self-taught developer working on random own projects alone (no team, no friend for guide/mentoring me). I'm seeking support, support in the sense, whether my ongoing project good to deploy with Strapi, or should I look for other things.

Use Case:
By using 3rd Party HTTP REST APIs (Built-in PHP/Curl), I want to make some transactions(purchase/recharge/remittance/payment/more likewise their services) with their platform. But, I want to scale this project to multiple users with some _privllages levels_ (like retailer/distributor/stockist) in services.

By their APIs, I'm able to use my own customized frontend dashboard (built with ant.design + next pages) and hence present scenario looks cool for 1 user. But, with more users, according to their privileges, I'll generate their frontend.

The issue is to involve Strapi as a backend, user management, their personalized transactions reports, along using their APIs + Strapi APIs. MongoDB preferred as database. Now, Can I store their JSON response to strapi occupied database, and can see/manage that responce in strapi or just show them in frontend dashboard as per their auth & they can continue to use 3rd party services. Anyone will help, how to accomplish this scenario.

**Comment by derrickmehaffy** [comment]
Hello,

Please see the following entry in the readme file: https://github.com/strapi/strapi#community-support

In order to try and keep the github issues clean only bug reports and feature requests should be posted here, please use one of the other areas to post questions. I am marking this as closed though you are welcome to continue the discussion.
