### ISSUE TITLE
Changing  the non-required field to requried field and arrange it

### ISSUE THREAD

**Issue by bykclk** [strapi/strapi#3074]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: SQLite
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
When created a non-required field, then converted to required field after adding a data, the server does not restart.

**Steps to reproduce the problem**
Add Content Type and add a field for that content type. Then add content type data and leave the field empty. After that, organize that field and mark the Required Field option in settings, then save it.

**What is the expected behavior?**
It needs to warning while saving.

**Suggested solutions**
Warnign while getting error and not saving.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2621

> This is a templated message
