### ISSUE TITLE
Strapi lost the connection to Database

### ISSUE THREAD

**Issue by Vivsss** [strapi/strapi#3083]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**:  6.9.0
- **Strapi version**:  3.0.0-alpha.25.2
- **Database**: Mongodb
- **Operating system**: Ubuntu 18.04.2
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I've created a react app with Strapi; that is in a nginx server but Strapi lost the connection to its Mongo Database; when I perform 

NODE_ENV=production pm2 start strapi --no-pmx --name="myNameDB" -- start

it start a new project ; so I can't access to strapi with all my records.
What can I do?

**Steps to reproduce the problem**
The content of my website was down

**What is the expected behavior?**
My site can perform the content filled in the database

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@Vivsss please fill in the required template, after you have updated the template reply back and I can reopen this.

Thank you

**Comment by Vivsss** [comment]
@derrickmehaffy  I fill the details of my problem. Thanks for your help!

**Comment by derrickmehaffy** [comment]
Thank you!

**Comment by lauriejim** [comment]
Are you sure your database configurations are correct in your `./config/environments/production/database.json` file

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
