### ISSUE TITLE
Fetch data based on DB connection

### ISSUE THREAD

**Issue by anitricks** [strapi/strapi#3087]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Is it possible to fetch data from a specified DB connection? For example, if Strapi has 3 different connections in the production environment. Can I fetch the data from one of the 3 databases through the request parameters to strapi? Is there a quick way to implement it if there isn't option already present?
I've read through the docs and I know there are multiple connections allowed based on a model however can I fetch specific data from a DB connection?

Thanks for the help

**Comment by lauriejim** [comment]
Hello, I don't understand what you are talking about.

One model is linked to one connection so to one database.
By using strapi.connections you can access to the ORM instance you want.

**Comment by anitricks** [comment]
oh okay. Yes i wanted to dynamically fetch a different connection of a model through a fetch request. nevermind i switched to another platform. thanks for your help
