### ISSUE TITLE
Creating a project in current directory fails

### ISSUE THREAD

**Issue by mattiejas** [strapi/strapi#3089]
**Informations**
- **Node.js version**: 11.8
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: SQlite
- **Operating system**: macOS
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When creating a new project in the current directory the name of the project is "." 

Also it crashes when trying to run. 

```sh
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/strapi/node_modules
npm WARN Invalid name: "."
```

**Steps to reproduce the problem**
```sh
  mkdir cms
  cd cms
  strapi new .
```

**What is the expected behavior?**
A project with the name "cms".

**Suggested solutions**
Look up the name of the directory and use that.

**Comment by soupette** [comment]
Instead of creating the directory yourself you should run the following command:

```
strapi new cms
```

**Comment by carl-parrish** [comment]
was this ever resolved? I can think of many reasons why you may want to use an already created directory.
