### ISSUE TITLE
Is-there a way that the Models could have some translation attributes?

### ISSUE THREAD

**Issue by alfirin** [strapi/strapi#309]
Is-there a way that the Models could have some translation attributes?

Example: I want a Model with a translated name.
Something like:
```json
{
    name: {"fr_FR": "Mon nom est Tom", "en_US": "My name is Tom"}
}
```

And when I query this Model with:
- a Query param `locale=en_US` or 
- a Cookie: with a locale field in the cookie `locale=en\-US;` or 
- a Header: `Accept-Language` header with the value `en_US`

I will get the Model with the name setted for this translation.
Something like this for the GET:
```json
{
    name: "My name is Tom"
}
```

Thanks a lot for your answer !!

**Comment by Aurelsicoko** [comment]
@alfirin Not yet! You can only have [static translations](https://strapi.io/documentation/guides/i18n.html) for the time being. In your case, you will need an i18n plugin that will allow you to add entries in different languages. I can't give you a date or a quick solution for your issue...

**Comment by alfirin** [comment]
@Aurelsicoko Thanks for the reply.

Do you have some plugin examples showing some translated data ?

Thanks for your help

**Comment by Aurelsicoko** [comment]
@alfirin No, but we have an [example app](https://github.com/strapi/strapi-examples/tree/master/hello-world) using the native i18n feature. I hope it will help you :)

**Comment by krestaino** [comment]
@Aurelsicoko Is this a planned feature?

**Comment by derrickmehaffy** [comment]
@krestaino this is a really old issue, but you can take a look here: http://strapi.io/vote 

```
Plugin - Content Internalization
Translate the content of your API in any language, from the admin panel.
```

There is a vote for it, if you want to support it, login with github and vote for it. The Strapi team places a priority on features with the most votes.

**Comment by maru3l** [comment]
Can we contribute for this feature? I'm a full stack web developer from Canada and almost all my project need to be bilingual. It's why this feature is really important for me. I will be trill to help the team to make this feature append.
