### ISSUE TITLE
Close Issue Bounty Program

### ISSUE THREAD

**Issue by MatheusRV** [strapi/strapi#3092]
Amazing terms only open issue 150, but I believe we can more. I want to collaborate with the project even more, today I became a contributor in opencollective and I want to start a reward program to close issues.

I thought about using BountySource by selecting the main issues.

What do you think about it?

**Comment by derrickmehaffy** [comment]
@MatheusRV probably best to discuss this on slack via github issues. Marking as closed as this is not a bug report or a feature request.
