### ISSUE TITLE
Enable timestamps option as default in the User & Permissions plugin

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#3093]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Enable timestamps option as default in the User & Permissions plugin:

```
  "options": {
    "timestamps": true
  },
```

**Comment by Aurelsicoko** [comment]
Sure, let's do it! @abdonrd can you create PR for this?

**Comment by abdonrd** [comment]
@Aurelsicoko done! #3119

**Comment by lauriejim** [comment]
We will add this option in the `beta`
