### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#3096]
**Informations**
- **Node.js version**: v11.3.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mlab
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Hello,

This is not a bug of strapi but I was wondering if the issue I'm having is related to strapi.

I'm trying to send a request to an api from a controller of graphql:

```
findOne: async (ctx) => {
    let url = "https://pci.zcredit.co.il/WebControl/RequestToken.aspx";
    try {
      request.post({url: url, agentOptions: {secureProtocol: "TLSv1_2_method"}, form: { 
        TerminalNumber: "0882012546",
       }}, function(err,response,body){
        console.log(err,response);
       })
       
    } catch (err) {
      console.log(err);
    }
```

But I'm getting the error:
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1159:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  code: 'ECONNRESET',
  path: null,
  host: 'pci.zcredit.co.il',
  port: 443,
  localAddress: undefined

Someone told me that I need to force tls 1.2 connection so I added it into my code in agentOptions but still getting the same error. Is it somehow related to strapi?

Thanks a lot in advance!

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by alexandrebodin** [comment]
Hi, 
Sorry but I cannot help you with that. You will have to check the documentation of the API your are requesting maybe you will get some infos for there.

Closing this as it's not related to strapi
