### ISSUE TITLE
Set timezone for CRON functions

### ISSUE THREAD

**Issue by remidej** [strapi/strapi#3099]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Set a timezone for CRON jobs. The CRON settings currently look like this in `server.json` :
```json
"cron": {
    "enabled": true
}
````

A timezone entry could probably be added, something like this: `timezone: "Europe/Paris"`.

**Comment by derrickmehaffy** [comment]
@remi2j I could be wrong but it's based off the system time, just change your server timezone.

**Comment by remi2j** [comment]
@derrickmehaffy I tried that, it didn't work. I think that's how node-cron works, but Strapi uses node-scheduler.

**Comment by derrickmehaffy** [comment]
@remi2j Yes from the looks of it, it doesn't support timezones yet. Though that comment you linked to looks like it could be handled in line. :man_shrugging:

**Comment by remi2j** [comment]
I've gone a bit deeper and found out `node-schedule` is using the `cron-parser` package, which has documented timezones support [in its readme](https://github.com/harrisiirak/cron-parser#readme)

**Comment by Aurelsicoko** [comment]
@remi2j You might be opened to change the package used if there is a better one available on npm. I'm okay to add this kind of option even if Strapi isn't the best tool to do CRON jobs. We keep the feature because we know it can be useful but there are many cleaner ways to run CRON jobs.

**Comment by shabab477** [comment]
Can anyone look into [this](https://github.com/strapi/strapi/pull/8373)? Thanks.

**Comment by derrickmehaffy** [comment]
Was merged in https://github.com/strapi/strapi/pull/8373 marking as closed.
