### ISSUE TITLE
Integrating automated timestamps into models

### ISSUE THREAD

**Issue by w0rldart** [strapi/strapi#310]
`createdAt` and `updatedAt` are fields which rarely miss from collections of modern applications.

I suggest implementing this through a toggle parameter which when enabled, a trait would be injected in the model to implement those additional fields, and also bind to the `lifecycle` events to ensure the values are created/updated automatically.

```json
{
  "connection": "default",
  "collectionName": "",
  "timestamps": true,
  "info": {
    "name": "testimonial",
    "description": ""
  },
  "attributes": {
    "client": {
      "type": "string",
      "required": true
    },
    "position": {
      "type": "string"
    },
    "context": {
      "type": "text",
      "required": true
    }
  }
}
``` 

More examples at https://laravel.com/docs/master/eloquent#defining-models under the Timestamps sub-section

**Comment by Aurelsicoko** [comment]
You can already do that with the models that depend on `strapi-bookshelf` (SQL databases) but I guess it's missing from the documentation.

```json
{
  "connection": "default",
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
     ...
  }
}

```

**Comment by u12206050** [comment]
How do I get this working, I have added both `"hasTimestamps": [null, "updated"]` to options and ```"updated": {
      "type": "date",
      "required": true,
      "multiple": false,
      "readonly": true
    }```
to the attributes but it still doesn't automatically update the field.
