### ISSUE TITLE
Cuts the content in WYSIWYG not reflecting on saving

### ISSUE THREAD

**Issue by Thanseem007** [strapi/strapi#3101]
**Informations**
- **Node.js version**: v10.13.0
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.25.2
- **Database**: Mongo db
- **Operating system**: Windows
- **(Optional) Link to your Project**: 

**What is the current behavior?**
 In Description field , select any content and cut the content.click save button.The content is not getting removed.

**Steps to reproduce the problem**

**What is the expected behavior?**
The content should be  removed.

**Suggested solutions**

**Comment by soupette** [comment]
@Thanseem007 can you please detail a bit more your issue because we can't know which plugin/view feature you are referring to.

**Comment by Thanseem007** [comment]
It is regarding the content manager plugin.The type is text.
![content manager](https://user-images.githubusercontent.com/49393739/55773719-86de4100-5aaf-11e9-8d9b-3bbdf57a6701.PNG)

**Comment by soupette** [comment]
So basically you are saying that you cannot remove the content of the field `AlbumDescriptionEn` ?

**Comment by Thanseem007** [comment]
select a particular content , right click on mouse and remove it by cut option.After the save the content will persist there.

**Comment by indatawetrust** [comment]
editor does not consider copy paste operations

**Comment by Thanseem007** [comment]
why they cant use copy paste functionality ?If they typped in a wrong place and why cant they cut and paste in other field ?
