### ISSUE TITLE
Anyone managed to get graphql createUser and updateUser to work

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#3104]
**Informations**
- **Node.js version**: 10.1.0
- **NPM version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.25.2
- **Database**:  mongodb v4.0.0
- **Operating system**:  Ubuntu 1404 (via vagrant vbox)
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I have a nuxt app where I want users to register themselves and update their profile.

1. I have tried ‘axios’. Although it works, I do  not like the ‘axios’ option because it does not return the specific strapi error. For example, if the username or email is already taken all I get is a 400 error. Not an intuitive msg to show the user.

2. I have tried ‘strapi-sdk-javascript. It works and the error msg from strapi is more intuitive. For example, if the username or email is already taken strapi says so. The issue I have with the sdk option is it only accept the username, email and password when registering a new user. I have to make another update user call to update the rest of the user profile, for example firstname, lastname etc.

3. Finally, I tried the graphql createUser and updateUser, via my app and also via the graphql playground. both of them does not work. I keep getting a 

> "message": "Bad Request",
> "data": "values.hasOwnProperty is not a function",

_**However, I can create and update other models via the graphql playground and via my app but it stubbornly refuse to work for the user model**_

**Steps to reproduce the problem**
Try to createUser or updateUser via the graphql playground

**What is the expected behavior?**
I should be able to create and update user using graphql

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
please please please use code blocks @laportem or just a screenshot

**Comment by laportem** [comment]
oops - my bad -- here is a screenshot

![image](https://user-images.githubusercontent.com/2515109/55784078-b426f100-5aa7-11e9-872a-6305170da0aa.png)

**Comment by derrickmehaffy** [comment]
(Can you edit your OP and remove the wall-o-text, please and thank you)

**Comment by lauriejim** [comment]
Hello !

Since we work on deep filtering, this issue is fixed on master, will be release at the beginning of next week.
