### ISSUE TITLE
Add an option to disable the "help" videos and the icon completely

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3105]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Briefly mentioned this to @soupette but I think there should be an option to disable the help videos (doesn't need to remove them) along with the little (?) icon in the lower right (debatable as to if that is even a good place for it)

I find it extremely rare that someone who has been using Strapi for a nice length of time to ever need them and the icon is in a very annoying place. It is great for new users don't get me wrong, but after a week of using Strapi it is effectively pointless and mildly annoying.

**Comment by soupette** [comment]
I agree the only question is where should we put this configuration.

**Comment by derrickmehaffy** [comment]
@soupette It isn't something that is subject to change often or in production, I would say it should be a hard coded config file. Maybe add a `settings.json` file in $root/config ? Somewhere that you can set global settings across all environments?

**Comment by derrickmehaffy** [comment]
@Aurelsicoko your thoughts?

**Comment by Aurelsicoko** [comment]
It's something that should be enabled/disabled without restarting the server. For example, I'm pretty sure a new administrator would like to have these help videos. 

For now, it could be a configuration saved in the core store but in the future, it might be associated with a specific administrator setting. We have a global setting section in the "Configurations" section, how easy is it to add that kind of configuration @soupette?

![image](https://user-images.githubusercontent.com/4144726/56039580-dc774f80-5d34-11e9-9e79-f9195f48d2d3.png)

**Comment by derrickmehaffy** [comment]
@Aurelsicoko as useful as that is, again we play into tracking this via source control. :P I still think a file based override then if you also want database level with the file based setting taking priority.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy I know that you want that file override system but we won't add it in a near future 🙈

I'm waiting for the @soupette's answer to take a final decision for this issue :p

**Comment by derrickmehaffy** [comment]
@Aurelsicoko your killing me with all these settings being stored in the database, it really can make deployments hard especially for teams that work locally on their own machine for development.

I find it highly unlikely that this setting is going to be changed on a production machine enough that it warrants storing it in the database. Either that or it should be a user based setting at the minimum.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy There will have no issues if we provide the right tools and workflow to easily migrate settings across databases.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy There will have no issues if we provide the right tools and workflow to easily migrate settings across databases.

My question is what benefit do users get by tracking this setting in the database over something that can easily be tracked and not need migrated if stored in a file.

I really hate to be beat around the bush here but a simple config.json file in the config directory for many of these environment independent and global settings would be far easier, and provide easy source control so that a users environment is **exactly** how they want it every time without needing to do any database migrations between them.

Sure things like the content builder fine, it makes sense that there would be some common things that need to be changed in production but Strapi is not wordpress, it is not drupal, it is not a normal CMS and shouldn't be treated like one. Just because product x, y, and z are doing it this way doesn't mean it is right.

Strapi is middleware, that is what a headless CMS is designed and built to be, the users provide the backend (database), and the frontend. Thus you will expect changes need to happen to the "middleware" and users need to be able to track and approve these changes just like it is done here in the mono repo. PR, approval process, discussion, design choices, ect. All of these are possible and actively used to provide solid source control with a proper approval process. when you start storing every single little setting in a single table on the database you lose the ability to track these things.

**Comment by Aurelsicoko** [comment]
I think we could create a `configuration.json` file which could be a mirror of the settings stored in the database. So you will be able to track all the changes, and maybe enable a mode to load this file during the start as the single source of truth concerning the configurations, and override the configurations stored in the database by the configuration of the files.

What do you think about that? 

It means that every time a configuration is updated via the interface and in databases, the files is edited as well on the server. It will work like a mirror (a static representation of the database). It could also be used to seed configurations to the database. Even if the file is large, we don't core because the only goal is to be able to follow the changes using Git or SVN.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko as discussed with others I think this is a fine idea along with having the option to force overwriting the core store on boot (as an override).

To me this sounds like a fine compromise for now, though personally on this specific option I think the option to hard code this makes more sense.

**Comment by SeedyROM** [comment]
> @Aurelsicoko your killing me with all these settings being stored in the database, it really can make deployments hard especially for teams that work locally on their own machine for development.
> 
> I find it highly unlikely that this setting is going to be changed on a production machine enough that it warrants storing it in the database. Either that or it should be a user based setting at the minimum.

100% agreed, the decision to store all of this stuff in the database and then simply *not* have the tooling required to make this manageable is a head-ache for no reason.

**Comment by soupette** [comment]
It has been added in #3633
