### ISSUE TITLE
Media field type not populating

### ISSUE THREAD

**Issue by Perttimv** [strapi/strapi#3107]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: Microsoft Azure Cosmos Emulator (Mongo hook)
- **Operating system**: Windows 10 Pro

**What is the current behavior?**
I have a Media field in a content type with several other field types. When I create new document of that content type, the file (image) is uploaded and added to upload_file collection correctly. When I start to edit the created document, the reference to the uploaded image is not populated. The issue can be repeated with the content type API-call.

**Steps to reproduce the problem**
Create content type with string field and media field. Create new document of new content type. Fill in the string field and add a media file and save the document. Open the document for editing.

**What is the expected behavior?**
The media file added to the document would be shown in the edit mode. It should also be populated to the content type API call.

**Notes**
There seems to be similar issues already but they seem to be referring to nested content types.

**Comment by lauriejim** [comment]
Hello!

Can you try with a local installation of Strapi (by following the CONTRIBUTING guide)
Normally it's fixed on master but I would like to be sure for your case it's OK.

Can you test with a fresh new app created from `master` please.

**Comment by soonzhi** [comment]
setting this in one of my models
  "mediaFile": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }

when i do deep populate from the parent:
const populate = ['sections','sections.contents','sections.contents.mediaFile','sections.contents.components','sections.contents.components.hasComponents']
    return Division.forge(_.pick(params, 'tag')).fetch({
      withRelated: populate
    });

However, mediaFile is not shown in the return result

**Comment by lauriejim** [comment]
Please can you format your message, it's not readable.
I read hundred issues per day, help to make my day better please.

In the last version of Strapi we auto populate media files data.
If you custom your populate to get more deep relation, you will have to add `.upload_file` to your media attribute `sections.contents.mediaFile.upload_file` to get the data.
