### ISSUE TITLE
Indentation settings

### ISSUE THREAD

**Issue by w0rldart** [strapi/strapi#311]
Whilst I wish you'd use 4 spaces indentation by default across your project, I do respect your choice and can only suggest to do so for a more common standard and what I believe, easier to read.

However, my question here is whether we can at least have an option for 2 of 4 spaces in the generated templates?

**Comment by Aurelsicoko** [comment]
Thanks, @w0rldart for this proposition. However, we don't plan to offer this feature. One of our goals is to make choices and we already did make it for Strapi in the indentation case. The lower the number of configurations is, the easier is to use the product. And we want to keep Strapi the most simple as possible.
