### ISSUE TITLE
Reserved keyword as field name breaks search on MySQL

### ISSUE THREAD

**Issue by mikelerch** [strapi/strapi#3112]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MySQL (Most likely affects other databases too)
- **Operating system**: Ubuntu 18.04.2 LTS (Bionic Beaver)

**What is the current behavior?**
I have a content type with a field called `key`. When I select that content type from the menu and start searching for an entry, I get an error message saying `An error occured`.

After checking the logs, the query that is being executed is the following
```sql
select count(*) as `count` from `some_table` where MATCH(key,some_column,another_column) AGAINST('*a*' IN BOOLEAN MODE);
```
**Steps to reproduce the problem**
See above. Create a content type with a field called `key` and search for entries in it.

**What is the expected behavior?**
The search functionality should work as usual, regardless of what a field is called.

**Suggested solutions**
The query should be
```sql
select count(*) as `count` from `some_table` where MATCH(`key`,some_column,another_column) AGAINST('*a*' IN BOOLEAN MODE);
```

The column name `key` should be surrounded by two backticks. The same is expected for any other reserved keywords in MySQL.

**Comment by lauriejim** [comment]
Since the search has been reviewed - this issue is fixed in beta.
