### ISSUE TITLE
Mailgun email provider not visible in Production Mode

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#3113]
**Informations**
- **Node.js version**:  10.15.1
- **NPM version**:   6.9.0
- **Strapi version**:   v3.0.0-alpha-25.2
- **Database**:  Mongo DB
- **Operating system**:  Ubuntu
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Provider mailgun is not showing in email plugin settings.

**Steps to reproduce the problem**
Installed the npm module from this page : https://www.npmjs.com/package/strapi-provider-email-mailgun and then restarted server but plugin not shown but showing in Dev mode.

**What is the expected behavior?**
It should be visible in Production mode too.

**Suggested solutions**

**Comment by lauriejim** [comment]
I just tried an all work well.
What is the command you use to install this provider ?
When you speak about `Dev` mode, it's because you are note starting strapi with `NODE_ENV=production` ?
In `Dev` you see the provider in `developement` tab and `production` tab ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.

**Comment by renyuanz** [comment]
Hi @lauriejim I just had the same issue. I used `npm install strapi-provider-email-sendgrid@alpha --save` to install the plugin, and I can see it in `development` mode in both `development` and `production` tab.
But in production mode, I can only see `sendmail` option in `production` tab without `Sendmail Default From` and `Sendmail Default Reply-To` inputs.
I tried to copy paste my dev `plugin_email_provider` key from my db (MySQL) to my production db, but seems not working neither.

Can you reopen this ticket plz? Thanks in advance.

**Comment by derrickmehaffy** [comment]
Reopening as the user provider more information

**Comment by lauriejim** [comment]
This issue is fixed in last beta version (beta.15)
