### ISSUE TITLE
Error executing DELETE MySQL

### ISSUE THREAD

**Issue by junioreuripedes** [strapi/strapi#3117]
**What is the current behavior?**
Executando o metodo DELETE esta aparecendo erro com a coluna "id" que não existe no MySQL.

In MySQL the column "id" is represented by the column "CO_VENDA_MESA".

The Strapi (version v3.0.0-alpha.25.2) by what I understood is trying to consult this column id that does not exist not my base, this made all the changes to change that column as I found in the documentation.

**Informations**
- **Node.js version**: v11.12.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MySQL client 5.0.11
Tipo de servidor: MariaDB
Versão do servidor: 10.1.30-MariaDB - Source distribution
OS: MacBook

**Steps to reproduce the problem**
> [2019-04-11T13:56:21.138Z] debug GET /mesas (73 ms)
> Error: Undefined binding(s) detected when compiling SELECT query: select tb_venda_mesa.* from tb_venda_mesa where tb_venda_mesa.id = ? limit ?
> at QueryCompiler_MySQL.toSQL (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/query/compiler.js:85:13)
> at Builder.toSQL (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/query/builder.js:72:44)
> at /Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/runner.js:37:34
> From previous event:
> at Runner.run (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/runner.js:33:30)
> at Builder.Target.then (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/interface.js:23:43)
> at processImmediate (timers.js:638:19)
> at process.topLevelDomainCallback (domain.js:136:23)
> [2019-04-11T13:56:29.089Z] debug DELETE /mesas/15 (10 ms)

**What is the expected behavior?**
**[Archive Mesa.settings.json]**

> {
> "connection": "teste",
> "collectionName": "tb_venda_mesa",
> "info": {
> "name": "mesa",
> "description": "Tabela de Venda Mesa."
> },
> "options": {
> "increments": true,
> "timestamps": false,
> "comment": "",
> "idAttribute": "CO_VENDA_MESA",
> "idAttributeType": "integer"
> },
> "attributes": {
> "CO_VENDA_MESA": {
> "default": "",
> "unique": true,
> "type": "integer",
> "required": true
> },
> "DT_CADAS": {
> "default": "",
> "type": "date",
> "required": true
> },
> "NU_MESA": {
> "default": "",
> "maxLength": 20,
> "unique": true,
> "type": "string",
> "required": true
> },
> "ST_MESA": {
> "default": "",
> "maxLength": 1,
> "type": "string",
> "required": true
> }
> }
> }

**[Archive routes.json]**

> {
> "routes": [
> {
> "method": "GET",
> "path": "/mesas",
> "handler": "Mesa.find",
> "config": {
> "policies": []
> }
> },
> {
> "method": "GET",
> "path": "/mesas/count",
> "handler": "Mesa.count",
> "config": {
> "policies": []
> }
> },
> {
> "method": "GET",
> "path": "/mesas/:CO_VENDA_MESA",
> "handler": "Mesa.findOne",
> "config": {
> "policies": []
> }
> },
> {
> "method": "POST",
> "path": "/mesas",
> "handler": "Mesa.create",
> "config": {
> "policies": []
> }
> },
> {
> "method": "PUT",
> "path": "/mesas/:CO_VENDA_MESA",
> "handler": "Mesa.update",
> "config": {
> "policies": []
> }
> },
> {
> "method": "DELETE",
> "path": "/mesas/:CO_VENDA_MESA",
> "handler": "Mesa.destroy",
> "config": {
> "policies": []
> }
> }
> ]
> }

**Comment by derrickmehaffy** [comment]
Please follow the bug report template, marking as closed. Once you have updated your original post with the template, reply back and this can be reopened.

**Comment by junioreuripedes** [comment]
Atualização para modelo de bug efetuada. Favor desbloquear.

**Comment by derrickmehaffy** [comment]
> You are missing the required information on versions. Also I do not actually speak portuguese, and we typically require english usage on this Github. Please also use code blocks instead of quotes.
> 
> Please see the following template:


Você está perdendo as informações necessárias nas versões. Também não falo português, e normalmente exigimos o uso do inglês neste Github. Por favor, use também blocos de código em vez de citações.

Por favor, veja o seguinte modelo:

```
<!-- ⚠️ If you do not respect this template your issue will be closed. -->

<!-- =============================================================================== -->
<!-- ⚠️ If you are not using the current Strapi release, you will be asked to update. -->
<!-- Please see the wiki for guides on upgrading to the latest release. -->
<!-- =============================================================================== -->

<!-- ⚠️ Make sure to browse the opened and closed issues before submitting your issue. -->

<!-- ⚠️ Before writing your issue make sure you are using:-->
<!-- Node 10.x.x -->
<!-- npm 6.x.x -->
<!-- The latest version of Strapi. -->

**Informations**
- **Node.js version**: <!-- Please ensure you are using the Node LTS version (v10) -->
- **NPM version**: 
- **Strapi version**: <!-- Please make sure you are on the latest version -->
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: <!-- To speedup support, if you have your project on github/gitlab you can provide a link -->


**What is the current behavior?**



**Steps to reproduce the problem**



**What is the expected behavior?**



**Suggested solutions**
```

**Comment by junioreuripedes** [comment]
I added the version information.

**Comment by derrickmehaffy** [comment]
Much better, thank you @junioreuripedes reopened :smile:

**Comment by lauriejim** [comment]
Sorry but it's not @derrickmehaffy.

Can you write clear steps with boulet points.
use ` symbole for your logs.
And write your message in english please.

I read hundred issue per day, we want to keep this GitHub clean for the community.
Hope you understand that.
