### ISSUE TITLE
Can't opt to recur through relations and get the full objects

### ISSUE THREAD

**Issue by vanpana** [strapi/strapi#3128]
**Informations**
- **Node.js version**: 10.11
- **NPM version**: 6.8
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: mongo
- **Operating system**: macos 

**What is the current behavior?**
When GETting an object, only the first level relations will be fetched. The second level relations will only display the ID.

**Steps to reproduce the problem**
- Create Object1, Object2 and Object3.
- Make relation between Object1 - Object2 and Object2 - Object3.
- Create one entity of Object3, one entity of Object2 and link the Object3 entity and one entity of Object1 and link the Object2 entity.
- Fetch Object1 by id.
Observe that Object2 entity will be all displayed, but Object3 will only display the id.

**What is the expected behavior?**
Have a switch to recur through all the relations

**Comment by derrickmehaffy** [comment]
@vanpana this is not a bug, see this article to customize the REST response or use the GraphQL plugin.

http://help.strapi.io/customize/custom-populate-data-rest-api
