### ISSUE TITLE
Multiple files are not added properly when two file fields are configured in the same model

### ISSUE THREAD

**Issue by cthulu** [strapi/strapi#3130]
**Informations**
- **Node.js version**: v10.0.0.
- **NPM version**: v6.9.0
- **Strapi version**: Strapi v3.0.0-alpha.26
- **Database**: sqlite
- **Operating system**: MacOS 10.14.5

**What is the current behavior?**
When I am using the cloudinary upload provider and add multiple images in a model where the "asset" field supports multiple files, I can see them correctly uploaded to Cloudinary but only one asset is linked to the entry. I can see the files in the the "Files Upload" menu though.
No errors are displayed in the console. When I try to add more files in the 'edit' it only adds one file again.
This works only the first time if I'm using the "local upload" provider. After adding more files to an existing content type it does not work 

**Steps to reproduce the problem**
1. Install cloudinary provider

       cd plugins/upload
       npm i --save strapi-provider-upload-cloudinary

1. configure it
1. Create a "Post" content type with a 2 types of media fields ("cover" with a single value, and "gallery" with multiple values)
1. Create an entry and add multiple files (gallery) and a single file (cover)
1. After saving see that it is all updated in cloudinary but incorrectly in the UI or in the model (graphql)

**What is the expected behavior?**
Multiple files are correctly linked to a "post" entity.

**Suggested solutions**
Not sure, no errors in console.
I think it's a UI problem as I can reproduce it to local upload provider as well.

**Comment by cthulu** [comment]
Btw I've also tried upping the plugin `npm i --save strapi-provider-upload-cloudinary@alpha` but got the same behavior.

**Comment by cthulu** [comment]
Interestingly, using Postgres instead of Sqlite provider seem to have no problems with cloudinary and multiple files.

**Comment by cthulu** [comment]
I've tested in the new alpha v3.0.0-alpha.26, same problem.

**Comment by lauriejim** [comment]
Hello! Thank you for your feedback.

Your issue is related to the Cloudinary provider ? It works well with default local provider ?

I tried to reproduce with local provider and it works well.

**Comment by jayakusumah** [comment]
same issue with imagekit provider

**Comment by har17bar** [comment]
helppp  please same issue

**Comment by jayakusumah** [comment]
> helppp please same issue

fixed with manual install
do not use strapi new cms --quickstart

use strapi new cms

set default database. ex: mongo

**Comment by har17bar** [comment]
@jayakusumah thnx for reply, on server when i save to localy its work fine but when use cloudinary dont working to me .. my default database is PostgreSQL

**Comment by har17bar** [comment]
@cthulu i switch  from using 2 different image fields in the model to one field it dont help

**Comment by lauriejim** [comment]
This look been fixed in beta version of strapi  - haven't been able to reproduce.

**Comment by TasTing** [comment]
same issue. 
I have two medias in a model. one is allowed for single upload and other is allowed for multiple upload.

when I use strapi backend to upload multiple files. It successfully uploaded to my cloudinary but failed to link them to the media field. the multiple media field only shows the last uploaded file.
