### ISSUE TITLE
Add a formula field

### ISSUE THREAD

**Issue by dufoli** [strapi/strapi#3131]
It is quite a standard feature on many CRM (saleforce, neolane,...).
It can be very flexible and useful for many things.
A formula field store a formula on metadata but nothing is stored in DB.
The formula is based on record fields and is calculated on the fly when api query this field.
potential use case:
with function:
- dateonly(mydate)
- urlized(myTitle)
-DaysAgo(myDate)
-If(IsClosed;'Closed', 'Open')
or just operations:
- TotalWithTaxes = TotalHt * VAT
- Cost = Price + shippingFee
- Surface = width * Height

**Comment by Aurelsicoko** [comment]
Yes, yes and yes! I've added it to the public roadmap, it could be awesome to have this new type of field available.

https://portal.productboard.com/strapi/c/58-formula-field

Please upvote the card and give me your insights, I close the issue.

**Comment by dufoli** [comment]
For that, you will need a little language with formula editor and a list of function. You can take look to salesforce editor here:
https://trailhead.salesforce.com/en/content/learn/modules/point_click_business_logic/formula_fields

**Comment by mik3lov3st3ch** [comment]
Directus uses some kind of "in-field templating" e.g. for the content of a dropdown like:
{{brand.name}} {{title}}

**Comment by TeoGoddet** [comment]
Could/Should I write an RFC for this ? 

This parser look really great : https://github.com/handsontable/formula-parser
 it can handle variable name (unfortunately without . and [] inside) and call a function to resolve variable names (giving us the opportunity to provide the value from the object or do the required queries to find it)

Main Tradeoff seems to be about performance and the fact that a generic solution would run on each record in strapi 
A more efficient solution but a lot harder would be to delegate some work to the ORM and DB
if querying 100 of ObjectA.child1.property1, the difference is clear :  1 db request at ORM level but 100 at strapi level

Another point of attention is the validation of user pseudo code input and the error handling

Maybe I have some time to do the backend work in february.
