### ISSUE TITLE
Content type not showing fields for creating a new content

### ISSUE THREAD

**Issue by Otavioensa** [strapi/strapi#3133]
**Informations**
- **Node.js version**: 10.0.0
- **NPM version**:  5.6.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: PostgreSQL
- **Operating system**: Heroku (IDK the OS)

**What is the current behavior?**
Hi folks, I've created a Content Type called `User` at development environment and then deployed my application to a Heroku app. For some reason, when I click at `Users` on the Content Type section and I click for adding a new user it won't load the fields so I can fill and submit it. This issue happens only in `production` and works fine in development environment. What could I possibly be missing?

**Steps to reproduce the problem**

1) Click at `Add New User` blue button at top right

![image](https://user-images.githubusercontent.com/7586857/56106436-844c7300-5f17-11e9-9ec3-aa77d48cafff.png)

2) It then loads ad infinitum and never shows me the fields for creating my User
![image](https://user-images.githubusercontent.com/7586857/56106482-b4941180-5f17-11e9-8bb3-a5db4dda2d96.png)

**What is the expected behavior?*

Showing the user fields so I can register an user (just like at development environment):
![image](https://user-images.githubusercontent.com/7586857/56106539-0b99e680-5f18-11e9-9793-b8e00ae15c42.png)
 

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
@Otavioensa I would very highly suggest **not** duplicating content-types like that. Strapi typically requires you to create the model in the "singular" format and it converts it to the plural form when needed, meaning you are basically fighting the `User-permissions` plugin by having two models that are effectively the same but with different fields.

This is not classified as a bug due to the similarity to an existing plugin model that is causing the problem.

**Comment by Otavioensa** [comment]
Sorry, I've described the issue in a wrong way, it was late night so I got confused when writing the issue and  changed the word `Posts`(the correct one) to `Users` (incorrect). The content type I actually created was `Posts`. I've just updated the issue description. 
Sorry for the confusion, I went till late night trying to figure what was happening with my `Posts` content type 😅  
Could you reopen again, @derrickmehaffy  ?

**Comment by lauriejim** [comment]
Hello, I suggest you to go to the `Content Manager` link in the left menu and then to update the Content Type you want.
You will be able to customise inputs to display in the Edit View.

**Comment by Otavioensa** [comment]
Hi @lauriejim 
I've setup a new project and deploy again. It worked so I guess I won't figure exactly what I was doing wrongly 😅

**Comment by Otavioensa** [comment]
Hi @lauriejim
I've ended up setting a new project and deploying it again. It worked so I guess I won't figure exactly what I was doing wrongly 😅
Thanks for your suggestion

**Comment by radiegtya** [comment]
I've experienced the same, please reopen

**Comment by lauriejim** [comment]
Was it in the alpha or beta ?

**Comment by MuhammedAsaad** [comment]
Same here.
