### ISSUE TITLE
Local policy on non singular query in custom graphql schema is not working

### ISSUE THREAD

**Issue by rmaroun** [strapi/strapi#3134]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha25.2
- **Database**: Mongo DB
- **Operating system**: Mac OSX mojave

**What is the current behavior?**

I have created a custom graphql schema for one of my content types. This custom graphql schema contains a singular query override and a plural query override (e.g. contact and contacts). Overriding the contact query is working fine with a plugin policy combined with a local policy. For the contacts query, i added a plugin policy and all works fine but when i add a local policy i am getting the following error message: `error Ignored attempt to bind to GraphQL query "contacts" with unknown policy "getOnlyManagedContacts"`. When I move the policy to a plugin or at global level and then update it in the graphql schema for the contacts query then it is working.

**Steps to reproduce the problem**

1. create a new content type
2. add a local policy in /api/myContentType/config/policies
3. create a custom graphql schema in /api/myContentType/config
4. assign the local policy to the myContentTypes graphql query as follow:

```
module.exports = {
  resolver: {
    Query: {
      myContentType: {
        description: 'Returns the exact myContentType',
        policies: ['plugins.users-permissions.permissions', 'isOwnerOfMyContentType'],
        resolver: 'MyContentType.findOne'
      },
      myContentTypes: {
        description: 'Returns a list of myContentTypes',
        policies: ['plugins.users-permissions.permissions', 'onlyGetManagedMyContentType'],
        resolver: 'MyContentType.find'
      },
    }
  }
};
```

**What is the expected behavior?**

the expected behavior is when restarting the server then no error message binding the myContentTypes graphql query to onlyGetManagedMyContentType local policy is displayed and that the local policy is applied to the non singular query

**Suggested solutions**

**Comment by lauriejim** [comment]
Thank you for this report!
We are currently on other topics, we will appreciate if you can take time to investigate on this issue.

**Comment by rmaroun** [comment]
Workaround for now: is a global policy.

**Comment by alexandrebodin** [comment]
Hi @rmaroun can you check if you still are having this issue ? 

This is supposed to be fixed in beta.19

**Comment by ralphsomeday** [comment]
Fixed!

**Comment by alexandrebodin** [comment]
Great :D Closing this PR
