### ISSUE TITLE
Can't update due to date field

### ISSUE THREAD

**Issue by jaime8111** [strapi/strapi#3135]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: 5.7.17 MySQL Community Server 
- **Operating system**: Mac Mojave

**What is the current behavior?**

If i have a content type with a date field, I can't edit it from the admin panel after create it.

**Steps to reproduce the problem**

I'd create a post content type. One of its fields is the publish_date (type: date).

I create a new post, everything works great. Then I go to that post again, **to edit it**, and when i try to save it **i get this error**:

```
update `posts` set `draft` = false, `slug` = 'first', `title` = 'first', `content` = '# My content', `id` = 1, `publish_date` = '2019-04-14T00:00:00.000Z', `updated_at` = '2019-04-15 07:59:12.708' where `id` = 1 

- ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2019-04-14T00:00:00.000Z' for column 'publish_date' at row 1
```

**What is the expected behavior?**

Be able to edit a record as many times as I want

**Suggested solutions**

Reformat the date string to match the expected data base format

**Comment by derrickmehaffy** [comment]
duplicate: 

https://github.com/strapi/strapi/issues/3036
https://github.com/strapi/strapi/issues/2663
