### ISSUE TITLE
Add region for Amazon SES email provider

### ISSUE THREAD

**Issue by Blacknosaur** [strapi/strapi#3136]
**Informations**
- **Node.js version**: v11.6
- **NPM version**: v6.5
- **Strapi version**: Alpha 25.2 (the problem is in strapi-provider-email-amazon-ses)
- **Database**: MongoDB 3.6.3
- **Operating system**: Amazon Linux AMI release 2017.09

**What is the current behavior?**
When setting up Amazon SES you haven't the possibility to select AWS region and it defaults to US East. If this is your case it will work, but if not it fails with an error 400 with an incorrect error message "auth.form.error.email.invalid"

**Steps to reproduce the problem**
Just install strapi ses plugin and configure it with an AWS account which doesn't belong to us-east-2

**Suggested solutions**
Adding a line in strapi-provider-email-amazon-ses/lib/index.js fixes the problem.
```   
 var client = nodeSES.createClient({
      key: config.amazon_ses_api_key,
      secret: config.amazon_ses_secret,
      amazon: "https://email.eu-west-1.amazonaws.com"
});
```
The "amazon" field should depend on a variable selectable from the config page of the email plugin

**Comment by derrickmehaffy** [comment]
@Blacknosaur Feel free to submit a PR, looks like you are right the part of the code is here:

https://github.com/strapi/strapi/blob/0e86e1b130bf040e886e8df8bc7063eff29d9af6/packages/strapi-provider-email-amazon-ses/lib/index.js#L38-L41

**Comment by Achder** [comment]
I have never done a PR, but this fixes the issue for me (adds amazon_ses_region and uses it in createClient):
```
'use strict';

/**
 * Module dependencies
 */

/* eslint-disable import/no-unresolved */
/* eslint-disable prefer-template */
// Public node modules.
const _ = require('lodash');
const nodeSES = require('node-ses');

/* eslint-disable no-unused-vars */
module.exports = {
  provider: 'amazon-ses',
  name: 'Amazon SES',
  auth: {
    amazon_ses_default_from: {
      label: 'Default From',
      type: 'text'
    },
    amazon_ses_default_replyto: {
      label: 'Default Reply-To',
      type: 'text'
    },
    amazon_ses_api_key: {
      label: 'Amazon Access key ID',
      type: 'text'
    },
    amazon_ses_secret: {
      label: 'Amazon Secret access key',
      type: 'text'
    },
    amazon_ses_region: {
      label: 'Amazon Region',
      type: 'text'
    }
  },

  init: (config) => {

    var client = nodeSES.createClient({
      key: config.amazon_ses_api_key,
      secret: config.amazon_ses_secret,
      amazon: config.amazon_ses_region
    });

    return {
      send: (options, cb) => {
        return new Promise((resolve, reject) => {
          // Default values.
          options = _.isObject(options) ? options : {};
          options.from = options.from || config.amazon_ses_default_from;
          options.replyTo = options.replyTo || config.amazon_ses_default_replyto;
          options.text = options.text || options.html;
          options.html = options.html || options.text;

          let msg = {
            from: options.from,
            to: options.to,
            replyTo: options.replyTo,
            subject: options.subject,
            altText: options.text,
            message: options.html
          };

          client.sendEmail(msg, function (err) {
            if (err) {
              console.log(err.Message);
              reject([{ messages: [{ id: 'Auth.form.error.email.invalid' }] }]);
            } else {
              resolve();
            }
          });
        });
      }
    };
  }
};
```

**Comment by derrickmehaffy** [comment]
@Blacknosaur Now is a good time to learn :P 

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
