### ISSUE TITLE
Unhandled promise rejection TypeError: "n.models is null"

### ISSUE THREAD

**Issue by FikriRNurhidayat** [strapi/strapi#3137]
**Informations**
- **Node.js version**: v11.11.0
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**:  Postgresql
- **Operating system**: Alphine

**What is the current behavior?**
Unhandled promise rejection TypeError: "n.models is null" is occured when I try to get my admin page, and there's no models loaded there. Something made that thing funnier, because it happened on my staging env, my local fine. So, a weeks ago I deployed my API to staging, it works fine, and there was no deploy activity, but Last Satuday, this 
Unhandled promise rejection TypeError: "n.models is null" happened, and I didn't fix it. After that, that errors had been fixed by magics, because I didn't do anything to do it.
As @lauriejim 

"lauriejim commented on Jun 12, 2018

So it happen randomly... Can you guys try with the last version of Strapi, fresh new app and fresh new database. Tell me if it still happen please."

And it fixed randomly. But now, it happened again.

**Steps to reproduce the problem**
I try to update my strapi version. Since I was using docker, so it must be fresh install on the Server.

**What is the expected behavior?**
Strapi show me all the models again.

**Suggested solutions**
What if, we have full control on Strapi project that we create, so we know exactly what's going on there. And also create some migration file.

**Comment by lauriejim** [comment]
Can you share the full error log please. And an admin page screen/

**Comment by derrickmehaffy** [comment]
@lauriejim @FikriRNurhidayat likely related, similar issue: https://github.com/strapi/strapi/issues/3123

More than likely missing something in the database.json, field or model name has a space/symbol in it, or you just need to delete the `plugin-content_manager-schema` entry in your `core_store` table/collection

**Comment by lauriejim** [comment]
Ho yes! An other issue is already open about this topic.
