### ISSUE TITLE
Server suddenly fails to start again

### ISSUE THREAD

**Issue by alliuca** [strapi/strapi#314]
Not sure what happened but at some point the strapi process errored out and on subsequent `strapi start` would just throw this error:

```
DEBUG (12407 on [hostname]): Server wasn't able to start properly.
ERROR (12407 on [hostname]): Cannot convert undefined or null to object
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at Strapi.module.exports.app (/usr/local/lib/node_modules/strapi/lib/core/configurations.js:81:45)
        at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:174:29)
        at <anonymous>
```

I did try to change `strapi.config.locales` to `strapi.config.functions.locales` both in that conversions.js file and in /lib/middlewares/language/index.js and now seems to work fine again.
I should note that none of this happened on first start after I generated a new project.

**Node.js version**: 8.6.0
**npm version**: 5.3.0
**Strapi version**: 3.0.0-alpha.6.4
**Operating system**: macOS Sierra v10.12.6

**Comment by lauriejim** [comment]
I don't really understand changes you did to have this issue. Can you explain more precisely what you did?
