### ISSUE TITLE
Deep Filtering in alpha.26, not working as expected

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3143]
https://github.com/strapi/strapi/pull/2452#issuecomment-451987575

I've updated to `alpha.26` and it seems the issue is alive again.

I must note i've tried both, the original comment query:

```
  query {
    users(where: { email_contains: "@mydomain.com", avatar: {url_ne: null }}) {
      username
      avatar {
        url
      }
    }
  }
```

And also this one:

```
  query {
    users(where: { email_contains: "@mydomain.com", avatar_ne: null }) {
      username
      avatar {
        url
      }
    }
  }
```

Result is this:

<img width="1428" alt="Captura de Pantalla 2019-04-16 a la(s) 14 26 53" src="https://user-images.githubusercontent.com/517228/56231055-e4e0ca80-6053-11e9-93a8-5accccaf02c4.png">

I'm using MongoDB

**Comment by derrickmehaffy** [comment]
There is no null filter

**Comment by derrickmehaffy** [comment]
The deep filtering PR did not add the null filter that is still in planning.

@aurelsicoko see why I want to make that card public? Lol

**Comment by jacargentina** [comment]
@derrickmehaffy all my 🥳.... is now turned to 😔

**Comment by alexandrebodin** [comment]
@jacargentina Sorry for the disappointment :( we wanted to release the deep filtering with the current filters first and make it easier to add more later on ;)

If you want to try and make a PR to add a `_null` and `_nnull` I can give you some pointers to get you started of course !

**Comment by derrickmehaffy** [comment]
@jacargentina https://portal.productboard.com/strapi/c/57-filter-on-null-value-in-the-generated-api Vote for it (and push your friends too :P )

**Comment by derrickmehaffy** [comment]
@alexandrebodin PR's are frozen remember :P

**Comment by alexandrebodin** [comment]
Won't be merged be I can guarantee this code won't be change before beta :)
