### ISSUE TITLE
Nested query using inconsistent naming convention for model

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#3144]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: 6.5
- **Strapi version**: alpha 26
- **Database**: mysql
- **Operating system**: macOS 10.14

**What is the current behavior?**
When I query a related model using graphql I'm getting an internal server error:
<img width="1433" alt="Screenshot 2019-04-16 13 20 21" src="https://user-images.githubusercontent.com/547583/56234369-c1655200-604a-11e9-9d4f-45bfe2c44982.png">

And here's a look at the `blends_management_systems__managementsystems_blends` table Strapi created:
<img width="318" alt="Screenshot 2019-04-16 13 26 39" src="https://user-images.githubusercontent.com/547583/56234629-549e8780-604b-11e9-9a2a-6d69138fb025.png">

**Steps to reproduce the problem**
Prior to upgrading to alpha 26 I had 2 models, `blend` and `managementsystem`. Under **Advanced -> Collection Name** I had `blends` and `management_systems`. As of alpha 22 I was able to query the nested resource successfully.

**What is the expected behavior?**
I should be able to query the nested resources.

**Suggested solutions**
When I look at the error message I'm seeing Strapi construct the model name using 2 different methods. It seems like when creating the table name and querying Strapi uses the `Collection Name` entered when creating the model. But when creating the join id column in the database it uses the standard model name. Note that these tables were created with a version of strapi well before version alpha 22 (maybe alpha 16). So I'm not sure if something has changed since then. Am I going to have to manually rename all my database columns?

**Comment by greatwitenorth** [comment]
Also as further followup, even if I do change the column name to `management_system_id` I see the following error:
<img width="1435" alt="Screenshot 2019-04-16 13 32 09" src="https://user-images.githubusercontent.com/547583/56234999-13f33e00-604c-11e9-952b-a3d46bc2a12d.png">

Note that it's now looking for `managementsystem_id` suggesting that different parts of the code are using different naming conventions.

**Comment by alexandrebodin** [comment]
@greatwitenorth Could you share the json models so we can reproduce your bug ? 

Thanks

**Comment by greatwitenorth** [comment]
Managementsystem.settings.json:
```json
{
  "connection": "default",
  "collectionName": "management_systems",
  "info": {
    "name": "managementsystem",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "blends": {
      "collection": "blend",
      "via": "managementSystems"
    }
  }
}
```

Blend.settings.json:
```json
{
  "connection": "default",
  "collectionName": "blends",
  "info": {
    "name": "blend",
    "description": "",
    "mainField": "name"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "description": {
      "type": "text"
    },
    "moistureLevels": {
      "collection": "moisturelevel",
      "via": "blends",
      "dominant": true
    },
    "componentMixes": {
      "collection": "componentmix",
      "via": "blends",
      "dominant": true
    },
    "primaryUses": {
      "collection": "primaryuse",
      "via": "blends",
      "dominant": true
    },
    "managementSystems": {
      "collection": "managementsystem",
      "dominant": true,
      "via": "blends"
    },
    "seedBreakdowns": {
      "collection": "seedbreakdown",
      "via": "blend"
    },
    "soilZones": {
      "collection": "soilzone",
      "via": "blends",
      "dominant": true
    },
    "type": {
      "type": "enumeration",
      "enum": [
        "hay",
        "pasture"
      ]
    }
  }
}
```

**Comment by freddysu** [comment]
I just updated from alpha 25 to alpha 26 and I ran into the same issue after updating.

**Informations**
 - Node.js version: v11.12.0
 - NPM version: 6.1.0
 -Strapi version: 3.0.0-alpha.26
 - Database: postgres
 - Operating system: macOS 10.14

Here's the error screenshot:
<img width="1680" alt="Screen Shot 2019-04-17 at 4 07 58 pm" src="https://user-images.githubusercontent.com/2948101/56264822-0496f200-612b-11e9-851c-9361afa0ebd7.png">

``ads_tags__adtags_ads`` table
<img width="272" alt="Screen Shot 2019-04-17 at 3 52 51 pm" src="https://user-images.githubusercontent.com/2948101/56264860-27c1a180-612b-11e9-8b2c-68a98684b1e8.png">

I noticed the error in the last line `ads_tags__adtags_ads_1.ad_tag_id does not exist`, where `ad_tag_id` doesn't match `adtag_id` in ``ads_tags__adtags_ads`` table.

Here's my json models:

`ad.settings.json`
```json
{
  "connection": "default",
  "collectionName": "ads",
  "info": {
    "name": "ad",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string",
      "required": true
    },
    "tags": {
      "collection": "adtag",
      "dominant": true,
      "via": "ads"
    },
    "link": {
      "default": "",
      "type": "text"
    },
    "imgs": {
      "collection": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "desc": {
      "default": "",
      "type": "text"
    },
    "start_time": {
      "default": "",
      "type": "date"
    },
    "end_time": {
      "default": "",
      "type": "date"
    },
    "is_active": {
      "default": false,
      "type": "boolean"
    },
    "lang": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "non_specific",
        "all",
        "zh_hans",
        "zh_hant",
        "en"
      ]
    }
  }
}
```

`Adtag.settings.json`
```json
{
  "connection": "default",
  "collectionName": "ad_tags",
  "info": {
    "name": "adtag",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "default": "",
      "unique": true,
      "type": "string",
      "required": true
    },
    "desc": {
      "default": "",
      "type": "string"
    },
    "ads": {
      "collection": "ad",
      "via": "tags"
    }
  }
}
```

**Suggested solutions**
Currently my workaround is to rename my table from `ad_tags` to `adtags` and
change `collectionName` from `ad_tags` to `adtags`  in `Adtag.settings.json`. Then it will work correctly.

**Comment by alexandrebodin** [comment]
Thank you for these details. 

We will try to reproduce and fix this as soon as possible !

**Comment by fakedob** [comment]
Sorry to reopen the issue, but I have followed the fix in the last commit and it seems that it fixes the problem only partially. Not sure if I have to open a new ticket though, so decided to add my comment here.

The problem with the naming exists when you create a ManyToMany relation on the User model, where the naming get in the following order:

Let's say we have a model `"#"` with a ManyToMany relation on `"users-permissions_user"` and it has `"dominant"` flag set to true. The column in the join table gets a name `"user_id"` and the query to to db is like:

`select '#s'.*, '#s_users__users_#s'.'user_id' as '_pivot_user_id', '#s_users__users_#s'.'#_id' as '_pivot_#_id' from '#s' inner join '#s_users__users_#s' on '#s_users__users_#s'.'#_id' = '#s'.'id' where '#s_users__users_#s'.'user_id' in (1)` where `"userspermissionsuser_id"` should be `"user_id"` instead.

When you set the `"dominant"` flag on the `"#"` model instead, you get a "`user_id"` naming on the join table column, but the generated query is as follows:

`select distinct '#s'.* from '#s' left join '#s_users__users_#s' as '#s_users__users_#s_1' on '#s_users__users_#s_1'.'#_id' = '#'.'id' left join 'userspermissionsuser' as 'userspermissionsuser_1' on '#s_users__users_#s_1'.'userspermissionsuser_id' = 'userspermissionsuser_1'.'id' where 'userspermissionsuser_1'.'id' in ('1')"` should be `"userspermissionsuser_id"` instead.

I guess they are somewhat reversed. I have spent 20 hours digging it and unfortunately did not find the  source :(

Also something I have to add, while debugging this exact request, I can see the model get populated (including all attributes and selected relation with its attributes) inside the querybuilder response, which then throws the error, which I miss to find the source of.

Thank you for you time, hope you can find the problem soon :)

**Comment by fakedob** [comment]
Sorry to reopen the issue, but I have followed the fix in the last commit and it seems that it fixes the problem only partially. Not sure if I have to open a new ticket though, so decided to add my comment here.

The problem with the naming exists when you create a ManyToMany relation on the User model, where the naming get in the following order:

Let's say we have a model `"A"` with a ManyToMany relation on `"users-permissions_user"` and it has `"dominant"` flag set to true. The column in the join table gets a name `"user_id"` and the query to to db is like:

`"select distinct 'as'.* from 'as' left join 'as_users__users_as' as 'as_users__users_as_1' on 'as_users__users_as_1'.'a_id' = 'as'.'id' left join 'users-permissions_user' as 'users-permissions_user_1' on 'as_users__users_as_1'.'users-permissions_user_id' = 'users-permissions_user_1'.'id' where 'users-permissions_user_1'.'id' in ('1')"` and you receive error for `"SQLITE_ERROR: no such column: as_users__users_as_1.users-permissions_user_id"` where `"userspermissionsuser_id"` should be `"user_id"` instead.

When you set the `"dominant"` flag on the `"A"` model instead, you get a "`userspermissionsuser_id"` naming on the join table column, but the generated query is as follows:

`"select 'as'.*, 'as_users__users_as'.'user_id' as '_pivot_user_id', 'as_users__users_as'.'a_id' as '_pivot_a_id' from 'as' inner join 'as_users__users_as' on 'as_users__users_as'.'a_id' = 'as'.'id' where 'as_users__users_as'.'user_id' in (1)"` and you receive error for - SQLITE_ERROR: no such column: as_users__users_as.user_id"` where `"user_id"` should be `"userspermissionsuser_id"` instead.

![gh](https://user-images.githubusercontent.com/8687970/56447728-c52afa00-6312-11e9-8b26-63499b3992ba.jpg)

I guess they are somewhat reversed. I have spent 20 hours digging it and unfortunately did not find the  source :(

Also something I have to add, while debugging this exact request, I can see the model get populated (including all attributes and selected relation with its attributes) inside the querybuilder response, which then throws the error, which I miss to find the source for.

Thank you for you time, hope you can find the problem soon :)

**Comment by lauriejim** [comment]
Hello @fakedob !

Can you open a new issue with the issue template to be sire to well understand your issue and have steps to be able to reproduce it.
