### ISSUE TITLE
TypeError: orm.load(...).buildQuery is not a function

### ISSUE THREAD

**Issue by HZooly** [strapi/strapi#3145]
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.26
- **Database**: MySQL (tested with --quickstart too)
- **Operating system**: macOS

**What is the current behavior?**

After a fresh install of latest Strapi, I'm unable to start the generated project.

**Steps to reproduce the problem**

- `npm i -g strapi@alpha`
- `strapi new test`
- Select MySQL, config database
- `cd test`
- `strapi start`
- Got this error:
```
(node:6012) UnhandledPromiseRejectionWarning: TypeError: orm.load(...).buildQuery is not a function
    at buildQuery (/Users/Zooly/Documents/DEV/gatsby/api/plugins/users-permissions/node_modules/strapi-utils/lib/buildQuery.js:116:21)
    at Function.count (/Users/Zooly/Documents/DEV/gatsby/api/plugins/users-permissions/config/queries/bookshelf.js:22:23)
    at Object.initialize (/Users/Zooly/Documents/DEV/gatsby/api/plugins/users-permissions/services/UsersPermissions.js:339:67)
    at module.exports (/Users/Zooly/Documents/DEV/gatsby/api/plugins/users-permissions/config/functions/bootstrap.js:167:65)
(node:6012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-04-16T19:37:52.569Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-04-16T19:37:52.571Z] warn Perhaps you forgot to call it?
```

**Comment by mimamuh** [comment]
Hi, I had the same issue today #3142.
Solution: Update `strapi-hook-mongoose` dependency to alpha.26 too.

**Comment by HZooly** [comment]
Ow, sorry missed yours..!
However, not fully the same. I don't have the `strapi-hook-mongoose` dependency since I'm using MySQL database. 

```
  "dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-alpha.26",
    "strapi-utils": "3.0.0-alpha.26",
    "strapi-hook-bookshelf": "3.0.0-alpha.26",
    "strapi-hook-knex": "3.0.0-alpha.26",
    "knex": "latest",
    "mysql": "2.16.0"
}
```

**Comment by HZooly** [comment]
@alexandrebodin no, @mimamuh did, but not on my side.

**Comment by alexandrebodin** [comment]
@HZooly It seems you have updated the right dependencies this should work. try to clean your node_modules if not working yet and run `npm install` again

**Comment by HZooly** [comment]
Ok I'll try. But I didn't updated anything. This comes from a fresh bootstrap of a Strapi project.

**Comment by HZooly** [comment]
Hmmm I don't this I have them globally.

**Comment by lauriejim** [comment]
Hello @HZooly !

I suggest you to remove manually all your globals Strapi node modules.
```
// display where are install global node_modules
npm root -g

// and then remove Strapi stuff
rm -r my/node_modules/path/strapi*
```

When it's node, re-install Strapi with `npm i strapi@alpha -g`
And create a new application.

If this steps doesn't work it mean you have an other issue in your machine that is not related to Strapi itself.

**Comment by HZooly** [comment]
Ok thanks for this suggest @lauriejim I'll try this evening.

I tried to do it yesterday but not manually, I used `npm uninstall strapi strapi@alpha -g`

**Comment by HZooly** [comment]
@lauriejim I've deleted all strapi folders in global node modules and it's working fine!

Thanks a lot for your help !
