### ISSUE TITLE
Multiple databases with split Users & Roles cause errors

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3147]
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: v26
- **Database**: MySQL
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: https://github.com/canonn-science/CAPv2-Strapi

**What is the current behavior?**

In my case I have two databases:
1) capiv2_base
2) capiv2_user

All tables are on the `capiv2_base` EXCEPT for the `users-permission_user` table which is on the `capiv2_user` database.

@alexandrebodin and I have traced the problem down to the fix for the counts of users per role on the adminUI attempting to use a SQL Join between two databases without the database prefix:

```
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage:
   'Table \'capiv2_user.users-permissions_role\' doesn\'t exist',
  sqlState: '42S02',
  index: 0,
  sql:
   'select distinct count(*) as `count` from `users-permissions_user` left join `users-permissions_role` as `users-permissions_role_1` on `users-permissions_role_1`.`id` = `users-permissions_user`.`role` where `users-permissions_role_1`.`id` = 1' }
```

Strapi is assuming that both these tables on the same database.

**Steps to reproduce the problem**

Split the users table into it's own database and attempt to query the adminUI for roles or permissions/advanced settings

**What is the expected behavior?**

Strapi should use the database name prefix before the table to prevent this issue, given this will only work if the tables are on the same DB server (which is common).

My reason for doing this is such that if a user updated their password on my Production server, they can still use that account to access my Staging server (for testing their applications before throwing load at my production one)

This is fairly common with larger APIs that they offer a "Test" server to play on without fear of hurting the production one, or filling the prod server with fake or useless data.

**Suggested solutions**

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum-staging.strapi.io/t/testing-new-theme-with-new-topic/38/7

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/global-hello-topic-to-introduce-yourself/45/2
