### ISSUE TITLE
Mongodb relationship

### ISSUE THREAD

**Issue by josselinlbe** [strapi/strapi#3149]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: Strapi 3.0.0-alpha.26
- **Database**: MongoDB
- **Operating system**:  Windows 7

**What is the current behavior?**
On the new Strapi version 26, i have this error when i try to create a relationship between two contents. It's a fresh install, i saved my old version 25.2.

debug POST /searches (114 ms)
TypeError: property.map is not a function
    at params.parseRelationships.Object.keys.reduce (C:\Users\users\Documents\project\app\server\node_modules\strapi-hook-mongoose\lib\relations.js:99:49)
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (C:\Users\users\Documents\project\app\server\node_modules\strapi-hook-mongoose\lib\relations.js:30:122)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Steps to reproduce the problem**
![1](https://i.imgur.com/Jf2lHFt.png)
![2](https://i.imgur.com/LoYy9zR.png)

When I try to POST with my app with the ObjectId of an entry of MongoDB, i have this return.
![image](https://user-images.githubusercontent.com/15314417/56290429-6bb0a880-6123-11e9-9396-9a83d246144c.png)

Search settings
`{
...
    "organizations": {
      "collection": "organization",
      "via": "searches",
      "dominant": true
    }
...
}
`

Organization settings
`{
...
    "searches": {
      "collection": "search",
      "via": "organizations"
    }
...
}
`

**Comment by alexandrebodin** [comment]
@josselinlbe Can you provide the POST request your are doing ? 

You are probably send a value instead of an array of values to generate the links

**Comment by josselinlbe** [comment]
Before I used to send a value. It's ok with an array. Thanks !
