### ISSUE TITLE
strapi-to-strapi auth provider

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#3150]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Hey! I would love to use strapi as my main user repository,  but I don't want one monolithic application to handle everything. I have different strapi microservices that have their own data schema.
But I would love to use strapi as my main user repository.

Is that somehow possible? Since the data structures are similar, it should be easy :)

**Comment by lauriejim** [comment]
Hello @MartinMuzatko !

Strapi is not made to manage micro services, so we will not work on this feature. 
But thank you for this feedback.

For now I don't know how to do that correctly.
You will probably have to redirect permissions request to the Strapi app that manage permissions.

**Comment by derrickmehaffy** [comment]
@MartinMuzatko if all your micro-services are on the same database you can share the user-permissions_user & user-permissions_role tables. (I do so with different environments)

**Comment by derrickmehaffy** [comment]
(Side note you could probably build an OAuth server plugin using passport after the framework rewrite is done)
