### ISSUE TITLE
Auth parameters for custom provider upload

### ISSUE THREAD

**Issue by andredrover** [strapi/strapi#3154]
**Informations**
- **Node.js version**:  10.15.3
- **NPM version**:  6.5.0
- **Strapi version**:  3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: Windows
- **(Optional) Link to your Project**:  https://github.com/voxivoid/strapi-provider-upload-ftp/tree/01044dedd8fb11ccbc6beb26b3d67549a6b3fa8e

**What is the current behavior?**
When I add a checkbox type parameter to a custom provider upload it always shows me the `This value is required.` message.

![image](https://user-images.githubusercontent.com/47530421/56316079-4fc3fb80-6151-11e9-91be-08d87e5dbcda.png)

**Steps to reproduce the problem**
Select my provider as the current provider, fill the form and try to save.

**What is the expected behavior?**
As it is a checkbox, it should accept both being unchecked or checked.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2734

> This is a templated message
