### ISSUE TITLE
Deep filtering + Graphql, deep object returns null 

### ISSUE THREAD

**Issue by merijnvanessen** [strapi/strapi#3155]
Node v10.6.0
NPM 6.1.0
MongoDB  v4.0.9
strapi 3.0.0-alpha.26
MongoDB
MacOS 10.14.1

What is the current behavior?
On a fresh install, a deep filtered query within the playground returns no object for the deep filtered item

```
{
  puppies(where:{breeds:{name_contains:"affenpinscher"}}){
    _id
    name
    breeds{
      _id
      name
    }
  }
}
```
Results correctly :
```
{
  "data": {
    "puppies": [
      {
        "_id": "5cb781e3d803f9b7e4594af3",
        "name": "sammy",
        "breeds": null
      }
    ]
  }
}
```
But breed is null, and breed should result an ID and a name

Steps to reproduce the problem
1. Make sure the latest strapi is installed (npm i -g strapi@alpha)
2. strapi new project
3. Mongo Db, and create a project
4. Add the grapqhl plugin from the marketplace (or install it with NPM)
5. add two content-types in the content-type builder
for example:
a) puppies
b) breeds

both contentypes have a field 'name'
I added two puppies, and two breeds, (affenpinscher, poodle ;-)

In content-type builder I added a relation, actually I tried all 5 of them.
But in my opion, a puppy 'has and belongs to one breed'

What is the expected behavior?
"breeds": null should return:

```
"breeds": [
          {
            "_id": "5cb781d6d803f9b7e4594af1",
            "name": "affenpinscher"
          }
        ]
```
Suggested solutions
I have no clue. Maybe I have to reinstall my mongoDB again. 
Or test on another machine

My puppies model:

```
{
  "connection": "default",
  "collectionName": "puppies",
  "info": {
    "name": "puppies",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "breed": {
      "model": "breeds",
      "via": "puppy"
    }
  }
}
```
My breeds model

```
{
  "connection": "default",
  "collectionName": "breeds",
  "info": {
    "name": "breeds",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "test": {
      "type": "string"
    },
    "puppy": {
      "model": "puppies",
      "via": "breed"
    }
  }
}
```

**Comment by alexandrebodin** [comment]
@merijnvanessen Looking at it now
