### ISSUE TITLE
Updating an entry removes it's one to many relation

### ISSUE THREAD

**Issue by acarrera94** [strapi/strapi#3156]
**Informations**
- **Node.js version**: Node v10.13.0
- **NPM version**: 6.7.0
- **Strapi version**: alpha.26
- **Database**: Mongoose 
- **Operating system**: Mac OS 10.14.3

**What is the current behavior?**
When I update an entry in the front end. It removes existing relationships that are one-to-many. 
**Steps to reproduce the problem**
1. Create two new content types: Product and Category 
2. Create a one-to-many relation. one Category has many products. 
3. Create a new Category 
4. Create a new product
5. Open the new category and add the new product as a relation and save.
6. Open the new category again and save again. 
7. Open the new category again
Result: previously added product is gone. 

**What is the expected behavior?**
previously added relations (products) will remain after updating a category.

**Suggested solutions**
I hit a dead end while debugging. in plugins/content-manager/config/queries/mongoose.js, the method this.updateRelations is called and I can't find where this method is defined. But I assume that the error happens in this method.

**Comment by acarrera94** [comment]
I hit a dead end while debugging. in plugins/content-manager/config/queries/mongoose.js, the method this.updateRelations is called and I can't find where this method is defined.

**Comment by merijnvanessen** [comment]
I have the same problem with postgres, right now. 

![Schermafbeelding 2019-04-18 om 23 20 29](https://user-images.githubusercontent.com/23075300/56392025-963c5780-6230-11e9-95e4-3e92e2b2798a.png)

Before saving

![Schermafbeelding 2019-04-18 om 23 21 09](https://user-images.githubusercontent.com/23075300/56392056-ace2ae80-6230-11e9-85c0-1533ff1eaf13.png)

After saving

![Schermafbeelding 2019-04-18 om 23 21 32](https://user-images.githubusercontent.com/23075300/56392072-b9ff9d80-6230-11e9-9ab2-e800d5036533.png)

**Comment by acarrera94** [comment]
The fix will be released Monday.

**Comment by merijnvanessen** [comment]
Thanks !

**Comment by BroTrue** [comment]
Still not fixed yes :(

**Comment by lauriejim** [comment]
Did you try with a fresh new application and database with Strapi `3.0.0-alpha.26.2` ?

**Comment by BroTrue** [comment]
@lauriejim No I didnt try, because there is no migration guide for this version. Migration is like always copy&paste new `admin` and `plugins` folder?

**Comment by derrickmehaffy** [comment]
@BroTrue https://github.com/strapi/strapi/issues/1880
