### ISSUE TITLE
Integer field minimum value can't be set to 0

### ISSUE THREAD

**Issue by Alluuu** [strapi/strapi#3162]
On a new install (quickstart) of Strapi on latest stable node.js and npm when adding a new or editing an existing integer type field, the value can not be set 0, The inputfield accepts -1 and when increasing with html controls it goes -> empty -> 1 ... but no 0.
I see 0 being quite important for many inputs where you know you need a positive value, like year, volume, other measurements etc..

This can be recreated with any latest Strapi install by creating new content type, adding integer field and from advanced field try to add minimum value restriction 0.

This seems to be implemented by someone for somereason, as the default value field acts properly and accepts 0

**Comment by derrickmehaffy** [comment]
@Alluuu Please follow the bug report template, after you have updated your original post with the proper required template information this can be reopened
