### ISSUE TITLE
How to choose images from the gallery?

### ISSUE THREAD

**Issue by LubomirGeorgiev** [strapi/strapi#3168]
I have an image that I want to re-use on multiple fields.
How can I choose this images from the gallery?
Currently it's always asking me to re-upload the same image over and over again.

**Comment by lauriejim** [comment]
this feature doesn't exist for now in Starpi.
Please check this card on the roadmap https://portal.productboard.com/strapi/c/28-media-library-with-edit-crop-resize-capabilities
It match with your need.

**Comment by LubomirGeorgiev** [comment]
@lauriejim When do you expect this feature to be implemented?

**Comment by Aurelsicoko** [comment]
@LubomirGeorgiev We plan to implement it at the end of the year (Q4). You can see the roadmap [here](https://portal.productboard.com/strapi/tabs/3-planned).
