### ISSUE TITLE
Polymorphic one-to-one relationships cause errors (model: "*")

### ISSUE THREAD

**Issue by robng** [strapi/strapi#3173]
**Informations**
- **Node.js version**: v11.10.1
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.26.1
- **Database**: mongodb
- **Operating system**: Debian

**What is the current behavior?**

When trying to define a one-to-one polymorphic field, the whole model suddenly appears to become undefined and cause errors.

> error Something went wrong in the model `Card` with the attribute `reference`
error Cannot read property `nature` of undefined

**Steps to reproduce the problem**

1. Create a new model with a one-to-one polymorphic field. In this case the field will be called `reference` and it's only attribute will be `"model": "*"`
```
{
  "connection": "default",
  "collectionName": "card",
  "info": {
    "name": "card",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    [...]
    "reference": {
      "model": "*"
    }
  }
}
```

**What is the expected behavior?**

The expected behavior would be for strapi to just accept the definition and allow the relation.
I have tried replacing the one-to-one with a many-to-many relation before (using `"collection: "*"`) and that worked just fine.

Also, as soon as `"model": "*"` is replaced with an actual model; for instance `"model": "contact"` strapi will restart and work just as expected.

**Suggested solutions**

I have not gone through strapi code too much; however the problem seems to stem from `strapi-hook-mongoose/lib/relations.js`.

**Comment by lauriejim** [comment]
Hello! Your model look wrong.
Some keys are missing. Please make sure your follow the docuementation here https://strapi.io/documentation/3.x.x/guides/models.html#relations

**Comment by robng** [comment]
Hello,

I've tried multiple combinations as shown in the docs. However I always seem to get the same error, once I specify anything other than an existing content type (like `model`: `card`).

Currently I'm trying to get a one-to-many relationship working like so:

Card.settings.json
```json
    "reference": {
      "model": "*",
      "via": "cards"
    }
```

Contact.settings.json
```json
    "cards": {
      "collection": "card",
      "via": "reference"
    }
```

and if I'm following the docs correctly, thats how it would be done.

**Comment by cimchd** [comment]
I just checked the documentation at https://strapi.io/documentation/3.x.x/guides/models.html#polymorphic and checked both examples listed.

The example there for one-to-many is working with polymorphic collections:
`Path — ./api/image/models/Image.settings.json.`
```js
{
  "attributes": {
    "related": {
      "collection": "*",
      "filter": "field"
    }
  }
}
``` 
The example there with one-to-one is not working:
`Path — ./api/image/models/Image.settings.json.`
```js
{
  "attributes": {
    "related": {
      "model": "*",
      "filter": "field"
    }
  }
}
```
I get an error: `error Cannot read property nature of undefined`

I also checked the linked example of the upload plugin https://strapi.io/documentation/3.x.x/guides/upload.html#usage
but it seems that this example has changed and doesn't use polymorphic relations anymore.

Maybe if it's not a bug, the syntax for the usage of `model ="*"` has changed or some requirements are not listed in the documentation?

**Comment by lauriejim** [comment]
@robng You use `via` instead of `filter`.
@cimchd You have also to use `model` in your other model. It's why you have this issue.

The reason is indicate in notes inside the documentation.

**Comment by robng** [comment]
Good morning.
I dont think it is a problem with via or filter (I might have used them wrongly, yes; I have already tried filter and probably any possible combination of model, via, filter, ...). However the problem always appears as soon as I do "model": "*". It is like strapi suddenly stops caring about anything once there's "model": "*".

**Comment by lauriejim** [comment]
I just tested it and it start.

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by MrRopain** [comment]
I'll try in a fresh environment tomorrow.

**Comment by robng** [comment]
It appears to work now.

**Comment by TurningTide** [comment]
Hello! I have the same trouble with polymorphic relations on beta.10:
`[2019-07-14T05:19:34.611Z] error Something went wrong in the model 'Like' with the attribute 'related'`
`[2019-07-14T05:19:34.613Z] error TypeError: Cannot read property 'nature' of undefined`

My Like.settings.json:

```
{
  "connection": "default",
  "collectionName": "like",
  "info": {
    "name": "like",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    [...]
    "related": {
      "model": "*",
      "filter": "field"
    }
  }
```

`collection="*"` seems to work fine, but when i set `model="*"`, strapi crashes

**Comment by emahuni** [comment]
it seems like there is a bug here. I have the same issue. If I change that to collection everything works fine, just model "*" that's causing the issue. The issue needs to be reopened. I am on beta14

**Comment by emahuni** [comment]
or maybe we should create another issue?

**Comment by theshanergy** [comment]
Was anyone able to get this working? I've got the same issue described above. Code is exactly the same as in the documentation and I'm seeing the same error as above.

`Something went wrong in the model `Comment` with the attribute `related`
Cannot read property 'nature' of undefined`

**Comment by darron1217** [comment]
Any update on this issue?
No one has problem with polymorphic relation?
