### ISSUE TITLE
Upgrade to v3.0.0-alpha.26.1 kills graphql queries

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#3174]
**Informations**
- **Node.js version**: v10.15.3 (installed via nvm 0.33.0)
- **NPM version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.26.1
- **Database**:  Mongo 4.0.9
- **Operating system**:  Ubuntu 14.04.5 LTS (running is vagrant box - host is win10)
- **(Optional) Link to your Project**: 

**What is the current behavior?**
The query below was working fine in v3.0.0-alpha.26.0 but the moment I upgraded to __v3.0.0-alpha.26.1__ all graphql queries stop working. See query and error in screenshot below.

The error may look like the supporting __strapi-utils__ packages does not exist but it is
`
$npm outdated
`

| Package | Current |Wanted|
| --------- | -------- |---------|
| strapi  | 3.0.0-alpha.26.1  |3.0.0-alpha.26.1|
| strapi-hook-mongoose | 3.0.0-alpha.26.1  |3.0.0-alpha.26.1|
| strapi-utils | 2.0.2  |2.0.2|

**Steps to reproduce the problem**
Upgrade to v3.0.0-alpha.26.1  and perform a graphql query similar to the one in the screenshot

**What is the expected behavior?**
Should be able to execture queries that work just fine in earlier version

**Suggested solutions**
Advice what has change to graphql in v3.0.0-alpha.26.1 and what is the workaround

![strapi-error](https://user-images.githubusercontent.com/2515109/56601297-a8ccdd00-65f2-11e9-9b73-0cfb1a2d7c4b.png)

**Comment by derrickmehaffy** [comment]
Likely due to the changes made to force `id` instead of `_id`

**Comment by laportem** [comment]
I am using __id__ in the query above even with ___id__ it does not work

**Comment by alexandrebodin** [comment]
you strapi-utils should also be in 3.0.0-alpha.26.1

**Comment by laportem** [comment]
@alexandrebodin , that seems to be the problem. it works after upping to strapi-utils@3.0.0-alpha.26.1
I now need to figure out why i was getting strapi-utils@2.0.2 after the upgrade
thanks

**Comment by conghai** [comment]
I think you not yet require `convertRestQueryParams` in `topic service file` => may be in `api > topic > services > Topic.js`

`const { convertRestQueryParams, buildQuery } = require('strapi-utils');`

**Comment by lauriejim** [comment]
Did you also update your plugins ?
By follow default steps in migration guides https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.25-to-alpha.26.html

By following these steps
- Getting started
- Update node modules
- Update the Admin
- Update the Plugins

**Comment by laportem** [comment]
With due respect I find the migration guides a bit confusing. I think this is where it gets confusing

1. **Getting started** (all ok)
2. **Update node modules**
Where do we run `npm install strapi@3.0.0-alpha.26.1 –save`. In the new project created in step 1 above or in my old existing project. If in my old existing project shouldn’t we also run 
`
npm install strapi-hook-mongoose@3.0.0-alpha.26.1 –save
`
`
npm install strapi-utils@3.0.0-alpha.26.1 –save
`

my issue was the **strapi-utils** was not moving to the new 26.1 version even after doing 
`
npm install strapi-utils@3.0.0-alpha.26.1 –save
`
I had to manually npm uninstall it, remove the node_modules folder and re npm install it

3. **Update the Admin**
I assume we need to move the Admin folder from the new project created in step 1 above to replace the Admin folder in my old existing project

5. **Update the Plugins** (all ok)

**Comment by derrickmehaffy** [comment]
@laportem https://github.com/strapi/strapi/issues/1880

**Comment by lauriejim** [comment]
Can you please give us an update about this issue?

**Comment by laportem** [comment]
Sorry, i got is sorted by doing a clean up Upgrade. The issue was the  "strapi-utils" was stuck with an older version.
I had to manually "npm uninstall" it and re "npm install" it to the newest version.
We can close the issue
