### ISSUE TITLE
Filtering params misconception not standard HTTP

### ISSUE THREAD

**Issue by backnight** [strapi/strapi#3175]
This issue is opened about a misconception for the filtering params: https://strapi.io/documentation/3.x.x/guides/filters.html#available-operators

As specified by the documentation:
`Find multiple product with id 3, 6, 8
GET /products?id_in=3&id_in=6&id_in=8`

This is not standard to build an url with multiple times the same parameter name: **id_in**

We can't request the API this way using any HTTP library.

It should be done like that:
`GET /products?id_in[]=3&id_in[]=6&id_in[]=8`
=> **id_in** would be an array and would be correctly built from any HTTP library.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

**Comment by alexandrebodin** [comment]
@backnight 

This syntax is what koa supports by default. 
You can request it like this for example with no problem:

```javascript
const axios = require('axios');
const querystring = require('querystring');

const qs = querystring.stringify({
  id: [1, 2],
});

axios.get(`http://localhost:3000?${qs}`)
```

In any case we plan on adding this to support the other syntax :) https://github.com/koajs/qs
