### ISSUE TITLE
error No generator called `new` found.

### ISSUE THREAD

**Issue by jippy89** [strapi/strapi#3176]
**Strapi Version:** 3.0.0-alpha.26.1
**Node Version:** v10.15.3
**NPM Version:** v6.4.1
**PNPM Version:** v3.1.0

**Little Background**
I had no idea, I just downloaded a fresh install of `strapi` and this happens. I was installing using `pnpm i -g strapi@alpha`. I am using the **Operating System** below:  
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.4
Codename:	Illyria

**What is the current behavior?**
Not working..

**Steps to reproduce the problem**
Running `strapi new cms --quickstart` seems to result in this error
```
🚀 Starting to create your Strapi application.

[2019-04-24T13:38:10.472Z] error No generator called `new` found.
```

**What is the expected behavior?**
Working as expected in **Getting Started**

**Comment by derrickmehaffy** [comment]
@jippy89 pnpm is not supported yet, please install node via a typical method such as the arch package manager, you need need node 10.

https://nodejs.org/en/download/package-manager/#arch-linux

**Comment by jippy89** [comment]
Thanks for quick response :)
Now I had this issue, after doing `strapi new cms --quickstart`,

**How to reproduce?**
`cd ProjectName`
`strapi start`

**Error Logs:**
2019-04-24T14:15:58.131Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-24T14:15:58.136Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load

**Comment by derrickmehaffy** [comment]
Hmmm that's odd considering quickstart is just SQLite (file based), might be a permission issue there. I can't reproduce it on Linux Mint 19.1

**Comment by jippy89** [comment]
I've tried this [issue](https://github.com/strapi/strapi/issues/1612#issuecomment-419411724) and it seems to be doing something. It does shows an error after I do `npm install` then `strapi start`, but it's fixed by `npm audit fix`, then I do another run of `strapi start`.

And it works! However, I can only open `localhost:1337`. I can't seem to open `localhost:1337/admin`,
I mean I do I can open it but this what shows on the page
![image](https://user-images.githubusercontent.com/33748953/56641539-c86e0f00-669f-11e9-9f40-90ea9f403d3b.png)

**Side note,** is this already off topic? If so, then I will open another issue for this.

**Comment by derrickmehaffy** [comment]
@jippy89 Technically it isn't a bug just a user environment issue. This convo would probably be better had on the slack: https://slack.strapi.io

So you are right, I'll mark this as closed, and we can continue here or on the slack.
