### ISSUE TITLE
Hierarchical relationship type

### ISSUE THREAD

**Issue by LucaGabi** [strapi/strapi#3178]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

In the relation content type one should be able to also define a hierarchical relation type.
As example, consider: employees model with superiors or pages with subpages.

Thanks!

**Comment by derrickmehaffy** [comment]
@LucaGabi The relation you are looking for is oneToMany or manyToMany

**One** superior can have **many** employees
or
**Many** employees can have **many** superiors
