### ISSUE TITLE
Locale query parameter does not return the correct translation in staging & production envs

### ISSUE THREAD

**Issue by devaublanc** [strapi/strapi#3179]
**Informations**
- **Node.js version**: v10.14.0
- **NPM version**: v6.9.0
- **Strapi version**: v3.0.0-alpha.21 (I know it's not the last version but I can't see any topic related to this issue in the higher versions Changelog)
- **Database**: mongoDB
- **Operating system**: Mac OS X

**What is the current behavior?**
I followed the strapi documentation with the exact same example. https://strapi.io/documentation/3.x.x/guides/i18n.html#internationalization
`/hello/John?locale=en_US` and `/hello/John?locale=fr_FR` everything works as expected in development env but in staging and production env, it's always take the key as fallback

**Steps to reproduce the problem**
1) Create the route

```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/hello/:name",
      "handler": "Hello.sayHello"
    }
  ]
}
```

2) Create the controller

```javascript
module.exports = {
  // GET /hello/:name
  sayHello: async (ctx) => {
    ctx.send(ctx.i18n.__('Foo %s', ctx.params.name));
  }
};
```

3) Create the i18n (fr_FR.json and en_EN.json)
```json
{
  "Foo %s": "Bonjour %s"
}
```

```json
{
  "Foo %s": "Hello %s"
}
```

I also forced the french in my config/language.json but it's always the key that appears `Foo Benjamin`
```json
{
  "enabled": true,
  "defaultLocale": "fr_fr",
  "modes": [
    "query",
    "subdomain",
    "cookie",
    "header",
    "url",
    "tld"
  ],
  "cookieName": "locale"
}
```

**What is the expected behavior?**
The query parameter locale have to works in the production and staging environments like it already does in development environment.

**Comment by devaublanc** [comment]
development env OK
![Capture d’écran 2019-04-24 à 13 55 38](https://user-images.githubusercontent.com/12794277/56657582-b341b200-6698-11e9-8d9d-b198508080b2.png)

staging, production env KO
![Capture d’écran 2019-04-24 à 13 55 19](https://user-images.githubusercontent.com/12794277/56657685-f8fe7a80-6698-11e9-99fa-a93a914ca69d.png)

**Comment by diamondback15** [comment]
I can confirm I have to the same problem when I try to use all endpoint of users-permisisons as well : /auth/reset-password?locale=fr or fr_FR

**Comment by lauriejim** [comment]
Hello! 
I just tried with a fresh new app with `alpha.26` and translations works well!

**Comment by devaublanc** [comment]
Ok I found the solution !

Yes @lauriejim with a fresh install everything is working. But the problem comes up if you upgrade Strapi by following the migration guide like I did

You have to rename this files: 
renamed:    config/locales/en_US.json -> config/locales/en_us.json
renamed:    config/locales/es_ES.json -> config/locales/es_es.json
renamed:    config/locales/fr_FR.json -> config/locales/fr_fr.json
renamed:    config/locales/it_IT.json -> config/locales/it_it.json
renamed:    config/locales/ru_RU.json -> config/locales/ru_ru.json
renamed:    config/locales/tr_TR.json -> config/locales/tr_tr.json
renamed:    config/locales/jp_JP.json -> config/locales/jp_jp.json

If you are using a CI hooked on GIT `git mv config/locales/fr_FR.json  config/locales/fr_fr.json`
