### ISSUE TITLE
Server wasn't able to start properly

### ISSUE THREAD

**Issue by ogonkov** [strapi/strapi#318]
Patched version (#317) seems fail to restart. Could be related to local installation.

```
INFO (1961 on MacBook.local): Server started in /Users/user/Projects/strapi-example/foo-project
INFO (1961 on MacBook.local): Your server is running at http://localhost:1337
DEBUG (1961 on MacBook.local): Time: Tue Oct 31 2017 23:24:56 GMT+0300 (MSK)
DEBUG (1961 on MacBook.local): Launched in: 698 ms
DEBUG (1961 on MacBook.local): Environment: development
DEBUG (1961 on MacBook.local): Process PID: 1961
DEBUG (1961 on MacBook.local): Version: 3.0.0-alpha.6.4 (node v8.9.0)
INFO (1961 on MacBook.local): To shut down your server, press <CTRL> + C at any time
... bunch of assets requests
DEBUG (1961 on MacBook.local): POST /content-type-builder/models/ (109 ms)
INFO (1960 on MacBook.local): The server is restarting

DEBUG (1974 on MacBook.local): Server wasn't able to start properly.
ERROR (1974 on MacBook.local): (hook:mongoose) takes too long to load
```

**Node.js version**: v8.9.0
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.6.4
**Operating system**: macOS 10.13

**Comment by Aurelsicoko** [comment]
I've made a local installation with your PR (#317) that I'm going to accept and I wasn't able to reproduce the bug. I need more details about your Mongo connection because the issue seems located into the `strapi-mongoose` hook.

**Comment by ogonkov** [comment]
Did you add some products?
What details i need to provide?

**Comment by jakobrosenberg** [comment]
I have the same error on 3.0.0-alpha.6.4 / Windows 10 x64.

It occurs if I create an API or if I save a Content Type.

**Comment by fisshy** [comment]
I got the same problem. Windows 10 x64.

**Comment by fisshy** [comment]
Ok, solved it by installing mongodb. It was missing.

Maybe Strapi should try detect mongodb and give a clearer message. 

https://docs.mongodb.com/v2.8/tutorial/install-mongodb-on-windows/

**Comment by jakobrosenberg** [comment]
I'm running Mongodb in a container, but I can't connect to it. Changing the config in ``config/environments/development/database.json`` doesn't change anything. I've tried different usernames, but it always tries to connect as ``admin``. I have no idea what password it's using.

**Comment by Aurelsicoko** [comment]
@jakobrosenberg Maybe you found something... Can you confirm me that you're running the server in a `development` environment? Because if it's not the case, make sure you also update `config/environments/production/database.json` configurations.

**Comment by jakobrosenberg** [comment]
@Aurelsicoko After several restarts and reconfigurations, it was finally working. For some reason, it kept connecting as admin@development or something like that regardless of what was in the database.json.

Does Strapi cache the config?

**Comment by lauriejim** [comment]
Hum there is no configuration cache in Strapi.

**Comment by Aurelsicoko** [comment]
@jakobrosenberg The core doesn't cache anything but `require` method does. It could be related... I just created a pull request (https://github.com/strapi/strapi/pull/344) to fix it.

**Comment by moeinrahimi** [comment]
in my case changing host from localhost to 127.0.0.1 in database.json at development folder did the trick

**Comment by M1chaelTran** [comment]
@moeinrahimi solution works for me! This should be the default settings instead of `localhost`

**Comment by krishnpalchouhan** [comment]
I'm totally new to this having same issue, not able start serve it got crashed
same issue 
also not able to find 
localhost
Api/config/environments/development/database.json

**Comment by krishnpalchouhan** [comment]
this is the error 
I found localhost in server.js
updated with 127.0.0.1 
still not working

node:9092) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: table `tmp_categories` already exists
(node:9092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-04-10T22:05:36.541Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-10T22:05:36.542Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! LapShopeeApi@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the LapShopeeApi@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-10T22_05_36_560Z-debug.log

**Comment by derrickmehaffy** [comment]
@krishnpalchouhan your issue has nothing to do with localhost vs 127.0.0.1. you are using SQLite thus you aren't using a database but a file.
