### ISSUE TITLE
Move WYSIWYG setting from core_store to model.settings.json

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3180]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Don't see why the `core_store` // `content-manager plugin` needs to store the WYSIWYG boolean flag for the text field. Considering to change then you need to use the content-type builder to toggle the flag, IMO it should be stored as a boolean option under the `model.settings.json` file which would also stop users from needing to migrate their `core_store` entries over between environments.

**Comment by lauriejim** [comment]
Hello @derrickmehaffy !
We try to keep the `Model.settings.json` file for database stuff.
In this case the option of the WYSIWG is only for the UI, not related to the database.
This is the reason why.

**Comment by derrickmehaffy** [comment]
@lauriejim If that is the case then what is the point in this block?

```
  "info": {
    "name": "alert",
    "description": "Canonn Emergency Alerts"
```

Since that is used by the UI?

**Comment by lauriejim** [comment]
It's a legacy, not placed in the right place.

**Comment by derrickmehaffy** [comment]
We shall agree to disagree for now :stuck_out_tongue_closed_eyes:

**Comment by lappalj4** [comment]
@lauriejim can we seriously reconsider this? This is one of the only major gripes I (and I suppose a few others too) have with the design of Strapi currently, being unable to store things like this in version control. It would just make too much sense from a development/CI/etc. perspective to be argued away with semantics - if Model.settings.json isn't the correct place for it, couldn't the UI config live in a separate json file?

**Comment by alexandrebodin** [comment]
It is going to change soon. We are going to introduce a specific type for wisywig which will then morph to a richer text editor

**Comment by lappalj4** [comment]
Okay, that's good to hear! Any plans to do something similar with the rest of the UI settings? I'm not sure I understand why those should be stored in the DB

**Comment by derrickmehaffy** [comment]
@lappalj4 I see the reason why they are doing it, but I think having **both** options is important as not everyone wants to change the layout in production, **but** some people will. Doing something similar to the over-ride system currently in the beta I think would work best.

I am 100% on board with moving some/all of the CTM stuff into files AND in the core_store
