### ISSUE TITLE
Graphql doesn't return multiple relations to same model with different names 

### ISSUE THREAD

**Issue by acarrera94** [strapi/strapi#3183]
**Informations**
- **Node.js version**: Node v10.13.0  
- **NPM version**: 6.7.0
- **Strapi version**: alpha.26.1 
- **Database**: mongo
- **Operating system**: Mac OS 10.14.3
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When running a query that includes multiple relations to the same model via different names, only the results of one of those relations is returned. 

**Steps to reproduce the problem**
1. create a content type. For example Recipes. 
2. create a many to many relation between Recipes and users called "favorites" 
3. create a many to many relation between recipes and users called  "upvotes"
4. create an entry for Recipes with DIFFERENT users for each relation to "favorites" and "upvotes" 
5.  run a graphql query for the recipe including favorites and upvotes:
```
query {
  recipe(id: "5cb7828b7f0980f2e9dd9723") {
    favorites {
      id
    }
    upvotes {
      id
    }
  }
}
```

Result: only the first relation relation "favorites" will be returned. upvotes will be an empty array. 
```
{
  "data": {
    "recipe": {
      "favorites": [
        {
          "id": "5c1bece5893dd4718a8cc0e9"
        }
      ],
      "upvotes": []
    }
  }
```

**What is the expected behavior?**
both relations will return their values. 

**Suggested solutions**
In loader.js change the indexQueries const inside the extractQueries function, to include alias. 
```
      // Find similar query.
      const indexQueries = queries.findIndex(query =>
        _.isEqual(
          { options: query.options, alias: query.alias },
          { options, alias: association ? association.alias : undefined }
        )
      );
```

Since PR aren't being accepted right now I'll leave this here until it's resolved.

**Comment by lauriejim** [comment]
Hello! What is the key you use in for your User model ?
2 different keys I imagine, or the same key ?

**Comment by acarrera94** [comment]
I use different keys. favoritedUsers and upvotedUsers

**Comment by lauriejim** [comment]
Did you migrate to alpha.26.1 or you create a new application ?

**Comment by acarrera94** [comment]
Both.

**Comment by lauriejim** [comment]
Hum weird, can you send me an application zipped or a GitHub with the issue.
Cause it work on my side...

**Comment by acarrera94** [comment]
It looks like the problem was that I was on the last version of the graphql plugin. Once I updated, that fixed it.
