### ISSUE TITLE
Be able to count with search params

### ISSUE THREAD

**Issue by mTrCarlos** [strapi/strapi#3187]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha-26.1
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When querying the count route (model/count) with any _q param, 400 error is thrown (Bad Request) with message "Your filters contain a field '_q' that doesn't appear on your model definition nor it's relations".

**Steps to reproduce the problem**
Navigate to any count route with some value for _q (plural_model/count?_q=search_term) or query the graphql 'connection' with (where: { _q: "search_term" }) { aggregate { count totalCount } } 

**What is the expected behavior?**
Return the number of filtered entries.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello! Thank you to report that.

This is not an issue, the feature doesn't exist in Strapi.

Only `where`, so classique filter, are applied, not search params.
You get an error because you are trying filter on unknown attributes.

**Comment by mTrCarlos** [comment]
Thanks for the fast reply! 

We thought it was an issue because of #2333, so sorry about that and thank you for clarifying this.

We'll look for a workaround, like an alternative count route on our api. Also I'll check the content-manager plugin, which seems that got it working somehow, so maybe I can replicate it on the api.

**Comment by RooQI** [comment]
Hello **mTrCarlos**. 

I have the same problem with postgres on the same configuration. Did you manage to find a solution? Until I came up with anything better, how to remove the parameter _q from the count request.

**Comment by RooQI** [comment]
I also found a solution in adding code to the controller. It works, but slowly

`count: async (ctx, next, { populate } = {}) => {
    if (ctx.query._q) {
      ctx.query._start = 0;
      ctx.query._limit = 0;
      const count = await strapi.services.zone.search(ctx.query);
      return count.length;
    } else {
      return strapi.services.zone.count(ctx.query, populate);
    }
  }`

**Comment by mTrCarlos** [comment]
Hello @RooQI.
We got a different approach by now, which suits better for our case. We needed the entry count but also being able to choose which fields are we looking for. So our temporal solution until strapi give us some tools on this side, its to pregenerate a keyword field on each entry with our searchable data and only look at it with a multiple _contains query, so the count route should work again with this approach.

Thanks for your solution, it seems fine altho didn't tested it yet (not much time over here lol)

**Comment by wemod123** [comment]
Hello,
In document, [here it have the example of](https://strapi.io/documentation/3.x.x/guides/graphql.html#aggregation-grouping):
![image](https://user-images.githubusercontent.com/26819270/57426335-62fa5080-7251-11e9-84f8-8da51813dabf.png)

Is it valid?
since when I try following this, get error of something like: 
"Your filters contain a field *** that doesn't appear on your model definition nor it's relations"

**Comment by derrickmehaffy** [comment]
This was added in the Strapi Beta, marking as closed.
