### ISSUE TITLE
Installation workflow minor bug

### ISSUE THREAD

**Issue by corepay** [strapi/strapi#3188]
**Informations**
- **Node.js version**: 11.14 
- **NPM version**:  6.9
- **Strapi version**: latest 
- **Database**: PostgresSQL
- **Operating system**:  Mac OSX Latest
- **(Optional) Link to your Project**: 

**What is the current behavior?**

After building a new strapi app in terminal then opening VS code and trying `strapi start` from the root project directory get error.  Need to go back to terminal where project was built to `strapi start` successfully.

**Steps to reproduce the problem**

### IN TERMINAL

1. `npm install strapi@alpha -g`
2.  `strapi new cms`
```
🚀 Starting to create your Strapi application.

? Choose your installation type Custom (manual settings)
? Choose your main database: Postgres
? Database name: strapi
? Host: 127.0.0.1
? Port: 5432
? Username: postgres
? Password: ********
? Enable SSL connection: false

⏳ Testing database connection...
It might take a minute, please have a coffee ☕️

The app has been connected to the database successfully!

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
✔ Install plugin users-permissions.
✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application cms is ready at /Users/Rjp/development/frameworks/strapi/cms.

⚡️ Change directory:
$ cd cms

⚡️ Start application:
$ strapi start
RJP-Macbook:strapi Rjp$ cd cms
RJP-Macbook:cms Rjp$ code .
```

### VS CODE

1.  RJP-Macbook:cms Rjp$ `strapi start` in embedded terminal (ctrl/~) 
```
[2019-04-25T12:33:39.501Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-25T12:33:39.503Z] error URL is not defined
ReferenceError: URL is not defined
    at Strapi.module.exports.app (/usr/local/lib/node_modules/strapi/lib/core/configurations.js:333:10)
    at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:223:29)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```
In VS CODE I then did another `install strapi@alpha -g` in case the VS Code embedded terminal did not pick up the strapi package and then `strapi start` returned the same error.  Closed VS Code terminal and opened another session same results.

Went back to the terminal where I did the initial build and `strapi start` successfully.

**What is the expected behavior?**

`strapi start` in embedded VS Code terminal

**Suggested solutions**

**Comment by lauriejim** [comment]
I think the nodejs version you use in you VS code in node 9 or less.
Make sure you use node 10 at least.

**Comment by corepay** [comment]
Thank you Jim,

You are 100% correct.  My terminal was set >10 and VSCode was set at >8.  After change strapi started no problems.

**Comment by lauriejim** [comment]
It's a known issue.
Enjoy now :)
