### ISSUE TITLE
Filtering not working as expected [Mongo only]

### ISSUE THREAD

**Issue by SK-Commit** [strapi/strapi#3189]
**Informations**
- **Node.js version**: v10.15.3  
- **NPM version**: 6.9.0
- **Strapi version**: latest 26.1 alpha
- **Database**: MongoDB
- **Operating system**: Windows Server 2012
- **(Optional) Link to your Project**: 

**What is the current behavior?**
If a value is filtered with greater than 101 and less than 102, when value is 100, only the last filter property is respected.

**Steps to reproduce the problem**
1. Create new project with mongoDB
2. Create content type test with numeric field "test".
3. Create entry with value 100
4. Filter in either Admin UI or REST request with test?test_gt=101&test_lt103
5. returns value 100 anyways

**What is the expected behavior?**
Value 100 should be filtered out and not returned.

**Suggested solutions**
Seems to be mongoDB only problem, and has something to do with the last filter applied only being respected. the filter function doesnt `{gt: 101 AND lt: 102}` and might only set the last only.

**Comment by alexandrebodin** [comment]
Hi, 
Thank you for reporting this issue. 

The bug has been identified and we will open a PR asap
