### ISSUE TITLE
Can't filter on created_at or updated_at (REST & GraphQL)

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3192]
**Informations**
- **Node.js version**: v10
- **NPM version**: v6
- **Strapi version**: v26.1
- **Database**: MariaDB 10.3
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

Attempting to filter (any filter) on the automated `created_at` or `updated_at` fields result in the following error:

```
{
"statusCode": 400,
"error": "Bad Request",
"message": "Your filters contain a field 'created_at' that doesn't appear on your model definition nor it's relations"
}
```

Likewise with graphql:

```
{
  "errors": [
    {
      "message": "Your filters contain a field 'created_at' that doesn't appear on your model definition nor it's relations",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "fmreports"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "status": 400
        }
      }
    }
  ],
  "data": {
    "fmreports": null
  }
}
```

**Steps to reproduce the problem**

Attempt to filter on the date fields

**What is the expected behavior?**

Should function as regular fields

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello @derrickmehaffy !
Can you join the http request you did please.

**Comment by derrickmehaffy** [comment]
@lauriejim 

I have tested all the known ways (this worked prior to v26)
`https://api.canonn.tech/systems?_limit=1&created_at=2019-04-23T01:35:14.000Z`
`https://api.canonn.tech/systems?_limit=1&created_at=2019-04-23%2001:35:14`

Same applies for all the filters **except** _sort which works fine but any exact matches, contains, containss, ect do not work.

Including _gte, _lte, _lt, _gt (which is what most people will be using for the date fields)

**Comment by derrickmehaffy** [comment]
For reference this is the exact match of an entry I already have: 
![image](https://user-images.githubusercontent.com/8593673/56900363-826fcd00-6a4a-11e9-92ca-5653e8d36e2a.png)

(With bookshelf I still need to send the proper format not the moment.js one so `YYYY-MM-DD HH:MM:SS`)

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/56900431-ad5a2100-6a4a-11e9-9ca6-9aac011c0e54.png)

```
query {
  fmreports(where: { created_at_gte: "2019-04-17 00:00:00" }) {
    systemName
  }
}
```

https://api.canonn.tech/graphql

**Comment by derrickmehaffy** [comment]
Also @lauriejim I think this is a bug not an enhancement :thinking:

**Comment by crushy26** [comment]
@lauriejim It seems like this issue exists in Beta.15, I tried on my production app.

The createdAt field is available

![Screenshot 2019-08-25 at 12 25 15 PM](https://user-images.githubusercontent.com/37217713/63646642-99da7080-c733-11e9-81fb-8ecdf8540316.png)

On query, I am getting the following,

![Screenshot 2019-08-25 at 12 25 30 PM](https://user-images.githubusercontent.com/37217713/63646646-b37bb800-c733-11e9-8677-23955a2ec089.png)
