### ISSUE TITLE
Content request and/or advice: Revision History?

### ISSUE THREAD

**Issue by pcrossnz** [strapi/strapi#3195]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Hi there,

I have had a good search for this feature and have asked in the slack channel but with no success. I am wondering whether it is possible to bootstrap a revision history in strapi? The CMS is brilliant, but I would like be able to either: review content posted to the CMS via frontend forms and/or walk-back direct content changes that are incorrect. Some headless CMSs such as prismic and squidex implement this feature, but are missing some of the excellent functionality that Strapi offers. 

Any ideas appreciated! Thanks,

Phil :)

**Comment by lauriejim** [comment]
Hello! Thank you for this feedback, appreciate! 
Can you send this message here https://portal.productboard.com/strapi/c/18-contribution-workflow
It's our roadmap and this request already exist.
Thank you.
