### ISSUE TITLE
Can't save User if password Field is empty

### ISSUE THREAD

**Issue by Emadeddin-eibo** [strapi/strapi#3198]
When using Auth Provider (Facebook in my case), the user will be stored without a password in the database.

That's not a problem since all future login will be using Facebook, but the issue appear when trying to edit the user from the admin panel.

Since there's some length checking on the password field, you can't save the user unless you enter some random password (no need for this password in later connect)

**Informations**
- **Node.js version**: v11.14.0
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26.1
- **Database**: PostgresQL
- **Operating system**: Mojave 10.14.4 

Thanks

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2963

> This is a templated message
