### ISSUE TITLE
cloudinary upload provider error when using Mongo

### ISSUE THREAD

**Issue by jayakusumah** [strapi/strapi#3199]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.26.1
- **Database**: Mongo
- **Operating system**:  Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**

When I use sqlite upload it works normally, but when I use Mongo client I get an error message

`'Schema hasn\'t been registered for model "UploadFile".\nUse mongoose.model(name, schema)'` when saving new entry (content type has media fields), and when on the plugin/upload page I get an error message `{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`

I use `strapi-provider-upload-cloudinary` ver 3.0.0-alpha.26.1
**Steps to reproduce the problem**
Add new connections with mongo clients, change upload configuration to cloudinary provider, add content type with mongo connection, add media (upload) field, try to add new entry.

**What is the expected behavior?**
works normally like sqlite client

**Suggested solutions**

**Comment by lauriejim** [comment]
This issue has been fixed in beta version (at least beta.15)
