### ISSUE TITLE
ManyToMany Relationship with the User Model Creates Login Loop

### ISSUE THREAD

**Issue by taylor-knapp** [strapi/strapi#3202]
**Informations**
- **Node.js version**: v11.13.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.26.1
- **Database**: Postgres
- **Operating system**: MacOs

**What is the current behavior?**
Creating a ManyToMany relationship between the User model and any other content type AND naming the field on the other content type _users_ initiates some sort of bug that continually kicks you out on login. 

Once you change the the name of the relation field on the other model, it will work.

**Steps to reproduce the problem**
Create a ManyToMany relationship on any model with the User model and name it 'users'. (Which is the default suggested name.)

**What is the expected behavior?**
It should work as any other ManyToMany relationship.

**Suggested solutions**
Change the default to something else / prevent the name 'users' / figure out the root cause.

**Comment by seegan** [comment]
Steps to produce the issue

Create a model and link the model with ManyToMany relation to user-permission model 
go to graphQl and run the query 
```
{
   modelname(id:"1") {
        id
        users {
            id 
        }
   }
```

Boom ER_BAD_FIELD_ERROR: Unknown column 'modelnames_users__users_modelnames_1.userspermissionsuser_id' in 'on clause'

Have a look at userspermissionsuser_id it should be user_id

Please help me to fix it ASAP :)

**Comment by seegan** [comment]
I just workaround with the node_modules/strapi-hook-bookshelf/lib/buildQuery.js Line number 85 by

```
      qb.leftJoin(
        `${originInfo.model.databaseName}.${assoc.tableCollectionName} AS ${joinTableAlias}`,
        `${joinTableAlias}.${singular(originInfo.model.collectionName)}_${
          originInfo.model.attributes[assoc.alias].column
        }`,
        `${originInfo.alias}.${originInfo.model.primaryKey}`
      );


to 

      qb.leftJoin(
        `${originInfo.model.databaseName}.${assoc.tableCollectionName} AS ${joinTableAlias}`,
        `${joinTableAlias}.${
          originInfo.model.attributes[assoc.alias].column
        }`,
        `${originInfo.alias}.${originInfo.model.primaryKey}`
      );
```

Sorry Still I don't know whether it is right or wrong, but I have to show my project to client tomorrow..

**Comment by lauriejim** [comment]
Hello @seegan! The issue you are talking about is different.
Can you create an other issue please.

**Comment by lauriejim** [comment]
@taylor-knapp can you give me the details to reproduce your issue please.

**Comment by lauriejim** [comment]
Okay good, I was creating the relation from `testcontenttype` and not from `user` side.
Okay so for now, please create your many to many not from `user` content type.
Of if you did it. Update the `./plugins/users-permissions/models/User.settings.json` and remove the attribute `dominant: true` from here and add it in `./api/testcontenttype/models/Testcontenttype.settings.json`

**Comment by wickY26** [comment]
> Okay good, I was creating the relation from `testcontenttype` and not from `user` side.
> Okay so for now, please create your many to many not from `user` content type.
> Of if you did it. Update the `./plugins/users-permissions/models/User.settings.json` and remove the attribute `dominant: true` from here and add it in `./api/testcontenttype/models/Testcontenttype.settings.json`

It does not work like that either. I tried this with postgres and mysql both throw error 'unknown column'.
I am on the alpha26.2 both with strapi and graphql.

**Comment by lauriejim** [comment]
Since we split the `User` and `Administrator` this issue did not exist anymore.
