### ISSUE TITLE
Access to strapi global outside module.exports

### ISSUE THREAD

**Issue by Otavioensa** [strapi/strapi#3204]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.26.1
- **Database**: PostgreSQL 
- **Operating system**: MacOS

**What is the current behavior?**

Hi guys! 
I'm loading some env variables inside the `custom.json` file and I've just noticed that I can't have access to such values outside `module.exports = async (cb) => {}` on the model hooks. 

**Steps to reproduce the problem**
1) Go to model and try to access strapi.config.environments.development.anyDeclaredPropertie outside hooks module.exports block.
2) You shouldn't get the values from the config

**Suggested solutions**
Is there any perspective or workaround to be able to load this file outside module.exports? I'm being forced to repeat the same code on each hook function since I have to get access to the same values.
My suggestion would be able to get access to the properties from custom.js on `strapi.config.environments[env]myPropertie` in any part of the model part or being able at least to load the custom.json with env variables loaded into it.

**Comment by lauriejim** [comment]
This is fixed in beta version.
