### ISSUE TITLE
Rate limit for both REST and GraphQL

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3206]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Adding in the option for a custom defined rate limit either via requests per hour or via the Leaky Bucket system: https://en.wikipedia.org/wiki/Leaky_bucket.

The goal being to prevent abuse, note that there should also be the option for an "IP Whitelist" that can bypass this limit.

**Comment by lauriejim** [comment]
Thank you for this idea. Can you submit it in ProductBoard please.
We will keep it in PB instead of GitHub.

A policy exist in the users and permission plugin.
Here is how to use it https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/routes.json#L194
Here is the policy https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js

If the config have to be updated, feel free to create a new one based on your need and use this new one in your routes.

**Comment by animatedcreativity** [comment]
> Here is how to use it https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/routes.json#L194

Thanks. Removing the `rateLimit` plugin from policies helped.
Will wait for the feature update though.

**Comment by nick-tw** [comment]
I think this needs to be off by default or made easier to disable.

I just had a backend service run in production and most of our users couldn't log in. I suspect cloudflare is relaying all requests through their own IP and was blocking all requests because it easily hit the rate limit.

**Comment by derrickmehaffy** [comment]
> I just had a backend service run in production and most of our users couldn't log in. I suspect cloudflare is relaying all requests through their own IP and was blocking all requests because it easily hit the rate limit.

That is most likely the case, for the moment I really can't recommend using the cloudflare proxy for the Strapi backend. But the proxy layer sitting between Cloudflare and your Strapi instance (Nginx, Caddy, Traefik, whatever) should able to handle the `X-Forwarded-For` header and Strapi should see that.

**Comment by tlchatt** [comment]
All these github rate limit policy examaple links are broken, cant find info in documentation, can't find an example and urgently need to increase this limit, attempting to automatically put any content into Strapi is goign miserably slow, have to create a bunch of async settimotu functions right now to slow everything.

**Comment by everythinginjs** [comment]
Hey guys I believe that users-permissions rateLimit does not work for graphql endpoint. any solutions ? should I write a custom middlewares via resolvers in the desired mutate ?!

**Comment by everythinginjs** [comment]
BTW, I found a way, although it is working but I am not sure if it is the best way to approach. 
in src/index.js on register method I added something below for Mutation.createInquiry:

```
"use strict";

const { getGraphQLRateLimiter } = require("graphql-rate-limit");

module.exports = {
  register({ strapi }) {
    const rateLimiter = getGraphQLRateLimiter({
      identifyContext: (ctx) => ctx.id,
    });
    const extensionService = strapi.plugin("graphql").service("extension");

    extensionService.use({
      resolversConfig: {
        "Mutation.createInquiry": {
          middlewares: [
            async (next, parent, args, context, info) => {
              const errorMessage = await rateLimiter(
                { parent, args, context, info },
                { max: 2, window: "30s" }
              );
              if (errorMessage) throw new Error(errorMessage);
              return  await next(parent, args, context, info);
            },
          ],
          auth: false,
        },
      },
    });
  },
};
```

I should also note that I used '[graphql-rate-limit(https://github.com/teamplanes/graphql-rate-limit)' package

**Comment by fabianrichter** [comment]
Thanks @everythinginjs for providing a solution. I was looking for something like this since the users-permissons plugin does not seem to work for GraphQL. I think for a temporary solution this should do it, but I am still waiting for a native graphql support.
