### ISSUE TITLE
Admin page load time over 30 seconds

### ISSUE THREAD

**Issue by mariorodriguespt** [strapi/strapi#3208]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**:  6.4.1
- **Strapi version**: trapi v3.0.0-alpha.26.1
- **Database**: Sqlite
- **Operating system**: macOs Mojave

**What is the current behavior?**
I was going throw the restaurant tutorial and at the step `6. Set roles and permissions`, I noticed the page was not loading.

According to the logs the issue lies in loading the internationalisation file:
```
GET /users-permissions/roles/3?lang=en-US (30046 ms)
```
There is one important aspect about this bug: If I switch my internet connection off the problem doesn't happens. I was running strapi in a slow public internet connection, the loading time is caused by it.

The issue seems to be server side.

**Steps to reproduce the problem**

1. Do a fresh Strapi install
2. Make sure you've a bad internet connection or use a HTTP Proxy with throttling to simulate a slow connection. Note: Do not use Chrome Network tools to throttle as it will also throttle the local dev server 
3. Go throw the tutorial

**What is the expected behavior?** Ω
I expect the page to have a decent load time, < 5 seconds ( 5 seconds is a lot when considering I'm running it locally) 

**Suggested solutions** 
I've the impression strapi is calling some URL regarding the translation or maybe something else.

It would be best to make strapi completely independent of being connected to the internet as it becomes really annoying to work with page loads over 30 seconds.

**Comment by derrickmehaffy** [comment]
@mariorodriguespt This has come up in a few other issues: https://github.com/strapi/strapi/issues?q=is%3Aissue+admin+slow+is%3Aclosed

Most of these concerns will be addressed in the beta releases which are slated for release within the next month or so. For now I am marking this as closed as it is a well known issue.
