### ISSUE TITLE
Live Demo on https://demo.strapi.io/admin link broken

### ISSUE THREAD

**Issue by citisolo** [strapi/strapi#3210]
**Informations**
- **Node.js version**: N/A
- **NPM version**: N/A
- **Strapi version**: N/A
- **Database**:  N/A
- **Operating system**:  Ubuntu Bionic
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Link to the live demo (https://demo.strapi.io/admin) producing 502 bad gateway error

**Steps to reproduce the problem**
1. go to https://strapi.io/
2. click the 'Try the live demo' button

**What is the expected behavior?**
To reach the Live Demo

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello! Thank you for this feedback!
It's fixed, issue on hook timeout.

**Comment by soubhikchatterjee** [comment]
Strapi demo link isnt working anymore. Is this on purpose?

**Comment by derrickmehaffy** [comment]
@lauriejim

**Comment by lauriejim** [comment]
This demo app is no longer available.
We switched on Platform.sh to generate requested instance, but due to some issue with their solution we removed it.
We are trying to find a scalable solution for that.
