### ISSUE TITLE
how to remove missing content types in left menu

### ISSUE THREAD

**Issue by newcode365** [strapi/strapi#3211]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: 6.5.0-next.0
- **Strapi version**: 3.0.0 alpha 26.1
- **Database**: postgres 9.5
- **Operating system**: ubuntu 16.04.5 LTS

**What is the current behavior?**
There is a missing content-types in left menu

**Steps to reproduce the problem**
1. create new content-type
2. change name & collection name (same word)
or insert digits on name, I don't remember exactly
3. click save & server crash!
4. can't restart server
5. remove wrong tables with pgAdmin manually
6. start server
7. items of content-type-builder is correct
8. but still can see missing content-type in left menu

**Suggested solutions**

How to refresh left menu items ? or fix?

**Comment by derrickmehaffy** [comment]
@newcode365 delete the `plugin_content-manager_schema entry in `core_store` on your database (can't do this from the adminUI, use a DB client)

Then restart your server

**Comment by lauriejim** [comment]
Hello!
I create a new app and your both step 2 works.
I m not able to reproduce your issue.

**Comment by newcode365** [comment]
> @newcode365 delete the `plugin_content-manager_schema entry in `core_store` on your database (can't do this from the adminUI, use a DB client)
> 
> Then restart your server

it works, thanks

**Comment by newcode365** [comment]
> Hello!
> I create a new app and your both step 2 works.
> I m not able to reproduce your issue.

Hello!
I can reproduce when I change name of content-type to camelcase

ex)
1. create content-type = 'test' -> save
2. change this name = 'testA' -> save
3. restart server
4. you may see 2 items in left menu and 1 item in content-type-builder
that can't remove with 'an error occured'

**Comment by lauriejim** [comment]
I'm not able to reproduce with a fresh install of `alpha.26.2`

**Comment by newcode365** [comment]
![Screen Shot 2019-05-07 at 10 12 13](https://user-images.githubusercontent.com/48101203/57265629-8ab3b200-70b3-11e9-88e0-4bca3a33a250.png)
![Screen Shot 2019-05-07 at 10 14 03](https://user-images.githubusercontent.com/48101203/57265630-8ab3b200-70b3-11e9-8553-478169ad61eb.png)
![Screen Shot 2019-05-07 at 10 14 21](https://user-images.githubusercontent.com/48101203/57265631-8b4c4880-70b3-11e9-919b-ec6d7cfaba09.png)
![Screen Shot 2019-05-07 at 10 14 34](https://user-images.githubusercontent.com/48101203/57265632-8b4c4880-70b3-11e9-9502-3909cc4a7656.png)
![Screen Shot 2019-05-07 at 10 14 49](https://user-images.githubusercontent.com/48101203/57265633-8b4c4880-70b3-11e9-8daf-19b1b143284a.png)
![Screen Shot 2019-05-07 at 10 15 40](https://user-images.githubusercontent.com/48101203/57265634-8be4df00-70b3-11e9-95f0-01d447c2b5d9.png)
![Screen Shot 2019-05-07 at 10 24 52](https://user-images.githubusercontent.com/48101203/57265635-8be4df00-70b3-11e9-9f96-7b41acc1b446.png)

fresh install tested on alpha 26.2

**Comment by newcode365** [comment]
![Screen Shot 2019-05-07 at 10 12 13](https://user-images.githubusercontent.com/48101203/57265954-ddda3480-70b4-11e9-9d60-07a561a6e068.png)
![Screen Shot 2019-05-07 at 10 14 03](https://user-images.githubusercontent.com/48101203/57265955-ddda3480-70b4-11e9-8b79-245366cbcd24.png)
![Screen Shot 2019-05-07 at 10 14 21](https://user-images.githubusercontent.com/48101203/57265956-de72cb00-70b4-11e9-8a11-728e838dd3be.png)
![Screen Shot 2019-05-07 at 10 14 34](https://user-images.githubusercontent.com/48101203/57265957-de72cb00-70b4-11e9-82bd-8e90ea56629a.png)
![Screen Shot 2019-05-07 at 10 14 49](https://user-images.githubusercontent.com/48101203/57265958-de72cb00-70b4-11e9-8248-9b941325dba3.png)
![Screen Shot 2019-05-07 at 10 15 40](https://user-images.githubusercontent.com/48101203/57265960-df0b6180-70b4-11e9-9ba6-8abf15417223.png)
![Screen Shot 2019-05-07 at 10 24 52](https://user-images.githubusercontent.com/48101203/57265961-df0b6180-70b4-11e9-87d2-e40b4375326f.png)

fresh install tested on alpha 26.2

**Comment by derrickmehaffy** [comment]
@newcode365 camelCase isn't supported.

https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#model--field-naming-schemes

**Comment by newcode365** [comment]
@derrickmehaffy oh really? thanks

**Comment by subwaymatch** [comment]
@derrickmehaffy Thanks for the fix to delete `plugin_content-manager_schema`. I've been suffering for a few hours until I finally arrived here and can't express how relieved I am.
