### ISSUE TITLE
strapi-provider-upload-aws-s3 upload send region: null 

### ISSUE THREAD

**Issue by Kishor-Kumar-Namdeo** [strapi/strapi#3212]
**Informations**
- **Node.js version**: 10.0.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2

- **Database**: mongodb
- **Operating system**: mac 
- **(Optional) Link to your Project**: 

**What is the current behavior?**

when i upload image from file upload then send 500 response

**Steps to reproduce the problem**

**What is the expected behavior?**

should be uploaded in aws server
![Screenshot 2019-05-02 at 1 06 59 PM](https://user-images.githubusercontent.com/38028353/57061644-456e3980-6cdb-11e9-8200-0dca3a939060.png)
![Screenshot 2019-05-02 at 1 08 41 PM](https://user-images.githubusercontent.com/38028353/57061769-c299ae80-6cdb-11e9-8e9b-25abc71503f7.png)

**Suggested solutions**

**Comment by derrickmehaffy** [comment]
> **Informations**
> 
> * **Node.js version**:
> * **NPM version**:
> * **Strapi version**:
> * **Database**:
> * **Operating system**:
> * **(Optional) Link to your Project**:

Please fill out the required template, after you have filled out the template correctly reply back and this issue can be reopened.

`<!-- ⚠️ If you do not respect this template your issue will be closed. -->`

**Comment by Kishor-Kumar-Namdeo** [comment]
Required template details updated, now help me.

**Comment by derrickmehaffy** [comment]
> now help me

Careful man, that is kinda rude and goes against the https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md

See my reply in Slack:

![image](https://user-images.githubusercontent.com/8593673/57068761-8177af00-6c87-11e9-978e-38a7cf9718bf.png)

![image](https://user-images.githubusercontent.com/8593673/57068776-8d637100-6c87-11e9-9595-52677a21c89c.png)

**Comment by Kishor-Kumar-Namdeo** [comment]
@derrickmehaffy 

i update version but its not working. 
here is my package.json 
```{
  "name": "server",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application.",
  "main": "./server.js",
  "scripts": {
    "setup": "cd admin && npm run setup",
    "dev": "node server.js",
    "start": "NODE_ENV=production node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "lodash": "^4.17.5",
    "strapi": "^3.0.0-alpha.26.1",
    "strapi-email-nodemailer-gmail": "^0.0.1",
    "strapi-hook-mongoose": "^3.0.0-alpha.26.1",
    "strapi-provider-upload-aws-s3": "^3.0.0-alpha.26.1"
  },
  "author": {
    "name": "kishor",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "kishor",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "packageManager": "npm",
    "uuid": "f7acb5f2-eef5-415d-80b5-af9e41981f43"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}
```

can you please check that, whats going wrong

**Comment by derrickmehaffy** [comment]
@Kishor-Kumar-Namdeo check with a fresh new project. Updating between versions is not as simple as changing the version number in the package.json

**Comment by lauriejim** [comment]
Hello! I just created a new app with last version of Strapi (alpha.26.1) and I installed this provider.
I set all configuration and I was able to upload files.

**Comment by hallya** [comment]
@lauriejim , I'm having the same issue.

Just to confirmed, to be working we should:

- Have strapi's version higher or equal to `strapi-provider-upload-aws-s3`
- Fill user aws accessId key and secret key
- Fill bucket with bucket name (not arn)

**Comment by hallya** [comment]
Alright I have my answer. 

Problem was in bucket's permissions. 

To have it work and be as secured as possible I had to set every (as it is by default) options to true except for the first one to be allowed to upload file, and the second to be allowed to download it.

I hope this will help others

**Comment by Kishor-Kumar-Namdeo** [comment]
i have created new project but giving same error, here my new package.json file
```{
  "name": "mysqltest",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application.",
  "main": "./server.js",
  "scripts": {
    "setup": "cd admin && npm run setup",
    "start": "node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "mysql": "2.17.1",
    "strapi": "3.0.0-alpha.26.1",
    "strapi-hook-bookshelf": "3.0.0-alpha.26.1",
    "strapi-hook-knex": "3.0.0-alpha.26.1",
    "strapi-provider-upload-aws-s3": "^3.0.0-alpha.26.2",
    "strapi-utils": "3.0.0-alpha.26.1"
  },
  "author": {
    "name": "kishor",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "kishor",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "packageManager": "npm",
    "uuid": "1de85abe-a8fe-4909-a77d-28d13351ff87"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}
```

**Comment by lauriejim** [comment]
@Kishor-Kumar-Namdeo did you check your Bucket permissions as @hallya said ?

**Comment by Kishor-Kumar-Namdeo** [comment]
@lauriejim yes, i have checked bucket permissions and all is fine there, no issue related permission in AWS.

**Comment by lauriejim** [comment]
I tried again and work, @hallya made it works too so I think the feature work well.
You error is `Access Denied` so it come from your AWS permission or your AWS credentials you set in the Strapi provider configuration.

**Comment by yusuke-kogawa** [comment]
FYI: 
I had same error. and I resolved by update S3 permissions.

strapi-provider-upload-aws-s3 module upload file with hard-coded permission `public-read`.
This means you should set s3 "Block public access" to off .

S3 management console
 -> "Permissions" tab
 -> "Block public access"
 -> "granted through ACLs" settings set to Off

**Comment by iedmrc** [comment]
> FYI:
> I had same error. and I resolved by update S3 permissions.
> 
> strapi-provider-upload-aws-s3 module upload file with hard-coded permission `public-read`.
> This means you should set s3 "Block public access" to off .
> 
> S3 management console
> -> "Permissions" tab
> -> "Block public access"
> -> "granted through ACLs" settings set to Off
> 
> Be careful, you should not set unnecessary permissions to s3.

My problem was the same as that. I solved it via using https://www.npmjs.com/package/strapi-provider-upload-aws-s3-ext rather than the official one.

**Comment by clorichel** [comment]
For the record, be aware the strapi-provider-upload-aws-s3 (as of `3.0.0-beta.18.8`) is indeed sending `ACL: 'public-read'` upon file upload. There is no need to use another plugin just for that reason though: the only thing needed as a consequence is to add the `s3:PutObjectAcl` permission to let that happen.

Here is the complete policy that needs to be attached to the IAM user from which you'll use the access key in the strapi plugin configuration:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowBucketActions",
            "Effect": "Allow",
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::your-s3-bucket"
        },
        {
            "Sid": "AllowObjectsActions",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::your-s3-bucket/*"
        }
    ]
}
```

Replace `your-s3-bucket` with whatever your bucket name is. Be aware `s3:ListBucket` resource in the first statement is limited to the bucket ARN, and the objects permissions are limited to ALL of the objects in the bucket ARN (ie do NOT miss the `/*` at the end of the second statement!).

**Comment by saksham-kapoor** [comment]
@clorichel Hi, where exactly do i have to add this piece of code? I'm fairly new to this, please help me out.

**Comment by bober2000** [comment]
@saksham-kapoor you should go to your AWS IAM user settings - Permissions - Add permissions- Attach existing policies directly - Create policy - Insert that code and name the policy
