### ISSUE TITLE
Generate valid token in custom way

### ISSUE THREAD

**Issue by amiiy** [strapi/strapi#3213]
I have some users who have no password. I want to authenticate them by passing an OTP code. for example, a user came to the registration form and enter her info with the phone number, then an otp code sends to that phone number and if user post that code with the phone number, the user will receive and jwt token and assume logged in. 
I don't know how to implement this workflow with strapi. I thought if I know how to generate a valid token, I can put an API call which does this.

**Comment by lauriejim** [comment]
Hello! I suggest you to create a new API with custom routes/controllers/services that manage this use case.
Run `strapi generate:api authotp` then clean your routes/controllers/service and create functions you need to your auth workflow.
You can check the user permission plugin Auth controller to see how current auth workflow work and use service that exist to update users.
