### ISSUE TITLE
XSRF cookie not being set / how to expose the CSRF token?

### ISSUE THREAD

**Issue by SFlame** [strapi/strapi#3214]
**Informations**
- **Node.js version**: 10.2.1
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26
- **Database**: MongoDB (Atlas)
- **Operating system**: Windows

**What is the current behavior?**

I can't access the CSRF/XSRF token in any way.
XSRF cookie is not being set and documentation about how to use Strapi CSRF token are lack/non-existing.

**Steps to reproduce the problem**

It's just not set any cookie and I can't get the current CSRF token in any way.

**What is the expected behavior?**

To be able to access the current CSRF token.

**Suggested solutions**

Improve documentation and fix the XSRF cookie (which is not being set at all).

**Comment by SeedyROM** [comment]
There is no CSRF/XSRF protection in strapi. So, yeah that might be why it's not documented.

**Comment by SFlame** [comment]
> There is no CSRF/XSRF protection in strapi. So, yeah that might be why it's not documented.

So what is it?

https://strapi.io/documentation/1.x.x/configuration.html#security (look for CSRF)

and:

![image](https://user-images.githubusercontent.com/22399885/57176078-103d2500-6e5c-11e9-9eab-c39de9f69308.png)

Once it's turned on, every request but GET will return 403 error: CSRF token mismatch.

**Comment by SeedyROM** [comment]
Nevermind, I never even saw this

**Comment by lauriejim** [comment]
Hello! please check the documentation of `lusca` we use this *node_module* to manage the security.
https://github.com/krakenjs/lusca#luscacsrfoptions
And also check the angular option.
