### ISSUE TITLE
Self referencing content types many to many with the same attribute name

### ISSUE THREAD

**Issue by fonzzzde** [strapi/strapi#3216]
**Informations**
- **Node.js version**: 10.15.2
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.1
- **Database**: mysql
- **Operating system**: centos
- **(Optional) Link to your Project**: 

**What is the current behavior?**

This is related to https://github.com/strapi/strapi/issues/2185, which was fixed in alpha.26.1
However, it does not seem to be possible to create an associated list of items of the same content types in a straightforward way.
I have a type 'Article' and would like to create a relation with other (related) articles. So I would like a many-to-many from Article/articles to Article/articles ( but this can't be done, it says "value already exists" when trying to save.

You can achieve it by introducing a new field ( for instance related_to ), but this field will be visible on the Article input/edit form, which is very confusing. (And hard to explain to non technical users). I would like to see just the option to add related articles. And this also leads to 2 SQL linking tables, while only one should be required.

**Steps to reproduce the problem**

Create type Article.
Add relation to list of related Articles

**What is the expected behavior?**

A many-to-many from Article/articles to Article/articles should just work with 1 SQL linking table, like it does for non-self many-to-many relations.

**Suggested solutions**

It looks like the only problem why the simple solution does not work is that the link table contains the field 'article_id' twice. With a name for the relation the second field could be named something like "related_article_id" or something ....

**Comment by lauriejim** [comment]
Hello! Thank you for this feedback.
Self referencing works when there is a notion of parent/children. 
So two different attributes name.

**Comment by Gusterson** [comment]
I don't see how the above commit closes this issue? I still have to have two columns on my data to self-reference? The issues presented by the OP remain the same:

 1) the second field will be visible on the Article input/edit form, which is very confusing. (And hard to explain to non technical users)
 1) This also leads to 2 SQL linking tables, while only one should be required
 ```
 CREATE TABLE articles_articles (
    article_id1 INT NOT NULL,
    article_id2 INT NOT NULL), 
    CONSTRAINT pk_article_article PRIMARY KEY (article_id1, article_id2);
 ```
 3) It's just kind of sloppy...
