### ISSUE TITLE
Setup Cloudfront url for AWS S3 provider

### ISSUE THREAD

**Issue by quangchien** [strapi/strapi#3218]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Hi, I have installed strapi-provider-upload-aws-s3 and uploaded file to s3 successfully but is there any way we can change the link to cloudfront instead of using s3 ?

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
I close this issue.
For this need, please set it in your front end application.

**Comment by rmaroun** [comment]
@lauriejim I have updated the upload provider to take into account cloudfront. You can configure if you wish or not to deliver the assets via cloudfront and fill in the URL and what happens then when uploading is that we store the cloudfront URL in the database and this how the screen looks like. Would that be an idea to submit a PR to have this available in strapi s3 provider?

![image](https://user-images.githubusercontent.com/4890827/74339290-16294480-4da4-11ea-9939-6bae8957f2df.png)

**Comment by lauriejim** [comment]
Thank you for submitting a PR, I will check that soon as possible.

**Comment by rmaroun** [comment]
@lauriejim you can review the PR here https://github.com/strapi/strapi/pull/5237

**Comment by B1Z1** [comment]
@rmaroun What about new version of strapi. Because settings button is hidden

**Comment by ScottEAdams** [comment]
If you want a quick way to use a cdn (i.e. cloudfront) instead of s3 urls in strapi 3, just set up a custom provider.

providers/strapi-provider-upload-aws-s3-cdn/package.json
```
{
  "name": "strapi-provider-upload-aws-s3-cdn",
  "version": "0.0.1",
  "description": "AWS S3 provider for strapi upload with cdn (cloudfront)",
  "directories": {
    "lib": "./lib"
  },
  "main": "./lib",
  "dependencies": {
    "aws-sdk": "^2.713.0",
    "lodash": "^4.17.19"
  },
  "strapi": {
    "isProvider": true
  },
  "engines": {
    "node": ">=10.10.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT",
  "scripts": {
    "test": "echo \"no tests yet\""
  }
}
`
``

providers/strapi-provider-upload-aws-s3-cdn/lib/index.js
```
'use strict'
// https://strapi.io/documentation/v3.x/plugins/upload.html#create-providers
// Copy of strapi-provider-upload-aws-s3 but uses cdn (i.e. cloudfront)
// https://github.com/strapi/strapi/tree/master/packages/strapi-provider-upload-aws-s3
/**
 * Module dependencies
 */

/* eslint-disable no-unused-vars */
// Public node modules.
const _ = require('lodash')
const AWS = require('aws-sdk')

module.exports = {
  init(config) {
    const S3 = new AWS.S3({
      apiVersion: '2006-03-01',
      ...config,
    })

    return {
      upload(file, customParams = {}) {
        return new Promise((resolve, reject) => {
          // upload file on S3 bucket
          const path = file.path ? `${file.path}/` : ''
          S3.upload(
            {
              Key: `${path}${file.hash}${file.ext}`,
              Body: Buffer.from(file.buffer, 'binary'),
              ACL: 'public-read',
              ContentType: file.mime,
              ...customParams,
            },
            (err, data) => {
              if (err) {
                return reject(err)
              }

              // set the bucket file url
              if (config.cdn) {
                file.url = `${config.cdn}${data.Key}`
              } else {
                file.url = data.Location
              }

              resolve()
            }
          )
        })
      },
      delete(file, customParams = {}) {
        return new Promise((resolve, reject) => {
          // delete file on S3 bucket
          const path = file.path ? `${file.path}/` : ''
          S3.deleteObject(
            {
              Key: `${path}${file.hash}${file.ext}`,
              ...customParams,
            },
            (err, data) => {
              if (err) {
                return reject(err)
              }

              resolve()
            }
          )
        })
      },
    }
  },
}
```

config/plugins.js
```
module.exports = ({env}) => ({
  upload: {
    provider: 'aws-s3-cdn',
    providerOptions: {
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_ACCESS_SECRET'),
      region: env('AWS_REGION'),
      params: {
        Bucket: env('AWS_BUCKET'),
      },
      cdn: env('CLOUDFRONT')
    },
  }
})
```

**Comment by derrickmehaffy** [comment]
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.
