### ISSUE TITLE
ERROR: Registry editing has been disabled by your administrator.

### ISSUE THREAD

**Issue by BeardDude** [strapi/strapi#3219]
**Informations**
- **Node.js version**: 10.1.0 
- **NPM version**: 6.4.1 
- **Strapi version**: 3.0.0-alpha.26.1 
- **Database**: MongoDb 
- **Operating system**: Windows 10

**What is the current behavior?**

on executing `strapi new project_name` runs into the below error

ERROR: Registry editing has been disabled by your administrator.
child_process.js:636
    throw err;
    ^
Error: Command failed: %windir%\System32\REG QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid
ERROR: Registry editing has been disabled by your administrator.

    at checkExecSyncError (child_process.js:596:11)
    at execSync (child_process.js:633:13)
    at u (C:\npm\node_modules\strapi\node_modules\node-machine-id\dist\index.js:1:7425)
    at trackSuccess

**Steps to reproduce the problem**
Run `strapi new project_name` from a non-admin account

**What is the expected behavior?**
The project should get bootstrapped

**Suggested solutions**
Wondering why `node-machine-id` is used and also why it isn't working in non-administrative account though it claims to work.

**Comment by derrickmehaffy** [comment]
@BeardDude 

`QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography /v MachineGuid`

ERROR: Registry editing has been disabled by your administrator.

I would talk to your system admin. This isn't a problem with Strapi, this is done by a package dependency, typically the MachineGuid is used during encryption. 

Marking as closed as not an issue with Strapi

**Comment by sshanzel** [comment]
I think this should be reconsidered. In my scenario, we actually have very strict security protocols for Company's machines. Hence, being unable to push further in allowing viewing of the registry.

Should Strapi allow some alternative to use some other basis for the key to be used in the encryption process? Our team is actually thinking to push this forward and use it for company purposes but being blocked by this concern.

**Comment by derrickmehaffy** [comment]
@sshanzel in your package.json, remove the Strapi key + object as documented here: https://strapi.io/documentation/developer-docs/latest/getting-started/usage-information.html

See if that fixes the issue, as I believe it's caused by our telemetry system.

**Comment by sshanzel** [comment]
Unfortunately, I am still suffering from the same issue 😢

![image](https://user-images.githubusercontent.com/13744167/112271103-f4330e80-8c93-11eb-8606-70b3b179ec47.png)

My actual package.json:
![image](https://user-images.githubusercontent.com/13744167/112271182-0a40cf00-8c94-11eb-8000-6eaebfd51069.png)

**Comment by derrickmehaffy** [comment]
I've tentatively reopened this to let the engineering team take a look but this really does reach beyond the Strapi application in general. Simply reading a value from the Windows registry, specifically `QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography` is not a major security risk so I'm not sure why your systems team would lock down your system that much, especially on a developer system.

**Comment by derrickmehaffy** [comment]
There is specifically only one key in that parent: 
![image](https://user-images.githubusercontent.com/8593673/112884976-042c6300-9085-11eb-8ce6-2614aaf41202.png)

And the child keys are basically empty minus the UserInterface which points to a crypt library dll.

**Comment by sshanzel** [comment]
Hi @derrickmehaffy,

We really appreciate you taking the extra mile to have a resolution on this manner. That's actually the part we really don't understand, why developers are having these restrictive measures when in fact it just hinders the development. Unfortunately, the company has strict protocols applied across their different domains and the probability to get this through is highly unlikely.

Again, thank you so much for the time and effort, especially in making this project as wonderful as it is.

**Comment by derrickmehaffy** [comment]
The part that gets to me, and why I think your company might actually have a bug in their Active Directory policies, is due to the actual error message:

`Registry editing has been disabled` but we are not editing your registry, we are simply reading a key. This is normal and literally thousands of enterprise grade applications rely on reading that GUID to generate a fingerprint of the system. I can promise almost anything that has an option to send debug information to the author of the software (including Microsoft) would need access to this key.

**Comment by derrickmehaffy** [comment]
Related upstream issue: https://github.com/automation-stack/node-machine-id/issues/27

**Comment by sshanzel** [comment]
I see. It seems, things should be mentioned on the upstream you have mentioned. Thanks for the reference!

**Comment by derrickmehaffy** [comment]
Marking as closed due to upstream issue.

**Comment by ldcaponi** [comment]
I ran into this issue when running locally on a company windows machine.  For a quick fix I removed the `machineIdSync` function calls in `node_modules\strapi\lib\services\metrics\sender.js`.

I believe a PR could be made to remove any reference to this function when UUID is removed from `package.json` or telemetry is disabled.

Thanks for the great work!

**Comment by sshanzel** [comment]
> I ran into this issue when running locally on a company windows machine. For a quick fix I removed the `machineIdSync` function calls in `node_modules\strapi\lib\services\metrics\sender.js`.
> 
> I believe a PR could be made to remove any reference to this function when UUID is removed from `package.json` or telemetry is disabled.
> 
> Thanks for the great work!

Yes. Currently, removing the UUID is not working as it is supposed to be (ignore the functions you have mentioned.
