### ISSUE TITLE
which directory should I put some translated docs?

### ISSUE THREAD

**Issue by fpetrouchka** [strapi/strapi#3220]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
well I'm about to translate Strapi's official docs and want to place it somewhere on repo, so which directory is most suitable for? Thanks.

**Comment by davidkartuzinski** [comment]
@fpetrouchka - Hello. We should coordinate! I am the Dev Advocate here.  What language are you going to translate to? We should coordinate as some of the docs are being rewritten... 

Are you in the Slack Channel?

-DK

**Comment by fpetrouchka** [comment]
@davidkartuzinski Hi, thanks for reply! I'm planning to translate docs to Japanese.
But for now if original docs are to be rewritten as you said, I'd see how it goes for a while.
I'm in slack channel w/ same display name. Would it be better if I make any suggestion in there?

**Comment by davidkartuzinski** [comment]
@fpetrouchka - This is fine. I found you on Slack. @lauriejim - can also respond to you here. But yes, basically with Beta being released soon, much of the doc is being rewritten.

**Comment by lauriejim** [comment]
Hello! Here is how we can translate the documentation with **vuepress** (that is the solution we use)
As @davidkartuzinski said we have to rewrite a large part of the documentation because of the `beta` version. So I suggest to wait for the `beta` before working on this point.

**Comment by fpetrouchka** [comment]
@lauriejim thanks, I'll do so && get familiar to some of vuepress until beta things come.
Please let me contribute at that time ;)
