### ISSUE TITLE
Cant login to Strapi studio - email is case sensitive

### ISSUE THREAD

**Issue by yoDon** [strapi/strapi#3221]
**Informations**
- **Node.js version**: Strapi Studio
- **NPM version**: Strapi Studio
- **Strapi version**: Strapi Studio
- **Database**: Strapi Studio
- **Operating system**: Strapi Studio
- **(Optional) Link to your Project**: 

**What is the current behavior?**

Login email addresses in strapi studio are case sensitive. Case sensitive email addresses are a bug that can prevent users from logging in.

**Steps to reproduce the problem**

1) Register as a new user with a capital letter in your email address (eg. newUser@outlook.com or newuser@Outlook.com)
2) Click on the confirmation link to confirm the account
3) Attempt to log in to the new account without including capital letters in your email address (eg. newuser@outlook.com) OR use the email auto-fill feature in chrome which is aware that email addresses are not case sensitive and which will default to all lowercase if you have previously used that email in an all lowercase form on another site
4)  See the alert from strapi studio that the login has failed

**What is the expected behavior?**

Login should succeed because email addresses should be case sensitive

**Suggested solutions**

1) You already fixed an essentially identical issue for strapi installations in https://github.com/strapi/strapi/issues/1557 I recommend applying that fix or a similar fix to strapi studio
2) users who figure out that something is up with case sensitivity and uppercase and lowercase letters in their email address and who find this issue report can work around it by logging in with the appropriate capital letters (hopefully you remember or can guess where they are) and then go to your profile page in strapi studio to change your email address to be all lowercase (after which you will of course only be able to log in with the email as all lowercase, until Strapi fixes the case sensitivity issue).

**Comment by derrickmehaffy** [comment]
@yoDon strapi studio is from v1 which is no longer maintained, you will need to use Strapi v3 (current sub version is v26.2)

Marking as closed as studio is no longer supported
