### ISSUE TITLE
npx strapi new fails on Python errors

### ISSUE THREAD

**Issue by yoDon** [strapi/strapi#3222]
**Informations**
- **Node.js version**:  10.15.3
- **NPM version**: 6.5.0
- **Strapi version**:  yes using npx to try to strapi new or strapi login
- **Database**: not yet configured
- **Operating system**: Win10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

npx strapi new and npx strapi login both report Python errors. npx strapi new then fails, npx strapi login succeeds.

**Steps to reproduce the problem**

1) run VS Code on Windows
2) run either `npx strapi login` or `npx strapi new`
3) see Python Anaconda error spew in console window (note: VS Code defaults to powershell terminal editor on windows and powershell is not compatible with Anaconda - when running anaconda you must run from an old-school cmd prompt. I have however tried to npx strapi new from both powershell and cmd terminals and I get the same result).  
4) After the error spew prints strapi new does not ask for additional configuration data, it simply reports the the application is ready (in my case I know it can't be as I don't have a database installed, haven't configured one, and didn't have an opportunity to request a sqlite install which was my plan). Strapi login appears to succeed.

```
npx strapi login
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\.....username.....\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\.....username.....\AppData\Roaming\npm-cache\_npx\4700\node_modules\strapi\node_modules\bufferutil
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\......username.....\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\.....username.....\AppData\Roaming\npm-cache\_npx\4700\node_modules\strapi\node_modules\utf-8-validate
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
your Strapi email address
```

**What is the expected behavior?**

no Python errors followed by strapi asking me how I want to configure my new application

**Suggested solutions**

Because npx is guaranteed to pull down a current copy of strapi each time, it is a better an more reliable way of running strapi than using a global install which is likely to become out of date in ways that don't show up in the user's project.json file. For this reason it is important to support npx strapi operations.

**Comment by yoDon** [comment]
I've also tried to npm install -g strapi, which results in a completely different set of errors having nothing to do with Python, as reported in https://github.com/strapi/strapi/issues/3223

**Comment by alexandrebodin** [comment]
Hi,

Strapi must be used with the alpha version. You can read about it [here](https://strapi.io/documentation/3.x.x/getting-started/quick-start.html)

**Comment by martindotslash** [comment]
Go this when I installed latest version of Node.js. 14.5.0 had to uninstall node and run Strapi using Yarn and Vs code terminal. might work with Node.js 12.18.

**Comment by martindotslash** [comment]
> **Informations**
> 
> * **Node.js version**:  10.15.3
> * **NPM version**: 6.5.0
> * **Strapi version**:  yes using npx to try to strapi new or strapi login
> * **Database**: not yet configured
> * **Operating system**: Win10
> * **(Optional) Link to your Project**:
> 
> **What is the current behavior?**
> 
> npx strapi new and npx strapi login both report Python errors. npx strapi new then fails, npx strapi login succeeds.
> 
> **Steps to reproduce the problem**
> 
> 1. run VS Code on Windows
> 2. run either `npx strapi login` or `npx strapi new`
> 3. see Python Anaconda error spew in console window (note: VS Code defaults to powershell terminal editor on windows and powershell is not compatible with Anaconda - when running anaconda you must run from an old-school cmd prompt. I have however tried to npx strapi new from both powershell and cmd terminals and I get the same result).
> 4. After the error spew prints strapi new does not ask for additional configuration data, it simply reports the the application is ready (in my case I know it can't be as I don't have a database installed, haven't configured one, and didn't have an opportunity to request a sqlite install which was my plan). Strapi login appears to succeed.
> 
> ```
> npx strapi login
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\.....username.....\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\.....username.....\AppData\Roaming\npm-cache\_npx\4700\node_modules\strapi\node_modules\bufferutil
> gyp ERR! node -v v10.15.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\......username.....\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\.....username.....\AppData\Roaming\npm-cache\_npx\4700\node_modules\strapi\node_modules\utf-8-validate
> gyp ERR! node -v v10.15.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> your Strapi email address
> ```
> 
> **What is the expected behavior?**
> 
> no Python errors followed by strapi asking me how I want to configure my new application
> 
> **Suggested solutions**
> 
> Because npx is guaranteed to pull down a current copy of strapi each time, it is a better an more reliable way of running strapi than using a global install which is likely to become out of date in ways that don't show up in the user's project.json file. For this reason it is important to support npx strapi operations.

Got this when I installed latest version of Node.js. 14.5.0 had to uninstall node and run Strapi using Yarn and Vs code terminal. might works with Node.js 12.18.
