### ISSUE TITLE
Missing content type after restart, needs a manual restart

### ISSUE THREAD

**Issue by lexoyo** [strapi/strapi#3225]
**Informations**
- **Node.js version**: 10.2.1
- **NPM version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: 
- **Operating system**: linux fedora 

**What is the current behavior?**

After I create a content type and strapi restarted, I see the content type in the side bar but not in the content type editor

It does not happen all the time, only sometimes (tested 5 times and had the bug 2 times) 

**Steps to reproduce the problem**

1- create a content type
2- save, strapi restarts
3- got back to content type builder

**What is the expected behavior?**

See the content type in content type builder

**Suggested solutions**

A workaround is to restart strapi by hand

**Comment by lauriejim** [comment]
Hello! Can you tell me how did you strapi your strapi application (the command you use)
and can you update your issue to add the database you use please.

**Comment by lexoyo** [comment]
Hi,
Thank you for your answer
I followed the starter guide so the default database and strapi start

**Comment by Gribbs** [comment]
Me too. I start with `yarn start` and using default database.
I should note I created a new project with `npx strapi@alpha new mob-app` since I am using node v11.x

**Comment by derrickmehaffy** [comment]
@Gribbs Node 11 isn't support and won't be, next is node 12 and work on that is ongoing. You should use node 10

**Comment by lauriejim** [comment]
Hello!
In the `alpha` version of Strapi you have to start your application with `strapi start` to be able to have the auto restart.
If you use `npm start` or `yarn start` you will have to manually restart your application.

In the `beta` version of Strapi. We set a message to tell you to use the correct command line to have access to this feature.

**Comment by Gribbs** [comment]
> @Gribbs Node 11 isn't support and won't be, next is node 12 and work on that is ongoing. You should use node 10

It seems to work otherwise. I followed the recommendation [here](https://github.com/strapi/strapi/issues/1550#issuecomment-416872757) . I agree with this [comment](https://github.com/strapi/strapi/issues/1550#issuecomment-495042135) . To add to that, I'd sooner have to stop and start the server than downgrade the Node version globally on my local machine just for Strapi. I guess it's possible to use nvm somehow but I can't work it out. I'll live with stop and start for now

**Comment by CalvinTsui** [comment]
"strapi start" works for me, thanks
