### ISSUE TITLE
Relations between objets removes at save time

### ISSUE THREAD

**Issue by omarnoir** [strapi/strapi#3227]
Node v10.15.3
npm 6.9.0
strapi 3.0.0-alpha.26

**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26
- **Database**: Mongodb
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
When I add and save a relation between 2 differents content type, all other relations are removed.

**Steps to reproduce the problem**
Create 4 content types.
Add relation attributes between 1 content towards the 3 others (no matter which relation type). 
Create 1 entry of each content types.
Add 2 relations to the first entry and save.
Add an new relation towards the last entry, the to others will be removed. 

Each time, only configurated relations are saved and other relations previously configured are removed.

**What is the expected behavior?**
Relations previously configured should stay saved when I configure a new one.

**Suggested solutions**
no solution suggested...

**Comment by derrickmehaffy** [comment]
@omarnoir please test with the latest version `Strapi version: 3.0.0-alpha.26` -> `Strapi version: 3.0.0-alpha.26.2`

**Comment by lauriejim** [comment]
Please can you give me **exact** content type and relations you created.
**exact** entry you created and relations you did in your data.

Your steps are not clear to be able to reproduce your issue exactly.

**Comment by omarnoir** [comment]
Thanks for your reactivity.

I did the update with the last version (3.0.0-alpha.26.2) But I still got the same issue.
For my dev, I am using the quickstart to create my test API.

More explenations : 
I try to gather all informations of my clients and their computers with strapi. 
Data will be extracted through the Graphql API (official plugin installed) and displayed in a webapp.

I have 5 content-types 

**1. Computeur** 
Fields : name, hostname, user, etc...
A relation 1-N with company
A relation 1-1 with adress

**2. Contact** 
Fields : name, mail, phone, address, etc... 
A relation N-1 whis company

**3. Adresse** 
Fields : string name, bool isprincipal, string add, string cp, string city, etc.. 
A relation N-1 with company
A relation 1-1 with computer (already mentionned before)  

**4. internal contact**  
Fields : name, mail, phone, etc...
A relation N-1 with company

**5. company **
Fields : string name, media logo, string phone, mail mail, etc...
So company have relation 
**--> 1-N with computers
--> 1-N with contacts
--> 1-N with addresses
--> 1-N with internal contacts**

With all of this, step to get my issue : 
1/ create a company without the relation fields and save
2/ create a computer, a contact, an address and a company contact and save
3/ from the company edit page, create a relation between the company and an address for exemple and save
4/ from the company edit page, create a relation between the company and a contact and save, the priviously relation with address is delated.
5/ from the company edit page, create a relation between the company and the internal contact & the computer and save, the priviously relation with the contact is delated.

As I Said, this problem is still present with the 3.0.0-alpha.26.2.
It was present in the 3.0.0-alpha.26 and another previous version.

@derrickmehaffy & @lauriejim, is it more understandable ?

**Comment by derrickmehaffy** [comment]
@omarnoir much more, I'll test it with MySQL (I know you are on mongo and I'm wondering if there are more issues with mongo)

Do you have a copy of your project somewhere like github or gitlab you can link?

**Comment by omarnoir** [comment]
I restart my tests with new instance of strapi.
Version used : 3.0.0-alpha.26.2
Plugin : graphql
Node.js version: v10.15.3
NPM version: 6.9.0
Database: Mongodb
Operating system: Ubuntu 18.04

company
         name (string)
         phone (string)
         mail (e-mail)
          logo (media)

pc
	name (string)
	hostname (string)
	user (string)
	isindomain (booleen)
        Relation 1-1 with company

companycontact
	surname (string)
	firstname (string)
	job (string)
	mobilephone (string)
	phone (string)
	mail  (e-mail)
        Relation 1-1 with company

tibs 
	surname (string)
	firstname (string)
	job (string)
	mail (e-mail)
	mobilephone (string)
	phone (string)
	zone (string)
        Relation 1-1 with company

I have created 2 companies, 2 companycontacts, 2 tibs, and 2 pcs
At this time, when I save a modification in relations betwenn company and other content type, no problems.

But when I change the relation type between companies and pcs from 1-1 to 1-n, now, the problem appears. I can add 2 pcs to my company, but if I modify another relation (addind a tibs to the company), relation between company is delated.

Same test if I modify the relation type between companies and companycontact from 1-1 to 1-n, the problem appears for companycontact too, and if I have 1 pc & 1 companycontact associated to a company, addind or delating a tibs to the company will delate link with the companycontact and the pc.

Now, if I change put back relations from 1-N to 1-1, no more problem.
Put back relations from 1-1  to 1-N, problem is back.

Thanks to you, now I know that the problem appears when I change a relation type between content-type, but is their a methode to avoid this problem when I change the relation type ?

**Comment by omarnoir** [comment]
Problem solved si closed
