### ISSUE TITLE
"fetchAll" is undefined when I create new table on Strapi

### ISSUE THREAD

**Issue by FikriRNurhidayat** [strapi/strapi#3231]
**Informations**
- **Node.js version**: 11.0.0
- **NPM version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: Postgresql
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
When I try to get the endpoint of my model such as /socialBusinesses, server reply Internal Server Error and the log said "fetchAll" is undefined.

**Steps to reproduce the problem**
I've tried to change my node version from 11.0.0 to 10.0.0, and the error still occured.

**What is the expected behavior?**
I can get on /socialBusinesses without internal server errror

**Suggested solutions**
-

**Comment by derrickmehaffy** [comment]
Please see the following bug report template:















**Informations**
- **Node.js version**: 
- **NPM version**: 
- **Strapi version**: 
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 


**What is the current behavior?**



**Steps to reproduce the problem**



**What is the expected behavior?**



**Suggested solutions**
```

As per the following line `⚠️ If you do not respect this template your issue will be closed.` please update your template to include the required information, after you have updated please reply back and your issue can be reopened.

Marking as closed as template was not filled out.

**Comment by derrickmehaffy** [comment]
Please update your Strapi version: `Strapi version: 3.0.0-alpha.25.2` or create a new project with v26.2 and test for the error again.

Per this line in the template: 
```
<!-- =============================================================================== -->
<!-- ⚠️ If you are not using the current Strapi release, you will be asked to update. -->
<!-- Please see the wiki for guides on upgrading to the latest release. -->
<!-- =============================================================================== -->
```
