### ISSUE TITLE
Modifying CSS in Strapi Plugin

### ISSUE THREAD

**Issue by isabellachen** [strapi/strapi#3234]
**Informations**
- **Node.js version**:  v10
- **NPM version**: 
- **Strapi version**:  v3
- **Database**: Mongo
- **Operating system**: MacOS

**What is the current behavior?**
I am trying to modify the CSS in plugins/content-manager/admin/src/containers/ListPage/styles.scss 

After the change, I rebuild the application with `npm run setup` followed by `strapi start`, however, the changes are not reflected. How can I modify the css of the plugin?

**Comment by isabellachen** [comment]
In the end I just override the styles in the main css file specified in App/index.js 
Would be nice to know how to do this without overriding the styles...

**Comment by lauriejim** [comment]
This issue is related to the alpha version.
We are cleaning these issues.

**Comment by noelchavez** [comment]
Is there an update how to override plugin styles in beta?

**Comment by axe312ger** [comment]
Funny, this still seems not possible in 2025 with v5 oO
