### ISSUE TITLE
Remove many to many with graphql

### ISSUE THREAD

**Issue by lajap** [strapi/strapi#3238]
**Informations**

- Node.js version: v10.14.2

- NPM version: v6.9.0

- Strapi version: v3.0.0-alpha.23

-Nuxt version: v2.6.3

- Database: MongoDB

- Operating system: Windows 10

**What is the current behavior?**
I am fairly new to graphql. I'm building a YouTube clone with nuxt, part of the do-it-yourself learning, where the subscribers to a channel (content) is a many-to-many relation with the user (content). The channel (content) as subscribers and user (content) as subscriptions. If subscribers is modified/mutated and posted through graphql, subscriptions is also updated, this behavior works on playground:

`mutation {
  updateChannel (input: {
    where: {
      id: "5c2ddad0ec44d845dceb75b4"
    }
    data: {
      subscribers: ["5c1db080310da34d544ac5b0", "5c2d88beec44d845dceb75ad"]
    }
  }) {
    channel {
      subscribers {
        _id
        username
        email
      }
    }
  }
}`

But in code it produces errors when passing arrays like that:

`
   let channelId = state.channel._id
    let subs = []
    let isSub = false

    await state.channel.subscribers.forEach(el => {
      subs.push(el._id)
    })

    await subs.filter(subscriber => {
      if (subscriber == userId) {
        isSub = true
        subs.splice(subs.indexOf(userId), 1)
      } else {
        isSub = false
        subs.push(userId)
      }
    })

    await this.$axios({
      method: 'post',
      url: '/graphql',
      data: {
        query: `
        mutation {
          updateChannel (input: {
            where: {
              id: "${channelId}"
            }
            data: {
              subscribers: "${subs}"
            }
          }) {
            channel {
              subscribers {
                _id
                username
                email
              }
            }
          }
        }
      `
      }
    })
      .then(res => {
        commit('setChannelCommonRes', res)
      })
      .catch(err => {
        commit('setChannelCommonErr', err)
      })`

There is a better way of writing the above but I get 
`"Cast to [ObjectId] failed for value "["5c1db080310da34d544ac5b0,5c2d88beec44d845dceb75ad"]" at path "subscribers""` errors

**Steps to reproduce the problem**
Try removing a single (_id) many-to-many relation using graphql. That's what I've struggle with.

**Suggested solutions**
I modify a list of subscribers and pass it back as a new updated entry to graphql, because I can't find a way to tell graphql to remove an id from a list in a dynamic way on the server. I suggest that realations should be dynamically detached from the server than sending a modified list already requested back to the server.

**Comment by lauriejim** [comment]
Hello! Can you try with the last version of Strapi please;
You are actually with `3.0.0-alpha.23` and the last version is `3.0.0-alpha.26.2`.

**Comment by lajap** [comment]
Thank you lauriejim. I updated strapi to `3.0.0-alpha.26.2`, but same errors. Do you have any suggestions/solutions?

**Comment by derrickmehaffy** [comment]
@lajap please test with a fresh project first not just updating your previous one

**Comment by lauriejim** [comment]
I just tried the GraphQL request you wrote in your message.
And it works well in `playground` (`/graphql`) if you have and issue it can from your Strapi migration (make sure you also update your plugins and reinstall all your deps as mentioned in the migration guide) of it come from your font-end code.

**Comment by lajap** [comment]
Thank you @derrickmehaffy and @lauriejim . I've updated Strapi and it's plugin, step by step. On playground it works as expected. Using graphql update works for other field types such as string, it works, but when you use array to attach mutiples in relation it fails.

This is from playground:
`mutation {
  updateChannel (input: {
    where: {
      id: "5c2ddad0ec44d845dceb75b4"
    }
    data: {
      subscribers: ["5c1db080310da34d544ac5b0", "5c2d88beec44d845dceb75ad"]
    }
  }) {
    channel {
      subscribers {
        _id
        username
        email
      }
    }
  }
}`
It works!
In code after creating an array and pass it, as I did above, it fails with this `message: "Cast to ObjectId failed for value "5c1db080310da34d544ac5b0,5c2d88beec44d845dceb75ad" at path "subscribers""`.

**Comment by lajap** [comment]
I'm using axios, I doubt it's an axios problem, nor a front-end problem, because other fields work. CRUD works with other field types. Look little closely same ids (user) used in playground are same used in code and somehow fails to recognize it's array with the same ids (user). I test first on playground, that it works then proceed into code.

This is what I did in code:
`updateChannel (input: {
        where: {
          id: "${channelId}"
        }
        data: {
          subscribers: "${subs}"
        }
      })`

I updated it to this:
`updateChannel (input: {
        where: {
          id: "${channelId}"
        }
        data: {
          subscribers: "[${subs}]"  //or this subscribers: [${subs}]
        }
      })`

same issue

**Comment by lauriejim** [comment]
You send `"${subs}"` as a string instead of the `Array`

**Comment by lajap** [comment]
Yeah, I think that's the problem. I'm using back-tick ( ``string``  ) and template literals ( `${expression}` ) with axios:
`data: {
            query: `
        mutation {
          updateChannel (input: {
            where: {
              id: "${channelId}"
            }
            data: {
              subscribers: ${[subs]}
            }
          }) {
            channel {
              subscribers {
                _id
                username
                email
              }
            }
          }
        }
      `
          }`

graphql fails because it's wrapped as a single string instead of an array. The problem is changed from `"${subs}"` to `${subs}` / `[${subs}]` I get the bad request 400 code, because it's not the right graphql expression. I'm stuck now, I don't know a better way, yet, to send the right graphql expression with `subs`.

Thank you @lauriejim

**Comment by lajap** [comment]
Oops! back-tick is used by github to express code, so they're removed in the above

**Comment by lauriejim** [comment]
When you use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and you use `${array}` inside it will display the array values as `a, b, c` for this array `['a', 'b', 'c']`

So you query will look like that

```
mutation {
  updateChannel (input: {
    where: {
      id: 5cd3f8fcccabcc156664ec4b
    }
    data: {
      subscribers: 5cd3f895ccabcc156664ec48,5cd3f8e6ccabcc156664ec49
    }
  }) {
    channel {
      subscribers {
        _id
        username
        email
      }
    }
  }
}
```

With this code 

```
mutation {
  updateChannel (input: {
    where: {
      id: "${channelId}"
    }
    data: {
      subscribers: [${subs.map(sub => `"${sub}"`)}]
    }
  }) {
    channel {
      subscribers {
        _id
        username
        email
      }
    }
  }
}
```

It will look like 

```

mutation {
  updateChannel (input: {
    where: {
      id: "5cd3f8fcccabcc156664ec4b"
    }
    data: {
      subscribers: ["5cd3f895ccabcc156664ec48","5cd3f8e6ccabcc156664ec49"]
    }
  }) {
    channel {
      subscribers {
        _id
        username
        email
      }
    }
  }
}
```

And it's the correct sentence.

**Comment by lajap** [comment]
Yeah, I didn't educate my self about template literal, that's where I had issues. I just spent few hours studying it after @lauriejim suggestions. @lauriejim you're right, and your solution is working as expected. I'm very grateful.

**Comment by lauriejim** [comment]
Your welcome!
