### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by mckraemer** [strapi/strapi#3239]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: PostgreSQL
- **Operating system**: Windows 10

**What is the current behavior?**
Can't start my Strapi project.

```
[2019-05-09T03:44:18.624Z] error Something went wrong in the model `Recipe` with the attribute `author`
[2019-05-09T03:44:18.628Z] error Cannot read property 'hasOwnProperty' of undefined
```

Implementation of Author:

```
  "author": {
      "model": "user",
      "via": "recipes",
      "plugin": "users-permissions"
    }
```

**Steps to reproduce the problem**
Create relationship with users
Update strapi from alpha.24 to alpha 26

**Comment by lauriejim** [comment]
Hello! 
I think you miss a steps in the migration guide. Is to save relations from your `User.settings.json` file to report them in the new model.
Here https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.25-to-alpha.26.html#update-the-plugins
