### ISSUE TITLE
Email templates and plugin settings hard to find

### ISSUE THREAD

**Issue by vedran-brnjetic** [strapi/strapi#3241]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Loosely connected to #549 in terms of consideration.

As I indicate above, I submitted my request in the Product Board.

## Email Templates non-intuitively placed in the Admin Panel

I had trouble finding the Email Templates and discovered them in *Roles & Permission*s*
It would be more convenient if Email Templates would be in something called **Email Settings**, which is the title of the settings page for the *Email Plugin*.

(* "Roles & Permission" button should say "Roles & Permissions")

## Email Plugin settings hard to find - inconsistency with Documentation Plugin

When I installed the *Documentation Plugin*, I got a very useful **Documentation** button in **Plugins** category in the left-side menu. *Email Plugin*.

![Menu](https://user-images.githubusercontent.com/31465141/57451676-a4e3c080-726a-11e9-83ad-aa37027bffa9.png)

## Proposal

Have an **Email Settings** button in **Plugins** category of the menu, and move *Email Templates* settings there as well.

**Comment by derrickmehaffy** [comment]
Look at this guy even going the extra step and giving a preview example.

+1 from me, they need to be moved.

**Comment by vedran-brnjetic** [comment]
> 
> 
> Look at this guy even going the extra step and giving a preview example.

That was simple in-browser editing :)

> 
> +1 from me, they need to be moved.
> 
> PS Email should be below Documentation, my alphabetical order OCD is triggering

Didn't realize they were alphabetical, it seemed perfectly valid in order of importance. 🔤 
Fixed

**Comment by Aurelsicoko** [comment]
I'm sorry but we won't add a new link "Email settings" in the left menu into the "Plugins" section. It makes no sense to me. This is not a plugin, we are talking about the templates of the email sent by the **Users & Permissions** plugin.

The emails settings should be moved to the **Configurations** section. In any case, we plan to rethink the entire layout of the administration panel because we made some choices which block us to build a clear, consistent and understandable interface.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko technically it is not the user-permissions that handle emails: https://github.com/strapi/strapi/blob/a0b6a7ce421f5641cff006d772e38e28d83ebddc/packages/strapi-plugin-users-permissions/controllers/Auth.js#L200-L209

Which uses the email plugin: https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-email

**Comment by derrickmehaffy** [comment]
So I agree these settings need to be moved outside the user-permissions options and given their own space (as this is something that could be modified in production) in which the typical configurations are disabled in production.

**Comment by vedran-brnjetic** [comment]
Well, I'm not necessarily telling you HOW to do things, but the point still is that this needs rethinking. 

For inspiration, I like how OctoberCMS is organized. It's intuitive and grouped nicely and logically.

![image](https://user-images.githubusercontent.com/31465141/57520781-30bb2280-7327-11e9-8547-c55bdcb49614.png)

![image](https://user-images.githubusercontent.com/31465141/57520848-67913880-7327-11e9-9293-97e476b47074.png)

**Comment by Aurelsicoko** [comment]
@derrickmehaffy Yeah, the email are sent by the **Email** plugin but these specific templates are handled by the **User & Permissions** plugin. I'm not speaking about technical stuff here... I just want to build a product that makes sense :)

@vedran-brnjetic Exactly what I'm thinking about. We should add a new item "Email Templates" in the sub-menu of the **Configurations** link. As I said, it's more complicated than this and we have to rethink the entire layout and the way we manage the plugin settings.

**Comment by lauriejim** [comment]
I'm closing this discussion, we got all your insight.
Thank you for your contribution to this discussion.
Appreciate.
