### ISSUE TITLE
Setting CORS origin to anything other than '*' throws InternalServerError

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#3242]
**Informations**
- **Node.js version**: 10.15.3 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: Mongo
- **Operating system**: Debian 

**What is the current behavior?**

Setting CORS Origin to anything other than * results in:

```
  InternalServerError: http://<ip>:1337 is not a valid origin
      at Object.throw (/home/owens/stratosphere-api/node_modules/koa/lib/context.js:97:11)
      at Object.origin (/home/owens/stratosphere-api/node_modules/strapi/lib/middlewares/cors/index.js:41:35)
  ...
```

**What is the expected behavior?**

Strarpi / KOA should use whatever we set in the CORS Origin field.

![image](https://user-images.githubusercontent.com/83678/57462456-e4001a80-7246-11e9-9593-e9fe4a41cca0.png)

**Comment by lauriejim** [comment]
Hello @nurikabe !

Thank you for this report. We have to find a way to apply `cors` configuration to API call and omit or find an other way to custom `cors` for the admin panel.

**Comment by lauriejim** [comment]
I confirm your issue. I close this because it's directly related to this one https://github.com/strapi/strapi/issues/2969
So now it's linked. Thank you.

**Comment by MANTENN** [comment]
Ok, if the domain is not in the whitelist. You will get the same error. I had just looked at the code but it took me some time to figure out what has been causing a cors error on the frontend. 

https://github.com/strapi/strapi/blob/2b22675edc450b4d462a810e59731ca0c0dabd79/packages/strapi/lib/middlewares/cors/index.js#L43-L45
