### ISSUE TITLE
Admin returns error after adding or saving content type with content type builder.

### ISSUE THREAD

**Issue by JaapWeijland** [strapi/strapi#3244]
**Informations**
- **Node.js version**: v10.15.3 
- **NPM version**:  6.4.1
- **Strapi version**: v3.0.0-alpha.26.2 
- **Database**: mongoDB
- **Operating system**: Ubuntu 16.04

Host: api.domain.nl/admin

**What is the current behavior?**
When saving a content type after editing, the admin dashboard shows me that there is an error. Redirection fails. Clicking on menu items at the left still works however.

**Steps to reproduce the problem**
- Go to Content Type Builder
- Pick Content Type to edit
- Add field
- Click save to add field
- Click save to save content type

**What is the expected behavior?**
Correctly being redirected to the concerning content type after saving.

**Suggested solutions**
When investigating with google dev tools, it seems that the redirect is sending me to api.domain.nl/content-type-builder/models, which of course doesn't exist. I think it should be api.domain.nl/admin/plugins/content-type-builder/models. Somehow it only takes the host and adds the relative path (/content-type-builder/models) to it, which leads to a wrongful url.

**Comment by lauriejim** [comment]
Hello!

Your issue looks weird. Can you send me us a screen shot of your browser console and a screenshot of the message you get.

Because like that I don't understand where the issue can come from.

**Comment by JaapWeijland** [comment]
I hope this helps.

![Schermafbeelding 2019-05-10 om 14 59 12](https://user-images.githubusercontent.com/7115712/57529037-353a0800-7334-11e9-829b-7f5f4952f9b8.png)

![Schermafbeelding 2019-05-10 om 14 59 40](https://user-images.githubusercontent.com/7115712/57529041-39662580-7334-11e9-96ca-46e85c60de87.png)

**Comment by lauriejim** [comment]
Actually you are in your **production** server but you start your application in **development** environment. 

Second thing, we did not recommend (it's the reason why we disable the content type builder plugin in production) to create/update/delete content type in production server.

Please check this article http://help.strapi.io/content-type/content-type-builder-is-not-visible

I don't know how your serve is configured and how you start your Strapi application but I think it can come from here. (make sure your is restarted after your update - if not it's probably because you start with `npm start` instead of `strapi start`)

**Comment by gvramesh2003** [comment]
I'm also facing the same issue.

What is the current behavior?

When saving a new content type, the admin dashboard shows me that there is an error. Redirection fails. Clicking on menu items at the left still works however.

Steps to reproduce the problem

- Go to Content Type Builder
- Add Content Type
- Add field
- Click save to add field
- Click save content type

![Strapi-error](https://user-images.githubusercontent.com/56820633/67197561-b389f280-f41a-11e9-85ac-69945ccdd4a5.png)

Also when I try to delete any "Content type", got success message. After refresh the page, deleted content type shown in page again and corresponding table is not deleted.

**Comment by derrickmehaffy** [comment]
@gvramesh2003 Please test with the latest version, I can tell by the response headers you are at least below beta.16

**Comment by RanaOsamaAsif** [comment]
I'm facing a similar issue in version **beta 18.6**. To use the content type builder we stop the server running in production mode and start it in development.

I receive **error 400** whenever I try to edit an existing content type or create a new one. I have been using Strapi for 3-4 monthts but this sort off issue never came.

**Comment by Gauravp15** [comment]
@RanaOsamaAsif Yes I'm getting the same 400 error on **beta 18.6**.  It is happening in development mode though. Weird that this din't happen last time I used strapi.

**Comment by derrickmehaffy** [comment]
@RanaOsamaAsif @Gauravp15 can you please post your 400 errors, the most recent comments on this thread are referencing 502 gateway errors which are a problem with the upstream proxy.

**Comment by Gauravp15** [comment]
@derrickmehaffy 
![error](https://user-images.githubusercontent.com/16864248/73206799-97a89200-4169-11ea-89df-70ca4531dd88.PNG)

**Comment by VGamezz19** [comment]
@lauriejim Hey, I check that u recoment don't use the production mode in a Developemnt enviroment.
The point is that i'm executing strapi in a development mode, and I face the sane bug

**Comment by lauriejim** [comment]
Did you update your application version?

**Comment by Aidoboy** [comment]
I'm also having this issue, I'm not familiar with the ins and outs of Strapi though, this is an undergrad capstone project that we're picking up from another semester's team. We (hopefully) upgraded from a few versions back in the Alpha to the latest Beta

**Comment by fredfies** [comment]
Hey, I also experienced this error. What I found out is, that it happened 'cause I tried to create a content type with the same name I had used before but already deleted. If I used a completely new name for the new content type everything worked fine.

**Comment by derrickmehaffy** [comment]
@fredfies see: http://github.com/strapi/strapi/1114
