### ISSUE TITLE
New content types are not correctly deployed to heroku

### ISSUE THREAD

**Issue by AdamGniady** [strapi/strapi#3245]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: mongodb
- **Operating system**: windows 10 / heroku

**What is the current behavior?**
I started my project with the heroku one click deployment and developed it locally with git clone etc. 
When i create new content types locally everything works fine. I can create new content types and i can add new content. Furthermore i can get the the information via a rest call. That is what i want. When i deploy my app to heroku i can't add new content to my content types and additionally i can't see the new types in the content manager but i can see theme in the sidebar "content types". I can open them, but i can't add new contents in them. 

**Steps to reproduce the problem**
1. Strapi Heroku One Click Installation
2. Clone Repo locally 
3. Develop new contenttypes via ui and test the rest calls etc. 
4. deploy to heroku
5. fail when you want to create new content

**What is the expected behavior?**
In production (after heroku deployment) i want to add content to my contenttypes that i created locally. 

**Suggested solutions**
I don't know. Maybe i have done something wrong?

**Comment by AdamGniady** [comment]
Maybe as additional information: I used this as a starter https://github.com/strapi/strapi-heroku-app

**Comment by lauriejim** [comment]
Can you try to remove in your database, in the `core_store` collection, the document that have **key** `plugin_content-manager_schema`

**Comment by AdamGniady** [comment]
Cool, that worked! So the next time i deploy a change in my contenttypes i have to delete this key?

**Comment by lauriejim** [comment]
We have an issue about that point  merge / sync of this schema that fail.
Sorry about that.

Hum if this issue come back, yes :/

**Comment by EdCouchman** [comment]
Hello dear Strapi team, I still have this problem and I can not find this plugin_content-manager_schema document in the core_store. Any idea how to solve this problem? Thanks!
