### ISSUE TITLE
Polymorphic relation is not well managed from the Content Manager

### ISSUE THREAD

**Issue by alexis-puska** [strapi/strapi#3247]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**:  6.9.0
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: mongo
- **Operating system**: windows 7
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Polymorphics collection failed 

**Path —** `Page.settings.json` 
```json
"related": {
  "collection": "*",
  "filter": "field"
}
```

**Path —** `Statics.settings.json`
```json
"page": {
  "model": "page",
  "via": "related"
}
```

**Steps to reproduce the problem**
when i create this relation, i create one page, i create some static object and set the page to the unique page. when i do that, only the last static object have the relation to the page. When a call the WS to get all page, in the related field, we seen only the last static objet edited.

**What is the expected behavior?**
In a one to many polymorphics relation, we need to have a collection and all object set inside this collection.

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello! 
Can you please read this issue https://github.com/strapi/strapi/issues/3173 and make sure all is OK.

**Comment by alexis-puska** [comment]
in the issue #3173 this is for one-to-one relation, in my case i would like to have a list of polymorphic object (one-to-many)

**Comment by lauriejim** [comment]
Ho okay see.
Thank you for this report!

**Comment by nachogarcia** [comment]
We're having the same issue with both 1-N and 1-1 with polymorphism. Tested with sqlite and mongo.
pagehome model:
```
  "attributes": {
    "title": {
      "type": "string"
    },
    "components": {
      "collection": "*",
      "filter": "field"
    }
  }
```

some random component model: 
```"attributes": {
    "title": {
      "required": true,
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "cta": {
      "type": "string"
    },
    "pagehome": {
      "model": "pagehome",
      "via": "components"
    }
  }
```
