### ISSUE TITLE
Dev environment runs out of memory on setup

### ISSUE THREAD

**Issue by wik-z** [strapi/strapi#3249]
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: default
- **Operating system**: Windows 10

**What is the current behavior?**
Trying to setup my environment to develop a plugin for strapi and it's giving me a lot of headache. I followed the steps in the documentation, but while running "Plugin development Setup" step 2 (`cd /admin && npm run setup`) it decides to throw a following error instead.
```
🏗  Building the admin...
  0% compilingFATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7C8FD0EFA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF7C8FAA296 node::MakeCallback+4518
 3: 00007FF7C8FAAC80 node_module_register+2160
 4: 00007FF7C92409BE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7C92408EF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7C977E954 v8::internal::Heap::MaxHeapGrowingFactor+11476
 7: 00007FF7C97750B7 v8::internal::ScavengeJob::operator=+25543
 8: 00007FF7C977362C v8::internal::ScavengeJob::operator=+18748
 9: 00007FF7C977C5A7 v8::internal::Heap::MaxHeapGrowingFactor+2343
10: 00007FF7C977C626 v8::internal::Heap::MaxHeapGrowingFactor+2470
11: 00007FF7C931F447 v8::internal::Factory::NewFillerObject+55
12: 00007FF7C93B712A v8::internal::WasmJs::Install+29530
13: 000002F80975C5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! strapi-admin@3.0.0-alpha.26.2 build: `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
```

**Steps to reproduce the problem**
Literally following the guide:
https://strapi.io/documentation/3.x.x/plugin-development/quick-start.html#development-environment-setup
until you reach "Plugin development Setup" section, step 2 `cd /admin && npm run setup`

**What is the expected behavior?**
Installation continues without issues

**Suggested solutions**
I don't know what causes the problem so it's hard to suggest anything. I suspect there's a memory limit set up somewhere in the build scripts, but it's hard to tell where exactly.

**Comment by Mindsaver** [comment]
I have the same problem.
Tried to get it with `--max_old_space_size=8192` working but i dont know where i should place this exactly.

**Comment by alexandrebodin** [comment]
I suggest using

`NODE_OPTIONS=--max_old_space_size=YOUR_VALUE npm run setup`

**Comment by wik-z** [comment]
I can't believe my eyes. I set it to 8192 and it's at least reaching 70% of the build but still fails, runs out of memory.
How's this so heavy on memory? 😮

**Comment by alexandrebodin** [comment]
That shouldn't be. Maybe an issue with windows. We have made a lot of changes for the next release. I suggest you wait for it (coming soon)

**Comment by lauriejim** [comment]
I close it since `beta` is released

**Comment by gabrilator** [comment]
Hey everyone, 
getting this same error after uploading an app to Heroku,

Running on beta 3.20 
Any suggestions??

**Comment by gabrilator** [comment]
May I add I'm getting this error when trying to upload files using the upload manager

**Comment by nguyenchauhuyen** [comment]
any update ?

**Comment by derrickmehaffy** [comment]
@gabrilator @nguyenchauhuyen this issue is about the build, for upload memory see: https://github.com/strapi/strapi/issues/6432

**Comment by hyaprakov** [comment]
This problem persists, I am getting something similar on an AWS EC2 at 90% build

**Comment by derrickmehaffy** [comment]
> This problem persists, I am getting something similar on an AWS EC2 at 90% build

Need at least 2 GB of **FREE** memory, the Free tier AWS EC2 instance doesn't have enough memory.

**Comment by okayrunner** [comment]
Seeing the same issue.

Running on AWS on a `t2.small` (2gb) 

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1991         365        1020          16         604        1427
Swap:             0           0           0
```

Strapi Version:  3.6.5 


```
$ cat /home/ec2-user/.pm2/logs/app-error.log
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a62e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9a9a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c25  [node]
```

**Comment by derrickmehaffy** [comment]
You only have 1020mb of **free** memory, you need at least 2048mb (ideally more for a little buffer).

Or you need to prebuild the admin and push that into source control so you don't need to build on the server.
