### ISSUE TITLE
Adding content type issue in alpha.26.2.

### ISSUE THREAD

**Issue by boverU** [strapi/strapi#3259]
- node version: 10.15.3
- npm version: 6.9.0
- strapi version: 3.0.0-alpha.26.2.

**What is the current behavior?**
In ContentTypeBuilder section trying to "Add Content Type", after adding "New Fields" I click save and instead of saving I got the error. In console I have  
![ssstrapi](https://user-images.githubusercontent.com/41537838/57691914-9b45c880-766f-11e9-8323-191bb3a49480.png)

. In command line I got  
![ssstrapi1](https://user-images.githubusercontent.com/41537838/57691923-a1d44000-766f-11e9-9c35-b8f80485b8bb.png)

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
