### ISSUE TITLE
Allow private file storage via strapi-upload-google-storage addon

### ISSUE THREAD

**Issue by pelayomendez** [strapi/strapi#3266]
- [X ] **I have created my request on the Product Board before I submitted this issue**
- [X ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

When using the "strapi-upload-google-storage addon" files are uploaded as public by default to the bucket. It will be handy to be able to define this in the control panel so files get stored not public.

This way you'll still be able to manage them but can use methods as signed URLs to retrive them in a more private way from Google Cloud.

**Comment by lauriejim** [comment]
This node module is not maintained by the Strapi team.
It's @danielmahon of the community that developed this upload provider.
I suggest you to find his repo to post the issue there.
We can't help you more on this part.

**Comment by pelayomendez** [comment]
Thanks. I couldn't find the repository anywhere. I will try to contact him and look into it.
