### ISSUE TITLE
Support bulk actions by default

### ISSUE THREAD

**Issue by Nader-Sl** [strapi/strapi#3269]
The routes/controllers at the moment doesn't seem to support optimized bulk-actions by default although one could implement it by defining his own route/controller, however basic things like multiple user create/edit/delete would be handy! right now i bet some people are just iterating over a set of data and call the corresponding CRUD upon each out of laziness which is not a good idea :D

**Comment by derrickmehaffy** [comment]
Duplicate: https://portal.productboard.com/strapi/c/42-bulk-route-to-create-multiple-entries

Also the template was not followed, marking this as closed.
