### ISSUE TITLE
"Cannot read property 'defaultConnection' of undefined" when running `dev` script

### ISSUE THREAD

**Issue by Qrysto** [strapi/strapi#3274]
**Informations**
- **Node.js version**: 12.2.0
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-next.4
- **Database**: none
- **Operating system**: Windows 10

**What is the current behavior?**
I get these errors when trying to run the project:

```
[2019-05-16T07:58:11.133Z] debug ⛔️ Server wasn't able to start properly.
[2019-05-16T07:58:11.135Z] error TypeError: Cannot read property 'defaultConnection' of undefined
    at module.exports (<project_path>...\node_modules\strapi\lib\core\bootstrap.js:25:47)
    at Strapi.load (<project_path>...\node_modules\strapi\lib\Strapi.js:270:11)
    at async Strapi.start (<project_path>...\node_modules\strapi\lib\Strapi.js:110:7)
error Command failed with exit code 1.
```

**Steps to reproduce the problem**
I just followed exactly what's instructed in the [Quick start guide](https://strapi.io/documentation/3.x.x/getting-started/quick-start.html), it seemed that the project got created successfully, but when the project tried to start, the above error occurred. 

**What is the expected behavior?**
By following exactly the Quick start guide, things should work without errors. When I tried to run it with `npm run dev` again, the same error occurred.

**Suggested solutions**
I figure it might be something to do with the database. I don't have a database - mongodb or sqlite... - installed, and I see the default config in database.json is "sqlite". But if it's required to have a database installed or configured, it should have been listed clearly in the [Installation requirements](https://strapi.io/documentation/3.x.x/getting-started/install-requirements.html#basic-installation-requirements) shouldn't it?

**Comment by lauriejim** [comment]
Hello, the `next` version is experimental.
And the documentation for this version is not published and different than the `alpha`.

I close this issue because you use `next` version. Please use `alpha` version.

How did you install and generate your project ?

**Comment by alexandrebodin** [comment]
@Qrysto node v12 is not supported by the way if you really want to try out next, make sur you are using node v10 ;) (pretty sure it's why you have a bug, sqlite is not working you node v12 and is the default db)

**Comment by Qrysto** [comment]
Thanks for your replies. It seems that node v12 was not the problem. I tried to downgrade both node to v10 and strapi to alpha, it still didn't work. However when I tried to remove strapi and reinstalled using `npm` (I used `yarn` before), then it worked. Even when I upgraded node back to v12, it still worked. But when I tried to upgraded strapi back to `next` version, it doesn't work anymore.

So based on my experiment, npm + strapi@alpha is what makes it work, regardless of the node version.

**Comment by Qrysto** [comment]
By the way, not directly related to the issue, but would like to ask, do you have any plan for when strapi is out of alpha/beta?

**Comment by derrickmehaffy** [comment]
> By the way, not directly related to the issue, but would like to ask, do you have any plan for when strapi is out of alpha/beta?

Better place to ask this is probably in the slack as to not flood github with unrelated questions

**Comment by Qrysto** [comment]
Slack link on the website doesn't work. It's fine if you can't answer here though

**Comment by lauriejim** [comment]
Hello! An update about this.
It was because of path with `\`.
We fixed it ;) Thank about the report of this issue @Qrysto

**Comment by Qrysto** [comment]
Nice, thanks @lauriejim

**Comment by KhanhKitin** [comment]
Hi! 
I had the same problem

[2020-05-28T10:59:38.060Z] debug ⛔️ Server wasn't able to start properly.
[2020-05-28T10:59:38.063Z] error TypeError: Cannot read property 'defaultConnection' of undefined
    at module.exports (C:\Users\Quoc_Khanh\Desktop\Strapi\backend_delux\node_modules\strapi\lib\core\bootstrap.js:42:47)
    at Strapi.load (C:\Users\Quoc_Khanh\Desktop\Strapi\backend_delux\node_modules\strapi\lib\Strapi.js:320:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'mysql',port: env.int('DATABASE_PORT', 3306),
        host: env('DATABASE_HOST', 'xxxxxx'),
        database: env('DATABASE_NAME', 'delux'),
        username: env('DATABASE_USERNAME', 'xxxx'),
        password: env('DATABASE_PASSWORD', 'xxxxx'),
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});

    "knex": "<0.20.0",
    "mysql": "^2.18.1",
    "sqlite3": "^4.2.0",
    "strapi": "3.0.0-beta.19.5",
    "strapi-admin": "3.0.0-beta.19.5",
    "strapi-connector-bookshelf": "3.0.0-beta.19.5",
    "strapi-plugin-content-manager": "3.0.0-beta.19.5",
    "strapi-plugin-content-type-builder": "3.0.0-beta.19.5",
    "strapi-plugin-email": "3.0.0-beta.19.5",
    "strapi-plugin-upload": "3.0.0-beta.19.5",
    "strapi-plugin-users-permissions": "3.0.0-beta.19.5",
    "strapi-provider-email-nodemailer": "^2.0.0",
    "strapi-utils": "3.0.0-beta.19.5"
Can you help me?

**Comment by tommyboylab** [comment]
I've just experienced this issue while migrating to release 3.0.0.

```
[2020-06-01T19:19:48.055Z] debug ⛔️ Server wasn't able to start properly.
[2020-06-01T19:19:48.056Z] error TypeError: Cannot read property 'defaultConnection' of undefined
    at module.exports (/var/www/server/node_modules/strapi/lib/core/bootstrap.js:35:71)
    at Strapi.load (/var/www/server/node_modules/strapi/lib/Strapi.js:317:11)
    at async Strapi.start (/var/www/server/node_modules/strapi/lib/Strapi.js:190:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.4.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tropicalt-bff@0.4.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2020-06-01T19_19_48_073Z-debug.log
```

**Comment by jsaguiar** [comment]
@tommyboylab I'm also having the same issue

**Comment by alexandrebodin** [comment]
Hello without having your strapi version nor your database config we cannot help you :) 

@KhanhKitin you are using v3.0.0 configuration in beta.19 this cannot work you need to migrate your dependencies. check the different migration guides to move from beta.19 to beta.20 then v3

https://strapi.io/documentation/v3.x/migration-guide/
