### ISSUE TITLE
user allowed

### ISSUE THREAD

**Issue by GlauberF** [strapi/strapi#3275]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

can I create a user and that user is only allowed to change the module that he created?

Because today I have several developers working with us and I would like both to have login, but only could work / change node module that he created

**Comment by derrickmehaffy** [comment]
@GlauberF please follow the bug report template, after you have updated your issue with the correct template this can be reopened.

**Comment by GlauberF** [comment]
@derrickmehaffy I adjusted.

**Comment by derrickmehaffy** [comment]
It's not quite a feature request but I'll reopen

**Comment by derrickmehaffy** [comment]
Short answer to your question is no the admin-UI doesn't have that sort of permissions yet.

**Comment by lauriejim** [comment]
Hello @GlauberF !
Thank you for this report.
I close this issue because it's already in our roadmap and details are here: https://portal.productboard.com/strapi/c/8-administrators-roles-permissions
Can you share your use case / need on Product Board please.
