### ISSUE TITLE
GraphQL Playground not working

### ISSUE THREAD

**Issue by Shenix** [strapi/strapi#3276]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: 
- **Operating system**: MacOS

Hi 
i switched to graphql but when i went to http://localhost:1337/graphql, Playground is not loading and get this error on console : 

Uncaught ReferenceError: GraphQLPlayground is not defined at graphql:537

I think that it needs update because file doesn't exist in JSDelivr.

Thanks

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
