### ISSUE TITLE
Errors in services not caught by controllers

### ISSUE THREAD

**Issue by IceOnFire** [strapi/strapi#3279]
**Informations**
- **Node.js version**: v12.2.0
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: MongoDB v3.6.8
- **Operating system**: Linux Ubuntu 19.04 (Disco Dingo)
- **(Optional) Link to your Project**: 

**What is the current behavior?**

If a service throws an Error, this will automatically trigger an HTTP 500 error on the server.

**Steps to reproduce the problem**

1. Create an API
2. Throw an Error from a function inside of a service
3. Wrap the related function inside the controller with a `try/catch` block and return a `ctx.badRequest(null, err.messages)` in the `catch` block

**What is the expected behavior?**

I expect the error to be propagated from the service to the controller, so I can catch it and behave accordingly.

Instead, the stacktrace shows that multiple other modules are involved:

```
Error: My custom error
    at async Object.doSomething (/home/antony/my-strapi-project/api/endpoint/services/Endpoint.js:263:26)
    at async /home/antony/my-strapi-project/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:59:20
    at async module.exports (/home/antony/my-strapi-project/plugins/users-permissions/config/policies/permissions.js:26:14)
    at async /home/antony/my-strapi-project/node_modules/strapi-utils/lib/policy.js:111:7
    at async validator (/home/antony/my-strapi-project/node_modules/koa-router-joi/joi-router.js:327:32)
    at async parsePayload (/home/antony/my-strapi-project/node_modules/koa-router-joi/joi-router.js:253:56)
    at async specExposer (/home/antony/my-strapi-project/node_modules/koa-router-joi/joi-router.js:369:5)
    at async prepareRequest (/home/antony/my-strapi-project/node_modules/koa-router-joi/joi-router.js:381:3)
[2019-05-16T16:13:47.674Z] debug POST /endpoint/do-something (418 ms)
```

**Suggested solutions**

Every module involved in the request should propagate the error up to the controller instead of breaking the server, but I have no idea where this should be handled in Strapi code.

**Comment by alexandrebodin** [comment]
Hi,

can you share your controller code (real one) plz

**Comment by IceOnFire** [comment]
Hi,

I would love to provide you a clean example with an installation from scratch but I get errors in creating a new project with `strapi new`.

So here is not a real, but a realistic controller:

```js
'use strict'

/**
 * Endpoint.js controller
 *
 * @description: A set of functions called "actions" for managing `Endpoint`.
 */

module.exports = {
  /**
   * Retrieve endpoint records.
   *
   * @return {Object|Array}
   */

  find: async (ctx, next, { populate } = {}) => {
    if (ctx.query._q) {
      return strapi.services.endpoint.search(ctx.query)
    } else {
      return strapi.services.endpoint.fetchAll(ctx.query, populate)
    }
  },

  /**
   * Retrieve a endpoint record.
   *
   * @return {Object}
   */

  findOne: async ctx => {
    if (!ctx.params._id.match(/^[0-9a-fA-F]{24}$/)) {
      return ctx.notFound()
    }

    return strapi.services.endpoint.fetch(ctx.params)
  },

  /**
   * Count endpoint records.
   *
   * @return {Number}
   */

  count: async ctx => {
    return strapi.services.endpoint.count(ctx.query)
  },

  /**
   * Create a/an endpoint record.
   *
   * @return {Object}
   */

  create: async ctx => {
    return strapi.services.endpoint.add(ctx.request.body)
  },

  /**
   * Update a/an endpoint record.
   *
   * @return {Object}
   */

  update: async (ctx, next) => {
    return strapi.services.endpoint.edit(ctx.params, ctx.request.body)
  },

  /**
   * Destroy a/an endpoint record.
   *
   * @return {Object}
   */

  destroy: async (ctx, next) => {
    return strapi.services.endpoint.remove(ctx.params)
  },

  doSomething: async (ctx, next) => {
    try {
      return strapi.services.endpoint.doSomething(ctx.params, ctx.request.body)
    } catch (error) {
      return ctx.badRequest(null, [error.message])
    }
  }
}
```

**Comment by alexandrebodin** [comment]
Hi, thansk for the details:

From what I'm seeing the issue is in the code you just shared with me.

your service function is async meaning it returns a promise. If you don't call `await` when calling your service it is not going to go in the catch function but just return a promise (which we catch later on)

here is a simplifed example you can look at https://codesandbox.io/s/4kszs

hope this helped

**Comment by IceOnFire** [comment]
How stupid I feel! You're totally right, sorry for wasting your time and thank you for helping me understand a thing that I totally missed even after 7 years of experience in JavaScript. Closing the issue.

**Comment by alexandrebodin** [comment]
my pleasure !
