### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by it-nilesh** [strapi/strapi#3286]
**Informations**
- **Node.js version**: 12.2.0 
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.26.2 
- **Database**: redis
- **Operating system**: windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

error Impossible to determine the use of ORM for the model customer.
TypeError: Cannot read property 'find' of undefined
at Object.fetchAll (D:\RND\Strapi\strapi-new\plugins\content-manager\services\ContentManager.js:19:52)
at find (D:\RND\Strapi\strapi-new\plugins\content-manager\controllers\ContentManager.js:33:83)

When I view model in the strapi admin panel, throw the above exception.

npm package : strapi-hook-redis

**What is the expected behavior?**
I want to store data in redis

**Comment by lauriejim** [comment]
Hello @it-nilesh!

Sorry for this issue.
We no longer supported. We forgot to notice it, we remove it from the `strapi new` CLI.
So I suggest you to use Postgres, MySQL or Mongo.

Sorry for that. We will remove this package in the beta version.
