### ISSUE TITLE
Post.query is not a function

### ISSUE THREAD

**Issue by Osmandiyaka** [strapi/strapi#3289]
Informations

Node.js version: 10.15.1
NPM version: 6.9.0
Strapi version: 3.0.0-alpha.26.2
Database: MongoDB 4.0.8
Operating system: window 10

After Creating content type call Post, when I make a rest call to /posts I get the error 
TypeError: Post.query is not a function

**Steps to reproduce the problem**
Create a contentType call xxx and make a rest call to /xxxs

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello!

Can you give us more details because here we cant understand where your issue come from.

Did you update your application or it's a fresh new one with `alpha.26.2`?
How did you create your content type ? CLI or content type builder ?
What are the attributes to your content type ?
