### ISSUE TITLE
Custom route on multiple models

### ISSUE THREAD

**Issue by Nazort** [strapi/strapi#3291]
This issue is a question 

I'm currently developing a project with a PostgreSQL database. I'm trying to add a custom route where I will need to query data from multiple tables.

An example is getting all data from a table applying a "where in" and getting data from another table applying where and so on until I find my specific rows.

Such as : 

`SELECT * from projects where id in (SELECT projects_id from account_by_project where account_id = VALUE)
`
I can't find code example to develop a "complex" custom route. And nothing about query including multiple models.

Could someone give me any tips?

**Comment by lauriejim** [comment]
Hello!

You can already did it with deep filtering feature.
📚https://strapi.io/documentation/3.x.x/guides/filters.html#available-operators

And you you want to create custom queries you can use the instance of knex in `strapi.connections.default`.
