### ISSUE TITLE
Disable id as possible attribute name

### ISSUE THREAD

**Issue by dave-dm** [strapi/strapi#3292]
added a row with an "id" column. Didn't give me a warning not to do it, then it crashes and won't start.

```
[2019-05-18T07:18:23.895Z] debug ⛔️ Server wasn't able to start properly.
[2019-05-18T07:18:23.902Z] error 
                        CREATE TABLE `items` (
                          id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
`id` varchar(255)  NULL ,
`summary` longtext  NULL ,
`title` varchar(255)  NULL ,
`created_at` timestamp DEFAULT CURRENT_TIMESTAMP  NULL ,
`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP  NULL 
                        )
                       - SQLITE_ERROR: duplicate column name: id
{ [Error: SQLITE_ERROR: duplicate column name: id] errno: 1, code: 'SQLITE_ERROR' }
```

**Comment by lauriejim** [comment]
Hello! Thank you to report this issue!

**Comment by s-kris** [comment]
Came here to open the exact issue.

**Comment by dave-dm** [comment]
I'm not sure it's a good idea to have `id` a default field. It's a field people will use, like a product id. For example if I remember correctly sequelize uses _id, _dateCreated and _dateModified as default fields.

**Comment by derrickmehaffy** [comment]
@dave-dm and @s-kris having a default  id field is absolutely a good idea as it is required by the typical SQL databases and needs a few requirements that most users might miss.

Users also shouldn't be setting the id manually as this interferes with SQL auto-increment especially with large clustered databases.

Strapi doesn't use sequelize due a lack of many features and instead uses bookshelf and knex

**Comment by derrickmehaffy** [comment]
If you need additional user defined fields I would suggest you add them as you mentioned `productid` ect

**Comment by dave-dm** [comment]
> @dave-dm and @s-kris having a default id field is absolutely a good idea as it is required by the typical SQL databases and needs a few requirements that most users might miss.
> 
> Users also shouldn't be setting the id manually as this interferes with SQL auto-increment especially with large clustered databases.
> 
> Strapi doesn't use sequelize due a lack of many features and instead uses bookshelf and knex

I never said having a default field was a bad idea. I said naming it `id` was a bad idea.

**Comment by derrickmehaffy** [comment]
@dave-dm I'd rather not pull something redundant from Mongo :nauseated_face: 

ID is a standard common practice (heck even mongo has it as a default, along with _id)

> Taken from many people but summarized down:
> 
> I don't consider it bad practice. Consistency is king, as usual.
> 
> I think it's all about context. In the context of the table on its own, "id" just means exactly what you expect, a label to help uniquely identify it against others that might otherwise be (or appear) identical.
> 
> In the context of joins, it's your responsibility to construct the joins in such a way as to make it readable to you and your team. Just as it is possible to make things look difficult with poor phrasing or naming, it is equally possible to construct a meaningful query with effective use of aliases and even comments.
> 
> In the same way a Java class called 'Foo' doesn't have its properties prefixed by 'Foo', don't feel obliged to prefix your table IDs with table names. It is usually clear in context what the ID being referred to is.

You can very easily name your own fields productid, commentid, blahid, ect. But the universal default for the table will always be id. There is even a pending change to remove all references to _id in the project completely as to remove the conflicts with mongo vs sql.

I'm marking this issue as closed unless @Aurelsicoko, @lauriejim, or @alexandrebodin have their own thoughts.

**Comment by dave-dm** [comment]
> I'm marking this issue as closed unless @Aurelsicoko, @lauriejim, or @alexandrebodin have their own thoughts.

well there's still the bug that if you do it without knowing, it breaks the database and no longer starts, with no indication on how to fix it

**Comment by Aurelsicoko** [comment]
The original issue is to ignore a field named `id` and display a warning to give explanations. It's a common practice to use `id` as a primary column in any tables.

Anyway, @dave-dm can you share your use case and why do you absolutely need to name your column `id` instead of `productId`?

**Comment by dave-dm** [comment]
I don't absolutely need to, it was just my recommendation to name it something else, because people like me will want to use it. You should fix the fact that it breaks the database if you use it without knowing you're not supposed to though.

And I do agree that it's common practice to use `id` as primary column, the difference is when I do that in my databases I have the choice to call it `my-product-name` if I want.

**Comment by Aurelsicoko** [comment]
Okay, I have a better understanding of the need here. It doesn't seem to be a priority but it makes sense to allow it in the future even if it will certainly require a lot of changes and verifications in the codebase...

**Comment by s-kris** [comment]
> I don't absolutely need to, it was just my recommendation to name it something else, because people like me will want to use it. You should fix the fact that it breaks the database if you use it without knowing you're not supposed to though.
> 
> And I do agree that it's common practice to use `id` as primary column, the difference is when I do that in my databases I have the choice to call it `my-product-name` if I want.

I feel the same. For now, you guys should just give an alert if someone is using 'id' as field name.
