### ISSUE TITLE
Destroy lifecycle callbacks support with Mongo

### ISSUE THREAD

**Issue by suhamera** [strapi/strapi#3294]
The documentation (https://strapi.io/documentation/3.x.x/guides/webhooks.html) describes that Until September 2018, remove lifecycle callback supported by Mongoose and gives an example of how you can add it yourself.

But this instruction is either outdated or not suitable at all.

The instructions say that you need to add the following line:
request.post (strapi.config.currentEnvironment.staticWebsiteBuildURL, entry);

But, in the described methods there is no entry, and when using the strapi.config.currentEnvironment.staticWebsiteBuildURL parameter, an error occurs: Error: options.uri is a required argument.

So how to add Destroy lifecycle callbacks?

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
