### ISSUE TITLE
MongoDB connection timeout

### ISSUE THREAD

**Issue by mariorodriguespt** [strapi/strapi#3295]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**:  6.4.1
- **Strapi version**: strapi v3.0.0-alpha.26.1
- **Database**: MongoDB
- **Operating system**: macOs Mojave

**What is the current behavior?**
I'm running a data migration using javascript that fetches data from an API and uses bulks writes to store in mongo. After about 8 minutes, I get error log saying the connection had a timeout. I tried to find a way to configure the mongoose connection config option but after checking the code I found it is not possible to do so.

As a result data is loss because of this timeout.

**Steps to reproduce the problem**
Create a function that writes to the database and let it run until it burns.

**What is the expected behaviour?**
I would expect the migration to go smoothly without losing the database connection. I'm using bulk operations with expression like `$min`, `$max`, etc. This mean the bulk operation is not a trivial one and will take some time to persist to mongo.

**Suggested solutions**
Allow mongoose connection config options.

**Comment by lauriejim** [comment]
This issue should be fixed in the beta since we review the query system.
I close this issue, will reopen it if needed.
