### ISSUE TITLE
Use model in afterUpdate with MongoDB

### ISSUE THREAD

**Issue by suhamera** [strapi/strapi#3296]
In general, if you use a Lifecycle callbacks, for example for afterCreate, everything works fine. Really returns an object with which you can do something.

But afterUpdate returns a rather complicated answer that cannot even be parsed (Converting circular structure to JSON) - so how to work with the model in this case? At least find out the objects with which Id have been changed?

**Comment by lauriejim** [comment]
Hello! I will answer to your question but.
Please next time follow the issue template. I don't have all information to be able to answer you correctly.
Strapi version and database you use. Template are here for a reason.

Well now your question.
Please check this article, there is an example about the usage of that part of Strapi http://help.strapi.io/customize/autofill-field
