### ISSUE TITLE
Database name from uri is override by default json value

### ISSUE THREAD

**Issue by mariorodriguespt** [strapi/strapi#3297]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**:  6.4.1
- **Strapi version**: strapi v3.0.0-alpha.26.1
- **Database**: MongoDB
- **Operating system**: macOs Mojave

**What is the current behavior?**

According to this closed [ticket](https://github.com/strapi/strapi/issues/432), you can add a `uri` params in your database configuration to connect to a mongo database. I found that strapi completely ignores the database specified in the `uri`.

Example: `mongodb+srv://admin:root@somewhere.net/yourDB`
`yourDB` is not used.

**Steps to reproduce the problem**

1 - Use Mongo Atlas free tier account
2 - Create a brand new repo with strapi with the `uri` for Mongo Atlas
3 - Run strapi
4 - Create a user
5 - Check Mongo Atlas and you'll find a new database named `strapi` instead of the intended database specified in the `uri`

**What is the expected behavior?**

I expect strapi to use the database specified in the `uri`

**Suggested solutions**

In case you're struggling  with this issue, I found a fix: add the `uri` and the `database` with your database name. This way Strapi will connect to the proper database.

**Comment by lauriejim** [comment]
Hello! 
Yes the database name looks override by the default value.
The update have to be done here https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js to make sure to use the uri database name.

**Comment by asherccohen** [comment]
I would like to point out that there is still some confusion about the right URI for Atlas.

Apparently the Atlas docs all state to use the 3.0+ version of the string which looks like:
`mongodb+srv://<username>:<password>@<cluster>/<dbname>?retryWrites=true&w=majority`

but the strapi docs suggest to use the old version which looks like:
`mongodb://<username>:<password>@<cluster list with port>/<dbname>?ssl=true&replicaSet=<replicaSet>&authSource=admin&retryWrites=true&w=majority`

Which one is correct and please update the docs.

**Comment by lauriejim** [comment]
You will need to use `Version: 2.2.12 or later` as mentioned into the documentation.

The uri database name is no longer override by the default database name.
