### ISSUE TITLE
Can`t run dev admin panel | Duplicate declaration "ReducerInjector" and Duplicate declaration "InjectSaga"

### ISSUE THREAD

**Issue by olehvoitenko** [strapi/strapi#3298]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

I have installed the strapi locally and trying to run the admin panel in dev mode, but got 
**Duplicate declaration "ReducerInjector" and Duplicate declaration "InjectSaga"** errors.

http://prntscr.com/nqfzbc

I have set up it based on this tutorial: https://jeanlescure.io/blog/customizing-strapi-admin-ui/

**Steps to reproduce the problem**
1. npm uninstall -g strapi
2. git clone strapi...
3. npm run setup && cd ..
4. strapi new admin-dev --dev
5. cd admin
6. npm start

Got the error: http://prntscr.com/nqfzbc

**What is the expected behavior?**
The admin panel will be running without the error;

Thanks a lot!

**Comment by lauriejim** [comment]
Hello! 
Can you be sure you clean well you strapi with `rm -rf $(npm root -g)/strapi*`
I just tried your step after a clean and it works.
> I was on node 11 but I'm not sure it can from here.
