### ISSUE TITLE
strapi.backendURL isn't changed after configuration

### ISSUE THREAD

**Issue by dkarski** [strapi/strapi#3299]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**
In **DEVELOPMENT** mode

I have installed the strapi locally and remotly. When I tried changed `backendURL` for both envirmoment like in documentation: [configurations.html#custom](https://strapi.io/documentation/3.x.x/configurations/configurations.html#custom) or [customize-admin.html#deployment](https://strapi.io/documentation/3.x.x/advanced/customize-admin.html#deployment)
Itsn't work... requests for `users-permissions/init` and `content-type-builder/autoReload` after run admin panel is sended to host not `BackendURL` which I set in configure files. Configured files dosen't work even by setup application.

When I overvrite `backendURL` in rutime application. Request is sended to execpation server not to host.

**Steps to reproduce the problem**
Change configure file to your backend url server like in documetation:
[configurations.html#custom](https://strapi.io/documentation/3.x.x/configurations/configurations.html#custom)
[customize-admin.html#deployment](https://strapi.io/documentation/3.x.x/advanced/customize-admin.html#deployment)

**What is the expected behavior?**
When I change `backendURL` in configure file all request is send to backendURL not host

**Suggested solutions**
Check `backendURL` is configurable. I suggest start from here:
[packages/strapi/lib/core/admin.js#L58](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/admin.js#L58)

Backend set default attribute to `/` even not set by `config`. 

While frontend check if attribute is set then it leave configuration.
[packages/strapi-admin/admin/src/public-path.js#L19](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/public-path.js#L19)

**Comment by lauriejim** [comment]
Hello! 

In the first link [configurations.html#custom](https://strapi.io/documentation/3.x.x/configurations/configurations.html#custom) the configuration is just an example for the usage of configuration. These configurations don't have any impact on your application.

Can you explain me what you are trying to do (the reason why your are trying to update this value) because I'm not sure to understand.

If it's because you have your admin hosted in an server than your Strapi application you will have to follow these instructions https://strapi.io/documentation/3.x.x/advanced/customize-admin.html#deploy-the-administration-panel-on-another-server-aws-s3-azure-etc-than-the-api

**Comment by dkarski** [comment]
Hi!

@lauriejim deploying on different servers work for **production** but not for **development** by condicion https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/admin.js#L58

It's now I deploy application only with **production** envirmoment but it's not clear that it not work for **development**. Maybe you should add information about it in the documentation?

**Comment by lauriejim** [comment]
Ho yes, it's because in `development` you normally don't need to use different servers for that.
So we did not offer you this feature in `development`.

**Comment by dkarski** [comment]
ok, It's sounds clear for me now. Thank you for your attention.
