### ISSUE TITLE
Mongoose config and api creation

### ISSUE THREAD

**Issue by kmathy** [strapi/strapi#330]
**Node.js version**: 8.1.2
**npm version**: 5.5.1
**Strapi version**: v3.alpha.6.4
**Operating system**: Windows 10 (using Bash On Windows to launch mongo server)

Firstly, congrats for the great framework, I follow you since several months 👍 

But I have a quite weird issue when creating the API using mongoose.
When installing Strapi, I had to link strapi and strapi-mongoose because of npm permissions. Not a problem.
When I override some configurations to connect to my DB, I had an error inside the node_modules, and I had to fix this bug to make it work:
strapi-mongoose, "Cannot read property 'mongoose' of undefined
C:\Users\kmathy\AppData\Roaming\npm\node_modules\strapi-mongoose\lib\index.js:49:104
```
const {host, port, username, password, database} = _.defaults(connection.settings, strapi.hooks.mongoose.defaults);
```
It seems it was 'hooks' the devil 😈 . After set it to 'hook', it worked properly.

But another problem occurred when add a new document in my collection. It is just an article containing 3 properties: title (string), description (string), content (text). I just set these with 'Test'.
```
ERROR (11736 on ADN-BE-103P): Cannot read property 'map' of undefined
    TypeError: Cannot read property 'map' of undefined
    at Function.findOne (C:\Users\kmathy\Documents\ADNEOM\backend_projet\blog-backend\plugins\content-manager\config\queries\mongoose.js:22:34)
    at Function.update (C:\Users\kmathy\Documents\ADNEOM\backend_projet\blog-backend\plugins\content-manager\config\queries\mongoose.js:44:51)
    at Function.create (C:\Users\kmathy\Documents\ADNEOM\backend_projet\blog-backend\plugins\content-manager\config\queries\mongoose.js:34:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
It seems it is this function:
```
findOne: async function (params) {
    return this
      .findOne({
        [this.primaryKey]: params[this.primaryKey] || params.id
      })
      .populate(this.associations.map(x => x.alias).join(' '));
  },
```
So, I'm quite blocked with these issues, so I'm waiting for your feedback 😄

**Comment by Aurelsicoko** [comment]
@kmathy Thanks for the kind words! We really appreciate :)

I think you found an issue! You're right `strapi.hooks` don't exist, everything is singular. So  `strapi.hook` is the right path. Feel free to submit a PR by following the [CONTRIBUTING guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#repository-organization).

Can you log `console.log(this)` in the `findOne` function?

**Comment by kmathy** [comment]
[bug_item.log](https://github.com/strapi/strapi/files/1450075/bug_item.log)
Here is what I found with `console.log(this)`

For the contribution, I will do that tonight :)

**Comment by kmathy** [comment]
I'm sorry but I'm not able to do the bug fix. 

I've followed the steps inside the contribution guide but I encountered a problem when creating the project with `strapi new`.
Also, it takes a long time to setup it (more than 20min).

Maybe someone else can do the fix? :)

**Comment by lauriejim** [comment]
Hi @kmathy your bugs have been fixed in our last alpha version. Can you install it and tell me if it work fine now.

**Comment by kmathy** [comment]
I try it this afternoon!

**Comment by kmathy** [comment]
Hi,

Great news, it works! I reinstalled all strapi and create a new model + document, and no error triggered ;)
Well done!

Just one thing:
I tried to install strapi with Yarn and there was an issue, see this [picture](https://user-images.githubusercontent.com/15690980/32693178-95691ea2-c726-11e7-90fb-0fd0d9890b0c.png)

As you can see, you recommend to use Node 8, but I had 8.1.2, and it seems we need 8.1.4 at least. Maybe we can have potential problems if we don't have the correct version (because NPM didn't raise the error)

However, Good work, go on this way! Love from Belgium!

**Comment by zaamx** [comment]
Hi!,

@kmathy  can you please tell me how to connect moongose in windows 10 bash?

I change the npm to another path as the instructions details.

then: 

- Install Mongo in bash
- Create the strapi db in mongo
- Install Strapi in Bash
- Create a Project
- Configure the Mongo connection 
- Create a model

And at this point trows error.

```
/mnt/d/Dev/bolsa/work/node_modules/mongodb/lib/mongo_client.js:433
          throw err
          ^

TypeError: Cannot assign to read only property 'mongoose' of object '#<Object>'
    at loadedModule.initialize.call.err (/home/alonso/.npm-global/lib/node_modules/strapi/lib/hooks/index.js:32:25)
    at NativeConnection.instance.connection.on (/mnt/d/Dev/bolsa/work/node_modules/strapi-mongoose/lib/index.js:79:20)
    at emitNone (events.js:105:13)
    at NativeConnection.emit (events.js:207:7)
    at /mnt/d/Dev/bolsa/work/node_modules/mongoose/lib/connection.js:860:13
    at connectCallback (/mnt/d/Dev/bolsa/work/node_modules/mongodb/lib/mongo_client.js:515:5)
    at /mnt/d/Dev/bolsa/work/node_modules/mongodb/lib/mongo_client.js:430:11
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

It's a error with the connection ?

I new to Strapi, 

Tnks and excuse my english.

**Comment by Aurelsicoko** [comment]
The issue has been fixed, I close. Feel free to open it again if a similar issue comes in.
