### ISSUE TITLE
Reset password link not working

### ISSUE THREAD

**Issue by Otavioensa** [strapi/strapi#3306]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.9.0
- **Strapi version**:  strapi@3.0.0-alpha.25.2
- **Database**:  PostgreSQL
- **Operating system**: Linux (Heroku)
- **Link to your Project**: https://github.com/Otavioensa/buy-my-stuff-cms

**What is the current behavior?**
The link sent by email when submitting my email on *Forgot password* section is not working. I receive a 404 - not found when clicking on it

**Steps to reproduce the problem**
1) **Go to the login section and click on "Forgot your password?"** 

![image](https://user-images.githubusercontent.com/7586857/58127651-36005300-7bec-11e9-8010-46ad07846a9c.png)

2) **Fill the email which I want to reset the password and click on "Send Email" button**

![image](https://user-images.githubusercontent.com/7586857/58128229-7dd3aa00-7bed-11e9-9a0e-3db961710e8c.png)

3) **The email for resetting the password is then sent to the email**

![image](https://user-images.githubusercontent.com/7586857/58128248-8926d580-7bed-11e9-895d-9c31b35b35cf.png)

4) Click on the link sent for resetting the password**

![image](https://user-images.githubusercontent.com/7586857/58128324-bd01fb00-7bed-11e9-88b2-a5518866feb1.png)

5) A 404 is returned
![image](https://user-images.githubusercontent.com/7586857/58128364-d60aac00-7bed-11e9-9972-e5ca9b990777.png)

**What is the expected behavior?**
The "reset password" link to work

Obs: I have removed the parts with my email info

**Comment by Otavioensa** [comment]
Update: 
I've checked the routes at **/plugins/user-permissions/config/reoutes.json** an there isn't a GET route for such link in fact (That's why I get a 404).
So how an admin user is supposed to reset the password via dash once this route does not exist?

**Comment by Otavioensa** [comment]
Update: 
I've checked the routes at **/plugins/user-permissions/config/routes.json** an there isn't a GET route for such link in fact (That's why I get a 404).
So how an admin user is supposed to reset the password via dash once this route does not exist?

**Comment by melaLetics** [comment]
I've got another problem with the reset password functionality. After receiving email and clicking the link, I just see the loading circle. Also when trying to open http://localhost:1337/admin. 
There is no way to get back to admin panel...

**Comment by lauriejim** [comment]
Hello! I just tried and it works well.
Make sure you are using the last version of Strapi (alpha.26.2)

**Comment by melaLetics** [comment]
I'm using 
Node.js : v10.15.0
NPM: 6.9.0
strapi : 3.0.0-alpha.26.2
Database: Mongo
Operating System: Windows 10

I destroyed the admin panel very often. What can I do to repair? I still see the loading circle when starting strapi so no possibilty to use the cms.

**Comment by lauriejim** [comment]
Did you have an error in your browser console ?

**Comment by Otavioensa** [comment]
Hey @lauriejim !
I've just tried updating the version to 3.0.0-alpha.26.2 but still won't work!
![image](https://user-images.githubusercontent.com/7586857/58344155-54a05d00-7e2b-11e9-9862-cf8a6895f4a0.png)

 I'm testing on Heroku and I do receive the email but once I click on the link I still get 404. Is there any reason why couldn't it work on Heroku? And how does it work if there isn't a GET handler for it? 😕 
![image](https://user-images.githubusercontent.com/7586857/58344332-c5e01000-7e2b-11e9-9099-265feae97285.png)

I'm struggling with this problem for a week :(

**Comment by Otavioensa** [comment]
Anyone who could help? Maybe @lauriejim ?

**Comment by Otavioensa** [comment]
@lauriejim 
Could you perhaps give more detail on how the test was made? 
I was wondering if it was tested on Heroku too

**Comment by lauriejim** [comment]
I tested it again with Heroku and it works well.
![Screenshot 2019-06-10 at 18 14 56](https://user-images.githubusercontent.com/5716596/59209482-b42c9580-8bab-11e9-897e-8b6d11d006c6.png)
![Screenshot 2019-06-10 at 18 14 48](https://user-images.githubusercontent.com/5716596/59209485-b4c52c00-8bab-11e9-84a6-b2881b8d8d7c.png)

**Comment by cotyhamilton** [comment]
@lauriejim what happens when you click the reset password link? It's never worked for me either. Last I tried was with the latest alpha and PostgreSQL

**Comment by lauriejim** [comment]
@cotyhamilton Did you receive an email with the reset password link ?

**Comment by lauriejim** [comment]
@Otavioensa any news on your side?

**Comment by Otavioensa** [comment]
Hey @lauriejim  
I'm working in other stuff but I'm still running on the same problem; Idk what is possibly wrong with my solution :(

**Comment by cotyhamilton** [comment]
Oh @laurijim I see in your comment that the link works, I overlooked that. I can test again soon with the beta, I upgraded a couple days ago, and will report back with more information.

**Comment by cotyhamilton** [comment]
Strapi 3.0.0-beta.7 running locally on docker
MacOS Safari

I no longer have any issues with the password reset, works perfectly as expected

**Comment by lauriejim** [comment]
Okay so I can close this issue.
