### ISSUE TITLE
How to get context or Current user in Function beforeSave

### ISSUE THREAD

**Issue by pnl107** [strapi/strapi#3309]
**Informations**
- **Node.js version**: v10 -->
- **NPM version**:  6.1
- **Strapi version**: 3.0.0@alpha26.0.2
- **Database**:  mysql
- **Operating system**:  Mac os

![image](https://user-images.githubusercontent.com/39798640/58151258-4fa8a580-7c93-11e9-9e08-0645f7da01a6.png)

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello! 

You can't access to the `ctx` inside these functions.
We know this and we will work on a new way to implement **lifeCycle** function.

Current function are based on the ORM life cycle and we have many issues related to the multi call on update or other.

Sorry for this. I suggest you to implement this logic in your service instead of in the life cycle function.

**Comment by Salman2301** [comment]
@lauriejim  can u provide an example for the alternate solution?

**Comment by gtamas** [comment]
@lauriejim 
Any news on this?

**Comment by lauriejim** [comment]
Sadly nop

**Comment by giacomocerquone** [comment]
see https://github.com/strapi/strapi/discussions/6871#discussioncomment-84978

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/auto-fill-created-by-field/293/4

**Comment by nikita-fuchs** [comment]
A workaround to make possible exactly what OP asked for can be found in this tutorial (starting around the middle) https://www.youtube.com/watch?v=AsEGCzFiWTM

**Comment by fatima-elmouhine** [comment]
yes you can access the context in a lifecycle by doing this : 
        const ctx = strapi.requestContext.get();
        const userId = ctx.state.user.id;
        
  It works fine for me 🤙

**Comment by TheRealBarenziah** [comment]
> yes you can access the context in a lifecycle, if you do this : const ctx = strapi.requestContext.get(); const userId = ctx.state.user.id;
> 
> It works fine for me 🤙

Not sure why people are thumbing down this solution...

This is indeed working fine and [documented to work with strapi v4.3.9+](https://web.archive.org/web/20240304044826/https://docs.strapi.io/dev-docs/backend-customization/requests-responses#accessing-the-request-context-anywhere)

I've used both solutions and I can confirm to future visitors:
- If you're using strapi v3, [nikita-fuchs's 2022 workaround](https://www.youtube.com/watch?v=AsEGCzFiWTM) (dare I say hack?) will do the job.
- If you're using strapi v4.3.9 or above, [fatima-elmouhine's solution](https://web.archive.org/web/20240304044826/https://docs.strapi.io/dev-docs/backend-customization/requests-responses#accessing-the-request-context-anywhere) is official and definitely the cleanest.
