### ISSUE TITLE
listen on entity changes to call another API

### ISSUE THREAD

**Issue by amiiy** [strapi/strapi#3310]
Hi. I wanted to add an integration with the [POS system ](https://developers.iqmetrix.com/api). now I want to Call POS API to update product name, description, images and any other product detail that is changed on the admin panel product edit pages. what is the best way to doing this? should I put a hook on models when some product change, to call the API? or put it on add/update services?
I thought it would be better to be something like listeners or signals which omit an add/update event when some entity change and this way it's could catch and dispatch request in the separate workflow that main application work.

**Comment by Otavioensa** [comment]
I think the best way of doing it is [by making the request call on the hook model part once the product is updated](https://strapi.io/documentation/3.x.x/guides/webhooks.html)
