### ISSUE TITLE
Can i use EC2 Roles on strapi-provider-upload-aws-s3 credentials?

### ISSUE THREAD

**Issue by luizbueno-hotmart** [strapi/strapi#3312]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

Hi people from Strapi. 

I would know if can i use EC2 Roles on strapi-provider-upload-aws-s3 credentials.

Or can i get strapi-provider-upload-aws-s3 credentials using a environment variables or get it on a separate file.

Thanks!

**Comment by lauriejim** [comment]
Hello!

We are using `aws-sdk` node module to connect to AWS services.
📚https://aws.amazon.com/fr/sdk-for-node-js/

You will be able to see the way to **login** and it use `access` and `secret` keys.

```
AWS.config.update({
  accessKeyId: config.public,
  secretAccessKey: config.private,
  region: config.region
});
``` 

So I'm not sure it's possible to connect with roles.

We will work on the way we manage environments and secret variables!
For now it's not possible to use env variable as `secret` and `access` key.

But you can **fork** this module and add this possibility to use env variables.

Thank you for this question / feedback!

**Comment by luizbueno-hotmart** [comment]
Thanks for your answer @lauriejim .

I got another question for you: in addition of the access key, theres a way to inform a session token?

`aws_access_key_id: << aws acess key >>
aws_secret_access_key: << aws secret acess key >>
aws_session_token: << aws session token >>`

Besides of this question, with aws-sdk there is an option to give permissions to EC2 instances and ECS instances using IAM Role instead of IAM User. So we can use this option too?

Using this method the permission to access a given resource (in our case an s3 bucket) is given in runtime by a policy definition.

In this way we don't rely on access keys and access secrets that can leak or that need to be rotated.
The aws-sdk works with this by default, as when a profile is not specified and an IAM User key/secret is not defined it will fallback to the IAM Role method, getting the policy attached to the container/instance. 

Therefore, to enable this functionality a way to select the policy method to access AWS resources are needed AND with IAM User method the functionality remain as is but with IAM Role theres no need to define an access key nor secret key.

Thanks again for your help and support.

**Comment by lauriejim** [comment]
You will have to customize this provider to add this `aws_session_token` as available option.

Here is to add input options in the config view https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-aws-s3/lib/index.js#L21

And here is where you set the AWS SDK settings https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-aws-s3/lib/index.js#L57

**Comment by gamanox** [comment]
> Thanks for your answer @lauriejim .
> 
> I got another question for you: in addition of the access key, theres a way to inform a session token?
> 
> aws_access_key_id: << aws acess key >>
> aws_secret_access_key: << aws secret acess key >>
> **aws_session_token: << aws session token >>**
> 
> Besides of this question, with aws-sdk there is an option to give permissions to EC2 instances and ECS instances using IAM Role instead of IAM User. So we can use this option too?
> 
> Using this method the permission to access a given resource (in our case an s3 bucket) is given in runtime by a policy definition.
> 
> In this way we don't rely on access keys and access secrets that can leak or that need to be rotated.
> The aws-sdk works with this by default, as when a profile is not specified and an IAM User key/secret is not defined it will fallback to the IAM Role method, getting the policy attached to the container/instance.
> 
> Therefore, to enable this functionality a way to select the policy method to access AWS resources are needed AND with IAM User method the functionality remain as is but with IAM Role theres no need to define an access key nor secret key.
> 
> Thanks again for your help and support.

Hi @luizgringo 

Did you manage to define a IAM role in the request? thanks

**Comment by dgokcin** [comment]
hi @luizgringo @gamanox  did you manage to use the plugin without access keys and secret keys?
