### ISSUE TITLE
Custom resolver returns "TypeError: Cannot read property 'primaryKey' of undefined"

### ISSUE THREAD

**Issue by greatwitenorth** [strapi/strapi#3313]
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: 6.5
- **Strapi version**: 26.2
- **Database**: mysql
- **Operating system**: macOS

**What is the current behavior?**
When I try to execute a custom resolver via graphql I get the following error:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'primaryKey' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "dealersWithinRange"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'primaryKey' of undefined",
            "    at /Users/nickv/Projects/brett-young-cms-strapi/plugins/graphql/services/Query.js:249:27"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Steps to reproduce the problem**
I created a model called 'dealer' with a custom resolver in `api/dealer/schema.graphql.js`
```js
module.exports = {
  query: `
    dealersWithinRange(lat: Float, lng: Float, radius: Int): [Dealer!]!
  `,
  resolver: {
    Query: {
      dealersWithinRange: {
        description: 'Find dealers within a specified radius of coordinates',
        resolver: 'Dealer.findWithinRange'
      },
    },
  },
};
```

my controller method:
```js
  findWithinRange: async (ctx) => {
    const {_lat, _lng, _radius} = ctx.params;
    return strapi.services.dealer.fetchWithinRange(_lat, _lng, _radius);
  },
```

and my service:
```js
  fetchWithinRange: (lat, lng, radiusInKm) => {
    radiusInKm = radiusInKm ? radiusInKm : 100;

    const distanceInKmsSql = `( 6371 * acos( cos( radians(${lat}) ) 
          * cos( radians( lat ) ) 
          * cos( radians( lng ) - radians(${lng}) ) 
          + sin( radians(${lat}) ) 
          * sin( radians( lat ) ) ) ) AS distance 
        `;
console.log(distanceInKmsSql)
    const populate = Dealer.associations
      .filter(ast => ast.autoPopulate !== false)
      .map(ast => ast.alias);

    return Dealer.query(qb => {
      qb.column(['*', strapi.connections.default.raw(distanceInKmsSql)]);
      qb.having('distance', '<=', radiusInKm);
      qb.orderBy('distance');
    }).fetchAll({
      withRelated: populate
    });
  },
```

When I try to execute this query using the following I get the above error:
<img width="1438" alt="Screenshot 2019-05-22 15 20 12" src="https://user-images.githubusercontent.com/547583/58205872-1f6a0280-7ca5-11e9-96eb-79e21f480dad.png">

**What is the expected behavior?**
I exepct to see the dealers within the range.

**Suggested solutions**
I can see that `model.primaryKey` was added in several places to `plugins/graphql/services/Query.js`:

https://github.com/strapi/strapi/blob/08a4f6f51492f0f1a8410876cfd5d7c92405fc5d/packages/strapi-plugin-graphql/services/Query.js#L249-L263

When I remove `model.primaryKey` from line 252 and 259, everything works as expected.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2973

> This is a templated message
