### ISSUE TITLE
Strapi crahes if you start typing into a one-to-one relational dropdown that is already filled with a relation

### ISSUE THREAD

**Issue by steampixel** [strapi/strapi#3317]
**Informations**
- **Node.js version**: 10.6.0
- **NPM version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: Linux
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Strapi will crash if you start typing into a relational dropdown field that is already filled

**Steps to reproduce the problem**
1. Create a new strapi project
2. Create a new content type named "product" with only one string field called "name"
3. Create a second content type called "shop" with a string field called "name"
4. Create a One-To-One relational field on the "product" type that links to the shop documents. 
5. Create your first shop by switching to the shop list and give it a name like "testshop"
6. Create your first product "test product" and link it to the new shop
7. Reopen the newly ceated product and focus the relational shop dropdown field
8 Start typing something

**What is the expected behavior?**
Show the list with the search results

**Suggested solutions**
I have discovered that this bug only occures if the field is already filled with a relation. If you delete the relation using the X button inside the field, the problem will not occure.

There is also a very strange HTTP-Request that might fail and cause the server to crash: 

`http://192.168.188.116:1337/content-manager/explorer/shop/[object Object]?source=content-manager&name_contains=foo`

This request should query the search results after every input. But the [object Object] in the URL makes not much sense.

As I already mentioned this error has something todo with already connected relations. If I use the X button first the request will look like expected if I start typing:

`http://192.168.188.116:1337/content-manager/explorer/shop/?source=content-manager&name_contains=media`

**Comment by lauriejim** [comment]
Hello! Yes you are right!
Thank you for this report.

**Comment by soupette** [comment]
The selects have been updated in #3633 and the bug is fixed.
