### ISSUE TITLE
Simple grahpql on users gives error about "email" field

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3320]
**Informations**
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**:  mongo
- **Operating system**: 

**What is the current behavior?**
Getting error `Error: Your filters contain a field 'email' that doesn't appear on your model definition nor it's relations`

**Steps to reproduce the problem**
Try doing the graphql query 
```
{
  users(where: {email_contains: "@nexion.com.ar"}) {
    email
    username
    avatar {
      url
      __typename
    }
    __typename
  }
}
```

**What is the expected behavior?**

Get results

**Suggested solutions**

![graphql-users](https://user-images.githubusercontent.com/517228/58349821-af8d8080-7e3a-11e9-9c77-31af943e94a1.png)

**Comment by alexandrebodin** [comment]
@jacargentina Hi, 

I cannot reproduce your bug on alpha26.2.

Have you made any modifications to your user model ? (can you share it)

If you could provide an example repo with the same error or at least steps to reproduce it will help a lot !

**Comment by jacargentina** [comment]
It was an error on my updating to newer strapi. Closing.
