### ISSUE TITLE
POST request to GET a list of items

### ISSUE THREAD

**Issue by EzequielRamis** [strapi/strapi#3321]
**Informations**

    Node.js version: v10.14.1
    NPM version: v6.9.0
    Strapi version: v3.0.0-alpha.26.2
    Database: PostgreSQL
    Frontend: Nuxt.js
    Operating system: Windows 10

**What is the current behavior?**
Having to make a GraphQL POST request to GET a list of items.
If I do make a GET request I get the following error:

![Screenshot_2019-05-25 Screenshot](https://user-images.githubusercontent.com/44057100/58373674-3c524000-7f08-11e9-98d3-3d5bf1dba168.png)

**Steps to reproduce the problem**
In the `strapi.request` first parameter I put the request type. In this case `get`

![Captura de pantalla (38)](https://user-images.githubusercontent.com/44057100/58373724-25f8b400-7f09-11e9-9aae-ae0751cb211b.png)

**What is the expected behavior?**
I get the list of items to consume

**Suggested solutions**
N.A

**Comment by derrickmehaffy** [comment]
@EzequielRamis there is no get requests in graphql, strapi doesn't build the graphql part as that is Apollo.

Reason for no get requests is a single endpoint the server doesn't know what you want.

**Comment by EzequielRamis** [comment]
@derrickmehaffy So are there only three type of requests? post, put and delete?

**Comment by derrickmehaffy** [comment]
No with graphql there is only POST, graphql is a query language, meaning it only responds to a question, meaning you are POSTing your question

**Comment by EzequielRamis** [comment]
@derrickmehaffy Ok thanks, I'll keep learning
