### ISSUE TITLE
Admin backend does not show json field content posted from Swagger UI (documentation plugin)

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#3323]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: v3.0.0-alpha.26.1
- **Database**: MongoDB 4.0.3
- **Operating system**: macOS 10.14.5
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Fields with type "json field" fails to load into admin backend when posted via Swagger UI or curl. The *data is saved* and can be viewed directly in the database, retrieved via Swagger UI, or requested via curl. 

Fields with type "json field" do save and load properly when the save and load comes from the admin backend.

**Steps to reproduce the problem**
1. Create a content type called Location (or whatever) that has at least one json field. 
2. Using the Swagger UI (documentation interface in strapi), add (POST) a new Location using the Swagger UI
3. In the Swagger UI list (GET) all locations. The location you added in step 2, along with the json field content are listed as having saved properly. Note the ID from the response body field: 
![image](https://user-images.githubusercontent.com/8559668/58385763-3dd44480-7faa-11e9-97a1-3aa88d899856.png)

4. Viewing the entry for this id in the strapi admin backend: 
![image](https://user-images.githubusercontent.com/8559668/58385786-a28f9f00-7faa-11e9-9cc2-9e4e653cd85d.png)

**What is the expected behavior?**
The strapi backend should show entries that have been created via the Swagger UI (curl, etc...) in the same way that it shows entries that have been created using the strapi admin backend:
![image](https://user-images.githubusercontent.com/8559668/58385818-2b0e3f80-7fab-11e9-909e-3b1cc7f6b86f.png)

**Suggested solutions**
I'm avoiding using the strapi backend to view and edit entries that contain json fields; no big deal.

Thanks for looking into this guys!

-Dan

**Comment by cube-dan** [comment]
Addendum:

Entries that have been created using other than the strapi admin backend also don't show content in lists, for example this backend url: `/admin/plugins/content-manager/location?_limit=10`
![image](https://user-images.githubusercontent.com/8559668/58386089-a40f9600-7faf-11e9-9f9e-5d0c60aaa965.png)

Data *is saved* properly however. Here's a screenshot from Robo 3T, a mongodb UI:
![image](https://user-images.githubusercontent.com/8559668/58386119-fbae0180-7faf-11e9-977a-e1027c47a502.png)

**Comment by lauriejim** [comment]
Hum this is weird, I just reproduce your steps and it work on my side.

**Comment by cube-dan** [comment]
Maybe I'm not posting the json correctly? What information can I provide to help debug this?

-Dan

**Comment by cube-dan** [comment]
Jim, 

Attached is a .json file I made using [mongodump](https://docs.mongodb.com/manual/core/backups/#back-up-with-mongodump) then unpacking the .bson output with [bsondump](https://docs.mongodb.com/manual/reference/program/bsondump/) to get something human readable. 

File: [location.json.txt](https://github.com/strapi/strapi/files/3249277/location.json.txt)

This file contains two Location entries. The first one was stored by strapi, the 2nd by the API. 

I think the critical difference here is that to get the Swagger UI to accept the json I have to encode the json as a string or I get a message like this:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Unexpected token } in JSON at position 5418"
}
```

Here's a screenshot of the two entries in Robo T3:
![image](https://user-images.githubusercontent.com/8559668/58830716-c6349400-85ff-11e9-90e9-7793f028ab3d.png)

After comparing the two entries I think the issue here is on my end. I'm obviously not posting the json properly (as a string) and it's confusing strapi's backend when I try to read from an entry that has escaped json in it.  

Thanks for taking a look, feel free to close this ticket.
