### ISSUE TITLE
I can not authenticate using localhost: 3000 only with localhost: 1337

### ISSUE THREAD

**Issue by Mateussmo** [strapi/strapi#3324]
**Informations**
- **Node.js version**:  10.15.3
- **NPM version**:  6.4.1
- **Strapi version**:  3.0.0-alpha.26.2
- **Database**:  MongoDB
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
In Google's Provider, when I put it localhost:1337  on field "The redirect URL to your front-end app"  I can Authenticate with google. But when I try it with localhost:3000 I can not authenticate.

**Steps to reproduce the problem**
I follow theses steps: https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment]
Hello!
Did you try to make it works with the `login-react` app ?

**Comment by Mateussmo** [comment]
I didn't. I Just tried it with the browser. If I access the browser when it's localhost:1337 I can authenticate by Google, but if it's localhost:3000 it doesn't show anything.

**Comment by lauriejim** [comment]
Please can you try. To make sure your application is well configured.
