### ISSUE TITLE
Collection Name with special characters causes Strapi not to boot

### ISSUE THREAD

**Issue by jsve** [strapi/strapi#3326]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: Postgres
- **Operating system**: MacOS

**What is the current behavior?**
When editing the `Collection Name` field, I am allowed to use special characters like `:`. See screenshot:
<img width="591" alt="Screenshot 2019-05-27 at 11 10 01" src="https://user-images.githubusercontent.com/9053945/58409766-0da3a900-8071-11e9-96c8-9873d4160a17.png">

If I save this Content Type, Strapi will no longer boot. 

**Steps to reproduce the problem**
 [ ] Create a new Content Type
 [ ] Select advanced settings
 [ ] add a `:` to the collection name

**What is the expected behavior?**
The shouldn't be a way to set invalid collection names.

**Suggested solutions**
The interface needs to warn and the API shouldn't accept invalid values.

**Fix for others encountering the same issue**
You can manually edit `collectionName` in `ModelName.settings.json` in `/api/modelname/models/` to something that Strapi accepts (i.e remove the `:`or other special character).

**Comment by lauriejim** [comment]
Hello! 
I just tried and it works well.
Did you update the content type you created or you update the User content type ?
