### ISSUE TITLE
Relations are not available in life cycle functions

### ISSUE THREAD

**Issue by renatodex** [strapi/strapi#3329]
**Informations**
- **Node.js version**: 11.1.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.x.x
- **Database**:  Postgresql
- **Operating system**: MacOS
- **Link to your Project**: Not required

**What is the current behavior?**
In the afterCreate callback, when a model has an upload field, it is not present on the model object. 

**Steps to reproduce the problem**
1. Create a content type with an Upload field.
2. Add a afterCreate callback with a console log on the model object.
3. Through the admin, create a new resource, including some image on the upload field.
4. Inspect the Console Log from your callback.

**What is the expected behavior?**
The upload data should be included in the Model object.

**Suggested solutions**
Not sure if only happens with afterCreate (haven't tested other callbacks), but the callbacks should give you an option to include Relations like this, since they are expressly defined on the Content Type, but they don't appear on the callback data.
This could be defined on the Admin itself, or they could be a default at least for Upload fields (since they are a shipped implementation)

**Comment by lauriejim** [comment]
Hello! 
Thank you for your feedback.

We have other issues about the life cycle function.
For this one it's because the entry creation and the file upload are two different function that are just called in the same time in the content manager.
But what happen behind, we first create the entry (without the upload, that is why you don't have access to the file data in the entry life cycle) and the we upload the file and link it to your created entry.

We have a work in our roadmap about the way we manage life cycle function.

**Comment by renatodex** [comment]
Sure,

Its fine, i thought the reason was something like that!
There is some time prediction for the releasing of the Plugins refactory?
This way, we would submit PR's to help to consume the roadmap, we see how people are anxious for the resolution of those issues.

**Comment by lauriejim** [comment]
We are currently reviewing the roadmap.
Will let you know about this topic when I will have a date.

**Comment by renatodex** [comment]
@lauriejim 
Taking that review into consideration, i would suggest that you guys consider to the roadmap tasks related to Data Consistence and Ease of Development, since they will automatically bring more people and make the project more attractive to newcomers.

Tasks like these may look cool for newcomers and business people:
https://portal.productboard.com/strapi/1-public-roadmap/c/37-wysiwyg-html-editor
https://portal.productboard.com/strapi/1-public-roadmap/c/19-content-internationalization
https://portal.productboard.com/strapi/1-public-roadmap/c/51-allow-local-installation-with-yarn-npm
https://portal.productboard.com/strapi/1-public-roadmap/c/50-components-library-release
https://portal.productboard.com/strapi/1-public-roadmap/c/43-2fa-via-users-permissions-plugin

But compared to these ones, from the Data Consistence point of view, the tasks above looks completely zero priority:
https://portal.productboard.com/strapi/1-public-roadmap/c/23-import-export-data
https://portal.productboard.com/strapi/1-public-roadmap/c/14-validations
https://portal.productboard.com/strapi/1-public-roadmap/c/22-delete-unnecessary-tables-collections-columns-in-the-databases
https://portal.productboard.com/strapi/1-public-roadmap/c/57-filter-on-null-value-in-the-generated-api
https://portal.productboard.com/strapi/1-public-roadmap/c/12-migrate-across-environments

**Comment by derrickmehaffy** [comment]
@renatodex I completely agree with you and was just talking with @lauriejim @soupette and @alexandrebodin about this. I think with the beta they are going to be focusing a bit more on bug fixes and core required stuff instead of the "fancy new good looking" features.

**Comment by vnitMendapara** [comment]
Ignoring the importance of upload object in the life cycle event can cause some serious issues when there are many microservices are dependent. Even I am facing the same no-uploaded-object issue for my project, and there is no solution available at this moment. Please include this in the roadmap.

**Comment by clementmas** [comment]
@derrickmehaffy I'm still having this issue (same reproduction steps). A PR was merged but does it resolve file upload relationships?
I'm getting an empty `data.files` array inside `afterCreate(data)`
