### ISSUE TITLE
error (hook:mongoose) takes too long to load

### ISSUE THREAD

**Issue by Rashidul420222** [strapi/strapi#3332]
**Informations**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: MongoDB
- **Operating system**: Windows 10

```
$ strapi start
[2019-05-28T02:48:33.321Z] debug ⛔️ Server wasn't able to start properly.
[2019-05-28T02:48:33.327Z] error (hook:mongoose) takes too long to load
(hook:mongoose) takes too long to load
```

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "flutter-ecommerce-raatb.mongodb.net",
        "port": 27017,
        "database": "server",
        "username": "AShop",
        "password": "rashidul",
        "srv": true
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

or

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "@flutter-ecommerce-raatb.mongodb.net",
        "port": 27017,
        "database": "server",
        "username": "AShop",
        "password": "rashidul",
        "srv": true
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
@Rashidul420222 In the future please give a fairly self explanatory title, please use code blocks, and please follow the bug report template. I have edited your original post.

**Comment by lauriejim** [comment]
Hello!

If you database connection is a little bit to long this error message can happen.
You have to update the `timeout` value in `./config/hook.json`.

**Comment by iram-shehzadi** [comment]
Hello,

I've found it helps to run **strapi start** then **strapi develop**

**Comment by Manish-Kumarr** [comment]
Try to update the ./config/hook.json file like that:

{
  "timeout": 100000,
  "load": {
    "order": [
      "Define the hooks' load order by putting their names in this array in the right order"
    ]
  }
}
