### ISSUE TITLE
GraphQL query returns only first element in nested array

### ISSUE THREAD

**Issue by avdeyev** [strapi/strapi#3335]
**Informations**
- **Node.js version**: v10.15.0
- **NPM version**: 6.9.0
- **Strapi version**: v3.0.0-alpha.26.2
- **Database**: mongo
- **Operating system**: macOS

**What is the current behavior?**

GraphQL query returns only first element in nested array
Example: bookmark related to 2 skills: Git, GraphQL

![image](https://user-images.githubusercontent.com/3809273/58492519-b9382080-8179-11e9-9c2a-e7e63116b991.png)

**Steps to reproduce the problem**

Build many-to-many relationship between two entities

**What is the expected behavior?**

REST works as expected
![image](https://user-images.githubusercontent.com/3809273/58492524-bc331100-8179-11e9-8543-9caad972d9d4.png)

**Suggested solutions**

I guess problem is inside many-to-many mapping in graphql plugin

**Comment by lauriejim** [comment]
Hello!
I just tried your steps and it works well on my side with a fresh new strapi application (alpha.26.2)
Did you migrate your app or it's a fresh new one.

**Comment by avdeyev** [comment]
Yes, I was migrating from 25.2. The only new feature is deep filtering. Did it affect /api content? Should I remake schema from scratch?

**Comment by avdeyev** [comment]
I remigrated again. This time db is empty and new with data it works correctly
