### ISSUE TITLE
enumaration not initilazed at create entity object

### ISSUE THREAD

**Issue by alexis-puska** [strapi/strapi#3336]
**Informations**
- **Node.js version**:  10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26.2 
- **Database**: mongo DB
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: professional project don't care

**What is the current behavior?**
create entity with enumeration failed, when you create entity, the enumaration is set to the first value, but if don't change it and save, the field enumarated is null and not send in graphQL

**Steps to reproduce the problem**
create a entity with enum, don't touch the enum when create en object, observe that filed eenumerated is not null, it's just not present.

**What is the expected behavior?**
field prensent and null !!!!!! cause graphql failed !!!!

**Suggested solutions**
set the field empty with the form, send error with the controller rest

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/2471

> This is a templated message

**Comment by alexis-puska** [comment]
Still here in beta version : 3.0.0-beta.2 !
