### ISSUE TITLE
Inversion in parameters prevents Strapi from returning reason for error when user logs in with Facebook but does not share his or her email

### ISSUE THREAD

**Issue by luc-plamondon** [strapi/strapi#3339]
**Informations**
- **Node.js version**: 11.10.0
- **NPM version**: 6.7.0
- **Strapi version**: v3.0.0-alpha.26.2
- **Database**: 
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Reason of error returned by Strapi is empty when webapp uses Facebook login but the user declines to share his or her email address.

This happens because parameters were inverted in file plugins/users-permissions/services/Providers.js, function getProfile:

`      // We need at least the mail.
      if (!profile.email) {
        return reject([{
          message: 'Email was not available.'
        }, null]);
      }`

"Null" should be the first param passed to reject, and the message should be the second param.

**Steps to reproduce the problem**

1. Call /connect/facebook. 
2. You will be redirected to the Facebook login page if you are not yet logged in to Facebook. Enter your Facebook username and password.
3. You will be redirected to the Facebook authorization page. Choose **not** to share your email.
4. You will be redirected to your web page with the following error: {"statusCode":400,"error":"Bad Request","message":"Bad Request"}

**What is the expected behavior?**

At step 4, Strapi should return the following error (note the reason for the error): 
{"statusCode":400,"error":"Bad Request","message":"Email was not available."}

A reason for the error is required in order to know why the login failed and to instruct the user on how to solve the problem.

It is just a matter of putting the params in the right order in the code above.

**Suggested solutions**

Replace reject call in code above with:
`return reject([null, 'Email was not available.']);`

As a side note, I would suggest the Strapi team adds a page in the doc to clarify how error handling works, so that contributors stick to the same pattern. I am confused because I see two patterns throughout the code: one with only a message (as was intended in the code above) and one with an error id, such as this example taken a few lines further down the file:

`return resolve([null, [{ messages: [{ id: 'Auth.advanced.allow_register' }] }], 'Register action is actualy not available.']);`

That would also help on issue https://github.com/strapi/strapi/issues/2673

**Comment by lauriejim** [comment]
Hello! Thank you for this report!
We are focusing on other issues and features.
You look have well identify the issue and the way to fix it.
Please can you submit a PR. Will really appreciate your help on this topic.

**Comment by lauriejim** [comment]
Fixed by this commit few month ago - https://github.com/strapi/strapi/commit/68cf8ab2313e4ec93f63a8202ba42286d4cf0365
