### ISSUE TITLE
Eumeration field special character causes GraphQL error. 

### ISSUE THREAD

**Issue by loongmxbt** [strapi/strapi#3340]
**Informations**
- **Node.js version**: v10.15.1
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: MongoDB
- **Operating system**: Ubuntu 16.04 LTS
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Entry has a enum field, when add utf-8 characters works fine.
When `strapi install graphql`, error occured
```
1|axconfer |     at Strapi.emit (events.js:189:13)
1|axconfer |     at onFinish (/home/dragonszy/.nvm/versions/node/v10.15.1/lib/node_modules/strapi/lib/hooks/index.js:44:12)
1|axconfer |     at _.forEach (/home/dragonszy/axconfer-api/node_modules/strapi-hook-mongoose/lib/index.js:631:13)
1|axconfer |     at process._tickCallback (internal/process/next_tick.js:68:7)
1|axconfer |   message:
1|axconfer |    'Syntax Error: Cannot parse the unexpected character "\\u57FA".',
1|axconfer |   locations: [ { line: 235, column: 26 } ] }
1|axconfer | 
1|axconfer | > axconfer-api@0.1.0 start /home/dragonszy/axconfer-api
1|axconfer | > node server.js
```
**Steps to reproduce the problem**
1. Create content type
2. Create enumeration, type 光伏 <enter>  风电
3. strapi install GraphQL
4. `strapi start` get an error

**What is the expected behavior?**
special characters in enumeration shouldn't influence GraphQL

**Suggested solutions**

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/1698

> This is a templated message
