### ISSUE TITLE
An error occurred during users-permisssions plugin installation

### ISSUE THREAD

**Issue by Hdoove** [strapi/strapi#3341]
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: v6.4.1
- **Strapi version**: v3.0.0-alpha.26.2
- **Database**: mysql
- **Operating system**: Mac

**What is the current behavior?**
⚠ An error occurred during users-permissions plugin installation.
- Install users-permissions plugin
✖ An error occurred during plugin installation.
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-users-permissions

**Steps to reproduce the problem**
1.npm install strapi@alpha -g
2.strapi new cms --quickstart

**What is the expected behavior?**
It should at least create a new CMS without errors

**Suggested solutions**
I have none

**Comment by lauriejim** [comment]
Hello! 
This issue have been resolved in the new architecture of the beta.
Sorry for the trouble.
