### ISSUE TITLE
Node v12 support

### ISSUE THREAD

**Issue by alexandrebodin** [strapi/strapi#3342]
Hello everyone,

We are openning this issue to track Node v12 support. 

Node v12 was approx. released a month ago (2019-04-23) and is on track to become the next LTS version of Node. 

This means Strapi needs to support v12 at last before v10 active LTS ends (2020-04-01).
Ideally we want to support Node v12 when before it start's its active LTS life (2019-10-22).

We plan on testing node v12 out and track here what's breaking so we can work towards supporting this version.

[Link to node release schedule](https://nodejs.org/en/about/releases/)

**Comment by rjain15** [comment]
? Host: (127.0.0.1) Error: Command failed: /bin/sh -c yarnpkg --cwd /var/folders/_f/rwc7xssn12vgxvmnq9_xv89m0000gp/T/strapibca313916236 add strapi-hoo
k-mongoose@3.0.0-beta.1
error strapi-hook-mongoose@3.0.0-beta.1: The engine "node" is incompatible with this module. Expected version "^10.0.0". Got "12.1.0"
error Found incompatible module.

**Comment by alexandrebodin** [comment]
Hi @rjain15 

Strapi doesn't support node v12. You need to use node v10 which is the current LTS

**Comment by millette** [comment]
@alexandrebodin Utile: https://github.com/nodejs/node/issues/25060
