### ISSUE TITLE
WYSIWYG title headings in markdown are not saved

### ISSUE THREAD

**Issue by Alluuu** [strapi/strapi#3348]
**Informations**
- **Node.js version**: 11.14.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.26.2
- **Database**: SQLite
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: locally hosted development project

**What is the current behavior?**
Whe na content type has WYSIWYG text field, none of the title headings H1, H2... get saved, when entity is saved. In preview editor you can see there being ## hashes, but when saving the content doesn't and when taking the entity up to edit again, the headings are not there.

**Steps to reproduce the problem**
Install strapi, create new project, create content type with text field, enable WYSIWYG, create content, try adding titles, save entity, edit again to see headings gone.

**What is the expected behavior?**
That all field contents get stored as expected.

**Comment by derrickmehaffy** [comment]
Can't reproduce this on current version:

![image](https://user-images.githubusercontent.com/8593673/58702171-dfb4b200-8359-11e9-84f4-2b005998aef8.png)

**Comment by lauriejim** [comment]
Did you customize something that could break you WYSIWYG?

**Comment by Alluuu** [comment]
Hi, I don't know how to reproduce anymore.

I unset WYSIWYG for both text fields in my content, saved, then set them again and saved.
Then it was still not applying the headings, but when I deleted all the content from the field, saved the entity and on a new edit tried again, it was working, really strange and no idea what could've caused this, but as it's not reproducible, I guess this issue can be closed.

Also no modifications, vanilla strapi.

Cheers,

Alari

**Comment by onsombal** [comment]
I encountered this same issue when using the strapi editor to add a H1, H2... title. The problem seems to be related to using the editor title selection field to add the "**initial**" title markup — the markup is not processed as desired.

To correct this issue, one must "manually" edit the hashed title: e.g. adding a space or deleting a space. Any manual edit on the target title corrects the issue. Thus, it's not surprising that reproducing this error is difficult if an edit had already been made to the target title.

If you enter the hash symbols manually rather than using the editor title selection feature, the issue does not occur. Thus, this seems to be an editor issue for "Add Title".

**Comment by onsombal** [comment]
> I encountered this same issue when using the strapi editor to add a H1, H2... title. The problem seems to be related to using the editor title selection field to add the "**initial**" title markup — the markup is not processed as desired.
> 
> To correct this issue, one must "manually" edit the hashed title: e.g. adding a space or deleting a space. Any manual edit on the target title corrects the issue. Thus, it's not surprising that reproducing this error is difficult if an edit had already been made to the target title.
> 
> If you enter the hash symbols manually rather than using the editor title selection feature, the issue does not occur. Thus, this seems to be an editor issue for "Add Title".

BTW — I'm using ST

**Comment by onsombal** [comment]
> > I encountered this same issue when using the strapi editor to add a H1, H2... title. The problem seems to be related to using the editor title selection field to add the "**initial**" title markup — the markup is not processed as desired.
> > To correct this issue, one must "manually" edit the hashed title: e.g. adding a space or deleting a space. Any manual edit on the target title corrects the issue. Thus, it's not surprising that reproducing this error is difficult if an edit had already been made to the target title.
> > If you enter the hash symbols manually rather than using the editor title selection feature, the issue does not occur. Thus, this seems to be an editor issue for "Add Title".
> 
> BTW — I'm using strapi-3.0.2
