### ISSUE TITLE
GroupBy not works as expected on GraphQL

### ISSUE THREAD

**Issue by levixie** [strapi/strapi#3354]
**Describe the bug**
```
postsConnection {
  groupBy {
    published {
      key
      connection {
        aggregate {
          avg {
            nb_likes
          }
        }
      }
    }
  }
}
```

**Steps to reproduce the behavior**
1. Follow the https://strapi.io/documentation/3.x.x/guides/graphql.html#aggregation-grouping
2. Both nb_likes is 10
```
{
  data: {
    postsConnection: {
      groupBy: {
        published: [
          {
            key: true,
            connection: {
              aggregate: {
                avg {
                  nb_likes: 10
                }
              }
            }
          },
          {
            key: false,
            connection: {
              aggregate: {
                avg {
                  nb_likes: 10 <-should be 0, groupby not works
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

**Expected behavior**
```
{
  data: {
    postsConnection: {
      groupBy: {
        published: [
          {
            key: true,
            connection: {
              aggregate: {
                avg {
                  nb_likes: 10
                }
              }
            }
          },
          {
            key: false,
            connection: {
              aggregate: {
                avg {
                  nb_likes: 0
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

**System**
- Node.js version: v12.1.0
- NPM version:6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: mongodb
- Operating system: Mac OS 10.14.5
**Additional context**

**Comment by lauriejim** [comment]
Hello! 
Can you share an application with the issue please.
Need all your data models to be able to reproduce the issue.

**Comment by hellsan631** [comment]
also seeing this issue with MongoDB. It doesn't seem to group and then aggregate values, rather aggregate then group. this means the aggregate is the same for each group

**Comment by hellsan631** [comment]
It looks like

**Comment by hellsan631** [comment]
also seeing this issue with MongoDB. It doesn't seem to group and then aggregate values, rather aggregate then group. this means the aggregate is the same for each group

```
    "strapi": "3.0.0-beta.7",
    "strapi-admin": "3.0.0-beta.7",
    "strapi-hook-mongoose": "3.0.0-beta.7",
    "strapi-plugin-graphql": "3.0.0-beta.7",
```

*update*

The GraphQL query being generated is this:
```graphql
query {
  postsConnection(where: {
    someField: true,
  }) {
    groupBy {
      authorName {
        key
      	connection {
          aggregate {
            count
            avg {
              nb_likes
            }
          }
        }
      }
    }
  }
}
```

when it hits mongo, it turns into this
```bash
aggregate { 
  aggregate: "post", 
  pipeline: [ 
    { $match: { someField: true } }, 
    { $skip: 0 }, 
    { $limit: 100 }, 
    { $group: { _id: null, nb_likes: { $avg: "$nb_likes" } } } 
  ]
}
```

It seems that it's not correctly adding the group query _id. the _id field should be, in this case, "$authorName" and not null

**Comment by hellsan631** [comment]
I did some digging, and from what I can tell, it seems that there is a method by which grouping is done during aggregation. Within [strapi-plugin-graphql/services/Aggregator.js](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/Aggregator.js) grouping is only called twice, once to do the actual grouping, the second to get aggregates for a field. It doesn't look like either of these are correlated together at any point. Although there is a connection function [Aggregator.js#L197](https://github.com/strapi/strapi/blob/457e8a630696d2f065c94e3005b2f688a12d1d80/packages/strapi-plugin-graphql/services/Aggregator.js#L197), but I'm unsure where that actually fires.

It seems as though there is some duplicate data there as well in
[Aggregator.js#L114](https://github.com/strapi/strapi/blob/457e8a630696d2f065c94e3005b2f688a12d1d80/packages/strapi-plugin-graphql/services/Aggregator.js#L114), as obj appears twice. When this function is used the two parameters passed in are never used.

I don't have the general knowledge of how strapi resolves it's queries within graphql, so i think this is a dead-end for me.

**Comment by jacargentina** [comment]
@lauriejim i can confirm; aggregation is not working at all

**Comment by lauriejim** [comment]
Okay thank you for this report!

**Comment by lauriejim** [comment]
I tested this issue and it work fine in the current version of Strapi `beta.17.7`
