### ISSUE TITLE
Multi Upload Not Uploading All Images to S3

### ISSUE THREAD

**Issue by Naismith** [strapi/strapi#3357]
**Describe the bug**
When uploading multiple media images through the interface, using the strapi-provider-upload-aws-s3 it only uploads some of the images. Often times only uploading one of the photos.

**Steps to reproduce the behavior**
1. Have strapi-provider-upload-aws-s3 installed, configured
2. Set up content type with multi media
3. Go to content type containing multi media
4. Attempt to upload multiple images
5. View results

**Expected behavior**
Expect all images to upload

**Screenshots**
https://www.youtube.com/watch?v=aCYlsY5j-r4&feature=youtu.be

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.26.2
- Database: postgres
- Operating system: ubuntu 16

**Comment by Naismith** [comment]
This is still an issue with

- Node.js version v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.1
- Database: sqlite (doesn't seem database specific).
- Operating systems: 
  - MacOS Mojave Version 10.14.4 
  - Ubuntu 16

**Comment by alexandrebodin** [comment]
@Naismith thank you for this report. We will try to reproduce asap !

If you want to contribute and try to fix this, let me know so I can help you get started ;)

**Comment by Naismith** [comment]
@alexandrebodin I've narrowed it down to not creating a relation in the **upload_file__morph** table. It seems to upload the file to S3 but fails at creating relations. 

I can try to see if I can create a fix for it if you would like.

**Comment by alexandrebodin** [comment]
@Naismith Yes go ahead ! 

Let me know if you need help ! you can come find me on slack ;)

**Comment by Naismith** [comment]
@alexandrebodin 

Hey Alex, I had thought I would have some time to look into this. But I haven't had any yet. I'm not sure how high priority of a ticket this is if you want to look into it. 😄

**Comment by alexandrebodin** [comment]
Right now it is not that high because you can at least to a loop upload even if not ideal it is working. 

It leaves you time to tackle the issue if you would like :)

I would be looking into the upload limits from amazon and batching sends maybe ;)

**Comment by alexandrebodin** [comment]
@Naismith I have been tryin gto mess it up a lot with the beta version and could break it.

Cand you try upgrading and tell me if it is ok now ?

**Comment by Naismith** [comment]
@alexandrebodin this appears to be working now 🎉 

However, I noticed that it does replace previous existing photos. Is this intended?

**Comment by Naismith** [comment]
@alexandrebodin Correction - it is not working (when I was trying it, I had my file upload set to local). After uploading 8 photos, only 2 were added.

**Comment by alexandrebodin** [comment]
@Naismith 

I don't get it I uploaded 15 images at once,  deleted some, re added some and so on and everything was sent correctly...

Can you tell me the size and mime types of the files you have been uploaded (exploring as many ideas as possible here !)

**Comment by alvinchen1988** [comment]
@alexandrebodin this happened to me as well. files are uploaded to s3 bucket correctly but fail to create all relations in the upload_file_morph table. The relation is only created for the last image uploaded.

When i change to local upload, everything works. It only happens when i switch to use the aws s3 plugin.

**Comment by alexandrebodin** [comment]
@alvinchen1988 which version of strapi are you using ?

**Comment by alvinchen1988** [comment]
@alexandrebodin i'm using Strapi v3.0.0-beta.3,  db is sqlite

**Comment by alvinchen1988** [comment]
@alexandrebodin are you able to reproduce on your end?

here are the dependencies in my package.json, if it helps:

  "dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-beta.3",
    "strapi-admin": "3.0.0-beta.3",
    "strapi-utils": "3.0.0-beta.3",
    "strapi-hook-bookshelf": "3.0.0-beta.3",
    "strapi-plugin-settings-manager": "3.0.0-beta.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.3",
    "strapi-plugin-content-manager": "3.0.0-beta.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.3",
    "strapi-plugin-email": "3.0.0-beta.3",
    "strapi-plugin-upload": "3.0.0-beta.3",
    "strapi-provider-upload-aws-s3": "3.0.0-beta.3",
    "strapi-hook-knex": "3.0.0-beta.3",
    "knex": "latest",
    "sqlite3": "latest"
  },

**Comment by alexandrebodin** [comment]
Hi guys,

I cannot successfully reproduce the issue. If you are up for it you can clone the repo, npm link all the pacakges in your app and try to debug the plugin and/or the provider.

Otherwise we can try figuring it out by sharing the same amazon bucket and files (doing it via slack of course)

**Comment by alvinchen1988** [comment]
@alexandrebodin actually, i spent more time testing today. This issue is not just s3 specific, it happened in local upload too. My knowledge level is not there yet to fix this bug so hoping you or someone from the community can step up and fix it. I can be available on slack anytime to help demonstrate the issue if needed. thanks

**Comment by alexandrebodin** [comment]
@alvinchen1988 Once I successfully reproduce it I'll be able to fix it :)

The issue is reproducing it right now. I'll do more testing soon

**Comment by alvinchencd** [comment]
@alexandrebodin i did more testing today and found that the issue happened on relational db(sqlite, mysql and etc) but doesn't appear on mongodb. Hopefully that gives you a little bit more insight. let me know if you need any other info to debug. thanks

**Comment by alexandrebodin** [comment]
Thank you for this insights it will help me narrow done what's happening

**Comment by Naismith** [comment]
hey @alexandrebodin - are you still having issues trying to reproduce this?

**Comment by alexandrebodin** [comment]
I haven't been able to reproduce yet. @lauriejim would you mind trying ?

**Comment by lauriejim** [comment]
I will try tmrw.

**Comment by lauriejim** [comment]
I just tried with beta.6 fresh new project and it works well. I'm able to upload 9 new pictures and all is good.

**Comment by alvinchen1988** [comment]
> I just tried with beta.6 fresh new project and it works well. I'm able to upload 9 new pictures and all is good.

what db did you use and what version? did you use local upload or other upload plugin?

**Comment by lauriejim** [comment]
I tried with SQLite database and using AWS S3 provider.
I also tried with mysql and local provider. Both work.

**Comment by alexandrebodin** [comment]
Hello guys ! 
We might have fixed this in the latest release beta.12 . If you all don't mind retrying with this new release ;)

**Comment by dugajean** [comment]
It's still happening for me. My project is hosted on Heroku and I installed the S3 plugin per the documentation's instructions. Only 1 image gets uploaded to S3, but I had an instance where 2 got uploaded at once, but I was selecting 3. 

There's no indication of the upload process, but that's a different issue.

**Comment by collinsmwade** [comment]
Can confirm I'm experiencing this as well, hosted on EC2 with S3 per the tutorial. 
Here are my dependencies, lemme know if I can offer any other information.

  "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "pg": "^7.11.0",
    "sqlite3": "latest",
    "strapi": "^3.0.0-beta.13",
    "strapi-admin": "^3.0.0-next.14",
    "strapi-hook-bookshelf": "3.0.0-beta.7",
    "strapi-hook-knex": "3.0.0-beta.7",
    "strapi-plugin-content-manager": "3.0.0-beta.7",
    "strapi-plugin-content-type-builder": "3.0.0-beta.7",
    "strapi-plugin-email": "3.0.0-beta.7",
    "strapi-plugin-settings-manager": "3.0.0-beta.7",
    "strapi-plugin-upload": "3.0.0-beta.7",
    "strapi-plugin-users-permissions": "^3.0.0-next.14",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.10",
    "strapi-utils": "3.0.0-beta.7"
  }

**Comment by alexandrebodin** [comment]
@collinsmwade you need to make sure all yout dependencies have the same beta.13 version. Then test again and let us know ;)

**Comment by collinsmwade** [comment]
Still seeing the issue with the following dependencies. 

  "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "pg": "^7.11.0",
    "sqlite3": "latest",
    "strapi": "^3.0.0-beta.13",
    "strapi-admin": "^3.0.0-beta.13",
    "strapi-hook-bookshelf": "3.0.0-beta.13",
    "strapi-hook-knex": "3.0.0-beta.13",
    "strapi-plugin-content-manager": "3.0.0-beta.13",
    "strapi-plugin-content-type-builder": "3.0.0-beta.13",
    "strapi-plugin-email": "3.0.0-beta.13",
    "strapi-plugin-settings-manager": "3.0.0-beta.13",
    "strapi-plugin-upload": "3.0.0-beta.13",
    "strapi-plugin-users-permissions": "^3.0.0-beta.13",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.13",
    "strapi-utils": "3.0.0-beta.13"
  },
