### ISSUE TITLE
Create admin while bootstrapping

### ISSUE THREAD

**Issue by JRakhimov** [strapi/strapi#3365]
How to create new user with permission Administrator while bootstrapping project?

```js
'use strict';

module.exports = cb => {
  strapi.plugins['users-permissions'].controllers.user
    .create({
      request: {
        body: {
          username: 'root',
          email: 'some.mail@mail.com',
          provider: 'local',
          password: '1234abc',
          confirmed: true,
          blocked: null,
          role: 1
        }
      }
    })
    .then(res => console.log(res))
    .catch(error => console.log(error));
  cb();
};
```
And yes it creates new admin but also throws error:
```
TypeError: ctx.badRequest is not a function at Object.create (/app/plugins/users-permissions/controllers/User.js:84:20)
```
and strapi creates this user in tmp/***.db file (sqlite) but in config I use Postgres. If I remove bootstrap script above it uses Postgres.

So how can I create new admin in right way?

**Comment by alexandrebodin** [comment]
@JRakhimov,

This issue is not a Strapi issue per say but a usage question. You can go on the community slack to ask for help  ;) http://slack.strapi.io. 

That being said you should be calling a `service` not a `controller`. The controller only expect a Koa context which you should even be trying to create. You can instead do:
```js
strapi.plugins['users-permissions'].services.user
    .add({ username: '', ...})
    .then(res => console.log(res))
    .catch(error => console.log(error));
```

And you should only call the `cb()` when your creationg has been processed (in a `then`)

I'll be closing this issue. I hope to see you on slack !

**Comment by leonardomerlin** [comment]
First, kudos for the community on slack :+1: (everyone is very helpful). But, for this type of question, it would be more helpful to use [StackOverflow (tag/strapi) ](https://stackoverflow.com/questions/tagged/strapi) IMHO.

Second, I would like to share here my solution - just in case other people arrive here in the same way that I did.

```js
// File: ./config/functions/bootstrap.js

'use strict';

module.exports = async () => {

  // Required fields:
  const params = {
    username: process.env.ADMIN_USER || 'admin',
    password: process.env.ADMIN_PASS || 'admin',
    email: process.env.ADMIN_EMAIL || 'your.email@company.com',
    blocked: false
  };

  // Check if exist any admin account - NOTE: you can change this query to find by specific email
  const admins = await strapi.query('administrator', 'admin').find({ _limit: 1 });
  if (admins.length) {
    console.error('You can\'t register a new admin');
  } else {

    // Hash password before storing in the database
    params.password = await strapi.admin.services.auth.hashPassword(params.password);

    try {
      // Create admin account
      const admin = await strapi.query('administrator', 'admin').create({
        ...params
      });

      console.info('(Admin) Account created:', admin);

    } catch (error) {
      console.error(error);
    }
  }
};
```

> The important part is in the `try/catch` block, but I decided to share the whole thing ;P

**Comment by comoser** [comment]
@leonardomerlin Thank you for the snippet!

It really helps giving a clear idea of what to do at bootstrap.
But I'm having a problem with this, I'm new to Strapi and I'm still grasping some concepts.

Still, while running this I get a `The model administrator can't be found.`.
Shouldn't this model be default from a Strapi server instance? Since we will always have an admin  user?

**Comment by lauriejim** [comment]
According to the auth service of `strapi-admin` you should use `strapi.query('user', 'admin')`

**Comment by comoser** [comment]
> According to the auth service of `strapi-admin` you should use `strapi.query('user', 'admin')`

Hey @lauriejim ty for your answer, maybe I'm seeing the docs wrong, but I can't find documentation on the services / utilities Strapi already has.

You're saying `According to the auth service`, but there is no place in the docs documenting this service, at least, none that I can find. If you do know where this is, can you point me to the correct service / API docs?

The only why I'm seeing I could know how this service works is by diving into the code, and I was trying to avoid that for now, since these kinds of informations usually have docs

**Comment by lauriejim** [comment]
Some documentation is missing about internal APIs I agree -
We will try to improve that in next months.
If you want to know what is available you have to dig into the code source 😝 the code source is the docs 😅
We have lot of work to do to improve that and the team is still small to tackle every topics we have.

**Comment by alexandrebodin** [comment]
Hi @comoser FYI, if some code is not documented it is not considered "public API" yet. This means you must be careful while using it as it can break on any given release. We whill be documenting programmatic APIs better in the future with stability statuses to help our user !

**Comment by zoltot** [comment]
The solutionis mostly @leonardomerlin 's , but I needed to make a couple changes to make it work.  I made a couple changes to it namely setting the isActive key equal to true, and getting the superAdmin role from the getSuperAdmin function.
```
'use strict';

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/v3.x/concepts/configurations.html#bootstrap
 */
const mongoose = require('mongoose');
module.exports = async () => {

    // Required fields:
    const params = {
      username: process.env.ADMIN_USER || 'test',
      password: process.env.ADMIN_PASS || 'test',
      firstname : process.env.ADMIN_USER || "Test", 
      lastname : process.env.ADMIN_USER ||"Test", 
      email: process.env.ADMIN_EMAIL || 'example@website.com',
      blocked: false,
      isActive: true,
    };
  
    // Check if exist any admin account - NOTE: you can change this query to find by specific email
    const admins = await strapi.query('user', 'admin').find({ _limit: 1 });
    if (admins.length) {
      console.error('You can\'t register a new admin');
    } else {
    try {
     // in the admin under services you can find the super admin role
      const superAdminRole = await strapi.admin.services.role.getSuperAdmin();
      // Hash password before storing in the database
      params.roles = [superAdminRole._id]
      params.password = await strapi.admin.services.auth.hashPassword(params.password);
  

        // Create admin account
        const admin = await strapi.query('user', 'admin').create({
          ...params
        });
  
        console.info('(Admin) Account created:', admin);
  
      } catch (error) {
        console.error(error);
      }
    }
  };
```
This setup will create your first user with all the credentials, just to reference most of this is not my work all I did was add the isActive param and find the getSuperAdmin Function.

**Comment by jakubgs** [comment]
This solution doesn't appear to work in `3.2.5` because when `bootstrap.js` is executed result of:
```js
await strapi.admin.services.role.getSuperAdmin()
```
Is just `null` the first time the application is started. After a restart it returns the correct object.

Also, `_id` was changed to `id`.

**Comment by jakubgs** [comment]
The solution I found working was posted here: https://forum.strapi.io/t/hard-code-the-strapi-administrator/1074/2?u=jakubgs
