### ISSUE TITLE
Login loop after creating relation

### ISSUE THREAD

**Issue by vladmarton** [strapi/strapi#3370]
**Describe the bug**
After clean installation and creating a plain content type with only one field - relation to User, app goes into login loop.

**Steps to reproduce the behavior**
1. `npm i -g strapi`
2. `strapi new cms --quickstart`
3. Create admin account
4. Login and create new content type with name **event**. 
5. Add a new relation field where you select that user can have many events. In the second tab (advanced or what it is), set a custom name for the field "user" - change it to **author**
6. Confirm your field and **save the content type**

**Expected behavior**
Popup closes and you are able to work with admin further.

**System**
- npm 6.9.0
- strapi 1.6.4
- node v10.15.3

**Comment by derrickmehaffy** [comment]
@vladmarton `npm i -g strapi` needs to be `npm i -g strapi@beta`

without the `@alpha` or `@beta` tags you are installing Strapi v1 as Strapi v3 is not in a full release state yet (hence those extra tags)

**Comment by vladmarton** [comment]
@derrickmehaffy switching to beta helped. Thanks.
I accidentally installed alpha and wasnt working there too, so I was getting a little frustrated, but now it seems its gone.
