### ISSUE TITLE
Deployable package takes to long to generate in the CI pipeline

### ISSUE THREAD

**Issue by facundofarias** [strapi/strapi#3378]
**Describe the bug**
When creating the deployable package in the CI Pipeline it takes 13 minutes.

**Steps to reproduce the behavior**
```
npm install --unsafe-perm --production
npm run setup
npm run setup --plugins
```

**Expected behavior**
Same result, but taking less time. For example, we are packing another nodejs app and it takes 1 minute.

**Screenshots**
NA.

**Code snippets**
NA.

**System**
- Node.js version: Docker image node:11.1.0
- NPM version: Docker image node:11.1.0
- Strapi version: 3.0.0-alpha.25.2
- Database: NA
- Operating system: Docker image node:11.1.0

**Additional context**
NA

Thanks!

**Comment by Naismith** [comment]
Hey @facundofarias 

The recommended setup is using Node v10 LTS. 

as well would you try updating to the beta version that was released?

**Comment by lauriejim** [comment]
Hello! That is the build time. We worked on it in the `beta` version.
So I suggest you to update to this version if you want a faster build time.
Here is the [migration guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html)

**Comment by facundofarias** [comment]
Indeed, it has improved (2m 23s), using Node v10 LTS and Strapi Beta.
Thanks! @lauriejim @Naismith
