### ISSUE TITLE
Fix database colors in settings manager

### ISSUE THREAD

**Issue by jsve** [strapi/strapi#3382]
**Describe the bug**
Development databases show as mongo, even though configured as Postgres. Works on staging and production.

**Steps to reproduce the behavior**
Add database connections to one database per environment. All Postgres (can be on same DB-instance). Open admin interface and see how they appear differently.

**Expected behavior**
Postgres database connections should always appear as Postgres, never as mongo.

**Screenshots**
![Screenshot 2019-06-05 at 16 20 09](https://user-images.githubusercontent.com/9053945/58964038-8364ee80-87ae-11e9-924f-bb25a199d8fd.png)

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0@beta.1
- Database: postgres
- Operating system: MacOS

**Comment by soupette** [comment]
Well from the screenshot it appears to be postgres and not mongo.

**Comment by jsve** [comment]
Sorry about the confusion. The "P" icon is different than the ones that indicate Postgres. Here are some more screenshots showing the difference

Settings for development db:
<img width="546" alt="Screenshot 2019-06-07 at 09 39 09" src="https://user-images.githubusercontent.com/9053945/59088629-53316300-8908-11e9-8500-ba088488aa7d.png">

Icon showing Postgres DB on production:
<img width="236" alt="Screenshot 2019-06-07 at 09 39 17" src="https://user-images.githubusercontent.com/9053945/59088630-53316300-8908-11e9-938b-b8e3bdfbd48a.png">

Settings for production db:
<img width="544" alt="Screenshot 2019-06-07 at 09 39 23" src="https://user-images.githubusercontent.com/9053945/59088631-53316300-8908-11e9-9bda-13a7398a87f1.png">

**Comment by soupette** [comment]
You are right I will look into it.
