### ISSUE TITLE
Deprecated when Installing Beta

### ISSUE THREAD

**Issue by vinczun** [strapi/strapi#3384]
Is this normal? First time using strapi.

**Screenshots**
![image](https://user-images.githubusercontent.com/49867576/58966530-099c2780-87e5-11e9-98c6-1345a4aad944.png)

**System**
- Node.js version: 10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.2
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
We are working on cleaning up all those warnings but don't be worried you can ignore them.

Closing this as there are no real fix to do
