### ISSUE TITLE
Cannot install the beta version in mac

### ISSUE THREAD

**Issue by wozaisuzhou** [strapi/strapi#3386]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bairamau** [comment]
are there more error logs above that?

**Comment by wozaisuzhou** [comment]
yes , there is a lot of errors ...   I can see there is complaining for python 2 ?  we need python 2 for this beta version ?

**Comment by wozaisuzhou** [comment]
i still cannot npm install the strapi@beta after I installed the python2

**Comment by davidkartuzinski** [comment]
@wozaisuzhou - Please give us more information about your operating system?

**Comment by wozaisuzhou** [comment]
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.9 and node@10.16.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib' 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/danny/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/strapi/node_modules/fsevents/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strapi/node_modules/fsevents/.node-gyp'
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/local/lib/node_modules/strapi/node_modules/fsevents
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/strapi/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/strapi/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/strapi/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/usr/local/lib/node_modules/strapi/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

> node-sass@4.12.0 install /usr/local/lib/node_modules/strapi/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/local/lib/node_modules/strapi/node_modules/node-sass/vendor/darwin-x64-64 : { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strapi/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:757:3)
    at sync (/usr/local/lib/node_modules/strapi/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/strapi/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/local/lib/node_modules/strapi/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/strapi/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/usr/local/lib/node_modules/strapi/node_modules/node-sass/vendor' }

> core-js@2.6.9 postinstall /usr/local/lib/node_modules/strapi/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.1.3 postinstall /usr/local/lib/node_modules/strapi/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> styled-components@4.3.0 postinstall /usr/local/lib/node_modules/strapi/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components

> node-sass@4.12.0 postinstall /usr/local/lib/node_modules/strapi/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /usr/local/lib/node_modules/strapi/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/strapi/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp verb check python version `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.16.0
gyp verb ensuring nodedir is created /Users/danny/.node-gyp/10.16.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/danny/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/strapi/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.16.0
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/strapi/node_modules/node-sass/.node-gyp/10.16.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.0' ]
gyp verb remove using node-gyp dir: /usr/local/lib/node_modules/strapi/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.16.0
gyp verb remove removing development files for version: 10.16.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.0' ]
gyp verb remove using node-gyp dir: /usr/local/lib/node_modules/strapi/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.16.0
gyp verb remove removing development files for version: 10.16.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strapi/node_modules/node-sass/.node-gyp'
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/strapi/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/lib/node_modules/strapi/node_modules/node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/strapi/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abov

**Comment by wozaisuzhou** [comment]
i am using the command : 

sudo npm i -g strapi@beta

**Comment by wozaisuzhou** [comment]
I am using the mac os version 10.14.4

**Comment by derrickmehaffy** [comment]
@wozaisuzhou https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by wozaisuzhou** [comment]
thank you  @derrickmehaffy  .   I think I know the problem was the node is installed by the installation.  So the npm was installed in the local folder ,  it does not have global permission ,  Thanks a lot !

**Comment by ririen** [comment]
I think adding a special parameter to the command line should also help. I had the same problem and disappeared after executing the following command:

`npm install -g strapi@beta --unsafe-perm`

**Comment by Casal0x** [comment]
> thank you @derrickmehaffy . I think I know the problem was the node is installed by the installation. So the npm was installed in the local folder , it does not have global permission , Thanks a lot !

you could fix it ?? i'm having the same issue :S

**Comment by wozaisuzhou** [comment]
@Casal0x  when you installed the nvm , and use it install the node ,   then install the strapi beta version , it is working

**Comment by aminsource** [comment]
I have same issue on centos 7 when I want install with : sudo npm i -g strapi@beta 
```
 Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/strapi/node_modules/node-sass/.node-gyp'
```

**Comment by derrickmehaffy** [comment]
@aminsource : https://github.com/strapi/strapi/issues/3386#issuecomment-499554119

**Comment by davidkartuzinski** [comment]
@aminsource @Casal0x - what is happening is that Strapi is trying to install into a directory with different user permissions than your user. The solution is to create another directory, and to put all new installations into that new directory from NPM.  

You can follow these instructions for just that part of it: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally 

or you can follow these[ Digital Ocean](https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#digital-ocean) instructions (should be the same for on a Mac and on CentOS).

Please let us know if this resolved it for you.

**Comment by aminsource** [comment]
@davidkartuzinski  thx as instructions done and with super user (note: don't use root user)

**Comment by davidkartuzinski** [comment]
@aminsource - do the instructions seems to say to use root user?

**Comment by aminsource** [comment]
@davidkartuzinski I mean this instruction:  https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally should execute with non root user and with root user I get EACCES permissions errors , anyway my issue solved thx

**Comment by lauriejim** [comment]
Everyone is OK with his write access? Can we close this issue?

**Comment by derrickmehaffy** [comment]
@lauriejim yeah this is a broad issue related to the eacess stuff from node, I think @davidkartuzinski is planning to write some docs related to this and the node KB article. I'd say we can close this.

If anyone else has problems with this and found this issue via a search: https://github.com/strapi/strapi/issues/3386#issuecomment-501516505
