### ISSUE TITLE
[Help] Modify the admin directory without running the build command every time a change is made

### ISSUE THREAD

**Issue by Galdencio** [strapi/strapi#3389]
In the beta, when I change the admin folder in the root or inside the plugins/plugin-name directory, to see the changes, I need to run the command `yarn build` and restart the server every time. This task is very time consuming, because it takes almost 5 minutes on my laptop to build the project. Is there a better way to solve this problem?

Obs: Before the beta I was able to make changes in the admin directory without run the build command.

**Comment by derrickmehaffy** [comment]
@Galdencio It is planned but was not included in the first release of the beta. This will come.

I am however closing this as it does not follow the Bug Report template or the Feature Request template.

Questions should be directed towards the Slack, Stackoverflow, or the spectrum chat.
