### ISSUE TITLE
translate's menu doesn't work

### ISSUE THREAD

**Issue by simonmnt** [strapi/strapi#3391]
**Describe the bug**
Hi,
when I would like to change language to french but doesn't appear into my menu. French language is configured by default. I don't understand, I don't have error in my terminal

**Screenshots**
![Menu](https://user-images.githubusercontent.com/1232756/59013918-8eb22b80-883b-11e9-9c8d-528334a625b0.png)

![Configuration](https://user-images.githubusercontent.com/1232756/59013933-970a6680-883b-11e9-9930-3c15885e23bf.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.2
- Database: mysql
- Operating system: macOs Mojave

**Comment by alexandrebodin** [comment]
Hi, 
that's not obvious but you can scroll in this menu and select any language configured

**Comment by simonmnt** [comment]
Oh gosh, I didn't see that. Ok, I see french Language but now I deleted all language but not french and English. In my menu, I've lot of different language. That normal ?

![Capture d’écran 2019-06-06 à 09 46 04](https://user-images.githubusercontent.com/1232756/59015736-f23e5800-883f-11e9-8ec5-5d1adc80c37e.png)

![Jun-06-2019 09-45-11](https://user-images.githubusercontent.com/1232756/59015745-f7030c00-883f-11e9-801a-c32e9e3cee12.gif)

**Comment by alexandrebodin** [comment]
I'm not sure.

@soupette might have the info

**Comment by soupette** [comment]
Well, the language page from the setting manager is made to allow you to add a new locale in your project's backend, it doesn't refer to the administration panel.

**Comment by simonmnt** [comment]
Ok, thanks @soupette !
