### ISSUE TITLE
users

### ISSUE THREAD

**Issue by pcrossnz** [strapi/strapi#3393]
Hi there,

I have just installed beta but this was an issue in alpha as well. 

**Steps to reproduce the behavior**
1. I made a modification to the "users" in content type builder. 
2. Strapi then generates a duplicate user field in the land hand panel, while losing the ability to add users. When clicking on users in the left hand panel, it either produces a white screen (alpha) or generates the following error message in beta

*"Something went wrong"
TypeError: Cannot convert undefined or null to object

    in t
    in DragDropContext(t)
    in Connect(DragDropContext(t))
    in withSaga(Connect(DragDropContext(t)))
    in withReducer(withSaga(Connect(DragDropContext(t))))
    in t
    in t
    in div
    in t
    in Connect(t)
    in withSaga(Connect(t))
    in withReducer(withSaga(Connect(t)))
    in mainComponent
    in t
    in div
    in kr
    in kr
    in t
    in t
    in div
    in div
    in div
    in t
    in withHooks(t)
    in Connect(withHooks(t))
    in withSaga(Connect(withHooks(t)))
    in withReducer(withSaga(Connect(withHooks(t))))
    in withReducer(withReducer(withSaga(Connect(withHooks(t)))))
    in t
    in t
    in div
    in t
    in Connect(t)
    in div
    in Ho
    in t
    in t
    in IntlProvider
    in t
    in Connect(t)
    in i*

**Expected behavior**
I am now unsure how to correct this. Any help appreciated. 

**Screenshots**

![Screen Shot 2019-06-06 at 10 18 27 PM](https://user-images.githubusercontent.com/14836461/59025786-0cf8e700-88a9-11e9-91c4-926eb320bae0.png)

**System**
Latest of all with fresh install.

**Comment by derrickmehaffy** [comment]
@Palivonas Please follow the bug report template, you are missing all the bottom information related to OS, NPM, Node, Database, ect versions.

I am marking this closed for now, but after you have updated your original post, please let us know and this can be reopened.
