### ISSUE TITLE
Error when install beta version on a fresh Ubuntu 18.04

### ISSUE THREAD

**Issue by onlinebizsoft** [strapi/strapi#3394]
**Describe the bug**
While run install I get these errors

Building: /usr/bin/node /usr/lib/node_modules/strapi/node_modules/node-gyp/bin/n                                                                                                                                                             ode-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags=                                                                                                                                                              --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/strapi/node_modules/node-gyp/bin/node-gyp.                                                                                                                                                             js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node v                                                                                                                                                             ersion: 10.16.0
gyp verb command install [ '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/roo                                                                                                                                                             t/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_m                                                                                                                                                             odules/strapi/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk sp                                                                                                                                                             ace
gyp verb command install [ '--node_gyp_internal_noretry', '10.16.0' ]
gyp verb install input version string "10.16.0"
gyp verb install installing version: 10.16.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.16.0
gyp verb ensuring nodedir is created /usr/lib/node_modules/strapi/node_modules/n                                                                                                                                                             ode-sass/.node-gyp/10.16.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.0' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/strapi/node_modules/no                                                                                                                                                             de-sass/.node-gyp
gyp verb remove removing target version: 10.16.0
gyp verb remove removing development files for version: 10.16.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.0' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/strapi/node_modules/no                                                                                                                                                             de-sass/.node-gyp
gyp verb remove removing target version: 10.16.0
gyp verb remove removing development files for version: 10.16.0
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/st                                                                                                                                                             rapi/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/strapi/node_modules/node                                                                                                                                                             -gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags="                                                                                                                                                              "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/strapi/node_modules/node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is install                                                                                                                                                             ed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/str                                                                                                                                                             api/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                                                             1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}                                                                                                                                                             )

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                                             ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-06T10_47_03_628Z-debug.log

**Steps to reproduce the behavior**
Just follow the exact command in your document on a fresh Ubuntu 18.04 (follow exactly from installing npm,....)

**Expected behavior**
Should pass this step and create a website OK

**Screenshots**
![image](https://user-images.githubusercontent.com/22501570/59027657-cf359780-8883-11e9-860a-2164698d079d.png)

**Comment by derrickmehaffy** [comment]
@onlinebizsoft 
` WARN EACCES user "root" does not have permission to access the dev dir "/roo t/.node-gyp/10.16.0"`

You have problems with permissions and node: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

I recommend you never run a node project as root and always create a service user along with giving that service user their own "global" install location for node packages.

For now I am marking this as closed, as this is not directly an issue with strapi but a user environment bug.

**Comment by davidkartuzinski** [comment]
@onlinebizsoft - The docs for deploying on a Digital Ocean VPS (Ubuntu 18.04) have just been revised and are located in this branch.  [](https://github.com/strapi/strapi/blob/96b7deb72eba982966d0b5d8ddf07c93661a038f/docs/3.0.0-beta.x/guides/deployment.md ) - this is a temporary link as the changes will soon be merged and deployed to the documentation. 

As @derrickmehaffy stated above and as further explained in the docs, you have a permission error and it is rather simple to fix.

**Comment by baranelitez** [comment]
I had the same issue today. Googling `WARN EACCES user "root" does not have permission to access the dev dir "/roo t/.node-gyp/10.16.0"` returned this issue.

**Comment by baranelitez** [comment]
> I had the same issue today. Googling `WARN EACCES user "root" does not have permission to access the dev dir "/roo t/.node-gyp/10.16.0"` returned this issue.

Reverted to an old snapshot of my VPS, upgraded node using nvm, same error.
Globally installing strapi seems to break node-gyp. When I try to run `node-gyp` it prints out: `internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
`

**Comment by derrickmehaffy** [comment]
@baranelitez this is not an issue with strapi, it's an issue with your VPS'es permissions related to node, as I have mentioned on quite a few issues.

http://lmgtfy.com/?q=node+eaccess

https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
https://givan.se/do-not-sudo-npm/
http://syskall.com/dont-run-node-dot-js-as-root/
https://stackoverflow.com/questions/4938592/how-why-does-npm-recommend-not-running-as-root

Short answer don't run node as root, redirect each user to have their own global packages install location or you can use the unsafe perms flag but **I very strong recommend you do not do this** as it effectively makes these apps/scripts/whatever run as root. **You should not be running any node.js application as root, anywhere, for any reason, ever.**

**Comment by baranelitez** [comment]
I can't believe you just lmgtfy'd me man. Anyway, thanks for your time and your concern for safeties. I'll try to resolve this.

**Comment by derrickmehaffy** [comment]
@baranelitez nothing personal man, but I see this exact same problem daily both here in github and in the slack.

After a while it just becomes "beating the dead horse"

**Comment by mtrabelsi** [comment]
@derrickmehaffy  lets face it genuinely : I know this is problem of Node, but the doc should be more responsible to keep the learning curve up for the new comers ( IMO ), some nice links included in the doc, I'm pretty sure the number of ticket will drop for this kind of issues :)

**Comment by derrickmehaffy** [comment]
@mtrabelsi But if that is the case, then do we also need to document everything that isn't directly related to Strapi? For instance for production usage, does the use of Nginx/Apache/Traefik? Do we also need to document how to use Let's Encrypt? Or how to use a Database CLI/Client to configure authentication, creating the database, assigning permissions.

I think pushing users to utilize and sharpen their "Google-Foo" along with a little more guidance on finding answers on their own is always a plus.

I can tell you before Strapi, I had never used node.js before. And I learned the hard way without anyone giving me links to common issues 😉

**Comment by onlinebizsoft** [comment]
@derrickmehaffy I agree with @mtrabelsi, many people comes and just want to give a quick test on a fresh machine to evaluate the framework (they can be not developers, just a junior technical guy) so more easy you do then more users you get :)

**Comment by derrickmehaffy** [comment]
@onlinebizsoft @mtrabelsi I welcome both of you to submit PRs for any missing docs you think need added and it can be reviewed by the Strapi team.

I myself am just like you guys, with little no development experience and am just a Systems/Network engineer as a day job.

But I do disagree that it should not be the responsibility of the Strapi team to write documentation for every single users environment. 

Windows, Mac, and all the different flavors of linux. There are many many many external guides for setting up your environment, and everyone's is going to be different. Especially those using machines they may not own in a business. To me that local or even remote development environment is extremely subjective. For instance I do not use NVM nor NPX, I create separate virtual machines for each project I'm working on. Likewise some users prefer to do it all on their host OS.

To me I view these choices just as not everyone uses VSCode.

For guides I recommend you look at places like [Digital Ocean](https://www.digitalocean.com/community) As they provide very nice guides written by the community (and by all means if you enjoy writing documentation, I would hope you would contribute there as well)

**Comment by davidkartuzinski** [comment]
@baranelitez - Did you resolve your issues? 
@mtrabelsi - This issue you speak about for newcomers and being able to get going as fast as possible with Strapi is something the team talks and is meeting about regularly.  In fact, I was hired as the Developer Advocate to help with this very issue.  You are right to say that this is a pain point and that there should be better documentation. 
The blessing and the "curse" - both with regards to writing docs - with Strapi, is that it is so customizable, and so plug and play, that there are just a lot of Docs to write!!  
@onlinebizsoft - Your way of thinking seems correct and matching with what I think.  The better the docs the better the experience. @derrickmehaffy linked to Digital Ocean as they have pretty decent docs.
We are also working on getting one click installs and several other exciting features into the pipeline so that with one or two commands, anyone could have a Strapi project up and running.
If you know of specific docs that are missing, need to be added to or fixed, please let me know.  Or better yet, write up a little outline with some links and maybe I can get it done.  The best of course 🥇 , is to submit a PR :)
