### ISSUE TITLE
GraphQL schema breaks if a new User model is introduced

### ISSUE THREAD

**Issue by mdibaiee** [strapi/strapi#3397]
**Describe the bug**
After upgrading to Beta, we wanted to introduce our own User model, and once we did, everything was fine until we enabled the GraphQL plugin.

The GraphQL plugin seems to generate colliding schemas for the Users-Permissions-User model and our User model:

```
Field "UserInput.email" can only be defined once.

Field "UserInput.password" can only be defined once.

Field "UserInput.blocked" can only be defined once.

There can be only one type named "editUserInput".

Field "editUserInput.email" can only be defined once.

Field "editUserInput.password" can only be defined once.

Field "editUserInput.blocked" can only be defined once.

There can be only one type named "createUserInput".

Field "createUserInput.data" can only be defined once.

There can be only one type named "createUserPayload".

Field "createUserPayload.user" can only be defined once.

There can be only one type named "updateUserInput".

Field "updateUserInput.where" can only be defined once.

Field "updateUserInput.data" can only be defined once.

There can be only one type named "updateUserPayload".

Field "updateUserPayload.user" can only be defined once.
    at assertValidSDL (/.../node_modules/graphql/validation/validate.js:89:11)
    at Object.buildASTSchema (/.../node_modules/graphql/utilities/buildASTSchema.js:78:34)
    at Object.buildSchemaFromTypeDefinitions (/.../node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (/.../node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/.../node_modules/strapi-plugin-graphql/services/Schema.js:260:22)
    at Function.initialize (/.../node_modules/strapi-plugin-graphql/hooks/graphql/index.js:52:50)
    at /.../node_modules/strapi/lib/hooks/index.js:52:31
    at after (/.../node_modules/strapi/lib/hooks/index.js:153:39)
    at /.../node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/.../node_modules/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at onFinish (/.../node_modules/strapi/lib/hooks/index.js:44:12)
```

**Steps to reproduce the behavior**
1. Create a User model with overlapping properties with users-permission-user
2. Install GraphQL plugin
3. Start server

**Expected behavior**
GraphQL should not create colliding schemas between these two models. Administrator model should be completely out of sight of applications.

**Screenshots**
N/A

**Code snippets**
If applicable, add code samples to help explain your problem.

```
{
  "connection": "default",
  "collectionName": "users",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "email": {
      "type": "email",
      "required": true
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "required": true
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
}
```

**System**
- Node.js version: v10.2.1
- NPM version: 5.6.0
- Strapi version: 3.0.0-beta.2
- Database: PostgreSQL
- Operating system: Linux (Archlinux)

**Additional context**
N/A

**Comment by mdibaiee** [comment]
I realized the beta upgrade doesn't necessarily mean we can't user the User model, instead it means the admininstrator model and user are now distinct models. IMO it wasn't clear in docs because of this quote:

> In this way, the Administrator model replaces the previous User model from the users-permissions plugin.

I was confused by this.

**Comment by alexandrebodin** [comment]
Hi,

Is it ok to close now ?

**Comment by mdibaiee** [comment]
@alexandrebodin maybe clarify this in the documentation as a means to avoid this kind of confusion?

**Comment by alexandrebodin** [comment]
@mdibaiee 

We won't be make the change for now. You can suggest a change by making a PR on the docs if you want :) 

I'm going to close this issue as there are not follow up to do with it.
