### ISSUE TITLE
permissions plugin error after beta update

### ISSUE THREAD

**Issue by Ayo91** [strapi/strapi#3405]
I found an issue in beta version after migrate from alpha one. Everything is working fine except when Im trying to edit a role using the rol&permissions plugin through the user interface. This is the error generated: 

error TypeError: plugins.find is not a function
    at role.permissions.role.permissions.reduce (./node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:220:19)
    at Array.reduce (<anonymous>)

Im using a MySQL database. 

Steps:
1. Open the admin panel
2. Click on role and permissions plugin
3. Click on edit "Public" role. 
4. Error is shown.

My workaround to allow the public role access to an entity was access to the database and modify the row.

**Comment by valicsek** [comment]
same with quickstart version. (SQLite)
`TypeError: plugins.find is not a function
    at role.permissions.role.permissions.reduce (/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:220:19)
    at Array.reduce (<anonymous>)`

**Comment by alexandrebodin** [comment]
Hi yes the error is coming from a request where the server is off we are going to fix it asap and create a PR to ignore it in case of error

**Comment by alexandrebodin** [comment]
SHould be resolved now
