### ISSUE TITLE
Unable to open a Particular role in admin panel/api call.

### ISSUE THREAD

**Issue by driku** [strapi/strapi#3406]
**Describe the bug**
I am unable to open a particular role to assign some permissions.
error TypeError: plugins.find is not a function
    at role.permissions.role.permissions.reduce strapi/beta/ei/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:220:19
This seems to happen as https://marketplace.strapi.io/plugins is down which is called to fetch the information about plugins.
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

**Steps to reproduce the behavior**
1. Go to admin panel
2. Click on Roles & permissions
3. Select a particular role to assign permission
4. You will get unexpected error happened i.e 500

**Expected behavior**
UI to assign user permissions should open up

**System**
- Node.js version: v11.9.0
- NPM version: 6.5.0
- Strapi version: 3.0.0-beta.2
- Database: Mongo
- Operating system: Mac OS

**Comment by alexandrebodin** [comment]
Fix #https://github.com/strapi/strapi/pull/3407 done. Closing
