### ISSUE TITLE
Failed to run in docker( Cannot find module 'lodash')

### ISSUE THREAD

**Issue by zhiwen-kooboo** [strapi/strapi#3408]
**Describe the bug**
Failed to run in docker( Cannot find module 'lodash')

**Steps to reproduce the behavior**
1. According to the documentation

```
docker pull strapi/strapi

docker run -e MONGO_INITDB_DATABASE=strapi \
           -v `pwd`/db/:/data/db \
           --name strapi-mongo \
           -d mongo

docker run -e APP_NAME=strapi-app \
           -e DATABASE_CLIENT=mongo \
           -e DATABASE_HOST=strapi-mongo \
           -e DATABASE_PORT=27017 \
           -e DATABASE_NAME=strapi \
           -v `pwd`/strapi-app:/usr/src/api/strapi-app \
           --link strapi-mongo:mongo \
           -p 1337:1337 \
           --name strapi -d strapi/strapi
```
2. Run failed and shows “Cannot find module 'lodash'”

**Expected behavior**
Should the be able to access my Strapi installation at localhost:1337.

**Screenshots**
![image](https://user-images.githubusercontent.com/45249999/59149858-99dca580-8a4d-11e9-950b-3abe2904dcf0.png)
![image](https://user-images.githubusercontent.com/45249999/59149861-b2e55680-8a4d-11e9-916c-e513f37f0aa9.png)

**System**
- Node.js version: 
- NPM version:
- Strapi version: docker image in docs
- Database: MongoDB
- Operating system: CentOS 7.6

Thanks for any help!

**Comment by alexandrebodin** [comment]
@zhiwen-kooboo Hi,

Can you please open this issue in this repo https://github.com/strapi/strapi-docker.
I'm closing it here.

**Comment by zhiwen-kooboo** [comment]
Okay, thanks!
