### ISSUE TITLE
Custom GraphQL schema in beta-3 is not working

### ISSUE THREAD

**Issue by sepehrHosseini** [strapi/strapi#3411]
**Describe the bug**
We have just upgraded our project to Strapi version 3-beta, and the custom GraphQL schema that we have defined for user model in `/extensions/users-permissions/config/schema.graphql` is not working anymore, it's like this file is being ignored, although I haven't seen any change about this on the docs. It used to work in the latest alpha version `#alpha.26`.

**Steps to reproduce the behavior**
1. Write some custom GraphQL schema
2. Start the project
3. Use the custom query/mutation

**Expected behavior**
The custom query/mutations that I've provided should work.

**Screenshots**
![Screen Shot 2019-06-09 at 16 45 23](https://user-images.githubusercontent.com/13555552/59158875-131fdb00-8ad6-11e9-9f93-8d1ac01104bd.png)

**Code snippets**
Here is the schema `/extensions/users-permissions/config/schema.graphql`:
```
module.exports = {
  query: `
    userSearch(_q: String!): [UsersPermissionsUser]
  `,
  resolver: {
    Query: {
      userSearch: {
        resolver: {
          plugin: 'users-permissions',
          handler: 'User.search'
        }
      },
    }
  }
};
```

Here is the query that will get sent to GraphQL endpoint:
```
query ($_q: String!) {
    userSearch(_q: $_q) {
        id
        first_name
        last_name
    }
}
```

Here is the error, when we request to that query:

```
{
    "errors": [
        {
            "message": "Cannot query field \"userSearch\" on type \"Query\". Did you mean \"users\"?",
            "locations": [{ "line": 2, "column": 3 }],
            "extensions": {
                "code": "GRAPHQL_VALIDATION_FAILED",
                "exception": {
                    "stacktrace": [
                        "GraphQLError: Cannot query field \"userSearch\" on type \"Query\". Did you mean \"users\"?",
                        "    at Object.Field (/project/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:64:31)",
                        "    at Object.enter (/project/node_modules/graphql/language/visitor.js:332:29)",
                        "    at Object.enter (/project/node_modules/graphql/language/visitor.js:383:25)",
                        "    at visit (/project/node_modules/graphql/language/visitor.js:250:26)",
                        "    at Object.validate (/project/node_modules/graphql/validation/validate.js:63:22)",
                        "    at validate (/project/node_modules/apollo-server-core/dist/requestPipeline.js:211:32)",
                        "    at Object.<anonymous> (/project/node_modules/apollo-server-core/dist/requestPipeline.js:124:42)",
                        "    at Generator.next (<anonymous>)",
                        "    at fulfilled (/project/node_modules/apollo-server-core/dist/requestPipeline.js:4:58)",
                        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
                    ]
                }
            }
        }
    ]
}
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: beta-3
- Database: PostgreSQL
- Operating system: MacOS

I have also asked this in StackOverflow: https://stackoverflow.com/q/56514188/5073175

**Comment by alexandrebodin** [comment]
@sepehrHosseini could you please try out this PR https://github.com/strapi/strapi/pull/3417 ?


You can clone the repo and link the packages to test them (you can only link the strapi-plugin-graphql package)

**Comment by sepehrHosseini** [comment]
@alexandrebodin previously there was other content in the schema file by default, which I didn't touch them, in this version I tried both, with those default content and without them, didn't made any difference.
Sure, I'll test it and let you know the result.

**Comment by sepehrHosseini** [comment]
@alexandrebodin how can I link the package to my project?

1. I ran `npm link` in `strapi-plugin-graphql`
2. I ran `npm link strapi-plugin-graphql` in my project root
3. Import `strapi-plugin-graphql` in `admin/src/plugins.js`
3. Ran `npm run build && npm run develop` in my project
4. Open `localhost:1337/graphql`
5. Got `404 Not Found`

I checked the `strapi-plugin-graphql` directory, and it looks like the admin files are missing:
```
/Volumes/code/strapi/packages/strapi-plugin-graphql/admin/src    fix/issue-3411
$ l
total 0
drwxr-xr-x  3 sepehrhosseini  admin    96B Jun 10 17:40 .
drwxr-xr-x  3 sepehrhosseini  admin    96B Jun 10 17:40 ..
drwxr-xr-x  3 sepehrhosseini  admin    96B Jun 10 17:40 assets

/Volumes/code/strapi/packages/strapi-plugin-graphql/admin/src    fix/issue-3411
$
```

**Comment by alexandrebodin** [comment]
Hi,

There are no admin in the graphql plugin just remove it from you admin plugin.js file (you should'nt even have to have this file ;))

**Comment by sepehrHosseini** [comment]
@alexandrebodin you're right, we don't have this file, but for our other plugins we need to modify it to be able to use them, thus we modify the one in node_modules 😊 . I know we shouldn't modify it, but we have no other way.

I removed `strapi-plugin-graphql` from `plugins.js` file, but still, I'm getting `404 Not Found` error on `/graphql` endpoint!
What should I do now?

**Comment by alexandrebodin** [comment]
Did you specified it in your package.json dependencies ?

**Comment by sepehrHosseini** [comment]
@alexandrebodin like this?
```
"strapi-plugin-graphql": "file:../strapi/packages/strapi-plugin-graphql",
```

When I add the line above, I get this error:
```
[2019-06-11T11:08:56.203Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-11T11:08:56.205Z] error Error: Cannot find module 'strapi/lib/load'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (/Volumes/code/logickit-new/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

**Comment by alexandrebodin** [comment]
@sepehrHosseini Let's continue this on slack I'll let you contact me so we can go faster ;)
