### ISSUE TITLE
Filtering result for GraphQL

### ISSUE THREAD

**Issue by tention** [strapi/strapi#3413]
**Describe the bug**
Tried to define a filter of isOwner to GraphQL result but does not seems to work as there is no query that I can modify (eg. ctx.query.owner) like REST. Tried using `resolverOf`to tweak the resolver, but it won't load any of the policies, so I could not get the owner from ctx.state.user.

**Steps to reproduce the behavior**
1. Write custom GraphQL schema
2. Add a new filterByOwner policy
3. Run query in GraphQL Playground

**Code snippets**
Tried the following but I could not find any query that I can edit like REST to get the filtered results.

    module.exports = {
      resolver: {
        Query: {
          conversations: {
            resolver: 'Conversation.find',
            policies: [
              'plugins.users-permissions.permissions',
              'plugins.users-permissions.isAuthenticated',
              'global.filterByOwner'
            ],
          },
        },
      }
    };

Tried using resolverOf but none of the defined policies will run, so I will not be able to get the user ID from ctx.state.user to perform the filtering.

    module.exports = {
      resolver: {
        Query: {
          conversations: {
            policies: [
              'plugins.users-permissions.permissions',
              'plugins.users-permissions.isAuthenticated',
              'global.filterByOwner'
            ],
            resolverOf: 'Conversation.find',
            resolver: (obj, options, context, ctx) => {
              return strapi.api.conversation.services.conversation.find({ id: 30 }); <--
            },
          },
        },
      }
    };

**System**
- Node.js version: v10.15.2
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.2
- Database: Postgres
- Operating system: macOS

Asked this in StackOverflow: https://stackoverflow.com/questions/56513679/

**Comment by derrickmehaffy** [comment]
@tention try with the beta.3 as there was an issue with beta.2 that got patched, not sure if it will fix this but worth testing anyway

**Comment by tention** [comment]
Tried beta.3 but still the same. Policies are not called if I use `resolverOf`.

Following is the full context when it entered the policy via `resolver: 'Conversation.find'`.

    { request:
       { method: 'POST',
         url: '/graphql',
         header:
          { host: 'localhost:1337',
            connection: 'keep-alive',
            'content-length': '111',
            accept: '*/*',
            origin: 'http://localhost:1337',
            authorization:
             'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTU5ODg3Nzg4LCJleHAiOjE1NjI0Nzk3ODh9.AmK1_sCuDBWWjDYUQb6EAgOEkEVAOkZzvpjnKy-ASq0',
            'user-agent':
             'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.109',
            dnt: '1',
            'content-type': 'application/json',
            referer: 'http://localhost:1337/graphql',
            'accept-encoding': 'gzip, deflate, br',
            'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8' } },
      response:
       { status: 404,
         message: 'Not Found',
         header:
          [Object: null prototype] {
            vary: 'Origin',
            'access-control-allow-origin': 'http://localhost:1337',
            'access-control-allow-credentials': 'true',
            'access-control-expose-headers': 'WWW-Authenticate,Server-Authorization' } },
      app: { subdomainOffset: 2, proxy: false, env: 'development' },
      originalUrl: '/graphql',
      req: '<original node req>',
      res: '<original node res>',
      socket: '<original node socket>' }

The ctx.query is empty:

    {}

**Comment by donmasakayan** [comment]
Experiencing the same issue. Also none of the policies are being triggered.

**Comment by lauriejim** [comment]
Hello @tention I think you issue is the association of these two issues:
https://github.com/strapi/strapi/issues/2766 and https://github.com/strapi/strapi/issues/1887

I think we can close this issue.
It will be easier to follow each specific topic.
