### ISSUE TITLE
Installation npm - Fail during installation of dependencies

### ISSUE THREAD

**Issue by Devportobello** [strapi/strapi#342]
Hi,

I wanted to try locally strapi to cover all aspect of your cms, but im facing an issue, is it possible to install strapi on Windows ?

Logs:
$ node -v
v8.6.0

$ npm -v
5.5.1

$ strapi -v
3.0.0-alpha.6.7

$ npm config get prefix
C:\Users\Code CI\AppData\Roaming\npm

$strapi new test
...
INFO (13660 on DESKTOP-T7K9F8B): Installing dependencies...
module.js:473 throw err; ^
Error: Cannot find module 'C:\Users\Code' at Function.Module._resolveFilename (module.js:527:15) at Function.Module._load (module.js:453:25) at Function.Module.runMain (module.js:665:10) at startup (bootstrap_node.js:187:16) at bootstrap_node.js:607:3 ERROR (13660 on DESKTOP-T7K9F8B): An error occurred during settings-manager plugin installation. ERROR (7748 on DESKTOP-T7K9F8B): Command failed: node C:\Users\Code CI\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js install settings-manager module.js:473 throw err; ^ Error: Cannot find module 'C:\Users\Code' at Function.Module._resolveFilename (module.js:527:15) at Function.Module._load (module.js:453:25) at Function.Module.runMain (module.js:665:10) at startup (bootstrap_node.js:187:16) at bootstrap_node.js:607:3 Error: Command failed: node C:\Users\Code CI\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js install settings-manager ...

Maybe the space ? "C:\Users\Code CI"

**Comment by Aurelsicoko** [comment]
Can you try with another user to check if the issue is related to space between `Code CI`? The issue seems more related to Node.js module resolution than Strapi... Do you already have an issue like that with others frameworks?

**Comment by Devportobello** [comment]
Tested with another user without space and worked.

For informations:
Seem the resolution of some module who lead to fail.
Between thoses steps:
INFO (4020 on DESKTOP-X): Installing dependencies...
/!\
INFO (4020 on DESKTOP-X): The plugin settings-manager has been successfully installed.

Notice that stack trace : npm\node_modules\strapi\bin\strapi.js install settings-manager ...

#closed

**Comment by 2pay** [comment]
i am have the same this topic:

```
D:\WORKSPACE>strapi new my-strapi
INFO (11012 on DESKTOP-IND1VHE): Creating your application... It might take a few seconds.
INFO (11012 on DESKTOP-IND1VHE): Copying the dashboard...
INFO (11012 on DESKTOP-IND1VHE): Installing dependencies...                                                             ERROR (11012 on DESKTOP-IND1VHE): An error occurred during settings-manager plugin installation.
ERROR (14856 on DESKTOP-IND1VHE): Command failed: node C:\Users\admin\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js install settings-manager                                                                                                Error: Command failed: node C:\Users\admin\AppData\Roaming\npm\node_modules\strapi\bin\strapi.js install settings-manager                                                                                                                       at checkExecSyncError (child_process.js:592:13)                                                                         at execSync (child_process.js:632:13)                                                                                   at defaultPlugins.forEach.defaultPlugin (C:\Users\admin\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\after.js:91:9)
    at Array.forEach (<anonymous>)                                                                                          at pluginsInstallation (C:\Users\admin\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\after.js:89:20)                                                                                                             at npm.install.err (C:\Users\admin\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\after.js:75:7)
    at ChildProcess.onSuccess (C:\Users\admin\AppData\Roaming\npm\node_modules\strapi\node_modules\enpeem\index.js:123:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)                                                                                  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
INFO (11012 on DESKTOP-IND1VHE): The plugin content-type-builder has been successfully installed.
INFO (11012 on DESKTOP-IND1VHE): The plugin content-manager has been successfully installed.
INFO (11012 on DESKTOP-IND1VHE): Linking `strapi` dependency to the project...
INFO (11012 on DESKTOP-IND1VHE): Your new application `my-strapi` is ready at `D:\WORKSPACE\my-strapi`.
```
I am try install again but error until.
