### ISSUE TITLE
Many to many on user causes all related entities plugin property to be removed.

### ISSUE THREAD

**Issue by Cmrickels** [strapi/strapi#3424]
When creating a many to many relationship on users with another entity, a write error is returned. Each entity that has a relationship to users is updated to have the "plugin":"users-permissions" removed. 

**Steps to reproduce the behavior**
1. Go to users entity
2. Click to add relationship
3. Create a many to many relationship with another entity
4. You will get a write error pop up
5. Look at your terminal. You should see that the related entity files have been updated and the "plugin":"users-permissions" property removed.

**System**
- Node.js version: v12.2.0
- NPM version: 6.9.0
- Strapi version: 3..0.0-beta.2
- Database: Mongo
- Operating system: Mac OS

**Comment by alexandrebodin** [comment]
Thank you for reporting this issue.
