### ISSUE TITLE
debug: Server wasn't able to start properly error: (hook:bookshelf) takes too long to load

### ISSUE THREAD

**Issue by rahadur** [strapi/strapi#3427]
**Describe the bug**
```console
[2019-06-11T16:59:14.377Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-11T16:59:14.381Z] error (hook:bookshelf) takes too long to load
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api.domain.com@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api.domain.com@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rahadur\AppData\Roaming\npm-cache\_logs\2019-06-11T16_59_14_455Z-debug.log
(node:2260) UnhandledPromiseRejectionWarning: Error: Command failed: npm run develop
    at makeError (C:\Users\Rahadur\AppData\Roaming\npm\node_modules\strapi\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Users\Rahadur\AppData\Roaming\npm\node_modules\strapi\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the behavior**
1. Open terminal.
2. `strapi new api.domain.com`
3. Choose your installation type Quickstart (recommended)
4. Quickstart

**Expected behavior**
When I first time create a fresh strapi project it should start properly after create project.

**Screenshots**
![tempsnip](https://user-images.githubusercontent.com/12534866/59293275-aa388e80-8ca0-11e9-816b-d28fa2699dd1.png)

**System**
- Node.js version:  v10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.3
- Database: default (Quickstart)
- Operating system: Windows 10

**Comment by josselinlbe** [comment]
Use `straip start`

**Comment by lauriejim** [comment]
Hello! I just tried to re-install strapi (beta.5) and create the same app name / options etc.. and it works well on my side.
Will need more detail to be able to understand your issue.

Can you try to uninstall Strapi and install it again.
And try to reproduce your issue.

And make sure you have all write/read access of your folders.
