### ISSUE TITLE
WYSIWYG editor stays when changing a text field to string.

### ISSUE THREAD

**Issue by justinluk** [strapi/strapi#3428]
**Describe the bug**
If you create a `text` field and turn on the WYSIWYG editor, the editor remains if you try to change that same field to a `string` field. 

**Steps to reproduce the behavior**
1. Create a new `text` field on a content type.
2. Turn on the WYSIWYG editor for that new `text` field.
3. Save the field.
4. Change that `text` field to a `string` field.
5. Add a new entry to your content type that contains said field.
6. See that the WYSIWYG editor remains, when it should just be an input field.

**Expected behavior**
When changing a `text` field to a `string` field, I expect that just a simple one line input field is available to edit the field. Instead, the old WYSIWYG editor remains.

**System**
- Node.js version: LTS 10.16
- NPM version: 6.9.0
- Strapi version: Strapi v3.0.0-beta.2
- Database: Default MongoDB
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Thank you for this report @justinluk.
For now, disable the `WYSIWYG` before change the type of your field.

**Comment by soupette** [comment]
We have added a new field type called `richtext` in #3664 so as soon as it merged your issue will be solved.
