### ISSUE TITLE
Can't update a user

### ISSUE THREAD

**Issue by ckj** [strapi/strapi#3429]
**Describe the bug**
When attempting to find or update a user, I get the following 400 Bad request error:

```
{"statusCode":400,"error":"Bad Request","message":"select \"users-permissions_user\".* from
\"users-permissions_user\" where \"users-permissions_user\".\"_id\" = $1 limit $2 - column
 users-permissions_user._id does not exist"}
```

**Steps to reproduce the behavior**
1. Fresh install strapi@beta with Postgres

2. Make a request:

```
.put(`http://localhost:1337/users/1]`, {email: "name@email.com"}, {
        headers: {
          Authorization: `Bearer ${token}`,
        }
      })
      .then(response => {
        console.log(response);
      })
      .catch(error => {
        console.log(error.response);
      });
```

**Expected behavior**
A 200 OK, with the updated user object.

**System**
- Node.js version: 10.0.0
- NPM version: 5.60
- Strapi version: 3.0.0-beta.3
- Database: Postgres 9.6
- Operating system: MacOS 10.14.4

**Additional context**
I'm also experiencing this problem in https://github.com/strapi/strapi/issues/3382. Is it possible it's related?

**Comment by lauriejim** [comment]
Hello! Thank you for this report! 
We will have to fix is asap and add some test for this feature.

**Comment by loongmxbt** [comment]
Same issue using sqlite. beta.5
