### ISSUE TITLE
Documentation custom config override not working

### ISSUE THREAD

**Issue by WeFlyCheap** [strapi/strapi#3430]
**Describe the bug**
When I create a settings.json file at ./extensions/documentation/config/settings.json it's not overriding the default settings.

**Steps to reproduce the behavior**
1. Add the settings.json file at ./extensions/documentation/config/settings.json
2. Make a change in the settings.json file
3. Restart the server
4. Regenerate documentation
5. Check for changes

**Expected behavior**
Changes made in the settings.json file are visible at the /documentation/v1.0.0 endpoint

**Screenshots**
![image](https://user-images.githubusercontent.com/39594925/59306022-b79f4a00-8c9b-11e9-81f4-7c3bb785973e.png)
![image](https://user-images.githubusercontent.com/39594925/59306067-cbe34700-8c9b-11e9-91c0-01c801f3b612.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.beta
- Database: MongoDB
- Operating system: Ubuntu 18.06

**Comment by derrickmehaffy** [comment]
@lauriejim works except you are also injecting some paths into the top of the swagger config

![image](https://user-images.githubusercontent.com/8593673/59510385-67c1ae00-8e68-11e9-925f-e77a1794bdff.png)
