### ISSUE TITLE
in AWS light sail Ubuntu 18.04 instance, can't install strapi@beta 

### ISSUE THREAD

**Issue by monkibraum** [strapi/strapi#3431]
**Describe the bug**
Hi, I'm installing strapi of the latest version in my AWS light sail instance, but during the installation of strapi@beta, the process is just killed without any clue. I have already installed beta version in one of my EC2 instance, but no luck with light sail. 

**Steps to reproduce the behavior**
1.  go to AWS light sail console and create Ubuntu 18.04 (Os-only) free instance.
2.  install nvm
```
   sudo apt update
   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
   nvm install 10.15.3
```
3.` npm install -g strapi@beta`
4. the installing process is killed 
```
npm info lifecycle yargs@7.1.0~install: yargs@7.1.0
npm info lifecycle sass-graph@2.2.4~install: sass-graph@2.2.4
npm info lifecycle node-sass@4.12.0~install: node-sass@4.12.0

> node-sass@4.12.0 install /home/ubuntu/.nvm/versions/node/v10.15.3/lib/node_modules/strapi/node_modules/node-sass
> node scripts/install.js

Killed
```

**Expected behavior**
successful installation

**Screenshots**

![스크린샷 2019-06-12 오후 3 06 28](https://user-images.githubusercontent.com/36508569/59327367-43f54f80-8d24-11e9-8626-0fa299cbe448.png)

**System**
- Node.js version: 10.15.3
- NPM version: 6.4.1
- Strapi version: latest beta
- Database: N/A
- Operating system: Ubuntu 18.04 / AWS light sail

**Comment by davidkartuzinski** [comment]
@monkibraum - The RAM (512) in the free version of AWS Light Sail is insufficient to build the Admin Panel for Strapi. This is a known issue that is being addressed.  If you wish to use Light Sail, you can temporarily upgrade to the $10 a month (2G RAM), build Strapi the first time, and then downgrade back to the free plan.  

Please see https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws - it's mentioned in the AWS EC2 deployment guide.

**Comment by monkibraum** [comment]
@davidkartuzinski I see, thanks!

**Comment by solcomgit** [comment]
> @monkibraum - The RAM (512) in the free version of AWS Light Sail is insufficient to build the Admin Panel for Strapi. This is a known issue that is being addressed. If you wish to use Light Sail, you can temporarily upgrade to the $10 a month (2G RAM), build Strapi the first time, and then downgrade back to the free plan.
> 
> Please see https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws - it's mentioned in the AWS EC2 deployment guide.

You can create a swap file to build the admin panel
