### ISSUE TITLE
Official maintenance for Google Storage

### ISSUE THREAD

**Issue by JamesGreenaway** [strapi/strapi#3437]
The current strapi-upload-google-storage plugin is not maintained any more.  In its current state (using strapi beta) am unable to get the plugin to work. is there any intention of providing official support for this storage option? Do you know why this plugin may not work?

**Comment by derrickmehaffy** [comment]
@JamesGreenaway I am closing this issue as it doesn't follow any of the issue templates and that plugin was not built by Strapi nor is it maintained by them. You will need to contact the author.

**Comment by JamesGreenaway** [comment]
There was no template to follow? Plus, the plugin is unmaintained! There is nobody to contact, and therefore the only solution is to contact you and ask you for help?

**Comment by derrickmehaffy** [comment]
@JamesGreenaway You would use the feature request template.

Strapi did not build that plugin, you are welcome to fork it and modify it yourself (you can compare the code to any of the other providers).

But since the Strapi team did not build it, issues for it shouldn't be posted here.

**Comment by derrickmehaffy** [comment]
https://github.com/danielmahon/strapi-upload-google-storage

**Comment by JamesGreenaway** [comment]
For future reference this plugin does work in alpha, I was just unaware that the admin panel integration is currently not available for the beta version of Strapi.

**Comment by jonmhutch7** [comment]
@JamesGreenaway You're not gonna find anyone at Strapi willing to help with this so I will! Here's my workaround:

As a workaround, and this will only work if you use only the google provider, you can create the following folders in the new extensions folder
```strapi-plugin-upload > config > functions```
and the copy the
```bootstrap.js```
file from the
```strapi-plugin-upload```
npm package. On line 23 replace
```d.startsWith('strapi-provider-upload-')```
with
```d.startsWith('strapi-upload-')```
and restart the server. You should have the ability to use the strapi-upload-google-storage plugin now.

**Comment by JamesGreenaway** [comment]
Thanks @jonmhutch7 you are a gent, i'll try that later.
