### ISSUE TITLE
Email confirmation does not respect proxy URL

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#3440]
**Describe the bug**
If proxy is configured in `server.json`, eg:

```
{                                        
  "host": "localhost",                   
  "port": 1337,                          
  "proxy": {                             
    "enabled": true,                     
    "ssl": true,                         
    "host": "api.stratosphereapp.io",    
    "port": 443                          
  },                                     
  ...
```

This generates a confirmation URL correctly, for example:

```
https://sub.host.tld/auth/email-confirmation?confirmation=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDAyNGMxOTI1YmI2MTAwMjdjNTQ4MDAiLCJpZCI6IjVkMDI0YzE5MjViYjYxMDAyN2M1NDgwMCIsImlhdCI6MTU2MDQzMTY0MSwiZXhwIjoxNTYzMDIzNjQxfQ.dEbjkrRB_bXGyNAglwiDFkq83Sshf-jdyE_U0gJhSug
```

However clicking on this link redirects to `localhost:1337` rather than the proxy URL.

**Steps to reproduce the behavior**
1. Turn on `Enable email confirmation`
2. Register via `/auth/local/register`
3. Click on link inside incoming email

**Expected behavior**
Should redirect to the defined proxy URL.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: beta.4
- Database: MongoDB
- Operating system: Ubuntu

**Comment by lauriejim** [comment]
Hello @nurikabe !
Thank you for this report.
This come from [this line](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L487)
Can you submit a PR to fix it please. Will appreciate your contribution on this point.

**Need definition**
If the user doesn't set a proxy we will have to use the URL (like now)
But if there is a proxy set. We have to use it.

I suggest you to write the test before and apply the result in a new variable. 
And use this variable in the `new URL`

**Comment by derrickmehaffy** [comment]
Also it should be mentioned that if the user has SSL enabled & using port 443 then the following `:443` should be omitted from the proxyURL. Likewise if the user is not using SSL & using port 80, then `:80` should also be omitted.

@nurikabe (or anyone who wants to work on this) if you could include that, it would be great :smile:

**Comment by nurikabe** [comment]
Looked at the code and it already seemed to be correct.

It turns out that there is a "Redirection url" field under `/plugins/users-permissions/advanced` which defaults to localhost:1337

I set that to my proxy URL and problem solved.
