### ISSUE TITLE
Form submission handling

### ISSUE THREAD

**Issue by onlinebizsoft** [strapi/strapi#3446]
I'm not sure if this is going to be a feature or I'm missing something. But I found myself confused with "headless CMS". It seems to be not a full features CMS (like wordpress) when it is completely lacking form submission handling?

These CMS are just resolving the problem of building content and displaying. But there is no way to receive content from users and present them in admin panel.

So JAMPstack or headless CMS worlds seems to be going meaningless when we are going to build a simple website with introduction pages and a few forms. We have strapi for backend content, have gatsby for generating static pages, going to add some server side code (nodejs) for handling form/email and build something else to display these data in another admin panel? Thats a lots components to make a simple websites.

**Comment by davidkartuzinski** [comment]
@onlinebizsoft - We are aware of this point of view.  And we have been discussing how to provide a better developer experience with regards to how fast someone can get up and going. @Aurelsicoko, has definitely been considering different solutions, paths and way forward.

Services like [Wufoo Forms](https://www.wufoo.com/), and Netlify Forms, are trying to compete in this space to solve that problem.  

What are your thoughts? What do you think should be done about this?

**Comment by onlinebizsoft** [comment]
@davidkartuzinski I know we have some solutions to archive these or any developer can handle these with a piece of nodejs or any server side language. However my point is that if the CMS doesn't include these basic features ready then it will be a very big cons.

With wordpress (very old one, bad performance, many security issues but still most popular one), any simple website can be done with just all in one place - one document - one thing to learn. Now with Strapi, we will need help with Gatsby, then we still need something else for email, form saving, data viewing,....

What I have in mind is that Strapi should support some kind of API and admin features for these to cover most users on the world.

**Comment by davidkartuzinski** [comment]
@onlinebizsoft I think @Aurelsicoko said it better than I could...  I will only add that I came from 10 years + experience with WordPress and I understand expectations when comparing where we are (with Strapi) (after releasing Beta a few days ago) and WordPress.  I also understand that there are things that we can fundamentally do with Strapi that we will never be able to do with WordPress but anything WordPress can do, will in due time be possible with Strapi. 

Its a pleasant experience to have conversation with individuals that really care about the future of Strapi.  Thank you.

**Comment by Aurelsicoko** [comment]
I created a card on ProductBoard https://portal.productboard.com/strapi/1-public-roadmap/c/62-forms. Feel free to upvote it and give me your insights!

**Comment by opentechiz** [comment]
Do we have any progress on this?

**Comment by derrickmehaffy** [comment]
@opentechiz there is no ETA, when work starts on this you will see it linked to a PR

**Comment by engrpeters** [comment]
Any Progress ? Here Startup here.

**Comment by derrickmehaffy** [comment]
@engrpeters as mentioned previously no ETA/Progress, when work starts on it you will see a Pull Request linked here, and likewise the Product Board will be updated to reflect it's WIP status.
