### ISSUE TITLE
Infinte loading on adding users-permissions plugin

### ISSUE THREAD

**Issue by ganeshpatro321** [strapi/strapi#3447]
**Describe the bug**
Admin panel goes into infinite loading after installing the users-permission plugin

**Steps to reproduce the behavior**
1. Go to 'marketplace'
2. Click on 'Download' of roles and permissions
3. Admin Panel goes to infinite loading after server restart.
4. See error "Unhandled Promise rejection in browser console"

**Expected behavior**
Reload of admin panel with the users-permissions plugin

**System**
- Node.js version: v10.16.0
- NPM version: v6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Operating system: ubuntu 18.04

**Additional context**
I also tried installing using the command line, same issue arises.

**Comment by Naismith** [comment]
@ganeshpatro321 - Could you try creating a new project using the strapi@beta there have been significant fixes and modifications to users between the alpha/beta.

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html

**Comment by lauriejim** [comment]
Hello! Please try with last version of Strapi (beta) - plugin update have been reviewed.
