### ISSUE TITLE
Cannot get filtered results

### ISSUE THREAD

**Issue by isabellachen** [strapi/strapi#3448]
**Describe the bug**
Unable to get filtered results.

**Steps to reproduce the behavior**

I have a strapi backend with several content types. One of which is categories. Using this endpoint `http://127.0.0.1:1337/categories?_limit=100`, I get the first 100 categories, so I know my endpoint is working. _sort also works great for me `http://127.0.0.1:1337/categories?_sort=title_es:ASC&_limit=3`

Using the custom type builder, I add a field 'highlighted'. When I query for the categories, I see this new property.

![image](https://user-images.githubusercontent.com/9280665/59504703-ceb08880-8ea3-11e9-9648-3338d5c37941.png)

However, when I use a url construction as suggested in the docs `http://127.0.0.1:1337/categories?highlighted=true`, I get an empty array. Attemping the same thing with `http://127.0.0.1:1337/categories?id=5c2f4a72df10c73290465da2` gives me results. So I think the problem is that highlighted is a boolean, but the query string is a string. 

Is there a way to query on a boolean?

**Expected behavior**
I expect to get returned an array of the categories where highlighted is set to true.

**System**
- Node.js version: 10.15
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.12.7.1
- Database: MongoDB
- Operating system: WIndows 10

**Comment by alexandrebodin** [comment]
HI @isabellachen,

Can you please complete your issue with the full issue template (missing system config) so we can help you.

**Comment by isabellachen** [comment]
@alexandrebodin I've updated it with the system config.
In the end I set the highlighted field to a string, so the person who updates the CMS has to type in 'true', this way, the query `highlighted=true` works. But it is a little bit weird in terms of user experience...

**Comment by alexandrebodin** [comment]
@isabellachen You should try updating your strapi version to at least alpha-26.2 or even beta.
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/

**Comment by alexandrebodin** [comment]
I'll close this as the issue should be resolved in the latest versions
