### ISSUE TITLE
Configuration environment not selected based on NODE_ENV

### ISSUE THREAD

**Issue by davidpurkiss** [strapi/strapi#3449]
**Describe the bug**
In the alpha version, I was able to create a directory `config/environments/qa` and specify database connection settings in `database.json` (and obviously other settings but this was my specific use case). I could then set the NODE_ENV environment variable to `qa` and the settings in the qa directory would be used. This does not appear to be working the same way in the beta version. Was this functionality removed from the beta version or is it a bug?

**Steps to reproduce the behavior**
1. Make a copy `config/environment/staging` and rename it to qa.
2. Run `NODE_ENV=qa strapi start`.
3. You should see the following error.

```
TypeError: Cannot read property 'defaultConnection' of undefined
    at module.exports (/home/david/Src/tse/proxima/cms/node_modules/strapi/lib/core/bootstrap.js:25:47)
    at Strapi.load (/home/david/Src/tse/proxima/cms/node_modules/strapi/lib/Strapi.js:270:11)
```

**Expected behavior**
Strapi should run using the settings in `config/environment/qa`

**System**
- Node.js version: v10.15.0
- NPM version: 6.4.1
- Strapi version: beta.4
- Database: Postgres
- Operating system: Ubuntu 18.04.2

**Comment by davidpurkiss** [comment]
Awesome! Thank you!!

**Comment by tim-hub** [comment]
solved?
