### ISSUE TITLE
strapi.develop command broken

### ISSUE THREAD

**Issue by EzequielRamis** [strapi/strapi#3456]
**Informations**

**Service:** AWS EC2
**Node.js version:** v10.16.0
**NPM version:** 6.9.0
**Strapi version:** 3.0.0-beta.5
**Database:** Postgres
**Operating system:** Ubuntu, 18.04 LTS

**What is the current behavior?**
Using the command `strapi develop`, supposedly it builds the admin UI with development configuration, but when the progression bar label says `additional chunk assets processing (91%)`, it does nothing, the bar gets frozen and I can not develop.

![Captura de pantalla (39)](https://user-images.githubusercontent.com/44057100/59531615-c31d8b80-8ebc-11e9-9a48-e177f385264a.png)

**What is the expected behavior?**
That strapi completes the task.

**Comment by alexandrebodin** [comment]
For now the build requires at least 2Go of RAM. You will either have to build your admin locally and deploy or increase your instance memory.

Closing this as we will be improving the performances step by step.
