### ISSUE TITLE
Cannot add new administrators

### ISSUE THREAD

**Issue by selfagency** [strapi/strapi#3457]
**Describe the bug**
Cannot add new administrators.

**Steps to reproduce the behavior**
1. Go to user dropdown
2. Click on 'Manage administrators'
3. Click 'Add new administrator'

**Expected behavior**
Should see form to add a new administrator

**Screenshots**
![Capto_Capture 2019-06-14_04-14-38_PM 2019-06-14 16_25_20](https://user-images.githubusercontent.com/2541728/59536186-0bd74380-8ec1-11e9-8ace-1e22dfb02045.gif)

**System**
- Node.js version: 10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.5
- Database: MySQL 5.7
- Operating system: MacOS & Linux

**Comment by alexandrebodin** [comment]
Hi @selfagency,

Can you reload the page with the inspector open and send us the error you get either in the client or on the server.

**Comment by selfagency** [comment]
There was no error on the server nor in the console. I went ahead and deleted the `plugin_content-manager_schema` from `core_store` and then I got this after rebuilding:

```
5|kifa-cms  | error TypeError: Cannot convert undefined or null to object
5|kifa-cms  |     at Function.keys (<anonymous>)
5|kifa-cms  |     at getApis (/apps/kifa-cms/node_modules/strapi-plugin-content-manager/config/functions/utils/getters.js:8:34)
5|kifa-cms  |     at module.exports (/apps/kifa-cms/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:293:28)
5|kifa-cms  | [2019-06-14T20:47:31.584Z] info Time: Fri Jun 14 2019 20:47:31 GMT+0000 (Coordinated Universal Time)
```

All my models were gone.

![screen_shot_2019-06-14_at_4 46 20_pm](https://user-images.githubusercontent.com/2541728/59537697-4e9b1a80-8ec5-11e9-9c45-ab8e3a2b3227.png)


Seeing as how that didn't work out, at @derrickmehaffy's recommendation, I deleted the entire `core_store` table and everything is now working, despite losing my entire configuration.

There's obviously something between alpha-26.2 and beta.5 that just isn't matching up properly.

**Comment by selfagency** [comment]
To be honest, the whole migration process from alpha to beta has been disastrous for me, requiring numerous attempts at different strategies to rebuild my project. I would highly recommend focusing on creating a data import/export utility to ease this process so that migration is as simple as spinning up a new project and importing your data.

**Comment by alexandrebodin** [comment]
We are aware of a  bug in the content-manager plugin that breaks a lot of stuff and we are going to be fixing this really. 

You encourage you to go to the linked issue and share this pain point or upvote it if it already exists ;)
https://github.com/strapi/strapi/issues/3415

**Comment by alexandrebodin** [comment]
I'm closing this issue as there are no real action to do for this particular issue but fix the content manager stuff as a whole.

**Comment by gianfigueroa** [comment]
> To be honest, the whole migration process from alpha to beta has been disastrous for me, requiring numerous attempts at different strategies to rebuild my project. I would highly recommend focusing on creating a data import/export utility to ease this process so that migration is as simple as spinning up a new project and importing your data.

do you need help? 
I have script in python for lot of things for migration. In my case was easy.
