### ISSUE TITLE
Strapi generate:api replaces "_" with " " causing GraphQL to break

### ISSUE THREAD

**Issue by jsve** [strapi/strapi#3467]
**Describe the bug**
`strapi generate:api` prevents Strapi from starting if used with attribute names containing "_".

**Steps to reproduce the behavior**
1. `strapi -- generate:api stuff cms_name:string´
2. `strapi develop` or `strapi start`

Get this error:
```
[2019-06-16T10:13:18.489Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-16T10:13:18.491Z] error GraphQLError: Syntax Error: Expected :, found Name "name"
```

Probable reason: strapi generate:api replaces "_" with " ", which messes up GraphQL syntax.

**Expected behavior**
strapi and plugins should work with all names `generate:api` generates. `generate:api` should either respect "_" or fail if names include underline.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0@beta.3
- Database: Postgres
- Operating system: MacOS

**Comment by jsve** [comment]
lodash.lowerCase is the reason for "_" being replaced with " ". Why is this necessary here?

https://github.com/strapi/strapi/blob/5dd0cadafe0fca6e357d12cbcd062aced196fe93/packages/strapi-generate-api/lib/before.js#L86

**Comment by lauriejim** [comment]
Hello! Thank you for this report.
It's an easy thing to fix.
The code have to be the same as this line.
https://github.com/strapi/strapi/blob/5dd0cadafe0fca6e357d12cbcd062aced196fe93/packages/strapi-generate-api/lib/before.js#L114
Can you please open a PR to fix it. Will appreciate your contribution on Strapi.

**Comment by msimmer** [comment]
I can do this up if it's still an issue

**Comment by lauriejim** [comment]
Hello @msimmer !
Feel free to submit a PR to fix it.
Then we will be able to review your code.

**Comment by msimmer** [comment]
Sounds good :)

How are development projects created in strapi@beta, by the way? I'm trying to run `strapi new strapi-dev --dev` but am getting `error: unknown option `--dev'`.

**Comment by derrickmehaffy** [comment]
@msimmer there is no project generation now, there is a script you can use to link the monorepo packages into an existing project: https://github.com/strapi/strapi/blob/master/scripts/link.js

IIRC (@alexandrebodin can correct me if I'm wrong) you just create a new project and use that command to link in from a local copy of the monorepo which will use those local packages instead of NPM based ones. Likewise you could modify your package.json to hard link copies of the packages instead also.

**Comment by derrickmehaffy** [comment]
^^^ That I believe is a temporary solution until a better one is worked out on how to build a project from source code instead of NPM modules.

**Comment by msimmer** [comment]
Got it, thanks!
