### ISSUE TITLE
"Delete All" CTA message is unclear

### ISSUE THREAD

**Issue by acupajoe** [strapi/strapi#3470]
**Describe the bug**
When selecting multiple entries in content manager (but not all entries) the multiple delete option says "Delete All"

**Expected behavior**
Option, provided all are not selected, should say "Delete Selected"

**System**
- Strapi version: v3.0.0-alpha.26.2

**Comment by lauriejim** [comment]
![Screenshot 2019-06-17 at 23 19 09](https://user-images.githubusercontent.com/5716596/59637534-53c2c880-9156-11e9-9ae3-129c9114b5c4.png)

Hum we can debate about this point.
The is a context about the **delete all**
And this button option doesn't exist if you don't select any entry.
So for me it's clear.

@Aurelsicoko what do you thing about this.

**Comment by davidkartuzinski** [comment]
It should say "Delete selected" if less than all are selected, "Delete All" if all items are selected.

**Comment by Aurelsicoko** [comment]
I agree with all of you. We should replace the "Delete All" by "Delete selected". @acupajoe can you make a PR for this?

**Comment by derrickmehaffy** [comment]
PR made ^^
