### ISSUE TITLE
Admin UI bugs (select permissions and input requirement)

### ISSUE THREAD

**Issue by RayPS** [strapi/strapi#3472]
**Describe the bug**
1. Unable to remove request prefix, it was empty by default.
    (Can be solved by editing `config/environments/development/request.json` for now)
2. Check boxes wrong behaviour.

**Steps to reproduce the behavior**
1. In the "Configurations" -> "Request" page.
2. In the "Roles & Permissions" page.

**Expected behavior**
1. Make the Prefix input optional instead of required.
2. Checking "Select All" should always select all.

**Screenshots**
1.
<img src="https://user-images.githubusercontent.com/1941540/59593639-e185c000-9124-11e9-88a7-9e5d1483bdc0.png" width="274px">
2.
<img src="https://user-images.githubusercontent.com/1941540/59593858-47724780-9125-11e9-9f71-29e29a37f596.gif" width="387px">

**Code snippets**
n/a

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.5
- Database: default
- Operating system: macOS Mojave

**Additional context**
n/a

**Comment by derrickmehaffy** [comment]
@RayPS please update your issue following the bug report template. I will mark this as closed for now, after you have updated your issue following the correct template it can be re-opened.

**Comment by RayPS** [comment]
Thanks @derrickmehaffy , the issue has updated

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
