### ISSUE TITLE
Lifecycle not triggered when deep filtering

### ISSUE THREAD

**Issue by IceOnFire** [strapi/strapi#3473]
**Describe the bug**
The `afterFetchAll` lifecycle is triggered correctly after searching for some documents, with or without filters. But when the filter is about a nested relation, then the lifecycle method will not be triggered anymore.

**Steps to reproduce the behavior**
1. Create a new Strapi 3.0.0-beta.5 project with Mongoose
2. Add a User document
3. Create an API for the Post collection with the following fields: title (string), author ("has" relation towards User)
4. Uncomment `afterFetchAll` of Post and put a `console.log(results)` inside
5. Add a Post document
6. Perform a GET Request on `/posts` or `/posts?title=something`
7. Perform a GET Request on `/posts/author.username=something`

**Expected behavior**
Point 6 should behave as point 5, triggering the `afterFetchAll` lifecycle method.

**System**
- Node.js version: v10.16.0 
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.5 
- Database: MongoDB v3.6.8
- Operating system: Ubuntu 19.04

**Comment by SeedyROM** [comment]
The lifecycle hooks have been buggy and inconsistent for a long time (according to a comment I read, since 1.0~. You're going to have to write your own service to make up for it. It's not that bad, but it's a pain when models get used all over the place.

**Comment by SeedyROM** [comment]
This is one of the many reasons I had to dump this framework for a hand written one. 

The team working on this project is amazing and the admin panel is sublime. But the ability to alter business logic is subpar at best. They're currently working on the plugin api, but seem to be ignoring the real back end problems. Which can makes this nothing more than a fancy pipe dream of an MVP in the real world. They also seem to avoid PRs religiously. Even with definite bug fixes, which drives me crazy!

Avoid the beta for now if you have any plans of using this outside of a prototype

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
We have to completely rethink the way we manage the lifeCycle.
Other issue exist about this topic.
It's already a topic we plan to review soon.

**Comment by jacargentina** [comment]
@lauriejim Please, the beta is basically useless without correct lifecycle working fine; i think there are some missing tests on this!

Lots of code on my strapi api:
 - generate some field value depending on other ones ( slugs )
 - validate fields dependening on other fields
 - a long long etc.

🙏 fix this ASAP!

**Comment by lauriejim** [comment]
Hello @jacargentina !
You message is out of the topic.
I understand you need more feature. We are still a little team with many topics to manage.
We are doing our best to provide you the best Open Source HeadLess CMS.
You can easily create a pull request to add new features on Strapi.

**Comment by derrickmehaffy** [comment]
Closing this and linking it to the master Review Lifecycles Issue: https://github.com/strapi/strapi/issues/1443

It will be reviewed with all the rest of the Lifecycle issues. Thank you!
