### ISSUE TITLE
Remove plurals

### ISSUE THREAD

**Issue by nzpopa** [strapi/strapi#3474]
Hello,

Could you please remove the auto-generated plural for Content Type? Eg: if I add a new Content Type called "Mail", the resulting type will be "Mails". 

The problem is that we're using other language than English when naming our Types, and it sounds strange with an "s" suffix.

Thanks!

**Comment by derrickmehaffy** [comment]
@nzpopa please update your issue to follow the `feature-suggestion` template.

After you have updated your original issue, this one can be reopened.

Also as a suggestion, I think it would be better for format this in a way to suggest something like `allow the ability to turn off automated plural routes`

**Comment by jorgebarrero** [comment]
This a very important issue. Should be considered not only for display issues. also for the creation of tables
