### ISSUE TITLE
Documentation: controller (and then service.findOne) should state clearly that it ONLY accepts/process a primary key

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3481]
In the website there is not a clear explanation about that; i was trying to get the first result for a given filter, but it was not working. 

Ej:
```
const res = await strapi.services.product.findOne({name: 'My name'});
console.log(res); // null
```

This should be used instead:

```
const res = await strapi.services.product.find({name: 'My name'});
console.log(res.length); //  1
```

**Comment by derrickmehaffy** [comment]
@jacargentina Bug template please ;)

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
