### ISSUE TITLE
Somewhere in Strapi auto update sql id cause relation error

### ISSUE THREAD

**Issue by loongmxbt** [strapi/strapi#3484]
**Describe the bug**
In 29190618, I have papers collection and ids 7,9,10,...,M, but in 20190619, the papers id change into 1,2,3,...,N. This leads to the relation error in other tables. And I don't know how the ids change.

![sqlite db 20190618](https://user-images.githubusercontent.com/5986600/59740677-6561b880-929b-11e9-8da9-4252b84edd58.png)
sqlite db 20190618
![sqlite db 20190619](https://user-images.githubusercontent.com/5986600/59740694-71e61100-929b-11e9-840f-4ffd0f383430.png)
sqlite db 20190619

I removed some entries and backup the db, then next day all the ID changes, re-index from 1 to N. This leads to upload_file and other relations go wrong.
![image](https://user-images.githubusercontent.com/5986600/59742550-8ed11300-92a0-11e9-9ef5-29f1e3db851d.png)
The upload_file_morph and other table relationship went wrong.

I wonder why it happens and how can I avoid it. Thanks!

**Steps to reproduce the behavior**

**Expected behavior**
ID shouldn't be changed.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.2
- NPM version: 5.6
- Strapi version:  beta.2
- Database: Sqlite3
- Operating system: Ubuntu16.04

**Additional context**

**Comment by loongmxbt** [comment]
I modified the datatable to the original ones 7,8,9...,M, and after a few hours, the paper id change into 1...N again.

**Comment by loongmxbt** [comment]
Code and db file: https://pan.baidu.com/s/1Gx5lXPzgQQz6Z30kkrnDqw
I have a sqlite file, which by starting the server shows the behaviour descirbed above.
1. Download the code zip and data0618.db
2. Unzip axconfer-api and install deps, copy the data0618.dn to .tmp/data.db
3. Use sqlite browser to see papers table, the id begins with no 7.
3. yarn yarn build strapi develop
4. The papers table id will change to 1..N magically.

Now the axconfer-api updates to the latest version beta.7.

**Comment by lauriejim** [comment]
Please can you download your app + database on GitHub.
It will be easier. Thank you.

**Comment by derrickmehaffy** [comment]
@loongmxbt you can push your code and DB file to a repo and link that repo here on github. The Strapi team and all the contributors try to only deal in English and that link you give is in Chinese thus making it hard to navigate

**Comment by loongmxbt** [comment]
@lauriejim @derrickmehaffy  Sorry for that, I change the download link into https://mega.nz/#F!mcUV2aqS!qTccSXHjfVEm7LuqdU_7jQ

**Comment by loongmxbt** [comment]
Some weeks later, this strange behaviour occurs again. I guess that's because I edited some data in Sqlite DB management tool, then restart server and cause unknown error.

Then I migrate from sqlite to mysql. 

The most interesting thing is the following message. 
`The SQL database indexes haven't been generated successfully.` When using mysql driver occurs this message. 

When using sqlite driver, no message and the id changes automatically.

![image](https://user-images.githubusercontent.com/5986600/61676145-76d03180-ad2d-11e9-8370-2a6f9d7754fb.png)

Fortunately, mysql doesn't change id when I edit or delete data.

**Comment by lauriejim** [comment]
It comes from your sequence management.
Make sure to manage well it and keep it update to your last entry id.
