### ISSUE TITLE
How deploy Strapi v3.0.0-alpha.25.2 on Heroku

### ISSUE THREAD

**Issue by Vivsss** [strapi/strapi#3487]
**Describe the bug**
I tried to deploy Strapi (v3.0.0-alpha.25.2) on Heroku; I made the same procedure that I used to deploy previous Strapi versions as v3.0.0-alpha.16 (https://blog.strapi.io/deploying-a-strapi-api-on-heroku/), but my deployment always fails.

**Steps to reproduce the behavior**
1. Steps descibed in this article: https://blog.strapi.io/deploying-a-strapi-api-on-heroku/
2. When I run : git push heroku master, the deployment fails, with the error:
` Installing any new modules (package.json)
   npm ERR! path /tmp/build_22056665e8b5f43db9ff488ba1d8bca7/node_modules/strapi
   npm ERR! code ENOENT
   npm ERR! errno -2
   npm ERR! syscall access
   npm ERR! enoent ENOENT: no such file or directory, access '/tmp/build_22056665e8b5f43db9ff488ba1d8bca7/node_modules/strapi'
   npm ERR! enoent This is related to npm not being able to find a file.
   npm ERR! enoent 
     
   npm ERR! A complete log of this run can be found in:
   npm ERR!     /tmp/npmcache.lCTz1/_logs/2019-06-19T09_22_47_655Z-debug.log
   -----> Build failed
`

**Expected behavior**
The Strapi app should to deploy on Heroku and to attach to a mongo database

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.4.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-alpha.25.2 
- Database: MongoDb
- Operating system: Mac

**Additional context**

**Comment by derrickmehaffy** [comment]
See the following documentation: https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#heroku

**Comment by Vivsss** [comment]
Many thanks @derrickmehaffy !

**Comment by Vivsss** [comment]
> See the following documentation: https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#heroku

I can't find in the documentation that you suggested to me any reference about the 'heroku addons:create mongolab:sandbox --as DATABASE' addons; it's still possible to use it instead of the MongoDB Atlas?

Many thanks!

**Comment by davidkartuzinski** [comment]
@Vivsss are you deploying the Alpha version or Beta version of Strapi? 

https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#_7-heroku-database-set-up  - did you follow these steps? They should be the same for Alpha...

**Comment by Vivsss** [comment]
> @Vivsss are you deploying the Alpha version or Beta version of Strapi?
> 
> https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#_7-heroku-database-set-up - did you follow these steps? They should be the same for Alpha...
> 
> If you're not using Atlas, the instructions will be similar to the postgres instructions in the link above but for mongodb.

Thanks for your reply @davidkartuzinski !
I'm deploying a  Strapi v3.0.0-alpha.25.2 but I can't deploy Strapi to Heroku; I followed all those steps that you suggested to me, but I still get this error:
`error Make sure your MongoDB database is running...
...
...
...
State changed from starting to crashed
 Process exited with status 1
at=error code=H10 desc="App crashed" method=GET path="/" host=salty-bayou-20692.herokuapp.com request_id=450bff42-5634-43d7-bcb5-05e1aca5d0ca fwd="78.192.237.13" dyno= connect= service= status=503 bytes= protocol=https`

Many thanks for your help!

**Comment by davidkartuzinski** [comment]
@Vivsss - I am trying to get to seeing if I can get a mongodb / heroku working.  Did you develop with MongoDB on your local machine or did you use QuickStart?  MongoDb needs to be used when developing locally for Alpha. In which case you will need to follow the documentation under Databases to set up a Strapi Project using MongoDb.

**Comment by Vivsss** [comment]
> @Vivsss - I am trying to get to seeing if I can get a mongodb / heroku working. Did you develop with MongoDB on your local machine or did you use QuickStart? MongoDb needs to be used when developing locally for Alpha. In which case you will need to follow the documentation under Databases to set up a Strapi Project using MongoDb.
> 
> https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku-mongodb
> 
> You may also have this issue: https://www.youtube.com/watch?v=5uTR1uOZZQo - Heroku defaults to Node Version 12 but that is incompatible with Strapi. Did you change that as per the video?
> 
> Another issue I found with Heroku, is this: https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#_4-update-gitignore - you. need to add `package-lock.json` to your `.gitignore` file

@ davidkartuzinski  Yes, I developed with MongoDB on your local machine, not using QuickStart but the manual configuration for MongoDB. I go check the issue in the video, I hope that this is problem. About the latest issue, I already did that. Honestly, I never had issue to deploy to Heroku with previous versions of Strapi, but I have this issue since I upgraded Strapi to  v3.0.0-alpha.25.2 version, I don't know why. Many thanks for your help and suggestions!

**Comment by davidkartuzinski** [comment]
@Vivsss - I have now followed the instructions from the blog and videos 3 times and they have had some edits.  But I can confirm that you can follow these instructions and deploy to Heroku no problem with PostgreSQL.  
I will now see about getting a MongoAtlas going, and then see about their mongodb plugin.  Hopefully you solved it though!

**Comment by Vivsss** [comment]
@davidkartuzinski many thanks for your reply and help! Unfortunately, the suggestion in the video doesn't work for my issue... 
To resume what is it: I can deploy my strapi app (v3.0.0-alpha.25.2) from my local machine to Heroku and I can attach it a MondoDB database through the command
`heroku addons:create mongolab:sandbox --as DATABASE`

Then, I add to the DATABASE_URI Config Var, these others: DATABASE_NAME, DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_HOST and DATABASE_PORT.

Nonetheless, when I try to access to my app (https://enigmatic-tor-49434.herokuapp.com/), I get this error: 
`app[web.1]: error Make sure your MongoDB database is running...`
`heroku[web.1]: Process exited with status 1`
`heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=enigmatic-tor-49434.herokuapp.com request_id=44fb9efe-0448-4173-b338-fda993f2e50f fwd="78.192.237.13" dyno= connect= service= status=503 bytes= protocol=https`

**Comment by davidkartuzinski** [comment]
@Vivsss - I am able to recreate this now.  Thank you for your patience.  I don't have a full solution yet, but I will!

**Comment by davidkartuzinski** [comment]
@Vivsss Please upgrade to the latest version of Strapi.  Since the latest update, I have only been able to recreate this error when I add a space after any of the key:value pairs in the Heroku Config.  Heroku seems to not strip the empty spaces.  

I have fully updated the Strapi / Gatsby Tutorial to work with Beta.  That section is applicable regardless of using Gatsby....

**Comment by Vivsss** [comment]
Many thanks @ davidkartuzinski ! 
Could you provide the link of the Strapi / Gatsby Tutorial that you updated?

**Comment by davidkartuzinski** [comment]
@Vivsss 

Here you go.  https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/ - you are welcome to open an issue about it if there is something that is unclear or doesn't work for you! But it should be totally fine now.  If in doubt, follow the written blog part.
