### ISSUE TITLE
Unable to install strapi@beta

### ISSUE THREAD

**Issue by briantan1979** [strapi/strapi#3493]
**Describe the bug**
Tried to install strapi using the command npm install strapi@beta -g

**Steps to reproduce the behavior**
1. sudo su
2. npm install strapi@beta -g
3. Errors displayed and strapi is not installed

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0 Beta 6
- Database: MongoDB 3.6.3
- Operating system: Ubuntu 18.04.2 LTS
![Snap 2019-06-20 at 13 09 51](https://user-images.githubusercontent.com/11909288/59819977-b8e80b00-935c-11e9-96f3-9e245e04c0e8.png)

**Comment by derrickmehaffy** [comment]
You shouldn't be installing any node.js application as root.

I would recommend you create a service user and scope global packages to that user (or use nvm like you are here).

https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#warn-eacces-or-error-eacces-permission-denied

Also:

http://syskall.com/dont-run-node-dot-js-as-root/
https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

Marking as closed as this is not an issue with Strapi

**Comment by briantan1979** [comment]
I created a service user as advised and still the same.
Is the problem I faced here similar to the problem reported [here](https://github.com/strapi/strapi/issues/3421) ?
If yes, what are the missing dependencies and please advise how to install them ?

**Comment by derrickmehaffy** [comment]
`sudo apt install -y build-essentials`

**Comment by Turkyden** [comment]
@briantan1979 You can try to install with `root` and run your node app with `other service user`.
