### ISSUE TITLE
s3 uploads fail

### ISSUE THREAD

**Issue by robster11** [strapi/strapi#3494]
When I attempt o upload files greater than approx 2mb I get an error.
smaller file seem to work fine.
I have confirmed that upload size has been set to a 20000mb so upload image is not an issue.

steps to reproduce,

upload file of 2mb or greater size using s3 upload plugin
after a period of time saying uploading file strapi admin says error.

I have tried with images and videos.
failing on beta.6 and beta.5

I can confirm the files upload correctly when uploading directly to s3 bucket.

**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
@robster11 Please fillout the template properly, after you have updated the template reply back and this can be reopened.

**Comment by lauriejim** [comment]
It's probably about your nginx config (or something else on your server) that block files with a big size.

**Comment by derrickmehaffy** [comment]
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by inverleighdigital** [comment]
Thanks I will check nginx configuration as strapi is running behind nginx and confirm if this fixes the issue.

**Comment by inverleighdigital** [comment]
confirming this was due to nginx configuration. thanks derrik!

**Comment by derrickmehaffy** [comment]
Your welcome @inverleighdigital o7
