### ISSUE TITLE
Upload multiple files remove all older relations of the entity

### ISSUE THREAD

**Issue by Lith** [strapi/strapi#3496]
**Describe the bug**
Since many month, when I upload new files for an entity, all older files are removed from the relation table _upload_file_morph_.
I wait many new Strapi update with the hope of this problem will be fixed, but not...
I try to reinstall all from the beginning, but the same bug appears.
I've found similar bugs fixed, but for other database system.

**Steps to reproduce the behavior**
1. Upload many files to server for an entity 
2. Refresh and check all files are ok
3. Upload new files to server for the same entity
4. Refresh and check all older files and new files are ok
4. See than all previous files are unlink from _upload_file_morph_ relations table

**Expected behavior**
If I upload multiple files on an entity, I want to keep all relations in _upload_file_morph_ table

**Model example**
```
    "detail_card": {
      "default": "",
      "type": "string"
    },
    "card_validated": {
      "type": "boolean"
    },
    "media_card": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    },
    "media_pictures": {
      "collection": "file",
      "via": "related",
      "plugin": "upload"
    }
```
- Field _media_card_ : 1 picture
- Field _media_pictures_ : multiple pictures

**System**
- **Node.js version**: v10.14.2
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-beta.6
- **Database**: bookshelf - mysql
- **Operating system**: Mac OS, Debian

**Additional context**
- **Upload system** : Google Cloud Storage and Local
The bug appears with upload-local system or any other upload system.

I used the default upload plugin without modification.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue!
We will do our best to fix this issue soon as possible.

**Comment by Radau** [comment]
@Lith here's a workaround I posted on a related issue, @lauriejim can you please check the validity of it and weigh in? I don't foresee it breaking anything but I haven't contributed to Strapi so I'm not very familiar with the codebase. Hopefully it can help you track down the issue and implement a permanent fix!

https://github.com/strapi/strapi/issues/1770#issuecomment-526319989

**Comment by mohimali** [comment]
@Radau Ive been looking into the issue for this issue, im really new to strapi and can't really find out how to test this fix you have created, but would this change fix the multi upload issue where the upload_file_morph existing relations gets replaced by new ones uploaded for the same entity?

**Comment by mohimali** [comment]
Works perfectly fine on mongodb(and also noticed no upload_file_morph so it must be doing it in a different way), so i think its mysql specific or whichever dbs use that relation file

**Comment by Radau** [comment]
Yes it is for bookshelf which is the MySQL ORM for strapi.

You would edit node_modules/strapi-hook-bookshelf/lib/relations.js which is 
in the root of your project. The other thread I linked to above provides 
some guidance as to what part of the file to edit

**Comment by mohimali** [comment]
I've just tried mysql now without your changes with a fresh custom installation selecting mysql as the dB and it works fine now. It's very strange I've got similar builds running on the same strapi beta running with this same issue. So unsure why it does it on some installations and not others.

**Comment by Lith** [comment]
> @Lith here's a workaround I posted on a related issue, @lauriejim can you please check the validity of it and weigh in? I don't foresee it breaking anything but I haven't contributed to Strapi so I'm not very familiar with the codebase. Hopefully it can help you track down the issue and implement a permanent fix!
> 
> [#1770 (comment)](https://github.com/strapi/strapi/issues/1770#issuecomment-526319989)

Hi @Radau, your solution is working fine :) 
I've test with the latest strapi version : 3.0.0-beta.16.1

@lauriejim Could you check and update `strapi-hook-bookshelf` with this solution or something similar ? 

Thanks !

**Comment by lauriejim** [comment]
Hello! This issue has been fixed in the last version of strapi (beta.16.2)
I close this issue.
Thank you for your interaction in this issue. Appreciate.
[Here is the PR](https://github.com/strapi/strapi/pull/3963) that close this issue.
