### ISSUE TITLE
When I send a POST with JSON field I receive Internal Server Error

### ISSUE THREAD

**Issue by riquedev** [strapi/strapi#3498]
**Describe the bug**
When performing a POST whose some fields are of JSON format I get internal error.

**Steps to reproduce the behavior**
1. The content must have JSON fields.
2. Now using NodeJS or any other language, get the authentication token
3. Now, send a POST to the content that was created.
```typescript
axios({
                        method: "post",
                        url: "<api_url>",
                        data: JSON.stringify(data),
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json; charset=utf-8',
                            "Authorization": `Bearer ${token}`
                        }
}).then(console.log).catch(console.error);
```

**Expected behavior**
You should now have received the internal error.

**Screenshots**
![xaasa](https://user-images.githubusercontent.com/18220248/59864673-bfc34d80-935d-11e9-8fd2-2e2b8859da7d.PNG)

**Code snippets**
```typescript
var pg = require('pg');
var conString = "";
var axios = require("axios");
const fetch = require('node-fetch');
var querystring = require('querystring');

var client = new pg.Client(conString);
const psql = (token) => {


    client.connect();
    client.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'").then((res) => {

        for (let rowIndex in res.rows) {

            let row = res.rows[rowIndex];
            let table_name = row.table_name;

            client.query(`SELECT count(*) as count from ${table_name}`).then((res) => {

                let count = res.rows[0].count;

                client.query(`SELECT * from ${table_name} LIMIT 10`).then(res => {

                    let rows = res.rows;
                    let fields = Object.keys(rows[0]);
                    // console.log(fields);

                    let data = {
                        name: table_name,
                        count: count,
                        fields: fields,
                        sample: rows
                    };

                    axios({
                        method: "post",
                        url: "<api_post_url>",
                        data: JSON.stringify(data),
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json; charset=utf-8',
                            "Authorization": `Bearer ${token}`
                        }
                    }).then(console.log).catch(console.error);

                })
            }).catch(console.error)
        }
    }).catch(console.error);
}

axios.post("<auth_url>l", {
    identifier: "",
    password: ""
}).then(response => {
    psql(response.data.jwt);
})
```

**Strapi System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB
- Operating system: Centos 7

**Client System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@riquedev `Strapi version: 3.0.0-alpha.26.2` Please test with the beta as the alpha is no longer being updated.

If the issue persists in the beta than we can keep this open.

**Comment by lauriejim** [comment]
Hello! I'm not able to reproduce your issue.
Did you have any other error log in your terminal ?

Can you send us the value of your `data` object.

**Comment by fabianwohlfart** [comment]
Just a small question, and I am absolutly not sure if this helps: But does the data needs to be stringified when sending json data with axios? Thought it shall not... That's probablz why its a 500, because the server cannot process a string if it thinks its an object.
