### ISSUE TITLE
Cannot Start Alpha Release

### ISSUE THREAD

**Issue by meads2** [strapi/strapi#350]
**Node.js version**:
**npm version**:
**Strapi version**:
strapi@alpha
**Operating system**:
Mac OSX
<img width="652" alt="screen shot 2017-11-21 at 9 39 22 pm" src="https://user-images.githubusercontent.com/13305877/33107287-87e32a30-cf04-11e7-9bc3-c2ac3d8996e6.png">

I installed a fresh copy of the Strapi alpha release, and it won't let me start the application. I took a look at the Strapi.js file where it says there is an error, but everything looks ok.

**Comment by dj-hedgehog** [comment]
If anyone else comes across this the error was that @meads2 was using Node v6. The new Strapi requires at least Node v8 für native `async...await` support among other features.
