### ISSUE TITLE
users-permissions middleware always checks JWT even when not required

### ISSUE THREAD

**Issue by TitoVince35** [strapi/strapi#3500]
**Describe the bug**
`users-permissions` middleware always checks given authorization token, even when not required.

**Steps to reproduce the behavior**
1. Create a model in content type builder
2. Make every action public on this model
3. Launch a "find" query on this model, adding an Authorization header with random content (using Postman, Curl...)
4. See result:
```json
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Invalid token."
}
```

**Expected behavior**
Unless an explicit "plugin.users-permissions.isAuthenticated" policy is given, no JWT validation should occur from Strapi's core.

**System**
- Node.js version: 10.10.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta2
- Database: MariaDB
- Operating system: Ubuntu 16.04LTS

**Additional context**
This is an issue for my project.
I wish to be able to use my own JWT-based authentication service using a policy.
Actually, `users-permissions`, or whatever does the JWT check, seems to be a mandatory middleware that cannot be skipped.

In case someone would be interested, there is a workaround to use a custom JWT validation:
- Create a `custom-jwt-auth` middleware and make sure it executes before `users-permissions`
- Perform your own validation, then replace the authorization header with a new one built for Strapi. The payload should contain an `id` field, idealy pointing to a Strapi user record id if your route is not declared as public.
- Drawback : you'll have to filter out every route on which you don't want your middleware to run - it's best to use policies when possible!!

**Comment by lauriejim** [comment]
Hello! I think in your case you just want to customize the [permissions.js policy](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js) to match with your custom need.

To customize it you will have to create a new file here `./extensions/users-permissions/config/policies/permissions.js`
Then to copy the origin file and to update what you want in this function to deal with your need.

**Comment by lauriejim** [comment]
But you point a good

**Comment by lauriejim** [comment]
But it's an other issue. So I close this one and will open one about the decision we have to do about this second point.

**Comment by TitoVince35** [comment]
I guess overriding `./extensions/users-permissions/config/policies/permissions.js` will do the trick in my case. Thanks for the quick help!
