### ISSUE TITLE
Newly created content types don't show in content manager

### ISSUE THREAD

**Issue by richard-hijzen** [strapi/strapi#3504]
## Describe the bug
When i create a new content type locally everything go's well. I can see the content type in the left menu and also in the content manager. I can even fill in all the fields.
When i deploy strapi to heroku i can see the content type in the left menu but not in the content manager and i also can't add a new type. The content types from the first time when i deployed to heroku work as expected. 

## error messages
I don't get any error messages.

## expected behavior
When i add strapi content types locally and then deploy them on heroku i expect that i can also access them to add content.

## screenshots

![strapi local](https://user-images.githubusercontent.com/18099231/59922308-cbcc0f80-9430-11e9-851a-e4220f06275a.png)

![strapi heroku](https://user-images.githubusercontent.com/18099231/59922424-07ff7000-9431-11e9-812c-6b66b8632835.jpg)

![strapi content type loading](https://user-images.githubusercontent.com/18099231/59922927-4e090380-9432-11e9-86d1-fe5f4527f3b8.jpg)

## System
- Node.js version: node v10.15.3
- NPM version:  4.6.1
- Strapi version: 3.0.0-alpha.25.2

**Comment by davidkartuzinski** [comment]
@richard-hijzen - Hello.  When you deploy your app to Heroku it is deployed in Production mode, so you won't be able to create new custom Content Types.  That you will have to do locally, and then push.

Did you go to the Content Manager and into your custom content type and in the tab for view make sure it is there?

**Comment by richard-hijzen** [comment]
Hello @davidkartuzinski , i think you didn't understand the issue. When i make a new content type locally and then push it to my strapi on heroku. The content type is visible in the left menu but in the content manager it is not visible. It looks like it isn't possible to add extra content types locally and then push them to the existing app on heroku to update the app .

**Comment by soupette** [comment]
@richard-hijzen, you also need to push your settings into production.

**Comment by richard-hijzen** [comment]
@soupette, Which settings do you mean?

**Comment by derrickmehaffy** [comment]
@richard-hijzen in your database `core_store` something like `plugin_content-manager_schema` that needs to be updated on your production database for now.

**Comment by richard-hijzen** [comment]
@derrickmehaffy, why doesn't strapi update the database automatically when I deploy an updated version of strapi with new content types? Locally everything works like it should and also the first deployment works fine. I can't find info that says that i need to do manual updates of the database.

**Comment by SeedyROM** [comment]
Nope, it won't do what you expect. Look at their feature timeline to be even more confused. This is apparently a non-issue.

**Comment by derrickmehaffy** [comment]
It's a problem (one that is very well known) and a fix is being worked on, but it's going to take some time.

Normally this doesn't happen with other deployments like on a server but something odd happens with heroku users.

**Comment by davidkartuzinski** [comment]
@richard-hijzen did @derrickmehaffy - explanation clear things up for you?  I guess I didn't understand.  Sorry about that.

**Comment by richard-hijzen** [comment]
@davidkartuzinski , yes now it's clear.

**Comment by davidkartuzinski** [comment]
@richard-hijzen Wonderful. I will close the issue then.

**Comment by gavmck** [comment]
In case someone else comes across this, we're experiencing the same issue with docker.

**Comment by twhitelow1** [comment]
I don't understand though. What is the fix on this?
