### ISSUE TITLE
strapi-admin@3.0.0-beta.7 seems to be corrupted

### ISSUE THREAD

**Issue by dakshrathod40** [strapi/strapi#3505]
So this is the issue i am facing while setting up the strpai beta version on Docker.
Can anyone help me out?
![Screenshot (8)](https://user-images.githubusercontent.com/48468251/59925321-76eec000-9455-11e9-81d1-e1ce1fad327f.png)

**Comment by alexandrebodin** [comment]
@dakshrathod40 Can you plz follow the issue template to get help.

**Comment by dakshrathod40** [comment]
sorry about that!
can you direct me?

**Comment by alexandrebodin** [comment]
When you create an issue there is a template. Fill it. ;)

then share your Dockerfile

**Comment by alexandrebodin** [comment]
Closing in favor of https://github.com/strapi/strapi/issues/3506

**Comment by syedsimanta03** [comment]
same issue on windows 10 nodev10
