### ISSUE TITLE
strapi-admin@3.0.0-beta.7 seems to be corrupted

### ISSUE THREAD

**Issue by dakshrathod40** [strapi/strapi#3506]
**Describe the bug**
i am deploying my strapi project by Docker there i am facing this issue

**Steps to reproduce the behavior**
build the image it would fail at npm install

**Expected behavior**
build image

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/48468251/59928928-617d9400-945d-11e9-9748-2fa0e53678c4.png)

**Code snippets**
```dockerfile
FROM node:11.15.0-stretch

WORKDIR /usr/src/api

RUN npm install -g strapi@beta

COPY . ./

RUN npm cache clean --force
RUN npm cache verify
RUN npm install
RUN chmod +x ./strapi.sh

EXPOSE 1337

COPY healthcheck.js ./
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s \
    CMD node /usr/src/api/healthcheck.js

CMD ["./strapi.sh"]
```

**System**
- Node.js version: 11.15.0
- NPM version: 6.9.0
- Strapi version: strapi@3.0.0-beta.7
- Database: MongoDB
- Operating system: linux

**Additional context**

**Comment by dakshrathod40** [comment]
I did use the node 10 image but i am facing the same problem

**Comment by alexandrebodin** [comment]
`FROM node:11.15.0-stretch` You are using node 11.15.0 in your image

**Comment by dakshrathod40** [comment]
i meant i have tried with node 10 it didnt work so i tried 11

**Comment by alexandrebodin** [comment]
When exactly does that error happen ? can you share a full log ?

**Comment by derrickmehaffy** [comment]
Tried to reproduce but I didn't get the error updating my project to beta.7

**Comment by alexandrebodin** [comment]
> Tried to reproduce but I didn't get the error updating my project to beta.7

I just copy pasted the the dockerfile and no errors either.

**Comment by derrickmehaffy** [comment]
Maybe an NPM cache problem? I know it took a good 20 minutes for the beta.7 updates to populate to the US servers.

**Comment by derrickmehaffy** [comment]
I'm marking this as closed as we don't have any new information related to the issue and this version (beta.7) is 2 versions old now.

If this comes up again it can be reopened.

**Comment by syedsimanta03** [comment]
same issue. os - windows 10 noce v10. Strapi is full of errors for windows users
