### ISSUE TITLE
Router prefix

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#3507]
**Description of the topic**

In your Strapi application you can add a `prefix` for the router.

See [here](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/router/index.js#L28), Strapi apply a prefix the the Koa router.

To do so, add the following object in your `./config/environment/.../request.json`.

```json
{
  ...
  "router": {
    "prefix": "/api"
  }
}
```

This will apply a **global** prefix to all routes.

**So that is my question**

1. With this option do we have to apply it to the admin and the the public folder?
_Because the admin route will be `/api/admin` and it's a little bit strange._

2. Do we need to have one prefix for the generated API, one different for the admin and one other for plugins, and again one other for the public folder?
_That  can be the same but have we to be able to do that._

**Describe the bug**

Currently if you add a prefix, the API will work, but the admin is not able to query the assets with the prefix. 
So there is no admin.

**Steps to reproduce the behavior**

1. Add the router prefix option as explain previously.
2. Start your application and try to access to your admin.

**System**
- Node.js version: v10.14.2
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.7
- Database: SQLite
- Operating system: macOS Mojave

**Comment by alexandrebodin** [comment]
Realted https://github.com/strapi/strapi/pull/3445

**Comment by derrickmehaffy** [comment]
In my mind the admin shouldn't be part of the prefix but that does complicate plugins and for instance the public path.

My thoughts would be something like:
1) Allow configurable router prefixes for all of them (plugin_prefix: blah, api_prefix: blah, admin_prefix: blah) Ugly but simple
2) Configure a single prefix but with booleans to turn it on and off
3) Only allow settings the prefix on generated routes (plugins included) and isolate the admin itself

**Comment by Aurelsicoko** [comment]
We should only apply the prefix to the public routes (it means to the routes generated by the user). Over time, I think we should define some of the plugins routes and administration routes as private. They are used for the dashboard, they should be consistent and not be changed at all. Otherwise, it creates issues like this one.
With that in mind,

**Comment by aisensiy** [comment]
I am deploying strapi in kubernetes. In order to expose strapi outside of kubernetes I have to put it behind an path based [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) like `/strapi`. But I found that I can not access admin any more. The `js` inside admin `index` page always try to access the `/admin` to get more js files but not the `/strapi/admin` page. 

![image](https://user-images.githubusercontent.com/661860/61520598-2ad97000-aa41-11e9-816e-2807bb900247.png)

I think my question may be related with this issue. And use a subdomain is not possible for my situation.

**Comment by Aurelsicoko** [comment]
There was a `host` parameter to set in the `server.json` path on the alpha version ([see alpha doc](https://strapi.io/documentation/3.0.0-alpha.x/advanced/customize-admin.html#deployment)) but I cannot find it in the beta documentation. It seems to have been removed ([see beta doc](https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#deployment)).

There is certainly a better way to do it now? @alexandrebodin or @soupette

**Comment by alexandrebodin** [comment]
Hi @aisensiy.

What you are looking for is documented [here](https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#deployment)

You can set the `admin.path` key and build your admin for a certain path.
If you also configure strapi to be in a subpath you need to specify the backend url of the strapi api like in the documentation :)

Hope this helps

**Comment by aisensiy** [comment]
Thanks for your reply. It works for me.

**Comment by ShyamRaj** [comment]
@alexandrebodin Even if you set the backend path in the config, The issue still exists for all the other plugins. Like content-manager, users-permissions etc., which prevents you to use it.

Any solutions for adding a prefix to content-manager and users-permissions? In other words prefix for plugins?

**Comment by derrickmehaffy** [comment]
I'm making an update here because this question is being asked a lot on Slack.

Until Strapi re-implement the router prefix you will need to use a sub-domain instead of a sub-folder.

If you would like to see this feature added back into Strapi respond to the original post by @lauriejim  with a 👍

**Comment by derrickmehaffy** [comment]
@lauriejim Also not a discussion as @petersg83 is already working on this as well

**Comment by derrickmehaffy** [comment]
I am marking this as closed as it has been fixed with https://github.com/strapi/strapi/pull/5833 and will be released in rc.1. Currently there is no plans to backport this to the beta versions.
