### ISSUE TITLE
how can I add upload image to strapi dashboard

### ISSUE THREAD

**Issue by oukrims** [strapi/strapi#351]
**Node.js version**: 6.11.5
**npm version**: 3.10.10
**Strapi version**:1.6.4
**Operating system**:ubuntu 16.04

**Comment by yesihao** [comment]
+1 seem there's no image uploader in v3 neither

**Comment by edimitchel** [comment]
Not yet ;)

**Comment by TareqElMasri** [comment]
Is that done?

**Comment by template01** [comment]
@TareqElMasri: yes! since strapi@alpha.11
