### ISSUE TITLE
Webpack stuck at "additional chunk assets processing (91%)" 

### ISSUE THREAD

**Issue by lopermo** [strapi/strapi#3512]
**Describe the bug**
Webpack won't finish loading.

**Steps to reproduce the behavior**
1. Use "strapi dev"

**Expected behavior**
It should finish loading and I'd have access to the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/11388254/59970557-8b23e180-9569-11e9-9745-7c43ea297bff.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.7
- Database: sqlite
- Operating system: Ubuntu

**Additional context**
If I use strapi start it'll finish running, but I cannot access "/admin". It'll always load the root path.

**Comment by alexandrebodin** [comment]
Hello,

It is a known issue with system having less than ~2Go of RAM is it your case ?

**Comment by heihachi88** [comment]
Just increase RAM and number of CPU's if you're using docker. It's not documented, i've spent whole day to figure it out.

**Comment by juanlopez1** [comment]
Hello, I had the same issue. To solve, I increased RAM to 2GB and work perfectly for me! :D

**Comment by davidkartuzinski** [comment]
@heihachi88 

> Just increase RAM and number of CPU's if you're using docker. It's not documented, i've spent whole day to figure it out.

I apologize that you had trouble finding this information. We did put it in our Deployment Guide. 
Each of the sections (Digital Ocean/AWS) have mention of this. 

For example,
https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#launch-an-ec2-virtual-machine

How could this be better documented?

**Comment by heihachi88** [comment]
@davidkartuzinski it's hidden, even when you pointed out to this link i found it using find function. I suggest to move it in a general section, like system requirements, so everyone would notice this.

**Comment by alexandrebodin** [comment]
I'm closing this issue as we are already aware of the limitations and are going to improve this as we go in the next months.

**Comment by madonzy** [comment]
@alexandrebodin @webcoderkz @davidkartuzinski no need to buy 10$ plan. Just create 2GB swap file. Works for me. https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-debian-9

**Comment by specsdhdeveloper** [comment]
@madonzy Worked for me, great, thank you!

**Comment by webcoderkz** [comment]
> @alexandrebodin @webcoderkz @davidkartuzinski no need to buy 10$ plan. Just create 2GB swap file. Works for me. https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-debian-9

I already had 2GB swap file, had no effect for me,

**Comment by scottydev** [comment]
> @alexandrebodin @webcoderkz @davidkartuzinski no need to buy 10$ plan. Just create 2GB swap file. Works for me. https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-debian-9

This worked great for me, thank you

**Comment by ZeeEssDoubleU** [comment]
Does the 2GB swapfile still work?  As in, has it currently worked for someone who's deployed in the past month?  I've followed the AWS and Digital Ocean swapfile guides to the T and I'm still getting memory heap allocation errors.

**Comment by derrickmehaffy** [comment]
I don't believe swap will really work in this case, we are actively working towards decreasing the RAM usage during build, but at the moment anything less than that while building isn't supported.

**Comment by Shizuri** [comment]
I'm on the AWS t2.micro free tier. Had the same problem. This worked for me:
1) Add a swap file [https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-memory-swap-file/)
2) Update Node.js memory limit to 1536MB `NODE_OPTIONS="--max-old-space-size=1536"` as per Node.js official recommendations [https://nodejs.org/api/cli.html#cli_node_options_options](https://nodejs.org/api/cli.html#cli_node_options_options

**Comment by irvanster** [comment]
> @alexandrebodin @webcoderkz @davidkartuzinski no need to buy 10$ plan. Just create 2GB swap file. Works for me. https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-debian-9

Thanks its Worked

**Comment by wajeshubham** [comment]
I was deploying my strapi app on EC2 t2.micro which has 1GiB RAM. However, Strapi production build stucks due to RAM shortage and strapi build at least required RAM > 1GiB.

To resolve this we can utilise swapfiles. When physical RAM is already in use, Amazon EC2 instances use swap space as a short-term replacement for physical RAM.

Run the following commands to make it work:

SSH into your EC2 instance
```
ssh -i "yourpem.pem" ubuntu@ec2-1-1-1-1.ap-south-1.compute.amazonaws.com
```
```
$ sudo fallocate -l 2G /swapfile
```

3G in the above command can be 1G which denotes we want to use 1GB swap space as a short-term replacement for physical RAM.

```
$ sudo chmod 600 /swapfile
```

```
$ sudo mkswap /swapfile
```

```
$ sudo swapon /swapfile
```

```
$ sudo nano /etc/fstab
```
Add the following like at the end of the above file
```
/swapfile swap swap defaults 0 0
```
Once done save the file.

List down the swap files. You should see one swap file being added.
```
$ sudo swapon -s
```

Now, build the Strapi project
```
$ cd /your-project
```
```
$ NODE_OPTIONS="--max-old-space-size=1536" NODE_ENV=production npm run build 
```
This should build the project successfully.

**Comment by rde9** [comment]
> To resolve this we can utilise swapfiles. When physical RAM is already in use, Amazon EC2 instances use swap space as a short-term replacement for physical RAM.

Thanks! I was using t4g.micro and had the same issue. With extra 2GB swap file it worked fine.

**Comment by stand1715** [comment]
> I was deploying my strapi app on EC2 t2.micro which has 1GiB RAM. However, Strapi production build stucks due to RAM shortage and strapi build at least required RAM > 1GiB.
> 
> To resolve this we can utilise swapfiles. When physical RAM is already in use, Amazon EC2 instances use swap space as a short-term replacement for physical RAM.
> 
> Run the following commands to make it work:
> 
> SSH into your EC2 instance
> 
> ```
> ssh -i "yourpem.pem" ubuntu@ec2-1-1-1-1.ap-south-1.compute.amazonaws.com
> ```
> 
> ```
> $ sudo fallocate -l 2G /swapfile
> ```
> 
> 3G in the above command can be 1G which denotes we want to use 1GB swap space as a short-term replacement for physical RAM.
> 
> ```
> $ sudo chmod 600 /swapfile
> ```
> 
> ```
> $ sudo mkswap /swapfile
> ```
> 
> ```
> $ sudo swapon /swapfile
> ```
> 
> ```
> $ sudo nano /etc/fstab
> ```
> 
> Add the following like at the end of the above file
> 
> ```
> /swapfile swap swap defaults 0 0
> ```
> 
> Once done save the file.
> 
> List down the swap files. You should see one swap file being added.
> 
> ```
> $ sudo swapon -s
> ```
> 
> Now, build the Strapi project
> 
> ```
> $ cd /your-project
> ```
> 
> ```
> $ NODE_OPTIONS="--max-old-space-size=1536" NODE_ENV=production npm run build 
> ```
> 
> This should build the project successfully.

perfect.
