### ISSUE TITLE
Cannot start strapi because of db error

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#3513]
**System**
- Node.js version: 10
- NPM version: bundled with node:10 image
- Strapi version: 3.0.0-beta.6
- Database: PostgreSQL 10
- Operating system: CentOS 7

When the following command fired: `NODE_ENV=production npm run start`

i'm getting the following errors in console:

```
error: could not open extension control file "/usr/pgsql-10/share/extension/pg_trgm.control": No such file or directory
    at Connection.parseE (/var/www/cms/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/var/www/cms/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/var/www/cms/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
```

Connection to DB is ok, tried with clean DB and sql dump from local dev machine. Locally on MacOS it starts ok, but when i'm deploying it on CentOS vps, i'm getting DB error.

**Comment by lauriejim** [comment]
Hello @heihachi88 !
When you create your application it set your database connection settings in `./config/environments/development/database.json` 
After that when you start your application without `NODE_ENV` - it start with **development** environment.

Here you start your application with `NODE_ENV=production` so it use `./coinfig/environement/production/database.json` config. So make sure config that are set in this file are correct.

**Comment by heihachi88** [comment]
Hello, thanks, but that obvious, i already mentioned that i'm using `NODE_ENV=production npm run start`, so i'm using production settings of database.json. There's another issue i think.

**Comment by lauriejim** [comment]
And are this settings correct?
Your database look to be on the same server as your Strapi application?
Make sure your database is well configured too.

**Comment by heihachi88** [comment]
@lauriejim yes, they are, database is on the same host, DB is working, i'm using it with different projects.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
