### ISSUE TITLE
The model of users cant be found

### ISSUE THREAD

**Issue by dakshrathod40** [strapi/strapi#3515]
**Describe the bug**
I am running an exsiting strapi project building it on docker
I am not able to get the Users table details in strapi admin showing error
**The model of users cant be found**
But i am able to post and get data from users table?? that is unsual!!

**Steps to reproduce the behavior**
1. Go to strapi admin panel
2. Click on Users
3. Debug Network you will see count api error

**Expected behavior**
It should show data of Users.

**Screenshots**
![Screenshot (10)](https://user-images.githubusercontent.com/48468251/59993968-ce687800-966f-11e9-96dd-80601ea9dac4.png)
![Screenshot (11)](https://user-images.githubusercontent.com/48468251/59993970-cf010e80-966f-11e9-85e9-959e27f75b4e.png)

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: beta-6
- Database: mongodb
- Operating system: linux, docker

**Comment by lauriejim** [comment]
If you are working with a fresh new app, did you have this issue. Or it came after a customization, or a content type creation?

**Comment by dakshrathod40** [comment]
In both scenario getting the same issue

**Comment by lauriejim** [comment]
Does it work without Docker ?
