### ISSUE TITLE
Editing admin password sets as plaintext in DB

### ISSUE THREAD

**Issue by fredrivett** [strapi/strapi#3518]
**Describe the bug**
When I create a new admin, I set the password in plaintext and it gets encrypted with the hash and stored in the DB. But if I then go and edit that newly created admin, and set a new password, that password is now stored in the database as plaintext.

*Note: this issue occurred using a postgres DB from Heroku*.

**Steps to reproduce the behavior**
1. Go to [https://localhost:1337/admin/plugins/content-manager/administrator?source=admin](https://localhost:1337/admin/plugins/content-manager/administrator?source=admin)
2. Click on `Add new administrator`
3. Fill in the fields as normal and click `Save`
4. View the `strapi_administrator` table in the postgres DB (you should see the new admin created and a hashed password)
5. Now click the pencil icon to edit the admin you just created. Update the password and click `Save`
6. View the `strapi_administrator` table in the postgres DB (you should see the admin password now set as plaintext in the DB, and now you cannot log back in using the new password set)

**Expected behavior**
The admin password to be encrypted when being saved after editing, and being able to log in with the newly set password.

**Screenshots**
![1__bash](https://user-images.githubusercontent.com/1713859/60029522-3aaba180-9699-11e9-87e8-f4bd5a0a33b6.png)

*Note: I only set this password to test it out, I normally set much better passwords* 😅 

**System**
- Node.js version: `v10.16.0`
- NPM version: `6.9.0`
- Strapi version: `3.0.0-beta.6`
- Database: `postgres`
- Operating system: `macOS Mojave 10.14.5`

**Comment by derrickmehaffy** [comment]
> Note: I only set this password to test it out, I normally set much better passwords

:rofl: 

I'll test this out to see if I can reproduce it, if so will be a critical issue.

**Comment by abdonrd** [comment]
Oops! Same on MongoDB!

**Comment by EskoRikkonen-efi** [comment]
@alexandrebodin I'm still having this issue with 3.0.0-beta.8. 

Tested with empty database by changing the password of both the 1st administrator created when accessing /admin the first time and a 2nd administrator created in /admin/plugins/content-manager/administrator: Both admins get a hashed password initially, but after editing and changing the password they are saved to DB in clear text.

**Comment by alexandrebodin** [comment]
Hi,

Check that your lock file has been updated with the right versions. You are most probably still in beta7

**Comment by EskoRikkonen-efi** [comment]
Meh, right you are: Had the old versions there. It works now. Thank you.
