### ISSUE TITLE
TypeError: entity.toLowerCase is not a function in strapi.query

### ISSUE THREAD

**Issue by suhamera** [strapi/strapi#3521]
i’ve just move to beta 7 and now i have to rewrite some of my custom cron functions
before i have: strapi.services.post.fetch({status:“current”}) .then(posts => {});
how i need to rewrite same query in beta with Strapi Core?
i tried this: strapi.query(Post).count({status:“current”}), but got

> UnhandledPromiseRejectionWarning: TypeError: entity.toLowerCase is not a function

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
