### ISSUE TITLE
How to actually use email sending?

### ISSUE THREAD

**Issue by heihachi88** [strapi/strapi#3522]
Strapi 3.0.0-beta6, can't figure out on how to use email. I saw a route `/email`, but where i can add payload, like, where to send it, message body or even attach files with an email? Documentation is very poor on this topic.

**Comment by lauriejim** [comment]
Hello! The thing I suggest you is to use the email service like here https://strapi.io/documentation/3.0.0-beta.x/guides/email.html#usage

And for the `POST /email` route, the function argument will be the body of your request.
See here https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-email/controllers/Email.js#L31

**Comment by pcrossnz** [comment]
Hi there. Did you have any luck? I'm also having a bit of trouble with the email!

**Comment by heavenkiller2018** [comment]
yes. i have the same problbem ,i can't send email locally!

**Comment by DekiGk** [comment]
Has anyone made `/email` API endpoint work?

I am getting this error:
```
[2020-03-15T01:56:11.923Z] error undefined

  AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at Function.boomify (C:\xxx\xxxxxxxxx\node_modules\boom\lib\index.js:107:14)     
      at C:\xxx\xxxxxxxxx\node_modules\strapi\lib\middlewares\boom\index.js:80:22      
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Using `localhost:1337/email` and providing `to`, `from`, `replyTo`, `subject`, `text` and `html` fields

**Comment by ivan-a-souza** [comment]
Try this, with Sendgrid provider:

{
  to: {
     email: "email@to"
  }
}

The SendGrid API is slightly different, and error handling is still not correct.

**Comment by klipitkas** [comment]
Documentation is still poor in this section, I have used the npm package:

```
yarn add strapi-provider-email-sendgrid
```

I also did create a file inside:

```
config/plugins.js
```

with the following contents:

```
module.exports = ({ env }) => ({
  email: {
    provider: 'sendgrid',
    providerOptions: {
      apiKey: env('SENDGRID_API_KEY'),
    },
    settings: {
      defaultFrom: 'info@example.com',
      defaultReplyTo: 'info@example.com',
    },
  },
});
```

I can then send email using cURL:

```bash
curl -X POST 'http://localhost:1337/email' \
-H 'Content-type: application/json' \
-d '{"to":"test@example.com","from":"test@example.com","subject":"test","html":"test","text":"test"}'
```

I can also try to check the API with an `OPTIONS` request:
```
curl -X OPTIONS 'http://localhost:1337/email' -I
HTTP/1.1 200 OK
Vary: Origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: SAMEORIGIN
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Allow: POST, HEAD, GET
X-Powered-By: Strapi <strapi.io>
X-Response-Time: 1ms
Date: Fri, 28 Aug 2020 18:03:51 GMT
Connection: keep-alive
```

But when I try to send email using my frontend Vue application, it seems that there is some weird cors issue:
```
HTTP/1.1 405 Method Not Allowed
Vary: Origin
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Frame-Options: SAMEORIGIN
Allow: HEAD, GET
X-Powered-By: Strapi <strapi.io>
X-Response-Time: 3ms
Content-Type: text/plain; charset=utf-8
Content-Length: 18
Date: Fri, 28 Aug 2020 17:57:14 GMT
Connection: keep-alive
```

**Comment by derrickmehaffy** [comment]
@klipitkas It would appear your Vue frontend is not sending the body payload as `application/json` it's sending it as `text/plain`

**Comment by klipitkas** [comment]
> @klipitkas It would appear your Vue frontend is not sending the body payload as `application/json` it's sending it as `text/plain`

Hi @derrickmehaffy and thanks for your reply. To clarify the headers shown above are the response headers.

I have tried setting the request headers using the code below:
```
import fetch from 'isomorphic-unfetch'

fetch(`${process.env.API_URL}/emails`, {
          method: 'POST',
          headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            message: this.message,
            name: this.name,
            email: this.email
          })
        })
...
```

But this did not work either. It appears as if the server only accepts `HEAD` and `GET` requests:
```
Allow: HEAD, GET
```

I did also provide proper permissions to any public user as shown below:
![Screenshot from 2020-08-29 00-38-28](https://user-images.githubusercontent.com/3259834/91617196-2dbaca00-e990-11ea-9d76-4b2260a4119d.jpg)

I am now trying to create a custom API and controller in order to achieve what I want.

**Comment by derrickmehaffy** [comment]
Can you open up a new discussion so we can work through your issue in a clean environment :)

**Comment by klipitkas** [comment]
> Can you open up a new discussion so we can work through your issue in a clean environment :)

This might be a non-issue, I just realised that in the URL in my frontend application I was using:
```
http://localhost:1337/emails
```

Instead of:
```
http://localhost:1337/email
```

which is what I was using on my `cURL` call.
