### ISSUE TITLE
Permissions not restored after mongo dump and restore

### ISSUE THREAD

**Issue by AntoninBeaufort** [strapi/strapi#3523]
**Describe the bug**
When I tried to dump my all Strapi database to restore it on new database/Strapi all data was imported, even permissions but in admin panels the permissions are not set.

**Steps to reproduce the behavior**
1. Mongo dump a Strapi database after set permissions on public
2. Mongo restore on another database
3. Create new strapi on this new database
4. Look permissions on new Strapi, they are empty, but in database the entries are in the right document

**Expected behavior**
Permissions restaured like on the Strapi backup.

**Code snippets**

- mongodump
- mongorestore

**System**
- Node.js version: 10.16
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.3 on backup and 3.0.0-beta.5 on new
- Database: MongoDB
- Operating system: Ubuntu on backup and Alpine on new

Thank you in advance for your help !

**Comment by lauriejim** [comment]
Hello!
So all your content types data are correct? But only permissions are note correct?

Can you share the **exact** command you use to export / import please.

**Comment by lauriejim** [comment]
Hello!
So all your content types data are correct? But only permissions are note correct?

Can you share the **exact** command you use to export / import please.

**Comment by pbonnefoi** [comment]
Hello I have the same problem. The permissions are correctly imported but the objectid is different and so the relation with the strapi_administrator is broken.

**Comment by ralexrdz** [comment]
I have the same problem. Dumping data from the server and trying to restore it locally with the same code, and same docker image, doesn't show the Nav Var Links: (Content Types / Plugins) 

I get this: 

![](https://i.imgur.com/lww8qwk.png)

instead of this:

![](https://i.imgur.com/Updt6bq.png)

**Comment by ralexrdz** [comment]
as explained [here](https://github.com/strapi/strapi/issues/9917#issuecomment-813976266) Not restoring strapi_administrator collection solved the problem
