### ISSUE TITLE
Getting strapi/application instance in test files using jest

### ISSUE THREAD

**Issue by amiiy** [strapi/strapi#3524]
Hi. I want to write some End-to-End tests for my strapi project using jest. I just don't know how to get strapi application instance in test files, should I use some helper module for getting it? or change the npm test command?
here is my test:
```
  describe("### /locations route test", () => {
    beforeEach(async () => {
      const data = await request.post({
        url: `${API_URL}/auth/local`,
        form: {
          identifier: "test@test.com",
          password: "test1234"
        }
      });
      token = JSON.parse(data).jwt;
    });

    it("GET /location/  should return the array of locations for this user", async () => {
      const res = await request.get({
        url: `${API_URL}/locations`,
        headers: { Authorization: `Bearer ${token}` }
      });

      const data = JSON.parse(res);

        expect(data).toMatchObject(locations);
    });
``` 

my mean, instead of executing a request to some fix endpoint, I run request with application instance like `request(app).post({...})`
and `package.json` command: 
```
    "test": "jest --config=jest.config.js --runInBand --coverage"

```

**Comment by lauriejim** [comment]
Hello! Can you precise what you mean by `strapi application instance` please.

**Comment by samohovets** [comment]
Hello, @lauriejim!

I guess he meant the global `strapi` object in a test suite. I faced the same problem, I just want to test some specific logic with Jest and `supertest`, but when I try to start server programmatically like so:
```js
const Strapi = require('strapi');
Strapi().start()
```
It throws an error `TypeError: require(...) is not a function`. 

You can reproduce it easily:
1. Create a Jest test somewhere in your Strapi app directory
2. Try to start Strapi programmatically somewhere in the test

**Comment by JaguarKnight** [comment]
I believe the problem is that you aren't getting the strapi global object. That is why there are no defined methods on. 

What is the appropriate way to get the strapi global.

**Comment by samohovets** [comment]
Figured it out recently. So to e2e test your endpoints with Jest you should create test environment   in your Strapi app, because jest uses `NODE_ENV=test` in the test suites. Create `config/environments/test` folder and copy contents from `config/environments/production` to that `test` folder. 

I wrote some basic setup function that starts strapi and allows to publicly access endpoints you want (just pass array of controller names). 

Here's the gist: https://gist.github.com/samohovets/d83a756a1d22ffaf2fb4a912be9e85d7

So the basic test with `supertest` may look like this:
```js
// function from gist file
const { setupStrapi } = require('../../helpers/strapi');

// We're setting timeout because sometimes bootstrap can take 5-7 seconds (big apps)
jest.setTimeout(10000);

beforeAll(async () => {
  await setupStrapi(['article']);
});

afterEach(async () => {
  await cleanup(); // pseudocode, not figured out how to cleanup it properly
});

it('should respond with 200 on /articles', async (done) => {
    const response = await request(strapi.server)
      .get('/articles')
      .expect('Content-Type', /json/)
      .expect(200);

    done();
  });
```

**Comment by lauriejim** [comment]
Hello @samohovets !
Thank you so so much for sharing this snippet code. I really appreciate that!

Could you please contribute to the documentation and add a **Guide** on **How to create 2to2 test**
This will help me a lot to reference your code.

There are already other guides to help you with the format - https://strapi.io/documentation/3.0.0-beta.x/guides/slug.html

**Comment by uyouthe** [comment]
@samohovets you want your pc's to be iMac pro and your websites to be HTML5?

**Comment by qunabu** [comment]
@samohovets I was inspired by you snippet and tested it with my project. 
I think the problem is you're calling `strapi.start` which might be too much for testing purpose - you can just call `strapi.load` and add routes manually. This will not generate any issues with process.exit from `afterAll` in your snipper and doesn't require any cleanup code as all. 

```js
const Strapi = require("strapi");

let instance;

async function setupStrapi(entryNamesToOpen) {
  if (!instance) {
    await Strapi().load();
    instance = strapi; // strapi is global now
    instance.app
      .use(instance.router.routes()) // this code in copied from app/node_modules/strapi/lib/Strapi.js
      .use(instance.router.allowedMethods());
  }

  return instance;
```

I've tried to explain this on my blog https://medium.com/@qunabu/strapi-jest-testing-with-gitlab-ci-82ffe4c5715a

**Comment by samohovets** [comment]
@qunabu looks like a nice solution, good job! It’s true that it’s too much to start Strapi instance for each test suite. But this approach makes setup script more resilient to change, as it don’t uses any strapi implementation stuff (manually applying middleware etc). 

 I like your way to test strapi apps, article is cool too. It’s a way efficient than my setup script and approach 👌

**Comment by Antoine-lb** [comment]
Hello, followed the doc step by step but I'm getting:
```
process.exit called with "1"

      at Strapi.stop (node_modules/strapi/lib/Strapi.js:240:13)
      at Strapi.stopWithError (node_modules/strapi/lib/Strapi.js:224:17)
      at node_modules/strapi-connector-bookshelf/lib/mount-models.js:625:14
```

it seems to come from the `Strapi().load();` directly. @qunabu do you know what can cause this function to fail?

**Comment by qunabu** [comment]
What version of strapi you're using ?

**Comment by Antoine-lb** [comment]
Got the problem, in the docs it sais ./config/**env**/test/database.json, but in your article ./config/**environments**/test/database.json

Now it works (great article @qunabu) :)

Don't really know if it was my error or something should be updated in the doc

**Comment by qunabu** [comment]
Actually those paths are different regarding of strapi versions - That's why I've asked. 

Since stable 3 version valid path is `./config/env/*` you must be using `beta` or even previous one

**Comment by Antoine-lb** [comment]
3.0.2 (node v12.18.0)

**Comment by qunabu** [comment]
https://strapi.io/documentation/v3.x/concepts/configurations.html#environments 

> Strapi configurations can also be created per environment in ./config/env/{env}/{filename}. These configurations will be merged into the base configurations defined in the ./config folder. The environment is based on the NODE_ENV environment variable (defaults to development).

> When starting Strapi with NODE_ENV=production it will load the configuration from ./config/* and ./config/env/production/*. Everything defined in the production config will override the default config.

`./config/env/*` is the latest valid one

**Comment by Antoine-lb** [comment]
Weird because now I'm in `3.0.5 (node v12.18.0)` but I still need to call it `environment` and not `env`.

I `yarn remove strapi strapi-*` and re-installed them, removed `node_modules`, `.tmp` and `.cache`. I don't know if is the best way of updating but it seemed to work well. I just didn't find a "good" way of updating to latest in the internet

**Comment by qunabu** [comment]
If you're interested I've created an [example project](https://github.com/qunabu/strapi-unit-test-example) with [CI/CD](https://app.circleci.com/pipelines/github/qunabu/strapi-unit-test-example) as well

**Comment by spenweb** [comment]
If you are using `strapi@3.1.1`, the current version of the unit-test guide from the official documentation is outdated and if you follow it, you will have a horrible time. While we wait for the official docs to be updated, I recommend following this PR #7115 7115 by @TracyNgot. I followed TracyNgot's updated and I got unit testing working.
