### ISSUE TITLE
Listening to a specific IP

### ISSUE THREAD

**Issue by JohnDiorroer** [strapi/strapi#3525]
**Describe the bug**
While trying to install strapi on a production server I encountered a problem. The HTTP server does not listen on the IP configured in my files: config/environments/<>/server.json.

To make it work I had to replace:
```
this.server.listen (this.config.port, async err => {
```
by
```
this.server.listen (this.config.port, this.config.host, async err => {
```
in the [Strapi.js](https://github.com/strapi/strapi/blob/6159fd0d569af38f5dbdea73376e8538878d851b/packages/strapi/lib/Strapi.js#L132) file.

Is there another way for the application to launch by listening to a specific IP?

For your work, thank you.

**Comment by lauriejim** [comment]
Hello!
I suppose you host your server in a AWS or Heroku or Digital Ocean.
You have to keep your `localhost` for the `host` value.
