### ISSUE TITLE
Facebook provider broken with Strapi beta.7

### ISSUE THREAD

**Issue by Lith** [strapi/strapi#3526]
**Describe the bug**
I've updated my Strapi App from beta.6 to beta.7 (in order to fix some bug) but this new version has broken the Facebook connection provider (and maybe other provider...).

**Steps to reproduce the behavior**
1. Update to Strapi Beta.7
2. Try to connect with Facebook
3. An error 500 occurs

```
error TypeError: Middleware stack must be an array!
    at compose (node_modules/koa-compose/index.js:20:41)
    at connect (extensions/users-permissions/controllers/Auth.js:269:12)
```
_I've overload the Auth.js but with the "original" version, the bug still happen._

**Expected behavior**
I can logged with the Facebook Provider
I can registered with the Facebook Provider

**System**
- Node.js version: v10.14.2
- NPM version: 6.9.0
- Strapi version:  3.0.0-beta.7
- Database: Bookshelf mysql
- Operating system: Mac OS X, Debian

Everything's working with **3.0.0-beta.6** (I've rollbacked twice to be sure)

**Comment by Lith** [comment]
Maybe this could help, but I think the bug is linked to latest Koa update : 
- https://github.com/strapi/strapi/pull/3466 @alexandrebodin ?

**Comment by Gorgonello** [comment]
I found the same issue with **3.0.0-alpha.26.2**. @Lith did you figure it out?

**Comment by JunhoYi** [comment]
I have the same problem. The difference is that I use Ubuntu.

**Comment by plduhoux** [comment]
I have the exact same issue for multiple providers since beta 7 too : The error appears for Facebook, Google, and Discord (I didn't implement other ones)

**Comment by plduhoux** [comment]
I fixed it locally by overriding `Auth.js` (copy and paste it from `strapi-plugin-users-permissions/controllers` to `extensions/users-permissions/controllers` folder) and by replacing lines  266 to 269 : 
```
    const Grant = require('grant-koa');
    const grant = new Grant(grantConfig);

    return compose(grant.middleware)(ctx, next);
```
by :
```
    const grant = require('grant-koa');
    const g = grant(grantConfig);
    
    return g(ctx, next);
```

It's not using `koa-compose` anymore and I am not sure of the side effects it may have in strapi... as I don't understand the use koa-compose here, I am not submitting a PR for that...

**Comment by kenkz447** [comment]
Same problem when update to **3.0.0-alpha.26.2**, did someone use beta version meet this problem?

**Comment by Lith** [comment]
> I found the same issue with **3.0.0-alpha.26.2**. @Lith did you figure it out?

That's depends of versions of libraries defined in your``package-lock.json``.
By example, when I've updated to beta.7, some new packages have been added or updated :
```
 ... // # added # 
    "@hapi/address": {
      "version": "2.0.0", ...
    },
    "@hapi/hoek": {
      "version": "6.2.4", ...
    },
    "@hapi/joi": {
      "version": "15.0.0", ...
      "requires": {
        "@hapi/address": "2.x.x",
        "@hapi/hoek": "6.x.x",
        "@hapi/topo": "3.x.x"
      }
    },
    "@hapi/topo": {
      "version": "3.1.0", ...
      "requires": {
        "@hapi/hoek": "6.x.x"
      }
    },
... // # updated # 
    "apollo-server-koa": {
      "version": "2.6.3", ...
    },
    "grant": {
      "version": "4.6.0", ...
     },
     "grant-koa": {
      "version": "4.6.0", ...
      },
```

And other, removed : 
```
"items": {
      "version": "2.1.2",...
},...
"joi": {
      "version": "10.2.2", ...
}
```

Maybe the PR of @plduhoux will be accepted and fix definitively this bug ?
I think it's the new migration of ``joi`` to ``@hapi/joi``. and the update of ``grant-koa`` are produced the bug.

**Comment by derrickmehaffy** [comment]
@Lith @kenkz447 @plduhoux 

Can you guys manually override your users-permissions plugins with the changes from this PR and test please?

https://github.com/strapi/strapi/pull/3541/files

If you are on beta you will use the `extensions` folder. You won't need to keep this after beta.9 is released but it is a temporary fix

**Comment by Lith** [comment]
@derrickmehaffy : this fix looks good 👍 I've update to beta.8 and overwrite the file `Auth.js`, I'm able to login with my Facebook provider now :) Thanks !

**Comment by muhaimincs** [comment]
i just experienced error with v3.0.0-beta.13

```bash
error TypeError: undefined is not a function at callback (/node_modules/strapi-plugin-users-permissions/controllers/Auth.js:142:23)
```
