### ISSUE TITLE
Node version error when creating a new project, and how to fix it

### ISSUE THREAD

**Issue by tolgasumer** [strapi/strapi#3528]
**Description**

Strapi fails to install the dependencies using yarn if a version newer than v10.0.0 of node.js is used in the system. This is caused by the `"node": "^10.0.0"` statement being obsolete, `"node": ">= 10.0.0"` should be used on package.json.

**Error**

`>strapi new my-project
🚀 Creating your Strapi application.

? Choose your installation type Quickstart (recommended)

✅ Connected to the database
🏗  Application generation:
✔ Copying files ...
✖ Installing dependencies ...
Error: Command failed: yarnpkg install --production --no-optional
error my-project@0.1.0: The engine "node" is incompatible with this module. Expected version "^10.0.0". Got "12.4.0"
error Found incompatible module.

yarn install v1.17.0
info No lockfile found.
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at makeError (/usr/local/lib/node_modules/strapi/node_modules/execa/index.js:174:9)
    at /usr/local/lib/node_modules/strapi/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  code: 1,
  stdout: 'yarn install v1.17.0\ninfo No lockfile found.\n[1/5] ' +
    'Validating package.json...\ninfo Visit ' +
    'https://yarnpkg.com/en/docs/cli/install for ' +
    'documentation about this command.\n',
  stderr: 'error my-project@0.1.0: The engine "node" is ' +
    'incompatible with this module. Expected version ' +
    '"^10.0.0". Got "12.4.0"\nerror Found incompatible ' +
    'module.\n',
  failed: true,
  signal: null,
  cmd: 'yarnpkg install --production --no-optional',
  timedOut: false,
  killed: false
}`

**Steps to reproduce the behavior**
1. Use a newer version than v10.0.0 of node.js
2. Create a new project `strapi new cms --quickstart`

**System**
- Node.js version: 12.4.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.7
- Database: Any
- Operating system: OSX

**Fix**
Create the project and ignore the error, then manually edit the line `"node": "^10.0.0"` to `"node": ">= 10.0.0"` on package.json in the created project folder.

The new engines tab on the package.json file should look like this:

`"engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  }`

**Comment by derrickmehaffy** [comment]
Only node 10 is supported right now. Node 12 support is being worked on but considering it doesn't go into LTS until October it isn't a huge priority.

I'm marking this as closed since it is a duplicate.

**Comment by syedsimanta03** [comment]
Strapi is great, but no stable version with latest node support. windows users facing a lot of issues. thanks
