### ISSUE TITLE
Content type builder not deleting removed content types in PostgreSQL

### ISSUE THREAD

**Issue by heihachi88** [strapi/strapi#3529]
Strapi 3.0.0-beta 6 / PostgreSQL 10.8

When i remove content type, for example "Page", the table still remains in a database, which causes lots of issues, like `null is already taken` when trying to create a new content.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1114

Also @heihachi88 please ensure you use the bug report templates, issues created without using a template are closed.
