### ISSUE TITLE
graphql cannot search based on selected user(s)

### ISSUE THREAD

**Issue by kktam** [strapi/strapi#3530]
**Describe the bug**
Graphql cannot search data based on a given user(s). return "Forbidden" error.

The demo server used is based on Deliveroo tutorial [https://blog.strapi.io/strapi-next-setup/](https://blog.strapi.io/strapi-next-setup/)

**Steps to reproduce the behavior**
1. Go to [http://localhost:1337/graphql](http://localhost:1337/graphql)
2. Type the following graphql query
3. Click "Play"

The query is:

```
query {
user ( id: "1") {
      id
      username
      orders {
        id
        address
        city
        created_at
        dishes
      }
    }
}
```

returns

```
{
  "errors": [
    {
      "message": "Forbidden",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "user"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "data": null,
          "isBoom": true,
          "isServer": false,
          "output": {
            "statusCode": 403,
            "payload": {
              "statusCode": 403,
              "error": "Forbidden",
              "message": "Forbidden"
            },
            "headers": {}
          },
          "message": "Forbidden",
          "stacktrace": [
            "Error: Forbidden",
            "    at handleErrors (C:\\Users\\n\\code\\strapi\\beta\\auctionbackend\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:116:54)",
            "    at module.exports (C:\\Users\\n\\code\\strapi\\beta\\auctionbackend\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:100:12)"
          ]
        }
      }
    }
  ],
  "data": {
    "user": null
  }
}
```

**Expected behavior**
Strapi need to open up a way for developers to construct queries that can find data based on a single user , or a group of users.

Currently the API server locked user, and cannot be selected to allow "find" or "findone" even in Authenticated mode.

If set to Authenticated Mode. Then graphql editor need to allow developer to fake a "login" session.

**Screenshots**

**Code snippets**
See above.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0_Beta.5
- Database: SQLite
- Operating system: Windows 10 Professional

**Additional context**
It is very difficult to build complex product logic if the graphql cannot search based on user, then the final product will not able to administrative analytics (such as find all the products used by a user), which is an important feature to have in any CMS product.

**Comment by Lith** [comment]
I think you have forgot to open rights in ``users-permissions-users``, check if `findone` is enabled for public role (but disable it after testing... it's not safe to keep it open).

1. Go to :  http://localhost:1337/admin/plugins/users-permissions/roles/edit/3
2. Open : USERS-PERMISSIONS
3. Check `findone` autorisation
4. Save

Also, you can add your authorization token Bearer in graphql.

**Comment by kktam** [comment]
@Lith  what are the steps in strapi to 1) find the JWT token created by Strapi in Admin server, and 2) apply the token Bearer in testing when using the graphql playground? [http://localhost:1337/graphql](http://localhost:1337/graphql)

**Comment by Lith** [comment]
@kktam 
1/ you can find the token in admin documentation : 
- http://localhost:1337/admin/plugins/documentation

2/ Apply the token into graphql like that 
![image](https://user-images.githubusercontent.com/605495/60371402-73c97600-99f9-11e9-8dea-33d34460bed9.png)

```
{
  "Authorization":"Bearer eyJhbGciOxJIUzI1NiIsInR5xCI6IkpXVCJ9.eyJpZCI6MSwxaXNBZG1pbiI6dHJ1ZSwxaWF0IjoxNTYxNjcyNDc0LCJleHAxOjE1NjQyNjQ0NzR9.gY9VzxP3nGTf8o9quuhbhmyzhg2hYgg0QxiZ5k2-MbU"
}
```
Replace this token after the word ``Bearer ``.

**Comment by kktam** [comment]
From my Documentation page, [http://localhost:1337/admin/plugins/documentation](http://localhost:1337/admin/plugins/documentation), the page is blank.  My server is built with version 3.0.0_beta.5. Is this correct?

![Admin Doc](https://user-images.githubusercontent.com/2776485/60373940-e8c78c00-99b6-11e9-9c67-5ce64fa102d8.PNG)

**Comment by Lith** [comment]
Yes, but I think you need to install the plugin from the MarketPlace.
 
Then, you will see new entry "Documentation" in "Plugins" section :
![image](https://user-images.githubusercontent.com/605495/60382027-56c68e80-9a5d-11e9-9b2a-d10eac920d8f.png)

**Comment by kktam** [comment]
Thanks. the problem is solved now. But I also have to upgrade to 3.0.0_beta.7 as well. Now the Swagger API is working [http://localhost:1337/documentation/v1.0.0](http://localhost:1337/documentation/v1.0.0) as well as authenticated Graphql playground call.
