### ISSUE TITLE
Content manager: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by friendofdog** [strapi/strapi#3531]
**Describe the bug**
When opening certain components in Content Manager, get the following error:
```
TypeError: Cannot read property 'split' of undefined
```
Occurs after upgrading from alpha.26.1 to beta.6. See **Additional context** for details.

**Steps to reproduce the behavior**
1. Upgrade to beta.6 from alpha.26.1
2. Click on Content Manager and attempt to edit (certain) component

**Expected behavior**
Content Manager opens as normal

**Screenshots**
<img width="446" alt="Screen Shot 2019-06-26 at 17 18 18" src="https://user-images.githubusercontent.com/8337121/60163394-7891fc80-9836-11e9-883c-f28934c25158.png">

**Code snippets**
n/a. The only code involved was that provided in the alpha -> beta migration guide.

**System**
- Node.js version: 10.15.0
- NPM version: 6.4.1
- Strapi version: beta.6
- Database: MongoDB
- Operating system: Mac OS Mojave 10.14.5

**Additional context**
This error does not occur in all components, just a few problematic ones. There is no discernible pattern to the affected components.

The cause of this problem appears to be certain (but not all) media fields. If I delete said media fields from affected components, the error does not occur and Content Manager functions normally. But if I reinstate the same field (with the same name), the error comes back.

**Comment by soupette** [comment]
This issue is coming from your `core_store` schema, it's a known bug that is going to be fixed soon. In order to fix it delete your `plugin_content_manager_schema` document in your db and it should be working fine.

**Comment by friendofdog** [comment]
I remember this bug from before! In alpha <=26 it would result in the loader spinning endlessly when creating a new entry.

Thanks, I remember what to do here.

**Comment by Pluto8195** [comment]
Im getting the same issue, when I go to a specific content-type except I cant find `plugin_content_manager_schema` in `core_store`

**Comment by derrickmehaffy** [comment]
@Pluto8195 as of beta.16 that was fixed and that key was split into one for each type, you shouldn't need to delete them anymore

**Comment by hristov296** [comment]
I have the same problem as @Pluto8195 
When opening any content type
![Screenshot from 2019-12-06 14-31-09](https://user-images.githubusercontent.com/18082688/70323311-2289a200-1835-11ea-81ca-6605ea88132f.png)

Strapi v3.0.0-beta.17.8
I dont have `plugin_content_manager_schema` in `core_store`

**Comment by derrickmehaffy** [comment]
@hristov296 is your project public somewhere I can look at it? (Github link)

**Comment by hristov296** [comment]
no, it is local

**Comment by derrickmehaffy** [comment]
Can you push it into a repo (private or public doesn't matter to me)

**Comment by hristov296** [comment]
https://github.com/hristov296/strapi-issue

**Comment by roelbeerens** [comment]
I just updated from 18.4 to 18.6 and this message appeared on one of my content types. Cleared the configuration in the core_store but that didn't fix it

**Comment by ovidiuficiu** [comment]
Any news regarding this issue? I'm getting it as well. Are there any workarounds existing?

**Comment by roelbeerens** [comment]
> Any news regarding this issue? I'm getting it as well. Are there any workarounds existing?

From my experience, when this pops up, usually when removing the specific settings in the core_store and do a full rebuild (remove cache, build and node_modules) and do a clean install the issue should be resolved

**Comment by ovidiuficiu** [comment]
@roelbeerens just tried that and it works like a charm. Thanks for your help.

**Comment by Alexpikey** [comment]
@roelbeerens Thanks a bunch! It works now 😸
