### ISSUE TITLE
Content type field names underscore bug with filters

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#3534]
**Describe the bug**
When creating a field name in the following pattern: `Title_en`, `Title_gr` it breaks content filtering in admin panel.

**Steps to reproduce the behavior**
1. Create new content type (let's call it `page`)
2. Add new field, for example a string type with the following name - `Title_en`
3. Go to: `/admin/plugins/content-manager/page?source=content-manager`
4. Open filters panel, choose `Title_en` is `123`, press enter
5. You will see the following filter text:

![image](https://user-images.githubusercontent.com/5739191/60212219-81102480-9882-11e9-97ae-f47073c6b4e7.png)

So it cannot search because of this.

**Expected behavior**
Underscores shouldn't cause an issue with content filtering, or at least describe this behavior in documentation 

**System**
- Node.js version: 10
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta6
- Database: PostgreSQL
- Operating system: MacOS 10.14.5

**Comment by derrickmehaffy** [comment]
Can you please test with the latest beta? Technically I don't think models/fields support symbols yet (work is being done there)

**Comment by webcoderkz** [comment]
Beta 8, same behavior.

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
If you are able to investigate in the code base to be able to find why this issue happen, we will appreciate.

**Comment by henrych4** [comment]
Just want to confirm: Does the filtering function fail? I tried to reproduce the issue and there was something wrong with filter text as you described. However, it is still able to filter the record.

**Comment by soupette** [comment]
This has been fixed in the latest beta.
I'm closing the issue

<img width="1180" alt="Screenshot 2019-10-10 at 09 06 03" src="https://user-images.githubusercontent.com/13311463/66546394-37033400-eb3d-11e9-9175-c57ef1023069.png">

**Comment by scottydev** [comment]
Holy crap @kwadwo underscores have finally been supported in Strapi? I almost can't believe it 😃

**Comment by webcoderkz** [comment]
@soupette good job, after 5 months, but better late, than never 😂
