### ISSUE TITLE
Missing Content-Type header on multipart form causes ugly error

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3535]
**Describe the bug**
When doing a POST to /upload to add an upload, it seems the Content-Type is REQUIRED. I was getting an error because of that missing. The fix was to add  `Content-Type: application/octet-stream`, but would be nice if strapi can handle that and give some clear error.

**Steps to reproduce the behavior**
1. Build a multipart form manually with some binary file, without the `Content-Type` part header
2. POST to /upload

**Expected behavior**
Would be nice if strapi can handle `stream.type == null`  in
https://github.com/strapi/strapi/blob/6159fd0d569af38f5dbdea73376e8538878d851b/packages/strapi-plugin-upload/services/Upload.js#L54

**System**
- Node.js version:10
- NPM version: 6.9
- Strapi version: 3.0.0-beta.7
- Database: mongo
- Operating system: macOS

**Comment by lauriejim** [comment]
Hello! Can you send me your form please to be able to reproduce your issue please.
Because by creating a simple HTML / JS form it work.
I followed the first code example [here](https://strapi.io/documentation/3.0.0-beta.x/guides/upload.html#examples)

**Comment by jacargentina** [comment]
I'm calling strapi api through Powershell. The example is like that:

```
$FilePath = 'c:\temp\temp.txt';
$URL = 'http://your.url.here';

$fileBytes = [System.IO.File]::ReadAllBytes($FilePath);
$fileEnc = [System.Text.Encoding]::GetEncoding('UTF-8').GetString($fileBytes);
$boundary = [System.Guid]::NewGuid().ToString(); 
$LF = "`r`n";

$bodyLines = ( 
    "--$boundary",
    "Content-Disposition: form-data; name=`"file`"; filename=`"temp.txt`"$LF",
    $fileEnc,
    "--$boundary--$LF" 
) -join $LF

Invoke-RestMethod -Uri $URL -Method Post -ContentType "multipart/form-data; boundary=`"$boundary`"" -Body $bodyLines
```

Note this, below `Content-Disposition` via an HTML Form, there is a `Content-Type` header, which i was not adding. After adding that line like this:

`    "Content-Type: application/octet-stream$LF", `

all works just fine.
