### ISSUE TITLE
new project failed in installing dependencies 

### ISSUE THREAD

**Issue by bermet123456** [strapi/strapi#3536]
the new app has been connected to the database succesfully.
but it failed in installing dependencies

? Choose your installation type Custom (manual settings)
? Choose your main database: MongoDB
? Database name: server
? Host: cluster0-8nios.mongodb.net
? +srv connection: true
? Port (It will be ignored if you enable +srv): 27017
? Username: sydykova2108
? Password: **********
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: true

⏳ Testing database connection...
It might take a minute, please have a coffee ☕️

The app has been connected to the database successfully!
🏗  Application generation:
√ Copying files ...
× Installing dependencies ...
{ Error: Command failed: npm install --production --no-optional
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this

**Comment by derrickmehaffy** [comment]
@bermet123456 Please follow the bug report template.

Closing for now, after you have updated your issue with the proper template please reply back and this can be reopened.
