### ISSUE TITLE
GraphQL nested filter using variable not giving correct results

### ISSUE THREAD

**Issue by bareblends** [strapi/strapi#3537]
**Describe the bug**
GraphQL queries using a variable in a nested filter are giving do not apply the filter, where adding the string directly in the query gives the correct result

**Steps to reproduce the behavior**
1. Query a content types relationship with variable in a nested filter
2. Compare the results to the same query entering the string directly in the filter

**Expected behavior**
The results given should be the same

**Screenshots**
Correct result using string
![Screenshot_2019-06-27 Playground - http localhost 1337 graphql(1)](https://user-images.githubusercontent.com/47200551/60242145-5791e000-98f8-11e9-8652-98e064710fca.png)
Incorrect result using variable (post id:1 is returned although its PostCategories are empty
![Screenshot_2019-06-27 Playground - http localhost 1337 graphql](https://user-images.githubusercontent.com/47200551/60242146-582a7680-98f8-11e9-9d20-b800c37c1d33.png)

**System**
- Node.js version: 10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.7
- Database: MariaDB 10.1.40
- Operating system: Ubuntu

**Additional context**
Model settings.json for above example attached below
Postcategory.settings.json
```json
{
  "connection": "default",
  "collectionName": "postcategory",
  "info": {
    "name": "postcategory",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "posts": {
      "collection": "post",
      "dominant": true,
      "via": "postcategories"
    }
  }
}
```

Post.settings.json
```json
{
  "connection": "default",
  "collectionName": "post",
  "info": {
    "name": "post",
    "description": ""
  },
  "options": {
    "timestamps": [
      "created_at",
      "updated_at"
    ]
  },
  "attributes": {
    "slug": {
      "unique": true,
      "required": true,
      "type": "string"
    },
    "featuredImage": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": true
    },
    "content": {
      "type": "text"
    },
    "postcategories": {
      "collection": "postcategory",
      "via": "posts"
    },
       ......
  }
}`

**Comment by merijnponzo** [comment]
I think I have the same problem with normal queries..
I even downgraded to from beta.7 to strapi 3.0.0-beta.2

Strapi 3.0.0-beta.2 or 3.0.0-beta.7
DB: Postgres
Node v10.6.0
NPM 6.1.0
macOs Mojave


This query should return no results
![Schermafbeelding 2019-06-27 om 09 57 39](https://user-images.githubusercontent.com/23075300/60251221-6f517000-98c8-11e9-9596-ab7119346f47.png)

Without variable
![Schermafbeelding 2019-06-27 om 10 00 24](https://user-images.githubusercontent.com/23075300/60251305-9740d380-98c8-11e9-928b-797340d30d39.png)

**Comment by Lith** [comment]
This bug is related to graphql latest update (14.4.0).
Could you try to force the older version (14.3.1) in your `package-lock.json` and launch a new `strapi build` ?

**Before** 
```
  "graphql": {
      "version": "14.4.0",
      "resolved": "https://registry.npmjs.org/graphql/-/graphql-14.4.0.tgz",
      "integrity": "sha512-E55z1oK6e4cGxCqlSsRWytYDPcIUxky3XkbuQUf6TIjCmn6C7CuBJpmkMF1066q95yPAGOZVPTVT7jABKbRFSA==",
      "requires": {
        "iterall": "^1.2.2"
      }
    },
```

**After**
```
"graphql": {
      "version": "14.3.1",
      "resolved": "https://registry.npmjs.org/graphql/-/graphql-14.3.1.tgz",
      "integrity": "sha512-FZm7kAa3FqKdXy8YSSpAoTtyDFMIYSpCDOr+3EqlI1bxmtHu+Vv/I2vrSeT1sBOEnEniX3uo4wFhFdS/8XN6gA==",
      "requires": {
        "iterall": "^1.2.2"
      }
    },
```

With the version 14.4.0, variables are not take in consideration but with the older 14.3.1, everything looks good (on my side this tricks it's working).

**Comment by derrickmehaffy** [comment]
@Lith :thinking: this is odd as the specific graphQL version is defined here: https://github.com/strapi/strapi/blob/0112a9726a485bd28f4d65b18b4913057670b413/packages/strapi-plugin-graphql/package.json#L17

**Comment by Lith** [comment]
@derrickmehaffy Yes... but curiously ``graphql`` is updated to the latest version (submit yesterday) when you update or fresh install strapi. 
If you block the version of graphql in ``strapi/packages/strapi-plugin-graphql/package.json``  the latest version of graphql will not be taken ?

Like this without the ``^`` ?
``"graphql": "14.3.0"``

**Comment by derrickmehaffy** [comment]
Ahhh you know what I think you are right:

> The caret ^ is more relaxed. It matches the most recent minor version (the second number) for the specified major version (the first number).
> ^1.2.3 will match any 1.x.x release including 1.3.0, but will hold off on 2.0.0.

So it's grabbing a newer version. Although this does appear to be an upstream issue, I'll do a pull request to hard code the version for now and if someone wants to file a bug report in the GraphQL repo to see if they can address it.

**Comment by derrickmehaffy** [comment]
Same thing here if people want to test locally using @Lith 's fix to see if that helps and reply back (here or the PR) and we can see about getting it merged in beta.9 until a more solid fix is done upstream.

**Comment by bareblends** [comment]
This fixed the issue for me as well, thanks for sorting out a fix so quickly!

**Comment by merijnponzo** [comment]
Thanks for the fix!

![Schermafbeelding 2019-06-28 om 19 17 22](https://user-images.githubusercontent.com/23075300/60359466-6b614300-99d9-11e9-864c-7da1486493eb.png)
![Schermafbeelding 2019-06-28 om 19 17 12](https://user-images.githubusercontent.com/23075300/60359468-6b614300-99d9-11e9-9e32-f82e539413d9.png)

**Comment by alexandrebodin** [comment]
Hi, here is more context about why it isn't working and why it is intended:

The schema generated by Strapi gives the `where` attribute a Type `JSON` this type means that the `where` clause should be sent as a JSON string to the server if using variables.

You queries should look like this:

```graphql
query articles($where: JSON) {
  articles(where: $where) {
    id
  }
}
```
and variables:
```json
{
  "where": {
    "title": "sth"
  }
}
```

I will look into more details what changed to give more explanations.

**Comment by emily-wheatcroft** [comment]
I'm having trouble forcing my yarn.lock to use the older version as I can't get rid of the caret. 

`graphql@^14.3.0:
  version "14.4.2"
  resolved "https://registry.yarnpkg.com/graphql/-/graphql-14.4.2.tgz#553a7d546d524663eda49ed6df77577be3203ae3"
  integrity sha512-6uQadiRgnpnSS56hdZUSvFrVcQ6OF9y6wkxJfKquFtHlnl7+KSuWwSJsdwiK1vybm1HgcdbpGkCpvhvsVQ0UZQ==
  dependencies:
    iterall "^1.2.2"`

**Comment by emily-wheatcroft** [comment]
Has a proper fix been put in for this? I've been unable to apply the fix suggested here

**Comment by emily-wheatcroft** [comment]
Is there any update on this? The fixes above are currently not working for me

**Comment by alexandrebodin** [comment]
@emily-wheatcroft The explanation is the correct way to use the JSON type :)

If you have an issue It might be coming from something else. don't hesitate to open a new issue if necessary.

**Comment by IRCraziestTaxi** [comment]
![image](https://user-images.githubusercontent.com/18566088/64997679-1251ce80-d8a7-11e9-8db6-d2f8ee12885b.png)
I'm getting these kinds of errors when i try to pass variables into my GraphQL query. The [above explanation](https://github.com/strapi/strapi/issues/3537#issuecomment-507170401) does not appear to work for me.

**Comment by alexandrebodin** [comment]
@IRCraziestTaxi  Hi you are not making your query the right way. See graphql docs: https://graphql.org/learn/queries/#variables

**Comment by IRCraziestTaxi** [comment]
@alexandrebodin Thank you SO MUCH. I was so frustrated after spending hours digging through docs that weren't that helpful and whatever SO/Github posts I could find that I didn't even notice the function signature syntax. You're a life saver.

**Comment by albsa** [comment]
@alexandrebodin thanks for the explaination, I think this should be added as a hint to the graphql docs as it is very confusing when new to GraphQL

**Comment by szmizorsz** [comment]
@alexandrebodin I am not able to use your solution, the JSON input type is not recognized:
<img width="1708" alt="Screenshot 2021-07-12 at 14 08 21" src="https://user-images.githubusercontent.com/7248153/125285523-073d1d80-e31b-11eb-99e4-a0d43c759b64.png">

Do I miss something?
Thanks
