### ISSUE TITLE
Created model return undefined in the avatar field where is the same reference to image

### ISSUE THREAD

**Issue by dkarski** [strapi/strapi#3538]
**Describe the bug**
Not correct creating model with more than one avatar which has reference to the same image.

**Steps to reproduce the behavior**
1. You have just uploaded some image and some model with more than one avatar attributes
2. Create new model instance by graphql mutation where every avatar has reference to the same image
3. Only one field (avatar attribute) will have reference to the uploaded image the last fields will have undefined. Getting undefined is randomly.

**Another steps to reproduce the behavior**
1. You have just uploaded some image and some model instance with avatar attribute wich has reference to uploaded image
2. Create new model instance by graphql mutation where every avatar has reference to the same image
3. Reference to the image for previous model instance will be detach

**Expected behavior**
Avatars of model could has reference to the same image.

**System**
- Node.js version: 10.15.3
- NPM version:  6.4.1
- Strapi version: 3.0.0-beta.7
- Database: MongoDB
- Operating system: Mac OS

**Comment by lauriejim** [comment]
Hello! 
Can you share with me your GraphQL mutation please.
