### ISSUE TITLE
Default value for related fields

### ISSUE THREAD

**Issue by 12three** [strapi/strapi#3539]
It would be nice to have the ability to set a default value for related fields

**Comment by derrickmehaffy** [comment]
@12three Please use the feature request template, issues without using a template are closed in order to keep the issues clear and clean.

For now I will mark this as closed, you are welcome to update your issue with the proper template and this can be reopened.

**Comment by lauriejim** [comment]
Hello @12three !
Could you give me more details please.
I'm not sure to understand your need.

**Comment by derrickmehaffy** [comment]
@lauriejim in this case the user is asking for a way to set a default value for a relation.

Say for example you have a `oneWay` relation between an `order` model and an `ordertype` model, allowing for a default value of `ordertype` ID 1 (using SQL IDs as an example).

Effectively meaning that all new orders that don't pass the `ordertype` relation will be given the relation ID of 1.

**Comment by lauriejim** [comment]
Got it! Thank you for the details.
