### ISSUE TITLE
Uploading to a collection throws "TypeError: Cannot read property 'globalId' of undefined" error

### ISSUE THREAD

**Issue by nurikabe** [strapi/strapi#3545]
**Describe the bug**

```
$ curl -X POST -F 'files=@sample.pdf' -F 'ref=project' -F 'refId=5d158d18e147df00112e16ae' -F 'field=files' -F 'source=users-permissions' https://somestrapidomain.com/upload
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```
Server logs show:
```
error TypeError: Cannot read property 'globalId' of undefined
at acc.(anonymous function).property.map.obj (/opt/app/node_modules/strapi-hook-mongoose/lib/relations.js:125:69)
at Array.map (<anonymous>)
at params.parseRelationships.Object.keys.reduce (/opt/app/node_modules/strapi-hook-mongoose/lib/relations.js:123:35)
at Array.reduce (<anonymous>)
at Function.update [as updateRelations] (/opt/app/node_modules/strapi-hook-mongoose/lib/relations.js:30:122)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**

Successful upload associated with the "files" field of the "project" entity.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: beta.8
- Database: MongoDB
- Operating system: Ubuntu 18.04.2 LTS

**Additional context**

Only a problem when ` -F 'source=users-permissions'` is included. Without ` -F 'source=users-permissions'`, however, no relationship is created.

What is the relevance of  the `source` parameter to creating relationships? 

Related to #3496?

**Comment by derrickmehaffy** [comment]
@nurikabe 

> source: (optional): The name of the plugin where the model is located.

Only relates to relationships with plugin models like /users

https://strapi.io/documentation/3.0.0-beta.x/guides/upload.html

**Comment by derrickmehaffy** [comment]
@nurikabe As there hasn't been a response yet I am marking this as closed, if you still have issues reply back and this can be reopened.

**Comment by nurikabe** [comment]
Was me failing to understand that plugin models could be referenced as well.

Tweaked the docs a bit: https://github.com/strapi/strapi/pull/3584

**Comment by JiboStore** [comment]
I have the same error too, I didn't specify `source`
In my case, the file is successfully uploaded but it is not linked to the field
