### ISSUE TITLE
Upload file doesn't work with graphQL

### ISSUE THREAD

**Issue by renanbronchart** [strapi/strapi#3546]
### Describe the bug

Hello,
I try to upload an image directly with graphQl mutation but it doesn't seem to work.

### Steps to reproduce the behavior

I work on Vue.js project
I have form with input file.
```
      <input
        @change="upload($event)"
        ref="file"
        type="file"
        name="fileInput[]"
        id="fileInput"
        class="inputfile inputfile-upload"
        capture="user"
      >
```

#### function upload:
```
upload (event) => {
  const formData = new FormData()

  formData.append('files', event.target.files[0])
  axios.post('https://db.smapps.app/graphql', {
          query: `
            mutation UploadFile($file: Upload!) {
              upload(file: $file) {
                id
                hash
                url
              }
            }
          `,
          variables: {
            file: formData,
          },
        })
}
```

I have this error with 400 status:
```
{"errors":[{"message":"Bad Request","locations":[{"line":3,"column":13}],"path":["upload"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"data":"Files are empty","isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Bad Request"},"headers":{}},"message":"Bad Request","stacktrace":["Error: Bad Request","    at Object.strapi.app.response.(anonymous function) [as badRequest] (/var/www/api/node_modules/strapi/lib/middlewares/boom/index.js:74:34)","    at Object.proto.(anonymous function) [as badRequest] (/var/www/api/node_modules/delegates/index.js:40:31)","    at Object.upload (/var/www/api/node_modules/strapi-plugin-upload/controllers/Upload.js:30:18)"]}}}],"data":null}
```

### Expected behavior

I would like to upload image with graphQl mutation.

### Supplements

I try to send to ```/graphql``` files directly instead of form Data() like : 
```
      axios.post('https://db.smapps.app/graphql', {
        query: `
          mutation UploadFile($file: Upload!) {
            upload(file: $file) {
              id
              hash
              url
            }
          }
        `,
        variables: {
          file: [event.target.files[0]],
        },
      })
```

And I have this error with 200 status:
```
{"errors":[{"message":"The \"path\" argument must be one of type string, Buffer, or URL. Received type undefined","locations":[{"line":3,"column":13}],"path":["upload"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be one of type string, Buffer, or URL. Received type undefined","    at Object.open (fs.js:408:3)","    at ReadStream.open (internal/fs/streams.js:110:12)","    at new ReadStream (internal/fs/streams.js:99:10)","    at Object.createReadStream (fs.js:1732:10)","    at Promise.all.files.map (/var/www/api/node_modules/strapi-plugin-upload/services/Upload.js:37:40)","    at Array.map (<anonymous>)","    at Object.bufferize (/var/www/api/node_modules/strapi-plugin-upload/services/Upload.js:36:13)","    at Object.upload (/var/www/api/node_modules/strapi-plugin-upload/controllers/Upload.js:34:65)"]}}}],"data":null}

```

### System

Node.js version: 10.13.0
NPM version: 6.4.1
Strapi version: 3.0.0-beta.7
Mysql: Version 14.14 Distrib 5.7.26, for Linux (x86_64)

Thanks a lot for response.

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/3516

**Comment by renanbronchart** [comment]
> Duplicate: #3516
Is not duplicate, is not the same problem

**Comment by derrickmehaffy** [comment]
@renanbronchart you have two open issues related to GraphQL mutation requests with upload, please limit it down to one and add some context to the other issue.

There is no reason to have two open issues with a similar context. The error messages may be different the source is still the same.

**Comment by renanbronchart** [comment]
Yes @derrickmehaffy,  I keep this issue, I just closed the first one.

**Comment by derrickmehaffy** [comment]
cool that's fine, doesn't matter which one is kept but just trying to help keep the issues a bit cleaner :)

**Comment by lauriejim** [comment]
Hello @renanbronchart, can you please update your body message with the database you use to make sure to work on the same env than you.

**Comment by lauriejim** [comment]
Hello! The GraphQL upload has been updated in the `beta.16` version of strapi.
See the [pull request 📦](https://github.com/strapi/strapi/pull/3819)
Can you please re-test your issue, please.
If it's ok, I will close this issue.

**Comment by miguelangeltorresfp** [comment]
@lauriejim Hi,
I'm using a code similar to the one used by @iamacatperson.
I took it from the Ben Awad's example `https://github.com/benawad/apollo-server-react-file-upload`
I works perfectly with his demo server, but when I try to upload an image to my strapi server it shows the follow error message:
**`Error: GraphQL error: createReadStream is not a function`**

**System**
Node.js version: 10.15.1
NPM version: 6.9.0
Strapi version: 3.0.0-beta.16.8
On Windows 10 pro

Note: I only had to add `name` as a field in the result in the Ben Awad's code:
```
const uploadFileMutation = gql`
  mutation UploadFile($file: Upload!) {
    upload(file: $file) {
      name
    }
  }
`;
`;
```

**Comment by veitbjarsch** [comment]
@miguelangeltorresfp I've encountered the same problem :-/. I'll have a look into it. May I can find something.

**Comment by veitbjarsch** [comment]
@miguelangeltorresfp I did it. Now I need to tidy up my code and will create a PR with the fix afterwards
