### ISSUE TITLE
Using provide for social login returns 500 error when we try to access connect/{provider}

### ISSUE THREAD

**Issue by m98** [strapi/strapi#3549]
**Describe the bug**
I followed documents to add social login to API, I generated web client API on Google Developer Console, and used those information to activate provider. 
When I browser to `http://localhost:1337/connect/google` I get the following error on browser and node logs:

Browser:
```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
}
```

Node:
```
[2019-06-28T14:57:15.031Z] error TypeError: Middleware stack must be an array!
    at compose (/mnt/e/personal/travel/api/node_modules/koa-compose/index.js:20:41)
    at connect (/mnt/e/personal/travel/api/node_modules/strapi-plugin-users-permissions/controllers/Auth.js:269:12)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[2019-06-28T14:57:15.035Z] debug GET /connect/google (19 ms)
[2019-06-28T14:57:15.508Z] debug GET /favicon.ico (1 ms)
```
![Capture](https://user-images.githubusercontent.com/7496103/60351411-fd1d8000-99da-11e9-9d23-16e12945adca.PNG)

**Steps to reproduce the behavior**
Follow the document to activate provider for Google social sign in, then go to [http://localhost:1337/connect/google/](http://localhost:1337/connect/google/)

**Expected behavior**
Unfortunately, the documentation is not very clear about this, but I expected to go to a page which helps me to log in using my Google account

**Code snippets**
I wrote no code

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.7
- Database: Mongodb - 4.0.10
- Operating system: Windows 10 / 64bit

**Comment by Lith** [comment]
Duplicate with #3526 ?
Try the solution described in, this will be fixed in beta.9

**Comment by alexandrebodin** [comment]
closing as @Lith just says :)
