### ISSUE TITLE
How to properly use postgres?

### ISSUE THREAD

**Issue by nkhdo** [strapi/strapi#355]
**Node.js version**: 8.9.0
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.6.7
**Operating system**: Linux mint 18

When I trying to add a postgres database, and create a model using content builder plugin, it tells me to create the table in my database first, and show me a link to strapi doc. However, I followed the link (https://strapi.io/documentation/guides/models.html#bookshelf) but found no information regarding the table creation step.

I think we should have a migration system/plugin for sql databases, is it reasonable?

Best Regards,

**Comment by lauriejim** [comment]
Yes we know about thats, it's in our roadmap to have a better workflow using content type builder with SQL database.

**Comment by lauriejim** [comment]
With this two new features https://github.com/strapi/strapi/pull/420 and https://github.com/strapi/strapi/pull/416 we improve the user experience for SQL database project.
Will be available in version `alpha.8`
