### ISSUE TITLE
Retrieve a single file depending on its id trigger an error instead of 404 status code

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#3551]
**Describe the bug**
Cannot get the file by id, because of an error:

```
error TypeError: Cannot read property 'url' of null
    at findOne (/Users/alexanderkim/Sites/dmvno-cms/node_modules/strapi-plugin-upload/controllers/Upload.js:135:41)
    at async /Users/alexanderkim/Sites/dmvno-cms/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:70:22
    at async module.exports (/Users/alexanderkim/Sites/dmvno-cms/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:39:14)
    at async /Users/alexanderkim/Sites/dmvno-cms/node_modules/strapi-utils/lib/policy.js:111:7
    at async validator (/Users/alexanderkim/Sites/dmvno-cms/node_modules/koa-joi-router/joi-router.js:407:32)
    at async noopMiddleware (/Users/alexanderkim/Sites/dmvno-cms/node_modules/koa-joi-router/joi-router.js:267:10)
    at async specExposer (/Users/alexanderkim/Sites/dmvno-cms/node_modules/koa-joi-router/joi-router.js:448:5)
    at async prepareRequest (/Users/alexanderkim/Sites/dmvno-cms/node_modules/koa-joi-router/joi-router.js:460:3)
[2019-06-30T19:07:05.398Z] debug GET /upload/files/1 (14 ms)
```

**Steps to reproduce the behavior**
1. Make a GET request as follows:

```
curl -X GET "http://localhost:1337/upload/files/1" -H "accept: application/json" -H "Authorization: Bearer tokenID_here"
```

**Expected behavior**
Getting a file in response if file exists, if not - return the error, that "file was not found". Now it returns error 500 and message above.

**System**
- Node.js version: 10 LTS
- NPM version: 6.9.0
- Strapi version: Strapi v3.0.0-beta.8
- Database: PostgreSQL 10.8
- Operating system: MacOS / Ubuntu

**Additional context**
This happens in all environments - dev, staging, production.

**Comment by lauriejim** [comment]
Hello @webcoderkz !
I created a new application, uploaded a files, opened permissions to fetch one files and it worked.
How did you upload you files?
Your file still exist?
Do you have a relation with this file?

**Comment by webcoderkz** [comment]
@lauriejim uploaded through admin panel in Files section. Yes, file exist, what you mean by relation? I just uploaded a single file, nothing more.

**Comment by lauriejim** [comment]
Hum when I check the code that fire this issue:
`/Users/alexanderkim/Sites/dmvno-cms/node_modules/strapi-plugin-upload/controllers/Upload.js:135:41)`
This is because `Cannot read property 'url' of null` so `data.url` is null in the code.
This happen when the image with the `id` **1** doesn't exist.
I just tried to fetch an image that exist and it work and I tried with an incorrect id that did not exist and I had this error.

Please @webcoderkz  can you confirm my message.

**Comment by webcoderkz** [comment]
@lauriejim that's the issue. It's needed to throw a correct response instead of this error.

**Comment by lauriejim** [comment]
OK clear now.
Please feel free to manage the error and submit a PR.
I will appreciate your contribution for this issue.

**Comment by forethoughtde** [comment]
@lauriejim I would like to fix this issue. Can you please guide me on which file should I look into?

**Comment by lauriejim** [comment]
Hello @forethoughtde !
I suggest you read the discussion (previous messages).
I explain all the stuff in [this message](https://github.com/strapi/strapi/issues/3551#issuecomment-509623915)

**Comment by lauriejim** [comment]
This issue has already been fixed.
I close this issue.
