### ISSUE TITLE
High GraphQL response time query images relations

### ISSUE THREAD

**Issue by cliqer** [strapi/strapi#3552]
**Describe the bug**
A Graphql query that also contains images is very slow.
Without images it works normally.

**Steps to reproduce the behavior**
I have an online staging site. feel free to:
1. Go to https://api.zerbinis.gr/graphql
2. Run the query:
```
query{
  categories{
    name
    books(limit:10){
      title
    }
  }
}
```
the speed is normal.

3. Now run this query to also contain image ids:
```
query{
  categories{
    name
    books(limit:10){
      title
      image{
        id
      }
    }
  }
}
```
The query takes forever and thats just with 10 books.
It is unusable when images are requested.

4. Now try to request directly with rest:
https://api.zerbinis.gr/categories
It is lighting fast while returning everything.

**Expected behavior**
Graphql to be almost as fast as rest

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.6
- Database: Mongo Atlas
- Operating system: OSX Dev & Centos 7 Production

**Comment by derrickmehaffy** [comment]
Please test with the beta, also can you clarify where this is being hosted and with what specifications?

**Comment by gianniskarmas** [comment]
I already tried with beta.9.
Strapi is hosted on a dedicated server in OVH (12-cores, 32G Ram) and DB in Mongo Atlas.
The same happens on my Macbook with local mongo.
Am I the only one with this problem?

**Comment by derrickmehaffy** [comment]
Well server specs are certainly not the issue lol. No I haven't seen any other issues related to slow GraphQL queries. You don't by chance have tracing enabled do you?

`extensions/graphql/config/settings.json` If so disable it. Tracing will absolutely slow queries down

**Comment by gianniskarmas** [comment]
There is no 'extensions' folder in beta and the server is running in production mode.
Any other clues?

**Comment by lauriejim** [comment]
Hello @gianniskarmas !
Thank you for reporting this.

Can you share with us a set of data to be able ton investigate please.

**Comment by gianniskarmas** [comment]
Hi @lauriejim.
Thank you for your time with my issue.

I created a repo:
[https://github.com/gianniskarmas/zerb](https://github.com/gianniskarmas/zerb)

Inside the db_json folder you can find the data to import in your mongo db (I use Studio3T).
Did some more tests and realised that when Images are included in the query it takes 5x more and when the remote atlas db connection's latency comes to play it becomes unusable.

Many Thanks and hope this helps.

**Comment by gianniskarmas** [comment]
Is there any progress made with this issue?
Trying every new strapi version but still the GraphQL performance when including images is very slow.
Is there any workaround?

**Comment by chadboyda** [comment]
The polymorphic relationship queries are causing it to be very slow. 

filter: { related.field: “image”, related.kind: “Product”, related.ref: { $in: [ ObjectId(‘5e5692b4182586204df2ac06’) ] } }

Even with a compound index the use of the $in slows it down substantially. The query will take 15ms vs 50ms for us if we switch the $in: to an equal

Is there a way we can optimize these queries in Strapi? In our use case we'll never have a file attached to more than one object.

**Comment by bfops** [comment]
I believe I'm hitting a similar issue; certain collections in our DB have become pathalogically slow to query via strapi, even for tiny collections and small simple queries.

I'm on the beta 3.0.0-18.7, but it looks like there's no mention of more recent versions having fixed this issue?

**Comment by derrickmehaffy** [comment]
I am going to close and lock this thread in favor of our global tracking issue here: https://github.com/strapi/strapi/issues/8552

If anyone has additional comments please place them on the tracking issue, we are doing this to help centralize the issue and make it clearer where various related bug reports stem from the same source.
