### ISSUE TITLE
Strapi new issue with Postgres. Tarn: unsupported option opt.afterCreate

### ISSUE THREAD

**Issue by thejettdurham** [strapi/strapi#3554]
**Describe the bug**
A fresh install of Strapi using knex fails to start with with the following error 

```
[2019-07-02T04:06:10.754Z] error Impossible to use the `default` connection...
[2019-07-02T04:06:10.755Z] warn Be sure that your client `default` are in the same node_modules directory
[2019-07-02T04:06:10.757Z] error Error: Tarn: unsupported option opt.afterCreate
    at new Pool (/app/node_modules/tarn/lib/Pool.js:89:15)
    at Client_PG.initializePool (/app/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:320:17)
    at Client_PG.Client (/app/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:87:12)
    at new Client_PG (/app/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/postgres/index.js:31:19)
    at Knex (/app/node_modules/strapi-hook-knex/node_modules/knex/lib/knex.js:57:42)
    at _.forEach (/app/node_modules/strapi-hook-knex/lib/index.js:178:45)
    at /app/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/app/node_modules/lodash/lodash.js:2996:24)
    at /app/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/app/node_modules/lodash/lodash.js:9344:14)
    at Function.initialize (/app/node_modules/strapi-hook-knex/lib/index.js:49:9)
    at /app/node_modules/strapi/lib/hooks/index.js:52:31
    at Promise (/app/node_modules/strapi/lib/hooks/index.js:149:37)
    at new Promise (<anonymous>)
    at Promise.all.Object.keys.map.hook (/app/node_modules/strapi/lib/hooks/index.js:75:9)
    at Array.map (<anonymous>)
    at Strapi.module.exports (/app/node_modules/strapi/lib/hooks/index.js:73:28)
```
**Steps to reproduce the behavior**
1. Create a new strapi project `strapi new repro`
2. Have a local postgres instance running with a new database named `repro`
3. Use the `Custom` option to point strapi at this postgres instance
4. `cd repro && npm start`
5. See the error described above

**Expected behavior**
Running `npm start` does not show this error

**System**
- Node.js version: `10.13.0`
- NPM version: `6.9.0`
- Strapi version: Beta 8
- Database: Postgres (latest docker image)
- Operating system: macOS Mojave 

**Additional context**
The source of the problem seems to be updates in the transitive dependency [Tarn](https://github.com/Vincit/tarn.js). The maintainers released an update about 7 hours ago, and this update is apparently doing stricter option key validation than previously existed.

Knex specifies tarn version `^1.1.5`, which allows for the new release `1.2.0` to be installed.

If I specify `"tarn": "1.1.5"` in my project's package.json, this error goes away.

**Comment by nmaxcom** [comment]
Exactly the same here. I also chose PostgreSQL. With --quickstart it all works (by default sqlite).

Maybe I can help with a bit of context:
in /node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:320
`this.pool = new _tarn.Pool(this.getPoolSettings(config.pool));`

For whatever reason, choosing PostgreSQL makes that key appear in the config.pool object:
![image](https://user-images.githubusercontent.com/8936090/60490278-83211b80-9ca6-11e9-8251-1e8af60f6cdc.png)

And so that cool goes straight to a for..of at node_modules/tarn/lib/Pool.js:

```js
for (let key of Object.keys(opt)) {
            if (!allowedKeys[key]) {
                throw new Error(`Tarn: unsupported option opt.${key}`);
            }
        }
```

And indeed, just like OP noted, it's stricter, allowedKeys being these (also in Tarn's Pool.js):
```js
const allowedKeys = {
            create: true,
            validate: true,
            destroy: true,
            log: true,
            min: true,
            max: true,
            acquireTimeoutMillis: true,
            createTimeoutMillis: true,
            destroyTimeoutMillis: true,
            idleTimeoutMillis: true,
            reapIntervalMillis: true,
            createRetryIntervalMillis: true,
            propagateCreateError: true
        };
```

It crashes and we are left without strapi :(

The for..of and the allowedKeys were [introduced just today](https://github.com/Vincit/tarn.js/commit/7105c612d7edbcb379ec75023e21769230ada3f3#diff-1b589a05fcf1509343500faf9cd70bda) (again, OP said it first 🙂)

It's easy to find a workaround in the meantime but what's the solution?

**Comment by alexandrebodin** [comment]
Yep all you just said is right. We will release a fix on our side too asap

This might be resolved on it's own https://github.com/Vincit/tarn.js/issues/33

**Comment by nmaxcom** [comment]
Tarn seems to be a popular package. Did they warn about this first?

**Comment by elhigu** [comment]
@nmaxcom no. Change was discussed in issues few months ago and it was meant to be released as major version change. But I accidentally released it as minor one. Now 1.2.0 is unreleased and 2.0.0 is out.

**Comment by alexandrebodin** [comment]
@elhigu Thank you for the qucik fix I'm closing this issue as it as been resolved 🚀

**Comment by kibertoad** [comment]
@alexandrebodin Was there ever a proper fix from strapi side? There are important fixes in tarn.js 2.0.0 and knex is switching to it from 0.19.0 onwards, so it would be a good idea to make sure unsupported keys are no longer passed to the pool :)

**Comment by alexandrebodin** [comment]
The invalid params are passed by knex itself not strapi :) so if knex support tarn v2 strapi will too ;)

**Comment by kibertoad** [comment]
Hmmm, interesting. @elhigu Are we passing any pool configs explicitly? I used to think that we only forward what user has provided.

**Comment by alexandrebodin** [comment]
@kibertoad 
Well we are passing afterCreate param which is valid as of know with knex at least in the docs :) 

If it is removed then we will need to update strapi for sure

**Comment by elhigu** [comment]
Yep. .afterCreate is part of pool config because of historical reasons. That hook is implemented in knex side and it should not be passed to pool creation.

**Comment by alexandrebodin** [comment]
Ok so if knex updates to tarn v2 and makes sure the param is only handled on knex's side we are all good :D Thanks guys !

**Comment by elhigu** [comment]
> Hmmm, interesting. @elhigu Are we passing any pool configs explicitly? I used to think that we only forward what user has provided.

Most important options like create, destroy and validate functions are passed by knex and not by user. Probably also some defaults to min, max and propagateCreateError and maybe even some default timeouts :) so yeah knex is generating most of the config internally and not only passing end user’s params.

**Comment by alexandrebodin** [comment]
Going to ref this PR here so we can keep up to date https://github.com/tgriesser/knex/pull/3345 ;)
