### ISSUE TITLE
500 Internal Server Error when clicking "Start the quick start tutorial"

### ISSUE THREAD

**Issue by BitesizedLion** [strapi/strapi#3557]
**Describe the bug**
The "start the quick start tutorial" brings you to a 500 Internal Server Error
and whilst I am here, the blog and slack button on the documentation page doesn't work

**Steps to reproduce the behavior**
1. Install strapi like normally
2. Run it
3. Go to http://localhost:1337/admin/
4. Press "Start the quick start tutorial"
5. See "500 Internal Server Error" error on the page. 

**Expected behavior**
For it to bring me to the actual page.

**Screenshots**
Not applicable.

**Code snippets**
Not applicable.

**System**
- Node.js version: v10.14.2
- NPM version: v6.4.1
- Strapi version: Latest (No clue)
- Database: No clue, literally just used the normal --quickstart
- Operating system: Windows 10 Pro

**Additional context**

**Comment by davidkartuzinski** [comment]
@BitesizedLion - It seems that there is a missing build step occurring.  Could you please list out the exact commands necessary to reproduce this error? 

There are many options and commands to install and run Strapi...

**Comment by BitesizedLion** [comment]
```
npm install strapi@beta -g
strapi new my-project --quickstart
```

I register a user, complete the form and press the "Start the quick start tutorial" button and it redirects me to the wrong documentation page, therefore it gives me a 500 Internal Server Error  (the 500 Internal Server Error is not on my side, the only wrong thing is the link the "Start the quick start tutorial" button leads me to.)

The exact steps I used are the ones listed here
https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_1-install-strapi-globally

**Comment by alexandrebodin** [comment]
The link in the interface is wrong. 
You need to add `3.0.0-beta.x` after `/documentation` in the url ;)

**Comment by alexandrebodin** [comment]
Should be working now with the right redirections ;) I'm closing this issue. 
Thanks again for reporting it !
