### ISSUE TITLE
.env file is not respected

### ISSUE THREAD

**Issue by karolisgrinkevicius** [strapi/strapi#3558]
`.env` file is not respected in certain environment config files 

**Steps to reproduce the behavior**
1. Create `.env` file in the root of strapi app
2. Put any variable, i.e.` DATABASE_PORT=27017`
3. Run development server using `yarn develop`
4. `MongoError: database name must be a string`

**Expected behavior**
Environment variables defined in `.env` file are respected when building the project

**Screenshots**

**Code snippets**
`config/environments/development/database.json`
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME || ''}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}"
      },
      "options": {}
    }
  }
}

```

**System**
- Node.js version: 10.7.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.8
- Database: Mongo
- Operating system: MacOSX 10.14.5

**Comment by derrickmehaffy** [comment]
@karolisgrinkevicius Strapi doesn't load data from .env natively yet you will need to add in a way to call the `.env` file.

As an example from my own project:
https://github.com/canonn-science/CAPIv2-Strapi/blob/ef3d8b738217e095d66c1eb3a14c6b692317b218/config/functions/bootstrap.js#L11-L13

In my case I am using two extra packages in my package.json:
```
    "dotenv": "^6.2.0",
    "find-config": "^1.0.0",
```

And using the bootstrap function (top of the file) to preload my .env before strapi starts:
```
require('dotenv').config({ path: require('find-config')('.env') });
```

**Comment by derrickmehaffy** [comment]
As this is not technically a bug, and is known about (I believe some native support for .env is planned but no ETA) I will mark this as closed.

If you have issues using my code, you are welcome to jump on the slack and ping me. :smiley:

**Comment by jasenmichael** [comment]
> find-config


@derrickmehaffy thank you, your method worked great to use local .env file with strapi
`
npm i dotenv find-config
`
and then add just above the module.exports in the config/functions/bootstrap.js file, add..
`
require('dotenv').config({ path: require('find-config')('.env') }) 
`

**Comment by derrickmehaffy** [comment]
Glad I could help ;)

**Comment by IvanKodola** [comment]
TypeError: Cannot read property 'defaultConnection' of undefined when use dotenv file

Steps to reproduce the behavior

Create .env file in the root of strapi app
Put any variable, i.e. DATABASE_PORT=5432
Add in bootrstap.js
require('dotenv').config({ path: require('find-config')('.env') });
Run development server using npm run develop
TypeError: Cannot read property 'defaultConnection' of undefined when use dotenv file

System

Node.js version: 10.16.0
NPM version: 6.9.0
Strapi version: 3.0.0-beta.15
Database: Postgress
Operating system: MacOSX 10.14.5

**Comment by derrickmehaffy** [comment]
did you install the required packages @IvanKodola ?
you need these two in your package.json:

```
    "dotenv": "^6.2.0",
    "find-config": "^1.0.0",
```

**Comment by IvanKodola** [comment]
TypeError: Cannot read property 'defaultConnection' of undefined when use dotenv file

Steps to reproduce the behavior

Create .env file in the root of strapi app
Put any variable, i.e. DATABASE_PORT=5432
Add in bootrstap.js
require('dotenv').config({ path: require('find-config')('.env') });
Run development server using npm run develop
TypeError: Cannot read property 'defaultConnection' of undefined when use dotenv file

System

Node.js version: 10.16.0
NPM version: 6.9.0
Strapi version: 3.0.0-beta.15
Database: Postgress
Operating system: MacOSX 10.14.5

**Comment by IvanKodola** [comment]
@derrickmehaffy Yes

**Comment by aistyler** [comment]
My package.json has the following script command.
so, my dotenv files(.env, .env.${NODE_ENV}, .env.${NODE_ENV}.local) are loaded before starting strapi. But not on Windows.

```js
"dependencies": {
  "dotenv-flow": "^3.1.0",
  ...
},
"scripts": {
  "dev": "node -r dotenv-flow/config -e 'require(\"./node_modules/strapi/lib/commands/develop.js\")({build:true})'"
}
```

**Comment by matepaiva** [comment]
@jasenmichael I used your approach in `bootstrap.js` and I set successfully the variables using `.env`. BUT...

Only one (big) problem. At that point, I think that the variable `NODE_ENV` is already used to set which environment folder will be used to get the variables (`environments/production`, `environments/development` or `environments/staging`).

It means that even if I set `NODE_ENV` in `.env` as `PRODUCTION`, if I go to `localhost:1337`, you will find the environment defined as `development`.

> **IMPORTANT**: this only happens if you run `npm start`. Everything works fine with `npm run develop`.

**Comment by jasenmichael** [comment]
@matepaiva 

> I think that the variable NODE_ENV is already used to set which environment folder will be used to get the variables (environments/production, environments/development or environments/staging).

I don't use the .env file to set the node environment, as I set that in the build/start commands, like..
```bash
npm run build
# which runs > NODE_ENV=development npm run build
# or 
NODE_ENV=production npm run build
```
 to load the associated config/environments/<development/staging/production>/database.json <<< which gets environments from .env if available(via the bootstrap.js approach). I can then have one .env in root directory to config NODE_ENV=development and NODE_ENV=production. I also use this for third party keys, and create proxy api routes for those services.
```
DEV_DB=strapi
DEV_DB_PASS=dev-db-password
PROD_DB=some-prod-db
PROD_DB_PASS=prod-db-pass
```

example configs:
config/environments/development/database.json
```js
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "database": "${process.env.DEV_DB}",
        "password": "${process.env.DEV_DB_PASS'}"
       // of course there are more key: value pairs
      },
    }
  }
}

```
config/environments/production/database.json
```js
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "database": "${process.env.PROD_DB}",
        "password": "${process.env.PROD_DB_PASS'}"
      },
    }
  }
}

```
note when deploying to Heroku or other SaaS, the NODE_ENV is already set to production, and you add the .env to .gitignore, and manually set the environments via the Heroku environment variables.

I like having all my environment variables in one .env file

**Comment by dgray0229** [comment]
Editing the bootstrap.js file didn't work for me. However, I did find a working solution on StackOverflow:

https://stackoverflow.com/questions/59792344/strapi-cms-where-to-put-the-environment-variables

Basically you install dotenv and create your own start script that runs dotenv.config() and then after you call the strapi start function. 

`
// server.js
const dotenv = require('dotenv');
const strapi = require('strapi');

dotenv.config();
strapi().start();
`

Then you would change your "yarn start" command in the package.json to run "node server". or whatever you name your start script, and that script will tell strapi to start after the env variables are configured.

**Comment by MattieBelt** [comment]
Since stable release 3.0.0, `.env` usage is implemented by default. Check out the new docs: https://strapi.io/documentation/v3.x/concepts/configurations.html#environment-variables

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/changing-database-credentials-on-heroku-6277/1772/2
