### ISSUE TITLE
Fail to set one to one relationship mysql

### ISSUE THREAD

**Issue by andreac998** [strapi/strapi#3565]
Sometimes when trying to create new entity vie API (post) the relationship one to one are missed.

It's easy to reproduce with remote and slow database server but happen in local too.

**Steps to reproduce**

1. Create two entities
2. Create a "relation" field type and set that one to one 
3. Use postman to call the POST api to create one of these entities setting in the body the relation field
4. Try many times
5. Sometimes the relation was unsetted

When this happen the "external keys" is setted only in one of the two tables.
No error reported by application

Node.js version: 10.16
NPM version: 6.9.0
Strapi version: beta and alpha

See screenshots of the same call with same data. 
<img width="979" alt="Schermata 2019-07-04 alle 14 41 55" src="https://user-images.githubusercontent.com/46871541/60668074-6255f300-9e6b-11e9-8851-6dca3d752764.png">
<img width="990" alt="Schermata 2019-07-04 alle 14 41 44" src="https://user-images.githubusercontent.com/46871541/60668075-6255f300-9e6b-11e9-8968-f2339136a5f3.png">

**Comment by lauriejim** [comment]
Hello @andreac998 !
I created a new app with `strapi beta.9` and it works.

What is your strapi version?

**Comment by andreac998** [comment]
Hello lauriejim 

I can reproduce with beta8 and different alpha version such 26.2.

It's easier to reproduce with a slow dbms server, you need to try many insert. 
I think that is a core bug with the double insert of the ID's in the two related tables

**Comment by lauriejim** [comment]
Hum are you sure the first request is ended before creating a new entry withe the same relation?

**Comment by andreac-ey** [comment]
Sure, I'm testing with postman with manual sending request

**Comment by andreac-ey** [comment]
Now I have make a new installation of beta10 using my local mysql.

I have make two content type:
- house with field:
    - name (string)
    - person (reference to person entity)
- person with field:
    - name (string)
    - house (reference to house entity)

I have set all permission of all api's allow to public

Using postman for create rows in house, after 50 identical request I have got the bug.

See screenshot.

Reproduce the bug it's very easy, need only try to make many post.
<img width="906" alt="Schermata 2019-07-09 alle 20 05 02" src="https://user-images.githubusercontent.com/52250111/60912306-5d3ade80-a285-11e9-8ceb-27eafb610861.png">
<img width="1001" alt="Schermata 2019-07-09 alle 20 04 45" src="https://user-images.githubusercontent.com/52250111/60912308-5d3ade80-a285-11e9-90f4-2ac0f7b87d01.png">

**Comment by andreac998** [comment]
@lauriejim Now I have make a new installation of beta10 using my local mysql.

I have make two content type:
- house with field:
    - name (string)
    - person (reference to person entity)
- person with field:
    - name (string)
    - house (reference to house entity)

I have set all permission of all api's allow to public

Using postman for create rows in house, after 75 identical request I have got the bug.

See screenshot.

Reproduce the bug it's very easy, need only try to make many post.
<img width="906" alt="Schermata 2019-07-09 alle 20 05 02" src="https://user-images.githubusercontent.com/52250111/60912306-5d3ade80-a285-11e9-8ceb-27eafb610861.png">
<img width="1001" alt="Schermata 2019-07-09 alle 20 04 45" src="https://user-images.githubusercontent.com/52250111/60912308-5d3ade80-a285-11e9-90f4-2ac0f7b87d01.png">

**Comment by derrickmehaffy** [comment]
@andreac998 I believe there is a miss-understanding here.

In the case of a `oneToOne` relationship between a house and a person. A House can only have one person and a person can only have one house (Hence `oneToOne`) If you create or update a house with a person that already has one, the older entry will no longer have that person.

Effectively the "newest" entry assigned between house and person will maintain that relationship. If instead you want a person to have multiple houses or likewise a house to have multiple persons. You need to use a `oneToMany` relationship (or a manyToOne, which are effectively the same thing but changing which side is "dominate")

The logic you are describing your screenshots is intended.

**Comment by andreac998** [comment]
Guys It's only an example to reproduce the bug, I don't need lessons about relations.

Please It's simple to try:
- use mysql
- create two entities
- create one2one relation and strapi create automatically the field in both 
- perform many insert

In some cases the ralation are missed and and it is a very serious problem in production

**Comment by derrickmehaffy** [comment]
@andreac998 what we are saying is we have tried to reproduce this (I have attempted this about 6 or 7 times now in the past 2 days) In total posting about 35,000 records and have not seen this happen.

I even dropped the specs on my database server to single cpu core at 1.5ghz with half  a gig of ram.

**Comment by andreac998** [comment]
It's really strange. I have the same problem with my Macbook and different production linux server.

**Comment by derrickmehaffy** [comment]
I've tested locally on my own machine, in my production virtual machines, using Vultr, and I setup a database on a remote cloud host that is quite literally in the farthest country I could find from my currently location (Sydney Australia, and I am in Phoenix, AZ the latency alone was around 450ms) and I could not reproduce this.

**Comment by andreac998** [comment]
@lauriejim @derrickmehaffy please look this 30 second video
[https://streamable.com/pvrls](url)

**Comment by andreac998** [comment]
@lauriejim @derrickmehaffy 
I have make a testing enviroment with a fresh vps.

please try to make POST with a client like postman at 

http://52.236.165.105:1337/entity1s

with body:
    {
        "name": "aaaaaa",
        "entity2": 1
    }

**Comment by andreac998** [comment]
The simple way to test:

`curl --header "Content-Type: application/json" --request POST --data '{"name": "aaaaaa","entity2": 1}' http://52.236.165.105:1337/entity1s`

look the key "entity2" in response

**Comment by derrickmehaffy** [comment]
> The simple way to test:
> 
> `curl --header "Content-Type: application/json" --request POST --data '{"name": "aaaaaa","entity2": 1}' http://52.236.165.105:1337/entity1s`
> 
> look the key "entity2" in response

That's more or less how I was firing a few thousand requests per minute to my testing servers :wink:

**Comment by andreac998** [comment]
> > The simple way to test:
> > `curl --header "Content-Type: application/json" --request POST --data '{"name": "aaaaaa","entity2": 1}' http://52.236.165.105:1337/entity1s`
> > look the key "entity2" in response
> 
> That's more or less how I was firing a few thousand requests per minute to my testing servers 😉

:) try that please. It's really easy to reproduce. 

This is a fresh vps, with a dedicated external mysql server, and a really basic strapi configuration.

**Comment by andreac998** [comment]
@lauriejim have you try the curl?

**Comment by andreac998** [comment]
@lauriejim @derrickmehaffy 

Finally I have found the problem.
https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/relations.js

When strapi store a oneToOne relation push into array relationUpdates two promise:
1. promise at line 107 that set to null the old relations(see the comment into the code)
2. promise at line 244 that update the row with the relation

at line 258 there are a promise.all for the resolution of both promises **BUT the order is crucial.**
The promise at line 107 need to be before the promise at line 244 and promise.all does not guarantee this.
  
Forcing these two promises to execute sequentially and in the right order, the problem disappears.

**Comment by derrickmehaffy** [comment]
@andreac998 nice find do you want to submit a PR to fix this?

**Comment by andreac998** [comment]
I have submit a PR but I think that it's better that you investigate to see if the problem can also be present with other types of relationships
