### ISSUE TITLE
Deploy Strapi to Azure

### ISSUE THREAD

**Issue by muhaimincs** [strapi/strapi#3576]
**Describe the topic**
There is no documentation on how to quick deploy fresh/existing Strapi apps to Azure (IIS Node environment)

**Your suggestions for this topic**
a how-to quick deployment using Azure DevOps in free tiers and related files required

**Comment by derrickmehaffy** [comment]
@muhaimincs Please use either the bug report for feature request template (this sounds like a feature request)

I am marking this as closed for now, after you have updated your issue with the proper template reply back and this can be reopened.

**Comment by muhaimincs** [comment]
I did the feature request on #3580

**Comment by davidkartuzinski** [comment]
@muhaimincs - Thank you for noting the missing Azure docs in the official Strapi documentation. We have received a few other requests and this is already in the "docs roadmap".  

In the meantime, have you asked for help in the Slack Channel?

**Comment by muhaimincs** [comment]
oh thanks. I'll seek help in Slack

**Comment by rhernandez2015** [comment]
You should be able to deploy a container using an Azure container registry, no? This issue is for documentation, it's absolutely technically feasible
