### ISSUE TITLE
Bug renomer un champ

### ISSUE THREAD

**Issue by tomderudder** [strapi/strapi#3577]
**Describe the bug**
Strapi plante au redémarrage aprés avoir renommer un champs

**Steps to reproduce the behavior**
1. Ajouter un modèle `event`
2. Ajouter un champ `eventtype`
3. Ajouter un contenu de type `event`
4. Modifier le modèke `event` en renommant `eventtype` => `eventType`
BUG ici
5. Quitter la console avec `Ctrl` + `C` puis redémarrer avec `strapi start`

**Expected behavior**
Le serveur doit redémarrer et les modification doivent être prise en compte mais il plante et au reémarrage manuel j'ai une erreur SQLITE `Error: SQLITE_ERROR: duplicate column name: eventType`

**Screenshots**
![image](https://user-images.githubusercontent.com/48674816/60755935-2ea7d400-9ff7-11e9-8a7d-11da9a754b25.png)

**System**
- Node.js version: v10.15.1
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.9
- Database:
- Operating system: Windows

**Additional context**
Je venais de installer strapi

**Comment by derrickmehaffy** [comment]
@tomderudder Please only use english here. I will close for now, but please update your issue to use english and it can be reopened.

Thank you

**Comment by lauriejim** [comment]
Hello @tomderudder !
This issue already exist in GitHub.
