### ISSUE TITLE
Export graphql schema

### ISSUE THREAD

**Issue by yassinebridi** [strapi/strapi#3578]
I know this feature is already been implemented in the graphql playground, but as you already know i can only download the strapi specific schema which can be overwhelming,
i only need the schemas that i created through the ui

**Comment by derrickmehaffy** [comment]
@yassinebridi Please use either the bug report for feature request template (this sounds like a feature request)

I am marking this as closed for now, after you have updated your issue with the proper template reply back and this can be reopened.

**Comment by yassinebridi** [comment]
I updated it, i don't know if that's what you need, because the bug report template is not suitable for this,
I will submit it to the productboard, if that's where you track feature requests.

**Comment by lauriejim** [comment]
Yes I suggest you to send a request on ProductBoard
Here is the link https://portal.productboard.com/strapi
