### ISSUE TITLE
New Strapi beta.9 won't start after installing graphql plugin, using MYSQL db

### ISSUE THREAD

**Issue by Alluuu** [strapi/strapi#3579]
**Describe the bug**
When creating a new project with strapi, it works, after installing graphql plugin according to the new plugins use system, it no longer works, i get an error:  "TypeError: Cannot read property 'routes' of undefined" when trying to start with either strapi develop or strapi start command

**Steps to reproduce the behavior**
1. Install latest strapi 'npm install strapi@beta -g'
2. create new project 'strapi new test'
2.1. choose manual method
2.2. use mysql server
3. go to the test directory and run server 'strapi develop'
4. everything works
5. stop server
6. add graphql plugin 'npm install starpi-plugin-graphql --save'
7. try to run strapi again 'strapi develop'
8. get error "TypeError: Cannot read property 'routes' of undefined"

**Expected behavior**
I expect strapi to start normally and have graphql available

**System**
- Node.js version: v11.14.0
- NPM version: 6.7.0
- Strapi version: v3.0.0-beta.9
- Database: mysql Ver 8.0.15 for Linux on x86_64
- Operating system: Windows 10 or alpine linux

**Comment by derrickmehaffy** [comment]
`Node.js version: v11.14.0`

@Alluuu Please test with node 10, as node 11+ is not supported

**Comment by lauriejim** [comment]
Hello @Alluuu !
To install plugins I suggest you to use `strapi install <plugin>` command.
This command will install the plugin version that match with your Strapi application.

Here when you install your plugin with npm you have to add `@beta` or `@3.0.0-beta.x` (x is your strapi version)

**Comment by Alluuu** [comment]
Thank you, I just made the discovery myself as well, that strapi install plugin still works. I followed the other approach based on having previously read the new migration doc.

**Comment by lauriejim** [comment]
OKay! Thank you for the update ;)
