### ISSUE TITLE
Deploy a Strapi CLI app on Azure

### ISSUE THREAD

**Issue by muhaimincs** [strapi/strapi#3580]
There is no documentation on how to quick deploy fresh/existing Strapi apps to Azure (IIS Node environment). And this actually has a lot of process before you can launch a Strapi apps

**Comment by lauriejim** [comment]
Hello! Thank you for this suggestion!

**Comment by phmatray** [comment]
Any update?

I've been blocking on the deployment of strapi on Azure for 2 days. So far, I have been able to use Cosmo DB and BLOB storage with Strapi. I also manage to build strapi in production mode with Azure DevOps

However, for the moment, I am forced to deploy my app to Heroku, which is not viable for the company's policy for which I work.

**Comment by derrickmehaffy** [comment]
@phmatray no updates, when work starts on something you'll see it in here as it will get linked to a PR

**Comment by cdemiguel** [comment]
@phmatray you can deploy it inside windows webapp if you are not using docker, if you use docker you can deploy it inside linux webapp,
Anyway, windows web app sometimes don't deploy correctly the web (strapi bug - i supose). I am usin a web.config with IIS Node environment file to do the deploy, 

`<configuration>
  <system.webServer>
    <handlers>
      <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
    </handlers>
    <rewrite>
      <rules>
        <rule name="<yourName>">
          <match url="/*" />
          <action type="Rewrite" url="server.js" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>`

we need a correct official documentation for that
i hope this helps, 
thanks,

**Comment by darita92** [comment]
@cdemiguel I see on your web.config you tell it to run a `server.js` file. What are the contents of that file? I don't see it on Strapi

**Comment by JamesBrightman** [comment]
This is still a problem - there still isn't sufficient documentation for deploying to Azure

**Comment by roycornelissen** [comment]
@phmatray I'm interested in how you are building strapi production in Azure DevOps, can you share a description/howto on this? 

Thinking of producing a Docker container and having it run in a WebApp on Linux in Azure (using MySQL for storage).

**Comment by roycornelissen** [comment]
@phmatray did you ever manage to get it working on Azure?

**Comment by ZiedBeta** [comment]
I managed making it working on an app service with admin web app enabled:

- making a deployment from azure devops
- and running on a app service (windows)

I followed the README of this repo  https://github.com/youkou2/Strapi-On-Azure-WebApp

**Comment by buerobuettner** [comment]
still don't get my azure deployment to work. Is there a description in progress allready?

**Comment by ZiedBeta** [comment]
@buerobuettner, did you follow these instructions  ?

https://github.com/youkou2/Strapi-On-Azure-WebApp

**Comment by buerobuettner** [comment]
I configured all config/environments/production files like the template (see https://github.com/youkou2/Strapi-On-Azure-WebApp) suggests it (of course applied to my azure app environment.

my _package.json_ file has the following script:
```
..
"production": "cross-env NODE_ENV=production npm run build",
..
```

when i call i with yarn on my local development environment (windows system), i get the following output:

```
> yarn production
yarn run v1.19.1
$ cross-env NODE_ENV=production npm run build

> CSPortal@0.1.0 build C:\dev\projects\smartcomponents\repo\backend
> strapi build

Building your admin UI with production configuration ...

√ Webpack
  Compiled successfully in 17.91s

Done in 37.55s.
```

i copied all to home\site\wwwroot and get the error where <my host> is replaced by me for the post here to hide the host:
`GET https://<my host>.azurewebsites.net/admin/runtime~main.f8506bf7.js net::ERR_ABORTED 404 (Not Found)
`
The reason is, because the generated index.html file wants the javascript file from the admin folder, that does not exist. 
see:
`<script type="text/javascript" src="/admin/runtime~main.f8506bf7.js"></script><script type="text/javascript" src="/admin/main.1d0d97f1.chunk.js"></script></body>`

Might there be a webpack bug?

**Comment by buerobuettner** [comment]
ok - there are so many problems. i dont get it to work except that it runs locally.
It's faster to re code the little custom code with asp.net and use their straight forward process of deployment

**Comment by ZiedBeta** [comment]
Do you deploy manually  ? FYI here is what is being deployed on my web app 

![image](https://user-images.githubusercontent.com/6813975/76604345-e25e4d80-650e-11ea-8b4c-88319fb1a27f.png)

**Comment by buerobuettner** [comment]
i tried a lot - with manual deployment and the devops way.
Thank you @ZiedBeta for your efforts, but i switch to ASP.NET core now due to the lack of azure deployment docu.

**Comment by derrickmehaffy** [comment]
fixed via: https://github.com/strapi/strapi/pull/5571
