### ISSUE TITLE
error to rerun server,when set data to custom column names for better name attribute in response API 

### ISSUE THREAD

**Issue by hamedhossani** [strapi/strapi#3581]
Hello,
**strapi** have problem with _custom column names_  for better name attribute in response API?
I have **category** collection.
in my mind based relation database (sql server) i have [ id, title, idparent ] now i have  **category** collection with _relation_ [category has many categories]  in _noSql_ database.
my sample data is
```
noparent -> clothes
clothes -> mens
clothes -> womans
```
noparent means _idParent_ = _null_ in relation database.

My Problem is:
When i insert label ```parent``` for _category_ in input _custom column names_ in popup  Edit Categories Field -> Advanced Setting in _Content Type Builder_ , i can't run application! I have to remove label ```parent``` from category input box aftar that,Server runs.

ps:
 i have this data structure <pre>[
    {
        "id": 1,
        "title": "clothes",
        "product": null,
        "category": null,
        "created_at": 1562590600885,
        "updated_at": 1562590600973,
        "categories": [
            {
                "id": 2,
                "title": "mens",
                "product": null,
                "category": 1,
                "created_at": 1562590609937,
                "updated_at": 1562590648220
            },
            {
                "id": 3,
                "title": "womens",
                "product": null,
                "category": 1,
                "created_at": 1562590615573,
                "updated_at": 1562590653103
            }
        ]
    },
    {
        "id": 2,
        "title": "mens",
        "product": null,
        "category": {
            "id": 1,
            "title": "clothes",
            "product": null,
            "category": null,
            "created_at": 1562590600885,
            "updated_at": 1562590600973
        },
        "created_at": 1562590609937,
        "updated_at": 1562590648220,
        "categories": []
    },
    {
        "id": 3,
        "title": "womens",
        "product": null,
        "category": {
            "id": 1,
            "title": "clothes",
            "product": null,
            "category": null,
            "created_at": 1562590600885,
            "updated_at": 1562590600973
        },
        "created_at": 1562590615573,
        "updated_at": 1562590653103,
        "categories": []
    }
]</pre>

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
