### ISSUE TITLE
Issues Migrating with SQLite

### ISSUE THREAD

**Issue by sparticvs** [strapi/strapi#3583]
**Describe the bug**
Issue exists when attempting to migrate when using SQLite

**Steps to reproduce the behavior**
1. Using `strap@alpha.26.2` create a new project (quickstart works too)
2. Create the Admin Account and Login for the first time
3. Follow [migration guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html)
```
[Error: SQLITE_ERROR: Cannot add a column with non-constant default] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
[2019-06-25T21:11:57.625Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-25T21:11:57.626Z] error Error: SQLITE_ERROR: Cannot add a column with non-constant default
```

**Expected behavior**
strapi runs without an error on the database.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/847020/60836401-92ff9a80-a193-11e9-9d85-c54aadc30670.png)

**System**
- Node.js version: v12.1.0 (It's not a Node.js issue)
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.7 (Also confirmed with 3.0.0-beta.10)
- Database: SQLite3
- Operating system: MacOS 10.13

**Additional context**
The issue is with [this](https://github.com/strapi/strapi/blob/39542bda800c13ae4ef30ddc62ddb5792984596b/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js#L415) line in the code. As mentioned in the above screenshot, this can't be done to a table that has existing rows of data.

**Comment by sparticvs** [comment]
Also, from the [SQLite Schema](https://www.sqlite.org/lang_altertable.html):

> ### ALTER TABLE ADD COLUMN
> 
> The ADD COLUMN syntax is used to add a new column to an existing table. The new column is always appended to the end of the list of existing columns. The column-def rule defines the characteristics of the new column. The new column may take any of the forms permissible in a CREATE TABLE statement, with the following restrictions:
> 
> - The column may not have a PRIMARY KEY or UNIQUE constraint.
> - The column may not have a default value of CURRENT_TIME, CURRENT_DATE, CURRENT_TIMESTAMP, or an expression in parentheses.
> - If a NOT NULL constraint is specified, then the column must have a default value other than NULL.
> - If foreign key constraints are enabled and a column with a REFERENCES clause is added, the column must have a default value of NULL.

The second bullet above is relevant when an existing table. Ironically, this was considered a for the `created_at` column. See [here](https://github.com/strapi/strapi/blob/39542bda800c13ae4ef30ddc62ddb5792984596b/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js#L406)

**Comment by lauriejim** [comment]
Hello @sparticvs !
Can you give us more context about the thing you tried to do.
And the moment where the issue happen.
Because without more context, I'm currently not able to understand the issue.

**Comment by sparticvs** [comment]
I was following the [migration guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html). Previously on Alpha.26 and moving to Beta.7 - this was a couple weeks ago, just got back from vacation - and encountered an error that according to the migration guide shouldn't have happened. Sorry for the original post being a little...scatter-brained.

In short, I completed the entire migration guide prior to running `strapi start` and it led to the error shown in the screenshot about the default value. I enabled the verbose logging for KNEX and found the query that was causing the error.

**Comment by lareeth** [comment]
I also get this error when migrating from alpha to beta. Please advise if there is a manual change that can fix this for the time being, while a more permanent fix is being worked on

**Comment by sparticvs** [comment]
@lareeth My workaround was:
```bash
# sqlite3 pathToSqlite.db
sqlite3> ALTER TABLE `users-permissions_user` ADD COLUMN `updated_at` timestamp DEFAULT NULL;
sqlite3> .quit
```

I believe there is a more complicated way of solving this - something like:
1. Create new table with the proper column definitions
2. Copy all of the rows from the alpha table to the beta table
3. Delete the alpha tables
4. Rename beta table to be the right name

The above follows the SQLite3 specification.

**Comment by evgarthub** [comment]
Nice! Now it works!
