### ISSUE TITLE
Strapi is not recognized as internal or external command in development mode

### ISSUE THREAD

**Issue by AkashNan** [strapi/strapi#3586]
I am setting up strapi in development mode and followed the steps mentioned in the documentation [https://strapi.io/documentation/3.0.0-alpha.x/plugin-development/quick-start.html#development-environment-setup](url)

Steps completed as of now are 

1. git clone git@github.com:strapi/strapi.git
2. cd strapi
3. npm run setup

I did uninstall strapi global version before doing so as suggested by documentation as well as link below I am following

[https://jeanlescure.io/blog/customizing-strapi-admin-ui/](url)

When I am executing the next below step I am getting error as 

> 'strapi' is not recognized as an internal or external command operable program or batch file.

`strapi new myDevProject --dev `in my project folder outside strapi folder. 

As I understood from the documentation I need to uninstall any global install of strapi before trying to setup strapi in development mdoe. Now I do understand that I did not have strapi installed what why this error but how to get it resolve. 

I tried
1. Installing strapi on my project directory which I might say as local strapi install
2. navigated to and ran ` \node_modules\strapi>strapi.js new admin-dev --dev` still same error

What am I missing? Any help?

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: I am confused if removed global install where to install now to set up dev
- Operating system: windows 10

**Comment by lauriejim** [comment]
Hello!
The article was talking about the `alpha` version of Strapi. 
Here is the [migration guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html) from the `alpha` to `beta`

So all the content of this article is no longer valid.

If you want to customise plugins - I suggest you to follow [this documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions)
