### ISSUE TITLE
What's is the best practices for doing manipulation object of another model?

### ISSUE THREAD

**Issue by msmaromi** [strapi/strapi#3592]
**Describe the topic**
Here is my cases

```
Counter:
current_queue (Queue)
end_queue (Queue)

Queue:
counter (Counter)
number (integer)
prev_queue (Queue)
```

Case 1: creating a Queue instance (POST `/queues`). - I check `Counter.end_queue`, if null then start the number with 1, if exists then increment from `end_queue.number` - Create the queue based on the condition

Case 2: start the queue (PUT /counter) - if current_queue is null, then find queue which the `prev_queue` is `null` (first queue) - update the `current_queue`

**Your suggestions for this topic**
If I do it in django, I just import the other model then just do the query (manipulation). I think in javascript (strapi) this object manipulation should be more easy.

**Comment by lauriejim** [comment]
Hello @msimmer!
Thank you for your message but GitHub is not the good place for this kind of question.
Can you please open a question on StackOverflow (will just have to copy and paste)
We are trying the keep the GitHub issues for issues, some technical discussion...

**Comment by lauriejim** [comment]
Add the tag `strapi` in your question. It will appear in our Slack channel.

**Comment by msimmer** [comment]
^ Think this "@" was meant for @msmaromi

**Comment by msmaromi** [comment]
@lauriejim actually I already posted in stackoverflow, before I posted it here. anw, hope any expert view my question. thanks

**Comment by lauriejim** [comment]
Can you also post the link of your question here please.
It can help.

**Comment by msmaromi** [comment]
https://stackoverflow.com/questions/56955978/what-is-the-best-practices-to-manipulate-instance-using-strapi
