### ISSUE TITLE
Replace undefined on production environment

### ISSUE THREAD

**Issue by stephane-r** [strapi/strapi#3600]
Hey community,

**Describe the bug**
I try to run my fresh strapi app on production environment (latest strapi version), but i've this error after build : 

`TypeError: Cannot read property 'replace' of undefined`

**Screenshots**

![image](https://user-images.githubusercontent.com/4712791/61003076-584c5c80-a363-11e9-93d6-2908a1ea1fbf.png)

**System**
- Node.js version: 10.15.1
- Yarn version: 1.16.0
- Strapi version: latest
- Database: default
- Operating system: Ubuntu

**Additional context**
You can see my project on [this repo](https://github.com/stephane-r/Youtube-Audio-Player-Api).

Thank you community !

**Comment by alexandrebodin** [comment]
You are missing a param in your database.json file for production. 

{
  "defaultConnection": "default",
  "connections": {
    "default": {
      *"connector": "strapi-hook-bookshelf"*
      "settings": {
        "client": "sqlite",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "srv": "${process.env.DATABASE_SRV || false}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "ssl": "${process.env.DATABASE_SSL || false}"
      },
      "options": {
        "ssl": "${process.env.DATABASE_SSL || false}",
        "authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE || ''}"
      }
    }
  }
}

**Comment by stephane-r** [comment]
Thank you @alexandrebodin ! Work nice with **connector** :)

**Comment by gaurav1209** [comment]
@alexandrebodin could you please give the config for connecting to MySQL Db too? I am trying but it do not save anything in the database instead saves it in the data.db file in tmp folder. I am using it in production mode.

**Comment by alexandrebodin** [comment]
that should be the same just use mysql as client name.

**Comment by gaurav1209** [comment]
> that should be the same just use mysql as client name.

I tried that too, but it causes error in building the admin panel.

Here is the production database.json

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "localhost",
        "port": "3306",
        "srv": "false",
        "database": "'**'",
        "username": "'**'",
        "password": "'**'",
        "ssl": "false"
      },
      "options": {
        "ssl": "${process.env.DATABASE_SSL || false}",
        "authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE || ''}"
      }
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "localhost",
        "port": "3306",
        "database": "somename",
        "username": "someuser",
        "password": "somepass"
      },
      "options": {}
    }
  }
}
