### ISSUE TITLE
Proper way to check if client JWT token is still valid

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3601]
@lauriejim @alexandrebodin 

# Context
1. a given API user validates correctly with `POST /auth/local`
2. the client app saves JWT received.

The next day or so:

1. same client app somehow must check if stored JWT is still valid, to continue sending requests for authenticated controller actions

# How to
I was currently using the route `GET /users/me` to check for JWT validity; but sadly i've found that route loads the user with ALL its relations (in my case, a given User model has a `blogs` collection). Now i'm  just thinking that `ctx.state.user` on `strapi/packages/strapi-plugin-users-permissions/config/policies/permissions.js` is loading a User **with all its relation documents in memory** !!??

My doubts are basically:

1. Is that full User loading correct?
2. Is there some other built-in way to check if saved JWT is still valid? (i mean, not expired yet)

### Note

I 've tried @derrickmehaffy suggestion of putting `autoPopulate: false` on the User `blogs` relation, but it still loads the complete user.... i'm  thinking if somebody has more than one collection... `GET /users/me` then would load waaay lots more data......😉

**Comment by dominikg** [comment]
> Is there some other built-in way to check if saved JWT is still valid? (i mean, not expired yet)
Most jwt tokens contain the expiration date. Use jwt-decode to decode the token on the clientside and check it. see here for details: https://github.com/auth0/jwt-decode/issues/53

**Comment by dominikg** [comment]
@alexandrebodin 
invalid token responses need to be handled by the client anyways (obtain new token, resend request). Validating exp on the client side is merely an optimization where you skip one request that has a high chance to fail.

**Comment by jacargentina** [comment]
Mmmm, it is not only the JWT expiration, but that user currently exists, is active, etc! So i think a check against the remote is needed anyway.

I mean:
1- Client side check JWT is not expired. YES.
**2- Then check if JWT token is still for an active user on the server.** YES/NO possibly

**Comment by lauriejim** [comment]
Okay clear.
For your need I suggest you to create in your `./extensions/users-permissions/config` folder a new `routes.json` file.

— `./extensions/users-permissions/config/routes.json`
```
{
  "routes": [{
    "method": "POST",
    "path": "/token/decrypt",
    "handler": "Auth.tokenDecrypt",
    "config": {
      "policies": [],
      "prefix": false
    }
  }]
}
```
Then you will have to create the `Auth` controller and write the function that will decrypt the token.

— `./extensions/users-permissions/controllers/Auth.js`
```
module.exports = {
  tokenDecrypt: async function(ctx) {
    // get token froml the POST request
    const {token} = ctx.request.body;

    // check toek requirement
    if (!token) {
      return ctx.badRequest('`token` param is missing')
    }

    try {
      // decrypt the jwt
      const obj = await strapi.plugins[
        'users-permissions'
      ].services.jwt.verify(token);

      // send the decrypted object
      return obj;
    } catch (err) {
      // if the token is not a valid token it will throw and error
      return ctx.badRequest(err.toString());
    }
  }
};
```
It's a POST request so you will have to send the token in the `body` of your request.
```
{
  "token": "...theJWT..."
}
```

Then you will have to allow this new route as a Public route.
So you have to go in your `admin panel > users permissions > public > users permission` and allow `tokendecrypt` function.

`💡note` you will note have to sent the `Authorization` header for this request.

**Comment by dominikg** [comment]
@lauriejim 
Your service uses the server-secret to decode the token and return the decoded content and it isn't authenticated. Could this pose a security issue?

If you just want to know if a stored token is still accepted as valid authentication by the server wouldn't it be enough to just have an authenticated route that returns a 204 with no cache headers?

And even such a route isn't necessary because the only time you need a valid token is when you want to communicate with a route that requires authentication. In that case you can just send the request and handle the authentication error response.
And you need that handler anyways because there is no guarantee that the token is valid in the next request after you checked it on a special route.

**Comment by alexandrebodin** [comment]
Hi many questions there:

- There are no security issues as the token payload is already decodable with the secret. Using it just makes sure it is valid from the server standpoint which is a requirement to verify it anyway. the data this is returned is still just the payload.

- You can do a route that just returns a 204 for sure. THis is only en example ;) You could also return a new token with. Up to you there

- Indeed you could only handle errors on normal api calls and this would work. For some usecase though you might want to check this before doing any other call and display a specific screen or sth. It is almost more of a UX question there.

**Comment by lauriejim** [comment]
Yap @alexandrebodin !

@dominikg The most interesting part of the code here is to show how create a route, a controller, call the service that verify the token.
The response of the route, in fact, we don't care. It's not important for the example.
As @alexandrebodin said, you just have to replace the response and ta da, it's ok.

Have to share concept to let you customize what you want by your own.

**Comment by jeremyrajan** [comment]
This really helped! 🙂 🎉. Thanks a lot! Should this be part of `JWT validation` docs? 🙂 @lauriejim

**Comment by lauriejim** [comment]
Your welcome, feel free to submit a PR to this guide to improve it.
