### ISSUE TITLE
use hashids

### ISSUE THREAD

**Issue by fouber** [strapi/strapi#3614]
Strapi use ``id`` field to uiquely identifying object, and it's a increasing number one by one. This is a data security issue, sometimes developers do not want data lists can be enumerated in id order. For example, if someone signed up for my website, and the user will know how many registered users my site has by id field.

In this case, I strongly recommend hashing the id field by [hashids](https://www.npmjs.com/package/hashids) or any other packages with similar functionality.

**Comment by absolux** [comment]
Or we can use a custom number as basis for the incremented identifier.
For example, we can use in your case `154758` instead of starting with `1`.
Here is an example for PostgreSQL.

```sql
# Create the table
CREATE TABLE example (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50)
);

# Change the initial value
ALTER SEQUENCE example_id_seq START WITH 154758;
```

[More details](http://www.sqlines.com/postgresql/datatypes/serial)

**Comment by lauriejim** [comment]
Here is also a issue related to this topic https://github.com/strapi/strapi/issues/1826
