### ISSUE TITLE
Field name mapping

### ISSUE THREAD

**Issue by hellsan631** [strapi/strapi#3615]
I would love to be able to map existing database fields to differently named fields within the definition of the attributes.

For example, using a database with **snake_case** field names and, without having to rename everything within the database, use **camelCase** within my code/graphQL queries.

## Suggestions
There should be a field within the model definitions file that allows me to specify a different field name that maps to a field in the database.

### Code
_SomeModel.settings.json_
```json
"attributes": {
    "coverageCode": {
        "type": "string",
        "from": "coverage_code"
    }
}
```

## Additional Context
When building a complex application, or when extending an existing application, data naming conventions are the first to get coupled. Renaming everything is sometimes not an option. It's much easier to allow each language to use it's ideal established conventions.

For example, if a system uses a lot of different microservices that rely on mysql & postgres data. If I wanted to integrate a quick React front-end, I would have to use snake_case, instead of the established naming convention of my language of choice.

**Comment by lionhive** [comment]
We're looking for a solution on this as well.

**Comment by lauriejim** [comment]
Hello! Thank you for this topic.
I'm not able to find it again, but I already see an issue or on an other support a message about this feature.

@Aurelsicoko What do you think about this?

I understand the need but for us it's not a priority.
The topic is clear I think we can add it in ProductBoard? @Aurelsicoko

**Comment by Aurelsicoko** [comment]
Yes, I will add it to ProductBoard but like you said it is not of our priorities. I would love to see the community making a PR for this. But, please open an RFC before submitting a PR to discuss the naming and how it could look like in our model definition.

**Comment by derrickmehaffy** [comment]
for reference on making an RFC: https://github.com/strapi/rfcs

**Comment by Aurelsicoko** [comment]
@derrickmehaffy Can we close the issue?

**Comment by derrickmehaffy** [comment]
@Aurelsicoko got a link to the productboard before we close it?

**Comment by Aurelsicoko** [comment]
No, because like I said it is not our priority. I cannot display everything on the public roadmap 🤷‍♂️. However, be sure that I already added into and classified the issue on the roadmap.

**Comment by mengqing** [comment]
In desperate need of this feature, does anyone know how / any directions I would go about implementing this?

**Comment by hellsan631** [comment]
> In desperate need of this feature, does anyone know how / any directions I would go about implementing this?

If your using graphQL, then you can use the field rename feature. Assuming an object `person`, with a field of `first_name`, we can use the following query to rename this to `firstName`:

```graphql
people {
  firstName: first_name
}
```

You can also use this for the query names themselves:

```graphql
carDealer: car_dealers (name: "Some Name") {
  modelNo: model_number
}
```

**Comment by mengqing** [comment]
@hellsan631 Thanks for the reply,  however that's not what I'm after. I thought the purpose of this issue is to be able to map an attribute to another attribute.

Eg: I have an existing field in the table named 'reset_password_token', however with the users-permissions plugin, the attribute is named 'resetPasswordToken'. I want to re-use the existing field in the table, but I also want to reference the attribute as 'resetPasswordToken' throughout the code base

**Comment by douglasjunior** [comment]
How about the "Custom column names" on the "ADVANCED SETTINGS"?

As I mentioned here https://github.com/strapi/strapi/issues/4616#issuecomment-704480137 this config seems to be ignored.
