### ISSUE TITLE
When will admin panel integration work for plugins?

### ISSUE THREAD

**Issue by mastix** [strapi/strapi#3616]
Hi guys,

I'm currently looking into the creation of a plugin for strapi and I was wondering when the admin panel integration will work (and be documented).

What does this limitation mean exactly? Does it mean that I'm currently not able to create plugin admin UIs?

Currently the documentation says:

> The admin panel integration is currently not available. You can still add backend features.

Is there any timeline? Version?

Thanks in advance,

Sascha

**Comment by alexandrebodin** [comment]
Hi @mastix,

Right now you can develop a plugin locally with an admin UI by installing it via npm in two ways:

- Linking it through `npm link` or `yarn link` and adding it to your package.json dependencies
- Adding it to your package.json dependencies using a file path:
```json
{
  "dependencies": {
    "my-plugin": "file://absolute-path-to-my-plugin"
  }
}
```

Once this is done you can npm run build and the package will be built. Althoutgh this will work we haven't enable the dev mode so this will be quite painfull to rebuild on every change. We will be improving this in the future but isn't the top prirotiy right now.

What is no supported however is the `admin` folder in a local plugin located in the `plugins folder`.

Hope this helped
