### ISSUE TITLE
AWS PM2 Config Failure

### ISSUE THREAD

**Issue by ruben00001** [strapi/strapi#3619]
**Describe the bug**

On attempting to deploy to AWS pm2 fails to start with this error:

```
[PM2][ERROR] File ecosystem.config.js malformated
/home/ubuntu/ecosystem.config.js:5
    script: 'server.js',
    ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/ubuntu/.npm-global/lib/node_modules/pm2/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/ubuntu/.npm-global/lib/node_modules/pm2/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/home/ubuntu/.npm-global/lib/node_modules/pm2/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.Common.parseConfig (/home/ubuntu/.npm-global/lib/node_modules/pm2/lib/Common.js:294:12)
```

**Steps to reproduce the behavior**

I modified my ecosystem.config.js to:

```
module.exports = {
  apps : [{
    name: 'strapi',
    cwd: '/home/ubuntu/[MY STRAPI PROJECT FOLDER NAME]'
    script: 'server.js',
    env: {
      NODE_ENV: 'production',
      DATABASE_HOST: '[MY RDS ENDPOINT]',
      DATABASE_PORT: '5432',
      DATABASE_NAME: 'strapi',
      DATABASE_USERNAME: 'postgres',
      DATABASE_PASSWORD: '[MY PASSWORD]',
    },
  }],
};
```

**Expected behavior**
PM2 to launch and to be able to access my Strapi project.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: AWS
- Operating system: Ubuntu 18.04

**Comment by lauriejim** [comment]
Did you follow [this documentation 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws) ?

**Comment by ruben00001** [comment]
> Did you follow [this documentation 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws) ?

I should have made that clear sorry - I followed the alpha version of that guide (https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#amazon-aws). 

I might have deviated where it says "ensure you are logged in as a non-root user" in the guide. I wasn't sure what was meant by that so I just continued as I was. Also the guide says to replace the boilerplate content of ecosystem.config.js with:

```
module.exports = {
  apps : [{
    name: 'strapi',
    cwd: '/home/ubuntu/path-to/your-strapi-root-folder'
    script: 'server.js',
    env: {
      NODE_ENV: 'production',
      DATABASE_HOST: 'your-unique-url.rds.amazonaws.com', // database Endpoint under 'Connectivity & Security' tab
      DATABASE_PORT: '5432',
      DATABASE_NAME: 'strapi',  // DB name under 'Configuration' tab
      DATABASE_USERNAME: 'postgres', // default username
      DATABASE_PASSWORD: 'Password',
    },
  }],
};
```
I'm not sure if the 'cwd' value I put in is correct (see above) or if I should have changed the value for 'DATABASE_PASSWORD' to my password as there's no instruction to do that.

**Comment by davidkartuzinski** [comment]
Try adding a `,` after `cwd: '/home/ubuntu/[MY STRAPI PROJECT FOLDER NAME]'` - it looks like you're missing a comma.

**Comment by ruben00001** [comment]
> Try adding a `,` after `cwd: '/home/ubuntu/[MY STRAPI PROJECT FOLDER NAME]'` - it looks like you're missing a comma.

Thanks! You're right and that's embarrassing for me... I'm a little rusty ; )

**Comment by Turkyden** [comment]
> Try adding a `,` after `cwd: '/home/ubuntu/[MY STRAPI PROJECT FOLDER NAME]'` - it looks like you're missing a comma.

Good Jobs, Haha!
