### ISSUE TITLE
Unable to start strapi in production mode

### ISSUE THREAD

**Issue by sidsaxena0** [strapi/strapi#3623]
**Describe the bug**
Hi today i freshly installed strapi beta on one of my linux service. All worked fine but when i tried starting server in production mode using this command : NODE_ENV=production npm run start
It gave me error below is the log : 

```
[2019-07-16T12:18:17.087Z] debug ⛔️ Server wasn't able to start properly.
[2019-07-16T12:18:17.089Z] error TypeError: Cannot read property 'replace' of undefined
    at module.exports (/opt/dogspedia/node_modules/strapi/lib/core/bootstrap.js:240:44)
    at Strapi.load (/opt/dogspedia/node_modules/strapi/lib/Strapi.js:283:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dogspedia@0.1.0 start: `strapi start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dogspedia@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-16T12_18_17_102Z-debug.log
```

**Steps to reproduce the behavior**
1. Install strapi
2. Create model
3. Build admin using NODE_ENV=production npm run build
3. Start in production mode using command NODE_ENV=production npm run start
4. You should get error saying error TypeError: Cannot read property 'replace' of undefined

**Expected behavior**
It should started normally without giving any of such error

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.13
- Database: mongoDb
- Operating system: linux ubuntu 18.10

**Comment by derrickmehaffy** [comment]
@alexandrebodin correct me if I'm wrong but we no longer need to define the `NODE_ENV` for building now? (I know I certainly haven't been and my proxy settings are different for each environment)

**Comment by alexandrebodin** [comment]
Hi.

You are missing the parameter connector in your database config in the `config/envrionments/production/database.json` 

Look at this issue this should fix it for you https://github.com/strapi/strapi/issues/3600

CLosing :)
