### ISSUE TITLE
Filter referenced objects Mongo

### ISSUE THREAD

**Issue by georgeMuraveiAlkh** [strapi/strapi#3626]
**Describe the bug**
Can't filter nested referenced object by query. With code example below strapi returns Objects which matched query and all other objects without loaded ```nested``` property. 
```
{   // parent
    _id: ObjectId('id'),
    nested: ObjectId('id')
{
{ //nested
    _id: ObjectId('id'),
    info: {
           first: 'someval',
           last: 'someval',
    {
{

fetch: (params) => {
    let convertedParams = strapi.utils.models.convertParams('user', params);
    return strapi.query('user')
      .find(convertedParams, [{
        path: 'nested',
        match: {
          $or: [
               {'info.first': {'$regex': params.name, $options: 'i'}}, 
               {'info.last': {'$regex': params.name, $options: 'i'}}
           ]
        }
      }])
      .then((users) => {
        return users;
      });
}
```

After that I'm getting:
```
// params.name = 'somev'

[{  
    _id: ObjectId('id1'),
    nested: {
        _id: ObjectId('id10'),
        info: {
               first: 'someval',
               last: 'someval',
        {
},
{  
    _id: ObjectId('id2'),
    nested: null // !!!!!!! value in 'first' and 'last' fields not matching regex and object not pulls from db
},
{  
    _id: ObjectId('id3'),
    nested: null // !!!!!!! value in 'first' and 'last' fields not matching regex and object not pulls from db
}
... ]

```
Is there a way to do this? And is it possible to pass pure query into Mongoose (without any changes from strapi) or some how use Mongoose functions (I need ```aggregated``` to do this properly)?

**System**
- Node.js version: 10.16
- NPM version: 9.6.0
- Strapi version: 3.0.0-alpha.20
- Database: MongoDB
- Operating system: Mojave

**Comment by lauriejim** [comment]
Hello!
For your kind of need I suggest you to use this `strapi.plugins['users-permissions'].models.user`
In this variable you will have access to the Mongoose instance of the User model.
Feel free to use Mongoose syntax to query what you want.
