### ISSUE TITLE
when I click save after create content type, error occur

### ISSUE THREAD

**Issue by mensafung** [strapi/strapi#3629]
**Describe the bug**

1. Go to content-type-builder
2. Click on 'save' after create content and field
3. See "error occur"

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-alpha.26.2
- Database: MongoDb
- Operating system: Ubuntu 18.04 LTS

**Additional context**

**Comment by derrickmehaffy** [comment]
@mensafung we need an example of the error such as screenshots or additional information.
