### ISSUE TITLE
Installing with yarn doesn't work

### ISSUE THREAD

**Issue by svallory** [strapi/strapi#363]
Not that it should, but it would be nice to have a warning in the "Get started" part of the doc

**yarn version**: 1.3.2

**Node.js version**: 8.9.1
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.6.7
**Operating system**: OSX 10.13.1

**Comment by Aurelsicoko** [comment]
@svallory Thanks for reporting this issue! Can you give us some log details, please?

**Comment by svallory** [comment]
@Aurelsicoko What I think is happening is that post install scripts don't run. Then, when trying to use strapi it starts complaining about missing modules. I added each one manually until I hit another error, just I don't remember what.

**Comment by svallory** [comment]
I went ahead and installed using npm, so I don't have the logs anymore :/
