### ISSUE TITLE
setting _limit=-1 does not work

### ISSUE THREAD

**Issue by hezzze** [strapi/strapi#3630]
**Describe the bug**
Setting `_limit=-1` does not get me the full data set as described by the documentation https://strapi.io/documentation/3.0.0-alpha.x/guides/filters.html#available-operators

**Steps to reproduce the behavior**
1. Send a request like `/items?_limit=-1`
2. the return data set only has one record

**Expected behavior**
it should return the full data set which is more than one records

**System**
- Node.js version: node v10
- NPM version: v6.9
- Strapi version: v3.0.0-alpha.23
- Database: v4.0.4
- Operating system: masOS mojave

**Comment by lauriejim** [comment]
Hello! This option has been added in `alpha.26`.
We are now in `beta` version.
I HIGHLY suggest you to migrate your app on the `beta` version of strapi.
To do that follow migration guide here https://strapi.io/documentation/3.0.0-beta.x/migration-guide/

**Comment by hezzze** [comment]
@lauriejim  Thanks, will make plan for that
