### ISSUE TITLE
Infinite loading after creating a plugin

### ISSUE THREAD

**Issue by L-u-n-a** [strapi/strapi#3631]
Hello everyone,

**The problem**

My admin panel is stuck in infinite loading after generating a plugin.

**Information:**
Strapi version: v3.0.0-beta.13
Nodejs version: 10.16.0
NPM version: 6.9.0
OS: Windows 10

**Steps to reproduce the problem**

I installed Strapi using: `strapi new my-project --quickstart`

The admin panel starts just fine.

I then generated a plugin using: `strapi generate:plugin my-plugin`

The admin panel is now stuck in infinite loading. The console is giving me the error:
`Error: only one instance of babel-polyfill is allowed`

If I remove the newly generated plugin the Admin panel once again starts.

**What is the expected behavior?**

The plugin is generated and the Admin panel still works.

**Comment by lauriejim** [comment]
Hello! I'm not able to reproduce your issue.
I installed `3.0.0-beta.13` version and generated a new app like you did.
And then generate a plugin by copy/past your command and I haven't any error.

Did you do something else than just generate a new plugin?
Did you use the `alpha` globally before or you have a fresh beta global version installed on your computer.

**Comment by L-u-n-a** [comment]
Hello Lauriejim,

I have fixed the issue by removing and reinstalling Strapi using the `npm install strapi@beta -g` command (the same command I used yestruday).

The globally installed version of Strapi was and is 3.0.0-beta.13.

I'm not sure what caused the error, and I'm not able to reproduce it again either. I didn't do anything other then install Strapi, generate a project and generate a plugin.
