### ISSUE TITLE
One-to-many relation causes unnecessary updates on linked entry

### ISSUE THREAD

**Issue by wysher** [strapi/strapi#3634]
**Describe the bug**
I'm using sqlite database and have some relation fields + havily use lifecycle callback methods (e.g. for creating google calendar events or generate dotpay payments).

strange thing is happening when i set one-to-many relation. Lets assume that I have user (parent) with many articles (children).

When I update User, Article lifecycle methods are called TWICE ([before/after] save, update), and then update on User entry is called.

I checked this for another relations and it works fine (even for many-to-many).

**Steps to reproduce the behavior**
1. Create one-to-many relation
2. console.log lifecycle methods

**Expected behavior**
Update is called only for parent entry.

**System**
- Node.js version: 10
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.13
- Database: sqlite
- Operating system: Linux

**Comment by lauriejim** [comment]
This is not due to this type of relations.
Please check this issue https://github.com/strapi/strapi/issues/1443
I close this one. All is said in this issue.

**Comment by lauriejim** [comment]
In any case, thank you for this message.
