### ISSUE TITLE
Infinite loading when I trying to Add New content after connected tMongoDBAtlas

### ISSUE THREAD

**Issue by keshibat** [strapi/strapi#3635]
**Describe the bug**

My admin panel is stuck in infinite loading when I trying to Add New content.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.9
- Database: mongoDBAtlas
- Operating system: Mac 10.13.6

**Steps to reproduce the behavior**

Following this step https://strapi.io/documentation/3.0.0-alpha.x/guides/databases.html#sqlite-installation
I installed Strapi using: strapi new my-project selecting Custom (manual settings)

Connected to MongoDB Atlas
I am able to create Content Type Builder but not able to Add New Content.
It goes infinite loop.

**Expected behavior**
I shold be able to New Entry and be able to save it.

**Screenshots**
![Imgur](https://i.imgur.com/D0aUF32.png)
![Imgur](https://i.imgur.com/ZZYXQ9j.png)
![Imgur](https://i.imgur.com/DaUlEEY.png)

**Code snippets**
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "cluster1-shard-00-00-1cmhp.gcp.mongodb.net:27017,cluster1-shard-00-01-1cmhp.gcp.mongodb.net:27017,cluster1-shard-00-02-1cmhp.gcp.mongodb.net:27017/test?ssl=true&replicaSet=Cluster1-shard-0&authSource=admin&retryWrites=true",
        "port": 27017,
        "database": "test",
        "username": "XXX",
        "password": "XXX"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**Additional context**

**Comment by davidkartuzinski** [comment]
Can you please try follow the directions for the Beta release.  The link is on top of the documentation. What you linked to is for the Alpha version of Strapi.

**Comment by davidkartuzinski** [comment]
@keshibat - Is there a reason you are not using the more modern and supported version of Strapi? Strapi is now in Beta.

There is a current pull request submitted on updated documentation for MongoAtlas, https://github.com/strapi/strapi/pull/3624/.

Meanwhile, you can follow the Beta instructions here: https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#mongodb-installation - but below are some changes that will soon be merged:

==============

Starting from Step 2 in the docs above:

==============

2. Next, click on the `Database Access` in the left menu (under `Overview`):
- Click the green `+ ADD NEW USER` button:
  - Enter a `username`.
  - Enter a `password`.
  - Under `User Privileges` ensure **`Read and write to any database`** is selected. Then click `Add User` to save.

3. Then `whitelist` your IP address. Click into `Network Access`, under `Security` in the left menu:
- Click the green `+ ADD IP ADDRESS`

  - Click `ADD CURRENT IP ADDRESS` or **manually** enter in an IP address to `whitelist`.
  - Leave a comment to label this IP Address. E.g. `Office`.
  - Then click the green `Confirm` button.
  - Delete the `0.0.0.0/0` configuration after testing the connection.
  **NOTE:** If for any reason you need to test the configuration or other aspect of your connection to the database, you may want to set back the `Allow Access from Anywhere`. Follow this steps:
  - Click the green `+ ADD IP ADDRESS`
    - Next add `0.0.0.0/0` in the `Whitelist Entry`. **Note:** In permanent projects you would configure this with the appropriate IP addresses.
    - Leave a comment to label this IP Address. E.g. `Anywhere`.
    - Click `Confirm`. Then wait until the status turns from `Pending` to `Active`.
  **OPTIONAL:** If you are serving you Strapi project from a known IP Address then follow the following steps to `allow Network Access`:
  - **Manually** enter in an IP address to `whitelist`, for your Strapi server.
  - Leave a comment to label this IP Address. E.g. `Heroku Server`
  - Then click the green `Confirm` button.
4. Retrieve database credentials
MongoDB Atlas automatically exposes the database credentials into a single environment variable accessible by your app. To locate it, follow these steps:
- Under `Atlas` in the left-hand, click on `Clusters`. This should take you to your `cluster`. Next, click `CONNECT` and then `Connect Your Application`.
- Under `1. Choose your driver version`, select **DRIVER** as `Node.js` and **VERSION** as `2.2.12 or later`. **IMPORTANT:** You **must** use `Version: 2.2.12 or later`.
- This should show a **Connection String Only** similar to this:
`mongodb://paulbocuse:<password>@strapi-heroku-shard-00-00-o777o.mongodb.net:27017,strapi-heroku-shard-00-01-o606o.mongodb.net:27017,strapi-heroku-shard-00-02-o606o.mongodb.net:27017/test?ssl=true&replicaSet=Strapi-Heroku-shard-0&authSource=admin&retryWrites=true&w=majority`
- You are interested in everything **BETWEEN** the `@` symbol and `&w=majority`. This is your database **"host":** variable. So in this case:
**NOT THIS PART:** `mongodb://paulbocuse:<password>@`
**JUST THIS PART:**

`strapi-heroku-shard-00-00-o777o.mongodb.net:27017,strapi-heroku-shard-00-01-o606o.mongodb.net:27017,strapi-heroku-shard-00-02-o606o.mongodb.net:27017/test?ssl=true&replicaSet=Strapi-Heroku-shard-0&authSource=admin&retryWrites=true`

**NOT THIS PART:** `&w=majority`

::: warning WARNING
When you copy the URL as above, ensure to delete the `&w=majority` after `...=true`. If you leave this in the string it will **not** connect.
:::

- You created earlier a `username` and `password`, within your **MongoDB Atlas** account for connecting to databases. These are the **"username":** and **"password:"** variables needed to configure your project and connect to MongoDB Atlas.

5. Update and replace your existing `/database.json` config file for the appropriate environment (development|production).

Replace the contents of `/database.json` with the following AND replace the **"host":**, **"username"**: and **"password:"** with the credentials to your account:

`Path: ./config/environments/(development|production)/database.json`.

@@ -276,12 +300,10 @@ Replace the contents of `database.json` with the following:
```
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "host": "cluster0-shard-00-00-y8imj.mongodb.net:27017,cluster0-shard-00-01-y8imj.mongodb.net:27017,cluster0-shard-00-02-y8imj.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true",
        "port": 27017,
        "username": "[THE USERNAME YOU CREATED ABOVE IN THE MONGODB ATLAS ACCOUNT]",
        "password": "[THE PASSWORD YOU CREATED ABOVE IN THE MONGODB ATLAS ACCOUNT]"
      },
      "options": {
        "ssl": true
```

You are now ready use Strapi locally or to deploy your project to an external hosting provider and use MongoDB Atlas as your database server.


==================

These instructions should work also for Strapi Alpha.  But I **HIGHLY** encourage and recommend you move to the Beta version of Strapi as soon as possible.

**Comment by keshibat** [comment]
@davidkartuzinski 
When I downloaded Strapi, the version was 3.0.0-beta.9, I didn't upgrade since then. 
I updated 3.0.0-beta.13 and it works!!    
Strapi version: 3.0.0-beta.9 => 3.0.0-beta.13

**Comment by davidkartuzinski** [comment]
@keshibat Great to hear.
