### ISSUE TITLE
Error: Cannot find module 'whatwg-fetch'

### ISSUE THREAD

**Issue by derrekmc** [strapi/strapi#3643]
After `strapi new appname` is done installing dependencies, I get an `Error: Cannot find module 'whatwg-fetch'` and the application never starts.

**Comment by soupette** [comment]
@derrekmc can you try to reinstall the dependencies and see if it works?

(Also, can you please follow the issue template?)

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
