### ISSUE TITLE
Admin panel still welcome page

### ISSUE THREAD

**Issue by kwzm** [strapi/strapi#3644]
**Describe the bug**
I don't know what I did that caused the admin panel could not be displayed after running `npm run dev` , which is still the welcome page.

**Steps to reproduce the behavior**
I'm not sure how this bug came about.
All I remember is that I wanted to package admin panel and make some changes, execute `npm run build` and that's it.

**Expected behavior**
Admin panel show.

**Screenshots**
![捕获](https://user-images.githubusercontent.com/16114101/61519049-8efa3500-aa3d-11e9-8b4a-bb24832b7cda.PNG)

**Code snippets**
None.

**System**
- Node.js version: 10.13.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.13
- Database: SQLite
- Operating system: win7

**Additional context**
None

**Comment by derrickmehaffy** [comment]
It would appear that your adminUI did not rebuild properly.

**Comment by petehamling** [comment]
I experienced the same issue.  `strapi new ...` failed to run to completion while installing the project dependancies.

I rectified it by entering the project directory and running `npm install; npm run build`

**Comment by llavre** [comment]
Got same problem. Manually install of dependencies and rebuild helped as mentioned at https://github.com/strapi/strapi/issues/3644#issuecomment-513176950.
