### ISSUE TITLE
confusion over amountLimit in graphql queries

### ISSUE THREAD

**Issue by aalasolutions** [strapi/strapi#3648]
**Describe the bug**
I might be wrong :D but i am not understanding the usage of `amountLimit` is its results are unexpected

**Steps to reproduce the behavior**
1. Change amountLimit to 10
2. Go to graphql http://localhost:1337/graphql
3. make a query without limit
4. It returned me 100 records, 

**Expected behavior**
If I set `amountLimit` to 10, and if I dont set limit, it should only return me 10 records, 

**Current configuration**
```json
{
  "endpoint": "/graphql",
  "tracing": false,
  "shadowCRUD": true,
  "playgroundAlways": false,
  "depthLimit": 7,
  "amountLimit": 10
}
```

As shown there is 100 records, I think this is not expected behaviour it should only return me 10 results
![image](https://user-images.githubusercontent.com/1493178/61532157-632d7e00-aa42-11e9-8cb8-9f819db9e491.png)

With `limit: -1` i get 10 records only, for me this is unexpected behaviour, as I dont want to set any limit and want to get all the records. I might be wrong as user can ask for thousands of records and Strapi dosnt want to keep system busy so `amountLimit` is a hard limit which can not be changed .
![image](https://user-images.githubusercontent.com/1493178/61532236-a687ec80-aa42-11e9-915a-ebd2543b05f5.png)

With `limit: 15` i get 10 records only. May be this is right
![image](https://user-images.githubusercontent.com/1493178/61532312-de8f2f80-aa42-11e9-9b93-8e6c144e46e3.png)

**System**
- Node.js version: v10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.13
- Database: MySQL
- Operating system: MacOS Mojave 10.14.4

**Comment by derrickmehaffy** [comment]
Wasn't able to reproduce over 100? (I have mine set to 1000) I requested 2000 as a limit and was only returned my maximum. Will need to test on lower limits

**Comment by aalasolutions** [comment]
I have set limit to 10, and while query I didnt passed any limit, and I got 100

**Comment by derrickmehaffy** [comment]
code related: https://github.com/strapi/strapi/blob/117656c05f93f1d6d3bde868e149465136a680cb/packages/strapi-plugin-graphql/services/Query.js#L46-L66

**Comment by aalasolutions** [comment]
Hmm, saw the code. What if I give access to external parties and I am building SaaS, and have set my `amountLimit` to 50, and I dont want any one to access more then 50 records in their request. They would still get 100. Which is not desired result. Or is it?...

**Comment by derrickmehaffy** [comment]
Based on that code it shouldn't meaning the issue is somewhere else, maybe the attribute isn't being overridden?

**Comment by derrickmehaffy** [comment]
Can you try starting your strapi with `strapi console` and enter this: `strapi.plugins.graphql.config.amountLimit` that should give you the limit based on the config

**Comment by aalasolutions** [comment]
It did returned me the proper value, I have set it to 5. Confirmed it again by restarting strapi console that I get five in there by calling the `strapi.plugins.graphql.config.amountLimit` and I got 5. Then went to graphql on browser and sent the request without limit and I got 100 records. 

I saw the code again and if limit is not defined it is just passing the params back

I think it should update limit and then send the params back.

```js
amountLimiting: (params = {}) => {
    const { amountLimit } = strapi.plugins.graphql.config;

    if (!params.limit) return params.limit = amountLimit;

    if (params.limit === -1) {
      params.limit = amountLimit;
    } else if (params.limit < 0) {
      params.limit = 0;
    } else if (params.limit > amountLimit) {
      params.limit = amountLimit;
    }

    return params;
  },
```

of why not just like following

```js
amountLimiting: (params = {}) => {
    const { amountLimit } = strapi.plugins.graphql.config;

    if(!amountLimit) return params; // not sure if this is needed

    if (!params.limit || params.limit === -1 || params.limit > amountLimit) { // combined lines which return same
      params.limit = amountLimit;
    } else if (params.limit < 0) {
      params.limit = 0;
    } 

    return params;
  },
```

**Comment by derrickmehaffy** [comment]
@aalasolutions Sure please do submit a PR :smiley:
