### ISSUE TITLE
I Have a Content Type That Shouldn't Exist

### ISSUE THREAD

**Issue by darrylmorley** [strapi/strapi#3649]
**Describe the topic**
In my admin page I am seeing a content type that shouldn't exist, also it can not be removed?
The 'guns-stock' content type is not in my db and can not be deleted from the content types screen.

**Your suggestions for this topic**

**Screenshots**
![strapi](https://user-images.githubusercontent.com/20406137/61536229-163ead00-aa2c-11e9-97da-5c981f2056a3.PNG)
![content types](https://user-images.githubusercontent.com/20406137/61536391-759cbd00-aa2c-11e9-93ce-101db537618e.PNG)

**Code snippets**
If applicable, add code samples to help explain your points.

**Additional context**
Admittedly it's not the end of the world, but I would like it not to be there :) How can I remove this?

**Comment by derrickmehaffy** [comment]
@darrylmorley delete the following entry in your database `core_store` => `plugin_content-manager_schema` 

It's a known issue that is being worked on. Note you don't need to purge the whole core_store just that entry. After you have purged it restart Strapi and that entry should disappear.

**Comment by darrylmorley** [comment]
Great thanks!
