### ISSUE TITLE
sql database using strapi-bookshelf not configured on project generation.

### ISSUE THREAD

**Issue by ozymandias547** [strapi/strapi#365]
node: v8.7.0
npm: 5.4.2
3.0.0-alpha.7
MacOS Sierra

I'm attempting to use strapi with strapi-bookshelf and a mysql configuration:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "localhost",
        "port": 3306,
        "username": "root",
        "password": "",
        "database": "strapi-dev"
      },
      "options": {}
    }
  }
}
```

I have created the `strapi-dev` database, but when starting up strapi, it doesn't create a users table or any other table, so I get this error:

`ER_NO_SUCH_TABLE: Table 'strapi-dev.user' doesn't exist`

Is there a "seed" database I can use?

**Comment by lauriejim** [comment]
Hello, you have to create manually your user table.

```
CREATE TABLE "user" (
    id integer NOT NULL,
    username text,
    email text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    role text,
    provider text,
    "resetPasswordToken" text,
    password text
);
```

We are working to improve the user experience with SQL databases to make it easier to use.

If you want fake data in your application, you can create data using content manager plugin in some clicks.

**Comment by dyunggertrude** [comment]
npm:5.6.0
node:v8.9.3
windows 10

Hello 
I create table test in database Mysql and in 'Content Type Builder' menu !!
I create  new column on mySQL database with strapi
Saving Model ok
after that in shell windows i have these messages
DEBUG : GET /content-manager/explorer/test/count?source=content-manager (4 ms)
DEBUG : GET /content-manager/explorer/test/count?source=content-manager (3 ms)
ERROR : The model user can't be found.
DEBUG : GET /content-manager/explorer/user?skip=0&limit=20&sort=id&source=content-manager (2 ms)
ERROR : The model user can't be found.
DEBUG (14680 on PC-DE-DANIEL): GET /content-manager/explorer/user/count?source=content-(3 ms)

**Comment by lauriejim** [comment]
Hi @dyunggertrude, thank you for this report. It will be fix in `strapi@aplha.7.2` today or monday.
But if you want, you just have to replace `source` url attribute by `users-permissions` when you try to list your users in the content manager.

**Comment by lauriejim** [comment]
Fix in this commit https://github.com/strapi/strapi/pull/381/commits/5b542cff2059b7a68fcceab638436e4684be34d7
