### ISSUE TITLE
How to get user Id from GraphQL ?

### ISSUE THREAD

**Issue by stephane-r** [strapi/strapi#3653]
Hi guys !

**Describe the topic**
I try to get user Id with GraphQL. Actualy, with SQLite, i can't show _id/id field on `me` query.
For update User or other data (from other model), i need to add where param's with user: id.

Do you know how i can get this information from GraphQL query ?

**Your suggestions for this topic**
Maybe return the _id / id field from `me` query ?

**Screenshots**
If applicable, add screenshots to help explain your points.
![image](https://user-images.githubusercontent.com/4712791/61583928-707c6280-ab3f-11e9-93b5-ebbc7184f794.png)

**Code snippets**
```
query {
  me {
    id
  }
}
```

**Additional context**
I use latest strapi@beta version :)

Thank you community !

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

In your case especially information about database
