### ISSUE TITLE
Misleading `strapi build` command

### ISSUE THREAD

**Issue by webdeb** [strapi/strapi#3654]
**Describe the topic**

The CLI command `build` is very misleading. Because it only generates the admin-spa. It does not generate the `api-app-bundle.js`, this is what I was expecting.

**Your suggestions for this topic**

Please rename the `strapi build` command into `strapi build-admin`

**Additional context**

I am still looking for a way, how to build one `bundle.js` file for the strapi application, to copy that file into a docker image and run it just by calling `node bundle.js`

**Comment by lauriejim** [comment]
Hello @webdeb !

Can you precise your need with `api-app-bundle.js`. What is this file?

It's normal that the `strapi build` build only the admin because it's the only thing that needs to be built.
The API (at least the node.js server) don't have to be built.

**Comment by webdeb** [comment]
Hello @lauriejim 

`api-app-bundle.js` (just to make it clear) which include everything the api needs to run.

> The API (at least the node.js server) don't have to be built.

Well, if it does not have to be build, then I've to copy the whole project to my docker-image with the whole node_modules. It's about **280mb**

**Comment by Naismith** [comment]
@lauriejim I believe webdeb is under the assumption the server goes through a build process with tree-shaking etc.

**Comment by derrickmehaffy** [comment]
@webdeb Strapi is not a "normal" node project that is design to be completely "built" into static files in a "drop and run" scenario. It's designed to be run as a service and thus the 280mb of node_modules should exist and be there. The build process is only building the admin where as the entire backend part of strapi is not "built"

**Comment by davidkartuzinski** [comment]
@webdeb - Hello.  Did you understand that `strapi build` would also build the front-end, ie. the React.js or Vue.js part? As mentioned earlier in the thread, `strapi build` only builds the administrative part of the content <- this is Strapi.  

The client part (React.js or Vue.js, for example as front-end) is separate. 

I am clarifying this because you asked an interesting question and we may have to clarify this in our docs.

Thank you.

**Comment by webdeb** [comment]
@derrickmehaffy Whats the difference, to "normal" node project, and what do you mean, by saying "It's designed to be run as a service"?

**Comment by webdeb** [comment]
There is an example of `node server.js` where `server.js` is just 

```
require('strapi').start()
```

If this works, why cant you compile the whole strapi application with all dependencies (not the admin spa) into a `server.js` file?

**Comment by derrickmehaffy** [comment]
Normal in my context being say a react project, you write the code, build it, and you get a build directory (or dist, ect) and you can take that "build" and just run it from another web server like apache. Strapi is not built nor designed for that, it's expected it will always be ran using node in some way. PM2 is an example of this, in that Strapi itself is it's own web server. The plugins contain both "frontend" and "backend" code, the frontend is compiled into the adminUI build whereas the backend is not.

**Comment by webdeb** [comment]
@derrickmehaffy all you said is true, besides the fact, that any application can be compiled to a minimal artifact, or are you running your OS from source code files right now?

**Comment by derrickmehaffy** [comment]
@webdeb I do usually yes :P and I understand your point

**Comment by webdeb** [comment]
Thank you all, I am closing this one. I guess its better to open a new thread to discuss the possibilities of a compile step, to create a minimal, deployable artifact.

**Comment by derrickmehaffy** [comment]
@webdeb This might be the best place for such a topic: https://github.com/strapi/rfcs

**Comment by StianOvrevage** [comment]
I found this issue with the same assumption that @webdeb had about `yarn build` actually building the API.

And currently the `node_modules` folder is no longer 280MB but 617MB.

Using the examples from https://github.com/strapi/strapi-docker leads to an incredible 2.16GB Docker image. From <2MB of actual source code.

I'm in the process of optimizing this but the fact that strapi API cannot be built like any other modern application is a major concern.

I see no reason why strapi could not be built/compiled like any other node project and removed 99% of the bloat in `node_modules`.

**Comment by jfmontanaro** [comment]
@StianOvrevage Did you ever have any luck with optimizing the image size? I'm encountering the same difficulty. I tried [node-prune](https://github.com/tj/node-prune), but that only got rid of ~36MB. I suspect dead-code elimination would get rid of a lot more.
