### ISSUE TITLE
Confirmed account got "Your account email is not confirmed" when login

### ISSUE THREAD

**Issue by bin16** [strapi/strapi#3658]
**Describe the bug**

- `Enable email confirmation` is on, and email service properly configured
- and database is SQLite for development environment
- Call register API to create an user, and check confirmation email. By clicking that confirmation URL, I see that, `IsConfirmed` field/switch is `ON` in admin panel, it means the user is confirmed.
- But I can not login, got error `Your account email is not confirmed`

**Steps to reproduce the behavior**
1. Environment is `development`, database is `SQLite 3`
2. Enable email confirmation
3. Register and open confirmation URL in email
4. Call login API
5. Got `Your account email is not confirmed`

**Expected behavior**

In admin panel, i see my account is confirmed, so i should login successfully

**Screenshots**

and i checked the users-permissions and got this:

![image](https://user-images.githubusercontent.com/11701531/61616459-0b3d8400-ac9b-11e9-9d3f-a2211b088b40.png)

`user.confirmed !== true`, user.confirmed is `1`(number, not true), so...

**Code snippets**

**System**
- Node.js version: `v10.16.0`
- NPM version: `6.10.1`
- Strapi version: `3.0.0-beta.13`
- Database: `SQLIte`
- Operating system: `Mac OS X`

**Additional context**
in package.json: 

```
strapi-plugin-users-permissions": "3.0.0-beta.13",
```

**Comment by derrickmehaffy** [comment]
Closing as no context was given

**Comment by bin16** [comment]
Sorry, issue edited

**Comment by bin16** [comment]
Sorry, issue edited.
@derrickmehaffy Can we re-open it?

**Comment by derrickmehaffy** [comment]
@bin16 can you please add the proper response here:

```
Describe the bug
A clear and concise description of what the bug is.
```

Also can you please try updating all your packages in the `package.json` to the current latest version: `beta.13` and test again.

Issue reopened

**Comment by bin16** [comment]
> @bin16 can you please add the proper response here:
> 
> ```
> Describe the bug
> A clear and concise description of what the bug is.
> ```
> 
> Also can you please try updating all your packages in the `package.json` to the current latest version: `beta.13` and test again.
> 
> Issue reopened

updated, and it still exists

**Comment by derrickmehaffy** [comment]
It's likely related to how SQL in general stores boolean values as a `tinyint` instead of something like mongo which stores the actual `true/false`

**Comment by lauriejim** [comment]
Hello! Thank you for this report.
This issue has been fixed in the `develop` branch.
