### ISSUE TITLE
Unable to specify provider redirect_uri for development mode

### ISSUE THREAD

**Issue by isabellachen** [strapi/strapi#3662]
**Describe the bug**
I am trying to get Strapi to pass Facebook the correct callback url, but am unable to achieve this despite following the documentation. I am running the [login-react example](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/fb_setup.md). 

Because eventually I will need to use this login flow with a React Native app, I will need Strapi to give facebook a custom callback url instead of `http://localhost:1337/connect/facebook/callback`. To simulate this, I create a tunnel with ngrok to localhost:1337. [According to this suggestion](https://github.com/strapi/strapi/issues/707#issuecomment-373048698) I set the redirect url in the environments > development > server.json then `strapi build` then `strapi start`, but still the callback passed to facebook is localhost:1337.
```
{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": false
  },
  "facebook": {
    "redirect_uri": "https://9befd9d8.ngrok.io/connect/facebook/callback"
}
```

**Steps to reproduce the behavior**
1. Download and run the [login-react](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/fb_setup.md) example
2. Download Strapi.
3. Create a Facebook Login App
3. Add the facebook redirect_uri configuration to environments > development > server.json
4. Create a tunnel to localhost:1337
5. `Strapi build` then `Strapi Start`
6. In the Strapi Dashboard Roles & Permissions > Facebook enter the Client ID, Secret and the redirect URL to the front-end app, in this case with Create React App is `http://localhost:3000/connect/facebook`
7. Configure the facebook app so that `https://9befd9d8.ngrok.io/connect/facebook/callback` is specified as a valid oAuth redirect URL.
8. Click the button to connect to facebook, you should be redirect to Facebook, but on inspection of the URL, the uri is still  `https://localhost:1337/connect/facebook/callback`

**Expected behavior**
I expected that after the configuration, the callback should use the ngrok tunnel as the host to redirect after successful authentication with facebook.

**System**
- Node.js version: 10.15.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.11
- Database: MongoDB
- Operating system: Windows 10 (whatever the latest version is)

**Additional context**
I would simply like to configure my redirect_uri for all my providers for development and production as specified[ in this comment ](https://github.com/strapi/strapi/issues/707#issuecomment-373048698)in another issue.

**Comment by lauriejim** [comment]
Hello! I'm not sure about what you want to do.
I just followed the Facebook login guide and it works well.

**Comment by derrickmehaffy** [comment]
@lauriejim I believe the problem is using this in production, not localhost

**Comment by lauriejim** [comment]
There is `development mode` mention in the issue title 🤔

**Comment by derrickmehaffy** [comment]
Yes but `development mode` doesn't always mean localhost :wink: I've noticed the redirection URI having issues when not using localhost and in this case I believe @isabellachen is trying to move into production with the URI provided: `https://9befd9d8.ngrok.io/connect/facebook/callback`

**Comment by isabellachen** [comment]
Yes, I'm trying to do the facebook login with a React Native app and a [webview](https://docs.expo.io/versions/latest/workflow/linking/#using-expowebbrowser-instead-of-linking-for-opening). This webview opens the example react app provided, but when Facebook sends the code back to Strapi, it needs to do so via the ngrok tunnel or through the network since the android emulator has access to the server running on my local machine via ngrok (or my network address). I managed to update the grant config via the bootstrap.js file after following [this suggestion](https://github.com/strapi/strapi/issues/3360), but I'm hoping there's a better way :)

**Comment by derrickmehaffy** [comment]
@isabellachen are you using the proxy settings in the server config? example from my own project: https://github.com/canonn-science/CAPIv2-Strapi/blob/2e71ca0a03e95aa6bd35ef72a886d01436f10908/config/environments/development/server.json#L4-L8

That config is designed to rebuild that redirect URI (more than just 3rd party auth, but also things like the upload plugin)

**Comment by isabellachen** [comment]
Nope, didn't think to try that. I'll give it a go tonight...

**Comment by isabellachen** [comment]
@derrickmehaffy That worked!

**Comment by krytthew** [comment]
Help please I have the same problem it is not sending me the complete redirect_uri only it sends the final part of the callback "/ connect / facebook / callback" and it does not send me the complete URI because it must.
![image](https://user-images.githubusercontent.com/38815569/87862400-55406080-c915-11ea-8e89-0854c165aa00.png)
