### ISSUE TITLE
Infinite loading when I trying to Add New content after deployed to HEROKU(MongoDB Atlas) 

### ISSUE THREAD

**Issue by keshibat** [strapi/strapi#3663]
**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.13
- Database: mongoDBAtlas
- Operating system: Mac 10.13.6

**Steps to reproduce the behavior**

**Deployed Strapi on HEROKU with MongoDB Atlas**
Workin fine with my local http://localhost:1337

1. go to Content Type Builder
2. create a new Content Type named Restaurant
3. fields to this Content Type: name (string), description (text) then save
4. go to "Restaurants" (top of left menu on admin panel) then click on "Add new Restaurant"

**Expected behavior**
Allowing me inserting new entry

![Imgur](https://i.imgur.com/ps3lglE.png)

**Comment by derrickmehaffy** [comment]
@keshibat please try this: https://github.com/strapi/strapi/issues/3245#issuecomment-491274630 and "restart" your strapi server on heroku.

It's a well known issue that is already being worked on. Closing this as a duplicate to many many previous issues. The Strapi team are aware of it and are working on it.
