### ISSUE TITLE
There is no admin folder

### ISSUE THREAD

**Issue by dugajean** [strapi/strapi#3665]
**Describe the bug**
Yesterday while I was playing around with Strapi, I learned that there should be a **admin/** folder in the root of the project. In my case there isn't. The only admin folder available is under **.cache/admin**. Changing the logo there doesn't have any effect as far as I could tell.

**Steps to reproduce the behavior**
1. `yarn global add strapi@beta` and `npm install strapi@beta -g` (tried both)
2. `strapi new my-project --quickstart`
3. Check the project root folder
4. No admin folder in sight

**Expected behavior**
The admin folder should be present.

**System**
- Node.js version: v12.2.0
- NPM version: 6.9.0
- Strapi version: Latest
- Database: SQLite (default)
- Operating system: Windows 10 Pro, also tried with WSL and got the same issue

**Additional context**
I tried `yarn` and `npm`, Windows 10 directly and WSL and nothing helped.

**Comment by lauriejim** [comment]
Hello @dugajean!
Where did you learn that a `/admin` folder is in the root of your project?
In the `alpha` version of strapi it was true. But not in the `beta` version.
Now the `/admin` folder is only here to override admin stuff.
📚 Documentation here: https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#customization

**Comment by dugajean** [comment]
Yep, I understood it wrong it seems. I already got support on this on Slack. Thanks a ton!

**Comment by gr8rizwan** [comment]
Documentation should be updated, https://strapi.io/documentation/3.0.0-beta.x/concepts/file-structure.html, it 's written about the admin folder, but it's not there in beta.

**Comment by lauriejim** [comment]
Hello @gr8rizwan !
This is for `contains your admin customization files.`
By default, your don't have any customization for your admin, so the folder doesn't exist.
It's the same as `.cache` folder, your application can work without.
