### ISSUE TITLE
Minimal deployable artifact

### ISSUE THREAD

**Issue by webdeb** [strapi/strapi#3666]
**Describe the topic**
Right now you have to carry the complete node_modules directory to the production system. For small projects its ok, but its not cool for a system which is container based (docker, etc) and you build every day dozens of containers through the CI pipeline.

A plain strapi project weights about **280mb** (npm i --production)
Compared to that the whole node-alipine docker image weights only **55mb** and this includes the complete alpine OS + v8 + node framework

**Your suggestions for this topic**
Creation of a compilation step, so that the whole api server is bundled with all its dependencies into small runnable node.js application artifact. Its expected, that a proper bundle step minification etc would reduce about 80-90% of the current project size. From 300mb -> 20 - 30mb.

**Comment by derrickmehaffy** [comment]
@Aurelsicoko Maybe something to add to the product board? I understand the purpose but I'm wondering if this is something that would eventually get pushed when near stable?

**Comment by webdeb** [comment]
Would be interesting to know what the core team thinks about it.
What challenges needs to be solved to make it possible? Maybe you guys can share some insights into the architecture of strapi.

**Comment by lauriejim** [comment]
Hello! Thank you for this feedback!
The main topic about the size of a project and all other performances topics are something we care about.
For this point "Minimal deployable artifact" this will be for later. We are focusing now on other topics that are more important right now.
I close this issue. Will reopen it when we will work on it.
At least we will open an rfc.

**Comment by Aurelsicoko** [comment]
Yes, you should definitely open an RFC (https://github.com/strapi/rfcs).

**Comment by swerder** [comment]
I managed to get strapi work as a node Single Execution Application (SEA), by adding special webpack handlings for the dynamic loading of modules(plugins, middleware,...).
The resulting sea.blob(containing api backend & admin files) is about 35mb, combined with required binary node modules (sharp, sqlite) + nodejs executable it's resulting in total files size of ~150mb.
Or if you want to use only the result of webpack build (single index.js) + binary node modules it's ~50mb.

I'm not sure if there would be a technical possibility to add the webpack logic inside the normal strapi code, but it works as module patches to the normal release.
More information / the needed files are in the repo: https://github.com/swerder/strapi-sea

Attention: It's not 100% error prove as I don't use all features of Strapi(to verify them), but it my be a try to check it.

**Comment by unrevised6419** [comment]
I would also be interested into making the Strapi packages much smaller.

My first initiative is this PR https://github.com/strapi/strapi/pull/23278. But going through node_modules, I see many other opportunities that could make the libraries much smaller.

First thing that I see there are a lot of dependencies that are not used at all in production, but because how Strapi is build you cannot drop them. There is need for a rethinking how the strapi cli works. Probably the runtime used commands need to be migrated into a separated cli, and those needed only for development/build can be omitted from production dependencies.
