### ISSUE TITLE
Cannot add new content's entry by click "Add new xxxx", if the content type "xxxx" is not created by self env. 

### ISSUE THREAD

**Issue by techgeniuswang** [strapi/strapi#3667]
**Describe the bug**
The problem is very strange.
If I created a new content type, for example the name is "testmodule", add a field "testfield". Then I can add a new entry for this content type from strap admin page. 
But my colleagues can't  add a new entry for the content type if he/she retrieved code.

**Steps to reproduce the behavior**
1. Go to 'Content Type Builder'
2. Click on 'Add Content Type'
3. Enter the name as 'testmodule'
4. add a new field with name as 'testfield'
5. Click on 'Save'
6. Strapi will show message that it is restarting.
7. When start again, can see a 'Testmodule' from Strapi menu
<img width="175" alt="image" src="https://user-images.githubusercontent.com/31273693/61700257-fdf1c980-ad6e-11e9-9027-01b517d618bb.png">
8. Then can add a new entry by click 'Add New Testmodule'
<img width="202" alt="image" src="https://user-images.githubusercontent.com/31273693/61700324-1a8e0180-ad6f-11e9-8d00-c3923ee9d834.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/31273693/61700355-28dc1d80-ad6f-11e9-9e29-172cba37fcd9.png">

9. Then push changed code(6 files) to GitHub, to let other people can retrieve the new content type
<img width="390" alt="image" src="https://user-images.githubusercontent.com/31273693/61700451-532ddb00-ad6f-11e9-85e9-f70ea32ccda7.png">
<img width="384" alt="image" src="https://user-images.githubusercontent.com/31273693/61700478-5c1eac80-ad6f-11e9-978d-62613f709b11.png">

10. Other people who pulled the above code, after strapi restarts, he/she can see "Testmodule" from strapi menu, but when click  'Add New Testmodule', the page still show the spin. So that he/she can't add new entry.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/31273693/61700831-be77ad00-ad6f-11e9-844a-230d6cbaf5eb.png">

**Expected behavior**
I think I have pushed **ALL** changed files to git, but regrading above description, other people can't add new entry for the new content type after they retrieved my pushed code. So may I know:
1. Is it a strapi's bug? 
2. OR I missed some file with need to push? 
3. OR strapi did something with my mongoDB which need redo at all my teammate's env?

Maybe this issue has been solved, but I can't find any related documents from website. 

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.23
- Database: MongoDB 4.0.2
- Operating system: macOS 10.14.5

**Comment by lauriejim** [comment]
Hello! Yes it's an issue related to Strapi.
Please can you follow this comment here https://github.com/strapi/strapi/issues/3548#issuecomment-514065145
Other issues mentioned this issue, we are working on it.
Sorry for the trouble.

**Comment by techgeniuswang** [comment]
hi @lauriejim thanks for your quickly response. I referred https://github.com/strapi/strapi/issues/3548#issuecomment-514065145 removed plugin_content-manager_schema from my core_store, and stopped strapi. Then retrieve a new content type relate code from git. Then start strapi. 
now I can see new content type from menu, and can see the new content type from content type builder.
But I can't see it from content manager, also cannot add new entry for the new content type
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/31273693/61712131-3225b400-ad88-11e9-8e35-3a2b7465f529.png">

would you please guide me how fix it? really appreciate.

**Comment by techgeniuswang** [comment]
My strapi worked.

Previous steps is stop strapi -> pull code -> start strapi----->result is failed as above description.
Then I tried keep strapi running -> delete plugin_content-manager_schema from my core_store -> restart strapi -> result is I can add new entry for the new content type. 

So I think the key point is should keep strapi running then delete plugin_content-manager_schema, right?

**Comment by lauriejim** [comment]
Yap that it.
We fixed this bug (in development branch) it will be released at the same time as the new Group feature.

**Comment by techgeniuswang** [comment]
Wow, Great!
