### ISSUE TITLE
Using AWS - Receiving The pool is probably full error 

### ISSUE THREAD

**Issue by CharlieGreenman** [strapi/strapi#3671]
**Describe the bug**
When starting my `strapi` project using `npm start ecosystem.config.js`, I will receive the error: `{ TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

**Steps to reproduce the behavior**

**Expected behavior**
It should probably connect to ip address when running `pm2 start ecosystem.config.js`

**Screenshots**
![Screenshot 2019-07-24 11 00 03](https://user-images.githubusercontent.com/8540141/61775770-37bfe000-ae02-11e9-83ce-eebbb557edf0.png)

**Code snippets**
### ecosystem.config.js ####
```
module.exports = {
  apps : [{
    name: 'razroo-blog',
    cwd: '/home/ubuntu/razroo-blog',
    script: 'npm',
    args: 'start',
    instances: 1,
    autorestart: true,
    watch: false,
    env: {
      NODE_ENV: 'production',
      DATABASE_HOST: 'obfusicated for the sake of this question', // database Endpoint under 'Connectivity & Security' tab
      DATABASE_PORT: '5432',
      DATABASE_NAME: 'strapi',  // DB name under 'Configuration' tab
      DATABASE_USERNAME: 'postgres', // default username
      DATABASE_PASSWORD: 'Password',
    },
  }],
};
```
###  production/server.json file ###
```
{
  "host": "${process.env.APP_HOST || 'obfuscated for purposes of this question '}",
  "port": "${process.env.PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
```

###  production/database.json file ###
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST || 'obfusicated for purposes of question'}",
        "port": "${process.env.DATABASE_PORT || 5432}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || 'strapi'}",
        "password": "${process.env.DATABASE_PASSWORD || 'Password'}"
      },
      "options": {
        "debug": false,
        "acquireConnectionTimeout": 100000,
        "pool":{
            "min": 0,
            "max": 100,
            "idleTimeoutMillis": 100000,
            "createTimeoutMillis": 100000,
            "acquireTimeoutMillis": 100000,
            "propagateCreateError": false
        }
      }
    }
  }
}
```

### hook.json ###
```
{
  "timeout": 100000,
  "load": {
    "before": [],
    "order": [
      "Define the hooks' load order by putting their names in this array in the right order"
    ],
    "after": []
  }
}
```

### package.json ###
```
{
  "name": "strapi-beta",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "lint": "eslint ."
  },
  "devDependencies": {
    "babel-eslint": "^10.0.0",
    "eslint": "^6.0.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-react": "^7.14.0"
  },
  "dependencies": {
    "knex": "latest",
    "lodash": "^4.17.5",
    "pg": "^7.11.0",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.13",
    "strapi-admin": "3.0.0-beta.13",
    "strapi-hook-bookshelf": "3.0.0-beta.13",
    "strapi-hook-knex": "3.0.0-beta.13",
    "strapi-plugin-content-manager": "3.0.0-beta.13",
    "strapi-plugin-content-type-builder": "3.0.0-beta.13",
    "strapi-plugin-email": "3.0.0-beta.13",
    "strapi-plugin-settings-manager": "3.0.0-beta.13",
    "strapi-plugin-upload": "3.0.0-beta.13",
    "strapi-plugin-users-permissions": "3.0.0-beta.13",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.13",
    "strapi-utils": "3.0.0-beta.13"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "bbaf920a-7800-45cd-b2b8-0e2b7c76b4fb"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.13
- Database: AWS Aurora(Postgres
- Operating system: Ubuntu 18.04.2 LTS

**Additional context**
I had the issue when migrated from Alpha to Beta. I used the documentation for doing it. I then decided to scrap project and start from beginning again. Both ended up giving me the same error: `{ TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

Followed documentation here: https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws

**Comment by BarryBuitelaar** [comment]
Same problem..

**Comment by CharlieGreenman** [comment]
Decided to not use AWS and move to Digital Ocean.

**Comment by BarryBuitelaar** [comment]
Please reopen this issue. I am working with AWS

**Comment by davidkartuzinski** [comment]
@BarryBuitelaar Are you getting the same error?  Are you trying to follow the docs? 

Please check your ec2 instance type is it micro or small?

**Comment by BarryBuitelaar** [comment]
@davidkartuzinski Yes indeed, i followed the docs. But i already fixed my issue. there was a problem with my security groups.

**Comment by davidkartuzinski** [comment]
@BarryBuitelaar thank you for letting us know.  Was it a deficiency in the docs?  Like a missing step?

**Comment by puuble** [comment]
same problem with AWS postgre instance pls help

**Comment by Quanda** [comment]
Same here

**Comment by 0x15a5a** [comment]
Same problem here using AWS postgre.

**Comment by jpkelly** [comment]
Same problem here.

**Comment by finkvi** [comment]
Same problem with https://cloud.ibm.com/catalog/services/elephantsql

**Comment by finkvi** [comment]
> Same problem with https://cloud.ibm.com/catalog/services/elephantsql

Works for me, database.json

```
      "options": {
        "useNullAsDefault": true,
        "pool":{
          "min": 1,
          "max": 4,
          "idleTimeoutMillis": 30000,
          "createTimeoutMillis": 30000,
          "acquireTimeoutMillis": 30000
        }
      }
```

**Comment by AliKHODR** [comment]
same problem using MySQL

**Comment by EyalRo** [comment]
I was encountering the same issue. The problem was with associating the RDS (not EC2) to the Strapi security group. Once I've allowed incoming Postgres on that sec group everything started working.

**Comment by axelraymundo** [comment]
> I was encountering the same issue. The problem was with associating the RDS (not EC2) to the Strapi security group. Once I've allowed incoming Postgres on that sec group everything started working.

I'm running into this problem now as well, how do you allow incoming Postgres on the sec group?

**Comment by hassaanp** [comment]
> > I was encountering the same issue. The problem was with associating the RDS (not EC2) to the Strapi security group. Once I've allowed incoming Postgres on that sec group everything started working.
> 
> I'm running into this problem now as well, how do you allow incoming Postgres on the sec group?
> 
> EDIT:
> I went to my Postgres RDS instance, under Connectivity and Security > Security group rules I clicked on one of the inbound rules and it redirected me to the RDS instance, click on Inbound tab then Edit, click Add Rule:
> 
> Type: PostgresSQL
> Protocol: TCP
> Port Range: 5432
> Source: Custom - Then type the name of your strapi security group, it will autocomplete.
> 
> Save.
> 
> Thanks @EyalRo!

This needs to be added to the documentation.

**Comment by derrickmehaffy** [comment]
@hassaanp I've added it to our list :wink:

**Comment by YannYves** [comment]
Thank you so much @EyalRo / @axelraymundo  !! You guys really helped me out on this one :) 
Definitely worth mentioning it in the docs @derrickmehaffy  
Iv'e learned a lot though while looking for answers

**Comment by bernardomontoya** [comment]
I struggled realy hard with this one, thank you so much @BarryBuitelaar  @axelraymundo ! That needs to be in the docs!

**Comment by Romkin7** [comment]
> > I was encountering the same issue. The problem was with associating the RDS (not EC2) to the Strapi security group. Once I've allowed incoming Postgres on that sec group everything started working.
> 
> I'm running into this problem now as well, how do you allow incoming Postgres on the sec group?
> 
> EDIT:
> I went to my Postgres RDS instance, under Connectivity and Security > Security group rules I clicked on one of the inbound rules and it redirected me to the RDS instance, click on Inbound tab then Edit, click Add Rule:
> 
> Type: PostgresSQL
> Protocol: TCP
> Port Range: 5432
> Source: Custom - Then type the name of your strapi security group, it will autocomplete.
> 
> Save.
> 
> Thanks @EyalRo!

Thank you so much, this saved my day! Finally it's working!! 👯
