### ISSUE TITLE
Missing envrionnment config for env: --dev. ( windows 10 )

### ISSUE THREAD

**Issue by jhonyourangel** [strapi/strapi#3673]
**Describe the bug**
At new projecrt creation, after creating the project it tryies to run and it crashes with this error

```
Missing envrionnment config for env: --dev.
Make sure the directory ./config/environments/--dev exists
```

**Steps to reproduce the behavior**
npm install strapi@beta -g
strapi new my-project --quickstart

**Expected behavior**
to work!

**Screenshots**
![image](https://user-images.githubusercontent.com/2562455/61797724-40c3a800-ae28-11e9-9c8c-9b9ddcc99cca.png)

**System**
- Node.js version: v12.2.0
- NPM version: 6.9.0
- Strapi version: latest beta
- Operating system: win 10

**Comment by derrickmehaffy** [comment]
@jhonyourangel check your `config/environments` folder if there is one named `--dev` delete it

**Comment by jhonyourangel** [comment]
there is none
![image](https://user-images.githubusercontent.com/2562455/61853360-04418c00-aebc-11e9-9fdf-5fe741b67257.png)

**Comment by jhonyourangel** [comment]
ps: i have tried to create a project on my personal computer, a mac, and worked at first try

**Comment by jhonyourangel** [comment]
looks like the command 
`npm run develop`  returns error 

```
Missing envrionnment config for env: --dev.
Make sure the directory ./config/environments/--dev exists
```


while `npm run start`

```
[2019-07-25T13:46:45.910Z] debug ⛔️ Server wasn't able to start properly.
[2019-07-25T13:46:45.916Z] error TypeError: Cannot read property 'defaultConnection' of undefined
    at module.exports (C:\Users\iutale\Developer\nodejs\testcms2\node_modules\strapi\lib\core\bootstrap.js:26:47)
    at Strapi.load (C:\Users\iutale\Developer\nodejs\testcms2\node_modules\strapi\lib\Strapi.js:283:11)
    at async Strapi.start (C:\Users\iutale\Developer\nodejs\testcms2\node_modules\strapi\lib\Strapi.js:123:7)
```


![image](https://user-images.githubusercontent.com/2562455/61879580-987b1580-aef3-11e9-9556-0c40dcc2891b.png)

**Comment by jhonyourangel** [comment]
i have to say though that `--dev` looks pretty familiar as a environment property.

maybe there is a type somewhere, that i am unable to find while searching the project

shouldn't this
`Make sure the directory **./config/environments/--dev** exists`
be 
`Make sure the directory **./config/environments/development** exists`

?

**Comment by jhonyourangel** [comment]
just run this in powershel
`$env:NODE_ENV="development"`

there is no default env that points to development.
hhmmm
