### ISSUE TITLE
Unable to extend email plugin following documentation

### ISSUE THREAD

**Issue by isabellachen** [strapi/strapi#3676]
**Describe the bug**
I'm trying to extend the email plugin so I can use attachments in the template. I'm using strapi-provider-email-nodemailer. This plugin provides support for attachments, all I have to do is include an array of attachments to options. 

The [documentation for how to extend plugin](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions) tells me that I have to 'extend the plugin's controllers by create controllers with the same names and override certain methods'

I create a file in `extensions/email/controllers/Email.js` and copy over the code from the original email plugin, modifying only the options object but changing the value of the `options.subject`, then `strapi build` followed by `strapi start`. 

**Steps to reproduce the behavior** (updated)
1. Create a strapi project according to the quickstart
2. `npm i strapi-provider-email-nodemailer`
3. Configure to use nodemailer in plugins > email > provider
4. Create under extensions an email folder with controller (extensions > email > controllers > Email.js) last time I did this - last week - it seemed that the email folder was created for me. Now only user-permissions folder was created.
5. Copy and paste the 'send' method from the strapi-plugin-email/controllers/Email.js
6. Modify the subject on the options object

**Expected behavior**
Expect to see the modified subject in a received email and not the one defined in the template.

**Screenshots**
extensions/email/controllers/Email.js 
![image](https://user-images.githubusercontent.com/9280665/61825112-f2320000-ae5f-11e9-8a1c-b31a2b2d1c57.png)

Subject not changed
![image](https://user-images.githubusercontent.com/9280665/61825480-c06d6900-ae60-11e9-8b23-bbb0f9b12966.png)

**System**
- Node.js version: 
- NPM version: 10.16
- Strapi version: 3.0.0. beta
- Database: mySql
- Operating system: MacOS

**Comment by lauriejim** [comment]
Hello! 

`extensions` folder works well. Your issue here it's because you updated the wrong file.
You updated the controller function (that is called by the route `/email`) and you have to update the service function.
In your example for the confirmation email, that call the service function [here](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L508).
