### ISSUE TITLE
Forgot password email link URL incorrect if admin path is customized

### ISSUE THREAD

**Issue by rhaft** [strapi/strapi#3677]
**Describe the bug**
If the admin path is modified in config/environments/**/server.json, the link included in a password reset email does not reflect the configured path but uses the default '/admin' path. Clicking on the link in the email redirects to an invalid URL.

**Steps to reproduce the behavior**
1. Configure a custom admin path in config/environments/development/server.json, i.e., "/panel"
2. Rebuild strapi admin
3. Go to 'http://example.com/panel/plugins/users-permissions/auth/login'
2. Click on 'Forgot your password?....'
3. Enter your user's email address and click on 'Send Mail'
4. Check the link in the Reset Password email sent to your email address. It uses the default "/admin/..." path when it should be "/panel/..."

**Expected behavior**
The Reset Password email should include a link using the customized admin path rather than the default path.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9
- Strapi version: beta.3
- Database: mongod
- Operating system: Ubuntu 18.04 LTS

**Comment by lauriejim** [comment]
Hello @rhaft!
Thank you for this report.
I think this issue come from this form https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage/saga.js#L31
@soupette will be able to confirm (or not) and provide a good way to fix it.

**Comment by rhaft** [comment]
Thanks @lauriejim . @soupette Happy to take on the task of fixing this issue... any requirements you can foresee other than checking the config for admin.path and using that rather than the hardcoded '/admin'?

**Comment by LucidNinja** [comment]
Has there been any progress on this? I can also confirm that Strapi is completely ignoring the content body of the email if this has been edited in the admin area.

**Comment by LucidNinja** [comment]
In looking into this further, it is actually that the email template cannot be customised for "Administrators", not "Users". And because of this issue where /admin is hardcoded, then the hardcoded Administrator email template will send the wrong URL every time, if the admin path has been customised (eg /admin -> /dashboard)

**Comment by felixhamel** [comment]
Will be fixed with : https://github.com/strapi/strapi/pull/4500
