### ISSUE TITLE
 Unauthorised 401 (API Consume)

### ISSUE THREAD

**Issue by nickngqs** [strapi/strapi#368]
**Node.js version**: v9.2.0
**npm version**: v5.5.1
**Strapi version**: 3.0.0-alpha.7
**Operating system**: MacOS Sierra

I'm getting Unauthorised 401 Code when I trying to consume the api. http://localhost:1337/products from http://localhost:3000 (Nuxt). Should i be enabling something? Not sure if CORS settings have anything to do with this.

**Comment by lauriejim** [comment]
Hello @nickngqs. The documentation about that will be publish today.
Actually you have to go in your admin dashboard, then in the user and permissions plugin and update `Guest` role and allow in `application` section find and findOne actions.

**Comment by nickngqs** [comment]
Ahh it works! But to be honest, i didn't even see the Application from the Accordion. The UI is abit weird? Thanks!

**Comment by Aurelsicoko** [comment]
@nickngqs Thank you for the feedback! Maybe we should open the first tab of the accordion?

**Comment by nickngqs** [comment]
Yup that would actually be good! And I do think that the other 3 sections is fighting attention with the Application section because they have icons, bigger, etc

**Comment by Aurelsicoko** [comment]
I agree. I will make some design research to find a way to improve the UX of this page.

**Comment by soupette** [comment]
I just made a PR to improve the UX on this view (https://github.com/strapi/strapi/pull/374)
