### ISSUE TITLE
Cannot create a relation "invalid input syntax for integer"

### ISSUE THREAD

**Issue by mdacosta** [strapi/strapi#3682]
**Describe the bug**
_It is really hard to describe this bug, so I am sorry in advance if it's not clear enough._

Given a model (A) with the following fields:
![Capture d’écran 2019-07-25 à 23 39 14](https://user-images.githubusercontent.com/12542151/61910680-93d75100-af35-11e9-8f33-384e5ea9f9bd.png)
And another one (B) which has a relation to the model A, if you set a A-model value in B-model entry, a "invalid input syntax for integer" is thrown.

The cause is that instead of passing the ID of the A-based entry, to passes the value of the "value" field of model A.

**The issue is caused by the fact that one of the fields is called `value`.**
After renaming it to anything else, everything works fine.

**Steps to reproduce the behavior**
1. create a model (A) with string field called "value"
2. add an entry in this model
2. create another model (B) which has a one-way relation with the previous one
3. and an entry in this model and set a value for the related model A
4. try to save
5. an error should appear on top of the page and a `error error: invalid input syntax for integer` should appear in the logs

**Expected behavior**
The value should be saved correctly

**Screenshots**
Here's an example of a request which fails:
![Capture d’écran 2019-07-25 à 23 46 14](https://user-images.githubusercontent.com/12542151/61911003-72c33000-af36-11e9-93b5-ae482de4b630.png)
As you can see it's the value of the `value` field which is sent instead of the id.

When changing the name of the field in the model (and database), everything works fine:
![Capture d’écran 2019-07-25 à 23 45 41](https://user-images.githubusercontent.com/12542151/61911084-a8681900-af36-11e9-9453-db7f9cfc0ad5.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.14
- Database: PostgreSQL v11.4
- Operating system: macOS 10.13.6

**Additional context**

**Comment by derrickmehaffy** [comment]
This is likely due to `value` being a reserved word somewhere, there are many and most are not known as it could be reserved from any number of locations. I would recommend just using a different name as it's unlikely that Strapi themselves can keep track of all the reserved names.

**Comment by lauriejim** [comment]
Hello @mdacosta !
Can you update your strapi version, this is not a valid version you set.

**Comment by mdacosta** [comment]
> Hello @mdacosta !
> Can you update your strapi version, this is not a valid version you set.

Done

**Comment by lauriejim** [comment]
Can you please provide the full request you try please.

**Comment by mdacosta** [comment]
I changed the column name.
