### ISSUE TITLE
can't save json schema to a json field

### ISSUE THREAD

**Issue by reutopiaer** [strapi/strapi#3684]
**Describe the bug**
error MongoError: The dollar ($) prefixed field '$schema' in 'jsonschema.$schema' is not valid for storage.

**Steps to reproduce the behavior**
1. create a json field
2. add json schema
3. save
4. get error

**Expected behavior**

**Screenshots**
![err](https://user-images.githubusercontent.com/759279/61942092-4efdf980-afcb-11e9-90f7-35ae11870fc6.jpeg)

**Code snippets**

**System**
- Node.js version: v10.15.3
- NPM version:6.4.1
- Strapi version: 3.0.0-beta.14
- Database: MongoDB shell version v4.0.2
- Operating system: windows10

**Additional context**

**Comment by derrickmehaffy** [comment]
This is not an issue with Strapi but a limit of mongo:

https://docs.mongodb.com/manual/reference/limits/#Restrictions-on-Field-Names
