### ISSUE TITLE
Strapi deployed on heroku often loses authorization configuration and admin accounts

### ISSUE THREAD

**Issue by Atheane** [strapi/strapi#3686]
We deployed strapi on heroku and several time a day, the online version works for a while and then loses admin accounts and roles / authorization configurations. Hence our client experiences a 403 answer from strapi API. Is it a known issue (I did not find it in the issues list) ? Or did I mixed things up during configuration. Thanks for your help.

**Comment by davidkartuzinski** [comment]
Could you please tell us which database you are using?

**Comment by Atheane** [comment]
mongoDB with mlabs

**Comment by derrickmehaffy** [comment]
@Atheane 

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by davidkartuzinski** [comment]
@Atheane - Thank you for the response regarding the database.  It would help if you follow the template so we can see what is happening.
