### ISSUE TITLE
Date filtering is not working with graphql

### ISSUE THREAD

**Issue by yassinebridi** [strapi/strapi#3687]
**Describe the bug**
Date filtering is not working through react-apollo, but it works in the graphql playground
*this is not a react-apollo problem, more on that bellow*

**Expected behavior**
for the date variables passed to the Query component to work.

**Code snippets**
when i test the query in the graphql playground, it works as expected and it shows the exact games from that period that i specified.
```graphql
{
  games(
    where: {
      time_gt: "2019-07-26"
      time_lt: "2019-07-29"
    }
  ) {
    id
    time
  }
}
```
but doing it through react-apollo
```javascript
  const start = "2019-07-26";
  const end = "2019-07-28";
  return (
    <Query
      query={LIMITED_DATE_GAMES}
      variables={{
        start: start,
        end: end
      }}
    >
      {({ data, error, loading }) => {
        if (loading) return <p>loading</p>;
        if (error) return <p>Error: {error}</p>;
        console.log(start);
        console.log(end);
        console.log(data);
        return <div>yaaaay</div>;
      }}
    </Query>
```
it shows **all** the games that are available in the database.

and this is the query:
```graphql
const LIMITED_DATE_GAMES = gql`
  query LIMITED_DATE_GAMES($start: DateTime!, $end: DateTime!) {
    games(where: { time_gt: $start, time_lt: $end }) {
      id
      time
    }
  }
`;
```
**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.10
- Database: postgres

**Additional context**
1- no matter what variables i pass, even just gibberish: const start = "asdfasdf", it has the same effect as passing the real variables
2- when passing the variables directly to the query, it works as it would through the graphql playground
```graphql
const LIMITED_DATE_GAMES = gql`
  query LIMITED_DATE_GAMES {
    games(where: { time_gt: "2019-07-26", time_lt: "2019-07-28" }) {
      id
      time
      location
      stadium
      status
      league {
        id
        name
      }
      teams {
        id
        name
      }
    }
  }
`;
```
3- it is not a react-apollo problem because i tested the query with prisma, with the same setup, prisma which has more or less the same API that strapi has, and it works as expected.
4- i haven't had a problem with other filterings

**Comment by derrickmehaffy** [comment]
You need to send the whole where filter as a single variable. https://github.com/strapi/strapi/issues/3537#issuecomment-507170401

This change was from upstream in the graphql package.

Closing and marking as a duplicate of https://github.com/strapi/strapi/issues/3537

**Comment by yassinebridi** [comment]
works like a charm.
