### ISSUE TITLE
Document deploying strapi to Zeit's Now

### ISSUE THREAD

**Issue by yassinebridi** [strapi/strapi#3688]
**Describe the topic**
Almost all my projects are deployed to now, having to deploy strapi to another platform like heroku, is an added cost. it would be pretty useful for users to chose as many platform as possible

**Additional context**
I tried deploying strapi to now, after it finished deploying, i can browse the index page, but i can't access the admin page.

**Comment by derrickmehaffy** [comment]
@yassinebridi you need to build the admin using `npm run build`, `yarn build`, or `strapi build`

However building Strapi's AdminUI requires at least 2GB of ram, if Zeit's now doesn't offer that you will need to build locally and commit your build folder to into git

**Comment by rodanato** [comment]
Hey @yassinebridi , did you have success with that deploy?

**Comment by yassinebridi** [comment]
@rodanato no, i just sticked to heroku.

**Comment by rodanato** [comment]
Oh, got it
