### ISSUE TITLE
Strapi can not run on windows 10

### ISSUE THREAD

**Issue by elektracodes** [strapi/strapi#3690]
**Describe the bug**
I install strapi globally and run the command it throws error that command not found. I went to the enviroment variables and added the path
`c:/Users/{username}/AppData/Roaming/strapi/bin`

It throws error invalid character. I do not know what more to do. Tried with 3.0.0-beta.13, same issues.

**Steps to reproduce the behavior**
1. run command line `npm install -g strapi@beta`
2. After install I cannot make strapi run, all commands are not found and when I add the env variable on windows 10, it says error.

**Screenshots**
![Screenshot](https://i.imgur.com/hIr89BZ.png)

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.13, 3.0.0-beta.14 
- Database:
- Operating system: Windows 10

**Additional context**
Tried with different command line tools. Uninstalled and re-installed Strapi. The issue is not fixed.
Is any version of Strapi beta working on Windows 10?

**Comment by elektracodes** [comment]
In case some has the same issue like me. Try re-install node. That worked for me.

**Comment by syedsimanta03** [comment]
I re-installed node v10.17 & also tried with v10.16. STill ERROR. Same issue. I wish I could use strapi on Win 10 latest version.

**Comment by FrankMwandi** [comment]
I am getting same problem

**Comment by ArneOb** [comment]
Obviously there is a command somewhere, that tries to start any 
xxxx.js 
instead of 
node xxxx.js
Thus the windows scripting host (WSH) tries to interprete it instead of nodejs.
