### ISSUE TITLE
Elasticsearch Support

### ISSUE THREAD

**Issue by CatsPlugins** [strapi/strapi#3701]
**Describe the topic**
I have do some research on Strapi, and it's really fast on the development ENV.

But, I wanna know if we can scale up, to serve Strapi as the backend, where we will have 10000 CCU at a time.

**Your suggestions for this topic**
I tried to search around for Elasticsearch support, but didn't find and clue how to deploy Elasticsearch with Strapi.

I got an empty NPM package about strapi-elasticsearch, and it has no files there.

I wanna know or can you guy please tell me where or how should I deploy Strapi with ElasticSearch?

Since, I want to use Strapi as the backend, to store upto 5 mils records (job site), and MongoDB will not suitable for the project.

**Additional context**

As mongodb, we're using for a marketplace at the moment, and it's quite slow, that's why I'm trying to use with ElasticSearch

**Comment by derrickmehaffy** [comment]
@CatsPlugins the elasticsearch plugin has not been built yet and there is no ETA on when work will start on it

**Comment by CatsPlugins** [comment]
Hi @derrickmehaffy ,

Thank you for your response! Do you know the keyword or the documentation or sample plugin, that I can write my own elasticsearch bridge to Strapi?

Thank you!

**Comment by derrickmehaffy** [comment]
I do not have any resources @CatsPlugins sorry

**Comment by lauriejim** [comment]
Hello! Can you submit your feature request here please https://portal.productboard.com/strapi

**Comment by MatheusRV** [comment]
Friendly Ping

**Comment by derrickmehaffy** [comment]
@MatheusRV this is not planned for some time, lots of other features taking priority right now.

**Comment by MatheusRV** [comment]
Any team interested in a budget to make this happen?

**Comment by jinyeng** [comment]
Any update on this yet ?

**Comment by lauriejim** [comment]
Nothing is planned for now.

**Comment by amitav13** [comment]
Related: there's a [community plugin](https://www.npmjs.com/package/strapi-hook-algolia) for Algolia, if that serves your needs.
