### ISSUE TITLE
Content Type created in builder but doesn't appear in manager

### ISSUE THREAD

**Issue by mzeydelis** [strapi/strapi#3704]
**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by mzeydelis** [comment]
I have created content type in Strapi and created fields then saved. Set permissions to content type. So it shows new content type in builder list but when I go to content type manager it's not there. I have restarted Strapi...nothing

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
