### ISSUE TITLE
Attempting to save new entry returns error

### ISSUE THREAD

**Issue by 1khdmurdolo** [strapi/strapi#3705]
Hi,

Environment as below.

Node.js version: 10.16.0
NPM version: 6.9.0
Strapi version: 3.0.0 beta.14
Database: MySQL
Operating system: Ubuntu
Environment: Production

So been having this issue locally, and now also after having deployed to our staging server. When I attempt to create a new entry on a content type that is just a name I am getting an error. When going to save the entry a toast/alert pops up saying:

> Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query.

In the console the error also returns a 400 code along with "Bad Request" and the above message.

1. Go to add an entry 
2. Enter the name
3. Click save
4. Error appears

The model of one I am trying to add, for example, is:
```
{
  "connection": "default",
  "collectionName": "agencies",
  "info": {
    "name": "agency",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": false,
    "comment": ""
  },
  "attributes": {
    "name": {
      "required": true,
      "type": "string"
    }
  }
}
```

The controller is empty, routes are the default for a new content type. Everything else is default.

This was a project that was migrated initially from alpha to beta following the migration guide, whether that helps in ascertaining what the issue might be.

If any more info is need please let me know.

Thanks.

**Comment by lauriejim** [comment]
Hello! It's an issue due to the migration, it will be hard to debug.
Your plugins are well migrated?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
