### ISSUE TITLE
the language can't choose chinese

### ISSUE THREAD

**Issue by landysunny** [strapi/strapi#371]
**Node.js version**:8.9.3
**npm version**:5.5.1
**Strapi version**:3.0.0.7
**Operating system**:windows 10

**Comment by soupette** [comment]
Hi could you be more specific on the error you got and the steps to reproduce it so we can take a look at it?

thanks in advance!

**Comment by landysunny** [comment]
it's my first time to try the strapi and i find there is a question.I try to use the plugin which called Settings Manages because I want to choose chinese as my default language.But i find when I add the language of chinese,there is a error occurred. And I don't konw the reason. I try to add the other language , it's ok. But i cant just add chinese.Could tell me why and how can I solve this problem. If you have any solution,please tell me.Thank you very much!

**Comment by soupette** [comment]
I just fixed the bug see: https://github.com/strapi/strapi/pull/380
In the meantime you can add a new locale by creating manually the file in `/config/locales/your_language.json`

**Comment by landysunny** [comment]
I had try your solution. But It seems didn't work, could show me by details.

**Comment by soupette** [comment]
Could you tell me what is the ISO 639 code of the language you trying to add ?

**Comment by landysunny** [comment]
![step01](https://user-images.githubusercontent.com/30380258/34086969-08195a86-e3db-11e7-815b-19b1bebcbe95.png)
![step02](https://user-images.githubusercontent.com/30380258/34086971-09bbbb2c-e3db-11e7-8499-b4000075841a.png)
![step03](https://user-images.githubusercontent.com/30380258/34086973-0beefabc-e3db-11e7-88bf-892ef44395ab.png)
the picture show which error I meet with, please help me, thank you very much!

**Comment by soupette** [comment]
Thanks!

So if you like to add this language you need to create a `zh_Hans_CN.json` file in your `my-app/config/locales` folder

**Comment by soupette** [comment]
I'm closing the issue
