### ISSUE TITLE
Graphql empty filtering fields returns all data.

### ISSUE THREAD

**Issue by yassinebridi** [strapi/strapi#3710]
**Describe the bug**
Graphql empty filtering returns all data.

**Expected behavior**
For the filtering to return only the wanted data.

**Code snippets**
This is straight from the graphql playground:
```graphql
query searchQuery {
  games(
    where: {
      league: { name_contains: "" }
    }
  ) {
    id
    league{
      name
    }
  }
}
```
So the name_contains filter is empty. yet, it returns all the data from the database
(i tested this with all kinds of filtering not only the nested ones)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.10
- Database: postgress

**Comment by derrickmehaffy** [comment]
@yassinebridi if you are looking for null fields you will need to update to the latest Strapi version (beta.14) and use the following filter `name_null: true`

Marking this as closed

**Comment by yassinebridi** [comment]
I'm actually filtering for the opposite, i want the non-null names filtering.
imagine this scenario(which is what i'm having trouble with): a search bar where i'm listening to user's input, everything works as expected, but when i empty the search field, the filtering is gonna end up like this:
```
where: {
   league: { name_contains: "" }
}
```
then it will returns all the games.

**Comment by alexandrebodin** [comment]
Hi,

`name_contains: "" ` means it will match all entries with a name containing the empty string which is true for name. Think of it like ` 'azdaz'.includes('')`

**Comment by yassinebridi** [comment]
Don't you think that's a bit problematic, the name_contains should only returns what you told it to return. otherwise you will just hack through it every time you face this problem.
unless of course there is a strapi way of dealing with this instead

**Comment by derrickmehaffy** [comment]
Yes but this case you you aren't asking for anything ;) you could instead use _null:false if the search is empty which will return every but null values.

Likewise you could combine the two so if contains is empty then the _null takes effect
