### ISSUE TITLE
Image upload response on production env contains local env url

### ISSUE THREAD

**Issue by Cmrickels** [strapi/strapi#3711]
In a production environment, after uploading an image, the response contains the URL of my local environment. 

1.) upload image on local environment using the uploads route from consuming client. The logo object in the response will contain the url property: http://localhost:1337/uploads.
2.) deploy and run on a production environment. For me is Ubuntu 18x bionic.
3.) When uploading an image in the same manner as done in step one. The response URL I receive has my http://localhost:1337/uploads/*** path from my local environment.
4.) When calling on the entity that contains the image, it responds with the production environments path but when uploading, the local environment path is returned. 

**Expected behavior**
I expect the URL returned when uploading an image to be my production url so i can immediately show the image without having to call for the related entity.

**Screenshots**
![image](https://user-images.githubusercontent.com/7825706/62300521-fa340600-b444-11e9-878f-a54177bfef06.png)

**System**
- Node.js version: 10
- NPM version:
- Strapi version: beta 3.14
- Database: Mongo
- Operating system: ubuntu 18 bionic

**Comment by lauriejim** [comment]
Hello! Did you configure your `./config/environments/production/server.json`
To specify your production host and port.
