### ISSUE TITLE
CamelCase model names makes strapi unusable.

### ISSUE THREAD

**Issue by romanmandryk** [strapi/strapi#3716]
**Describe the bug**
I can not use camel case (or underscores or dashes) in model names to separate words in multi-word name.

I have 2 models - Question and QuestionType and I want to create a one-to-many relationship between them.

When I generate `strapi generate:api QuestionType` all seems working. Problems start when I add a relation field to QuestionType.questions (many : 1 ) Question.questionType.
It finishes without issues but then: 

1. it breaks admin UI. See screenshot (it renamed QuestionType to Questiontype and added questionType which is a field!, not a content type). Notice inconsistency that "Question Type" in Content type builder is still correct (but with space - which I think is nice formatting but adds more to confusion).

2. "QuestionType" becomes unusable in admin UI. When I try to add one record, screen loads indefinitely. (see screenshot 2)

(3. with graphql plugin, this will crash the server so I had to uninstall it)

(4. generate:api allows using CamelCase for model names, but Admin UI doesn't - it forces you to all lowercase first time, but you can rename it later - which causes same issues as when generating.

**Steps to reproduce the behavior**
1. Create Question type in UI  with string field "name"
2. generate QuestionType api `strapi generate:api QuestionType` or create it in UI with lowercase and then rename it to QuestionType (because of the bug 4.)
3. in UI create relation field QuestionType.questions (many : 1 ) Question.questionType. (see screenshot
4. in UI try to add new Quest

**Expected behavior**
I can name my models with camel case (or underscores or dashes to make multi-word models clearly understandable) and be able to use relations and clear UI.

**Screenshots**
![scr1](https://user-images.githubusercontent.com/7701755/62336467-c673e180-b513-11e9-8742-076c499ca3e4.png)
![scr2](https://user-images.githubusercontent.com/7701755/62336466-c673e180-b513-11e9-8134-50ca2c50be7f.png)
![scr3](https://user-images.githubusercontent.com/7701755/62336465-c5db4b00-b513-11e9-974e-a58d9f4fe4b1.png)

**System**
- Node.js version: 10.15.1
- NPM version: 6.8.0
- Strapi version: Strapi v3.0.0-beta.14
- Database: PostgreSQL
- Operating system: MacOS 10.14.6

**Comment by soupette** [comment]
According to the [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#models) model names should be lowercased. Regarding the admin UI you need to rename your content types with lowercase names and then delete your `plugin_content_manager_schema` document in your `core_store` collection. Then if you restart your server it should be working properly

**Comment by lauriejim** [comment]
Hello @romanmandryk !
Thank you for reporting this.

We managed this from the Admin Panel because it's not allowed to do what you try to do.
But you still able to create this CamelCamel content type from the command line.
We have to add a validation in the command line.

Can you please use only lowercase value for your content type and attribute name.
Here is the feature request to be able to customize your content types name in the menu https://portal.productboard.com/strapi/1-public-roadmap/c/13-administration-menu

**Comment by romanmandryk** [comment]
Thanks @lauriejim ,
using lowercase everywhere is fine (camel case is just a habit), it just should behave in a same way when creating and editing content type name in Admin and in CLI

**Comment by lauriejim** [comment]
Yes, I agree with that.
Currently not a priority for us but we have to do it.

**Comment by manu-4216** [comment]
I was able to fix this issue by manually editing `projectName/api/contentTypeName/models/contentTypeName.settings.json`.

The `yarn strapi start` works without that error

**Comment by soupette** [comment]
@lauriejim can we close this issue since we can set any name for a content type?

**Comment by derrickmehaffy** [comment]
Well not "any" but camel case names should work, marking as closed.
