### ISSUE TITLE
Reserved "id" model's field name collision

### ISSUE THREAD

**Issue by tomVlt** [strapi/strapi#3717]
Hi,

Using a field name of "id" inside an sql relation is allow, but collides with the auto-generated one at ORM/SQL layer.

**Steps to reproduce the behavior**
Add a new content type.
Add a new field to it.
Use "id" as a field name.

**Expected behavior**
We may, at the most basic point, provide an extra logic inside react input to invalidate "id" string submission. That's just a quick fix. We may add an extra block of logic at model generator/updator layer . I'm new to strapi, no dev env set, I've just completed the quick start guide for now. If someone can provide insights about location and a bit of core logic I would handle one of the solutions with a bit of time.

**Logs**
```
{ [Error: SQLITE_ERROR: duplicate column name: id] errno: 1, code: 'SQLITE_ERROR' }
[2019-08-02T07:50:12.209Z] debug ⛔️ Server wasn't able to start properly.
[2019-08-02T07:50:12.210Z] error Error: SQLITE_ERROR: duplicate column name: id
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utilisateur\AppData\Roaming\npm-cache\_logs\2019-08-02T07_50_12_248Z-debug.log
```

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.14
- Database: Sqlite
- Operating system: Win 64 or GNU/Linux Debian

PS vraiment top de voir une initiative Française. Bonne journée !

**Comment by derrickmehaffy** [comment]
@tomVlt a topic like this was brought up a while ago (can't find the related issue)

The short and sweet answer is, you shouldn't use the name `id` for two reasons:
1) It's a reserved word (trust me I know there isn't a good place to look for those)
2) Strapi already adds that field by default in which the values are assigned by the hook/database itself

I would suggest (depending on what you are using it for) adding a prefix to the name like `itemid` or something of the sort.

**Comment by tomVlt** [comment]
Yes thank you for the workaround ! That's what I did instantly.

I still think the form validation is too permissive, leading to a core hard fail. From where you have to recover manually.

IMO user experience might be affected. Espacially for those using only the WYSIWYG pannel. And as you mention I'm not the first one.
Why not add an extra logic bloc at input level inside the react app ? It's a dirty quick fix but at least it's something.

**Comment by carlosen14** [comment]
This is still happening 

just ran `yarn create strapi-app my-project --quickstart`, create a collection and name a column `id`, then it couldn't restart because of this error.

![image](https://user-images.githubusercontent.com/9368632/76268695-7f319a00-6234-11ea-8520-c8e83b396033.png)
