### ISSUE TITLE
Misleading information in hooks documentation

### ISSUE THREAD

**Issue by daksamit** [strapi/strapi#3719]
I think it is like a little bug in documentation:

Look at https://strapi.io/documentation/3.0.0-beta.x/advanced/hooks.html
inside initialize, `this` is a Function 

![image](https://user-images.githubusercontent.com/7165997/62385239-cea04100-b554-11e9-8e00-08aa13c3214a.png)

if we want to get access to hook config (from defaults) inside initialize function, we can get it:
`this().defaults['myConfig']` or `strapi.config.hook.settings.myhook['myConfig']`

**System**
- Node.js version: 10.15.1
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.13

**Comment by davidkartuzinski** [comment]
@daksamit - Thank you.  Would you like to make a Pull Request?

**Comment by daksamit** [comment]
ok :)
