### ISSUE TITLE
When I create a new user that new user can't access the admin panel.

### ISSUE THREAD

**Issue by arthurbernierjr** [strapi/strapi#3724]
**Describe the bug**

**Steps to reproduce the behavior**
1. Go to 'http://localhost:1337/admin/plugins/content-manager/user?source=users-permissions'
2. Click on '+ Add New User'
3. Create the user by adding username and password and checking confirmed  '....'
4. Add the role authenticated
5. Wait for server to restart
6. Then logout of the admin panel and try to log in with the credentials you created
7. Receive an error
![Screenshot from 2019-08-03 19-50-22](https://user-images.githubusercontent.com/38284764/62417820-f90efe80-b627-11e9-848f-5de566e60dab.png)

**Expected behavior**
I expected to be able to log in to the admin panel as the user I created

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta-14 
- Database: MongoDB via Atlas
- Operating system: Linux PopOS! 18.0.4LTS and OSX Mojave

**Additional context**
I also loggged in to my MongoDB database to ensure that the user was entered into the users collection. they were added to the collection.

**Comment by loongmxbt** [comment]
In Strapi@beta, users are divided into admin users(can access /admin) and normal users for safety concerns I think. You can create admin users by: 1) login with admin; 2) click the top-right admin user name; 3) click "manage the administrators"; 4) click "add new administrator".

**Comment by davidkartuzinski** [comment]
@loongmxbt Gave you the correct instructions.  If you would like to read more about it, we published an article. https://blog.strapi.io/why-we-split-the-management-of-the-admin-users-and-end-users/

**Comment by arthurbernierjr** [comment]
Thankyou

**Comment by soupette** [comment]
I'm closing this issue since there is no "bug" to be fixed.

**Comment by GamerBoy2K** [comment]
Is there any way to give a role to access the admin panel (with limited access) ?

**Comment by MattieBelt** [comment]
@GamerBoy2K https://portal.productboard.com/strapi/1-public-roadmap/c/8-users-roles-permissions-ce-ee

**Comment by Chris533** [comment]
For now you can use [react-admin](https://github.com/nazirov91/ra-strapi-rest) or [bunadmin](https://github.com/bunred/bunadmin-plugin-buncms-strapi-user).

**Comment by ludalex** [comment]
According to Productboard this is planned to be released in Q2. Is there a branch where the development is happening so I can help/test the feature out?

**Comment by sebacampos** [comment]
> Is there any way to give a role to access the admin panel (with limited access) ?

With this **RBAC feature [PR](https://github.com/strapi/strapi/pull/6965/),** `3.1.0` will release the possibility to have 3 admin panel roles... 

Although not sure if will provide '_limited access_' by role. I really need that feature to limit what Editors see in the Strapi Dashboard, so that they can upload content **only** in Articles without me having to build front-end for that action, But won't see anything else from the Dashboard (Other ContentType different from Articles, ContentType Builder, Plugins,  Roles,  etc)
