### ISSUE TITLE
Microsoft Provider Error 500

### ISSUE THREAD

**Issue by Mikeez** [strapi/strapi#3730]
I am unsure about other providers, but the Microsoft provider has error 500 when redirected to:
http://localhost:1337/connect/microsoft

The Azure API seems to be set up correctly based on documentation (has the callback URL)

Error:
> TypeError: Middleware stack must be an array!
>     at Object.compose (C:\Users\msalib\Desktop\DataCentral\backend\node_modules\koa-compose\index.js:20:41)
>     at connect (C:\Users\msalib\Desktop\DataCentral\backend\plugins\users-permissions\controllers\Auth.js:164:34)
>     at async C:\Users\msalib\Desktop\DataCentral\backend\node_modules\strapi\lib\middlewares\router\utils\routerChecker.js:59:20
> [2019-08-06T04:56:49.894Z] debug GET \connect\microsoft (2608 ms)

**System**
- Node.js version: Latest
- NPM version: Latest
- Strapi version: Latest
- Database: MySQL Latest Version
- Operating system: W10 Pro.

**Comment by derrickmehaffy** [comment]
@Mikeez please follow the bug report template and fill out the versions.

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
