### ISSUE TITLE
_q=query returns all entries in quickstart project

### ISSUE THREAD

**Issue by SK-Commit** [strapi/strapi#3732]
**Describe the bug**
As the title says, in quickstart project _q returns all entries. Example: With a field 'title' in content type 'blog', and creating 2-3 entries.
No matter what blogs?_q=query is, all entries is returned.

**Steps to reproduce the behavior**
1. Create content-type 'blog'.
2. Create field 'title'.
3. Create 2-3 entries for type.
4. GET request for blogs?_q=query
5. All entries is returned, no matter what the query matches.

**Expected behavior**
Only return entries matching the query.

**Screenshots**
[Screenshot](https://strapi.slack.com/files/U90SU3GBS/FM2QJH4CU/image.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10
- NPM version: 6.4.1
- Strapi version: beta14
- Database: SQLite
- Operating system: Windows

**Additional context**

**Comment by lauriejim** [comment]
Thank you for reporting this issue @SK-Commit !
We will take a look.

**Comment by SK-Commit** [comment]
BTW. it's only for Quickstart project, i don't think i mentioned this.

**Comment by alexandrebodin** [comment]
Hi @SK-Commit, The quick start uses a Sqlite databases which by default does have fulltext search. What happens si when you run a search we cannot do a where filter so we return everything.

**Comment by SK-Commit** [comment]
_q request is full search by my understanding, and no matter what _q=query is, all data is returned.

**Comment by alexandrebodin** [comment]
Because sqlite doesn't support fulltext search so it basically run SELECT * FROM type. we can disable that and return nothing but there is just no search feature for sqlite

**Comment by SK-Commit** [comment]
That's also what @derrickmehaffy was saying, i just wanted to make you aware that this was happening, I'm using Mongo normally, but wanted to test some features on a new quick project, which included _q requests.

**Comment by derrickmehaffy** [comment]
Can confirm I did mention this is slack that SQLite doesn't support certain indexes

**Comment by alexandrebodin** [comment]
Thank for that. Right now this is intended but we could invert the behaviour if this becomes an isssue in the future.

**Comment by SK-Commit** [comment]
Your call, would be nice to have for other people, when it's mentioned in the docs.

**Comment by derrickmehaffy** [comment]
@alexandrebodin as SQLite generally isn't recommended for production usage maybe just having @davidkartuzinski document that certain features are available if you are using SQLite?

**Comment by alexandrebodin** [comment]
Sure thing we should document it; I'll put that in our documentation backlog and close the issue for now
