### ISSUE TITLE
The same updatedAt in the list file uploaded

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#3738]
Hello
i have one problem with strapi . In the list upload files in the row updated is the same datetime in all rows
my strapi is beta 3
[image](https://user-images.githubusercontent.com/14913444/62546587-07495e80-b864-11e9-898a-194a091ec8cd.png)

**Comment by soupette** [comment]
Please can follow the issue template?

In the meantime I found that the bug is due to the chosen database where the `Updated` row can be either `updatedAt` or `updated_at`.
