### ISSUE TITLE
Microsoft provider not working

### ISSUE THREAD

**Issue by Mikeez** [strapi/strapi#3739]
**Describe the bug**
I only have Strapi backend running and trying to ensure MS Login works. I have set up the Azure Directory and followed the guide.

**Steps to reproduce the behavior**
1. Strapi Start and Login
2. Enable Microsoft Provider
3. Add In Client ID, Private Key (Enable Azure and add URL Redirect)

**Expected behavior**
To be able to login, have microsoft dialog box authenticate me

**Screenshots**
No screen shot but on the console I get error:

> TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
>     at callback (C:\Users\MyUserName\Desktop\backend\project\plugins\users-permissions\controllers\Auth.js:95:16)

On the browser I get error:

> {
> statusCode: 500,
> error: "Internal Server Error",
> message: "An internal server error occurred"
> }

**System**
- Node.js version: 10.0.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2 (Latest)
- Database: MySQL 8
- Operating system: Windows 10

**Additional context**

**Comment by lauriejim** [comment]
Hello! Can you try with the last version of Strapi (beta.14)
Here with the alpha.16 you are not in the latest version of Strapi.

**Comment by Mikeez** [comment]
Oh I did not kow that to be honest. I will try this instantlly.

**Comment by leinue** [comment]
I encoutered this error too.

```shell
[2019-10-23T05:38:22.547Z] error TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
    at Object.callback (/root/strapi-00/node_modules/strapi-plugin-users-permissions/controllers/Auth.js:157:23)
[2019-10-23T05:38:22.547Z] debug GET /auth/google/callback (6 ms) 500
[2019-10-23T05:38:22.585Z] debug GET /favicon.ico (1 ms) 200
```

**Comment by leinue** [comment]
> I encoutered this error too.
> 
> ```shell
> [2019-10-23T05:38:22.547Z] error TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
>     at Object.callback (/root/strapi-00/node_modules/strapi-plugin-users-permissions/controllers/Auth.js:157:23)
> [2019-10-23T05:38:22.547Z] debug GET /auth/google/callback (6 ms) 500
> [2019-10-23T05:38:22.585Z] debug GET /favicon.ico (1 ms) 200
> ```

fixed

**Comment by Mikeez** [comment]
> > I encoutered this error too.
> > ```shell
> > [2019-10-23T05:38:22.547Z] error TypeError: Cannot read property 'Symbol(Symbol.iterator)' of object
> >     at Object.callback (/root/strapi-00/node_modules/strapi-plugin-users-permissions/controllers/Auth.js:157:23)
> > [2019-10-23T05:38:22.547Z] debug GET /auth/google/callback (6 ms) 500
> > [2019-10-23T05:38:22.585Z] debug GET /favicon.ico (1 ms) 200
> > ```
> 
> fixed

Can you tell me how you fixed it :)? Also, can you tell me how you are using it to login LOL? The flow

**Comment by lauriejim** [comment]
I just created a new app, followed the docs and all is working fine.
