### ISSUE TITLE
Wanted to implement Transaction for multi-transaction

### ISSUE THREAD

**Issue by mtmsuhail** [strapi/strapi#3740]
**Describe the topic**
How can I implement Transaction for multiple collection insert?

**Your suggestions for this topic**
I don't have any Idea

**Screenshots**

**Code snippets**

**Additional context**
Need to implement MongoDB transaction described here https://docs.mongodb.com/manual/core/transactions/

**Comment by derrickmehaffy** [comment]
This is not currently supported @mtmsuhail .

A feature request already exists for multi - insert:
https://portal.productboard.com/strapi/1-public-roadmap/c/42-bulk-route-to-create-multiple-entries

For now I'm marking this as closed. Thank you.
