### ISSUE TITLE
Unique field not working in SQLite

### ISSUE THREAD

**Issue by craigharman** [strapi/strapi#3741]
**Describe the bug**
Assigning "unique" to a content type string field but am still able to use non-unique values.

I have read https://github.com/strapi/strapi/issues/1189 which doesn't mention SQLite.

**Steps to reproduce the behavior**
1. Install Strapi using --quickstart defaults
2. Create a new content type with a string field that has the "unique" config setting set
3. Create an item with "test" in the unique field from 2
4. Repeat step 2 with "test" in the unqiue form field
4. Both items are added

**Expected behavior**
The item in step 4 should be rejected as it is not unique

**Screenshots**
See last 3 entries below. 1 was added via api, 2 via admin interface.

![Screen Shot 2019-08-07 at 12 36 47 pm](https://user-images.githubusercontent.com/324026/62595358-a2980d80-b910-11e9-919c-c7a86efc7afe.png)

**System**
- Node.js version: 10.16
- NPM version:
- Strapi version: v3-beta-14
- Database: SQLite
- Operating system: OS X

**Comment by derrickmehaffy** [comment]
@craigharman https://github.com/strapi/strapi/issues/1189 does address this issue as SQLite does use bookshelf and knex hooks. So while it may not be directly mentioned it is included regardless.

Due to that, I'm marking this as a duplicate.
