### ISSUE TITLE
Remote debug not fully working

### ISSUE THREAD

**Issue by ikesler-tenengroup** [strapi/strapi#3743]
**Describe the bug**
I'm running strapi using next command in terminal: `NODE_OPTIONS='--inspect=0.0.0.0:9229' strapi develop`. Remote debugger connects successfully to the running process, but breakpoints are not working - not being hit and not even recognized by the debugger - missing "checkmark" on it.
At the same time:
- Breakpoints are working in `node_modules/strapi/bin/strapi.js` file.
- Breakpoints are working in any file when IDE starts the process (tried in IntelliJ IDEA).
- Remote debug is working in other (non-strapi) projects.

It would be really nice to have remote debug fully working in order to debug Strapi inside Docker container. Currently it is not working not in Docker nor locally.

**Steps to reproduce the behavior**
1. Run `NODE_OPTIONS='--inspect=0.0.0.0:9229' strapi develop`
2. Attach debugger to localhost:9229
3. Set a breakpoint in an API controller or plugin controller
4. Perform an action that runs the code line where breakpoint is set

**Expected behavior**
Breakpoint should be hit - execution should stop and IDE should activate the breakpoint. Before being hit breakpoint should be "recognized" by debugger - "checkmark" in IntelliJ IDEA.

**System**
- Node.js version: 12.7.0 or 11.7.0 
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.11 
- Database: Postgre
- Operating system: Ubuntu

**Additional context**
Issue happens in IntelliJ Idea, Visual Studio Code, Chrome Dev tools debugger. Issue does not occur when IDE runs the process (checked in IntelliJ only).

**Comment by lauriejim** [comment]
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by alexandrebodin** [comment]
@ikesler-tenengroup, can you try do this with yarn start ? 

yarn develop runs a cluster that starts strapi in a sub process this might be the reason you cannot debug as you wish

**Comment by ikesler-tenengroup** [comment]
hey
thank you for reply
indeed, `NODE_OPTIONS='--inspect=0.0.0.0:9229' strapi start` allowed me to debug.
But it also means that I cannot use auto-refresh provided by `strapi develop` (reload process upon file change). Could you please clarify a couple of things:
1. "cluster: - you mean https://nodejs.org/api/cluster.html ?
2. Is there a chance that I can combine both debug and auto-refresh?
3. Can I somehow make that "cluster" to start sub process with --inspect flag?

Thank you very much.

**Comment by keepitsimple** [comment]
Any updates on how to debug strapi?

**Comment by maxbaluev** [comment]
This is very slowing development process!

**Comment by alexandrebodin** [comment]
You can look at the code in here https://github.com/strapi/strapi/blob/master/packages/strapi/lib/commands/develop.js

to create a custom develop command to easily debug

**Comment by ikesler-tenengroup** [comment]
I have come up with next solution:
having next script in `develop.js` file (my custom one):
```
'use strict';
const strapi = require('strapi');
strapi({ dir: process.cwd(), autoReload: true }).start();
```
I'm using [nodemon](https://nodemon.io/) by next command: `nodemon --inspect=0.0.0.0:9228 develop.js`

Now I can attach to 9228 by debugger.

**Comment by keepitsimple** [comment]
Guys,
strong suggestion to make some recommendations in documentation how to debug it remotely.
Strapi 3.x is big application and there are a lot of gaps in the documentation & in FAQ; responses on questions in Slack and on Stackoverflow are way to slow too.

     PLEASE GIVE AS A TOOL TO INVESTIGATE Strapi

It will give us a chance answer on questions ourselve.

**Comment by keepitsimple** [comment]
@ikesler-tenengroup Thank you so much. 
Finally I can debug STRAPI in my docker container.

**Comment by alexandrebodin** [comment]
Closing this issue and passing the request for documentation to the people who can make it :)

**Comment by ChinaShrimp** [comment]
Thanks @ikesler-tenengroup , it helps me a lot!

Wondering whether this file could be generated by strapi scaffold?

**Comment by CKGrafico** [comment]
Thanks @ikesler-tenengroup 
If someone is using VSCode and Docker + Docker compose we have this config:
launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Docker: Attach to Node",
      "type": "node",
      "request": "attach",
      "port": 9229,
      "address": "localhost",
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "/opt/app",
      "protocol": "inspector"
    }
  ]
}
```
server.js
```
const strapi = require('strapi');

strapi({ dir: process.cwd(), autoReload: process.env.NODE_EV === 'development' }).start();

```
package.json
```
"dev:docker": "node --inspect=0.0.0.0 server",
 "start": "node server",
```

**Comment by EternalBlack** [comment]
Is this still applicable to the latest Stable release (3.0.1)?

I use `package.json`
```
    "debug": "node --inspect=0.0.0.0:9229 ./node_modules/strapi/bin/strapi develop"
```
`launch.json`
```
{
      "type": "node",
      "request": "attach",
      "name": "Attach to strapi",
      "port": 9229
    }
```
and it tells me that the debugger is attached but like described by others it doesn't trigger the breakpoint and I'm not quite sure if I got the correct `server.js` but it seems like there were some changes made since then.

**Comment by renz45** [comment]
I fixed this in the above PR, but for anyone on an older version, you can create a file with the following to fix the inspector:

*develop-inspect.js*
```javascript
const cluster = require('cluster');
const inspector = require('inspector');
const develop = require("strapi/lib/commands/develop.js")

// propagate the port number to the new cluster, normally each time a cluster forks, it assigns a random ip to the inspector
cluster.setupMaster && cluster.setupMaster({
  inspectPort: process.debugPort
});

// Close inspector manually on fork so we can keep reusing the same inspector window in new forks.
cluster.on('fork', (worker) => {
  inspector.close()
});

// Call the original develop command
develop(false, true)
```
Then run it: `node --inspect develop-inspect.js`

**Comment by mauroeparis** [comment]
The PR was sadly closed but the fix @renz45 recommends still works! 👌

**Comment by Florian-crg** [comment]
Well, I am using strapi v4.4.7 and I still need the develop-inspect.js... 

Btw on v4 and more replace `const develop = require("strapi/lib/commands/develop.js")` by `const develop = require("@strapi/strapi/lib/commands/develop");`

**Comment by Florian-crg** [comment]
> I fixed this in the above PR, but for anyone on an older version, you can create a file with the following to fix the inspector:
> 
> _develop-inspect.js_
> 
> ```js
> const cluster = require('cluster');
> const inspector = require('inspector');
> const develop = require("strapi/lib/commands/develop.js")
> 
> // propagate the port number to the new cluster, normally each time a cluster forks, it assigns
> // a random ip to the inspector
> cluster.setupMaster && cluster.setupMaster({
>   inspectPort: process.debugPort
> });
> 
> // Close inspector manually on fork so we can keep reusing the same inspector window in new forks.
> cluster.on('fork', (worker) => {
>   inspector.close()
> });
> 
> // Call the original develop command
> develop(false, true)
> ```
> 
> Then run it: `node --inspect develop-inspect.js`

Well, I am using strapi v4.4.7 and I still need the develop-inspect.js...

Btw on v4 and more replace const develop = require("strapi/lib/commands/develop.js") by const develop = require("@strapi/strapi/lib/commands/develop");

**Comment by bajiraonakamoto** [comment]
> 

Work to me! Thanks!

**Comment by bajiraonakamoto** [comment]
Solution from @a8c71 work to me. I just adding `"sourceMap": true` in `tsconfig.json`

**Comment by t-fritsch** [comment]
For anyone still looking for this feature, in 4.15.0 with vscode, here is a solution that seem to work and to provide both :
- live reloading (as regular `npm run develop` command does)
- AND vscode debugger auto-reconnect on reload (no need to kill/relaunch debugger on each file save/modification)

1. as @bajiraonakamoto said, we have to add `sourceMap` key to `tsconfig.json` :
    ```json
      "compilerOptions": {
        "outDir": "dist",
        "rootDir": ".",
        "sourceMap": true
      },
     ```
2. create a `.vscode/launch.json` file (see [vscode documentation](https://code.visualstudio.com/Docs/editor/debugging#_launch-configurations)) and generate a "npm" launch configuration that starts the develop script (nothing changed from the configuration generated by vscode by default apart task name and last runtimeArgs) : 
    ```json
    {
        "name": "launch & debug strapi develop",
        "request": "launch",
        "runtimeArgs": [
            "run-script",
            "develop"
        ],
        "runtimeExecutable": "npm",
        "skipFiles": [
            "<node_internals>/**"
        ],
        "type": "node",
    }
    ```

I first tried to use "attach" mode, but with no chance (live reload was working but debugger was disconnected at first reload), so sticking to make vscode launch the `develop` command..

**Comment by fl034** [comment]
I'm using strapi in a dockerized environment, both for local development and production. That's why I needed/wanted to use the `attach` request instead of `launch`.

I got it to work with the following approach:

**launch.json**

```json
{ "configurations": [{
  "type": "node",
  "request": "attach",
  "name": "Attach to strapi locally",
  "address": "localhost",
  "port": 9229,
  "localRoot": "${workspaceFolder}",
  "remoteRoot": "/opt/app"
}]}
```

Then I have an extra compose file for debugging that I append (`-f`) to my other develop compose file

**docker-compose.debug.yml**

```yaml
  api:
    ports:
      - 9228-9229
    environment:
      - NODE_OPTIONS=--inspect=0.0.0.0:9228
```

With the `NODE_OPTIONS` I inject --inspect via the environment. You can inject this also in other ways.

In the launch.json I use port 9229 because during container startup I'm getting `Starting inspector on 0.0.0.0:9228 failed: address already in use` so after strapi is launched it's listening on 9229 then.

**Comment by shaunakv1** [comment]
I am looking for right config to use debug with docker and vs code. any update on config that works?

**Comment by thatsgolden** [comment]
> Is this still applicable to the latest Stable release (3.0.1)?
> 
> I use `package.json`
> 
> ```
>     "debug": "node --inspect=0.0.0.0:9229 ./node_modules/strapi/bin/strapi develop"
> ```
> 
> (`"debug": "node --inspect=0.0.0.0:9229 ./node_modules/strapi/bin/strapi start"` works fine though)
> 
> `launch.json`
> 
> ```
> {
>       "type": "node",
>       "request": "attach",
>       "name": "Attach to strapi",
>       "port": 9229
>     }
> ```
> 
> and it tells me that the debugger is attached but like described by others it doesn't trigger the breakpoint and I'm not quite sure if I got the correct `server.js` but it seems like there were some changes made since then.

tried in Webstorm successfully 👍

**Comment by thatsgolden** [comment]
or
```
    "develop": "strapi develop -- --inspect=0.0.0.0:9229",
```
