### ISSUE TITLE
Cannot set date in beforeCreate hook

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#3747]
**Describe the bug**
I've created a Date field in a "news" page. When administrator creates a new instance of "news", he can optionally choose the date, or omit it. When he omits the date, i want to pre fill it automatically, using `beforeCreate` hook in "News.js". 

**Steps to reproduce the behavior**
1. Create new content type "news"
2. Add "date" field, don't make it required by default
3. create a new "news" page without filling "date" field and save it. In database (MySQL in my case) this field would be empty.
4. try to add code from **code snippets** section in order to pre-fill the date, when the date field is empty.

**Expected behavior**
Date field would be filled using `beforeCreate` hook.

**Code snippets**
```
beforeCreate: async (model, attrs) => {
  if (attrs['Date'] === null) {
    model.set('Date', '2030-00-00 00:00:00+00');
  }
}
```

**System**
- Node 12
- NPM version: 6.10
- Strapi version: beta.14
- Database: MySQL
- Operating system: macOS 10.14.6

**Additional context**
When i create the "news" page, if user didn't fill the date field, i want it to be pre-filled automatically. But `model.set()` seems to have no effect when i create a new page.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by webcoderkz** [comment]
@derrickmehaffy i just updated my issue. Maybe you could give me an answer?

**Comment by alexandrebodin** [comment]
Hi try doing attrs[`dateˋ] = ‘2030-00-00...’

**Comment by derrickmehaffy** [comment]
^^^ what Alex said but for now the date needs to be a MySQL accepted format `YYYY-MM-DD hh:mm:ss`

**Comment by webcoderkz** [comment]
@alexandrebodin thanks, could you explain, why `model.set()` won't work? I couldn't find any documentation regarding this.

**Comment by lauriejim** [comment]
You will have to use this example. Here is to slugify the content but custom this function to answer your need.
```
// const slugify = require('slugify');

beforeSave: async (model, attrs, options) => {
  if (options.method === 'insert' && attrs.title) {
    model.set('slug', slugify(attrs.title));
  } else if (options.method === 'update' && attrs.title) {
     attrs.slug = slugify(attrs.title);
  } 
}
```

**Comment by webcoderkz** [comment]
@lauriejim there's no documentation about `model` and `attrs`? So, `model` is used when i use `beforeCreate` or insert?

**Comment by webcoderkz** [comment]
```
  beforeSave: async (model, attrs, options) => {
    // mysql date format: 2019-08-01 00:00:00+00
    let today = new Date();
    let dd = today.getDate();
    let mm = today.getMonth() + 1; //January is 0!
    let yyyy = today.getFullYear();

    if (dd < 10) {
      dd = '0' + dd;
    }

    if (mm < 10) {
      mm = '0' + mm;
    }

    let hours = today.getHours();
    let minutes = today.getMinutes();
    let seconds = today.getSeconds();

    const result = `${yyyy}-${mm}-${dd} ${hours}:${minutes}:${seconds}+00`;

    if (attrs['Date'] === null && options.method === 'insert') {
      model.set('Date', result);
    } else if (options.method === 'update' && attrs['Date'] === null) {
      attrs['Date'] = result;
    }
  }
```

Only update method is fired, when it's insert (creating a new page) it doesn't set my `Date` field in db.

**Comment by lauriejim** [comment]
Did you send a `Date` value in your create request?
Bookshelf did not allow you to set a value that not exists in your request.

**Comment by derrickmehaffy** [comment]
Closing this and linking it to the master Review Lifecycles Issue: https://github.com/strapi/strapi/issues/1443

It will be reviewed with all the rest of the Lifecycle issues. Thank you!
