### ISSUE TITLE
Is studio.strapi active in v3?

### ISSUE THREAD

**Issue by shinokada** [strapi/strapi#3749]
My Strapi vesion is 1.6.4. I think is is v3.0.0.-beta.14. When I run `strapi new cms --quickstart`, I get info and warning.

```
info: Your new application `cms` is ready at `/Users/shinokada/Projects/Strapi/tutorial/cms`.
warn: You do not have a `.strapirc` file at `/Users/shinokada`.
warn: First, you need to create an account on http://studio.strapi.io/
warn: Then, execute `$ strapi login` to start the experience.
```

When I check the doc at[https://strapi.io/documentation/3.0.0-beta.x/]( https://strapi.io/documentation/3.0.0-beta.x/), there is no doc about Studio. Is it still recommended to create an account and run `strapi login`?

**Comment by lauriejim** [comment]
Hello! The sutdio is only for the v1.
In the v3 the studio is inside your application.

Do not forget the `@beta` tag when you install strapi to use the v3
https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_1-install-strapi-globally
