### ISSUE TITLE
Many to many additional fields

### ISSUE THREAD

**Issue by benjamincanac** [strapi/strapi#3750]
Hi,

First of all, thanks for Strapi, it's awesome! I've been able to do everything I've wanted to do using Strapi, except this.

I can't find a way to add and handle extra fields in postgres many-to-many relation.

My use case:

I have Song and User models, I have a pivot table to link songs and users, however I would like to be able to add a state column in the pivot table to say this User added this song in state `todo` for example.

Thanks!

**Comment by lauriejim** [comment]
Hello! this feature is not available in strapi.
We do not manage `pivot` with bookshelf.

**Comment by benjamincanac** [comment]
Hi,

Will you ever handle it? If not, would you accept a PR?

**Comment by derrickmehaffy** [comment]
@benjamincanac You are welcome to submit a PR to be reviewed.

**Comment by lauriejim** [comment]
I highly suggest you contact @alexandrebodin if you want to work on this point.
To make this feature work you will have to touch really tricky part of the codebase.
To make sure you will code in the right place and in the right way, please do nothing without speaking with @alexandrebodin.

**Comment by Adambrb** [comment]
Hi! Is there a solution please ?

**Comment by alexandrebodin** [comment]
Hi this feature is not supported. But you can always create two one-many relations with 3 models. so you can add the fields you want in the pivot table.

**Comment by Adambrb** [comment]
Ok i will do like that thanks.

**Comment by ariel-diaz** [comment]
Hi! Is there a solution please ?

**Comment by derrickmehaffy** [comment]
@ariel-diaz see Alex's comment: https://github.com/strapi/strapi/issues/3750#issuecomment-645229100
