### ISSUE TITLE
Are there any updated Doc for 1.6.4?

### ISSUE THREAD

**Issue by shinokada** [strapi/strapi#3751]
I just installed Strapi 1.6.4.

It seems the documentation is not updated to 1.6.4.

1. When I run `strapi new my-project --quickstart`, it is supposed to open a browser. But it doesn't. So I have to run `strapi start`, not `strapi develop` which is in the documenation.

2. When I login, the look is completely different from any tutorials. There are no plugins nor general. There is a Model and Users on the left panel but nothing under Model.
![Screen Shot 2019-08-09 at 22 10 08](https://user-images.githubusercontent.com/147320/62781231-7b993180-baf2-11e9-9dc6-92224def1de3.png)
 
3. I have run `strapi generate api car name:string year:integer license:string` to create a model.

etc.

Are there any updated documentation I can read?

**Comment by derrickmehaffy** [comment]
@shinokada Strapi v1 is no longer supported. The docs are for Strapi v3 when you install globally you need to use `npm i -g strapi@beta`

Marking as closed as no longer supported version

**Comment by shinokada** [comment]
I used `npm i -g strapi@beta`, but when I run `strapi -v` it shows 1.6.4.
