### ISSUE TITLE
link a file to two entries in order, the first entry will lost the file link.

### ISSUE THREAD

**Issue by hhzrz** [strapi/strapi#3752]
**Describe the bug**
One file can't be linked to more entries.

**Steps to reproduce the behavior**
1. Upload a file and get the file `id`.
2. Create a content-type named `foo` with a media field named `img`.
3. POST a new record `r1` to `foo` with the media field set to `id`.
4. Check the new record `r1` in admin panel, the file is linked to this record correctly.
5. Do step 3 again: POST a new record `r2` to `foo` with the media field set to `id`.
6. Check both `r1` and `r2`, you'll see only `r2` linked with the file, the `img` field of `r1` becomes empty.

**Expected behavior**
The file should be linked to both `r1` and `r2`.

**System**
- Node.js version: node10
- NPM version: 6.9
- Strapi version: 3.0.0-beta.14
- Database: mongodb:4.0
- Operating system: ubuntu16.04

**Comment by lauriejim** [comment]
Hello!
The current feature we have in Strapi it to let you attach an image to one entry.
To be able to add an email to multiple entries we need to develop a Media Library
Please can you add your feedback on this roadmap item please https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities
