### ISSUE TITLE
Cannot find module strapi-hook-knex

### ISSUE THREAD

**Issue by LyoRepo** [strapi/strapi#3753]
facing this issue during MYSQL configuration:

ubuntu@ip-10-0-2-105:~/painel$ strapi develop
[2019-08-09T13:47:08.070Z] debug ⛔️ Server wasn't able to start properly.
[2019-08-09T13:47:08.072Z] error Error: Cannot find module 'strapi-hook-knex'
Require stack:
- /home/ubuntu/painel/node_modules/strapi/lib/core/load-hooks.js
- /home/ubuntu/painel/node_modules/strapi/lib/core/index.js
- /home/ubuntu/painel/node_modules/strapi/lib/Strapi.js
- /home/ubuntu/painel/node_modules/strapi/lib/index.js
- /home/ubuntu/painel/node_modules/strapi/lib/commands/develop.js
- /usr/lib/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at loadHookDependencies (/home/ubuntu/painel/node_modules/strapi/lib/core/load-hooks.js:67:42)
    at async Promise.all (index 0)
    at async module.exports (/home/ubuntu/painel/node_modules/strapi/lib/core/load-hooks.js:16:3)
    at async Promise.all (index 5)
    at async Strapi.load (/home/ubuntu/painel/node_modules/strapi/lib/Strapi.js:248:9)
    at async Strapi.start (/home/ubuntu/painel/node_modules/strapi/lib/Strapi.js:123:7)

**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
@LyoRepo Please completely fill out the required template.

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
