### ISSUE TITLE
connection test failed; cannot find module utils/connectivity.js

### ISSUE THREAD

**Issue by KrzysztofWelc** [strapi/strapi#3758]
**Describe the bug**
Everytime when I try to create new project with strapi new command, I get error; When I choose custom installation, no matter what configuration I provide, i get error "⛔️ Connection test failed: Cannot find module 'C:\Users\Krzysiek\AppData\Local\Temp\strapi
622d08cce2e8\node_modules\strapi-hook-bookshelf\lib\utils\connectivity.js'." I didn't have such an error using strapi@alpha. I've tried to install strapi with yarn and npm also.

**Steps to reproduce the behavior**
1. Open console
2. run ```strapi new <project_name>```
3. choose custom installation
4. provide configuration 
5. see this error

**Expected behavior**
create new strapi project

**System**
- Node.js version: v10.15.0 
- Yarn version: 1.13.0
- NPM version: 6.5.0
- Strapi version: 3.0.0-beta.14 
- Database: mysql 
- Operating system: windows 10

**Comment by lauriejim** [comment]
Hello! You have an issue that mentions`alpha` version and you look using `beta` version of strapi.
I suggest removing strapi globally from your computer.
You can then install strapi@beta globaly or use `npx create-strapi-app my-project`
I suggest the `npx` option.

**Comment by KrzysztofWelc** [comment]
I have tried both, but still getting this same error, no matter if I try to use mysql or mongo. ```strapi -v``` tells that i'm using strapi 3.0.0-beta.14. I have even tried to reinstall yarn and node

**Comment by lauriejim** [comment]
Maybe check this link https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

**Comment by elliottross23** [comment]
I had the same issue on mac OS catalina and was able to create a new project using the CLI command

I used this command:
`strapi new cms --dbclient mongo --dbhost 127.0.0.1 --dbsrv false--dbname my-db-name --dbssl false --dbport 27017 --dbusername none --dbpassword none --debug`

**System**
- node -v **10.15.3**
-npm -v **6.9.0**
- strapi **3.0.0-beta.18**
-database **mongo**
- operating system **macOS Catalina**

**Comment by jeremyccrane** [comment]
Thanks @elliottross23 ! I was having the same issue with *strapi@3.0.0-beta.18* while attempting to create a new project using *MongoDB*

**Comment by vSanjo** [comment]
@elliottross23's plan works great - but there's a typo in his command.

`strapi new cms --dbclient mongo --dbhost 127.0.0.1 --dbsrv false --dbname project-cms --dbssl false --dbport 27017 --dbusername none --dbpassword none --debug`

Hopefully this helps - what a pain!

**Comment by elliottross23** [comment]
@vSanjo ah good catch and yes you will likely have to update those. When I tried leaving them empty it told me I needed to have one.

**Comment by alexandrebodin** [comment]
Hi, This has been fixed in beta.18.1 ;)

**Comment by matepaiva** [comment]
I am having this problem trying to install it via `npx create-strapi-app test_project` in digital ocean ubutun 20.04, node 15.0.1 and npm 7.0.3.

**Comment by derrickmehaffy** [comment]
`node 15.0.1 and npm 7.0.3` 

Node 15 is not supported and will never be supported. We only support node "even" releases which go LTS. At the moment, the maximum we support is Node v14 and NPM v6

**Comment by matepaiva** [comment]
Apparently, downgrading node and npm to the latest LTS version did the trick.
```
$ node --version
v14.15.0
$ npm --version
6.14.8
```

**Comment by matepaiva** [comment]
Thank you for the information @derrickmehaffy

**Comment by itsMattShull** [comment]
@matepaiva were you able to get mysql config working?  I'm using the same versions of node and npm that you mentioned a couple of posts up but I still get `⛔️ Connection test failed: connect ECONNREFUSED 127.0.0.1:3306`.  The database in mysql is already created but has no tables.

**Comment by matepaiva** [comment]
@itsMattShull Your problem is not the same as I was having ─ the error message is different. Maybe your MySQL config is not allowing connection with a password?

**Comment by dewald-els** [comment]
Don't know if this is still a problem. But It's happening to me when trying to setup Strapi with MongoDB on MacOS with M1. 

<img width="991" alt="image" src="https://user-images.githubusercontent.com/10051247/125159050-43367e00-e175-11eb-8ea4-c97f1d1403b3.png">

I can connect to the MongoDB instance using the credentials. First time user and can't find any other posts about this. 

**Environment:**
MongoDB shell version v4.4.5
Node v16.4.2
Npm v7.18.1

**Comment by 1ur11** [comment]
> Don't know if this is still a problem. But It's happening to me when trying to setup Strapi with MongoDB on MacOS with M1.
> 
> <img alt="image" width="991" src="https://user-images.githubusercontent.com/10051247/125159050-43367e00-e175-11eb-8ea4-c97f1d1403b3.png">
> 
> I can connect to the MongoDB instance using the credentials. First time user and can't find any other posts about this.
> 
> **Environment:**
> MongoDB shell version v4.4.5
> Node v16.4.2
> Npm v7.18.1

@dewald-els I have similar issue on macOs.
Issue can be solved with using **Node v14** instead v16.

**Comment by dewald-els** [comment]
@1ur11 thanks for the reply! I solved it by using the quick start template and manually entering the mongodb connection in the database.js file. 

On a side note, I can’t get node 14 working on the M1 Mac. Which is why I’m using v16 instead.

**Comment by derrickmehaffy** [comment]
> Which is why I’m using v16 instead.

Just a heads up the v3 doesn't support Node 16 and you will most likely hit issues, we are planning Node 16 support in our v4 coming soon.
