### ISSUE TITLE
After npm install strapi@beta -g and strapi -v shows 1.6.4 not v3 

### ISSUE THREAD

**Issue by shinokada** [strapi/strapi#3760]
**Describe the bug**

After npm install strapi@beta -g and strapi -v shows 1.6.4 not v3 

**Steps to reproduce the behavior**

```
npm install strapi@beta -g
npm -g ls --depth=0
/Users/shinokada/.nvm/versions/node/v10.15.3/lib
...
└── strapi@3.0.0-beta.14
strapi -v
1.6.4
...
Package        Current         Wanted  Latest  Location
strapi   3.0.0-beta.14  3.0.0-next.17   1.6.4  global
```

**Expected behavior**

I am expecting `strapi -v` shows version 3.

**Screenshots**

<img width="636" alt="Screen Shot 2019-08-10 at 17 08 54" src="https://user-images.githubusercontent.com/147320/62819539-940c5900-bb91-11e9-835d-fd93279acca8.png">

**System**
- Node.js version: v10.15
- NPM version: v6.10.3
- Strapi version: 1.6.4
- Operating system: macOS 10.14.6

**Comment by SaulPuentes** [comment]
Same here.

Do you find the solution @shinokada?
