### ISSUE TITLE
Update JSON save as String with Bookshelf

### ISSUE THREAD

**Issue by rejifald** [strapi/strapi#3763]
**Describe the bug**
After first updating entry with json fields, json fields becomes strings.

**Steps to reproduce the behavior**
1. Create model with json fields
2. Create entry with some json data
3. Update created entry (IMPORTANT: Do this through generated API, not through Admin Panel)
3. Look at the response

**Expected behavior**
Created entry has json data inside fields which created with json type

**Code snippets**
Update model request
```
addresses: []
categories: [1]
description: null
id: "50"
isVIP: 0
lang: "ru"
links: []
name: "dsadas"
phones: []
positions: [{category: 1, position: 1}]
region: "cern"
```
Response
```
addresses: "[]"
categories: [{id: 1, name: "Housing", lang: "en", parent: null, slug: "Housing",…}]
created_at: "2019-08-10T21:35:15.281Z"
description: null
id: 50
isVIP: 0
lang: "ru"
links: "[]"
name: "dsadas"
phones: "[]"
positions: "[{"category":1,"position":1}]"
region: "cern"
slug: "dsadas-423617"
updated_at: "2019-08-10T21:35:24.678Z"
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.14
- Database: sqlite
- Operating system: MacOS

**Comment by lauriejim** [comment]
This issue has been fixed in `develop` branch - this will be released with the **Group** feature

**Comment by derrickmehaffy** [comment]
I can confirm this issue as well, quite annoying :P
