### ISSUE TITLE
update instead post

### ISSUE THREAD

**Issue by secreal** [strapi/strapi#3772]
**Describe the bug**
hi, im trying to use strapi for existing database,
I have made the required fields in the api folder similar to the fields in the database with json files and have success with getAll, but I have a problem when creating a new record, I post with the correct parameters, but instead of creating a new record, the strapi doing update instead of creating new record (database postgresql), id was primary key with guid generated by UI

**Steps to reproduce the behavior**
1. create new model with id = string and increment false
2. send post to new model
3. look at the database
3. look at the debug message

**Expected behavior**
new record is created on the database table

**Screenshots**
![image](https://user-images.githubusercontent.com/586113/62884183-15194b00-bd60-11e9-8ba6-1391089ef660.png)

**Code snippets**
```
{
  "connection": "connectiontwo",
  "collectionName": "network_connection",
  "info": {
    "name": "NetworkConnection",
    "description": ""
  },
  "options": {
    "increments": false,
    "comment": "",
    "timestamps": false
  },
  "attributes": {
    "id": {
      "type": "string"
    },
    "barcode": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "from_connector_type": {
      "type": "string"
    },
    "from_module_name": {
      "type": "string"
    },
    "from_port_number": {
      "type": "integer"
    },
    "install_date": {
      "type": "date"
    },
    "is_from_patch_panel_rear": {
      "type": "integer"
    },
    "is_to_patch_panel_rear": {
      "type": "integer"
    },
    "length": {
      "type": "float"
    },
    "manufacturer": {
      "type": "string"
    },
    "model_name": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "part_number": {
      "type": "string"
    },
    "serial_number": {
      "type": "string"
    },
    "state_flag": {
      "type": "string"
    },
    "state_last_synchronized": {
      "type": "biginteger"
    },
    "state_last_updated": {
      "type": "biginteger"
    },
    "to_connector_type": {
      "type": "string"
    },
    "to_module_name": {
      "type": "string"
    },
    "to_port_number": {
      "type": "integer"
    },
    "cable_type_id": {
      "type": "string"
    },
    "from_id": {
      "type": "string"
    },
    "to_id": {
      "type": "string"
    }
  }
}
```
and this error message
```
[2019-08-12T16:13:06.873Z] error CustomError: No Rows Updated
    at Child.<anonymous> (D:\deploy\dco-cable-sync-backend\node_modules\bookshelf\lib\model.js:1136:25)
    at Child.tryCatcher (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\deploy\dco-cable-sync-backend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
[2019-08-12T16:13:06.895Z] debug POST /network_connection (196 ms)
```

and this the result when i already have that row in the database
```
[2019-08-12T16:15:14.190Z] debug POST /network_connection (81 ms)
```

it was returning the field of table with updated value

**System**
- Node.js version: 10.16.2
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.14
- Database: postgresql
- Operating system: windows server 2019

**Additional context**
i suspect the problem happen because i don't set any primary key on my model, but i didn't know how to add primary key to model, except the field id itself

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by secreal** [comment]
ok

**Comment by derrickmehaffy** [comment]
The problem here I think is related to:
```
    "id": {
      "type": "string"
    },
```

Strapi injects an ID field already and if you are using a UUID: https://strapi.io/documentation/3.0.0-beta.x/guides/models.html#model-options

As a side note, I highly recommend that you **do not use an existing database** especially if another system is writing to it. Strapi should be the only application writing data to the database, in which case I would suggest that you export the data and format the data itself to match your requirements and structure built in Strapi, not the other way around.

**Comment by secreal** [comment]
unfortunately, I use strapi to change the database value that other applications have provided to do ETL, and unfortunately, only one of these tables uses id, whereas other tables do not use id
![image](https://user-images.githubusercontent.com/586113/62908231-2767a900-bda1-11e9-87dd-d43042dc85c0.png)
https://sxwhelpcenter.ecostruxureit.com/display/public/DCIMDEVELOPER/ETL+Import+Database

is there an alternative to doing it manually in this table only?
