### ISSUE TITLE
After 24h, admin users and API permissions are reset using Heroku

### ISSUE THREAD

**Issue by matthieusibille** [strapi/strapi#3776]
**Describe the bug**

When deployed and heroku, after 24h the admin users and api permissions are reset. You have to recreate an admin if you want to log in the strapi administration. 
- During this 24h period, everything works without any issue.
- Content types and database settings are still there, only admin users and api permissions are wiped.

**Steps to reproduce the behavior**

1. install and init a strapi project locally
2. configure an admin user and api permissions
3. create a content type, add some posts
4. configure api permissions
5. deploy on heroku with heroku CLI or with github
6. wait 24h
7. after 24h admin users and api permissions are reset and need to be reconfigure

**Expected behavior**

admin users and api permissions should not reset after any period of time

**System**

_Heroku_
- app is using hobby dynos
- node 12.8
- npm 6.10.3
- strapi 3.0.0-beta.15
- operating system Linux (i guess)

_On my computer_
- node 10.15.2
- npm 6.4.1
- strapi 3.0.0-beta.15
- operating system windows 10

_Database_
- mLabs (MongoDB)

**Side note** 
I did not configure anything in Configurations > Serveur, i left everything as it is. I only configure Database development and production.

One thing i don't understand is where admin users and api permissions are stored, is it in the database or in strapi files?

Thank you for your help

**Comment by derrickmehaffy** [comment]
@matthieusibille they are stored in the database. This sounds like something was configured to use SQLite (using --quickstart) and was never adjusted

**Comment by matthieusibille** [comment]
@derrickmehaffy Thank you for your response.
Where can i change this? in Configurations > Database, i don't see any mention of SQLite.

**Comment by derrickmehaffy** [comment]
I would check your database.json @matthieusibille I'm entirely just guessing as that is the only way those items would be wiped is if they were stored somewhere other than your database.

**Comment by matthieusibille** [comment]
@derrickmehaffy it seems a good place so start. I checked my mLabs database and i don't see any user collection, i don't know if it's normal or not.
I have set my mLabs database as default and recreate an admin user maybe it will fix the issue.

**Comment by derrickmehaffy** [comment]
Generally yes this happens if you change the default connection name. For example in my project I have a split database just for user data (this is absolutely not the default and requires a lot of custom changes)

![image](https://user-images.githubusercontent.com/8593673/62936374-7d772500-bd7e-11e9-8db1-f22647e35592.png)

**Comment by matthieusibille** [comment]
@derrickmehaffy, i can confirm that was the issue here. I recreated a strapi project but without Quick start this time, i set my mLabs db as default and now my admin user is stored in my db on mLabs and everything still work after 24h.
Thank you for your help !

**Comment by derrickmehaffy** [comment]
no problem, marking as closed.

**Comment by bdradu** [comment]
@matthieusibille Heroku recreates the dynos every night so anything stored in the dyno that is not the result of the build process will be lost after 24h. If you had your db on the dyno it probably was deleted and created again like in the case of a fresh install.
