### ISSUE TITLE
Create model and link it

### ISSUE THREAD

**Issue by AakashPat** [strapi/strapi#3781]
**Describe the topic**
So I have two models in concern.
1. Address
2. User

A User account has 1(one) address linked as billing_address & many(multiple) addresses linked as shipping_addresses.
I want to be able to create a billing_address and link it to the User account.

**Screenshots**
![2019-08-14 03_14_59-Window](https://user-images.githubusercontent.com/10728448/62979553-c8a63c00-be41-11e9-9a8c-bebc871f2bac.png)
![2019-08-14 03_15_15-Window](https://user-images.githubusercontent.com/10728448/62979554-c93ed280-be41-11e9-8c95-d077955ad8df.png)

**Additional context**
I have tried passing in 'ref', 'refId', 'field' along with the POST request to the route /address, but it does not link the created address to the specified User model as expected.

**Comment by derrickmehaffy** [comment]
@AakashPat that ref, refId, and field is for file uploads so unless you are trying to upload a file to store on the model that won't be of much use to you.

Also we need more information:

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
