### ISSUE TITLE
Deleting Entry with Graphql returns null values

### ISSUE THREAD

**Issue by carolinmaisenbacher** [strapi/strapi#3784]
**Describe the bug**
Deleting an entry through Graphql endpoint returns an empty object with all fields set to null.

When running a deletePost mutation I get an error saying:
`"message": "Cannot return null for non-nullable field Post.id.",`

I have a content type post with two fields: 
* name (required)
* comments 

When executing the following mutation
```
mutation deletePost {
  deletePost(input: { where: { id: 1 } }) {
    post {
      id
    }
  }
}
```

The entry gets deleted from the database, but the following error occurs:
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Post.id.",
      "locations": [
        {
          "line": 12,
          "column": 7
        }
      ],
      "path": [
        "deletePost",
        "post",
        "id"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Post.id.",
            "    at completeValue (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:596:13)",
            "    at completeValueCatchingError (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:531:19)",
            "    at resolveField (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:471:10)",
            "    at executeFields (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:311:18)",
            "    at collectAndExecuteSubfields (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:747:10)",
            "    at completeObjectValue (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:737:10)",
            "    at completeValue (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:626:12)",
            "    at completeValueCatchingError (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:531:19)",
            "    at resolveField (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:471:10)",
            "    at executeFields (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:311:18)",
            "    at collectAndExecuteSubfields (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:747:10)",
            "    at completeObjectValue (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:737:10)",
            "    at completeValue (/Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:626:12)",
            "    at /Users/me/strapi/strapi-api/node_modules/graphql/execution/execute.js:528:16"
          ]
        }
      }
    }
  ],
  "data": {
    "deletePost": null
  }
}
```
The same error occurs when querying for the required `name` field.

When a not required field in the mutation, it throws no error, but returns null:
```
mutation deletePost {
  deletePost(input: { where: { id: 4 } }) {
    post {
      comments
    }
  }
}
```

Result:
```
{
  "data": {
    "deletePost": {
      "post": {
        "comments": null
      }
    }
  }
}
```

**Steps to reproduce the behavior**
0. Have the strapi graphql plugin installed
1. Create a new Content Type Post 
with 2 fields: `name` (required) and `comments` (not required)
3. Create a Post entry
2. Allow the Public User all Permissions for Post
3. Go to the Graphql Interface and test the deletion query:
```
mutation deletePost {
  deletePost(input: { where: { id: 1 } }) {
    post {
      id
    }
  }
}
```
4. See the error

**Expected behavior**
I expected Strapi to return the attributes of the entry that I just deleted, but instead it only returns `null` values.

**System**
- Node.js version: v12.8.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.14
- Database: PostgreSQL
- Operating system: macOS Mojave 10.14.5

**Comment by fadinasr** [comment]
I'm using Strapi with GraphQL plugin in production and the issue still exists. Any solution?

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
