### ISSUE TITLE
Production black page for admin panel

### ISSUE THREAD

**Issue by razvan-soare** [strapi/strapi#3786]
**Describe the bug**

I followed this guide: 
https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#digital-ocean
to deploy strapi on digital ocean server. I followed all the steps everything seem to be working just fine but when i cloned it to my server. I installed everything did NODE_ENV=production npm run build but when i try to access the admin page is black.

Im getting this errors in console. From what i can see is trying to access the files in /admin folder but i have no such thing there. When i did `npm run build` it generated all these files in /build folder

**Expected behavior**

Admin should build an run, and if needed docs should be updated if there is changes

**Screenshots**

<img width="349" alt="Screenshot 2019-08-14 at 09 42 06" src="https://user-images.githubusercontent.com/39434481/63034948-e962a600-bec2-11e9-877f-9dcf417d8c4e.png">

**Code snippets**
N/A

**System**
- Node.js version: v10.16.2
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: **User did not provide** -DM
- Operating system:**User did not provide** -DM

**Edit**: Edited by @derrickmehaffy to enforce template.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
@razvan-soare Please fillout the missing database and operating system.

Also if you have error logs from the server please provide as well.

**Comment by lauriejim** [comment]
I close this issue since we don't have news.
