### ISSUE TITLE
Relationships are empty in lifecycle callback

### ISSUE THREAD

**Issue by grantyi** [strapi/strapi#3788]
**Describe the bug**
In the lifecycle callback for models, the fields representing relationships are empty despite setting them when creating. I have tried `beforeCreate`, `afterCreate`, `beforeSave` and `afterSave`. The relationship is correct when viewing through Strapi Admin

**Steps to reproduce the behavior**
1. Create a Strapi project using MongoDB
2. Create a content type that has a many-to-many relationship to another content type
3. Create a new instance of the new content type and add a relationship to another content type
4. In lifecycle callback, observe that the model's array for the many-to-many relationship is empty.

**Expected behavior**
I would expect that the relationship be preserved in the lifecycle callback.

**System**
- Node.js version: 10.12.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.15
- Database: MongoDB
- Operating system: Ubuntu 18.04

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check #3329

> This is a templated message
