### ISSUE TITLE
Creating a MongoDb Model One-Way Type Relationship

### ISSUE THREAD

**Issue by ridvann** [strapi/strapi#379]
**Node.js version**:  8.7.0
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.7.1
**Operating system**: MacOsX High Sierra

Hi,

MongoDb Model I want to create one-way type relationship. But I did not see such an option in the Admin Panel.

I read your help files. I added it as described. 

```
"country": {
      "model":"country"
    }
```

But I am getting the following error.

```
ERROR (20696 on RCA-MacBook-Pro.local): Impossible to register the `bank` model.
ERROR (20696 on RCA-MacBook-Pro.local): Reference virtuals require `foreignField` option
Error: Reference virtuals require `foreignField` optionat Schema.virtual 
```
What would I do wrong?

Thanks

**Comment by Almusamim** [comment]
I'm getting same error.. are we doing something wrong here?

```
RROR (4760 on DESKTOP-C2OQDKG): Impossible to register the `car` model.
ERROR (4760 on DESKTOP-C2OQDKG): Reference virtuals require `foreignField` option
    Error: Reference virtuals require `foreignField` option
```

**Node.js version:** 8.1.3
**npm version:** 5.6.0
**Strapi version:** 3.0.0-alpha.7.2
**Operating system:** Win 10

**Comment by Aurelsicoko** [comment]
@Almusamim Thanks for reporting this issue. Can you try to make a `one-to-one` relationship following the [documentation](https://strapi.io/documentation/guides/models.html#one-to-one)?

Can you show me the structure of your models to reproduce the issue on my machine?

**Comment by ridvann** [comment]
Hello @Aurelsicoko ,

There is no problem with `One-to-one` method in my project.
But I want to use the `one-way` method. When I do this, the above problem is happening.
You can find my API files below.

Thanks

[api.zip](https://github.com/strapi/strapi/files/1569518/api.zip)

**Comment by Aurelsicoko** [comment]
I double-checked... and it's crazy! We didn't implement the `one-way` relationship in the connectors but documentation is already there.

**Comment by okaris** [comment]
Is this not implemented in the admin frontend?

**Comment by Aurelsicoko** [comment]
You're right, we didn't implement the one-way relationships in the UI. You can up-vote this message if you think this is really important for you. Otherwise, you can do it manually by following the documentation https://strapi.io/documentation/guides/models.html#one-way

**Comment by okaris** [comment]
@Aurelsicoko I will do it and submit a PR if thats allright. Thanks for the swift reply!
