### ISSUE TITLE
Creating new users with admin is unsuccessful

### ISSUE THREAD

**Issue by fxfeiyi** [strapi/strapi#3790]
Based on the code of the previous project, we developed a new model called Report locally, which has a relationship with User (User has many reports). I can see from User content type builder page, it has a relationship with Report (User belongs to many Blogs). 
Locally through the strapi admin page, users can be created locally and report can be created. 
But when we deploy the code to the server, we can create a report but not a user. There are the following error message in User create page.

s @ main.js:1
(anonymous) @ main.js:1
f @ main.js:11
ps @ main.js:11
./admin/src/i18n.js @ main.js:1
t @ main.js:1
./admin/src/intlPolyfill.js @ main.js:1
t @ main.js:1
(anonymous) @ main.js:1
./admin/src/app.js @ main.js:1
t @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:16 TypeError: Cannot read property 'type' of undefined
    at r.renderAttr (main.js:48)
    at Array.map (<anonymous>)
    at t.value (main.js:48)
    at Eo (main.js:16)
    at Oo (main.js:16)
    at zo (main.js:16)
    at hr (main.js:16)
    at fr (main.js:16)
    at zr (main.js:16)
    at Lr (main.js:16)
Xo @ main.js:16
o.callback @ main.js:16
$o @ main.js:16
Vo @ main.js:16
Ir @ main.js:16
zr @ main.js:16
Lr @ main.js:16
Dr @ main.js:16
Re @ main.js:16
main.js:16 Uncaught TypeError: Cannot read property 'type' of undefined
    at r.renderAttr (main.js:48)
    at Array.map (<anonymous>)
    at t.value (main.js:48)
    at Eo (main.js:16)
    at Oo (main.js:16)
    at zo (main.js:16)
    at hr (main.js:16)
    at fr (main.js:16)
    at zr (main.js:16)
    at Lr (main.js:16)
r.renderAttr @ main.js:48
value @ main.js:48
Eo @ main.js:16
Oo @ main.js:16
zo @ main.js:16
hr @ main.js:16
fr @ main.js:16
zr @ main.js:16
Lr @ main.js:16
Dr @ main.js:16
Re @ main.js:16

**I found the line number is 127, details is undefined.**
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/5952167/63155851-01aefe00-c046-11e9-88a1-0240fd774ca5.png">

When I tried to connect to the server directly with the local code, the report page could not be opened too. There was no error message, and the page kept showing a load icon.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
