### ISSUE TITLE
How to call stored procedure

### ISSUE THREAD

**Issue by nttg20** [strapi/strapi#3792]
My project is using framework, Because the filter can't support my request follow this SQL;
SELECT * FROM notification where
(apartment_id = 1 and floor_id = 1 and building_id = 1 and city_id = 1)
or (apartment_id is null and floor_id = 1 and building_id = 1 and city_id = 1)
or (apartment_id is null and floor_id is null and building_id = 1 and city_id = 1)
or (apartment_id is null and floor_id is null and building_id is null and city_id = 1);

I'm finding a solution to resole this issue, as building a custom service and create a store producer from my sql. But I not sure can call to store producer from that custom service.

This issue very important with my project, I look forward to receiving your help
Thank you so much!

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
