### ISSUE TITLE
An empty date is displayed incorrectly in the list of elements

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#3794]
**Describe the bug**  
When the date is displayed in the list of elements in the administrative interface, if the record has no date, the current date is displayed

**Steps to reproduce the behavior**  
1) create date type field  
2) display field in list
3) add an item without filling the date field
4) open item list  
  
![date](https://user-images.githubusercontent.com/16899697/63214408-45475c00-c15b-11e9-9ee4-9e7b8e1a4530.png)  

**Expected behavior**  
Display that there is no date
  
**System**
1) nodejs v10.16.0  
2) NPM v6.10.3  
3) Strapi version: 3.0.0-beta.15  
4) Database: mongodb  
5) Operating system: WSL Windows 10 - Ubuntu 18.04

**Comment by soupette** [comment]
I am closing this issue since it is related with #2811 and it is fixed in #3639
