### ISSUE TITLE
File name is not visible in the admin panel

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#3795]
Hey. I thought for a long time a bug or an idea, and yet they outweighed the bug.  
  
**Describe the bug**  
Attaching files we do not see their names and previews in the admin panel. If there are several files, you need to open them to see what's inside and delete  
  
**Steps to reproduce the behavior**  
1) create a file type field with a multiple mark  
2)  add multiple files to it  
3) save item  
  
![image](https://user-images.githubusercontent.com/16899697/63215604-6a909600-c16c-11e9-9877-168023bd99d4.png)  

If the content editor wants to delete the file 1 out of 10 he will have to look for it for a long time by touch.  You also have icons for certain types of files(pdf, zip, jpg), I think it’s worth adding a default icon to other files

**System**  
nodejs v10.16.0
NPM v6.10.3
Strapi version: 3.0.0-beta.15
Database: mongodb
Operating system: WSL Windows 10 - Ubuntu 18.04

**Comment by soupette** [comment]
@Aurelsicoko I strongly believe @vlad320 got a point here! We should update (just a little the file component) maybe by adding the name of the file somewhere...

**Comment by vlad320** [comment]
@soupette @Aurelsicoko Hello. 

If this does not interfere with the slider, you can write the name in it. Shortening long names.

![image](https://user-images.githubusercontent.com/16899697/63461518-24a13e00-c49c-11e9-9acf-6701ac16dc3b.png)
