### ISSUE TITLE
Language selection confusion

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#3796]
**Describe the bug**  
My language is Russian.  
When I changed the language to English to take a screenshot for the previous issue, I could not return the Russian back. He was not wearing a header.  

![image](https://user-images.githubusercontent.com/16899697/63215702-d1627f00-c16d-11e9-8477-953295532a14.png)  

Now I’ll go to edit the config :)   

**System**   
nodejs v10.16.0
NPM v6.10.3
Strapi version: 3.0.0-beta.15
Database: mongodb
Operating system: WSL Windows 10 - Ubuntu 18.04

**Comment by vlad320** [comment]
excuse me. But nothing hinted that the list could be scrolled with the mouse. Close.

**Comment by chiliec** [comment]
I agree with you, it's confusing. Reopen issue please, maybe we need to do something about it.

**Comment by vlad320** [comment]
I return issue. The client may not be so smart :)

**Comment by soupette** [comment]
Maybe we can add a scrollbar to the component...

**Comment by guidovizoso** [comment]
Hi! I can take the issue

**Comment by soupette** [comment]
This view will be removed when #4122 is merged.
