### ISSUE TITLE
New Strapi app with MongoDB Atlas DB error: "MongoWriteConcernError: No Write concern named 'majority' found in the replica set configuration."

### ISSUE THREAD

**Issue by sethpkendall** [strapi/strapi#3797]
**Describe the bug**
After a new Strapi application install with a correctly configured connection to a MongoDB Atlas connection  I am shown the message "The app has been connected to the database successfully!" When I proceed into the project directory and run "strapi start" for the first time I receive this error "MongoWriteConcernError: No Write concern named 'majority' found in the replica set configuration." I have configured my MongoDB Cluster according to the Strapi docs instructions. What is causing this error? Is it an issue with 

**Steps to reproduce the behavior**
1. Create a new Mongo Cluster
2. Install a new strapi application with a mongoDB database.
3. start Strapi for the first time. 

**Expected behavior**
Strapi starts and asks me to create a new admin user

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.16.0
- NPM version:6.9.0
- Strapi version: 3.0.0-beta.15
- Database: MongoDB Atlas Cluster
- Operating system: Windows 8

**Comment by sethpkendall** [comment]
update: my issue was due to setting up my MongoDB Atlas Cluster with Driver version 3.0 or later. The Strapi docs state: "You **must** use Version: 2.2.12 or later..."

The picker in Mongo Atlas defaults to 3.0 now days so you have to switch it back to 2.2.12 or later

**Comment by centogram** [comment]
If anyone else gets this error on an Atlas Cluster just remove the &w=majority connect option and all should work well even with a later DB driver.

**Comment by ctngln** [comment]
Many thanks, @centogram *dap*

**Comment by omsutar** [comment]
Thanks @centogram, it worked

**Comment by Kelvinblaze** [comment]
Wow, i have been everywhere searching for a fix. Thanks alot @centogram

**Comment by nemo369** [comment]
@centogram THNAK you so much

**Comment by czl032405** [comment]
@centogram  Thank You so much.

**Comment by erdenedavaa** [comment]
@centogram Thank you so much

**Comment by antonioduran** [comment]
Thank you @centogram . Greetings man..

**Comment by controlpee** [comment]
@centogram Thank you very much Sir.

**Comment by Abheetarora** [comment]
@centogram thanks alot

**Comment by Gonzalo-Bruna** [comment]
@centogram thanks it worked it was what I needed.

**Comment by PritamPrajarpathi** [comment]
> 
> 
> If anyone else gets this error on an Atlas Cluster just remove the &w=majority connect option and all should work well even with a later DB driver.

thank you so much

**Comment by ad3rinto** [comment]
I got the same error. Removed the "&w=majority " as recommended but still did not work.
Mine looked like this 
const mongoURL = "mongodb+srv://<username>:<password>@cluster0.vdlpgxh.mongodb.net/?retryWrites=true&w=majority/userDB";

I fixed this by removing "/userDB" . ( This was defined by me)

**Comment by shivdhb** [comment]
THU
