### ISSUE TITLE
error TypeError: entity.toLowerCase is not a function

### ISSUE THREAD

**Issue by htchia** [strapi/strapi#3799]
**Describe the bug**
In [Services Documentation](https://strapi.io/documentation/3.0.0-beta.x/guides/services.html#core-services) in the **find** function the strapi.query function was been used. When I copy-paste it to my Service file(*../beta-project/api/orderitemdemand/services/Orderitemdemand.js*) and try to use it in front-end website I get the error

> error TypeError: entity.toLowerCase is not a function
> at Strapi.query (/project/beta-project/node_modules/strapi/lib/Strapi.js:422:29)
> at Child.afterUpdate (/project/beta-project/api/orderitemdemand/models/Orderitemdemand.js:54:12)
> at Promise.mapSeries (/project/beta-project/node_modules/bookshelf/lib/base/events.js:101:64)
> at tryCatcher (/project/beta-project/node_modules/bluebird/js/release/util.js:16:23)
> at Object.gotValue (/project/beta-project/node_modules/bluebird/js/release/reduce.js:155:18)
> at Object.gotAccum (/project/beta-project/node_modules/bluebird/js/release/reduce.js:144:25)
> at Object.tryCatcher (/project/beta-project/node_modules/bluebird/js/release/util.js:16:23)
> at Promise._settlePromiseFromHandler (/project/beta-project/node_modules/bluebird/js/release/promise.js:517:31)
> at Promise._settlePromise (/project/beta-project/node_modules/bluebird/js/release/promise.js:574:18)
> at Promise._settlePromiseCtx (/project/beta-project/node_modules/bluebird/js/release/promise.js:611:10)
> at _drainQueueStep (/project/beta-project/node_modules/bluebird/js/release/async.js:142:12)
> at _drainQueue (/project/beta-project/node_modules/bluebird/js/release/async.js:131:9)
> at Async._drainQueues (/project/beta-project/node_modules/bluebird/js/release/async.js:147:5)
> at Immediate.Async.drainQueues (/project/beta-project/node_modules/bluebird/js/release/async.js:17:14)
> at runCallback (timers.js:705:18)
> at tryOnImmediate (timers.js:676:5)
> at processImmediate (timers.js:658:5)

**Expected behavior**
When I copy-paste the **find** function from [Services Documentation](https://strapi.io/documentation/3.0.0-beta.x/guides/services.html#core-services)  to my Service file it will work without errors.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15 (in the logs on restarting is 3.0.0-beta.14)
- Database: SQLite (I used quickstart)
- Operating system: Ubuntu 16

**Comment by nezzard** [comment]
Have the same error

**Comment by dannycoulombe** [comment]
Why did the author closed this thread? Did he succeeded resolving this issue? If so, how?

**Comment by dannycoulombe** [comment]
Oooh.. I see. The parameter passed to strapi.query(PARAMETER) is invalid. At least you may know now!

**Comment by htchia** [comment]
When I copy-paste this 
        return strapi.query(Product).find(params, populate);
  },
I replace *Product* with *Orderitemdemand* e.g.:
        return strapi.query(Orderitemdemand).find(params, populate);
  },
And got the error above. 
So I replace *Orderitemdemand* with *'Orderitemdemand'*, a string, e.g.:
        return strapi.query('Orderitemdemand').find(params, populate);
And it works! 
  },

**Comment by hack-and-backslash** [comment]
> 
> 
> When I copy-paste this
> 
> > return strapi.query(Product).find(params, populate);
> 
> I replace **Product** with **Orderitemdemand** e.g.:
> 
> > return strapi.query(Orderitemdemand).find(params, populate);
> 
> And got the error above.
> So I replace **Orderitemdemand** with **'Orderitemdemand'**, a string, e.g.:
> 
> > return strapi.query('Orderitemdemand').find(params, populate);
> 
> And it works!

I use something like `strapi.services.product.findOne(ctx.request.query)`

**Comment by nurikabe** [comment]
Is `strapi.services` the only way to query by related document?

**Comment by lauriejim** [comment]
I don't understand you question, be `strapi.services` give you access to you API services function.
And these services use the [Query system 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/queries.html#queries).
So in your code you can use the Query system to fetch your data.

**Comment by nurikabe** [comment]
Thanks, got it now. I was just getting confused when constructing my query.

That said, is there any advantage to using `strapi.services` versus directly accessing the query system? Query caching or any other magic?

**Comment by lauriejim** [comment]
Your API services use queries to fetch the data - [see here](https://strapi.io/documentation/3.0.0-beta.x/guides/services.html#services).
So there is no magic stuff or caching.
The only difference will be for your use case.

If you want to create a custom logic that - fetch some data and manage it - and this custom logic have to be reusable in your application, in this case, you will have to create a service.

If you just want to fetch some data in a controller, for example, you can use queries directly.
