### ISSUE TITLE
Is there $and operator in api?

### ISSUE THREAD

**Issue by nezzard** [strapi/strapi#3800]
I need to get movies, that includes all of ids for example 24 and 25
this request /movies?genres.seq=24&genres.seq=25 returns me movies, that includes this ids but it can be movie onlye with one of this ids. 
Can I somehow filter so that the movie necessarily contains all the IDs in the list?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
@nezzard the github issues is only for Bug reports and feature requests, as to your question: https://strapi.io/documentation/3.0.0-beta.x/guides/filters.html#filters-2

`_in` and `_nin` is what you would use with the rest routes
