### ISSUE TITLE
Emails marked as Spam

### ISSUE THREAD

**Issue by cfontana0** [strapi/strapi#3804]
**Describe the topic**
I have some issues sending emails using the strapi's service and gmail. Basically, I configured Google Suite for my company and tried to send emails using the `strapi.plugins.email` plugin, however, they are received as Spam all the time.

I talked with the Google Suite's support team, and they indicated me that I have to configure DKIM and SPF for my email, and I did that following these tutorial:
https://support.google.com/a/answer/174124
https://support.google.com/a/answer/33786

However, I still receiving the mails as Spam.

I talked with them again, they indicated me that I have to add a custom SPF record on my hosting service for Strapi / my domain. For instance, if I use the gmail service, I have to include `v=spf1 include:serverdomain.com include:_spf.google.com ~all`

Any idea?

**Your suggestions for this topic**
NA

**Screenshots**
NA

**Code snippets**
NA

**Additional context**
NA

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
As a side note I don't believe this is directly an issue with Strapi unless some specific header needs to be passed?

**Comment by tiberiumihai** [comment]
I know this is closed but I think the strapi-provider-email-sendmail needs to have a configuration like in the example from node-sendmail:

```
const sendmail = require('sendmail')({
  logger: {
    debug: console.log,
    info: console.info,
    warn: console.warn,
    error: console.error
  },
  silent: false,
  dkim: { // Default: False                   <---------------- THIS SHOULD BE ADDED
    privateKey: fs.readFileSync('./dkim-private.pem', 'utf8'),
    keySelector: 'mydomainkey'
  },
  devPort: 1025, // Default: False
  devHost: 'localhost', // Default: localhost
  smtpPort: 2525, // Default: 25
  smtpHost: 'localhost' // Default: -1 - extra smtp host after resolveMX
})
```

[Source: node-sendmail git repo](https://github.com/guileen/node-sendmail)

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/unsolved-problem-emails-goes-to-spam/512/1
