### ISSUE TITLE
Restrict authenticated users to see only their  related profile

### ISSUE THREAD

**Issue by emrahc** [strapi/strapi#3805]
I have profile content model. Related to user model.Each user has spesific profile relation Only authenticated users see profile. Kinda social media user/profile. But any authenticated user could see other profiles too. How can i restrict this? I already tried  this solution from a https://github.com/strapi/strapi/issues/2799 but not working. Still any authenticated user could see other profiles as well. I assume there is no builtin solution in Strapi. What should i do?

```
find: async (ctx) => {
    const user = ctx.state.user;
    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'User is not authenticated' }] }]);
    }
      var data;
      if (ctx.query._q) {
            data = await strapi.services.institution.search({user:user.id});
          } else {
            data = await strapi.services.institution.fetchAll({user:user.id});
          }

    if(!data){
      return ctx.notFound();
    }
    ctx.send(data);
  },
```

**Comment by derrickmehaffy** [comment]
@emrahc only issues and feature requests with core code are allowed here on github:

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
As a suggestion though you can use a policy and assign it to the route instead checking the incoming `ctx.state.user.role` or any part of the `ctx.state.user` 

You could lock down routes based on the users ID, role's id/type/name, ect. I would recommend you take a look at the documentation around policies: https://strapi.io/documentation/3.0.0-beta.x/guides/policies.html#policies
