### ISSUE TITLE
The "Populate more user informations on POST /auth/login" commit causes localStorage problems

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3807]
I have a relation between an user and its blog posts. Updating from beta.14 to beta.15 which contains this "fix" about "Populate more user informations on POST /auth/login" causes the following problem: when i log in with my user , i'm now getting a very BIG post result on auth, containing ALL blog posts from ALL history (which is  A LOT) giving me avatars, etc which is a LOT of data; i' storing on browser that result in `localStorage` which is now exhausting the available space, and getting this error i'm attaching.

![error](https://user-images.githubusercontent.com/517228/63350036-08ce5880-c333-11e9-945e-54f386d0be38.png)

Getting ALL info about an user on doing auth is not very clever i think.... going back to beta.14 and hoping for a fix on this.

**Comment by alexandrebodin** [comment]
Have you tried defining your user model with the option autoPopulate: false ?

```json
{
  "attributes": {
    "yourRel": {
       "autoPopulate": false
    }
  }
}
```

**Comment by jacargentina** [comment]
Just tried, like this:

![strapi](https://user-images.githubusercontent.com/517228/63355331-59967f00-c33c-11e9-860c-0a532747487a.png)

Not working. Same problem.

**Comment by alexandrebodin** [comment]
Ok so right now your best course of action is to overwrite the Auth.js controller of the users-permissions plugin and change the query to only populate the fields you want.

**Comment by jacargentina** [comment]
So you say i must copy/paste auth.js controller, and leave the returned object as it was before that commit?

**Comment by alexandrebodin** [comment]
Yes this is the best course of action for now.

**Comment by alexandrebodin** [comment]
@jacargentina what DB are you on ?

**Comment by jacargentina** [comment]
mongodb

**Comment by alexandrebodin** [comment]
@jacargentina Where are you modifying you User.settings.json file ?

**Comment by jacargentina** [comment]
![strapi](https://user-images.githubusercontent.com/517228/63524340-3ac9f100-c4d2-11e9-970e-c67e52fa1849.png)

**Comment by alexandrebodin** [comment]
Ok I just tested to use the autoPopulate on the upcoming release and this will work. I'll keep you updated ;). 
btw: If you have no real use for the blogs field in the user you can use a oneWay relation instead.

**Comment by lauriejim** [comment]
Beta.16 is released - should be ok now.
