### ISSUE TITLE
Using Common Attributes in multiple models

### ISSUE THREAD

**Issue by baldeepsinghkwatra** [strapi/strapi#3809]
**Describe the topic**
I have multiple API's which need certain common fields for eg. status, author, updatedBy, createdBy, assignedTo, assignedOn etc.

**Your suggestions for this topic**
In the api/*/models/*.settings.json file it will be great if we can import certain common attributes from another json file defined in util directory of the project.

**Additional context**
If anyone has done that or if there is some way to handle this use case please share. 
If not can we add into the feature request?

**Comment by lauriejim** [comment]
Hello and thank you for this message.
We do not plan to offer this feature now.
Can you please send this insight (copy and paste) in the [Product Roadmap](https://portal.productboard.com/strapi)
I have no workaround for you.
You have to repeat the operation for all you content types.
