### ISSUE TITLE
[bug] setup error

### ISSUE THREAD

**Issue by pouyamiralayi** [strapi/strapi#3810]
windows 10 x64
node: 10.16.3
npm: 6.9.0
strapi 3.0.0@beta-15

1) cloned the repo
2) issued yarn setup
3) yarn setup resulted below error:
`
error C:\Users\Admin\Documents\strapi\node_modules\metrohash: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\Admin\Documents\strapi\node_modules\metrohash
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.3 | win32 | x64
gyp info spawn C:\Users\Admin\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'C:\\Users\\Admin\\Documents\\strapi\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\Documents\\strapi\\node_modules\\metrohash\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\Documents\\strapi\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Admin\\.node-gyp\\10.16.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Admin\\.node-gyp\\10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Admin\\Documents\\strapi\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Admin\\.node-gyp\\10.16.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Admin\\Documents\\strapi\\node_modules\\metrohash',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Admin\\Documents\\strapi\\node_modules\\metrohash\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  metrohash_wrapper.cpp
  metrohash128.cpp
  metrohash128crc.cpp
  metrohash64.cpp
  win_delay_load_hook.cc
C:\Users\Admin\.node-gyp\10.16.3\x64\node.lib : fatal error LNK1127: library is corrupt [C:\Users\Admin\Documents\strapi\node_modules\metrohash\build\metrohash.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Admin\Documents\strapi\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\Documents\\strapi\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Admin\Documents\strapi\node_modules\metrohash
`
4) beside this, i had another error for optional xxhash which states that library is corrupt.

note: i am using a fresh node environment with no strapi cli installed at all. and i have just installed windows-build-tools successfully.

i searched a lot about this but all the answers are referring to the alpha version.
in slack guys gave me exact steps on how to setup development env, but i am stuck at the first step: yarn setup :) . any opinion on this would be appreciated.
thanks in advance.

**Comment by vlad320** [comment]
@pouyamiralayi Hello. Install WSl and and have no problems :)
https://linuxhint.com/install_ubuntu_windows_10_wsl/

**Comment by vlad320** [comment]
https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies  
maybe the second answer will help you with 411 votes

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by pouyamiralayi** [comment]
Hello again! thanks for your response and apologize for not following the issue template.
you were right because of this issue relating to my environment and i do not blame strapi for that.
for those who ran into similar issue, these steps helped me:
`npm install --global --production windows-build-tools@4.0.0
`
this will solve the python problem. but after that you must do something like this:
remove the  `~/.node-gyp` directory
and do: `npm i -g node-gyp` again.
thanks in advance.

**Comment by Sletheren** [comment]
For me it was because of XCode
This one solved it: `sudo xcode-select --reset`
