### ISSUE TITLE
GraphQL where filter using variables return all data

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#3815]
Related to [#3537 ](https://github.com/strapi/strapi/issues/3537#issuecomment-507170401)

**Describe the bug**
Trying to filter a query with where, and _contains based on a variable doesn't filter anything, and outputs all the data

1.- Make this query:

```
query($where:JSON) {
        magazines( where: { url_contains:$where }){
          number
          url
          title
        }
      }
```
and variables: 

```
{
  "where": {
  	"url": "my-page-slug"
  }
}
```

**Expected behavior**
It should output an array with just the item which url contains `my-page-slug`

**System**
- Node.js version: v10.15.2
- NPM version: npm -v
- Strapi version: Strapi v3.0.0-beta.15
- Database: SQLite
- Operating system: Ubuntu 19.04

**Comment by derrickmehaffy** [comment]
Duplicate, also please see this comment: https://github.com/strapi/strapi/issues/3537#issuecomment-507170401

You need to pass the entire where: {} json structure in the variable

**Comment by derrickmehaffy** [comment]
example: 
![image](https://user-images.githubusercontent.com/8593673/63457200-603cf900-c405-11e9-8417-953c50aba2f2.png)

**Comment by Jesus82** [comment]
Hi, thankd for your coment. I'm aware of issue #3537 and I tried to follow it. I did transcribe wrong the variables (I've just edited them). The variable part I have it as follow:

```
{
  "where": {
  	"url": "my-page-slug"
  }
}
```

And the result is the same (I get all data instead of just the data I request.

Cheers.

**Comment by derrickmehaffy** [comment]
The image you linked is showing the wrong format also. Can you confirm using the way I described iny example fixes the issue

**Comment by Jesus82** [comment]
I tried this way, same result 
[https://i.ibb.co/6yPYt4N/Sen-titulo.png](url)

And same result if I change `url_contains` for `url`

**Comment by Jesus82** [comment]
@derrickmehaffy Could you confirm if there's a bug or if it is something still wrong with my syntax?

**Comment by derrickmehaffy** [comment]
@Jesus82 in your most recent image link: https://github.com/strapi/strapi/issues/3815#issuecomment-523937818 that is the correct syntax and it appears to return the correct data.

**Comment by Jesus82** [comment]
I'm trying to return just item number 11, querying by url.

Isn't the query correct? (it should output just number 11 as I see it)

**Comment by derrickmehaffy** [comment]
@Jesus82 I think I see the problem here, you are using SQLite which doesn't have as much support of indexes so some of the filtering options may not work. Can you please try and swap over to MySQL/Postgres and see if your project works there?

**Comment by Jesus82** [comment]
Ok, I will try so. Any tips on how to create an MySQL/Postgres DB and make it work with Strapi? In the guides it just covers SQLite and Mongo

**Comment by derrickmehaffy** [comment]
Install either MySQL or MariaDB server the connect to the server using the cli tool 
(depending on if you are using MySQL or MariaDB, I recommend MariaDB)
`sudo mysql -u root`

Then do the following to create a database, user, and grant permissions:
```
create database strapi;
create user strapi@localhost identified by 'strapi';
grant all privileges on strapi.* to strapi@localhost;
```

Once you have the database setup you can modify your `config/environments/development/database.json` like so:

```

{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "127.0.0.1",
        "port": 3306,
        "database": "strapi",
        "username": "strapi",
        "password": "strapi"
      },
      "options": {}
    }
  }
}
```

You may also need to install the `mysql` and `knex` npm package if they aren't set in your package.json file (example is here in my own project: https://github.com/canonn-science/CAPIv2-Strapi/blob/67027c8e387c63244fb3b4c2c67d29c0b05919c6/package.json#L28-L30 )

**Comment by Jesus82** [comment]
Changed to MySQL (same version as in your package.json), rewrote a mockup db with 2 entrances, and same result.

![image](https://i.ibb.co/KXLYYNF/Captura-de-pantalla-de-2019-08-26-21-08-05.png)

**Comment by itsmepetrov** [comment]
I faced with the same issue, I'm using lates beta with sqlite

**Comment by derrickmehaffy** [comment]
@itsmepetrov Most likely that is a problem with SQLite as it doesn't support proper indexes like the other databases, I would suggest you test it with a proper database. I'm not entirely sure if this is something Strapi can even fix as it's more a platform issue than Strapi.

**Comment by Jesus82** [comment]
Hi @derrickmehaffy, I checked with MySQL as per your instructions, and the bug was still there (see [](https://github.com/strapi/strapi/issues/3815#issuecomment-524990739))

**Comment by itsmepetrov** [comment]
@derrickmehaffy I've tried to change my query from:

```gql
query pages($slug: String!) {
  pages(where: { slug: $slug }) {
    id
    title
    slug
    content
  }
}
```

to:

```gql
query pages($where: JSON!) {
  pages(where: $where) {
    id
    title
    slug
    content
  }
}
```

And it started working!

It looks like parsing query parameters like `where` in new Strapi versions was changed and now we should pass it as complete json variable.

**Comment by itsmepetrov** [comment]
And what plan for sqlite, are you going to completely remove support for it?

**Comment by derrickmehaffy** [comment]
@itsmepetrov there is no plans to remove SQLite that I'm aware of, it will just have a limited feature set and it's not recommended for any sort of production usage anyway just simple testing locally.

Personally I don't even use it for testing locally on my own project and I always recommend setting up a local copy of your database.
 
---

As multiple people have stated the change to passing the entire where json structure seems to work I am going to mark this issue as closed for now.

**Comment by Jesus82** [comment]
Finally found out where the issue is. The queries are working OK with MySQL, but the [graphql playground](http://localhost:1337:graphql) doesn't.
