### ISSUE TITLE
MongoError: E11000 duplicate key error collection

### ISSUE THREAD

**Issue by AminZibayi** [strapi/strapi#3817]
**Describe the bug**

**Steps to reproduce the behavior**
1. Create a new Content-Type
2. Add a unique field
3. Add some content to the created Content-Type
4. Delete the unique field
5. Try to create at least two new records.
6. Encounter a 500 internal server error

**Expected behavior**

There should not be any errors.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.9
- Database: MongoDB
- Operating system: Ubuntu

**Suggested solution**

Removing a field from a Mongoose model doesn't affect the database so Strapi should also remove the unneeded indexes from DB.
By the way, as a quick fix, after removing a unique field the developer can manually remove the related index.

**Comment by lauriejim** [comment]
Hello and thank you for this issue.
You can find here the same issue https://github.com/strapi/strapi/issues/1692
The topic is to unset a Unique constrains.
I close this one.

**Comment by dafabulousteach** [comment]
For those finding this question, I was able to fix the duplicate key error by 

1. Removing the unique constraint in the Strapi admin UI
2. Logging into the Mongo shell and dropping the collection
