### ISSUE TITLE
Feature request: Add parameter to choose the sorting order

### ISSUE THREAD

**Issue by rojasmi1** [strapi/strapi#382]
**Strapi version**: 3.0.0-alpha

Hi. I was taking a look at the documentation and saw there is an option for [sorting results](https://strapi.io/documentation/guides/filters.html#sort) from the API, but there is no way on choosing the order (ascendant/descendant).

Is something missing in the documentation or the option is just not available at all? If so, it'd be nice to have that option.

BTW, I really like what you've done so far... giving it a try to see how it works for a personal project.

**Comment by Aurelsicoko** [comment]
@rojasmi1 You can define the order with the `-` character. `GET /user?_sort=email` or `GET /user?_sort=-email`. 

You're right, this information is missing from the documentation.

**Comment by rojasmi1** [comment]
Cool! Thanks for the quick reply @Aurelsicoko!

**Comment by Aurelsicoko** [comment]
The documentation has been updated https://github.com/strapi/strapi/pull/400!
