### ISSUE TITLE
Cant start strapi with mongodb on local

### ISSUE THREAD

**Issue by webface** [strapi/strapi#3821]
**Describe the bug**
Cannot start strapi with mongo connection

**Steps to reproduce the behavior**
1. strapi new heroku-dashboard
```
? Choose your installation type Custom (manual settings)
? Choose your default database client mongo
? Database name: heroku-dashboard
? Host: 127.0.0.1
? +srv connection: true
? Port (It will be ignored if you enable +srv): 27017
? Username: 
? Password: 
? Authentication database (Maybe "admin" or blank): 
? Enable SSL connection: No
```

**Expected behavior**
yarn develop ...launch admin interface

**Screenshots**

**Code snippets**
`{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
		"client":"mongo",
        "database": "heroku-app",
        "host": "127.0.0.1",
        "srv": "true",
        "port": 27017,
        "username": "",
        "password": ""
      },
      "options": {
		"authenticationDatabase": "",
		"ssl": true,
        "minimize": true
      }
    }
  }
}`

**System**
- Node.js version: 10.15.3
- NPM version: 6.4.1
- Strapi version: 3.beta
- Database: Mongo Shell version v4.0.3
- Operating system:Mac

**Additional context**
I get the following error:
`$ strapi develop
querySrv ENOTFOUND _mongodb._tcp.127.0.0.1
[2019-08-22T13:40:12.533Z] debug ⛔️ Server wasn't able to start properly.
[2019-08-22T13:40:12.533Z] error querySrv ENOTFOUND _mongodb._tcp.127.0.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by derrickmehaffy** [comment]
Disable srv

**Comment by Nauman440** [comment]
Connecting strapi with MongoDB is very easy. I followed this article which helped me to connect both MongoDB and MongoDB Atlas with my strapi project.

https://www.mstweaks.com/strapi-with-mongodb-and-mongodb-atlas/

**Comment by AntonioChagoya** [comment]
> Connecting strapi with MongoDB is very easy. I followed this article which helped me to connect both MongoDB and MongoDB Atlas with my strapi project.
> 
> https://www.mstweaks.com/strapi-with-mongodb-and-mongodb-atlas/

What if you are not doing it for the first time?

Seems like it is hard to get the DATABASE_URI, necessary for the connection, how can you change between prod and local enviroments?
