### ISSUE TITLE
Strapi -v showing 3.0.0-next.19

### ISSUE THREAD

**Issue by crushy26** [strapi/strapi#3828]
**Describe the bug**
On macOS Mojave, I tried to install strapi globally and on strapi -v it's showing 3.0.0-next.19, but on ubuntu system it's showing 3.0.0-beta.15

**Expected behavior**
Should show the latest version of beta 3.0.0-beta.15

**Screenshots**
![Screenshot 2019-08-23 at 2 37 58 PM](https://user-images.githubusercontent.com/37217713/63581065-c798ab80-c5b3-11e9-95d8-fdb1677ddb66.png)
![Screenshot 2019-08-23 at 2 38 52 PM](https://user-images.githubusercontent.com/37217713/63581067-c8314200-c5b3-11e9-8a8f-55c16b24ce27.png)

**System**
- Node.js version: v10.16.2
- NPM version: 6.9.0
- Strapi version: 
- Database: 
- Operating system: macOS Mojave

**Comment by derrickmehaffy** [comment]
you should wipe and reinstall the strapi global package: `npm i -g strapi@beta`

Also you can modify all the package versions in your package.json and delete the `build`, `.cache`, `node_modules`, `package-lock.json`, and `yarn.lock` and rerun either `npm i` or ` yarn install`

**Comment by crushy26** [comment]
Hey, @derrickmehaffy

As you can see I tried to reinstall over existing package, here is the case:

![before](https://user-images.githubusercontent.com/37217713/63612235-68f72000-c5fb-11e9-8681-95ebd138c1fe.png)

To make sure, I uninstalled the whole package globally and reinstalled again, still I get to see the same:

![Screenshot 2019-08-23 at 11 10 45 PM](https://user-images.githubusercontent.com/37217713/63612299-90e68380-c5fb-11e9-9419-2bd7dd048988.png)

I can surely manually change the local package.json to the desired version but removes the purpose of global strapi while creating new project. It would be great if you can take a look at this issue.
