### ISSUE TITLE
Build fails: "error (hook:bookshelf) takes too long to load" and cannot connect to PostgreSQL

### ISSUE THREAD

**Issue by websocket98765** [strapi/strapi#3838]
**Describe the bug**

During build, I get these two error below: 

The end result is build fails (error code > 0) and Strapi continues and starts itself acting like it was successful (but sqlite is used and Postgres isn't altered by Strapi in any way). 

I believe Sqlite is used because redeploying wipes out any data, such as new users, entered in the admin and then the Start New screen is shown after every deploy.

### Errors 

```
### Error 1: "(hook:bookshelf) takes too long to load"

Aug 24 06:56:22 PM  > strapi start
Aug 24 06:56:22 PM  
Aug 24 06:56:26 PM  [2019-08-24T18:56:26.359Z] error (hook:bookshelf) takes too long to load
Aug 24 06:56:26 PM  (hook:bookshelf) takes too long to load
Aug 24 06:56:26 PM  npm ERR! code ELIFECYCLE
Aug 24 06:56:26 PM  npm ERR! errno 1
Aug 24 06:56:26 PM  npm ERR! my-admin2@0.1.0 start: `strapi start`
Aug 24 06:56:26 PM  npm ERR! Exit status 1
Aug 24 06:56:26 PM  npm ERR!
Aug 24 06:56:26 PM  npm ERR! Failed at the my-admin2@0.1.0 start script.
Aug 24 06:56:26 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Aug 24 06:56:26 PM  

### Error 2: "no such file or directory, open '/opt/render/project/src/package.json'"

Aug 24 06:56:26 PM  npm ERR! A complete log of this run can be found in:
Aug 24 06:56:26 PM  npm ERR!     /opt/render/.cache/_logs/2019-08-24T18_56_26_373Z-debug.log
Aug 24 06:56:28 PM  ==> Starting service with 'npm run start'
Aug 24 06:56:28 PM  npm ERR! path /opt/render/project/src/package.json
Aug 24 06:56:28 PM  npm ERR! code ENOENT
Aug 24 06:56:28 PM  npm ERR! errno -2
Aug 24 06:56:28 PM  npm ERR! syscall open
Aug 24 06:56:28 PM  npm ERR! enoent ENOENT: no such file or directory, open '/opt/render/project/src/package.json'
Aug 24 06:56:28 PM  npm ERR! enoent This is related to npm not being able to find a file.
Aug 24 06:56:28 PM  npm ERR! enoent
Aug 24 06:56:28 PM  
Aug 24 06:56:28 PM  npm ERR! A complete log of this run can be found in:
Aug 24 06:56:28 PM  npm ERR!     /opt/render/.cache/_logs/2019-08-24T18_56_28_672Z-debug.log
Aug 24 06:56:45 PM  

## Then Strapi continues to start itself and acts like it was successful:

Aug 24 06:56:48 PM  [2019-08-24T18:56:48.180Z] info Time: Sat Aug 24 2019 18:56:48 GMT+0000 (Coordinated Universal Time)
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.182Z] info Launched in: 2385 ms
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.182Z] info Environment: production
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.182Z] info Process PID: 81
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.182Z] info Version: 3.0.0-beta.15 (node v12.9.0)
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.182Z] info To shut down your server, press <CTRL> + C at any time
Aug 24 06:56:48 PM  
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.183Z] info ☄️  Admin panel: http://localhost:10000/admin
Aug 24 06:56:48 PM  [2019-08-24T18:56:48.184Z] info ⚡️ Server: http://localhost:10000
```

**Steps to reproduce the behavior**
1. Created new project using:
npx create-strapi-app <name-your-project>

2. I updated `config/environments/production/database.json` to use `postgres` and ran `npm install --save pg`
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "srv": "${process.env.DATABASE_SRV || false}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "ssl": "${process.env.DATABASE_SSL || false}"
      },
      "options": {
        "ssl": "${process.env.DATABASE_SSL || false}",
        "authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE || ''}"
      }
    }
  }
}
```

and specified these production env vars in my web host (render.com, like Heroku; values ommitted):
```
DATABASE_HOST
DATABASE_NAME
DATABASE_PASSWORD
DATABASE_PORT
DATABASE_SSL   true
DATABASE_USERNAME
NODE_ENV       production
```

3. I set Render.com to use these commands, which seem to work as expected:

Build command:
`npm install && npm run build`

Run command:
`npm run start` 

4. During build, I get the two errors described earlier.

The end result is build fails (error code > 0) and Strapi starts itself (but sqlite is used and Postgres isn't altered by Strapi in any way).

I say Sqlite is used b/c redeploying wiped out any data, such as new users, entered in the admin and then the Start New screen is shown after every deploy.

**Expected behavior**

Strapi connects to PostgreSQL. If I create the Super Admin user on Strapi and then build/redeploy again, I should be able to login with this user (b/c Strapi should have used PostgresQL). 

**System**

- Node.js version: v10.16.3 (Another oddity, Strapi says the node version is `12.9.0` but if I run `node --version` I get `v10.16.3`, so Strapi's indication of node version is incorrect.) 
- NPM version: 6.9.0
- Strapi version: Strapi v3.0.0-beta.15
- Database: Postgres
- Operating system: Linux (render.com)

**Additional**

- Is it possible Strapi's start script specifies the package.json file name in uppercase? Because casing matters on Linux. This could cause one of the errors. 
- My database details are correct b/c I use them in the Postico Postgres client to connect I could connect to the DB, and that's how I saw Strapi never created any tables in the DB.
- I've tried for hours on this, and tried creating fresh Strapi installations and asking in strapi.slack.com, but on luck yet. I'd like to avoid switching to MongoDB if I can solve these errors, which I assume are Postgres related since Sqlite works as expected in the development env.

**Comment by websocket98765** [comment]
_Related feature request from this_: Don't fallback to Sqlite in production. It makes it extremely difficult to troubleshoot  database setup issues and creates opportunity for developers to start using the Strapi admin without realizing that it is using Sqlite instead of their specified Postgres/etc database credentials.

**Comment by websocket98765** [comment]
Further info: I get the exact same error (`(hook:bookshelf) takes too long to load`) when using `NODE_ENV=production npm run start` locally. The full error log (below) says it `Failed to exec start script`. Keep in mind I can start Strapi successfully with sqlite (both locally and on Render.com) indicating that the issue is related to the start script when using postgres:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.3
3 info using node@v12.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle myproject@0.1.0~prestart: myproject@0.1.0
6 info lifecycle myproject@0.1.0~start: myproject@0.1.0
7 verbose lifecycle myproject@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle myproject@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/path/to/myproject/node_modules/.bin:/usr/local/Cellar:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar
9 verbose lifecycle myproject@0.1.0~start: CWD: /path/to/myproject
10 silly lifecycle myproject@0.1.0~start: Args: [ '-c', 'strapi start' ]
11 silly lifecycle myproject@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle myproject@0.1.0~start: Failed to exec start script
13 verbose stack Error: myproject@0.1.0 start: `strapi start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid myproject@0.1.0
15 verbose cwd /path/to/myproject
16 verbose Darwin 18.6.0
17 verbose argv "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.4.0
19 verbose npm  v6.10.3
20 error code ELIFECYCLE
21 error errno 1
22 error myproject@0.1.0 start: `strapi start`
22 error Exit status 1
23 error Failed at the myproject@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by izzuddinnatsir** [comment]
This also happened to me. Running Strapi in development mode using `yarn develop` with PostgresQL as the database.

- Node version: 10.16.2
- Strapi version: 3.0.0-beta.15
- OS: Ubuntu 18.04 LTS

**Comment by websocket98765** [comment]
Also tried creating a new project (`npx create-strapi-app myproj`) without using `--quickstart`, in case that was the issue, and specifying all postgres details. But I still encounter the same error when Strapi attempts to start itself in production: 

```
Sep 4 06:57:55 PM  > strapi start
Sep 4 06:57:55 PM  
Sep 4 06:58:27 PM  (hook:bookshelf) takes too long to load
Sep 4 06:58:27 PM  [2019-09-04T18:58:27.044Z] error (hook:bookshelf) takes too long to load
Sep 4 06:58:27 PM  npm ERR! code ELIFECYCLE
Sep 4 06:58:27 PM  npm ERR! errno 1
Sep 4 06:58:27 PM  npm ERR! myproj@0.1.0 start: `strapi start`
Sep 4 06:58:27 PM  npm ERR! Exit status 1
```

**Comment by websocket98765** [comment]
Closing. I managed to get Strapi + Postgres working on Heroku, and could connect to Heroku Postgres but not Render's Postgres. My latest theory is some kind of issue with Render's DB even though creds were correct. I've notified Render about the issue.

**Comment by websocket98765** [comment]
Solved with the help of Render's super helpful support: 1.) When connecting to their Postgres from a service/node, the internal connection string should be used and SSL needs to be disabled, 2.) I also typo'd the port # as 5342 instead of 5432.

To avoid this for others in the future, the already-open, Strapi issue to use a DB URL will be very helpful: https://github.com/strapi/strapi/issues/3094

**Comment by websocket98765** [comment]
Sorry, last update. I also had to increase `hook.json`'s timeout to `10000` (which I didn't see mentioned in the docs) and exclude `package-lock.json` (which was mentioned in docs) to get the build to work. It may be helpful to change to change Strapi's defaults to reflect these so others don't encounter similar issues.

**Comment by romanmandryk** [comment]
@websocket98765 - thanks for pointing to hook.json - timeout.
Default timeout is 3000ms which is too low for remote connections. Local postgres database is always fine, but connecting to a remote db (AWS RDS) sometimes worked but sometimes threw the error. Raising timeout to 30000 solved the issue.

**Comment by ChristopherLMiller** [comment]
where is the hook.json located?  I'm experiencing this issue with mysql even.

**Comment by maliksajid** [comment]
I was experciencing the same issue ith all databases. I solved it by changing by project directory permissions.

`sudo chmod -R 777 strapi_cms`

strapi_cms is my project directory. Thank You

**Comment by websocket98765** [comment]
@ChristopherLMiller `./config/hook.json`

**Comment by Igor2122** [comment]
am having the same issue, but do not see a clear solution to the problem,
the weir thing is that everything was working fine, my client added all the data to db and i just needed to add cell to my Product model after what it all crashed and the app is down 
i have changed the time out in the hook to 30000
what else i can do to fix this issue ?
