### ISSUE TITLE
Unable to filter via createdAt field

### ISSUE THREAD

**Issue by crushy26** [strapi/strapi#3841]
**Describe the bug**
Getting error 'Your filters contain a field 'createdAt' that doesn't appear on your model definition nor it's relations'

**Expected behavior**
Previously in Alpha i was able to filter

**Screenshots**
![Screenshot 2019-08-25 at 12 25 30 PM](https://user-images.githubusercontent.com/37217713/63646857-df4c6d00-c736-11e9-989a-4162e3cf914d.png)

createdAt field exists as shown,
![Screenshot 2019-08-25 at 12 25 15 PM](https://user-images.githubusercontent.com/37217713/63646860-ea9f9880-c736-11e9-9f7f-d9b73770d772.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: MongoDB
- Operating system: MacOS Mojave / ubuntu 18.04 LTS

**Comment by derrickmehaffy** [comment]
fix was already created and merged into this PR, will be released when beta.16 is released

**Comment by derrickmehaffy** [comment]
https://github.com/strapi/strapi/pull/3664

**Comment by farzer** [comment]
hope beta.16 come soon 🙏

**Comment by lauriejim** [comment]
Hello @farzer - it's released.
