### ISSUE TITLE
Respect unique constraint for relations field

### ISSUE THREAD

**Issue by raza2022** [strapi/strapi#3854]
**Document Created with Wrong Relation Field ID and Duplicate ID**

Let's Say You have a relational field named `categoryID` in `users` collection to link with `Categories` collection, and also this field has a check as `unique` fields option in advanced settings. So when new user created it should have a valid `categoryID` which already exists, 

Now There are three cases and please make sure my case is 2nd and 3rd  as first one already asked in previous issues.

1. `categoryID` not supplied then user created successfully (not my issue as I know there is notrequired fields feature currently in strapi and it's already asked)

2. wrong `categoryID` supplied and user still created (that's my case), means you can pass any valid 24 digit mongodb ID from any collection (not from `categories`) and it will be accepted without any error ?

3. use the same ID again and again it will created new user despite `unique` fields is checked in advanced settings in relational field??
 
**Steps to reproduce the behavior**
1. Go to 'Admin Panel Content Builder'
2. Add new Content Type `Categories`
3. Go to `user` collections and add relational field name `categoryID` to Categories
4. Go in advanced settings tab and check the `unique field`
5. Create New User from Front End using Strapi SDK or axios with any valid mongodb 24 digit ID and it will created without any error

**Expected behavior**
It should not create `user` and throw error that `Category with specific ID is not exists` or `invalid category Id`.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-next.11
- Database: MongoDB 3.0.14 Community
- Operating system: Linux Ubuntu 14.04

**Comment by petersg83** [comment]
@derrickmehaffy Is it something to close? I'm not sure to properly understand the issue

**Comment by sobhardwaj** [comment]
is it still open in new release ??

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Is it something to close? I'm not sure to properly understand the issue

AFAIK it still does exist in v4 @petersg83 as you can't mark relations as unique (or required but that's more of a feature request)

**Comment by petersg83** [comment]
What does it mean to have a relation marked as unique?

**Comment by derrickmehaffy** [comment]
> What does it mean to have a relation marked as unique?

The only use-case that comes to mind would be in a one2many or many2many where you couldn't set the same relation on multiple entries (I think)

Take for example a pet vet, they register pet "owners" and "pets" and the link to what owners "own" a pet, that pet should only be allowed to uniquely be assigned to one owner. This is probably a bad example. Similar to the fact we can't set relations as required either :thinking:

**Comment by petersg83** [comment]
Isn't it handle by choosing the right type of relations? If a pet can have one owner only, then it's a `OWNER` one2Many `PET`.

**Comment by derrickmehaffy** [comment]
sounds good, I'll go ahead and close it
