### ISSUE TITLE
Allow definition of null as default value

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#3862]
there are many instances were I would like to define a null value

eg: `endedAt` should be null on creation, and the date set on ending of the model's representation. Therefore all models that don't have an endAt date set have not ended and those that are non-null have ended.

Null default makes a lot of things possible when designing models

**Comment by soupette** [comment]
I agree we should add this option in the content type builder, in the meantime you can set the default value directly in the model's attribute.

for instance:

```
{
  "connection": "default",
  "collectionName": "articles",
  "info": {
    "name": "article",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "title": {
      "type": "string",
      "default": null
    }
  }
}
```

**Comment by cayrescript** [comment]
> Concordo que devemos adicionar essa opção no construtor de tipos de conteúdo. Enquanto isso, você pode definir o valor padrão diretamente no atributo do modelo.
> 
> por exemplo:
> 
> ```
> {
>   "connection": "default",
>   "collectionName": "articles",
>   "info": {
>     "name": "article",
>     "description": ""
>   },
>   "options": {
>     "increments": true,
>     "timestamps": [
>       "created_at",
>       "updated_at"
>     ],
>     "comment": ""
>   },
>   "attributes": {
>     "title": {
>       "type": "string",
>       "default": null
>     }
>   }
> }
> ```

I am using it this way and it works, but when it goes into production it creates the field as empty, "". 
Any idea?

**Comment by emahuni** [comment]
Oh I was doing that 🤦🏽‍♂️ but I was using waterline syntax:
```js
{
   ...
   defaultTo: null,
}
```
and the admin was saying error occurred. I will try that and see if the admin doesn't throw.

Yah, but the null needs to be recognised in the admin studio.

**Comment by derrickmehaffy** [comment]
`admin studio` AdminUI, studio was from Strapi v1 and is no longer used. Just clarifying that for other users.

**Comment by emahuni** [comment]
ok, so what do we call this one?

**Comment by derrickmehaffy** [comment]
It's typically referred to the AdminUI.

**Comment by sarneeh** [comment]
> I agree we should add this option in the content type builder, in the meantime you can set the default value directly in the model's attribute.
> 
> for instance:
> 
> ```
> {
>   "connection": "default",
>   "collectionName": "articles",
>   "info": {
>     "name": "article",
>     "description": ""
>   },
>   "options": {
>     "increments": true,
>     "timestamps": [
>       "created_at",
>       "updated_at"
>     ],
>     "comment": ""
>   },
>   "attributes": {
>     "title": {
>       "type": "string",
>       "default": null
>     }
>   }
> }
> ```

The problem with this approach is that whenever you'll edit the schema in the Admin UI, it will be overwritten without the `default` property.

**Comment by derrickmehaffy** [comment]
Closing this as we have the default option in the CTB now and it should no longer be wiped from the model settings.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/how-do-you-setup-a-definition-to-have-default-null-value/5194/1
