### ISSUE TITLE
The Content Type Builder doesn’t support polymorphic relation attribute display

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#3864]
i created a polymorphic relationship to have 2 tables together in an endpoint but the content -Manager does not work in the admin

<img width="733" alt="Captura de pantalla 2019-08-29 a las 13 48 09" src="https://user-images.githubusercontent.com/14913444/63941006-fb1f7e00-ca6a-11e9-8b61-b35843542d7d.png">

You could also make an endpoint for the polymorphic table to obtain only the related data, it would be very useful for tables that are not related

**Comment by lauriejim** [comment]
Thank you for this reporting.
If you are able to investigate on this issue we will appreciate.$

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
