### ISSUE TITLE
Unable to edit empty ctx.query in policy

### ISSUE THREAD

**Issue by mohanen** [strapi/strapi#3870]
**Describe the bug**
Consider a GET request with a policy to restrict the user to access his data.

when i try to set ctx.query.owner in an empty ctx.query its not reflected but when the ctx.query has any other values in it means its reflected.

**Steps to reproduce the behavior**

1. Create a Policy with `ctx.query.owner = "anything";` 
2. Assign it to any api 
3. Access the api **with query string** in url - **owner will be set**
4. Access the api **with no query string** in url - **owner will not be set** 

**Expected behavior**
No matter the the query string is empty or not i should be able to set the a key value pair in ctx.query

**System**
- Node.js version: v10.16.3
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.15
- Database: MongoDb
- Operating system: Ubuntu 18.04

**Comment by lauriejim** [comment]
Hello @mohanen !
You are right. Thank you for this report.

**Comment by lauriejim** [comment]
This is due to `koa-qs`.
In this case, I suggest you do something like this
```js
ctx.query = {
  ...ctx.query,
  name: "P1"
};
```
It will work in any case.
