### ISSUE TITLE
Limit Graphql/REST results that belongs to owner in Strapi

### ISSUE THREAD

**Issue by raza2022** [strapi/strapi#3873]
****
When a medium Or large project initiated with Strapi, The first thing comes about Access control, and the majority of projects want a very simple and widely accepted use case which is 
**User can only find/update/delete their own documents**
Now there is two thing to solve in strapi (Which till now found let me know if other solution exists) for it one is obviously `roles`, yes these roles great but roles works in more broader way so not suites here, and the second official thing comes `policies`, I know only for this specific Use Case Many developers initiated some customized solution which breaks on every new release, I just wanna to get response if Strapi development Team has plan for builtin policy for this specific USE CASE
USE CASE:
This discussion directly related and based on/from https://github.com/strapi/strapi/issues/624

**Your suggestions for this topic**
I think there should be official way to handle this widely used, USE CASE, and it should work for both REST/GRAPHQL as well or at least there should a good document to solve it so Strapi Starter can achieve it

**Screenshots**
https://imgur.com/a/vNgmVxy

**Code snippets**
https://github.com/strapi/strapi/issues/624

**Additional context**
`IsOwner` defecto policy stops working too after current release. I am looking around strapi code deeply and might start making PRs hopefully

**Comment by raza2022** [comment]
CC: @derrickmehaffy @lucaperret @lauriejim @abdonrd

**Comment by derrickmehaffy** [comment]
Is this a discussion topic?

**Comment by raza2022** [comment]
@derrickmehaffy yes

**Comment by derrickmehaffy** [comment]
As in are you planning to build this yourself, if you are looking to do a feature request then I suggest you open one on the product board: https://portal.productboard.com/strapi/1-public-roadmap/tabs/2-under-consideration

typically discussion topics are to get feedback on something you plan to build yourself or are looking to get a group together to work on it. I agree something needs to be added instead of everyone basically haven't to build the same custom code on all their projects, but the Strapi team themselves are quite busy on a few other things and their short term roadmap is pretty well full until Nov.

**Comment by raza2022** [comment]
I added it here so anyone already know solution or start working one same request the will collaborate to combined effort

**Comment by raza2022** [comment]
I just start this discussion here so get more details/existing solutions from fellow developers and get if anyone already started/implemented same feature within strapi

**Comment by alhill** [comment]
Now it can be done with policies but it's true that in some typical case would be great to have an option for that. Per example, in the project I'm working right now almost every model have a relationship with the "master" model Organization and every role have policies to restrict what they can fetch/edit in their own organization, something like a multitenancy system. Or the case @raza2022  said, users can only fetch/edit models which are related/owned by them.

Policies are great for specific needs but their typical uses should be an option in the CMS

**Comment by derrickmehaffy** [comment]
closing this as it was outlined in the sept blog post: https://strapi.io/blog/monthly-update-september-2019?redirectPage=1

![image](https://user-images.githubusercontent.com/8593673/66478251-cbdb3400-ea4e-11e9-8eb6-0b9641461b49.png)

This will require the new DBAL layer that is currently in development.
