### ISSUE TITLE
Bookshelf search query builder strips unicode/cyrillic characters

### ISSUE THREAD

**Issue by stefanSheva** [strapi/strapi#3874]
**Describe the bug**
Bookshelf search query builder strips unicode/cyrillic characters preventing search in non-english languages.

**Steps to reproduce the behavior**
1. Create a model with a text field
2. Create an object of that model which has some cyrillic/unicode text in the field
    Example: `{ "title": "Објект" }`)
3. Run a REST request on /<model-name>?_q="Објект" 

**Expected behavior**
It should return an array of one object following the previous example, but returns an empty array due to the query being replaced to an empty string due to the regex in `packages/strapi/lib/core-api/queries/bookshelf.js`.

**Screenshots**

**Code snippets**
Relevant snippet causing the issue:

https://github.com/strapi/strapi/blob/5dd0cadafe0fca6e357d12cbcd062aced196fe93/packages/strapi/lib/core-api/queries/bookshelf.js#L141

**Potential fix**

```js
const query = (params._q || '').replace(/[^\u0400-\u04FFa-zA\+-Z0-9.-\s]+/g, '');
```

Changes made:
1. Added `\u0400-\u04FF` unicode range to cover cyrillic languages
2. Added `\+` as an exception to enable multi-word search.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta7 but applicable to all upper versions as well
- Database: Postgres
- Operating system: Linux

**Comment by derrickmehaffy** [comment]
@stefanSheva You up to make a Pull Request?

**Comment by stefanSheva** [comment]
Will do, in a bit.
