### ISSUE TITLE
findOne service returning 404 when querying with anything else than _id

### ISSUE THREAD

**Issue by puzzledbytheweb** [strapi/strapi#3875]
Hello everyone!

**Describe the bug**
When I try to make a query such as:
```
{...controller code}
return strapi.services.myModel.findOne({
           name: "ze"
});
```
It responds with 404 (Not Found). If I do:
```
{...controller code}
return strapi.services.myModel.find({
           name: "ze"
});
```
It responds (correctly) with an array with my only entry for this.

As I'm writing this I wonder if this is an expected behaviour in order to require my field to be unique. If that's so I think it should be clearer in the documentation. 

**Steps to reproduce the behavior**
1. Go to '/api/myModel/controllers/MyModel.js'
2. Write a custom controller that returns the code found above
3. Trigger the controller

**Expected behavior**
It should return the first document that it finds (in this case the unique document).

**Screenshots**
![bugStrapiConsole](https://user-images.githubusercontent.com/35262512/64041364-2ed7d200-cb57-11e9-8676-55663fc5a986.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: MongoDB
- Operating system: Manjaro Linux

**Comment by derrickmehaffy** [comment]
This is intended yes the `findOne` means to find one by it's ID. If you need to filter for anything else I would recommend you use `find` as that accepts all the other filters.

The `findOne` is basically the same as `localhost:1337/somemodel/$ID`
The `find` is basically the same as `localhost:1337/somemodel`

For now I will mark this issue as closed, if you have something else that makes this seem like a bug do let me know and I can reopen this.

**Comment by MaViVa45** [comment]
How to get a specific record using findone by other column but not by it's ID

**Comment by MaViVa45** [comment]
> How to get a specific record using findone by other column but not by it's ID

Remove :id and add your own column name like below for path variable
```
{
      "method": "GET",
      "path": "/somemodels/:column",
      "handler": "somemodel.findOne",
      "config": {
        "policies": []
      }
    },
```
Now add below code to file in controllers folder.
```
const { sanitizeEntity } = require("strapi-utils");

module.exports = {
  async findOne(ctx) {
    const { column } = ctx.params;

    const entity = await strapi.services.somemodel.findOne({ column });
    return sanitizeEntity(entity, { model: strapi.models.somemodel});
  },
};
```

**Comment by derrickmehaffy** [comment]
> > How to get a specific record using findone by other column but not by it's ID
> 
> Remove :id and add your own column name like below for path variable
> 
> ```
> {
>       "method": "GET",
>       "path": "/somemodels/:column",
>       "handler": "somemodel.findOne",
>       "config": {
>         "policies": []
>       }
>     },
> ```
> 
> Now add below code to file in controllers folder.
> 
> ```
> const { sanitizeEntity } = require("strapi-utils");
> 
> module.exports = {
>   async findOne(ctx) {
>     const { column } = ctx.params;
> 
>     const entity = await strapi.services.somemodel.findOne({ column });
>     return sanitizeEntity(entity, { model: strapi.models.somemodel});
>   },
> };
> ```

You will want to build out the path a bit more else a solution like this would mean that the `:id` one is never called. Something like `/somemodels/blah/:column`
