### ISSUE TITLE
Issues with GraphQL policies

### ISSUE THREAD

**Issue by donmasakayan** [strapi/strapi#3880]
I'm reporting 3 issues, all related to GraphQL policies. I've also created a pull request to address these issues. Some of these issues have been reported before (will reference them), but have not been resolved.

- Node.js version: 10.15.1
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: Postgres
- Operating system: Mac OSX Mojave

### Issue 1: Inaccurate Documentation on GraphQL Policies
The official Strapi [documentation for using policies in GraphQL resolvers](https://strapi.io/documentation/3.0.0-beta.x/guides/graphql.html#execute-a-policy-before-a-resolver) says to use `policy: []`, but the code ([here](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-graphql/services/Mutation.js#L29) and [here](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-graphql/services/Query.js#L95)) actually searches for a `policies: []` key. 

Furthermore, REST API routes also use `policies` (and not `policy`). Even though GraphQL can have different policies per action than REST, it still doesn't make sense for these keys to be different. 

As such, documentation should be updated to instead use `policies`.

### Issue 2: Policies not triggering for custom Mutations
GraphQL Mutations policies defined in `schema.graphql`, specifically only those that link to **custom** actions inside controllers do not trigger. 

Mutations that link to shadow CRUD mutations (i.e. createPost) work just fine however.

For example:

In `api/posts/config/schema.graphql`

```
module.exports = {
  resolver: {
    Mutation: {
      customMutation: {
        policies: ["global.myCustomPolicy"], // <-- Does not trigger
        resolver: "Post.customMutation"
      },
      createPost: {
        policies: ["global.myCustomPolicy"], // <-- Triggers alright
        resolver: "Post.create"
      },
    }
  }
}
```

Related issues:
https://github.com/strapi/strapi/pull/3735 - Didn't seem to fix it.
https://github.com/strapi/strapi/issues/2766 - Predecessor to above issue
https://github.com/strapi/strapi/issues/3413

### Issue 3: Policies don't have `ctx.state.user`
Policies for **ALL** GraphQL mutations and queries (both custom and shadow crud) don't have access to `ctx.state.user`.

For example, in `config/policies/myCustomPolicy.js`
```
"use strict";

/**
 * `myCustomPolicy` policy.
 */

module.exports = async (ctx, next) => {
  console.log(ctx.state.user); // Returns undefined

  await next();
};
```

It seems that `ctx.state.user` is being populated just fine via the `permissions.js` policy in `strapi-plugin-users-permissions` [as seen here](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-users-permissions/config/policies/permissions.js#L21).

However, this policy is appended to the end of the policies list (i.e. **only after all other custom policies** (as seen [here](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-graphql/services/Query.js#L238-L240) and [here](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-graphql/services/Mutation.js#L157-L159))), and thus is not accessible.

Related issue:
https://github.com/strapi/strapi/issues/3413

-----

Here's the pull request:
~https://github.com/strapi/strapi/pull/3881~
https://github.com/strapi/strapi/pull/4008 (Updated for 3.0.0-beta.16.3)

**Comment by lauriejim** [comment]
Thank you @donmasakayan for this issue and also for the PR.
Really appreciate!

**Comment by wemod123** [comment]
@donmasakayan  awesome PR 👍 

An additional question: 
How to access `ctx.params` and `ctx.query` in the grphaql policies ?

Refer to [this section description](https://strapi.io/documentation/3.0.0-beta.x/guides/graphql.html#customise-the-graphql-schema), `ctx.params` and `ctx.query` can be accessed in controller, but not in policy.

**Comment by lauriejim** [comment]
In the [policy documentation 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/policies.html#how-to-create-a-policy) you can see, the `ctx` is in function params.

**Comment by wemod123** [comment]
@lauriejim Thank you for your reply.

I had check the code,  [Here](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-graphql/services/Query.js#L263) the policy had been executed, but the `params` and `query` is assign to ctx [Here,](https://github.com/strapi/strapi/blob/0b822a641bff67c9386b3c4e6dc1f21b387edd20/packages/strapi-plugin-graphql/services/Query.js#L285) which is obviously behind the policy.

I'm very new to Javascript, and extremely fresh to graphql, I dont know if it is reasonable or not to move the assignments before policy was called.
