### ISSUE TITLE
Required and unique fields

### ISSUE THREAD

**Issue by sorxrob** [strapi/strapi#3882]
**Describe the bug**
Able to create duplicate and null values using _postman for api_ and _strapi-sdk-javascript for graphql requests_ even if fields are set to required and unique.

**Steps to reproduce the behavior**
1. Create a new Content-Type
2. Add a unique and required field
3. Try to create records and set the required/unique values to null/any record with same data
4. Will still be inserted to database

**Expected behavior**
Since the field is required/unique we should not be able to create a new entry with existing values or null values.

**System**
- Node.js version: v10.15.3
- NPM version: 6.10.1
- Strapi version: 3.0.0-beta.15
- Database: SQLite/MySQL
- Operating system: OS X 10.14.6

**Comment by ashiqsultan** [comment]
Looks similar to issue no #1189

**Comment by derrickmehaffy** [comment]
Agreed @ashiqsultan they are similar and this is planned to be worked on, closing in favor of #1189
