### ISSUE TITLE
MongoDB database connection from AWS EC2

### ISSUE THREAD

**Issue by vnitMendapara** [strapi/strapi#3885]
**Describe the bug**
Strapi is no able to connect remote mongodb (Mongo deployed on AWS EC2), if mongodb security is enabled. from command line able to connect but from strapi it is showing following error.
```
[2019-09-02T09:31:06.230Z] debug ⛔️ Server wasn't able to start properly.
[2019-09-02T09:31:06.231Z] error Make sure your MongoDB database is running...
```

**Steps to reproduce the behavior**
1. Create strapi project locallly with **strapi new project**
2. Create mongodb on AWS EC2 with security enable. (Config referance Url - https://medium.com/mongoaudit/how-to-enable-authentication-on-mongodb-b9e8a924efac )
3. Try to connect strapi with remote ec2 mongodb

**Expected behaviour**
it should work properly but i am getting error like mentioned above.

**Code snippets**
my database.json configuration file is as above.

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "database": database_name,
        "host": **ec2 public url**,
        "port": 27017,
        "username": "", 
        "password": "",
        "ssl": false
      },
      "options": {
      }
    }
  }
}
```

i tired with and without username and password in above config file
username = mongodb database username
password = mongodb database password

**System**
- Node.js version: 10.16.2
- NPM version: 6.11.2
- Strapi version: 3.0.0-beta.15
- Database: Mongo
- Operating system: ubuntu-bionic-18.04-amd64-server of AWS EC2

**Comment by james-knott** [comment]
Having same problem same error

**Comment by vnitMendapara** [comment]
@lauriejim 
Both EC2 (strapi admin and mongo) are in same security group, and all port access are given in inbound as well as outbound .

**Comment by lauriejim** [comment]
You did not answer my question.
Are you able with a UI software like Robot Mongo?

**Comment by vnitMendapara** [comment]
Sorry For Late Reply,
Yes i am able to do with UI software I used dbeaver for testing.

**Comment by mcanzerini** [comment]
+1
