### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by blondie63** [strapi/strapi#389]
I read "SQL & NoSQL databases: Work with Mongo as a main database, also supports Postgres, MySQL, etc." on https://github.com/strapi/strapi
But i don't understand if strapi can works without MongoDB..
I seen that "strapi new myprj" cmd create a project MongoDB based

Thanks for help
Blondie

**Comment by soupette** [comment]
Hi @blondie63! Strapi can totally works without MongoDB. 

In order to do so you have to options : 
1- Setup a new connection from the `settings-manager`[plugin](http://localhost:1337/admin/plugins/settings-manager/databases/development) (in this case you'll have to first have MongoDB running in order to access the admin panel) 

2- Manually setup another database by editing your `./config/environments/**/database.json` [see the documentation](https://strapi.io/documentation/configurations/configurations.html#database). 

If you chose option 2 you have to create your user table beforehand, install your client and run `npm install strapi-bookshelf@alpha` .

**Comment by blondie63** [comment]
Looking on your docs i see that connector can be: "strapi-mongoose" , "strapi-bookshelf" or "connector": "strapi-redis" , right ?

**Comment by soupette** [comment]
You'll need to create the user table to access the admin
```
CREATE TABLE user (
 id INT PRIMARY KEY UNIQUE,
 username TEXT UNIQUE,
 email TEXT UNIQUE,
 provider TEXT,
 password TEXT,
 resetPasswordToken TEXT,
 role TEXT
)
```

Then change your `./config/environments/your_env/database.json` config file.
For example if you like to use `postgres` while developing

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "localhost",
        "port": 5432,
        "database": "my_db",
        "username": "",
        "password": ""
      },
      "options": {}
    }
  }
}
```

**Comment by blondie63** [comment]
Hi, the proble is dependencies !
Look below:
iMac-di-Mauro:test mauro$ npm install

> test@0.1.0 postinstall /Users/mauro/Documents/_projects/Webapp/strapi/test
> node node_modules/strapi/lib/utils/post-install.js

Install plugin content-manager dependencies...
npm notice created a lockfile as package-lock.json. You should commit this file.
Install plugin content-type-builder dependencies...npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN strapi-plugin-content-type-builder@3.0.0-alpha.7.2 No repository field.

Install plugin email dependencies...
npm notice created a lockfile as package-lock.json. You should commit this file.npm WARN strapi-plugin-email@3.0.0-alpha.7.2 No repository field.

Install plugin settings-manager dependencies...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN strapi-plugin-settings-manager@3.0.0-alpha.7.2 No repository field.

Install plugin users-permissions dependencies...
iMac-di-Mauro:test mauro$ npm install

> test@0.1.0 postinstall /Users/mauro/Documents/_projects/Webapp/strapi/test
> node node_modules/strapi/lib/utils/post-install.js
Install plugin content-manager dependencies...
Install plugin content-type-builder dependencies...
npm WARN strapi-plugin-content-type-builder@3.0.0-alpha.7.2 No repository field.

Install plugin email dependencies...
npm WARN strapi-plugin-email@3.0.0-alpha.7.2 No repository field.

Install plugin settings-manager dependencies...
npm WARN strapi-plugin-settings-manager@3.0.0-alpha.7.2 No repository field.
Install plugin users-permissions dependencies...
npm WARN strapi-plugin-users-permissions@3.0.0-alpha.7.2 No repository field.

Install admin dependencies...
npm WARN bookshelf@0.9.5 requires a peer of knex@>=0.6.10 <0.12.0 but none is installed. You must install peer depe
ndencies yourself.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none is installed. You mu
st install peer dependencies yourself.

added 2 packages, removed 1 package and updated 1 package in 9.26s
iMac-di-Mauro:test mauro$ strapi start
WARN (40973 on iMac-di-Mauro.local): (hook:knex) wasn't loaded due to missing key `enabled` in the configuration
DEBUG (40973 on iMac-di-Mauro.local): Server wasn't able to start properly.
ERROR (40973 on iMac-di-Mauro.local): Cannot read property 'knex' of undefined
    TypeError: Cannot read property 'knex' of undefined
    at Function.initialize (/Users/mauro/Documents/_projects/Webapp/strapi/test/node_modules/strapi-bookshelf/lib/index.js:41:25)
    at /usr/local/lib/node_modules/strapi/lib/hooks/index.js:21:31
    at Promise (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:103:37)
    at new Promise (<anonymous>)
    at Promise.all.Object.keys.map.hook (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:48:9)
    at Array.map (<anonymous>)
    at Strapi.module.exports (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:46:28)
    at Strapi.load (/usr/local/lib/node_modules/strapi/lib/Strapi.js:185:23)
    at <anonymous>

**Comment by soupette** [comment]
What node version and strapi are you currently using?

**Comment by blondie63** [comment]
ops.. was an old msg..
i've used 3.0.0-alpha.7.2 on node 8.9.3

**Comment by soupette** [comment]
And do you still have the problem?

**Comment by blondie63** [comment]
I've plan to test again when they/you release alpha.8.x :)
