### ISSUE TITLE
Error: Enum value can only be defined once.

### ISSUE THREAD

**Issue by jonathanredford** [strapi/strapi#3890]
**Describe the bug**
Adding values to an enum field where a word is used more than once across multiple values
ie. 
`Australian Cricket`
`Australian Football`

Error when starting strapi: `Error: Enum value "ENUM_ACCOUNT_DENOMINATION.Australian" can only be defined once.`

The error only arises when using the GraphQL plugin.

**System**
- Node.js version: 11.14.0
- NPM version: 6.10.2
- Strapi version: v3.0.0-beta.15
- Database: MongoDB (local)
- Operating system: macOS 10.14.6

**Comment by derrickmehaffy** [comment]
This is due to the spaces in your values, you will need to use a proper case style without symbols:

```
australianCricket
australianFootball
```
