### ISSUE TITLE
Trying to deploy Strapi on Heroku with MySQL fails due to SSL settings.

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#3891]
**Describe the bug**
Trying to deploy Strapi on Heroku with MySQL fails due to SSL settings.

**Steps to reproduce the behavior**
1.- Open an account on Heroku.
2.- Create an app (following the Strapi-Heroku [deployment guide](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku))
3.- Install the ClearDB MySQL plugin.
4.- Modify `/config/environments/production/database.json` to

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${ process.env.DATABASE_HOST || '127.0.0.1' }",
        "port": "${ process.env.DATABASE_PORT || 3306 }",
        "srv": "${ process.env.DATABASE_SRV || false }",
        "database": "${ process.env.DATABASE_NAME || 'strapi' }",
        "username": "${ process.env.DATABASE_USERNAME || 'strapi' }",
        "password": "${ process.env.DATABASE_PASSWORD || 'strapi' }",
        "ssl": "${ process.env.DATABASE_SSL || true }"
      },
      "options": {
        "ssl": "${ process.env.DATABASE_SSL || true }",
        "authenticationDatabase": "${ process.env.DATABASE_AUTHENTICATION_DATABASE || '' }"
      }
    }
  }
}
```

**Expected behavior**
Deployment is OK and admin opens.

**System**

    Node.js version: v10.15.2
    NPM version: npm -v
    Strapi version: Strapi v3.0.0-beta.15
    Database: MySQL
    Operating system: Ubuntu 19.04

**Comment by brunovianna** [comment]
I'm having the same problem. Here is a printout of the error:

`> strapi start

[2019-11-02T16:48:13.934Z] error Impossible to register the 'category' model.
[2019-11-02T16:48:13.935Z] error TypeError: Unknown SSL profile ''
    at Function.getSSLProfile (/var/www/strapi/cms/node_modules/mysql/lib/ConneconConfig.js:34:24)
    at Object.createConnection (/var/www/strapi/cms/node_modules/mysql/index.js:13:34)
    at /var/www/strapi/cms/node_modules/knex/lib/dialects/mysql/index.js:65:38
    at Promise._execute (/var/www/strapi/cms/node_modules/bluebird/js/release/debuggability.js:411:9)
    at Promise._resolveFromExecutor (/var/www/strapi/cms/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/www/strapi/cms/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL.acquireRawConnection (/var/www/strapi/cms/node_modules/knex/lib/dialects/mysql/index.js:64:12)
    at create (/var/www/strapi/cms/node_modules/knex/lib/client.js:287:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cms@0.1.0 start: `strapi start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cms@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by webcoderkz** [comment]
Just faced the same issue `error Impossible to register the 'category' model.`. Hell, so many headaches to JUST deploy this CMS......

**Comment by derrickmehaffy** [comment]
@webcoderkz need the full error.

@brunovianna Your issue comes from an improper SSL setting on your database.json file

**Comment by webcoderkz** [comment]
@derrickmehaffy i have exact the same error as @brunovianna

**Comment by derrickmehaffy** [comment]
@webcoderkz post your database.json (the one that is actually being used based on your env start settings) and remove any private data.

**Comment by webcoderkz** [comment]
It's by default, i haven't touched it.

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "srv": "${process.env.DATABASE_SRV || false}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "ssl": "${process.env.DATABASE_SSL || false}"
      },
      "options": {
        "ssl": "${process.env.DATABASE_SSL || false}",
        "authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE || ''}"
      }
    }
  }
}

```

**Comment by derrickmehaffy** [comment]
Under your options object delete both those (not sure why you have a mongoDB setting in there for authDB)

Remove the SSL option under the default object unless you know your MySQL DB needs SSL. Also remove the srv option as well.

I'm assuming you are setting the host, port, database, username, and password via ENV variables properly when you start Strapi.

**Comment by webcoderkz** [comment]
@derrickmehaffy if it's not necessary (options object), then why it's here by default? To cause issues for DX?

**Comment by derrickmehaffy** [comment]
Most likely it's from the templates being merged, that error message looks to be coming from Knex (upstream change where they throw and error instead of ignoring keys that don't match valid options).

Yes Strapi for now needs at least 2GB of ram to build due to node-sass which if you take a look at the PRs is in the process being removed. This is not a "simple" and quick change that is being done step by step. :wink: 

Strapi will create the tables and columns from the model however it does not delete or rename any. If you are prone to doing a lot of renames, I'd suggest you plan migrations carefully and make any necessary DB changes manually during a planned maintenance.

**Comment by webcoderkz** [comment]
@derrickmehaffy i do all the db operations manually, because all is strapi can do it's just creating tables... lol

**Comment by derrickmehaffy** [comment]
As I mentioned, upstream problem. Difficult to keep up with especially when people have `^` in their package versions which means knex could just update the next time you use `npm install`

As for creating tables, it's the same with Mongo but that should change in the future, just isn't a priority right now. Lots of other stuff going on. I'm going to close this issue as this should solve everyones problem. I'll a make a PR to clean up the template and remove the un-needed crap from it.

**Comment by brunovianna** [comment]
If anyone needs a quickfix, you can just remove the SSL from the configs:
```

{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "database": "databasename",
        "host": "127.0.0.1",
        "port": 3306,
        "username": "user",
        "password": "pass"
      },
      "options": {}
    }
  }
}
```
