### ISSUE TITLE
Can't upload files through API: Python aiohttp

### ISSUE THREAD

**Issue by emptyopen** [strapi/strapi#3895]
Been banging my head and trying every combination I can think of, but continue to get a 400 response. 

I have been successful with Postman with the following process:
1) "Login" and retrieve JWT
2) Use JWT as auth header and POST a form-data file 

However, with Python and aiohttp, I cannot perform the second step. I can successfully retrieve the JWT, but cannot find a format to send the form-data in. 

Here is the code that I have been using:

```
resp = await session.request(method='POST', url=self.ip_address + '/upload',
                                         headers={'Content-Type': 'application/json',
                                                  'Authorization': f'Bearer {self.jwt}'},
                                         data=body)
```

For `body`, I have tried:
```
body = aiohttp.formdata.FormData()
body.add_field('files', filepath, filename=f'@{filepath}', content_type='application/json')
For this one, I've tried the above without content_type field, without the `@` symbol, with just 'files' and filepath
``` 
`body = json.loads({'files': filepath})`
`body = {'files': filepath}`
and a whole bunch of others. 

Whenever I manage to actually get a request through and get the 400 error, the error is always the same: 

> [2019-09-04T01:03:38.881Z] error Error: invalid JSON, only supports object and array
>     at parse (/home/ubuntu/nostradamus.strapi/node_modules/co-body/lib/json.js:60:13)
>     at /home/ubuntu/nostradamus.strapi/node_modules/co-body/lib/json.js:45:22
>     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
