### ISSUE TITLE
Collections not created automatically on MongoDB

### ISSUE THREAD

**Issue by flavea** [strapi/strapi#3899]
**Describe the bug**
I am currently using strapi with strapi-docker with MongoDB database hosted on alicloud. I build the API using content type builder on my local with local MongoDB and development environment, and it's working fine as it should be, all files and collections are generated as they should. But when I deployed it to staging and production, the collections/tables are not created and I have to manually create the collection. Sometimes the collections are created, but more often they are not. I have access to the database so I can create the collections myself, but this might be troubling in the future. Any idea on why this happens? I am not sure if this is related to the database, docker/kubernetes, or strapi itself.

**Steps to reproduce the behavior**
1. Create content type on development.
2. Deploy it to staging and then production.

**Expected behavior**
The MongoDB collection should be generated/created upon deployment.

**System**
- Node.js version: node:11.1.0-alpine (docker) - 10.6 (local)
- NPM version: ^6.0.0
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
@flavea Strapi alpha is no longer supported, if you are using the strapi-docker repo it has not been updated and you should built your own container for now.

I'm closing the issue as Alpha is no longer supported only the beta versions.
