### ISSUE TITLE
accessing the admin area from a new tab will prompt the user to re-enter his login credentials even if he was already authenticated.

### ISSUE THREAD

**Issue by hadihallak** [strapi/strapi#390]
**Node.js version**: v8.2.1
**npm version**: 5.4.2
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: windows 10

Title ^

**Comment by soupette** [comment]
Hi @hadihallak what browser were you using?

**Comment by hadihallak** [comment]
@soupette Chrome Version 63.0.3239.84 (Official Build) (64-bit)

**Comment by acifer** [comment]
This problem is in mac safari too.

**Comment by soupette** [comment]
You'll have to check the remember me checkbox if you want to stay logged in
