### ISSUE TITLE
error: invalid input syntax for type json

### ISSUE THREAD

**Issue by merijnponzo** [strapi/strapi#3901]
Hello,

I had a json field within a contenttype. I added some content into it.
But decided to remove the field after all.

Next time when I save my document (contenttype page)
I got these errors

```
error error: invalid input syntax for type json
    at Connection.parseE (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta13/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta13/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Applications/AMPPS/www/puppyplaza/puppyplaza_postdev_beta13/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:638:20)
```

Steps to reproduce:
See my introduction

Node v10.6.0
Mac
strapi 3.0.0-beta.13
Postgres

I tried to restart strapi. With no success.

The solution is to remove the column within my database

**Comment by derrickmehaffy** [comment]
For now marking this issue as closed, @merijnponzo if you have the information that @lauriejim is requesting we can reopen this. Thanks!

**Comment by rovaniemi** [comment]
@derrickmehaffy @lauriejim this bug is still in the Strapi. 

The problem occurs when the admin wants to change the JSON field content type. After deleting the JSON field and recreating new content type with the same name the following error message will appear

```
error: invalid input syntax for type json
```

Versions:
Node v12.11.1
MacOs Catalina 10.15
strapi 3.0.0-beta.17.5
Postgres 12

**Comment by derrickmehaffy** [comment]
@rovaniemi that is expected, you have to manually clean up your database, strapi doesn't delete tables it columns

**Comment by dvidsilva** [comment]
@monolithed something happened to me 

created a field as "richtext"

yarn dev 


stop

changed field to "blocks"


```
⠏ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌───────────────────────────────────────────────────────────────────────────┐│                                                                           ││   error: alter table "public"."collections" alter column "description"    ││   type jsonb using ("description"::jsonb) - invalid input syntax for      ││   type json                                                               ││   at Parser.parseErrorMessage (/Users/daveed/code/markketplace/node_mod   ││   ules/pg-protocol/dist/parser.js:283:98)                                 ││   at Parser.handlePacket (/Users/daveed/code/markketplace/node_modules/   ││   pg-protocol/dist/parser.js:122:29)                                      │

```

Found a workaround, but sharing in case is useful
