### ISSUE TITLE
Keyboard navigation support within the AdminUI

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#3903]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

 **Please describe your feature request:**

Support better keyboard navigation on the adminUI in general as well as specifically for the CTM and CTB plugin UIs.

This was a suggestion from the Coding with Jason livestream: https://www.twitch.tv/videos/476766670

Also per request tagging @davidkartuzinski

**Comment by davidkartuzinski** [comment]
The example, from the video, was entering the tabbed components (with just the keyboard) in and out and then navigating within the tab itself.

**Comment by derrickmehaffy** [comment]
As sysadmin by day I'm well aware of how important keyboard navigation can be :) Used to working with servers without the aid of a mouse but this is something many programmers and developers prefer as to not take our hands off the keyboard.

It should be more or less possible to navigate most if not the entire admin with just the keyboard.

**Comment by soupette** [comment]
@derrickmehaffy that's something we can work on, there's a [*Shortcut component](https://github.com/strapi/buffet/blob/master/buffet/src/components/Shortcut/index.js) waiting in [Buffetjs](https://buffetjs.io). Also, some plugins also have keyboard navigation like the users-permissions (ctrl+n)

**Comment by derrickmehaffy** [comment]
Fixed in v4, marking as closed
