### ISSUE TITLE
Two column relation to one table, save error

### ISSUE THREAD

**Issue by rockswang** [strapi/strapi#3913]
**Describe the bug**
I have two table: terms & links
"link" record is used to describe the relationship between two terms
The content types can be saved without problem, but when I was trying to add a link record for two terms, i cannot save successfully.

**Steps to reproduce the behavior**
see description

**System**
- Node.js version: 12.5
- NPM version:
- Strapi version: latest 3.0.0-beta
- Database: mysql
- Operating system: windows 10 x64

**Additional context**
No

**Comment by derrickmehaffy** [comment]
@rockswang please properly fill out the bug report template and include as much information as possible such as sample model settings files. System information should be filled out as detailed as possible.

Thanks

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
