### ISSUE TITLE
Create 2 Many-to-One to the same model with the same attribute name

### ISSUE THREAD

**Issue by rockswang** [strapi/strapi#3914]
**Describe the bug**
I have two table: terms & links
"link" record is used to describe the relationship between two terms
The content types can be saved without problem, but when I was trying to add a link record for two terms, i cannot save successfully.

**Steps to reproduce the behavior**
1. create 'term' content type
2. create 'link' content type, add two relation columns: 1) 'subj' relate to Term via 'terms' in many-to-one 2) 'obj' relate to Term via 'terms' in many-to-one 
3. Add two term records, it's ok
4. Add a link record for above-mentioned term records, I cannot save, error message is "links is not defined on the model."

**Expected behavior**
link record can be saved

**Screenshots**
none

**Code snippets**
none.

**System**
- Node.js version: 12.5
- NPM version:
- Strapi version: 3.0.0-beta
- Database: mysql
- Operating system: win10 x64

**Additional context**
none.

**Comment by derrickmehaffy** [comment]
@rockswang again please ensure the systems fields are field out completely:

```
System

Node.js version: 12.5
NPM version:
Strapi version: 3.0.0-beta
Database: mysql
Operating system: win10 x64
```

What version of MySQL and Strapi Beta?

Also please provide your `api/term/models/Term.settings.json` and `api/link/models/Link.settings.json` files

**Comment by rockswang** [comment]
MySQL version: 5.7.17
Strapi version: v3.0.0-beta.15
Term.settings.json:
```json
{
  "connection": "default",
  "collectionName": "terms",
  "info": {
    "name": "term",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "links": {
      "collection": "link",
      "via": "obj"
    }
  }
}
```
Link.settings.json
```json
{
  "connection": "default",
  "collectionName": "links",
  "info": {
    "name": "link",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "subj": {
      "model": "term",
      "via": "links"
    },
    "obj": {
      "model": "term",
      "via": "links"
    },
    "label": {
      "type": "string"
    }
  }
}
```
