### ISSUE TITLE
Choose the field that content types display when adding relation.

### ISSUE THREAD

**Issue by tcvmdev** [strapi/strapi#3918]
**Describe the topic**
Currently I have a testimonial content type and a student content type with a many-to-one relationship. When I'm creating a relation from testimonial to student, the drop down shows just the first name of the student.

The main issue here is that many students have the same first name, and the only way to properly choose the correct student for the testimonial is to go through them one-by-one (while memorizing their order), and clicking the "Details" on the top right corner of the student selector.

**Your suggestions for this topic**
Is there a way to define the label that displays for the student e.g. lastName, firstName? Thanks for the great CMS, and thank you for your help!

**Comment by derrickmehaffy** [comment]
This has already been added and will be in beta.16 with an ETA of around Sept 17th

**Comment by tcvmdev** [comment]
@derrickmehaffy I just updated to the beta.16.5, and loving the group fields. I'm reaching out again for changing the field that is displayed when picking a relationship. 

Right now, only the _id fields are being displayed for content types that I'm trying to relate to one another. Is there a way to change the field that is being displayed in the new beta?

Thanks again!
<img width="218" alt="Screen Shot 2019-09-18 at 5 00 16 PM" src="https://user-images.githubusercontent.com/54483758/65189193-e6188800-da35-11e9-9ed4-fdb3c367ce37.png">

**Comment by lauriejim** [comment]
Hello @tcvmdev !
Yes you have to go in `content manager` in the left menu.
Then you click on the content type that have the `Semesters` relation.
Click on the `Edit View` tab.
And to conclude, click on the relation, at the bottom of the page, you will be able to change the *Entry Title*
