### ISSUE TITLE
Using MySQL as database

### ISSUE THREAD

**Issue by RWOverdijk** [strapi/strapi#392]
**Node.js version**: 8.9.3
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: MacOS 10.13.2

I'm trying to set MySQL as the primary database, but it seems to not run migrations and create the tables. Is this an extra manual step I should be taking?

**Comment by soupette** [comment]
Hi @RWOverdijk if you're using MySQL you have to manually create the tables, migrations can only be ran if you're using MongoDB.

**Comment by RWOverdijk** [comment]
@soupette Which tables? Where can I find the tables to be created?

**Comment by soupette** [comment]
You just need to create the user table
```
CREATE TABLE user (
 id INT PRIMARY KEY UNIQUE,
 username TEXT UNIQUE,
 email TEXT UNIQUE,
 provider TEXT,
 password TEXT,
 resetPasswordToken TEXT,
 role TEXT
)
```

**Comment by soupette** [comment]
I'm closing the issue

**Comment by lachlantweedie** [comment]
This would be great in the docs - spent a while looking for how to do this with Postgres.

**Comment by elialber** [comment]
Unhandled promise rejection (rejection id: 1): Error: select count(*) as `count` from `users-permissions_role` - ER_NO_SUCH_TABLE: Table ',myproject.users-permissions_role' doesn't exist
