### ISSUE TITLE
Permission deletion/creation on deletion/creation content type

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#3925]
**Describe the bug**
Impossible to find content type permission of a content type I created.

**Steps to reproduce the behavior**
1. Create a content type names `restaurant`
2. Go to Roles & Permissions
3. Check Application permissions in any role (you will see `Restaurant` permissions)
4. Go in the content type builder and delete the `restaurant` content type.
5. Recreate a content type with the same name.
5. Recheck the role, the `Restaurant` permissions don't exist.

**Expected behavior**
I expected to have the ability to manage `Restaurant` permissions.

**System**
- Node.js version: v12.6.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16
- Database: SQLite
- Operating system: MacOS

**Additional context**
We can notice the permissions for the `Authenticated` role works fine!

**Comment by mtmsuhail** [comment]
you are deleteting the content type in 4th step. then why you need permission for no-existing content type?

**Comment by derrickmehaffy** [comment]
> you are deleting the content type in 4th step. then why you need permission for no-existing content type?

I second this, why should you see permissions for a content-type you deleted?

**Comment by davidkartuzinski** [comment]
I believe he left off the step of adding the exact same Content Type back. In this case, adding back Restaurant. That would go between steps 4 and 5. 

So create a content type, delete it, and then put it back.

This can happen for a number of reasons.
