### ISSUE TITLE
Error Migrating from beta-15 to beta-16 with Mysql 

### ISSUE THREAD

**Issue by nicolaniro** [strapi/strapi#3927]
**Describe the bug**
Updating strapi from beta-15 to beta-16 leads to an error:
```
[2019-09-09T16:30:16.843Z] error Bootstrap function in plugin "users-permissions" failed
[2019-09-09T16:30:16.845Z] error TypeError: Cannot read property 'id' of null
    at permissions.reduce (/Users/nicolaniro/dev/strapi/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:437:116)
```

**Steps to reproduce the behavior**
1. `strapi new strapi` (this will install strapi beta-15)
2. select mysql (i have amazon RDS free tier)
3. `cd strapi`
4. `npm install`

5. Do the migration from 15 to 16 following [the official guide](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html#bootstrap-function), in particular update from 15 to 16 these packages:
```
    "strapi": "3.0.0-beta.16",
    "strapi-admin": "3.0.0-beta.16",
    "strapi-utils": "3.0.0-beta.16",
    "strapi-plugin-settings-manager": "3.0.0-beta.16",
    "strapi-plugin-content-type-builder": "3.0.0-beta.16",
    "strapi-plugin-content-manager": "3.0.0-beta.16",
    "strapi-plugin-graphql": "3.0.0-beta.16",
    "strapi-plugin-users-permissions": "3.0.0-beta.16",
    "strapi-plugin-email": "3.0.0-beta.16",
    "strapi-plugin-upload": "3.0.0-beta.16",
    "strapi-hook-bookshelf": "3.0.0-beta.16",
    "strapi-hook-knex": "3.0.0-beta.16",
```

6. modify /strapi/config/functions/bootstrap.js 

```
const doingNothing = () => console.log("Doing nothing")
module.exports = async () => {
  await doingNothing();
};
```
7. `npm install`
8. `rm -rf ./build`
9. `npm run build`
10. `npm run dev`

**Expected behavior**
expected strapi to start

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: beta-15 upgrating to 16
- Operating system: MAC O/S 10.14 MOJAVE

**Comment by alexandrebodin** [comment]
Hi,

It looks like some of your permissions are linked to non existent roles. Can you verify that you do not have rows in the table `users-permissions_permission` with role set to null.

**Comment by nicolaniro** [comment]
Yes, there are some rows with NULL permissions. No idea why that’s is happening

**Comment by alexandrebodin** [comment]
@nicolaniro Can you share how many rows you have with that null role and what they are ?

**Comment by nicolaniro** [comment]
@alexandrebodin these are the rows with NULL in the role column

![Image](https://user-images.githubusercontent.com/16844846/64606716-2ee19880-d3c7-11e9-805b-19b620f72167.png)

**Comment by michaeltrim** [comment]
For anyone coming across this error, when creating a new mongodb instance I ended up with duplicate records for all the users-permissions_ types, solved by deleting the first set that were created with no role

**Comment by Lokinorse** [comment]
The same error here. I can assure I have no rows with null role.

**Comment by SonySadi** [comment]
I deleted all the rows and set the permission again

**Comment by ryanhex53** [comment]
For anyone clone mongodb instance (use mongodump & mongorestore), this error will happen. Because the `role`  objectid in collection `users-permissions_permission` will not match any records in `users-permissions_role`.

**Comment by ryanhex53** [comment]
For anyone clone mongodb instance use `mongodump` & `mongorestore` without `--gzip` option, this error will happen. the `role` objectid in `users-permissions_permission` may not match any records in collection `users-permissions_role`.

When you dump & restore mongodb, please add `--gzip` option to keep objectid same as original.

**Comment by sergioarroyop** [comment]
Leyend @ryanhex53, you saved my day
