### ISSUE TITLE
Graphql createUser can create user without password

### ISSUE THREAD

**Issue by daehruoydeef** [strapi/strapi#3928]
**Describe the bug**
createUser mutation does not require a password and creates a User with a empty password.

**Steps to reproduce the behavior**
1. install strapi and quickstart
2. install graphql
3. use mutation as stated in strapi documentation (see code snippets)
4. look into 

**Expected behavior**
Send Error Message that a password is required!

**Code snippets**
`mutation {
  createUser(input: {
    data: {
      username: "John",
      email: "john@doe.com"
    }
  }) {
    user {
      username
      email
    }
  }
}`

However if you add a password field inside the mutation, the password will be set for the user but I feel like this should throw a error Message.

**System**
- Node.js version: v11
- NPM version: 6.9
- Strapi version: 3.0.0 beta.8
- Database: MongoDB
- Operating system: Ubuntu 18.10

**Comment by derrickmehaffy** [comment]
There shouldn't be any security issue as a user without a password would fail authentication AFAIK

**Comment by derrickmehaffy** [comment]
@daehruoydeef 

Can you please do me a favor and config this bug on recommended versions? Typically bug reports are ignored if they aren't using latest versions:

```
Node.js version: v11
Strapi version: 3.0.0 beta.8
```

Node 10 or 12 (preferably 12 since it goes LTS in just under a month)
beta.15 or 16 (preferably 16 since it was just released today)

**Comment by daehruoydeef** [comment]
I tested again with strapi beta.16 and it throws an error on a missing password. I will keep in mind to always check for the latest version I just did npm i -g strapi@beta and thought I was fine and got the latest version. 

I think the Documentation needs an update so a password field is added since when you copy the example now it does not work.
