### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by pcornier** [strapi/strapi#393]
**Node.js version**: 8.9.3
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: Ubuntu 16.04

It seems not possible to create the first user after moving Strapi to production.
 
I installed Nginx and redirected port 80/443 to localhost:1337 but when I try to access:
`https://mydomain.org/admin`

I'm redirected to:
`https://mydomain.org/http://localhost:1337/admin/plugins/users-permissions/auth/register`

**Comment by Aurelsicoko** [comment]
Did you set the `host` domain in your build configuration [(see the documentation)](https://strapi.io/documentation/advanced/customize-admin.html#deployment)? You will need to rebuild the administration panel then.

**Comment by pcornier** [comment]
I was able to access the administration today:

- I re-installed everything
- I changed my config (just changed host in `server.js`)
- then I ran `npm install` in root directory and in admin directory.

I'm not quite sure I understand why it started to work - the only thing I changed is the configuration file that was edited before running `npm install` -  so I think this should be tested again by someone else and clearly written somewhere.

**Comment by Aurelsicoko** [comment]
The administration needs to know the host (IP or domain) to work well. I've added a new section in the documentation to explain [How to deploy](https://github.com/strapi/strapi/pull/397/commits/3c7efa07f819ed23be5a50324062adfd337cd0b0#diff-925b742cb88b0afdae5671aa57a18fe3).

**Comment by franzos** [comment]
This related to #423. Even with the correct settings, the admin panel remains inaccessible.

**Comment by Aurelsicoko** [comment]
It should be fixed with these changes https://github.com/strapi/strapi/pull/431
