### ISSUE TITLE
Hide some access on sidebar

### ISSUE THREAD

**Issue by jonathanroze** [strapi/strapi#3931]
Hi,

 I want to hide some content on the left sidebar, i'm using Strapi 3.0.0-beta.14.

I try different solutions founded on Github but it doesn't work!

Thanks!

**Comment by soupette** [comment]
@jonathanroze, 

With the latest beta (v.16) you can modify the [content manager](https://github.com/strapi/strapi/blob/eec3acfa6350b89cb1bbe166f9757acb0a0ecc2b/packages/strapi-plugin-content-manager/controllers/ContentTypes.js#L10-L47)'s controller in order to hide/show specific content types.

**Comment by jonathanroze** [comment]
I need to edit directly this file or via layout.js in admin/config ?

**Comment by derrickmehaffy** [comment]
This will be apart of this feature request: https://portal.productboard.com/strapi/1-public-roadmap/c/13-administration-menu marking this as closed for now.
