### ISSUE TITLE
ctx.request.body.files is undefined in beta.16

### ISSUE THREAD

**Issue by rejifald** [strapi/strapi#3933]
**Describe the bug**
After migrating from beta.15 to beta.16 I faced with problem that `ctx.request.body.files` now is undefined.

**Expected behavior**
`ctx.request.body.files` contains sent files.

**Code snippets**
Working code in beta.15
```
'use strict';
const sharp = require('sharp');
const fs = require('fs');

/**
 * A set of functions called "actions" for `ImageProcessing`
 */

module.exports = {
  resize: async (ctx, next) => {
    const image = ctx.request.body.files.image;
    const { width, height, ...opts } = ctx.request.body.fields;
    if (!width || !height) {
      ctx.throw(400, 'You must specify both width and height.');
    }

    let imgPath = strapi.config.appPath + `/uploads/${width}x${height}-${image.name}`;
    await sharp(image.path).resize(+width, +height, opts).toFile(imgPath);
    const file = await strapi.services.utils.uploadFile(ctx, {
      file: fs.createReadStream(imgPath),
    });

    fs.unlink(imgPath, () => {});

    ctx.send(file);
    next();
  }
};
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16
- Database: MongoDB
- Operating system: MacOS

**Comment by alexandrebodin** [comment]
We have upgraded the dependency koa-body. 
Now the files are on `ctx.request.files`. I am going to update the changelog thanks for the notice !
