### ISSUE TITLE
Is it possible to upload external files via URL

### ISSUE THREAD

**Issue by zmaximov-roi** [strapi/strapi#3937]
What is a proper way to upload external file via URL?

I would like to upload user images through the social login process. But got a problem with getting file in a suitable format for  strapi.plugins.upload.services.upload.upload()

Currently I see two possible solutions but they are ugly:
- send request from backend to api, append received data to node.js FormData and send request to /upload endpoint.

```
const formData = new FormData()
formData.append('files', request(imageUrl))

const file = await fetch('http://localhost:1337/upload', {
    method: 'POST',,
    body: formData
})
    .then(res => res.json())
```

- get file buffer, create an object with it, pass it to bufferize service strapi.plugins.upload.services.upload.bufferize() and then pass result to upload service:

```
const image = await fetch(imageUrl)
    .then(res => res.buffer())
const buffers = await strapi.plugins.upload.services.upload.bufferize({
        buffer: image,
        name: 'logo.png',
        mime: 'image/png',
        size: 20000
});
const uploadedFiles = await strapi.plugins.upload.services.upload.upload(
    buffers,  {
        provider: 'local',
        name: 'Local server',
        enabled: true,
         sizeLimit: 1000000
    }
);
```

**Comment by ningacoding** [comment]
because of strapi does not support base64 upload file, so we can add an endpoint that does and then post the file to upload.

**Comment by sevenkoncepts** [comment]
Hello every one when i use this formla to upload file in strapi

const image = await fetch(imageUrl)
    .then(res => res.buffer())
const buffers = await strapi.plugins.upload.services.upload.bufferize({
        buffer: image,
        name: 'logo.png',
        mime: 'image/png',
        size: 20000
});
const uploadedFiles = await strapi.plugins.upload.services.upload.upload(
    buffers,  {
        provider: 'local',
        name: 'Local server',
        enabled: true,
         sizeLimit: 1000000
    }
);

I get this error

error TypeError: strapi.plugins.upload.services.upload.bufferize is not a function
    at Object.module.exports [as upload] (/Users/macbookpro/path-to-folder/config/functions/upload.js:24:62)

In upload.js on line 24 I have this code

const buffers = await strapi.plugins.upload.services.upload.bufferize({
    path: imgPath,
     buffer: image, 
    name: name,
    type: `image/${ext}`,
    size: buffer.toString().length 
  });

Looking forward to hear from you all experts

**Comment by brijmcq** [comment]
@sevenkoncepts  bufferize function was removed. you can check it here https://github.com/strapi/strapi/commit/e5b319d81e2870dd77667503c36a33be6f058afa#diff-3a7fa35e6ea39d3bd6114d319f1ce604b67ab84e30d27078045cb79d5fe5829cL26

Were you able to get it worked?

**Comment by kevinvugts** [comment]
> What is a proper way to upload external file via URL?
> 
> I would like to upload user images through the social login process. But got a problem with getting file in a suitable format for strapi.plugins.upload.services.upload.upload()
> 
> Currently I see two possible solutions but they are ugly:
> 
> * send request from backend to api, append received data to node.js FormData and send request to /upload endpoint.
> 
> ```
> const formData = new FormData()
> formData.append('files', request(imageUrl))
> 
> const file = await fetch('http://localhost:1337/upload', {
>     method: 'POST',,
>     body: formData
> })
>     .then(res => res.json())
> ```
> 
> * get file buffer, create an object with it, pass it to bufferize service strapi.plugins.upload.services.upload.bufferize() and then pass result to upload service:
> 
> ```
> const image = await fetch(imageUrl)
>     .then(res => res.buffer())
> const buffers = await strapi.plugins.upload.services.upload.bufferize({
>         buffer: image,
>         name: 'logo.png',
>         mime: 'image/png',
>         size: 20000
> });
> const uploadedFiles = await strapi.plugins.upload.services.upload.upload(
>     buffers,  {
>         provider: 'local',
>         name: 'Local server',
>         enabled: true,
>          sizeLimit: 1000000
>     }
> );
> ```

Hi @zmaximov-roi 

Did you managed to get it working? I tried several things but didn't got it working yet.

Best,

**Comment by cosydney** [comment]
Hey, Similar issue here. 

I would like to get a image url as an input and upload it to aws s3 via Strapi so it creates an file entry. The solution above seems not to be up to date with the current version of Strapi. Has anyone been doing this on their own ? 

Cheers !

**Comment by iamjagan** [comment]
For anyone else still looking at a solve, the following upload.js worked for me 
`const path = require('path');
const fs = require('fs').promises;

module.exports = async (imgPath) => {
  
  // we want the file type without the "." like: "jpg" or "png"
  const ext = path.extname(imgPath).slice(1);
  // name of the file like image01.jpg
  const name = path.basename(imgPath);
  // read contents of file into a Buffer
  const buffer = await fs.readFile(imgPath);
  // get the buffersize using service function from upload plugin
  const fileData = await strapi.plugins.upload.services.upload.enhanceFile({
    path: imgPath,
    name,
    type: `image/${ext}`,
    size: buffer.toString().length 
  });
  return strapi.plugins.upload.services.upload.uploadFileAndPersist(fileData);
  
}`

**Comment by Yondo202** [comment]
adsgasg
