### ISSUE TITLE
Sqlite3 client missing when building admin panel in production mode

### ISSUE THREAD

**Issue by nahueld** [strapi/strapi#3939]
**Describe the bug**
When running `NODE_ENV=production IS_ADMIN=true npm run setup --debug` the process fails because sqlite3 is not installed

**Steps to reproduce the behavior**
1. Go to your strapi app directory
2. Run `NODE_ENV=production IS_ADMIN=true npm run setup --debug`
3. See error

```
🏗  Building the admin...

> strapi-admin@3.0.0-alpha.26.2 prebuild /Users/nahuel/Projects/Personal/site/api/admin
> cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

[2019-09-09T22:46:48.377Z] error The client `sqlite3` is not installed.
[2019-09-09T22:46:48.378Z] error You can install it with `$ npm install sqlite3 --save`.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.26.2 prebuild: `cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.2 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```

**Expected behavior**
The error should not be reproduced and the panel built.

**System**
- Node.js version: v10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2

**Comment by lauriejim** [comment]
OKay good. We are focussing on the beta version.
I close this issue since it's related to `alpha` and there is a workaround here.
