### ISSUE TITLE
All API routes return a 404 error

### ISSUE THREAD

**Issue by kmohab71** [strapi/strapi#3941]
I was working on a project with strapi and react and suddenly when i run the strapi from the terminal it runs normally but doesn't work in the browser all the pages gives the same error {"statusCode":404,"error":"Not Found","message":"Not Found"}
but in the frontend all the API requests to gets a normal request from strapi 
<img width="839" alt="Screen Shot 2019-09-10 at 4 58 49 AM" src="https://user-images.githubusercontent.com/34548894/64590883-38600600-d3b1-11e9-8d28-70e314487434.png">

system 
- Node.js version: 12.6.0
- NPM version:6.11.3
- Strapi version: 3.0.0-beta.15
- Database: mongoDB atlas
- Operating system:MacOs mojave

**Comment by geminigeek** [comment]
i am having a similar issue with login , users cant login via api all login request get 404, the user creation works perfectly !!

**Comment by kmohab71** [comment]
Yes but my problem that all the strapi pages doesn’t open they give me 404 not found

**Comment by lauriejim** [comment]
Hello @kmohab71 ! Your issue is super weird.
I suppose your APIs (article, course, journal) exist.
Here I don't see any reason why it happens.
Did you customize something in your application?

**Comment by kmohab71** [comment]
Hello @lauriejim no i didn't do any customization 
that what appears when i try to access http://localhost:1337/admin

<img width="1680" alt="Screen Shot 2019-09-14 at 3 28 19 PM" src="https://user-images.githubusercontent.com/34548894/64908753-4f319000-d704-11e9-9642-e9ae81ef9bd3.png">

**Comment by lauriejim** [comment]
In your application can you run `yarn && yarn build`
Or if you use npm `npm i && npm run build`

**Comment by kmohab71** [comment]
@lauriejim i use npm

**Comment by lauriejim** [comment]
And does it solve your issue?

**Comment by kmohab71** [comment]
@lauriejim i deleted the package-lock and the node modules then used yarn install(instead of npm install ) then strapi develop and it works perfectly now 
thank you for your time

**Comment by davidkhierl** [comment]
same having this issue after updating and creating some new content type all of the sudden some icons become 404, then I tried to refresh the page and it showing {"statusCode":404,"error":"Not Found","message":"Not Found"} tried to restart the container yet no luck

**Comment by demiton** [comment]
I have the same issue. Everything working but after adding a new field to a single type, i get a 404 error : 
``` 
ERROR #11321  PLUGIN
"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

Request failed with status code 404
  Error: Request failed with status code 404
```
I tried to build again strapi and restart, but same result

**Comment by pedromihael** [comment]
Some update around here?

**Comment by hellobrunao** [comment]
Hi all. I'm having the same issue. I've created some Single Types, enabled them as public on user roles, and the endpoints are giving me a 'Not Found' error on all routes created.

this is what I have in one of the api endpoints (page-home) routes.json file:

```
{
  "routes": [
    {
      "method": "GET",
      "path": "/page-home",
      "handler": "page-home.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/page-home",
      "handler": "page-home.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/page-home",
      "handler": "page-home.delete",
      "config": {
        "policies": []
      }
    }
  ]
}
```

it returns only 'Not Found' when I try a GET in postman:

![image](https://user-images.githubusercontent.com/6074367/101683796-35384780-3a44-11eb-9855-e736aa6d633f.png)

Anyone was able to solve it?

**Comment by pedromihael** [comment]
Brunão, isso parece estranho mesmo. Tenta escrever um strapi lifecycle hook do tipo afterFind() que simplesmente retorna um `{ res: "ok" }` e vê se seu get surte efeito.

**Comment by pedromihael** [comment]
For common knowledge, above I suggested that a lifecycle hook should be created to force any return to the route with get method.

See more about lifecycle hooks: https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

**Comment by hellobrunao** [comment]
Hey @pedromihael I've found what was the problem.
For anyone who is having the same hard time as I was, the problem was a silly thing… you gotta Save the single type and then **Publish** it. I had only saved, that’s why it was returning not found.

I think it is a bad UX that could be improved, since on the Collection Type doesn't require to Publish it, only save and it is done. I literally spent 5 hours of my day trying to figure what was wrong with the API… bad UX was the problem.

**Comment by KibobiShtrudelz** [comment]
> Hey @pedromihael I've found what was the problem.
> For anyone who is having the same hard time as I was, the problem was a silly thing… you gotta Save the single type and then **Publish** it. I had only saved, that’s why it was returning not found.
> 
> I think it is a bad UX that could be improved, since the Collection Type doesn't require publishing, only save and it is done. I literally spent 5 hours of my day trying to figure what was wrong with the API… bad UX was the problem.

Thank you @hellobrunao !!! You saved me :D

**Comment by SagaraZD** [comment]
@hellobrunao  thanks for reminding this :D

**Comment by MikeReyCodes** [comment]
Ok guys there's a few reasons why you may have 404 - which by the way is the default error. 

1. Drafts, quite common you can unset this in the Content-Type-Builder
2. The path. is now  localhost:1337/**api**/[your route] 
3. **Permissions**, go to settings then Public, and check you have given permission for the routes to be read. You can also see when you do this, that it shows you the correct GET path, which shows api there. 

A lot of tutorials from even just one year ago don't have this as it's a recent change, so I hope I've helped some of you.

**Comment by jmucio** [comment]
Thanks @MikeReyCodes 

I was following a tutorial which must have been based upon an older version of Strapi. The [base-url]/api/[your-route] was the ticket. I was leaving the /api out.

**Comment by ssshammi** [comment]
Hi i think this work in pastman but not when i call the services from andriod app. i tried to call localhost:1337/api/auth/local
from app and it does not return anything just 404. should I add cros ?

**Comment by jmone01** [comment]
Very helpful and greatly appreciated @MikeReyCodes. Good tutorials out there, but all now outdated!

> Ok guys there's a few reasons why you may have 404 - which by the way is the default error.
> 
> 1. Drafts, quite common you can unset this in the Content-Type-Builder
> 2. The path. is now  localhost:1337/**api**/[your route]
> 3. **Permissions**, go to settings then Public, and check you have given permission for the routes to be read. You can also see when you do this, that it shows you the correct GET path, which shows api there.
> 
> A lot of tutorials from even just one year ago don't have this as it's a recent change, so I hope I've helped some of you.

**Comment by thomas-cruz** [comment]
Getting the same problem. I have anything and everything published and allowed. Works fine in postman but I get 404 when called by axios.  
> Hi i think this work in pastman but not when i call the services from andriod app. i tried to call localhost:1337/api/auth/local/ from app and it does not return anything just 404. should I add cros ? Hi this issue was not related to cross i called get instead of post localhost:1337/api/auth/local/register. All good thanks

**Comment by Lauro235** [comment]
For me I've followed the process:

1. Save
2. Publish
3. Update Permissions
4. Test in Postman

In Localhost it works fine, but live, I'm not having any luck... Not sure what to try to be honest.

**Comment by Lauro235** [comment]
```plaintext
> 1. Drafts, quite common you can unset this in the Content-Type-Builder
```

The two options I see are

1. Draft and Publish
2. Internationalisation

Are you suggesting we uncheck the 'Draft and Publish' option?

**Comment by MusabDev** [comment]
> ve found what was the problem.

In my case, it was (non-draft). So, I just had to save it! 🎉
