### ISSUE TITLE
Ordering Content Type entries in the List view (preferably using drag and drop)

### ISSUE THREAD

**Issue by a14m** [strapi/strapi#3946]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
It would be really beneficial if there was a way to retain the order (using `order` column for example) of a collection and be able to update it via drag-and-drop on the collection view.

There are many cases when we want to have a certain order of items (regardless of insert order/id/filter/sort options provided in the view), and to be able to retrieve the data using the predefined order later (as seen in the collection view for example)

Using drag and drop would help as it's really tedious to go to a huge collection and pump the order column of each item (for a CMS user) or run a query on the database (for CMS power user)

most common use case, ordering an employee list on a company website (or add a new employee at a specific position)

**Comment by a14m** [comment]
Hey @Aurelsicoko, by "Collection view", I mean the table view (of a content-type) -as attached in the screenshot-

<img width="1309" alt="Screen Shot 2019-09-13 at 10 19 31" src="https://user-images.githubusercontent.com/347712/64847957-7c047b00-d610-11e9-8460-008ea379b18f.png">

So the use case is that we want to have a way to easily change the ordering of a list (list of employees, list of featured posts, etc etc, so that when we are using graphQL to query the data, we get the list ordered... and for the content people to be able to change the website structure without having to do a lot of manual work)

as you can see (in the screenshot attached), we use a `position` or `order` integer column but we have to manually go through the whole table/list to update each entry in case we needed to insert something in the middle or update the ordering...
it would be really good if there is something like a drag and drop to allow the ordering (with minimal effort for the content people) to work with...

Please let me know if I can do more help, I'm actually looking into implementing a new `order` data-type (basically an integer) on content-type builder to provide the functionality, as we really need this feature if we are to use Strapi in production (but I'll probably need more help with the implementation from the strapi team).

**Comment by a14m** [comment]
Would you be open to help approving our PR (when we finish it and merge it into some release)?
or work closely on the PR later?

**Comment by gregorskii** [comment]
This is a necessary feature, Contentful has it. I do see the PR is only for the bookshelf, is that the super type of the database ORM? Meaning would this work for Mongo as well?

**Comment by a14m** [comment]
The PR still work in progress... I pushed the branch... I still cannot get the table UI to work properly, but it should work with both...
I haven’t tested with mongodb yet... but I found a couple of issues with strapi postgress migrations
Please feel free to participate as well, I can give you access to the repo to also work on the same branch...
I know that it’s a crucial feature and only when started to migrate from an old wordpress instance, I found that it not there and (weirdly) was not requested before.

**Comment by gregorskii** [comment]
I think there was some comment on this that got deleted. What is needed to test this on a project? Is it a custom fork of strapi? How can I test it for mongo?

**Comment by lukemcd** [comment]
I think this request would be very helpful. Perhaps "sortable" could be an option when creating/editing a collection type. The sorting action in the list view would automatically generate the order number either into a reserved field name or a numeric field the user creates and associates with sorting.

**Comment by kjng** [comment]
Another vote for this feature. In the meantime, I am also using a column to sort the data to the order I want.

A reserved "list order" field/column in the database would work well.

**Comment by WebTerminator** [comment]
Any updates on this? I am just facing this issue and I will need to add an integer filed that I can manually update.

**Comment by ahrherrera** [comment]
Upvote for this feature. It's really needed when we need to sort records from a content-type.

In my case I need this because I need to custom reorder my app Products

**Comment by qudo-lucas** [comment]
Please add this ASAP

**Comment by qudo-lucas** [comment]
I thought I needed this but now I am not so sure. I just made an "Order" column in the CMS that is type Number and then the front end sorts on this property. If you want it to reflect the same order in the CMS, just click the column header and do a normal sort on column.

**Comment by a14m** [comment]
> just click the column header and do a normal sort on column
and how do you update the order column? when you have 50+ records that you need to update -not to mention pagination issues with updating a list (that might have unique constraint on the order column)-?

**Comment by MartinN3** [comment]
@qudo-lucas yes but consider this as written by @a14m above your reply.

``as you can see (in the screenshot attached), we use a position or order integer column but we have to manually go through the whole table/list to update each entry in case we needed to insert something in the middle or update the ordering...``

**Comment by xAgustin93** [comment]
How's this business going, do you know anything?

**Comment by choudharypravesh03** [comment]
Upvote for this feature. My usecase is that when I go to configuration view and drag and drop components, I want it to reflect in my graphql query. Any updates on this ?

**Comment by mizvyt** [comment]
I am building a help centre where the order of articles specified by the content manager matters. I second this approach and I think it should be higher on the priority list :-)

**Comment by petertenhoor** [comment]
+1

Enabling a sort setting for a content type which enables drag & drop sorting would be great.

**Comment by matthewthomsonnz** [comment]
+1 Googled "collection order strapi" and now I'm here and disappointed - very fundamental feature and should be high priority

**Comment by AugustGSP** [comment]
I currently use an order field in place of this feature, luckily my collection is only 5 or so items. This method would does not scale though, I couldn't imagine maintaining order fields for more than 20 items. This feature would be a nice addition.

**Comment by dneckel** [comment]
+1 This feature would be very welcome. For some use cases it is enough to use repeatable components which support ordering but if you need a dynamic zone you are currently out of luck as they are not supported as fields on components. As said before the manual approach with order field does not scale at all.

**Comment by TheRoadSouth** [comment]
Exploring strapi and really liking it so far. But +1 for this feature.

**Comment by jdortegar** [comment]
+1 We need this in our app for sure

**Comment by iezqrom** [comment]
Yes, upvote!

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/re-organize-documents-inside-a-collection/541/2

**Comment by globalsysgabriell** [comment]
+1 Upvote 👍

**Comment by cgonzalezsan** [comment]
+1 this is a really important feature. Nowadays, most of the CMSs have some kind of sorting implemented.

The best would be to have the order on the relation itself, by drag and drop. My use case is having a product which has and belongs to multiple product categories. I need to sort these products on the product category level, meaning that products will have different sorting depending on the product category. The only workaround I can think of, is to create a new JSON field in the product category which has an array of product IDs sorted in the manual way that I like. This is very hard to maintain for the client and user-unfriendly

**Comment by TomasSestak** [comment]
+1 very much needed

**Comment by konstaner** [comment]
+1 for this feature

**Comment by voncarcha** [comment]
+1 i need this too

**Comment by BlakeSearlSonocent** [comment]
+1 this would be great

**Comment by StevenMilne-Sonocent** [comment]
+1 this would be super useful to us! 😁

**Comment by kgrosvenor** [comment]
+ yep this would be amazing

**Comment by walt-er** [comment]
+1, extremely necessary. Asking clients/editors to maintain manual lists of references is just not acceptable IMO.

**Comment by alyrik** [comment]
+1. It would be really nice feature.

**Comment by jo-elbdev** [comment]
+1. I would love it!

**Comment by eltel** [comment]
Super +1, this is such an obviously needed feature - is there any news on this?

**Comment by Matb85** [comment]
+1 would appreciate

**Comment by rexolion** [comment]
+1 We need this!

**Comment by dmnkvd** [comment]
Yes please, +1!

**Comment by tylerforesthauser** [comment]
Throwing my +1 for this too. Thanks!

**Comment by amykapernick** [comment]
This would be great, currently setting up Strapi as my main internal CMS and this would be great for reordering items in my portfolio

**Comment by sercanvirlan** [comment]
+1 would be awesome!

**Comment by AndreasFaust** [comment]
+1 This is an important feature IMHO.

**Comment by icy-meteor** [comment]
+1 Need this at the earliest, dealbreaker! :)

**Comment by torquan** [comment]
+ 1 for order in content-types via drag & drop.

But seeing this thread keeps going since September 2019..

**Comment by cyrusliew1** [comment]
+1 This is an essential feature for every CMS.

**Comment by stopplay** [comment]
+1,  Has this been added yet? i can order my images in the gallery but not the project.

**Comment by robertosanval** [comment]
+1

**Comment by stopplay** [comment]
I don't think Strapi have read this, haven't seen a response.

**Comment by cristiansarov** [comment]
+1

**Comment by AdamSiekierski** [comment]
Bump. IMO it's a must-have

**Comment by cbauerswald** [comment]
+1 need this! Super necessary for non-technical people to be able to use it. Adding an "order field" way too cumbersome when wanting to reorder.

**Comment by jhaddock385** [comment]
This feature would be really helpful. Currently I'm having to work around this problem and it's not ideal for content producers.

**Comment by l1e** [comment]
Hello. Please, add this feature to strapi. It is very important.

**Comment by GomatoX** [comment]
As a simplier suggestion it could be another content-type for example **sorter**, which allows to add default sort field (or even multiple fields) and be managed directly from list using drag and drop. But there is an issue with drag and drop between different pages, so still it should be also possible to change order directly in edit view.

**Comment by jfahrni** [comment]
+1
Please add this Feature. Strapi is so cool, but that's a really missing feature!

**Comment by moritzruth** [comment]
How is this still marked as `severity: low`?

**Comment by soupette** [comment]
> Why is this still marked as `severity: low`?

This is how we "grade" the severity of an issue:

- `critical`: 
If the issue has a security impact or breaks core usage of the product.
In this case the technical team have to hotfix it right away!
- `high`:
If it breaks the basic use of the product.
It makes Strapi unusable.
- `medium`:
If it breaks the advanced use of the product
If there is a workaround but should be fix.
- `low`:
If the issue only affects a very niche base of users and an easily implemented workaround can solve.

As this issue is a feature request, its severity is `low`.

**Comment by moritzruth** [comment]
> [...] and an easily implemented workaround can solve.

So, what’s the workaround?

**Comment by gonzoandrea** [comment]
+1

**Comment by tourdefran** [comment]
+1

**Comment by stopplay** [comment]
@soupette  What's the workaround, please?

**Comment by soupette** [comment]
Currently the only workaround would be to customise the core files of both the front-end part and the back-end one.

**Comment by brnpimentel** [comment]
I workaround creating a numeric field which I insert manually the order of the content. 
Then at the frontend I order by this field. It's not the ideal but I can't think of any other way. 🤷🏻‍♂️

This issue severity should be greater because it is a basic feature for any cms.

**Comment by moritzruth** [comment]
My workaround is creating a singleton type with a dynamic zone and a single component, as components can be reordered.

**Comment by stopplay** [comment]
@brnpimentel likewise, but when you have 50 projects to order them becomes a bit of a job, a new project comes in to go on top and we then involve renumbering.

FYI Craft, has this feature @soupette , its a basic feature, even Wordpress has it.

**Comment by eltel** [comment]
I added a number field to all posts and filter by that field... It means
manually entering the number - but it works.
Hope that helps.

**Comment by osilviotti** [comment]
Not a solution obviously, but if you're going to go down the route of manually setting a number field use larger numbers (e.g. 100, 200, 300 instead of 1, 2, 3) so you can reorder things without having to change the number everywhere. If I wanted to move 300 between 100 and 200 I can now just set it to 250 instead of having to go into 200 and 300 and swapping the numbers

**Comment by krunal86** [comment]
+1 we want to give our marketing team a flexibility to add portfolio, menus, testimonials and they should be able to rearrange it. Currently it's tedious to update each row. Instead drag and drop is easier.

**Comment by jwayn** [comment]
+1

**Comment by pjexler** [comment]
+1

**Comment by rocketraman** [comment]
Agreed. I have to admit, I ran into this issue in the first 5 minutes of getting started with Strapi, with the very first collection I created: a set of FAQs. Clearly I want my FAQs to be ordered, and I was surprised to see I could not do that without creating my own custom ordering key (which is a pain to maintain).

**Comment by tourdefran** [comment]
My workardound was using a **Date field**, you can also use a **DateTime** to have more options if an entry has the same date.
In the front I retrieve the data sorting by date like this: ?_sort=SomeDateField:ASC
or DESC, depending on your case

**Comment by Gtosta96** [comment]
Upvote

**Comment by finex** [comment]
:+1: This feature is very interesting. I really hope it will be implemented. Thank you!

**Comment by smonkey72** [comment]
+1

**Comment by flkx** [comment]
pareil

**Comment by sarahknights** [comment]
+1

**Comment by aurelienbobenrieth** [comment]
I agree on the need of this feature.

My workaround was :
Let's say you want to sort a list of "**Item**" ; 
I created a _component_ called "**ItemSorting**" with a _relation_ to "**Item**"; 
Then I created a _Single Type_ called "**ItemSortingList**" in which I put my freshly created _component_.

I then added all my "**Item**"s in my _Single Type_ resulting in having a drag and drop ready list of "**Item**", allowing me to sort and display my "**Item**"s in quite a handy way.

**Comment by joshjung** [comment]
This is absolutely needed. I realize you all have other things on the list, but it is the *only* feature that is a turn off to the platform right now.

To clarify, for every single case on several sites that I have run into this, a simple "sorted" array on a JSON field in the parent collection would suffice. Or a table that is nothing but the index of an item, its relation in another field, and a JSON array in another field. We don't need anything other than an ordered list. Could even manage the sorting on the client as long as we have the array of sorted ids.

Or even the ability to specify another field on the parent object as the "sorting array" field. Then when it gets reordered in the Strapi Admin, you just update the "sorting array" to contain the ids of the items they were sorted into. We could manually do the sorting on the client based on the contents of this field. Obviously this would be an issue with a collection that has a relation with thousands of items, but it would still be an option in our hands and it would give us the ability to use an alternative if that need arises.

**Comment by jzsb** [comment]
This will be very great feature. Now I have to manually add each field. Makes me want to switch to another CMS.

**Comment by jzsb** [comment]
This would be a great feature. Debating whether I should move to a different CMS.

**Comment by lana1123** [comment]
+1 for this feature too

**Comment by migueltrias** [comment]
+1 for the sorting feature, much needed

**Comment by talalash** [comment]
+1 for this

**Comment by ivoevolution** [comment]
+1 it will be great

**Comment by bulteau** [comment]
+1 Thanks

**Comment by dimasxp** [comment]
+1

**Comment by sinkalex31** [comment]
+1

**Comment by kgrosvenor** [comment]
I though the same, but has no one tried using Dynamic Zones ?

**Comment by stopplay** [comment]
It is embarrassing, we advised a client to use this platform and have to now implement Craft free of charge, and boycott strapi. Absolutley embarresing such a basic feature.

**Comment by finex** [comment]
> It is embarrassing, we advised a client to use this platform and have to now implement Craft free of charge, and boycott strapi. Absolutley embarresing such a basic feature.

I don't agree with this comment. You should have tried and tested the product features you need *before* proposing it to your customers. Responsibility is yours in this case.

**Comment by kgrosvenor** [comment]
> It is embarrassing, we advised a client to use this platform and have to now implement Craft free of charge, and boycott strapi. Absolutley embarresing such a basic feature.

What is more embarressing is you didnt even look at the dynamic zones, its exactly what you need. Sorting can be done within the filters.

**Comment by drazik** [comment]
I worked around this by adding a repeatable component property in a single type. Hope it helps somebody!

**Comment by kazzkiq** [comment]
I'm a fresh new user and Strapi is such a piece of cake, but it makes me perplexed that such a "simple" CMS feature like this isn't fixed in 2 years now.

Just ran into this issue before giving a presentation to a client, and when he asks "what if I want to sort the content of this page?" I will have to say "well... see this 'order' field? You can keep updating all of those whenever you need to change one item position".

Not exactly a productive approach, right?

**Comment by MrAlevy** [comment]
Very sad actually... very sad...

**Comment by mickeyvanolst** [comment]
has anyone actually tried to add this feature by themselves? or added a pull request?

**Comment by gamanox** [comment]
Maybe the content type view editor could be useful to solve this, let me check if I could work on that

**Comment by filippodicostanzo** [comment]
+1

**Comment by sabahallah** [comment]
Just installed Strapi locally to test it after a deep research on headless CMS, and in the first 10 mins I discovered there's no option to order the collection items.
Now I need to create an order field then me and the client have to update all content manually. This is tedious.
+1 vote to implement this feature.

**Comment by eurolife** [comment]
+1 this would be a very useful feature, however I am going to try some of the workarounds suggested in the above comments.

**Comment by Matb85** [comment]
BTW are you going to implement this in v4?

**Comment by Brewd3v** [comment]
Please +1

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-v4-beta-is-live/11623/26

**Comment by benderillo** [comment]
> Please let me know if I can do more help, I'm actually looking into implementing a new order data-type (basically an integer) on content-type builder to provide the functionality, as we really need this feature if we are to use Strapi in production (but I'll probably need more help with the implementation from the strapi team).

@a14m have you had a chance to work on this? It's been two years since the request was submitted and I doubt this will be coming any time soon. So was wondering if you had eventually built your own solution which you could probably put on a public fork?

**Comment by yurydyatlov** [comment]
+1

**Comment by derrickmehaffy** [comment]
Locking this as the +1s aren't needed, thanks for the feedback but I believe we have enough information to make a decision at some point.

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/ordering-content-type-entries-in-the-list-view
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
