### ISSUE TITLE
Cannot get specific entry

### ISSUE THREAD

**Issue by angganegara** [strapi/strapi#395]
**Node.js version**: 8.8.1
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: MacOS Sierra 10.12.2

Fresh install of Strapi, following the docs quick start, everything working fine until **Get a specific entry (GET)** section. I have 2 entries on my Product table:

![screen shot 2017-12-20 at 12 33 13 am](https://user-images.githubusercontent.com/14870820/34167689-69cf841a-e51d-11e7-8170-d9cf8685d574.png)

When I tried to get the iphone, it shows me macbook pro instead. You can see below that the ID doesn't match.

![screen shot 2017-12-20 at 12 35 13 am](https://user-images.githubusercontent.com/14870820/34167803-bb494a60-e51d-11e7-9843-59df0ef09a24.png)

I did not touch any of the API configurations so I'm not sure what the problem is.

**Comment by goodpixels** [comment]
Same here, I have been getting this error too.

**Comment by lauriejim** [comment]
You are write, we are working on it

**Comment by hadihallak** [comment]
also, why is it returning two ID fields  (id and_id) with the request?
is it a bug or am I missing something? because I've noticed this issue when I worked on strapi last night.

**Comment by lauriejim** [comment]
You receive data of your document object. So you have `_id` and `__v` keys.

**Comment by lucaperret** [comment]
I've generated a new app to see the differences of /api/* files with mine, and there is a difference in the fetch method of services/_model_.js.
To correct this bug, you should update like this commit https://github.com/strapi/strapi/commit/519239c35c01135f0c5c0222d10f5309a190dd60.
@Aurelsicoko maybe could be could to add this in the migration guide ?
