### ISSUE TITLE
SQLite is not an option in the admin panel

### ISSUE THREAD

**Issue by lifehome** [strapi/strapi#3951]
**Describe the bug**
SQLite option is missing in the Database connectivity configuration.

**Steps to reproduce the behavior**
1. Go to 'Configuration' > 'Database'
2. Modify or add a new database connection
3. Check out the client connectivity options
4. **There is no SQLite.**

**Expected behavior**
I can choose SQLite and enter the path. If the path field is empty, it should have some default failover.

**Screenshots**
<img width="1003" alt="螢幕截圖 2019-09-11 上午1 17 23" src="https://user-images.githubusercontent.com/1886237/64635363-1490d480-d432-11e9-8b03-cfb0594fffca.png">

**System**
- Node.js version: v12.10.0
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.16.1
- Database: SQLite via `--quickstart`
- Operating system: macOS Mojave

**Additional context**
I think it is related to #2562.

**Comment by ceefour** [comment]
**Additional bug**

Even when "choosing" Mongo (the default there) and then setting the fields, the generated file will still use "sqlite3" instead.

![image](https://user-images.githubusercontent.com/24123/64916953-6334ca80-d7b4-11e9-8409-587f96432859.png)

Resulting `config\environments\development\database.json`:

```json
  "connections": {
    "default": {
      "settings": {
        "client": "sqlite3",
        "filename": ".tmp/data.db",
        "enabled": true,
        "host": "localhost",
        "port": 27017,
        "database": "appstudio_dev",
        "username": "",
        "password": ""
      },
      "options": {
        "useNullAsDefault": true
      }
    },
```

**Comment by AJRdev** [comment]
@lauriejim I will take on the first issue about SQLite not being displayed in the configuration form ✋

**Comment by AJRdev** [comment]
@soupette I just noticed your PR (https://github.com/strapi/strapi/pull/3967) about removing the settings-manager plugin. 
Do you think this issue will be fixed in by your PR directly or should I checkout from your branch to fix it ?

**Comment by derrickmehaffy** [comment]
Marking this as closed as the settings-manager is being removed.
