### ISSUE TITLE
Scaffolding APIs on plugin seems broken

### ISSUE THREAD

**Issue by EloB** [strapi/strapi#3965]
**Describe the bug**
A simple scaffolding and creating a api on a plugin seems broken.

**Steps to reproduce the behavior**
```bash
$ strapi new myapp
$ cd myapp/

$ strapi generate:plugin myplugin
$ strapi generate:api -p myplugin mymodel first:string second:string

$ yarn develop

$ strapi develop
[2019-09-11T14:52:25.574Z] debug ⛔️ Server wasn't able to start properly.
[2019-09-11T14:52:25.579Z] error TypeError: Cannot read property 'bind' of undefined
    at routerChecker (/Users/ollebroms/Documents/testing/myapp/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:33:43)
    at /Users/ollebroms/Documents/testing/myapp/node_modules/strapi/lib/middlewares/router/utils/composeEndpoint.js:16:34
    at _.forEach.value (/Users/ollebroms/Documents/testing/myapp/node_modules/strapi/lib/middlewares/router/index.js:63:15)
    at /Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:2990:24)
    at /Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:9342:14)
    at _.forEach (/Users/ollebroms/Documents/testing/myapp/node_modules/strapi/lib/middlewares/router/index.js:60:13)
    at /Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:2990:24)
    at /Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/Users/ollebroms/Documents/testing/myapp/node_modules/lodash/lodash.js:9342:14)
    at Object.initialize (/Users/ollebroms/Documents/testing/myapp/node_modules/strapi/lib/middlewares/router/index.js:49:11)
    at Promise.resolve.then (/Users/ollebroms/Documents/testing/myapp/node_modules/strapi/lib/middlewares/index.js:54:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
```

**Expected behavior**
I except the application to start and it should show the model in the sidebar and I don't except that I need to provide any controller actions.

This will work if it's not inside a plugin and I don't have to provide controller actions.
```bash
$ strapi new myapp
$ cd myapp/

$ strapi generate:api mymodel first:string second:string

$ yarn develop
```
It will automatically show up in the sidebar:
![image](https://user-images.githubusercontent.com/476567/64710298-fd94c580-d4b7-11e9-9fb5-73553965eee6.png)

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.1
- Database: any
- Operating system: any

**Comment by EloB** [comment]
If this will take awhile to fix in core is there a interim solution for it? If so can we discuss how to solve it?
https://github.com/EloB/strapi-test/pull/1

**Comment by FrancisVarga** [comment]
Just try over the content manager not over the CLI

**Comment by alexandrebodin** [comment]
@EloB 

The -p option made sense in old projects when we generated controllers and services full of code. Now the code in generated by the framework but only for user models. When it comes to plugins we have no clue to whatt the intent is so it's hard to generate code for them. 

If you really wish to do that you can go to https://github.com/strapi/strapi/tree/master/packages/strapi/lib/core-api and look the codebase that corresponds to tthe controllers and services generated by the framework when creating a new model. Hope this helps.

**Comment by alexandrebodin** [comment]
@EloB Thanks for you idea. For now we don't plan on doing something like that because we plan on make new apis for it in the future.

This could look like this
```js
//controller.js
const { createController } = requrie('strapi/factories');

module.exports = createController({
  // customCode
})
```

There are two cases in plugin development: 
- Add models to reuse without specific behaviours (your usecase)
- Add new apis with a totally free form

We prefer avoiding adding overhead for the custom plugins as they are the majority for now.
 The only solution I can propose that would be in line with what we are planning is to template files with the code.

**Comment by EloB** [comment]
Just tried this and this isn't enough because `createController` and `createService` need to pass `plugin` and it's not possible at the moment. You need to write a lot of code to start doing a plugin at the moment xD

**Comment by EloB** [comment]
```js
// The implementation right now
module.exports = ({ model, strapi }) => {
  return {
    /**
     * expose some utils so the end users can use them
     */
    uploadFiles,
    /**
     * Promise to fetch all records
     *
     * @return {Promise}
     */
    find(params, populate) {
      return strapi.query(model).find(params, populate);
    },

// Preferred solution
module.exports = ({ model, plugin, strapi }) => {
  return {
    /**
     * expose some utils so the end users can use them
     */
    uploadFiles,
    /**
     * Promise to fetch all records
     *
     * @return {Promise}
     */
    find(params, populate) {
      return strapi.query(model, plugin).find(params, populate);
    },
```

**Comment by lauriejim** [comment]
Hello! I close this issue because it already exists here - https://github.com/strapi/strapi/issues/3889
