### ISSUE TITLE
Issues with relational fields and arrays

### ISSUE THREAD

**Issue by TomFevrier** [strapi/strapi#3966]
Hello there! I am building my portfolio website using Gatsby and Strapi, but I seem to have issues with relational fields and arrays.

For each project I have an array of "related projects" that I want to display, but I cannot access composite fields (images, or other relational fields) with GraphQL. Same with arrays of images, composite fields are not accessible.

For instance, in the following query the `publisher` field only gives me the id of the publisher, not the whole type (which has a name and a slug):
```javascript
query ProjectTemplate($id: String!) {
        strapiProject(id: { eq: $id }) {
			title
			related {
				id
				slug
				title
				date
				publisher
			}
        }
}
```

So my question is: is it possible to access those, maybe by running a secondary GraphQL query to access data using an id? I tried to do that (with the `useStaticQuery` function), but I am quite new to GraphQL and:
- I don't know how to include a variable in a GraphQL query (to look for data associated with a given id in that case): `strapiProject(id: { eq: ${node.id} })` doesn't work
- if I try with a hardcoded id (see below), the query seems to "replace" the query getting the content of my page

```javascript
{data.strapiProject.related && (
	<ul className={styles.grid}>
		{data.strapiProject.related.map(node => {
			const related = useStaticQuery(graphql`
				query Relation {
					strapiProject(id: { eq: "Project_3" }) {
						id
						slug
						title
						date
						featured_image {
							childImageSharp {
								fluid(maxWidth: 600) {
									...GatsbyImageSharpFluid
								}
							}
						}
						publisher {
							name
						}
					}
				}
			`);
			return (
				<li key={node.id} className={styles.item}>
					<ProjectPreview {...related} />
				</li>
			);
		})}
	</ul>
)}
```

### System
- **Node.js version:** 10.16.3
- **NPM version:** 6.9.0
- **Strapi version:** 3.0.0-beta.15
- **Database:** SQLite (development)
- **Operating system:** Ubuntu 18.04

Can anyone help me with this? Thank you very much, and please let me know if you need more details.

**Comment by lauriejim** [comment]
Hello! Can you please follow [the issue template](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

You can find a [Gatsby video 🎙](https://www.twitch.tv/videos/476766670) that uses Gatsby with images.
I'm sure it will help you to use Gatsby + Strapi.

**Comment by TomFevrier** [comment]
> Hello! Can you please follow [the issue template](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> You can find a [Gatsby video studio_microphone](https://www.twitch.tv/videos/476766670) that uses Gatsby with images.
> I'm sure it will help you to use Gatsby + Strapi.
I added my system specs, though I don't think these relate to my problem. The video you shared is not helpful neither, my issue is with Strapi and GraphQL, not Gastby...

**Comment by lauriejim** [comment]
Can you share with me your project model, please?
