### ISSUE TITLE
Content relations are showing IDs instead of names in the Edit View.

### ISSUE THREAD

**Issue by heyomi** [strapi/strapi#3968]
**Informations**

- **Node.js version**: v10.16.3
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-beta.16.2
- **Database**: MongoDB
- **Operating system**: Windows 10

**What is the current behavior?**

I updated from 3.0.0-beta.15 to 3.0.0-beta.16.2 with relational fields on my main content type.

The Edit View is now showing the content IDs instead of the name. Any ideas why this is happening?

![image](https://user-images.githubusercontent.com/1944368/64726704-1c528680-d4cf-11e9-9d89-cc1f1c0cfc36.png)

**Steps to reproduce the problem**

Use strapi 3.0.0-beta.15. Set up content types with one-to-many & one to one relationships. Migrate to 3.0.0-beta.16.

**Comment by derrickmehaffy** [comment]
@heyomi 

![image](https://user-images.githubusercontent.com/8593673/64727356-89452c80-d48d-11e9-8477-2bf08648ed09.png)

Marking as closed as there is a new feature in beta.16/beta.16.1 that allows users to change this.

**Comment by victorkane** [comment]
@derrickmehaffy yes, there is a feature to modify entry from id to, say, name. But you have to do it with each and every _use_ in each and every content type and in each and every relation. It's crazy, almost (but of course, strapi is still the best :)) a deal breaker for usability. There should be some way to avoid this madness. For every strapi app you make, you have to go through the whole thing for every content type and every relation, and sometimes it's quite confusing, so, twice. I vote this issue be left open until improved usability is achieved. Strapi isn't a prototype, a lot of us are actually planning on using it.

**Comment by derrickmehaffy** [comment]
@victorkane I don't disagree with you trust me. I have suggested many many many times to the Strapi team to allow for forceful file overrides in the model settings. However in your case I take it you are using Mongo.

@soupette @Aurelsicoko I'm reopening this, can we fix this so mongo users will default to first **non-ID** string for relation values? That should at least fix most of these.

**Comment by Aurelsicoko** [comment]
@derrickmehaffy I think we could use the "Entry Title" of each Content-Type by default in each relational field, then let the user customises the value and if there is no string/text field availalble, use the ID as the latest option ;)

**Comment by cam424** [comment]
If you ran into this again like I did, the ID still appears to be displaying with the relation is configured first on the model before other fields and wouldn't resolve when changing the Entry title dropdown. I resolved by deleting the relation, saving and recreating, ensuring that the Entry title was set to the field I wanted. Worked like a charm.
