### ISSUE TITLE
Not possible to save a change on the layout of a repeatable group in the content manager

### ISSUE THREAD

**Issue by rmaroun** [strapi/strapi#3969]
**Describe the bug**

**Steps to reproduce the behavior**
1. Create a repeatable group
2. go to content manager and click on the repeatable group you just created
3. Change the entry title or add a placeholder to one of the group's fields then the save button will appear. Click on the save button to save the changes]
4. you get an error message 'error has occured' (no log messages)

**Expected behavior**
After editing the layout of a repeatable group in the content manager, I should be able to save it without error messages

**Screenshots**

![image](https://user-images.githubusercontent.com/4890827/64731275-28474400-d4e1-11e9-9430-9da100cd5fc2.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10
- NPM version:
- Strapi version: 3.0.0-beta.16.2
- Database: MongoDB 4.0.6
- Operating system: OSX

**Additional context**

**Comment by lauriejim** [comment]
Hello @rmaroun ! Thank you for reporting this issue.

By checking the `network` I can see the errors.

Here are the messages:
- `settings.mainField must be one of the following values: field1, field2, createdAt, updatedAt`
- `settings.defaultSortBy must be one of the following values: field1, field2, createdAt, updatedAt`
