### ISSUE TITLE
cb is not a function error

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#3971]
**Describe the bug**
`cb is not a function` gets thrown during `strapi develop` after upgrading to beta 16.

[2019-09-12T01:53:25.200Z] debug ⛔️ Server wasn't able to start properly.
[2019-09-12T01:53:25.202Z] error TypeError: cb is not a function
at module.exports.cb (/usr/src/api/gecms-app/config/functions/bootstrap.js:12:3)
at execBootstrap (/usr/src/api/gecms-app/node_modules/strapi/lib/Strapi.js:381:15)
at Strapi.runBootstrapFunctions (/usr/src/api/gecms-app/node_modules/strapi/lib/Strapi.js:399:12)
error Command failed with exit code 1.

**Steps to reproduce the behavior**
1. Update to Beta 16
2. Run `strapi develop` on existing application
3. See terminal output for error
5. Downgrade to 15 and it works again

**Expected behavior**
I expected the application to build.

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Yarn version: 1.17.3
- Strapi version: Beta 16
- Database: MySQL 8
- Operating system: CentOS

**Additional context**
Building in Docker with Docker Compose linking to a MySQL DB.

**Comment by wanjas** [comment]
Here is the migration guide it should solve this issue for you as it did for me 
[https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html)

**Comment by amartincolby** [comment]
Sigh. I searched like crazy, and there it was, in the docs, all along. Thank you muchly.

**Comment by tcvmdev** [comment]
Hi! @amartincolby @wanjas how did you end up implementing the callback function in bootstrap.js? 

I'm upgrading from strapi@alpha where bootstrap.js was just:

'use strict';
module.exports = cb => {
  cb();
};

and so I got the same error that @amartincolby received. 

Now, trying to implement the "Async", "Promise", or "Sync" in the migration Docs, it expects you to write some function here. What exactly should you be doing here without any other functions in bootstrap.js?

Thank y'all for your help!

**Comment by vvenance** [comment]
@tcvmdev looks like this fix isn't working for 3.0.0-next.24 version of strapi.
Any docs I haven't looked at ?

**Comment by LucasMatuszewski** [comment]
> @tcvmdev looks like this fix isn't working for 3.0.0-next.24 version of strapi.
> Any docs I haven't looked at ?

As far as I know "next" versions are not for normal development. They are for Strapi team and contributors, to develope new features.

The latest version of strapi is beta.17.4 - please use this migration guide if you have v16 now:
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.16-to-beta.17.4.html

or this one if you have some older beta version (I was migrating from v13 and it works fine):
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html

Good luck! :)

**Comment by animatedcreativity** [comment]
> The latest version of strapi is beta.17.4 - please use this migration guide if you have v16 now:
> https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.16-to-beta.17.4.html
> 
> or this one if you have some older beta version (I was migrating from v13 and it works fine):
> https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html

Thanks for the help!
I had beta.15 and those guided really helped me to upgrade to beta.17.5

> For anyone who wants a basic fix, just use
> 
> ```js
> module.exports = () => {};
> ```
> 
> for your bootstrap.js!

You must do this before doing `npm run build`.
