### ISSUE TITLE
strapi commands not found/deprecation issues, running node v10.x.x and npm v6.x.x

### ISSUE THREAD

**Issue by aturtle35** [strapi/strapi#3972]
**Describe the bug**

_the strapi CLI does not appear to be working correctly._

FYI: I am a relatively novice coder, but am really excited to try strapi. I am familiar with running commands in the terminal and working with CLIs...I have run wordpress, react.js, next.js, and express.js locally for various projects and have not had any issues with the command line/node.js...

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.2
- Database: I tried...SQLite, MongoDB, PostGres, and MySql
- Operating system: macOS Mojave, Version 10.14.6

**_NOTE:_ I completely uninstalled/reinstalled node.js and restarted my computer to ensure that there was not any node/npm version mixing or system issues - still received the same errors**

**Steps to reproduce the behavior**
1. installed latest strapi with 'npm install strapi@beta -g'
2. ran 'strapi new _test_ --quickstart'
3. command line returned this error: _'-bash: strapi: command not found'_
4. ran all other strapi commands specified in https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-new, command line returned this error for all commands, _'-bash: strapi: command not found'_
5. ran 'npx  strapi _test_ (--quickstart **and** manual)', which works but ends in significant errors (see screenshots below). 
6. when running start/dev with project, '_test_'(npx configuration only), strapi studio does not synchronize properly (--quickstart) and the strapi server does not configure to allow for an admin account setup (manual setup)

**Expected behavior**
1. install latest strapi with 'npm install strapi@beta -g'
2. run command 'strapi new <my project> --quickstart'
3. successful return with no deprecations and errors; proper server connection and  synchronization with strapi studio

**Screenshots**
![Screen Shot 2019-09-11 at 11 41 09 PM](https://user-images.githubusercontent.com/55221475/64752590-2a63cf80-d4ee-11e9-93f9-c183be364ed7.png)

![Screen Shot 2019-09-11 at 11 27 07 PM](https://user-images.githubusercontent.com/55221475/64752593-2c2d9300-d4ee-11e9-9022-ea07862fefdb.png)

![Screen Shot 2019-09-11 at 11 27 34 PM](https://user-images.githubusercontent.com/55221475/64752597-2e8fed00-d4ee-11e9-8b6e-e36f8a1c08b9.png)

**Additional context**
when installing strapi via command 'npm install strapi@beta -g', i received a notice that boom(@hapi/boom) and hoek(@hapi/hoek) versions were out of date...boom(@hapi/boom) is running on 7.3.0(latest is 7.4.3); I did not see what version hoek is running on and could not find hoek listed as a dependency...could this contribute to the issue?

_**I am sure it is something small (read stupid) that I am overlooking or not doing, but any guidance would be much appreciated!!**_

**Comment by izzuddinnatsir** [comment]
You can use 
```
npx create-strapi-app folder-name --quickstart 
```

**Comment by izzuddinnatsir** [comment]
Then start strapi in development mode with 
```
npm run develop
```
From inside your strapi folder

**Comment by lauriejim** [comment]
Hello @aturtle35 !

I suggest you follow this [getting started 📚](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project) that is a good way to start with strapi.

**Note** when you ran `npx strapi ...` (5) you forgot to specify `@beta`. Should be `npx strapi@beta new my-project --quickstart`
