### ISSUE TITLE
URIError appeared after entering "%" symbol into the Search input field 

### ISSUE THREAD

**Issue by PinchukABAG** [strapi/strapi#3974]
**Describe the bug**
The Error appeared after entering "%" symbol into the Search input field

**Steps to reproduce the behavior**
1. Go to Content Types 
2. Fill in the Search input field by % symbol 
3. See error

**Expected behavior**
A searched entry that contains % has found

**Screenshots**

![image](https://user-images.githubusercontent.com/51051832/64780368-76e7f300-d560-11e9-8bf5-f22695cc5dc4.png)

**System**
- Strapi version: Strapi v3.0.0-beta.14
- Operating system: Windows 10
- Database: MongoDB v. 4.0.11
- Browser: Google Chrome  Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by lauriejim** [comment]
Can you please specify the database you use, please.

**Comment by lauriejim** [comment]
I tested with SQLite database and the issue happen.
@PinchukABAG Thank you for reporting this issue.
I think it's because special characters are not escaped in the request. 
@soupette will be able to confirm or not.

**Comment by PinchukABAG** [comment]
> Can you please specify the database you use, please.

Done! 
The bug was reproduced on the MongoDB. 

@lauriejim always glad to help)
