### ISSUE TITLE
Content type builder not showing up on strapi develop on latest strapi

### ISSUE THREAD

**Issue by ghost** [strapi/strapi#3975]
**Describe the bug**
Upgraded to v3.0.0-beta.16.2 and on running _strapi develop_ and opening the content type builder in admin panel shows 'Reload feature is required for this plugin.'

**Steps to reproduce the behavior**
1. Upgrade to v3.0.0-beta.16.2
2. Click on content type builder
3. You might find the message

**Expected behavior**
Previously the builder used to open on beta.15

**Screenshots**
Strapi develop:
![Screenshot 2019-09-12 at 5 42 34 PM](https://user-images.githubusercontent.com/37217713/64783173-bcb6b280-d584-11e9-8f22-fd14189ffd2d.png)

error:
![Screenshot 2019-09-12 at 5 43 01 PM](https://user-images.githubusercontent.com/37217713/64783206-d952ea80-d584-11e9-8016-12412c78afed.png)

**System**
- Node.js version: v10.16.2
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.16.2
- Database: MongoDB
- Operating system: MacOS Mojave

**Comment by liming** [comment]
Hi, how did you solve this problem? I'm stuck here.

**Comment by lauriejim** [comment]
If you updated your application version, dont forget to rebuild your admin panel.
Run `yarn build` then try to restart your server with `strapi develop`

**Comment by Mario-Boss** [comment]
I have the same problem as has been described above.. 
I have to mention, that removing 'build' folder and using 'strapi develop' command doesn't work.. the same with NPM equivalents;
My 
strapi version: 3.0.0-beta.17.8 
node version: 10.16.3
mongo version 4.2.2
no errors for Mongo, Nginx
any clue..?

**Comment by lauriejim** [comment]
Can you try to also remove the `.cache` folder and make sure all you npm dependencies are with the right version.
