### ISSUE TITLE
Minimum and Maximum values not functioning on generated API

### ISSUE THREAD

**Issue by CausticD** [strapi/strapi#3978]
Describe the bug
When adding or editing a String field of a content type, the minimum and maximum values seem to be ignored.

Steps to reproduce the behavior

Go to Content Type Builder
Click on an existing Content Type with at least one String type field
Click the edit icon on a Number field
Go to Advanced
Check minimum value
Enter a minimum value of 10
Check maximum value
Enter a maximum value of 12

Expected behavior
POSTing to the end point with strings that are too short or too long should return 500 error.

System

Node.js version: v10.16.3
NPM version: 6.9.0
Strapi version: 3.0.0-beta.16.2
Database: default
Operating system: Linux Container

Notes

The functionality works for ints, but not strings at all via REST POST. It doesn't work for strings no matter which combination of minimum and maximum I set. However, it does seem to work for Strings in the web UI if you select 'Create an entry'.

**Comment by lauriejim** [comment]
Closing and liked to this global issue https://github.com/strapi/strapi/issues/4324
