### ISSUE TITLE
String fields should auto-trim leading and trailing blank spaces

### ISSUE THREAD

**Issue by jasongitmail** [strapi/strapi#3983]
**Describe the bug**

(I consider this a bug because it deviates from expected UX.)

When saving a string field, Strapi should automatically trim leading and trailing spaces before storing in the database. This ensures data quality for these fields, and prevents issues such as a user copying and pasting a string into the input and accidentally & unknowingly (because it's not visible) saving trailing white spaces.

(Related & untested--and I can create another issue if desired--but enumeration field options should also have their leading/trailing spaces trimmed off of all options when setting up allowed values. That's not so much of a data quality issue though, but would be a best practice.)

**Steps to reproduce the behavior**

1. In Content Type Builder, create a string field 
<img width="704" alt="string field" src="https://user-images.githubusercontent.com/50032291/64833758-a9c8d000-d5ce-11e9-887f-829ba810e69e.png">
2. In Strapi, create a new entry, enter data for this field including leading and trailing spaces, & save it.
<img width="366" alt="data entry" src="https://user-images.githubusercontent.com/50032291/64833786-c6fd9e80-d5ce-11e9-8838-bf5354c06ec4.png">
3. Check the DB to see actual string stored.
<img width="121" alt="data in DB" src="https://user-images.githubusercontent.com/50032291/64833881-16dc6580-d5cf-11e9-97e0-e3bce0c5a940.png">

**Expected behavior**

The string should be saved in the DB without any leading or trailing spaces

**Actual behavior**

The string is stored in the DB with leading and trailing spaces.

**System**
- Node.js version: **User did not provide**
- NPM version: **User did not provide**
- Strapi version: beta.16
- Database: SQLite
- Operating system: **User did not provide**

**Edited by:** @derrickmehaffy

**Comment by derrickmehaffy** [comment]
@jasongitmail if possible in the future please make sure you include the `System` information when creating bug reports as this helps narrow down issues during troubleshooting.

**Comment by lauriejim** [comment]
Hello, thank you for reporting this. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by soupette** [comment]
@jasongitmail I have been putting some thoughts into this issue and here's my point of view: this feature should not be added in the `content-manager` as the generated APIs won't have the same behaviour, if we start to auto trim the text fields in this plugin the users should expect to have the same behaviour when they enter some data in their client application. Furthermore, with the customisation system you can easily add it to your application by modifying the corresponding file (it's should be located in `content-manager/admin/src/containers/EditViewDataManager`). Finally such behaviour may not please all of our users.

Therefore I am closing this issue.

**cc/** @alexandrebodin @lauriejim

**Comment by derrickmehaffy** [comment]
Well said @soupette locking this issue.
