### ISSUE TITLE
What does it mean by saying strapi is a headless CMS?

### ISSUE THREAD

**Issue by zhaoyao91** [strapi/strapi#3991]
I am new to strapi. After looking through some docs, I feel it is like a modern `sails.js`. Even without the admin panel, strapi is high level and powerful to create web backends.

I am confused of its intrudoction `headless CMS`. I found in the 1.x.x documentation, it said `Strapi is an open-source Node.js rich framework for building applications and services`. 

So by switching from service framework to headless CMS, is the target, mission or intention changed or somewhat? 

Some other things also declare them to be CMS such as ghost and wordpress, but I have some feeling, this and that are different, but I can't tell it clearly.

**Comment by derrickmehaffy** [comment]
@zhaoyao91 It means there is no public frontend, allowing users to build or use whatever frontend you want and using REST/GraphQL based APIs from Strapi to store and fetch the content. 

For now I'm marking this issue as closed as it doesn't follow one of the required templates.

**Comment by zhaoyao91** [comment]
thanks for explain :)
