### ISSUE TITLE
Impossible to create model with a Date that is set to unix timestamp 0

### ISSUE THREAD

**Issue by EloB** [strapi/strapi#3993]
**Describe the bug**
It's impossible to create model with a Date that is set to unix timestamp 0.

**Steps to reproduce the behavior**
1. Create content type.
2. Add a Date field. Set default value to 1970, 1 Januari, 00:00:00.
3. Try to create a model of that content type you created.

**Screenshots**
![image](https://user-images.githubusercontent.com/476567/64903772-2935cc80-d6bf-11e9-8168-ec04ff4bad38.png)

![image](https://user-images.githubusercontent.com/476567/64903769-1a4f1a00-d6bf-11e9-8522-cacd502d3b4d.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.3
- Database: postgres
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@EloB can you please include the versions (minus windows 10)

```
Node.js version: latest stable
NPM version: latest stable
Strapi version: latest beta
Database: postgres
Operating system: Windows 10
```

These are needed in order to properly troubleshoot your issue. Once you have updated your post with these versions I can reopen it.

**Comment by EloB** [comment]
Updated but the problem is probably a if statement that uses unix timestamp....

**Comment by derrickmehaffy** [comment]
I understand @EloB 😃 just trying to keep the issues clean, clear, and easy to follow. 😉

**Comment by SusilRamarao** [comment]
Hi @EloB i tried to replicate the issue, when i tried to set the default date as 1970 January 1, until here it is taking input, but after that when i enter time as 00:00:00, it is automatically changing to 1960 31 december 18:30. Not able to modify date. Please let me know if i am replicating the issue correctly. Thanks.

![dateissue](https://user-images.githubusercontent.com/8603210/67083294-88a06400-f1b8-11e9-90f5-1835e1b2b03f.gif)

**Comment by EloB** [comment]
@SusilRamarao I don't remember... :(

**Comment by petersg83** [comment]
Hi,
Thanks for this issue report.
I was able to reproduce it with version `Strapi v3.0.0-beta.16.1` but not with `Strapi v3.0.0-beta.16.3` and neither with the latest version `Strapi v3.0.0-beta.19.3`.
Please reopen this issue if you can reproduce the error with the latest version of Strapi.
