### ISSUE TITLE
Strapi + Graphql Real time query building through the Authenticated module

### ISSUE THREAD

**Issue by sajumani** [strapi/strapi#3994]
Hi,

**Describe the bug**
Am trying to create Field level permission, with strapi policies + Graphql

**Expected behavior**
We should able to restrict, Field level permission

**Screenshots**
Probably, it's our expectation 

**System**
- Node.js version: v12
- NPM version: v6
- Strapi version: 3 Beta
- Database: MongoDB
- Operating system: Windows

**Additional context**
Could you suggest best solution for field level permission ?

Am looking for a field level permission in strapi endponits.

In your other discussion i found "**Graphql**" but Graphql works for public role endpoints only.
I write polices to find authenticated fields based on role but Am trying to write Graphql query inside inside policies

Is this right idea ? Or any alternative solutions ?

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by sajumani** [comment]
@derrickmehaffy Could you reopen the issue ?

**Comment by derrickmehaffy** [comment]
Reopening @sajumani Thank you for following the template

**Comment by lauriejim** [comment]
Hello! Sorry but there is no solution for that in Strapi via GraphQL.
You will have to deal manually with policies to override the response data.
