### ISSUE TITLE
Not able to deep populate Mongoose

### ISSUE THREAD

**Issue by heyomi** [strapi/strapi#3995]
Hi.

**System**
Node.js version: v10.16.3
NPM version: v6.9.0
Strapi version: 3.0.0-beta.16.3
Database: MongoDB
Operating system: Windows

**Question**
How do I extend the back-end queries to get nested objects? 
Is there a Strapi guide?

![image](https://user-images.githubusercontent.com/1944368/64911410-734b9c00-d719-11e9-9da5-408a0ff65640.png)

**Comment by lauriejim** [comment]
Hello! Thank you for this message.
Normally you have to update your controller function like this:
```
module.exports = {
  find(ctx) {
    if (ctx.query._q) {
      return strapi.services.article.search(ctx.query);
    }
    return strapi.services.article.find(ctx.query, ['messages', 'messages.article']);
  },
};
```
The second argument is the data you want to populate.

But I tried and I have an issue to populate the data.
I transform this question as an issue.

**Comment by lauriejim** [comment]
Hello @heyomi !

According to this [Populating across multiple levels](https://mongoosejs.com/docs/populate.html#deep-populate) documentation from Mongoose.
You can send this Object to Deep Populate your data.

In your example.

```
module.exports = {
  find(ctx) {
    if (ctx.query._q) {
      return strapi.services.article.search(ctx.query);
    }
    return strapi.services.article.find(ctx.query, {
      path: 'messages',
      populate: {
        path: 'article'
      }
    });
  },
};
```

**Comment by coderdix** [comment]
> Hello @heyomi !
> 
> According to this [Populating across multiple levels](https://mongoosejs.com/docs/populate.html#deep-populate) documentation from Mongoose.
> You can send this Object to Deep Populate your data.
> 
> In your example.
> 
> ```
> module.exports = {
>   find(ctx) {
>     if (ctx.query._q) {
>       return strapi.services.article.search(ctx.query);
>     }
>     return strapi.services.article.find(ctx.query, {
>       path: 'messages',
>       populate: {
>         path: 'article'
>       }
>     });
>   },
> };
> ```

Could you do this with 2 fields you'd want to populate from the same path. Like I have a path that needs to populate 2 seperate fields but only gives the last one I declare. Mongoose says "If you call populate() multiple times with the same path, only the last one will take effect."

**Comment by pmacom** [comment]
I know this issue is old, but I'm sure someone might want this answer to @coderdix's question in the future. It seems like you can pass it an array of { path, populate } objects.

```
return strapi.services.article.find(ctx.query, [
  { path: 'messages', populate: { path: 'article' }},
  { path: 'messages', populate: { path: 'language' }},
]);
```
