### ISSUE TITLE
[bug] Renaming property in content type does not rename/recreate indexes properly

### ISSUE THREAD

**Issue by ceefour** [strapi/strapi#4002]
**Describe the bug**
Renaming property in content type does not rename/recreate indexes properly

**Steps to reproduce the behavior**
1. Use MongoDB
1. Create content type using Content Type Builder
2. Create property **with (unique) index**, e.g. `name`
3. Save
4. Rename property to `title`
5. Index `name_1` still exists (but `index_1` also created)

**Expected behavior**
Index `name_1` dropped, then new index `title_1` with new property/field.

**System**
- Node.js version: 10.16.3
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.16.3
- Database: SQLite
- Operating system: Windows 10 1903

**Comment by lauriejim** [comment]
Hello @ceefour !
This case is voluntary from our side.
Strapi **never** delete stuff from your database.
You will find the same is you delete a content type, we do not delete the data.
In SQL if you delete a column we do not delete the column in your database.
There are others issues that talk about this topic.
The issue we can have is about removing `unique` from a field. But an issue already exist about this.
In any case, thank you for reaching our this point.
