### ISSUE TITLE
Groups with related fields have undefined values in Edit View

### ISSUE THREAD

**Issue by heyomi** [strapi/strapi#4004]
**Describe the bug**
In Repeatable groups with relation fields, after selecting a value for the relation field and saving the content type that encapsulates the repeatable group then the data is persisted but the relation field selected is not displayed in the Admin UI

**Steps to reproduce the behavior**
1. Create two new Content Types (contentA & contentB) with one or more text fields.
2. Create a new Group (groupA) with a text field and a related field linked to contentB.
3. Update contentA by adding a new Group which refers to groupA.
4. Add content, groups, etc. populating all fields.
5. Edit any contentA content, scroll to the Group (groupA)
6. The groupA entries will have an **undefined** value selected in the dropdown list for contentB
7. The **details** link will lead to a 404 page.
http://localhost:1337/_/plugins/content-manager/groupB/undefined

**Expected behavior**
The dropdown list should show the selected value in the Group.

**Screenshots**
![image](https://user-images.githubusercontent.com/1944368/64921803-5ec1df00-d7bf-11e9-94d9-0256888895fe.png)

**System**

Node.js version: v10.16.3
NPM version: 6.9.0
Strapi version: 3.0.0-beta.16.2
Database: MongoDB
Operating system: Windows 10

**Comment by rmaroun** [comment]
Reported here https://github.com/strapi/strapi/issues/3999

**Comment by derrickmehaffy** [comment]
Marking as duplicate: https://github.com/strapi/strapi/issues/3999
