### ISSUE TITLE
PM2 there is no server.js in my strapi project

### ISSUE THREAD

**Issue by vickylance** [strapi/strapi#4005]
**Describe the topic**
I followed this documentation to setup pm2 and strapi in digital ocean.
https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#digital-ocean

**Screenshots**
I am getting this error as there is no server.js in my strapi project.
vickylance@vickylance:~$ pm2 start ecosystem.config.js
[PM2][WARN] Applications jcpenny-cms not running, starting...
[PM2][ERROR] script not found : /home/vickylance/Projects/jcpenny-store-configurator/cms/server.js

**Code snippets**
This is what is there in my ecosystem.config.js
```
module.exports = {
  apps : [{
    name: 'jcpenny-cms',
    cwd: '/home/vickylance/Projects/jcpenny-store-configurator/cms',
    script: 'server.js',
```

**Additional context**
Obviously there is no server.js file that is why its failing but is there some other script that I must point to?

**Comment by derrickmehaffy** [comment]
You will need to make one, strapi doesn't have one by default.

```
#!/usr/bin/env node
'use strict'; 

// Start Strapi
const strapi = require('strapi');
strapi().start();
```

**Comment by scottydev** [comment]
Had this same issue, thanks for the answer. Wish this was updated in the step-by-step docs:

https://strapi.io/documentation/3.0.0-alpha.x/guides/deployment.html#the-ecosystem-config-js-file
