### ISSUE TITLE
Strapi crashes when creating has-many relation

### ISSUE THREAD

**Issue by bytasv** [strapi/strapi#401]
**Node.js version**: v8.9.3
**npm version**: v5.5.1
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: Mac OS X

Hello

I've started working with strapi and already got an issue.

I created two content types and I want to define the relation of has-many between them. As soon as I do that through admin panel I start getting this error:
```
.../strapi-ps/node_modules/mongodb/lib/mongo_client.js:433
          throw err
          ^

TypeError: Cannot read property 'nature' of undefined
    at Object.defineAssociations (.../strapi-ps/node_modules/strapi-utils/lib/models.js:254:23)
```

What am I doing wrong? Though I strongly believe this is a bug and should not break like this...

**Comment by soupette** [comment]
Hello @bytasv could you show us your models configuration?

**Comment by bytasv** [comment]
@soupette could You please tell me where should I look at? Do You want me to paste the generated code?

**Comment by soupette** [comment]
Yes please your API folder could be great. If you want add me to your github repository so I can take a look at it

**Comment by bytasv** [comment]
@soupette hey, I've just pushed to a public repo my code that does not work: https://github.com/bytasv/strapi-test

**Comment by Khanji** [comment]
I've encountered the exact same error, but with the following steps, which makes sense why the error appeared:

1. create new content type through content manager, lets call it: Roles. Don't save it yet.
2. create new content type through content manager, lest call it: Users. 
3. create a relation field with roles. 
4. save the Users content type. 

The same error appears.
```

TypeError: Cannot read property 'nature' of undefined
    at Object.defineAssociations (.../strapi-ps/node_modules/strapi-utils/lib/models.js:254:23)
```

@bytasv did you try to remove the content types and recreate your content types after? Because my strapi does not crash on belongs-to-many relation creation and also not on many-to-many.

Hope this helps

**Comment by bytasv** [comment]
@Khanji after I start getting errors mentioned above, I can not do anything anymore. The application just keeps crashing and I'm unable to remove neither models, nor relations

**Comment by soupette** [comment]
hi @bytasv could you add me to your repository so I can have a look?

**Comment by bytasv** [comment]
@soupette do you need access? because the repo is public

**Comment by soupette** [comment]
If test2 has many test1 then the files should be as follow :

*** Path -*** `api/test1/models/Test1.settings.json` 
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "test1",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "test2s": {
      "collection": "test2",
      "via": "test1"
    }
  }
}
```
*** Path -*** `api/test1/models/Test2.settings.json`
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "test2",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "test1": {
      "model": "test1",
      "via": "test2s"
    }
  }
}
```

**Comment by bytasv** [comment]
@soupette I created everything via admin UI that is provided. I will try to do the same with 7.3 and will let You know here

**Comment by bytasv** [comment]
@Aurelsicoko @soupette - I've tested with latest version and it seems to be working fine! Thanks guys, great work

**Comment by lauriejim** [comment]
There is already an open issue about that.
