### ISSUE TITLE
Display model names and field names in original case

### ISSUE THREAD

**Issue by sheerun** [strapi/strapi#4016]
**Describe the topic**

Currently names of models and fields are displayed in UI in capital case even though they were created lower case. Personally I think this is misleading and doesn't look good in UI. It is especially visible if one field in from capital letter and second not:

 https://imgur.com/a/WjUjDTV

**Your suggestions for this topic**

I think it would be reasonable to preserve original case for both models and field names. Also for sake of consistency types could be from lower case as well.

**Comment by lauriejim** [comment]
Hello @sheerun , thank you for sharing this.
Ping @Aurelsicoko about this point.

**Comment by soupette** [comment]
@lauriejim I think beta.18 fixes this one.

**Comment by lauriejim** [comment]
Yes!
