### ISSUE TITLE
(hook:mongoose) takes too long to load

### ISSUE THREAD

**Issue by MaLub** [strapi/strapi#402]
**Node.js v9.3.0**:
**npm 5.6.0**:
**Strapi 3.0.0-alpha.7.2**:
**Operating system MacOS 10.12.6**:

Trying the 'Getting Started':

```
[devel my-project]$ strapi start
DEBUG (85755 on macbook-07.fritz.box): Server wasn't able to start properly.
ERROR (85755 on macbook-07.fritz.box): (hook:mongoose) takes too long to load
```

I've installed mongo in a docker container.

Write a small node.js to test that the connection works (Package mongodb)

```
var MongoClient = require('mongodb').MongoClient,
  test = require('assert');
// Connection url
var url = 'mongodb://192.168.99.100:27017/test';
// Connect using MongoClient
MongoClient.connect(url, function(err, db) {
  // Get an additional db
  var testDb = db.db('test');
        console.log(testDb);
  db.close();
});
```

LOGS from the mongodb, connection seems to work

```
2017-12-22T09:11:52.825+0000 I NETWORK  [listener] connection accepted from 192.168.99.1:56917 #7 (1 connection now open)
2017-12-22T09:11:52.832+0000 I NETWORK  [conn7] received client metadata from 192.168.99.1:56917 conn: { driver: { name: "nodejs", version: "3.0.0-rc0" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "16.7.0" }, platform: "Node.js v9.3.0, LE, mongodb-core: 3.0.0-rc0" }
2017-12-22T09:11:52.842+0000 I NETWORK  [conn7] end connection 192.168.99.1:56917 (0 connections now open)
```

Here ist my develop/database.json
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "192.168.88.100",
        "port": 27017,
        "database": "development",
        "username": "",
        "password": ""
      },
      "options": {}
    }
  }
}
```

I've also looked at https://github.com/strapi/strapi/issues/318
The fix with clearing the cache is also in strap-version I'm using.

https://github.com/strapi/strapi/pull/344

**Comment by MaLub** [comment]
The error sits in fron ;) Wrong IP - now it works

**Comment by crisz** [comment]
It didn't work for me too. I changed "localhost" to "127.0.0.1" and now it works.

**Comment by memolipd** [comment]
Running strapi and mongodb through a docker-compose file leads to this problem intermittently.

It works and connects fine most of the time but sometimes it seems to timeout.

Restarting the containers fixes the issue `ctrl+c` and then `docker-compose up`.

Could it be a timeout which we can change?
