### ISSUE TITLE
ContentType plugin automatic delete files

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#4023]
hey, I created a function generic in service  ContentType.js  that allows you to delete all the files related to that entry or with several entries, here I share the code?

**Comment by lauriejim** [comment]
What do you want to do exactly? I'm not sure to understand.

**Comment by derrickmehaffy** [comment]
@mbistuer best to just submit a PR explaining your changes, or you can discuss it on Slack.

**Comment by mbistuer** [comment]
@derrickmehaffy  @lauriejim   I created a pull request https://github.com/strapi/strapi/pull/4032
