### ISSUE TITLE
How to integrate with auth0? 

### ISSUE THREAD

**Issue by caoer** [strapi/strapi#403]
Hi, we have a client who is using auth0 as their user system service. 
Can strapi integrate with [Auth0](https://auth0.com)?

**Comment by pierreburgy** [comment]
During the next few weeks we are going to integrate [PassportJS](http://www.passportjs.org/) (and authentication providers, including Auth0 with https://github.com/auth0/passport-auth0).

Thanks to that, Auth0 integration will be available.

**Comment by lauriejim** [comment]
You can check how our `users-permissions` plugin work and custom it to work with Auth0

**Comment by dfliess** [comment]
can you resume the steps needed to add a new provider ? I'd like to add https://github.com/sdurandeu/passport-mercadolibre

**Comment by itspoma** [comment]
any updates in Auth0 integration?

**Comment by julestruong** [comment]
@pierreburgy any news ?

**Comment by carlows** [comment]
+1, was the passport integration merged already?

**Comment by carlows** [comment]
https://www.npmjs.com/package/strapi-plugin-auth0 maybe you could share any issues you faced implementing this?

**Comment by derrickmehaffy** [comment]
Passport integration has not been added yet and is planned. Currently the auth system is all contained in the `users-permissions` plugin and uses Grant/Purest.

The plan is to split 3rd party providers into their own plugins and use passport.js with them.

**Comment by derrickmehaffy** [comment]
> https://www.npmjs.com/package/strapi-plugin-auth0 maybe you could share any issues you faced implementing this?

That package is a placeholder with no code (hence the 0.0.0 version tag)

**Comment by Gribbs** [comment]
+1
please implement passport.js

**Comment by IRCraziestTaxi** [comment]
Why was this closed? I don't see where auth0 integration is available.

**Comment by sekhuat** [comment]
Any update on Strapi and Auth0 integration? This integration is paramount with app with authentication.

**Comment by derrickmehaffy** [comment]
@sekhuat No update yet, once work starts on it an update will be posted. As of right now it isn't in the roadmap yet and probably won't be until after November.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/61691031-832d9d80-acdf-11e9-91ad-b46eafdd3bb4.png)

https://blog.strapi.io/monthly-update-july-2019/

**Comment by nguyenDalex** [comment]
Is there auth0 support?

**Comment by lauriejim** [comment]
Strapi implement [**Purest**](https://github.com/simov/purest) and [**Grant**](https://github.com/simov/grant) to manage provider authentication.

**Grant** handle **Auth0** so you will able to add this provider in your application.

**Comment by nbolution** [comment]
Can anybody explain how to Setup the necessary things to use Auth0 as provider? I still found Purest example and Purest doesn't Support Auth0.

Would be great!

**Comment by derrickmehaffy** [comment]
> Can anybody explain how to Setup the necessary things to use Auth0 as provider? I still found Purest example and Purest doesn't Support Auth0.
> 
> Would be great!

Grant does: https://github.com/simov/grant

**Comment by Heziode** [comment]
You can take a look at: https://github.com/Heziode/strapi-auth0-example

And more specifically, [this commit](https://github.com/Heziode/strapi-auth0-example/commit/fcf411756dce2747421527d556a87d18b30d3e92), it show how I have integrated Auth0 to Strapi using Grant.

**Comment by derrickmehaffy** [comment]
I see no reason not to, you want to submit a Pull Request @Heziode

**Comment by Heziode** [comment]
Yep, 

I will do that no later than this weekend.
