### ISSUE TITLE
DeprecationWarning while running strapi develop.

### ISSUE THREAD

**Issue by dgtllion** [strapi/strapi#4030]
Hi all,

i'm using strapi 3.0.0.-beta.16.1 with MongoDB 4.2.0 and when i run ```strapi develop``` then i get this response:
```
> (node:11279) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> debug ⛔️ Server wasn't able to start properly.
```
Is there a way how to pass options to mongoose/mongoDB or how to fix it?

I've found a solution on mongoose documentation but dont know how to do that with strapi.
https://mongoosejs.com/docs/deprecations.html

Thanks

**Comment by derrickmehaffy** [comment]
This was already fixed here: https://github.com/strapi/strapi/pull/3961

As the error suggest you need to pass `{ useUnifiedTopology: true }` to mongoose in the database.json

**Comment by mohitr-optimus** [comment]
How can I use this { useUnifiedTopology: true }

**Comment by dgtllion** [comment]
> How can I use this { useUnifiedTopology: true }

I just reinstalled global and local strapi to newest version and it worked.

**Comment by cherndong** [comment]
Hi, Hopefully this is not too late.

The workaround is to create a database directly in mongodb so that you can bypass the following setting in your nodejs: { useUnifiedTopology: true }

Thank you.
