### ISSUE TITLE
File Upload - API - Related Fields are not updated

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4034]
File Upload Plugin is used Via API to upload Image With Reference to a Model

Example : Model : Glossary , Mapping ref Field : DependentItems

curl -X POST -F 'files=@files.jpg' -F 'refId=5d80de49edc8756a4d58106d' -F 'ref=Glossary' -F 'field=DependentItems' http://localhost:1337/upload

Output : related":[null ] - Image is uploaded but Releated Details is not updated 

Help Documentation says : 
-F 'source=users-permissions'
I am not sure what to mention on the Source ?

**Comment by lauriejim** [comment]
Hello @sunithakarthikeyan !
Source is necessary if you upload a file that is linked to a plugin's model (like user)
In your case, you are trying to link your upload file to Glossary that is not a plugin model. So you don't need to add this option in your request.

**Comment by sunithakarthikeyan** [comment]
Request : curl -X POST -F 'files=@files.jpg' -F 'refId=5d80de49edc8756a4d58106d' -F 'ref=Glossary' -F 'field=DependentItems' http://localhost:1337/upload

Response : {"_id":"5d8b37923fe8f730eb0c8ee3","name":"arc.png","sha256":"uW6Ikj43RG6TpdyuDDInHSnOyyaBcUqfF7F_nluZDNg","hash":"467fa6843dde480c9161e8fb3e3a2f9d","ext":".png","mime":"image/png","size":"215.13","url":"http://210.210.127.202:1337/uploads/467fa6843dde480c9161e8fb3e3a2f9d.png","provider":"local",**_"related":[null],_**"createdAt":"2019-09-25T09:46:58.621Z","updatedAt":"2019-09-25T09:46:58.670Z","__v":0,"id":"5d8b37923fe8f730eb0c8ee3"}]

**Comment by sunithakarthikeyan** [comment]
Glossary is userdefined datamodel and Related Key is set as NULL

**Comment by lauriejim** [comment]
Can you please format your messages.
It's currently not readable.
