### ISSUE TITLE
The user email field should be private

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4037]
**Describe the topic**
Any user who can run `GET /users`, can see the `email` of the other users.

**Your suggestions for this topic**
Users can see their own email, but not the email of others.

**Comment by alexandrebodin** [comment]
@abdonrd Can you please follow the template ;)

This is intended as the route is only accessible to administrators by default and is used to get th elist of users in the administration panel. 

The only case where the route is accessible is if you make it accessible in the roles & permissions plugin.

**Comment by derrickmehaffy** [comment]
Also an isOwner policy would apply here (see Sept blog post)

**Comment by abdonrd** [comment]
> @abdonrd Can you please follow the template ;)

I use the template. I just remove the not applicable sections (Screenshots, Code snippets).

**Comment by abdonrd** [comment]
> This is intended as the route is only accessible to administrators by default and is used to get th elist of users in the administration panel.
> 
> The only case where the route is accessible is if you make it accessible in the roles & permissions plugin.

Yes, for example my use case is create a web application and I need to:
- Create a user search engine. (`GET /users` with filters)
- Create the detail page of each user. (``GET /users/:id``)

**Comment by derrickmehaffy** [comment]
best to create a custom route for that @abdonrd removing any fields you don't want seen.

**Comment by abdonrd** [comment]
Yes, but I think this should change. Data as personal as an email should be private by default.

**Comment by derrickmehaffy** [comment]
> Yes, but I think this should change. Data as personal as an email should be private by default.

And it is :P that route is protected, and was not designed to be used for the purpose you are wanting to use it for :wink:

**Comment by weidox** [comment]
You're considering only a simple scenario about searching users. In my case, I'm linking user in many places, similar to using created_at/updated_at whose future was not clear till now. And I see no way to automatically sanitize private info like email.

**Comment by blheson** [comment]
What about in cases where a user is a relation field in another collection type (say books). When retrieving books, the user object is attached to the books and the emails are attached. This can also expose the email. 

For example 
```

 {
_id:....,
name:....,
author:{
  ...
  email: EXPOSED_EMAIL
  ...
 },
 ...
}
```

**Comment by spiff-radio** [comment]
> Don't know if it is a good practice, though.
Could someone from Strapi answer this ?

**Comment by Boegie19** [comment]
I will give my answer doing that is bad pratice since the email can then never leave trough any apis.
better solution in my opinion is https://github.com/strapi-community/strapi-plugin-protected-populate
where you can set what every endpoint can and can't populate

**Comment by Boegie19** [comment]
I would just use the plugin I recommanded since else you would basicly have to write the same plugin for yourself.
Since you need to remove the populate deeply+ remove filtering deeply on it
