### ISSUE TITLE
Can't strapi start (ENV: Production) with Plugin GraphQL 3.0.0-beta.15

### ISSUE THREAD

**Issue by jimmi2051** [strapi/strapi#4038]
**Describe the bug**
I can't start strapi when import plugin GraphQL. 

**Steps to reproduce the behavior**
1. strapi install graphql 
2. strapi start ( <-- this is work  )
3. rm -rf node_modules 
4. rm -rf package-lock.json
5. npm install 
6. strapi start ( <-- this is error )
7. Message error: [2019-09-18T03:08:38.909Z] error TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.generateSchema (/home/deftnt/Documents/be-lms/node_modules/strapi-plugin-graphql/services/Schema.js:160:25)
    at Function.initialize (/home/deftnt/Documents/be-lms/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at /home/deftnt/Documents/be-lms/node_modules/strapi/lib/hooks/index.js:52:31
    at after (/home/deftnt/Documents/be-lms/node_modules/strapi/lib/hooks/index.js:153:39)
    at /home/deftnt/Documents/be-lms/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (/home/deftnt/Documents/be-lms/node_modules/strapi/lib/hooks/index.js:164:17)
    at Object.onceWrapper (events.js:286:20)
    at Strapi.emit (events.js:198:13)
    at onFinish (/home/deftnt/Documents/be-lms/node_modules/strapi/lib/hooks/index.js:44:12)
    at _.forEach (/home/deftnt/Documents/be-lms/node_modules/strapi-hook-mongoose/lib/index.js:725:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Expected behavior**

**Screenshots**
http://i.imgur.com/K2CDNtZ.png

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: "10.16.2"
- NPM version:  "6.9.0"
- Strapi version: "3.0.0-beta.15"
- Database: "MongoDB"
- Operating system: "Ubuntu 18.04"

**Additional context**
My app was deployed in Heroku. When I import plugin GraphQL to my app, it makes my app crash. I tried to remove plugin GraphQL and my app work ok.

**Comment by lauriejim** [comment]
Hello @jimmi2051 !
In your description, you look working without `production` environment.
I tried to reproduce your issue, but all works fine in my side.
Can you please verify all your strapi dependencies (in your package.json) have the same version.

**Comment by jimmi2051** [comment]
I have used version 3.0.0-beta.15 for all package strapi. I tried restart but it was still error. 
I also tried remove GraphQL, node_modules, package-lock.json and re-install GraphQL but it isn't working. 
"dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-beta.15",
    "strapi-admin": "3.0.0-beta.15",
    "strapi-hook-mongoose": "3.0.0-beta.15",
    "strapi-plugin-content-manager": "3.0.0-beta.15",
    "strapi-plugin-content-type-builder": "3.0.0-beta.15",
    "strapi-plugin-email": "3.0.0-beta.15",
    "strapi-plugin-graphql": "^3.0.0-beta.15",
    "strapi-plugin-settings-manager": "3.0.0-beta.15",
    "strapi-plugin-upload": "3.0.0-beta.15",
    "strapi-plugin-users-permissions": "3.0.0-beta.15",
    "strapi-utils": "3.0.0-beta.15"
  },

**Comment by dakshrathod40** [comment]
Hey @jimmi2051,

change this:
**"strapi-plugin-graphql": "^3.0.0-beta.15",**
to 
**"strapi-plugin-graphql": "3.0.0-beta.15",**

(Remove ^)
This might help!!

**Comment by jimmi2051** [comment]
Thanks @dakshrathod40, It works with me.
