### ISSUE TITLE
Websockets plugin with json-rpc 2.0

### ISSUE THREAD

**Issue by popuguytheparrot** [strapi/strapi#4039]
Hello 👋.

I would like to have a plug-in for web sockets with a sub protocol json-rpc 2.0. for creating APIs like REST (get, post, etc).

JSON RPC
https://www.jsonrpc.org/specification

**Comment by derrickmehaffy** [comment]
Please post your feature request here: https://portal.productboard.com/strapi/1-public-roadmap/tabs/2-under-consideration
