### ISSUE TITLE
strapi package has a dependency with a security vulnerability (ReDoS)

### ISSUE THREAD

**Issue by harukogaki** [strapi/strapi#4043]
**Describe the bug**
One of strapi's packages, `strapi-admin` , currently uses a dependency with a known vulnerability for stripping markdown: `remove-markdown@0.2.2`. 

**Steps to reproduce the behavior**
1. Go to `./packages/strapi-admin/package.json`
2. Find `remove-markdown^0.2.2`
3. Find vulnerability here: https://snyk.io/vuln/SNYK-JS-REMOVEMARKDOWN-73635 

**Expected behavior**
Stripping markdown functionality should not use dependency with a vulnerability.

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15

**Comment by derrickmehaffy** [comment]
@harukogaki if you could please provide a PR to fix this vulnerability that would appreciated. Thanks

**Comment by derrickmehaffy** [comment]
As we have had no more updates to this issue in some time I'm marking as closed, depends will be reviewed if there is an issue.
