### ISSUE TITLE
Missing content types in permissions

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#4045]
**Describe the bug**
All content types are not visible in the roles & permissions tab under public. I have confirmed that routes are associated with these content types.

**Steps to reproduce the behavior**
1. Download Strapi Docker
2. Create MySQL project with newest Beta (16.4)
3. Create various content types.
4. Check permissions for "public."

**Expected behavior**
I should see all content types under permissions.

**Screenshots**
<img width="1013" alt="Screen Shot 2019-09-18 at 2 13 06 PM" src="https://user-images.githubusercontent.com/28883798/65174245-82369500-da1e-11e9-8cc4-d391036b8b1b.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10 LTS
- NPM version: 6.9.0
- Yarn version: v1.17.3
- Strapi version: Beta 16.4
- Database: MySQL 8
- Operating system: CentOS in Docker

**Additional context**
I re-cloned my repo to build a fresh local database volume. In my primary app, only one content type is not appearing. In my re-cloned project with a fresh database, nearly no types are appearing. Of note, in my primary project, along with the missing type, an option for delete is missing for one type.
<img width="770" alt="Screen Shot 2019-09-18 at 2 16 51 PM" src="https://user-images.githubusercontent.com/28883798/65174593-333d2f80-da1f-11e9-8750-d7976661055f.png">

**Comment by amartincolby** [comment]
Made progress. I'm able to get everything to display by dropping the users-permissions_user, users-permissions_role, and users-permissions_permission tables.

**Comment by lauriejim** [comment]
Hello @amartincolby !
With the information you gave me, I'm not able to reproduce your issue.
Please can you give me a specific steps to reproduce the issue.
(You said,  create various type of content, but it's not really precise, the name of the content type and attributes name/type can maybe have an impact)

**Comment by amartincolby** [comment]
Since Story is the one that failed to post, I'm attaching an image showing its structure.
<img width="1407" alt="Screen Shot 2019-09-19 at 11 47 24 AM" src="https://user-images.githubusercontent.com/28883798/65259915-7d7fe880-dad3-11e9-80c8-db3c51cd3e53.png">

Here is the model:
```
{
  "connection": "default",
  "collectionName": "Story",
  "info": {
    "name": "story",
    "description": "A story for general consumption"
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "headline": {
      "maxLength": 64,
      "default": "",
      "required": true,
      "minLength": 3,
      "type": "string"
    },
    "summary": {
      "maxLength": 255,
      "type": "string"
    },
    "media": {
      "collection": "file",
      "via": "related",
      "plugin": "upload"
    },
    "author": {
      "default": "",
      "minLength": 8,
      "type": "string"
    },
    "feedback": {
      "type": "string"
    },
    "body": {
      "minLength": 5,
      "required": true,
      "type": "richtext"
    },
    "publish": {
      "type": "date"
    },
    "keyword": {
      "type": "string"
    },
    "type": {
      "required": true,
      "enum": [
        "Standard",
        "Featured"
      ],
      "type": "enumeration"
    },
    "locations": {
      "collection": "location",
      "via": "stories"
    },
    "functions": {
      "collection": "function",
      "via": "stories"
    },
    "dls": {
      "collection": "dl",
      "via": "stories"
    },
    "businesses": {
      "collection": "business",
      "via": "stories"
    },
    "categories": {
      "collection": "category",
      "via": "stories"
    }
  }
}
```
And the routes:
```
{
  "routes": [
    {
      "method": "GET",
      "path": "/stories",
      "handler": "Story.find",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/stories/count",
      "handler": "Story.count",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/stories/:id",
      "handler": "Story.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "POST",
      "path": "/stories",
      "handler": "Story.create",
      "config": {
        "policies": []
      }
    },
    {
      "method": "PUT",
      "path": "/stories/:id",
      "handler": "Story.update",
      "config": {
        "policies": []
      }
    },
    {
      "method": "DELETE",
      "path": "/stories/:id",
      "handler": "Story.delete",
      "config": {
        "policies": []
      }
    }
  ]
}

```
I don't actually know if Story had anything to do with the problem, honestly. Again, the behavior with my populated application, and the virgin one that I built specifically for testing, was different. The code files were the same, though.

I've attached a dump of the test DB.

This DB represents this state in the UI
<img width="788" alt="Screen Shot 2019-09-19 at 12 04 34 PM" src="https://user-images.githubusercontent.com/28883798/65261197-b456fe00-dad5-11e9-93c5-bc86918ff6bd.png">
[test_db.sql.zip](https://github.com/strapi/strapi/files/3632209/test_db.sql.zip)

**Comment by ilin-in** [comment]
Experiencing the same issue, some of the content-types in application section of Roles & Permissions are disappearing (but still visible in content-types on top left bar) and appearing again only after restarting service.

**Comment by lauriejim** [comment]
Can you provide steps to reproduce, please.
Until I haven't a step by step, it's hard for me to understand and help :/

**Comment by ilin-in** [comment]
I was not able to reproduce this issue again, it could be connected to cases when you manually changing some sort of data.

**Comment by derrickmehaffy** [comment]
the only time (and it's been a while) I could reproduce something like this is using the offline `strapi generate:api` command, once in a blue moon strapi doesn't check if the permission nodes for that model are there and "forgets" to add them.

**Comment by pitiboy** [comment]
Addition: I experience the same with my strapi instance that it is not avialable for *public* role. 
![image](https://user-images.githubusercontent.com/28708898/72878986-4c6f2900-3cfc-11ea-944b-3b0d963e9202.png)
I can see correctly for the *Authenticated* role everything as expected: 
![image](https://user-images.githubusercontent.com/28708898/72879057-6ad52480-3cfc-11ea-9a79-53ac02b307c8.png)
The table I have is very simple, but it think it is not related to that: 
![image](https://user-images.githubusercontent.com/28708898/72879112-86402f80-3cfc-11ea-8295-b8fc10b05d1f.png)

I had used sqlite, and the table suggests the same:
![image](https://user-images.githubusercontent.com/28708898/72879843-01561580-3cfe-11ea-9bb6-4bcce2ad5603.png)

When I inserted manually the missing lines to table *users-permissions_permission* as a workaround, it had resolved itself.

interestingly, I have another strapi instance, where this had been operating well, as expected, ande it worked for the 4th attempt on the original issue.

**Comment by Lith** [comment]
Hello,

I've experiencing (almost) the same issue.
When I create a new content type (on staging or production environment) the bug happens.

I try to provide the most details as possible below.

Last time when this bug happening : 
- 26/02/2020 at 15h00 : Launch new release in production with new content-type : "licenses". I set permissions `find` and `findOne` for all roles.
- 03/03/2020 at 16h10 : Everything's works fine 
- 03/03/2020 at 16h11 : A 403 occurs on my route "/licenses" (without any modification or new release put in production)

Please find below the log :
![403-error-licenses](https://user-images.githubusercontent.com/605495/75971766-85411700-5ed2-11ea-9949-62b3ccb6ae09.png)
 
1/ I check `users-permissions_permissions` table and surprise  `licenses` doesn't exist anymore.
2/ I check the admin panel, and the  `Licenses` content-type is present in the left panel, but not displayed in Autorization & Permissions section.

I stop the instance and relaunch it.
Licenses is reappearing, but I need to re-configure again all permissions.
ons.

**Comment by lauriejim** [comment]
Hello! Permissions are not updated/created/deleted in another place than this file.

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js

**Comment by arnespremberg** [comment]
I'm experiencing the same issue. Happened when pushing my local repository (runs on sqlite) to the staging server (runs on mysql) including some new models.
Was able to fix it manually by adding (all of) the missing database columns.

A fix here would be greatly appreciated. Is there any info I can provide you with that would be of any help? If it happens again I might look a moment into the file, but at the moment can't afford the time...

**Comment by ivanjeremic** [comment]
I have the same issue when using the `strapi generate:api <name> --plugin <name>` I actually generate models for my plugin, and this collection-types are not listed in Roles & Permissions, any info on how to resolve this issue?

**Comment by salouri** [comment]
Similar issue happened with me and here what fixed it with me: run from command prompt (bash):

`rm -rf build .cache node_modules package-lock.json && npm i && npm run build --clean && npm run develop`

in other words: remove cached modules and builds, the re-build the admin and re-run strapi again.

I hope it helps someone

**Comment by alexvais** [comment]
Hi! I have the same issue! There are some update to fix it?

**Comment by AakashPat** [comment]
Still running into this issue!!!

**Comment by stentibbing** [comment]
I had the same problem with my plugins content type not showing up in Admin -> Roles and therefore not being able to access the content via GraphQL. Took some digging around in the users-premissions plugin repo but got it solved. 

As it turns out, the users-permissions plugin scans for controllers and routes and I had problems with both of them since I followed the tutorial on the Strapi blog: [(https://strapi.io/blog/how-to-create-a-strapi-v4-plugin-add-a-content-type-to-a-plugin-3-6)].

The users-permissions plugin only registers actions for content types which implement core controller methods. So if your plugin implements only custom controllers, user-permissions plugin won't register your content type.

Another thing the users-permissions plugin does, is it scans for routes and only includes routes with type of 'content-type' into route map. So if the routes are type of 'admin', they're being skipped.

The solution was to use createCoreController factory to implement controllers and have type 'content-type' not 'admin' for the routes.

**Comment by javix64** [comment]
In the case someone is still with this issue:

I went to the directory and notice that where missing three folders: 'controllers, routes, services'. 
After creating this folders with their 'core' system, everything was working fine.

**Comment by kepes** [comment]
@stentibbing can you provide code example for a plugin please! I've been struggling with it for a while and it doesn't work to add the plugin's content-type to the admin interface and to the standard API.

**Comment by stentibbing** [comment]
Two things you need to have: 

1. You need to implement the controller of your plugin with createCoreController. 
Please see:
https://docs.strapi.io/developer-docs/latest/development/backend-customization/controllers.html#implementation

2. Routes need to have type 'content-api'.
An example of one:
'use strict';

module.exports = {
  type: 'content-api',
  routes: [
    {
      method: 'GET',
      path: '/post/find',
      handler: 'post.find',
      config: {
        policies: [],
        auth: false,
      },
    },
  ],
};

Thats it!

**Comment by kepes** [comment]
For me there was three main mistake to implement content-type properly:
1. In [How to create a Strapi v4 plugin : Server customization 4/6](https://strapi.io/blog/how-to-create-a-strapi-v4-plugin-server-customization-4-6) at "Routes structuration" in `server/routes/index.js` the config is empty at the begining but later it's poulated with proper config data. I missed it and just put empty hash into index.js thinking framework will read all files from folder. 
2. Names must be consistent in content-type, service and controller. My content type name was `instaimage` because Strapi don't allow `instaImage` and also can't use name like `insta-image` because the content name must be same with JS variable name. So, my content type become `instaimage` but first I named my service and controller `instaImage` with capital 'I' which cause many problems.
3. I think `createCoreRouter` not working in plugins which is a bug I'm opening an issue. At the time when this method called content types not initialized so it can't find my custom type.

**Comment by gonzaloner** [comment]
I've just ran into this problem, probably after upgrading Strapi but I'm not really sure. I have not found the root of the problem but I have been able to apply a simple workaround:
- Copy the `src/api` directories as a backup
- Delete the missing content types and create them again from the strapi panel
- Replace the needed backup model files in the new directories of `src/api`

I only replaced the `schema.json` files but it is possible to keep custom routes, controllers and services aswell.
Strapi will not delete the data during this process, but you should get database backup just in case.

**Comment by mjarosie** [comment]
> I was just playing around with Strapi when I encountered the same issue. What I did was to fix it.
> 
>     * Go to `src\api` - It where your content types live.
> 
>     * If a content type does not show in the permissions tab, open it's folder and change any file in the sub-directories that has a  .js  file extension to .ts
> 
> 
> My theory is, that the issue is caused by using `create-strapi-app` with a JS template combined and --ts flag.
> 
> PS. The solution proposed by [gonzaloner](https://github.com/gonzaloner) also worked for me.

I've run into this problem as well after using [ecommerce template](https://github.com/strapi/starters-and-templates/tree/main/packages/templates/ecommerce) with `--ts` flag. I can confirm that this fixed the issue. In addition to renaming files from `.js` to `.ts` I also had to update import statements (use `import ... from` instead of `require`), otherwise I was getting `TS2451: Cannot redeclare block-scoped variable` errors. Example change for a controller:

Before:
```javascript
// src/api/category/controllers/category.js
'use strict';

/**
 *  category controller
 */

const { createCoreController } = require('@strapi/strapi').factories;

module.exports = createCoreController('api::category.category');
```

After:
```typescript
// src/api/category/controllers/category.ts
"use strict";

/**
 *  category controller
 */

import { factories } from "@strapi/strapi";

module.exports = factories.createCoreController("api::category.category");
```

You basically have to do it for each `js` file (in `controllers`, `routes` and `services` directories) of each entity in `api` directory.
