### ISSUE TITLE
Add possibility to add shareEnabled: true on playground

### ISSUE THREAD

**Issue by EloB** [strapi/strapi#4048]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
A pretty simple but powerful feature to add is playground share button.

Read more here:
https://www.prisma.io/blog/introducing-graphql-playground-f1e0a018f05d#sharing-your-playgrounds-using-graphql-bin

https://github.com/strapi/strapi/blob/7c5f1484ba75891043065f6500186baa44013293/packages/strapi-plugin-graphql/hooks/graphql/index.js#L94

By adding `shareEnabled: true` on the file above in side that object. I haven't fully tested it but it started to show up in UI. We could probably make this optional with config but it would be nice feature to have.

**Comment by derrickmehaffy** [comment]
@EloB do feel free to submit a PR, this would be nice to have :smile:

**Comment by ivandevp** [comment]
May I help with this? 🙋‍♂

**Comment by lauriejim** [comment]
Feel free to investigate the **GraphQL** plugin and submit a pull request.
Your contribution is welcomed.

**Comment by tuphamdev96** [comment]
You should add this to Strapi's document. Thanks you xD
