### ISSUE TITLE
3.0.0-beta.16.4 breaks GraphQL aggregation query

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#4049]
**Describe the bug**
Going from 3.0.0-beta.16.3 to 3.0.0-beta.16.4, breaks my grahpql aggregation query.

**Steps to reproduce the behavior**
- run graphql an aggregation query
- Getting wrong results (all items are always the same (wrong) value)

**Expected behavior**
Get correct results (different values btw)

**Code snippets**
Big complex model to post here. Sorry.

**System**
- Node.js version: v12.10.0
- NPM version:6.11.3
- Strapi version:  3.0.0-beta.4
- Database: mongodb
- Operating system: macOS

**Additional context**
Also updated to 3.0.0-beta.5; didnt fix that. Going back to beta.3 does fixes it.

**Comment by alexandrebodin** [comment]
@jacargentina Without model info and an example query there is no way we can help you.

Can you please share a concrete example.

**Comment by derrickmehaffy** [comment]
`Also updated to 3.0.0-beta.5; didnt fix that. Going back to beta.3 does fixes it.` You are quite behind on updates in general also. As Alex said, we need examples to reproduce the issue.

**Comment by alexandrebodin** [comment]
@derrickmehaffy I'm pretty sure he means 16.4 and 16.5 ;)

**Comment by jacargentina** [comment]
@derrickmehaffy yeah, as @alexandrebodin  pointed... my confusion on numberings.... sorry.

I was using like this:

```javascript
    const query = gql`query {
      sinGenerar: licenserequestsConnection(where: {parent_null: true}) {
        aggregate {
          totalCount
        }
      }
   }
```

Somehow previously i had to put `totalCount` as `count` was not working (on 3.0.0-beta.16.3 and previous versions) and `totalCount` had the aggregate value (weird).

It seems now there is some bug fixed, which made `count` work, and also `totalCount` is also changed its result to be the real collection total count!  I've changed my aggregate query and it works fine.

Cheers and sorry!
