### ISSUE TITLE
Strapi + MongoDB + GraphQL, why you sooo slow :(

### ISSUE THREAD

**Issue by phongtt3** [strapi/strapi#4051]
**Describe the topic**
I'm using strapi 3.0.0-beta.16.5 (node v10.16.3)
- 2 content types: Video, Tag
- Video: 645 entries
- Tags: 2145 entries
- Relation: Videos  has and belongs to many  Tags
- Each video has ~20 tags

Environment: localhost
Device: 8Gb ram, Mac OS
Only using UI to create content types, no custom code

**Screenshots**
Query: using graphql, get first 50 videos + tag (only ID)
Time response: 12s
<img width="826" alt="image" src="https://user-images.githubusercontent.com/4243190/65213441-27b23d00-dae1-11e9-9ec7-73e732699d17.png">

**Comment by derrickmehaffy** [comment]
@phongtt3 please use the bug report template and not the discussion template. 

Discussion template is for technical discussions prior to an [RFC](https://github.com/strapi/rfcs) being created.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

After you have updated your issue with the proper template I can reopen.

Thank you!
