### ISSUE TITLE
Question regarding maximum amount of content types

### ISSUE THREAD

**Issue by kindziora** [strapi/strapi#4053]
### Description
    
A user should be able to create content types, and generate data for this content type.
By that the amount of content types will not be limited, resulting in thousands of model and settings files. It seems like that such an amount of files would slow down the hole strapi system.

### Question
Is strapi designed for that kind of usage? What would be the strapi way to do it?

Kind Regards

Alex

**Comment by lauriejim** [comment]
Can you precise your **description** please.
Can you give me more information about this _It seems like that such an amount of files would slow down the hole strapi system_
The number of files doesn't have a relation with the application performance.

**Comment by derrickmehaffy** [comment]
It would increase startup time but shouldn't matter in run time. I have 97 models myself and while my startup time is around 6 seconds, it has no real effect on performance. 

(Also I answered your question in slack)

**Comment by lauriejim** [comment]
OKay great @derrickmehaffy thank you.
I can close this issue.

**Comment by kindziora** [comment]
Hi @lauriejim thanks for your reply, at some point strapi needs to parse the models (and parsing thousands of files at once could reasult in memory and/or performance issues).
Thanks to @derrickmehaffy i will give it a try.
