### ISSUE TITLE
Wrong response  - error Grant: missing session or misconfigured provider

### ISSUE THREAD

**Issue by kutsyk** [strapi/strapi#4054]
Hello,

I'm having a strange behavior with my strapi social providers.
![image](https://user-images.githubusercontent.com/6589214/65258405-2134bd00-db03-11e9-9bdf-0c0f2c94f02d.png)

I configured facebook provider well, as said in the tutorial, but I'm not able to achieve it working with frontend app. Either mine(angular), either from the tutorial React app.

Here is my button: 
```
<a href="http://localhost:1337/connect/facebook">Facebook</a>
```
In the result it opens well facebook for to sign in(if needed) or redirect back to my frontend app, to route: `http://localhost:4200/connect/facebook`

After, I get received `code` and send the request to strapi - `this.http.get<any>(`http://localhost:1337/connect/facebook/callback`, {params: loginParams})`

Where `loginParams` contains code, here is trimmed request URL:
`http://localhost:1337/connect/facebook/callback?code=AQCBCqGtENsPB4fypJ8oHnQ0YfigHPXHTL9H0nbKA4lUoV2kJDBnuVpD2ABxLn-....qD4xCJ5eoK4NRBgFpsElvDYNE8DIOUNmLDAxpMMCqxejkfMenDPL`

Response to my code or Postman request is next:
`"error=Grant%3A%20missing%20session%20or%20misconfigured%20provider"`

If I just copy the URL and opet it in browser, it redirects me to `http://localhost:1337/auth/facebook/callback?acces...`, with showing all needed data.

But neither my code, neither postman do not receive the same result.

**System**
- Node.js version: v10.16.0
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.15
- Database: mongo
- Operating system: windows/linux

**Comment by lauriejim** [comment]
Hello @kutsyk !
I just tested the **Facebook** login with the [React Login](https://github.com/strapi/strapi-examples/tree/master/login-react) application.
By following the process, Facebook redirect you to your frontend application with `access_token` and not `code` query params.

**Comment by kutsyk** [comment]
Hello @lauriejim , it's true. I had bad handling of the response in my side. Everything works fine, thank you.

**Comment by lauriejim** [comment]
Thank you for the feedback.
