### ISSUE TITLE
how to change which fields for display in content manager relations?

### ISSUE THREAD

**Issue by alisharghi** [strapi/strapi#4055]
Hi guys!
After Build my site with Strapi , i had a problem.
we have some content type with some relations.
in each content type relations , fields to search is different.
Can i change fields from relation for display or search?(search in id or name or username or ...)
for example :
![Screenshot 2019-09-19 21:45:20](https://user-images.githubusercontent.com/42144245/65266033-81d5f100-db27-11e9-8ead-b46d48e1ad83.png)
![Screenshot 2019-09-19 21:44:52](https://user-images.githubusercontent.com/42144245/65266042-85697800-db27-11e9-856a-b83769b70dde.png)
![Screenshot 2019-09-19 21:44:11](https://user-images.githubusercontent.com/42144245/65266054-88fcff00-db27-11e9-8b82-9026cef61779.png)

**Comment by gfritzdev** [comment]
Hi,  go to the content manager.  Then go to the "Edit View" of the model that has the relation you would like to change.  Click on the relation,  a dropdown will appear at the bottom called "Entry Title".

**Comment by alisharghi** [comment]
> Hi, go to the content manager. Then go to the "Edit View" of the model that has the relation you would like to change. Click on the relation, a dropdown will appear at the bottom called "Entry Title".

All of entry title have default value "_id" , i change it to others fields and save it but doesn't affect

**Comment by gfritzdev** [comment]
<img width="2041" alt="Screen Shot 2019-09-19 at 12 53 23 PM" src="https://user-images.githubusercontent.com/29345721/65276420-84f7bf80-dadc-11e9-8769-91befb788a74.png">

Your updating the entry title located at the bottom of the page right?

**Comment by alisharghi** [comment]
> <img alt="Screen Shot 2019-09-19 at 12 53 23 PM" width="2000" src="https://user-images.githubusercontent.com/29345721/65276420-84f7bf80-dadc-11e9-8769-91befb788a74.png">
> 
> Your updating the entry title located at the bottom of the page right?

![Capture+_2019-09-20-00-42-04](https://user-images.githubusercontent.com/42144245/65277691-b9e92e00-db3f-11e9-9ef7-a2f0057a5f0c.png)
no , located at the top

**Comment by gfritzdev** [comment]
Well theres your problem,  thats updating the entry title of the Payment model,  not the relation,  use the one that appears at the bottom after click on a relation like you did there.

**Comment by alisharghi** [comment]
> Well theres your problem, thats updating the entry title of the Payment model, not the relation, use the one that appears at the bottom after click on a relation like you did there.

after click on a relation , entry title doesn't appear at the bottom.
I'll try to update my strapi version
my current strapi version : 3.0.0-alpha-26.2

**Comment by gfritzdev** [comment]
You are way behind,  we are on 3.0.0-beta.16.5.  I highly recommend upgrading.

**Comment by derrickmehaffy** [comment]
`my current strapi version : 3.0.0-alpha-26.2`

Alpha is no longer supported, please update to beta.
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/

Marking as closed as the user is using an unsupported version.

**Comment by themightyatom** [comment]
This issue lives on in the current version.
"Set the displayed field of your entry" does not change the value shown. 
In my case it shows the german version of a title. Most annoying. Have tried many ways of rectifying.
![Screenshot 2021-02-15 172721](https://user-images.githubusercontent.com/807176/107971888-545ad480-6fb3-11eb-9550-7495935568aa.png)
![groupnmae](https://user-images.githubusercontent.com/807176/107971890-54f36b00-6fb3-11eb-9182-7e6ea648f1fc.png)
