### ISSUE TITLE
Files related don´t work in beta 16

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#4057]
Hello

**Describe the bug**

I have a personalized service to upload a file in beta 15, it works correctly, but when I switch to beta 16, I delete the file related to the json, all but the last one I created.
I had to download the version to work again

My custom service:
``` 
 uploadsc: async json => {
    // Retrieve provider configuration.

    const config = await strapi
      .store({
        environment: strapi.config.environment,
        type: 'plugin',
        name: 'upload'
      })
      .get({
        key: 'provider'
      });

    // Extract optional relational data.
    const { source, refId, ref, field } = json.fields;

    // Transform stream files to buffer
    const buffers = await strapi.plugins.upload.services.upload.bufferize(
      json.files.files
    );

    const enhancedFiles = buffers.map(file => {
     // Add details to the file to be able to create the relationships.
      if (refId && ref && field) {
        Object.assign(file, {
          related: [
            {
              refId,
              ref,
              field,
              source
            }
          ]
        });
      }

      return file;
    });

    const uploadedFiles = await strapi.plugins.upload.services.upload.upload(
      enhancedFiles,
      config
    );

    // Send 200 `ok`
    return uploadedFiles;
  } 
```

**System**
- Node.js version:  (v10) 

- Strapi version: 3.16
- Database:MYSQL
- Operating system:MACos and Ubuntu

**Additional context**

**Comment by lauriejim** [comment]
Sorry but I don't understand your message, what is your issue?

**Comment by mbistuer** [comment]
@lauriejim  my problem is when you add a file to a specific table all the records with the upload file relationship are left in an empty object like file: {}. The last record added is the only one that contains the data

**Comment by alhill** [comment]
This is related to the breaking changes of Beta 16, upload controllers and services have changed and modified older versions doesn't work anymore. I had to customize again the new version :(

**Comment by lauriejim** [comment]
@mbistuer Can your try with the last version of Strapi.
If it works, use the code of the plugin by the last version and replace your current code.
Sorry for the disappointment.
