### ISSUE TITLE
Packaging a strapi project into an executable

### ISSUE THREAD

**Issue by AminZibayi** [strapi/strapi#4058]
**Describe the topic**
packaging a strapi project into an executable is possible using `nexe`, however, it does not offer any security options and code obfuscation nexe/nexe#545
`pkg` would be a good option but after spending sometime I still could not get it up and running, strapi seems much more complex than some simple scripts and assets...
do you have any suggestions on this topic?

**Your suggestions for this topic**
#3666

**Comment by lauriejim** [comment]
As you can see in the issue you linked - we have currently nothing to accomplish what you are trying to do.

**Comment by swerder** [comment]
I managed to get strapi work as a node Single Execution Application (SEA), by adding special webpack handlings for the dynamic loading of modules(plugins, middleware,...).
The resulting sea.blob(containing api backend & admin files) is about 35mb, combined with required binary node modules (sharp, sqlite) + nodejs executable it's resulting in total files size of ~150mb.
Or if you want to use only the result of webpack build (single index.js) + binary node modules it's ~50mb.

I'm not sure if there would be a technical possibility to add the webpack logic inside the normal strapi code, but it works as module patches to the normal release.
More information / the needed files are in the repo: https://github.com/swerder/strapi-sea

Attention: It's not 100% error prove as I don't use all features of Strapi(to verify them), but it my be a try to check it.
