### ISSUE TITLE
Strapi not sending email

### ISSUE THREAD

**Issue by avneesh74** [strapi/strapi#4061]
**Describe the topic**
Hey i am new to strapi, I have a app hosted on heroku (https://kriidanew.herokuapp.com/). If i disable email confirmation and try to submit the form then it works fine but if i enable email confirmation from strapi backend then after registration the email is not sent and it throws error in my react app.

I have tried  this with both the email provider sendmail and nodemailer but both of them have same behavior 

**Your suggestions for this topic**

**Screenshots**
If applicable, add screenshots to help explain your points.

**Code snippets**
If applicable, add code samples to help explain your points.

**Additional context**

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
