### ISSUE TITLE
How to get multiple levels of childs?

### ISSUE THREAD

**Issue by TiesTheunissen** [strapi/strapi#4062]
**Describe the bug**
Can't get more than 3 levels of complex childs.

**Steps to reproduce the behavior**
1. Go to "http://localhost:1337/admin/plugins/content-type-builder/models?modalType=model&settingType=base&actionType=create"
2. Create 5 content types (example: content_a, content_b, content_c, content_d,content_e)
for the fields: give them a relation to the parent a-b b-c c-d d-e
3. Create at least one content. for all content types.
4. Get the content by the auto generated API. "http://localhost:1337/content_a"

**Expected behavior**
returns a json with all the childs inc content_e

**Actual behavior**
returns a json with the child until content_c with an id

example json expected
```
{
	"object_a": {
		"id":1,
		"object_b": {
			"id":2,
			"object_c": {
				"id":3,
				"object_d": {	
					"id":4,
					"object_3": {
						"id":5
					}
				}
			}
		}
	}
}

```
output json: actual
```
{
	"object_a": {
		"id":1,
		"object_b": {
			"id":2,
			"object_c":3
		}
	}
}
```

**System**
node: 10.16.3
npm: 6.9.0
strapi: beta 3.0.0-beta.16.5

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello @TiesTheunissen !
If you want to achieve this thing, you will have to customize your query.
By default, strapi populate first level + media information.
You will have to customize your [service function 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/services.html#services).
In the function you want to update, you will have to specify the data you want to populate.
Here is the [query example 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/queries.html#examples) to populate data on findOne

**Comment by TiesTheunissen** [comment]
That is the problem. We don't know what our content managers create. The even manage the full content types with a few restrictions. but the relations under it are fully variable.

**Comment by lauriejim** [comment]
In this case I suggest you to use GraphQL.
It will be the best way for you to query the data you want.

**Comment by TiesTheunissen** [comment]
But with GraphQL you must exacly specify the fields you want and with objects there under it. I agree that GraphQL is usefull to get multiple levels of childs but if you don't know before howmany nested child levels are there and what fields are there this is a problem right?

**Comment by derrickmehaffy** [comment]
@TiesTheunissen in either case you are going to want a custom service. Strapi can't code in the ability to just keep populating all nested relations. Such a thing would mean you could effectively DDoS your service with a single query.

**Comment by TiesTheunissen** [comment]
Okey. thank you

**Comment by ico85** [comment]
Dead links everywhere...

**Comment by derrickmehaffy** [comment]
> Dead links everywhere...

https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html

**Comment by centigrade-thomas-becker** [comment]
> > Dead links everywhere...
> 
> https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html

https://docs.strapi.io/developer-docs/latest/plugins/graphql.html
