### ISSUE TITLE
Renaming a field from uppercase to lowercase causes "duplicate column name" [SQLITE]

### ISSUE THREAD

**Issue by aballaci** [strapi/strapi#4066]
Steps to reproduce:

1. Create a custom ContentType X with one field "Abc"
2. Rename the custom ContentType field "Abc" => "abc"
3. Save the ContentType.

error Error: SQLITE_ERROR: duplicate column name: abc

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello @aballaci !
This is due to a Knex issue.
We already have an issue open about the topic.
Thank you for reporting it.

**Comment by CarlosBC** [comment]
Hello @lauriejim.
I have made fresh install of Strapi "version 3.0.0-beta.19.3", i'm using Postgresql and knex "<0.20.0".
The is a solution for this problem?
Can be fixed by hand?
Thank you!

**Comment by matulkum** [comment]
I have the same issue. Renaming makes the server crash, without any chance to rename the field to lowercase ever again. Also not when deleting the field and creating a new one.

Can you link to the other open issue you mentioned? I can not find it.

**Comment by derrickmehaffy** [comment]
@matulkum it's #1114 

For the moment the best way is to rename the field manually in the model settings file `./api/yourModel/models/yourModel.settings.json`

Then also change the name in the database, do make sure your Strapi server **isn't** running while doing this changes.
