### ISSUE TITLE
Configure layout for Groups is not working

### ISSUE THREAD

**Issue by ytachi0026** [strapi/strapi#4067]
**Configure layout for Groups is not working**
When you create a Group (similar to the blog https://strapi.io/blog/repeatable-groups-feature?redirectPage=1), and then you add it to any Content Type, when you edit the Layout and then hit Save, it doesn't work.

**Steps to reproduce the behavior**
1. Go to your panel admin and then to 'Content Manager'
2. Got to the tab Groups
3. Click on 'any Group you just created'
4. Rearrange the fields at your will.
5. Click on 'save'
6. It prompts a dialog box saying: An error has occurred. 

**Expected behavior**
It should show a success message.

**Screenshots**

![image](https://user-images.githubusercontent.com/1701423/65367553-9df59300-dbf8-11e9-90d8-c3c38878bff2.png)

And on the terminal:
`[2019-09-21T03:47:17.375Z] debug PUT /content-manager/groups/opening_hours (26 ms) 400`

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16
- Database: Mongo 
- Operating system: MacOS / Ubuntu

**Additional context**

**Comment by lauriejim** [comment]
Hello! Can you give me the exact strapi version please.
`6.9.0` is your npm version I think.
I will not be able to help you without this information.

**Comment by insightguides** [comment]
Have same error while trying edit the group view and while click "saving" button,  error happened
![image](https://user-images.githubusercontent.com/29601375/65417327-19726280-ddfa-11e9-89e0-4ba106b751fc.png)

Browser Console log:
![image](https://user-images.githubusercontent.com/29601375/65417465-5dfdfe00-ddfa-11e9-95f3-bc0395544f78.png)

Version : Strapi v3.0.0-beta.16
Envrionment: test
Build env: Docker

**Comment by ytachi0026** [comment]
hi @lauriejim , sorry, I messed up the information, here is the current version i am using:

nodejs: v10.16.3
npm: 6.9.0
```
    "strapi": "3.0.0-beta.16",
    "strapi-admin": "3.0.0-beta.16",
    "strapi-hook-mongoose": "3.0.0-beta.16",
    "strapi-plugin-content-manager": "3.0.0-beta.16",
    "strapi-plugin-content-type-builder": "3.0.0-beta.16",
    "strapi-plugin-email": "3.0.0-beta.16",
    "strapi-plugin-settings-manager": "3.0.0-beta.16",
    "strapi-plugin-upload": "3.0.0-beta.16",
    "strapi-plugin-users-permissions": "3.0.0-beta.16",
    "strapi-provider-upload-aws-s3": "3.0.0-beta.16",
    "strapi-utils": "3.0.0-beta.16"
```

**Comment by lauriejim** [comment]
Okay, we fixed this issue in the last version of strapi (3.0.0-beta.16.5)
Can you please update your packages versions, remove your `package-lock.json` of `yarn.lock` and re-install your application packages.
Then re-build the admin by running `yarn build` or `npm run build`
This should fix your issue.

**Comment by ytachi0026** [comment]
Thanks @lauriejim, updating strapi to 16.5 fixed the issue
