### ISSUE TITLE
Media preview list doesn't work when restoring a dump in another environment with mongo db

### ISSUE THREAD

**Issue by rmaroun** [strapi/strapi#4068]
**Describe the bug**
I created a dump of my staging environment with mongodump where i have enabled the media preview component in some of my content types. When i restore the dump using mongorestore, then i am not able to see the images in the list view of my content types

**Steps to reproduce the behavior**
1. Enable the media preview component in content type list view by adding a media field to the list view of your content type in your content manager
2. Go to your content type and check if you can see the images in the list view screen of your content type
3. If you see the images then all is good for now
4. Create a backup of your database using mongodump
5. Restore this mongo dump to on your dev environment (local)
6. Open your strapi admin panel and go to the content types that have an image in their list view
7. You will see "-" in the image column and not the image preview

**Expected behavior**
I should see the image preview when using a dump and restore in the content types that have the media preview enabled in their list view

**Screenshots**
this is how it looks like in staging
![image](https://user-images.githubusercontent.com/4890827/65369190-79c2a200-dc4a-11e9-88c7-aec2f0890a70.png)

and this how it looks like after restoring the dump in dev
![image](https://user-images.githubusercontent.com/4890827/65369178-657ea500-dc4a-11e9-8bdd-63aff2043e89.png)

**System**
- Node.js version: v12
- Strapi version: beta.15
- Database: mongo db 4.0.6
- Operating system: Mac OS Mojave

**Comment by lauriejim** [comment]
Hello @rmaroun !
Can you give me the command you run to export and import your database.
Then I notice you specify your application is using `3.0.0-beta.15` version of strapi.
But the image preview feature is available in the `3.0.0-beta.16.4`version.
[Here is the changelog 📦](https://github.com/strapi/strapi/releases/tag/v3.0.0-beta.16.4)

**Comment by rmaroun** [comment]
@lauriejim my bad the version I am using is **beta.16.4**

- export command
`mongodump --uri "mongodb://username:password@server:port/database_name" --out ./staging`

- import command
`mongorestore --host xxx --port xxx --username xxx --password "xxxx" --db xxxx ./staging/database_name --nsInclude '*' --drop`

**Comment by lauriejim** [comment]
Okay thank you.
And when you are visiting one of your entries, did you see the image?

**Comment by rmaroun** [comment]
Yes when you go in the details page then you can see the image. So no issue about the image url, it seems like a bug which definitely needs to be high on the list as this is something we will do quite often to restore production to staging or dev.

**Comment by lauriejim** [comment]
Hum okay, so weird.
When you are visiting the list view, there is a request that fetches your data to display.

<details>
<summary>The request to fetch restaurants</summary>
<pre>http://localhost:1337/content-manager/explorer/restaurant?_limit=10&_sort=id:ASC&source=content-manager&_start=0</pre>
</details>

Can you share with me the result of this request for your content type.
I need to know if the images are in the data you fetch.

<details>
<summary>My restaurant data</summary>
<pre>
[
  {
    "id": 1,
    "name": "ASPIC",
    ...
    "cover": [
      {
        "id": 1,
        "name": "aspic_004.jpeg",
        "hash": "29d5f5ef9bbc4a438cfb9a9299fd0607",
        "sha256": "g1d-uzspNcbj5NB9rkRUR-ONLSOP7f2cDuEGnmQexq8",
        "ext": ".jpeg",
        "mime": "image/jpeg",
        "size": "69.93",
        "url": "/uploads/29d5f5ef9bbc4a438cfb9a9299fd0607.jpeg",
        "provider": "local",
        "public_id": null,
        "created_at": "2019-03-12T13:12:02.403Z",
        "updated_at": "2019-03-12T13:12:02.416Z"
      },
      ...
    ]
  }
]
</pre>
</details>

**Comment by rmaroun** [comment]
@lauriejim 

there you go:

![image](https://user-images.githubusercontent.com/4890827/65629370-7f661200-dfd3-11e9-9abe-92e5bf4b4460.png)

**Comment by vlad320** [comment]
@lauriejim 
Good afternoon. Do you need any additional settings to display the preview? version 16.5. I see the image field in the list, but everywhere dashes, the field just created. MongoDb.

**Comment by lauriejim** [comment]
Thank you @rmaroun !
So you have the pictures data 👌
Did you update your application from a previous version of Strapi.
If `yes` can you rebuild your admin please by running `yarn build` or `npm run build`

**Comment by rmaroun** [comment]
@lauriejim when doing this it looks like I am loosing the picture field within the content manager layout. I cannot find the image field and select it. Were you able to reproduce from your side? thanks

**Comment by ralphMevision** [comment]
@lauriejim when I am doing the restore on a windows PC then all is working, the difference could be the mongodb version (windows: v4.0.12 and on mac: v4.0.6). Will try to upgrade mongo on my mac and try it again.

**Comment by rmaroun** [comment]
@lauriejim upgraded on mac os to 4.0.12 and still same issue. Can you try and reproduce as this is not working for me. The content manager is not even showing me the image field in the dropdown for the list page.

**Comment by lauriejim** [comment]
Hum working on windows and not with mac (never saw that during all strapi life 😅)
As it works on your windows the issue look not coming from strapi.
I was not able to reproduce. All is working fine on my side.

**Comment by rmaroun** [comment]
Maybe related to my environment, closing this one.

**Comment by lauriejim** [comment]
Hum I think. If you find the solution, please share it with us to make sure it come from your env.
