### ISSUE TITLE
strapi console

### ISSUE THREAD

**Issue by BrotherSymeon** [strapi/strapi#4069]
I noticed that the CLI documentation for version 3.x does not have a mention of 
`strapi console` command but it is in version 1

I recently started playing with this thing and it is awesome. I ran this command
` strapi console`
and got this
`info: Starting the application in interactive mode...`
`error: The hook `_config` failed to load!`

I'm thinking maybe this is just something you can't do anymore but I thought I would at least ask
Thank you

**Comment by BrotherSymeon** [comment]
Sorry to bother you. I found the issue.

i ran 
`npx strapi console`
that works much better :-)

**Comment by rmaroun** [comment]
@BrotherSymeon can you then close the issue?

**Comment by lauriejim** [comment]
You can also run `yarn strapi console` or `npm run strapi console`
