### ISSUE TITLE
Sort not working with decimals

### ISSUE THREAD

**Issue by dakuenjery** [strapi/strapi#407]
**Node.js version**: 9.3.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: macOS 10.13.2

The request `http://localhost:1337/product?_sort=decimal` returns the following

    [
        {
            "_id": "5a3e76a1711b332e62151da6",
            "name": "Item 1",
            "decimal": "1499.1",
            "__v": 0,
            "id": "5a3e76a1711b332e62151da6"
        },
        {
            "_id": "5a3e76ab711b332e62151da7",
            "name": "Item 2",
            "decimal": "599.6",
            "__v": 0,
            "id": "5a3e76ab711b332e62151da7"
        },
        {
            "_id": "5a3e76b6711b332e62151da8",
            "name": "Item 3",
            "decimal": "999.2",
            "__v": 0,
            "id": "5a3e76b6711b332e62151da8"
        }
    ]

The request `http://localhost:1337/product?_sort=-decimal` returns the following

    [
        {
            "_id": "5a3e76b6711b332e62151da8",
            "name": "Item 3",
            "decimal": "999.2",
            "__v": 0,
            "id": "5a3e76b6711b332e62151da8"
        },
        {
            "_id": "5a3e76ab711b332e62151da7",
            "name": "Item 2",
            "decimal": "599.6",
            "__v": 0,
            "id": "5a3e76ab711b332e62151da7"
        },
        {
            "_id": "5a3e76a1711b332e62151da6",
            "name": "Item 1",
            "decimal": "1499.1",
            "__v": 0,
            "id": "5a3e76a1711b332e62151da6"
        }
    ]

The same thing is observed in admin panel.

Sorting by strings, floats and ints works correctly.

**Comment by dakuenjery** [comment]
![image](https://user-images.githubusercontent.com/2018050/34320777-22e98dd2-e812-11e7-868b-96c66811277c.png)

**Comment by dakuenjery** [comment]
This is due to the fast strapi use mongoose-double, which store double values as string on mongodb. Mongo sorting values as strings

**Comment by dakuenjery** [comment]
#408 This fixes the problem

**Comment by Aurelsicoko** [comment]
@dakuenjery Can you answer my [request in the PR](https://github.com/strapi/strapi/pull/408)? So we could merge your work and close this issue.

**Comment by dakuenjery** [comment]
I'm sorry for the delay. I'll try to do it as soon as possible.

**Comment by Aurelsicoko** [comment]
The PR has been merged, it should be fixed!
