### ISSUE TITLE
How to catch and save all errors errors in strapi?

### ISSUE THREAD

**Issue by saikrishnadeep** [strapi/strapi#4071]
I'm trying to integrate my strapi application with sentry, for which I will need to write a middleware. Use the following documentation: https://strapi.io/documentation/3.0.0-beta.x/advanced/middlewares.html I was able to create a custom middleware with the following:

```js
module.exports = strapi => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        try {
          await next();
        } catch (error) {
          Sentry.captureException(error)
        }

      });
    }
  };
};

```

However, doing so is preventing strapi to print out the errors to console the usual way but the error is captured by sentry application. 

**So, my question is**: How do I capture the error "seamlessly" and send it to a third party application, at the same time not hinder with the default functioning and error logging of the strapi to console.

Any help would be greatly appreciated!

Thanks :)

**EDIT:** I figured out that all strapi errors are accessible at the "boom" middleware as pointed out in this file: https://github.com/strapi/strapi/blob/6309af25c921640cb76aeeda463e55db1eb53ef1/packages/strapi/lib/middlewares/boom/index.js#L69 ,but how do I write a separate custom add-on middleware without touching this file?

**Comment by lauriejim** [comment]
Hello @saikrishnadeep !

You will have to `throw` your error to continue in the middleware stack.
And that will format the error with boom.

```js
module.exports = strapi => {
  return {
    initialize() {
      strapi.app.use(async (ctx, next) => {
        try {
          await next();
        } catch (error) {
          Sentry.captureException(error);
          throw(error);
        }
      });
    }
  };
};
```

**Comment by leonardyhuang** [comment]
Hi, what is the sequence of the middlewares? Is this correct (see _errorReporting_)?
```json
{
  "timeout": 100,
  "load": {
    "before": [
      "responseTime",
      "logger",
      "cors",
      "responses",
      "gzip"
    ],
    "order": [
      "Define the middlewares' load order by putting their name in this array is the right order"
    ],
    "after": [
      "errorReporting",
      "parser",
      "router"
    ]
  }
}
```
p.s: _Strapi v3.0.0-beta.16.5_.

Thanks.

**Comment by saikrishnadeep** [comment]
@leonardyhuang You gotta but your error reporting at the ending of everything. Something like this:

```json
{
  "timeout": 100,
  "load": {
    "before": [
      "responseTime",
      "logger",
      "cors",
      "responses",
      "gzip"
    ],
    "order": [
      "Define the middlewares' load order by putting their name in this array is the right order"
    ],
    "after": [
      "parser",
      "router",
      "sentry"
    ]
  }
}
```

**Comment by ceefour** [comment]
This is now documented at https://strapi.io/documentation/3.0.0-beta.x/guides/error-catching.html#handle-errors

Related issue: #2810

**Comment by gregg-cbs** [comment]
It would be nice to know how to do this in Strapi V4

**Comment by derrickmehaffy** [comment]
> It would be nice to know how to do this in Strapi V4

If you run into issues with the logger not logging something, in the middlewares file move it to the top of the array.

I've been meaning to make a PR to do that by default
