### ISSUE TITLE
Many-to-many relation bug

### ISSUE THREAD

**Issue by lstaszewski** [strapi/strapi#4075]
**Describe the bug**
When i create two models and relation many to many between them, then i edit model1 order of relations changes.

**Steps to reproduce the behavior**
1. Create model `foo` with one field `name`.
2. Create model `bar` with one field `name`.
3. Edit model `foo` and add new relation many to many field to model `bar`.
4. Create three records of `bar` model for example names `bar1`, `bar2`, `bar3`.
5. Create one record of `foo` model` for example name `foo1` and relation field in order `bar1`, `bar2`, `bar3`.
6. Check `foo1` record save ok (you have to see relations in order `bar1`, bar2`, bar3`.
7. Edit `bar1` reecord by change name to `bar1a`.
8. Edit `foo1` and see relations order `bar2`, `bar3`, `bar1a`.

WATCH VIDEO:
https://drive.google.com/file/d/1aVwGn7fyFTTb0QuHigq45R12wEnbIdLI/view?usp=sharing

**Expected behavior**
In step 8 i should see relation order equal to `bar1a`, `bar2`, `bar3`

**System**
- Node.js version: v10.16.3
- NPM version:6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: Mongo
- Operating system: Ubuntu 16.04

**Comment by lstaszewski** [comment]
I reporduce this bug on same enviroment and on strapi version 3.0.0-beta.16.5

**Comment by lauriejim** [comment]
Hello! @lstaszewski 
Thank you for reporting this. And the definition of steps - really appreciated.
Here is the issue https://github.com/strapi/strapi/issues/2166

**Comment by lstaszewski** [comment]
@lauriejim #2166 have `LOW` priority and a can't comment there. I think this issue should have `HIGH` priority. What should i do if i need to have good order of relations objects?

**Comment by lstaszewski** [comment]
@lauriejim BTW. I used version `3.0.0-alpha.12.2` before and there was no issue. What happened?

**Comment by derrickmehaffy** [comment]
@lstaszewski Strapi is open source, you are more than welcome to dig into the issue and should you be able to fix it, submit a PR :smiley:

**Comment by lstaszewski** [comment]
@derrickmehaffy I will try :) , but I am surprised that this issue has `LOW` priority.

**Comment by derrickmehaffy** [comment]
![image](https://user-images.githubusercontent.com/8593673/65444487-f8534700-dde4-11e9-9e39-74bb7d89a7bf.png)

https://strapi.io/blog/monthly-update-september-2019?redirectPage=1

**Comment by derrickmehaffy** [comment]
It has a low priority because there are depends required to make this work properly. In the grand scheme of things the ordering of content is not high one. It doesn't affect the actual performance or ability for Strapi to run.

**Comment by lstaszewski** [comment]
@derrickmehaffy  Ok, maybe this doesn't affect performance or ability, but in my case (I suspect others will be found) this issue makes strapi unusable. Thanks for information.

**Comment by lauriejim** [comment]
As @derrickmehaffy said, your are free to dig into this issue. 
I suggest you to write an RFC in this repo [strapi/rfcs](https://github.com/strapi/rfcs) to make sure your pull request is done correctly and by going in the right way.
But the topic of manually order relations is much bigger than you can think.
But if you want to fix this in particular. You can check the `relations.js` file of the `strapi-hook-mongoose`. You will have to make sure the `array` that store the relation maintain the right order.
