### ISSUE TITLE
GraphQL is acting really slow compared to REST

### ISSUE THREAD

**Issue by JelmerV-WFC** [strapi/strapi#4080]
**Describe the bug**
When I do a GraphQL query to fetch one content type item GraphQL is responding really slow, from 3 seconds to sometimes 8 or 9 seconds. When I try the same call with REST it's response time is +/- 300ms.

**Steps to reproduce the behavior**
1. Import a lot of items (in my case 5407 items)
2. Query one of that item with GraphQL

**Expected behavior**
A quick response

**Screenshots**
REST (deals/5d6a8e91e6927e01756bd892)
![image](https://user-images.githubusercontent.com/39594925/65423952-a1606880-de0a-11e9-9129-2d219d1aff4b.png)
GraphQL (graphql?id=5d6a8e91e6927e01756bd892)
![image](https://user-images.githubusercontent.com/39594925/65424136-0fa52b00-de0b-11e9-8d83-5de1e1c8c230.png)

**Code snippets**
GraphQL query:
`query {
  deal(id: "5d6a8e91e6927e01756bd892") {
    id
    automatic
    title
    intro
    price
    days
    nights
    date
    persons
    slug
    show_on_homepage
    automatic
    additional_html
    website {
      id
      country_code
    }
    providers {
      id
      name
    }
    arrival_airport {
      id
      name
    }
    departure_airport {
      id
      name
    }
    dealtypes {
      id
      name
    }
    booking_examples {
      id
      title
      url
      image {
        id
        url
      }
    }
    board_type {
      id
      name
    }
    dealproviders {
      id
      deeplink
      original_link
      active
      not_affiliate
      provider {
        id
      }
    }
    providers {
      id
      name
    }
    notes
    including_flight
    including_transfer
    including_rentalcar
    including_accommodation
    accommodation {
      id
      name
    }
    selected_media
    destination {
      id
      name
      parent {
        name
      }
    }
    affiliate_url
    publish_date
    expire_date
    alternative_date
    formula_price_4_lg
    formula_price_4_hp
    formula_price_4_ai
    formula_price_8_lg
    formula_price_8_hp
    formula_price_8_ai
    formula_price_15_lg
    formula_price_15_hp
    formula_price_15_ai
    discount
    discount_expire
    created_by {
      email
      username
    }
    edited_by {
      email
      username
    }
    createdAt
    updatedAt
    hide_partners
    published_deal {
      wordpress_id
    }
  }
}
`

**System**
- Node.js version: v10.16.1
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.5
- ~~Database: Mongoose (MongoDB Atlas)~~
- Operating system: Ubuntu 18.04

Edit by @derrickmehaffy Issue appears on all Databases Mongo, MySQL, and Postgres

**Comment by derrickmehaffy** [comment]
I can confirm this on a 5 node MariaDB Galera Cluster, GraphQL is acting quite slow.
Beta 16.5 ect ect. In my case I know I can rule out the database causing slowness.

**Comment by abdonrd** [comment]
I also have slow response in GraphQL!

**Comment by JelmerV-WFC** [comment]
My database response is also not the problem. When I log the original query response in the service file it's showing instant.

**Comment by derrickmehaffy** [comment]
Best guess is some change within the past few versions has royally borked the data-loader cache for GraphQL so it's constantly refetching data that it should have cached in memory. It might be worth toggling DB debugging on and seeing how many queries are hitting the DB backend. If that is the case then the GQL package probably needs a fresh set of eyes unless @alexandrebodin has any ideas.

**Comment by mbistuer** [comment]
I'm slow too with filters..

<img width="379" alt="Captura de pantalla 2019-09-23 a las 22 31 19" src="https://user-images.githubusercontent.com/14913444/65460491-4d797200-de52-11e9-8781-d9d6a72020e8.png">

**Comment by alexandrebodin** [comment]
@JelmerV-WFC Could you please enable the `tracing` in your grahpql config so you can have performance details per field and pinpoint them ? THis would help a lot !

To update the config : https://strapi.io/documentation/3.0.0-beta.x/guides/graphql.html#configurations

**Comment by JelmerV-WFC** [comment]
How can I best share this information, because it are a lot of rules. I can see that one of my relations is taking a lot of time. That relation is not that detailed (2 text fields and 1 richt text). It is a many to many relation, but other many to many relations are a lot quicker.

**Comment by alexandrebodin** [comment]
@JelmerV-WFC you can send a link the file if you can upload it somewhere.

**Comment by JelmerV-WFC** [comment]
@alexandrebodin I think it may be partly related to manyToMany relations. I use manyToMany because there was no manyWay at that time. Maybe GraphQL queries all the related items that are linked to that selected relations or something? jsFiddle with the tracing: https://jsfiddle.net/623Lvu54

**Comment by derrickmehaffy** [comment]
@JelmerV-WFC I don't think it's just mTM as I don't have any of them myself

**Comment by JelmerV-WFC** [comment]
Ah yeah thats true. In my case (see the jsFiddle) I can see that my relations are really slow. Even the hasOne relations, for example `deal.destination` that takes 397ms.

**Comment by jsonpj3wt** [comment]
Any news on this issue?  So far, looks like using graphql is not a viable option but want to make sure because we are also seeing some very bad query performance issues.

**Comment by acarrera94** [comment]
I'm seeing this issue as well, on top of that I noticed it's eating a lot more memory than before. I'm running on Cloud run with a limit of 512M. And some of the queries are using much more than that and causing my instances to shut down. And I'm using mongo atlas with a connection limit of 80 and some of these queries are causing it to go over the limit. I can change the limits but this didn't happen before this last release.

**Comment by derrickmehaffy** [comment]
@acarrera94 agreed something in the past few releases is slowly degrading performance. Prior to the beta or just after the first few beta releases GraphQL was fast as heck (I noticed the speed improvement when @Aurelsicoko added the data loader) My guess is the data loader isn't running properly and data isn't being cached like it should. Causing GQL to constantly go and refetch data it should already have.

**Comment by derrickmehaffy** [comment]
Specifically: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/Loaders.js

**Comment by acarrera94** [comment]
I started having issues as soon as I updated to `3.0.0-beta.16.6` from `3.0.0-beta.15`. So that's probably a hint as to where the issue is.

**Comment by JelmerV-WFC** [comment]
Maybe this is the change that created this issue:

![image](https://user-images.githubusercontent.com/39594925/65904257-65a34100-e3be-11e9-8574-3a47c2c3ede6.png)

**Comment by derrickmehaffy** [comment]
that's a good catch @JelmerV-WFC can you try to reimplement that locally and see if things improve?

**Comment by JelmerV-WFC** [comment]
Yes, testing at as we speak :)

**Comment by JelmerV-WFC** [comment]
I don't think that's the bottleneck unfortunately :( I think it happened in this commit, but there are a ton of changes: https://github.com/strapi/strapi/commit/187a669d1e6838de5191dd4827a040209f87e4df

**Comment by acarrera94** [comment]
Yeah there's lots of changes, I think it's very likely that the issue is in `packages/strapi-plugin-graphql/services/Resolvers.js` Since that uses the data-loader as well. @alexandrebodin is probably the most familiar with with this file right now.

**Comment by derrickmehaffy** [comment]
Yeah I've been quite busy the past week and didn't get to review changes to the graphql package as detailed as I normally do.

**Comment by derrickmehaffy** [comment]
@alexandrebodin @lauriejim I'm marking this one as a bug and confirmed since we have so many people describing similar issues.

**Comment by derrickmehaffy** [comment]
I am going to close and lock this thread in favor of our global tracking issue here: https://github.com/strapi/strapi/issues/8552

If anyone has additional comments please place them on the tracking issue, we are doing this to help centralize the issue and make it clearer where various related bug reports stem from the same source.
