### ISSUE TITLE
Ability to control paths that cause strapi to restart

### ISSUE THREAD

**Issue by gregorskii** [strapi/strapi#4082]
**Please describe your feature request:**

Using `strapi develop` will cause the app to restart on any file change. It would be create to be able to add to the ignore list in chokidar. This could be accomplished via a command line arg, environment variable, or a file.

I think the file option would be the easiest where a file could could be called `.strapiignore` or the like.

The current ignored files are here https://github.com/strapi/strapi/blob/master/packages/strapi/lib/commands/develop.js#L95.

What do you think?

**Comment by derrickmehaffy** [comment]
I agree this would be nice

**Comment by lauriejim** [comment]
Hello @gregorskii !
Thank you for this suggestion.
Can you please give me your use case.

**Comment by derrickmehaffy** [comment]
@lauriejim I would be happy to provide my own usecases :stuck_out_tongue_closed_eyes: 

1) Scripts kept in the working directory that work independent of Strapi but are used to maintain it
2) DB Exports, Examples, and testing files
3) Readme, documentation, ect

All of which would be good cases to exclude these from the auto-restart/watcher

**Comment by gregorskii** [comment]
My specific use case is that I am using a separate process to seed my database with initial content for development.

I have created a set of node scripts in a folder called /database. Every time I change the seed file the server reloads. These files have no affect on the Strapi instance other than the data stored in the tables.

This is mainly an issue when I am doing heavy development against those scripts. To mitigate I have changed my strapi-docker instance to use a different command that doesn't load Strapi. This is difficult because to see the data in the Strapi dashboard I have to restart docker and remove the command.

**Comment by lauriejim** [comment]
Okay thank you for sharing this. 
I suggest you to create a RFC on [strapi/rfcs](https://github.com/strapi/rfcs)

**Comment by gregorskii** [comment]
Will do, thanks.

**Comment by gregorskii** [comment]
Created https://github.com/strapi/rfcs/pull/5

**Comment by gregorskii** [comment]
Actually going to re-open, don't know the process between RFC's and feature requests.

**Comment by gregorskii** [comment]
This was resolved in the RFC, you can change the fields by updating the command that starts strapi. 

https://github.com/strapi/rfcs/pull/5

It's a small use case so having that documentation on GH might be enough.

**Comment by remi2j** [comment]
If you're dealing with temporary files, you can store them in a `.tmp` folder at the root of your project. It won't cause restarts

**Comment by derrickmehaffy** [comment]
@lauriejim @alexandrebodin based on https://github.com/strapi/rfcs/pull/5#issuecomment-541531742 did we ever get this documented? If so I'm not finding it and if it's not I'll reopen this so we can document it.

**Comment by u007** [comment]
after digging code and debugging, i finally found the solutioon

config/server.js

```
admin: {
    auth: {
      
    },
    watchIgnoreFiles: [
      '**/dump/**',
      '**/ignoredfolder/**',
    ]
  },
```

need to add full path or **/ and end with /**

**Comment by BrOrlandi** [comment]
What if I want to do the opposite? I want to include some folders to be watched.
My case is that I'm using strapi inside a lerna monorepo, and the strapi package depends on other package's folders.
Is there a way I can include these folders to watch and restar strapi when something changes?

**Comment by derrickmehaffy** [comment]
> What if I want to do the opposite? I want to include some folders to be watched.
> My case is that I'm using strapi inside a lerna monorepo, and the strapi package depends on other package's folders.
> Is there a way I can include these folders to watch and restar strapi when something changes?

We don't support running Strapi inside of a monorepo at this time.

**Comment by cunairport** [comment]
> after digging code and debugging, i finally found the solutioon
> 
> config/server.js
> 
> ```
> admin: {
>     auth: {
>       
>     },
>     watchIgnoreFiles: [
>       '**/dump/**',
>       '**/ignoredfolder/**',
>     ]
>   },
> ```
> 
> need to add full path or starts with double asterisk and end with double asterisk

Works like a charm

**Comment by irvv17** [comment]
> after digging code and debugging, i finally found the solutioon
> 
> config/server.js
> 
> ```
> admin: {
>     auth: {
>       
>     },
>     watchIgnoreFiles: [
>       '**/dump/**',
>       '**/ignoredfolder/**',
>     ]
>   },
> ```
> 
> need to add full path or starts with double asterisk and end with double asterisk

Works like a charm, very useful if u have a docker volume directory in the same work directory

**Comment by FieldMarshallVague** [comment]
The link above is wrong, since they released v4.

https://docs-v3.strapi.io/developer-docs/latest/setup-deployment-guides/configurations.html#server

**Comment by KantapongC** [comment]
For Strapi v4, solution is to add it in **config/admin.js** rather than in config/server.js

config/admin.js

```
module.exports = ({ env }) => ({
  auth: {
    ...
  },
  watchIgnoreFiles: ['**/ignoredfolder/**'],
});
```

**Comment by valtumi** [comment]
And simply that for specific files or group of files `watchIgnoreFiles: ['**/*.md']`

**Comment by jakubmirejovsky** [comment]
Hi @KantapongC , do you have any success with ignoring JS files in controllers? When developing, it would be a nice plus not to wait for a server restart, which is often unnecessary.

`module.exports = ({ env }) => ({
  watchIgnoreFiles: ['**/controllers/**'],
});
`
^^ this doesn't work :(

**Comment by KantapongC** [comment]
Hi @jakubmirejovsky, I am able to do so with these configurations in my project. When I edit code under `**/controllers/**` folder, the server does not restart.

Strapi v4.16.2 with typescript

`config/admin.ts`

```javascript
export default ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT'),
    },
  },
  flags: {
    nps: env.bool('FLAG_NPS', true),
    promoteEE: env.bool('FLAG_PROMOTE_EE', true),
  },
  watchIgnoreFiles: ['**/controllers/**'],
});

```

**Comment by ngotrongphuc** [comment]
> after digging code and debugging, i finally found the solutioon
> 
> config/server.js
> 
> ```
> admin: {
>     auth: {
>       
>     },
>     watchIgnoreFiles: [
>       '**/dump/**',
>       '**/ignoredfolder/**',
>     ]
>   },
> ```
> 
> need to add full path or starts with double asterisk and end with double asterisk

you're right, it must be full path like this `'/Users/username/Documents/my-strapi/dump'` or be wrapped with double asterisk like this `'**/dump/**'`
