### ISSUE TITLE
idAttribute is not working since it's hardcoded as 'id' 

### ISSUE THREAD

**Issue by ilin-in** [strapi/strapi#4084]
**Describe the bug**
When table has no `id` property (e.g. column_id) `idAttribute` mentioned in [Model options](https://strapi.io/documentation/3.0.0-beta.x/guides/models.html#model-information) does not work, since it's hardcoded here

**Steps to reproduce the behavior**
1. Create a database with table that has PK with different name rather than 'id'
2. Create a model for this table
3. You cannot use your custom id to perform CRUD requests in admin panel

**Expected behavior**
- Id shouldn't be visible in list view in admin panel. 
- User could tap on entity to go to edit screen (now undefined)
- Resolve crash by value [hardcoded here](https://github.com/strapi/strapi/blob/b2a81821dcc5be8b870c8137a6225ac3f978535d/packages/strapi-hook-bookshelf/lib/mount-models.js#L48)

**Screenshots**
<img width="295" alt="Screen Shot 2019-09-24 at 03 20 43" src="https://user-images.githubusercontent.com/1626752/65474096-d99f8f80-de7a-11e9-9868-b5bc4930f2f0.png">

**Code snippets**
Attribute 'id' hardcoded everywhere across `strapi-plugin-content-manager`

**System**
- Node.js version: tried with v10.15.3 and v12.4.0 
- NPM version: v6.11.3
- Strapi version: latest
- Database: mysql
- Operating system: Mac OS 

**Additional context**
There are also bookshelf plugin that managing synchronization needs to be resolved with proper id attributes.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by ilin-in** [comment]
Thank you @derrickmehaffy I've updated issue according the template.
And I've also made a PR according this issue: https://github.com/strapi/strapi/pull/4163 please check it out

**Comment by lauriejim** [comment]
This has been removed so I close this issue.
Will be reworked in the database layer.
