### ISSUE TITLE
Strapi Start Admin Page: An Error occurred

### ISSUE THREAD

**Issue by forethoughtde** [strapi/strapi#4085]
I cannot access built-in admin panel; I get _an error occurred_ message.

**Steps to reproduce the behavior**
1. Go to terminal and run the following command _npx create-strapi-app my-project --quickstart_
2. Wait for it to complete execution and open a webpage
3. Observe the error

**Expected behavior**
I should be able to access built-in admin panel without error.

**Screenshots**
<img width="1680" alt="Screenshot 2019-09-24 at 14 15 41" src="https://user-images.githubusercontent.com/9781577/65510733-eef5d780-ded5-11e9-8a94-c3b832bdb6fa.png">

**System**
Node: v12.8.0
npm: 6.10.3
MongoDB shell version v4.2.0
MongoDB server version: 4.2.0
Mac: 10.14.6 (18G87)

<img width="808" alt="Screenshot 2019-09-24 at 14 10 54" src="https://user-images.githubusercontent.com/9781577/65510712-e1405200-ded5-11e9-86eb-b6276883aebf.png">

**Additional context**
This happen only on computer Mac laptop.

**Comment by lauriejim** [comment]
Can you send me your browser console.
An error look happens in the network.

**Comment by lauriejim** [comment]
Can you send me your browser console.
An error look happens in the network.

**Comment by forethoughtde** [comment]
Upon following [this](https://github.com/strapi/strapi/issues/3284), I was able to fix this problem. 

It does not really make sense to edit a file in a package in **node_modules** directory. Is there any fix for this?

**Comment by lauriejim** [comment]
In fact, this has been fixed on last version of strapi (beta.16.5)

On the first application start `./extension/users-permissions/config/jwt.json` files is created and it restart the server.
It doesn't wait the end of Group & Permissions data setup.
So data are missing.
