### ISSUE TITLE
Cannot find module strapi/lib/utils/post-install.js

### ISSUE THREAD

**Issue by TheRealBarenziah** [strapi/strapi#4087]
**Describe the bug**
Not sure if bug, it may very well just be me being a newbie as I fear it may come from AWS. Still, I believe it's worth posting because I've seen too few references on this problem (and haven't see anyone having exactly this issue anyway).
Long story short, I tried to install a node module in my initially working Strapi app (`npm install axios` in ./myproject); not only did I failed, but I've also broken my Strapi in the process.

**Steps to reproduce the behavior**
1. Have a working, deployed Strapi backend (will name the project ./myproject for reference)
2. Connected in SSH, then in ./myproject `npm install axios`
3. If it complains about permissions redo with `sudo` prefix
4. `strapi start` doesn't work anymore
5. do the typical `rm -rf node_modules && npm install --cache /tmp/empty-cache` as it is usually enough to fix most node_module problems
6. Watch it fail because `Cannot find module /home/me/myproject/node_modules/strapi/lib/utils/post-install.js`

**Expected behavior**
`strapi start` should be working after running `rm -rf node_module` and `npm i`

**Code snippets**
`npm ERR! A complete log of this run can be found in: /tmp/empty-cache/_logs/2019-09-24T13_31_06_005Z-debug.log` : this is the end of this log file

```
20027 info lifecycle myOldProject@0.1.0~install: myOldProject@0.1.0
20028 silly postinstall myOldProject@0.1.0
20029 info lifecycle myOldProject@0.1.0~postinstall: myOldProject@0.1.0
20030 verbose lifecycle myOldProject@0.1.0~postinstall: unsafe-perm in lifecycle true
20031 verbose lifecycle myOldProject@0.1.0~postinstall: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/me/myproject/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/$
20032 verbose lifecycle myOldProject@0.1.0~postinstall: CWD: /home/me/myproject
20033 silly lifecycle myOldProject@0.1.0~postinstall: Args: [ '-c', 'node node_modules/strapi/lib/utils/post-install.js' ]
20034 silly lifecycle myOldProject@0.1.0~postinstall: Returned: code: 1  signal: null
20035 info lifecycle myOldProject@0.1.0~postinstall: Failed to exec postinstall script
20036 verbose stack Error: myOldProject@0.1.0 postinstall: `node node_modules/strapi/lib/utils/post-install.js`
20036 verbose stack Exit status 1
20036 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
20036 verbose stack     at EventEmitter.emit (events.js:193:13)
20036 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
20036 verbose stack     at EventEmitter.emit (events.js:193:13)
20036 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
20036 verbose stack     at ChildProcess.emit (events.js:193:13)
20036 verbose stack     at maybeClose (internal/child_process.js:1001:16)
20036 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
20037 verbose pkgid myOldProject@0.1.0
20038 verbose cwd /home/me/myproject
20039 verbose Linux 4.14.106-97.85.amzn2.x86_64
20040 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--cache" "/tmp/empty-cache"
20041 verbose node v11.13.0
20042 verbose npm  v6.7.0
20043 error code ELIFECYCLE
20044 error errno 1
20045 error myOldProject@0.1.0 postinstall: `node node_modules/strapi/lib/utils/post-install.js`
20045 error Exit status 1
20046 error Failed at the myOldProject@0.1.0 postinstall script.
20046 error This is probably not a problem with npm. There is likely additional logging output above.
20047 verbose exit [ 1, true ]
```
This is my package.json : 
```

  "name": "myOldProject",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application.",
  "main": "./server.js",
  "scripts": {
    "setup": "cd admin && npm run setup",
    "start": "node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"
  },
  "devDependencies": {
    "babel-eslint": "^7.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-react": "^7.7.0"
  },
  "dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-alpha.25.2",
    "strapi-hook-bookshelf": "3.0.0-alpha.25.2",
    "strapi-hook-knex": "3.0.0-alpha.25.2",
    "knex": "latest",
    "mysql": "2.16.0"
  },
  "author": {
    "name": "irrelevant",
    "email": "",
    "url": ""
  },
  "maintainers": [
    {
      "name": "irrelevant",
      "email": "",
      "url": ""
    }
  ],
  "strapi": {
    "packageManager": "npm",
    "uuid": "a324d580-da3c-462d-952e-3e0ccb1d9ac2"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT"
}

```

**System**
`node -v` : 11.13.0
`npm -v` : 6.7.0
- Strapi version (as seen in package.json) : 3.0.0-alpha.25.2
- Database: SQL
`cat /etc/system-release` : Amazon Linux release 2 (Karoo)
`uname -r` : 4.14.106-97.85.amzn2.x86_64

**Additional context**
- When I run `strapi start`, the error message is actually `Cannot find module 'strapi-utils'`; missing another module looks like a hint that I'm missing something obvious.
- For reference, ./myproject was originally a clone of ./myOldProject, which still runs fine. I've used this to double check my package.json, but haven't found anything strange. 
- tried to look at that post-install.js file, but I couldn't find it anywhere, not in the repo, not on the Internet
-   A guy somewhere had 
```
  "strapi-helper-plugin": "3.0.0-alpha.25.2",
   "strapi-utils": "3.0.0-alpha.25.2"
```
in his devDependencies; It seemed logic to try that, but with no success.
- While googling my problem, most answers referred to [this page][1] but I don't see how it helps me
- [this issue][2] recommends `unsafe-perm = true` in .npmrc, I've got no luck with that
- [this issue][3] was irrelevant, also using yarn is out of the question
- [this issue][4] what lauriejim said doesn't apply as my "postinstall" is already set like this
- reading through [this one][5] was a bit depressing and not that helpful in my case
- SOF seems inappropriate / overkill for my issue

Will gladly edit it if I figure it out in the meantime

[1]: https://strapi.io/documentation/3.0.0-alpha.x/migration-guide/migration-guide-alpha.12.1-to-alpha.12.2.html
[2]: https://github.com/strapi/strapi/issues/2787
[3]: https://github.com/strapi/strapi/issues/2951
[4]: https://github.com/strapi/strapi/issues/429
[5]: https://github.com/strapi/strapi/issues/1993

**Comment by lauriejim** [comment]
It will be hard you welp you.
Did you also remove you `package-lock.json`?

**Comment by TheRealBarenziah** [comment]
Hello, sorry I forgot to mention it, but yes every time I delete node_modules I also delete package-lock.json

I heard that it will be hard to resolve. Actually I have a short deadline for what I need to do, so I generated a new strapi for my specific need, and have no problem so far and been able to install npm module (axios) as easily as expected. But the setup isn't the same as the one I first described: I'm it's not deployed and I'm running it locally. Also it not a fix at all, just an avoidance I luckily can afford.

When this is done I intend to keep trying to resolve this issue as the more I think about it, the more I believe it's a problem on my end and not with the library. The two next things I intend to investigate are AWS configuration (I know nearly nothing about it so its probable come from there), and my strapi install, as I fear my global install of Strapi could conflict with the node_module local install (thought about this eventuality after seeing `strapi start` failing to launch my new project (with output `strapi.start is not a function`), while `yarn start` launches it flawlessly)

**Comment by lauriejim** [comment]
If you re-create a project you will do it with last version of strapi (the beta.16.5) and your previous project is with alpha version.
Thing are working differently, many updates have been made.
And when you create a project with yarn or via npm, node modules are not installed in the same way.

**Comment by TheRealBarenziah** [comment]
It is true, my new project is 3.0.0-beta.16.5.
I'm not sure what you meant by "And when you create a project with yarn or via npm, node modules are not installed in the same way.". If you mean you shouldn't mix the two once you used one (typically having a yarn.lock && a package-lock), I am aware of it. 

I've just been able to reproduce this issue, now I'm pretty sure the problem actually was with `npm audit fix`, it somehow mess the whole strapi. [Here is the repo](https://github.com/TheRealBarenziah/strapidemo) if someone wants to dig on that matter.

What I've been unable to reproduce, and I'm kinda certain happened in my original problem, was `strapi start` failing straight after adding axios module (I am usually wary of `npm audit fix` and don't see myself running it unless forced to)

Feel free to close this issue; and please let me know if you want me to edit the original issue now that we've narrowed its cause.

**Comment by derrickmehaffy** [comment]
@TheRealBarenziah yes do not use `npm audit fix` As it will pull in many invalid modules that aren't supported yet or it tries to fetch `strapi-next` versions for whatever reason. the next tag should not be used by anyone that isn't testing and they certainly should not be mixed with beta packages.

https://github.com/TheRealBarenziah/strapidemo/blob/28b6a7039e223f64903594ef009088ab8c837902/cms/package-lock.json#L4963-L4965

That was your problem.

Marking this as resolved, for those that come across this in the future:
1) **Never** use `npm audit fix`
2) Make sure all your strapi packages don't have `~` or `^` in the version
3) Make sure all your strapi packages are using the same tag release (beta/next)
