### ISSUE TITLE
Load provider credentials from file config / env variables

### ISSUE THREAD

**Issue by fodkastir** [strapi/strapi#4090]
**Describe the topic**
Currently `strapi-provider-upload-aws-s3` saves AWS credentials in DB which doesn't seem secure to me, or necessary. Among other provider plugins it is rare in which these keys will need to be modified in production.

For example with the `strapi-provider-upload-aws-s3` If you needed to change your S3 variables you would also need to do quite a bit of manual migration making storing them in the database an un-necessary risk for little to no reward.

**Your suggestions for this topic**
These config options should be stored in local files that could be used with environment variables just like the database settings are.

**Edited by**: @derrickmehaffy

**Comment by websocket98765** [comment]
👍  Env vars would be the preferred solution of course, because credentials shouldn't be stored in the DB or in git (files).

**Comment by derrickmehaffy** [comment]
>  Env vars would be the preferred solution of course, because credentials shouldn't be stored in the DB or in git (files).

I agree completely @websocket98765 :stuck_out_tongue: The intention would be something similar to how database.json is setup. You **could** set them static in the file (at the users own risk) but realistically you would define an env variable in the file and load it that way either at runtime or via something like dotenv.

**Comment by lauriejim** [comment]
Here, there are two solutions.
The first is to fork the plugin and update the code to load configs from a `strapi.config` variable.
Or the second is to create a PR on the email and upload providers to manage this case.
The best way to create a PR is to open an RFC on [strapi/rfcs](https://github.com/strapi/rfcs) to define how to manage this stuff.

**Comment by lependu** [comment]
Hi guys!
I was wondering why integrating AWS credentials and region configuration into this plugin (or even into the strapi configuration) is necessary. The AWS javascript SDK [automatically loads](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-node.html) credentials and region. On top of that saving this information into the database kind of goes against the AWS best practices recommendation. 

IMO the only configuration what this plugin has to provide is the bucket name, and let AWS SDK handle the hard staff. I happy to create an RFC or PR, but before that please, point me into the right direction if I am missing something.

**Comment by orhankutlu** [comment]
Hi everyone, I also had the same concern and needed to extend the plugin a bit. I created a package for my personal use and decided to publish it GitHub after I saw the thread. All thoughts are welcome 😊 

GitHub: 
https://github.com/orhankutlu/strapi-provider-upload-aws-s3-extended

NPM
https://www.npmjs.com/package/strapi-provider-upload-aws-s3-ext

**Comment by derrickmehaffy** [comment]
WIP Draft PR that addresses this: https://github.com/strapi/strapi/pull/5747

**Comment by derrickmehaffy** [comment]
@lauriejim Also gonna leave this here as it's not so much a discussion but a feature request that is already being worked on by @alexandrebodin

**Comment by lauriejim** [comment]
This is already the case for the Upload plugin.
Since the Media Lib release (beta.20).
Now configurations are based on a file.

**Comment by derrickmehaffy** [comment]
This has been fixed in rc.1 and will not be backported to the beta versions. It is not recommended to migrate to the rc tagged releases yet but the stable version is due by the end of this month (may 2020)

For now I am marking as closed.
