### ISSUE TITLE
Set related_id's type to VARCHAR(255) instead of integer in upload_file_morph table

### ISSUE THREAD

**Issue by websocket98765** [strapi/strapi#4091]
**Describe the bug**

Currently, the `upload_file_morph` table's `related_id` column defaults to a type of `integer`. This caues an issue when a developer uses a string ID type (UUID/NanoID/etc) on their user-defined model, becuase `related_id` only expects to receive integer ID's.

**Suggested solution**

Change `related_id` column type to `VARCHAR(255)`. This should work for both integer ID or string UUID types, no matter which a developer uses on their models.

**Steps to reproduce the behavior**
1. In MyModel.settings.json, set `"idAttributeType": "UUID"`
2. In Mymodels.js, replace the ID with the desired ID type. E.g.

```
  const nanoid = require('nanoid');

  beforeCreate: async (model, attrs, options) => {
    model.set('id', nanoid());
  },
```
3. Set the model to contain an image property--e.g.:

```
    "thumb": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    }
```
4. Attempt to save an image. (I don't have the error message text handy anymore unfortunately. But it relates to the type integer cannot accept the given value.)

**Expected behavior**

The image should save without an error. 

**System**
- Node.js version: 12
- NPM version: 6
- Strapi version: v3.0.0-beta.16
- Database: Postgres

**Comment by lauriejim** [comment]
Thank you for reporting this.
I will need @alexandrebodin point of view on this.

🛠 You can work around by using the [extension system 📚][https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions] to change the `./plugins/upload/models/File.settings.json` file.
You will be able to change the type.

**Comment by alexandrebodin** [comment]
Hi, 

The problem with this approach is that this will prevent using numeric indexes on the related_id column. 

We won't be setting this as the default behaviour but you can change it using jim's suggestion :)

**Comment by websocket98765** [comment]
I found the file you suggested (https://raw.githubusercontent.com/strapi/strapi/master/packages/strapi-plugin-upload/models/File.settings.json), but it only only the definition for the `upload_file` table, not the `upload_file_morph` table which contains the `related_id` column that needs to be altered.

Where is the definition for `upload_file_morph` table located? (I can't find it searching the Strapi repo for `upload_file_morph`.)

**Comment by lauriejim** [comment]
Arg after digging in your case it will be more complicated than I expected.
Cause the update you want to do is not managed by the file I sent you.
You want to modify an auto-generated thing.
This `[model.collectionName]_morph` table is generated in the `strapi-hook-bookshelf` and managed in the `mount-models.js` file.
If you want to update this, there is just 1 way, it's to fork this module and do your custom inside.
