### ISSUE TITLE
Plugin upload only applicable to default database

### ISSUE THREAD

**Issue by yuensunn** [strapi/strapi#4092]
**Describe the topic**
Was trying to upload media files in secondary database's table but was prompted with error message 

> select distinct `upload_file_morph`.* from `upload_file_morph` where `field` = 'gallery' and `upload_file_morph`.`related_id` in (19) and `upload_file_morph`.`related_type` = 'ritualinfos' - ER_NO_SUCH_TABLE: Table 'Ritual.upload_file_morph' doesn't exist

It appears to me that the strapi-plugin-upload is binded to the first/default database only. Is there a way to apply to the other databse too?

using:-
- "strapi": "3.0.0-beta.16.5"
- "mysql" : "5.7"

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
