### ISSUE TITLE
Values should not start with a number or a special character (Enum field)

### ISSUE THREAD

**Issue by TiesTheunissen** [strapi/strapi#4094]
**Describe the bug**
When creating an Enumuration as a field for a content type cant contain a special character.

**Steps to reproduce the behavior**
1 Create a content type.
2 Create a field as an enum.
3 Add as values:
"test"
"test2"
"test3"
This is including the " characters.
The same is with ' characters.
Or if I use values like: te-st it also gives me the error

**Expected behavior**
values could container "",'',-

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

**Comment by cns-dan** [comment]
Only alphanumeric characters and underscores (not beginning with a number) are permitted according to this:

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-type-builder/admin/src/containers/AttributeForm/index.js#L111

```
        const hasEnumFormatError = split.filter(
          v => !new RegExp('^[_A-Za-z][_0-9A-Za-z]*$').test(v)
        );
```

You can work around it by editing the enum values in the Model.settings.json file.
