### ISSUE TITLE
Search Query to Show Count of Items and List of Items in the Same Response (Strapi with MongoDB )

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4096]
**Describe the topic**
Search Query to Show Count of Items and List of Items in the Same Response (Strapi with MongoDB )

**Your suggestions for this topic**
I am trying to get the output of the following queries 
       var count = strapi.services.article.count(ctx.query);
       var content = strapi.services.article.find(ctx.query);
Then prepare a JSON and return the variable
var prepare_content = {"count" : count, "Content" :content}

Then i found that on creating a console.log (strapi.services.article.count) this is not only printing count + lot of schema releated stuff. 
Would like to know how to solve this ?

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

**Comment by sunithakarthikeyan** [comment]
**System**

Node.js version: v10.16.0
NPM version:6.9.0
Strapi version: v3.0.0-beta.14
Database:MongoDB
Operating system:Ubuntu 18

**Comment by lauriejim** [comment]
Please, can you well format your message.
It's not readable like this.
