### ISSUE TITLE
Search Query to Show Count of Items and List of Items in the Same Response (Strapi with MongoDB )

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4098]
Search Query to Show Count of Items and List of Items in the Same Response (Strapi with MongoDB )

**Steps to reproduce the behavior**

NA

**Code snippets If applicable, add code samples to help explain your problem.**

var count = strapi.services.article.count(ctx.query);
var content = strapi.services.article.find(ctx.query);
Then prepare a JSON and return the variable
var prepare_content = {"count" : count, "Content" :content}

Then i found that on creating a console.log (strapi.services.article.count) this is not only printing count + lot of schema releated stuff.
Would like to know how to solve this ?

**System**

Node.js version: v10.16.0
NPM version:6.9.0
Strapi version: v3.0.0-beta.14
Database:MongoDB
Operating system:Ubuntu 18

**Additional context Add any other context about the problem here.**
NA

**Comment by lauriejim** [comment]
Hello @sunithakarthikeyan !

As I asked you in [this issue](https://github.com/strapi/strapi/issues/4096) (the same by the way) you don't template your code in the right way.
It make the issue hard to read and understand.

Here is the [Markdown documentation](https://guides.github.com/features/mastering-markdown/) to learn how to template your issue.

Thank you.

I will reopen the issue when it will be done.
Thank you for your time.
