### ISSUE TITLE
Instead of Name , Mongo ID is shown in Related Content Type

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4099]
**Describe the bug**
In New Version beta 16.5, Related Content Type is not showing the Field Name instead MongoDB _ID is listed. This was working fine in Version beta@14

**Steps to reproduce the behavior**
1. Add a ContentType - Channel with one required field (name)
2. Add a Content Type - Category with Channel as releated Field
3. On Creating datas for Category , channel is listed in dropdown as mongoID instead on Name

**Expected behavior**
Dropdown to show Names 

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.16.0
- NPM version:6.9.0
- Strapi version: v3.0.0-beta.16.5
- Database:Mongo DB 
- Operating system:Ubuntu 18

**Additional context**

**Comment by sunithakarthikeyan** [comment]
![1](https://user-images.githubusercontent.com/2913281/65598589-66e8fe00-dfb9-11e9-9ed4-26fa82078bd0.png)

**Comment by lauriejim** [comment]
Hello! Here is tweet with a GIF that will let you update this.
https://twitter.com/laurie_jim/status/1176508780370190342?s=20
