### ISSUE TITLE
Createdby and lastmodifiedby field's to be added by default in all models 

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4100]
**Describe the topic**
Createdby and lastmodifiedby field's to be added by default in all models 

**Your suggestions for this topic**
loggedin usercontext to be persisted

**Screenshots**
NA

**Code snippets**
NA

**Additional context**
NA

**Comment by lauriejim** [comment]
Hello! The proposition is interesting.
Can you submit it in the[ public roadmap 🗓](https://portal.productboard.com/strapi) please.
For know you can deal with it by creating a custom middleware to manage it.
