### ISSUE TITLE
Add new type field - Google Maps

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#4101]
Hello.

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Good afternoon. I think it’s worth adding a new type to the field types - google maps.
With the ability to search by place name and select labels.
Very often you need to provide locations for companies, attractions, etc.

I attach screenshots, trimming as much as possible so as not to be considered advertising)

![image](https://user-images.githubusercontent.com/16899697/65637195-1f00c000-e027-11e9-8e2b-22c0d4e74bba.png)

![image](https://user-images.githubusercontent.com/16899697/65637238-32139000-e027-11e9-87ba-55bb33acefb1.png)

**Comment by lauriejim** [comment]
Hello @vlad320 !
Thank you for this suggestion.
I think this is really close to this feature request [issue](https://github.com/strapi/strapi/issues/2527)
I suggest you to add you content in this issue. Because the stored data will be the same.
The UI will change only.
Thank you for your time.
