### ISSUE TITLE
Clicking on Content Manager's Settings button in the PluginCard breaks the admin UI

### ISSUE THREAD

**Issue by eriktoyra** [strapi/strapi#4104]
**Describe the bug**
Clicking on the "Settings" button on the PluginCard for plugin Content Manager causes the admin UI to break with the error "Something went wrong." It's basically the same bug that has been reported in #3942 but in another place.

**Steps to reproduce the behavior**
1. Go to 'Marketplace'
2. Click on 'Settings' on the Content Manager PluginCard.
3. See the "Something went wrong" error.

**Expected behavior**
I expect to see the settings page for Content Manager plugin. 

**Screenshots**
<img width="1123" alt="Skärmavbild 2019-09-26 kl  09 48 56" src="https://user-images.githubusercontent.com/149738/65669415-ca1f7280-e043-11e9-9353-08a82823d044.png">

<img width="1127" alt="Skärmavbild 2019-09-26 kl  09 56 14" src="https://user-images.githubusercontent.com/149738/65669463-e7ecd780-e043-11e9-9b33-f2442085ce15.png">

**System**
- Node.js version: v10.15.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.16.5
- Database: 
- Operating system: macOS

I know how to fix this so I'm willing to contribute with a PR to solve the incorrect url. Let me know if you would like me to do so.

**Comment by derrickmehaffy** [comment]
I can confirm this issue both within the marketplace and plugin menus, clicking that gear will result in the same error.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting it.
Can you please submit a PR to fix it, please.
It's a super simple issue to fix, so a good opportunity for you to contribute to an Open Source projet.
I checked really fast and here is the issue `packages/strapi-admin/admin/src/components/PluginCard/index.js` at line 66.

**Comment by eriktoyra** [comment]
@lauriejim I tracked the problem to the same place. I will submit a PR before the weekend.

**Comment by eriktoyra** [comment]
Closing as the PR has been approved and merged to master.
