### ISSUE TITLE
Group type children's relation elements Error

### ISSUE THREAD

**Issue by dayrlism10** [strapi/strapi#4105]
**Describe the bug**
Adding a group that contain relation elements will cause application breaking

<img width="685" alt="Screenshot 2019-09-26 at 5 22 34 PM" src="https://user-images.githubusercontent.com/38413388/65677360-0b377700-e084-11e9-8f7e-b9f1118294ae.png">

**Steps to reproduce the behavior**
1. Go to content type builder
2. Create a group with relation element to other content type.
3. Add the group to other content type

**Expected behavior**
Application won't be able to start again until you revert it to original

**Screenshots**

1
![Screenshot 2019-09-26 at 5 24 12 PM](https://user-images.githubusercontent.com/38413388/65677818-da0b7680-e084-11e9-9be5-523bf3a2afad.png)

2
![Screenshot 2019-09-26 at 5 24 19 PM](https://user-images.githubusercontent.com/38413388/65677750-bd6f3e80-e084-11e9-83df-33c14c89a1df.png)

3
![Screenshot 2019-09-26 at 5 24 58 PM](https://user-images.githubusercontent.com/38413388/65678011-2b1b6a80-e085-11e9-885b-068341c595ab.png)

**System**
- Node.js version: v10.16.0
- NPM version:6.11.3
- Strapi version: 3.0.0-beta.16.5
- Database: MySQL
- Operating system: Mac

**Comment by lauriejim** [comment]
This issue no longer exist in the last version of Strapi - beta.17.8
