### ISSUE TITLE
How to migrate from beta.8 to beta.16

### ISSUE THREAD

**Issue by daehruoydeef** [strapi/strapi#4106]
**Describe the topic**
I am having trouble migrating from beta.8 to beta.16. 
I created the Project with beta.8 but as time progressed new versions got released. I tried to change all the beta.8 occurrences inside the package.json to beta.16, removed the node_modules and build folder and reinstalled all the packages. I tried to run with strapi develop but it is giving me errors.

I tried to update from beta.8 to beta.9 by removing all the node_modules and the build folder. Ran `npm install` and `strapi develop`.

I tried going to beta.15 same error

The Error says: `Cannot convert undefined or null to object` and is linked to generateSchema and the graphql plugin.

**Your suggestions for this topic**
Something like strapi update to ease this process or give clear instructions on migrating.

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/

**Comment by daehruoydeef** [comment]
Are there specific guides for beta also? I am running beta.8, I feel like since the alpha so much has changed so the guides do not apply to the beta versions.

**Comment by derrickmehaffy** [comment]
For the most part @daehruoydeef you don't need to modify much in the beta, hence the lacking guides. Given there are sometimes issues or smaller migration guides (beta.15 to beta.16) but generally issues result from package lock files or strapi package versions having carrots `^` in them.

You should be updating to the latest release (beta.16.5 which is a hotfix version) and you do need to replace some code which is detailed in the beta.15 to beta.16 migration guide.

There are a lot of guides that don't apply anymore and they are in the process of being rewritten (if you look at the commit history for the docs, and or some of the other Strapi repos like food advisor).

**Comment by daehruoydeef** [comment]
I just changed, to beta.15 first, reinstalled node_modules and rebuild the admin panel. Finally migrated to 16.

Thanks for the help 👍
