### ISSUE TITLE
Unable to set manyToMany or manyWay relation to null

### ISSUE THREAD

**Issue by JelmerV-WFC** [strapi/strapi#4109]
**Describe the bug**
It is not possible to set a `manyToMany` or `manyWay` relation to null. It's trying to map on the nullable object that will cause an error.

**Steps to reproduce the behavior**
1. Create a `manyToMany` or `manyWay` relation field
2. Set that field to null
3. `Cannot read property 'map' of null`

**Expected behavior**
Set the relation field to null

**System**
- Node.js version: v10.16.1
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.5
- Database: MongoDB
- Operating system: macOS

**Additional context**
I already fixed it at my side. Will do a pull request.

**Comment by alexandrebodin** [comment]
How exactly are you trying to set null ? programmaticaly ? 

many to many and manyWay should be arrays. we should prevent passing null instead of allowing it

**Comment by JelmerV-WFC** [comment]
In GraphQL the guys who build the frontend are sending null if there is no relation set. Should they send an empty array in that case?

**Comment by alexandrebodin** [comment]
I guess we can alllow null even if it doesn't really reflect what is happening in the back-end.
