### ISSUE TITLE
Suggestion (Easy GraphQL "enabling")

### ISSUE THREAD

**Issue by mehdi-cit** [strapi/strapi#411]
Hello All,
I saw graphql mentioned in the roadmap, The library below might go a long way in making it easy to have strapi "GraphQL enabled" (At least for the read part)
https://github.com/stems/join-monster

**Comment by Aurelsicoko** [comment]
Thanks for sharing this library, I didn't know it. It could be very interesting the build the SQL part based on it. I'm closing the issue but feel free to continue the discussion if you have more to share with us.

**Comment by mehdi-cit** [comment]
Another library that may help with mutations as well. MongoDB support should be coming as well.
https://github.com/graphcool/prisma
https://github.com/graphcool/prisma/issues/1643
However, note that the license is "Apache 2"
https://github.com/graphcool/prisma/blob/master/LICENSE

**Comment by Aurelsicoko** [comment]
@mehdi-cit We already developed something very similar to Prisma two years ago (https://github.com/strapi/waterline-graphql). We will base our future work on it.

**Comment by Aurelsicoko** [comment]
Yes, it is but the logic will be the same. Instead of calling Waterline functions, we will use our Query system to call the CRUD methods on the right connector (strapi-bookshelf or strapi-mongoose).
