### ISSUE TITLE
Strapi plugins on NPM not up to date

### ISSUE THREAD

**Issue by gregorskii** [strapi/strapi#4115]
Hi,

I believe the Strapi plugins on NPM are not up to date with code in develop.

See:

https://www.npmjs.com/package/strapi-plugin-users-permissions/v/3.0.0-beta.16.6

The plugin is missing the folder https://github.com/strapi/strapi/tree/develop/packages/strapi-plugin-users-permissions/admin/src/containers/AuthPage

It seems it may be built from master.

Github feature tagging indicates that these files should be similar to develop (at least when it comes to this container) per https://github.com/strapi/strapi/commit/664491d5939cfe3e87ad94ca360feaff8cdfcee1#diff-f2963c2e0ba3c9be905e9e21d1cdffc5.

If this is in error can this be addressed so the tag pulls from the correct code?

Thanks

**Comment by derrickmehaffy** [comment]
@gregorskii strapi releases are done on master. Develop branch is done on next releases.

**Comment by derrickmehaffy** [comment]
Marking as closed as this is intended.

**Comment by gregorskii** [comment]
The next version does not have develop either, is that correct?

https://www.npmjs.com/package/strapi-plugin-users-permissions/v/3.0.0-next.24

**Comment by derrickmehaffy** [comment]
The next version is only updated when passed to contributors like myself and others for testing pre-release of larger features that need more testing. Generally at the discretion of Strapi themselves.

**Comment by gregorskii** [comment]
Ah ok. Thank you.

**Comment by pouyamiralayi** [comment]
Hi dear @derrickmehaffy ! by this you mean we do not face errors any more regarding missing files like:
``admin/src/containers/AuthPage/forms`` ?
i mean 16.7+
tnx.
