### ISSUE TITLE
Context access issue in Roles resolver GraphQL

### ISSUE THREAD

**Issue by nom4da** [strapi/strapi#4116]
Users-Permissions plugin graphql schema resolvers are loading the Context variable with brackets {}, which returns undefined. If I remove brackets it works. 

![image](https://user-images.githubusercontent.com/1816294/65742654-4a64d700-e11b-11e9-91dd-7f346bd1c53a.png)

You can test on graphql playground:
`query {
  roles {
    name
  }
}`
Error: Cannot read property 'badRequest' of undefined

![image](https://user-images.githubusercontent.com/1816294/65742556-e3dfb900-e11a-11e9-9232-cad8d7fab3c4.png)

**If I remove brackets it works:**

![image](https://user-images.githubusercontent.com/1816294/65743612-96197f80-e11f-11e9-87e4-d86c76255fae.png)

![image](https://user-images.githubusercontent.com/1816294/65743644-b5b0a800-e11f-11e9-80c6-f07ef30cc935.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.6
- Database: mongo
- Operating system: windows 10

**Comment by lauriejim** [comment]
Hello @nom4da !
Thank you for reporting this.

Can you please submit a pull request to update this.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md
