### ISSUE TITLE
afterCreate Hook Not Working In Role

### ISSUE THREAD

**Issue by sajumani** [strapi/strapi#4119]
**Describe**
Role & Permissions Life cycle methods not firing. 

**Steps to reproduce the behavior**
1. Am created model file under "extensions\users-permissions\models\Role.js"
2. afterCreate Method not firing when i create new Role

**Expected behavior**
All extensions life cycle should work as expected

**Code snippets**
afterCreate: async (model, result) => {
       console.info('afterCreate hook', model, result );
}

**System**
- Node.js version: v10
- NPM version: v6
- Strapi version: strapi@3.0.0-beta.14
- Database: MongoDB
- Operating system: Windows

**Additional context**
Please anyone reply in this

**Comment by derrickmehaffy** [comment]
Closing as duplicate: https://github.com/strapi/strapi/issues/1443

Lifecycles plan to be reviewed but will require the new DB abstraction layer detailed in the sept blog: https://strapi.io/blog/monthly-update-september-2019?redirectPage=1

**Comment by sajumani** [comment]
Hi,

This is not duplicate of #1443 

Custom content type model hooks are working good for me. 

Plugin extension model hooks (Roles, Permissions & user ) not working

**Comment by derrickmehaffy** [comment]
@sajumani right now all lifecycle callbacks are considered under review working or not. As they will be modified to use the DB abstraction layer. Thus until that new process is complete all "bugs" related to them are marked as duplicate to the review issue I linked above.

**Comment by sajumani** [comment]
Ok Thanks for your info

**Comment by sajumani** [comment]
Any other way to fire event after insertion ? @derrickmehaffy
