### ISSUE TITLE
Cannot read property 'defaultConnection' of undefined

### ISSUE THREAD

**Issue by alexbigapps23** [strapi/strapi#412]
**Node.js version**:8.9
**npm version**:5.5.1
**Strapi version**:3.0.0-alpha 7.2
**Operating system**:

hi how i can fit it 
Cannot read property 'defaultConnection' of undefined ?

**Comment by lauriejim** [comment]
Hello @alexbigapps23 can you give me more information about your problem.
When this problem happens?

**Comment by dotcorps** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\VANK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'develop'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]
5 info lifecycle strapi@0.1.0~predevelop: strapi@0.1.0
6 info lifecycle strapi@0.1.0~develop: strapi@0.1.0
7 verbose lifecycle strapi@0.1.0~develop: unsafe-perm in lifecycle true
8 verbose lifecycle strapi@0.1.0~develop: PATH: C:\Users\VANK\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\gatsbylearning\e-commerce\backend\node_modules\.bin;C:\Users\VANK\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\xampp\php;D:\composer;D:\Git\cmd;D:\Git\mingw64\bin;D:\Git\usr\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\VANK\AppData\Local\Microsoft\WindowsApps;C:\Users\VANK\AppData\Roaming\Composer\vendor\bin;C:\Users\VANK\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\VANK\AppData\Local\atom\bin;C:\Program Files\heroku\bin;C:\Users\VANK\AppData\Local\Yarn\bin;C:\Users\VANK\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\VANK\AppData\Roaming\npm
9 verbose lifecycle strapi@0.1.0~develop: CWD: E:\gatsbylearning\e-commerce\backend
10 silly lifecycle strapi@0.1.0~develop: Args: [ '/d /s /c', 'strapi develop' ]
11 silly lifecycle strapi@0.1.0~develop: Returned: code: 1  signal: null
12 info lifecycle strapi@0.1.0~develop: Failed to exec develop script
13 verbose stack Error: strapi@0.1.0 develop: `strapi develop`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\VANK\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\VANK\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid strapi@0.1.0
15 verbose cwd E:\gatsbylearning\e-commerce\backend
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\VANK\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "develop"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error strapi@0.1.0 develop: `strapi develop`
22 error Exit status 1
23 error Failed at the strapi@0.1.0 develop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
