### ISSUE TITLE
Heroku deployment with MongoDB connection string fail

### ISSUE THREAD

**Issue by ruben00001** [strapi/strapi#4126]
**Describe the bug**
Following the 3.0.0-beta.x Heroku deployment guide with MongoDB, I attempt to set the Heroku database URI to the connection string for Node.js 'v.2.2.12 or later' but this leads to an error:

'replicaSet' is not recognized as an internal or external command,
operable program or batch file.
'authSource' is not recognized as an internal or external command,
operable program or batch file.
'retryWrites' is not recognized as an internal or external command,
operable program or batch file.
'w' is not recognized as an internal or external command,
operable program or batch file.

and the build fails.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.12
- Database:
- Operating system: windows 10

**Additional context**
I resolved the problem for now by using a string from one of the MongoDB shards but I don't know if this is optimal.

**Comment by lauriejim** [comment]
Can you please:
- Link the documentation you followed.
- Give us the MongoDB hosting solution you use.
Thank you.

**Comment by derrickmehaffy** [comment]
I'm marking this issue as closed, @ruben00001 if you have more information such as the stuff that @lauriejim asked for do provide it and this can be reopened. Thanks!

**Comment by ruben00001** [comment]
Sorry for not getting back to you. I've started another project and have encountered the same problem. If the issue could be re-opened I'd appreciate it. 

Documentation: https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku

I've set up MongoDB as instructed to in the Strapi docs: https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#mongodb-installation

**Comment by ruben00001** [comment]
For some reason using the MongoDB connection string from Driver Node.js version 3.0 or later without the '&w=majority' at the end of it leads to a successful deployment. Again, I'm not sure if this is safe or optimal, but, it's working.

**Comment by andrewl64** [comment]
@ruben00001 Did you managed to figure out what the problem was?

**Comment by ruben00001** [comment]
> @ruben00001 Did you managed to figure out what the problem was?

No. I just used the workaround I mentioned above.
