### ISSUE TITLE
Relation selection field is showing IDs instead of names

### ISSUE THREAD

**Issue by Elementrat** [strapi/strapi#4128]
**Describe the bug**
Hi folks! I'm evaluating whether to move my team's project from 3.0.0-beta.7 to 3.0.0-beta.16, and in my exploratory test migration, I'm seeing potentially blocking behavior - wondering whether user error is at play here, expected behavior has changed, or there's a bug.
migrate 
**Steps to reproduce the behavior**
(In beta 8 - Behavior we are used to and want to preserve)
1. Go to any content type instance that uses relations
2. Look at the relations lists
3. See that the displayed value is their -name- (human friendly)
![image](https://user-images.githubusercontent.com/1383125/65798699-2dce9c00-e127-11e9-9ef1-70e543bab5d3.png)

(In beta 16 - What seems invalid & not desired)
1. Go to any content type instance that uses relations
2. Look at the relations lists
3. See that the displayed value is their ID
![image](https://user-images.githubusercontent.com/1383125/65798661-10013700-e127-11e9-80d2-d0cc227b8d6d.png)

**System**
- Node.js version: 
- NPM version:
- Strapi version: "3.0.0-beta.16.6"
- Database: Mongo / Mongoose
- Operating system: Win10

**Comment by acarrera94** [comment]
You can configure this by clicking on "Configure the Layout".
But I assume most people would want name by default.

**Comment by veitbjarsch** [comment]
I'm not sure if it already was present in bet-7, but in the latest version you can choose what kind of field you are gonna display there. Therefore you need go to  Content Manager => Content Type and select your content type. The take the right tab and click your relational field, you wanna edit. On the bottom of the page you can change your entry title.

**Comment by derrickmehaffy** [comment]
As @acarrera94 stated you can change this in the content-manager plugin via that configure the layout button. I believe by default on new project it does indeed use the first string field, migration may need to reset this manually but as this is not a bug I am going to mark this as closed. Please do feel free to ask questions if you have them.

**Comment by cschweda** [comment]
I just did a fresh install of .beta.16.8 -- no migration. I'm getting this issue with every relation -- the relation dropdowns always display IDs.

I've set the 'entry title' to something that's not an ID (name, for example) -- but it doesn't make a diffference.

Help! This is a show stopper for me. Is there a way to configure something other than IDs to display?

**Comment by lauriejim** [comment]
Here is a short video to update it https://www.loom.com/share/791d3b6041914f43a368aa31657f9bcd
