### ISSUE TITLE
Cannot customize strapi-hook-bookshelf

### ISSUE THREAD

**Issue by vuanhnguyeen** [strapi/strapi#4129]
**Describe the topic**
I am working with strapi alpha 26.2. I get a problem with strapi-hook-bookshelf. I want to create field in mysql with the case "pdf" with the type "varchar(255)". I see module strapi-hook-bookshelf will do it. And I create "hooks" folder in the root and copy module strapi-hook-bookshelf then paste it in "hooks" folder. Then I create case "pdf" in index.js in row 500 like this. 
`
case 'string':
case 'enumeration':
case 'password':
case 'email':
case 'pdf':
type = 'varchar(255)';
break;
`
And I create depedencies in package.json.
`
  "strapi": {
    "dependencies": [
      "strapi-hook-knex"
    ]
  },
`
Then I run `npm run start`, I get error: `debug ⛔️ Server wasn't able to start properly.
[2019-09-28T02:16:40.735Z] error Cannot read property 'schema' of undefined
TypeError: Cannot read property 'schema' of undefined`. And I see error with `knex`: `const tableExist = await ORM.knex.schema.hasTable(table);` in row 459. I dont know how to fix it. Sorry for my weak englisk. Thanks so much
**Your suggestions for this topic**
Clear and simple suggestions for how you think this should be handled.

**Screenshots**
![image](https://user-images.githubusercontent.com/43888185/65810390-10a3d700-e1d4-11e9-8121-01fa10e8f54a.png)
![image](https://user-images.githubusercontent.com/43888185/65810403-2fa26900-e1d4-11e9-9fe8-7788528c5f88.png)
![image](https://user-images.githubusercontent.com/43888185/65810434-9a53a480-e1d4-11e9-8286-9210c827384c.png)
![image](https://user-images.githubusercontent.com/43888185/65810469-fdddd200-e1d4-11e9-9be5-47af93a047af.png)

**Code snippets**
If applicable, add code samples to help explain your points.

**Additional context**

**Comment by derrickmehaffy** [comment]
Strapi Alpha versions are no longer supported here or in slack. For this reason I'm marking this as closed.
