### ISSUE TITLE
Controller context does not contain user object (ctx.state.user)

### ISSUE THREAD

**Issue by alxnkt** [strapi/strapi#4132]
**Describe the bug**
Context object in controller does not contain user information (ctx.state.user).

**Steps to reproduce the behavior**
I was trying to get some objects from my database, that belong to the user logged in. I'm getting user information from `ctx.state.user`. When I request my api via `strapi.request("post", "/page", { data: {/* */}})` from my NUXT frontend using AJAX-request everything is ok. But when "server-side request" come into play, `ctx.state.user` becomes `undefined`.
(I' m using somethig like described in this tutorial [Cooking a Deliveroo clone with Nuxt](https://strapi.io/blog/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-setup-part-1-7))

**Expected behavior**
`ctx.state.user` must contain user object. [Docs](https://strapi.io/documentation/3.0.0-alpha.x/guides/authentication.html#user-object-in-strapi-context)

**Code snippets**
```
module.exports = {
  findThem: async ctx => { 
    return strapi.services.product.findThem(ctx.request.body, ctx.state.user); 
    // ctx.state.user is undefined
  },
};
```

**System**
- Node.js version: v12.7.0
- NPM version: 6.11.3
- Strapi version: beta 16.6
- Database: MongoDB
- Operating system: MacOS (latest)

**Comment by alxnkt** [comment]
I also can't get user information from `ctx.state` in policy. 
I use simplest policy `isAuthenticated`:
```
module.exports = async (ctx, next) => {
  if (ctx.state.user) {
    return await next();
  }
  ctx.unauthorized('You\'re not logged in!');
};
```
When I reload browser tab with F5, `ctx.state.user` is `undefined`. When I'm using AJAX-request, ctx.state.user is filled as expected.

**Comment by lauriejim** [comment]
Can you give me the route you created in the `routes.json` file, please.

**Comment by lauriejim** [comment]
I just tested with `beta.16.6` version and I can access to the user data in the state.
Here is [a quick video](https://www.loom.com/share/a6abd240c63342e3bb7058ebb291f57b).

**Comment by alxnkt** [comment]
> Can you give me the route you created in the `routes.json` file, please.


This is my route:
```
    {
      "method": "POST",
      "path": "/products",
      "handler": "Product.findThem",
      "config": {
        "policies": []
      }
    }
```

**Comment by alxnkt** [comment]
Appreciate for your help!
As I can see in your demo video, you send  ajax-request with bearer token via postman (right?). I can get user info through ajax too. But the problem occurs when I'm using simple http request with cookies.
[Video](https://www.loom.com/share/4782421865e9429cba3b46681327c10a)

**Comment by veitbjarsch** [comment]
@alxnkt you can set the auth token as header or as parameter to your request. The cookie won't be recognized as far I know.
<img width="645" alt="Screenshot 2019-10-03 at 00 06 48" src="https://user-images.githubusercontent.com/12811012/66085550-d5a5f880-e571-11e9-88b5-73fff33ecb85.png">

**Comment by lauriejim** [comment]
@alxnkt you are trying something that doesn't exist in strapi. That is the reason why it doesn't work.
You have to follow [the Authentication documentation](https://strapi.io/documentation/3.0.0-beta.x/guides/authentication.html#authentication).
If you want to update this to work with cookies, feel free to use the [extension concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions) to update the [logic function](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/policies/permissions.js) that manage it.
