### ISSUE TITLE
Invalid link on setup page

### ISSUE THREAD

**Issue by VentyCZ** [strapi/strapi#4133]
**Describe the bug**
The "privacy policy" link on the setup page leads to a wrong page (/policy => 404).

**Steps to reproduce the behavior**
1. Start fresh install
2. Go to http://localhost:1337/admin
3. Click on "privacy policy" link in the "Keep me updated about ..." checkbox
4. You get redirected to /policy - resulting in 404

**Expected behavior**
Should be redirected to /privacy (see footer of strapi.io site)

**Screenshots**
![2019-09-28](https://user-images.githubusercontent.com/3247664/65815814-756f2980-e1f4-11e9-8b85-65553f9bbc63.png)
![2019-09-28 (1)](https://user-images.githubusercontent.com/3247664/65815852-c41cc380-e1f4-11e9-8331-9990a7402888.png)

**System**
- Strapi version: master

**Comment by lauriejim** [comment]
Thank you @VentyCZ for this report.
And thank you for this PR.
I will review it.
