### ISSUE TITLE
Incorrect response for not confirmed email address

### ISSUE THREAD

**Issue by shivaji** [strapi/strapi#4134]
**Describe the bug**
Incorrect response when an email address is not confirmed with an incorrect password.

**Steps to reproduce the behavior**
1. Successfully registered to the user using  <instance>/auth/local/register
2. Email is received on given email address but not confirmed the email address
3. When tried to log in with the correct identifier with an incorrect password using <instance>/auth/local api 
4. Received response is:
```
{
       "statusCode": 400,
       "error": "Bad Request",
	"message": [{
		"messages": [{
					"id": "Auth.form.error.confirmed",
					"message": "Your account email is not confirmed"
					}
				    ]
				}
			]
		}


**Expected behavior**		
	```
{
	   "statusCode": 400,
	   "error": "Bad Request",
	   "message": [	{
		             "messages": [{
						"id": "Auth.form.error.invalid",
						"message": "Identifier or password invalid."
						}
					]
				}
			]
		}
```


**System**
- Node.js version: 10.16.2
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.16.6
- Database: Sqlite 3
- Operating system: Windows 8.1

**Comment by lauriejim** [comment]
Hello @shivaji !
But the message you got is also correct for me.
When you try signin, we first check if you are able or not (is your account confirmed)
If **NO** we don't need to check your password because in any case (right password or not), you will not be able to access cause you are not confirmed.
If **YES**, in this case, we check if the username/password is correct.

**Comment by derrickmehaffy** [comment]
And indeed the process that @lauriejim described is a good one. It prevents possible brute Force on u confirmed users.

**Comment by veitbjarsch** [comment]
I don't know the opposite is also it leaks user informations (unconfirmed account) to the public without knowing the password. The brute force can still be applied on confirmed account. And what will you achieve, if you brute force an unconfirmed account correctly? It will also stop you afterwards with the same confirmation error response.

**Comment by derrickmehaffy** [comment]
@veitbjarsch there is also a rate limit applied to wrong password requests
