### ISSUE TITLE
Can't visit http://localhost:1337/admin 

### ISSUE THREAD

**Issue by nycat** [strapi/strapi#4135]
## Eviroment
- npm: 6.11.3
- node: v10.16.3
- os: macbook os 10.14.6
- MySQL: mysql 8.x

## steps;
- npx strapi-create-app my-project --dev
After several steps, the database.json looks like this

> "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "database": "cms",
        "host": "127.0.0.1",
        "port": 3306,
        "username": "account name",
        "password": "password"
      },

## Problem
http://localhost:1337/admin path shows the same page with http://localhost:1337

**Comment by pouyamiralayi** [comment]
hi @nycat! did you run `` npm run build`` ? this command will build the admin for you.
cheers.

**Comment by derrickmehaffy** [comment]
@nycat @pouyamiralayi is correct you need to build.
`strapi built`
`npm run build`
`yarn build`

**Comment by derrickmehaffy** [comment]
Also --dev is no longer a valid option that was from Alpha versions which is no longer supported

**Comment by james-julius** [comment]
This is pretty old but for futurer users I had this same problem  and needed to ensure that host and port were properly set in the config/server.js file. It had defaulted to using LAN without this.

```
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337)
```
