### ISSUE TITLE
Cannot remove default value for number type in group

### ISSUE THREAD

**Issue by rmaroun** [strapi/strapi#4138]
**Describe the bug**
I created a group with number fields. I am setting the number fields default value and saving the group. When editing the number fields of that group and resetting their default value to an empty value I am then getting the following error message when saving the group: default must be a `number` type, but the final value was: `""`

**Steps to reproduce the behavior**
1. Go to Content manager and create a group with some number fields
2. Give a default value for those number fields and save the group
3. Edit that same group and remove the default value of one of the number fields and save the group
4. See error (xxxxdefault must be a `number` type, but the final value was: `""`)

**Expected behavior**
Group should be saving with empty default value for number field

**Screenshots**
![image](https://user-images.githubusercontent.com/4890827/65828228-d7816a80-e298-11e9-87ef-02958607cfd5.png)

**System**
- Node.js version: v12
- Strapi version: beta.16.5
- Database: Mongodb 4.0.6

**Comment by lauriejim** [comment]
Hello @rmaroun ! 
You are right! Thank you for reporting this issue.

**Comment by NerdyLuffy** [comment]
@lauriejim I believe the present issue can be closed

**Comment by rmaroun** [comment]
Solved
