### ISSUE TITLE
Enumeration is listed as ID in the Listing Screen 

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4142]
**Describe the bug**
Enumeration is listed as ID in the Listing Screen instead of Title or Name

**Steps to reproduce the behavior**
1. Add a Content Type "Page"
2. Create a Enumeration "Category" & and add "News" & "Movies"
3. Add a Data on Article under Category News
4. Go to Article - Listing screen and and Category is listed as ID instead of News

**Expected behavior**
Category to be listed as News instead of System generated ID

**Screenshots**
![page](https://user-images.githubusercontent.com/2913281/65863815-7b990d80-e38e-11e9-8fa6-64959b2e416a.png)

**Code snippets**
NA

**System**
- Node.js version:  v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.16.6
- Database:Mongo
- Operating system:Ubuntu 18

**Additional context**

**Comment by derrickmehaffy** [comment]
Can you please provide your model settings file? Enumeration values aren't relations so this literally shouldn't be possible.

**Comment by sunithakarthikeyan** [comment]
{
  "connection": "default",
  "collectionName": "page",
  "info": {
    "name": "page",
    "description": ""
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "Title": {
      "type": "string"
    },
    "Latest_News": {
      "group": "slots",
      "type": "group"
    },
    "review": {
      "group": "slots",
      "type": "group"
    },
    "gallery": {
      "group": "slots",
      "type": "group"
    },
    "Buzz": {
      "group": "slots",
      "type": "group"
    },
    "LatestNews": {
      "group": "simple_slot",
      "repeatable": true,
      "type": "group"
    },
    "More_Reviews": {
      "group": "simple_slot",
      "repeatable": true,
      "type": "group"
    },
    "Upcoming_Movies": {
      "group": "simple_slot_with_image",
      "repeatable": true,
      "type": "group"
    },
    "More_Galleries": {
      "group": "simple_slot_with_image",
      "repeatable": true,
      "type": "group"
    },
    "FOD": {
      "group": "fod",
      "repeatable": true,
      "type": "group"
    },
    "channel": {
      "enum": [
        "News",
        "Finance",
        "Movies",
        "Sports"
      ],
      "type": "enumeration"
    },
    "category": {
      "enum": [
        "HomePage",
        "Kollywood",
        "Bollywood"
      ],
      "type": "enumeration"
    }
  }
}

**Comment by derrickmehaffy** [comment]
Glad to hear it, marking as closed then
