### ISSUE TITLE
TypeError: Cannot read property 'users' of null. Fresh project with MongoDB

### ISSUE THREAD

**Issue by brijmcq** [strapi/strapi#4143]
**Describe the bug**
Newly created strapi with mongoDB giving me errors when going to the admin dashboard.
```
GET /content-type-builder/autoReload (6 ms)
TypeError: Cannot read property 'users' of null
    at init (/home/bri/code/strapi/test/plugins/users-permissions/controllers/UsersPermissions.js:136:42)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Steps to reproduce the behavior**
1. create a new project with mongoDB. Just follow this guide https://strapi.io/documentation/3.0.0-alpha.x/guides/databases.html#mongodb-installation

**Screenshots**
- **uses-permissions_permission**
all the rows here have values in `role` column
![image](https://user-images.githubusercontent.com/13441420/65877818-2a554200-e3bf-11e9-8d52-fef492f636cd.png)

- **users-permissions_role**
![image](https://user-images.githubusercontent.com/13441420/65877858-3ccf7b80-e3bf-11e9-92cc-9014ef32c889.png)

**Code snippets**
No code changes.

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: mongoDB
- Operating system: ubuntu 18

**Additional context**
I was able to run it using the quickstart. But when I tried to use the mongoDB option, it's not working.

**Comment by lauriejim** [comment]
Hello!
This issue has been fixed in the `16.6`.
Can you delete the `users-permissions-*` collections in your atlas database and restart your app.
It should work.

**Comment by Saad-Abbasi** [comment]
I am facing the same with online MongoDB Atlas

**Comment by derrickmehaffy** [comment]
@Saad-Abbasi can you please open up a new bug report as this one is from almost a year ago.
