### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#4148]
**Describe the bug**
The validation of 2 entities existing from beta.15 broke.
I can’t repeat on new ones. :(
Swears on a date if it is not filled. The date not required.
If the date is filled, then other errors are normally output.

![image](https://user-images.githubusercontent.com/16899697/65896841-f8f16c00-e3e8-11e9-8d66-1701563f4c54.png)

![image](https://user-images.githubusercontent.com/16899697/65896883-0c043c00-e3e9-11e9-9328-201d9300aa57.png)

System
Node.js version: 10.16.3
NPM version:6.9.0
Strapi version:3.0.0-beta.16 - 3.0.0-beta.16.6 
Database: MongoDB
Operating system: Windows WSL, Ubuntu 18.08

**Comment by vlad320** [comment]
I was able to overcome the problem myself.

There was the following auto-generated .settings.json

    "dateStart": {
      "type": "date",
      "default": ""
    },

I deleted the "default": "" and it worked.

But just to leave it here, perhaps you need to update the description of migrations from version 15 to 16.

**Comment by soupette** [comment]
The issue has been fixed in the latest beta can you upgrade your app?
After upgrading your app you need to run `strapi build`.
