### ISSUE TITLE
Max File Size not being considered - Upload Plugin

### ISSUE THREAD

**Issue by jsonpj3wt** [strapi/strapi#4156]
Going into the plugin settings for Upload and setting the Max File Size to something later than 209715 MB (like an MP4), `incoming_form.js` will reject the file for exceeding the file size. 

**Steps to reproduce the behavior**
1. Go to Plugins
2. Go to the configuration for Files Upload
3. Set the Max File Size to 350000 and Save
4. Attempt to upload a file that is larger than 209715 MB. See error

**Expected behavior**
The file should upload.

**Code snippets**
Within `incoming_form.js`:
The constructor is taking `opts`, however, it is always null.
`this.maxFileSize = opts.maxFileSize || 200 * 1024 * 1024; //Defaults to OR case`
The error is thrown here:
```
part.on('data', function(buffer) {
    self._fileSize += buffer.length;
    if (self._fileSize > self.maxFileSize) {
      self._error(new Error('maxFileSize exceeded, received '+self._fileSize+' bytes of file data'));
      return;
    }
    if (buffer.length == 0) {
      return;
    }
    self.pause();
    file.write(buffer, function() {
      self.resume();
    });
  });
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.6
- Database: Mongo - Atlas
- Operating system: MacOS v10.14.6

**Comment by lauriejim** [comment]
Hello @jsonpj3wt !
Can you precise the way you use to upload your file please.

**Comment by jsonpj3wt** [comment]
@lauriejim this is through the multi-part form upload as documented but also through the upload plugin itself (via the UI or component type upload).

Here is the code we are using from a .net core app:
```
MultipartFormDataContent imageUploadData = new MultipartFormDataContent();
using (StreamContent streamContent = new StreamContent(stream)) {
    streamContent.Headers.Add("Content-Type", mimeType);
    imageUploadData.Add(streamContent, "files", $"{fileName}");
    imageUploadData.Add(new StringContent(refId), "refId");
    imageUploadData.Add(new StringContent(STRAPI_UPLOAD_FIELD), "field");
    imageUploadData.Add(new StringContent("page"), "ref");

    using (HttpClient httpClient = new HttpClient()) {
         httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {jwt}");
         var result = await httpClient.PostAsync($"{STRAPI_DOMAIN}upload", multipart);
         bool currentFilePosted = result.StatusCode == System.Net.HttpStatusCode.OK;
         return currentFilePosted;
      }
```

**Comment by lauriejim** [comment]
Hum this still not really clear for me.
`incoming_form.js` is not a strapi file. So what is this file in your application?
It's a `js` file and you sent me a `.net` code so I don't understand (and I'm not a `.net` developer so I will no be able to help you on this part)

**Comment by jsonpj3wt** [comment]
@lauriejim It does the same thing no matter the language or just using the Strapi Upload Plugin UI.  The problem is if you try to upload a large file (download something like an mp4), the upload will fail.  It is not accounting for the size set on the upload plugin and failing at that location.  So either the npm package used in upload is the problem (which it could be) or passing in the options to that tool is preventing large files from being uploaded.

**Comment by lauriejim** [comment]
And what is the error message you have?

**Comment by jsonpj3wt** [comment]
@lauriejim the result is a 500.  Debugging, the response is `'maxFileSize exceeded, received 20010241024 bytes of file data'`

**Comment by lauriejim** [comment]
Okay are you having a NGINX?
If yes, make sure the your configuration allow you to upload large files.

**Comment by jsonpj3wt** [comment]
This is hosted via ECS/Fargate but I will check the configurations on it as well.  Since this happens locally, I can check that too.  Thanks!

**Comment by jsonpj3wt** [comment]
Changing settings did not help and the error happens running locally too :(
