### ISSUE TITLE
Question: Master-Detail document

### ISSUE THREAD

**Issue by coooolers** [strapi/strapi#4157]
Hi

Is it possible to create a master-detail document meaning for the "master" data (comprising of few fields) there can exist "many" records in the "detail" data i.e. a document that supports 1-N?

If not, how can I achieve this? Any hints please.

With Regards
Raman

**Comment by coooolers** [comment]
One more question.. I am looking forward to create a small ERP like solution. It is basically a 

Is it possible to develop it using Strapi? If yes, could anybody guide me how to  proceed?

**Comment by lauriejim** [comment]
Hello @coooolers ! 
Thank you to be interested by strapi!

Can you please join the [Community Slack](https://slack.strapi.io) for this kind of question.
You will have a fast answer to your questions.
We try to have only issues report on GitHub.

And checkout the Group feature.
