### ISSUE TITLE
Image are not lockable in the content type builder

### ISSUE THREAD

**Issue by veitbjarsch** [strapi/strapi#4164]
**Describe the bug**
A linked Image isn't lockable (configurable: false).

**Steps to reproduce the behavior**
1. Install latest beta version
2. create a new content type and add an image field via the UI 
3. Lock the field/ set configurable to false
4. Refresh the Content Manager and check the filed. The edit button is still visible. No lock sign

**Expected behavior**
Image entry should not be editable. 

**Screenshots**
<img width="1024" alt="Screenshot 2019-10-02 at 11 59 06" src="https://user-images.githubusercontent.com/12811012/66035819-2420ac00-e50c-11e9-9861-b4d37bd880bb.png">
**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.16.0
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.16.7
- Database: sqllite
- Operating system: mac os (latest)

**Comment by lauriejim** [comment]
Hello @veitbjarsch !
Thank you for reporting this issue.
I think a condition for polymorphic relations doesn't work in the admin panel.
