### ISSUE TITLE
afterCreate() being called twice when using Groups Field

### ISSUE THREAD

**Issue by puzzledbytheweb** [strapi/strapi#4166]
**Describe the bug**
Hi all.  When creating a new document with a group field, the lifecycle callback  afterCreate/afterSave runs twice. The first time it returns the result object with the group field as 'null'. The second time, it returns with the group field populated with the respective id. 

**Steps to reproduce the behavior**
1. Create a content type with a group field.
2. Add afterCreate in the /api/contentType/model/ContentType.js
3. Console.log the result parameter.

**Expected behavior**
AfterCreate should be trigger only once, when creating the ContentType.

**System**
- Node.js: v10.15.1
- NPM version: 6.10.3
- Strapi version:  3.0.0-beta.16
- Database: mongoDB
- Operating system: Windows 10

**Comment by rubilva** [comment]
I'm having the same problem...

**Comment by derrickmehaffy** [comment]
Closing as related to: https://github.com/strapi/strapi/issues/1443

Currently lifecycles are considered "broken" until the new DBAL layer is done.

**Comment by cpres** [comment]
I was getting this double lifecycle event for my afterUpdate, and then I found out only one of them carries the attribute message, so making a conditional like so worked for my code:
```  
afterUpdate: async (model, attrs, options) => {
    if (attrs.message && attrs.message.hashedName) {
      let {_id} = model._conditions
      sendPushNotification(_id)
    }
  },
```
