### ISSUE TITLE
Graphql query variables with where clause are not respected

### ISSUE THREAD

**Issue by daehruoydeef** [strapi/strapi#4168]
**Describe the bug**
Graphql query variables with where clause are not respected, instead of returning the searched Item, the whole list is returned

**Steps to reproduce the behavior**
1. query with variables and where clause
2. query without variables and where clause

**Expected behavior**
returns the selected search result like without variables

**Code snippets**
```
query($title: String!) {
  questions(where: {title: $title}) {title}
}

returns:

{
  "data": {
    "questions": [
      {
        "title": "Early Birds"
      },
      {
        "title": "Night Owl"
      },
    ]
  }
}

VARIABLES: 
{
  "title": "Night Owl"
}
```

However If i enter the where clause directly without the variables like

```
query {
  questions(where: {title: "Night Owl"}) {title}
}

returns 
{
  "data": {
    "questions": [
      {
        "title": "Night Owl"
      },
    ]
  }
}
```

**System**
- Node.js version: v10
- NPM version: 6.11.3
- Strapi version: 16.9
- Database: Mongo
- Operating system: Ubuntu 16.10

**Comment by derrickmehaffy** [comment]
```
query($where: JSON!) {
  questions(where: $where) {title}
}

VARIABLES: 
{
  "where": {
    "title": "Night Owl"
  }
}
```

The entire where json structure has to be defined before hand, you should construct this and pass it as a variable itself and not inside the Query. This is not a Strapi thing but an upstream GraphQL change.

As such marking the bug as closed as this is intended function.
