### ISSUE TITLE
No attachments in strapi-provider-email-sendmail

### ISSUE THREAD

**Issue by Lajcik007** [strapi/strapi#4174]
**Describe the bug**
While using email plugin with "strapi-provider-email-sendmail" no attachments are added to sent email

**Steps to reproduce the behavior**
1. Install latest beta version
2. Try to send email with attachment via email plugin
3. No errors are displayed
4. Email is sent, but no attachments are included

**Expected behavior**
Attachments included to sent email.

**System**
- Node.js version:  v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.14.3
- Database: mongoDB
- Operating system: linux mint

**Comment by lauriejim** [comment]
Can you give us more detail please. We can't help you with this informations.
We need a code.
The step `2.` is not clear.
