### ISSUE TITLE
Hidden Fields to be introduced in Content Type

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4180]
**Describe the topic**
Hidden Fields to be introduced in Content Type for not listing in the Edit Screen

**Your suggestions for this topic**
Reason : Example We would like to keep some fields in the Model , Example : Recipe Content Type , Version , SeoURL , These fields are not maintained by user. Hence they can be hidden in the Edit Screen.
**Screenshots**
NA

**Code snippets**
NA

**Additional context**
NA

**Comment by lauriejim** [comment]
Hello! It's already possible to customize the displayed layout to hide fields.
Here is an example in [video 📺](https://www.loom.com/share/791d3b6041914f43a368aa31657f9bcd)

**Comment by richardevcom** [comment]
> 
> 
> Hello! It's already possible to customize the displayed layout to hide fields.
> Here is an example in [video 📺](https://www.loom.com/share/791d3b6041914f43a368aa31657f9bcd)

Is there a way to do this dinamically - for example - creating (select dropdown) listing field with options and by clicking on any option, the fields either fade out/hide or fade in/show? Trying to build page templating solution similar to what WordPress has.

**Comment by lauriejim** [comment]
Ho okay - conditional stuff based on select value.
There is now way to do that by default in Strapi.
After that you can try to develop it by customizing the admin panel of the content manager using this [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html)
