### ISSUE TITLE
File Upload API image url is wrong when using S3

### ISSUE THREAD

**Issue by arnoldgamboa** [strapi/strapi#4182]
**Describe the bug**
File Upload API image url is wrong when using S3. It still has the localhost URL, however s3 has it's own URL and doesn't need the localhost url be appended

**Steps to reproduce the behavior**
1. Activate S3 as your File Upload source
2. Upload a file
3. Check the details of the file via API, ie. `/upload/files/2`
4. See the `url` key.

**Expected behavior**
`url` key should not append `localhost` url if the source is other than local ie. s3.

**Screenshots**
![mow-api-www_jbcx0ghd0_at_d2c_io_upload_files_1](https://user-images.githubusercontent.com/587603/66189973-8e2c8300-e6bd-11e9-8f6a-0d29b96586b3.jpg)

**System**
- Node.js version: v10.15.3
- NPM version: v6.4.1
- Strapi version: beta 16
- Database: MySQL
- Operating system: Mac OS

**Comment by FailedSitcom** [comment]
I believe this is a bug, and will open a pull request shortly to resolve the issue.

**Comment by FailedSitcom** [comment]
Here is the pull request I created that I believe resolves this issue: https://github.com/strapi/strapi/pull/4191

**Comment by lauriejim** [comment]
The fix is merged on `master`. 
Stay tuned for the next release of strapi.

**Comment by lauriejim** [comment]
and thank you for this repport! Appreciated 👍
