### ISSUE TITLE
Repeatable Groups - How to post via API ?

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4183]
**Describe the topic**
I have a Model where Group is one of the Field. From UI its working fine . How to post the same via API

**Your suggestions for this topic**
NA
**Screenshots**
NA
**Code snippets**
Model
{
  "connection": "default",
  "collectionName": "article",
  "info": {
    "name": "article",
    "description": ""
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "Title": {
      "type": "string"
    },
   
    "DependentItems": {
      "group": "dependent_item",
      "repeatable": true,
      "type": "group"
    }
  }
}

Group Settings Files 
{
  "info": {
    "name": "DependentItem",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_dependent_items",
  "attributes": {
    "ImageName": {
      "type": "string"
    },
    "ShowcaseArea": {
      "enum": [
        "Listing",
        "Landing"
      ],
      "type": "enumeration"
    },
    "Description": {
      "type": "text"
    },
    "image": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }
  }
}
**Additional context**
We need this to migrate the existing articles to this new format

**Comment by alhill** [comment]
In POST body send an array of objects as value of the repeatable group field. As simple as it sounds ;)
```
{
  field1: "value1",
  field2: "value2",
  repeatableGroupField: [
    {
      groupField1: "valueGroupField1",
      groupField2: "valueGroupField2"
    }
  ]
}
```

**Comment by sunithakarthikeyan** [comment]
Thanks Its working

**Comment by lauriejim** [comment]
@sunithakarthikeyan Can you please, next time, well format you JSON and follow the issue template.
I'm trying to keep the GitHub issues clean, readable and understandable.
I'm pretty sure you can understand.
If it's not respected, I will close your issue.
Thank you.
https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
