### ISSUE TITLE
Strapi GraphQL query: “start” argument wouldn't work

### ISSUE THREAD

**Issue by amitschandillia** [strapi/strapi#4184]
**Describe the topic**
There _seems to be_ a bug in the **Users-Permissions - User** models. When executing the query, the model seems to be ignoring the `start` argument even though it's available in query documentation.

**Your suggestions for this topic**
Suggest fix the bug or point in the right direction in case something is missing in my code.

**Screenshots**
Here's what's returned when query is run with no arguments:
![no-args](https://user-images.githubusercontent.com/42805381/66195040-6e905d00-e6b3-11e9-815f-5875f70f87b6.jpg)
It returns all 3 users, i.e. `Arnold`, `Bill`, and `Vin`. As expected.

With `start: 0, limit: 1`:
![start-0-lim-1](https://user-images.githubusercontent.com/42805381/66195175-b31bf880-e6b3-11e9-9310-f626dcba554a.jpg)
This time it returns `Arnold`, also as expected since it's the 0th item in the collection.

But with `start: 1, limit 1`:
![start-1-lim-1](https://user-images.githubusercontent.com/42805381/66195283-eeb6c280-e6b3-11e9-92bf-71c8bc6a0230.jpg)
You see, it still returns `Arnold` which is unexpected since I've asked for the 1st item this time, i.e. `Bill`.

**Code snippets**
Not tweaked any relevant code yet.

**Additional context**
I'm using **Strapi v3.0.0-alpha26.2** on **Node v10.16.0**.

**Comment by lauriejim** [comment]
I close this issue.
Please refer to the discussion on this [StackOverflow question](https://stackoverflow.com/questions/58231310/strapi-graphql-query-start-argument-wouldnt-work)
