### ISSUE TITLE
Allow content items to be reorderable, allow content to have 'Is reorderable' flag in content type builder

### ISSUE THREAD

**Issue by kgrosvenor** [strapi/strapi#4186]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

**Comment by lauriejim** [comment]
Can you please submit this feature request here https://portal.productboard.com/strapi
Thank you for your time @kgrosvenor !
