### ISSUE TITLE
ctx is not defined for queries made using GraphQL for users-permissions

### ISSUE THREAD

**Issue by baldeepsinghkwatra** [strapi/strapi#4193]
**Describe the bug**
This function inside (strapi-plugin-users-permissions/controllers/UsersPermissions.js)
```
 async getRoles(ctx) {
    try {
      const roles = await strapi.plugins[
        'users-permissions'
      ].services.userspermissions.getRoles();
      ctx.send({ roles });
    } catch (err) {
      ctx.badRequest(null, [{ messages: [{ id: 'Not found' }] }]);
    }
  },
```

**Steps to reproduce the behavior**
When invoked via graphql query ({roles(start:0,limit:20){id name description}})
**ctx is not defined when invoked via graphql**
{
  "errors": [
    {
      "message": "Cannot read property 'badRequest' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "roles"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'badRequest' of undefined",}]

**Expected behavior**
It should work as it did it in previous versions. **Happened after updating to 3.0.0-beta.16.8**

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: Mongo
- Operating system: Mac / ubuntu

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/4116

And please well format your messages, your issue is not readable.

> This is a templated message
