### ISSUE TITLE
Multiple media in repeatable groups not working

### ISSUE THREAD

**Issue by narduin** [strapi/strapi#4205]
Hello !
I'm running into a small bug with the new group feature (which I love by the way).

**Describe the bug**
When adding multiple media files (jpg, svg, etc.) inside a repeatable group element, only one remain after saving.

**Steps to reproduce the behavior**
1. Create a _group_
2. Add an _image field_ and check "allow multiple files"
3. Use the group inside a _content type_ and make it repeatable
4. Add multiple files to the media field
5. Save
6. Go back to see only one image inside the group (or query the images to see only one response)

**Expected behavior**
All the media files should be saved inside the group.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.16.8
- Database: sqlite
- Operating system: MacOS 10.14.6

**Additional context**
Multiple media files is working fine on media field outside the group.  
**It is working fine when the group is not repeatable.** Changing this setting after uploading multiple files to a non repeatable group makes the next entries bug but not the first.

Thanks a lot!

**Comment by lauriejim** [comment]
Thank you @narduin for reporting this issue!

**Comment by nathanlentz** [comment]
I'll give this bug a whirl!

**Comment by FilipeCovas** [comment]
@lauriejim @nathanlentz Hi, I have a project in progress and I need this feature, what is the date to fix this bug? thanks guys

**Comment by derrickmehaffy** [comment]
No update yet @FilipeCovas, when there is one you will see a PR linked to this issue. Do feel free to dig into it yourself also, anyone can submit a PR :wink:
