### ISSUE TITLE
Unable to login in admin when parser middleware is disabled

### ISSUE THREAD

**Issue by denisinvader** [strapi/strapi#4212]
**Describe the bug**
When `parser` middleware is disabled I can't log in into the admin interface.

**Steps to reproduce the behavior**
1. In the file `config/environments/[development]/request.json` change `parser.enabled` to `false`
2. Try to log in as admin

**Expected behavior**
I successfully logged in the admin interface

**Code snippets**
Error message:
```
TypeError: Cannot read property 'identifier' of undefined
    at callback (/usr/src/api/app/plugins/users-permissions/controllers/Auth.js:32:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**System**
- Node.js version: v11
- NPM version:
- Strapi version: 3.0.0-alpha.26.2
- Database: mongo
- Operating system: OSX (official strapi Docker image)

**Additional context**
I disabled default parser because I need a raw request body for cryptography. I've tried to set `includeUnparsed` option to `true` in `config/environments/.../request` but `ctx.request.body[Symbol.for('unparsedBody')]` is `undefined` [docs](https://github.com/dlau/koa-body#a-note-about-unparsed-request-bodies). So I disabled this middleware and parse body right in the custom controller. If somebody could suggest a better solution it would be fine.

Now the plugin excepts that parser middleware is enabled [source](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L23)

**Comment by lauriejim** [comment]
Hello @denisinvader !
If you disable the parser middleware, the request is not parsed so you can't have access to the request data.
Please check the Koa documentation if you want more information.
Here is the [middleware code](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/parser/index.js).
And for your information, the logic that manage the admin authentication is not in the **Users & Permissions** plugin. It's in the `strapi-admin` package. There is an **Auth** controller.
Here is a [blog article](https://strapi.io/blog/why-we-split-the-management-of-the-admin-users-and-end-users) that explain the split.

**Comment by DipeshMaywade** [comment]
can i remove the login signup process for super admin in strapi? if yes then how ?
