### ISSUE TITLE
Audit Log Viewer on Strapi?

### ISSUE THREAD

**Issue by cderick** [strapi/strapi#4215]
## Bug description
There's a place to check all update logs? I search in the documentation but not able to find nothing regarding an Audit Log Viewer. Currently you can filter the last time updated but not the last person that changed or a log of those changes.

## Steps to reproduce the behavior
1. Go to: Everywhere in Strapi and could not find.
2. Click in: Everywhere to find the audit log.

## Expected behavior
Somewhere in the content manager or content type, user be able to see all the update logs by content type: User that modified, Last time that was update, etc...

## System
- Node.js version: v12.11.1
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.16.8
- Database: Sqlite
- Operating system: MAC OS Mojave

@derrickmehaffy Updated

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by cderick** [comment]
@derrickmehaffy can you reopen my issue?

**Comment by derrickmehaffy** [comment]
@cderick Reopened but just an FYI no I don't think there is an audit log at all related to this. Most likely this would be a feature request but it is probably something you would need to implement yourself. I'm only opening it back up to see if anyone on the Strapi team have suggestions.

**Comment by lauriejim** [comment]
Hello! This request is really similar to this one https://github.com/strapi/strapi/issues/3195

If you want this feature, I suggest you create a middleware in your application.
(search middleware in the doc, I won't send you a link because the doc structure will change soon.)
and in this middleware add your custom logic to store / of stream on an other service, the request data / url / authenticated user.

**Comment by abbeyseto** [comment]
This might help someone to create an Audit trail using strapi middleware. https://medium.com/@adenleabbey/audit-log-trail-with-strapi-74f6bdf70daf

**Comment by lauriejim** [comment]
Thank you for this article 🚀

**Comment by TasosBak** [comment]
> This might help someone to create an Audit trail using strapi middleware. https://medium.com/@adenleabbey/audit-log-trail-with-strapi-74f6bdf70daf

Is this still relevant guys?

**Comment by derrickmehaffy** [comment]
@TasosBak it should still be fairly relevant, I can't guarantee the entire content or if anything within the Strapi structure has changed but functionally it should still work I believe.

**Comment by TasosBak** [comment]
@derrickmehaffy I found that for some reason, the project works only after I remove JSON.stringify from lines 74 and 107 from [this gist](https://gist.github.com/abbeyseto/17e785650d468493bc8cdac4395b5329#file-strapi-middleware-full). I'm fine by it, just letting anyone interested know.

**Comment by biapar** [comment]
Audit log is a requisite for GDPR

**Comment by teraflops-droid** [comment]
Guys, I followed the steps in this link [](https://medium.com/@adenleabbey/audit-log-trail-with-strapi-74f6bdf70daf) but found no log in the terminal of anywhere else
