### ISSUE TITLE
Poor display of the administrative panel on small screens

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#4216]
Good afternoon, unfortunately not all hull hd monitors yet and I was approached with the following problem.

As I understand it, the stapi has problems with the display, especially on the mobile version, so the question is, will there be an improvement in adaptive display?

![image](https://user-images.githubusercontent.com/16899697/66442243-5e92c780-ea7d-11e9-862b-0793592f0108.png)

![image](https://user-images.githubusercontent.com/16899697/66442262-6d797a00-ea7d-11e9-9910-ac2b0e387c36.png)

![image](https://user-images.githubusercontent.com/16899697/66442353-ccd78a00-ea7d-11e9-98a6-5d8881ec4ecc.png)

Strapi: 3.0.0-beta.16.6

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
