### ISSUE TITLE
send out email with default providers with attachments

### ISSUE THREAD

**Issue by sunsgs** [strapi/strapi#4218]
**Describe the topic**
I would like to send out email with default providers with attachments

**Your suggestions for this topic**
I can see from the code that there is the possibility to do it but i don't know how

Can you please provide any clue?

Thanks

**Comment by lauriejim** [comment]
Hello! The attachment in the default email provider has been added 6 days ago, so it's not released yet.
The next release will be next week. 
Stay tuned.
