### ISSUE TITLE
Something went wrong in the model `File` with the attribute `related`

### ISSUE THREAD

**Issue by a-klimashevsky** [strapi/strapi#4220]
**Describe the bug**

**Steps to reproduce the behavior**
1. Setup str.api with sqlite db (ok)
2. change database connection to mongodb
3. execute strapi start
4. command exit with code 1 and follow stack

corp-cms         | [2019-10-09T14:26:40.130Z] error Something went wrong in the model `File` with the attribute `related`
corp-cms         | [2019-10-09T14:26:40.131Z] error TypeError: Cannot convert undefined or null to object
corp-cms         |     at Function.keys (<anonymous>)
corp-cms         |     at Object.defineAssociations (/cms/node_modules/strapi-hook-mongoose/node_modules/strapi-utils/lib/models.js:498:34)
corp-cms         |     at buildRelation (/cms/node_modules/strapi-hook-mongoose/lib/mount-models.js:428:15)
corp-cms         |     at relationalAttributes.forEach.name (/cms/node_modules/strapi-hook-mongoose/lib/mount-models.js:74:7)
corp-cms         |     at Array.forEach (<anonymous>)
corp-cms         |     at Object.keys.map.model (/cms/node_modules/strapi-hook-mongoose/lib/mount-models.js:73:26)
corp-cms         |     at Array.map (<anonymous>)
corp-cms         |     at module.exports (/cms/node_modules/strapi-hook-mongoose/lib/mount-models.js:14:23)
corp-cms         |     at Promise.all.Object.keys.map.name (/cms/node_modules/strapi-hook-mongoose/lib/index.js:182:16)
corp-cms         |     at Array.map (<anonymous>)
corp-cms         |     at mountPlugins (/cms/node_modules/strapi-hook-mongoose/lib/index.js:180:35)
corp-cms         |     at Object.keys.filter.map (/cms/node_modules/strapi-hook-mongoose/lib/index.js:132:11)
corp-cms         |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Expected behavior**
strapi start ok

**System**
- Node.js version: dubnium
- NPM version: N/A
- Strapi version: 3.0.0-beta.1
- Database: mongodb
- Operating system: Linux

**Additional context**
File model is described in https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/models/File.settings.json

**Comment by derrickmehaffy** [comment]
```
System

Node.js version: dubnium
NPM version: N/A
Strapi version: 3.0.0-beta.1
Database: mongodb
Operating system: Linux
```

Node version: We need the actual version `node --version` and same for npm `npm --version`

Strapi beta 1 is very old the current latest is beta.16.8 please test with the current latest release

Database: we also need the mongoDB version

Operating system: What distro of linux? What version of the distro.

Please provide more information, once you have done so this can be reopened.
