### ISSUE TITLE
GraphQL breaks the build with a custom local plugin

### ISSUE THREAD

**Issue by grahamcrackers** [strapi/strapi#4224]
**Describe the bug**
When creating a local plugin that contains a custom model, installing strapi-plugin-graphql will break the build at runtime

**Steps to reproduce the behavior**
1: spin up a new strapi project `strapi new strapi-test`
2: install graphql plugin `strapi install graphql`
3: create a custom plugin `strapi generate:plugin awsome-plugin`
4: create a custom model for that plugin `strapi generate:model awsomething --plugin=awesome-plugin`
5: go to the `plugins/awesome-plugin/models/models` and move your models up a level to `plugins/awesome-plugin/models` because it creates a duplicate folder on generate (another bug i think ????)
6: try and run it `strapi develop`
7: see error
```
[2019-10-09T20:31:11.874Z] error Error: Cannot find the controller's action custommodel.findOne
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Query.js:163:16
    at Object.composeQueryResolver (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Query.js:199:7)
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Resolvers.js:331:19
    at Array.reduce (<anonymous>)
    at Object.buildShadowCRUD (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Resolvers.js:269:30)
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Schema.js:147:23
    at Array.reduce (<anonymous>)
    at Object.generateSchema (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/services/Schema.js:141:48)
    at Object.initialize (/Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at /Users/grahamcrackers/dev/tfs-svm/strapi-graphql/node_modules/strapi/lib/hooks/index.js:43:28
```

**Expected behavior**
The server should start without an error.

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: beta16.5-16.8
- Database: sqlite,mongodb
- Operating system: macOS 10.14.6

**Additional context**
This is a fresh install with no other moving parts. I've also tried to put an empty schema.graphql file that only contains `module.exports = {}` in the plugins config folder like the getstarted project in the strapi monorepo, and it still fails at runtime.

**Comment by lauriejim** [comment]
Hello @grahamcrackers !
Thank you for reporting this issue.

It's because your controller not have `find` or `findOne` functions.

```js
// Try to find the controller that should be related to this model.
const controller = isSingular
  ? _.get(controllers, `${name}.findOne`)
  : _.get(controllers, `${name}.find`);
```

To workarround you can add the following lines in your controller.

```js
findOne(ctx) {
  ctx.body = {};
},
find(ctx) {
  ctx.body = [];
},
```

About the model folder generation issue.
Here is the related issue https://github.com/strapi/strapi/issues/3694
It has been fixed on master, will be released next week.

**Comment by grahamcrackers** [comment]
Thanks @lauriejim, I was looking through the code and had a hunch that it was those lines that were tripping me up. It looks like when you run `strapi generate:model custommodel --plugin=awsesome-plugin` it doesn't generate the controller in the plugin space. 

I added a file for the plugin model, added the code snippet for `find` and `findOne` and it spun right up.

**Comment by lauriejim** [comment]
For `strapi generate:model`, as it's in the command name, it only generates model.
It's normal. If you want to generate a controller, you will have to run `strapi generate:controller`
If you want to generate all the API login, you will have to run `strapi generate:api`
