### ISSUE TITLE
Cannot create relations on group

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#4225]
**Describe the bug**
When I try to create relations in a group in the UI, I get a generic error.
```
POST /content-type-builder/groups (55 ms) 400
```

**Steps to reproduce the behavior**
1. Create a content type.
2. Create another content type
3. Relate the two content types.
4. Create a group
5. Try to relate the group to one of the content types

**Expected behavior**
I expect the relation to succed and the model to save

**Code snippets**
The group and model that I am trying to relate are below.

The content type

```
{
  "connection": "default",
  "collectionName": "Link",
  "info": {
    "name": "link",
    "description": "A URL to content."
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "title": {
      "default": "Title",
      "required": true,
      "minLength": 3,
      "maxLength": 64,
      "unique": true,
      "type": "string"
    },
    "url": {
      "minLength": 4,
      "default": "www.example.com",
      "required": true,
      "unique": true,
      "type": "string"
    },
    "mylinks": {
      "collection": "mylink",
      "via": "links"
    }
  }
}
```
And the group I am trying to create

<img width="838" alt="Screen Shot 2019-10-09 at 9 39 03 PM" src="https://user-images.githubusercontent.com/28883798/66532435-67b38100-eadd-11e9-81ed-f4e44484e627.png">

**System**
- Node.js version: v10 latest
- NPM version: 6.9
- Strapi version: Beta 16.8
- Database: MySQL 8
- Operating system: CentOS in Docker

**Comment by amartincolby** [comment]
Probably doesn't offer any other insight, but here is my console.
![image](https://user-images.githubusercontent.com/28883798/66578372-f90c0d00-eb48-11e9-9bdf-9465a6853ed8.png)

**Comment by lauriejim** [comment]
Hello @amartincolby !

Information you gave me is not enough precise to understand and reproduce correctly your steps.

**Relate the two content types.** - What is the relation type (Many-to-Many, One-to Many, ...)?

**Try to relate the group to one of the content types** - What king of relations?

I also need your content type name.

Please imagine I know nothing from what you did and I have to be stupid, follow your steps and see the error.

**Comment by amartincolby** [comment]
The relation of the two content types is many-to-many. I do not _know_ if this has any effect on the problem, but I wanted to make sure that my structure was mirrored in any testing you do.

For the failed Group relation, it doesn't matter. If I try one-to-one or one-to-many I still get the 400 error.

When you say the content type name, do you mean the group? The group is named mylinkcontent.

**Comment by amartincolby** [comment]
Update for those who are interested: Manually setting the config files allowed me to create the one-to-one relations, even though the UI continued to fail.

**Comment by amartincolby** [comment]
I will try to create a fresh Strapi instance and recreate the problem then provide the config files. Hopefully that will help more easily debug the issue.

**Comment by amartincolby** [comment]
I'm unable to replicate the problem with a fresh instance, so I'm just uploading a zip of my API and Group folders. 
[Archive.zip](https://github.com/strapi/strapi/files/3725684/Archive.zip)

**Comment by lauriejim** [comment]
All is working fine with the last version of strapi using beta.17.8 and your APIs / groups.
