### ISSUE TITLE
Domain config / routing

### ISSUE THREAD

**Issue by lkostrowski** [strapi/strapi#423]
**Node.js version**: 9.3.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.7.3
**Operating system**: Debian 9 / OSX 

Hi

I have deployed my demo-app to my VPS.
I have set my domain on `config/enviroments/production/server.js`

```
{
  "host": "my-domain.com",
  "port": 1337,
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  }
}
```

I have run my app by `NODE_ENV=production npm run start`

I can access `my-domain.com` easily and strapi is working.
When I go to `my-domain.com/admin` I get redirected to:
`http://my-domain.com/:1337/admin/plugins/users-permissions/auth/register`

Is it my fault with configuration? I have it behind nginx reverse proxy pointing :80 to localhost:1337

Thanks, great job working on it

**Comment by edimitchel** [comment]
I confirm that is problematic, I have the same issue.
I suggest to create a reverse proxy configuration that in case of the redirection is made on reverse proxy info and not on server configuration.

**Comment by edimitchel** [comment]
After tries, seems to be index.html file generated first time that hold wrong information into body attribute : 
Find in `<body front=".../:1337/admin" back=".../:1337"` in the file `admin/admin/build/index.html` and clean it : that works !
@Aurelsicoko !

**Comment by franzos** [comment]
@edimitchel thanks for this, finally gained access. I actually have to edit this file - after - the server has been started, because it's generated on every `npm start`. Aside from this bug, the documentation presents conflicting information:
Option 1) [official documentation](https://strapi.io/documentation/advanced/customize-admin.html#deployment)
Option 2) [recent commit](https://github.com/strapi/strapi/pull/397/commits/3c7efa07f819ed23be5a50324062adfd337cd0b0#diff-925b742cb88b0afdae5671aa57a18fe3)

**Comment by Aurelsicoko** [comment]
@edimitchel @franzos I'm currently working on it. We removed these attributes in production environment. More changes are coming, it's a very tricky part that involves many cases and I don't want to introduce more breaking changes so... Wish me good luck!

**Comment by edimitchel** [comment]
Good luck :four_leaf_clover: @Aurelsicoko !
May the 4th be w/ u !

**Comment by edimitchel** [comment]
I don't try [this config](https://strapi.io/documentation/advanced/customize-admin.html#with-the-plugins-on-another-server), may be a good workaround ?

**Comment by franzos** [comment]
@edimitchel have you had any success with this config? I tried to add the 'admin' section to the existing config, however it didn't have any effect, even after a full rebuild. For now, the workaround you mentioned earlier works fine - just that you need to edit `admin/admin/build/index.html` every time strapi restarts.

**Comment by Aurelsicoko** [comment]
@edimitchel @franzos @lkostrowski We made a lot of changes in the WebPack configurations (https://github.com/strapi/strapi/pull/431). You don't need to rebuild the plugins whatever the case and you only have to rebuild the admin in some cases. The documentation has also been updated. I hope it will fix the issue.

**Comment by tmvanetten** [comment]
@Aurelsicoko I am still seeing the same issue with the latest version.  I have to clean that `admin/admin/build/index.html` and then update `config/environment/dev/server.js` to my instance ip to get it working.

**Comment by edimitchel** [comment]
@tmvanetten Did you take last version of the code (from fix/deploy branch) ? 
I don't see any pull request merged.. @Aurelsicoko, you confirm ?

**Comment by Aurelsicoko** [comment]
The [PR](https://github.com/strapi/strapi/pull/431) has been merged yesterday. It should be released today.

**Comment by Aurelsicoko** [comment]
Guys (@edimitchel, @tmvanetten, @franzos @lkostrowski), can someone test with the latest version (alpha@8.3)? It should be fixed. We were able to deploy on Heroku and AWS.

**Comment by edimitchel** [comment]
It works properly!
I'll continue test but it seems to be good!

**Comment by Aurelsicoko** [comment]
Woooohoo! This one wasn't easy to fix. So many use cases to handle... Feel free to comment and reopen the issue if necessary.
