### ISSUE TITLE
The relations are very slow in admin Panel (cause auto -populate)

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#4233]
Hello!
The relationships in admin panel is very slow and sometimes give a error 
i have a lot of contents in the relation   account with images and videos 
I think It has to remove the auto-populate in the relationship at least in the too many relations
gif:
http://www.giphy.com/gifs/YOvIznkAvM2rVgRyST

**System**
- Node.js version:v10

- Strapi version: 16.8
- Database:Mysql
- Operating system:Ubuntu server

<img width="1108" alt="Captura de pantalla 2019-10-10 a las 16 25 50" src="https://user-images.githubusercontent.com/14913444/66578054-b400ce80-eb7a-11e9-810f-cb98061a3f3b.png">

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello! Can you precise `lot of contents` please.
