### ISSUE TITLE
No --watch-admin option for strapi dev

### ISSUE THREAD

**Issue by Christinaaaa** [strapi/strapi#4235]
When running `strapi develop`, `localhost:1377` cannot be reached, and `The server is restarting` repeatedly shows up in terminal.
Admin panel could be reached when running `strapi start`, but I cannot add new content type in this mode.

I am running strapi version 3.0.0-beta.16.8. 
According to doc
https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-develop-dev
there should be an option --watch-admin for strapi dev to load admin panel.
However, I tried `strapi dev -h`, and `--no-build` is the only option available. There is no option named `--watch-admin`. Just wondering how to load the admin panel when running strapi develop.

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: MongoDB db version v3.2.22
- Operating system: Ubuntu 18.04.2 LTS

**Comment by derrickmehaffy** [comment]
This will be in the next version that is releasing next week. The docs were getting updated and released before the latest features were being pushed out.

**Comment by Christinaaaa** [comment]
Is editing code the only way to create/modify content type since ContentType Builder is not available under `strapi start`?
Just wondering if there is a way to access the admin panel and do customization on the panel before the next release?

**Comment by derrickmehaffy** [comment]
@Christinaaaa the CTB is only enabled when you are in the development environment and when you use `strapi develop` / `npm run develop` / `yarn develop`

This is so that users can't accidentally take down their production application by trying to modify stuff in prod. As Strapi stores the model configs in files which require node to restart to take effect meaning if there is a problem you can knock the application offline. Also if you do any sort of clustering this would mean that one node in the cluster would have different code than the others.

**Comment by derrickmehaffy** [comment]
Just to show an example I am currently testing the WIP branch for this feature: 
![image](https://user-images.githubusercontent.com/8593673/66665010-78a9e280-ec02-11e9-8f43-b507eb00d86a.png)

**Comment by Christinaaaa** [comment]
Is that expected that `localhost:1377` page is not available when running `strapi dev` only?

**Comment by derrickmehaffy** [comment]
no? The strapi adminUI should still be there when running `strapi develop`

**Comment by Christinaaaa** [comment]
`strapi start` works as expected (admin panel available) 

but `strapi develop` is giving me this message repeatedly:
![Screenshot from 2019-10-11 12-34-20](https://user-images.githubusercontent.com/12404726/66672304-976ca100-ec23-11e9-9db5-13a95bae33bf.png)

instead of successful messages i got for `strapi start`
![Screenshot from 2019-10-11 12-38-36](https://user-images.githubusercontent.com/12404726/66672555-2679b900-ec24-11e9-92b6-2fe840383227.png)

It seems like the server cannot be started correctly when running `strapi develop`.

Not sure what the difference is between develop and start.. any setting to change?
