### ISSUE TITLE
Language change does not change UI

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#4239]
**Describe the bug**
Language change does not cause text change in application.

**Steps to reproduce the behavior**
1. Go to admin panel.
2. Click language menu in the upper-right
3. Change language
4. UI Does not update

**Expected behavior**
The UI should update to the new language

**System**
- Node.js version: v10 latest
- NPM version: 6.9
- Strapi version: Beta 16.8
- Database: MySQL
- Operating system: CentOS in Docker

**Comment by Slide109** [comment]
Faced similar problem. Langues update in Settings Manager doesn't reflect language menu options

**Comment by lauriejim** [comment]
Hello! @amartincolby !
Thank you for reporting this issue! You are right!

**More information:**
When I'm on the `login` page, I'm able to switch the language.
But after login, I'm not able to switch the language.

@Slide109 the **Language** option in the settings-manager plugin is here to manage backend i18n settings. That doesn't affect the Admin UI.

**Comment by lauriejim** [comment]
This issue is already fixed on master.
Will be released in 2/3 days.
