### ISSUE TITLE
upload file path from strapi server

### ISSUE THREAD

**Issue by obaidh** [strapi/strapi#4240]
**Describe the topic**
Hi, there I try to fix it this issue from 2 weeks everything fine only uploads file image path it's giving me the path without website URL.
Like this :
            `   "URL": "/uploads/b96d6c5bdd7f42e2b4f2e59be349d0ca.jpg",`
and I change the code on node modules under file path : 
`/…./node_modules/strapi-provider-upload-local/lib/index.js`

to like this : 
`file.url = `${strapi.config.url}/uploads/${file.hash}${file.ext}`
`
after this the image upload works fine and I get it the path like this : 
`"url": "http://localhost:1337/uploads/43ac377b05494a9fa285f011696d1ec8.jpg",
`

**Your suggestions for this topic**
I don't know what the good solution but I do something works for me 
**Screenshots**
If applicable, add screenshots to help explain your points.

**Code snippets**
file : `/…./node_modules/strapi-provider-upload-local/lib/index.js`

change from: 
file.url = `/uploads/${file.hash}${file.ext}`;
to : 
`file.url = `${strapi.config.url}/uploads/${file.hash}${file.ext}`

**Additional context**
nothing! :)

**Comment by derrickmehaffy** [comment]
@obaidh as I mentioned in slack. You can submit a pull request with your changes to be reviewed or you can fork the provider and run your own version.

For now though marking this as closed.

**Comment by maximilianofried** [comment]
Hello, how can i change the path of the upload URL without changing node_modules files, when uploading from the plugin and also when using the slate editor to add an image. it is always like '![photo](/uploads/photo.jpeg)' and i need something customised like, '![photo](mywebsite.com/uploads/photo.jpeg)' 

@derrickmehaffy 

Thank you!

**Comment by callmesoul** [comment]
@i99dev  why my `strapi.config.url = underfined`

**Comment by kirwako** [comment]
you can use this strapi plugin
that prepend public url/media prefix to your media URL in api's URL

it converts the URLs from `/uploads/thumbnail.png` to `https://example.org/uploads/thumbnail.png` just
in response without changing the relative path in database

https://www.npmjs.com/package/strapi-plugin-media-prefix
