### ISSUE TITLE
Cannot run "Developement mode" on lates beta

### ISSUE THREAD

**Issue by xaun** [strapi/strapi#4244]
**Describe the bug**
`strapi develop --watch-admin` as per https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#development-mode is throwing: 
```
error: unknown option '--watch-admin'
```

**Expected behavior**
To enable the front-end development mode.

**System**
- Node.js version: 10.2.1
- NPM version: 5.6.0
- Strapi version: 3.0.0-beta.16.8
- Database: postgresql
- Operating system: macos

**Additional context**

Im hoping to be able to fully customise the admin UI - is this possible? Not finding any guides / tutorials on this online and the docs are very minimal. 

For example, Ideally I want to create my own react component(s) for each content type page.

**Comment by soupette** [comment]
@xaun the documentation has been released before the new version. It will be released this week.
If you really need this feature you can use the `@next` tag but this release has not been fully tested yet.

**Comment by xaun** [comment]
@soupette thanks. Where can I see a list of [customisable plugins](https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#customization) ? I'm a bit lost as to what to create in `./admin` to get my desired results.

**Comment by soupette** [comment]
All plugins are customisable since we replace their associated files.
Here's where  [the plugins are required](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/plugins.js). 
What are you trying to modify?

**Comment by xaun** [comment]
@soupette Oh actually, I don't need to modify the plug pages (at this stage). I need to modify the "Content Type" pages. Is this possible?

**Comment by soupette** [comment]
Yes it is possible [here are all the font-end files you can modify](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-type-builder/admin) in this plugin.
