### ISSUE TITLE
Text Escaping Issue

### ISSUE THREAD

**Issue by mario-riff** [strapi/strapi#4253]
Node: v10.15.3
NPM: v6.4.1
Strapi: Strapi v3.0.0-alpha.26.2
Database: AWS RDS PostgreSQL

We are experiencing an issue where any text that resembles json that is saved via the CMS backend is being escaped and converted. To recreate this issue simply enter the text '["Test"]' into a String or Text field, and after saving the text is converted to '{"Test"}'.

In addition we have json data which is an array of objects, and that text is being escaped and converted when saved. Enter the text '[{"test":"value"}]' which will become '{"{\"test\":\"value\"}"}' when saved.

The expected behavior is that no matter what text we add to a Text or String field, it should remain the same and unmodified after saving the record.

We tried to use the json data type, but it was not compatible with our PostgreSQL database, and we could not get it to work. As a result, we've tried to use Text fields to store our json data, but it's being escaped when the record is saved in the database. Again, we're able to retrieve and save the data just fine via the API calls, and this issue is specific to saving records via the backend. Any information regarding this issue would be appreciated as it's causing large problems in our production environment.

**Comment by derrickmehaffy** [comment]
@mario-riff please note the alpha version is no longer supported, I suggested you try with a fresh beta project.

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello @mario-riff !
This issue is fixed in the last version of Strapi (beta.16.8)
I suggest you update your application by following migration guides that are in the documentation.
