### ISSUE TITLE
Can't login to strapi, Internal Server Error

### ISSUE THREAD

**Issue by lanceliamll** [strapi/strapi#4256]
Hi guys, why i can't login to strapi? Says internal server error, i tried so many times but still wont.

In the create-react-app, my api's were not working, but on the postman it is, but before this issue came. i had changed the cors domain thing from "*" to some config. Please help asap.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
@lanceliamll the alpha version is no longer supported, please test with the latest beta version.

**Comment by lanceliamll** [comment]
@derrickmehaffy  btw, the strapi is working earlier, and its up on the cloud. and suddenly i had changed the CORS Domain, how can i undo that? or do you have any way to bypass that.

**Comment by derrickmehaffy** [comment]
@lanceliamll I'll offer you this since you are newer to the project, the config is stored in `config/environments/production/security.json` but please do keep in mind the alpha was depreciated and support discontinued.

**Comment by lanceliamll** [comment]
@derrickmehaffy  huhu u saved my life sir. Thank you so much. I will be more succint and careful next time
