### ISSUE TITLE
Cannot read property 'globalId' of undefined when updating `User` collection with a media ID payload

### ISSUE THREAD

**Issue by iamacatperson** [strapi/strapi#4259]
**Describe the bug**
Unable to do an `updateUser` mutation that contains a media type payload (using the media's ID). Returns "Bad Request" error: Cannot read property 'globalId' of undefined.

**Steps to reproduce the behavior**
1. Under `User` collection, create a Content-Type "media" (e.g. logo).
2. Upload a logo using `/upload` endpoint (only providing the "file" param). Will receive the logo's ID as a response.
2. Do an `updateUser` graphql mutation passing the above logo's upload ID as an `input` parameter.

Example:

```
input: {
   data: {
      // ..other payload
      logo: "5da5de7e5ed46450e1998bd2" 
   },
   where: {
            id: userId
   }
}
```

**Additional context**
When I do an `updateUser` mutation without including the "logo" payload above (since my "User" collection has other content types), it's successful. Only when I add the "logo" payload does an error occur.

I am also using the same method for the other collections (for uploading media) and they are fine. Only happens on `User` collection.

**Expected behavior**
Would expect a successful update of my User collection which would show the logo that I added.

**Code snippets**
`{"errors":[{"message":"Bad Request","locations":[{"line":3,"column":5}],"path":["updateUser","user"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"data":"Cannot read property 'globalId' of undefined","isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Bad Request"},"headers":{}},"message":"Bad Request","stacktrace":["Error: Bad Request","    at Object.strapi.app.response.(anonymous function) [as badRequest] (/usr/local/lib/node_modules/strapi/lib/middlewares/boom/index.js:68:34)","    at Object.proto.(anonymous function) [as badRequest] (/usr/local/lib/node_modules/strapi/node_modules/delegates/index.js:40:31)","    at Object.update (/usr/src/api/strapi-app/plugins/users-permissions/controllers/User.js:154:11)","    at process.internalTickCallback (internal/process/next_tick.js:77:7)"]}}}],"data":{"updateUser":{"user":null,"__typename":"updateUserPayload"}}}`

**System**
- Node.js version: v10.15.3
- NPM version: 6.9.0
- Strapi version: v3.0.0-alpha.26.2
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
@iamacatperson The alpha version is no longer supported, please test with the latest Beta version. If the error persists there also we can reopen this.

**Comment by iamacatperson** [comment]
@derrickmehaffy Okay, noted. But is there any workaround for this? Because we don't have enough buffer time to do the migration (and do fixes if anything else is affected). The current alpha version that we have installed is working perfectly for what we need for the time being except for this part.

Any advise would be appreciated. Thanks!

**Comment by RanaOsamaAsif** [comment]
**Strapi version v3.0.0-beta.11**

@derrickmehaffy  I'm facing this issue as well when trying to update a user's profile picture via GraphQL mutation. 

Here is the mutation I'm executing in the GraphQL playground
`mutation update{
  updateUser(input:{where: {id: "5daafac2c404f83532248be2"},
    data:{
      first_name: "New First Name"
      profile_image: "5daee5c70a977a5af9634129"
  }})
  {
    user{
      first_name
    }
  }
}`

Another thing that I have observed is that when this "Cannot read property 'globalId' of undefined" error occurs the previous(which I uploaded via admin panel) profile picture is removed as well. This might be a possible duplicate of [https://github.com/strapi/strapi/issues/3496](url)

Kindly suggest a solution or workaround maybe. Thanks!

**Comment by derrickmehaffy** [comment]
`Strapi version v3.0.0-beta.11` @RanaOsamaAsif always test with the latest version.

**Comment by RanaOsamaAsif** [comment]
@derrickmehaffy Hi, thanks for replying. Can you kindly provide me with the link of migrating guide from Strapi version v3.0.0-beta.11 to beta.17.3. The only guide I could find was from beta.15 to beta.16.

**Comment by derrickmehaffy** [comment]
you would follow the same guide to the beta.17 stuff. Most updates don't require a migration guide on the beta you just change the package versions in your package.json

`rm -Rf node_modules .cache build package-lock.json yarn.lock`
`npm i` // `yarn install`
`npm run build` // ` yarn build` // `strapi build`

**Comment by RanaOsamaAsif** [comment]
@derrickmehaffy I was able to successfully migrate to beta.17.3 and can confirm that this issue is resolved now. Using GraphQL profile picture on user's model was updated successfully. 
Thanks a lot!
