### ISSUE TITLE
Can't update group if before if empty groups existed before.

### ISSUE THREAD

**Issue by Bienio** [strapi/strapi#4265]
**Describe the bug**
If the model has two groups and the second group will be updated, and the first group is empty, then the second group will not save the changes.

**Steps to reproduce the behavior**
1. Create new record in model 'post'
2. Fill only 'title' field
3. Save record
4. Open record for update
5. Fill group 'meta' and leave group 'description' empty
6. Save record
7. Open this record but 'meta' is empty

**Code snippets**
Model post
```
{
  "connection": "default",
  "collectionName": "post",
  "info": {
    "name": "post",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "description": {
      "group": "description",
      "type": "group"
    },
    "meta": {
      "group": "meta",
      "type": "group"
    }
  }
}
```
Group description
```
{
  "info": {
    "name": "description",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_descriptions",
  "attributes": {
    "title": {
      "type": "string"
    },
    "detail": {
      "type": "richtext"
    }
  }
}
```
Group meta
```
{
  "info": {
    "name": "meta",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_metas",
  "attributes": {
    "title": {
      "type": "string"
    },
    "keywords": {
      "type": "text"
    },
    "description": {
      "type": "text"
    },
    "canonicalLink": {
      "type": "string"
    },
    "picture": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }
  }
}
```

**System**
- Node.js version: v10.16.1
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.16.8 
- Database: mysql
- Operating system: MacOS

**Comment by lauriejim** [comment]
Hello @Bienio !
Thank you for reporting this issue.

After checking the request, the group data is not sent.
The value is `null` for both groups.

But If I add a description, it works.

I change the layout to check if it comes from the order.
And it's the issue! If you update the layout and you set `meta` before `description` you can send meta alone.

**Comment by Bienio** [comment]
That's work! Thanks for fix!
Strapi is amazing
