### ISSUE TITLE
Unable to update email template, subject and from address

### ISSUE THREAD

**Issue by deepakgd** [strapi/strapi#4266]
**Describe the bug**
Unable to update email templates, subject, from address from admin panel

**Steps to reproduce the behavior**
1. Goto: http://localhost:1337/admin/plugins/users-permissions/email-templates
2. Edit reset password
3. Change any content such as shipper email or mail content or subject or response email
4. Click save
5. Logout
6. Forgot password
7. Enter email and click send email
8. Check your email
Changes which you have done in step 3 are not reflected in mail

**Expected behavior**
Email template, subject and address are need to be updated

**Screenshots**

![Screenshot from 2019-10-16 11-14-35](https://user-images.githubusercontent.com/8593673/66892099-99c25880-ef9f-11e9-8aae-d36a8834ca77.png)
![Screenshot from 2019-10-16 11-14-15](https://user-images.githubusercontent.com/8593673/66892101-99c25880-ef9f-11e9-9910-92c34af8be79.png)
![Screenshot from 2019-10-16 11-14-00](https://user-images.githubusercontent.com/8593673/66892103-99c25880-ef9f-11e9-9bff-dab66e613827.png)

**System**
- Node.js version: V10
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: mysql
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
@deepakgd please don't use external image services if possible. You can just drag and drop the screenshots into the github editor and it will add them. Makes it a little easier to see whats going on without clicking on a bunch of links 😄

**Comment by deepakgd** [comment]
@derrickmehaffy sure thanks

**Comment by lauriejim** [comment]
Hello @deepakgd !

The email template you are trying to update is for your users "forgot password" feature.
https://strapi.io/documentation/3.0.0-beta.x/plugins/users-permissions.html#authentication

Here you are using the admin forgot password.
To update this template, you will have to customize the admin by following the `Customization` concept.
https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#admin-extension
https://github.com/strapi/strapi/blob/master/packages/strapi-admin/controllers/Auth.js#L321

**Comment by felixhamel** [comment]
Fixed in https://github.com/strapi/strapi/pull/4500

**Comment by bakulaw** [comment]
how do I change the value of URL?, my template does not show the value and starts with "code=f9a2bf3147aa22cbbc131064a9."
