### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by guidone** [strapi/strapi#4268]
**Describe the bug**
Got this error "Error: SQLITE_ERROR: near "transaction": syntax error" trying to migrate from 3.0.0-beta.16.1 to 3.0.0-beta.16.8

**Steps to reproduce the behavior**
1. Updated all strapi dependencies from 3.0.0-beta.16.1 to 3.0.0-beta.16.8 in package.json
2. Run strapi dev  

**Screenshots**
<img width="984" alt="migration-issue" src="https://user-images.githubusercontent.com/502519/66897334-103e7500-eff7-11e9-970c-2047b3273073.png">

**System**
- Node.js version: 10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: sqlite
- Operating system: macos

**Comment by derrickmehaffy** [comment]
That sounds like you have a cached package, purge your `build`, `.cache`, `node_modules`, `package-lock.json`, and `yarn.lock` and rerun either `npm i` or `yarn install` and then try your `strapi develop`

**Comment by guidone** [comment]
Same problem, where are stored the migrations in the repo?

**Comment by lauriejim** [comment]
I created an application with `beta.16.1`, removed the `yarn.lock` file, updated the dependencies to `betat.16.8`, run `yarn` to install new deps.
And it works well...

**Comment by guidone** [comment]
The application has some tables and forms in it, it might be relevant the fact that the database is not empty. Anyone knows where is the migration file so I can inspect what operation the script is trying to do on the db?

**Comment by derrickmehaffy** [comment]
There is no migration file @guidone Strapi doesn't delete or rename tables or columns yet. All it does is add new ones if needed.

**Comment by guidone** [comment]
@derrickmehaffy this is not exactly true in [buildDatabaseSchema.js](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js#L191) some table in sqlite3 are renamed and rebuilt, nevermind I've found the problem, there was a table named "transactions" and a field named "transaction" and this was throwing and error [here](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js#L213), perhaps it's a clash with reserved names.
I renamed it into "payments" and the DB update wen through.

**Comment by bohnmedia** [comment]
It seems, that there is a problem when you use internal keywords. Got the same problem with the following names.

- order
- transaction
- select
- alter

![image](https://user-images.githubusercontent.com/9419148/69245824-d9382200-0ba7-11ea-9d7d-43a7fba4e05b.png)

**Comment by derrickmehaffy** [comment]
Yeah those are all SQL reserved and they aren't being escaped, I wouldn't recommend using them.

**Comment by bohnmedia** [comment]
Are there plans to escape the names in the future?

**Comment by derrickmehaffy** [comment]
Knex handles all those, strapi doesn't define that right now. AFAIK no
