### ISSUE TITLE
/admin not working. Always shows public/index.html

### ISSUE THREAD

**Issue by mariusbolik** [strapi/strapi#4271]
**Describe the bug**
On http://localhost:1337/admin the Admin Panel should show. But I only see die "Welcome..." Page.

**Steps to reproduce the behavior**
1. npx create-strapi-app my-project
2. Choose MySQL as Database
3. Insert Credentials
4. Choose "No" for SSL
5. run "strapi start" or "npm run start"

**Expected behavior**
Admin Panel should show up.

**Screenshots**
![Strapi Error](https://i.imgur.com/FpymZFF.png "Landing Page")
![Strapi Error](https://i.imgur.com/yy7NlbS.png "Console")

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.16.3
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.1
- Database: MySQL
- Operating system: macOS Catalina

**Comment by derrickmehaffy** [comment]
You need to build or use `strapi develop`

`npm run build` / `yarn build` / `strapi build`

**Comment by cadavre** [comment]
I don't get it. We need to run development env to get into the CMS?

**Comment by jcousins-ynap** [comment]
@cadavre I think you're expected to use `npm run start` to run the cms, it doesn't include the admin pages.

**Comment by cadavre** [comment]
I'm confused now, so `/admin` isn't the CMS? :) How can I get to the CMS then? :)

**Comment by jcousins-ynap** [comment]
There seems to be two parts to this application (please someone correct me if I am wrong). 

The first part is the _admin interface_ which is a static website created by `npm run build` or `npm run develop`. This output is similar to the built output of a `create-react-app` application.

The second part is the _api_ which is a node application started by `npm run start`. This is the rest api between the admin interface and the database.

**Comment by cadavre** [comment]
Ok, so I think we can say `/admin` is CMS and Strapi itself is a headless-CMS. That's kind confusing.

The odd part (and my question) here is we can manage content via UI by visiting `/admin` – event if we're in production – we can manage the content. If we set proper rights we can make user group that will have access to only content edition and not model edition.

But with no `/admin` we have no content edition. What's the point of the admin panel then?

**Comment by jcousins-ynap** [comment]
The point is that the `/admin` is the GUI where you control the content, models, plugins, and endpoints.

**Comment by cadavre** [comment]
And thanks to Roles & permissions we can give a user access only to Content creator, even in production.

**Comment by scottydev** [comment]
Thanks to @derrickmehaffy for the answer.

**Before** running `strapi().start()` you need to build the admin interface by running  `npm run build`.

Make sure all strapi processes are killed before running either command.

**Comment by lauriejim** [comment]
Okay an explanation of what happen with strapi.
- When you create an application using the `quickstart`  flag - it creates an application with `SQLite` as database. When the app is created, we automatically run `yarn develop`. This command checks if there is a built admin - if not - it runs `yarn build` - then it starts the server.
- When you chose to use a custom database, it will just create the application (the admin is not build - so you can directly access to the admin dashboard)
So to build the admin you can run `yarn develop` - that will start your app in `dev` mode and build your admin if it's needed.
You can also run `yarn build` - it will just run the admin build.
And the `yarn start` just launch your server.

So if you create a strapi app with a custom database and you start your server with `yarn start` the admin has been never built - so no accessible.
