### ISSUE TITLE
Add save button on top and bottom of create an entry

### ISSUE THREAD

**Issue by Cpaczek** [strapi/strapi#4273]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
On the create an entry page the save/reset button should be on the top and bottom for content types that have a lot of different fields so you don't have to scroll back up. A floating save button could also work.

**Comment by talentedunicorn** [comment]
If this is approved, can I take this? 😊

**Comment by derrickmehaffy** [comment]
@soupette I also agree with this

**Comment by Cpaczek** [comment]
@talentedunicorn feel free

**Comment by websocket98765** [comment]
I'd recommend using CSS `position: sticky;` to keep the bar with all buttons visible at the top of the page as it's scrolled. <https://caniuse.com/#search=sticky> That way buttons are always visible and not just at top and button of long pages.

**Comment by soupette** [comment]
Sure let's do it I am pretty sure @Aurelsicoko agrees on it. However if you plan on developing updating the component can you use the develop branch as all components have been migrated to styled-components?


Thanks a lot @talentedunicorn if you need any help feel free to reach out to either @virginieky or me (@soupette) on the community Slack!

**Comment by Cpaczek** [comment]
Also the rendering of the header-subtitle should be toggled if there is any content to make sure that the text looks centered just a note.
![image](https://user-images.githubusercontent.com/25715982/66983875-75817d00-f06e-11e9-8a08-636c55e1aebe.png)

**Comment by soupette** [comment]
Sure, in fact we are planning to add this component to our new UI component library, [@buffetjs/custom](https://www.npmjs.com/package/@buffetjs/custom) all these improvements could be added.

**Comment by talentedunicorn** [comment]
> Sure let's do it I am pretty sure @Aurelsicoko agrees on it. However if you plan on developing updating the component can you use the develop branch as all components have been migrated to styled-components?
> 
> Thanks a lot @talentedunicorn if you need any help feel free to reach out to either @virginieky or me (@soupette) on the community Slack!

Thanks will do. Really excited to work on this 😊
I'm already on that Slack and will drop a message if I run into issues 🙏

**Comment by talentedunicorn** [comment]
> Also the rendering of the header-subtitle should be toggled if there is any content to make sure that the text looks centered just a note.
> ![image](https://user-images.githubusercontent.com/25715982/66983875-75817d00-f06e-11e9-8a08-636c55e1aebe.png)

Should this be filled under another issue?

**Comment by Cpaczek** [comment]
Maybe, you can only see the visual issue if you can straighten it with you will have to do to make it floating so it depends technically right now it is an issue but you can't see it

**Comment by talentedunicorn** [comment]
> I'd recommend using CSS `position: sticky;` to keep the bar with all buttons visible at the top of the page as it's scrolled. https://caniuse.com/#search=sticky That way buttons are always visible and not just at top and button of long pages.

I attempted to implement `position: sticky` but unfortunately the support isn't that good at the moment specifically for IE, i've added action buttons at the bottom for now hopefully this will make creating and editing easier :)

**Comment by websocket98765** [comment]
@talentedunicorn Support will never come in IE, since IE development ended at IE11. It was replaced by Microsoft Edge, which has had support for `sticky` for >2 yrs. IMO it's ok to not support IE anymore, but that's depends on Strapi's policy whether they aim to support IE or not these days.  @soupette Does Strapi care about supporting IE, given Edge replaced it long ago?

**Comment by derrickmehaffy** [comment]
I'd offer a guess that no considering they only recently started supported Windows at all (server side at least) or even for local development. More than likely their focus is probably Chrome, Firefox, and naturally Safari (since all the Strapi devs are on Macs)

**Comment by Aurelsicoko** [comment]
Hi everyone,

With the upcoming release of the Dynamic Zones, we will also implement a sticky bar both for the Content-Type Builder and Content Manager. Please find a screenshot of what it will look like.

![Dynamic zones   components](https://user-images.githubusercontent.com/4144726/67492411-a8cb9980-f676-11e9-83a1-24e7c5d5f4ce.png)

Note: in this screenshot, you can also see that we plan to highlight the fields which have an error in a different (and better) way than it is currently.

If you want more details about the Dynamic Zones and the Component concepts, please take a look at the last [Monthly Update](https://strapi.io/blog/monthly-update-october-2019?redirectPage=1) article.
