### ISSUE TITLE
Cancel Button not working on Roles and Permissions

### ISSUE THREAD

**Issue by Cpaczek** [strapi/strapi#4274]
**Describe the bug**
Cancel button does not work when adding a new role

**Steps to reproduce the behavior**
Navigate to Roles & permission
Click add new role
Cancel button top right does not work

**Expected behavior**
Should close the new role window.

**System**
- Node.js version: 10
- NPM version: 6
- Strapi version: 3.0.0-beta.17.1
**Additional context**

**Comment by soupette** [comment]
@Cpaczek, in fact the cancel button clears the form instead of closing the window

**Comment by soupette** [comment]
I am closing this issue since it is the intended behaviour.
