### ISSUE TITLE
API returning ID strings as arrays

### ISSUE THREAD

**Issue by Palgie** [strapi/strapi#4277]
**Describe the bug**
In a generated API that has a many-to-many relationship the JSON response from the API returns the attached relationship IDs string as a split array rather than a string.

In my case the relationship is that a product can have multiple collections and vendors attributed to it the endpoint. If you visit `/products` (e.g.) the result that each product has a collection array of objects as expected:

```
...
collections: [{
_id: "5d6681dd08236f0007debe37",
title: "Collection Name",
handle: "collection-name",
createdAt: "2019-08-28T13:30:05.350Z",
updatedAt: "2019-08-28T13:30:05.361Z",
__v: 0,
id: "5d6681dd08236f0007debe37"
}
...
]
...
```

In the alternative endpoint, e.g. `/collections` the ID of product should follow the same structure but instead is output as the following:

```
...
product: [{
stock: 1,
collections: [
{
0: "5",
1: "d",
2: "6",
3: "6",
4: "8",
5: "2",
6: "5",
7: "b",
8: "0",
9: "8",
10: "2",
11: "3",
12: "6",
13: "f",
14: "0",
15: "0",
16: "0",
17: "7",
18: "d",
19: "e",
20: "b",
21: "e",
22: "4",
23: "6"
},
{
0: "5",
1: "d",
2: "6",
3: "6",
4: "8",
5: "1",
6: "e",
7: "7",
8: "0",
9: "8",
10: "2",
11: "3",
12: "6",
13: "f",
14: "0",
15: "0",
16: "0",
17: "7",
18: "d",
19: "e",
20: "b",
21: "e",
22: "3",
23: "8"
}
...
}]
}]
```

**Expected behavior**
Expected the API to return a string when referencing IDs from related data.

**Screenshots**
<img width="393" alt="Screenshot 2019-10-17 at 17 38 11" src="https://user-images.githubusercontent.com/725626/67018932-842f6900-f12e-11e9-9e18-befcc7dec28a.png">

**System**
- Node.js version: v12.9.1
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.16.7
- Database: MongoDB (Atlas)
- Operating system: MacOS

**Additional context**
The `/collections` endpoint has no custom controllers, models, services, etc.

Relevant part of the product model:
```
   "collections": {
      "collection": "collection",
      "via": "products",
      "dominant": true
    },
```

Relevant part of the collection model:
```
    "products": {
      "collection": "product",
      "via": "collections"
    }
```

It's also worth noting that the Atlas DB's IDs and types seem to be stored correctly, the Admin also displays the relationship and allows updates to the relationships correctly. GraphQL parsed these relationships properly as I'd only noticed this happening when I switched to REST API calls. Suggesting that this is an issue trying to fetch and display the nested data rather than with the data itself.

**Comment by alexandrebodin** [comment]
Hi @Palgie This has been fixed beta 16.8 you can upgrade to check it out ;)
