### ISSUE TITLE
Missing space right behind lightning emoji

### ISSUE THREAD

**Issue by daksamit** [strapi/strapi#4278]
Hello!
Maybe it's just visually a little annoying, but
when you run `yarn develop`, there is missing space character right behind emoji on server boot.
Maybe just add one align logs?

![image](https://user-images.githubusercontent.com/7165997/67030809-808ce980-f110-11e9-8902-550082242489.png)

**Comment by derrickmehaffy** [comment]
@daksamit this has been fixed on beta.17.1
