### ISSUE TITLE
403 Forbidden error on GET /users-permissions/init

### ISSUE THREAD

**Issue by fmaldonados** [strapi/strapi#4279]
**Describe the bug**
When I go to admin I receive a forbidden error in the console.

**Steps to reproduce the behavior**
1. Create a new strapi project (MySQL)
2. Add 
`"pool": {
          "min": 0,
          "max": 10,
          "idleTimeoutMillis": 3000,
          "createTimeoutMillis": 3000,
          "acquireTimeoutMillis": 3000
        }`
    in the database.json in options.
3. NPM run build
4. NPM Start

**Expected behavior**
Should go to http://localhost:1337/admin/auth/register

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.1
- Database: MariaDB (Azure), I use the default admin user that azure creates.
- Operating system: Windows 10

**Additional context**
Works with a local instance of MariaDB and also works when I do the suggested solution from [here](https://github.com/strapi/strapi/issues/3284#issue-445319771)

Strapi is cool, hope I can get some help, thanks!

**Comment by derrickmehaffy** [comment]
Duplicate #4267
