### ISSUE TITLE
The response of GraphQL queries with multiple models are wrong

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4280]
**Describe the bug**

The response of GraphQL queries with multiple models are wrong.

**Steps to reproduce the behavior**

1. Make a query with multiple models. Example:

```javascript
query {
  users(limit: 2) {
    username
    name
  }
  matchdays(limit: 2) {
    name
  }
}

```

**Expected behavior**

Return the right response.

**Screenshots**

<img width="1223" alt="Screenshot 2019-10-18 at 15 40 00" src="https://user-images.githubusercontent.com/1007051/67076393-a7562900-f1bf-11e9-9308-31ca5c32263f.png">
<img width="1217" alt="Screenshot 2019-10-18 at 15 40 46" src="https://user-images.githubusercontent.com/1007051/67076396-a7562900-f1bf-11e9-9568-ab878c817089.png">

**System**
- Node.js version: `v10`
- NPM version: `v6`
- Strapi version: `v3.0.0-beta.17.1`
- Database: MongoDB
- Operating system: macOS

**Comment by alexandrebodin** [comment]
Looks like it returns the data from userd and tries to map that to tje matchdays... maybe an issue with the loaders. Will have take some time to dig. Thanks for reporting !

**Comment by lauriejim** [comment]
I tested this issue with beta.17.8 and all work fine.

**Comment by abdonrd** [comment]
I just tried, and I found another related issue. Whitespace issue?

See the screenshoots:

<img width="1215" alt="Screenshot 2019-12-03 at 11 24 52" src="https://user-images.githubusercontent.com/1007051/70042759-bb16ec80-15bf-11ea-8add-284442923e46.png">
<img width="1215" alt="Screenshot 2019-12-03 at 11 26 50" src="https://user-images.githubusercontent.com/1007051/70042820-d5e96100-15bf-11ea-92fd-f6893eed33e6.png">
<img width="1215" alt="Screenshot 2019-12-03 at 11 25 29" src="https://user-images.githubusercontent.com/1007051/70042761-bbaf8300-15bf-11ea-8f15-8e26153b3f1b.png">

**Comment by lauriejim** [comment]
Should create a new issue I thing

**Comment by abdonrd** [comment]
@lauriejim #4662

**Comment by lauriejim** [comment]
Thank you 😉
