### ISSUE TITLE
Custom GraphQL Queries are not working

### ISSUE THREAD

**Issue by volfpe** [strapi/strapi#4283]
**Describe the bug**
Custom GraphQL Queries are not working. If you add custom query definition (in `./api/*/config/schema.graphql`) and than try to call this query, the request will fail (`Cannot read property 'plugin' of undefined`).

I have tried to find the source of this bug and it seems that `globalPolicy` middleware is not called on custom graphql query request (located in `strapi-utils/lib/policy.js`). Regular graphql queries work fine.

**Steps to reproduce the behavior**
1. Create new content type (e.g. `article` in strapi UI). Fields do not matter.
2. Create `./api/article/config/schema.graphql` file
3. Insert the following to created file
```
module.exports = {
  definition: ``,
  query: `
    someQuery: Boolean!
  `,
  type: {},
  resolver: {
    Query: {
        someQuery: {
            resolver: (obj, options, ctx) => {
                return true
            }
        }
    },
  },
};
```
4. Call the following query (in http://localhost:1337/graphql)
```
query {
  someQuery
}
```
5. See error

**Expected behavior**
The query should pass and server should return `true`

**System**
- Node.js version: `v10.15.3`
- NPM version:
- Strapi version: `3.0.0-beta.17.1`
- Database: `psql`
- Operating system: `Mac OS`

**Comment by alexandrebodin** [comment]
Hi @volfpe, 
Have you tried declaring someQuery as a function instead of an object with a resolver directly ? 


someQuery() {
  Return true
}

**Comment by volfpe** [comment]
Hello @alexandrebodin !
Oh, yes, it seems to work!

My previous resolvers definition (before upgrade from `3.0.0-beta.13`) was this:
```
  resolver: {
    Query: {
        someQuery: {
            resolver: strapi.controllers.article.someQuery,
        }
    },
  }
```

Modifying that to this structure fixes my problem.
```
  resolver: {
    Query: {
        someQuery: strapi.controllers.article.someQuery
    },
  }
```

Thanks for your help!
Updating the documentation would be great ;)

Can we still define policies in resolver definitions? (https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#execute-a-policy-before-a-resolver)

**Comment by alexandrebodin** [comment]
@volfpe WHat you were doing should still be feasable it's still a bug but I gave you a workaround for now ;) 

You can add policies with your resolver following the current doc but that might still break with the exact same error you get right now. 

Going to fix this asap. Thanks fro reporting it !

**Comment by alexandrebodin** [comment]
@volfpe Currently this usecase isn't manageable for us as it causes issues with permissins handling. 

To make it work you will need to specify a resolverOf with your resolver. To do so it means adding a controller action (no route needed) so it can be configurable in the roles & permissionns. 

*`controllers/Controller.js`*
```js
module.exports = { customAction() {} )
```

*`schema.graphql.js`*
```js
module.exports = { 
  query: ' someQuery: Boolean',
  resolver: {
    Query: {
       someQuery: {
         resolverOf: 'Controller.someAction', 
         resolver() { return true }
       }
    }
  }
}
```

I'm going to be adding this to the consideration for future updates. and closing for now.

**Comment by sndrgb** [comment]
Can someone help me on this? I've been trying for hours and in no way I can do a custom query

```
module.exports = {
  query: 'cityBySlug(slug: String!): City',
  resolver: {
    Query: {
      cityBySlug: {
        description: 'OH',
        resolverOf: 'application::city.city.find',
        resolver: async (obj, options, context) => {
          const slug = context.params.slug;
          return await strapi.api.city.services.city.findSlug(slug);
        }
      }
    }
  }
}
```

**Comment by alexandrebodin** [comment]
@sndrgb This looks about right. where are you putting this code ?

**Comment by sndrgb** [comment]
@alexandrebodin It's ok everything resolved thanks a lot!

**Comment by sriram10** [comment]
@sndrgb May I know how it got resolved? I'm still facing issue. I couldn't do a custom query.

Here is my sample code:
```
module.exports = {
  query: 'discourseCategoriesOrder(where: JSON): Int!',
  resolver: {
    Query: {
      discourseCategoriesOrder: {
        description: 'Return the count of discourseCategories',
        resolverOf: 'application::discourse-category.discourse-category.count',
        resolver: async (obj, options, ctx) => {
          return await strapi.api['discourse-category'].services['discourse-category'].count(options.where || {});
        }
      }
    }
  }
};
```

This is the error message I'm getting,
```Cannot query field \"discourseCategoriesCount\" on type \"Query\". 
Did you mean \"discourseCategories\", \"discourseCategoriesConnection\", 
\"discourseCategory\", or \"discoursePage\"?```
