### ISSUE TITLE
GraphQL Playground wouldn't respect query variables

### ISSUE THREAD

**Issue by amitschandillia** [strapi/strapi#4285]
**Describe the bug**
My Strapi installation has 3 users with `username` as one of the fields. I am trying to lookup a particular user by username using the `where` clause in the `users` query. This works fine if I pass a static value for the `username`, e.g., `where: {username: "jonsnow"}`, but the `where` clause is entirely ignored if I pass the value via query variables.

**Steps to reproduce the behavior**
1. Go to https://dev.schandillia.com/graphql
2. Run the following query:
  ```
  {
    users (where: {username: "jonsnow"}) {
      username
      firstName
    }
  }
  ```
3. See results. It should be:
  ```
  {
    "data": {
      "users": [
        {
          "username": "jonsnow",
          "firstName": "Jon"
        }
      ]
    }
  }
  ```
4. Now run the same query using query variables. The query looks like this:
  ```
  query users($username: String!) {
    users(where: {username: $username}) {
      username
      firstName
    }
  }
  ```
  And the query variables:
  ```
  {
    "username": "jonsnow"
  }
  ```
5. The output will now include all users as if the `where` clause didn't exist:
  ```
  {
    "data": {
      "users": [
        {
          "username": "negger",
          "firstName": "Arnold"
        },
        {
          "username": "jonsnow",
          "firstName": "Jon"
        },
        {
          "username": "tonystark",
          "firstName": "Tony"
        }
      ]
    }
  }
  ```

**Expected behavior**
The expected behavior would be for the query to respect query variables being passed and return only entries that match the `where` condition.

**Screenshots**

Results with query variables (incorrect output):
![graphqlplayground](https://user-images.githubusercontent.com/42805381/67098147-40de0480-f1d9-11e9-8397-080266f5732a.jpg)

Results with static value (correct output):
![apollo-2](https://user-images.githubusercontent.com/42805381/67098574-1e002000-f1da-11e9-83aa-ff6bbf1193e2.jpg)

**Code snippets**
The repo for my Strapi installation is up at https://github.com/amitschandillia/proost/tree/master/dev-beta

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: MongoDB
- Operating system: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)

**Additional context**
FWIW, I didn't face this issue with alpha.

**Comment by alexandrebodin** [comment]
Hi,

Since a recent chnge in graphql you can’ot run your query this way, look at this issue to fix your query :) 

Hope this helped

**Comment by alexandrebodin** [comment]
Issue: https://github.com/strapi/strapi/issues/3537
