### ISSUE TITLE
Error: Field "Query.news" can only be defined once.

### ISSUE THREAD

**Issue by Teo0303** [strapi/strapi#4289]
**Describe the bug**
I've created new content type called 'news'. Everything was working till I installed graphQL. When I installed graphQL server stopped working and showing this error:
Error: Field "Query.news" can only be defined once.
Here's complete log.
C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2019-10-18T16_17_21_355Z-debug.log

**Screenshots**
![image](https://user-images.githubusercontent.com/39439363/67111407-485bd880-f1ee-11e9-8c8d-d304ae41e406.png)

**System**
- Node.js version: v10.15.0
- NPM version: 6.4.1
- Strapi version: 3.0.0 -beta
- Database: GraphQL
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi, can you share your api models plz ?

**Comment by Teo0303** [comment]
> Hi, can you share your api models plz ?

Hi, yes of course.

![image](https://user-images.githubusercontent.com/39439363/67112932-ca99cc00-f1f1-11e9-9b1e-64b566bee2e7.png)

**Comment by alexandrebodin** [comment]
Here is the explanation.

Your content type as a plural name. When we generate the graphql schema for the content type we generate a plural name based on the name of the content type to generate a query to get the list of entry. 
Unfortunatly news is already plural so we create the same name for both the single fetch and the collection fetch. It produces this 
**example**
```graphql
type Query {
  news(id: ID): News!
  news(limit: Int, ...): [News!]!
}
```
This explains the error.

We should check that to avoid the issue in the future. For now you will have to rename your content type to be sth la NewsPost 

Hope this helpes you :)

**Comment by Teo0303** [comment]
> Here is the explanation.
> 
> Your content type as a plural name. When we generate the graphql schema for the content type we generate a plural name based on the name of the content type to generate a query to get the list of entry.
> Unfortunatly news is already plural so we create the same name for both the single fetch and the collection fetch. It produces this
> **example**
> 
> ```graphql
> type Query {
>   news(id: ID): News!
>   news(limit: Int, ...): [News!]!
> }
> ```
> 
> This explains the error.
> 
> We should check that to avoid the issue in the future. For now you will have to rename your content type to be sth la NewsPost
> 
> Hope this helpes you :)

It's working now. thank you so much!

**Comment by davidkhierl** [comment]
having also the same error with the content type of 'agenda'

**Comment by lerototi** [comment]
@davidkhierl Are you fixed it? I have a "anamnese" model, with this problem!

**Comment by lauriejim** [comment]
This issue comes from a plural issue. There is another issue open about it.
Try to fix it by using @alexandrebodin fix.

**Comment by norbertbede** [comment]
hi. same here 
v. 3.0.0-beta.17.8 (node v10.13.0)

**Comment by JKortmann** [comment]
I have the same error.
3.0.0-beta.17.8 (node v13.1.0)

**Comment by jared-shepherd** [comment]
In case anyone happens upon this post as I did and it doesn't resolve their issue, this might help!

**I was creating components in 3.0.4** and Strapi crashed with this message:

_There can be only one type named "editComponentGroupNameComponentName"_

**The solutions was to delete a duplicate JSON file at this location: _./components/GroupName/ComponentName.json_**

**Comment by sebastianjung** [comment]
As I do not need the news model available on my graphql endpoint i disabled the shadow crud creation of the news model like so (inside the api/<model>/config/schema.graphql.js)

```
module.exports = {
  resolver: {
    Query: {
      news: false // The `news` query will no longer be in the GraphQL schema.
    }
  },
};
```

which makes the error disappear. Most of you might need to rename the model though. Just my specific case i wanted to share.

Read more about disabling the shadow crud feature here:
[https://strapi.io/documentation/v3.x/plugins/graphql.html#customize-the-graphql-schema](https://strapi.io/documentation/v3.x/plugins/graphql.html#customize-the-graphql-schema)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/error-field-query-products-can-only-be-defined-once/2393/1

**Comment by orszaczky** [comment]
Why is this closed? It's obviously still an issue. My installation broke because of this - I created two nested components (`resources`, and repeatable called `resource`), and my app crashed. I tried to fix it manually and now my admin UI doesn't load anymore.

This issue and the allowed naming patterns should be documented and there should be a warning at component creation about what namings are allowed. :/

**Comment by derrickmehaffy** [comment]
It's closed due to: https://github.com/strapi/strapi/issues/4289#issuecomment-543837198

The parent issue for this: https://github.com/strapi/strapi/issues/1198

Locking thread, comments about words that aren't handled should be pointed to the parent issue.
