### ISSUE TITLE
Npm install gives error after updating from 7.2 to 7.3

### ISSUE THREAD

**Issue by acifer** [strapi/strapi#429]
**Node.js 9.2.0**:
**npm 5.5.1**:
**Strapi 3.0.0-alpha.7.3**:
**Mac os Sierra 10.12.6**:
After updating application from 6.4 to 7.2 it was working if I installed npm install in the admin folders but post updating to 7.3. 
Npm install is giving following error 
>mystrapiapp postinstall /Users/aadilrasheed/code/code/xcg
> node node_modules/strapi-utils/script/plugin-install.js

module.js:544
    throw err;
    ^
can not find node_modules/strapi-utils/script/plugin-install.js'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by lauriejim** [comment]
Create new project with `7.3` version and replace the `admin` folder with the new one.

**Comment by acifer** [comment]
I already did it apparently there is problem with the     "postinstall": "node node_modules/strapi-utils/script/plugin-install.js",
in package.json

**Comment by lauriejim** [comment]
Can you update the `postinstall` in your `package.json` to : `"postinstall": "node node_modules/strapi/lib/utils/post-install.js"` and try again please.

**Comment by acifer** [comment]
Thanks it works now. I guess there should be small posts about these issues, such as database table name change.
