### ISSUE TITLE
SQLITE_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by darthzyklus** [strapi/strapi#4292]
**Describe the bug**
I'm using gatsby to fetch data from a server with strapi, where I uploaded multiple images files and after I create another gallery with a bunch of images, the server gives me this 500 error  "SQLITE_ERROR: too many SQL variables" and I can't finish building my site

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: SQLITE ?
- Operating system: CentOS 7+

**Comment by lauriejim** [comment]
Hello @darthzyklus .
With the info you gave me I will not be able to help you.
I need to know more:
- You data models
- Number of images you used
- And steps to reproduce your issue

**Comment by animatedcreativity** [comment]
This may be helpful for someone: [https://github.com/strapi/strapi/issues/7214#issuecomment-691618116](https://github.com/strapi/strapi/issues/7214#issuecomment-691618116)
