### ISSUE TITLE
Spell checking is disabled for rich text fields

### ISSUE THREAD

**Issue by dandv** [strapi/strapi#4300]
I've just installed Strapi with `npx create-strapi-app my-project --quickstart` and created a Content Type for an Article, with a `content` Rich Text field. While editing it in Chrome 77, I'm surprised to see that spell checking is disabled. Do I need to enable a setting somewhere? We're considering Strapi to manage our blog posts (served via Gatsby), and spell checking is an essential function.

![image](https://user-images.githubusercontent.com/33569/67192068-7f7de580-f3b8-11e9-8e5a-bd92a238b226.png)

**Comment by dandv** [comment]
After using the rich editor some more, I've noticed there are no scrollbars, no synchronized scrolling, and generally, the experience could be much better if Strapi integrated the excellent StackEdit markdown editor, and side-by-side editing was the default.

Any thoughts on that?

![image](https://user-images.githubusercontent.com/33569/67194028-f5d01700-f3bb-11e9-8f6c-903a7ce1bda1.png)

**Comment by soupette** [comment]
@dandv we are aware that the current WYSIWYG could be improved. However we are under active development of others features like the [dynamic-zones](https://portal.productboard.com/strapi/1-public-roadmap/c/9-static-content-types-pages). However, we the release of the beta.17 we have added a new feature which allows you to develop inside the administration panel so changing the current WYSIWYG has never been easier so you can easily the [StackEdit markdown editor](https://stackedit.io/) to your project.

Feel free to DM me on Slack if you need guidelines on how to do it.
