### ISSUE TITLE
Use proper title case

### ISSUE THREAD

**Issue by dandv** [strapi/strapi#4301]
Not a big deal, but it was slightly odd to see the Strapi UI capitalize Every Single Word in titles, even when in English, those words should not be capitalized. For example, "Create An Entry" should be "Create an entry" (or at most "Create an Entry", but I don't see the point of capitalizing all nouns), because "an" is a preposition and those don't get capitalized when title casing.

![image](https://user-images.githubusercontent.com/33569/67192567-6c1f4a00-f3b9-11e9-879f-de1f190b8ac2.png)

See https://titlecase.com/:

![image](https://user-images.githubusercontent.com/33569/67192592-79d4cf80-f3b9-11e9-8bb4-24467e6265a2.png)

I would suggest capitalizing only the first letter, but if the AP Style is desired, the [titlecase](https://www.npmjs.com/package/titlecase) package does the job.

**Comment by soupette** [comment]
@dandv I agree we are currently working on the content manager so we will take care of removing all the unnecessary capitalised words in the plugin.

**Comment by Aurelsicoko** [comment]
100% agree on this! We'll remove that asap. It's a choice we made years ago. We were okay with it, but we changed our mind and we would like to change it. We will certainly follow the right way to write things. In other words, we will write "Create an entry", not "Create an Entry" or "Create An Entry".

**Comment by soupette** [comment]
I am closing this issue as I moved to the correct repository.

Here's the [pull request](https://github.com/strapi/buffet/pull/108)
