### ISSUE TITLE
Strapi Default File/Image Store

### ISSUE THREAD

**Issue by danielamiir** [strapi/strapi#4302]
How is Strapi saving files/images by default if I have connected to a MongoDB instance? It currently seems unclear whether Strapi is saving uploaded files to MongoDB or just locally? I am going to deploy Strapi in a production container environment that can sometimes be restarted, meaning if the container crashes&restarts, I should still be able to access uploaded images/files.

The documentation is unclear on this topic. It should clearly state what data is saved where with different configurations and setups.

**Comment by veitbjarsch** [comment]
So feel free to add a PR 😉

**Comment by lauriejim** [comment]
Hello @danielamiir !
I suggest you read [this part of the documentation](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#install-providers) to install an upload provider that will send your file on AWS for example.

**Comment by Seanmclem** [comment]
> So feel free to add a PR 😉
But, where is it saved though?
The original question can't add a PR without their answer

**Comment by derrickmehaffy** [comment]
@Seanmclem the default provider stores the files on the local file system in `./public/uploads` there is no provider that I am aware of that stores the binary files in any database.

**Comment by AnujDivkar** [comment]
Strapi stores the media files using the file system in ./public/uploads there is no way to configure strapi to stores the  file in a database in binary format. However you can write your own code to save the file in binary format.
Refer the link below to know more :https://medium.com/@dineshuthakota/how-to-save-file-in-mongodb-using-node-js-1a9d09b019c1

**Comment by MattieBelt** [comment]
FYI, there is an community upload provider to save file in the mongoDB: https://github.com/AHgPuK/strapi-mongodb-files
