### ISSUE TITLE
Rich text field shows as `-` in the list view

### ISSUE THREAD

**Issue by dandv** [strapi/strapi#4303]
I've defined an "article" type with a String `title` and a Rich Text `content`. After entering some content, in the list view it appears as `-`, making our editors think there's no content in that article.

![Rich text preview is -](https://user-images.githubusercontent.com/33569/67193424-e56b6c80-f3ba-11e9-90c0-9673c46d9e88.gif)

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
