### ISSUE TITLE
Admin returns error after adding or saving content type with content type builder.

### ISSUE THREAD

**Issue by gvramesh2003** [strapi/strapi#4306]
**Informations**

Node.js version: v10.15.3
NPM version: 6.4.1
Strapi version: v3.0.0-alpha.26.2
Database: MySQL
Operating system: Ubuntu 16.04
Host: node.systimanx.xyz/admin

**What is the current behavior?**

When saving a content type, the admin dashboard shows me that there is an error. Redirection fails. Clicking on menu items at the left still works however.

**Steps to reproduce the problem**

1. Go to Content Type Builder
2. Pick Content Type to edit
3. Add field
4. Click save to add field
5. Click save to save content type

**What is the expected behavior?**

Correctly being redirected to the concerning content type after saving.

![Strapi-error](https://user-images.githubusercontent.com/56820633/67198375-76266480-f41c-11e9-825e-84cb1409ea0f.png)

**Comment by lauriejim** [comment]
Hello! This issue looks related to the `alpha.16.2` version of strapi.
We are not in `beta.17.2`. I suggest you update your application.
This issue doesn't exist in the last version.
(the alpha.x.x is not maintained so I close this issue)
Migration guides are available in the documentation.
Thank you.
