### ISSUE TITLE
Deleted Content type shown in page again

### ISSUE THREAD

**Issue by gvramesh2003** [strapi/strapi#4307]
**Informations**

Node.js version: v10.15.3
NPM version: 6.4.1
Strapi version: v3.0.0-alpha.26.2
Database: MySQL
Operating system: Ubuntu 16.04
Host: node.systimanx.xyz/admin

**What is the current behavior?**

Try to delete any "Content type", got success message. After refresh the page, deleted content type shown in page again and corresponding table is not deleted.

**Steps to reproduce the problem**

1. Go to Content Type Builder
2. Delete any Content Type
3. Refresh Page

**Comment by derrickmehaffy** [comment]
@gvramesh2003 please test with the latest Beta version, Strapi alpha is no longer supported. After you have tested with the beta please do let us know if the issue persists here and we can reopen it.
