### ISSUE TITLE
How to override s3 upload provider lib and set ACL private

### ISSUE THREAD

**Issue by Eric0201** [strapi/strapi#4308]
**Describe the topic**
How to override file https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-aws-s3/lib/index.js
I want remove  **ACL:** **public-read** in s3 config. Please help me create extensions. Thanks

**Comment by lauriejim** [comment]
Hello!

To access your uploaded files, you will need this `ACL: public-read`
If you change this option, you will not be able to see your files in the content manager.

To deal with what you want, you can create a `providers` folder.
In this folder, you duplicate the provider you want to custom.
And in the `package.json` you link the dependency via the file system.

I will add some documentation about the customization.

**Comment by Eric0201** [comment]
thanks you very much , please add documentation  about the customization.
