### ISSUE TITLE
Content Insertion in Editor Appears in Wrong Location and With Wrong Content

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#4309]
**Describe the bug**
When editing rich text in the Markdown editor, content inserted by various means will often appear in unexpected places. Further, depending on the scenario, the content that does appear is wrong while other existing content is deleted.

**My example text is**

It was the best of times, it was the worst of times,
it was the age of wisdom, it was the age of foolishness,
it was the epoch of belief, it was the epoch of incredulity,
it was the season of Light, it was the season of Darkness,
it was the spring of hope, it was the winter of despair,
we had everything before us, we had nothing before us,
we were all going direct to heaven, we were all going direct the other way
In short, the period was so far like the present period,
that some of its noisiest authorities insisted on its being received,
for good or for evil,
in the superlative degree of comparison only.

**Steps to reproduce the behavior**
1. Create a content type with a rich text editor
2. Create a new piece of content
3. Copy above lines of text into the editor
4. Place the cursor after the word "incredulity"
5. Hit enter
6. Click "select them" to insert an image.
7. If all goes well, an extra carriage return is added
8. If upload is slow, such as on AWS, ![Uploading my-image.jpg]() will not go away
9. No complete image hash appears
10. The final line of text (in the superlative...) disappears

**Steps to reproduce the behavior of bug 2**
1. In the same text, insert a carriage return.
2. Plase an image
3. Insert another carriage return further down the text
4. Return the cursor to a higher line
5. Insert image
6. Uploading text remains and image hash appears appears at the lower empty line

**Steps to reproduce the behavior of bug 3**
1. Insert an image by any means
2. Wait for the hash to appear
3. Insert an image on the same line as the hash
4. The original hash is replaced and the uploading text does not disappear

**Expected behavior**
The image should be inserted without a carriage return, in the correct location, and in the correct form. No text should disappear. Hashes should not be overwritten.

**Screen shots
**Image for bug 2**
<img width="963" alt="Screen Shot 2019-10-21 at 10 14 41 AM" src="https://user-images.githubusercontent.com/28883798/67213269-bc170480-f3eb-11e9-9df1-e74effccf0ef.png">
**

**System**
- Node.js version: v10 latest
- NPM version: 6.9
- Strapi version: Beta 16.8 and Beta 17
- Database: MySQL
- Operating system: CentOS in Docker

**Additional context**
The two AWS plugins being used are the base Strapi plugin and the custom-domain plugin.

**Comment by amartincolby** [comment]
@soupette I dredged up an old bug that was similar to this, but this is my complete write-up after testing to get the various issues to manifest. Bug 1 is hard to manifest. I was experiencing it on Friday but today couldn't get it. I was able to get some issues to somewhat appear by throttling my connection to "Slow 3G".

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/978

> This is a templated message
