### ISSUE TITLE
Deploy Strapi with PM2 instance in development mode

### ISSUE THREAD

**Issue by gvramesh2003** [strapi/strapi#4310]
**Informations**

Node.js version: v10.15.3
NPM version: 6.4.1
Strapi version: 3.0.0-beta.17.2
Database: MySQL
Operating system: Ubuntu 16.04
Host: node.systimanx.xyz:1337/admin

**What is the current behavior?**

When I click "Content Type Builder" menu, got the page with error message.

![image](https://user-images.githubusercontent.com/56820633/67227014-f87e4b00-f453-11e9-8278-08097ed36ffb.png)

**Note**: start my application with 
sudo NODE_ENV=development pm2 start npm --name abc -- start

**Comment by lauriejim** [comment]
Hello! When you start your application with `npm start` that not let you access the **Settings Manager** and the **Content Type Builder**.
It's not based on the environment you started your application.
You need to start your app with `yarn develop` to have access to this feature.

**Comment by anhtuank7c** [comment]
I believe you have your dedicated web server for dev environment and want to run from it

```
cd /path/to/your/strapi
pm2 start npm --name your_app_name -- run develop
```

**Comment by shredinger137** [comment]
This final comment is very helpful to me. Should it be included in the documentation, https://strapi.io/documentation/developer-docs/latest/guides/process-manager.html#starting-with-strapi-command ?

**Comment by derrickmehaffy** [comment]
> This final comment is very helpful to me. Should it be included in the documentation, https://strapi.io/documentation/developer-docs/latest/guides/process-manager.html#starting-with-strapi-command ?

https://strapi.io/documentation/developer-docs/latest/guides/process-manager.html#starting-with-strapi-command

We use the `start` reference here, as you shouldn't be running a persistent instance in develop mode.

**Comment by merc74** [comment]
Why "you shouldn't be running a persistent instance in develop mode", I want that for my development environment which is a private network, and I want my developer to work on it remotely.

**Comment by merc74** [comment]
@derrickmehaffy 
Ok, but can you explain why? Perhaps there is an excellent reason; I just would like to know if I can live with the consequences.

**Comment by tyuhbh0** [comment]
> > I believe you have your dedicated web server for dev environment and want to run from it
> > ```
> > cd /path/to/your/strapi
> > pm2 start npm --name your_app_name -- run develop
> > ```
> 
> Thank you so much

it's working... Thank You Radhikad

**Comment by AdemYuksel** [comment]
pm2 start ./node_modules/@strapi/strapi/bin/strapi.js --name strapi-dev -- develop

worked for me on windows server
