### ISSUE TITLE
File upload providers don't work

### ISSUE THREAD

**Issue by pedrocruzio** [strapi/strapi#4312]
**Describe the bug**
When trying to install an upload provider on the latest version of Strapi, the server does not start successfully and returns the error below. I tested in multiple providers like Cloudinary and IBM Cloud Storage and I get the same result. 

**Steps to reproduce the behavior**
1. npm install strapi-provider-upload-aws-s3 --save
2. npm start

**Expected behavior**
After the installation, the server is supposed to start correctly and allow you to configure the custom provider in the dashboard (admin/plugins/upload/configurations/development).

**Code snippets**
```
[2019-10-21T23:54:59.018Z] error Bootstrap function in plugin "upload" failed
[2019-10-21T23:54:59.019Z] debug ⛔️ Server wasn't able to start properly.
(node:6616) UnhandledPromiseRejectionWarning: TypeError: Symbol.for is not a function
    at EventEmitter.asJson (/backend/node_modules/strapi-utils/node_modules/pino/pino.js:155:36)
    at EventEmitter.pinoWrite (/backend/node_modules/strapi-utils/node_modules/pino/pino.js:215:16)
    at EventEmitter.LOG (/backend/node_modules/strapi-utils/node_modules/pino/lib/tools.js:93:10)
    at Strapi.stopWithError (/backend/node_modules/strapi/lib/Strapi.js:299:14)
    at Strapi.start (/backend/node_modules/strapi/lib/Strapi.js:257:12)
(node:6616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a pr
omise which was not handled with .catch(). (rejection id: 2)
(node:6616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non
-zero exit code.
```
**System**
- Node.js version: v10.16.3
- NPM version: v6.9.0
- Strapi version: v3.0.0-beta.17.2
- Database: SQLite3
- Operating system: MacOS Mojave (v10.14.6)

**Comment by derrickmehaffy** [comment]
please use the following command: `npm install strapi-provider-upload-aws-s3@beta --save` without the @beta tag you would be pulling from the @latest tag which isn't used right now (and won't be until Strapi goes stable)

**Comment by pedrocruzio** [comment]
Unfortunately, this didn't work on my current project. I tried it with a fresh installation of Strapi and that it worked. So I'm not sure what the problem is, but closing the issue for now.

Thanks @derrickmehaffy!
