### ISSUE TITLE
After installing GraphQL plugin: "an error occurred during models config fetch"

### ISSUE THREAD

**Issue by jacobopolavieja** [strapi/strapi#4314]
**Describe the bug**
After installing the GraphQL plugin, I can't access the admin panel. I receive an error of "an error occurred during models config fetch" (translated from my language).
API seems to be working with Playground, Postman, etc.

**Steps to reproduce the behavior**
1. Install GraphQL plugin
2. Start strapi with 'yarn strapi start'
3. Use Playground
4. Go to localhost:1337/admin
5. A blank page shows up with a little pop up stating "an error occurred during models config fetch" (in Spanish, which is my local language)

**Expected behavior**
Load Strapi's admin panel

**Screenshots**
![strapierror](https://user-images.githubusercontent.com/65220/67268949-049af480-f4b6-11e9-8e56-5e3a5cd9bc60.png)

**System**
- Node.js version: 12.10.0
- NPM version: 6.10.0
- Strapi version: 3.0.0-beta.17.2
- Database: SQLite
- Operating system: Windows 10

**Comment by jacobopolavieja** [comment]
Nevermind... My fault.

To test with Playground I had installed the ModHeader Chrome extension as advised in Strapi's doc. It relies with the set configuration for the admin panel too, so it was trying to send the same Authorization headers to the admin panel as to the GraphQL Playground.

Unchecking the header in the ModHeader extension or just pausing ModHeader solved the problem.

Leaving this right here in case anyone one suffers this same mistake.

Sorry for the inconvenience!

**Comment by dlolsen** [comment]
@jacobopolavieja 
> Leaving this right here in case anyone one suffers this same mistake.
Thank you!

**Comment by azhariemuhammad** [comment]
thank you @jacobopolavieja
