### ISSUE TITLE
Cant select an already uploaded file on media field in any content type

### ISSUE THREAD

**Issue by anmolmahatpurkar** [strapi/strapi#4318]
**Describe the bug**
While adding content to any content type with a media field, the generated form does not have an option to select from the already uploaded files in the File Upload Section.

**Steps to reproduce the behavior**
1. Create a content type with a media field.
2. Try adding an entry in the content type.
3. In the media field, there is no option to select from the already uploaded files

**Expected behavior**
The media field in any content type should allow to select from the already uploaded files in the file upload section.

**Screenshots**
![Screenshot 2019-10-22 at 6 19 57 PM](https://user-images.githubusercontent.com/36692003/67287873-87916e80-f4f9-11e9-93b1-1b191455ceb5.png)

**System**
- Node.js version: 10.16.3
- NPM version:
- Strapi version: 3.0.0-beta.17.2
- Database: PG
- Operating system: MacOS

**Additional context**

**Comment by soupette** [comment]
@anmolmahatpurkar this is the expected behaviour, the possibility to choose between already uploaded files will come with the [media library](https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities) feature that is already planned.
