### ISSUE TITLE
Groups don`t work with MongoDB

### ISSUE THREAD

**Issue by arsen-ch** [strapi/strapi#4322]
**Describe the bug**
Entries with groups cannot be saved and fetched when use MongoDB. In the previous version, everything worked fine.

**Steps to reproduce the behavior**
1. Add group to a type.
2. Create new entry and fill group. 
3. Press save: TypeError: Cannot read property '0' of undefined

**System**
- Strapi version: 3.0.0 beta 17.3
- Database: MongoDB

**Comment by JelmerV-WFC** [comment]
@alexandrebodin I can confirm that this is the case

**Comment by alexandrebodin** [comment]
@JelmerV-WFC I cannot reproduce can you share your json models to test ?

**Comment by JelmerV-WFC** [comment]
@alexandrebodin 

Rsscolumn:
```
{
  "connection": "default",
  "collectionName": "rsscolumn",
  "info": {
    "name": "rsscolumn",
    "description": ""
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "type": {
      "enum": [
        "top",
        "left",
        "right",
        "bottom"
      ],
      "type": "enumeration"
    },
    "website": {
      "model": "website"
    },
    "column_deals": {
      "group": "column_deal",
      "repeatable": true,
      "type": "group"
    }
  }
}
```

Column_deal:
```
{
  "info": {
    "name": "column_deal",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_column_deals",
  "attributes": {
    "deal": {
      "model": "deal"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "text"
    },
    "url": {
      "type": "string"
    },
    "direct_link": {
      "type": "boolean"
    },
    "image": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "button_text": {
      "type": "string"
    },
    "selected_media": {
      "type": "json"
    }
  }
}
```

**Comment by JelmerV-WFC** [comment]
@alexandrebodin the full error is:
```
[2019-10-23T08:45:00.526Z] error TypeError: Cannot read property '0' of undefined
    at markArraySubdocsPopulated (/node_modules/mongoose/lib/document.js:555:48)
    at model.Document.$__init (/node_modules/mongoose/lib/document.js:515:3)
    at model.syncWrapper [as $__init] (/node_modules/kareem/index.js:234:23)
    at model.Document.init (/node_modules/mongoose/lib/document.js:481:8)
    at completeOne (/node_modules/mongoose/lib/query.js:2828:12)
    at model.populate (/node_modules/mongoose/lib/query.js:2083:7)
    at /node_modules/mongoose/lib/model.js:4598:16
    at /node_modules/mongoose/lib/utils.js:264:16
    at next (/node_modules/mongoose/lib/model.js:4071:5)
    at _done (/node_modules/mongoose/lib/model.js:4202:5)
    at _next (/node_modules/mongoose/lib/model.js:4192:7)
    at /node_modules/mongoose/lib/model.js:4598:16
    at /node_modules/mongoose/lib/utils.js:264:16
    at _hooks.execPost (/node_modules/mongoose/lib/query.js:4326:11)
    at /node_modules/kareem/index.js:135:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by alexandrebodin** [comment]
@JelmerV-WFC I just don't have any errors with this model :( must be sth wrond in db. Have you change from a non repeatable to a repeatable or sth ?

**Comment by JelmerV-WFC** [comment]
@alexandrebodin I think it happens after updating from 16.8 to 17.x. And it is indeed database related I think because if I downgrade back to 16.8 I get the same error.

**Comment by alexandrebodin** [comment]
ok I'm pretty sure I know what's going on... it's because the kind value in some ref are in lowercase now and previsouly was in capitalize or sth of that kind...

**Comment by alexandrebodin** [comment]
Well even when I switch from 16.5 to 17.3 I don't have any difference.

**Comment by JelmerV-WFC** [comment]
I can see in a git commit that a coleague of mine changed the name of the field `column_deal` to `column_deals` in the Rsscolumn model. Guess it has something to do with that? How do I test this, what do I need to change in the database?

**Comment by alexandrebodin** [comment]
Renaming didn't break anything for me. Could you send me an extra of the data (hoping you don't have too much data) via slack ?

**Comment by JelmerV-WFC** [comment]
@alexandrebodin sure. Can you message me on Slack what you need exactly?

**Comment by alexandrebodin** [comment]
@arsen-ch are you using mongo atlas ?

**Comment by alexandrebodin** [comment]
The error is coming from an update in mongoose 5.7.6 I'll try to reproduce in a sandbox to create an issue on there repo. in the meantime you should use lock the mongoose version to 5.7.4

I'll be release a new beta to lock the version and fix this.
