### ISSUE TITLE
Feature or help wanted: Query Image width/height to prevent browser reflow

### ISSUE THREAD

**Issue by secretlifeof** [strapi/strapi#4323]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I am wondering if it would be possible to receive the width of an image, from a GraphQL query? The image size can be queried. The reason being to prevent browser reflow when adding images.

A possibility is using javascript client side. But is that the best solution when doing SSR?

```
let image = new Image()
image.src = 'https://image_source'
image.onload = () => {
  { height, width } = image;
  const ratio = width / height;
}
```

Still feeling new, I guess there might be an easier solution that I have not thought of. I would feel happy if somebody could point me in the right direction.

Thank you!

**Comment by lauriejim** [comment]
Hello! Thank you for this feature request.
Can you please add it as a comment of this roadmap feature card, please.
https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities

I close this issue.
Thank you for this insight.
