### ISSUE TITLE
Review validation layer

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#4324]
### Introduction
I create this issue to avoid other issues related to the same topic.

## Description
Currently, if you are adding a `min` / `max` limit or `default value`,  will not be applied in the REST routes.
Only `required` and `unique` constraints work.

`min` / `max` will only be applied in the admin panel.

## Contribution

If you want to work on this topic, I suggest you open an RFC on the following repo [strapi/rfcs](https://github.com/strapi/rfcs)

**Comment by derrickmehaffy** [comment]
FYI @lauriejim the default value also isn't applied to the REST either

**Comment by lauriejim** [comment]
Fixed in the stable
