### ISSUE TITLE
Graphql: Nested objects returns null

### ISSUE THREAD

**Issue by anmolmahatpurkar** [strapi/strapi#4326]
**Describe the bug**
Fetching for nested objects returns null in response

**Expected behavior**
Should return the respective data in the response

**Screenshots**
![Screenshot 2019-10-22 at 9 52 43 PM](https://user-images.githubusercontent.com/36692003/67308034-195ba480-f517-11e9-8808-0d72dd7be84d.png)

**System**
- Node.js version: v10.16.3
- NPM version:
- Strapi version: 3.17.3
- Database: Postgres
- Operating system: MacOS

**Comment by pouyamiralayi** [comment]
Hi! similarly i am experiencing [this](https://github.com/strapi/strapi/issues/3784) in v16.8.
mine is a simple delete mutation.
cheers!

**Comment by alexandrebodin** [comment]
@anmolmahatpurkar Can you verify that when you are running only one query at once they work (e.g sites or logos) ?

**Comment by anmolmahatpurkar** [comment]
@alexandrebodin No they don't. Same issue when running one query at a time.

<img width="1141" alt="Screenshot 2019-10-23 at 12 12 46 PM" src="https://user-images.githubusercontent.com/36692003/67365070-852d2400-f58e-11e9-8bc5-2117446697a7.png">

Also important to note the `darkRectangle` is a group in this case. 

```
Site: Content Type
Logo: Content Type
    darkRectangle: group

Site has and belongs to one logo.
```

```
darkRectangle: {
    src: Field Type Media
    alt: Field Type String
}
```

**Comment by anmolmahatpurkar** [comment]
Just confirming. The issue still exists after upgrading to 3.0.0-beta.17.4.

**Comment by alexandrebodin** [comment]
@anmolmahatpurkar Can you share the json files of your models

**Comment by anmolmahatpurkar** [comment]
Logo.settings.json

```
{
	"connection": "default",
	"collectionName": "logos",
	"info": {
		"name": "logo",
		"description": ""
	},
	"options": {
		"increments": true,
		"timestamps": ["created_at", "updated_at"],
		"comment": ""
	},
	"attributes": {
		"name": {
			"type": "string"
		},
		"darkRectangle": {
			"group": "image",
			"type": "group"
		},
		"darkSquare": {
			"group": "image",
			"type": "group"
		},
		"lightRectangle": {
			"group": "image",
			"type": "group"
		},
		"lightSquare": {
			"group": "image",
			"type": "group"
		},
		"whiteMonotoneRectangle": {
			"group": "image",
			"type": "group"
		},
		"whiteMonotoneSquare": {
			"group": "image",
			"type": "group"
		},
		"blackMonotoneRectangle": {
			"group": "image",
			"type": "group"
		},
		"blackMonotoneSquare": {
			"group": "image",
			"type": "group"
		},
		"site": {
			"model": "site",
			"via": "logo"
		}
	}
}
```

Site.settings.json
```
{
	"connection": "default",
	"collectionName": "sites",
	"info": {
		"name": "site",
		"description": ""
	},
	"options": {
		"increments": true,
		"timestamps": ["created_at", "updated_at"],
		"comment": ""
	},
	"attributes": {
		"locale": {
			"model": "locale",
			"via": "site"
		},
		"companyName": {
			"type": "string"
		},
		"twitterSiteID": {
			"type": "string"
		},
		"logo": {
			"model": "logo",
			"via": "site"
		},
		"siteMeta": {
			"group": "meta",
			"type": "group"
		},
		"social": {
			"group": "social",
			"required": true,
			"type": "group"
		}
	}
}
```

**Comment by anmolmahatpurkar** [comment]
@alexandrebodin Here's a small reproducible to confirm the issue. Will delete the repo once you are through with it.
https://github.com/anmolmahatpurkar/strapi-graphql-bug

<img width="1391" alt="Screenshot 2019-10-24 at 2 30 15 AM" src="https://user-images.githubusercontent.com/36692003/67433716-3de27a00-f606-11e9-8867-8c0f1c8a01b0.png">

**Comment by alexandrebodin** [comment]
Thanks !
