### ISSUE TITLE
can GitHub provider redirect to api with code? then redirect to front end with token and user profile 

### ISSUE THREAD

**Issue by igigi** [strapi/strapi#4327]
**Describe the bug**
GitHub provider can not redirect to api with code, then redirect to front end with token and user profile 

**Steps to reproduce the behavior**
1. go to admin Roles & Permissions plugin config page
2.config GitHub provide with "http://localhost:8000/callback"
3. front end login with GitHub to "http://localhost:1337/connect/github"
4. after authorization, redirected to "http://localhost:8000/callback?code=xxxx", not redirect to "http://localhost:ocalhost:1337/callback?code=xxxx"

**Expected behavior**
want to  redirect to "http://localhost:ocalhost:1337/callback?code=xxxx", then with token and user profile to front end

**Screenshots**

**Code snippets**

**System**
- Node.js version: v10.13.0
- NPM version: 6.4.1
- Strapi version: v3.0.0-beta.17.2
- Database: mongo
- Operating system: macOS Mojave

**Additional context**

**Comment by igigi** [comment]
**Describe the bug**
GitHub provider can not redirect to api with code, then redirect to front end with token and user profile 

**Steps to reproduce the behavior**
1. go to admin Roles & Permissions plugin config page
2.config GitHub provide with "http://localhost:8000/callback"
3. front end login with GitHub to "http://localhost:1337/connect/github"
4. after authorization, redirected to "http://localhost:8000/callback?code=xxxx", not redirect to "http://localhost:ocalhost:1337/callback?code=xxxx"

**Expected behavior**
want to  redirect to "http://localhost:ocalhost:1337/callback?code=xxxx", then with token and user profile to front end

**Screenshots**

**Code snippets**


**System**
- Node.js version: v10.13.0
- NPM version: 6.4.1
- Strapi version: v3.0.0-beta.17.2
- Database: mongo
- Operating system: macOS Mojave

**Additional context**

**Comment by igigi** [comment]
Can you open this issue?

**Comment by derrickmehaffy** [comment]
Ah sorry forgot to reopen

**Comment by lauriejim** [comment]
Hello @igigi !
It's not how the OAuth works.
[Here is an article](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2) that explains the 0Auth flow.
So what you are trying to do is not possible.

**Comment by igigi** [comment]
Article that you provide is very helpful, thanks.

maybe Expected behavior should be modified, it is that strapi api complete all  authorize work, then return user profile and strapi api token to front end.

is it possible?

My project is Gatsby react application and strapi api. GitHub login use strapi GitHub provider. like this:
https://store.gatsbyjs.org/

**Comment by geosigno** [comment]
+1 
How to manage that http://localhost:ocalhost:1337/callback?code=xxxx send the token back to the client side?

**Comment by lauriejim** [comment]
Hello @geosigno !
This react app example to use the Strapi provider login will help you to understand how to deal with if with Strapi 
https://github.com/strapi/strapi-examples/tree/master/login-react/react-login-front-end-app
