### ISSUE TITLE
Settings Manager Icon Asset Missing

### ISSUE THREAD

**Issue by eddiewang** [strapi/strapi#4329]
**Describe the bug**

This asset is missing: 
https://raw.githubusercontent.com/strapi/strapi/master/packages/strapi-plugin-settings-manager/admin/src/assets/images/logo.svg?sanitize=true

It's used across many Strapi versions.

**Comment by derrickmehaffy** [comment]
The settings manager is going to be removed and depreciated.

Marking as closed
