### ISSUE TITLE
Fix your CI Enviroment

### ISSUE THREAD

**Issue by xstable** [strapi/strapi#4331]
Your CI-Enviroment stuck on an apt-get command. Maybe you need to manually fix this, so that CI work again. 

The result of this issue is, that all PR's here in Github will get a `fail` notice for the CI-Check.

![image](https://user-images.githubusercontent.com/1778068/67365960-e6df9500-f572-11e9-9132-0579bc4f87ec.png)

**Comment by alexandrebodin** [comment]
Hi @xstable,
I looked at multiple PRs that are open and the CI just runs correctly. Travis sometimes just fails for no reason and needs a restart of the jobs. you can push again on your branch to run them again (amend a commit for example) 

I'm closing this as this is working fine in all the other PRs

**Comment by derrickmehaffy** [comment]
It's a travis problem their network can be really slow at times, which causes a stall and travis kills free users during the wait
