### ISSUE TITLE
naming a field "id" causes data loss

### ISSUE THREAD

**Issue by rpalmite** [strapi/strapi#4333]
**Describe the bug**

**Steps to reproduce the behavior**
1. Create a content type
2. Name a string field "id"
3. Create a couple other fields (say description etc)
4. Create a couple instances of the above type (including typing in ids)
5. View the new record and notice the id field is an auto-generated guid and not the id you entered into step 4

**Expected behavior**
It should keep the entered id field values

**Screenshots**

**System**
- Node.js version: 
- NPM version:
- Strapi version: Strapi v3.0.0-alpha.26.2
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment]
The ID name is. Reserved word, @soupette you want to add that to the list? I know the beta doesn't allow it.

@rpalmite strapi alpha is no longer supported, for that reason I am closing this as it won't be fixed on alpha.
