### ISSUE TITLE
JSON:API support

### ISSUE THREAD

**Issue by Jimmy89** [strapi/strapi#4335]
**Description**
In older posts (from Strapi v2 announcements) I saw that JSON:API support (https://jsonapi.org/format/) was mentioned as a future feature (as a plugin, like GraphQL). I wasn't able to find back the link. In the current v3.0 beta release I cannot find anything about this topic. I'm wondering what happened with this feature and I'm curious what the rationales where behind the decisions. 

**Additional context**
My company is currently trying to work with JSON:API, together with Open API. Those two can be used side-by-side, JSON:API tightens the the params used in your API while Open API is great for documenting this.

**Comment by alexandrebodin** [comment]
Hi @Jimmy89 Thank you for suggesting this. 

Right now this is not on our roadmap. It will certainly not be implemented as the default API standard in Strapi, but someone can eventually create a plugin that would generate APIs that implement the JSON:API standard.

Feel free to submit an idea on https://portal.productboard.com/strapi/1-public-roadmap/tabs/3-planned ;) 

I'm Closing this issue as we have enough information.

**Comment by glbatistabh** [comment]
Good evening and apologies for resurrecting the topic. I would like to know if there is already a plugin for Strapi V4.2 that implements the JSONAPI standard? I searched but couldn't find any plugin that does this.

**Comment by alexandrebodin** [comment]
Hello @glbatistabh the v4 fo Strapi implements it partially already but we don't plan on going all the way there for the moment and I don't think any plugin exists for this at the moment. Have you tried looking on npm directly ?
