### ISSUE TITLE
uuid applied on relation if primaryKeyType is uuid

### ISSUE THREAD

**Issue by Tcharlyson** [strapi/strapi#4339]
**Describe the bug**
I have an id (primary key) type set to uuid and a column referencing another table column with the association "oneWay". Unfortunately, this second column (addressId) will take the type uuid instead of an integer.

**Steps to reproduce the behavior**
```
{
  "connection": "default",
  "collectionName": "establishments",
  "info": {
    "name": "establishment",
    "description": "Établissement"
  },
  "options": {
    "idAttribute": "id",
    "idAttributeType": "uuid",
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "name": {
      "required": true,
      "type": "string"
    },
    "frequency": {
      "type": "float",
      "required": true
    },
    "addressId": {
      "model": "address"
    }
  }
}
```
**Expected behavior**
An entity with a uuid as a primary key should be able to relate to another entity using the integer id as a foreign key

**Screenshots**
<img width="299" alt="Screenshot 2019-10-23 at 16 20 55" src="https://user-images.githubusercontent.com/11333362/67402616-1ca36e80-f5b1-11e9-8d28-1de1ed1fcac2.png">

**System**
- Node.js version: 12.1.0
- NPM version:
- Strapi version: 3.0.0-beta.17.3
- Database: postgres
- Operating system: MacOS

**Comment by Tcharlyson** [comment]
Check line 388 of buildDatabaseShema.js from strapi-hook-bookshelf

**Comment by lauriejim** [comment]
Hello @Tcharlyson , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free to investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment]
I'm closing this issue since we remover this customization.
This will be completely review in the new database layer.
