### ISSUE TITLE
uuid treated as a relation in backoffice entity configuration

### ISSUE THREAD

**Issue by Tcharlyson** [strapi/strapi#4340]
**Describe the bug**
When using uuid as a primary key, it is treated as a relation instead of a simple property (uuid). Icon for uuid doesn't exist as well.

**Screenshots**
<img width="824" alt="Screenshot 2019-10-23 at 16 33 27" src="https://user-images.githubusercontent.com/11333362/67403913-e4049480-f5b2-11e9-836a-b5e1db4f0588.png">

**System**
- Node.js version: 12.1.0
- NPM version:
- Strapi version: 3.0.0-beta.17.3
- Database: postgres
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
UUID support isn't entirely there yet @Tcharlyson.

**Comment by Tcharlyson** [comment]
> UUID support isn't entirely there yet @Tcharlyson.

Okay thanks for letting me know ! @derrickmehaffy

**Comment by lauriejim** [comment]
Hello @Tcharlyson !
Something that could be cool is asking to @Aurelsicoko to give you an icon for `uuid`.
And create a PR to fix it.
Thank you.
