### ISSUE TITLE
As super-admin I can see the user password hash

### ISSUE THREAD

**Issue by Tcharlyson** [strapi/strapi#4341]
**Describe the bug**
As super-admin I can see the user password hash

**Expected behavior**
The password field needs to be empty instead of containing the hash of the user password

**System**
- Node.js version: 12.1.0
- NPM version:
- Strapi version: 3.0.0-beta.17.3
- Database: postgres
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
I did mention this to @soupette a while back. @alexandrebodin is this something better wiped from the backend of strapi-admin ?

**Comment by alexandrebodin** [comment]
Yes this should not be returned by the api. BUt if I do that the front breaks. This is a legacy thing for now.

**Comment by Tcharlyson** [comment]
The real problem here is, if we want to just modify the username of the user and we don't empty the password field, it will replace the password in database by the hashed one

**Comment by alexandrebodin** [comment]
> The real problem here is, if we want to just modify the username of the user and we don't empty the password field, it will replace the password in database by the hashed one.

Nope it wont :) there is a special check to avoid this. I agree with you that it should be removed but for now it doesn't cause issues

**Comment by derrickmehaffy** [comment]
The front breaks o_O

**Comment by soupette** [comment]
It doesn't really breaks it just won't let you update your user. I will take care of fixing that with the next feature.

**Comment by alexandrebodin** [comment]
> The front breaks o_O

The form expects data so if we don't send it, it will complain. That's why we need to change the code on both sides to avoid sending it.

**Comment by jozefcipa** [comment]
Any update on this issue?

**Comment by derrickmehaffy** [comment]
@lauriejim I'm gonna leave this one here as I think it's a bug not a discussion. This should eventually be fixed even if it's not a priority
