### ISSUE TITLE
Hide / make private timestamps, _id, id and __v with MongoDB

### ISSUE THREAD

**Issue by lambertkevin** [strapi/strapi#4342]
**Describe the bug**
There is no way with the beta to make private some of the attributes through the model's JSON

**Steps to reproduce the behavior**
- Create a a new model with timestamps for example.
- Try to add it manually to the attributes in the model's JSON.
- Make it private.
- The API response will still contain the timestamps.
(Also valid with id, _id, and __v)

**Expected behavior**
We should be able to hide those attributes from the API response

**System**
- Node.js version: v11.3.0
- NPM version: 6.5.0
- Strapi version: v3.0.0-beta.17.2
- Database: Mongodb
- Operating system: MacOS/Debian

**Comment by mswaidan** [comment]
Have you tried using the `sanitizeEntity` function? [Docs](https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#utils)

**Comment by lauriejim** [comment]
Hello @lambertkevin !
Yes, you are right!

I don't think it will be a priority for us.
If you want this "feature", I suggest you open an RFC on [strapi/rfcs](https://github.com/strapi/rfcs)
And if the RFC is approved, open a PR to contribute to Strapi.
