### ISSUE TITLE
Field labels, description and placeholders are not git trackable

### ISSUE THREAD

**Issue by igorasantos** [strapi/strapi#4346]
**Describe the bug**
After I create a data project aimed to reproduce it, the labels, descriptions and placeholders set on the "template project", and track then on a GH repo, they doesn't appear on a repo clone (only the content type fields).

**Steps to reproduce the behavior**
1. Create a new Strapi project
2. Start the git tracking (`git init`, `git remote add origin`...)
3. Create a new Content type with some string field and save it.
4. Go to the content type you created and click to add one entry
5. Click on "configure the layout"
6. Click on the field created before.
7. Change the default values of label, description and placeholders.
8. Get back to the "add one entry" screen and check the effect.
8. Logout from Strapi and stop the server.
9. Commit the changes on git and push them.
10. On a new directory, clone the repo choosing other name.
11. `yarn instal`or just `yarn` to install the dependencies.
12. `yarn develop` to run the Strapi server
13. Create new admin and log in.
14. Go to the content type created before and click to add one entry.
15. Note that the setting (label, description and placeholder) is no longer there, just the string field.

**Expected behavior**
Content type fields configurations (label, description and placeholder) present when I clone my Strapi projects.

**System**
- Node.js version: v11.6.0
- NPM version: 6.5.0 (but I'm using `yarn`).
- Yarn version: 1.13.0
- Strapi version: strapi@3.0.0-beta.17.4"
- Database: SQLite
- Operating system: Ubuntu 16.04 LTS

**Additional context**
I'm trying to set up a CMS to be used by non specialists users (different university administrative units). So, the possibility of these configurations being trackable will determine if my project will be effective or not.

**Comment by derrickmehaffy** [comment]
This topic has been brought up a few times, those settings are stored in the database. I too would prefer to track these in Git and make them **not** changeable in production, but Strapi have stated for now that is how it is and they will likely add some way to dump them into files and reimport to a production database but they won't be "read" from the files.

**Comment by igorasantos** [comment]
Hmmm
That's a little sad...
But thanks for the information!

**Comment by lauriejim** [comment]
Hello, as Derrick said, we discuss a lot about this topic.
Some UI information is stored in a database. So they are not trackable via git.
There is the same issue with `permissions`. So the solution we will work on is a helper(probably a command line) that will help you to migrate your data.

In any case, thank you for this feedback.
I close this topic.

**Comment by beakid** [comment]
Any news regarding this? Especially labels and descriptions really need to be configurable in the config JSON files.

**Comment by derrickmehaffy** [comment]
See this PR for the docs @beakid https://github.com/strapi/strapi/pull/6489/files
