### ISSUE TITLE
Bootstrap function in plugin error 

### ISSUE THREAD

**Issue by obaidh** [strapi/strapi#4349]
**Describe the bug**
strapi framework , itry to deployments to Heroky but I error massage like this :
`2019-10-24T03:36:45.969306+00:00 app[web.1]: [2019-10-24T03:36:45.968Z] error Bootstrap function in plugin "content-manager" failed`

I deployments with new projects its work fine only when I create strapi quick start, but when I create with manual setting and clean without adding anything or if additional or building any content. get this error Bootstrap function .

**Steps to reproduce the behavior**

**Expected behavior**
deployments without any issue 

**System**
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
- Strapi version: I work with different version beta and alpha same issue 
- Database: mangos 
- Operating system: Heroku

**Additional context**

**Comment by lauriejim** [comment]
Hello @obaidh !

I just followed this documentation about the deployment on Heroku https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku
And also the MongoDB Atlas database docs https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#install-on-atlas-mongodb-atlas

All work fine. Make sure your database configuration for the production environment is correct.
