### ISSUE TITLE
GRAPHQL cannot use where clause with OR 

### ISSUE THREAD

**Issue by daehruoydeef** [strapi/strapi#4355]
**Describe the bug**
Filtering using a where clause and a OR folled by a array of filters are not working.

**Steps to reproduce the behavior**
1. create a content type called group with just a title
2. add 2 groups add the titles "one" and "two"
3 use query:
`query {
    groups (where: {
        OR[{title: "one"}, {title: "two"}]
    })
    {title}
}
`

**Expected behavior**
allow filtering using OR operator

**System**
- Node.js version: v10
- NPM version: 6.12
- Strapi version: 3.0.0-beta.17.3
- Database: MongoDB
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
Or filters aren't supported yet in GraphQL, there was mention of support for it coming after the new DBAL layer is done.

**Comment by lauriejim** [comment]
Hello @daehruoydeef !
Thank you for this report. An issue already exist on this topic https://github.com/strapi/strapi/issues/3194
