### ISSUE TITLE
Deep filter and filter on date fail

### ISSUE THREAD

**Issue by mswaidan** [strapi/strapi#4356]
**Describe the bug**
A url query that contains both a deep filter and a timestamp based param always returns zero results.
 
**Steps to reproduce the behavior**
1. Send a query to a model with both a deep filter and a timestamp param, like `www.example.com/events?user.office=Beijing&createdAt_gt=2019-1024
2. Result will be an empty array.

**Expected behavior**
Result should be an array containing documents that match the query parameters.

**Code snippets**
I found a few lines in strapi-utils/lib/buildQuery.js that could be contributing to the problem:

1. This line returns `undefined` for `createdAt` and `updatedAt` attributes. I think it should be returning `timestamp`:
https://github.com/strapi/strapi/blob/038bbb3e206b27b2d60b5d1689c4451faebe6b3a/packages/strapi-utils/lib/buildQuery.js#L125

2. Because `type` is `undefined`, this function returns the attribute value as a `string`, but it needs to be a `Date` (or converted elsewhere to a MongoDB `ISODate` for the query to perform as expected:
https://github.com/strapi/strapi/blob/038bbb3e206b27b2d60b5d1689c4451faebe6b3a/packages/strapi-utils/lib/buildQuery.js#L62-L84

For now I'm working around this by:
``` 
if (attribute == 'createdAt' || attribute == 'updatedAt') { 
    type = 'timestamp' 
} 
```
after line 128, and then:
```
    case 'timestamp':
      return new Date(value)
```  
in the `castValueToType` function, but it's a pretty hacky solution so I'm not going to open a PR. Just flagging this for someone who knows their way around the amazing ❤️Strapi❤️ better than I do.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.17.4
- Database: MongoDB
- Operating system: Ubuntu flavored WSL

**Comment by mswaidan** [comment]
How annoying, somehow github wiped the reset the text I spend 20 mins on back to the template. Will edit.

**Comment by derrickmehaffy** [comment]
No problem @mswaidan :P I won't close it :wink:

**Comment by mswaidan** [comment]
Thanks @derrickmehaffy ! Fixed.

**Comment by lauriejim** [comment]
Hello @mswaidan !
Can you please share your models, please.
It will help me to reproduce your issue.

**Comment by mswaidan** [comment]
Thanks for looking into this @lauriejim!

Two models in question here, neither model has modifications to the lifecycle callbacks. Let me know if there's anything else you need.

1. Event.settings.json:
```
{
  "connection": "default",
  "collectionName": "events",
  "info": {
    "name": "event",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "platform": {
      "type": "string"
    },
    "properties": {
      "type": "json"
    },
    "user": {
      "model": "user",
      "plugin": "users-permissions",
    }
  }
}
```
2. User.settings.json:
```
{
  "connection": "default",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": [
      "created_at",
      "updated_at"
    ]
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "name": {
      "type": "string"
    },
    "office": {
      "type": "string"
    }
  }
}
```

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
Feel free to submit a PR event if you are not sure.

**Comment by mswaidan** [comment]
👌 Will try to get one in this week.

**Comment by Convly** [comment]
Hello @mswaidan, I tried to reproduce the issue, but it seems resolved by now. Can you try again and tell me if you still experience any unexpected results?

**Comment by alexandrebodin** [comment]
Hi, I'm closing this issue as we haven't been able to reproduce with the latest version of strapi. Feel free to comment if you end up getting this issue again :D
