### ISSUE TITLE
How to set role to admin or login admin panel with role authenticated

### ISSUE THREAD

**Issue by Eric0201** [strapi/strapi#4358]
**Describe the topic**
Hello, I want set limit role for user login admin panel. Example i have 2 users, one administrator and one editor, i want editor can login admin panel but active role with content-types, hide all plugin content-types builder, content-manager, role permissions, upload ... Please suggest solution help me.

**Comment by derrickmehaffy** [comment]
Hello,

Normal users can't login to the admin panel, you can see the following blog post that explains this: https://strapi.io/blog/why-we-split-the-management-of-the-admin-users-and-end-users?redirectPage=1

Eventually the adminUI users will have split permissions and allow for more "normal" type users that will be able to login (see this feature roadmap: https://portal.productboard.com/strapi/1-public-roadmap/c/8-administrators-roles-permissions )
