### ISSUE TITLE
Appending a value to an existing relation field array via GraphQL mutation

### ISSUE THREAD

**Issue by RanaOsamaAsif** [strapi/strapi#4366]
**Strapi Version Beta.17.3**
I'm trying to add a user to my current user's following list which is a relation array but executing this mutation overrides the existing array and the value given in the mutation is stored in the array after mutation.

Is it possible? How can I add a new element in the array using mutation?

```
mutation UpdateProfile($fields: updateUserInput!){
  updateUser(input: $fields){
    user{
      id
      following{
        id
      }
    }
  }
}
```
Variables:
```
{
   "fields":{
    		"where": {"id": "5daafac2c404f83532248be2"},
                      "data":{
                        "following": [ "5d95f6133da38d38c144569f" ]
                      }
               }
}
```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by dlolsen** [comment]
@RanaOsamaAsif Did you figure anything out? 

I'm curious if this can be done in a single Strapi GraphQL mutation, or if it requires a separate query to collect existing values, append a new one, and then update with the new array.
