### ISSUE TITLE
I added Json Field in Content Type but I can't submit data in json format in postman.

### ISSUE THREAD

**Issue by mtrucc** [strapi/strapi#4367]
**Describe the topic**
I added Json Field in Content Type but I can't submit data in json format in postman.

**Your suggestions for this topic**
I want to submit a json formatted data and save it. If not, I will use string.

**Screenshots**
![2019-10-26 054535](https://user-images.githubusercontent.com/16724665/67607004-a58af780-f7b5-11e9-949b-98b7dbe682dc.png)
![2019-10-26 055538](https://user-images.githubusercontent.com/16724665/67607019-ac196f00-f7b5-11e9-8a1a-75decb3f264f.png)

**Code snippets**
`var form = new FormData();
form.append("username", "admin22234");
form.append("email", "admin@adm3421n.admin");
form.append("password", "admin12331");
form.append("phone", "1234567890");
form.append("name", "adminaaa");
form.append("jsontest", "{\"name\":\"123\"}");

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://localhost:1337/auth/local/register",
  "method": "POST",
  "headers": {
    "User-Agent": "PostmanRuntime/7.16.3",
    "Accept": "*/*",
    "Cache-Control": "no-cache",
    "Postman-Token": "96807e43-d67c-4844-9a71-bcd7775050c1,de0b3cd3-ca17-4db7-a381-bccd6fa580e4",
    "Host": "localhost:1337",
    "Content-Type": "multipart/form-data; boundary=--------------------------230921094001559629707472",
    "Accept-Encoding": "gzip, deflate",
    "Cookie": "csrfToken=nXfmvRukBm3WasSZw4HG-HvS",
    "Content-Length": "1332",
    "Connection": "keep-alive",
    "cache-control": "no-cache"
  },
  "processData": false,
  "contentType": false,
  "mimeType": "multipart/form-data",
  "data": form
}

$.ajax(settings).done(function (response) {
  console.log(response);
});`

**Additional context**
I know this may be a very stupid question, but I haven't found any good way at the moment.

**Comment by pouyamiralayi** [comment]
Hi there! have you tried form-urlencoded instead of form-data?
cheers!

**Comment by lauriejim** [comment]
Hello @mtrucc !
You have to use the `raw` format.
And after select the `application/json`

![Uploading Screenshot 2019-10-27 at 3.04.15 PM.png…]()

**Comment by mtrucc** [comment]
Hi, thank you very much for your help. I seem to have found the problem. I added the Content Type name to testjson.
Then submit the form to http://localhost:1337/testjsons
At this time, you can submit the content as Json Field in Content Type
However, if you are a registered user, submitting Json Field is not supported.
Need to submit it with the method you provided, so the problem is solved. Thank you very much.
