### ISSUE TITLE
Image upload on custom CKEditor

### ISSUE THREAD

**Issue by sgtpsibin** [strapi/strapi#4369]
Hello all, i first time using Strapi, i tried to replace default editor with CKEditor by follow: https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi.

All look good, but i can't upload image. In the console, i see the warning about missing Upload adapter in CKEditor.

Image uploading is important. Do we have any solution for this?

**Comment by pouyamiralayi** [comment]
Hi there! check this [integration guide](https://ckeditor.com/docs/ckfinder/demo/ckfinder3/samples/ckeditor.html).
cheers!

**Comment by sgtpsibin** [comment]
Hi @pouyamiralayi, I am very happy to receive your support. I tried to config CKEditor with upload url of Strapi. And it still error. I hope to learn more from you.
![image](https://user-images.githubusercontent.com/50952024/67631114-921a8200-f8c4-11e9-85a0-d3c8b257fac6.png)

**Comment by derrickmehaffy** [comment]
As this is not a bug with strapi I'm marking this as closed. You can continue the discussion if you wish.

**Comment by loongmxbt** [comment]
@sgtpsibin Hi, any luck on image uploading?

**Comment by loongmxbt** [comment]
I have do some searching.
https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html
Official Image Uploaders
1. Easy Image - upload to a cloud CKEditor offers
2. CKFinder - a browser-based file uploader with its server-side connectors (PHP and ASP.NET).
3. Simple adapter - uploading images to your server using the XMLHttpRequest API with a minimal editor configuration.
4. Base64 adapter

I think the Simple Adapter may be best suitable for Strapi.
https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html
```
import SimpleUploadAdapter from '@ckeditor/ckeditor5-upload/src/simpleuploadadapter';

ClassicEditor
    .create( document.querySelector( '#editor' ), {
        plugins: [ SimpleUploadAdapter, ... ],
        toolbar: [ ... ],
        simpleUpload: {
            // The URL that the images are uploaded to.
            uploadUrl: 'http://example.com',

            // Headers sent along with the XMLHttpRequest to the upload server.
            headers: {
                'X-CSRF-TOKEN': 'CSFR-Token',
                Authorization: 'Bearer <JSON Web Token>'
            }
        }
    } )
    .then( ... )
    .catch( ... );
```

There is a Classic Editor configuration here. But I don't know how to configure the React Version. e.g. access the Bearer token.

**Comment by sgtpsibin** [comment]
I have back to default editor

**Comment by JelmerV-WFC** [comment]
Hi @sgtpsibin!

I created a custom CKEditor build to make it work for strapi.

`yarn add ckeditor-build-with-simple-upload-provider-strapi`
or
`npm install ckeditor-build-with-simple-upload-provider-strapi`

Only thing you need to do is change the `./extensions/content-manager/admin/src/components/CKEditor/index.js` file: 

```
import React from 'react';
import PropTypes from 'prop-types';
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from 'ckeditor-build-with-simple-upload-provider-strapi';
import styled from 'styled-components';

const Wrapper = styled.div`
  .ck-editor__main {
    min-height: 200px;
    > div {
      min-height: 200px;
    }
  }
`;

const Editor = ({ onChange, name, value }) => {
  return (
    <Wrapper>
    <CKEditor
  editor={ClassicEditor}
  data={value}
  onChange={(event, editor) => {
    const data = editor.getData();
    onChange({ target: { name, value: data } });
  }}
  config={{
    simpleUpload: {
      uploadUrl: `${strapi.backendURL}/upload`,
    }
  }}
  />
  </Wrapper>
);
};

Editor.propTypes = {
  onChange: PropTypes.func.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string.isRequired,
};

export default Editor;
```

If your upload route needs authentication then use the following `./extensions/content-manager/admin/src/components/CKEditor/index.js` file (I don't know if this is the best way to receive the jwt token. Maybe @soupette can say something about this): 

```
import React from 'react';
import PropTypes from 'prop-types';
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from 'ckeditor-build-with-simple-upload-provider-strapi';
import styled from 'styled-components';

const Wrapper = styled.div`
  .ck-editor__main {
    min-height: 200px;
    > div {
      min-height: 200px;
    }
  }
`;
const TOKEN_KEY = 'jwtToken';
const parse = JSON.parse;

const Editor = ({ onChange, name, value }) => {

  let jwtToken = '';

  if (localStorage && localStorage.getItem(TOKEN_KEY)) {
    jwtToken = parse(localStorage.getItem(TOKEN_KEY)) || null;
  }

  if (sessionStorage && sessionStorage.getItem(TOKEN_KEY)) {
    jwtToken = parse(sessionStorage.getItem(TOKEN_KEY)) || null;
  }

  return (
    <Wrapper>
    <CKEditor
  editor={ClassicEditor}
  data={value}
  onChange={(event, editor) => {
    const data = editor.getData();
    onChange({ target: { name, value: data } });
  }}
  config={{
    simpleUpload: {
      // The URL that the images are uploaded to.
      uploadUrl: `${strapi.backendURL}/upload`,

        // Headers sent along with the XMLHttpRequest to the upload server.
        headers: {
          Authorization: "Bearer " + jwtToken
      }
    }
  }}
  />
  </Wrapper>
);
};

Editor.propTypes = {
  onChange: PropTypes.func.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string.isRequired,
};

export default Editor;
```

After you did all that, don't forget to run `strapi build` or `yarn build` or `npm run build`!

**Comment by chernandezweb** [comment]
Hi  @sgtpsibin,

I just tested  the solution @JelmerV-WFC  mentionned.

It works perfectly.

**Comment by sgtpsibin** [comment]
Thanks for all, everyone is awesome

**Comment by NicoCoco1163** [comment]
Hi, @JelmerV-WFC 

thanks for your job

I'm getting jwtToken by built-in func, and it works


```
import { auth } from 'strapi-helper-plugin';

const jwtToken = auth.getToken();
```

**Comment by JelmerV-WFC** [comment]
@NicoCoco1163 Thats a better solution! Will change that in my comment :)
