### ISSUE TITLE
No docs on strapi-plugin-graphql

### ISSUE THREAD

**Issue by andyjessop** [strapi/strapi#437]
There has been mention of a graphql plugin, and it seems available on npm: https://www.npmjs.com/package/strapi-plugin-graphql

But there are no associated docs - can you give an update on its development for v3?

**Comment by soupette** [comment]
Hi @andyjessop the development of this plugin hasn't started yet.

**Comment by andyjessop** [comment]
That's a tad disappointing - I garnered from other discussions that development was well under way. Can I ask a follow up question: is there a timescale for this plugin, or should I start my new project on an earlier version?

**Comment by soupette** [comment]
The graphql plugin is in our radar. Hoverwer, we don't know yet when the development is going to start. You can upvote the feature [on our requested features page](https://strapi.io/vote) to make it the most wanted feature.

**Comment by lethak** [comment]
Hi, I was considering using strapi for a new project and I feel like the lack of a 'native' GraphQL support is going to be a problem. You guys are doing a dream CMF, shame you dropped this with 3.x.
