### ISSUE TITLE
Deleting file from 'Files Upload' breaks any other content that has it as a 'Media' relation

### ISSUE THREAD

**Issue by pouyamiralayi** [strapi/strapi#4372]
Hello there! i am facing the same scenario in [this issue](https://github.com/strapi/strapi/issues/2956).
i have already posted the [details](https://github.com/strapi/strapi/issues/2956#issuecomment-546357548) in the referenced issue.
cheers!

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
