### ISSUE TITLE
Admin login permission error on v3.0.0-beta.17.4

### ISSUE THREAD

**Issue by arnoldgamboa** [strapi/strapi#4373]
**Describe the bug**
After I updated on beta 17.4, I can't login anymore and is getting a `403 permissions/init` error. See screenshot

**Steps to reproduce the behavior**
1. Upgrade to beta 17.4
2. Login to admin
2.1 This is particulary seen on instances I've deployed. Locally, It's weird that it's working.

**Screenshots**
![Screen_Shot_2019-10-28_at_11_58_16_AM](https://user-images.githubusercontent.com/587603/67651194-e5e7a280-f97a-11e9-98ca-a0193b80987f.jpg)

**System**
- Node.js version: 10
- NPM version:
- Strapi version: Beta 17.4
- Database: MySQL
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment]
Generally this is caused by slow response from a remote database, can you try bumping up the wait timeout in `config/hook.json` to something like `10000`

**Comment by arnoldgamboa** [comment]
Database is within the same machine though, so latency is not an issue.

-Arnold

**Comment by derrickmehaffy** [comment]
We will need more information as to your setup as we had seen previous issues related to this and wasn't able to reproduce it outside an extremely slow database.

**Comment by alexandrebodin** [comment]
@arnoldgamboa DO you have any error in your console so we can get more details ? 

If you downgrade back to a previous version does it work again ?

**Comment by arnoldgamboa** [comment]
1. There's no console error. I know that's weird. It's most like a front
end issue I guess? But really it's not. I've tested this on other browsers
and also on Incognito to be sure. Same result.

2. Another weird thing is when I downgraded to 16, result is the same.

-Arnold

**Comment by alexandrebodin** [comment]
@arnoldgamboa From what I gather the issue is because the init permissions isn't enable on the public role for some reason... 

If you run this  query

```
SELECT *
FROM `users-permissions_permission`
WHERE role = 2 and action = 'init';
```

You should get sth like

|type|controller|action|enable|policy|role|
|---|--|--|--|--|--|
|users-permissions|userspermissions|init|1|NULL|2|


Can you share your result ?

**Comment by arnoldgamboa** [comment]
So weird. I reinstalled everything, including the database, and it suddenly
worked. I don't know how to replicate it. I just hope it won't come back
again :D

-Arnold

**Comment by jsonpj3wt** [comment]
We are also seeing this in our production environment.  Works fine in dev even locally but once it is out on our servers, same problem.  We cannot just wipe the database easily since it is production.

@alexandrebodin We have three entries for what you asked for:
{
    "_id" : ObjectId("5db72274659c45c762f927e0"),
    "type" : "users-permissions",
    "controller" : "userspermissions",
    "action" : "init",
    "enabled" : true,
    "policy" : "",
    "createdAt" : ISODate("2019-10-28T17:16:37.144Z"),
    "updatedAt" : ISODate("2019-10-28T17:16:38.485Z"),
    "__v" : 0,
    "role" : ObjectId("5d9bbded40bc86614d8ec017")
},
{
    "_id" : ObjectId("5db72275659c45c762f92929"),
    "type" : "users-permissions",
    "controller" : "userspermissions",
    "action" : "init",
    "enabled" : true,
    "policy" : "",
    "createdAt" : ISODate("2019-10-28T17:16:37.156Z"),
    "updatedAt" : ISODate("2019-10-28T17:16:38.486Z"),
    "__v" : 0,
    "role" : ObjectId("5d9bc52bbb285a6176539a15")
},
{
    "_id" : ObjectId("5db72274659c45c762f92697"),
    "type" : "users-permissions",
    "controller" : "userspermissions",
    "action" : "init",
    "enabled" : true,
    "policy" : "",
    "createdAt" : ISODate("2019-10-28T17:16:37.131Z"),
    "updatedAt" : ISODate("2019-10-28T17:16:38.487Z"),
    "__v" : 0,
    "role" : ObjectId("5d9bbded40bc86614d8ec018")
}

**Comment by derrickmehaffy** [comment]
@jsonpj3wt include your error also because I think your code was different believe it was a 500 code not a 403

**Comment by jsonpj3wt** [comment]
ah ok:

We modified it to do some cleanup and do an npm run build to make sure everything is correct.  Now we are getting an error running admin <api-path>/users-permissions/init - response: 500.  Literally tried everything and it works locally just fine.  Only difference I can see is it is running in production.

Also, this works fine in another database instance and also works fine running the container locally as well as running strapi locally.  Super strange that once in AWS/ECS, this happens.

There are no logs that describe the issue either.  Attempted to call the users_permissions/init endpoint 50+ times to make sure I didn't miss the log error, but nothing but 500 from the call.

**Comment by derrickmehaffy** [comment]
@arnoldgamboa can you confirm you are also using AWS either as a host or for their managed database?

**Comment by EdenLiang** [comment]
If you are using MySQL and you are the first time login to Admin, you will call "user-permissions/init", but that permission's role is 1, which is "Authenticated". at that time, you are not login yet
So you need to change it to 2, which is "public". 
Change from
| Type | controller | action | enabled | policy | role |
|:--:|:--:|:--:|:--:|:--:|:--:|
| users-permissions | userspermissions | init | 1 |  | 1 |
To
| Type | controller | action | enabled | policy | role |
|:--:|:--:|:--:|:--:|:--:|:--:|
| users-permissions | userspermissions | init | 1 |  | 2 |

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/admin-panel-401-error-on-custom-permissions-with-httponly-cookie/1067/1
