### ISSUE TITLE
Compile error when i use local dependency 

### ISSUE THREAD

**Issue by jmeviler** [strapi/strapi#4374]
**Describe the bug**
 Compile error when i use local dependency with `strapi-plugin-content-manager` 

**Steps to reproduce the behavior**
1. Install local dependency  `npm install ~/xxxxx/strapi/packages/strapi-plugin-content-manager`
2. Install all dependencies `npm install `
3. Startup `npm run develop`

**Expected behavior**
Strapi should startup.

**Screenshots**
![image](https://user-images.githubusercontent.com/8113957/67651150-b5a00400-f97a-11e9-828b-c45dbb48cdee.png)

**Code snippets**
```
 "dependencies": {
    "knex": "^0.16.5",
    "lodash": "^4.17.5",
    "mysql": "^2.17.1",
    "pg": "^7.10.0",
    "sqlite3": "^4.0.6",
    "strapi": "3.0.0-beta.17.4",
    "strapi-admin": "3.0.0-beta.17.4",
    "strapi-hook-bookshelf": "3.0.0-beta.17.4",
    "strapi-hook-knex": "3.0.0-beta.17.4",
    "strapi-hook-mongoose": "3.0.0-beta.17.4",
    "strapi-middleware-views": "3.0.0-beta.17.4",
    "strapi-plugin-content-manager": "file:../../packages/strapi-plugin-content-manager",
    "strapi-plugin-content-type-builder": "3.0.0-beta.17.4",
    "strapi-plugin-documentation": "3.0.0-beta.17.4",
    "strapi-plugin-email": "3.0.0-beta.17.4",
    "strapi-plugin-graphql": "3.0.0-beta.17.4",
    "strapi-plugin-upload": "3.0.0-beta.17.4",
    "strapi-plugin-users-permissions": "3.0.0-beta.17.4",
    "strapi-provider-email-mailgun": "3.0.0-beta.17.4",
    "strapi-provider-upload-aws-s3": "3.0.0-beta.17.4",
    "strapi-utils": "3.0.0-beta.17.4"
  },json
```
**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.4
- Database: 
- Operating system:  macOS Mojave 10.14.6

**Additional context**
- This issue exists in all versions. `(ps. 3.0.0-beta.14 ~ 3.0.0-beta.17.4)`

**Comment by derrickmehaffy** [comment]
What kind of modifications are you doing?

**Comment by derrickmehaffy** [comment]
Ah nevermind I see you are using the example. I wouldn't normally recommend this that is there mainly to serve as testing not really for user usage.

**Comment by jmeviler** [comment]
> What kind of modifications are you doing?

I want to add  cascade for content type.  So, I need to use local dependency, but compile error when startup...

**Comment by derrickmehaffy** [comment]
I would recommend you setup a normal project and throw a copy of the CTM plugin into something like `packages/` at the root of the project then hard link it in the package.json.

Working from inside the monorepo is not a very straight forward (or recommended) process.

**Comment by jmeviler** [comment]
> I would recommend you setup a normal project and throw a copy of the CTM plugin into something like `packages/` at the root of the project then hard link it in the package.json.
> 
> Working from inside the mono repo is not a very straight forward (or recommended) process.

Tkx @derrickmehaffy . 
I will try.  If have other errors, I will continue to comment...

**Comment by soupette** [comment]
@jmeviler if you want to use the `getstarted` app for development you don't need to modify the `package.json` however here's how to develop the administration panel;

```
cd strapi/examples/getstarted && yarn develop
cd strapi/packages/strapi-admin && yarn develop
```

Then, go to localhost:4000/admin.
