### ISSUE TITLE
Deleting file from 'Files Upload' breaks any other content that has reference as a 'Media' relation to that file

### ISSUE THREAD

**Issue by pouyamiralayi** [strapi/strapi#4384]
**Describe the bug**
Suppose that we have a content type "Post".
In "Post" we have an "Images" field with type "Media" that has "Allow multiple files" checked.
If any of the files added in "Media" for a Post are deleted in the "Files Upload" section under Plugins, then the Post will no longer be editable; for any further visits upon Post content type, the admin panel will ouput this error:
```
TypeError: Cannot read property 'split' of undefined

    in Es
    in td
    in As
    in withRouter(undefined)
    in tr
    in t
    in styled.tr
    in tbody
    in table
    in t
    in styled.table
    in Cs
    in Cs
    in withRouter(undefined)
    in div
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in styled.div
    in hi
    in ac
    in ac
    in k
    in t
    in t
    in Unknown
    in _g
    in k
    in mainComponent
    in t
    in div
    in ar
    in ar
    in t
    in t
    in div
    in div
    in div
    in t
    in k
    in withSaga(Connect(t))
    in withReducer(withSaga(Connect(t)))
    in t
    in ro
    in t
    in div
    in div
    in io
    in k
    in t
    in t
    in IntlProvider
    in t
    in k
    in t

```

**Steps to reproduce the behavior**
1. Create a content type "Post".
2. Add a field named "Images" of type "Media" and check "Allow multiple files"
3. Create a new "Post" and upload an image file to its "Images" field.
4. On the left side under Plugins click "Files Upload"
5. Delete the file that was uploaded in step 3 using the trash can icon.
6. Go back and edit the Post, see that instead of edit panel the above error will be shown.

**Expected behavior**

Deleting the file would not break any functionality and for content types that already hold a reference to that file, the reference get cleared as well.

**Screenshots:**

**Screenshot: 1**
![67575108-b0f40980-f748-11e9-92ff-4a31621533e8](https://user-images.githubusercontent.com/53266765/67724574-b2e1f500-f9f4-11e9-85f1-671578282b69.png)

**Screenshot: 2**
![67575664-e816ea80-f749-11e9-87a3-9ebcd97ba1ff](https://user-images.githubusercontent.com/53266765/67724770-5c28eb00-f9f5-11e9-8457-ee49eb1a6d28.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.11.1
- Strapi version: 16.8
- Database: postgres
- Operating system: windows 10 x64

**Additional context**
i tried to remove the file using destroy endpoint ``("upload/files/:id")`` and when i retrieved the content type, the field holding file references was an array with **one empty object** **(Screenshot: 2)** and i guess that's the problem. cheers!

**Comment by derrickmehaffy** [comment]
@soupette @virginieky

**Comment by Parka** [comment]
For a quick fix you can delete the relevant row in upload_file_morph.
Example for SQLite, with same content type name and field name as in the example:
`DELETE FROM upload_file_morph WHERE related_type="posts" AND field="images"`

**Comment by veitbjarsch** [comment]
This problem is a more general one. If you delete any image (either via the admin ui or by API command) that has a relation to an other entry this entry will be unavailable to access via graphql, because the relation in the upload_file_morph is still present. 

I could implement the workaround from @Parka into the upload service with knex, but I don't know if this is the right place/way to do this.

**Comment by pouyamiralayi** [comment]
@veitbjarsch i think the best place to implement this is inside the provider (local provider).

**Comment by veitbjarsch** [comment]
@pouyamiralayi no the local provider doesn't deal with the database. This will be handled inside strapi-plugin-upload. My current question ist, is there a smarter way to access and modify the upload_file_morph table instead of using knex. May strapi.query() can do the job but there is no documentation for connection tables.

**Comment by pouyamiralayi** [comment]
@veitbjarsch you are totally right, my mistake! about the query i guess this is it:
``strapi.query('file', 'upload').delete({id: file.id})``
cheers!

**Comment by iedmrc** [comment]
Mine either suffer with the same problem. I'm looking forward to it to be fixed.

**Comment by DaveYouey** [comment]
I don't have time at the moment to put a PR in, but a quick fix for anyone suffering with problems with this, update strapi-plugin-content-manager plugin - `/node_modules/strapi-plugin-content-manager/admin/src/components/MediaPreviewList/index.js` on line 39 from 
```
const fileType = includes(mime, 'image') ? 'image' : getFileType(name);
```
to 
```
let fileType = ''
if (name) {
    fileType = includes(mime, 'image') ? 'image' : getFileType(name);
}
```

Stops the offending code trying to reference an empty upload object to create text/css classes for the UI.
