### ISSUE TITLE
Issue with view file and copy link of uploaded file

### ISSUE THREAD

**Issue by badoet** [strapi/strapi#4386]
**Describe the bug**
Wrong url composition in view file and copy link of uploaded file

**Steps to reproduce the behavior**
1. Go to 'Files Upload'
2. Click on the record to copy the link
3. the recorded link will be https://https://<host>:<port> ...
problem here is there is extra https:// at the front and also the additional `:port` 

1. Go to 'Files Upload'
2. Click on the eye icon record to open the file in new tab
3. the new tab will be https//<host>:<port> ...
problem here is there is the missing `:` between `https` and `//` and also the additional `:port` 

**Expected behavior**
N/A

**Screenshots**
N/A

**Code snippets**
N/A

**System**
- Node.js version: 
- NPM version:
- Strapi version: 3.0.0-beta.17.4
- Database:
- Operating system:
- Environment: production

**Comment by derrickmehaffy** [comment]
@badoet what is the config of your proxy settings in `config/environments/*/server.js`

Here is the spot in the documentation that covers this: https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#server

And here is an example of a properly setup proxy setting:
```
{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": true,
    "host": "api.example.com",
    "port": 443,
    "ssl": true
  },
  "autoReload": {
    "enabled": true
  },
  "cron": {
    "enabled": true
  },
  "admin": {
    "autoOpen": false
  }
}
```

**Comment by badoet** [comment]
got it thank you
