### ISSUE TITLE
Can't aggregate count the User model

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4387]
**Describe the bug**

Can't aggregate count the User model

**Steps to reproduce the behavior**

1. Run this GraphQL query:

```
query GetUsers {
  usersConnection(limit: 2) {
    aggregate {
      count
    }
    values {
      username
    }
  }
}
```

2. See the error:
`"message": "The model user can't be found."`

**Expected behavior**

Return the count.

**System**
- Node.js version: `v10`
- NPM version: `v6`
- Strapi version: `v3.0.0-beta.17.4`
- Database: MongoDB
- Operating system: macOS

**Comment by abdonrd** [comment]
Thanks @lauriejim!

Mention that the same query works for me in other models.

**Comment by abdonrd** [comment]
I think I found the bug here:

https://github.com/strapi/strapi/blob/447594684d1ebcc283f19cc22f242e3684b2e583/packages/strapi-plugin-graphql/services/Aggregator.js#L361-L366

When the `modelName` is `user`, the query should be:

```javascript
strapi.query('user', 'users-permissions')
```

**Comment by navicstein** [comment]
This issue should still be opened, as am still seeing the issue currently

**Comment by alexandrebodin** [comment]
@navicstein  If you are still experiencing an issue similar to this one, please open a new issue with the exact queries and informations you have.
