### ISSUE TITLE
Permissions setup fail on MongoDB

### ISSUE THREAD

**Issue by savyir** [strapi/strapi#4402]
hi,
**summary**
I want to edit one of my content types, but I got "an error occurred"

1. Go to content type builder
2. Click on one of content types
3. Click on add another field, fill it, and then click on Save button on top
4. See error "an error occurred"

**Expected behavior**
I want to change my model and add a new field or update one of them.

**Screenshots**
![image](https://user-images.githubusercontent.com/24469125/67817708-b42e2300-fac3-11e9-8756-a69ad6b9c55c.png)

**System**
- Node.js version:  12
- NPM version: 6 (latest yarn)
- Strapi version: 3.0.beta17.4
- Database: sqlite
- Operating system: Centos 7

**Comment by savyir** [comment]
it works when I login with ip and port !

![image](https://user-images.githubusercontent.com/24469125/67826885-51e51a80-fae3-11e9-9726-ec5a89fd62db.png)

but with reverse proxy dosen't work

**Comment by savyir** [comment]
No, I just installed it with "yarn create strapi-app my-project --quickstart" directly last night.
I think it is latest version

**Comment by lauriejim** [comment]
Okay we fixed this issue for Bookshelf (SQL databases) but the issue still exists on Mongo.

The issue is: when strapi create the application, on the first start, we create the `jwt.json` file and when you update/create a new file, it triggers a server restart.
But the permissions database setup is not finished. So some permissions are missing (in your case permission to update a content type)

I suggest you remove your `users-permissions_permission` collection and restart your application.

Let me know if it's work.

**Comment by savyir** [comment]
where is the "users-permissions_permission" collection? 
I just see a folder called "users-permissions" in the extensions folder. 

I guess there is something with request handling. 
content-type update works when I login with ip:1337
I can give you ssh access if it helps.

**Comment by derrickmehaffy** [comment]
@savyir he means in the database.

**Comment by savyir** [comment]
I installed Strapi with --quick-start flag, so I don't know how to access the DB
should I reinstall it?

**Comment by derrickmehaffy** [comment]
you can use any SQL client like DBeaver/HeidiSQL to open up the SQLite DB file

**Comment by savyir** [comment]
Thank you. I didn't know that.


@derrickmehaffy I tried what you said, but didn't work. 
I installed Strapi with MySql,
created a new content-type and saved it,
when I go to update I got the same error.

I deleted the "users-permissions_permission" table from MySql DB and restarted Strapi (yarn && yarn build && yarn develop) , but the error still exists.

**Comment by lauriejim** [comment]
Can you try with another OS?
Your issue is really weird.
If you are signed in as an admin you have access to all API routes. So impossible to have a 403 error.

**Comment by derrickmehaffy** [comment]
Make sure you don't have the mod header chrome extension installed

**Comment by savyir** [comment]
@lauriejim @derrickmehaffy 
 in chrome , firefox , desktop and phone , it doesn't work.
I'm using admin panel with proxy in address and works well.
