### ISSUE TITLE
Is the "you should not be able to reach the administration panel" after setup warning still valid?

### ISSUE THREAD

**Issue by mhelmetag** [strapi/strapi#4403]
**Describe the topic**
In https://github.com/mhelmetag/strapi/blob/master/CONTRIBUTING.md, there's a section where it says "If you've followed the recommended setup, you should not be able to reach the administration panel at http://localhost:1337/admin." The thing is... I can view the admin page from that URL (after creating a root user) and `yarn develop` says I can too (from the screenshot below).

**Your suggestions for this topic**
Can we remove this from the contributing docs now? I believe it's no longer valid.

I can make a PR for that once I get the go ahead.

**Screenshots**
<img width="871" alt="Screen Shot 2019-10-30 at 12 12 26 AM" src="https://user-images.githubusercontent.com/8609429/67836505-05311d80-faaa-11e9-8658-65836d94617f.png">

**Code snippets**
N/A

**Additional context**
N/A

**Comment by derrickmehaffy** [comment]
@lauriejim @Aurelsicoko this is what I brought up the other day the contrib docs need some updates. The process outlined in them doesn't work most of the time.

**Comment by mhelmetag** [comment]
FWIW, the contrib doc did work for me other than that. I just found that little detail confusing (but to be fair... a lot changes in a year when that was added).

Only other thing I've noticed is that `yarn develop` runs in the dev environment and `getstarted` is missing a `database.json` for that env. Not sure if that's intended or not.
