### ISSUE TITLE
Content-Manager relation dropdown weird behavior

### ISSUE THREAD

**Issue by TheRealBarenziah** [strapi/strapi#4407]
**Describe the bug**
Relational dropdowns behavior were fine in alpha, but since beta they're pretty annoying to work with. This issue is about the annoyance because I couldn't reproduce my original issue (where I strictly couldn't get more than 21 elements in my dropdown).

**Steps to reproduce the behavior**
1. Get [this repo](https://github.com/TheRealBarenziah/strapi-reproduce-issue) (credentials are in readme)
2. There are 26 mommies (for each letter of alphabet) and a baby (which has only one mommy).
3. Before clicking on the 'babies' tab, open your browser developer tools, Network tab. Clear it.
4. Now edit the baby: we want to link it to its mom (which is 'z'). You can see the HTTP request made by the dropdown when you clicked the baby entry: `http://localhost:1337/content-manager/explorer/mommy?_limit=20&_start=0&source=content-manager`
5. Click the 'mommy' dropdown and scroll down to see it effectively fetched the 20 first mommies. As you get to the end of the dropdown, you can see the log of a new request: `http://localhost:1337/content-manager/explorer/mommy?_limit=20&_start=1&source=content-manager`
6. You still can't attribute the baby it's mom 'z', you only see moms up to 'u'
7. To find the mom 'z' you have to repeat the process of hitting the end of dropdown several times (scroll up, scroll down, scroll up, scroll down...): see how the `_start` param is incremented by 1 each time you hit the end of dropdown

**Expected behavior**
I expected a smooth experience like in alpha where the `_start` parameter were incremented by 20 each time we hit the bottom of the dropdown. My teammate work with those dropdowns a lot so he instantly noticed the change.

**Code snippets**
My workaround atm is to change [this line](https://github.com/strapi/strapi/blob/473d7002085eb987578ccb2b495e9c24093242c8/packages/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js#L118) (`./node_modules/strapi-plugin-content-manager/admin/src/components/SelectWrapper/index.js` L118 )
This const:
```
  const onMenuScrollToBottom = () => {
    setState(prevState => ({ ...prevState, _start: prevState._start + 1 }));
    ref.current();
  };
```
becomes: 
```
  const onMenuScrollToBottom = () => {
    setState(prevState => ({ ...prevState, _start: prevState._start + 20 }));
    ref.current();
  };
```
Did a `yarn build` after that, and now things are better (fetching entries 20 by 20)

**System**
- Node.js version: 12.10.0
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.17.4
- Database: SQLite (same behavior with mySQL, and I assume, with all DBs)
- Operating system: Linux Mint 19.2 Tina / Amazon RedHat

**Additional context**
I can live with this issue by doing my workaround and rebuilding the app. In case anybody else is annoyed by this, the fix should do it. Basically this function is called on the event of hitting the end of dropdown. I don't like the new way of handling this (for my baby & mom example, the dropdown have to go make several requests before you're able to find 'z', and each more mommy would add another request). It's not a critical problem (the fix is easy and works well enough for me) but it deserved to be documented imo.

**Comment by derrickmehaffy** [comment]
@TheRealBarenziah can you submit a PR? Also you may want to check this code in the develop branch and make sure it hasn't been tweaked. beta.18 will have quite a few changes so it's possible this has already been addressed (haven't looked myself)

**Comment by TheRealBarenziah** [comment]
I can look into beta.18 and/or submit a PR this Friday; letting it open in the meantime. Insight from the author of this component would be welcome

**Comment by TheRealBarenziah** [comment]
Little update;
I haven't done a PR yet because I don't find my workaround satisfying enough. I mean, it makes it possible to live with the bug instead of really fixing it.

The problem seems common for most browsers (I've also tested Opera, Chromium, Firefox, Safari & Brave).

The thing is, `onMenuScrollToBottom` should trigger when you're already to the bottom & scroll down, and it doesn't. But I suspect it should, because I saw it working at least once. My goal is to also restore this behavior (so the experience is smooth, instead of having to scroll-up scroll-down every 20 entries)

I have leads in [this library issues](https://github.com/JedWatson/react-select/issues/3232), but I'll need to dig a bit further.

**Comment by lauriejim** [comment]
@soupette will be the best person to help you!

**Comment by soupette** [comment]
@TheRealBarenziah I have read the issue and it since the best way at the moment would be to remplace the components...
Do you feel like taking care of it?

**Comment by TheRealBarenziah** [comment]
Are we talking about the whole SelectWrapper component?

I can look into it, but can't guarantee to succeed quick as I have a pretty busy month. On top of that I'm pretty junior so I assume it will take me a fair amount of time.

Afaik `react-select` is pretty mainstream as a library (used by 54k repos) so I still have some hope of fixing it w/o having to rewrite the whole thing.

If you still think the best way is to rewrite it, please give me some infos on how you envision the new one (can also be done on Strapi Slack if you prefer)

**Comment by elektracodes** [comment]
Same issue here. I have Talks and Speakers and the dropdown no longer work.  I have to write the DB queries myself. Any idea how to fix this?
I cannot do the same hack @TheRealBarenziah did, since .cache folder is build each time on deploy

**Comment by Alykod** [comment]
I tried to tackle the problem, and this is what I came up with. 

` const onMenuScrollToBottom = () => {
    setState(prevState => ({ ...prevState, _start: prevState._start + 1, _limit: prevState._limit + options.length}));
  };
`

since the data returns in increments of 20 or less, this would expand the limit up to 20, every time you reach the end of the menu.


![weirdloader](https://user-images.githubusercontent.com/29825345/72798770-bfe83c00-3c11-11ea-9181-082450409110.gif)

**Comment by soupette** [comment]
I am closing this issue as it fixed with the `beta.19` release. Feel free to reopen an issue if you think the bug was not fixed correctly.
