### ISSUE TITLE
Allow Repeatable field feature for all field types to store array of multiple values

### ISSUE THREAD

**Issue by MurzNN** [strapi/strapi#4413]
- [x] I have created my request on the Product Board, but it disappear after sending and I can't link to it here.

- [x] I have looked at all the other requests on the Product Board before I submitted this issue, and there are no issues exactly about this simple feature.

At now, `Repeatable field` option have only `Group` and `Media` field types, why it available only for two field types?

Is it hard to extend it and allow repeatable feature for other field types (string, number, boolean, etc)? 

Will be very useful to store array of values for single field directly in field data, without using relations or groups!

**Comment by lauriejim** [comment]
Hello! If you sent this feature request on the product board, it's enough.
I don't think we need it also open in GitHub.
Thank you for this insight @MurzNN

**Comment by derrickmehaffy** [comment]
Yup if it was submitted via product board then @Aurelsicoko will see it
