### ISSUE TITLE
mongoose plugin not working after upgrading to beta.17.4

### ISSUE THREAD

**Issue by qivhou** [strapi/strapi#4415]
**Describe the bug**
before update, I have a development set up in beta.14. In my dev, I had a mpath plugin for mongoose as following. (/config/functions/mongoose.js), I can use the functions by mPath, for example `getAllChildren()`, it attaches on mongoose document.

code as following,
```javascript
    return strapi
      .query('Org')
      .findOne(params)
      .then((doc) => {
        return doc.getAllChildren();
      });
```

config as below
```javascript
'use strict';

const mPath = require('mongoose-mpath');

module.exports = (mongoose) => {
  mongoose.plugin(mPath);
};

```

But now, I got error as following 
```
error TypeError: doc.getImmediateChildren is not a function
```

seems it's related with [updates](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.15-to-beta.16.html#custom-controllers-and-services) `If you are using core services, you previously needed to call result.toJSON() or result.toObject() to get a plain javascript object. This is not the case anymore, you will now receive a simple object directly.` 

NOT SURE HOW to do with it to make the plugin work again?

**System**
- Node.js version: 10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.4
- Database: mongoDB 3.2.8
- Operating system: MacOS 10.14.5

**Comment by derrickmehaffy** [comment]
@qivhou please follow the bug report template, also please include the required information to the **system** block I just edited onto your post

**Comment by alexandrebodin** [comment]
Hi @qivhou,

Using the strapi.query util won’t work in your case. To run full mongoose queries you can access your model through strapi.models.org and run any mongoose query.

Hope this helps you :)

**Comment by qivhou** [comment]
@derrickmehaffy report set up.
@alexandrebodin it worked before. you mean it's not working on new version ?

**Comment by derrickmehaffy** [comment]
There was lots of changes to the hooks @qivhou

**Comment by alexandrebodin** [comment]
@qivhou as you pointed out in your description, the data returned by the queries are now plain js objects an not mongoose or bookshelf documents.

**Comment by alexandrebodin** [comment]
I'm going to close this issue as we just changed the way to do that but it is still doable. 

Let us now if you need help.

**Comment by qivhou** [comment]
@alexandrebodin could you give some ideas on it ？ demo or some codes？thank you very much！

**Comment by qivhou** [comment]
saw the [models document](https://strapi.io/documentation/3.0.0-beta.x/global-strapi/api-reference.html#strapi-models) mentioned @alexandrebodin , will have a try ! Thank you guys for your amazing work!
