### ISSUE TITLE
Path when using a custom upload service is always temp-folder

### ISSUE THREAD

**Issue by kolomu** [strapi/strapi#4416]
**Describe the bug**
When using a custom upload service (with @koa/multer) the upload path is always my temp folder.

I created a repository showcasing my issue here: https://github.com/kolomu/custom-editor-strapi
The following files are important: 
sample2.html (The upload html file)
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <form action="http://localhost:1337/customupload" method="POST" enctype="multipart/form-data">
        <input type="file" name="upload" />
        <button type="submit">send</button>
    </form>
</body>

</html>
```

api/custom
-   services/MyUpload.js
```javascript
var multer = require('@koa/multer');
const path = require('path');

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        console.log('in dest');
        cb(null, path.resolve(__dirname, './public'));
    },
    filename: function (req, file, cb) {
        console.log('in filename');
        let fileName = file.originalname.toLowerCase();
        let fileExtension;

        if (fileName.endsWith('.jpg')) {
            fileExtension = '.jpg';
        } else if (fileName('.png')) {
            fileExtension = '.png'
        }
        cb(null, file.fieldname + '-' + Date.now() + fileExtension)
    }
});

const upload = multer({ storage: storage });

module.exports = {
    imgUpload: (ctx) => {
        console.log('in imgUpload!');
        console.log('ctx');
        console.log(ctx)
        upload.single('upload')(ctx, () => {
            console.log('ctx.request.files', ctx.request.files);
            console.log('ctx.files', ctx.files);
            ctx.body = 'done';
        });
    }
};
```
-  controllers/Custom.js
```javascript
'use strict';
module.exports = {
  handleUpload: async ctx => {
    strapi.services.myupload.imgUpload(ctx); 
    ctx.send('Hello World!' + JSON.stringify(ctx));
  },
};
```
-  config/routes.json
```json
{
    "routes": [
      {
        "method": "POST",
        "path": "/customupload",
        "handler": "Custom.handleUpload",
        "config": {
          "policies": []
        }
      }
    ]
  }
```

 

**Steps to reproduce the behavior**
1. Start the server with port 1337
2. Upload a file in sample2.html
3. See in node log that the path is temp and not dest

**Expected behavior**
Use the expected path and also execute the multer functions.

**Screenshots**
![Wrong Path](https://i.imgur.com/ObhK2HX.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.9
- Strapi version: 3.0.0-beta.17.4
- Database: quickstart (SQLLite)
- Operating system: Windows 10

**Additional context**
First I thought that multer and koa was the issue but I created a new repository with the same structure (except async koajs) and there it worked without issues. You can find the repository here:

https://github.com/kolomu/koajs-example-server-multer

**Comment by lauriejim** [comment]
Hello @kolomu !
This issue is not related to Strapi itself.
Can you please open this issue as a question on StackOverflow.
And add the tag `strapi`.
Thank you ;)

PS: To access to the data vs file in your request,
check the default controller logic for the `create` function.
https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#core-controllers

**Comment by lauriejim** [comment]
Hello @kolomu !
This issue is not related to Strapi itself.
Can you please open this issue as a question on StackOverflow.
And add the tag `strapi`.
Thank you ;)

PS: To access to the data vs file in your request,
check the default controller logic for the `create` function.
https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#core-controllers
