### ISSUE TITLE
API register user mail validation

### ISSUE THREAD

**Issue by Mateuszry** [strapi/strapi#4419]
**Describe the bug**
Strapi allows to register user with invalid email. Behavior depends on `email confirmation` config:
- **Case 1:** When `email confirmation` is disabled Strapi creates user with invalid email and `auth/local/register` returns `200`. 
- **Case 2:** When `email confirmation` is enabled user with an invalid email is saved to the database, but the error occurs when trying to send a confirmation email(Nodemailer in my case) and `auth/local/register` returns `400` with body:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": {
    "code": "EENVELOPE",
    "command": "API"
  }
}
``` 

**Steps to reproduce the behavior**
- **Case 1:**:
1. Send request to `auth/local/register` with example payload:
```
{
  "username": "exampleUserName",
  "email": "invalidUserEmail",
  "password": "examplePassword"
}
```
2. Respnse code `200` and invalid email in response `"email": "invalidUserEmail"`

- **Case 2:**:
1. Enable `email confirmation` in `Roles & Permissions` -> `Advenced Settings`
2. Send request to `auth/local/register` with example payload:
```
{
  "username": "exampleUserName",
  "email": "invalidUserEmail",
  "password": "examplePassword"
}
```
3. Respnse code `400` with body:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": {
    "code": "EENVELOPE",
    "command": "API"
  }
}
```

**Expected behavior**
There should be bad request response with error when email given during user registration not match regex(`emailRegExp`) defined in `strapi-plugin-users-permissions/controllers/Auth.js`

**Code snippets**
For example it could be handle in `else` clausal in `strapi-plugin-users-permissions/controllers/Auth.js`:
```
if (isEmail) {
    params.email = params.email.toLowerCase();
} else {
    return ctx.badRequest(
        null,
        formatError({
            id: 'Auth.form.error.email.invalid',
            message: 'Email invalid.',
        })
    );
}
```

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.4
- Database: postgres:12
- Operating system: Ubuntu Linux with dockerized Strapi

**Comment by derrickmehaffy** [comment]
This will likely come with the validation layer, right now there is almost nothing that has any validation on it.

This was brought up with other things like default values, enum values, min and max settings, ect.

**Comment by derrickmehaffy** [comment]
https://portal.productboard.com/strapi/1-public-roadmap/c/14-validations

**Comment by Mateuszry** [comment]
> This will likely come with the validation layer, right now there is almost nothing that has any validation on it.
> 
> This was brought up with other things like default values, enum values, min and max settings, ect.

In my opinion it is not validation feature. It is just a bug which misleads users, because they receive response 400 with strange message. Account is created in Strapi database, so they cannot confirm their account nor use the same username again.

**Comment by lauriejim** [comment]
Hello @Mateuszry !
Thank you for reporting this issue. Feel free to submit a PR to fix that.
Will really appreciate your contribution.
