### ISSUE TITLE
Chrome lose session on a new tab on same admin url

### ISSUE THREAD

**Issue by huesoamz** [strapi/strapi#4426]
**Describe the bug**
After you login on Admin UI, if you wanna open in a new tab (in Chrome) with the same url of a content-type or any url of the admin you get redirect to the login.

The problem its that chrome dont store the session between tabs, but I dont know why dont store all in local storage like Firefox did.

**Steps to reproduce the behavior**
1. Go to Admin section
2. Click on any link and open it in a new tab
3. Automatically you redirect to login

**Expected behavior**
Maintain the session on the same browser in all tabs

**Screenshots**
1) Local Storage:

![image](https://user-images.githubusercontent.com/3308717/68034332-3d01b600-fca0-11e9-8386-c66fff2e2edb.png)
2) Session Storage:

![image](https://user-images.githubusercontent.com/3308717/68034406-5c004800-fca0-11e9-8588-a327a972ca98.png)

**System**
- Node.js version: 10.17.0
- NPM version: 6.11.3
- Strapi version: Strapi v3.0.0-beta.17.2
- Database: MongoDB
- Operating system: Debian

**Additional context**
In firefox this works because all data is store on local storage instead of spliting the data in local storage/session storage like "chrome do"

![image](https://user-images.githubusercontent.com/3308717/68034139-eb592b80-fc9f-11e9-83cb-25cb26e185e2.png)

**Comment by derrickmehaffy** [comment]
Can confirm this, tad annoying when I want to open something in another tab

**Comment by huesoamz** [comment]
After to many test, I saw that the behaviour its related to the "remember me" function on the login, if you click remember me the APP store the jwt/userInfo on localstorage and this persist on tabs...but if  you dont the session is created only for current tab.

I closed the issue, because maybe its the correct behaviour of the remember me.

**Comment by Tdnshah** [comment]
@huesoamz I would like to know if this is the expected behaviour as remember login should actually work like if on the same machine if we then it should remember the login credentials, but if once logged even with marking remember me it should not forget the active session right?
