### ISSUE TITLE
couchbase db support

### ISSUE THREAD

**Issue by joshvoll** [strapi/strapi#4427]
just a question if there is a plan to add support to couchbase db ;)

**Comment by derrickmehaffy** [comment]
@joshvoll there is no current plans right now that I am aware of

> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by medabdev** [comment]
Any updates about the couchbase support?
I don't know about other people, but for me, it's because it's built on top of v8, the same as nodejs runtime engine.
I'm not very sure if there are any performance or productivity benefits to it, but having the same base components just feels more organized

**Comment by derrickmehaffy** [comment]
> Any updates about the couchbase support?
> I don't know about other people, but for me, it's because it's built on top of v8, the same as nodejs runtime engine.
> I'm not very sure if there are any performance or productivity benefits to it, but having the same base components just feels more organized

We have no plans to implement couchbase support in the short or long term future.
