### ISSUE TITLE
Dates in list view are shown without time

### ISSUE THREAD

**Issue by fl034** [strapi/strapi#4428]
**Describe the bug**
Dates in list view are shown without time. In my use case I have a content-type that has many entries that differ only in time.
I guess adding the time wouldn't hurt anybody. But making it adjustable would be the nicer way, of course.

I'm creating this as a bug report since I think it just was forgotten. E.g. in relational field selection you can see the whole date time.

**Screenshots**
<img width="642" alt="Bildschirmfoto 2019-11-02 um 00 13 01" src="https://user-images.githubusercontent.com/11268968/68061519-98b25a80-fd05-11e9-98c0-1ffe91162045.png">

**System**
- NPM version: node v12.13.0
- Strapi version: v3.0.0-beta.17.4
- Database: mongo
- Operating system: ubuntu / docker

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this.
I ping @Aurelsicoko and @soupette to give you the best advice on this topic.
Then I think you will be able to open a PR to fix it by following their instructions.

**Comment by fl034** [comment]
@soupette thanks for pointing me in the right direction, it worked great :-).

For a quick workaround I'd suggest this. Later we could inject the user's locale globally so the date will be displayed nicely.
Making it adjustable per field would also be great of course :), like you mentioned.

```js
moment().format('lll');  // Nov 8, 2019 10:22 AM
```

Should I make a PR with this small edit?

**Comment by Aurelsicoko** [comment]
@soupette I think by default we should display the time. However, it might be interesting to have a setting for that, but it will take too much time to implement. I would like to handle it while we will be developing the component to define the format of a relationship in the list view. It will certainly work in the same way.

**Comment by soupette** [comment]
@Aurelsicoko already done that check out #4830 I have added a dedicated config file so users can easily modify this setting until it is set in the `core_store`

**Comment by soupette** [comment]
I am closing this issue as now `datetime` and `timestamps` are shown with the time
<img width="397" alt="Screenshot 2020-02-27 at 12 17 38" src="https://user-images.githubusercontent.com/13311463/75440048-44d61c00-595b-11ea-8e37-5760d16f3406.png">
