### ISSUE TITLE
How to create a model or API with defining fields, validations and relationingship etc. via CLI 

### ISSUE THREAD

**Issue by maliksajid** [strapi/strapi#4430]
Hello, I'm a fan of CLI and being a developer prefer CLI instead of GUI. I want a single command of Strapi CLI through which I can generate API or Model. But in the same command, I also wanna mention the name of the fields of the table, validation rules for these fields and relationship with other tables if any.

Thank You

**Comment by pouyamiralayi** [comment]
> generate API
[generate api](https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-generate-api)
> name of the fields of the table
[generate model](https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-generate-model)
>  I want a single command

it is easy to combine the above commands into one. use ``&&`` in between.
for the validation i am not sure of a way also there is commands for defining [policies](https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-generate-policy)
cheers!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```
