### ISSUE TITLE
Content Type with field name 'length' not working properly in Many-to-Many relations

### ISSUE THREAD

**Issue by Kriskator** [strapi/strapi#4431]
**Describe the bug**
This took me a while to find out:
Querying for data in a many-to-many relation returns no data if related model includes a column named 'length' **and** contains data (not null).

**Steps to reproduce the behavior**
1. Go to admin area to menu 'Content Type Builder' and add a random Content Type with a Number field named 'length'. E.g. Movie with String field 'name' and Number field 'length. Also add a relation field with a random other Content Type, e.g. User. Make sure you pick a 'has and belongs to many' relation.
2. Go to Content Type 'Movies' and add data entries, make sure that length field contains data.
3. Go to Content Type 'Users' and add or edit an entry and add some Movie items from Movies dropdown on the right side and save.
4. Reopen currenty added/edited entry. No relations with Movies are shown. Try to query the relation data through REST or GraphQL, also no results, even though Database contains data correctly.

**Expected behavior**
Relation Data should be queried/shown correctly in the described scenario. 

**System**
- Node.js version: 10.16.3
- Yarn version: 1.19.0
- Strapi version: beta17.4
- Database: mysql (MariaDB)
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
More than likely this would be a javascript reserved word. @alexandrebodin @soupette add it to the list?

@Kriskator I'd suggest you use a different name.

**Comment by lauriejim** [comment]
This issue has been fixed in the stable version of Strapi.
