### ISSUE TITLE
fails to start when using database uri on production

### ISSUE THREAD

**Issue by deebov** [strapi/strapi#4435]
**Describe the topic**

My app is deployed on Heroku. I use Postgres as a default database. The problem is that Heroku updates the database credentials once in a while. So, it was not the best idea to use database credentials separately. I tried using the database uri as here:
![image](https://user-images.githubusercontent.com/28673719/68084627-feaff680-fe59-11e9-949e-c7c3b9521304.png)

It worked when I tested it locally. ( ran `yarn build && yarn start` )

But it fails to `npm start` when I push it to Heroku. However, the build process was successful.

Here's the logs from heroku:
![image](https://user-images.githubusercontent.com/28673719/68084655-6108f700-fe5a-11e9-99c7-174bd7575c36.png)

P.s. Yes, I have set `DATABASE_URI` environment variable on Heroku and it works when I use db credentials separately

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
