### ISSUE TITLE
File upload doesn't remove old relations

### ISSUE THREAD

**Issue by sefasaid** [strapi/strapi#4437]
**Describe the bug**
I have a user model like this

```json
"profile_img": {
  "model": "file",
  "via": "related",
  "plugin": "upload"
},
```

it works on admin panel but when i upload from mobile device or post data from postman it doesn't remove old relations so when i remove profile image, old profile image comes. how can i resolve

**Steps to reproduce the behavior**
1. upload image from mobile device or postman
2. go on user detail in admin panel
3. remove profile just uploaded
4. reload page
5. see old profile image is there

**Expected behavior**
when i upload an image it must remove all old relations from file upload

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.16.3
- NPM version:6.9.0
- Strapi version: 3.0.0-beta.16.4
- Database:mongodb
- Operating system:macos

**Additional context**
I'm using s3 file upload plugin

**Comment by lauriejim** [comment]
Hello! All works fine on my side (beta.17.5).
Before reloading, did you save your entry updates?

**Comment by yaoyonstudio** [comment]
got the same issue

**Comment by sefasaid** [comment]
> my side (beta.17.5).

yes i did save. But issue is still there.

**Comment by lauriejim** [comment]
Can you share a screen record please.
