### ISSUE TITLE
Uploaded media does not follow on Content Type name update on MongoDB

### ISSUE THREAD

**Issue by kiwimonk** [strapi/strapi#4439]
**Describe the bug**
Renaming a Content Type that has media uploads loses the media associated with it

**Steps to reproduce the behavior**
1. Go to 'Content Type Builder'
2. Rename a Content Type with Media
3. View the Content entries

**Expected behavior**
The upload_file.related.kind in the database should be updated when a content type is renamed.
If I change it manually in the database everything works again.

**System**
- Node.js version: v12.13.0
- Strapi version: v3.0.0-beta.17.4
- Database: Mongodb 4.2.1
--

- Operating system:
Linux Docker Host

**Comment by lauriejim** [comment]
Hello @kiwimonk !
Thank you for reporting this issue.

**Note:** This will only happen with MongoDB. It will work fine with an SQL database.
Due to relations are managed with specific tables in SQL.

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
