### ISSUE TITLE
Sort by date and not set default to current datetime in admin 

### ISSUE THREAD

**Issue by gvramesh2003** [strapi/strapi#4450]
Sort record by date field in API response. Default date is not set in admin panel

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

And please check existing issues before posting a new one - there is already one for each of your topics.
