### ISSUE TITLE
Endpoint http://localhost:1337/admin not working

### ISSUE THREAD

**Issue by davidemorra** [strapi/strapi#4453]
hi, I have this issue but nothing is changed (or well.. yesterday I updated my Mas).

The error that I see is this:

`main.39e5d438.chunk.js:formatted:110926 Uncaught TypeError: Cannot read property 'email' of undefined
    at Module.<anonymous> (main.39e5d438.chunk.js:formatted:110926)
    at a (runtime~main.0418a51d.js:formatted:38)
    at t (runtime~main.0418a51d.js:formatted:21)
    at Array.r [as push] (runtime~main.0418a51d.js:formatted:12)
    at main.39e5d438.chunk.js:formatted:1`

and if I open inspect I see this part of code:

`var Lr = Object(a.memo)(Fr)
      , jr = n(33)
      , Rr = {
        "forgot-password": {
            endPoint: "forgot-password",
            inputs: [[{
                label: {
                    id: "Auth.form.forgot-password.email.label"
                },
                name: "email",
                type: "email",
                placeholder: "Auth.form.forgot-password.email.placeholder"
            }]],
            schema: jr.object({
                email: jr.string().email(D.translatedErrors.email).required(D.translatedErrors.required)
            })
        },` 

Can you help me? The version is v3.0.0-beta.17.5

**Comment by gianfigueroa** [comment]
If the page redirect again to index, it is posible missed try strapi build

**Comment by lauriejim** [comment]
Can you run `yarn build` or `npm run build` in your project.

And can you please follow the issue template and also well format your error messages.

**Comment by davidemorra** [comment]
I found the mistake (mine) in the packages.json the dep strapi-admin was a different version. Thanks and sorry for this!
