### ISSUE TITLE
Remove dependency to open-browser-webpack-plugin and deprecated "open" version

### ISSUE THREAD

**Issue by viheikki** [strapi/strapi#4456]
**Describe the bug**
Strapi admin depends on a 3 year old open-browser-webpack-plugin package that is dependent on open@0.0.5 that has a critical security issue.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ open                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >0.0.5                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ strapi-admin                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ strapi-admin > open-browser-webpack-plugin > open            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/663                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```
**Steps to reproduce the behavior**
1. Install Strapi with `npx create-strapi-app my-project --quickstart`
2. Run `npm install && npm audit` in the my-project folder

**Expected behavior**
Strapi dependencies should not have any high priority vulnerabilities.
The functionality to open browser automatically after build is completed not necessary and open-browser-webpack-plugin and open should be removed from the project.

**System**
```
my-project@0.1.0 /Users/test/my-project
└─┬ strapi-admin@3.0.0-beta.17.5
  └─┬ open-browser-webpack-plugin@0.0.5
    └── open@0.0.5 
```

**Comment by soupette** [comment]
@viheikki I agree this plugin should be removed as it is not maintained anymore, however command injections we could simply remove the plugin and the update the  webpack `devServer` configuration by enabling it ([see the doc](https://webpack.js.org/configuration/dev-server/#devserveropen)).

**cc/** @alexandrebodin

**Comment by alexandrebodin** [comment]
Yep you can remove it :)
