### ISSUE TITLE
Photos that erase themselves

### ISSUE THREAD

**Issue by snakom23** [strapi/strapi#4457]
Uploading problem in the photos, the images are saved but after a while they are eliminated from the server remaining only as an entry in the DB.

Strapi last version and mongoDB. Strapi is hosted on heroku

**Comment by websocket98765** [comment]
Your node may be using ephemeral storage and losing static files after any redeploys. Your best bet is to use a persistent block storage like Amazon S3. 

See "Install the Strapi Provider Upload AWS S3 Plugin" at https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
