### ISSUE TITLE
REST not producing the expected Output JSON for Group inside Content Type

### ISSUE THREAD

**Issue by jedinrk** [strapi/strapi#4459]
I have created two content types, Journey and Pages. Journey has relation with many Pages.
Pages has a Group field Variables which is repeatable. 

On call of Journey REST API, the Group field under Pages are not getting listed or shown on the JSON

**Steps to reproduce the behaviour**
1. Create two content types. A & B, make B a relational field to A (one to many)
2. Create a group G and make it repeatable, 
3. Add G as a field for B.
4. Create an Entry for B and A respectively.
5. Call REST API for listing A.

**Expected behaviour**
Expected JSON should be contain List of G inside B which is inside A

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.4
- Database: Sqlite
- Operating system: Mac OS Mojave

**Comment by derrickmehaffy** [comment]
@jedinrk can you please provide examples of what you see and what you expect to see?

**Comment by jedinrk** [comment]
@derrickmehaffy 

My expect JSON would be 
`[
  {
    "id": 1,
    "Title": "title",
    "created_at": "2019-11-05T19:35:49.095Z",
    "updated_at": "2019-11-05T20:35:44.575Z",
    "Group": [
      {
        "id": 10,
        "Key": "key1",
        "Datatype": "String",
        "Data": "data1"
      },
      {
        "id": 9,
        "Key": "key2",
        "Datatype": "String",
        "Data": "data2"
      },
      {
        "id": 11,
        "Key": "key3",
        "Datatype": "String",
        "Data": "data3"
      }
    ],
    "B": [
      {
        "id": 1,
        "Type": "type1",
        "Title": "tile",
"Group": [
      {
        "id": 10,
        "Key": "key1",
        "Datatype": "String",
        "Data": "data1"
      },
      {
        "id": 9,
        "Key": "key2",
        "Datatype": "String",
        "Data": "data2"
      },
      {
        "id": 11,
        "Key": "key3",
        "Datatype": "String",
        "Data": "data3"
      }
    ],
        "created_at": "2019-11-05T19:15:31.898Z",
        "updated_at": "2019-11-05T19:25:14.930Z"
      }
    ]
  }
]`

But I get this instead.
`[
  {
    "id": 1,
    "Title": "title",
    "created_at": "2019-11-05T19:35:49.095Z",
    "updated_at": "2019-11-05T20:35:44.575Z",
    "Group": [
      {
        "id": 10,
        "Key": "key1",
        "Datatype": "String",
        "Data": "data1"
      },
      {
        "id": 9,
        "Key": "key2",
        "Datatype": "String",
        "Data": "data2"
      },
      {
        "id": 11,
        "Key": "key3",
        "Datatype": "String",
        "Data": "data3"
      }
    ],
    "B": [
      {
        "id": 1,
        "Type": "type1",
        "Title": "tile",
        "created_at": "2019-11-05T19:15:31.898Z",
        "updated_at": "2019-11-05T19:25:14.930Z"
      }
    ]
  }
]`

The Group List in the B content type is expected, but is missing

**Comment by lauriejim** [comment]
Can you please share your content types models, please.

**Comment by jedinrk** [comment]
@lauriejim 

`{
  "connection": "default",
  "collectionName": "journeys",
  "info": {
    "name": "journey",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "vars": {
      "group": "variables",
      "repeatable": true,
      "type": "group"
    },
    "Title": {
      "type": "string"
    },
    "Chapters": {
      "collection": "page"
    }
  }
}`


`{
  "connection": "default",
  "collectionName": "pages",
  "info": {
    "name": "page",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "PageType": {
      "type": "string"
    },
    "svars": {
      "group": "variables",
      "repeatable": true,
      "type": "group"
    },
    "Navigation": {
      "group": "navigation",
      "type": "group"
    },
  }
}`

**Comment by lauriejim** [comment]
I need your groups too.

**Comment by jedinrk** [comment]
@lauriejim group model:

`{
  "info": {
    "name": "Variables",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_variables",
  "attributes": {
    "Key": {
      "type": "string"
    },
    "Datatype": {
      "type": "string"
    },
    "Data": {
      "type": "string"
    }
  }
}`

**Comment by naveenlogiticks** [comment]
@lauriejim Hi any update on this

**Comment by lauriejim** [comment]
You miss the `navigation` group info.

**Comment by InsitesDigital-MO** [comment]
Hi, is there any more info on this issue?

I have a similar problem where groups don't appear in the JSON for content types use a relationship to link to another content type.

**Comment by naveenlogiticks** [comment]
> Hi, I would be interested in finding a solution for this, is there any more info on the issue / ways to fix it?
> 
> I have similar problems where groups don't appear in the JSON for content types use a relationship to link to another content type.

I solved it by using MongoDB instead of sqlite. This issue is caused only for sqlite Strapi implementation

**Comment by lauriejim** [comment]
I would love be able to reproduce the issue. Can you send me your navigation group please.

**Comment by lynnReilaender** [comment]
I have the same issue: _In general_, the REST API does not deliver groups and group based attributes of linked / related entities at the moment.

**Comment by lauriejim** [comment]
OKay here is clear https://github.com/strapi/strapi/issues/4661
I will keep this issue as referal.
