### ISSUE TITLE
Confirmation providers other than local

### ISSUE THREAD

**Issue by Mateuszry** [strapi/strapi#4461]
**Describe the bug**
When "Enable email confirmation" option is enabled users created after login by Facebook or other providers are not confirmed and there is only one way to activate them manually with content manage(Turn on "Confirmed" and save user).

**Steps to reproduce the behavior**
1. Turn on and configure any of available login providers in Roles & Permissions
2. Correctly login with provider
3. Use received JWT token on `/users/me` action
4. You should receive 401 response with body:
```
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Your account email is not confirmed."
}
```

**Expected behavior**
User created after login with provider other than `local` should be automatically `confirmed`

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.5
- Database: postgres:12
- Operating system: Ubuntu Linux with dockerized Strapi

**Comment by lauriejim** [comment]
Hello! Thank you @Mateuszry for reporting this issue and submitting PR.

**Comment by derrickmehaffy** [comment]
Marking this as closed as the PR was merged
