### ISSUE TITLE
Cannot build strapi admin

### ISSUE THREAD

**Issue by matthieuowlie** [strapi/strapi#4468]
**Describe the bug**
I'm unable to build Strapi admin with version 3.0.0-beta

**Steps to reproduce the behavior**
1. Go to strapi folder
2. npm install
3. strapi build

**Expected behavior**
The build would have been successful

**Screenshots**
![strapibuild](https://user-images.githubusercontent.com/56551343/68381801-be4ec200-0152-11ea-955a-7694251b4dfc.png)

![config](https://user-images.githubusercontent.com/56551343/68382104-53ea5180-0153-11ea-8986-a9905ae873cf.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Strapi plugin settings manager: 3.0.0-beta.17.3
- Database: sqlite
- Operating system: Windows

**Additional context**
I updated my strapi to the latest version (17.5 for everything but plugin settings manager in 17.3)
npm outdated tell me everythings up to date
it doesn't work in development or staging mode (sqlite or postgresql)
It worked before updating version

**Comment by Binnenhorster** [comment]
I had the same issue yesterday. You will find the solution in this migration guide:

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.16-to-beta.17.4.html

but it leads to confusion that this guide says something different: https://strapi.io/documentation/3.0.0-beta.x/guides/update-version.html#upgrading-your-dependencies

the documentation in the second link needs to be changed.

**Comment by lauriejim** [comment]
Hello! Thank for this message @Binnenhorster .

I suggest you check the **Migration Guide** section.
If there is a migration guide available for you version update, you have to follow the guide insteead of this update guide.
