### ISSUE TITLE
GraphQL multiple queries sometimes fail

### ISSUE THREAD

**Issue by alhill** [strapi/strapi#4469]
**Describe the bug**
When making a GraphQL query which calls several models sometimes it works but sometimes fails with an error (Expected Iterable, but did not find one for field Query.whichever.)

**Steps to reproduce the behavior**
1. Query multiple models through GraphQL
```
{
    configs{
        _id
    }
    roles{
        _id
    }
    equipos{
        _id
    }
}
```

2. About 80% of times the query will work without problem
```
{
    "data": {
        "configs": [
            {
                "_id": "5dbae64361026e0310514615"
            }
        ],
        "roles": [
            {
                "_id": "5dc1968891ea617674592eb5"
            },
            {
                "_id": "5dba8707df87024e64126d2c"
            },
            {
                "_id": "5dc008c732b888535dc9dfb2"
            },
            {
                "_id": "5dba8707df87024e64126d2d"
            }
        ],
        "equipos": [
            {
                "_id": "5dc2e4e791ea617674592f1d"
            },
            {
                "_id": "5dc2e67391ea617674592f1f"
            },
            {
                "_id": "5dc2e84d91ea617674592f20"
            }
        ]
    }
}
```

3. But the other 20%...
```
{
    "errors": [
        {
            "message": "Expected Iterable, but did not find one for field Query.equipos.",
            "locations": [
                {
                    "line": 8,
                    "column": 5
                }
            ],
            "path": [
                "equipos"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "message": "Expected Iterable, but did not find one for field Query.equipos.",
                    "stacktrace": [
                        "GraphQLError: Expected Iterable, but did not find one for field Query.equipos.",
                        "    at completeListValue (/home/ec2-user/environment/cix/node_modules/graphql/execution/execute.js:606:11)",
                        "    at completeValue (/home/ec2-user/environment/cix/node_modules/graphql/execution/execute.js:573:12)",
                        "    at /home/ec2-user/environment/cix/node_modules/graphql/execution/execute.js:492:16",
                        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
                    ]
                }
            }
        }
    ],
    "data": {
        "configs": [
            {
                "_id": "5dbae64361026e0310514615"
            }
        ],
        "roles": [
            {
                "_id": "5dc1968891ea617674592eb5"
            },
            {
                "_id": "5dba8707df87024e64126d2c"
            },
            {
                "_id": "5dc008c732b888535dc9dfb2"
            },
            {
                "_id": "5dba8707df87024e64126d2d"
            }
        ],
        "equipos": null
    }
}
```

I don't know if it could be related to #4280 or its bugfix #4328 because the data is correct when fetched (not like in this issue) and the error is only temporary

**System**
- Node.js version: v10.17.0
- NPM version: v6.11.3
- Strapi version: Beta 17.4
- Database: MongoDB
- Operating system: Debian

**Comment by lauriejim** [comment]
Haha, it's a horrible issue! "Sometimes" is the worst word for us.
Can you share with me your models, it will help me to "try" to reproduce.

**Comment by avdkishore** [comment]
This issue is actually true and gets very difficult to predict when this happens. The graphql plugin is highly unreliable.

**Comment by alhill** [comment]
Sorry for not answering this issue, I circumvented this problem making the query in other way, but today I've being trying to reproduce it.
First, I tried to update Strapi to make the tests with a fresh install of latest Strapi and... #4781
So I decided to try with 17.8 instead.

In the fresh installation of Strapi I created some models named model1, model2, model3... each one with 3 string fields named field1, field2 and field3. I have created two entries in each model.

With everything ready I started testing this query
```
{
    model1S{
        _id
        field1
        field2
        field3
    }
    model2S{
        _id
        field1
        field2
        field3
    }    
    model3S{
        _id
        field1
        field2
        field3
    }
    model4S{
        _id
        field1
        field2
        field3
    }
    model5S{
        _id
        field1
        field2
        field3
    }
    model6S{
        _id
        field1
        field2
        field3
    }
    model7S{
        _id
        field1
        field2
        field3
    }
}
```
It worked consistently

I thought maybe the failure it would happen if the models have relations between them and I created some random one-to-many and many-to-many relationship but it worked too.

After that I spotted that in my original post I was trying to fetch roles, from the users-permisions plugin so I added it to the query

```
{
    model1S{
        _id
        field1
        field2
        field3
    }
    model2S{
        _id
        field1
        field2
        field3
    }    
    model3S{
        _id
        field1
        field2
        field3
    }
    model4S{
        _id
        field1
        field2
        field3
    }
    model5S{
        _id
        field1
        field2
        field3
    }
    model6S{
        _id
        field1
        field2
        field3
    }
    model7S{
        _id
        field1
        field2
        field3
    }
    roles{
        _id
    }
}
```

And it returned the good old "Expected Iterable, but did not find one for field Query.xxx". As before it doesn't appears in any try, only sometimes.

But I decided to go a little further and added users from Users-Permissions plugin to the query too. And it went completely nuts. On each query it returned a different number of entries, filled with their data or nulled and once on a while, the Expected Iterable error, in one or many models.

Last try was removing some of the models of the query, maybe I was overcharging too much the query. It continued failing although not so much times.

A video example maybe is more explanatory, haha
https://www.youtube.com/watch?v=kfT7oprL1Lg

**Comment by alexandrebodin** [comment]
Hey thanks for the infos :) If you can try this PR https://github.com/strapi/strapi/pull/5109 and let me know if this fixed it it would be awesome !

**Comment by navicstein** [comment]
This issue as of `Feb 3 2020` is still pending even on development, this issue should be re-opened

**Comment by alhill** [comment]
I have running a Strapi 18.6 and a 18.7 and I cannot reproduce the error in the newer one. Querying several models seem now to return stable responses.
