### ISSUE TITLE
does not delete a field from database

### ISSUE THREAD

**Issue by deebov** [strapi/strapi#4473]
**Describe the bug**
I created and removed the `category` field from `Resources` content type. you can't see the removed field in strapi UI. but it is still in the database. When we try to add a `Resource` it gives us an error that says this:
![image](https://user-images.githubusercontent.com/28673719/68405908-bae32700-01a2-11ea-8017-97f460675637.png)

We even tried to re-create the `Resources` content type. but it didn't fix it. And when we looked at our database there was the `category` field that we have removed. you can see it here:
![image](https://user-images.githubusercontent.com/28673719/68406085-fda4ff00-01a2-11ea-95a8-0afc1c5d84b1.png)

![image](https://user-images.githubusercontent.com/28673719/68406175-26c58f80-01a3-11ea-9225-22cef5d25137.png)

**Steps to reproduce the behavior**
we don't know the exact reason and steps to reproduce this error. I think this happens once in a while but can be very problematic to fix.

**Expected behavior**
removed fields should be removed from the database as well.

**Screenshots**
see above ^

**System**
- Node.js version: v12.9.1
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.15
- Database: postgres ( in heroku )
- Operating system: heroku

**Additional context**

**Comment by nboussarsaracn** [comment]
Hi ! I am having the same issue. I am manually removing the fields from the table currently but a fix should come. Thanks!

**Comment by nboussarsaracn** [comment]
@deebov could you please add the label 'type: help wanted' https://github.com/strapi/strapi/labels/type%3A%20help%20wanted%20%F0%9F%A4%B7%E2%80%8D%E2%99%82%EF%B8%8F

Thanks!

**Comment by monico-moreno** [comment]
This might be related to this 👉 https://github.com/strapi/strapi/issues/1114#issuecomment-386552097

**Comment by lauriejim** [comment]
This is completely related to this issue.
Thank you @monico-moreno for this message.
