### ISSUE TITLE
Logout option

### ISSUE THREAD

**Issue by n8tb1t** [strapi/strapi#4474]
Strapi doesn't have the logout option, so if JWT token is compromised there is no way to prevent the hacker from accessing the protected content. Do you have a solution for this?
I think something like this could work:
https://stackoverflow.com/a/57522538

**Comment by derrickmehaffy** [comment]
@n8tb1t There is no way to invalidate a single token, Strapi does not store them yet in any capacity (Memory or database) as it stores no session information. The only way to invalidate a token would be to change your JWT key in `extensions/users-permissions/config/jwt.json`. This will however invalidate all users.

I would suggest you update your original post and turn this into a feature request following the proper FR template. For now I will mark this as closed as it doesn't follow any of the required templates. It can be reopened when you have updated the original post and/or created an entry on the product board.

(Side note I do agree this needs to be added, but right now the JWT is just an encrypted form of the user's data with an expire timestamp which by default is 30 days)

> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by derrickmehaffy** [comment]
I'm linking this issue: https://github.com/strapi/strapi/issues/3866 as it relates to storing session information in something like Redis with a fallback to the database itself.

**Comment by n8tb1t** [comment]
we can store the jwt secret in users data, and randomly generate it on log out. and use it in instead of process.env.JWT_SECRET...

**Comment by n8tb1t** [comment]
Also we can check if the user's IP is changed, and regenerate the secret as well

**Comment by derrickmehaffy** [comment]
The correct way would be to store the tokens in Redis (or fallback to memory/database) and implement a logout function to invalidate that token. We should never expose the JWT_SECRET to the user ever. As that is used to decrypt that jwt at the server to verify the information contained in it.

**Comment by n8tb1t** [comment]
I agree, about exposing the secret to users. so it could be stored in redis or in memory. but if a system has 1000s of users this will be a lot of data to store and verify.

**Comment by derrickmehaffy** [comment]
Aye yeah, JWT really isn't even designed as session storage to begin with. http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/

But the data storage problem no matter how you look at it would be something that a system like Redis is designed to handle (especially at scale)

**Comment by derrickmehaffy** [comment]
These are the main options for Stateful JWT: https://blog.indrek.io/articles/invalidate-jwt/

**Comment by n8tb1t** [comment]
Well, currently as a fix I'll create a model for storing secrets, and then regenerate them on logout. this model will only have one accessible method to authorized users, so the secret won't be exposed. and then inhttps://github.com/strapi/strapi/blob/9ae81b9dc943c5924a9184cad5dc3d60dc1c49ad/packages/strapi-plugin-users-permissions/services/Jwt.js#L54 I will use the key from the DB instead of  process.env.JWT_SECRET. I'll let you now if it works.
