### ISSUE TITLE
Global search does not filter on SQLite

### ISSUE THREAD

**Issue by KKings** [strapi/strapi#4477]
**Describe the bug**
In the Search bar on the Strapi Admin interface, search does not filter items correctly

**Steps to reproduce the behavior**
1. Create a content type, Category
2. Create a field, category_name, with a type of string
3. Create two categories based on the Category content type, one called 'Appliances' and one called 'Electric'
4. In the search bar on the top of the strapi admin interface, type 'Electric' - you could put anything and it still doesn't filter
5. Notice that both 'Appliances' and 'Electric' are shown still

**Expected behavior**
Search should filter the results correctly

**Screenshots**
<img width="723" alt="Screen Shot 2019-11-07 at 7 53 58 PM" src="https://user-images.githubusercontent.com/6739329/68440278-80748c80-0198-11ea-871b-a068963d322b.png">

**System**
- Node.js version: 11.3.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.17.5
- Database: sqlite
- Operating system: High Sierra

**Comment by animatedcreativity** [comment]
I upgraded from beta.15 to beta.16 & then beta.17.5. Everything is working fine except global search.
Filters are working as expected.

**Comment by nboussarsaracn** [comment]
Same problem is happening for me too. Some Content Types are `Global Search` `OK` whereas some are `KO`.

# Competency
Here is the content type called  `Competency` where it has a relation of type `Content has many Competencies`:
<img width="1680" alt="Competency - ContentType" src="https://user-images.githubusercontent.com/55238907/68550494-81f5bd00-0403-11ea-9362-be55ac642b27.png">

Here is the list of items belonging to `Competency`:
<img width="1680" alt="Competency - All" src="https://user-images.githubusercontent.com/55238907/68550493-81f5bd00-0403-11ea-8e54-d99016172093.png">

Here, the `Global Search` is working OK:
<img width="1680" alt="Competency - Search OK" src="https://user-images.githubusercontent.com/55238907/68550496-81f5bd00-0403-11ea-8fa0-24b8594a50c0.png">

# Content

Here is the content type called  `Content` where it has many relations to other entities: 
<img width="1680" alt="Content - All" src="https://user-images.githubusercontent.com/55238907/68550497-828e5380-0403-11ea-9754-d6789433955c.png">

Here is the list of items belonging to `Content`:
<img width="1680" alt="Content - ContentType" src="https://user-images.githubusercontent.com/55238907/68550498-828e5380-0403-11ea-88aa-e049bb3e49ef.png">

Here, the `Global Search` is NOT working - KO:
<img width="1680" alt="Content - Search KO" src="https://user-images.githubusercontent.com/55238907/68550499-828e5380-0403-11ea-887b-e701b31fbe82.png">

A help is appreciated :)

**Comment by nboussarsaracn** [comment]
@KKings could you please add the label 'type: help wanted' https://github.com/strapi/strapi/labels/type%3A%20help%20wanted%20%F0%9F%A4%B7%E2%80%8D%E2%99%82%EF%B8%8F

Thanks!

**Comment by MartinPL** [comment]
Looks like search don't work with the simplest configuration:
https://i.imgur.com/KinRbV2.png

**Comment by lauriejim** [comment]
This issue is due to SQLite. The implementation of the search works well on MongoDB, MySQL, PG but SQLite nop.

**Comment by derrickmehaffy** [comment]
ehhhh `MySQL, PG` not so much @lauriejim I believe @alexandrebodin is aware of SQL search issues but global search hasn't really worked that great with MySQL for sure.

**Comment by jos3000** [comment]
I came here to say that I have the same problem with `PG` on `3.0.0-beta.17.5`

**Comment by alexandrebodin** [comment]
If someone is willing to have a look it would be great :) I wont have time to check for a while

**Comment by JoshTheWanderer** [comment]
@alexandrebodin I've been looking at the searching on postgres, as we're having issues with it.

I'm seeing more relevant results for our use-case using a case-insensitive like rather than the current full-text query.

Would you accept a PR that switches to using like/ilike, and adds support for all the database clients? I noticed while digging through the code that only mysql and postgresql are supported at the moment.

**Comment by alexandrebodin** [comment]
@JoshTheWanderer There are quite a few tradeoffs if we actually decide to switch to using LIKE as the query engine isn't the same. It is a breaking change even if it might be a better fit. 

I need to dig a bit more in the legacy code to give you a definitive answer. I'm enclined to say it would be better to simply use LIKE queries and add a search engine plugin for user who need it.

**Comment by JoshTheWanderer** [comment]
@alexandrebodin, absolutely, it's a definite behaviour change. It does provide better results for us than the current implementation though.

If you do decide to go down this route then let me know and I can submit a PR, I've already made the changes locally.

**Comment by waymondo** [comment]
Also chiming in to say this isn't working for me with `pg` on `3.0.0-beta.17.8`.

I've found a workaround by overriding the content manager service locally at `extentions/content-manager/services/ContentManager.js`, deleting the `_q` parameter and replace it with custom query support, i.e.:

```module.exports = {
  search(params, query) {
    const { model } = params
    const source = delete query.source
    switch (model) {
      case "page":
        query.title_contains = query._q
        delete query._q
        break
      case "section":
        query.name_contains = query._q
        delete query._q
        break
    }
    return strapi.query(model, source).find(query)
  },
}```

Is `_q` is used by full-text support offered by bookshelf? I'm confused exactly how that option is interpreted. Is there some configuration or seeding step that is necessary that I'm missing?

**Comment by myrcutio** [comment]
I encountered this same issue, and @waymondo gave me an idea to try using bookshelf more directly:

```
module.exports = {
  // Search performs a bookshelf query
  // https://bookshelfjs.org/api.html#Collection-instance-query
  async search(params, query) {
    const { model } = params;
    const { source } = query;

    let contentType = strapi.query(model, source)

    return await contentType.model.query(qb => {
      const primarySort = query._sort.split(':')[0]
      const searchToken = '%' + query._q + '%'
      const querySearch = qb.where(primarySort, 'like', searchToken)
      Object.keys(contentType.model.attributes).map(attribute => {
        const attributeObject = contentType.model.attributes[attribute]
        if (attributeObject && attributeObject.type) {
          querySearch.orWhere(attribute, 'like', searchToken)
        }
      })
    }).fetchAll()
  },
}
```

This doesn't do anything for the count and totally breaks pagination, but it does return only relevant results.

**Comment by monkeymosher** [comment]
I have the same issue with `pg` on `3.0.0-beta.19.4`
