### ISSUE TITLE
Required Validator required for Related Fields

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4479]
**Describe the bug**
Required True/False option is missing for Releated Fields
**Steps to reproduce the behavior**
1. Create a ContentType Category
2. Create a ContentType Recipe
3. Add a String Field and Mark Required True
4. Add another Field of Type "Relation" (Recipe has one Category) (How to set required true )

**Expected behavior**
Required True/False option is missing for Related Fields

**Screenshots**
NA

**Code snippets**
"attributes": {
    "RecipeTitle": {
      "type": "string",
      "required": true
    },
 "category": {
      "model": "category",
      "required": true
    },
**System**

- Node.js version: v10.16.0
- NPM version:6.9.0
- Strapi version: 3.0.0-beta.16.5
- Database:Mongo :v4.0.10
- Operating system:Ubuntu 18.04

**Additional context**
Required true explicity added in Model.settings.file but still its allowing the data to be saved without dropdown value

**Comment by lauriejim** [comment]
Hello! Here is the same issue.
https://github.com/strapi/strapi/issues/557
