### ISSUE TITLE
Error with groups on model with "sku" as name

### ISSUE THREAD

**Issue by mdacosta** [strapi/strapi#4482]
**Describe the bug**
I have a model which name is `sku`. So the collection name and associated DB table are pluralized as `skus`.
[The `pluralize.singular('skus')` function returns `skus`, and this what is used when the column referencing the primary key of the `skus` table is created in the join table between the `skus` table and the group tables.](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/generate-group-relations.js#L51)
The problem is that when browsing in the administration to list existing entries, I have the following error : `Unhandled rejection error: column skus_groups.sku_id does not exist`.

My guess is that we don't use the `pluralize` lib for queries, but after searching for a while, I can't find where the `skus_groups.sku_id` field name is generated for the query.

**I would like to highlight on the fact that I can't reproduce the issue on any other acronym than "sku".** [I think there's a bug in the `pluralize` lib.](https://github.com/blakeembrey/pluralize/issues/137)
But still, I think that we should always rely on the `pluralize` lib everywhere.
What do you think?

**Steps to reproduce the behavior**
1. create a model with "sku" as name
2. create a group and add it to the model
3. try to create a new entry on the model
4. the page should not load and you should have an error in the logs

**Expected behavior**
We should be able to add a group on a model which has an acronym for name.

**Screenshots**

**Code snippets**

**System**
- Node.js version: v10.16.0
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.17.5
- Database: PostgreSQL 11.4
- Operating system: MacOS 10.13.6

**Additional context**

**Comment by alexandrebodin** [comment]
Hi @mdacosta. Can you test this in the latest version of strapi ? This should be fixed ;)

**Comment by lauriejim** [comment]
I can confirm, it works on the last version of Strapi. Thank @alexandrebodin for the fix.

**Comment by mdacosta** [comment]
> Hi @mdacosta. Can you test this in the latest version of strapi ? This should be fixed ;)

Yeah sorry I have no time to test, but I trust you on this one! 😃
