### ISSUE TITLE
Entry title doen't change 3.0.0-beta.17.5

### ISSUE THREAD

**Issue by sysRoot** [strapi/strapi#4483]
**Describe the bug**
Changing the entry title has no effect on my setup, in either development or production.
`id` persists as the entry title for the relations lists, but it changes for what appears at the top of an individual entry in the backend. I first thought it was an artifact from converting from alpha to beta, and as I didn't have any sort of important data, I scrubbed both the database and the install of strapi for my project, and rebuilt it

**Steps to reproduce the behavior**
Start a new strapi project on 3.0.0-beta.17.5
Create two contents, set a relation between them, specifically in my case, many to many.
Create a content in each respective content type
Set a relation between them, with default settings, you see the `id`
Edit the layout and change the `Entry title`, to a more sane field
Try to set a relation again, the chosen `Entry title` appears for the content itself now, but in the relationship field, it persists as ID

**Expected behavior**
Ability to change entry title, and have it affect the relational list selection, as of right now, I cannot see anything but `id`.

**Screenshots**
![Annotation 2019-11-08 094949](https://user-images.githubusercontent.com/414285/68485390-3974ae80-020d-11ea-8da1-c7c52dcdcede.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: Tested with v12/v13 not yet tested with v10, will report back
- NPM version: 6.12
- Strapi version: 3.0.0-beta.17.5 
- Database: MongoDB
- Operating system: Win10, not able to test on my Ubu server currently.

**Additional context**
I have reason to believe this could be an isolated incident, if not for the slack where another user mentioned having the same issue, but did not report if they had resolved it.

I can't bring myself to believe switching to nodejs v10 to be the fix, but I will try for the sake of sanity when I return from work.

**Comment by sysRoot** [comment]
Made a grave error in interpretation of problem, didn't see the other entry title option. My apologies.

**Comment by arabscimitar** [comment]
I have  the same error and not sure way entry title not changed for a some models
