### ISSUE TITLE
DATABASE_AUTHENTICATION_DATABASE is not set in database.json

### ISSUE THREAD

**Issue by botzill** [strapi/strapi#4484]
**Describe the bug**
When I set env `DATABASE_AUTHENTICATION_DATABASE=my_auth_db` I see that generated `database.json` does not contain 
```
"options": {
	"authenticationDatabase": "my_auth_db"
      }
```
which fails to start.

**Steps to reproduce the behavior**
Using example https://github.com/strapi/strapi-docker/blob/master/examples/mongo/docker-compose.yml

**Expected behavior**
To start OK with a mongo DB

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.17.5
- Database: Mongo
- Operating system: MacOS

If I manually add this options in `database.json` then it works ok.

**Comment by derrickmehaffy** [comment]
Please create the issue on the Strapi docker repo for this but you can set the field to 
`"authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE}"`

to allow usage with environment variables (the same applies to any setting in that file or globally within Strapi.

**Comment by botzill** [comment]
But it should generate proper `database.json` file when we do `strapi new `, no?

**Comment by botzill** [comment]
Solved it by using `- EXTRA_ARGS=--dbauth= my_auth_db`, but yes seems to be a docker issue, thx.
