### ISSUE TITLE
Load bootstrap function before defaults are loaded?

### ISSUE THREAD

**Issue by saikrishnadeep** [strapi/strapi#4485]
I was just wondering what the expected before of `functions/boostrap.js` must be? In my boostrapi, I'm loading environment variables from `.env` file since there is no default support for it. However, I noticed that the `boostrap.js` is called **after** the default configuration is set, where `this.config.evironment` is already is set. As you can see here: https://github.com/strapi/strapi/blob/9ae81b9dc943c5924a9184cad5dc3d60dc1c49ad/packages/strapi/lib/Strapi.js#L96-L133

Shouldnt the expected behaviour load boostrap.js BEFORE creating an instance of default config? Since the bootstrapi doesnt depend on the config anyway!

Any clarification would be appreciated. I can follow with a PR if this is what the default usage should be.

I would propose this should not to be default behavior. Since if I run `strapi start` the configuration doesnt take into account `bootstrap.js` however when `strapi develop` is run, since the options are updated after an instance has already been loaded
 
https://github.com/strapi/strapi/blob/9ae81b9dc943c5924a9184cad5dc3d60dc1c49ad/packages/strapi/lib/commands/develop.js#L32-L36

 this time the `boostrap.js` will overwrite the environment variables and `this.config` will use the environment variables from `.env`. Hence while developing the bootstrap functions overwrites default but not when its in production. Definitely fishy beahviour.

**Comment by derrickmehaffy** [comment]
@saikrishnadeep please make sure you follow the template we need the information contained at the bottom of it related to versions and OS. Issues that don't follow the template are closed until the template is added.

Thanks :smile: 

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello @saikrishnadeep !
Well the bootstrap function is called after the configuration load and after the database connection.
This let you play with your data, before your server start.

Here is an issue that talks about `.env` https://github.com/strapi/strapi/issues/3558
Hope it will help you.

Thank you for your feedback about adding configs in the start function of Strapi.
It has been sent to the team.

**Comment by saikrishnadeep** [comment]
@lauriejim Thanks for you reply Jim, I had gone through it over again. In fact, I use the exact same method as mentioned in that thread. Like I pointed out earlier.

`npm run development` -> Respects the .env file
`npm run start` -> Overrides the NODE_ENV variables and other variables from default configuration.

To understand why this is happening for development and not start, please check my original question above. Moreover, by simple `console.log` at the bootstrap.js you can see how the variables from `bootstrap.js` are being overridden the second time by default settings.

**Comment by lauriejim** [comment]
Can you give me an app and the .env file to be able to reproduce your issue please.

**Comment by saikrishnadeep** [comment]
Any variable like which is in the default config is overridden. For example, a simple `.env` file with the following 

```bash
NODE_ENV=staging # will be overriden to development
PORT=1234 # will be overridden to 1137
DATABASE_NAME=foo # will not be overridden since default config doesn't require it.
```

will have the above faulty behaviour when you `npm run start` but works just fine when you do `npm run development`

**Comment by saikrishnadeep** [comment]
@lauriejim I appreciate the concern, has there been any progress on this matter? If you do see this as faulty behaviour, I can make the appropriate PR for it. Please let me know.

**Comment by derrickmehaffy** [comment]
@alexandrebodin thoughts? I remember us having this conversation when it got changed before related to my query on loading dotenv.

**Comment by alexandrebodin** [comment]
@saikrishnadeep your bootstrapi file is required before the config load but the function it exports is executed after the load. 

Right now you should require your dotenv outside the bootstrapi function e.g :

```
const dotenv = require('dotenv');

dotenv.config()

module.exports = () => {
  // do other stuff
}
```

**Comment by saikrishnadeep** [comment]
@alexandrebodin Dear Alex, that is precisely what I'm doing. I've pointed out in the above comments that I'm using the same method as prescribed in #3558 however, this problem occurs. I've also pointed out in the above comments why some variables are being overridden by the default config parameters. I hope it is clear therein. Please let me know if any further clarification is required.

**Comment by sebastianjung** [comment]
Is there any solution to this problem yet?

**Comment by alexandrebodin** [comment]
@saikrishnadeep.

What you can simply do is instead of relying on the bootstrap function to load your dotenv you can create a server.js file as follows.

```js
const dotenv = require('dotenv');
const strapi = require('strapi');

dotenv.config();
strapi().start();
```

and update your `npm start`script to run `node ./server.js` instead of `strapi start`

We will certainly revisit the current implementation in the future but this is a good workaround

**Comment by derrickmehaffy** [comment]
^^^ what Alex said, although I do think it would be nice to eventually have a `strapi().develop();` so we could still run with auto-restart and use environment variables in a development environment.
