### ISSUE TITLE
Filtering data manyWay cause an 500 internal error with SQLite

### ISSUE THREAD

**Issue by TomaszJaworski** [strapi/strapi#4487]
Hello,
I think i found some bug in deep filtering data with relations. 

I have freshly installed new version of strapi cms on my computer and i create two new Content Types in it. In that case it will be Restaurants (width field name and description) and Tags (with field name). And now in Restaurants i create relations with Tags just like on image below
![relations](https://user-images.githubusercontent.com/1165339/68512140-d0765080-0277-11ea-9022-6e1de05f148f.png)

I put some random data and when i go to `/restaurants` endpoint i see something like this:
![relations_example](https://user-images.githubusercontent.com/1165339/68512454-bab55b00-0278-11ea-9ecd-d30ad90b47b4.png)

Everything looks god until i try to filter restaurants by tag name and go to `/restaurants?tags.name=food`. Filtering data resturn a `500 internal server error` and in console i have:
![relations_console](https://user-images.githubusercontent.com/1165339/68512707-6d85b900-0279-11ea-9e48-84c6c31fdf52.png)

When i try change relations type to other everyting is fine, but with that last one i have always same error. Is it a bug? or it is my mistake?

**System**
- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: Strapi v3.0.0-beta.17.5
- Database: SQLite
- Operating system: Windows 10 / Ubuntu Digital Ocean

**Comment by lauriejim** [comment]
Hello @TomaszJaworski !
Thank you for reporting this issue!
Your query looks OK the issue probably comes from Strapi.

**Comment by tranlehaiquan** [comment]
Is anything new? I try to create a blog with the same model and API (posts, tags, posts__tags). In docs `Strapi` suggest be careful with nest query and suggest a new route. So I create new route, controller, services with a custom query. I try to custom services and query but I realize I need to access table `posts__tags` which holding relation of `posts` and `tags` to get query base on tag.name but It seems no way to access `posts__tags`, right?
