### ISSUE TITLE
Unauthenticated Users are able to access protected resource

### ISSUE THREAD

**Issue by acifer** [strapi/strapi#449]
**Node.js v9.2.0**:
**npm 5.6.0**:
**Strapi 3.0.0-alpha.7.3**:
**Operating system Mac os Sierra.**:

if Authorization header is not passed to a request "plugins.users-permissions.permissions" policy is not able to restrict access on an User created api.

**Comment by lauriejim** [comment]
Hello @acifer can you be more precise. What do you mean by "User created API" ?
Don't really understand your problem.

**Comment by acifer** [comment]
When I create a custom API without using the Strapi-CLI tool or Admin dashboard api's are not getting protected by default.

**Comment by acifer** [comment]
@lauriejim were you able to reproduce the bug. Actually, my application was created using the Strapi version 6.4 then I successfully migrated to 7.2 but for a guest User the API is not protecting the endpoints created without using Strapi-CLI or admin dashboard. It will be really nicer if we have less magic in these CLI created API and everything is transparent.

**Comment by lauriejim** [comment]
We fix it in `alpha.8` all new controller's actions are disable for guest users and other groups you have created. To available it you have to use you admin dashboard.

To move to `alpha.8` you can use this guide https://strapi.io/documentation/migration/migration-guide-alpha-7-4-to-alpha-8.html

**Comment by acifer** [comment]
Closing it as it works in alpha.8
