### ISSUE TITLE
Wrong database.js generated if first attempt failed (mongodb)

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#4490]
**Describe the bug**
Using npx create-strapi-app, I generated manually a project linked to a local mongo database.
While doing so I typed to quickly and set ssl to true (instead of false, since I'm running locally). 
The second attempt (with ssl: false) was successfully able to connect to the db so my project generation ended up properly.

The issue is that when I used to start the development server (`npm run develop`) it could not start because unable to reach the database.

I noticed that my development `database.js` was like
```js
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "database": "test_strapi",
        "host": "127.0.0.1",
        "srv": false,
        "port": 27017,
        "username": "",
        "password": ""
      },
      "options": {
        "authenticationDatabase": "admin",
        "ssl": true
      }
    }
  }
}
```
It looks like the first attempt's settings were kept to generate this file.

**Steps to reproduce the behavior**
1. npx create-strapi-app my-app
2. Follow the steps and choose mongo as database
3. Set your local db params and choose ssl=true 
4. It will fail and prompt params again
5. Re enter the same settings but using ssl=false instead
6. Wait generation to finish
7. Open config/environments/development/database.js

> You will notice that ssl is set to true

**Expected behavior**
I expected the generated file to match my latest attempt

**Screenshots**
N/A

**Code snippets**
N/A

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: mongo
- Operating system: ubuntu 18.04

**Additional context**
N/A

This is not a critical bug but I spent time figuring out how to resolve it so it may discourage new users !
BTW thanks for this awesome tool, I especially enjoy the relation creation tool which is definitely a time saver for models definition !

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
I will try to fix it right now. I think it's an easy fix.
