### ISSUE TITLE
Auth providers for (React) Native applications

### ISSUE THREAD

**Issue by rnnyrk** [strapi/strapi#4491]
Hi,

Can the current docs be extended with a solution to use the auth providers with a native app? Currently it requires a client secret, but when making auth credentials for native apps there is not client secret provided. Would be really nice, since I've enjoyed Strapi for web, but would like to use it for native platforms as well

**Comment by pouyamiralayi** [comment]
>  for native apps there is not client secret provided

@rnnyrk what to do you mean? every auth provider will provide you with a token that can be stored locally on the mobile side.

**Comment by rnnyrk** [comment]
If you create an - for example Google - account in the dev console and you chose the iOS or Android option you won't get a client secret. But the client secret is required in the Strapi dashboard

**Comment by pouyamiralayi** [comment]
@rnnyrk you must enable ``Authorized redirect URIs``. the instruction is [here](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md).
google console has changed and you find the referenced section under credentials, OAuth client ID.
cheers!

**Comment by rnnyrk** [comment]
@pouyamiralayi  Like I said I would like to use it with a native app. When selecting iOS in the Google dev console there is no client secret 
<img width="641" alt="Screenshot 2019-11-11 at 14 06 00" src="https://user-images.githubusercontent.com/4519142/68589616-aba6f680-048c-11ea-8789-14e380e6aa7b.png">

**Comment by pouyamiralayi** [comment]
@rnnyrk i see. it would require it's own provider on the strapi side that implements [this](https://developers.google.com/identity/sign-in/ios/backend-auth).

**Comment by lauriejim** [comment]
Thank you for this feedback it's really interesting.

**Comment by alxistn** [comment]
Is there an existing solution to use strapi providers (aka Facebook, Google, etc...) in react-native for example ?

I am creating a mobile app with react-native and I need to use the strapi authentication providers but I have no clue how.

**Comment by rnnyrk** [comment]
I still didn't figure out an solution for this unfortunately

**Comment by crushy26** [comment]
@lauriejim do we have any solution here? or implement via existing solutions? please let us know here. It's critical for mobile apps.

**Comment by erikfenriz** [comment]
Any updates? Looking for examples with React Native as well.

**Comment by kabaros** [comment]
I will write this properly when I get a chance and add a PR to strapi, but leaving it for now as a comment, maybe it helps someone get in the right direction. 

You need to create a new provider in strapi (or update the existing Google one) to:

```javascript
switch (provider) {
    case 'google': {
      const google = purest({ provider: 'google', config: purestConfig });
      google
        .query('oauth')
        .get('tokeninfo')
        // this is the only difference from the default google provider from strapi, 
        // we'll be passing id_token rather than access_token similar to what's described here: https://developers.google.com/identity/sign-in/ios/backend-auth
        .qs({ id_token: access_token }) 
        .request((err, res, body) => {
          if (err) {
            console.log(err)
            callback(err);
          } else {
            console.log(body)
            callback(null, {
              username: body.email.split('@')[0],
              email: body.email,
            });
          }
        });
      break;
```

then in the React Native app using `@react-native-community/google-signin`


```javascript

import {
  GoogleSignin,
  statusCodes,
} from '@react-native-community/google-signin';

try {
      GoogleSignin.configure({
        webClientId: GOOGLE_WEB_CLIENT_ID, // Remember you need to setup a Web project in addition to the Android project in Google developer console, this bit took me a while to figure - read the @react-native-community/google-signin for more info
        offlineAccess: true
      });
      await GoogleSignin.hasPlayServices();


      const {idToken, serverAuthCode } = await GoogleSignin.signIn();

    // now at this point, the Android signin finished and returned a serverAuthCode and idToken
    // we will pass the idToken (not serverAuthCode as docs implied - this bit I need to understand more) 
    // to our Strapi custom Google provider, and that should link the Google account to a User in strapi and exchange the ID token with a JWT token we can use in the app
      const { data } = await axiosInstance().get('/auth/google/callback', {
      params: {
        access_token: idToken,
      },
    });

    const { jwt, user } = data;
    // save the JWT token and user info if you'd like 

    } catch (error) {
      if (error.code === statusCodes.SIGN_IN_CANCELLED) {
        // user cancelled the login flow
      } else if (error.code === statusCodes.IN_PROGRESS) {
        // operation (e.g. sign in) is in progress already
      } else if (error.code === statusCodes.PLAY_SERVICES_NOT_AVAILABLE) {
        // play services not available or outdated
      } else {
        // some other error happened
      }
    }


```

**Comment by hirengavit** [comment]
@kabaros  i can't find extensions/users-permissions/services/Providers.js

**Comment by amogh-jrules** [comment]
I tried the method mentioned here, but could not get it to work. https://stackoverflow.com/questions/57097415/extend-strapi-social-auth-providers-api-for-react-native This seems promising, will update the comment if this works out for me

**Comment by rnnyrk** [comment]
Currently I'm not working with Stripe anymore because I couldn't figure out social authentication with React Native. Anyone already found a working solution?

**Comment by Ernesto385291** [comment]
Any updates? I'm right now working on a react native project and I would love to use Strapi.

**Comment by Lith** [comment]
Hello, 

Maybe I will frust some people, but I'm using Google, Facebook and Apple provider in my mobile app with Strapi without problem. (I'm using Expo, so maybe this can be different of React Native app, but the way is the same).

I've changed the way to connect and I'm not using Strapi to generate the access_token, I do it natively in my app.
When this is done, I call the URL : 
```
https://api.domain.com/auth/google/callback?access_token=${accessToken}
```

Strapi has web authentication information set and I've generate an oAuth2 access for each device : 
![google_oauth2](https://user-images.githubusercontent.com/605495/108336712-a0389400-71d4-11eb-8333-a593b47950db.png)
- `web-app` : Strapi backend information 
- `expo`, one by device (android & ios)
-  `web-app-android-stage` : Generated mobile app for Android (stage environment)   
- `web-app-ios-stage` : Generated mobile app for iOS (stage environment)  

So, it's true than for now, Strapi is not perfect when you need a mobile app, but you can develop and use Strapi. 

Don't use Strapi to generate the `access_token`, do it natively (this will be a better experience for your customer and you gain some time of development) and send them directly to `callback`.

Thanks

**Comment by Gherciu** [comment]
I have a simple workaround ;)

1. In your React native/React app use 'react-google-login' or other similar lib to get the user `access_token`
2. Then with the obtained token call strapi endpoint `/auth/google/callback?access_token=${access_token}`
3. And this strapi endpoint will return a JWT and userPayload...

And that is))) simple

**Comment by derrickmehaffy** [comment]
actually gonna close this in favor of https://github.com/strapi/strapi/issues/4719

**Comment by steve-rodri** [comment]
@Lith What are you setting for "the redirect url to your front end app" in the strapi provider panel? Or are you not using it?

I've tried @Gherciu 's method but unless the google provider is activated it won't return the jwt

**Comment by am2222** [comment]
Hi, Any updates on this?
