### ISSUE TITLE
Have updated to beta 3.x and markdown editor has gone missing, no options to enable it again

### ISSUE THREAD

**Issue by kgrosvenor** [strapi/strapi#4492]
Markdown editor has gone missing, checkbox to enable also does not appear, is there anything that i am missing here?

EDIT: I notice there is now a RICH text type, how can i migrate data over?

**Comment by kgrosvenor** [comment]
Been of an annoying breaking change, but i think i can work around it, why couldn't we enable on a text type like before, seems like duplication to me!

**Comment by derrickmehaffy** [comment]
richtext type is the new WYSIWYG editor, it's no longer a setting in the database but hard coded in the file.
