### ISSUE TITLE
wrong folder structure when generating models for plugins using CLI

### ISSUE THREAD

**Issue by pouyamiralayi** [strapi/strapi#4493]
**Describe the bug**

Generating models for plugins using command line interface will nest models folder into an extra models folder.

**Steps to reproduce the behaviour**
1. create a new project: ``yarn create strapi-app test-strapi``
2. choose quick start (tested with postgres as well)
3. generate a new plugin: ``npx strapi generate:plugin test-plugin``
4. generate a new model for that plugin: ``npx strapi generate:model test-model --plugin test-plugin`` (also tested with ``generate:model test-model blah:string --plugin test-plugin``)
5. go to your plugin directory and see that there are 2 nested models directory.

**Expected Behaviour**

CLI would generate only one models folder not 2.

**Screenshots:**

![image](https://user-images.githubusercontent.com/53266765/68532582-522bb400-0334-11ea-8199-baf0ca696169.png)

**System:**

- Node.js version: 12.11.1
- Strapi version: 17.5
- Database: postgres, sqlite
- Operating system: windows 10 x64

**Comment by lauriejim** [comment]
Hello @pouyamiralayi !
Here is the same issue.
https://github.com/strapi/strapi/issues/3889
