### ISSUE TITLE
Disabling tutorials in admin panel has no effect

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#4495]
**Describe the bug**
Impossible to disable tutorials in admin ui. Since a ".cache" directory is in a ".gitignore" and it's being created during `npm run build` (when building an admin ui), there's no way to set `SHOW_TUTORIALS = false` on production. Also ".cache/admin/src/config.js" has a comment in the upper section:

```
// DO NOT MODIFY THESE OPTIONS
export const LOGIN_LOGO = null;
export const SHOW_TUTORIALS = true;
```
Why do not modify these options?

**Expected behavior**
There should be ENV variable, to control `SHOW_TUTORIALS` variable.

**System**
- Node.js version: LTS 10
- NPM version: 6
- Strapi version: beta 17.4 (3.0.0)
- Database: MySQL
- Operating system: Catalina 10.15.1

**Comment by derrickmehaffy** [comment]
Create a file at `admin/src/config.js` (not .cache, which is overwritten on each build)

Add this:
```
export const SHOW_TUTORIALS = false;
```

And rebuild

**Comment by webcoderkz** [comment]
Thanks, i also nuked ".cache" and "build" directories, then run "npm run develop" and it's kinda working.

**Comment by fmctaggart** [comment]
Just a warning to all that venture here - do not modify these options or you're dashboard may one day appear blank.
