### ISSUE TITLE
error Error: Undefined binding(s) detected when compiling SELECT.

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#4496]
**Describe the bug**
Trying to create a model entry through admin interface, but i'm getting an error: `Undefined column(s): [categories.id] query: select categories.* from categories where categories.id = ? limit ?`. I have 3 models: news, categories, videos. Every model gives the same error on creation, except the field name: categories.id, news.id, videos.id. I don't know why id is undefined? It's working fine on my development environment and database (db is exact copy of development in a production).

**Steps to reproduce the behavior**
1. Create dev and prod environments.
2. Make an exact copy of dev environment, and copy dev db to a prod db.
3. Try to create a new model entry on a production env.
4. Admin ui does this xhr request: `https://hostname/content-manager/explorer/category?source=content-manager` with an error 400, bad request: `Undefined binding(s) detected when compiling SELECT. Undefined column(s): [categories.id] query: select `categories`.* from `categories` where `categories`.`id` = ? limit ?`

**Expected behavior**
I expect dev and prod environments to be the same, but prod gives me headaches with some unknown errors.

** screenshots **
![image](https://user-images.githubusercontent.com/5739191/68543845-81026280-03e6-11ea-9d1d-d7664032620b.png)

**System**
- Node.js version: 10
- NPM version: 6
- Strapi version: 3.0.0 beta 17.4
- Database: MySQL
- Operating system: Catalina 1.15.1

**Comment by lauriejim** [comment]
Can you make sure your auto-increment ids are well setup after your data migration?

**Comment by webcoderkz** [comment]
Yeah, @lauriejim that's was the issue, i already fixed it, forgot to close this.

**Comment by lauriejim** [comment]
Haha okay thanks - already had this issue when I migrated my Strapi app in my prod database.

**Comment by TasosBak** [comment]
Hello guys! How did you fix the auto-increment ids?
