### ISSUE TITLE
Update web admin to handle nested repeatable groups

### ISSUE THREAD

**Issue by 8byr0** [strapi/strapi#4498]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Description**
It would be really appreciable to have ability to use nested repeatable groups!
It is actually possible but not through web admin.

Here is the definition for wrapping group:
```js
{
  "info": {
    "name": "WrapperGroup",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_wrappers",
  "attributes": {
    "items": {
      "group": "nested_group
      "repeatable": true,
      "type": "group"
    }
  }
}
```

And the nested one:
```js
{
  "info": {
    "name": "NestedGroup",
    "description": ""
  },
  "connection": "default",
  "collectionName": "groups_nested",
  "attributes": {
   "aBooleanAttribute": {
      "type": "boolean"
    }
  }
}
```

Doing so allows to query properly data (create, get, update...) via endpoints.
But the following features are missing :
- Nested group editor (shown as `[object Object]` in array field)
![image](https://user-images.githubusercontent.com/21955112/68547619-e7d24c80-03e3-11ea-976f-9599cdfbeb45.png)

- Allow group in group fields (option is missing)
![image](https://user-images.githubusercontent.com/21955112/68547632-046e8480-03e4-11ea-8079-29465d4e9b03.png)

A side effect I also noticed was in documentation plugin telling for GET endpoints that
> Could not render this component, see the console.

Feel free to tell me if you need additional information!

**Comment by alexandrebodin** [comment]
Hi @8byr0 this feature will be available in our next release ~ december.

I’m closing this issue until then :)

**Comment by 8byr0** [comment]
Great, thanks a lot ! (I'm in love with stapi 😃 )

**Comment by LuisOsta** [comment]
@alexandrebodin Is there a limit to the current number of nested repeatable groups? I noticed on the admin panel that there seems to only be support for one level of nesting.

**Comment by lauriejim** [comment]
Yes that's it. The admin design/UX can't manage more than 2 levels. But the code (manage the content through the API) has no limit in terms of deep structure.

**Comment by LuisOsta** [comment]
@lauriejim So if I wanted to create a component that had 2 levels deep of repeatable groups would making a custom UI element solve that problem? I want it to be something a non-technical person could use.

**Comment by derrickmehaffy** [comment]
That is the case @LuisOsta yes, during testing when you had more than 2 levels of nesting we noticed extremely bad performance and thus limited it to only 2 levels, at this point in time that is all we support.

**Comment by LuisOsta** [comment]
@derrickmehaffy Do you have any recommendations or resources I could look into on how to possibly restructure the data model? Also, would it be possible to have a repeatable group of dynamic zones? (I know that y'all get a ton of feature requests so I don't want to be that guy, I really love Strapi and the work y'all do).
