### ISSUE TITLE
Change properties in Strapi API documentation plugin swagger

### ISSUE THREAD

**Issue by deepakgd** [strapi/strapi#4499]
**Describe the bug**
Unable to change properties in Strapi API documentation plugin swagger.

I have created custom API called auth/google which verify Google tokenId and generate JWT token for Front end react.

Now i like to have custom properties in swagger API. Currently it contains { foo: "string" } in request body and all responses

**Steps to reproduce the behavior**
1. created users-permissions-User.json file in projectfolder/extensions/users-permissions/documentations/1.0.0/overrides/users-permissions-User.json
and then added below content

```
{
  "paths": {
    "/auth/google": {
      "post": {
        "deprecated": false,
        "description": "Login a user using the identifiers email and password",
        "responses": {
          "200": {
            "description": "response",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "tokenId": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        },
        "summary": "",
        "tags": [
          "Users-Permissions - User"
        ],
        "requestBody": {
          "description": "",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "tokenId": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
  "tags": [
    {
      "name": "Users-Permissions - User"
    }
  ]
}
}
```
2.Then http://localhost:1337/admin/plugins/documentation clicked regenerate button
3. clicked open button

**Expected behavior**
Properties should be updated

**Comment by fathonyfath** [comment]
Hey, 

I'm having similar problem and moving your overrides to `plugins` help solve the issue.

Apparently the code still looking at the `plugins` folder while now it is named `extensions`.

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/services/Documentation.js#L1905

So, if you have `projectfolder/extensions/users-permissions/documentations/1.0.0/users-permissions-User.json` you should place the overrides in `projectfolder/plugins/users-permissions/documentations/1.0.0/overrides/users-permissions-User.json`.

Hope that helps!

**Comment by deepakgd** [comment]
@fathonyfath same tried but if I stop process and start again using strapi develop command then all changes are discarded automatically

**Comment by deepakgd** [comment]
@fathonyfath Suppose if your code working please share me your github link i will try same

**Comment by fathonyfath** [comment]
Unfortunately it is private repo and I can't share it. 

I can give you the folder structure that I used to make overriding works.

```
.
+ extensions
| + users-permissions
| | + documentation
| | | + 1.0.0
| | | | + users-permissions-User.json
| | | | + users-permissions-Role.json
| + <other_extensions_here>
+ plugins
| + users-permissions
| | + documentation
| | | + 1.0.0
| | | | + overrides
| | | | | + users-permissions-User.json <your override file>
| | | | | + users-permissions-Role.json <your override file>
| + <other_overriden_docs_for_other_extensions>
+ api
+ config
+ <etc>
```

Everything in overrides folder will never be regenerated.

**Comment by deepakgd** [comment]
Hi @fathonyfath Due to long travel unable to try your idea. Just now I saw your suggestion. Unfortunately there is no such folder exists in project. Should i create plugins folder manually? Please find attachment 
![Screenshot from 2019-12-04 10-13-44](https://user-images.githubusercontent.com/8350548/70113409-1825a780-167f-11ea-92cd-9dd976734157.png)

Extension folder:
![Screenshot from 2019-12-04 10-16-41](https://user-images.githubusercontent.com/8350548/70113439-325f8580-167f-11ea-930b-091820344f65.png)
Currently i am using following version:
```
     "strapi": "3.0.0-beta.17.4",
    "strapi-admin": "3.0.0-beta.17.4",
    "strapi-hook-mongoose": "3.0.0-beta.17.4",
    "strapi-plugin-content-manager": "3.0.0-beta.17.4",
    "strapi-plugin-content-type-builder": "3.0.0-beta.17.4",
    "strapi-plugin-documentation": "3.0.0-beta.17.4",
```

**Comment by fathonyfath** [comment]
Yes, you should try create your own folder.

![image](https://user-images.githubusercontent.com/4829378/70114676-dbae7780-168f-11ea-9aa4-415f54c0bfad.png)

Here is my package.json:

```
    "strapi": "^3.0.0-beta.17.6",
    "strapi-admin": "^3.0.0-beta.17.6",
    "strapi-hook-bookshelf": "^3.0.0-beta.17.6",
    "strapi-hook-knex": "^3.0.0-beta.17.6",
    "strapi-plugin-content-manager": "^3.0.0-beta.17.6",
    "strapi-plugin-content-type-builder": "^3.0.0-beta.17.6",
    "strapi-plugin-documentation": "^3.0.0-beta.17.6",
    "strapi-plugin-email": "^3.0.0-beta.17.6",
    "strapi-plugin-upload": "^3.0.0-beta.17.6",
    "strapi-plugin-users-permissions": "^3.0.0-beta.17.6",
```

I believe this is a mistake from Strapi side, suggesting doing an investigation on this.

**Comment by derrickmehaffy** [comment]
```
    "strapi": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-admin": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-hook-bookshelf": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-hook-knex": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-plugin-content-manager": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-plugin-content-type-builder": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-plugin-documentation": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-plugin-email": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-plugin-upload": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
    "strapi-plugin-users-permissions": "^3.0.0-beta.17.6",   <--- Remove Carrot ^
```

Having carrots in front of Strapi packages may cause version to use the `@next` tag from npm instead of the proper `@beta` tag.

**Comment by fathonyfath** [comment]
Right, thanks for pointing it out.

**Comment by deepakgd** [comment]
@fathonyfath not working i am getting error `Error: You have some local plugins with the same name as npm installed plugins:
`
![Screenshot from 2019-12-04 14-42-15](https://user-images.githubusercontent.com/8350548/70129203-49fd3500-16a4-11ea-867b-b7426a957d4f.png)

**Comment by Prabhu161292** [comment]
+1 I am also facing same issue. Please help me to fix.

**Comment by krizic** [comment]
@fathonyfath is right, creating a parallel structure in plugins to place override file works. Unfortunately, it seems like a bug on strapi side and until its fixed, all overrides have to live in the plugins folder. Here is how I got it working for me. Reset server and regenerate docs.
![Annotation 2020-01-04 000732](https://user-images.githubusercontent.com/549492/71754472-95af2400-2e86-11ea-8fe5-fa3fe2bccd8e.png)

**Comment by krizic** [comment]
added PR which will fix this issue: https://github.com/strapi/strapi/issues/4499
