### ISSUE TITLE
Display components fields in the List view

### ISSUE THREAD

**Issue by botzill** [strapi/strapi#4501]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Not sure where to post this, so decided here. I was wandering if it's useful to have groups fields displayed in List View? For my use-case Is really useful to know the group in list view for easier management and browse of content. 

Thx!

**Comment by lauriejim** [comment]
Hello, can you give me an example, please.
With your real use case.

**Comment by soupette** [comment]
@lauriejim he wants to have the hability to display a the `group`'s (soon `component`) data in the table component in the content manager listview.

@botzill you can extend the plugin so it is displayed

**Comment by botzill** [comment]
Yes, I want to display that field into the listview as a column, @lauriejim how to easily extend that will this be possible in the future by default?

**Comment by lauriejim** [comment]
I'm asking the question because, like relations, what to display in the column?
If you have a repeatable group. It's hard to predict the value to display.

That why I would like a real use case to better understand the need.

**Comment by pixelprogrammer** [comment]
Just curious if I am understanding this correctly, would this work similar to Wordpress's ACF Flexible Content field?

So you would essentially have a dropdown of potential field groups to choose from (defined in the settings) which you can then start adding? This would also have a repeater option as well. So you could potentially mix and match group fields in many different orders.

**Comment by wysher** [comment]
I agree. Components and repeatable fields should be visible in Lists and have ability to filter them on List as well.

Setting visible fields probably should go to `Configure The View` page.

In my case for instance I have many models that requires basic client info like first/last name, phone, email etc. I can create component to not repeat myself, but then I will not see any basic data on list.

**Comment by IgorNoskov** [comment]
Guys, when will this feature be ready? It's a very necessary feature.

**Comment by KarolScibior** [comment]
Hi, any news regarding this feature?

**Comment by mationorato** [comment]
I would like to colaborate and code this feature, where can i start?

**Comment by markokhman** [comment]
+1 any status on this?

**Comment by markokhman** [comment]
Let me describe my case more precise:

I need to put this field:
<img width="857" alt="Screen Shot 2021-07-06 at 12 47 07" src="https://user-images.githubusercontent.com/5987968/124590827-df9e0f00-de5b-11eb-9b53-633401677ccd.png">

Here:
<img width="1183" alt="Screen Shot 2021-07-06 at 12 45 05" src="https://user-images.githubusercontent.com/5987968/124590851-e593f000-de5b-11eb-848c-dbbd4737f446.png">

How is that possible?

**Comment by ClareKang** [comment]
+1 any status on this?

**Comment by derrickmehaffy** [comment]
Locking thread as the status update checks are becoming too much. When/if we start working on this, you will see an update from us or a PR linked to the issue.

**Comment by soupette** [comment]
It's now possible with the v4, here's the associated [documentation](https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/admin-panel.html#predefined-hook) the example show how the i18n plugin inject the 'Content Available in' column in the table.



Here's how to display components value in the Content manager list view for all content types:

1. First use the admin configuration file to register the hook that will allow you to add a column in the table

Path: `my-app/src/admin/app.js`

```js
import injectColumnInTable from "./extensions/injectColumnInTable";

export default {
  config: {
    locales: ["fr"],
  },
  bootstrap(app) {
    app.registerHook(
      "Admin/CM/pages/ListView/inject-column-in-table",
      injectColumnInTable
    );
  },
};
```

2. Create a React component that will handle the display of the repeatable components:

Path: `my-app/src/admin/extensions/RepeatableCell.js`

```js
import React, { useState, useRef } from "react";
import styled from "styled-components";
import { Flex } from "@strapi/design-system/Flex";
import { Box } from "@strapi/design-system/Box";
import { Tooltip } from "@strapi/design-system/Tooltip";
import { Typography } from "@strapi/design-system/Typography";
import { Popover } from "@strapi/design-system/Popover";
import { SortIcon, stopPropagation } from "@strapi/helper-plugin";

const Button = styled.button`
  svg {
    > g,
    path {
      fill: ${({ theme }) => theme.colors.neutral500};
    }
  }
  &:hover {
    svg {
      > g,
      path {
        fill: ${({ theme }) => theme.colors.neutral600};
      }
    }
  }
  &:active {
    svg {
      > g,
      path {
        fill: ${({ theme }) => theme.colors.neutral400};
      }
    }
  }
`;

const ActionWrapper = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  height: ${32 / 16}rem;
  width: ${32 / 16}rem;
  svg {
    height: ${4 / 16}rem;
  }
`;

const RepeatableCell = ({ data, metadatas, name }) => {
  const [visible, setVisible] = useState(false);
  const buttonRef = useRef();

  const handleTogglePopover = () => setVisible((prev) => !prev);

  if (!data?.length) {
    return "-";
  }

  const mainField = metadatas.mainField.name;

  return (
    <Flex {...stopPropagation}>
      <Tooltip label="Display repeatable values">
        <Button type="button" onClick={handleTogglePopover} ref={buttonRef}>
          <Flex>
            <Typography
              style={{ maxWidth: "252px", cursor: "pointer" }}
              textColor="neutral800"
              ellipsis
            >
              {data[0][mainField] || "-"}
            </Typography>
            <ActionWrapper>
              <SortIcon />

              {visible && (
                <Popover source={buttonRef} spacing={16} centered>
                  <ul>
                    {data.map((entry) => (
                      <Box key={entry.id} padding={3} as="li">
                        <Typography>{entry[mainField] || "-"}</Typography>
                      </Box>
                    ))}
                  </ul>
                </Popover>
              )}
            </ActionWrapper>
          </Flex>
        </Button>
      </Tooltip>
    </Flex>
  );
};

export default RepeatableCell;
```

3. Create the hook 

Path: `my-app/src/admin/extensions/injectColumnInTable.js`

```js
import React from "react";
import get from "lodash/get";
import { Typography } from "@strapi/design-system/Typography";
import RepeatableCell from "./RepeatableCell";

const addColumnToTableHook = ({ displayedHeaders, layout }) => {
  // Skip if the content type does not have a component in its schema
  if (Object.keys(layout.components) === 0) {
    return {
      displayedHeaders,
      layout,
    };
  }

  // Retrieve all components field
  const componentsAttributes = Object.entries(
    layout.contentType.attributes
  ).filter((entry) => {
    const [, { type }] = entry;

    return type === "component";
  });

  // Create the components list layout
  const componentsToDisplay = componentsAttributes.map((attribute) => {
    const [attributeName, { type, component, repeatable }] = attribute;

    // Retrieve the mainField of the component. The one that is used in the edit view to know which field we want to display
    const mainFieldName = get(
      layout,
      ["components", component, "settings", "mainField"],
      ""
    );
    // Retrieve the mainField schema in order to apply custom rendering in case it's a date, number....
    const mainFieldSchema = get(
      layout,
      ["components", component, "attributes", mainFieldName],
      {}
    );

    const metadatas = {
      ...get(layout, ["contentType", "metadatas", attributeName, "list"]),
      mainField: { name: mainFieldName, schema: mainFieldSchema },
    };

    const schema = {
      key: `__${attributeName}_key__`,
      name: attributeName,
      fieldSchema: { type, component, repeatable },
      metadatas,
      cellFormatter: (data) => {
        if (repeatable) {
          return (
            <RepeatableCell data={data[attributeName]} metadatas={metadatas} />
          );
        }

        return (
          <Typography
            style={{ maxWidth: "252px", cursor: "pointer" }}
            textColor="neutral800"
            ellipsis
          >
            {data[attributeName]?.[mainFieldName] || "-"}
          </Typography>
        );
      },
    };

    return schema;
  });

  return {
    displayedHeaders: [...displayedHeaders, ...componentsToDisplay],
    layout,
  };
};

export default addColumnToTableHook;
```


Here's what the result should look like:


<img width="1568" alt="ctb-schema" src="https://user-images.githubusercontent.com/13311463/144268858-4b5c81a7-e2c6-4982-a02f-c6a992636b24.png">

<img width="798" alt="cm-edit-view" src="https://user-images.githubusercontent.com/13311463/144268893-afaafd5e-455c-47ba-9c81-83211e675440.png">

<img width="1139" alt="cl-lv" src="https://user-images.githubusercontent.com/13311463/144268958-fc7f6276-adb8-4b94-9d44-d43455d60ff0.png">

**Comment by derrickmehaffy** [comment]
Marking as closed as it's possible to do in the v4 but won't be added by default
