### ISSUE TITLE
Cannot trigger custom middleware when edit contents in Strapi UI

### ISSUE THREAD

**Issue by gengengengengen** [strapi/strapi#4502]
**Describe the bug**
Cannot trigger custom middleware when edit contents in Strapi UI.

**Steps to reproduce the behavior**
1. Create Strapi App of version 3.0 beta.
2. Create path `.middlewares/middlewares_name/` and add the `index.js` to the folder.
3. Write code in `index.js` followed the initiate function of guide. Add some loggers for test.
4. Create `middleware.json` in 'config/environments/ENV/' and add `middleware_name` to `config/middleware.json` to enable my middleware. 
5. Start Strapi and try some edit to contents. Middleware didn't work, no errors and logs.
(PS: I tried requests like `localhost:3000/myContent` can trigger the middleware.)

**Expected behavior**
Custom middleware triggered after edit contents in Strapi UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/12140810/68569683-b1570900-0499-11ea-9045-f6cf2c825f3e.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: none
- Operating system: Win 10 1903

**Comment by lauriejim** [comment]
Hello! I just tried top add a middleware and it works fine.

Here is a [short video](https://www.loom.com/share/2735fe860b3640a58831d50731efc129) of what I did.

**Comment by mateja176** [comment]
> **Describe the bug**
> Cannot trigger custom middleware when edit contents in Strapi UI.
> 
> **Steps to reproduce the behavior**
> 
> 1. Create Strapi App of version 3.0 beta.
> 2. Create path `.middlewares/middlewares_name/` and add the `index.js` to the folder.
> 3. Write code in `index.js` followed the initiate function of guide. Add some loggers for test.
> 4. Create `middleware.json` in 'config/environments/ENV/' and add `middleware_name` to `config/middleware.json` to enable my middleware.
> 5. Start Strapi and try some edit to contents. Middleware didn't work, no errors and logs.
>    (PS: I tried requests like `localhost:3000/myContent` can trigger the middleware.)
> 
> **Expected behavior**
> Custom middleware triggered after edit contents in Strapi UI.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/12140810/68569683-b1570900-0499-11ea-9045-f6cf2c825f3e.png)
> 
> **System**
> 
> * Node.js version: 10.16.3
> * NPM version: 6.9.0
> * Strapi version: 3.0.0-beta.16.8
> * Database: none
> * Operating system: Win 10 1903

I'm still having trouble with setting up middleware and perhaps the OP experienced the issues because of the `.` prefix in `.middlewares`.

@lauriejim unfortunately the video is no longer available. Can you share the code please?

Also it would be really awesome if the cli had an option to scaffold middleware, however that is a topic for another thread.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
