### ISSUE TITLE
Policies not working for graphql queries

### ISSUE THREAD

**Issue by devyourcar** [strapi/strapi#4503]
**Describe the bug**
Local strapi policies (e.g. api/config/policies/isOwner.js) do not work for graphql queries. The same policies work for mutations and rest endpoints however.

**Steps to reproduce the behavior**
1. Create a new api controller, with a custom function. (e.g. sample(){})
2. Create a custom local policy under config/isOwner.js
3. Create a config/schem.graphql.js file, create a new query that uses the sample function above as well as the local isOwner policy.
4. Start the server. The following error comes up: 
`Ignored attempt to bind to GraphQL query "sample" with unknown policy "isOwner"`

**Expected behavior**
The isOwner policy should be recognised by the strapi graphql plugin.

**Code snippets**
I believe the problem is under `strapi-plugin-graphql/services/Schema.js#255`.

```
switch (type) {
          case 'Mutation': {
            let name, action;
            if (
              _.has(resolverObj, ['resolver']) &&
              _.isString(resolverObj.resolver)
            ) {
              [name, action] = resolverObj.resolver.split('.');
            } else if (
              _.has(resolverObj, ['resolver', 'handler']) &&
              _.isString(resolverObj.resolver.handler)
            ) {
              [name, action] = resolverObj.resolver.handler.split('.');
            } else {
              name = null;
              action = resolverName;
            }

            const mutationResolver = Mutation.composeMutationResolver({
              _schema: strapi.plugins.graphql.config._schema.graphql,
              plugin,
              name: _.toLower(name),
              action,
            });

            acc[type][resolverName] = mutationResolver;
            break;
          }
          case 'Query':
          default:
            acc[type][resolverName] = Query.composeQueryResolver({
              _schema: strapi.plugins.graphql.config._schema.graphql,
              plugin,
              name: resolverName,
              isSingular: 'force', // Avoid singular/pluralize and force query name.
            });
            break;
        }
```

The query should pass the same **name** to the compose function as Mutation. (As mentioned, policies work for mutations). Perhaps the switch case statement is not necessary, so the resolverObj logic can be reused?

**System**
- Node.js version: 10.17.0
- NPM version: 6.13.0
- Strapi version: v3.0.0-beta.17.5
- Database: Postgres
- Operating system: OSX Catalina

**Comment by lauriejim** [comment]
Hell! Can you please share your `config/schem.graphql.js`
