### ISSUE TITLE
Dynamic configurations

### ISSUE THREAD

**Issue by lucaperret** [strapi/strapi#451]
Node.js version: v8.9.0
npm version: 5.6.0
Strapi version: 3.0.0-alpha.7.3
Operating system: macOS Sierra

Dynamic configurations isn't working properly.
When using template literals on database name configurations `"database": "${process.env.DB_NAME}"`, mongodb thrown an error: `ERROR (MongoError/33 on 5e9ae6854dbd): database names cannot contain the character '.'`.
It is the same on each connection field.

**Comment by Aurelsicoko** [comment]
It has been fixed in this commit (https://github.com/strapi/strapi/pull/431/commits/9031ff1799e5aa4c285a6acedbafe125c2a189e6#diff-9644d9780d0570bf4d1528fc66540eb6R378). It should be released quickly.

**Comment by Aurelsicoko** [comment]
It has been fixed on alpha.8.3. Feel free to reopen the issue if it still doesn't work.
