### ISSUE TITLE
The provider package isn't installed. Please run `npm install strapi-upload-undefined`

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#4510]
**Describe the bug**
After running a created project in production env we had this error
Error: The provider package isn't installed. Please run `npm install strapi-upload-undefined`
I'm using a local provider.

**Steps to reproduce the behavior**
Deploy your app from local machine to a production using this guide: https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#configuration

**Expected behavior**
on production files must be uploaded without any issues, using local provider.

**System**
- Node.js version: 10
- NPM version: 6
- Strapi version: 3.0.0 - beta 17.4
- Database: MySQL
- Operating system: Ubuntu 18.04 LTS

**Additional context**
Manually modifying table `core_store` - `plugin_upload_provider`:

```
{"enabled":true,"provider":"local","sizeLimit":2000}
```

I've added "provider": "local" and it works.

**Comment by lauriejim** [comment]
Hello! It's not really clear to me.
Did you migrate some database info during your production deployment?

**Comment by webcoderkz** [comment]
@lauriejim i've migrated exact dev db copy in to production database.

**Comment by lauriejim** [comment]
Can you tell me what your `package.json` look likes

**Comment by alxnkt** [comment]
In my opinion, the cause of this this behavior is a bug in upload configuration save form `http://localhost:1337/admin/plugins/upload/configurations/production`. When I save development mode, the form sends:
```
enabled: true
provider: "local"
sizeLimit: 1000
```
When I save production or stage configuration, it sends:
```
enabled: true
sizeLimit: 3000
```

That is why core_store does not contain `provider` field for production and stage configurations.

**Comment by alxnkt** [comment]
I tried to use method of @webcoderkz, and it's working for me. If you don't want to have a deal with db, you can just comment out this two lines in `/node_modules/strapi-plugin-upload/admin/src/containers/ConfigPage/saga.js`
```
    // if (body.provider === 'local') {
      body = {
        enabled: body.enabled,
        provider: 'local',
        sizeLimit: body.sizeLimit,
      };
    // }
```
and then save configuration via you API UI. Rebuild is required.
So ugly hack... Hope, this will be fixed.
IMHO, the root of the problem is that `core_store` `plugin_upload_provider` is not filled by defaults for stage and production environments.
