### ISSUE TITLE
UsersPermissions initialize bootstrap function is slow

### ISSUE THREAD

**Issue by victorlambert** [strapi/strapi#4511]
Hi there,

After upgrading to v3.0.0-beta.17.5 strapi is taking  ~20 sec to start with `strapi dev`.
Seems to be the UsersPermissions `initialize` bootstrap function causing this issue (~19sec).

**Steps to reproduce the behavior**
1. Create an app with 20 api/content types and 8 roles
2. Start the app with `strapi dev`

**Expected behavior**
It was taking less than 7 sec in v3.0.0-beta.11 with the same configuration.

**Screenshots**
![Screenshot 2019-11-12 at 10 45 39](https://user-images.githubusercontent.com/9954979/68661878-fb90c680-053b-11ea-804d-ee415fa08031.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.17.5 
- Database: MongoDB
- Operating system: MacOS / Unix

**Additional context**
The number of content types and roles is creating a big number of permissions entries (1800+) in `users-permissions_permission` database collection, causing I guess, slow manipulations in `initialize` (and more precisely `updatePermissions`) function in UserPersmissions service.

**Comment by victorlambert** [comment]
Here are some updates, it was so annoying that I had to dig into it 😅.
This is line is causing the issue.
https://github.com/strapi/strapi/blob/447594684d1ebcc283f19cc22f242e3684b2e583/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L392

Since we are using the query builder to retrieve roles, it autopopulates permissions and users by default, and I have 1800+ permissions and 23000+ users in my case, causing the slow start.

Extending roles model and setting autopopulate to false to both users and permissions fixed my issue, I am back to 3 sec to start the app. Not sure if we should set this by default in the role model though, or if we have to change something to prevent this.

**Comment by n8tb1t** [comment]
So this change won't affect the strapi work? can you please provide the extended roles model with the changes.

**Comment by victorlambert** [comment]
Populated users and permissions do not seems to be used in this case. It may affect other strapi services dependent of this default behaviour but I haven't found any.

Everything is working fine since I extended the role model like this in `extensions/users-permissions/models/Role.settings.json` :
```
{
  "connection": "default",
  "info": {
    "name": "role",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string",
      "minLength": 3,
      "required": true,
      "configurable": false
    },
    "description": {
      "type": "string",
      "configurable": false
    },
    "type": {
      "type": "string",
      "unique": true,
      "configurable": false
    },
    "permissions": {
      "collection": "permission",
      "via": "role",
      "plugin": "users-permissions",
      "configurable": false,
      "autoPopulate": false,
      "isVirtual": true
    },
    "users": {
      "collection": "user",
      "via": "role",
      "configurable": false,
      "autoPopulate": false,
      "plugin": "users-permissions"
    }
  },
  "collectionName": "users-permissions_role"
}

```

**Comment by n8tb1t** [comment]
@victorlambert it should be extended after the project is ready and all the permissions already stored in the DB? What the `autoPopulate` means exactly, so now the permissions won't be cached in memory and strapi will check the db each time ?

**Comment by victorlambert** [comment]
@n8tb1t doing this, you are just overriding the role mongoose model of the users-permissions plugin.
More info here [https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#plugin-extensions](url).

This is nothing about caching, `autoPopulate` is an undocumented feature that let you decide default mongoose population when using strapi queries ([https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html](url).
