### ISSUE TITLE
Сontent id is not really unique, that bad for security

### ISSUE THREAD

**Issue by MurzNN** [strapi/strapi#4517]
Current id of created content at first time looks like unique id's, but really they are not unique! When users create content they only iterates buy +1, for example: `5dc16735bd5a00594ab3cbbf`, `5dc16740bd5a00594ab3cbc0`, `5dc16765bd5a00594ab3cbc1` like regular integer auto-increment field.

If we use unique ID's, they must be really unique and randomly generated, instead of iterated numbers, going in order. Current way have very bad security, because having current content id, each user can easily lookup previous and next content items.

For generate really unique id's we can use https://www.npmjs.com/package/uniqid library or something similar. Here is list of popular unique id generators: https://github.com/grantcarthew/awesome-unique-id

**Comment by derrickmehaffy** [comment]
Please update the issue following the template, also do feel free to submit a PR.

> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by lauriejim** [comment]
Hello! I suggest you to use this feature to add this kind of feature in your application.
https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#database-orm-customization
There is the same topic with SQL database.

**Comment by MurzNN** [comment]
Thanks, this is great and simple solution! But find this is not easy, so will be good to recommend this way in Strapi install docs as alternative to default uuid generator.

**Comment by derrickmehaffy** [comment]
All of the SQL DB IDs typically use the standard integer value so mongo doing something similar isn't all that much of a risk. If someone needed the extra security they could follow this method. If you wanted to submit a PR @MurzNN detailing the process you are more than welcome to.

**Comment by MurzNN** [comment]
For MySQL there are auto_increment integers used as content id, so content id's are 1, 2, 3, etc - that's ok. But MongoDB by default use non-numeric hash strings, so better to have them unique by default, instead of serial, in Strapi. Even if this can be simply solved via adding `mongoose-simple-random` plugin.
