### ISSUE TITLE
Cannot use an external database with strapi

### ISSUE THREAD

**Issue by gourraguis** [strapi/strapi#452]
**Node.js version**:v8.9.0
**npm version**:5.6.0
**Strapi version**:3.0.0-alpha.7.3
**Operating system**:Windows 10
I want to use strapi with an external mongoDB database hosted at mLab, I configured my strapi application to connect with the right setting on on the database.json file:
`{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "ds045867.mlab.com:46727",
        "port": 46727,
        "database": "myDb",
        "username": "myUsername",
        "password": "myPassword"
      },
      "options": {}
    }
  }
}
`
Still, no matter how much I try it, it doesn't connect, I keep getting the same error which is:
`DEBUG (6496 on DESKTOP-HAL6BGE): Server wasn't able to start properly.
ERROR (6496 on DESKTOP-HAL6BGE): (hook:mongoose) takes too long to load
`
What do you think is the problem? I'm not sure if I'm doing something wrong or if external databases don't work.

**Comment by alexanderwallin** [comment]
You are including the port number in the `host` field – is that correct?

**Comment by htamhue** [comment]
i have a same issue 
![alt text](https://image.prntscr.com/image/a-V9XLwbTty2QzQ6fXF0mQ.png)

**Comment by Aurelsicoko** [comment]
As @alexanderwallin said, try to remove the port number from the host URL.

```json
{  
   "defaultConnection":"default",
   "connections":{  
      "default":{  
         "connector":"strapi-mongoose",
         "settings":{  
            "client":"mongo",
            "host":"ds045867.mlab.com",
            "port":46727,
            "database":"myDb",
            "username":"myUsername",
            "password":"myPassword"
         },
         "options":{  

         }
      }
   }
}
```

**Comment by LasaleFamine** [comment]
+1 here. 
Here is my db configuration:
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "dsXXXXX.mlab.com",
        "port": "19018",
        "database": "strapi",
        "username": "XXX",
        "password": "XXX"
      },
      "options": {}
    }
  }
}
```

Getting the same error of @gourraguis.

**Comment by Aurelsicoko** [comment]
@gourraguis @LasaleFamine Did you create the first user of your mLab database? If yes, are you using the username/password of this user to connect?

It's a common mistake to forget to create the user on mLab. The UX is pretty bad...

**Comment by LasaleFamine** [comment]
Yeah, I'm trying with my first user/password.
Don't you have the same problem?

**Comment by bishoymelek** [comment]
+1
the same here

**Comment by pierreburgy** [comment]
We published an article explaining [how to use Strapi with mLab](https://blog.strapi.io/using-mlab-with-strapi/). Please reopen the issue if you still have the problem.

**Comment by koolkav1** [comment]
I have the exact same problem with Windows 7 and I followed the mLab tutorial on medium.

**Comment by johhansantana** [comment]
the article seems outdated.

I have added the following as my configuration

```
Lets configurate the connection to your database:
? Choose your main database: MongoDB (recommended)
? Database name: johhansantana
? Host: ds******.mlab.com
? +srv connection: false
? Port (It will be ignored if you enable +srv): 61072
? Username: jsantana
? Password: ********
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: false

⏳ Testing database connection...
⚠️ Database connection has failed! Make sure your database is running.
```

2 questions from here are a bit confusing compare to mysql/postgres setup.

+srv ?
What is an `Authentication database` the example is not clear.
What's the difference between doing SSL connection or not?

**Comment by usb248** [comment]
Same issue. Problem comes from strapi and not mlab. I checked my mlab connection with node and it works but not with strapi...

**Comment by lauriejim** [comment]
Please check this issue https://github.com/strapi/strapi/issues/2013
We will update the article
