### ISSUE TITLE
POST requests to strapi returns 404

### ISSUE THREAD

**Issue by omerfaran** [strapi/strapi#4520]
**Describe the bug**
My strapi system resides in port 443. When I'm sending a GET request to http://mysite:443 it's working but a POST request reutrns 404.

**Steps to reproduce the behavior**
1. Go to https://reqbin.com/
2. Send an empty POST request

**Expected behavior**
Should not return a 404
**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.15
- NPM version: 6.4
- Strapi version: 3.0
- Database:
- Operating system: Centos

**Additional context**
Thanks in advance

**Comment by derrickmehaffy** [comment]
@omerfaran we need more information. We need your actual strapi version, your database type and version, how are you running your server, permissions configured, model settings.

Right now I can't reproduce your bug without more information. Please update the original post with all the needed information then respond here and I can reopen your issue.

**Comment by omerfaran** [comment]
Hello Derrick I appologize for the trouble and it seems like the issue is regarding to something else, so thanks for replying and closing it
