### ISSUE TITLE
Infinite loading after admin registration on /admin

### ISSUE THREAD

**Issue by joelbqz** [strapi/strapi#4521]
When creating a new project using `yarn create strapi-app my-project` and selecting MySQL(It works well with SQLite) then after yarn develop, I open the /admin route, register a new admin and it keeps infinite loading without showing any log or error.

**Steps to reproduce the behavior**

1. `yarn create strapi-app my-project`
2. select MySQL
3. wait until installation finish, then open http://localhost:1337/admin
4. try to register the admin
5. infinite loading
6. try to open again http://localhost:1337/admin and keeps on infinite loading

**System**

Node.js version: v11.0.0
NPM version: 6.4.1
Strapi version: 3.0.0-beta.17.5
Database: MySQL 5.7.23
Operating system: macOS Mojave 10.14.5

The issue is only with MySQL, works well with SQLite

**Comment by joelbqz** [comment]
PD:  I tested again using MongoDB and the same issue is happening.

**Comment by joelbqz** [comment]
Update: just tested changing my node version, downgraded from v11 to v10.x.x and it is working now.

**Comment by derrickmehaffy** [comment]
Only Node LTS versions are supported. ("Even" Numbered releases)

So Node 12, Node 10 only. Marking as closed as was user environment issue.
