### ISSUE TITLE
wrong order of saved files

### ISSUE THREAD

**Issue by vlad320** [strapi/strapi#4525]
Hello 👋

**Describe the bug**
When adding multiple files at once, their order does not match what was before saving.  
The more files, the more likely that the order will be violated. When saving six files, the problem is observed 9 out of 10 times.

**Steps to reproduce the behavior**
1) create a file type field with a multiple mark
2) add multiple files to it
3) save item  

**Before save**
1) 
![image](https://user-images.githubusercontent.com/16899697/68853719-58e86b80-0726-11ea-80ae-8ff70186533e.png)
2)
![image](https://user-images.githubusercontent.com/16899697/68853741-643b9700-0726-11ea-8443-2d217019f1ec.png)
**Afte Save**
1)
![image](https://user-images.githubusercontent.com/16899697/68853907-b41a5e00-0726-11ea-9b40-1741712dc92d.png)
2)
![image](https://user-images.githubusercontent.com/16899697/68853937-c1374d00-0726-11ea-8f06-65944b2e003c.png)

**System**
nodejs v10.16.0
NPM v6.10.3
Strapi version: 3.0.0-beta.16.7
Database: mongodb
Operating system: WSL Windows 10 - Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
Strapi has no way to manage the order of files. Right now they just return in the order the database responds with.

There is already quite a few issues related to specific ordering that will be addressed in the future based on this blog post: 
![image](https://user-images.githubusercontent.com/8593673/68894270-303f8200-06e4-11ea-88b9-62015838863d.png)

https://strapi.io/blog/monthly-update-september-2019?redirectPage=1

But there is no ETA.

**Comment by lauriejim** [comment]
Hello! If you want to use the media file to do a carousel, I suggest you to create a group - with an image and a order.
In this way, you will have consistency in your image order.
We have a card about that in the Roadmap. Can you please send you feedback there.
https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities
Thank you.
