### ISSUE TITLE
Accessing config in services

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#4527]
**Describe the bug**
`strapi.config` lacks defined config in services declaration.

Let's say I have `config/environments/custom.json`:
```js
{
    "baseUrl": "https://base.url
}
```

Then I'd like to use it in `api/{name}/services/{service}.js`:
```js
const apiClient = got.extend({
    baseUrl: strapi.config.baseUrl
})

module.exports = { ... }
```

But `strapi.config` doesn't have the properties from config, which I think most developers would expect.

Am I doing something wrong, or is it some kind of a bug?

**System**
- Node.js version: v12.10.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.17.5
- Database: SQLite
- Operating system: OSX

**Comment by lauriejim** [comment]
Hello! Your config structure is not correct.
You are adding a JSON file in the `environments` folder.

If you want a custom config by env, you will have this structure `config/environments/development/custom.json` and `config/environments/production/custom.json`

Then how to access it, by using `strapi.config.currentEnvironment. baseUrl`

If you want a global config var, it will be `config/custom.json`
And you will access via `strapi.config.baseUrl`

**Comment by sarneeh** [comment]
@lauriejim I was talking about `config/environments/{environment}custom.json`. It was a typo in my description. It still doesn't work the way you describe it.

It works inside the exported functions, but does outside of them:

`api/{name}/services/{name}.js`:
```js
 // doesn't work:
 console.log(strapi.config.currentEnvironment)
 
 module.exports = {
   someFunction() {
    // works:
    console.log(strapi.config.currentEnvironment)
   }
}
```

**Comment by lauriejim** [comment]
Hello. It's normal and I will explain to you the reason.

When strapi start, we are loading all your controllers / services / policies / configs in the same time.
So when strapi is loading your code, your first log contains an empty `strapi.config`.
Then when your function is called, all the config are loaded and that's fine.

To deal with your use-case of having a client that us your config by env, I suggest you to use a hook (that is what I do with my Strapi apps.)
Here is the [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/hooks.html#custom-hooks)

In your example, you can have something like that.

**Path —** `./hooks/got/intex.js`

```js
const got = require('got');

module.exports = strapi => {
  const hook = {
    initialize: async () => {
      strapi.got = got.extend({
        baseUrl: strapi.config.baseUrl
      });
    }
  };

  return hook;
};
```

and then in your controllers, you can use `strapi.got(...)`

**Comment by sarneeh** [comment]
@lauriejim Didn't think about this kind of solution! Thank you very much!

**Comment by lauriejim** [comment]
Your welcome! I'm here to help you and let you have a good exp with Strapi.

**Comment by BobLamarley** [comment]
> Hello. It's normal and I will explain to you the reason.
> 
> When strapi start, we are loading all your controllers / services / policies / configs in the same time.
> So when strapi is loading your code, your first log contains an empty `strapi.config`.
> Then when your function is called, all the config are loaded and that's fine.
> 
> To deal with your use-case of having a client that us your config by env, I suggest you to use a hook (that is what I do with my Strapi apps.)
> Here is the [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/hooks.html#custom-hooks)
> 
> In your example, you can have something like that.
> 
> **Path —** `./hooks/got/index.js`
> 
> ```js
> const got = require('got');
> 
> module.exports = strapi => {
>   const hook = {
>     initialize: async () => {
>       strapi.got = got.extend({
>         baseUrl: strapi.config.baseUrl
>       });
>     }
>   };
> 
>   return hook;
> };
> ```
> 
> and then in your controllers, you can use `strapi.got(...)`

I'm facing the same problem inside /extensions/models/user.js : 
This portion of code 
![image](https://user-images.githubusercontent.com/7857364/72811790-a6221580-3c60-11ea-92bd-7f55dc57f803.png) is outside `module.exports = {}`
So i created a hook in `./hooks/got/index.js` as you said : 
![image](https://user-images.githubusercontent.com/7857364/72812155-44ae7680-3c61-11ea-8b8f-c9d61f803785.png)

Then i activate it according to the doc :  
![image](https://user-images.githubusercontent.com/7857364/72812117-34969700-3c61-11ea-83ca-b668bd6872f8.png)
And replace the first portion of code that was causing the problem by using the new born hook :)
![image](https://user-images.githubusercontent.com/7857364/72812248-76274200-3c61-11ea-92fa-050269575615.png)
But i got this error :/
![image](https://user-images.githubusercontent.com/7857364/72812288-88a17b80-3c61-11ea-996e-cc37f8b0df84.png)

**Comment by sarneeh** [comment]
@BobLamarley It's not about the hook, it's about using `strapi.*` properties outside of services/controllers/etc. This won't work. Strapi parses those files before initialization.

**your-service.js**
```
console.log(strapi.got); // won't work

module.exports = {
  yourFunc: () => {
    console.log(strapi.got); // will work
  } 
}
```
