### ISSUE TITLE
GraphQL policies don't seem to be executing

### ISSUE THREAD

**Issue by motorvor** [strapi/strapi#4528]
**Describe the bug**
Global policies do not seem to be executing when included in the schema.graphql file for a specific model

**Steps to reproduce the behavior**
1. Create a default installation of Strapi. Also install the GraphQL plugin.
2. Through the admin app, add a few entries for `Model` with a `name` property
2. Create a file under `/config/policies` called `testpolicy.js`
3. Inside that file, add: 
```
module.exports = async (ctx, next) => {
  console.log("Test Policy");
};
```
4. Go to `/api/model/config/routes.json` and add  `"policies": ["global.testpolicy"]` under the `GET` method for `/models`
5. Next create a file called `schema.graphql` under `/api/model/config` with the following code:
```
module.exports = {
  resolver: {
    Query: {
      models: {
        policies: ['global.testpolicy'],
      },
    }
  },
};
```
6. Run the development environment with `npm run develop`
7. In a browser, access the `/models` endpoint. A log with stating `Test Policy` should show up in the console of where you're running Strapi. This is correct and expected. 
8. Next try the equivalent in GraphQL by going to the `/graphql` endpoint and running a query like this:
```
query {
  models {
    name
  }
}
```
9. With the GraphQL query, the log does not appear in the console (where strapi is running, not web console) and instead of the query returning data, it returns:
```
{
  "data": {
    "models": null
  }
}
```
**Expected behavior**
I would expect the log `Test Policy` to show up in the console and the data to be returned by the `/models` endpoint, just like the REST API implementation

**System**
- Node.js version: **10.15.3**
- NPM version: **6.13.0**
- Strapi version: **3.0.0-beta.17.5**
- Database: **MongoDB**
- Operating system: **Windows 10**

**Comment by lauriejim** [comment]
Hello! It's maybe not clear, you are right...
You have to add the `resolver: 'Model.find'`
And then all will work fine.

I will update the docs to make it clearer.
Thank you for this feedback.

**Example for Restaurant model**

```
module.exports = {
  resolver: {
    Query: {
      restaurants: {
        policies: ['global.testpolicy'],
        resolver: 'Restaurant.find'
      },
    }
  },
};
```

**Comment by motorvor** [comment]
Ah okay! Thank you for that clarification!
