### ISSUE TITLE
SSL and Production issue

### ISSUE THREAD

**Issue by chrisformula** [strapi/strapi#4534]
**Describe the bug**
I have a server running SSL on DIgitalocean. When I put my Strapi in Production and use domain.com/admin I log in fine but as soon as I try to add content I just get an infinite load.

**Steps to reproduce the behavior**
1. I used this guide https://medium.com/@derrickmehaffy/using-strapi-in-production-with-https-717af82d1445 to the T. Also using MongoDB
2. Strapi Start to start dev env
3. Add Content via manage
4. Put Strapi in production using NODE_ENV=production pm2 start server.js --name api

**Expected behavior**
Login and create new content.

**System**
- Node.js version: v10.16.3
- NPM version:6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB shell version v3.6.3
- Operating system: Ubuntu 18.0.4

**Comment by derrickmehaffy** [comment]
Alpha is no longer supported. You should be using the beta, (also that's my guide ;) )

**Comment by chrisformula** [comment]
It is an awesome guide and very helpful! So the issue will be resolved if I use beta instead of alpha?

**Comment by derrickmehaffy** [comment]
Most likely yes, I haven't finished the 2nd part of the new guide (nginx related stuff) but that old one you linked should be fine for Nginx. The new guide for Beta is on my own blog: https://derrickmehaffy.com/strapi-nginx-mariadb-lets-encrypt-awesome-sauce-part-1/

**Comment by derrickmehaffy** [comment]
I'm going to go ahead and close this as alpha is no longer supported but please do free to ask any questions you need to here or you are welcome to join the [Strapi slack](https://slack.strapi.io)

**Comment by chrisformula** [comment]
Awesome thank you so much Derrick! Definitely subscribing to your blog and
once again thank you for the assistance.
