### ISSUE TITLE
Cannot create a Content Type named function

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#4539]
**Describe the bug**
If I try to name a content type "function," along with the AWS provider plugin, the build process will fail.

The error in the console is:
```
[2019-11-15T17:46:57.644Z] error Bootstrap function in plugin "upload" failed
[2019-11-15T17:46:57.645Z] error TypeError: this._reset is not a function
```
**Steps to reproduce the behavior**
1. Create an application with a MySQL DB
2. Install strapi-provider-upload-aws-s3
3. Create a content type named "function"
4. Application restart/build will fail.

**Expected behavior**
Obviously, the application should not fail.

**System**
- Node.js version: 10
- NPM version: 6.9
- Strapi version: Beta 17.5
- Database: MySQL 8
- Operating system: CentOS in Docker

**Comment by derrickmehaffy** [comment]
Uhhhh that is absolutely going to be a reserved word in JavaScript. I'd pick a different name

**Comment by amartincolby** [comment]
Picking a different name isn't so easy. It previously worked fine and we built up a system of relations around it. Further, the usage of "function" to describe job function within the org is widespread. Everyone knows what it means. And of course, what one can do in the UI shouldn't have to take into account the peculiarities of the implementation language.

**Comment by derrickmehaffy** [comment]
Not sure what else to tell you: https://mathiasbynens.be/notes/javascript-identifiers

```
The spec describes four groups of reserved words: keywords, future reserved words, null literals and boolean literals.

Keywords are tokens that have special meaning in JavaScript: break, case, catch, continue, debugger, default, delete, do, else, finally, for, function, if, in, instanceof, new, return, switch, this, throw, try, typeof, var, void, while, and with.

Future reserved words are tokens that may become keywords in a future revision of ECMAScript: class, const, enum, export, extends, import, and super. Some future reserved words only apply in strict mode: implements, interface, let, package, private, protected, public, static, and yield.

The null literal is, simply, null.

There are two boolean literals: true and false.

None of the above are allowed as variable names.
```

Model names are variables, as they are used by the internal API.

**Comment by derrickmehaffy** [comment]
I'd suggest `jobfunction`, `jobFunction`, `job-function`, or `job_funcation` any of those would be fine and still describe what it is.

**Comment by amartincolby** [comment]
We're thinking about that, but again, that is not a small change for us. And as I want to stress, it previously worked fine.

**Comment by soupette** [comment]
Currently it is impossible to create a `singleType` or a `collectionType` using the administration panel. However, we still need to validate the name when we create them using the command line or when creating the api manually. So let's leave it open until we **"validate the schema"** when the application starts.

**Comment by lauriejim** [comment]
Hello! This issue has been fixed in the stable version of Strapi.
