### ISSUE TITLE
sendgrid plugin can't send email 500 + CORS error

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [strapi/strapi#4542]
**Describe the bug**
I'm not sure how to work with this so I am trying to follow the online tutorial or whatever I can find. According to a [SO post](https://stackoverflow.com/questions/58816656/sending-emails-with-sendgrid-and-a-custom-controller-for-strapi), controller doesn't seem to be needed any more. So I think I would just add send, reply to email and sendgrid api key in admin UI, then write something in the front-end. 

in front-end console:
I am getting POST http://localhost:1337/email 500 (Internal Server Error) checkout:1 Access to XMLHttpRequest at 'http://localhost:1337/email' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

strapi server in node:
error undefined

AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object at Function.boomify (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/boom/lib/index.js:107:14) at /home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi/lib/middlewares/boom/index.js:80:22 at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:25189) UnhandledPromiseRejectionWarning: Error: Provide at least one of to, cc or bcc at Mail.addTo (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/@sendgrid/helpers/classes/mail.js:278:13) at Mail.fromData (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/@sendgrid/helpers/classes/mail.js:114:12) at new Mail (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/@sendgrid/helpers/classes/mail.js:44:12) at Function.create (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/@sendgrid/helpers/classes/mail.js:627:12) at MailService.send (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/@sendgrid/mail/src/classes/mail-service.js:174:25) at /home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-provider-email-sendgrid/lib/index.js:54:20 at new Promise () at Object.send (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-provider-email-sendgrid/lib/index.js:35:16) at Object.send (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-plugin-email/services/Email.js:70:20) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async Object.send (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-plugin-email/controllers/Email.js:41:5) at async /home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:67:22 at async module.exports (/home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:111:3) at async /home/annie/Desktop/annies-vegan-bakery/server/node_modules/strapi/node_modules/strapi-utils/lib/policy.js:111:7 at async evalmachine.:59:11 (node:25189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

Does this mean the "to" email entered in the front end is somehow not sent back?

**Expected behavior**
I expected to get email sent by sendgrid from my setting after stripe charge. 

**Code snippets**
```
const headers = {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer '+ jwtToken
              }
            
            await axios
            .post(`${apiUrl}/email`, {
                data: {
                    to: confirmEmail,
                    from: 'hi@anniesveganbakery.com',
                    subject: `Order Confirmation from Annie's Vegan Bakery`,
                    text: 'Your order has been processed.',
                    html: '<h1>Expect your order to arrive in 2-3 shipping days.</h1>'

                }
            })
```

[CODE](https://github.com/AnnieTaylorCHEN/annies-vegan-bakery/blob/master/src/components/Checkout.js) related to problem 
go to line 92 -102

**System**

- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.4
- Database: MongoDB atlas cloud
- Operating system: LinuxMint 19.2 Cinnamon
- Front-end : React 16.11.0
- strapi-provider-email-sendgrid": "^3.0.0-beta.17.5"

**Additional context**
I tried adding headers and deleting headers, but problem remains.

**Comment by AnnieTaylorCHEN** [comment]
Hi, I figured out the problem:
with new strapi, we don't need to send data in encapsulated form. So we should write:
```
await axios
            .post(`${apiUrl}/email`, {
                    to: confirmEmail,
                    from: 'hi@anniesveganbakery.com',
                    subject: `Order Confirmation from Annie's Vegan Bakery`,
                    text: 'Your order has been processed.',
                    html: '<h1>Expect your order to arrive in 2-3 shipping days.</h1>'
                }
            ,{headers})
```
Nothing is written in controller.

**Comment by Ermal45** [comment]
I still have an error, after i register, it sends the email first time, if i do it again it will show the same error its very weird.
