### ISSUE TITLE
GraphQL - "Aggregation & Grouping" does not work with the "where" parameter

### ISSUE THREAD

**Issue by ejzambra** [strapi/strapi#4543]
I don't know if I'm correct, but I want to get the sum of the chosen fields and group the products from a list in a date range.

Query
```
query{
  inventoriesConnection(where:{
    date_gt:"2019-11-10T00:00:00.000Z"
  }){
    aggregate{
      sum{
        inputProduct
        outputProduct
      }
    }
    groupBy{
      product{
      	key
      }
    }
  }
}
```
Result
```
{
  "data": {
    "inventoriesConnection": {
      "aggregate": {
        "sum": {
          "inputProduct": null,
          "outputProduct": null
        }
      },
      "groupBy": {
        "product": []
      }
    }
  }
}
```
If I repeat the query without the "where" parameter, it does give me results.

Query
```
query{
  inventoriesConnection{
    aggregate{
      sum{
        inputProduct
        outputProduct
      }
    }
    groupBy{
      product{
      	key
      }
    }
  }
}
```
Results
```
{
  "data": {
    "inventoriesConnection": {
      "aggregate": {
        "sum": {
          "inputProduct": 3100,
          "outputProduct": 310
        }
      },
      "groupBy": {
        "product": [
          {
            "key": "5dc88996c321e573759f32ae"
          },
          {
            "key": "5dc889aac321e573759f32af"
          }
        ]
      }
    }
  }
}
```
![Captura realizada el 2019-11-17 22 28 24](https://user-images.githubusercontent.com/3055638/69022631-e11a7b00-0989-11ea-89ca-b838d4fce7f3.jpeg)

**System**
- Node.js version: v10.17.0
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.5
- Database: mongo (docker image mongo:latest)
- Operating system: Ubuntu 16.04.5 LTS | elementary OS 0.4.1 Loki | Linux 4.4.0-166-generic

**UPDATE**
I performed the same test but from its docker container and still giving the same result

**System**
- Strapi: docker image strapi/strapi:alpine
- Database: mongo (docker image mongo:latest)

![Captura realizada el 2019-11-19 23 08 22](https://user-images.githubusercontent.com/3055638/69208805-fa0a6400-0b22-11ea-85fb-a97f43617e94.jpeg)
![Captura realizada el 2019-11-19 23 14 10](https://user-images.githubusercontent.com/3055638/69208807-faa2fa80-0b22-11ea-8289-8701f8fbaffd.jpeg)

**Comment by ejzambra** [comment]
UPDATE:
I performed the same test but from its docker container and still giving the same result

**System**

- Strapi: docker image strapi/strapi:alpine
- Database: mongo (docker image mongo:latest)

![Captura realizada el 2019-11-19 23 08 22](https://user-images.githubusercontent.com/3055638/69208599-2a9dce00-0b22-11ea-95f0-70ed36a1fb5a.jpeg)
![Captura realizada el 2019-11-19 23 14 10](https://user-images.githubusercontent.com/3055638/69208641-5456f500-0b22-11ea-8090-634900db6bd8.jpeg)

**Comment by lauriejim** [comment]
Can you test to use a `where` with something else than a date please and tell me if it still not work.
Can you also please send me your date models.
It will help me to reproduce.

**Comment by petersg83** [comment]
I reproduced the issue with `3.0.0-beta.17.5` but I couldn't reproduce it with `3.0.0-beta.20.1`.
