### ISSUE TITLE
"Configuration" Tab in left navigation is not shown

### ISSUE THREAD

**Issue by manoharramarao** [strapi/strapi#4546]
Configuration tab after Marketplace tab in the left navigation is not visible after logging in as admin user. This was available in the previous version 16.X.X where we could configure different DBs.

![image](https://user-images.githubusercontent.com/2945080/69036623-4911a580-0a0c-11ea-93cc-6d094e68dee6.png)

**Comment by derrickmehaffy** [comment]
This is intended as the `Settings-Manager` plugin has been depreciated, you can configure all the settings within the files. 

This was depreciated as of beta.17.4: https://github.com/strapi/strapi/releases/tag/v3.0.0-beta.17.4

From this PR: https://github.com/strapi/strapi/pull/4122

```
[Plugin] Remove strapi-plugin-settings-manager (#4122) @soupette @virginieky
```
