### ISSUE TITLE
Enable findOne by unique fields GraphQL

### ISSUE THREAD

**Issue by nicecatch** [strapi/strapi#4547]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

About the GraphQL plugin:

If a model has a unique field defined in it, we should be able to filter for that field.
In this moment only IDs can be used for filtering

Example:
model Article with title, content and slug. Slug is required and unique
I would like to run this query

`
query {
  article(slug: "my-awesome-article") {
    title
    id
    content
  }
}
`

**Comment by lauriejim** [comment]
Thank you for this feedback!

**Comment by abdonrd** [comment]
I'm also interested on this!

**Comment by alexandrebodin** [comment]
Hi @nicecatch great suggestion. You can achieve that by overridding the query and the action to handle it quickly on your own :)

**Comment by abdonrd** [comment]
@lauriejim Maybe is a good example for another guide?

**Comment by abdonrd** [comment]
> Hi @nicecatch great suggestion. You can achieve that by overridding the query and the action to handle it quickly on your own :)

Where I can override the query? Thanks!

**Comment by abdonrd** [comment]
> Hi @nicecatch great suggestion. You can achieve that by overridding the query and the action to handle it quickly on your own :)

@alexandrebodin Where I can override the query? Thanks!

**Comment by alexandrebodin** [comment]
@abdonrd You can override your graphql creating a `schema.graphql.js` file in the `./api/{api}/config` folder

This would look something like that:

```js
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  query: `
    articleBySlug(id: ID slug: String): Address
  `,
  resolver: {
    Query: {
      articleBySlug: {
        resolverOf: 'Article.findOne',
        resolver(_, args) {
          const entity = strapi.services.article.findOne(args);
          return sanitizeEntity(entity, { model: strapi.models.article });
        },
      },
    },
  },
};

```

**Comment by abdonrd** [comment]
I just created the `api/competition/config/schema.graphql.js` file with:

```javascript
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  query: `
    competitionBySlug(id: ID slug: String): Competition
  `,
  resolver: {
    Query: {
      competitionBySlug: {
        resolverOf: 'Competition.findOne',
        resolver(_, args) {
          const entity = strapi.services.competition.findOne(args);
          return sanitizeEntity(entity, { model: strapi.models.competition });
        }
      }
    }
  }
};
```

But if I tried the query:

```graphql
{
  competitionBySlug(slug: "fms") {
    id
    name
  }
}
```

I get this error:

`"message": "Cannot return null for non-nullable field Competition.id."`

**Comment by alexandrebodin** [comment]
Here is a working example. You need to await your service call and only pass the right params

```js
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  query: `
    articleBySlug(id: ID name: String): Article
  `,
  resolver: {
    Query: {
      articleBySlug: {
        resolverOf: 'Article.findOne',
        async resolver(_, { slug }) {
          const entity = await strapi.services.article.findOne({ slug });
          return sanitizeEntity(entity, { model: strapi.models.article });
        },
      },
    },
  },
};

```

**Comment by abdonrd** [comment]
Thanks @alexandrebodin! It works now! 👏 

And how would it be with a plugin?
I've tried this, but it doesn't work for me.

```javascript
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  query: `
    userByUsername(username: String): UsersPermissionsUser
  `,
  resolver: {
    Query: {
      userByUsername: {
        resolverOf: 'User.findOne',
        async resolver(_, { username }) {
          const entity = await strapi.plugins['users-permissions'].services.user.findOne({ username });
          return sanitizeEntity(entity, { model: strapi.plugins['users-permissions'].models.user });
        },
      },
    },
  },
};
```

**Comment by abdonrd** [comment]
@alexandrebodin it works with:

```javascript
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  query: `
    userByUsername(username: String): UsersPermissionsUser
  `,
  resolver: {
    Query: {
      userByUsername: {
        plugin: 'users-permissions',
        resolverOf: 'User.findOne',
        async resolver(_, { username }) {
          const entity = await strapi.plugins['users-permissions'].services.user.fetch({ username });
          return sanitizeEntity(entity, { model: strapi.plugins['users-permissions'].models.user });
        },
      },
    },
  },
};
```

It's the right way?

**Comment by derrickmehaffy** [comment]
This can be done via customization, marking as closed. 

We have filters that would work just as easily also.
