### ISSUE TITLE
Create nightly builds

### ISSUE THREAD

**Issue by n8tb1t** [strapi/strapi#4549]
Can you please generate modules packages each time the merge to master is done, so people will be able to use the fixes right away without waiting to the next beta release, you can look how it's done in GatsbyJS project.

**Comment by derrickmehaffy** [comment]
Normally I would close this for not having a template but I think this is a great idea.

**Comment by derrickmehaffy** [comment]
@lauriejim @alexandrebodin

**Comment by alexandrebodin** [comment]
Hi, 

We already plan on setting this up. This will be put in place once we release the stable version to avoid creating more issues that we already have between the beta and next tags.

**Comment by lauriejim** [comment]
Hello @n8tb1t !
Thank you for this feedback, really interesting!
