### ISSUE TITLE
Unable to change upload limit strapi-plugin-upload

### ISSUE THREAD

**Issue by tommyboylab** [strapi/strapi#4553]
**Describe the bug**
I am unable to upload files larger than 10kb to Strapi though strapi-plugin upload. 

Trying to change the settings on the server through the plugin settings doesn't work.

Changing the 'Roles and Permissions' for both authenticated / public users and trying to change the settings doesn't work

Creating a user in the DB using the same credentials as the Strapi Administrator and trying to change the settings as an authenticated user doesn't work.

**Steps to reproduce the behaviour**
1. Go to Plugins
2. Click on Files Upload Settings
3. Change the value of upload limit to any number you wish
4. Save
5. View output in the terminal

**Expected behaviour**
I should be able to change the upload limit of the DB, given I am in development mode, and am in the administrator portal.

**Screenshots**
N/A
**Code snippets**
```[2019-11-19T17:46:34.067Z] debug GET /admin/plugins (4 ms) 200
[2019-11-19T17:46:35.880Z] debug GET /upload/environments (20 ms) 200
[2019-11-19T17:46:35.881Z] debug GET /upload/settings/development (25 ms) 200
[2019-11-19T17:46:47.837Z] debug PUT /upload/settings/development (10 ms) 200
[2019-11-19T17:46:48.062Z] debug GET /upload/files?_limit=10&_sort=hash%3AASC&_start=0 (8 ms) 200
```

**System**
- Node.js version: LTS V12
- NPM version: 6.12.1
- Strapi version: v3 17.5
- Database: SQLite
- Operating system: Ubuntu LTS 18.04

**Additional context**
I am able to upload files smaller than 10kb, but anything bigger fails (3.2mb img for example)

**Comment by jsonpj3wt** [comment]
Similar to https://github.com/strapi/strapi/issues/4156?

**Comment by tommyboylab** [comment]
Solved by adjusting file upload limit of NGINX. Closing this ticket.

**Comment by drewmarshburn** [comment]
+1 on this. As an additional note for detection, take a look at the upload network request:

- NGINX will provide a 413: Request Entity Too Large. Looks like it has a 1 mb default limit.
- Strapi upload limits return a 500. You can see in the console logs for the request `Error: maxFileSize exceeded`
