### ISSUE TITLE
Creating Content Type "Number" Crashes Server

### ISSUE THREAD

**Issue by stylustscott** [strapi/strapi#4554]
**Describe the bug**
Creating a content type called "Number" overwrites the JavaScript Number global class causing server to crash with "TypeError: Number.isSafeInteger is not a function".

**Steps to reproduce the behavior**
1. Create a new installation (I'm using PostgreSQL, but I'm not sure if this is relevant to the issue).
2. Create your Admin account
3. Create a new Content Type called "Number"
4. Save it

**Expected behavior**
Content type names should either prohibit safe words like Number or Object -- or they should not overwrite the default JavaScript global classes.

**Screenshots**
```
$ npm run develop

> personal-strapi@0.1.0 develop /home/xxxxxxxx/strapi-application
> strapi develop

internal/async_hooks.js:118
  if (!Number.isSafeInteger(asyncId) || asyncId < -1) {
              ^

TypeError: Number.isSafeInteger is not a function
    at validateAsyncId (internal/async_hooks.js:118:15)
    at emitBeforeScript (internal/async_hooks.js:349:3)
    at processTicksAndRejections (internal/process/task_queues.js:70:7)
```

**System**
- Node.js versions: v10.17.0 and v12.13.1
- NPM version: v6.11.3 and v6.12.1
- Strapi version: 3.0.0-beta.17.5
- Database: PostgreSQL 11 (GCP)
- Operating system: Ubuntu 19.04 (disco) - Pop!_OS 19.04

**Comment by lauriejim** [comment]
Thank for this feedback!

Can you please create a PR to add this list of prohibited words.
I will appreciate your contribution to this topic.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

You will have to investigate in the `content-type-builder` plugin.

Thank you.

**Comment by batraman** [comment]
Hi!
I was reading the source code and this looks like a `good-first-issue` so I added a PR for it. 
Hope that's alright.

Cheers!
