### ISSUE TITLE
Strapi stores any Date with the Previous Date

### ISSUE THREAD

**Issue by donwilly2010** [strapi/strapi#4555]
**Describe the bug**
Strapi is a very good framework so far in our development environment. however, we noticed an issue: it seems Strapi stores date in database using the previous date. This means all the dates are one day behind the actual date captured

**Steps to reproduce the behavior**
1. Create any Content Type
2. Add a date type field
3. Save the Content Type
4. Add a new date entry into the content type
5) got MongoDB and check the data and see the date is stored as one day behind

**Expected behavior**
The exact same day inputed should be stored in database

**System**
- Node.js version: v10.16
- NPM version: 
- Strapi version: 3.0.0-beta.15
- Database: MongoDB v4.2.0
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@donwilly2010 please actually specify the versions:

```
Node.js version: latest version
NPM version: latest version
Strapi version: latest version
Database: MongoDB
Operating system: Windows 10
```

"latest version" doesn't help us reproduce the issue.

**Comment by derrickmehaffy** [comment]
Side note, the date data comes from your OS, so you should probably verify your OS has the proper date.

**Comment by donwilly2010** [comment]
Hi,

thanks for your feedback. the date on my OS is absolutely correct. And I was talking about entering the date into a strapi date field. I expect that the inputed date be stored. inputed dates comprising of past date or future date cannot be loaded from pc current date.

**Comment by lauriejim** [comment]
So can you please update 

```
Node.js version: latest version
NPM version: latest version
Strapi version: latest version
Database: MongoDB
Operating system: Windows 10
```

with exact version please.

**Comment by donwilly2010** [comment]
Hi,

The Node version is 10.16
Strapi version is 3.15-beta
Mongo DB is version 4.2.0

The were the latest versions of the above few months ago when i downloaded them.

**Comment by derrickmehaffy** [comment]
And that's why we ask for specific versions because they aren't the latest :stuck_out_tongue:

**Comment by lauriejim** [comment]
Never see this version of strapi `3.15-beta`

**Comment by donwilly2010** [comment]
Also on our application, new Date() was used to capture current date, but by the time we checked the MongoDB, the previous day was stored.
I have actually seen a previous issue report on date issues on strapi and I was thinking  it has been resolved.. Please note that the date on my system is very correct.

**Comment by donwilly2010** [comment]
@lauriejim  everybody knows I am talking about the strapi version is 3.0.0-beta.15. 

Meanwhile, this issue occurs mainly when the date is created at the front end and POSTED to Strapi via API call

**Comment by donwilly2010** [comment]
please what exactly can I do to resolve this issue?? Is there any other person that has this issue.
I am also using strapi-sdk-javascript at my front end app. I really need to be sure that the issue is the strapi version before i start getting a new version. 
Since i have listed all the systems I am using in our own environment, is the issue caused by any of the systems in my own environment??

**Comment by derrickmehaffy** [comment]
Three things to note:
1) The `strapi-sdk-javascript` isn't currently maintained (says so on the repo): https://github.com/strapi/strapi-sdk-javascript/blob/master/README.md
2) By using Strapi versions below beta.17.5 you are opening yourself up to a critical security risk that could have very damaging effects on your project especially if you open your outdated strapi instance on the internet
3) We will need to reproduce this on the current latest stable version to confirm the issue (which I plan on looking at today)

As a foot note to that, **every** bug report is only "confirmed" if it can be reproduced on the latest stable version, any older versions are not even tested or looked at.

**Comment by donwilly2010** [comment]
thanks so much for your feedback. please i wish to confirm that this issue also occurs when a new date is entered unto a date filed directly on strapi admin so it really not a strapi jdk issue.
kindly confirm the issue today and give me a feedback. thank you so much for the assistance. you guys are great!!

**Comment by donwilly2010** [comment]
Hahahahahaha.. and you say you dont work with Strapi.. But you are promoting Strapi aggressively in most of the threads in this forum and also closing issue posts.. nice work though.. I am still waiting for your feedback on my other posts.

**Comment by derrickmehaffy** [comment]
Could not reproduce this on beta.17.5

Created 3 entries:
- One for today no time
- One for tomorrow
- One for today with 03:33:33 set as time.

![image](https://user-images.githubusercontent.com/8593673/69343215-658b2900-0c2a-11ea-8c37-6b797588218a.png)

**Comment by donwilly2010** [comment]
Please which OS and Database did you use for the above??

**Comment by derrickmehaffy** [comment]
per @donwilly2010 on slack: 
![image](https://user-images.githubusercontent.com/8593673/69920246-b4169f80-1442-11ea-81a3-9cf595f8d2c3.png)

Marking this as closed as it could not be reproduced.
