### ISSUE TITLE
Querying a relationships group fields returns null in GraphQL

### ISSUE THREAD

**Issue by DanWebb** [strapi/strapi#4556]
**Describe the bug**
Using graphql, when querying a relationship + a group field inside the relationship the group field returns null.

For example...

```
query group_fields_in_relationship {
  parent(where: { some_prop: "some_value" }) {
    id
    related_content_type {
      group_field {
        title
      }
    }
  }
}
```

`parent.related_content_type.group_field` will be `null`

But, if I query the `related_content_type` directly the `group_field` returns correctly.

**Steps to reproduce the behavior**
1. Create a group field and add it to a content type
2. Relate the content type with a group field in it to another content type
3. Try to query the group field through the content type relationship
4. See the group fielod in the query return `null`

**Expected behavior**
The group field to return what it contains

**System**
- Node.js version: 12.6.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: postgres
- Operating system: macOS mojave

**Comment by lauriejim** [comment]
Hello @DanWebb !

Thank you for this report! I can confirm this issue.
We will do our best.

**Comment by lynnReilaender** [comment]
Comment on that, since I think it's related: Also the JSON response via REST API does not contain group based fields or the group reference itself within the relationships.

(And: Groups are really a cool feature.)

**Comment by gavinwilliams** [comment]
Would be good to get an ETA on this or whether anyone is working on it. It's a bit of a blocker.

**Comment by lauriejim** [comment]
If you are using the REST API - here is a workaround.
[Custom populate relations](https://spectrum.chat/strapi/general/group-doesnt-appear-on-findall-with-relations~c0bcc957-3170-4e80-96de-ee3e7625b5bf)
