### ISSUE TITLE
Forgot password email is case sensitive

### ISSUE THREAD

**Issue by 1um** [strapi/strapi#4559]
**Describe the bug**
In Auth module `register` lowercasing email, but `forgotPassword` is not.

**Steps to reproduce the behavior**
1. Register as user@email.com
2. Send forgot password for User@email.com
3. Get an error `Auth.form.error.user.not-exist`

**Expected behavior**
Email should be send to user@email.com

**Code snippets**
https://github.com/strapi/strapi/blob/1162698778aa721522081f4f4e70ecb30521f83e/packages/strapi-plugin-users-permissions/controllers/Auth.js#L274-L286

**System**
- Strapi version: 3.0.0-beta.11

**Comment by lauriejim** [comment]
Hello @1um !

Thank you for reporting this issue.
