### ISSUE TITLE
Strapi fail to create relations between custom content type and users

### ISSUE THREAD

**Issue by storm1er** [strapi/strapi#456]
**Node.js version**: 8.9.4
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.7.3
**Operating system**: Ubuntu 17.10 x64

----

Hi everyone,

I don't know if it's related to #401 but everytime I create a relation between some custom content type and users it fails : 

* Remove browser cache & cookie
* Drop strapi database from mongo
* `strapi new my-awesome-app && cd my-awesome-app && strapi start`
* Going to strapi/admin & create account
* Create a content type
* In this content type create a field relation as `User has many [your field]`
* Save
* Go to user content type :white_check_mark: 
* Go to your custom content type :red_circle: Error's appear

Any idea ?

I have to go, I'll complete this issue with console log and more if needed.

**Comment by storm1er** [comment]
## Chrome console log : 

![image](https://user-images.githubusercontent.com/9821946/35042608-ac24183a-fb89-11e7-89c4-cd1b440cd259.png)

With strapi@alpha
* The server restarted multiple times while saving the new content type (causing `_health ERR_CONNECTION_REFUSED`).
* The last request to `/content-type-builder/models/test?` was the request to see the content type `test` model which display "error happen" popup.

----

I'm trying with the actual repo...

**Comment by storm1er** [comment]
News : creating the project with `strapi new [project-name] --dev` make the error disappear. The cms is working well in dev mode.

**Comment by lauriejim** [comment]
Hi @storm1er.

Can you try to do same actions (without dev mode), but after you test model creation, wait the server restart. It has to restart 2 times (it's actually normale). And tell me if the problem is persistent.

We are working on a "waiting" loader after you make actions which need a server restart to avoid you to have this issue.

**Comment by storm1er** [comment]
# What I've done : 

## Checkout tag `v3.0.0-alpha.8`
* `npm run setup`
* Check `strapi -v`
* Remove & clean : mongo & cookie
* `strapi new my-awesome-app && cd my-awesome-app && strapi start`
* Connect, create account, create new content type
* Create relation field, save, wait 2 server restart
* Try to look at the new content type model : :white_check_mark: 

## Checkout tag `v3.0.0-alpha.7.3`
_The version with which I had the problem first._
* `npm run setup`
* Check `strapi -v`
* Remove & clean : mongo & cookie
* `strapi new my-awesome-app && cd my-awesome-app && strapi start`
* Connect, create account, create new content type
* Create relation field, save, wait 2 server restart
* Try to look at the new content type model : :white_check_mark: 

----

Well it seems that I was just too fast for strapi ^^'
Resolved ^^
