### ISSUE TITLE
Secured User Creation for Restricted Permissions

### ISSUE THREAD

**Issue by donwilly2010** [strapi/strapi#4560]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Strapi is now a very good product. But I noticed something that makes Strapi less secured than it should be. Right now we have built a  front end app that connects to our Strapi backend. This front end app registers new users and is also used to login new users. However we noticed that any other third party front end app that knows the IP and port of our Strapi backend can also register new users and also Login new users to our Strapi backend. 

 Hence, There is need for every Strapi instance that is downloaded and installed to generate a unique ownersKey. this Key will be included at the API call header (alongside email and password) when a new user is created. This will ensure that the API call for creating user that will have restricted access actually only comes from our own front end apps.

**Comment by derrickmehaffy** [comment]
@donwilly2010 This shouldn't be too difficult to implement, if you are willing to submit a PR it would be a nice add (although this should be an entirely optional addition.)

**Comment by donwilly2010** [comment]
please what do you mean by submitting a "PR"?? I have already sent a Feature Request on the strapi road map portal

**Comment by derrickmehaffy** [comment]
PR = Pull Request, meaning you create this code and submit the code to be added into the project. Strapi is open source meaning anyone can submit pull requests to be merged in.

**Comment by donwilly2010** [comment]
I see. In my company, I have mainly senior mobile developers and senior front end developers, hence we do not have the capacity to create such addition to strapi.
However, I know there are many in this forum who can create the code addition and submit to strapi. We really hope this feature is added soon as its very critical and makes strapi deployments very vulnerable to attacks

**Comment by derrickmehaffy** [comment]
It most likely won't be something that Strapi puts a priority on themselves, they are quite booked up for the next few months working on other features. (the vulnerability of this issue isn't quite that critical, CORS and most of the other security methods in place do a pretty good job at handling most security issues, and limiting login and registering to a specific frontend via this method isn't going to stop anyone major from ripping the key out of your frontend and using it).

If the security key you are mentioning is stored on the frontend, and that frontend is sent to the user, all I would need to do is capture the network packets and check the headers to grab the key and send it myself.

**Comment by donwilly2010** [comment]
thanks for the feedback. since you fully understand what i am trying to achieve. can you please suggest any set of existing features in strapi that can help me to ensure that third parties cannot create users and then login users to my backend

**Comment by derrickmehaffy** [comment]
To be frank there isn't a lot that can be done to prevent that. Many of the methods can be spoofed if someone really wanted to do this. Other than tracking who would be doing that and implementing varying levels of blocking (IP, or entire blocks of IP Addresses).

CORs can help if they are trying to do this over their own frontend (Googling around for more information on how CORs works might be a good idea here). But if we are strictly talking about the REST API routes the alternatives are really limited down to 3 ways:
1) Whitelists
2) Blacklists
3) Locking your endpoints out of the internet (Server Side frontend that is the only way to connect to Strapi endpoints and not putting them on the web).

As a footnote to the above, I don't see where a 3rd party using the register and login routes as a security risk. All they are doing is making accounts and using them. For instance I can directly call Google APIs (or facebook, or github) to register an account with them and even login with it. There isn't much room for abuse here unless your goal to prevent bot accounts which is an entirely different topic altogether.

**Comment by derrickmehaffy** [comment]
Your suggestion here is what those of us in the network field call "security through obscurity" and while it can help prevent some automated systems, it will not prevent humans.

**Comment by donwilly2010** [comment]
Hi. please do not downplay the importance of my request. We are are team of senior developers and business partners with so many products in production so we are telling you what is good for Strapi in order for developers to use Strapi to build any platform that can be used for online purchase or card payment.
All platforms used for online payment has this same concept and its called secretKey.

The essence of security features is to make an attack more difficult. There is never a fail proof system.

**Comment by derrickmehaffy** [comment]
I don't work for Strapi, just giving my thoughts. CORs in your case locking to specific domain would prevent the requests (given someone isn't using a DNS hijacking request. All I'm saying is sending a key in a header won't help you secure when that key can just be spoofed.

**Comment by derrickmehaffy** [comment]
Now if you are using a server side frontend in which the user isn't passing that header and instead the server side frontend is talking to Strapi than yes it would be far more secure.

**Comment by derrickmehaffy** [comment]
If you want more information on CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS would be a good read.

**Comment by donwilly2010** [comment]
Some people are using Strapi as backend for Mobile Apps. So the front end in this case is a Mobile App

**Comment by derrickmehaffy** [comment]
Then even with SSL I can sniff the request traffic and extract the token out of the headers and use that to send the request from anywhere (without a frontend) using your suggested method. The same applies for any header being sent.

For example Strapi uses the `authorization` header to pass the JWT. 

example: 
![image](https://user-images.githubusercontent.com/8593673/69335501-556b4d80-0c1a-11ea-9886-11586f05f96d.png)

If the same applies where the "frontend" in your case the mobile app is sending a header with a predefined secret key, all I would need to do is grab this header and fire the request from something like Postman.

Trust me I'm not trying to downplay your request, but what I am saying is if you want more security careful planning needs to happen. I've been a systems and network engineer for the past 5 years, testing security of applications is what I do for a hobby.

**Comment by donwilly2010** [comment]
You still miss the point. Most systems used for attack are automated systems or scripts. the human systems are a far minority.  these automated sripts and bots is what everybody wants to avoid.
secondly, not everybody uses http API requests with headers.. there other approach to API calls.

**Comment by derrickmehaffy** [comment]
Agreed there is, but I don't agree with minority of human systems, someone has to write those systems. Even us just discussing this issue is putting it out in the open, especially if documentation would have to be written for it.

You can add this type of feature yourself into your project if you wanted without it needed to be merged into the core monorepo. (In fact quite a few users do add their own security methods into Strapi which I've had the pleasure of seeing and testing)

**Comment by donwilly2010** [comment]
Hi. I think we are on same page. we will look for ways to enhance our own security.
Meanwhile for security reasons, i think its best you delete the post you made above that shows how to get Strapi jet code from headers. Secondly, since you have been testing Strapi systems, what has been the performance of Strapi when serving a backend with up to 2 million registered users running on MongoDB/Linux. What kind of server spec is required for this kind of deployment??

**Comment by derrickmehaffy** [comment]
@donwilly2010 my post related to authorization headers is not secret (nor should it be) I am a firm believer in open source software and open source information (I attend defcon every year I can)

As for discussion about the performance of Strapi I don't think this issue is the best place for it. I'd recommend you jump on the Strapi slack for discussions like that https://slack.strapi.io

**Comment by donwilly2010** [comment]
Hahahahahaha.. and you say you dont work with Strapi.. But you are promoting Strapi aggressively in most of the threads in this forum and also closing issue posts.. nice work though.. I am still waiting for your feedback on my other posts.

**Comment by derrickmehaffy** [comment]
Just another user like you helping out the Strapi team as a contributor. It's common here on github for someone who doesn't work for a company to contribute back to a project. I assist the Strapi team with intercepting github issues to try and provide a base level response until they can get the chance to look at it. (as for your other issue it's on my to-do list but that is a long list)

**Comment by donwilly2010** [comment]
I still believe you can give me a little insight here regarding Strapi Performance and Server Requirements..  or at least give me a direct link where I can read about it.. rather than just sending me the strapi slack link

**Comment by donwilly2010** [comment]
Please can someone help with the details of how to configure Strapi CORS to only accept API calls from a specific domain with SSL from a front end application that has both Web and Mobile.

**Comment by lauriejim** [comment]
Hello! Strapi is using lusca to manage cors - https://www.npmjs.com/package/lusca
You can configure it in `./configuration/environments/development/security.json`

**Comment by donwilly2010** [comment]
Hi. Thanks for your feedback. Please can you provide details of a sample configuration that allows a specific domain with SSL. We are looking for how to restrict API calls to Strapi to be only from our Web and Mobile App.

**Comment by lauriejim** [comment]
I will check, but I suggest you to implement an API gateway on front off your app to manage it.

**Comment by donwilly2010** [comment]
Thanks for your suggestion. Please can you also provide a link that provides details of how to implement an API gateway on a Strapi Server.

**Comment by derrickmehaffy** [comment]
I'm going to mark this as closed as we have gone quite a bit off the feature request path, do feel free to continue discussion.
