### ISSUE TITLE
api upload user avatar error

### ISSUE THREAD

**Issue by LightningVII** [strapi/strapi#4564]
**Describe the bug**
I add User Content a "Avatar" field, media type,
use /upload api ,  error!
![image](https://user-images.githubusercontent.com/13807519/69330529-0d860e00-0c8e-11ea-9129-889c719ec9f2.png)

but I upload Article Content, "background" filed, success

help me

**Steps to reproduce the behavior**
1. default User Content add type "Avatar" field, type is media,
2. request /upload api

**Expected behavior**
reponse 500 

**Screenshots**
![image](https://user-images.githubusercontent.com/13807519/69330529-0d860e00-0c8e-11ea-9129-889c719ec9f2.png)

**System**
- Node.js version: v10.17.0
- NPM version:6.13.0
- Strapi version: 3.0.0-beta.17.5
- Database:mongoDB
- Operating system:macOS

**Additional context**
Create "Articles" Content, add "background" field, type is media,
request /upload api, success!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello @LightningVII !
I just tested it and it works well. 
In your first test you missed the `source` attribute.
Because the user model in in the `users-permissions` plugin you have to mention the source.
Here is the related documentation: https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters

**Comment by LightningVII** [comment]
> Hello @LightningVII !
> I just tested it and it works well.
> In your first test you missed the `source` attribute.
> Because the user model is in the `users-permissions` plugin you have to mention the source.
> Here is the related documentation: https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters

I see, I tried again and it worked, thx @lauriejim
