### ISSUE TITLE
Misleading documentation (concepts/configurations/database)

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#4567]
**Describe the bug**
In the database configuration documentation, the docs state, that database connection `options`should be placed as a child of `connections` (not a specific connection, i.e. `default`):
![image](https://user-images.githubusercontent.com/11553624/69345444-6dba8700-0c71-11ea-8998-1936991ef647.png)

Which results in a: `TypeError: Cannot read property 'replace' of undefined`, because Strapi treats `options` as another connection.

**Comment by derrickmehaffy** [comment]
@sarneeh good catch, can you make a PR to fix that?

**Comment by sarneeh** [comment]
@derrickmehaffy Sure, give me a sec 😄
