### ISSUE TITLE
Different Backend URL for uploads (Fetching Images via different domain name)

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4574]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
"Open in New Tab" option in Strapi Admin shows the Image URL Path as "https://domainname/uploads/image.jpg"

We need to have different domainname for downloading images. (ie )Can we have this domain name different from (strapi.BackendURL) 

**Your suggestions for this topic**
In Configuration we can have ImageDownloadURL as key similar to backend
    
"build": {
      "host": "http://domainname/app", 
      "backend": "http://domainname/api",
     "ImageDownloadURL" :"http://imagedomainname"
 }

**Screenshots**
![tab](https://user-images.githubusercontent.com/2913281/69424360-6c12c100-0d4e-11ea-965e-062d595af77c.png)

**Code snippets**
If applicable, add code samples to help explain your points.

**Additional context**

**Comment by derrickmehaffy** [comment]
You will probably want to fork the plugin/provider (depends if you are using a provider) to do this.

**Comment by lauriejim** [comment]
Hello! To do so, you will have to create your own provider based on `strapi-provider-upload-local`

You will have to [update this line](https://github.com/strapi/strapi/blob/f9bc0a9b2ec6b7007851005554083873a3dd6498/packages/strapi-provider-upload-local/lib/index.js#L24) to match with the URL you want.

Here is some [documentation](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#create-providers) about provider creation.

**Comment by sunithakarthikeyan** [comment]
Thanks Laurie Will try the same
