### ISSUE TITLE
strapi new project --dev not working

### ISSUE THREAD

**Issue by LeoMartinDev** [strapi/strapi#4583]
**Describe the bug**
`strapi new project --dev` fail with `error: unknown option `--dev'`

**Steps to reproduce the behavior**
- `npm i -g strapi`
- `strapi new project --dev` 

**Expected behavior**
Should generate a new strapi project

**System**
- Node.js version: v10.16.3
- NPM version: V6.9.0
- Strapi version: 3.0.0-beta.17.5
- Operating system: MacOS Catalina

**Comment by LeoMartinDev** [comment]
Just found that it's not supposed to work if you've not cloned Strapi, it should be explained in the doc

**Comment by derrickmehaffy** [comment]
--dev was for alpha and was removed.
