### ISSUE TITLE
Can't add entries to repeatable groups from a controller 

### ISSUE THREAD

**Issue by bouhendfaycal** [strapi/strapi#4590]
**Describe the bug**
i have a model `posts` that have a group `comments`,
 when creating the first comment it works fine, but adding new comments gives me this : 
`Error: Some of the provided groups in comments are not related to the entity`
using sqlite works, the problem is when using mongodb

**Steps to reproduce the behavior**
1. create a repeatable field and add it to a content type
2. in the content type controller add code to insert the new entries to the group

**Code snippets**
```javascript
    const entity = await strapi.services.posts.findOne({ id: formData.id });
...
    let newComment = [
      ...entity.comments,
      {
        user: user,
        content: formData.comment
      }
    ];

...
strapi.services.posts.update({ id: formData.id },{comments : newComment});
```

**System**
- Node.js version: v10.15.2
- NPM version: 6.4.1
- Strapi version: beta 17.4
- Database: mongo:latest
- Operating system: macos

**Update**
i was able to add entries to a group by remapping previous ones ( removing the field _id )
```javascript
     let newComment = [
      ...entity.comments.map(com => {
        delete com._id;
        return com;
      }),
      {
        user: user.id,
        content: formData.comment
      }
    ];
```

**Comment by lauriejim** [comment]
Hello! Thank you for this report.

Added a notification, if you are sending the `id` of a group entry, it means there is an update to apply.
In your case, it's not necessarily the case. So to optimize your request perf, you will have to remove the `id` cause you just want to add a new entry I guess.

**Comment by bouhendfaycal** [comment]
in strapi groups i can't just add the new entry, i have to include all previous ones or otherwise they will be deleted !
currently to update an entry in a group you have to use the parent update(), or there is an other way ?

**Comment by lauriejim** [comment]
I closed my previous message. Was not correct.
In fact - `_id` is an object - you have to stringify it.
We don't have functions to pop or push entries.

**Comment by lauriejim** [comment]
Just tried and it works with the stable version of Strapi.
