### ISSUE TITLE
Bad Request Error on API Login 

### ISSUE THREAD

**Issue by MMrj9** [strapi/strapi#4591]
**Describe the bug**
I'm trying to get my jwt token using the api login method described in the documentation.
But I'm getting a 400 Bad Request error.
The code is exactly the same as the one in the documentation.

**Expected behavior**
Should login successfully and return user data and token.

**Code snippets** 
```
        axios
        .post(`${config.serverUrl}/auth/local`, {
            identifier: config.identifier,
            password: config.password
        })
        .then(response => {
            // Handle success.
            console.log('Well done!');
            console.log('User profile', response.data.user);
            console.log('User token', response.data.jwt);
        })
        .catch(error => {
            // Handle error.
            console.log('An error occurred:', error);
        });
````

**System**
- Node.js version: 12.4.0
- NPM version: 6.11.3
- Strapi version:  v3.0.0-beta.17
- Database: mongodb
- Operating system: Ubuntu

**Comment by bouhendfaycal** [comment]
check in user roles and permissions if you have permission to connect/register/**callback** in the public role

**Comment by MMrj9** [comment]
> check in user roles and permissions if you have permission to connect/register/**callback** in the public role - @bouhendfaycal 

Yes, the public roles has all auth permission enabled 

![Captura de ecrã 2019-11-25, às 13 58 48](https://user-images.githubusercontent.com/7461503/69546485-c351a500-0f8b-11ea-85d7-dfb2ba72dada.png)

**Comment by bouhendfaycal** [comment]
try replacing your dynamic values ( config. ..) with actual values, also check strapi server logs for more details

**Comment by MMrj9** [comment]
> try replacing your dynamic values ( config. ..) with actual values, also check strapi server logs for more details

Thanks. It was a dumb mistake. I was missing the port in the url
