### ISSUE TITLE
 add noindex meta tag to the default public/index.html

### ISSUE THREAD

**Issue by nicosh** [strapi/strapi#4593]
**Describe the bug**
Probably this is not a real bug but more an enhancement, even if it could be fixed easily I think it would make sense to add `<meta name="robots" content="noindex">` to the default `public/index.html`  since most likely we dont want index of (lazy dev) apis being indexed.
**Steps to reproduce the behavior**
Just google  "Welcome to your Strapi app" and you will find a lot of strapi api main pages being indexed

**Expected behavior**
By default index of strapi app should not be indexed.

**Comment by derrickmehaffy** [comment]
@nicosh the Index page is due to be refreshed here soon: https://github.com/strapi/strapi/pull/4418

**Comment by derrickmehaffy** [comment]
But if you could please submit a PR against the branch that PR was merged into
