### ISSUE TITLE
When having multiple uploads, cant identify each of them

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#4594]
**Describe the bug**
I have a content type, which has a upload field with many files

**Steps to reproduce the behavior**
1. Go to edit a given content type which has 7 files attached
2. You see 1/7 but cant identify their names (for example, to delete some of them)

**Expected behavior**
Clearly see the file name

**Screenshots**

<img width="439" alt="Captura de Pantalla 2019-11-25 a la(s) 10 14 37" src="https://user-images.githubusercontent.com/517228/69545764-2c77ef00-0f71-11ea-8d37-4a35331463ef.png">

**System**
- Node.js version: v13.1.0
- NPM version: v6.12.1
- Strapi version: v3.0.0-beta.17.5
- Database: mongodb
- Operating system: macOS

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
This is a topic for @soupette 

There is a workaround
You can edit your `./config/environments/development/security.json` file.
And for the ` "img-src": "'self' http:"` replace it by ` "img-src": "'self' http: data:"`

**Comment by lauriejim** [comment]
It has been fixed in the last version of Strapi (at least beta.18.7)
