### ISSUE TITLE
Mongo internals are being returned via API

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#4597]
**Describe the bug**
All mongo internals are being returned via API.

**Steps to reproduce the behavior**
1. Connect Strapi to mongo
2. Create a new entity
3. Fetch the entity via API

**Expected behavior**
I expect the API to just return an `id` of a document, not the mongo internals like `_id` or `__v`

**Screenshots**
![image](https://user-images.githubusercontent.com/11553624/69619112-5d245b00-103b-11ea-866a-da6067b70025.png)

**System**
- Node.js version: 12.10.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.17.5
- Database: MongoDB
- Operating system: MacOS

**Comment by lauriejim** [comment]
Hello, please refer to this issue.

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi/issues/4342
