### ISSUE TITLE
Installation guide for PostgreSQL

### ISSUE THREAD

**Issue by cawoodm** [strapi/strapi#4602]
Hello, could we have an @installation guide for PostgreSQL?
https://strapi.io/documentation/3.0.0-alpha.x/guides/databases.html

**Comment by lauriejim** [comment]
Hello! I'm not sure we need to have an installation guide of databases in our docs.
I think we will remove them.
I suggest you to search on google how to install PG on your OS

**Comment by cawoodm** [comment]
So how do folks know how the DB and users need to be set up?

I'm not talking about how to install and run PostgreSQL but at least what needs to be done to get strapi working on PostgreSQL. We spent an entire day trying to figure it out.

Specifically:
* Do we need this weird "bookshelf" hook?
* What rights does the strapi User in Postgress require?

**Comment by derrickmehaffy** [comment]
@cawoodm for SQL databases yes, you need both bookshelf and knex. Mongo uses mongoose.

As for permissions, all permissions for the database.
