### ISSUE TITLE
modelConnection GraphQL queries are bypassing permissions.

### ISSUE THREAD

**Issue by joelbqz** [strapi/strapi#4605]
**Describe the bug**
GraphQL connection queries ignores Public Role permissions and don't return forbidden

**Steps to reproduce the behavior**
1. Create a Model
2. Add some entries
3. Remove all permissions for Public role
4. Perform a GraphQL connection query ie.
![image](https://user-images.githubusercontent.com/19965325/69672648-89090600-1066-11ea-8ff3-77361de80aa4.png)

**Expected behavior**
It returns the results without being authenticated, as it is shown here 
![image](https://user-images.githubusercontent.com/19965325/69672695-a1792080-1066-11ea-8144-87ed6e18dae8.png)

**System**
- Node.js version: v12.11.1
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.17.5
- Database: MongoDB
- Operating system: Mac OS Mojave

**Additional context**
I don't know If this is a bug, or I'm doing something wrong and I need to set permissions for connection graphql queries in a different place than /admin/plugins/users-permissions/roles

**Comment by joelbqz** [comment]
Update: If you run this query it will return users even If the public role dont have permission to see them
```
{
  usersConnection {
    groupBy {
      username {
        key
      }
      email {
        key
      }
    }
  }
}
```

**Comment by lauriejim** [comment]
Hello! Thank you for this report!

**Comment by joelbqz** [comment]
@lauriejim thanks!

**Comment by joelbqz** [comment]
Update: @lauriejim I still can run this query with public role without any permission:  `{
  usersConnection {
    groupBy {
      username {
        key
      }
      email {
        key
      }
    }
  }
}`

**Comment by joelbqz** [comment]
Strapi version: 3.0.0-beta.17.7

**Comment by derrickmehaffy** [comment]
@alexandre

**Comment by derrickmehaffy** [comment]
@alexandrebodin

**Comment by alexandrebodin** [comment]
Hi @joelbqz I just retested and receive a forbidden error with the exact query you shared. Can you make sure you are using the  3.0.0-beta.17.7 and not a next-x version (check you are using and exact version in your package.json and run yarn why strapi to verify)

**Comment by joelbqz** [comment]
Hello @alexandrebodin 

Node.js version: v12.11.1
NPM version: 6.11.3
Strapi version: 3.0.0-beta.17.7
Database: MongoDB
Operating system: Mac OS Mojave

Strapi running on development environment(Strapi v3.0.0-beta.17.7)
![image](https://user-images.githubusercontent.com/19965325/70072367-d9331b80-15c4-11ea-9b63-b4ff9d9eab12.png)

Query response(not forbidden):
![image](https://user-images.githubusercontent.com/19965325/70072481-126b8b80-15c5-11ea-8c63-0427f4641e4d.png)

User permissions for public role:
![image](https://user-images.githubusercontent.com/19965325/70072533-2dd69680-15c5-11ea-8479-0d51785b131c.png)

**Comment by alexandre** [comment]
Remove my user from the thread, please.

**Comment by joelbqz** [comment]
@alexandrebodin 
![image](https://user-images.githubusercontent.com/19965325/70073325-a68a2280-15c6-11ea-91a2-613c9630b8cb.png)

Strapi is running on 3.0.0-beta.17.8, do I need to upgrade dependencies strapi-plugin-graphql?
Do you think

**Comment by derrickmehaffy** [comment]
Two things @joelbqz 

1) you should make sure none of your strapi packages have a carrot `^` in them as it will mess up and pull @next tags from npm
2) All Strapi built and managed packages (all of the ones you have right now) should be the same version. So if Strapi is beta.17.8 then all of them need to be beta.17.8

**Comment by joelbqz** [comment]
@derrickmehaffy thanks! just updated all the dependencies, its working now!

**Comment by derrickmehaffy** [comment]
Glad to hear it :+1:
