### ISSUE TITLE
Releated Content Types to Show images in the dropdown

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4607]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Created a Content Type "ShowCaseImage" and media (jpg) is one of the FieldType.
Created a Content  Type "Article" and created One Article has Many "ShowcaseImages"
When creating a Article Can we have the Preview of the Image in the Dropdown

**Your suggestions for this topic**
In Content Manager Screen ....On Article we can set Entry Title as "**Media**" for ShowCaseImage.

**Screenshots**
![article](https://user-images.githubusercontent.com/2913281/69694068-a1782f80-10fd-11ea-95f9-652ef45dada1.png)
![contentmanager](https://user-images.githubusercontent.com/2913281/69694069-a1782f80-10fd-11ea-8829-ba3eb8fa6c53.png)
![add](https://user-images.githubusercontent.com/2913281/69694070-a210c600-10fd-11ea-962e-28d79130fa65.png)

**Code snippets**
If applicable, add code samples to help explain your points.

**Additional context**
Objective: Editors Would require to add Existing Images to reuse them in Articles by looking up the Preview of the same in Current Screen.

In Current Strapi version (17.4) Image name is listed and on clicking the same its going to the Image Content Type but on travelling back the via Back button in the application the Article Content is Lost.

Another Suggestion : **Open in New Tab**  Option in addition to the existing feature "**Click to Jump to the Entry**" will be a workaround option for now.

Preview on Images in dropdown in most required feature for Editors for us.

**Comment by lauriejim** [comment]
Hello @sunithakarthikeyan ! 

Thank you for this insight.
We will not work on it so I will close your issue. BUT!

I will send you some resources that will let you custom the admin panel to have this feature.

Here is the customization concept: https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#plugin-extensions
Here is a guide that show you how to customize the admin: https://strapi.io/documentation/3.0.0-beta.x/guides/custom-admin.html
Here is an article that update the WYSIWYG: https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi?redirectPage=1

**Comment by sunithakarthikeyan** [comment]
Thanks Lauriejim, We have managed to tweak the code and can show the images after selecting the same
![images](https://user-images.githubusercontent.com/2913281/69861201-e9de4b80-12bd-11ea-928f-75103299574e.png)
