### ISSUE TITLE
Grouping Content Types as Menu / Submenu

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4608]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Grouping Content Types as Menu / Submenu. We have 20 Content Types and its difficult to pick from Single menu . Can we have one level hierarchy for addressing this issues

**Comment by derrickmehaffy** [comment]
Hello, I am marking this feature request as a duplicate as this one is already planned.

You can view this feature request on the product board here: https://portal.productboard.com/strapi/1-public-roadmap/c/13-administration-menu

Scheduled ETA is Q3 2020
