### ISSUE TITLE
Customize database column name and field name in the API response

### ISSUE THREAD

**Issue by ly525** [strapi/strapi#4616]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Hi, I want to ask a question  about API:
In the table  `art_work` I created 3 fields:

```js
create_time: DateTime
update_time: DateTime
cover_url: Text
```

When I use strapi.service.findOne or find,  to visit /art-work/1 will get the response:
```js
{
   create_time: '2019-01-01T10:00:00',
   update_time: '2019-01-02T00:00:00',
   cover_url: 'http://img.com/abc.png'
}
```

I want to get the camelCased api response, may I add some fieldNameMapping to api/art-work/model.setting.json
like this（Spring Boot）：

![image](https://user-images.githubusercontent.com/12668546/69786368-41fd4b00-11f5-11ea-9eeb-de2ea08b0147.png)

I want to get the response like
```js
{
   createTime: '2019-01-01T10:00:00',
   updateTime: '2019-01-02T00:00:00',
   coverUrl: 'http://img.com/abc.png'
}
```

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

This is an help wanted and not a feature request.
Can you open a StackOverflow question by given your strapi version you are using and the database you use please.

**Comment by ly525** [comment]
@lauriejim  thanks for your reply. Sorry about this, I think it's a feature request more that bug, which need support from strapi.
I re-searched the issues and found that #3615 is similar with my issue, I will watch that issue, thanks.

**Comment by lauriejim** [comment]
What changed between the data you currently get and the data you expect?

**Comment by ly525** [comment]
@lauriejim 

the data I currently get 
```json
{
    "id": 5397,
    "title": null,
    "description": null,
    "cover_image_url": "/uploads/2c94e35f9d1f423ea8d60bad10232858.png",
    "pages": [],
    "is_publish": null,
    "is_template": 0,
    "created_at": "2019-11-25T09:51:26.249Z",
    "updated_at": "2019-11-25T09:51:26.261Z",
    "workforms": []
}
```

the data I expect:
```json
{
    "id": 5397,
    "title": null,
    "description": null,
    "coverImageUrl": "/uploads/2c94e35f9d1f423ea8d60bad10232858.png",
    "pages": [],
    "isPublish": null,
    "isTemplate": 0,
    "createdAt": "2019-11-25T09:51:26.249Z",
    "updatedAt": "2019-11-25T09:51:26.261Z",
    "workforms": []
}
```

I want to covert the json key from `underline` to `camelCased `
I used `strapi.js` for my open-source project: https://github.com/ly525/luban-h5
I want to add a field mapping to provide the api which is  compatible with Java API(or similar with java)

thanks!

**Comment by ichirkin** [comment]
+1 🙏🏻

**Comment by douglasjunior** [comment]
Same here, we tried also to set the "Custom Column Name" to customize the database column name, but this config seems to be ignored.

Strap 3.1.6, REST and GraphQL.

We need that in JSON the object is returned as "secao", and in the database the column has the name "secao_id".

So, we try to set the `secao_id` in **Field name**:

![image](https://user-images.githubusercontent.com/1512341/95246165-80d33880-07ea-11eb-9a95-43b981fc118d.png)

And `secao` in **Custom column names**.

![image](https://user-images.githubusercontent.com/1512341/95245673-ce02da80-07e9-11eb-9cae-be7c08dc72b9.png)

But the **Custom column names** just doesn't change anything.

_We also tried to invert the values of **Field name** and "**Custom column names**, but it didn't work._

**Comment by saxahan** [comment]
+1 :pray:

**Comment by derrickmehaffy** [comment]
Is technically possible in v4, again @alexandrebodin should we just document the unstable API for this?

**Comment by ohadperry** [comment]
still not clear regarding this feature, is it possible? if yes, how exactly? @ilytrevino

**Comment by derrickmehaffy** [comment]
> still not clear regarding this feature, is it possible? if yes, how exactly? @ilytrevino

In Strapi v4 you can customize the database stuff via this method but you should be careful: https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#database-validations-and-settings

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
