### ISSUE TITLE
Why does strapi always automatically restart?

### ISSUE THREAD

**Issue by RoymanJing** [strapi/strapi#462]
**Node.js version**:8.94
**npm version**:5.6.0
**Strapi version**:3.0.0-alipha.7.3
**Operating system**:centos-release-7-2.1511.el7.centos.2.10.x86_64

Strapi always automatically restarts, the performance is bad, please help.

INFO (10473 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10473 on localhost): Your server is running at http://localhost:1337
DEBUG (10473 on localhost): Time: Wed Jan 17 2018 09:29:49 GMT-0800 (PST)
DEBUG (10473 on localhost): Launched in: 1299 ms
DEBUG (10473 on localhost): Environment: development
DEBUG (10473 on localhost): Process PID: 10473
DEBUG (10473 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10473 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10473 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10485 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10485 on localhost): Your server is running at http://localhost:1337
DEBUG (10485 on localhost): Time: Wed Jan 17 2018 09:29:55 GMT-0800 (PST)
DEBUG (10485 on localhost): Launched in: 1372 ms
DEBUG (10485 on localhost): Environment: development
DEBUG (10485 on localhost): Process PID: 10485
DEBUG (10485 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10485 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10485 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10498 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10498 on localhost): Your server is running at http://localhost:1337
DEBUG (10498 on localhost): Time: Wed Jan 17 2018 09:30:00 GMT-0800 (PST)
DEBUG (10498 on localhost): Launched in: 1218 ms
DEBUG (10498 on localhost): Environment: development
DEBUG (10498 on localhost): Process PID: 10498
DEBUG (10498 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10498 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10498 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10517 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10517 on localhost): Your server is running at http://localhost:1337
DEBUG (10517 on localhost): Time: Wed Jan 17 2018 09:30:05 GMT-0800 (PST)
DEBUG (10517 on localhost): Launched in: 1283 ms
DEBUG (10517 on localhost): Environment: development
DEBUG (10517 on localhost): Process PID: 10517
DEBUG (10517 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10517 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10517 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10529 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10529 on localhost): Your server is running at http://localhost:1337
DEBUG (10529 on localhost): Time: Wed Jan 17 2018 09:30:11 GMT-0800 (PST)
DEBUG (10529 on localhost): Launched in: 1244 ms
DEBUG (10529 on localhost): Environment: development
DEBUG (10529 on localhost): Process PID: 10529
DEBUG (10529 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10529 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10529 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10541 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10541 on localhost): Your server is running at http://localhost:1337
DEBUG (10541 on localhost): Time: Wed Jan 17 2018 09:30:17 GMT-0800 (PST)
DEBUG (10541 on localhost): Launched in: 1376 ms
DEBUG (10541 on localhost): Environment: development
DEBUG (10541 on localhost): Process PID: 10541
DEBUG (10541 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10541 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10541 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10553 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10553 on localhost): Your server is running at http://localhost:1337
DEBUG (10553 on localhost): Time: Wed Jan 17 2018 09:30:22 GMT-0800 (PST)
DEBUG (10553 on localhost): Launched in: 1235 ms
DEBUG (10553 on localhost): Environment: development
DEBUG (10553 on localhost): Process PID: 10553
DEBUG (10553 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10553 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10553 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10565 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10565 on localhost): Your server is running at http://localhost:1337
DEBUG (10565 on localhost): Time: Wed Jan 17 2018 09:30:28 GMT-0800 (PST)
DEBUG (10565 on localhost): Launched in: 1470 ms
DEBUG (10565 on localhost): Environment: development
DEBUG (10565 on localhost): Process PID: 10565
DEBUG (10565 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10565 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10565 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10577 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10577 on localhost): Your server is running at http://localhost:1337
DEBUG (10577 on localhost): Time: Wed Jan 17 2018 09:30:34 GMT-0800 (PST)
DEBUG (10577 on localhost): Launched in: 1740 ms
DEBUG (10577 on localhost): Environment: development
DEBUG (10577 on localhost): Process PID: 10577
DEBUG (10577 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10577 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10577 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10589 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10589 on localhost): Your server is running at http://localhost:1337
DEBUG (10589 on localhost): Time: Wed Jan 17 2018 09:30:40 GMT-0800 (PST)
DEBUG (10589 on localhost): Launched in: 2242 ms
DEBUG (10589 on localhost): Environment: development
DEBUG (10589 on localhost): Process PID: 10589
DEBUG (10589 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10589 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10589 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10602 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10602 on localhost): Your server is running at http://localhost:1337
DEBUG (10602 on localhost): Time: Wed Jan 17 2018 09:30:45 GMT-0800 (PST)
DEBUG (10602 on localhost): Launched in: 1248 ms
DEBUG (10602 on localhost): Environment: development
DEBUG (10602 on localhost): Process PID: 10602
DEBUG (10602 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10602 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10602 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10614 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10614 on localhost): Your server is running at http://localhost:1337
DEBUG (10614 on localhost): Time: Wed Jan 17 2018 09:30:50 GMT-0800 (PST)
DEBUG (10614 on localhost): Launched in: 1235 ms
DEBUG (10614 on localhost): Environment: development
DEBUG (10614 on localhost): Process PID: 10614
DEBUG (10614 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10614 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10614 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10626 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10626 on localhost): Your server is running at http://localhost:1337
DEBUG (10626 on localhost): Time: Wed Jan 17 2018 09:30:56 GMT-0800 (PST)
DEBUG (10626 on localhost): Launched in: 1274 ms
DEBUG (10626 on localhost): Environment: development
DEBUG (10626 on localhost): Process PID: 10626
DEBUG (10626 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10626 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10626 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10639 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10639 on localhost): Your server is running at http://localhost:1337
DEBUG (10639 on localhost): Time: Wed Jan 17 2018 09:31:02 GMT-0800 (PST)
DEBUG (10639 on localhost): Launched in: 1666 ms
DEBUG (10639 on localhost): Environment: development
DEBUG (10639 on localhost): Process PID: 10639
DEBUG (10639 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10639 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10639 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10651 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10651 on localhost): Your server is running at http://localhost:1337
DEBUG (10651 on localhost): Time: Wed Jan 17 2018 09:31:07 GMT-0800 (PST)
DEBUG (10651 on localhost): Launched in: 1523 ms
DEBUG (10651 on localhost): Environment: development
DEBUG (10651 on localhost): Process PID: 10651
DEBUG (10651 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10651 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10651 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10663 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10663 on localhost): Your server is running at http://localhost:1337
DEBUG (10663 on localhost): Time: Wed Jan 17 2018 09:31:12 GMT-0800 (PST)
DEBUG (10663 on localhost): Launched in: 1224 ms
DEBUG (10663 on localhost): Environment: development
DEBUG (10663 on localhost): Process PID: 10663
DEBUG (10663 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10663 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10663 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10675 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10675 on localhost): Your server is running at http://localhost:1337
DEBUG (10675 on localhost): Time: Wed Jan 17 2018 09:31:18 GMT-0800 (PST)
DEBUG (10675 on localhost): Launched in: 1204 ms
DEBUG (10675 on localhost): Environment: development
DEBUG (10675 on localhost): Process PID: 10675
DEBUG (10675 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10675 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10675 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10687 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10687 on localhost): Your server is running at http://localhost:1337
DEBUG (10687 on localhost): Time: Wed Jan 17 2018 09:31:23 GMT-0800 (PST)
DEBUG (10687 on localhost): Launched in: 1262 ms
DEBUG (10687 on localhost): Environment: development
DEBUG (10687 on localhost): Process PID: 10687
DEBUG (10687 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10687 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10687 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10699 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10699 on localhost): Your server is running at http://localhost:1337
DEBUG (10699 on localhost): Time: Wed Jan 17 2018 09:31:29 GMT-0800 (PST)
DEBUG (10699 on localhost): Launched in: 1493 ms
DEBUG (10699 on localhost): Environment: development
DEBUG (10699 on localhost): Process PID: 10699
DEBUG (10699 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10699 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10699 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10711 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10711 on localhost): Your server is running at http://localhost:1337
DEBUG (10711 on localhost): Time: Wed Jan 17 2018 09:31:35 GMT-0800 (PST)
DEBUG (10711 on localhost): Launched in: 1415 ms
DEBUG (10711 on localhost): Environment: development
DEBUG (10711 on localhost): Process PID: 10711
DEBUG (10711 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10711 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10711 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10723 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10723 on localhost): Your server is running at http://localhost:1337
DEBUG (10723 on localhost): Time: Wed Jan 17 2018 09:31:41 GMT-0800 (PST)
DEBUG (10723 on localhost): Launched in: 1725 ms
DEBUG (10723 on localhost): Environment: development
DEBUG (10723 on localhost): Process PID: 10723
DEBUG (10723 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10723 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10723 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10735 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10735 on localhost): Your server is running at http://localhost:1337
DEBUG (10735 on localhost): Time: Wed Jan 17 2018 09:31:46 GMT-0800 (PST)
DEBUG (10735 on localhost): Launched in: 1406 ms
DEBUG (10735 on localhost): Environment: development
DEBUG (10735 on localhost): Process PID: 10735
DEBUG (10735 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10735 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10735 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

INFO (10747 on localhost): Server started in /home/wpe/strapiDemo/strapiDemo
INFO (10747 on localhost): Your server is running at http://localhost:1337
DEBUG (10747 on localhost): Time: Wed Jan 17 2018 09:31:51 GMT-0800 (PST)
DEBUG (10747 on localhost): Launched in: 1241 ms
DEBUG (10747 on localhost): Environment: development
DEBUG (10747 on localhost): Process PID: 10747
DEBUG (10747 on localhost): Version: 3.0.0-alpha.7.3 (node v8.9.4)
INFO (10747 on localhost): To shut down your server, press <CTRL> + C at any time
INFO (10747 on localhost): File changed: /home/wpe/strapiDemo/strapiDemo/log.txt
INFO (9665 on localhost): The server is restarting

**Comment by Aurelsicoko** [comment]
It's caused by the `log.txt` file at the root of your project. Also, to avoid the restart you have two choices:

- Run your server using `npm start`
- Disabled the auto-reload feature https://strapi.io/documentation/configurations/configurations.html#server

**Comment by RoymanJing** [comment]
got it, thanks!
