### ISSUE TITLE
cannot save modified rich content when use IME(in my case Chinese)

### ISSUE THREAD

**Issue by StinsonZhao** [strapi/strapi#4621]
**Describe the bug**  

I found that when I update rich content(in the draft-js editor), as usual, I inserted 2 Chinese words (**with IME**) into the sentence, and clicked 'save' button. But the content was still original.

**Steps to reproduce the behavior**
1. Go to admin
2. Click 'edit' button to update an existing rich article, **JUST USE IME TO INPUT SOME CHINESE， NO OTHER CHARS, JUST IME WORDS, EVEN SPACE**
3. Click 'save'
4. Then go back to see, nothing changed

**Expected behavior**
I can update rich content with IME.

**Screenshots**
![2019-11-28 20 04 38](https://user-images.githubusercontent.com/6703905/69805505-c4990100-121b-11ea-83dc-ecd41befa387.gif)

**Code snippets**
I find somewhere maybe make a mistake:

```javascript
// strapi-plugin-content-manager/admin/src/components/Wysiwyg/index.js
...
  onChange = editorState => {
    this.sendData(editorState);
    this.setState({ editorState });
  };
...

sendData = editorState => {
    // 🔥
    // remove these lines, it works for me.
    // so it seems like with IME, `this.getEditorState().getCurrentContent()` is always  equal to `editorState.getCurrentContent()`
    // then this.props.onChange won't be called.

    // if (
    //   this.getEditorState().getCurrentContent() ===
    //   editorState.getCurrentContent()
    // )
    //   return;

    this.props.onChange({
      target: {
        value: editorState.getCurrentContent().getPlainText(),
        name: this.props.name,
        type: 'textarea',
      },
    });
  };
```

**Comment by lauriejim** [comment]
Hello! Can you check the data sent in the request?
Is your update applied in the request?

**Comment by StinsonZhao** [comment]
> Hello! Can you check the data sent in the request?
> Is your update applied in the request?

Still the original data.

In fact, if I just insert something with IME, then the content in the editor(markdown) is changed, but when I click 'preview', the previewed content is also still the original. Then I have to insert one space and then delete the space immediately, that will work.
