### ISSUE TITLE
Missing warning/prompt about losing unsaved content

### ISSUE THREAD

**Issue by sibyl229** [strapi/strapi#4629]
**Describe the bug**
When editing content of an entry through the Admin panel, if the user **accidentally** navigates to another page without saving the change, there is no prompt to warn them that the unsaved change will be lost. 

**Accidentally navigating to another page can easily happen, and it would be disappointing if a user has entered a lot of content, and losing them by this simple mistake.**

**Steps to reproduce the behavior**
1. Assuming the content type Restaurant exists, with a field called `description` for rich text description
2. On the Admin Panel, navigate to "Create an Entry" for Restaurant
3. Enter text to the `description` field, but **without clicking on the "Save" button**
4. Navigate to another page within the Admin Panel, such as browsing to another content type through the sidebar. 
5. Observe that no warning or prompt is shown, but when coming back to "Create an (restaurant) Entry", the previously entered description is lost. 

**Expected behavior**
A prompt is shown, such as "Your unsaved content will be lost." With option to 1) "Discard un-saved change" (and proceed to where the user intended to go) or 2) "Stay on the page".

**Screenshots**
N/A.

**Code snippets**
N/A

**System**
Docker for Mac, Docker version 19.03.1, build 74b1e89

**Additional context**
N/A

**Comment by derrickmehaffy** [comment]
@sibyl229 I think this should be a feature request not a bug report

**Comment by derrickmehaffy** [comment]
Going to mark this as closed @sibyl229 can you please open up a feature request for this?

Also tagging @Aurelsicoko about this
