### ISSUE TITLE
Admin dashboard mobile support

### ISSUE THREAD

**Issue by dcalsky** [strapi/strapi#463]
Current admin dashboard is mussy on the mobile device. Do we have any plan to fix it?

**Comment by lauriejim** [comment]
You will find the answer here https://stackoverflow.com/questions/48254489/strapi-responsive-ui

**Comment by ialmanzaj** [comment]
i'm going to be working on it

**Comment by svjp** [comment]
@ialmanzaj How's the mobile support going? I'd like to help! But also I don't want to step over your feet.

**Comment by DzmitryG** [comment]
Hi everyone,
was it prioritized so low?
4 years from submission and still no responsive version, any deadline?

**Comment by derrickmehaffy** [comment]
> Hi everyone, was it prioritized so low? 4 years from submission and still no responsive version, any deadline?

Someone else in the community is working on their own. Though the repo is private atm

@Saad-ISAA

**Comment by Saad-ISAA** [comment]
@DzmitryG  I have developed a mobile app supported for android and iOS for Strapi v4 and is planned to be released in this month.

**Comment by IamSAL** [comment]
A CMS should allow the user's manage content on the go. Plz prioritize this 🙏

**Comment by godecafcode** [comment]
> @DzmitryG  I have developed a mobile app supported for android and iOS for Strapi v4 and is planned to be released in this month. 
> 
> 

Awesome. How's the development of the app going?

**Comment by Saad-ISAA** [comment]
> > @DzmitryG  I have developed a mobile app supported for android and iOS for Strapi v4 and is planned to be released in this month.
> 
> Awesome. How's the development of the app going?

it's ready for publish, just waiting for the marketing team to provide some details, then it'll be public. :-)

**Comment by cKhoff** [comment]
Any updates ?

**Comment by havardox** [comment]
Any updates? I'm hesitant about using Strapi because of this.

**Comment by hariangr** [comment]
> > > @DzmitryG  I have developed a mobile app supported for android and iOS for Strapi v4 and is planned to be released in this month.
> > 
> > Awesome. How's the development of the app going?
> 
> it's ready for publish, just waiting for the marketing team to provide some details, then it'll be public. :-)

Got any updates?

**Comment by DzmitryG** [comment]
> > > > @DzmitryG  I have developed a mobile app supported for android and iOS for Strapi v4 and is planned to be released in this month.
> > > 
> > > Awesome. How's the development of the app going?
> > 
> > it's ready for publish, just waiting for the marketing team to provide some details, then it'll be public. :-)
> 
> Got any updates?

I'm waiting for updates too :)

**Comment by Saad-ISAA** [comment]
https://github.com/Saad-ISAA/strapi-mobile
It's public now.
We are working on getting it on the stores. meanwhile you can use the apk attached in the releases of this repo

@DzmitryG @hariangr @havardox @cKhoff 
CC: @derrickmehaffy

**Comment by PeteJStewart** [comment]
I thought this was discussing responsive support for the admin web interface, as that seems like something Strapi should have.
But a Flutter mobile app is also pretty cool!

Does anyone know if there's a plan to make the web admin area responsive for mobile phones.  It seems to work ok for larger devices, but isn't seemingly usable on phones.

**Comment by derrickmehaffy** [comment]
> I thought this was discussing responsive support for the admin web interface, as that seems like something Strapi should have. But a Flutter mobile app is also pretty cool!
> 
> Does anyone know if there's a plan to make the web admin area responsive for mobile phones. It seems to work ok for larger devices, but isn't seemingly usable on phones.

It's an idea we have tossed around but no, no official timeline. It would basically require us to build features on top of our new design system to make those responsive and then we could work on making the admin itself responsive

**Comment by oelbaga** [comment]
Almost 2023 I'm searching for the same thing and seeing these questions about making the dashboard responsive years ago. I love strapi but it's unbelievably disappointing that you can't even do a simple post entry on a phone. 

I'm unsure how these limits are ok in todays environment. Consider simply allowing the toggling the sidebars off screen and allowing scroll.

**Comment by dominikjasek** [comment]
I created a patch which makes it at least little bit more usable for users on phone. It looks still ugly, however IMHO better than current strapi non-responsive version.


https://user-images.githubusercontent.com/48070343/199592171-a6df21ce-c039-4d81-9c67-e8cff2925dd7.mp4



Feel free to use it: https://gist.github.com/dominikjasek/87b22fa9cd452ffcca14ff66d5358bed

**Comment by RyanCwynar** [comment]
Yeah, how is this not higher up.. it's just some CSS work. it's not even a hard feature to deliver on. Would make it easier to get content edits out of my non-technical founders.

**Comment by nguyenth69** [comment]
I think this feature will be for paid users

**Comment by mancioshell** [comment]
I think it's and unbelievable things that in the 2023 a CMS does not have a responsive design in the admin Panel.

**Comment by oelbaga** [comment]
> I think it's unbelievable things, in the 2023 a CMS does not have a responsive admin panel gui.

Truly unbelievable. Seems like the market for headless CMS is wide open right now!

**Comment by martinjdlabs** [comment]
I also need this!

**Comment by m7jxc** [comment]
> I think it's unbelievable things, in the 2023 a CMS does not have a responsive admin panel gui.

And it's actually so easy to make it responsive. I wonder why it's still delayed...
If they let me to do it, I'd lovely help for free

**Comment by turbcool** [comment]
It has been 2 years and still no responsive admin UI. I moved on with Directus for my next projects.

**Comment by BIhab** [comment]
Still nothing? We got V4, V5, and now V6 but still not adapted to mobile?
