### ISSUE TITLE
update returns null when updated by other key other than id

### ISSUE THREAD

**Issue by emahuni** [strapi/strapi#4631]
**Describe the bug**
When updating a record in the DB, update doesn't return anything if the key that was used was not id.

**Steps to reproduce the behavior**
1. Create an API named record, with a string field called `data` in the model
2. Open Strapi console and create a single entry with: { data: 'this is it' }
3. `strapi.query('record').update({data: 'this is it'}, {data: 'that was it'}).then(r=>console.log(r))`
4. You should notice that the update was done in the DB, as expected, but the result of `r` in the code above was not the expected. It produces `null` and some deprecation warning of using a domain property in MakeCallback. Update with id as the key works without any issues.

**Expected behavior**
The same result as this command `strapi.query('record').update({id: 1}, {data: 'that was it'}).then(r=>console.log(r))`, which produces a the result of the updated record.

**System**
- Node.js 13.2.0
- NPM version: 6.13.1
- Strapi version: 3.0.0-beta.17.6
- Database: Postgresql
- Operating system: Linux Debian

**Comment by derrickmehaffy** [comment]
This is not a bug, for now the ID is the only supported way to update data.

**Comment by micahbule** [comment]
This also exists for the the `afterUpdate()` lifecycle for version 3.2.3. If this was already fixed in later versions, please correct me -- and maybe update the documentation as well.

Thanks.

**Comment by derrickmehaffy** [comment]
@micahbule can you point to the documentation that needs an update?
