### ISSUE TITLE
Use of JWT in httpOnly cookie

### ISSUE THREAD

**Issue by luwes** [strapi/strapi#4632]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
This is a duplicate of the Strapi JS SDK issue https://github.com/strapi/strapi-sdk-javascript/issues/31 by @sedubois but since the sdk is not maintained I like to open a discussion here. 

JWTs are stored in localStorage, but according to this article (https://www.rdegges.com/2018/please-stop-using-local-storage/), this is subject to XSS attacks so instead they should be stored in cookies.

> please, please, whatever you do, do not store session information (like JSON Web Tokens) in local storage. This is a very bad idea and will open you up to an extremely wide array of attacks that could absolutely cripple your users.

---

Reply by @pierreburgy

> According to many articles, storing tokens in local storage is an important security mistake:

* [auth0.com/docs/security/store-tokens](https://auth0.com/docs/security/store-tokens)
* [stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage)
* [dev.to/rdegges/please-stop-using-local-storage-1i04](https://dev.to/rdegges/please-stop-using-local-storage-1i04)

> But, tell me if I am wrong, the `js-cookie` module causes the exact same issue, because the token is accessible through any script running on the same domain. The only way to solve this issue is to store the token from a server with `HttpOnly`: [developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies).

**Your suggestions for this topic**

- Would be great to have an answer by a Strapi team member describing why most Strapi examples work with localStorage.
- I think some extra info in the docs would help beginning Strapi devs.
Maybe on this page? https://strapi.io/documentation/3.0.0-beta.x/guides/jwt-validation.html#customize-the-jwt-validation-function
- Add example code to implement authorization via a JWT cookie.
- Discuss if a httpOnly cookie should be the preferred way in a browser context as it's safer and looks simpler too. An authenticated user can easily hit a GET endpoint and view the authenticated content.

**Comment by luwes** [comment]
Probably misinterpreted the `strapi.sid` cookie?
Should we set an extra cookie with the JWT token (from 3rd party)?

**Comment by luwes** [comment]
The providers all return an access token. If the signed in user is to make any requests to the provider API (via Strapi) that access token also has to be stored somewhere. Currently there seems no way to get that access token from the user-permissions service.

**Comment by derrickmehaffy** [comment]
@luwes the JWTs are not stored by Strapi, they are generated on the fly and decrypted per request.

While I agree it's not a good idea to store them in localStorage, there isn't nothing stopping anyone from using httpOnly cookies.

@lauriejim thoughts on adding something to the docs? Personally I feel that goes beyond the realm of Strapi itself (as it's not really a problem of strapi) that being said I have been all in favor of storing user session information to prevent hijacking/repeater attacks in which someone takes a JWT and uses it (from say a different IP Address than it was requested for).

To do the above ^^^ would related to my Discussion topic on actual storage of the JWT in something like Redis with a fallback to either memory or the database. https://github.com/strapi/strapi/issues/3866

**Comment by luwes** [comment]
Thanks for your reply. Makes sense mostly. So we as strapi users would need to add `extensions/users-permissions/controllers/Auth.js` and add a `httpOnly` cookie there (can only be created by the server) with the JWT token.

To have authorization to the 3rd party API like Twitter, Instagram the gotten OAauth Access Token could be stored in the user DB table or so.

I think the part to store the JWT in Redis, DB, etc. makes less sense. This is needed on the client side right?

**Comment by derrickmehaffy** [comment]
No Redis is client side it would keep a cached state of the user and the token assigned to them/IP Address/ect.

Basically at the point of logout, the client would fire a request and delete that state.

(I'm not entirely familiar with httpOnly cookies, if it's something that Strapi has to send then it could be an option to add)

**Comment by luwes** [comment]
I don't see any benefit to storing the JWT on the server. The JWT is needed on the client to authenticate the user (to "log in") (for every request). Either in local storage where you pass the JWT as a header Authorization: Bearer in the request from the client OR this is stored in the `httpOnly` cookie which doesn't require passing that header all the time, it's just gotten from that cookie which is available both on client and server.

**Comment by derrickmehaffy** [comment]
It acts as a means of revoking a JWT which isn't currently possible without forcefully revoking all issued JWTs. When a JWT is created and sent to the client, until it expires it is valid, including if someone steals that JWT and uses it in a "repeater" attack

**Comment by derrickmehaffy** [comment]
Along with the above ^^^ it would also allow for easier support of refresh tokens to reissue a JWT without the user needing to enter in their account information again.

**Comment by luwes** [comment]
@derrickmehaffy I think I get your point but to be sure this will still require a JWT on the client correct? either via local storage or httpOnly cookie.

It could be a good first step to inform users how to add this in Strapi because a `httpOnly` cookie can only be set on the server. Most resources strongly recommend not using local storage it seems. 

https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage

**Comment by derrickmehaffy** [comment]
Generally yes both options could exist but in the cases I mentioned even if someone got their hands on the token they wouldn't be able to do anything.

On the flip side to that there are cases where JWT can still be secure such as with mobile apps keeping it locked inside an app sandbox or similar applications such as desktop apps or server scripts ect.

Benefit of a headless CMS is not all content may come from the browser :) So we don't want to lock out people who can't use cookies

**Comment by derrickmehaffy** [comment]
I do agree with your solution though it would be worth added for better security

**Comment by keymandll** [comment]
This was not mentioned yet as far as I see, it may be under one of the links posted, but:

Please note if you passed JWT as an HttpOnly cookie you would also have to implement CSRF protection. 

What I ended up implementing in one of my projects is .e.g.:

 0. All authenticated sessions are issued a CSRF token (CSRF tokens are OK to be stored in local storage)
 1. API allows JWT to be passed in either as a cookie (httpOnly) or in Auth header
 2. Only if JWT is received via cookie the API requires a valid CSRF token as well
 3. (Consider) Attribute within JWT to specify if it was issued to a user or an app. If token was issued to user, expect JWT as cookie, otherwise expect JWT in header.

Also:

 1. Once you have an XSS the outcome of an attack can be a lot more than stealing a JWT token.
 2. Caching JWTs in Redis, etc. is generally a bad idea. The nice thing about a JWT is that it's issued to the client and the server does not have to keep a copy to be able to authenticate a client. If you put user JWTs in another service on "server-side" you have to make sure that service is really really secure as if that service gets compromised, all cached JWTs will be exposed to the attacker.

**Comment by yhrchan** [comment]
Sorry I was also trying to figure out how to use httpCookie via Strapi as I don't want to store the returned JWT to local storage on the client side. How would I do this? Is this a functionality which exist out of the box from Strapi? I couldn't find such information from the documentations. Any help would be greatly appreciated!

Thanks!

**Comment by curiousercreative** [comment]
> 2. Caching JWTs in Redis, etc. is generally a bad idea. The nice thing about a JWT is that it's issued to the client and the server does not have to keep a copy to be able to authenticate a client. If you put user JWTs in another service on "server-side" you have to make sure that service is really really secure as if that service gets compromised, all cached JWTs will be exposed to the attacker.

@keymandll can you reference anything for the "generally a bad idea" claim? Your prescription to have the token store be secure is valid of course, but it'd seem that Redis is no harder to secure for most applications and if you want token revocation, you'll need to store them. [SO question " Should I store JWT tokens in Redis"](https://stackoverflow.com/questions/44890564/should-i-store-jwt-tokens-in-redis)

**Comment by Fl4zher** [comment]
I actually have an issue with storing the JWT in localstorage. The issue is that i am using Next.js for SSR my application, and it is not possible to get values from localstorage with SSR. 
I would better like the httpOnly cookie method. But another problem is that i am using GraphQL, so the question is - how can i edit the graphql context within Strapi?
