### ISSUE TITLE
add Apple Providers

### ISSUE THREAD

**Issue by mehdiraized** [strapi/strapi#4635]
https://developer.apple.com/documentation/signinwithapplejs/configuring_your_webpage_for_sign_in_with_apple

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```
