### ISSUE TITLE
Dinamic field displaying in content-type item creation

### ISSUE THREAD

**Issue by richardevcom** [strapi/strapi#4637]
- [+] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
I've been trying to make content-type with custom fields that either are shown or hidden depending on what value is selected in Listing dropdown field. For example - Page content-type with "template" listing field, with values "home","about","contacts" etc. and with fields for each of page templates. Whenever you change the listing value, according page fields are shown and unrelated fields are hidden (something similar that WordPress has - page templates).

I've read the docs, but no luck to figuring out the best way to implement this solution. Basically it's something similar to this: [https://github.com/strapi/strapi/issues/4180](https://github.com/strapi/strapi/issues/4180), only the visibility of field is determined by value of another field.
Any leads/suggestions on how to do this dinamically?

**Your suggestions for this topic**
Dynamic field display & inner field relations.

**Screenshots**
n/a

**Code snippets**
n/a

**Additional context**
n/a

P.S. I love Strapi and thanks for your work in advance!

**Comment by derrickmehaffy** [comment]
I agree this really needs to be a thing. The best example I can think of would be something like cars

Parent: "Make" - "Ford"
Child: "Model" - "Mustang"

You shouldn't be able to select "Toyota" - "Mustang"

**Comment by lauriejim** [comment]
Hello @richardevcom .
Thank you for this insight.

Can you please send this to this card - https://portal.productboard.com/strapi/1-public-roadmap/c/9-static-content-types-pages
This feature will answer your need.

**Comment by derrickmehaffy** [comment]
Uhhh @lauriejim I don't think that is what he is asking....

**Comment by derrickmehaffy** [comment]
Here is a demo of what I'm thinking the user means: https://www.sanwebe.com/2013/05/select-box-change-dependent-options-dynamically

@richardevcom can you confirm this is similar to what you are asking for and I can reopen?

**Comment by richardevcom** [comment]
> 
> 
> Here is a demo of what I'm thinking the user means: https://www.sanwebe.com/2013/05/select-box-change-dependent-options-dynamically
> 
> @richardevcom can you confirm this is similar to what you are asking for and I can reopen?

Yes that's exactly what I meant and this is only one of many examples. Basically the idea is to be able define content-type "meta" fields in content builder with conditions, which when met are either shown or hidden in content type edit page.

@lauriejim  that is not exactly what I meant. I will submit this as a new idea soon. Hopefully other will back it up. I would be glad to help testing it out too.

**Comment by richardevcom** [comment]
@derrickmehaffy  @lauriejim I've submitted the idea and I really hope you will consider it as an future update, this could be game changing feature for this already amazing solution.

**Comment by lauriejim** [comment]
Ho okay I see! Thank you for these details.
You did great to submit the idea on the Productboard.
