### ISSUE TITLE
Rich text field preview is empty in Admin UI

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#4640]
**Describe the bug**
When using "Rich text field" in a content type (model) it shows as "-" (hyphen) in a model list page, e.g: "http://localhost:1337/admin/plugins/content-manager/MODEL_NAME?source=content-manager", doesn't matter, if it's empty or not, it will show "-" in a preview anyway.

**Steps to reproduce the behavior**
1. Create a new content type;
2. Add a new field with type "Rich text";
3. Add a new page of created above content type's;
4. Fill your "Rich text" field with some random content;
4. Go to content manager: "http://localhost:1337/admin/plugins/content-manager/ctm-configurations/models";
5. Choose your created content type;
6. Under layout, add your "Rich text" field:
![image](https://user-images.githubusercontent.com/5739191/69954815-6a06ea00-1526-11ea-99b5-bd06dea13c8f.png)
7. Save
8. Go to "http://localhost:1337/admin/plugins/content-manager/MODEL_NAME?source=content-manager" and see "-" (hyphen) instead of a truncated content.

**Expected behavior**
It should display truncated text, just as with normal text field.

**Screenshots**
![image](https://user-images.githubusercontent.com/5739191/69954546-c4ec1180-1525-11ea-9c2f-7fab253aac48.png)

**System**
- Node.js version: v12.10.0
- NPM version: 6.13.1
- Strapi version: Strapi v3.0.0-beta.17.6
- Database: MySQL 5.7
- Operating system: MacOS 10.15.1

**Additional context**
It's related to this issue: https://github.com/strapi/strapi/issues/4303

**Comment by derrickmehaffy** [comment]
@soupette correct me if I'm wrong but this was intended for now wasn't it?

**Comment by soupette** [comment]
Yes it was.

**Comment by derrickmehaffy** [comment]
Alright for now I'm going to mark this as closed then since it was intended, @webcoderkz do feel free to continue the discussion.

**Comment by webcoderkz** [comment]
@soupette can you explain a reason for that?
