### ISSUE TITLE
Cannot update by non-primary-key params

### ISSUE THREAD

**Issue by Froelund** [strapi/strapi#4644]
**Describe the bug**
When trying to update an entity by non-primary-key, knex throws an error.

**Steps to reproduce the behavior**
1. Using bookshelf, postgres connection
2. Create an API called `Report` with fields: name(required, unique string) and status: integer
3. Create an entity with the name of: `andrew`
3. Use the service, and try to update: ```await strapi.services.reports.sync({ name: 'andrew' }, {status:8});```
4. Knex will fail, with something like:
```
Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [report.id] query: select "report".* from "report" where "report"."id" = ? limit ?
    at QueryCompiler_PG.toSQL (/Users/.../reports/node_modules/strapi-hook-knex/node_modules/knex/lib/query/compiler.js:101:13)
    at Builder.toSQL (/Users/.../reports/node_modules/strapi-hook-knex/node_modules/knex/lib/query/builder.js:76:44)
    at /Users/.../reports/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:30:36
```
**Expected behavior**
Should update the entity successfully, as valid params is given.

**System**
- Node.js version: 10.15.1
- NPM version: 6.13.0
- Strapi version: 3.0.0-beta.17.8
- Database: postgres
- Operating system: Mac osx

**Comment by Froelund** [comment]
It seems that `updateRelations` is used with the initial `params` instead of the id of the resolved `entry`.
https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/queries.js#L137

**Comment by lauriejim** [comment]
This issue is kind in the same topic than this one https://github.com/strapi/strapi/issues/4547
