### ISSUE TITLE
post  content-type="application/xml" raw content, ctx.request.body  get null object {}

### ISSUE THREAD

**Issue by igigi** [strapi/strapi#4646]
Describe the bug
post  content-type="application/xml" raw content, ctx.request.body  get null object {}, modify content-type to be "text/plain", it is ok.

Steps to reproduce the behavior

I write a policy to modify ctx.quest.body,

debug it, can't get ctx.quest.body from postman xml content.

modify postman's content-type to be text/plain,retry, can get xml content

Screenshots

Code snippets
`  try {
    console.log(ctx.request.body);
    if (typeof ctx.request.body !== 'string') throw new Error('XMLDataError');
    ctx.request.weixin = await api._parse(ctx.request.body, 'middleware_pay');

  } catch (err) {
    return ctx.reply(err.message);
  }
await next();
`
System

Node.js version: v10.13.0
NPM version: 6.4.1
Strapi version: v3.0.0-beta.17.6
Database: mongo
Operating system: macOS Mojave
Additional context

**Comment by igigi** [comment]
config start file  bootstrap.js with   strapi.config.middleware.settings.parser.includeUnparsed = true;
debug it get { [Symbol(unparsedBody)]: undefined }

**Comment by derrickmehaffy** [comment]
`application/xml` This format isn't currently supported only `application/json` and in certain cases (mainly related to uploads `form-data`)

**Comment by igigi** [comment]
> `application/xml` This format isn't currently supported only `application/json` and in certain cases (mainly related to uploads `form-data`)

can I add xml parser middleware to support it?

**Comment by derrickmehaffy** [comment]
I wouldn't see why not but currently Strapi doesn't support it. For now I'm going to mark this as closed, but please do feel free to create a feature request on the product board if you want. :smile: 

https://portal.productboard.com/strapi/1-public-roadmap/tabs/2-under-consideration/submit-idea

**Comment by gtamas** [comment]
@derrickmehaffy 
Any updates regarding this?
I need Strapi to return XML or JSON response depending on the value of the Accept header.
Is there a plugin for this? If there isn't, what's the best way to implement. middleware?

**Comment by gtamas** [comment]
@derrickmehaffy 
@igigi 
By the way, the ability of parsing XML request body would be important, since it allows much better validation than JSON Schema.

**Comment by derrickmehaffy** [comment]
There is no update on this @gtamas as I don't believe there are any current plans to support xml, though if someone in the community wanted to develop this option I would recommend they post up on the [RFC](https://github.com/strapi/rfcs) repo as some discussion would need to be made about other options as well.
