### ISSUE TITLE
Relation field displayed as record id when used MongoDB

### ISSUE THREAD

**Issue by 4ok** [strapi/strapi#4648]
<img width="529" alt="b1" src="https://user-images.githubusercontent.com/5138012/70087908-d6184980-161d-11ea-939a-e7edc256ad52.png">

<img width="720" alt="b2" src="https://user-images.githubusercontent.com/5138012/70087922-df091b00-161d-11ea-8491-b38e56d32919.png">

<img width="624" alt="b3" src="https://user-images.githubusercontent.com/5138012/70087935-e7615600-161d-11ea-9391-5c985a04347e.png">

------------

Everything is good if is used SQLite

**Comment by zaw-hlaing-bwar** [comment]
I was also using MongoDB and encountered the same issue.
I solved it by

1) You need to go Content Manager
<img width="1439" alt="Screen Shot 2019-12-04 at 15 09 11" src="https://user-images.githubusercontent.com/18108171/70126892-51264200-16a8-11ea-8a74-8c988bc60478.png">

2) Choose the content type and go to edit view

<img width="1439" alt="Screen Shot 2019-12-04 at 15 09 43" src="https://user-images.githubusercontent.com/18108171/70126967-829f0d80-16a8-11ea-872e-e0065a5b17ce.png">

3) Choose the relational field and edit the Entry Title

<img width="1439" alt="Screen Shot 2019-12-04 at 15 10 22" src="https://user-images.githubusercontent.com/18108171/70127023-a2363600-16a8-11ea-8b2d-ed371c9361b7.png">

Hope you got it!

**Comment by derrickmehaffy** [comment]
@zaw-hlaing-bwar you are correct, I'm going to go ahead and close this because an answer was given, and the issue was opened without following a template.

(thank you @zaw-hlaing-bwar )

**Comment by 4ok** [comment]
@zaw-hlaing-bwar, its work, great, thanks!
