### ISSUE TITLE
Multifield Search 

### ISSUE THREAD

**Issue by heavenkiller2018** [strapi/strapi#4649]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
in graphql plugin, the filter " where <field>_contains: Contains. " can only search on one field.  In fact, multifield search is  very necessary!

for example:

the following snippet is from the official website:
query {
  users(limit: 10, start: 10, sort: "username:asc", where: {
    email_contains: "@strapi.io"
  }) {
    username
    email
  }

  }
}

but if  i want to get the results which's  email contain "@strapi.io" and "@strapi.com"?

**Comment by derrickmehaffy** [comment]
Can you please open this as a bug report? (Also code blocks please).

Can can confirm (though not sure if intended) this doesn't work:

![image](https://user-images.githubusercontent.com/8593673/70142148-d3394b00-1655-11ea-8187-7e7e3433e644.png)
