### ISSUE TITLE
How do we "manage the order in your request"?

### ISSUE THREAD

**Issue by strongpauly** [strapi/strapi#4655]
In issue #2166 you state that:

> The best way to manage this is to manage the order in your request - especially if you use GraphQL. You will be able to fetch relations data and define an order for these.

I am uncertain how to do this.  I assume that the syntax for the example given in #2166 would look something like:
```graphql
{
  customer {
      title
      testimonials(sort: "something:asc") {
        title
        content
      }
  }
}
```
However, I am uncertain as to what the sorting column should be to retain the sorting applied in the UI.

Could you provide an example on that issue until it is fixed?

**Describe the bug**
See issue #2166

**Steps to reproduce the behavior**
Follow steps for #2166

**Expected behavior**
As described in #2166

**System**
- Node.js version: v10.17.0
- NPM version: yarn v1.19.2
- Strapi version: 3.0.0-beta.17.5
- Database: Postgres 10.6
- Operating system: macOS

**Additional context**
See #2166

**Comment by derrickmehaffy** [comment]
@strongpauly please don't open new issues related to the same issue. It would be better to add your own information to issue #2166 

Marking as closed for duplicate

**Comment by strongpauly** [comment]
I would have loved to have commented on that issue, but it is locked and I am unable to do so. Hence me opening this duplicate, on which I am able to comment

**Comment by lauriejim** [comment]
Hello! but your query works to sort relations.

| sort desc | sort asc |
| :--------- | :--------- |
| <img width="961" alt="Screenshot 2019-12-05 at 8 18 12 PM" src="https://user-images.githubusercontent.com/5716596/70266332-90ce5600-179c-11ea-81af-92cfd7fe66f3.png"> | <img width="961" alt="Screenshot 2019-12-05 at 8 18 17 PM" src="https://user-images.githubusercontent.com/5716596/70266325-890eb180-179c-11ea-9699-ca5fd076a269.png">|

**Comment by strongpauly** [comment]
Yes, this works if I want to sort by a particular field, but I want the order set in the UI.  Is there any way to specify this in the query?
Is this not possible?   Is this why #2166 is still open?

**Comment by lauriejim** [comment]
Ho yap that s it!
