### ISSUE TITLE
Group doesn't appear on findAll with relations

### ISSUE THREAD

**Issue by Stun3R** [strapi/strapi#4661]
**Describe the bug**
I have 2 content types: Firefighter & Case. I designed them in order to have a relation between them (One-to-One). My Case has 3 Group (BPM, Gyroscope, Accelerometer). When I call the Case endpoint I get everything (Field + Group) as following :
```
#GET /cases
[
    {
        "id": 1,
        "serial": "YD8Y-JX74-ES8R-BGOC",
        "firefighter": {
            "id": 1,
            "serial": "S3GN75HLSF",
            "created_at": "2019-11-28T04:21:40.716Z",
            "updated_at": "2019-11-28T05:01:30.805Z",
            "case": 1
        },
        "created_at": "2019-11-28T04:43:43.140Z",
        "updated_at": "2019-11-28T05:01:30.806Z",
        "BPM": {
            "id": 1,
            "value": 75,
            "alert": false
        },
        "Gyroscope": {
            "id": 1,
            "x": 0,
            "y": 0,
            "z": 0,
            "alert": false
        },
        "Accelerometer": {
            "id": 2,
            "x": 0,
            "y": 0,
            "z": 0,
            "alert": false
        },
        "GPS": {
            "id": 1,
            "longitude": 5.3676044,
            "latitude": 43.3102998
        }
    }
]
```
But when I call the Firefighter endpoint the case object doesn't contain it group and it's very problematic because for my dashboard I must call the firefighter instead of the case.
```
#GET /firefighters
[
    {
        "id": 1,
        "serial": "S3GN75HLSF",
        "created_at": "2019-11-28T04:21:40.716Z",
        "updated_at": "2019-11-28T05:01:30.805Z",
        "case": {
            "id": 1,
            "serial": "YD8Y-JX74-ES8R-BGOC",
            "firefighter": 1,
            "created_at": "2019-11-28T04:43:43.140Z",
            "updated_at": "2019-11-28T05:01:30.806Z"
        }
    }
]
```

**Steps to reproduce the behavior**
1. Go to 'Content Type builder'
2. Create 2 Content Type. One with 3 Group (BPM, Gyroscope, Accelerometer).
3. Set a OneToOne relation between the 2 Content Type
4. Then try to get the content type that has no Group. You'll see that you can't see the Group populate in the relation content type.

**Expected behavior**
Having all Group populate through relation search.

**System**
- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.5
- Database: PostgreSQL
- Operating system: Unix

**Comment by danielocampo2** [comment]
I believe I am having the same issue but with a ContentType instead of a group. Seems to be related.

I have the types Question, Option and Poll. A poll has many questions, and a question has many options.
If I query /questions I get all the questions with all the options.
However, if I query /polls I get all the polls with all the questions but they don't have any options.

@Stun3R is there any way to fix this behavior on our own before the bug is fixed in Strapi?

My strapi version is  v3.0.0-beta.17.8

Thanks.

**Comment by lauriejim** [comment]
Hello @danielocampo2 ! Looks to be a different issue, can you create a new one please.

**Comment by alexandrebodin** [comment]
HI @Stun3R This issue has been fixed since beta.18. Closing this issue.

If you still have issue after migration let us know ;)
