### ISSUE TITLE
Can't use the same GraphQL query variable in 2 different query

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4662]
**Describe the bug**

Reference from https://github.com/strapi/strapi/issues/4280#issuecomment-561102731

**Steps to reproduce the behavior**

Check this queries. Whitespace issue?

<img width="1215" alt="Screenshot 2019-12-03 at 11 24 52" src="https://user-images.githubusercontent.com/1007051/70042759-bb16ec80-15bf-11ea-8add-284442923e46.png">
<img width="1215" alt="Screenshot 2019-12-03 at 11 26 50" src="https://user-images.githubusercontent.com/1007051/70042820-d5e96100-15bf-11ea-92fd-f6893eed33e6.png">
<img width="1215" alt="Screenshot 2019-12-03 at 11 25 29" src="https://user-images.githubusercontent.com/1007051/70042761-bbaf8300-15bf-11ea-8f15-8e26153b3f1b.png">

**System**
- Node.js version: `v10`
- NPM version: `v6`
- Strapi version: `v3.0.0-beta.17.8`
- Database: MongoDB
- Operating system: macOS

**Comment by lauriejim** [comment]
Hello @abdonrd !
I just tried with a fresh new app and it works well on my side.
[Here](https://www.loom.com/share/e041745261a741ff8c9ed56ac5277ab9) is a record of what I did.
And I still have the competitions with your request 🤔

**Comment by abdonrd** [comment]
@lauriejim Try with the variables:

```graphql
query GetExploreData($where: JSON) {
  competitions(where: $where) {
    slug
    name
  }
  users(where: $where) {
    username
    name
  }
}

```

```json
{
  "where": {
    "name_contains": "red bull"
  }
}
```

**Comment by lauriejim** [comment]
Okay got it. In fact, the issue is because a query params can't be used for 2 or more queries.

**Comment by alexandrebodin** [comment]
@abdonrd Would be great if you could try this PR out ;) https://github.com/strapi/strapi/pull/5109
