### ISSUE TITLE
Infinite loading when creating entry after updating relationed model

### ISSUE THREAD

**Issue by Kelayn** [strapi/strapi#4666]
**Describe the bug**
Creating of a new entry of a model with relations in GUI, after updating any of its relationed model (I guess), causes infinite loading of "create new entry" menu.
Also,  clicking of  "edit the fields" causes "Cannot read property 'getIn' of undefined" error to appear.

**Steps to reproduce the behavior**
1. Create model A
2. Create model B and make any relationship between A and B
3. Change A
4. Try to create new entry of A
5. See the error

**Expected behavior**
Being able to create new entry, see fields to enter.

**Screenshots**
![image](https://user-images.githubusercontent.com/31416046/70319610-c07c6d00-1833-11ea-94e8-b7224237e3a2.png)

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: MongoDB
- Operating system: Ubuntu 16.04

**Additional context**
Well, I usually get this problem and solve it by removing all the relations from the "frozen" model and returning them back, but getting this error not in development mode is quite annoying, because I have no ability to change my models. Maybe the reason of this bug isn't what I described, though I get it this way.
Would appreciate any possible help, maybe could solve it by myself if the root of the problem is tracked.
Thank you.

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-beta.15` please test on the latest version (beta.17.8) The issue you are describing was fixed back in beta.16

**Comment by Kelayn** [comment]
@derrickmehaffy 
Thank you so much for quick response.

 I upgraded my strapi versions (both local and global) to beta.17.8 and now I can't even start a server :)
Though the problem now differs, it says "strapi.models.core_store.forge is not a function". Yet, it doesn't refer to https://github.com/strapi/strapi/issues/3184.

![image](https://user-images.githubusercontent.com/31416046/70321552-a4c79580-1838-11ea-955e-9589e48e6215.png)

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/

**Comment by Kelayn** [comment]
God, I love you so much. Thank you for your effort!
