### ISSUE TITLE
Error: Cannot find module 'strapi-utils'

### ISSUE THREAD

**Issue by marineb** [strapi/strapi#4672]
Here is the full error I get : 

```
$ strapi
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'strapi-utils'
Require stack:
- /usr/local/lib/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/strapi/bin/strapi.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/strapi/bin/strapi.js' ]
}
```

Meanwhile this is what my package.json file looks like
I have tried a `rm -rf node_modules`. 

```
  "dependencies": {
    "@hapi/cryptiles": "^4.2.1",
    "jquery": "^1.9.1",
    "knex": "^0.17.0",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.17.8",
    "strapi-admin": "3.0.0-beta.17.8",
    "strapi-hook-bookshelf": "3.0.0-beta.17.8",
    "strapi-hook-knex": "3.0.0-beta.17.8",
    "strapi-plugin-content-manager": "3.0.0-beta.17.8",
    "strapi-plugin-content-type-builder": "3.0.0-beta.17.8",
    "strapi-plugin-email": "3.0.0-beta.17.8",
    "strapi-plugin-upload": "3.0.0-beta.17.8",
    "strapi-plugin-users-permissions": "3.0.0-beta.17.8",
    "strapi-utils": "^3.0.0-beta.17.8",
    "tunnel-agent": "^0.6.0"
  },
```

Thanks for your help!

**Comment by marineb** [comment]
I uninstalled strapi globally and reinstalled it using `yarn global add strapi@3.0.0-beta.17.8`. All good now.

**Comment by TheRealBarenziah** [comment]
In case marineb or anybody else reads this: installing Strapi globally is not recommended anymore.  

Please either use `yarn create strapi-app` or 'npx create-strapi-app` (cf [Quick start guide](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project) )

**Comment by billhennessy** [comment]
I ran into the same problem. So I tried creating a brand new Strapi instance with `yarn create strapi-app`. The new site also generates `Error: Cannot find module 'strapi-utils'`

**Comment by sebastianjung** [comment]
same for me. Fresh install on strapi v3.0.0-beta.18.3.

Updated update controller function to following:
`async update(ctx) {
    let entity;
    if (ctx.is('multipart')) {
      const { data, files } = parseMultipartData(ctx);
      entity = await strapi.services.product.update(ctx.params, data, { files });
    } else {
      entity = await strapi.services.product.update(ctx.params, ctx.request.body);
    }

    console.log('updated lul')

    return sanitizeEntity(entity, { model: strapi.models.product });
  },`

leads to error in console:

Cannot find module 'strapi-utils'

Any help would be very much appreciated!

**Comment by sebastianjung** [comment]
Somehow the strapi-utils folder seems corrupted:
![image](https://user-images.githubusercontent.com/17472892/72154698-96c5e100-33b1-11ea-8521-104a54314598.png)

`npm i strapi-utils` fixed it for me

**Comment by gabrilator** [comment]
Same here! any solutions to this?

**Comment by lauriejim** [comment]
Hello, make sure your application is up to date with package versions.
Follow migration guides in the docs if necessary for app migration.
Then clean your npm cache and install node modules.
That should resolve your issue.
