### ISSUE TITLE
Receive “application/json” data

### ISSUE THREAD

**Issue by alsozx** [strapi/strapi#4676]
**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
@alsozx you need to actually fill out the template or provide some kind of context. Closing
