### ISSUE TITLE
receive “application/json” data

### ISSUE THREAD

**Issue by alsozx** [strapi/strapi#4677]
**Describe the bug**
Handle data whose "POST" request header is content-type :"application/json", ctx.req.on('data') is not executed

**Steps to reproduce the behavior**

**Expected behavior**
can receive content-type :"application/json" data

**Screenshots**
![image](https://user-images.githubusercontent.com/22681246/70374915-0ec46580-1933-11ea-95dc-4596e4e34b8a.png)
.

**Code snippets**
const getData = async(ctx) => {
                console.log('2222')
                return new Promise((resolve, reject) => {
                    // console.log(ctx.req)
                    let str='';
                    ctx.req.on('data',function(chunk){
                        console.log('3333')
                        str += chunk;
                    })
                    ctx.req.on('error',function(chunk){
                        console.log(chunk)
                        
                    })
                
                    ctx.req.on('end',function(chunk){
                        console.log('4444')
                        resolve(JSON.parse(str))
                    })
                });
            }

**System**
- Node.js version: v12.13.0
- NPM version:6.12.0
- Strapi version: 3.0.0-beta.17.5
- Database: mysql
- Operating system: windows

**Additional context**

**Comment by derrickmehaffy** [comment]
Can you explain what you are trying to do?

**Comment by alsozx** [comment]
![image](https://user-images.githubusercontent.com/22681246/70374959-d4a79380-1933-11ea-9639-71b94b2fd53b.png)

**Comment by alsozx** [comment]
![image](https://user-images.githubusercontent.com/22681246/70375040-79c26c00-1934-11ea-971b-2258b8fd3d2e.png)

**Comment by alsozx** [comment]
![image](https://user-images.githubusercontent.com/22681246/70375051-8c3ca580-1934-11ea-8259-11795422eff0.png)

**Comment by derrickmehaffy** [comment]
@alsozx Please type out what you are trying to do, your pictures are not helping.

**Comment by lauriejim** [comment]
Hello @alsozx !

You already created 3 other issues with the same topic.
Can you please take time to explain clearly your issue. And also take time to well format your issue.

Here is not readable.

If you don't respect my indication I will have to block you from Strapi GitHub.
https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md
