### ISSUE TITLE
Unable to retrieve data from a POST request in a custom controller

### ISSUE THREAD

**Issue by TotomInc** [strapi/strapi#4679]
**Describe the bug**
I am unable to retrieve data sent from a POST request in a custom controller.

**Steps to reproduce the behavior**
1. Browser send a simple POST request (using Axios in the example)
   ```js
   axios.post('http://localhost:1337/payment/checkout', {
     nonce: 'fake-valid-nonce',
   });
   ```
2. Custom controller function that receives the POST request doesn't contain the data sent:
   ```js
   checkout: async (ctx) => {
     // `ctx.request` doesn't contain any data sent in the POST request,
     // see screenshot.
     console.log(ctx.request);

     ctx.send('temporary successfull');
   }
   ```
3. Properly route the controllers from the module:
   ```json
	{
	  "routes": [
	    {
	      "method": "POST",
	      "path": "/payment/checkout",
	      "handler": "Payment.checkout",
	      "config": {
	        "policies": []
	      }
	    }
	  ]
	}
   ```

**Expected behavior**
I expect to have at least a `data` (or something similar) object in my `ctx.request` in order to retrieve all the data sent from the browser in the POST request.

**Screenshots**
![image](https://user-images.githubusercontent.com/9285210/70387069-e6735000-19a0-11ea-8db2-d5beee4032cd.png)

**Code snippets**
See **Steps to reproduce the behavior**.

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.8
- Database: Mongo
- Operating system: MacOS Catalina 10.15.1

**Additional context**
I tried to do the request using the native `fetch` browser API and sending a `FormData`, without success.

I have also played with the `parseMultipartData` strapi-utils which cause this error: `When using multipart/form-data you need to provide your data in a JSON 'data' field.`

I may have ommited an essential step, which leads to the creation of this issue, because I find it really annoying that there isn't a special section with examples to help new Strapi users to properly send/fetch data.

**Comment by derrickmehaffy** [comment]
`console.log(ctx.request.body)` I think? Not near my computer to look atm. But right now unless you are sending files to the upload service all other requests need to be in the `application/json` (with axios you may need to actually send the content-type header)

**Comment by TotomInc** [comment]
Thanks for the help, it works fine.

First time I'm using koajs and I find it strange to not see the `body` object even if I have `console.log` the request object.

**Comment by derrickmehaffy** [comment]
Yeah I'm not quite sure of the reason, maybe @alexandrebodin or @lauriejim can add some context (pun intended) here.

**Comment by Anmol99999** [comment]
@TotomInc Can you please Tell if your issue is resolved as I am currently facing the same issue ?

**Comment by derrickmehaffy** [comment]
> Thanks for the help, it works fine.
> 
> First time I'm using koajs and I find it strange to not see the `body` object even if I have `console.log` the request object.

It's a javascript prototype thing that I don't fully understand myself. Basically if you don't log it exclusively "it doesn't exist"

**Comment by srinidhi-s-dev** [comment]
yes I'm using strapi v5,and i wanted to create entries into strapi ,with excel file by sending data as form-data with file (key name)in body. To read the data from excel i used xlsx lib, if i log the request there is no body /data.If i log the  ctx.request.body im getting raw/json which is not feasible to parse the data. Need a help  @derrickmehaffy for creating a post request in strapi through files in documentation or relevant blog would be much helpful.
when i log the ctx.request.body its coming in raw/json
