### ISSUE TITLE
 UnhandledPromiseRejectionWarning on "strapi new"

### ISSUE THREAD

**Issue by kevinskyba** [strapi/strapi#468]
Hey,

when I run the following, I get the said issue. I'm not able to create a new proejct on my setup.

> H:\Path\To\Project>strapi new project
INFO (18316 on PC): Creating your application... It might take a few seconds.
INFO (18316 on PC): Lets configurate the connection to your database:
 Choose your main database: MongoDB (highly recommended)
 Database name: project
 Host: localhost
 Port: 27017
 Username:
 Password:
INFO (18316 on PC): Testing database connection...
Der Befehl "rm" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
(node:18316) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: rm -r H:\Path\To\Project\project
Der Befehl "rm" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Node.js version**: v6.12.3
**npm version**: 3.10.10
**Strapi version**: 3.0.0-alpha.8
**Operating system**: Win 10

**Comment by Nsbx** [comment]
Same problem, i think we need to create condition to execute different command over OS detected
I found usage here : https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/before.js
Line : 210

**Comment by John0x** [comment]
is this already published?
I have the same problem using the newest alpha version from npm
