### ISSUE TITLE
Default where clause with multi params value

### ISSUE THREAD

**Issue by Chrisstar56** [strapi/strapi#4680]
**Describe the bug**
I have a blogpost model, as well as a category model. Each post can have multiple categories. So I want to only display posts which have, let's say, the categories 1 and 5. But instead, it returns me all posts which have either of them (not necessarily both). I think this is the expected behavior of _in but not "exact".

**Steps to reproduce the behavior**
This is the query I am using:
```
blogposts(where: { categories: { id: [1, 5] } }) {
...
}
```
It behaves the same as:
```
blogposts(where: { categories: { id_in: [1, 5] } }) {
...
}
```

**Expected behavior**
Only blogposts which have both categories (1 and 5) will be returned.

**Screenshots**
![Screenshot_2019-12-08 Playground - http localhost 1337 graphql](https://user-images.githubusercontent.com/18631757/70396862-16583d00-1a0d-11ea-8266-dc26a071bbcd.png)
As you can clearly see, the value

**System**
- Node.js version: 10.15.3
- Strapi version: Should be latest
- Database: SQLite (standard installation, I didn't change anything)
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi @Chrisstar56,

using an array is simply a shortcut to the id_in for sure as it wouldn't make sense to search categories that have id = 2 & id = 5. 

If I understand well what you want is a new feature to specify relation with a `some` match or `every` match filter. like:

```graphql
blogposts(where: { categories_every: { id: [1, 5] } }) {
...
}
```

Does that make sense to you ?

**Comment by lauriejim** [comment]
Since we have no more detail on this discussion, I'm closing it.
Can also be related to the "filter OR" issue.
