### ISSUE TITLE
Strapi admin page not running

### ISSUE THREAD

**Issue by syedsimanta03** [strapi/strapi#4683]
**Describe the bug**

**Steps to reproduce the behavior**
Just run npm start develop

**Expected behavior**
It should run admin page
**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.13
- NPM version: 6.x
- Strapi version: latest npx
- Database: mdb
- Operating system: win10 - 64bit

**Additional context**
***all dependencies are very old***

**Comment by derrickmehaffy** [comment]
Please properly fill out the bug report template.

As for the depends problem it comes from Grant/Purest.

Marking as closed as this is not a proper bug report.
