### ISSUE TITLE
When using a field that has a hyphen it gives an error saying the field is not correct

### ISSUE THREAD

**Issue by codeHatcher** [strapi/strapi#4684]
**Describe the bug**
When using a field that has a hyphen it gives an error saying the field is not correct

**Steps to reproduce the behavior**
1. Go to 'where to create a field for a new content type'
2. Click on 'add another field, string'
3. Add a name that includes a hypen such as 'trial-title'
4. See error 'Name should start with alphabetical characters. Underscores and numbers only are allowed after.'

**Expected behavior**
I do not expect an error since my text follows the rules of the error

**Screenshots**
![strapierrorspace](https://user-images.githubusercontent.com/5360982/70421277-2fdfa000-1a72-11ea-9035-e31841031396.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.8
- Database: mongodb
- Operating system: ubuntu 18

**Additional context**

**Comment by codeHatcher** [comment]
recreated same error with node v10

$ strapi develop

```
 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Mon Dec 09 2019 08:58:55 GMT+0000 (Coordinated … │
│ Launched in        │ 1477 ms                                          │
│ Environment        │ development                                      │
│ Process PID        │ 5474                                             │
│ Version            │ 3.0.0-beta.17.8 (node v10.17.0)    
```

**Comment by lauriejim** [comment]
Hello @codeHatcher !

Your name doesn't respect the rule.
You are using a dash instead of an underscore.
As said in the message.

So all works fin in this case.

**Comment by codeHatcher** [comment]
got it, thank you! It's kind of confusing the way it is written
