### ISSUE TITLE
GraphQL BUG: strapi query 100 times the same data

### ISSUE THREAD

**Issue by matan335** [strapi/strapi#4689]
It seems like strapi duplicating data, 
in the database I have only one item with the id 5d5107598972e70a628f9878

but when I query the data Ive got back an array of 100 items all of them are duplicated of the 5d5107598972e70a628f9878 id and has the same properites

this slows down my application very much please help me through it 

System:

- Node.js version: 10.0.0
- Strapi version: Should be latest
-oprating system: macos

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
Please properly follow the template and fill it out properly with all specific versions. "Latest" is not a version.
