### ISSUE TITLE
Windows 10 strapi develop or strat commands not working

### ISSUE THREAD

**Issue by syedsimanta03** [strapi/strapi#4691]
Describe the bug
I'm unable to build Strapi admin with latest version npx 

Steps to reproduce the behavior

Go to strapi folder
npm install
strapi build
See error
Expected behavior
The build would have been successful

System

Node.js version: 10.16.3
NPM version: 6.9.0
Strapi version: latest npx
Strapi plugin settings manager: 3.0.0-beta.17.3
Database: sqlite
Operating system: Windows

**Comment by derrickmehaffy** [comment]
@syedsimanta03 please test with the latest version as of strapi beta 17.4 the settings manager is depreciated.

If you are using the npx create command it should be installing the latest (beta.17.8)

**Comment by derrickmehaffy** [comment]
Just tested on Windows 10 and worked perfectly:

![image](https://user-images.githubusercontent.com/8593673/70497906-ecb51980-1ad1-11ea-9973-c14e20848252.png)
