### ISSUE TITLE
GraphQL BUG: query returns the same data multiplied

### ISSUE THREAD

**Issue by matan335** [strapi/strapi#4692]
Calling a GraphQL query return an array of 100 items all of the same data

this makes the request way slower than it should please help 

**System:**

1.  Operating: macos
2.  Strapi: most updated version
3. Node: 10.0.0

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

Can you please add more details, what is you GraphQL query, what your model look likes.
Thank you.
