### ISSUE TITLE
 Redirection url for account confirmation is not working

### ISSUE THREAD

**Issue by mikekoro** [strapi/strapi#4700]
... or I am completely missing the point;)

**Describe the bug**

`Redirection url` under Roles & Permissions > Advanced settings is set to my custom URL http://localhost:3000/activate however whenever I create a new user this URL is being sent

http://localhost:1337/auth/email-confirmation/%%CODE%%

which leads to `{"statusCode":404,"error":"Not Found","message":"Not Found"}`

Also, the Email Address Confirmation template has this URL - <p><%= URL %>/<%= CODE %></p>

**Expected behavior**

I guess the URL I have in my template should be sent? Or get me redirect from http://localhost:1337/auth/email-confirmation/%%CODE%% to http://localhost:3000/activate/%%CODE%%

**Screenshots**

S1
<img width="691" alt="Screenshot 2019-12-10 18 13 54" src="https://user-images.githubusercontent.com/2127545/70577255-e168f900-1b78-11ea-9078-cb563c30bce3.png">

S2
<img width="456" alt="Screenshot 2019-12-10 18 14 39" src="https://user-images.githubusercontent.com/2127545/70577280-f34a9c00-1b78-11ea-92af-a31af535c926.png">

S3
<img width="597" alt="Screenshot 2019-12-10 18 15 07" src="https://user-images.githubusercontent.com/2127545/70577308-03fb1200-1b79-11ea-8b15-56b6f27f0e3f.png">

S4
<img width="602" alt="Screenshot 2019-12-10 18 21 56" src="https://user-images.githubusercontent.com/2127545/70577824-014cec80-1b7a-11ea-9b3c-aff0002fe083.png">

**System**
- Node.js version: v12.11.1
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.7
- Database: Mongo
- Operating system: Mac OS X

**Comment by lauriejim** [comment]
Hello! I will explain to you how the process works.

If you activate the `Email confirmation` option, when a new user is created, it sent an email to this new user.

The email content sent is configurable in **Roles & Permissions** > **Email templates** > **Email Address Confirmation**

`<p><%= URL %>?confirmation=<%= CODE %></p>` Here is the URL you will receive.
Templated it will look like that `http://localhost:1337/auth/email-confirmation?confirmation=blablabla`
[Here is the code](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L532)

Then when you visit this URL, it confirm the user account and redirect to the `Redirection URL` you set.

**Comment by mikekoro** [comment]
@lauriejim Is there any way to intercept that email? I'd like to use Sendgrid's transactional emails for that.

**Comment by lauriejim** [comment]
You will have to customize your application by following the [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html)

You will find [many guides](https://strapi.io/documentation/3.0.0-beta.x/guides/api-token.html) that customize plugins.
Find in the code where the action is called. And customize the code to match your need.

**Comment by mikekoro** [comment]
> You will have to customize your application by following the [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html)
> 
> You will find [many guides](https://strapi.io/documentation/3.0.0-beta.x/guides/api-token.html) that customize plugins.
> Find in the code where the action is called. And customize the code to match your need.

Thanks @lauriejim 

So the docs say:

_controllers: You can extend the plugin's controllers by creating controllers with the same names and override certain methods

What I did:

1. created `extensions/users-permissions/controllers/User.js`. It matches the [plugin](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/User.js#L84)

```
module.exports = {

    async create(ctx) {

        console.log("I am hit!", ctx)

    },

};
```

But I am not getting "I am hit" It just creates a new user as usual.

Could you please point me in the right direction?

**Comment by CSituma** [comment]
First of all,
Good job 

You guys are doing amazing work!!
Maybe someday i may join the team :)

So I know this is closed but I'm experiencing the exact same predicament.

Everything seems to be working fine BUT the redirect (which I have set as my nextjs sign-in page)

So i do get a confirmation link In my mail
(contains the strapi URL,confirmation code and message )
When I click it takes me to that URL ,it confirms my email but it doesn't redirect

So all I get it " Not found"
