### ISSUE TITLE
STRAPI  build error

### ISSUE THREAD

**Issue by syedsimanta03** [strapi/strapi#4701]
Just run npx command on windows  10 , Node v10

> cwebp-bin@5.1.0 postinstall C:\Users\Sam\Desktop\Node\my-project\node_modules\cwebp-bin
> node lib/install.js

  ‼ connect ETIMEDOUT 151.101.0.133:443
  ‼ cwebp pre-build test failed
  i compiling from source
  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "./configure --disable-shared --prefix="C:\Users\Sam\Desktop\Node\my-project\node_modules\cwebp-bin\vendor" --bindir="C:\Users\Sam\Desktop\Node\my-project\node_modules\cwebp-bin\vendor""
'.' is not recognized as an internal or external command,
operable program or batch file.

    at Promise.all.then.arr (C:\Users\Sam\Desktop\Node\my-project\node_modules\bin-build\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by derrickmehaffy** [comment]
Closing, duplicate: https://github.com/strapi/strapi/issues/4691
