### ISSUE TITLE
Strapi/MySQL exits after renaming a field changing case only

### ISSUE THREAD

**Issue by acdhirr** [strapi/strapi#4706]
**Describe the bug**

Renaming a field for a Content Type in the Content Type Builder causes the application to exit with an error when only the case of the name changes. 

This happens when for instance you rename 'summary' to 'Summary'. 
Renaming to 'Summery' does not result in an error.

*How to recover from this bug:*

You have to set the field name to its old value in the file `app/api/[typename]/models/[typename].settings.json` in order to get the application up again.

**Steps to reproduce the behavior**

- Create a content type 'Page'
- Add a field 'summary'    
- Save the content type
- Edit field 'summary' and rename to 'Summary'
- Save the content type again
 
Strapi will exit with message
    
    [2019-12-11T15:29:05.973Z] error Error: ER_DUP_FIELDNAME: Duplicate column name 'Summary'

**Expected behavior**

Either apply the change without error or inform the user that such a change is not possible. 

**Screenshots**

![Screenshot_2019-12-11 Strapi - Content Type Builder](https://user-images.githubusercontent.com/28700785/70638610-7af7df80-1c39-11ea-98ff-315102d5b2d9.png)

**System**

- Node.js version: v12.13.0
- Strapi version: 3.0.0-beta.17.8
- Database: MySQL
- Operating system: Ubuntu 18.04.3 LTS

**Additional context**

I use the latest strapi/strapi Docker image (dec 11th 2019)

Here's a full trace:

strapi    | [2019-12-11T14:34:31.264Z] error Impossible to register the 'page' model.  
strapi    | [2019-12-11T14:34:31.265Z] error Error: ER_DUP_FIELDNAME: Duplicate column name 'Summary'  
strapi    |     at Query.Sequence._packetToError (/srv/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)  
strapi    |     at Query.ErrorPacket (/srv/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)  
strapi    |     at Protocol._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)  
strapi    |     at Parser._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Parser.js:433:10)  
strapi    |     at Parser.write (/srv/app/node_modules/mysql/lib/protocol/Parser.js:43:10)  
strapi    |     at Protocol.write (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)  
strapi    |     at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:91:28)  
strapi    |     at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:525:10)  
strapi    |     at Socket.emit (events.js:210:5)  
strapi    |     at addChunk (_stream_readable.js:308:12)  
strapi    |     at readableAddChunk (_stream_readable.js:289:11)  
strapi    |     at Socket.Readable.push (_stream_readable.js:223:10)  
strapi    |     at TCP.onStreamRead (internal/stream_base_commons.js:182:23)  
strapi    |     --------------------  
strapi    |     at Protocol._enqueue (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)  
strapi    |     at Connection.query (/srv/app/node_modules/mysql/lib/Connection.js:201:25)  
strapi    |     at /srv/app/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/mysql/index.js:130:18  
strapi    |     at Promise._execute (/srv/app/node_modules/bluebird/js/release/debuggability.js:384:9)  
strapi    |     at Promise._resolveFromExecutor (/srv/app/node_modules/bluebird/js/release/promise.js:518:18)  
strapi    |     at new Promise (/srv/app/node_modules/bluebird/js/release/promise.js:103:10)  
strapi    |     at Client_MySQL._query (/srv/app/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/mysql/index.js:124:12)  
strapi    |     at Client_MySQL.query (/srv/app/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:158:17)  
strapi    |     at Runner.query (/srv/app/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:135:36)  
strapi    |     at Runner.queryArray (/srv/app/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:224:14)  
strapi    |     at /srv/app/node_modules/strapi-hook-knex/node_modules/knex/lib/runner.js:37:25  
strapi    |     at tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)  
strapi    |     at /srv/app/node_modules/bluebird/js/release/using.js:185:26  
strapi    |     at tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)  
strapi    |     at Promise._settlePromiseFromHandler (/srv/app/node_modules/bluebird/js/release/promise.js:547:31)  
strapi    |     at Promise._settlePromise (/srv/app/node_modules/bluebird/js/release/promise.js:604:18)  
strapi    |     at Promise._settlePromise0 (/srv/app/node_modules/bluebird/js/release/promise.js:649:10)  
strapi    |     at Promise._settlePromises (/srv/app/node_modules/bluebird/js/release/promise.js:729:18)  
strapi    |     at Promise._fulfill (/srv/app/node_modules/bluebird/js/release/promise.js:673:18)  
strapi    |     at PromiseArray._resolve (/srv/app/node_modules/bluebird/js/release/promise_array.js:127:19)  
strapi    |     at PromiseArray._promiseFulfilled (/srv/app/node_modules/bluebird/js/release/promise_array.js:145:14)  
strapi    |     at Promise._settlePromise (/srv/app/node_modules/bluebird/js/release/promise.js:609:26)

**Comment by acdhirr** [comment]
I just noticed that when you delete a field in the Content Type Builder, the field still lives on in the database. I use the MySQL Docker version, which I forgot to mention.

**Comment by acdhirr** [comment]
I installed strapi with mongo and the bug is gone. So I changed the title to include MySQL.

**Comment by lauriejim** [comment]
Hello! Here is a full topic about this.
https://github.com/strapi/strapi/issues/1114
