### ISSUE TITLE
Option to disable the REST API

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4708]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

I would like to propose and option to disable the HTTP API.
Why? Because we only use the GraphQL API.

**Comment by derrickmehaffy** [comment]
Temporary workaround: Delete the routes.json for the models you don't need REST on.

**Comment by ChristianHeimke** [comment]
A better option is to remove the paths you don't need from the `routes.json` of each module and keep it as empty json file like:

```
{
  "routes": [

  ]
}
```

An option to disable / override a core module is currently not possible according to the strapi documentation:
> The following middlewares cannot be disabled: responses, router, logger and boom.
(https://strapi.io/documentation/v3.x/concepts/middlewares.html#core-middleware-configurations)

I tried it with different approaches without success and I think keeping the `routes.json` as empty array is a better option to keep the strapi-structure alive.

**Comment by irtzamazhar** [comment]
What about the policies if we add any policy in routes then how can we use that one in GraphQL?

**Comment by ChristianHeimke** [comment]
you need to implement a custom resolver and pass the policy to it: 

* https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#customize-the-graphql-schema
* https://forum.strapi.io/t/sharing-context-ctx-between-middleware-and-policies-and-controllers-6692/1771/2
* some parts of #1887 might be helpful

**Comment by derrickmehaffy** [comment]
Since REST is our core communication API we can't just disable it. There are options now within the v4 to disable routes on each content-type but we won't do this globally.

**Comment by abdonrd** [comment]
> 

How to do it? Thanks!

**Comment by saintego** [comment]
But disabling rest api route disable also same graphql query/mutation

**Comment by chrisbakr** [comment]
I was in the same need of blocking the default API and did it with a global middleware. Haven't tested it thoroughly but it seems to be doing what we want without breaking anything:

`
module.exports = (config, { strapi })=> {
    return async (ctx, next) => {
        const endpoint = ctx.request.url.split('/')[1];
        
        if(endpoint == 'api') {
            return ctx.unauthorized("This action is unauthorized.");
        }

        return next();
    };
  };`

**Comment by derrickmehaffy** [comment]
We don't have GraphQL options for everything so you would have some moving functionality.

Also just a reminder here, REST is and will remain our default and will get updates and improvements first, GQL is not promised the same.
