### ISSUE TITLE
Underscore still being removed from column name in api generator

### ISSUE THREAD

**Issue by asadakbar** [strapi/strapi#4709]
**Describe the bug**
When I run ```strapi generate:api thing thing_name:string```, the underscore is dropped and replaced with a space in the Thing.settings.json file and the column is generated with the name "thing name" instead of "thing_name". I saw that there was a fix merged in for this here https://github.com/strapi/strapi/pull/3590, however it is still happening on version v3.0.0-beta.17.8. It could be specific to postgres, that's the db I am running.  The pr only mentioned testing on mongo and mysql.

**Steps to reproduce the behavior**
1. Generate a new strapi app with postgres as your db.
2. Run ```strapi generate:api thing thing_name:string```
3. Take a look at the Thing.settings.json file to see the attribute name with a space instead of the underscore.
4. Take a look at the db column created with a space instead of the underscore.

**Expected behavior**
I expected the column name to have the underscore the way I stated in the cli generate:api command.

**Screenshots**

**Code snippets**

**System**
- Node.js version: v12.1.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.17.8
- Database: Postgres
- Operating system: OSX Mojave

**Additional context**

**Comment by lauriejim** [comment]
Hello! I just tried and it works well https://www.loom.com/share/a253c4a69264421d81b2a26ff678b898
