### ISSUE TITLE
MySQL adding/forcing underscores to things?

### ISSUE THREAD

**Issue by fortydegrees** [strapi/strapi#4713]
I had strapi working fine after the quickstart with SQLite. However, like many others I realised too late that there's no easy way to change to a real database when you want to finish testing and actually deploy. 

So in switching to MySQL I started a new strapi project from scratch. Upon recreating my table structure identically, I'm running into a lot of issues.

One was to do with uploading images while creating a record. This was working fine with SQLite but failed with MySQL. I managed to find a workaround as mentioned here: https://github.com/strapi/strapi/issues/1919 but would still consider it a bug.

Now, I'm trying to add records via POST API, but it keeps failing. Not only this but also when trying to view records/tables, I get errors. I haven't change anything under the hood. The error I get on posting/creating a new record is: error Error: ER_BAD_FIELD_ERROR: Unknown column 'sports.team_id' in 'where clause'

which is obviously linked to relationships of some kind. The same error happens when I try and view the record.

I don't know where the underscored team_id has come from. I have labelled some fields that I created like idTeam, but have no clue where or how this transform is happening, or how to fix it. I'm worried that renaming all my columns in my database would mess other things up?
Does strapi properly work with MySQL?

**Comment by fortydegrees** [comment]
I think this issue was due to a missing relationship on one of the tables.

The API/POST issue still exists, which massively slows down the time it takes to upload thousands of records

**Comment by lauriejim** [comment]
Hello! Can you please share with me your application.
With the issue content you sent, I'm not able to understand where is the issue.
I'm not able to reproduce anything.
And can you please follow the issue template.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
