### ISSUE TITLE
When in a relation, user's sensitive data should be masked

### ISSUE THREAD

**Issue by kevinskyba** [strapi/strapi#472]
By default, for privacy and security reasons, private user data should be masked when user is in a relation with another content-type.

**Behaviour:**
```
GET localhost:1337/custom

 {
        "_id": "...",
        "__v": 0,
        "owner": {
            "_id": "...",
            "username": "admin",
            "password": "...",
            "email": "...",
            "provider": "...",
            "role": 0,
            "__v": 0,
            "id": "..."
        },
        "id": "..."
    }

```

**Expected:**

```
GET localhost:1337/custom

 {
        "_id": "...",
        "__v": 0,
        "owner": {
            "_id": "...",
            "username": "admin",
            "__v": 0,
            "id": "..."
        },
        "id": "..."
    }

```

**In my opinion this should be the default case for any query on any user object, if the authenticated user itself is not requesting it.**

**Strapi version**: 3.0.0-alpha.8

**Comment by Aurelsicoko** [comment]
@kevinskyba You're totally right! We should hide sensitive data coming from User model. We will fix the issue in the next release.

**Comment by mikedevita** [comment]
@kevinskyba I think no matter what the password field should be stripped from the json response directly. In what scenario would you need to know the hash of the users password other than during login? I am very new to strapi@alpha but I am trying to dig into this right now.

**Comment by Aurelsicoko** [comment]
@mikedevita It has been fixed. We introduced a new property `private` in the models that allows you to hide model's attributes from the server responses.
