### ISSUE TITLE
Strapi raw body to comply with Stripe constructEvent

### ISSUE THREAD

**Issue by lambertkevin** [strapi/strapi#4720]
**Describe the bug**
As I was playing with the [Stripe webhooks api](https://stripe.com/docs/api/webhook_endpoints), it appears that I can't use the ```constructEvent``` method because I can't get the raw request body from strapi. A similar issue existed with Express and was resolved by using ```body-parser``` middleware but I can't figure out the strapi equivalent.

**Steps to reproduce the behavior**
1. Install the [stripe cli](https://stripe.com/docs/stripe-cli)
2. Create a simple hook in you strapi app
3. Start forwarding to your strapi app the events from the stripe-cli (eg: ```stripe listen --forward-to localhost:1337/hook```)
4. Launch an event with your stripe cli (e.g.: ```stripe trigger payment_intent.created```)
4. See error (``` Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing```

**Expected behavior**
I should be able to get a correct ```constructEvent``` result by parsing the body of my request.

**Screenshots**
<img width="754" alt="Screen Shot 2019-12-13 at 02 52 18" src="https://user-images.githubusercontent.com/44363395/70763249-c7cfd900-1d53-11ea-88dc-c8fce216d433.png">
<img width="894" alt="Screen Shot 2019-12-13 at 02 51 56" src="https://user-images.githubusercontent.com/44363395/70763256-cd2d2380-1d53-11ea-9469-87f9003b51aa.png">

**Code snippets**
My hook:
```
  hook: async (ctx) => {
    const body = JSON.stringify(ctx.request.body);
    const endpointSecret = 'whsec_secret';
    const signature = ctx.request.headers['stripe-signature'];

    const event = stripe.webhooks.constructEvent(body, signature, endpointSecret);
    console.log(event)
}
```
**System**
- Node.js version: 11.12.0
- NPM version: 6.7.0
- Strapi version: 3.0.0-beta.17.8
- Database: postgres
- Operating system: MacOS

**Ideas**
As said before, stripe is giving an example for ***Express*** [here](https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express.js) which solves the issue by using ```bodyParser.raw({type: 'application/json'})``` as a middleware for this route.

**Comment by lambertkevin** [comment]
Ok found a solution after a LOT of time 😆

You have to modify all your request.json files to add a parameter to the koa-body parser.

```
"parser": {
    "enabled": true,
    "multipart": true,
    "includeUnparsed": true
  }
``` 

```includeUnparsed``` will add a symbol containing the unparsed body in ```ctx.request.body```.

To get this symbol you'll have to import ```const unparsed = require('koa-body/unparsed.js');```and then ```ctx.request.body[unparsed]``` will contain the raw buffer of the body.

```
const unparsed = require('koa-body/unparsed.js'); 
...
  hook: async (ctx) => {
    const endpointSecret = 'whsec_secret';
    const signature = ctx.request.headers['stripe-signature'];
    const event = stripe.webhooks.constructEvent(ctx.request.body[unparsed], signature, endpointSecret);
}
```

**Comment by lauriejim** [comment]
So you are okay with your issue.
We can close it I think.

**Comment by derrickmehaffy** [comment]
I will mark as closed as user found resolution to their issue.

**Comment by olso** [comment]
Maybe this will help someone in the future https://github.com/stripe/stripe-node/issues/396#issuecomment-653691205

**Comment by collegewap** [comment]
Here is what worked for me

Create a middleware (/config/middleware.js) and update it to the following
```
module.exports = {
  settings: {
    cors: {
      enabled: true,
    },
    parser: {
      enabled: true,
      multipart: true,
      includeUnparsed: true,
    },
  },
};
```
In the controller (/api/<model>/controllers/<model>.js):

```
const unparsed = require("koa-body/unparsed.js");
const unparsedBody = ctx.request.body[unparsed];
```

**Comment by okwme** [comment]
@collegewap I dont see `includeUnparsed` as a valid option in the [strapi documentation](https://strapi.io/documentation/developer-docs/latest/concepts/middlewares.html#core-middleware-configurations). When I try your method I don't see it in the body object either. Any idea what could be different on my setup?

**Comment by okwme** [comment]
nm i figured it out, had `middleware.js` in the wrong `config` directory 🤦‍♂️

**Comment by nazrdogan** [comment]
I had the same issue with v4. I changed `middleware.js` like this. it may help anyone have same issue.

```
module.exports = [
  "strapi::errors",
  "strapi::security",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  {
    name: "strapi::body",
    config: {
      includeUnparsed: true,
    },
  },
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

**Comment by dam-ion** [comment]
@callum-gander I am still running into the same issue as well. includeUnparsed doesn't seem to work.

**Comment by multijump** [comment]
> const unparsedBody = ctx.request.body[unparsed];

it worked well in v4

**Comment by Justinkarso** [comment]
I found this solution to be working:

```
"@strapi/strapi": "4.11.7",
"stripe": "^12.14.0"
```

In root > config > middleware.js 
```
module.exports = [
  "strapi::errors",
  "strapi::security",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  { name: "strapi::body", config: { includeUnparsed: true } }, // add this
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

In your controller
src > api > [api-name] > controllers > [api-name].js
```
// At the top of your file
const unparsed = require("koa-body/unparsed.js");

module.exports = createCoreController("api::example.example", ({ strapi }) => ({ 
  async webhook(ctx) {
    const unparsedBody = ctx.request.body[unparsed];
    const signature = ctx.request.headers["stripe-signature"];

    let event;

    try {
      event = stripe.webhooks.constructEvent(unparsedBody, sig, endpointSecret);
    } catch (err) {
      return ctx.badRequest(`Webhook Error: ${err.message}`);
    }

    console.log("Webhook received", event.type);

    return { received: true };
  },
}));
```

**Comment by raphaelMrci** [comment]
Now, `unparsed` is no longer available this way. You have to use :

`const unparsed = Symbol.for('unparsedBody');`

Don't need to import anything, just probably to have `koa-body` installed as package

**Comment by th0rgall** [comment]
The two previous posts also work for me in Strapi v4.19.1 (Justinkarso's solution with raphaelMrci's additional suggestion).

I did not have to install `koa-body` as a separate package, I guess the version that Strapi includes by default is enough.

**Comment by Karso23** [comment]
Im using `strapi 4.24.3 and stripe 15.8.0` and when I try to use 
`const unparsed = Symbol.for('unparsedBody');`

I get this error `TypeError: Cannot convert a Symbol value to a string`
any tips/suggestions

**Comment by TupiC** [comment]
For anyone struggling in strapi version 5:
`const unparsedBody = ctx.request.body[Symbol.for("unparsedBody")];`
