### ISSUE TITLE
Filtering by fields inside a relation causes deletion of those fields from the response

### ISSUE THREAD

**Issue by Satherial** [strapi/strapi#4725]
**Describe the bug**
Filtering by relation one-to-many fields, causes the find to reply with the right results, but without those fields.

**Steps to reproduce the behavior**
Create 3 apis, for example  "zone", "operation" and "info". The models would be:
operation:
`
[...]
    "info": {
      "model": "info",
    },
[...]
`
info:
`
[...]
    "zone": {
      "model": "zone"
    },
[...]
`
zone is just plain data.

Then filter like this:
const query = {
      ['info.zone_in']: myzoneidsarray,
    }
const operations = await strapi.query('Operation').find(query)

**Expected behavior**
We expect to get the operations with the info relation filtered by the zones we need and with the field zone equals to the zone id.

**System**
- Node.js version: 10.15.0
- NPM version: 6.10.2
- Strapi version: v3.0.0-beta.17.8
- Database: mongo on mongo cloud
- Operating system: Mac Osx 10.15.1

**Comment by lauriejim** [comment]
Hello! 
Can you tell me please how you created your relations?
Because I think some information are missinig in the relation definition.
So relation is a oneWay so the data is accessible just in one way.

**Comment by Satherial** [comment]
hello, I've created the relations by hand, writing the models by myself.
Inside the "operation" model.settings.json I've just defined the field "info" as described, as a "model:info" and the "info" model.settings.json I've defined the field "zone" as "model:zone".
Zone is just a plain data without model fields, something like "myfield:{type:string}".

**Comment by lauriejim** [comment]
Can you share your 3 models structure. I'm not sure of the data structure you created.
