### ISSUE TITLE
Cant run strapi: not master and slaveOk=false

### ISSUE THREAD

**Issue by matan335** [strapi/strapi#4729]
Have been using strapi for a while

tried to run it as always and encountered an error

`error MongoError: not master and slaveOk=false`

please help

*System**
- Node.js version: 12.10.0
- NPM version: 6.12.1
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB
- Operating system: macos

**Comment by derrickmehaffy** [comment]
Alpha is no longer supported, I would recommend you test and upgrade to the latest beta.

Marking as closed as Alpha isn't supported anymore.
