### ISSUE TITLE
Nested related ContentType doesn't appear in find / findAll

### ISSUE THREAD

**Issue by danielocampo2** [strapi/strapi#4731]
The easiest way to describe this bug is with my current example:

I have the types Question, Option and Poll. A poll has many questions, and a question has many options.
If I query /questions I get all the questions with all the options.
However, if I query /polls I get all the polls with all the questions but they don't have any options.

**Steps to reproduce the behavior**
1. Create a Content Types A, B and C, where A has many B and B has many C.
2. Enable a public API for find / findAll for type A (not strictly required but easier to see it through API)
3. Query find / findAll (either through code using the A service or through the API)
4. Content Type A has all the related B types but B doesn't include any of the C types.

**Expected behavior**
All the data is retrieved, including all the content of type C included in type B. 

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: v3.0.0-beta.17.8
- Database: MySQL
- Operating system: MacOS Mojave 10.14.6

Currently I am working around this issue by overriding the controller for find, getting all the data by myself and attaching it to the response, but this is of course not ideal.

Thanks.

**Comment by lauriejim** [comment]
Hello @danielocampo2 !
This is completely normal.
Strapi populate first relation by default.
Then if you want more you will have to customize your controller function.
See this thread https://spectrum.chat/strapi/general/group-doesnt-appear-on-findall-with-relations~c0bcc957-3170-4e80-96de-ee3e7625b5bf
