### ISSUE TITLE
Newly registered user login error:

### ISSUE THREAD

**Issue by wangyuks** [strapi/strapi#4734]
Newly registered user login error:
`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.invalid",
                    "message": "Identifier or password invalid."
                }
            ]
        }
    ]
}`

**Comment by soupette** [comment]
I'm closing this issue as it doesn't follow the issue template and also it seems a duplicate of #4735
