### ISSUE TITLE
When I create a new user to log in, I get an error:

### ISSUE THREAD

**Issue by wangyuks** [strapi/strapi#4735]
When I create a new user to log in, I get an error:
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.invalid",
                    "message": "Identifier or password invalid."
                }
            ]
        }
    ]
}
![image](https://user-images.githubusercontent.com/26295888/70899930-ae1fe180-2032-11ea-8cb2-fb044ef5ed17.png)

**Comment by soupette** [comment]
Can you give details step to reproduce your issue?

I am guessing you want to give your users access to the administration panel but the user model is different than the administrator one.

In order to create a new administration you need to click on the `Manage the administrator` link which is located in the dropdown of the top right corner button (click on `wangy`).

**Comment by wangyuks** [comment]
I am a user created with the user content type that comes with strapi. Where do I log in?

**Comment by soupette** [comment]
If you are a user created with the `user` content type you **cannot** log in to the administration panel, only **administrator** can.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by wangyuks** [comment]
**Describe the bug**
When I create a user using the user module that comes with strapi, I can't log in through the login page of strapi with an error:
{
"statusCode": 400,
"error": "Bad Request",
"message": [
{
"messages": [
{
"id": "Auth.form.error.invalid",
"message": "Identifier or password invalid."
}
]
}
]
}
**Steps to reproduce the behavior**
1. add an user
![image](https://user-images.githubusercontent.com/26295888/70958156-48c00500-20b3-11ea-8e68-4a3da936991e.png)
2. Sign out of current user
![image](https://user-images.githubusercontent.com/26295888/70958203-6f7e3b80-20b3-11ea-9051-eeb88bed29a2.png)

3. Login with the user you just added
4. See error
{
"statusCode": 400,
"error": "Bad Request",
"message": [
{
"messages": [
{
"id": "Auth.form.error.invalid",
"message": "Identifier or password invalid."
}
]
}
]
}

The user content type that comes with strapi can be bound to permissions. I need such users to do permission control. At the time, I ca n’t log in.

**Comment by ShyamRaj** [comment]
I have the same issue, I think I now understand this concept, Only admin users can only login to the admin panel.

May be my following question is a separate issue,
I created a new admin user to the admin panel for content creators (Basically i want a regular user to manage content but looks like the regular user cannot login to admin panel),So how do I setup some permissions to not let the content admin user to not delete other admin users or change the password for the main admin user, etc.

**Comment by derrickmehaffy** [comment]
@ShyamRaj you are correct that normal users cannot login to the admin but currently there is no permissions system for the admin (meaning what you are stating is possible and there isn't currently a way to limit that). Strapi does plan to add a permissions system to the adminUI: https://portal.productboard.com/strapi/1-public-roadmap/c/8-administrators-roles-permissions

You can read more about the split users in this blog post: https://strapi.io/blog/why-we-split-the-management-of-the-admin-users-and-end-users?redirectPage=2

**Comment by ShyamRaj** [comment]
Thanks for the quick clarification @derrickmehaffy is there any ETA for the admin-roles-permissions, I see Q2 2020!

**Comment by derrickmehaffy** [comment]
That is the only estimate right now, currently the strapi team are entirely focused on the webhooks and media library features so they haven't even started working on the admin permissions feature yet. A better ETA will come when they start work on it.
