### ISSUE TITLE
Can't send a user an email to reset their password

### ISSUE THREAD

**Issue by codeHatcher** [strapi/strapi#4737]
**Describe the bug**
When resetting a user the system says the email address doesn't exist

**Steps to reproduce the behavior**
1. Go to 'login page'
2. Click on 'forgot password'
3. Type email of existing user
4. Click on 'send email'
5. See error 'This email does not exist'

**Expected behavior**
I expect to see an email sent to my account and a message saying that an email was sent

**Screenshots**
![image](https://user-images.githubusercontent.com/5360982/70953777-6b75fd80-2062-11ea-984b-3009a63840b6.png)
![image](https://user-images.githubusercontent.com/5360982/70953793-7e88cd80-2062-11ea-9b10-95b368203654.png)

**Code snippets**

server response

```json

{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.form.error.user.not-exist","message":"This email does not exit"}]}]}
```

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.8
- Database: mongodb
- Operating system: ubuntu 18

**Additional context**

**Comment by lauriejim** [comment]
Hello! By default strapi is using `sendmail` to send emails.
But your local machine smtp server have to be well configured.
It's an easy way to go to use your local smtp server BUT it could fail.
In anycase, if you want to send email, I suggest you to use an email provider like sendgrid, ...
You will find all the docs you need here https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#install-new-providers
