### ISSUE TITLE
Installing admin package on now.sh

### ISSUE THREAD

**Issue by lucaperret** [strapi/strapi#474]
Node.js version: v8.9.4
npm version: 5.6.0
Strapi version: 3.0.0-alpha.8

When trying to deploy on [now.sh](https://zeit.co/now), facing this issue:
```
01/18 11:50 PM  npm start
01/18 11:50 PM
                > my-strapi-app@0.1.0 start /home/nowuser/src
                > node server.js
01/18 11:50 PM  fs.js:1081
                  return binding.unlink(pathModule.toNamespacedPath(path));
                                 ^
01/18 11:50 PM
                Error: EACCES: permission denied, unlink '/home/nowuser/src/admin/admin/src/config/plugins.json'
                    at Object.fs.unlinkSync (fs.js:1081:18)
                    at fs.access.err (/home/nowuser/src/node_modules/strapi/lib/core/plugins.js:76:16)
01/18 11:50 PM      at FSReqWrap.oncomplete (fs.js:149:20)
01/18 11:50 PM  npm ERR! code ELIFECYCLE
```

Maybe link to [this specification](https://zeit.co/docs/deployment-types/node#file-system-specifications):

> ### File System Specifications
> By default, it's not possible to write files to the file system when creating Node.js deployments.
> But there's an exception: The first time the build step (either using the build or now-build) runs, Node.js will be able to write to the file system. This is necessary for allowing applications to be bundled and/or transpiled on the server.
After either the start or now-start scripts have started running, the only writable location will be /tmp.

**Comment by lucaperret** [comment]
The problem is still there:
```bash
> ▲ npm start
> app@0.1.0 start /home/nowuser/src
> node server.js
> [2018-03-20T18:41:51.841Z] warn (hook:mongoose) wasn't loaded due to missing key `enabled` in the configuration
> fs.js:1085
>   return binding.unlink(pathModule.toNamespacedPath(path));
>                  ^
> Error: EACCES: permission denied, unlink '/home/nowuser/src/admin/admin/src/config/plugins.json'
>     at Object.fs.unlinkSync (fs.js:1085:18)
>     at fs.access.err (/home/nowuser/src/node_modules/strapi/lib/core/plugins.js:76:16)
>     at FSReqWrap.oncomplete (fs.js:153:20)
```
Why the `plugins.json` file has to be rewrited ?

**Comment by Aurelsicoko** [comment]
This file is used to load the plugins into the administration panel (https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/app.js#L92). The administration panel, the plugins and the backend can be on different servers so it helps us to load the plugins correctly.

We did that to avoid the backend (API) to expose the installed plugins. However, there might have a better way to do this...

**Comment by lucaperret** [comment]
This is due to a limitation of Zeit now. Strapi will not be authorized to write models files on it.
@matheuss do you plan to implement file persistence on @zeit now ?

**Comment by billgo** [comment]
I have the same question ?

**Comment by DimitryDushkin** [comment]
same here

**Comment by perrosnk** [comment]
any solution?

**Comment by Aurelsicoko** [comment]
No, it still impossible until Zeit doesn't allow to write files on their servers. As we are not storing the models in database (which make sense), we have to be able to write the files and generate the folders in the project when you're creating a new API (aka Content-Type).

**Comment by greatwitenorth** [comment]
@Aurelsicoko can you confirm then that Strapi does in fact write files in production? This seems to contradict information given to me by @emadicio
> If you run your app with NODE_ENV=production you'll notice that plugins that actually edit or create files are disabled. So that means you cannot create or edit content types in prod
https://github.com/strapi/strapi/issues/1986#issuecomment-422969635

**Comment by Aurelsicoko** [comment]
The Content-Type builder is disabled in production, it means that you can't create files new content-type in production. However, it doesn't mean that Strapi doesn't write files in production. I'm thinking about the `plugins.json` file which is written at every start.

Does it cause any issues?

**Comment by thetre97** [comment]
Can you deploy with Docker? According to the [Zeit docs](https://zeit.co/docs/deployment-types/docker#file-system-specifications)...

## File System Specifications
There are no limitations inside Docker deployments when it comes to the file system. It's always writable and readable.

**Comment by rsternagel** [comment]
What about Now 2.0 ([apparently released on 08/11/18](https://zeit.co/blog/now-2))? Would it work with Strapi?

**Comment by derrickmehaffy** [comment]
@rsternagel `static files and serverless functions` Strapi is not just static files and really cannot function "serverless" as it is a dynamic system that runs code on the server itself. Some nodejs projects can be "built" and deployed in serverless environments but that isn't Strapi. That would pose a huge security risk, and honestly isn't feasible to run your API on a clients machine (many of them).

Serverless and static systems are never going to work with Strapi, it isn't built for that.

**Comment by cschweda** [comment]
What about deploying on Now with the strapi-docker repo?

**Comment by Aurelsicoko** [comment]
@thetre97 It's not done yet... The community doesn't seem to understand this decision. I trust the Zeit team and I'm blown away by their work but the vendor lock-in seems to be a valuable argument to don't remove the Docker support.
