### ISSUE TITLE
Old contents having createdAt = today on admin panel (No createdAt in some api response)

### ISSUE THREAD

**Issue by Christinaaaa** [strapi/strapi#4743]
**Describe the bug**
On admin panel, I noticed some old contents created long time ago on Strapi are having createdAt = today. 
When running script calling api, for some contents, createdAt field is missing in the response while for the rest it exists.
In api response with createdAt missing, there is a field named "cta" having empty string.

**Steps to reproduce the behavior**
Not sure how to trigger this.

**Expected behavior**
All the contents should have correct createdAt timestamp.

**Screenshots**

**Code snippets**
Article contentType is setup this way with two timestamps createdAt and updatedAt.
```
{
  "connection": "default",
  "collectionName": "article",
  "info": {
    "name": "article",
    "description": ""
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "contentTitle": {
      "default": "",
      "type": "string"
    },
    "content": {
      "default": "",
      "type": "richtext"
    },
...
}
```

**System**
Node.js version: v10.16.3
NPM version: 6.9.0
Strapi version: 3.0.0-beta.16.8
Database: MongoDB db version v3.2.22
Operating system: Ubuntu 18.04.2 LTS

**Additional context**
Has anyone seen this before? What causes that and how to fix it? Is that a Strapi bug or probably issue on our end?

**Comment by derrickmehaffy** [comment]
Can you please test with the latest version `beta.18.2` as `beta.16.8` is a few months old now.
