### ISSUE TITLE
Make optional filters in creating Strapi queries

### ISSUE THREAD

**Issue by Tobska** [strapi/strapi#4748]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

From what I read in the documentation, all filters that are in a query using Strapi's query functions are **all required** (therefore they are built with an "AND" condition in SQL). However, I'm trying to build a query that has optional filters (built with an "OR" condition).

For example (this is what I had in mind):

```
strapi.query.("restaurant").find({
  or: { menu_null: false, openTime_gt: 2019-01-01T00:00:00Z }
})
```

So it would display menus that are not null **OR** openTimes that are greather than said time.

```
// ONLY CURRENT WAY
strapi.query.("restaurant").find({
  menu_null: false,
  openTime_gt: 2019-01-01T00:00:00Z
})
```

^^ Doing this would display menus that are not null **AND** openTimes that are greather than said time.

This was also posted in: https://stackoverflow.com/questions/57619456/how-do-i-add-an-or-condition-in-a-graphql-where-statement

**Comment by derrickmehaffy** [comment]
I agree OR filters need to be added although this may be something that should be included in an entire filtering system rewrite (something along the lines of following say the OpenAPI standard or close to for REST and some other GQL related standard)

**Comment by derrickmehaffy** [comment]
@Aurelsicoko

**Comment by lauriejim** [comment]
Hello! Here is an issue about this topic https://github.com/strapi/strapi/issues/3194
