### ISSUE TITLE
Adding an enum type to a model fails if it has a custom default value

### ISSUE THREAD

**Issue by Billybobbonnet** [strapi/strapi#4749]
Hello,

I use strapi latest version (Strapi v3.0.0-beta.17.8), with a local mongoDB.

This bug is easy to reproduce:

1. Create a model
2. Add an enumeration type field to this model

If you don't set a default value to your field, it works. If you do, it fails  with a toast "an error occurred".

Let me know if you need more details.

**Comment by soupette** [comment]
@Billybobbonnet I am unable to reproduce your issue can you give more details?

**Comment by Billybobbonnet** [comment]
I am on an Ubuntu 18.04 machine, with a fresh strapi install. All plugins but documentation are installed. I use a local mongoDB (4.2.2) direct connection.

The faulty default value I mentioned is in the "advanced" tab of the enumeration field definition dialog. I used a string list. With default value, I can't save it (but it is created). Without default value I can save.

Let me know if you need more specifics.

**Comment by soupette** [comment]
Can you provide screenshots because it's working fine on my side.

**Comment by Billybobbonnet** [comment]
I'm not sure if it will be helpful but here are some screenshots.

The enum field in the model object (emailFrequency):

![image](https://user-images.githubusercontent.com/8236816/71092494-9ddd4300-21a7-11ea-8f9d-11ff65b37708.png)

Its details "advanced" tab where I select, e.g. "weekly" instead of "immediately" (first & default field)
![image](https://user-images.githubusercontent.com/8236816/71092748-1ba14e80-21a8-11ea-8832-ef0334b7bdf2.png)


What happens when saving after changing the default enum value:
![image](https://user-images.githubusercontent.com/8236816/71092852-55725500-21a8-11ea-8f61-dd4843f0e119.png)


The error displayed on the console is 
`debug PUT /content-type-builder/groups/settings (7 ms) 400`

**Comment by Billybobbonnet** [comment]
Note that it happens with every model, whether it is associated with a content or not.

create model > create enum field > set default value > error

The document in local DB looks like this (from robomongo):
![image](https://user-images.githubusercontent.com/8236816/71093297-345e3400-21a9-11ea-9d69-b7f56d4aa3b3.png)

**Comment by soupette** [comment]
@Billybobbonnet can you try upgrading to beta.18?

**Comment by Billybobbonnet** [comment]
![image](https://user-images.githubusercontent.com/8236816/71094566-7ab49280-21ab-11ea-879d-d4e5d0ea9afe.png)

I just did, and it didn't change the error.

**Comment by soupette** [comment]
Honestly I am not able to reproduce it what is the error you get in the chrome console and it your server?

**Comment by Billybobbonnet** [comment]
chrome console: 
![image](https://user-images.githubusercontent.com/8236816/71097978-375d2280-21b1-11ea-8e7e-6fb54f71f8fc.png)

Server console (as mentioned above)
![image](https://user-images.githubusercontent.com/8236816/71098046-58be0e80-21b1-11ea-848a-c2e1b24332c3.png)
