### ISSUE TITLE
Erro in MySQL query run server

### ISSUE THREAD

**Issue by lucasdu4rte** [strapi/strapi#475]
**Node.js version**: v9.4.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8
**Operating system**: Ubuntu 17.10

after I run strapi I was asked to do two steps manually, execute the query and restart the server
```
CREATE TABLE "user" (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username text,
  email text,
  provider text,
  role text,
  resetPasswordToken text,
  password text,
  updated_at timestamp,
  created_at timestamp
);
```
This SQL QUERY generate erro: 

> ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"user" ( id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, username text, email ' at line 1

My Solution:
```
CREATE TABLE user (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username text,
  email text,
  provider text,
  role text,
  resetPasswordToken text,
  password text,
  updated_at timestamp null,
  created_at timestamp null
);
```
I'm a beginner developer, and I still do not know and I did not try to contribute to the project: /

**Comment by lauriejim** [comment]
Hi @lucasdu4rte thank your for this issue.

A pull request have been submitted to fix it https://github.com/strapi/strapi/pull/497

**Comment by lauriejim** [comment]
Fixed here https://github.com/strapi/strapi/pull/507/commits/462b44a759caef15ebf3239a84e912b3c057b897
