### ISSUE TITLE
Inconsistency in component group name parsing

### ISSUE THREAD

**Issue by izzuddinnatsir** [strapi/strapi#4756]
**Describe the bug**
When naming component group with underscore or camel case, the result component group name is dash name. for example TestCategory or test_category will be converted to test-category which result to regex error when adding a component under that group name.

**Steps to reproduce the behavior**
Please watch this screencast
https://www.loom.com/share/745e65b2d2e24b3388396b62f3d082d3

**Expected behavior**
Strapi should not convert underscore and camel case to dash.

**System**
- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: Strapi 3 beta 18.1
- Database: PostgreSQL
- Operating system: Ubuntu 18.04 LTS (installed Strapi using official strapi/strapi docker image)

**Comment by alexandrebodin** [comment]
This behaviour is intended for consistentcy. The names of the components and there categories are normalized. We will not be changing this behaviour. 

We just need to change the form regex for categories.
