### ISSUE TITLE
Strapi Fields not updating

### ISSUE THREAD

**Issue by morgietalkie** [strapi/strapi#4758]
**Describe the bug**
So I've now tried to install Strapi twice - both with Yarn and NPX, but I seem to run into some troubles every time. When Strapi is first installed, it seems to work fine - but as soon as i'm shutting down the server and starting it again it won't let me see the updates, whenever i'm creating new content types or fields. However everything works - but in order to see the changes, i have to close the server and start Strapi again? Please help or let me know if anyone is facing the same issues. 

**Steps to reproduce the behavior**
1. Install strapi (Works fine)
2. Closing down the strapi server. 
3. npx strapi start (Works fine)
4. Creating new content types / fields - press save (Nothing happens)
5. Shutting down the strapi connection again. 
6. npx strapi start (Still works fine)
7. Now I can see the changes from step 4 now - But same thing is happening if I try to create new content types / Fields and press save.

**Expected behavior**
When I press "Save" in the content type builder I expect the page to reload and show the new content-type / Fields I've made. 

**Code snippets**
When save is pressed the console shows following message:
Fetch failed loading: HEAD "http://localhost:1337/_health"

**Comment by soupette** [comment]
Try `npm run develop` or `yarn develop` in fact any command that ends with `develop` instead of `start`

**Comment by morgietalkie** [comment]
Thanks man! Totally worked!! 
You're a genius!
