### ISSUE TITLE
The new date picker doesn't allow change of year

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4761]
**Describe the bug**
With the new datepicker is imposible change the year.

For example, I need to select `August 12, 1993`. I can't go month by month until 1993. 😅 

**Expected behavior**
An option like the previous date picker.

**Screenshots**

<img width="347" alt="Screenshot 2019-12-19 at 03 47 26" src="https://user-images.githubusercontent.com/1007051/71140701-4d4eff80-2212-11ea-91bc-976c7011ab65.png">

**System**
- Node.js version: `v12`
- NPM version: `v6`
- Strapi version: `v3.0.0-beta.18.1`
- Database: MongoDB
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
Come now @abdonrd you know the rules :P **I know** it's for beta.18.1 but anyone else that reads this wont. And even I take time to fill out the entire template for even small bugs :P

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by abdonrd** [comment]
I would swear that I had added the system information. Updated!

**Comment by abdonrd** [comment]
Also friendly ping to @soupette!

**Comment by abdonrd** [comment]
@derrickmehaffy can you re-open it? 😄

**Comment by derrickmehaffy** [comment]
Reopened :P

**Comment by soupette** [comment]
In fact I think that this issue should be closed on this repo and opened on [this one](https://github.com/strapi/buffet)

**Comment by abdonrd** [comment]
Ok, moved to https://github.com/strapi/buffet/issues/68
