### ISSUE TITLE
Additional guide is required for date type in migration guide for beta.18

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#4763]
**Describe the bug**
I can't update content after migrating v3.0.0-beta.18, which has date attribute.

**Steps to reproduce the behavior**
1. Select existing content has date attribute.
2. Save and it occurs error.
```
error ValidationError: <content type> validation failed: date: Invalid format, expected an ISO compatble date
```

**Expected behavior**
It should've been updated.

**Screenshots**
<img width="326" alt="스크린샷 2019-12-19 오후 2 14 16" src="https://user-images.githubusercontent.com/4951716/71146767-de9d9080-2269-11ea-9459-09c8fe0e187d.png">

So when I created new content, It created and updated with no error. So I checked out the database and the date field was saved differently.
<img width="802" alt="스크린샷 2019-12-19 오후 2 03 35" src="https://user-images.githubusercontent.com/4951716/71146647-6a62ed00-2269-11ea-9669-e465337f8b05.png">
I think new date types (datetime, and time) added in beta.18 causes error to origin content. I think migration guide needs to explain about it.

**System**
- Node.js version: v10.15.3
- NPM version: v6.9.0
- Strapi version: v3.0.0-beta.18
- Database: mongo
- Operating system: macOS

**Additional context**
It's my content type's date attribute.
```js
"attributes": {
    ...
    "date": {
      "required": true,
      "type": "date"
    }
    ...
}
```

**Comment by alexandrebodin** [comment]
HI @iicdii you need to change it to datetime ;). Will udpate the migration guide
