### ISSUE TITLE
PUT request to repeatable group fails when including id

### ISSUE THREAD

**Issue by robster11** [strapi/strapi#4765]
**Describe the bug**

When I attempt to  do a REST PUT request to a content type that has a repeatable group. The PUT request fails and generated an error when I include "id" or "_id" in the request.

{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Some of the provided groups in files are not related to the entity"
}

**Steps to reproduce the behavior**

An example here is a repeatable group called files. 

"files": [
            {
               "_id": "5ddba9e520e078157db72b59",
               "filename": myfile.txt",
                "status": "To Check",
                "edited": "2019-11-25T10:15:55.190Z",
                "fliesize": 9882836
            }
        ], 

If I attempt to put this to content type the request fails.

If I remove "_id" the PUT request works.

"files": [
            {
               "filename": myfile.txt",
                "status": "To Check",
                "edited": "2019-11-25T10:15:55.190Z",
                "fliesize": 9882836
            }
        ], 

**Expected behavior**

I should be able to make a put request and update a group in a content type with the original  "_id"

**Screenshots**
NA

**Code snippets**
See above

**System**
- Node.js version: 
- NPM version: 12
- Strapi version: V3.0.0-beta.17.8
- Database: Mongodb
- Operating system: Ubuntu

**Additional context**
NA

**Comment by soupette** [comment]
It's not really a bug, in fact you need to remove the ids when editing a document. You can checkout [this code](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/utils/cleanData.js) that cleans it automatically in the content manager you can easily modify it so it suits your need.

**Comment by alexandrebodin** [comment]
Mistake on our side indeed you should be able to edit a content type with the old group id. 

Can you please share the follwing informations:

- model schemas
- full api call you made

Thanks !

**Comment by therobster121** [comment]
Suggest we close this. Our developers can no longer reproduce
.

**Comment by derrickmehaffy** [comment]
@alexandrebodin I'll let you close this one, unless you want to try and reproduce it.
