### ISSUE TITLE
creating new content type on centos 7 error

### ISSUE THREAD

**Issue by qaxim** [strapi/strapi#4772]
Hello 

just installed your latest beta on centos 7 and when I tried to add content type its showing error on console such as below : 

main.bf86b396.chunk.js:20119 POST http://139.162.195.38:1337/content-type-builder/content-types 400 (Bad Request)
main.bf86b396.chunk.js:133361 
{err: Error: Bad Request
    at http://139.162.195.38:1337/admin/main.bf86b396.chunk.js:20119:253564}
err: Error: Bad Request at http://139.162.195.38:1337/admin/main.bf86b396.chunk.js:20119:253564
response: Response {payload: {…}, type: "basic", url: "http://139.162.195.38:1337/content-type-builder/content-types", redirected: false, status: 400, …}
stack: "Error: Bad Request↵    at http://139.162.195.38:1337/admin/main.bf86b396.chunk.js:20119:253564"
message: "Bad Request"
__proto__: Object
__proto__: Object

any solutions please asap ?

**Comment by alexandrebodin** [comment]
@qaxim In order to help you we need you to fill the issue template with all the necessary informations. 

We will reopen the PR once updated. Thanks !
