### ISSUE TITLE
Slow admin dashboard because auto populates all the queries

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4775]
#### Describe the bug

As my project has grown, I have seen the administration panel become slower and slower. Today I found one of the reasons: The auto population.

For example, if I have a `Post` model with an `authors` field.
And this `authors` field is a relationship with the `User` model.
When I create a new post, and search users in the `authors` dropdown, the query get **all** the user information, with their auto populated relations. And this is crazy! 😅 

And it gets worse now when my `User` model has more than 10 relationships.

#### Expected behavior

Just request the minimum information: they key to show in the dropdown selector.

#### System
- Node.js version: `v12`
- NPM version: `v6`
- Strapi version: `v3.0.0-beta.18.2`
- Database: MongoDB
- Operating system: macOS

**Comment by abdonrd** [comment]
Ok, it doesn't affect dropdowns only, it affects all the calls the dashboard makes. On the lists too.

**Comment by abdonrd** [comment]
I know it's a hack, but for now I make this changes:

1. Add `"autoPopulate": false` in **all** the model relations.
2. Add these two files:

`extensions/content-manager/controllers/ContentManager.js`
```javascript
'use strict';

const contentManagerService = require('../services/ContentManager');

module.exports = {
  /**
   * Returns an entity of a content type by id
   */
  async findOne(ctx) {
    const entry = await contentManagerService.fetch(ctx.params);

    // Entry not found
    if (!entry) {
      return ctx.notFound('Entry not found');
    }

    ctx.body = entry;
  },
};
```

`extensions/content-manager/services/ContentManager.js`

```javascript
'use strict';

/**
 * A set of functions called "actions" for `ContentManager`
 */
module.exports = {
  fetch(params, populate) {
    if (!populate) {
      const modelAssociations = strapi.query(params.model).model.associations;
      populate = modelAssociations.map(association => association.alias);
    }

    return strapi.query(params.model).findOne({ id: params.id }, populate);
  },
};
```

In the service I force the population.

**Comment by alexandrebodin** [comment]
We sure have performance issues. It's not a top priority right but feel free to open a PR to the content-manager to handle this ;) 

I can guide you through it if you need ;)

**Comment by rahulvyas1** [comment]
Facing the same issue!

I did the step #1 as advised by@abdonrd but for #2 - the there is no content-manager folder in the extension

How to proceed?

**Comment by tonyAndr** [comment]
Hope to see in the future updates easier way to disable auto-population of related items. 

It is nice to have an option "autoPopulate" because without it Strapi admin panel is just too slow and useless. Setting this parameter to false makes it blazing fast. 
I don't really use sidepanel with related items, but it would be nice at least to see there how many items are related (eg. how many articles has selected category). And of course when "autoPopulate" is false it is not possible to filter articles by category id, which is sad.

**Comment by abdonrd** [comment]
Is there news on this? It's been a long time. Thanks!

**Comment by abdonrd** [comment]
Mention that this (https://github.com/strapi/strapi/issues/4775#issuecomment-567648534) is no longer working with the latest versions of Strapi.

**Comment by abdonrd** [comment]
@alexandrebodin makes sense to add this code (https://github.com/strapi/strapi/issues/4775#issuecomment-770378614) as a PR?

If not, adding the `"autoPopulate": false` makes the content manager unusable.

**Comment by abdonrd** [comment]
> We sure have performance issues. It's not a top priority right but feel free to open a PR to the content-manager to handle this ;)
> 
> I can guide you through it if you need ;)

@alexandrebodin done! https://github.com/strapi/strapi/pull/9307

**Comment by kiselevAlex** [comment]
It don't work for update entity :(

**Comment by abdonrd** [comment]
@derrickmehaffy fixed in v4?

**Comment by derrickmehaffy** [comment]
Yes fixed in v4, closing

**Comment by kibblerz** [comment]
I'm on 4.1.2.

This needs to be opened back up. It's said to have been fixed, yet my admin is taking 15 seconds to load a content type with 2 relations. When i look at the data being returned, i see that the related content types are being fully populated, including their relations. Population should be limited to the ID and relevant field to display as the entry name.

**Comment by derrickmehaffy** [comment]
> I'm on 4.1.2.
> 
> This needs to be opened back up. It's said to have been fixed, yet my admin is taking 15 seconds to load a content type with 2 relations. When i look at the data being returned, i see that the related content types are being fully populated, including their relations. Population should be limited to the ID and relevant field to display as the entry name.

please check on v4.1.3
