### ISSUE TITLE
Slug example not working

### ISSUE THREAD

**Issue by EloB** [strapi/strapi#4776]
**Describe the bug**
The documenation for how to produce slugs isn't working.
https://strapi.io/documentation/3.0.0-beta.x/guides/slug.html#create-attributes

`getUpdate()` and `update` is no longer existing. So the code fails.

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.2
- Database: bookshelf - sqlite
- Operating system: Windows 10

**Comment by EloB** [comment]
My bad. I didn't see something in docs.

**Comment by pedrogpimenta** [comment]
@EloB could you say what didn't you see? It's not working for me as well and I'm going crazy...

**Comment by samyilias** [comment]
@pedrocruzio same here using mongoose and MongoDB

**Comment by d-ban** [comment]
Same error here, modified code like this and now it's working again. 

Path — ./api/article/models/Article.js  
connector: 'bookshelf' 

```
module.exports = {
  lifecycles: {
    async beforeCreate(data) {
      strapi.log.debug("beforeCreate")
      data.slug = slugify(data.title, {lower: true});
    },
    async beforeUpdate (params,data) {
      strapi.log.debug("beforeUpdate")
      data.slug = slugify(data.title, {lower: true});
    },
  },
};
```
https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

**Comment by tan-ahmed** [comment]
@d-ban thank you so much. I did not know it was possible to "log" completely new to strapi.

**Comment by d-ban** [comment]
@tan-ahmed  yeah, it's working. if you want to log data `strapi.log.debug("data",data)`

**Comment by joscelyn** [comment]
You can now use the build-in slug field (uid): [https://strapi.io/documentation/v3.x/concepts/models.html#exceptions](https://strapi.io/documentation/v3.x/concepts/models.html#exceptions)

**Comment by graciano** [comment]
> connector: 'bookshelf'

@d-ban what does 'connector' mean in this context?

I'm having a similar issue and I can't debug, like you other example code here :(

**Comment by graciano** [comment]
If it helps anyone, I missed the `lifecycles:` declaration and that's why it wasn't working for me.

**Comment by IrynaSpyrydonova** [comment]
console.log exactly what kind of data you are getting. In my case, it was because I had a `Title` field, but I am querying slugify as` data.title`. So just change your fields to lowercase.

**Comment by adriannecris** [comment]
How do I configure the lifecycles for v4?

**Comment by thoushif** [comment]
I found this helpful!
https://dev.to/elchiconube/create-a-slug-system-with-strapi-v4-1abm

**Comment by Kokopelli84** [comment]
thank you @thoushif . The docs need to be updated since they make no mention of a `lifecycle.js` file
