### ISSUE TITLE
Profile button redirect to incorrect URL format

### ISSUE THREAD

**Issue by antokara** [strapi/strapi#4777]
**Describe the bug**
The URL of the admin's profile is invalid and causes `KOA` to throw `500` on page refresh

**Steps to reproduce the behavior**
1. Login as admin (perhaps as any other user as well)
2. Click on the User menu on the top right
3. Click on the "profile" menu option
4. The URL should now be `/admin/plugins/content-manager/strapi::administrator/1?redirectUrl=/plugins/content-manager/strapi::administrator/?_page=0&_limit=0&_sort=id`
5. Refresh the page using the browser's refresh button
6. Page shows `{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`
7. Error Log shows `error AssertionError [ERR_ASSERTION]: pathname required
    at send (/node_modules/koa-send/index.js:39:3)`

**Expected behavior**
The page appears exactly as before the page refresh

**Screenshots**
Shouldn't be needed

**Code snippets**
Shouldn't be needed

**System**
- Node.js version: v12.13.1
- NPM version:6.12.1
- Strapi version: v3.0.0-beta.18.2
- Database: postgreSQL
- Operating system: Fedora 31 (workstation)

**Additional context**
I think having two `?` in the URL is what is causing the problem because KOA request expects only one
https://github.com/koajs/koa/blob/master/docs/api/request.md
replacing the second `?` with `&` fixes the issue, like so
`/admin/plugins/content-manager/strapi::administrator/1?redirectUrl=/plugins/content-manager/strapi::administrator/&_page=0&_limit=0&_sort=id`
or encoding it `%3F`...

And to be honest, I am not even sure why that `redirectUrl` param is even there.
When I go to other menus like "Manage the Administrators" the URL is like so `/admin/plugins/content-manager/strapi::administrator` without that parameter...

(In both cases, I am logged in...)

**Comment by derrickmehaffy** [comment]
@antokara can you take a look at this issue and maybe make a pull request to fix?

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
Ping @soupette for this. 
This is probably a super quick fix to do.
Feel free @antokara to investigate and make a PR. It will be a great gift for us to see a PR to fix this.

**Comment by antokara** [comment]
I wish I had the time. Perhaps if no one picks it up in the next couple of weeks, I can find time to open the PR for it.

**Comment by abrahamcuenca** [comment]
Hi @antokara I have a fix for this here:  https://github.com/abrahamcuenca/strapi/tree/fix/profile-button-redirect-to-incorrect-url-format

For PR should I request into the develop branch?

**Comment by lauriejim** [comment]
Awesome! Thank you for your PR!
