### ISSUE TITLE
Admin board crashes when deleting multiple fields from Content-Type

### ISSUE THREAD

**Issue by Fralez** [strapi/strapi#4779]
**System**
- Node.js version: v10.17.0
- NPM version: 6.11.3
- Strapi version: 3.0.0-alpha.26.2
- Database: mongoDB
- Operating system: Ubuntu 19.10 x86_64

**Bug Description**

When I try to delete multiple fields from a Content-Type at once before hitting the save button, the server stops and crashes.

**Steps to reproduce the behaviour**
1. Create a Content-Type with 3 fields and save it
2. Go to the Content-Type created and delete all the 3 fields
3. Hit the save button
4. It will tell you that the server is restarting
5. The restart takes more than  expected and crashes the server

**Screenshots**

Content-type generated:
![image](https://user-images.githubusercontent.com/40028772/71220352-fa735780-22a6-11ea-9667-960a516c15f9.png)

Last screen before error:
![image](https://user-images.githubusercontent.com/40028772/71220403-2393e800-22a7-11ea-839b-3722bc76141b.png)

Error displayed:
![image](https://user-images.githubusercontent.com/40028772/71220280-c39d4180-22a6-11ea-881e-dda013ca2c9e.png)

**Additional context**

Apparently, if you undo the modifications made by Strapi in the model's JSON (in this case it would be `Products.settings.json`) inside the route of the model (in this case it would be `api/products/models`) the server goes back to normal.

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-alpha.26.2` Alpha is no longer supported, please test this bug on the latest beta version (beta.18.2) and provide more information, if the bug is confirmed on the beta we can reopen this.
