### ISSUE TITLE
Cannot create new Strapi API in Windows in Beta.18.2

### ISSUE THREAD

**Issue by alhill** [strapi/strapi#4781]
**Describe the bug**
I have updated Strapi to latest beta version (18.2 when writing this) and it fails on Windows 10 when creating a new API. After some tries I have scrolled back to 17.8 and it worked without problem. I tried doing npm install -g strapi@beta as unprivileged user and as root and executing strapi new api with cmd, Powershell and MinTTY but it always fails with 
`⛔️ Connection test failed: spawn npm; ENOENT`

Complete log with --debug flag
```
⛔️ Connection test failed: spawn npm; ENOENT

Full error log:
{ Error: spawn npm; ENOENT
    at notFoundError (C:\Users\alvaro\AppData\Roaming\npm\node_modules\strapi\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\alvaro\AppData\Roaming\npm\node_modules\strapi\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\alvaro\AppData\Roaming\npm\node_modules\strapi\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm;',
  path: 'npm;',
  spawnargs:
   [ 'install',
     '--prefix',
     'C:\\Users\\alvaro\\AppData\\Local\\Temp\\strapid6aeff1c94d1',
     'strapi-connector-mongoose@3.0.0-beta.18.2' ],
  stdout:
   '\nUsage: npm <command>\n\nwhere <command> is one of:\n    access, adduser, audit, bin, bugs, c, cache, ci, cit,\n    clean-install, clean-install-test, completion, config,\n    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,\n    edit, explore, get, help, help-search, hook, i, init,\n    install, install-ci-test, install-test, it, link, list, ln,\n    login, logout, ls, org, outdated, owner, pack, ping, prefix,\n    profile, prune, publish, rb, rebuild, repo, restart, root,\n    run, run-script, s, se, search, set, shrinkwrap, star,\n    stars, start, stop, t, team, test, token, tst, un,\n    uninstall, unpublish, unstar, up, update, v, version, view,\n    whoami\n\nnpm <command> -h  quick help on <command>\nnpm -l            display full usage info\nnpm help <term>   search for help 
on <term>\nnpm help npm      involved overview\n\nSpecify configs in the ini-formatted file:\n    C:\\Users\\alvaro\\.npmrc\nor on the command line via: npm <command> --key value\nConfig info can be viewed via: npm help config\n\nnpm@6.7.0 C:\\Users\\alvaro\\AppData\\Roaming\\npm\\node_modules\\npm\n\n',
  stderr: '',
  failed: true,
  signal: null,
  cmd:
   'npm; install --prefix C:\\Users\\alvaro\\AppData\\Local\\Temp\\strapid6aeff1c94d1 strapi-connector-mongoose@3.0.0-beta.18.2',
  timedOut: false,
  killed: false }
```

The error raises when strapi installer tries to connect with mongo, but mongo is installed and working. And going back to 17.8 works as usual so this is not the problem.

**Steps to reproduce the behavior**
1. Update Strapi to Beta 18.2 in Windows 10
2. Try to create a new API with MongoDB and default settings

**System**
- Node.js version: v10.16.3
- NPM version: 6.7.0
- Strapi version: Beta 18.2
- Database: MongoDB
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
@alhill The error is seems to happen when the script is trying to install strapi-connector-mongoose@3.0.0-beta.18.2.

Can you try to simply run `npm install strapi-connector-mongoose@3.0.0-beta.18.2` and share the error you get if any

**Comment by alhill** [comment]
Nope, installing manually strapi-connector-mongoose@3.0.0-beta.18.2 doesn't change anything, exact same error than before.
BTW, the error log seems to be true, the folder strapiWhicheverID doesn't exist. And if you create it manually when retrying to connect to the database the script delete it (so one more time, it doesn't exist, haha)

**Comment by alexandrebodin** [comment]
Thanks for the details !

**Comment by atlmtw** [comment]
Hey just adding on to this. Its happening for me as well on Ubuntu 18.04. The error message just says: 
⛔️ Connection test failed: spawn npm; ENOENT

Steps I took were:
1. strapi new [project-name]
2. mongo
3. and entering all the info

Has worked in the past but it fails immediately now and does not appear to attempt a connection.

Hope this may help any diagnosis!

**Comment by kresdjan** [comment]
I get the same error on Mac when using `Custom (manual settings)` and choosing either MongoDB or Postgres. Only the `Quickstart` option that uses sqlite works.

macOS: 10.15.2
node: v13.5.0
npm: v6.13.4

**Comment by dsciamma** [comment]
I have the same problem on windows with postgres

**Comment by cotyhamilton** [comment]
Same issue on mac with npx
- Strapi: Version 3.0.0-beta.18.2
- macOS: v10.14.6
- node: v10.14.2
- npm: v6.10.1
- database:
  - PostgreSQL
I installed yarn and used it instead to get this to work
