### ISSUE TITLE
Enum data type throws error while migrating in dynamic zone/components

### ISSUE THREAD

**Issue by jakeFeldman** [strapi/strapi#4786]
**Describe the bug**
Adding "Enum" to new dynamic zone/components throws an error.

```sh
[2019-12-21T08:21:51.057Z] error Migration failed
[2019-12-21T08:21:51.059Z] error error: syntax error at or near "check"
    at Connection.parseE (/Users/<directory>/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/Users/<directory>/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/Users/<directory>/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Steps to reproduce the behavior**
1. Create new component using content type builder
2. Select Enum data type
3. Add name and values
4. Hit "Finish" and then hit "Save"
5. In the console you should see the error after the server restarts.

**Expected behavior**
Migrations should run and be error free. When removing the enum data type and saving there is no error in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/25087876/71305431-27039e00-2391-11ea-9ea7-99f36da70e5e.png)

**Code snippets**
`/components/page-components/diptych.json`

```json
{
  "connection": "default",
  "collectionName": "page_component_diptych",
  "info": {
    "name": "diptych",
    "icon": "images"
  },
  "options": {},
  "attributes": {
    "background_image": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "is_full_width": {
      "type": "boolean",
      "default": false
    },
    "heading": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "cta_label": {
      "type": "string"
    },
    "cta_href": {
      "type": "string"
    },
    "icon": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "icon_position": {
      "type": "enumeration",
      "enum": [
        "left",
        "right"
      ]
    }
  }
}
```

**System**
- Node.js version: 10.15.3
- NPM version: v6.4.1
- Strapi version: 3.0.0-beta18.2
- Database: Postgres v11.4
- Operating system: MacOSX 10.14.6

**Comment by sprashivaesh** [comment]
I have this problem too

**Comment by lauriejim** [comment]
I just tried with `beta.18.3` and it works well.
📺[Here](https://www.loom.com/share/8995575983094f37a0f49f5dc2370cf2) is a record of what I did.

**Comment by jakeFeldman** [comment]
@lauriejim Thanks for looking into this. This was after upgrading to v18.2. I'm guessing my DB was in a bad state. I dropped all my tables and allowed Strapi to migrate to a fresh DB and the problem resolved itself. Thanks again. I think we can close this issue.
