### ISSUE TITLE
/upload return the url contains `localhost:1337` after migrate from beta.13 to beta.17.8

### ISSUE THREAD

**Issue by ly525** [strapi/strapi#4791]
**Describe the bug**
when the strapi version is: `3.0.0-beta.13`,
the `/upload` respnse is 

```json
[
    {
        "id": 1875,
        "name": "RjQkhE3OsrVv7uz.png",
        "hash": "b2c665392e044e7fb81019df4d4cd035",
        "sha256": "kfiz-6Iuc-Pcn3OCDn-Co1xCd9ieemgxSF56LYGqC5M",
        "ext": ".png",
        "mime": "image/png",
        "size": "222.58",
        "url": "/uploads/b2c665392e044e7fb81019df4d4cd035.png",
        "provider": "local",
        "provider_metadata": null,
        "created_at": "2019-12-21T14:36:17.716Z",
        "updated_at": "2019-12-21T14:36:17.716Z",
        "related": []
    }
]
```

but when I upgrade the strapi version to `3.0.0-beta.17.8`
the `/upload` response is 
````json
[
    {
        "id": 1875,
        "name": "RjQkhE3OsrVv7uz.png",
        "hash": "b2c665392e044e7fb81019df4d4cd035",
        "sha256": "kfiz-6Iuc-Pcn3OCDn-Co1xCd9ieemgxSF56LYGqC5M",
        "ext": ".png",
        "mime": "image/png",
        "size": "222.58",
        "url": "http://localhost:1337/uploads/b2c665392e044e7fb81019df4d4cd035.png",
        "provider": "local",
        "provider_metadata": null,
        "created_at": "2019-12-21T14:36:17.716Z",
        "updated_at": "2019-12-21T14:36:17.716Z",
        "related": []
    }
]
````

**Steps to reproduce the behavior**
##### 1. upload image then get `http://localhost:1337/uploads/xxx.png`
1. `git clone https://github.com/ly525/luban-h5`
2. `cd back-end/h5-api && yarn && yarn dev`
3. visit http://localhost:1337/admin/
4. upload image from the admin panel
5. you will see the image url is `http://localhost:1337/uploads/xxx.png`

##### 2. upload image then get `/uploads/xxx.png`
6. `git checkout fad25b8` # the strapi dependencies is beta.13 in this commit
7. rm -rf node_modules && yarn && yarn dev
8. visit http://localhost:1337/admin/
9. upload image from the admin panel
10. you will see the image url is `http://localhost:1337/uploads/xxx.png`

**Expected behavior**
1. this breaks my online product and makes me confused.
2. I do not want to config proxy in server.json and want to get `{url: '/uploads/xxx.png'}`, could you please do not add the host prefix url to the image url, because:
   - the host domain may change(many customers may use my product powered by strapi and they have their domain
   - we will save the image url to the database.

1. Can strapi provide  an option to keep the relative image path as before)
2. may you please revert to `{url: '/uploads/xxx.png'}`? thanks a lot!

**Screenshots**
![image](https://user-images.githubusercontent.com/12668546/71359530-ac709380-25c7-11ea-9982-584a722480ba.png)

![image](https://user-images.githubusercontent.com/12668546/71360944-6b2eb280-25cc-11ea-99b2-1794e10a1a83.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.8
- Database: sqlite3
- Operating system: Mac & Centos7

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by ly525** [comment]
@derrickmehaffy thanks, I have already updated the issue

**Comment by derrickmehaffy** [comment]
Reopening, thank you for updating it

**Comment by lauriejim** [comment]
I ping @alexandrebodin and @Aurelsicoko for this topic!

**Comment by alexandrebodin** [comment]
Actually this isn't a change we made recently. This is old code that just got fixed. I agree that we shouldn't add the domain part. Will do a fix for that.

**Comment by ly525** [comment]
> Actually this isn't a change we made recently. This is old code that just got fixed. I agree that we shouldn't add the domain part. Will do a fix for that.


Thanks for your understanding and the next work

**Comment by abdonrd** [comment]
> Actually this isn't a change we made recently. This is old code that just got fixed. I agree that we shouldn't add the domain part. Will do a fix for that.

@alexandrebodin @lauriejim Sorry to relive this old issue, but...

Why shouldn't the URL be prefixed?

In this way... When displaying the images from a web application:
- It work if we setup a provider like Cloudinary or so (because the absolute URL).
- It doesn't work if we setup the local provider (because the relative URL).

I think the behavior should be the same regardless of the provider you are using.
The web application shouldn't have to worry about whether the URL is coming from one site or another.

**Comment by abdonrd** [comment]
Meanwhile, from where could this logic change?
I am not clear where I could change this behavior with the current structure of the plugin.

**Comment by caraie** [comment]
> Actually this isn't a change we made recently. This is old code that just got fixed. I agree that we shouldn't add the domain part. Will do a fix for that.

Why it shouldn't include the domain?
When using a provider like strapi-provider-upload-cloudinary it includes the full url. It's tricky, because in a local environment you have to add manually the base url of the server, but in production you have to avoid that. For me it looks like inconsistent.
IMO to make it consistent it makes sense to have the localhot:1337 in a local dev environment and the provider URL in production.

**Comment by derrickmehaffy** [comment]
@caraie it might be good to post your thoughts on this on the pain points issue as this topic has come up a few times and it may be helpful to see how many also feel the same.

https://github.com/strapi/strapi/issues/10419

**Comment by alexandrebodin** [comment]
> > Actually this isn't a change we made recently. This is old code that just got fixed. I agree that we shouldn't add the domain part. Will do a fix for that.
> 
> @alexandrebodin Why it shouldn't include the domain?
> When using a provider like strapi-provider-upload-cloudinary it includes the full url. It's tricky, because in a local environment you have to add manually the base url of the server, but in production you have to avoid that. For me it looks like inconsistent.
> IMO to make it consistent it makes sense to have the localhot:1337 in a local dev environment and the provider URL in production.

What you say means you would need to use a provider in production but some user want a locale provider to write to a shared volumen in their infra & serve it with a CDN or something as simple as a nginx server for example. 
In the end we don't know where the file are served from (which domain / path). 

A solution you can think of is to add an option to specify which domain the files will be served from to to set it as prefix in db. But this makes it very hard for end users if then want to migrate file from one location to another (force to migrate their DB). to keep this flexibility we would need to add the prefix dynamically. 
I think we shared an example to add a prefix dynamically using a lifecycle function (@derrickmehaffy does that ring a bell ?). I think that this is a valid solution we could automate with an option maybe. Something like:

```
module.exports = {
  upload: {
    provider: 'locale',
    providerOptions: {
      dynamicallyPrefixed: true|false,
      basePath: 'https://my-domain/assets/some-sub-path'
    }
  }
}
```

**Comment by caraie** [comment]
>but some user want a locale provider to write to a shared volumen in their infra & serve it with a CDN or something as simple as a nginx server for example.

I'm talking about the development mode, strapi by default runs in the localhost:1337, so the API's should provide the media URI's pointing to localhost:1337/uploads/...
I don't want to point to cloudinary or a domain in development mode.

With the current implementation, if I have strapi running in the 1337 and a frontend running in the 3000, the frontend will try to find the images in localhost:3000/uploads/..., but the images should be in localhost:1337/uploads/...

**Comment by abdonrd** [comment]
> > but some user want a locale provider to write to a shared volumen in their infra & serve it with a CDN or something as simple as a nginx server for example.
> 
> I'm talking about the development mode, strapi by default runs in the localhost:1337, so the API's should provide the media URI's pointing to localhost:1337/uploads/...
> I don't want to point to cloudinary or a domain in development mode.
> 
> With the current implementation, if I have strapi running in the 1337 and a frontend running in the 3000, the frontend will try to find the images in localhost:3000/uploads/..., but the images should be in localhost:1337/uploads/...

Exactly! What I have wanted to say here: https://github.com/strapi/strapi/issues/4791#issuecomment-835337726

**Comment by alexandrebodin** [comment]
Yep agreed this is a specific case of adding a prefix dynamically it's just the default behaviour tu use the backend server url. 
In anycase we can't enable it without being able to configure the prefix & disable it. If you want to work on a PR let us know :)

**Comment by caraie** [comment]
I can take a look at it during this weekend, if we want to make it configurable, is there any preferred configuration for the prefix? (I never contributed to strapi before)

**Comment by derrickmehaffy** [comment]
@alexandrebodin the only one I've seen just injects the servers url into the path as a prefix, not dynamically but it shouldn't be too hard.

**Comment by ArianHamdi** [comment]
do you work on the issue ?
I need the domain prefix in image url.

**Comment by jvinhit** [comment]
i have same issue , image need domain prefix in url.

**Comment by thenotoriousjr** [comment]
> i have same issue , image need domain prefix in url.

Try this and see if it works?

`  const imageUrl = ( your query ); 
  const siteUrl = 'your URL here;

src={`${siteUrl}${imageUrl}`}`

temporary fix

**Comment by Henrissat** [comment]
so i have a problem to call the site url ine the return()
<img className="card" src=http://localhost:1337{item.img.data.attributes.url}/>
doesn't work !

**Comment by Henrissat** [comment]
so i have en problem to call the siteUrl in the return()

`
<img className="card" src="http://localhost:1337{item.img.data.attributes.url}"/>
`
they doesn't work !
