### ISSUE TITLE
Licence related question...

### ISSUE THREAD

**Issue by veerjainATgmail** [strapi/strapi#4792]
Hi,

The content manager plugin 
(https://strapi.io/marketplace/content-manager) says this plugin licence is AGPL. 
Can someone clarify on this? 

I do not see that mentioned in the strapi GitHub code. Is this MIT or AGPL licenced?
Am I missing some point here?

Thanks,
MJ.

**Comment by derrickmehaffy** [comment]
Even with no template I'll leave this one open

@lauriejim @Aurelsicoko can you clarify the license of the plugins (I believe they are MIT)

**Comment by lauriejim** [comment]
Hello! It's an issue on the website.
The license is MIT - see here in the repo https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/LICENSE.md
I will fix it. Thank you for reporting this.
