### ISSUE TITLE
A content type does not contains media field if it's in relation with a component

### ISSUE THREAD

**Issue by Danil44** [strapi/strapi#4795]
**Describe the bug**

I have a "categories" type that has relation with "foods" type, and a repeat "options" component that also has a relationship with type "foods". The "categories" type returns an array of "foods" with its media field, but the "options" component returns the same array WITHOUT a media field

**Steps to reproduce the behavior**
1. Create a content type "category",
2. Create a content type "food" and add some picture to its media field,
3. Add to "category" type a component "options" that has a relation "one to many" with "foods",
4. Go to "/categories" url, and you will see that "foods" inside of "options" component will not contain a media field

**Expected behavior**
Component return a media field

**Screenshots**
Food type:
![image](https://user-images.githubusercontent.com/40319337/71325806-d60fb900-24fa-11ea-9c94-e19b421f734d.png)

Category type: 
![image](https://user-images.githubusercontent.com/40319337/71325820-f2135a80-24fa-11ea-8456-0ca9c53a421c.png)

"/categories" result: 
![image](https://user-images.githubusercontent.com/40319337/71325981-330c6e80-24fd-11ea-92ce-ff50b782b0a8.png)

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.2
- Database: MySQL
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi @Danil44, This was intended to avoid loading to many levels of data. Will do a PR to add it for convenience
