### ISSUE TITLE
Content Manager plugin not working in admin UI in development mode

### ISSUE THREAD

**Issue by hyperion0201** [strapi/strapi#4801]
**System**
- Node.js version: 13.2.0
- NPM version: 6.13.1
- Strapi version: 18.2 beta
- Database: MongoDB
- Operating system: MacOS Catalina 10.15.2

Steps to reproduce the problem:

I did a fresh install of Strapi beta 18.2 (lastest)
strapi new demo-project
cd demo-project && strapi build && strapi develop
The Content Manager just loaded an error page (i attached a link of screenshot [here](https://i.imgur.com/6ImSuOl.png)).

**Comment by derrickmehaffy** [comment]
Can you post any error messages from the Strapi terminal (build process maybe?)

**Comment by hyperion0201** [comment]
I don't see any errors messages from the Strapi terminal (in build process too). it's just "DEBUG GET /content-manager/content-types, ..." and i can't see any error messages, so i can't figure what was the problem. But i think the content-manager plugin version 18.2 beta is the problem. Use the old as 17.8 beta and it worked.

**Comment by pravosud** [comment]
@hyperion0201, i had the same problem. Solved this by manually update strapi-helper-plugin to 18.2 version

**Comment by derrickmehaffy** [comment]
@hyperion0201 all the plugins need to be the same version, beta.18.3 was just released about an hour ago. (make sure you have no carrots `^` in strapi package versions)
