### ISSUE TITLE
Content manager UI doesn't allow setting of negative float

### ISSUE THREAD

**Issue by quentingllmt** [strapi/strapi#4803]
**Describe the bug**
The content manager UI in the administration panel doesn't allow me to set a new entry when a field 'number' (type float or double) is set to a negative decimal number (-1.5, -100.4, ...).

**Steps to reproduce the behavior**
1. Create a new content-type Test
2. Add in Test a new number field called test_field and set is format to double or float
3. Add a new entry with the content manager view (left column) and try to set the value to, for example -175.5. 
4. See error when saving : "Please enter a valid value. The two nearest valid values are...."

**Expected behavior**
I expect to be allowed to create new entries with negative decimal values.

**Screenshots**
![image](https://user-images.githubusercontent.com/10945434/71351715-adc4a080-2574-11ea-8ced-e94a5953ab7d.png)

**System**
- Node.js version: 12.14.0
- NPM version: 6.13.4
- Strapi version:  v3.0.0-beta.18.1
- Database: SQLLite
- Operating system: Ubuntu

**Additional context**
The values can be correctly set using the create route.

**Comment by derrickmehaffy** [comment]
@quentingllmt can you please test with the latest hotfix (beta.18.3) as I believe this was fixed in beta.18.2

**Comment by quentingllmt** [comment]
Hi Derrick,
Thanks for your fast answer, I'm using strapi docker, do I only need to update the pakcage.json then run npm install / build to update strapi ?

**Comment by quentingllmt** [comment]
Ok, I did it.
It has been fixed in Strapi v3.0.0-beta.18.2.
Thanks
