### ISSUE TITLE
Component get ID incremented after update

### ISSUE THREAD

**Issue by Stun3R** [strapi/strapi#4806]
**Describe the bug**
When updating a Content Type component the ID of the component just increment.

**Steps to reproduce the behavior**
1. Create a Content Type
2. Add a Component
3. Update the Content Type with PUT method and make change to the Component

**Expected behavior**
The ID of the component should not be incremented

**System**
- Node.js version: v12.13.1
- Strapi version: 3.0.0-beta.18
- Database: SQlite but might be the same bug for other
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
> The ID of the component should not be incremented

Understatement of the year right there :stuck_out_tongue_closed_eyes:

**Comment by TheRealBarenziah** [comment]
[I failed to reproduce your issue](https://youtu.be/UEzXYG8P1QM)
Could you please give more information about what you did & what you saw ?

**Comment by Stun3R** [comment]
> [I failed to reproduce your issue](https://youtu.be/UEzXYG8P1QM) (/e freshly generated app)
> Could you please give more information about what you did & what you saw ?

I think I failed to explain well the problem :D 
[Here an explanation video about it](https://youtu.be/3qxYcyTqPX0)

**Comment by lauriejim** [comment]
Hello @Stun3R thank you for reporting this.

By following the doc here about the entry update - https://strapi.io/documentation/3.0.0-beta.x/content-api/api-endpoints.html#update-an-entry

We can see you have to specify the `id`during a **component** update.
If you don't set the `id` of the entry you want to update, it creates a new component entry.

The question is - do we need to use the `id`if the compo is not repeatable?

@alexandrebodin is the best person to answer this question.

**Comment by alexandrebodin** [comment]
Hi, 

the id doesn't really change, the component is just replaced by a new one. You can verify that the component with the old id doesn't exist anymore. You need to provide the old id to update the component entry or it will replace it with a new one.

**Comment by MrObvi** [comment]
Is there any solution for this issue, I have the same problem. When I update (or publish) content the ID of the component gets incremented, even if I do not change anything in that component.
I use this ID and I need it to be stable.

**Comment by arilanto** [comment]
Hello,
I have the same issue here : when I update a content in admin panel (edit a content and publish), the id of my content is incremented, actualy strapi delete the previous one and create a new one.. 
I use Strapi v5.5 (an try to update to 5.6 but same behavior)

**Comment by eauneiladavan** [comment]
Hello,

I have different issue but it is related when updating a repeatable component with id, I'm specifying the id of it but I'm getting an invalid key error.

![Image](https://github.com/user-attachments/assets/dafed1f1-f50a-4083-88c9-ecdd0f0a526a).

Strapi version: 5.4.1
Node: 22.11.0

Hopefully this can fix.

**Comment by AlexisSniffer** [comment]
why close the issue if clearly this has not been resolved and is a big problem?

node: v20.15.0
strapi: 5.6.0

**Comment by GaryVoss** [comment]
I'm experiencing the same issue when updating content type entries in Strapi 5

Using DB Browser for SQLite I can see that when I create an entry, 2 DB rows are created with incremental id values.

<img width="1149" alt="Image" src="https://github.com/user-attachments/assets/76182839-4cbb-464c-abc0-b1789bdd5231" />

The first row seems to be the draft version of the entry, which is updated when I 'Save' the entry in the Strapi CP, and the second row is the published version, which is updated when I 'Publish' the entry.

Every time I publish changes in the Strapi CP, the second row's id increments by 1; however, the first row retains it's original id when saving or publishing the entry.

The Strapi CP displays the first row's id whereas my Next.js app display the second row's id.

<img width="1084" alt="Image" src="https://github.com/user-attachments/assets/29a693f4-b668-43e9-b5d7-7591099ad5c6" />

This make the id useless in my Next.js app as I need it to remain the same.

As the id increments are happening when I publish data directly into the Strapi CP then it seems to be a core issue or perhaps even a intended action within Strapi.

Strapi version: 5.3.0
Node: 18.18.0

**Comment by derrickmehaffy** [comment]
It is absolutely intended for our content history feature (for the enterprise edition).

In most use cases this ID should be completely ignored.

**Comment by GaryVoss** [comment]
Thanks for confirming @derrickmehaffy.

**Comment by Jishnusu** [comment]
im facing same issue is there any solution ?

**Comment by estephanobrusa** [comment]
Hi,
I have the same issue, currently I use documentId to workaround the problem
