### ISSUE TITLE
Error on tables creation when components has uuid type as id

### ISSUE THREAD

**Issue by josianyman** [strapi/strapi#4807]
**Describe the bug**
Strapi fails to create `owner_components`-table if the `owner` content type ids are uuid.

Strapi tries to create column `owner_id integer` and foreign key constraint `owner_id references owner (id)`. This cause error because integer and uuid are incompatible types.

**Steps to reproduce the behavior**
1. Create simple `owner` content type.
2. Set `owner` `idAttributeType: uuid`
3. Create simple `child` component type
3. Add repeatable `child` component to `owner`
4. Remove database tables and start Strapi
5. See errors and wrong column types in `owner_components` table

**Expected behavior**
Component table `owner_id` column type should be uuid instead integer.

**Screenshots**
The database tables:

![image](https://user-images.githubusercontent.com/15654964/71359096-e162f300-2593-11ea-9ddd-52da3ab6af91.png)

**Code snippets**
Owner content type model:
```
{
  "connection": "default",
  "collectionName": "owner",
  "info": {
    "name": "Owner"
  },
  "options": {
    "idAttributeType": "uuid",
    "uuid": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "child": {
      "type": "component",
      "repeatable": true,
      "component": "default.child"
    }
  }
}
```

Child component:
```
{
  "info": {
    "name": "Child",
    "icon": "address-book"
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string"
    }
  },
  "connection": "default",
  "collectionName": "child"
}
```
**System**
- Node.js version:  v12.13.1 
- NPM version: v6.12.1
- Strapi version: 3.0.0-beta.18 
- Database: postgresql
- Operating system: macOS Catalina

**Comment by lauriejim** [comment]
Thank you @josianyman for reporting this issue.

**Comment by alexandrebodin** [comment]
the idAttribute is known not to work. The issue hasn't been addressed for very long. I would suggest you avoid using this feature at all.

**Comment by lauriejim** [comment]
Hello! I'm closing this issue since we remover this option in the stable version of Strapi.
