### ISSUE TITLE
Get totalCount when paginate a relationship

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#4808]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**

Hello! In this kind of query where `matchdays` is a relationship:

```graphql
query GetUser($matchdaysLimit: Int, $matchdaysStart: Int) {
  user(id: "5d18957887089800179fea91") {
    name
    matchdays(limit: $matchdaysLimit, start: $matchdaysStart) {
      id
    }
  }
}
```

I need to paginate the `matchdays`, so I'm going to use `limit` and `start` fields...
But how can I know the `totalCount` of the `matchdays`?

**Comment by alexandrebodin** [comment]
Currently there is no pagination in the plugin. The graphql schema needs to be changed

**Comment by jesusprubio** [comment]
+ 1 here

**Comment by Tansito** [comment]
Awesome, it could be really nice to have this!

**Comment by CAJazzer** [comment]
You can get the count by defining an aggregate resolver.  See this example:
https://github.com/strapi/foodadvisor/wiki/3.-Back-end

**Comment by abdonrd** [comment]
@alexandrebodin Any news here?

**Comment by lauriejim** [comment]
Hello @abdonrd , we are not working on that topic right now.
And it's not a prio for us now so I don't know when or if we will work on it.

**Comment by neudysrd** [comment]
@abdonrd You can use **userConnector** query, this return count and totalCount.

This query is generated automatically when you created **user** collection.

**Comment by abdonrd** [comment]
@neudysrd check the query of the main post, what I want is to paginate the relationship with the matchdays 😊

**Comment by neudysrd** [comment]
@abdonrd You can get totalCount using userConnector query. Then you do the pagination

**Comment by abdonrd** [comment]
> @abdonrd You can get totalCount using userConnector query. Then you do the pagination

Could you show me what the query would be like? Thank you!

**Comment by neudysrd** [comment]
@abdonrd check this on your playground

`
# Write your query or mutation here
{
  usersConnection{
    values{
      firstName
    } 
    aggregate{
      count
      totalCount
    } 
  } 
} 
`

**Comment by abdonrd** [comment]
But this is the count for the users... I want it for the matchdays relationship.

**Comment by nmitra6** [comment]
Is version 3.3 is production ready for any serious work ?

**Comment by derrickmehaffy** [comment]
> Is version 3.3, production ready for any serious work ?
> Without any time frame for version 4, is it worth to start using Strapi ?
> It feels like, this project is on siesta.

Yes we have numerous people using Strapi in production with v3, you can continue to use v3 until v4 launches.

v4 rough timeline is a beta at the end of Sept and stable v4 release will be +1 month after public beta.

**Comment by boazdejong** [comment]
@derrickmehaffy Why was this removed from the milestone?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Why was this removed from the milestone?

Because we weren't able to ship it in the first release. Not sure if/when it's coming.

Was trying to test the other day and it's not possible to page yet, but you can filter.

**Comment by derrickmehaffy** [comment]
Currently not possible and we do not plan to add support for this as we cannot currently paginate relationships.

Marking as closed as discussed with @Aurelsicoko

**Comment by the94air** [comment]
The way this feature has been evaluated in the first place was strange 😕
