### ISSUE TITLE
Strapi doesn't start in Heroku after upgrading to beta.18

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#4810]
Describe the bug
Update from beta.16.2 to beta.18 is OK in local. When deployed to heroku, build gives this output.
 

> 2019-12-23T17:12:31.378067+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/graphql"  status=503 bytes= protocol=https
> 2019-12-23T17:12:43.798256+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/graphql" status=503 bytes= protocol=https
> 2019-12-23T17:13:13.361258+00:00 app[api]: Starting process with command `strapi build` by user xxx
> 2019-12-23T17:13:55.614800+00:00 heroku[run.8712]: State changed from starting to up
> 2019-12-23T17:13:55.691550+00:00 heroku[run.8712]: Awaiting client
> 2019-12-23T17:13:55.720041+00:00 heroku[run.8712]: Starting process with command `strapi build`
> 2019-12-23T17:14:38.956004+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/graphql"  status=503 bytes= protocol=https
> 2019-12-23T17:14:43.237641+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/graphql" status=503 bytes= protocol=https
> 2019-12-23T17:14:45.999337+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/robots.txt" status=503 bytes= protocol=https
> 2019-12-23T17:14:50.097929+00:00 heroku[run.8712]: State changed from up to complete
> 2019-12-23T17:14:49.856733+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/graphql" tatus=503 bytes= protocol=https
> 2019-12-23T17:14:50.081969+00:00 heroku[run.8712]: Process exited with status 0

And then when trying to do a `strapi start`, the output is:

> error Error: ENOENT: no such file or directory, open '/app/public/production.html'
>     at Object.openSync (fs.js:456:3)
>     at Object.readFileSync (fs.js:358:35)
>     at Object.initialize (/app/node_modules/strapi/lib/middlewares/public/index.js:39:24)
>     at /app/node_modules/strapi/lib/middlewares/index.js:43:28

Steps to reproduce the behavior
1.- Open an account on Heroku.
2.- Create an app with Strapi beta.16.2 and postgresql as DB in production
3.- Update to beta.18 following the guide
4.- Deploy to Heroku

Expected behavior
Deployment is OK and admin opens.

System

Node.js version: v10.15.2
NPM version: 6.13.4
Strapi version: 3.0.0-beta.18
Database: MySQL(local) / PostgreSQL (heroku)
Operating system: Ubuntu 19.10

**Comment by alexandrebodin** [comment]
Hi, there is a step in the migration guide on how to create the production.html file you are missing ;) https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#adding-new-root-page-files
