### ISSUE TITLE
"form.button.finish" on the my button in Content-Type-Builder

### ISSUE THREAD

**Issue by EugeneFox78** [strapi/strapi#4814]
1. I created a Content Type.
2. Then added to it a field "name" of type "Short text".
3. Saved the changes.
4. Opened the content type for change and clicked on the "name" field.
5. The green button contains the inscription "form.button.finish"
![Снимок экрана в 2019-12-24 10-41-12](https://user-images.githubusercontent.com/52984888/71392249-01e58880-263a-11ea-94e3-1bd99441fdbc.png)

When trying to customize, I managed to change the labels on the buttons "Add another field" and "Cancel", but not on this one.
![ide](https://user-images.githubusercontent.com/52984888/71392183-cfd42680-2639-11ea-8316-95d215635505.png)

### System
Node.js version: v12.13.1
NPM version: 6.12.1
Strapi version: 3.0.0-beta.18.2
Operating system: Ubuntu 18.04 x64

**Comment by lauriejim** [comment]
Hello! I'm using the `beta.18.3`and it looks working.
[📽Here](https://www.loom.com/share/62923bc422664f25a6fdfcf17623cbb4) is a record of what I did.

**Comment by EugeneFox78** [comment]
> Hello! I'm using the `�beta.18.3`�and it looks working.
> [film_projectorHere](https://www.loom.com/share/62923bc422664f25a6fdfcf17623cbb4) is a record of what I did.

I figured it out. The problem is localization.
I used basic localization through "project_root/admin/src/translations/xxx.json" and "form.button.finish" is here. But "form.button.cancel" and "form.button.add-field" are in "project_root/extentions/content-type-builder/admin/src/translations"

**Comment by lauriejim** [comment]
Ho okay! So you customized the translations.
Well, the translation keys position is important.
After that, we will a big review of non-used translation key and have some consistency inside the position of these keys.

I close this issue. 
Thank you for reporting this.
