### ISSUE TITLE
Custom GraphQL mutation doesn't work

### ISSUE THREAD

**Issue by red-sight** [strapi/strapi#4819]
Hello!
Can't do with mutations

**Steps to reproduce the behavior**
1. Create any local or global controller for graphql mutation
2. Create any local or global policy
3. Describe the mutation in API schema and add the controller for it
4. Run graphql query with this mutation and see at console that controller runs, even if our policy returning ctx.unauthorized.
![image](https://user-images.githubusercontent.com/2592568/71415277-5c9bd600-2674-11ea-8cff-9eb7e9ceeaa0.png)

**Expected behavior**
Controller shouldn't run if policy gives unauthorized responce.

**Code snippets**

Controller (./api/secret/controllers/Secret.js)
```javascript
module.exports = {
  someSecret: async ctx => {
    console.log("In someSecret controller instead :-(");    
    return true;
  }
};
```

Policy (./config/policies/isOwner.js)
```javascript
module.exports = async (ctx, next) => {
  console.log("In isOwner policy");
  ctx.unauthorized("Not permitted");
  return await next();
};
```
Schema (.\api\secret\config\schema.graphql)
```javascript
module.exports = {    
  mutation: `
    someSecret(id: ID): Boolean
  `,
  resolver: {
    Mutation: {
      someSecret: {
        policies: ['global.isOwner'],
        resolver: 'secret.someSecret'
      },
    }
  }
}
```

**System**
- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: v3.0.0-beta.17.8
- Database: Mongo
- Operating system: Win 10

**Comment by derrickmehaffy** [comment]
Can you test on the latest beta please (beta.18.3)

**Comment by red-sight** [comment]
> Can you test on the latest beta please (beta.18.3)

Tested now on v3.0.0-beta.18.3
the same behaviour

**Comment by red-sight** [comment]
I have noticed that such happens only if policy runs with custom mutation. If I add policy to automatically created mutation, the resolver runs if it should.

**Comment by red-sight** [comment]
Is there any solution or a direction if I do something wrong?
I still have to write the policy logic for my custom mutations right in the controller..

**Comment by lauriejim** [comment]
Hello! After reading your policy, you `return await next();` so you say to continue in the middleware stack.

If you want to stop it and say you are unauthorized, you have to `return ctx.unauthorized("Not permitted");` to not trigger the `next` function.

**Comment by red-sight** [comment]
> Hello! After reading your policy, you `return await next();` so you say to continue in the middleware stack.
> 
> If you want to stop it and say you are unauthorized, you have to `return ctx.unauthorized("Not permitted");` to not trigger the `next` function.


ok, then if I change to, for example,

```javascript
module.exports = async (ctx, next) => {
  console.log("In isOwner policy");
  if (true) {
    return ctx.unauthorized("Not permitted");
  } else {
    return await next();
  }
};
```
The behaviour will be the same - policy runs custom mutation instead of ctx.unauthorized

**Comment by goodok21** [comment]
not sure, but you can try:

```js
throw new Error('Error message');
```

**Comment by alxistn** [comment]
> not sure, but you can try:
> 
> ```js
> throw new Error('Error message');
> ```

It works

**Comment by lauriejim** [comment]
Thank you for this workaround.

**Comment by red-sight** [comment]
> not sure, but you can try:
> 
> ```js
> throw new Error('Error message');
> ```

This works,
but server response returns a lot of unnecessary info that we shouldn't open to client side:
```{
    "errors": [
        {
            "message": "Not authorized!",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createSecret"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "Error: Not authorized!",
                        "    at module.exports (C:\\Users\\dmala\\nodejs\\mutation-issue\\config\\policies\\denyToAll.js:19:9)",
                        "    at dispatch (C:\\Users\\dmala\\nodejs\\mutation-issue\\node_modules\\koa-compose\\index.js:42:32)",
                        "    at module.exports (C:\\Users\\dmala\\nodejs\\mutation-issue\\node_modules\\strapi-plugin-users-permissions\\config\\policies\\permissions.js:111:9)",
                        "    at async C:\\Users\\dmala\\nodejs\\mutation-issue\\node_modules\\strapi-utils\\lib\\policy.js:111:7",
                        "    at async C:\\Users\\dmala\\nodejs\\mutation-issue\\node_modules\\strapi-plugin-graphql\\services\\Mutation.js:200:22"
                    ]
                }
            }
        }
    ],
    "data": {
        "createSecret": null
    }
}```

**Comment by JuniYadi** [comment]
> not sure, but you can try:
> 
> ```js
> throw new Error('Error message');
> ```

i'm facing same issue, but with policy in GraphQL default (not custom), when using `return ctx.unauthorized(`You're not allowed to perform this action!`)`, look like graphql mutation still continue execution after return a error pages (try in delete mutation).

but after using `throw new Error('not allowed')`. it's stop directly.

**Comment by lauriejim** [comment]
I will close this issue because it's the way it should work.
Based on the last policy functions that are in the core of Strapi.
