### ISSUE TITLE
Issue with upgrading to 18.3

### ISSUE THREAD

**Issue by altaygileren** [strapi/strapi#4820]
**Describe the bug**
I delete the .cache, build, package-lock, and node_modules files and directories and try to follow the Strapi docs to migrate to 18.3 and after I npm run build and then develop I run into an error of 

[2019-12-24T14:56:25.390Z] debug ⛔️ Server wasn't able to start properly.
[2019-12-24T14:56:25.391Z] error ConnectorError: connector "strapi-hook-mongoose" not found: Cannot find module 'strapi-connector-strapi-hook-mongoose'

What I did was removed the strapi-hook-mongoose from the package file and replaced it with the strapi-connector-mongoose package

**Expected behavior**
Upgrade from 17.5 to 18.3

**System**
- Node.js version: 10.0.0
- NPM version:
- Strapi version: 17.5
- Database: Mongoose
- Operating system: Mac

**Comment by alexandrebodin** [comment]
@altaygileren You forgot a step https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#database-configuration You need to update the `database.json` config too :)
