### ISSUE TITLE
No relationship when importing data

### ISSUE THREAD

**Issue by altaygileren** [strapi/strapi#4821]
**Describe the bug**
I posted this in the Slack channel a few times and no response by anyone so I'm posting it here. I imported data from a JSON file to MongoDBAtlas with the relationship fields intact with the ID of who it is related to in the field and the relationship is only reflected in one place.. so for example

I have bins and users... when I import the bin I have a field of 'user' which contains the users ID... after the import if I look at a bin I can see the users ID it is related to... but if I click the user and view their bin relationship it shows 0. 

**Expected behavior**
Relationships showing

**System**
- Node.js version: 10.0.0
- NPM version:
- Strapi version: 17.5
- Database: MongoDB Atlas
- Operating system: Mac

**Comment by lauriejim** [comment]
Hello! Can you please open this question on StackOverflow.
And can you add the command you use to export / import your database.
This issue is probably related to your import / export rather that strapi itself.
Thank you.
