### ISSUE TITLE
Adding new custom field types

### ISSUE THREAD

**Issue by niallobrien** [strapi/strapi#483]
Hi, I'd like to explore the possibility of creating new field types to further expand what's already within Strapi. How would I go about this?

Thanks in advance.

**Node.js version**: 8.9.0
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.6.7
**Operating system**: Windows 7 Enterprise

**Comment by soupette** [comment]
Hi @niallobrien you'll have to modify the content-type-builder plugin and the content-manager plugins.
In order to do so you have to start your project in [development mode](https://strapi.io/documentation/plugin-development/quick-start.html)

**Steps to display your new input in the content type builder**
- To display your new field you'll have to add it in the `/plugins/content-type-builder/admin/src/containers/Form/forms.json`file. 
- You'll have to add the corresponding translations in the `/plugins/content-type-builder/admin/src/translations` folder
- From now on you're able to display your new attribute in the plugin (this might have an impact on the plugin's component) 
- You won't have to modify the actions or reducer of the plugin's front-end part.

**Use your new type in the content manager**
- In the content manager plugin you'll have to modify the `Edit` container and its children in order to display your new field type.
- You'll have to either create a new input type in the `strapi-helper-plugin/src/components/Input/index.js` file or a new Input directly in your plugin's `admin/src/components` folder and import it in the `content-manager/admin/src/admin/components/EditForm/index.js` file.
 
**Adding a new type is not optimal at the moment you might have to modify the core of this two plugins.**

**Comment by niallobrien** [comment]
Thanks for the info. Are there plans to make this process more modular in the future?

**Comment by soupette** [comment]
Well we're currently working on the upload, but since the Input Library has been redone it should be normally easier to create new types (for the front end part), you'll will just have to edit a json file if the GUI doesn't contain it already. However it's not on our short-term road map to allow to create custom field from the GUI 🏗🏗..

**Comment by UserGalileo** [comment]
Hi guys! I'm looking at Strapi cause I really need a new Headless CMS, I like a LOT of things I've seen in Strapi but this feature in particular would be essential and could be a game changer in the CMS scenario.

In particular, what I'd need is the "Location" field, a-la Contentful.

If this enhancement is difficult to implement (I believe so), could I ask if you could include a location field type soon? Thanks, and compliments!

**Comment by Daekan** [comment]
I'm also considering to use Strapi but I don't feel confident using it without a feature to add custom field types...

This is a must.

**Comment by Daekan** [comment]
@UserGalileo Did you find a solution for this or did you choose other CMS?

**Comment by UserGalileo** [comment]
@Daekan I don’t need it right now, but I’m also looking at graphCMS which should implement that feature and it’s GraphQL based :) I’m keeping an eye on both!

**Comment by victorkane** [comment]
The great virtue of Strapi.io is that it is a completely open source CMS. This practically doesn't really exist in today's world, believe it or not. They all want to keep your stuff in the cloud behind a paywall and give you toys, like graphCMS, like [contentful and others](https://www.cmswire.com/web-cms/13-headless-cmss-to-put-on-your-radar/) or else are oldish or directly abandoned, like Keystone. Strapi.io is open, I've just started using it and I'm amazed at how it creates my API automatically, including the basic code. You can even develop templates and use these from the command line generator. Also, the road is open to develop and make pull requests (I only hope I'll be able to do this in the future). So I don't think it's fair to compare something like graphCMS (completely behind a paywall) and a community driven open source project.

**Comment by UserGalileo** [comment]
@victorkane GraphCMS is going open source this month with the beta release for testing and they are doing an awesome job to improve the platform :)

**Comment by harmjanluth** [comment]
Anyway.. +1 for custom fields. Mandatory feature.

**Comment by Clonk-HTML5** [comment]
+1 for custom fields. Mandatory feature.

**Comment by bkd705** [comment]
+1 for this one. Would be open to assisting in implementation, am a bit new to Strapi however so some direction would be wonderful if possible.

**Comment by MWalid** [comment]
+1 too

**Comment by soupette** [comment]
@bkd705 do you mean adding a new type of field in the content-type-builder or customising the content-manager with new fields?

**Comment by gianniskarmas** [comment]
@soupette IMHO any solution to make it easier to add custom fields to users would be great.

**Comment by roonie007** [comment]
+1

**Comment by selected-pixel-jameson** [comment]
+1

**Comment by Aurelsicoko** [comment]
This feature will be implemented. Please upvote and give us more insights via Product Board (https://portal.productboard.com/strapi/c/10-custom-fields).

**Comment by derrickmehaffy** [comment]
@steampixel if you haven't already you can also send your support on the product board page as well :)

**Comment by tsan** [comment]
> Hi @niallobrien you'll have to modify the content-type-builder plugin and the content-manager plugins.
> In order to do so you have to start your project in [development mode](https://strapi.io/documentation/plugin-development/quick-start.html)
> 
> **Steps to display your new input in the content type builder**
> 
> * To display your new field you'll have to add it in the `/plugins/content-type-builder/admin/src/containers/Form/forms.json`file.
> * You'll have to add the corresponding translations in the `/plugins/content-type-builder/admin/src/translations` folder
> * From now on you're able to display your new attribute in the plugin (this might have an impact on the plugin's component)
> * You won't have to modify the actions or reducer of the plugin's front-end part.
> 
> **Use your new type in the content manager**
> 
> * In the content manager plugin you'll have to modify the `Edit` container and its children in order to display your new field type.
> * You'll have to either create a new input type in the `strapi-helper-plugin/src/components/Input/index.js` file or a new Input directly in your plugin's `admin/src/components` folder and import it in the `content-manager/admin/src/admin/components/EditForm/index.js` file.
> 
> **Adding a new type is not optimal at the moment you might have to modify the core of this two plugins.**

Hi,

I try your way but when, on the admin, I add the custom field and save, the server stopped.
There is the error: UnhandledPromiseRejectionWarning: TypeError: Invalid value for schema path `Email.type`

I look to where the schema is generated and I can't find it.
I'm start strapi with MongoDB and looking to have custom field in Object format.

Thanks,

**Comment by cwahlfeldt** [comment]
+1 need this so I can kill off wordpress + acf please 👍

**Comment by ChristopherDosin** [comment]
So in fact currently it's not really possible to create custom content fields?

**Comment by derrickmehaffy** [comment]
@ChristopherDosin possible yes. difficult also yes. deployment after creation? Very difficult. Upgradability on strapi versions and keeping modifications? near impossible at the moment.

**Comment by ChristopherDosin** [comment]
@derrickmehaffy argh .. okay. Hopefully, those custom fields will come in the near future. Maybe we should start a fundraising for this incredibly useful feature? ^^

**Comment by derrickmehaffy** [comment]
@ChristopherDosin the problem is not funds, it's lack of outside contributors. The Strapi team is quite busy working on other more important stuff right now. If someone else wanted to take up development of this they are welcome to submit a PR.

**Comment by ChristopherDosin** [comment]
@derrickmehaffy Understand - I would if i could :) But i am not that Node.js / Strapi / JS Guru to submit such a PR .. :(

**Comment by derrickmehaffy** [comment]
There are quite a number of other important feature requests as well: https://portal.productboard.com/strapi/tabs/2-under-consideration but I am in the same boat @ChristopherDosin

**Comment by ChristopherDosin** [comment]
@derrickmehaffy Do you know a headless CMS where it's possible to create such a custom field? We need to fetch some Data from an API and bundle this to a custom field type.
I know Prismic - But there you would need a specific data structure, which is also not the best option, because you have another application running which converts the API to the given needs ..

**Comment by cwahlfeldt** [comment]
@ChristopherDosin This might be a long shot but... WordPress with the plugins: Advanced Custom Fields and ACF to Rest API. Then use the Rest API to grab data. Not sure how to pull api data to populate a custom strapi field though.

ACF (Advanced Custom Fields) provides all the functionality I would like to see in Strapis custom fields. Obviously its a different architecture and approach but ACF gets it right when it comes to fields. Its worked for every single client Ive served for the last 5 years doing WP dev. The `Flexible Content` especially allows me to make any data model I need for content creators.

https://www.advancedcustomfields.com/

p.s. rant:
This is the most important feature for me and my workflow. This would push Strapi beyond a "possible" solution for my clients, and actually become a viable, real solution that I can sell to business's. With that said I totally understand the team has obligations and more important structural features but without this I cant adopt strapi just yet but, Im hoping I can sooner than later :)

Cheers!

**Comment by derrickmehaffy** [comment]
> p.s. rant:
> This is the most important feature for me and my workflow. This would push Strapi beyond a "possible" solution for my clients, and actually become a viable, real solution that I can sell to business's. With that said I totally understand the team has obligations and more important structural features but without this I cant adopt strapi just yet but, Im hoping I can sooner than later :)

Trust me, lots of us have "deal breaking" bugs and features we want, hence why I would like to see other contributors with higher skills sets than myself help build the features they want. This is an open source project after all :wink: (I'm not a member of the Strapi team)

**Comment by lapphan** [comment]
Will it possible to add a custom field type like "ValueWithUnit" with this future feature?
Currently I manage to do it in Strapi with JSON field: 
`{
  "value": 14
  "unit": "mm",
}`
and can filter it through GraphQL endpoint.
But it will be nice if we can have a custom filed type to display it properly in Content Manager screen. It's empty now:
![image](https://user-images.githubusercontent.com/11986206/55932572-74e9d300-5c54-11e9-9a8d-ab903dcfc883.png)

**Comment by Aurelsicoko** [comment]
Yes, we rewrote the plugin to accept custom field in the future. We don't support it for now but don't worry we have this feature in mind.

**Comment by dhniels** [comment]
I see this is closed, was this feature added?

**Comment by derrickmehaffy** [comment]
@dhniels It has not, if you see here: https://github.com/strapi/strapi/issues/483#issuecomment-437675592

It was moved over to the Feature Request tracking (ProductBoard)

**Comment by sheerun** [comment]
Still not implemented?

**Comment by ChristopherDosin** [comment]
> Still not implemented?

No, but you can contribute ;)

**Comment by sheerun** [comment]
Any tips?

**Comment by danielbidala** [comment]
Hi. I'm on laravel at the moment but thinking to learn node.js. I've found strapi today and it seems very promising but without custom form field types and custom list column types it's unusable for my projects.

Now I use October CMS for backend apps, it's based on laravel so I think it's not an option for you guys. It has all the feature you missing from strapi in this issue. Hope custom fields and list column types will be implemented.

**Comment by freemh** [comment]
> @ChristopherDosin This might be a long shot but... WordPress with the plugins: Advanced Custom Fields and ACF to Rest API. Then use the Rest API to grab data. Not sure how to pull api data to populate a custom strapi field though.
> 
> ACF (Advanced Custom Fields) provides all the functionality I would like to see in Strapis custom fields. Obviously its a different architecture and approach but ACF gets it right when it comes to fields. Its worked for every single client Ive served for the last 5 years doing WP dev. The `Flexible Content` especially allows me to make any data model I need for content creators.
> 
> https://www.advancedcustomfields.com/
> 
> p.s. rant:
> This is the most important feature for me and my workflow. This would push Strapi beyond a "possible" solution for my clients, and actually become a viable, real solution that I can sell to business's. With that said I totally understand the team has obligations and more important structural features but without this I cant adopt strapi just yet but, Im hoping I can sooner than later :)
> 
> Cheers!

Custom fields are the most important aspect of having better control over the app by adding multiple and different forms of content. I'm really not 100% into Strapi because of custom fields, I love to see this feature in the near future.

**Comment by lauriejim** [comment]
Hello, an update about this topic.
This coming step by step.

"Currently, we have added this feature to the administration panel ([documentation here](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/frontend-field-api.html )) which is the first step to the adding custom fields to your project. It works great if you add them manually but the content-type-builder does not support it yet."

cc @soupette author of this quote.

**Comment by beve** [comment]
@lauriejim Yeah, great news ! It really the killer feature i was expecting to switch to Strapi for my projects.

Thanks for all this work.

**Comment by lichaar** [comment]
@lauriejim @soupette Really looking forward to this, Finally Strapi is coming to a stage which can be used for much more projects.

**Comment by SuperMasterBlasterLaser** [comment]
@lauriejim 

Is it possible to create custom field based on existing fields like jsonfield? I wan't to create new type of field and assign it to my content types

**Comment by lauriejim** [comment]
Hello! It's not possible to create a new field, but your can update the JSON field that currently exist in Strapi to make it matches your need.
Here is an example with the [WYSIWYG inpu](https://strapi.io/documentation/v3.x/guides/registering-a-field-in-admin.html)t.

**Comment by guanghw** [comment]
For the moment，create new field by customized jsonfield， is good idea!but it's limited ,a project can only have one custom field,i think may jsonfiled have an optional attribute,like 'subtype' or else,then our customize field can use this for show a different look

**Comment by katiasmet-studiohyperdrive** [comment]
Is this still not possible? For example with a plugin? I try to create a plugin for a new type of field ,but it doesn't show up in the field selector.

**Comment by derrickmehaffy** [comment]
> Is this still not possible? For example with a plugin? I try to create a plugin for a new type of field ,but it doesn't show up in the field selector.

You can't currently inject new fields into the content-type builder but you can add custom fields manually. For example see: https://www.paulgaumer.com/blog/how-to-create-a-color-picker-plugin-for-strapi-cms

Just note that the `columnType` needs to match a data type **for your database**. Attempting to modify a model with a custom field set manually through the .json config will throw errors and likely break the model.

**Comment by rullymartanto** [comment]
I have try that tutorial but when I am using version 3.6.5 it won't work
I think because this issue
![image](https://user-images.githubusercontent.com/5577057/128471533-da653b66-b91e-4894-ad66-602fbcb4ee89.png)

in version 3.2.5 
![image](https://user-images.githubusercontent.com/5577057/128471646-e42013c4-7615-4046-a006-d82f29c6a25a.png)

**Comment by sinkng** [comment]
I was able to add custom field in Strapi (as of writing Strapi v4.0.3).

The change was simple - just 1 line of code in Strapi "content-manager" source code to render your registered custom fields, which are registered through your custom plugins.

- Recap: Strapi allows your custom plugins to be registered as well as to be registered as a custom field.

- This change does not break "content-type-builder" or interfere any other processes those are put in placed for Strapi to work.

- Currently working on a demo, I'll post a link here soon.
- Next I will work on allow "content-type-builder" to pickup registered custom fields and able to config them.

**Comment by derrickmehaffy** [comment]
> I was able to add custom field in Strapi (as of writing Strapi v4.0.3).
> 
> The change was simple - just 1 line of code in Strapi "content-manager" source code to render your registered custom fields, which are registered through your custom plugins.
> 
> * Recap: Strapi allows your custom plugins to be registered as well as to be registered as a custom field.
> * This change does not break "content-type-builder" or interfere any other processes those are put in placed for Strapi to work.
> * Currently working on a demo, I'll post a link here soon.
> * Next I will work on to allow "content-type-builder" to pick-up registered custom fields, config them and save them.

Ping me when you post here :)

**Comment by sinkng** [comment]
@derrickmehaffy 
Here is the video about Strapi v4 Custom Field Type Renderer
- [https://youtu.be/3of3s_xhEnE](https://youtu.be/3of3s_xhEnE)

**Comment by soupette** [comment]
@sinkng very cool, in schema.json you can use the `pluginOptions` object in order to set some custom config, you'll then be able to retrieve them in the admin in the `fieldSchema` object.

**Comment by sinkng** [comment]
> @sinkng very cool, in schema.json you can use the `pluginOptions` object in order to set some custom config, you'll then be able to retrieve them in the admin in the `fieldSchema` object.

Thank you @soupette for your pointer. Very much appreciated. There's a lot more to learn about Strapi but I am falling in love with it even though we just met for 1 week. Great job Strapi Team.

**Comment by 524c** [comment]
> The great virtue of Strapi.io is that it is a completely open source CMS. This practically doesn't really exist in today's world, believe it or not. They all want to keep your stuff in the cloud behind a paywall and give you toys, like graphCMS, like [contentful and others](https://www.cmswire.com/web-cms/13-headless-cmss-to-put-on-your-radar/) or else are oldish or directly abandoned, like Keystone. Strapi.io is open, I've just started using it and I'm amazed at how it creates my API automatically, including the basic code. You can even develop templates and use these from the command line generator. Also, the road is open to develop and make pull requests (I only hope I'll be able to do this in the future). So I don't think it's fair to compare something like graphCMS (completely behind a paywall) and a community driven open source project.

Strapi is one of the tools I love the most right now. VueJS + Strapi + GraphQL + Insomnia = ❤️
