### ISSUE TITLE
Bug on Component with two media inputs

### ISSUE THREAD

**Issue by atlmtw** [strapi/strapi#4831]
**Describe the bug**
Currently my component that I created with two "media" fields is sharing the same file upload. So when a file is removed from one of the media inputs, the other media input has its file removed. And vice versa for uploading. (Happens for both single and multi upload media fields)

**Steps to reproduce the behavior**
1. Go to content type with component
2. Upload a pdf in one of the media input fields
3. Click Save
4. Come back to component entry in content type to see both media input fields being filled

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB
- Operating system: Ubuntu 18.04

**Additional context**
Originally built Strapi with beta 17.8. Afterwards I saw 18.3 fixed some issues we were having and so we made an upgrade. We followed the migration guide and everything worked well. First I created a component with only one media input field. And I made some uploads to them. However, I realized that I was missing another media input field afterwards. So I went back to the content type builder for the component and added another input field. After creating it, I noticed the new field was pre-populated with the file from the previous media input field. After experimenting around, I started facing the issues described above.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue!
I ping @alexandrebodin about that.

**Comment by atlmtw** [comment]
More importantly thank you for everything the Strapi team is doing. I've been with it since Alpha and it has grown so much. Keep up the good work everyone!!

**Comment by lauriejim** [comment]
Thank you for this message @atlmtw !
