### ISSUE TITLE
Custom mutation returns null

### ISSUE THREAD

**Issue by svenadlung** [strapi/strapi#4832]
Hi guys,

I am pretty new to Strapi so please forgive me if I am wrong with sth.

I tried to create some custom mutation, which seems to work but it is returning no values.

**Steps to reproduce the behavior**
1. Create content type `idea`
2. Within `idea/config` create `schema.graphql`
3. Write custom mutation (see snippets below)
4. Create custom resolver in `idea/controllers/idea.js`

**Expected behavior**
In my example instead of null `title` should show `Test`.

**Screenshots**
<img width="910" alt="Bildschirmfoto 2019-12-26 um 18 53 43" src="https://user-images.githubusercontent.com/11420688/71485391-1c258f00-2811-11ea-9348-3172e7662c7d.png">

**Code snippets**

Schema (`idea/config/schema.graphql`):
```
module.exports = {
    definition: `
        type IdeaPayload {
            title: String
        }
    `,
    mutation: `
        updateIdeaState(input: JSON): IdeaPayload
    `,
    resolver: {
        Mutation: {
            updateIdeaState: {
                resolver: 'Idea.updateIdeaState'
            },
        },
    },
};
``` 

Resolver function (`idea/controllers/idea.js`):
```
module.exports = {
  async updateIdeaState(ctx) {
    return { 
      title: 'Test'
    };
  }
};
```

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: SQLite
- Operating system: MacOS Catalina

**Comment by lauriejim** [comment]
Hello @svenadlung !
You are right, there is an issue here.
If you are not passing arg, it sent the data. And if you add some input args, it resolve null.

Thank you for reporting this issue.
Ping @alexandrebodin .

**Comment by ScottAgirs** [comment]
Same here happens for Queries
![image](https://user-images.githubusercontent.com/11737572/71794331-041eee00-300f-11ea-9832-fa4610bed13d.png)

Schema (*/config/schema.graphql):
```javascript
module.exports = {
  definition: `
    type CurrentUser {
        id: Int
        firstName: String
        lastName: String
        email: String
        username: String
    }
  `,
  query: `
    currentUser: CurrentUser
  `,
  resolver: {
    Query: {
      currentUser: {
        description: 'Return the currentUser userProfile',
        resolver: 'UserProfile.currentUser',
      },
    },
  }
};
```

**Resolver function** (*/controllers/user-profile.js):
```javascript
module.exports = {
    currentUser: async ctx => {
        console.log("GOT IN? y/N")
    },
};
```

For **GOT IN?** answer would be No : )
It doesn't even hit controller.

**Comment by alexandrebodin** [comment]
Hi @svenadlung,

What you can simply do is rename your input to another name:

```js
module.exports = {
    definition: `
        type IdeaPayload {
            title: String
        }
    `,
    mutation: `
        updateIdeaState(ideaInput: JSON): IdeaPayload
    `,
    resolver: {
        Mutation: {
            updateIdeaState: {
                resolver: 'Idea.updateIdeaState'
            },
        },
    },
};
```

This will work because the input name is used internally by the plugin to know if the mutation is a generated one or not. If you really want to use options.input there are other ways to get around it but it is more complex :)

**Comment by svenadlung** [comment]
@alexandrebodin Thank you so much. No worries, that's no problem at all. 

The only thing that needs to be changed is everything that is related to the default params like `where` -> from `ctx.params.where` to `ctx.request.body.ideaInput.where`.

I'll close this issue. It would be great to have some more descriptions for custom mutations in the docs for better understanding.
