### ISSUE TITLE
Creating Strapi unique slug 

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#4833]
Hello folks, any native/recommended way of ensuring uniqueness on the `slug` field? Checking the unique field when creating a Content Type doesn`t seem to do the trick - also (feature request?) perhaps this could be handled internally - if a slug already exists and the unique field is checked, it could append "an incremental number or something of the sorts at the end of the string (?)

https://github.com/strapi/strapi/blob/master/docs/3.0.0-beta.x/guides/slug.md#auto-createupdate-the-slug-attribute

**Comment by derrickmehaffy** [comment]
https://portal.productboard.com/strapi/1-public-roadmap/c/29-uid-type-seo-friendly-url


Already planned and being worked on, marking as closed
