### ISSUE TITLE
Allow extensions of the strapi-admin package for backend changes

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#4838]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Allowing for backend modifications of the [strapi-admin](https://github.com/strapi/strapi/tree/master/packages/strapi-admin) Should be something to consider specifically related to the adminUI administrators model to customize it. This is a similar concept to the users-permissions extensions for the users model.

Previously I was using a hook to make these changes: https://github.com/canonn-science/CAPIv2-Strapi/blob/production/hooks/admin-model/index.js

```javascript
const _ = require('lodash');

module.exports = () => {
  return {
    async initialize() {
      await _.merge(strapi.admin.models.administrator, {
        connection: 'users'
      });
    },
  };
};
```

I did this as a "hacky" solution to to change the database connection used for this model, but as of beta.18 this method appears to be broken. I have also attempted to set this via the bootstrap file but my guess is this happens on initial bootup of Strapi so any changes after wouldn't really matter.

The admin itself in my opinion should be considered a "plugin" in itself as in theory you could run Strapi without the admin at all.

I did not create a product board entry for this as it seems like such a small change I'm not sure if it is something that should be included on there.

**Comment by derrickmehaffy** [comment]
tagging @alexandrebodin and @Aurelsicoko for thoughts.

**Comment by soupette** [comment]
We are planning to make this package a plugin

**Comment by derrickmehaffy** [comment]
Thanks @soupette :)

**Comment by Chris533** [comment]
Nice! Watching

**Comment by soupette** [comment]
We will see with @alexandrebodin when we will make this package a plugin.

**Comment by nunsie** [comment]
any updates on this yet?

**Comment by ChenDogg** [comment]
Also hacking this one at present. This is a game changer... allows for use cases to expand by multiples

**Comment by gtamas** [comment]
Oh wow... I can't believe this. This issue was opened almost half a year ago and there is still no progress.

@soupette 
We are working on a project now which needs this change. What's the best workaround for this? Should I use custom webpack config?

**Comment by soupette** [comment]
@gtamas the best way would be to fork the strapi-admin package and install your fork instead of the default one.

**Comment by gtamas** [comment]
@soupette 
OK thx! Then we actually have to fork Strapi itself, since strapi-admin is now a part of that. The NPM links are broken, they point to a separate repo which doesn't seem to exist anymore.

**Comment by derrickmehaffy** [comment]
I'm locking this thread for now and can/will unlock once the Strapi team have more updates and need feedback before they work on this. There is no current ETA

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/customize-default-registration-admin-form/592/2

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/extend-user-admin-model/713/12

**Comment by derrickmehaffy** [comment]
Closing this as the package is now core, best to use patch-package to make these modifications.
