### ISSUE TITLE
Scheduled publish article

### ISSUE THREAD

**Issue by ejuo** [strapi/strapi#4840]
Hello. I could not find the appropriate discussion.
Is it possible to implement the scheduled publish article? Automatically publish the article at a given time in the future.

**Comment by lauriejim** [comment]
Hello! This feature doesn't exist by default.
But you can use the [CRON tasks](https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#cron-tasks) and in your content type, you add a **Date** field.
Then in your CRON task you will have to fetch every minute (for example) article that match the current date and the **Date** field value you created in your content type.
You can use the [Queries](https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html#api-reference) to fetch and update your data.
