### ISSUE TITLE
Query dynamic zone with graphql does not return component content

### ISSUE THREAD

**Issue by tomolenet** [strapi/strapi#4849]
**Describe the bug**
If you query a content type with a dynamic zone by graphql you are not able to receive the content of the components.

**Steps to reproduce the behavior**
1. Create a content type
2. Add a dynamic zone with minimum two components inside
3. Query the content type by graphql

**Expected behavior**
Receive the components content.

**Screenshots**
![image](https://user-images.githubusercontent.com/38924650/71546235-31c3c180-2995-11ea-9e07-75d109ac0c2d.png)

**Code snippets**
If you query the content type by REST the component content is accessible:

```
[
  {
    "id":1,
    "title":"Hello World",
    "created_at":"2019-12-28T16:05:25.987Z",
    "updated_at":"2019-12-28T16:05:25.987Z",
    "content":[
      {
        "__component":"content.text",
        "id":1,
        "content":"This is an example content entry. Its the first entry."
      },
      {
        "__component":"content.image",
        "id":1,
        "caption":"A simple caption.",
        "image":{
          "id":1,
          "name":"c4935c879aef4c788fc744c5f05065b0.jpg",
          "hash":"51e30fe22a42401c96c16a8de56379e5",
          "sha256":"5zb6O1wyGreFnqW8KaV1bBuzOBO33aJfPKRbwtCGOc8",
          "ext":".jpg",
          "mime":"image/jpeg",
          "size":14573.84,
          "url":"/uploads/51e30fe22a42401c96c16a8de56379e5.jpg",
          "provider":"local",
          "provider_metadata":null,
          "created_at":"2019-12-28T16:05:26.133Z",
          "updated_at":"2019-12-28T16:05:26.133Z"
        }
      },
      {
        "__component":"content.text",
        "id":2,
        "content":"This is an example content entry. Its the second entry."
      }
    ]
  }
]
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDb
- Operating system: Linux

**Comment by sprashivaesh** [comment]
same problem on postgres

**Comment by tomolenet** [comment]
And even worse in `gatsby-source-strapi` you can not distinguish between components. https://github.com/strapi/gatsby-source-strapi/issues/93

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
I ping @alexandrebodin about that.

**Comment by alexandrebodin** [comment]
Hi, 

Dynamic zones are union types in graphql so you need to use fragments to query the fields:

```graphql
{
  restaurants {
    dz {
      __typename
      ... on ComponentDefaultClosingperiod {
        label
      }
    }
  }
}
```

We should add some examples in the docs @lauriejim 

Closing the issue.
