### ISSUE TITLE
Failed to create new app with Sqlite3 database

### ISSUE THREAD

**Issue by radmen** [strapi/strapi#485]
**Node.js version**:
9.3.0

**npm version**:
5.5.1

**Strapi version**:
3.0.0-alpha.8.2

**nvm version**:
0.33.6

**Operating system**:
macOS High Sierra (10.13.2)

I tried to create new Strapi app with sqlite3 database. Configuration wizard asks me for details of database connection (!) and then fails after providing default values.

Below, I'm pasting an excerpt from the console.

```
$ strapi new strapi-sqlite
INFO (99212 on amon-ereb.local): Creating your application... It might take a few seconds.
INFO (99212 on amon-ereb.local): Lets configurate the connection to your database:
 Choose your main database: Sqlite3
 Database name: strapi
 Host: localhost
 Port: 1433
 Username:
 Password:
INFO (99212 on amon-ereb.local): Testing database connection...
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
WARN (99212 on amon-ereb.local): Database connection has failed! Make sure your database is running.
 Choose your main database: (Use arrow keys)
  MongoDB (highly recommended)
  Postgres
  MySQL
❯ Sqlite3
  Redis
```

**Comment by ArkhipovK** [comment]
The same problem with postgres and mysql.

**Comment by lauriejim** [comment]
Hi @radmen can you update then version of  Strapi to `alpha.10.x` and tell me if you still have your issue please.

**Comment by brunovandamme** [comment]
I still get the same error on `alpha.10.1` when choosing sqlite3

**Comment by ArkhipovK** [comment]
@brunovandamme what about other dbs like mysql or postgres?

**Comment by brunovandamme** [comment]
Just wanted a quick view what strapi was all about, so i choose the db with the least amount of setup being sqlite. But it resulted in the error described. Have no installations of mysql/postgres, so can't comment on it.

I also found it strange that it asked a host and port when selecting sqlite3.

**Comment by ArkhipovK** [comment]
What is your os then?

**Comment by brunovandamme** [comment]
Running MacOS 10.13 High Sierra

**Comment by radmen** [comment]
@lauriejim @ArkhipovK I've tested `alpha.10.1`

Here are some results:

* `mysql` database: strapi creates new app, no error, also no tables (it doesn't create anything). `strapi start` failes with something like this:

```
$ strapi start

⚠️  TABLE `core_store` DOESN'T EXIST

CREATE TABLE `core_store` (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  key text,
  value text,
  environment text,
  type text,
  tag text
);

ALTER TABLE `core_store` ADD COLUMN `parent` integer, ADD FOREIGN KEY (`parent`) REFERENCES `core_store`(`id`);
```

* `postgres` failed on `strapi new` (though it's a totally different issue):

```
INFO (27390 on amon-ereb.local): Creating your application... It might take a few seconds.
INFO (27390 on amon-ereb.local): Lets configurate the connection to your database:
 Choose your main database: Postgres
 Database name: (strapi) post
module.js:544
    throw err;
    ^

Error: Cannot find module '/Users/radmen/tmp/tmp/node_modules/pg/package.json'
```

* `sqlite3` strapi keeps asking me about... connection details

```$ strapi new strapi-sqlite3
INFO (27451 on amon-ereb.local): Creating your application... It might take a few seconds.
INFO (27451 on amon-ereb.local): Lets configurate the connection to your database:
 Choose your main database: Sqlite3
 Database name: strapi
 Host: 127.0.0.1
 Port: 1433
 Username:
 Password:
INFO (27451 on amon-ereb.local): Testing database connection...
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
WARN (27451 on amon-ereb.local): Database connection has failed! Make sure your database is running.
 Choose your main database: Sqlite3
 Database name: ./test.sqlite
 Host: 127.0.0.1
 Port: 1433
 Username:
 Password:
INFO (27451 on amon-ereb.local): Testing database connection...
Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
WARN (27451 on amon-ereb.local): Database connection has failed! Make sure your database is running.
 Choose your main database: (Use arrow keys)
  MongoDB (highly recommended)
  Postgres
  MySQL
❯ Sqlite3
  Redis
```

**Comment by ibc** [comment]
Same here.

* Mac OS High Sierra 10.13.3
* strapi: 3.0.0-alpha.10.2

**Comment by micahscopes** [comment]
I'm also having this issue on Linux with Strapi 3.0.0-alpha.10.2

**Comment by radmen** [comment]
@derrickmehaffy I'm not sure if this is MacOS related. I've tried to run cli tool on Docker's node env (node:9.2-alpine) and it still keeps asking me for sqlite connection details :)

**Comment by derrickmehaffy** [comment]
@radmen the sqlite3 issue is likely related to Knex.js based on its response about `useNullAsDefault`

**Comment by derrickmehaffy** [comment]
I was looking through the documentation thats listed in that error and it seem the option `useNullAsDefault: true` needs to be passed along to knex. See there example:

```
var knex = require('knex')({
  client: 'mysql',
  connection: {
    host : '127.0.0.1',
    user : 'your_database_user',
    password : 'your_database_password',
    database : 'myapp_test'
  },
  useNullAsDefault: true
});

knex('coords').insert([{x: 20}, {y: 30}, {x: 10, y: 20}])
// insert into `coords` (`x`, `y`) values (20, NULL), (NULL, 30), (10, 20)"
```

Not sure where strapi defines knex connection variables.

**Comment by radmen** [comment]
@derrickmehaffy I'm talking here about SQLite. There should be a different "connection settings" prop.

In knex this config looks more like this:

```
var knex = require('knex')({
  client: 'sqlite3',
  connection: {
    filename: "./mydb.sqlite"
  }
});
```

My issue was originally intended to show only this problem (lack of different project setup for SQLite). Later it turned out that there're problems with MySQL/PSQL dbs.

**Comment by derrickmehaffy** [comment]
Aye yeah the useNullAsDefault isn't just limited to MySQL I believe it also affects SQLite as well. (Just in that example from Knex documentation they used MySQL)

**Comment by crazyx13th** [comment]
Same here. 
Win 10 
node: 9.5.0 + npm 5.6.0
strapi: 3.0.0-alpha.10.3

thx! (why issue is closed?)

![grafik](https://user-images.githubusercontent.com/8912561/36737450-5b23d5a2-1bdb-11e8-81a1-bceefa87e85b.png)

**Comment by lauriejim** [comment]
Good catch, miss to re-open it

**Comment by adamflater** [comment]
Just noticed the if the table owner in postgres is not the same as the connected knex/strapi db user, `hasTable` will return false. If you're using the postgres cli you can do this before running the recommended create table scripts: 

```
postgres=# \c my-strapi-db my-strapi-db-user
You are now connected to database "my-strapi-db" as user "my-strapi-db-user".
postgres=# # run create table scripts now
```

**Comment by lauriejim** [comment]
We are stoping sqlite support.

**Comment by yashha** [comment]
Thats sad, it is a good way to quickstart.
I liked that about django. you start it, it runs and eventually you switch to mysql.

**Comment by lauriejim** [comment]
Yes you are right ! But actually the experience si not good with sqlite and it's not our priority to fix this connector.
We will work on a great experience with MySQL and Postgres and don't focus on sqlite.
Remove it is the best way to omit bugs on this part.

**Comment by GerhardMes** [comment]
sad to hear that.

**Comment by gnpretorius** [comment]
@lauriejim 

I think this is a mistake. MySQL, Postgre & MongoDB are complete overkill for 90% of use cases out there. Also, having a development version which is completely isolated and self contained goes a long way in help evaluating the framework as well as spiking out new work. 

For the additional 5% effort needed to support Sqllite (I'm assuming most of the data access is abstracted through a common library) you would open it up to 50% more use cases. 

You should reconsider this. I know this decision has deterred me from trying out strapi so I would imagine outer people feel similarly. It does look awesome though :)

**Comment by subhero24** [comment]
I feel the same way. Not supporting SQLite has also stopped me from trying out strapi. SQLite lowers the barrier for entry significantly, and is even enough for most use cases beyond tryout.

**Comment by micahscopes** [comment]
I just wanted to chime in and say "sad!"  I hope some day there's room for sqlite or something like it!
