### ISSUE TITLE
Uploads should have the same permission control as content types

### ISSUE THREAD

**Issue by aahung** [strapi/strapi#4853]
**Describe the bug**
I noticed when I create a content type that public users cannot access, the files associated to it can still be downloaded. 

**Steps to reproduce the behavior**
1. Have a content type that is not publicly accessible and has a media field
2. Create one
3. Acquire the URL of the file
4. Open the URL without authentication, I can still open it

**Expected behavior**
404

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: v3.0.0-beta.18.3
- Database: Mysql
- Operating system: Ubuntu 18

**Additional context**

**Comment by derrickmehaffy** [comment]
I agree with the permissions, I disagree about the error, should be 403 or 401

**Comment by lauriejim** [comment]
Thank you for this feedback. 
I ping @Aurelsicoko about that to have his insight about this topic.

**Comment by kaufmann42** [comment]
Any updates on this front? Would be nice to be able to secure certain uploaded files.

**Comment by derrickmehaffy** [comment]
I'd say currently this is a feature request, but no updates about it

**Comment by kaufmann42** [comment]
That's disappointing :( For anyone looking for workarounds, it may be possible for you to store your file in base64 encoding as a resource. Definitely not preferable and not sure how this would impact performance.

**Comment by lauriejim** [comment]
I let this status until the @Aurelsicoko feedback about that.
But I completely understand the need, and I agree.
