### ISSUE TITLE
Can't created a new project... the Installation of dependencies are deprecated and corrupt

### ISSUE THREAD

**Issue by Tech-K** [strapi/strapi#4858]
**Describe the bug**
When trying to create a new project with strapi, the installation of the dependencies is deprecated and some are corrupt.

**Steps to reproduce the behavior**
1. Already installed strapi with 
`npm i strapi`

2. I follow the documentation to start a new project with strapi, running the command 
`npx create-strapi-app my-project --quickstart`

3. Try to perform this installation without success
![image](https://user-images.githubusercontent.com/55622278/71607168-71cda480-2b4d-11ea-80ab-7cb5c51d5999.png)

**Expected behavior**
I expected my first project to be created without errors, as in the documentation

**Screenshots**
![Installing Dependencies](https://user-images.githubusercontent.com/55622278/71607153-5a8eb700-2b4d-11ea-89b5-3f95e10498df.png)

**Code snippets**
- `npm install strapi`
- `npx create-strapi-app my-project --quickstart` 

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB
- Operating system: Windows 10 - 64bits

**Additional context**
I want to create my first project with strapi :(

**Comment by derrickmehaffy** [comment]
`npm i strapi@beta` which you shouldn't need this for npx installs.

I wasn't able to reproduce but you should clear your cache and try again (or try using yarn instead of npx)
