### ISSUE TITLE
i18n implementation

### ISSUE THREAD

**Issue by dsfrederic** [strapi/strapi#4863]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [X] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
I can't seem to find documentation about i18n for gatsby. There was an article for a previous version of strapi. What changed? Why is it deleted?

**Your suggestions for this topic**
Add documentation + examples for i18n.

**Comment by lauriejim** [comment]
Hello! 
This [**feature**](https://portal.productboard.com/strapi/1-public-roadmap/c/19-content-internationalization) is our [**Public Roadmap**](https://portal.productboard.com/strapi/1-public-roadmap/c/19-content-internationalization)
For now, there is a [short article](https://medium.com/strapi/content-internationalization-with-strapi-507ef5869c15) to deal with a custom i18n management, but it's just an workaround.
