### ISSUE TITLE
migration guide incorrect path example?

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#4866]
Hello,

I'm using https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html

and in 
2. Change the collectionName of the component
and also in
3. Change the collectionName of the component

The path in the guide is: `./api/components/category/component.json`

However, there is no instruction to move 'components' into ./api, so either a step is missing, or the correct path should read: `./components/category/component.json`

Please advise.

Thank you.

**Comment by hkovacs** [comment]
thank you. seeing that this was just a typo. i would have loved to contribute that directly. i guess next time i will just make the changes and provide pr.

**Comment by lauriejim** [comment]
Haha yes, quick and easy fix.
