### ISSUE TITLE
Forgot password form - Objects are not valid as a React child (found: object with keys {id}).

### ISSUE THREAD

**Issue by mdilshan** [strapi/strapi#4868]
**Describe the bug**
When I try to submit forgot password form I received 400 bad request error with following response.
`{
"statusCode":400,
"error":"Bad Request",
"message":[{"messages":[{"id":"Auth.form.error.email.invalid"}] }]
}`
After that I got React minified error.  I opened it with react error decoder and here's what I got `Objects are not valid as a React child (found: object with keys {id}).`

**Expected behavior**
Send the email and display success or error message

**Screenshots**
![Screenshot (83)](https://user-images.githubusercontent.com/47513639/71639062-6a191780-2c95-11ea-85ef-715895bdbb47.png)

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB
- Operating system: Windows 10

**Additional context**
In response, it says entered email is not valid but it is the correct email. When I try to submit the form with correct email it takes 1-2 seconds to print errors in console but if I try to submit the form with wrong email it immediately print the same error message in the console

**Comment by lauriejim** [comment]
Hello @mdilshan for reporting this issue.
Here is a frontend issue for @soupette .

Abou the email issue - please check this trouble shooting page - https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#trouble-shooting
