### ISSUE TITLE
content type won't save

### ISSUE THREAD

**Issue by moeinrahimi** [strapi/strapi#487]
**Node.js version**: v8.5.0
**npm version**: 5.3.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: windows 10 64bit
basically content type is not working at all, I create a content type and fields for it then hit save and pop says it created ok, but when i click the new contnet type just created on the sidebar it failes, looks like it doesn't save to database 
error message in console 
```
ERROR (9784 on tht): The model aaaaaaa can't be found.
ERROR (9784 on tht): Cannot read property 'count' of undefined
    TypeError: Cannot read property 'count' of undefined
        at Object.count (C:\Users\moein\prj\plugins\content-manager\services\ContentManager.js:24:52)
        at count (C:\Users\moein\prj\plugins\content-manager\controllers\ContentManager.js:45:86)
        at dispatch (C:\Users\moein\prj\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
        at next (C:\Users\moein\prj\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
        at dispatch (C:\Users\moein\prj\node_modules\koa-compose\index.js:42:32)
        at next (C:\Users\moein\prj\node_modules\koa-compose\index.js:43:18)
        at module.exports (C:\Users\moein\prj\plugins\content-manager\config\policies\routing.js:15:9)
        at dispatch (C:\Users\moein\prj\node_modules\koa-compose\index.js:42:32)
        at next (C:\Users\moein\prj\node_modules\koa-compose\index.js:43:18)
        at module.exports (C:\Users\moein\prj\plugins\users-permissions\config\policies\permissions.js:24:20)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by lauriejim** [comment]
Hello @moeinrahimi , can you try again. But wait the server restart (2 times) before going on the content type page.

**Comment by moeinrahimi** [comment]
@lauriejim 
actually content type gets save, but you need to restart the server so it works properly .

**Comment by storm1er** [comment]
Here's my content type "account" : 
```json
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "account",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "startamount": {
      "type": "decimal",
      "required": true
    },
    "startdate": {
      "type": "date",
      "required": true
    },
    "owner": {
      "model": "user",
      "via": "accounts",
      "plugin": "users-permissions"
    },
    "lines": {
      "collection": "line",
      "via": "account"
    }
  }
}
```

Even after a restart, I can't save anything. 

But if a create a lambda content type without  any relation, it works... any idea ?

**Comment by lauriejim** [comment]
@storm1er Can you open an other issue for your case please.

**Comment by pkail** [comment]
Does anything work in Strapi?  The install f**ks up, the very first example in the documentation f**ks up.  It doesn't work with Node 10, it doesn't work with Node <10.

**Comment by derrickmehaffy** [comment]
@pkail .... Strapi is alpha and changes rapidly right now. There is a lot of core stuff being reworked.

This issue your talking about seems to be related to windows, which has been documented to have issues. Please use WSL or a Linux VM.

**Comment by pkail** [comment]
If it doesn't work on Windows why doesn't it say so on the GitHub page, to stop people wasting hours of their time?  Why doesn't it say that it doesn't install with Yarn?  It also has a large list of unsupported dependencies, even when it does install.

The database setup wouldn't work unless I downgraded my Node version to 8.  Then the document type wouldn't save unless I upgraded my Node version to 10 or reinstalled my entire operating system.  And when the document type failed to save the error was less than helpful. 

If there's one version of the stack which actually does work I would be more than happy to give it another go.  I would love it to work: I've been searching for days for something like this.  It looks much more elegant than Ghost, and it would be great to have something running on Postgres.  But it's hard to have any confidence in it.  There are no demos, no usable tutorials and breaking errors which are almost a year old.

**Comment by derrickmehaffy** [comment]
@pkail Hence the term "Alpha" there is no mention of windows and yarn because they worked in the past and will be eventually supported in the future. A quick glance through open and closed issues and you will realize that support for windows is minimal and that is being worked on.

Unless someone is working on better windows support, all issues related to building projects on windows are closed and suggested to use WSL or a linux VM.

I'm sorry you having problems and seem to be frustrated, however with any alpha project you should expect problems. And since this is an open source project anyone can come and help to work on these problems. If you want to see better support, than please do look through the source code and submit Pull Requests with fixes. :smile:

**Comment by pkail** [comment]
Node projects normally work equally well on any platform, so that's what people expect. If it doesn't work using Windows or Yarn that's fine: it would just be helpful if it said this.

**Comment by derrickmehaffy** [comment]
@pkail If you want the most up to date information, I recommend you join the slack as bugs are typically discussed more so there.
