### ISSUE TITLE
Relation error

### ISSUE THREAD

**Issue by DrChills** [strapi/strapi#488]
**Node.js version**: v8.9.4
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Win 10

I've created a relation between 'posts' and 'postCategories'. I've created this in 'posts' content type builder as 'Post Categories has many posts'. This saves as

post.settings.json:
`"postCategories": {
      "model": "postCategories",
      "via": "posts",
      "plugin": ""
    }`

However the strapi instance has a fatal error with:

>  Something went wrong in the model `Post` with the attribute `postCategories`

Seem's to be a bug, as this is a fresh install. I only have two content types, both of which only have 1 entry with a single string field! PostCategories.settings.json didn't change after adding the relation

**Comment by DrChills** [comment]
Update, 

> Post Categories has and belongs to many Posts 

seems to work fine! however, it gives me the id of each entry, which isn't ideal from a users point of view!

**Comment by lauriejim** [comment]
Hello @DrChills, can you try to create `postcategories` content type instead of `postCategories`.

**Comment by borg** [comment]
Came across this issue when creating relationship when not both Content Types were yet saved (although still available in frontend). Deleting attribute flag in xxx.settings.json, restarting, saving both Content Types, then creating relationships worked.

**Comment by Globerada** [comment]
Hi.
I am experiencing the same error.

```
error Something went wrong in the model `Category` with the attribute `website`
error Cannot read property 'hasOwnProperty' of undefined
```

I have a model Website which should have several categories:

![error](https://i.imgur.com/Bw70B7R.png)


**website.settings.json:**

```{
  "connection": "default",
  "collectionName": "website",
  "info": {
    "name": "website",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string",
      "required": true
    },
    "description": {
      "default": "",
      "type": "text"
    }
  }
}
```

**Category.settings.json**
```
{
  "connection": "default",
  "collectionName": "category",
  "info": {
    "name": "category",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "default": "",
      "type": "string"
    },
    "slug": {
      "default": "",
      "type": "string"
    },
    "description": {
      "default": "",
      "type": "text"
    },
    "website": {
      "model": "website",
      "via": "categories"
    }
  }
}
```
Any ideas?

**Comment by lauriejim** [comment]
@Globerada what is the Strapi version you use please

**Comment by Globerada** [comment]
14.4.0 alpha.
For this I just followed your tutorial on the relation for restaurant - dishes.
But now, I can't edit or add new models because off the bug of the blank screen in "/#create::contentType::baseSettings". So I am waiting

**Comment by tfasolino** [comment]
Same problem with the 25.2 here. Just after creation of a new table with a single relation with user

error Something went wrong in the model `Contact` with the attribute `user`
error Cannot read property 'hasOwnProperty' of undefined

**Comment by lauriejim** [comment]
Can you give us exact steps to reproduce your issue please.

**Comment by newcode365** [comment]
Same problem happened 
when change property '1 to many' -> 'many to 1'
then server refresh failed
