### ISSUE TITLE
Service interruption after new content type creation

### ISSUE THREAD

**Issue by turanahmet** [strapi/strapi#4880]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [X] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Service interruption after new content type created

**Your suggestions for this topic**
When a user create a content type, api can not respond for a while. I think service restarts during this operation. This can cause service down time at production environment.

**Comment by derrickmehaffy** [comment]
This is intended, you should be building models locally (or in some kind of development environment) Pushing those changes into some kind of source control, testing them in staging, and planning and/or scheduling shorter downtime to roll those changes into production (after properly testing them)

There is no plans to allow for Content-Type builder access while in production/staging environments, this is to enforce proper development workflow between different environments.

Strapi is no and has no plans to be a sole database focused CMS, while it is built for ease of use it also focuses on the larger picture where code source control is important. Moving model settings into the database negates this as there is no real proper way to control the changes.

Marking as closed but do feel free to continue the discussion.
