### ISSUE TITLE
Can't disable or override `/` page

### ISSUE THREAD

**Issue by azerothl** [strapi/strapi#4881]
**Describe the bug**
The public middleware can't be disabled.

**Steps to reproduce the behavior**
1. Rename the `public/index.html` to whatever you want.
2. Set the `config/environments/**/middleware.json` with
```javascript
{
  "public": {
    "enabled": false
  }
}
```
3. Start Strapi `yarn develop`
4. Strapi return an error 
```shell
error Error: ENOENT: no such file or directory, open 'D:\www\miaCode-dev\public\index.html'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.initialize (D:\www\miaCode-dev\node_modules\strapi\lib\middlewares\public\index.js:39:24)
    at Promise.resolve.then (D:\www\miaCode-dev\node_modules\strapi\lib\middlewares\index.js:45:28)
error Command failed with exit code 1.
```

**Expected behavior**
Strapi shouldn't throw an error if the public middleware is disabled and there is no `public/index.html` file.

**System**
- Node.js version: 10.13
- NPM version: 6.4.1
- Strapi version: Beta 18.3
- Database: PostgreSQL
- Operating system: Windows 10

**Additional context**
After checking the states of middlewares in `strapi/lib/middlewares/index.js`, the list of enabled middleware return 
```
[ 'boom',
  'cors',
  'favicon',
  'language',
  'logger',
  'parser',
  'public', <== shouldn't be there!
  'responses',
  'router',
  'session',
  'xframe',
  'xss',
  'users-permissions',
  'active' ]
```
The public middleware is still enabled, looks like it doesn't take the modification in `config/environments/**/middleware.json`

**Comment by lauriejim** [comment]
Hello @azerothl !
Can you tell me what you want do exactly?
Because the Admin Panel is served with the `public` middleware.
I suppose you want to override the `/` route?

**Comment by derrickmehaffy** [comment]
@lauriejim he want's to disable serving those placeholder default pages in the public folder.

**Comment by wemod123** [comment]
seems in the latest version (18+), can not overwrite the path '/' by just put it in a api route.

**Comment by wemod123** [comment]
I check some possible solutions, since I also want to overwrite the '/'.
there could be different solutions, but the key is put you logic before `public` middleware, you could customize another middleware, and put it before `public`, or simply control the `public` resources via api, below is a rough example to control all resources, including public resources:

1. modify `/config/middleware.json`, put the "public" middleware after "router"
```
...
"after": [
      "parser",
      "router",
      "public"
    ]
...
```

2. add a route under your api, `/api/**/config/router.json`
```
...
{
      "method": "GET",
      "path": "/*",
      "handler": " ***.preCheck",
      "config": {
        "policies": []
      }
 }
...
```

3. In corresponding controllers file, add a method of `preCheck`, for example:
```
preCheck: async (ctx, next) => {
    console.log('pre-check', ctx.request.path) //  do what you want here, can control public files of course, since this controller will be accessed for every route
    await next();
},
```

4. of course you need to enable the controller `preCheck` for all roles.

**Comment by lauriejim** [comment]
Here are the topics
- Be able to disable the `/` route that renders `index.html` page.
- Be able to override the`/` route.

**Comment by derrickmehaffy** [comment]
@lauriejim may consider just a straight redirect from `/` to `/admin` or some other custom redirect URL?

**Comment by Gerald308** [comment]
Need someone to get son my wife’s phone because she cheating on me and I like to know more information on what’s going on if someone wants to help me

**Comment by lauriejim** [comment]
Considering that route `/` can send data, just a redirection option is not enough I think.

@Aurelsicoko we need your advice on this topic.

**Comment by alexandrebodin** [comment]
Hi, You can create a middleware to override it.

```js
module.exports = () => {
  return {
    initialize() {
      strapi.router.get('/', (ctx) => {
        ctx.send('Hello world')
      })
    },
  };
};
```

**Comment by and2** [comment]
Hey, I'm struggling with this as well. Tried the middleware approach, but still can't override the '/' route from the public middleware `strapi.router.get('/', serveIndexPage);`

**Comment by alexandrebodin** [comment]
@and2 where are you putting this code ?

**Comment by and2** [comment]
@alexandrebodin, thanks for getting back to me. have sorted it out by loading "public" middleware after "router"
