### ISSUE TITLE
"Invalid Date" for Time-Field

### ISSUE THREAD

**Issue by sebastian-ludwig** [strapi/strapi#4886]
**Describe the bug**
When I create a new ContentType-Entry with a given time, it shows "Invalid Date" in ContentType-Overview. It works correctly in  ContentType-Edit-View.

**Steps to reproduce the behavior**
1. Create ContentType "Test" with date (date-field), time (time-field), datetime (datetime-field)
2. Create ContentType-Entry with date/time/datetime for 1. January 2020 at 7 o´clock am (Germany --> UTC+1)
3. Display in "Test"-Overview: 5e0ed831880ea509c1090af0 (Id) | Wednesday, January 1st 2020 (Date) | Wednesday, January 1st 2020 (Datetime) | Invalid date (Time)

**Expected behavior**
- Should show correct Time
- Should also show Time information for Datetime.

**System**
- Node.js version: v13.1.0
- NPM version: 6.12.1
- Strapi version: v3.0.0-beta.18.3
- Database: Mongo
- Operating system: OSX

**Additional context**
I also do not understand why creating and updating date-fields have different request-parameters, is it on purpose?
- Creating with 1. January 2020 at 7 o´clock am:
`data: {"date":"2020-01-01T11:00:00.000Z","datetime":"2020-01-01T06:00:00.000Z","time":"07:00:00"}` (why 11:00:00.000Z?)
- Updating to 8 o´clock am:
`data: {"_id":"5e0ed831880ea509c1090af0","date":"2020-01-01","datetime":"2020-01-01T07:00:00.000Z","time":"08:00:00",...}`

**Comment by soupette** [comment]
@sebastian-ludwig this has been fixed in #4830
