### ISSUE TITLE
Run strapi in docker container

### ISSUE THREAD

**Issue by lucasdu4rte** [strapi/strapi#489]
Hello guys, I'm studying strapi use cases and as we are also studying docker. After many attempts at dockerfiles, and configuration file changes I decided to ask for help because my attempts were flawed.

**Comment by Aurelsicoko** [comment]
@lucasdu4rte It seems related to https://github.com/strapi/strapi/issues/510

**Comment by memolipd** [comment]
Yep we use docker alot here, but I'm also struggling to get strapi working in docker - which would be useful for dev/deploying.

here's my current docker-compose.yaml file:

`version: '2'
services:
  redirector-app:
    image: node:8-alpine
    env_file: .env
    volumes:
        - .:/var/app
    working_dir: /var/app
    command: node server.js
    ports:
        - 1337:1337
    links:
        - mongodb
    depends_on:
        - mongodb

  mongodb:
    image: mongo:latest
    env_file: .env
    volumes:
      - /data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

volumes:
  mongodb:
`

**Comment by memolipd** [comment]
Ahh I figured out the issue - it was pointing to localhost, not the mongodb image hostname of "mongodb"

I'll leave this up for anyone else wanting a working docker-compose file

**Comment by dj-hedgehog** [comment]
@memolipd 
You can't just execute Strapi inside a vanilla Node.js container. You need to create a Dockerfile for Strapi which installs it (as you would do on your own PC). I will take care of creating an official Dockerfile which can be built and published to Docker soon.

**Comment by memolipd** [comment]
@dj-hedgehog for dev, I pass in the current directory as a volume which has node_modules. I've had to amend the run command to make sure the plugins install, but is otherwise working:
```command: ash -c "node node_modules/strapi/lib/utils/post-install.js && node_modules/nodemon/bin/nodemon.js server.js"```

**Comment by Aurelsicoko** [comment]
@memolipd @dj-hedgehog There is also a member (@lucaperret) which is working on a similar issue. We discussed it and one of the solutions is to enhance the `strapi new` command line. The purpose is to be able to pass arguments like that `strapi new myApp --dbhost=locahost --dbport=1337 --dbusername=root --dbpassword=root` into the command line to avoid the interactive part of the CLI.

PS: It's not the same issue but I was thinking you might be interested in it and maybe share your thoughts about it.

**Comment by Aurelsicoko** [comment]
I think we can close this issue, feel free to continue the discussion though...
