### ISSUE TITLE
How to add a reusable middlware

### ISSUE THREAD

**Issue by aelamel** [strapi/strapi#4892]
Hello, community,

I would like to create a custom middleware and publish it to npm to be reusable.

I've looked into the strapi-middleware-views code and what've understood is that I have to create a separate project with some specific folder structure and configuration in the package.json file.

I've managed to do that, but I'm facing an issue when I'm trying to install my middleware in strapi (from the local path or even from the published version to npm)

the error that i get is :

`2020-01-03T16:58:55.183Z] error Error: Cannot find module 'strapi-middleware-recaptcha-v3'
cms_1         |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
cms_1         |     at Function.resolve (internal/modules/cjs/helpers.js:33:19)
cms_1         |     at Object.loadMiddlewareDependencies (/apps/cms/node_modules/strapi/lib/core/load-middlewares.js:91:17)
cms_1         |     at module.exports (/apps/cms/node_modules/strapi/lib/core/load-middlewares.js:22:13)
cms_1         |     at Strapi.load (/apps/cms/node_modules/strapi/lib/Strapi.js:341:7)
cms_1         |     at process._tickCallback (internal/process/next_tick.js:68:7)
cms_1         |     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
cms_1         |     at startup (internal/bootstrap/node.js:283:19)
cms_1         |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
cms_1         | npm ERR! code ELIFECYCLE
cms_1         | npm ERR! errno 1
cms_1         | npm ERR! website-cms@0.1.0 develop: `strapi develop`
cms_1         | npm ERR! Exit status 1
cms_1         | npm ERR! `

Here is the link for the draft code for my middleware, I don't know if I've made a mistake somewhere
https://www.npmjs.com/package/strapi-middleware-recaptcha-v3
Thanks in advance for your answers

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
