### ISSUE TITLE
Live demo at demo.strapi.io not working

### ISSUE THREAD

**Issue by MurzNN** [strapi/strapi#4893]
Demo host at https://demo.strapi.io/ not working, is it turned off or something broken?

**Comment by derrickmehaffy** [comment]
@lauriejim 

As this isn't a bug with Strapi itself I'm gonna mark this closed but I'll follow up with Jim to check on it.

**Comment by lauriejim** [comment]
Hello @MurzNN ! Where did you find this link?

**Comment by MurzNN** [comment]
In other issue via Google :) https://github.com/strapi/strapi/issues/3210

Also here https://strapi.io/demo is demo video, but live interactive demo will be much better! So will be very good to recover the live demo instance of Strapi.

**Comment by lauriejim** [comment]
Okay I see.
So the best experience of Strapi is when you are in `development` mode with the content manager, you can create your content type, etc... but you need to be in local.
Open these features in a public app is simply not possible.
That's the reason why we stopped it.
