### ISSUE TITLE
GraphQL query { me {} } 400 Bad request: No authorization header was found

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#4898]
Looking to query `me {}`with GraphQL, however, getting the `400 Bad Request  No authorization header was found ` error.

Other queries and mutations work fine, including login/logout. 
Hoping that I`m missing something and someone can tell me what 🙏 

**Screenshots**
![image](https://user-images.githubusercontent.com/11737572/71777408-70e1ac00-2f6d-11ea-9c75-aed9c78d50c4.png)

**Code snippets**
```javascript
const ME_QY = gql`
  query {
    me {
      username
      id
      email
    }
  }
`;
```

**System**
- "strapi": "3.0.0-beta.18",

**Comment by derrickmehaffy** [comment]
Are you passing the JWT in an authorization header?

**Comment by ScottAgirs** [comment]
@derrickmehaffy, not explicitly, I guess I was hoping that it`s somehow handled by Strapi by default 😄Especially since all the other queries/mutations worked

Any suggestions/tips for where and how to pass it properly?

**Comment by derrickmehaffy** [comment]
@ScottAgirs Strapi can't help with what you are sending on your client, it expects the bearer JWT in an authorization header which based on the error message being sent you aren't sending it.

**Comment by ScottAgirs** [comment]
Thanks @derrickmehaffy, after several frustrating hours, turns out what I initially did with `'apollo-link-context'`was right, but just wasn`t taking effect for some reason. Resolved, thanks again!
