### ISSUE TITLE
multifield search in where clause of graphql plugin

### ISSUE THREAD

**Issue by heavenkiller2018** [strapi/strapi#4899]
**Describe the bug**
there is a defect that multifield search is not supported in graphql plugin .

**for example:**
in mongodb shell:

`
db.stores.insert(
   [
     { _id: 1, name: "Java Hut", description: "Coffee and cakes" },
     { _id: 2, name: "Burger Buns", description: "Gourmet hamburgers" },
     { _id: 3, name: "Coffee Shop", description: "Just coffee" },
     { _id: 4, name: "Coffee Shop Clothes Clothes Clothes", description: "Discount clothing" },
     { _id: 5, name: "Java Shopping", description: "Indonesian goods" }
   ]
)
`
if i want to get data that contain 'coffee' in 'description' field, the script could be like this:
`
db.getCollection("stores").find( {
                "description" : {
                    "$regex" : 'coffee',
                    $options: 'i'
                }
            })
`
results:
`
{ 
    "_id" : 1.0, 
    "name" : "Java Hut", 
    "description" : "Coffee and cakes"
}
{ 
    "_id" : 3.0, 
    "name" : "Coffee Shop", 
    "description" : "Just coffee"
}
`

the correspondent where clause in graphql plugin of strapi is following:
where: {"description_contains":"coffee"}

but if i want to fetch data that contain 'coffee'  in  'description' or 'name'  field,  it could be realized in mongodb shell like this:
`
db.getCollection("stores").find(
    { 
        "$or" : [
            {
                "name" : {
                    "$regex" : 'coffee',
                    $options: 'i'
                }
            },
                        {
                "description" : {
                    "$regex" : 'coffee',
                    $options: 'i'
                }
            }
        ]
    }
);
`

results:
`
{ 
    "_id" : 1.0, 
    "name" : "Java Hut", 
    "description" : "Coffee and cakes"
}
{ 
    "_id" : 3.0, 
    "name" : "Coffee Shop", 
    "description" : "Just coffee"
}
{ 
    "_id" : 4.0, 
    "name" : "Coffee Shop Clothes Clothes Clothes", 
    "description" : "Discount clothing"
}

`

but i'm suprised it can't be realized in graphql plugin of strapi because there is no correspondent syntax. or you can give me some advise to get it?

multifield search is very useful and extensive in absence of text index search!
I strongly recommend to improve it!

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
