### ISSUE TITLE
FindOne can't have multiple parameters if it contains primary key with mongoose

### ISSUE THREAD

**Issue by lambertkevin** [strapi/strapi#4900]
**Describe the bug**
When using the strapi-hook-mongoose lib and trying to ```findOne``` on a model, if you're giving a primary key as one of the params, the rest is ignored. 

**Steps to reproduce the behavior**
1. Create a model with a boolean "private" for example
2. Create an entry with private at true
3. From its controller, create a findOne method that will findOne of your model with the ctx.params + ```private: false```
4. Allow this api route as public
5. You can retrieve your entry with the api despite it being a "private" entry

**Expected behavior**
You should be able to have multiple params to a findOne (it's not findById)

**Code snippets**
Source for the findOne in strapi-hook-mongoose:
```
  async function findOne(params, populate) {
    const primaryKey = getPK(params);

    if (primaryKey) {
      // Here params is redefined completely
      params = {
        [model.primaryKey]: primaryKey,
      };
    }

    const entry = await model
      .findOne(params)
      .populate(populate || defaultPopulate);

    return entry ? entry.toObject() : null;
  }
````

**Comment by derrickmehaffy** [comment]
Please be sure to include the versions, this is a requirement for the bug report template

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
