### ISSUE TITLE
FindOne can't have multiple parameters if it contains primary key with mongoose

### ISSUE THREAD

**Issue by lambertkevin** [strapi/strapi#4901]
**Describe the bug**
When using the strapi-hook-mongoose lib and trying to ```findOne``` on a model, if you're giving a primary key as one of the params, the rest is ignored. 

**Steps to reproduce the behavior**
1. Create a model with a boolean "private" for example
2. Create an entry with private at true
3. From its controller, create a findOne method that will findOne of your model with the ctx.params + ```private: false```
4. Allow this api route as public
5. You can retrieve your entry with the api despite it being a "private" entry

**Expected behavior**
You should be able to have multiple params to a findOne (it's not findById)

**Code snippets**
Source for the findOne in strapi-hook-mongoose:
```
  async function findOne(params, populate) {
    const primaryKey = getPK(params);

    if (primaryKey) {
      // Here params is redefined completely
      params = {
        [model.primaryKey]: primaryKey,
      };
    }

    const entry = await model
      .findOne(params)
      .populate(populate || defaultPopulate);

    return entry ? entry.toObject() : null;
  }
````

**System**

- Node.js version: v11.12.0

- NPM version: 6.7.0

- Strapi version: beta.17.8

- Database: Mongodb

**Comment by lauriejim** [comment]
Hello, can you check if the issue exists in the last version of Strapi? 
At least `beta.18.x`

**Comment by lambertkevin** [comment]
I checked the source for beta.18.3 and it's exactly the same, so yes it exists in the latest version.

**Comment by lauriejim** [comment]
I think there is a difference here between 2 types of requests.

**1.** Find one entry based on a unique field. So the request you will do have only one entry.
For example with ID. IDs are unique. So in this case here is the feature request - https://github.com/strapi/strapi/issues/4547

**2.** Find one entry based on non unique field. In this case you can use find function with a limit set to 1.
Because you will be able to add sort params, or other.

And I'm not sure for the case 2 we have to manage this via find one function.
Need @alexandrebodin point of view.

**Comment by alexandrebodin** [comment]
Hi @lambertkevin, 

I agree with you that the findOne should be able to handle your use case. Are you open to making a PR @lambertkevin ? This behaviour would need to also be implemented in the bookshelf side of things in the same way.

**Comment by lambertkevin** [comment]
@alexandrebodin Yes I can make a PR for this issue, but I want to make sure that we agree on what I'm going to do. The idea will be pretty simple since I'm just going to remove this part
```
    const primaryKey = getPK(params);

    if (primaryKey) {
      // Here params is redefined completely
      params = {
        [model.primaryKey]: primaryKey,
      };
    }
```

And leave params be whatever it was initially. Is it ok with you?

**Comment by alexandrebodin** [comment]
@lambertkevin If you do that this will break :)

the `getPK` func returns either `params[model.primaryKey] || params.id` for interop purposes. 

You will need to rename the property `id` to `model.primaryKey` if there is one instead of just leaving params.


```js
const primaryKey = getPK(params);

if (primaryKey) {

params = {
   ..._.omit(params, 'id'),
   [model.primaryKey]: primaryKey,
}
      

```
