### ISSUE TITLE
error MissingSchemaError: Schema hasn't been registered for model "GroupDocument".

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#4905]
i get this error when i visit url /admin/plugins/upload

`
error MissingSchemaError: Schema hasn't been registered for model "GroupDocument".
Use mongoose.model(name, schema)
at new MissingSchemaError (/path/to/strapi/node_modules/mongoose/lib/error/missingSchema.js:22:11)
`

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html

I followed the guide including running this command:
`
db.getCollection('association').update(
  { 'board_meeting_minutes.kind': 'GroupDocument' },
  { $set: { 'board_meeting_minutes.$.kind': 'ComponentDocumentDocument' } },
  { multi: true }
);`

I also manually checked the records to ensure the 'kind' is 'ComponentDocumentDocument'

I did a grep to see if 'GroupDocument' exists in any file in my strapi, but recursive search found 0 results.

i noticed in core_store that there is a record for 'plugin_content_manager_configuration_groups::document' with a value containing '"isGroup": true' yet i didnt see anything in the guide about changing records in core_store. are any changes supposed to be made? is the guide missing a step? did i miss a step?

my system:
mongo: v4.0.12
node: v10.16.3
npm: 6.9.0
strapi: v3.0.0-beta.18.3
ubuntu 18.04

thank you

**Comment by alexandrebodin** [comment]
Hi @hkovacs,

Did you check the upload_file collection ? You might have files pointing to that GroupDocument you will need to run a similar query if so ;).

Hope this helped!

**Comment by hkovacs** [comment]
@alexandrebodin very helpful. i found it in upload_file. do i change GroupDocument to ComponentDocument? or ComponentDocumentDocument? thank you

**Comment by alexandrebodin** [comment]
@hkovacs You will have to check the globalId with the method explained in the guide. 

If you used ComponentDocumentDocument in the first place you should use the same here too. (I guess your category is document too hence the double document)

**Comment by hkovacs** [comment]
@alexandrebodin yes i have been using ComponentDocumentDocument as my category is also document, but I have struggled with the guide, and things are not working perfectly yet, so my doubts keep me nervous.

thank you. I will close this tkt once the page stops throwing error.

**Comment by hkovacs** [comment]
files upload page is displaying correctly. thank you @alexandrebodin
