### ISSUE TITLE
Content manager plugin - Getting error when trying access to settings

### ISSUE THREAD

**Issue by gastonbesada** [strapi/strapi#4908]
**Describe the bug**
Getting "TypeError: Cannot convert undefined or null to object" when trying access to CM plugin settings.

**Steps to reproduce the behavior**
1. Go to "Marketplace"
2. Click on "Settings" on "Content Manager" card.
3. See error: Something went wrong.
Detalles: TypeError: Cannot convert undefined or null to object

**Screenshots**
![image](https://user-images.githubusercontent.com/884940/71823894-16347700-3077-11ea-92cf-1bf91b679967.png)
![por defecto 2020-01-06 a la(s) 11 24 40](https://user-images.githubusercontent.com/884940/71824040-601d5d00-3077-11ea-93c2-150567f330b2.jpg)

**System**
- Node.js version: 12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: sqlite
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
@soupette @virginieky

**Comment by jmchza** [comment]
hi @soupette 
I know this is a question on the subject but I am using the same version wuth mysql and the plugin Content Manager appears as installed but on my left side menu -> plugin list it isn't listed.
So the question is it possible that this plugin is not supported on Mysql? 

Thanks.

**Comment by nhatbao123** [comment]
I have already installed the content manager, so why hasn't it appeared on the plugins section please help me to resolve this issue
![ssss](https://user-images.githubusercontent.com/68341519/88777523-82acca00-d1b1-11ea-9974-c013b39d39e8.png)

**Comment by lauriejim** [comment]
Because the Content Manager doesn't display anything in the Plugin section in the left menu.
The plugin let you access your Collection and Single Types in the left menu.
