### ISSUE TITLE
Cannot add component item with graphql mutation

### ISSUE THREAD

**Issue by fouss** [strapi/strapi#4909]
**Describe the bug**
Hi, i got an issue with components and graphql since I upgraded to beta 18. I cannot add any component item with a graphql mutation of a parent object.

**Steps to reproduce the behavior**
1. Create a mutation to add an item in a collection (you can do it on the graphql playground) with a linked component (Itried with repeatable and single component)
2. Click on 'play'
3. Observe the result, there is no error but the array of component display list of "null" instead component data

**Expected behavior**
Create component item while create the parent item from graphql request.

**Code snippets**
```
mutation addProExample {
  createPro(
    input: {
      data: {
        name: "proTest"
        certif: [{ date: "2020-01-15T11:00:00.000Z" }]
      }
    }
  ) {
    pro {
      _id
      name
      certif {
        date
      }
    }
  }
}
```
=> response 
```
{
  "data": {
    "createPro": {
      "pro": {
        "_id": "5e1343e3ea6ae600dee0953a",
        "name": "proTest",
        "certif": [
          null
        ]
      }
    }
  }
}
```

**System**
- Strapi version: v3.0.0-beta.18.3
- Database: MongoDB
- Operating system: Docker (from strapi/base)

**Additional context**
Everything works fine by the Strapi UI, the graphql playground and logs don't show any error at all 

When the item is added by the UI, the object looks like :
```
certif
:
[
{
_id
:
5e13521dea6ae600dee0953e,
kind
:
"ComponentProCertif",
ref
:
5e13521dea6ae600dee0953d
}
]
`
and from the graphql mutation : 
`certif:
[{
_id
:
5e13525fea6ae600dee09540
}]
```

```
"dependencies": {
    "lodash": "^4.17.5",
    "strapi": "3.0.0-beta.18.3",
    "strapi-admin": "3.0.0-beta.18.3",
    "strapi-connector-mongoose": "3.0.0-beta.18.3",
    "strapi-plugin-content-manager": "3.0.0-beta.18.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.3",
    "strapi-plugin-email": "3.0.0-beta.18.3",
    "strapi-plugin-graphql": "3.0.0-beta.18.3",
    "strapi-plugin-upload": "3.0.0-beta.18.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.3",
    "strapi-utils": "3.0.0-beta.18.3"
  }
```

**Comment by lauriejim** [comment]
Hello @fouss !
I tried to create a repeatable compo with GraphQL and it works.
[📺 Here](https://www.loom.com/share/6074f31622d446dabc7e899e0b606a85) what I did.
Can you tell me if I'm missing something?

**Comment by fouss** [comment]
thx @lauriejim after your video i tried to add my component to a fresh new collection and that's work !! so i removed my "old" collection, and recreate the exact same (without the first letter in uppercase) and everything is fine now... So my problem didn't come from my component but from the collection. I'll dig a bit more to understand what append during the migration to beta 18

**Comment by fouss** [comment]
i reopen this issue beacause i got the same pb with all my "old collections" (from before beta 18), i cannot use graphql with any component linked to these collection. I can't erase my datas, I think I just missed something during the migration... If someone have an idea :)

**Comment by fouss** [comment]
I think the problem came from here in the migration guide 
db.getCollection('contentTypeCollection').update(
  { 'componentField.kind': 'GroupsMyGroup' },
  { $set: { 'componentField.$.kind': 'ComponentCategoryMyComponent' } },
  { multi: true }
);

I didn't do it because I don't understand how that's work but that's really seems to be the reason of my pb.

**Comment by lauriejim** [comment]
Hello!
This command is here to manage the rename of Group to Component.
Groups/Components are linked to a Content-Type like oneWay or manyWay.
So you have to update the `kind` attribute of the relation definition.
That is what this command does.
