### ISSUE TITLE
Can't seem to use id_in in where clause GraphQL / MongoDB

### ISSUE THREAD

**Issue by roelbeerens** [strapi/strapi#4912]
First of all, not sure if it's a duplicate of this one [https://github.com/strapi/strapi/issues/4569](https://github.com/strapi/strapi/issues/4569). It seems somehow related, but I'm not 100% sure.

**Describe the bug**
When using the GraphQL plugin in the latest version of Strapi (3.0.0-beta.18.3) in combination with MongoDB, it seems it not possible to use id_in in a where clause. A simple slug_in seems to be working properly.

**Steps to reproduce the behavior**
1. Setup a Strapi environment with MongoDB
2. Create a content type (like 'asset') 
3. Create a content type related to asset (like 'category') 
4. Create an entry in asset and category and link them together
4. Navigate to the graphql playground
5. Enter something like this:

`query {
  assets(where: {
    category: {
    	id_in: ["5e13628f63277f72332c8e0b"]
    }
  }) {
    id
  }
}`

6. Witness an empty result

**Expected behavior**
The filtered item with the ID should be visible in the result. For reference, try adding a 'slug' field to the 'category' content type. Filtering like this, works properly:

`query {
  assets(where: {
    category: {
    	slug_in: ["band"]
    }
  }) {
    id
  }
}`

**System**
- Node.js version: v10.17.0
- NPM version: 6.13.3
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB (latest docker image)
- Operating system: MacOS / MongoDB in docker

**Comment by alexandrebodin** [comment]
Hi @roelbeerens,

As a workaround you can do directly : `categories_in`. We will make a fix for your usecase though ;)

**Comment by roelbeerens** [comment]
Hi @alexandrebodin,

Thanks for your response! Thats seems to work, however when adding a second filter, like this:

`query {
  assets(where: {
    category: {
      parent: "5e13625563277f72332c8e0a"
    }
    category_in: ["5e13628f63277f72332c8e0b"]
  }) {
    id
  }
}`

The response is empty. If you've got a working example in regard to this situation, please let me know :)

**Comment by roelbeerens** [comment]
Hi @alexandrebodin,

Just tested the implementation with a many-to-many relation and got the following response when using deep filtering:

`{
  "errors": [
    {
      "message": "$in requires an array as a second argument, found: missing",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "assetsConnection",
        "values"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "ok": 0,
          "errmsg": "$in requires an array as a second argument, found: missing",
          "code": 40081,
          "codeName": "Location40081",
          "name": "MongoError",
          "stacktrace": [
            "MongoError: $in requires an array as a second argument, found: missing",
            "    at Connection.<anonymous> (/Users/Roel/Projects/bookthat-platform/services/app/node_modules/mongodb/lib/core/connection/pool.js:460:61)",
            "    at Connection.emit (events.js:198:13)",
            "    at processMessage (/Users/Roel/Projects/bookthat-platform/services/app/node_modules/mongodb/lib/core/connection/connection.js:368:10)",
            "    at Socket.<anonymous> (/Users/Roel/Projects/bookthat-platform/services/app/node_modules/mongodb/lib/core/connection/connection.js:537:15)",
            "    at Socket.emit (events.js:198:13)",
            "    at addChunk (_stream_readable.js:287:12)",
            "    at readableAddChunk (_stream_readable.js:268:11)",
            "    at Socket.Readable.push (_stream_readable.js:223:10)",
            "    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"
          ]
        }
      }
    }
  ],`

with the following query:

`query {
  assetsConnection(where: {
    tags: {
      slug_in: ["funk"]
    }
  }) {
    values {
      name
    }
  }
}`

**Comment by roelbeerens** [comment]
Nevermind, the documents where messed up which resulted in above result

**Comment by sebastianjung** [comment]
@roelbeerens 
Having the same problem with Error Message:

Error message:
`$in requires an array as a second argument, found: missing`

on
`"strapi": "3.1.4"`

Can you tell me how you have been able to fix this issue?


My Query:
```
query Moderator {
  users(where: { userRoles: { uid: "moderator" } }) {
      id
  }
}
```

My Relation:
![image](https://user-images.githubusercontent.com/17472892/91584761-6e482280-e953-11ea-92a0-6d6ca3492276.png)

Any help is very much appreciated!

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
