### ISSUE TITLE
Admin panel does not allow pagination navigation further than 4000 items

### ISSUE THREAD

**Issue by dmelniko** [strapi/strapi#4915]
**Describe the bug**
I've created 5000 articles of the same content type. The admin panel is unable to display any articles through pagination navigation past article 3999. The following error occurs if trying to access any page beyond that: "An error occurred during models config fetch". Articles are present and accessible if searched for.

**Steps to reproduce the behavior**
1. Generate >4000 articles of same content type
2. Click on that content type in admin panel and try to navigate to last page
3. See error  "An error occurred during models config fetch"

**Expected behavior**
Expect to be able to see articles on all pages

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
-Database: MongoDB
- Operating system: Ubuntu 18.04.3 LTS

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-beta.16.8` Please test with the latest version (beta.18.3)

![image](https://user-images.githubusercontent.com/8593673/71870265-8f14ec80-30d2-11ea-8623-52dabdc1cf52.png)

I was not able to reproduce this, for now I'll mark this as closed, if you still have the issue on the latest beta version reply back and we can reopen this. In the future all bug reports must be made on the current version. Thanks! :smiley:
