### ISSUE TITLE
Plugin list use local icons

### ISSUE THREAD

**Issue by ocyangel** [strapi/strapi#4917]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

THANKS FOR ALL GREAT JOB

However, I fond out that you use some icons which hosted in https://raw.githubusercontent.com.
eg. https://raw.githubusercontent.com/strapi/strapi/master/packages/strapi-plugin-content-manager/admin/src/assets/images/logo.svg?sanitize=true

And they can't show correctly sometimes as below
![image](https://user-images.githubusercontent.com/6308331/71865419-a1784000-313d-11ea-9569-1398a5df91fb.png)
![image](https://user-images.githubusercontent.com/6308331/71865461-c8367680-313d-11ea-99d3-c3f083d692b4.png)

Is that any possibility to change the URL to be a local directory or anyway else to make those icons show better

**Comment by derrickmehaffy** [comment]
@soupette I do agree we should avoid outside connections where possible and keep the static assets in the plugin itself. The marketplace is a bit different because in the future that would be loaded from a remote server (basically static for now)

**Comment by lauriejim** [comment]
Hello @ocyangel !
Can you please share the `network` browser request error you get, please.
Thank you.

**Comment by ocyangel** [comment]
@lauriejim It just happens sometimes. The error code is :net::ERR_CONNECTION_RESET
Icons can be showed after refreshing the page some times. It is not an error of strapi, but the network. when icons don't show, I can't visit https://raw.githubusercontent.com either. If those icons host in other servers or just use local files, the problem will be solved. Some advice: plugins installed 
should local files and the marketplace can host in your servers

**Comment by ocyangel** [comment]
It just happens sometimes. The error code is :net::ERR_CONNECTION_RESET
Icons can be showed after refreshing the page some times. It is not an error of strapi, but the network. when icons don't show, I can't visit https://raw.githubusercontent.com either. if icons host in other servers, this problem will be solved. Some advice: plugins installed should use local files while  marketplace host in your servers
