### ISSUE TITLE
Error on File list after deleting Content Type MongoDB

### ISSUE THREAD

**Issue by Adam-Asatryan** [strapi/strapi#4918]
**Describe the bug**
I have created content type which has media attachment. When I am deleting content type it does not delete attachment as well so when I am opening Files upload dashboard it throws an error as it tries to find a related model which is deleted

**Expected behavior**
Either it should delete related attachment or it will show correctly on the Files upload dashboard

**System**
- Node.js version: 12.6.0
- NPM version: yarn v1.17.3
- Strapi version: 3.0.0-beta.18.3
- Database: Mongoose
- Operating system: macOS Mojave

**Comment by hyperion0201** [comment]
i also faced this issue with both local provider and AWS S3 . Is there anyway to work-around it?

**Comment by loiclouvet** [comment]
Facing same issue too. 
### Workaround :
I modified `/node_modules/strapi-connector-mongoose/lib/mount-models.js`
Line 230 : ` const ref = obj.ref` =>  `const ref = obj.ref || {};`
With this workaround, files upload dashboard is working fine.

I also added a cron task to remove related attachment if related item does not exist anymore.
I don't have enough time to dig into this bug yet.
