### ISSUE TITLE
an error occurred notice when saving new field

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#4920]
**Describe the bug**

i got this error when i tried to save a simple text field or a number (integer) field:

`debug PUT /content-type-builder/content-types/application::association.association (43 ms) 400`

this happened while following the guide to update to 18.3 https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html

**Steps to reproduce the behavior**
1. update from 17.5 to 18.3
2. follow the guide
3. drink a beer :)
4. please see my json files below as there is nothing wrong with the normal steps for adding fields to a content type that doesnt have components.

the name of my content type is association (as in a company) and the name of my field both times was testfield. this content type is the only one with components. my other content types do not have components and allow me to save new fields without any problems.

**Code snippets**

my `./api/association/model/Association.settings.json` as follows:

```
{
  "connection": "default",
  "collectionName": "association",
  "info": {
    "name": "associations",
    "description": "all details pertinent to an association are stored here"
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "name": {
      "minLength": 6,
      "required": true,
      "type": "string"
    },
    "mysqlId": {
      "type": "integer",
      "default": "0"
    },
    "ein": {
      "type": "integer",
      "default": "0"
    },
    "token": {
      "minLength": 9,
      "required": true,
      "unique": true,
      "type": "string"
    },
    "county": {
      "type": "string"
    },
    "mailing_address": {
      "component": "address.address",
      "type": "component"
    },
    "physical_address": {
      "component": "address.address",
      "type": "component"
    },
    "est_address": {
      "component": "address.address",
      "type": "component"
    },
    "est_name": {
      "type": "string"
    },
    "est_email": {
      "type": "email"
    },
    "officePhone": {
      "type": "string"
    },
    "office_fax": {
      "type": "string"
    },
    "about": {
      "type": "richtext"
    },
    "hero_image": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    },
    "images": {
      "collection": "file",
      "via": "related",
      "plugin": "upload"
    },
    "intro_text": {
      "type": "string"
    },
    "board_meeting_minutes": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "membership_meeting_minutes": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "financial_statements": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "budgets": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "contractor_agreements": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "director_certifications": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "disclosures": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "declarations": {
      "component": "document.document",
      "type": "component",
      "repeatable": true
    },
    "amendments": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "by_laws": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "articles_of_incorporation": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "rules_and_regulations": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "forms": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    }
  }
}
```

my `./components/address/address.json` as follows:

```
{
  "info": {
    "name": "address",
    "description": "address block"
  },
  "connection": "default",
  "collectionName": "components_address_addresses",
  "attributes": {
    "address_line_1": {
      "type": "string"
    },
    "address_line_2": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "zipcode": {
      "type": "string"
    },
    "latitude": {
      "type": "float"
    },
    "longitude": {
      "type": "float"
    }
  }
}

```
and components_address_addresses is the collection name in mongo

my `./components/document/document.json` as follows:

```
{
  "info": {
    "name": "document",
    "description": ""
  },
  "connection": "default",
  "collectionName": "components_document_documents",
  "attributes": {
    "title": {
      "type": "string"
    },
    "file": {
      "collection": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }
  }
}

```
and components_document_documents is the collection name in mongo

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: mongo v4.0.12
- Operating system: ubuntu 18.04

**Additional context**
any ideas on how to troubleshoot this? or what to change which will allow me to add to my content type? 

thank you

**Comment by shakahl** [comment]
We are facing with this issue too.

- 3.0.0-beta.18.3
- 3.0.0-beta.18.4 (issue still exists)

**Comment by shakahl** [comment]
After some debug we realized that the problem came from incorrect relation config. The "via" property was not specified on the model's relation. Probably the admin ui created the relation with incorrect config.

**Comment by hkovacs** [comment]
> Specifying the missing via poperty solved this issue.

what file did you change? please provide more details.

**Comment by shakahl** [comment]
> > Specifying the missing via poperty solved this issue.
> 
> what file did you change? please provide more details.

I modified the `api/{model}/models/{model}.settings.json` files.

**Comment by hkovacs** [comment]
@shakahl  
do you think the guide is correct and complete? 
are you using mongodb?

my json files are posted above. i always appreciate if someone finds a mistake in them and shows it to me...

thank you

**Comment by hkovacs** [comment]
im closing this tkt. it turns out that perhaps my json files are fine.

i looked in the network while retesting this bug and actually found the problem for which i will make a new tkt.

**Comment by megetron** [comment]
please note that this symptom happens to me as well but can't say if this is exactly the same issue.
this is happens to me when you edit the "*.settings.json" file with a key starts with a number and afterwards try to add new variables through the UI itsself.
e.g.

```
    "64bit": {
      "type": "boolean"
    }
```

hope it helps
