### ISSUE TITLE
How to handle image upload during Content Group updating

### ISSUE THREAD

**Issue by martineon** [strapi/strapi#4922]
Hello everyone !

I wish you a **Happy New Year** ! 🎉 🎉

I'm a little bit stuck... I want to upload an image to a group during the update of a content..

Let's say i've a list of `Restaurants`, where everyone have a group `Dishes` with a field `img` of type `media`.

I tried this :

```
axios
   .put("http://localhost:1337/restaurant/1", { dishes: [img: FormData] })
   .then(res => console.log(res));
```

But it's returning null on the img field : 

```
{
  id: 1,
  name: "test",
  dishes: [
    {
      id: 1, 
      img: null
    }
  ]
}
```

If someone can enlight me 😉!

Thanks

**Comment by soupette** [comment]
It should be something like this:

```
const data = {
  id: 1,
  name: 'test',
  dishes: [
    {
      id: 1,
      img: new Blob(),
    },
  ],
};
const cleanedData = {
  id: 1,
  name: 'test',
  dishes: [
    {
      id: 1,
      img: null,
    },
  ],
};
const formData = new FormData();

formData.append('data', JSON.stringify(cleanedData));
// Add the file to upload the key corresponds to the uploaded file path
formData.append('files.dishes.0.media', new Blob());
```

**Comment by martineon** [comment]
Hello @soupette !

Thanks for the answer ! 😉

So, if i understood what you said, i've to do this: 

```
axios.post("/upload", formData)
```

Does it mean, i've to separate the image upload from the content update ?

In my case, i want to add a `dishes` to the `restaurant` which is already created.

The **dish** should be like this : 

```
let dish = {
  name: "Ravioli",
  price: 10,
  img: null
}
```
and **restaurant** (already created) : 

```
let restaurant = {
  id: 1
  name: "test",
  dishes: []
}
```

So, with your way i've, first, to update the `dishes` without the image, and then upload the image ?

something like this ?

```
axios
   .put("http://localhost:1337/restaurant/1", { ...dish })
   .then(res => {
     const formData = new FormData();

     formData.append('data', JSON.stringify(res.data));

     formData.append('files.dishes.0.img', new Blob());

     axios.post("http://localhost:1337/upload", formData);
    });
```

Thanks
