### ISSUE TITLE
Update Users and Permissions plugin dependency `purest` to 3.x

### ISSUE THREAD

**Issue by thomb** [strapi/strapi#4929]
**Describe the bug**
`strapi-plugin-users-permissions` relies on `purest@2.0.1` which has 7 known moderate security vulnerabilities associated with its dependencies according to `yarn audit`

**Expected behavior**
`yarn audit` should not report any security vulnerabilities.

I understand that these are "only" `moderate` issues, and from the looks of the `purest` documentation the change to version 3.x is non-trivial.

ps. sorry if this is not a `bug` per se, your documentation guidelines are not helpful.

**Comment by alexandrebodin** [comment]
Hi @thomb we are aware of that but we are very shorthanded. If you are felling like making a PR for it it would be awesome !

Don't hesitate to come and talk to me on our community slack ;)

**Comment by thomb** [comment]
Sounds good, except that http://slack.strapi.io is not currently working so I can't hop on it. 
I'd happily do so otherwise.

**Comment by derrickmehaffy** [comment]
@lauriejim can you take a look at the slack subdomain.

@thomb https://strapi.slack.com/

**Comment by thomb** [comment]
@derrickmehaffy I am unable to sign into the strapi workspace via that slack link, from the Slack password reset email:

```
You asked us to send you a password reset link for strapi.slack.com. It turns out the email address <my.email@address> doesn't have an account for that workspace yet.

If you’re pretty sure you do have an account, you can find your workspace by trying a different email address.
```

**Comment by derrickmehaffy** [comment]
Strapi itself doesn't host the slack server it's an SaaS service. So issues with authorization is something Strapi itself has no control over. Although I did just try to register another test user and it did work just fine? (Also I'm on the slack right now with my main account)

**Comment by thomb** [comment]
Was it an `@strapi.io` email address? I don't have the ability to register a user with an email address I have access too.

**Comment by derrickmehaffy** [comment]
No I don't work for Strapi my main user account is an @gmail.com address but I just tested with my work email and with an email server I own.

**Comment by thomb** [comment]
Alright. Thanks @derrickmehaffy that enough of you playing my tech support ;). 
I'll sort it out. Appreciate you taking the time to respond all the same.

**Comment by derrickmehaffy** [comment]
No problem, looking forward to seeing you on slack :P but please if you do want to work on this, it would **greatly** appreciated. Alex is single handed right now (he is lead backend developer for Strapi) and it would really help out the project.

**Comment by thomb** [comment]
I'll be checking to see what's involved with the update today to see if it's feasible for me to take on.

Mainly wanted to hop on slack (I can sign into my many other workspaces - work and personal - just not `strapi` /shrug) to discuss `gatsby-source-strapi` dependency updates as well.

**Comment by alexandrebodin** [comment]
Closing this issue as it was upgraded recently :)
