### ISSUE TITLE
One way relation interface

### ISSUE THREAD

**Issue by ArkhipovK** [strapi/strapi#493]
**Node.js version**:  v8.9.3
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Win7 Ultimate

It is impossible now to create one-way relations via admin pannel interface. 

Moreover i can't figure out how i can specify field for filling the corresponding column. Let assume we have 2 models (stuff and order). And we want the order to belong to some stuff in classical one-to-many relation. Here how we can implement this:
```json
{
  "connection": "default",
  "collectionName": "stuff",
  "info": {
    "name": "stuff",
    "description": "boxing stuff"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "text"
    },
    "price": {
      "type": "decimal"
    },
    "img": {
      "type": "string"
    }
  }
}
```
```json
{
  "connection": "default",
  "collectionName": "order",
  "info": {
    "name": "order",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "stuff": {
      "model": "stuff"
    }
  }
}
```
But the stuff column is empty, despite that I've already set some value to this field:

![default](https://user-images.githubusercontent.com/9945452/35221567-73ec7efa-ff9c-11e7-843d-02058c85cbf6.png)
![default](https://user-images.githubusercontent.com/9945452/35221615-9f34547a-ff9c-11e7-89ef-53c720c3e9f4.png)

**Comment by soupette** [comment]
Hi @ArkhipovK this features is not developed yet. However, you can modify the plugin so you can add other fields.

To do so, start a project in dev mode `strapi new my-project --dev`

Then in the content-manager plugin (path: my-project/plugins/content-manager/admin/src/containers/ListPage/index.js) you need to add the  headers you want to add.

You can create a function like the following before the `render` method

```
addOtherHeaders = () => {
    const otherHeaders = Object.keys(get(this.props.schema, [this.props.match.params.slug, 'relations'], {})).reduce((acc, current) => {
      acc.push({
        name: current,
        label: current,
        type: 'relation',
      });

      return acc;
    }, [])

    return this.generateTableHeaders().concat(otherHeaders);
  }
```

Then you need to modify the `headers` given to the `Table` component.

```
<Table
   records={listPage.records}
   route={this.props.match}
   headers={this.addOtherHeaders()}
   // Other props
/>
```

Then you might need to adapt the `TableRow`component so it displays this need field.

Such feature is not in our ROADMAP for the next upcoming features. Nevertheless you can upvote the feature you would like us to develop in priority on our vote page: https://strapi.io/vote.

**Comment by derrickmehaffy** [comment]
+1 on this for me. Would love to have one way relations with what I'm working on.

**Comment by lauriejim** [comment]
Done https://github.com/strapi/strapi/pull/1199
