### ISSUE TITLE
Show another field (different to ID) on related data combo boxes

### ISSUE THREAD

**Issue by jaime8111** [strapi/strapi#4933]
After updating Strapi to v3.0.0-beta.18.3 I realize that now I don't know how to show a different field on the right related data selection box. I always get the IDs.

![image](https://user-images.githubusercontent.com/531988/71969278-a05f1580-3206-11ea-83a6-492f875f5305.png)

I change the config of the view, but I don't see any change:

![image](https://user-images.githubusercontent.com/531988/71969596-4448c100-3207-11ea-9202-5fc95a31add3.png)

After that I restart Strapi server, but again, I don't see any change.

What do I have to do to view another field on related data combo box?

Thanks!

**Steps to reproduce the behavior**
1. Go to any content type detail with related data.
2. Click on the related data combo box.
3. View the options. All of them show only the ID of each related data

**Expected behavior**
Be able to select wich field will be visible on related data combo boxes.

**System**
- Strapi version: v3.0.0-beta.18.3
- Database: MongoDB

**Comment by soupette** [comment]
You need to click on the `configure the view` link that is located in the right side of the edit view of your content type. Then you can click on your relation and change the displayed field

![Screenshot 2020-01-08 at 11 18 30](https://user-images.githubusercontent.com/13311463/71970405-f339cc80-3208-11ea-8d6c-273662d6ac2c.png)

**Comment by jaime8111** [comment]
I forgot how to do it.

Thanks!

**Comment by jaime8111** [comment]
Just one more question. Every time I will update Strapi in the future I will have to reconfigure all the views?
