### ISSUE TITLE
Certain ContentManager extension methods are not being used

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#4935]
**Describe the bug**
I wanted to override some of the methods from `strapi-plugin-content-manager/services/ContentManager.js` (create/edit/delete), but they're not being used.

**Steps to reproduce the behavior**
1. Copy/paste the `node_modules/strapi-plugin-content-manager/services/ContentManager.js` file to `extensions/content-manager/ContentManager.js`
2. Add some `console.log`'s to the methods
3. Go to the admin panel to invoke some of those

**Expected behavior**
The overriden methods from extensions folder should be used.

**Notes**
**It did work properly on 3.0.0-beta.17.x. After I migrated to 3.0.0-beta.18.x, it stopped working.**

**System**
- Node.js version: 12.10.0
- NPM version: 6.10.30
- Strapi version: 3.0.0-beta.18.4
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
I can confirm that the extension methods aren't being used attempting to add a `console.log()` to any of the following services in that file yields nothing in the Strapi console:

- fetch
- fetchAll
- count
- create
- edit
- delete
- deleteMany
- search
- countSearch

However if you put something like 
```javascript
console.log({
  "Test": "test"
})
```

Above the `module.exports = { ...` it will fire when strapi boots up, so the extension file is being loaded but the extended services aren't being used.

Tagging @soupette and @alexandrebodin for thoughts. (This is a breaking bug for anyone that had custom logic, thus preventing them from updating to Strapi.beta.18.x)

**Comment by alexandrebodin** [comment]
The controller is requiring the service directly. Hence the issue.

Btw what's your usecadse for extending the content manager service ?

**Comment by derrickmehaffy** [comment]
@alexandrebodin I'd imagine something along the lines of validation before it gets saved into the database. I suppose he could probably handle this at the controller level of the CTM?

**Comment by sarneeh** [comment]
@alexandrebodin Exactly as @derrickmehaffy said, I needed some custom validation on saving a model as hooks are not working properly for now.

**Comment by sarneeh** [comment]
Thanks @alexandrebodin!
