### ISSUE TITLE
Sendemail validation bug on specific address

### ISSUE THREAD

**Issue by loongmxbt** [strapi/strapi#4938]
**Describe the bug**
When I POST http://localhost:1337/auth/forgot-password
```
{
	"email": "dragonszy@163.com"
}
```
response
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.invalid"
                }
            ]
        }
    ]
}
```

When I POST http://localhost:1337/auth/forgot-password
```
{
	"email": "dragonszy@gmail.com"
}
```
response
```
{
    "ok": true
}
```

There is some validation error on email domains. Here is the 163.com

**Steps to reproduce the behavior**
1. Go to Postman, make sure the user created
2. POST http://localhost:1337/auth/forgot-password, with email dragonszy@163.com
3. See error, "id": "Auth.form.error.email.invalid"

**Expected behavior**
Email address like xxx@126.com xxx@163.com and so should not be invalid.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.13.1
- NPM version: 6.13.4
- Strapi version: 18.4
- Database: MySQL 5.7
- Operating system: MacOS

**Additional context**

**Comment by lsj333610dl** [comment]
I have the same issue
```
// req
{
    "email": "lsj333610dl@naver.com"
}

// res
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.invalid"
                }
            ]
        }
    ]
}
```

but gmail address is success
```
// req
{
    "email": "lsj333610dl@gmail.com"
}

// res
{
    "ok": true
}
```


* Strapi version: 18.4
* Database: Mongo 4.2
* Operating system: MacOS

**Comment by loongmxbt** [comment]
BTW, when I use mailgun provider, send email to the same address. `http://localhost:1337/auth/forgot-password`
```
{
	"email": "dragonszy@gmail.com"
}
```

It becomes
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.invalid"
                }
            ]
        }
    ]
}
```

When I change to sendmail, it's ok. I think there might be some other validation bug inside.

**Comment by lauriejim** [comment]
Hello @loongmxbt and @lsj333610dl !
Here is a short video of what I did to debug your issue, that will help you understand the issue.
[Screen record](https://www.loom.com/share/81a060e38fdc492586168fb0e7e9f433)
The issue is related to the SMTP server instead of email validation.
As you can see in the video, it could work with your `@163` email.
Here is the [troubleshooting doc](https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#trouble-shooting) about that.

**Comment by loongmxbt** [comment]
@lauriejim  Thank you for the detailed video, I've got some understanding on debugging email service.
The mailgun issue is due to the Mailgun service disabled the domain which causes the error.
