### ISSUE TITLE
Not all fields are render in view mode

### ISSUE THREAD

**Issue by ArkhipovK** [strapi/strapi#494]
**Node.js version**:  v8.9.3
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Win7 Ultimate

My model:

```json
{
  "connection": "default",
  "collectionName": "punchbags",
  "info": {
    "name": "punchbag",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "text"
    },
    "price": {
      "type": "decimal"
    },
    "img": {
      "type": "string"
    },
    "height": {
      "type": "float"
    },
    "width": {
      "type": "float"
    },
    "type_name": {
      "type": "string"
    },
    "icon": {
      "type": "text"
    }
  }
}
```
Response: 
![default](https://user-images.githubusercontent.com/9945452/35224262-360af684-ffa6-11e7-9ed9-ec19b493d587.png)

Result:
![default](https://user-images.githubusercontent.com/9945452/35223606-c46dc58a-ffa3-11e7-8b86-275d69370f89.png)

**Comment by lauriejim** [comment]
I close this issue. We will not do it. 
Maybe in a long futur with a custom configuration for which data display in this table.

**Comment by ArkhipovK** [comment]
So what to do if i don't want to see there only half of my model's fields? Make pull request by myself?

**Comment by derrickmehaffy** [comment]
@ArkhipovK This may be something to submit to the vote page https://strapi.io/vote to see if there is other interest. As I too would be interested in something like this, specifically showing a certain field from a relation.
