### ISSUE TITLE
Dynamic configurations from environment variables

### ISSUE THREAD

**Issue by alexanderwallin** [strapi/strapi#495]
**Node.js version**: 9.4.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Heroku-16 (Ubuntu 16.04)

I'm trying to figure out a way to deploy a Strapi app to Heroku.

A free Heroku instance gets a dynamic port number on each start, provided in the `PORT` environment variable, which a web app needs to serve its content to. Since Strapi configs are in JSON, I can't find a way to adapt to his.

Is there a way? Or would this be a good thing to put in a plugin?

**Comment by Aurelsicoko** [comment]
@alexanderwallin Sure you can do it by editing your `/production/server.json` file like this:

```json
{
  "host": "${process.env.HOST}",
  "port": "${process.env.PORT}",
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  }
}
```

**Comment by alexanderwallin** [comment]
Whoa, brilliant. Thanks!
