### ISSUE TITLE
Error saving enum with null value

### ISSUE THREAD

**Issue by websocket98765** [strapi/strapi#4951]
**Describe the bug**

Document fails to save due to error `SQLITE_CONSTRAINT: CHECK constraint failed:`.

Possibly related to: https://github.com/strapi/strapi/pull/4773

**Steps to reproduce the behavior**
1. Create a model with a non-required enum.
2. Create a new document and don't not alter this enum's value. Save it. It will save successfully. 
3. Edit the enum value. Save it. It will save successfully.
4. Edit the enum value back to "Choose here". Save it. It will fail to save. It will show an error message with a long SQL message that's hard to read. Check the console to see the logged error. It will contain `SQLITE_CONSTRAINT: CHECK constraint failed`

**Expected behavior**
In step #4, it should be possible to set this non-required enum back to "Choose here" and it should save successfully.

**Likely cause**

- In Step #4, viewing the logged error, it shows the SQL it's attempting to use and shows it is trying to store an empty string as the value for our non-required enum.
- If I view the table's creation SQL, I see it contains a constraint: 
```
`myEnumField` text check  `(`myEnumField` in ('foo', 'bar','baz'))`
```
- The problem is that it's trying to store a value of an empty (`''`) and should be storing `NULL`. This way the constraint will pass for our non-required enum.

**System**
- Node.js version: node v13.5
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.2 
- Database: SQLite
- Operating system: mac

**Comment by derrickmehaffy** [comment]
@websocket98765 please test with latest beta.18.4 as I believe there have been a few patches now that should resolve this

**Comment by websocket98765** [comment]
Looks good in 18.4
