### ISSUE TITLE
Component database collection rename not accurate in migration guide

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#4952]
**Describe the bug**
following the migration guide https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html

the command for renaming collection doesnt work for my version of mongodb
`db.collection.renameCollection('groups_my_group', 'components_my_component');`
also, according to new category usage i think this is more correct?
`db.collection.renameCollection('groups_my_group', 'components_myCategory_my_component');`

perhaps if the guide command works for a specific version of mongodb, then that needs to be specified.

the following commands worked for me in mongodb v4:
db.groups_addresses.renameCollection('components_address_addresses');
db.groups_documents.renameCollection('components_document_documents');

also note that my command includes the category while the guide command does not. of course my way might be wrong. i await someones feedback.
ie: `db.groups_myGroupName.renameCollection('components_myCategoryName_myComponentName');`

Thank you

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: mongo v4.0.12
- Operating system: ubuntu 18.04

**Comment by alexandrebodin** [comment]
Hi @hkovacs You don't have to specifically rename it using the category. It's really up to you. When generating a new content type we do use the category to generate the collectionName but you can change it. 

Open to have a PR to use the category as it might help user better understand ;)

**Comment by sreddim** [comment]
the groups got deleted from mongo DB after renaming groups folder to components and moved them under category. 
when I try the command for renaming the collection , it gives "renameCollection must either take a string and an optional boolean or an object. "

I tried the command as mentioned by @hkovacs with/ without category it gives ""source namespace does not exist" error, which make sense as the groups were deleted from mangodb database.

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html 
I followed exactly the same in documentation untill migration part. now stuck because there are no groups table in DB.

**Comment by hkovacs** [comment]
@alexandrebodin thank you for your guidance. your statement "You don't have to specifically rename it using the category" disagrees with the functionality i found when creating a new component in 18.3. the collection gets named with the category name.

while i would love to provide a pr, my system is not working properly, so i am afraid that i am not yet qualified. i think the strapi pros really need to take some time to scrub the guide as it regards to mongodb so that us users can get back to normal proper operations.

**Comment by alexandrebodin** [comment]
@hkovacs If you read my response again I do say that we use the category name when creating a component :) But you can change the collectionName in the json file generated if you wish to :)

I do wish we were add more hands to do this. Hopefully soon !

**Comment by hkovacs** [comment]
ok, so it is optional, but the system does it. us users need things to be a bit more clear. we are here asking for clarity because our strapis are broken because the guide is not clear (as it pertains to mongodb).

i think there is enough feedback out there that we need a working guide and that it is a smart idea at this point to stop development and scrub the guide and ensure existing users are operational. otherwise you are just leaving a trail of frustrated users. 

i left keystone because 3 months ago strapi had very good community support in slack while keystone was nearly dead silent. now it seems that the strapi community is struggling with this upgrade and the strapi folks are not realizing when it's time to jump in and lead. 

this is a delorean. 
![delorean-5](https://user-images.githubusercontent.com/1257358/72096767-8f57f680-3323-11ea-9bbe-5dc0386b7391.jpg)

it looked cool in the 1980's, but you wouldn't want to use it for transportation as it didnt run well. dont let strapi become a delorean. please helps us by providing a correct and accurate guide.

**Comment by alexandrebodin** [comment]
@hkovacs I do understand that need for sure.

We are really shorthanded for the amount of work to do and it is really hard to be everywhere at once. I'm sure you can understand that.

If you are willing to help us please create a PR to upgrade the guide.

We have been improving our migration guides as much as we could and will continue to do so thanks to the support of the community and the feedbacks we receive. So keep them coming ;)

**Comment by gustawdaniel** [comment]
Closed without a link to docs.

It should be reopened and solved.
