### ISSUE TITLE
OAuth signin does not create a new user

### ISSUE THREAD

**Issue by wdhodges** [strapi/strapi#4954]
**Describe the bug**
Create a new application, enable an OAuth provider, launch the react-login example, try to login with discord / Microsoft. Get a successful `token` for both, however a new user is not created. Maybe I'm doing this wrong? Not really sure.

**Steps to reproduce the behavior**
See above.

**Expected behavior**
Logs in, creates a user with the correct provider listed.

**Screenshots**
N/A

**Code snippets**
N/A

**System**
- Node 12.14.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.4
- Database: SQLITE
- Operating system: Windows 7 and Windows 10

**Additional context**
I could be doing this wrong, so if I am, my apologies

**Comment by wdhodges** [comment]
Okay so if you create a strapi app with `npx`, this error happens. However, if you globally install strapi and use `strapi new` then it works.

**Comment by derrickmehaffy** [comment]
That is quite odd and two should not be any different :thinking:

**Comment by wdhodges** [comment]
I was able to re-create on a Windows 7 and Windows 10 box, can you try to
re-create if you get a moment? Just to make sure I’m not losing my mind 😅

**Comment by lauriejim** [comment]
Hello it's super odd since I reviewed all providers' login and it worked fine on my side.
Here is a [screen record](https://www.loom.com/share/9c9dc22ebcb144f587eaed852acc860f)

**Comment by wdhodges** [comment]
This has been fixed since Beta.16. Thanks!

**Comment by lauriejim** [comment]
Great thank you for the update

**Comment by negati-ve** [comment]
Experiencing same issue on beta.20

**Comment by mmorainville** [comment]
Hi,

I have the same problem on beta.20.1, on my front callback URL I retrieve the following parameters in the query instead of retrieving as expected a user and a JWT. Also, no user is created in the Strapi backend.

```
access_token: "ya29.a0AfH6..."
id_token[header][alg]: "RS256"
id_token[header][kid]: "960a7e..."
id_token[header][typ]: "JWT"
id_token[payload][at_hash]: "whdElY..."
id_token[payload][aud]: "814...-2oelml....apps.googleusercontent.com"
id_token[payload][azp]: "814...-2oelml....apps.googleusercontent.com"
id_token[payload][email]: "...@gmail.com"
id_token[payload][email_verified]: "true"
id_token[payload][exp]: "1590337247"
id_token[payload][iat]: "1590333647"
id_token[payload][iss]: "accounts.google.com"
id_token[payload][sub]: "116364..."
id_token[signature]: "PnLDLU..."
raw[access_token]: "ya29.a0AfH6..."
raw[expires_in]: "3599"
raw[id_token]: "eyJhbG...cgqVAgR5YlzP5WWCeKn30hZ9xfn4xrg"
raw[scope]: "openid https://www.googleapis.com/auth/userinfo.email"
raw[token_type]
```

**Comment by zreecespieces** [comment]
I'm currently experiencing this:
- Strapi 3.0.0
- Node v13.11.0
- MongoDB Atlas
- macOS 10.14.6

I'm successfully redirected from the application frontend to the Facebook OAuth screen via http://localhost:1337/connect/facebook. Then I'm redirected back to the application correctly after giving permission, but only with the query parameters:

access_token: EAAKZ...
raw[access_token]: EAAKZ...
raw[token_type]: bearer
raw[expires_in]: 5183999

No user is created in the backend database, and no 'user' or 'jwt' are returned with the payload as described [here](https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers)

This is not expected behavior, correct? Or are we then supposed to use this access token ourselves to create the user in Strapi?

**Comment by GabeL7r** [comment]
I noticed when I set `The redirect URL to your front-end app` to `/auth/github/callback` the user gets created, however, they don't get redirected to my front end application. If I redirect to the frontend application the user doesn't get created.

**Comment by petersg83** [comment]
Please, check out this PR where the doc is clearer about the login flow : https://github.com/strapi/strapi/pull/7132
