### ISSUE TITLE
Scoped Policies doesn't work with custom resolver Graphql

### ISSUE THREAD

**Issue by canhkieu** [strapi/strapi#4955]
**Describe the bug**
Global Policies is work very well but Scoped Policies doesn't work with custom resolver Graphql with this error
```
error Ignored attempt to bind to GraphQL query "comments" with unknown policy "isOwner"
```

**Code snippets**

**api\comment\config\policies\isOwner.js**
```
module.exports = async (ctx, next, args) => {
  console.log("Enter isOwner");
  await next();
};
```

**api\comment\config\schema.graphql.js**
```
module.exports = {
  resolver: {
    Query: {
      comments: {
        description: "get comments",
        policies: [
          "plugins.users-permissions.isAuthenticated",
          "isOwner"
        ],
        resolver: "Comment.index"
      }
    }
  }
};
```

**api\comment\controllers\comment.js**
```
module.exports = {
  index: async ctx => {  
    return await strapi.services.comment.find();
  }
};
```
**System**
- Node.js version: 10.12 
- NPM version:
- Strapi version: tested on 3.0.0-beta.18.3 and 3.0.0-beta.18.4
- Database: sqlite
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello @canhkieu !
Thank you for reporting this issue.
You will find it here - https://github.com/strapi/strapi/issues/3134
This one is a duplicate so I close it.
