### ISSUE TITLE
Content migration

### ISSUE THREAD

**Issue by bchristie** [strapi/strapi#4957]
Hi team, 

Any plans or solutions regarding content migration (either for environment shifts (dev to qa to prod) or as a deploy mechanism? 

Seems you're coupled to the state of a database & reliant on full DB backup/restore. Would be great if you could serialize that out (including files such as schema definitions or plugins) making the upgrade a 2 step process:

1. Start w/ strapi baseline, database agnostic
2. Import package w/ schema, baseline data, etc. and it adds it to configured DB.

In docker land, this would be comparable to just adding a layer atop strapi/strapi container w/ cli call.

(Bonus: ability to spin up instance w/ specified admin account and not hack it with a curl post)

Could also be used when going between multiple DBs (sqlite in dev, mongo in pre-prod).

Thoughts?

**Comment by derrickmehaffy** [comment]
Please see the following entry on the Product Board, the rough timeline is work will start on this feature in Q2 2020: https://portal.productboard.com/strapi/1-public-roadmap/c/12-migrate-across-environments
