### ISSUE TITLE
Use transaction or lock database connection on database schema init

### ISSUE THREAD

**Issue by cadavre** [strapi/strapi#4958]
On first launch of Strapi it creates a database schema based on model definitions. Unfortunately it looks like whole process is async and many SQL queries are sent to the server simultaneously.

This causes many different problems, including:

```
ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
```
or
```
ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
DETAIL:  Key (extname)=(pg_trgm) already exists.
```

**Comment by derrickmehaffy** [comment]
@cadavre I agree this is a bug but can you update your issue to properly follow the template, I'll reopen it once it's been updated. Thanks :)

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by kargakis** [comment]
For anyone lurking in this issue, I stumbled across this error too and the issue was that I was using the same collectionName across different components and content types so my DB client was trying to create the same table in the DB more than once.

**Comment by derrickmehaffy** [comment]
I believe this possibly relates to #1114
