### ISSUE TITLE
Handle JSON input in content manager

### ISSUE THREAD

**Issue by harshilsharma63** [strapi/strapi#496]
**Node.js version**: 8.9.3
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Ubuntu 16.04 x64

Additional details -
**Database**: PostgreSQL
**Database version**: 9.6.6

Values in JSON fields appear as `Map {"<key>": <value> }`. For example 

Value saved through UI - `{"a": 5, "b": 10}`
Value persited in database - `{"a": 5, "b": 10}`
Value displayed in UI - `Map { "a": 5, "b": 10 }`

**Comment by Aurelsicoko** [comment]
@harshilsharma63 Not sure the clearly understand the issue here... Can you give us more details?

**Comment by harshilsharma63** [comment]
@Aurelsicoko please see following screenshots to get a better idea

Data in database - https://imgur.com/zt3usIa
Same data displayed in Strapi admin - https://imgur.com/GPbgYWd

My model.json
```
{
  "connection": "My DB",
  "collectionName": "foobar",
  "info": {
    "name": "foobar",
    "description": ""
  },
  "options": {},
  "column_1": {
    "name": {
      "type": "string"
    },
    "column_2": {
      "type": "json"
    }
  }
}
```

**Comment by harshilsharma63** [comment]
I went through the source code and it seems you are using `Immutable.Map` for JSON objects retrieved from the database. Is it this `Immutable.Map` that is causing the extra "Map" in output. Stringifying it seems to solve the issue.

**Comment by harshilsharma63** [comment]
Any update on this one? Its effectively making admin interface unusable for JSON objects.

**Comment by soupette** [comment]
Hi @harshilsharma63 we'll look into it

**Comment by acoreyj** [comment]
Was something done here because I am seeing a different issue. Saving json data from the admin panel saves to the database as a string instead of as json.

![image](https://user-images.githubusercontent.com/11298888/36552118-bb637af6-17be-11e8-9d07-c629da21f445.png)
![image](https://user-images.githubusercontent.com/11298888/36552157-d0218ff0-17be-11e8-818b-4e09358420cc.png)
![image](https://user-images.githubusercontent.com/11298888/36552345-4049dff8-17bf-11e8-9bd2-060d4ff48a76.png)

**Comment by Aurelsicoko** [comment]
@acoreyj The solution to this issue is to add a real JSON field in the UI. Currently, @soupette is working on the WYSIWYG field and one of his next steps is to develop the JSON field component. I can give you a release date but it should be available in the coming weeks (~6 weeks).

**Comment by Joshfindit** [comment]
Having a different but related issue: saving a json object in the content manager is changing it to `[object Object]` (see #970)

**Comment by soupette** [comment]
Hi @Joshfindit, we haven't started to implement the JSON input yet.
However you can 'easily' implement your own in the content manager ([I found this one](https://github.com/mac-s-g/react-json-view)) that shouldn't be hard to add.

In order to do you have to create an JSONInput in ` plugins/content-manager/admin/src/components/JSONInput/index.js`;

then you need to import it in the `Edit` component and pass it to the `Input` component like the following:

```
render(){
    return (
      <div className={styles.form}>
        <div className="row">
          {this.orderAttributes(this.state.displayedFields).map((attr, key) => {
            const details = this.state.displayedFields[attr];
            // Retrieve the input's bootstrapClass from the layout
            const layout = this.getInputLayout(attr);
            const appearance = get(layout, 'appearance');
            const type = !isEmpty(appearance) ? appearance.toLowerCase() : get(layout, 'type', getInputType(details.type));

            return (
              <Input
                autoFocus={key === 0}
                customBootstrapClass={get(layout, 'className')}
                didCheckErrors={this.props.didCheckErrors}
                errors={this.getInputErrors(attr)}
                key={attr}
                label={get(layout, 'label') || details.label || ''}
                multiple={this.fileRelationAllowMultipleUpload(attr)}
                name={attr}
                onBlur={this.props.onBlur}
                onChange={this.props.onChange}
                placeholder={get(layout, 'placeholder') || details.placeholder}
                resetProps={this.props.resetProps}
                selectOptions={get(this.props.attributes, [attr, 'enum'])}
                type={type}
                validations={this.getInputValidations(attr)}
                value={this.props.record[attr]}
                // Here your new component
                customInputs={{ json: JSONInput }}
              />
            );
          })}
        </div>
      </div>
    );
  }
```

**Comment by raza2022** [comment]
@soupette can you elaborate some more please then so it's so nice of you
in fact I implemented the above mentioned but no changed reflected in display then I just commented the edit component in fully still no change :( I am just confused that from where edit page rendering
help will be greatly appreciated I I will made pull request for it if able to do it for others
