### ISSUE TITLE
strapi thinks 0 is not a number

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#4960]
**Describe the bug**
while trying to add a new field to my content type, i got a notice that "an error occurred". i had the network tab open and dug into the item and the preview subtab showed me:
`contentType.attributes.ein.default must be a `number` type, but the final value was: `"0"`

now if anyone is not sure about this... 0 is most definitely a number. im not going to harp...

**Steps to reproduce the behavior**
i have provided that detail above

**Expected behavior**
i expect that if i define that a field is a number and the default should be 0, then strapi code should be ok with that and save the content type correctly.

also, if an error already makes it to the network, then it would be a tremendous improvement if the error notice provided that error message.

at this point i'm not feeling comfortable enough to say that i can fix any of this in strapi be or fe, but if i do figure out how, then i will certainly update here.

**Screenshots**
![Screenshot from 2020-01-09 21-41-23](https://user-images.githubusercontent.com/1257358/72099757-f1b3f580-3329-11ea-9439-0b3dadd3798e.png)

**System**
Node.js version: 10.16.3
NPM version: 6.9.0
Strapi version: 3.0.0-beta.18.3
Database: mongo v4.0.12
Operating system: ubuntu 18.04

**Comment by hkovacs** [comment]
i was able to fix the 0 issue by changing settings `api/association/models/Association.settings.json` and removing the double quotes from "0" and making it just 0

that allowed the the content type to save correctly.

while i do consider this issue to be closed for its primary. the fact the the notice isnt displaying the network message makes me want to leave this open while i dig into that...

if any of the bosses think this should be closed, plmk

**Comment by lauriejim** [comment]
Hello! I'm not sure to understand the steps you did. It's not crystal clear with a step by step.

Here is what I tried based on your description - https://www.loom.com/share/921a52e28e9940b09e2c11a8cbe3cfa2
It works well.

Let me know if I miss something.

**Comment by hkovacs** [comment]
> Hello! I'm not sure to understand the steps you did. It's not crystal clear with a step by step.
> 
> Here is what I tried based on your description - https://www.loom.com/share/921a52e28e9940b09e2c11a8cbe3cfa2
> It works well.
> 
> Let me know if I miss something.

the problem was not with saving a value in a record. the problem was with saving a new field in the content type while my ein field was set as number saving default value of "0". when i tried saving the content type, the notice in the screenshot above was displayed. i saw the details in the network. it would be helpful if the details in the network would display in the notice.

**Comment by lauriejim** [comment]
I'm not sure to follow you, can you write the step by step actions to do to reproduce your issue please.

**Comment by pedrogray** [comment]
I'm having a similar issue. First I created a content-type, then a number field without a default value. Then I tried to update the default value to 0 and it wouldn't update it (the save button was never green for 0, it was for other numbers tho). Even setting it manually in the model file didn't seem to work, as I tested with a POST request and the new record's field value was still null.

**Comment by hkovacs** [comment]
> I'm having a similar issue. First I created a content-type, then a number field without a default value. Then I tried to update the default value to 0 and it wouldn't update it (the save button was never green for 0, it was for other numbers tho). Even setting it manually in the model file didn't seem to work, as I tested with a POST request and the new record's field value was still null.

what version? was it after upgrading from 17x to 18x? please provide the snippet of that field from the Yourmodel.settings.js.

**Comment by hkovacs** [comment]
> I'm not sure to follow you, can you write the step by step actions to do to reproduce your issue please.

i will try to make a video walk through next week. 

the key is that if an error is thrown to the network in the console, then it should bubble up to the notice that appears so that users know what has failed...

i would love to help with this, but that will have to be in february.

**Comment by pedrogray** [comment]
> > I'm having a similar issue. First I created a content-type, then a number field without a default value. Then I tried to update the default value to 0 and it wouldn't update it (the save button was never green for 0, it was for other numbers tho). Even setting it manually in the model file didn't seem to work, as I tested with a POST request and the new record's field value was still null.
> 
> what version? was it after upgrading from 17x to 18x? please provide the snippet of that field from the Yourmodel.settings.js.

Actually I just solved it by replacing default: 0 to default: "0" in the .settings.js.

**Comment by hkovacs** [comment]
> > > I'm having a similar issue. First I created a content-type, then a number field without a default value. Then I tried to update the default value to 0 and it wouldn't update it (the save button was never green for 0, it was for other numbers tho). Even setting it manually in the model file didn't seem to work, as I tested with a POST request and the new record's field value was still null.
> > 
> > 
> > what version? was it after upgrading from 17x to 18x? please provide the snippet of that field from the Yourmodel.settings.js.
> 
> Actually I just solved it by replacing default: 0 to default: "0" in the .settings.js.

interesting that your fix was the reverse of mine. glad you solved it.
