### ISSUE TITLE
/connect/google?callback=<callback_url> isn't working

### ISSUE THREAD

**Issue by fregu** [strapi/strapi#4961]
**Describe the bug**
According to the documentation I am supposed to be able to add ?callback= with an url to configure an other redirect URL than is defined on the Provider.

There are two problems with this, firstly the check for provider in strapi-plugin-users-permissions/controllers/Auth.js (line: 258) does not take the querystring into consideration and any request gets ´Provider is not enabled`.

One simple fix to this is changing the code to 
```js
const [requestPath] = ctx.request.url.split('?')
    const provider =
      process.platform === 'win32'
        ? requestPath.split('\\')[2]
        : requestPath.split('/')[2];

    const config = grantConfig[provider];
```

The next problem is that the connect-url used for triggereing an provider authentication `/connect/google` is triggered again when the authentication from the provider is complete and the app, returns to the url `/connect/facebook/callback`

since both these paths is handled by the route `/connect/*` in strapi-plugin-users-permissions/config/routes.json (line: 191)

This time the callback URL is no longer in the return request, and thus Strapi always redirects to the callback_url defined in Strapi admin.

**Steps to reproduce the behavior**
1. Enable a provider with a valid OAuth Provider
2. add the `?callback=http://differentURL.tha.in.starpi.com`
3. Get error message, 400: Provider is not enabled 
4. Fix issue accordion to code example above
5. Find new bug where you callback url is totally ignored.

**Expected behavior**
I expect Strapi to redirect to the callback url I defined in the connect request

**Suggested solution**
Either store the callback URL so it is used when getting response from provider, or see if it is possible to pass along the callback queryString to provider to send back in response.

**Comment by derrickmehaffy** [comment]
@fregu can you please make a PR to fix this?

**Comment by fregu** [comment]
I could for the first issue, but it still would not work, since the callback url parameter is lost in all redirects. Thats why I decided on creating an issue instead. 

If anyone have a suggestion on how to best solve it, I would be more than happy creating a PR.
