### ISSUE TITLE
Support MySQL data type SET

### ISSUE THREAD

**Issue by matbrgz** [strapi/strapi#4963]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

Enum is used for radio box, but if yout list has less than 64 items you could use SET for the checkboxs. This is a elegant MySQL solution instead of use all varchar 255.

Enum you must choose only one option.
Set you could storage more than one option.

**Comment by derrickmehaffy** [comment]
(note this would need to be a new data type, enumeration values should only have one option, it's a binary state)

That being said it would be nice to have some multi-select field, API wise we could just post an array.

**Comment by derrickmehaffy** [comment]
Setting as duplicate to: https://github.com/strapi/strapi/issues/784
