### ISSUE TITLE
My Strapi site went down due to https://analytics.strapi.io/track CORS policy change

### ISSUE THREAD

**Issue by onexdata** [strapi/strapi#4975]
**Describe the bug**
It looks like someone changed something for analytics.strapi.io.  My Strapi site was working perfectly last night, but today it's down. When I try to login to the admin page, I get a spinner and then a CORS policy error trying to access https://analytics.strapi.io/track.  When I disable the uuid for tracking, everything works.

**Steps to reproduce the behavior**
Try to login to Strapi admin, you will be unable.

**Expected behavior**
Strapi analytics should not take down the entire admin app.

**Screenshots**
![image (4)](https://user-images.githubusercontent.com/5068507/72171062-177be180-33a0-11ea-8da5-7da1ff58deb4.png)

**Comment by onexdata** [comment]
Looks like someone fixed whatever was causing the CORS issue, because it's back up. Is it possible to confirm that if the tracker doesn't work you can't login to admin and patch that?

I don't mind using Strapi analytics to provide feedback, but I also want to be able to login to the backend 😃

**Comment by derrickmehaffy** [comment]
@onexdata this shouldn't be a problem in newer versions, can you confirm what strapi version you are ok?

**Comment by derrickmehaffy** [comment]
As there has been no update from @onexdata with regards to the current strapi version in use, I'm marking this as closed. It can be reopened when more information is provided.

**Comment by mzndr** [comment]
I'm having this exact issue right now. Popped up out of nowhere.
