### ISSUE TITLE
Cannot see all possible options in relations fields

### ISSUE THREAD

**Issue by Jesus82** [strapi/strapi#4977]
**Describe the bug**
After creating a one belong to many relations between items from the same table (something like _Food has many Foods_ in the table Food), when I try to enter the relationship (Meat isParent of Meatballs), the list of options available are not the whole table, but just 20 items. 

**Steps to reproduce the behavior**
1. Create the table Food
2. Go to Content Type Builder
3. Create a hasParent _**Food** has many Foods **hasChild**_ relation in the Food table
4. Create a relationship
5. Check the items available in the dropdown menu and see if you can choose among all the items in the Food table

**Expected behavior**
I can choose among any item

**System**
- Node.js version: v10.15.2
- NPM version: 6.13.4
- Strapi version: Strapi v3.0.0-beta.18.4
- Database: postgresql
- Operating system: Ubuntu 19.10

**Comment by soupette** [comment]
**cc/** @Aurelsicoko

**Comment by ragnorc** [comment]
Same issue, search also does not return all options.

**Comment by soupette** [comment]
@lauriejim we are not displaying relations in the list view, do so I need a design...

**Comment by Jesus82** [comment]
> Hello @Jesus82 ! I think your issue is the same as this one - #4407
> Can you confirm please.
> @soupette I think this is an issue to fix, not related to @Aurelsicoko

Hi, in my case, I cannot see more items if I go to the bottom of the dropdown, then back to the top, then back to the bottom. I also cannot see any petition in the console.

Also, when I input a text in the dropdown menu, it never returns any result.

**Comment by lauriejim** [comment]
Can you please check if there is a request in your network when you scroll down?

**Comment by Jesus82** [comment]
> Can you please check if there is a request in your network when you scroll down?

There is no request, even going top and bottom of the dropdown several times. Tested in FF and Chrome.

**Comment by lauriejim** [comment]
OKay thank you for these details

**Comment by soupette** [comment]
I am closing this issue as it has been fixed with the `beta.19` release. Feel free to reopen it if you think it was not fixed correctly.

**Comment by Jesus82** [comment]
Updated to v3.0.0-beta.19.3, but the problem still persists

![strapi](https://user-images.githubusercontent.com/8875832/76119476-d0048100-5fef-11ea-8545-451f0a9b1af7.gif)

**Comment by lauriejim** [comment]
Hello @Jesus82 - Just tried again and it works - https://www.loom.com/share/d996fdb4c50142ab84ccf727e5436694

**Comment by Jesus82** [comment]
Hi @lauriejim 
I've just updated to 3.0.0-beta.19.4, and rebuilt the admin and I still have the same issue (both in Firefox and Chromium latest versions). Any hints of what I could do more?

Cheers!

**Comment by lauriejim** [comment]
Hello, so did I do well in the last video?
Because if I did, I don't have any understanding of your issue.

**Comment by Jesus82** [comment]
Hi @lauriejim, yes, in your video the issue was solved. The problem is that in my project it is still unsolved (I've just updated to beta-20), it still happens the same issue as in the video I posted (when you try to select an option, it just shows the first 20 options with the first 20 id's).

So my questions are:
- Is there any options/settings that might be causing this behaviour?
- Is there anything else I could do in order not to be forced to delete my project and create it again? (I'm thinking here about deleting some cached folder).

Thanks in advance!

**Comment by lauriejim** [comment]
Hum can you please try to clear your npm cache, clear everything you can and re-install node modules and rebuild your admin.

**Comment by Jesus82** [comment]
Here's what I did:
- Deleted all registries in local database, and created them again.
- Deleted local repository.
- `git init` and `git clone` again
- `npm install && npm run build --clean`

Problem still persist. If you want to clone the repo to take a look just let me know.

Cheers!
