### ISSUE TITLE
Change favicon .ICO to retina image @2x

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#4981]
Create Strapi project.
Go to http://localhost:1337/admin/
Observe favicon of bad quality - screenshot is attached.

<img width="110" alt="favicon" src="https://user-images.githubusercontent.com/1038168/72215153-5d5fb380-3520-11ea-9d49-43b071cbea42.png">

Please, change current favicon to file @2x for support retina displays, for example, Macbook Pro.

**Comment by lauriejim** [comment]
Fixed in the stable version of Strapi.
