### ISSUE TITLE
Can't save content model and start Strapi server after adding "Published_at" field

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#4984]
I created content type Article. 
A table with all articles has columns: "Created_at" and "Updated_at" by default.
I would like to keep drafts in the CMS, so I need to have additional field "Published_at" for separation of drafts and finished articles.

**What I did**

I added field "published_at" to content type Article.

<img width="850" src="https://user-images.githubusercontent.com/1038168/72236727-1984b100-35e9-11ea-8d37-3d71c19353ce.png">

Clicked "Save" button for this content type.

**What happened**

Strapi couldn't restart automatically:

<img width="1400" src="https://user-images.githubusercontent.com/1038168/72236780-3e792400-35e9-11ea-8c53-8802c6c28c7f.png">

In the terminal:

<img width="1003" src="https://user-images.githubusercontent.com/1038168/72236803-55b81180-35e9-11ea-91f7-31391e1283f6.png">

**Questions**

1. How could I fix the problem?
Now I can't start Strapi server in the terminal, it shows the same error:

```
[2020-01-13T06:46:25.262Z] error Impossible to register the 'article' model.
[2020-01-13T06:46:25.262Z] error Error: SQLITE_ERROR: duplicate column name: published_at
```
2. Could you add some alert about hidden columns and its names, please, to admin panel?
I wouldn't add field "published_at" if I knew that Strapi has this column in background.

======= 

Strapi 3.0.0-beta.18.4 (node v12.14.0)

**Comment by lauriejim** [comment]
Hello! 

I tried to reproduce your issue be I couldn't.
Here is what I did - https://www.loom.com/share/89ab5ccac0df414790a12c66056d9e44

Let me know if I missed something.

Here is an article (will be published this week) about schedule publication - https://github.com/strapi/strapi/pull/4999/files
Could be useful for you.

**Comment by lwintjen** [comment]
Hello, I experienced the same issue, with `content`, `description`, `datum` when written in lowercases.
![image](https://user-images.githubusercontent.com/43049559/73137466-ad7a6200-4058-11ea-8741-6d28344bbafd.png)
![image](https://user-images.githubusercontent.com/43049559/73137468-b1a67f80-4058-11ea-8fbc-82bde300608e.png)
![image](https://user-images.githubusercontent.com/43049559/73137486-e1558780-4058-11ea-85cc-da7cd82bd9b3.png)

To fix this, I had to manually change the fields in the `CONTENT_TYPE.settings.json` file. You should be able to fix it aswell by doing the same @teinett 
![image](https://user-images.githubusercontent.com/43049559/73137489-e9adc280-4058-11ea-9b57-eed8eb13da83.png)
