### ISSUE TITLE
Set password complexity

### ISSUE THREAD

**Issue by alxnkt** [strapi/strapi#4990]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

I would like to be able to set password complexity. It would be convenient to set restrictions to password length, big letters, small letters, numbers, etc
I'm not sure, if this is related to [this request](https://portal.productboard.com/strapi/1-public-roadmap/c/14-validations?utm_medium=social&utm_source=portal_share), so I didn't create new one.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by lauriejim** [comment]
Hello @alxnkt ! Thank you for this proposition.
I ping @Aurelsicoko about this topic.

**Comment by Aurelsicoko** [comment]
Oh, nice one! @soupette could you give me how complicated is it to implement that?

**Comment by derrickmehaffy** [comment]
Id say adding a simple regex validation for both the frontend and backend and just make it editable (pretty sure it's already using regex) and store that in the core_store.

**Comment by soupette** [comment]
@Aurelsicoko it's not complicated at all, I think there's an opened PR #4924 that allows to set a Regexp for a field.

**Comment by derrickmehaffy** [comment]
> @Aurelsicoko it's not complicated at all, I think there's an opened PR #4924 that allows to set a Regexp for a field.

This also needs to be added to the backend for the REST/GQL routes however for registering. @alexandrebodin thoughts?

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/security/p/set-password-complexity
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
