### ISSUE TITLE
Managing scheduling sendgrig parameters "send_at"; "send_each_at" "batch_id" 

### ISSUE THREAD

**Issue by jeremy-hubsy** [strapi/strapi#4993]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I try to schedule emailing with sendgrid for the app I'm building. But the send_at, send_each_at and batch_id option is not manage by the strapi provider. 
Do you think you'll manage the send_at option with strapi one day? 
Thanks in advance for your reply.

**Comment by lauriejim** [comment]
Hello @jeremy-hubsy !
It's not planned but you can easily add these options in the [sendgrid provider](https://github.com/strapi/strapi/blob/master/packages/strapi-provider-email-sendgrid/lib/index.js)
I suggest you submit a pull request on the file I linked.
If you have any questions, I can help you.

**Comment by jeremy-hubsy** [comment]
Thanks a lot Jim for your reply!
I really needed these features so I looked on my own without knowing that you had answered.
The solution I found is to put in the service folder of my controller a personalized connection to sendgrid. In this way the send_at and the batch_id work.
