### ISSUE TITLE
Unable to deep query manually with populate

### ISSUE THREAD

**Issue by samuelpetroline** [strapi/strapi#4996]
**Describe the bug**

I have a case where I need to query on a nested property
`professional.professionalCategories.name` where `professionalCategories` is a many to many relation with `professional`.

It works fine until I need to populate some other field.

When adding 
```js
     populate = [
            {
                path: 'user'
            },
            {
                path: 'professionalCategories'
            },
            {
                path: 'skills'
            },
            {
                path: 'projects',
                populate: {
                    path: 'projectImages'
                }
            }
        ]
```
It throws `TypeError: path.split is not a function`. I noticed it was because I was passing an object array instead of a string array. 

But, by passing an array `['user', 'professionalCategories', 'skills', 'projects', 'projects.projectImages']` it throws another error: `MissingSchemaError: Schema hasn't been registered for model "professional".`

The populate with object array works perfectly when there is no filter

**Steps to reproduce the behavior**

**Expected behavior**
It should query correctly and populate

**Screenshots**

**Code snippets**
Full code

```js
const query = {
    'professionalCategories.name': 'foo'
}

const entities = await strapi.query('professional')
                .find(query, [
                        {
                            path: 'professionalCategories'
                        },
                        {
                            path: 'projects',
                            populate: {
                                path: 'projectImages'
                            }
                        }
                    ])
```

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB
- Operating system: Linux Mint

**Additional context**

**Comment by lauriejim** [comment]
Hello @samuelpetroline ! Thank you for reporting this issue.
That is weird, we will check that.

**Comment by alexandrebodin** [comment]
@samuelpetroline the populate syntax of strapi.query is a simple array:

`['professionalCategories', 'projects', 'projects. projectImages']`

Have you tried it ?

**Comment by lauriejim** [comment]
Done and works well @alexandrebodin !
I was thinking this format was just for SQL and for MongoDB it was the format that used @samuelpetroline .

**Comment by alexandrebodin** [comment]
> Done and works well @alexandrebodin !
> I was thinking this format was just for SQL and for MongoDB it was the format that used @samuelpetroline .

If you want to use a format specific to one of the unerlying ORM you can do it by using the model directly (not the query) :

```js
// get ORM model: mongoose for ex
const model = strapi.query(modelName).model;

return model.find().populte([{path: 'path' }])
```

**Comment by lauriejim** [comment]
Thank you for this precision.

**Comment by cenap** [comment]
> > Done and works well @alexandrebodin !
> > I was thinking this format was just for SQL and for MongoDB it was the format that used @samuelpetroline .
> 
> If you want to use a format specific to one of the unerlying ORM you can do it by using the model directly (not the query) :
> 
> ```js
> // get ORM model: mongoose for ex
> const model = strapi.query(modelName).model;
> 
> return model.find().populte([{path: 'path' }])
> ```
When I do that I am getting:
`MissingSchemaError: Schema hasn't been registered for model "level"`

**Comment by derrickmehaffy** [comment]
Hello @cenap !

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
