### ISSUE TITLE
Default deep filter not working GraphQL

### ISSUE THREAD

**Issue by trung-ung** [strapi/strapi#5001]
**Describe the bug**
I am developing a shift management app. Currently, there is only one new Content-Type which is like this:
![jobs](https://user-images.githubusercontent.com/55078059/72473142-bbc1b600-37ee-11ea-9b13-8f98acf496c3.png)

Important note: **Creator** is a one-to-one relationship with User and **Enrollers** is a one-to-many relationship with User

I make multiple instances for Users and Jobs

And here is the result if I get all jobs ##Request1
![3jobsintotal](https://user-images.githubusercontent.com/55078059/72475384-73f15d80-37f3-11ea-92b1-50037897b349.png)

And here is the result if I get all job which includes "trungemployee" in enrollers ##Request2
![trungemployeejobs](https://user-images.githubusercontent.com/55078059/72475691-1c9fbd00-37f4-11ea-92f5-0dd4ba07a682.png)
This should not be correct here as all Jobs Enrollers has the user with username trungemployee

Even funnier this is the result if I get all job which includes "trinhemployee" in enrollers ##Request3
![trinhemployeejob](https://user-images.githubusercontent.com/55078059/72475871-81f3ae00-37f4-11ea-9659-2af2aeb27546.png)
The only one result does not even have trinhemployee as the employee

Additionally, I tried the test with **enrollers id 1** ##Request4 
![enrolleridjob](https://user-images.githubusercontent.com/55078059/72476246-6c32b880-37f5-11ea-8183-40a4e25d6200.PNG)
This should show nothing as I dont have jobs with enrollers id equal to 1

One final test, I tried to test it with **enrollers id 4** ##Request5
![enrollerid4](https://user-images.githubusercontent.com/55078059/72476671-73a69180-37f6-11ea-9f11-4650ab47a0c4.PNG)
Is it referencing **job id** instead of **enrollers id** here?

Final note: all queries using **creator** in **where** with the above conditions result in expected behaviors. So I am not sure what is the case with **enrollers**.

**Steps to reproduce the behavior**
You can make the same Content-Type, and some instances to reproduce this issue.

**Expected behavior**
1/ Expect ##Request2 to response jobs with id 1, 2, 4 (right now none are responded)
2/ Expect ##Request3 to response jobs with id 1 and 2 (right now job id 4 is responded)
3/ Expect ##Request4 to response jobs with no jobs (right now job id 1 is responded)
3/ Expect ##Request5 to response jobs with id 1, 2(right now job id 4 is responded)

**Screenshots**
Provided above

**Code snippets**
Provided above

**System**
- Node.js version: v10.15.3
- NPM version:6.4.1
- Strapi version: "3.0.0-beta.18.4",
- Database: sqlite
- Operating system: Windows 10

**Additional context**

**Comment by trung-ung** [comment]
I tried again with mongodb setup and everything go as expected. Maybe this only happens to sqlite.

**Comment by derrickmehaffy** [comment]
This is indeed an issue with SQLite @trung-ung many of the filters don't work, or don't work as expected with SQLite. I would recommend you use one of the other databases.

@alexandrebodin this is what I was talking about last week, I get the feeling it's relating to the full-text indexes (or something to do with deep queries?)

**Comment by alexandrebodin** [comment]
have you tried `enrolles: 1` directly ?

**Comment by trung-ung** [comment]
@alexandrebodin here it is, nothing changes comparing to filter by ```emrollers id 1```
![enroller1](https://user-images.githubusercontent.com/55078059/73119370-8002bb00-3f69-11ea-922c-4aaaa4f36218.png)

**Comment by trung-ung** [comment]
Also, did does not only affect in graphql request, even REST request shows the same results
##Request2 
![request2](https://user-images.githubusercontent.com/55078059/73119407-1c2cc200-3f6a-11ea-9805-f53ce3e6186d.PNG)
##Request3
![request3](https://user-images.githubusercontent.com/55078059/73119410-218a0c80-3f6a-11ea-9bd7-0be79a118c6b.PNG)
##Request4
![request4](https://user-images.githubusercontent.com/55078059/73119413-26e75700-3f6a-11ea-8caa-a9853fdd63f4.PNG)
##Request5
![request5](https://user-images.githubusercontent.com/55078059/73119415-2c44a180-3f6a-11ea-82d2-4e8addb2b731.PNG)

All of the responses are the same as when done in Graphql

**Comment by alexandrebodin** [comment]
Can you please share your model.settings.json files so we can test locally ?

**Comment by nameszian** [comment]
The `where` it's not working properly.

<img width="949" alt="where_graphql" src="https://user-images.githubusercontent.com/23345155/73194209-1b438e00-412c-11ea-9420-1f5be57935ad.png">

Tested on Strapi beta.17. This query in theory it filters by status and user identifier (with status = created), but you can see that it also returns status empty.

**Comment by alexandrebodin** [comment]
@nameszian Your comment is not realted to this issue. I'm going to hide them to avoid a blur on the issue at hand here. Feel free to find a realted issue or open a new one with your usecase ;)

**Comment by alexandrebodin** [comment]
@trung-ung Can you please also share your queries in JSON ;)

**Comment by dayrlism10** [comment]
i think im facing the same issue in mysql too, wht i notice is that if deep filtering is penetrating into an array it wont work as expected, correct me if im wrong?

**Comment by Convly** [comment]
Hello @trung-ung, I failed at reproducing your issue on the current release. Could you try again on **v3.0.0-beta.19.4** and tell me if you still experience unexpected results?

Here are the results I got from your requests (_it returns the same results when queried over REST API_):

**Example 1**
![First example](https://user-images.githubusercontent.com/25851739/78043541-c44c7600-7373-11ea-9c5d-8b0bd45f8e9f.png)
**Example 2**
![Second example](https://user-images.githubusercontent.com/25851739/78043651-e645f880-7373-11ea-8546-bdede088a003.png)
**Example 3**
![Screenshot 2020-03-31 at 17 18 34](https://user-images.githubusercontent.com/25851739/78043690-f3fb7e00-7373-11ea-8706-c5857654cce3.png)
**Example 4**
![Fourth example](https://user-images.githubusercontent.com/25851739/78043072-2e185000-7373-11ea-9618-88dd1d378155.png)

**Comment by Convly** [comment]
Hi, I'm closing this issue as we haven't been able to reproduce with the latest version of Strapi. Feel free to comment if you end up getting this issue again!
