### ISSUE TITLE
Configuration and Content Manager missing in the Admin Panel UI

### ISSUE THREAD

**Issue by AgileWish** [strapi/strapi#5002]
Alpha had two links Configuration and Content  Manager, I  think the Beta is missing those two link.  those were useful features.  Not sure if this is intentional or not. 

Can that be installed from the outside?
Screenshot on this link that uses Beta 16.5 has these two links.  
https://strapi.io/documentation/3.0.0-beta.x/plugins/documentation.html#installation

**System**
- Node.js version: V10
- NPM version: 6.0
- Strapi version: 18.4
- Database: Postgres
- Operating system: Ubuntu

Installed all dependencies.  Package.json file.
{
  "name": "strapi-app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.0.0-beta.18.4",
    "strapi-admin": "3.0.0-beta.18.4",
    "strapi-utils": "3.0.0-beta.18.4",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.4",
    "strapi-plugin-content-manager": "3.0.0-beta.18.4",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.4",
    "strapi-plugin-email": "3.0.0-beta.18.4",
    "strapi-plugin-upload": "3.0.0-beta.18.4",
    "strapi-connector-bookshelf": "3.0.0-beta.18.4",
    "knex": "<0.20.0",
    "pg": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "3e4cc131-569f-4d31-8c44-beb95f978d65"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

**Comment by derrickmehaffy** [comment]
Settings manger was depreciated. And the CTM is in the process of being merged into the CTB (not going away, just being integrated into the rest of the UI)

Marking this as closed as it is intended.
