### ISSUE TITLE
File download in custom controller not working?

### ISSUE THREAD

**Issue by mondayrunner** [strapi/strapi#5003]
**Describe the bug**
I'm now using the Koa .set method to force a custom download in my custom end point. The problem is that only the plain text is showing in my browser of the VCALENDAR. 

**Steps to reproduce the behavior**
1. Generated custom API controller
2. Changed the route and create an end point
3. End point works
4. Added:

```javascript
ctx.set('Content-type: text/calendar; charset=utf-8');
ctx.set('Content-Disposition: inline; filename=calendar.ics');
```

**Expected behavior**
Force a download of the file.

**Code snippets**
Calendar.js looks like this:

```javascript
module.exports = {
  index: async (ctx, next) => {
      ctx.set('Content-type: text/calendar; charset=utf-8');
      ctx.set('Content-Disposition: inline; filename=calendar.ics');
      ctx.body = 'BEGIN:VCALENDAR PRODID:-//xyz Corp//NONSGML PDA Calendar Version 1.0//EN VERSION:2.0 BEGIN:VEVENT DTSTAMP:19960704T120000Z UID:uid1@example.com ORGANIZER:mailto:jsmith@example.com DTSTART:19960918T143000Z DTEND:19960920T220000Z STATUS:CONFIRMED CATEGORIES:CONFERENCE SUMMARY:Networld+Interop Conference DESCRIPTION:Networld+Interop Conference   and Exhibit\nAtlanta World Congress Center\n Atlanta\, Georgia END:VEVENT END:VCALENDAR';
  }
};
```

**System**
Node 12.14.0
NPM version: 6.13.4
Strapi version: 3.0.0-beta.18.4
Database: SQLITE
Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
I believe you need a `return ctx.body`

**Comment by mondayrunner** [comment]
Hi Derrick, thanks for the quick answer. Seems that I was a bit to quick (or frustrated :) to post and found the solution this morning:

```javascript
      ctx.type = 'text/calendar; charset=utf-8';
      ctx.set('Content-Disposition: attachment; filename=calendar.ics');
      ctx.body = 'VCALENDAR_CODE';      
```

You have to use ctx.type for setting the Content-Type header, .set is not working here. Also the attachment property is needed in the ctx.set!
(for more info see: https://github.com/koajs/koa/blob/master/docs/api/response.md)

Hope this mistake helps people in the future wanting to generate iCal files in Strapi.

Cheers!
Tim
