### ISSUE TITLE
Adding Support  for case sensitives fields in sql DBs

### ISSUE THREAD

**Issue by TusharManohar** [strapi/strapi#5004]
**Please describe your feature request:**
please add support for case sensitive fields in postgres, mysql

**Comment by derrickmehaffy** [comment]
@TusharManohar can you please use the entire template and also please provide more information as to what exactly you want to see. Are you looking more for a regex based field, in that you can apply a regex string to restrict exactly what you expect to have?

---

> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```
