### ISSUE TITLE
Dynamic Fields with apollo (graphql)

### ISSUE THREAD

**Issue by Thrajnor** [strapi/strapi#5008]
## **Describe the bug**
Apollo breaks when it tries to query strapi for a dynamic field with multiple types. This problem seems to occur only using apollo because in graphql sandbox everything works fine

### Strapi (Backend)
1. Go to Strapi admin panel with qraphql plugin instaled
2. Create a dynamic field with more than 1 component

### Nuxt.js (Frontend)
1. Send query using apollo to strapi for dynamic field
2. See errors about missing fields

## **Expected behavior**
Apollo gets an array of fields with multiple types from the dynamic field

## **Screenshots**
![Screenshot from 2020-01-16 16-28-29](https://user-images.githubusercontent.com/27703720/72539260-54077b80-387f-11ea-958a-37340e0332a6.png)
![Screenshot from 2020-01-16 16-46-12](https://user-images.githubusercontent.com/27703720/72539547-c0827a80-387f-11ea-9077-de4292f33b01.png)

### Strapi (Backend)
- Node.js version: v12.13.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.4
- Database: SQLite
- Operating system: Linux

### Nuxt.js (Frontend)
- "nuxt": "^2.9.2",
- "graphql": "^14.5.8",
- "graphql-tag": "^2.10.1",
- "@nuxtjs/apollo": "^4.0.0-rc18",

## **Additional context**
It seems to be more of apollo's bug than strapi's tho. All solutions I found revolves around adding apollo [`IntrospectionFragmentMatcher`](https://www.apollographql.com/docs/react/data/fragments/#fragments-on-unions-and-interfaces) to the backend but I have no idea how to correctly implement it in strapi. :(

This issue makes dynamic fields with graphql/apollo virtually unusable so I think it would be good if someone would look into it, and maybe made some tutorial or mention in docs how to set up dynamic fields correctly in strapi with qraphql :)

**Comment by theo-stocchetti** [comment]
I'm stuck on the same problem, i have find this article about this : https://medium.com/@jacky_ttt/day121-warning-heuristic-fragment-matching-going-on-8208b584cb5e

That explain how to generate fragments with the IntrospectionFragmentMatcher, the solution is explained with a new intance of ApolloClient but i don't understand how i can implement with getting the default apollo client.

```
// new appolo client
const client = new ApolloClient...

// vs getting the default client 
const client = this.app.apolloProvider.defaultClient
```

If you want test your components and advance in your project, you can use 'no cache policy' (not recommended) option in your query :

`const request = await client.query({ query, fetchPolicy: 'no-cache' })`

**Comment by stijnwesterhof** [comment]
@Thrajnor Are you still searching for a solution?

**Comment by pfritsch** [comment]
Same problem here

**Comment by ilackovic** [comment]
+1, same problem with NextJS, can't find a way to get dynamic fields to work

**Comment by alastair-todd** [comment]
Reverted to the fetch API for this one.

**Comment by derrickmehaffy** [comment]
As we have seen no update on this issue in a few months, going to market it as closed.

As the issue isn't related to Strapi directly but the tools used to fetch the data, please use our [Forum](https://forum.strapi.io/)

**Comment by zimkha** [comment]
Hi i wont to make a dynamic field in my type schema How I do it?
