### ISSUE TITLE
It's impossible to add a new required field.

### ISSUE THREAD

**Issue by Adam-Asatryan** [strapi/strapi#5012]
It's impossible to add a new required field.

Like, create a user model that has Firstname and Lastname add content and try to modify the model by adding new let's sat bio field and mark as required. Then try to modify existing content and add a bio. YOU CANT as it returns validation failed

![image](https://user-images.githubusercontent.com/57621125/72612500-64cef480-3946-11ea-8718-7ff71f4ca7e2.png)

**The idea is so good but implementation is awful an untrustable**

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by Adam-Asatryan** [comment]
this is not  a bug report just FYI, I no longer need strapi, you are not trustable

**Comment by lauriejim** [comment]
Hello! I would love to have more information to debug if necessary.
With the info you gave us, I can't reproduce and understand your issue.

**Comment by sarneeh** [comment]
> this is not a bug report just FYI, I no longer need strapi, you are not trustable

🤣
