### ISSUE TITLE
Unable to start strapi with MongoDb

### ISSUE THREAD

**Issue by RaghavAggiwal** [strapi/strapi#5016]
**Describe the bug**
Started a new strapi app with MongoDb but on runnnig strapi start, an error was thrown.

**Steps to reproduce the behavior**
1. strapi new project (with mongo running in background)
2. strapi start

**Expected behavior**
Server must start

**Screenshots**
![strapi1](https://user-images.githubusercontent.com/11409213/72655469-c5981480-39ba-11ea-8c09-fbe3a37e8bcc.PNG)
![strapi2](https://user-images.githubusercontent.com/11409213/72655470-c630ab00-39ba-11ea-9c6c-82b0e363e9a0.PNG)

**System**
- Node.js version: 12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDb 4.2.2
- Operating system: Windows 

**Additional context**
I don't have any password set on mongodb

**Comment by derrickmehaffy** [comment]
Alpha is no longer supported, please test using the beta.

Marking as closed due to unsupported version

**Comment by lauriejim** [comment]
@RaghavAggiwal you can use `npx create-strapi-app project` instead
