### ISSUE TITLE
Time fields shows wrong value on lists

### ISSUE THREAD

**Issue by wysher** [strapi/strapi#5019]
**Describe the bug**
- Time field shows value as Invalid Date on List view
- DateTime field shows only date on List view

**Steps to reproduce the behavior**
1. Create model that contains time and datetime fields
2. Add new entry with any values
3. Go back to list view

**Expected behavior**
Time fields shows time instead of trying to be parse as date.
DateTime fields shows date and time

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: beta 18.4
- Database: sqlite
- Operating system: Mac OS High Sierra

**Comment by derrickmehaffy** [comment]
@soupette

**Comment by soupette** [comment]
Do you have any screenshot? Because from my side it is displayed correctly.

![Screenshot 2020-01-20 at 10 39 20](https://user-images.githubusercontent.com/13311463/72715639-2406f380-3b71-11ea-90fd-e1ef770b2206.png)

**Comment by wysher** [comment]
@soupette 
![image](https://user-images.githubusercontent.com/16906868/72739706-7d3c4a80-3ba4-11ea-805d-5952a1061c90.png)

Maybe it's only sqlite thing...

**Comment by soupette** [comment]
I am also using sqlite, did you rebuild your front-end when upgrading your app?

**Comment by wysher** [comment]
Yep. I'm using fresh strapi install.

**Comment by wysher** [comment]
Also created_at and updated_at shows only date (without time)

**Comment by lauriejim** [comment]
Hello @wysher !
I just created a new app with `beta.18.5` all time formats from my Content-Type attributes work fine.
Here is what I did - https://www.loom.com/share/ed253642251941ea84fe8e00f1db19ab
And I confirm for the `created_at` and `updated_at` format @soupette

**Comment by wysher** [comment]
I confirm thath problem was solved. Thank you.
