### ISSUE TITLE
using "strapi-provider-upload-aws-s3" crashes strapi and prevents from connecting to production environment.

### ISSUE THREAD

**Issue by specsdhdeveloper** [strapi/strapi#5028]
When following the AWS Deployment tutorial, I get stuck on [step 7](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#_6-install-pm2-runtime)

when trying to access strapi on port 1337 at the url given by the EC2 console, I get a ERR_CONNECTION_REFUSED. looking at `pm2 list` after trying to connect, I see uptime value at a few seconds, which indicates me the app just crashed.

It seems the error is related to the `strapi-provider-upload-aws-s3` package. when reverting to the initial commit where this package was not yet added, i am able to access the backend and setup an admin user. However in the Files Upload plugin configuration, I am unable to set the provider to something other than "local server". 

- Node.js version: v10.18.1
- NPM version: 6.13.4   
- Strapi version: 3.0.0-beta.18.4
- Database: PostgreSQL
- Operating system: Ubuntu 18.04 LTS

Please help me host my files on S3 in my production environment. 
On localhost, in development environment, it seems fine and I am able to select the dropdown option "Amazon Web Service S3"
thanks :)

**Comment by lauriejim** [comment]
Hello! If you deploy your app without the AWS provider, does it work?

**Comment by specsdhdeveloper** [comment]
Hello @lauriejim  Yes, without the AWS provider it works. Where can I find/add logs to trace back the error?

**Comment by lauriejim** [comment]
Make sure PORTs are open for your PG database.

**Comment by specsdhdeveloper** [comment]
Hello, it seems the error is on the database side indeed, not with the strapi-provider-upload-aws-s3 plugin. I was actually using sqlite. switching to postgres in database.json and building yields the same `ERR_CONNECTION_REFUSED`

In the deployment tutorial it doesn't mention anything about the database connection ports. I added a security group in amazon RDS, with port 5432 open for connection

![image](https://user-images.githubusercontent.com/29488489/72888067-2aca6d80-3d0d-11ea-912e-e596c819abdf.png)

I am effectively able to connect to the pg database from a third-party pg-admin tool, but no tables to be found in there. So I'm still not sure why strapi wouldn't connect to the database.

I'll guess I'll try a local mySQL instead

**Comment by specsdhdeveloper** [comment]
Ok, got it. Somehow I had to put default database name 'postgres' in ecosystem.config.js
