### ISSUE TITLE
Homepage doesn't update after creating first content type

### ISSUE THREAD

**Issue by niallobrien** [strapi/strapi#503]
**Node.js version**: 8.9.0
**npm version**: 5.5.1
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Windows 7 (Enterprise)

After creating my first content type, the homepage still displays the below message.

![image](https://user-images.githubusercontent.com/1525669/35304968-7c01bf8a-008f-11e8-9a00-0c04ccf1b0c2.png)

**Comment by htamhue** [comment]
![image](https://user-images.githubusercontent.com/16870937/35314841-6121b2ee-00fb-11e8-80c9-3c538ab92f3a.png)
You can click **Posts** type

**Comment by niallobrien** [comment]
Specifically, the big blue button that says "Create your first content type", when technically, I already have.

**Comment by trustlee** [comment]
You might consider this a higher priority as virtually all first-time users run into it or a similar UI/process oddity when creating first content type.

**Comment by lauriejim** [comment]
Will be fixed in this PR https://github.com/strapi/strapi/pull/903
