### ISSUE TITLE
Where to post user made plugins until marketplace is complete

### ISSUE THREAD

**Issue by boazpoolman** [strapi/strapi#5032]
This was edited by @derrickmehaffy to make it a discussion topic relating to a temporary medium for user plugins until the marketplace is finished

---

- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Hi! I was wondering what would be the place for developers to share their contrib plugins? Is there a place where other Strapi users can find these, for their own usage?

**Your suggestions for this topic**

- An ecosystem place on the docs where we could do PRs to add user plugins
- A separate repo similar to the tutorials one where users can submit their plugins
- We could use the Github Wiki as that should be open for anyone to edit (will need to check)

**Comment by derrickmehaffy** [comment]
I will leave this open even though it doesn't follow the template guidelines.

For the moment there isn't really a good spot, wondering if a simple ecosystem spot on the docs would be enough until work starts on the marketplace.

@lauriejim

**Comment by lauriejim** [comment]
Hello! We don't have the marketplace open for now.
We can't work on it right not because of the lake of resources.
We are working on features and stability.

**Comment by derrickmehaffy** [comment]
@lauriejim Do you think having an ecosystem spot in the docs would be a good temporary place?

**Comment by lauriejim** [comment]
Having an awesome-strapi repo could be cool also ^^

**Comment by derrickmehaffy** [comment]
@pierreburgy @Aurelsicoko Thoughts on this? If we want to create an `awesome-strapi` repo I think it would be good.

**Comment by lauriejim** [comment]
Here it is, please submit a PR to this repo - https://github.com/strapi/awesome-strapi

**Comment by derrickmehaffy** [comment]
> Here it is, please submit a PR to this repo - https://github.com/strapi/awesome-strapi

A short note on this, that repo isn't currently public but it will be soon!
