### ISSUE TITLE
Content type creation fails silently in production mode

### ISSUE THREAD

**Issue by gottlike** [strapi/strapi#5038]
When Strapi is started with `strapi start` you can't create new content types in the admin panel, apparently (`strapi dev` works, however). When you try to create a content type in production mode anyway, Strapi will just fail silently on save.

**Expected behaviour**: An error message should pop up, saying that new content types cannot be created in production mode and `strapi dev` should be used instead. Or even better: Gray out everything that's not usable and display a notification.

**Comment by derrickmehaffy** [comment]
This is expected.

`strapi start` -> No auto-restart as this is generally used for production.
`strapi dev` -> Has auto-restart as this is for development use.

Strapi doesn't support creating content types in production as the model settings are saved in files. Node needs to restart to see changes in files. Any issue, bad change, or just in general restarting the API would cause downtime (even just a few seconds to restart). Users are expected to develop locally (`strapi dev`), push changes into a staging environment to test with (`NODE_ENV=staging strapi start`), then if everything is working well deploy into production (`NODE_ENV=production strapi start`)

I am closing this as it is intended. If you would like you can submit a PR to show an error message. Generally though environments are not changed simply with the command (start vs dev) but by the `NODE_ENV` variable. This is fairly common with all nodejs based projects.

**Comment by derrickmehaffy** [comment]
Due note that when you create a project there are many helpful explanations of what the command options are:

```
Your application was created at /Users/paulbocuse/Desktop/Projects/my-project.

Available commands in your project:

  yarn develop
  Start Strapi in watch mode.

  yarn start
  Start Strapi without watch mode.

  yarn build
  Build Strapi admin panel.

  yarn strapi
  Display all available commands.

You can start by doing:

  cd /Users/paulbocuse/Desktop/Projects/my-project
  yarn develop

Running your Strapi application.
```

https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start-tutorial.html#_1-install-strapi-and-create-a-project

**Comment by gottlike** [comment]
@derrickmehaffy Please read my description carefully.. it's about failing **silently**. I (now) know that this is intended, but surely you want to present users with a helpful error message in case they don't know about this (as I did in the beginning).

**Comment by gottlike** [comment]
After all, it kind of feels very broken if you use a feature and it doesn't do anything.. that's just bad UX/UI - regardless of "why" it fails.

**Comment by derrickmehaffy** [comment]
`If you would like you can submit a PR to show an error message.`

I understand your point but the documentation does state fairly clearly the differences between strapi start vs strapi dev

**Comment by gottlike** [comment]
I do understand your perspective too, but I have to disagree. If you are aiming for a product that "works according to specification", sure.. that's good enough. But if Strapi want's to become a _delightful_ and _polished_ product to use, these things must be addressed, imho. Closing the issue and saying that I can do it myself would be fine if it's something of very little value to the majority of users - but here I disagree.

So, last try: I'm pinging @Aurelsicoko, because this is kind of a DX/UX issue. If he as a PO agrees that it's fine like that, then that's how things are, I guess.

**Comment by derrickmehaffy** [comment]
Agreed, I'll let the Strapi team decide to reopen. The other reason I closed the issue was due to lack of a proper template.

**Comment by lauriejim** [comment]
Hi! Thank you for reporting this.

@Aurelsicoko I think it could be cool to manage this specific thing.
Many people from the community are starting there app with `strapi start` and don't understand what happen.
The interface allows them to create / update Content Type but there is no error or warning message.

**Comment by soupette** [comment]
@lauriejim you are right. I will make a PR so a notification is displayed when the user is in the `development` environment and doesn't have the `autoReload` feature enabled. I will also remove the call to actions like in production mode.

**Comment by bastianhilton** [comment]
why can't you create content types in production, to me it seems like an almost unusable headless cms if you can create anything in production

**Comment by derrickmehaffy** [comment]
This is intended @bastianhilton https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

Creating content-types in production is the same as "testing in production" which is not a good policy, and to be able to do it you would need to store the model information in the database which makes source control practically impossible.
