### ISSUE TITLE
REST routes with plural resource names 

### ISSUE THREAD

**Issue by niallobrien** [strapi/strapi#504]
Node.js version: 8.9.0
npm version: 5.5.1
Strapi version: 3.0.0-alpha.8.3
Operating system: Windows 7 (Enterprise)

Hi, if my understanding of REST is correct (and based on how other frameworks have implemented it eg. Laravel, Rails etc.)
Shouldn't all REST methods operate on a plural form of the resource? For example, you'd GET all posts via `/posts` and not `/post` and DELETE a specific post via `/posts/:id` etc.?

![image](https://user-images.githubusercontent.com/1525669/35305378-032d0590-0091-11e8-91f9-6e39cef9ebb3.png)

Thanks.

**Comment by Aurelsicoko** [comment]
I totally agree! Thank you for raising this feature request @niallobrien 👍

**Comment by gonzochic** [comment]
To be honest, this is a breaking change for Strapi (isn't it?). At least it might be smart to version the API. For me it is breaking the ecosystem that i have built to work with Strapi + other things in your ecosystem (see https://github.com/strapi/gatsby-source-strapi/pull/26)

**Comment by derrickmehaffy** [comment]
It is and was warned about :p. As this is alpha you should assume every change is a breaking one.

**Comment by lauriejim** [comment]
It was wrote in the migration / change log

**Comment by gonzochic** [comment]
@derrickmehaffy i have to admin, you are right. It is an alpha version and therefore the API can/will break.
