### ISSUE TITLE
Customize repeatable field title

### ISSUE THREAD

**Issue by kapik** [strapi/strapi#5044]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Hi !! 👋 

The title of each repeatable content must be customizable.
On my screenshot, I have created a repeatable component `Testrepeat` with a relationship `Test` as a field.
As you can see, the title is `4`.

I think this is the ID/index of the `Testrepeat` field (this is the fourth field created globally).

Maybe we could choose which field to display?
- any field of the repeated group
- any field of a relationship field

In my example, I would like to display `Test 1` instead of `4`.

![2020-01-21_22-25-17](https://user-images.githubusercontent.com/511247/72845367-bfe24d80-3c9e-11ea-90a8-5b8d1ab2796a.png)

In this kind of situation, when the fields are collapsed, it is difficult to find the right content.

What do you think about that ?
Thx 😃

**Comment by soupette** [comment]
You can easily change this setting using the administration panel to do so you need to:

- Click on the content type in the left menu
- Click on the `Add new <contentType>` button
- In the editview you will see a link on the right side (`Configure the view`) click on this button
- In the layout reorder click on the link `Set the component's layout` so you can access its settings view
- from there you will see a select input `Entry title`
- choose the desired field you want to display
- save

**Comment by kapik** [comment]
we can not do this.
The only field available is `id` ! 
I think this is related to https://portal.productboard.com/strapi/1-public-roadmap/c/49-display-relational-field-in-list-view ¯\_(ツ)_/¯

**Comment by lauriejim** [comment]
Can you try w/ the last version of strapi (beta.18.6)
I just tried and I can select the select value as `Entry title`

**Comment by kapik** [comment]
The update did not change anything

**Comment by bilobrkk** [comment]
In the repeatable component, you need to create a unique and required field, then you will have the option to choose a title as Entry title. :)
<img width="620" alt="image" src="https://user-images.githubusercontent.com/32678214/189959738-a9120bbe-05ee-49d9-a5cd-3a112951c76b.png">

**Comment by untimated** [comment]
thank you for the insights, now i know how the label itself can be configured.

however, i still have a problem with custom field inside a repeatable component. It didn't show in the list of field of entry (only shorttext type does). 

unfortunately my custom field must store value in string text (to store json) and no where it can make it to the entry

**Comment by CoderIllusionist** [comment]
> Thank you guys, now i know how the label itself can be configured.
> 
> However, i still have a problem with custom field inside a repeatable component. It didn't show in the list of field of entry (only shorttext type does).
> 
> ...and unfortunately my custom field **must store value in string text** (to store json) and no where it can make it to the entry
> 
> ![image](https://user-images.githubusercontent.com/7563893/255329922-6a174ada-cb4f-4aa0-acc8-7b17f6f9bbf3.png)

@untimated did you find a solution for this ?
