### ISSUE TITLE
Creating a new field with the same name as the earlier deleted field doesn't update the data type in the database

### ISSUE THREAD

**Issue by jiv-e** [strapi/strapi#5045]
**Describe the bug**
~~Big integer field values have zero decimal in the default database (SQLite), eg. 12454623.0~~
Creating a new field with the same name as the earlier deleted field doesn't update the data type in the database.

**Steps to reproduce the behavior**
1. Setup Strapi instance with the default database (SQLite).
2. Create a new content type.
3. Add a short text field named 'Foo' to the content type. Save the content type.
4. Delete the text field created in step 2. Save the content type.
5. Create a new big integer field named 'Foo' to the Content type. Save the content type.
6. Now the UI shows that the field type is Number.
7. Check the database and see that the actual type in the database is varchar(225). This causes the problem I opened this issue with. See 'Describe the bug' section.

**Expected behavior**
Options:
1. Deleting the field will delete it from the database. (Add a warning?)
2. Creating a field clashing with the existing database column will cause an error.
3. Creating a field clashing with the existing database column will cause a warning that the previous data will be overridden and the column type is changed. User can select to proceed or cancel.

**System**
- Node.js version: v12.14.1
- NPM version: 6.13.6
- Strapi version: 3.0.0-beta.18.3
- Database: SQLite
- Operating system: MacOS

**Comment by jiv-e** [comment]
Oh... it seems this is an SQLite problem. Can somebody confirm this only happens on SQLite?

https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite

Could there still be a warning or something when using SQLite?

**Comment by derrickmehaffy** [comment]
@jiv-e Strapi doesn't update the column in the database yet, you need to do the migration manually (likewise for renaming fields/models)

**Comment by lauriejim** [comment]
This issue is related to this one https://github.com/strapi/strapi/issues/1114

**Comment by lauriejim** [comment]
Closing because related to the issue I linked in my last message.
