### ISSUE TITLE
Can't change request limit record for admin panel request Content-Types

### ISSUE THREAD

**Issue by apodaka** [strapi/strapi#5049]
**Describe the bug**
While i was adding data to my content (Entertainment Events), i noticed that the relationa data only retrieve a limit of 20 records (tryed to set the city of the event), that means that i will not be able to add a record with a city that is in position 21 of the index and more, using strapi admin pannel because i can't change the limit feature (Maybe i don't know how to do it). There is a way that it could be possible change limit to admin pannel requests?

**Steps to reproduce the behavior**
1. SignIn to Admin Panel
2. Create a City content type with the name attribute 
3. Create a State content type with name attribute and a relation (State have cities) (optional)
4. Add 21 entries or more to city content type. (20 citys prefixed with a number for better understand) example: 

1:santa ana
2:disneyland
3:morestuff
...

5. Cretae a Events content type and a relation with cities.
6. Create an entrie for an Event using the admin pannel and try to select one of the citys that are in 21th position of the dropdown

**Expected behavior**
You can't select a record that is in position 21 of the index or more

**Screenshots**
![4e5385b7-c64b-43fb-88bd-806eb9511cc6-strapi-issue1](https://user-images.githubusercontent.com/18412209/72883280-43149b00-3cc1-11ea-92f2-109f74f6082c.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.18
- Database: Mongodb 4.0
- Operating system: Windows 10 using powershell

**Comment by derrickmehaffy** [comment]
@apodaka as you scroll it will load more records in the dropdown

**Comment by apodaka** [comment]
> @apodaka as you scroll it will load more records in the dropdown

Tryed to but i can't load more. For some extra details, i started strapi in dev mode with 
> yarn develop

And in my server.js the host is a local ip

> 192.168.0.4

**Comment by derrickmehaffy** [comment]
@apodaka can you jump on the Strapi slack?

**Comment by apodaka** [comment]
cant do right now, but look i found the core of my problem. Yes, autoscroll works well, but if i try to search "Culiacán" in the search field, it is not founded, because was not loaded at the first 20, They were added as the States were added: First state and then the citys of the state (**they are not sorted**). So *Culiacán* is in state *Sinaloa*, and have to scroll down and load the data first for use the search field, that have no sense. 

Tanks for your help!

**Comment by LucasMatuszewski** [comment]
Hi, I have the same problem. We have a model with all Countries data (248 records).
On Relation Select I see only first 20 items. When I scroll to the end it loads only one new record. When I try to scroll again it load one more again...
Search doesn't work neither.

Is it a bug or desired behavior? Quite strange I would say ;)
Can I change this limit in some simple way ? Some customization?

Logs from CLI:
```
[2020-04-15T19:01:16.477Z] debug GET /content-manager/explorer/application::address-countries.address-countries?_limit=20&_start=1 (90 ms) 200
[2020-04-15T19:01:18.017Z] debug GET /content-manager/explorer/application::address-countries.address-countries?_limit=20&_start=2 (73 ms) 200
[2020-04-15T19:01:19.190Z] debug GET /content-manager/explorer/application::address-countries.address-countries?_limit=20&_start=3 (109 ms) 200
[2020-04-15T19:01:20.726Z] debug GET /content-manager/explorer/application::address-countries.address-countries?_limit=20&_start=4 (79 ms) 200
```

Error on search in Select field:
```
[2020-04-15T19:01:04.456Z] error Error: ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list
    at Query.Sequence._packetToError (D:\Dev\Projects\Edukey_Next_Strapi\strapi\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
```

**Comment by lauriejim** [comment]
Hello! What is the version of Strapi you are using?

**Comment by LucasMatuszewski** [comment]
> Hello! What is the version of Strapi you are using?

Sorry @lauriejim - I should upgrade before asking... On Beta.20 it works fine, thanks! :)
