### ISSUE TITLE
Browser autofill the username and password

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#5053]
**Describe the bug**

The browser autofill the username and password when create a new user:

<img width="925" alt="Screenshot 2020-01-22 at 11 59 45" src="https://user-images.githubusercontent.com/1007051/72888972-f788de00-3d0e-11ea-9218-37729e6f0c2a.png">

**Steps to reproduce the behavior**
1. Go to Users content type
2. Click on Add new User
3. The browser autofill the username and password ⚠️ 

**Expected behavior**

The browser not autofill the username and password.

**System**
- Node.js version: v12
- NPM version: v6
- Strapi version: v3.0.0-beta.18.5
- Database: MongoDB
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
I can confirm this issue.
