### ISSUE TITLE
Date fields are making the form unusable

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#5054]
**Describe the bug**
When I have multiple `datetime` fields on my content-type, the creation form is completely unusable (the input fields have a massive lag).

**Steps to reproduce the behavior**
1. Create a component with a `datetime` field
2. Create a content-type with a `string` field and a repeatable component field from step 1
3. Go to the add form, add ~10 of the repeatable date fields and try to type anything into the text field

**Expected behavior**
The date fields do not break form performance

**Screenshots**
![2020-01-22 14 11 05](https://user-images.githubusercontent.com/11553624/72896924-17c19880-3d21-11ea-86e5-2d5bcb7a82df.gif)

**System**
- Node.js version: 12
- NPM version: 6
- Strapi version: beta.18.5
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
I can confirm this issue, as @sarneeh instructions state you will need a repeat comp with a date, datetime, or time field attached to a mode.

When you create the entry, try to create quite a few of the repeat entries then try typing in the text (string) box.

![image](https://user-images.githubusercontent.com/8593673/72979867-78d78380-3d96-11ea-98f8-e5d9ae9259b9.png)

You should notice a very significant lag of the input.

@soupette @virginieky

**Comment by derrickmehaffy** [comment]
Created a test project for this: https://github.com/derrickmehaffy/datetime-entry-lag

**Comment by sarneeh** [comment]
Hey @soupette are you planning to release it today? 😃
