### ISSUE TITLE
Deleting one entry with dynamic zone affects all other entries

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#5056]
**Describe the bug**
Deleting a content-type which has a dynamic zone, deletes all dynamic-zone components from other entries.

**Steps to reproduce the behavior**
1. Create a component with a `string` field
2. Create a content type with Dynamic Zone, with component from step 1
3. Create a new entry, add a component via dynamic zone and fill the string field
4. Repeat step 3
5. Delete one of the entries
6. The another (and all other) entries will have cleared-out values in their dynamic zone components

**Expected behavior**
Deleting a single entry should not affect all other entries.

**Video**
![Kapture 2020-01-22 at 16 44 16](https://user-images.githubusercontent.com/11553624/72908940-86f5b780-3d36-11ea-9f5a-af430463f65f.gif)

**System**
- Node.js version: 12
- NPM version: 6
- Strapi version: beta.18.5
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment]
@alexandrebodin

**Comment by derrickmehaffy** [comment]
I did not @alexandrebodin I was working on a few other things. Nice job on the quick PR though.

**Comment by sarneeh** [comment]
Wow, that was fast! Where can I buy you a beer @alexandrebodin? 😄
Btw. when are you planning to release a new version?

**Comment by alexandrebodin** [comment]
@sarneeh Because it is a critical bug will be releasing tomorrow :)

**Comment by sarneeh** [comment]
Awesome! Thank you 😄
