### ISSUE TITLE
Error: bind EACCES null:1337

### ISSUE THREAD

**Issue by whwnow** [strapi/strapi#5057]
**Describe the bug**
After executing the command  `npm run develop`， an error is displayed 

```
[2020-01-22T15:25:07.637Z] error Error: bind EACCES null:1337
    at listenOnMasterHandle (net.js:1326:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:43:8)
    at process.emit (events.js:198:15)
    at emit (internal/child_process.js:848:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```
And I have checked that port 1337 is not occupied

**Steps to reproduce the behavior**
1. `npx create-strapi-app my-project --quickstart`
2. `npm run develop`

**Expected behavior**

**System**
- Node.js version:  12.13.0
- NPM version:  6.12.0
- Strapi version:  3.0.0-beta.18.5
- Database: SqlLite
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! Do you have a port restriction in your machine?

**Comment by whwnow** [comment]
I have reset my firewall and the problem persists. Why the error message is `null:1337`, not `localhost:1337`

**Comment by derrickmehaffy** [comment]
@whwnow can you provide your `config/environments/*/server.json` please?

**Comment by whwnow** [comment]
`config/environments/development/server.json`
```
{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
```
This is the config. I have not modified the default configuration

**Comment by derrickmehaffy** [comment]
🤔 This is quite odd I am not able to reproduce this.

**Comment by panoti** [comment]
I have the same problem

```shell
[2020-02-07T04:37:10.097Z] error Error: bind EACCES null:1337
    at listenOnMasterHandle (net.js:1365:16)
    at rr (internal/cluster/child.js:129:12)
    at Worker.<anonymous> (internal/cluster/child.js:96:7)
    at process.onInternalMessage (internal/cluster/utils.js:43:8)
    at process.emit (events.js:214:15)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by lauriejim** [comment]
Did you have another app that uses this port?

**Comment by panoti** [comment]
@lauriejim I check my open port on my window by command `netstat -an | find /i "listening"`

Results:

```
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:1024           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:2063           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:2179           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5040           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49668          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49669          0.0.0.0:0              LISTENING
  TCP    10.0.75.1:139          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1845         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:1851         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:2111         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:2375         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5354         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:7173         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:15292        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:15393        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:18171        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:23401        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:45623        0.0.0.0:0              LISTENING
  TCP    192.168.19.113:139     0.0.0.0:0              LISTENING
  TCP    192.168.31.133:139     0.0.0.0:0              LISTENING
  TCP    [::]:135               [::]:0                 LISTENING
  TCP    [::]:445               [::]:0                 LISTENING
  TCP    [::]:1024              [::]:0                 LISTENING
  TCP    [::]:2179              [::]:0                 LISTENING
  TCP    [::]:7680              [::]:0                 LISTENING
  TCP    [::]:49664             [::]:0                 LISTENING
  TCP    [::]:49665             [::]:0                 LISTENING
  TCP    [::]:49666             [::]:0                 LISTENING
  TCP    [::]:49667             [::]:0                 LISTENING
  TCP    [::]:49668             [::]:0                 LISTENING
  TCP    [::]:49669             [::]:0                 LISTENING
```
There is no any apps opening 1337 port. I think Windows 10 restrict `1337` port.

**Comment by lorduakiti** [comment]
I have the same problem for port 3001 using the custom configuration. 

server.json
```
{
  "host": "localhost",
  "port": 3001,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": true
  }
}
```

**Comment by derrickmehaffy** [comment]
If you guys are on linux/mac please run a `netstat -plnt` in the terminal and provide the response

**Comment by derrickmehaffy** [comment]
As I have seen no updates to this and we are currently unable to reproduce I'm going to mark this as closed, should you still have issues please provide any guidance on reproducing this issue.

**Comment by w3bdesign** [comment]
I had this problem as well today.

I had to change the port number in config\environments\development\server.json to get it to work.

**Comment by Huskydog9988** [comment]
same as w3bdesign

**Comment by arbolitoloco** [comment]
Had same problem running quickstart project installation, followed what [w3bdesign](https://github.com/w3bdesign) did but in `config/server.js`

**Comment by bastianhilton** [comment]
For those that comes across this in the future, i had the same issue as well:
`strapi develop
[2020-06-14T03:21:05.005Z] error Error: bind EACCES 0.0.0.0:1337
    at listenOnMasterHandle (net.js:1365:16)
    at rr (internal/cluster/child.js:129:12)
    at Worker.<anonymous> (internal/cluster/child.js:96:7)
    at process.onInternalMessage (internal/cluster/utils.js:43:8)
    at process.emit (events.js:214:15)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)`

But i went into my Strapi directory and then went to Config folder, inside is the server.js and changed my file:

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
});

to:

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 8082),
});

and it works. Weird however that port 1337 wasn't taken by anything else on my system, so this is a workaround but not a solution to whatever is the underlining problem.

**Comment by praveenangyan** [comment]
I'm running WSL on Windows and I had the same error. I had to change the port to 3001 in order to get it to run.

**Comment by philliprognerud** [comment]
I changed my port from 1337 to 8080. Works fine now. Not sure if this is a Strapi issue, rather specific systems have something using 1337 port already. Maybe the default port should be something else? Unless 1337 has a practical use, which I'm assuming not.

**Comment by derrickmehaffy** [comment]
> I changed my port from 1337 to 8080. Works fine now. Not sure if this is a Strapi issue, rather specific systems have something using 1337 port already. Maybe the default port should be something else? Unless 1337 has a practical use, which I'm assuming not.

It would be quite the task to update all of our docs, generally the issue is windows only or you have something else running on that port.

**Comment by awoerz** [comment]
> > I changed my port from 1337 to 8080. Works fine now. Not sure if this is a Strapi issue, rather specific systems have something using 1337 port already. Maybe the default port should be something else? Unless 1337 has a practical use, which I'm assuming not.
> 
> It would be quite the task to update all of our docs, generally the issue is windows only or you have something else running on that port.

Yeah but the issues is still showing closed but it is still occurring on Windows. I love Strapi so far, but I really hate that the port doesn't work out of the box for most users and there hasn't been a real solution, just a work around.

**Comment by derrickmehaffy** [comment]
@awoerz it's only a workaround for a user environment issue. I have tested this on 7 different windows environments, one of which being my personal windows computer and the rest being virtual machines hosted in various environments (including my own lab infrastructure on XCP-NG).

In all my testing, I am unable to reproduce the issue and the default port `1337` works fine.

![image](https://user-images.githubusercontent.com/8593673/109347854-00f94980-7831-11eb-8e51-45cb68baa063.png)

**Comment by james-w-arnold** [comment]
Hey, so just tried setting up the quickstart project on my Win10 PC.
Encountered the same issue.
I chucked this command into Powershell:
`Get-Process -Id (Get-NetTCPConnection -LocalPort 1337).OwningProcess`
And this revealed the culprit process to be RzSDKServer. 

This process is run as part of the Razer Chroma tools, which many people will have installed if they're using any Razer peripherals, and install any of the drivers that Razer recommends.
This could probably explain how some people are having this issue on Windows machines.

I'll get around this by just changing the port in the server config, but thought this might be a useful disclaimer for you to add somewhere if this issue is impacting enough people.

**Comment by awoerz** [comment]
@james-w-arnold @derrickmehaffy 

I used the powershell command that James recommended and that is my problem. I currently use three Razer peripherals so I bet this is definitely the reason for the issue for most users on Windows. I am looking for a way to maybe specify a port but haven't found one yet. In the meantime, it looks like the only fix is to change the server while developing locally.

**Comment by derrickmehaffy** [comment]
@awoerz might be good to review our documentation around that but I believe you should be able to pass in a `PORT` environment variable from the get-go (even while creating) to temporarily change the port.

The alternative is to create the project using the `--no-run` flag which won't immediately start the Strapi server and allow you to set the config, use environment variables, or set a `.env` file.

**Comment by derrickmehaffy** [comment]
I'm going to lock this thread as it has been confirmed that this isn't a Strapi issue, but a user environment issue. Further discussion on this should move to our forum: https://forum.strapi.io

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/develop-command-failed-error-error-bind-eacces-0-0-0-0-1337/3902/4
