### ISSUE TITLE
Loading spinner rewuired while saving datas in content type

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#5059]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Created a contenttype with 3 components.When adding data it's takes 10secs to save and getting back to listing screen.During this time user will be tempted to click n number of times thereby creating duplicate entries 

**Your suggestions for this topic**
Loading spinner can be shown still the data is getting saved.,This conveys the message that data is getting saved

**Screenshots**
If applicable, add screenshots to help explain your points.

**Code snippets**
If applicable, add code samples to help explain your points.

**Additional context**
Also can we give some success message saying "Data Saved Successful "

**Comment by lauriejim** [comment]
Hello! Can you please use an issue template.
I close this issue, I will re-open it when the format will be correct.
