### ISSUE TITLE
3.0.0-alpha.7.2

### ISSUE THREAD

**Issue by htamhue** [strapi/strapi#506]
**Node.js version**: >7
**npm version**: >3
**Strapi version**: 3.0.0-alpha.7.2
**Operating system**: window

Hello everyone!
How to config textarea as WYSIWYG field type?
![image](https://user-images.githubusercontent.com/16870937/35314730-b307e412-00fa-11e8-8258-d928ce580c22.png)

**Comment by Aurelsicoko** [comment]
It's on the roadmap! [Please vote on the dedicated page](https://strapi.io/vote) to prioritize the development of this feature.
