### ISSUE TITLE
Allow change user email as non required field

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#5061]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Allow change user email as non required field.

**Comment by lauriejim** [comment]
Hello @abdonrd , can you please share a use case.

**Comment by abdonrd** [comment]
Right now, we have an application where the users do not have email.

**Comment by lauriejim** [comment]
Okay and you want this feature available from the admin panel.

The workaround is to customize the `extensions/users-permissions/models/User.settings.json` and to set the required value of email to false.
Then to customize the register function and remove the email validation.

**Comment by derrickmehaffy** [comment]
Marking as closed as this is a niche use-case that will always require customization as we need to have one main required field for the user. Most of the code-base uses email (including the admin panel, where the username is not required).

In the case of 3rd party auth, email is almost exclusively unique and usernames are not.

**Comment by jnuno98** [comment]
Why don't you just make the User table fully customizable? I really don't understand why it is completely locked
I am doing an application where i really don't even want an User table with this format and it is a bit annoying that it can't be easily changed

**Comment by shestakov-vladyslav** [comment]
I do support last comment

**Comment by SzczurekYT** [comment]
I also. I'm making an app, and I don't need an email. It would be a lot easier for me If I could just remove all the email stuff.

**Comment by asadul44** [comment]
> 

After change as you mention, in strapi version 4.1.12  when create user show again error the email required

**Comment by ventsislavnikolov** [comment]
Did anyone find a solution in Strapi 4 to set username not required?

**Comment by MrTheFirst** [comment]
In my application, I create users via telegram by phone number, the user's email also interferes.

**Comment by creazy231** [comment]
> Does anyone have a solution for this problem in 2023?
> 
> Only changing the schema.json on "src/extensions/users-permissions/content-types/user/schema.json" doesn't work anymore
> 
> I tried to change to `"required": false` or `"unique": false,`, but the admin interface seems to change but the validation still occours

have you tried running `yarn build` / `npm run build` after you've changed the `schema.json`?

**Comment by derrickmehaffy** [comment]
Build doesn't do anything for the backend, all it does is build the admin panel.

**Comment by derrickmehaffy** [comment]
Currently it isn't really possible to completely disable it as it's basically hard coded into the plugin to require it but we are working on plans to build an entirely new plugin that will replace the current one.

**Comment by SzczurekYT** [comment]
Yeah. The issue with is that so need a required, unique filed, and currently it is the email field. I think that in the new version strapi should allow editing the User table, and just required the admin to set a field which will be used to identify a user. As you saw in the comments it doesn't need to be an email and possibilities are endless, it could ba a phone number, some id, unique tag etc.

**Comment by ArthurPedroti** [comment]
If I can set the email to not be unique, I can make a workaround and put some admin email in always account, but even that I can't do, and it's complicated if you are doing some other use cases and your users don't have emails.

I think if we can choose to email not be unique, we can make a workaround and don't need to do a big modification on the plugin, because email will continue to be required.

**Comment by infomus** [comment]
It's 2024 and this is still a very much needed customization. I don't agree that it's niche - there are many applications I can think of that do not and should not require an email to use

**Comment by infomus** [comment]
I found a workaround if anyone is interested:

Change `configurable` to false and `required` to true in `server/src/extensions/users-permissions/content-types/user/schema.json` and then go into the admin portal and delete the email field. Allow the server to restart, then re-add the email field but keep "Unique field" unchecked.

**Comment by imHowie** [comment]
> I found a workaround if anyone is interested:如果有人感兴趣，我找到了一个解决方法：
> 
> Change `configurable` to false and `required` to true in `server/src/extensions/users-permissions/content-types/user/schema.json` and then go into the admin portal and delete the email field. Allow the server to restart, then re-add the email field but keep "Unique field" unchecked.更改 `configurable` 为 false 和 `required` true in `server/src/extensions/users-permissions/content-types/user/schema.json` ，然后进入管理门户并删除电子邮件字段。允许服务器重新启动，然后重新添加电子邮件字段，但保持“唯一字段”未选中。

此方法不管用了，我的Strapi版本是4.14.4
