### ISSUE TITLE
Relations to be saved in same collection for nosql dbs like mongo

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#5065]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Contenttype - Article is having multiple relation with channel and categories and media. So the data is split across four collections. As data grows GET request takes almost 10 seconds to list in the listing screen and 5 seconds for loading in edit screen.Is it possible to store all the data in single collection  (Article) without reference

**Comment by lauriejim** [comment]
Same as the other issue, can you please follow the bug issue template.
Thank you.
