### ISSUE TITLE
Strapi console to be available in already-running Strapi instance

### ISSUE THREAD

**Issue by cadavre** [strapi/strapi#5066]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

The request is fairly simple. Strapi console is a powerful tool to be used along with already-running instance of Strapi. I.e. to load configuration fixtures on project initialization etc.

The only problem is when we start `strapi console` on already-running instance with Strapi – console wants to bind already used http listener port.

**Request:**

Strapi console shall not bind http listener at all.

**Comment by lauriejim** [comment]
Hello! Thank you for this message.
I ping @alexandrebodin about this topic.

**Comment by alexandrebodin** [comment]
Hi @cadavre strapi console is merely a running instance of strapi with a repl so you can access the strapi instance.

The thing we would like to have is a better CLI. 

Being able to connect to a running instance is not something we are planning on implementing for the time being.

You could however create a script like:

```js
cosnt strapi = require('strapi');

const app = strapi();

app.load()
.then(() => {
  // strapi is initialized but not started
  // you can init a repl here if you like
})
```

**Comment by cadavre** [comment]
`app.load().then()` is actually pretty good. Why not use it in `strapi console` in the first place? :)
