### ISSUE TITLE
Use transaction or lock database connection on database schema init

### ISSUE THREAD

**Issue by cadavre** [strapi/strapi#5067]
**Describe the bug**
Due to no transactional synchronous SQL calls API initialization warns or fails for multiple reasons:

1. `ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"` (warn)
2. `ERROR: Impossible to register the '...' model.` (fail)

**Steps to reproduce the behavior**
1. Create any simple API.
2. Commit API to store models.
3. Try `strapi start` on fresh instance.

**Expected behavior**
Strapi starts a new instance with all model created and no bugs/errors on initialization.

**Logs**

Ad 1)
```
postgres_1 | ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
postgres_1 | DETAIL:  Key (extname)=(pg_trgm) already exists.
postgres_1 | STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
api_1      | warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
postgres_1 | ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
postgres_1 | DETAIL:  Key (extname)=(pg_trgm) already exists.
postgres_1 | STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
api_1      | warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
postgres_1 | ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
postgres_1 | DETAIL:  Key (extname)=(pg_trgm) already exists.
postgres_1 | STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
api_1      | warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
postgres_1 | ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
postgres_1 | DETAIL:  Key (extname)=(pg_trgm) already exists.
postgres_1 | STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
api_1      | warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
postgres_1 | ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
postgres_1 | DETAIL:  Key (extname)=(pg_trgm) already exists.
postgres_1 | STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
api_1      | warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
```

Ad 2)
```
error: Impossible to register the '...' model.
error: relation "core_store" does not exist
    at Connection.parseE (/srv/app/node_modules/pg/lib/connection.js:606:11)
    at Connection.parseMessage (/srv/app/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/srv/app/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
error Command failed with exit code 1.
```

**System**
- Node.js version: 12.13.0
- Strapi version: any, including 3.0.0-beta.18.6
- Database: postgres
- Operating system: irrelevant (but it's debian:stretch)

**Additional context**
Both error are happening because of asynchronous SQL init calls.

```
CREATE EXTENSION IF NOT EXISTS pg_trgm
duplicate key value violates unique constraint "pg_extension_name_index"
```
Happens because of multiple queries that want to accomplish creation of an extension. While first success query creates this extension – other fails with "duplicate key".

```
error: Impossible to register the '...' model.
error: relation "core_store" does not exist
```
Happens less often, but is also the same case – `core_storage` is created asynchronously which causes dependent queries to fail if the table is not yet created. To fix this you just need to re-run Strapi – table `core_storage` will then be existing and other queries will succeed.

**Comment by derrickmehaffy** [comment]
@cadavre would you be willing to submit a PR to address this? I know @alexandrebodin had started adding transactions in a few places.

**Comment by alexandrebodin** [comment]
@cadavre can you share your pg version ??

The db migration needs to be revised. The transcations are only on table generation not the extensions and full text search yet sadly

**Comment by cadavre** [comment]
It's PostgreSQL 12.1. Could you point me to a file where this DB init happens in Strapi? Sorry I'm not even a JS developers, so it might be quite hard to help.

**Comment by alexandrebodin** [comment]
@cadavre We are planning to fix all of this in the next 2 months so don't worry :)

If you want to have a look, check the strapi-connector-bookshelf pacakge. File: `buildDatabaseSchema.js`

**Comment by sven-verkstedt** [comment]
> @cadavre We are planning to fix all of this in the next 2 months so don't worry :)
> 

Hit these errors on initial setup when using docker-compose with volumes:

```
[...]
  api:
    image: strapi/strapi
    volumes:
      - type: volume
        source: strapi-app
        target: /srv/app
[...]
  db:
    image: postgres
    volumes:
      - type: volume
        source: strapi-db
        target: /var/lib/postgresql/data

volumes:
  strapi-app:
  strapi-db:
[...]
```

```
api_1  | You can start by doing:
api_1  | 
api_1  |   cd /srv/app
api_1  |   yarn develop
api_1  | 
api_1  | Starting your app...
api_1  | Building your admin UI with development configuration ...
api_1  | ℹ Compiling Webpack
api_1  | ✔ Webpack: Compiled successfully in 22.69s
db_1   | 2020-03-16 15:48:24.503 UTC [78] ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
db_1   | 2020-03-16 15:48:24.503 UTC [78] DETAIL:  Key (extname)=(pg_trgm) already exists.
db_1   | 2020-03-16 15:48:24.503 UTC [78] STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
db_1   | 2020-03-16 15:48:24.503 UTC [74] ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
db_1   | 2020-03-16 15:48:24.503 UTC [74] DETAIL:  Key (extname)=(pg_trgm) already exists.
db_1   | 2020-03-16 15:48:24.503 UTC [74] STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
db_1   | 2020-03-16 15:48:24.504 UTC [73] ERROR:  duplicate key value violates unique constraint "pg_extension_name_index"
db_1   | 2020-03-16 15:48:24.504 UTC [73] DETAIL:  Key (extname)=(pg_trgm) already exists.
db_1   | 2020-03-16 15:48:24.504 UTC [73] STATEMENT:  CREATE EXTENSION IF NOT EXISTS pg_trgm
api_1  | [2020-03-16T15:48:24.514Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
api_1  | [2020-03-16T15:48:24.515Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
api_1  | [2020-03-16T15:48:24.521Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
api_1  | [2020-03-16T15:48:26.812Z] info File created: /srv/app/extensions/users-permissions/config/jwt.json
api_1  | 
api_1  |  Project information
```

Does this mean I can just ignore these errors and restart the containers, or is there a workaround I need to follow?

Regards
Sven

**Comment by cadavre** [comment]
@sven-verkstedt I work with these for some time now. After restarting api container all works fine, but I guess some relations are corrupted in database. Nevertheless all is working fine.

**Comment by sven-verkstedt** [comment]
Well, but is there some DB migrate script or yarn command available that I can run (repeatedly) to ensure DB and all relations are in a clean state? 
Thanks!

**Comment by caicheng** [comment]
waiting for the fix, thanks. 
or is there any solusion?

**Comment by caicheng** [comment]
Waiting for the fix, thanks.
Is there any solution?

**Comment by petersg83** [comment]
It should be ok now, this call is not done anymore : https://github.com/strapi/strapi/pull/5991/files#diff-f2683c8198562c3d860d45a78a2fb88fL139

Update to a least `3.0.0-beta.20.3` and it should work fine. I'm closing the issue, don't hesitate to open a new one if needed.
