### ISSUE TITLE
Watch admin not watching certain files

### ISSUE THREAD

**Issue by CKGrafico** [strapi/strapi#5072]
**Describe the bug**
when --watch-admin is used the folder `./extensions`is not being watched.

**Steps to reproduce the behavior**
1. Create a folder called ./extensions
2. Override any file there for example `extensions\content-manager\admin\src\containers\EditView\EditViewStrapi.js`
3. run `strapi dev --watch-admin`
4. Change the created file.
5. watch is not triggered
6. Change any controller of the app
7. Watch triggered

**Expected behavior**
--watch-admin watch overrided files from strapi in local folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/2048511/72985087-7d775880-3de5-11ea-9cd7-c5bbfea0b6f3.png)

![image](https://user-images.githubusercontent.com/2048511/72985111-8c5e0b00-3de5-11ea-9f24-007ffaa4c4e6.png)

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: Strapi v3.0.0-beta.18.5
- Database: mysql
- Operating system: Windows

**Comment by soupette** [comment]
@CKGrafico is the filed copied in the `.cache` folder if yes the change is trigger but you will need to import it in another file so it used. Also, `EditViewStrapi.js` doesn't exist in the codebase that is why your app is not reloaded.

**Comment by CKGrafico** [comment]
Awesome thanks!
