### ISSUE TITLE
The aggregate.count value from graphql is wrong when I overwrite the find() function in a controller

### ISSUE THREAD

**Issue by wil92** [strapi/strapi#5074]
**Describe the bug**
I need to overwrite the `find()` function to inject some filters in the query and then request this list via graphql. To get the list I'm using the **postsConnection** query but the values that came in the `aggregate.count` it's not the right. I overwrite the count method also in the controller, but the bug persists.

This is my `find` function in the Post controller:

```
find(ctx) {
    if (!isWriter(ctx)) {
      ctx.query = {
        ...ctx.query,
        publishedAt_lte: new Date().toISOString(),
        enable: true
      };
    }
    const filters = convertRestQueryParams(ctx.query);
    return buildQuery({
      model: Post,
      filters
    });
}
```

This is my `count` function (this is just a test):
```
count() {
  return 0;
},
```

**Steps to reproduce the behavior**
This is my query

```
query {
  postsConnection(
    sort: "createdAt:desc"
    limit: 5
    start: 0
  )
  {
    values {
      id
      title
      body
    }
    aggregate {
      count
    }
  }
}
```

I get this response:

```
{
  "data": {
    "postsConnection": {
      "values": [
        {
          "id": "5e298dea637fb75a2f64563a",
          "title": "sadfsafd",
          "body": "asdfsadf"
        }
      ],
      "aggregate": {
        "count": 3
      }
    }
  }
}
```

**Expected behavior**
The count value should be equals to 1 and not to 3

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: mongodb
- Operating system: ubuntu

**Comment by lauriejim** [comment]
Hello @wil92 
The aggregate is based on `where` params you give to the `postConnection`
By default we can't know the params customization you did in your `find` function.
To achieve what you are trying to do, I suggest you create a custom controller function to count your data and in GraphQL call this query to have the count of your data based on the same custom query.
