### ISSUE TITLE
Model timestamp updated_at has default value set on creation

### ISSUE THREAD

**Issue by cadavre** [strapi/strapi#5075]
**Describe the bug**
`updated_at` field is auto-populated for Postgres because of column option to default to `CURRENT_TIMESTAMP`.

**Expected behavior**
`updated_at` field shall not be set on entity creation.

**Screenshots**
<img width="512" alt="Zrzut ekranu 2020-01-23 o 16 19 53" src="https://user-images.githubusercontent.com/461796/72997156-334da180-3dfc-11ea-878b-5e8f3e3a6980.png">

**Code snippets**
`car/models/Car.settings.json`:
```
{
  "info": {
    "name": "car"
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ]
  },
  "attributes": {
    "name": {
      "type": "string"
    },
// ...
```

**System**
- Strapi version: 3.0.0-beta.18.6
- Database: Postgres

**Comment by lauriejim** [comment]
Hello! I'm not sure to follow you.
Can you please give me the details of your issue.

**Comment by cadavre** [comment]
On **creation** of an entity – `updated_at` field is updated along `created_at`. This is not what should be happening.

**Comment by lauriejim** [comment]
What should happen to you?

**Comment by cadavre** [comment]
Newly created entity (that had not beed updated yet), shall have `updated_at = null`.

Tons of the systems depends on this check: `updated_at IS NOT NULL` to check if an entity was changed anytime after creation.

**Comment by lauriejim** [comment]
Hum would like the @Aurelsicoko  and @alexandrebodin point of view about that.

**Comment by cadavre** [comment]
FYI it's how it was before `beta.18`. BTW same update since we cannot filter by date ranges in admin UI anymore. :(

**Comment by alexandrebodin** [comment]
Hi @cadavre this is pretty much a question of opinion here. We are not planning on changing this behaviour anytime soon. 

Having updated_at not being null is really practical in many usecases. You can just compare both timestamps if you really need to check if the entity was changed after creation.
