### ISSUE TITLE
Update content type template

### ISSUE THREAD

**Issue by ycuello85** [strapi/strapi#5077]
Hi, good morning everyone, I have a little problem with the editing of a content type. It happens that if I remove an element from a table when creating another one it adds me with the id that follows it doesn't restart it. The same if I want to change the order of how the content I'm publishing will look like it would. Greetings and thanks for the answer.

**Comment by batuhankok** [comment]
Hi @ycuello85,
I think that is not an issue and it is not about Strapi. The situation that you mentioned is about how relational databases works 😊

**Comment by ycuello85** [comment]
> Hi @ycuello85,
> I think that is not an issue and it is not about Strapi. The situation that you mentioned is about how relational databases works 😊
Thanks @batuhankok for the prompt reply, I'll check what you say

**Comment by lauriejim** [comment]
It's normal, auto incrementation based on sequences.
