### ISSUE TITLE
Configure a prefix for Strapi tables when using an existing database

### ISSUE THREAD

**Issue by ghost** [strapi/strapi#5080]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

For situations where a Strapi app is generated on a pre-populate/utilized database; It would be nice to be able to auto prefix all tables generated by Strapi.

**Comment by lauriejim** [comment]
I find this idea cool. Thank you @rosuji-mms for submitting it.
@Aurelsicoko and @alexandrebodin what do you think about it?

**Comment by alexandrebodin** [comment]
We could do it. Just need to check the length  to avoid too long table names as it already is an issue.

**Comment by rosuji-mms** [comment]
@alexandrebodin @lauriejim this is great news. I would be happy to land a hand in this if needed.

**Comment by jacksbox** [comment]
Are there any news on this? If it is still an open task I would like to contribute!

**Comment by alexandrebodin** [comment]
Hi @jacksbox This is still open for contrbutions :)

**Comment by borihan-p** [comment]
+1

**Comment by hassanrehman** [comment]
+1

**Comment by jakobsjoqvist** [comment]
Hi! Is this issue still open for contributions? If it is then I would like to contribute 😀

**Comment by alexandrebodin** [comment]
Hello @jakobsjoqvist. This is Still open for contributions yes. You will have to contribute to the v4 code though. You can check it out in the releases/v4 branch in packages/core/database. There is a schema folder with all the database schema management implementation. Let us know if you want to start working on that and need some help.

**Comment by jakobsjoqvist** [comment]
Super! Yes, I will work on this one! I will contact you (or Strapi team) if I need some help.

**Comment by jakobsjoqvist** [comment]
Hi again,

I have now submitted PR #11491 to address this issue.

**Comment by jakobsjoqvist** [comment]
Re-sumitted the PR in #11793 since the old PR (#11491) was closed when the `releases/v4` branch was deleted.

**Comment by SAG33** [comment]
It's no good idea because database table names can be used by other services. A better solution seems to be  when first connecting a database creating the choice of a superadmin of rules for using database tables: master or servant table of DB
