### ISSUE TITLE
Deleting file upload results in TypeError: Cannot read property 'split' of undefined in Content Type that references file 

### ISSUE THREAD

**Issue by DaveYouey** [strapi/strapi#5084]
**Describe the bug**
Having an uploaded file in the **Files Upload** section, and a **Content Type** entry that references the file, deleting the file in the **Files Upload** section and subsequently attempting to view the **Content Type** panel causes a "something went wrong" error on the page and a JS error in the console `TypeError: Cannot read property 'split' of undefined`. After this there is no way to view that panel without getting involved with the db directly to remove the entry.

**Steps to reproduce the behavior**
1. Upload a file in the **Files Upload** panel
2. Create a content type with a media field and create an entry referencing the file in step 1
3. delete the updated file in the **Files Upload** panel
4. try and view the content type created in step 2

**Expected behavior**
The content type list to appear, with the entry having an empty value for the media field

**Screenshots**
Upload a file:
<img width="1440" alt="Screenshot 2020-01-24 at 11 56 47" src="https://user-images.githubusercontent.com/40293221/73067704-4b2b3100-3ea1-11ea-83e2-73a1dd601bf5.png">
Create a content type referencing the file:
<img width="1440" alt="Screenshot 2020-01-24 at 11 56 24" src="https://user-images.githubusercontent.com/40293221/73067714-51211200-3ea1-11ea-9df7-622cf37c8062.png">
After deleting the file:
<img width="1440" alt="Screenshot 2020-01-24 at 11 57 15" src="https://user-images.githubusercontent.com/40293221/73067729-58482000-3ea1-11ea-8fd8-46620505340d.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.18.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.6
- Database: Default quickstart (SQLite?)
- Operating system: OSX

**Additional context**
Looks to me purely a UI issue not checking the length of the files array in the entry before trying to split. The network request is returning fine with an empty object for the files.

**Comment by lauriejim** [comment]
This issue already exists, please browse the list of opened or closed issues before posting an issue.
Please check https://github.com/strapi/strapi/issues/4384

> This is a templated message
