### ISSUE TITLE
GraphQL return nulls on nested dynamic zone fields

### ISSUE THREAD

**Issue by MeLlamoPablo** [strapi/strapi#5086]
**Describe the bug**
Given a content type named `Nested`, which has a dynamic zone containing any type of components, and a content type `Base` with a relation "Base belongs to many Nesteds", `strapi-plugin-graphql` will always return null for the dynamic zone field when querying `findOne` `Base`. Querying `findOne` `Nested` works as expected.

**Steps to reproduce the behavior**
1. Clone this repo: https://github.com/MeLlamoPablo/strapi-graphql-dynamic-zones-bug-repro
2. Set it up with `yarn` and run it with `yarn develop`
3. Go to the admin panel at `http://localhost:1337/admin`
4. Create a `Nested` with test data.
5. Create a `Base` including this `Nested`.
6. Query it from graphql.

**Expected behavior**
The content from the dynamic zone is included in the response, as it happens with REST:

```
$ curl -H "Authorization: Bearer $token" localhost:1337/bases/1
```

```json
{
  "id": 1,
  "title": "test",
  "created_at": "2020-01-24T16:13:27.795Z",
  "updated_at": "2020-01-24T16:13:27.795Z",
  "nesteds": [
    {
      "id": 1,
      "title": "test",
      "created_at": "2020-01-24T16:13:21.614Z",
      "updated_at": "2020-01-24T16:13:27.807Z",
      "components": [
        {
          "__component": "a.a",
          "id": 2,
          "text_field": "hello world"
        },
        {
          "__component": "b.b",
          "id": 2,
          "number_field": 123
        }
      ]
    }
  ]
}
```

**Code snippets**

This is the query used to retreive the data.

```graphql
query {
  base(id:1) {
    title
    nesteds {
      title
      components {
        ... on ComponentAA {
          text_field
        }
        ... on ComponentBB {
          number_field
        }
      }
    }
  }
  
  nested(id:1) {
    title
    components {
      ... on ComponentAA {
        text_field
      }
      ... on ComponentBB {
        number_field
      }
    }
  }
}
```

This is the data returned from the query:

```json
{
  "data": {
    "base": {
      "title": "test",
      "nesteds": [
        {
          "title": "test",
          "components": null
        }
      ]
    },
    "nested": {
      "title": "test",
      "components": [
        {
          "text_field": "hello world"
        },
        {
          "number_field": 123
        }
      ]
    }
  }
}
```

Notice how the `components` field is missing when we query the `Nested` through `Base`, but is present when we query it directly.

**System**
- Node.js version: v12.13.0
- NPM version: v6.2.10
- Strapi version: `3.0.0-beta.18.6`
- Database: sqlite
- Operating system: Ubuntu 18.04

**Additional context**
Interestingly enough, this happens for `belongs to many` relations, but not for `has many`.

Thank you for your time.

**Comment by lauriejim** [comment]
This issue has been fixed in the stable version.
Just tested it and it works well.
