### ISSUE TITLE
GraphQL: Deep Filter on repeatable component throws error

### ISSUE THREAD

**Issue by saschatu** [strapi/strapi#5089]
**Describe the bug**
I create a component "Description" which consists of a language and a text field. This component is used in a content type and marked as repeatable. 

In GraphQL I would like to filter on the language in order to get just one descritpion entry. But the API throws the error "Your filters contain a field 'Description.Language' that doesn't appear on your model definition nor it's relations"

**Steps to reproduce the behavior**
1) Create a component with two fields (e.g. Language and Description) and a content type with some fields and this description component, mark it as repeatbale (see definitions below under Coder Snippets)
3) Create one entry with two description - one for EN.
4) Query:
```
query {
  hackathons(where:{ Description: {Language: "EN" } }) {
    Title
    Langu
    Description {
      Language
      Description
    }
  }
}
```

Note: without the filter works. 

**Expected behavior**
Returns only the english description.

**Code snippets**
Create Component: 
```
{
  "info": {
    "name": "Description",
    "icon": "atlas"
  },
  "options": {},
  "attributes": {
    "Language": {
      "type": "enumeration",
      "enum": [
        "EN",
        "DE"
      ],
      "required": true,
      "default": "DE"
    },
    "Description": {
      "type": "richtext"
    }
  },
  "connection": "default",
  "collectionName": "components_language_fields_descriptions"
}
```
And Content type:
```
{
  "connection": "default",
  "collectionName": "hackathons",
  "info": {
    "name": "Hackathon"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Title": {
      "type": "string",
      "unique": true,
      "required": true
    },
    "Description": {
      "type": "component",
      "repeatable": true,
      "component": "language-fields.description"
    },
    "Langu": {
      "type": "enumeration",
      "enum": [
        "DE",
        "EN"
      ],
      "default": "DE"
    }
  }
}
```

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.6
- Database: SQlite
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi deep filtering on filters isn’t available for now.

**Comment by saschatu** [comment]
Hi @alexandrebodin,
thanks for your fast replay - so it is a feature request or something already planned? 
Thanks a lot!
Sascha

**Comment by alexandrebodin** [comment]
We should prevent the query because it needs to be implemented so a minor bug / and a new feature request to add it :)

**Comment by dankostov** [comment]
I am having the same issue, it would be wonderful if we get this feature!

**Comment by lauriejim** [comment]
I'm closing this issue, let's consider the feature request that is linked.
