### ISSUE TITLE
Setup failure on path containing space (' ')

### ISSUE THREAD

**Issue by shrotavre** [strapi/strapi#509]
**Node.js version**: 8.9.4
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Ubuntu 16.04 (dual booted with Windows)

I tried on setting up Strapi in an empty directory under the `/media/usr/Development Disk/#experiment/newdir` and it fails. So I changed my drive name to a non-spaced name, and it succeeded. 

The output log made me suspecting an issue on command line execution due to the space on the path. So, I tried to replicate it again by setting up Strapi on a new folder with a name containing space (`test one`) aand it failed again. The output is kinda like this: 
```
rm: cannot remove 'one': No such file or directory
(node:7005) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: rm -r /media/shrotavre/devdisk/#experiment/test one
rm: cannot remove 'one': No such file or directory

(node:7005) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
(In my case) I think the issue is related to the 21st line on `packages/strapi-bookshelf/lib/utils/connectivity.js`:
```
execSync(`rm -r ${scope.rootPath}`);
```
This issue might be resolved by adding brackets around the `${scope.rootPath}`. 

I'm putting up this as an issue because maybe there may be other implementations of command line executions that are prone to the space issue like this one.

**Comment by ArkhipovK** [comment]
This  issue must be already solved in this pull request https://github.com/strapi/strapi/pull/492
