### ISSUE TITLE
Filter for 'datetime' fields in list view is very limited

### ISSUE THREAD

**Issue by ThomasMoritz** [strapi/strapi#5091]
I'm not sure if it is actually a bug but if I want to filter over a `datetime` field in the list view I only get two filters ('is' and 'is not'). If I switch to a `date` field I get the full filter list. 

As a workaround just override `strapi-plugin-content-manager/admin/src/components/FilterPickerOption/utils.js` and add `datetime` to switch-case-statement right under `date`.

**Steps to reproduce the behavior**
1. Add a `datetime` field to a content type.
2. Add some date
3. Go to the "List view"
4. Try to filter over the newly added field

**Expected behavior**
Get all the filters you get for a `date` field. 

**Screenshots**
<img width="1382" alt="datetime_bug" src="https://user-images.githubusercontent.com/5557208/73118497-2ee8cc00-3f55-11ea-8fce-298cea334718.png">

**System**
- Node.js version: 12.10.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.18.6
- Database: mongo db
- Operating system: MacOS Catalina

**Comment by jikotw74** [comment]
same issue here

**Comment by lauriejim** [comment]
Thank you for reporting this. Thank you for this feedback.
