### ISSUE TITLE
Cannot init project with mongodb with docker

### ISSUE THREAD

**Issue by Hulkmaster** [strapi/strapi#5096]
**Describe the bug**
So what i want:
docker with strapi
docker with mongo
docker with front

i want to start strapi project with cli (npx), but when i try to init with mongo config - it tries immediately to coonect to db (which it cannot do, because it is in docker, and will be available via docker network)

**Steps to reproduce the behavior**
1. have mongo in docker network
2. try to init strapi with npx with mongo config

**Expected behavior**
I would expect to either have promt like "could not connect to mongo, should we still continue?" or even to ignore that error

**Comment by lauriejim** [comment]
Hello!
Are you using a docker-compose file?
This [video](https://youtu.be/XjoXqyl4LpA) can help you maybe 🤔

**Comment by Hulkmaster** [comment]
important step is missing in that video

strapi project init

in that video project is already creaeted and person just wraps it in docker


my problem was: i could not init the project without running mongo instance, because cli tries to connect to mongo during installation

**Comment by roelbeerens** [comment]
@Hulkmaster Is your mongo in docker accessible from outside your docker network? If not, have you set an internal and external port? 

This is my local docker-compose, with which I could init strapi just fine:

`version: "3.7"

services:

  database:
    container_name: project-mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=project
      - MONGO_INITDB_ROOT_PASSWORD=project
    ports:
      - 27017:27017`

Notice my external and internal port numbers are the same (intentional)

**Comment by Hulkmaster** [comment]
okay, maybe i should extend my question

What i want to do:
Several docker containers, all of them in dedicated docker networks, only reverse-proxy is accessible from outside, so

reverse-proxy: 80:80
network: reverse-proxy

mongo: backend network

front: reverse-proxy network

strapi: reverse proxy and backend network


so mongo should be accessible only from strapi docker container


right now i cannot do that, because strapi install with mongo connectors require me to run mongo db in advance, expose the port outside, wait for strapi to install, only then remove port expose, put strapi into container (via volume or add/copy), run the app


i think that extra step, where i HAVE TO expose mongodb port in order to INSTALL strapi is unneeded
