### ISSUE TITLE
Installing within Container

### ISSUE THREAD

**Issue by lucaperret** [strapi/strapi#510]
Strapi version: 3.0.0-alpha.8.3
Operating system: node:latest image from Docker hub

To be able to install dependencies and running the `postinstall` script inside a container, I'm setting [this argument](https://docs.npmjs.com/misc/config#unsafe-perm):
```bash
npm install --unsafe-perm
```
Otherwise, this warning is shown but all the app isn't well installed:
```bash
npm WARN lifecycle my-strapi-app@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) my-strapi-app@0.1.0 node node_modules/strapi/lib/utils/post-install.js /path/to/my-strapi-app
```
Due to these lines https://github.com/strapi/strapi/blob/master/packages/strapi-admin/scripts/setup.js#L18 the npm cli installation should be launched with root permission.

It can be a problem for some environment without root permission.

**Comment by Aurelsicoko** [comment]
As I already said to you, did you try [to run the following commands](https://docs.npmjs.com/getting-started/fixing-npm-permissions) before launch `npm install` at the root of your project?

I took a look at the Shell.JS project that we are using and there is no issue about the root permission.

**Comment by lauriejim** [comment]
@lucaperret Can you give us an update about this issue please

**Comment by lucaperret** [comment]
Everything is working properly now.

**Comment by ntloi95** [comment]
> Everything is working properly now.

What did you do to fix it?
