### ISSUE TITLE
Content types are not showing until restart node server

### ISSUE THREAD

**Issue by DanielWahl** [strapi/strapi#5101]
**Describe the bug**
On newly installed Strapi on Ubuntu 18 Server, the content types are not listed after creation.
When I restart the Node Server, it's listed.

**Steps to reproduce the behavior**
1. Install current Strapi on Ubuntu 18
2. Run in Development Mode (npm start)
3. Configure everything
4. Do to admin panel an create a content type
5. Content type not listed

**Expected behavior**
Content type should be listed after creation

**System**
- Ubuntu 18.04.3 LTS with Plesk Onyx
- Node.js version: v12.4.0 / v10.18.1
- NPM version: 6.13.6
- Strapi version: 3.0.0-beta.18.6 (node v10.18.1)

**Additional context**
When I restart the Node server (alt+c and npm start), the content types are shown.
But I need to restart the node server after every content type creation. When I add 2 types, only the first one is shown after restart.

Thanks for every help

**Comment by derrickmehaffy** [comment]
@DanielWahl This is intended, if you want to avoid manually doing this you can use `npm develop` however Strapi stores model configs in the files ( `api` directory) and in order for these changes to take effect node has to restart. The develop command automatically restarts for you.

As this is an intended action I'm going to mark this as closed.

**Comment by DanielWahl** [comment]
Just in case anyone else wonders how to do this:
`npm run develop`

@derrickmehaffy thank you
