### ISSUE TITLE
Displaying the exception messages in the Admin UI

### ISSUE THREAD

**Issue by batuhankok** [strapi/strapi#5104]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Hi,

I have been added some sophisticated validations to my content type article's lifecycle callbacks to use both Admin UI side and API side of Strapi. These validations throw an error exception to stop saving process if something goes wrong. However, when the error exception thrown, then Admin UI calls `strapi.notification.error()` with constant message like "An error occured". 

How can I replace this message with the message of exception. In this way, I could give an meaningful errors in the side of Strapi Admin UI.

Thanks for your time.

**Comment by lauriejim** [comment]
Hello! Can you please share the code that sends the error message from your backend.

**Comment by batuhankok** [comment]
Hi Jim,

We are throwing the exception below if backoffice users try to delete any content.
```
beforeDestroy: async (model, attrs, options) => {
    throw new Error(`No one can destroy the content!`);
},
```

**Comment by lauriejim** [comment]
Thank you for this update.

**Comment by oussemala** [comment]
Hello, i'm using `"strapi": "~3.5.4"` and throwing with:
`throw new Error('Please fill expiry date')`
in models afterCreate function, but it didn't display the error in the UI.
