### ISSUE TITLE
Local Plugin Documentation Incorrect - Unable to make queries

### ISSUE THREAD

**Issue by KempfCreative** [strapi/strapi#5106]
**Describe the bug**
Local Plugin Documentation is incorrect. Will result in errors if implemented per instructions.

**Steps to reproduce the behavior**
1. Create a new plugin via the Strapi CLI, then follow the directions here: https://strapi.io/documentation/3.0.0-beta.x/plugin-development/backend-development.html
2. Once you start to create the queries in the plugin's controllers (`./plugins/my-plugin/api/controllers/index.js`) per the instructions, you get `undefined` function calls.
3. Fix that error by using `.config.queries` instead of `.queries`.
4. Still see `model` as `undefined` in `./plugins/my-plugin/api/config/queries/bookshelf/index.js` per the same documentation.

**Expected behavior**
I should be able to follow the local-plugin directions and have a working local plugin.

**System**
- Node.js version: node v10.15.3 
- NPM version:
- Strapi version: 3.0.0-beta.18.6 
- Database: postgresQL
- Operating system: MacOS

**Additional context**
This was working in Strapi beta.7. It seems some undocumented changes here (https://github.com/strapi/strapi/commit/56c59c5ae10c25a967a6459c668b487c0df3a3ee#diff-9516fae0820d9599ffeb039d1cac1cceR92) are related to how this should be working?

**Comment by alexandrebodin** [comment]
Hi, If you feel like opening a PR to remove the section about the queries go for it ;)

You can look this doc on how to run queries https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html

**Comment by KempfCreative** [comment]
I'll be happy to, once we update our plugin internally. Then I'll have a roadmap for how to update the docs.
