### ISSUE TITLE
GraphQL where filter it's not working properly.

### ISSUE THREAD

**Issue by nameszian** [strapi/strapi#5107]
**Describe the bug**
The where it's not working properly, does not filter anything.

**Steps to reproduce the behavior**
1. Go to 'http://localhost:1337/graphql'
2. Make a GraphQL WHERE i.e. Code snippets --> Query.
3. See the result. Does not filter anything because it returns everything, with status in created (good) but also in empty (error).

**Expected behavior**
This query in theory it filters by status and user identifier (with status = created), but you can see that it also returns status empty, so does not filter anything.

**Screenshots**
<img width="949" alt="where_graphql" src="https://user-images.githubusercontent.com/23345155/73200988-40d69480-4138-11ea-9c90-9ef62c440e6f.png">

**Code snippets**
Query:
```
query OrderByUserIdAndStatus($userId: ID!, $status: String!) {
	orders(where: { user: $userId, status: $status }) {
    status
  }
}
```
Query variable:
```
{
 	"status": "created",
	"userId": "5dd0a9b16bf37d9903b15556"
}
```
**System**
- Node.js version: v10.
- NPM version: v6.
- Strapi version: 3.0.0-beta.17.5.
- Database: mongo.
- Operating system: linux and macOS.

**Additional context**
empty

**Comment by derrickmehaffy** [comment]
the entire where statement needs to be a query variable.

**Comment by nameszian** [comment]
How? can you give me some clue?

**Comment by alexandrebodin** [comment]
@derrickmehaffy not anymore. This was fixed. Issue with the graphql-json type

**Comment by nameszian** [comment]
Is it fixed in the latest version? To know if I have to update mandatory or not...

**Comment by alexandrebodin** [comment]
I was talking about the query variable :) We need to check your exact error. Not sure it is fixed.

**Comment by nameszian** [comment]
Any news?

**Comment by lauriejim** [comment]
Hello! I just tried with latest version of Strapi (beta.18.7) and it works well.

**Comment by geocine** [comment]
May you reopen this issue Doesn't seem to work on my end I am using `beta.18.7`

**Query**
```gql
query GetProducts($name: String) {
  products {
    name
    description
    price
    images(where: { name: $name }) {
      name
    }
  }
}

```
**Query Variable**
```json
{
  "name":"a"
}
```
Running this query returns the records where the `name` of the file is not even equal to `"a"`.

This is the schema generated by at `exports/graphql/schema.graphql`

```gql
type Query {
  products(sort: String, limit: Int, start: Int, where: JSON): [Product]
}

type Product {
  name: String
  description: String
  price: Float
  images(sort: String, limit: Int, start: Int, where: JSON): [UploadFile]
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
}
```

**Comment by alexandrebodin** [comment]
This query is supposed to filter out images only. Without seeing the response you get we cannot help.

**Comment by derrickmehaffy** [comment]
@geocine 

### Query

```query GetProducts($where: JSON!) {
  products {
    name
    description
    price
    images(where: $where) {
      name
    }
  }
}
```

### Variables

```
{
  "where": {
    "name":"a"
  }
}
```
