### ISSUE TITLE
Cannot create a relation attribute named attribute

### ISSUE THREAD

**Issue by votruk** [strapi/strapi#5108]
**Describe the bug**
If you create ContentType with name Attribute and then use this type as a relation one to many and add column "attributes" into the other ConentType, eg AtributeGroup, -- you'll have a constant crash either during the creation of a new AtributeGroup entry or when you trying to load entries on the AtributeGroup page.

**Steps to reproduce the behavior**
1. Create AttributeGroup ContentType with one text field 'Name'
2. Create Attribute ContentType. Add relation Many-to-One to AttributeGroup. Use default names for columns. It will be the 'attributes' column in an AttributeGroup ContentType.
3. Try to create a new entry for AttributeGroup. 
4. When you'll try to save this entry you'll see a dialog with error 'attributes is not defined on the model.'

**Expected behavior**
Either "Attribute" should be forbidden to use as a ContentType name, or forbid to use 'attributes' name for relation's columns.

**System**
- Node.js version: v13.7.0
- NPM version: 6.13.6
- Strapi version:  3.0.0-beta.18.6
- Database: SQLite
- Operating system: MacOS

**Comment by lauriejim** [comment]
Thank you @votruk for reporting this issue!

Will try to fix it soon as possible.

**Comment by lauriejim** [comment]
@HichamELBSI I can see there is a PR that hasn't been merged.
The issue still exist, in the backend the message is well managed, but I can still use the name "attributes" for the relation in the admin panel.

**Comment by HichamELBSI** [comment]
I will check that today :+1:
