### ISSUE TITLE
Filters problem when "something went wrong."

### ISSUE THREAD

**Issue by amartincolby** [strapi/strapi#5110]
**Describe the bug**
I am migrating from 17.5 to 18.5. I have gone through the migration guide and Strapi successfully starts up. When I click on a content type, I get "an error occured during models config fetch." On the back end, I see the error "error Error: Your filters contain a field 'source' that doesn't appear on your model definition nor it's relations." This happens for all content types. I created a new content type through the 18.5 UI. The database is successfully updated, but when I then click on the new content type on the left-hand side, the error appears.

![image](https://user-images.githubusercontent.com/28883798/73218411-e9c8c380-4127-11ea-8b0a-c06b68e4204b.png)

I see "source is content-manager" among the filters above the list. If I remove it with the "x" button, I see the error "error TypeError: Cannot read property 'associations' of undefined" on the back-end. All of this is being done on a brand new database generated by Strapi.

Worse is when I click on Content Manager. All I get is an ominous "something went wrong."

![image](https://user-images.githubusercontent.com/28883798/73217472-fcda9400-4125-11ea-9f84-dc3ac36795de.png)

I assume this has something to do with my specific schema and can provide whatever information is required for investigation.

**Steps to reproduce the behavior**
1. Build an API with Beta 17
2. Migrate to Beta 18.5
3. See errors?

**Expected behavior**
The migration should happen smoothly.

**System**
- Node.js version: Node 10.16.3
- NPM version: 6.9
- Strapi version: Beta 18.5
- Database: MySQL
- Operating system: Docker CentOS

**Comment by soupette** [comment]
Can you try to delete your `.cache` and `build` folders and then restart your app? I am pretty sure that during your migration you did not rebuild the administration panel.

**Comment by amartincolby** [comment]
Thanks for the response. I did that multiple times. I even started fresh from our 17.5 repo and performed all the steps again. The outcome is the same.

**Comment by soupette** [comment]
Can you provide me with the URL from the browser because the `source` has been removed so maybe you didn't upgrade your app correctly. I am thinking that this is an upgrade issue as the `Source is content-manager`  has been removed.

**Comment by amartincolby** [comment]
Sorry for the delayed response. I got side-tracked on my project. First, I'll get you the URL as requested. Then, now that I know that source has been removed, I'm going to go through the process again and carefully track each step.

**Comment by amartincolby** [comment]
@soupette Problem resolved. We were using a multi-stage Docker build that was using an image that contained an old image of Strapi. Rebuilding our base images with an explicit reference to the beta version that we were targeting fixed the problem.

**Comment by danieltorres1109** [comment]
I have the same problem.
Node.js version: Node 18.13.0
Strapi Version: 4.11.4

If you are as urgent as me, go from version "4.11.4" to "4.11.3".
1) change:
"@strapi/strapi": "4.11.3",
 "@strapi/plugin-users-permissions": "4.11.3",
 "@strapi/plugin-i18n": "4.11.3",
 
2) rm -rf node_modules
3)  rm yarn.lock 
4) yarn install
