### ISSUE TITLE
Non showstopper error after migrating to latest 3.0.0-beta.18.6

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#5115]
**Describe the bug**
After migrating from 3.0.0-beta.18.4 to 3.0.0-beta.18.6, I am seeing this error on start-up (yarn develop). See error in screenshot below.

Although this error does not seem to stop the app from running or misbehaving, **thus far!** It looks like both API and  the Admin panel are responding as expected.

Any ideas what could be causing the issue

**Steps to reproduce the behavior**
1. remove 'node_modules' folder
2. Change strapi packages in package.json from 3.0.0-beta.18.4 to 3.0.0-beta.18.6,
3. remove 'cache' and 'admin' folders
4. yarn develop

**Expected behavior**
Was not expecting any error on the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/2515109/73295109-fec45600-41fe-11ea-86a6-0b82297c705b.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.15.3
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.6
- Database: PostgreSQL v11.3
- Operating system: Ubuntu 1404 (via vagrant vbox)

**Additional context**

**Comment by derrickmehaffy** [comment]
Do you have my models or fields with the word `check` in it?

**Comment by laportem** [comment]
No. there are no models (content type), components or fields named ‘check’

**Comment by derrickmehaffy** [comment]
Is your project somewhere public where I can grab it and try to reproduce locally? At this point without a way to reproduce I'm honestly not sure.

(On a side note, you may want to consider upping that vagrant vbox version)

**Comment by laportem** [comment]
The code is not on github yet. Still developing locally. I will put the code on github tomorrow and send you the link

**Comment by lauriejim** [comment]
Do you have a clear steps to reproduce? Because I tried a migration and it works 🤔

**Comment by laportem** [comment]
I just did a normal migration like this

1. remove the 'node_modules' folder
2. change the strapi packages version in package.json from 3.0.0-beta.18.4 to 3.0.0-beta.18.6,
3. remove the 'cache' and 'admin' folders
4. yarn install
5. yarn develop

**Comment by lauriejim** [comment]
Can you tell me if I'm missed something?

https://www.loom.com/share/9531be92b50b42a2866cac99949d23f0

**Comment by laportem** [comment]
Ok, the steps you followed is the same as I did, except the app you migrated from has far less content types, components, fields, relationships etc.

I have now migrated from 3.0.0-beta.18.6  to 3.0.0-beta.18.7 and still have this issue.

The more I dig into this the more I am convinced it is caused by a field or relationship type in Postgres but it will be a tedious one to debug.

**Comment by laportem** [comment]
Errors disappeared after upgrading to the latest 3.0.0-beta.19.3. Closing issue
