### ISSUE TITLE
Is there any way to create a cascading DropDownList from the Strapi admin?

### ISSUE THREAD

**Issue by freemh** [strapi/strapi#5117]
I don't find any way to achieve dynamic or cascading dropdown list from the `admin` for a `relational` content type, as an example I have to add a `restaurant` on a specific `country` and `city` like in this GIF:

![Image of Yaktocat](https://cdn-media-1.freecodecamp.org/images/R6rX0AxiRQV668mITyMfa7Zl6bUW8SE53IJj)

**Comment by lauriejim** [comment]
Hello @freemh !
I think another issue already exist about this topic.
This kind of field not exit in Strapi.
I suggest you to submit your need here please - https://portal.productboard.com/strapi
