### ISSUE TITLE
Adding explicit icons to the Content-Type-Builder

### ISSUE THREAD

**Issue by lucas-jg** [strapi/strapi#5121]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

I want the content type builder to show the advanced settings for the field with an icon.
Users can easily identify the type if the value in the advanced settings is inserted as an icon.

It's an example image.
![strapi](https://user-images.githubusercontent.com/31200025/73339251-b28b1b80-42bb-11ea-93b0-735a3dc2ec7c.jpg)

I couldn't find the right icon, so I put in a circle.
But it will be more effective if you put the right icon in.

This function will have a great visual effect.

**Comment by derrickmehaffy** [comment]
I quite like this, tagging @Aurelsicoko and @soupette.

**Comment by soupette** [comment]
I also do like the idea!

**Comment by derrickmehaffy** [comment]
moved to: https://feedback.strapi.io/customization/p/adding-explicit-icons-to-the-content-type-builder
