### ISSUE TITLE
Strapi keeps re-arranging model attribute lines

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#5122]
**Describe the bug**
When adding or changing the data model (not sure if at any other situations as well) Strapi re-organizes the attribute definitions.

Is this something that is already in the works? This causes lots of changes and makes it much harder to review code commits/PRs.

**Steps to reproduce the behavior**
1. Add/edit data model
2. The affected files will be scrambled (screen attached)

**Screenshots**
![image](https://user-images.githubusercontent.com/11737572/73345089-728f4e80-4251-11ea-8af7-6fe83a5f5707.png)

**System**
- Node.js version: 10.0.0
- NPM version: 6.0.0
- Strapi version: 3.0.0-beta.18.6
- Database: Postgres
- Operating system: MacOS

**Comment by ScottAgirs** [comment]
PS. Perhaps any potential temporary hacks available?

**Comment by lauriejim** [comment]
This is fixed in the stable version of Strapi.
