### ISSUE TITLE
Add additional validations to the registration API (/auth/local/register)

### ISSUE THREAD

**Issue by iedmrc** [strapi/strapi#5134]
**Describe the bug**
There is no bug, I just had a question / needed help but [asked to edit the issue with a bug template](https://github.com/strapi/strapi/issues/5134#issuecomment-582399557).

**Steps to reproduce the behavior**
1. Try to validate the input sent to `/auth/local/register` via POST method

**Expected behavior**
Expected to have a proper way to add a validation middleware/policy/function to the `/auth/local/register`

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.13.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.18.7
- Database: postgresql 12.1
- Operating system: macos catalina

**Additional context**
I looked for how can I validate additional fields that I added to `User` model while registering a user through `/auth/local/register` API and couldn't succeed to find anything. I also tried to add a new policy to the `extensions/users-permissions/config/routes.json` file I created. 

```
{
  "routes": [
    {
      "method": "POST",
      "path": "/auth/local/register",
      "config": {
        "policies": ["plugins.users-permissions.ratelimit", "myValidationPolicy"]
      }
    }
  ]
}
```

But it raises such an exception:
```
[2020-01-30T12:27:48.879Z] debug ⛔️ Server wasn't able to start properly.
[2020-01-30T12:27:48.881Z] error TypeError: Cannot read property 'undefined' of undefined
```

What is the proper way to validate that additional fields on the`User` model on the server-side?

**Comment by iedmrc** [comment]
This should be a very common case. What am I missing? :)

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message

**Comment by iedmrc** [comment]
Hey @lauriejim , could you please re-open that since I edited to fit for issue template. Thanks!

**Comment by lauriejim** [comment]
Hello! 

You can easily update the policy of the register function by using the customization concept.
https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#plugin-extensions

Here is a short video - https://www.loom.com/share/3cc0ddb379284dccba480e41be539e5d
