### ISSUE TITLE
Only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by clowNay** [strapi/strapi#514]
**Node.js version**: v8.3.0
**npm version**: 5.4.2
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: macOS v10.12.6

After a clean install I still get the issue.
I have changed the port to 3333 as the only thing.
I'm being redirected to http://localhost:3333/admin/plugins/users-permissions/auth/register

<img width="1274" alt="screen shot 2018-01-25 at 08 53 29" src="https://user-images.githubusercontent.com/6547117/35376893-58972048-01ad-11e8-883f-37173a051c1f.png">

**Comment by soupette** [comment]
Could you tell me if you started your project in dev mode?

Did you manage to start the project at some point?

**Comment by clowNay** [comment]
I did not start the project in dev mode no.
Yes I had it running on another computer first, where I from there created a GitHub repository and then afterwards pulled it down to another. That's when it stopped working, it still works on the other one though.

**Comment by clowNay** [comment]
Was an issue with file permissions

**Comment by mortendybdal** [comment]
Hi @clowNay 
How did you manage to solve the problem with the "only one instance of babel-polyfill is allowed"-error?
I have no problem running Strapi on localhost, but as soon as I deploy it to Heroku, the issue pops up.  I'm redirected to /admin/plugins/users-permissions/auth/register and it shows a blank white screen with the exact same errors in my console as above. 
I'm using a mongodb running on compose.io, but other than I'm simply following https://blog.strapi.io/deploying-a-strapi-api-on-heroku/. Any help or suggestions would be great!

**Comment by Duske** [comment]
Hey folks,
I had the same problem and could solve it by running `npm run setup --plugins` in the strapi directory.
Maybe it works for some of you as well!

**Comment by Norbz** [comment]
same issue here. Deployed on a VPS.
Tried to run setup with --plugins but ended up getting an error (even on local)

When running setup on my VPS, I get no error, but then the admin panel can't be accessed.

**Comment by soupette** [comment]
@Norbz you need to delete the analytics plugin in order to launch the command with the `--plugins` options.

Also what is your current version of Strapi?

**Comment by Norbz** [comment]
@soupette My current strapi version is strapi@3.0.0-alpha.12.1.3

Resolved it for now by removing the build folder from the npmignore, this way my CI pushes the build folder onto the production server.

This is my first try with strapi, coming from keystoneJS, but I find it very confusing to push the builded admin to git, and not on npm package, but I understand this allows to deploy the API without any admin if needed, which is nice.

**Comment by situee** [comment]
@steampixel  I ran `npm run setup --plugins` at the project root, and problem solved. Please try it.

**Comment by steampixel** [comment]
Hey, thanks for the advice @situee @soupette. Unfortunately the command throws an error after installing and building a few minutes later:
```
/usr/src/api # cd strapi-app/
/usr/src/api/strapi-app # npm run setup --plugins

> strapi-app@0.1.0 setup /usr/src/api/strapi-app
> cd admin && npm run setup


> strapi-admin@3.0.0-alpha.14.5 presetup /usr/src/api/strapi-app/admin
> node ./scripts/preSetup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...

Packaged installed successfully

> strapi-admin@3.0.0-alpha.14.5 setup /usr/src/api/strapi-app/admin
> node ./scripts/setup.js

🏗  Building the admin...
(node:515) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! strapi-admin@3.0.0-alpha.14.5 build: `APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.14.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-19T08_58_24_432Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.14.5 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.14.5 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-19T08_58_24_471Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-app@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-app@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-19T08_58_24_491Z-debug.log
```
Maybe this has something todo with my Windwos host machine, with wrong permissions or the filesystem. I have encountered seveal similar errors when working with docker and nodejs on Windows using other frameworks and libs. I will switch to Ubuntu next year and try it again.

**Comment by yeomann** [comment]
thanks, After making some changes via --dev i created the build and ran into babe-poylfill issue. after doing `npm run setup --plugins ` admin panel is resolved finally so now i can login.

**Comment by Liroo** [comment]
@steampixel I do not have time to look at this issue if this is from babel or strapi but I had the same strange problem.

And this was due to the structure of my project.
I had the strapi app inside another project managed by webpack and babel and I really don't know why. When I was running the command `nom run setup --plugins`, and when the command `cross-env APP_PATH=$APP_PATH npm run build:dll && cross-env NODE_ENV=production IS_ADMIN=true ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress` was executed in the script. The `.babelrc` of my root project and not the strapi admin folder was used.

This is really strange but I don't have time to go with this issue.

**Comment by DevarshiDave** [comment]
having the same issue, created a new plugin and the 'only one babel-plyfill is allowed' error came. 
using the 'npm run setup --plugins' command also results in error

`Plugin - Email
�  Installing packages...
�  Building...
✅  Success

�  Plugin - My-custom-plugin
�  Installing packages...
�  Building...
D:\Projects\Kodava koota\Solutions\KodavaKootaAPI\plugins\my-custom-plugin\node_modules\strapi-helper-plugin\node_modules\.bin\rimraf:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-plugin-my-custom-plugin@0.0.0 build:clean: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/rimraf admin/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-plugin-my-custom-plugin@0.0.0 build:clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avnish Dave\AppData\Roaming\npm-cache\_logs\2019-06-08T18_12_24_828Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-plugin-my-custom-plugin@0.0.0 prebuild: `npm run build:clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-plugin-my-custom-plugin@0.0.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avnish Dave\AppData\Roaming\npm-cache\_logs\2019-06-08T18_12_24_891Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.26.2 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.26.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avnish Dave\AppData\Roaming\npm-cache\_logs\2019-06-08T18_12_25_211Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! KodavaKootaAPI@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the KodavaKootaAPI@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avnish Dave\AppData\Roaming\npm-cache\_logs\2019-06-08T18_12_25_355Z-debug.log`
