### ISSUE TITLE
user tables have hyphen instead of underscore.

### ISSUE THREAD

**Issue by AgileWish** [strapi/strapi#5143]
Strapi is generating user-permissions_permission, users-permissions_role, and users-permissions_user table.  This is against GraphQL standards.  You will not be able to query those tables without tweaks in the graphQL.
All tables should be created using underscore.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
