### ISSUE TITLE
Error log when updating enum values

### ISSUE THREAD

**Issue by adrienharnay** [strapi/strapi#5144]
**Describe the bug**
After adding an enum to a content type, my server crashes with the error:

```
error error: syntax error at or near "check"
    at Connection.parseE (/fakepath/node_modules/pg/lib/connection.js:605:11)
    at Connection.parseMessage (/fakepath/node_modules/pg/lib/connection.js:401:19)
    at TLSSocket.<anonymous> (/fakepath/node_modules/pg/lib/connection.js:121:22)
    at TLSSocket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:181:23)
```

Running `DEBUG=* yarn strapi develop` points to the following query:

```
  knex:query alter table "jobsitems" alter column "stage" type text check ("stage" in ('draft', 'test', 'published')) using ("stage"::text check ("stage" in ('draft', 'test', 'published'))) trx22 +9ms
```

Which maybe would be more valid like so:

```
  knex:query alter table "jobsitems" alter column "stage" type text
  knex:query alter table "jobsitems" add constraint name check ("stage" in ('draft', 'test', 'published')) using ("stage"::text check ("stage" in ('draft', 'test', 'published')))
```

(I'm not an expert in knex but this seems like valid syntax)

**Steps to reproduce the behavior**
1. Add an enum to a content type
2. Server crashes and error appears. Can't restart it

**Expected behavior**
/

**Screenshots**
/

**Code snippets**
/

**System**
- Node.js version: 12.14.1
- NPM version:6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: Postgresql 10.6
- Operating system: MacOS

**Additional context**

**Comment by derrickmehaffy** [comment]
indeed `check` is a reserved keyword for PostgreSQL: https://www.postgresql.org/docs/8.1/sql-keywords-appendix.html

For now I would avoid using it, general rule of thumb until some better validation is added is to follow the "two word" rule for models and field naming. 

The problem in this case is the SQL syntax is wrong as `check` is not escaped.

**Comment by ITninja04** [comment]
I can confirm this happened for me too. Error is a bit different than @adrienharnay posted:

```
[2020-01-31T14:16:27.046Z] error error: syntax error at or near "check"
    at Connection.parseE (/var/www/trcapi/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/var/www/trcapi/node_modules/pg/lib/connection.js:413:19)
    at TLSSocket.<anonymous> (/var/www/trcapi/node_modules/pg/lib/connection.js:129:22)
    at TLSSocket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by soupette** [comment]
@derrickmehaffy at this rate we are going to create a file with the allowed words instead of the forbidden ones...

**Comment by derrickmehaffy** [comment]
@soupette I know lmfao

**Comment by ITninja04** [comment]
@soupette @derrickmehaffy at the risk of sounding like an idiot, I have the same error and none of the fields in my instance use the word 'check'. My enum is a list of US States in ISO format, and produces the same error that @adrienharnay outlined above.

**Comment by lauriejim** [comment]
Hello @adrienharnay , can you please precise your model attribute and enum values you are trying to add?
This will help to reproduce your issue.

**Comment by aperron** [comment]
Hello, I reproduce the same issue.

**Steps to reproduce the behavior**

1. create a strapi application `yarn create strapi-app my-project`.
1. chose a Postgres database.
1. create an object with a field city (for example) of type Enum, save the modification > strapi restart
1. add a new value to this enum, save the modification => Strapi restart with error: 
> error Migration failed.
> error: syntax error at or near "check" 

in database log:

> ERROR:  syntax error at or near "check" at character 51
> STATEMENT:  alter table "tests" alter column "city" type text check ("city" in ('paris', 'londres', 'rennes')) using ("city"::text check ("city" in ('paris', 'londres', 'rennes')))

**System**
- Node.js version: 13.7.0
- NPM version:6.13.6
- Strapi version: 3.0.0-beta.18.7
- Database: Postgresql 12.1
- Operating system: Archlinux

**Comment by lauriejim** [comment]
Geat! thank you for these detail.

**Comment by aperron** [comment]
The application is still up and running. There is the error message every time you start or restart, and you can't modify an entity or create a new entity with the new value of enumeration because the constraint in bdd is unchanged.

**Comment by msoundar25** [comment]
I can confirm this happens when using content-type enum and doing anything inside /api with controller.js or model.js

**Comment by AG-Teammate** [comment]
Apparently knex does not support altering enum column types https://github.com/knex/knex/issues/1699 https://stackoverflow.com/a/45300797

One possible workaround on Strapi side is to use a simple string column type for enumeration fields, like this:
https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js#L72
```
case 'enumeration':
  return table.string(name);
  //return table.enu(name, attribute.enum || []); https://github.com/strapi/strapi/issues/5144
```

**Comment by gpiccin** [comment]
I've the same problem with Strapi v3.0.0-beta.18.8. 
My workaround was create another table to specify the enumerator values. This approach force to use one specific type and reduce the risk of input incorrect values.

**Comment by derrickmehaffy** [comment]
@alexandrebodin this is why previously I had specifically set SQL databases to use varchar instead of enum which I see has changed in recent versions (I must have missed this change). Many SQL databases including PostgreSQL and MySQL really don't handle dynamic updates to enum very well.

It might be worth reverting to the previous column type instead.

**Comment by alexandrebodin** [comment]
We could revert to a string now that there is a validation layer. We need to investigate using specific database migration code to handle it cleanly though.

**Comment by derrickmehaffy** [comment]
> We could revert to a string now that there is a validation layer. We need to investigate using specific database migration code to handle it cleanly though.

I agree, I had changed it in the past for similar reasons but until Strapi has a solid validation and migration features built for now reverting to text or varchar would be the best solution.

**Comment by alexandrebodin** [comment]
@derrickmehaffy your PRs are always welcome ;)

**Comment by derrickmehaffy** [comment]
I'll see what I can do, you changed the structure of this file so I'm not sure of where all it is referenced. Just here right @alexandrebodin ?

https://github.com/strapi/strapi/blob/7e7689c05f09c5ca74a2661bcb8e47795b0406b8/packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js#L71-L72

**Comment by alexandrebodin** [comment]
> I'll see what I can do, you changed the structure of this file so I'm not sure of where all it is referenced. Just here right @alexandrebodin ?
> 
> https://github.com/strapi/strapi/blob/7e7689c05f09c5ca74a2661bcb8e47795b0406b8/packages/strapi-connector-bookshelf/lib/buildDatabaseSchema.js#L71-L72

Yep. right there :)
