### ISSUE TITLE
Create a slug system

### ISSUE THREAD

**Issue by vks-pthibeault** [strapi/strapi#5147]
**Describe the bug**
Following the guide in the docs on creating a slug system, the model's lifecycle methods do not actually update the field's value in the database, therefore leaving it blank in all subsequent API requests.

**Steps to reproduce the behavior**
1. Create a new content type and modify its `beforeSave` lifecycle callback to populate a field ('urlFR' in my case) as described in the docs: https://strapi.io/documentation/3.0.0-beta.x/guides/slug.html#auto-create-update-the-slug-attribute
2. Add an entry to the content-type, ensuring that the field that should be used to populate slug is filled (logging `model.attributes` at this step will show the slug field as having been filled properly)
3. Return to edit the same entry: the slug field is empty. Also noticeable through an API call and in the database.

**Expected behavior**
The lifecycle callback should populate the field in the database, making it retrievable through the API.

**Screenshots**
The logs of the `beforeSave` callback
![Capture](https://user-images.githubusercontent.com/53871124/73556050-a9fe2680-441c-11ea-9529-eb0070372812.PNG)

API call
![Capture](https://user-images.githubusercontent.com/53871124/73556203-f5183980-441c-11ea-8a59-ab241fe99688.PNG)

**Code snippets**
```
beforeUpdate: async (model, attrs, options) => {
    if (model.relations.French !== undefined) {
      if (model.relations.French.models[0] !== undefined) {
        console.log(
          model.relations.French.models[0].relations.component.attributes.URL
        );
        model.set(
          "urlFR",
          model.relations.French.models[0].relations.component.attributes.URL
        );
        console.log(model.attributes);
        console.log("beforeUpdate");
      }
    }
  }
```

**System**
- Node.js version: v13.2.0
- NPM version: 6.13.4
- Strapi version: v3.0.0-beta.18.6 
- Database: MySQL 10.3.22-MariaDB
- Operating system: Linux

**Comment by rowild** [comment]
Why has this issue been closed without any further explanation? I encounter the same problem and therefore assume this problem has not yet been fixed... Please advise / explain! Thank you!

**Comment by vks-pthibeault** [comment]
> Why has this issue been closed without any further explanation? I encounter the same problem and therefore assume this problem has not yet been fixed... Please advise / explain! Thank you!

At the time, it had simply been explained to me in the Community Slack (now Discord) that lifecycle methods were new and unreliable, and that I should find a different way to do it.

I didn't feel that information was relevant to post here, but if it's still an issue, could be worth reopening.

**Comment by derrickmehaffy** [comment]
Keep in mind this issue is 2 years old and we already have a built in slug system, but if you wanted to handle more complex slug logic then lifecycles are the way to go.

See the lifecycle documentation: https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#available-lifecycle-hooks

I'm going to set this as closed as the feature already exists and for discussion on lifecycles and how to use them please visit our community forum or community discord to ask non bug report related questions.

https://forum.strapi.io
https://discord.strapi.io

**Comment by rowild** [comment]
Thanks for clarifying, @derrickmehaffy and @vks-pthibeault vks!
