### ISSUE TITLE
why require path layout.js outside of package?

### ISSUE THREAD

**Issue by ardani** [strapi/strapi#515]
https://github.com/strapi/strapi/blob/d3efb41e1042955a28db8a7de16636a6020439d5/packages/strapi-helper-plugin/lib/src/app.js#L30

**Comment by soupette** [comment]
When a plugin has a layout.js file in its config folder it can tell the `content-manager` how to display the inputs. See https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/config/layout.js
