### ISSUE TITLE
GraphQL Mutation Policy Not Execute

### ISSUE THREAD

**Issue by JuniYadi** [strapi/strapi#5151]
**Describe the bug**
I'm try to use Policy in GraphQL Mutation, but policy not execute when i'm send a post to graphql endpoint.

**Steps to reproduce the behavior**
1. Call GraphQL and GraphQL still return a output than no output in console

**Expected behavior**
i want use a policy to check a user owner of data, this is works good in REST API

**Screenshots**
![Screenshot from 2020-02-01 16-57-44](https://user-images.githubusercontent.com/31454084/73590876-84574700-451a-11ea-9292-12af43729e5c.png)

**Code snippets**
- GraphQL Mutation Request
```
mutation {
  createQuestion (input: {
      data: {
        name: "testing"
      }
  }) {
    question {
      id
    }
  }
}
```

- GraphQL Responses Output
```
{
  "data": {
    "createQuestion": {
      "question": {
        "id": "5e354b89deb3d553456d0d49",
      }
    }
  }
}
```

- /api/questions/config/schema.graphql
```
module.exports = {
    resolver: {
        Mutation: {
            createQuestion: {
                policies: ["global.Debug"],
                resolver: "Questions.create"
            }
        },
    },
};
```

- /config/policies/Debug.js
```
'use strict';
/**
 * `Debug` policy.
 */
module.exports = async (ctx, next) => {
  console.log('error test')
};
```

**System**
- Node.js version: 10.18.1
- NPM version:6.13.4
- Yarn version: 1.21.1
- Strapi version: 3.0.0-beta.18.6
- Database: MongoDB Latest (Docker)
- Operating system: Ubuntu 19.04

**Comment by lauriejim** [comment]
Hello @JuniYadi !

In your policy, can you call `next` after your log.

I think the issue can come from here.

**Comment by JuniYadi** [comment]
Hi @lauriejim ,

Yes, i'm already try that, but still not working only for Mutation.

### Screenshoot
![Screenshot from 2020-02-05 23-43-45](https://user-images.githubusercontent.com/31454084/73862718-8ea67780-4871-11ea-906e-75546e175fdf.png)
![Screenshot from 2020-02-05 23-44-00](https://user-images.githubusercontent.com/31454084/73862733-9239fe80-4871-11ea-9911-656864199934.png)

**Comment by lauriejim** [comment]
Hello! Is your application open source? (on github)
That will help me to debug you.

**Comment by JuniYadi** [comment]
Hi,

Sure, here: https://github.com/JuniYadi/Strapi-gql
even with new strapi 3.0.0-beta.18.7, still not working graphql policy in mutation

### Steps to reproduce the behavior
1. make new strapi
2. added graphql plugins
3. create question api with name and descriptions fields
4. make debug policy
5. added schema.graphql to /api/questions/config/schema.graphql
6. define mutation with policy
7. test call mutation in graphql
8. no console.log result in terminal or we can say, policy not execute.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
I can confirm (When I was trying to reproduce I didn't noticed you used `questions` and not `question` as content type name)
Probably related to this issue - https://github.com/strapi/strapi/issues/4819

**Comment by JuniYadi** [comment]
Hi,

Thanks, i'm try not using `s` in the end of api  (ex: comment), and i'm confirm, it's works perfectly.

### Screenshoot
![Selection-20200207-002](https://user-images.githubusercontent.com/31454084/74032050-a141bd80-49e5-11ea-9ebb-3fec90f0c2b1.png)

Commit - [Added API `Comment`](https://github.com/JuniYadi/Strapi-gql/commit/0783dd6d59267d7ebdc9bcc9233c7fbdba41ee76)

**Comment by lauriejim** [comment]
Great so it's a duplicated of this one - due to the `s`
https://github.com/strapi/strapi/issues/3134
