### ISSUE TITLE
Can't resolve module 'airbnb-prop-types'

### ISSUE THREAD

**Issue by thebiltheory** [strapi/strapi#5153]
**Describe the bug**
Cannot run `yarn develop` due to a module not found. 

**Steps to reproduce the behavior**
1. `yarn create strapi-app hello-world --quickstart`
2. `cd hello-world`
3. `yarn develop`

**Expected behavior**
Run the app

**Error **
```bash
Error: Module not found: Error: Can't resolve 'airbnb-prop-types' in '/Users/xxx/node_modules/react-dates/lib/components'
    at /Users/xxx/node_modules/strapi-admin/index.js:191:23
    at finalCallback (/Users/xxx/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/xxx/node_modules/webpack/lib/Compiler.js:265:20)
    at /Users/xxx/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/xxx/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/xxx/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/xxx/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/xxx/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/xxx/node_modules/neo-async/async.js:2830:7
    at /Users/xxx/node_modules/neo-async/async.js:2830:7
    at done (/Users/xxx/node_modules/neo-async/async.js:2863:11)
    at /Users/xxx/node_modules/neo-async/async.js:2818:7
    at /Users/xxx/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/xxx/node_modules/neo-async/async.js:2830:7
    at /Users/xxx/node_modules/neo-async/async.js:2830:7
    at done (/Users/xxx/node_modules/neo-async/async.js:2863:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**System**
- Node.js version: 12.10 (I tried with 10.11.0)
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta.18.7 
- Database: 
- Operating system: Mac OS 

# Solution
```bash
yarn cache clean
```

**Comment by soupette** [comment]
Is anyone having this issue? I cannot reproduce the bug.

**Comment by thebiltheory** [comment]
It's weird, because I haven't found anything related to it.
I tried multiple times, but I get always the same issue. 

What do you use as a system?

**Comment by soupette** [comment]
Same as yours...

If you run `yarn add -D airbnb-prop-types` at the root of your app you should be able to start your project. I know it's a not a fix and we should look into it but since I cannot reproduce it that's the best advice I can give you.

**Comment by derrickmehaffy** [comment]
This is generally a cache issue, it shouldn't be a problem directly with Strapi

**Comment by thebiltheory** [comment]
@derrickmehaffy the Strapi apps are freshly generated.

**Comment by lauriejim** [comment]
Hello! I just tried too and all works fine.
Here is what I did (base on your steps) https://www.loom.com/share/c23e228497234b0a80b7eac59636e3aa
Maybe I miss something 🤔

**Comment by thebiltheory** [comment]
@lauriejim running `yarn create strapi-app hello-world --quickstart` on a windows machine worked perfectly. 

I will try to empty yarn's cache this evening and try again.

**Comment by thebiltheory** [comment]
Clearing yarn's cache did the trick. 
Thanks for trying guys!

**Comment by lauriejim** [comment]
Thank you for the update.
