### ISSUE TITLE
Disabled Slack account

### ISSUE THREAD

**Issue by bartduisters** [strapi/strapi#5155]
Unable to request invite for Slack. It says my account has been disabled for strapi.slack.com. I've posted messages on Spectrum about this well over a week ago, without any response. Hence this ticket to try and get my account enabled so I can join the conversations.

**Comment by derrickmehaffy** [comment]
@bartduisters this is something you will need to contact slack about, it's not something Strapi can control.

https://strapi.slack.com/help/requests/new

**Comment by bartduisters** [comment]
Slack tells me to contact a `Workspace Administrator`, I guess that is one of the persons inside the Slack group.

`You recently tried to sign in to Strapi, but it looks like your account for that workspace is deactivated. We're sorry about that!

If you think this was a mistake, please contact a Workspace Administrator to reactivate the account.`
