### ISSUE TITLE
Add progress indicator for file upload

### ISSUE THREAD

**Issue by fl034** [strapi/strapi#5156]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

_I didn't put this on the product board since this is a small UX improvement_

**Please describe your feature request:**

When uploading files, you don't see the progress. This is okay for small files, but with larger files you click save and then it uploads, but the UI doesn't show anything.

Also it maye be cool to start uploading the file right away when dropping it, not only on saving the new content entry. Of course on cancellation it should then stop the upload and delete the file.

**Comment by lauriejim** [comment]
Thank you @fl034 for this insight.
I ping @Aurelsicoko about this.
Can you please add this in this feature card - https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities
Thank you.

**Comment by fl034** [comment]
Done :-)

**Comment by tiberiumihai** [comment]
I've seen that the new media library was released. Is this ready to be used? An example would be useful. Thanks.

**Comment by lauriejim** [comment]
Hello! Can you please precise your need? What kind of example you would like.

**Comment by tiberiumihai** [comment]
I'm trying to upload some large files using strapi, while creating (multipart), or updating (not multipart). For these files the media library won't be used. Instead of that, I'll move the files from temporary directory in a hfs file system (let's say, a network drive). While uploading these large files, I would like to display a loader in my ui (an angular application).

I know that, in a nodejs application I would use { httpOptions: { reportProgress: true } }, but it doesn't seems to work with strapi backend. Do I need to configure something or add my own logic so that I can receive HttpEvents for the uploading files?

Thanks!

**Comment by tiberiumihai** [comment]
I've totally forgot to include ```{ observe: 'events' }``` in my request.

I'm using angular http client using these options in order to receive HttpEvents.
```typescript
this.http.post<any>(id, formData, {
  reportProgress: true, // These fields are required to receive HttpEvents
  observe: 'events',
}).pipe(
  map(event => {
    switch (event.type) {
      case HttpEventType.UploadProgress:
        const progress = Math.round(100 * event.loaded / event.total);
          return { status: 'progress', message: progress };
        case HttpEventType.Response:
          return event.body;
        default:
          return `Unhandled event: ${event.type}`;
      }
  })
);
```

Thanks for all the hard work guys!

**Comment by sethpkendall** [comment]
I'm also curious if it is possible to get upload progress updates from the file upload endpoint. Right now my code looks like this:
`axios.post(
      postURL,
      formData, // <-- this formData has a big file attachment
      {
        headers:{
          Authorization:`Bearer ${token}`
        },
        onUploadProgress: (progress) => progressReportFunction(progress) // <-- this updates the progress bar
      }
    ).then((response) =>{
      // this code does not run for a while
      resolve(response);
    })

const reportProgress = progress => {
    const newPercentProgress = Math.round((progress.loaded/progress.total)*100);
    setProgress(newPercentProgress);
  }`

It sort of works like this but the progress bar goes to 100% pretty fast and then doesn't resolve for much longer.

**Comment by markokhman** [comment]
Hallo guys, any updates on this one?

**Comment by raphaelkieling** [comment]
> I'm also curious if it is possible to get upload progress updates from the file upload endpoint. Right now my code looks like this:
> 
> ```
> axios.post(
>       postURL,
>       formData, // <-- this formData has a big file attachment
>       {
>         headers:{
>           Authorization:'Bearer ${token}'
>         },
>         onUploadProgress: (progress) => progressReportFunction(progress) // <-- this updates the progress bar
>       }
>     ).then((response) =>{
>       // this code does not run for a while
>       resolve(response);
>     })
> 
> const reportProgress = progress => {
>     const newPercentProgress = Math.round((progress.loaded/progress.total)*100);
>     setProgress(newPercentProgress);
>   }
> ```
> 
> It sort of works like this but the progress bar goes to 100% pretty fast and then doesn't resolve for much longer.

I'm have the same "problem" here, i'm trying upload some big videos and the progress bar went to the 100% quickly. We have any updates?

**Comment by tannynogales** [comment]
I have the same problem.. my code is like @tiberiumihai describe above, but the progress go to 100% immediately.

![image](https://user-images.githubusercontent.com/5474417/184554418-9aa6ca40-cd3e-43f9-9a74-85a556021eee.png)

Following is the componente side (I am using angular)
![image](https://user-images.githubusercontent.com/5474417/184554444-f5af25d2-c451-47a1-bc70-337975b5e075.png)

**Comment by andneuma** [comment]
Hey there, the problem seems to be still occuring. For our uploads we still experience this behaviour, we're on strapi 5.9.0 run inside a docker container. Any news on this? Maybe reopen the issue?

**Comment by alexandrebodin** [comment]
@andneuma please open a new issue this one is too old to track for us 🙏
