### ISSUE TITLE
Different results for limit -1 (REST vs GraphQL)

### ISSUE THREAD

**Issue by bartduisters** [strapi/strapi#5161]
**Describe the bug**
According to the documentation on the [`limit`](https://strapi.io/documentation/3.0.0-beta.x/content-api/parameters.html#limit) parameter, it should be possible to ignore the default result size of 100 results by setting limit to -1. This works for REST, but does not work for the GraphQL.

**Steps to reproduce the behavior**
1. Have a route with a result of more than 100 results, e.g. 150 results.
2. Have the GraphQL plugin active.
3. Through Postman, do a REST call for the given route with _limit=-1.
4. Through /graphql do a query on the same resource with limit set to -1.

**Actual behavior**
REST returns 150 results. GraphQL returns 100 results.

**Expected behavior**
I expect the same results for both the REST call as the GraphQL call (both 150 results).

**System**
- Node.js version: 10.15.2
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.6
- Database: MongoDB
- Operating system: Linux (Ubuntu 19.10)

**Comment by bartduisters** [comment]
Also, [this part of the documentation](https://strapi.io/documentation/3.0.0-alpha.x/guides/graphql.html#configurations) warns about changing the amountLimit because of performance reasons.

I guess the -1 option should be something that can be opted-in for people who are aware of this risk.

**Comment by asdutoit** [comment]
Hi @bartduisters, 
I had a similar issue and some clever guys from the Slack group gave me a workaround that worked for me.  PS, I am not sure if this is the best way forward but at least it works for now. 
In your Strapi Server folder structure "/extensions/graphql/config/settings.json", add the following:

`{
  "endpoint": "/graphql",
  "tracing": false,
  "shadowCRUD": true,
  "playgroundAlways": false,
  "depthLimit": 7,
  "amountLimit": -1,
  "shareEnabled": false
}
`

Note, if you don't have the "/graphql/config/settings.json" file, just create it and restart the server:

![Screenshot 2020-02-05 09 51 37](https://user-images.githubusercontent.com/20240370/73821675-228a2c00-47fd-11ea-9191-b514d64f43f1.png)

Hope it works for you.

**Comment by lauriejim** [comment]
Hello!  GraphQL has its own configurations.
You will also have to allow -1 for reasons explained into the docs.
Could probably be added in the docs to set this to -1 to remove the limit (like the REST API).
Will appreciate a PR for that. Thank you.
