### ISSUE TITLE
GraphQL settings.json overwrite not picked up

### ISSUE THREAD

**Issue by bartduisters** [strapi/strapi#5163]
**Describe the bug**
According to the [file structure documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/file-structure.html) `/extensions: contains the files to extend installed plugins.` and `/plugins: contains your local plugins.`.

The [GraphQL documentation](https://strapi.io/documentation/3.0.0-alpha.x/guides/graphql.html#configurations) says the extension/overwrite of the GraphQL plugins should be done in `./plugins/graphql/config/settings.json`.

However, neither work. I've tried to overwrite the amountLimit by overwriting the settings.json of the plugin in `./extensions/graphql/config/settings.json` and `./plugins/graphql/config/settings.json`.

The used settings.json file:
```json
{
  "endpoint": "/graphql",
  "tracing": false,
  "shadowCRUD": true,
  "playgroundAlways": false,
  "depthLimit": 7,
  "amountLimit": 1000
}
```

**Steps to reproduce the behavior**
1. Put the settings.json in either location.
2. Have a resource with more than 100 items.
3. Manually restart Strapi.
4. Through /graphql, do a query that matches more than 100 items.

**Actual behavior**
With the config in `./extensions/graphql/config/settings.json`.
I get back 100 items (the default setting).

With the config in `./plugins/graphql/config/settings.json`. Strapi will not boot, since there is a local plugin with the same name as an installed plugin.

**Expected behavior**
I expect to get back more than 100 items, since the `amountLimit` is set to 1000.

**Workaround**
Edit the settings.json in the node_modules package of the GraphQL plugin. This is by no means a good solution.

**System**
- Node.js version: v10.15.2
- NPM version: v6.13.4
- Strapi version: 3.0.0-beta.18.6
- Database: MongoDB
- Operating system: Linux (Ubuntu 19.10)

**Comment by thg303** [comment]
same issue here. any idea how to fix it? @bartduisters
