### ISSUE TITLE
User Permissions / Content Types Getting Wiped Periodically

### ISSUE THREAD

**Issue by Elementrat** [strapi/strapi#5164]
Heya Folks!

My team is relying heavily on Strapi in building out our product, and so far we've had an amazing experience with it. 

However, we've started running into an issue that's pretty concerning:
On some unknown interval, our live instances of strapi are forgetting about either our content types, or their associated user permission settings. This causes our live site experiences and builds to fail. 

**Repro Steps**
1. It's not yet clear what triggers it, but our (heroku hosted) instances forget about some of the content types we support. An example:  
![image](https://user-images.githubusercontent.com/1383125/73616932-3f8ce800-45ce-11ea-97ac-3bdb345ed33e.png)

When it occurs, this entire content type disappears from the Roles & Permissions view. 

No code is changing, and no deployments are happening when this occurs.

The temporary fix is simple enough: 
By running the CMS locally, we are always able to see all our content types. By manually clicking the permissions (count, find, create, etc)  for each, we are able to fix our hosted instances.

Pretty weird!

Wondering if this sounds familiar / like a known issue, or whether there might be something causing this that I'm missing. 

Thanks in advance for any insight you can provide!

_Context:_
Strapi Version: 3.0.0-beta.17.5
DB: MongoDB
Executing Instances: 
#1 - Heroku (Always Running - Live / User Instance - all requests from users on our production site route here)
#2 - Heroku (Always Running - Build Instance - all requests from our build process route here)
#3 - Local Instance (Runs ad-hoc on developer machines)

**Comment by SK-Commit** [comment]
Heroku is not recommended for usage of strapi, as Heroku forgets things, like with using file upload on Heroku instances, maybe @derrickmehaffy can elaborate this

**Comment by derrickmehaffy** [comment]
@Elementrat my guess is your project was created using the `--quickstart` option meaning it was spun up using SQLite and not MongoDB. If you check your database.json files I'm also guessing those list SQLite. Heroku has an ephemeral file system (basically means changes are not kept during dyno restarts)

Heroku also restarts those dynos every few hours or on every deploy, thus meaning if you are using SQLite your database is effectively being wiped back to the version stored in git. Likewise all file uploads are deleted unless you have the upload plugin connected to a 3rd party (AWS S3, Cloudinary, ect).

Please check your database.json files to confirm.

**Comment by Elementrat** [comment]
> Heroku is not recommended for usage of strapi, as Heroku forgets things, like with using file upload on Heroku instances, maybe @derrickmehaffy can elaborate this

Oh, we've been using it in production for awhile and were unaware of this guidance. Is this posted in the documentation somewhere? 



> @Elementrat my guess is your project was created using the `--quickstart` option meaning it was spun up using SQLite and not MongoDB. If you check your database.json files I'm also guessing those list SQLite. Heroku has an ephemeral file system (basically means changes are not kept during dyno restarts)

> Heroku also restarts those dynos every few hours or on every deploy, thus meaning if you are using SQLite your database is effectively being wiped back to the version stored in git. Likewise all file uploads are deleted unless you have the upload plugin connected to a 3rd party (AWS S3, Cloudinary, ect).
> 
> Please check your database.json files to confirm.

We are not using SQLite - we have a remote Mongo connection. We're aware of the dyno restarts & inaccessibility of persistent storage, we rely on the S3 upload provider.

**Comment by derrickmehaffy** [comment]
Can you please actually confirm that your database.json is setup properly for mongo. Because this sounds exactly like it is not (I've seen this same issue about 100 times)

As for Heroku, it's not documented because it's more a general collective bias. Heroku has extremely poor performance in testing and does not scale well.

**Comment by Elementrat** [comment]
> Can you please actually confirm that your database.json is setup properly for mongo. Because this sounds exactly like it is not (I've seen this same issue about 100 times)
> 
> As for Heroku, it's not documented because it's more a general collective bias. Heroku has extremely poor performance in testing and does not scale well.

environments / production / database.json

{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}"
      },
      "options": {
        "authenticationDatabase": "<redacted - name of a mongo instance>",
        "ssl": false
      }
    }
  }
}

**Comment by derrickmehaffy** [comment]
@Elementrat are you passing the `NODE_ENV` in your heroku config to ensure it is using the production environment?
