### ISSUE TITLE
Run strapi as non-root user

### ISSUE THREAD

**Issue by bellaxie** [strapi/strapi#5165]
Hi there,

I'm having trouble to run strapi as non-root user, the folders and files under web root set 'root' as owner, permission is 755. I've also set the non-root user owner of these 2 folders   'plugins/graphql/config/generated' and 'admin/admin/src/config/plugins.json' which I got from the error msg when starting the service. But it still doesn't work. I got this msg which doesn't help much.

`[2020-02-03T00:42:49.313Z] error EACCES: permission denied, unlink '/var/www/srscms-dev.vmlaustralia.com/public_html/admin/admin/src/config/plugins.json'
{ [Error: EACCES: permission denied, unlink '/var/www/srscms-dev.vmlaustralia.com/public_html/admin/admin/src/config/plugins.json']
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path:
   '/var/www/srscms-dev.vmlaustralia.com/public_html/admin/admin/src/config/plugins.json' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-cms@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-cms@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pm2user/.npm/_logs/2020-02-03T00_42_49_332Z-debug.log
`

If I set owner of the whole web root folder to the non-root user, then it worked. I wonder if the non-root user which runs the nodejs process really need write access to all the files and folder? For security concerns, I'd like to restrict the permission of the user running the service process, so it's an extra level of security in place rather than leaving it all to the web app to control security.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
