### ISSUE TITLE
Error command cli strapi new 

### ISSUE THREAD

**Issue by tiagotcunha** [strapi/strapi#517]
**Node.js version**: v8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.8.3

**Operating system**: windows 10

**Do you want to request a *feature* or report a *bug*?**
Bug.
Create project command not working on windows.

**What is the current behavior?**

cli command "strapi new" fails with error 'rm' is not recognized as an internal or external command,
operable program or batch file.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

Install strapi package globaly and run command cli for create project "strapi new myProject"

**What is the expected behavior?**

**Comment by lauriejim** [comment]
It's fixed here on master https://github.com/strapi/strapi/pull/469, will be published soon.

**Comment by mittalyashu** [comment]
Facing the same issue.

**Comment by Arcath** [comment]
A quick fix is to open `NODEINSTALL\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js` 

and change line 210 to:

`execSync(`rmdir /S /Q ${scope.rootPath}`);`

This was with `3.alpha.8.3`

**Comment by mittalyashu** [comment]
> A quick fix is to open NODEINSTALL\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js

And where can I find this NODEINSTALL directory?

**Comment by d8vjork** [comment]
Why is it closed? I still cannot create a new strapi site in Windows PS (W10).

Fails trying a rm

![image](https://user-images.githubusercontent.com/2331052/35562313-42c8490e-05b3-11e8-8241-814d0fc67122.png)
