### ISSUE TITLE
GraphQL is acting really slow compared to REST

### ISSUE THREAD

**Issue by roelbeerens** [strapi/strapi#5182]
**Describe the bug**
Original bug here: https://github.com/strapi/strapi/issues/4080

I've noticed some slow performance whenever the amount of relations started growing of an entry. I thought the fix mentioned in #4080 already fixed this, but after some testing, I've come up with the following results (same query/same output fields):

REST: 110-120ms
GraphQL: 900-910ms

That's a big difference. After reading the original issue, I started to dig through the graphql plugin and started fiddling with the populate settings on line 155 in services/Loader.js (as already mentioned in the original post). Setting the populate to a hard coded [] results in a huge boost:

GraphQL: 120-140ms

The funny thing here is, the fields that originally are populated in the params, are still queryable after setting the populate to [].
However, this does not seem to have effect when deep filtering. I not sure why, but i'll try to figure that out sometime this week.

**Steps to reproduce the behavior**
1. Go to services/Loader.js in the graphql-plugin
2. Set the populate option on line 155 to []
3. Fire up a GraphQL sandbox
4. Witness the speed increase.

**Expected behavior**
A performance of GraphQL which is near the same as the REST performance.

**System**
- Node.js version: 10.17.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: MongoDB (latest Docker image)
- Operating system: MacOS 10.15.2

**Additional context**
It seems the impact on performance is happening when there are many-to-* relations on a content type. I'm not sure why setting an empty array as the populate value still results in populated fields (or are those populated on request when stating them in the query?). I haven't fully debugged the code, but this was the result of a quick test.

I'll try to look into this issue this week if i've got some spare time. Maybe I can help around :)

**Comment by JelmerV-WFC** [comment]
I have exactly the same problem. Especially when you have multiple many-to-* relations it sometimes takes up to a couple of seconds to load. When I check the tracing, it takes a lot of time to receive the relations indeed.

**Comment by adim** [comment]
I have also performance issues with populate fields from other documents.
my query is pulling 2000 documents from one model and populate it with 4 other documents.
**statistics:**
2000 documents with 4 populate: ~10 seconds
2000 documents with 1 populate: ~3.5 seconds
any idea how I can improve it?

**System**
    Node.js version: 12.13.0
    NPM version: 6.13.4
    Strapi version: 3.0.0-alpha.26.2
    Database: MongoDB

**Comment by JelmerV-WFC** [comment]
@adim Are you on alpha? Please update to beta and test again. Alpha is not supported anymore.

**Comment by JelmerV-WFC** [comment]
@derrickmehaffy Can you confirm you have the same issues with MySQL? 

@alexandrebodin It looks like the more relations a content type has the slower the queries become.

I have a deal content type with the following relations:
    - Accommodation: accommodation (hasOne)
         - Destination: destination (hasOne)
    - Destination: destination (hasOne)
         - Destination: parent (hasMany)
         - Destination: children (belongsToMany)
    - Website (hasOne)
         - Contains of only 3 simple string fields

When I query deals with a limit of 20 this is how long it takes to fetch the relations according to GraphQL tracing:
    - Accommodation: 250-400 ms
    - Destination: 1000-1500 ms
    - Website: 140-200 ms

The query itself is around 2000-2600 ms in total.

**Comment by roelbeerens** [comment]
This morning I've dug a bit deeper with the tracer enabled. Let me explain my situation first:

I have an entity type called 'Asset' which has a many-to-many relation with 'Tag'.
A normal GraphQL query looks like this: query { assets { name, tags { name } } }

What I think is going on here is that, as tags is also related to assets and vice-versa, assets are also populated on tags. I did not see any deeper connections in when debugging, so there is no assets > tags > assets > tags etc etc. Just the assets > tags > assets. As mentioned, for some reason, clearing the populate for the tags relation, gives a huge speed boost. You would think with that, you can't query assets anymore within tags, but actually, on request, those field are populated when needed (which makes sense).

I think the following should be checked:

If the parent relation is equal as the child relation, you shouldn't populate it. Logically you already have that data, but if needed, it will be populated on request.

Here are some tracing results:

With population:

![Screenshot 2020-02-05 at 11 02 34](https://user-images.githubusercontent.com/5938477/73832298-35562e00-4808-11ea-884f-d017e417e8fc.png)

Without population:

![Screenshot 2020-02-05 at 11 03 10](https://user-images.githubusercontent.com/5938477/73832319-3dae6900-4808-11ea-9e14-71494f4d8591.png)

With population on request:

![Screenshot 2020-02-05 at 11 12 18](https://user-images.githubusercontent.com/5938477/73832403-646c9f80-4808-11ea-8090-101f16d6e239.png)

**Comment by alexandrebodin** [comment]
Hi guys,

Right now the graphql plugin is pretty "naive" when it comes to populating. It just uses the default populations which is less than optimal at best.

 I'm going to try and review this behavior during the next months to improve the performances and reliabilty.

As soon as we have some to give you for test I will let you know ;)

**Comment by JelmerV-WFC** [comment]
It may also be a good idea to test with a bigger test set. I have, for example, one content type with more than 10.000 items in it. This content type has multiple different type relations with other content types. Even the simple hasOne relations become very slow.

**Comment by roelbeerens** [comment]
Thanks for the reply @alexandrebodin. Thank you for your honesty and estimated timeframe.

**Comment by faugstad** [comment]
Just to chime in: we're also experiencing this problem. 
I'll keep my fingers crossed for a fast solution.

**Comment by MANTENN** [comment]
I have an issue as well with the rest API and GraphQL. I am not sure how walmart managed to scale this. I built a custom GraphQL server before using this with NodeJS and PostgresQL, it was far more performant. I think with ORMs the objects do not need to be constructed when fetching the data(find, count, etc). 

It takes a good 5s to load the response--Rest and GraphQL.

I am using:
- Strapi 3.0.0-alpha.26.2
- MySQL 8.0.19 x86_64 (Homebrew) 
- macOS 10.14.4 (18E226)
- CPU: i5 8600K
- RAM: 16GB DDR4
- HDD: Corsair LX 256GB SSD

**Comment by derrickmehaffy** [comment]
`Strapi 3.0.0-alpha.26.2` @MANTENN Alpha hasn't been supported in over a year now.

**Comment by MANTENN** [comment]
@derrickmehaffy Got it. I will upgrade to beta and prerelease, and see if I see any performance improvements.

**Comment by MANTENN** [comment]
So I removed the belongsToMany relationship and set it to has one x. The performance is significantly improved. I'm guessing it's a circular reference.

**Comment by abdonrd** [comment]
There are no news here, right?

**Comment by derrickmehaffy** [comment]
Hi @abdonrd not currently no this is something we will be looking into with the new database backend review for v4.

**Comment by derrickmehaffy** [comment]
I am going to close and lock this thread in favor of our global tracking issue here: https://github.com/strapi/strapi/issues/8552

If anyone has additional comments please place them on the tracking issue, we are doing this to help centralize the issue and make it clearer where various related bug reports stem from the same source.
