### ISSUE TITLE
Showstopping Migration Beta 18.7 Error

### ISSUE THREAD

**Issue by Elementrat** [strapi/strapi#5183]
Heya, currently experiencing a critical issue.

I followed this migration guide to move my team from 17.5 to 18.7
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html

When trying to load any content type, I'm just getting:
![image](https://user-images.githubusercontent.com/1383125/73784080-ad115380-4749-11ea-952a-cd2a21ca3f00.png)

- We didn't have any existing repeatable fields / groups.

DB: Mongo

Any insight or help here would be extremely appreciated.

**Comment by roelbeerens** [comment]
Have you tried removing the node_modules, build and .cache folder? That actually solved this issue for me.

**Comment by roelbeerens** [comment]
Glad I could help :) I stumbled upon this as my local providers weren't updating on change (which required a full node_modules wipe). This made me think, and with that I could successfully update to the latest version. 

I agree this should be added to the upgrade docs.

**Comment by derrickmehaffy** [comment]
Marking as closed as issue resolved (It's a general common knowledge to delete the node_modules btw 😉 )
