### ISSUE TITLE
Allow admin authentication through a provider

### ISSUE THREAD

**Issue by BenMcH** [strapi/strapi#5188]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

Our IT security group manages users centrally through Active Directory and do not want to provision new credentials for Strapi admins. The ability to add a custom provider, like is available for standard users, would be an ideal solution to this problem. 

This would mean that we would also need the ability to restrict access based on a role/permission that we could configure within Strapi.

**Comment by lauriejim** [comment]
Thank you for this insight, ping @Aurelsicoko

**Comment by Aurelsicoko** [comment]
@BenMcH Sadly, it's not in our roadmap for this year, but we will considering it then ;)

**Comment by agustinflorez** [comment]
@Aurelsicoko is there a way we can develop this feature ourselves? 
@BenMcH Did you find a workaround?

**Comment by BenMcH** [comment]
@agustinflorez nope, unfortunately we ended up having to ditch strapi and rolled a custom solution instead

**Comment by BenMcH** [comment]
If you wanted to develop the feature yourself, you would need to modify strapi-admin to have a provider config. Should be doable, just tedious

**Comment by agustinflorez** [comment]
@BenMcH Got it, thanks!

**Comment by derrickmehaffy** [comment]
Technically already exists, SSO, but requires a gold license. You are welcome to create your own if you wish without using our SSO code but unlikely we will add providers to the admin outside of SSO
