### ISSUE TITLE
Content Types ending with "s" can't be saved

### ISSUE THREAD

**Issue by eiskalteschatten** [strapi/strapi#5190]
**Describe the bug**
When creating a content type that ends in the letter "s", Strapi automatically creates the table in the database using "es" for the plural. The problem is that if you have a component within that content type, the column with the ID added to the component table is correct without the "es", but Strapi looks for it just without the "s". 

For example:
Content Type: "about_us"
Table name: "about_uses" (sounds funny, but whatever)
A component is added to the "about_us" content type. In the component table, the "about_us_id" column is added, but Strapi looks for the column "about_us**e**_id".

**Steps to reproduce the behavior**
1. Create type: "about_us"
2. Create a component and add it to the content type.
3. Start Strapi and create an item of content type "about_us".
4. Try saving. An error is returned.

**Expected behavior**
The item should be saved and Strapi should look for the column without the "e" that it added to the name.

**System**
- Node.js version: 10.18.1
- Strapi version: 3.0.0-beta.18.6
- Database: Postgres
- Operating system: Linux

**Comment by lauriejim** [comment]
Hello @eiskalteschatten !
You are right! Thank you for reporting this issue.

**Comment by eiskalteschatten** [comment]
No problem! I'm glad you were able to understand the description because I had difficulties finding a good way to describe it.
