### ISSUE TITLE
Multiple versions of dom-helpers found

### ISSUE THREAD

**Issue by freemh** [strapi/strapi#5194]
**Describe the bug**

I'm trying to customize the administration panel, so after a `yarn develop --watch-admin` I'm getting a warning: 

```
 WARNING  Compiled with 1 warnings
dom-helpers
  Multiple versions of dom-helpers found:
    3.4.0 ./~/dom-helpers from ./~/react-transition-group/CSSTransition.js
    5.1.3 ./~/react-virtualized/~/dom-helpers from ./~/react-virtualized/~/dom-helpers/cjs/scrollbarSize.js

```

**System**
- Node.js version:  **v12.4.0**
- NPM version: **6.13.6**
- Strapi version: **3.0.0-beta.18.7**
- Database: **MongoDB**
- Operating system: **Mac OS**

**Comment by lauriejim** [comment]
Hello! Can you please provide the exact steps you did.
It will help me to understand what you did!

**Comment by freemh** [comment]
@lauriejim After running the command `yarn develop --watch-admin`, I get a warning telling me that **Webpack** found out a different version of the `dom-helpers` package on both `react-transition-group` and `react-virtualized` which they are both dependencies of `strapi-admin`.

I do check `package.json` on `react-transition-group` which includes the version `3.4.0` of the `dom-helpers`:

```json
...
"dependencies": {
  "dom-helpers": "^3.4.0",
  "loose-envify": "^1.4.0",
  "prop-types": "^
},
...
```
And we've a different version `^5.0.0` of the `dom-helpers` on the `package.json` of the `react-virtualized`:

```json
...
"dependencies": {
  "babel-runtime": "^6.26.0",
  "clsx": "^1.0.1",
  "dom-helpers": "^5.0.0",
  "loose-envify": "^1.3.0",
  "prop-types": "^15.6.0",
  "react-lifecycles-compat": "^3.0.4"
},
...
```

And this is what I'm getting as a result of the `yarn develop --watch-admin`:

```json
 WAIT  Compiling...                                                      2:48:08 PM

 WARNING  Compiled with 1 warnings                                       2:48:10 PM

 warning  

dom-helpers
  Multiple versions of dom-helpers found:
    3.4.0 ./~/dom-helpers from ./~/react-transition-group/CSSTransition.js
    5.1.3 ./~/react-virtualized/~/dom-helpers from ./~/react-virtualized/~/dom-helpers/cjs/scrollbarSize.js

Check how you can resolve duplicate packages: 
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle
```

So, the cause of the problem is different versions of the `dom-helpers` which cause a duplication when **webpack** try to bundle everything.

**Comment by lauriejim** [comment]
Thank you for these details, I ping @soupette  about that.

**Comment by soupette** [comment]
Hi @freemh thanks for spoting the issue you are right we have 2 different version of `dom_helpers`, but I don't think that this is major issue at the moment as the administration panel still runs correctly. I have checked the latest version of [react-transition-group](https://github.com/reactjs/react-transition-group) and it uses the same version of the dependency as `react-virtualized` so we will upgrade this package soon so the warning disappears.

**Comment by diogotcorreia** [comment]
Can confirm this is still happening on beta-19.3

**Comment by worapolburaphan** [comment]
@soupette This issue still happening same.

**Comment by wemod123** [comment]
Anyone solved this issue?

**Comment by rudral** [comment]
I also have an error like this after typing `yarn develop --watch-admin` in terminal.

```
...
Multiple versions of @buffetjs/hooks found:

   3.0.5 ./~/@buffetjs\core/~/@buffetjs\hooks from ./~/@buffetjs\core\dist\components\TimePicker\index.js

   3.0.6 ./~/@buffetjs\hooks from .\.cache\plugins\strapi-plugin-upload\admin\src\containers\HomePage\index.js

Check how you can resolve duplicate packages: 
https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle
```

System

- Node.js version: v12.13.1
- NPM version: 6.14.5
- Strapi version: 3.0.0-beta.20.3
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
@soupette @HichamELBSI do we need to keep this open?

**Comment by soupette** [comment]
I am closing it.
