### ISSUE TITLE
Admin Console- Create a new Component tutorial does not match expectation nor explanation

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#5196]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Is it possible that Create a new Component called, "Hours of Operation" within the Admin console only available for mongo DB ?
This relates to this guide: https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start-tutorial.html#_4-create-a-new-content-type-called-category
I can't get the past a validation error on the field: "Select a category or enter a name to create a new one"

Is there anything is missing in this guide ?

IF not can you please briefly what would be the files to change or add in order to add a new component to make it available to the admin console? 
I am currently digging to find out this but any help will be appreciated.

Thanks.

**Comment by jmchza** [comment]
By the way it seems externally complex the idea of building a new react component to add it into the content-type-builder plugin in order top be used from the FormModal menu.
Please correct me if am wrong, I am more than happy to know that my perception is wrong and that there is something missing that could simplify this.
I though initially the idea of being a flexible read admin console was to have the flexibility to just build your react component and plug it in. 
I believe building a new plugin would not simplify this, but instead I meant to extend the content-type-builder plugin.
Thanks.

**Comment by lauriejim** [comment]
Hello! Can you please precise your question, I'm not sure to follow what you are trying to do.
The tuto works fine, I just tried this section of the doc and look fine - https://www.loom.com/share/e287f6a948d74ac9a824d4418d40211b

**Comment by jmchza** [comment]
Hi @lauriejim thank you very much for your response.
Yes I have tried that with the exact same variable name, (I am talking about the one called hours) and that is the only way to get that component saved.
So now my understanding was that I could you use this approach to create a component of any nature i.e: I could create one that displays avatars and the user could select any amount of avatar into a specific model page.

So I guess now that I dag a bit deeper, is that this is only a component for hours. 
Could I use this approach to create more components? If so, how would that be? Is there anything I could gab to start with and go from there ?

Thanks heaps and I happy to keep helping the pattform to continue growing.

**Comment by lauriejim** [comment]
Hello! I'm not sure to understand your question.

**Comment by lauriejim** [comment]
__
