### ISSUE TITLE
How to create migration file use strapi-generate-migrations

### ISSUE THREAD

**Issue by toraihand** [strapi/strapi#5197]
Hi everybody, 

I installed strapi-generate-migrations and try to create migration file use "strapi migrate:make <connectionName> <migrationName>". But it seem migrate: make doesn't exists in strapi command.
Anyone can introduce me how to use it?

Thank you

**Comment by quanghuy9289** [comment]
Same question, could anyone can help?

**Comment by derrickmehaffy** [comment]
This package has not been maintained in almost 2 years, it was depreciated some time ago with no plans to continue work on it in the future:

![image](https://user-images.githubusercontent.com/8593673/74002967-2bc6e600-492e-11ea-8146-e429b5edf705.png)

Marking as closed as this package is no longer supported.
