### ISSUE TITLE
call dropCollection from mongoose

### ISSUE THREAD

**Issue by dragouf** [strapi/strapi#5199]
I wanted to clear the database collections before to insert data. I tried with :

`await strapi.query('acollection').delete({ });`

but it seems not to work with big collection. 
Normally with mongoose we should be able to do that :

`mongoose.connection.db.dropCollection('acollection', function(err, result) {...});`

so, how to access this with strapi ?

**Comment by lauriejim** [comment]
Hello! This is not possible for now, I just created a PR to allow the access to the Mongoose instance via `strapi.connections.default`
With that, you will be able to access your `dropCollection` function.
