### ISSUE TITLE
Unintentionally moving text editor cursor Korean characters

### ISSUE THREAD

**Issue by ESnark** [strapi/strapi#5204]
**Describe the bug**
If you enter a Latin alphabet after a few Korean characters including spaces, the cursor moves to the beginning of the line.

**Steps to reproduce the behavior**
1. Go to a text editing page.
2. Input Korean characters with two or more spaces.
3. Enter Latin alphabet.

**Expected behavior**
The cursor should be at the end of the line.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/31977180/74082587-e1b14200-4a9e-11ea-8d6a-e24c9a477364.gif)

**System**
- Node.js version: v12.14.1
- NPM version: v6.13.4
- Strapi version: v3.0.0-beta.18.7
- Database: SQLite (I guess this is the default option of `--quickstart`, correct?)
- Operating system: macOS 10.15.3 (Catalina)

**Comment by ESnark** [comment]
Same in Strapi v3.0.0-beta.20
The problem only occurs in Firefox and it's fine in Chrome.

**Comment by derrickmehaffy** [comment]
shouldn't be a problem in v4 with the new editor
