### ISSUE TITLE
error ConnectorError: connector "strapi-hook-mongoose" not found: Cannot find module 'strapi-connector-strapi-hook-mongoose'

### ISSUE THREAD

**Issue by lawrence-edmondson** [strapi/strapi#5206]
I got this error in strapi and had to jump through a few hoops to solve it. If you're getting this error there's nothing wrong with your mongoose configuration. I'm using node 10.15.3 and npm 6.4.1 and Strapi 3.0.0-beta.18.3 https://github.com/strapi/strapi/releases/tag/v3.0.0-beta.18.3

The problems I encountered were with the Strapi codebase. 
The first issue was with Strapi reading two of the enumerations I had in my models file.
In my `/api/artists/models/Artists.settings.json` file I had the following 

    "genres_new": {
      "enum": [
        "hip hop",
        "r&b",
        "pop",
	"dance"
      ],
      "type": "enumeration"
    },"

I had to remove the `&` from `r & b` and make it `r and b`

    "genres_new": {
      "enum": [
        "hip hop",
        "r and b",
        "pop",
	"dance"
      ],
      "type": "enumeration"
    },"

I also had an enumeration with a series of integers from 1..10 which I had to remove completely.

After making these changes I upgraded to v3.0.0-beta.18.3 by doing the following:

1. Update your package.json dependencies

```
"dependencies": {
    "strapi": "3.0.0-beta.18.3",
    "strapi-admin": "3.0.0-beta.18.3",
    "strapi-connector-mongoose": "3.0.0-beta.18.3",
    "strapi-plugin-content-manager": "3.0.0-beta.18.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.3",
    "strapi-plugin-email": "3.0.0-beta.18.3",
    "strapi-plugin-graphql": "3.0.0-beta.18.3",
    "strapi-plugin-upload": "3.0.0-beta.18.3",
    "strapi-plugin-users-permissions": "^3.0.0-next.41",
    "strapi-utils": "3.0.0-beta.18.3"
  }

```
2. Update the modules, clear your cache and build directories

```
     npm install strapi-connector-strapi-hook-mongoose 
     npm install -g install-peerdeps
     npm install
     npm audit fix
     rm -rf .cache
     rm -rf build
     npm run dev
```

I then got the following error

    error TypeError: fn is not a function
        at execBootstrap (.../src/node_modules/strapi/lib/Strapi.js:381:15)
        at Strapi.runBootstrapFunctions (.../src/node_modules/strapi/lib/Strapi.js:399:12)
        at process._tickCallback (internal/process/next_tick.js:68:7)

I fixed it by following the instructions here [Compile error when starting strapi in development mode #4015][1]

I was then able to start my Strapi server
```npm run start ```
 
  [1]: https://github.com/strapi/strapi/issues/4015

**Comment by derrickmehaffy** [comment]
Please see the migration guide as it explains what you need to do: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#upgrading-your-dependencies

"strapi-connector-mongoose": "3.0.0-beta.18.3",

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
