### ISSUE TITLE
Admin Panel is a Blank Page when run behind nginx

### ISSUE THREAD

**Issue by faztp12** [strapi/strapi#5207]
**Describe the bug**
Strapi admin panel doesnt work when it is ran behind a nginx reverse proxy
Both `npx strapi develop` and `npx strapi start` behaves similarly
It works fine when not behind nginx

![image](https://user-images.githubusercontent.com/12441615/74095950-36e06880-4b1e-11ea-8ed6-75af7ff4307c.png)

**Steps to reproduce the behavior**
1. Create a new strapi project, `npx create-strapi-app my-app --quickstart`
2. Build and start strapi `npx strapi build`, `npx strapi start`
3. Setup nginx
```
server {
	listen                       80;
	listen                       443;
	root                         /home/--------------------/application-server;

	server_name
	api.-------------.com;

	ssl                          on;
	ssl_certificate              -------------------.cert;
	ssl_certificate_key          --------------------.pem;
	ssl_session_timeout          5m;
	ssl_protocols                TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers                  "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";
	ssl_prefer_server_ciphers    on;

	location / {
		proxy_pass                  http://localhost:1337/;
		proxy_http_version          1.1;
		proxy_set_header            X-Forwarded-Host $host;
		proxy_set_header            X-Forwarded-Server $host;
		proxy_set_header            X-Real-IP $remote_addr;
		proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header            X-Forwarded-Proto $scheme;
		proxy_set_header            Host $http_host;
		proxy_set_header            Upgrade $http_upgrade;
		proxy_set_header            Connection "Upgrade";
	}

	#                            set client body size to 2M #
	client_max_body_size         2M;

	location = /favicon.ico {
		log_not_found               off; access_log off;
	}
	location = /robots.txt {
		log_not_found               off; access_log off; allow all;
	}
	location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
		#                           expires max; # Cache control
		log_not_found               off;
	}
}
```
4. Admin panel wont work as expected

**Expected behavior**
Admin panel should work properly

**Screenshots**
- Chrome Network Tab
![image](https://user-images.githubusercontent.com/12441615/74096046-8bd0ae80-4b1f-11ea-85f8-d03561d5ec1f.png)

- curl directly onto strapi port works!
(9051 here, not 1337, nginx is set to 9051 actually)

![image](https://user-images.githubusercontent.com/12441615/74096098-3779fe80-4b20-11ea-868c-fbd2367511bf.png)

- Setting the proxy in server.js

![image](https://user-images.githubusercontent.com/12441615/74096440-2e3f6080-4b25-11ea-800d-628aca2d2fc6.png)

**System**
- Node.js version: v12.15.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: sqlite
- Operating system: ubuntu-server 18.04

Thank you :)

**Comment by ITninja04** [comment]
@faztp12 please review the deployment guide on the wiki:
https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#configuration

**Comment by faztp12** [comment]
@ITninja04 Thank you for the response.
I have validated my configuration with the one mentioned in the DigitalOcean Deployment section of the document you have linked me to, still no luck 😢

**Comment by faztp12** [comment]
The following block was the culprit 🤦‍♂ 🤦‍♂ 
```
location ~* \.(css|gif|ico|jpeg|jpg|js|png)$ {
  # expires max; # Cache control
  log_not_found               off;
}
```
