### ISSUE TITLE
Creating a required field when data already exist

### ISSUE THREAD

**Issue by alex067** [strapi/strapi#5211]
**Describe the bug**
After updating the user content type, adding in a required date field and clicking "Save," Strapi attempts to restart but fails. An error is produced:

[2020-02-09T17:08:37.518Z] error Impossible to register the 'user' model.
[2020-02-09T17:08:37.519Z] error error: column "Birthdate" contains null values

This is without attempting to add a new user. This happened directly after I added a new date type field to the User content type.

Strapi is unable to start again. 

**Steps to reproduce the behavior**
1. Go to Content type builder
2. Click on User
3. Add a date field content type, required type
4. Click save

**Expected behavior**
Strapi restarts to save the changes, and loads back up just fine.

**System**
- Node.js version: v10.14.1
- NPM version: 6.4.1
- Strapi version: Unsure
- Database: Postgres running on docker container
- Operating system: Strapi is on windows 10, postgres is on a docker container using official image.

**Comment by lauriejim** [comment]
Hello!

This issue is "normal" but we have to not let you validate your form in this case.

If you have already some entries in your database and you are adding a new required field, all your previous entries don't have value for this new attribute. So it is `NULL` and not work with the `required` (NOT NULL) constrains.

What would be the best behaviour for you?
An alert message that tells you you can't do this action, or be able to apply a default value for entries that are already created, or something else...

**Comment by alex067** [comment]
I see what the issue is. 

I think the best thing is for the CMS to abstract as much as it can, so we don't have to manually alter the table and remove the required column.

A field that lets us put default values to current entries would be great. That way the CMS can avoid having us go into the db and manually alter the table,

On a side note: I tried going into my postgres instance and look for the required field in my users model, and couldn't find it. How would we manually remove this required column? It's a field added to the users content type.

**Comment by jojoucsd** [comment]
I run in to similar issue, added a required field in Dev table and when deploy to production the error column of 'xyz'  is "null" occur.  The build is success but strapi is not starting. 

I end up roll back my build and added the table on my production table instead. Which is not really desired 

Is there a better way to do this or work around ? Thanks

**Comment by ancashoria** [comment]
I'm running into this issue too. Seems like a big gotcha for beginners.

**Comment by lauriejim** [comment]
Hello! Yes I agree!
We have not the solution we will implement for that for now.
But the subject is well defined.

**Comment by lauriejim** [comment]
The app is no longer crashing - we are displaying an error in the terminal.
Then you will have to manually migrate your data to fix the contrains
