### ISSUE TITLE
Dependencie error while using ``npx create-strapi-app``

### ISSUE THREAD

**Issue by Fefke** [strapi/strapi#5213]
**Describe the security issue**
I tried to quikstart with the  
```npx create-strapi-app bloggiblogblog --quickstart```
command and got the (Code Snippets - 1.) error...

**Screenshots**

**Code snippets**
1.  
```npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm ERR! Unexpected end of JSON input while parsing near '...= 6.0.0"}},"3.0.0-alp'
```

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: <span style="color:red">unuseable ... idk</span>
- Database: -
- Operating system: W10

**Additional context**
the boom rep. changed it's name to hapi/boom;  
intl-realativeform is deprecated;  
core-js is no longer maintained - because of 2 much issues;  
hoek is available under hapi/hoek;  
mailcomposer is unmaintained;  
popper.js renamed itself to propperjs/core;  
buildmail is unmaintained;  

Please fix this install file and the dependencies <3

**Comment by derrickmehaffy** [comment]
These are expected for now, there is no critical security issues with those depends at the moment. If you would like to assist in fixing them please submit a pull request.

For now I am marking this issue as closed as it does not follow the bug report template. All security issues should be sent according to the [security policy](https://github.com/strapi/strapi/blob/master/SECURITY.md)
