### ISSUE TITLE
Cannot create content with name 'Object' 

### ISSUE THREAD

**Issue by jonasfrey** [strapi/strapi#5216]
After saving a new content with the name 'Object' ,
 the GUI says 

"The restart takes longer than expected
The server should have restarted, please check your logs in the terminal.", 

and the console says 
"[2020-02-10T08:30:19.758Z] error Impossible to register the 'object' model.
[2020-02-10T08:30:19.763Z] error Object.create is not a function"

When i do the command  ``` strapi start ```
i cannot start starpi anymore the console says again 
"[2020-02-10T08:33:42.918Z] error Impossible to register the 'object' model.
[2020-02-10T08:33:42.922Z] error Object.create is not a function"

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
