### ISSUE TITLE
How can I control multiple editing post

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#5223]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
How can I control multiple editing of a Content by Mutiple Users 

**Your suggestions for this topic**
Page Locking / Alerting User B that User A is Currently editing the content .Do you wish to proceed

**Screenshots**
Some Reference
![Screenshot from 2020-02-11 16-49-43](https://user-images.githubusercontent.com/2913281/74232408-bae94a80-4cee-11ea-8708-b4b3499b8af4.png)

**Code snippets**

**Additional context**
I have Blog which has 12 Slots and Each Slot is edited by different people. Need a option to Tag this content as "Apply Lock" . If applied then on Admin we need to alert a User if the Edit Option is clicked for the content

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```
