### ISSUE TITLE
Any way to export and import schema / structure from one environment to another

### ISSUE THREAD

**Issue by anandagrawal84** [strapi/strapi#5230]
**Describe the topic**
We are working with strapi on multiple environments, is it there any way to promote content type schema changes or content changes from one environment to another?

**Comment by derrickmehaffy** [comment]
Please see the following planned feature request, ETA is Q4 2020: https://portal.productboard.com/strapi/1-public-roadmap/c/12-migrate-across-environments

**Comment by lauriejim** [comment]
Hello! You data schema is based on your files (./api/**/models/**.settings.json)
So you just have to push your app in production and the schema will be updated.
About the data migration - refer to the link that sent Derrick.

**Comment by 0xAl3xH** [comment]
For posterity, as of the time of writing, copying `src/api/*` to the newly setup instance works in transferring the schema
