### ISSUE TITLE
Size Limit comparaison issue

### ISSUE THREAD

**Issue by 7mioda** [strapi/strapi#5233]
when uploading a file even if its size is less then the size the limit the response's status was 400
and it was due to the size limit
file size = 853.40
limit size =  5000000000

if i changed the code to parse the tow numbers it will work correctly

**Code snippets**
if (parseFloat(file.size) > parseFloat(config.sizeLimit)) {

**System**
- Node.js version: 10.15.0
- Strapi version: 3.0.0-beta.17.5
- Database: mongodb
- Operating system: linux

**Comment by derrickmehaffy** [comment]
Can you submit a pull request @7mioda ?

**Comment by 7mioda** [comment]
okey @derrickmehaffy

**Comment by lauriejim** [comment]
Hello! I was not able to reproduce.
Can you give me more details about your issue and steps to reproduce please.
