### ISSUE TITLE
Admin development watcher broken when the project root path contains keywords

### ISSUE THREAD

**Issue by jeremh2** [strapi/strapi#5234]
**Describe the bug**
When base directory containing the strapi app have ‘admin**’ or ‘extensions’ somewhere in its path (e.g. ~/administrator/foo/strapi/), the admin development watcher script does not copy files to the appropriate cache directory, breaking the live rebuild. 

**Steps to reproduce the behavior**
1. Create a folder containing 'admin' or 'extensions' keywords
2. Create a new strapi app in this folder using ```yarn create strapi-app my-project --quickstart``` command
3. Launch admin development server using ```yarn develop --watch-admin``` command
4. Eject a file to customize the admin app (e.g. ```admin/src/containers/HomePage/index.js```)
5. Modify the created file and save it

**Expected behavior**
The admin home page should reflect the changes made in the ejected file. 
The modified file should have been copied to the .cache folder with the same subpath of the origin file (```.cache/admin/src/containers/HomePage/index.js```)

**System**
- Node.js version: 10.19.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: sqlite
- Operating system: Mac OS 10.14.6

**Comment by jeremh2** [comment]
Hi Strapi guys ! 
Hope you are well since you moved from Blacksmith offices. 

Recently started using Strapi for a side project and I'm impressed of what it can do !
I've submitted a small fix for a bug I ran into when customizing the admin. 
Don't hesitate to tell me if the fix needs changes before being merged. 

See you ;)

**Comment by lauriejim** [comment]
Hi! Thank you for reporting this issue, @soupette will have a look at this topic and the PR you did.
And thank you for contributing to the project.

Yap we are going well, new office rue St-Denis and the team is growing.
Thank you for your feedback,  we will appreciate your feedback about your experience with the project.
It will help to improve it in the right way. Feel free to share it with us.
