### ISSUE TITLE
Content-manager failed to load entries from MongoDB Azure CosmosDB

### ISSUE THREAD

**Issue by nduyduc** [strapi/strapi#5238]
I'm trying to connect strapi with Azure CosmosDB database. Strapi runs but it does not show any entries in the content-manager tables.

As I discovered, GET /content-manager/explorer/application::[collection_name].[collection_name]?_limit=10&**_sort=id**:ASC&_start=0 returns an empty array while it should return an array of entries.
When I tried GET /content-manager/explorer/application::[collection_name].[collection_name]?_limit=10&**_sort=_id**:ASC&_start=0, it returns expected array. 
Might be a problem with id and _id while querying data.

**Steps to reproduce the behavior**
1. Change database config to Azure CosmosDB database
2. Npm run develop
3. Go to any admin panel's content-manager table

**Expected behavior**
All entries in the database are shown in the content-manager tables.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.7
- Database: Azure CosmosDB mongodb 3.6
- Operating system: windows 10

**Comment by lauriejim** [comment]
We removed the `_id` so this is no more an issue normally.
