### ISSUE TITLE
MySQL configuration at Auth & Permissions do not show

### ISSUE THREAD

**Issue by lucasdu4rte** [strapi/strapi#524]
**Node.js version**: v9.4.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.8

**Operating system**: Ubuntu 17.10

**Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**What is the current behavior?**
In the configuration of strapi using MySQL, the permissions do not appear screen, and also the * CRUD *

**If the current behavior is a bug, please provide the steps to reproduce the problem**
 -- Install strapi
 -- Configure MySQL database
 -- Start Strapi Server
 -- Add table User manually in database
 -- Create new user
 -- Go to page Auth & Permissions

**What is the expected behavior?**
It does not list the standard roles of strapi, and it is not possible to add new role

![captura de tela de 2018-01-26 09-57-00](https://user-images.githubusercontent.com/22087517/35439228-fd50bb0c-0280-11e8-953d-d195b97a03c4.png)

**Comment by lauriejim** [comment]
Hi @lucasdu4rte Can you update to last version on Strapi and tell me if it still happen ?
