### ISSUE TITLE
Policies not executing before Mutations when the resolver name is kebab-cased

### ISSUE THREAD

**Issue by dmcclory** [strapi/strapi#5244]
Hi, I'm sorry to file this, because it looks very similar to #5151 and #4819, but I've been looking at both of them and I'm pretty sure this is distinct.
It's similar to #5151, but in this case the models are all singular. And it's different from #4819 because the resolvers are just the built in controller functions.

**Describe the bug**

When you have a model with multiple words (so the uid ends up being camel cased) and you run a mutation a policy before a Graphql mutation, the policy code does not get executed. The policies do run for Queries!

**Steps to reproduce the behavior**
1. create a local or global policy
2. create a model which has camel cased name (so the directory ends up being kebab-cased)
3. configure the schema.graphql for a Mutation (update) & a Query (findOne) so that they use the policy
4. run the query, the policy is invoked before the resolver method.
5. run the mutation, the policy code does not execute, and the server runs the mutation

**Expected behavior**
I would expect the policy to be invoked before the mutation!

**Code snippets**
I created a repo with a reproduction here: https://github.com/dmcclory/strapi-graphql-camelcase-bug-repro

api/camel-case/config/schema.graphql
```
module.exports = {

 resolver: {
   Query: {
     camelCase: {
       resolver: "camel-case.findOne",
       policies: [
         "global.ownershipPolicy"
       ]
     }
   },
   Mutation: {
     updateCamelCase: {
       resolver: "camel-case.update",
       policies: [
         "global.ownershipPolicy"
       ]
     }
   }
 }
}
```

the policy code is very simple:
```
'use strict';

module.exports = async (ctx, next) => {

  console.log("I am a global policy and I am running!")
  console.log(Object.keys(ctx.request.body))
  console.log(ctx.request.body.operationName)
  console.log(ctx.request.body.title)
  return await next()
}
```

And I used these graphql queries
```
query GetMovie {
  movie(id: 1) {
    title
  }
}

mutation UpdateTitle {
  
  updateMovie(input: {
    where: {id: 1},
    data: { title: "Better Movie"}
  }) {
    movie {
      title
    }
  }
}

query GetCamelCase {
  camelCase(id: 1) {
    title
  }
}

mutation UpdateCamelCase {
  updateCamelCase(input: {
    where: {id: 1},
    data: { title: "Neutral Camel"}
  }) {
    camelCase {
      title
    }
  }
}
```

**Screenshots**
Here's console output after running those 4 mutations in order:

![Screen Shot 2020-02-14 at 9 59 35 AM](https://user-images.githubusercontent.com/1952789/74543834-19434280-4f14-11ea-99a8-534c39f2b0b8.jpg)

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.7
- strapi-plugin-graphql version: 3.0.0-beta.18.7
- Database: postgres
- Operating system: OSX

Thanks for taking a look at it! This is a great project!

**Comment by lauriejim** [comment]
Hello @dmcclory !

Thank you for reporting this issue!

**Comment by alexandrebodin** [comment]
Hello. This one is pretty old but it has actually been fixed for a while now. 

FYI here is a valid schema you can use now
```
module.exports = {
  resolver: {
    Query: {
      camelCase: {
        resolver: 'camel-case.findOne',
        policies: ['global::ownershipPolicy'],
      },
    },
    Mutation: {
      updateCamelCase: {
        resolver: 'camel-case.update',
        policies: ['global::ownershipPolicy'],
      },
    },
  },
};

```

I'm going to close it now :)
