### ISSUE TITLE
Cannot customize the login page Documentation plugin

### ISSUE THREAD

**Issue by ericzon** [strapi/strapi#5247]
**Describe the bug**
I'm trying to customise the login template of documentation plugin but my custom template gets replaced by the original.

**Steps to reproduce the behavior**
1. Go to /extensions/documentation/public/login.html
2. Remove Strapi logo line as example
3. Go to documentation link: http://localhost:1337/documentation/v1.0.0
4. You will see the original version
5. Checking /extensions/documentation/public/login.html again, is a copy of file located in
node_modules/strapi-plugin-documentation/public/login.html

**Expected behavior**
I expect to keep login.html customised.

**System**
- Node.js version: v10 LTS
- NPM version: 6.13.7
- Strapi version: v3.0.0-beta.18.7
- Database: data.db (default)
- Operating system: MacOS Mojave

**Additional context**
I'm new with Strapi but I've worked with other CMS and I think that this is a bug. I've also tried creating an /extensions/documentation/overrides/public/login.html but I had the same behaviour.

**Comment by lauriejim** [comment]
Thank you for reporting this issue.

Here is the reason of this issue.
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-documentation/controllers/Documentation.js#L162

The file is re-write anytime the function is call.
You can fix it in your application using the customization concept.
Rewrite this function without the re-write of this file and it will should work.

**Comment by sam-pires** [comment]
Hello @derrickmehaffy @kasonde 
is it a bug?

**Comment by kasonde** [comment]
@sam-pires it seems at the time it was. I'd have to look into whether this is still the case now.

**Comment by sam-pires** [comment]
> @sam-pires it seems at the time it was. I'd have to look into whether this is still the case now.

Thanks @kasonde 
No need to check again, we'll review it for the v4 🙂

**Comment by emilieringwald** [comment]
Thanks @ericzon, the documentation plugin is on our radar and we'll have a look at this in the coming weeks. We'll keep you posted!

**Comment by derrickmehaffy** [comment]
Moved to: https://feedback.strapi.io/developer-experience/p/customize-the-login-page-documentation-plugin
