### ISSUE TITLE
Controller's `count` not being called on GraphQL

### ISSUE THREAD

**Issue by fullmoon6661** [strapi/strapi#5250]
**Describe the bug**
If you try to override the `count` callback in the controller as described [in the documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#core-controllers), the callback gets called fine via REST but will not get called via GraphQL. Unless you override the GraphQL Aggregator resolver to call the controller (see additional info). I'm thinking this caused by [this](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/Aggregator.js#L356)

**Steps to reproduce the behavior**
1. Override `count` callback in the controller
```js
module.exports = {
    count(ctx) {
        console.log("Ad controller: count");
        if (ctx.query._q) {
            return strapi.services.ad.countSearch(ctx.query);
        }
        return strapi.services.ad.count(ctx.query);
    },
};
```
2. Test the controller via REST [http://localhost:1337/ads/count](http://localhost:1337/ads/count)
3. Test the controller via GraphQL
```graphql
query {
  adsConnection {
    aggregate {
      count
    }
  }
}
```
4. See the log

**Expected behavior**
`count` callback should still be called via GraphQL.

**Screenshots**
Log via REST
![image](https://user-images.githubusercontent.com/32438205/74593674-53215f80-5060-11ea-8089-881db23b0b8e.png)
Log via GraphQL
![image](https://user-images.githubusercontent.com/32438205/74593688-74824b80-5060-11ea-95b1-5439ef5a9f4e.png)

**Additional info**
How do I manually override GraphQL Aggregator resolver:
```js
module.exports = {
  resolver: {
    AdAggregator: {
      count(args) {
        return strapi.controllers.ad.count({
          query: args.where || {}
        });
      }
    }
  }
};
```

**System**
- Node.js version: v10.16.0
- Yarn version: 1.21.1
- Strapi version:  Strapi v3.0.0-beta.18.7
- Database: MongoDB
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! I don't think this is an issue.
The GraphQL aggregation is not related to the `count` function of the controller.
The count aggregation has its own system.
After that,  if you want to use the `count` function of your controller, I suggest you to create a `count` query in your `schema.graphql` file that use the `count` function as resolver.
This is what we did in the FoodAdvisior app example.

**Comment by fullmoon6661** [comment]
That is exactly what I said. 
But the issue is its not consistent. All other endpoints call on the controllers, and `count` should too.

**Comment by lauriejim** [comment]
OKay well, a big work on GraphQL and aggregation will be done before the stable version.
So this will be reviewed soon.

**Comment by rmonnier9** [comment]
Hi !

> How do I manually override GraphQL Aggregator resolver"

I'm asking myself the same question, have you found a way ?

**Comment by fullmoon6661** [comment]
@rmonnier9 The snippet below what you quoted is how I override GraphQL Aggregator resolver.

**Comment by rmonnier9** [comment]
@fullmoon6661 
Oh thanks indeed ! I first thought you were asking the question.

Just tried and your trick works !

However, I still don't find a way to disable all the `[model]Connection` type and queries for security, but this is the subject of an other open issue: #5697 

Thanks for you help !

**Comment by 8byr0** [comment]
If anyone's wondering why context is not available in controller using the snippet above(Thanks @fullmoon6661 for providing it!), update code like this: 

```javascript
module.exports = {
  resolver: {
    AdAggregator: {
      count(obj, opts, graphqlContext) {
        return strapi.controllers.ad.count(graphqlContext.context);
      }
    }
  }
};
```

The main benefit of passing context like this is to share the same code to handle HTTP and Gql requests. Is you want to add args, you can still pass them to `ctx.query`, just the way an HTTP request would be.

And for the explaination, the code passing context to graphql aggregator is here : https://github.com/strapi/strapi/pull/4200/commits/0a98b13e8d3a93955c14f1d95818711a51ec2822

**Comment by derrickmehaffy** [comment]
no more count or aggreg in v4, marking as closed
