### ISSUE TITLE
Support GET-requests for the graphQl plugin

### ISSUE THREAD

**Issue by endiendo** [strapi/strapi#5256]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
I didn't see it anywhere in doc and can't make it working.

**Comment by derrickmehaffy** [comment]
@endiendo while GraphQL proper does support GET requests it's not generally recommended. https://graphql.org/learn/serving-over-http/

Most GraphQL requests are passed via POST as there is a limit to the URL length.

I'll leave this up to @Aurelsicoko and @alexandrebodin if they want to add this or close it.

**Comment by sebastiencloss** [comment]
My problem is that it is then not cacheable by a service-worker (PWA), for example with Workbox.

Resources on this problem:
https://medium.com/@jono/cache-graphql-post-requests-with-service-worker-100a822a388a
https://w3c.github.io/ServiceWorker/#cache-put
https://developers.google.com/web/tools/workbox/modules/workbox-cacheable-response

**Comment by alexandrebodin** [comment]
HI, @endiendo Get queries are already supported by the graphql server we are using: apollo-server. You can learn more [here](https://www.apollographql.com/docs/apollo-server/requests/)
