### ISSUE TITLE
When adding new content, select field was incorrectly wrapped

### ISSUE THREAD

**Issue by kubuntux** [strapi/strapi#5266]
**Describe the bug**
When adding new content, select field was incorrectly wrapped.

![image](https://user-images.githubusercontent.com/8105211/74779582-c2a18400-52d8-11ea-9854-56d5a7ef87f1.png)

![image](https://user-images.githubusercontent.com/8105211/74779712-fb415d80-52d8-11ea-942e-2d2357d5e0e1.png)

The select field is very short, and drop down options are all broken.

![image](https://user-images.githubusercontent.com/8105211/74779806-3348a080-52d9-11ea-9473-50f6229ef09e.png)

Dropdown came from dynamic zone with relations child.

![image](https://user-images.githubusercontent.com/8105211/74779997-a4885380-52d9-11ea-8e6c-275ad16034f2.png)

**Steps to reproduce the behavior**
1. Setup a new new component (eg. Pricing). Include a Relations field in this component, relating to any content type (eg. Currency)
2. Update an existing content type (eg. Products) and add a new dynamic zone (Pricing). Add the newly created component to the dynamic zone.
3. Go to your existing content type and create new entry

**Expected behavior**
The select box should be wrapped properly like this:

<img width="785" alt="Screen Shot 2020-02-19 at 5 39 01 AM" src="https://user-images.githubusercontent.com/8105211/74780254-28424000-52da-11ea-9f50-b4149d2910a4.png">

**System**
- Node.js version: v13.8.0
- NPM version: 6.13.6
- Strapi version: Strapi v3.0.0-beta.18.7
- Database: MongoDB 4.2.3 Enterprise (Atlas)
- Operating system: macOS Catalina 10.15.2

**Comment by kubuntux** [comment]
Pull request https://github.com/strapi/strapi/pull/5280

**Comment by soupette** [comment]
I am closing this issue as it has already been fixed on the `master` branch. Feel free to reopen it if you think it was fixed incorrectly
