### ISSUE TITLE
Initial setup using MySQL don't allow . (dot) in database name

### ISSUE THREAD

**Issue by jeliasson** [strapi/strapi#5267]
**Describe the bug**
Databases using `Azure Database for MySQL` on version `5.7.27-log` allows using . (dot) in database names. Setup of Strapi using MySQL does not allowed this. This causes one to create a temporary database that does not have a dot in the name, set permissions, do the setup, change database name and then update `database.json`. 

Edit: Also true for Postgres.

**Steps to reproduce the behavior**
1. `yarn create strapi-app`
2. Select MySQL
3. Enter `foo.bar` as database name.

**Expected behavior**
Allow use of . (dot) in username for MySQL connections during setup of Strapi.

**System**
- Node.js version: v13.5.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: MySQL 5.7.27-log
- Operating system: Ubuntu under WSL

**Comment by lauriejim** [comment]
Hello! This is something we have to check with each database documentation.
Feel free to add database specifications and then create a pull request to fix this.
Thank you for your contribution.

**Comment by maazkabir** [comment]
@lauriejim  @alexandrebodin 
Hey there second time contributor here( one of my PR's is in review stage)
Can I start looking into this? 
Is this a feature that's on the table? Is this still needed?
Can I add a PR for this issue/enhancement?
If not, can you nudge me in the right direction I would love to contribute!

**Comment by alexandrebodin** [comment]
Hey, yeah you will need to upgrade the strapi-generate-new package to allow different database names based on the client type. get a look in this package and let us know if you feel like working on it :)

**Comment by ZarakiKanzaki** [comment]
Hi! I'd like to know more about the status of this issue, I saw that the or were closed due a complete overhaul of the code. I would love to know more if I can contribute someway to this issue. Thanks in advance for your time

**Comment by derrickmehaffy** [comment]
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/developer-experience/p/initial-setup-using-mysql-dont-allow-dot-in-database-name

Thanks!
