### ISSUE TITLE
Full text search on postgres gives no results

### ISSUE THREAD

**Issue by cadavre** [strapi/strapi#5271]
**Describe the bug**
`_q=2020` on entity with short text field like `Invoice 1235/65/2020` gives `[  ]` no results.

This problem is mainly hurting in admin panel UI.

**Steps to reproduce the behavior**
1. Create invoice entity, add simple text field called "invoice_no".
2. Create customer entity, add relation to invoice.
3. Add new invoice entity with `invoice_no="Invoice 1235/65/2020"`.
4. Try to add new customer with invoice, search for "2020" – you'll be given with no results.

Please don't care about domain logic in above example.

**Expected behavior**
Entity with "Invoice 1235/65/2020" is found.

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.7
- Database: postgres
- Operating system: Docker container on Ubuntu

**Additional context**
I tried playing with `strapi.utils.convertParams` putting default return type as:
```
        } else {
          type = '_contains';
        }
```
but this gives same results.

The problem is strictly with `strapi-connector-bookshelf` which uses `tsvector`s in `queries.js`. This does not produce results as one would except.

Shouldn't we explicitly define when we want to search in fulltext mode and when with just simple `LIKE %q%`?

**Comment by derrickmehaffy** [comment]
related: https://github.com/strapi/strapi/issues/4813

**Comment by lauriejim** [comment]
I'm closing this issue due to the linked one by Derrick.

**Comment by lauriejim** [comment]
Thank you for reporting this in any case!

**Comment by cadavre** [comment]
I didn't wanted to create this issue in the first place, but #4813 fixed will not fix this one.

In this case I'm re-posting this issue on #4813. Thanks.

**Comment by lauriejim** [comment]
Thank you!
