### ISSUE TITLE
Low performance if users are filtered by role.name

### ISSUE THREAD

**Issue by davidemorra** [strapi/strapi#5274]
Hello!!

**Description**
Low performance if users are filtered by role.name

**Steps to reproduce the behavior**
1. Populate users (aprox 1k records)
2. Call GET /users?_start=0&_limit=10&role.name=Authenticated
3. Call GET /users
4. Compare times

**Expected behavior**
Comparable times

**Result**
GET /users?_start=0&_limit=10&role.name=Authenticated (**14351 ms**) 200
GET /users (**778 ms**) 200

**System**
- Node.js version: 12.15.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: mongo
- Operating system: ubuntu or macos

Any idea?

**Comment by davidemorra** [comment]
ok no reaction on this issue

**Comment by alexandrebodin** [comment]
Is your server in the same region as your database. And is your server in the same region as you when querying the API ?

**Comment by davidemorra** [comment]
same region, same conditions in both queries, same environments .. and with param _limit I expect to have at least same response time, make sense?

**Comment by alexandrebodin** [comment]
Sounds like a good idea to verify. Right now I get 500ms when querying for the 1000 first entries with the same filter as yours. Also you might want to try the beta.20 to see if there is a perf difference.
