### ISSUE TITLE
JWT Payload should not contain password

### ISSUE THREAD

**Issue by longweiquan** [strapi/strapi#528]
**Node.js version**: 8

**npm version**: 5

**Strapi version**: 3.0.0@alpha8

**Operating system**: Mac

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The JWT Payload contain private information which is secured.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Current Token

**What is the expected behavior?**
Ideally, The JWT Payload should only contain (_id, iat, exp).

**Comment by lauriejim** [comment]
Thank you for this issue. It's could be awesome if you can fix it and submit a pull request to the project.
