### ISSUE TITLE
GraphQl files deleting

### ISSUE THREAD

**Issue by nezzard** [strapi/strapi#5288]
Hi, i',m looking all day for info about, how to delete uploaded files through GraphQL, and can't find nothing. Pls help

**Comment by navicstein** [comment]
I don't think uploaded files should be deleted, what to do is to create an `api` that will get exposed to your frontend, then manually `unlink` the files that must have matched some  `id` in your database

**Comment by nezzard** [comment]
If I create some route for deleting, will it automatically work in GraphQL?

**Comment by nezzard** [comment]
It’s strange that all functions implemented to graphql except deleting file

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the feature request template.

A proper issue submission let's us better understand the purpose behind your feature request to better understand if it could be implemented.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. Please also submit your feature request on the [Product Board](https://portal.productboard.com/strapi/tabs/2-under-consideration)

Please update the issue, and reply back so it can be reopened.

Thank you.

> A copy of the feature request template can be found below:

```
<!--
Hello 👋 Thank you for submitting a feature request.

We are using ProductBoard to manage our roadmap and feature requests.

Can you please submit your feature request here: https://portal.productboard.com/strapi
-->

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
```

**Comment by navicstein** [comment]
@nezzard yes, if you create a function[API] it should get exposed by graphql automatically then you should be able to write some logic to delete files locally when the endpoint is called, in our case, mutated
