### ISSUE TITLE
Can't and any field to user model via GUI

### ISSUE THREAD

**Issue by Adriang71** [strapi/strapi#529]
**Node.js version**: 8.4.0
**npm version**:5.4.2
**Strapi version**: "3.0.0-alpha.8.2"
**Operating system**: osx 10.12.6 

Hello, I try strapi and I found issue.
When I want to save user model with with some content type via GUI and in my network tab I see request with 400 status and blank page.

I use mongodb, here is message:
```{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"request.error.model.unknow"}]}]}```

When I try to add other content type there is no problem with any filed.

**Comment by soupette** [comment]
Is the error still happening with the new version of Strapi?
