### ISSUE TITLE
Cannot create one way relationship with UUID and SQLlite

### ISSUE THREAD

**Issue by seanaye** [strapi/strapi#5295]
**Describe the bug**
I am using the workaround described in #1826 to add UUID as PK in my models.
This works as expected in standalone tables but when there is a one-way, one-to-many relationship, the "owner" record fails to add.

SQLlite doesn't know how to set uuid on PK which is why it is done in Strapi in the beforeCreate hook. This works fine in the actual table but i'm not sure how to force strapi to set it on the relational table (albums__photos). AFAIK there is no hooks or way to access the model being inserted into this relational table.

Is there a workaround in Strapi? I know it is possible to access the DB directly and remove the constraint.

**Steps to reproduce the behavior**
1. Create content type with one-way, one-to-many relation (the last one in the GUI)
2. Change the model settings to use UUID
*album.settings.json*
```json
"options": {
    "increments": true,
    "timestamps": true,
    "idAttributeType": "uuid"
}
```
3. Add modify the beforeCreate hook as described in #1826
*album.js*
```javascript
const uuid = require('uuid')

module.exports = {
  beforeCreate: async (model, attrs, options) => {
    console.log({model, attrs, options})
    model.set('id', uuid())
  }
}
```
4. Attempt to add a record where album has one or more photos
5. 
```
SQLITE_CONSTRAINT: NOT NULL constraint failed: albums__photos.id
```

**Expected behavior**
Record should be added normal

**Screenshots**
Following field is not set by SQLlite. How do I explicitly tell strapi to set this field?
![image](https://user-images.githubusercontent.com/24496822/75065440-e15d7180-54b6-11ea-9094-ce74ae284833.png)

**System**
- Node.js version: v12.12.0
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.18.7 
- Database: SQLlite3
- Operating system: Mac OS 10.14.6

**Comment by lauriejim** [comment]
This feature `idAttributeType` has been removed in the stable version of Strapi - So I close this issue.
