### ISSUE TITLE
Strapi with Firebase

### ISSUE THREAD

**Issue by seamug** [strapi/strapi#530]
Hi 

Is there any instruction on setting up Strapi on Firebase?

Thanks
Hisham

**Node.js version**:

**npm version**:

**Strapi version**:

**Operating system**:

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by storm1er** [comment]
I don't think so, firebase is using is own api, if you want to do so, you'll probably have to create a new database query structure (like they already did with postgresql, etc)

**Comment by Aurelsicoko** [comment]
@seamug Thank you for this feature request!  You're not the first one and host the data on Firebase isn't one of our priority. We are working to integrate Strapi with DaaS such as mLab, Mongo Atlas, etc. Maybe we will integrate Strapi with Firebase though.

**Comment by nodox** [comment]
I do wish this would support firebase as the database. How do I write my own plugin or data provider to connect with Firebase?

**Comment by Aurelsicoko** [comment]
@nodox We already have two connectors [Mongoose](https://github.com/strapi/strapi/tree/master/packages/strapi-mongoose) and [Bookshelf](https://github.com/strapi/strapi/tree/master/packages/strapi-bookshelf). I didn't check how we could support Firebase but it could be a great thing 👍

**Comment by samlogan** [comment]
+1

**Comment by JREAM** [comment]
+1

**Comment by Aurelsicoko** [comment]
@tohagan @samlogan @JREAM Are we agree that you're using Firebase as a database only? Because it offers a lot of others features such as push notifications, authentication, etc. I would like to know what exactly you're looking for with this integration?

**Comment by samlogan** [comment]
@Aurelsicoko database only for me

**Comment by Aurelsicoko** [comment]
@samlogan Thank you for the answer! We will consider a new connector to Firebase but if you need it now, the best way is to contribute to the project and create the `strapi-hook-firebase` package 👍

**Comment by lauriejim** [comment]
Visit our [Contributing Guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to start your development.

**Comment by rrubio** [comment]
+1

**Comment by Aurelsicoko** [comment]
I've created a private card on Product Board (you can see the public roadmap [here](https://portal.productboard.com/strapi)). I'm closing this issue because we've enough information and use cases to develop the feature. However, this is not our priority and we would love to see the community create the connector. Feel free to ping me if you want more details.

**Comment by HausOfAlejandro** [comment]
Any news on this?, really looking for using Strapi with Firestore. :-)

**Comment by derrickmehaffy** [comment]
No news @Hausofalejandro. More than likely someone in the community would need to work on it

**Comment by rjain15** [comment]
+1, I need firebase (or firestore) instead of mongodb storage. Can I take the mongo provider and change the code (not sure how much is the effort) to support firebase?

**Comment by storm1er** [comment]
@rjain15 You can use mongodb provider as a base, but don't edit it, you better create your own provider.

**Comment by feelosophical88** [comment]
@rjain15 Did you ever get around to trying out Firestore?

**Comment by camillo777** [comment]
Yes now that mLab is out, you should include in Strapi support for serverless DB like Firestore or FaunaDB.

**Comment by lauriejim** [comment]
There is a documentation about MongoDB Atlas.
Here is [the documentation 📚](https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#install-on-atlas-mongodb-atlas)

**Comment by alexgorgos** [comment]
+1

**Comment by majirosstefan** [comment]
+1

**Comment by siberder** [comment]
+1

**Comment by wdhodges** [comment]
+1

**Comment by derrickmehaffy** [comment]
For the moment Strapi has stated they will not work on this themselves, It was recommended that the community work on creating a connector for this.

You can take a look at the current connectors to get an idea of the amount of work needed.
[strapi-connector-mongoose](https://github.com/strapi/strapi/tree/master/packages/strapi-connector-mongoose)
[strapi-connector-bookshelf](https://github.com/strapi/strapi/tree/master/packages/strapi-connector-bookshelf)

I have locked this conversation as nothing new/useful is being added
