### ISSUE TITLE
Uninstall script for documentation plugin doesn't work

### ISSUE THREAD

**Issue by jrybinski** [strapi/strapi#5302]
**Describe the bug**
Uninstall script for documentation plugin doesn't work.

**Steps to reproduce the behavior**
1. Install documentation plugin
2. Add some new content types.
3. Try to uninstall documentation plugin
```
yarn strapi uninstall documentation
```
4. See error. 
```
╰─ yarn strapi uninstall documentation                                                                                                                                                                                                     ─╯
yarn run v1.21.1
$ strapi uninstall documentation
? Do you want to delete the plugin generated files in the extensions folder? Yes
✔ Uninstalling dependencies
The "path" argument must be one of type string, Buffer, or URL. Received type undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
5. Run Strapi and `Documentation` section is still in the admin panel but throws an error when we try to open it.

**Expected behavior**
Documentation plugin is removed without error and admin panel UI is updated correctly.

**System**
- Node.js version: 10.18.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: MongoDB
- Operating system: macOS Catalina

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
I think it's a simple issue to fix, I will appreciate if you can investigate and submit a PR to fix that.
Thank you.

**Comment by LucasMatuszewski** [comment]
I have exactly the same problem. @jrybinski did you find a way to fix it?

@lauriejim - I don't know Strapi enough to fix it now. Could you handle this or at least send me some links to documentation/repo where I will find a code responsible for deleting plugins in strapi? It would make it easier for me to investigate it myself.

**Comment by lauriejim** [comment]
Thank you for your PR, I will take a look soon as I can.
Or will involve the rest of the team.

**Comment by LucasMatuszewski** [comment]
Thanks @lauriejim - I can fix my PR during a weekend, but I need answer about deleting this 3 folders :)
```
/extensions/user-permissions/documentation
/extensions/email/documentation/1.0.0 
/extensions/upload/documentation/1.0.0
```
