### ISSUE TITLE
Filter combined with search is not working in admin

### ISSUE THREAD

**Issue by JelmerV-WFC** [strapi/strapi#5303]
**Describe the bug**
Filter combined with search is not working in admin

**Steps to reproduce the behavior**
1. Go to a content-type overview
2. Apply a filter (e.g. Id is xxx)
3. Now type something in the search bar
4. The filter is still applied (visually) but not applied anymore

**Expected behavior**
The search is queried along with the configured filters

**Screenshots**
Without search:
![image](https://user-images.githubusercontent.com/39594925/75146598-bb74de80-56fb-11ea-9b54-7336e25dccd6.png)

With search:
![image](https://user-images.githubusercontent.com/39594925/75146669-da737080-56fb-11ea-8543-72488d6a9357.png)

**System**
- Node.js version: v10.17.0
- NPM version: 6.11.3
- Strapi version: 18.7-beta
- Database: MongoDB
- Operating system: MacOS / Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
I believe the entire search/filtering system here in the admin is getting an overhaul

**Comment by JelmerV-WFC** [comment]
@derrickmehaffy ah okay. It also is not working with the internal API (e.g. `application::deal.deal?_q=portugal&_limit=20&_start=0&is_published_deal=true`). `is_published_deal=true` is not applied there anymore.

**Comment by derrickmehaffy** [comment]
I don't think `_q` was designed to be used with filters, it's original purpose was a bit of a "type-a-head" type thing for the CTM when searching relations. It kinda acts as a fuzzy search across the full-text indexes.

**Comment by derrickmehaffy** [comment]
@lauriejim not a discussion as @JelmerV-WFC already working on PR

**Comment by alexandrebodin** [comment]
This was merged a while back now. Closing
