### ISSUE TITLE
Can't set unique on a rich text field

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#5305]
**Describe the bug**

Can't set **unique** on a **rich text** field => getting an error when saving.

**Steps to reproduce the behavior**
1. Create a new Content-Type
2. Add a Rich Text Field
3. In Advanced Setting, set "Unique field"
4. Click on finish and save => error

**Expected behavior**
The "unique field" setting should not exist for Rich Text fields.

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: SQLite
- Operating system: MacOS

**Comment by robinv85** [comment]
I looked at this and found some code with a lot of conditional statements to load the right attributes in the form, seems to me this is just a quick fix but would probably be better to refactor.

How about having one single source of truth for this data, so the admin UI and the backend use the same data to determine which attributes are supported for which fields?
