### ISSUE TITLE
Tutorial request on deployment on DigitalOcean 

### ISSUE THREAD

**Issue by shinokada** [strapi/strapi#531]
I just wanted to request a tutorial or doc page on deployment especially DigitalOcean.

**Comment by pierreburgy** [comment]
Good suggestion @shinokada! This is in our plans: we are going to publish an article (https://blog.strapi.io/p/cd1ad84c-1ca5-409d-be05-fb06bca4e8c5/) and add it in the documentation this week.

**Comment by shinokada** [comment]
Great! The blog article, [Building a static blog using Gatsby and Strapi](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/) was very useful for me. I'd like to see using a slug for a URL.

**Comment by ArkhipovK** [comment]
Are there any changes in heroku variant?

**Comment by pierreburgy** [comment]
@shinokada yes, it should work. Did you have any issue with that?

@ArkhipovK to use Heroku, you only need to set your database configuration in [Heroku environment variables](https://devcenter.heroku.com/articles/config-vars) and update the port config in your Strapi project:

*Path: `config/environments/production/server.json`*:
```json
{
  "host": "localhost",
  "port": "${process.env.PORT || 1337}",
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  }
}
```

Btw @Aurelsicoko, shouldn't we update the generators to set this value by default?

**Comment by ArkhipovK** [comment]
@pierreburgy thanks for reply, but what if i have pipe to heroku from bitbucket, and bitbucket repo does not include node_modules. So i suppose i have to run some command or script to insall them first. What is the proper action now?

**Comment by pierreburgy** [comment]
@ArkhipovK Heroku will automatically detect that your app is a Node.js app and then, will install the node modules.

**Comment by pierreburgy** [comment]
The tutorial has been published: https://medium.com/@strapi/how-to-deploy-a-strapi-api-on-ubuntu-16-04-17f8fbbf5c5b, so I am closing the issue.

Thanks again for your suggestion!
