### ISSUE TITLE
Components don't have "where" argument in graphql

### ISSUE THREAD

**Issue by rafaeljuliani** [strapi/strapi#5310]
I have a content type "livro" with a reusable component field "capitulo". Strapi doens't create "capitulos", so there isn't  a "where" argument in graphql and I can't do the follow query:

`query {
  livros(where: {some key: value}) {
   capitulos(where: {some key: value}) { content}
  }
}`

I've only made it work by creating a content type "capitulo", but that is not the desiderable solution, because the entries are feed separately.

This way, I ask: "How can I get just the content of "capitulo" that matches a specific key:value in spite of that bug?"

**Comment by derrickmehaffy** [comment]
@rafaeljuliani currently it is no possible to filter on components due to how they are managed in the backend as polymorphic relations

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
