### ISSUE TITLE
Server doesn't start when Graphql shadowCRUD is set to false

### ISSUE THREAD

**Issue by skavinvarnan** [strapi/strapi#5312]
**Describe the bug**
Server doesn't start when Graphql shadowCRUD is set to false

**Steps to reproduce the behavior**
1. Install graphql plugin
2. Adding the [configuration file](https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#configurations)
3. Update ShadowCRUD to false
4. start the server with ```yarn develop```
5. The server doesn't start  

**Error logs**
```
yarn run v1.19.1
$ strapi develop
[2020-02-25T09:40:25.321Z] debug ⛔️ Server wasn't able to start properly.
[2020-02-25T09:40:25.321Z] error Error: Unknown type "UserInput".

Unknown type "UploadFile". Did you mean "Upload"?

Unknown type "UploadFile". Did you mean "Upload"?
    at assertValidSDL (/Users/skavinvarnan/Projects/strapi/vega/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/Users/skavinvarnan/Projects/strapi/vega/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/Users/skavinvarnan/Projects/strapi/vega/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at makeExecutableSchema (/Users/skavinvarnan/Projects/strapi/vega/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.generateSchema (/Users/skavinvarnan/Projects/strapi/vega/node_modules/strapi-plugin-graphql/services/Schema.js:300:22)
    at Object.initialize (/Users/skavinvarnan/Projects/strapi/vega/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:59:50)
    at /Users/skavinvarnan/Projects/strapi/vega/node_modules/strapi/lib/hooks/index.js:37:28
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
The server should without any shadowCRUD queries or mutation 

**Code snippets**
```
{
  "endpoint": "/graphql",
  "tracing": false,
  "shadowCRUD": false,
  "playgroundAlways": false,
  "depthLimit": 7,
  "amountLimit": 100
}
```

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.7
- Database: Mongo
- Operating system: Mac

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.

**Comment by gfpacheco** [comment]
Same problem here.

Node.js version: v12.16.1
NPM version: 6.13.4
Strapi version: 3.0.0-beta.19.5
Database: SQLite
Operating system: Mac

**Comment by angelorc** [comment]
Same error here. Impossible to disable and so can't customize graphql schema
```
{
   "shadowCRUD": false,
}
```

**Comment by gfpacheco** [comment]
@angelorc This bug sucks, but there's a workaround

On your `api/my-model/config/schema.graphql.js` write:
```
module.exports = {
  type: {
    MyModel: false,
  },
};
```

Then you can customize the `definition`, `query`, `mutation` and `resolver` fields as you please.

It worked for me

**Comment by angelorc** [comment]
Ok thanks

**Comment by alexandrebodin** [comment]
Hi I have been reviewing the graphql issues to prepare v4 :) Could you tell me what you would expect when disable shadowCRUD ? (should it disable the entire generated schema / only for Content Types / what about plugins ...) 

If you just disable everything wouldn't adding a graphql route manually give you more power ? 

Thank you for all the feedbakc you can give us !

**Comment by gfpacheco** [comment]
Good to hear you're looking for better GraphQL support on v4.

Does disabling shadowCRUD do anything on the plugins' REST endpoints? I just expect it to work the same way on GraphQL, and yes, disable any schema types/inputs that are not being used because the queries and mutations were disabled.

**Comment by derrickmehaffy** [comment]
shadowcrud is required in v4 for now, marking as closed.
