### ISSUE TITLE
Limit error when going to the last page

### ISSUE THREAD

**Issue by Tansito** [strapi/strapi#5314]
**Describe the bug**
In the panel administrator with a DataSet of 4464 entries and a limit configured by default to 10 if I want to go to the last page (447) I obtain the next error:
```
MongoError: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.
```

The panel administrator is doing the next query:
```
GET /content-manager/explorer/application::molecule.molecule?_limit=10&_sort=id:ASC&_start=4460
```

**Steps to reproduce the behavior**
1. With a DataSet of 4464 entries
2. Go to the last page

**Expected behavior**
I suppose that this behavior happens due to the sort `&_sort=id:ASC` that we are doing by default in the panel administrator but I'm not absolutely sure.

We should expect to go to the last page.

**System**
- Node.js version: v13.3.0
- NPM version: 6.13.2
- Strapi version: 3.0.0-beta.18.7
- Database: MongoDB
- Operating system: Mac

**Comment by Tansito** [comment]
is there some news about this issue? Or is there something where i can help to maybe provide more info if it's needed?

**Comment by lauriejim** [comment]
Hello! I just tried and it works well.
https://www.loom.com/share/d1f3fdb024e64de5b21bcafd8e7df82d
Did I missed something?

**Comment by Tansito** [comment]
Hello @lauriejim , thanks for taking a look (the video was amazing!). I was investigating the possible causes and I think that this is related with:

```
this behavior happens due to the sort &_sort=id:ASC
```

and

```
operation used more than the maximum 33554432 bytes of RAM
```

Probably it will happen when your sorted data exceeds your maximum capacity of RAM, and that depends a lot of the data that you are sorting.

So, without being a Strapi problem it's true that someday with larger datasets it's probably that you can find in the future in a similar situation because we don't have a way to paginate without sorting the data in the panel administrator (as default you always sort by **&_sort=id:ASC**). My proposal then is to allow to paginate in the admin panel without sorting your data (avoiding memory problems).

**Comment by lauriejim** [comment]
Thank you for your comment, I ping @alexandrebodin and @soupette for this.

**Comment by alexandrebodin** [comment]
Hi @Tansito,  

Have you tried running a pagination query manually with postman with and without the sort to verify it is coming from this param ?

How big are your entities ? Did you configure mongo tu use less RAM than normal ? 32MB of limit seems really low to me

**Comment by Tansito** [comment]
Hi @alexandrebodin ,

First of all excuse me for the delay in the response. At the start of the analysis what I did it was to run the query **without** sorting it (and that it worked) but just to confirm it as you said (and for my surprise) I run the query a moment ago now with the sort:

```
query Test {
  molecules(limit: 10, sort:"id:asc", start: 250) {
    id
  }
} 
```
And it worked perfectly fine so I suppose now that is not related with the mongo configuration at the end (I checked too that the returned id's are the corresponding id's for that positions in the database just to ensure that the query went well) if not with some code in the panel administrator.

Related with the last part of your question @alexandrebodin my entities are around 10kb (they are big) so now I'm restructuring the data to see if this can fix the problem (I will let you know). And about the Mongo configuration what I can say is that I left the size configured by default hehe.

**Comment by Tansito** [comment]
If you are agree, how the issue seems an edge-case from my side (as @alexandrebodin said), nobody seems to have a similar problem and I'm not totally sure that part of the problem comes from the admin-ui either I will close it by now and if I find something I open another issue referencing to this. But thank you as always for your support @lauriejim and @alexandrebodin :)

**Comment by virtualkitchenco** [comment]
I am getting a similar error after I upgraded Strapi from Strapi v3.0.0-beta.14 to Strapi v3.0.0-beta.16.
Visiting the last couple pages in the admin page will result "error MongoError: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit."
