### ISSUE TITLE
Admin dashboard won't be changed 

### ISSUE THREAD

**Issue by majdas007** [strapi/strapi#5317]
**Admin panel can't be changed after i re-build the project**
After i run the project with `yarn strapi develop --watch-admin` then i removed the **leftMenuFooter** to make some changes it instantly changed but after restart the server nothing happened and it runs the old version of the admin dashboard.

**Here is a quick explanation of what i did**
1. `yarn strapi develop --watch-admin`.
2. I made some changes to the **LeftMenuFooter**
3. `yarn build`

**Expected behavior**
What i expect is that i will have the new admin panel.

**System**
- Node.js version: **12.16**
- NPM version: **6.13.4**
- Strapi version: **3.0.0-beta.x**
- Database: **Postgresl**
- Operating system:**Mac**

**Comment by MattieBelt** [comment]
Fixed I guess?
By following these docs, suggested by Jelmer Visser [@Slack](https://strapi.slack.com/archives/C0BNGCDNH/p1582645658378500)
 
https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html#customize-the-strapi-admin-package

and

https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html#customize-a-plugin

So make no changes in .cache dir

**Comment by majdas007** [comment]
This issue is closed since @MattieBelt has made eveything look clear
