### ISSUE TITLE
too long table name in mysql data base when creating relationship of the content

### ISSUE THREAD

**Issue by sugarzhao** [strapi/strapi#5319]
**Describe the bug**

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
Please properly fill out the required template
