### ISSUE TITLE
Strange behavior of relations

### ISSUE THREAD

**Issue by dakuenjery** [strapi/strapi#532]
**Node.js version**: 9.4.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.8.3
**Operating system**: Mac os 10.13.2

There are 2 custom types: pagetypes and pages. Pages belongs to many Pagetypes.
But if we look at the page record structure we will see this:
```
{
  "_id": "5a6df8079dd4ae610eb2d16b",
  "name": "page1",
  "__v": 0,
  "id": "5a6df8079dd4ae610eb2d16b"
} <- no relation to pagetypes
```
And pagetype record will see:
```
{
  "_id": "5a6df7f59dd4ae610eb2d16a",
  "name": "pagetipe1",
  "__v": 0,
  "id": "5a6df7f59dd4ae610eb2d16a",
  "pages": "5a6df8079dd4ae610eb2d16b" <-- relation to page. But I expected an array
}
```
We cannot create one-to-many relation, because if I create a new page (page2) and set relation to the pagetypes table, 'pages' in the pagetype record will be change to the new page2 id and page1 will become "without" relation.

Reproduce:
1. Create page1
![image](https://user-images.githubusercontent.com/2018050/35484591-0b32a72e-0463-11e8-8c25-7563a2362d3f.png)
 2. Create page2
![image](https://user-images.githubusercontent.com/2018050/35484598-35ff5f42-0463-11e8-8c72-35aeb66a603c.png)
3. Go to page1. Relation is empty
![image](https://user-images.githubusercontent.com/2018050/35484605-47f4dc86-0463-11e8-9f19-377e16973505.png)

**Comment by Aurelsicoko** [comment]
@dakuenjery Can you provide the models of the Content Types (pagetypes and pages)? Also which databases are you using? I would be able to take a look when you will give me these details. Thanks!

**Comment by dakuenjery** [comment]
I use mongodb 3.6

Pages.settings.json
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "pages",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "type": {
      "collection": "pagetypes",
      "via": "pages"
    }
  }
}
```
Pagetypes.settings.json
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "pagetypes",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "pages": {
      "model": "pages",
      "via": "type"
    }
  }
}
```

**Comment by Aurelsicoko** [comment]
I think you're not using the right relation type. Try to use `many-to-many` relationships instead. If a `Page` belongs to many `PageTypes` and a `PageTypes` can belongs to many `Page`, it's not a `one-to-many` relationship.

**Comment by dakuenjery** [comment]
No. One page can belongs to one PageType. But I have more then 1 page, and one PageType can belongs to many Pages. In alpha9 this working fine. At first sight)

**Comment by gstazure** [comment]
Just started with strapi and got stuck in a similar issue. 
Consider a simple model. A list of contacts,  and a list of cards. Contacts can have many cards but each card will have only 1 contact. Simple 1 to many relationship.

Stuck in catch 22. Cant add Contact without choosing Card and vice versa. 
Its so ridiculous that I am sure that I am doing something stupid, but any help to fix it would be highly appreciated.

`{
  "connection": "default",
  "collectionName": "contact",
  "info": {
    "name": "contact",
    "description": "contact"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "collection": "cards",
      "dominant": true,
      "via": "assigned"
    },
    "email": {
      "type": "email"
    }
  }
}
{
  "connection": "default",
  "collectionName": "cards",
  "info": {
    "name": "cards",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "cards": {
      "unique": true,
      "type": "string",
      "required": true
    },
    "assigned": {
      "model": "contact",
      "via": "name"
    }
  }
}

**Comment by Aurelsicoko** [comment]
@gstazure Try something like that

```js
// Cards.settings.json
{
  "connection": "default",
  "collectionName": "cards",
  "info": {
    "name": "cards",
    "description": ""
   },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "cards": {
      "unique": true,
      "type": "string",
      "required": true
     },
    "name": {
      "model": "contact"
    }
  }
}
```

```js
{
  "connection": "default",
  "collectionName": "contact",
  "info": {
    "name": "contact",
    "description": "contact"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "collection": "cards",
      "via": "name"
    }
  }
}
```
