### ISSUE TITLE
Webhooks does not trigger for User.create event via the API

### ISSUE THREAD

**Issue by lancevo** [strapi/strapi#5324]
**Describe the bug**
It happened with creating an account via local provider API. 
Webhook doesn't trigger on User.create event. It's triggered for other events such as User.update, User.delete. On other models, all events are triggered properly. Not sure if this is intended.

**Steps to reproduce the behavior**
Admin Page -> Webhooks -> Create a webhook ... Events Entry - tick all check boxes

**Expected behavior**
Webhook to trigger User.create when a new User's created.

**System**
- Node.js version: 10+
-  NPM version:
- Strapi version: 3.0.0-beta.18.6
- Database: mongodb
- Operating system: mac os x

**Comment by derrickmehaffy** [comment]
I can confirm this bug on 18.7

**Comment by lauriejim** [comment]
Thank you for reporting this issue.

Ping @alexandrebodin

**Comment by alexandrebodin** [comment]
Hi @lancevo. Right now you can receive event on delete but you shouldn't :)

The user plugin is running some custom CRUD code it isn't emitting events for the weebhoks. It was a deliberate choice for now. 

Can you explain your usecase for listening to user creation ? 

Thanks !

**Comment by lancevo** [comment]
@alexandrebodin I have to send the user info to another API.  Right now, I implement it in the afterCreate method of the User model.

What is the logical place to do this?
What did you not want user CRUD to emit events for the webhooks?

Thanks

**Comment by alexandrebodin** [comment]
The main reason is that right now you cannot deslect the webhook pour content type and Users contain private informations. We would rather not send the users to third party services without giving control to the user to disable it.

You can indeed use the lifecycles to implement it yourself.

**Comment by UnKnoWn-Consortium** [comment]
@alexandrebodin 
I am not sure if such opinionated default is appropriate. If I am adopting a micro-service architecture for my system, it is totally logical and legitimate for a ```User.create``` and misc be propagated among other co-working services. In such use case, user info is still within my system and not sent to any third-party service without consent.

**Comment by edgycoder** [comment]
I experience the same struggle. 
I wish the `user.create` also trigger the webhook!

Would be even better if `user` had its own column in the webhook selection section

**Comment by liebisca** [comment]
I have the same problem. I want to send new users to my CRM, but unfortunately it does not send the payload data.

**Comment by ghonchesefidi** [comment]
I have the same problem. I'm going to change my user credit amount.

**Comment by mancku** [comment]
Same problem here. I'd like to use the Webhooks to send some user information to other internal services.
I understand that it has some implications and the Strapi team prefers not to do that for now, but @alexandrebodin is that Ok if I create a PR to update [the documentation](https://strapi.io/documentation/developer-docs/latest/concepts/webhooks.html#developer-documentation) so it explains that the Webhooks don't work on Users and that way other devs won't struggle thinking its something wrong on their code/system?
Thanks

**Comment by alexandrebodin** [comment]
Hi @mancku You can totally make a PR on our docs to give this precision.

**Comment by derrickmehaffy** [comment]
closing as docs PR merged
