### ISSUE TITLE
Strapi requires duplicate ids in mongoose even if you explicitly turn off the id field

### ISSUE THREAD

**Issue by onexdata** [strapi/strapi#5325]
**Describe the bug**
I'm creating a document search pattern using simhash. I am storing the simhash uint64 as _id and verified with MongoDB support and a Google cloud architect that using a simhash as the _id index is both ideal for sharding and significantly faster than the generic ObjectId approach MongoDB supplies out of the box.

Strapi supports this by me just setting serviceName/models/serviceName.settings.json's _id attribute to "biginteger". So far so good 👍 and woohoo!

However, Strapi looks like it still *requires* the existence of the "id" field as well, no matter what I do, yielding forced duplicate indexes (MongoDB requires "_id", and Strapi requires "id").

If I don't explicitly set the id attribute to required: false, Strapi actually duplicates the _id field and put's it into id.

The closest I can get is setting the id attribute in the model to required: false and index: false, which gets me past creating without an id field, but then it looks like Strapi is still inserting a null id field and still setting the id field as a key.

**Steps to reproduce the behavior**
1. Create a Strapi service.
2. Create a beforeCreate hook in models/ServiceName.js that generates the _id field, i.e.
```
module.exports = {
  beforeCreate: async (model) => {
    const id = parseInt(Math.random() * 10000000) // Simulating a simhash int
    model.set('_id', id)
    console.log('After beforeCreate, the model looks like this:', model)
  }
}
```
3. Create a /models/ServiceName.settings.json model that defines _id as an int and id as not required, i.e.
```
{
  "connection": "whisper",
  "collectionName": "fingerprints",
  "info": {
    "name": "fingerprint",
    "description": "Fingerprints"
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": "Fingerprints contain a uint64 simhash id and m referrs to matches, will have an i for uint64 production id and t for uint32 timestamp in ms"
  },
  "attributes": {
    "_id": {
      "type": "biginteger"
    },
    "id": {
      "type": "biginteger",
      "required": false,
      "index": false
    },
    "m": {
      "type": "json"
    }
  }
}
```
```
After beforeCreate, the model looks like this: { m: null, _id: Long { _bsontype: 'Long', low_: 437480, high_: 0 } }
[2020-02-26T03:52:32.048Z] error MongoError: E11000 duplicate key error collection: Whisper.fingerprints index: id_1 dup key: { id: null }
    at Function.create (C:\Users\njste\code\experience-engine\platform\node_modules\strapi-hook-mongoose\node_modules\mongodb\lib\core\error.js:44:12)
    at toError (C:\Users\njste\code\experience-engine\platform\node_modules\strapi-hook-mongoose\node_modules\mongodb\lib\utils.js:150:22)
    at C:\Users\njste\code\experience-engine\platform\node_modules\strapi-hook-mongoose\node_modules\mongodb\lib\operations\common_functions.js:266:39
    at handler (C:\Users\njste\code\experience-engine\platform\node_modules\strapi-hook-mongoose\node_modules\mongodb\lib\core\sdam\topology.js:973:24)
    at C:\Users\njste\code\experience-engine\platform\node_modules\strapi-hook-mongoose\node_modules\mongodb\lib\core\sdam\server.js:437:5
    at C:\Users\njste\code\experience-engine\platform\node_modules\strapi-hook-mongoose\node_modules\mongodb\lib\core\connection\pool.js:420:18
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
**Expected behavior**
Strapi should not force an id field when using mongoose, it should use _id.

**System**
- Node.js version: v12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0.17.7 (having "Migration failed" error upgrading to 18.7)
- Database: MongoDB
- Operating system: Windows 10 Pro

**Comment by derrickmehaffy** [comment]
This is done as Strapi supports not only NoSQL but also SQL databases. In order to keep code complexity down (as in theory you could be using both NoSQL and SQL in the same project) Strapi forces the use of `id`.

Afaik there is no plans to allow for that to be easily disabled, `id` is used in just about every package/plugin and modifying that would not be a fun task.

**Comment by lauriejim** [comment]
Hello, ping @alexandrebodin about this.

**Comment by alexandrebodin** [comment]
Exactly as @derrickmehaffy explained. Right now we are adding an id field to reduce complexity of the DB layer. This might eventually change but not something that willl happen anytime soon

**Comment by derrickmehaffy** [comment]
Per Alex's comment going to mark this as closed but do feel free to keep up the discussion. 😃
