### ISSUE TITLE
Unable to override role while creating user through API or GraphQL

### ISSUE THREAD

**Issue by skavinvarnan** [strapi/strapi#5329]
**Describe the bug**
When creating a user unable to override the role of the user through params

**Steps to reproduce the behavior**
1. Perform a curl request
```
curl -X POST "http://localhost:1337/auth/local/register" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"username\":\"bf\",\"email\":\"bf@ty.com\",\"password\":\"acskdjhaksjdfhaksjdfh\",\"role\":\"public\"}"
```
2. User is created but the default role is assigned

**Expected behavior**
The user should be created with the specified role

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.7
- Database: Mongo
- Operating system: Mac

**Comment by derrickmehaffy** [comment]
This is a security risk and is not/will not be supported by Strapi, it has come up before in previous discussion.

You will need to use plugin extensions to override the users-permissions plugin.

**Comment by skavinvarnan** [comment]
@derrickmehaffy agreed. That seems to be a better solution

**Comment by skavinvarnan** [comment]
@derrickmehaffy This particular usecase cannot be configured with plugin extensions. 

**Example:**
Lets say i have a big app which has multiple user roles and everyone of then will be put into each bucket, but my app uses only API's or GraphQL. In this case i wont be able to do that even with the help of plugin extensions. But since security is the highest priority, can we have a global extension parameter which is disabled by default. 

something like ``` settings.allow_role_assignment_from_api ```

**Comment by derrickmehaffy** [comment]
@lauriejim @alexandrebodin I will let you two decide to reopen.

My vote here would be no for Strapi itself and instead off load this to user configuration

**Comment by alexandrebodin** [comment]
We won't allow doing this with the registration api. You can use the user apis instead :)

**Comment by skavinvarnan** [comment]
@alexandrebodin you mean on the [update function](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/User.js#L161), i can add an option to update role. Shall i go ahead a create a PR?
