### ISSUE TITLE
Filtering relationship doesn't work with SqLite3

### ISSUE THREAD

**Issue by AntoineBourin** [strapi/strapi#5331]
Hello,

I've got an issue with Strapi. 
I have two content types : one is Vehicles, the other is Person. I have a relation between them, so Persons can have multiple vehicles.

The problem is that I have 100 vehicles in my database. When i go to the Person creation page and I want to filter all vehicles, only the 20th first can be viewed on the select field. 
The frontend are correctly filtering vehicles with text typed but i see your request `/content-manager/explorer/application::vehicules.vehicules?_q=audi&_limit=20&_start=1` who always return same result not filtered.
For example, when I type like here "Audi", request return Citroën vehicles.... 

I don't know if this is working with other databases, but relation filter is not working at all with SQLite :(

Thanks in advance for your answer

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
It is not possible to filter on relational values as they cannot be displayed in the list view yet. See this feature: https://portal.productboard.com/strapi/1-public-roadmap/c/49-display-relational-field-in-list-view
