### ISSUE TITLE
Strapi rewrite all 'plugin_content_manager_configuration_content_types' keys in "core_store" database table on each restart

### ISSUE THREAD

**Issue by MurzNN** [strapi/strapi#5337]
Our team try to configure Strapi content manager settings between development and production environment via exporting `core_store` database table to git and syncing.

And we got issue, that on each Strapi restart it rewrites all `plugin_content_manager_configuration_content_types::*` keys to same value (without changes), but every rewrite makes `updatedAt` field changed. This happens with production and development modes.

Here is example of one item changes:
```
{
	"_id": {
		"$oid": "5db03265187a497f0027c72e"
	},
	"key": "plugin_content_manager_configuration_content_types::users-permissions.role",
	"environment": "",
	"tag": "",
	"value": "{\"uid\":\"role\",\"source\":\"users-permissions\",\"settings\":{\"searchable\":true,\"filterable\":true,\"bulkable\":true,\"pageSize\":10,\"mainField\":\"id\",\"defaultSortBy\":\"id\",\"defaultSortOrder\":\"ASC\"},\"metadatas\":{\"id\":{\"edit\":{},\"list\":{\"label\":\"Id\",\"searchable\":true,\"sortable\":true}},\"name\":{\"edit\":{\"label\":\"Name\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"Name\",\"searchable\":true,\"sortable\":true}},\"description\":{\"edit\":{\"label\":\"Description\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"Description\",\"searchable\":true,\"sortable\":true}},\"type\":{\"edit\":{\"label\":\"Type\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"Type\",\"searchable\":true,\"sortable\":true}},\"permissions\":{\"edit\":{\"label\":\"Permissions\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true,\"mainField\":\"id\"},\"list\":{\"label\":\"Permissions\",\"searchable\":false,\"sortable\":false}},\"users\":{\"edit\":{\"label\":\"Users\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true,\"mainField\":\"id\"},\"list\":{\"label\":\"Users\",\"searchable\":false,\"sortable\":false}},\"createdAt\":{\"edit\":{\"label\":\"CreatedAt\",\"description\":\"\",\"placeholder\":\"\",\"visible\":false,\"editable\":true},\"list\":{\"label\":\"CreatedAt\",\"searchable\":true,\"sortable\":true}},\"updatedAt\":{\"edit\":{\"label\":\"UpdatedAt\",\"description\":\"\",\"placeholder\":\"\",\"visible\":false,\"editable\":true},\"list\":{\"label\":\"UpdatedAt\",\"searchable\":true,\"sortable\":true}}},\"layouts\":{\"list\":[\"id\",\"name\",\"description\",\"type\"],\"edit\":[[{\"name\":\"name\",\"size\":6},{\"name\":\"description\",\"size\":6}],[{\"name\":\"type\",\"size\":6}]],\"editRelations\":[\"permissions\",\"users\"]}}",
	"type": "object",
	"createdAt": {
		"$date": "2019-10-23T10:58:45.436Z"
	},
	"updatedAt": {
- 		"$date": "2020-01-27T09:47:22.168Z"
+ 		"$date": "2020-01-27T09:51.12.113Z"
	},
	"__v": 0
}
```

This happens on each Strapi restart, so this bug each time produce a lot of changes in exported table, even if we don't change anything!

Is there any ways to fix this problem and prevent rewriting records with same value?

**System**
- Node.js version: 13.9.0-1nodesource1
- NPM version: 3.5.23.5.2
- Strapi version: v3.0.0-beta.18.6
- Database: MongoDB
- Operating system: Ubuntu Linux

**Comment by derrickmehaffy** [comment]
@soupette thoughts? Maybe do a comparison with expected value vs existing value (not sure of the performance differences between just writing vs reading first/then writing.

@MurzNN AFAIK this was done to prevent corrupted instances of the content-manager display storage (which used to happen often). I suppose realistically it probably doesn't even need the updated_at value (or created_at for that matter).

**Comment by MurzNN** [comment]
> Maybe do a comparison with expected value vs existing value (not sure of the performance differences between just writing vs reading first/then writing.

Instead of deep json comparison, we can simply calculate some checksum (md5?) of new and old value, and update only when checksum differs. This will not eat too much performance...

**Comment by derrickmehaffy** [comment]
Well something to keep in mind also is doing this for all databases not just mongo. I'm sure the SQL databases would also support something like this but if we index (not sure if that is done already) comparing the exact values shouldn't be too bad.

I will let @soupette and @alexandrebodin give their thoughts here.

**Comment by alexandrebodin** [comment]
I don't really like the idea of adding overhead for now. We will eventually work on the db migration path so I don't want to make choices about this right now. 

You can just export your data without the date fileds for now as a workaround.

**Comment by MurzNN** [comment]
> I don't really like the idea of adding overhead for now.

But making 20+ **write** queries to database on each Synapse startup make much larger overhead, than "read + detect changes, and write only if changed", and db migration path will not resolve those overhead.

**Comment by MurzNN** [comment]
> You can just export your data without the date fileds for now as a workaround.

Export is not problem, following import to production database is main problem, we must write custom script for fill `core_store` database table from exported data, instead of simple "mongoimport" from json file.

**Comment by derrickmehaffy** [comment]
I'm actually wondering if this is one of the causes for why my project takes so long to load up.

98 Models not including the plugins

**Comment by alexandrebodin** [comment]
It does have an overhead for sure. I just don't want to create a temporary solution right now. We clearly have a lot to work on on the performance side of things. But it's just not a top priority we the few resources we have right now. 

If you are willing to work on improving this we can surely discuss a fix and you could work on a PR :)

**Comment by marconucara** [comment]
Hello @MurzNN, can you share a bit about you dump & versioning implementation? I'm going to address the same problem soon.
Thanks.

**Comment by MurzNN** [comment]
@marconucara, I make simple bash script, that do mongoexport and mongoimport for configuration collections:
```
COLLECTIONS=(
  core_store
  users-permissions_role
  users-permissions_permission
)
```

And export:
```
mongoexport -d $DATABASE_NAME -c $COLLECTIONS --out $APP_DIR/conf-sync/core_store.json --pretty
```

Import:
```
mongo $DATABASE_NAME --eval "db.getCollection('$COLLECTION').remove({})" > /dev/null
mongoimport -d $DATABASE_NAME -c $COLLECTION --file $APP_DIR/conf-sync/$COLLECTION.json > /dev/null
```

**Comment by MurzNN** [comment]
I find the place, where config written to database, and add check for changes, here is my PR https://github.com/strapi/strapi/pull/5367 - can you review it?

**Comment by derrickmehaffy** [comment]
> It does have an overhead for sure. I just don't want to create a temporary solution right now. We clearly have a lot to work on on the performance side of things. But it's just not a top priority we the few resources we have right now.
> 
> If you are willing to work on improving this we can surely discuss a fix and you could work on a PR :)

In either case this PR does improve some performance regardless. I think the lodash method is fine just not as quick as the previous change.
