### ISSUE TITLE
Changing upload provider break config

### ISSUE THREAD

**Issue by corentinchap** [strapi/strapi#5339]
**Describe the bug**
I was using the Cloudinary provider for the beginning of my projects and then switched to a custom one after some time.
The payload sent to update with the new provider still includes the old provider name and old details

**Steps to reproduce the behavior**
1. Install an upload provider, use it once (in my case Cloudinary)
2. Change provider
3. Update settings from the admin panel
4. Try to upload a file, Strapi will ask the old provider because database isn't up to date
4. When updating the config, we see the payload with the mixed config. In my case the payload was
```
{
    "port": "22",
    "enabled": true,
    "host": "xm4zj.ftp.infomaniak.com",
    "name": "Local server",
    "user": "xm4zj_assets",
    "provider": "cloudinary",
    "api_secret": "1234567489",
    "cloud_name": "corentinchap",
    "basePath": "/assets",
    "sizeLimit": 30000,
    "api_key": "123456789",
    "password": "123456789",
    "baseUrl": "https://assets.tribalcabane.ch/"
}
```

**Expected behavior**
When switching provider we would like to make sure that the table is flushed with default data.
The expected payload must be for the FTP provider
```
{
    "port": "21",
    "enabled": true,
    "host": "xm4zj.ftp.infomaniak.com",
    "name": "Local server",
    "user": "xm4zj_assets",
    "provider": "FTP",
    "sizeLimit": 30000,
    "password": "123456789",
    "baseUrl": "http://assets.tribalcabane.ch/"
}
```

**System**
- Node.js version: 12.14.1
- NPM version: 1.13.14
- Strapi version: 3.0.0-beta-18.7
- Database: sqlite for testing, mongodb
- Operating system: windows

**Comment by lauriejim** [comment]
Hello! I just tried with the last version of Strapi and all works well.
If I update the upload provider, new uploaded files are going in the right place.
