### ISSUE TITLE
Uncapitalize field names in model fields list

### ISSUE THREAD

**Issue by MurzNN** [strapi/strapi#5351]
All field names in Strapi model fields list are capitalized, even they starts with lowercase letter, this confuse developers. Will be good to disable capitalizing of field name in interface.

Version: Strapi v3.0.0-beta.18.6

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by MurzNN** [comment]
I update issue to match template

**Comment by veitbjarsch** [comment]
I don't think this will confuse a developer. Normally I'll have a look into the code instead of the admin backend. Personally I like the capitalization, because the backend site looks more esthetic. And the content Editor doesn't need to know if a data table starts with a lower or upper letter.

**Comment by MurzNN** [comment]
This place is for developers only, because it in `content-type-builder` setting interface, not in content manager.

>  And the content Editor doesn't need to know if a data table starts with a lower or upper letter.

Also content editors don't see snake_case and camelCase, but they see :) Ideally Content editors must see custom display names for fields (like in model name), instead of internal variable names. Hope this will happens in future versions...

Here https://github.com/strapi/strapi/pull/5296 is PR for solve this issue.
