### ISSUE TITLE
Unnecessary join queries on many-to-many relations cause performanse issue in large datbase.

### ISSUE THREAD

**Issue by alishojagit** [strapi/strapi#5363]
**Describe the bug**
i have a many-to-many relation between doctor and meta. graphql query:
 doctors(limit:1}) {
    id
    metas{    id    }
    }

generates 3 mysql queries :
1.  select `doctors`.* from `doctors` limit 1

2. select distinct `metas`.* from `metas` left join `doctop`.`doctors_metas__metas_doctors` as `doctors_metas__metas_doctors_1` on `doctors_metas__metas_doctors_1`.`meta_id` = `metas`.`id` left join `doctop`.`doctors` as `doctors_1` on `doctors_metas__metas_doctors_1`.`doctor_id` = `doctors_1`.`id` where `doctors_1`.`id` in ('308384')

3. select distinct `doctors`.*, `doctors_metas__metas_doctors`.`meta_id` as `_pivot_meta_id`, `doctors_metas__metas_doctors`.`doctor_id` as `_pivot_doctor_id` from `doctors` inner join `doctors_metas__metas_doctors` on `doctors_metas__metas_doctors`.`doctor_id` = `doctors`.`id` where `doctors_metas__metas_doctors`.`meta_id` in (26, 438, 872)

the third query is very time consuming. i have 1500000 doctors in my db, and system crashs with heap mempry!! i want only one doctor metas.  i dont undrestand why the third query is generated! 
increaseing server memory, the heap memory error disapears. but the query runing time is 30 seconds!  and make website very slow. i even created a new strapi inctance, with doctor and meta only models. the queries is the same as my current instance!

 

 

**Steps to reproduce the behavior**
1. define meta, doctor models
2. a many-to-many relation betwnn meta and doctor
3. create 100K doctor and 100k metas
4. query the doctors and metas. 3 qouries last more than 30S. low performance ....

**Expected behavior**
2 first qouries is enough!:
1.  select `doctors`.* from `doctors` limit 1

2. select distinct `metas`.* from `metas` left join `doctop`.`doctors_metas__metas_doctors` as `doctors_metas__metas_doctors_1` on `doctors_metas__metas_doctors_1`.`meta_id` = `metas`.`id` left join `doctop`.`doctors` as `doctors_1` on `doctors_metas__metas_doctors_1`.`doctor_id` = `doctors_1`.`id` where `doctors_1`.`id` in ('308384')

 
**System**
- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version:  v3.0.0-beta.18.8
- Database: mysql
- Operating system: centos

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
@alexandrebodin is it just me or does this look like a race condition on the many to many relationship?

**Comment by mehdiraized** [comment]
+1

**Comment by alishojagit** [comment]
please help, wich core files i should check for debuging ? @derrickmehaffy 
i  must  deliver the project in next week.

**Comment by marefati110** [comment]
i have same problem

**Comment by alexandrebodin** [comment]
Right now you should use a manyWay relation (unidirectional relation to avoid the issue).
This is due to autopopulation being used even if not necessary. 

Hopefully we can address this soon. Help is always welcomed ;)

**Comment by alishojagit** [comment]
@alexandrebodin 
tnx for ur quick answer.
please hint me which module or file i can edit and  solve my problem.
in another word weher i look for the problem?
the problem is in bookshelf? graphql ? strapi files?

**Comment by alexandrebodin** [comment]
You can update your model in the interface from many to many to manyWay (the relation will only be accessible in one direction so be careful)

**Comment by derrickmehaffy** [comment]
To answer your other question @alishojagit the issue is with Strapi and the population so this is a bug. For now there is no known solution to it other than the suggestion that Alex gave which is to use manyWay instead of manyToMany.

As an objective opinion here, I would avoid manyToMany as much as possible as it is a very complex relation that is not handled well in SQL in general.

**Comment by derrickmehaffy** [comment]
I am going to close and lock this thread in favor of our global tracking issue here: https://github.com/strapi/strapi/issues/8552

If anyone has additional comments please place them on the tracking issue, we are doing this to help centralize the issue and make it clearer where various related bug reports stem from the same source.
