### ISSUE TITLE
Error: Invalid format, expected an ISO compatible date

### ISSUE THREAD

**Issue by UndarkAido** [strapi/strapi#5365]
**Describe the bug**
When trying to manually create an entry for a component with a date, the error "Error: Invalid format, expected an ISO compatible date" pops up and the entry isn't saved.

**Steps to reproduce the behavior**
1. Create a Strapi project using mongoose
2. Create a content type with a date field
3. Attempt to create an entry for that type

**Expected behavior**
The entry should be created

**System**
- Node.js version: v13.9.0
- NPM version: 6.14.1
- Strapi version: Powered by Strapi v3.0.0-beta.18.8
- Database: MongoDB v3.6.8
- Operating system: Ubuntu 19.10

**Additional context**
```
[2020-02-28T23:14:44.692Z] error Error: Invalid format, expected an ISO compatible date
    at parseDate (/home/aidan/Code/capconnect/node_modules/strapi-utils/lib/parse-type.js:37:11)
    at parseType (/home/aidan/Code/capconnect/node_modules/strapi-utils/lib/parse-type.js:89:14)
    at model.set (/home/aidan/Code/capconnect/node_modules/strapi-connector-mongoose/lib/utils/index.js:48:25)
    at SchemaString.SchemaType._applySetters (/home/aidan/Code/capconnect/node_modules/mongoose/lib/schematype.js:944:22)
    at SchemaString.SchemaType.applySetters (/home/aidan/Code/capconnect/node_modules/mongoose/lib/schematype.js:968:16)
    at SchemaString.SchemaType.getDefault (/home/aidan/Code/capconnect/node_modules/mongoose/lib/schematype.js:922:25)
    at $__applyDefaults (/home/aidan/Code/capconnect/node_modules/mongoose/lib/document.js:375:22)
    at model.Document (/home/aidan/Code/capconnect/node_modules/mongoose/lib/document.js:123:5)
    at model.Model (/home/aidan/Code/capconnect/node_modules/mongoose/lib/model.js:99:12)
    at new model (/home/aidan/Code/capconnect/node_modules/mongoose/lib/model.js:4579:15)
    at /home/aidan/Code/capconnect/node_modules/mongoose/lib/model.js:3068:22
    at /home/aidan/Code/capconnect/node_modules/mongoose/lib/model.js:3104:7
    at Array.forEach (<anonymous>)
    at /home/aidan/Code/capconnect/node_modules/mongoose/lib/model.js:3103:15
    at /home/aidan/Code/capconnect/node_modules/mongoose/lib/utils.js:283:5
    at new Promise (<anonymous>)
[2020-02-28T23:14:44.693Z] debug POST /content-manager/explorer/application::capstone.capstone (15 ms) 400
```
```js

  "connection": "default",
  "collectionName": "capstones",
  "info": {
    "name": "Capstone"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "CapstoneName": {
      "type": "string"
    },
    "StartDate": {
      "type": "datetime"
    },
    "EndDate": {
      "type": "datetime"
    },
    "Description": {
      "type": "richtext"
    },
    "Pictures": {
      "collection": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "DisplayPhoto": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "Featured": {
      "type": "boolean"
    },
    "viewcount": {
      "type": "integer"
    },
    "posts": {
      "via": "capstone",
      "collection": "post"
    },
    "moderator": {
      "via": "capstone",
      "plugin": "users-permissions",
      "model": "user"
    },
    "sponsors": {
      "collection": "sponsor",
      "via": "capstones",
      "dominant": true
    },
    "department": {
      "via": "capstones",
      "model": "department"
    },
    "creators": {
      "via": "createdcapstones",
      "plugin": "users-permissions",
      "collection": "user",
      "dominant": true
    }
  }
}
```

**Comment by kubuntux** [comment]
Hello.

Tested using the following and it worked on my side:

- Node.js version: v13.8.0
- NPM version: 6.13.6
- Yarn version: 1.22.0
- Strapi version: Powered by Strapi v3.0.0-beta.18.8
- Database: MongoDB v3.6.8 (via docker)
- Operating system: MacOS Catalina 10.15.2 (19C57)

`
 {
 "connection": "default",
  "collectionName": "pages",
  "info": {
    "name": "Pages"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "date_published": {
      "type": "datetime"
    }
  }
}
`

Video

https://vimeo.com/394617937

**Comment by derrickmehaffy** [comment]
@UndarkAido please confirm when you got the error and how you were sending data (AdminUI, REST, GraphQL?)

**Comment by UndarkAido** [comment]
@derrickmehaffy I'm sending the data in the AdminUI and the error pops up when I click 'Submit' on the 'Create An Entry' page.

**Comment by UndarkAido** [comment]
Oh wait a second, that paste didn't come from the branch I was running. I'm doing this a college capstone project, and being new to Strapi, we probably messed up porting it so we tried recreating the API from scratch. I pasted the recreated version but was running the badly ported version. The recreation seems to be working.

**Comment by frenchqwerty** [comment]
Hi, I have same issue after upgrade from alpha to beta.

**Comment by UndarkAido** [comment]
@frenchqwerty I'll reopen the issue for ya

**Comment by lauriejim** [comment]
Hello! Since the last version is the 3.0.1, I will close this issue.
Please if you have any issue with the latest version of Strapi please open a new issue.
Thank you.
