### ISSUE TITLE
strapi start can only be used inside a strapi project-windows user

### ISSUE THREAD

**Issue by Karolinehc** [strapi/strapi#5366]
Hello Everyone! any help would be appreciate PLEASE!

1. When I want to start my connection among strapi an mongodb
2. using "strapi start" appear "strapi start can only be used inside a strapi project"
3. Once again I want to continue to create users on my app fluter to achieve it I need to re-start "strapi new server" or "strapi start" right?
**System**
4.- Node.js version: v10.16.3
- NPM version:6.14.1
- Strapi version: 3.0.0-alpha 26.2
- Database: mongodb atlas
- Operating system:windows 10
5 Before it I typed 

npm install
npm cache clean
npm install -g npm
npm install
But it doesn't  work 

Somebody can put me on the right direction? 
Thank you
![strapi-mongodb-flutter](https://user-images.githubusercontent.com/28733391/75597676-c6fe3780-5a64-11ea-9a40-611dd8cda3f6.gif)

**Comment by izznatsir** [comment]
It looks like that your strapi app is located in the server directory. You have to cd to server directory to be able to use strapi start, yarn start, or npm run start to start your strapi server.

**Comment by derrickmehaffy** [comment]
Indeed that is the case @izznatsir you need to be in the root of the Strapi project. Marking as closed.

**Comment by mohammed7aafar** [comment]
in my case I was running the command `npm run develop` in my strapi working directory but it generates error.
so I decided to deleted the **package-lock.json** and executed `npm install` and it worked.

**Comment by Coderddd** [comment]
yarn install => yarn develop.
