### ISSUE TITLE
Update User in graphql creates error in apollo MutationData.onMutationCompleted method

### ISSUE THREAD

**Issue by tanveerbhatia** [strapi/strapi#5375]
**Describe the bug**
When trying to mutate the user using graphql query
The Database is updating and getting response too, but generating error on apollo client onMutationComplete method
```
error TypeError: Cannot read property 'data' of undefined
    at MutationData.onMutationCompleted
```
Apollo client MutationData.onMutationCompleted Error line.
```
private onMutationCompleted(
    response: ExecutionResult<TData>,
    mutationId: number
  ) {
    const { onCompleted, ignoreResults } = this.getOptions();

   const { data, errors } = response;

```
response is returning empty.
if updating any other API it's is working as normal. The issue is with user update only.

**Expected behavior**
It Should run Apollo mutation data Complete method and return with data response in MutationData.onMutationCompleted

**Code snippets**
```
mutation {
    updateUser(
	input: {
		where: { id: "id_here" }
			data: { fname: "fName here" }
		}
	) {
	user {
		id
		fname
		email
		role {
		    name
		    type
	        }
        }
    }
}
```

**System**
- Node.js version: v10.16.3
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.8
- Database: MongoDB
- @apollo/react-hooks: ^3.1.3,
- react-apollo: ^3.1.3,
- apollo-boost": ^0.4.7,
- Operating system: Windows 10 x64

**Comment by derrickmehaffy** [comment]
@tanveerbhatia did you find a solution to this issue?
