### ISSUE TITLE
Me Endpoint does not expose all data

### ISSUE THREAD

**Issue by bjarn** [strapi/strapi#5389]
**Describe the bug**
When an authenticated user calls the users/me endpoint, it does not expose additional fields. However, they do show up when you call the users/{id} endpoint. 

For example, the {id} endpoint contains the profile image field that has been set up, but this does not work in the Me endpoint.

**Steps to reproduce the behavior**
1. Authenticate as a user
2. Call the Me endpoint
3. See missing data

**Expected behavior**
The Me endpoint should contain all the user's data.

**System**
- Node 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.8
- Database: MySQL
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment]
This is intended, to cut down on query latency for those with a lot of relations.

Only role is populated, you can customize this by using plugin extensions.

For now I am marking this as closed, if have questions do feel free to ask

**Comment by Hredhya** [comment]
I am facing the same issue, Can you elaborate on how to fix this,as I am new to strapi

**Comment by dsfaccini** [comment]
Hello, this issue ranks high when googling "strapi modify me endpoint" so I wanted to give You and future visitors a solution.
I found it [here](https://medium.com/@fabian.froeschl/add-updateme-route-to-strapi-4-0s-users-permissons-plugin-fc31798df295) and the code is the following:
```javascript
// src/extensions/users-permissions/strapi-server.js
// strapi-server.js is a new file You must create
module.exports = (plugin) => {
  plugin.controllers.user.meWithBilling = (ctx) => {
    ctx.params.id = ctx.state.user.id;
    ctx.query = { populate: ["billing_detail", "role"] };

    return plugin.controllers.user.findOne(ctx);
  };

  plugin.routes["content-api"].routes.push({
    method: "GET",
    path: "/users/me",
    handler: "user.meWithBilling",
  });

  return plugin;
};

```
