### ISSUE TITLE
Unable to login with Facebook for accounts without email

### ISSUE THREAD

**Issue by bison92** [strapi/strapi#5393]
**Describe the bug**
There's no way AFAIK to login with facebook if your facebook account has no email. When signin up on facebook, you can either use your email or your mobile phone. In the second case (an account that is only using the mobile phone) the login won't work.

**Steps to reproduce the behavior**
1. Configure your facebook provider.
2. Create a facebook account using a mobile phone number instead of email.
3. Wait 60 minutes (facebook restriction to add app integrations on new accounts)
4. Try to log-in using facebook, and it will loudly fail.

**Expected behavior**
Given that facebook accounts are not required to have an email. Facebook log-in flow should not depend on that. 

**Code snippets**

Here's the code that requests the email from facebook:
https://github.com/strapi/strapi/blob/0f3fd09a1c8499da15908de6932cf3ad1d9000b3/packages/strapi-plugin-users-permissions/services/Providers.js#L174-L187

And here's the code that fails when email is unavailable
https://github.com/strapi/strapi/blob/0f3fd09a1c8499da15908de6932cf3ad1d9000b3/packages/strapi-plugin-users-permissions/services/Providers.js#L39-L42

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.8
- Database: MySQL
- Operating system: Windows (dev) | Docker on AppService (prod)

**Additional context**
This problem is also happening if you use an account without a validated email. We had kind of a hard time looking for the problem because of #3339 but we finally saw the "Email was not available." error phrase. We know we can solve this by upgrading strapi to a version that has #3339 fixed and showing some alert when this error occurs. But, given that this is not a requirement from Facebook, **shouldn't we support every kind of Facebook account?**

Regards,

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
Can you please submit a PR to fix this issue.
You will have to apply the same system as GitHub provider - https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/Providers.js#L209
Thank you!

**Comment by RileyMShea** [comment]
I have the same issue but with the Twitter provider,  phone-number-based accounts do not work.

**Comment by ferdigokdemir** [comment]
<img width="495" alt="Screen Shot 2020-07-18 at 23 28 14" src="https://user-images.githubusercontent.com/23097465/87861386-6194df80-c94e-11ea-9e18-2330df201e1d.png">
Same issue, any fix?

**Comment by RileyMShea** [comment]
@ferdigokdemir I did a janky  workaround by overriding the `./user-permissions/services/Providers.js`.    Disabling the null email check and setting null emails to a pseudo-email based on a real social account uuid is probably your best best afaik right now. Might be a long time before we see a proper solution if email as pkey is as deeply baked into strapi as I think it might be.

**Comment by ferdigokdemir** [comment]
Can you share example code?

**Comment by tention** [comment]
Used this as workaround, and changed username to Facebook ID instead.

```
      facebook
        .query()
        .get('me?fields=id,name,email')
        .auth(access_token)
        .request((err, res, body) => {
          // If no email, create a mimic email based on id
          let facebookEmail = body.email;
          if (!facebookEmail) {
            facebookEmail = body.id.concat('@facebook.com');
          }
          if (err) {
            callback(err);
          } else {
            callback(null, {
              // Changed this to ID instead of name
              username: body.id,
              email: facebookEmail,
            });
          }
        });
      break;
```

**Comment by derrickmehaffy** [comment]
Closing this as it's quite easy to modify this logic, as we already do for the Instagram provider: 

https://github.com/strapi/strapi/blob/df832fafd1705266d65bae22d8dd3a0fe37964cf/packages/strapi-plugin-users-permissions/services/Providers.js#L334

If you want to see an example I just created one yesterday as a user wanted to modify the logic for the Discord one: 
https://github.com/derrickmehaffy/strapi-test-custom-discord/blob/de2c10e2569d23204b9629bed397102d53dae0b7/extensions/users-permissions/services/Providers.js#L158-L161

**Comment by RileyMShea** [comment]
@derrickmehaffy Do you not see it as an issue that you are theoretically supporting these authentication providers, yet out of the box it's completely broken for half of the people trying to authenticate?  There's a whole swarm of underlying issues with this I don't want to even want to get into(now I need a second field to hold "actualEmail" etc..).  After months of using strapi, I won't use it on any new projects because of this.

Even if you used a social provider that required users to have emails, anytime that user updates their email with the said provider, it will completely break their authentication with strapi.  

There is nothing in the docs about this and users don't find out until weeks or months into development when they finally get their first ph# only user.

Let's be honest, strapi should've made the primary key socialID or even just some autogenerated UUID out of the gates.  I really hope for the sake of your users that your next major release makes that change.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Do you not see it as an issue that you are theoretically supporting these authentication providers, yet out of the box it's completely broken for half of the people trying to authenticate? There's a whole swarm of underlying issues with this I don't want to even get into(now I need a second field to hold "actualEmail" etc..). After months of using strapi, I won't use it on any new projects because of this.
> 
> Even if you used a social provider that required users to have emails, anytime that user updates their email with the said provider, it will completely break their authentication with strapi.
> 
> There is nothing in the docs about this and users don't find out until weeks or months into development when they finally get their first ph# only user.
> 
> Let's be honest, strapi should've made the primary key socialID or even just some autogenerated UUID out of the gates. I really hope for the sake of your users that your next major release makes that change.

Please feel free to submit a PR if you think it would be worth modifying the default logic

**Comment by abaksha-sc** [comment]
Maybe it will help for someone who will read this issue.

I fixed another strapi issue and the same fix works fine here also for users who doesn't have an email.
Fix is here: https://github.com/strapi/strapi/issues/19761#issuecomment-1997151590

The idea is to search user in database by "username OR email". So when email is absent we register user with only username and on next authentications we searches him by username.

P.S. If user changed username in social account and email is absent then we are not able to link his social account with database user. In this case he will be registered again. 
The ideal solution is to search current user by account id which is providing by the auth service (mostly provides as "providerAccountId"). But it's difficult to override strapi behavior to return it. By default strapi returns only username and email for all providers:

https://github.com/strapi/strapi/blob/489f9b45e18c189ef54dab2ae6e1d60bdf691b17/packages/plugins/users-permissions/server/services/providers-registry.js#L83-L84
