### ISSUE TITLE
Strapi is not using the configured host when launching the server

### ISSUE THREAD

**Issue by fodkastir** [strapi/strapi#5399]
**Describe the bug**
Strapi is not using the configured host when spinning up the server

**Steps to reproduce the behavior**
Even the host that you want to launch your server is configurable but actually Strapi in not using it.
In [Strapi.js](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/Strapi.js#L236), Strapi launches the sever by doing `this.server.listen(this.config.port, async err` instead of `this.server.listen(this.config.port, this.config.host, async err`, which means Node will listen to 0.0.0.0 by [default](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback).
There was an issue #3525 opened but closed without a fix.

**Expected behavior**
Strapi should use the host value in config when launching the server.

**Additional context**

**Comment by derrickmehaffy** [comment]
@fodkastir please do feel free to submit a PR

**Comment by lauriejim** [comment]
Thank you for reporting that. Ping @alexandrebodin

**Comment by alexandrebodin** [comment]
Yep It is a really simple fix for sure :) If you are willing to open a PR @fodkastir  it would be awesome 💯
