### ISSUE TITLE
Partial model update remote MongoDB 

### ISSUE THREAD

**Issue by Compaurum** [strapi/strapi#5406]
**Describe the bug**
We have remote mongo db (Atlas cluster). Sometimes, when we want to update model with included group in it, It updates only root part of the object and not embedded group. Seem like it happens, because under the hood we update two collections - model collection and group collection and one of request to db breaks. It's hard to verify because there is no any errors from the strapi about this. It happened few times in last month so I think it's pretty often.

**Steps to reproduce the behavior**
1. Setup remote mongo db
2. Create model with embedded group.
3. Update many many times.
4. Compare expected model and result we have

**Expected behavior**
I expect a throwback error if the group collection update failed.

**System**
- I use latest docker strapi/strapi images. 3.0.0-beta.19-node12
- Database: Atlas MongoDB

**Comment by lauriejim** [comment]
Hello! Can you precise "It updates only root part of the object and not embedded group"
I'm not sure to understand what is happening.

**Comment by lauriejim** [comment]
I'm closing since I don't have any update.
