### ISSUE TITLE
Cant update an user

### ISSUE THREAD

**Issue by Nyeedz** [strapi/strapi#541]
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.8.3

**Operating system**: Windows 10 x64

**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** When trying to update a user via PUT, the message **"You can't call the query method without passing the model's name as a first argument"** is shown on the console, and the message on the http response is this: `{
	"statusCode": 400,
	"error": "Bad Request",
	"message": "Cannot read property 'update' of undefined"
}`

**If the current behavior is a bug, please provide the steps to reproduce the problem**: Send a PUT request to the url **http://localhost:1337/user/:youruserid** with the object `{
	"email": "test@test.com"
}`

**What is the expected behavior?** The response code should be 200 and the user should be updated

**Comment by lauriejim** [comment]
Can you tell me the database you use please

**Comment by sm4rtie** [comment]
had the same issue, passed it by adding a new route with `"path": "/user/:id/:model",` but in admin panel updating still doesn't work. 
Using mongo as database and strapi 3.0.0-alpha.8.3.

**Comment by Nyeedz** [comment]
> Can you tell me the database you use please

i'm using MongoDB

**Comment by lauriejim** [comment]
It's fix in our last release https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.9.2

**Comment by HDMiranda** [comment]
@lauriejim, I'm in version 10.2 and it's still a issue for me.

**Comment by FabAdrien** [comment]
@lauriejim Same problem here only when I try to update the email address of the user...
`"message": "Cannot read property 'id' of null"`

**Comment by lauriejim** [comment]
Checkout `alpha.11.1` and on master branch for last users fixes.

**Comment by hansemannn** [comment]
Hey folks, quick question here: Does someone has an example of updating a user model? I tried the following but only get back a `403 Forbidden`:
```sh
PUT /user/:id
```
with body (JSON-encoded):
```json
{ "email": "newmail@example.com" }
```
Are there parameters that need to be send with the body? I already set the bearer-token to use the JWT returned on auth. Thx!

**Comment by lauriejim** [comment]
You have have, one user can update his profile with this route ?

**Comment by hansemannn** [comment]
Yep, that was the idea!

**Comment by lauriejim** [comment]
I link a screen about a discussion of this topic.

You just have to update to your use case (User api routes)

<img width="1031" alt="screen shot 2018-09-12 at 19 35 57" src="https://user-images.githubusercontent.com/5716596/45442744-288ce380-b6c3-11e8-9012-88aff8532518.png">

**Comment by doublemarked** [comment]
> You just have to update to your use case (User api routes)

@lauriejim How in the beta do we apply a policy to the /user update route?

**Comment by lauriejim** [comment]
Please for that you will have to check how the **extensions** folder work.
**📚Documentation here:** https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions

You will have to extend the [User model](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/models/User.settings.json)

And to add a policy please check this documentation https://strapi.io/documentation/3.0.0-beta.x/guides/policies.html
