### ISSUE TITLE
Last characters in long UID textfield are hidden

### ISSUE THREAD

**Issue by tomolenet** [strapi/strapi#5416]
**Describe the bug**
If the input of your UID textfield takes more space than the UID textfield width, the last characters of your input are not visible. Even if I move my cursor to the end of the line.

**Steps to reproduce the behavior**
1. Create a Content Type with an UID field.
2. Add a Content Type to your collection with a long UID.

**Expected behavior**
I am able to view and access the last characters of my UID.

**Screenshots**
![image](https://user-images.githubusercontent.com/38924650/75910681-90526380-5e4e-11ea-9b7a-1b8ba4328db9.png)

**System**
- Node.js version: v10.18.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.1
- Database: mongodb
- Operating system: linux

**Comment by derrickmehaffy** [comment]
I think the UIDs need a cut off limit

**Comment by tomolenet** [comment]
> I think the UIDs need a cut off limit

Not sure about a restriction at this point. Why would you do that? Sometimes titles of posts, the uid is based on, are very long?

**Comment by derrickmehaffy** [comment]
@tomolenet The problem here is URLs have a limit, in theory someone could build a UID that exceeds the limits of a URL (2048 characters). It is not uncommon for a slug-type field to have a maximum length and trim any excess off.

**Comment by lauriejim** [comment]
Hello! Thank you for this report.
Ping @alexandrebodin  and @Aurelsicoko

**Comment by alexandrebodin** [comment]
We should simply just fix the input. The UID field isn't restricted to URL usage so no reason to restrict it by default.
