### ISSUE TITLE
Creating an entry with a required image field throws a validation error

### ISSUE THREAD

**Issue by feute** [strapi/strapi#5418]
**Describe the bug**
Strapi throws a validation error when trying to create an entry that has a required image field. It works when it's not marked as required.

The response I get is:

```json
{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"ValidationError","message":"ValidationError"}],"errors":{"image":["image must be defined."]}}],"data":[{"messages":[{"id":"ValidationError","message":"ValidationError"}],"errors":{"image":["image must be defined."]}}]}
```

**Steps to reproduce the behavior**
1. Create a project with `--quickstart`.
2. Create a content type with at least one image field.
3. Create a new entry with any image and click *Save*.

**Expected behavior**
The entry should not throw a validation error if the image is actually present.

**System**
I used a 'vanilla' project using the Strapi CLI create command with `--quickstart`.
- Node.js version: 12.15.0
- Strapi version: 3.0.0-beta.19
- Database: SQLite
- Operating system: Linux, Fedora 31

**Additional context**
I updated from Strapi 3.0.0-beta.18.x before creating the content type with the image field, if that's relevant to the issue.

**Comment by alexandrebodin** [comment]
@feute Hi, this was fixed in beta.19.1 :)

**Comment by nkmnz** [comment]
I think I might get a related error using 19.3. Everything works fine when I hit the frontend route for the first time for a given Question, which produces an Answer object in the db. The second time I hit the route, it should produce a new Answer object, but since the update to 19.1 (and 19.3), I get the Validation Error and the same response as @feute above. 


`error Error: ValidationError
    at /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/services/entity-validator/index.js:26:29
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.create (/Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/services/entity-service.js:65:23)
    at async Object.getAnswerFor (/Users/edukat.io/Code/edukatio-api/backend/api/answer/services/Answer.js:221:21)
    at async Object.askVariant (/Users/edukat.io/Code/edukatio-api/backend/api/learn/services/learn.js:22:20)
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:77:22
    at async module.exports (/Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:112:3)
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi-utils/lib/policy.js:52:5
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/xss/index.js:34:9
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/xframe/index.js:30:9
    at async session (/Users/edukat.io/Code/edukatio-api/backend/node_modules/koa-session/index.js:41:7)
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/boom/index.js:92:9
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/boom/index.js:75:11
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/responses/index.js:17:9
    at async cors (/Users/edukat.io/Code/edukatio-api/backend/node_modules/@koa/cors/index.js:54:32)
    at async /Users/edukat.io/Code/edukatio-api/backend/node_modules/strapi/lib/middlewares/logger/index.js:43:11`

`{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "ValidationError",
  "data": {
    "errors": {
      "question": [
        "question must be defined."
      ]
    }
  }
}`

**Comment by nkmnz** [comment]
rollback to 18.8 resolves the issue, update to 19.3 recreates it

**Comment by alexandrebodin** [comment]
We need more details @nkmnz required Relations need to be passed. The issue is about media here not relations.

**Comment by abdonrd** [comment]
@alexandrebodin I have this issue with the last version: `v3.0.0-beta.20`.

**Comment by cinder92** [comment]
im still getting this issue on 4.7.0
