### ISSUE TITLE
Content type manager's list view has no loader

### ISSUE THREAD

**Issue by kubuntux** [strapi/strapi#5422]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Content type manager's list view has no loader. This is noticeable, especially if the DB is hosted remotely. And it often leads to confusion because of the thought that the content type has no entry whenever the user is going to open a content type list or switch to another page.

![final_5e60ca5999e5f70016dbf741_681233](https://user-images.githubusercontent.com/8105211/75969189-86416b00-5f09-11ea-8730-553a8e924548.gif)

**Comment by lauriejim** [comment]
Hello @kubuntux !
Thank you for reporting this issue, can you please just update the issue template by following the **ISSUE** one. Thank you!

**Comment by lauriejim** [comment]
Ping @soupette @maevalienard and @Aurelsicoko about this topic.

**Comment by soupette** [comment]
I am closing this issue as it has been implemented by @virginieky
