### ISSUE TITLE
Configure the view for list view cannot save

### ISSUE THREAD

**Issue by harrykc** [strapi/strapi#5424]
**Describe the bug**
The settings of the list view cannot save for all content types.

**Steps to reproduce the behavior**
1. Go to one of content type listing page
2. Click on "Configure the view"
3. add/remove some fields
4. save it and got error

**Screenshots**
<img width="1931" alt="Screenshot 2020-03-05 at 6 43 09 PM" src="https://user-images.githubusercontent.com/7317546/75974074-2e0e6700-5f11-11ea-9913-84c70a593559.png">

**System**
- Node.js version: v12.14.1
- NPM version: 6.13.6
- Strapi version: v3.0.0-beta.19.1
- Database: mongodb
- Operating system: ubuntu

**Comment by derrickmehaffy** [comment]
I can confirm this on beta.19.1

![image](https://user-images.githubusercontent.com/8593673/75974367-e269a800-5e93-11ea-9050-d3f449a2814a.png)
