### ISSUE TITLE
Bad behavior of endpoint fields in roles-permissions plugin admin panel

### ISSUE THREAD

**Issue by malliaridis** [strapi/strapi#5437]
**Describe the bug**
When configuring the permissions of a role the endpoint fields of the endpoints have multiple behavior issues: 
1. The clickable area is the word (text) and the checkbox only
2. The configuration wheel (when field checked) appears when hovering the endpoint field and has `cursor = pointer` when hovered, but is not clickable
3. If you want to show the endpoint configurations you have to uncheck and recheck the endpoint, since there is no selection without toggle possible

**Steps to reproduce the behavior**
1. Reproduction of clickable area check
    1. Enable `Roles & Permissions` plugin
    2. Go to `Roles & Permissions` plugin's Admin panel
    3. Select a role 
    4. Go to the Permissions and hover over the checkbox, the text and the empty area of an unchecked endpoint field
2. Reproduction of missing click action on configuration wheel
    1. Follow the steps 1.1 - 1.3
    2. Check an endpoint
    3. Select an other endpoint (this will toggle the endpoint's check state)
    4. Hover over the unselected but checked endpoint field (the configuration wheel appears)
    5. Click on the configuration wheel (no click action)
3. Reproduction of missing select action without toggling
    1. Follow the steps 2.1 - 2.4
    3. Try to select the endpoint field (to configure) without toggling the endpoint check status

**Expected behavior**
1. I would expect that I can click on the whole field area (see below screenshots) where the highlighting happens and toggle only the check state of the endpoint when clicking on the checkbox or text. I would also expect here a hovering effect like when checked 
2. I would expect a selection of the endpoint field and an opening of the advanced settings (but click action is missing atm)
3. The expected behavior here is a possibility to select the endpoint without toggling it's checked state (see also 1.)

**Screenshots**
![Screenshot of expected areas](https://i.imgur.com/QWuy7Px.png)
Terminology: 
* *expected toggle area*: the area which toggles the checked state of the endpoint field on click (text and checkbox)
* *expected selection area*: the area which selects the endpoint field (without toggling the checked state). This area is the same as the highlighted (in grey) area of the selected field
* *expected image button*: The image button of the configuration wheel which opens the configuration / advanced settings

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.18.7
- Database: Any (it is view related)
- Operating system: Any (it is view related)
- Browser: Chrome (but probably any)

**Additional context**
* The problem with the configuration wheel is probably because the bubbling events are not handled properly
* The missing hover effect of unchecked endpoint fields and the clickable area might be on purpose, but doesn't reflects the user's expectations (at least not my expectations)
* The `Select All` checkbox affects also the appearance of the focused / selected / checked endpoint views causing unreproducable (by single single endpoint selection) view states. This might be fixed if the above issues are fixed correctly

P.S. I wrote these issues together since they are hardly related to the same object and it's behavior / user interaction.

**Comment by lauriejim** [comment]
Thank you this reporting! 
Sorry for the super late response, II missed this message in the notification center.
Any way.

You are right, I ping @soupette about this behaviors.

Something I would super appreciate is if you can try to submit a PR to fix this issue.
The topic you are pointing has to be fixed and it could be done by someone from the Community.
Here is the [contributing guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) to help you to getting started.

Thank you.

**Comment by pijushbarik** [comment]
This issue still seems to exist in Chrome, but works fine in Firefox. The checkboxes are not clickable and not visible whether its is checked or not.

Screenshots
Chrome
![chrome](https://user-images.githubusercontent.com/40261261/101985055-7da56e80-3cab-11eb-8176-58ae9cf1452f.png)

Firefox
![firefox](https://user-images.githubusercontent.com/40261261/101985059-8138f580-3cab-11eb-9a5a-3f4f2dc04a38.png)


Strapi version: 3.3.4
Node version: 14.15.0
Chrome version: 87.0.4280.88
Firefox version: 83.0
OS: Manjaro linux
