### ISSUE TITLE
Cannot use 'in' operator to search for 'excludeEmptyString' in url must be a valid URL

### ISSUE THREAD

**Issue by gorgekara** [strapi/strapi#5439]
**Describe the bug**
After upgrading strapi to 3.0.0-beta.19 / 3.0.0-beta.19.2 i get an error (output shown below). I basically followed this guideline: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.html

```
[2020-03-05T19:28:54.191Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-05T19:28:54.194Z] error TypeError: Cannot use 'in' operator to search for 'excludeEmptyString' in url must be a valid URL
    at StringSchema.matches (/Users/gjorgekarakabakov/Development/my-project/node_modules/strapi-utils/node_modules/yup/lib/string.js:107:51)
    at Object.<anonymous> (/Users/gjorgekarakabakov/Development/my-project/node_modules/strapi-admin/controllers/Webhooks.js:21:8)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadFiles (/Users/gjorgekarakabakov/Development/my-project/node_modules/strapi/lib/load/load-files.js:35:17)
    at async Promise.all (index 0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gjorgekarakabakov/.npm/_logs/2020-03-05T19_28_54_211Z-debug.log
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-strapi-app
Arguments: my-project --quickstart
Directory: /Users/gjorgekarakabakov/Development
Output:

```

**Steps to reproduce the behavior**
1. Follow migration guideline on https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.html and update all dependencies to 3.0.0-beta.19.2.
2. Remove `/node_modules`, `/build`, `/.cache` and run `yarn install`
3. Run `yarn develop` (tried running `yarn build` just in case, no luck)

**Expected behavior**
Should build and run the server without errors.

**System**
- Node.js version: 13.10.1 (tried with older version as well)
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.19.2
- Database: SQLite
- Operating system: MacOS / Windows

**Additional context**
This issue wasn't happening on 3.0.0-beta.18.4. Also tried to create new strapi app with `yarn create strapi-app my-app` but the same error ocurred.

**Comment by perdidao** [comment]
I'm having the same problem on different environments.
Just yesterday I had a clean install and all went great.

**Comment by gorgekara** [comment]
Might be an error caused by `yup` - `..ject/node_modules/strapi-utils/node_modules/yup/lib/string.js`

**Comment by mirkavolakova** [comment]
I'm getting exactly the same error when following this installation guide: https://strapi.io/documentation/3.0.0-beta.x/installation/cli.html

Run just `yarn create strapi-app backend --quickstart --no-run` and when running `yarn develop` or `yarn strapi dev` after, I get that very same error.

**Comment by philip993** [comment]
I got the same error as well.

**Comment by dmcclccam** [comment]
Got the same error as well, when trying to follow the instalation guide.

**Comment by ifavo** [comment]
I am having the same issue, upgrading from 19.1 – could it be linked to this change? https://github.com/strapi/strapi/compare/v3.0.0-beta.19.1...v3.0.0-beta.19.2#diff-9a25487764c861c8d09bc61a5bebfdd6L78

**Comment by gorgekara** [comment]
@ifavo diff link seems broken

**Comment by mirkavolakova** [comment]
@gorgekara The link's supposed to be: https://github.com/strapi/strapi/compare/v3.0.0-beta.19.1...v3.0.0-beta.19.2#diff-9a25487764c861c8d09bc61a5bebfdd6 (@ifavo, you're missing a # there before the diff)

**Comment by teunw** [comment]
I ran `npm i -S yup@0.28.1` manually before running strapi develop and it seems to work fine.

**Comment by afloret** [comment]
yup published a new version 0.28.2 which introduce this bug by dependency in strapi-utils in strapi-admin so you can change the version of yup in strapi-utils in strapi-admin to 0.27.0 and run "npm install" but it's only a patch since strapi fix the dependency issue

**Comment by derrickmehaffy** [comment]
@alexandrebodin I can confirm this issue on a fresh project as well

![image](https://user-images.githubusercontent.com/8593673/76054879-51e0a580-5f2f-11ea-82dd-b6fa158a4aa8.png)

**Comment by dngrhm** [comment]
I can confirm that applying the PR https://github.com/strapi/strapi/pull/5440 fixes the issue for a fresh project.  I applied the change manually and the fresh project started correctly.  (I am using the strapi/strapi docker image)

**Comment by veerjainATgmail** [comment]
```
cd node_modules/strapi-utils/
npm install yup@0.28.1
```
fixed the reported issue.. However, enabling the graphQL results in the following error:

[2020-03-06T06:40:31.104Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-06T06:40:31.106Z] error TypeError: Cannot use 'in' operator to search for 'excludeEmptyString' in url must be a valid URL

**Comment by gorgekara** [comment]
🍻to @MattieBelt for pushing a fix so fast! PR #5440 is working for me as well

**Comment by MattieBelt** [comment]
https://github.com/jquense/yup/issues/798

**Comment by chrisformula** [comment]
Same problem none of the above work

**Comment by MattieBelt** [comment]
3.0.0-beta.19.3 should fix the problem.

@chrisformula Are you still having this problem, after updating strapi version?

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
