### ISSUE TITLE
camelCase core middleware are not loaded (responseTime)

### ISSUE THREAD

**Issue by getorca** [strapi/strapi#5441]
**Describe the bug**
Following the instructions on https://strapi.io/documentation/3.0.0-beta.x/concepts/middlewares.html#node-modules-structure to enable responseTime middleware does not add the header `X-Response-Time`. However if I create a custom middleware with the contents of https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/responseTime/index.js I can get the `X-Response-Time` header.

**Steps to reproduce the behavior**
1. add the following to config/environments/**/middleware.json
`{
  "responseTime": {
    "enabled": true
  }
}`
2. View the response headers of an API call in a browser
3. `X-Response-Time` header is not present

**Expected behavior**
The  `X-Response-Time` header should be present when the responseTime middleware is enabled.

**System**
- Strapi version: 3.0.0-beta.18.7 & v3.0.0-beta.19.2
- Database: MongoDb

**Comment by lauriejim** [comment]
Hello @getorca !

Thank you for reporting this issue. After some investigation, the issue doesn't come from the middleware itself.

Is a middleware is in the `packages/strapi/lib/middlewares` folder and the name is in camelCase, it's not loaded.
Probably an issue from the [middleware loader](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/load-middlewares.js).

**Comment by alexandrebodin** [comment]
@getorca Your configuration is conflicting with one already set in `config/environments/**/response.json`: 
```json
{
  "gzip": {
    "enabled": false
  },
  "responseTime": {
    "enabled": false
  }
}
```

If you enable it there it should work jsute fine.  Let us know once you have verified ;)

**Comment by lauriejim** [comment]
Confirmed, it works on the last version of Strapi.
