### ISSUE TITLE
strapi.entityService is undefined

### ISSUE THREAD

**Issue by ganisivakumar** [strapi/strapi#5442]
**Describe the bug**
Trying to upload file while creating an entry. Followed as per documentation.
I am getting this error, 
"Cannot read property 'uploadFiles' of undefined"

**Code snippets**
`module.exports = {
    /**
   * Promise to add record
   *
   * @return {Promise}
   */
    async create(data, { files } = {}) {
        const entry = await strapi.query('question').create(data);
    
        if (files) {
            console.log("inside", typeof files)
          // automatically uploads the files based on the entry and the model
          console.log("Entry", strapi.entityService)
          await strapi.entityService.uploadFiles(entry, files, {
            model: strapi.models.question,
          });
          return this.findOne({ id: entry.id });
        }
    
        return entry;
    },
};`

**System**
- Node.js version:  10.15.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: Mongodb
- Operating system: Mac

**Additional context**

**Comment by alexandrebodin** [comment]
Hi @ganisivakumar,

You are using a version of strapi that doesn't have the entityService. Make sur to upgrade to at least beta 18.5
