### ISSUE TITLE
model is undefined in uploadToEntity function

### ISSUE THREAD

**Issue by ganisivakumar** [strapi/strapi#5445]
**Describe the bug**
I am trying to upload an image while creating a restaurant. I am getting this error "`Cannot read property 'attributes' of undefined`" in **uploadToEntity** function in upload service. 
When i tried debugging this line `const model = strapi.getModel(params.model, source);`
source is coming as undefined, params are` { id: '5e624d72a06f8d1e084d28cf', model: Model { restaurant } },`  but model is undefined. So, it is failing there.

**Code snippets**
```
async uploadToEntity(params, files, source) {
    // Retrieve provider settings from database.
    const config = await strapi
      .store({
        environment: strapi.config.environment,
        type: 'plugin',
        name: 'upload',
      })
      .get({ key: 'provider' });

    const model = strapi.getModel(params.model, source);
```

**System**
- Node.js version: 10.15.6
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.5
- Database: Mongodb
- Operating system: Mac

**Additional context**
 ```
const entry = await strapi.query('restaurant').create(data);
    
        if (files) {
            console.log("inside", typeof files)
          // automatically uploads the files based on the entry and the model
          console.log("Entry", entry)
          await strapi.entityService.uploadFiles(entry, files, {
            model: strapi.models.restaurant,
          });
          return this.findOne({ id: entry.id });
        }
    
        return entry;
```

**Comment by alexandrebodin** [comment]
hi @ganisivakumar model expect the name of the model not the object. just pass model: 'restaurant' ;)

**Comment by Domenico-Esposito** [comment]
> hi @ganisivakumar model expect the name of the model not the object. just pass model: 'restaurant' ;)

Hi @alexandrebodin 
you have an example of "files" attribute for `strapi.entityService.uploadFiles` ??
