### ISSUE TITLE
Replace "There is no [type]" by a loading message when appropriate

### ISSUE THREAD

**Issue by clorichel** [strapi/strapi#5450]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:** when users arrive on a content type page, the message is by default `There is no [Type]...` (where `[Type]` is the content type name). Depending on many factors (api/db servers load, entries per page, etc...) it can take a bit to actually get content displayed.

How about replacing the initial message with a `Loading [Type.plural]...`?

**Comment by derrickmehaffy** [comment]
@clorichel please edit your original post to make this a bug report.

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by clorichel** [comment]
Sure! Glad it sounds like a bug 🤓Done.

Be aware the GitHub bug issue template mention v10 as the LTS node version, but LTS is v12 if I'm not mistaken.

**Comment by lauriejim** [comment]
Hello! this topic already exists here! https://github.com/strapi/strapi/issues/5422

**Comment by MattieBelt** [comment]
@clorichel v10 & v12 are both active LTS. 
https://nodejs.org/en/about/releases/
