### ISSUE TITLE
Enumeration value check on Postgres

### ISSUE THREAD

**Issue by czyzu01** [strapi/strapi#5454]
**Describe the bug**
When allowed values in enumeration fields are changed after creation, database constraints are not updated, this causes an error when we try

**Steps to reproduce the behavior**
1. Go to Content Type builder, create type with enumeration field 
2. Set couple of values
3. Save 
4. terminate strapi
5. start strapi again
6. edit allowed values for enumeration
7. try to save element of collection with a new value in enumeration
8. error pops up

**Expected behavior**
Whenever a set of values is changed in strapi for enumeration field a constraint in db should be updated.

**Code snippets**
This is what is created in postgresql when describing a table representing component
```
Check constraints:
    "components_visibility_user_statuses_value_check" CHECK (value = ANY (ARRAY['active'::text, 'suspended'::text]))
```

**System**
- Based on docker: strapi/base:12-alpine
- Strapi version: 18.7
- Database: Postgres 11.7
- Operating system: alpine

**Comment by yunyu** [comment]
I am experiencing a similar issue, where adding a new enum field causes a syntax error for the migration:

```
[2020-03-06T23:40:29.406Z] error Migration failed
[2020-03-06T23:40:29.408Z] error error: syntax error at or near "check"
    at Connection.parseE (/srv/app/node_modules/pg/lib/connection.js:604:13)
```

**Comment by lauriejim** [comment]
This issue has been fixed in the last version of Strapi.
https://www.loom.com/share/542642fb58854dbeb490642b03ac5622
