### ISSUE TITLE
Graphql resolver field not executed

### ISSUE THREAD

**Issue by kjurenec** [strapi/strapi#5458]
Hi, I created `schema.graphql.js` in ./api/organization/config/ folder with content:
```javascript
module.exports = {
  resolver: {
    Query: {
      organizations: {
        resolverOf: "application::organization.organization.find",
        resolver: async (obj, options, { context }) => {
          const { modelName } = strapi.api.organization.models.organization;
          return strapi.query(modelName).find({}, []);
        }
      }
    },
    Organization: {
      name: ({ name }) => name,
      id: ({id}) => id,
      locations: {
        resolverOf: "application::location.location.find",
        resolver: () => {
          return [];
        }
      }
    }
  }
};
```
When i try tu execute query:
```graphql
{
  organizations { 
   id
    name
    locations {
      name
    }
  }
}
```

It all works. Data is returned, but i expected for organization.locations (locations is the collection type same as organizations) to return an empty array, but it returns real data. The same problem is with organization.id field.  I tested organization.name, and that field is getting executed.

**System**
- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.19.3
- Database: sqlite
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello! I'm not sure to understand what you are trying to do?
Why are you updating your GraphQL query?

**Comment by kjurenec** [comment]
@lauriejim i want to use dataloader so i can optimize the number of database queries

**Comment by lauriejim** [comment]
@alexandrebodin any feedback about that?

**Comment by alexandrebodin** [comment]
Hi @kjurenec right now we do not supported overriding a Type fields resolvers correctly. 

You can only ovewritte the fields that do not have a resolver defined by strapi directly (hence the name field working). But for id and relation fields we do generate resolvers that cannot be overwritten for now. 

We will add this feature in the futur for sure :)
