### ISSUE TITLE
Import/export data plugin

### ISSUE THREAD

**Issue by 7mioda** [strapi/strapi#5459]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Topic: Import/export data plugin**
I saw on the roadmap that the Import/export data feature is planned so I have been lately working on a plugin that can do the job.
For the moment I tested it only with MongoDB databases.
So I opened this discussion for advice to help me continue developing this plugin.

**Suggestions for this topic**
Here below screenshots of the plugin's folder structure and code.

**Screenshots**
***Folder structure***
![folder_structure](https://user-images.githubusercontent.com/26418713/76151418-3d2e1a00-60b5-11ea-877b-62acd6446663.png)
***Controllers***
![export](https://user-images.githubusercontent.com/26418713/76151450-84b4a600-60b5-11ea-913a-8a8db337f62c.png)
![import](https://user-images.githubusercontent.com/26418713/76151452-8b431d80-60b5-11ea-8dc6-4984ab0a8768.png)
***Services***
![services](https://user-images.githubusercontent.com/26418713/76151477-b9286200-60b5-11ea-8820-bb4b8bbb8b4d.png)

**Additional context**
I managed for the moment to import and export data from and to all content types (MongoDB => CSV).
I 'll be very happy if anyone can guide me threw the development of this plugin.
I really enjoy working with Strapi and I want to give something back to the community.

**Comment by derrickmehaffy** [comment]
@endymion1818 it might be better to link to code in a repo or something instead of screenshots but nice job anyway 😉

**Comment by 7mioda** [comment]
@derrickmehaffy, if it would be more helpful I'll be pleased to push the code in a GitHub repo

**Comment by lauriejim** [comment]
Thank you @7mioda !
Ping @Aurelsicoko @alexandrebodin

**Comment by derrickmehaffy** [comment]
@7mioda me and @Mcastres are currently working on an `awesome-strapi` repo so if you wanted to make your package into a plugin that would be great (publish to npm and all that) and we could link it on there. For now going to close this as there is already an entry on the product board for the import/export stuff.

Do feel free to reply here though once you move it into a git repo or you can poke me on the Strapi slack.
