### ISSUE TITLE
Bootstrap function in plugin "users-permissions" failed

### ISSUE THREAD

**Issue by devalexandre** [strapi/strapi#5460]
**Describe the bug**
When I create a clean project using mysql not work

**Steps to reproduce the behavior**
1.  yarn create strapi-app papodedev-strapi 
2. Choose your installation type custom
3. Choose your default database client mysql

```
Database name: papodedev-strapi
? Host: 127.0.0.1
? Port: 3306
? Username: curso
? Password: *******
? Enable SSL connection: No
```
4. cd papodedev-strapi/
5. yarn build
6. yarn develop

```
Bootstrap function in plugin "users-permissions" failed
[2020-03-08T01:53:10.241Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Users/alexandre/projetos/papodedev-strapi/node_modules/knex/lib/client.js:318:17
    at tryCatcher (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alexandre/projetos/papodedev-strapi/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
error Command failed with exit code 1.

```

**System**
- Node.js version: v12.13.0
- Yarn version: 1.19.1
- Strapi version: 3.0.0-beta.19.3
- Database: Mysql
- Operating system: MacOS

**Comment by daniymilner** [comment]
I have the same problem with mysql connection

**Comment by devalexandre** [comment]
I managed to solve by looking at an issue

```javascript
"options":{
      "pool":{
            "min":0,
             "max":15,
              "idleTimeoutMillis":30000,
              "createTimeoutMillis":30000,
             "acquireTimeoutMillis":30000
       }
}
```

**Comment by v-osnovnom-bezvreden** [comment]
> I managed to solve by looking at an issue
> 
> ```js
> "options":{
>       "pool":{
>             "min":0,
>              "max":15,
>               "idleTimeoutMillis":30000,
>               "createTimeoutMillis":30000,
>              "acquireTimeoutMillis":30000
>        }
> }
> ```

Can you please give more info on solution ?
I have just tha same problenm with fresh install under linux.

```
[2020-03-17T13:27:10.998Z] error Bootstrap function in plugin "users-permissions" failed
[2020-03-17T13:27:10.999Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

**Comment by angelsalvadordev** [comment]
In config / environments / development / database.json put the following in the "options" braces:

`
"options": {
       "pool": {
             "min": 0,
              "max": 15,
               "idleTimeoutMillis": 30000,
               "createTimeoutMillis": 30000,
              "acquireTimeoutMillis": 30000
        }
}
`

**Comment by angelsalvadordev** [comment]
> > I managed to solve by looking at an issue
> > ```js
> > "options":{
> >       "pool":{
> >             "min":0,
> >              "max":15,
> >               "idleTimeoutMillis":30000,
> >               "createTimeoutMillis":30000,
> >              "acquireTimeoutMillis":30000
> >        }
> > }
> > ```
> 
> Can you please give more info on solution ?
> I have just the same problem with fresh install under linux.
> What should I fix ? Where?
> 
> ```
> [2020-03-17T13:27:10.998Z] error Bootstrap function in plugin "users-permissions" failed
> [2020-03-17T13:27:10.999Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
> ```

Place it in the "options" braces of the database.json file found in config / environments / development / database.json

**Comment by nahumobregon** [comment]
thanks

**Comment by vinitbolla10** [comment]
its is still giving the same error

**Comment by pbindisramos** [comment]
thanks! worked for me

**Comment by macleysousa** [comment]
> its is still giving the same error

delete all tables of database.

**Comment by guhandelta** [comment]
I am not quite sure what's causing this error, I even get the same log, even after I clear everything in database.json and just have module.exports = () => {}

This is the first this I'm using strapi, can anyone help me understand/resolve this issue? 

![image](https://user-images.githubusercontent.com/17257834/84092102-6f0c9080-a9c4-11ea-9d2d-11a9b1f58e27.png)

**Comment by PhantomxJoker** [comment]
I'm stucked too, but my issue is a little different:

`[2020-06-11T23:01:39.375Z] error Bootstrap function in plugin "users-permissions" failed
[2020-06-11T23:01:39.376Z] error TypeError: Cannot read property '_id' of undefined
    at dbPermissions.map.p (/usr/src/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:267:59)
    at Array.map (<anonymous>)
    at Object.updatePermissions (/usr/src/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:266:46)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
`

Has somebody something like this?

**Comment by ronit-mukherjee** [comment]
> I'm stucked too, but my issue is a little different:
> 
> `[2020-06-11T23:01:39.375Z] error Bootstrap function in plugin "users-permissions" failed [2020-06-11T23:01:39.376Z] error TypeError: Cannot read property '_id' of undefined at dbPermissions.map.p (/usr/src/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:267:59) at Array.map (<anonymous>) at Object.updatePermissions (/usr/src/app/node_modules/strapi-plugin-users-permissions/services/UsersPermissions.js:266:46) at processTicksAndRejections (internal/process/task_queues.js:86:5) `
> 
> Has somebody something like this?

I also facing the same issue

**Comment by fredrekt** [comment]
if all those don't work, try deleting the users-permissions_permission table/collection, worked for me.

**Comment by derrickmehaffy** [comment]
@PhantomxJoker and @ronit-mukherjee I take it you were updating from a previous beta version, I think you missed a part in one of the migration guides: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.19-to-beta.19.4.html#route-syntax-changes

**Comment by MarcosSarges** [comment]
```
db.getCollection("users-permissions_permission").find({ role: null }).forEach(it => {
    db.getCollection("users-permissions_permission").deleteOne({ _id: it._id })
})
```

https://github.com/strapi/strapi/issues/5460#issuecomment-642977507

Use is code per delete all role null

**Comment by antongavrilenkov** [comment]
This function helped me to fix the issue. I started with @MarcosSarges solution and finished with deleting all records from the "users-permissions_permission" table.

```
async function strapiFix() { 
  let allRecords = await db.collection("users-permissions_permission").find().toArray(); 
	
  for (record of allRecords) { 
    await db.collection("users-permissions_permission").deleteOne({ _id: record._id })
  }  
}
```

**Comment by monkey-company** [comment]
for PostgreSQL :

`DELETE FROM public."users-permissions_permission" WHERE "role" IS NULL`

**Comment by Louvki** [comment]
Facing similiar issue. None of the solutions helped so far.
Setup is Postgres on AWS RDS

`error error: select distinct "strapi_permission".* from "strapi_permission" left join ""."public"."strapi_role" as "strapi_role_1" on "strapi_role_1"."id" = "strapi_permission"."role" where "strapi_permission"."subject" = $1 and "strapi_permission"."action" in ($2, $3, $4, $5) and "strapi_role_1"."id" = $6 limit $7 - zero-length delimited identifier at or near """"`

**Comment by Radmehr-aghdam** [comment]
I had this issue too. 
Delete database and build admin panel again. after that you can upload your db :)
