### ISSUE TITLE
error on content type

### ISSUE THREAD

**Issue by mjodeh** [strapi/strapi#5462]
**Describe the bug**
Add a field of type text in a content type and make it a required and unique field, then delete this field from the content type, only 1 time an insertion will be successful and the next insertion will give `fieldname` is duplicate!

**Expected behavior**
When a field is removed from a content type is should be deleted also from the db

**System**
- Node.js version: v12.13.0
- NPM version:
- Strapi version: 3.0.0-beta.18.3
- Database: mongodb
- Operating system: ubuntu

**Comment by lauriejim** [comment]
Hello! An issue already exist about that.
This is due to this point - https://github.com/strapi/strapi/issues/1114
We are not removing the required/unique constraints, you will have to manually do it.
