### ISSUE TITLE
Strapi doesn't check for reserved words "Media"

### ISSUE THREAD

**Issue by lucguislain** [strapi/strapi#5464]
**Describe the issues**
Strapi doesn't check for reserved words like "media" [new collection].

**Steps to reproduce the behavior**
1. Go to 'new collection type'
2. Call it 'Media'
3. Add several fields and save it.
4. The server doesn't restart, need to rename api/media and edit all files.

[2020-03-08T08:10:00.269Z] info File created: ..\strapi\backend\api\media\controllers\media.js
[2020-03-08T08:10:03.414Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-08T08:10:03.416Z] error Error: Field "Query.media" can only be defined once.

**Expected behaviour**
Strapi should rise an error or report the use of reserved/already used words.

**System**
- Node.js version: V12.16.1
- NPM version: 6.14.2
- Strapi version: v12.16.1
- Database: Sqlite
- Operating system: Windows 10

**Comment by PolMrt** [comment]
It used to have a fix #3471.
May help to fix 🙂

**Comment by derrickmehaffy** [comment]
gonna close as a duplicate of https://github.com/strapi/strapi/issues/1198
