### ISSUE TITLE
`strapi "install" "graphql"  error code ELIFECYCLE

### ISSUE THREAD

**Issue by linjinxing** [strapi/strapi#5468]
**Describe the bug**
[2020-03-09T01:21:08.348Z] error Error: Command failed: npm run strapi -- install graphql
- Installing dependencies
✔ Installing dependencies
- Rebuilding admin UI
Command failed: npm run build

> strapi-demo@0.1.0 build /home/admin/nodejs/strapi-demo
> strapi build

Building your admin UI with development configuration ...
ℹ Compiling Webpack

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-demo@0.1.0 strapi: `strapi "install" "graphql"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-demo@0.1.0 strapi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-09T01_21_08_147Z-debug.log

> strapi-demo@0.1.0 strapi /home/admin/nodejs/strapi-demo
> strapi "install" "graphql"

    at makeError (/home/admin/nodejs/strapi-demo/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/admin/nodejs/strapi-demo/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Steps to reproduce the behavior**
download graphql in the marketplace-plugins.

**Expected behavior**
installation is successful.

**System**
- Node.js version: 
[root@VM_0_6_centos ~]# node --version
v10.16.3
- NPM version: 
[root@VM_0_6_centos ~]# npm -v
6.9.0
- Strapi version: 
- Database:sqlite
- Operating system:
[root@VM_0_6_centos ~]# cat /proc/version
Linux version 3.10.0-957.21.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue Jun 18 16:35:19 UTC 2019

**Additional context**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'strapi',
1 verbose cli   '--',
1 verbose cli   'install',
1 verbose cli   'graphql' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestrapi', 'strapi', 'poststrapi' ]
5 info lifecycle strapi-demo@0.1.0~prestrapi: strapi-demo@0.1.0
6 info lifecycle strapi-demo@0.1.0~strapi: strapi-demo@0.1.0
7 verbose lifecycle strapi-demo@0.1.0~strapi: unsafe-perm in lifecycle true
8 verbose lifecycle strapi-demo@0.1.0~strapi: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/admin/nodejs/strapi-demo/node_modules/.bin:/home/admin/nodejs/strapi-demo/node_modules/.bin:/home/admin/nodejs/node_modules/.bin:/home/admin/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/usr/bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/admin/nodejs/strapi-demo/node_modules/.bin:/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin:/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin:/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.el7_6.x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle strapi-demo@0.1.0~strapi: CWD: /home/admin/nodejs/strapi-demo
10 silly lifecycle strapi-demo@0.1.0~strapi: Args: [ '-c', 'strapi "install" "graphql"' ]
11 silly lifecycle strapi-demo@0.1.0~strapi: Returned: code: 1  signal: null
12 info lifecycle strapi-demo@0.1.0~strapi: Failed to exec strapi script
13 verbose stack Error: strapi-demo@0.1.0 strapi: `strapi "install" "graphql"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid strapi-demo@0.1.0
15 verbose cwd /home/admin/nodejs/strapi-demo
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "strapi" "--" "install" "graphql"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error strapi-demo@0.1.0 strapi: `strapi "install" "graphql"`
22 error Exit status 1
23 error Failed at the strapi-demo@0.1.0 strapi script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Can you please update your issue body to make it readable, please.

**Comment by derrickmehaffy** [comment]
I'm going to mark this issue as closed, if you are still having problems please feel free to reply back and follow @lauriejim 's instructions. thank you!

**Comment by arvi** [comment]
I am having the same issue with `Version: 3.0.0-beta.20.3 (node v10.15.3)`

```bash
[2020-05-19T12:48:47.560Z] info Installing graphql...
[2020-05-19T12:50:01.058Z] info File changed: /Users/me/strapi-mysql
[2020-05-19T12:50:02.068Z] info File changed: /Users/me/strapi-mysql/yarn.lock
[2020-05-19T12:50:02.068Z] info File changed: /Users/me/strapi-mysql/package.json
[2020-05-19T12:50:47.577Z] info Installing graphql...
[2020-05-19T12:51:02.793Z] info File changed: /Users/me/strapi-mysql/package.json
[2020-05-19T12:51:02.850Z] info File changed: /Users/me/strapi-mysql/package.json
error Error: Command failed: npm run strapi -- install graphql
- Installing dependencies
✔ Installing dependencies
- Rebuilding admin UI
Command failed: npm run build
Error: Module not found: Error: Can't resolve './CategoryName' in '/Users/me/strapi-mysql/.cache/plugins/strapi-plugin-content-type-builder/admin/src/components/ComponentSelect'
    at compiler.run (/Users/me/strapi-mysql/node_modules/strapi-admin/index.js:67:23)
    at finalCallback (/Users/me/strapi-mysql/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/me/strapi-mysql/node_modules/webpack/lib/Compiler.js:265:20)
    at hooks.make.callAsync.err (/Users/me/strapi-mysql/node_modules/webpack/lib/Compiler.js:670:21)
    at _err1 (eval at create (/Users/me/strapi-mysql/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at _addModuleChain (/Users/me/strapi-mysql/node_modules/webpack/lib/Compilation.js:1173:13)
    at processModuleDependencies.err (/Users/me/strapi-mysql/node_modules/webpack/lib/Compilation.js:1096:25)
    at asyncLib.forEach.err (/Users/me/strapi-mysql/node_modules/webpack/lib/Compilation.js:1017:13)
    at /Users/me/strapi-mysql/node_modules/neo-async/async.js:2830:7
    at /Users/me/strapi-mysql/node_modules/neo-async/async.js:2830:7
    at done (/Users/me/strapi-mysql/node_modules/neo-async/async.js:2863:11)
    at /Users/me/strapi-mysql/node_modules/neo-async/async.js:2818:7
    at asyncLib.forEach.err (/Users/me/strapi-mysql/node_modules/webpack/lib/Compilation.js:1017:13)
    at /Users/me/strapi-mysql/node_modules/neo-async/async.js:2830:7
    at /Users/me/strapi-mysql/node_modules/neo-async/async.js:2830:7
    at done (/Users/me/strapi-mysql/node_modules/neo-async/async.js:2863:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-mysql@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-mysql@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-05-19T12_51_08_855Z-debug.log


> strapi-mysql@0.1.0 build /Users/me/strapi-mysql
> strapi build

Building your admin UI with development configuration ...
ℹ Compiling Webpack

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-mysql@0.1.0 strapi: `strapi "install" "graphql"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-mysql@0.1.0 strapi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-05-19T12_51_08_908Z-debug.log


> strapi-mysql@0.1.0 strapi /Users/me/strapi-mysql
> strapi "install" "graphql"


    at makeError (/Users/me/strapi-mysql/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/me/strapi-mysql/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by derrickmehaffy** [comment]
@arvi can you provide your package.json?

**Comment by arvi** [comment]
Hello @derrickmehaffy ,

`package.json`
```json
{
  "name": "strapi-mysql",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "mysql": "latest",
    "strapi": "3.0.0-beta.20.3",
    "strapi-admin": "3.0.0-beta.20.3",
    "strapi-connector-bookshelf": "3.0.0-beta.20.3",
    "strapi-plugin-content-manager": "3.0.0-beta.20.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.3",
    "strapi-plugin-email": "3.0.0-beta.20.3",
    "strapi-plugin-graphql": "3.0.0-beta.20.3",
    "strapi-plugin-upload": "3.0.0-beta.20.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.3",
    "strapi-utils": "3.0.0-beta.20.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "0036dc06-fdc5-4503-8b0a-2401312cc2fb"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

---

` /Users/me/.npm/_logs/2020-05-19T12_51_08_908Z-debug.log`

```bash
9 verbose lifecycle strapi-mysql@0.1.0~strapi: CWD: /Users/me/strapi-mysql
10 silly lifecycle strapi-mysql@0.1.0~strapi: Args: [ '-c', 'strapi "install" "graphql"' ]
11 silly lifecycle strapi-mysql@0.1.0~strapi: Returned: code: 1  signal: null
12 info lifecycle strapi-mysql@0.1.0~strapi: Failed to exec strapi script
13 verbose stack Error: strapi-mysql@0.1.0 strapi: `strapi "install" "graphql"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid strapi-mysql@0.1.0
15 verbose cwd /Users/me/strapi-mysql
16 verbose Darwin 18.7.0
17 verbose argv "/Users/me/.nvm/versions/node/v10.15.3/bin/node" "/Users/me/.nvm/versions/node/v10.15.3/bin/npm" "run" "strapi" "--" "install" "graphql"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error strapi-mysql@0.1.0 strapi: `strapi "install" "graphql"`
22 error Exit status 1
23 error Failed at the strapi-mysql@0.1.0 strapi script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by anumber8** [comment]
Hi,

I had the same error but it did install graphql. Try to go yoururl/graphql and see if it loads the UI and execute a test. I did and it worked fine.

**Comment by dilukangelosl** [comment]
Im trying to Run strapi on an AWS Instance and I cant get to install Graphql plugin 

```
Command failed: npm run build
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa0bb60 node::Abort() [node]
 2: 0xa0bf6c node::OnFatalError(char const*, char const*) [node]
 3: 0xb820fe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb82479 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2ee35  [node]
 6: 0xd2f4c6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd3bd45 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd3cbf5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3f6ac v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd0615b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x1047d9e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13cce79  [node]
```

Any solution for this ?

**Comment by derrickmehaffy** [comment]
@dilukangelosl `heap limit Allocation failed - JavaScript heap out of memory` how much ram does this EC2 instance have, it looks like it's hitting an error when trying to rebuild the admin panel. Strapi currently needs ~2GB of memory to build

**Comment by ace3** [comment]
Hi, for someone with a 1GB or less RAM VPS, but don't want to upgrade the VPS, you can fix this by adding swap to your box.
The guidelines are, if your ram is less than 2GB, add 2x of your current RAM.
If In your case your ram is 1GB, then Add the 2GB swap.
And don't forget to reboot the server after adding swap.

This also works if you want to build the production build of React/Vue.

**Comment by derrickmehaffy** [comment]
(Keep in mind, that while it may be possible, Strapi does not support 1GB Ram + 1GB of swap. If issues occur going forward, you will be recommended to use 2GB of RAM or build locally/in a CI/CD and commit into source control for those limitations)

**Comment by ace3** [comment]
yes, I agree with @derrickmehaffy, there is a performance cost by using the swap to replace the RAM.
