### ISSUE TITLE
Single type afterSave lifecycle callback not executing when update

### ISSUE THREAD

**Issue by kaluabentes** [strapi/strapi#5469]
I'm using afterSave lifecycle callback in my single type model, when I save a existing record the callback won't execute.

1. Create afterSave lifecycle callcaback
2. Create a single type
3. Try to edit and save the changes

**Comment by derrickmehaffy** [comment]
I am closing this issue and linking it to https://github.com/strapi/strapi/issues/1443 which is the complete tracking issue for all issues with lifecycle callbacks
