### ISSUE TITLE
strapi-provider-upload-aws-s3 fail with file >=2GB 

### ISSUE THREAD

**Issue by rawiki** [strapi/strapi#5470]
**Describe the bug**
Uploading large files over 2GB to AWS S3 or Digital Ocean Spaces fails with a buffer error. 

**Steps to reproduce the behavior**
1. Install strapi-provider-upload-aws-s3 and configure with bucket details
2. Go to file upload section. Attempt to upload >= 2GB  media file

**Expected behavior**
It should upload files without issue

**Code snippets**
The following is logged to the console -

```
error RangeError [ERR_INVALID_OPT_VALUE]: The value "2303644295" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:346:3)
    at Function.concat (buffer.js:531:25)
    at createBuffer (/Users/kokirikiri/development/backend/node_modules/strapi-plugin-upload/services/Upload.js:40:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async Object.upload (/Users/kokirikiri/development/backend/node_modules/strapi-plugin-upload/controllers/Upload.js:55:21)
    at async /Users/kokirikiri/development/backend/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:83:22
    at async module.exports (/Users/kokirikiri/development/backend/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:40:14)
    at async /Users/kokirikiri/development/backend/node_modules/strapi-utils/lib/policy.js:118:7
```

**System**
- Node.js version: v10.18.1 
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.4 / 3.0.0-beta.19.3
- Database: local sqlite3
- Operating system:Ubuntu 18.04.3 LTS

**Additional context**
Fails on my OSX dev machine as well as ubuntu server.

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-beta.18.4` Please test on the latest release.

**Comment by rawiki** [comment]
I've just upgraded to 3.0.0-beta.19.3 and same issue

**Comment by derrickmehaffy** [comment]
:thinking: I'm wondering if that integer value is too large, it should be in Mb not bytes (which is what that appears to be)

**Comment by derrickmehaffy** [comment]
In your node_modules can you directly add a console.log() before here: https://github.com/strapi/strapi/blob/a70991a37e8bd55573aa0497811ca958d14ce2e5/packages/strapi-plugin-upload/services/Upload.js#L40-L50

And try to log the `stream.size / 1000`

**Comment by rawiki** [comment]
The result of `console.log(stream.size / 1000)` for a 2.32GB file is `2303644.295`

**Comment by derrickmehaffy** [comment]
So something isn't right here then because your error is feeding back `2303644295` and your log is giving back `2303644.295`

The `2303644.295` is Kb whereas I'm guessing `2303644295` is Bytes. Strapi should be using Kb which is what that upload plugin is doing. Can you link your package.json here?

**Comment by rawiki** [comment]
```json
{
  "name": "backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@miscellaneous/strapi-provider-upload-do-spaces": "^2.5.0",
    "knex": "<0.20.0",
    "pg": "^7.17.1",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.19.3",
    "strapi-admin": "3.0.0-beta.19.3",
    "strapi-connector-bookshelf": "3.0.0-beta.19.3",
    "strapi-plugin-content-manager": "3.0.0-beta.19.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.19.3",
    "strapi-plugin-email": "3.0.0-beta.19.3",
    "strapi-plugin-upload": "3.0.0-beta.19.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.19.3",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.19.3",
    "strapi-utils": "3.0.0-beta.19.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "f569233d-66d4-4bf2-8925-760cedac6071"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by derrickmehaffy** [comment]
` "strapi-provider-upload-aws-s3": "^3.0.0-beta.19.3",` Please try removing the caret `^` from this package.

`"@miscellaneous/strapi-provider-upload-do-spaces": "^2.5.0",` This package is not one built by Strapi, if this is what you are using for storage you will need to contact the author of that plugin.

**Comment by rawiki** [comment]
The do-spaces plugin isn’t being used. Removing the caret and reinstalling the aws plugin doesn’t change the issue.

**Comment by lauriejim** [comment]
Hello, can you please check the value in your Upload plugin configuration for `Maximum size allowed (in MB)`

**Comment by rawiki** [comment]
It's set to 3000 MB

**Comment by lauriejim** [comment]
Hello! Did you find any thing about this?

**Comment by derrickmehaffy** [comment]
Hello!

As we have not received any new or updated information in over 7 days we are marking this issue/discussion as closed. Should you have new information please feel free to respond and we can consider reopening it.

For others finding this closed issue and you have updated information, please open up a new bug report and simply reference this closed bug report so that we can get any new information you may have. If you have questions please refer to the [contributor's guide]([https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue)) on opening issues.

Thank you and have a great day!

**Comment by darron1217** [comment]
I've exprienced same issue. I uploaded file bigger than 2GB then fail with error above.

This issue is related with Node.js(V8) buffer module.
https://nodejs.org/api/buffer.html#buffer_static_method_buffer_allocunsafe_size

Node's max buffer size is `0x7fffffff` which is `2147483647` bytes. The error is thrown from buffer module.
Maybe we should find another way to handle large files.

**Comment by darron1217** [comment]
However @derrickmehaffy would you re-open this issue?

**Comment by derrickmehaffy** [comment]
@darron1217 I would rather open up a new issue and reference this one as it's quite old and I want to start on a clean issue to try and debug it from the start. Could you open up a new bug report?

**Comment by darron1217** [comment]
@derrickmehaffy Got it 👍
