### ISSUE TITLE
Inconsistent count return

### ISSUE THREAD

**Issue by filipinyo** [strapi/strapi#5477]
**Describe the bug**
It's more of an improvement than a bug. calling count on upload files returns an object for an example: 

{
    "count": 12
}

while calling count on other routes returns a number. this should be consistent on every endpoint.

**Expected behavior**
Return the count number only and not the object.

**System**
- Node.js version: 10.9.0
- NPM version: 6.2.0
- Strapi version: beta 19.3
- Database: Mongodb
- Operating system: windows

**Comment by derrickmehaffy** [comment]
@alexandrebodin which way is intended here? I'm guessing just the number response, but I know you guys have been working on the upload plugin so wanted to make sure before I dig and submit a PR

**Comment by alexandrebodin** [comment]
IMO, We should return this format everywhere to have real integer with json instead of a strign a user needs to parse.

**Comment by derrickmehaffy** [comment]
It would be a breaking change but I don't disagree

**Comment by alexandrebodin** [comment]
I'm going to close this issue has this isn't a bug with strapi. We will be working on the APIs for the next major version of strapi but right now this doesn't create any bug for users.
