### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by NilakArgento** [strapi/strapi#548]
**Node.js version**:
v8.9.4
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.8.3
**Operating system**:
Ubuntu 14.04

Ok, let's start..
I used examples from docs "Authentication" for register and login new users. Now i have some content types like orders, payments, posts and others.
How to make some routes to be able to accessed only by authenticated users !? Now it's impossible, because the users by default has role like "Guest"

p.s. how to make update to alpha.9 ?!

**Comment by derrickmehaffy** [comment]
@NilakArgento Upgrading to alpha.9 guide: https://strapi.io/documentation/migration/migration-guide-alpha-8-to-alpha-9.html

**Comment by NilakArgento** [comment]
@derrickmehaffy i upgraded. thx for link)
Apart from roles: Administrator and Guest... we need something like "Registered".

Because some routes shouldn't be accessible by guests...and add a posibility to change default role for new registred users
Another idea will be the fields need to have a default value.

**Comment by lauriejim** [comment]
That's good point. 

Actually you can fix it by creating a new Registered role and update the `register` function to apply to your new users the Register role.

**Comment by storm1er** [comment]
@lauriejim That's what I did multiple times. But this issue just makes me realize that we shouldn't need to edit code to do this. It could be really awesome to deal roles attributions through UI =D

**Comment by lauriejim** [comment]
I'm agree with you @storm1er.

**Comment by acoreyj** [comment]
Under guest permissions you can set the isauthenticated policy to any permission to do this

**Comment by lauriejim** [comment]
UI to update default role on register is coming https://github.com/strapi/strapi/pull/773
