### ISSUE TITLE
Can't change field name in content type.

### ISSUE THREAD

**Issue by terepon4ikus** [strapi/strapi#5484]
**Describe the bug**
You cannot change the case of the created field.

**Steps to reproduce the behavior**
1. Create content type with text field, eg '**Test**', and save
2. Try change name of field 'Test' -> 'test'
3. Get error in terminal `Error: SQLITE_ERROR: duplicate column name: test`

**Expected behavior**
It is possible to change the case of the field name without errors.

**System**
- Node.js version: 10.19.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database: SQLite
- Operating system: Linux Fedora 30

**Comment by lauriejim** [comment]
Thank you for reporting this issue.
This is the same topic as this one - https://github.com/strapi/strapi/issues/5045
