### ISSUE TITLE
Move forgot password redirect URL in plugin settings

### ISSUE THREAD

**Issue by aalshaikh** [strapi/strapi#549]
i see in forget password in body request the client can set the url, i think it's wrong since because anyone can set the url and redirect user to fake website to get the code
i think the url should be set from the dashboard

**Comment by lauriejim** [comment]
Yes you are right. I think it's have to be moved on email template settings of the plugins users and permissions.

**Comment by lauriejim** [comment]
Actually to fix it, you will have to change the forgot password template and replace `HOST` variable by a static url.

**Comment by lauriejim** [comment]
Will have to use this advanced setting input for confirmation and forgot password redirection - https://github.com/strapi/strapi/pull/1733/files
