### ISSUE TITLE
Uninstalling plugins from admin panel shows downloading message

### ISSUE THREAD

**Issue by akashvibhute** [strapi/strapi#5490]
**Describe the bug**
When a plugin is uninstalled from admin panel, the overlay message is same as the one shown when installing a plugin. It should be different

**Steps to reproduce the behavior**
1. Go to Admin Panel
2. Click on plugins
3. Click on delete button for a plugin (e.g. graphql)
4. Confirm the delete pop up

**Expected behavior**
The message shown during plugin removal/deletion should say so, instead it says downloading

**Screenshots**
![image](https://user-images.githubusercontent.com/21662960/76390200-fe3ce480-6392-11ea-9dae-55d6cf83b753.png)

**Code snippets**

**System**
- Node.js version:  v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database: Postgres
- Operating system: Windows

It's not a major issue but should be noted.

**Comment by shabab477** [comment]
Would like to take a shot.

**Comment by MattieBelt** [comment]
@lauriejim / @akashvibhute Issue is fixed and can be closed
