### ISSUE TITLE
Cannot create custom resolvers in Users-Permissions

### ISSUE THREAD

**Issue by alhill** [strapi/strapi#5491]
**Describe the bug**
I have just migrated an API from 18.6 to 19.3 and custom resolvers located in users-permissions plugin make Strapi crash.

**Steps to reproduce the behavior**
1. Create /extensions/users-permissions/controllers/User.js with a controller for the custom resolver
```
module.exports = {
  async findPeople(ctx) {
    let entities;
    if (ctx.query._q) {
      entities = await strapi.query('user', 'users-permissions').search(ctx.query);
    }
    else {
      entities = await strapi.query('user', 'users-permissions').find(ctx.query);
    }
    return entities.map(entity => {
      const user = {
        id: entity.id,
        image: entity.image,
        name: entity.name,
        surname: entity.surname
      }

      return user;
    });
  }
}
```

2. Register the custom resolver in /extensions/users-permissions/config/schema.graphql
```
module.exports = {
  definition: `
    type User {
      id: ID!
      name: String
      surname: String
      image: JSON
    }
  `,
  query: `
    findPeople: [User]
  `,

  resolver: {
    Query: {
      findPeople: {
        description: 'Get all Users Info',
        resolver: {
          plugin: 'users-permissions',
          handler: 'User.findPeople'
        }
      }
    }
  }
}
```
3. Run Strapi

With this example, Strapi throws `TypeError: resolver.startsWith is not a function` when starting. If I try with a mutation (the example code is a truncated version of a bigger file, for clarity sake) the error changes to `Error: Error building query. Expected a string, got [object Object]`. The code shouldn't be a problem, all the custom resolvers are working just fine in Strapi Beta 18.6.

**System**
- Node.js version: v10.11
- NPM version: v6.4.1
- Strapi version: Beta 19.3
- Database: MongoDB 3.6.8
- Operating system: Amazon Linux AMI 2018.03

**Comment by alexandrebodin** [comment]
Hi @alhill, There is a missing information in the migration guide 🤦‍♂ our bad.

If you look at the doc [here](https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#customise-the-graphql-schema). You will see we changed the resolver declaration :) 

Will update the migration guide !

**Comment by flofleche** [comment]
> Hi @alhill, There is a missing information in the migration guide man_facepalming our bad.
> 
> If you look at the doc [here](https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#customise-the-graphql-schema). You will see we changed the resolver declaration :)
> 
> Will update the migration guide !

I actually couldn't find any updates in the related migration guide explaining how to proceed for a custom resolver in Users-Permissions plugin.
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.html

Me too I got the following message after migrating from `18.6` to `19` : 
`Error: Error building query. Expected a string, got [object Object]` 

Maybe have you forget about updating it ;) ?
Would be a great help if you could add it to the migration guide anyway !?

Thanks for your nice work always at Strapi.io

**Comment by DennisWanjiru** [comment]
What was the fix to this cause looks like the docs links provided are not working anymore.

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/developer-docs/latest/update-migration-guides/migration-guides/migration-guide-beta.18-to-beta.19.html
