### ISSUE TITLE
Sort by size in files upload working incorrectly

### ISSUE THREAD

**Issue by gavmck** [strapi/strapi#5498]
**Describe the bug**
If you go to Admin -> files upload and sort by size, the sizes are not sorted correctly. I'm not sure what method is being used, but they seem semi-random.

**Expected behavior**
It should sort in the correct order.

**Screenshots**
<img width="112" alt="Screenshot 2020-03-12 at 14 47 05" src="https://user-images.githubusercontent.com/800251/76533700-5e558880-6470-11ea-9e7e-bdd057eda5b6.png">

**System**
- Node.js version: 12.6.0
- Strapi version: 3.0.0-beta.18.6
- Database: Postgres
- Operating system: Unix

**Comment by lauriejim** [comment]
Hello @gavmck !
This issue has been fixed, can you please update your application.
Migration guides are into the documentation.
Thank you.

**Comment by gavmck** [comment]
Thanks!
