### ISSUE TITLE
Can't save content with relation ?

### ISSUE THREAD

**Issue by storm1er** [strapi/strapi#550]
**Node.js version**:
v8.9.4
**npm version**:
5.6.0
**Strapi version**:
v3.0.0 alpha 9
**Operating system**:
Ubuntu 16.04

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We can't save content with relation ?

**If the current behavior is a bug, please provide the steps to reproduce the problem**

Step by step : 
- Install strapi
- `strapi new strapidev --dev`
- create those content type (through gui) : 
- Account : 

<details>

```json

{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "account",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "creation": {
      "type": "date",
      "required": true
    },
    "amount": {
      "type": "decimal",
      "required": true
    },
    "owner": {
      "model": "user",
      "via": "accounts",
      "plugin": "users-permissions"
    },
    "lines": {
      "collection": "line",
      "via": "account"
    }
  }
}

```

</details>

- Line : 

<details>

```json

{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "line",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "description": {
      "type": "text"
    },
    "amount": {
      "type": "decimal",
      "required": true
    },
    "account": {
      "model": "account",
      "via": "lines"
    }
  }
}

```

</details>

- This result in user model : 

<details>

```json

{
  "connection": "default",
  "info": {
    "name": "user",
    "description": ""
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "accounts": {
      "collection": "account",
      "via": "owner"
    }
  }
}


```

</details>   
   

   
- Then try to create an account with you as owner of it.
- I'm getting an error, getting this through network dev tab : 

<details>

```json
{  
  "statusCode":400,
  "error":"Bad Request",
  "message":[  
    {  
      "messages":[  
        {  
          "id":"This Account,validation,failed,amount,Path,amount,is,required is already taken",
          "field":[  
            "Account",
            "validation",
            "failed",
            "amount",
            "Path",
            "amount",
            "is",
            "required"
          ]
        }
      ]
    }
  ]
}
```

</details>

**Comment by storm1er** [comment]
Just realized that `"collectionName": "",` is always empty ... is that normal ?

**Comment by storm1er** [comment]
Mongodb, here are the settings : 

<details>

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-mongoose",
      "settings": {
        "client": "mongo",
        "host": "localhost",
        "port": 27017,
        "database": "strapidev",
        "username": "",
        "password": ""
      },
      "options": {}
    }
  }
}
```

</details>

**Comment by Redni** [comment]
I noticed something similar.

Arch Linux, Node v9.5.0, Npm: 5.6.0, Strapi: 3.0.0-alpha.9.1

### 1. Content Type
**Name:** letter
**Fields:**

- String: pol
- String: eng

### 2. Content Type
**Name:** word
**Fields:**
- String: one

**Relation:** 
-  Field name: world
-  Field name: letter

**_Words has and belongs to many Letters_**

And when you click to save or try to start, the console throws:

`ERROR (2407 on comp): Something went wrong in the model "word" with the attribute "letter"`

I tried many combinations of relationships and everyone throws an error. Interestingly, I've done the "Articles" relationship with "Users" before and there is no problem here. From what I noticed, at least for me, it is impossible to save any relations except those of Users.

**Comment by storm1er** [comment]
@lauriejim 
Having the col' name "amount" in two different table, linked with a relation, seems to be the problem.  
When removing "amount" col from amount, or line, make the app working as expected.

**Comment by lauriejim** [comment]
@storm1er Your issue is related to `required` settings on you models. To hot fix it, juste delete `"required": true` in your models.

**Comment by Aurelsicoko** [comment]
@redni In your case, it's because the relations hasn't be made correctly. Check again your models and the documentation.

@storm1er Change the type `Decimal` to `Float`. And it works. The Decimal type is not well supported by Mongo and the implementation seems not optimal right now.
