### ISSUE TITLE
SQLITE_ERROR: duplicate column name: Name

### ISSUE THREAD

**Issue by golfhotel** [strapi/strapi#5501]
**Describe the bug**
When I rename a model option, the database stops working.

**Steps to reproduce the behavior**
I followed this [Strapi guide](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html#_2-create-an-administrator-user). All software is at the latest version. In step 3 fill in all the fields as described in the guide. Everything ends successfully.
Now, if I try to change the object option, the problem occurs.
1. In the ```restaurant``` click on ```Name``` option 
2. I rename the name field by changing it from ```name``` to ```Name```.
3. Click ```Finish```.
4. Click ```Save``` button and wait for Strapi to restart.
5. From the Strapi administrative page I have a server message `The restart is taking longer than expected. The server needs to be restarted, please check your logs in the terminal.`
6. From the SSH terminal I have the following message: 
   `error Impossible to register the 'restaurant' model`
   `error Error: SQLITE_ERROR: duplicate column name: Name`

**Screenshots**
![error](https://user-images.githubusercontent.com/7843301/76588288-f1c9a080-64e6-11ea-8a18-9145ecbccd38.jpg)

**System**
![system](https://user-images.githubusercontent.com/7843301/76588299-fb530880-64e6-11ea-8469-2f3cb485c7e4.png)
Strapi software is at last version. 

**Additional context**
The test was performed 3 times and each time I performed a new installation of the virtual machine and the related software required in the prerequisites of the guide.

Best regards.

**Comment by derrickmehaffy** [comment]
Closing as duplicate: https://github.com/strapi/strapi/issues/1114
