### ISSUE TITLE
Add content type button is missing

### ISSUE THREAD

**Issue by alex-mironov** [strapi/strapi#5509]
I'm using strapi v3.0.0-beta.19.3. Apparently I cannot create a new content type, "Add content type" button is missing:
<img width="1440" alt="Screen Shot 2020-03-15 at 16 27 36" src="https://user-images.githubusercontent.com/2544767/76703387-1c2f7f80-66da-11ea-9df4-ca9df8841178.png">

**Comment by MattieBelt** [comment]
@alex-mironov You are probably in production mode, where the creation/editing of content (collection) types is disabled. This is because creating/editing content types changes database and the code. Also production-apps don't always have permissions to change files.

**Comment by elirodrigues** [comment]
I'm still trying to find out how to open it in development mode, since the command "strapi start dev" doesn't change anything.
 I've installed with quickstart and, after long hours, found out how to deploy it to heroku + mongo atlas. When it finally happened, I've discovered I couldn't create new "content types". 
Now I'm looking for a way to create it locally, the app runs local, but still the button "create content type" doesn't apper.

**Comment by lauriejim** [comment]
Hello commands are 
- `yarn develop`
- `yarn start`

`strapi start dev` doesn't exist.

**Comment by elirodrigues** [comment]
It has been working well with:

**npm run develop --watch-admin**

Ty

**Comment by LucasAndrad** [comment]
Is this already present on the documentation? It should be.
This different behavior on production totally makes sense, but it's not trivial.

**Comment by MattieBelt** [comment]
@LucasAndrad [here](https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging), but I'm not sure if this is the best place. Where would you suggest it should be mentioned?

**Comment by samithw** [comment]
I had the same issue. Even though it shows that you are on development mode below, when you try to add a content type - it doesn't show Create new content type button.
![image](https://user-images.githubusercontent.com/8359114/87908513-21377d80-ca84-11ea-9956-7ad4c4d1d2c6.png)

Only thing which got this fixed was setting the NODE_ENV to development before starting the server through command prompt. 

**`set NODE_ENV=development`
`npm run develop`**


Note : NODE_ENV is set to development by default, but for some reason it doesn't work without setting it again. I'm new to this maybe some one else can explain what is exactly happening here.

**Comment by reza-ebrahimi** [comment]
The issue still exists in `development` environment for `Heroku` deployment.

**Comment by ProHashim** [comment]
![image](https://user-images.githubusercontent.com/56976652/172040067-0d28361c-58eb-43c8-adc2-732897dccb49.png)
I had some problem, I ran `npm run develop` and it worked.
