### ISSUE TITLE
cannot create models, only responce 500 erros on build

### ISSUE THREAD

**Issue by dareksob** [strapi/strapi#551]
.**Node.js version**: 8.3.0

**npm version**:

**Strapi version**: 3.0.0-alpha.9

**Operating system**:windows 10

**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
cannot save properties by admin tools

**If the current behavior is a bug, please provide the steps to reproduce the problem**
strapi new PROJECT
(local mongo database)
on backend create new api and try to create new properties. Nothing will create only the api root will be created

on list view i get only critical errors.

**Comment by lauriejim** [comment]
Can you give me the `PUT` request parameters you send and the error message you receive.
You will have to inspect you browser network.

**Comment by lauriejim** [comment]
@dareksob Can you give us an update about your issue please.

**Comment by dareksob** [comment]
Hi @lauriejim sorry for the long wait. 
I try the issue with the latest version of stapi (strapi@3.0.0-alpha.10.2) and a newer version of node (v8.9.4) wth the same setup. This time a can create the content types over the backend, without problem. I only response (fails) on _health request two times, but wasn't any side effect on saving or update process.
Bug is closed 👍
