### ISSUE TITLE
failed to create a custom project with mongo

### ISSUE THREAD

**Issue by StevenYuysy** [strapi/strapi#5512]
**Describe the bug**

Failed to create a custom project with mongo choice.

**Steps to reproduce the behavior**

```bash
yarn create strapi-app strapi-project
```

choose custom and use mongo client.

```bash

? Choose your installation type Custom (manual settings)
? Choose your default database client mongo
? Database name: strapi
? Host: 127.0.0.1
? +srv connection: false
? Port (It will be ignored if you enable +srv): 27017
? Username:
? Password:
? Authentication database (Maybe "admin" or blank):
? Enable SSL connection: No
```

then I got following error.

```bash
⛔️ Connection test failed: Command failed: yarnpkg --cwd /var/folders/ld/8g745xy94bs9jq944z81m4mh0000gp/T/strapi3a6ffb7ed9c2 add strapi-connector-mongoose@3.0.0-beta.19.3
(node:68668) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add add strapi-connector-mongoose@3.0.0-beta.19.3" instead.
```

**Expected behavior**

It should create successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/11738111/76740136-5a937000-67a8-11ea-8093-7449feb05de1.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version:  12.16.1
- NPM version: 6.13.4
- Strapi version: 
- Database: MongoDB
- Operating system: MacOS

**Additional context**

**Comment by derrickmehaffy** [comment]
What version of yarn are you using?

**Comment by aksdevac** [comment]
Hi, upgrade for Yarn to `1.22`, it seems `0.24.6` seems to Old. it should work fine after that, I just tried.

**Comment by StevenYuysy** [comment]
Fixed it after upgraded Yarn. Thx!
