### ISSUE TITLE
Unable to delete content type

### ISSUE THREAD

**Issue by anthonyatp** [strapi/strapi#5513]
**Describe the bug**
For some reason, I was able to create a content type with spaces in the dev admin panel:
![image](https://user-images.githubusercontent.com/42555665/76747032-682d0380-6770-11ea-8afc-47ad46c7eadb.png)

I delete all the changes I made in the code and restarted the server, however the content type is still there. What's even stranger is if I log in to the admin panel in production, it is still there! Even though I delete all my code and no changes were pushed to production.

I have cleared my cache and cookies and even tried a completely different browser but it's still there.

Any idea's as to why this is happening?

**Screenshots**
![image](https://user-images.githubusercontent.com/42555665/76747426-028d4700-6771-11ea-8322-4f23fb027a37.png)

**System**
- Node.js version: 10.19.0
- Strapi version: 3.0.0-beta.6

**Comment by derrickmehaffy** [comment]
`3.0.0-beta.6` you are on an extremely old version. Please update to the latest or test with the latest version (fresh project) and confirm the bug.
