### ISSUE TITLE
Relational field in component has an extra col-6 div

### ISSUE THREAD

**Issue by gavmck** [strapi/strapi#5514]
**Describe the bug**
I have a component which includes a relation field. When configuring the view, the component is wrapped with two `<div class="col-6">` causing its padding and width to be off.

**Steps to reproduce the behavior**
1. Create a group component
2. Add a relation field to that component
3. Configure the view
4. Add the component group to a base content type
5. Look at the component group in the base content type new/edit view.

**Expected behavior**
It should lay out like it says it will in the "configure the layout" view.

**Screenshots**
<img width="285" alt="Screenshot 2020-03-16 at 12 12 04" src="https://user-images.githubusercontent.com/800251/76757615-c7464480-677f-11ea-9cf3-fff6664024b2.png">
<img width="631" alt="Screenshot 2020-03-16 at 12 15 21" src="https://user-images.githubusercontent.com/800251/76757636-d3ca9d00-677f-11ea-9ba1-d7873f6aa52d.png">

**System**
- Node.js version: 12.6
- Strapi version: 3.0.0-beta.18.6
- Database: Postgres
- Operating system: Unix

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-beta.18.6` Please test on the latest version as this one is a bit older

Current latest is beta.19.3

**Comment by gavmck** [comment]
Ah I think I see the fix for this in beta 19
Let me update and get back to you.

**Comment by lauriejim** [comment]
Hello, no news, I suppose it should be OK on the last version.
Will re-open if it's not OK.

**Comment by gavmck** [comment]
Thanks, we have some work to do to be able to update Strapi, but I'll pop back in here when it's done
