### ISSUE TITLE
error The client `undefined` for the `default` connection is not supported.

### ISSUE THREAD

**Issue by anthonyatp** [strapi/strapi#5517]
**Describe the bug**
I recently upgraded strapi from `v3.0.0-beta.6` to `v3.0.0-beta.19.3`. I have followed the migration guides but when I run `yarn run develop` I get the error:
```
error The client `undefined` for the `default` connection is not supported.
```

Here's what my `config/environments/{env}/database.json` file looks like:

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "settings": {
        "database": "**********",
        "ssl": true,
        "uri": "${process.env.DATABASE_URL}"
      },
      "options": {
        "ssl": "true"
      },
      "connector": "bookshelf"
    }
  }
}
```

Any ideas what is causing this error?

Thanks!

**Comment by derrickmehaffy** [comment]
You are missing the client part under settings:

https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#database

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "host": "localhost",
        "port": 5432,
        "username": "${process.env.USERNAME}",
        "password": "${process.env.PASSWORD}",
        "database": "strapi",
        "schema": "public"
      },
      "options": {
        "debug": true
      }
    }
  }
}
```

**Comment by JoaoGadelha** [comment]
Any update for the newest version of Strapi  ? This solution doesnt fit it, and I'm having the same error message : ```error The client `undefined` for the `default` connection is not supported.```

**Comment by ahmadjoya** [comment]
I have the same error and my database.js is

```
const { parse } = require("pg-connection-string");

module.exports = ({ env }) => {
  const { host, port, database, user, password } = parse(env("DATABASE_URL"));

  return {
    defaultConnection: "default",
    connections: {
      default: {
        connector: "bookshelf",
        settings: {
          client: "postgres",
          host,
          port,
          database,
          username: user,
          password,
          ssl: { rejectUnauthorized: false },
          options: {
            ssl: false,
          },
        },
      },
    },
  };
};
```

But still the same error

**Comment by JoaoGadelha** [comment]
I fixed it by setting the host, database, username, client, etc.... You got to input the database credentials, for example, in my case I had something like this :
```
settings: {
          client: "postgres",
          host: "localhost",
          port: 5432,
          database: "postgres",
          username: "postgres",
          password: 1234abcd,
          ssl: { rejectUnauthorized: false },
          options: {
            ssl: false,
          },
        },
```

**Comment by derrickmehaffy** [comment]
> I have the same error and my database.js is
> 
> ```
> const { parse } = require("pg-connection-string");
> 
> module.exports = ({ env }) => {
>   const { host, port, database, user, password } = parse(env("DATABASE_URL"));
> 
>   return {
>     defaultConnection: "default",
>     connections: {
>       default: {
>         connector: "bookshelf",
>         settings: {
>           client: "postgres",
>           host,
>           port,
>           database,
>           username: user,
>           password,
>           ssl: { rejectUnauthorized: false },
>           options: {
>             ssl: false,
>           },
>         },
>       },
>     },
>   };
> };
> ```
> 
> But still the same error

I'd suggest handling it like this instead:

```js
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: config.host,
        port: config.port,
        database: config.database,
        username: config.user,
        password: config.password,
        ssl: {
          rejectUnauthorized: false,
        },
      },
      options: {
        ssl: true,
      },
    },
  },
});
```

**Comment by roshankhandelwal** [comment]
With v4 - 
Running complex queries would update to - 

`await strapi.db.connection.raw( ' **** ' ) `FROM `await strapi.connections.default.raw ( ' **** ' )`

Posting it here - since the database.js has changed considerably and does not work with a connections object anymore.

**Comment by ngoclammevn** [comment]
In my case
- The problem comes from the Nodejs package
So I upgrade the package strapi in file `package.json`
- Change package `strapi-hook-bookshelf` -> `strapi-connector-bookshelf`
Because package `strapi-hook-bookshelf` has been deprecated
Also change `"connector": "strapi-hook-bookshelf" `->  `"connector": "bookshelf"` in config strapi
