### ISSUE TITLE
TypeError: user.toJSON is not a function

### ISSUE THREAD

**Issue by sm4rtie** [strapi/strapi#552]
**Node.js version**:
v8.9.4
**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.8.3
**Operating system**:
Ubuntu 17.10

**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
getting error 'TypeError: user.toJSON is not a function' when trying to send email with resetPasswordToken using /auth/forgot-password
**If the current behavior is a bug, please provide the steps to reproduce the problem**
creating an ajax call to url: '/auth/forgot-password' with email and url in data, getting error 'TypeError: user.toJSON is not a function'. user object isn't null. Probably something goes wrong when trying to insert data into email template? I have mailgun configured, other contact form works.
**What is the expected behavior?**
sending email with reset password token

**Comment by M1chaelTran** [comment]
hey @sm4rtie, I ran into the same issue as you.
Found out why I got the error and raised a PR for the fix.

On a different question for you, you mentioned you have configured mailgun...
Could you share the detail on how you set it up? I would like to do the same.
Thanks

**Comment by sm4rtie** [comment]
sure :) npm install mailgun-js
``` 'use strict';

/**
 * Email.js service
 *
 * @description: A set of functions similar to controller's actions to avoid code duplication.
 */
 const _ = require('lodash');
 const mailgun = require('mailgun-js')({apiKey: 'your-api-key', domain: 'sandbox-etcetera'});

 module.exports = {
 send: (options, cb) => {
   var data = {
  from: options.from || '"Administration Panel" <no-reply@strapi.io>',
  to: options.to,
  subject: options.subject,
  text: options.text,
  html: options.html
};
mailgun.messages().send(data, function (error, body) {
  console.log(body);

});
 } ```

and in auth/forgotPassword(i think it was automatically generated) 
```

const { email, url } = ctx.request.body;
/* ... */
try {
      // Send an email to the user.
      await strapi.plugins['email'].services.email.send({
        to: user.email,
        from: (settings.from.email || settings.from.name) ? `"${settings.from.name}" <${settings.from.email}>` : undefined,
        replyTo: settings.response_email,
        subject: settings.object,
        text: settings.message,
        html: settings.message
      });
    } catch (err) {
      return ctx.badRequest(null, err);
    }
```
