### ISSUE TITLE
strapi auth login local identifier or password invalid

### ISSUE THREAD

**Issue by paltur** [strapi/strapi#5521]
Strapi version: 3.0.0-alpha.26.0
Database: mongo
Operating system: Windows

Registration work but login not work
  void _registerUser() async {
    setState(() => _isSubmitting = true);
    http.Response response = await http.post(
        'http://192.168.1.100:1337/auth/local',
        body: {"identifier": _email, "password": _password});
    final responseData = json.decode(response.body);
    if (response.statusCode == 200) {
      setState(() => _isSubmitting = false);
      _showSuccessSnack();
      _redirectUser();
      print(responseData);
    } else {
      setState(() => _isSubmitting = false);
      final String errorMsg = responseData['message'];
      _showErrorSnack(errorMsg);
    }
  }

**Comment by derrickmehaffy** [comment]
@paltur the Strapi Alpha versions are no longer supported.

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by jscontreras** [comment]
Here is another pretty well documented case. (Is the official Strapi - Tina CMS integration)
It seems like the API changed.

https://tina.io/guides/nextjs/tina-with-strapi/authenticating-with-strapi/
```
{statusCode: 400, error: "Bad Request",…}
data: [{messages: [{id: "Auth.form.error.invalid", message: "Identifier or password invalid."}]}]
0: {messages: [{id: "Auth.form.error.invalid", message: "Identifier or password invalid."}]}
error: "Bad Request"
message: [{messages: [{id: "Auth.form.error.invalid", message: "Identifier or password invalid."}]}]
statusCode: 400
```

**Comment by gustavorps** [comment]
+1

**Comment by jscontreras** [comment]
I forgot to update this. It was my mistake. I was creating the user in the wrong strapi section.

**Comment by gustavorps** [comment]
Me to @jscontreras
I used the endpoint /auth/local/register and set the password in admin panel
