### ISSUE TITLE
GraphQL Mutation for passwordReset not available

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#5524]
**Describe the bug**
There are no GraphQL Mutations for `/auth/forgot-password` and `/auth/reset-password`.

**Steps to reproduce the behavior**
1. Install the GraphQL plugin
2. Open `http://localhost:3337/graphql`
3. Click on *Docs*
4. See that there is no mutation for those

**Expected behavior**
There should be a mutation to trigger a "forgot password" and to "reset password".

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/76857992-718c9d80-684e-11ea-8b08-bafaaf33e6a3.png)

**System**
- Node.js version: v13.7.0
- NPM version: 6.13.6
- Strapi version: `beta-19.3`
- Database: `mongodb`
- Operating system: `Windows`

**Comment by roelbeerens** [comment]
@diogotcorreia I just spun a small little repo with some solutions I use, maybe you can use that: https://github.com/roelbeerens/strapi-graphql-password-reset

**Comment by diogotcorreia** [comment]
@roelbeerens Thanks a lot, I'll definitely look into that!

It should still be implemented into `strapi-plugin-users-permissions` anyway.

**Comment by lauriejim** [comment]
Thank you for reporting this.
Can you please submit a PR to add this mutation.
I will appreciate your contribution.

**Comment by roelbeerens** [comment]
@lauriejim Thanks, i'll setup a PR for this.

**Comment by diogotcorreia** [comment]
Closing this since it has been merged
