### ISSUE TITLE
Middleware is not being triggered when calling upload plugin api endpoint

### ISSUE THREAD

**Issue by rmaroun** [strapi/strapi#5525]
**Describe the bug**

**Steps to reproduce the behavior**
1. Create a middleware which just has a console.log (as an example)
2. Call the upload plugin api endpoint
3. You won't see the middleware message in the strapi console

**Expected behavior**
When calling the upload api endpoint you should be able to see the console.log output of your middleware in the console (basically it means that the code of your middleware was executed before reaching the upload endpoint).

**System**
- Node.js version: v10.13
- Strapi version: 18.7

**Additional context**
Currently it works with any content type api endpoint (I can see the output of the middleware console.log) but when calling upload api endpoint nothing shows up. Haven't tested it for other plugins like user-permissions but could also be the case.

**Comment by derrickmehaffy** [comment]
I can confirm this with my sentry middleware on beta.19.3

**Comment by rmaroun** [comment]
@petersg83 can you reproduce it?

**Comment by lauriejim** [comment]
Hello! I just tried and it works well.
Here is what I did, can you tell me if I messed something.
https://www.loom.com/share/a5c6b06d29a64357ad5bceb5b85dedf9

**Comment by ralphsomeday** [comment]
@lauriejim can you try it with the S3 provider as I am not even getting any console message using the Admin UI, I was testing it using an api client. Tested it now with Admin UI and not getting any message.

**Comment by lauriejim** [comment]
The admin panel calls the rest endpoint `POST /upload` so there is no difference.
The origin of the request has no impact on the middleware stack.
Then about the provider, it's the same, it will not have any impact on the middleware stack.
The plugin endpoint is called and then instead of using the local provider function, it will call the AWS S3 one, so it will not impact your log.

**Comment by ralphsomeday** [comment]
@derrickmehaffy anything different that we may have done from the video of @lauriejim  with our middleware?

**Comment by ralphsomeday** [comment]
@lauriejim just recorded how to reproduce the bug using beta.19.4. Can you let me know if you can reproduce?
https://www.loom.com/share/80bf744c748c4a7db4fcb621a2fcf76a

**Comment by lauriejim** [comment]
Hello! I tried again and all works fine on my side, are you able to create a new project from scratch and reproduce the issue.
If you can record to let me see exactly what you did, that could help me.

**Comment by rmaroun** [comment]
Hi Jim, thanks for the remote assistance. The problem was due to the router middleware being loaded before my custom middleware which was causing the issue. Putting my custom middleware before the the router middleware works!
