### ISSUE TITLE
Does Strapi support "Model Tree Structures with Parent References" in MongoDB?

### ISSUE THREAD

**Issue by andriusmarkovic** [strapi/strapi#5537]
Hi, I have a problem with making relationship in MongoDB.
```
//Categories
{
  _id: 2000,
  name: 'Jacket',
  parentId: 1000
},
{
  _id: 1000,
  name: 'Clothes'
}
```
So a category can have many children and can have a parent.

But there is no ObjectId in db.
That is the problem I have.
I created relation field as parentid in AdminUI.
After that the AdminUI has stopped working. Maybe because of no ObjectID.

So is there any way to make relation field but not in ObjectId type?
or is there any way to see relationships in AdminUI depends on current db structure?

**Comment by victorkane** [comment]
I believe that when you are using MongoDB, you must respect how a document based database, which is by definition _not_ a relational database, handles relationships. This is described in the MongoDB Docs: https://docs.mongodb.com/manual/tutorial/model-referenced-one-to-many-relationships-between-documents/ 

So MongoDB based Strapi instances cannot implement something outside of those characteristics.

In your examples, @andriusmarkovic, you have no alternative but to use references, which, by definition, involve ObjectId references.

So this is a MongoDB question, not a Strapi question.

**Comment by victorkane** [comment]
Please also see Model Tree Structures with Parent References: https://docs.mongodb.com/manual/tutorial/model-tree-structures-with-parent-references/ This is very close to what you describe. However, the lookups _still use references (even if they don't look like UUID numbers).

The question to ask in this issue would be, then, does Strapi support "Model Tree Structures with Parent References" for example?

**Comment by andriusmarkovic** [comment]
@victorkane Thanks.
Yes, you are right. I updated the title.

**Comment by lauriejim** [comment]
Hello, please follow the issue template [here](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission lets us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
