### ISSUE TITLE
Registering a user twice via GraphQL gives misleading error

### ISSUE THREAD

**Issue by EricKit** [strapi/strapi#5549]
**Describe the bug**
When you register a user, then try to re-register a user with the same username the returned error is "Cannot return null for non-nullable field UsersPermissionsLoginPayload.jwt."

**Steps to reproduce the behavior**
1. Start a new project
2. Add a user with username "bob"
3. Add another user with username "bob"

**Expected behavior**
Proper GraphQL Error, not a null value to a non-nullable field. Preferably one like "Username is taken" not an "INTERNAL_SERVER_ERROR"

**Screenshots**
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/4143477/77130688-2ae99f80-6a16-11ea-92c6-2882786c36c8.png">

**Comment by roelbeerens** [comment]
This is related to https://github.com/strapi/strapi/issues/5558

**Comment by EricKit** [comment]
Sure is.
