### ISSUE TITLE
[3.0.0-alpha.9] User update error

### ISSUE THREAD

**Issue by tungtb** [strapi/strapi#555]
Node.js version: 8.9.4

npm version: 5.6.0

Strapi version: 3.0.0-alpha.9

Operating system: Ubuntu 16.04

Do you want to request a feature or report a bug?
Bug

What is the current behavior?
Update user

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Update user infomation
https://gyazo.com/f4fe843c27e5069c9ccc322d73f2f69e
**What is the expected behavior?**
User can update user information.

**Comment by lauriejim** [comment]
It's fix in this release https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.9.2
