### ISSUE TITLE
Loose component's data when you rename the component attribute name with MongoDB

### ISSUE THREAD

**Issue by Chris-Pollock** [strapi/strapi#5556]
**Bug description**
I have reproduced this on multiple different repeatable components and so am pretty sure this is a bug. I'm new to strapi I hope these aren't too frequent :(

If you simply use repeatable components, and change the fieldname that sets up the repeatable component, the api starts returning incorrect data that looks like this:

{
"_id": "5e68d688c0c615169ce924b2",
"kind": "ComponentLinkLink",
"ref": "5e68d60f43eeb628b07576b3"
},
as a reference of some sort, instead of the actual object. If you rename it back, suddenly the object appears properly again. 

{
"_id": "5e68d688c0c615169ce924b5",
"normal properties on that type go here": "etc",
}

**System**
- Node.js version: v12.13
- NPM version: 6.12
- Strapi version: 3.0.0-beta.19.3
- Database: Mongodb
- Operating system: Windows

**Comment by lauriejim** [comment]
Hello! Can you please provide steps to reproduce please, I'm not sure of what you are doing.

**Comment by Chris-Pollock** [comment]
I thought it was pretty clear but I will detail this more:

Steps - fresh strapi install as per steps above.
create collection type.
create a repeatable component.
add the repeatable component as a field to the collection type
add some data so that the json displays relationships.
go to the api via http://localhost:1337/yourtypehere
ensure the json data is as expected, returning data from the repeatable component
rename the field that is used for the repeatable component on the collection type.
check the api via http://localhost:1337/yourtypehere

json data now looks weird like this.

{
"_id": "5e68d688c0c615169ce924b2",
"kind": "ComponentNameHere",
"ref": "5e68d60f43eeb628b07576b3"
},

**Comment by Chris-Pollock** [comment]
Just as further information - this also happens if you just rename the category (or folder it displays in) of repeatable components. So use the component, add some values, rename the category and the api will break.

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
