### ISSUE TITLE
GraphQL login mutation doesn't throw detailed error message

### ISSUE THREAD

**Issue by roelbeerens** [strapi/strapi#5558]
**Describe the bug**
I noticed that the schema.graphql.js in the latest version of the User Permissions plugin is somewhat changed. The checkBadRequest function doesn't return an Apollo error anymore which results in a JWT error when the password and/or username is incorrect. 

**Steps to reproduce the behavior**
1. Go to config/schema.graphql.js
2. Go to line 8-14
3. Check the throw new Error 
4. This used to be a throw new ApolloError

**Expected behavior**
A clear error message when the username and/or password is incorrect when trying to log in.

**System**
- Node.js version: 13.10.1
- NPM version: 6.14.3
- Strapi version: 3.0.0-beta.19.3
- Database: MySQL / MariaDB
- Operating system: MacOS

**Comment by alexandrebodin** [comment]
Hi, Yes we add to remove the ApolloError to avoid making the ApolloServer a dependency of the users-permissions plugin. 

We won't be changing this right away as we need to handle error handling differently in our case (certainly passing and `errors` object to the graphql context with some errors like `ApolloError` and such + some Strapi specific errors). 

If you are interested in contributing let us know ;)

**Comment by roelbeerens** [comment]
Hi, thanks for the clear message. I do share your idea that your code should be as independent as possible. I'd love to help out. Is there already like something a error handler Strapi uses right now?

**Comment by roelbeerens** [comment]
@alexandrebodin would you guys prefer a error handler within the plug-in, or using a global one somewhere in the core?

**Comment by alexandrebodin** [comment]
Hi @roelbeerens we found out where the issue is coming from and it isn't only because of the ApolloError change. We are going to fix this on our side  as it requires more work than expected. 

Thank you for reporting this !
