### ISSUE TITLE
strapi-provider-email-amazon-ses returns error undefined when incorrect was credentials are used

### ISSUE THREAD

**Issue by Sejori** [strapi/strapi#5559]
**Describe the bug**
When using the ses provider errors are not returned with a status or description. Would be helpful to know why the email.send() function failed.

**Expected behavior**
Standard Strapi error object to be returned with status and messages e.g. "500 - AWS SES connection parameters incorrect"

**Code snippets**
[2020-03-20T15:43:56.332Z] error undefined

  AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
      at Function.boomify (/usr/app/node_modules/boom/lib/index.js:107:14)
      at /usr/app/node_modules/strapi/lib/middlewares/boom/index.js:80:22

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
To be honest, this provider is not really maintained.
So if you want it fixed, can you please submit a PR, I will appreciate your contribution.
Thank you.

**Comment by puuble** [comment]
> **Describe the bug**
> When using the ses provider errors are not returned with a status or description. Would be helpful to know why the email.send() function failed.
> 
> **Expected behavior**
> Standard Strapi error object to be returned with status and messages e.g. "500 - AWS SES connection parameters incorrect"
> 
> **Code snippets**
> [2020-03-20T15:43:56.332Z] error undefined
> 
> AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object
> at Function.boomify (/usr/app/node_modules/boom/lib/index.js:107:14)
> at /usr/app/node_modules/strapi/lib/middlewares/boom/index.js:80:22

Hi can you help me for AWS installation? how to make your settings? can you share?

**Comment by everyday-practice** [comment]
@puuble I also spent half a day trying to figure this out, but gave up and decided to use Sendgrid provider instead. Did you have any progress on integrating SES?

**Comment by anumber8** [comment]
@ghost i'm also on the same struggle been a week. Do you managed to succeed ?

**Comment by adamrhunter** [comment]
I've created a PR #8086 to correctly set the error message that is returned from SES if the sendEmail call fails.
