### ISSUE TITLE
Required fields in User Model are not created / ignored while register

### ISSUE THREAD

**Issue by Giom24** [strapi/strapi#5560]
**Describe the bug**
Required fields in User Model are not created / ignored while register

**Steps to reproduce the behavior**
1. Add some custom fields to the User Model
2. Mark them as required
3. Use the API to register an User. Besides the username, email and password the required fields
are set in the body as JSON.
4. The Server always response with "Auth.form.error.email.taken"

**Expected behavior**
The User should be created with the given fields

**System**
- Node.js version: v12.16.1
- NPM version: 
- Strapi version: 3.0.0-beta.19.3  
- Database: Mongo
- Operating system: Its your Docker image. I think is Ubuntu?

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this.
It's not really an issue.
The register function allows only some fields, username, password and email.
You will have to update the register controller function using the [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html)

If you add custom field in your User model, how you would like to define if you can add it or not via the registration function?

**Comment by victorray84** [comment]
Hi,
  I've customized the registration. It works. But, while try to upload image through registration, I'm getting image null.  But, other data saved to database.I've updated the Auth.js code and using multipart. I've attached my code here. Can u tell me what's the problem?

**System**

Node.js version:v12.14.0
NPM version: 6.13.4
Strapi version: 3.0.0-beta.18.6
Database: Mysql
Operating system: Mac OS X [10.15.3]
[strapi_custom_registration.zip](https://github.com/strapi/strapi/files/4371040/strapi_custom_registration.zip)

**Comment by lauriejim** [comment]
Hello! I just re-created it for you - https://www.loom.com/share/4a74317002924c25b0b64a8830916a65

**Comment by Giom24** [comment]
Thanks for you reply.

> If you add custom field in your User model, how you would like to define if you can add it or not via the registration function?

I thought it might be possible to edit the User.settings.json so that the controller is able to set the required fields automatically.

**Comment by victorray84** [comment]
Thanks for ur reply. I just made a mistake. You should upgrade the docs. As source field was not mentioned on the doc. While debugging, source was always undefined. Again thanks for ur help. I love Strapi. Thanks for ur support.

**Comment by derrickmehaffy** [comment]
@victorray84 can you point out where in the docs you saw the issue so I can make a PR to fix it?

**Comment by ramigs** [comment]
> Hello! I just re-created it for you - https://www.loom.com/share/4a74317002924c25b0b64a8830916a65

this was really helpful, thanks @lauriejim

**Comment by lauriejim** [comment]
Hello! As a conclusion of this issue.
Can you please open an [RFC](https://github.com/strapi/rfcs) for the technical proposal, this will help to understand how the form should work.
And the current way to achieve that is to follow my video for customization.
