### ISSUE TITLE
Error after saving an administrator profile

### ISSUE THREAD

**Issue by artlogic** [strapi/strapi#5564]
**Describe the bug**

After saving an administrator profile, I receive: "An error occurred during record fetch". The console shows this: `[2020-03-20T23:58:54.222Z] debug GET /content-manager/explorer/strapi::administrator/&_page=0&_limit=0&_sort=id (57 ms) 404`

**Steps to reproduce the behavior**
1. Install strapi using `npx create-strapi-app my-project --quickstart`
2. Create a new admin user
3. Once logged in, click on the user's name and then profile
4. Edit the password and hit save
5. Receive the error.

**Expected behavior**
It should not display the error/hang/404.

**System**
- Node.js version:  v12.16.1
- NPM version: 6.14.2
- Strapi version:  3.0.0-beta.19.3
- Database: sqlite (but that doesn't seem to matter - it also happens with mysql)
- Operating system: Debian (also happens in the strapi docker container)

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
Just to let you know, an error occurs in the frontend, but your update has been made.
