### ISSUE TITLE
Need to have CreatedBy and lastUpdatedBy field's by default in all models/CollectionTypes

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5565]
## Description:

Since we will be having many Users/Admins to our App.  It will be better, great if we can able to Audit Strapi.

In all models, We want to know User who created `Collection-Type` with default `createdBy` attribute  & We want to see User who made changes to existing articles with default `lastUpdatedBy` attribute.

Currently we are only having only 2 default attributes: `createdAt` and `updatedAt` 

**System info**

- Node.js version: `v10.15.3`
- NPM version: `6.4.1`
- Strapi version: `3.0.0-beta.18.4`
- Database: `Mongo`/ `Redis`
- Operating system: `MAC`

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Comment by derrickmehaffy** [comment]
@vinod77 please make a request on https://portal.productboard.com/strapi/tabs/2-under-consideration for the audit feature.

Marking as closed here.

**Comment by fallion** [comment]
@derrickmehaffy I can't seem to find it on there. I want to vote for this as we need to audit all changes in the app in another service.
