### ISSUE TITLE
Bad Request Error on Login

### ISSUE THREAD

**Issue by daxyonis** [strapi/strapi#5567]
**Describe the bug**
I create a new user in the UI with role Authenticated. I enable the Auth Permissions for Authenticated. Then I use Postman to call the API for login:

![test_login](https://user-images.githubusercontent.com/16484367/77227419-9b97d580-6b56-11ea-91d2-f98bcdab5b1b.PNG)

No matter what the user is I always get the same Bad Request error with message "Auth.form.error.email.provide" :  "Please provide your username or your e-mail."

- I have tried passing either the username or email but still have the same error.
- I thought to myself, maybe I need a working email sending so I have tried using strapi-provider-email-nodemailer and configured gmail to send email, without more success. Note that using nodemailer directly with same config works from my machine.

**Expected behavior**
I expected the login to work out of the box.

**Screenshots**
![test_create2](https://user-images.githubusercontent.com/16484367/77227555-81aac280-6b57-11ea-9450-fee58ebce5c2.PNG)

![test_login2](https://user-images.githubusercontent.com/16484367/77227558-853e4980-6b57-11ea-98d7-4bf80df6a575.PNG)

![image](https://user-images.githubusercontent.com/16484367/77227634-1b726f80-6b58-11ea-9f11-769fbc336a7b.png)

**System**
- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database: sqlite3 latest
- Operating system: Windows 10

**Comment by alexandrebodin** [comment]
Hi @daxyonis 

You are not sendiing the request as `json` :)

Make sur to send the `content-type: application/json` header. With postman you need to select json in the dropdown menu on the right :)

Enjoy !
