### ISSUE TITLE
Error when searching a content type with no searchable fields or UID

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#5577]
**Describe the bug**
When searching a content type that has no searchable fields, there is an error thrown on console.
Additionally, you can't search by UID.
This is only happening with Mongoose.

**Steps to reproduce the behavior**
1. Create a Content Type with a UID and an Integer.
2. Add one or two entries.
3. Try to search by UID.

**Expected behavior**
It should only return the entries that match the search.

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/77325510-60d99d00-6d10-11ea-92c2-13dc09f06715.png)

**System**
- Node.js version: v13.7.0
- NPM version: 6.13.6
- Strapi version: beta-19.3
- Database: Mongoose
- Operating system: Windows 10 1909

**Additional context**
I'll be submitting a PR to fix this.

**Comment by derrickmehaffy** [comment]
`I'll be submitting a PR to fix this.` :+1:
