### ISSUE TITLE
"_ in" on endpoint query to match any value in array doesn't work properly

### ISSUE THREAD

**Issue by fparol4** [strapi/strapi#5582]
Hello, sorry my bad english. Thats my first issue. 

I am trying to use the "in" query operator that corresponds to a value in the array, but passing an array does not work, but passing only one value correspond correctly, wtf?

**Working** 
![image](https://user-images.githubusercontent.com/47286899/77355399-20cfe580-6d23-11ea-8bb7-bfb27af67ff0.png)

**!Working**
![image](https://user-images.githubusercontent.com/47286899/77355518-55dc3800-6d23-11ea-8e08-aeab6635b323.png)

btw, i tryied so many different ways to make this request, tryied to understand the default .search context and how the filters are passed to him but i cant. 

Im sorry if its a stupidy question, thannkxs
If that is in the wrong place, please, correct me

**Comment by alexandrebodin** [comment]
Hi @fparol4, you can query like follows:

- `GET http:/localhost?Title_in[]=Programming&Title_in[]=OtherValue`

I'm going to close this :)
