### ISSUE TITLE
Allow Cyrillic in Enumeration textarea (The value not match the regex.) 

### ISSUE THREAD

**Issue by NickCashFlow** [strapi/strapi#5587]
**Describe the bug**
Hi!
When I type several lines in Russian into the value field in the Enumeration Type Content, I get an error "The value not match the regex". But if I adding strings in Latin, then everything works as expected.

**Steps to reproduce the behavior**
1. Click the "+ Create new content-type" link
2. Enter `restaurant`, and click Done
3. A window opens with fields options:
4. Click the **Enumeration** field
5. Type `markers` in the Name field
6. Type several lines in Cyrillic under the BASE SETTINGS tab, in the Values (one line per value) field
7. Click Finish and you'll get an error "The value not match the regex."

**Expected behavior**
When I click Finish then Enumeration field saved changes

**Screenshots**
https://prnt.sc/rm01i8

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.19.3
- Database: sqlite3@latest
- Operating system: Windows 7 Ultimate x64

**Comment by derrickmehaffy** [comment]
enumeration values have a strict regex for GraphQL support see this issue: https://github.com/strapi/strapi/issues/4780

Closing as duplicate

**Comment by chumaty** [comment]
@NickCashFlow Вам удалось решить эту проблему?

**Comment by derrickmehaffy** [comment]
Hello!

To be inclusive of everyone in the community and to provide the best possible answer that everyone can refer to, we require that everyone uses English on all of our respective platforms. 

Thank you and have a wonderful day!
