### ISSUE TITLE
Upload files related to an User model entry

### ISSUE THREAD

**Issue by deivijt** [strapi/strapi#5588]
**Describe the bug**
When I upload a file to / upload and want to associate it with a field of the User model, it throws the following error:
`[2020-03-24T15:50:29.167Z] error TypeError: Cannot read property 'associations' of undefined
    at /Users/.../strapi-upload/node_modules/strapi-connector-bookshelf/lib/relations.js:273:48
    at Array.forEach (<anonymous>)
    at /Users/.../strapi-upload/node_modules/strapi-connector-bookshelf/lib/relations.js:265:42
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/Users/.../strapi-upload/node_modules/strapi-connector-bookshelf/lib/relations.js:100:59)`

**Steps to reproduce the behavior**
1. Add a field called image to the user model
2. Send request to / upload with the fields files, refId, ref, field (see screenshot below)
3. See error

**Expected behavior**
Upload the image and associate it to the user model field.

**Screenshots**
not working
![error](https://i.imgur.com/fiit5BE.png)

works
![success](https://i.imgur.com/pxOT6C8.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database:  MySQL. v5.7.28
- Operating system:   MacOS

**Additional context**
will the property ref = user be correct? 🤔

**Comment by derrickmehaffy** [comment]
Per: https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters

- files: The file(s) to upload. The value(s) can be a Buffer or Stream.
- path (optional): The folder where the file(s) will be uploaded to (only supported on strapi-provider-upload-aws-s3).
- refId: The ID of the entry which the file(s) will be linked to.
- ref: The name of the model which the file(s) will be linked to (see more below).
- source (optional): The name of the plugin where the model is located.
- field: The field of the entry which the file(s) will be precisely linked to

you are missing `source (optional): The name of the plugin where the model is located.`

Marking as closed but do feel free to respond if you still have issues.

**Comment by saadik1232** [comment]
> Per: https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters
> 
> * files: The file(s) to upload. The value(s) can be a Buffer or Stream.
> * path (optional): The folder where the file(s) will be uploaded to (only supported on strapi-provider-upload-aws-s3).
> * refId: The ID of the entry which the file(s) will be linked to.
> * ref: The name of the model which the file(s) will be linked to (see more below).
> * source (optional): The name of the plugin where the model is located.
> * field: The field of the entry which the file(s) will be precisely linked to
> 
> you are missing `source (optional): The name of the plugin where the model is located.`
> 
> This should be `users-permissions`
> 
> Marking as closed but do feel free to respond if you still have issues.

awesome solution brother
