### ISSUE TITLE
Something went wrong when saving component in Dynamic Zone with Strapi

### ISSUE THREAD

**Issue by qsedmi** [strapi/strapi#5591]
**Describe the bug**
When I save the custom Collection Type and I added Components to its Dynamic Zone field, everything is saved but the _Content-Types Builder_ is no more accessible and displays an error message instead  `ReferenceError: can't access lexical declaration 'allComponents'`. 

Same thing when I click on _Create a new Component_ in the _Add new component to the dynamic zone_ pop up with the error `ReferenceError: can't access lexical declaration 'originalIcon' before initialization`.

**Steps to reproduce the behavior**
1. Go to _Content-Types Builder_ in the sidebar of the Admin interface
2. Add new Dynamic zone field and add existing components
3. Click on Finish and Save the Collection Type
4. See error `ReferenceError: can't access lexical declaration 'allComponents' before initialization` with `Something went wrong.` title

**Expected behavior**
The Collection Type should be saved and displayed with a Dynamic Zone field and Components inside of it.

**Screenshots**

![Content-Types Builder interface just before I save the Collection Type](https://user-images.githubusercontent.com/25525202/77476738-6c65ba80-6e1b-11ea-978e-e29bddb54211.png)

![Error in Content-Types Builder interface](https://user-images.githubusercontent.com/25525202/77476743-712a6e80-6e1b-11ea-8fbe-dc36e65e8dbd.png)

**Console Error**

![Firefox Console Error](https://user-images.githubusercontent.com/25525202/77518852-c51a6f00-6e7e-11ea-8fcd-3ed85999de9f.png)

**System**
- Node.js version: v10.15.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.19.3
- Database: 
- Operating system: Windows 10 64-bit

**Additional context**
I tried it by installing Strapi through Commande line and by modifying an existing project. Error persists.

Thanks for your help,
Quentin

**Comment by qsedmi** [comment]
Another message which I think is related is when I try to add a new component to a Dynamic Zone :

`can't access lexical declaration 'originalIcon' before initialization`

![Screenshot_2020-03-24 Strapi - Content Type Builder(2)](https://user-images.githubusercontent.com/25525202/77480637-5c9da480-6e22-11ea-858d-fd49b89a1b8c.png)

Same problem with the variable originalIcon initialized after being accessed. 

![Screenshot_2020-03-24 Strapi - Content Type Builder(3)](https://user-images.githubusercontent.com/25525202/77480636-5c9da480-6e22-11ea-996f-23dbfb4263fc.png)

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment]
Hello @qsedmi !

Can you please precise exact steps to reproduce your issue, because it's not clear for me.

`Add new Dynamic zone field and add existing components` but you are showing a screenshot from a Content Type and not a Component.

**Comment by qsedmi** [comment]
Hello @lauriejim !

I created a new Collection Type I called _Article_. It has a field called Content which is a Dynamic Zone field. I added to it Components I previously created.

When I save my _Article_ Collection, I get the first message `ReferenceError: can't access lexical declaration 'allComponents' before initialization` with `Something went wrong.` and I cannot access the Content Type Builder interface.

When I deleted the components manually in the _article.settings.json_ file:

From
```
"Content": {
      "type": "dynamiczone",
      "components": [
        "content.image",
        "content.link",
        "content.paragraph",
        "content.quote"
      ]
    }
```
To
```
"Content": {
      "type": "dynamiczone",
      "components": [

      ]
 }
```
I can reload the Content Type Builder interface, but if I retry to add Components to the Dynamic Zone the same error occurs. 

Another point is I'm not allowed to create new Component from the _Add a component_ button neither:

**Steps to reproduce the behavior**

1. Reload Article (which is a custom Collection Type)
2. Click on _Add a component_ button of the Dynamic zone field
3. Click on _Create a new component_ (See screenshot)
4. See error `ReferenceError: can't access lexical declaration originalIcon' before initialization`


![Error when I clicked on Create a new component](https://user-images.githubusercontent.com/25525202/77548147-6cfb6100-6eae-11ea-978e-4d758ce0afbb.png)

Error I get:

![Error in Content-Types Builder interface](https://user-images.githubusercontent.com/25525202/77549584-50602880-6eb0-11ea-88bf-62444ce07756.png)

Thanks,
Quentin

**Comment by soupette** [comment]
@qsedmi I tried to reproduce your bug but I am not able can you share your repo?

**Comment by qsedmi** [comment]
Hi @soupette !

Here is my repo: https://github.com/qsedmi/Strapi-Quentin-Sedmi.git

Thank you,
Quentin

**Comment by soupette** [comment]
@qsedmi I have cloned your repository and everything works fine. I am able to create new components and add the existing ones to your `Content` dynamic zone.

**Comment by qsedmi** [comment]
Hello @soupette 
I think I have a problem with one of the dependencies:

Here is the result of `npm audit`:

![1 high severity vulnerability](https://user-images.githubusercontent.com/25525202/78054048-c4537280-7381-11ea-891c-755bb11ad571.png)

**Comment by qsedmi** [comment]
I solved the problem by installing Strapi outside of my React App folder.

Sorry that I disturbed you and thank you for your quick answers,
Quentin

**Comment by soupette** [comment]
I think that was the probleme having strapi inside your client folder. I am closing this issue then.
