### ISSUE TITLE
Strapi warning of performance issue with graphql filtering

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#5593]
**Describe the bug**
I have this very simple graphql query (see below).  Basically, there is a many-to-one relationship between "stocks" and "product"

I want to filter out all "stocks" not linked to a "product"

```
query {
  stocks (where: {product: {id_null:false}}) {
    id
    name
    sku
    quantity
    product {
      id
      name
      slug
    }
  }
}
```
And on the console, Strapi is warning me of this filter

> [2020-03-25T11:43:19.384Z] warn Deep filtering queries should be used carefully (e.g Can cause performance issues).
When possible build custom routes which will in most case be more optimized.

Should we take this warning serious. If so, what is a better option to make this kind of filtering

**System**
- Node.js version: v10.15.3
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.19.3
- Database: v11.3
- Operating system: Ubuntu 1404 (via vagrant vbox)

**Comment by derrickmehaffy** [comment]
can you try with just a `(where: {product_null: false})`

**Comment by derrickmehaffy** [comment]
The warning about deep filtering is sent any time deep filtering is used in general (rest and graphql since it uses the same code)

**Comment by laportem** [comment]
```
(where: {product_null: false})
```
does the job as well and the warning message is no longer coming up. But if i need to do deep filtering, is there really a performance impact or just a warning for us to be careful

**Comment by lauriejim** [comment]
It could be slower yes. Depending on your filter, data structure you have and quantity of data you have. The log is added by default if you are filtering on relations.
