### ISSUE TITLE
Not able to access dotenv variables in the Strapi Admin front-end for different env's 

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5599]
**Describe the topic**
How can i access `dotenv` variables for `UAT` & `PROD`environments  in Strapi Admin front-end ? (I have overridden some front-end Admin code)
Currently in the Admin front-end I am always getting it as `process.env.NODE_ENV`: `production` in all env’s. But it should be different for each environment: `DEV`,  `UAT`,  & `PROD`

**Expected Behavior**
Should be able to access dotenv variables in all different environments & `process.env.NODE_ENV` should return respective `dotenv` variable

On DEV:  `process.env.NODE_ENV`: `dev`
On UAT:  `process.env.NODE_ENV`: `uat`
On PROD:  `process.env.NODE_ENV`: `production`
 
**Your suggestions for this topic**
Need to get access to `dotenv` variables for all respective environments (DEV, UAT, PROD).

- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**System**
- Strapi version: `3.0.0-beta.19.3`
- Node.js version: `v10.15.3`
- NPM version: `6.4.1`
- Database: `Mongo`
- Operating system: `MAC`

**Comment by alexandrebodin** [comment]
Hi That's not how client side works :) The env variables are created at build time in the js bundle not at runtime.

**Comment by vinod77** [comment]
I know env variables are created at build time. But i want to get different env variables for each environment.

On DEV: process.env.NODE_ENV: dev
On UAT: process.env.NODE_ENV: uat
On PROD: process.env.NODE_ENV: production

**At Build Time**

But currently on all the environments i am getting `process.env.NODE_ENV` as  `production`. I want to get it according to each environment as said above.

**Comment by alexandrebodin** [comment]
This is not something we will be able to do. THe NODE_ENV=production is required to build the admin panel correctly. It doesn't recognize other env variables.

**Comment by vinod77** [comment]
@alexandrebodin Could you please let me know if there is any other way/workaround for this? 
Right now i have manually added our UAT `dotenv` variable in this file: `strapi-admin/admin/src/config.js`: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/config.js  as we are only on UAT now. 
But I need to add PROD `dotenv` variable before we go to PROD, not knowing how i can do that.
