### ISSUE TITLE
manual sorting of relations in GUI not working

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#5603]
**Describe the bug**
The Admin GUI offers a possibility to sort the selections for a related type field. But after saving the item, the sorting is not done. The entries of the realtion type field are still sorted as the were added.

**Steps to reproduce the behavior**
1. Make 2 Collection
2. Make a field the relates to the other collection
3. Add some relations and individually sort them
4. Save the item and reopen it or get it by api - The sorting is not corresponding the individual sorting, but the initial adding order

**Expected behavior**
Resorting the selection

**Screenshots**
![strapi-relation-sorting](https://user-images.githubusercontent.com/8960545/77570206-ab534900-6ecb-11ea-99a6-699966b94c98.png)

**System**
- Node.js version: 10.16.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.19.3 
- Database: sqlite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Hello, this feature is not currently available for normal relations yet please see the following FAQ: https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#relations-aren-t-maintaining-their-sort-order
