### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by mittalyashu** [strapi/strapi#561]
**Node.js version**: 6.11.5

**npm version**: 3.10.10

**Strapi version**: 3.0.0-alpha.9.1

**Operating system**: Windows 10

**Do you want to request a *feature* or report a *bug*?** Report a bug

**What is the current behavior?** Error => Cannot read property 'start' of undefined

**If the current behavior is a bug, please provide the steps to reproduce the problem**
https://www.useloom.com/share/ff06f7681ecf496da31dbc9d9fe0999d

**What is the expected behavior?**
It should start running.

**Comment by lauriejim** [comment]
Hi @mittalyashu, you have to update your node version to node 9 and npm 4.

**Comment by mittalyashu** [comment]
After updating got this error.
![image](https://user-images.githubusercontent.com/29014463/35743991-2ad71b68-0865-11e8-85f9-0c04f7c89b4d.png)

**Comment by lauriejim** [comment]
You change your node version and install strapi again and generate a new project ?

**Comment by mittalyashu** [comment]
Got it.

**Comment by mittalyashu** [comment]
Still not working, getting the same error.
![image](https://user-images.githubusercontent.com/29014463/35763596-aec0e088-08d5-11e8-821f-f84b84b62adb.png)

**Comment by mittalyashu** [comment]
When I tried to change the database to MySQL, then I got this error.

![image](https://user-images.githubusercontent.com/29014463/35826320-6bf4d448-0ade-11e8-8817-efe2515280c1.png)

**Comment by Aurelsicoko** [comment]
Set the `/config/hook.json` timeout value to 5000...

**Comment by mittalyashu** [comment]
Still not working.

![image](https://user-images.githubusercontent.com/29014463/35987314-5ca61408-0d21-11e8-84b2-cf68ebb38ad6.png)

**Comment by Aurelsicoko** [comment]
It seems that your SQL database is not running. Make sure you provide the right connection information to connect Strapi to it. I can't reproduce your issue. The error is happening in the `./plugins/users-permissions/config/functions/bootstrap.js` because there are many requests done in this file and they can't be executed because the connection to the database doesn't exist.

**Comment by mittalyashu** [comment]
Do we need to run SQL database separately?

**Comment by Aurelsicoko** [comment]
@mittalyashu Sure, Strapi only provides a Node.js HTTP server with a dashboard to manage the data. We don't launch a MongoDB ou SQL database automatically. That's why, when you run `strapi new myApp` we ask about your database details to connect Strapi to it.

**Comment by mittalyashu** [comment]
Well, I haven't run any database separately. Can you tell me how to run a MySQL database?

**Comment by derrickmehaffy** [comment]
@mittalyashu this is old though should help with beginners (would highly recommend looking up tutorials that match the current version): https://www.digitalocean.com/community/tutorials/a-basic-mysql-tutorial

**Comment by lamarena** [comment]
Can anyone can help me with this? I can not start strapi
![screenshot_1](https://user-images.githubusercontent.com/23172332/36851483-9915f5f4-1d69-11e8-810a-b97bbd5d40dd.jpg)
