### ISSUE TITLE
Push rejected on Heroku using npm

### ISSUE THREAD

**Issue by TakCastel** [strapi/strapi#5611]
**Describe the bug**
When we want to push some modification to the API (happened when I created a new Content-Type in development), the command `git push heroku master` throws an error : 

```
error: failed to push some refs to 'https://git.heroku.com/my-api.git'
```

**Steps to reproduce the behavior**
1. Use Heroku for deployment following the 
2. Add a new Content-Type in development
3. Push the modifications following the documentation : https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku
4. Error code : 

```
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to my-api.
remote:
To https://git.heroku.com/my-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/my-api.git'
```

I added the `package-lock.json` in my `.gitignore` 

**Expected behavior**
I did it once before and everything worked fine. Then suddenly it didn't want to take anymore modification.

**System**
- Node.js version: 10.16.2,
- NPM version: 6.14.3
- Strapi version: 3.0.0-beta.19.3
- Database: mongodb
- Operating system: macos

**Additional context**
When I switched to yarn, it all worked perfectly fine.

**Comment by derrickmehaffy** [comment]
This is not an issue with Strapi directly but a problem with Heroku and NPM.

Marking as closed for now, do feel free to keep up the discussion though :)
