### ISSUE TITLE
Uploading images results in Server Error in Production

### ISSUE THREAD

**Issue by carillem** [strapi/strapi#5616]
**Describe the bug**
When I upload more than 1 image to a collection type, it results in a server error in production but it works perfectly in development.

**Steps to reproduce the behavior**

**Expected behavior**
Upload the image successfully. 

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version:  v12.16.1
- NPM version:6.13.4
- Strapi version: 3.0.0-beta.19
- Database: postgresql
- Operating system: macos

**Additional context**
DB is postgresql. and image sizes are `436KB` and `60KB` respectively.

**Comment by derrickmehaffy** [comment]
We need more information, can you please completely fill out the required template for reproduction steps

**Comment by derrickmehaffy** [comment]
Closing as user has not provided any reproduction steps, can be reopened when updated.
