### ISSUE TITLE
WYSIWYG Editor Performance is very slow with huge files/content

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5619]
**Describe the bug**
WYSIWYG Editor Performance is very slow for huge files/content of size more than 1.2MB and taking around 4-5 min to load and causing Browser crash.

I am using WYSIWYG editor for our API docs which is in `md` file, has around 20,000 lines of content

**Steps to reproduce the behavior**
1. Create a WYSIWYG field
2. Add or copy/paste `md` content of around 20,000 lines to WYSIWYG field
3. Save the article
4. Now try to open it the same article

**Observed Behavior**
It's taking around 5 minutes to load & causing very slowness & sometime causing Browser to crash

**Expected behavior**
Faster loading though we use huge files/content

**NOTE:** Earlier we used Strapi `Alpha` version & it was much faster compared to the recent Beta version

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.19.3
- Database: Mongo
- Operating system: MAC

**Comment by lauriejim** [comment]
Thank you for reporting this issue!
Here is a guide - how to customize the admin - https://strapi.io/documentation/3.0.0-beta.x/guides/custom-admin.html#update-the-content-manager
And here an example to update the WYSIWYG - https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html#customize-a-plugin
By updating the compo this can be more performant maybe.

**Comment by soupette** [comment]
Hi @vinod77 I have tried several editors
- [draft-js](https://draftjs.org/)
- [CKEditor](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/balloon-editor.html)

And they both suffer performance issue with huge md content I have tested both with this [content](https://raw.githubusercontent.com/JJ/top-github-users-data/master/formatted/top-Espa%C3%B1a.md) and honestly they both take quite some time to load the content. I am not sure what we can do about it.

**Comment by derrickmehaffy** [comment]
unlikely something we can fix and no one else has provided additional information on this, closing
