### ISSUE TITLE
Unable to launch Admin Panel when using --watch-admin option

### ISSUE THREAD

**Issue by AnthonyPhan** [strapi/strapi#5639]
**Describe the bug**
When launching Strapi with the --watch-admin option enabled the administration panel is not accessible. 

**Steps to reproduce the behavior**
1. Create a new strap project using `strapi new myproject --quickstart`
2. Navigate to the newly created project directory `cd myproject`
3. launch strap with the watch-admin option `strap develop --watch-admin`
4. Navigate to the admin panel at http://localhost:1337/admin/ 
5. Take notice of the errors in your terminal and the error you will receive in the web browser

**Expected behavior**
The expected behaviour would be to see the administration panel appear and any changes I make to files within the admin folder in my root directly to automatically be previewed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12785492/77867263-1d7bb300-7269-11ea-9967-0f048ec70b00.png)

![image](https://user-images.githubusercontent.com/12785492/77867250-118ff100-7269-11ea-80b3-775ad8c83614.png)

**System**
- Node.js version: 12.6.0
- NPM version: 6.9.0
- Strapi version: 1.0.0-beta.19.3
- Database: SQLLite and Postgres
- Operating system: Windows

**Additional context**
If i add files to the admin folder in the root directly and rerun build, changes to admin panel are reflected. I just cannot develop the admin front end with autoReload. 
I also tried going to download the entire admin folder form github and manually put them into the admin root director of my project, but this causes build to fail.

**Comment by christianguevara** [comment]
That looks like port 8000 is in use in your system, try looking for any app running in the background using port 8000

**Comment by AnthonyPhan** [comment]
I have checked and there is nothing running in the background on port 8000. I'm unsure where strapi is even getting reference to port 8000? 
When i run "strapi develop" it runs on port 1337, would this change when running with the --watch-admin option?

**Comment by AnthonyPhan** [comment]
I'm unsure what the issue was but restarting my desktop has resolved it!
