### ISSUE TITLE
Limit not respected when querying multiple media type with GraphQL

### ISSUE THREAD

**Issue by LorbusChris** [strapi/strapi#5640]
**Describe the bug**
I've created a single type `Frontpage` that contains a multiple media type `pictures`. Limiting the query results for returned `pictures` does not seem to work.

**Steps to reproduce the behavior**
1. Create a single type with multiple media type field `pictures` (with graphql plugin installed)
2. Upload 3 items to `pictures` via admin UI 
3. Try to limit the number of returned items from multiple media type field with `limit` parameter in graphql query.
4. See that always all items from `pictures` are returned.

**Expected behavior**
I expect the number of items returned to be limited to the given number.

**Code snippets**
from auto-generated schema.graphql:
```
type Frontpage {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  pictures(sort: String, limit: Int, start: Int, where: JSON): [UploadFile]
}
```
```
"""The `Upload` scalar type represents a file upload."""
scalar Upload

type UploadFile {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  name: String!
  hash: String!
  sha256: String
  ext: String
  mime: String!
  size: Float!
  url: String!
  provider: String!
  provider_metadata: JSON
  related(sort: String, limit: Int, start: Int, where: JSON): [Morph]
}
```
these two queries yield the same result (there are a total of 3 items in `pictures`)
```
query {
  frontpage {
    pictures (limit: 1){
      url
    }
  }
}

query {
  frontpage {
    pictures {
      url
    }
  }
}
```
yields
```
{
  "data": {
    "frontpage": {
      "pictures": [
        {
          "url": "/uploads/f8c46ebe6e84405e8cae5fb5b91e5c3b.png"
        },
        {
          "url": "/uploads/1c4076ecbbfe4b20a76fce410fa754f9.png"
        },
        {
          "url": "/uploads/e02d507892b247c8a54948bf14d45564.png"
        }
      ]
    }
  }
}
```

**System**
- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: v3.0.0-beta.19.3
- Database: sqlite
- Operating system: Fedora 31 Linux

**Additional context**
development mode, using  strapi-docker

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
I'm notifying the team about this issue.

**Comment by arabscimitar** [comment]
also filter, start and sort is not respected and that for any Moraph relation type

**Comment by abdonrd** [comment]
I have the same issue:

<img width="752" alt="Screenshot 2020-09-15 at 12 27 11" src="https://user-images.githubusercontent.com/1007051/93199538-cf8f3480-f74e-11ea-85ea-a0fd3bd421ff.png">

**Comment by xaun** [comment]
Any update on this?

**Comment by gnibblz** [comment]
I am able to specify a limit < 100 without issue, but anything > 100 is not respected and assumes 100.

**Comment by kliakos** [comment]
> I am able to specify a limit < 100 without issue, but anything > 100 is not respected and assumes 100.

Follow this issue https://github.com/strapi/strapi/issues/9959

**Comment by Basti271** [comment]
hey, any news on this? I get all images using for example this gql:

```
query AlbumsInCategory($Category: String!, $Count: Int!) {
    categories(where: { title: $Category }) {
      title
      albums(limit: $Count, sort: "published_at:desc") {
        title
        description
        published_at
        slug
        photographer {
          name
          website
          email
          vita
          avatar {
            url
          }
        }
        images(limit: 1) {
          name
          alternativeText
          caption
          url
        }
      }
    }
  }

```

**Comment by derrickmehaffy** [comment]
should be fixed in v4

**Comment by derrickmehaffy** [comment]
it's `pagination: { limit: -1 }`

https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/graphql-api.html#pagination-by-offset
