### ISSUE TITLE
Users /me endpoint doesn't return media

### ISSUE THREAD

**Issue by FutsalShuffle** [strapi/strapi#5641]
**Describe the bug**
The `/users/me` endpoint doesn't return the media type field that i added. When i GET on let's say `/users/1` it returns as it should.

**Steps to reproduce the behavior**
1. Go to Users fields edit
2. Create a new media field
3. GET /`users/me`
4. See everything but this field

**Expected behavior**
Being able to see this field

**Code snippets**
Haven't changed any code, fails to work on both production and development builds

**System**
- Node.js version: 10.16.3 / 13.12.0
- NPM version:  6.9.0
- Strapi version: 3.0.0-beta.19.3
- Database: postgre
- Operating system: Windows 10 / Linux

**Additional context**
Is there's some trick to make it work?

**Comment by alexandrebodin** [comment]
Hi, This is the intended behaviour :) The /me route returns only a subset of informations to ensure no data leaks. You can customize this on your own if you require it to return more info :)

Have a good day :)

**Comment by FutsalShuffle** [comment]
> Hi, This is the intended behaviour :) The /me route returns only a subset of informations to ensure no data leaks. You can customize this on your own if you require it to return more info :)
> 
> Have a good day :)
Could you please provide a bit more info on where to dig to make it return media field? I want to make it return user's profile picture and it would make more sense to get it there than getting ID from /me and then fetching /users/:id.

**Comment by alexandrebodin** [comment]
Sure, You can look at this short doc on where tu put your files. https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html#customization

The idea is that you will have to overwritte the /me controller action by copying it in a customizing the file in the extensions folder
. Your code could look like :

`extensions/users-permissions/controllers/User.js`
```js
const { sanitizeEntity } = require('strapi-utils');

const sanitizeUser = user =>
  sanitizeEntity(user, {
    model: strapi.query('user', 'users-permissions').model,
  });

module.exports = {
  async me(ctx) {
    const user = ctx.state.user;

    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
    }

    const userQuery = await strapi.query('user', 'users-permissions');
    const userWithMedia = userQuery.findOne({ id: ctx.state.user.id }, ['mediaField']);

    const data = sanitizeUser(userWithMedia, { model: userQuery.model });
    ctx.send(data);
  },
};

```

**Comment by FutsalShuffle** [comment]
Beautiful, tweaked the code a little bit and now its working! Thanks a lot!

```
async me(ctx) {
    const user = ctx.state.user;

    if (!user) {
      return ctx.badRequest(null, [
        { messages: [{ id: 'No authorization header was found' }] },
      ]);
    }
   
	const userQuery = await strapi.query('user', 'users-permissions');
    const userWithMedia = await userQuery.findOne({ id: ctx.state.user.id });
    const data = sanitizeUser(userWithMedia, { model: userQuery.model });
    ctx.send(data);
```

For w/e reason it wasn't working with `['mediaField']` 
Also a question - why doesn't Strapi verifies user's ID on update by default? Its just a 3 lines of code and without it anyone can change, let's say a username of any User...

**Comment by alexandrebodin** [comment]
This is checked by our permissions system not by which user it is ;) You need to all users to have the right to update a user. This isn't a route made for a user to update its own infos :)

**Comment by FutsalShuffle** [comment]
So updating and user's profile information in here would be a wrong way to do it? Or is it just supposed to be like that so the devs can tweak it?

**Comment by alexandrebodin** [comment]
Not sure to know what you want to achieve :) I would recommend you go onto slack to discuss the way you want to approach your own business logic ;)

**Comment by FutsalShuffle** [comment]
Its gonna be a default User profile, where he can enter his data like his first and last names. Obviously it would need a way for users to be able to change it, so that's why i'm wondering what's wrong with storing and updating it in a default Users route

**Comment by alexandrebodin** [comment]
I would recommend you create a custom route to avoid messing with the existing code :)

**Comment by FutsalShuffle** [comment]
Ok i will check it all out. Thanks for your time and work!

**Comment by loongmxbt** [comment]
Works for me!
Step1: create `extensions/users-permissions/controllers/User.js`
Step2: Add the following
```
// users/me with media and relational fields
const { sanitizeEntity } = require('strapi-utils');

const sanitizeUser = user =>
  sanitizeEntity(user, {
    model: strapi.query('user', 'users-permissions').model,
  });

module.exports = {
  async me(ctx) {
    const user = ctx.state.user;

    if (!user) {
      return ctx.badRequest(null, [{ messages: [{ id: 'No authorization header was found' }] }]);
    }

    const userQuery = await strapi.query('user', 'users-permissions');
    const userWithMedia = await userQuery.findOne({ id: ctx.state.user.id });

    const data = sanitizeUser(userWithMedia, { model: userQuery.model });
    ctx.send(data);
  },
};
```
Then /users/me will return all custom fields
