### ISSUE TITLE
The model 'collection name' can't be found

### ISSUE THREAD

**Issue by JamesKrub** [strapi/strapi#5643]
I'm trying to get data from a collection inside the **extensions/user-permission** that I overrode 
by using 

`const test = await strapi.query('backoffice_roles').findOne({ name: 'restaurant name' });`

and I got an error  ``error Error: The model backoffice_roles can't be found.`` 

How can I solve this?

**Comment by alexandrebodin** [comment]
Hi @JamesKrub 
To access a content type queries you need to use it's name not it's collection name :) 
Your model is probably  called  `backoffice-role` :)
