### ISSUE TITLE
VK provider crashes the server

### ISSUE THREAD

**Issue by FutsalShuffle** [strapi/strapi#5647]
**Describe the bug**
Strapi server crashes on `GET` `/connect/vk`. After it asks for app's permission on collecting your data, it redirects you to your endpoint and server crashes.

**Steps to reproduce the behavior**
1. Turn on VK provider
2. Fill all the fields
3. GET /connect/vk

**Expected behavior**
It should return JWT token with all the other information

**Code snippets**
Nothing was changed in original code

**System**
Node.js version: 10.16.3 / 13.12.0
NPM version: 6.9.0
Strapi version: 3.0.0-beta.19.3
Database: postgre
Operating system: Windows 10 / Linux

**Additional context**
Google provider for example works as intended. VK doesn't work both in production and development mode and on both Linux and Windows.

**Comment by MattieBelt** [comment]
@sulakin are you still using it with the latest version? 
Any advise/fix for @FutsalShuffle?

**Comment by sulakin** [comment]
> @sulakin are you still using it with the latest version?
> Any advise/fix for @FutsalShuffle?

Checked, works on version 3.0.0-beta.19.3
@FutsalShuffle can you attach screenshots **strapi edit provider vk** and **vk settings app**?
