### ISSUE TITLE
Not able to create a newProject with v3@alpha.9

### ISSUE THREAD

**Issue by Yobikap** [strapi/strapi#565]
**Node.js version**: 8.1.0

**npm version**: 5.6.0

**Strapi version**: v3@alpha.9

**Operating system**:
Distributor ID:	elementary
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki 

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When typing
$ strapi new myNewProject
The prompt hangs on *Database name: (strapi)*

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Update strapi v3@alpha.8 to strapi v3@alpha.9 with npm i strapi@alpha

Create a new project using:
$ strapi new myNewProject
Choose MongoDB

Now it hangs and I am not able to type anything in terminal.

**What is the expected behavior?**
That it creates a project and does not hang in Terminal

**Comment by Aurelsicoko** [comment]
@Yobikap What terminal are you using? It seems more related to the library that we are using to display the prompts.

**Comment by Yobikap** [comment]
@Aurelsicoko  I am using io.elementary.terminal or in the past the name was pantheon-terminal . In v3@alpha.8 I could easy create a new project with the same terminal.

**Comment by lauriejim** [comment]
@Yobikap there is any errors displayed ?

**Comment by Yobikap** [comment]
No errors, only a blinking cursor in terminal.

**Comment by lauriejim** [comment]
Okay, are you able to try with one of these terminal ? https://github.com/SBoudrias/Inquirer.js#support-os-terminals

**Comment by Yobikap** [comment]
![screenshot from 2018-02-20 11 18 52](https://user-images.githubusercontent.com/2850919/36418712-f0478676-162f-11e8-92c2-f30f83b96781.png)
L: Konsole | R: Gnome-terminal

@lauriejim Tried with both of them it hangs on Database name: (strapi)

Still using node v8.1.0 (npm v5.6.0)

**Comment by lauriejim** [comment]
@Yobikap can you update to node 9.
But not sure it will solved this issue.

**Comment by Yobikap** [comment]
Node 9 solved this issue.
