### ISSUE TITLE
Double slash bug

### ISSUE THREAD

**Issue by Boujemaa1** [strapi/strapi#5650]
**Describe the bug**
Double slash shows a link to create first administrator.

**Steps to reproduce the behavior**
1. type  localhost:1337// in browser
2. Make sure you add 2 slashes //
3. Navigate 

**Expected behavior**
redirect to //localhost:1337

**Screenshots**
![bugstrapi](https://user-images.githubusercontent.com/51121850/77961701-22c11800-72d2-11ea-85bb-4c92c7dcebe5.png)

**System**
- Node .js version: v 12.2.0
- NPM version: v 6.9.0
- Strapi version: Strapi v 3.0.0-beta.19.3
- Database:  mongodb
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Not a security risk as the request from that link will fail (even if the link worked strapi would just redirect to login)

**Comment by derrickmehaffy** [comment]
@soupette is this something that "needs to be fixed"?

**Comment by Boujemaa1** [comment]
like you said it's not a security risk but must clean. Thanks for this beautiful cms!

**Comment by derrickmehaffy** [comment]
I've talked with the frontend strapi team and this isn't considered a bug. There isn't anything to "fix" here per say. There is never really a case where you would use/need a double slash after the domain.

Marking as closed
