### ISSUE TITLE
Missing Change Password in user permissions?

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#5653]
**Describe the bug**
🤞 I'm not missing something but it looks like the current `/change-password` REST and/or the
`changePassword` GraphQL mutation actually is handling the **reset password** logic. 

To fix this I'm proposing two things:
1. rename current `change-password` logic to `reset-password`
2. implement a new `change-password` mutation, for which I have a proposed PR, which I will reference in the comments shortly.

**Expected behavior**
For the global self-isolation to end soon.

**Proposed solution**
**Follow the progress:** https://github.com/strapi/strapi/pull/5655

**Inpired by**
The awesome PR https://github.com/strapi/strapi/pull/5580/ by @roelbeerens

**Comment by ScottAgirs** [comment]
PR with the proposed solutions https://github.com/strapi/strapi/pull/5654

**Comment by diogotcorreia** [comment]
Really looking forward to this!
Hope it gets merged soon 🤞
