### ISSUE TITLE
Content building missing Field type Enumeration

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#566]
**Node.js version**:
v9.4.0

**npm version**:
5.6.0

**Strapi version**:
Version: 3.0.0-alpha.9.1

**Operating system**:
Ubuntu 16.04 LTS

**Do you want to request a *feature* or report a *bug*?**
Feature & Bug

**What is the current behavior?**
Admin panel does not allow the option of enumeration, adding it to the Model.settings.json such as below and attempting to edit the content builder will not display anything.
`{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "test",
    "description": ""
  },
  "attributes": {
    "testString": {
      "type": "string"
    },
    "testNumber": {
      "type": "integer"
    },
    "testNumber2": {
      "type": "float"
    },
    "testNumber3": {
      "type": "decimal"
    },
    "testDate": {
      "type": "date"
    },
    "testEmail": {
      "type": "email"
    },
    "testText": {
      "type": "text"
    },
    "testBoolean": {
      "type": "boolean"
    },
    "testJson": {
      "type": "json"
    },
    "testPassword": {
      "type": "password"
    },
    "testEnum": {
      "type": "enumeration"
    }
  }
}
`

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Manually add a field with the type enumeration, start strapi, and attempt to edit the field with the content builder.

**What is the expected behavior?**
Able to add enumeration field, define options using the content builder.

**Comment by soupette** [comment]
Hi @derrickmehaffy in order to add your nex type in the content type builder you'll have to modify some files...

First you need to start your project in development mode [see the CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md).

Then in your `my-project/plugins/content-type-builder/admin/src/containers/Form/forms.json` file add the following:

In the `attribute` object
```json
"attribute": {
"enumeration": {
      "baseSettings": {
        "items": [
          {
            "label": "content-type-builder.form.attribute.item.enumeration.name",
            "name": "name",
            "type": "string",
            "value": "",
            "validations": {
              "required": true
            }
          }
        ]
      },
      "advancedSettings": {
        "items": [
          {
            "title": "content-type-builder.form.attribute.item.settings.name",
            "label": "content-type-builder.form.attribute.item.requiredField",
            "name": "params.required",
            "type": "checkbox",
            "value": false,
            "validations": {},
            "inputDescription": "content-type-builder.form.attribute.item.requiredField.description"
          },
          {
            "label": "content-type-builder.form.attribute.item.uniqueField",
            "name": "params.unique",
            "type": "checkbox",
            "value": false,
            "validations": {},
            "inputDescription": "content-type-builder.form.attribute.item.uniqueField.description"
          },
          {
            "label": "content-type-builder.form.attribute.item.minimumLength",
            "name": "params.minLength",
            "type": "checkbox",
            "value": false,
            "validations": {},
            "items": [
              {
                "label": "",
                "name": "params.minLengthValue",
                "value": "",
                "type": "number",
                "validations": {
                  "required": true
                }
              }
            ]
          },
          {
            "label": "content-type-builder.form.attribute.item.maximumLength",
            "name": "params.maxLength",
            "type": "checkbox",
            "value": false,
            "validations": {},
            "items": [
              {
                "label": "",
                "name": "params.maxLengthValue",
                "value": "",
                "type": "number",
                "validations": {
                  "required": true
                }
              }
            ]
          }
        ]

      }
    },
```

This step will allow you to edit your `enumeration` [field](http://localhost:1337/admin/plugins/content-type-builder/models/test#edittest::attributeenumeration::baseSettings::11)

Now we need to add some translation

In ``my-project/plugins/content-type-builder/admin/src/translation/en.json` file 

Add the following : 

```json
"form.attribute.item.enumeration.name": "Name",
  "attribute.enumeration": "Enum"
```

**Comment by derrickmehaffy** [comment]
I will test this and update if I have further issues. Just wondering why it wasn't added by default? 

Wasn't sure if this is something that was planned or was going to be removed from the CLI/documentation.

**Comment by lauriejim** [comment]
Hello @derrickmehaffy can you please give us an update about this issue.
@soupette message helped you ?

**Comment by derrickmehaffy** [comment]
I have not gone ahead with the changes, I have spoken with @pierreburgy who stated this should eventually make it into the existing project. I would image this issue should wait until a pull request is made to incorporate the enum field type in the admin panel as it is supported in the CLI.

**Comment by soupette** [comment]
This was fixed when we merged https://github.com/strapi/strapi/pull/685.
The enumeration type is still not supported in the content type builder yeet, however if the content manager handles it now if you manually create this type.

**Comment by derrickmehaffy** [comment]
@soupette a user is still unable to add the enum type from the admin UI though correct?
