### ISSUE TITLE
Upon first install: The SQL database indexes haven't been generated successfully.

### ISSUE THREAD

**Issue by rmcsharry** [strapi/strapi#5666]
**Describe the bug**
Upon first installation after building the admin panel, I type `npm run develop`
and receive this error:

![Screenshot 2020-03-31 at 22 23 52](https://user-images.githubusercontent.com/1156100/78071772-54071a00-739e-11ea-81cb-3ec8e8cd721a.png)

**Steps to reproduce the behavior**
1. Setup postgres in a docker container
2. npx create-strapi-app <app-name>
3. Fill in the postgres credentials
4. npm run build
4. npm run develop

**Expected behavior**
No errors.

**System**
- Node.js version:  11.6.0
- NPM version: 6.5.0-next.0
- Strapi version: v3.0.0-beta.19.4
- Database: Postgres
- Operating system: MacOS Catalina

**Comment by derrickmehaffy** [comment]
related to full-text indexes: https://github.com/strapi/strapi/issues/4813

These warnings can safely be ignored for now, the bookshelf backend for indexes needs to be rewritten which I believe is planned for strapi v4. marking this as closed for now as relates to https://github.com/strapi/strapi/issues/4813
