### ISSUE TITLE
[Feature] Automated Documentation with Swagger integration?

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#567]
**Do you want to request a *feature* or report a *bug*?**
Feature

Are they any current plans to integrate something like swagger for automated API documentation? Something along the lines of how loopback does its documentation structure (and also hiding certain listings based on permissions)

**Comment by Aurelsicoko** [comment]
@derrickmehaffy Thank for this feature request! Currently, it's not possible and it's not our main priority. However, the feature is already listed on the [Community Vote](https://strapi.io/vote) page and you can vote for it if it's important for you.

**Comment by derrickmehaffy** [comment]
For those curious and have found this with a search, I recommend you vote for the feature on the strapi vote page. Its listed as: 

```
Plugin - Documentation
Auto-generated documentation based on your API structure.
```
