### ISSUE TITLE
Multiple execution of the hook functions

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#5677]
**Describe the bug**
Multiple execution of the hook function in the models

**Steps to reproduce the behavior**
1. Go to 'api/**/models/**.js'
2. uncomment afterUpdate func or any other func 
3. and write(console.log("test"))
4. you will see
>>> test
>>> test
>>> test
>>> test

**Expected behavior**
>>> test

**Code snippets**

  // After updating a value.
  // Fired after an `update` query.
  afterUpdate: async model => {
      console.log("test")
}

**System**
- Node.js version: v12
- NPM version: v6
- Strapi version: v19.3
- Database: mysql
- Operating system: ubuntu18.04

**Comment by derrickmehaffy** [comment]
related/duplicate: https://github.com/strapi/strapi/issues/1443
