### ISSUE TITLE
Environment config creating wrong URL links in admin

### ISSUE THREAD

**Issue by sachin-rajput** [strapi/strapi#568]
**Node.js version**: 8.3.0

**npm version**: 5.4.0

**Strapi version**: 3.0.0-alpha.9

**Operating system**: OSX 10.13.1

**Do you want to request a *feature* or report a *bug*?** report a bug

**What is the current behavior?** 

Wrong URL creation in three files after updating env. json file

`admin/admin/build/config/plugins.json`
`admin/admin/build/main.js`
`admin/admin/src/config/plugins.json`

I'm trying to follow this [documentation](https://strapi.io/documentation/advanced/customize-admin.html#deployment) and separate admin and api. 

**If the current behavior is a bug, please provide the steps to reproduce the problem**

If we update the /environments/***/server.json as follows:

```
{
 "host": "localhost",
 "port": 1337,
 "autoReload": {
   "enabled": true
 },
 "cron": {
   "enabled": false
 },
 "admin": {
   "build": {
     "host": "http://admin.dev.domain/dashboard",
     "backend": "http://api.dev.domain",
     "plugins": {
       "source":  "host",
       "folder": "/plugins"
     }
   }
 }
}
```

Then after running - `npm run setup` in project root ( only rebuilds admin)
The config file update creates wrong url in plugin.json (under admin/admin/build/config):
it creates if env is development then:

`"development": "/http:/admin.dev.domain/dashboard"`

There are two more config files where this auto creation of URL is same as above

`admin/admin/build/main.js`
`admin/admin/src/config/plugins.json`

I was not able to achieve separation of admin and api even after correcting above URLs manually.
I did do `npm run setup --plugins` and then made sure to copy/paste build folder to server.

Please suggest the correct steps and also let me know if above observation is a bug.

**What is the expected behavior?**
Below URL should be created: ( I guess)

`"development": "http://admin.dev.domain/dashboard"`

**Comment by Aurelsicoko** [comment]
Try to add a slash at the end of your URLs.

```json
{
 "admin": {
   "build": {
     "host": "http://admin.dev.domain/dashboard/",
     "backend": "http://api.dev.domain/",
     "plugins": {
       "source":  "host",
       "folder": "/plugins"
     }
   }
 }
}
```

Also, can you try with a simpler URL like `http://admin.domain/dashboard` and `http://api.domain`. The bug could be related to the sub-domain...

**Comment by lauriejim** [comment]
Hi @sachin-rajput can you give us an update if the @Aurelsicoko message helped you please.

**Comment by lauriejim** [comment]
No news after my last message, I close this issue.
