### ISSUE TITLE
strapi-connector-mongoose 3.0.0-beta.19.4 removes all manually created indexes

### ISSUE THREAD

**Issue by AHgPuK** [strapi/strapi#5682]
**Describe the bug**
After upgrading to 3.0.0-beta.19.4, strapi-connector-mongoose started to remove manually created indexes at launch point.

Breaking changes at mount-models.js:

>     
    // Ensure indexes are synced with the model, prevent duplicate index errors
    Model.syncIndexes(null, () => {
      Model.on('index', error => {
        if (error) {
          if (error.code === 11000) {
            strapi.log.error(
              `Unique constraint fails, make sure to update your data and restart to apply the unique constraint.\n\t- ${error.message}`
            );
          } else {
            strapi.log.error(`An index error happened, it wasn't applied.\n\t- ${error.message}`);
          }
        }
      });
    });

**Expected behavior**
Indexes should remain

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.4
- Database: MongoDB
- Operating system: All

**Additional context**
I think if we would replace syncIndexes to ensureIndexes then it could solve this problem.

**Comment by alexandrebodin** [comment]
Hi @AHgPuK Can you explain what are the other indexes you need ? 

Using `ensureIndexes` will not fix the problem with duplicate indexes which is why we made the change in the first place. 

Would you consider having the possibility to customize the model during the creation process a solution for your issue ?

**Comment by AHgPuK** [comment]
I need a lot of compound indexes for query optimizations to use big data.
The main problem - there is no entry point between mongoose schema and model creating to interact with a schema in order to add my own custom indexes.

**Comment by alexandrebodin** [comment]
Before we can provide a clean way to create those indexes via Strapi, I would like to propose only running this sync in development mode so it doesn't clear your indexes in production.

This would go along not applying changes to the content. when the schema changes. 

Would that work for you until we design a better approach to this ?

**Comment by AHgPuK** [comment]
Yes, I think it is good enough.

**Comment by nuno-tomas** [comment]
I've realized I can create different single index types by using the syntax documented on mongoose at the SCHEMA.settings.json:
"title": {
    "type": "string",
    "index": "text"
}
but can't really find a way to create a compound index without hacking (currently I'm delaying the execution of the manual index creation).
