### ISSUE TITLE
Email plugin not sending attachment

### ISSUE THREAD

**Issue by victormidp** [strapi/strapi#5685]
**Describe the bug**
Strapi is not being able to send a pdf attachment thru email using strapi-provider-email-sendgrid. I even tried replacing the file with just text and the file name as "file.txt" but it did not work. The email always arrives but without the file.

**Steps to reproduce the behavior**
1. Install the plugin strapi-provider-email-sendgrid
2. Configure the email plugin
3. Go to the /API folder and create the config and controllers folders with the appropriate files inside.
4. Set the route method as POST
5. Create a controller (see code snippets section)
6. Set a valid email for receiving the message
7. Run development mode and send a request to the created route that contains a file with the multipart form property name as "file".

**Expected behavior**
Receive an email that contains the file sent on the request to the defined endpoint/route

**Screenshots**

**Code snippets**
routes.json
```json
{
    "routes": [
      {
        "method": "POST",
        "path": "/test-form",
        "handler": "Test-form.index"
      }
    ]
}
  
```
Test-form.js
```js
const fs = require('fs');

module.exports = {
    // GET /test-form
    index: async ctx => {
      const file = ctx.request.files.file;
      const filePath = file.path;
      const attachment = fs.readFileSync(filePath).toString('base64');

      res = await strapi.plugins['email'].services.email.send({
              to: 'test@example.com',
              from: 'noreply@example.com',
              subject: 'File',
              text: `
              New file sent
              `,
            attachments: [
              {
                filename: 'file.pdf',
                content: attachment
              }
            ]
      }).then(() => console.log('Sent')).catch((err) => console.log(err));
      ctx.send('DONE');
    },
};
```

**System**
- Node.js version: v12.8.0
- NPM version: 6.14.4
- Strapi version: v3.0.0-beta.19.3
- Database: Postgres
- Operating system: Mac OS Catalina

**Additional context**
[file.pdf](https://github.com/strapi/strapi/files/4417497/file.pdf)

**Comment by lauriejim** [comment]
I'm closing this issue, I just tested and it works fine.
Successfully sent the file with your code.

ps: you have to update
```diff
- res = 
+ const res = 
```

**Comment by MSafyan** [comment]
NOTE:
I was on AWS SES sandbox and attachments were not working but then I moved to SendGrid and was able to send email attachments.
Don't know specifics just my experience.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-email-provider-attachment/1851/2
