### ISSUE TITLE
Default findOne responding with error 400 'Bad request'

### ISSUE THREAD

**Issue by PavloTyshchenko** [strapi/strapi#5688]
**Describe the bug**
When I'm trying to fetch any data by it's id (for example: "http://localhost:1338/courses/1") I get next error: 
```
{statusCode: 400, error: "Bad Request", message: "Your filters contain a field '0' that doesn't appear on your model definition nor it's relations"}
```
I tried to use findOne with console.log, so ctx.params looks like: 
```
{ '0': 'courses/1', id: '1' }
```
There is no difference between default controllers and controller with custom functions - it concerns all content types.
Permissions - everything allowed for public. Other routes work fine.
What could be the cause?

**Steps to reproduce the behavior**
Actually I don't know what happend with project. Previous commits did not affect any configurations.

**Expected behavior**
I should get entity by id from server.

**System**
- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.7
- Database: sqlite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-beta.18.7` Please test on the latest version.

If you have any custom routes you may have a conflict

**Comment by drewtownchi** [comment]
Oddly enough I started seeing this after upgrading to 19.5 with Postgres/Win10/Node 12.  19.3 was fine.

**Comment by derrickmehaffy** [comment]
Can you post the code you are using or a link to your project somewhere? (Github/Gitlab/Bitbucket)

**Comment by drewtownchi** [comment]
The repo is private, sorry.

This is from the `controllers\sources.js` file

```js
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  async find(ctx) {
  // snip, this works fine
  },
    async findOne(ctx) {
      const entity = await strapi.services.source.findOne(ctx.params);
      if(entity.picks) {
        delete entity.picks
      }
      return sanitizeEntity(entity, { model: strapi.models.source });
    },
};
```

**Comment by PavloTyshchenko** [comment]
@derrickmehaffy updated strapi and got same behaviour as **drewtownchi** . Now I only see this when overriding the findOne method in the controller too.

**Comment by derrickmehaffy** [comment]
@alexandrebodin @lauriejim any thoughts here? It looks to me like they are using the custom response guide from the docs.

**Comment by alexandrebodin** [comment]
Hi yes we refactored the findOne to allow for filtering other than just the id. Doing this means we use all the params sent to findOne. (As it should be anyway)

You shouldn't be using ctx.params directly but use the params you need only. Here it is the id.

eg: `findOne({ id: ctx.params.id })`

We didn't think about updating the docs to explain the right way to calls thoses methods sadly.

**Comment by alexandrebodin** [comment]
I think we need to update this doc only @derrickmehaffy  ? https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#custom-controllers

**Comment by derrickmehaffy** [comment]
I believe so, I don't think services need to be changed. Tested PR and that works. 

@PavloTyshchenko @drewtownchi see that PR for a quick fix in your own projects
