### ISSUE TITLE
Profile /me endpoint example

### ISSUE THREAD

**Issue by Amurmurmur** [strapi/strapi#569]
Since user related end points are inside a user-permissions plugin under:
```
/plugins/user-permissions/controllers/User.js line 36
```

Is it a good practise to just modify controller/models/services to output more data about the user, for example age etc any extra data the user would put?

Or what would be the best practice not to touch the plugin but maybe combine the data from the plugin with the endpoint data like api/profile or something?

**Comment by Aurelsicoko** [comment]
@Amurmurmur Currently, the best way is to edit the model provided by the plugin. We already thought to find a way to add attributes to a model without edit the original model but it's not our priority right now.

**Comment by Amurmurmur** [comment]
Thank you so much for clearing it up for me!
