### ISSUE TITLE
strapi beforeCreate method not working as expected

### ISSUE THREAD

**Issue by Onyejekwe1** [strapi/strapi#5692]
I'm working on an e-commerce app using flutter and strapi, I have a strapi user.js model, and I want the beforeCreate method to add a stripe customer_id to the user model before create. This is my code:
```
beforeCreate: async (model) => {
const customer = await stripe.customers.create({
email: model.get('email')
})
console.log(customer);
model.set('customer_id', customer.id);
},
```
But it's not adding the customer_id as expected. Or is there any other way I can generate a customer id from stripe and assign it to the current user on create? I 'm using strapi version 3.0.0-beta.19.3

**Comment by derrickmehaffy** [comment]
Closing, please see the following issue: https://github.com/strapi/strapi/issues/1443
