### ISSUE TITLE
WYSIWYG editor's Performance is very slow for huge files/content on Stapi-Beta

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5693]
**Describe the topic**
We have a collection-type for API docs & our API docs are huge files with around 20, 000 lines of md content. Since we added all of this content to one article/WYSIWYG content editor, it is causing high performance issues, taking 3-4 minutes to load the article which has this huge content.

How can we improve performance of WYSIWYG loading time? it became so difficult to update content on Strapi now.

**Note:** 
1. The API response is quick & loading fast on the front-end as well from DB
2. It was faster on earlier Alpha version, we are facing this issue only after migrating our App to latest Beta.

**Your suggestions for this topic**
WYSIWYG editors loading time/performance should be faster even when it has huge content.

**Additional context**
This is blocking our release.

- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
