### ISSUE TITLE
WYSIWYG editor's Performance is very slow for huge files/content on latest Stapi-Beta

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5695]
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
We have a collection-type for API docs & our API docs are huge files with around 20, 000 lines of md content. Since we added all of this content to one article/WYSIWYG content editor, it is causing high performance issues, taking 3-4 minutes to load the article which has this huge content.

How can we improve performance of WYSIWYG loading time? it became so difficult to update content on Strapi now.

**Your suggestions for this topic**
WYSIWYG editors's loading time should be faster even for huge files/content

**Screenshots**
<img width="1680" alt="Strapi - Content Manager 2020-04-02 16-14-29" src="https://user-images.githubusercontent.com/23507845/78300420-1a005a00-74fd-11ea-88ba-d8cc6bc26bc1.png">

**Code snippets**
N/A

**To Reproduce:**
Please add around 20,000 lines of markDown content to WYSIWYG field and test loading time

**Additional context**
WYSIWYG editors loading time/performance should be faster even when it has huge content.

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.19.3
- Database: Mongo
- Operating system: MAC

**Comment by lauriejim** [comment]
Hello! You already created 3 issues about that - https://github.com/strapi/strapi/issues/5619
