### ISSUE TITLE
Strapi does not work with latest version of the `pg` package

### ISSUE THREAD

**Issue by hissalht** [strapi/strapi#5696]
**Describe the bug**
Latest version of the `pg` package (`8.0.0`) is not compatible with strapi.

**Steps to reproduce the behavior**
1. Install the `pg` package like described here https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#_5-install-the-pg-node-module
2. Start the server with the following config.
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST}",
        "port": "${process.env.DATABASE_PORT}",
        "database": "${process.env.DATABASE_NAME}",
        "username": "${process.env.DATABASE_USERNAME}",
        "password": "${process.env.DATABASE_PASSWORD}",
        "ssl": true
      },
      "options": {}
    }
  }
}
```
3. The server fails to start with the following error.
```
➜  project-folder git:(master) ✗ yarn develop 
yarn run v1.22.0
$ strapi develop
[2020-04-02T22:06:49.564Z] error Impossible to register the 'model-name' model.
[2020-04-02T22:06:49.568Z] error Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
When I start the server in production mode, the connection to the DB is made.

**How to fix**
Install the last `7.x.x` version instead.
```bash
yarn add pg@^7.18.2
```

**Note**
The `7.18.2` version of `pg` shows a deprecation warning.
```
(node:3130) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.
```

**System**
- Node.js version: v12.16.1 LTS
- Strapi version: 3.0.0-beta.19.3
- Database: PGSQL
- Operating system: Ubuntu WSL on windows/heroku dyno

**Comment by daxyonis** [comment]
I had the same problem deploying my strapi backend to Heroku with the Postgres addon. The deprecation warning you referred to seems to have the solution...
This is what I used to fix it using the latest pg version (^8.0.0) and in production\database.json : 
`"ssl": {
          "rejectUnauthorized": false
        }`

**Comment by derrickmehaffy** [comment]
Linking upstream issue: https://github.com/brianc/node-postgres/issues/2009

**Comment by matheusgrieger** [comment]
I have set up a Strapi project today with the latest `pg` version and it is working normally, as it seems so far.

**Comment by alexandrebodin** [comment]
@hissalht Did the pg lib resovle the issue with a new version ? Is it good for you now ?

**Comment by hissalht** [comment]
Like [daxyonis said](https://github.com/strapi/strapi/issues/5696#issuecomment-608179879), it just a matter of updating the config.

Updating [the doc ](https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html#_4-update-your-database-config-file)should be enough to close this issue.

**Comment by alexandrebodin** [comment]
We just merged a PR to update the docs. It will be updated on the next release. (beta.20.3) I'm going to close the issue :)

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/error-no-pg-hba-conf-entry-for-host-ssl-off/3409/1

**Comment by hawaiifi** [comment]
The fix is in the latest docs:

https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/databases.html#configuration-structure

Update ./config/database.js

`module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', '127.0.0.1'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'strapi'),
      user: env('DATABASE_USERNAME', 'strapi'),
      password: env('DATABASE_PASSWORD', 'strapi'),
      schema: env('DATABASE_SCHEMA', 'public'), // Not required
      ssl: {
        rejectUnauthorized: env.bool('DATABASE_SSL_SELF', false), // For self-signed certificates
      },
    },
    debug: false,
  },
});`
