### ISSUE TITLE
Can't disable aggregation on GraphQL

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#5697]
**Describe the bug**
There is no way to disable the aggregation feature for a specific type.

**Steps to reproduce the behavior**
1. Install the GraphQL extension
2. Copy the snippet below into `schema.graphql.js` for the API type.
3. Try to query `{api type name}Connection`
4. See that it still works when it should have been disabled

**Expected behavior**  
For example, considering an API for `order`, this should disable the `ordersConnection` query on GraphQL, but it doesn't:
```javascript
module.exports = {
  type: {
    OrderConnection: false, // This shouldn't even be necessary, but it also does nothing
  },
  resolver: {
    Query: {
      ordersConnection: false,
    },
  },
};
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/78308089-67052000-753f-11ea-9a0b-129f9c70e30e.png)

**System**
- Node.js version: `v13.7.0`
- NPM version: `v6.13.6`
- Yarn version: `v1.22.4`
- Strapi version: `v3.0.0-beta.19.5`
- Database: `MongoDB`
- Operating system: `Windows 10 1909 with WSL Ubuntu 18.04 LTS`

**Additional context**
This is relevant to me because I've limited the `find` and `findOne` controllers to only show the orders from the logged-in user. However, this aggregator returns the count of the orders from ALL users, which I don't want to be public.
I'd like to disable it since I'm not using it and it's just leaking data I don't want to.

**Comment by rmonnier9** [comment]
I have the same problem, did you find a solution ?

**Comment by diogotcorreia** [comment]
@rmonnier9 I did, but the solution is not pretty. I could only find this by digging in the `strapi-plugin-graphql` source code.
You have to disable the default `find` resolver (e.g. for an `order` type, disable the `orders` resolver).
Then you can create your own resolver:
```js
module.exports = {
  query: `
    ordersCustom(sort: String, limit: Int, start: Int, where: JSON): [Order]
  `,
  resolver: {
    Query: {
      orders: false,
      ordersCustom: {
        resolver: 'application::order.order.find',
      },
    },
  },
};

**Comment by rmonnier9** [comment]
@diogotcorreia 
Thanks for your answer ! I just tried and it works.

However we have to change that for every Content Type, I tried to check the source code as well but I didn't find a way to easily add an option to disable the aggregation types and queries generation.

**Comment by diogotcorreia** [comment]
@rmonnier9 There is actually an easy way to disable aggregation for all content types.

The code responsible for that is https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/type-definitions.js#L409-L418 .
So if you delete that in `node_modules/strapi-plugin-graphql/services/type-definitions.js`, it shouldn't load aggregation anymore.

You can then use [patch-package](https://www.npmjs.com/package/patch-package) to make those changes permanent in your project.
