### ISSUE TITLE
Forgot Password doesn't work for Guests

### ISSUE THREAD

**Issue by illoRocks** [strapi/strapi#570]
**Node.js version**: 9.0.0

**npm version**: 5.6

**Strapi version**: 3.0.0-alpha.9.1

**Operating system**: Ubuntu

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
Get an error when a guest role send a forgot-password request:
`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.email.invalid"
                }
            ]
        }
    ]
}`
If the admin send a forgot-password request then the result is:
`{
    "ok": true
}`

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Use the /auth/forgot-password with an email from a guest-role

**What is the expected behavior?**the
sending email with reset password token

**Comment by lauriejim** [comment]
Hello @illoRocks ! Thank you for this issue.

But I can't reproduce this issue. Your error message come from this line :https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-email/services/Email.js#L33

Can you log and give me the `err` content please.

**Comment by illoRocks** [comment]
Hello,

I checked that and I think my email provider (for the guest account) blocked the mail
because of missing configurations or something else (I use my local pc). The behavior is independent of the role.

(The `err` was an empty object)

Sorry for the effort.
