### ISSUE TITLE
plugin model not found

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#5701]
**Describe the topic**
i generate new plugin by this command 
```
yarn strapi generate:plugin track
```
then i generate new model by this command (becuase model directory and file not created when plugin generated)
```
yarn strapi generate:model log --plugin track
```
i see a model directory created inside a mode directory

```
***
controllers
models
    models
        Log.js
        Log.settings.json
``` 
Is it normal ???? two model directory ?

i fill Log.settings.json like this 

```
{
  "connection": "default",
  "collectionName": "Track_logs",
  "info": {
    "name": "log"
  },
  "options": {
    "increments": true,
    "timestamps": ["created_at", "updated_at"]
  },
  "attributes": {
    "message": {
      "type": "text"
    },
    "username": {
      "type": "string"
    }
  }
}
```
and then when i user log table by this code 

```
const test = await strapi.query('log','track').find({id:1})
```
i get error
```
error Error: The model log can't be found.
```
i suggest we should have one model directory i transfer file 
```
controllers
models
    Log.js
    Log.settings.json
``` 
now i have this error
```
error Error: [GraphQL] Cannot find action "plugins::track.log.findOne". Check your graphql configurations.

```

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment]
I attempted to reproduce this on the latest beta ( `beta.19.5`) and could not, using the plugin/model generate commands works fine and generates the expected folder structure: 
![image](https://user-images.githubusercontent.com/8593673/78360041-04297e00-756b-11ea-905b-786570065c3d.png)

**Comment by lauriejim** [comment]
I also tried and it works well.
