### ISSUE TITLE
Db initial data population

### ISSUE THREAD

**Issue by KonstantinKudelko** [strapi/strapi#5706]
Hello 👋

Do we have some way for initial data population before strapi starts?

Thanks a lot!

**Comment by juandl** [comment]
@KonstantinKudelko do you find a way for this?

**Comment by johanguse** [comment]
Check the [ecommerce template](https://github.com/strapi/strapi-template-ecommerce) there's a sample in there. The folder `data` has a database and `config/functions/bootstrap.js` has a function to populate.
