### ISSUE TITLE
ArangoDB Support

### ISSUE THREAD

**Issue by ronbravo** [strapi/strapi#5708]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

This is a feature request for seeing if the ArangoDB could be supported. Arrango supports multi-model structure and also has the ability to support some SQL like statements with it's AQL language. Going through some of the discussions about Strappi's ORM mapping needs and the choice to work SQL friendly DBs (SQLite, MySQL, Postgres, etc) because of the structured data, it seems like an opportunity to support a DB like Arango which provides a nice set of features for the developer. I think there was talk at one point of providing multiple DB support through some kind of plugin architecture?

**Comment by ronbravo** [comment]
@derrickmehaffy  Thanks for the quick reply. Is there an area of strapi where I can investigate how the calls to the backend are being wrapped or abstracted away. I figure I could make a fork and on my own I can maybe add / modifiy code or somekind of driver to connect to https://orango.js.org? I am a bit new to all of this. I don't want to build an Headless CMS from scratch so strapi seems like a really nice option, however I would like access to the arangodb. Would this be something outside the range of possibility, even if I did it myself? Also, if it's not a bad idea, any recommendations where I could start reading or looking into how strapi connects to databases?

**Comment by alexandrebodin** [comment]
Hi, We aren't going to add new databases until we totally refactor our database layer no.

**Comment by derrickmehaffy** [comment]
@ronbravo you will want to look at the connectors but right now it would not be an easy process to create your own. As Alex mentioned they plan on completely refactoring those as is.

**Comment by mysticaltech** [comment]
Hey Stapi team, when you do refactor you db layer, please see [ArangoDB](https://www.arangodb.com/) as a priority, it is one of the best multi-model DB out there! **KV, Document, Graph and Search All-in-one**, nothing can ever beat that, and they have a pretty solid JS client https://github.com/arangodb/arangojs. Keep up the good work! Merci beaucoup 👍
