### ISSUE TITLE
Can't update Content-types view

### ISSUE THREAD

**Issue by rmonnier9** [strapi/strapi#5709]
**Describe the bug**

For every collection, when I try to customize the view in the admin panel, I get a 400 validationError : this field cannot have keys not specified in the object shape.

**Steps to reproduce the behavior**
1. Go to the admin panel
2. Click on a collection
3. Click on Edit the view
4. Set 20 documents per page for example and Save

**System**
- Node.js version: 12.14.0
- NPM version:
- Strapi version: 3.0.0-beta.19
- Database: postgres
- Operating system: Mac OS

Hi Strapi Community !

Does anyone else have this bug ?

I checked the validation schema here: 

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/controllers/validation/model-configuration.js

and it seems like my admin frontend send this field that is not in the schema: apiID: "collectionName".

Thanks for your help !

**Comment by derrickmehaffy** [comment]
Update to the latest hot fix beta.19.5

**Comment by soupette** [comment]
@derrickmehaffy should we close this issue?

**Comment by derrickmehaffy** [comment]
Yup @soupette the bug is likely related to the old version the user is on, marking as closed.
