### ISSUE TITLE
Cannot create new strapi-project using MySQL (MariaDB)

### ISSUE THREAD

**Issue by typoworx-de** [strapi/strapi#571]
**Node.js version**: v8.4.0
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.9.1
**Operating system**: Ubuntu 16.04 (Xenial)

Bug request

**What is the current behavior?**
`strapi new strapi-test
INFO (19961 on gabriel-G75VX): Creating your application... It might take a few seconds.
INFO (19961 on gabriel-G75VX): Lets configurate the connection to your database:
 Choose your main database: MySQL
 Database name: project_strapi
 Host: localhost
 Port: 3306
 Username: project
 Password: project
INFO (19961 on gabriel-G75VX): Testing database connection...
WARN (19961 on gabriel-G75VX): Database connection has failed! Make sure your database is running.`

**If the current behavior is a bug, please provide the steps to reproduce the problem**
See above. Tried to create new project using strapi on local dev-machine (using MariaDB as MySQL Server). Port 3306 is open (also there's no "skip-networking" in my.cnf).
User "project" has access to all database-scopes "project_%". Did not make any difference I created the database before running strapi or not (same error as above).

**What is the expected behavior?**
Database creation should success. Other programs (php+mysql) work as expected on same dev-machine.

**Comment by rroblik** [comment]
+1 , same for me

**Comment by derrickmehaffy** [comment]
+1 Also looking for further support on MariaDB. My testing also yielded the same results.

**Comment by Aurelsicoko** [comment]
@typoworx-de @rroblik @derrickmehaffy Hey guys, I just tested and it works like a charm on my machine. Can you give me all the steps to reproduce the issue?

**Comment by wizysanjay** [comment]
I'd got the same error

Lets configurate the connection to your database:
? Choose your main database: MySQL
? Database name: strapi
? Host: localhost
? Port: 3306
? Username: root
? Password: **********

⏳ Testing database connection...
⚠️ Database connection has failed! Make sure your "strapi" database exist.

Node.js version: v9.3.0
npm version: 6.2.0
Strapi version: 3.0.0-alpha.13
mariadb
mac osx

**Comment by lauriejim** [comment]
I think you are on Windows. Please check here https://github.com/strapi/strapi/issues/1612#issuecomment-406988561

**Comment by wizysanjay** [comment]
Sorry, but I'm really on MacOS

<img width="579" alt="screenshot 2018-07-26 21 53 28" src="https://user-images.githubusercontent.com/13049732/43270063-63480452-911e-11e8-9fd1-0379f780d5ab.png">

**Comment by Aurelsicoko** [comment]
@wizysanjay Did you create the database `strapi` in your MySQL database?

**Comment by wizysanjay** [comment]
of course, It's ready

<img width="451" alt="screenshot 2018-07-26 23 32 32" src="https://user-images.githubusercontent.com/13049732/43275529-3db63480-912c-11e8-8273-901811c16878.png">

**Comment by derrickmehaffy** [comment]
@wizysanjay what version of MariaDB? I'm running a Galera Cluster with MariaDB 10.2.16 and am not having this issue (Local MariaDB as well works fine)

I also would suggest you create a user in MariaDB for Strapi and not use the built in root account.

**Comment by wizysanjay** [comment]
@derrickmehaffy sorry, I've checked it again, it not mariadb, 

<img width="566" alt="screenshot 2018-07-27 08 42 04" src="https://user-images.githubusercontent.com/13049732/43297040-18bea8fe-9179-11e8-814a-d26bf18328a8.png">

**Comment by derrickmehaffy** [comment]
@wizysanjay can you try updating MySQL to either 5.6 LTS, 5.7 Stable, or 8.0 Latest

Just for your reference:
MariaDB Version -> MySQL Version
10.0 -> 5.6
10.1 -> 5.7
10.2 -> 5.7
10.3 -> 5.7

**Comment by wizysanjay** [comment]
@derrickmehaffy Thank for your support, It's worked !

**Comment by derrickmehaffy** [comment]
No problem :smiley: 

@johannpinson looks like MySQL 5.6 is bare minimum for Strapi on your PR for the versions
