### ISSUE TITLE
Ability to use `os` module in configuration files?

### ISSUE THREAD

**Issue by brookskindle** [strapi/strapi#5710]
**Describe the bug**
Within a `<environment>/database.json` configuration file, I am unable to use the `os` module to obtain the current person's username.

Example: `config/environments/development/database.json`
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "database": "${process.env.DEV_DATABASE_NAME || 'my-db'}",
        "host": "${process.env.DEV_DATABASE_HOST || 'localhost'}",
        "port": 5432,
        "username": "${process.env.DEV_DATABASE_USER}",
        "password": "${process.env.DEV_DATABASE_PASSWORD || ''}"
      },
      "options": {}
    }
  }
}
```
I have the ability to specify sane defaults for most of the connection information, but the one thing I wish I had was the ability to default the `username` to the current user. This could be accomplished by using `os.userInfo().username`
```json
        "username": "${process.env.DEV_DATABASE_USER || os.userInfo().username}",
```
But `os` isn't imported by default so the following error occurs when calling `npm start`
```
[2020-04-04T00:18:38.866Z] debug ⛔️ Server wasn't able to start properly.
[2020-04-04T00:18:38.867Z] error error: role "${process.env.DEV_DATABASE_USER || os.userInfo().username}" does not exist
```

My question is: Is there a way to specify a list of custom module imports that can be accessible while importing configs?

**Steps to reproduce the behavior**
1. Create a new project
2. Within `config/environments/development/database.json`, edit the `username` field (or similar) to call `os.userInfo().username`.
    * `        "username": "${os.userInfo().username}",`
3. Run `npm start`

**Expected behavior**
The database connection string correctly interprets `os.userInfo().username` and fetches the current user's username

**Screenshots**
<img width="1382" alt="Screen Shot 2020-04-03 at 6 19 58 PM" src="https://user-images.githubusercontent.com/2654835/78415678-1f7ea280-75d8-11ea-86dc-0b922b4f9a18.png">

**System**
- Node.js version: 
- NPM version: v12.10.0
- Strapi version: 3.0.0-beta.19.5
- Database: postgres
- Operating system: macOS Mojave 10.14.6

**Comment by derrickmehaffy** [comment]
You can convert the config file from .json to .js and wrap the json in a `module.exports` thus allowing you to call in additional packages.

I'm going to mark this issue as closed as there is a pending PR for a massive config system rewrite that will change all config files to .js anyway.
