### ISSUE TITLE
Sqlite: filter not working on one to many relation.

### ISSUE THREAD

**Issue by hlege** [strapi/strapi#5714]
**Describe the bug**
A Simple filter is not working on a relation between two collections.
Strapi: 3.0.0-beta.19.3 (node v10.14.2) with sqlite

**Steps to reproduce the behavior**
1. Create a Color collection
2. Create a Dog collection with one to many relations to Color
3. Create a Color content eg.: White
4. Create a Dog content
5. Create other Dog content and select White color

**Expected behavior**
/dogs -> list all dogs and the second dog has a white color with id:1
/dogs?colors.id_in=1 ->  excpect the dogs with color id:1.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by hlege** [comment]
Is it still not good?

**Comment by lauriejim** [comment]
Hello! I just tried to reproduce your issue and it works well on my side.
Here is what I did - https://www.loom.com/share/15a5323fe9ac4024a6f009d07a26acd3
Let me know if I miss something.

**Comment by hlege** [comment]
You choose the wrong relation type. I choose the last one. "XXX has many YYY" type.

**Comment by lauriejim** [comment]
Okay you did ` /tests?color.id=1` and should be ` /tests?colors.id=1`
