### ISSUE TITLE
Upload Path

### ISSUE THREAD

**Issue by yapnel** [strapi/strapi#5723]
Hi

Is there a way to change the upload path for file upload plugin to something else? I want to point it to a network share path to store the uploaded files.

Thanks,

**Comment by jlvadell** [comment]
Hi yapnel,

The uploaded files by default are stored in the public assets folder, I didn't find a way to change the uploads folder path but you can change the entire public assets folder path: 
[Docs](https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#Application)

Hope it helps.
