### ISSUE TITLE
Collection Types don't use custom plural in sidebar

### ISSUE THREAD

**Issue by locopati** [strapi/strapi#5727]
**Describe the bug**
A custom plural collection type name should be display in the sidebar

**Steps to reproduce the behavior**
1. Create a Collection Type named 'One'
2. Edit the description > Advanced Settings > Collection Name = 'many'
3. Observe the Collection Types in the sidebar
4. The sidebar displays 'Ones'

**Expected behavior**
I expect the sidebar to display 'Many'

**Screenshots**
![image](https://user-images.githubusercontent.com/41705/78618832-a1c1cd80-7849-11ea-8eae-abd17d496ab1.png)

![image](https://user-images.githubusercontent.com/41705/78618935-e5b4d280-7849-11ea-83df-7a62959f3979.png)

**System**
- Node.js version: 13.7
- NPM version: 6.14.2
- Strapi version: 3b19.5
- Database: Mongo 4.2.5
- Operating system: Arch Linux 4.19.97

**Comment by lauriejim** [comment]
Hello @locopati !
The `Collection name` has an impact only in your database, this will not impact the value displayed in the Admin Panel.
You will not able to customize the value in the menu for now.
This is in our Roadmap - https://portal.productboard.com/strapi/1-public-roadmap/c/13-administration-menu
