### ISSUE TITLE
Is there any way to allow user access to /admin with restrict permission ?

### ISSUE THREAD

**Issue by anhhtz** [strapi/strapi#5728]
Hello,

I want to allow users who can access to `/admin` with low permission. They can:
- NOT create new `content-type`.
- Manage their `content-types` like as C,R,U,D.
- Manage their profile like as Fullname, email, password,...
- ...

Best regards,

**Comment by derrickmehaffy** [comment]
Please see the following FAQ: https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#user-can-t-login-to-the-admin-panel
