### ISSUE TITLE
Cannot delete file already deleted in Cloudinary

### ISSUE THREAD

**Issue by jiv-e** [strapi/strapi#5729]
**Describe the bug**
Cannot delete file already deleted in Cloudinary when using strapi-provider-upload-cloudinary.

**Steps to reproduce the behavior**
1. Use Cloudinary provider.
2. Upload a file.
3. Delete the file directly from Cloudinary (use the Cloudinary UI for example).
4. Go to Strapi's File Upload page and click the trashcan icon of the uploaded file.

**Expected behavior**
The file information would be removed from Strapi.

**Actual behavior**
Error message is displayed. The file information is not removed.

**Screenshots**
![2020-04-07_10-56-47](https://user-images.githubusercontent.com/831144/78644415-83e28000-78be-11ea-9fd7-9415b3746079.png)

**Comment by derrickmehaffy** [comment]
Please update your bug report with the required information from the template:

```
**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:
```

**Comment by lauriejim** [comment]
Hello @jiv-e thank you for reporting this issue.
It is not a case we managed in the Cloudinary provider.
Can you please submit a PR to fix it please. I will really appreciate your contribution to this issue.

**Comment by dhiyo7** [comment]
> **Describe the bug**
> Cannot delete file already deleted in Cloudinary when using strapi-provider-upload-cloudinary.
> 
> **Steps to reproduce the behavior**
> 
> 1. Use Cloudinary provider.
> 2. Upload a file.
> 3. Delete the file directly from Cloudinary (use the Cloudinary UI for example).
> 4. Go to Strapi's File Upload page and click the trashcan icon of the uploaded file.
> 
> **Expected behavior**
> The file information would be removed from Strapi.
> 
> **Actual behavior**
> Error message is displayed. The file information is not removed.
> 
> **Screenshots**
> ![2020-04-07_10-56-47](https://user-images.githubusercontent.com/831144/78644415-83e28000-78be-11ea-9fd7-9415b3746079.png)

how to connect between strapi and cloudinary? I have searched for references but still failed

**Comment by lauriejim** [comment]
Here is the function that deletes the files. ([code](https://github.com/strapi/strapi/blob/master/packages/strapi-provider-upload-cloudinary/lib/index.js#L47))
I think you can check the error that is returned when you are deleting a file and this file is already deleted. Then add the exception to not send an error in this case.

**Comment by jiv-e** [comment]
Thanks for pointing that out! I may work on this later, but I happily give this to anyone who is interested.

**Comment by arnellebalane** [comment]
Hi, I would like to work on this issue. Thanks @lauriejim for pointing to the right direction on where to start looking into it!
