### ISSUE TITLE
Extending a Model Service "Create" return 500 when alongside with files

### ISSUE THREAD

**Issue by maisur** [strapi/strapi#5743]
**Describe the bug**
I want to extending my model service following instruction from this [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/services.html#extending-a-model-service)

**Steps to reproduce the behavior**
1. Just copy & paste the code from [documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/services.html#extending-a-model-service) in "create" tab to my service file
![image](https://user-images.githubusercontent.com/47018830/78753993-ef048300-79a0-11ea-8946-e0f6449f8cea.png)
2. Hit my API Endpoint using postman
3. Return 500
![image](https://user-images.githubusercontent.com/47018830/78754132-2bd07a00-79a1-11ea-9e2d-5ec66bd82d15.png)
![image](https://user-images.githubusercontent.com/47018830/78754635-04c67800-79a2-11ea-91aa-6c5505e1438a.png)

**Expected behavior**
A new data is created.

**System**
- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.5
- Database: mysql
- Operating system: Linux

is there something i miss?

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue.
`model` should be a string.
```js
await strapi.entityService.uploadFiles(entry, files, {
  model: 'item',
});
```
I will fix that now.
