### ISSUE TITLE
GraphQL Cannot return null UsersPermissionsMe.id

### ISSUE THREAD

**Issue by Fl4zher** [strapi/strapi#5748]
**Describe the bug**
When i try to get "Me" query from frontend client with apollo client, i get this error message: 
'GraphQL error: Cannot return null for non-nullable field UsersPermissionsMe.id.'

This error is only when no user is found. So the graphql still expects user to be returned, but null is returned which is what it should. 

**Steps to reproduce the behavior**
From frontend client, try to get "me" query with GraphQL

**Expected behavior**
I expect the graphql to return null, with an error to the frontend client.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```
