### ISSUE TITLE
Unexpected behavior observed with <date> field on posting to database

### ISSUE THREAD

**Issue by andrewchung** [strapi/strapi#5749]
**Describe the bug**

The value posted to the database is not the same as what is entered into the \<date\> field when adding a new (or saving an existing) record.

Specific issues:
<ol>
<li>Entering in a date of *April 8, 2020* will be posted as *April 7, 2020* in the database.</li>
<li>If the date is not modified in the edit screen, any subsequent *saving* of the data will cause the posted date to go back by one day.  e.g. in issue#1 above, April 7 will turn into April 6, etc... </li>
</ol>

**Steps to reproduce the behavior**
<ol>
<li>Create a DATE field in a collection</li>
<li>Add a new record and populate the DATE field</li>
<li>Save the record</li>
<li>See error (date will go back by one day)</li>
<li>Go back to the record and go into edit mode</li>
<li>Press *save* without modifying anything</li>
<li>See error (date will go back by another day)</li>
</ol>

**Expected behavior**

Date value posted in the database should be exactly the same as what was entered into the \<date\> field initially.

**System**
- Node.js version: 13.3.0
- NPM version: 6.13.2
- Strapi version: 3.0.0-beta.19.3
- Database: sqlite
- Operating system: MacOSx

**Comment by derrickmehaffy** [comment]
Likely an issue with conversion of dates between timezones, saving is converting back to UTC, but fetching is not.

@andrewchung what timezone are you in?

**Comment by andrewchung** [comment]
@derrickmehaffy EDT, UTC-4

**Comment by alexandrebodin** [comment]
Hi, the dates are persisted as UTC dates so they are standardized. If you want to display them in your timezone you can simply use a utility for it.
This is done to make API consumption agnostic to your specific timezone.

I’m closing this issue as it is intended.

**Comment by alexandrebodin** [comment]
Hi @andrewchung  ater another review. I actually think there is an issue with the way the Strapi client is sending the data to the backend. We should convert it to UTC but using your locale. 

I'm reopening this. FYI, if you use the API you will need to still convert this to the right locale if needed.
