### ISSUE TITLE
Related data is not show in input type content-type view

### ISSUE THREAD

**Issue by Yobikap** [strapi/strapi#575]
**Node.js version**:
8.1.0
**npm version**:
5.6.0
**Strapi version**:
v3@alpha.9
**Operating system**:
Distributor ID: elementary
Description: elementary OS 0.4.1 Loki
Release: 0.4.1
Codename: loki

**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
When trying to save a content-type that has relation, the related is saved to database but not shown in content-type with the already chosen value.
**If the current behavior is a bug, please provide the steps to reproduce the problem**
`{
  "connection": "default",
  "collectionName": "countries",
  "info": {
    "name": "countries",
    "description": ""
  },
  "attributes": {
    "country name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "country numeric code": {
      "type": "integer",
      "required": true,
      "unique": true
    },
    "country isd code": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "country alpha 2 code": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "cities": {
      "collection": "cities",
      "via": "Country name"
    }
  }
}`

`{
  "connection": "default",
  "collectionName": "cities",
  "info": {
    "name": "cities",
    "description": "citieslist"
  },
  "attributes": {
    "city name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "area locations": {
      "collection": "arealocation",
      "via": "city name"
    },
    "status": {
      "type": "boolean"
    },
    "Country name": {
      "model": "countries"
    }
  }
}
`
**What is the expected behavior?**
That the related data is saved and shown in the inputfield

I am using MongoDB

**Comment by storm1er** [comment]
Same problem : 

**Content types :**
- Account
- Line
- Tag
- User

**Relations :**
- Account to many lines
- Account to one user
- Line to one account
- Line to many tags
- Tag to one user
- Tag to many lines
- User to many account
- User to many tag

**Step to reproduce :**
1. Create an account linked to an user
2. Create a line linked to an account
3. Creation a tag linked to an user
4. Go to the line created in 2., then assign the tag create in 3.
5. Go to the tag or the line from 2 or 3, relation doesn't appear.

**Comment by lauriejim** [comment]
@Yobikap CAn you give me your `arealocation` model please.
@storm1er Can you give me a .zip of you models please (easier to try to help you to reproduce your bug)

**Comment by Yobikap** [comment]
@lauriejim 

This is my arealocation model:

```
{
  "connection": "default",
  "collectionName": "arealocation",
  "info": {
    "name": "areaLocation",
    "description": "area location for cities"
  },
  "options": {
    "hasTimestamps": true
  },
  "attributes": {
    "area location name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "status": {
      "type": "boolean"
    },
    "city name": {
      "model": "cities"
    }
  }
}

```

**Comment by storm1er** [comment]
@lauriejim The problem disappeared since release 10.1, on the same models.

**Comment by lauriejim** [comment]
@Yobikap I have reproduce your model, then play with content manager and don't have any problems.
Can you tell me steps to reproduce your issue please

**Comment by Yobikap** [comment]
I have upgraded to the last version alpha 10.1

See the screencast how to reproduce the problem
[Screencast from 2018-02-26 17.26.18.webm.zip](https://github.com/strapi/strapi/files/1759428/Screencast.from.2018-02-26.17.26.18.webm.zip)

**Comment by lauriejim** [comment]
Okay thank you for this video, it's really clear now. 
I think it's come from the type of the relation.

**Comment by Yobikap** [comment]
How can I solve this?

**Comment by lauriejim** [comment]
I don't know right now, I have to investigate on it.

**Comment by mnlbox** [comment]
I can confirm that I have same problem. :disappointed:

**Comment by lauriejim** [comment]
Work on alpha.12.1.3 since the work we did on relations stabilization.
