### ISSUE TITLE
PUT generates error 404

### ISSUE THREAD

**Issue by inverleighdigital** [strapi/strapi#5751]
**Describe the bug**

In Strapi 19.5 and 19.4 Dev environment we are unable to submit PUT requests without generating an error.  When I roll back to 19.3 put requests work fine. 

**Steps to reproduce the behavior**
1. submit a simple unauthenticated put request via postman:

https://myapi.com/myendpoint/5e8e9dd3fb6cd54caca09b6d

{
        "status": "Checked"
    }

2. Response is:

{"statusCode":404,"error":"Not Found","message":"entry.notFound"}

**Expected behavior**
PUT requests succeeds.

**System**
- Node.js version: 
V12.0.0
- NPM version: 6.14.2
- Strapi version:  19.5 and 19.4
- Database: Mongodb
- Operating system:
Ubuntu
**Additional context**

**Comment by derrickmehaffy** [comment]
We need more information, when you get a 404 generally it means that endpoint doesn't exist, so it's most likely not a bug but a change in your application.

**Comment by inverleighdigital** [comment]
Its very strange in that all put request work fine in 19.3 but when we upgraded to 19.5 the put request stopped working and generated an error.  Roll back and it works again.
This is across more than one content type.

**Comment by inverleighdigital** [comment]
PUT and POST requests still work fine.

**Comment by derrickmehaffy** [comment]
Is your project code somewhere public like a Github repo that you can share? This will almost be impossible to reproduce without looking at your specific project.

**Comment by inverleighdigital** [comment]
Understand. Its not public. I can provide the model and request privately if required?

**Comment by derrickmehaffy** [comment]
Yes, if you are on the Strapi Slack you can PM me directly `@DMehaffy (Not Strapi Employee)`

**Comment by inverleighdigital** [comment]
OK

**Comment by rmaroun** [comment]
I have the same issue the put returns

`{"statusCode":404,"error":"Not Found","message":"entry.notFound"}`

Have you been able to solve this?

**Comment by rmaroun** [comment]
Rolling back to 19.3

> We need more information, when you get a 404 generally it means that endpoint doesn't exist, so it's most likely not a bug but a change in your application.

@derrickmehaffy the response is coming back from strapi with the following json

`{"statusCode":404,"error":"Not Found","message":"entry.notFound"}`

**Comment by derrickmehaffy** [comment]
Seems the issue is only on Mongo due to a find one failing at objectID lookup.

**Comment by inverleighdigital** [comment]
I did a cleanup as per Derricks instructions  and confirm  issue is with 19.5 an 19.4 but not with 19.3. One of our devs saw an issue with '_id' not matching agree that the issues are most likely related
 related

**Comment by derrickmehaffy** [comment]
@alexandrebodin this will likely need a hotfix

**Comment by alexandrebodin** [comment]
Hi, I havent' been able to reproduce on any of thoses versions. (We have automated tests that test PUT requests with all the DBs with basic cases and none are failing right now :/)

Can you please share one of the models.json files that fails so i can investigate ?

**Comment by alexandrebodin** [comment]
FYI, if this fails on custom controllers you will need to make sure the findOne is not called with ctx.params but with `({ id: ctx.params.id })`  This fix might be the problem you are having with custom controllers https://github.com/strapi/strapi/pull/5452

**Comment by rmaroun** [comment]
@alexandrebodin I am using `ctx.params._id` and then findOne({ _id: xxxx }). Are you saying I should replace _id by id even with mongo? thanks

**Comment by inverleighdigital** [comment]
@alexandrebodin  I have provided  models.json to @derrickmehaffy . We are not using any  custom controllers

**Comment by derrickmehaffy** [comment]
> @alexandrebodin I am using `ctx.params._id` and then `findOne({ _id: xxxx })`. Are you saying I should replace _id by id even with mongo? thanks

Yes you should because this is translated by mongoose in the connector. Beyond that you should be using id everywhere

**Comment by derrickmehaffy** [comment]
Wondering if this relates to old data from previous versions missing an `id` field before it was fixed a while back.

**Comment by inverleighdigital** [comment]
That's a good point of investigation I will check the raw mongodb  data.

**Comment by alexandrebodin** [comment]
The queries support using `_id` so no problems here. Even though it is supported I would recommend you keep the id to be as agnostic as possible ;)

**Comment by inverleighdigital** [comment]
@alexandrebodin anything else you suggest we check?  anything else we can provide to assist in troubleshooting?

**Comment by alexandrebodin** [comment]
@petersg83 will investigate this issue, as it might be related to a PR we made in beta.19.4 but at first glance I don't see want could be the issue and cannot reproduce.

**Comment by derrickmehaffy** [comment]
Thanks to @petersg83 finding the issue

```
    {
      "method": "PUT",
      "path": "/assets/:_id",   <---- Change to :id 
      "handler": "Asset.update",
      "config": {
        "policies": []
      }
```

**Comment by rmaroun** [comment]
This seems to be the issue and moved all _id to id and all is now working fine when moving from 19.3 to 19.5

**Comment by petersg83** [comment]
Thank everybody for your help. I'm glad it works fine for you!
I added a migration guide :)

**Comment by inverleighdigital** [comment]
Yes confirmed also that this has fixed the issue for us.

**Comment by zernonia** [comment]
I'm using strapi "3.1.3" and still facing the similar issue. POST with the same api endpoint has no trouble, but with PUT. 

PUT https://mysite.my/profiles/5f3406b23721b5290973e33f
```
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "entry.notFound"
}
```

**Comment by derrickmehaffy** [comment]
@zernonia can you open up a github discussion so we can talk about your specific usecase. Thank you!

**Comment by Boytobeaman** [comment]
In my  service, I use Promise.all().then(),
it will throw 404 for my put route,

Then I change Promise.all().then() to await Promise.all()
It works fine now
but logically Promise.all().then() should work the same with await Promise.all()

**Comment by petersg83** [comment]
It's not really the same actually. `Promise.all().then() `will be run asynchronously and the javascript engine will continue to execute the code after. If there is no more code after, it hits the `return` statement and the response to the request is sent. However your asynchronous code hasn't been executed and the response is, I guess, empty: thus 404.
By doing an `await`, the javascript engine wait for the `promise.all()` to be executed before hitting the return statement.
Your can also return the promise itself `return Promise.all().then()`.

**Comment by Boytobeaman** [comment]
> It's not really the same actually. `Promise.all().then() `will be run asynchronously and the javascript engine will continue to execute the code after. If there is no more code after, it hits the `return` statement and the response to the request is sent. However your asynchronous code hasn't been executed and the response is, I guess, empty: thus 404.
> By doing an `await`, the javascript engine wait for the `promise.all()` to be executed before hitting the return statement.
> Your can also return the promise itself `return Promise.all().then()`.

Hi You are right, Thanks
