### ISSUE TITLE
Enable SSL using certbot and nginx

### ISSUE THREAD

**Issue by juliensl** [strapi/strapi#5760]
Hello the Strapi community ! 

**Describe the bug**
I am strying to set httpS on my Strapi production but it is very difficult O.O
I followed the tutorial written by @derrickmehaffy  https://medium.com/@derrickmehaffy/using-strapi-in-production-with-https-717af82d1445 , but it does not work for me :'( 

My pm2 service : 
![strapi_pm2](https://user-images.githubusercontent.com/43228020/78975542-9a821480-7b14-11ea-8b4e-b8242f523f15.png)

My /etc/nginx/conf.d/upstream.conf file : 
```
# Strapi upstream server
upstream strapi-gatsby {
    server localhost:1337;
}
```

My /etc/nginx/sites-available/strapi.live-for-good.org.conf file : 
```
server {
# Listen HTTP
    listen 80;
    server_name strapi.live-for-good.org;
# Define LE Location
    location ~ ^/.well-known/acme-challenge/ {
      default_type "text/plain";
      root         /var/www/html;
    }
# Else Redirect to HTTPS // API
#    location / {
#      return 301 https://$host$request_uri;
#    }
}
```

I cleared the **default** package in `sites-available` and `sites-enabled`, made the link, and when I wanted to check it with `service nginx configtest`, it fails :cry: 

But, when I launch `sudo nginx -t && sudo service nginx reload`, I got this : 
```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

So, this is my nginx.conf : 
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
```

**System**
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database: mongoDB on MLab
- Operating system: ubuntu 18.04

I think that it could be very nice to explain how it works in the documentation, I tryied to understand but there are too much tutorials on google and the 3 links in the SSL documentation part looks like to do the same thing but not exactly :/ 

Thank you for your help :smiley:

**Comment by derrickmehaffy** [comment]
Closing this as it's not an issue with Strapi. Generally I don't recommend you directly exit the /etc/nginx/nginx.conf file which is what you are doing here.

**Comment by derrickmehaffy** [comment]
I plan on adding actual documentation for nginx (there is an Open PR I'm working on)

**Comment by juliensl** [comment]
Youpss... I did not know that the nginx.conf file was delicate :/ 

You are right, it's not an issue sorry, I use github too much ><
I will post my message in stackoverflow :) 

Have a good day, and sorry for the trouble.

**Comment by derrickmehaffy** [comment]
No problem @juliensl do feel free to poke me on slack also and I can try to assist a bit more directly.
