### ISSUE TITLE
Feedback on 3.0.0-next.49

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#5761]
Hi,
As suggested by @soupette I put my feedback in this issue instead of the PR https://github.com/strapi/strapi/pull/5750 so the PR can be merged and the feedback not forgotten :)

Very nice work, congrats to all the team! :)

Few things I saw:

1. I couldn't upload a big file (a video of 700mb), even though I increased the sizeLimit value in the config
1. When I upload a big file (a video of 700mb), it doesn't work because it's too big, and I receive a 500 error instead of a nice error. In admin, it displays "Internal error".
2. When I put a bad url, the asset is displayed (with a broken image but still displayed), and when I click on "Upload 1 asset to the library", it displays "bad request" under the asset. (I would expect an error "Those URLs are not valid : [urls]").
3. When I select an asset, all the assets move a bit to the bottom, I wasn't expecting that. (because it adds the text "X assets selected" (or something like that) above the table)
4. When I change to another page, there is a spinner on all the page, even the title disappears. It feels like a glitch. Is it possible to put the spinner only on the table part of the page? Or put a skeleton? So the title stays static.
5. Depending on if the page is full of assets or not, the navigation buttons are not at the same place. I went to the last page and wanted to come back to the previous page, it felt annoying for me to move the mouse on where the buttons went to click on "<". (One solution is to put the navigation buttons above the table. I not a big fan of this solution but it works).
6. When I upload many assets, the scroll seems broken on firefox.
![Capture d’écran 2020-04-09 à 14 43 25](https://user-images.githubusercontent.com/11708220/78896271-81c02300-7a70-11ea-8ca0-d718a28948af.png)
7. When I upload many assets and that it takes time, I can click on "add more assets". Should this button be disabled once I click on "upload X assets" ?
8. When I have many assets in my media lib and I display them 50/page, I scroll at the end of the page, click on next page, then I am on the next page but in the middle of it. Not at the bottom (like I was when I clicked on next page), neither at the top, but in the middle

Otherwise, very nice work, it's way better now :)

**Comment by derrickmehaffy** [comment]
Tagging @JelmerV-WFC

**Comment by derrickmehaffy** [comment]
I agree, this is a good place for feedback, I'm currently testing and making a list myself (along with noting any issues on migrations and updating versions per @alexandrebodin )

**Comment by derrickmehaffy** [comment]
@alexandrebodin I test again and could not duplicate the previous issues I had with SQL migrations, seemed to be my system was having a bad day :shrug:

@soupette / Frontend Team
I did test and confirm the issues that @petersg83 mentioned. Will continue to test to see if I notice any other odd issues.

**Comment by JabStrapi** [comment]
Thank you for all the feedback. We have fixed the most annoying issues for the first version of the feature. We will add the rest of your feedbacks with the one from the rest of the community to continue improving the feature in the future.

**Comment by alexandrebodin** [comment]
Thank you guys for the comments. I'm closing the issue to avoid having too many feedback channels. We are keeping all this on our side for improvements. You can of course add some stuff here of needed ;)
