### ISSUE TITLE
Required fields when components error on MongoDB

### ISSUE THREAD

**Issue by Tansito** [strapi/strapi#5762]
**Describe the bug**
If you have a component (repeatable or simple) in a collection and you try to populate an empty field that you changed to required the validation doesn't let you modify it because it says:
```
ValidationError: project validation failed: fieldOfScience: Path `fieldOfScience` is required.
```

The only case that the collection updates correctly is when you have an empty simple component or no components at all but if you have:
- A populated simple component
- An empty repeatable component
- A populated repeatable component

I suppose that with an empty simple component works because you are sending a **null** in this case in the POST.

**Steps to reproduce the behavior**
1. The collection must have a no populated field that is not required and a repeatable component. For example, in this case **abstract** is not required:
![Screen Shot 2020-04-15 at 12 48 19 PM](https://user-images.githubusercontent.com/9059044/79329079-6db86d80-7f17-11ea-8a81-9a8d91d6e4c8.png)
2. Create a new entry:
![Screen Shot 2020-04-15 at 12 51 19 PM](https://user-images.githubusercontent.com/9059044/79329299-d43d8b80-7f17-11ea-966f-1593b893ef3f.png)
3. Now change the **abstract** field of the collection to required:
![Screen Shot 2020-04-15 at 12 52 09 PM](https://user-images.githubusercontent.com/9059044/79329373-fb945880-7f17-11ea-9c2f-b04882db6f0a.png)
4. Go to that collection, try to populate the **abstract** field and see the error:
![Screen Shot 2020-04-15 at 12 53 49 PM](https://user-images.githubusercontent.com/9059044/79329514-3ac2a980-7f18-11ea-92c8-6e42210666ca.png)

**Expected behavior**
It should update the collection like when you don't have the component in the collection.

**System**
- Node.js version: v13.12.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.19.5
- Database: MongoDB
- Operating system: MacOS Catalina 10.15.3

**Comment by lauriejim** [comment]
Hello! I'm not sure to follow your explanation.
Can you precise the exact steps to reproduce, because with the current one I'm not sure of what I have to do.
Thank you.

**Comment by Tansito** [comment]
Hi @lauriejim , sorry I tried to be clearer adding some images and clarifying some steps. Let me know if you need something more. Just to clairy if I wasn't this behavior happens for:
- A populated simple component
- An empty repeatable component
- A populated repeatable component

But not for:
- A no populated simple component

And from my understand it should work in every case (like when you don't have a component or the simple component is no populated)

**Comment by Tansito** [comment]
Any news about this?

**Comment by lauriejim** [comment]
Hello! Here is what I did by following your step by step - https://www.loom.com/share/0d813e13a9be4f72a3a4ee13c0117406

**Comment by Tansito** [comment]
Thanks @lauriejim , I saw that you were using in the test Postgres and I tested the same with that database and it worked. After that I did the same steps with a new project but changing the database for mongo and I could reproduce the error.

**Comment by lauriejim** [comment]
I will close this issue because it's related to this topic - https://github.com/strapi/strapi/issues/6292
You already have data created, you switch required to true and the constrain doesn't match the data created.
