### ISSUE TITLE
When ctx.status=304, ctx.body will be null. Then "TypeError: Cannot read property 'isBoom' of null"

### ISSUE THREAD

**Issue by Balabili** [strapi/strapi#5764]
**Describe the bug**
I write a custom controller. 

`
demo: async ctx => {
  ctx.send('Text', 304);
}
`

The lib/middlewares/boom/index.js code:

`
        ctx.status = ctx.body.isBoom ? ctx.body.output.statusCode : ctx.status; 
        ctx.body = ctx.body.isBoom ? ctx.body.output.payload : ctx.body;
`

When ctx.status change to 304, Koa will change ctx.body to null.
Then  ctx.body.isBoom will throw an error.

**System**
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.17.5
- Database:
- Operating system:

**Additional context**

**Comment by alexandrebodin** [comment]
Hi, this was changed in recent version of strapi. 
If you still endup having this issue in beta.19.5 let us know.

I’ll close the issue in the meantime
