### ISSUE TITLE
Retry webhook requests if error happens

### ISSUE THREAD

**Issue by Jolg42** [strapi/strapi#5767]
**Please describe your feature request:**

So I looked into the webhook implementation after asking @pierreburgy on a zoom meetup and it looks like it's quite basic, only one try is done when an event is received:
https://github.com/strapi/strapi/blob/master/packages/strapi/lib/services/webhook-runner.js#L77-L113

The problem with this approach is that it happens quite often that a webhook destination fails for many reasons like temporary downtime / maintenance.

An easy solution would be to use [p-retry](https://github.com/sindresorhus/p-retry) and retry a few times.

Example from p-retry README:
```js
const pRetry = require('p-retry');
const fetch = require('node-fetch');

const run = async () => {
	const response = await fetch('https://sindresorhus.com/unicorn');

	// Abort retrying if the resource doesn't exist
	if (response.status === 404) {
		throw new pRetry.AbortError(response.statusText);
	}

	return response.blob();
};

(async () => {
	console.log(await pRetry(run, {retries: 5}));
})();
```

More complicated solutions from https://zapier.com/engineering/webhook-design/
- Create a DB queue: When you send webhooks inline, all your code is in one place. With this option, you’ll be creating a record in your existing database for each notification you need to send. Rather than initiating a connection immediately, you’ll need a separate process to frequently look for new notifications and send them. Since the end user isn’t waiting, timeouts are not as big of a concern. And if you need to retry a notification, just keep it marked active until it succeeds or is called the maximum number of times.
- Use a proper queue: If you know you’ll need to scale your solution, use a tool specifically designed for that. You can use open source scalable queueing solutions like RabbitMQ or a service like Amazon Simple Queuing Service. This way, your interaction is limited to adding and removing “messages,” which tell you what webhooks to call. Like the DB queue, you need a separate process to consume items from the queue and send notifications. In addition to using a tool designed for this purpose, a proper queue also saves database resources for what it does best–providing data to your primary application.

**Comment by lauriejim** [comment]
Hello @Jolg42 !
Thank you for sharing this idea.
Can you please open an RCF in this repo [strapi/rfcs](https://github.com/strapi/rfcs) this will be the right place to discuss the implementation of this.

**Comment by Jolg42** [comment]
Sorry, I just checked the RFC repo, your process is too time consuming / complicated in my opinion for such a small suggestion and this issue has everything already 🙃

**Comment by derrickmehaffy** [comment]
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/retry-webhook-requests-if-error-happens
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!
