### ISSUE TITLE
Component fields are missing in API response

### ISSUE THREAD

**Issue by stefba** [strapi/strapi#5769]
**Describe the bug**

Component fields are missing in API response (if their types are referenced by a relation).

**Steps to reproduce the behavior**

1. Create `piece` type:
```
title Text
info Component
    material Text
    color Text
```
2. Create a single `selection` type:
```
entry Component (repeatable)
    piece Relation with *piece* (Selection has one Piece)
```
3. Create pieces and a selection of these pieces.
4. Go to `http://localhost:1337/selection`.

**Expected behavior**

I expect to get a list of pieces on `/selection`. A selection is returned, but the pieces have no `info` field. Only their title is returned. `/pieces`, on the other hand, works fine and as expected, with the `info` field included in the response.

**System**
- Node.js version: v12.16.2
- NPM version: 6.14.4 
- Strapi version: 3.0.0-beta.19.5
- Database: Sqlite
- Operating system: Debian

**Comment by lauriejim** [comment]
Hello @stefba ! Thank you for reporting this.
By default, we are limiting the number of relations we populate by default.
You should receive the `info: ID` normally, I will confirm that with the tech team.
To be able to get more date, you will have to customize your controller function.
**Path —** `api/selection/controllers/selection.js`
```js
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  async find(ctx) {
    const entry = await strapi.services.selection.find(['entry', 'entry.piece', 'entry.piece.info']);
    return entry;
  },
};
```

**Comment by lauriejim** [comment]
*This message is to help for the tech team*

This is the response we have:

```json
{
    "id": 1,
    "created_at": "2020-04-15T14:27:49.890Z",
    "updated_at": "2020-04-15T14:27:49.890Z",
    "entry": [
        {
            "id": 1,
            "piece": {
                "id": 1,
                "title": "P1",
                "created_at": "2020-04-15T14:27:10.358Z",
                "updated_at": "2020-04-15T14:27:10.358Z"
            }
        },
        {
            "id": 2,
            "piece": {
                "id": 2,
                "title": "P2",
                "created_at": "2020-04-15T14:27:17.757Z",
                "updated_at": "2020-04-15T14:27:17.757Z"
            }
        }
    ]
}
```

I think the key `info` is missing. We should have it with the `ID` of the compo.
BUT we can't get a compo entry with it's `ID`
SO should we populate, in any cases, component values?

**Comment by stefba** [comment]
Thank you for you response!

I couldn’t make the controller function work. I already wrote a function that joins the two queries (`/pieces` and `/selection`), so I will maybe look into this later.

From a users perspective, it feels odd that a key doesn’t show up in the response at all, with no notification whatsoever. But I don’t know what complexities would come with it to populate the component values or even the id.

Thank you for your work.
