### ISSUE TITLE
Focus conflict between 2 inputs in "new component to the dynamic zone"

### ISSUE THREAD

**Issue by thollander** [strapi/strapi#5771]
**Describe the bug**
When creating a new component in a `Dynamic Zone`, there is a minor bug : the focus is not well managed between the name of the component and the input for searching icons. 

**Steps to reproduce the behavior**
1. Go to **Plugins** > **Content Types Builder**
2. Choose a *collection*
3. Add a new *dynamic zone* field on it
4. Click on *Add a component*
5. Click on *Create a new component*
6. Click on the magnifying glass for searching icons
7. Type in the `Name` field
8. You should see that after one keyup, the focus goes to the input for searching icons

**Expected behavior**
The focus should stay on the input `Name` when we type in it. 

**Screenshots**
![bugStrapi3](https://user-images.githubusercontent.com/23191482/79064980-87567c80-7cad-11ea-9914-b5350c5f9790.gif)

**System**
- Strapi version: `v3.0.0-beta.19.5`
- Operating system: OS X

**Comment by lauriejim** [comment]
Hello @thollander !
Thank you for reporting this issue.
If you close the search bar by clicking on the `x` it will work well.
