### ISSUE TITLE
Plugin documentation missing OperationId field

### ISSUE THREAD

**Issue by Erim32** [strapi/strapi#5773]
Hello,
after many tries to contribute but unsuccessful installation of the fork (sql3 issue). I post this basic feature request because I can't code it myself. 

I noticed strapi-documentation doesn't generate the OpenApi OperationId field used by many services to name every operation. Check [OpenApi Documentation](https://swagger.io/docs/specification/paths-and-operations/)

I tag @alexandrebodin because he looks very involved on this plugin.

- **Note**
OperationId  must be unique for a same URL.

- **Reflexion/Suggestion**
If I can do a recommendation, that will be a good thing to name generated OperationId with the name of the default method created. For exemple :  
      
      "method": "GET"
      "path": "/categories"
      "handler": "Category.find"
      "handler": "Category.find"
      "operationId": "find",

      "method": "GET",
      "path": "/categories/count",
      "handler": "Category.count",
      "operationId": "count",

      "method": "GET",
      "path": "/categories/:id",
      "handler": "Category.findOne",
      "operationId": "findOne",
     
      "method": "POST",
      "path": "/categories",
      "handler": "Category.create",
      "operationId": "create",
    
      "method": "PUT",
      "path": "/categories/:id",
      "handler": "Category.update",
      "operationId": "update",
      
      "method": "DELETE",
      "path": "/categories/:id",
      "handler": "Category.delete",
      "operationId": "delete",

- **Example of usage :**
{
  "routes": [
    {
      "method": "GET",
      "path": "/categories",
      "handler": "Category.find",
      **"operationId": "find",**
      "config": {
        "policies": []
      }
    },

- **Steps:**
- [ ] **Add facultative field "operationId" in generated config/routes.json files.**
Reference to this file [link](https://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/json/routes.json.js)
- [ ] **Load "operationId" field for documentation generaiton**
Need to edit this object : [Link](https://github.com/strapi/strapi/blob/da9340ead23f6ef8d810b031c51d784f913f87a5/packages/strapi-plugin-documentation/services/Documentation.js#L467)
- [ ] **Add explicit OperationId for others plugins (upload, permissions ... )**
- [ ] **Create an error message if operationId is not unique**

I hope you can add this very soon,
Thx for your work

**Comment by derrickmehaffy** [comment]
It would probably be easier to just strip off the controller name instead of adding another field (users and permissions does this already as well)

**Comment by Erim32** [comment]
Hi @derrickmehaffy, that can be the default value indeed, but I suggest adding a facultative value to routes.json for custom services / operations (not expose functions names).

**Comment by derrickmehaffy** [comment]
> Hi @derrickmehaffy, that can be the default value indeed, but I suggest adding a facultative value to routes.json for custom services / operations (not expose functions names). 

Is there some security risk that I'm seeing with regards to function names? As for custom I can't see a use-case where you would reuse a controller function with the same name on multiple routes? Thus if you want to build a custom function it would simply use that.

**Comment by Erim32** [comment]
You right ( @derrickmehaffy ) 👍

**Comment by MarkusWendorf** [comment]
Hello there,

I was trying to use Strapi with https://github.com/contiamo/restful-react#code-generation-from-openapi--swagger-specs
And noticed the missing operationId in the documentation plugin.

There's https://github.com/strapi/strapi/pull/6023 but the work on this PR halted.
So I played around with the documentation api a little to make my use case work.

**Goal**: generate unique & ledgible ids (specifically for code generation)

#### The operationId for APIs (generateApiDocumentation) use controllerMethod + controllerName:
```
const operationId = _.upperFirst(controllerMethod) + _.upperFirst(controllerName);
```
Example: **FindOneQuestion**

#### For plugins (generatePluginDocumentation) use endPoint:
```
const segments = endPoint.replace(/[{}*]/g, '').split(/[\/-]/);
const operationId = segments.map(_.upperFirst).join("") + verb.toUpperCase();
```
Example for endpoint /auth/{provider}/callback: **AuthProviderCallbackGET**
The http verb at the end doesn't look to good for code generation but is required to make it unique.

Testing for my use case:
```
npx restful-react import --file full_documentation.json --output my-awesome-generated-types.tsx
```
For example, generated hooks: useFindOneQuestion & useAuthProviderCallbackGET

(will output error if there's a duplicate, goal: generated API is somewhat legible)

There could be a problem with the uniqueness of the operationId for APIs (as noted in the PR above), but I'm not sure if it really is a problem in practice.

What do you think?

**Comment by emilieringwald** [comment]
Hello! We planned to work on the documentation plugin soon, our team will keep you posted shortly :)

**Comment by derrickmehaffy** [comment]
see: https://feedback.strapi.io/developer-experience/p/plugin-documentation-missing-operationid-field
