### ISSUE TITLE
Production build: Stored images corrupted on every rebuild

### ISSUE THREAD

**Issue by omar-enrique** [strapi/strapi#5774]
First off, Happy Easter everyone!

**Describe the bug**
My Strapi project is deployed on Heroku right now, connected to a MongoDB Cloud Atlas where I store my data. My MongoDB holds a blog collection, and each blog post has a featured image. 

Whenever the Heroku server cycles and restarts the Strapi app, the image is corrupted, and is no longer viewable. The URL is still returned but there is no image at that URL.  This behavior does not occur on the development version of Strapi on my local host.  Even when I restart Strapi, image storage persists.

**Steps to reproduce the behavior**
When make a new blog post, everything is properly stored as a document in my blog collection. Everything except for the image of course, which seems to be stored on the Strapi server, with a URL to that image passed back when I request it.

**Expected behavior**
As far as I am aware, Strapi is functioning just as expected in the production build. Considering that Strapi offers an Image file field that you can store in a database entry, I would assume that Strapi is supposed to be able to handle image storage.  Is this correct? Otherwise, should I be uploading images to an external image hosting site (like imgbb or imgur) and storing the URL to that image?

**System**
Node.js version: v10.15.3
yarn version: 1.22.0
Strapi version: 3.0.0-beta.18.8
Database: MongoDB
Production version is hosted on Heroku

**Additional context**

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

**Comment by derrickmehaffy** [comment]
Images are not stored in the database (as not all of the databases support this) they are stored on the filesystem (Which that FAQ explains) you will need to use an upload provider like AWS-S3, Cloudinary, ect
