### ISSUE TITLE
CONTENT MANAGER is not working

### ISSUE THREAD

**Issue by hzrcan** [strapi/strapi#5776]
**Content manger is not working**
I don't see the content manager when I log into the dashboard. See that it is installed.

I am currently using version 3.0.0-beta.19.5.

Strapi helper plugin and strapi plugin content manager "are both installed.

Downgrading has not helped either.

Anyone have any idea why it doesn't work?

**Steps to reproduce the behavior**
1. Go to /dashboard or /admin
2. Login and create collections
3. See menu items left, no ‘Content manager’

**Expected behavior**
I expect a link to ‘Content manager’ and a working Content manager.

**System**
- Node.js version: v10.16.0
- NPM version: 6.14.3
- Strapi version: 3.0.0-beta.19.5.
- Database: postgreSQL
- Operating system: OSX

**Comment by christianguevara** [comment]
1. Use latest beta
1. Maybe you mean the  collection type builder ? And are you trying to use it in production mode? [Check this](https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#frequently-asked-questions)
1. Did you tried in a blank project ?
1. Any customization to any proxy ?

You are not using the bug report template. This issue is probably to be closed.

**Comment by hzrcan** [comment]
@christianguevara 

1. I’m using the latest beta > 3.0.0-beta.19.5
2. No, I mean the content manager
3. Yes this is a blank project, there is no menu item to ‘Content manager’. The package is installed
4. No customization with proxy

**Comment by christianguevara** [comment]
Yes latest beta is 19.5, my bad.
You are not attaching any errors in the strapi console or browser, difficult to think about a solution.

I'm ALMOST sure, you are following a Udemy course with an old Strapi version.

**Comment by hzrcan** [comment]
It’s not going about any collection, but about the plugin ‘Content manager’.  And I didn’t follow any tutorial via Udemy.

I did it from the official guide of Strapi.

Look below, the Content manager plugin is not here. And there is no any error in the console.

![F7342FF9-F571-4E3E-8A04-43FA1BA73C71](https://user-images.githubusercontent.com/3510239/79083951-85360180-7d31-11ea-81c2-be39c018dc56.jpeg)

**Comment by christianguevara** [comment]
To edit data you need to click the collection type as is shown in my screenshot.

**Comment by christianguevara** [comment]
It is not clear what you want to do, I can't understand.

**Comment by hzrcan** [comment]
> It is not clear what you want to do, I can't understand.

It’s not difficult, but you don’t want to understand :) 

The plugin content manager is not showing?
This is the whole issue.

I shared screenshots, and explained very clear.

**Comment by derrickmehaffy** [comment]
The "content manager" menu link was removed, it was merged into the content type builder a while ago, and more than likely the two plugins will merge into one in the future. You access the CTM through the views (list/edit) or via the content type builder.

@hzrcan I would caution you never to tell anyone here to "be quiet".

Im locking this thread as it has gotten too heated over a simple issue of semantics.
