### ISSUE TITLE
Be able to set null for date input

### ISSUE THREAD

**Issue by locopati** [strapi/strapi#5777]
**Describe the bug**
I want to clear the date that was set on a field

**Steps to reproduce the behavior**
1. Create a type with a date field that is not required
2. Create an instance of the type with a value in the date field and save it
3. Edit the instance and clear the date field
4. It cannot be cleared
5. Make a GraphQL request to clear the field
6. The request errors

**Expected behavior**
You can clear the field in the UI
The GraphQL mutation works

**Code snippets**
```
mutation UnsetDate($id: ID!) {
  updateYourType(input:{
    where:{
      id: $id
    },
    data: {
      date_field: null
    }
  }) {
    your_type { 
      id
      date_field
    }
  }
}
```

This returns `"message": "Expected type Date, found \"\"; Date cannot represent an invalid date-string ."`

**System**
- Node.js version: 13.7
- Yarn version: 1.22
- Strapi version: 3b19.5
- Database: Mongo 4.2.5
- Operating system: Arch Linux 4.19-97

**Additional context**

**Comment by derrickmehaffy** [comment]
Node.js version: 13.7

You are on an unsupported node version, please test on node 12/10.

**Comment by lauriejim** [comment]
Thank you @locopati for reporting this issue.
This is due to the format validation. Can you please investigate it and submit a PR to allow `null`
Thank you.

**Comment by richardgrey** [comment]
I think this works now, so the issue could be closed.

**Comment by lauriejim** [comment]
This error still exist with MongDB.

**Comment by weidox** [comment]
Just encountered same issue, don't know if that's DB related though we're using MongoDB.

**Comment by luisjuniorj** [comment]
This error still exist with PostgreSQL.

**Comment by rmonnier9** [comment]
I get the same error with PostgreSQL as well.

**Comment by arturaum** [comment]
> This error still exist with PostgreSQL.

Any changes?

**Comment by lauriejim** [comment]
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/new-release-strapi-v3-1-7/256/1

**Comment by hieucd04** [comment]
Ran into this issue today.

- Node: 12.18.3
- Strapi: 3.2.4
- Database: SQLite
- OS: Windows 10 Pro

**Comment by smoothdvd** [comment]
This issue will be fired when you POST formData.

Content type has a non-required field, which type is 'date'.

```
Error: Invalid format, expected an ISO compatible date
    at parseDate (/Users/alexgao/Dev/find-missing-people/node_modules/strapi-utils/lib/parse-type.js:37:11)
    at parseType (/Users/alexgao/Dev/find-missing-people/node_modules/strapi-utils/lib/parse-type.js:89:14)
    at /Users/alexgao/Dev/find-missing-people/node_modules/strapi-connector-bookshelf/lib/parser.js:12:14
    at /Users/alexgao/Dev/find-missing-people/node_modules/strapi-connector-bookshelf/lib/mount-models.js:463:25
    at Array.map (<anonymous>)
    at mapper (/Users/alexgao/Dev/find-missing-people/node_modules/strapi-connector-bookshelf/lib/mount-models.js:460:29)
    at Child.<anonymous> (/Users/alexgao/Dev/find-missing-people/node_modules/strapi-connector-bookshelf/lib/mount-models.js:619:63)
    at /Users/alexgao/Dev/find-missing-people/node_modules/bookshelf/lib/base/events.js:101:64
From previous event:
    at Child.triggerThen (/Users/alexgao/Dev/find-missing-people/node_modules/bookshelf/lib/base/events.js:101:20)
    at Child.<anonymous> (/Users/alexgao/Dev/find-missing-people/node_modules/bookshelf/lib/model.js:1152:23)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Child.<anonymous> (/Users/alexgao/Dev/find-missing-people/node_modules/bookshelf/lib/model.js:1060:10)
From previous event:
    at runCreate (/Users/alexgao/Dev/find-missing-people/node_modules/strapi-connector-bookshelf/lib/queries.js:113:45)
    at /Users/alexgao/Dev/find-missing-people/node_modules/strapi-connector-bookshelf/lib/queries.js:53:34
    at /Users/alexgao/Dev/find-missing-people/node_modules/knex/lib/transaction.js:183:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-05-13T06:59:20.415Z] debug POST /missing-person-notices (42 ms) 500
```

**Comment by MuizU** [comment]
Did anyone find a workaround in postresql

**Comment by crazyfree** [comment]
today I got same problem. 
There is existing data in the database for exam `delivery_date` = `2023-10-06 00:00:00.000000`. 
I use API to set it to null so I do set `delivery_date` = null. 
All other fields get updated but `delivery_date` stay unchanged

**Comment by mootensai** [comment]
I think this issue should still opened because we still couldn't set date input to null by `null` value

**Comment by luisjuniorj** [comment]
Thats why i moved on... How many years to set a field to null?

Em sex., 6 de out. de 2023 05:44, Yohanes Candrajaya <
***@***.***> escreveu:

**Comment by amh092** [comment]
Im facing the same issue has anybody solved it ?
