### ISSUE TITLE
How to create dropdown list in the form created by content Content Type Builder? Please help 

### ISSUE THREAD

**Issue by gurjantsingh7979** [strapi/strapi#578]
**Node.js version**:

**npm version**:

**Strapi version**:

**Operating system**:

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by soupette** [comment]
Hi @gurjantsingh7979 could you be more specific?

**Comment by gurjantsingh7979** [comment]
Hi Soupette,

Let us say I have created a template to register a doctor, now I would like to give the option in the same registration template to select the hospital(from the list of hospitals i.e. dropdown hospitals list) to which he is associated.  Hope this is clarifying the requirements.

**Comment by derrickmehaffy** [comment]
@gurjantsingh7979 The value type your looking for is enumeration, it is supported from what I can tell on the cli side but not on the admin side. See my issue here: https://github.com/strapi/strapi/issues/566

enumeration (enum) is a categorical variable IE a set hospital.

**Comment by soupette** [comment]
Hi @gurjantsingh7979 if you want the enumeration you have  enumeration you can manually create it in your model as follows:

```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "product",
    "description": ""
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "type": {
      "type": "enumeration",
      "enum": ["val1", "val2", "val3"],
      "required": true
    }
  }
}
```
