### ISSUE TITLE
how to add Search functionality in the content type?

### ISSUE THREAD

**Issue by gurjantsingh7979** [strapi/strapi#579]
**Node.js version**:

**npm version**:

**Strapi version**:

**Operating system**:

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by soupette** [comment]
Could you be more specific? Can you update your issue using the template so I can have a clear idea of your request.

Thanks!

**Comment by derrickmehaffy** [comment]
@soupette I believe what @gurjantsingh7979 is looking for is a search function on the Content Manager. 

![image](https://user-images.githubusercontent.com/8593673/35861801-9239a3e0-0b06-11e8-961a-084affcd3982.png)

Something that would allow you to search the data to return results matching the query.

**Comment by gurjantsingh7979** [comment]
Right @derrickmehaffy.

**Comment by soupette** [comment]
In order to add search functionnality you have to first start your project in  `dev mode` [see the CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md).

Once your project is in dev mode you have to add the `InputSearchWithErrors` component to the `List`container which is located in `my-project/plugins/content-manager/admin/src/containers/List/index.js`.

You have to create an action, a saga and update the reducer
**Path —** `my-project/plugins/content-manager/admin/src/containers/List/constants.js`
```
export const ON_CHANGE = ''content-manager/app/List/ON_CHANGE';
export const SEARCH_SUCCESS = ''content-manager/app/List/SEARCH_SUCCES';
```
**Path —** `my-project/plugins/content-manager/admin/src/containers/List/actions.js`
```
import { ON_CHANGE, SEARCH_SUCCESS } from './constants';

export function onChange({ target }) {
  return {
    type: ON_CHANGE,
    keys: target.name.split('.'),
    value: target.value,
  };
}

export function searchSuccess(data) {
  return {
    type: SEARCH_SUCCESS,
    data,
  }
}
```

Now you have to fire the saga to get the data from your backend
**Path —** `my-project/plugins/content-manager/admin/src/containers/List/sagas.js`

```
// Import your constant so the saga is listening to the event
import { ON_CHANGE } from './constants';
import { searchSuccess } from './actions';


// The function to get your data
export function* search(action) {
  try {
    const requestUrl = `something/search/${action.value}`;
    const data = yield call(request, requestUrl, { method: 'GET' });

    yield put(searchSucccess(data));
    
  } catch(err) {
    console.log(err);
  }
}

// register your saga
export function* defaultSaga() {
  // ...
  yield fork(takeLatest, ON_CHANGE, search);

  // ...
}
```


Then pass your data to the reducer

**Path —** `my-project/plugins/content-manager/admin/src/containers/List/reducer.js`
```
import {
  // ...,
  ON_CHANGE,
  SEARCH_SUCCESS,
} from './constants';

const initialState = fromJS({
  currentModel: false,
  currentModelName: false,
  currentModelNamePluralized: false,
  loadingRecords: true,
  records: [],
  loadingCount: true,
  count: false,
  currentPage: 1,
  limit: 10,
  sort: 'id',
  initLimit: 10,
  initSort: 'id',
  // ADD THIS LINE
  value: '',
});

function listReducer(state = initialState, action) {
  switch (action.type) {
   // ...
    case ON_CHANGE:
       return state.updateIn(action.keys, () => action.value);
    case SEARCH_SUCCESS:
       return state.set('records',  action.data);
    default:
      return state;
  }
}

````

Create the selector:

**Path —** `my-project/plugins/content-manager/admin/src/containers/List/selectors.js`

```
const makeSelectValue = () =>
  createSelector(selectListDomain(), substate => substate.get('value'));

export { 
  // ...
  makeSelectValue,
};
```

I thinking of something like this in the index.js
```
import { InputSearchWithErrors as Input } from 'components/InputsIndex';
import {
  // ...
  onChange,
} from './actions';

// Selectors.
import {
 // ...
  makeSelectValue
} from './selectors';
// Other imports

export class List extends React.Component {
   // ...
   render() {
     // ...
     return (
       <div>
        <div className={`container-fluid ${styles.containerFluid}`}>
          <PluginHeader
            title={{
              id: pluginHeaderTitle,
            }}
            description={{
              id: this.props.count > 1 ? 'content-manager.containers.List.pluginHeaderDescription' : 'content-manager.containers.List.pluginHeaderDescription.singular',
              values: {
                label: this.props.count,
              },
            }}
            actions={pluginHeaderActions}
          />

          {/* ADD THE INPUT HERE */ }
          <Input
              onChange={this.props.onChange}
              value={this.props.value}
               name="value"
          />

          <div className={`row ${styles.row}`}>
            <div className='col-lg-12'>
              {content}
              <PopUpWarning
                isOpen={this.state.showWarning}
                toggleModal={this.toggleModalWarning}
                content={{
                  title: 'content-manager.popUpWarning.title',
                  message: 'content-manager.popUpWarning.bodyMessage.contentType.delete',
                  cancel: 'content-manager.popUpWarning.button.cancel',
                  confirm: 'content-manager.popUpWarning.button.confirm',
                }}
                popUpWarningType={'danger'}
                onConfirm={this.handleDelete}
              />
              <TableFooter
                limit={this.props.limit}
                currentPage={this.props.currentPage}
                onChangePage={this.handleChangePage}
                count={this.props.count}
                className="push-lg-right"
                onChangeLimit={this.handleChangeLimit}
              />
            </div>
          </div>
        </div>
      </div>
     );
   }
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators(
    {
      deleteRecord,
      setCurrentModelName,
      loadRecords,
      loadCount,
      changePage,
      changeSort,
      changeLimit,
      onChange,
    },
    dispatch
  );
}

const mapStateToProps = createStructuredSelector({
  records: makeSelectRecords(),
  count: makeSelectCount(),
  loadingCount: makeSelectLoadingCount(),
  models: makeSelectModels(),
  currentPage: makeSelectCurrentPage(),
  limit: makeSelectLimit(),
  sort: makeSelectSort(),
  currentModelName: makeSelectCurrentModelName(),
  currentModelNamePluralized: makeSelectCurrentModelNamePluralized(),
  schema: makeSelectSchema(),
  value: makeSelectValue(),
});

// ...
```

If you're struggling please see [the users-permissions plugin](https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-users-permissions/admin/src/containers/EditPage);

and the [InputSearchWithErrors documentation](https://github.com/strapi/strapi/blob/master/docs/3.x.x/en/plugin-development/ui-components.md#inputsearchwitherrors)

**Comment by soupette** [comment]
I'm closing the issue feel free to reopen it if needed.

**Comment by derrickmehaffy** [comment]
@soupette I'm curious to know if features like this are planned to be integrated into the Default Strapi interface instead of added manually for each user?

**Comment by soupette** [comment]
Yes but it's not our main priority..
However this functionality can be a plugin developed by a member. 
I wan to emphasize the fact that it can be a plugin since a plugin can inject some component into another using the `injectedComponents.js` file.

See the [documentation](https://strapi.io/documentation/plugin-development/frontend-use-cases.html#inject-design) to find more about it.

**Comment by derrickmehaffy** [comment]
That makes sense, just wanted to clarify the use case as I have not seen any references to it previously.

Thank you.

**Comment by gurjantsingh7979** [comment]
Thanks @soupette @derrickmehaffy for helping. I did all the changes mentioned by @soupette , but did not work. What I am looking is highlighted in the screenshot. please me to accomplish this.
  
![screen shot 2018-02-13 at 11 42 59 am](https://user-images.githubusercontent.com/20162939/36135907-d7f4457c-10b3-11e8-9fe8-e7525fa97dc5.png)

Thanks,

**Comment by gurjantsingh7979** [comment]
@soupette I think I have no git permissions to open this issue again, so please open this issue.

**Comment by soupette** [comment]
Well the solution I gave you is for the front end part you also need to create the `/search` in your apis.

So in the `content-manager` plugin create a `/search` route and its associated controller. You'll have to create the queries in the `my-project/plugins/content-manager/config/queries` also.

You can take a look at this https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/UsersPermissions.js to help you. In this file you'll see `searchUsers` function that does what you want to achieve.

**Comment by derrickmehaffy** [comment]
No problem, looks good. I am wanting to do something similar with my API so would be great to take a look at what you have done.
