### ISSUE TITLE
Missing colon in Input component styles

### ISSUE THREAD

**Issue by ierehon1905** [strapi/strapi#5790]
Style definitions contain a syntax error.

 ### Steps to reproduce:
go to
https://github.com/strapi/strapi/blob/5c06f723301c1e6b1c495b14dba289b9ca3faff8/packages/strapi-admin/admin/src/components/Inputs/Wrapper.js#L18

### Path
`/packages/strapi-admin/admin/src/components/Inputs/Wrapper.js`
### Expected
`width: 50%;`

### Actual
`width 50%;`

### Screenshot
<img width="1010" alt="screen" src="https://user-images.githubusercontent.com/31146334/79228781-b2d29600-7e6a-11ea-8726-e7a82f03b064.png">

**Comment by derrickmehaffy** [comment]
@ierehon1905 can you submit a pull request

**Comment by ierehon1905** [comment]
@derrickmehaffy  Yes, I will make changes and submit asap

**Comment by ierehon1905** [comment]
@derrickmehaffy I fixed a few other typos
