### ISSUE TITLE
Fetching data from Strapi API throws GraphQL Error: Invalid Token

### ISSUE THREAD

**Issue by lsliwaradioluz** [strapi/strapi#5799]
**Describe the bug**
I've set up a new Strapi project and connected it to my Nuxt.js app. While trying to fetch data from the Strapi API, I get an error GraphQL error: Invalid token. The same Nuxt app can fetch data from another Strapi backend (version 3.0.0-beta.18.7) just fine. On the other hand, another Nuxt app can't fetch data from my new Strapi API either. So I guess the problem lies in the new Strapi app. 

I've configured everything like I did in that previous Strapi app (3.0.0-beta.18.7). The GraphQL playground works fine, I can query my data successfully. Any hints on why this happens? Same problem was mentioned on Strapi's Slack channel by a user named @glimow, he hasn't started a new issue however (at least I haven't found it).

**Steps to reproduce the behavior**
1. Create new Strapi project (3.0.0-beta.19.5)
2. Connect it to MongoDB Atlas database (free tier) 
3. Create new content type "programs" with field name. 
4. Create new program with name "whatever"
5. Create new nuxt project via npx create-nuxt-app <app-name>
6. Install GraphQL and nuxt-apollo to query data from Strapi 
7.  Query for programs using nuxt-apollo 

**Expected behavior**
data from Strapi is fetched into nuxt app successfully 

**Screenshots**

https://www.loom.com/share/24f6a785c04b481d821aba29a243feb5

**System**
- Strapi version: (3.0.0-beta.19.5)
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Can you please log the request headers and see if you are sending a JWT to a public route (as in the route has public pemrissions but no authenticated permissions).

If that is the case it's working as intended, as there may be cases where you want to force public routes only and sending any authorization header (valid or not) is not a public request.

**Comment by lsliwaradioluz** [comment]
I've found the bug which was dumb. The token of the older app was still stored in my cookies under default name and got loaded for the new app as well (since both were running on localhost). Hence the error. Deleting the token from cookies solved my issue. Lesson learned: don't use the default token name in apollo :) 

The issue can be closed, thank you @derrickmehaffy for your suggestion.
