### ISSUE TITLE
how to print the debug, info or error logs in the strapi?

### ISSUE THREAD

**Issue by gurjantsingh7979** [strapi/strapi#580]
**Node.js version**:

**npm version**:

**Strapi version**:

**Operating system**:

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by Yobikap** [comment]
you can use:

`strapi.log.debug("your string or object")`

**Comment by gurjantsingh7979** [comment]
Thanks Yobikap for reply, can you please let me know where it will store the logs?

I am seeing in my project, it has not created any folder with logs name.

**Comment by Yobikap** [comment]
You can put this snippet in your code when developing.

The output should be in your console or terminal.

For logging information see:
https://github.com/strapi/strapi-docs/blob/master/files/logging.md

For file logging, you could use something like pino-multi-stream. Because
strapi.log is based on pino logging, you should be able to implement this.

But I am not sure about it.

**Comment by gurjantsingh7979** [comment]
I have used below given statement, but it has not worked on my side. Please advise.
strapi.log.debug("my object ...");

**Comment by sbastias** [comment]
I tried adding
```
strapi.log.debug("LOOK AT ME!")
```

And got this:

> Uncaught TypeError: Cannot read property 'debug' of undefined

**Comment by nmitra6** [comment]
strapi.log.debug is not working in strapi version: "3.6.5"

**Comment by nmitra6** [comment]
even though initial startup time was less, I am wasting hell lot of a time even for small customization. It's future is bleak if you put hurdles at every step and very shady documentations, describing very little. Probably it's only good for blogs. Feels worst than a Chinese product

**Comment by tayrotayro** [comment]
So I have the logs printing in the terminal, ("strapi.log.info, strapi.log.warn, straip.log.error"), but does anyone have a solution on how to print those logs to a log file?

**Comment by derrickmehaffy** [comment]
> So I have the logs printing in the terminal, ("strapi.log.info, strapi.log.warn, straip.log.error"), but does anyone have a solution on how to print those logs to a log file?

Use a service manager like PM2, which will automatically keep a log file of the stdout from Strapi

**Comment by forntoh** [comment]
> So I have the logs printing in the terminal, ("strapi.log.info, strapi.log.warn, straip.log.error"), but does anyone have a solution on how to print those logs to a log file?

Where are the logs printed, I don't see it in my terminal. I only see the HTTP requests logs

**Comment by dtokarczyk** [comment]
> > So I have the logs printing in the terminal, ("strapi.log.info, strapi.log.warn, straip.log.error"), but does anyone have a solution on how to print those logs to a log file?
> 
> Where are the logs printed, I don't see it in my terminal. I only see the HTTP requests logs

Exacly, I'm trying to debug something but I don't see anything in the console.

**Comment by vonbarnekowa** [comment]
any solution?

**Comment by alicanso** [comment]
strapi.log is not working for me as well. why this issue has been closed? is there any solution?

**Comment by psparsa** [comment]
The code within the `bootstrap.ts` file doesn't run at all. I used the `strapi.log.debug` function in `src/index.ts`, and it works fine.

`index.ts:`
```ts
export default {
  bootstrap() {
    strapi.log.debug("Hello World!");
  },
};
```

my strapi version: `4.6.0`

reference:
https://docs.strapi.io/dev-docs/configurations/functions

**Comment by adrianoresende** [comment]
Why is this issue closed if we don't have a solution? @lauriejim

**Comment by IskanVa** [comment]
Any info how to fix it ?
