### ISSUE TITLE
Overriding User controller ctx bypassing is("multipart")

### ISSUE THREAD

**Issue by fadhilx** [strapi/strapi#5800]
**Describe the bug**
i tried to override the create controller function for user-permission on `extensions\users-permissions\controllers\User.js`

**Steps to reproduce the behavior**
1. Create 'extensions\users-permissions\controllers\User.js'
2. write this codes
```js
"use strict";
const { parseMultipartData, sanitizeEntity } = require("strapi-utils");

/**
 * Read the documentation (https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#core-controllers)
 * to customize this controller
 */

module.exports = {
  create: async function (ctx) {
    let entity;
    let controller = strapi.plugins["users-permissions"].controllers.user;
    let model = strapi.plugins["users-permissions"].models.user;
    console.log(ctx);
    if (ctx.is("multipart")) { // <--- its bypassed here
      const { data, files } = parseMultipartData(ctx);
      entity = await controller.create(data, { files });
    } else {
      entity = await controller.create(ctx.request.body);
    }
    return sanitizeEntity(entity, { model });
  },
};
```
3. try create user on admin(browser) 
4. You wil have 400 error saying that `ctx.request.body` should have `data` key, But it dont have multipart

**Expected behavior**
`ctx.is("multipart")` should not be truthy, or `ctx.request.body` should have `data` key, so it not have that 400 error

**Screenshots**
400 error saying that `ctx.request.body` should have `data` key, But it dont have multipart
![image](https://user-images.githubusercontent.com/15516786/79315069-2214bc80-7f35-11ea-9ff8-ed33b54f26ce.png)
here is the payload sent
![image](https://user-images.githubusercontent.com/15516786/79315606-c26ae100-7f35-11ea-987e-da77ec84d2fa.png)
here is the header:
![image](https://user-images.githubusercontent.com/15516786/79315727-efb78f00-7f35-11ea-9d2a-16a09b17d3b5.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.15.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.5
- Database: mongodb
- Operating system: Windows 10

**Comment by lauriejim** [comment]
Hello @fadhilx .
Here you are in a controller and you are calling the controller.create.
You are calling the controller you are currently updating.
So you have to call the service instead.
