### ISSUE TITLE
findOne is Always returning the last entry.

### ISSUE THREAD

**Issue by bogdancrisu** [strapi/strapi#581]
**Node.js version**:
9.5.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.9

**Operating system**:
OSX

So after reading about something that is happening to me, more exactly Issue #395, I tried again by creating a new Strapi app with alpha.9 that as far as I know, it contains the commit 519239c witch supposed to be a fix, the same problem can be found. From my investigations this part `.findOne(_.pick(params, _.keys(<%= globalID %>.schema.path)))` more exactly `_.pick(params, _.keys(<%= globalID %>.schema.path))`  is returning an empty array. In order to continue with my project I changed the line to `.findOne({"_id": params._id })`.

**Comment by lauriejim** [comment]
Can you be more precise please.
You create a new content type via the content type builder ?
And then using the generated routes you can't get a specific entry ?

**Comment by mukeshmaurya91** [comment]
@bogdancrisu  i'm also stuck in same problem. And after doing some research found that (*. schema.path) is wrong and this must be  (*.schema.paths). 
@lauriejim  Please fix this issue asap. Thanks

**Comment by bogdancrisu** [comment]
@lauriejim So after creating the route via content type builder, I'm unable to fetch the right item via the route/:id, is always returning the last entry that the collection has.

**Comment by lauriejim** [comment]
Hi @bogdancrisu and @mukeshmaurya91 please update to the last version of Strapi.

**Comment by T-Zahil** [comment]
Same probleme here, and I use the latest version.

`{
      "method": "GET",
      "path": "/product/:category/:id",
      "handler": "Product.findOneByCategory",
    },`

This route always return the last entry.

**Comment by lauriejim** [comment]
@T-Zahil Can you please open a new issue, following the issue template.
