### ISSUE TITLE
afterCreate function fired before insert query

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#5812]
**Describe the bug**
i want to update a record after created but cant find that
its happen in afterSave function too
**Steps to reproduce the behavior**
uncomment afterCreate function
```javascript
afterCreate: async (model, attrs, options) => {
    const { attributes } = model;
    const { id } = attributes;
    const res = await strapi.query('comment').findOne({ id: id })
    console.log(res); // null
}
```
**System**
- Node.js version: v12
- NPM version: v6
- Strapi version: v19.03
- Database: mysql
- Operating system: ubuntu18.04

**Additional context**

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1443
