### ISSUE TITLE
Changing field case with MySQL crashes: ER_DUP_FIELDNAME

### ISSUE THREAD

**Issue by artlogic** [strapi/strapi#5818]
**Describe the bug**
Changing the case of a field when using MySQL causes strapi to crash and fail to restart.

**Steps to reproduce the behavior**
1. Start with a new install.
2. Create a new collection type.
3. Add one field to it: `test`
4. Save.
5. Edit the field and change the name to `Test`.
6. Save
7. Strapi crashes: `error Error: ER_DUP_FIELDNAME: Duplicate column name 'Test'`

**Expected behavior**
I would not expect a crash.

**Code snippets**

Here's the entire traceback:
```
strapi    | [2020-04-16T06:59:05.277Z] debug ⛔️ Server wasn't able to start properly.
strapi    | [2020-04-16T06:59:05.279Z] error Error: ER_DUP_FIELDNAME: Duplicate column name 'Test'
strapi    |     at Query.Sequence._packetToError (/srv/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
strapi    |     at Query.ErrorPacket (/srv/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
strapi    |     at Protocol._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
strapi    |     at Parser._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
strapi    |     at Parser.write (/srv/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
strapi    |     at Protocol.write (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
strapi    |     at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:88:28)
strapi    |     at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:526:10)
strapi    |     at Socket.emit (events.js:210:5)
strapi    |     at addChunk (_stream_readable.js:308:12)
strapi    |     at readableAddChunk (_stream_readable.js:289:11)
strapi    |     at Socket.Readable.push (_stream_readable.js:223:10)
strapi    |     at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
strapi    |     --------------------
strapi    |     at Protocol._enqueue (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
strapi    |     at Connection.query (/srv/app/node_modules/mysql/lib/Connection.js:198:25)
strapi    |     at /srv/app/node_modules/knex/lib/dialects/mysql/index.js:130:18
strapi    |     at Promise._execute (/srv/app/node_modules/bluebird/js/release/debuggability.js:384:9)
strapi    |     at Promise._resolveFromExecutor (/srv/app/node_modules/bluebird/js/release/promise.js:518:18)
strapi    |     at new Promise (/srv/app/node_modules/bluebird/js/release/promise.js:103:10)
strapi    |     at Client_MySQL._query (/srv/app/node_modules/knex/lib/dialects/mysql/index.js:124:12)
strapi    |     at Client_MySQL.query (/srv/app/node_modules/knex/lib/client.js:158:17)
strapi    |     at Runner.query (/srv/app/node_modules/knex/lib/runner.js:135:36)
strapi    |     at Runner.queryArray (/srv/app/node_modules/knex/lib/runner.js:224:14)
strapi    |     at /srv/app/node_modules/knex/lib/runner.js:37:25
strapi    |     at tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)
strapi    |     at /srv/app/node_modules/bluebird/js/release/using.js:185:26
strapi    |     at tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)
strapi    |     at Promise._settlePromiseFromHandler (/srv/app/node_modules/bluebird/js/release/promise.js:547:31)
strapi    |     at Promise._settlePromise (/srv/app/node_modules/bluebird/js/release/promise.js:604:18)
strapi exited with code 1
```

**System**
- Node.js version: (same as strapi/strapi:latest docker container)
- NPM version: (same as strapi/strapi:latest docker container)
- Strapi version: 3.0.0-beta.19.5
- Database: MySQL
- Operating system: Linux/Docker

**Comment by BraveLilToaster** [comment]
Looks related to #1114. Would love to know if this is being worked on or something that could be contributed to.

**Comment by lauriejim** [comment]
Here is the same issue - https://github.com/strapi/strapi/issues/5941
I'm closing this one.
Thank you for reporting this issue.

**Comment by artlogic** [comment]
@lauriejim Respectfully, I think these are different issues. I'm not really concerned about old fields cluttering up the database. Literally if I change the case of the field, strapi ceases to work (see the above traceback. The key here is this `Duplicate column name 'Test'`.

Some data backends (like MySQL) operate in case-insensitive mode by default, which means changing the case of a field doesn't create a new field in the database. It attempts to create a duplicate field, causing the above crash.

IMO, strapi should be aware of it's backend's case sensitivity and respond appropriately, instead of assuming all backends are case sensitive.

**Comment by lauriejim** [comment]
Hello, I understand your thought.
A global work on the database layering will fix all these topics.
Alex is working on it.
Also related in a sense of this https://github.com/strapi/strapi/issues/1114
Impact of UI actions on the database.
