### ISSUE TITLE
Thumbnails are still created even with alt sizes turned off

### ISSUE THREAD

**Issue by drewtownchi** [strapi/strapi#5830]
**Describe the bug**
The new media manager is creating thumbnail images even with the alt sizes turned off.  When using a provider like Cloudinary this creates unnecessary resources.

**Steps to reproduce the behavior**

1. Turn off alt sizes option in the media manager.
2. Upload an image.
3. See thumbnail image is still created.

**Expected behavior**
Only the original image should be uploaded.

**System**

- Node.js version: 12
- NPM version: 6.14.4
- Strapi version:  3.0.0-beta.20
- Database: Postgres 11
- Operating system: Windows

**Comment by drewtownchi** [comment]
It looks like this is expected behavior. From Slack:

aureliengeorget:strapi:  13 minutes ago
Yes, we need them to display the images in the Media Library and the content manager... otherwise we would have to load the high resolution images. To avoid performances issues we always generate thumbnails

**Comment by ngotrongphuc** [comment]
I found a way to disable thumbnail generation in Strapi v5. Simply add this file at ./src/extensions/upload/strapi-server.ts - it overrides the generateThumbnail method of the Upload plugin. Now thumbnails in the media library will use the original image URL as a fallback.
```ts
export default (plugin) => {
  // Override upload plugin to disable thumbnail generation
  plugin.services['image-manipulation'].generateThumbnail = () => {}
  return plugin
}
```
