### ISSUE TITLE
GraphQL file upload error on Node 13

### ISSUE THREAD

**Issue by remi2j** [strapi/strapi#5831]
**Describe the bug**
When I use the `upload` GraphQL mutation, I get the following error: 

```txt
{"errors":[{"message":"Maximum call stack size exceeded","locations":[{"line":2,"column":3}],"path":["upload"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["RangeError: Maximum call stack size exceeded","    at _openReadFs (internal/fs/streams.js:151:21)","    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)","    at ReadStream.deprecated [as open] (internal/util.js:89:15)","    at ReadStream.open (/Users/remi/Code/enki/back/node_modules/fs-capacitor/lib/index.js:90:11)","    at _openReadFs (internal/fs/streams.js:154:12)","    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)","    at ReadStream.deprecated [as open] (internal/util.js:89:15)","    at ReadStream.open (/Users/remi/Code/enki/back/node_modules/fs-capacitor/lib/index.js:90:11)","    at _openReadFs (internal/fs/streams.js:154:12)","    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)","    at ReadStream.deprecated [as open] (internal/util.js:89:15)","    at ReadStream.open (/Users/remi/Code/enki/back/node_modules/fs-capacitor/lib/index.js:90:11)","    at _openReadFs (internal/fs/streams.js:154:12)","    at ReadStream.<anonymous> (internal/fs/streams.js:147:3)","    at ReadStream.deprecated [as open] (internal/util.js:89:15)","    at ReadStream.open (/Users/remi/Code/enki/back/node_modules/fs-capacitor/lib/index.js:90:11)"]}}}],"data":null}
```

**Steps to reproduce the behavior**

1. Set your Node version to 12
2. Upload a file with the upload mutation
3. It works fine
4. Set your Node version to 13
5. Upload a file with the upload mutation
6. You get the error

**Expected behavior**
I expected the file upload to work on Node 13.

**System**

- Node.js version: 13.12.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.19
- Database: MongoDB
- Operating system: MacOS 10.15.2

**Additional context**

I think I narrowed down the issue. The heart of the problem is that **graphql-upload** didn't support Node 13 until v9 ([see this issue](https://github.com/jaydenseric/graphql-upload/issues/170#issuecomment-561056556), same bug as mine).

I found that Strapi is indirectly using graphql-upload on v8:

```sh
npm ls graphql-upload
```

returns:

```txt
path/to/my/project
└─┬ strapi-plugin-graphql@3.0.0-beta.19
  └─┬ apollo-server-koa@2.9.12
    └─┬ apollo-server-core@2.11.0
      └── graphql-upload@8.1.0
```

This means that Strapi isn't the root of the problem (apollo-server-core has to update its dependency first, then apollo-server-koa). But I'm opening the issue for awareness in case others go through the same loophole.

I don't know if there's another fix possible on Strapi's end. In the meantime, I can either use the REST API for file uploads, or use Node 12.

**Comment by derrickmehaffy** [comment]
Node 13 is not supported (and won't be as it's a development release) Strapi will only ever support the LTS versions of node such as currently Node 10/12 and likely Node 14 went it goes LTS in October. Until then you should be using LTS versions.

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information per the [contributor guidelines for issues](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by ceefour** [comment]
@marcasellkhelaifi please open a new bug as @derrickmehaffy said, and mention this bug too there as history.
