### ISSUE TITLE
strapi-provider-upload-rackspace wont work with latest beta

### ISSUE THREAD

**Issue by abanchev** [strapi/strapi#5832]
**Describe the bug**
The latest beta generates thumbnails which don't have a filename, but just a hash. The rackspace plugin wont be able to upload them as it relies on the filename.

**Steps to reproduce the behavior**

1. Setup rackspace as a provider
2. Try to upload an image

**Expected behavior**
The image should upload along with the thumbnails.

**System**

- Node.js version: 12
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: mysql
- Operating system: linux

**Additional context**
Not sure if the thumbnails should have the name, or if the plugins should use the hash instead.

**Comment by alexandrebodin** [comment]
Hi, Thank you for your feedback. Indeed I see where the error is coming from. Sadly I haven't been able to test the rackspace provider as getting an account takes ages :/. If you are willing to test this and make a PR this would be awesom !! 

You should just be able to replace `file.name` by `file.hash + file.ext`. I am still waiting for the rackspace accoutn validation so as long as I cannot test I will not be pushing a change for now. 

Let me know If you can help ;)

**Comment by abanchev** [comment]
I also don't have an account, I was working on a FTP provider when I noticed that this one wouldn't work because of the issue.

**Comment by alexandrebodin** [comment]
Ok, as soon as I get the access to the rackspace account I'll push a fix.
