### ISSUE TITLE
renaming fields of content types do not copy existing data : add an option to copy as a solution ? 

### ISSUE THREAD

**Issue by remisharrock** [strapi/strapi#5836]
**Describe the bug**
when renaming a field of a content type the response still exists but with the old name

**Steps to reproduce the behavior**

maybe this is related:
steps to reproduce : 
create a content type with a field
add some data
rename the field   // here some options should consider copying existing data to the new name
the data is still in the response but with the old field name

**Expected behavior**
the data should be copied with the new name

**System**

- Node.js version: v13.12.0
- NPM version: 6.14.4
- Strapi version: v3.0.0-beta.20
- Database: mongoDB
- Operating system: windows 10 2004

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1114
