### ISSUE TITLE
modal window disapear if mouse goes out of window during selection

### ISSUE THREAD

**Issue by remisharrock** [strapi/strapi#5837]
**Describe the bug**
when we select something in a modal window, during the selection, if the mouse goes out of the window, the window closes

**Steps to reproduce the behavior**

click inside a modal window and drag the mouse outside the window, it closes.

**Expected behavior**
the window shouldn't close

**System**

- Node.js version: v13.12.0
- NPM version: 6.14.4
- Strapi version: v3.0.0-beta.20
- Database: mongoDB
- Operating system: windows 10 2004

**Comment by soupette** [comment]
@remisharrock we will need more information in order to understand where it happens can you provide a video maybe?

**Comment by remisharrock** [comment]
yes, bien sûr :)
https://partage.imt.fr/index.php/s/76zdwsdZcyWMrzA

**Comment by MattieBelt** [comment]
@remisharrock Are you still holding your mouse click until it closes or did you release it after selecting the text?

**Comment by remisharrock** [comment]
holding my mouse, it closes when I release
