### ISSUE TITLE
Cursor not found error with Sharded Mongo Cluster

### ISSUE THREAD

**Issue by schuylr** [strapi/strapi#5839]
**Describe the bug**

After running Strapi in production for the first time, any subsequent run fails with the error:

```
root@strapi-56cc8894b8-hhv2z:/var/www/apps/strapi# node server.js
[2020-04-17T02:50:17.634Z] error Bootstrap function in plugin "users-permissions" failed
[2020-04-17T02:50:17.637Z] error MongoError: Cursor not found (namespace: 'strapi_production.users-permissions_permission', id: 99938245034687426).
    at Connection.<anonymous> (/var/www/apps/strapi/node_modules/mongodb/lib/core/connection/pool.js:460:61)
    at Connection.emit (events.js:310:20)
    at processMessage (/var/www/apps/strapi/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at Socket.<anonymous> (/var/www/apps/strapi/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Steps to reproduce the behavior**

1. Create a sharded MongoDB cluster (not Atlas or single-node)
2. Create a Strapi project, point to this new cluster
3. Run the project (`yarn develop` is fine)
4. Cancel the run, and run it again

**Expected behavior**

Server runs normally, no errors occur.

**Screenshots**

![image](https://user-images.githubusercontent.com/12628715/79527771-6d62c400-8036-11ea-8c17-a9e905ea4bfa.png)

**Code snippets**

I pinned the issue down to [this line](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L410)

```
const roleCount = await strapi.query('role', 'users-permissions').count();
```

To fix the issue, I placed this line above it, since I already know that the default permissions already exist:

```
return this.updatePermissions();
```

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: Sharded MongoDB Cluster
- Operating system: Ubuntu 14.10

**Comment by schuylr** [comment]
It looks like I'm still having issues related to this Bootstrap function sporadically. All of my Googling points to the problem lying with the query or mongoose itself, but I'm happy to add any additional information to debug the issue.

**Comment by lauriejim** [comment]
Hello! Thank you for this report, related to other issues that use "sharded MongoDB cluster (not Atlas or single-node)"
I ping @alexandrebodin if it can have an impact during the database layer rework.

**Comment by alexandrebodin** [comment]
Hi @schuylr This error usually happens when you fetch too much data with mongo. I don't think a count query should be an issue though. 

This might also come from connectivity issues with your database if you are not in the same region.

**Comment by schuylr** [comment]
@alexandrebodin The database is within the same region as the Strapi instance

**Comment by alexandrebodin** [comment]
Thank you for the answer, Right now I don't have an explanation for this issue. We will need to investigate this more during our next issue fixing sessions.

**Comment by wemod123** [comment]
@schuylr Did you solve this issue later on?

**Comment by schuylr** [comment]
Yes. I had architected my "mongos" instances incorrectly - each mongos instance needs to have its own FQDN for connections and can't be load balanced, because the mongos instances do not share cursors between each other. I'll close this, but I hope that helps.
