### ISSUE TITLE
Error: Cannot wrap non-Error object. When save content type while run with pm2

### ISSUE THREAD

**Issue by JoshuaYang** [strapi/strapi#584]
**Node.js version**:
9.4.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.9.1

**Operating system**:
centos 7

**Do you want to request a *feature* or report a *bug*?**
yes

**What is the current behavior?**
When I run my project with **strapi start**, everything is right;
When I run my project with **pm2 start server.js --name strapi**, the website can open successfully. But when I create a content type and save it, it tells **"Error: Cannot wrap non-Error object"**

**What is the expected behavior?**
Everything go right like I use **strapi start**

**Comment by lauriejim** [comment]
Hello @JoshuaYang.
I tried with `pm2@2.1.5` and `strapi@3.0.0-alpha.10.2` and I have no errors in the terminal.

But if you don't start you project with `strapi start` the auto restart when new content type is created is not available. So if you refresh your page, the content-type is created but not mount in your project.

To use correctly the content-type-builder please launch with `strapi start`.

Let me know if it works fine.

**Comment by simeonackermann** [comment]
An idea might be to start strapi with the [pm2 --watch flag](http://pm2.keymetrics.io/docs/usage/watch-and-restart/l).

**Comment by simeonackermann** [comment]
Ok, I guess the best is to use a simple json config for pm2.

**config.json**
```
{
  "apps" : [
    {
      "name": "appname",
      "script": "strapi",
      "args": "start"
    }
  ]
}
```

And then start with
`pm2 start config.json`

**Comment by ahgood** [comment]
cd strapi_directory
pm2 start server.js
