### ISSUE TITLE
The Content-Type creator cannot generate UID with NON-English language

### ISSUE THREAD

**Issue by turnerguo** [strapi/strapi#5840]
**Describe the bug**
As you can see here, when I type Chinese words here it can not generate a UID for me, and also the UID can't be edited because it is readonly, I think here should be some improves, such as make it editable?
![image](https://user-images.githubusercontent.com/633880/79534768-0ed92c80-80ae-11ea-932a-d6c6bfcc2a26.png)

Tried some other languages...
![image](https://user-images.githubusercontent.com/633880/79535200-57451a00-80af-11ea-9a14-c145525daaec.png)

**Steps to reproduce the behavior**

1. Go to 'Content Types'
2. Click on 'Create a new content type'
3. Then see the results as above screenshot.

**Expected behavior**
It should be a way to make UID possible in any language.

**System**

- Node.js version: Node LTS version (v10.17.0)
- NPM version: v6.0
- Strapi version: 3.0.0-beta.20
- Database: default
- Operating system: macOS 10.15

**Comment by derrickmehaffy** [comment]
`Strapi version: latest version` Please clarify "latest"

**Comment by turnerguo** [comment]
> `Strapi version: latest version` Please clarify "latest"

Yes, I have updated the post.

**Comment by lauriejim** [comment]
Hello! It's the attended thing.
Here is the regexp that validate the UID format - `new RegExp('^[A-Za-z0-9-_.~]*$')`
As you saw in the description of the field, this generated UID is used for many things including routing.
We can't generate all these things with "special characters".
I suggest in general to only use English language for all your development stuff.
