### ISSUE TITLE
Local Media file provider - unable to skip-to-time in uploaded MP4 video/stream chunks

### ISSUE THREAD

**Issue by RichardBosworth** [strapi/strapi#5860]
**Describe the bug**

After uploading an MP4 video (that has been optimised for web streaming by Handbrake.exe) to the local/native Strapi file provider (default with the docker image), the native HTML5 video player is unable to effectively stream the file and will not allow "skipping" to a specific timepoint. The HTML5 video player is pointed to the direct Strapi URL of the media file, as in the GraphQL response.

If the same file is uploaded to a different online file provider and the HTML5 video player is pointed to the direct link, it allows skipping to a timepoint/streaming.

If the same file is uploaded to a Strapi instance using an external provider (such as Amazon S3) and the HTML5 video player is pointed to the direct link, it allows skipping to a timepoint/streaming.

This may be an issue with the way the local Strapi provider handles sending bytes to an HTML5 video client.

**Steps to reproduce the behavior**

1. Upload an MP4 video file (optimised for web streaming - such as in Handbrake) to the Media field of a Content item, using Strapi's local file upload provider.
2. Use the GraphQL API to get the URL for that media field's uploaded file.
3. Make a sample HTML5 web page with a video player, and an MP4 source pointing to the above media URL, ensuring the Video tag has the controls option to allow skipping to a point in the video.
4. Try to skip the video using the controls to a certain point.
5. This should not work.
6. Compare the above with the same file either uploaded to a different location (I used a Nextcloud direct/download file link), or with a Strapi instance with an external provider.
7. Point the webpage video player to that new URL.
8. Time skipping should now work again

**Expected behavior**
You should be able to skip to a point in time in any web-optimised streaming video using Strapi's local provider.

**Screenshots**
Not possible as video.

**Code snippets**
N/A

**System**

The latest Docker container image.

**Comment by christianguevara** [comment]
I did help to test the issue.

I uploaded the same video to S3 bucket and just opened it, it worked with no problem, meaning i were able to go to any point in time in the video.

In the strapi link /uploads/xxxxx.m4v i was not able to do it.

**Comment by abanchev** [comment]
Probably the starpi http server does not support Range requests.

**Comment by lauriejim** [comment]
Hello! Is this issue a duplicate or related to this one https://github.com/strapi/strapi/issues/2246
