### ISSUE TITLE
Migration from 19.5 to 20 breaks authentication providers

### ISSUE THREAD

**Issue by AnthonyPhan** [strapi/strapi#5861]
Hi All,

**Describe the bug**
When attempting to migrate form 3.0.0-beta.19.5 to 3.0.0-beta.20 authentication providers no longer work. In the previous build of our Strapi bac3.0.0-beta.19.5 k end we used Microsoft and google providers successfully. However after migrating to 20 we find that we receive the following error message even when the provider is clearly enabled in the admin center.

`{"statusCode":400,"error":"Bad Request","message":"This provider is disabled.","data":"This provider is disabled."}`

**Steps to reproduce the behavior**

1. Create a project with Strapi 3.0.0-beta.19.5  
2. Enable a third party authentication provider
3. Stop the server
4. upgrade the strapi dependencies in your package.json to 3.0.0-beta.20
5. peform a clean rebuild of your project
6. Attempt to authenticate in your front end applicaiton

**Expected behavior**
The third party authentication provider should redirect to the login page.

**Screenshots**
![image](https://user-images.githubusercontent.com/12785492/79629361-bd976e80-817b-11ea-84ea-4e56c050785a.png)
![image](https://user-images.githubusercontent.com/12785492/79629363-c7b96d00-817b-11ea-8f8f-a6dcc48aa7cf.png)

**System**

- Node.js version: 12.6.0
- NPM version:  6.99.0
- Strapi version: 3.0.0-beta.20
- Database: SQLLite
- Operating system: Windows 10

**Additional context**
Third party authentication providers worked without issue in previous version. Rolling back to 19.5 does resolve the issue.

**Comment by Y2-MosheHarush** [comment]
Are you using ajax for the connect request?

**Comment by nuno-tomas** [comment]
Hello,

New user here, and I'm also facing the issue this issue - Facebook (except that I didn't migrate from previous version, went directly into 3.0.0-beta.20).

![image](https://user-images.githubusercontent.com/20334287/80671449-bfc5cb00-8aa1-11ea-9e22-9b3f6c139d40.png)
![image](https://user-images.githubusercontent.com/20334287/80671475-dff58a00-8aa1-11ea-83ae-0abacc5ceaf7.png)

System
Node.js version: 10.16.0 (lol)
NPM version: 6.9.0
Strapi version: 3.0.0-beta.20
Database: MongoDB
Operating system: Windows 10

BTW: Congrats on the project ;)

**Comment by BeyondSpace609520** [comment]
Hello. I use MongoDB.
I faced same issue too.
In my memory, I did Google auth when I use SQLite.
But it doesn't work when I use MongoDB.
How can I solve this?

**Comment by abhyuday10** [comment]
I am getting the same issue, with Strapi version: 3.0.0-beta.20.1
Anyone have a resolution? I am unable to use any of the auth providers even though they are enabled in the admin panel and database.

**Comment by bamne123** [comment]
Guys any solutions for this? I am also facing same issue. Worst part is I m not able to console log from `Auth.j`s also.

**Comment by bamne123** [comment]
Found error ...

For windows, it is checking `\\` but the requestPath has value `/connect/google`.
Platform check is not needed.

File Path: `strapi-pluging-users-permissions\controllers\Auth.js`
Line Number: `258`

```
const provider =
      process.platform === 'win32' ? requestPath.split('\\')[2] : requestPath.split('/')[2];
```

**Comment by abhyuday10** [comment]
Yup, just found it too. 
Solution, replace line 258 in Auth.js to this
```     const provider =
      process.platform === "win32"
        ? requestPath.split("/")[2]
        : requestPath.split("\\")[2];
```
and put the patched Auth.js in \extensions\users-permissions\controllers to override the default.
