### ISSUE TITLE
The unique option doesn't work with MongoDB

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#5863]
**Describe the bug**

The unique option doesn't work

**Steps to reproduce the behavior**

1. Create a Type with a unique field
2. Create a document with a value in this unique field
3. Create another document with the same value in this unique field

**Expected behavior**

I expect a warning for the unique field, but it creates the document.

**System**

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.0.0-beta.20
- Database: MongoDB
- Operating system: macOS

**Comment by derrickmehaffy** [comment]
Can you give the model settings file @abdonrd

**Comment by abdonrd** [comment]
@derrickmehaffy example:

```json
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "competitions",
  "info": {
    "name": "Competition"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "slug": {
      "type": "uid",
      "targetField": "name",
      "required": true
    },
    "website": {
      "type": "string",
      "unique": true
    },
    "instagram": {
      "type": "string",
      "unique": true
    },
    "twitter": {
      "type": "string",
      "unique": true
    }
  }
}
```

**Comment by derrickmehaffy** [comment]
Hmmmm it certainly should be applying unique here both at the Strapi validation and the database.

**Comment by lauriejim** [comment]
Hello! Thank you for reporting this issue. I think it will come with the validation and database layer I think.
@alexandrebodin will be able to confirm that I think.

**Comment by alexandrebodin** [comment]
Currently Strapi doesn't check unique at validation to avoid perf issues. But the unique indexes are created so you should be getting the errors.

**Comment by abdonrd** [comment]
v4.2.0

> Can you give me your mongoDB version ?

**Comment by alexandrebodin** [comment]
Ok thank you will be tested this asap :)

**Comment by alexandrebodin** [comment]
Hi @abdonrd I haven't been able to reproduce the error with a mongo DB. The unique index is created correctly on my DB. Can you check the indexes exist in your DB ? 
Can you verify the credentials you are using have the right to generate indexes in your mongo db ?

**Comment by abdonrd** [comment]
@alexandrebodin no, I can't see the unique indexes:

<img width="159" alt="Screenshot 2020-05-31 at 09 57 50" src="https://user-images.githubusercontent.com/1007051/83347427-4bdb4480-a325-11ea-9c4f-74f998f097ab.png">

Note: Now I'm already with the Strapi `v3.0.1`.

**Comment by jacargentina** [comment]
I'm using strapi 3.1.4

When I do a POST /thingy with a duplicated index, I'm getting this as a response:

<img width="674" alt="Captura de Pantalla 2020-08-29 a la(s) 13 46 30" src="https://user-images.githubusercontent.com/517228/91642121-1cf56d00-e9ff-11ea-8a87-4516e569d43f.png">

Which on the strap logs is this:

<img width="1490" alt="Captura de Pantalla 2020-08-29 a la(s) 13 55 01" src="https://user-images.githubusercontent.com/517228/91642139-41514980-e9ff-11ea-98fd-071e5dd91f2c.png">


My question is, why I'm not seeing the very same error on the first capture, and just a generic 500 server error?

**Comment by alexandrebodin** [comment]
Hi, Database errors should not be returned in user space. Right now unique constraints are not check on the app level hence we cannot treat them as a Bad request for now.

**Comment by simonwidjaja** [comment]
> > Can you give me your mongoDB version ?
> 
> v4.2.0

same here with current MongoDB Atlas (free plan)

**Comment by noob-master147** [comment]
hey
i'm facing the same issue with docker container of mongo.

when can a fix be expected?

**Comment by derrickmehaffy** [comment]
> hey
> i'm facing the same issue with docker container of mongo.
> 
> when can a fix be expected?

Right now we don't have a timeline but possibly in Q3

**Comment by ChiKaLiO** [comment]
> MongoDB is not supported anymore in Strapi v4, marking as closed

it would be supported in next version no ??

**Comment by derrickmehaffy** [comment]
> > MongoDB is not supported anymore in Strapi v4, marking as closed
> 
> it would be supported in next version no ??

No, we will not maintain a mongodb option anymore, if mongodb themselves create one that's on them but it doesn't apply to us anymore

**Comment by ChiKaLiO** [comment]
> > > MongoDB is not supported anymore in Strapi v4, marking as closed
> > 
> > 
> > it would be supported in next version no ??
> 
> No, we will not maintain a mongodb option anymore, if mongodb themselves create one that's on them but it doesn't apply to us anymore

what about this ? :/ 

https://strapi.io/blog/mongo-db-support-in-strapi-past-present-and-future

**Comment by derrickmehaffy** [comment]
> > > > MongoDB is not supported anymore in Strapi v4, marking as closed
> > > 
> > > 
> > > it would be supported in next version no ??
> > 
> > 
> > No, we will not maintain a mongodb option anymore, if mongodb themselves create one that's on them but it doesn't apply to us anymore
> 
> what about this ? :/
> 
> https://strapi.io/blog/mongo-db-support-in-strapi-past-present-and-future

It's up to mongodb to do their thing, so far since that forum thread we haven't heard from them. They would need to take the lead on it and we would help them but to date we haven't gotten any contact at all.

**Comment by ChiKaLiO** [comment]
hmm :'( Okay thanks <3 and any news about those migration tools  ?

**Comment by derrickmehaffy** [comment]
> hmm :'( Okay thanks <3 and any news about those migration tools ?

We haven't even started working on them and probably won't until the start of January. We have bugs to patch in v4 atm and too many people going on vacation over the next few weeks.

**Comment by ChiKaLiO** [comment]
> > hmm :'( Okay thanks <3 and any news about those migration tools ?
> 
> We haven't even started working on them and probably won't until the start of January. We have bugs to patch in v4 atm and too many people going on vacation over the next few weeks.

so its a sure thing :p ? keep it up
