### ISSUE TITLE
Error connecting to the Mongo database, invalid connection string

### ISSUE THREAD

**Issue by WebTerminator** [strapi/strapi#5865]
**Describe the bug**
I am trying to run a production env locally (after having built my portfolio with this [strapi tuorial](https://strapi.io/blog/strapi-starter-next-js-blog)) to test it before pushing to Heroku.
I have followed [these instructions](https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#mongodb-installation) but when I run `NODE_ENV=production yarn start` within the backend project I get: 

![Screen Shot 2020-04-18 at 13 40 35](https://user-images.githubusercontent.com/4947347/79637861-47ded300-817a-11ea-96f2-50ebf90ac1a4.png)

**Steps to reproduce the behavior**

1. cd backend
2. NODE_ENV=production yarn start

**Expected behavior**
Successful production environment running

**Code snippets**
This is my production database and the variables have been set in heroku as per [these instructions](https://strapi.io/documentation/3.0.0-beta.x/deployment/heroku.html)

```
heroku config:set DATABASE_URI="mongodb://paulbocuse:<password>@strapidatabase-shard-00-00-fxxx6c.mongodb.net:27017,strapidatabase-shard-00-01-fxxxc.mongodb.net:27017,strapidatabase-shard-00-02-fxxxc.mongodb.net:27017/test?ssl=true&replicaSet=strapidatabase-shard-0&authSource=admin&retryWrites=true&w=majority"
heroku config:set DATABASE_NAME="my-database-name"
```

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "mongoose",
      "settings": {
        "uri": "${process.env.DATABASE_URI}",
        "database": "${process.env.DATABASE_NAME}"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**System**

- Node.js version: 10.0.0
- NPM version: 5.6.0
- Strapi version: 3.0.0-alpha.26.2
- Operating system: macOS High Sierra 10.13.6

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-alpha.26.2` Alpha is no longer supported you should update to the beta.

**Comment by WebTerminator** [comment]
@derrickmehaffy that was my global strapi but the one I use for the project is beta as uploaded above. Thanks

**Comment by derrickmehaffy** [comment]
You are mixing different versions of Strapi, this will need to be corrected
