### ISSUE TITLE
AWS S3 upload access denied ACL public-read

### ISSUE THREAD

**Issue by lowki** [strapi/strapi#5868]
**Describe the bug**
When I try to upload a file with AWS S3 upload provider, I have a "denied access" error.

**Steps to reproduce the behavior**

1. Use npm v12.16.1
2. `npx create-strapi-app my-project --quickstart`
3. `cd my-project`
4. `yarn add strapi-provider-upload-aws-s3`
5. Create settings file at extensions/upload/config/settings.json
```json 
{
    "provider": "aws-s3",
    "providerOptions": {
      "accessKeyId": "<accesskeyid>",
      "secretAccessKey": "<secretaccesskey>",
      "region": "eu-west-3",
      "params": {
        "Bucket": "<bucket-name>"
      }
    }
  }
```
6. Go to Media Library in admin panel and upload a file

**Expected behavior**
The file should be uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/1659775/79660408-4af6b500-81b4-11ea-8ac0-9e346b16eef1.png)

![image](https://user-images.githubusercontent.com/1659775/79660606-59dd6780-81b4-11ea-8ca8-2eba151b2936.png)

**System**

- Node.js version: 12.6.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.20
- Database: sqlite
- Operating system: Archlinux

**Additional context**
I've tested my AWS credentials through aws cli to ensure it have access to upload to the bucket.

**Comment by derrickmehaffy** [comment]
Unsure if this is a bug or not so I'll leave it here.

**Comment by lowki** [comment]
It's probably a misconfiguration, but in this case the [documentation](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider) is wrong :)

**Comment by B1Z1** [comment]
Maybe you have missconfiguration, bacause It works in my server

**Comment by lowki** [comment]
Maybe, how can I have a more verbose log?

**Comment by lowki** [comment]
I've just made a successful test in the project, so using the same npm modules.

```js
const fs = require('fs')
const AWS = require('aws-sdk');
const s3 = new AWS.S3({
    region: 'eu-west-3',
    accessKeyId: 'EXAMPLEACCESSKEYID',
    secretAccessKey: 'SECRETEXAMPLEACCESSKEY'
});
 
const fileName = 'test.txt';

const uploadFile = () => {
  fs.readFile(fileName, (err, data) => {
     if (err) throw err;
     const params = {
         Bucket: 'my-bucket-name',
         Key: 'test.txt',
         Body: JSON.stringify(data, null, 2)
     };
     s3.upload(params, function(s3Err, data) {
         if (s3Err) throw s3Err
         console.log(`File uploaded successfully at ${data.Location}`)
     });
  });
};

uploadFile();
```

**Comment by lowki** [comment]
I think I've found someting in the headers of the request.
```
HttpRequest {
  method: 'PUT',
  path: '/backpack_0c14b827a8.png',
  headers: {
    'User-Agent': 'aws-sdk-nodejs/2.658.0 linux/v12.16.1 callback',
    'x-amz-acl': 'public-read',
    'Content-Type': 'image/png',
    'Content-MD5': 'pRQJQ94PQp6z0YhcrrzTRA==',
    'Content-Length': 6120,
    Host: 'my-bucket-name.s3.eu-west-3.amazonaws.com',
    'X-Amz-Content-Sha256': 'UNSIGNED-PAYLOAD',
    'X-Amz-Date': '20200419T144408Z',
    Authorization: 'AWS4-HMAC-SHA256 Credential=##########/20200419/eu-west-3/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-acl;x-amz-content-sha256;x-amz-date, Signature=19d8ca78a640ddf0c7529240d19493928af83680ae9380a1194c5a94165b45c2'
  },
```
The upload tries to specify a public-read acl to the file. My bucket doesn't have a public access, which is what I want, so It throw an access denied error.

I don't know if it's a bug or an expected behavior, but it would be nice to document it :)

**Comment by christianguevara** [comment]
I think you DO need to have public read access, if you don't have it, Strapi would not be able to render the content. Right now, all the uploads are ment to be public.

**Comment by vmarchesin** [comment]
+1 I have a bucket with public read access and get the same error. `aws-cli` works so credentials are correct. Followed the same steps as @lowki.

**Comment by vmarchesin** [comment]
So the `public-read` in the request is indeed the problem. `strapi-provider-upload-aws-s3` has `ACL: 'public-read'` hardcoded, so if your bucket doesn't have public read access it won't work indeed. This is not how that it should work. I have a CDN that serves my bucket files and I don't want the bucket itself to be public. 

So I copied the provider, followed the [steps in the docs ](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#create-providers) and modified it just a little bit. All I had to do is remove the hardcoded property and change the `file.url` that is saved to the DB. Now it stores the image in the bucket but the URL points to the CDN, so everything works as expected. When deleting the file it just needs the `Key` so it deletes correctly as well.

Strapi renders the content fine because the URL it is using is the CDN, not the bucket.

```js
const AWS = require('aws-sdk');

module.exports = {
  init(providerOptions) {
    const s3 = new AWS.S3({
      accessKeyId: providerOptions.accessKeyId,
      secretAccessKey: providerOptions.secretAccessKey,
    });
    const Bucket = providerOptions.params.Bucket;

    return {
      upload(file, customParams = {}) {
        return new Promise((resolve, reject) => {
          const Key = `${file.hash}${file.ext}`;
          s3.upload(
            {
              Key,
              Body: Buffer.from(file.buffer, 'binary'),
              // ACL: 'public-read', // don't use this
              ContentType: file.mime,
              Bucket,
              ...customParams,
            },
            (err, data) => {
              if (err) return reject(err);
              // set the file url to the CDN instead of the bucket itself
              file.url = `https://myCDNurl/${Key}`;
              resolve();
            }
          );
        });
      },
      delete(file, customParams = {}) {
        return new Promise((resolve, reject) => {
          s3.deleteObject(
            {
              Key: `${file.hash}${file.ext}`,
              Bucket,
              ...customParams,
            },
            (err, data) => {
              if (err) return reject(err);
              resolve();
            }
          );
        });
      },
    };
  },
};
```

This should be changed. Enforcing `public-read` should not be done.

**Comment by lauriejim** [comment]
Hello! Here is a video I made about this, maybe it can help.
https://www.youtube.com/watch?v=vrLmZCOTj6Y&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=12&t=0s
If you think there is an issue, can you please submit a PR.

**Comment by vmarchesin** [comment]
The solution, in my opinion, would be to remove the `ACL: 'public-read'` property from the s3 call (it can still be passed down using the `customParams` and pass down some extra config for `file.url`. If no custom url is passed it saves the file to the bucket itself, keeping the current behavior. If you pass a custom url it will assign the custom url to the file instead. Something like:
```
if (customParams.customUrl) {
  file.url = `${customParams.customUrl}/${Key}`
} else {
  file.url = data.Location // current behavior
}
```
This would allow for a custom CDN to be used instead of the bucket, just like in my example above.

Only thing I didn't figure is where those `customParams` are coming from, I didn't have time to dig deeper.

**Comment by z82n** [comment]
I'm having the same issue and have been going at it for the last dozen hours.

Is there a particular list of permissions required from aws ? 

I have a vanilla strapi instance, a public s3 bucket as per @lauriejim 's video and a user with the following policy attached

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucketname",
                "arn:aws:s3:::mybucketname/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}
`

**Comment by z82n** [comment]
Also no success registering a new provider, and the only way I got upload to s3 working locally is by commenting out _within **node_modules**_

`ACL: 'public-read'`

like pointed out by @vmarchesin

**Comment by lauriejim** [comment]
Hello! Can you please submit a PR with the right way to manage that.
Can you also write a great PR body to help for the review.
We will need to make sure it's also well documented in the readme of the provider.
Thank you!

**Comment by creslinux** [comment]
I ran into this, to add my two-pence worth, insisting an S3 bucket be made public to operate is wrong.

Its not unusual for buckets be only presented behind authenticated gateways, s3 proxies, or even internal stack for caching caching and of course CDNs.

By default asking to put all media directly on the web and public, even media not associated to any mode/slug is overly opinionated of use.

**Comment by alex88** [comment]
In my case I get an error even with a public bucket:

This is my plugins config:

```
module.exports = {
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_ACCESS_SECRET,
      region: process.env.AWS_REGION,
      params: {
        Bucket: process.env.AWS_UPLOADS_BUCKET,
      },
    },
  }
};
```

those keys have this policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutAnalyticsConfiguration",
                "s3:GetObjectVersionTagging",
                "s3:CreateBucket",
                "s3:ReplicateObject",
                "s3:GetObjectAcl",
                "s3:GetBucketObjectLockConfiguration",
                "s3:DeleteBucketWebsite",
                "s3:PutLifecycleConfiguration",
                "s3:GetObjectVersionAcl",
                "s3:DeleteObject",
                "s3:GetBucketPolicyStatus",
                "s3:GetObjectRetention",
                "s3:GetBucketWebsite",
                "s3:PutReplicationConfiguration",
                "s3:PutObjectLegalHold",
                "s3:GetObjectLegalHold",
                "s3:GetBucketNotification",
                "s3:PutBucketCORS",
                "s3:GetReplicationConfiguration",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:GetObject",
                "s3:PutBucketNotification",
                "s3:PutBucketLogging",
                "s3:GetAnalyticsConfiguration",
                "s3:PutBucketObjectLockConfiguration",
                "s3:GetObjectVersionForReplication",
                "s3:GetLifecycleConfiguration",
                "s3:GetInventoryConfiguration",
                "s3:GetBucketTagging",
                "s3:PutAccelerateConfiguration",
                "s3:DeleteObjectVersion",
                "s3:GetBucketLogging",
                "s3:ListBucketVersions",
                "s3:RestoreObject",
                "s3:ListBucket",
                "s3:GetAccelerateConfiguration",
                "s3:GetBucketPolicy",
                "s3:PutEncryptionConfiguration",
                "s3:GetEncryptionConfiguration",
                "s3:GetObjectVersionTorrent",
                "s3:AbortMultipartUpload",
                "s3:GetBucketRequestPayment",
                "s3:GetObjectTagging",
                "s3:GetMetricsConfiguration",
                "s3:DeleteBucket",
                "s3:PutBucketVersioning",
                "s3:GetBucketPublicAccessBlock",
                "s3:ListBucketMultipartUploads",
                "s3:PutMetricsConfiguration",
                "s3:GetBucketVersioning",
                "s3:GetBucketAcl",
                "s3:PutInventoryConfiguration",
                "s3:GetObjectTorrent",
                "s3:PutBucketWebsite",
                "s3:PutBucketRequestPayment",
                "s3:PutObjectRetention",
                "s3:GetBucketCORS",
                "s3:GetBucketLocation",
                "s3:ReplicateDelete",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "arn:aws:s3::: bucket-name/*",
                "arn:aws:s3::: bucket-name"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListAccessPoints",
                "s3:HeadBucket"
            ],
            "Resource": "*"
        }
    ]
}
```

however I'm still getting:
```
[2020-07-13T22:05:24.875Z] [2020-07-13t22:05:24.873z] error AccessDenied: Access Denied
    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:831:35)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by codingwithchris** [comment]
I'm having the exact same issue as described multiple times above:

We do not want `public-read` bucket access either. being able to turn this on or off via a config would be ideal:

```
[2020-08-28t16:01:37.332z] error AccessDenied: Access Denied
    at Request.extractError (/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

    at Request.emit (/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by rukyasu** [comment]
Another and a bit cleaner workaround for this is to continue using config in `plugins.js` as usual and just add your desired CDN url as another property. An ability to use environment variables is a nice bonus.

```js
// plugins.js

module.exports = ({ env }) => ({
  upload: {
    provider: "aws-s3",
    providerOptions: {
      accessKeyId: env("AWS_ACCESS_KEY_ID"),
      secretAccessKey: env("AWS_ACCESS_SECRET"),
      region: "eu-central-1",
      params: {
        Bucket: "updown-dev-df1d5f40",
      },
      cdnUrl: env("CDN_URL"), // ADDED PROPERTY
    },
  },
});
```
Don't worry, S3 object will consume it without any issues or conflicts, allowing you to use it in the plugin.

```js
// node_modules/strapi-provider-upload-aws-s3/lib/index.js

...
          S3.upload(
            {
              Key: `${path}${file.hash}${file.ext}`,
              Body: Buffer.from(file.buffer, 'binary'),
              // ACL: 'public-read',
              ContentType: file.mime,
              ...customParams,
            },
            (err, data) => {
              if (err) {
                return reject(err);
              }
              // set the bucket file url
              file.url = S3.config.cdnUrl + data.Key // HERE WE REFER TO THE ADDED PROPERTY IN PLUGINS.JS

              resolve();
            }
          );
...
```

**Comment by capsloq** [comment]
Thank you very much for the solution. The upload works just fine.
However strapi can't read the uplaoded picture since public access is denied. How do you use the IAM user to read the uploaded files on s3 in strapi?

**Comment by rukyasu** [comment]
> Thank you very much for the solution. The upload works just fine.
> However strapi can't read the uplaoded picture since public access is denied. How do you use the IAM user to read the uploaded files on s3 in strapi?

You have to configure public access to your bucket via cloudfront. There are many guides. That's the right way to expose your bucket anyway. Then you'll tell strapi to use cloudfront url for reading.

**Comment by genzdev** [comment]
@rukyasu I am getting this error message: ```error Bootstrap function in plugin "upload" failed
error Error: The provider package isn't installed. Please run `npm install strapi-provider-upload-cms```

This persists despite having run `npm install` multiple times for the custom provider package.

I tried to create a custom provider based on your solution because my change in `node_modules` wouldn't work when deployed via a CICD pipeline & built again.

Any help is much appreciated? (Steps to replicate below)

Steps to replicate:
1. Created a `.providers/strapi-provider-upload-cms` (same as aws-s3 but with custom options)
2. Specified it in package JSON referencing the package to the local dir
3. The `index.js` in `.providers/strapi-provider-upload-cms/lib/` has exact same configuration as your suggested workaround as mentioned here: https://github.com/strapi/strapi/issues/5868#issuecomment-705200530

This is my package json:
```
{
  "name": "my-project",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "ckeditor-build-with-simple-upload-provider-strapi": "^1.0.7",
    "knex": "<0.20.0",
    "sqlite3": "^5.0.0",
    "strapi": "3.4.4",
    "strapi-admin": "3.4.4",
    "strapi-connector-bookshelf": "3.4.4",
    "strapi-connector-mongoose": "^3.4.4",
    "strapi-plugin-content-manager": "3.4.4",
    "strapi-plugin-content-type-builder": "3.4.4",
    "strapi-plugin-email": "3.4.4",
    "strapi-plugin-upload": "3.4.4",
    "strapi-plugin-users-permissions": "3.4.4",
    "strapi-provider-upload-cms": "file:.providers/strapi-provider-upload-cms",
    "strapi-utils": "3.4.1"
  },
  "engines": {
    "node": "12.19.0",
    "npm": "6.14.8"
  }
}
```

Found a similar issue from someone else: https://github.com/strapi/strapi/issues/6228#issuecomment-670537753, not sure if this is the correct diagnosis.

**Comment by genzdev** [comment]
I have resolved the above-mentioned issue(https://github.com/strapi/strapi/issues/5868#issuecomment-767251821), it turned out to be a simple fix.

Reason:
- My customization of the existing `strapi-provider-upload-aws-s3` provider package which I named `strapi-provider-upload-cms` was being referenced as `"strapi-provider-upload-cms": "file:.providers/strapi-provider-upload-cms"` in `package.json.
- Now the referenced local package `strapi-provider-upload-cms` which was inside `.providers/` dir had the following structure: ```
- 
```
.providers/
- strapi-provider-upload-cms/
- - lib/
- - - index.js
- - package.json
```
- Now here, the `index.js` is where all the magic happens, the reason the structure is this way is that my customized provider was a ripoff of the original `strapi-provider-upload-aws-s3` & the `index.js` was referenced correctly (that it was inside `/lib` dir) in their `package.json`.

Solution:
- I simply moved the `index.js` out of the `/lib` dir of my custom provider & voila, it worked.

What can be done better:
- @strapi  can improve the error messaging for the custom providers.

**Comment by gholias** [comment]
I followed the official docs and I'm still getting `error AccessDenied: Access Denied` when I try to upload an image using Strapi.
How can I fix that?

**Comment by callmephilip** [comment]
@gholias check permissions for AWS user you are using to upload files. The following role policy works for me:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::YOUR_BUCKET_NAME_HERE/*"
            ]
        }
    ]
}
```

Also, make sure that disable public access blocking for the bucket you upload to (Click on the bucket -> Permissions -> Block public access (bucket settings))

**Comment by lordvee** [comment]
I read this thread as i am having the same issue.
I am really struggling to understand why would that have to be hard-coded. Ideally this should be set as an option. 

There are use cases where you don't want the bucket to be public.

**Comment by derrickmehaffy** [comment]
> I read this thread as i am having the same issue.
> I am really struggling to understand why would that have to be hard-coded. Ideally this should be set as an option.
> 
> There are use cases where you don't want the bucket to be public.

Because we don't proxy the files back through the Strapi application on fetch, the user is fetching the file directly from AWS

**Comment by lordvee** [comment]
yes, actually i just realized this and spent the night thinking how to overcome this setting.

my use case is a profile picture, which the user may not necessarily want to share with everyone.

I was thinking to have a custom collection field 'personal media' that deals with this use case.

**Comment by derrickmehaffy** [comment]
> yes, actually i just realized this and spent the night thinking how to overcome this setting.
> 
> my use case is a profile picture, which the user may not necessarily want to share with everyone.
> 
> I was thinking to have a custom collection field 'personal media' that deals with this use case.

The best option would be with a custom provider (there are a few on npm) the implement Cloudfront in front of your S3 bucket so you can keep limited access to the bucket.

**Comment by baermathias** [comment]
@derrickmehaffy Could you elaborate more on this option? How can you configure cloudfront in a way that certain urls can only be accessed by certain users?

I have another solution in mind, which would restrict or allow access to certain urls on nginx level. I think it should be possible to store active user sessions in redis and then use `njs` scripting on each request and check if a certain request + jwt has an active session open.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Could you elaborate more on this option? How can you configure cloudfront in a way that certain urls can only be accessed by certain users or user roles?

Sorry I should have clarified, it's not possible for specific users, this would be more so S3 bucket protections to avoid exposing the bucket itself to the "public web". To handle a case like that, your only option would be to find a way to proxy the file serving back through Strapi itself

**Comment by bakeruk** [comment]
The flexibility of implementing AWS S3 is a powerful asset for all developers with varying knowledge. This flexibility must be respected regarding the potential fix for this issue.

### ACL
In its simplicity, the ACL must be optional but also be able to be set if required.

### CDN
In its simplicity, the same can also go for the developers who wish to implement this module to work in conjunction with a CDN. Give the module the ability to resolve CDN file URLs with the given CDN domain. If a domain is not provided, simply fall back to the original S3 URL of the file.

Both of the above proposals can be done with simply config and can be changed using environment variables. Their implementation should meet most development requirements.

While we are on the subject a lot of the `upload` parameters could be added from the [AWS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property) such as `StorageClass`, `ServerSideEncryption`, etc to meet advance requirements.

```typescript
module.exports = ({ env }) => ({
  // ...
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('AWS_S3_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_S3_ACCESS_SECRET'),
      region: env('AWS_S3_REGION'),
      params: {
        Bucket: env('AWS_S3_BUCKET'),
        ACL: env('AWS_S3_ACL'), // New (optional)
        StorageClass: env('AWS_S3_STORAGE_CLASS') // New (optional)
        ... // More AWS SDK S3.upload parameters
      },
      cdnDomain: env('AWS_S3_CDN_DOMIN') // New (optional)
    },
  },
  // ...
});
```

I believe this would be a great interaction of this module. But what do you think?

BTW I am happy to create a PR and implement this if agreed.

**Comment by paulpopus** [comment]
@callmephilip I think you may want to limit the action to object retrieval only by setting the action to `s3:GetObject` instead.

Here is the updated policy we're using:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::YOUR_BUCKET_NAME_HERE/*"
            ]
        }
    ]
}
```

**Comment by dennisameling** [comment]
> nvm the issue was the missing PutObjectAcl permission

Adding the `PutObjectAcl` permission fixed things for me as well! So then the full policy becomes

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "StrapiS3Access",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucketname",
                "arn:aws:s3:::mybucketname/*"
            ]
        }
    ]
}
```

**Comment by hongsw** [comment]
Block all public access : Off
Object Ownership : Bucket owner preferred

Bucket policy :
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "StrapiS3Access",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucketname",
                "arn:aws:s3:::mybucketname/*"
            ]
        }
    ]
}
```

cf.  "Principal" added

**Comment by selected-pixel-jameson** [comment]
Doesn't this seem like a huge security concern to anyone else? Just leaving our buckets wide open waiting for someone to come along and delete everything?

**Comment by selected-pixel-jameson** [comment]
I've slightly modified @vmarchesin solution based off Strapi V4.

```
'use strict';

/**
 * Module dependencies
 */

/* eslint-disable no-unused-vars */
// Public node modules.
const _ = require('lodash');
const AWS = require('aws-sdk');



module.exports = {
    init(config) {
        const S3 = new AWS.S3({
            apiVersion: '2006-03-01',
            ...config,
        });
        const upload = (file, customParams = {}) =>
            new Promise((resolve, reject) => {
                // upload file on S3 bucket
                const path = file.path ? `${file.path}/` : '';
                const key = `${path}${file.hash}${file.ext}`
                S3.upload(
                    {
                        Key: key,
                        Body: file.stream || Buffer.from(file.buffer, 'binary'),
                        ContentType: file.mime,
                        ...customParams,
                    },
                    (err, data) => {
                        if (err) {
                            return reject(err);
                        }

                        // set the bucket file url
                        file.url = `${config.cdn}/${key}`;

                        resolve();
                    }
                );
            });

        return {
            uploadStream(file, customParams = {}) {
                return upload(file, customParams);
            },
            upload(file, customParams = {}) {
                return upload(file, customParams);
            },
            delete(file, customParams = {}) {
                return new Promise((resolve, reject) => {
                    // delete file on S3 bucket
                    const path = file.path ? `${file.path}/` : '';
                    S3.deleteObject(
                        {
                            Key: `${path}${file.hash}${file.ext}`,
                            ...customParams,
                        },
                        (err, data) => {
                            if (err) {
                                return reject(err);
                            }

                            resolve();
                        }
                    );
                });
            },
        };
    },
}
```

This all works, except for deleting. When I delete the file via the admin interface delete is never even called. Any ideas?

**Comment by ikoif** [comment]
For anyone seeing `AccessControlListNotSupported: The bucket does not allow ACLs` when using the official strapi plugin `@strapi/provider-upload-aws-s3` in its most basic use case. 

I don't know what exactly the case is for CDNs, but for the most basic use case of uploading a file via an AWS IAM programmatic user and then being able to view the file publicly (using the URL on a public web page) then these are my settings:

My Block public access (bucket settings)

**Comment by Mukhammadali** [comment]
Or simply set `ACL: null` like this instead of updating bucket ACL configuration or modifying the plugin source code

```
        provider: 'aws-s3',
        providerOptions: {
          accessKeyId: env('AWS_ACCESS_KEY_ID'),
          secretAccessKey: env('AWS_ACCESS_SECRET'),
          region: env('AWS_REGION'),
          params: {
            Bucket: env('AWS_BUCKET'),
          },
        },
        actionOptions: {
          upload: {
            ACL: null
          },
          uploadStream: {
            ACL: null
          },
        }
```

**Comment by pwizla** [comment]
Hello @lowki,

Sorry for not replying earlier, we, unfortunately, didn't have time to focus on issues before now.

I've just fixed it with PR #954 and linked to the issue from the docs if users need more details.
I will close this issue now, please feel free to open another one if it happens with the v4 documentation. Thank you!

**Comment by manvydasu** [comment]
@Mukhammadali 
That only solves part of problem. Files get uploaded, but then Strapi's admin panel can't load these private images. Seems like strapi just lacks proper support for private S3 buckets.

**Comment by derrickmehaffy** [comment]
This is correct, we do not support private buckets.

**Comment by manvydasu** [comment]
@derrickmehaffy 
Could we at least have a hash which is longer than 10 symbols so that files would be harder to find if someone did public scanning on bucket? Or is the current hash (10 symbols) considered to be safe by Strapi?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Could we at least have a hash which is longer than 10 symbols so that files would be harder to find if someone did public scanning on bucket? Or is the current hash (10 symbols) considered to be safe by Strapi?

We don't focus on file security at all simply because we don't expect that the files should be secure at all. We only set the hash to prevent duplicates, it's not a security feature.

**Comment by kibblerz** [comment]
actionOptions: {
        upload: {
          ACL: "private"
        },
        uploadStream: {
          ACL:  "private"
        }
      }
      
    Just add this to upload.config in config/plugins.js. Problem solved :)

**Comment by kibblerz** [comment]
```
strapi.db.lifecycles.subscribe({
      models: ["plugin::upload.file"],
      beforeCreate(event) {
        if(event.params.data.url){
          const imagePath = new URL(event.params.data.url).pathname
          event.params.data.url = `${bucketPath}${imagePath}`
        }
      },
    })
```

This lifecycle hook can overwrite the urls for usage with cloudfront. You can also do a findMany on the files during bootstrap, and replace the urls as Strapi boots to make the images work in the admin

**Comment by nicoes** [comment]
@kibblerz nice info on the lifecycle hook. For me the url doesn't get overridden unfortunately with the Cloudfront url, even though I can log it to the console. But reassigning it to event.params.data.url doesn't look to be persisted.

**Comment by SrTristao** [comment]
Hellow everyone, I have followed some tips above, I choose set actionOptions (upload, uploadStream and delete) to ACL: "private" and I had a great result but After image uploaded in s3, Strapi not render the image in admin / website.

![image](https://user-images.githubusercontent.com/18468813/215158142-ac819d8d-0a57-4878-8303-39f815566ada.png)

Were someone through it?

**Comment by SrTristao** [comment]
Hello, everyone.

I created a svc_user in aws to manage s3 bucket specific to strapi and added policy bellow.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "{arn-bucket}/*",
                "{arn-bucket}"
            ]
        }
    ]
}

I don't know Why but worked after 5 or 10 minutes and Worked very nice.

**Comment by blockmar** [comment]
+1 for all the suggested CDN solutions that also remove the default ACL. Exposing a bucket directly without cloudfront is bad practice and using S3 ACLS is no longer recommended and give violations in AWS Security hub.

Lets get with the times after 3 years of having this ticket open.

**Comment by luketych** [comment]
PLEASE FIX THIS. MY GOD

**Comment by dipanshuhappy** [comment]
This issue is still there
