### ISSUE TITLE
Can't access strapi.server in bootstrap.js file

### ISSUE THREAD

**Issue by kadirgombel** [strapi/strapi#5869]
**Describe the bug**
strapi.server is not accessible in bootstrap.js

**Steps to reproduce the behavior**

try to access strapi.server in bootstrap.js

**Expected behavior**
It should be accessible 

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v10.16.3
- NPM version: v6.14.2
- Strapi version: v20
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment]
@kadirgombel can you please provide some examples or code snippets so we can try to reproduce this?

**Comment by kadirgombel** [comment]
@derrickmehaffy `console.log(strapi.server);` in bootstrap.js results with `undefined`. I was able to access to strapi.server in v19.4

**Comment by timhonders** [comment]
We have the same problem, we use the bootrsrap.js to add a socket.io connection like this tutorial:

https://medium.com/strapi/strapi-socket-io-a9c856e915a6

Example code to reproduce:

`/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#bootstrap
 */

module.exports = () => {
    console.log('++++++++++++++++++++++++++++++++++++++++++++++');
    console.log('[bootstrap.js]', strapi.server);
	console.log('++++++++++++++++++++++++++++++++++++++++++++++');
};
`

**Comment by derrickmehaffy** [comment]
I was able to reproduce this:

beta.19.5 `console.log(strapi.server)` works
beta.20 `console.log(strapi.server)` does not

@alexandrebodin ?

**Comment by alexandrebodin** [comment]
Hi, strapi.server is only accessible after the server has started from now on. As such it is not available in bootstrap anymore. Is there any reason you need access to `strapi.server` during bootstrap ?

**Comment by timhonders** [comment]
@alexandrebodin 
If u want to add a socket.io server to strapi, socket.io needs a http server.
So when u add the stapi server like in the following tutorial:

https://medium.com/strapi/strapi-socket-io-a9c856e915a6

u can make socket connections to strapi.

I am new to strapi so maybe ther is a better place to do this?

**Comment by alexandrebodin** [comment]
Thank you for this insight :) Right now you can create a `server.js` file and do 

```js
const app = require('strapi')();

app.start()

socket(app.server); 
```

Will think of a cleaner way for future releases

**Comment by timhonders** [comment]
ok thanx

**Comment by alexkharech** [comment]
```js
strapi.start(() => {
  console.log(strapi.server);
});
```

**Comment by alexkharech** [comment]
hook for socket.io
```js
module.exports = (strapi) => {
  return {
    initialize() {
      // wait 5 seconds for the server to start
      setTimeout(() => {
        const io = require("socket.io")(strapi.server, {
          path: "/",
        });
        io.on("connection", async (socket) => {
          if (socket.handshake.headers.authorization) {
            const token = socket.handshake.headers.authorization.split(" ")[1];
            if (token) {
              try {
                const { id, isAdmin } = await strapi.plugins[
                  "users-permissions"
                ].services.jwt.verify(token);
                socket.join(id);
              } catch (e) {
                console.log(e);
              }
            }
          }
        });
        strapi.io = io;
      }, 5000);
    },
  };
};

```

**Comment by alexandrebodin** [comment]
@alexkharech I think you can using nextTick instead of setting a timeout. Can you verify this ?

**Comment by alexkharech** [comment]
@alexandrebodin Please specify which object should contain this method? in the global strapi, he is absent

**Comment by obuchmann-pc-web** [comment]
I can verify the missing strapi.server.

But i got socket.js running in `config/functions/bootstrap.js` via process.nextTick

```
module.exports = async () => {

  process.nextTick(() =>{
    var io = require('socket.io')(strapi.server);
    io.on('connection', function(socket){
      console.log("a user connected")
      // send message on user connection
      socket.emit('hello', JSON.stringify({message: 'Hello user'}));


      // listen for user diconnect
      socket.on('disconnect', () => console.log('a user disconnected'));
    });
    strapi.io = io; // register socket io inside strapi main object to use it globally anywhere
  })

};

```

**Comment by Moizsohail** [comment]
Any solution

**Comment by Moizsohail** [comment]
> I can verify the missing strapi.server.
> 
> But i got socket.js running in `config/functions/bootstrap.js` via process.nextTick
> 
> ```
> module.exports = async () => {
> 
>   process.nextTick(() =>{
>     var io = require('socket.io')(strapi.server);
>     io.on('connection', function(socket){
>       console.log("a user connected")
>       // send message on user connection
>       socket.emit('hello', JSON.stringify({message: 'Hello user'}));
> 
> 
>       // listen for user diconnect
>       socket.on('disconnect', () => console.log('a user disconnected'));
>     });
>     strapi.io = io; // register socket io inside strapi main object to use it globally anywhere
>   })
> 
> };
> ```

Hey thanks for the solution.
How do I connect an external project like vue to this socket? I mean what address should I use. I tried using 
ws://localhost:1337 but it does not work

**Comment by wacoom** [comment]
socket.io Not working after upgrade to 3.1.1

**Comment by Moizsohail** [comment]
> socket.io Not working after upgrade to 3.1.1,
> debug GET /socket/?EIO=3&transport=websocket (22 ms) 404

Check this out I just ran it

https://stackoverflow.com/questions/63059975/how-to-set-up-a-socket-connection-on-a-strapi-server

**Comment by wacoom** [comment]
> > socket.io Not working after upgrade to 3.1.1,
> > debug GET /socket/?EIO=3&transport=websocket (22 ms) 404
> 
> Check this out I just ran it
> 
> https://stackoverflow.com/questions/63059975/how-to-set-up-a-socket-connection-on-a-strapi-server

@Moizsohail , what is your Strapi Version ?

**Comment by wacoom** [comment]
3.0.0-beta.20.3  =====>            console.log(strapi.server) works
                   3.1.1  =====>            console.log(strapi.server)   undefined

**Comment by Moizsohail** [comment]
3.0.5. I see.

**Comment by alexandrebodin** [comment]
Hi, the change Happened in 3.0.0 that is not normal that it works in 3.0.5 :/ can you confirm the running version of strapi with a console.log strapi.config.info ?

**Comment by Moizsohail** [comment]
![15958623076154224201574963048832](https://user-images.githubusercontent.com/32095770/88558091-8838d180-d044-11ea-8d0a-55da757a1e4e.jpg)

**Comment by alexandrebodin** [comment]
can you share your bootstrap file please so I can test the fix :)

**Comment by Moizsohail** [comment]
> > socket.io Not working after upgrade to 3.1.1,
> > debug GET /socket/?EIO=3&transport=websocket (22 ms) 404
> 
> Check this out I just ran it
> 
> https://stackoverflow.com/questions/63059975/how-to-set-up-a-socket-connection-on-a-strapi-server

This is my implementation

**Comment by litehacker** [comment]
Hello, I can get access `socket.emit('hello', {message: await strapi.services.question.findOne()});` even if the `questions` are not public, and I should access them only by submitting my JWT.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/bootstrap-js-strapi-object/11233/1

**Comment by laohanme** [comment]
Hi is there any solution for this in Strapi v4

**Comment by Ed-Isingoma** [comment]
Hello, do we only have to rely on process.nextTick even in strapi v5?
