### ISSUE TITLE
http://localhost:1337/graphql/ don't work

### ISSUE THREAD

**Issue by ricar2ce** [strapi/strapi#5871]
I have running strapi, but when I go to the address: http://localhost:1337/graphql/ , it returns the following:
{"statusCode": 404, "error": "Not Found", "message": "Not Found"}

thanks in advance

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
