### ISSUE TITLE
How to render rich text?

### ISSUE THREAD

**Issue by mrcnw** [strapi/strapi#5876]
Hello,

I have the problem associated with rendering rich text. I am using Gatsby and I have tried react-markdown, but it doesn't work. Only bullet points make let's say `<br />`. How to you deal with WYSIWYG in Strapi?

![image](https://user-images.githubusercontent.com/32802948/79703125-08af9f80-82aa-11ea-9fdf-d12da34759c2.png)

**Comment by DarkWayfarer** [comment]
@mrcnw Hey. 
Use this instruction https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi

**Comment by DBosley** [comment]
The rich text that strapi generates by default is just markdown. Use a markdown to html parser to render it on your site.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
