### ISSUE TITLE
Strapi development -watch-admin 404

### ISSUE THREAD

**Issue by kulbon** [strapi/strapi#5877]
**Describe the bug**

I want to create a plugin, I used CLI to create one.
After running

`NODE_ENV=development yarn develop --watch-admin`

my admin is 404

`Welcome back!
To access the server ⚡️, go to:
http://localhost:1337

[2020-04-20T06:25:51.444Z] debug GET /admin/plugins/dotpay (36 ms) 404
[2020-04-20T06:25:51.773Z] debug GET /favicon.ico (1 ms) 200
[2020-04-20T06:25:52.385Z] debug GET /admin/plugins/dotpay (7 ms) 404
[2020-04-20T06:25:52.631Z] debug GET /favicon.ico (0 ms) 200
[2020-04-20T06:25:53.247Z] debug GET /admin/plugins/dotpay (6 ms) 404
[2020-04-20T06:25:53.601Z] debug GET /favicon.ico (0 ms) 200
[2020-04-20T06:26:01.460Z] debug GET /admin/ (5 ms) 404`

`{"statusCode":404,"error":"Not Found","message":"Not Found"}`

When i start: 
`NODE_ENV=development yarn develop`

Everything is working. When I create build. My changes appears with no errors.

**System**

- Node.js version: v10.15.2
- yarn version: 1.22.4
- Strapi version: 3.0.0-beta.20
- mysql, 10.3.7-MariaDB-1:10.3.7+maria
- Operating system: debian 9

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html#changing-the-port

**Comment by derrickmehaffy** [comment]
By default when using --watch-admin the normal admin on port 1337 is disabled and runs the admin in a hot-reload on a different port. This is intended.

**Comment by kulbon** [comment]
With port 8000 still no luck,

ERR_CONNECTION_REFUSED

After changing port in Config/development/server.js
`{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": true
  },
  "admin": {
    "autoOpen": false,
    "port": 3001
  }
}
`

On localhost:3001/admin I have 

ERR_CONNECTION_REFUSED

**Comment by rachaelsingleton** [comment]
Did you figure this out? Having the same issue.

**Comment by alreece45** [comment]
It looks like there is a separate `watch-admin` command that's needed:

 * Run the strapi API (e.g: `yarn run strapi develop --watch-admin`)
 * Run the strapi admin, with the host set (e.g: `HOST=127.0.01 yarn run strapi watch-admin`

**Comment by kulbon** [comment]
> * Run the strapi API (e.g: `yarn run strapi develop --watch-admin`)

This is not working for me, it starts with port 1337 like usual with live-reload for api / endpoints.

> * yarn run strapi watch-admin`

This works for me :) but I need to run "yarn develop" also in second console window :)

**Comment by derrickmehaffy** [comment]
You shouldn't include `run` with yarn commands

**Comment by Jaikant** [comment]
+1 for the issue, seeing the same problem.

When I run 

`NODE_ENV=development yarn develop --watch-admin`

I get the below error on localhost:1337

`{"statusCode":404,"error":"Not Found","message":"Not Found"}`

**Comment by bikoev** [comment]
1. _root/extensions/users-permissions_ create _**models**_ folder, if you dont have it, and create _**User.settings.json**_ with: 
```
{
  "connection": "default",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    }
  }
}
```
2. then **strapi build --clean** and **strapi develop --watch-admin**

---------------------
if it doesn't help:
1. Add new user with Authenticated role(if you don't have one)
2. check config/environments/development/server.json: `"host"` should be with value `"localhost"`, not `"${process.env.HOST || '0.0.0.0'}"` or something

**Comment by kulbon** [comment]
@bikoev Not working for me...

I don't know if it is related but my :1337 admin page looks like this:
![image](https://user-images.githubusercontent.com/32324644/83872496-6866ea80-a732-11ea-8327-73fe66556d49.png)

**Comment by bikoev** [comment]
User.settings.json doesn't affect the start page. Anyway on --watch-admin mode 8000 is a servicing port(if you haven't changed it in server.json config), admin panel will work on this port, not 1337.  If you have time, create a clean strapi project and try what I suggested

**Comment by ckyleda** [comment]
I am having this exact issue.

Oddly enough, this worked fine previously, and has now suddenly stopped working. Whereas the output before stated something akin to "Admin panel started on localhost:8000", this output no longer appears.  The output is below:

```
 Actions available                                                            

Welcome back!
To access the server ⚡️, go to:
http://localhost:3000

 DONE  Compiled successfully in 6121ms                                                                                                                                                                            3:12:53 PM

 WAIT  Compiling...                                                                                                                                                                                               3:12:53 PM

 DONE  Compiled successfully in 680ms     
```

This link, takes you do the panel that says "open admin" which of course returns {"statusCode":404,"error":"Not Found","message":"Not Found"}.

So, where is the admin panel being bound to? Is it failing to start? Is it bound to a port and simply not reporting it? Can we turn on debugging somehow?

In fact, how does the entire thing work? The documentation is remarkably poor in describing how this is all wired together.

**Comment by winston0410** [comment]
I have the same issue, with an error of ` InternalServerError: http://localhost:8000 is not a valid origin`.  Not sure if this can help.

**Comment by raphaelsoul** [comment]
try visit http://127.0.0.1:8000

**Comment by adriancbo** [comment]
Same issue

**Comment by kadiresen** [comment]
can you try this again after you've created a simple cors middleware like this:

(config/middleware.js)

```
module.exports = {
  settings: {
    cors: {
      origin: "http://localhost:8000,http://localhost:1337",
    },
  },
};
```

**Comment by chihab** [comment]
Make sure you're not already running something on 8000 (Gatsby).

**Comment by hermanndettmann** [comment]
I stumbled upon this thread here as I have the same issue and hope there is some help. I just want to create a new local plugin and can't get the development setup to run like described in the docs.

The plugin is already scaffolded from the CLI and now I want to build some UI. But when I run `npm run develop -- --watch-admin` it first hangs at:

`Welcome back!
To access the server ⚡️, go to:
http://localhost:1337`

after a while it spits out a lot of warnings regarding duplicate packages in different versions. Now I can access `http://localhost:1337` but `http://localhost:1337/admin` gives me a blank screen with the text _Not Found_. So I can't access the admin at all. The only way I could see my changes is to rerun `npm run build` over and over again. But what is this `npm run develop -- --watch-admin` for then?

I also tried accessing `localhost:8000` but with no luck. It doesn't send any response even if the CLI told me so.

So any ideas how to fix this? I would be really happy as I really like Strapi so far!

**System**

- Docker with Lando
- Node.js version: v14.15.3
- npm version: 6.14.9
- Strapi version: 3.4.1
- mysql 5.7

**Comment by derrickmehaffy** [comment]
@hermanndettmann currently we don't support the watch-admin inside of docker, you will need to run it on your host.

**Comment by hermanndettmann** [comment]
@derrickmehaffy Thanks for the quick response! I reconfigured my stack and running the node stuff now on my host works. Thanks!

**Comment by fl034** [comment]
@hermanndettmann what was your solution? 
@derrickmehaffy could you elaborate a little why this is not possible? Maybe there's a workaround?

**Comment by hermanndettmann** [comment]
@fl034 see my former comment. ;-)

**Comment by mike-hor** [comment]
for the issue, seeing the same problem.
![image](https://user-images.githubusercontent.com/17822235/120524907-25edf180-c40a-11eb-80ed-77f48a96c54d.png)
![image](https://user-images.githubusercontent.com/17822235/120525016-3f8f3900-c40a-11eb-9e6d-ef5de3b74fcb.png)

**Comment by markushi** [comment]
I did face the same issue recently and running outside docker was not an option for me. I managed to get it running with docker quite easily, maybe it's useful for some other folks as well:
1. Adapt docker config to publish the admin port (default 8000) to the host as well
2. Set the `admin.host` property in `/config/server.js` to `0.0.0.0` to allow host access

@derrickmehaffy if it makes sense, I'd be happy to create a PR for updating the docs.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy if it makes sense, I'd be happy to create a PR for updating the docs.

Sure please feel free on the docs repo: https://github.com/strapi/documentation

**Comment by mstys** [comment]
I had the same issue when I set `PORT` to `8000` in `.env` file . Then `--watch-admin` doesn't work for me.
After removing this option everything works again as follow:

```bash
Welcome back!
To access the server ⚡️, go to:
http://localhost:1337

ℹ ｢wds｣: Project is running at http://localhost:8000/
ℹ ｢wds｣: webpack output is served from /admin/
ℹ ｢wds｣: Content not from webpack is served from /Users/michal.stys/OwnProjects/my-site/backend
ℹ ｢wds｣: 404s will fallback to /admin/
Starting the development server...

Admin development at http://localhost:8000/admin/
``` 

Hope I help someone.

**Comment by vivmagarwal** [comment]
Yes, it's a minor bug with `--watch-admin` as of now. 

Even though the CLI suggests `Admin development at http://localhost:8000/admin/` 

if you check the listening ports, its 8080 and not 8000:
```
node      97230 vivek   26u     IPv4 0x6b15a3c995407737        0t0                 TCP *:1337 (LISTEN)
node      97254 vivek   24u     IPv6 0x6b15a3ce6e296b3f        0t0                 TCP *:8080 (LISTEN)
```
Solution:
use this URL instead: http://localhost:8080/admin/auth/login 
when using with the `--watch-admin`
