### ISSUE TITLE
Different upload adapter per environment not possible since 3.0.0-beta.20

### ISSUE THREAD

**Issue by fechy** [strapi/strapi#5878]
**Describe the bug**
Since 3.0.0-beta.20, the ability to configure the upload adapter based on the environment is gone. Leaving to 2 options:
- Manually changing in dev to use local and ignore the settings file, or...
- Use S3 (or whatever production adapter you use) for dev too.

This is very inconvenient and there is no information on how to make it work as one would expect.

**Steps to reproduce the behavior**
- Update to latest 3.0.0-beta.20

**Expected behavior**
- Being able to configure adapter by environment similar to the server config

**System**

- Node.js version:  v12
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.20
- Database: Postgres
- Operating system: Docker linux

**Comment by derrickmehaffy** [comment]
While I wouldn't directly label this as a bug per-say I'll leave this here to get feedback from the engineering and product teams

@alexandrebodin @Aurelsicoko

**Comment by alexandrebodin** [comment]
Hi,

Here is a discussion where I share how you can easily make env depend configurations: https://github.com/strapi/strapi/pull/5358, until we release our new config loader that will make this more mainstream

**Comment by fechy** [comment]
Perfect, I didn't found a category where to put it that's why it ended up as a bug.
The discussion maybe needs more visibility since this is a drastic change from the previous version.
