### ISSUE TITLE
The provider package isn't installed. Please run `npm install strapi-provider-upload-aws-s3

### ISSUE THREAD

**Issue by thalaivar-subu** [strapi/strapi#5879]
**Describe the bug**
Everything was working fine. Until last deployement in production. We have added some new content types. No changes in package level , nothing. The usual procedure.
We were unable to upload in Production.
So we reverted back to the old Image -> It is working fine.
We are clue less. So started looking in the internals of strapi.

**Steps to reproduce the behavior**
We itself don't know.

**Expected behavior**
It should upload to S3.

**Screenshots**
![image](https://user-images.githubusercontent.com/52786293/79724959-0d09a600-8306-11ea-8f7a-05014cd1022e.png)

**Code snippets**
While Requiring AWS S3 package -> There is no provider name.
![image](https://user-images.githubusercontent.com/52786293/79724812-ccaa2800-8305-11ea-9fe8-983f281fe2c7.png)
File -> /opt/strapi/plugins/upload/config/functions/bootstrap.js

**System**
- Node.js version: v10.14.2
- NPM version: 6.4.1
- Strapi version: Version -> 3.0.0-alpha.22
- Database: MongoDB
- Operating system: Linux Ubuntu 16.04

Response 
{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"The provider package isn't installed. Please run `npm install strapi-provider-upload-aws-s3`"}]}]}

**Additional context**
We are not in the situation to migrate strapi to new version currently. We want a hack/fix.

Thanks & Regards

**Comment by derrickmehaffy** [comment]
@thalaivar-subu `3.0.0-alpha.22` Sorry bug Strapi alpha is no longer supported. I know you are looking for a hack but unfortunately this isn't place to request something like that.

The Strapi team had to make the hard choice to simply stop supporting the Alpha in order to focus on the future.

**Comment by thalaivar-subu** [comment]
@derrickmehaffy  -> Thanks for your support. We are in the process of upgrading.
And have a found a fix too. I will post it here so that it will help someone like us who are facing this issue and are using old version of strapi.

![image](https://user-images.githubusercontent.com/52786293/79733605-02094280-8313-11ea-9079-f784122fa36b.png)
Move the provider package to **exact version** 
remove **^**

**Comment by derrickmehaffy** [comment]
Yes generally speaking (for all strapi versions) all strapi packages should be the same "version" with no `^` in them
