### ISSUE TITLE
403 /auth/local with mysql DB

### ISSUE THREAD

**Issue by ayelsew** [strapi/strapi#5889]
**Describe the bug**
When I try to login through the strapi API using a previous registered user, the server response is 403 forbidden.

**Steps to reproduce the behavior**

1. Start the back end in developer mode (yarn develop);
2. Send a request to the /auth/local route, expecting a 200 status code but receive a 403 Forbidden code instead;

**Screenshots**
![image](https://user-images.githubusercontent.com/33585141/79795798-deea8d00-832a-11ea-8a02-e07399324050.png)

**Code snippets**
Code of request (with jest):
```
describe("loggin", () => {
    it("post", done => {
        fetch(URI + "/auth/local", {
            method: "post",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                identifier: "test",
                password: "test1234"
            })
        }).then(async res => {
            const d = await res.json()
            console.log(d)
            expect(res.status).toEqual(200)


            done()
        }).catch(err => {
            done.fail(err)
        })
    })
})
```

**System**

- Node.js version: 13.11
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta-20
- Database: MySQL
- Operating system: Kubuntu 18.04

**Additional context**
I have been using strapi-beta-19.5, but because of this problem I tried to upgrade to 3.0.0-beta-20, without success.

**Comment by lauriejim** [comment]
Hello, did you customize anything in your application?
Because it works well on my side.
