### ISSUE TITLE
Bad link to parameters concept document

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#5891]
**Describe the bug**
The very first sentence in **[Parameters](https://strapi.io/documentation/3.0.0-beta.x/content-api/parameters.html)** section, has a bad link (spelled as **`parameters' concepts`**). 

**Note 1** There is no sub-section `parameters` in the `Concepts` section.

**Note 2** The apostrophe character in **`parameters' concepts`** is syntactically incorrect.

**System**

- Node.js version: v12.14.0
- NPM version: 6.13.6
- Strapi version:  3.0.0-beta.19.5
- Database: N/A
- Operating system: Windows 10 Enterprise

_**My comment**: I am very sensitive to the correctness and completeness of the technical documentation, being burned in the past when this priority was not at the top of my list_

**Comment by derrickmehaffy** [comment]
@lauriejim I think we are missing the programmic usage for parameters, was removed in https://github.com/strapi/strapi/pull/5674
