### ISSUE TITLE
Create a new project failed.

### ISSUE THREAD

**Issue by Halloween2018** [strapi/strapi#5892]
The env is: window 10
node v12.16.2
npm 6.14.4
docker 19.03.8
yarn 1.22.4
The problem has been going on for more than a week.I'm following the document guide to install strapi，either the way using cli or docker，the same problem arises:
[2020-04-20T11:03:10.576Z] debug ⛔️ Server wasn't able to start properly.

[2020-04-20T11:03:10.577Z] error Error:

Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp.node'

Require stack:

- /srv/app/node_modules/sharp/lib/constructor.js

- /srv/app/node_modules/sharp/lib/index.js

- /srv/app/node_modules/strapi-plugin-upload/services/image-manipulation.js

- /srv/app/node_modules/strapi/lib/load/load-files.js

- /srv/app/node_modules/strapi/lib/load/load-config-files.js

- /srv/app/node_modules/strapi/lib/commands/develop.js

- /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js

- Run "npm rebuild --verbose sharp" and look for errors

- Consult the installation documentation at https://sharp.pixelplumbing.com/install

- Search for this error at https://github.com/lovell/sharp/issues

at Object.<anonymous> (/srv/app/node_modules/sharp/lib/constructor.js:34:9)

at Module._compile (internal/modules/cjs/loader.js:956:30)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)

at Module.load (internal/modules/cjs/loader.js:812:32)

at Function.Module._load (internal/modules/cjs/loader.js:724:14)

at Module.require (internal/modules/cjs/loader.js:849:19)

at require (internal/modules/cjs/helpers.js:74:18)

at Object.<anonymous> (/srv/app/node_modules/sharp/lib/index.js:3:15)

**Comment by christianguevara** [comment]
Hey!
Your are not following the [bug report template](https://github.com/strapi/strapi/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by Halloween2018** [comment]
> > This is a templated message
> 
> Hello, please follow the issue template.
> 
> A proper issue submission let's us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.
> 
> Please update the issue.
> 
> Thank you.
> 
> > A copy of the bug report template can be found below:
> 
> ```
> 
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Steps to reproduce the behavior**
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Code snippets**
> If applicable, add code samples to help explain your problem.
> 
> **System**
> - Node.js version: 
> - NPM version:
> - Strapi version: 
> - Database:
> - Operating system:
> 
> **Additional context**
> Add any other context about the problem here.
> ```

OK, I'll update later!

**Comment by ramonmulia** [comment]
hey @Halloween2018 did you fix it?

**Comment by adhamaa** [comment]
https://github.com/strapi/strapi/discussions/5835#discussioncomment-147750

**Comment by adhamaa** [comment]
> 
> 
> hey @Halloween2018 did you fix it?

https://github.com/strapi/strapi/discussions/5835#discussioncomment-147750

**Comment by virgil9306** [comment]
This still happens, why the discussion was deleted I don't know.

That link is broken @adhamaa 
Here is the archived page: https://webcache.googleusercontent.com/search?q=cache:oQbfgkD7X4gJ:https://github.com/strapi/strapi/discussions/5835%3Fsort_order%3Drelevance+&cd=1&hl=en

**Comment by derrickmehaffy** [comment]
> That link is broken @adhamaa
> This still happens, why the discussion was deleted I don't know.
> @ramonmulia Here is the archived page: https://webcache.googleusercontent.com/search?q=cache:oQbfgkD7X4gJ:https://github.com/strapi/strapi/discussions/5835%3Fsort_order%3Drelevance+&cd=1&hl=en

We disabled discussions in late dec 2020 as we moved to our [forum](https://forum.strapi.io) thank you for the archive link though. :)
