### ISSUE TITLE
Media Library with resize capabilities

### ISSUE THREAD

**Issue by kapik** [strapi/strapi#5898]
Hey !

You have released the media library but the resize feature mentioned throw the [roadmap](https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities) is missing 😢 

Do you plan to add it 🙏 ?

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
