### ISSUE TITLE
upgrade error from 19.5 to 20

### ISSUE THREAD

**Issue by altezza04** [strapi/strapi#5905]
<img width="797" alt="Screenshot 2020-04-22 at 5 16 44 PM" src="https://user-images.githubusercontent.com/59946405/79964324-1c7f1f80-84bd-11ea-9de7-39e082e3512a.png">

I follow the instruction at https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html, updating the dependencies to beta20. then when I run "yarn develop" it give the follow screen, and also an error on login {"statusCode":400,"error":"Bad Request","message":"failed to decode"} (console log:  /%3C%=%20strapi.config.admin.url%20%%3E)

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html#index-page
