### ISSUE TITLE
Graceful Start/Shutdown

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#5912]
**Please describe your feature request:**

It would be great if Strapi could support graceful start/shutdown like shown in the PM2 docs: https://pm2.keymetrics.io/docs/usage/signals-clean-restart/

I'm using a `server.js` file in production, could it also be implemented there? There doesn't seem to be much documentation available regarding `require("strapi");`.
Just saw from another issue that there is a `strapi.stop()` method, but what about listening for when the server is ready?

Also, I'm willing to submit a PR, but some guidance would be appreciated:
- Where should I place these functions?
- What needs to be stopped? Only Koa and the DB or something else?

**Comment by diogotcorreia** [comment]
Creating a `server.js` with this code works as a workaround:

```javascript
const strapi = require('strapi');
const app = strapi();
app.start(() => process.send('ready'));

process.on('SIGINT', () => {
  if (app.server) {
    app.server.close(() => {
      process.exit(0);
    });
  }
});
```

Should I still add it as a PR?

**Comment by lauriejim** [comment]
I ping @alexandrebodin about that.

**Comment by alexandrebodin** [comment]
Hi @diogotcorreia, I think that using the server.js technique is the only good way of doing it :) 

We need to improve the "strapi" programmatic API in order to make it more usable as a framework. This is clearly a topic on our mind that we will work on in during the rest of the year :) 

Your approache looks really good. We will need to provide some simple access to also close your database connection or stop some I/O service to make it more complete :)

**Comment by leonardomerlin** [comment]
I'm closing the db connections during my tests like this:

```js
afterAll(async (done) => {

  // Destroy (db) connections
  for(const conn of Object.values(strapi.connections)) {
    if(conn.destroy) {
      await conn.destroy();
    }
  }

  done();
});
```

> BTW, using this approach I can run jest without the `--detectOpenHandles` or `--forceExit` flags.

IMHO, this issue can be considered a partial implementation of #5253

**Comment by sazaam** [comment]
cant have it work... at all
process.send('ready')); process send is not a function

**Comment by littleski** [comment]
There is also another issue to be tacled regarding "plugins" (at least).
I use the following plugins:
-            'content-manager',
-            'content-type-builder',
-            'documentation',
-             'email',
-             'sentry',
-             'upload',
-             'users-permissions'

And with them, i have around 11-12Mb of Memleak per test suite at dismount:
(this is run inBand with a forced garbage collection after each test)
- PASS tests/****(52.793 s, 201 MB heap size)
- PASS tests/**** (12.834 s, 213 MB heap size)
- PASS tests/****(13.398 s, 224 MB heap size)
- PASS tests****(11.561 s, 236 MB heap size)
- PASS tests/****14.188 s, 248 MB heap size)
- PASS tests/****(10.627 s, 257 MB heap size)
- PASS tests/**** (12.64 s, 267 MB heap size)

When attaching a debugger to properly heap dump and look @ the objects:

1. Most of the leaks comes from compiled codes
<img width="1585" alt="Screenshot 2021-09-09 at 11 17 56" src="https://user-images.githubusercontent.com/14992157/132659269-e84b58b7-e7f9-465b-b6b9-dc9866bb4997.png">

2. And this code seems to be retained (but i am not really a node expert) by strapi.plugins
<img width="1585" alt="Screenshot 2021-09-09 at 11 21 35" src="https://user-images.githubusercontent.com/14992157/132659684-75851cc7-f218-47e6-a985-b1fbb0be673f.png">

Few notes :
- Most plugins doesn't implement a "destroy" function to properly handle dismount. (Strapi do a check on destroy to see if the plugins implement the method and run it if its the case, but most of them don't)
- I now do a small "hack" to prevent some plugins to be instanciated 

(Basically, except for my global bootstrap when i want to load them, each test suite won't be loading all plugins, i need that cause i have bootstrap functions which i mock i my test to do them just once for the test battery to save some time)

`
...
const tmpStrapi = await _strapi();
        if (!bootstrap) {
          // Override Strapi Installed Plugins for tests
          tmpStrapi.config.installedPlugins = [
          //  'content-manager',
          //  'content-type-builder',
          // 'documentation',
          //  'email',
            // 'sentry',
            // Theses ones are harder to desactivate
            'upload',
            'users-permissions'
          ];
        }
        /** the following code in copied from `./node_modules/strapi/lib/Strapi.js` */
        await tmpStrapi.load();
.. Etc, continue init`

With this hack, the leak go down from ~12Mb to ~8Mb, (which for 250+ test suites is already a nice improvement).

Trying to find a solution for the other 8, or at least to reduce the leak to 1Mb but that's quite painfull.

And this is not related, but i also use proper lockfile to avoid paralel "load" of strapi (i run my test with 5-10 runners in CI), as parallel load cause random Error.

**Comment by littleski** [comment]
Also, server options is not really viable for me, i want to be able to access strapi services directly to test them, as well as target the routes with an agent (like supertest), and not care what i should use. I use load & destroy, which should be doing the job, except for the point mentionned above.

**Comment by qunabu** [comment]
> I'm closing the db connections during my tests like this:
> 
> ```js
> afterAll(async (done) => {
> 
>   // Destroy (db) connections
>   for(const conn of Object.values(strapi.connections)) {
>     if('destroy' in conn) {
>       await conn.destroy();
>     }
>   }
> 
>   done();
> });
> ```
> 
> > BTW, using this approach I can run jest without the `--detectOpenHandles` or `--forceExit` flags.
> 
> IMHO, this issue can be considered a partial solution of #5253

I'm trying to add your code into https://github.com/qunabu/strapi-unit-test-example yet without success, maybe there is something else that listen here 

I want to make this example to work  without the `--detectOpenHandles` or `--forceExit` flags.

**Comment by derrickmehaffy** [comment]
Currently possible in the v4, marking as closed
