### ISSUE TITLE
Bootstrap function in plugin "content-manager" failed

### ISSUE THREAD

**Issue by abstractk** [strapi/strapi#5915]
**Describe the bug**
Updating Strapi from 18.x to 19.x and getting the error

**Steps to reproduce the behavior**

1. Go to the [migration guide ](https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.18-to-beta.19.html)
2. Follow instructions. Remove `.cache` and `build` directories
3. Run `yarn develop`
4. See below error

```
error Bootstrap function in plugin "content-manager" failed
error Error: Invalid Model configuration for model strapi::administrator. Verify your {{modelName}}.config.js(on) file:
  - Cannot convert undefined or null to object

    at validateCustomConfig (/var/www/node_modules/strapi-plugin-content-manager/services/utils/configuration/index.js:17:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
```

**Expected behavior**
Local environment should start 

**System**

- Node.js version: `v12.16.2`
- NPM version: `6.14.4`
- Strapi version: `3.0.0-beta.19`
- Database: Mongo
- Operating system: Ubuntu

**Comment by nik0145** [comment]
I have the same problem with "3.0.0-beta.19". 
Install 3.0.0-beta.19.3. 
It's worked for me.

**Comment by nik0145** [comment]
Did it works for you, @abstractk ?

**Comment by abstractk** [comment]
Thanks @nik0145, yes that works.
