### ISSUE TITLE
customize strapi-admin-content-manager?

### ISSUE THREAD

**Issue by dunods** [strapi/strapi#5919]
how do i customize services strapi-admin-content-manager within node_modules.

i did try to create my-app/extensions/strapi-admin-content-manger/services/ContentTypes.js but it didnt work ?any help

**Comment by derrickmehaffy** [comment]
`my-app/extensions/content-manger/services/ContentTypes.js`

**Comment by dunods** [comment]
![image](https://user-images.githubusercontent.com/8032766/80088683-0b024a00-8587-11ea-8345-ec923fd73b52.png)

already try it shows error 
please assist
