### ISSUE TITLE
Component cannot be edited with content types builder getting error component icon.required

### ISSUE THREAD

**Issue by ralphsomeday** [strapi/strapi#5921]
**Describe the bug**
I am trying to edit a component using the content type builder. My component has only one enum field and I want to add another description field, all works fine in the type builder but when I hit the save button to update the component then I am getting the following error and a blank page in the Admin UI:

```json
{"error":{"component.icon":["icon.required"]}}
```

**Steps to reproduce the behavior**

1. Create a component using the content type builder with one field that is an enum field 
2. Create a content type that uses this component
3. Create an item of the content type that uses this component
4. Go to content type builder to edit your component and add a new description field
5. try to save the component
6. Blank page in admin UI and error message in the browser console with a 400 bad request response from the server

**Expected behavior**
Saving the edited component works and restarts the server to apply the changes to the component

**Screenshots**

![image](https://user-images.githubusercontent.com/61593456/80092284-d086b600-8562-11ea-8476-64c1dc0f5be4.png)

**System**

- Node.js version: 10.6
- Strapi version: beta 19.5
- Database: Mongo db v4.0.12
- Operating system: Mac OSX Catalina 10.15.4

ps: The only way it works now is if you do it directly in the code and add the field there. It seems the bug is happening when using the Admin UI.

**Comment by soupette** [comment]
Hi @ralphsomeday can you try to upgrade your app to beta.20 and see if the problem persists?

**Comment by marefati110** [comment]
i have same problem with some tables. it's not just for Component

**Comment by lauriejim** [comment]
Hello @ralphsomeday .
Can you please try with the last version of Strapi and confirm the issue exist or not in the last version.

**Comment by ralphsomeday** [comment]
Hi @lauriejim upgraded to beta.20.1 and still have the same issue. See following screenshot:

![image](https://user-images.githubusercontent.com/61593456/80526228-b863cc00-8992-11ea-84bf-3defe0994ace.png)

**Comment by soupette** [comment]
Can add a screenshot of the body of the request fromt the network tab?

**Comment by walhallyus** [comment]
Found the problem!!!!  if u upgraded from old version u have to add an icon to the model(component) first!
![image](https://user-images.githubusercontent.com/4601890/80581224-88a9d800-8a15-11ea-91f1-2230cde3a654.png)

This icon should not be a required field.. in my opinion

**Comment by soupette** [comment]
@walhallyus the icon is for the administration panel. It is there to have a visual way to identify your component in the content manager.

**Comment by walhallyus** [comment]
so if u upgrade from a previous version where u dont have icons, the app should break when trying to change something on the model? and yea... with no details about this....

**Comment by ralphsomeday** [comment]
@soupette that is the issue! As mentioned in the description of this issue it works fine when changing the content type in the json file but the issue is happening when using the admin ui. Can we make this icon optional in the admin ui? or during the migration we have to manually add it to all component .json files? What do you recon?

**Comment by ralphsomeday** [comment]
Adding `"icon": "none"` to the component model make things work. So either we have to add it during migration or make the icon not required.
