### ISSUE TITLE
any idea how do i fetch external api and display it within the strapi dashboard.?

### ISSUE THREAD

**Issue by dunods** [strapi/strapi#5925]
hello,

is anyone here have experience to fetch data from external api and display it within strapi admin?
and using all the functionality of content-manager to manage it (crud function)?
for example given this extenal api as an example 
https://jsonplaceholder.typicode.com/posts

please assist

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
