### ISSUE TITLE
Strapi Provider Upload S3 does not show up on admin panel

### ISSUE THREAD

**Issue by matheusgrieger** [strapi/strapi#5928]
**Describe the bug**
Following the installation instructions on the website I am supposed to go to the Plugins page and enter the `Files Upload` plugin settings as described [here](https://strapi.io/documentation/3.0.0-beta.x/deployment/amazon-aws.html#_3-configure-the-plugin-with-your-bucket-credentials).

It does not show up for me, as you can see in the screenshot below. However adding the configuration files in `extensions/upload/config/settings.json` does the trick and the provider works as expected but I cannot choose a separate provider for each environment like development (I don't want to upload my development testing files to S3).

**Steps to reproduce the behavior**

1. Create a simple project
2. Follow instructions from [Amazon AWS Deployment](https://strapi.io/documentation/3.0.0-beta.x/deployment/amazon-aws.html) **OR**
3. Simply install `strapi-provider-upload-aws-s3@3.0.0-beta.20`.

**Expected behavior**
It should appear in the plugins list and allow different settings for each environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/6992464/80155743-c2538c80-8598-11ea-89b5-1eff016da014.png)

![image](https://user-images.githubusercontent.com/6992464/80156128-8a991480-8599-11ea-9cd0-ea1c97ac939d.png)

**System**

- Node.js version: 
- NPM version: 12.14.0
- Strapi version: 3.0.0-beta.20
- Database: Postgres
- Operating system: MacOS for development, Linux when deployed

**Additional context**
Also, using this `settings.json` file to store access keys is not a really good idea considering it'll be pushed to the repository. It would be better to use environment variables, at least in production.

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.20.html#upload-plugin-settings

https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#using-a-provider

**Comment by derrickmehaffy** [comment]
You can use environment variables in those settings json files or convert them to .js

```
{
  "provider": "aws-s3",
  "providerOptions": {
    "accessKeyId": "{$process.env.AWS_KEY}",
    "secretAccessKey": "{$process.env.AWS_SECRET}",
    "region": "aws-region",
    "params": {
      "Bucket": "{$process.env.AWS_BUCKET}"
    }
  }
}
```

**Comment by officialrj18** [comment]
i am also facing this same issue on heroku server @matheusgrieger 
database : postgress

**Comment by tayloraleach** [comment]
Was there a solution to this? I do not see the 'Files Upload' section in my admin UI either... ? Brand new project.

**Comment by pjamieson** [comment]
With v3.1.1, the instructions for uploading images to S3 in https://strapi.io/documentation/v3.x/deployment/amazon-aws.html appear dated as the instructions there do not match the current UI. The conflicting instructions/example at https://strapi.io/documentation/v3.x/plugins/upload.html#using-a-provider (as well as essentially the same in the plugin's Readme on Git) don't work. Any plans to update these docs? Thanks!

**Comment by JiboStore** [comment]
@matheusgrieger would you please share with us your `settings.json` as described:
```
It does not show up for me, as you can see in the screenshot below. However adding the configuration files in extensions/upload/config/settings.json
```
Where did you get it? I've been trying hard and Googling and trying various strapi commands but to no avail, the upload plugin never shows up and there is no way for me to configure to use S3 in that case

**Comment by derrickmehaffy** [comment]
@JiboStore there is no longer an option in the UI you should see the following docs and the README file for each provider: https://strapi.io/documentation/v3.x/plugins/upload.html#enabling-the-provider

**Comment by matheusgrieger** [comment]
@JiboStore see @derrickmehaffy's comment

**Comment by ferreria23** [comment]
This still doesn't work, tried on version `3.3.4` under docker. The only solution is to use the old way (as described in the beta documentation)
