### ISSUE TITLE
Image becomes broken link

### ISSUE THREAD

**Issue by niyasmhdth** [strapi/strapi#5929]
I have recently hosted strapi cms on a free tier of heroku as part of development where i noticed this bug. When ever i create a new object with data in object. I get the details in endpoints . But the image assets that i upload through image/asset library in strapi dashboard tends to work in the beginning. After few hours the image links becomes broken and when we try to view the image the image assets shows the broken link sign. Also when we try the image end point the server returns empty response with a status code.
Node.js version: 12.16.2
NPM version: 6.14.4
Strapi version: Latest
Database: Heroku Postgres
Operating system: macOS Mojave

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#why-is-my-app-s-database-and-uploads-resetting-on-heroku

**Comment by philgran** [comment]
I have also run into this issue. It seems like when the heroku dyno shuts down, all the image links get broken. I was able to fix it by going to the Media Library tab of my Strapi app, and clicking Replace Media for all images. This is a very manual process and is definitely not sustainable at scale.
