### ISSUE TITLE
Find one resource with invalid id gives 500 instead of 404 with mongodb

### ISSUE THREAD

**Issue by amrsalama** [strapi/strapi#5930]
**Describe the bug**
Find-one endpoint `/resource/:id` responses with 500 status code instead of 404, this happens with MongoDB setup.

**Steps to reproduce the behavior**
1. Setup Strapi with MongoDB configuration.
2. Create a collection (resource).
3. Give `findOne` access to the public.
4. Send a request to `/resource-name/any-invalid-id`.

**Expected behavior**
404 response.

**System**

- Node.js version: 12.15.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: MonogoDB
- Operating system: MacOS

**Additional context**
```
error CastError: Cast to ObjectId failed for value "any-invalid-id" at path "_id" for model "category"
```
This problem is known with MongoDB, It's expected due to passing invalid ObjectID, it tries to parse it to ObjectID first so it fails and we have the 500 response.

**Comment by derrickmehaffy** [comment]
@amrsalama did you update from a previous version?

https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.19-to-beta.19.4.html#route-syntax-changes

**Comment by amrsalama** [comment]
@derrickmehaffy No

**Comment by derrickmehaffy** [comment]
Can you check your routes file because Strapi automatically pluralizes routes (regardless if it's find or fineOne)

**Comment by amrsalama** [comment]
I think we are talking about 2 different things 😄 **Steps to reproduce the behavior** section in the bug description can explain how to reproduce it. It's MongoDB related issue. Actually a famous issue
https://stackoverflow.com/questions/14940660/whats-mongoose-error-cast-to-objectid-failed-for-value-xxx-at-path-id

**Comment by DarkWayfarer** [comment]
@lauriejim @amrsalama 
I think I can add one more point to this problem. 
On version 20, you can’t delete single photos. Multiple load fields have no such problems.

before:
![image](https://user-images.githubusercontent.com/16899697/80867057-73fb6780-8cd5-11ea-8c84-6d298764c2bf.png)
after i try to delete images:
![image](https://user-images.githubusercontent.com/16899697/80867077-8ecddc00-8cd5-11ea-9909-655f6c337928.png)
then i delete the images from the multiple field:
![image](https://user-images.githubusercontent.com/16899697/80867120-bde44d80-8cd5-11ea-9c22-e37600a5576e.png)
and then again try to remove from a single
![image](https://user-images.githubusercontent.com/16899697/80867139-d2c0e100-8cd5-11ea-8170-f390aec8f256.png)
reload
![image](https://user-images.githubusercontent.com/16899697/80867143-e2402a00-8cd5-11ea-83bf-951de539e5ff.png)

**Comment by lauriejim** [comment]
Hello @DarkWayfarer , can you please create another issue please.

**Comment by sarthakkundra** [comment]
is it still open? I would like to work on this issue

**Comment by derrickmehaffy** [comment]
It is yes @sarthakkundra by all means if you can provide a fix here that would be great.

**Comment by daniel-julius-sam** [comment]
Is this issue open?

**Comment by Zulkarnine1** [comment]
Hello, I'm also interested to try it out if it's open.... is it?

**Comment by mani9896** [comment]
@derrickmehaffy Hey if possible can i work on this one?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy Hey if possible can i work on this one?

I'm unsure if we will work on this since we are dropping support for MongoDB with our v4, once we drop the support the MongoDB/Mongoose team will end up building their own connector and likely scrapping our code for the connector.

**Comment by derrickmehaffy** [comment]
MongoDB is not supported anymore in Strapi v4, marking as closed
