### ISSUE TITLE
GraphQL does not appear in extensions

### ISSUE THREAD

**Issue by AnthonyPhan** [strapi/strapi#5933]
Hi All,

After installing the graphQL plugin from the marketplace, a graphql folder is not created within the extensions folder as stated int he documentation [here](https://strapi.io/documentation/3.0.0-beta.x/plugins/graphql.html#usage).

I am trying to increase the graphql row limit form 100 to 1000 but am unable to find the `settings.json` file that should be located in `./extensions/graphql/config/settings.json`

**Steps to reproduce the behavior**

1. Create a new strapi project using quickstart
2. launch strapi in development mode
3. install graphql from the market place
4. look inside the project folders to is the graphql folder is created

**Expected behavior**
After installation of the graphql plugin there should be a grpahql folder present in the extensions directory

**System**

- Node.js version: 12.6.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.20
- Database: SQLlite
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment]
Per those docs: You can edit these configurations by **_creating_** following file.

Meaning you need to create that folder/file path as the default is in node_modules

**Comment by AnthonyPhan** [comment]
*face palm* 
Yes, that worked perfectly... My apologies, I should have read the documentation more carefully

**Comment by derrickmehaffy** [comment]
All good, you aren't the only one :wink:
