### ISSUE TITLE
Add a "test email" button on email providers

### ISSUE THREAD

**Issue by Heziode** [strapi/strapi#5935]
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

Add a "test email" button on email providers, that sends a dummy email (with default from and default to, for example).

This allowing to quickly test if our mail configuration working or not.

**Comment by lauriejim** [comment]
Hello! Thank you for this insight!
I ping @Aurelsicoko about this idea.
I think it's something coo we can easily add in the admin panel.

If we confirm this enhancement/feature.
Here is the frontend [Settings Page code](https://github.com/strapi/strapi/blob/9cbc24c438ab90fea939d1f7719798df2597d1cc/packages/strapi-plugin-upload/admin/src/containers/SettingsPage/index.js) to add an input for the email and a button to trigger the email.
We will have to create a new route to manage the backend logic.

**Comment by Aurelsicoko** [comment]
Good idea! Could you submit a PR? Something like we did with the Webhook to "Trigger it" to try it.

**Comment by Heziode** [comment]
I m very busy lately, but I'll see what I can do.
