### ISSUE TITLE
MySQL Migration failed on `upload_file` table

### ISSUE THREAD

**Issue by Lith** [strapi/strapi#5936]
**Describe the bug**
The latest release (beta.20) is running a migration for `upload_file` table.
When I launch `strapi develop` an error occurs :

```
[
  {
    sql: 'alter table `upload_file` modify `alternativeText` varchar(255) null, modify `caption` varchar(255) null, modify `width` int null, modify `height` int null, modify `formats` longtext null, modify `size` decimal(10, 2) not null, modify `previewUrl` varchar(255) null, modify `created_at` timestamp null, modify `updated_at` timestamp null',
    bindings: []
  }
]
[2020-04-24T09:45:24.016Z] error Migration failed
[2020-04-24T09:45:24.016Z] error Error: ER_BAD_FT_COLUMN: Column 'size' cannot be part of FULLTEXT index
```

**Steps to reproduce the behavior**

1. Install Strapi with an oldest release (beta.19) with MySQL
2. Migrate to beta.20
3. See error

You can also manually launch `alter table` command  : 
```
alter table `upload_file` modify `alternativeText` varchar(255) null, modify `caption` varchar(255) null, modify `width` int null, modify `height` int null, modify `formats` longtext null, modify `size` decimal(10, 2) not null, modify `previewUrl` varchar(255) null, modify `created_at` timestamp null, modify `updated_at` timestamp null;
```

You will see the error:  `Column 'size' cannot be part of FULLTEXT index`

**Expected behavior**
No error.

**How to Fix**
Remove FULLTEXT index before running an `alter table` command migration.
```
drop index SEARCH_UPLOAD_FILE on upload_file;
```
Then re-run the `alter table` command manually.

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.20
- Database: MySQL 5.7
- Operating system: MacOSX Catalina // debian

**Additional context**
It's not a blocking error, strapi is working with this error, but this can maybe affect performance ?

Thanks,

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#file-model
