### ISSUE TITLE
How to add role when register from local provider

### ISSUE THREAD

**Issue by jackyang1984** [strapi/strapi#5947]
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

When user register, maybe the role is different by the setting default, we can post role type.

**Comment by derrickmehaffy** [comment]
Strapi have already stated they have zero intention of allowing this or selecting the role in register as it's a massive security risk.

**Comment by lauriejim** [comment]
Due to a security risk.
