### ISSUE TITLE
Strapi Image Asset URL Broken Link.

### ISSUE THREAD

**Issue by niyasmhdth** [strapi/strapi#5949]
There is an issue when uploading an asset image in the Strapi admin dashboard. it works after uploading and for about 2 hours, later the image link gets broken, and when we got to asset library, the image is no longer visible and will show broken link icon, also fetching the image through API endpoints the image shows error status code as a response 

NPM version: 6.0.0
Strapi version: 3.0.0-beta.20
Database: Heroku Postgres
Operating system: macOS

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by soupette** [comment]
@niyasmhdth are you using an upload provider like Cloudinary with heroku?

**Comment by niyasmhdth** [comment]
Nope, It was just a basic test, well i started on local environment, made
one object and tried hosting on the heroku free tier with heroku free
postgres database, everything works perfect, set the environment mode to
production, and i can do just how did in local, uploading images from my
system and it shows in the media asset library, everything is fine at the
beginning. Even the endpoints give me data of image and url everything, but
after 2,3 hours the image becomes broken link, and when i check the image
library i get uploaded image names but mot image preview

**Comment by soupette** [comment]
With Heroku you need a provider as changes in the file system is not allowed with Heroku. You can setup Cloudinary with a free tier.

**Comment by niyasmhdth** [comment]
Ok let me try that, thanks for the support

**Comment by niyasmhdth** [comment]
I tried with Cloudinary, when I try uploading image asset by image URL I
get a bad request  error in strapi dashboard

**Comment by WebTerminator** [comment]
@niyasmhdth this might help you: https://medium.com/@kwinten.yc.li/strapi-set-default-file-upload-provider-to-s3-cloudinary-rackspace-5b8ef6f61daa

**Comment by Saurav223** [comment]
> @niyasmhdth are you using an upload provider like Cloudinary with heroku?

yes I am using it and same problem occur
