### ISSUE TITLE
image preview url is wrong with strapi-provider-upload-dropbox

### ISSUE THREAD

**Issue by mkkravchenkoo** [strapi/strapi#5952]
In admin-panel image preview has wrong url
```
<img src="https://www.dropbox.com/s/g2ve8n36igti5dw/my_image.jpeg?raw=1?2029.355000000578" class="sc-psRme cJJQzT">
```

The problem is that dropbox returns link to file with own get-params (`?raw=1`) `https://www.dropbox.com/s/g2ve8n36igti5dw/my_image.jpeg?raw=1`
But when it displays in admin panel link will be changed to `https://www.dropbox.com/s/g2ve8n36igti5dw/my_image.jpeg?raw=1?2029.355000000578`

So, in admin panel we have `?raw=1?2029.355000000578` instead `?raw=1&something=2029.355000000578`

**Steps to reproduce the behavior**

1. install strapi-provider-upload-dropbox
2. create file with configuration in extensions/upload/config/settings.json
3. upload file from admin panel using dropbox
4. tag image has wrong url 

**Additional context**

I found, that `2029.355000000578` is `cacheRef.current`

**Comment by derrickmehaffy** [comment]
`strapi-provider-upload-dropbox` This provider was not created by or maintained by Strapi, please contact the author.
