### ISSUE TITLE
 ERROR:  value too long for type character varying(255) -  postgresql

### ISSUE THREAD

**Issue by ashbuilds** [strapi/strapi#5953]
Adding JSON type column is working fine but after there is a limit to it, I can't add more data after certain point it gives above error. 

**Steps to reproduce the behavior**

1. Add JSON column
2. Try to add multiple JSON object into that column and click save button.
3. It should show above `ERROR:  value too long for type character varying(255) ` in console.

**Expected behavior**
 There should not be any limit to JSON field or if it is then it should be controlled by strapi admin panel currently there is no way to set limit.
<img width="803" alt="Screenshot 2020-04-25 at 8 13 17 PM" src="https://user-images.githubusercontent.com/2686288/80281612-9bcb5800-8736-11ea-8d02-40eb653fdcaf.png">

**System**
- Node.js version: v12.14.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.5
- Database: postgresql
- Operating system: macos

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by ashbuilds** [comment]
@derrickmehaffy Please reopen i added some more details to the issue.

**Comment by derrickmehaffy** [comment]
@ashbuilds please ensure you test this bug with the latest stable version as well (beta.20)

**Comment by ashbuilds** [comment]
@derrickmehaffy Sure i will get back to you. Thanks :)

**Comment by lauriejim** [comment]
Hello! I just tried with the last version of Strapi and it works well.
Can you please try to create a new app with a content type that looks likes yours.
And tell me if it works or not with the last version on your side.
If yes, I suggest you update your application version.

**Comment by derrickmehaffy** [comment]
As we have not heard a reply yet, I'm going to mark this as closed. If you encounter further issues please include the information that Jim asked for and we can re-open this.

**Comment by ashbuilds** [comment]
@lauriejim @derrickmehaffy Yes its working as expected. Thanks :)
