### ISSUE TITLE
Post request returns null field, possibly error in documentation

### ISSUE THREAD

**Issue by mykhailohoy** [strapi/strapi#5958]
**Describe the bug**
Resolving a POST request results in null field of the created component.

**Steps to reproduce the behavior**
Code is the same as the one in [official docs'](https://strapi.io/documentation/3.0.0-beta.x/guides/auth-request.html#login-as-a-reader) section "Create an article".
You will get something like:
```
data {
  created_at: "2020-04-26T15:10:25.919Z",
  title: null,
  content: null,
  id: 34,
  updated_at: "2020-04-26T15:10:25.919Z",
}
```

**Expected behavior**
Field will have the value I passed in my request.

**System**

- Node.js version: 13.12.0
- NPM version: 6.14.4
- Strapi version:  3.0.0-beta.20
- Database: SQLite
- Operating system: Windows 10

**Additional context**
What is the most interesting, If i use code as below:
```
axios.post(url, {
  title: "foo",
  content: "bar"
}
```
it works. Perhaps error in docs?

**Comment by lauriejim** [comment]
Hello! You are mentioning the documentation of the `login` request.
If you scroll down you will see the documentation to create an entry - https://strapi.io/documentation/3.0.0-beta.x/guides/auth-request.html#create-an-article
You will see the request is different.

**Comment by bidoubiwa** [comment]
Hello! 
Maybe there is something I'm missing here, but as per the [documentation of creating an article](https://strapi.io/documentation/developer-docs/latest/guides/auth-request.html#login-as-a-reader): 

```js
import axios from 'axios';

const {data} = await axios
  .post('http://localhost:1337/articles',  {
    data: {
      title: 'my article'
      content: 'my super article content'
    },
    headers: {
      'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTc2OTM4MTUwLCJleHAiOjE1Nzk1MzAxNTB9.UgsjjXkAZ-anD257BF7y1hbjuY3ogNceKfTAQtzDEsU'
    }
  });

console.log(data);
```

I tried with my own content-type `movies`

```javascript
    const res = await axios.post('http://localhost:1337/movies', {
      data: {
        title: "Ariel",
        poster: "https://image.tmdb.org/t/p/w500/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg",
      },
      headers: {
        'Authorization': `Bearer ${token.data.jwt}`,
      }
    })
```

res looks like this: 
```javascript
  data: {
    id: 7,
    title: null,
    overview: null,
    poster: null,
    created_at: '2021-04-04T14:34:11.898Z',
    updated_at: '2021-04-04T14:34:11.898Z'
  }
```

But, if I add it the same way you would login: 

```javascript
const res = await axios.post('http://localhost:1337/movies', {
      id: 10,
      title: "Ariel",
      poster: "https://image.tmdb.org/t/p/w500/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg",
      headers: {
        'Authorization': `Bearer ${token.data.jwt}`,
        'Content-Type': 'application/json'
      }
    }
```

Then my return is the followin: 
```js
  data: {
    id: 8,
    title: 'Ariel',
    overview: null,
    poster: 'https://image.tmdb.org/t/p/w500/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg',
    created_at: '2021-04-04T14:36:57.078Z',
    updated_at: '2021-04-04T14:36:57.078Z'
  }
```



But when I read your last answer on this issue: 

> Hello! You are mentioning the documentation of the login request.
If you scroll down you will see the documentation to create an entry - https://strapi.io/documentation/3.0.0-beta.x/guides/auth-request.html#create-an-article
You will see the request is different.

You redirect to the example that returns null in every field.

**Comment by derrickmehaffy** [comment]
https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#upload-files-related-to-an-entry

**Comment by bidoubiwa** [comment]
I'm not sure I understand the linked doc. I'm not trying to add a file. Sorry if i'm missing something

**Comment by derrickmehaffy** [comment]
Apologizes I made the assumption with the .jpg that were were trying to upload files. Your default axios config isn't set to send the data as `application/json` and is most likely trying to send it as either `form-data` or `x-www-form-urlencoded`. Form data is only supported during a file upload, and by adding the `Content-type` header axios converts the data object into `application/json`.

Either you need to send that header with every request, update the axios config to automatically make requests as `application/json`, or you can try passing the data payload through a `JSON.stringify()` which axios should send as `application/json`.

**Comment by derrickmehaffy** [comment]
See an example of this here: https://github.com/axios/axios/issues/827#issuecomment-338290911

**Comment by jagmeet039** [comment]
![Capture](https://user-images.githubusercontent.com/67494943/149204982-213e80be-a22a-4681-82ba-30c8c1c0e9e7.PNG)

Not able to post article. Tried with both kind of users (Author and Reader) even though giving permission in setting but still not able to post it.

Getting error : 400 Validation Error, Missing data payload in the request body

I am able to acheive a GET request and able to fetch the post created manually (using Create New Entry Option) but when trying to achieve it through POST method by properly providing the Authorization token also, not able to do it.

Can anybody help me with this?
