### ISSUE TITLE
Delete field in admin interface doesn't affect database

### ISSUE THREAD

**Issue by Advoskr** [strapi/strapi#5959]
**Describe the bug**
Hi there and thank you for this great product.

I have and issue: if i want to recreate some field with another type (say, i had a field `alias` of type text, now i want to make a collection of `aliases` and therefore change the field to type `relation`). But, when i delete this field and submit changes, databse table isn't modified. After i create a field with same name i get an error in interface for creating new items in collection. 

**Steps to reproduce the behavior**

1. Create a collection, say, `Article`
2. Create text field `Alias` in collection `Article`
3. Add some data to `Article`. Some of new items must have `Alias`.
4. Remove field `Alias` in collection `Article`. Do not change any data before this change!
5. Save changes.
6. Create collection `Alias`.
7. Create relation field `Alias` in collection `Article`, which relates to collection `Alias`
8. Open items editor for collection `Article` and see error.

**Expected behavior**
Db column is deleted on step 4 and re-created on step 7. Data of this column'll be lost, but the collection shall work after all the steps above.

**System**

- Node.js version: included in official docker image
- NPM version: included in official docker image
- Strapi version: 3.0.0-beta 20
- Database: postgres latest
- Operating system: docker and debian 9.

**Additional context**

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/1114
