### ISSUE TITLE
Autoreload and polling 

### ISSUE THREAD

**Issue by rroblik** [strapi/strapi#596]
**Node.js version**:
`v8.9.4`

**npm version**:
`5.6.0`

**Strapi version**:
`3.0.0-alpha.9.2`

**Operating system**:
`Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux `
(inside Vmware, Windows 8 host, shared folder)

**Do you want to request a *feature* or report a *bug*?**
Feature (maybe a bug)

**What is the current behavior?**
Server not restarting automatically when saving files in dev env.

**What is the expected behavior?**
Server restarting automatically on file save.

Note : As Strapi use `fs` and as it's NOT fully compatible on NFS systems, maybe use polling, and allow an "poll" option in strapi start command ?
`strapi start --poll`

EDIT : working out of the box sometimes ... randomly !

Regards

**Comment by lauriejim** [comment]
Hi @rroblik can you be more precise about what you want with `--poll` tag please.
And what do you suggest to watch files for Strapi restart ?

**Comment by lauriejim** [comment]
@rroblik Can you give us an update plase

**Comment by rroblik** [comment]
Hi, sorry for the delay.

I consider this as not a bug ; working fine.

Regards

**Comment by stunningpixels** [comment]
I am also experiencing this, with settings:
  "autoReload": {
    "enabled": true
  },

Node.js version:
v9.8.0

npm version:
5.6.0

Strapi version:
3.0.0-alpha.11.1

Operating system:
macOS 10.13.2 (17C88)

**Comment by PaulWeinsberg** [comment]
This problem appear when you run npm commands inside node container on MacOSX.

Fixed with process env variable

```
CHOKIDAR_USEPOLLING=true npm run $task
```

It's possible to solve it easily for strapi team :

line 120 in node_modules/strapi/lib/commands/develop.js for example, with additional option.

```javascript
  const watcher = chokidar.watch(dir, {
    ignoreInitial: true,
    usePolling: true, // Option to add
    ignored: [
      /(^|[/\\])\../,
      /tmp/,
      '**/admin',
      '**/admin/**',
      'extensions/**/admin',
      'extensions/**/admin/**',
      '**/documentation',
      '**/documentation/**',
      '**/node_modules',
      '**/node_modules/**',
      '**/plugins.json',
      '**/index.html',
      '**/public',
      '**/public/**',
      '**/*.db*',
      '**/exports/**',
      ...watchIgnoreFiles,
    ],
  });
```

**Comment by derrickmehaffy** [comment]
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by PaulWeinsberg** [comment]
Hello !

Thanks, i do this quickly.

Have a good day too.
