### ISSUE TITLE
file upload with ref and refId doesnt correctly save to collection component

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#5961]
**Describe the bug**
I am able to upload a file using the following fields:
ref: "association" (my collection name)
refId: "5da979e69bd03850f90e35b3" (the association id)
field: "amendments" (the component name)
title: "test file upload" (self explanatory)
files: a-test-file.txt (the file that has been uploaded)

**Steps to reproduce the behavior**
I POST to `/upload` and the file correctly saves to the media library, and "partially" saves to association. however, the entry in the "association" collection record contains no file id, and no title (a custom component field name), and no file attached, it only contains a placeholder and displays "Create and entry" text in place of the id.

the console log response contains this object:
```
alternativeText: null
caption: null
createdAt: "2020-04-26T19:43:08.484Z"
ext: ".txt"
hash: "a-test-file_c173e9bc72"
height: null
id: "5ea5e44cdf1d550c62fbd3f1"
mime: "text/plain"
name: "a-test-file"
provider: "local"
related: Array(1)
0: {__contentType: "Association",images: Array(6), _id: "5da979e69bd03850f90e35b3", …}
length: 1
__proto__: Array(0)
size: 0.02
updatedAt: "2020-04-26T19:43:08.501Z"
url: "/uploads/a-test-file_c173e9bc72.txt"
width: null
__v: 0
_id: "5ea5e44cdf1d550c62fbd3f1"
```
the response indicates that it reached the correct record, but for some reason the component portion is not saved.

**Expected behavior**
I expect the file to be completely referenced in the "association" collection record component element. 

**Screenshots**
as you can see in this screenshot of the association record, some amendments documents already exist by attaching them directly via the record interface. the last item "create an entry" was created by posting to /upload and it did not save correctly as the ones using the record interface did.
![amendment-entry-incomplete](https://user-images.githubusercontent.com/1257358/80318815-69445c80-8815-11ea-8707-46903021f924.png)

**Code snippets**
this is the "association" partial of the component named amendments:
```
    "amendments": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
```

this is the component called document:
```
{
  "connection": "default",
  "collectionName": "components_document_documents",
  "info": {
    "name": "document",
    "description": "",
    "icon": "file-alt"
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "file": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }
  }
}
```

**System**

Node.js version: v10.16.3
NPM version: 6.9.0
Strapi version: Strapi v3.0.0-beta.20
Database: mongo v4.0.12
Operating system: ubuntu 18.04

**Additional context**
perhaps what i am trying to do is not available at this stage. if so, i would appreciate some steps to make this work completely.

thank you

**Comment by alexandrebodin** [comment]
Hi, If you want to set the media on a component the ref and refId must point to the component your want to upload the image too :) 

E.G

```js
axios.post('/upload', {
  ref: 'document.document',
  refId: 'compoId',
  field: 'file'
//....
})
```

Another  way of doing this is to upload the image first and then create the entry with the media id:

```json
{
  "amendments": [
    { "file": 1 },
    { "file": 2 }
  ]
}
```

Closing this issue as it is more of a usage question ;)

**Comment by hkovacs** [comment]
@alexandrebodin Thanks so much!

how is the compoId available? is there an api way to get the compoId? i dont see a controller for components. do i use the "association" controller?

thank you!

**Comment by alexandrebodin** [comment]
When fetching the contentType you will have the compose and there ids. If you just created them you can use the response to get the ids. You might also consider uplaoding the files at the same time. You can read more [here](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#upload-file-during-entry-creation)

Have fun ;) !

**Comment by hkovacs** [comment]
> When fetching the contentType you will have the compose and there ids. If you just created them you can use the response to get the ids. You might also consider uplaoding the files at the same time. You can read more [here](https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#upload-file-during-entry-creation)
> 
> Have fun ;) !

the form is for uploading a file to a new component record for an existing association entry and i have used what i could from the upload documentation to get as far as i have till now.

i think using component "document.document" is not going to work as I must connect the uploaded file to a specific association while the component record does not exist.

based on what i see in roles permissions, i think i will continue saving to the association and then do an updatecomponent if the response has the component id. i will comment here with the results.

thank you!

**Comment by hkovacs** [comment]
@alexandrebodin i have tried following this page https://strapi.io/documentation/3.0.0-beta.x/concepts/models.html#components to update an existing collection entry with a new component entry. i am not successful. is there a page that covers this capability? or perhaps an api route for creating component? ive only found this page https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/config/routes.json which does not have create comopnent.

thank you

**Comment by hkovacs** [comment]
the following are my steps for attempting to create a new component entry when updating a content record.

step 1: upload file. this works and i receive a status 200 and the contentType object of the upload file record.
step 2: create new component record while updating existing content record: 
- i do a POST as follows:
```
    let newComponent =  {
        title: "test", 
        file: "5eaad06a80e2bd0bddf08bd4" // this is the id of the just uploaded file in step 1
    }
    const jwt = getJwt();

    var data = {
        'PUT',
        headers: {
            Accept: 'application/json',
            'Content-Type': 'application/json',
            'Authorization': jwt,
        },
        body: JSON.stringify(newComponent)
    };

    const response = await fetch(`${process.env.REACT_APP_API_ENDPOINT}/associations/5da979e69bd03850f90e35b3`, data);
```

i receive a response.status 200 from this, but when i check the db and association record there is no successful saving of new component record containing my newComponent data.

i am pretty sure that i am misunderstanding the guide and that theres something to point out that i missed.

thank you.

**Comment by alexandrebodin** [comment]
Hey to achieve what you want to do you will need to first fetch the contentType entry and then add the component to the requiredField


```js
import fetch from 'fetch';

const fileId = uploadFile();

const contentTypeEntry = fetchEntry(id);

// if single compo
contentTypeEntry.compoField = {
 title: 'new compo',
 field: fileId
};

// if repeatable compo
contentTypeEntry.componentField.push({
  title: 'new compo',
   file: fileId
});

const res = await fetch('/associations/associationId', {
 method: 'PUT',
 body: JSON.stringify(entry)
})
```

**Comment by Capossito** [comment]
how do i access the refid and the field from a custom upload provider? i used to get from file.related[0].field and .refid, with the new update i get undefined now.

**Comment by hkovacs** [comment]
> how do i access the refid and the field from a custom upload provider? i used to get from file.related[0].field and .refid, with the new update i get undefined now.

please show your code so you can be answered properly.

**Comment by Capossito** [comment]
> > how do i access the refid and the field from a custom upload provider? i used to get from file.related[0].field and .refid, with the new update i get undefined now.
> 
> please show your code so you can be answered properly.

before the new update i could get the ref and field name

`

  
  init: config => {

    const S3 = new AWS.S3({
      apiVersion: '2006-03-01',
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
      region: config.region,
    });

    return {
      upload: file => {
        return new Promise((resolve, reject) => {
          
          const bkt = config.params.bucket;
          const tag = file.related[0].field;
          const ref = file.related[0].refId;
          const path = `${tag}/${ref}/`;
          S3.upload(
            {
              Bucket: bkt,
              Key: `${path}${file.hash}${file.ext}`,
              Body: Buffer.from(file.buffer, 'binary'),
              ContentType: file.mime,
            },
            (err, data) => {
              if (err) {
                return reject(err);
              }
              file.url = `https://mycdn/${data.key}`;
              file.tag = tag;
              resolve();
            }
          );
        });
      },
      delete: file => {
        return new Promise((resolve, reject) => {
          // delete file on S3 bucket
          const bkt = config.params.bucket;
          S3.deleteObject(
            {
              Bucket: bkt,
              Key: `${tag}/${file.hash}${file.ext}`,
            },
            (err, data) => {
              if (err) {
                return reject(err);
              }
              resolve();
            }
          );
        });
      },
    };
  },
};`

**Comment by hkovacs** [comment]
> > > how do i access the refid and the field from a custom upload provider? i used to get from file.related[0].field and .refid, with the new update i get undefined now.
> > 
> > 
> > please show your code so you can be answered properly.
> 
> before the new update i could get the ref and field name
> 
> `
> 
> init: config => {
> 
> ```
> const S3 = new AWS.S3({
>   apiVersion: '2006-03-01',
>   accessKeyId: config.accessKeyId,
>   secretAccessKey: config.secretAccessKey,
>   region: config.region,
> });
> 
> return {
>   upload: file => {
>     return new Promise((resolve, reject) => {
>       
>       const bkt = config.params.bucket;
>       const tag = file.related[0].field;
>       const ref = file.related[0].refId;
>       const path = `${tag}/${ref}/`;
>       S3.upload(
>         {
>           Bucket: bkt,
>           Key: `${path}${file.hash}${file.ext}`,
>           Body: Buffer.from(file.buffer, 'binary'),
>           ContentType: file.mime,
>         },
>         (err, data) => {
>           if (err) {
>             return reject(err);
>           }
>           file.url = `https://mycdn/${data.key}`;
>           file.tag = tag;
>           resolve();
>         }
>       );
>     });
>   },
>   delete: file => {
>     return new Promise((resolve, reject) => {
>       // delete file on S3 bucket
>       const bkt = config.params.bucket;
>       S3.deleteObject(
>         {
>           Bucket: bkt,
>           Key: `${tag}/${file.hash}${file.ext}`,
>         },
>         (err, data) => {
>           if (err) {
>             return reject(err);
>           }
>           resolve();
>         }
>       );
>     });
>   },
> };
> ```
> 
> },
> };`

the refid and field values are provided by you. you have access to them from the start. if your use case differs from this discussion, then best to start a new discussion instead of taking this one off track.
