### ISSUE TITLE
Image preview disappears from collection creation

### ISSUE THREAD

**Issue by Fezzzi** [strapi/strapi#5967]
Image preview disappears from collection creation form after wrapping and unwrapping containing component. Images are uploaded after saving the form nevertheless.

**Steps to reproduce the behavior**

1. Create `testComponent` component with single media field
2. Create `testCollection` collection with single field of component type, choose existing component and select `test` component with repeatable component setting.
3. Put several `testComponent` entries in new `testCollection` entry form
4. Choose random 'testComponent' entry and fill its image. See the input field's preview.
5. Wrap and unwrap the component's configuration.
6. The image preview is now blank.

**Expected behavior**
The image preview to display the image selected.

**Screenshots**
![Image_preview_bug](https://user-images.githubusercontent.com/36623372/80360600-df7da900-887f-11ea-942a-eeea75d4b814.gif)

**Code snippets**
`components/components/testComponent`: 
```
{
  "connection": "default",
  "collectionName": "components_components_testComponent",
  "info": {
    "name": "testComponent",
    "icon": "file-image"
  },
  "options": {},
  "attributes": {
    "Field": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": true
    }
  }
}
```
`api/testCollection/models/testCollection.settings.json`:
```
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "testCollections",
  "info": {
    "name": "testCollection"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Field": {
      "type": "component",
      "repeatable": true,
      "component": "components.testComponent"
    }
  }
}
```

**System**
Tried on both `3.0.0-beta.20` and `3.0.0-beta.19.5` versions.

**Comment by soupette** [comment]
@Fezzi from the Gif that you provided it appears that you haven't rebuid your administration panel. Can you try to upgrade to the latest version of Strapi then tun `yarn strapi build --clean` and check if the problem persists?

**Comment by Fezzzi** [comment]
Was using `npm strapi build`, running `yarn strapi build --clean` with `3.0.0-beta.20` helped indeed, thank you!
