### ISSUE TITLE
GraphQL Mutation don't return the Payload

### ISSUE THREAD

**Issue by veitbjarsch** [strapi/strapi#5970]
**Describe the bug**
Since beta 19 a mutation don't return any payload on a successful execution (queries still do). I've tested this behavior in 18.8 (still working) and 19.3 (did not work anymore). 

**Steps to reproduce the behavior**

1. Create a new project
2. Create a custom api endpoint with aggregations and a custom controller
3. execute a graphql query against the custom controller

**Expected behavior**
payload should be returned on a successfull mutation

**Code snippets**
I can do a workaround with specifying the collection name at the return statement of the mutation controller
```
async createByUser(ctx) {
    ...
    return {<COLLECTION NAME>: await service.create(body)};
  },
```

**System**

- Node.js version: v12
- Strapi version: Beta 20
- Database: sql lite
- Operating system: mac os

**Comment by alexandrebodin** [comment]
Hi, are you talkin gabout custom mutations ?

**Comment by veitbjarsch** [comment]
Yes I'm talking about custom ones. I've implemented these routes several versions ago, but in Beta19 they stoped working as expected until I've wrapped the result with an object with the collection name as key. It maybe ist on purpose, but then there should be some notice in the migration guide. Also queries are still working in the same way as before (returning directly the result without the wrapping object). 

Maybe also the solution is to clarify the graphql queries and mutations more in the documentation.

**Comment by alexandrebodin** [comment]
@veitbjarsch If you are create custom mutations (that don't override any generated one) you should be able to return whatever you want (so this would be a bug). But if it is to exteend existing mutations then it should keep the same response format. 

Can you share and more complete schema.graphql.js file so we can reproduce the bug more easily ? (no need for the code inside the mutation just the schema ;))

**Comment by veitbjarsch** [comment]
the schema:
```
  definition: `
    type PublicWishPayload {
      wish: PublicWish
    }

    type PublicWish {
      id: ID!
      title: String!
      description: String
      image: UploadFile
      order: Int
    }
  `,
  mutation: `
    subscribeWish(input: subscribeWishInput): PublicWishPayload
  `,
  resolver: {
    Mutation: {
      subscribeWish: {
        resolver: 'Wish.subscribeWish'
      },
    },
  }
```

the controller before beta19:
```
async subscribeWish(ctx) {
    ...
    return  await strapi.query('wish').update(...); 
  },
```

the controller after beta19:
```
async subscribeWish(ctx) {
    ...
    return { wish: await strapi.query('wish').update(...) };
  },
```

I mean it does make sense to return the key wish inside the controller. But I'm wondering why this change was never mentioned. The "old" style still works inside my query controllers.

**Comment by alexandrebodin** [comment]
This is an issue that's why it wasn't mentionned :)

**Comment by alexandrebodin** [comment]
Hi @veitbjarsch After reading your example again, I think this is indeed what we should be doing but we should have documented it :). Can you share a query example that still works with "old" style please ?

**Comment by alexandrebodin** [comment]
Hi @veitbjarsch I will close this PR as the behavior is as we expect it :)
