### ISSUE TITLE
error: column "id" specified more than once

### ISSUE THREAD

**Issue by Guang0404** [strapi/strapi#5973]
Yarn version: 1.21.1
Node version: 12.13.0
Platform: win32 x64
Database : PostgreSQL 12.1
OS : Windows10

What is the current behavior?

"strapi develop" crashes on start with the following error message:

> [2020-04-27T20:24:57.777Z] debug ⛔️ Server wasn't able to start properly.
[2020-04-27T20:24:57.778Z] error error: column "id" specified more than once
    at Connection.parseE (...path\backend\node_modules\pg\lib\connection.js:600:48)
    at Connection.parseMessage (...path\backend\node_modules\pg\lib\connection.js:399:19)
    at Socket.<anonymous> (..path\backend\node_modules\pg\lib\connection.js:115:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)

**Steps to reproduce the behavior**
I was making new content types in the content type builder. However, to the best of my knowledge, I have not created any fields with the name "id." 

Here is my schema list of the content types :

`input ArchiveInput {
  uid: String
  post_categories: [ID]
}

type Archives {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  uid: String
  post_categories(sort: String, limit: Int, start: Int, where: JSON): [PostCategory]
}

type ComponentContentImageHeadingDescription {
  id: ID!
  heading: String
  description: String
  img(sort: String, limit: Int, start: Int, where: JSON): [UploadFile]
}

input ComponentContentImageHeadingDescriptionInput {
  img: [ID]
  heading: String
  description: String
}

input createFileInput {
  data: FileInput
}

type createFilePayload {
  file: UploadFile
}

input createPageInput {
  data: PageInput
}

type createPagePayload {
  page: Page
}

input createPostCategoryInput {
  data: PostCategoryInput
}

type createPostCategoryPayload {
  postCategory: PostCategory
}

input createPostInput {
  data: PostInput
}

type createPostPayload {
  post: Post
}

input createRoleInput {
  data: RoleInput
}

type createRolePayload {
  role: UsersPermissionsRole
}

input createSubscriberInput {
  data: SubscriberInput
}

type createSubscriberPayload {
  subscriber: Subscribers
}

input createUserInput {
  data: UserInput
}

type createUserPayload {
  user: UsersPermissionsUser
}

"""
A date string, such as 2007-12-03, compliant with the `full-date` format
outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for
representation of dates and times using the Gregorian calendar.
"""
scalar Date

"""
A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the
`date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO
8601 standard for representation of dates and times using the Gregorian calendar.
"""
scalar DateTime

type deleteArchivePayload {
  archive: Archives
}

input deleteFileInput {
  where: InputID
}

type deleteFilePayload {
  file: UploadFile
}

type deleteHomePayload {
  home: Home
}

input deletePageInput {
  where: InputID
}

type deletePagePayload {
  page: Page
}

input deletePostCategoryInput {
  where: InputID
}

type deletePostCategoryPayload {
  postCategory: PostCategory
}

input deletePostInput {
  where: InputID
}

type deletePostPayload {
  post: Post
}

input deleteRoleInput {
  where: InputID
}

type deleteRolePayload {
  role: UsersPermissionsRole
}

type deleteSiteInfoPayload {
  siteInfo: SiteInfo
}

input deleteSubscriberInput {
  where: InputID
}

type deleteSubscriberPayload {
  subscriber: Subscribers
}

input deleteUserInput {
  where: InputID
}

type deleteUserPayload {
  user: UsersPermissionsUser
}

input editArchiveInput {
  uid: String
  post_categories: [ID]
}

input editComponentContentImageHeadingDescriptionInput {
  id: ID
  img: [ID]
  heading: String
  description: String
}

input editFileInput {
  name: String
  alternativeText: String
  caption: String
  width: Int
  height: Int
  formats: JSON
  hash: String
  ext: String
  mime: String
  size: Float
  url: String
  previewUrl: String
  provider: String
  provider_metadata: JSON
  related: [ID]
}

input editHomeInput {
  title: String
  description: String
}

input editPageInput {
  uid: String
  title: String
  description: String
  featured_img: ID
  content: [PageContentDynamicZoneInput!]
}

input editPostCategoryInput {
  uid: String
  title: String
  description: String
  featured_img: ID
  posts: [ID]
}

input editPostInput {
  uid: String
  title: String
  description: String
  post_categories: [ID]
  featured_img: ID
  post_content: String
}

input editRoleInput {
  name: String
  description: String
  type: String
  permissions: [ID]
  users: [ID]
}

input editSiteInfoInput {
  title: String
  description: String
  headline: String
  email: String
  twitter_handle: String
  instagram_handle: String
  googleAnalyticsID: String
  facebook_handle: String
}

input editSubscriberInput {
  first_name: String
  last_name: String
  email: String
  phone_number: Long
  profile_picture: [ID]
  date_of_birth: Date
  gender: ENUM_SUBSCRIBERS_GENDER
  password: String
  username: String
}

input editUserInput {
  username: String
  email: String
  provider: String
  password: String
  resetPasswordToken: String
  confirmed: Boolean
  blocked: Boolean
  role: ID
}

enum ENUM_SUBSCRIBERS_GENDER {
  male
  female
  other
  prefer_not_to_reveal
}

input FileInput {
  name: String!
  alternativeText: String
  caption: String
  width: Int
  height: Int
  formats: JSON
  hash: String!
  ext: String
  mime: String!
  size: Float!
  url: String!
  previewUrl: String
  provider: String!
  provider_metadata: JSON
  related: [ID]
}

type ForgotPassword {
  ok: Boolean
}

type Home {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  title: String
  description: String
}

input HomeInput {
  title: String
  description: String
}

input InputID {
  id: ID!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON

"""The `Long` scalar type represents 52-bit integers"""
scalar Long

union Morph = UsersPermissionsMe | UsersPermissionsMeRole | UsersPermissionsLoginPayload | ForgotPassword | Archives | updateArchivePayload | deleteArchivePayload | Home | updateHomePayload | deleteHomePayload | Page | PageConnection | PageAggregator | PageGroupBy | PageConnectionId | PageConnectionCreated_at | PageConnectionUpdated_at | PageConnectionUid | PageConnectionTitle | PageConnectionDescription | PageConnectionFeatured_img | createPagePayload | updatePagePayload | deletePagePayload | PostCategory | PostCategoryConnection | PostCategoryAggregator | PostCategoryGroupBy | PostCategoryConnectionId | PostCategoryConnectionCreated_at | PostCategoryConnectionUpdated_at | PostCategoryConnectionUid | PostCategoryConnectionTitle | PostCategoryConnectionDescription | PostCategoryConnectionFeatured_img | createPostCategoryPayload | updatePostCategoryPayload | deletePostCategoryPayload | Post | PostConnection | PostAggregator | PostGroupBy | PostConnectionId | PostConnectionCreated_at | PostConnectionUpdated_at | PostConnectionUid | PostConnectionTitle | PostConnectionDescription | PostConnectionFeatured_img | PostConnectionPost_content | createPostPayload | updatePostPayload | deletePostPayload | SiteInfo | updateSiteInfoPayload | deleteSiteInfoPayload | Subscribers | SubscribersConnection | SubscribersAggregator | SubscribersGroupBy | SubscribersConnectionId | SubscribersConnectionCreated_at | SubscribersConnectionUpdated_at | SubscribersConnectionFirst_name | SubscribersConnectionLast_name | SubscribersConnectionEmail | SubscribersConnectionPhone_number | SubscribersConnectionDate_of_birth | SubscribersConnectionGender | SubscribersConnectionPassword | SubscribersConnectionUsername | createSubscriberPayload | updateSubscriberPayload | deleteSubscriberPayload | UploadFile | UploadFileConnection | UploadFileAggregator | UploadFileAggregatorSum | UploadFileAggregatorAvg | UploadFileAggregatorMin | UploadFileAggregatorMax | UploadFileGroupBy | UploadFileConnectionId | UploadFileConnectionCreated_at | UploadFileConnectionUpdated_at | UploadFileConnectionName | UploadFileConnectionAlternativeText | UploadFileConnectionCaption | UploadFileConnectionWidth | UploadFileConnectionHeight | UploadFileConnectionFormats | UploadFileConnectionHash | UploadFileConnectionExt | UploadFileConnectionMime | UploadFileConnectionSize | UploadFileConnectionUrl | UploadFileConnectionPreviewUrl | UploadFileConnectionProvider | UploadFileConnectionProvider_metadata | createFilePayload | updateFilePayload | deleteFilePayload | UsersPermissionsPermission | UsersPermissionsRole | UsersPermissionsRoleConnection | UsersPermissionsRoleAggregator | UsersPermissionsRoleGroupBy | UsersPermissionsRoleConnectionId | UsersPermissionsRoleConnectionName | UsersPermissionsRoleConnectionDescription | UsersPermissionsRoleConnectionType | createRolePayload | updateRolePayload | deleteRolePayload | UsersPermissionsUser | UsersPermissionsUserConnection | UsersPermissionsUserAggregator | UsersPermissionsUserGroupBy | UsersPermissionsUserConnectionId | UsersPermissionsUserConnectionCreated_at | UsersPermissionsUserConnectionUpdated_at | UsersPermissionsUserConnectionUsername | UsersPermissionsUserConnectionEmail | UsersPermissionsUserConnectionProvider | UsersPermissionsUserConnectionConfirmed | UsersPermissionsUserConnectionBlocked | UsersPermissionsUserConnectionRole | createUserPayload | updateUserPayload | deleteUserPayload | ComponentContentImageHeadingDescription

type Mutation {
  updateArchive(input: updateArchiveInput): updateArchivePayload
  deleteArchive: deleteArchivePayload
  updateHome(input: updateHomeInput): updateHomePayload
  deleteHome: deleteHomePayload
  createPage(input: createPageInput): createPagePayload
  updatePage(input: updatePageInput): updatePagePayload
  deletePage(input: deletePageInput): deletePagePayload
  createPostCategory(input: createPostCategoryInput): createPostCategoryPayload
  updatePostCategory(input: updatePostCategoryInput): updatePostCategoryPayload
  deletePostCategory(input: deletePostCategoryInput): deletePostCategoryPayload
  createPost(input: createPostInput): createPostPayload
  updatePost(input: updatePostInput): updatePostPayload
  deletePost(input: deletePostInput): deletePostPayload
  updateSiteInfo(input: updateSiteInfoInput): updateSiteInfoPayload
  deleteSiteInfo: deleteSiteInfoPayload
  createSubscriber(input: createSubscriberInput): createSubscriberPayload
  updateSubscriber(input: updateSubscriberInput): updateSubscriberPayload
  deleteSubscriber(input: deleteSubscriberInput): deleteSubscriberPayload

  """Create a new role"""
  createRole(input: createRoleInput): createRolePayload

  """Update an existing role"""
  updateRole(input: updateRoleInput): updateRolePayload

  """Delete an existing role"""
  deleteRole(input: deleteRoleInput): deleteRolePayload

  """Create a new user"""
  createUser(input: createUserInput): createUserPayload

  """Update an existing user"""
  updateUser(input: updateUserInput): updateUserPayload

  """Delete an existing user"""
  deleteUser(input: deleteUserInput): deleteUserPayload
  upload(refId: ID, ref: String, field: String, source: String, file: Upload!): UploadFile!
  multipleUpload(refId: ID, ref: String, field: String, source: String, files: [Upload]!): [UploadFile]!
  login(input: UsersPermissionsLoginInput!): UsersPermissionsLoginPayload!
  register(input: UserInput!): UsersPermissionsLoginPayload!
  forgotPassword(email: String!): ForgotPassword
  changePassword(password: String!, passwordConfirmation: String!, code: String!): UsersPermissionsLoginPayload
  emailConfirmation(confirmation: String!): UsersPermissionsLoginPayload
}

type Page {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  uid: String
  title: String
  description: String
  featured_img: UploadFile
  content: [PageContentDynamicZone]
}

type PageAggregator {
  count: Int
  totalCount: Int
}

type PageConnection {
  values: [Page]
  groupBy: PageGroupBy
  aggregate: PageAggregator
}

type PageConnectionCreated_at {
  key: DateTime
  connection: PageConnection
}

type PageConnectionDescription {
  key: String
  connection: PageConnection
}

type PageConnectionFeatured_img {
  key: ID
  connection: PageConnection
}

type PageConnectionId {
  key: ID
  connection: PageConnection
}

type PageConnectionTitle {
  key: String
  connection: PageConnection
}

type PageConnectionUid {
  key: String
  connection: PageConnection
}

type PageConnectionUpdated_at {
  key: DateTime
  connection: PageConnection
}

union PageContentDynamicZone = ComponentContentImageHeadingDescription

"""Input type for dynamic zone content of Page"""
scalar PageContentDynamicZoneInput

type PageGroupBy {
  id: [PageConnectionId]
  created_at: [PageConnectionCreated_at]
  updated_at: [PageConnectionUpdated_at]
  uid: [PageConnectionUid]
  title: [PageConnectionTitle]
  description: [PageConnectionDescription]
  featured_img: [PageConnectionFeatured_img]
}

input PageInput {
  uid: String
  title: String
  description: String
  featured_img: ID
  content: [PageContentDynamicZoneInput!]
}

type Post {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  uid: String
  title: String
  description: String
  featured_img: UploadFile
  post_content: String
  post_categories(sort: String, limit: Int, start: Int, where: JSON): [PostCategory]
}

type PostAggregator {
  count: Int
  totalCount: Int
}

type PostCategory {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  uid: String
  title: String
  description: String
  featured_img: UploadFile
  posts(sort: String, limit: Int, start: Int, where: JSON): [Post]
}

type PostCategoryAggregator {
  count: Int
  totalCount: Int
}

type PostCategoryConnection {
  values: [PostCategory]
  groupBy: PostCategoryGroupBy
  aggregate: PostCategoryAggregator
}

type PostCategoryConnectionCreated_at {
  key: DateTime
  connection: PostCategoryConnection
}

type PostCategoryConnectionDescription {
  key: String
  connection: PostCategoryConnection
}

type PostCategoryConnectionFeatured_img {
  key: ID
  connection: PostCategoryConnection
}

type PostCategoryConnectionId {
  key: ID
  connection: PostCategoryConnection
}

type PostCategoryConnectionTitle {
  key: String
  connection: PostCategoryConnection
}

type PostCategoryConnectionUid {
  key: String
  connection: PostCategoryConnection
}

type PostCategoryConnectionUpdated_at {
  key: DateTime
  connection: PostCategoryConnection
}

type PostCategoryGroupBy {
  id: [PostCategoryConnectionId]
  created_at: [PostCategoryConnectionCreated_at]
  updated_at: [PostCategoryConnectionUpdated_at]
  uid: [PostCategoryConnectionUid]
  title: [PostCategoryConnectionTitle]
  description: [PostCategoryConnectionDescription]
  featured_img: [PostCategoryConnectionFeatured_img]
}

input PostCategoryInput {
  uid: String
  title: String
  description: String
  featured_img: ID
  posts: [ID]
}

type PostConnection {
  values: [Post]
  groupBy: PostGroupBy
  aggregate: PostAggregator
}

type PostConnectionCreated_at {
  key: DateTime
  connection: PostConnection
}

type PostConnectionDescription {
  key: String
  connection: PostConnection
}

type PostConnectionFeatured_img {
  key: ID
  connection: PostConnection
}

type PostConnectionId {
  key: ID
  connection: PostConnection
}

type PostConnectionPost_content {
  key: String
  connection: PostConnection
}

type PostConnectionTitle {
  key: String
  connection: PostConnection
}

type PostConnectionUid {
  key: String
  connection: PostConnection
}

type PostConnectionUpdated_at {
  key: DateTime
  connection: PostConnection
}

type PostGroupBy {
  id: [PostConnectionId]
  created_at: [PostConnectionCreated_at]
  updated_at: [PostConnectionUpdated_at]
  uid: [PostConnectionUid]
  title: [PostConnectionTitle]
  description: [PostConnectionDescription]
  featured_img: [PostConnectionFeatured_img]
  post_content: [PostConnectionPost_content]
}

input PostInput {
  uid: String
  title: String
  description: String
  post_categories: [ID]
  featured_img: ID
  post_content: String
}

type Query {
  archive: Archives
  home: Home
  page(id: ID!): Page
  pages(sort: String, limit: Int, start: Int, where: JSON): [Page]
  pagesConnection(sort: String, limit: Int, start: Int, where: JSON): PageConnection
  postCategory(id: ID!): PostCategory
  postCategories(sort: String, limit: Int, start: Int, where: JSON): [PostCategory]
  postCategoriesConnection(sort: String, limit: Int, start: Int, where: JSON): PostCategoryConnection
  post(id: ID!): Post
  posts(sort: String, limit: Int, start: Int, where: JSON): [Post]
  postsConnection(sort: String, limit: Int, start: Int, where: JSON): PostConnection
  siteInfo: SiteInfo
  subscriber(id: ID!): Subscribers
  subscribers(sort: String, limit: Int, start: Int, where: JSON): [Subscribers]
  subscribersConnection(sort: String, limit: Int, start: Int, where: JSON): SubscribersConnection
  files(sort: String, limit: Int, start: Int, where: JSON): [UploadFile]
  filesConnection(sort: String, limit: Int, start: Int, where: JSON): UploadFileConnection
  role(id: ID!): UsersPermissionsRole

  """
  Retrieve all the existing roles. You can't apply filters on this query.
  """
  roles(sort: String, limit: Int, start: Int, where: JSON): [UsersPermissionsRole]
  rolesConnection(sort: String, limit: Int, start: Int, where: JSON): UsersPermissionsRoleConnection
  user(id: ID!): UsersPermissionsUser
  users(sort: String, limit: Int, start: Int, where: JSON): [UsersPermissionsUser]
  usersConnection(sort: String, limit: Int, start: Int, where: JSON): UsersPermissionsUserConnection
  me: UsersPermissionsMe
}

input RoleInput {
  name: String!
  description: String
  type: String
  permissions: [ID]
  users: [ID]
}

type SiteInfo {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  title: String
  description: String
  headline: String
  email: String
  twitter_handle: String
  instagram_handle: String
  googleAnalyticsID: String
  facebook_handle: String
}

input SiteInfoInput {
  title: String
  description: String
  headline: String
  email: String
  twitter_handle: String
  instagram_handle: String
  googleAnalyticsID: String
  facebook_handle: String
}

input SubscriberInput {
  first_name: String
  last_name: String
  email: String
  phone_number: Long
  profile_picture: [ID]
  date_of_birth: Date
  gender: ENUM_SUBSCRIBERS_GENDER
  password: String!
  username: String
}

type Subscribers {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  first_name: String
  last_name: String
  email: String
  phone_number: Long
  date_of_birth: Date
  gender: ENUM_SUBSCRIBERS_GENDER
  password: String!
  username: String
  profile_picture(sort: String, limit: Int, start: Int, where: JSON): [UploadFile]
}

type SubscribersAggregator {
  count: Int
  totalCount: Int
}

type SubscribersConnection {
  values: [Subscribers]
  groupBy: SubscribersGroupBy
  aggregate: SubscribersAggregator
}

type SubscribersConnectionCreated_at {
  key: DateTime
  connection: SubscribersConnection
}

type SubscribersConnectionDate_of_birth {
  key: ID
  connection: SubscribersConnection
}

type SubscribersConnectionEmail {
  key: String
  connection: SubscribersConnection
}

type SubscribersConnectionFirst_name {
  key: String
  connection: SubscribersConnection
}

type SubscribersConnectionGender {
  key: String
  connection: SubscribersConnection
}

type SubscribersConnectionId {
  key: ID
  connection: SubscribersConnection
}

type SubscribersConnectionLast_name {
  key: String
  connection: SubscribersConnection
}

type SubscribersConnectionPassword {
  key: String
  connection: SubscribersConnection
}

type SubscribersConnectionPhone_number {
  key: ID
  connection: SubscribersConnection
}

type SubscribersConnectionUpdated_at {
  key: DateTime
  connection: SubscribersConnection
}

type SubscribersConnectionUsername {
  key: String
  connection: SubscribersConnection
}

type SubscribersGroupBy {
  id: [SubscribersConnectionId]
  created_at: [SubscribersConnectionCreated_at]
  updated_at: [SubscribersConnectionUpdated_at]
  first_name: [SubscribersConnectionFirst_name]
  last_name: [SubscribersConnectionLast_name]
  email: [SubscribersConnectionEmail]
  phone_number: [SubscribersConnectionPhone_number]
  date_of_birth: [SubscribersConnectionDate_of_birth]
  gender: [SubscribersConnectionGender]
  password: [SubscribersConnectionPassword]
  username: [SubscribersConnectionUsername]
}

"""A time string with format: HH:mm:ss.SSS"""
scalar Time

input updateArchiveInput {
  data: editArchiveInput
}

type updateArchivePayload {
  archive: Archives
}

input updateFileInput {
  where: InputID
  data: editFileInput
}

type updateFilePayload {
  file: UploadFile
}

input updateHomeInput {
  data: editHomeInput
}

type updateHomePayload {
  home: Home
}

input updatePageInput {
  where: InputID
  data: editPageInput
}

type updatePagePayload {
  page: Page
}

input updatePostCategoryInput {
  where: InputID
  data: editPostCategoryInput
}

type updatePostCategoryPayload {
  postCategory: PostCategory
}

input updatePostInput {
  where: InputID
  data: editPostInput
}

type updatePostPayload {
  post: Post
}

input updateRoleInput {
  where: InputID
  data: editRoleInput
}

type updateRolePayload {
  role: UsersPermissionsRole
}

input updateSiteInfoInput {
  data: editSiteInfoInput
}

type updateSiteInfoPayload {
  siteInfo: SiteInfo
}

input updateSubscriberInput {
  where: InputID
  data: editSubscriberInput
}

type updateSubscriberPayload {
  subscriber: Subscribers
}

input updateUserInput {
  where: InputID
  data: editUserInput
}

type updateUserPayload {
  user: UsersPermissionsUser
}

"""The `Upload` scalar type represents a file upload."""
scalar Upload

type UploadFile {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  name: String!
  alternativeText: String
  caption: String
  width: Int
  height: Int
  formats: JSON
  hash: String!
  ext: String
  mime: String!
  size: Float!
  url: String!
  previewUrl: String
  provider: String!
  provider_metadata: JSON
  related(sort: String, limit: Int, start: Int, where: JSON): [Morph]
}

type UploadFileAggregator {
  count: Int
  totalCount: Int
  sum: UploadFileAggregatorSum
  avg: UploadFileAggregatorAvg
  min: UploadFileAggregatorMin
  max: UploadFileAggregatorMax
}

type UploadFileAggregatorAvg {
  width: Float
  height: Float
  size: Float
}

type UploadFileAggregatorMax {
  width: Float
  height: Float
  size: Float
}

type UploadFileAggregatorMin {
  width: Float
  height: Float
  size: Float
}

type UploadFileAggregatorSum {
  width: Float
  height: Float
  size: Float
}

type UploadFileConnection {
  values: [UploadFile]
  groupBy: UploadFileGroupBy
  aggregate: UploadFileAggregator
}

type UploadFileConnectionAlternativeText {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionCaption {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionCreated_at {
  key: DateTime
  connection: UploadFileConnection
}

type UploadFileConnectionExt {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionFormats {
  key: JSON
  connection: UploadFileConnection
}

type UploadFileConnectionHash {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionHeight {
  key: Int
  connection: UploadFileConnection
}

type UploadFileConnectionId {
  key: ID
  connection: UploadFileConnection
}

type UploadFileConnectionMime {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionName {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionPreviewUrl {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionProvider {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionProvider_metadata {
  key: JSON
  connection: UploadFileConnection
}

type UploadFileConnectionSize {
  key: Float
  connection: UploadFileConnection
}

type UploadFileConnectionUpdated_at {
  key: DateTime
  connection: UploadFileConnection
}

type UploadFileConnectionUrl {
  key: String
  connection: UploadFileConnection
}

type UploadFileConnectionWidth {
  key: Int
  connection: UploadFileConnection
}

type UploadFileGroupBy {
  id: [UploadFileConnectionId]
  created_at: [UploadFileConnectionCreated_at]
  updated_at: [UploadFileConnectionUpdated_at]
  name: [UploadFileConnectionName]
  alternativeText: [UploadFileConnectionAlternativeText]
  caption: [UploadFileConnectionCaption]
  width: [UploadFileConnectionWidth]
  height: [UploadFileConnectionHeight]
  formats: [UploadFileConnectionFormats]
  hash: [UploadFileConnectionHash]
  ext: [UploadFileConnectionExt]
  mime: [UploadFileConnectionMime]
  size: [UploadFileConnectionSize]
  url: [UploadFileConnectionUrl]
  previewUrl: [UploadFileConnectionPreviewUrl]
  provider: [UploadFileConnectionProvider]
  provider_metadata: [UploadFileConnectionProvider_metadata]
}

input UserInput {
  username: String!
  email: String!
  provider: String
  password: String
  resetPasswordToken: String
  confirmed: Boolean
  blocked: Boolean
  role: ID
}

input UsersPermissionsLoginInput {
  identifier: String!
  password: String!
  provider: String = "local"
}

type UsersPermissionsLoginPayload {
  jwt: String!
  user: UsersPermissionsMe!
}

type UsersPermissionsMe {
  id: ID!
  username: String!
  email: String!
  confirmed: Boolean
  blocked: Boolean
  role: UsersPermissionsMeRole
}

type UsersPermissionsMeRole {
  id: ID!
  name: String!
  description: String
  type: String
}

type UsersPermissionsPermission {
  id: ID!
  type: String!
  controller: String!
  action: String!
  enabled: Boolean!
  policy: String
  role: UsersPermissionsRole
}

type UsersPermissionsRole {
  id: ID!
  name: String!
  description: String
  type: String
  permissions(sort: String, limit: Int, start: Int, where: JSON): [UsersPermissionsPermission]
  users(sort: String, limit: Int, start: Int, where: JSON): [UsersPermissionsUser]
}

type UsersPermissionsRoleAggregator {
  count: Int
  totalCount: Int
}

type UsersPermissionsRoleConnection {
  values: [UsersPermissionsRole]
  groupBy: UsersPermissionsRoleGroupBy
  aggregate: UsersPermissionsRoleAggregator
}

type UsersPermissionsRoleConnectionDescription {
  key: String
  connection: UsersPermissionsRoleConnection
}

type UsersPermissionsRoleConnectionId {
  key: ID
  connection: UsersPermissionsRoleConnection
}

type UsersPermissionsRoleConnectionName {
  key: String
  connection: UsersPermissionsRoleConnection
}

type UsersPermissionsRoleConnectionType {
  key: String
  connection: UsersPermissionsRoleConnection
}

type UsersPermissionsRoleGroupBy {
  id: [UsersPermissionsRoleConnectionId]
  name: [UsersPermissionsRoleConnectionName]
  description: [UsersPermissionsRoleConnectionDescription]
  type: [UsersPermissionsRoleConnectionType]
}

type UsersPermissionsUser {
  id: ID!
  created_at: DateTime!
  updated_at: DateTime!
  username: String!
  email: String!
  provider: String
  confirmed: Boolean
  blocked: Boolean
  role: UsersPermissionsRole
}

type UsersPermissionsUserAggregator {
  count: Int
  totalCount: Int
}

type UsersPermissionsUserConnection {
  values: [UsersPermissionsUser]
  groupBy: UsersPermissionsUserGroupBy
  aggregate: UsersPermissionsUserAggregator
}

type UsersPermissionsUserConnectionBlocked {
  key: Boolean
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionConfirmed {
  key: Boolean
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionCreated_at {
  key: DateTime
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionEmail {
  key: String
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionId {
  key: ID
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionProvider {
  key: String
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionRole {
  key: ID
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionUpdated_at {
  key: DateTime
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserConnectionUsername {
  key: String
  connection: UsersPermissionsUserConnection
}

type UsersPermissionsUserGroupBy {
  id: [UsersPermissionsUserConnectionId]
  created_at: [UsersPermissionsUserConnectionCreated_at]
  updated_at: [UsersPermissionsUserConnectionUpdated_at]
  username: [UsersPermissionsUserConnectionUsername]
  email: [UsersPermissionsUserConnectionEmail]
  provider: [UsersPermissionsUserConnectionProvider]
  confirmed: [UsersPermissionsUserConnectionConfirmed]
  blocked: [UsersPermissionsUserConnectionBlocked]
  role: [UsersPermissionsUserConnectionRole]
}
`

**Additional context**
I did install the plugin "strapi-provider-upload-aws-s3": "^3.0.0-beta.20" for AWS upload. Other than that, there aren't any modifications.

**Comment by derrickmehaffy** [comment]
Please make your issue readable, if you are going to add that much information it would be better to link to a git repo containing your project.
