### ISSUE TITLE
content manager plugin is not visible in the plugin section

### ISSUE THREAD

**Issue by shivaping** [strapi/strapi#5974]
After installing latest strapi, i dont see the content manager plugin in the left hand side of the plugin panel

![Image 28-04-20 at 3 07 AM](https://user-images.githubusercontent.com/13598222/80423336-7ccaf280-88fd-11ea-9943-69a7f32adf34.jpeg)

**Comment by iicdii** [comment]
They are included in the menu under "COLLECTION TYPES"
you can see it redirects to "/admin/plugins/**content-manager**/collectionType/plugins::users-permissions.user" when you click the `Users` menu.

**Comment by derrickmehaffy** [comment]
There is no link in the left menu anymore it's included in the Content-Type builder and the list/edit views of the model.

**Comment by nhatbao123** [comment]
So, how did we install the content management plugin version, please!

**Comment by lauriejim** [comment]
I don't understand your question, this plugin is installed by default.

**Comment by nhatbao123** [comment]
Now I have a way to solve this problem.Thank
