### ISSUE TITLE
Context on query resolver

### ISSUE THREAD

**Issue by ronildo** [strapi/strapi#5978]
**Describe the bug**
Context on a custom GraphQL resolver does not have all the properties like a controller. I'm not sure if this is really a bug or the correct implementation, but I was trying to use to user from store, but I can't.

![Screen Shot 2020-04-27 at 5 10 08 PM](https://user-images.githubusercontent.com/622159/80433961-74a39080-88c6-11ea-8fb1-93f63dc5e248.png)

**Steps to reproduce the behavior**

1. Console log from resolver function.
![Screen Shot 2020-04-27 at 5 22 15 PM](https://user-images.githubusercontent.com/622159/80433984-85540680-88c6-11ea-9755-4986ecd0bf25.png)

**Expected behavior**
This is the object I was expecting.
![Screen Shot 2020-04-27 at 8 35 50 PM](https://user-images.githubusercontent.com/622159/80434061-baf8ef80-88c6-11ea-9b05-659664d10f11.png)

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: sqlite
- Operating system: Mac OS

**Comment by MrRorg** [comment]
Hello,
Just use `ctx.context` instead of `ctx`
