### ISSUE TITLE
Syntax error - Documentation

### ISSUE THREAD

**Issue by lpouvreau** [strapi/strapi#5980]
Hello there,

Just a quick syntax error in your documentation

**Describe the bug**
https://github.com/strapi/strapi/edit/master/docs/3.0.0-beta.x/plugins/documentation.md
L.104
`"showGeneratedFiles": true",` instead of `"showGeneratedFiles": true,`

**Steps to reproduce the behavior**
n/a

**Expected behavior**
n/a

**Comment by derrickmehaffy** [comment]
@lpouvreau can you create a pull request?

**Comment by lpouvreau** [comment]
Yes of course, sorry for that.
I created a PR and I'll close this issue
