### ISSUE TITLE
Writing the character '%' in the search bar makes it partially reset

### ISSUE THREAD

**Issue by petersg83** [strapi/strapi#5984]
**Describe the bug**
When you write the character '%' in the search bar, the search bar is reset but the results are displayed. You have to wait a bit after typing '%'

**Steps to reproduce the behavior**

1. Go to the search bar of one of you content-types
2. Write "hello%"
3. See the input being cleared

**Expected behavior**
The input is only cleared when I delete the text myself

**Screenshots**
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/11708220/80468297-4b731680-893f-11ea-8c23-cb079041d1d0.gif)

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: beta.20.1
- Database: sqlite
- Operating system: macOS

**Additional context**
The results of the search are weird but it is an issue that doesn't seem to be related and that is already being fixed : https://github.com/strapi/strapi/tree/fix/4813/searchDoesntAlwaysWork.
So don't worry if you see weird results. The '%' bug seems to come front the front.

**Comment by tudorilisoi** [comment]
That's because the `%` character is not urlencoded as a parameter value. 
`%` has special meaning in an URL, so when strapi is setting the route it should encode query parameters values
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by soupette** [comment]
I agree! It's a miss! 
If someone feels like making a PR to fix this bug it would be awesome!

Here are the files to investigate:
- [Content Manager](https://github.com/strapi/strapi/blob/9414eb717be8bb0739b8eb7445257d3507a92f7d/packages/strapi-plugin-content-manager/admin/src/containers/ListView/index.js#L243-L254)
- [Strapi-helper-plugin](https://github.com/strapi/strapi/blob/master/packages/strapi-helper-plugin/lib/src/utils/getQueryParameters.js)
