### ISSUE TITLE
Facebook Login Redirect URI pointing to localhost

### ISSUE THREAD

**Issue by rohankandwal** [strapi/strapi#5986]
**Describe the bug**
Deployed Strapi project on server and created a Facebook App. As per documentation, configured Strapi admin and Facebook App.

**Expected behavior**
On opening, https://example.com/connect/facebook/, the URL redirects to
https://www.facebook.com/dialog/oauth?client_id=XXX73507618017&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Fconnect%2Ffacebook%2Fcallback&scope=email

Since this is on server, it shouldn't redirect to 'localhost'.

**Screenshots**
<img width="917" alt="Facebook Admin" src="https://user-images.githubusercontent.com/7704510/80483416-ade60a00-8973-11ea-9bca-d49e02e668b1.png">

<img width="1183" alt="Facebook App Settings" src="https://user-images.githubusercontent.com/7704510/80483584-f43b6900-8973-11ea-9547-aebde5f33fda.png">

**System**

- Node.js version: v13.12.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: mongodb

**Comment by negati-ve** [comment]
doesn't look like a problem with strapi. 
most probably your site url is set to localhost under settings->basic in facebook developer console

**Comment by rohankandwal** [comment]
@negati-ve Attaching screenshots from settings->basic in FB console.
<img width="1086" alt="Screen Shot 2020-05-03 at 11 58 26 AM" src="https://user-images.githubusercontent.com/7704510/80907525-9fae3a00-8d35-11ea-8ef9-23579b2ef8f3.png">
<img width="1622" alt="Screen Shot 2020-05-03 at 11 56 59 AM" src="https://user-images.githubusercontent.com/7704510/80907528-a341c100-8d35-11ea-9f2d-aac9aa123f00.png">

let me know if I am missing something.

**Comment by lauriejim** [comment]
Did you checked this issue - https://github.com/strapi/strapi/issues/3360

**Comment by rohankandwal** [comment]
> Did you checked this issue - #3360

I haven't, let me try it out and get back to you.

**Comment by negati-ve** [comment]
Strapi has a proxy config.

you need to configure your proxy under 
config/environment/development/server.json 
```
"proxy": {
    "enabled": true,
    "host": "xyz.com",
    "port": 80,
    "ssl": true
  }
```

this way strapi knows where you should redirect after authentication via facebook

hope that helps

**Comment by negati-ve** [comment]
I tested this on my test deployment and it works perfectly. 
Please verify and close this issue
thanks

**Comment by rohankandwal** [comment]
> Strapi has a proxy config.
> 
> you need to configure your proxy under
> config/environment/development/server.json
> 
> ```
> "proxy": {
>     "enabled": true,
>     "host": "xyz.com",
>     "port": 80,
>     "ssl": true
>   }
> ```
> 
> this way strapi knows where you should redirect after authentication via facebook
> 
> hope that helps

This worked, but I had to change port 80 to 443 to make it work. Thanks.

**Comment by justcodejs** [comment]
> Strapi has a proxy config.
> 
> you need to configure your proxy under
> config/environment/development/server.json
> 
> ```
> "proxy": {
>     "enabled": true,
>     "host": "xyz.com",
>     "port": 80,
>     "ssl": true
>   }
> ```
> 
> this way strapi knows where you should redirect after authentication via facebook
> 
> hope that helps

It works for me!
