### ISSUE TITLE
GraphQL nested filtering doesn't work with components

### ISSUE THREAD

**Issue by Fl4zher** [strapi/strapi#5987]
**Describe the bug**
When i try to filter by a component within Content-type, i receive an error instead: 
` "message": "Your filters contain a field 'barcode.ean' that doesn't appear on your model definition nor it's relations"`

**Steps to reproduce the behavior**
1. Create content type
2. Create component to the content type. 
3. Make a query with {where: {component: { type: filter } } }

**Expected behavior**
I expect the response to be filtered by the component type as requested.

**Screenshots**
The query
![query](https://user-images.githubusercontent.com/13366825/80489740-92253880-8960-11ea-9538-0fc64fc4127b.PNG)

**System**

- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.20
- Database: MySQL
- Operating system: Windows 10 64bit

**Comment by derrickmehaffy** [comment]
duplicate: https://github.com/strapi/strapi/issues/5124
