### ISSUE TITLE
⛔️ Server wasn't able to start properly

### ISSUE THREAD

**Issue by mauricewegner** [strapi/strapi#5994]
First of all: 
Love this project! 

Following the AWS deployment guide, I got stuck at this point:

<img width="979" alt="screen" src="https://user-images.githubusercontent.com/53715854/80521645-a894b980-898b-11ea-97a1-510818c33a31.png">

Already checked out similar issues but couldn't find a solution yet. I'm currently running the build process locally pushing the build dir onto Github (temporarily) due to CPU lack on the ec2 instance.

**`database.json`** (production):
``` json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}"
      },
      "options": {
        "ssl": false
      }
    }
  }
}
```

PM2 **`ecosystem.config.js`**
``` js
module.exports = {
  apps : [
    {
        name: 'strapi',
        cwd: './XXXXX-strapi/',
        script: 'npm',
        args: 'start',
        env: {
          NODE_ENV: 'production',
          DATABASE_HOST: 'strapi-db.XXXXX.XXXXX.rds.amazonaws.com',
          DATABASE_PORT: '5432',
          DATABASE_NAME: 'strapi',
          DATABASE_USERNAME: 'postgres',
          DATABASE_PASSWORD: 'XXXXX'
        },
    },
  ],
};
```

**`package.json`**
``` js
{
  "name": "XXXXX",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "pg": "^8.0.3",
    "sqlite3": "latest",
    "strapi": "^3.0.0-beta.20",
    "strapi-admin": "3.0.0-beta.20",
    "strapi-connector-bookshelf": "3.0.0-beta.20",
    "strapi-plugin-content-manager": "3.0.0-beta.20",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20",
    "strapi-plugin-email": "3.0.0-beta.20",
    "strapi-plugin-graphql": "^3.0.0-beta.20",
    "strapi-plugin-upload": "3.0.0-beta.20",
    "strapi-plugin-users-permissions": "3.0.0-beta.20",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.20.1",
    "strapi-utils": "3.0.0-beta.20"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "XXXXX"
  },
  "engines": {
    "node": ">=12.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

PS: there's a vulnerability issue I couldn't fix (probably should open up a new report for that)
<img width="644" alt="lodash_strapi" src="https://user-images.githubusercontent.com/53715854/80523651-aed86500-898e-11ea-9e5e-a2966fa87e27.png">

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: Strapi v3.0.0-beta.20
- Database: Postgres
- Operating system: Ubuntu 18.04.4 LTS

Thanks in advance

**Comment by derrickmehaffy** [comment]
All strapi packages need to be the same version and remove any carets `^` before **strapi package** versions. 

Also **do not use** `npm audit fix` with Strapi you will break stuff.

**Comment by mauricewegner** [comment]
> All strapi packages need to be the same version and remove any carets `^` before **strapi package** versions.

Thank you very much. The different versions were causing the issue in my case. 🚀 


> Also **do not use** `npm audit fix` with Strapi you will break stuff.

Haven't used it. Just audited the issue to get some further information.

**Comment by AliKHODR** [comment]
i am having the same problem, i followed the doc but i got stuck at this point : my project is not available at http://your-ip-address:1337/.
System
-     Node.js version: 12.18.0
-     NPM version: 6.14.4
-     Strapi version: "3.0.1"
-     strapi-provider-upload-aws-s3 : "^3.0.0-beta.20.3",
-     Database: MySQL
-     Operating system: Ubuntu 18.04.4 LTS

**Comment by EddStrickland** [comment]
> i am having the same problem, i followed the doc but i got stuck at this point : my project is not available at http://your-ip-address:1337/.
> System
> Node.js version: 12.18.0
> NPM version: 6.14.4
> Strapi version: "3.0.1"
> strapi-provider-upload-aws-s3 : "^3.0.0-beta.20.3",
> Database: MySQL
> Operating system: Ubuntu 18.04.4 LTS

Did you find a solution to this as this is exactly the issue I'm having all the Carets are removed and the Strapi module versions are all aligned.

**Comment by mauricewegner** [comment]
> > i am having the same problem, i followed the doc but i got stuck at this point : my project is not available at http://your-ip-address:1337/.
> > System
> > Node.js version: 12.18.0
> > NPM version: 6.14.4
> > Strapi version: "3.0.1"
> > strapi-provider-upload-aws-s3 : "^3.0.0-beta.20.3",
> > Database: MySQL
> > Operating system: Ubuntu 18.04.4 LTS
> 
> Did you find a solution to this as this is exactly the issue I'm having all the Carets are removed and the Strapi module versions are all aligned.

If I remember correctly I have also upgraded the EC2 instance and moved the build process onto it. Since Strapi requires at least 2GB RAM. You might also want to check [https://strapi.io/documentation/v3.x/getting-started/deployment.html#recommended-requirements](here) if you fulfill the (minimum) requirements
