### ISSUE TITLE
Rotation of uploaded images

### ISSUE THREAD

**Issue by alxnkt** [strapi/strapi#5996]
**Describe the bug (feature)**
In Strapi of version beta.20 there is a new possibility - creation of thumbnails of images. This is very useful and convenient feature. Thank you. In previous versions I had to do it by my own with help of [sharp](https://www.npmjs.com/package/sharp) package: I could resize and rotate an image according to EXIF orientation tag. 
New upload plugin does not automatically rotate images, so photos from iphone with "portrait" orientation (orientation tag 6) appears with wrong rotation. 
So I want to ask:
1. Is there any way to "hook" upload process to rotate an image (or do some other manipulations)?
2. Is there any way to choose necessary formats? For example, I need thumbnail and medium size, but I don't need large size, sometimes I don't even need original file.

**Steps to reproduce the behavior**

1. Upload any image with EXIF orientation tag equaled 6 (photo from iphone with "portrait" orientation). 
2. Go to "Media Library".
3. Ensure the image has improper rotation.

**Expected behavior**
I would like images to be properly rotated.

**Screenshots**
In Finder:
![finder](https://user-images.githubusercontent.com/49128174/80612360-89a62e00-8a44-11ea-85ce-3b34c679eaa8.png)
In Media Library (the building "fell down"):
![media](https://user-images.githubusercontent.com/49128174/80612361-8ad75b00-8a44-11ea-91fa-bd0bba15daf1.png)

**Code snippets**
My implementation of auto rotation:
```javascript
// sharp automatically rotates image according to orientation tag
const thumbnailBuffer = await sharp(file.path)
    .resize(300)
    .rotate()
    .toBuffer();
```

**System**

- Node.js version: 13.13.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: PostgreSQL 12.2
- Operating system: MacOS Catalina 10.15.4

**Comment by lauriejim** [comment]
Thank you for this message!
I ping @Aurelsicoko @soupette and @alexandrebodin for this idea.

**Comment by alxnkt** [comment]
Seems like issue can be closed, because PR is merged.

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/image-upload-rotating-exif-param/3538/1
