### ISSUE TITLE
Upload plugin not shown

### ISSUE THREAD

**Issue by brycelund** [strapi/strapi#5997]
**Describe the bug**

Installing strapi-provider-upload-aws-s3 does not work

**Steps to reproduce the behavior**

1. `npx create-strapi-app testapp`
2. `npm i --save strapi-provider-upload-aws-s3@beta`
3. Create `/extensions/upload/config/settings.json` with
```
{
  "provider": "aws-s3",
  "providerOptions": {
    "accessKeyId": "dev-key",
    "secretAccessKey": "dev-secret",
    "region": "aws-region",
    "params": {
      "Bucket": "my-bucket"
    }
  }
}
```
4. `yarn develop`
5. Click Plugins > File Upload cog
6. AWS S3 is not shown

**Expected behavior**
Expected behavior is that the provider becomes available for use

**System**

- Node.js version: 12.16.1 
- NPM version: 6.13.4
- Strapi version:  v3.0.0-beta.18.2
- Database: n/a
- Operating system: MacOS. Also attempted on Ubuntu 18.04

**Comment by brycelund** [comment]
npx defaulted to installing old version

**Comment by raphaelsoul** [comment]
any resolution? In my case there's no plugin named upload event it is listed in package.json. Also tried install again with `yarn strapi install upload`

**Comment by oussj** [comment]
Same here... Something came with a solution ?

**Comment by tayloraleach** [comment]
Same issue here, on v 3.0.6 do not see the files upload option

**Comment by raphaelsoul** [comment]
for my expierence, seems the UI of upload plugin is deprecated.
But upload to s3 works good.

**Comment by clevercodenl** [comment]
I'm having the same problem but with the cloudinary provider. The files upload menu item is not displaying, is there a workaround for this ?

**Comment by derrickmehaffy** [comment]
@clevercodenl did that config work for you?

**Comment by clevercodenl** [comment]
@derrickmehaffy yes, it did
