### ISSUE TITLE
Sqlite3 client missing when app start in production mode

### ISSUE THREAD

**Issue by alsozx** [strapi/strapi#5999]
Describe the bug
sqlite3 exists in node_modules, but when running pm2 start --env production the process fails because sqlite3 is not installed

Steps to reproduce the behavior

Go to your strapi app directory
RUN pm2 start --env production
See error
| > project@0.1.0 start /opt/project
| > node tool/index.js && strapi start
| [2020-04-29T11:40:58.103Z] error The client `sqlite3` is not installed.
| [2020-04-29T11:40:58.104Z] error You can install it with `$ npm install sqlite3 --save`.
| npm
|  ERR! code ELIFECYCLE
| npm ERR! errno 1
| npm
|  ERR! project@0.1.0 start: `node tool/index.js && strapi start`
| npm 
| ERR! Exit status 1
| npm ERR! 
| npm ERR! Failed at the project@0.1.0 start script.
| npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /root/.npm/_logs/2020-04-29T11_40_58_118Z-debug.log

Expected behavior
strapi app can start normally.

System

Node.js version: v12.16.1
NPM version: V6.13.4
Strapi version: 3.0.0-beta.19.3

**Comment by derrickmehaffy** [comment]
`Strapi version: 3.0.0-beta.19.3` Please test with the latest version. Also, please make your issue readable by following the proper bug report template.
