### ISSUE TITLE
Enhance MySQL requirements

### ISSUE THREAD

**Issue by padupuy** [strapi/strapi#600]
**Node.js version**:
v9.3.0

**npm version**:
5.5.1
**Strapi version**:
3.0.0-alpha.9.2
**Operating system**:
macOS High Sierra 10.13.1 

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The creation of the strapi project fails when MySQL is chosen as database engine and the MySQL configuration is not compatible with strapi instruction 

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Create a new strapi project
2. Chose MySQL as database engine
3. Copy / Paste strapi instructions
Installation failed with `ERROR 1067 (42000): Invalid default value for 'created_at'`

**What is the expected behavior?**
Installation must complete without exceptions

When the installation process is in progress and MySQL is chosen as database engine, is it possible to check `sql_mode` and check if it not contains `NO_ZERO_IN_DATE,NO_ZERO_DATE` ?
Or at lease, help the user to achieve its installation by displaying a strapi help link with mysql requirements ?
I had to edit my mysql conf file to set new `sql_mode` remove those values.

Edit : `/usr/local/etc/my.cnf`
Add : `sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
Restart mysql service

**Comment by derrickmehaffy** [comment]
This information should not trigger automatically and should be documented as not everyone will use a locally hosted MySQL Instance or even in the local LAN. In many cases it should be expected a remote database will be used especially those geared towards more redundant based setups such as using Galera Clusters.

**Comment by lauriejim** [comment]
Hi @padupuy thank your for this issue. 
Your issue is really specific to your configuration. I let this issue open but we will not investigate soon for this issue. 

But if you want you can contribute to improve Strapi documentation making a pull request to add your point in the doc.

**Comment by lauriejim** [comment]
A part of this issue here https://github.com/strapi/strapi/issues/767
