### ISSUE TITLE
Update method in user plugin returns unsanitized user

### ISSUE THREAD

**Issue by drewtownchi** [strapi/strapi#6000]
**Describe the bug**
The `update` method is returning an unsanitized user method which could leak data unnecessarily.

**Steps to reproduce the behavior**

1. Submit a **PUT** request to the `/users/update` route.
2. Look at the raw JSON returned

**Expected behavior**
The returned JSON should return a sanitized user object, no password hash and no reset token.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/9697868/80603316-dadb0100-89f5-11ea-88bb-b1e25b4ba294.JPG)

**Code snippets**

https://github.com/strapi/strapi/blob/6a6d53b4029c4b08837c8fd2a6aea820b91ce18a/packages/strapi-plugin-users-permissions/controllers/User.js#L219-L221

**System**

- Node.js version: v12.16.1
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.21
- Database: pg 11
- Operating system: Windows 10

**Additional context**

I think the PR could be to either always sanitize the returned value or, if the ctx's current role is an admin don't sanitize the data if for some reason the unsanitized values are necessary in the admin panel.

**Comment by derrickmehaffy** [comment]
@drewtownchi I won't close this because it needs to be addressed if there is a problem, but can you please edit your post to follow the required bug report template.

Generally I'd provide an automatic response and close the issue.

**Comment by drewtownchi** [comment]
> @drewtownchi I won't close this because it needs to be addressed if there is a problem, but can you please edit your post to follow the required bug report template.

Very sorry. I opened the issue via the code and it didn't include the template. Updated!

**Comment by derrickmehaffy** [comment]
No problem I know not all the 3rd party clients populate the template, thank you for fixing it. If you are up for making a pull request please do :smile:

**Comment by lauriejim** [comment]
Ping @alexandrebodin about this issue/PR.
I also think it should be clean.
