### ISSUE TITLE
content type  is not defined due to globalid missing error

### ISSUE THREAD

**Issue by Rajeshkumaran** [strapi/strapi#6006]
Hello , recently I have migrated my strapi project from strapi alpha.22 to beta.20 by following this guide (https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-alpha.26-to-beta.html)

**Issue**
I have a content type named **category** which is created in alpha.22 version.During migration I just copied the contents of api.

The api data is not able to consumed in graphql (/graphql)
When I tried to get the data using graphql it throws error refer the below image

![image](https://user-images.githubusercontent.com/24778412/80709141-6fcf1e80-8b0a-11ea-9671-6936e9e5492b.png)

But when I change the code in api/category/services/Category.js  replacing the **Category** to strapi.models["category"] ,it is working fine

![image](https://user-images.githubusercontent.com/24778412/80709339-c2a8d600-8b0a-11ea-9f36-34a622c471db.png)

**Expected behavior**
Graphql endpoint has to return data.

- Node.js version: 12.8.1
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.20.1
- Database: mongo 
- Operating system: macOs mojave

**Comment by derrickmehaffy** [comment]
Unless you have a need to customize the controllers and service, those files should be wiped empty except for an empty module.exports object. With the Strapi beta, all the core controllers and services are pulled from the `strapi` package in node_modules via the new core-api

**Comment by Rajeshkumaran** [comment]
Thanks @derrickmehaffy for your solution.But what I need to do if i have already made some changes in services/Category.json ,how can I access the global **Category** here without strapi.models.category

**Comment by lauriejim** [comment]
Hello! This guide it to migrate to the first version of the beta.
Then you also have to check major changes of each migration guide.
It's not an easy thing to do.

**Comment by derrickmehaffy** [comment]
To be clear @Rajeshkumaran I generally suggest to users migrating from the Alpha all the way to the latest beta, is to create a new project and manually migrate your models and customization over.

There have been a ton of changes since the Alpha versions that just make updating step by step a difficult task (that gets more difficult the long you wait)
