### ISSUE TITLE
Add a blocking state when saving/editing in the Content Manager

### ISSUE THREAD

**Issue by ayhid** [strapi/strapi#6008]
- [x] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**

When saving content types, users can still click multiple times anywhere on the application before they are redirected on the listing page.

This is problematic when you have for example build hooks to trigger upon save.

As discussed with @soupette I am posting the feature request for this behaviour.
here is a link for the slack thread to have some context
https://strapi.slack.com/archives/C0BNGCDNH/p1588232998490000

**Comment by soupette** [comment]
I am closing this issue as it has been fixed in `v3.1.0`
