### ISSUE TITLE
MYSQL can't update any model

### ISSUE THREAD

**Issue by wingsiu** [strapi/strapi#601]
Node.js version: v8.9.4
npm version: 5.6.0
Strapi version: 3.0.0-alpha.9.1
Operating system: Mac OSX 10.13.3

database : mysql

can't update any models

**Comment by Aurelsicoko** [comment]
@wingsiu Could you format your issue with the template provided? Also, for a better experience, we highly recommend using MongoDB. With SQL databases, we can't update the tables and columns automatically for the moment.

**Comment by lauriejim** [comment]
@wingsiu can you give us some update about your issue please.

**Comment by lauriejim** [comment]
I close this issue, no news.
