### ISSUE TITLE
media library interface throws errors when adding new file

### ISSUE THREAD

**Issue by hkovacs** [strapi/strapi#6011]
**Describe the bug**
when in strapi admin uploading a file in a content record. two error notices show up. uploading functionality seems to work.

**Steps to reproduce the behavior**
0. open network before starting
1. content type record with file upload field
2. click the black area for adding media file
3. click blue "add more assets" button
4. click blue "browse files" button
5. choose a test file
6. click green "upload 1 asset to the library" button
7. see two alerts display
8. see network entries in red

**Expected behavior**
calling files and count might be incorrect in this functionality

**Screenshots**
![media-upload-2-error-notices](https://user-images.githubusercontent.com/1257358/80741233-fba07500-8b21-11ea-8135-1fce9e6b174c.png)

**System**
Node.js version: v10.16.3
NPM version: 6.9.0
Strapi version: Strapi v3.0.0-beta.20.1
Database: mongo v4.0.12
Operating system: ubuntu 18.04

**Additional context**
Thank you!

**Comment by derrickmehaffy** [comment]
Can you please post your package.json here as well (or at the very least your depends)

**Comment by hkovacs** [comment]
@derrickmehaffy here you go:
```
  "devDependencies": {},
  "dependencies": {
    "axios": "^0.19.2",
    "moment": "^2.24.0",
    "react-moment": "^0.9.7",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "strapi": "3.0.0-beta.20.1",
    "strapi-admin": "3.0.0-beta.20.1",
    "strapi-connector-mongoose": "3.0.0-beta.20.1",
    "strapi-plugin-content-manager": "3.0.0-beta.20.1",
    "strapi-plugin-content-type-builder": "3.0.0-beta.20.1",
    "strapi-plugin-email": "3.0.0-beta.20.1",
    "strapi-plugin-upload": "3.0.0-beta.20.1",
    "strapi-plugin-users-permissions": "3.0.0-beta.20.1",
    "strapi-utils": "3.0.0-beta.20.1"
  },

```

**Comment by derrickmehaffy** [comment]
So its uploading locally (and appears to actually upload) but fails to fetch and provide a count. Quite odd, anything in the server console?

**Comment by hkovacs** [comment]
yes, it uploads. no complaints there. :) 

per your comment about fetch and count, i guess it is attempting to display a refreshed display of files.

only item in the pm2 log is `POST /upload (120 ms) 200` and then pm2 restarts strapi due to the failures.

**Comment by soupette** [comment]
It seems weird that your server is restarting

**Comment by ig1na** [comment]
I am having the same issue here

**Comment by lauriejim** [comment]
Hello @hkovacs ! Did you try to start your application without PM2?
Just to know if it's not related to it.

**Comment by lauriejim** [comment]
Can you please share your model (every model related to this content type, and components too)
Just to make sure to be able to reproduce correctly your issue.

**Comment by hkovacs** [comment]
> Hello @hkovacs ! Did you try to start your application without PM2?
> Just to know if it's not related to it.

you were correct. pm2 seems to have a problem with running strapis `npm run develop`

i manually run `npm run develop` and upload file does not throw any errors in network.

however, there is a bit of a UX problem here:

in this image i upload my test file
![upload-asset](https://user-images.githubusercontent.com/1257358/81039293-4834d900-8eb1-11ea-9f4d-3b77e66415dc.png)

after i click the green "upload asset" button it gives me the "selected" tab:
in this image of "selected" tab there are no files. not even the one i uploaded which most likely is the one i am selecting for this operation.
![nothing-selected](https://user-images.githubusercontent.com/1257358/81039387-8cc07480-8eb1-11ea-94f8-8450261cee1d.png)

but if i click on browse, i see my test file:
![theres-test-file](https://user-images.githubusercontent.com/1257358/81039503-df9a2c00-8eb1-11ea-971f-95fdd5a7311e.png)

perhaps it is the intention of the functionality to select the file automatically, but it is failing to display anything in the "selected" tab?
or,
perhaps the browse tab is supposed to be shown, but the functionality is incorrect and not displaying "browse" tab?

**Comment by hkovacs** [comment]
> Hello @hkovacs ! Did you try to start your application without PM2?
> Just to know if it's not related to it.

i see that there is a guide page for using pm2 https://strapi.io/documentation/3.0.0-beta.x/guides/process-manager.html#install-pm2 

i will configure mine accordingly and test the pm2 problem again

thank you!

**Comment by hkovacs** [comment]
> Hello @hkovacs ! Did you try to start your application without PM2?
> Just to know if it's not related to it.

i implemented pm2 per the guide https://strapi.io/documentation/3.0.0-beta.x/guides/process-manager.html#install-pm2

retested.

still having the same errors with `pm2 start server`. no errors with `npm run develop`.

i will provide my models shortly.

**Comment by hkovacs** [comment]
> Can you please share your model (every model related to this content type, and components too)
> Just to make sure to be able to reproduce correctly your issue.

the issue is related to the "association" model

```
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "association",
  "info": {
    "name": "associations",
    "description": "all details pertinent to an association are stored here"
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "name": {
      "minLength": 6,
      "required": true,
      "type": "string"
    },
    "mysqlId": {
      "type": "integer",
      "default": 0
    },
    "ein": {
      "type": "integer",
      "default": 0
    },
    "token": {
      "minLength": 9,
      "required": true,
      "unique": true,
      "type": "string"
    },
    "county": {
      "type": "string"
    },
    "mailing_address": {
      "component": "address.address",
      "type": "component"
    },
    "physical_address": {
      "component": "address.address",
      "type": "component"
    },
    "est_address": {
      "component": "address.address",
      "type": "component"
    },
    "est_name": {
      "type": "string"
    },
    "est_email": {
      "type": "email"
    },
    "officePhone": {
      "type": "string"
    },
    "office_fax": {
      "type": "string"
    },
    "about": {
      "type": "richtext"
    },
    "hero_image": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "images": {
      "collection": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "intro_text": {
      "type": "string"
    },
    "board_meeting_minutes": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "membership_meeting_minutes": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "financial_statements": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "budgets": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "contractor_agreements": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "director_certifications": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "disclosures": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "declarations": {
      "component": "document.document",
      "type": "component",
      "repeatable": true
    },
    "amendments": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "by_laws": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "articles_of_incorporation": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "rules_and_regulations": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "forms": {
      "component": "document.document",
      "repeatable": true,
      "type": "component"
    },
    "notices": {
      "type": "component",
      "repeatable": true,
      "component": "document.document"
    },
    "directors": {
      "type": "component",
      "repeatable": true,
      "component": "director.director"
    }
  }
}
```

users are assigned an association:
```
{
  "connection": "default",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "association_id": {
      "model": "association"
    },
    "firstName": {
      "type": "string",
      "required": true,
      "minLength": 3
    },
    "lastName": {
      "type": "string",
      "required": true,
      "minLength": 3
    },
    "unitNumber": {
      "type": "string",
      "required": true,
      "minLength": 1
    }
  }
}
```

association contains these components:
address:
```
{
  "info": {
    "name": "address",
    "description": "address block"
  },
  "connection": "default",
  "collectionName": "components_address_addresses",
  "attributes": {
    "address_line_1": {
      "type": "string"
    },
    "address_line_2": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "zipcode": {
      "type": "string"
    },
    "latitude": {
      "type": "float"
    },
    "longitude": {
      "type": "float"
    }
  }
}
```

director:
{
  "connection": "default",
  "collectionName": "components_director_directors",
  "info": {
    "name": "director",
    "icon": "address-book"
  },
  "options": {},
  "attributes": {
    "photo": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "full_name": {
      "type": "string",
      "required": true,
      "minLength": 7
    },
    "title": {
      "type": "string",
      "minLength": 2
    },
    "email": {
      "type": "email",
      "required": true
    }
  }
}
```

document:
```
{
  "connection": "default",
  "collectionName": "components_document_documents",
  "info": {
    "name": "document",
    "description": "",
    "icon": "file-alt"
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "file": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }
  }
}
```

thank you!

**Comment by hkovacs** [comment]
> It seems weird that your server is restarting

its probably restarting because i use pm2 flag --watch which restarts after a change.

**Comment by derrickmehaffy** [comment]
> > It seems weird that your server is restarting
> 
> its probably restarting because i use pm2 flag --watch which restarts after a change.

Yes you should not be using the built-in watcher, if you got this from any part of the documentation please link me to it so I can swiftly remove it.

**Comment by hkovacs** [comment]
> > > It seems weird that your server is restarting
> > 
> > 
> > its probably restarting because i use pm2 flag --watch which restarts after a change.
> 
> Yes you should not be using the built-in watcher, if you got this from any part of the documentation please link me to it so I can swiftly remove it.

roger that. i disabled watch. unlikely that i found it in a guide. i most likely copied it from my react command.

thank you!

**Comment by hkovacs** [comment]
i think the error was caused by misconfigured upstream. i did some reconfiguration and the errors stopped.

im still getting the ui problem but i guess i will make a new tkt for that.

**Comment by hkovacs** [comment]
interestingly, although i had the ui bug 10 minutes ago. it went away after i just did strapi restart. 

its nice when everything works :)

thanks to all of you for providing input to get me in the right direction. special thanks to @derrickmehaffy

**Comment by hkovacs** [comment]
ok, the ui issue comes and goes. i might make a new tkt next week.
