### ISSUE TITLE
Mongoose query with unprojection on dynamic zone field causes error

### ISSUE THREAD

**Issue by atlmtw** [strapi/strapi#6016]
**Describe the bug**
When creating a custom controller on a content type that has a dynamic zone field, excluding it from the selection of the query causes an error (Mongoose). For instance lets say we have dynamic zone field called "modules".

If my query looks like this:
```js
strapi.query("name")
  .model
  .find({},{modules:0}); <-- Excluding it from selection through field projection
```

Then it causes an error with the strapi-mongoose-connector library. If I don't include "modules" in it, it works. If I try to unproject another field that is not a dynamic zone field, it works. 

My custom controller code looks like this:
<img width="717" alt="Screen Shot 2020-04-30 at 5 23 15 PM" src="https://user-images.githubusercontent.com/15266711/80763333-4b744180-8b0c-11ea-938c-1fa2438d3a9d.png">

The error message I get is in this screen shot:
<img width="739" alt="Screen Shot 2020-04-30 at 5 52 04 PM" src="https://user-images.githubusercontent.com/15266711/80763302-3b5c6200-8b0c-11ea-9138-c660a1eec365.png">

It appears that the library is still trying to map on the dynamic zone field despite it not being in the returned query.

**Expected behavior**
It should return all objects that match the query of the controller without the "modules" dynamic zone field.

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20.1
- Database: MongoDB 4.2.6
- Operating system: Ubuntu 18.04 LTS

Thanks again and as always I appreciate the work the Strapi team does!

**Comment by lauriejim** [comment]
Thank you for reporting this issue, I ping @alexandrebodin about that.

**Comment by alexandrebodin** [comment]
Hi @atlmtw There is an automatic population of dynamic zones hence the code running. It is a pretty easy fix to check if there is data before trying to process it. A good first PR if you want ;)

**Comment by atlmtw** [comment]
Hey @alexandrebodin! Maybe ill try it out later tonight and submit a PR.

**Comment by alexandrebodin** [comment]
Closing as https://github.com/strapi/strapi/pull/6916 was merged. It will be available in the next release :)
