### ISSUE TITLE
Update api dynamically  

### ISSUE THREAD

**Issue by spyshow** [strapi/strapi#6017]
hi 

i have an application that the server create tables in the database when admin add new machines,
do strapi have a "watch" function for the database , so the api changes ( add new endpoint ) for the new added machines ??

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
