### ISSUE TITLE
updateEntry overwriting existing data

### ISSUE THREAD

**Issue by danielgymnasium** [strapi/strapi#6024]
**Problem**
**Hi**
On using the .updateEntry to my articles `http://localhost:1337/artigos/1` and passing my data object to like so its updating the all comments array: 

`{
        "comments": [
            {
                "text": comentario,
                "username": username,
                "reply": []
            }
        ]
    }`

On the docs https://strapi.io/documentation/3.0.0-beta.x/content-api/api-endpoints.html#update-an-entry when adding a new entry that doesnt have an ID in its object i would add to the existing array.
**What it should be doing**
Since im not passing any ID on inside my object array i would expect it to increment not overwrite it like so:

`{
        "comments": [
            {
                "id": 1,
                "text": oldcoment,
                "username": username,
                "reply": []
            },
           {
                "id": 2,
                "text": comentario,
                "username": username,
                "reply": []
            }
        ]
    }`

Am i missing anything ? im using a JSON field for the comments in my collection type

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
