### ISSUE TITLE
Strapi sendGrid on Heroku - Bad Request - Auth.form.error.email.format

### ISSUE THREAD

**Issue by elirodrigues** [strapi/strapi#6034]
Hey guys,
I'm looking for help to complete the configuration of SendGrid plugin. Currently, my SendGrid is provided by Heroku. But, it keeps insistently sending me the message errror: "Auth.form.error.email.format".

Bellow the steps I've followed:

1. (locally) Install Strapi and configure contents, users, etc 
2. (locally) npm install strapi-provider-email-sendgrid@alpha --save
3. (locally) npm run develop --watch-admin
4. (Heroku) go to Heroku and provide SendGrid
5. (through Heroku) On Sendgrid: generate SendGrid API key
6. (locally) Go to Strapi Admin / Settings / E-mail 
7. (locally) Select Sendgrid as a provider and add Sendgrid API Key
8. (locally) Go to Groups and Permissions and allow everything to Email plugin
9. (locally) Execute a POST on Postman

**Screenshots**

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/25332847/80894005-68944600-8cad-11ea-867b-4570042a9c36.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/25332847/80894021-85c91480-8cad-11ea-9fae-257a17a02aeb.png">

![image](https://user-images.githubusercontent.com/25332847/80894112-7ac2b400-8cae-11ea-97b9-1f7498129a13.png)

**Code snippets**
I've also tested the connection using Python, just for the check and it works fine:

`# using SendGrid's Python Library
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

message = Mail(
    from_email='MYEMAIL@gmail.com',
    to_emails='MYEMAIL@gmail.com',
    subject='Consegui - Sending with Twilio SendGrid is Fun',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
try:
    sg = SendGridAPIClient(os.environ.get('MY_SENDGRID_KEY'))
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e)`

**System**
- Strapi version: 
- Node.js version:node v12.16.2
- NPM version:6.14.4
- Strapi version: 3.0.0-beta.20
- Database: MongoDb in Mongo Atlas, via mongoose
- Operating system: Mac OS Catalina 10.15.4

**Additional context**
With all that being said. Is there any advice from the community?

Tks, Eli.

**Comment by derrickmehaffy** [comment]
Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to the [discussions](https://github.com/strapi/strapi/discussions)

I have converted this to a discussion for you, we try to keep Github clean and only for bug reports and feature requests.
