### ISSUE TITLE
Strapi GraphQL model callbacks aren't firing

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#6035]
I'm trying to get callbacks on a model to fire when I make a GraphQL query but this doesn't seem to happen. Is there a particular reason for this? Or am I doing something wrong.

To reproduce the issue:

- Install Strapi
- Install GraphQL plugin
- Create and Save a content type
- Edit the model lifecycle hook to log out a response on "afterFetch"

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/strapi/issues/1443

**Comment by kasonde** [comment]
@derrickmehaffy I don't know if it's of any use here since this is closed but I've noticed this happens after creating a relation and reloading the server. The afterFetch hook for example just stops firing

**Comment by derrickmehaffy** [comment]
@kasonde all the lifecycle callbacks are considered "broken" there is already a PR that is linked to that other issue to fix them and will likely be in the next major release.
