### ISSUE TITLE
Error: SQLITE_ERROR: duplicate column name: id

### ISSUE THREAD

**Issue by deka** [strapi/strapi#6037]
**Describe the bug**
Some fields name are reserved but ui accept them, like 'id'

**Steps to reproduce the behavior**
In Content Type builder : 
- Create new collection
- Add field named id
- Server won't restart

**Expected behavior**
- A user message to inform that some fields are reserved.
- A lock to not save a field with a reserved name

**System**

Database: SQLite (default)

**Comment by derrickmehaffy** [comment]
closing duplicate: #4539

Though not directly related to "ID" it is a reserved word.
