### ISSUE TITLE
The inability to use Queries

### ISSUE THREAD

**Issue by redni** [strapi/strapi#604]
**Node.js version**:
v9.5.0

**npm version**:
5.6.0

**Strapi version**:
3.0.0-alpha.9.2

**Operating system**:
Arch Linux

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?** 
The inability to use Queries: where, sort, skip, limit. The system incorrectly replaces the entered get variables.

**If the current behavior is a bug, please provide the steps to reproduce the problem**

`GET http://localhost:1337/strapi?where={"name":"inder"}&sort={"name": -1}&skip=0&limit=1`

"Where" it did not work so I added:

`console.log (convertedParams)` to `fetchAll` function in `./api/strapi/service/Strapi.js`

In the console I received:
```
{ where: 
   { where: '{"name":"inder"}',
     sort: '{"name": -1}',
     skip: '0',
     limit: '1' },
  sort: '',
  start: 0,
  limit: 100 }
```
Quotas have been added to the entered variables, which should not be. By them, numbers are not read as numbers and JSON as JSON.

**What is the expected behavior?**
The console response should look like this:
```
{ where: 
   { where: {"name":"inder"},
     sort: {"name": -1},
     skip: 0,
     limit: 1},
  sort: '',
  start: 0,
  limit: 100 }
```
I've edited Strapi.js in Services and fetchAll function. By setting where, sort, skip and limit rigidly without quotes, everything works perfectly. I only checked unallocated variables like:
```
.where(convertedParams.where)
.sort({ "name": -1 }) //HERE
.skip(convertedParams.start)
.limit(convertedParams.limit)
```

 So I do not know if "where" should it be included in the next "where" in JSON? Should not it be like this?

```
 { 
     where: {"name":"inder"},
     sort: {"name": -1},
     skip: 0
  }
```

**Comment by Aurelsicoko** [comment]
@redni You're not using the right syntax in your URL. Take a look at the documentation https://strapi.io/documentation/guides/filters.html

**Comment by redni** [comment]
@Aurelsicoko Thank you, it works great. Next time I will look through the sources and documentation much more thoroughly before I write anything. I apologize and close the issue.
