### ISSUE TITLE
[SECURITY] Upgrade lodash on `strapi-plugin-graphql` to >=4.17.12

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#6042]
**Describe the bug**
In contrast to the other packages, `strapi-plugins-graphql` seems to be targeting lodash `4.17.11` instead of `^4.17.11`. This means a security vulnerability related to prototype pollution comes up when doing `yarn audit` because it can't be upgraded with `yarn upgrade`.

**Steps to reproduce the behavior**
1. Install Strapi
2. Run `yarn install`
3. Run `yarn audit`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/80922008-094c3980-8d72-11ea-829f-c6ccb55d3a7c.png)

**Code snippets**
*none*

**System**
- Node.js version: `v13.7.0`
- NPM version: `v6.13.6`
- Strapi version: `3.0.0-beta.20.1`
- Database: `MongoDB`
- Operating system: `Windows 10 1909 (WSL Ubuntu 18.04 LTS)`

**Additional context**
There also seems to be a vulnerability on `strapi-admin`.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by diogotcorreia** [comment]
Updated

**Comment by alexandrebodin** [comment]
Hi @diogotcorreia We merged a PR updating the dependency, This will be released in the next release. 

Closing the issue as resolved
